### ISSUE TITLE
[Bug] Issue with offers reversed in the beta wallet (made to buy xch by stably)

### ISSUE THREAD

**Issue by stuttgart82** [Chia-Network/chia-blockchain#10004]
### What happened?

Hi, When adding the created offers to "view offers", the transaction appears reversed. I want to convert 80 usd into 1 xch and create correctly my offer but when adding it, at the end, it summarize at "you offer 1 xch to get 80 usd....

### Version

chia wallet 1.2.11265

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
can you provide screenshots?

**Comment by stuttgart82** [comment]
[](url)

> can you provide screenshots?

![Capture d’écran 2022-02-04 095918](https://user-images.githubusercontent.com/98598714/152505071-e1c3bdf1-22ea-4f68-8b8d-0309a36aab93.jpg)
![Capture d’écran 2022-02-04 100030](https://user-images.githubusercontent.com/98598714/152505076-0907d98c-9a51-4dfd-bda8-984d8879724d.jpg)

**Comment by stuttgart82** [comment]
Still not solved... :/
