### ISSUE TITLE
[BUG] Plotter destination path incorrect.

### ISSUE THREAD

**Issue by tony-clark-fc** [Chia-Network/chia-blockchain#1001]
RC2 on Windows 10.  Issued the following command from PowerShell.  drive F: was definitely available, as I was able to manually copy the completed .tmp files to it.

> $args = 'plots create -k 32 -b 16000 -u 64 -r 4 -t "c:\temp" -d "f:\"';  powershell -noexit -Command "Start-Process ./chia.exe -argumentlist '$args'"

![image](https://user-images.githubusercontent.com/75770456/108685240-dfe1e180-752e-11eb-86d6-c545d60481df.png)

**Comment by tony-clark-fc** [comment]
I just looked at this again and I think I know what caused the problem.  __-d "f:"__ should probably be __-d "f:\"__.  I'll test and advise.

**Comment by tony-clark-fc** [comment]
NOTE: The command issued above is not displaying correctly (a bug in GIT)!  There is a backslash following the f: that isn't visible.

![image](https://user-images.githubusercontent.com/75770456/108687427-ad85b380-7531-11eb-950a-7b167bbe0763.png)

**Comment by mariano54** [comment]
Looks like there is a space after the f: for some reason

**Comment by tony-clark-fc** [comment]
Yep - that's the problem.  I suspect it doesn't like being directed to the root of the drive.  I've used the same command successfully using a destination of 'f:\plots'.

**Comment by berlef80** [comment]
I didn't have this issue previously, but it happened to me today as well.  Now plotting to a subfolder and it works fine
