### ISSUE TITLE
[Bug] offer history doesn't show CAT information 

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10018]
### What happened?

After an offer has been created (70 USDS for 1 XCH), under "offers you created", it shows "unknown CAT" instead USDS. and Unknown CAT for XCH.
Also the numeric values are off, it is showing 1,000,000,000 unknown cat instead of 1 XCH
<img width="1312" alt="Screen Shot 2022-01-29 at 12 07 05 AM" src="https://user-images.githubusercontent.com/93196638/151650438-2a0f244b-e394-489b-8e15-55d8db4e80f0.png">

### Version

1.2.12 dev 207

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
My suspicion is that the data cached by the useGetWalletsQuery() hook is being purged between calls.

**Comment by esaung** [comment]
Thanks Jeff, we can close this issue out for now since we've made some big changes into the 1.3 releases.
