### ISSUE TITLE
[Bug] while on wallet mode, a resync shows information from another wallet and other errors

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10024]
### What happened?

In wallet mode so only on the light client sync protocol, after accepting some offers I created and sending myself transactions, the wallet shows synced and eventually goes into a resyncing mode. When that happens, the GUI starts to display strange states (CLI shows the correct values while syncing):
1.) all balances in all wallets are zeroed out
2.) at one point it shows the balance from another wallet that has been setup
3.) it shows an error screen

eventually when it syncs up, the balances show correctly, but while that's happening it could be very confusing for users and what they see.

state before and after the syncing is complete:
<img width="1312" alt="Screen Shot 2022-01-29 at 1 09 15 AM" src="https://user-images.githubusercontent.com/93196638/151666645-28549551-49ee-4f86-af24-2d1d229298dc.png">

balances all show error while resyncing (GUI displays synced):
<img width="1312" alt="Screen Shot 2022-01-29 at 1 11 38 AM" src="https://user-images.githubusercontent.com/93196638/151666669-679d342b-10a8-42e0-baa6-d0635419a4be.png">

balances are showing from another wallet (did not change wallets):
<img width="1312" alt="Screen Shot 2022-01-29 at 1 11 47 AM" src="https://user-images.githubusercontent.com/93196638/151666698-da136fda-9410-47a2-b32d-e27a846273da.png">

what the CLI shows for the balances while it's syncing (these are the correct balances) and GUI shows 0 balance:
<img width="1512" alt="Screen Shot 2022-01-29 at 1 13 21 AM" src="https://user-images.githubusercontent.com/93196638/151666715-84fe365c-be5b-4813-87f5-06eda900f22b.png">

### Version

1.2.12 dev 207

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by HarunSMetin** [comment]
@esaung 
If this issue open to contribution. I would like to take part. But This is my first time contributing to an open-source project. Therefore, I need some guidance.

**Comment by mariano54** [comment]
@HarunSMetin yes you can definitely contribute! The first step is installing chia blockchain from source, and running the chia services. Then you can start changing some code and adding logging to see what is going on. I recommend using INFO logging and then you can print things using log.info(f"...."). 
Fixing a bug usually requires finding a way to replicate it consistently. Once you can do this, then just figure out where in the code it is failing. This one looks related to wallet_node.py.f

**Comment by HarunSMetin** [comment]
@mariano54 I would like to be assigned for this issue. I have installed chia. Now i am trying to understand how "wallet_node.py" works .

**Comment by emlowe** [comment]
Closing issue, resolved in 1.3
