### ISSUE TITLE
[Bug] text says "{Offerfilepath}" when viewing an offer file

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10020]
### What happened?

When viewing an offer file, we are showing "{offerfilepath}" instead of showing the path of the offer file. Also some other variables are showing where it shouldn't.
<img width="1312" alt="Screen Shot 2022-01-29 at 12 35 42 AM" src="https://user-images.githubusercontent.com/93196638/151650639-12e94748-7217-4540-a7d5-1d8e1a64e344.png">

<img width="1312" alt="Screen Shot 2022-01-29 at 12 58 16 AM" src="https://user-images.githubusercontent.com/93196638/151651458-a69d5d5a-9dcc-442d-84a2-dbd333161106.png">

### Version

1.2.12 dev 207

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
Fixed
