### ISSUE TITLE
[BUG] Websocket exception on harvester when plots are moved

### ISSUE THREAD

**Issue by PanzerKunst** [Chia-Network/chia-blockchain#1003]
**Describe the bug**
This bug was already reported on b27. I'm re-creating it, and giving details on how it happened on my system.

On a server I'm running plotter + harvester (remote).

In config.yaml I have several plot_directories, including:
- /dest
- /almost-empty

The server is running a plotter with `-d /dest`, and from time to time - before that disk gets full - I move several plots to `/almost-empty`. The move is done via `rsync`.

While one of those moving scripts was running, the harvester crashed, and the last log shows:
```
05:48:52.417 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panzerkunst/chia-blockchain/src/daemon/server.py", line 149, in safe_handle
    async for message in websocket:
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/panzerkunst/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Expected behavior**
The harvester can handle moving plots without crashing.

**Desktop (please complete the following information):**

- Chia version: 1.0rc2
- OS: Ubuntu 20.04

**Comment by cameroncooper** [comment]
I've also run into this a couple times.

**Comment by hoffmang9** [comment]
Can you confirm this was RC2?

**Comment by hoffmang9** [comment]
Wait - you did - nm

**Comment by wjblanke** [comment]
can you give us the dmesg hex dump for the crash?

**Comment by PanzerKunst** [comment]
@wjblanke dmesg:
```
[385024.379325] chia_harvester[58315]: segfault at 2 ip 00007fd0c2939701 sp 00007fd04b7fc998 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7fd0c28cd000+b7000]
[385024.379342] Code: 39 c6 75 e5 31 c0 c3 66 90 c3 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00 00 41 57 48 01 fe 41 56 48 8d 46 fd 41 55 41 54 55 53 <66> 41 83 78 02 00 48 89 44 24 b8 48 c7 c0 fd ff ff ff 48 89 7c 24
```

**Comment by wjblanke** [comment]
yes it is, and it is in chiapos so should be able to track it down. more to come and thanks!

**Comment by wjblanke** [comment]
Sigh, same place as last time (DTableH->fastMode). I thought the error checking would take care of the NULL FSE_DTable here. Maybe it is coming from somewhere else.

000000000006c6f0 <FSE_decompress_usingDTable@@Base>:
   6c6f0:       41 57                   push   %r15
   6c6f2:       48 01 fe                add    %rdi,%rsi
   6c6f5:       41 56                   push   %r14
   6c6f7:       48 8d 46 fd             lea    -0x3(%rsi),%rax
   6c6fb:       41 55                   push   %r13
   6c6fd:       41 54                   push   %r12
   6c6ff:       55                      push   %rbp
   6c700:       53                      push   %rbx
SEGFAULT (DTableH->fastMode?)  6c701:       66 41 83 78 02 00       cmpw   $0x0,0x2(%r8)
   6c707:       48 89 44 24 b8          mov    %rax,-0x48(%rsp)
   6c70c:       48 c7 c0 fd ff ff ff    mov    $0xfffffffffffffffd,%rax
   6c713:       48 89 7c 24 c0          mov    %rdi,-0x40(%rsp)
   6c718:       48 89 74 24 b0          mov    %rsi,-0x50(%rsp)
   6c71d:       0f 85 6d 03 00 00       jne    6ca90 <FSE_decompress_usingDTable@@Base+0x3a0>
   6c723:       48 85 c9                test   %rcx,%rcx
   6c726:       0f 84 c7 02 00 00       je     6c9f3 <FSE_decompress_usingDTable@@Base+0x303>
   6c72c:       48 8d 42 08             lea    0x8(%rdx),%rax

size_t FSE_decompress_usingDTable(void* dst, size_t originalSize,
                            const void* cSrc, size_t cSrcSize,
                            const FSE_DTable* dt)
{
    const void* ptr = dt;
    const FSE_DTableHeader* DTableH = (const FSE_DTableHeader*)ptr;
    const U32 fastMode = DTableH->fastMode;

    /* select fast mode (static) */
SEGFAULT    if (fastMode) return FSE_decompress_usingDTable_generic(dst, originalSize, cSrc, cSrcSize, dt, 1);
    return FSE_decompress_usingDTable_generic(dst, originalSize, cSrc, cSrcSize, dt, 0);
}

    static std::vector<uint8_t> ANSDecodeDeltas(
        const uint8_t *inp,
        size_t inp_size,
        int numDeltas,
        double R)
    {
        if (DT_MEMO.find(R) == DT_MEMO.end()) {
            std::vector<short> nCount = Encoding::CreateNormalizedCount(R);
            unsigned maxSymbolValue = nCount.size() - 1;
            unsigned tableLog = 14;

            FSE_DTable *dt = FSE_createDTable(tableLog);
            size_t err = FSE_buildDTable(dt, nCount.data(), maxSymbolValue, tableLog);
            if(err != FSE_error_no_error)
                throw std::logic_error("FSE_buildDTable failed");
            DT_MEMO[R] = dt;
        }

        std::vector<uint8_t> deltas(numDeltas);
        size_t err = FSE_decompress_usingDTable(&deltas[0], numDeltas, inp, inp_size, DT_MEMO[R]);


FSE_buildDTable should have succeeded... Hmmm...

**Comment by wjblanke** [comment]
With address 2 it is definitely a NULL dereference on the fastMode comparison. I'm not sure how dt and thus DT_MEMO[R] can be NULL if FSE_createDTable worked though.

**Comment by wjblanke** [comment]
DT_MEMO (and CT_MEMO) are globals. Maybe there is some thread safety issue there with multiple provers creating and destroying entries. I'm not sure how python multithreading affects it.

**Comment by mariano54** [comment]
Ohh good point. I think we release the python GIL in chiapos for efficiency in the python bindings, so it could be two threads accessing it at the same time

**Comment by PanzerKunst** [comment]
FYI I experienced the exact same exception, and same dmesg, by restarting a running harvester (`chia start harvester -r`).
So it seems it's not limited to moving plots...

**Comment by hoffmang9** [comment]
We think we just figured out what is going on. Will attempt to fix.

**Comment by mariano54** [comment]
This is hopefully now fixed by the new chiapos. We will have to confirm on the next testnet

**Comment by hoffmang9** [comment]
Should be fixed by RC4. Closing under that assumption - re open if we're wrong.
