### ISSUE TITLE
not able to farm not found plots

### ISSUE THREAD

**Issue by ProfyTourny** [Chia-Network/chia-blockchain#1004]
Dear
I am plotting on a  PC and farming on Raspberry Pi 3
I use external HDD 
I added directory on HDD where plot are
They are recognized in Not plot found
but i cannot farm them
when i click the three dots beside the plot it just lists Delete
Kindly

**Comment by mariano54** [comment]
You need to add the keys that you used for plotting, into your farming machine. 
use `chia keys show` and `chia keys add -m`, or get the 24 words from the keys menu.
