### ISSUE TITLE
Issue with Latest Block Challenges

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain#1005]
Hi,

In the Farm Tab, in the Latest Block Challenges its showing allot of completed challenges as per the screenshots.  

![image](https://user-images.githubusercontent.com/36589806/108577270-2b985d80-736c-11eb-859b-3d1f22f47e9d.png)

To get it to update i have to do a forced reload, but even then, it still shows allot of block challenges

![image](https://user-images.githubusercontent.com/36589806/108577328-60a4b000-736c-11eb-9f49-e9aac53ca68f.png)

I am running RC2 with Windows 10

**Comment by hoffmang9** [comment]
I think RC5 fixed this but re-open if spotted again.

**Comment by shaneo257** [comment]
Nope, still getting the same issue on RC5 as well
![image](https://user-images.githubusercontent.com/36589806/110304963-e94b6d80-8047-11eb-8c67-c7685fa676d4.png)

**Comment by shaneo257** [comment]
after i do a reload
![image](https://user-images.githubusercontent.com/36589806/110305053-041de200-8048-11eb-8cd3-3de0a6cc7fe4.png)

**Comment by hoffmang9** [comment]
The issue/enhancement here is that we should probably cap the total history of Latest Block Challenges to a fixed amount. That said, Latest Block Challenges should go away completely or be merged with Last Attempted Proof.

**Comment by mariano54** [comment]
This is covered by this:
https://github.com/Chia-Network/chia-blockchain-gui/issues/50
