### ISSUE TITLE
[Bug] fake plots affect whole net

### ISSUE THREAD

**Issue by smurfjack** [Chia-Network/chia-blockchain#10059]
### What happened?

Someone is developing several versions of fake plots,and is winning blocks every minutes,may be direct the verify proc to a certain normal plot,even the fake plots can pass through and win blocks.the timelord shows reward not on the chain 3 times a minute.and normal solo users or nft users affected very badly.
 

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by smurfjack** [comment]
timelord chia.timelord.timelord : WARNING Will not infuse 4f744e73ccac152d487711bcceaa28bb88963e923d183f21c412a262095dcf38 because its reward chain challenge is not in the chain

**Comment by smurfjack** [comment]
The fake heights are 1491201 wins 0.024894
1490377 wins 0.25 1490087 wins 0.022756

**Comment by mariano54** [comment]
No these are not fake plots. Sometimes people are slow sending their blocks, so small forks are created. The only people affected will be those that have slow harvesters / slow lookup times, and are not able to get their blocks in the 28 second time limit. Not a bug.
