### ISSUE TITLE
Trade issues

### ISSUE THREAD

**Issue by aaronscientiae** [Chia-Network/chia-blockchain#1006]
A beginner so forgive my dumb.
I have 2 txch so I made a colored coin and it showed up with 250,000,000 in the cc wallet. I sent 1000 to txch1q53s652mf7qg5g2aneq92xpzk22ds6t8fcva0ag6pzut394d6xwqks27m6 as well as .25 txch to them as well. They both got it. 
I created a trade of 1000000 of my cc wallet coins and (attached is the offer file) but when they tried to import the offer they got 
'>' not supported between instances of 'NoneType' and 'int'
Not sure if this helps.
 I checked my colored coin and now the balance is 249,999,000 but spendable is 0. The GUI loses me because there are such vast different orders of magnitude of numbers and I don't know what is in what denomination.

[offer1.zip](https://github.com/Chia-Network/chia-blockchain-gui/files/6018239/offer1.zip)

![image](https://user-images.githubusercontent.com/1449658/108634546-dec98b00-742e-11eb-8ae5-afb903ed3224.png)
![image](https://user-images.githubusercontent.com/1449658/108634552-e7ba5c80-742e-11eb-871f-7b04b9705dcf.png)

**Comment by emlowe** [comment]
Closing this issue, as it has no bearing on new work regarding CATs to replace colored coins
