### ISSUE TITLE
Wallet not syncing in fast mode Linux dev 233[Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#10073]
### What happened?

I'm running 1.2.12 dev 233 on a VM with a fresh install of Ubuntu 20.04. I installed Chia using dpkg with the .deb installer.

I started the GUI in Farming Mode. The wallet is syncing from 0. This was not the case in the previous dogfooding build, where the wallet synced rapidly in Farming Mode. Note that the GUI shows Not Synced with the latest block (see image). Also see the attached INFO log file.

![wallet_sync](https://user-images.githubusercontent.com/69756004/152119822-c1a64616-769d-46a9-a2d0-001644419005.png)

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7984777/debug.log)

### Version

chia-blockchain_1.2.12.dev233_amd64.deb

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
See log file attached above.
```

**Comment by bolshoytoster** [comment]
@danieljperry from the logs it looks like it can't find any keys, could you run `chia keys generate` and try again?

**Comment by danieljperry** [comment]
The wallet did eventually sync, but I'm not sure exactly when. The full node is still syncing, so I think this is a different problem than what I initially thought. I now believe this is simply a "long time to sync" issue.

For the record, I installed and ran Chia on a new Ubuntu VM. I initially generated a new key in the GUI, so there are zero previous transactions. I did not need to run `chia keys generate` in order for the wallet to sync. New log file attached.

[Uploading debug.zip…]()

**Comment by danieljperry** [comment]
The zipped log file never updated, so here is the uncompressed original:

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7990987/debug.log)

**Comment by bolshoytoster** [comment]
@danieljperry this is likely unrelated to this issue, but the logs show a syntax error in a sql command.

**Comment by esaung** [comment]
@danieljperry - is the issue that it took a long time to sync with a newly generated wallet?

**Comment by esaung** [comment]
@Yostra - FYI...

**Comment by danieljperry** [comment]
The issue that still exists is a refresh problem, which is documented elsewhere. The wallet does sync properly now.
