### ISSUE TITLE
[BUG] [MARMOT]

### ISSUE THREAD

**Issue by thechiaplot** [Chia-Network/chia-blockchain#10074]
### What happened?

6C2C001388F352685B11687280626963888F37A5082BD86D457F99216C3B2591

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
please dont remove for a day, part of Groundhog Day Marmot Hunt - blaktron
```

**Comment by esaung** [comment]
all done.
