### ISSUE TITLE
sending coins then shows spendable balance 0

### ISSUE THREAD

**Issue by aaronscientiae** [Chia-Network/chia-blockchain#1007]
I had 2 txch and made .25 into a colored coin and .25 I sent to someone, then I sent .1 and .1 but then my spendable balance on colored coin shows 0 and now spendable balance on main wallet is 0. Then someone sent me some coins and I have those, but still showing 1.15 unspendable.
![image](https://user-images.githubusercontent.com/1449658/108635056-d3c42a00-7431-11eb-9f83-edd5ea9dd1f4.png)
![image](https://user-images.githubusercontent.com/1449658/108635062-dcb4fb80-7431-11eb-81f9-d87034824c61.png)
coloured wallet
![image](https://user-images.githubusercontent.com/1449658/108635065-e2aadc80-7431-11eb-9611-828fbd74522b.png)
![image](https://user-images.githubusercontent.com/1449658/108635068-ec344480-7431-11eb-8c19-7855d33a719c.png)

**Comment by emlowe** [comment]
Closing this issue, as it has no bearing on new work regarding CATs to replace colored coins
