### ISSUE TITLE
GPU errors when starting GUI on Ubuntu Linux [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#10072]
### What happened?

On an Ubuntu 20.04 VM, fresh OS install, never installed Chia before on this system.
I installed the Chia's .deb using dpkg from the command line.
Upon running chia-blockchain, I got 3 GPU errors (see log output). These errors don't seem to affect Chia, and they may be out of Chia's control. If this is the case, it would be nice to suppress them from showing in the CLI (logging them would be fine) because an end user might think something is wrong with Chia.

### Version

chia-blockchain_1.2.12.dev233_amd64.deb

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
djperry@UbuntuNew:~$ chia-blockchain &
[1] 2399
djperry@UbuntuNew:~$ Running python executable: 
child process success
[2433:0202/155659.335365:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[2471:0202/155659.410107:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[2444:0202/155659.444446:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

**Comment by bolshoytoster** [comment]
@danieljperry according to [this](https://github.com/YoongiKim/AutoCrawler/issues/31#issuecomment-751690395) comment, you might fix it by updating your GPU drivers:
```sh
sudo apt update
sudo apt upgrade
reboot
```
If it doesn't work then you could try using the propreitary drivers if you have an nvidia GPU. It's probably easiest to do this with the GUI. Run `software-properties-gtk --open-tab=4`, select the top one and `Apply Changes`.

**Comment by danieljperry** [comment]
I have tried both of these suggestions, but the errors still occur. This doesn't seem to affect Chia at all, so I think (if possible) the errors should be logged and not displayed in the CLI.

**Comment by esaung** [comment]
@AmineKhaldi - can you take a look at this and follow up with @danieljperry ?

**Comment by emlowe** [comment]
These errors are from chromium/electron - We could consider turning off app.disableHardwareAcceleration(), but that would disable it everywhere. Might see if there is a way to just redirect those somewhere

**Comment by seeden** [comment]
It is already disabled via https://github.com/Chia-Network/chia-blockchain-gui/commit/43f5ab15664537847cfb7a43487f902f9ed8c5dd
