### ISSUE TITLE
[Bug] Share offer dialog pops up twice

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10099]
### What happened?

when clicking on share offer dialog, two dialog pop up
<img width="1312" alt="Screen Shot 2022-02-03 at 3 30 35 PM" src="https://user-images.githubusercontent.com/93196638/152432318-f03042cb-9a8e-4ea1-813b-4f857664b40d.png">
.

### Version

1.2.12 dev 233

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
Fixed
