### ISSUE TITLE
White screen on startup with v1.2.12246

### ISSUE THREAD

**Issue by JonRosenSystems** [Chia-Network/chia-blockchain#10110]
![image](https://user-images.githubusercontent.com/1927724/152581183-a418a1ca-9af2-409b-b018-c41c2547e9cf.png)

**Comment by esaung** [comment]
what version of the client is this on?

**Comment by JonRosenSystems** [comment]
Windows 10

**Comment by Riyadaljuboory** [comment]
Same issue since a week
