### ISSUE TITLE
[Bug] Confirmed Offer cause XCH stuck in pending state

### ISSUE THREAD

**Issue by ytx1991** [Chia-Network/chia-blockchain#10124]
### What happened?

I accepted one offer about sell 6.25 XCH for 500 USDS. The offer is confirmed and I received the USDS. But there are 18.75 XCH stuck in the pending state forever. It's not the first time, usually delete the wallet database and wallet peers database then resync will solve this.

The original coin has 25 XCH, the new coin has 18.75 XCH (25-6.25), but it didn't collect by the wallet. I have attached suspicious logs.

### Version

light wallet 1.2.11265

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-02-05T11:32:40.126 wallet chia.wallet.wallet         : WARNING  Record: {'additions': [{'amount': 18750000000000,
                'parent_coin_info': '0x5f582438f924e0643795c65bcd862edc8c5533e19669e75dd4c34619ce07f5b0',
                'puzzle_hash': '0xa747b85d200b57a2b6ddda60ae38299bc914bc3d9a7c61d165ea7cd08770cd9b'}],
 'amount': 6250000000000,
 'confirmed': False,
 'confirmed_at_height': 0,
 'created_at_time': 1644089551,
 'fee_amount': 0,
 'memos': [],
 'name': '0x9b839f4e020ae69da7b7f127bb2fe5c6d229b82fbad7ae2c4ea76e6b1e386398',
 'removals': [{'amount': 25000000000000,
               'parent_coin_info': '0x781edbef25ad68dcc338b8857de6e31f3be307e7f001968bde580b0b30a1f95e',
               'puzzle_hash': '0x84beb46a8fb40f883fdba21a411993f250ee9333e782a9d551d9993ef36f7b14'}],
 'sent': 0,
 'sent_to': [],
 'spend_bundle': None,
 'to_puzzle_hash': '0x0101010101010101010101010101010101010101010101010101010101010101',
 'trade_id': '0x332256313b60d6783120105603f87d8e4e321e3f3030a65632ecc8fb7b6bd80e',
 'type': 5,
 'wallet_id': 1} not in mempool, []
```

**Comment by JustinCheng0509** [comment]
Issue "Solved" by delete the wallet & Peers DB and resynced. Possible wallet db issue and some bad peers.
