### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by doomogi** [Chia-Network/chia-blockchain#10144]
### What happened?

![image](https://user-images.githubusercontent.com/11176824/153010008-96b84c55-d0cb-4bb7-aba6-5ecedc5b528b.png)

offer bug?

There is no change in the pending balance after the offer.

### Version

CHIA Wallet 1.2.11265

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
Can you tell us what you did with the offers? Do you have any open offers or offers you accepted?

What do you expect to see?

**Comment by doomogi** [comment]
After the walnet update, I saw an offer that was not shown in the offer creation list, so it is working normally after deleting it.
However, wallet synchronization is not working and the pending balance is still the same. First, I will watch for about a day and send you an e-mail again if there is no change.

Using a translator.
Windows용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 발송된 메일입니다.

________________________________
보낸 사람: esaung ***@***.***>
보낸 날짜: Friday, February 11, 2022 6:53:58 AM
받는 사람: Chia-Network/chia-blockchain ***@***.***>
참조: doomogi ***@***.***>; Author ***@***.***>
제목: Re: [Chia-Network/chia-blockchain] [Bug] (Issue #10144)


Can you tell us what you did with the offers? Do you have any open offers or offers you accepted?

What do you expect to see?
