### ISSUE TITLE
[Bug] content updates

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10155]
### What happened?

The following content strings need to be updated:
1.) upon quitting the Chia app, we need to update the content to be more generic. current content says, "Are you sure you want to quit? GUI plotting and farming will stop."
<img width="1060" alt="CleanShot 2022-02-21 at 09 56 19@2x" src="https://user-images.githubusercontent.com/663017/154998802-b4c8e70b-329b-4655-a7df-37b788826013.png">

2.) update content on the farmer/wallet selection home screen

3) Update the text in the walled dropdown from "Chia Wallet" to "Chia"

4) The Chia wallet should have "XCH" instead of the Chia logo to be more consistent with the other wallet types. 
<img width="506" alt="CleanShot 2022-02-21 at 10 01 46@2x" src="https://user-images.githubusercontent.com/663017/154999348-7f310ad9-126a-4572-88de-b06d9b16220e.png">

5.) modify the default content from "CAT Wallet" to "Chia Asset Token"
![Screen Shot 2022-02-25 at 3 51 31 PM](https://user-images.githubusercontent.com/93196638/155808076-143f5c1f-2b32-4ccb-a492-09052c4231da.png)

### Version

1.2.12 dev 263

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by sethjenks** [comment]
2) Update the text in the walled dropdown from "Chia Wallet" to "Chia"
3) The Chia wallet should have "XCH" instead of the Chia logo to be more consistent with the other wallet types.

**Comment by seeden** [comment]
Updated via https://github.com/Chia-Network/chia-blockchain-gui/commit/b9b8c51249ab70b18b93e1383a37a34a71526602
