### ISSUE TITLE
[Bug] 1.3 beta wallet: incorrect balances, broken DB migration paths

### ISSUE THREAD

**Issue by ojura** [Chia-Network/chia-blockchain#10194]
### What happened?

I tried out the 1.3 beta today on my full node/farmer setup. I observed the following issues:

Wallet DB migration from 1.2.11: very borked, only the standard Chia wallet recreated  -- not even the standard CATs like Spacebucks or Stably.
The Chia wallet had an incorrect balance (it showed the amount of only the last incoming transaction in my case as the entire balance).
The pooling wallet was not recreated.

Wallet DB migration from light wallet beta: The pooling wallet was not recreated

The symptoms of the pooling wallet not being recreated (observed in both migration paths):
- `POOLING_WALLET` not showing up in `chia wallet show`
- empty `chia plotnft show`
- Pool tab in the GUI shows the NFT, but instead of the green "Change pool" button, there's "This plot NFT is assigned to a different key. You can still create plots for this plot NFT, but you can not make changes."

Mitigation which restored full functionality for me: 
- deleted the wallet DB folder contents (in both cases);
- synced the 1.3 beta wallet from scratch (this was quick because I had a full node running; full node DB migration to v2 went without issues!)
- re-added all of my CATs
- manually copied over the `trade_records` table from the light wallet beta DB to preserve my offers

### Version

1.3 beta

### What platform are you using?

Linux

### What ui mode are you using?

GUI/CLI

**Comment by wallentx** [comment]
I believe this is also what I experienced after a DB upgrade. I pool with chiahub.io, and I saw that my config.yaml pooling section did not have my pool url in place, and `chia plotnft show` showed that I was self pooling. @yan74 (much thanks :pray:) verified that they had my singleton in their db as a member.

Correcting the config.yaml caused the farmer and wallet to crash upon startup with the following:
``` process, pid_path = launch_service(self.root_path, exe_command)
  File "/home/william/chia-blockchain/chia/daemon/server.py", line 1280, in launch_service
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia_wallet'
2022-02-12T03:34:56.487 daemon chia.daemon.server         : INFO     chia daemon exiting in 5 seconds
2022-02-12T03:34:56.489 daemon chia.daemon.server         : INFO     Daemon WebSocketServer closed```

Re-syncing my wallet now to see if I can get things back to a working state

**Comment by wallentx** [comment]
To follow up, I deleted the contents of the wallet db folder, and that let me start my farmer without the previously mentioned error log. Something still seems very strange, but I am sending partials back to the pool now.

**Comment by ojura** [comment]
noticed another one in the wild on Keybase
![image](https://user-images.githubusercontent.com/9062353/153779320-a567a1b0-b2fc-43b0-9972-c799b708f397.png)

**Comment by ojura** [comment]
Some additional 1.3 beta wallet wonkiness which is probably related to this issue: I have a single-issuance CAT with a fixed total supply of 10: https://www.spacescan.io/xch/cat1/1cc8af1c4aee5974dd2655ef0c40709ead5bc57b899b636a38446c50fb13da50

After some sending some mojos back and forth, here's what my wallet shows:
![image](https://user-images.githubusercontent.com/9062353/153880143-b68537fa-e8e3-424b-9d82-0a37498a5b1a.png)

So apparently I forged a mojo of this fixed-supply single issuance CAT according to my v2 wallet. However I know this is not the case based on my manual accounting.

I have archived the wallet DB which ended up in this strange condition and will try to analyse it Soon (TM).
It's my dev throwaway wallet; I can share privately with Chia Network if there's interest.

**Comment by wallentx** [comment]
I've tried for days to replicate the behavior that I was seeing initially, but have been unable to- https://github.com/Chia-Network/chia-blockchain/issues/10439. My issue was experienced with the first beta release, and I believe whatever may have caused it has likely since been fixed.

**Comment by ojura** [comment]
Yeah, I deleted my v1 wallet DB and cannot reproduce anymore.

I think I do however have a wallet DB from the light wallet beta times which is missing the plot NFT coin. If the light beta messed up and forgot to add the plotnft singleton coin to the wallet DB, is it a bug of 1.3 that it mistakenly believes that the wallet is "synced" to a certain height because the wallet DB says so?

Should we have a "sync from scratch" button in the UI if the user believes they're missing some coins?

**Comment by paninaro** [comment]
Since this report is fairly comprehensive, and several fixes have gone in relating to the points mentioned, I'm going to close this out. If specific issues persist, please feel free to open individual reports for those issues.
