### ISSUE TITLE
[Enhancement] - better resource management when users switch from farmer to wallet

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10198]
User's may not be aware that if they are in farmer mode and switch to wallet mode that resources will still continue to be used to sync the full node in the background.

the enhancement will cover improving the GUI experience to better notify the user what is happening when switching from farmer to wallet mode and shutting off the farmer, harvestor, and full node services.

the workaround this is currently to switch the wallet mode, and close and relaunch the app. This will make the wallet fall back to just the light wallet sync without consuming additional resources syncing the full node.

**Comment by mariano54** [comment]
Why not just stop the farmer, harvester and full node instead?

**Comment by esaung** [comment]
good point, I updated the issue. we'll still need some GUI work as it will take some time to shut down the services.

**Comment by arvidn** [comment]
my understanding is that the main challenge is that we (currently) don't have clean shutdowns. We don't always await all tasks for instance. I imagine a clean shutdown for all components would be a prerequisite to switch between farmer <-> wallet mode cleanly.

I believe kyle has made some efforts to improve some places

**Comment by emlowe** [comment]
Moved to Jira back log tracking - closing issue
