### ISSUE TITLE
[Bug] Cancelled CAT offers stuck in pending, wrong amount was locked

### ISSUE THREAD

**Issue by jcheng0509-Chia** [Chia-Network/chia-blockchain#10191]
### What happened?

I have created these three offers and cancelled them all during testing. 
![image](https://user-images.githubusercontent.com/93954044/153569199-9577be8f-815d-4839-8c42-fbe213dd99bc.png)
It has been two days, my Crypto Shibe is still stuck with the correct amount 
![image](https://user-images.githubusercontent.com/93954044/153569334-b1a33e6b-fe52-49cc-882e-df4455414d7b.png)
While the SBX was locked at a very large number. 
![image](https://user-images.githubusercontent.com/93954044/153569435-f24d617b-1519-45e7-9a94-5cddd08d3e2e.png)
![image](https://user-images.githubusercontent.com/93954044/153569447-d9ed068d-decf-4855-ba4b-f116b32e4d81.png)

While I am currently using 1.2.12.269, this was performed on earlier beta version (not sure if its 267 or 266)

### Version

1.2.12.269

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Yongling01** [comment]
@wjblanke @paulhainsworth-chia @RWilsonChia
Looks this is similar issue as below.
https://github.com/Chia-Network/chia-blockchain/issues/9875

**Comment by emlowe** [comment]
Closing issue as we believe the large majority of issues are fixed in 1.3 release - please reopen if you have problems with 1.3
