### ISSUE TITLE
I've just saw a message about 1.3 beta and upgraded (but i didn't understand why upgrade file name  is 1.2.12269 and not 1.3...)

### ISSUE THREAD

**Issue by seanb95531** [Chia-Network/chia-blockchain#10209]
I've just saw a message about 1.3 beta and upgraded (but i didn't understand why upgrade file name  is 1.2.12269 and not 1.3...)
I have a farmer's pc with 1 key/wallet and 3 farmer nodes.
In early versions it was 1 xch address for all 3 nodes and 1 equal balance. Now its shows 3 different "recieve address", 3 different balances (for the same wallet). i can;t see transactions from one node in another, one transaction was gone to nowhere (~0.5 xch,  but it's still very disappointing).
So, how to fix it? Remove all data (include db, wallet and client) from pc, install old client and sync from memkeys? On all nodes? Will it help?

Sorry for my English, now in my native Russian:
Друзья, помогите. Обновился до бетки (правда, почему то, на странице загрузке версия 1.2.12269, а не 1.3 - хотя по тексту говориться об 1.3).
У меня ферма из 3х компов, основной ставил просто, 2 вспомогательных - по инструкции для дополнительных фермеров. Все было замечательно, все фармилось на пул, везде все было синхронно. Но вот после обновления начался какой-то ужас - на всех 3 компах показывает разный баланс, разный адрес для получения, исходящие транзакции отнимают баланс именно у данного фермера, при этом часть транзакции на обновленных компах уходят в "никуда" (те, которые были отправлены на "старые" адреса, которые были до обновления клиента... Потерял так 0,5 xch - обидно). Про пул пишет, что "Этот участок NFT привязан к другому ключу." - причем это на всех обновленных клиентах так.
Что делать то? Как вернуть весь этот зоопарк обратно, учитывая что я и бд обновил? Полностью все грохнуть и зачистить, включая bd и wallet, восстановить все с memkey и дождаться полной синхронизации? Или есть способ попроще?

_Originally posted by @MiniGamer21 in https://github.com/Chia-Network/chia-blockchain/discussions/10208_

**Comment by esaung** [comment]
1.3 betas are versioned with 1.2.12 XXX. Try the latest 1.3 beta 3 (1.2.12 dev355) and let us know
