### ISSUE TITLE
[enhancement] - improve sync status reporting to better communicate

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10200]
With the addition of the light wallet sync protocol and the full node sync merged together in the 1.3 beta how the sync status is reported can be improved to better represent and help users understand where the wallet is in terms of syncing up.

The enhancement would improve the types of states that we report while syncing to give users a better indication where they are at in the sync process.

**Comment by mariano54** [comment]
This requires a backend change, to send back a string that shows progress of applying each CoinState.

**Comment by sethjenks** [comment]
Here is a link to the Figma file with the recommended UI changes: https://www.figma.com/file/WEms0gjFT82wz5XV3U2yuN/Syncing-Status?node-id=5%3A67

**Comment by emlowe** [comment]
Closing issue -
