### ISSUE TITLE
Balances not showing in 1.3 beta [Bug] 

### ISSUE THREAD

**Issue by hydro28** [Chia-Network/chia-blockchain#10211]
### What happened?

New beta wallet shows synced, but balances for Chia and all CATs are zero. 

Looks like still fetching older blocks on the log. Not sure if this is normal when already showing a status of synced 

Lite wallet only installed. 

### Version

1.3 beta wallet 

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by hydro28** [comment]
My wallet had a lot of transactions. Someone of Keybase (skwee) with a similar situation tried raising initial_num_public_keys to 500, which restored normal balances. This did not work for me.

**Comment by esaung** [comment]
try 1.3 beta 3 that was release yesterday and let us know if you are still having an issue.

**Comment by emlowe** [comment]
We believe substantially all issued fixed in the 1.3 release - please try the released 1.3 and re-open issue if you continue to have problems

**Comment by hydro28** [comment]
Yes, all is working! Thank you.
