### ISSUE TITLE
[Bug] Block height 1562512 not found in chain

### ISSUE THREAD

**Issue by luis360** [Chia-Network/chia-blockchain#10225]
### What happened?

I cannot get block data, occurred error:  Block height 1562512 not found in chain. restarting the node still cannot get block data

log: 
Cannot connect to host 240e:3a1:5051:2590:edcf:757c:6c52:4b00:8444 ssl:<ssl.SSLContext object at 0x7f6295d15c40> [Cannot assign requested address
KeyError: b'\xd7\x80\xd2,z\x87\xc9\xe0\x1d\x98\xb4\x9a\t\x10\xf6p\x1c;\x95\x01WA1k?\xda\x04.]{\x81\xd2'

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by esaung** [comment]
try 1.3 beta and let us know if you are still experiencing issues?

**Comment by emlowe** [comment]
Please upgrade to 1.3 release and re-open if you have further issues
