### ISSUE TITLE
Date format in 1.3 beta only shows MM/DD/YYYY [Bug] 

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain#10223]
### What happened?

The date format in `Full Node` of the client shows as `MM/DD/YYYY` and doesn't use the time format of the OS, this can be particular confusing for users that use a different format, ie `DD/MM/YYYY`

### Version

1.3 Beta

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/commit/7f71e668f1e5b4ebe22f3cf4cd62738bf8d859f4
