### ISSUE TITLE
Cancelled offer transaction shows a full coin amount instead of the offered amount

### ISSUE THREAD

**Issue by jcheng0509-Chia** [Chia-Network/chia-blockchain#10234]
Cancelled Transaction History was showing the full coin amount instead of the amount I was trying to send out to. 
Previously stuck in this stage:
![image](https://user-images.githubusercontent.com/93954044/153956287-3fb46058-abad-4806-b808-39b80fefef6f.png)

After fully syned up, still showing pending, pending offer was caused due to a cancelled offer transaction. 

![image](https://user-images.githubusercontent.com/93954044/153955923-4b492cc7-fa7d-4ab9-9e74-ec2da1e42528.png)
And it would stuck in either pending or confirmed with the wrong amount when start the client. 

Pending state causing balancing showing the coin locked
![image](https://user-images.githubusercontent.com/93954044/153964505-a489b312-8265-4c56-9feb-308e6d748928.png)

![image](https://user-images.githubusercontent.com/93954044/154147023-155151c0-2b26-43f9-b7b4-5342dca8e166.png)
After updated to the newest version, transaction history is still too messy and doesn't make sense. and the balance sheet is showing weird numbers as well. 
![image](https://user-images.githubusercontent.com/93954044/154147144-8c9e4e48-e271-42b4-a32b-30435965356c.png)

**Comment by esaung** [comment]
@jcheng0509-Chia - is the SBX coin being locked up because of an offer or a transaction? if an offer, what is the amount that is supposed to be locked up in the offer? what are the SBX amounts you are expecting to see?

**Comment by jcheng0509-Chia** [comment]
> 

it was locked up due to an offer. supposed to be 0.001 sbx instead of 75223.212

**Comment by paninaro** [comment]
@Quexington has a fix for this: PR #10538
