### ISSUE TITLE
[Enhancement] - Allow users to copy and paste their mnemonic.

### ISSUE THREAD

**Issue by sethjenks** [Chia-Network/chia-blockchain#10250]
### What happened?

Users should be able to paste their 24 words from the clipboard to add their key into a wallet.
<img width="582" alt="CleanShot 2022-02-15 at 15 54 21@2x" src="https://user-images.githubusercontent.com/663017/154163579-8061eb2f-21f2-436e-9d87-189e332b8672.png">
<img width="600" alt="CleanShot 2022-02-15 at 15 54 25@2x" src="https://user-images.githubusercontent.com/663017/154163588-7a240a30-3902-4d8c-9afd-b617c8926036.png">
 

Figma File: https://www.figma.com/file/jblgntMG9CvfNyAXFOnq3V/1.3-Mnemonic-Update?node-id=0%3A1

Also add a copy button that copy all 24 word mnemonic to the clipboard so that user can CTRL-v/CMD-V the mnemonic

![Screen Shot 2022-02-25 at 10 11 43 AM](https://user-images.githubusercontent.com/93196638/155748899-7e8b9d8b-1ed8-46c8-9188-a3afc9c25018.png)

![copy-mnemonic](https://user-images.githubusercontent.com/663017/155775751-1b964286-937a-407a-8418-edf8cf52a3f5.png)

### Version

1.2.12

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
This is a good enhancement. Can we make this copy AND paste?

**Comment by lipalong** [comment]
This was added here: https://github.com/Chia-Network/chia-blockchain-gui/pull/673

**Comment by emlowe** [comment]
Closing issue
