### ISSUE TITLE
[Bug] Key migration does not remove key from Python keyring

### ISSUE THREAD

**Issue by ojura** [Chia-Network/chia-blockchain#10267]
### What happened?

After key migration is performed, the old keys are still stored unprotected in `~/.local/share/python_keyring/cryptfile_pass.cfg`.

### Version

1.3 beta

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Yes, this is on purpose as we want to allow for some more releases easy downgrade.

We will remove this in a future release
