### ISSUE TITLE
[Bug] Syncing issues in 1.2.11

### ISSUE THREAD

**Issue by foadmenbari** [Chia-Network/chia-blockchain#10298]
### What happened?

Yesterday i update to 1.2.11
In full node tab all field show loading icon
And mining not work
And plot are syncing yellow color

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Please include a screenshot and log details - there are insufficient details in this report to take any action
