### ISSUE TITLE
[Bug] chia plotnft leave --id 2 --fee INTEGER unintentionally thinks its -f fingerprint

### ISSUE THREAD

**Issue by GrayTsar** [Chia-Network/chia-blockchain#10314]
### What happened?

The cli incorrectly uses the option -f for fingerprint
instead of --fee for transaction fee

Expected command: chia plotnft leave --id 2 --fee 50000000
Actuall command thats called: chia plotnft leave --id 2 -f ee50000000

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by hamlynt** [comment]
Can confirm encountered same behaviour. This is exacerbating the impact of the current dust storm as it prevents adding a fee to prioritise a pool change.

**Comment by daverof** [comment]
Fixed in main and should be in the latest 1.3 beta:
https://github.com/Chia-Network/chia-blockchain/commit/41717337e6b35f5a85433538b8d023bafad567f5

**Comment by emlowe** [comment]
Yes, this was fixed by #9968
