### ISSUE TITLE
[Bug] chia plotnft join with a tx fee is broken. Does not work at all.

### ISSUE THREAD

**Issue by GrayTsar** [Chia-Network/chia-blockchain#10329]
### What happened?

Dust storm makes it impossible to join a pool because the tx fee for plotnft join is by default 1 mojo.

Since there was an option to add a tx fee via the cli. I tried using it, but that's totally broken and doesn't work at all.
For the details, see the log output.

Deleting line 15 and 16 in plotnft.py still fails to add a tx fee
It still says "0.00005" is not an integer.
    if fee < 0 or fee > MAX_CMDLINE_FEE:
        raise click.BadParameter(f"Fee must be in the range 0 to {MAX_CMDLINE_FEE}")

MAX_CMDLINE_FEE is 0.5

And to top it all off, apparently the entire add tx to plotnft join is broken af.
See the last two paragraphs in the log output.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia plotnft join -i 2 -u "https://pool.poolchia.com/" -m "0.00005"
Error: Invalid value for '--fee': 0.0005 is not a valid integer
 
chia plotnft join -i 2 -u "https://pool.poolchia.com/" -m "500000000"
Error: Invalid value for '-m' / '--fee': Fee must be in the range 0 to 0.5
 
chia plotnft join -i 2 -u "https://pool.poolchia.com/" -m "0.5"
Error: Invalid value for '--fee': 0.5 is not a valid integer

Apperently the entire add tx to plotnft join is broken
This is the output when I removed line 15 and 16 in plotnft.py
chia plotnft join -i 2 -u "https://pool.poolchia.com/" -m "50000000"
Exception from 'wallet' Value 50000000000000000000 of size 66 does not fit into uint64 of size 64
 
chia plotnft join -i 2 -u "https://pool.poolchia.com/" -m "2"
chia wallet get_transaction -f [fingerprint] -tx [txid]
Amount sent: 1E-12 xch
```

**Comment by esaung** [comment]
Can you try with the latest 1.3 beta builds on chia.net/downloads and see if the issue still exists?

in the latest build (1.2.12 dev 344) there is a known issue (https://github.com/Chia-Network/chia-blockchain/issues/10356) with trying to switch an existing plot nft from self pooling to a pool, but other than that, transaction fees should work in the GUI and the CLI.

**Comment by emlowe** [comment]
Fixed by 9968
