### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ahmadzabihi5** [Chia-Network/chia-blockchain#10339]
### What happened?

Hi,
there is error when I want to load Chia software. it stops at connecting to Wallet in the first running of  chia Software .
![Untitled](https://user-images.githubusercontent.com/100061790/154853921-63b05761-9ea0-486e-b71b-19ddb48e09e9.png)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
dup of #10340
