### ISSUE TITLE
[Bug]  Chia Wallet get_transactions --no-paginate 

### ISSUE THREAD

**Issue by JustAlias** [Chia-Network/chia-blockchain#10332]
### What happened?

Chia Wallet get_transactions --no-paginate
 could not get the entire transaction record and only printed part of it from a long time ago

### Version

1.2.12284

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by mawwammaw** [comment]
What happened?

Same here. 

chia wallet get_transactions just shows the first transactions. Nothing recent. But balance is correct, though. Tested it with v1 and v2 wallet db. Same result. 

Version
1.2.12.322

What platform are you using?
Ubuntu 21.10

What ui mode are you using?
CLI

**Comment by JustAlias** [comment]
I want to print all transaction records using “get_transactions --no-paginate” 
It can be printed completely in the V1 db. After switching to the V2 db., the command ends when no data in the last two months is printed

**Comment by mariano54** [comment]
Fixed in main
