### ISSUE TITLE
 Peak Height 11229- Peak height not moving in days.

### ISSUE THREAD

**Issue by DEFfreedom** [Chia-Network/chia-blockchain#1034]
Problems at the farm...

Hello, The issue is that  with my peak height being stuck at 11229 for days now.  I deleted the whole program along with all my plots for a fresh restart and this did not solve the problem.  Please help!

Running on a new lap top with an intel core 13 10th gen.  Thank you for your time.

**Comment by hoffmang9** [comment]
You are on Beta 27 and that chain has been dead for a few days. The current chain is RC2 and you should upgrade.

**Comment by DEFfreedom** [comment]
Thank you.  New to all this.  How do I do that?

**Comment by hoffmang9** [comment]
This should get you down the path - https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL

**Comment by DEFfreedom** [comment]
Thank you for all your hard work!  You are making the world a better place.
