### ISSUE TITLE
[Bug] Transactions Time is incorrect in wallet

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#10344]
### What happened?

As Stated in #9696 the transaction time is incorrect in the Wallet.

supposed, you have two devices with the same wallet.  
You make a payment from device 1, device 2 is not connected to the internet.

2 Weeks later you decide to check your wallet on device 2 which is now syncing.
In the main page with the sync overview, the creation times of the blocks are shown properly.  
In the wallet on device 2, the Transaction time is not the time we sent the money (blocktime). The transaction time is the time when the given block was synced locally on device 2.

Example 2:
Suppose you have a farm running in a remote location.
Once a Month you start the wallet locally in order to transfer the funds to another wallet. Your incoming transactions are not trackable anymore, when which transaction appeared.

Example 3: 
You only have one device. You are moving to a new computer or you need to resync your wallet for some reason. Now you have no insight about your transactions at all anymore. Transactions which may be years back show up as having executed a few Moments ago at the synctime

### Version

1.2.11

### What platform are you using?

Windows & Ubuntu

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
can you test this in 1.3 beta?

**Comment by forReason** [comment]
Will be able to test later that day

**Comment by forReason** [comment]
Ohhh, Awesome!!
![image](https://user-images.githubusercontent.com/12736950/155819687-37e0d46a-361c-4a2f-9bfb-e65dc88d4564.png)

thank you
