### ISSUE TITLE
[Bug] Chia refuses to sync.  Has been Stuck on "Not Synced" since 2/09

### ISSUE THREAD

**Issue by dhandler01** [Chia-Network/chia-blockchain#10342]
### What happened?

No matter how many times I reboot my comp or restart Chia it never syncs.  Been this way for 11 days.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by YusakuMuroya** [comment]
I think db file has some trouble. I also faced similar problem 2 times.

In my case, I did below process.
1)shutdown Chia Blockchain GUI
2) delete "blockchain_v1_mainnet.sqlite" in C:\Users\[USER NAME]\.chia\mainnet\db folder.
3) receive whole blocks again(maybe need 2 days to reach latest block)

**Comment by komocode** [comment]
I uninstalled and deleted the mainnet folder.

I reinstalled chia, let it sync for 5 days only to run into the same "Not Synced" error.

What's going on?

**Comment by zeniff12** [comment]
Having same problem. Am in the middle of doing the fix involving deleting the previous blockchain data from the db folder. Almost done. But it has given me the "Not Synced" red death three times now while trying to resync from scratch (3 days now). Luckily, restarting the GUI has started the syncing process. But am hoping for a more permanent fix to this bug soon. Also hoping it will be back up and running once fully synced.

**Comment by dhandler01** [comment]
> I think db file has some trouble. I also faced similar problem 2 times.
> 
> In my case, I did below process. 1)shutdown Chia Blockchain GUI 2) delete "blockchain_v1_mainnet.sqlite" in C:\Users[USER NAME].chia\mainnet\db folder. 3) receive whole blocks again(maybe need 2 days to reach latest block)

I did this and it synced for about 36 hours and is now "Not Synced" again.  This is ridiculous.

**Comment by esaung** [comment]
try the 1.3 beta and let us know if it still doesn't sync

**Comment by emlowe** [comment]
We believe such issues are closed in 1.3

**Comment by Park-Milbern** [comment]
In such cases, it is crucial to erase the damaged database and restart the synchronization process from the start. This process may take several days to complete.

A quicker solution would be to utilize a backup snapshot of the database file.
[](https://chiadb.co/)
