### ISSUE TITLE
[BUG] Exception: [WinError 87] The parameter is incorrect:

### ISSUE THREAD

**Issue by tony-clark-fc** [Chia-Network/chia-blockchain#1035]
**Describe the bug**
Detected an exception in the log of my full node.

**To Reproduce**

No symptoms evident in the GUI.  I just happened to be watching the logs and saw the exception.  Not sure that you'll be able to reproduce, but the exception is quite specific, so you may be able to correlate it with other bugs.

**Expected behavior**
Detected Exception in the log (details in additional content):  

     Exception: [WinError 87] The parameter is incorrect: 
     -----8<------
     "src\harvester\harvester_api.py", line 166, in new_signage_point_harvester

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
- RAM: 8GB

**Additional context**

18:18:01.110 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:18:01.110 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4 127.0.0.1
18:18:02.148 harvester src.plotting.plot_tools : INFO     Searching directories ['E:\\plots']
18:18:02.152 harvester src.plotting.plot_tools : INFO     Loaded a total of 18 plots of size 1.7820136863701919 TiB, in 0.024984359741210938 seconds
18:18:02.155 harvester src.harvester.harvester : INFO     0 plots were eligible for farming 2b5fcf9e2e... Found 0 proofs. Time: 0.02798 s. Total 18 plots
18:18:02.156 harvester harvester_server        : INFO     -> farming_info to peer 127.0.0.1 d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4
18:18:10.048 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:18:10.048 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4 127.0.0.1
18:18:11.065 harvester src.harvester.harvester : INFO     0 plots were eligible for farming 2b5fcf9e2e... Found 0 proofs. Time: 0.00200 s. Total 18 plots
18:18:11.066 harvester harvester_server        : INFO     -> farming_info to peer 127.0.0.1 d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4
18:18:18.195 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:18:18.195 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4 127.0.0.1
18:18:19.208 harvester src.harvester.harvester : INFO     0 plots were eligible for farming 2b5fcf9e2e... Found 0 proofs. Time: 0.00000 s. Total 18 plots
18:18:19.209 harvester harvester_server        : INFO     -> farming_info to peer 127.0.0.1 d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4
18:18:27.384 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:18:27.384 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4 127.0.0.1
18:18:36.922 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:18:47.021 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:18:56.382 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:19:06.535 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:19:18.534 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:19:25.581 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:19:34.426 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:19:46.208 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:19:57.191 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:20:05.373 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:20:17.415 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:20:26.602 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:20:36.452 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:20:45.782 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:20:54.490 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:02.673 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:11.960 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:21.075 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:29.205 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:34.748 harvester harvester_server        : ERROR    Exception: [WinError 87] The parameter is incorrect:
'E:\\plots\\plot-k32-2021-02-18-19-49-de858ed6cec19b0d1253eecef236362fbcd29198a99d3b81fd2db264d33aecc0.plot', closing connection {'host': '127.0.0.1', 'port': 8447}. Traceback (most recent call last):
  File "src\harvester\harvester_api.py", line 166, in new_signage_point_harvester
18:21:34.751 harvester harvester_server        : INFO     Connection closed: 127.0.0.1, node id: d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4
18:21:35.758 harvester src.harvester.harvester : INFO     peer disconnected {'host': '127.0.0.1', 'port': 8447}
18:21:37.750 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
18:21:37.761 harvester harvester_server        : INFO     -> handshake to peer 127.0.0.1 d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4
18:21:37.762 harvester harvester_server        : INFO     Connected with farmer {'host': '127.0.0.1', 'port': 8447}
18:21:38.765 farmer farmer_server              : INFO     -> harvester_handshake to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:38.767 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:38.765 harvester asyncio                 : ERROR    Task exception was never retrieved
18:21:39.781 harvester harvester_server        : INFO     <- harvester_handshake from peer d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4 127.0.0.1
18:21:39.807 harvester src.plotting.plot_tools : INFO     Searching directories ['E:\\plots']
18:21:39.828 harvester src.plotting.plot_tools : INFO     Loaded a total of 18 plots of size 1.7820136863701919 TiB, in 0.04497337341308594 seconds
18:21:39.831 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4 127.0.0.1
18:21:39.868 harvester src.plotting.plot_tools : INFO     Searching directories ['E:\\plots']
18:21:39.872 harvester src.plotting.plot_tools : INFO     Loaded a total of 18 plots of size 1.7820136863701919 TiB, in 0.03797793388366699 seconds
18:21:39.877 harvester src.harvester.harvester : INFO     0 plots were eligible for farming 2b5fcf9e2e... Found 0 proofs. Time: 0.04298 s. Total 18 plots
18:21:39.881 harvester harvester_server        : INFO     -> farming_info to peer 127.0.0.1 d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4
18:21:49.330 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 127.0.0.1 f102f60239bc1b934daea11d3a8aebc290325fef416d921fe4dfca4afa7c1632
18:21:49.330 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer d34191d0333b71e6fde0feb350dbaf3f96be2095495b9104959be44ce908b3c4 127.0.0.1
18:21:50.367 harvester src.harvester.harvester : INFO     0 plots were eligible for farming 2b5fcf9e2e... Found 0 proofs. Time: 0.02201 s. Total 18 plots

**Comment by hoffmang9** [comment]
Please try RC7
