### ISSUE TITLE
[Bug] Show All rows per page causes GUI and CLI to hang in wallet with lots of transactions

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10360]
### What happened?

choosing the All option in the transaction history of the wallet causes the wallet GUI/CLI to hang in a wallet with many transactions.
<img width="1312" alt="Screen Shot 2022-02-21 at 2 05 46 PM" src="https://user-images.githubusercontent.com/93196638/155019991-6c0e3025-d386-4355-927b-f2204cac8481.png">

Request: remove the "All" option in the row drop down

### Version

1.2.12 dev 333

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/commit/0d803b7d99891754398f27b6aed5f44564b8cee1
