### ISSUE TITLE
[Bug] restore metadata for colored coins and other smart wallets from backup 

### ISSUE THREAD

**Issue by JoseJuara** [Chia-Network/chia-blockchain#10373]
### What happened?

I had to reopen the Chia wallet, enter my mnemonic phrase and it asked me to restore metadata for colored coins and other smart wallets from backup (basically a drag and drop box).
What files should I restore? IT has a green button saying it's "SAFE TO SKIP", but when I click on it, it doesn't work.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
Hi @JoseJuara , this screen is no longer needed. It is safe to skip. That screen doesn't exist in later builds of our light wallet client and the upcoming 1.3 release.

**Comment by JoseJuara** [comment]
Hola @esaung entiendo que no es necesario pero no me deja omitirlo. aunque clickee que es seguro de saltar aparece una notificacion que dice "fingerprint" y no puedo hacer nada.
