### ISSUE TITLE
[Bug]  . ./activate : No such file or directory

### ISSUE THREAD

**Issue by bipurna** [Chia-Network/chia-blockchain#10391]
### What happened?

`. ./activate
`
`bash: ./activate: No such file or directory`

### Version

latest

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Please provide more details - did you run `sh install.sh` first? Please include the output of running the install script.

**Comment by bipurna** [comment]
I am using Ubuntu 20.04, and I followed the documentation to install it. When I run `sh install.sh` , throws these errors =>
`apt-get is /usr/bin/apt-get
Installing on Ubuntu 20.04 LTS.
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Ign:2 http://ppa.launchpad.net/florian-rival/gdevelop/ubuntu focal InRelease   
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease                 
Hit:4 https://download.mono-project.com/repo/ubuntu stable-focal InRelease     
Hit:5 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease             
Hit:6 https://dl.google.com/linux/chrome/deb stable InRelease                  
Hit:7 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease         
Hit:8 https://brave-browser-apt-release.s3.brave.com stable InRelease          
Ign:9 http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu focal InRelease
Hit:10 http://ppa.launchpad.net/maarten-fonville/android-studio/ubuntu focal InRelease
Ign:11 http://ppa.launchpad.net/synapse-core/ppa/ubuntu focal InRelease
Ign:12 http://ppa.launchpad.net/webupd8team/java/ubuntu focal InRelease
Err:13 http://ppa.launchpad.net/florian-rival/gdevelop/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Err:14 http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Err:15 http://ppa.launchpad.net/synapse-core/ppa/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Err:16 http://ppa.launchpad.net/webupd8team/java/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done                      
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.mono-project.com/repo/ubuntu stable-focal InRelease' doesn't support architecture 'i386'
E: The repository 'http://ppa.launchpad.net/florian-rival/gdevelop/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/synapse-core/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
