### ISSUE TITLE
[Bug] wallet restore from backup page keeps turning

### ISSUE THREAD

**Issue by darwinjobchia** [Chia-Network/chia-blockchain#10407]
### What happened?

wallet restore from backup page keeps turning
![Screenshot 2022-02-24 190843](https://user-images.githubusercontent.com/83147673/155504484-fe3e1b92-99c9-4ce9-b119-023adff4749e.jpg)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
I believe this is entirely removed from 1.3 - please re-open if you have further issues in 1.3 release
