### ISSUE TITLE
[enhancement] add cancel transaction on pending confirm accepted offer

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10417]
in the case where an offer has been accepted but for some reason gets stuck in the "pending confirm" state, allow the user to cancel the transaction in the GUI

![Image 2-24-22 at 2 41 PM](https://user-images.githubusercontent.com/93196638/155605279-94673a0f-42c3-40bb-9277-59135ed5e594.jpg)

CLI already has an option to cancel:

1. ./chia wallet get_offers -> get the record id
2.  ./chia wallet cancel_offer -id $record_id --insecure

**Comment by paninaro** [comment]
Fixed in commit:
https://github.com/Chia-Network/chia-blockchain-gui/commit/b241f44e740773b7711b1003a517189160909809
