### ISSUE TITLE
Chia Blockchain 1.2.12284

### ISSUE THREAD

**Issue by siamsukto7720** [Chia-Network/chia-blockchain#10412]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/10410

<div type='discussions-op-text'>

<sup>Originally posted by **siamsukto7720** February 24, 2022</sup>
Hello ,
I downloaded 1.2.12284 and wallet is not syncing. I am unable to determine what is wrong. I reviewed debug log and my plots are farming. Can you please advise?

Version
1.2.12284

What platform are you using?
Windows

What ui mode are you using?
GUI

Relevant log output
No response</div>

**Comment by siamsukto7720** [comment]
issue resolved with beta3. thank you

**Comment by esaung** [comment]
thanks, closing
