### ISSUE TITLE
Untrusted sync launched even when trusted full node is available and found

### ISSUE THREAD

**Issue by altendky** [Chia-Network/chia-blockchain#10438]
### What happened?

Several times in a row I had my full node synced and running prior to launching my wallet.  The wallet started up and found a remote untrusted peer first and started into an untrusted sync.  It kept with the untrusted sync despite connecting to my local full node, using it for untrusted sync, and indicating it as trusted in the `chia wallet show` output.

### Version

1.3 beta era `main`

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
Yeah, I'll try to get back to this.
```

**Comment by altendky** [comment]
This is at least in part being worked on in https://github.com/Chia-Network/chia-blockchain/pull/10415.  We can review this ticket for any remaining changes after 10415 is merged.

**Comment by mariano54** [comment]
Done
