### ISSUE TITLE
[Bug] - Connecting wallet is not working

### ISSUE THREAD

**Issue by victortb23** [Chia-Network/chia-blockchain#10431]
### What happened?

My chia blockchain stopped working after a power outage. I have restarted the computer several times and it is not working. It only appears "connecting the wallet" and does not develop. Does anyone have any suggestions to solve this problem?

Follow the log file
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/8141157/debug.log)
:

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BlueMining** [comment]
Same  problem  dont connect and keep in loading

**Comment by emlowe** [comment]
Please upgrade to 1.3 and re-open if you have further issues.
