### ISSUE TITLE
[bug] CLI plotting has default buffer size that always fails when plotting larger k

### ISSUE THREAD

**Issue by elyograg** [Chia-Network/chia-blockchain#10455]
### What happened?

When I try to plot the larger plot sizes like k34 and k35, the plot never finishes.  It says there's not enough memory.

`Caught plotting error: Not enough memory for sort in memory. Need to sort 4.999758GiB`

But there is plenty of memory.  Output from free (which reports in KiB):

```
              total        used        free      shared  buff/cache   available
Mem:       65897320    38370952      453424      673660    27072944    26182132
Swap:             0           0           0
```
The program wants 5GiB.  And there is in excess of 20GiB available.  If the program is checking "free" memory rather than "available" memory, then it will see only a few hundred thousand kilobytes.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by shaneo257** [comment]
what about the temp storage drive you're using?

**Comment by elyograg** [comment]
Your question was vague, but I have decided that you're asking about disk space and here's that info.  Both tmp_dir and final_dir are on this storage volume.  And that brings up another issue -- why does it COPY the final plot instead of asking the OS to move it?  In cases where both source and destination are on the same mount point, like mine, the move would be instantaneous, and in situations where they are on different mounts, the OS will do a copy then delete.

```
elyograg@smeagol:~$ df -h /storage0/chia-blockchain
Filesystem      Size  Used Avail Use% Mounted on
-                22T  6.0T   16T  28% /storage0/chia-blockchain
```

**Comment by elyograg** [comment]
I think I found a workaround.  While I am building plots, I will run this in a screen:

`while true; do echo 3 > /proc/sys/vm/drop_caches; sleep 30 ; done`

**Comment by elyograg** [comment]
My workaround did not work.  k34 and k35 plots failed, with the "Not enough memory" error.  There should have been plenty of memory in the "free" column with that workaround.  It is and was successfully building k32 and k33 plots even before I started fiddling.

**Comment by emlowe** [comment]
I believe the complaint if you didn't specify any value for Max Ram and the default is not designed to work with k=35. Please provide your exact command for creating these plots.

You likely need to provide a bigger number for the "buffer" - somewhat misnamed in the CLI - but I believe the default is not adjusted for K size automatically.

If using CLI - then you use the `-b` or `--buffer` option and provide a value in MiB - so --buffer 6000

**Comment by elyograg** [comment]
It does set a value automatically.  It's just under 5GiB for a k35 and something less than that for k34.

This system has 64GB of RAM and all the programs on it use a little more than half that.  The system does have PLENTY of memory.  Here's an example commandline:

`numactl --interleave=all chia plots create -n 4 -r 4 -k 35 --tmp_dir /storage0/chia-blockchain/plot --final_dir /storage0/chia-blockchain/final`

**Comment by elyograg** [comment]
When I asked the GUI to create a k35 plot, it used a really big number for -b ... 26200 if I remember right.  That plot also failed to build, but as it was started by the GUI and not a shell, I never saw the error message.  I've just started a k35 plot attempt with -b6144 ... if a value is given with -b, will the program still check to make sure the memory is available, or will it allocate blindly? A blind allocation of 6144MB would succeed on this system, but the value over 26000 that the GUI tried to use could very well fail.

If the source code is actually in this repo, then I can take a look, and if so, I will check  it out.

**Comment by emlowe** [comment]
That is the chia installed version - it uses pyinstaller to create a binary. You can have both the git repo and the installed version on the same system, but it can get confusing which chia is being run. To use the git version you want to make sure you are in the venv (`. ./activate`) or directly call the venv version.

It does not try to allocate the memory, rather it tries to see if it would fit by calculating how many buckets are needed and if that number could fit in the amount of ram specified. The source for your original error is found here: https://github.com/Chia-Network/chiapos/blob/0502f346b984bf80ca7f5d7c600fe3467483d9dd/src/sort_manager.hpp#L286

**Comment by elyograg** [comment]
I haven't installed from the git repo, I just have the binary package installed.  So no confusion there.  I cloned the git repo, but I did not build or install it.

With your latest information, now it makes perfect sense why it's failing.  The default value for -b is 3389, and plots of k34 and larger require more memory than that.  The error message could use some improvement.  Rather than saying "Not enough memory" it should say something like "XXX buffer space  is required and only YYY has been allowed."  That could have  "with the -b option" added to the end.  And maybe the default value for -b should change depending on the plot size, rather than always defaulting to 3389.

On my latest k35 plot attempt, I am passing -b6144 and I think that will probably fix it.  Thank you for persevering through my beginnner's misunderstanding!

**Comment by elyograg** [comment]
6144 didn't work.  It failed again, likely at a later step, because the number in the error changed.

`Caught plotting error: Not enough memory for sort in memory. Need to sort 7.250167GiB`

I'll try starting with 8192 and see what happens.

**Comment by elyograg** [comment]
I can say for sure that -b8192 is enough for a k34 plot.  I don't yet know if it's enough for a k35, but the plotting has lasted longer so far with -b8192 than it has ever lasted before ... nearly four days now.

Because the error message said "Not enough memory" I initially was digging down the wrong rabbit hole.  It wasn't that I didn't have enough memory ... it was that I didn't inform the program that it had the right to ask for enough memory.  A subtle distinction, but supremely important.

I would think that the program developers know in advance how much buffer space each of the plot sizes will take ... and that they are in a position to make the program "fail fast" ... if the available buffer space is not going to be enough, it should fail immediately and inform the user that it must be given more space with the -b option.

Or alternately, it could just preconfigure itself with the minimum buffer space required for the plot size requested, inform the user about how much memory it will allocate, and give them a few seconds to stop the program with ctrl-c if that will be a problem.  That requires the end user to pay attention, and that cannot be guaranteed, but if it had said anything when it first started other than asking for my keyring passphrase, I definitely would have noticed.

The principle of least surprise is what I'm going for here.  Either the program should have configured itself such that it would work properly, never giving me an error message, or it should have given an error message indicating what I needed to do to fix the problem.  Instead it gave me an error message that probably made perfect sense to the developer who wrote the code, but says completely the wrong thing to a novice.
