### ISSUE TITLE
GUI and CLI both sync then come out of sync every 1 or 2 minutes 1.2.12376[Bug] 

### ISSUE THREAD

**Issue by L4bb3rs** [Chia-Network/chia-blockchain#10467]
### What happened?

GUI and CLI both sync then come out of sync every 1 or 2 minutes, happen more regularly when using RPC.

### Version

1.2.12376

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Unclear if you are referring to the node or the wallet, in any event, Please try 1.3 release version.
