### ISSUE TITLE
Plots disappeared from GUI, still taking up space on HDD

### ISSUE THREAD

**Issue by rcf96** [Chia-Network/chia-blockchain#1046]
I attempted to add another plot to my HDD but in the process all of my plots have disappeared in the GUI. I have tried signing in and out and refreshing the GUI multiple times. I have also tried setting and resetting the plot directory where my plots are located. I can see the files on my hard disk in the folder where my plots are. Let me know if there is an easy fix to this.

**Comment by dorkmo** [comment]
did you start a new wallet and get a new 24 word password?

**Comment by rcf96** [comment]
I have not started a new wallet. I am using the same wallet that I started with.

**Comment by ayaseen** [comment]
Same it happens to me

**Comment by pmaslana** [comment]
@rcf96 Were the plots Farming or still Plotting? I noticed that it can be easy to interrupt the plots while they are plotting and then they will disappear if you exit out of the GUI.

**Comment by rcf96** [comment]
@pmaslana They were Farming when this occurred. I had never exited the GUI prior to this happening. I created an additional plot now and that one is farming. I have a total of 4 plots that are taking up space on my drive but only 1 of them is farming, they are all in the same directory.

**Comment by wjblanke** [comment]
Can you set logging to INFO and let us know what the logs are saying?

**Comment by ayaseen** [comment]
Anyone found a solution for this behavior. It does not make sense to recreate the plots again

**Comment by rcf96** [comment]
@wjblanke I have set my logging to INFO in my config.yaml file. I will let you know what information comes from that if any. I have yet to see any additions to the log file yet.

**Comment by hoffmang9** [comment]
Please make sure that the directory that the plot you are expecting to see is listed in your config.yaml file.

**Comment by mariano54** [comment]
Probably just a key mismatch.
