### ISSUE TITLE
[Bug] Wallet v2 db forces payout_instructions address to STANDARD_WALLET address

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#10478]
### What happened?

On first run of chia wallet service in beta3, or on sync from 0, the chia wallet service sets the `payout_instructions:` entry in `config.yaml` to be that of a receive address tied to the STANDARD_WALLET.

I have my rewards for pooling configured to send to a cold wallet address. I set this in `config.yaml` at `payout_instructions:`, and `chia plotnft show` verifies my desired address at `Payout instructions (pool will pay you with this):`.

To replicate this, simply `chia stop all -d` and delete the contents of `~/.chia/mainnet/wallet/db/` and then `chia start wallet`. This will replace my `payout_instructions:` entry in `config.yaml`. This behavior also happens if updating from a working `1.2.11` -> `beta3`

### Version

1.2.12.dev376

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by paninaro** [comment]
```-> main()
  /Users/jeffc/src/macos/chia-blockchain/chia/server/start_wallet.py(94)main()
-> return run_service(**kwargs)
  /Users/jeffc/src/macos/chia-blockchain/chia/server/start_service.py(278)run_service()
-> return asyncio.run(async_run_service(*args, **kwargs))
  /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py(44)run()
-> return loop.run_until_complete(main)
  /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py(629)run_until_complete()
-> self.run_forever()
  /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py(596)run_forever()
-> self._run_once()
  /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py(1890)_run_once()
-> handle._run()
  /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py(80)_run()
-> self._context.run(self._callback, *self._args)
  /Users/jeffc/src/macos/chia-blockchain/chia/wallet/wallet_node.py(637)receive_and_validate()
-> await self.wallet_state_manager.new_coin_state(valid_states, peer, fork_height)
  /Users/jeffc/src/macos/chia-blockchain/chia/wallet/wallet_state_manager.py(856)new_coin_state()
-> pool_wallet = await PoolWallet.create(
  /Users/jeffc/src/macos/chia-blockchain/chia/pools/pool_wallet.py(354)create()
-> await self.update_pool_config(True)
  /Users/jeffc/src/macos/chia-blockchain/chia/pools/pool_wallet.py(252)update_pool_config()
-> await update_pool_config(self.wallet_state_manager.root_path, list(pool_config_dict.values()))
  /Users/jeffc/src/macos/chia-blockchain/chia/pools/pool_config.py(83)update_pool_config()
-> save_config(root_path, "config.yaml", full_config)
> /Users/jeffc/src/macos/chia-blockchain/chia/util/config.py(44)save_config()
-> path: Path = config_path_for_filename(root_path, filename)
```

**Comment by ojura** [comment]
Another report in the wild:
https://www.reddit.com/r/chia/comments/srpzc7/13_beta_may_change_pool_payout_address/

**Comment by paninaro** [comment]
The issue appears to be `PoolWallet.create()` calling `PoolWallet.update_pool_config()` with `make_new_authentication_key` set to `True`. `update_pool_config` will write a new pool config section in this scenario. Discussing with @aqk how best to preserve existing pool config data.
