### ISSUE TITLE
Should this < be <= ?

### ISSUE THREAD

**Issue by freddiecoleman** [Chia-Network/chia-blockchain#10473]
https://github.com/Chia-Network/chia-blockchain/blob/7fb26a7a142e297e608c2f086fb57b450d7826e4/chia/full_node/coin_store.py#L225

When looking up historic coins you would probably expect the end height to be included in the results.

**Comment by RnMss** [comment]
I think that's mostly about aesthetics and conventions.

In Python, when you write `some_list[1:3]` you get a new list of length 2, not 3. `[ some_list[1], some_list[2] ]`

In C++, when you write `std::vector<int>(&data[1], &data[3])`, you get a vector of size 2 not 3.

So by convention if the parameters are named "begin" / "end", it usually means "begin" is the first element, and "end" is one element after the last.
