### ISSUE TITLE
[BUG] Trying to plot to an external drive but the temp file never gets converted to the plot file

### ISSUE THREAD

**Issue by berlef80** [Chia-Network/chia-blockchain#1051]
**Describe the bug**
I run the plotter and everything is working fine until the last step when the temp file gets copied over to the HDD drive at which point I am left with a full 1GB temp file both on the SDD and the HDD drive, but it never converts to the final plot file.  I have shut down Chia multiple times deleted the file, and started over but it does the same thing  I have also plotted many plots to the same drives in the past.  I am farming off the same drive and Chia is seeing that.

**To Reproduce**
Set HDD to external drive and start plotting

**Expected behavior**
Changes tmp plot to plot file in final drive

**Desktop (please complete the following information):**

- OS: Windows 10 GUI Chia

**Additional context**
Work around seems to be to just remove the tmp from the end of the file or plot to internal HDD and then copy to external drive

**Comment by hoffmang9** [comment]
Please try RC7
