### ISSUE TITLE
[Bug] CLI allows setting fee (-m) when creating an offer - and then errors out

### ISSUE THREAD

**Issue by dyiwhitebox** [Chia-Network/chia-blockchain#10518]
Creating an offer file with a fee throws this error:

Exception from 'wallet' {'error': 'Error creating offer: ', 'success': False}

Log shows:

2022-03-02T08:36:49.455 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\wallet_rpc_api.py", line 900, in create_offer_for_ids
  File "chia\wallet\trade_manager.py", line 231, in create_offer_for_ids
Exception: Error creating offer:

chia.exe version = 1.2.12.dev355

If the fee is left off the offer gets created successfully.

command used:
chia.exe wallet make_offer -o 1:1 -r 3:78.7 -m .00005 -p C:\xch_dex\56db523f-c064-4c5b-a83f-c619b4872476.offer

**Comment by esaung** [comment]
currently that's not supported when making an offer. Can I ask why you are making an offer with a fee?

what would you expect the behavior to be since you would still have to wait for a taker to pick up the offer?

**Comment by emlowe** [comment]
I think the bug here is that the CLI allows you to set the fee (`-m`) but then errors out randomly. The CLI should be updated to not accept the `-m` option if the fee doesn't work.

**Comment by emlowe** [comment]
I believe this works now in v.1.3.4, you can add a fee at the time of offer creation
