### ISSUE TITLE
XCH missing when downgrading client software from beta to stable

### ISSUE THREAD

**Issue by nur-azhar** [Chia-Network/chia-blockchain#10512]
### What happened?

My $XCH went missing after downgrading client software from  1.3-beta3 to 1.2.11, I'm running full node and downgraded because the wallet doesn't sync.

After 1.2.11 sync, my $XCH went missing and the transaction history isn't complete either

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by nur-azhar** [comment]
just to follow up I reinstall the latest beta version and open it, XCH is here

different blockchain?

**Comment by esaung** [comment]
This is not a bug. We switched to using observer keys starting with the light wallet and the 1.3 betas. see our blog post here: https://www.chia.net/2022/02/10/1.3-beta-release.en.html
