### ISSUE TITLE
[Bug] config.yaml thrashing

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10536]
### What happened?

issues with config.yaml being written to while in memory and losing previous configurations that have been set. As reported by @wallentx and @altendky 

### Version

1.2.12 dev389

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by mariano54** [comment]
Fixed or is there a new issue

**Comment by esaung** [comment]
just tracking the issue. not sure if there was another issue filed for what we was discussed.

**Comment by mariano54** [comment]
I will close as I'm pretty sure this is now fixed. If it is not, feel free to reopen @altendky
