### ISSUE TITLE
[BUG] GUI - Unable to connect to wallet due to javascript error

### ISSUE THREAD

**Issue by emiltmadsen** [Chia-Network/chia-blockchain#1055]
**Describe the bug**
When I start up the GUI through my terminal a javascript error appears and the GUI gets stuck on "connecting to wallet".
This has happened a couple of times after I've shutdown and started up my PC and tried to open the Chia GUI again. The only solution I've found is to reinstall Chia.

**To Reproduce**

See screenshot 1.

**Expected behavior**
The GUI starts up and connects normally.

**Screenshots**
What I did to produce the error:
![Screenshot from 2021-02-25 10-47-47](https://user-images.githubusercontent.com/61865338/109128035-bd7edc80-7757-11eb-930a-97220c8f4523.png)

The error:
![Screenshot from 2021-02-25 10-47-10](https://user-images.githubusercontent.com/61865338/109128069-c8397180-7757-11eb-95d5-3aee50f1e88e.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Pop!_OS 20.10
- CPU: Intel Core i7-6500U (2.5GHz quadcore)

**Comment by mariano54** [comment]
Please try `. ./activate` and install the new version (rc5)
