### ISSUE TITLE
[Feature request] Import/export blockchain DB (or database validation feature)

### ISSUE THREAD

**Issue by babipanghang** [Chia-Network/chia-blockchain#10572]
Since the blockchain database is growing quite large these days and will only keep getting larger, syncing a database from 0 can be a major pain in the bottom. It would be desirable to download a database from somewhere and be able to import that.

At this moment, i understand one should not import from untrusted sources. This leads me to the question: could a database export/import function be created so that a database can be verified before use, basically enabling people to safely use a database from a third party?

**Comment by scrutinously** [comment]
Like a database with a checksum stored on the blockchain signed by a farmer's key?

**Comment by babipanghang** [comment]
As i understand it, when a new block is added to the chain, a farmers job is to verify it and add that block to the database. When syncing from scratch, this involves requesting and downloading all blocks from peers and doing the above for each block.
It seems to me that this process could be a lot faster if requesting and downloading individual blocks could be skipped altogether and the blocks could be read from a file instead.

That way, one would not have to trust the author of the file, since each block is still verified before it gets added to the database.

**Comment by shaneo257** [comment]
in 1.3 when its released will compress the db by at least 40%
chia devs are also looking into other improvements on how its synced, ie instead of syncing from 0, sync from peak height and go back to zero
