### ISSUE TITLE
[Feature Enhancement] Notify the user that the payout address for a pool NFT has been set to a default address on initial load

### ISSUE THREAD

**Issue by DrakeFS** [Chia-Network/chia-blockchain#10586]
There should be a user notification drawing attention to the payout address of a newly loaded pool NFT.   After "fixing" my pool NFT from #10585 I noticed all my pools where no longer farming to my cold wallet.

### What happened?

All of my pool NFTs generated new payout addresses after the update.  There was no warning that the payout addresses had changed.  The farmer reward and pool reward where both correct. 

Verfied the addresses where changed in the config.yaml comparing to a backup of the config.yaml from before the update.

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by babipanghang** [comment]
1.3 implements the new light wallets if i'm not mistaken. Could it be that it generated a new light wallet address for you and points to that by default?

**Comment by DrakeFS** [comment]
That should not be the default behavior.   I do not farm to an address of a wallet that is on my farmer (I farm to a cold wallet).

The update probably didn't directly cause this issue though.  I resolved my initial issue #10585 by removing the pool info from the config.yaml and resyncing my DBs.  Since the payout address is saved in said info, the client just assigned a new address to it when it found the pool nft info from my wallet.  The client should probably notify the user of this behavior on the first load of a pool nft.
