### ISSUE TITLE
1.3.0 - Solo NFT shows as Pooling and can't claim rewards [Bug] 

### ISSUE THREAD

**Issue by athena9** [Chia-Network/chia-blockchain#10590]
### What happened?

- Updated to 1.3.0 by running the windows installer.
- Let the client start, choose farming mode, full node running, then closed GUI
- Ran chia db upgrade and deleted the old v1 files
- Restarted Chia to resume farming

My solo NFT now thinks that it is pooling. I can't see my unclaimed rewards, and there's no mechanism to claim them.

In the GUI no pool URL is reported, but in the CLI a pool URL is returned. This URL is one that was used several months ago, and also one that exists on an unused NFT from another key. It isn't clear which side its coming from, but I suspect its from the other key rather than months old data - after resyncing the wallet dbs the issue persists.

If I switch to another key, it correctly identifies the NFT as being solo in the GUI. Switch back to the owning wallet and it again shows as pooling instead of self pooling.

![image](https://user-images.githubusercontent.com/22037868/157234509-a58f4b13-ff44-47b7-b7fc-ef0daf0a09c2.png)

I've just deleted the config.yaml and run chia init (hence 0 plots). I did not need to re-add keys at any point.

@wallentx has been assisting over keybase

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by athena9** [comment]
Potential resolution.

Deleting all wallet keys in addition to the wallet databases, restarting chia, readding the keys, and resyncinc wallets has put things back in order. My solo NFT is solo, unclaimed rewards are present, and the CLI is no longer reporting a URL for the solo pool.

Still tempted to clean everything, but might get a clean blcokchain synced on another node first.

**Comment by mariano54** [comment]
Do not delete wallet keys unless you have a backup. You should only need to delete the wallet DB (perhaps also delete entire .chia folder and re-add your node DB backup there).

There is currently an issue with syncing plotnfts and we're looking into it.

**Comment by athena9** [comment]
Good point regarding being absolutely certain keys are backed up.

Deleting the wallet folder was not sufficient, for whatever reason.

**Comment by DrakeFS** [comment]
I fixed my issue by also removing the pool NFT info from the config.yaml along with resyncing my wallet(s) from 0.

I will note, this changed my payout addresses for my pool NFTs, which I had to set back to my cold wallet.

**Comment by prodchia** [comment]
Deleting .chia isn't working for me. I have already tried it twice

**Comment by OMeliante** [comment]
> Do not delete wallet keys unless you have a backup. You should only need to delete the wallet DB (perhaps also delete entire .chia folder and re-add your node DB backup there).
> 
> There is currently an issue with syncing plotnfts and we're looking into it.

Meanwhile, more 300+tb farm is farming for nobody? Zero rewards? Great

**Comment by prodchia** [comment]
I switched back to 1.2.11

**Comment by barkgabri** [comment]
I switched back to 1.2.11 and fix the andress in config.yaml

**Comment by mariano54** [comment]
@prodchia what platform are you running on? windows?

**Comment by ojura** [comment]
It looks like #10194 was not fixed after all.

**Comment by mariano54** [comment]
I think this should be fixed by: https://github.com/Chia-Network/chia-blockchain/pull/10631
Download: https://github.com/Chia-Network/chia-blockchain/actions/runs/1959674376
Note: you will need to delete the wallet DB and start again.

**Comment by OMeliante** [comment]
Meanwhile, chia price is getting BELOW 70 dollars. Problems with bugs, without any relevant news for chia's utility... Please guys, devs, Bram, do something! The Project is making one year and we are still trying to believe in it! We, miners, are doing our part!

**Comment by azrielitay** [comment]
@mariano54  having same issue in Ubuntu afther upgrading to 1.3.
I was on space pool before upgrade and it moved to solo.
When tring to change pool from solo to pool i get error message: (log file shows below)
2022-03-10T13:35:22.543 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/harvester/chia-blockchain/chia/rpc/rpc_server.py", line 215, in safe_handle
    response = await self.ws_api(message)
  File "/home/harvester/chia-blockchain/chia/rpc/rpc_server.py", line 206, in ws_api
    return await f(data)
  File "/home/harvester/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1346, in pw_join_pool
    total_fee, tx, fee_tx = await wallet.join_pool(new_target_state, fee)
  File "/home/harvester/chia-blockchain/chia/pools/pool_wallet.py", line 717, in join_pool
    raise ValueError(msg)
ValueError: Asked to change to current state. Target = {'owner_pubkey':

looking in config.yaml its look like the 0x is missing in the Pool tag under - authentication_public_key:

**Comment by mariano54** [comment]
@azrielitay can you try with the fix here:
https://github.com/Chia-Network/chia-blockchain/actions/runs/1960768052

And delete wallet DB before starting?
authentication_public_key is not used in 1.3, why do you think that might cause an issue?

**Comment by iJeys** [comment]
How can this be on NFT rates in SOLO and yes now I can't request them, they just lie in the SOLO Pool 
1.3.
![SOLO](https://user-images.githubusercontent.com/74445568/158004337-a970ae61-bb8b-46be-99cd-b5aae9a83019.PNG)
0

**Comment by azrielitay** [comment]
> I think this should be fixed by: #10631 Download: https://github.com/Chia-Network/chia-blockchain/actions/runs/1959674376 Note: you will need to delete the wallet DB and start again.

still same issue:
when changing from "self pool" to "pool".
2022-03-12T12:28:55.723 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 1346, in pw_join_pool
  File "chia/pools/pool_wallet.py", line 717, in join_pool
ValueError: Asked to change to current state. Target = {'owner_pubkey': 'XXXX',
 'pool_url': 'https://eu1.pool.space',
 'relative_lock_height': 64,
 'state': 3,
 'target_puzzle_hash': 'XXXX',
 'version': 1}

**Comment by azrielitay** [comment]
> > I think this should be fixed by: #10631 Download: https://github.com/Chia-Network/chia-blockchain/actions/runs/1959674376 Note: you will need to delete the wallet DB and start again.
> 
> still same issue: when changing from "self pool" to "pool". 2022-03-12T12:28:55.723 wallet chia.rpc.rpc_server : WARNING Error while handling message: Traceback (most recent call last): File "chia/rpc/rpc_server.py", line 215, in safe_handle File "chia/rpc/rpc_server.py", line 206, in ws_api File "chia/rpc/wallet_rpc_api.py", line 1346, in pw_join_pool File "chia/pools/pool_wallet.py", line 717, in join_pool ValueError: Asked to change to current state. Target = {'owner_pubkey': 'XXXX', 'pool_url': 'https://eu1.pool.space', 'relative_lock_height': 64, 'state': 3, 'target_puzzle_hash': 'XXXX', 'version': 1}

@mariano54 a work around i found is opening config.yaml file and enter manualy the pool url in 
"pool_url: "
its look like the upgrade to 1.3 change the config.yaml pool setting.

**Comment by wallentx** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/10680 should resolve this

**Comment by xlgosx** [comment]
> Do not delete wallet keys unless you have a backup. You should only need to delete the wallet DB (perhaps also delete entire .chia folder and re-add your node DB backup there).
> 
> There is currently an issue with syncing plotnfts and we're looking into it.

for me going back to 1.2.11 solved the problem. For non technical people like me, its impossible to find that db folder, so I just installed 1.2.11 which seems to properly sync the wallet without complicated stuff, they should fix the wallet syncing feature for the gui soon .
