### ISSUE TITLE
[Bug] 1.3 - CLI command `chia keys show` displays non-observer wallet address

### ISSUE THREAD

**Issue by daverof** [Chia-Network/chia-blockchain#10591]
### What happened?

Wallet addresses generated in version 1.3 (GUI) are now observer addresses by default.

However, the CLI command `chia keys show` displays the first wallet address as the non-observer address.

This is confusing, as the command `chia keys derive wallet-address` defaults to observer addresses unless the `-d` option is used.

If observer addresses are now the preferred default as the documentation implies, can the `chia keys show` command be updated to show the first observer address, or at the very least show both observer and non-observer addresses?

### Version

1.3

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by mariano54** [comment]
+1

**Comment by emlowe** [comment]
Yes, it should be updated to the observer address - we should also check that the GUI and `chia keys show` display the same address on initial use

**Comment by paninaro** [comment]
I included the ability to show the old (non-observer derived) wallet address by adding the `-d` option:
e.g.
`chia keys show -d`
...
`First wallet address (non-observer): xch13vqjr7wag3lmjjya94ds0n20zqt7kc52dyhj7jw90r27m76pmf0qlryh3g`
