### ISSUE TITLE
[Bug] 1.3.0 Wallet is not fully synchronized.

### ISSUE THREAD

**Issue by mpmarinov** [Chia-Network/chia-blockchain#10625]
### What happened?

After the update I have lost 2.69 XCH... It is not fully synchronized. On 24.02.2022 I won a block with self pooling. But my wallet is synchronized only until 14.02.2022. It has been like this since yesterday. Total Network Space 28.153 EiB since yesterday and changes almost like not...

Is there problem with version 1.3.0?

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by mariano54** [comment]
Can you try deleting ~/.chia/wallet/db and all files in there, and start chia again?

**Comment by mariano54** [comment]
This might be related to the plotnft syncing issue as well, did you obtain any pool rewards?

**Comment by mpmarinov** [comment]
No. I am in self pooling. But I have installed 1.2.11 again. Otherwise I'm just getting busy with synchronization.

Version 1.3.0 is not ready yet. Otherwise I liked.

Hopefully you will get in touch when the bugs are fixed....

**Comment by emlowe** [comment]
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by emlowe** [comment]
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5
