### ISSUE TITLE
[Bug] The harvester network is not automatically updated in GUI v 1.3.0. 

### ISSUE THREAD

**Issue by hevren14** [Chia-Network/chia-blockchain#10622]
### What happened?

The harvester network is not automatically updated in GUI v 1.3.0. 

I started the GUI, only the harvester in GUI was online as it's supposed to be. After I ran six harvesters,  still only the harvester in GUI was online. However, they did not seem online in the harvester network; they participated the farming. When I exited the GUI and started it again, all harvesters seemed online. When I closed the harvesters one by one, they didn't participate in farming naturally, but all the harvesters seemed online in the harvester network section. 

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to provide more details for this? Perhaps screenshots, or logs?

**Comment by hevren14** [comment]
> Are you able to provide more details for this? Perhaps screenshots, or logs?
![1](https://user-images.githubusercontent.com/101264873/157776454-94fed4c6-3f24-4a80-8a53-64d67e15b2c8.jpg)
![2](https://user-images.githubusercontent.com/101264873/157776465-0b4ca195-be41-4fe1-81f7-01d392f35ddd.jpg)
![3](https://user-images.githubusercontent.com/101264873/157776475-bdf9d2d9-52fb-4b9e-bda8-bc2ac1a2c20d.jpg)
![4](https://user-images.githubusercontent.com/101264873/157776483-ed819f8f-10c8-4f5f-a771-5f2575a35080.jpg)
![5](https://user-images.githubusercontent.com/101264873/157776490-958a9781-e84e-44a6-aa89-7d98a6bc33a2.jpg)

**Comment by wallentx** [comment]
I see. So it appears that in the Farm section, the status of the harvester's aren't updated in real time, and are only displaying the status of them at the time of launch.

**Comment by emlowe** [comment]
Not sure if we have a refresh notification for this - but it seems a reasonable thing to do.

Thanks for the detailed report!

**Comment by seeden** [comment]
Added missing event get_connections for farmer service https://github.com/Chia-Network/chia-blockchain-gui/pull/657.
