### ISSUE TITLE
[Bug] 1.3.0 GUI Pool tab showing malformed address

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#10635]
### What happened?

[config.yaml.txt](https://github.com/Chia-Network/chia-blockchain/files/8219139/config.yaml.txt)

I run my wallet/farmer/harvester/full_node on my Arch Linux (btw) server. I use the chia CLI. I had just upgraded from the latest beta, to the 1.3.0 release, and everything was running fine.

- My farmer was 👍
- Immediately after updating to 1.3.0, I `chia start farmer` and let the node and the wallet get synced. This did not take very long. I did a `chia plotnft show`, and saw that my pool `payout_instructions` were changed from my desired cold-wallet address, to the `First wallet address` that shows when running `chia keys show`, which is *not* what I wanted :-1:
- I `chia stop all -d` and checked for zombies, and there were none :+1:
- I modified my `config.yaml` to use the correct address by putting in my cold wallet address - *IN REGULAR ADDRESS FORMAT - NOT IN PUZZLE HASH FORMAT* - value into the `.pool.pool_list[].payout_instructions` key, and I then executed `chia start farmer`, and once again let every thing sync (did not take long), and checked that my address was correct with `chia plotnft show`, and I saw that the value of `Payout instructions (pool will pay to this address):` was correctly set to my cold wallet address 👍
- I was reading in the Keybase support chat after release, and saw a bunch of people say they were having issues with the `Pools` tab of their Chia 1.3.0 GUI being broken. There were so many, that I decided to see if maybe the GUI alone was broken, even if everything else was working fine for me. I enabled X11-forwarding, connected to my server, installed the chia GUI, and ran `sh start-gui.sh`, and went to the pools tab to see that my GUI was also displaying incorrect, and invalid information :-1: 

![2022-03-08_04-45](https://user-images.githubusercontent.com/8990544/157564210-6df8cdf0-fd4d-43f5-95f7-ad6ae4608c8d.png)

- I opened developer tools to see if anything was complaining, but there wasn't
- I verified that my `config.yaml` was not then displaying the same corrupt information that my GUI wallet was. My wallet info was still good :+1: 
- I started tailing my debug logs, and saw nothing odd :+1: 
- I selected `Edit Payout Instructions` in the GUI, and the pop-up window displayed, and had that same short `xch1jlgazv` address :-1: 
- I modified the address to the correct address that was already set in my `config.yaml`, and clicked `Save`. The screen flashed to a quick loading animation, but immediately popped back up to the input window. I wasn't sure if it had "saved", since the expected UI behavior is to no longer display the input prompt after saving, if the input has been accepted successfully :man_shrugging: 
- I clicked `Cancel` on the popup, and was back to the normal view of the `Pool` tab, except that it was now showing my `Payout Address` correctly.
- I checked `chia plotnft show` and verified that my address was still okay, and it was :+1: 
- I checked my `config.yaml`, and it was also okay :+1: 

### Version

1.3.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
The cause of this bug, is if you put in a `Receive Address` in the `payout_instructions:` field of your `config.yaml`, the GUI will render it as a messed up address.

If you instead put in the `Receive Address` as a `PUZZLE HASH` (https://www.chiaexplorer.com/tools/address-puzzlehash-converter) with the prefix removed, the GUI is fine.

`a5915f7b2cc5ee3f3431ce8ebb801d4e9ed9538e3d48e59c0e9c884f26fc3506` = Good rendering in GUI
`xch15kg477evchhr7dp3e68thqqaf60dj5uw84ywt8qwnjyy7fhux5rqz3jq57` = Bad rendering in GUI

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/655
