### ISSUE TITLE
[Bug] Unable to claim self-pooling rewards in CLI or GUI after upgrade to 1.3

### ISSUE THREAD

**Issue by iced-caffeine** [Chia-Network/chia-blockchain#10640]
### What happened?

I am unable to claim self-pooling rewards after upgrading to 1.3 from 1.2.11.  I understand that there is a known issue with the CLI, but the GUI appears to fail as well.  Specifically I am take the following steps:

1. Go to Pool tab
2. Click "Claim Rewards"
3. In the dialog screen, the text shows "You will receive 1.75 XCH to" and does NOT show any receiving address.  There is also no way to enter an address into this area.
4. For the sake of trying to see if this would work anyways, I confirmed the transaction with 100k mojo to give it some priority.
5. Transaction with 100k mojo fee shows as pending in my wallet, but nothing happens.  I assume this is because it is an invalid transaction (due to missing address) however I don't know how to try to confirm this.

It is also worth noting that if I go to "Manage Farming Rewards" from the Farm tab, I receive the warning "No private keys for one or both addresses. Safe only if you are sending rewards to another wallet."  and both the Farmer Reward Address and the Pool Reward Address text boxes are blank.  However, the xch_target_address field for the farmer and the pool are filled in properly in the config.yaml file.

I have tried upgrading the DB, and I have also tried fully deleting the wallet db's.

I'm not sure where the root cause is on this one, but something definitely appears to have not made the transition from 1.2.11 to 1.3 properly
![chia_claim_rewards_address_missing](https://user-images.githubusercontent.com/101305165/157578750-e608ce5f-19bf-4115-b8e0-afe0a5b081df.png)
.

### Version

1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by klosmariusz007** [comment]
I have exactly the same issue.

**Comment by iced-caffeine** [comment]
Maybe obvious since this issue is still open, but the issue remains unresolved in 1.3.1, at least for me.

**Comment by emlowe** [comment]
It does work in my testing without a fee, however, due to dusting this means it can be difficult to get into the mempool and get the tx confirmed. It is for sure not working with a fee, we are working on it.

**Comment by iced-caffeine** [comment]
Ok, interesting and good to know.  Were you able to see the address in the windows GUI in your test (see photo) or did you just push the transaction through with no fee?

**Comment by emlowe** [comment]
It will show the payout address correctly on the pool overview screen, but once you click `claim rewards` it shows like in this bug - that is also not fixed yet.

**Comment by a6654196** [comment]
申请了1.75，但是钱包没有收到

**Comment by a6654196** [comment]
Applied for 1.75, but did not receive my wallet

**Comment by LYY-LYY** [comment]
![无标题](https://user-images.githubusercontent.com/48404760/161358246-60950c0b-d8e7-4539-987c-6283dabd88b8.png)
我也是从农村合作社提取之后，钱包显示记录但是一直不到账

**Comment by a6654196** [comment]
我的提现了1.75，然后钱包有一个减1.75&nbsp; 然后又加1.75， 合作社的1.75 不见了&nbsp; ，但是我提现的时候 钱包地址是上一次钱包地址，可能问题出在这里，然后查看钱包地址，好像是还没有确认，卡在15000左右，不知道要等多少天，&nbsp; 还能不能到账我也不清楚，15916841910&nbsp; 加V

**Comment by LYY-LYY** [comment]
请问申请的1.75可以找回吗？

**Comment by LYY-LYY** [comment]
请问申请的1.75XCH可以找回吗？

**Comment by chiavivi** [comment]
我的也是不能领取1.75，之耕种的，一直报错

**Comment by LYY-LYY** [comment]
现在才发现我是从农村合作社提取奖励的时候，错把费用当成提取奖励，费用直接输入1.75 ，请问还有挽回的可能性吗
![无标题](https://user-images.githubusercontent.com/48404760/162441301-f4adf03f-ecdd-46ae-b6c0-80b5e4269730.png)
？

**Comment by iced-caffeine** [comment]
Confirming I was successfully able to claim rewards in 1.3.4, however the "You will receive 1.75 XCH to ..." address shows a different address than the pool target address in the config.yaml.  The rewards showed up correctly at the address in the config.yaml, however the address shown in the claim rewards prompt was just whatever the current Receive address of the wallet was that is shown in the wallet receive tab.

**Comment by emlowe** [comment]
The self-claiming rewards always go to the wallet address and are not related to the pool target address in config.yaml

**Comment by catxch** [comment]
> Confirming I was successfully able to claim rewards in 1.3.4, however the "You will receive 1.75 XCH to ..." address shows a different address than the pool target address in the config.yaml. The rewards showed up correctly at the address in the config.yaml, however the address shown in the claim rewards prompt was just whatever the current Receive address of the wallet was that is shown in the wallet receive tab.

I still can't get the reward, tell me how you do it.

**Comment by catxch** [comment]
> The self-claiming rewards always go to the wallet address and are not related to the pool target address in config.yaml

Now I seem to be the only one left. who still can't receive the reward in the chia system
