### ISSUE TITLE
[Bug] Accepted offers status still shows as Pending Accept

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#10651]
### What happened?

Several of my offers that I created were accepted. The XCH I requested is in my wallet and the tx history shows as confirmed. The USDS I spent is similarly confirmed in my tx history. Yet the offers still show up in my Manage Offers "offers you created" as Pending Accept. See attached log. 

In screenshots, note that the XCH wallet tx history shows confirmed transactions for 2 XCH,  2XCH, 2XCH and 2.55XCH. All are confirmed. They correspond to USDS tx, and also to accepted offers that are still Pending Accept.

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/8225286/debug.log)
![Screen Shot 2022-03-10 at 8 33 04 AM](https://user-images.githubusercontent.com/86693700/157710052-fd896587-9425-49a0-a0c7-3c41900d5989.png)

![Screen Shot 2022-03-10 at 8 33 28 AM](https://user-images.githubusercontent.com/86693700/157710114-c826670b-68f7-46c4-ad89-2832dd40339c.png)
![Screen Shot 2022-03-10 at 8 33 56 AM](https://user-images.githubusercontent.com/86693700/157710200-88e82867-f75a-46f8-9164-b8fef7159c0e.png)

### Version

1.3 production

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
If you refresh, do the offers still show Pending?
