### ISSUE TITLE
[Bug] 1.3.0 white screen

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10658]
### What happened?

Launching the Chia app from background to foreground ends up with a white screen pretty frequently. Not exactly sure how long you have to wait for the app to be in background or if something else is triggering, but it seems at least 2-3 hours. This seems to happen more frequently then 1.2.12.

This is after I am fully synced to a local node and in farmer mode.

![Screen Shot 2022-03-10 at 5 08 12 PM](https://user-images.githubusercontent.com/93196638/157771214-874948f7-da87-4a22-b6c0-72fe94a7cff6.png)

hitting the reload option does fix it the GUI as a workaround. 

### Version

1.3.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'length')
    at bp (esm.js:4519)
    at ia (react-dom.production.min.js:157)
    at qs (react-dom.production.min.js:267)
    at Tu (react-dom.production.min.js:250)
    at Au (react-dom.production.min.js:250)
    at ku (react-dom.production.min.js:250)
    at bu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wo (react-dom.production.min.js:122)
us @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
hi @ react-dom.production.min.js:131
ms @ react-dom.production.min.js:220
Cu @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Du @ react-dom.production.min.js:252
bu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Go @ react-dom.production.min.js:123
Vo @ react-dom.production.min.js:122
vu @ react-dom.production.min.js:244
notify @ Subscription.js:15
notifyNestedSubs @ Subscription.js:85
o @ Subscription.js:90
v @ redux.js:296
(anonymous) @ queryLifecycle.ts:222
(anonymous) @ cacheLifecycle.ts:201
(anonymous) @ windowEventHandling.ts:13
(anonymous) @ polling.ts:24
(anonymous) @ invalidationByTags.ts:24
(anonymous) @ cacheCollection.ts:39
(anonymous) @ devMiddleware.ts:17
(anonymous) @ index.ts:61
(anonymous) @ index.js:20
dispatch @ redux.js:659
(anonymous) @ createAsyncThunk.ts:649
(anonymous) @ index.js:32
(anonymous) @ index.js:32
r @ createAsyncThunk.ts:709
Show 3 more frames
esm.js:4519 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at bp (esm.js:4519)
    at ia (react-dom.production.min.js:157)
    at qs (react-dom.production.min.js:267)
    at Tu (react-dom.production.min.js:250)
    at Au (react-dom.production.min.js:250)
    at ku (react-dom.production.min.js:250)
    at bu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wo (react-dom.production.min.js:122)

**Comment by andriitalkstech** [comment]
Can confirm this issue happened to me as well.
Restart of a wallet fixes the issue.

**Comment by Vitaliy-Steffensen** [comment]
You or the package are trying to access the length of an array which is not defined yet.
It sometimes happens to me if i try to get an array from a state where i havent set the initialvalues to be an empty array.

So the state shoud look like this useState([]) and bot useState() or useSate({}).

It can also happend due to javascripts var. When you use the var keyword for your variables it is possible to refference the variable before it is declared, and not get any compile error like with const or let. But if you try to refference the .length of the var thats not yet declared it would throw you an undefined runtime error

**Comment by esaung** [comment]
Haven’t experienced in 1.3.4, so I’m closing
