### ISSUE TITLE
DB update error

### ISSUE THREAD

**Issue by Liimp** [Chia-Network/chia-blockchain#10666]
### What happened?

I checked it three times and on different computers, there is always an error on phase 5.
Python 3.7 and 3.9
OS: Ubuntu 18.04 and Slackware 15.0 

### Version

1.3.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
[1/5] converting full_blocks
      25195.98 seconds                             
[2/5] converting sub_epoch_segments_v3
      101.57 seconds                             
[3/5] converting hint_store
      6495.97 seconds                             
[4/5] converting coin_store
     32202k coins 2509.2 coins/s  Traceback (most recent call last):
  File "chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "chia-blockchain/chia/cmds/chia.py", line 148, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "chia-blockchain/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "chia-blockchain/chia/cmds/db.py", line 32, in db_upgrade_cmd
    no_update_config,
  File "chia-blockchain/chia/cmds/db_upgrade_func.py", line 43, in db_upgrade_func
    convert_v1_to_v2(in_db_path, out_db_path)
  File "chia-blockchain/chia/cmds/db_upgrade_func.py", line 317, in convert_v1_to_v2
    bytes.fromhex(row[0]),
ValueError: non-hexadecimal number found in fromhex() arg at position 4
```

**Comment by emlowe** [comment]
I'm would initially think there is something wrong with your source DB - do your different computers actually have the same source DB (you copied it around) - or was it synced independently on each computer

**Comment by arvidn** [comment]
I agree. do you think there's a risk your database is corrupt? I wouldn't expect it to necessarily be noticed until you actually read the corrupt entry. In v1, coin IDs are always hex, maybe you could have a look at your `coin_store` table to see what the coin_name field contains.

**Comment by arvidn** [comment]
when you say you tested on different computers, did you copy the same database file from one node to all of them?

**Comment by Liimp** [comment]
> 

Yeah, I copied the table to another computer and tried to update it.
I'll try to synchronize the new database and upgrade.
Thank you!

**Comment by Liimp** [comment]
I checked DB and it has a lot of missing indexes. Resynced DB and everything is ok.

**Comment by ALTracer** [comment]
> I checked DB and it has a lot of missing indexes. Resynced DB and everything is ok.

How exactly did you "check DB"?
I'm facing this issue as well -- the conversion breaks at the end seemingly for unobvious reasons.

The first time I started the conversion from CLI while the farmer was running (and GUI too).
The second time I waited for sync, gracefully closed the full_node and friends, flushed all the Linux caches and initiated the upgrade. There was sufficient space on that exFAT drive. The conversion crashed in the end as well.

Logs: https://pastebin.com/pa3niKn9

**Comment by Liimp** [comment]
> > I checked DB and it has a lot of missing indexes. Resynced DB and everything is ok.
> 
> How exactly did you "check DB"? I'm facing this issue as well -- the conversion breaks at the end seemingly for unobvious reasons.
> 
> The first time I started the conversion from CLI while the farmer was running (and GUI too). The second time I waited for sync, gracefully closed the full_node and friends, flushed all the Linux caches and initiated the upgrade. There was sufficient space on that exFAT drive. The conversion crashed in the end as well.
> 
> Logs: https://pastebin.com/pa3niKn9


I resynced the db and got this error again. Apparently the database cannot be downloaded without losing indexes. As a result, now I started synchronization, after 5 minutes, stopped it, made an upgrade and then started synchronization again in db v2. I did not find another solution. 
You can check the database in sqlite, but that will only waste your time, because there will definitely be errors.

**Comment by arvidn** [comment]
> Apparently the database cannot be downloaded without losing indexes.

What do you mean by "losing indexes"?

this error message is a hint:

> sqlite3.OperationalError: database or disk is full

I believe the problem is that sqlite uses temporary files while building indices. This means it's using storage on other drives (say, the system drive) rather than where your database is stored.

A solution to this is to either set `TMP` (windows) or `SQLITE_TMPDIR` (unixes) to a directory where there's plenty of space.

There's an outstanding PR that attempts to improve the error message here: https://github.com/Chia-Network/chia-blockchain/pull/10494

Since your failure happens during the index-building step, you don't actually have to go through the whole conversion again, those indices will be rebuilt by the full node the first time it starts up with the new DB as well (but you may have the same issue with temp space).

**Comment by ALTracer** [comment]
@Liimp , what's your partition setup btw?

@arvidn Yes, indeed, I just tried to execute manually the CREATE INDEX command via sqlite3 (which shows up in the python backtrace), this hogs the 3 GiB free of 32 GiB on my root partition (as in `/`) and dies afterwards with an

`Error: stepping, database or disk is full (13)`

I'll try exporting the SQLITE_TMPDIR before trying `chia upgrade db` or the sqlite3 commands.

For the record, `chia db validate` refuses to check the v2 file of 32 GiB (as opposed to 71 GiB v1, height 1690000) because `Database is missing version table`

**Comment by Liimp** [comment]
> what's your partition setup btw

ext4

**Comment by Liimp** [comment]
> @Liimp
> 
> > Apparently the database cannot be downloaded without losing indexes.
> 
> What do you mean by "losing indexes"?
> 
> this error message is a hint:
> 
> > sqlite3.OperationalError: database or disk is full
> 
> I believe the problem is that sqlite uses temporary files while building indices. This means it's using storage on other drives (say, the system drive) rather than where your database is stored.
> 
> A solution to this is to either set `TMP` (windows) or `SQLITE_TMPDIR` (unixes) to a directory where there's plenty of space.
> 
> There's an outstanding PR that attempts to improve the error message here: #10494
> 
> Since your failure happens during the index-building step, you don't actually have to go through the whole conversion again, those indices will be rebuilt by the full node the first time it starts up with the new DB as well (but you may have the same issue with temp space).

I cant explain and didn't save log. Maybe I will check DB againg and write log here.

**Comment by Liimp** [comment]
> @Liimp
> 
> > Apparently the database cannot be downloaded without losing indexes.
> 
> What do you mean by "losing indexes"?
> 
> this error message is a hint:
> 
> > sqlite3.OperationalError: database or disk is full
> 
> I believe the problem is that sqlite uses temporary files while building indices. This means it's using storage on other drives (say, the system drive) rather than where your database is stored.
> 
> A solution to this is to either set `TMP` (windows) or `SQLITE_TMPDIR` (unixes) to a directory where there's plenty of space.
> 
> There's an outstanding PR that attempts to improve the error message here: #10494
> 
> Since your failure happens during the index-building step, you don't actually have to go through the whole conversion again, those indices will be rebuilt by the full node the first time it starts up with the new DB as well (but you may have the same issue with temp space).

sqlite> row 77716179 missing from index coin_puzzle_hash

This DB I synced yesterday (full sync). With old DB I had ~15-20 errors like this.

**Comment by arvidn** [comment]
> sqlite> row 77716179 missing from index coin_puzzle_hash
> 
> This DB I synced yesterday (full sync). With old DB I had ~15-20 errors like this.

Interesting. Perhaps I'm wrong about the db being consistent after failing during index-building.

**Comment by Liimp** [comment]
> > sqlite> row 77716179 missing from index coin_puzzle_hash
> > This DB I synced yesterday (full sync). With old DB I had ~15-20 errors like this.
> 
> Interesting. Perhaps I'm wrong about the db being consistent after failing during index-building.

I don't know :)
I couldn't upgrade two DBs and it is so sad

**Comment by arvidn** [comment]
> I don't know :)
> I couldn't upgrade two DBs and it is so sad

I'm pretty confident this is because of temporary space. you could try running `chia db upgrade` again after setting `TMP` or `SQLITE_TMPDIR` to a path with plenty of space

**Comment by arvidn** [comment]
also, if you're syncing a new DB from scratch, `chia init` will create a v2 database by default

**Comment by Liimp** [comment]
> also, if you're syncing a new DB from scratch, `chia init` will create a v2 database by default
I'l check it. TY

**Comment by Liimp** [comment]
> also, if you're syncing a new DB from scratch, `chia init` will create a v2 database by default

it's incredible. Same PC, same db, same size of tmpfs, same sdd and I did it :) But I did full DB check. 
I don't know how, but it works)))

initializing v2 version
initializing v2 block store
height: 1689665
[1/5] converting full_blocks
      587.28 seconds                              
[2/5] converting sub_epoch_segments_v3
      8.30 seconds                             
[3/5] converting hint_store
      12.69 seconds                             
[4/5] converting coin_store
      1720.70 seconds                             
[5/5] build indices
      block store
      coin store
      hint store
      411.11 seconds                             
updating config.yaml
database_path: db/blockchain_v2_CHALLENGE.sqlite

LEAVING PREVIOUS DB FILE UNTOUCHED blockchain_v1_mainnet.sqlite
