### ISSUE TITLE
Starting services Full Dode [Bug] 

### ISSUE THREAD

**Issue by jama9999** [Chia-Network/chia-blockchain#10671]
### What happened?

Endless starting services after replacing full node db
![123](https://user-images.githubusercontent.com/77139949/157900073-c9d30764-8fe4-43b1-8897-3a4d1388adea.png)

### Version

1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by sifanjiao** [comment]
我也出现同样的错误
