### ISSUE TITLE
V1.3.0 will not open on Mac 10.14.6 - Chia daemon fails to start because of keyring error?

### ISSUE THREAD

**Issue by S1m0nP1** [Chia-Network/chia-blockchain#10687]
### What happened?

Upgraded to 1.3.0 from 1.2.11 and GUI never loads, just displays: "loading keyring status"
Problem seems to be an error in getting password from the keyring?

### Version

1.3.0

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
simons-MacBook-Pro:~ simonperfitt$ chia version
1.3.0
simons-MacBook-Pro:~ simonperfitt$ chia start wallet
Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "keyring/backends/macOS/__init__.py", line 49, in get_password
NameError: name 'api' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 152, in <module>
  File "chia/cmds/chia.py", line 148, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/chia.py", line 123, in run_daemon_cmd
  File "chia/util/keychain.py", line 476, in is_keyring_locked
  File "chia/util/keychain.py", line 644, in has_master_passphrase
  File "chia/util/keyring_wrapper.py", line 190, in get_shared_instance
  File "chia/util/keyring_wrapper.py", line 121, in __init__
  File "chia/util/keyring_wrapper.py", line 131, in refresh_keyrings
  File "chia/util/keyring_wrapper.py", line 173, in _get_initial_cached_passphrase
  File "chia/util/keyring_wrapper.py", line 333, in get_master_passphrase_from_credential_store
  File "keyring/backends/macOS/__init__.py", line 50, in get_password
NameError: name 'api' is not defined
[2550] Failed to execute script 'chia' due to unhandled exception!
Daemon not started yet
Failed to create the chia daemon
```

**Comment by athena9** [comment]
+1 with slightly different output.

After deleting wallet DBs due to incorrect balance starting Chia logs:

"ERROR failed to migrate keys silently. Run 'chia keys migrate manually'"

Which produces:

File "chia/util/keyring_wrapper.py", line 556, in get_passphrase
AttributeError: 'NoneType' object has no attribute 'get_password'

**Comment by emlowe** [comment]
This feels somewhat like you have some old processes left running. Please see if a reboot helps

**Comment by S1m0nP1** [comment]
> 

Thanks, but I have tried multiple times - reboot, delete .chia folder etc. GUI never loads, just displays: "loading keyring status"

**Comment by S1m0nP1** [comment]
1.2.11 works fine (apart from some sync issues)

**Comment by paninaro** [comment]
The provided backtrace seems to indicate that is an issue with the python keyring module. I'm not sure why 1.2.11 would work fine given as the module hasn't been updated. We could possibly look at bumping the keyring module version, though we'd want to let a change like that bake for a while.

**Comment by paninaro** [comment]
@S1m0nP1 are you comfortable with git cloning the `chia-blockchain` repository and trying to update the keyrings module version? I'd be curious to know if editing `setup.py` and changing `"keyring==23.0.1"` to `"keyring==23.1.0"`

`git clone git@github.com:Chia-Network/chia-blockchain.git`
`cd chia-blockchain`
(edit setup.py changing "keyring==23.0.1" to "keyring==23.1.0")
`sh install.sh`
`. ./activate`
`chia run_daemon`

**Comment by S1m0nP1** [comment]
That seems to remove the error:

(venv) simons-MacBook-Pro:chia-blockchain simonperfitt$ chia run_daemon
Chia directory /Users/simonperfitt/.chia/mainnet
/Users/simonperfitt/.chia/mainnet already exists, no migration action taken

{"ca_crt": "/Users/simonperfitt/.chia/mainnet/config/ssl/ca/private_ca.crt", "cert": "/Users/simonperfitt/.chia/mainnet/config/ssl/daemon/private_daemon.crt", "key": "/Users/simonperfitt/.chia/mainnet/config/ssl/daemon/private_daemon.key", "message": "cert_path", "success": true}

**Comment by S1m0nP1** [comment]
<img width="1056" alt="Screenshot 2022-03-15 at 11 12 01" src="https://user-images.githubusercontent.com/87375676/158365829-b518f914-4cc4-4773-9fcf-8648ed30c9d9.png">

**Comment by paninaro** [comment]
@S1m0nP1 thanks for checking that. I'll add a task to update the module.

**Comment by emlowe** [comment]
@S1m0nP1 Can you confirm a couple things in your initial report.
1) are you using the DMG installer, or git clone/setup.sh (in the initial report)
2) if not using the DMG, which version of python do you have?

**Comment by S1m0nP1** [comment]
> 
1. I used the DMG installer
2. (Python 3.9.5)

**Comment by wallentx** [comment]
The DMG that we are building currently doesn't work for Mojave, but you can git clone, and execute `sh install.sh`, it should work fine until we sort out our DMG issues.

**Comment by gregallen** [comment]
This could just be a lock file in the `.chia_keys` directory - see:
see https://github.com/Chia-Network/chia-blockchain/issues/10648#issuecomment-1080524521

**Comment by emlowe** [comment]
There will be a specific release of 1.3.5 for 10.14 - a separate DMG. It's not published yet on the download page, but will be soon.

You can get a copy of the 10.14 specific DMG from the github release page https://github.com/Chia-Network/chia-blockchain/releases/tag/1.3.5

**Comment by emlowe** [comment]
Specific 10.14 release is available on the chia download page. Closing issue
