### ISSUE TITLE
[Bug] 1.3 wallet balances are incorrect

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#10699]
### What happened?

Last night my wallet on my M1 Mac showed I had 18 XCH, when node was fully synched. This morning it shows only 7.94 XCH. Doing a manual count of the offer I created and that have been accepted, I should have 18+ XCH. Force reload doesn't change the balances. Something is definitely wrong with how the wallet is displaying balances in the GUI. CLI also shows 7.94 XCH. Logs attached. 

Double checked with my Intel Mac machine, also running 1.3, and it indeed shows 18XCH in the GUI. 
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/8238333/debug.log)

### Version

1.3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

![Screen Shot 2022-03-12 at 11 57 50 AM](https://user-images.githubusercontent.com/86693700/158033333-5d3ec970-2217-4c24-9ab1-c4e9ecc4c0fb.png)

![Screen Shot 2022-03-12 at 12 05 25 PM](https://user-images.githubusercontent.com/86693700/158033328-3bdfb9b1-e368-4043-a578-b49846399a5d.png)

**Comment by paulhainsworth-chia** [comment]
Update: After quitting the M1 client and starting it a couple times, the balance now is correctly displayed. Still need to root cause this issue.

**Comment by brianjojoray** [comment]
I have the same problem. The wallet blance is incorrect still

**Comment by JimbiniBambini** [comment]
My balances on Win10 machine are changing randomly everytime I restart the client. I tried also to resync the wallet, but the issue still persists. Sadly it doesn't display any additional coins, only in the "minus" direction :D

**Comment by doggeh** [comment]
I too am experiencing this. CLI shows the correct balance on my linux server. The GUI on my fully synced Windows box shows a balance 1.3XCH lower.

**Comment by emlowe** [comment]
Possibly fixed in #11338

**Comment by emlowe** [comment]
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5
