### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Alanbor88** [Chia-Network/chia-blockchain#10697]
### What happened?

when updating to the last versio, the chias that I had bought disappeared, I only have the farmeadas, and it is well siencronizado

### Version

Version 1.3.0 | 64 bit

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by shaneo257** [comment]
have you removed your wallet db and let it resync, your chia haven't disappeared as its still on the blockchain

**Comment by Alanbor88** [comment]
no, just update, nothing was deleted and no re-syncing

**Comment by shaneo257** [comment]
close the client, delete the wallet db, then reopen and let it resync

**Comment by ljboy1979** [comment]
the same as me

**Comment by wallentx** [comment]
There are a few known issues in 1.3.0+. Can you try the Latest Dev build at https://www.chia.net/download/ and see if this fixes it for you? You'll need to resync your wallet DB.
