### ISSUE TITLE
[BUG] rc3 Gui failed to start plotting "Loading..." in log

### ISSUE THREAD

**Issue by dorkmo** [Chia-Network/chia-blockchain#1069]
In both windows and ubuntu stalled out a "Loading..."

![image](https://user-images.githubusercontent.com/1923070/109234163-cf30a600-7790-11eb-98d6-3a973631a7cf.png)

**Comment by dorkmo** [comment]
just tried View > Reload, no luck. Nothing happening in the temp folder either...

**Comment by hoffmang9** [comment]
Confirmed and replicated - chasing it.

**Comment by dorkmo** [comment]
all gravy! thanks again!
