### ISSUE TITLE
[Bug] Unable to switch plotnft to self-pooling

### ISSUE THREAD

**Issue by robeclar1970** [Chia-Network/chia-blockchain#10703]
### What happened?

unable to transfer to self pooling or any other   stuck with core pool server.com

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Copper Felidae
Pool:

https://core.pool-server.com
Status
Self Pooling
Unclaimed Rewards
0 XCH

Number of Plots
340
Launcher Id


Payout Address
```

**Comment by emlowe** [comment]
This may be fixed in 1.3.1 - recommend you upgrade and resync your wallet again.
