### ISSUE TITLE
Wallet on different PC have different balance[Bug] 

### ISSUE THREAD

**Issue by Poss77** [Chia-Network/chia-blockchain#10714]
### What happened?

I have two PC with the Chia GUI 1.3.0 (Windows 11).  The wallet are both synced and they show a different balance.  Also, I create an offer on one of them and the spendable balance didn't change on my second PC, is that normal?

![image](https://user-images.githubusercontent.com/82526500/158072253-68cc070a-c78f-41be-b4d6-aec589357b32.png)

![image](https://user-images.githubusercontent.com/82526500/158072264-32881c54-2e68-437d-afbb-db79d91cc4a3.png)

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Creating an offer is a local event, it doesn't go on the blockchain, so there is no way for the second computer to detect it until this offer is accepted, so this is expected.

**Comment by Poss77** [comment]
that make sense for the offer.  There is still a problem with different balances on different PC

**Comment by ZeroCool-NT** [comment]
I have a similar problem, only the balances of coins are not so impressive. What would not pump the blockchain from the Internet to the second car added the Chia wallet to simple copying of the same folders from the first machine

**Comment by wallentx** [comment]
There are a few known issues in 1.3.0+. Can you try the Latest Dev build at https://www.chia.net/download/ and see if this fixes it for you? You'll need to resync your wallet DB.
