### ISSUE TITLE
[Bug] Большая проблема в работе клиента 1.3.0, solo mining не работает, нет возможности вывести CHIA за NFT через запрос вознаграждения

### ISSUE THREAD

**Issue by iJeys** [Chia-Network/chia-blockchain#10719]
### What happened?

Заметил большую проблему, которую постараюсь объяснить.
Сильно различаются балансы кошельков в версии 1.2.11 (db.v1) и 1.3.0 (db.v2) и я знаю с чем это связано
![1](https://user-images.githubusercontent.com/74445568/158113995-4cc49811-05b8-4b1c-9d22-663c361a3f7e.PNG)
1. Я занимаюсь SOLO майнингом и запрашиваю вознаграждения через CLAIM REWARDS
2. Когда мы запрашиваем вознаграждение без разницы через какой клиент 1.2.11 или 1.3.0 то вознаграждение 1.75 Chia падает в кошелёк 1.3.0 но не падает в кошелёк 1.2.11
3. В итоге мы получаем такое расхождение балансов на кошельке.
4. И недавно случилось вообще непонятное, награждение за два последних блока упали полностью на SOLO POOL и теперь я не могу их запросить, они попросту не выводятся.
![2](https://user-images.githubusercontent.com/74445568/158114863-a37dd67b-d8b3-4742-bfa6-23f3f23769d6.PNG)
5. У меня NFT плоты и награда для майнера не должна падать в POOL
![3](https://user-images.githubusercontent.com/74445568/158114471-397ead14-70aa-4560-a29b-b76484c3236e.PNG)

https://xchscan.com/address/xch1sm96egxnz7zpxxulvrhmphk43n0fpjdylrwjsp3d7uvs0jyjndeqnfaa6c

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by lcgogo** [comment]
@iJeys 

The blog mentions Database Version 2.0 , not sure it's the root cause.

https://www.chia.net/2022/02/10/1.3-beta-release.en.html

**Comment by iJeys** [comment]
> https://www.chia.net/2022/02/10/1.3-beta-release.en.html

Я не могу запросить награду с адреса контракта.  Она попросту не выводится

**Comment by wallentx** [comment]
Can you try and resync your wallet DB with 1.3.1? Please note that claiming with a fee currently does not work, and claiming without a fee results in transactions taking a long time to finish due to network congestion. We are working on it!
