### ISSUE TITLE
Stuck at connecting to wallet

### ISSUE THREAD

**Issue by zyrke1** [Chia-Network/chia-blockchain#10733]
![image](https://user-images.githubusercontent.com/101621810/158317725-e6eb6c39-d5f4-4817-8f1c-fecb8c10d2af.png)

**Comment by pipilu2022** [comment]
I have the same problem as you. can't enter Chia Blockchain 1.3.1 in windows 10 system. loading 1 hours , can't enter.
![33](https://user-images.githubusercontent.com/101960047/159147136-bc4f2d0a-d4d9-4445-8ed3-36e2de665cd9.png)

**Comment by wallentx** [comment]
Are you able to reboot your system and see if this resolves it? If it does not, are you able to provide us with logs? You may also want to try and start chia via the command line, rather than the GUI.
