### ISSUE TITLE
[BUG] Can not install On Manjaro (ArchLinux)

### ISSUE THREAD

**Issue by ayaseen** [Chia-Network/chia-blockchain#1075]
**Describe the bug**
I got an error while I am trying to install chia with python3.9 on Manjaro:

ERROR: Could not find a version that satisfies the requirement miniupnpc==2.1
ERROR: No matching distribution found for miniupnpc==2.1

**To Reproduce**

I follow those steps:

- python -m venv venv
- source venv/bin/activate
- pip install --upgrade pip
- pip install -i https://hosted.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10

The output:

Looking in indexes: https://hosted.chia.net/simple/
ERROR: Could not find a version that satisfies the requirement miniupnpc==2.1
ERROR: No matching distribution found for miniupnpc==2.1

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Manjaro 20
- CPU: Amd Ryzen 9

**Comment by hoffmang9** [comment]
Should be fixed by https://github.com/Chia-Network/chia-blockchain/pull/1181 and will be in the next release.
