### ISSUE TITLE
Connection not restored after internet outage.

### ISSUE THREAD

**Issue by staviq** [Chia-Network/chia-blockchain#1076]
0.2.2, Windows gui.

I had a small ~5min internet outage yesterday, and the chia connection did not recover after internet came back.

It's stuck, since yesterday.

Height 39947

Last blocks stuck unfinished from around 4pm from the day before.

[debug.zip](https://github.com/Chia-Network/chia-blockchain/files/6048442/debug.zip)

**Comment by dorkmo** [comment]
rc4 came out this morning, might give it a try too

**Comment by staviq** [comment]
Dumb question, wht am i supposed to do at "Drag and drop your backup file" ? I don't see any option to make backup from gui from the previous version ?

**Comment by hoffmang9** [comment]
It's a backup of non vanilla wallet data - Coloured coins or rate limited wallets. Skip.

I test - far too often - that chia-blockchain will reconnect and sync when a laptop is hibernated and moved to a new network. Was your router confused about uPnP after the outage?

**Comment by mariano54** [comment]
I got the same issue after losing wifi, my node did not recover. This was defnitely working a few months ago, not sure when we broke it.

Also, I was syncing and the sync did not cancel properly.

**Comment by mariano54** [comment]
Fixed by this: https://github.com/Chia-Network/chia-blockchain/pull/1095
