### ISSUE TITLE
[Bug]Upgrade to 1.3 《 This should be below 5 seconds to minimize risk of losing rewards.》

### ISSUE THREAD

**Issue by jackwalk** [Chia-Network/chia-blockchain#10762]
### What happened?
<img width="838" alt="1647396384(1)" src="https://user-images.githubusercontent.com/811100/158502392-f01c52d9-9773-4bda-975e-1c6ffc831570.png">
<img width="733" alt="1647397004(1)" src="https://user-images.githubusercontent.com/811100/158503451-41fa3452-2b0f-4b15-bfdb-56ad34b7b8e4.png">

Problems after upgrade
Appears every few minutes

### Version

1.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by jackwalk** [comment]
Returned version 1.2.11 normal

**Comment by jackwalk** [comment]
Appears every few minutes

**Comment by wallentx** [comment]
Hi, thank you for reporting!
This is actually a duplicate of https://github.com/Chia-Network/chia-blockchain/pull/10675, and we already have a fix for it merged in.
