### ISSUE TITLE
 farmer payout address

### ISSUE THREAD

**Issue by Slepoiy** [Chia-Network/chia-blockchain#10779]
### What happened?

On the harvester after updating to version 1.3, the fields "address of payments to the farmer" and "address of payments to the pool" are empty.

When I try to specify the wallet where I store XCH and re-enter the settings, these fields are empty again.

The question arises, where will 0.25 XCH go if I win the block? What needs to be done to fix this
![Снимок экрана (30)](https://user-images.githubusercontent.com/94319776/158694987-262a4125-baa6-4496-80a9-f24d0eb0e2a0.png)
?

### Version

1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Thanks - this fixed in 1.3.1

But your address is stored correctly in config.yaml
