### ISSUE TITLE
RC3 will not plot

### ISSUE THREAD

**Issue by pauliedi** [Chia-Network/chia-blockchain#1078]
Attempting to plot K-32 & 33.. When viewing view log, it is hung at "Loading..." Tried several reboots, then let run overnight. Still stuck at "Loading..." 
Update...see Java script error attached.
<img width="431" alt="JAVA ERROR Capture" src="https://user-images.githubusercontent.com/79347951/109298183-2ec69a00-7801-11eb-8054-3bdf88f0a36d.PNG">

**Comment by dorkmo** [comment]
be sure to update to rc4

**Comment by hoffmang9** [comment]
Fixed by RC4
