### ISSUE TITLE
[Bug] "help translate" link of the language menu in GUI leads to 404

### ISSUE THREAD

**Issue by brause** [Chia-Network/chia-blockchain#10784]
### What happened?
when changing to language of the gui the first link is "help translate".
it leads to 
https://github.com/Chia-Network/chia-blockchain-gui/tree/main/src/locales/README.md
which is a 404 file not found.

needs to be changed to 
https://crowdin.com/project/chia-blockchain
i guess.

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Fixed by https://github.com/Chia-Network/chia-blockchain-gui/pull/697
I believe will be in 1.3.5

**Comment by seeden** [comment]
Already fixed.
