### ISSUE TITLE
[Bug] When you close and open chia gui, the farm don't start till it's full sync and you open farm section

### ISSUE THREAD

**Issue by javirub** [Chia-Network/chia-blockchain#10796]
### What happened?

Started at 1.3.0 but still happening in 1.3.1, when you close your wallet and you have to sync again, it fully syncs but don't start farming until it's fully sync and you go to farm section, so if you open chia and leave home you could be losing farm revenue for days or weeks...

How to replicate:
1- Close wallet.
2- Open wallet.
3- Don't enter into farm.

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by msterm** [comment]
my farming has stopped. It says syncing. But from the beginning. And nothing is happening. Syncing doesn't work either.

**Comment by emlowe** [comment]
closing old issue
