### ISSUE TITLE
[Bug] Farmer - PlofNFT goes to unrecoverable farming state (until restart)

### ISSUE THREAD

**Issue by FazendaPool** [Chia-Network/chia-blockchain#10806]
### What happened?

Found this bug while testing our pool on testnet:
- If you start the farmer and for some reason it cannot connect to the pool to fetch difficulty via `/get_farmer`, plotNFT will enter unrecoverable farming state as shown on the log below.
- Requires a restart and a successful connection to the pool at start to work properly.

### Version

1.3.2.dev26

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-03-19T18:26:38.917 farmer chia.farmer.farmer         : WARNING  No pool specific difficulty has been set for 330b318ffade3d526d893d4dc8a3acd5f9d05ed6fec67994100f08cf0a9450d2, check communication with the pool, skipping this signage point, pool: http://127.0.0.1:5555
```

**Comment by scrutinously** [comment]
Were you able to come up with any kind of workaround/fix for this?

**Comment by FazendaPool** [comment]
yes, you can manually fix it by going to self-pooling and deleting unconfirmed transactions. But i had to delete the unconfirmed transactions more than once.

**Comment by scrutinously** [comment]
Just to add some more info, I've encountered 7 windows farmers running varying versions of 1.3.x that have had this issue happen on mainnet.

**Comment by xdustinface** [comment]
@FazendaPool @scrutinously Actually it should recover itself but there is currently a retry interval of one hour for the `GET /pool_info` call. Did you try to wait a bit more than one hour before you restarted? Would be cool if you could confirm. Also i opened a PR to change the interval to 5 minutes see https://github.com/Chia-Network/chia-blockchain/pull/11076.

**Comment by scrutinously** [comment]
> @FazendaPool @scrutinously Actually it should recover itself but there is currently a retry interval of one hour for the `GET /pool_info` call. Did you try to wait a bit more than one hour before you restarted? Would be cool if you could confirm. Also i opened a PR to change the interval to 5 minutes see #11076.

Only one of the 7 people had it fix itself on its own, and that guy had chia running (effectively self pooling due to this issue) for over 10 days, then it suddenly stopped getting the pooling errors so we can assume was finally able to update the pool_info successfully on one of those 1 hour retries. 3 of those people were able to get it working again by utilizing the odd workaround identified by fazendapool, and 1 got it working by running the db upgrade (could just be coincidence and got a successful pool_info update after restarting?).

**Comment by emlowe** [comment]
Numerous changes to the code here likely have changed this environment for this issue.
Closing issue, will reopen if there are further comments added
