### ISSUE TITLE
[Bug]  Harvesters cannot connect to farms

### ISSUE THREAD

**Issue by JustAlias** [Chia-Network/chia-blockchain#10800]
### What happened?

[](url)Harvester runs on Linux ,Farm runs on Windows

I have 150 harvesters, all connected to a farm node

The harvester frequently lost connection, this is not a network problem, I tried to restart the harvester can not be solved, restart the farm service can be solved, but it will happen again next time

Not on a fixed harvester, 
they can't be reconnected once they go offline, only to restart farm service

When I had 200 harvesters, I also had lost connections on older versions. After I tried to reduce it to 150 harvesters, this didn't happen on 1.2.11, but is now very easy to happen on 1.3.1

![微信图片_20220319005805](https://user-images.githubusercontent.com/93747660/159048546-9c2e48fa-96f4-4976-b685-bbad87507678.png)

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Just to confirm, do you have 150-200 remote harvesters? This seems like a very large number which surprises me, so I want to make sure you really run this many harvesters

**Comment by JustAlias** [comment]
> 

yes! it's true

**Comment by JustAlias** [comment]
> 只是为了确认一下，您有 150-200 台远程收割机吗？这似乎是一个非常大的数字，让我感到惊讶，所以我想确保你真的运行这么多收割机

yes! it's true

**Comment by emlowe** [comment]
This deployment is something not really supported by the Chia software - running this many harvesters is not tested and is not a recommended deployment model.
