### ISSUE TITLE
[Bug] When sending CAT, wallet says transaction confirmed, but it is not found in blockchain

### ISSUE THREAD

**Issue by MojoWhaleCom** [Chia-Network/chia-blockchain#10815]
### What happened?

Sending CATs out to users, the wallet sees the transactions as confirmed, but they are not found in blockchain database and the user does not receive the token

### Version

1.3.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
$ chia wallet get_transaction -tx 0xef792db09b48f58abd7009cf489d5401d8430dcd1378a85119d99f3196adf816
Transaction ef792db09b48f58abd7009cf489d5401d8430dcd1378a85119d99f3196adf816
Status: Confirmed
Amount received: 0 XCH
To address: xch1yqg8r2jqf48aazk7lel37z3cqra3l0e55daxzh54cugmk3nyklxsn3fr67
Created at: 2022-03-20 20:00:15

$ chia wallet get_transaction -tx 0xdabb0f95fa89860729a543d7f85a34a3ccc59dce4892ccc40726c8c480388f9e
Transaction dabb0f95fa89860729a543d7f85a34a3ccc59dce4892ccc40726c8c480388f9e
Status: Confirmed
Amount received: 0 XCH
To address: xch1ej0mp5cyvyy9zddysdcq2cxywelct9dejhadk8s508yy8aeadj8qg2w7rm
Created at: 2022-03-20 20:00:10
```

**Comment by wallentx** [comment]
Thanks for reporting this! We are always working on improving the wallet, but the foundational baseline functionality is something we feel we have already mostly delivered on, and large scale transaction support like this is a future improvement we want to support but is much further out.  Being able to support high volume transactions at the scale you are looking for is akin to some of the enterprise solutions we work on, and generally speaking those are problems we tackle in a more structured way with our business partners and not part of our foundational open source development.

**Comment by MojoWhaleCom** [comment]
Hello,

I just checked our logs. Our faucet was doing 177 tx per day on average before switching to 1.3 and than 1.3.1 and adding cats. Than from March 10 to 17 there are 1377 claims in total, but first we added our own token, than others, totaling 5 CATS. So in 7 days there were around 5000 total transactions, XCH and CATs included. Would you consider this high traffic?

Please note the faucet runs on a separate server, away from our main site and also runs a full node. 

Thank you
