### ISSUE TITLE
Fetching submodule mozilla-ca results in "fatal: remote error: upload-pack: not our ref 7a45..."

### ISSUE THREAD

**Issue by flotti455** [Chia-Network/chia-blockchain#10814]
I'm upgrading chia from `1.2.11` (`b74a3f3849cadeece2fac3efa3cb55d7d3a0647f`) to latest `1.3.1` by following the [*update from source* documentation](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#update-from-source).

During the `git fetch` step, I get the following error:
```
Fetching submodule mozilla-ca
From https://github.com/Chia-Network/mozilla-ca
   cc65e26..20338a0  main       -> origin/main
fatal: remote error: upload-pack: not our ref 7a45e05b3b9cacadb40ee11d88cf07ac719ed637
fatal: the remote end hung up unexpectedly
```

**Comment by wallentx** [comment]
GitHub has been having issues the past few days. Are you able to try this again and see if it fixes it?

**Comment by emlowe** [comment]
Closing issue as this was a git/github problem and not related directly to chia
