### ISSUE TITLE
[Bug] lookup qualities daramatically increased after upgrading to 1.3.1

### ISSUE THREAD

**Issue by mmitech** [Chia-Network/chia-blockchain#10810]
### What happened?

Qualities lookup dramatically increased after upgrading to 1.3.1 it went from an average of less than 5 secs to more than 15 secs

![image](https://user-images.githubusercontent.com/4456920/159150758-a47ca669-fab9-48c7-8abb-506df6408c55.png)

This is also costing me a lot of stale partials on the pool side 

![image](https://user-images.githubusercontent.com/4456920/159150848-856a26bd-418c-406b-bd95-7b0a9bd3df28.png)

### Version

1.3.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by mmitech** [comment]
OK so changing the config values as mentioned here https://github.com/Chia-Network/chia-blockchain/issues/10701#issuecomment-1066030908 solved the issue for me

**Comment by mmitech** [comment]
Still getting a lot of stales, the average lookup time is down now but I am seeing way worst times than before.

**Comment by mmitech** [comment]
I downgraded back to 1.2.11, seems like 1.3.x is not production-ready yet.

**Comment by stefan-lange** [comment]
How many connections to other full nodes do you have? If the number is high, you could reduce them to 10 or 20. (I have 10 and it is working great)

**Comment by mmitech** [comment]
I had ~ 80, what is the logic behind reducing them if this worked perfectly before?

**Comment by stefan-lange** [comment]
The connection handling in chia seems to be, let's say, not efficent enough. On weaker systems (like the RPI) this will cause stales. After the first 'duststorm' I played with this setting and it was/is the solution for me. Had no more stales since then.

**Comment by loppefaaret** [comment]
> Still getting a lot of stales, the average lookup time is down now but I am seeing way worst times than before.

If you are on Keybase, please DM me @pyl 
i would love to get more into this - as 1.3.1 should contain some harvester changes that solved another issue in 1.3.0
How many total plots do you have on the harvester ?

**Comment by mmitech** [comment]
> > Still getting a lot of stales, the average lookup time is down now but I am seeing way worst times than before.
> 
> If you are on Keybase, please DM me @pyl i would love to get more into this - as 1.3.1 should contain some harvester changes that solved another issue in 1.3.0 How many total plots do you have on the harvester ?

I DMed you on Keybase, I have between 25K and 30K on my harvesters.

**Comment by mmitech** [comment]
bad farming performance still persist, as confirmed by the chia team as well

**Comment by xdustinface** [comment]
@mmitech Can you please try https://github.com/Chia-Network/chia-blockchain/pull/11204

**Comment by mmitech** [comment]
> @mmitech Can you please try #11204

I will try it this week, I am dealing with wallet issues now :D
