### ISSUE TITLE
1.3.1 arm64.deb hangs starting Full Node

### ISSUE THREAD

**Issue by cliveflint** [Chia-Network/chia-blockchain#10813]
I've just upgraded from an erlier version and the new app won't start up properly.

It gets to 
Starting Services
Full Node

and just doesn't get any further. It's been like this for more than 12 hours.

This is running on Raspberry Pi 4 8Gb 5.10.103-V8+

**Comment by emlowe** [comment]
Please provide log output and OS version

**Comment by wallentx** [comment]
Are you able to reboot your RPi and try again? There could be a few things that are causing this, but we need to see logs in order to further help.

**Comment by emlowe** [comment]
closing issue due to lack of response
