### ISSUE TITLE
[Bug] lost choose option Wallet/Farmer at startup

### ISSUE THREAD

**Issue by dial-888** [Chia-Network/chia-blockchain#10822]
### What happened?

After installing 1.3.1 (over 1.2.11) version at first start there was a screen where I was able to choose what to lanch - Wallet mode or Farmer mode. But at this first start in Farmer mode the Wallet balance was incorrect. So I closed the program and run it again. Now the balance are correct but I lost this mode screen at startup.

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MojoWhaleCom** [comment]
Click on Settings button on top right and choose it from there?

**Comment by emlowe** [comment]
The GUI remembers the last setting - it will always startup in the mode last chosen - it only asks at startup the first time. To switch modes, you use the setting button and restart the app. To switch back, you need to again use the setting button and restart the app. More improvements are expected, but the current process is you need to restart the app after each change.
