### ISSUE TITLE
[Bug] Wallet dust storms cause high transaction counts, in turn increasing wallet sync time considerably

### ISSUE THREAD

**Issue by SametBasturkk** [Chia-Network/chia-blockchain#10835]
### What happened?

They send to me always 1 mojo and my wallet part sync is taking so long time. maybe hours. This is my farm wallet I cannot change the address. 

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
'puzzle_hash': '0x6f5587a26826fce05048c03bab92d751c39692ef01bf99ce3081c6dc60ef46ab'} at 1606211 wallet_id:1
2022-03-22T13:22:28.912 wallet chia.wallet.wallet_state_manager: INFO     Adding coin: {'amount': 1,
 'parent_coin_info': '0x5bd7265b58d47b8d3d01362b926a79991ae365c1724cd6291ee17a8b3fc9260b',
 'puzzle_hash': '0x6f5587a26826fce05048c03bab92d751c39692ef01bf99ce3081c6dc60ef46ab'} at 1606213 wallet_id:1
2022-03-22T13:22:29.032 wallet chia.wallet.wallet_state_manager: INFO     Adding coin: {'amount': 1,
 'parent_coin_info': '0x5cadb775318b38e419f8b52172afb76b7ad7c70209f6ae1d15f1ffad5753bd44',
 'puzzle_hash': '0x6f5587a26826fce05048c03bab92d751c39692ef01bf99ce3081c6dc60ef46ab'} at 1606213 wallet_id:1
2022-03-22T13:22:29.096 wallet chia.wallet.wallet_state_manager: INFO     Adding coin: {'amount': 1,
 'parent_coin_info': '0x5a87dcb8c7fbbf37fab6df40a940f41bde6e0db9caa7b8eec8efc27117d687de',
 'puzzle_hash': '0x6f5587a26826fce05048c03bab92d751c39692ef01bf99ce3081c6dc60ef46ab'} at 1606219 wallet_id:1

and more and more
```

**Comment by cemalefendi** [comment]
I have also same problem wallet sync take hours

**Comment by zhangyongchang88** [comment]
我也是同样得问题，钱包升级后由于工作模式变更，现在新的几乎根本不会工作，一直显示正在同步中。我得农场有10p，我得钱包每天都会收到沙尘暴攻击。

**Comment by SametBasturkk** [comment]
> If you are running the wallet in standalone wallet mode, try and switch it to run a synced full_node as well - this will allow it to trust the local node database, and skip some verifications, and should speed up the wallets syncing speed. if you are already doing that (most farmers run the wallet together with the farming node) there isn't much more you can do at this point in time. apart from ensuring the databases are on SSD based devices i guess that what you would like to see, is a function that skips any transaction smaller than "X" mojo's from being processed ?

Yeah i think this İs the best way for fix. Than after sync it can calculate mojo's
