### ISSUE TITLE
[Bug] Sending cat transaction sometimes gets stuck in Pending

### ISSUE THREAD

**Issue by joeharrison714** [Chia-Network/chia-blockchain#10836]
### What happened?

Every so often when sending a CAT, the transaction will get a transaction ID but it's status will be stuck in Pending. If I restart the services, the transaction goes through rather quickly once the wallet is back up. I am running a full node along with the wallet.

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by joeharrison714** [comment]
I checked the log and there are no errors or warnings at the time that this happened

**Comment by wallentx** [comment]
possibly relates to https://github.com/Chia-Network/chia-blockchain/issues/10873

**Comment by joeharrison714** [comment]
Yes #10873 perfectly describes this issue I was seeing

**Comment by 0X1231** [comment]
+1
