### ISSUE TITLE
[Bug] Wallet GUI shows Synched but incorrect balances

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#10832]
### What happened?

Wallet has 23.5 XCH. 

Quit 1.3 app
Launch 1.3 app
Choose wallet that contains 23.5 XCH
Observe that once wallet shows status Synched, the balance is incorrect
Click around in the app, such as to Manage Offers, client back to XCH wallet
Observe that wallet status is still Synched, and balance has updated, but is still incorrect
Click around a bit more
Observe that wallet balance is now correct

### Version

1.3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by radiologyken** [comment]
I have the same issue.  I had 22 coins.  My UPS failed and when I powered back on the machine (v1.2.11), it would not sync.  I deleted the wallet DB file.  Before starting back up the Chia client, I updated to v1.3.0.  I started the chia client and it started syncing from 0.  Several days elapsed and it finally caught up.  There is a discrepancy in coins from my main machine vs my plotters.  

I compared transactions and it seems that between v1.3.0 did not recognize mined coins before 1/14/2022.  The only coins it's showing are ones I earned on 1/14/2022 and forward.  My plotters have coins earned from 1/7/2022 as well as others before that date.  

I'm running v1.3.0 on Win10 x64.  I can upgrade and resync if necessary.  I'm also willing to help troubleshoot if needed.

**Comment by wallentx** [comment]
Can you try the Latest Dev build at https://www.chia.net/download/ and see if this fixes it for you? You'll need to resync your wallet DB.

**Comment by emlowe** [comment]
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by emlowe** [comment]
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5
