### ISSUE TITLE
Memory leak in chia.exe process 1.3.1 [Bug] 

### ISSUE THREAD

**Issue by Jared-woodruff** [Chia-Network/chia-blockchain#10859]
### What happened?

A memory leak is observed in the chia.exe process over 24 hours while running on a farming machine using other 1.3.1 forked clients (SHIBgreen, BTCgreen & Flax), (Chia.exe --type=renderer) exhausts all system memory slowly overtime.

Hosting system:
Windows 10 21H1 (19043.1586) x64

Hardware Spec:
CPU: AMD Ryzen 3900x
RAM: 32GB at 3200 Mhz (14-14-14)
SSD: Samsung 980 Pro 1TB NVMe
NET: x2 10GbE Intel x540-T2

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
None
```

**Comment by mariano54** [comment]
Is this in the wallet or full node process? How much memory is consumed?

**Comment by Jared-woodruff** [comment]
> Is this in the wallet or full node process? How much memory is consumed?

It appears to be the main UI rendering process "Chia.exe --type=render" its currently sitting at 3.8GB for that process (it started at 380 MB when I last restarted the process 12 hours ago), when the memory hits the limit the UI just shows a white box but the farming process and full node processes continue to operate. 

I've upgraded the server to 96GB of ram yesterday which seems to be giving me more time between required restarts. If I only run the Chia client its memory growth is very slow, almost unnoticeable.

Only thing i notice from Procmon64 & Visual studio dumps is that it have Nvidia dll's loaded by the chia process (I'm assuming this is electron accessing hardware acceleration) but if it helps the GPU in use is GT 1030 [2GB DDR5] running driver version 512.15 [DCH]

The alts currently running on that server are:

- SHIBgreen [1.3.1 fork] _*DB Upgraded to v2_
- BTCgreen [1.3.1 fork] _*DB Upgraded to v2_
- Silicon [1.2.9 fork]
- aedge [1.2.9 fork]
- Transact [1.2.9 fork]
- FLAX [1.3.0 fork] _*DB Upgraded to v2_
- Flora [1.2.9 fork]
- ETHgreen [1.2.9 fork]
- Pecanrolls [1.2.9 fork]
- TAD [1.2.9 fork]
- Cryptodoge [1.2.9 fork]
- GreenDoge [1.2.9 fork]
- DogeChia [1.2.9 fork]

**Comment by wallentx** [comment]
Possibly relates to https://github.com/Chia-Network/chia-blockchain/issues/10916

**Comment by japetrov** [comment]
The same behaviour is observed in my ubuntu server farming with Chia 1.3.1 GUI.
Total reported use of system memory:
- before starting chia: 1.9GB
- after 5 min. running: 3.6GB
- after 24h: 10.2GB

Configuration:
HP Proliant360p Dual Xeon E5-2670
RAM 32GB
Ubuntu 20.04.4 LTS 64-bit

**Comment by Jared-woodruff** [comment]
After testing I can confirm the memory leak seems to be associated with the Electronium component rendering the wallet chart widget. 
If you open the client but don't click the wallet page, leaving it on the default page the leak does not occur.

**Comment by Jared-woodruff** [comment]
Issue is no longer present in version 1.3.4 of Chia.
Closing ticket.
