### ISSUE TITLE
upgraded to ver 1.3.1 and wallet not syncing up.

### ISSUE THREAD

**Issue by lokomoko37** [Chia-Network/chia-blockchain#10853]
### What happened?

after upgrade from ver 12.x which my wallet had x.xxx chia in it in ver 1.3.1 i am missing .xx chia what gives?
I have let it sync and all of that nonsense still nothing after hours of the update. 

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
i have no clue where to find
```

**Comment by Jared-woodruff** [comment]
Yep that happened to me.

**Comment by lokomoko37** [comment]
> Yep that happened to me.

...and did it sort itself out?

**Comment by Jared-woodruff** [comment]
Nah, still screwed up- I have setup the wallet only on another pc and it shows the correct balance but my farming server shows only the balance farmed since I installed 1.3.1 (0.04 XCH)

**Comment by lokomoko37** [comment]
Ok thanks, I will try that.

**Comment by lokomoko37** [comment]
Ok so... I got it to sync.
This is what I have done:
Shut down the Chia client,
Deleted the wallet/db folder under
 "user_name/.chia/mainnet/wallet/db"
So I just deleted the "db" folder.
Restarted the Chia client and let the wallet sync and it's all good now shows all of my precious little chias.
Hope this helps.
