### ISSUE TITLE
[Bug] 1.3x轻钱包整合后得版本，关于钱包得部分超级不正常，非常难用

### ISSUE THREAD

**Issue by zhangyongchang88** [Chia-Network/chia-blockchain#10866]
### What happened?

我得农业地址每天都再遭受沙尘暴攻击，没有升级1.3x得时候虽然有沙尘暴，但并不影响我得钱包使用。现在更新过后，钱包总是不同步，并且新版和旧版本有时候显示得xch数量都不一致。但他们都是完全同步得状态，我不得不再另一台电脑上又安装了一个1.2x得版本来使用发送接收硬币。

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by zhangyongchang88** [comment]
![1648130707(1)](https://user-images.githubusercontent.com/70252155/159933758-9b388163-df98-4c4d-83cc-77dd55b8fa4d.jpg)
上一张图1.31得版本号漏掉了。没有截图抓上，看这一张

**Comment by ljboy1979** [comment]
Plz use English to describe your problem

**Comment by jcheng0509-Chia** [comment]
We recommend you use a local node if you have a large history of transactions, you may also try out our newest dev builds.

**Comment by lidangqi** [comment]
#10646

**Comment by zhangyongchang88** [comment]
看来chia是不打算解决这个问题了。

**Comment by zhangyongchang88** [comment]
> 

再1.3x下如何使用1.2x技术方式的钱包？我的硬盘很大，我不怕占用空间。
另外他们把轻钱包和全节点整合在一起我不认为这是对的

**Comment by emlowe** [comment]
Closing issue, please reopen if you have problems with newer versions
