### ISSUE TITLE
[Bug] transactions gets stuck in "pending" and are not retried

### ISSUE THREAD

**Issue by felixbrucker** [Chia-Network/chia-blockchain#10873]
### Prerequisites
- 1.3.x wallet (1.3.0 or 1.3.1)
- Mempool is full

### How to reproduce
- Send a transaction, preferrably a multi out which wont be included due to the full mempool straight away
  - Might need to repeat the step above a few times to get a stuck transaction

### What happens
When a transaction is stuck, it will show its state as "Pending" via `chia wallet get_transaction`. The tx will never be included in the mempool and thus never confirm.

### Current workaround
Restarting the wallet service (`chia start -r wallet`) sometimes results in the tx transitioning to "In mempool" state and confirm within a minute. In the past few weeks the amount of wallet service restarts required to get a stuck transaction "unstuck" this way was 1-7.

### Version

1.3.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by joeharrison714** [comment]
Here is another instance of this happening in which restarting chia solved the problem https://www.reddit.com/r/chia/comments/tnp1v4/24_hours_pending_transaction_dust_storm/

**Comment by hbroer** [comment]
I have a similar problem. Accepted an offer and forgot to add a fee. After 12h pending I canceled it. 2 days later I have still peding balance of a token (-1CH21) and XCH (+0.25). The offer is listed as "canceled".

**Comment by hbroer** [comment]
Annoying. Why does nobody write "delete unconfirmed transactions" (which is hidden in that 3dots menu). And why is there no info in the UI what to do and what problems it can cause If someone deletes the unconfirmed transactions? It makes no sense that it stays unconfirmed for days. And why is there no standard fee. Or better like in my Ethereum Wallet where I can choose from three or so options? Not even a current USD price is shown. This software is very alpha and absolute not ready for market.

**Comment by aqk** [comment]
Fix here: https://github.com/Chia-Network/chia-blockchain/pull/11167
