### ISSUE TITLE
[Bug] cancel_offer function from chia/cmds/wallet_funcs.py fails

### ISSUE THREAD

**Issue by Jsewill** [Chia-Network/chia-blockchain#10882]
### What happened?

While running `chia wallet cancel_offer -id <id_string> -f <fingerprint> -m <fee>`, the cancel_offer function from chia/cmds/wallet_funcs.py fails while attempting to print the offer details (trade record), printing the following message: `Exception from 'wallet' non-hexadecimal number found in fromhex() arg at position 0`.

Commenting out line 434, `await print_trade_record(trade_record, wallet_client, summaries=True)` is sufficient to make the aforementioned function work. Sorry that I don't have time to track it down any further.

### Version

1.3.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
N/A
```

**Comment by paninaro** [comment]
@Jsewill is this still reproducible for you? If so, it would be helpful to have the full stack trace. Thanks for reporting the issue!

**Comment by Jsewill** [comment]
@paninaro Yes, it is still an issue. I also experience what seems to be a similar issue when listing offers via `chia wallet get_offers -s`, even when I specify an offer id. Same message:

`Exception from 'wallet' non-hexadecimal number found in fromhex() arg at position 0`

There's no relevant info in the chia logs. Is there another way I could capture the stack trace for that exception?

**Comment by paninaro** [comment]
@Jsewill can you share the command line you're using? I can repro the issue if enter a non-hex digit as the first character of the offer ID.

e.g.
`chia wallet cancel_offer -id zb9ed0d971a9a709466555e70dfcdbbde95ccf673db1abbf4632bd90107380db`

Whereas these both work:
`chia wallet cancel_offer -id 0xeb9ed0d971a9a709466555e70dfcdbbde95ccf673db1abbf4632bd90107380db`
`chia wallet cancel_offer -id eb9ed0d971a9a709466555e70dfcdbbde95ccf673db1abbf4632bd90107380db`

Since the exception is originating in the wallet service, you can probably find the stack trace in `~/.chia/mainnet/log/debug.log`. But it seems like maybe the offer ID has a bad character in it in the first character position.

**Comment by Jsewill** [comment]
As I said before, in a different way, it seems to occur with _every_ valid offer, and when I comment out the print function, everything else works. That alone should tell you that I passing a proper hexadecimal ID, unless I'm missing something.

As I said before, there is no trace of an error in the chia logs, pardon the pun.

Here are example commands which generate this message:

`chia wallet cancel_offer -id d1e9935622e2fd8a4302ead8346673d5a154c8584527a2aa3219d5f3e46f57eb`

`chia wallet get_offers -s` and `chia wallet get_offers -s -id d1e9935622e2fd8a4302ead8346673d5a154c8584527a2aa3219d5f3e46f57eb`

Also, I've just noticed that it _appears_ that get_offers only complains when there was a fee specified when the offer was created. However, I have yet to fully confirm this.

**Comment by Jsewill** [comment]
Here's the **_different_** error message and stack trace from when I attempted to cancel that particular offer I mentioned before:

`Exception from 'wallet'`

`Error while handling message: Traceback (most recent call last):
  File "/redacted/chia-blockchain/chia/rpc/util.py", line 16, in inner
    res_object = await f(request_data)
  File "/redacted/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1012, in cancel_offer
    async with self.service.wallet_state_manager.lock:
  File "/usr/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
concurrent.futures._base.CancelledError`

**Comment by paninaro** [comment]
Right, one side will always be a non-XCH asset, but the offered asset is what I was curious about. Thanks for the update.
