### ISSUE TITLE
[Bug] GUI Crashes when trying to manually disconnect a stale peer

### ISSUE THREAD

**Issue by alnuweiri** [Chia-Network/chia-blockchain#10890]
### What happened?

Every day I get some stale peers. Chia doesn't disconnect them automatically, even though their height is not at the peak height, and they don't send or receive anything for a long time. When I try to disconnect them manually through GUI they stay in my peer list and after a few seconds, the GUI crashes. I can't even disconnect them through CLI. The only solution is to restart Chia. This is very annoying and chia still counts them as connected peers, so after a few days, I will have like 7~10 stale peers which might affect my syncing performance.

I had the same issue with stale peers with Chia 1.2.11 but the GUI never crashed.

To reproduce the issue, run Chia GUI for some time till you have 40~50 peers, then try to disconnect some peers who are not synced manually. 

Edit: I noticed that this case mostly happened when disconnecting a few peers from the GUI in a fast way (few seconds only between each disconnect)

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
This no longer happens in 1.6.2
