### ISSUE TITLE
Do not display wallet balance

### ISSUE THREAD

**Issue by arz24ir** [Chia-Network/chia-blockchain#10901]
Hello Please help me 🙏😔😭
 I transferred 100 Chia currencies (#xch) to Chia software, but 57 of them are available What should I do to have it displayed in my bag?

**Comment by arz24ir** [comment]
no

در تاریخ جمعه ۱ آوریل ۲۰۲۲،‏ ۱:۲۶ William Allen ***@***.***>
نوشت:

**Comment by emlowe** [comment]
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by emlowe** [comment]
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5
