### ISSUE TITLE
[Bug] Transaction showed as confirmed locally but did not exist on blockchain

### ISSUE THREAD

**Issue by joeharrison714** [Chia-Network/chia-blockchain#10914]
### What happened?

I sent a CAT transaction which showed as confirmed when checking the status locally, but the recipient never got it. When I resynced my wallet, the transaction was gone.

tx id: 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce

Here was the output of get_transaction BEFORE resyncing:
```
{'additions': [{'amount': 997943693168,
                'parent_coin_info': '0x603336f0c86a2d892a560428071350321b848d1ae1ce224ea99ed2cc34c88567',
                'puzzle_hash': '0x165ff0f6a52c5d43af0a6ec93cd14e4b3aa6c423daa8a03347f73ce63314e44b'}],
 'amount': 0,
 'confirmed': True,
 'confirmed_at_height': 1749568,
 'created_at_time': 1648319440,
 'fee_amount': 50000,
 'memos': [],
 'name': '0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce',
 'removals': [{'amount': 997943743168,
               'parent_coin_info': '0xc4057235141e702b4f1c7dc64c8965ecf3adc85f1a5fda0992aa7d54c236efd7',
               'puzzle_hash': '0x454ab5e957115740290df3653ef62ea91841ac24a3e5bd8123b4131290d046ed'}],
 'sent': 0,
 'sent_to': [],
 'spend_bundle': None,
 'to_puzzle_hash': '0x860d575bc2a33bcde1967c0b5df00798bf2b35bb53b8d94412833cf6de355272',
 'trade_id': None,
 'type': 1,
 'wallet_id': 1}
```

Take not of confirmed and confirmed at height values.

After I deleted and resynced the wallet database, I once again tried get_transaction but now I get:

```
Exception from 'wallet' {'error': 'Transaction 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce not found', 'success': False}
```

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-03-27T16:08:32.883 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce not found

2022-03-27T16:13:10.508 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\wallet_rpc_api.py", line 612, in get_wallet_balance
KeyError: 3

2022-03-27T16:18:03.402 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\util.py", line 16, in inner
  File "chia\rpc\wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce not found
```

**Comment by 0X1231** [comment]
+1

**Comment by MojoWhaleCom** [comment]
Yup, typical

**Comment by joeharrison714** [comment]
Here is another example. The recipient of a cat I sent in the amount of 35.166 never got it. The transaction shows as confirmed in the wallet that sent. I synced another machine with the same wallet to compare, and the transaction is not there
![image](https://user-images.githubusercontent.com/7193254/160430536-6a1cc1e4-9426-4a74-b209-0c76a3f43194.png)

**Comment by jorgetu** [comment]
I'm having the same problem
Today I installed 1.3.2 version, and resync my wallet with the option onnect_to_unknown_peers: false  and the problem still persists.

In my case  the transaction is creating a new plot NFT 
2022-04-02T11:23:13.487 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0x462df0b43dfc615821822cdaca588c3d103cde5da50e015883d4e24f4e577d4f not found

**Comment by joeharrison714** [comment]
> If you try to resync your wallet with a local trusted node only (`connect_to_unknown_peers: false` in config.yaml), do you see any different results?

I will try this next time I see it. Just in case this matters, both times I saw it I was using a local full node

**Comment by navyfeng** [comment]
> ### What happened?
> I sent a CAT transaction which showed as confirmed when checking the status locally, but the recipient never got it. When I resynced my wallet, the transaction was gone.
> 
> tx id: 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce
> 
> Here was the output of get_transaction BEFORE resyncing:
> 
> ```
> {'additions': [{'amount': 997943693168,
>                 'parent_coin_info': '0x603336f0c86a2d892a560428071350321b848d1ae1ce224ea99ed2cc34c88567',
>                 'puzzle_hash': '0x165ff0f6a52c5d43af0a6ec93cd14e4b3aa6c423daa8a03347f73ce63314e44b'}],
>  'amount': 0,
>  'confirmed': True,
>  'confirmed_at_height': 1749568,
>  'created_at_time': 1648319440,
>  'fee_amount': 50000,
>  'memos': [],
>  'name': '0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce',
>  'removals': [{'amount': 997943743168,
>                'parent_coin_info': '0xc4057235141e702b4f1c7dc64c8965ecf3adc85f1a5fda0992aa7d54c236efd7',
>                'puzzle_hash': '0x454ab5e957115740290df3653ef62ea91841ac24a3e5bd8123b4131290d046ed'}],
>  'sent': 0,
>  'sent_to': [],
>  'spend_bundle': None,
>  'to_puzzle_hash': '0x860d575bc2a33bcde1967c0b5df00798bf2b35bb53b8d94412833cf6de355272',
>  'trade_id': None,
>  'type': 1,
>  'wallet_id': 1}
> ```
> 
> Take not of confirmed and confirmed at height values.
> 
> After I deleted and resynced the wallet database, I once again tried get_transaction but now I get:
> 
> ```
> Exception from 'wallet' {'error': 'Transaction 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce not found', 'success': False}
> ```
> 
> ### Version
> 1.3.1
> 
> ### What platform are you using?
> Windows
> 
> ### What ui mode are you using?
> CLI
> 
> ### Relevant log output
> ```shell
> 2022-03-27T16:08:32.883 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
>   File "chia\rpc\util.py", line 16, in inner
>   File "chia\rpc\wallet_rpc_api.py", line 667, in get_transaction
> ValueError: Transaction 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce not found
> 
> 2022-03-27T16:13:10.508 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
>   File "chia\rpc\util.py", line 16, in inner
>   File "chia\rpc\wallet_rpc_api.py", line 612, in get_wallet_balance
> KeyError: 3
> 
> 2022-03-27T16:18:03.402 wallet chia.rpc.util              : WARNING  Error while handling message: Traceback (most recent call last):
>   File "chia\rpc\util.py", line 16, in inner
>   File "chia\rpc\wallet_rpc_api.py", line 667, in get_transaction
> ValueError: Transaction 0x93c9eb22283597e4776c4008823de24ba8e4d6c2b2da5b0407a992403ba41dce not found
> ```

Same problem in version 1.2.11

Transaction 9410f0fe2a7ed7adbd0106091eef233fb0dea6734d9ecdb0a1c392ba7a9497f4 confirmed on local wallet, but failed on blockchain.

![image](https://user-images.githubusercontent.com/1535983/167098650-7ffe9f6e-5919-4e37-833c-a34857d5a1b3.png)
![image](https://user-images.githubusercontent.com/1535983/167098793-1b74410a-d508-4d8e-ba30-a8f09c209c62.png)

**Comment by uranik777** [comment]
Same problem in version 1.5.0 - transaction confirmed in wallet but hash missing in bockchain explorer
```
>chia wallet get_transaction -tx 0x2bbcabef68f4ceaf286282e9d0c96b34d8c369e5f2b97a399b244da6c214fdc7
Transaction 2bbcabef68f4ceaf286282e9d0c96b34d8c369e5f2b97a399b244da6c214fdc7
Status: Confirmed
Amount sent: 3.9 XCH
To address: xch1s49y026x9yuwhmdy7xexsw8m3m3urejp3f70n69ysxuf43g090gsf6cclf
Created at: 2022-08-18 10:06:14
```
This transaction was found on xchscan.com with a different transaction hash:
>https://xchscan.com/ru/txns/0x7a287c3b119d12df7604d0ba16acbf37fe54f1544ba25ee83a6b7b8037e5df66
ok
but wallet transaction hash 0x2bbcabef68f4ceaf286282e9d0c96b34d8c369e5f2b97a399b244da6c214fdc7 not found :(
>https://xchscan.com/ru/txns/0x2bbcabef68f4ceaf286282e9d0c96b34d8c369e5f2b97a399b244da6c214fdc7
error 404

**Comment by uranik777** [comment]
With the -v flag, extended information about the transaction is shown, it would be nice to add a parameter for the hash of the transaction in the blockchain:
```
 'confirmed': True,
 'confirmed_at_height': 2416157,
 'confirmed_transaction_hash': 0x7a287c3b119d12df7604d0ba16acbf37fe54f1544ba25ee83a6b7b8037e5df66,
```
