### ISSUE TITLE
[Bug] Wallet shows only transactions made on old wallet address

### ISSUE THREAD

**Issue by iSky1ine** [Chia-Network/chia-blockchain#10910]
### What happened?

At March 9 i updated Chia to version 1.3.0, at that moment i had about 20 XCH, i sent them to myself (new wallet address generated by 1.3.0), when 1.3.1 were released i installed it and everything were fine till today. First from transactions history (and balance) disappeared block rewards i got from March 9, i decided to resync wallet hoping it will help, deleted wallet db and synced from scratch and now all my transactions and coins from March 9 is disappeared. Last transaction showed in GUI is moving my 20 XCH from old address to new one. I still can see coins on my new address with chia explorer, but not in GUI. It looks like my wallet address that i used from March 9 is not connected to my mnemonic. I tried to resync wallet few time, fully reinstall Chia, installed latest dev version and resynced again, nothing helps.

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by sergiosurvival** [comment]
Yo realice un retiro esta mañana y se quedo pendiente version 1.3.1

**Comment by iSky1ine** [comment]
Problem fixed, i created to much addresses so my address were #847 and didn't showed in gui, because it's show only first 100 by default, so i changed it to 1000 in config and everything appeared in gui, moved coins to first address just to prevent future problems
