### ISSUE TITLE
[Bug] 钱包一直不到帐

### ISSUE THREAD

**Issue by LYY-LYY** [Chia-Network/chia-blockchain#10911]
### What happened?

自耕种爆块后，从农村合作社申领奖励1.75xch一星期之后钱包都没有到账，但是钱包下方有1.75的交易记录

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by 0X1231** [comment]
+1

**Comment by LYY-LYY** [comment]
求官方解答，谢谢！

**Comment by wallentx** [comment]
Based on translation, it seems like this is a duplicate of https://github.com/Chia-Network/chia-blockchain/issues/10640
