### ISSUE TITLE
how to miner on harvester

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-blockchain#1093]
i create the plot with farm_id and pool_id, 
and it check polts in harvester 

it show 
```
 WARNING  Plot /home/cery/miner/miner10/plot-k32-2021-02-20-07-41-e0af2077ef916164045da6744d80cfb77e72943e5a045505f2f49d8ce9af71b2.plot has a farmer public key that is not in the farmer's pk list.
```
what does that mean ?

**Comment by mariano54** [comment]
It means you need to have the keys that were used for plotting, in the farmer machine. Checkout links on the wiki, or ask help in the keybase beginner channel

**Comment by ldjdsc** [comment]
> i create the plot with farm_id and pool_id,
> and it check polts in harvester
> 
> it show
> 
> ```
>  WARNING  Plot /home/cery/miner/miner10/plot-k32-2021-02-20-07-41-e0af2077ef916164045da6744d80cfb77e72943e5a045505f2f49d8ce9af71b2.plot has a farmer public key that is not in the farmer's pk list.
> ```
> 
> what does that mean ?


怎么解决的这个问题？
