### ISSUE TITLE
1.3.1版本更新后，丢失了chia币[Bug] 

### ISSUE THREAD

**Issue by cxm9874123** [Chia-Network/chia-blockchain#10973]
### What happened?

- 更新完1.3.1版本后，正常挖chia一周多没什么问题，前几天关机4小时后，再开机更新的时候，发现自己钱包里的chia币丢失了一部分，仔细检查了钱包的记录后，发现是对之前一段时间的挖掘工作不识别了
- 丢失的挖掘工作时间如下，约有近10天的挖掘工作不被认可，于是该日期所获得的钱包里的币变成丢失了
![_5V3H0Y%B`XJTPW0~(QVQKG](https://user-images.githubusercontent.com/63990278/161094900-b0ea2a3b-21d9-430a-86c6-47071451e486.png)

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by cxm9874123** [comment]
2022.3.12-2022.3.14
2022.3.14-2022.3.28
这期间的挖掘工作时间遗失了，请问要如何解决和追回丢失的chia币

**Comment by zhangyongchang88** [comment]
与我前几天反应的问题一致，#10866   
1.2x显示的币和1.3x显示的不一致

**Comment by LeslieChiang** [comment]
> Are you able to provide more information, such as logs, and how you were able to know that there were missing transactions? If you are pooling, does your pool show that you were given a payout for those missing transactions?

I am also facing the same problem, the transaction is confirmed and shown on xchscan but is just not appearing in the wallet. The DB v2 is so ever delicate and I won't even call it a version release, more appropriate for alpha. Yea, various resolutions floating around, either you delete the whole thing and reinstall or delete the db or change certain config.yaml parameters but the issue surface again after doing some transactions (like sending xch to another wallet)...
