### ISSUE TITLE
[Bug]  transaction ledger only shows outgoing transactions when sending transaction to self

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10981]
### What happened?

I was creating change in my own wallet by sending myself a transaction with USDS. After the settlement of the transaction the ledger only shows the outgoing transaction and doesn't show the incoming transaction.

expected behavior: transaction ledger shows incoming transaction also.
![Screen Shot 2022-03-31 at 3 57 21 PM](https://user-images.githubusercontent.com/93196638/161148161-87f1a558-f4e2-40f0-aa37-d0107cf42ad4.png)

### Version

1.3.1 dev 75

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by Quexington** [comment]
This is actually expected behavior.  You basically made two change coins for yourself and our display does not display change.  I think if this was a more prevalent issue this issue would not have gone unanswered for a year+ so I'm going to close it.
