### ISSUE TITLE
Alignment on Release Notes RC1 and Beta 27

### ISSUE THREAD

**Issue by dvd101x** [Chia-Network/chia-blockchain#1098]
This is a minor issue for the website.

On the webpage for [Release Notes](https://www.chia.net/releases/), there is an extra line break on the date column for RC1 and the date column for Beta 27 is aligned differently than the rest.

**Comment by hoffmang9** [comment]
This seems to have just resolved itself. It could have been an error on GitHub's side as that page is dynamically built from their API.

**Comment by dvd101x** [comment]
I did some digging, and it's only on Safari and Safari on IOs.
Chrome and Firefox are ok.

<img width="1160" alt="Captura de Pantalla 2021-03-01 a la(s) 10 08 44 p  m" src="https://user-images.githubusercontent.com/16261897/109595882-e34f0d00-7ada-11eb-915f-f1688358ddd1.png">

**Comment by hoffmang9** [comment]
Great....

**Comment by dvd101x** [comment]
It seems to be related to the width of the element “February 18, 2021”, I tried switching it to 19 or 17 and it didn’t overflow and the layout was consistent.

**Comment by hoffmang9** [comment]
I'm going to close this as wontfix but thanks for pointing it out.
