### ISSUE TITLE
[Bug] error message not user friendly 

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#10980]
### What happened?

when spendable balance is not enough (0 in this case), the error message isn't very user friendly. it currently says:
"can't send more than 0 in a single transaction"

![Screen Shot 2022-03-31 at 3 45 23 PM](https://user-images.githubusercontent.com/93196638/161147052-b5521e4d-daad-4932-9e8b-579353edce2d.png)

### Version

1.3.1 dev75

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Moved to Jira backlog tracking
