### ISSUE TITLE
[Bug]  sending 100XCH ended up being thousands of 0.000000000002

### ISSUE THREAD

**Issue by cryptosven76** [Chia-Network/chia-blockchain#10985]
### What happened?

i tried to send 100 XCH to a different address and what happened was i see 10's of thousands of 0.000000000002 XCH transfers. it seems as if the 100 XCH never ended up on the receiving node. 

### Version

1.3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by Ealrann** [comment]
Hello. The 0.000000000002 XCH transfers are related to the Dust Storm (somebody try to flood the Chia Blockchain, unsuccessfully).
If you can, I advise you to find your transaction ID and input it in xchscan.com, it's the easiest way to check the status of a transaction.

**Comment by jiyifanzi** [comment]
> Hello. The 0.000000000002 XCH transfers are related to the Dust Storm (somebody try to flood the Chia Blockchain, unsuccessfully). If you can, I advise you to find your transaction ID and input it in xchscan.com, it's the easiest way to check the status of a transaction.

how to fix this attack ? my wallet almost 0.000000000002 XCH

**Comment by Ealrann** [comment]
There is nothing to fix about the 0.000000000002 XCH. Somebody is simply sending money to lots of address. 

About your 100XCH, did you check the transaction ID? You can also check the target address (the one you sent the 100XCH to) on xchscan.com.

**Comment by wallentx** [comment]
Are there any more details that you can provide? Is this still an issue, or did this transaction end up showing up? `chia wallet get_transactions --no-paginate` should show your transaction history there, but note that this might take a while to complete.

**Comment by cryptosven76** [comment]
chia wallet   get_transactions  --no-paginate returns only a few 10's of lines of transactions, but not more than 2 days bag , the transactions in question have been made more than a week ago. and to answer your question, they never actually hit the target wallet, which is very disappointing to say the least as this was quite some amount of chia
