### ISSUE TITLE
[Bug] a node cannot be deleted

### ISSUE THREAD

**Issue by maogo** [Chia-Network/chia-blockchain#11009]
### What happened?

like:
8444/8444  7c1837bb... Mar 31 14:12:07      0.0|0.0    
-Height: No Info    -Hash: No Info

run chia show -r 7c1837bb  cannot be deleted

### Version

1.3.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by alnuweiri** [comment]
I have the same problem, but I believe that the chia team doesn't see this problem as a priority for now.

**Comment by maogo** [comment]
> I have the same problem, but I believe that the chia team doesn't see this problem as a priority for now.

I assume its a bad node and has been in my peer list for a few day. So ,not sure how it will affect the normal node.

**Comment by emlowe** [comment]
Closing as Duplicate of #9172
