### ISSUE TITLE
1.2.11升级到1.3.2

### ISSUE THREAD

**Issue by hyperx1231** [Chia-Network/chia-blockchain#11012]
### What happened?

1：1.2.11升级到1.3.2如何升级DB到V2？ 在demon下 输入CHIA DB UPGRADE无效

2：为什么升级后原来的NFT账户看不到了，自助添加登录了不同的密匙不可做任何更改？

### Version

1.32

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by elarkasi** [comment]
重新下载最新版本，重新同步数据试试，现在的数据量大概要5-6天左右才能全部同步完。

**Comment by emlowe** [comment]
Use version 1.3.5 and resync your wallet - feel free to reopen if you have problems with 1.3.5
