### ISSUE TITLE
[Bug] DB Upgrade failure for space constraints throws uncaught error and leaves Chia in down state

### ISSUE THREAD

**Issue by beachseeker** [Chia-Network/chia-blockchain#11026]
### What happened?

While performing chia db upgrade, I ran out of space at around 38GB.  The upgrade process failed with an uncaught error, and left my Chia farmer in a down state.  
1. The stated FAQ and CLI information on required space is not sufficient to understand the space requirements. (another issue already recorded)
2. The process should do it's own calculation on the the space requirements as a validation and warn the user.  
3. After the upgrade failed, my farmer stopped syncing.  I assume, even with the failure, it tried to continue with the process, using a DB in a bad state, and a system drive completely full.

Suggested action: Update the documentation as a priority, and a incorporate validation and error handling as a fix as soon as possible.   The biggest problem here is that there's no way for a user to understand, given the doc in it's current state, how much space is required, and secondary are the lack of validation at the point where that knowledge is best known (in the command processing), and the evident lack of proper error handling.  Thanks!

### Version

1.3.2

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
Machine is currently not booting, so I am not able to provide.
```

**Comment by wallentx** [comment]
Thank you for reporting. I'm linking this issue to https://github.com/Chia-Network/chia-blockchain/issues/11025 and closing this one.

**Comment by beachseeker** [comment]
While I understand the action taken seems the easiest, and was the most important FIRST step, I do not agree that updating documentation is the complete solution.  Do you really think not having validation or error handling on a production function is professional?
