### ISSUE TITLE
How to switch wallet read mode for 1.2x？[Bug] 

### ISSUE THREAD

**Issue by zhangyongchang88** [Chia-Network/chia-blockchain#11037]
### What happened?

The light wallet integrated with the 1.3.x version cannot be used normally. My wallet address has been attacked by 1-2mojo again. The new version cannot be synchronized normally. The old version 1.2x can be used normally. I hope to switch back.

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MojoWhaleCom** [comment]
I agree!

**Comment by emlowe** [comment]
Please make sure that you are using the wallet with a fully synced local node. We are testing with wallets that have many transactions (10s and 100s of thousands) - and when using a local node we find that those all sync correctly. It is true that remotely syncing such wallets is more problematic.

please provide as many details as you can, particularly any information about the h/w in question and what precise problem you are having.

**Comment by emlowe** [comment]
I'll note for completeness the only way to revert to the old wallet is to run to chia 1.2.11

**Comment by wallentx** [comment]
This duplicates https://github.com/Chia-Network/chia-blockchain/issues/11035
Closing this issue.
