### ISSUE TITLE
1.32后原来的NFT不能用了[Bug] 

### ISSUE THREAD

**Issue by hyperx1231** [Chia-Network/chia-blockchain#11031]
### What happened?

提示 此农田NFT绑定了其它密钥。你仍然可以用此农田NFT开垦农田，但是你无法进行任何更改

### Version

1.32

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you sending your rewards to a cold wallet? Are you able to still farm?
