### ISSUE TITLE
Farming rewards dialog incorrectly claims there is no private key for address

### ISSUE THREAD

**Issue by zhangyongchang88** [Chia-Network/chia-blockchain#11036]
### What happened?

![image](https://user-images.githubusercontent.com/70252155/161584812-ffaae686-c8c5-4218-9914-b04a9473db95.png)

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you sending your rewards to a cold wallet? This message is expected if so.

**Comment by alnuweiri** [comment]
I have the same problem and I am sending my reward to the hot wallet!

**Comment by emlowe** [comment]
This is a bug with observer addresses - this dialog is not checking the new observer addresses
