### ISSUE TITLE
1.3x钱包一直未同步 [Bug] 

### ISSUE THREAD

**Issue by zhangyongchang88** [Chia-Network/chia-blockchain#11035]
### What happened?
![image](https://user-images.githubusercontent.com/70252155/161584507-bdd39fd4-6c60-4e59-a6bc-ed059bd2d18e.png)

![image](https://user-images.githubusercontent.com/70252155/161582693-a066bd59-535c-474a-9d16-b1de36a38658.png)
我的钱包地址一直再遭受1-2mojo的攻击，上万条记录导致我升级1.3x后钱包无法同步出数据，如何切换回旧的钱包同步模式？

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to sync if you are running in "Farmer" mode? If your wallet has lots of "dust" transactions, it might be useful to sync to a local full_node only, by setting `connect_to_unknown_peers: false` in your config.yaml.
