### ISSUE TITLE
Pool points not showing up

### ISSUE THREAD

**Issue by Yarnila** [Chia-Network/chia-blockchain#11041]
Since the update to1. 3.3 I no longer see points found since start or last 24hrs and points successful and yes I see proves being found.

**Comment by wallentx** [comment]
What does it show as your `Current state` and `Current difficulty` from the output of `chia plotnft show`? Also, please verify that the rest of the information from that output looks to be accurate.

**Comment by apinc14** [comment]
It was corrected, I must have accidentally change the address during install. Not sure how I managed that, thanks for the replies

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by emlowe** [comment]
closing based on last comment
