### ISSUE TITLE
[Bug] Exception from 'chia wallet make_offer'

### ISSUE THREAD

**Issue by Jsewill** [Chia-Network/chia-blockchain#11040]
### What happened?

When attempting to create a CAT for XCH offer, like so:

```echo y | chia wallet make_offer -f <fingerprint> -o <ID>:1 -r <ID>:0.3 -p <offer_file_path>```

I receive output something like the following:

```
OFFERING:
  - 1 CAT Name Here (1000 mojos)
REQUESTING:
  - 0.3 XCH (300000000000 mojos)
Confirm (y/n): Exception from 'wallet' 
```

See the "Relevant log output" field on this issue for a relevant excerpt of the log.

I assume this is because the wallet went out of sync just before I attempted to create my offer(s), but I can't be sure, as my wallet is in and out of sync--apparently due to the number of CAT wallets I have. I'm excited for the wallet optimizations, to be sure.

### Version

1.3.3

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
WARNING  Error while handling message: Traceback (most recent call last):
  File "chia-blockchain/chia/rpc/util.py", line 16, in inner
    res_object = await f(request_data)
  File "chia-blockchain/chia/rpc/wallet_rpc_api.py", line 901, in create_offer_for_ids
    async with self.service.wallet_state_manager.lock:
  File "/usr/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
concurrent.futures._base.CancelledError
```

**Comment by esaung** [comment]
how many CAT wallets do you have?

**Comment by Jsewill** [comment]
Upwards of 35.

**Comment by emlowe** [comment]
Closing old issue
