### ISSUE TITLE
[BUG] Plot creation out of memory

### ISSUE THREAD

**Issue by Jeremy-Kemp** [Chia-Network/chia-blockchain#1104]
When creating plots, there appears to be a memory leak causing plot creation to fail.

Plot creation is running out of memory. This happens on a system with 16GB RAM when creating a `-k 32` plot.

**To Reproduce**
`chia plots create -k 32 -b 2000 -t <path_to_local_ssd> -d <path_to_plot_dir_mounted_via_sshfs>`

**The Error**
```
Compressing tables 2 and 3
...
	Bucket 50 QS. Ram: 1.923GiB, u_sort min: 3.250GiB, qs min: 0.815GiB. force_qs: 0
	Bucket 25 QS. Ram: 1.923GiB, u_sort min: 3.250GiB, qs min: 0.895GiB. force_qs: 1
	Bucket 51 QS. Ram: 1.923GiB, u_sort min: 0.203GiB, qs min: 0.083GiB. force_qs: 1
	First computation pass time: 1699.272 seconds. CPU (90.330%) Mon Mar  1 04:03:43 2021
Caught plotting error: Not enough memory for sort in memory. Need to sort 2.041358GiB
```

**Desktop (please complete the following information):**

- Chia 1.0rc4
- Xubuntu 20.04
- Ryzen 7 3700X
- 16GB RAM

**Comment by hoffmang9** [comment]
By handing the process only 2000 MiB you didn't allow it enough buffer to complete.
