### ISSUE TITLE
[Bug] Harvester cannot reconnect

### ISSUE THREAD

**Issue by JustAlias** [Chia-Network/chia-blockchain#11056]
### What happened?

My harvester and the farmer are running on different machines. When my harvester was accidentally disconnected, it could not be reconnected. The harvester has been trying to reconnect, is it because the farmer did not release the old connection?
I tried to restart the normal harvester using the "chia start harvester-r" and the situation was the same.
restart the famer, can solve the problem!

This didn't happen on 1.2.x

The harvester is on Linux
The farmer  is on Windows

### Version

1.3.1   1.3.2   1.3.3  

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Fixed in 1.4.0
