### ISSUE TITLE
pool wallet chia.rpc.rpc_server [Bug] 

### ISSUE THREAD

**Issue by hyperx1231** [Chia-Network/chia-blockchain#11078]
### What happened?

加入矿池后出现一下错误
022-04-07T18:41:28.616 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0xc208447ad4f582d334b80f3077f9f2b8f6e29650304282a82bb7b8f4e8e2b22f not found

### Version

1.33

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
022-04-07T18:41:28.616 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 215, in safe_handle
  File "chia/rpc/rpc_server.py", line 206, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 667, in get_transaction
ValueError: Transaction 0xc208447ad4f582d334b80f3077f9f2b8f6e29650304282a82bb7b8f4e8e2b22f not found
```

**Comment by wallentx** [comment]
Translation note: "An error occurred after joining the mining pool"

**Comment by emlowe** [comment]
This seems to be similar (perhaps the same) to #11125

**Comment by HVNC1** [comment]
то же.версия 1.5.1
![image](https://user-images.githubusercontent.com/95166695/189451345-aafef505-0b18-43ca-8736-f19af40740ae.png)
