### ISSUE TITLE
[Bug] Offer shows XCH instead of TXCH when connected to a testnet

### ISSUE THREAD

**Issue by cmmarslender** [Chia-Network/chia-blockchain#11086]
### What happened?

While connected to testnet, I was going to accept some `BadJokeCoin` for `txch`, but the offer summary showed `XCH` instead. Should probably show TXCH to be clear we're on a testnet when reviewing the offer / avoid panic.

![Screen Shot 2022-04-07 at 3 53 24 PM](https://user-images.githubusercontent.com/1915905/162311695-b80932bf-91d7-4cf6-8442-57be76466fe3.png)

### Version

1.3.2.dev122

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by Starttoaster** [comment]
Can confirm I also saw this in Ubuntu 20.04, same build of chia, in CLI.

**Comment by paninaro** [comment]
GUI has been fixed. Created a separate issue for the remaining CLI issue #13393
