### ISSUE TITLE
Can't install timelord on Centos

### ISSUE THREAD

**Issue by Z2020Z** [Chia-Network/chia-blockchain#111]
Hi, 

I'm trying to install timelord on Centos. But it seems like it's not supported yet. Is that right? 

Also, may I ask what the hardware requirement is to run a timelord? Is it possible to run on a virtual machine for local simulation? Thanks a lot!

"sh install_timelord.sh" Error:
install_timelord.sh: line 4: type: apt-get: not found
make: Entering directory `../chia-blockchain/lib/chiavdf/fast_vdf'
g++ -std=c++1z -D VDF_MODE=0 -D ENABLE_ALL_INSTRUCTIONS=0 -no-pie -pthread -march=native -O3   -c -o vdf_server.o vdf_server.cpp
g++: error: unrecognized command line option \u2018-std=c++1z\u2019
g++: error: unrecognized command line option \u2018-no-pie\u2019
make: *** [vdf_server.o] Error 1
make: Leaving directory `.../chia-blockchain/lib/chiavdf/fast_vdf'

Best,
Zz

**Comment by hoffmang9** [comment]
Which version of CentOS are you using? You have to be in the `scl enable devtoolset-8 bash` mode for most version of CentOS. Also, did you create the symbolic link for cmake? You have to be in the same environment that will successfully build fullnode etc.

You can run a timelord in a local simulation inside a VM but it's CPU intensive so it may be slow/laggy.

**Comment by Z2020Z** [comment]
My version is CentOS Linux release 7.7.1908 (Core). Tried "scl enable devtoolset-8 bash". It worked. Thanks a lot!
