### ISSUE TITLE
请问错把费用当成奖励还有挽回的可能性吗?

### ISSUE THREAD

**Issue by LYY-LYY** [Chia-Network/chia-blockchain#11112]
### What happened?

我是从农村合作社提取奖励的时候，错把费用当成提取奖励，费用直接输入1.75 ，请问还有挽回的可能性吗？谢谢！
![162441301-f4adf03f-ecdd-46ae-b6c0-80b5e4269730](https://user-images.githubusercontent.com/48404760/162557279-ac2dd4f4-f5b4-40d8-a9dc-f107abf6f28d.png)

### Version

1.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
Currently, theres no way to recover the incorrect fee amount

**Comment by a6654196** [comment]
On March 24th, I also made a mistake. The fee is $1.75,Here’s my addressxch1n4tqjh3pju52e664s59qz2h509wjaucnv4j66c5tl098as7sxysq79ye75

**Comment by wallentx** [comment]
@a6654196 and @LYY-LYY do theses transactions show in your wallet transaction list? Please share a screenshot, or paste your transaction list showing this

**Comment by a6654196** [comment]
![cb3af1af3eb7faeb21c7bbe255e0b0d](https://user-images.githubusercontent.com/102576030/163525565-fb3e22b3-21ee-4a44-9728-bb2d77e11fb5.jpg)
![8d0343471a6b04e6a21b15ddf305c6e](https://user-images.githubusercontent.com/102576030/163525573-861d024c-7d0b-4d0f-b677-6135ad4cb60d.jpg)
Thank you

**Comment by LYY-LYY** [comment]
我的交易记录
![image](https://user-images.githubusercontent.com/48404760/163527494-defb9b5d-d99a-42e6-989d-0262dd0d59d9.png)

**Comment by LYY-LYY** [comment]
我的钱包交易记录有的
![image](https://user-images.githubusercontent.com/48404760/163527629-85155cf4-58bc-47ac-8f74-128d0be94ee2.png)

**Comment by a6654196** [comment]
@wallentx

**Comment by a6654196** [comment]
@wallentx hank you

**Comment by liuyuansharp** [comment]
@LYY-LYY 能把你的地址贴出来吗？

**Comment by emlowe** [comment]
@a6654196 Yes, your 1.75 as a fee is now gone to the farmer who farmed the block and cannot be restored. I'm sorry for this, but that XCH is not coming back

@LYY-LYY  I don't see the outgoing transaction in your list from when you claimed the rewards, so I don't know if the fee is present for you or not.

**Comment by a6654196** [comment]
@wallentx @emlowe  The pool does not need to be charged, why set the cost option, I believe there are more than a few people in this situation? XHC was transferred as an expense. I think it’s an abnormal transaction. The system should test the transaction back

**Comment by a6654196** [comment]
@wallentx @emlowe Application for cash withdrawal is free, why set the option I’m sure there are a lot of people in this situation? XHC was transferred as an expense. I don’t think that’s a good deal. The system should terminate the transaction

**Comment by a6654196** [comment]
@wallentx @emlowe Withdrawal requests are free, why set the option I’m sure there are a lot of people in this situation? XHC was transferred as an expense. I don’t think that’s a good deal. The system should terminate the transaction

**Comment by a6654196** [comment]
@emlowe @wallentx @The withdrawal request is free. Why? To set this option, I’m sure there are many people in this situation? XHC was transferred as an expense. I don’t think that’s a good deal. The system should terminate the transaction

**Comment by emlowe** [comment]
Due to dust storms there is often fee pressure on mainnet, so using a fee may be required to either get your transaction included in the first place or prioritized ahead of dust (so you don't need to wait hours to complete the claim)

That said, in other places of the UI, the UI will warn you about using a very high fee, but this dialog box does not. We will be making some UX improvements in followup releases.

**Comment by LYY-LYY** [comment]
@emlowe 1.75的奖励至今确实没有到账，而且费用我确定输入了1.75xch

**Comment by shaneo257** [comment]
yeh you wont get that 1.75, as it was used for the fee amount

**Comment by ihola777** [comment]
should translate the 费用 to 手续费 to avoid misunderstanding

**Comment by zhangyongchang88** [comment]
我认为费用应该自动计算，而不是让用户自己填写。一个合格的产品不应该让用户过多的考虑那些无用的东西，我转账bnb eth时从未考虑过小费的问题

**Comment by zhangyongchang88** [comment]
> 由于沙尘暴，主网经常有费用压力，因此可能需要使用费用来将您的交易放在首位或优先于尘埃（因此您无需等待数小时即可完成索赔）
> 
> 也就是说，在 UI 的其他地方，UI 会警告您使用非常高的费用，但此对话框不会。我们将在后续版本中进行一些 UX 改进。

Why not improve to automatic mode

**Comment by shaneo257** [comment]
fee suggestions will be coming in a future update
