### ISSUE TITLE
Unable to claim rewards for Self Pooling. 

### ISSUE THREAD

**Issue by Ratchanida** [Chia-Network/chia-blockchain#11121]
### What happened?

I received 1.75 xch for my self-pooling.  After updated to GUI v. 1.3.3, it seems to have an issue/bug.  When I clicked CLAIM REWARDS, it shows the next screen to confirm a receive wallet and put fee amount.  But my receiving address is blank out (You will receive 1.75 xch to_____), and It does not show my wallet address.   For the older version of GUI, it will automatically show my received address.  Please help. Thanks

![solo pool 1](https://user-images.githubusercontent.com/86420352/162635204-a83daf20-9871-4434-bdd5-4423c30cb96e.JPG)

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
This is a GUI display issue, however, the claim does go to your wallet address. Note there may be some other issues with claiming however, which we hope will be addressed in the next release.

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/682/commits/91a06a398d2a526f2f9fd32c0570b32330b2a2f7
