### ISSUE TITLE
[Enhancement] Allow configuration of the number of weight_proof worker processes 

### ISSUE THREAD

**Issue by liuyuansharp** [Chia-Network/chia-blockchain#11138]
### What happened?

i just run a chia wallet on ECS with 1G ram. 
The 4 wallet_worker almost running out of memory on the ECS。

i found the default  wallet processes is 4.

self._num_processes = 4

Is there any way to configure this parameter?

### Version

1.3.3

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
It is not configurable, other than changing the code.
