### ISSUE TITLE
Address critical TODOs in src/ [ENHANCEMENT]

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#1113]
There are a number of TODOs and many of them need to be handled or resolved as WONTFIX. I have skipped some TODOs that were not release or consensus critical.

## Critical for mainnet farming
- [x]  https://github.com/Chia-Network/chia-blockchain/blob/main/src/consensus/block_body_validation.py#L93 "The prev generators root must be valid" @aqk 
- [x] https://github.com/Chia-Network/chia-blockchain/blob/main/src/consensus/block_creation.py#L151 "prev generators root" likely @aqk 
- [x] https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node.py#L1147 "finished slots is not correct" @mariano54 
- [x] https://github.com/Chia-Network/chia-blockchain/blob/main/src/consensus/difficulty_adjustment.py#L79 "The blocks selected for the timestamps are the last block which is also a transaction block, and which is infused before the final block in the epoch. Block at height 0 is an exception. check edge cases here" Believe this is @bramcohen 's requested change from @mariano54 
- [x] https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node.py#L1129 "should we look at end of slots too?"  @mariano54 
- [x] https://github.com/Chia-Network/chia-blockchain/blob/main/src/timelord/timelord.py#L239 "handle the special case when infusion point is the end of subslot." @mariano54 
- [x] https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node_store.py#L582 "Returns all sub slots that have been completed between the prev sb and the new block we will create - review this code" @mariano54 

## Critical for mainnet first transaction
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/types/mempool_item.py#L23 "test to see if self.fee_per_cost < or >"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/consensus/block_body_validation.py#L310 "Check for spending a coin that does not exist in this fork - fix this, there is a consensus bug here" @Yostra 
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/util/condition_tools.py#L77 "pkm_pairs_for_conditions_dict - check types"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/util/condition_tools.py#L100 "check condition very carefully (ensure there are the correct number and type of parameters) maybe write a type-checking framework for conditions and don't just fail with asserts"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/util/condition_tools.py#L117 "check condition very carefully" near duplicate of one above.
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/wallet/wallet_node.py#L722 "review all verification - validate_removals - wallet"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/wallet/wallet_state_manager.py#L723 "handle returning of -1 in find fork point"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/wallet/wallet_state_manager.py#L74 "Don't allow user to send tx until wallet is synced"

## Not critical for mainnet
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node.py#L1029 "count overflow blocks separately (also in validation)" @mariano54 
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/consensus/block_body_validation.py#L390 "22. Verify aggregated signature - move this to pre_validate_blocks_multiprocessing so we can sync faster"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node.py#L329 "fix weight proofs so they work at the beginning as well" @almogdepaz - this may have already been addressed.
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node.py#L1034 "pre-validate VDFs outside of lock"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/full_node/full_node.py#L537 "disconnect from peer which gave us the heaviest_peak, if nobody has the peak"
- [x] https://github.com/Chia-Network/chia-blockchain/blob/main/src/simulator/simulator_constants.py#L5 "fix this with new consensus" @mariano54 
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/util/streamable.py#L39 "Remove hack, this allows streaming these objects from binary"
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/wallet/cc_wallet/cc_wallet.py#L624 "add support for array in stored records" @matt-o-how 
- [ ] https://github.com/Chia-Network/chia-blockchain/blob/main/src/wallet/wallet_node.py#L802 "why if record_info is not None and record_info.wallet_type == WalletType.COLOURED_COIN?"

**Comment by mariano54** [comment]
I have categorized the ones that are important for mainnet farming launch

**Comment by mariano54** [comment]
The consensus todos were fixed by this change:
https://github.com/Chia-Network/chia-blockchain/pull/1174
