### ISSUE TITLE
My comp restarted and now Chia won't restart

### ISSUE THREAD

**Issue by dhandler01** [Chia-Network/chia-blockchain#11145]
### What happened?

I even download the new version 1.3.3 or whatever from 10 days ago and it won't even launch to install.  

### Version

Whatever the last Beta was...

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by LeslieChiang** [comment]
yea.. is very delicate. I don't know how many times I had to reinstall.

**Comment by dhandler01** [comment]
This does not inspire confidence that this platform is viable long term...

**Comment by wallentx** [comment]
Are you able to set your chia config.yaml to DEBUG, and share the log output when you attempt to start it? Without more details, we can't determine if the issue is specifically related to Chia.

**Comment by wallentx** [comment]
I've also noticed that if you have bad values in your `config.yaml`, and you try to launch the GUI, nothing appears to happen. If you check your task manager, you may see 3 Chia services, but nothing outputs to the logs.
You may want to kill any of the Chia processes running, rename your current `config.yaml`, and try to re-launch Chia. It should generate a new `config.yaml`, and Chia should open.

You can verify if this is indeed the issue by running `.\chia.exe stop all -d` from your `C:\Users\YOURUSER\AppData\Local\chia-blockchain\app-YOURVERSION\resources\app.asar.unpacked\daemon\` directory. If you have an invalid `config.yaml`, it will inform you of the issues.
