### ISSUE TITLE
Transactions are gone after the update [Bug] 

### ISSUE THREAD

**Issue by Sulphurian** [Chia-Network/chia-blockchain#11169]
### What happened?

Hi,

Yesterday, I updated the CHIA to version 1.3.3. Today, all my 20 receiving transactions from March 13 to April 13 were deleted (yellow box below), and I lost around 0.25 XCH in my balance. I'm synced to mainnet, no outside transcations or transfers were made.

How can I solve it?

![image](https://user-images.githubusercontent.com/103616718/163299584-3314ea43-d5bd-46bc-8281-2aec2603aac2.png)

![image](https://user-images.githubusercontent.com/103616718/163300711-a0a63ca6-aca2-4a7b-b5af-d8b98bc82a8b.png)

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you syncing in "Farming mode" or "Wallet mode"?

**Comment by Sulphurian** [comment]
> Are you syncing in "Farming mode" or "Wallet mode"?

In both modes, the same problem persists.

**Comment by emlowe** [comment]
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by emlowe** [comment]
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5
