### ISSUE TITLE
[Bug] 当农场规模达到2PiB以上，GUI会运行缓慢。

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11172]
### What happened?

当农场规模达到2PiB以上，GUI会运行缓慢。

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
This should be helped by https://github.com/Chia-Network/chia-blockchain/pull/9695

**Comment by jcheng0509-Chia** [comment]
如果你有兴趣可以在Keybase上联系我 @jcheng0509, 可以试试看我们内部的新版本有没有解决问题

**Comment by sunyuting83** [comment]
直接命令行挖就行了。GUI开不开都一个样。

**Comment by 0X1231** [comment]
> 如果你有兴趣可以在Keybase上联系我 @jcheng0509， 可以试试看我们内部的新版本有没有解决问题
希望你们在下一个版本中解决此问题。

**Comment by emlowe** [comment]
Fixed in 1.3.5 - freel free to reopen if you continue to have issues in 1.3.5
