### ISSUE TITLE
[Bug] Key list missing from initial GUI screen

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#11176]
### What happened?

1.3.2.dev156 build:

My login screen no longer reliably shows my list of keys. On launch, the keys are not displayed. I have about 15 separate keys. Quitting and restart resolves. But if I leave a wallet and try to open another, it will hang with a spinner, and then show no keys in the list. 
- 
![Screen Shot 2022-04-14 at 2 23 05 PM](https://user-images.githubusercontent.com/86693700/163479471-1b6981ac-3e29-4c06-a8f2-1c19053a7dcc.png)
 

### Version

1.3.2.dev156

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
This looks to be the GUI version of https://github.com/Chia-Network/chia-blockchain/issues/11175

**Comment by wallentx** [comment]
Closing since it's a dupe
