### ISSUE TITLE
  Fee for misfilling

### ISSUE THREAD

**Issue by a6654196** [Chia-Network/chia-blockchain#11174]
### What happened?

Mine Pool to receive incentives, the wrong to fill in the cost of 1.75, how to find back

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by a6654196** [comment]
xch1n4tqjh3pju52e664s59qz2h509wjaucnv4j66c5tl098as7sxysq79ye75

**Comment by wallentx** [comment]
This duplicates https://github.com/Chia-Network/chia-blockchain/issues/11112 so I will close this issue.
