### ISSUE TITLE
[Bug] An invalid config.yaml will cause the Chia GUI to fail to open silently in Windows (and prob other OSs)

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#11180]
![2022-04-15_03-30 (1)](https://user-images.githubusercontent.com/8990544/163547258-0fad9ced-9c5d-48d2-bf65-6daaaf26e3db.png)
### What happened?

Easily repeatable:
- Stop all Chia services
- Open your config.yaml, and make a modification that would intentionally break valid yaml formatting
- Save the config.yaml
- Double click Chia icon to launch it
- After noticing that nothing is happening, check task manager and you'll see a few Chia processes, but nothing will be in the logs
- verify what is happening by trying to execute `chia.exe stop all -d` from the command line, and you'll see that it's throwing a `yaml.scanner.ScannerError`, which prevents any Chia services from attempting to run, which would also prevent it from outputting any log info.

### Version

1.3.2.dev156

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
see https://trello.com/c/Rwj2jdei/1268-ui-needs-to-have-timeouts-and-handle-problems-when-starting-chia-services
