### ISSUE TITLE
The correct wallet balance is not displayed

### ISSUE THREAD

**Issue by tuniflor** [Chia-Network/chia-blockchain#11198]
Good afternoon, 
made a registration on https://www.chia.net/download/
Transferred 39,90023860 XCH into the wallet 2022-03-13 00:51:04,
withdrawal address xch16a4vgxdnyzpjr8l6895xqwdsqjwn5nx0arxm6v9ylxhewsj9kxks9m33mv
after the completion of synchronization, the balance was reflected in full.
When I accessed the wallet again, with the seed phrase, the balance reflected zero coins.
Please sudgest me why this happens and how to restore the correct balance 
BR
![CXH transaction 2022-04-17 at 09 53 45](https://user-images.githubusercontent.com/103874729/163704165-4cfe49a7-90ef-4ec2-8311-e152c1a3def9.jpeg)

**Comment by wallentx** [comment]
We don't have a mobile app. What app is this in your screenshot?

**Comment by emlowe** [comment]
Closing issue
