### ISSUE TITLE
[Bug] Edit Payout instructions option disappeared

### ISSUE THREAD

**Issue by fish7221** [Chia-Network/chia-blockchain#11191]
### What happened?

I did a fresh install of chia gui 1.3.3 on a windows 10 machine. I don't see the "Edit Payout instructions option" in the pool tab 3-dots menu.
I have another computer with 1.3.3 which I DO see the option, And also saw the option in previous versions of chia gui.

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Closing issue due to lack of response
