### ISSUE TITLE
v2 db file still very large after both upgrade and clean syncs [Bug]

### ISSUE THREAD

**Issue by pyroguysf** [Chia-Network/chia-blockchain#11192]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/11049

I'm experiencing the same bug, as have a few others I've heard from. I've upgraded the db files using 1.3.1 of both a Windows 10 and RPi4 environment that have been up since July and only saw a ~5% reduction in both cases when the v2 file was finished (87.3 GB v1 to 82.9 GB v2 on Windows). I've also done multiple clean installs of Windows 10 in both VMs and on bare hardware, updated it, installed the latest version of Chia (used 1.3.1 and 1.3.3), put in my keys, turned off UPnP, and let it sync. In every single case, my v2 db files are currently at 90+ GB.

<div type='discussions-op-text'>

<sup>Originally posted by **20pyro00** April  3, 2022</sup>
### What happened?

I am running chia on a Raspberry Pi 4 using linux. I got a message, that my farm stopped working, so i checked on it. There was a JavaScript error, telling me "no space left on device". I then checked the filemanager and saw, that the .sqlite-file is 90GiB!!! My Wallet-file is also 9GiB. Is that normal? I had a lot of problems with my setup and had to restart/reinstall often. Could that somehow broke something?

### Version

1.3.3

### What platform are you using?

Pi4

### What ui mode are you using?

GUI

### Relevant log output

_No response_</div>

**Comment by shaneo257** [comment]
when you installed the 1.3.x client, did you run the `chia db upgrade` command as detailed here https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#upgrade, that will then convert your db from v1 to v2 and have the reduced size

**Comment by pyroguysf** [comment]
Per my original comment, yes, I upgraded, for only a 5% reduction, but that part of the problem is pretty irrelevant when I can clean install an OS, clean install Chia, clean sync v2, and end up with the same result because that means there's a larger issue going on that isn't user caused since all I'm doing to the clean install is giving it my keys and turning off UPnP (which is explained as a "tip" in the quickstart guide, and I'd just rather not let programs use UPnP if they don't need it).

I'm not the only one this is happening to, but I only saw a discussion on here about it, not an issue, so I opened this one. There's another guy on reddit that said his friend has the problem, but he doesn't - [link](https://www.reddit.com/r/chia/comments/u368jb/hardware_keeps_dying_how_many_writes_does_the_new/i4umjoj/). I've seen plenty of other people posting about the same problem too. 

There's not really anything left I can try as a user if a clean install causes the same issue. I'd happily upload the .sqlite file for testing...if it wasn't 90+ GB on a 10mbps upload. I don't know if any log files will be useful either, but for me at least, the issue has been consistently reproduceable in a clean environment.

**Comment by emlowe** [comment]
I suspect your DB is not actually using the V2 format (the filename is not an indication of the format of the DB). Please run `chia db validate`

**Comment by pyroguysf** [comment]
> I suspect your DB is not actually using the V2 format (the filename is not an indication of the format of the DB). Please run `chia db validate`

On a clean machine that has had Windows 10 reinstalled, with chia 1.3.3 installed, never any earlier version, the output is:
`opening file for reading: D:\.chia\db\blockchain_v2_mainnet.sqlite`
`FAILED: Database is missing version table`
I have a few TB of plots on an external and this system farms and gets pool points without any issue. The path above is correct - the db is on a different drive since it won't fit on my OS drive.

On my main farming system that's been up since July, been upgraded to 1.3.1, had the db manually upgraded, then updated to 1.3.3, the output is:
`opening file for reading: C:\Users\chia\.chia\mainnet\db\blockchain_v2_mainnet.sqlite`
`peak hash: 96e4b0ba051822fe287688aeb905df8b5891ecf5fc6bd8d1b9b6942e64946f50`
`peak height: 1856466`
`traversing the full chain`
`0 orphaned blocks: 592`
`592 orphaned blocks`
`DATABASE IS VALID: C:\Users\chia\.chia\mainnet\db\blockchain_v2_mainnet.sqlite`

**Comment by emlowe** [comment]
`FAILED: Database is missing version table` - this means your DB is v1 despite the filename

**Comment by pyroguysf** [comment]
> `FAILED: Database is missing version table` - this means your DB is v1 despite the filename

So, if that's the case, then 1.3.x has a bug that can make a v1 database on a clean install, but instead it names it as a v2?
As an experiment... I shut down chia, renamed the db from v2 to v1, and changed two lines in config.yaml from v2 back to v1, started it back up and am now running chia db upgrade on this. I'll update with the results when it finishes.

### **However...** 
That just means there's two problems with the same symptom, because, my main farmer on 1.3.3 that underwent the db upgrade, and successfully validated with the output above is still massive.

**Comment by emlowe** [comment]
My v2 node DB is 59 GiB (as reported by `ls -h`) - I don't know why your DB appears to be so much larger. Yes, 1.3.x does have a bug that it may not create a v2 DB by default - this has been fixed in #10498 but I don't think that has make it into a release yet.

**Comment by B1gCarr0t** [comment]
> > `FAILED: Database is missing version table`- 这意味着您的数据库是 v1，尽管文件名
> 
> 如果是这种情况，那么 1.3.x 有一个错误可以在全新安装时生成 v1 数据库，但它却将其命名为 v2？ 作为一个实验......我关闭了 chia，将 db v2 重命名为 v1，并将 config.yaml 中的两行从 v2 更改回 v1，重新启动它，现在正在运行 chia db upgrade 。完成后我会更新结果。
> 
> 最初验证失败的v2文件从全新重命名为v1、更新config.yaml、“chia db升级”，104 GB v1文件从104 GB缩小到6 GB。然后编辑后的那样，这是一个尺寸的差别很大，但安装的手动配置工作非常具有创新性，并且工作需要相当多的手动配置工作。
> 
> ### **然而……**
> 这只是意味着，并有两个问题有着相同的表现，因为我在 1.3.3 上的主要经常性经历了数据库升级成功验证了其他的输出仍然很大。

We did the same thing, but I can't ensure that the v2db obtained in this way is effective

**Comment by emlowe** [comment]
I don't believe there are any further issues here to resolve - closing issue
