### ISSUE TITLE
[Bug] CH21 token shows in Pending but not in Spendable or Total

### ISSUE THREAD

**Issue by teapot33** [Chia-Network/chia-blockchain#11199]
### What happened?

CH21 tokens that have a balance are not showing up on Spendable Balance

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by teapot33** [comment]
![chiabug1 9633](https://user-images.githubusercontent.com/103876495/163705797-a0b4da98-4a63-49ee-9a79-561cf0429206.PNG)

**Comment by emlowe** [comment]
Generally such issues are resolved by resyncing your wallet - recommend trying v1.3.4 released today

**Comment by wallentx** [comment]
Are you able to download the Latest Dev and see if this still happens? We put in some fixes yesterday that seem to resolve this problem in our testing so far. https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
If this does work for you, please let us know!

**Comment by teapot33** [comment]
Great, yes this is resolved. Thanks
