### ISSUE TITLE
[Bug] Incorrect wallet balance

### ISSUE THREAD

**Issue by p30hashemi** [Chia-Network/chia-blockchain#11215]
### What happened?

Shows the wallet balance after syncing incorrectly.
What should I do to have the correct display?

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Generally, resyncing the wallet resolves such issues

**Comment by p30hashemi** [comment]
What should I do to do this?

**Comment by endurance1968** [comment]
Stop and retart GUI or more drastic: Stop GUI, _delete wallet DB_ (mabe take a backup), restart gui should fix it.

**Comment by wallentx** [comment]
Are you able to download the Latest Dev and see if this still happens? We put in some fixes yesterday that seem to resolve this problem in our testing so far. https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
If this does work for you, please let us know!

**Comment by kckc33** [comment]
i am having the same problem, deleted everything reinstall and also tried the newest beta
wallets shows incorrect balance and shows none transaction history

what should i do

**Comment by emlowe** [comment]
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by emlowe** [comment]
Please test 1.3.5 as several related issues were resolved. Closing issue - please re-open if you have issues with 1.3.5
