### ISSUE TITLE
[Bug] 因为chia官方的收割机不好用，我被逼成了hpool的无节点矿工。

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11216]
### What happened?

我的机器上有170张硬盘，我的收割机无法正常工作。如果减少一部分硬盘，减少到几十块，则收割机可以正常工作。因为收割机的问题，我现在去了hpool去做了无节点矿工，这跟我对chia的信仰违背，但是我没有其它办法。hoppl的扫盘工具，比收割机好用太多了。希望官方可以借鉴。

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Closing as duplicate of #11225
