### ISSUE TITLE
disable to get in my account [Bug] 

### ISSUE THREAD

**Issue by allzima1** [Chia-Network/chia-blockchain#11217]
### What happened?

The blockchain spontaneously got me out and now it doesn't let me in through the 24 key words. what the hell should i do?

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
'NoneType' object is not subscriptable
```

**Comment by allzima1** [comment]
Guys i just found out the solution. you only need to reinstall the previous version blockchain. That is just ridiculous bug of the shitty new version.....

**Comment by catxch** [comment]
> พวกฉันเพิ่งพบวิธีแก้ปัญหา คุณจะต้องติดตั้ง blockchain เวอร์ชันก่อนหน้าใหม่เท่านั้น นั่นเป็นข้อผิดพลาดที่ไร้สาระของเวอร์ชันใหม่ที่น่าขยะแขยง .....

What version did you install to fix the problem?

**Comment by emlowe** [comment]
Duplicate of #10593 - the circumstances that cause this error aren't complete known - however, restarting the app generally is a workaround
