### ISSUE TITLE
[Bug] 卡住了一笔CH21 NFT交易，请问这种情况应该怎么处理？

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11224]
### What happened?

![image](https://user-images.githubusercontent.com/97425684/164080113-d9c8437e-c2b5-482d-aaa1-d5942bfbb4c1.png)
点过撤回了，但是没有效果，状态已经是已完成了，但是钱包里显示待处理。

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by 0X1231** [comment]
临时解决方法，删掉了钱包数据库。

**Comment by emlowe** [comment]
Duplicate of #11199 - I recommend you resync you wallet with v 1.3.4
