### ISSUE TITLE
[Bug] Install.sh won't install on Arch Linux

### ISSUE THREAD

**Issue by SemnoSao** [Chia-Network/chia-blockchain#11238]
### What happened?

Clean clone of repo on Manjaro Linux.

```$ sh install.sh
Installing on Arch Linux.
warning: git-2.35.1-1 is up to date -- skipping
warning: openssl-1.1.1.n-1 is up to date -- skipping
 there is nothing to do
```

the next command on the instruction from installing from source is `. ./activate` that gives the following output:

`bash: ./activate: No such file or directory`

I suspect the problem is the install.sh is just not doing what it should 🧐

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by LuaKT** [comment]
Chia currently only supports python 3.9 and below. If you have an up-to-date Arch install you likely have python 3.10 so you need to install 3.9 from AUR.

There is also a bug in the install script where it doesn't correctly display the wrong version error.

**Comment by SemnoSao** [comment]
Thankss! 
installing python39 from AUR solved the problem.
