### ISSUE TITLE
[Bug] When running start harvester on 1.3.4 on my rpi4 I get ssl error

### ISSUE THREAD

**Issue by BubbleTrouble14** [Chia-Network/chia-blockchain#11232]
### What happened?

When running the command start harvester on my rpi 4 I get this error.

### Version

1.3.4

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f98c8b780>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
```

**Comment by BubbleTrouble14** [comment]
Did a clean install of the chia-blockchain folder and a restarted the rpi4, still didnt fix the issue.

**Comment by BubbleTrouble14** [comment]
Weird thing is that one rpi4 works but the other 3 not.

**Comment by BubbleTrouble14** [comment]
Tried removing .chia folder and re-running chia init -c with the certificates again but also didnt fix the issue.

**Comment by stefan-lange** [comment]
Maybe the old and deprecated python 3.7 is a problem? Just guessing

**Comment by emlowe** [comment]
Not sure this is something chia can resolve directly - see https://github.com/aio-libs/aiohttp/issues/3535

Looks to be a spurious error from the aiohttp report - but it seemed wasn't consistent. I might consider trying at least python 3.8

**Comment by BubbleTrouble14** [comment]
Okay I think it had to with the python version for some reason. I just flashed the raspberry pi's and using ubuntu server instead of raspbian lite now.
