### ISSUE TITLE
[Bug]  Dashboard is missing nodes info, instead says "No data"

### ISSUE THREAD

**Issue by brause** [Chia-Network/chia-blockchain#11251]
### What happened?

Sorry, i did not know where to put this. So here we go:

Peer info is empty right now:
https://dashboard.chia.net/d/em15uQ47k/peer-info?orgId=1
![image](https://user-images.githubusercontent.com/6328682/164390181-370a54ce-23a0-4090-af4c-2640a919b66a.png)

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by justinengland** [comment]
not a block chain issue, please do not submit dashboard issues to the block chain repo.

**Comment by emlowe** [comment]
Thanks for the report! - we do have a repo for the grafana dashboard  - https://github.com/Chia-Network/pub-metrics-grafana
