### ISSUE TITLE
[Bug] Can't create cold wallet from Windows GUI. Client 'soft lock' if started without internet connection

### ISSUE THREAD

**Issue by jm-XCHcentral** [Chia-Network/chia-blockchain#11250]
### What happened?

Tried booting GUI on a fresh install of Win10 without an internet connection to create a "cold wallet".

-Selected "Wallet" mode. 
-GUI doesn't start the Wallet service without an internet connection. 
-At this point, the Chia GUI is "soft locked" on the starting services screen.  Closing the client and restarting just takes you back to the same screen. Also uninstalled the software and reinstalled, which again, brings you back to the same screen. 

-Wallet service started upon activating internet connection. (which makes these keys unsuitable to be used for a cold wallet)

Also tried:
-Switched client to "Farmer" mode.
-Let client connect and sync ~1000 blocks.
-Shut down client & turned off internet connection.
-Restarting client, and none of the services loaded, resulting in the same "soft lock"

Recommend the creation of a "cold wallet generation" option in the GUI. 
Also recommend moving the client past the "starting services" screen even if they don't have an internet connection. The "soft lock" will be extremely frustrating for users who aren't aware of the issue.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by jm-XCHcentral** [comment]
Also Tested on an M1 Mac Mini.
GUI functioned fine without being connected to the internet. Services started as expected and was able to create keys through GUI in an acceptable "cold wallet" manner.

**Comment by emlowe** [comment]
I was able to disconnect from the network and using the latest release 1.6.2 I was able to generate a new key with the GUI without issues.

This was likely fixed at some point 

Closing issue
