### ISSUE TITLE
[Bug] chia in docker container with non-root user won't start / lock file problem / compile_clvm

### ISSUE THREAD

**Issue by stefan-lange** [Chia-Network/chia-blockchain#11257]
### Environment
- custom docker image
- chia 1.3.4 compiled from source
- pipenv as venv
- python 3.9.12 (also tested with 3.9.11, 3.9.10)
- **'non-root'** user inside docker, chia runs as user 3981

### Command inside docker container
chia -h
...every chia_* cmd hangs

### Current state
deadlock, chia doesn't show anything. 

### Expected state
help is shown

### Debugging support
- Stack see below
- per try-and-error debugging I can say the problem is the custom user in combination with lock file creation of `compile_clvm`. Maybe the lock file is written to some directory with different permissions. What is this concrete directory?
- with user `root` everything works fine
- until chia 1.3.3 the custom user also worked fine

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia@27d9ea5841a5:/app$ chia -h
^CTraceback (most recent call last):
  File "/opt/chia-blockchain/.venv/bin/chia", line 5, in <module>
    from chia.cmds.chia import main
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/cmds/chia.py", line 18, in <module>
    from chia.cmds.plotters import plotters_cmd
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/cmds/plotters.py", line 2, in <module>
    from chia.plotters.plotters import call_plotters
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/plotters/plotters.py", line 5, in <module>
    from chia.plotters.bladebit import get_bladebit_install_info, plot_bladebit
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/plotters/bladebit.py", line 10, in <module>
    from chia.plotting.create_plots import resolve_plot_keys
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/plotting/create_plots.py", line 10, in <module>
    from chia.daemon.keychain_proxy import KeychainProxy, connect_to_keychain_and_validate, wrap_local_keychain
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/daemon/keychain_proxy.py", line 5, in <module>
    from chia.cmds.init_funcs import check_keys
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/cmds/init_funcs.py", line 10, in <module>
    from chia.consensus.coinbase import create_puzzlehash_for_pk
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/consensus/coinbase.py", line 6, in <module>
    from chia.wallet.puzzles.p2_delegated_puzzle_or_hidden_puzzle import puzzle_for_pk
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py", line 68, in <module>
    from .p2_conditions import puzzle_for_conditions
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/p2_conditions.py", line 17, in <module>
    MOD = load_clvm("p2_conditions.clvm")
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/load_clvm.py", line 106, in load_clvm
    return Program.from_bytes(bytes(load_serialized_clvm(clvm_filename, package_or_requirement=package_or_requirement)))
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/load_clvm.py", line 92, in load_serialized_clvm
    compile_clvm(full_path, output, search_paths=[full_path.parent])
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles/load_clvm.py", line 73, in compile_clvm
    with_lock(f"{full_path}.lock", do_compile)
  File "/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/util/lock.py", line 39, in with_lock
    time.sleep(0.1)
KeyboardInterrupt
```

**Comment by stefan-lange** [comment]
the reason seems to be that the clvm compile logic wants to create a *.lock file in
```
/opt/chia-blockchain/.venv/lib/python3.9/site-packages/chia/wallet/puzzles
```

fixed it for me with this, which is not 100% future proof. That changes the owner of the code directory to the current user, so it can be written to:
```
RUN find /opt/chia-blockchain/.venv/ -type d -name "puzzles" -exec chown $UID {} \;
```

I don't understand exactly why this is done, because in the folder there are already `*.clvm` and the related `*.clvm.hex` files - in my case. I think it is not really nice, because the app code can be changed during execution. My intention was to secure the app so no one can change it.

Suggestion: if you need temp or cache files, why not using the existing folders like ~/.cache etc. for that? There should be version for every OS.

**Comment by sashka4** [comment]
the workaround is legit: making container's /chia-blockchain/chia/wallet/puzzles writable fixes the deadlock.
I don't think it is a best practice to compromise immutability of SW containers. I use [official chia docker container]([url://https://github.com/Chia-Network/chia-docker]) in read-only mode, so making it fully or partially writable is undesirable. I hope the team can address the issue in one of the upcoming releases.

**Comment by strayer** [comment]
Can this be reopened? This is affecting me too. I'm running Chia in a custom Docker image that is not run as root, so starting chia always fails with this deadlock since the virtualenv is owned by root and the whole container is read-only too.

For now I hacked a permission fix into my image and stopped running the container with read_only, but this shouldn't be the case.

**Comment by stefan-lange** [comment]
> Can this be reopened? This is affecting me too. I'm running Chia in a custom Docker image that is not run as root, so starting chia always fails with this deadlock since the virtualenv is owned by root and the whole container is read-only too.
> 
> For now I hacked a permission fix into my image and stopped running the container with read_only, but this shouldn't be the case.

Sure, I can. Maybe there will be some answers from 'officials' ;). Took me a few hours and at least one grey hair to find a solution ^^

**Comment by stefan-lange** [comment]
Dear bot, go away!

**Comment by stefan-lange** [comment]
Dear bot, go away, forever!

**Comment by wiryonolau** [comment]
Is this fix on 1.4.0 ?

**Comment by stefan-lange** [comment]
no, not fixed, but the workaround still works, see https://github.com/Chia-Network/chia-blockchain/issues/11257#issuecomment-1106553247

**Comment by Damme** [comment]
this happened to me too, got my own docker files since the beginning, and I also had to change the owner to make it run. I had no issue with 1.3.5 though.

**Comment by lourkeur** [comment]
I ran into this issue when installing Chia 1.5.0 through Nixpkgs. It is also designed around immutability so the python module directory is not writable. Starting something as simple as `chia` with no argument hangs since the lock code keeps trying to lock the file on behalf of the clvm compiler.

I think this could be resolved with a smarter locking procedure that would raise an error when it cannot create the lock but the lock doesn't exist. I will try to see if applying #12541 solves the issue. (It probably will add a big delay since every lock has to timeout one after the other.)

**Comment by wallentx** [comment]
> 

We are working on this at the moment (https://github.com/Chia-Network/chia-blockchain/pull/12050 is part of it), but for the moment, this workaround seems to be the advisable.
