### ISSUE TITLE
no reconoce mis discos al cambiar 1.3.4

### ISSUE THREAD

**Issue by fermin55** [Chia-Network/chia-blockchain#11266]
Actualice windows 10 21h2, y a 1.3.4 de chia y no reconce mis discos, ni puedo hacer parcelas, que se  puede hacer

**Comment by wallentx** [comment]
Hi, are you farming and plotting all on once machine, or do you have remote harvesters? With 1.3.4, you'll need to update your remote harvesters as well.
As for not being able to make plots, can you describe what's happening, or provide logs or screenshots?

**Comment by emlowe** [comment]
closing issue due to lack of response
