### ISSUE TITLE
[Bug] After the transition from version 1.2.11 to 1.3.4, one of the Plots parts stopped joining the pool

### ISSUE THREAD

**Issue by MatveyFV** [Chia-Network/chia-blockchain#11260]
### What happened?

After the transition from version 1.2.11 to 1.3.4, one of the Plots parts stopped joining the pool:
![image](https://user-images.githubusercontent.com/82934186/164602572-d44832a1-9b15-48b1-a83b-923a87072917.png)
![image](https://user-images.githubusercontent.com/82934186/164784883-5342e5cc-3374-4675-bfa1-92157ce97c72.png)

### Version

Chia Blockchain 1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Move your wallet DB out of the way and resync the wallet should resolve this.

The wallet DB is located in `C:\Users\[name]\.chia\mainnet\wallet\db`

**Comment by MatveyFV** [comment]
Move 112 Gb out of the way - doesn't seem like a good idea...

**Comment by wallentx** [comment]
Are you able to download the Latest Dev and see if this still happens? We put in some fixes yesterday that seem to resolve this problem in our testing so far. https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
If this does work for you, please let us know!

**Comment by emlowe** [comment]
Please upgrade to 1.3.5 and resync your wallet. Marking closed - free free to reopen if you have further issues with 1.3.5
