### ISSUE TITLE
1.3.4 Farming Performance (400 second lookup time) [Bug] 

### ISSUE THREAD

**Issue by reythia** [Chia-Network/chia-blockchain#11280]
### What happened?

I have a large monolithic farm with several JBODs attached to a single farmer.

New releases occasionally lead to very slow farming performance, whilst 1.3.3 was generally stable.

1.3.4 sets a new record at 437 seconds for a lookup.

I have full DEBUG level logs available and am happy to work with team over keybase (reythia).

A grep of logs suggests there is a single disk is associated with the majority of slow lookups since 1.3.4, so the issue may well be hardware on my end. I will check this and report back.

**Even if it is a failing disk, it shouldn't bring down the whole farm.**

Wouldn't it make more sense for lookups to timeout with a warning after ~30 seconds rather than skipping several signage points? And respond with what is available in time? ie "700 of 800 plots"

Previous farming issues:

1.3.0 https://github.com/Chia-Network/chia-blockchain/issues/10668
1.2.10 https://github.com/Chia-Network/chia-blockchain/issues/8972

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-04-23T06:19:30.698 harvester chia.harvester.harvester: WARNING  Looking up qualities on ... took: 437.51397252082825. This should be below 5 seconds to minimize risk of losing rewards.

2022-04-23T06:19:30.698 harvester chia.harvester.harvester: INFO farming a71d9acfe9... Found 0 proofs. Time: 437.51397 s. Total...
```

**Comment by xdustinface** [comment]
This should be fixed already by https://github.com/Chia-Network/chia-blockchain/pull/11204.

**Comment by reythia** [comment]
Testing 1.3.547

**Comment by chiamaster** [comment]
latest patch still not fixed for me

**Comment by alnuweiri** [comment]
Could you please provide more lines of the log file where this problem is happening, I have found an issue where I am receiving some signage points twice and that is making the harvester look twice for the proof in less than 1 second, and I believe this might make the lookup time very long in the second time if you have a big farm.  Check issue #11294

**Comment by reythia** [comment]
Closing this issue as the long lookup times in 1.3.4 appear to be - coincidentally timed - with a failing disk.

The current potentially performs better at startup when loading plots, but 1.3.4 shows no on-going issues since pulling the bad disk.

I think graceful handing of slow responses from bad disks or unavailable network shares is a different issue.

**Comment by reythia** [comment]
Closing this issue as the long lookup times in 1.3.4 appear to be - coincidentally timed - with a failing disk.

The current potentially performs better at startup when loading plots, but 1.3.4 shows no on-going issues since pulling the bad disk.

I think graceful handing of slow responses from bad disks or unavailable network shares is a different issue.

**Comment by emlowe** [comment]
Note, long lookup times due to a single disk issue is a long standing issue (see #7788 ), however, it isn't simple to solve and hasn't been a high priority.
