### ISSUE TITLE
[Bug] 1.3.4 Breaks rpc over lan (self_hostname binding)(windows, maybe others?)

### ISSUE THREAD

**Issue by MindSpice** [Chia-Network/chia-blockchain#11282]
### What happened?

I use a custom farm manger I wrote to monitor my farm.  My farmer is also running windows, so I'm not sure if this issue is only with windows or also is reproducible on linux.

Upon updating to 1.3.4 I can not long start the daemon with self_hostname set to anything but local_host. Reverting to 1.3.3 instantly fixes the issue.

Some cravats. To be able to bind my  self_hostname on windows to allow remote(lan) access I already had to bind it to the actual lan ip (192.168.0.xxx) as binding to 0.0.0.0 would cause the daemon no not start as well.

I know windows isn't the most ideal system, but using multiple computer around the house and needing windows for work it is easier to keep my farmer on windows as well no not have to deal with samba shares when transferring plots of my network. It would also be worth checking if this is also a bug on linux. 

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Do you get any errors either on the console or in the log? You could try making the change and then run the daemon in the foreground with `chia run_daemon` - this can help identify daemon bugs because errors are typically seen directly in the terminal window. Note, we did change the socket library the daemon uses in 1.3.4 (from websockets to aiohttp which all the other services were using.

**Comment by MindSpice** [comment]
> Do you get any errors either on the console or in the log? You could try making the change and then run the daemon in the foreground with `chia run_daemon` - this can help identify daemon bugs because errors are typically seen directly in the terminal window. Note, we did change the socket library the daemon uses in 1.3.4 (from websockets to aiohttp which all the other services were using.


Not sure why but it worked perfect when updating to 1.3.4 today, though the other night I couldn't get it to work no matter what. Though I didn't think to restart(I have restarted since). Not sure if there was a zombie process I missed or something blocking it from binding or what , but all is well now.

Closing issue. Thanks for the  help, sorry for wasting your time.
