### ISSUE TITLE
Chias not send 

### ISSUE THREAD

**Issue by JoeDaPro12** [Chia-Network/chia-blockchain#11285]
### What happened?

Hello need help.
Wanted to send my chias to the exchange.
Output is not listed in my blockchain. I was always synced. But I still have 1.2.9 maybe because of the version?

![IMG-20220423-WA0000](https://user-images.githubusercontent.com/104257573/164892676-77fda875-d234-4c2a-a3f8-f62b7be27603.jpeg)

Addendum: Restart helped

### Version

1.2.9

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
I'm not sure what the problem here is, your transaction has been sent to the chain and you are waiting for confirmation. This seems normal.
