### ISSUE TITLE
(0.2.4) Fresh install, synchronisation frozen since yesterday

### ISSUE THREAD

**Issue by staviq** [Chia-Network/chia-blockchain#1129]
Fresh windows install, fresh chia install 0.2.4 gui.

Imported 24w from previous windows install ( also on chia 0.2.4 )

Synchronization was painfully slow at first and then stopped altogether and is stuck at the same height since yesterday.

Status Syncing 12832/28415
Connection Status Connected
Wallet status not synced
Wallet height 11104

Height from "Blocks" 12831
Height from "Connections" 31204

All plots have status "Syncing"

[debug.zip](https://github.com/Chia-Network/chia-blockchain/files/6075469/debug.zip)

**Comment by mariano54** [comment]
This is a known bug, will be fixed in next release. For now, restart the application and wait 10-15 minutes. If it doesn't start syncing, try again.

**Comment by staviq** [comment]
Ok.

Thank You for the response!
