### ISSUE TITLE
[Bug] failed to open plots??

### ISSUE THREAD

**Issue by jonny77** [Chia-Network/chia-blockchain#11301]
### What happened?

<img width="877" alt="image" src="https://user-images.githubusercontent.com/1962170/165026364-38045d65-df43-452f-81f5-b55f35fa6965.png">

in old version , the plots are ok 

### Version

latest

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
You should run `chia plots check` against those files - There may have been a transient error that cause them to get reported as invalid.

**Comment by emlowe** [comment]
Closing issue due to lack of response
