### ISSUE TITLE
[Bug] Extremely slow switch to Pool tab 

### ISSUE THREAD

**Issue by endurance1968** [Chia-Network/chia-blockchain#11300]
### What happened?

Open the Chia GUI on a full node with a approx 1PB farm connected using multiple pools.
Switch to Pooling tab. Window opens emtpy then showing connecting to daemon (~ 1minute) while **chia.exe takes a ful CPU core.**

https://github.com/Chia-Network/chia-blockchain/issues/11228 might describe similar issues.

this can be reproduced on slow machines (i7-7700 3.6Ghz)

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
This should be fixed in main. Are you able to try this with a build from Latest Dev - https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
Let us know how your experience is with this

**Comment by endurance1968** [comment]
Confirmed fixed in latest dev version

**Comment by emlowe** [comment]
Closing per latest comments
