### ISSUE TITLE
[Bug] WARNING Will not infuse

### ISSUE THREAD

**Issue by mazm786** [Chia-Network/chia-blockchain#11314]
### What happened?

In Debug.log, Found following string only in bulk Quantity
timelord chia.timelord.timelord   : WARNING  Will not infuse 0b656ac6xxxxxxxxxxxxxxxxxxxxxx because its reward chain challenge is not in the chain

### Version

1.3.3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
timelord chia.timelord.timelord   : WARNING  Will not infuse 0b656ac6xxxxxxxxxxxxxxxxxxxxxx because its reward chain challenge is not in the chain
```

**Comment by shaneo257** [comment]
are you trying to run a timelord?

**Comment by emlowe** [comment]
Closing issue due to lack of response
