### ISSUE TITLE
[Bug] 1.3.4 still automatically synchronize v1db

### ISSUE THREAD

**Issue by B1gCarr0t** [Chia-Network/chia-blockchain#11313]
### What happened?

I reinstalled ChiA1 3.4 and resynchronize the DB, but I got v1db instead of v2db a week later

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by endurance1968** [comment]
did you maybe restore a older config.yaml?
Running several nodes but a automatic fallback to v1 once upgraded I have not seen yet.

**Comment by B1gCarr0t** [comment]
> 

Newly installed Chia. In config, manually point to v2db of D: / /

**Comment by wallentx** [comment]
Are you able to run `chia.exe db validate <path to v1 db>` and share the output? It's possible that it erroneously named it as v1.
