### ISSUE TITLE
[Bug] No pool switch button even if synched

### ISSUE THREAD

**Issue by endurance1968** [Chia-Network/chia-blockchain#11311]
### What happened?

If you open the pool tab on the chia GUI it shows "you cannot... until fully snyched" but the gui shows as status fully synched.
Might be connected to https://github.com/Chia-Network/chia-blockchain/issues/11300 (slow GUI, high load on chia.exe)

Resolve the issue using reloading the window

![2022-04-26_06h57_54](https://user-images.githubusercontent.com/38796027/165225180-28f7514c-6037-4b4b-a62a-598aa78694a6.png)
.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by yiqiang320** [comment]
手动修改yaml  添加矿池

**Comment by endurance1968** [comment]
@yiqiang320 could you please write in english?
It is about the GUI to be fixed - luckily I do not change anything currently.

**Comment by wallentx** [comment]
This also should be fixed in main. Are you able to try this with a build from Latest Dev - https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
Let us know how your experience is with this

**Comment by endurance1968** [comment]
confirmed looks far better now using latest dev version 1.3.5113

**Comment by emlowe** [comment]
Likely fixed in 1.3.5 - you will need to resync the wallet . Feel free to re-open if you see further issues in 1.3.5
