### ISSUE TITLE
[Bug]Неправильный баланс кошелька

### ISSUE THREAD

**Issue by zelentsovab** [Chia-Network/chia-blockchain#11333]
### What happened?

После перезагрузки chia 1.3.4 пропали пополнения кошелька за период с 05.04.2022 по 25.04.2022 и баланс кошелька уменьшился с 0,594861 XCH до 0,385268567664 XCH. Подскажите как исправить.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
close the client, delete your wallet db, and let it resync from 0

**Comment by emlowe** [comment]
Please test with 1.3.5 as various fixes for this are in 1.3.5. Closing issue. Feel free to re-open if problems continue with 1.3.5
