### ISSUE TITLE
[Bug] Cannot delete pool

### ISSUE THREAD

**Issue by yiqiang320** [Chia-Network/chia-blockchain#11349]
### What happened?

![mmexport1651127232095](https://user-images.githubusercontent.com/22174721/165690851-1b236d2a-c9cf-4e89-ac0d-2407e7c32ed8.png)

Cannot delete pool  

### Version

1.3.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
Currently, it is not possible to remove a plotNFT once it is created - we do want to look if it possible to remove plotNFT's in the future

**Comment by 0X1231** [comment]
希望可以删除

**Comment by 0X1231** [comment]
隐藏功能还没有推出呢？

**Comment by 0X1231** [comment]
隐藏功能还没有推出呢？

**Comment by 0X1231** [comment]
隐藏功能还没有推出呢？
