### ISSUE TITLE
[Bug]点击正在更重就发生异常

### ISSUE THREAD

**Issue by juelianfy** [Chia-Network/chia-blockchain#11375]
### What happened?

我一个机器上有13000个地，只要一点击“正在耕种”，程序就会卡死。地块少一点的机器没有这个问题。

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
Possibly fixed in https://github.com/Chia-Network/chia-blockchain/pull/11338

**Comment by chiavivi** [comment]
请问楼主，可以正常领取奖励不？

**Comment by wallentx** [comment]
This should be fixed in main. Are you able to try this with a build from Latest Dev - https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
Let us know how your experience is with this

**Comment by emlowe** [comment]
Fixed in 1.3.5
