### ISSUE TITLE
Wallet not connecting after update

### ISSUE THREAD

**Issue by rhw1** [Chia-Network/chia-blockchain#1139]
After updating to 1.0rc4 from 1.0rc3 I have lost connection with my wallet and the chia therein. It says it is "not synced". Is there a way I can recover the wallet?

**Comment by tentious** [comment]
I'm also having this problem.

**Comment by Badt-AFFKT** [comment]
Full Node Status
Status
Syncing 5024/33903

Tell me what could be the problem?

**Comment by Badt-AFFKT** [comment]
synchronization is in progress and then stopped again

**Comment by mariano54** [comment]
New update coming really soon, fixing the issue

**Comment by Badt-AFFKT** [comment]
Thanks, we'll wait!

**Comment by mariano54** [comment]
Updated to rc5, please install

**Comment by rhw1** [comment]
I have updated to 1.0rc5 and the node has synced, wallet has synced. Still no chia in my wallet. Is there some way to recover it?

**Comment by mariano54** [comment]
It's a new system, all testnet Chia was reset

**Comment by Badt-AFFKT** [comment]
sync works, thanks

**Comment by rhw1** [comment]
OK I think I have it back now. I'll back it up
