### ISSUE TITLE
[Bug] chia daemon listens only on IPv4 socket

### ISSUE THREAD

**Issue by cross** [Chia-Network/chia-blockchain#11397]
### What happened?

This is related, and/or root cause, of bug #11390 .  Something about the aiohttp ws_connect method will perform a connection to "::1" if given a `wss://localhost:55400` URI, at least on some of my hosts that have no IPv4 connectivity.  127.0.0.1 is on the system, and the daemon is listening on it.  But, chia never can tell it's there because chia is trying IPv6.

Unrelated to the problem caused, however, the more correct fix here is to have the main daemon, like farmer and other pieces, listen on IPv6 as well as IPv4 when on a machine with IPv6 addresses.  I'm not sure where this is in the code, or if it's purely within aiohttp somewhere.  But I feel it should be addressed.

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by cross** [comment]
This should remain open.  The daemon should be able to bind to IPv6 and/or both IPv4 and IPv6.

**Comment by emlowe** [comment]
In doing some research on this, the daemon will listen to both IPv6 and IPv4 without code changes, as long as localhost is mapped to both `127.0.0.1` and `::1` in /etc/hosts (windows tests pending).

On macOS, this is the default and so the daemon listens to both by default.
This is also the default on Rocky 8.
However, on Ubuntu, `localhost` is only mapped to `127.0.0.1` and a different name (`ip6-localhost`) to `::1`. However, if `/etc/hosts` is modified to return both for localhost, then the daemon starts listening on both automatically.

Closing issue as it seems that as long as `localhost` is mapped to both addresses, the daemon does listen and is available on both addresses. This seems some specific aspect of Ubuntu that `localhost` is not mapped to `::1`
