### ISSUE TITLE
[Bug] chia db upgrade fails on raspberry pi4

### ISSUE THREAD

**Issue by mcanto73** [Chia-Network/chia-blockchain#11410]
### What happened?

Hello,
chia db upgrade still failing on pi4 raspberry with 4gb ram and zram instsalled.
The procedure start and runs several hours and then it's killed. See below logs.
During the db upgrade chia is running (chia start farmer)
Is there something that I can try ?

thanks

### Version

1.3.4

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) pi@mcanto:~/chia-blockchain $ chia db upgrade
opening file for reading: /chia_plot6/CHIA/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
opening file for writing: /chia_plot6/CHIA/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
initializing v2 version
initializing v2 block store
peak: e37c70xxxxxxxxx....xxxxx9ed0 height: 19xxxx45
[1/5] converting full_blocks
      6388.79 seconds
[2/5] converting sub_epoch_segments_v3
      523.71 seconds
[3/5] converting hint_store
      294.23 seconds
[4/5] converting coin_store
      8332k coins 260.4 coins/s  Killed
(venv) pi@mcanto:~/chia-blockchain $

(venv) pi@mcanto:~/.chia/mainnet/db $ ls -lh
total 143G
-rw-r--r-- 1 pi pi 124G May  3 03:01 blockchain_v1_mainnet.sqlite
-rw-r--r-- 1 pi pi  32K May  3 08:14 blockchain_v1_mainnet.sqlite-shm
-rw-r--r-- 1 pi pi 487K May  3 08:14 blockchain_v1_mainnet.sqlite-wal
-rw-r--r-- 1 pi pi  19G May  3 01:40 blockchain_v2_mainnet.sqlite
-rw------- 1 pi pi  59M May  2 20:41 height-to-hash
-rw-r--r-- 1 pi pi 5.1M May  3 02:57 peers.dat
-rw-r--r-- 1 pi pi 5.0M Mar 11 10:24 peer_table_node.sqlite
-rw------- 1 pi pi 373K May  2 20:41 sub-epoch-summaries
drwxr-xr-x 2 pi pi 4.0K May  3 08:05 TMP
-rw------- 1 pi pi    0 May  3 01:57 tmpdiuxm_o6
```

**Comment by Muffexx** [comment]
Hey.

Do you have enough free storage? Since the average reduction is about 45% you need at least 68G free space for the v2_db (since your v1_db is 124GB)

regards

**Comment by mcanto73** [comment]
> Hey.
> 
> Do you have enough free storage? Since the average reduction is about 45% you need at least 68GB free space for the v2_db (since your v1_db is 124GB)
> 
> regards

yes, there is enough space. About 500gb Free

**Comment by emlowe** [comment]
Check your system log to see if why the process was killed. It may have run out of memory `sudo journalctl | grep -i oom`

**Comment by mcanto73** [comment]
Yes,
you are right : 
May 03 01:57:14 mcanto kernel: Out of memory: Killed process 403177 (chia) total-vm:1868120kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:3684kB oom_score_adj:0

Now I'm trying to convert with chia processes (farming) stopped.

The real problem is now that, after the last db upgrade failed, the synching is no more working. I can connect to peers but the behind is still increasing. Any idea on how can I validate / rebuild the db or fix ?

thanks

**Comment by emlowe** [comment]
The pi4 should be able to sync up - what kind of disk is your DB on? It must be on an SSD in order to catch up.

**Comment by mcanto73** [comment]
> The pi4 should be able to sync up - what kind of disk is your DB on? It must be on an SSD in order to catch up.

sorry but I don't understand your reply ! I know that pi4 is able to sync up but it's abut two days, after last db upgrade fail, that it's no more synching. The disk is a 2 TB Samsung SSD (870 I think). So the question is how to exit from this stale

**Comment by Muffexx** [comment]
Wild assumption: Possibly the (not completely) generated v2_db was not removed, but already stored in the configuration yaml?

**Comment by emlowe** [comment]
1) Check the log file for any errors
2) I don't think the upgrade changes config.yaml until the very end, but it's worthwhile to check if your config.yaml points to the correct thing

The upgrade process itself cannot really cause your node to suddenly not be able to sync, it doesn't modify your existing DB at all.

**Comment by mcanto73** [comment]
2022-05-04T23:02:00.786 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-5601' coro=<FullNode._sync() done, defined at /home/pi/chia-blockchain/chia/full_node/full_node.py:796> exception=ValueError('Header hash b1930f421abc401cfd14646c0faec9443465f9b001405ad2220d41160b15eae0 not in the blockchain')>
Traceback (most recent call last):
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 928, in _sync
    await self._finish_sync()
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 1184, in _finish_sync
    await self.weight_proof_handler.get_proof_of_weight(peak.header_hash)
  File "/home/pi/chia-blockchain/chia/full_node/weight_proof.py", line 89, in get_proof_of_weight
    wp = await self._create_proof_of_weight(tip)
  File "/home/pi/chia-blockchain/chia/full_node/weight_proof.py", line 133, in _create_proof_of_weight
    ses_blocks = await self.blockchain.get_block_records_at(summary_heights)
  File "/home/pi/chia-blockchain/chia/consensus/blockchain.py", line 809, in get_block_records_at
    res = await self.block_store.get_block_records_by_hash(hashes)
  File "/home/pi/chia-blockchain/chia/full_node/block_store.py", line 399, in get_block_records_by_hash
    raise ValueError(f"Header hash {hh} not in the blockchain")
