### ISSUE TITLE
[Bug] Syncing is in stale - pi4 - after db update failed

### ISSUE THREAD

**Issue by mcanto73** [Chia-Network/chia-blockchain#11423]
### What happened?

Hello,
after last db upgrade failed (not sure if related, it failed at least 4/5 times : I tried with all the new chia relase 1.3 1.32 1.33 1.34) chia start, peers connected, Syncing but blocks behind become bigger : 
Current Blockchain Status: Not Synced. Peak height: 1921089
Current Blockchain Status: Syncing 1921089/1927362 (6273 behind).
Current Blockchain Status: Syncing 1921089/1927367 (6278 behind).
Current Blockchain Status: Syncing 1921089/1927381 (6292 behind).

I have restarted, I have switched back to 1.3.3 and now 1.3.4.
I don't see any relevant logs 

Any idea ?

Thanks

### Version

1.3.4

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) pi@mcanto:~/chia-blockchain $ while true
> do
> chia show -s -c | grep Status
> sleep 120
> done
Current Blockchain Status: Not Synced. Peak height: 1921089
Current Blockchain Status: Syncing 1921089/1927362 (6273 behind).
Current Blockchain Status: Syncing 1921089/1927367 (6278 behind).
Current Blockchain Status: Syncing 1921089/1927381 (6292 behind).

(venv) pi@mcanto:~/chia-blockchain $ chia show -s -c
Network: mainnet    Port: 8444   RPC Port: 8555
Node ID: d85ef06529685f227812d6bf31fc00917bbablablaxxxxxxxff980c5
Genesis Challenge: ccd5bb71183532bff220ba46c268991a3ff0blablaxxxxxxxx5fbb
Current Blockchain Status: Syncing 1921089/1927389 (6300 behind).
Peak: Hash: 290dc9ce0ee1060xxxxxxxxxxx7f080c9ca5ad58c3e
      Time: Mon May 02 2022 22:58:25 CEST                  Height:    1921089

Estimated network space: 27.352 EiB
Current difficulty: 2368
Current VDF sub_slot_iters: 136314880
Total iterations since the start of the blockchain: 7590597259947

  Height: |   Hash:
  1921089 | 290dc9ce0ee1060305bb84a11342ec81fddef9dcfda131d7f080c9ca5ad58c3e
  1921088 | bab5fc6dd7e9c62a240e000099bf5b9af583159a3b70ce309b85b9d7e2de6725
  1921087 | 5f8d306dd49da6a0472b0e82ba949cf57f7d05e2ec374c19b6897c3315bc0136
  1921086 | 4e1aaff6e4f2b53e278c003a043181fdf89e0200a8601f6a1e3fd49a4895dfa5
  1921085 | 20274e45535743ae820137303a2d892f89351ef7cb2c9f190018278b16263a21
  1921084 | 63f631ace523165a3f705021d7609bde6ee071f402b4c14eb42e8757f9423b79
  1921083 | 600148d2432664a903c27e4fdf363321636ef0b00da2eec93879df7e8073941c
  1921082 | bb2116f2ee7f73e173d52317335af5c831c9c67e6073b22310af1c0f95503019
  1921081 | d3a69235cf9cf1bced86b02fb770e0d8f40f716b3f41e5156e29f5523deada66
  1921080 | 47d2fddf32ab385b31030b83f0bd998aa154c2673c1ba55e4841a611c2823568

Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
FARMER    127.0.0.1                              43298/8447  ba37bcf4... May 04 07:45:56      0.0|0.0
FULL_NODE 178.136.193.86                          8444/8444  aa5514c9... May 04 07:57:48      0.0|0.0
                                                 -Height:  1642421    -Hash: aa76556d...
FULL_NODE 108.3.171.211                           8444/8444  0c56a050... May 04 07:59:26      0.0|0.0
                                                 -Height:  1918662    -Hash: 68014999...
WALLET    127.0.0.1                              43306/8449  f703a56f... May 04 07:59:37      4.6|0.0
FULL_NODE 72.182.48.232                           8444/8444  a524110b... May 04 07:57:49      0.0|0.0
                                                 -Height:  1912525    -Hash: f80f12b6...
FULL_NODE 124.148.126.139                         8444/8444  2d50c3e8... May 04 07:59:46      0.0|16.4
                                                 -Height:  1927397    -Hash: d2d98193...
FULL_NODE 114.230.222.144                         8444/8444  da48a0a2... May 04 07:57:49      0.0|0.0
                                                 -Height:  1280175    -Hash: f2a6f34a...
FULL_NODE 178.252.115.214                         8444/8444  a7fc8375... May 04 07:59:13      0.0|0.0
                                                 -Height:  1814235    -Hash: 748aef11...

(venv) pi@mcanto:~/.chia/mainnet/log $ chia wallet show
Wallet height: 1927361
Sync status: Syncing...

Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
FULL_NODE 127.0.0.1                               8444/8444  d85ef065... May 04 08:01:09      0.0|5.4
                                                 -Height: No Info    -Hash: No Info    -Trusted: True
FULL_NODE 76.125.165.219                          8444/8444  ad3d4bf6... May 04 08:01:39      0.0|16.4
                                                 -Height: No Info    -Hash: No Info
FULL_NODE 126.28.100.153                          8444/8444  1c0b9ebc... May 04 08:01:39      0.0|3.1
                                                 -Height: No Info    -Hash: No Info
FULL_NODE 109.90.133.209                          8444/8444  cc705a4e... May 04 08:01:39      0.0|2.6
                                                 -Height: No Info    -Hash: No Info
FULL_NODE 98.208.74.114                           8444/8444  71e144ec... May 04 08:01:39      0.0|0.0
                                                 -Height: No Info    -Hash: No Info
```

**Comment by mcanto73** [comment]
I tried another db upgrade, with the chia processes down to free up memory, and it seems db is corrupted

(venv) pi@mcanto:~/chia-blockchain $ chia db upgrade
opening file for reading: /chia_plot6/CHIA/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
opening file for writing: /chia_plot6/CHIA/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
initializing v2 version
initializing v2 block store
peak: 290dc9ce0ee1060305bb84a11342ec81fddef9dcfda131d7f080c9ca5ad58c3e height: 1921089
[1/5] converting full_blocks
   1589000 17.29% 195.5 blocks/s ETA: 8126.0 s    conversion failed with error: database disk image is malformed.
The target v2 database is left in place (possibly in an incomplete state)
  /chia_plot6/CHIA/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
If the failure was caused by a full disk, ensure the volumes of your
temporary- and target directory have sufficient free space.
you can specify the "SQLITE_TMPDIR" environment variable to control the temporary directory to be used


LEAVING PREVIOUS DB FILE UNTOUCHED /chia_plot6/CHIA/.chia/mainnet/db/blockchain_v1_mainnet.sqlite

**Comment by mcanto73** [comment]
2022-05-04T23:02:00.786 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-5601' coro=<FullNode._sync() done, defined at /home/pi/chia-blockchain/chia/full_node/full_node.py:796> exception=ValueError('Header hash b1930f421abc401cfd14646c0faec9443465f9b001405ad2220d41160b15eae0 not in the blockchain')>
Traceback (most recent call last):
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 928, in _sync
    await self._finish_sync()
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 1184, in _finish_sync
    await self.weight_proof_handler.get_proof_of_weight(peak.header_hash)
  File "/home/pi/chia-blockchain/chia/full_node/weight_proof.py", line 89, in get_proof_of_weight
    wp = await self._create_proof_of_weight(tip)
  File "/home/pi/chia-blockchain/chia/full_node/weight_proof.py", line 133, in _create_proof_of_weight
    ses_blocks = await self.blockchain.get_block_records_at(summary_heights)
  File "/home/pi/chia-blockchain/chia/consensus/blockchain.py", line 809, in get_block_records_at
    res = await self.block_store.get_block_records_by_hash(hashes)
  File "/home/pi/chia-blockchain/chia/full_node/block_store.py", line 399, in get_block_records_by_hash
    raise ValueError(f"Header hash {hh} not in the blockchain")
ValueError: Header hash b1930f421abc401cfd14646c0faec9443465f9b001405ad2220d41160b15eae0 not in the blockchain

**Comment by emlowe** [comment]
Your node DB is likely corrupt - you could try `chia db validate` - however this only runs on v2 DB.

**Comment by mcanto73** [comment]
> Your node DB is likely corrupt - you could try `chia db validate` - however this only runs on v2 DB.

Yes, probably is corrupted.
I made a copy of db (renamed) and start sync. It's working but it will take a lot of days on raspberry; is there a way to speed up : using a more powerful pc (not arm)? Isn't there any procedure to repair the dB?
Thanks

**Comment by emlowe** [comment]
No, there is no repair other than download again.

**Comment by mcanto73** [comment]
> No, there is no repair other than download again.

Is there a way to speed up ?
Can I sync in a faster  Linux server and then move   back to arm?

**Comment by emlowe** [comment]
Yes, certainly you can sync the node on any computer and copy the node DB around - however, just make sure you always STOP chia before copying the DB and if there is a WAL file still after stopping the DB, you must also copy the WAL file along with the .sqlite file

**Comment by emlowe** [comment]
Closing issue
