### ISSUE TITLE
[Bug]  new plots are not added 1.3.5.dev93

### ISSUE THREAD

**Issue by grobalt** [Chia-Network/chia-blockchain#11428]
### What happened?

I am on 1.3.5.dev93 as i had issues with a few hunderd disks and response times. New times with ~700 disks are between 3 and 5 seconds, all good.

I use currently these harvester parameter:
  num_threads: 30
  parallel_read: true
  plot_directories:
  - /media/chia01
  - /media/chia02
  - /media/chia03
  - /media/chia04
  - /media/chia05
  - /media/chia06
  - /media/chia07
  - /media/chia08
  - /media/chia09
  - /media/chia10
  - /media/chia11
  - /media/chia12
  - /media/chia13
  - /media/chia14
  - /media/chia15
  - /media/chia16
  plots_refresh_parameter:
    batch_size: 300
    batch_sleep_milliseconds: 1
    interval_seconds: 600
    retry_invalid_seconds: 600

I am still plotting to 3 directories (3 Jbods) but the new plots are not loaded after 24 hours. Am i missing any other setting or went something bad in one of the current dev versions ? Log file does not show any information.

### Version

1.3.5.dev93

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by 0X1231** [comment]
So it seems that the problem of the harvester has not only not been improved, but has also gone backwards.

**Comment by 0X1231** [comment]
The performance of the official harvester is so poor that it is not as good as the tools provided by hpool,flexpool.io.

**Comment by wallentx** [comment]
I'm running a build that has harvester/farmer code that is parallel with what you are running, and I am not having any issues with new plots being detected.
Are you able to provide any debug logs, and are the plots detected after restarting the farmer service?
Have you verified that the newly created plots have been made with the correct key?

**Comment by 0X1231** [comment]
> 我正在运行一个包含与您正在运行的代码平行的收割机/农民代码的构建，并且在检测到新地块时我没有任何问题。 是否可以提供任何调试日志，重新启动农民服务后是否检测到地块？ 您是否验证了新创建的地块是使用正确的密钥制作的？

It is normal to have less than 1 PC,50 block hard drive, but if it is a hard disk with more than 1 PC,50 block, the harvester will not work properly. No power output, query plot time more than 60 seconds. The harvester can't carry any more hard drives. I have 165 hard drives on my pc.

**Comment by 0X1231** [comment]
A single computer has a large number of hard drives, 100 + or even 200 + more, can each instance be responsible for only part of the hard disk, can start a few more harvester programs.
The hpool tool I currently use, a hpool hoe, is responsible for finding 50-60 hard drives.

**Comment by emlowe** [comment]
I recommend trying 1.3.5 as there is an important harvester optimization in there. Note we have tested over 300 disks on a single harvester with various versions and it works quite well.

**Comment by 0X1231** [comment]
> 我建议尝试 1.3.5，因为那里有一个重要的收割机优化。请注意，我们已经在一台不同版本的收割机上测试了 300 多个磁盘，并且运行良好。

请问您是用的Windows GUI，还是linux版本？

**Comment by grobalt** [comment]
> I recommend trying 1.3.5 as there is an important harvester optimization in there. Note we have tested over 300 disks on a single harvester with various versions and it works quite well.

I still have the same issue. The farmer starts, for a few hours everything seems to be okay, then the local plots are all dropped. Will open a new thread soon (after deleting all logs, start from scratch and add this log)
