### ISSUE TITLE
[Bug] Unexplained plots check command not working

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11435]
### What happened?

Executing plots check will not detect any files on disk.
It was normal before.
Is it a problem with the python version?
Python 3.9.7

You might as well give it a try. I found this problem after upgrading 1.3.4, even if I returned 1.3.0.

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to try this with a build from Latest Dev, which uses `Python 3.10` - https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds
The `chia plots check` command is working for me on this build.
Please let us know how your experience is with this.

**Comment by 0X1231** [comment]
> Are you able to try this with a build from Latest Dev, which uses `Python 3.10` - https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds The `chia plots check` command is working for me on this build. Please let us know how your experience is with this.

I just tried it, but it didn't work. It was tested on the Windows10 computer.

**Comment by xdustinface** [comment]
I assume is related to https://github.com/Chia-Network/chia-blockchain/issues/11528 and is not an issue. Feel free to re-open if there is still something wrong.

**Comment by 0X1231** [comment]
> 我认为与#11528有关，不是问题。如果仍然有问题，请随时重新打开。

是的，已经解决了。需要添加目录
