### ISSUE TITLE
Pool payout adress changed

### ISSUE THREAD

**Issue by MaximusChia** [Chia-Network/chia-blockchain#11452]
I recently updated from 1.2.11 to 1.3.4
Did a clean install Deleted DB folders
A new receive payment adress got created, but also affected my pool payout adress. 
I had to change it manually to revert back previous adress.
I know new areceive adress is changed with each updated, but not pool payout adress.

**Comment by DrakeFS** [comment]
Payout addresses (including pools) are only **stored locally** in the config.yaml.  If you have to recreate the config.yaml, then all pool payout addresses will be changed to a new random address from your wallet key.

> I know new areceive adress is changed with each updated, but not pool payout adress.

Unless your config.yaml is renamed or deleted before the update, no addresses should be changing.

Also to note, not all pools use the pool payout address set by the Chia client (like spacepool)

**Comment by emlowe** [comment]
There are several possible payout related addresses  in config.yaml
`farmer:xch_target_address`
`pool:xch_target_address`

There is also the PlotNFT payout address when using a plotnft - this is stored in config.yaml as `payout_instructions` (under `pool:pool_list`) - this is where the Pool will payout to when pooling (is not related to claiming self-pooling rewards)

As DrakeFS says if you delete your config.yaml and resync your wallet, a new payout address may be generated and used as the PlotNFT is synced - however, this payout address will still go to your XCH ("standard") wallet.

Closing issue, as this is working as expected in this case. Will re-open if additional comments indicate some related issue
