### ISSUE TITLE
Debug.log

### ISSUE THREAD

**Issue by OVelihin** [Chia-Network/chia-blockchain#11455]
### What happened?

all time i can see this message. Can some one help?

farmer chia.farmer.farmer : WARNING PUT /farmer response: {'error_code': 16, 'error_message': 'REQUEST_FAILED'}

### Version

Last

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
all time i can see this message. Can some one help?

farmer chia.farmer.farmer : WARNING PUT /farmer response: {'error_code': 16, 'error_message': 'REQUEST_FAILED'}
```

**Comment by loppefaaret** [comment]
It is a command used in the pooling protocol, where the farmer can `PUT` a command or request to the pool - some pools do not support this function.

**Comment by loppefaaret** [comment]
yes, they do not support the `PUT` function.
closing
