### ISSUE TITLE
[Bug] Wallet without credit

### ISSUE THREAD

**Issue by atrinpc** [Chia-Network/chia-blockchain#11462]
### What happened?

Chia wallet balance was zero in an instant without any problems !!!!

And this is not acceptable at all and shows the unreliability of Chia

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
...
```

**Comment by emlowe** [comment]
Your issue can not be addressed as you have provided insufficient details to reproducibility or diagnostics. Closing issue
