### ISSUE TITLE
UI start-up hangs with waiting for Keyring status

### ISSUE THREAD

**Issue by gregallen** [Chia-Network/chia-blockchain#11473]
### What happened?

Seems the daemon fails to start due to its port having been reserved by a Docker Desktop install on Windows 10

However, this bug is about how hard it is for the end user to diagnose this fault and hence how to resolve it

perhaps the daemon port needs to be changed, or at least determined dynamically during install to not be reserved?

Also, just changing the port in config.yaml doesn't fix the UI (although it seemed that it did fix staring from the command line) - perhaps any associated required change in config for the UI could be eliminated or at least better documented?

See also #8022

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-05-09T22:15:14.664 daemon __main__                   : INFO     Starting Daemon Server
2022-05-09T22:15:14.665 daemon __main__                   : INFO     Not implemented
```

**Comment by emlowe** [comment]
There are two places in config.yaml where you need to change daemon_port. The second one is under `ui:daemon_port` - changing both value does work.

Closing issues, as workaround is to use a different port in config.yaml.

Yes, this isn't very user-friendly, but it's also not particularly complex either
