### ISSUE TITLE
[Bug] No keys loaded. Run 'chia keys generate' or import a key

### ISSUE THREAD

**Issue by lidangqi** [Chia-Network/chia-blockchain#11497]
### What happened?

After the wallet has been running for a period of time, 
chia wallet show will prompt 

*****No keys loaded. Run 'chia keys generate' or import a key*****

### Version

1.3.5

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia wallet show
No keys loaded. Run 'chia keys generate' or import a key
```

**Comment by wallentx** [comment]
Possibly related to https://github.com/Chia-Network/chia-blockchain/issues/11175
Need to investigate a bit more.

**Comment by lidangqi** [comment]
> 可能与#11175相关， 需要进一步调查。
Thank you, after adding the -f option, it can be displayed correctly,👍
