### ISSUE TITLE
[Bug] Plots are not been recognize by the Farmer. 

### ISSUE THREAD

**Issue by yoga2005live** [Chia-Network/chia-blockchain#11514]
### What happened?

It was working fine yesterday but now the plots are not been seen by the farmer 
![image](https://user-images.githubusercontent.com/17745923/168309213-2fe4c586-9cdc-4e82-a168-ddb1ef4574bb.png)
![image](https://user-images.githubusercontent.com/17745923/168309285-15093994-f030-4d89-827e-a27f2cacd80e.png)

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by xdustinface** [comment]
Could this just be a typo in your path? In the screenshot it says `FramingFolders`. Maybe it should be `FarmingFolders`?
