### ISSUE TITLE
Can't Claim Pool Rewards [Bug] 

### ISSUE THREAD

**Issue by FVierra27** [Chia-Network/chia-blockchain#11515]
### What happened?

Whenever I do "chia plotnft claim -i *" with the correct ID it gets stuck. When I run the chia wallet get_transaction it says pending. Transactions never show up on chain explorers nothing. Then I have to run chia wallet delete_unconfirmed_transactions in order to try to re-run plotnft claim. I have waited days to see if anything happens and nothing does.

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
You likely need a fee - however, the get stuck part is because of #10873

You should be getting some sort of error report either on the CLI or in the logs that indicate what the problems is. Please include this information

**Comment by FVierra27** [comment]
> You likely need a fee - however, the get stuck part is because of #10873
> 
> You should be getting some sort of error report either on the CLI or in the logs that indicate what the problems is. Please include this information

1. Is there anyway to find out what to use for a "fee"
2.  Where would I find it in the logs?

**Comment by chiavivi** [comment]
一直不能领取奖励，从1.3版本到现在还是不能领取，发了日志还是没有解决方案：2022-05-18T10:04:26.955 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 228, in safe_handle
  File "chia\rpc\rpc_server.py", line 219, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1418, in pw_absorb_rewards
  File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards
ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

**Comment by wallentx** [comment]
Based on your logs, have you tried to delete the unconfirmed transaction first?

**Comment by wallentx** [comment]
> 一直不能领取奖励，从1.3版本到现在还是不能领取，发了日志还是没有解决方案：2022-05-18T10:04:26.955 wallet chia.rpc.rpc_server : WARNING Error while handling message: Traceback (most recent call last): File "chia\rpc\rpc_server.py", line 228, in safe_handle File "chia\rpc\rpc_server.py", line 219, in ws_api File "chia\rpc\wallet_rpc_api.py", line 1418, in pw_absorb_rewards File "chia\pools\pool_wallet.py", line 788, in claim_pool_rewards ValueError: Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.


Based on your logs, have you tried to delete the unconfirmed transaction first?

**Comment by loppefaaret** [comment]
To find your `debug.log` you will have to navigate to your users home folder, and under `~/.chia/mainnet/log/` you will find it.
If you could please attach the log to this issue, we might have a better chance at figuring out what is causing the issue.

**Comment by chiavivi** [comment]
否尝试过很多次，先删除未确认的交易（包括合作社和钱包位置）

**Comment by FVierra27** [comment]
Looks like 1.3.5 fixed my issue. Updated, deleted unconfirmed transactions, tried again, and it looks like it went through.

**Comment by emlowe** [comment]
Closing issue
