### ISSUE TITLE
[Bug] Average space just goes down with no reason after it rebounds - chia-CLI repo version

### ISSUE THREAD

**Issue by jd1900** [Chia-Network/chia-blockchain#11525]
### What happened?

![image](https://user-images.githubusercontent.com/63632981/168411664-50428746-dca1-4b6b-94c5-9e9362cc69fb.png)

![image](https://user-images.githubusercontent.com/63632981/168411712-e22b344b-bc47-4176-b6bc-a201dd1f5e85.png)

I'm having this problem since I updated to latest Ubuntu (22.04 LTS) and changed to repo CLI chia version. I'm in the latest 1.3.5 compatible with Python 3.10. I first though it may be related to not being Python 3.10 compatible when I was in 1.3.4, but after upgrading this still happens. I have 4 farmers and all of them have the same problem after upgrading to Ubuntu and switching from compiled to repo chia-CLI version.

Any idea why is this happening? Or how to fix it?

### Version

1.3.5

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by Motophan** [comment]
Thank you for providing relevant logs.

**Comment by jd1900** [comment]
I had to change Pool to get it working back again
