### ISSUE TITLE
[Bug] Problems that cannot be used by chia plots check

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11528]
### What happened?

Unable to detect any plot in my drive directory.
Chia plots check-g A:\
![image](https://user-images.githubusercontent.com/97425684/168416646-f9d60fe4-1d46-43ee-80cc-7a403674a802.png)

### Version

1.3.6

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by 0X1231** [comment]
why？？

**Comment by shaneo257** [comment]
have you got plots in A:\ drive?

**Comment by 0X1231** [comment]
> 你有 A:\ 驱动器中的情节吗？

yes，

**Comment by 0X1231** [comment]
Is it necessary to log in the private key to use the chia plots check command?

**Comment by xdustinface** [comment]
No but you need to have your plot directories set in the `config.yaml`. Do you even see any plots if you run `chia plots check`  without `-g`?

**Comment by 0X1231** [comment]
> 不，但您需要将绘图目录设置在`config.yaml`. 如果你`chia plots check` 没有运行，你甚至会看到任何情节`-g`吗？

ok i'll test it now

**Comment by 0X1231** [comment]
> 不，但如果你 会看到任何目录没有设置在`config.yaml`。`chia plots check``-g`

Thank you very much for your reply. As you told me how to operate, this command has been successfully executed. Thanks again.
