### ISSUE TITLE
 It is not possible to modify the pool contract [Bug] 

### ISSUE THREAD

**Issue by aart-farmer** [Chia-Network/chia-blockchain#11544]
### What happened?

If you try to change pool or autofarmer, my status stays pending indefinitely.

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
22-05-16T22:04:23.078 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://europe.ecochia.io, Cannot connect to host europe.ecochia.io:443 ssl:<ssl.SSLContext object at 0x000001E375B11540> [getaddrinfo failed]
```

**Comment by wallentx** [comment]
Can you share what command you are trying, and what the output is of that? What is the pool address that you are moving from, and what pool are you moving to? Can you possibly enable log level INFO or DEBUG and try to recreate the error, and share the output?
