### ISSUE TITLE
Transaction fees

### ISSUE THREAD

**Issue by GBourb** [Chia-Network/chia-blockchain#1157]
I send me 3 transactions.

I tried it, hahaha

first one : 30 TXCH with 1TXCF (fee)
Second one : 0.5 TXCH with 2 TXCH (fees)
Third one : 2 with no fees.

I have a question

Are the fees optional ?
or i'm just too soon ?
Do i have to set the fees manualy ? 

Thanks
My first language is not english !

**Comment by hoffmang9** [comment]
Fees are currently optional but must be a number of some sort which includes `0`.

**Comment by GBourb** [comment]
Are the fees going to be distributed to the miners ?

**Comment by hoffmang9** [comment]
Yes - more details -https://www.chia.net/2020/11/10/pools-in-chia.html
