### ISSUE TITLE
Laptop keeps panicking and shutting down in final stages of plotting

### ISSUE THREAD

**Issue by Userdbv** [Chia-Network/chia-blockchain#1158]
Can anyone provide advice as to why the plotting process consistently causes a panic during the final stages of plotting on my mac. Very frustrating after hours of plotting... I'm running an external SSD drive (Samsung-500GB-980-PRO-M-2-NVMe-SSD) and feel like that might be the issue. The report is as follows (thanks for any help):

Panic(CPU 2, time 16830717064801): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff86b98c3290, spinlock owner: 0xffffff86badb5d10, current_thread: 0xffffff86badb5d10, spinlock_owner_cpu: 0x2
RAX: 0xffffff86b6b82360, RBX: 0xffffff936914ef08, RCX: 0x00000000000003ce, RDX: 0x000032d000000000
RSP: 0xffffffb0b2dcbaa0, RBP: 0xffffffb0b2dcbae0, RSI: 0xffffff86badb5d10, RDI: 0xffffff936914ef08
R8:  0xffffffb0b2dcbc60, R9:  0xffffff800f30f110, R10: 0x0000000000ffffff, R11: 0x0000000000000000
R12: 0xffffff86badb5d10, R13: 0x0000000000000000, R14: 0x000032d0ac2ecfc4, R15: 0xffffff86b6b82360
RFL: 0x0000000000000003, RIP: 0xffffff800f2ccb67, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 2), Frame : Return Address
0xffffffa06d920f80 : 0xffffff800f3ed5bb 
0xffffffa06d920fd0 : 0xffffff800f25fbdd 
0xffffffb0b2dcbae0 : 0xffffff800f2ccd04 
0xffffffb0b2dcbb10 : 0xffffff800f30d930 
0xffffffb0b2dcbb30 : 0xffffff800f30f149 
0xffffffb0b2dcbbe0 : 0xffffff800f30f646 
0xffffffb0b2dcbc50 : 0xffffff800f30e694 
0xffffffb0b2dcbd10 : 0xffffff800f3125e8 
0xffffffb0b2dcbd50 : 0xffffff800f823364 
0xffffffb0b2dcbd70 : 0xffffff800f82344e 
0xffffffb0b2dcbdb0 : 0xffffff800f87bfdd 
0xffffffb0b2dcbe30 : 0xffffff800f8774e5 
0xffffffb0b2dcbee0 : 0xffffff800f877311 
0xffffffb0b2dcbf40 : 0xffffff800f9698cb 
0xffffffb0b2dcbfa0 : 0xffffff800f2601f6 

Process name corresponding to current thread: Chia Helper (Renderer)

Mac OS version:
20D80

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x000000000f000000
KernelCache base:  0xffffff800f200000
Kernel slide:      0x000000000f010000
Kernel text base:  0xffffff800f210000
__HIB  text base: 0xffffff800f100000
System model name: MacBookPro13,2 (Mac-66E35819EE2D0D05)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 16830717094136
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000f4eb4e9eb6b
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000001d87ce1be6 0x0000000000000000
last started kext at 216232538000: @filesystems.smbfs	3.4.1 (addr 0xffffff7fb0465000, size 434176)
last stopped kext at 435102761452: >usb.!UHostPacketFilter	1.0 (addr 0xffffff801204f000, size 8192)
loaded kexts:
@filesystems.smbfs	3.4.1
@filesystems.exfat	1.4
>AudioAUUC	1.70
@fileutil	20.036.15
>AGPM	119
>X86PlatformShim	1.0.0
>!APlatformEnabler	2.7.0d0
@filesystems.autofs	3.0
>!AHIDALSService	1
>!AUpstreamUserClient	3.6.8
>!AGraphicsDevicePolicy	6.2.2
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
|IO!BSerialManager	8.0.3d9
>!AHDA	283.15
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!A!ISKLGraphics	16.0.1
>!A!ISKLGraphicsFramebuffer	16.0.1
>!ABacklight	180.3
>!A!IPCHPMC	2.0.1
>eficheck	1
>!A!ISlowAdaptiveClocking	4.0.0
>!AEmbeddedOSSupportHost	1
>!AThunderboltIP	4.0.3
>!AMCCSControl	1.14
>usb.realtek8153patcher	5.0.0
@filesystems.apfs	1677.81.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ATopCaseHIDEventDriver	4030.5
>AirPort.BrcmNIC	1400.1.1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ARTC	2.0
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@kext.triggers	1.0
>!AGraphicsControl	6.2.2
|IOAVB!F	930.1
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
|IO!BHost!CUARTTransport	8.0.3d9
|IO!BHost!CTransport	8.0.3d9
|IOAccelerator!F2	439.52
>!ABacklightExpert	1.1.0
|IONDRVSupport	585
@!AGPUWrangler	6.2.2
@!AGraphicsDeviceControl	6.2.2
|IOSlowAdaptiveClocking!F	1.0.0
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
|IOSerial!F	11
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
|IOGraphics!F	585
>!ASMBus!C	1.0.18d1
>usb.cdc.ncm	5.0.0
>usb.!UiBridge	1.0
>usb.!UHub	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AThunderboltPCIDownAdapter	4.1.1
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
>!AActuatorDriver	4400.28
>!AHIDKeyboard	223
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
>!AHS!BDriver	4030.5
>IO!BHIDDriver	8.0.3d9
>!AHSSPIHIDDriver	61
>!AHSSPISupport	61
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>!A!ILpssSpi!C	3.0.60
>!A!ILpssDmac	3.0.60
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IONVMe!F	2.1.0
|IOUSB!F	900.4.2
>!A!ILpssI2C	3.0.60
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.3d9
|IOReport!F	47
|IO!BPacketLogger	8.0.3d9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1
panic(cpu 0 caller 0xffffff800f3e2960): "Spinlock acquisition timed out: lock=0xffffff86b98c3290, lock owner thread=0xffffff86badb5d10, current_thread: 0xffffff86b6b82360, lock owner active on CPU 0x2, current owner: 0xffffff86badb5d10, time: 16830717115075"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.81.3/osfmk/i386/locks_i386.c:505
Backtrace (CPU 0), Frame : Return Address
0xffffffa04d583ab0 : 0xffffff800f2bab4d 
0xffffffa04d583b00 : 0xffffff800f3fd7e3 
0xffffffa04d583b40 : 0xffffff800f3ede1a 
0xffffffa04d583b90 : 0xffffff800f25fa2f 
0xffffffa04d583bb0 : 0xffffff800f2ba3ed 
0xffffffa04d583cd0 : 0xffffff800f2ba6d8 
0xffffffa04d583d40 : 0xffffff800fabef9a 
0xffffffa04d583db0 : 0xffffff800f3e2960 
0xffffffa04d583df0 : 0xffffff800f2db0fa 
0xffffffa04d583e30 : 0xffffff800f2db01c 
0xffffffa04d583e60 : 0xffffff800f308d7b 
0xffffffa04d583f20 : 0xffffff800f3d98b3 
0xffffffa04d583f60 : 0xffffff800f3f6eaa 
0xffffffa04d583f80 : 0xffffff800f3ed5bb 
0xffffffa04d583fd0 : 0xffffff800f25fbdd 
0xffffffb0b30f3db0 : 0xffffff800f3123d1 
0xffffffb0b30f3e10 : 0xffffff800f8795e9 
0xffffffb0b30f3f00 : 0xffffff800f878716 
0xffffffb0b30f3f40 : 0xffffff800f9698cb 
0xffffffb0b30f3fa0 : 0xffffff800f2601f6 

Process name corresponding to current thread: Chia Helper (Renderer)

**Comment by hoffmang9** [comment]
This crashed in your filesystem drivers. Is it possible your external SSD is overheating?

**Comment by mcmar47** [comment]
I've had a very similar issue, 3 separate kernel panics across 4 days of time with the same root process showing in my logs upon reboot (Chia Helper (Renderer)).
