### ISSUE TITLE
Plot Count wrong in GUI [Bug] 

### ISSUE THREAD

**Issue by wmahler** [Chia-Network/chia-blockchain#11581]
### What happened?

Since my Upgrade to 1.3.5 the remote harvester shows zero plots, it should be 936.
![chia_bug1](https://user-images.githubusercontent.com/50576070/169476737-48158948-d873-4ba9-8860-180e9059cf5b.PNG)
 
The farming works fine, even Pool shows everything is working as intended. It's just a display bug in the GUI.
![chia_bug2](https://user-images.githubusercontent.com/50576070/169476912-25aba4da-c5f5-45db-b0de-d381768308e2.PNG)

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Your harvester is also running 1.3.5 correct?
Is there anything noteworthy in either the harvester log or the farmer log?

**Comment by xdustinface** [comment]
Also, if you know how to run the CLI (not sure if this is common thing in Windows), what does running `chia farm summary` show?

**Comment by moxuec** [comment]
I have the same situation, windows fullnode version 1.3.5, linux harvester version1.3.2.Actually the harvester works

**Comment by xdustinface** [comment]
@moxuec You need to upgrade the harvester. A harvester running a version <1.3.4 is not compatible anymore with a farmer on version 1.3.5. Harvesting plots does still work while plot reporting on the farmer and in the GUI will not work.
