### ISSUE TITLE
[Bug] Timeout doesn't recover.  Requires full restart.

### ISSUE THREAD

**Issue by jacoblroberts** [Chia-Network/chia-blockchain#11584]
### What happened?

Randomly there will be a timeout issue.  It will show in the 'Connection Status' in the 'Full Node' tab, Error with an info icon that says there was a timeout after 600 seconds.  The only way to recover from this is to restart completely.  The GUI hangs with shutting down as it can't stop all services.  If I force close it and try to restart the GUI, it will not connect or it will connect but not show the key to select.  It gives options to add a new key or import.  Once I fully reboot, all is well.  

This has happened on both of my Ubunut machines (OG and Pooling), multiple times.

### Version

1.3.2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Can you try this with 1.3.5? If you are still having problems, are you able to provide us with logs?
