### ISSUE TITLE
[Bug] NFT0 - assets that exceed 10mb should allow the user to click to load/view the content in the GUI

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#11666]
### What happened?

Currently if the file size is > 10mb, we show an error. Instead we should provide a link for the user to click on that enable the user to view the asset
![Screen Shot 2022-05-27 at 9 47 54 AM](https://user-images.githubusercontent.com/93196638/170723312-77ca00e0-929d-4b13-82cb-a91c11d478eb.png)
.

### Version

1.3.6. dev386

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
@sethjenks @seeden @paninaro

with current build - 1.3.6 dev686 on mac m1

![Image](https://user-images.githubusercontent.com/93196638/174941800-4fb30dd9-8819-4cea-9a08-d00921d960a1.png)

we'd want to update the content here to say: "File is over 10mb" with the show preview button.

on viewing the details of the NFT:
same content update
![Image](https://user-images.githubusercontent.com/93196638/174942100-53eefdfc-5ac7-44c1-83c0-c361a2376ce5.png)

after clicking on the image on the NFT details screen, there's an error that pops but hard to read:

![Image](https://user-images.githubusercontent.com/93196638/174942429-9179511b-c303-41b4-94d4-2d8b1619bae8.png)

we should allow the user view a larger version of the image instead of returning an error that can't be read.

**Comment by seeden** [comment]
Fix was already pushed
