### ISSUE TITLE
Syncing 0/36565

### ISSUE THREAD

**Issue by IssaEgvi** [Chia-Network/chia-blockchain#1166]
Installed the new 0.2.5 just now, Syncing is at 0/0 instead of 0/36565
Didn't try anything to solve it, waiting for instructions here. 
Successfully generated a Plot but it won't sync either.

OS: Windows 10 Pro 1909
CPU: Ryzen 5 3600

**Comment by mariano54** [comment]
Did you restart the application?  Do you have any full node connections?
