### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChrisMarshallasdfasdfasdffsadf** [Chia-Network/chia-blockchain#1167]
**Describe the bug**
Syncing currently takes longer than 120 hours on a fast computer with fast wifi

**To Reproduce**
I tried on two different computers - same issues.

**Expected behavior**
I expected it to complete within a day or two

**Screenshots**

**Desktop (please complete the following information):**
windows
- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by mariano54** [comment]
Try installing the new version rc5

**Comment by ChrisMarshallasdfasdfasdffsadf** [comment]
Ok, thanks. Doing it now.
