### ISSUE TITLE
[Bug] NFT0 - can't mint with CLI command

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#11682]
### What happened?

esaung@Chia-Macbook daemon % ./chia wallet nft mint -i 2 -aa txch138wgdml3nlld4vshlv95xr0x79m52wfeka7kzx8z3yt73y8et80sjk7rc8 -nh 149ff43613eea7d5a6716b98ffab7750c0f3c014de5a5726e50b82d7876bafee -u "https://ipfs.io/ipfs/QmaPR8EBY6Ccurttw5rs3Y5LsKDpTV6sLm46dnMwzr8oRL"
Wallet keys:
3)   *******0625 (Synced)
4)   *************
5)   ************
Choose a wallet key [1-5] ('q' to quit, or Enter to use 3871580625): 3
Failed to mint NFT: {'error': 'Metadata URIs must be a list', 'success': False}
esaung@Chia-Macbook daemon % 

### Version

1.3.6 dev386

### What platform are you using?

macOS

### What ui mode are you using?

CLI

**Comment by AmineKhaldi** [comment]
PR #11748 landed to adapt to the recent RPC changes. Please also note while retesting that `-aa` flag doesn't exist anymore. The RPC has royalty address and target address, so the CLI introduced `-ra` and `-ta` flags accordingly.

**Comment by trepca** [comment]
@esaung can you try again?

**Comment by esaung** [comment]
cli commands are working with the latest build 1.3.6 dev659
