### ISSUE TITLE
[Bug] NFT0 - infinite loading spinner on NFT images

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#11681]
### What happened?

The gui seems to refresh and gets stuck where it shows a "loading preview" with the spinner, but never actually loads the image.
Clicking into an individual image, and then coming back fixes the issue.
![Screen Shot 2022-05-27 at 11 52 22 AM](https://user-images.githubusercontent.com/93196638/170795521-c5ea25d0-ea43-499d-b618-994ae65aac1b.png)

### Version

1.3.6 dev386

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@seeden did you have an idea of what causes this?

**Comment by seeden** [comment]
iframe onLoad is not firing sometimes. I need to figure out when
