### ISSUE TITLE
1.2.11 shows I have 42 xchs, 1.3.5 shows I have 6. I can no longer see all xch in 1.3.5[Bug] 

### ISSUE THREAD

**Issue by zhangyongchang88** [Chia-Network/chia-blockchain#11689]
### What happened?

1.2.11显示我有42个xch，1.3.5显示我有6个。我无法再1.3.5看到所有xch
我的收割机和全节点版本为1.2.11，另一台机器安装了1.3.5的最新版本。xch数量不一致
并且我实际已经挖了1000多枚xch了，但1.3.5版本中收割机状态只显示出我挖了800多枚
我每隔一定周期会把挖出的xch转移到另一台安全电脑中，前几天电脑重启了安全电脑，xch数量从1007变为999xch，丢失了8个硬币，钱包交易记录上显示不出来这笔收款 高度1969337 收款地址 xch1743ptq6aqdsym5zkgnv8nx5fah2k6qzxuhh3pm4sltkuyqwtlgesa06san，而我单独又测试发送了0.001是没有问题的，不论我如何操作重新启动，重新安装，这8个xch都无法找回。

1.2.11 shows I have 42 xchs, 1.3.5 shows I have 6. I can no longer see all xch in 1.3.5
My harvester and full node version is 1.2.11 and another machine has the latest version of 1.3.5 installed. Inconsistent number of xch
And I have actually dug more than 1000 xch, but the harvester status in version 1.3.5 only shows that I have dug more than 800
I will transfer the mined xch to another security computer at regular intervals. The computer restarted the security computer a few days ago, the number of xch has changed from 1007 to 999xch, 8 coins have been lost, and the wallet transaction record cannot be displayed. This payment height is 1969337 and the payment address is xch1743ptq6aqdsym5zkgnv8nx5fah2k6qzxuhh3pm4sltkuyqwtlgesa06san, And I have tested and sent 0.001 separately, there is no problem, no matter how I restart, reinstall, these 8 xch can't be retrieved.

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by zhangyongchang88** [comment]
![image](https://user-images.githubusercontent.com/70252155/170836291-75ea64ac-661e-4745-86e7-b7e0d7d0f5a0.png)
![image](https://user-images.githubusercontent.com/70252155/170836318-7541b600-9996-4e00-ad7e-acaa476d44d8.png)

**Comment by zhangyongchang88** [comment]
#10866 #11688

**Comment by mariano54** [comment]
Can you wait a few hours, and then report the new balance?

**Comment by mariano54** [comment]
Also, please delete the Wallet DB and resync. Does it result in the same balance?

**Comment by wjblanke** [comment]
Yes, the above is good advice. ALSO! Before doing all this, please set logging to INFO in config.yaml and send us the logs.

**Comment by zhangyongchang88** [comment]
> 你能等几个小时，然后报告新的余额吗？

我等了一天了余额也不对，我今天爆了一个1.2.11块显示44个xch 1.3.5显示8个xch
![image](https://user-images.githubusercontent.com/70252155/170848830-4d9824d3-f1fc-4c73-aa16-26a2278b78c8.png)
![image](https://user-images.githubusercontent.com/70252155/170848838-7159b448-ea62-4a38-b921-282dbcce469e.png)

**Comment by zhangyongchang88** [comment]
> 会导致相同

你让我删除什么db文件？1.3.5我是全新安装的也需要删除吗？

**Comment by shaneo257** [comment]
close the client, then located the wallet db, located at C:\Users\<yourusername>\.chia\mainnet\wallet\db and delete those files

**Comment by nqzhang** [comment]
一年多了 钱包同步还是这个鸟样 真是服
一直同步 一直同步
![image](https://user-images.githubusercontent.com/12559853/170866427-fc239cae-8e59-48ca-b928-a47b353faaaf.png)

**Comment by luis360** [comment]
I also encountered the same problem. After the upgrade, my balance became less. I deleted the wallet/db and resynchronized, but the synchronization was very slow. Is there a faster synchronization method?

**Comment by luis360** [comment]
oh my god,this is really a regrettable project. let me know if you sync

**Comment by zhangyongchang88** [comment]
![image](https://user-images.githubusercontent.com/70252155/171452830-5d22c89d-da9e-474b-8414-b013031ec8f8.png)
![image](https://user-images.githubusercontent.com/70252155/171452888-a3cf8d5b-881a-42ac-a04b-d6f8daa6076c.png)

**Comment by luis360** [comment]
If you solve it please let me know how you solved it. thanks you

**Comment by 1-justinstarr** [comment]
Hello. I have been having some major issues for a long time. I keep seeing information that says I have a lot of crypto that I cannot seem to find. Someone leading me around I believe. Can’t update windows or access other features at times. Network trouble now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhangyongchang88** [comment]
> 如果你解决了，请告诉我你是如何解决的。谢谢你

如果你解决了也请告诉我。

**Comment by zhangyongchang88** [comment]
> If you solve it please let me know how you solved it. thank you

hi，我再全新安装以后，售沙尘暴影响的钱包同步等待了大约3-4天，最终硬币数量正常了。另一个丢失8xch的安全钱包再全新安装后大约半天正常了。期间我使用1.2.11使用安全钱包的密匙同步，同步完成后余额几乎为0，我不清楚为什么，如果谁知道希望科普一下原因。

**Comment by mikeowoo** [comment]
> > If you solve it please let me know how you solved it. thank you
> 
> hi，我再全新安装以后，售沙尘暴影响的钱包同步等待了大约3-4天，最终硬币数量正常了。另一个丢失8xch的安全钱包再全新安装后大约半天正常了。期间我使用1.2.11使用安全钱包的密匙同步，同步完成后余额几乎为0，我不清楚为什么，如果谁知道希望科普一下原因。

我也遇到同样问题。同步好几天，最后只显示一半的币。是不是换个电脑，单独搞个钱包能正常啊？还是老哥说的沙尘暴是个什么东西，好久没关注了

**Comment by zhangyongchang88** [comment]
> 

安装1.5.0应该可以得到解决

**Comment by emlowe** [comment]
Closing issue - please add additional comments if problems occur in newer versions. In particular dusty wallets likely benefit from the dust filtering features. For very large wallets we recommend running a local node and not wallet-only moe
