### ISSUE TITLE
[Bug] C:\Users\cxm98\.chia 可以删除吗？

### ISSUE THREAD

**Issue by cxm9874123** [Chia-Network/chia-blockchain#11698]
### What happened?

https://tiebapic.baidu.com/forum/w%3D580%3B/sign=a41f7d35e6cc7cd9fa2d34d1093a233f/5fdf8db1cb13495401938ebc134e9258d0094a5c.jpg?tbpicau=2022-05-31-05_4ca9b9536b7e1aa1e63b8b8f9e432143

如图，可以删除吗？
文件越来越大了

或者可以设定指定到其他盘位置里吗？

### Version

ChiaSetup-1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by delgh1** [comment]
答案：不能
解释：`~/.chia`文件夹包含整个区块链的数据库及你的钱包（所以很大）
区块链数据库文件可以指定到别的路径。
修改`~/.chia/config/config.yaml`，`full_node:`小节下的`database_path: db/blockchain_v1_CHALLENGE.sqlite`，改成移动后的路径。
如果满意这个回答，记得按下方按钮关闭这个帖子。

A rough translation:
"Can I delete this folder C:\Users\*\.chia ?"
Short answer: No.
Long answer: it contains the whole blockchain data and your wallet, the size is big, but no.
the db path can be changed.
Update `~/.chia/config/config.yaml`, under section `full_node:`, change `database_path: db/blockchain_v1_CHALLENGE.sqlite`
If you are satisfied with this answer please remember to close this ticket blahblahblah.

[What is the new database?](https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-new-database)

**Comment by jacoblmyplus** [comment]
你好，问题解决了吗？我也碰到了一样的问题c盘满了，我想把数据库文件搬到别的盘有没有办法结局
