### ISSUE TITLE
Lost Chia

### ISSUE THREAD

**Issue by mjdegen** [Chia-Network/chia-blockchain#11691]
### What happened?

Lost one of my xch transactions from the pool server. The pool says I have 3 transactions. Chia 1.35 GUI for Mac says I only have 2 transactions. This means I lost some chia?

### Version

1.35

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by zhangyongchang88** [comment]
新版本查找硬币功能有问题，我和你有同样的毛病。
