### ISSUE TITLE
[Bug] My node has been unable to catch up with the latest height, it has been about 10 days.

### ISSUE THREAD

**Issue by luis360** [Chia-Network/chia-blockchain#11692]
### What happened?

my node has been unable to catch up with the latest height, it has been about 10 days.
It takes a long time to sync some blocks, but then goes out of sync for a long time.
before I found out that the wallet has a lot of dust transactions, is there any effect on this, and how can I reject these dust transactions, so that my nodes can synchronize to the latest height faster

sync logs：
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/38502473/170850274-09c9dfa9-da93-4cc1-8874-dd5fa4535b39.png">

### Version

1.3.5

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
Are you able to try to run with a synced local full node, and also set `connect_to_unknown_peers: false` in your config.yaml, and let us know if this resolves the issue?

**Comment by 0X1231** [comment]
希望官方尽快更新最低手续费机制，以防止沙尘造成的危害。

**Comment by emlowe** [comment]
Closing due to lack of response
