### ISSUE TITLE
[Bug] 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by SplitMilky** [Chia-Network/chia-blockchain#11700]
Windows 11
![image](https://user-images.githubusercontent.com/81430176/170866464-b7777cc7-ef7b-437c-94e2-d31ba22438b4.png)

Related #9513
Closed CHIA client as the GUI was all white and blank. When the close window popped up it was also empty. I waited for it to do it's thing but it never disappeared so I eventually closed it manually.

After starting CHIA up and entered my keyring password I had no option to load my key, only to create a new key or enter my mnemonic.

I enter my mnemonic and this is when I received the subject popup, and my key has not imported.

![image](https://user-images.githubusercontent.com/81430176/170866432-201fa7ec-9e25-483d-b485-51d6764edd16.png)

**Comment by wallentx** [comment]
This is a [known issue](https://github.com/Chia-Network/chia-blockchain/issues/11175) that we are trying to track down, but are having a hard time reproducing. If you reboot your machine, all of your keys will show as they should. If you experience this again, and you have logs that you can share, we would appreciate it.
