### ISSUE TITLE
[Bug] macOS Mojave 10.14.6 - "Loading configuration"

### ISSUE THREAD

**Issue by DonSchnipsel** [Chia-Network/chia-blockchain#11702]
### What happened?

Chia GUI is running but only showing "Loading configuration" (see attachment).

Thank you for your help
![Bildschirmfoto 2022-05-29 um 16 49 53](https://user-images.githubusercontent.com/106480571/170875642-58bba1ae-5212-4c4a-819c-62d732b71cf2.png)
!

### Version

1.3.5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by DonSchnipsel** [comment]
Thats fixed :)
I did the following:

I copied the "Contents" folder from my other Mac where the Chia GUI was running without problems (from here: /Applications/Chia.app/Contents) and replaced it with the same folder and same location at the other Mac (where the GUI was stuck at "Loading configuration").

When I tried to start the GUI again, it got stuck at "loading keyring status".

I found the solution in this post: https://github.com/Chia-Network/chia-blockchain/issues/10687
(brew and python needs to be installed to do the following)

> are you comfortable with git cloning the `chia-blockchain` repository and trying to update the keyrings module version? I'd be curious to know if editing `setup.py` and changing `"keyring==23.0.1"` to `"keyring==23.1.0"` fixes things.
> 
> `git clone git@github.com:Chia-Network/chia-blockchain.git`
> `cd chia-blockchain`
> 
> (edit setup.py changing "keyring==23.0.1" to "keyring==23.1.0")
> `sh install.sh`
> `. ./activate`
> `chia run_daemon`

GUI running as normal again. Not sure if this is a installer bug or just my old Mac running Mojave ^^

**Comment by DonSchnipsel** [comment]
I need to leave the terminal open otherwise the GUI loses connection to daemon...

Maybe someone knows how to fix this, that I am able to use the GUI only?

**Comment by wallentx** [comment]
You are running 2 separate Chia installs as-is, which is not what you would want to do. I would suggest rebooting, downloading and installing this Mojave build, https://download.chia.net/install/Chia-1.3.5-10.14-intel.dmg and ONLY running Chia from this install.
