### ISSUE TITLE
May need another term for "Chain info"- i.e. "On-chain Data/Info"

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#11737]
May need  another term for this, like "On-chain Data/Info"

_Originally posted by @ytx1991 in https://github.com/Chia-Network/chia-blockchain/pull/11653#discussion_r883709677_

**Comment by Drhicom** [comment]
When will 1.4.0 be released? And I hope the displaying of plots has been fixed since the last 6 beta's,,Thank you for your hard work.

Roy
