### ISSUE TITLE
[Bug] DB Upgrade in Windows

### ISSUE THREAD

**Issue by jm-XCHcentral** [Chia-Network/chia-blockchain#11743]
### What happened?

Attempted to upgrade v1 DB in Windows.

Using command: C:\Users\user\AppData\Local\chia-blockchain\app-1.3.5\resources\app.asar.unpacked\daemon>chia db upgrade

Error returned was - FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\user\\.chia\\mainnet\\db\\blockchain_v2_mainnet.sqlite'

Client should not have returned this error... as it should be creating the v2 database.

Worked around it by using the input option C:\Users\user\AppData\Local\chia-blockchain\app-1.3.5\resources\app.asar.unpacked\daemon>chia db upgrade --input C:\Users\user\.chia\mainnet\db\blockchain_v1_mainnet.sqlite

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
When you ran `chia db upgrade`, did your config.yaml already have have pointers to the blockchain_v2_mainnet.sqlite db?
