### ISSUE TITLE
[Bug] Mint NFT throws double spend log message

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#11741]
### What happened?

Used this RPC to mint NFT:

paulhainsworth@Pauls-MacBook-Air ~ % chia rpc wallet nft_mint_nft '{"wallet_id": 2, "uris": ["https://live.staticflickr.com/3077/3158078382_a6304b8444_h.jpg"], "hash": "92a80905f7f0cc203fb534038d8cc3f0f019064d9870cacbea2416bd19ff316f", "artist_percentage": 1500, "artist_address": "txch1vtxfjqyfwdutcamh7j9wr0gz65uxgf90wut0reuekewwkuxuzefsr6f9sf"}'

Outcome in log:

2022-06-01T18:07:57.824 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x2ed87260ef5e4e47bbe32e5a9f547ddbd7b5e690e0c9b6472ad6c2cd27745e15'}

### Version

1.3.6dev386

### What platform are you using?

macOS

### What ui mode are you using?

CLI

**Comment by pmaslana** [comment]
This might be related to the MEMPOOL_CONFLICT errors that I receive when trying to mint multiple NFTs too quickly and the parent coin ID is being used for the other transactions. How quickly after minting an NFT did you receive the error for the subsequent mint?

**Comment by pmaslana** [comment]
I still receive this error when trying to mint before the transaction is processed.

**Comment by pmaslana** [comment]
@
