### ISSUE TITLE
[Bug] (NFT) Wallet should prevent transfer w/insufficient fee funds

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#11742]
### What happened?

Start with 0 txch in wallet.
Transfer NFT to a txch address, include a network fee.

This should fail, but the transfer is initiated.
The NFT does eventually transfer successfully without using a fee.

### Version

1.3.6.dev371

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by trepca** [comment]
We've changed transfer functionality recently, can you try again?

**Comment by danieljperry** [comment]
I just tried on 1.3.6.dev581 (from the release/1_4_0 branch, cloned a few hours ago) and the transfer still went through with a fee, from a wallet with no money. So it doesn't appear to be fixed in this code.

**Comment by danieljperry** [comment]
This is still failing (NFT transfers without actually charging a fee) as of 1.3.6.667. However, it is likely a dup of this bug, which affects fees more generally:
https://github.com/Chia-Network/chia-blockchain/issues/11951
