### ISSUE TITLE
[BUG] Network not launched yet, waiting for Genesis Challenge. 

### ISSUE THREAD

**Issue by Werdnad** [Chia-Network/chia-blockchain#1175]
When loading chia gui this message is displayed in RC5: 

Network not launched yet, waiting for Genesis Challenge! 

If I try and close the Gui it displays Closing doen node and Server, and doesn't close.

![image](https://user-images.githubusercontent.com/80155873/110205248-e6495500-7e6e-11eb-8d67-62f9663ee7b9.png)

-Windows 10 

Have tried restarting computer, reinstalling chia, deleting all chia related files in app-data, and clearing registry.

**Comment by Badt-AFFKT** [comment]
synchronization works intermittently (

**Comment by hoffmang9** [comment]
There are new and different bugs in RC6.
