### ISSUE TITLE
[Bug] Processing the same signage point multiple times

### ISSUE THREAD

**Issue by Jacek-ghub** [Chia-Network/chia-blockchain#11757]
### What happened?

From time to time my logs show that the node processed the same signage point, e.g.,:
```
2022-06-01T23:17:09.473 full_node chia.full_node.full_node: INFO       Finished signage point 39/64: CC: 609df8fce29565da1ccbb7257669d09a49b5e0a8bd76532126677fb3e21fc726 RC: 384b2bdf32ca312ddcf773d754206a5644ff4df68891333be039af73dfd6e94d
2022-06-01T23:17:09.489 full_node chia.full_node.full_node: INFO       Finished signage point 39/64: CC: 609df8fce29565da1ccbb7257669d09a49b5e0a8bd76532126677fb3e21fc726 RC: 384b2bdf32ca312ddcf773d754206a5644ff4df68891333be039af73dfd6e94d
```

Should those multiple processing of the same thing be suppressed by the node?

Are those duplicate signage points due to some peers sending the same info, as such rather node specific (as such, the node not filtering those dups).

Or rather the network decided that there was some change in a given signage point, and every node on the network needs to reprocess it?  If this is the case, can the protocol be a bit extended to add a version to the signage point (so, the second time it needs to be processed, it will be ...:v2 mark on that signage point).

The problem with those dups comes mostly from pools marking those as potential duplicate plots on the farm, thus triggering people to constantly search for duplicate plots.

### Version
1.3.5

### What platform are you using?
Windows

### What ui mode are you using?
GUI

**Comment by william-gr** [comment]
Would appreciate some insight here. On the pool side as he mentions it can be quite annoying.
We do not want to ignore double signage points partials because there is a chance they are real, like duplicated plots.

**Comment by Jacek-ghub** [comment]
If we assume that (some of) those duplicates represent duplicate plots, isn't this the internal problem for the farmer, not really an error that should be propagated to the network (to the pool)?  As such, this should be addressed as an additional bug (unrelated to duplicates coming from the network).

Having the node at least flag those dups with ERROR level, and identifying which was the offending plot would be a great improvement already.
