### ISSUE TITLE
[Bug] NFT Wallet takes a very long time to update transaction after minting an NFT and do not show it pending

### ISSUE THREAD

**Issue by pmaslana** [Chia-Network/chia-blockchain#11761]
### What happened?

The list of transaction history in the GUI and from the CLI are extremely slow to show the latest transactions when minting NFTs. It did not update until the next day and after I restarted all services. However, I did try restarting all services after I minted and waited about 30 mins. The transactions are not showing up for that wallet, with and without a full synced.

The NFT does show up in my wallet and the expected coins being removed and added back to the wallet (Parent coin value - 1 mojo) are displayed in the logs.

### Version

1.3.6412

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by trepca** [comment]
were you using fees when minting?

**Comment by pmaslana** [comment]
The transactions appear to be posting

**Comment by pmaslana** [comment]
The transactions appear to be showing up properly now
