### ISSUE TITLE
Farmer not displaying Harvester Plots 

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/chia-blockchain#11800]
Good afternoon,   Farmer using release 1.3.6551 in the Plots tab not showing the harvester plots. The total Plot Count in the Farmer tab is correct, you just can't view the plots in the Plots Tab from any Harvester.

**Comment by ciciban74** [comment]
How did you solve the problem? It's the same with me. Yesterday, after the update to 1.3.5 Harvester does not show in Farming "Plots passed filter" although it shows all the plots in "Farming Menager" (local and remote). I don't know what to do.
