### ISSUE TITLE
После перезагрузке клиента пропали монеты XCH[Bug] 

### ISSUE THREAD

**Issue by sinkler999** [Chia-Network/chia-blockchain#11827]
### What happened?

Мне нужно было перезагрузить компьютер, после перезагрузке я снова зашел в программу для майнинг Chia и не обнаружил ранее пойманые блоки и свои монеты. 

вот мой кошелек  xch1y43z8tnddmvdhq57z2ec2aujt4n3ckp7m3h50n4yj2t89jzjhm4qr4qd8p  на него 05.06.2022 был пойман блок. но сейчас его нет. 
![Screenshot_3](https://user-images.githubusercontent.com/107115739/172605203-e20007e4-4b70-4ce9-a9bc-d793d7437ff6.png)

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by zhangyongchang88** [comment]
你好，删除钱包的DB文件，并重新运行等待同步完成，或者全新安装。我就是这么解决的

**Comment by lqpl38** [comment]
Такая же проблема, выключил включил пропали монеты. Получилось как-нибудь решить?
