### ISSUE TITLE
Plots from remote harvesters NOT included on the log and plots counts.

### ISSUE THREAD

**Issue by rkandel** [Chia-Network/chia-blockchain#11825]
The plots from remote harvesters are not added up on the farming machine (full node). In addition, they are not displayed on the log file either. However, looking at the challenges log list on the main node, they are listed in recent transactions list.

How do I verify these plots from remote machines are ACTUALLY farming?

![Chia Farming](https://user-images.githubusercontent.com/6655937/172580636-61e0fb4a-1e80-49ff-828b-54383494bb1d.png)

**Comment by wallentx** [comment]
Can you provide a few more details about your setup?
What version are you running?
What OS?
How many systems are in your farm setup?
If remote harvesters, how many remote harvesters, and how many plots per harvester?
How many total plots do you have?

If you have any logs, providing those may be useful as well.

**Comment by rkandel** [comment]
Hi William,

Thank you for your email.

I am running the latest Chia GUI on Windows 10 and 11. There is one Full
Node (Farmer) and two harvesters. For the number of plots, please refer to
the original screenshot I uploaded. The full node has just over 1200 plots,
one of the harvesters has 800+ plots and the other one has under 200 plots.

Just like on the GUI (refer to the screenshot),  the logs shows the
attempts from the full node but not the harvesters.

Regards,
Rishi Kandel

*Disclaimer*
This email message and its attachments may contain personal or confidential
information. It is intended for the named addressee only. If you are not
the intended recipient, you must not use or disclose this message or its
attachments (including by saving, copying or delivering the information to
anyone else). Instead, we ask that you immediately notify the sender by
reply email and then permanently delete both messages and any attachments
from your system.  You should not rely on this email as containing any
commitment or consensus by the sender or a group, unless specifically
indicated otherwise. The opinions and views expressed in this communication
are solely the personal expression by the sender and does not represent any
organisational or institutional views unless otherwise endorsed by any
organisation.
