### ISSUE TITLE
Comment doesn't match code

### ISSUE THREAD

**Issue by geraldneale** [Chia-Network/chia-blockchain#11824]
https://github.com/Chia-Network/chia-blockchain/blob/e6290b840728d8582901086c5f19ffdc53a2a4d0/chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py#L70
DEFAULT_HIDDEN_PUZZLE = Program.from_bytes(bytes.fromhex("ff0980"))
DEFAULT_HIDDEN_PUZZLE_HASH = DEFAULT_HIDDEN_PUZZLE.get_tree_hash()  # this puzzle `(x)` always fails

ff0980 is NOT the puzzle (x), but rather (=)

Perhaps the comment should read "this puzzle is `(=)`" or maybe just remove the comment altogether. I seem to recall that there was once a time when it was (x), but I believe it's been (=) for awhile.  As-is it's misleading at important juncture in understanding how the standard transaction works with chialisp.

**Comment by trepca** [comment]
@geraldneale good catch, do you want to make a PR for this?
