### ISSUE TITLE
[BUG] Expected time to win inaccuracy

### ISSUE THREAD

**Issue by GeorgePapageorgakis** [Chia-Network/chia-blockchain#1184]
I am more than a week now with Expected time to win in 2 days. However I dont see any challenges solved and haven't farmed any coins. Is it something that i am missing here?

Note: actually i havent farmed any coins at all... I am farming from 25th of February...

- OS: Windows 10
- CPU: Intel i7 6700K
- 16GB RAM
- Chia Network version 1.0 RC5

**Comment by hoffmang9** [comment]
It is likely that your txch receive address in config.yaml is wrong. Take one from your wallet and update both entries.

**Comment by GeorgePapageorgakis** [comment]
Could you please be more specific? I dont see any "address" field in the initial-config.yaml.
Is the file name "initial-config.yaml" correct?

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/blob/main/src/util/initial-config.yaml#L91 is one of the two entries.

Your config.yaml is in `~/.chia/1.0rc5/conf/`

**Comment by GeorgePapageorgakis** [comment]
I am running windows 10 not linux :o
I dont see any other config file or folder...

**Comment by hoffmang9** [comment]
`~` is short for C:\Users\yourusername\.chia` and will literally work if you type `cd ~\.chia`

**Comment by GeorgePapageorgakis** [comment]
ok I have changed the 
`xch_target_address`
to my address. Lets see if it works :)
