### ISSUE TITLE
Chia blocks misplaced/pool activity - went solo, yet block rewards (1.75) transferred to pool

### ISSUE THREAD

**Issue by moranden** [Chia-Network/chia-blockchain#11847]
### What happened?

Hi Chia community!

I am contacting you in connection with the recent behavior of my chia farm. 3-4 weeks ago I decided to go full solo and stop pooling with Flexpool for a while just to try my luck. I actually won a 2 blocks right after (05/17/2022 and 05/23/2022), everything went as expected (2 x 0.25xch directly to my wallet, 2 x 1.75 showed in GUI under my solo pooling session – easily claimable without any issues, done that for both rewards on 05/23/2022). 

However, since then I won another two blocks, but somehow I only received 0.25xch (0.50xch) directly to my wallet and 1.75 (3.5xch in total) nowhere. So I started digging and found out that the 1.75 rewards are reported under Blocks menu within my original/former Flexpool gui - webpage. || note: I did not perform any actions with the farmer between first solo claimed rewards and these two, which went to flexpool || 

Please note that I did not send any partials anymore, also my Flexpool homepage was blank (0 workers online with 0 B of total storage since the day I stopped pooling with them) and I do not receive any small rewards for pool farming as it was before. In my chia client I saw that all plots were allocated to solo farming, 0 to pool farming. Is there any way how to solve this issue and get my rewards back? 

Please let me know and I will provide my Flexpool pooling address and block height for both rewards directly - I don't know if it is secure to share it right here to the post as a public info. 

Thank you very much!

What I already did based on help and ideas provided by fellow redditors: reboot of my farm machine, tried to go solo once again, also joined SpacePool on 06/04/22 for like 12 hours (approx last peak size approx. the same as the total amount of my plots) and then went back solo (also SpacePool overview still says "last seen self-pooling"). Double or tripple checked via CLI command chia plotnft show, which states that I am SELF-POOLING with all my plots! Also both farmer reward address and pool reward address changed via gui to my newly generated wallet address in my farmer client and also confirmed in config.yaml that it changed properly.

EDIT on 06/10/2022: yesterday 21 hours ago I won another block (wow, lucky me!), but it is the same story again? 0.25xch directly to me, the rest of the reward to Flexpool, which is crazy considering the fact that the last pool I was connected to is SpacePool.. I have made printscreen of everyting which I think might be useful, can provide on request to share more details with you. ---- linked to my comment below posted 19 hours ago. 

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by moranden** [comment]
Well, what is wrong with my farm? Since I noticed the issue first time a week ago, I switched one more time to SOLO, then moved back to SpacePool for almost 12 hours, then went back SOLO (also SpacePool page says - last seen solo farming).. YET, another block won an hour ago and claimed by flexpool again? :-D This is ridiculous, ofc flexpool dash says 0 workers online, 0B reported space.
Cmd chia plotnft show says that I am selfpooling with all my plots, this is just a bad joke.. Ofc zero rewards or payments received by FP. I just dont know what to do :)

**Comment by emlowe** [comment]
Check your plots for `chia plots check -n 5` and make sure the pool contract for the plots is as expected. You specifically want to see something like `Pool contract address:  txch1my0dspj2lrth8sz9x6kpm9w6cxsvg6wydgvm9ds7wsy6ppgh9q5sarxf5w`

Do you have any OG plots? - for these you will see something like `Pool public key:        8d530a7f9bb223b2eb56438b9b34f8bdc13da6ff12436ce56d00e89334d9710aa31c8212f8dc59b72c1b66c72d9dd0e1`

**Comment by moranden** [comment]
> Check your plots for `chia plots check -n 5` and make sure the pool contract for the plots is as expected. You specifically want to see something like `Pool contract address: txch1my0dspj2lrth8sz9x6kpm9w6cxsvg6wydgvm9ds7wsy6ppgh9q5sarxf5w`
> 
> Do you have any OG plots? - for these you will see something like `Pool public key: 8d530a7f9bb223b2eb56438b9b34f8bdc13da6ff12436ce56d00e89334d9710aa31c8212f8dc59b72c1b66c72d9dd0e1`

Hi emlowe,

thank you for the comment, I did run the command, all plots are valid, but I cannot see anything like pool contract address, the only row which contains word pool is "pool public key:" and that states for all my plots value "None". 

Please note that i do NOT have any OG plots, fully replaced by NFT plots right after introducing pooling option.

**Comment by emlowe** [comment]
Yes, ok you are still on 1.2.11 so that is correct (the showing of the pool contract in chia plots check is in a later version)

Have you tried claiming rewards ? Maybe with the cli - just attempt `chia plotnft claim`

I might also suggest checking the `pool_list` in config.yaml

**Comment by moranden** [comment]
Hi, ahh, I see. Well there is nothing to claim in gui and also in cli, after executing the command with self_pooling wallet it says that there is nothing to claim. In addition, the rewards are listed on the web dashboard of my flexpool contract GUI, so it was already consumed by them. 

In config.yaml the weird thing is that after I rejoined Space Pool for a short period of time, I saw their address in pool_url within the GUI and also config.yaml file. But after I left the pool and went solo, the pool_url "https://eu1.pool.space" dissapeared and went to "pool_url: ' '" like it is my self_pool wallets (yes, I have 7 bullets in total in section "pool_list"), that is also weird, because in GUI and after running "chia plotnft show" it lists only 5 of them, where first 2 bullets from config.yaml are not present (https://xch-de.flexpool.io is listed as the first bullet in the pool_list overview in config file, thus one of these 2 not listed in CLI and GUI).

**Comment by moranden** [comment]
> Yes, ok you are still on 1.2.11 so that is correct (the showing of the pool contract in chia plots check is in a later version)
> 
> Have you tried claiming rewards ? Maybe with the cli - just attempt `chia plotnft claim`
> 
> I might also suggest checking the `pool_list` in config.yaml



> Check your plots for `chia plots check -n 5` and make sure the pool contract for the plots is as expected. You specifically want to see something like `Pool contract address: txch1my0dspj2lrth8sz9x6kpm9w6cxsvg6wydgvm9ds7wsy6ppgh9q5sarxf5w`
> 
> Do you have any OG plots? - for these you will see something like `Pool public key: 8d530a7f9bb223b2eb56438b9b34f8bdc13da6ff12436ce56d00e89334d9710aa31c8212f8dc59b72c1b66c72d9dd0e1`

Hi emlowe, I already moved to 1.3.5 and ran the command you suggested, everyting seems fine without any issues.

**Comment by emlowe** [comment]
I'm unclear on whether there is any action here for this issue. I assume you don't have any further issues.

Switching pool status from pooling to self-pooling requires 2 on-chain transactions to complete. It's possible that the second transaction (which happens automatically after the block height lock) didn't go through - but this doesn't match with your statement that you were able to claim rewards after leaving the pool.

I have no further suggestions other than I recommend staying up to date with chia releases - the current release is 1.6.2. Closing issue as I don't believe there is any actionable work we can do here.
