### ISSUE TITLE
[Bug] chia: error: unrecognized arguments: wallet show

### ISSUE THREAD

**Issue by toby3582** [Chia-Network/chia-blockchain#11850]
### What happened?

chia: error: unrecognized arguments: wallet show

### Version

main

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
I just pulled the latest from main, and attempted to reproduce the issue you are describing, but was unable to. Can you share the output of `git rev-parse HEAD`, or possibly do a `git pull`, re-run `sh install.sh`, and try the command again? Any debug logs may help as well.
