### ISSUE TITLE
[Bug] 电脑意外断电后，chia钱包丢失了14天的币，其中包括一次爆块，该如何找回？

### ISSUE THREAD

**Issue by ElipsK** [Chia-Network/chia-blockchain#11867]
### What happened?

![QQ截图20220610195548](https://user-images.githubusercontent.com/107255965/173061422-fa1b9976-e712-43bb-a112-f7bb4547c5d1.png)
![QQ截图20220610195607](https://user-images.githubusercontent.com/107255965/173061428-0bdc9067-6a3c-4ec9-a5d0-1fe67b667ac6.png)
![QQ截图20220610195619](https://user-images.githubusercontent.com/107255965/173061430-4c9bd8d1-a20d-48e0-99d6-2349f549ba0e.png)
我是使用Space矿池的，因此有每次的转出记录，对比chia钱包的收入5.22-6.2和6.8-6.9收入的chia币都消失了，该如何找回？

### Version

断电时使用的是1.3.3，目前已经更新1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ihola777** [comment]
try to delete the wallet db and then waiting for fully synchronized
