### ISSUE TITLE
solo爆块后，self pooling中的claim rewards后1.75区块显示已到账，但钱包中始终不显示[Bug] 

### ISSUE THREAD

**Issue by weizhangjian** [Chia-Network/chia-blockchain#11888]
### What happened?

>chia plotnft show
Wallet id 2:
Current state: SELF_POOLING
Current state from block height: 2085528
Launcher ID: f8112fa27d620957565c49cf8a7dfbbd02dce1076214067cf04c5b83b8f683f2
Target address (not for plotting): xch100v0xy6y0wxaveguead3xkgygdw693ky2kwvs8v4eextx7y4agcq89f4pj
Number of plots: 1530
Owner public key: a84933d30df7f033f7ce0c99f311150ad8cb17f96ad2d7ec72665e9bae1ea5a72f5589caad9050a234f568ed092e8e38
Pool contract address (use ONLY for plotting - do not send money to this address): xch1m7zlujsfujmkaejsmc467w26kevavtkg56gqq662kvj2hp9xxzdqx06s6w
Claimable balance: 0.0 xch (0 mojo)

Target address (not for plotting): xch100v0xy6y0wxaveguead3xkgygdw693ky2kwvs8v4eextx7y4agcq89f4pj
这个地址1.75已经全部到账，不过不管是gui还是cli中的钱包余额都没有增加。 

>chia wallet get_transaction -f 1047992625 -tx 0x05f82ccee20aca3045fd5540396e4b6e88aea2803472c21c2498dd8f632442cf
Transaction 05f82ccee20aca3045fd5540396e4b6e88aea2803472c21c2498dd8f632442cf
Status: Confirmed
Amount sent: 1.75 XCH
To address: xch100v0xy6y0wxaveguead3xkgygdw693ky2kwvs8v4eextx7y4agcq89f4pj
Created at: 2022-06-12 10:15:48

区块查询详见：都已经到账了。都爆了4次了。
https://blockchain.chiaexplorer.com/blockchain/address/xch100v0xy6y0wxaveguead3xkgygdw693ky2kwvs8v4eextx7y4agcq89f4pj

但是钱包中还是迟迟不显示。这是bug吗？

>chia wallet show
Wallet height: 2110559
Sync status: Synced
Balances, fingerprint: 1047992625

Chia Wallet:
   -Total Balance:         1.000000000201 xch (1000000000201 mojo)
   -Pending Total Balance: 1.000000000201 xch (1000000000201 mojo)
   -Spendable:             1.000000000201 xch (1000000000201 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1

Pool wallet:
   -Total Balance:         0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable:             0.0 xch (0 mojo)
   -Type:                  POOLING_WALLET
   -Wallet ID:             2

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Likely this is a simple wallet sync error - you can try resyncing your wallet, specifically it is helpful to sync with a synced full node (ie, not "wallet-only" mode). There are a number of fixes we are currently testing in main we hope resolve many of these wallet sync issues
