### ISSUE TITLE
Plotting fails in Big Sur for some - both x86_64 and M1 [BUG]

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#1189]
**Describe the bug**
Plotting fails in Big Sur - both x86_64 and M1 for some but not everyone.

**To Reproduce**
Install on Big Sur. It may require not having dev tools installed to replicate though it will replicate on Big Sur on M1 with devtools installed. 

On x86_64 plotting "starts" but if you open the plot log all you see is one entry "Loading...".
On Big Sur it doesn't even pop the creating plots page.

This came in in RC3 with the switch to Click and the RC4 fix didn't fix this.

debug.log from M1:
```
12:07:37.540 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "/Users/hoffmang/chia-blockchain/chia-blockchain-gui/../src/daemon/server.py", line 217, in safe_handle
    response, sockets_to_use = await self.handle_message(websocket, decoded)
  File "/Users/hoffmang/chia-blockchain/chia-blockchain-gui/../src/daemon/server.py", line 322, in handle_message
    response = await self.start_plotting(cast(Dict[str, Any], data))
  File "/Users/hoffmang/chia-blockchain/chia-blockchain-gui/../src/daemon/server.py", line 551, in start_plotting
    "command_args": self._build_plotting_command_args(request, True),
  File "/Users/hoffmang/chia-blockchain/chia-blockchain-gui/../src/daemon/server.py", line 439, in _build_plotting_command_args
    a = request["a"]
KeyError: 'a'
```

debug.log from x86_64
```
18:31:01.565 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "src/daemon/server.py", line 217, in safe_handle
  File "src/daemon/server.py", line 322, in handle_message
  File "src/daemon/server.py", line 551, in start_plotting
  File "src/daemon/server.py", line 439, in _build_plotting_command_args
KeyError: 'a'
```

**Comment by hoffmang9** [comment]
I installed Atom and it installed some of its prerequisites and now plotting works on Big Sur...

**Comment by swim** [comment]
strange the Atom prereqs amended the issue as the Atom Electron version doesn't seem to support m1 yet RE https://github.com/atom/atom/issues/21688

**Comment by hoffmang9** [comment]
![Screenshot 2021-03-06 at 23 41 57](https://user-images.githubusercontent.com/30377676/110399771-41c04200-802b-11eb-92f7-9491200b58e5.png)

Adding both for showing how it manifests and for the "DevTools Failed to load SourceMap:" errors in the electron console.

**Comment by hoffmang9** [comment]
Hrm - https://github.com/electron/electron/issues/22996

**Comment by arvidn** [comment]
on BigSur M1 (fresh with virtually nothing installed other than Chia) it *works* if I launch from the command line:

```
cd /Applications/Chia.app
./Contents/MacOS/Chia
```

at least it starts, prints log and created temporary files, I did not complete a k32.

When I launch it from Finder, the "create plot" button just brings me back to the plots tab with no new item in the list, nor a process running in the background, plotting.

**Comment by mariano54** [comment]
I also experienced a plotting issue on Mac OS Catalina 10.15.7, on a machine that was not M1.

**Comment by danra** [comment]
Still an issue with RC9

**Comment by hoffmang9** [comment]
Painfully aware that this is still a problem . Plotting from Terminal works great in the interim.

https://github.com/Chia-Network/chia-blockchain/wiki/Quick-Start-Guide#macos

**Comment by arvidn** [comment]
I believe this can be closed. it works in 1.0

**Comment by hoffmang9** [comment]
Thanks to both @arvidn and @wjblanke for the painful find and fix!
