### ISSUE TITLE
[Bug] Error message every time `chia plotnft show` is ran

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#11897]
### What happened?

On mainnet, from current HEAD of `release/1.4.0` (b8e34c856)

Every time I run `chia plotnft show`, the plotnft info shows as expected up until it is supposed to show the pool payout address, where it spits out:
```
Exception from 'wallet' <bytes32: 84d52a439ed7d11b73054198add4a2b34c34b56c03abf67198d5f3d70753ee5b>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f39a1645a80>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f39a1698c40>, 563381.436435318)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f39a1644e20>
```
This happens on a wallet that has a plotnft.

### Version

b8e34c856

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
No relevant debug log output
```

**Comment by emlowe** [comment]
`plotnft show` does need the farmer to be running - see #9919. So this might be related
