### ISSUE TITLE
[Bug] Balance mismatch between 2 computers

### ISSUE THREAD

**Issue by fantasylincen** [Chia-Network/chia-blockchain#11901]
### What happened?

I installed two clients on two computers, and asked one of them to turn off and restart after a period of time. I found that the balances of the two clients were not synchronized

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Can you provide more details - are you running in wallet-only mode on both issues? 
This sounds like a wallet syncing issue, you can try to resync the wallet.

**Comment by fantasylincen** [comment]
我有两台电脑，都安装了同样私钥的钱包，其中一台关机两三天左右，关机后，进行了几次转账操作，钱包余额18左右，然后把关机的钱包再次打开同步，同步成功后余额显示4.9,而正常那台钱包还是18. &nbsp;删除wallet.db后，恢复正常


I have two computers with wallets with the same private key installed. One of them has been shut down for about twoorthree days. After the shutdown, several transfer operations have been carried out. The wallet balance is about 18, and then the shut-down wallet is opened again for synchronization. After the synchronization is successful, the balance displays 4.9, while the normal wallet is still 18 , Delete wallet.db , sync….., return to normal


------------------ Original ------------------
From: Earle Lowe ***@***.***&gt;
Date: Fri,Jun 17,2022 1:12 AM
To: Chia-Network/chia-blockchain ***@***.***&gt;
Cc: fantasylincen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Chia-Network/chia-blockchain] [Bug]  (Issue #11901)





 
Can you provide more details - are you running in wallet-only mode on both issues?
 This sounds like a wallet syncing issue, you can try to resync the wallet.
