### ISSUE TITLE
TechDebt: `uint64()` doesn't seem like it should be needed long term.

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#11926]
While the `uint64()` added in [`5be6db6` (#11919)](https://github.com/Chia-Network/chia-blockchain/pull/11919/commits/5be6db6971d13c65132b7aab29f1e5899cea8cb0) looks to be required now, at least for hinting, it doesn't seem like it should be needed long term.  `chia_rs` does indicate that the type should be `u64` https://github.com/Chia-Network/chia_rs/blame/59f6709693b7b68ff2d5cdf2fe8711f0f537e33b/wheel/src/coin.rs#L25 but the generated hints just say `int`.  I haven't checked the actual runtime type of either the amount nor the others that are supposed to be `bytes32`.

```python
class Coin:
    parent_coin_info: bytes32
    puzzle_hash: bytes32
    amount: int
```

_Originally posted by @altendky in https://github.com/Chia-Network/chia-blockchain/pull/11919#pullrequestreview-1008435422_

**Comment by altendky** [comment]
[`a18f910` (#11942)](https://github.com/Chia-Network/chia-blockchain/pull/11942/commits/a18f910b6da766ff226db7cc836430998dc4d657)

**Comment by altendky** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/12000/files/dd1a07965abd2af07cb5a03c1329bfc3c0ecc441..3a42d071b9e31f4c530e246785843c9eb5d2837f

**Comment by altendky** [comment]
[`1aa4810` (#12010)](https://github.com/Chia-Network/chia-blockchain/pull/12010/commits/1aa48103b82921cc85fd369d19f9c3d0c4514949)

**Comment by arvidn** [comment]
even though the `amount` field is guaranteed to fit in a `uint64`, the actual type is the built-in `int` type. Hinting it as `uint64` would be error prone (and caused a few failures while when I initially tried to do that). I describe the issue in the PR description here: https://github.com/Chia-Network/chia-blockchain/pull/11807

**Comment by arvidn** [comment]
sorry if that caused merge issues for the nft branch. It believe it could be fixed by making the fixed int types rust types too.

**Comment by arvidn** [comment]
I wouldn't think it would be very high priority though

**Comment by altendky** [comment]
Other than the noise of adding a bunch of `uint64()` calls, the hard part is that we still lack proper hint checking in lots of places so this isn't automatically caught.  I don't have a preferred action here yet.

**Comment by emlowe** [comment]
I believe we went the other direction and chia_rs now has the fixed-width types like uint64 - see https://github.com/Chia-Network/chia-blockchain/pull/17505

closing item
