### ISSUE TITLE
[Bug] Trouble switching to self-pooling wrt unconfirmed transactions

### ISSUE THREAD

**Issue by mixkelvin** [Chia-Network/chia-blockchain#11930]
### What happened?

Cannot self pool due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.
but there is no unconfirmed transaction.

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Do you mean you tried to use `delete unconfirmed transactions` and that action reported there are no unconfirmed transactions?

**Comment by emlowe** [comment]
Closed due to lack of response
