### ISSUE TITLE
Decreasing coin add log line from info to debug breaks third party monitors such as Chiadog.

### ISSUE THREAD

**Issue by guydavis** [Chia-Network/chia-blockchain#11955]
Please see this [line](https://github.com/Chia-Network/chia-blockchain/blob/c6f60e791b1d32fac47a0e6d124f10b459aca92e/chia/wallet/wallet_state_manager.py#L1159) of logging.  Here's the [commit](https://github.com/Chia-Network/chia-blockchain/pull/11886/files#diff-a367f650aed3b60eba2c253ce15852630c1baf5e9891223d1557ac9cb3333d20R1118) that made this change.

![20220617_105120](https://user-images.githubusercontent.com/12936/174343514-aaa964f3-0c55-467f-bbbc-a79ad1ea50d9.png)

Log monitors such as [Chiadog](https://github.com/martomi/chiadog) look for this log line in the Chia log at `info` level.  By moving this message to `debug` level, Chiadog no longer can report on added coins as in previous versions of Chia. 

Would it be possible to get this log line back to `info` level again?  Thanks!

**Comment by mariano54** [comment]
Sure, can you make a PR for it?
