### ISSUE TITLE
Fees don't actually get paid with NFT transactions [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#11951]
### What happened?

The following command was run on a wallet with less than 1 TXCH. The fee is for 1 trillion mojos. The command succeeds (it should fail due to insufficient funds) and no fee is deducted:

`chia rpc wallet nft_add_uri '{\"wallet_id\": 2, \"nft_coin_id\": \"ea9409d5469eb4b9baa09c41cff28900e0a5ee543696e542bd751fbfd79ee972\", \"key\": \"mu\", \"uri\": \"https://newmetadatauri.net\", \"fee\": \"1000000000000\"}'`

A similar CLI command also succeeds without deducting a fee:
`chia wallet nft add_uri -i 2 -ni ec45154989debc4d04ea98971735da727b41c85766115b8793dda6b21e26f8c7 -lu https://2new_license_uri.com -m 0.5`

For the record, a normal TXCH tx does deduct the fee as expected:
`chia wallet send -a 0.5 -m 0.01 -t txch1d2cwjcuq24t0aqrateed0ptk0r9quy45ap7gu5kj7zfs0r27qwfsr8s50g`

### Version

1.3.6.dev667 (release/1.4.0 branch)

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by trepca** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/12008

**Comment by trepca** [comment]
This works for me now. @danieljperry can you test again?

**Comment by danieljperry** [comment]
Confirmed this is fixed in dev741.
Test 1: add fee greater than amount in wallet. Result: "Can't select amount higher than our spendable balance."
Test 2: add smaller fee. Result: fee is actually deducted.
