### ISSUE TITLE
[Bug] stdout pipe tought "cut -f 2" doesnt work with chia logs on most messages (example chia.plotting.check_plots)

### ISSUE THREAD

**Issue by NetrunnerAT** [Chia-Network/chia-blockchain#11977]
### What happened?

This is a minor Bug.

If i use "chia plot check" and pipe it tought "cut -f 2" i get lines like this.

Finding proof took: 947 ms
Proofs 8 / 5, 1.6
2022-06-19T09:29:43.071  chia.plotting.check_plots        : INFO     Testing plot /mnt/hdd-old/disk1/plot-k32-2022-06-16-03-53-65(deleted for post)bec9.plot k=32
Pool contract address:  xch1(deleted for post)
Farmer public key:      8c(deleted for post)

Its look like a lot of messages in stdout in "chia.plotting.check_plots" and "chia.plotting.manager" or chia in common, are not well formated for the linux command "cut"? Tabulator missing for correct formating?

https://github.com/Chia-Network/chia-blockchain/blob/main/chia/plotting/check_plots.py

Line 97     log.info(f"Starting to test each plot with {num} challenges each\n")
Line 107   log.info(f"\t{'Pool public key:':<23} {plot_info.pool_public_key}")

### Version

1.3.5

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
Out of curiosity, what is it that you are wanting to return exactly, and how would you want the end result to be formatted?
