### ISSUE TITLE
Closing GUI stops Daemon[Bug] 

### ISSUE THREAD

**Issue by ob7** [Chia-Network/chia-blockchain#11976]
### What happened?

If you start your full node from command line via chia start farmer, and then you open up the gui, when you close the gui, it stops everything that was started on the command line as well.

Preferably, when running chia from the command line first, and then only opening up the gui later, when closing the gui it will not stop everything that was started on command line. 

It makes sense to stop everything if it was started from the gui, but if it was started from cmd line then gui shouldn't stop all the processes when it exits.

### Version

latest

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by NetrunnerAT** [comment]
Its normal ;-)

start chia as systemd job. if  you shutdown the gui, systemd restart chia again. you lost only some sec of not farming.

**Comment by wallentx** [comment]
Related to https://github.com/Chia-Network/chia-blockchain-gui/pull/670

**Comment by dfifield1** [comment]
Still an issue. There needs to be a setting to prevent the stopping of services when you exit the gui.
