### ISSUE TITLE
[Bug] Accept Offer button greyed out

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#12007]
### What happened?

1. Create an offer for an NFT
2. Save the offer file on desktop
3. View the offer file through View an Offer
4. Observe that the Accept Offer button is greyed out (see screenshot)

Is it a new thing that offers can't be accepted by the offer creator?
![Screen Shot 2022-06-21 at 6 36 15 PM](https://user-images.githubusercontent.com/86693700/174924815-31956fed-78f2-4873-9120-fcf65054be66.png)
 

### Version

dev686

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
@paulhainsworth-chia please re-test with the latest DF build
