### ISSUE TITLE
Wallet Status & Balance Unreliable [Bug] 

### ISSUE THREAD

**Issue by reythia** [Chia-Network/chia-blockchain#12053]
### What happened?

Wallet incorrectly reports 'synced', balances are incorrect, and transaction history is inconsistent across nodes. Basic information can not be relied upon. This affects multiple versions and OS.

I've just finished syncing a new node from scratch. The node is up to date and the wallet shows 'Synced'. It's missing over 100,000 transactions and the balance is wrong. This is 1.3.5 on windows. Restarting Chia a few times it quickly comes back to 'synced' with no new data.

So I just cleared the wallet DBs on this node and set connect_to_unknown_peers: false. This time it's decided its fully synced after a minute or two with 180,000 transactions missing.

I saw this whilst syncing the blockchain - entire receive addresses missing - which I originally thought was because the new versions didn't "know" about older non-observer addresses. It eventually started picking up transactions before the node was fully synced so I wrote it off, but there was no indication as to why it was missing, why it started being tracked, or why it never finished.

I have another node with the same wallet which settled at 80,000 transactions short with the wrong balance. I didn't notice for weeks until checking something on a public explorer. This one being 1.3.4 on Ubuntu. I've archived that wallet DB and currently resyncing a new one, but I've done that twice before since 1.3.4 was released. 

Could be the older key style, could be the heavily dusted addresses, not sure, but deleting and resyncing the wallet DB doesn't resolve.

### Version

1.3.5, 1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by mariano54** [comment]
Hello. Do you mind trying out the "Latest Dev" download from this page: https://www.chia.net/download/?

This might fix the issue.

**Comment by reythia** [comment]
Thanks. I'll try the latest and get back to you. I think it's around 200k with dust.
