### ISSUE TITLE
[Bug] Can't make an offer to buy and NFT that I already own

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#12083]
### What happened?

1. Get the NFT ID of an NFT I already own
2. Create an offer to acquire that NFT in exchange for 1 TXCH
3. Save offer file
4. Open offer file with same wallet
5. Accept the offer

Expected result: I should buy my own NFT and spend the 1 TXCH to acquire it. 

Outcome: "offers you accepted" shows "Failed" 
![Screen Shot 2022-06-25 at 1 34 59 PM](https://user-images.githubusercontent.com/86693700/175789813-8a2d5752-ef87-4ce5-acce-adf707263afa.png)

See log error message

### Version

dev752

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-06-25T13:33:47.553 wallet chia.wallet.trade_manager  : WARNING  Trade with id: 0a970264b4cbb53927d1ab437ed4c54d5e81a23e5a48a4549db60f98d927c3c7 failed
```

**Comment by pmaslana** [comment]
William Allen and I were able. tosuccessfully accept our own offers
