### ISSUE TITLE
[Bug] What exactly are the yields on the farming panel showing?

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#12089]
### What happened?

Currently I am soloing and the earnings are not showing on the panel.
The address is not filled in this wallet, and the income is not displayed on the panel
Can it be displayed on this panel as long as this farmer node explodes all the rewards?

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to share a screenshot of the field that you are wondering about

**Comment by 0X1231** [comment]
![image](https://user-images.githubusercontent.com/97425684/176821146-1bd5a834-05d3-4305-af4d-155fd6228a27.png)
