### ISSUE TITLE
[Bug] Show Preview button doesn't always work

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#12092]
### What happened?

1. In wallet 1, create an offer file offering 1 txch for an NFT that is in wallet 2
2. copy the offer blob to clipboard
3. open wallet 2
4. click view offer and paste in the blob
5. click the "show preview" button the nft thumbnail (file is over 10mb)

result: nothing happens when show preview button is clicked
expected result: preview should be shown

Note: I noticed that another similar button in the GUI didn't work either as expected. In plots > add plot > "browse" button on Select Temporary Directory -- this also didn't pop a system dialog to select a folder. Quitting the app and restarting resolved this. 

### Version

dev752

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
I've had no problems with this working on windows
