### ISSUE TITLE
[Bug] Save Offer File doesn't always open system dialog to save the file

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#12091]
### What happened?

1. Create an offer
2. Select "save offer file" (see screenshot)

expected result: system dialog should pop to ask me to save the file 
result: nothing happens
![Screen Shot 2022-06-25 at 6 46 03 PM](https://user-images.githubusercontent.com/86693700/175795953-35c82215-09fe-47e0-b22f-54d6f943b0d1.png)

### Version

dev752

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by mariano54** [comment]
Maybe fixed by https://github.com/Chia-Network/chia-blockchain/pull/12095
