### ISSUE TITLE
[Bug] Greedy NFT 

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#12094]
### What happened?

1. Wallet1 owns Greedy NFT, which has a 655.35% creator fee
2. Open Wallet 2, and create an offer file XCH for NFT.
3. Paste in Greedy NFT's NFT ID and offer 1 txch
4. Observe error message: "unable to create an offer where the net amount is negative"

When a creator fee is over 100%, is this use case of trying to buy an NFT from the creator always a negative value? 
![Screen Shot 2022-06-25 at 7 22 36 PM](https://user-images.githubusercontent.com/86693700/175796740-76d1db60-cccc-4a32-8405-2725fb1f7aba.png)

### Version

dev752

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by pmaslana** [comment]
So, we cannot create nor accept an offer with creator fees greater than 100%.

**Comment by pmaslana** [comment]
This is by design
