### ISSUE TITLE
Incorrect wallet balance [Bug] 

### ISSUE THREAD

**Issue by GPS-2022** [Chia-Network/chia-blockchain#12101]
### What happened?

Some deposits and my wallet balance are gone.

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
have you closed the client, deleted the wallet db, and restarted and let the wallet resync?

**Comment by wallentx** [comment]
We've just released 1.4.0 https://github.com/Chia-Network/chia-blockchain/releases if you would like to try that.

**Comment by luckypig3400** [comment]
> have you closed the client, deleted the wallet db, and restarted and let the wallet resync?

## Thanks a lot ~ ヾ(≧▽≦*)o That's work for me!

I'm using Win10 21H2, just few hours ago I found my wallet Transaction records from 6/3 ~ 7/2 were missing, and so did part of my XCH coins.

### After I closed the Chia GUI and deleted the following folder
* C:\Users\```Your User Name```\.chia\mainnet\wallet
(You can backup this folder before deleting it.)

### And wait for the few minutes, my losing Coins & Transaction records has come back！
