### ISSUE TITLE
[Bug] Receiving an ASSERT_MY_PARENT_ID_FAILED error for minting NFT to DID Wallet

### ISSUE THREAD

**Issue by pmaslana** [Chia-Network/chia-blockchain#12111]
### What happened?

I am running the following command, which results in a success message in the terminal window:

chia rpc wallet nft_mint_nft '{"wallet_id": 5, "royalty_address":"txch1lglmcufwrwyc5n9mhfqaa6nwh2v2xlrsnljvu5fgqe4cl3p46pxs5djym4", "target_address": "txch1lglmcufwrwyc5n9mhfqaa6nwh2v2xlrsnljvu5fgqe4cl3p46pxs5djym4", "royalty_percentage": 250, "uris": ["https://ipfs.io/ipfs/QmYpSF5rp363ZEuB38efKQEUYEf3CwKJJq81Wtkjjxeqej"], "hash": "a4221203173bf7bc3720a2673a2bfd9131f20bfa245b80374688868a259b2d27", "meta_uris": ["https://pastebin.com/raw/94gsyzcD"], "meta_hash": "d41c1bde82f812fd4f278bf195c404d53059a2608de0d4a7ddb6444051f83df7", "license_uris": ["https://raw.githubusercontent.com/Chia-Network/chia-blockchain/main/LICENSE"], "license_hash": "30a358857da6b49f57cfe819c1ca43bfe007f528eb784df5da5cb64577e0ffc6", "series_number": 1, "series_total": 100, "did_id": "did:chia:14zku9jtt093cq6nfu7f4s5f8r8a5heap9ffha9d3dhvf6klk5arqjjyn8l", "fee": 0.000000002}'

I pulled the latest from release/1.4.0 and re-installed chia to see if that would fix the issue, but it does not.

[log-output.txt](https://github.com/Chia-Network/chia-blockchain/files/8988632/log-output.txt)

### Version

1.3.6.dev752 - latest on release/1.4.0

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-06-26T21:05:58.142 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_MY_PARENT_ID_FAILED',

"sent": 1, "sent_to": [["05cf3b5315c08357ca99c2795027ed2062bfed1ef398268aa1c9a30a290ba8e1", 3, "ASSERT_MY_PARENT_ID_FAILED"], ["05cf3b5315c08357ca99c2795027ed2062bfed1ef398268aa1c9a30a290ba8e1", 3, "ASSERT_MY_PARENT_ID_FAILED"], ["05cf3b5315c08357ca99c2795027ed2062bfed1ef398268aa1c9a30a290ba8e1", 3, ASSERT_MY_PARENT_ID_FAILED"], ["05cf3b5315c08357ca99c2795027ed2062bfed1ef398268aa1c9a30a290ba8e1", 3, "ASSERT_MY_PARENT_ID_FAILED"]],
```

**Comment by danieljperry** [comment]
I have reproduced the issue.

OS: Windows
Version: dev752

Command:
`chia rpc wallet nft_mint_nft '{\"wallet_id\": 4, \"royalty_address\":\"txch1mldt8hsz329sdjj3zdcy39xlh4rx4qctfhfzplul07zxkmwzlq0qpc5tsp\", \"target_address\": \"txch1mldt8hsz329sdjj3zdcy39xlh4rx4qctfhfzplul07zxkmwzlq0qpc5tsp\", \"royalty_percentage\": 250, \"uris\": [\"https://ipfs.io/ipfs/QmYpSF5rp363ZEuB38efKQEUYEf3CwKJJq81Wtkjjxeqej\"], \"hash\": \"a4221203173bf7bc3720a2673a2bfd9131f20bfa245b80374688868a259b2d27\", \"meta_uris\": [\"https://pastebin.com/raw/94gsyzcD\"], \"meta_hash\": \"d41c1bde82f812fd4f278bf195c404d53059a2608de0d4a7ddb6444051f83df7\", \"license_uris\": [\"https://raw.githubusercontent.com/Chia-Network/chia-blockchain/main/LICENSE\"], \"license_hash\": \"30a358857da6b49f57cfe819c1ca43bfe007f528eb784df5da5cb64577e0ffc6\", \"series_number\": 1, \"series_total\": 100, \"did_id\": \"did:chia:14zku9jtt093cq6nfu7f4s5f8r8a5heap9ffha9d3dhvf6klk5arqjjyn8l\", \"fee\": 700000000}'`

Log:
`2022-06-27T10:08:11.342 wallet chia.wallet.wallet         : INFO     About to sign a transaction: [CoinSpend(coin=Coin(parent_coin_info=<bytes32: 0a08a2ed956b6385f1a8c7e3949d379d4cb62bfa8ab32c95c2cab49fa7c6a070>, puzzle_hash=<bytes32: 7a3d80686204f17e12a0ed3b2f2b0b0bf83c8fe943ae68b571030af2fa9ed2b8>, amount=299989999999), puzzle_reveal=SerializedProgram(ff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0ac95e9610e9231d1a0d379ccc5e8d37e6bb60b1439f15f1c8b0f9dc7d4f5b7aa1b791616535f9ae04b90cc4912ecf279ff018080), solution=SerializedProgram(ff80ffff01ffff33ffa0eff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9ff0180ffff33ffa0f7f57d3daed3f8398a2e03cd9f638d3331ca0e422b7de00488a3b68472ae89a5ff8545af12fa7e80ffff34ff8429b9270080ffff3cffa0c58392cc19ce09cb7eb8ce309ab82accb7e08c383269be9c598a79943c730aa080ffff3dffa07154d662af8054846dc568d685e770575e09259e1c7f53e624e7f3a3137839a98080ff8080))]
2022-06-27T10:08:11.373 wallet Test DID                   : INFO     About to select coins for amount 1
2022-06-27T10:08:11.375 wallet Test DID                   : INFO     Successfully selected coins: {Coin(parent_coin_info=<bytes32: 60b1e329c1111f4fcdabd588c9a1a27dc83f4d2d40aa21aadda3e8eaa6d236f0>, puzzle_hash=<bytes32: 8e0ce0472224669d146ea98dc6af2b31b1ca62d202db2ee25b37f8f25da3c3d7>, amount=1)}
2022-06-27T10:08:11.477 wallet chia.wallet.wallet_node    : INFO     new coin state received (1-2/ 2)
2022-06-27T10:08:11.492 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x4be0f769a0d149dea5979b130436f8ed59427ec0401431aea731f9326c8c5a52'}
2022-06-27T10:08:11.494 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'ASSERT_ANNOUNCE_CONSUMED_FAILED',
 'status': 3,
 'txid': '0x4be0f769a0d149dea5979b130436f8ed59427ec0401431aea731f9326c8c5a52'}`

**Comment by pmaslana** [comment]
Needed to delete wallet DB and create a new DID due to recent code changes.

**Comment by danieljperry** [comment]
Chialisp has changed. I was able to fix my version of this issue by deleting my wallet, deleting my wallet db, creating a new wallet, and creating a new DID/NFT wallet. Afterward, the same minting command was successful.
