### ISSUE TITLE
[Bug] Transaction hash changed to another after some time

### ISSUE THREAD

**Issue by vayamos-exchange** [Chia-Network/chia-blockchain#12113]
### What happened?

2022-06-22 about 17:30 i sent some Chia to address: xch1uk9a4fdyhacrg9y8kqqan3rw4fwefzszyjpzruj7tmuhm32h0ksq59xwkz

Then the transaction hash was as follows: 0x22240f1ce00cef8d2f8c89e85f79c2d9657108772485fb2f9f55ce31e86a8dbc
Now after a few days Chia wallet shows different hash for the same transaction: 0x9a968ba9f2a0f552e4c0d845fae4f682d1f845930a3bd016b8ac0b8b21a610c4

The transaction is still visible in the block explorer under the old hash, and there is no information about the new one.
So why has the hash changed over time? How can we uniquely identify a given transaction if the transaction hash is not reliable?

### Version

latest

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
$ chia wallet get_transactions
(...)

Transaction 9a968ba9f2a0f552e4c0d845fae4f682d1f845930a3bd016b8ac0b8b21a610c4
Status: Confirmed
Amount received: 0.22887 XCH
To address: xch1uk9a4fdyhacrg9y8kqqan3rw4fwefzszyjpzruj7tmuhm32h0ksq59xwkz
Created at: 2022-06-22 17:21:14
```

**Comment by ageorge95** [comment]
Hi,
I am no expert by any means, but maybe [0x22240f1ce00cef8d2f8c89e85f79c2d9657108772485fb2f9f55ce31e86a8dbc](https://alltheblocks.net/chia/coin/0x22240f1ce00cef8d2f8c89e85f79c2d9657108772485fb2f9f55ce31e86a8dbc) is the coin that went in xch1uk9a4fdyhacrg9y8kqqan3rw4fwefzszyjpzruj7tmuhm32h0ksq59xwkz and 9a968ba9f2a0f552e4c0d845fae4f682d1f845930a3bd016b8ac0b8b21a610c4 is the transaction hash.

What I am saying is that 9a968ba9f2a0f552e4c0d845fae4f682d1f845930a3bd016b8ac0b8b21a610c4 was the transaction hash from the beginning and 0x22240f1ce00cef8d2f8c89e85f79c2d9657108772485fb2f9f55ce31e86a8dbc was the coin that got in that wallet address, from the beginning.

Not sure if these things can change over time; Once they are written in the blockchain, no one can change them. Right 😨 ?

Most probably it is a visual bug (hopefully).

**Comment by vayamos-exchange** [comment]
@ageorge95 that's impossible, because I'm 100% sure that the old hash was in the same place a few days ago where different hash is now.  I would never have discovered this problem otherwise

**Comment by emlowe** [comment]
Did you resync the wallet DB in the meantime?

Chia doesn't have transactions per se - it has coins. For record-keeping, the notion of a transaction is solely a local wallet construct and represents the hash of the entire spendbundle submitted to the chain. The chain itself (and the various explorers) do not allow viewing this spendbundle hash as a transaction. You cannot view this transaction on chain, you can only view coins

However, if you do `chia wallet send...` that transaction id (and spendbundle) is stored in the wallet DB and shouldn't change - however, this spendbundle as submitted to the chain is ONLY stored in the wallet db . It should remain there and allow you to query it based on the ID, as long as you do not resync the wallet. Once you resync the wallet however, you lose all the information about these spendbundles and the transaction id will no longer be available.
