### ISSUE TITLE
1.3.5.dmg won't install "Chia" is damaged and can't be opened [Bug] 

### ISSUE THREAD

**Issue by joshhamon** [Chia-Network/chia-blockchain#12115]
### What happened?

Neither version of 1.3.5 on the official website will load. The dmg creates the application file but that file won't launch from USB, only from ~/Applications

I'm running 10.14.6

### Version

1.3.5

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by jack60612** [comment]
This is not an issue and is simply user error, closing issue
