### ISSUE TITLE
[Bug] Full node all spinners

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#12121]
### What happened?

1. switch from testnet to mainnet
2. delete peers.dat, wallet db
3. launch dev758 client
4. endless spinners on full node
5. note that wallet is synced and can spend
6. go to terminal, run chia show -s and observe:

Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up

### Version

dev758

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by pmaslana** [comment]
Switch between mainnet and testnet multiple times. Did not experience any issues.
