### ISSUE TITLE
[Bug] "Cannot find child coin, please wait then retrv." Error received in NFT preview.

### ISSUE THREAD

**Issue by pmaslana** [Chia-Network/chia-blockchain#12151]
### What happened?

When creating and viewing an offer for an NFT that exceeds 10mb, I received "Cannot find child coin, please wait
then retrv." in the preview window
![Screen Shot 2022-06-28 at 2 14 17 PM](https://user-images.githubusercontent.com/79757486/176500117-d4687167-7495-45fa-8dd8-39356fc14d78.png)
.

### Version

1.3.6dev762

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Need to verify if this is reproducible on a wallet synced to a local full node that is NOT connected to remote untrusted nodes.
