### ISSUE TITLE
[Bug] offer total shown in gui does not match apparent total used

### ISSUE THREAD

**Issue by altendky** [Chia-Network/chia-blockchain#12184]
### What happened?

I had 0.101xch spendable and when to create an offer for 0.1xch in requesting an NFT and provided a 0.001xch fee and got an error stating that the amount would be 0.104xch.  I expect a 0.03xch royalty but the GUI states it will be taken out of the 0.1xch i offered and the total will be 0.101xch.

```
Error creating offer: Can't select amount higher than our spendable balance. Amount: 104000000000, spendable: 101000000000
```

![paste (6)](https://user-images.githubusercontent.com/543719/176942586-930c6649-f774-4e62-9a61-5c0dbcf3467c.png)

backend and remote gui: 16aafffb71d297f27ca4e99cba69a7efc3033a3e

I had exactly 0.101xch spendable balance because i had sent myself that before making a previous offer of the same form as above and that offer apparently didn't use the expected 0.101xch coin but instead used the bigger coin, presumably because it though it needed or actually did use the full 0.104xch.

### Version

`main` after 1.4.0

### What platform are you using?

Pi4

### What ui mode are you using?

GUI

**Comment by danieljperry** [comment]
This is the bug: In the scenario where someone makes an offer to buy an NFT, the GUI claims the royalty will be deducted, but it's actually added.

Here's a flow I did to verify this:

1. Buyer/Maker: Offer 100 million mojos to buy cooked meat. GUI claims 3 million mojos will be deducted as a Creator Fee and seller will receive 97 million mojos. Total amount offered is 100 million mojos. Save offer file.

2. Seller/Taker: View offer file. It claims the Seller/Taker will receive 97 million mojos in exchange for cooked meat. Additionally, there will be a 3 million-mojo Creator Fee. Total amount offered is 100 million mojos. Net proceeds to be deposited in Seller/Taker's wallet is 97 million mojos.

3. Seller/Taker: Accept offer. For simplicity, neither Maker nor Taker has added a transaction fee.

4. Seller/Taker: After transaction completes, 100 million mojos has been deposited. This is incorrect. It was supposed to be 97 million. Cooked meat NFT leaves wallet as expected.

5. Buyer/Maker: 103 million mojos has been deducted. This is incorrect. It was supposed to be 100 million. Cooked meat NFT received as expected.
