### ISSUE TITLE
Local Simulation Problem

### ISSUE THREAD

**Issue by Z2020Z** [Chia-Network/chia-blockchain#122]
I'm running the local simulation using run_all_simulation.sh on CentOS 7.7. 
But got this: 
VDF Server: Got stop signal before completing the proof!

Can I ask why VDF get stop signal before completing the proof?

I've set up introducer_peer to 127.0.0.1:8445  and disabled uPnP.

**Comment by hoffmang9** [comment]
Yes - If a better proof of space or a new winning block comes out, then there is often no reason to keep trying to complete the proof of time that that VDF instance is working on.

It's working as expected.
