### ISSUE TITLE
CH21 Token still in a pending status [Bug] 

### ISSUE THREAD

**Issue by GaJIoDHbI** [Chia-Network/chia-blockchain#12240]
### What happened?

Still didnt get my 2 ch21. Confirmed on high: 1405944. Date 11 Jan 2022. Address: xch1g0fd9288aec66qlmwjgqzetmcgw8plv0wxvzc4fenl4z64xhh83sr9vqfe. Status: Pending balance 2CH21. 
But my CH21 wallet is: xch1rxg4ek43frqw4rl3sh46wuh3h0vtprc5w7shlt606f4agvu5337qaq6ygr.

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to provide more details on how you matched the pending send to your wallet? If you ran any CLI commands relevant to this, can you share the output?
Are you using Farming mode, or wallet mode?

**Comment by GaJIoDHbI** [comment]
Status is still pending...
