### ISSUE TITLE
[Bug]1.4.1293 The wallet of light money cannot be synchronized.

### ISSUE THREAD

**Issue by Concord-us** [Chia-Network/chia-blockchain#12268]
### What happened?

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/9056554/debug.log)
Look down on the log for details

### Version

1.4.1293

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Detailed log has been uploaded to the attachment
```

**Comment by HVNC1** [comment]
что вы сделали с бумажником.почините его

**Comment by emlowe** [comment]
closing issue
