### ISSUE TITLE
[No Keys Loaded message after plotnft claim] 

### ISSUE THREAD

**Issue by jmhands** [Chia-Network/chia-blockchain#12266]
### What happened?

`chia plotnft claim -i 2 -m 0.000000000005`

cli pauses for a long time, then completes the tx

then a `chia wallet show` will error out with 
```No keys loaded. Run 'chia keys generate' or import a key```

`chia start -r wallet` does not immediately fix. Getting connection error on the wallet

### Version

1.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
This may duplicate https://github.com/Chia-Network/chia-blockchain/issues/12312

**Comment by wallentx** [comment]
@jmhands can you try main and see if this is resolved? https://github.com/Chia-Network/chia-blockchain/issues/11175 was closed out with a fix that got merged this evening.
