### ISSUE TITLE
[Bug] 1.4.1293 Synchronization completed, still can not be sent!

### ISSUE THREAD

**Issue by Concord-us** [Chia-Network/chia-blockchain#12269]
### What happened?

![image](https://user-images.githubusercontent.com/97425684/177603657-ac2f2bf0-bd98-40f4-ac87-b0dca7a737d5.png)

### Version

1.4.1293

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
I reported this issue internally last week, and @seeden and @mariano54 provided feedback, and seem to have a path for resolution

**Comment by 0X1231** [comment]
ok

**Comment by emlowe** [comment]
Closing issue that was likely fixed in later releases.
