### ISSUE TITLE
[Bug] Nft does not display

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#12271]
### What happened?

![image](https://user-images.githubusercontent.com/97425684/177611068-b8455d9d-df01-44f9-83bb-0b0701952a96.png)

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
ubuntu 22.04
```

**Comment by wallentx** [comment]
Where is the metadata for these NFTs hosted? I believe the GUI doesn't have the ability to resolve IPFS data yet.

**Comment by 0X1231** [comment]
> 这些 NFT 的元数据托管在哪里？我相信 GUI 还没有能力解析 IPFS 数据。

不在IPFS上

**Comment by 0X1231** [comment]
我重启了一下电脑这个问题OK了
