### ISSUE TITLE
[Bug] Retrying in five minutes why?

### ISSUE THREAD

**Issue by lolminerxmrig** [Chia-Network/chia-blockchain#12289]
### What happened?

Time for phase 4 = 652.970 seconds. CPU (95.040%) Thu Jul  7 12:53:31 2022
Approximate working space used (without final file): 269.348 GiB
Final File size: 101.358 GiB
Total time = 19872.013 seconds. CPU (161.670%) Thu Jul  7 12:53:31 2022
Could not copy "D:\\plot-k32-2022-07-07-07-22-5316f6514389e82d605334a71bbdd3323492164e063aecbf35dec97eccbfbae2.plot.2.tmp" to "W:\\chia\\plot-k32-2022-07-07-07-22-5316f6514389e82d605334a71bbdd3323492164e063aecbf35dec97eccbfbae2.plot.2.tmp". Error The volume for a file has been externally altered so that the opened file is no longer valid.. Retrying in five minutes.

### Version

1.3.5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Time for phase 4 = 652.970 seconds. CPU (95.040%) Thu Jul  7 12:53:31 2022
Approximate working space used (without final file): 269.348 GiB
Final File size: 101.358 GiB
Total time = 19872.013 seconds. CPU (161.670%) Thu Jul  7 12:53:31 2022
Could not copy "D:\\plot-k32-2022-07-07-07-22-5316f6514389e82d605334a71bbdd3323492164e063aecbf35dec97eccbfbae2.plot.2.tmp" to "W:\\chia\\plot-k32-2022-07-07-07-22-5316f6514389e82d605334a71bbdd3323492164e063aecbf35dec97eccbfbae2.plot.2.tmp". Error The volume for a file has been externally altered so that the opened file is no longer valid.. Retrying in five minutes.
```

**Comment by wallentx** [comment]
What are your `D:` and `W:` drives (internal, external, etc)?

**Comment by lolminerxmrig** [comment]
tmp SSD D: and work sata W:

**Comment by wallentx** [comment]
These errors seem to indicate that something is happening with the drives outside of Chia. Are you able to verify that there are no errors on the disk, and that they connections (of cables are used) are good?
