### ISSUE TITLE
[Bug] App hard crash that requires a full reboot to resolve

### ISSUE THREAD

**Issue by 0xFuego** [Chia-Network/chia-blockchain#12288]
### What happened?

Got a crash,popped up an error notification. Syslog gives nothing useful. Relevant portion of the chia log is below. Looks like it errors then breaks at 288 in a way that cant be recovered from. (even closing the app doesnt seem to fix it)

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-07-07T19:50:42.707 daemon __main__                   : ERROR    Ping error
Traceback (most recent call last):
  File "chia/daemon/server.py", line 284, in ping_task
  File "aiohttp/web_ws.py", line 295, in ping
  File "aiohttp/http_websocket.py", line 676, in ping
  File "aiohttp/http_websocket.py", line 653, in _send_framea
  File "aiohttp/http_websocket.py", line 663, in _write
ConnectionResetError: Cannot write to closing transport
```

**Comment by wallentx** [comment]
Do you have a coredump, or screenshot of the error? For clarification, did the popup error show up in the Chia GUI, or was it some system message?

**Comment by 0xFuego** [comment]
It exits the app and shows a system message (Chia blockchain has stopped working). The gui then just hangs on reconnecting to daemon.
I saw it again today, but forgot to take a screenshot.

**Comment by wallentx** [comment]
This may duplicate https://github.com/Chia-Network/chia-blockchain/issues/12312

**Comment by 0xFuego** [comment]
managed to grab this:
![image](https://user-images.githubusercontent.com/108899879/180595716-98b32df1-2e91-4f4b-a75b-f0f9e4ac8cd3.png)

**Comment by 0xFuego** [comment]
![image](https://user-images.githubusercontent.com/108899879/180595733-9ad103d3-ff3f-4a3d-b8d4-e55362b6256a.png)
