### ISSUE TITLE
When opening Chia program, stuck on loading configuration

### ISSUE THREAD

**Issue by pipilu2022** [Chia-Network/chia-blockchain#12283]
### What happened?

chia 1.4.0, windows 10 , stuck on loading configuration . I try 2 different computers , the same problem , who can help me to sovle this problem??
![33](https://user-images.githubusercontent.com/101960047/177733537-7d0dd50d-75b6-412e-817f-ac0909eb7789.png)

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Hermes88** [comment]
same problem on macOS

**Comment by wallentx** [comment]
Are you running Hyper-V? Docker for Windows can cause Hyper-V to reserve ports that the Daemon needs. If you run `chia run_daemon` from the command line, it will output the daemon logs to stdout, which should show you more information that you might be able to share with us.
