### ISSUE TITLE
Needed consistency for error `Try sending a smaller amount`

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#12291]
In the interest of consistency - should this be the same error text as above

` f"Transaction of {amount} mojo would use more than {max_num_coins} coins. Try sending a smaller amount"`

_Originally posted by @emlowe in https://github.com/Chia-Network/chia-blockchain/pull/12261#discussion_r916356722_

**Comment by emlowe** [comment]
Moved to jira backlog tracking
