### ISSUE TITLE
[Bug]  NFT - settled offer still showing pending in my offers list

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#12297]
### What happened?

I submitted an offer for an NFT that was accepted via Dexie. I no longer see the NFT in my wallet which is expected, however the offer in my wallet still shows as "pending". 

screenshot of the pending offer for 0.95 XCH
<img width="1451" alt="Screen Shot 2022-07-08 at 10 33 00 AM" src="https://user-images.githubusercontent.com/93196638/178046457-bfe0e690-9fcf-4ab6-aff5-860127d2b08c.png">

Details of the pending offer 
<img width="1451" alt="Screen Shot 2022-07-08 at 10 34 47 AM" src="https://user-images.githubusercontent.com/93196638/178046472-d4385002-bdb8-408b-a686-4c66cfab4dbe.png">

NFT ID: nft1hkxf8q9ql26c5t3uy4u8xu9nverenvjx0majfzfwgrqu39hyn69s47523e
Spacescan: https://www.spacescan.io/xch/nft/nft1hkxf8q9ql26c5t3uy4u8xu9nverenvjx0majfzfwgrqu39hyn69s47523e

Offer blob that was accepted:
offer1qqph3wlykhv8jcmqvpsxygqqwc7hynr6hum6e0mnf72sn7uvvkpt68eyumkhelprk0adeg42nlelk2mpafsyjlm5pqpj3dhq0hkafum3qew8efaeznn0xhx2dpwt8ehscxxleml0fzwalaknlt9a2e4qzga7vxmxqa0z773t9alapuw0t0dsaqgtu4ke2u4h5lr5w8e5w3grm98ah7x7rtjpucwqvg55sgwt9mlks77elymk0r8pqhzuh87murmlwc9v7eme28mkthevmumnd8l3xqlhehxuuf3wnweqlam6lnmsl9967hkhjtf0cjrkd9xhvdlmwv0vzcrddq6r9s5tkrg5zx8yyf4hgyrxwsgxd6qdcfqd9a5zlf25ds0maa08cu80xsnahf3mf8hthruufl5g7vyfzkmm480uvf9uml8lp0m0vnrwtrcxk6uhn6xk53t3c8nrfauen0ww5l4twn4rj8pux8kun08wqhhnl9p20yrzg8zglwtxld8x6rer52amu2498h0tjew9ee4hunkyrku42z4eqzu06xs3lk3ysrg6r8lp806qxnhspvt03ns09les7ktzuastpmahdup4xh3m40j25ewfym4hux8ccuey70syevt6tlc0z3jff9q5z3d7n6e85hnkg9ny2anf245ezankfejkye27gen9uenfk9jk2mj229uenq2f5ea9ven4t9qe5kt4w956jk2wkfgkjknjd949atj6t9hg8drj27s5jmn7dfj4lfn7gws6glnt3wx95ajxfx58qn5e54n6rpjg0ej656ufwer6zsvpjqxanzckpdvyf0wmm9yhfv0lwedt7yhm3758mha6n5hfsk70cvmh9avwvau6kyxa36x0q5a2uz8xhzkgel855np8egly6n3fe9yzuj3t9dzj5rk4tfnf3yv5j3f93yj7de0f985ajfhf0xzs24fetyj6d9vf9r8qkn4ffqh5ljg07te8rdcgfhxzju907z6lga353xk89zs0krx89ufdetyz6n7tfxxtyt8hdsq9n8d35pftp48kxd3lp0rmxk4k5dqzt26ehc5htaf6avlzwm6g67haxhjd5waq9fcz0vefyupa3sr29t8q8a2n3f9kpnvpqhlm408a6stnmxh9ddllehxu5z4dhf7wandtvah3qjdl843tjan4awk73kjmsxca4ep5n4drcd668sm4qnw0xlm5hz8ds79zeacpmf8v8wa05409lf2se53patm308pcaa6z4hlzdw9hf3w0ekrc9zhdxmw4x4ur9zpe2cmgmhzazcd069s6lsf7aszc62l6wk93d087lamcjt4h27w7eze856r5advllk5055hucz4d0d0kruh26hnn67gp8g4v39u3hjrep5ut944stkyq5dnccvp0wh57rmuk255ktu2xysl8vhjpl6532k78gfdj7xhmauath50j6t9r77jq4l6mkfjvr564720evhuh3wqftzsd4r20llctrmnc50gn63egawgkasuxkcnvajm6shv9tulwew3mcx48q6k9ulx3608lzu6ycvfk8lqenj72cnvxtv254870t4etkv8m9d0h00kzmkpsf0mdjyfhkr95qc6zvqrs8xm8yqr8csrwqxsnz52gtcq8dtcg4gzfjn5vw8l7mle09zvjf7l6xwelr6we7kf7ldl4mlv3evak255angzjndp7fusdehhh62mpt9mxmzwwuu5c025cynmlt0tnxkuezxfp0e5v5wdlj5ldu9088yh4jlulw8mrw9lrecx4esglt3ha5l9axthj0sujyvql4hnex7keld0kdzytaz2gnalujfrx4vaa0y4trc03t745uw05edshthl2wcltklmkr4f997wwxq2ef8tp2klnuz9

### Version

1.4.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by trepca** [comment]
@esaung was this resolved with more recent versions?

**Comment by esaung** [comment]
not sure, that wallet db was blown away in testing, and I haven't been dealing with NFT trading recently. We can close this issue but keep an eye on this to see if this issue pops up again.
