### ISSUE TITLE
[Bug] NFT information cannot be synchronized in cli wallet

### ISSUE THREAD

**Issue by laozhang713** [Chia-Network/chia-blockchain#12307]
### What happened?

NFT information cannot be synchronized in cli wallet. NFT can be seen in the GUI, but there is only a standard wallet in cli without any NFT information. I want to know how to synchronize NFT information in cli.

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
Is the information that you are looking for more than what the CLI currently provides?
https://docs.chia.net/docs/13cli/did_cli
https://docs.chia.net/docs/13cli/nft_cli
You can also interface with DID and NFT information via the RPC
https://docs.chia.net/docs/12rpcs/did_rpcs
https://docs.chia.net/docs/12rpcs/nft_rpcs
