### ISSUE TITLE
[Bug] Melt-cast nft wallet, with the official light wallet can not be opened!

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#12304]
### What happened?

As long as a wallet that has been melted into NFT and contains a lot of works cannot be opened with an official light wallet, nor can it be opened for a few days of synchronization.
I've tried this on many accounts.
Windows.
Linux.
It is also unable to complete synchronization.

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
1.4.0以及1.4.1测试版
1.4.0 and 1.4.1 dev
```

**Comment by BernardJin** [comment]
您可以说中文，我负责翻译

**Comment by 0X1231** [comment]
> 您可以说中文，我负责翻译

熔铸过nft的轻钱包无法完成同步！

**Comment by Gbolahan657** [comment]
If you truly need help contact hackerdecon936@gmail.com
