### ISSUE TITLE
The balance of the wallet is displayed incorrectly

### ISSUE THREAD

**Issue by ard577** [Chia-Network/chia-blockchain#12309]
### What happened?

The balance of the wallet is displayed incorrectly, the receipts from the pool for three weeks have disappeared. Before that, they were displayed correctly. (from 6 June to 1 July).

![image](https://user-images.githubusercontent.com/109071262/178236493-e653a663-2089-40a1-9fc9-b1d5ec9e1bfd.png)

was adr:     xch1fs9ejekxqh2s502r7nt54dmv6z763yx0a3lxgk8vcpra95vq936skxp2vp

now adr:    xch1d603h8p2vty0fxf43zpswuwgvzsesmsc53h9v0vgrdxyzy8fcl7s6vwer6

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you seeing that your pool payout address is now set to xch1d603h8p2vty0fxf43zpswuwgvzsesmsc53h9v0vgrdxyzy8fcl7s6vwer6?
Can you also share a screenshot of the current state so that I can compare that to the screenshot that you've posted above?

**Comment by BrandtH22** [comment]
I recommend upgrading to 1.5.0 then note that you may need to increase your derivation index if that is a new wallet address.
