### ISSUE TITLE
[Bug] Can not send Chia from CLI

### ISSUE THREAD

**Issue by xulifan** [Chia-Network/chia-blockchain#12312]
### What happened?

Just updated to 1.4.0. from 1.2.X, but when I tried to send coin, it hangs on "Submitting transaction..." for about 5-10 minutes, then throw a exception and failed.:

(venv) lxu@chia:~$ chia wallet send  -a *** -t xch19nawxep6e5ng56nx8jqy7hlzf2r576eey6ltua3tv8ygph4f4q2qlcg2n4
Wallet keys:
1) * ************ (Synced)
2)   !!!!!!!!!!!!!!!!!!
Choose a wallet key [1-2] ('q' to quit, or Enter to use ************): 1
Submitting transaction...
Exception from 'wallet'

(venv) lxu@chia1:~$ chia wallet show
No keys loaded. Run 'chia keys generate' or import a key

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
Do you happen to have any debug logs surrounding this event? I've experienced this a few times on `main` recently (where I wasn't running debug level logging), but haven't seen it in 1.4.0.

**Comment by wallentx** [comment]
This may duplicate https://github.com/Chia-Network/chia-blockchain/issues/11175

**Comment by wallentx** [comment]
Closing this due to duplicate
