### ISSUE TITLE
[Bug] harvesters cant sync to node

### ISSUE THREAD

**Issue by bogidogi** [Chia-Network/chia-blockchain#12354]
### What happened?

after i upgrade my chia 1.3.5 to 1.4.0 , im getting this error.

proof search time is going to 30-40 seconds , about 1-2 later it will be fine on node and harvesters.

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
harvester---

harvester chia.plot_sync.sender   : INFO     _send_next_message didn't receive response expected_message_type: plot_sync_loaded, expected_identifier: {'message_id': 3799, 'sync_id': 1657727243, 'timestamp': 1657727971}, message None

node ----

farmer chia.plot_sync.receiver    : WARNING  _process: node_id 49a83d61b4e62f7315edd8e7071e2d2b95826169d895b76b7dc6ad681e085386, InvalidIdentifierError Invalid identifier: Actual {'message_id': 3795, 'sync_id': 1657727240, 'timestamp': 1657727971}, Expected {'message_id': 3797, 'sync_id': 1657727240, 'timestamp': 1657727971}
```

**Comment by wallentx** [comment]
Are you using a remote harvester, and if so, did you also update the remote harvester to 1.4.0?
Did you see this error just once, and then it resolve and operate as normal?

**Comment by bogidogi** [comment]
> Are you using a remote harvester, and if so, did you also update the remote harvester to 1.4.0? Did you see this error just once, and then it resolve and operate as normal?

im okey right now , after i change my batch_size to 300 , it is working
