### ISSUE TITLE
Trying to accept an NFT offer for CAT throws error unless you first send 500 CATs to yourself

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#12359]
### What happened?

This issue comes by way of a Twitter thread where user `@kimsk` was trying to purchase an NFT from `@endertown` for 1,000 `CATMOS`, but was getting an Error in the GUI when clicking to accept. 
https://twitter.com/hoffmang/status/1546677026081292288?s=20&t=u50T5xr17RARiZHgcSaAcg

@hoffmang9 replied implying that he too was having the issue with `@endertown`'s offers, and apparently the workaround was that the person buying needed to first send 500 `CATMOS` to themselves in order for the offer to be accepted.

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by hoffmang9** [comment]
Confirming both having the issue and the work around working for me.

**Comment by joshpainter** [comment]
More info: these NFTs have a 50% royalty so total price would actually be 1500 CATMOS.

This was a total guess on my part after getting a similar error myself during testing with a new wallet. I transferred 2000 CATMOS into the new wallet and then tried to accept my offer for the NFT and got the error mentioned in thread. I looked through debug logs and saw something about "coin selection" around the errors IIRC (didn't save log, sorry). My guess was that code was trying to select one coin to pay for the NFT and another to send the royalty? To test my theory I sent 500 CATMOS to myself to split the single 2000 CATMOS coin into 1500 and 500. I was then able to accept the offer successfully without error, but I still didn't know if it was really "the workaround" or if it was just a transient error until several other users including @hoffmang9 validated it.

Hope that helps!

**Comment by hoffmang9** [comment]
I had two coins of 1000 CATMOS each before forcing the split with a 500 self transaction

**Comment by joshpainter** [comment]
Interest, the plot thickens!

**Comment by jack60612** [comment]
I am assuming there is some weird coin selection issue where the coins are not being split??

**Comment by jack60612** [comment]
Ill look at the code now

**Comment by jack60612** [comment]
Sorry for the delay, i have been busy. Linking PR that resolves this now!
