### ISSUE TITLE
[Bug] wallet balance incorrect (cli linux)

### ISSUE THREAD

**Issue by Maldiniiii** [Chia-Network/chia-blockchain#12428]
### What happened?

the wallet balance is not displayed correctly (since version 1.3.5).

I farm on 2 pools (payments are made to 2 different addresses).

the total on these two addresses differs from my wallet.

### Version

1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
Are you seeing that your wallet is not showing the transactions from your pool payouts? This may just be that your wallet has missed some transactions. If you are interested, you can try to run `main`, where we have some changes that should help fill in missing transactions.

**Comment by Maldiniiii** [comment]
yes my wallet is not showing the correct amount from my pool payouts.
I think it was the change from 1.3.4 to 1.3.5 when the error appeared.
suddenly the wallet showed less than before.

how can i try "main"?

**Comment by wallentx** [comment]
You can try one of the "Latest Dev" builds from the downloads page https://chia.net/download/
