### ISSUE TITLE
[BUG] Chia RC5 causes MacOS 10.15.7 to restart

### ISSUE THREAD

**Issue by russ-tolman** [Chia-Network/chia-blockchain#1245]
Panic(CPU 2, time 374883550054825): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff80adf06570, spinlock owner: 0xffffff80b7117000, current_thread: 0xffffff80b7117000, spinlock_owner_cpu: 0x2
RAX: 0xffffff80bc31e000, RBX: 0xffffff80ae612c88, RCX: 0x00000000000000e0, RDX: 0x0009701100000000
RSP: 0xffffffa7859d3a70, RBP: 0xffffffa7859d3ab0, RSI: 0xffffff80b7117000, RDI: 0xffffff80ae612c88
R8:  0xffffffa7859d3c30, R9:  0xffffff800876b2e0, R10: 0x0000000000ffffff, R11: 0xffffff80bbab2a00
R12: 0xffffff80b7117000, R13: 0x0000000000000000, R14: 0x000970121d125c8e, R15: 0xffffff80bc31e000
RFL: 0x0000000000000093, RIP: 0xffffff800872afb0, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 2), Frame : Return Address
0xffffff873d7e4f80 : 0xffffff8008845dfb 
0xffffff873d7e4fd0 : 0xffffff80086c0bed 
0xffffffa7859d3ab0 : 0xffffff800872b154 
0xffffffa7859d3ae0 : 0xffffff8008769aa0 
0xffffffa7859d3b00 : 0xffffff800876b319 
0xffffffa7859d3bb0 : 0xffffff800876b821 
0xffffffa7859d3c20 : 0xffffff800876a944 
0xffffffa7859d3ce0 : 0xffffff800876e638 
0xffffffa7859d3d20 : 0xffffff8008c50a44 
0xffffffa7859d3d40 : 0xffffff8008c50b2e 
0xffffffa7859d3d80 : 0xffffff8008ca67ed 
0xffffffa7859d3db0 : 0xffffff8008ca7253 
0xffffffa7859d3e20 : 0xffffff8008ca14a0 
0xffffffa7859d3ee0 : 0xffffff8008ca1260 
0xffffffa7859d3f40 : 0xffffff8008d84be7 
0xffffffa7859d3fa0 : 0xffffff80086c1206 

BSD process name corresponding to current thread: Chia Helper (Ren

Mac OS version:
19H2

Kernel version:
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Kernel UUID: 05D51A3D-3A87-3FF0-98C3-9CF3827A3EDD
Kernel slide:     0x0000000008400000
Kernel text base: 0xffffff8008600000
__HIB  text base: 0xffffff8008500000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 374883550089065
last loaded kext at 238422681656459: >!UMergeNub	900.4.2 (addr 0xffffff7f8b230000, size 12288)
loaded kexts:
com.avg.PacketForwarder	2.1
com.avg.FileShield	4.0.0
com.Cycling74.driver.Soundflower	2
com.uaudio.driver.UAFWAudio	4.3.1 47542
com.kairos.driver.DuetDisplay	1
com.uaudio.driver.UAD2System	9.13.0
@filesystems.smbfs	3.4.4
@filesystems.exfat	1.4
@kext.AMDFramebuffer	3.1.0
@kext.AMDRadeonServiceManager	3.1.0
@kext.AMDRadeonX4000	3.1.0
>!AUpstreamUserClient	3.6.8
>!AGraphicsDevicePolicy	5.2.6
>!AMCCSControl	1.14
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	5.2.6
>AudioAUUC	1.70
>AGPM	111.4.4
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
>!AHDAHardwareConfigDriver	283.15
>!AHDA	283.15
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.6f7
>!AMGPUPowerControl	5.2.6
>ACPI_SMC_PlatformPlugin	1.0.0
>!AThunderboltIP	3.1.4
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>eficheck	1
@kext.AMD7000!C	3.1.0
>!ALPC	3.1
>!A!ISlowAdaptiveClocking	4.0.0
>!AFIVRDriver	4.1.0
>!A!IMCEReporter	115
|IO!BUSBDFU	7.0.6f7
|SCSITaskUserClient	422.120.3
>!U!SCoexistentDriver	489.120.1
>!AFileSystemDriver	3.0.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.141.1
>!AAHCIPort	341.140.1
>AirPort.BrcmNIC	1400.1.1
@private.KextAudit	1.0
|!ABCM5701Ethernet	10.3.5
>!AACPIEC	6.1
>!AACPIButtons	6.1
>!AHPET	1.8
>!ARTC	2.0
>!ASMBIOS	2.1
>!AAPIC	1.7
>!A!ICPUPowerManagementClient	222.0.0
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
>!A!ICPUPowerManagement	222.0.0
|EndpointSecurity	1
>!UMergeNub	900.4.2
>!A!BHIDKeyboard	209
>IO!BHIDDriver	7.0.6f7
>!AHIDKeyboard	209
@kext.AMDRadeonX4030HWLibs	1.0
|IOAccelerator!F2	438.7.3
@kext.AMDRadeonX4000HWServices	3.1.0
>!ASMBus!C	1.0.18d1
@kext.triggers	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IOFireWire!F	4.7.5
|IOAVB!F	850.1
>!ABacklightExpert	1.1.0
>!AGraphicsControl	5.2.6
|IONDRVSupport	576.1
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>!ASMBusPCI	1.0.14d1
>!AHDA!C	283.15
|IOHDA!F	283.15
@!AGPUWrangler	5.2.6
@kext.AMDSupport	3.1.0
@!AGraphicsDeviceControl	5.2.6
|IOGraphics!F	576.1
>IOPlatformPlugin!F	6.0.0d8
>!AThunderboltEDMSink	4.2.3
>!AThunderboltDPOutAdapter	6.2.6
|IOSlowAdaptiveClocking!F	1.0.0
@plugin.IOgPTPPlugin	840.3
|Broadcom!BHost!CUSBTransport	7.0.6f7
|IO!BHost!CUSBTransport	7.0.6f7
|IO!BHost!CTransport	7.0.6f7
|IO!B!F	7.0.6f7
|IO!BPacketLogger	7.0.6f7
>usb.IOUSBHostHIDDevice	1.2
|IOUSBMass!SClass	4.0.4
>!UAudio	323.4
>usb.!UHub	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
>!AXsanScheme	3
|IOAHCI!F	290.0.1
|IO80211!F	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
|IOEthernetAVB!C	1.1.0
>mDNSOffloadUserClient	1.0.1b8
|IONVMe!F	2.1.0
>usb.!UEHCIPCI	1.2
>usb.!UEHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IOSMBus!F	1.1
>!AEFINVRAM	2.1
|IOHID!F	2.0.0
>!AEFIRuntime	2.1
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.140.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
panic(cpu 0 caller 0xffffff800883baa0): "Spinlock acquisition timed out: lock=0xffffff80adf06570, lock owner thread=0xffffff80b7117000, current_thread: 0xffffff80bc31e000, lock owner active on CPU 0x2, current owner: 0xffffff80b7117000, time: 374883550115756"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2/osfmk/i386/locks_i386.c:501
Backtrace (CPU 0), Frame : Return Address
0xffffff871cf97af0 : 0xffffff800871a65d 
0xffffff871cf97b40 : 0xffffff8008854a75 
0xffffff871cf97b80 : 0xffffff80088465fe 
0xffffff871cf97bd0 : 0xffffff80086c0a40 
0xffffff871cf97bf0 : 0xffffff8008719d27 
0xffffff871cf97cf0 : 0xffffff800871a117 
0xffffff871cf97d40 : 0xffffff8008ec1a6c 
0xffffff871cf97db0 : 0xffffff800883baa0 
0xffffff871cf97df0 : 0xffffff8008738f5a 
0xffffff871cf97e30 : 0xffffff8008738e7c 
0xffffff871cf97e60 : 0xffffff800876545c 
0xffffff871cf97f20 : 0xffffff8008833807 
0xffffff871cf97f60 : 0xffffff800884e663 
0xffffff871cf97f80 : 0xffffff8008845dfb 
0xffffff871cf97fd0 : 0xffffff80086c0bed 
0xffffffa754ef3da0 : 0xffffff800876e431 
0xffffffa754ef3e00 : 0xffffff8008ca3349 
0xffffffa754ef3f00 : 0xffffff8008ca2456 
0xffffffa754ef3f40 : 0xffffff8008d84be7 
0xffffffa754ef3fa0 : 0xffffff80086c1206 

BSD process name corresponding to current thread: Chia Helper (Ren

**Then after I rebooted and was opening Chia, I got:**

**A JavaScript error occurred in the main process**
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at createWindow (/Applications/Chia.app/Contents/Resources/app.asar/src/electron-starter.js:62:18)
    at App.<anonymous> (/Applications/Chia.app/Contents/Resources/app.asar/src/electron-starter.js:164:7)
    at App.emit (events.js:315:20)

Now Chia is taking forever to connect to Wallet

**Comment by hoffmang9** [comment]
Please try RC7 https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0rc7
