### ISSUE TITLE
Balance not updating

### ISSUE THREAD

**Issue by dkackman** [Chia-Network/chia-blockchain#125]
I have been running alpha's sine 1.3. With the most recent move to the 1.5 code, my chia balance (as reported by the SSH client) has not updated. I've run 1.5 for about a week now and my winnings are at the same value.

(Running on WSL)

**Comment by hoffmang9** [comment]
We just release a 1.5.1 bug fix release for this. Harvester was broken.

https://github.com/Chia-Network/chia-blockchain/releases/tag/alpha-1.5.1
