### ISSUE TITLE
[BUG] macOS won't connect to Wallet

### ISSUE THREAD

**Issue by russ-tolman** [Chia-Network/chia-blockchain#1250]
am on Catalina 10.15.7 and Wallet will not connect today. I rebooted a couple times and reinstalled Chia, but still no Wallet connection. Ideas?

**Comment by danra** [comment]
Same issue. On Big Sur

**Comment by hoffmang9** [comment]
Please try RC7 https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0rc7
