### ISSUE TITLE
[Bug] Loading keyring status

### ISSUE THREAD

**Issue by Campanulata** [Chia-Network/chia-blockchain#12519]
### What happened?

Loading keyring status all the time

### Version

Chia-intel_latest_dev 1.4.1.dev345

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
i can't find it
```

**Comment by wallentx** [comment]
Are you running Mojave 10.14? If so, we only provide installers for Catalina 10.15 and higher.
You are still able to install this from source - https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#MacOS
