### ISSUE TITLE
[BUG] Exception while fetching alert

### ISSUE THREAD

**Issue by cameroncooper** [Chia-Network/chia-blockchain#1252]
**Describe the bug**
Running dev (53c31ef) there seems to be a periodic issue fetching the alert. My logs show a successful fetch every two seconds as expected, then occasionally there is a 5 minute delay followed by an exception. After the exception the successful fetches resume until the next 5 minute delay delay and exception. Here's a snippet from my debug log:

16:54:46.423 daemon __main__                   : INFO     Network is not ready yet
16:54:49.014 daemon __main__                   : INFO     Network is not ready yet
16:54:51.856 daemon __main__                   : INFO     Network is not ready yet
16:59:54.679 daemon __main__                   : ERROR    Exception while fetching https://download.chia.net/notify/testnet_6_alert.txt, exception:
16:59:57.392 daemon __main__                   : INFO     Network is not ready yet
17:00:00.148 daemon __main__                   : INFO     Network is not ready yet
17:00:02.829 daemon __main__                   : INFO     Network is not ready yet
17:00:05.527 daemon __main__                   : INFO     Network is not ready yet
17:00:08.211 daemon __main__                   : INFO     Network is not ready yet
17:00:10.865 daemon __main__                   : INFO     Network is not ready yet
17:05:13.671 daemon __main__                   : ERROR    Exception while fetching https://download.chia.net/notify/testnet_6_alert.txt, exception:
17:05:16.401 daemon __main__                   : INFO     Network is not ready yet
17:05:18.988 daemon __main__                   : INFO     Network is not ready yet
17:05:21.735 daemon __main__                   : INFO     Network is not ready yet
17:05:24.318 daemon __main__                   : INFO     Network is not ready yet

**To Reproduce**
No specific steps cause this to happen other than starting the gui.

**Expected behavior**
Expected "Network is not ready yet" messages every 2 seconds

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu
- CPU: i7

**Comment by hoffmang9** [comment]
Known. WONTFIX. 😉
