### ISSUE TITLE
[Bug] Wallet never completes synchronization

### ISSUE THREAD

**Issue by santivu** [Chia-Network/chia-blockchain#12524]
### What happened?

Hi,

probably due to my "personal dust storm", receiving tons of vey small transacctions in my wallet during a few months, now I'm getting some issues trying to move xch from my farming wallet to a new one, and also impossible to get synchro in a powerful computer.

I'm trying to configure a light wallet into a brand new PC, with a Ryzen 5950x and 2x980 Pro M2 and the syncho process neves completes. When arriving to the current wallet height, it starts again forever

![wallet](https://user-images.githubusercontent.com/88079415/180238850-b9aeced8-e5df-4bd6-bb44-0fd7dbb3b487.png)
![screen](https://user-images.githubusercontent.com/88079415/180238871-16457f6d-5396-4255-b920-011308c60e9f.png)
.

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
Are you able to try to try the latest Dev build for Windows - https://download.chia.net/latest-dev/ChiaSetup-latest-dev.exe
We have improved syncing code in our Dev builds that should greatly improve wallet sync speed. If you try this, please let us know how this works out.

**Comment by santivu** [comment]
Hi William,

Thanks for your reply.
I was trying with dev version, last Monday, with similar results.
Just to try something different…
Would be better to syncro from scratch, deleting the wallet folder (ir takes in my case almost 2 days), or keeping a recent db?
Thanks again,



-Santi

**Comment by santivu** [comment]
BTW, just downloaded the latest dev version and tried with mi current wallet, near the curent height.It starts well but after a couple of minutes, it sucks and crash.    -Santi De: William AllenEnviado: jueves, 21 de julio de 2022 19:59Para: Chia-Network/chia-blockchainCC: santivu; AuthorAsunto: Re: [Chia-Network/chia-blockchain] [Bug] Wallet never completes synchronization (Issue #12524) Are you able to try to try the latest Dev build for Windows - https://download.chia.net/latest-dev/ChiaSetup-latest-dev.exeWe have improved syncing code in our Dev builds that should greatly improve wallet sync speed. If you try this, please let us know how this works out.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by santivu** [comment]
Hi again, Today, downloaded the dev 1352 and got a new error.    -Santi De: santi vEnviado: viernes, 22 de julio de 2022 9:58Para: Chia-Network/chia-blockchainAsunto: RE: [Chia-Network/chia-blockchain] [Bug] Wallet never completes synchronization (Issue #12524) BTW, just downloaded the latest dev version and tried with mi current wallet, near the curent height.It starts well but after a couple of minutes, it sucks and crash.    -Santi De: William AllenEnviado: jueves, 21 de julio de 2022 19:59Para: Chia-Network/chia-blockchainCC: santivu; AuthorAsunto: Re: [Chia-Network/chia-blockchain] [Bug] Wallet never completes synchronization (Issue #12524) Are you able to try to try the latest Dev build for Windows - https://download.chia.net/latest-dev/ChiaSetup-latest-dev.exeWe have improved syncing code in our Dev builds that should greatly improve wallet sync speed. If you try this, please let us know how this works out.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wallentx** [comment]
If you are running our dev builds, you will need to run the wallet in "Farming" mode. The faster syncing code from the dev builds require the wallet to be connected to a trusted full node that is running that same code.

**Comment by santivu** [comment]
Hi,

Still I have the same issues as described in https://github.com/Chia-Network/chia-blockchain/issues/12585

Thanks



-Santi

**Comment by santivu** [comment]
Hi,

you were right. Using a PC as light wallet mode is not functional. Never completes synchronization.

Using the GUI as full node, finally completes the synchoniztion, after around 28 hours.
Any option to get a best speed?

Also I need to perform transactions from CLI, as from the GUI all crashes.

Thanks

**Comment by Gbolahan657** [comment]
If you truly need help contact hackerdecon936@gmail.com

**Comment by wallentx** [comment]
Our next release will include the best syncing speeds that we have had so far, but we are still working on things to make everything fast and stable. Fortunately, you should only need to do the larger sync just once, as long as you allow your wallet to stay relatively up to date with the block height.

I will report to our team about the transactions crashing in the GUI

**Comment by paninaro** [comment]
> Also I need to perform transactions from CLI, as from the GUI all crashes.

Do you have any info you can share regarding how the GUI is crashing? If possible, a screen recording would be helpful. As currently reported, there's nothing actionable for us to look into.

**Comment by santivu** [comment]
I tried again to perform 2 transactions from the GUI (using now 1.4.0 and also 1.5.1) and the crash disappear. Now after 1-2 seconds I get the normal pop-up with the confirmation message.
Many thanks for the recent improvements.
The only complicate pending stuff is the huge size of the wallet and the time for a full synchronization in a new machine.

**Comment by santivu** [comment]
Thanks for including solutions of these issues in 1.6.0!!!!
You are so responsive.
Good job!!!

**Comment by emlowe** [comment]
Please let us know if the dust filtering in 1.6.0 resolves this issue for you. Marking issues closed as we believe the dust filtering in 1.6.0 will result in wallets being able to sync by ignoring the majority of dust.

**Comment by santivu** [comment]
Hi guys,After installing 1.6.0 and use it during some weeks, I’ve been winning blocks, moving from wallet to wallet and operating without any issue now.The only thing I didn’t test is to make a conplete synchronization of the wallet, in a new machine. But I assume must work much better than before and ignoring the dust.Many thanks for fixing this. It was really annoying.Have a nice weekend,-SantiEl 21 sept 2022, a las 18:10, Earle Lowe ***@***.***> escribió:﻿
Please let us know if the dust filtering in 1.6.0 resolves this issue for you. Marking issues closed as we believe the dust filtering in 1.6.0 will result in wallets being able to sync by ignoring the majority of dust.
