### ISSUE TITLE
CH21 missing

### ISSUE THREAD

**Issue by Phidan** [Chia-Network/chia-blockchain#12609]
Hi there,

After updating to version 1.5.0 the CH21 balance is showing  0 and the previous transactions are deleted. Is anyone elese facing the same issue?

**Comment by Jsewill** [comment]
They did say something about reissuing CAT1 CATs. :man_shrugging:

**Comment by shaneo257** [comment]
its detailed here
https://www.chia.net/2022/07/25/upgrading-the-cat-standard.en.html
