### ISSUE TITLE
[Bug] 1.5.0 pooling Show exception

### ISSUE THREAD

**Issue by Concord-us** [Chia-Network/chia-blockchain#12607]
### What happened?

![1658868113778](https://user-images.githubusercontent.com/97425684/181108133-a17c0fc6-c201-4ca4-b590-76e98b657041.png)

### Version

1.5.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
1.5.0 does a wallet resync - this should resolve once that is complete.

**Comment by 0X1231** [comment]
> 1.5.0 会重新同步钱包 - 一旦完成，这应该会解决。
需要删除数据库重新同步就好了！
