### ISSUE TITLE
[BUG] chia keys add -m 24words ::: Not Working

### ISSUE THREAD

**Issue by tony-clark-fc** [Chia-Network/chia-blockchain#1261]
**Describe the bug**
After upgrading to rc6, tried to add keys using "chia keys add -m 24words".  Received output "Error: no such option: -m

**To Reproduce**

Upgrade to rc6 and follow install instructions in Wiki

**Expected behavior**
As per the process I followed for each upgrade, this command has always worked.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: Rpi 4

**Additional context**

**Comment by hoffmang9** [comment]
Per the release notes, you know have to give the mnemonic on stdin. Just type chia keys add then hit return and enter your words

**Comment by tony-clark-fc** [comment]
My bad... I'll study the release notes next time
