### ISSUE TITLE
[Bug] nft_mint_nft RPC expects edition_number/edition_total while wallet_rpc_client is sending series_number/series_total

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#12634]
### What happened?

During the naming NFT minting fix for series --> edition, a mismatch between expected/sent params was introduced:

wallet_rpc_client.py is sending the request as:
```
        request: Dict[str, Any] = {
            ...
            "series_number": edition_number,
            "series_total": edition_count,
            ...
        }
```

While wallet_rpc_api.py is expecting:

```
        metadata_list = [
            ...
            ("sn", uint64(request.get("edition_number", 1))),
            ("st", uint64(request.get("edition_total", 1))),
        ]
```

The result is that 1.5.0 mints NFTs with a hardcoded edition count of 1 and edition number of 1

### Version

1.5.0

### What platform are you using?

macOS

### What ui mode are you using?

CLI

**Comment by DrakoPensulo** [comment]
"Error: no such option: -e" when executing the command "chia wallet nft mint .... " with -en/-et parameters. Minting is possible when -sn/-st parameters used instead, with the expected warning message "WARNING: Series total(-st) and number(-sn) options are *deprecated*, please use -en and -ec."
