### ISSUE TITLE
[Bug] Harvester disconnects after 300,000+ points found since start 

### ISSUE THREAD

**Issue by 2411TrollFarmer** [Chia-Network/chia-blockchain#12647]
### What happened?

A few days ago when I hit around 306,000 points found (seen in Chia GUI pooltab) from start my harvester dropped connection with my full node as it was no longer showing in farming or plots tab. Thinking this was an issue with my harvester I went ahead and closed CHIA (CLI used on harvester)  and reopened it. I ran back to my full node (gui) and went to the plots tab to see if my harvester would show up. After seeing the harvester pop in there was a bar and I think text saying it was loading plots. This bar however and text stalled at 2%. I ran back to the harvester and closed and reopened Chia again. On my full node the text was stalled at 23% and not loading at all. I then proceeded to shutdown my harvester and turned it back on and the same results happened.  Next I went ahead and closed the Chia GUI on full node and reopened and the issue was resolved. 

7/2//2022
The harvester disconnected again and this time its was around the 345,000 points found since start. I noticed this since my Space Pool dashboard showed a decent drop in size. On my full node I do recall seeing my hddcoin client dropped several tb. Looking on the Space Pool website my farm was dropping considerable amounts during the night.  I restarted Chia on my Full node and harvester this morning and its running and slowly building back up. I have provided some screenshots and logs as well. 

* I will make sure next time I Hit around 300,000 points found since start I have clean logs for around the 300,000 if this does disonnect.

This is when the harvester disconnected around 
![123](https://user-images.githubusercontent.com/110186435/181584459-f14c5ff6-d6f2-4cef-b3cd-4b7f765448bc.JPG)

The circled item is the harvester that disconnects 
![exampel 1](https://user-images.githubusercontent.com/110186435/181584726-ba46ba7d-1ec4-4a01-9682-8d03b51535a2.JPG)

Last 2 is size dropping a ton
![saddsa](https://user-images.githubusercontent.com/110186435/181584803-4c457448-e84e-42e0-aa59-98980567a1c6.JPG)

![SmartSelect_20220728-091637_Space Pool - Chia Farming](https://user-images.githubusercontent.com/110186435/181584849-bf5e554e-457a-4e32-8c4f-08db9366a972.jpg)

Logs from Full node and the disconnecting harvester 
[Chia Logs.zip](https://github.com/Chia-Network/chia-blockchain/files/9212437/Chia.Logs.zip)

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by xdustinface** [comment]
Is the harvester also on 1.4? There was an issue (https://github.com/Chia-Network/chia-blockchain/pull/11481) in versions <1.4 where the harvester wouldn't reconnect.

**Comment by 2411TrollFarmer** [comment]
> Is the harvester also on 1.4? There was an issue (#11481) in versions <1.4 where the harvester wouldn't reconnect.

The harvester is indeed on 1.4.0 . I knew that disconnect issue was happening on 1.3.x and I think was fixed on 1.4.0

**Comment by xdustinface** [comment]
Can you let me know your plot refresh parameter?

**Comment by 2411TrollFarmer** [comment]
On both config.yaml it's 

plots_refresh_parameter:
    batch_size: 300
    batch_sleep_milliseconds: 1
    interval_seconds: 120
    retry_invalid_seconds: 1200

**Comment by xdustinface** [comment]
Ok, sorry the the late reply :) I checked your logs but it seems like the times of the logs do not match. Like in the "Full Node Log" there is no entry where the harvester disconnected. Did this happen again since then?

**Comment by 2411TrollFarmer** [comment]
I have seen the response. I am currently waiting to hit around 300,000 points  before  start the log collections for fullnode and harvester. thanks for keeping this open

**Comment by 2411TrollFarmer** [comment]
This issue seems to have resolved itself. I am at 450,000 points found since start. No harvesters dropping. Thanks for your concern.
