### ISSUE TITLE
[Bug] Sharing offers to Offerpool times out in 1.5.0 GUI

### ISSUE THREAD

**Issue by jussipvainionpaa** [Chia-Network/chia-blockchain#12640]
### What happened?

Trying to share an offer to Offerpool.io from Chia GUI in the Offers tab and receiving this error:
![image](https://user-images.githubusercontent.com/81168697/181377236-6385a597-55d0-4544-89ac-c3b54b101e08.png)

### Version

1.5.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
This is a general network error - suggest you contact OfferPool. During the CAT2 upgrade time, many of the DEXs had some downtime.
