### ISSUE TITLE
[Bug] Chia wallet get_address <--new-address/--latest-address> is buggy in CLI and GUI

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#12667]
### What happened?

**On the Windows GUI:**
The refresh receive address button does not refresh the address at all, on any of the views where you should be able to show a new receive address. The GUI is forever stuck with the address `xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4`

There is also odd behavior on the CLI for both Windows and Linux. On Windows, the `--latest` address is always `xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4`, just like the GUI, but on Linux, it was a completely mixed bag of results..

**Windows CLI:**
```
⮞  chia wallet get_address -l
xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4
⮞  chia wallet get_address -n
xch1z7uu6l6kfvh2tqtejajparj4z7s4qu42xmj5qrzkeysjs0wdtp0sf0ggnd
⮞  chia wallet get_address -l
xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4
⮞  chia wallet get_address -n
xch1xuy6t5rm8a78950yzwc6d0frwfwg7e45u7d33fvlxulx48r8ltxs02eyg0
⮞  chia wallet get_address -n
xch17ksh7hlaet4drfmdgt3f90fgawrt0gvudh6qy474zpaz5vrdfh5qv7xufd
⮞  chia wallet get_address -n
xch18n9ny7tkt4vevy8gml6zt82ptynp63h5aqprnd6rphjhe9837ufqnftwzz
⮞  chia wallet get_address -n
xch1td6vp68dn4njdslz4mdkgyv34gsj2yqs28v6p2d5nn9ptwa8cyzqtk7280
⮞  chia wallet get_address -l
xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4
```

**Linux CLI:**
```
~ > chia wallet get_address -l
xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4
~ > chia wallet get_address -n
xch1u2cxpykc9spv0tug9kg7h4lxxfem9zl54rf5fac7jpkgmghq7pjs375wc3
~ > chia wallet get_address -l
xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4
~ > chia wallet get_address -n
xch17d64m6xxrkmy8evjhk9dvsmzlmfmxhs8sjhn8dt607g6l9xjxu4s426vm4
~ > chia wallet get_address -n
xch1f6279dapxdfu3jfvwyzlcggat5370kketjy536rxz3lj0xk92d0qahps3m
~ > chia wallet get_address -l
xch1f6279dapxdfu3jfvwyzlcggat5370kketjy536rxz3lj0xk92d0qahps3m
~ > chia wallet get_address -n
xch13mjnc0e24cxjfxc86dvs6lqkm25n6h7z3kxpyhu4aw6t7c30f9ascc452c
~ > chia wallet get_address -n
xch12y3mgxn3d2t56gjp09t7sv7yvkm0ja076vwq69mgteklk0wgkaqqtg3pv6
~ > chia wallet get_address -l
xch12y3mgxn3d2t56gjp09t7sv7yvkm0ja076vwq69mgteklk0wgkaqqtg3pv6
```

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by mariano54** [comment]
If anyone has seen these bugs, please provide detailed instructions on how to replicate it. 
I have never seen it and thus I can't fix it.

**Comment by shaneo257** [comment]
![image](https://user-images.githubusercontent.com/36589806/181723381-be29cfbd-9a1e-4f7e-9023-7306be3e5d8e.png)
if i go to Tokens, Chia, Receive and click on `New Address` nothing happens

**Comment by shaneo257** [comment]
![image](https://user-images.githubusercontent.com/36589806/181723625-715648f0-7167-4c21-9116-44401d36e977.png)
have received 3 transactions into the wallet since it was originally reported, this is on windows

**Comment by mariano54** [comment]
Can you try with a new key?
Can you try on CLI?

**Comment by shaneo257** [comment]
![image](https://user-images.githubusercontent.com/36589806/181726269-40e5b455-f53d-4127-984a-ebb3a7eea7e8.png)

**Comment by emlowe** [comment]
I'll note on macOS I was not able to reproduce - I wonder if the GUI just isn't refreshing the view.

**Comment by oiG8Uchi** [comment]
I also have the same problem. The GUI cannot get the new address. The new address can be obtained from the CLI, but there is still no change after running chia wallet get_address PS: My private key is generated in chia1.0；chia 1.4have no such problem

**Comment by avsync** [comment]
I'm experiencing the same issue in the windows 1.5 gui. I tried multiple wallets that existed pre 1.5 and they don't generate a new receive address when using the 'new address' button on the tokens tab or the new address icon on the NFTs tab. I generated a brand new wallet and that works without issue.

**Comment by shaneo257** [comment]
can confirm on 1.5.1414 i am able to generate a new receiving address in the windows gui

**Comment by avsync** [comment]
Seconded, new address working correctly in 1415.
