### ISSUE TITLE
has timed out 600 seconds[Bug] 

### ISSUE THREAD

**Issue by zhangyongchang88** [Chia-Network/chia-blockchain#12728]
### What happened?

![image](https://user-images.githubusercontent.com/70252155/182148858-71afd583-3cb5-4046-ae57-651beab27521.png)

### Version

1.4.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by zhangyongchang88** [comment]
我的账户曾经遭受过沙尘暴攻击，钱包显示我有48.109967820062 XCH我需要发送48个xch到另一个地址，我填写了0.00001free，等待好久就会发生错误提示。

**Comment by zhangyongchang88** [comment]
![image](https://user-images.githubusercontent.com/70252155/182163166-a82fa7d1-0363-44f9-83ad-99eb91469abc.png)
这是被沙尘暴袭击过的地址。有180000+记录

**Comment by wallentx** [comment]
This should be fixed in 1.5.0. Can you try to upgrade and let us know if this fixes the problem? You may just have to try the transaction multiple times.

**Comment by zhangyongchang88** [comment]
我升级后解决问题了。
