### ISSUE TITLE
Status Waiting for network to launch[BUG]

### ISSUE THREAD

**Issue by Sutejm** [Chia-Network/chia-blockchain#1273]
**Describe the bug**

**Expected behavior**
After installing new Release note: Usually after opening the application status normaly starts to syc all my plots and however now I am getting Status - Waiting for network to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/80568417/111022473-ded3ff80-83ca-11eb-93e1-5b391ee61e49.png)
![issue](https://user-images.githubusercontent.com/80568417/111022491-f4e1c000-83ca-11eb-861e-7227be224a2f.png)

**Desktop (please complete the following information):**

- OS: Windows
- CPU:  Intel(R) Xeon(R) E-2286G CPU @ 4.00GHz   4.01 GHz

**Additional context**

**Comment by mariano54** [comment]
From the #announcements channel on keybase:

There seems to be a bug effecting Windows. To work around edit C:\Users\USERNAME\.chia\testnet\config\config.yaml and change testnet6: GENESIS_CHALLENGE: null to GENESIS_CHALLENGE: e0c271a9db2870e650a3634c58b52015c616ed90f1d47853cbbcd158df51a969

If you are using the Mac installer it is the same workaround but - Edit /Users/USERNAME/.chia/testnet/config/config.yaml and change testnet6: GENESIS_CHALLENGE: null to GENESIS_CHALLENGE: e0c271a9db2870e650a3634c58b52015c616ed90f1d47853cbbcd158df51a969
And then restart the application

**Comment by Sutejm** [comment]
Thank you. That has worked 👍
