### ISSUE TITLE
Full Node not working after installing 1.5

### ISSUE THREAD

**Issue by krashbandit78** [Chia-Network/chia-blockchain#12746]
Never had any issues running Chia client, but after the forced download of update 1.5 I can no longer get synced up...I saw where people deleted their DB file and then redownloaded the whole file, so I tried that.  It was doing fine, but around 1.5M block, it just stopped.  I've restarted, checked firewall, restarted again, run as administrator, etc. Any thoughts?

Running Win10, Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz   1.61 GHz, 32GB RAM, on a NUC.

![image](https://user-images.githubusercontent.com/110464785/182363713-01bcd656-9cf4-418f-b669-cb466708af1c.png)

**Comment by wallentx** [comment]
Are you able to provide us with logs? Setting your log level to INFO, and restarting the service would be helpful.

**Comment by krashbandit78** [comment]
> Are you able to provide us with logs? Setting your log level to INFO, and restarting the service would be helpful.
Yeah, the file is too big to share here, but here's a link to a copy of it: https://1drv.ms/u/s!AtiUzpceTOPbgvIB34uLfUlR13XLpA?e=hT8u7k

Thanks for any insight.

**Comment by Kiddoxxx** [comment]
having exactly the same problem here.

**Comment by wallentx** [comment]
Are you able to try one of the latest main builds from https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds and let us know how this goes for you?

**Comment by Makondo46** [comment]
Same issue here....

**Comment by kreaninw** [comment]
Same issue here... I can't sync my wallet anymore. Luckily, I didn't update my farm yet, just a wallet on my laptop. It seems, there's no test being done at all before the release.

**Comment by mook05** [comment]
Hi team, similar issue here. Updated to 1.5.0 a few days ago. GUI gets me to the Starting Services Screen, everything loads except Full Node - gets stuck on trying to start the Full Node and sits there for days. This is on a Mac Mini (intel) running Catalina 10.15.7. I updated an old 1.3.? version of Chia on a different Mac Mini (intel) running the latest MonteryOS to 1.5.0 on a different network / internet connection and it starts / connects fine (that computer has no plots on it though). 

I installed one of the latest dev builds and no difference at all. I wondered if it was my ISP / or router creating the issue so I connected to a different network / internet service (hotspotted to my phone) and also no difference at all. So to me this is pointing to the issue being related to Chia 1.5.0 not liking the older MacOS Catalina. Unfortunately that is the latest version OS this Mac Mini can run.

I have attached my debug.log file, hopefully someone can take a look and advise what the issue may be? I see a lot of reconnecting to peer and cannot connect to host issues. 

Thank you
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/9274260/debug.log)
!

**Comment by krashbandit78** [comment]
My issue is resolved. The first time I tried to re-sync after deleting mainnet.sqlite DB, my attempt to re-sync failed because I ran out of C: drive space.  After deleting the original file, I had room to continue downloading the new one but for some reason it bugged out and would not continue.  I deleted the partial mainnet.sqlite and started over, and now it finally works.  Sometimes I have to reload during initial startup because it freezes at "staring full node", but after reload everything works again.

**Comment by Kiddoxxx** [comment]
Hello, i was having a problem with previous 1.4 version but was a problem
of hard disk full then i cleaned the hard disk, installed 1.5 then nothing
worked more with the full node stucked in loading process

Il Gio 4 Ago 2022, 19:42 William Allen ***@***.***> ha
scritto:
