### ISSUE TITLE
chia blockchain 1.5, wallet always crashed

### ISSUE THREAD

**Issue by olinkcloud** [Chia-Network/chia-blockchain#12740]
Hello,
I setup a new chia 1.5 full node, it takes about 2-3days to sync the blockchain, looks good, but it took about 5-6 days to sync the wallet, and the wallet crashed several times, it will return "No keys loaded. Run 'chia keys generate' or import a key" when run "chia wallet show"

I have to restart the full node to recover the wallet.

Any advise?

**Comment by wallentx** [comment]
This is a known issue that we are working on. You may see benefit by restarting the entire system, and bringing everything back up, and allow everything to fully sync up before running commands. If your CPU usage on the wallet service is still 100%, you should allow it time to complete.

**Comment by wallentx** [comment]
Related to https://github.com/Chia-Network/chia-blockchain/issues/11175

**Comment by wallentx** [comment]
Closing this due to duplicate
