### ISSUE TITLE
[BUG] 1.0rc6: `chiapos` fails to build on FreeBSD 12.2 release

### ISSUE THREAD

**Issue by vkz** [Chia-Network/chia-blockchain#1275]
**Describe the bug**
Attempting to build `chia` from source, checkout tag `1.0rc6`, `sh install` fails while building `chiapos`.

**To Reproduce**
1. Go through the nuisance of issue #1110 to get `maturin` and `clvm_rs` installed
2. `sh install.sh`
3. Everything succeeds up until `chiapos`
```
 [ 91%] Building ASM object CMakeFiles/RunTests.dir/src/b3/blake3_sse41_x86-64_unix.S.o
  gmake[2]: *** [CMakeFiles/RunTests.dir/build.make:95: CMakeFiles/RunTests.dir/tests/test.cpp.o] Killed
  gmake[2]: *** Waiting for unfinished jobs....
  gmake[2]: *** [CMakeFiles/ProofOfSpace.dir/build.make:82: CMakeFiles/ProofOfSpace.dir/src/cli.cpp.o] Killed
  gmake[1]: *** [CMakeFiles/Makefile2:150: CMakeFiles/ProofOfSpace.dir/all] Error 2
  gmake[1]: *** Waiting for unfinished jobs....
  [ 94%] Linking CXX shared module ../lib.freebsd-12.2-RELEASE-p4-amd64-3.7/chiapos.so
  [ 94%] Built target chiapos
  gmake[1]: *** [CMakeFiles/Makefile2:231: CMakeFiles/RunTests.dir/all] Error 2
  gmake: *** [Makefile:114: all] Error 2
  Traceback (most recent call last):
```

**Expected behavior**
be able to install `chia` on FreeBSD 12.2 would nice seeing how we're fool-steam-aheading into mainnet

**Screenshots**

**Desktop (please complete the following information):**

- OS: FreeBSD 12.2 release

**Additional context**
Python 3.7, all latest packages

**Comment by vkz** [comment]
ok ... there's nothing holly in the world and I think I just lost all faith
that `killed` error message gave me reason to suspect that `GOD` has interfered. See, install was attempted on Vultr single CPU instance. So I checked `chiapos` locally, edited `cmake` arg to `-j 1` in your `setup.py` and it ... worked.

There is `god`. And it is cruel

I am speechless ... wtf. Also maybe that `-j 6` of yours should be optional? I still can't believe some VM watchdog would so brutally interfere.

Please, leave this with me for now. I'll try to build on other beefier machines tomorrow

**Comment by hoffmang9** [comment]
Cruel indeed. I do want to get the clvm-rs up on our pypi though.

**Comment by hoffmang9** [comment]
clvm-rs is on our Pypi. Closing
