### ISSUE TITLE
[BUG] Adding 24 word mnemonic is broken in 1.0rc6

### ISSUE THREAD

**Issue by shola** [Chia-Network/chia-blockchain#1277]
**Describe the bug**
`chia keys add -m 24words` is broken in 1.0rc6

**To Reproduce**

1. write down your 24 word mnemonic somewhere
2. install chia 1.0rc6 on a new system (or nuke all `.chia` config)
3. execute `chia keys add -m 24words`
4. See error that goes something like `-m is not a supported option`

**Expected behavior**
In prior versions of chia I could enter all of my 24 word mnemonic as a string, and everything would get initialized properly.

**Desktop (please complete the following information):**

- OS: ubuntu server 20.04 LTS
- OS: xubuntu 20.04 LTS
- CPU: xeon e5640 (dual 6 core) and amd phenom 2 (3 core)

**Additional context**
I had to checkout 1.0rc4 and build that in order to add my 24words. Then I checked out 1.0rc6 and built it again. Everything seems to be working fine and I have 2 config dirs: `~/.chia/testnet` and `~/.chia/1.0rc4`. The `testnet` one seems to be the one that is actually used.

**Comment by vkz** [comment]
wrap your 24 words in quotes: `chia keys add -m '24 words go here'`. Tripped me too

**Comment by hoffmang9** [comment]
As the release notes mention the way you enter the 24 words has changed for security reasons. The safe way is to hit chia keys add -m and hit return

**Comment by shola** [comment]
Makes sense @hoffmang9. I updated the 2 occurrences of the old 24 words behavior in the wiki. Please update if I missed any:

https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines
https://github.com/Chia-Network/chia-blockchain/wiki/Moving-plots
