### ISSUE TITLE
[Bug] GUI does not shorten NFT Names, preventing access to hamburger settings

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#12802]
### What happened?

See image below, when NFT names are longer than expected the GUI should shorten these as it does wallet addresses. Since the full name is displayed the hamburger settings are not accessible (secondary NFT shown has hamburger setting for comparison).

note: this is on the data grid view of all NFTs

![image](https://user-images.githubusercontent.com/48610606/183121092-5efbef34-4fb3-42ab-a681-85489f9ce29d.png)
![image](https://user-images.githubusercontent.com/48610606/183121275-e67c503d-edf9-486a-b3d5-6bfd562196da.png)

### Version

1.5.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
This was fixed in https://github.com/Chia-Network/chia-blockchain-gui/pull/882, and should be in the next release.
