### ISSUE TITLE
[Bug] infinite spinner when clicking on "Full node" in the GUI

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#12809]
### What happened?

Running on commit hash for chia-blockchain-gui - 93b5806d826aa50ec8a962882453362b640ea4f0

When I click on "Full node", I get the dialog box that pops up and the spinner, but it seems to be stuck there.

I'm running in wallet only mode. If there's no status to report while in wallet-only mode, the dialog should reflect that instead of showing a spinner that never stops.

![Screen Shot 2022-08-05 at 6 06 34 PM](https://user-images.githubusercontent.com/93196638/183222328-617b2173-664a-4935-ad8b-6b4953b1dd8f.png)

### Version

1.5.1 commit hash - 93b5806d826aa50ec8a962882453362b640ea4f0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
recreation of this issue to put it in the right bucket - https://github.com/Chia-Network/chia-blockchain-gui/issues/880

**Comment by paninaro** [comment]
Simplest fix would probably be to prevent clicking on Full Node in wallet-only mode.

**Comment by paninaro** [comment]
This has been fixed
