### ISSUE TITLE
[Bug] NFT Offer; Improve wallet CLI messaging

### ISSUE THREAD

**Issue by Jsewill** [Chia-Network/chia-blockchain#12814]
### What happened?

While creating an offer, offering an NFT which isn't in my wallet, for XCH, the wallet responds with the following:
```shell
...
Offers for NFTs will have royalties automatically added.  Are you sure you would like to continue? (y/n): Confirm (y/n): Exception from 'wallet' {'error': "Error creating offer: 'NoneType' object has no attribute 'id'", 'success': False}
```
Some messaging about trying to send an NFT we don't have, would be nice.

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by Gbolahan657** [comment]
If you truly need help contact hackerdecon936@gmail.com
