### ISSUE TITLE
Upgraded RC6 is out of sync

### ISSUE THREAD

**Issue by huangmeibao** [Chia-Network/chia-blockchain#1281]
full node status  Always show  “Waiting for network to launch”  ， Previous versions worked fine

**Comment by huangmeibao** [comment]
System is Windows 10

**Comment by hoffmang9** [comment]
Workaround in #announcements in on Keybase.

There seems to be a bug effecting Windows. To work around edit C:\Users\USERNAME\.chia\testnet\config\config.yaml and change testnet6: GENESIS_CHALLENGE: null to GENESIS_CHALLENGE: e0c271a9db2870e650a3634c58b52015c616ed90f1d47853cbbcd158df51a969

**Comment by huangmeibao** [comment]
is working  ,,Thank you
