### ISSUE TITLE
[Bug] The fee was filled in incorrectly

### ISSUE THREAD

**Issue by maigaoxiang111** [Chia-Network/chia-blockchain#12816]
### What happened?

![5CFE9ECF-5013-4EFA-9A66-1F928E281A5C](https://user-images.githubusercontent.com/110707933/183233649-58bf49df-af37-4274-a322-4839e68ccdc4.jpeg)
The fee was filled in 1.75 coins, the consequence did not arrive in the account, the address was shown to the account, but the total balance was not reached.

### Version

1.40

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by maigaoxiang111** [comment]
![Uploading 903E3BD5-F637-4911-8A7A-0D7F4B29B3AB.jpeg…]()

**Comment by shaneo257** [comment]
so when you added a fee, you put in 1.75XCH?

**Comment by emlowe** [comment]
Closing issue due to lack of responses
