### ISSUE TITLE
[BUG] Upgrade to 0.2.6 MAC OS

### ISSUE THREAD

**Issue by mcb0** [Chia-Network/chia-blockchain#1282]
**Describe the bug**

On MacOS Big Sur, all was working fine until I upgraded to version 0.2.6.  Now software will not sync, status is "Waiting for network to launch" and the Blocks section has waiting circle spinning.  All plots appear to be there just not available because they are waiting for sync.

**To Reproduce**

1. Open Chia app after upgrade
2. App will not sync

**Expected behavior**
App to open and sync

**Screenshots**

**Desktop (please complete the following information):**

- OS: [MAC OS Big Sur]
- OS Version 11.2.3
- CPU: 3 GHz Dual-Core Intel Core i7

**Additional context**

**Comment by hoffmang9** [comment]
Keybase #announcements has the work around:
```
If you are using the Mac installer it is the same workaround but - Edit /Users/USERNAME/.chia/testnet/config/config.yaml and change testnet6: GENESIS_CHALLENGE: null to GENESIS_CHALLENGE: e0c271a9db2870e650a3634c58b52015c616ed90f1d47853cbbcd158df51a969
And then restart the application
```
