### ISSUE TITLE
[Bug] SBX wallet refresh issue

### ISSUE THREAD

**Issue by wjblanke** [Chia-Network/chia-blockchain#12823]
### What happened?

SBX wallet does not appear on sync. Trying to add wallet says it already exists. Then SBX wallet appears.

### Version

1.5.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
https://user-images.githubusercontent.com/1206691/183297763-54a745bd-0693-4fc5-bfbe-8d5bc1c31e73.mov

**Comment by Gbolahan657** [comment]
If you truly need help contact hackerdecon936@gmail.com
