### ISSUE TITLE
RPC for calculating NFT royalties

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#12836]
Currently the GUI and wallet backend have separate implementations for determining NFT royalties when creating/taking an offer. This led to a bug in 1.4.0 wherein the GUI assumed that offers for an NFT would have the royalty amounts subtracted from the offered amount.

To avoid future bugs and simplify the code, we should have a single implementation of the royalty calculation logic in the wallet, and expose it through an RPC.

**Comment by paninaro** [comment]
@trepca is this something your team can take?

**Comment by trepca** [comment]
Yes

**Comment by trepca** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/13129
