### ISSUE TITLE
Disallow minting of invalid NFTs

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#12848]
### What happened?

We require that the sha256sum of the URI content to be provided at the time of minting via:
```
┌───────────────────────┐
│ -nh, --hash           │▒
│ -u, --uris            │▒
╞═══════════════════════│▒
| -mh, --metadata-hash  │▒
| -mu, --metadata-uris  │▒
╞═══════════════════════│▒
| -lh, --license-hash   │▒
| -lu, --license-uris   │▒
└───────────────────────┘▒
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
```

We don't do any sort of check to validate that the content actually matches. This puts the responsibility on the user to determine the hash. This is fairly easy to do on *nix:

```
               +                OS: Arch Linux x86_64
               #                Hostname: MSI
              ###               Kernel Release: 5.15.57.1-microsoft-standard-WSL2
             #####              Uptime: 0:19
             ######             WM: None
            ; #####;            DE: None
           +##.#####            Packages: 402
          +##########           RAM: 408 MB / 15848 MB
         #############;         Processor Type: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
        ###############+        $EDITOR: None
       #######   #######        Root: 36G / 251G (14%) (ext4)
     .######;     ;###;`".
    .#######;     ;#####.
    #########.   .########`
   ######'           '######
  ;####                 ####;
  ##'                     '##
 #'                         `#

curl -Ls https://www.chia.net/img/branding/chia-logo.svg | sha256sum
8447ea324a9b3b8fca8c907f7b62b2d843f9cc6966d25757853dfdaf93a19a6f  -
```

Now observe the same action ran on Windows:
```
        ,.=:!!t3Z3z.,                  William@MSI
       :tt:::tt333EE3                  -----------
       Et:::ztt33EEEL @Ee.,      ..,   OS: Windows 11 Home Insider Preview x86_64
      ;tt:::tt333EE7 ;EEEEEEttttt33#   Host: Micro-Star International Co., Ltd. GE76 Raider 11UE
     :Et:::zt333EEQ. $EEEEEttttt33QL   Kernel: 10.0.25174
     it::::tt333EEF @EEEEEEttttt33F    Uptime: 13 hours, 47 mins
    ;3=*^```"*4EEV :EEEEEEttttt33@.    Packages: 73 (scoop)
    ,.=::::!t=., ` @EEEEEEtttz33QF     Shell: bash 4.4.23
   ;::::::::zt33)   "4EEEtttji3P*      Resolution: 1920x1080, 3840x1080
  :t::::::::tt33.:Z3z..  `` ,..g.      DE: Aero
  i::::::::zt33F AEEEtttt::::ztF       WM: Explorer
 ;:::::::::t33V ;EEEttttt::::t3        WM Theme: Custom
 E::::::::zt33L @EEEtttt::::z3F        Terminal: Windows Terminal
{3=*^```"*4E3) ;EEEtttt:::::tZ`        CPU: 11th Gen Intel i7-11800H (16) @ 2.310GHz
             ` :EEEEtttt::::z7         Memory: 30747MiB / 32469MiB
                 "VEzjt:;;z>*`

curl -Ls https://www.chia.net/img/branding/chia-logo.svg | sha256sum.exe
ce7e83893cdada4407d5525ee914ae9a01d9e20c2b3670fc0e8c054b6761f1b6  -
```

Given the same usage, `sha256sum.exe` provides an incorrect hash for some reason.
Currently, the most basic minting command might resemble:
`chia wallet nft mint -i 2 -u https://www.chia.net/img/branding/chia-logo.svg -nh ce7e83893cdada4407d5525ee914ae9a01d9e20c2b3670fc0e8c054b6761f1b6`

If a Windows user were to run this, the output would be:
```

WARNING: Series total(-st) and number(-sn) options are *deprecated*, please use -en and -ec.

NFT minted Successfully with spend bundle: {'aggregated_signature': giant unformatted python object block...
```

The resultant output of a successful NFT minting is jarring, and isn't at first obvious that the minting happened successfully. It contains information that leaves the user to question it's importance or relevance, and seems like something that should appear in debug logs, rather than stdout.
A familiar user would recognize the output as a successful minting- except that we allowed the user to mint an NFT with an `Image Hash Mismatch`.
_(Worth noting that the "Successful" output doesn't guarantee that the NFT actually get's minted, as there seems to be a limitation on the number of NFTs that can be minted in relation to the block, or coin that gets selected for the spend, but I believe these issues are currently known, and are being worked on.)_

This is a bad user-experience. Should the user want to include metadata, and a license, the steps required double for each, as would their output of erroneous hashes if using sha256sum.exe.

I'd like to suggest that the best experience we could provide would not be to check if the hash matches the URI content, but to instead derive the hash from the content URI upon execution of the minting command, and completely remove the `-nh`, `-mh`, and `-lh` required options.
This would make the most basic minting command resemble:
`chia wallet nft mint -i 2 -u https://www.chia.net/img/branding/chia-logo.svg`

### Version

1.5.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
Invalid example NFT minted for reference: https://www.spacescan.io/xch/nft/nft1rfly3hzfrm70ac4ne3ckpm0ajfghq75hyvqhfs0cpfnwxqzkhstsz37rz7
```

**Comment by trepca** [comment]
@wallentx thanks, good idea
