### ISSUE TITLE
[BUG] Log plot filename of plot that had an error

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#1287]
**When proving fails but doesn't tell which plot RC7**
At times I find this error message, it would be great to log the plot file, on which the error occurred.

`00:21:39.224 harvester src.harvester.harvester : ERROR    Error using prover object Caught an unknown exception!`

**Comment by xorinox** [comment]
This error comes along in the middle of what seems unrelated

16:25:45.562 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer 4e1c41e2593f7cffaf05534e8a2acf5127dbf6b40f40f9ec3fec5d9d3cecd25e 192.168.1.110
16:25:45.717 harvester src.harvester.harvester : INFO     0 plots were eligible for farming cfa9813f01... Found 0 proofs. Time: 0.14286 s. Total 728 plots
16:25:45.728 harvester harvester_server        : INFO     -> farming_info to peer 192.168.1.110 4e1c41e2593f7cffaf05534e8a2acf5127dbf6b40f40f9ec3fec5d9d3cecd25e
16:25:54.140 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer 4e1c41e2593f7cffaf05534e8a2acf5127dbf6b40f40f9ec3fec5d9d3cecd25e 192.168.1.110
16:25:54.295 harvester src.harvester.harvester : ERROR    Error using prover object Caught an unknown exception!
16:25:54.306 harvester src.harvester.harvester : INFO     1 plots were eligible for farming cfa9813f01... Found 0 proofs. Time: 0.15515 s. Total 728 plots
16:25:54.318 harvester harvester_server        : INFO     -> farming_info to peer 192.168.1.110 4e1c41e2593f7cffaf05534e8a2acf5127dbf6b40f40f9ec3fec5d9d3cecd25e
16:26:03.479 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer 4e1c41e2593f7cffaf05534e8a2acf5127dbf6b40f40f9ec3fec5d9d3cecd25e 192.168.1.110
16:26:03.794 harvester src.harvester.harvester : INFO     1 plots were eligible for farming cfa9813f01... Found 0 proofs. Time: 0.26255 s. Total 728 plots

**Comment by xorinox** [comment]
I think all we really need is adding the **on {filename}**

`                try:
                    quality_strings = plot_info.prover.get_qualities_for_challenge(sp_challenge_hash)
                except Exception as e:
                    self.harvester.log.error(f"Error using prover object {e} on {filename}")
                    return []`

**Comment by mariano54** [comment]
:+1:

**Comment by mariano54** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/1500
