### ISSUE TITLE
[BUG] Harvester thinks there are multiple copies of a plot, but that is not true

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#1288]
**When harvester RC7 thinks there are multiple copies but that is not true**
I have searched through all my plots using the *id* and cannot find multiple copies.

`00:34:29.373 harvester src.plotting.plot_tools : WARNING  Have multiple copies of the plot /chia/harvesting/node-12/disk02/plot-k32-2021-03-07-17-35-6964059dc78f6c03ec2746e522865b24e6a2bcfd4c018e906e5ace0fb1d65be4.plot, not adding it.
01:02:00.896 harvester src.plotting.plot_tools : WARNING  Have multiple copies of the plot /chia/harvesting/node-12/disk02/plot-k32-2021-03-07-20-30-3de8c2a9599a92623bf87bb13f43e73150084341c53d0cd93cdc3c034ffca669.plot, not adding it.
01:02:22.083 harvester src.plotting.plot_tools : WARNING  Have multiple copies of the plot /chia/harvesting/node-12/disk04/plot-k32-2021-03-08-06-44-c5419b9f82c86a2af3aa44ac0930767896d107aad099cd29dc03b58106b22e26.plot, not adding it.
01:03:20.988 harvester src.plotting.plot_tools : WARNING  Have multiple copies of the plot /chia/harvesting/node-12/disk06/plot-k32-2021-03-12-00-05-a41aa791775383e5d4e3c234fb2e3e95d5e14b9c2b1b28e1740cb436aaad7e80.plot, not adding it.`

**Comment by gandroz** [comment]
same for me
