### ISSUE TITLE
Full Node not working after installing 1.5.0 on MacOS Catalina

### ISSUE THREAD

**Issue by mook05** [Chia-Network/chia-blockchain#12880]
Hi Chia Team,

Updated to 1.5.0 a week or two ago. GUI gets me to the Starting Services Screen, everything loads except Full Node - gets stuck on trying to start the Full Node and sits there for days. This is on a Mac Mini (intel) running Catalina 10.15.7. I updated an old 1.3.? version of Chia on a different Mac Mini (intel) running the latest MonteryOS to 1.5.0 on a different network / internet connection and it starts / connects fine (that computer has no plots on it though). 

I installed one of the latest dev builds and no difference at all. I wondered if it was my ISP / or router creating the issue so I connected to a different network / internet service (hotspotted to my phone) and also no difference at all. So to me this is pointing to the issue being related to Chia 1.5.0 not liking the older MacOS Catalina. Unfortunately that is the latest version OS this Mac Mini can run.

I have attached my debug.log file, hopefully someone can take a look and advise what the issue may be? I see a lot of reconnecting to peer and cannot connect to host issues. 

Thank you
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/9274260/debug.log)
!

_Originally posted by @mook05 in https://github.com/Chia-Network/chia-blockchain/issues/12746#issuecomment-1207131320_

(Raised as new issue as no response in other thread)

**Comment by cmmarslender** [comment]
It looks like you're still on the v1 DB - it might be worth trying to convert to the v2 db. Either way, versions that were still on v1 DB are also missing (if I remember correctly) some newer cache files that make startup much faster - it looks like your full node (per your logs) was validating the chain, which takes a while with no cache files. If you have another synced node, you could try pulling over the `height-to-hash` and `sub-epoch-summaries` files from the other synced node's DB folders to see if it will start up quicker with those already available.

**Comment by mook05** [comment]
> It looks like you're still on the v1 DB - it might be worth trying to convert to the v2 db. Either way, versions that were still on v1 DB are also missing (if I remember correctly) some newer cache files that make startup much faster - it looks like your full node (per your logs) was validating the chain, which takes a while with no cache files. If you have another synced node, you could try pulling over the `height-to-hash` and `sub-epoch-summaries` files from the other synced node's DB folders to see if it will start up quicker with those already available.

Cheers Chris. I found those 2 files on my other node that was synced ok, the files were missing completely in my db folder on this main machine that won't connect. Have copied them in and will just leave it and see if it will connect at all over time. The other node that did connect no problem is also still on the v1 DB (I didn't even know there was a change to v2). So far the log is filling up with the same "Reconnecting to Peer / Cannot connect to host" entries over and over. Will check back in with an update when I have something to report. Thanks again..

**Comment by akashkatare5** [comment]
I am not able to sync my node after installing V2 Chia.
Please help, I have attached below .log file. (@cmmarslender)

Thanks,
Akash

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/9336485/debug.log)
