### ISSUE TITLE
GUI Screen Blank Forever

### ISSUE THREAD

**Issue by rkandel** [Chia-Network/chia-blockchain#1292]
Hi, 
I upgraded to RC 7 on Ubuntu 20.04 LTS and since then the GUI screen stays blank forever. Nothing is displayed on the screen except the top menu bar. I also tried fresh install by removing both .chia and chia-blockchain folder but no luck at all.

The terminal is stuck with the following text:
_> electron
> electron .

/home/rishi/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
/home/rishi/chia-blockchain/app.asar.unpacked/daemon
false
/home/rishi/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../src/daemon/server.py
child process success
(node:4432) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert_

**Comment by JacoSwanepoel** [comment]
Hi - I have the same issue ever since upgrading to rc6. Upgraded to rc7 in hope that it will fix the issue, but no luck. I updated and reinstalled everything I could think of. No luck. Have you perhaps found the cause and how to fix it?

**Comment by rkandel** [comment]
Tried everything I can thing of but no luck yet. I am also newbie for Linux so I am not sure whether it is Linux issu or Chia. The Chia log files show the following error:
---------------------------
_06:46:47.301 full_node full_node_server        : WARNING  Peer 60.119.26.36 is still banned, not connecting to it
06:48:01.256 full_node full_node_server        : WARNING  Banning 163.182.190.99 for 600 seconds
06:48:01.257 full_node src.full_node.full_node : ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "/home/rishi/chia-blockchain/src/full_node/full_node.py", line 612, in _sync
    validated, fork_point = await self.weight_proof_handler.validate_weight_proof(response.wp)
  File "/home/rishi/chia-blockchain/src/full_node/weight_proof.py", line 485, in validate_weight_proof
    segment_validation_task = asyncio.get_running_loop().run_in_executor(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 783, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 16, in __init__
    util._flush_std_streams()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 439, in _flush_std_streams
    sys.stderr.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rishi/chia-blockchain/src/full_node/full_node.py", line 615, in _sync
    raise ValueError(f"Weight proof validation threw an error {e}")
ValueError: Weight proof validation threw an error [Errno 32] Broken pipe_

**Comment by JacoSwanepoel** [comment]
At least you get a log file. I don't even get a log at this point. All was well on previous versions... 

Broken pipe - is it maybe struggling to open some connection. 

What is the value for GENESIS_CHALLANGE in your config.yaml file?
![image](https://user-images.githubusercontent.com/10955751/111229930-b3296300-85de-11eb-948f-6b4164863675.png)

There was some issue where it was set to null by the installer. I think the value should be:
e0c271a9db2870e650a3634c58b52015c616ed90f1d47853cbbcd158df51a969

**Comment by JacoSwanepoel** [comment]
Maybe that is a different issue. My GUI is still blank with the value manually entered.

**Comment by rkandel** [comment]
> At least you get a log file. I don't even get a log at this point. All was well on previous versions...
> 
> Broken pipe - is it maybe struggling to open some connection.
> 
> What is the value for GENESIS_CHALLANGE in your config.yaml file?
> ![image](https://user-images.githubusercontent.com/10955751/111229930-b3296300-85de-11eb-948f-6b4164863675.png)
> 
> There was some issue where it was set to null by the installer. I think the value should be:
> e0c271a9db2870e650a3634c58b52015c616ed90f1d47853cbbcd158df51a969

Thanks. the Genesis are listed on the config file.

**Comment by JacoSwanepoel** [comment]
RC9 fixed the issue for me!

**Comment by rkandel** [comment]
So did it for me. Thanks.

Regards,
Rishi Kandel

*Disclaimer*
This email message and its attachments may contain personal or confidential
information. It is intended for the named addressee only. If you are not
the intended recipient, you must not use or disclose this message or its
attachments (including by saving, copying or delivering the information to
anyone else). Instead, we ask that you immediately notify the sender by
reply email and then permanently delete both messages and any attachments
from your system.  You should not rely on this email as containing any
commitment or consensus by the sender or a group, unless specifically
indicated otherwise. The opinions and views expressed in this communication
are solely the personal expression by the sender and does not represent any
organisational or institutional views unless otherwise endorsed by any
organisation.
