### ISSUE TITLE
[Bug] GUI Tokens balance takes over 10 minutes to show up

### ISSUE THREAD

**Issue by eFishCent** [Chia-Network/chia-blockchain#12986]
### What happened?

When first launching GUI on mac M1, the Tokens GUI screen takes over 10 minutes to show up. Everything has a spinning circle, showing loading for the duration.

Even after 10 minutes, the balances show up, but the Transactions don't show up until you refresh the Tokens page; you click on a different GUI section and come back to Tokens page.

![Screen Shot 2022-08-14 at 11 05 19 AM](https://user-images.githubusercontent.com/69721134/184689074-402e4dd3-c533-4188-b06c-2d464f7f27db.png)
 

### Version

1.5.1.dev445

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
Contact eFishCent for logs or additional GUI screenshots.
```

**Comment by paninaro** [comment]
@seeden is this an area that should be covered by the polling interval changes?
