### ISSUE TITLE
[Bug] GUI Closing down services list is empty on shut down

### ISSUE THREAD

**Issue by eFishCent** [Chia-Network/chia-blockchain#12987]
### What happened?

When shutting down GUI on macOS m1, sometimes the GUI screen with Closing down services list is empty.

![Screen Shot 2022-08-14 at 10 46 14 AM](https://user-images.githubusercontent.com/69721134/184689593-782a566e-7645-4b13-84dd-b52e24ea30fd.png)

This tends to happen most often when shutting down the GUI client within the first few minutes of the GUI launching, especially if the GUI is still stuck loading the Tokens (see [Bug 12986](https://github.com/Chia-Network/chia-blockchain/issues/12986))

### Version

1.5.1.dev445

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
Contact eFishCent for logs or additional GUI screenshots.
```

**Comment by paninaro** [comment]
Seems likely that this is related to the wallet balances not showing up. May not be actionable if the backend is completely wedged.

**Comment by wallentx** [comment]
Seeing the same issue on 1.5.1445 SOMETIMES.
