### ISSUE TITLE
[Bug] FullNode not working

### ISSUE THREAD

**Issue by PachiMc** [Chia-Network/chia-blockchain#12992]
### What happened?

Hi, when i try to install a new database v2 for not download the full node manually the full node never start, if i remove it all works fine and the node start from 0; i tried multiple database from multiple website all have the same error, tried using GUI and cli, no one work.

### Version

1.5.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by MumfMeisterT** [comment]
Hello PachiMc, 
When you download the V2 blockchain it may be in a compressed file, you will need to make sure that it is extracted and placed into your /.chia/mainnet/db/ folder. It will still need a little bit of time to sync up to current blockchain height. If all this above is correct and you are still running into this issue, could you provide the error you are speaking of or a screenshot? Thank you.
