### ISSUE TITLE
[BUG] Harvester is exiting with IncompleteReadError fatal error

### ISSUE THREAD

**Issue by tayyib1437** [Chia-Network/chia-blockchain#1299]
**Describe the bug**
I'm running a remote harvester. It happens once a day or more often. It could be something with my connection between harvester and farmer (they are far away).

The problem is that this error is fatal for the harvester process. Looks like it should be able to recover from it, and try again perhaps. It shouldn't be required to restart the whole process (including rescanning the plots).

```
15:09:12.152 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer dba774560caa034e59c78d42ceb8c47599c3389f07896b961fb339ce8921dd3a x.x.x.x
15:09:21.430 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer dba774560caa034e59c78d42ceb8c47599c3389f07896b961fb339ce8921dd3a x.x.x.x
15:09:21.539 harvester src.harvester.harvester : INFO     0 plots were eligible for farming 97cd85fd7a... Found 0 proofs. Time: x s. Total x plots
15:09:21.541 harvester harvester_server        : INFO     -> farming_info to peer x.x.x.x dba774560caa034e59c78d42ceb8c47599c3389f07896b961fb339ce8921dd3a
15:09:30.718 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chia/chia-blockchain/src/daemon/server.py", line 215, in safe_handle
    async for message in websocket:
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
In the terminal window I also have this error:
`munmap_chunk(): invalid pointer`

Harvester in run on Raspberry Pi 4 B using Ubuntu 20.04. Chia version is 1.0rc7.

**Comment by Deca** [comment]
Same issue on my harvester, but unfortunately it happens more frequently, about every 1-2hr

**Comment by hoffmang9** [comment]
This is a bug in harvester in that it should tolerate it but it almost always means that one or more of your plots has a problem.

**Comment by Deca** [comment]
> This is a bug in harvester in that it should tolerate it but it almost always means that one or more of your plots has a problem.

Uhm, I'm actually also plotting in the same directory...so having an incomplete plot could be a problem for the harvester?

**Comment by sa970** [comment]
Man I swear to God like I don’t know how to use the words but I lost my laptop so what’s habits today it was and I’m a shy but I am by the way so I’m so sorry bro

Sent from my iPhone

‫في 21‏/03‏/2021 الساعة 6:54 م، كتب/كتبت ‏Deca ***@***.***>:‬

﻿

This is a bug in harvester in that it should tolerate it but it almost always means that one or more of your plots has a problem.

Uhm, I'm actually also plotting in the same directory...so having an incomplete plot could be a problem for the harvester?

**Comment by sa970** [comment]
Brother Walla I swear by the name of God I don’t know how to use it I just like insulin do you watch it which I can do like just I want my laptop you know what I meanie

Sent from my iPhone

‫في 21‏/03‏/2021 الساعة 7:06 م، كتب/كتبت ‏satt ma ***@***.***>:‬

﻿ Man I swear to God like I don’t know how to use the words but I lost my laptop so what’s habits today it was and I’m a shy but I am by the way so I’m so sorry bro

Sent from my iPhone

‫في 21‏/03‏/2021 الساعة 6:54 م، كتب/كتبت ‏Deca ***@***.***>:‬

﻿

This is a bug in harvester in that it should tolerate it but it almost always means that one or more of your plots has a problem.

Uhm, I'm actually also plotting in the same directory...so having an incomplete plot could be a problem for the harvester?

**Comment by mariano54** [comment]
Can you both provide more context in what scenarios this happens? Are any files being copied? Are you plotting on the same drive? Are you inserting or removing drives?

**Comment by mariano54** [comment]
This is probably a crash in chiapos while creating proofs.

**Comment by mariano54** [comment]
munmap_chunk(): invalid pointer

This is the same issue we experienced with the 0xffffffff challenge (PR for this in chiapos)

**Comment by Deca** [comment]
> Can you both provide more context in what scenarios this happens? Are any files being copied? Are you plotting on the same drive? Are you inserting or removing drives?

I've not moved files manually nor mounted/dismounted drives. I'm plotting on a nvme drive different from the one where the SO is installed and I run the chia commands

**Comment by hoffmang9** [comment]
We believe the 1.0.3 release fixes this.
