### ISSUE TITLE
Chia Plot Missing Keys

### ISSUE THREAD

**Issue by Omar-Hakase** [Chia-Network/chia-blockchain#13006]
Hi there! I apologize if this has already been posted but I wasn't able to find an answer to my issue.

I recently switch my OS from Ubuntu to Pop OS. I configured my Chia blockchain GUI and it's already synced. However, when I add my plots I get this error. Any ideas on how to solve this?

![Chia](https://user-images.githubusercontent.com/83560860/184906298-f38cdcab-2796-417e-93ed-a6802d2f7887.png)

Cheers!

**Comment by shaneo257** [comment]
when you installed chia on the new OS, did you put in the correct mnemonics for your plots?
