### ISSUE TITLE
Consider general applicability of websockets reconnection code

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#13019]
The new reconnect code seems, at a glance, to be pretty general.  Can it not provide reconnect behavior for 'everything' instead of just the keychain proxy?  Though that question may be a good indication of my (lack of) understanding of the structure around the proxy.

_Originally posted by @altendky in https://github.com/Chia-Network/chia-blockchain/pull/12782#pullrequestreview-1062751168_

**Comment by jack60612** [comment]
> The new reconnect code seems, at a glance, to be pretty general.  Can it not provide reconnect behavior for 'everything' instead of just the keychain proxy?  Though that question may be a good indication of my (lack of) understanding of the structure around the proxy.
> 
> 
> 
> _Originally posted by @altendky in https://github.com/Chia-Network/chia-blockchain/pull/12782#pullrequestreview-1062751168_

@altendky what else would you want?

**Comment by altendky** [comment]
I generally assumed that we have multiple websocket connections and each of them might benefit from reconnect behavior.  I had not inspected any of them to consider actual applicability.

**Comment by jack60612** [comment]
> I generally assumed that we have multiple websocket connections and each of them might benefit from reconnect behavior.  I had not inspected any of them to consider actual applicability.

Most web-socket connections that require it already implement reconnect-ability, so I think this is not needed
