### ISSUE TITLE
Visual bug on Chia Blockchain Gui on Linux green characters disappear[Bug] 

### ISSUE THREAD

**Issue by coloc77** [Chia-Network/chia-blockchain#13033]
### What happened?

when I use the chia blockchain in gui mode under unbuntu I have a display problem that occurs after a few hours. The program window is still accessible but all the information normally in green does not appear. Linux reports that the chia blockchain program has stopped working. I close by clicking on the x and I restart the program and everything returns to normal. even if I have this display bug, farming seems to continue perfectly except that I no longer see the green inscriptions of the gui mode.
How can I solve the problem?
chia blockchain version 1.3.5 and 1.5.0 same bug.
Kubuntu 21.10
Dell Optiplex 7070 Micro PC (Intel 9700)
graphic card intel uhd 630

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to provide us with some of your logs, or a screenshot from when this happens?
