### ISSUE TITLE
[Enhancement] Write permission for sourcecode folder is required to operate? 

### ISSUE THREAD

**Issue by CrimsonAndRed** [Chia-Network/chia-blockchain#13051]
### What happened?

Hi, chia development team.
I encountered a problem with a newest chia-blockchain software, which could not be reproduced on 1.3.1 version.
Basically any chia cli command (ex. _source activate && chia version_) hangs infinitely and on SIGINT signal throws following stacktrace:
![trace](https://user-images.githubusercontent.com/16984211/185458341-56885c4b-6d50-4ea7-80ef-cafa8428461a.png)
My investigation shows, that at some point of time bladebit plotter support was added and it tries to eagerly compile some .clvm code (see chia/wallet/puzzles/p2_conditions.py#17), which in turn requires to create lock file in codebase sourcetree (chia/util/lock.py#27). Taking closer look at internals it seems that any error happened during lock file creation would be simply mocked and infinite loop would continue (see chia/util/lock.py#16-21). It is never stated that write permission for sourcecode folder should be granted to a user that uses chia, which was an issue in my case (lack of write permissions). 
Some of my ideas:
- keep infinite loop only in case particular error happened, otherwise log/not catch this error
- do not create lock files in source code folder, use $CHIA_ROOT instead?

### Version

1.5.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by stefan-lange** [comment]
see https://github.com/Chia-Network/chia-blockchain/issues/11257

**Comment by emlowe** [comment]
I believe this was resolved by #13609
