### ISSUE TITLE
stop using integer literals to index sql result rows

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#13112]
I don't like the existing pattern of having a query in one place that hopefully keeps the selected columns properly matched to the indexing off in another function...  but I think this refactor is still correct.  Even if we can't use dict rows like in the data layer code, we could at least have an enumeration of the columns and reference by that rather than integer literals.

_Originally posted by @altendky in https://github.com/Chia-Network/chia-blockchain/pull/12341#pullrequestreview-1042592120_

**Comment by altendky** [comment]
An enumeration only works if you use the right enumeration for that exact query since the indexes aren't table column indexes but query column indexes.  Benchmarking dict-like row usage would still be a nice thing to check.

**Comment by emlowe** [comment]
Moved to Jira backlog tracking -
