### ISSUE TITLE
Blank GUI after upgrading to 1.0rc6 (also persisted upgrading to 1.0rc7)

### ISSUE THREAD

**Issue by JacoSwanepoel** [Chia-Network/chia-blockchain#1311]
The Electron GUI is blank when I launch it with npm run elecetron &. This started happening after I upgraded to 1.0rc6 from rc5. It is still the case after upgrading to rc7 even after I completely reinstalled Ubuntu out of desperation. 
I see no log files created in the .chia/testnet/log/ directory - so I have no idea if any components are running properly. 

**To Reproduce**
1. install 1.0rc7 following the exact install instructions
2. launch the GUI and full node with npm run electron &

**Expected behavior**
I expect to see the GUI launch, prompting me to select the cert and and then initialising the node and plots. As per the normal GUI behaviour pre 1.0rc6.
I also expect to see some log files in .chia/testnet/log/

**Screenshots**
![image](https://user-images.githubusercontent.com/10955751/111230745-018b3180-85e0-11eb-9854-6fd28e86abf8.png)

![image](https://user-images.githubusercontent.com/10955751/111230780-0ea82080-85e0-11eb-873b-74aae5cdfb35.png)

![image](https://user-images.githubusercontent.com/10955751/111230824-2089c380-85e0-11eb-813a-c0719b5937d0.png)

![image](https://user-images.githubusercontent.com/10955751/111230869-3303fd00-85e0-11eb-9b83-5e1bedc2448e.png)

![image](https://user-images.githubusercontent.com/10955751/111230950-5169f880-85e0-11eb-98b7-ffcf623a6a3d.png)

**Desktop (please complete the following information):**
Ubuntu 20.04.2.0 LTS

**Additional context**
My plots are generating fine. Full node used to work fine up to me upgrading to rc6 from rc5.

**Comment by JacoSwanepoel** [comment]
Some more info. Tried to start all from the cli, get this error:

![image](https://user-images.githubusercontent.com/10955751/111232945-fdf9a980-85e3-11eb-9dc7-df1dcb0067e5.png)

**Comment by JacoSwanepoel** [comment]
More info. When I start the electron GUI with debug logging enabled, I see the following in the debug.log file:

![image](https://user-images.githubusercontent.com/10955751/111279815-fd3c3400-8632-11eb-93c1-6f7bd9f9b087.png)

No logging after this and the GUI is just blank. 

If I start the node from CLI  with "chia start -r node harvester farmer wallet" it does log and seem to work. Not sure.

**Comment by mariano54** [comment]
Try rc9

**Comment by JacoSwanepoel** [comment]
RC9 - fixed the issue for me, confirmed. Thank you!
