### ISSUE TITLE
[Bug] Tons of "WARNING  Rate limiting ourselves. message type: respond_peers" messages in log 

### ISSUE THREAD

**Issue by jayhohoho2019** [Chia-Network/chia-blockchain#13132]
### What happened?

After upgrade to 1.5.1 (from 1.5.0), full node shows a large number of "WARNING  Rate limiting ourselves. message type: respond_peers" messages in debug.log.  Full node is in sync.  Most connected peers are in sync, have even farmed a block since the upgrade, but these warning messages are filling up the log.  

### Version

1.5.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-08-23T22:56:57.376 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_proof_of_weight, peer: 31.19.126.71
2022-08-23T22:56:58.384 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_proof_of_weight, peer: 31.19.126.71
2022-08-23T22:56:59.391 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_proof_of_weight, peer: 31.19.126.71
2022-08-23T22:57:01.625 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 190.16.85.253
2022-08-23T22:57:01.626 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 109.111.131.6

Last 5 lines of log

Since upgrade, 1851 lines of this message type has shown up in log, with a total of 14 unique IPs.
```

**Comment by jayhohoho2019** [comment]
2022-08-23T16:59:22.007 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 88.26.224.173
2022-08-23T16:59:22.263 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 88.26.224.173
2022-08-23T17:04:02.144 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 24.96.61.222

First 3 lines in log, to provide a timeframe for the total of 1851 lines of messages.

**Comment by jayhohoho2019** [comment]
As of now Wed 24 Aug 2022 12:51:47 PM EDT, 4293 lines of this “Rate limiting" warning messages in log.  So that's during a 20 hour time span.

**Comment by alnuweiri** [comment]
The same problem here.

**Comment by luckeyca** [comment]
I think this bug might be long before 1.5.0 because there were tons of the rate limiting errors in my logs dated on July 31st which was the oldest I could go back.

**Comment by jayhohoho2019** [comment]
As of now they are 9.89% of the total debug.log lines.

**Comment by jayhohoho2019** [comment]
14% of total log as of now and still growing.   13951 lines

**Comment by zhangyongchang88** [comment]
> 截至目前，占总日志的 14%，并且仍在增长。13951行

能正常爆块吗？

**Comment by 00linglin** [comment]
I had the same issue on one of my harvesters and full node, ended up changing outbound_rate_limit_percent in the config file from 30 to 100 for both the harvester and full node. The messages stopped, not sure how it will affect other things though. I was having huge amounts of stale points for the affected harvester.

**Comment by wallentx** [comment]
Anyone reporting these problems, can you also share what pool you are with?

**Comment by Motophan** [comment]
Just came here to say this broke my farm down to a crawl. I will always stay 3-4 versions behind because I cannot trust chia-network to release code that has been bugtested. My 1.3PiB farm went to 500TiB overnight!

**Comment by jayhohoho2019** [comment]
> Anyone reporting these problems, can you also share what pool you are with?

I'm self farming.

**Comment by jayhohoho2019** [comment]
And as of now 16.0% of debug.log line count.

**Comment by TheGreatGooglyMoogly** [comment]
> Anyone reporting these problems, can you also share what pool you are with?

I have 6 Pool NFTs, 4 are with different pools (Spacepool, XCHpool, Chiahub & Spacefarmers), two are self-pooling & a load of non-NFT plots. In my case its only rate-limiting 2 IPs, both are synced full nodes.

**Comment by CEduardoGR** [comment]
> Anyone reporting these problems, can you also share what pool you are with?

I'm farming solo and I have this problem too.

**Comment by keliew** [comment]
Version: 1.5.1
OG solo, NFT pooling.

```
inbound_rate_limit_percent: 80
outbound_rate_limit_percent: 80
```
```
$ grep 'Rate limiting ourselves' ~/.chia/mainnet/log/debug.log | wc -l
203
```
My other node also has a same setup, but...
```
 $ grep 'Rate limiting ourselves' ~/.chia/mainnet/log/debug.log | wc -l
0
```

Both nodes have more or less the same amount of peers (>50).

**Comment by wallentx** [comment]
Thanks for the feedback. It seems this does seem to be impacting a spread of people.
What I've found so far _may_ give some hint as to what's happening.
From https://github.com/Chia-Network/chia-blockchain/pull/11636 which got pulled into both `main` and `1.5.1`:
> • Adds a capability RATE_LIMITS_V2 to signal that the node supports the new, more permissive rate limits. This allows wallets to make more requests per second, since the backend has been optimized (in the other PRs).
> • The lowest compatible rate limit that both peers support is used

I won't speculate as to what is happening beyond guessing that this might be peer dependent.

**Comment by skweee** [comment]
Before 1.5.1 this may have been already happening but was most likely invisible for most users. A diff between 1.5.1 and 1.5.0 reveals that this message changed severity:
- up to 1.5.0 and including: DEBUG
- starting with 1.5.1: WARNING

This is the relevant commit, which was first released in 1.5.1:
https://github.com/Chia-Network/chia-blockchain/commit/ab53d489955863e7fc03caef69b29b09b0184784

<img width="891" alt="image" src="https://user-images.githubusercontent.com/7595525/187075816-41d1811d-8bc5-4d54-acf2-61cef4b9fa8c.png">

**Comment by bhorvitz** [comment]
I am self-pooling and also seeing lots of these.  FWIW, the nodes that I am connected to that are reporting rate limiting are full nodes, not light wallets.  get_connections shows them as "type": 1.  I believe that a wallet shows up as type 6?  I might be misinterpreting that.

**Comment by jayhohoho2019** [comment]
21734 lines.  20.25% of my debug.log line count as of now.  Again this is my full node/wallet/farmer.

**Comment by LudmilaAlex** [comment]
Windows 11
Version 1.5.1 | 64 bit  NFT pooling, solo,
CLI
28.08.2022 11:50:46.829 Update to  v1.5.1 
At the time of 08/30/2022 06:13:43
Total events from logger Full_Node 69520
Including 15879 “WARNING” events, including 15826 “WARNING Rate limiting ourselves. message type: respond_peers, peer:,,,"	This is 15826/15879=99.67%
[https://mega.nz/file/NxQjyLra#LBbijLBwjMznCu_t6yYD1wEsWvVKqwpcg-tHxeq11Y8](url)
[https://mega.nz/file/Qk5VnTyA#TKBzjYMyVN0VZFUsBfRsa8yr79gjK9EXuxQ3JC-dM9w
Before (Windows 11, Version 1.5.1 | 64 bit NFT pooling, solo, CLI) this was not even close!

**Comment by jayhohoho2019** [comment]
33.04% of debug.log line count now.

**Comment by Sikevich** [comment]
windows 10/64
v1.5.1
new problem for v1.5.0 

2022-09-03T00:04:01.925 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 104.48.169.185
2022-09-03T00:05:02.232 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 71.231.207.161
2022-09-03T00:05:02.234 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 104.48.169.185
2022-09-03T00:05:02.238 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 71.231.207.161
2022-09-03T00:05:02.239 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 71.231.207.161
2022-09-03T00:05:02.240 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 104.48.169.185
2022-09-03T00:05:02.242 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: 104.48.169.185

>50% of log

**Comment by jayhohoho2019** [comment]
41.4% of log

**Comment by jayhohoho2019** [comment]
49.2% of log.   Also for the last half day or so my sync'ed peer count has remained under 10.  Normally it's above 40.   I'm restarting chia full node.

**Comment by Motophan** [comment]
Hi please fix this

**Comment by Wontell** [comment]
Im self pooling and have the same issue, i had 300K log just with this,
Maybe its a coincidence but the moment i "let the CPU breath" it stopped and 24 hours ago i deleted the log and since than tehre is no new one.
Im on 12700 [non K] in windows to save power i use power saver mode on the Chia PC.
Yesterday i enabled normal mode and deleted the log, so far no new one.
No I re-enabled the power saver power profile will see tomorrow if the error repeats

**Comment by Sikevich** [comment]
hi.I use maximum performance power mode all the time. Over the past week, the number of messages has decreased to <> 10%. 19.09.2022, 03:33, "Wontell" ***@***.***>: Im self pooling and have the same issue, i had 300K log just with this,Maybe its a coincidence but the moment i "let the CPU breath" it stopped and 24 hours ago i deleted the log and since than tehre is no new one.Im on 12700 [non K] in windows to save power i use power saver mode on the Chia PC.Yesterday i enabled normal mode and deleted the log, so far no new one.No I re-enabled the power saver power profile will see tomorrow if the error repeats—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Kikicaj** [comment]
It's been one month since, its already 1.6 and the same error message appears eventhough everything works fine. How come its not fixed yet?

**Comment by jayhohoho2019** [comment]
Just an update.  I rotated to a new log after upgrading to v1.6.0.  From 2022-09-23T12:57:16 to 2022-09-25T22:21:08.500, log has 1101/1279 lines of this Rating Limiting message, or 86.082%. All rate limit settings are default in config.yaml.

**Comment by jayhohoho2019** [comment]
A little more stats.  
1. the rate limiting message only appears on my full node/farmer/wallet.  It's not present on any of my remote harvesters.
2. on my full node debug.log, of 206679 lines, here is the distribution by message type.  So majority is respond_beers, with a good amount of respond_end_of_sub_slot as well.  What does this tell me?

new_peak_wallet,121
respond_additions,156
respond_block,145
respond_block_header,15
respond_blocks,11
respond_children,83
respond_end_of_sub_slot,10184
respond_header_blocks,540
respond_peers,105302
respond_proof_of_weight,1552
respond_puzzle_solution,31
respond_removals,116
respond_ses_hashes,41
respond_to_coin_update,57

3. I rotated the log on full node since 2022-10-12T10:58:52.573 and so far it's all respond_peers, out of 844 lines.
respond_peers,618

**Comment by 0x216c75636b** [comment]
hi any update on this?

**Comment by Sinkevi4** [comment]
Hi.
There are changes. I have ceased to appear uncontrollably these messages. Approximately once a day comes 200 lines within 10 minutes. The only replacement in the device is the transition to the BETA version.

**Comment by CEduardoGR** [comment]
Hi
After collecting data from my logs I found that I (and probably you too) may be loosing XCH because of this problem. 
When it happens my lookup time goes sky high, far more than 5 seconds. 

The attached log contains less than 1 second of log. 
[debug_.log](https://github.com/Chia-Network/chia-blockchain/files/9875188/debug_.log)

The IP address of the remote host was removed but it was always the same host.

And while this was happening my lookup times was like this (from moments before the event until to moment I captured the screenshot and saved a second of the log). 
![lookup_time](https://user-images.githubusercontent.com/55378201/198178251-4b0eedd8-d357-4c02-befe-a6eb6d9b8c5f.png)

I can't say for sure but the lookup times possibly increased because saving 5 or more lines of log each millisecond uses a lot of CPU and also high disk throughput when the data is flushed to the log.

This does not occur all the times this message is logged, but this bursts of several minutes of the message appearing several times per millisecond happens between 4 and 7 times a day (in the last 15 days, I don't have older data atm).

Do you guys have the same behavior in your rigs? I'm asking because I'm not sure if this is a problem with my setup. If it's a local problem the feedback from this post should be ignored. Let's see what will be found by more users.

**Comment by CEduardoGR** [comment]
A few more info


redacted@redacted:~> cat ~/.chia/mainnet/log/debug.log|grep "message type: new" | wc -l
330871
redacted@redacted:~> cat ~/.chia/mainnet/log/debug.log|wc -l
341915

The log starts 22:13:37.607 and stops at 00:04:31.230 (a few moments ago).  Less than 2 hours and 330.871 events of this type from a total of 341.915

**Comment by jayhohoho2019** [comment]
With global outbound_rate_limit_percent: 50, full node was restarted on 2022-10-12.  Here is the daily log line count that contains "Rate limiting".  As we can see the daily total varies quite a bit.  On the peak day it averaged ~23 lines per minute. 
2022-10-12:544
2022-10-13:74
2022-10-14:210
2022-10-15:217
2022-10-16:7253
2022-10-17:11874
2022-10-18:14375
2022-10-19:22576
2022-10-20:3358
2022-10-21:13805
2022-10-22:7158
2022-10-23:6822
2022-10-24:10723
2022-10-25:5435
2022-10-26:32407

There is little correlation of this count to block rewards it seems, but it does seem to be unnecessarily adding way too many warnings to log.  Could you move it back to DEBUG in v1.6.1?

**Comment by CEduardoGR** [comment]
Can I change the source code locally to suppress this (I don't mind having to change again and again in future versions until this is fixed) or there is some kind of verification against tampering and I should avoid doing this?

**Comment by hugepants** [comment]
@jayhohoho2019 
> Could you move it back to DEBUG in v1.6.1?

Done, not in 1.6.1, but will be in the next release: https://github.com/Chia-Network/chia-blockchain/commit/1220fcfd695bd04402486d4ccfdad9dfaf92affa

@CEduardoGR 

> Can I change the source code locally to suppress this

You could, or just update and run from `main` now

**Comment by jayhohoho2019** [comment]
Thanks.  Btw looks like in v1.6.1 another WARNING has taken the lead.  Since 2022-11-05 there have been 33604 lines of the following.  Should I file another separate bug?
full_node chia.full_node.mempool  : WARNING  Fee estimator error

**Comment by hugepants** [comment]
> Should I file a separate bug?

Already filed : https://github.com/Chia-Network/chia-blockchain/issues/13750

**Comment by andsoitgoes** [comment]
I'm on 1.6.1 and not only do I have the other error, I have this one, too.

What's the solution? I'm updated and using the CLI on Windows. 

My log file is currently almost 360k lines long...

**Comment by emlowe** [comment]
This was fixed in 1.6.2 in #13758

**Comment by jayhohoho2019** [comment]
Unless there is another bug tracking it, probably should leave this open until the following is fixed too:
2023-01-05T17:26:30.242 full_node chia.full_node.full_node: WARNING  Time for header validate: 0.011703014373779297

Excessive "WARNING Time for header validate" messages.

**Comment by jayhohoho2019** [comment]
This is still present in v1.6.2.

**Comment by emlowe** [comment]
Please open a new issue for different log entries.

**Comment by jayhohoho2019** [comment]
Opened [14303](https://github.com/Chia-Network/chia-blockchain/issues/14303)
