### ISSUE TITLE
[Bug] farmer chia.plot_sync.receiver    : ERROR

### ISSUE THREAD

**Issue by Godmen-du** [Chia-Network/chia-blockchain#13158]
### What happened?

debug.log message is (2022-08-25T15:42:33.277 farmer chia.plot_sync.receiver    : ERROR    reset: node_id 9d206c63a795abfd12e0dcaded7fc1fd7e73ce0cbad813bbf498d99e15cd8a76, current_sync: [state 0, sync_id 0, next_message_id 0, plots_processed 0, plots_total 0, delta [valid +0/-0, invalid +0/-0, keys missing: +0/-0, duplicates: +0/-0], time_done None] )

Unable to mine for 4-7 days at solo. Total Size of Plots is 1.5Pib

### Version

1.51

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2022-08-25T15:42:33.277 farmer chia.plot_sync.receiver    : ERROR    reset: node_id 9d206c63a795abfd12e0dcaded7fc1fd7e73ce0cbad813bbf498d99e15cd8a76, current_sync: [state 0, sync_id 0, next_message_id 0, plots_processed 0, plots_total 0, delta [valid +0/-0, invalid +0/-0, keys missing: +0/-0, duplicates: +0/-0], time_done None] )
```

**Comment by wallentx** [comment]
Are you running a remote harvester? If so, is everything updated to 1.5.1?
Can you try to delete `~/.chia/mainnet/cache/plot_manager.dat`, and restart the harvester to see if this prevents this from happening?

**Comment by Godmen-du** [comment]
Reboot after deletion, same message.
Execute force reload to display==>{2022-08-26T09:09:44.925 daemon __main__  : ERROR    Unexpected exception trying to send to websocket: Connection lost Traceback (most recent call last):
  File "chia\daemon\server.py", line 233, in incoming_connection
  File "aiohttp\web_ws.py", line 308, in send_str
  File "aiohttp\http_websocket.py", line 690, in send
  File "aiohttp\http_websocket.py", line 659, in _send_frame
  File "aiohttp\base_protocol.py", line 80, in _drain_helper
ConnectionResetError: Connection lost  }

**Comment by Rod-ree** [comment]
I started getting this same error on Ubuntu a few days ago.

**Comment by CEduardoGR** [comment]
Do this error mean that the farmer and harvesters are not farming? I mean farming for real because I can see in the logs of every machine that there are plots passing the filter but my ETW is around a month so I can't say my machines are farming as they should.

The error started after the upgrade to 1.5.1. I'm running Chia CLI, openSUSE Linux in all computers (1 farmer/harvester and 6 harvesters). Double checked the version, 1.5.1 in all of them.

**Comment by xdustinface** [comment]
This message `ERROR reset ....` does not necessarily mean it's an actual bad error, i will change the log level there to `INFO`. 

But to still understand why you can't farm, can you post the full log either here or send it to me on keybase base.io/dustinface. Thanks!

**Comment by emlowe** [comment]
closing due to lack of response
