### ISSUE TITLE
Didn't show all NFT in wallet[Bug] 

### ISSUE THREAD

**Issue by advlive** [Chia-Network/chia-blockchain#13167]
### What happened?

after 1.5.1 all NFT did not show in wallet but on 1.4 can see. also in 1.5.1 two profile add in NFT which in profile can not see like NFT wallet 5, NFT wallet 27 

### Version

1.5.2145

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
This is an issue that I was also experiencing. Are you able to try one of the Dev builds from [Latest Dev](https://www.chia.net/download/#:~:text=OpenBSD-,Latest%20Dev,-Note%3A%20Dev%20builds) to see if that works any better for you? It resolved it for me.
