### ISSUE TITLE
[Bug] 1.5.1 收割机，无法自动农业。

### ISSUE THREAD

**Issue by zhangyongchang88** [Chia-Network/chia-blockchain#13170]
### What happened?

![image](https://user-images.githubusercontent.com/70252155/186722474-882c6ebc-defd-4c83-9e51-b77c5144888a.png)

### Version

1.5.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by zhangyongchang88** [comment]
收割机无法自动农业

**Comment by zhangyongchang88** [comment]
我的收割机System是NoDisk，没有GPU，使用bat调用，每次重启系统会还原。
![image](https://user-images.githubusercontent.com/70252155/186725234-1d042a5a-584a-479a-b211-6293ac667dd3.png)
![image](https://user-images.githubusercontent.com/70252155/186725451-93c228ea-2867-42b2-9661-5a866dc7fd54.png)

**Comment by zhangyongchang88** [comment]
所有的收割机都提示
![image](https://user-images.githubusercontent.com/70252155/186725541-0348ef14-1165-4d9f-bdac-f718b7c7cb83.png)
1.5.1下无法自动农业。
我现在已经退回1.5.0版本

**Comment by BernardJin** [comment]
您好，如果您遇到的是因为钥匙提示导致的自动化问题，您可以在脚本中输入'echo y | command'来自动帮您的所有机器点击Y。

**Comment by zhangyongchang88** [comment]
> 您好，如果您遇到的是因为钥匙提示导致的自动化问题，您可以在脚本中输入'echo y | command'来自动帮您的所有机器点击Y。

我测试过，输入Y后还有其他提示，两步输入后，也没有能正常农业，我目前已经退回1.5.0了

**Comment by zhangyongchang88** [comment]
> 您好，如果您遇到的是因为钥匙提示导致的自动化问题，您可以在脚本中输入'echo y | command'来自动帮您的所有机器点击Y。

总之收割机没有能像以前一样正常工作，这种提示或者输入再收割机中感觉没有任何必要，这对我来说是一种负担。

**Comment by zhangyongchang88** [comment]
我的收割机和钱包是独立的，收割机端不应该有这样的提示。

**Comment by BernardJin** [comment]
您好，很抱歉给您造成不便，您以后如果有任何类似的问题可以直接联系我的微信，微信号为：M_Jin98
