### ISSUE TITLE
[BUG] Exception when running chia farm summary

### ISSUE THREAD

**Issue by mmulsow** [Chia-Network/chia-blockchain#1318]
**Describe the bug**
I'm seeing this exception when running `chia farm summary` on rc7 shortly after starting the farmer:

```
$ chia farm summary
Exception from 'wallet' {'error': "'NoneType' object has no attribute 'tx_store'", 'success': False}
Connection error. Check if harvester is running at 8560
```

**To Reproduce**
1) Run `chia start farmer`
2) Run `chia farm summary` shortly after

**Expected behavior**
I'm expecting to see the `Connection error` message since the harvester probably hasn't started yet, but I was not expecting to see the Exception.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: 2x Xeon E5-2698. v4

**Additional context**

**Comment by mariano54** [comment]
This is just before the green flag I think, it's not a real issue.
