### ISSUE TITLE
Harvester Network/ Last Attempted Proof / Harvesters Plots

### ISSUE THREAD

**Issue by 0ferreira** [Chia-Network/chia-blockchain#13208]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/13207

<div type='discussions-op-text'>

<sup>Originally posted by **0ferreira** August 27, 2022</sup>
Hi guys!

i need some help. i dont know if i m having a issue or its working ok. 

I have 2 raspbarrys  Harvester  chia and they show 0 plots.

but all plots are showing up in the Last Attempted Proof

Do i have to worry?

![image](https://user-images.githubusercontent.com/94022118/187043778-a91df980-7266-4b4c-8cc5-50a8ebb614ab.png)

![image](https://user-images.githubusercontent.com/94022118/187043811-ab505a74-7c96-4d81-a962-99b38d04c5f4.png)

![image](https://user-images.githubusercontent.com/94022118/187043875-49c9af0e-5bad-498c-989d-c477dafbc403.png)

I just end the update to 1.5.1 from 1.3.5

thanks

</div>

**Comment by wallentx** [comment]
Are all of your harvesters running the same version of Chia as your node?

**Comment by wallentx** [comment]
What is the output of `chia farm summary`?

**Comment by emlowe** [comment]
closing issue due to lack of response
