### ISSUE TITLE
[Bug] No add_mirror output

### ISSUE THREAD

**Issue by fizpawiz** [Chia-Network/chia-blockchain#13230]
### What happened?

`chia data add_mirror` does not produce any output, regardless of success or failure.

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
(none)
```

**Comment by emlowe** [comment]
Fixed by https://github.com/Chia-Network/chia-blockchain/pull/13247

**Comment by emlowe** [comment]
Closing - fixed and merged
