### ISSUE TITLE
Make better tests for testing coin store

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#13244]
this test might be better if it didn't have wallets and nodes. Check  out the other tests in the file. We can usually just add coins manually to the coin store, and don't need all these services up and running, which takes time and decreases stability

_Originally posted by @mariano54 in https://github.com/Chia-Network/chia-blockchain/pull/12878#discussion_r944097727_

**Comment by danieljperry** [comment]
I already removed the test that comment was aimed at.
