### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Turbobussi** [Chia-Network/chia-blockchain#13241]
### What happened?

When starting chia. Slow starting after 1.51 update also never get status ready. It stays like picture.

![image](https://user-images.githubusercontent.com/41567456/187501813-828ebfff-3180-498f-ad02-e95a187ec9ec.png)

### Version

1.51

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to provide any logs? Does this always happen even after restarting Chia?

**Comment by emlowe** [comment]
Closing issue due to lack of response
