### ISSUE TITLE
[Bug] Your team's code level is too bad, please test carefully !/ 你们团队的代码水平太差了，请仔细测试

### ISSUE THREAD

**Issue by dysuwen** [Chia-Network/chia-blockchain#13255]
### What happened?

Your team's code level is too bad, please test carefully !/ 你们团队的代码水平太差了，请仔细测试

I use chia from May 2021. Manage 200 nodes, The currently released version does not have a stable
Please test your team before releasing。cause a lot of trouble to our users。Please stabilize the basic 
functions before adding new functions。

我从2021.5月开始使用chia, 管理200个节点，当前发布的版本没有一个稳定的，请你们团队做好测试后在发布。
给我们用户造成很大的麻烦. 请把基础功能做稳定后再增加新功能。

v1.3.1 功能勉强正常，但是到了2,300,000高度却不工作.
v1.3.1 works just fine, But at height 2300000 he doesn't work

v1.3.4/v1.3.5  集群模式连接不正常，无法正常工作.
v1.3.4/v1.3.5  cluster mode is not working, 

v1.4.0  钱包无法发送.
v1.4.0  wallet not sending 

v1.5.0 Win客户端无法正常同步，内存泄漏.
v1.5.0 Win client cannot sync properly, memory leak

![1](https://user-images.githubusercontent.com/6263057/187680658-e3483b76-f041-4b44-8964-e02120c153a1.png)
![2](https://user-images.githubusercontent.com/6263057/187680675-49317134-672a-4598-b74b-0abe6eb26477.png)
![3](https://user-images.githubusercontent.com/6263057/187681178-63e5adf2-06cd-450e-a941-154490587612.png)

### Version

v1.4.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by Motophan** [comment]
Hey so like, why not have 1 or 2 nodes and use remote harvesters?
Running that many nodes does not seem like it would be helpful to the network or productive for the end user.

**Comment by dysuwen** [comment]
> Hey so like, why not have 1 or 2 nodes and use remote harvesters? Running that many nodes does not seem like it would be helpful to the network or productive for the end user.
> 
> 2ndly, 8GB is too low for chia for ram unless you run linux (lower ram requirement) and headless (no gui for less resource usage)

My production environment use Ubuntu linux, working in cluster mode, and has 16-128G memory, (1 master node, 199 harvester nodes, using port 8447 to connect to the master node) but every version released so far has problems

Some of the screenshots I have are actually operating in the test environment.

**Comment by emlowe** [comment]
Closing issue - there is insufficient information on any one specific issue to resolve.

It is preferable to create an issue about a specific problem and provide reproducible steps. Otherwise these issues aren't helpful
