### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ly379042261** [Chia-Network/chia-blockchain#13250]
### What happened?

After updating to 1.5.1, the total farmland is 0，The path is normal

### Version

1.5.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ly379042261** [comment]
When trying to delete the original path and add it again：[Error 13] Permission denied. You are trying to access a file/directory without having the necessary permissions. Most likely one of the plot folders in your config.yaml has an issue.

**Comment by wallentx** [comment]
Are you able to provide us with any logs? Are you sure that the path to the plots are available to Windows?

**Comment by emlowe** [comment]
Closing issue due to lack of response
