### ISSUE TITLE
Data layer: CLI needs a `chia start/stop data-only`, or decouple `data` from the wallet

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#13284]
### What happened?

Currently the `chia start/stop data` command starts/stops the `data` service and the `wallet` service. To fall in line with other CLI options, any service that is bundled with starting/stopping other services should also have an `*-only` option.
This will be useful if someone wants to run these services separately, or to handle if they are already running, or if you want to stop the data service, but keep the wallet running.

### Version

1.5.2.dev2256

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by TheLastCicada** [comment]
Agree - this is needed

**Comment by emlowe** [comment]
Migrated to Jira backlog - closing GH issue
