### ISSUE TITLE
[Bug] need root information in get_keys_values, get_keys, get_value

### ISSUE THREAD

**Issue by fizpawiz** [Chia-Network/chia-blockchain#13293]
### What happened?

It is not clear how a datalayer subsciber would be able to tell that the data they have is out of date.  `get_keys_values`, `ket_keys` and `get_value` should return at least the root associated with the data it returns, and preferably also a flag inidicating whether that data is current based on the most recent root on chain.

### Version

1.6.0 dogfood

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by fchirica** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/13306

you can query by `root_hash` those calls. if the answer is empty, it means we don't have that root hash (otherwise it'll produce the expected keys/values, not the empty list).

**Comment by emlowe** [comment]
I believe this is resolved in 1.6.2 with the changes in #13306 and the new `get_sync_status` from #13440
