### ISSUE TITLE
[Bug] What happened here？

### ISSUE THREAD

**Issue by Jutean** [Chia-Network/chia-blockchain#13354]
### What happened?

soft
![soft](https://user-images.githubusercontent.com/15607204/188780411-d2977534-82ed-423d-b163-3d2998b2ff44.png)
pool
![pool](https://user-images.githubusercontent.com/15607204/188780415-c1b7c6bd-7089-485e-a883-8a4f2138c8dd.png)
![soft2](https://user-images.githubusercontent.com/15607204/188782421-c0d2b6ae-c64b-43d7-b58b-16a9ef330ebc.jpg)

From August 22 to September 3, all rewards disappeared

### Version

1.5.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Jutean** [comment]
From August 22 to September 3, all the profits in the period disappeared

**Comment by shaneo257** [comment]
have you closed the client, deleted the wallet db and reopened it?

**Comment by Jutean** [comment]
> have you closed the client, deleted the wallet db and reopened it?
I'll try
