### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jrescobarp7** [Chia-Network/chia-blockchain#1338]
I am trying to load the Chia GUI on my Mac running Catalina (10.15.7). Chia and the gui download and install just fine, but GUI is still getting stuck on "Connecting to Wallet". 

**To Reproduce**
Every time I try to run chia-gui (npm run electron &) from the chia-blockchain-gui/ directory.

**Expected behavior**
I expect it to ask me what key I would like to connect with, instead it is just "Connecting to Wallet" for as long as I leave it there.

**Screenshots**
![image](https://user-images.githubusercontent.com/77700497/111359963-ccb7c280-8651-11eb-824e-8a52ca172a82.png)

**Desktop (please complete the following information):**

- OS: MacOS Catalina (10.15.7)
- OS Version/Flavor: Catalina (10.15.7)
- CPU: 2.2 Ghz Quad-core Intel Core i7

**Additional context**
I am connected to the internet and have installed and updated all Chia software.

I have also tried: 
 Quitting and reloading GUI
 Quitting and starting on a new Terminal window
 Reloading GUI screen while in window with keyboard shortcut (cmd+ r) and View drop down
 Force reloading GUI both with keyboard shortcut (shift+cmd+r) and with View dropdown menu
 Restarting my computer
 Reinstalling GUI
 Reinstalling Chia
 Updating Chia
 Updating the GUI
 Waiting for up to an hour

**Comment by dorkmo** [comment]
which rc are you on?

**Comment by jrescobarp7** [comment]
I installed Chia on this computer last night and ran "git checkout 1.0rc7" so I believe I am on rc1.0rc7. Is there a command I could run to double check this?

**Comment by dorkmo** [comment]
youll want to git checkout 1.0rc9 to get the latest from this morning

**Comment by jrescobarp7** [comment]
I have updated to 1.0rc9, but it's still stuck "Connecting to Wallet". 

I did notice that at the end of the "npm run electron &" command I received this message. Im not sure if this helps solve the issue, but it is saying it cannot find "websockets". The sh commands all compiled successfully, so I'm really not sure what is causing this issue.

![image](https://user-images.githubusercontent.com/77700497/111371113-9b91bf00-865e-11eb-9808-879311a9902b.png)

**Comment by hoffmang9** [comment]
did you run `sh install.sh`? You should re-run it and watch it for errors.

**Comment by jrescobarp7** [comment]
I re-ran `sh install.sh` and received no errors (see screenshot at bottom). I also attached screenshots (first two screenshots) of me re-running `sh install-gui.sh` in case you guys could find errors that I am missing. But besides some warnings, and some files that aren't being processed I am only seeing successful compilations. What do you guys recommend I do next?


<img width="1207" alt="Screen Shot 2021-03-16 at 6 29 24 PM" src="https://user-images.githubusercontent.com/77700497/111397086-0dc9ca00-8686-11eb-9637-d2f6f8f94ac8.png">
<img width="979" alt="Screen Shot 2021-03-16 at 6 30 26 PM" src="https://user-images.githubusercontent.com/77700497/111397089-0f938d80-8686-11eb-95f6-58f320ff83a4.png">


<img width="1127" alt="Screen Shot 2021-03-16 at 4 03 47 PM" src="https://user-images.githubusercontent.com/77700497/111397079-09051600-8686-11eb-9f6b-be1b6df68e77.png">

**Comment by Stochastic-Adventure** [comment]
Encountered the same problem under Windows 10. I installed chia network via Windows installer. It is my first time using Chia so I don't have a wallet yet. Any thoughts on how to fix this?

**Comment by hoffmang9** [comment]
We believe this is fixed in 1.0.1
