### ISSUE TITLE
[BUG] Waiting for Network to Launch

### ISSUE THREAD

**Issue by Sutejm** [Chia-Network/chia-blockchain#1339]
**Describe the bug**

After downloading the new patch I seem to not able to syc my plots

**Screenshots**
![image](https://user-images.githubusercontent.com/80568417/111362750-153da300-8687-11eb-9927-3585cd00c24a.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- 
**Additional context**

**Comment by hoffmang9** [comment]
This is the correct message before the green flag is dropped. Will drop in about 15 minutes.

**Comment by Teledyol** [comment]
It's 12:35 PST and I'm still looking at the spinning pizza wheel of Death

Either the network hasn't started up or I need to find something else to stare at

**Comment by dorkmo** [comment]
you might try to restart real quick, you dont want to be on the pizza wheel

**Comment by Teledyol** [comment]
I updated to 0.2.9 • I saw that after I made that spurious comment

It appears to be synched now
