### ISSUE TITLE
Pooling Tab - Number of Plots is NOT the Same as Farming and Plots Tabs

### ISSUE THREAD

**Issue by jacoblroberts** [Chia-Network/chia-blockchain#13494]
### What happened?

Plots and Farming tab shows 9090 plots but the Pooling tab only shows 9018.  72 plots missing which is the size of an 8TB drive. 

I've refreshed plots and even rebooted. No change.

### Version

1.3.6-dev0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by jacoblroberts** [comment]
> Pooling tab shows PlotNFT plots only. Seems like you still have 72 OG plots?

I have 212 plots with missing keys.  These are the only OG plots I have remaining.  I deleted them, across 3 drives.  Now I have 0 with missing keys but the Pooling tab still shows only 9018, instead of 9090.

**Comment by wallentx** [comment]
> > Pooling tab shows PlotNFT plots only. Seems like you still have 72 OG plots?
> 
> I have 212 plots with missing keys. These are the only OG plots I have remaining. I deleted them, across 3 drives. Now I have 0 with missing keys but the Pooling tab still shows only 9018, instead of 9090.

If you have `jq` installed, can you run the following to see if there is any output:
`chia rpc farmer get_harvesters | jq -r '.harvesters[] | {duplicates: .duplicates[], failed_filenames: .failed_to_open_filenames[], no_key: .no_key_filenames[]}'`

**Comment by jacoblroberts** [comment]
> If you have `jq` installed, can you run the following to see if there is any output

No output.

**Comment by jacoblroberts** [comment]
I updated to the latest and now the plots are showing as missing keys.  False alarm.  Thanks for the help.
