### ISSUE TITLE
MAC GUI stuck on loading configuration upon start

### ISSUE THREAD

**Issue by zcreativemedia** [Chia-Network/chia-blockchain#13525]
I totally formatted my hard drive and installed a fresh copy of the High Sierra Mac OS on my Mac mini, downloaded all the security updates to the OS and the Chia GUI 1.3.5 and its stuck on "Loading configuration". Nothing I do seems to fix this. Please help!

**Comment by d1m1trus** [comment]
use latest version 1.6.0

**Comment by wallentx** [comment]
High Sierra has never been supported with our `.dmg` installers, or installing from source. You'll need to use OSX Mojave (10.14) or higher.
