### ISSUE TITLE
[BUG] Creating plots doesn't work in macOS GUI

### ISSUE THREAD

**Issue by Atemu** [Chia-Network/chia-blockchain#1353]
**Describe the bug**

When you try to create a plot in the GUI on macOS, no progress happens.

**To Reproduce**

1. Make new plot (k-25 in /tmp/ for testing in my case)
2. Click on 'Create plot'
3. Observe that no progress is done (no system resources are used to do anything, dir stays empty)

**Expected behavior**

It should create a plot by using a noticable amount of disk io and CPU time.

**Screenshots**

<img width="1680" alt="Screenshot 2021-03-17 at 19 42 29" src="https://user-images.githubusercontent.com/18599032/111521068-ff98ae00-8758-11eb-9611-dcc22cf3414c.png">

**Desktop (please complete the following information):**

- OS: macOS 
- OS Version/Flavor: 11.2.3 
- CPU: 6C "i9" from 2018 MBP 15

**Additional context**

**Comment by wjblanke** [comment]
We have a fix ready for this that will be in next release. Thanks for the report!

**Comment by Atemu** [comment]
Thank you for the fast response!

Where can I find the fix? The commit in master that's ahead of the current release seems unrelated.

**Comment by hoffmang9** [comment]
It will be in the 1.0 release - out later today.

**Comment by Atemu** [comment]
Exciting, thanks!
