### ISSUE TITLE
[Bug] Wallet DB Paths incorrect after DB Upgrade from V1 to V2

### ISSUE THREAD

**Issue by kiwihaitch** [Chia-Network/chia-blockchain#13547]
### What happened?

Think I've found a bug in the `chia db upgrade` that appears to have been partially fixed in 1.6.0, but introducess new "buggy" behavior. 

I have three machines with multiple keys that run full_nodes & wallets. Two were upgraded from V1 to V2 using some version prior to 1.6.0. The pre-upgrade DB Path in the wallet: section of config.yaml was database_path: wallet/db/blockchain_wallet_v1_CHALLENGE_KEY.sqlite. After the upgrade the DB Path was: `database_path: wallet/db/blockchain_v2_mainnet.sqlite`. This hard-coded path resulted in all keys having *exactly the same balances & transactions*, and only one sqllite DB existed in the wallet DB dir.

Doing a clean `chia init` results in `database_path: wallet/db/blockchain_wallet_v2_CHALLENGE_KEY.sqlite`, and a separate sqllite DB for each key.

Today to test I upgraded the third machine DB to 1.6.0 to V2. Post upgrade the DB path was `database_path: wallet/db/blockchain_wallet_v1_CHALLENGE_KEY.sqlite` - the same as the V1 path. It now correctly generates a sqllite DB per key, HOWEVER, the files in the wallet/db path are named `blockchain_wallet_v2_r1_mainnet_<key>.sqllite`.

- So in pre 1.6.0 you get a single hard-coded path and all keys used the one hard coded path.
- With 1.6.0 and clean init we get the expected path and DB names.
- With 1.6.0 upgrade it appears the path doesn't get modified, but the template for the DB names is not honored. The files are `...v2...` vs the expected `...v1...` names

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by arvidn** [comment]
this problem happens when you just run:
```
chia db upgrade
```
without any other arguments?

There is no new version of the wallet DB schema, the upgrade comment is not supposed to touch the wallet DB at all, just the blockchain DB. The config file has multiple keys called `database_path`, one under `wallet:` and one under `full_node:`, which one are you referring to?

Is the wallet db path changed in the config file by upgrading the blockchain database?
If so, is the full_node db path also updated?

**Comment by kiwihaitch** [comment]
1) No other arguments on the upgrade command
2) It's the `wallet: database_path:`
3) The full_node: database paths were updated and set to:
on the pre1.6.0 upgrade it was set to:  `database_path:
db/blockchain_v2_mainnet.sqlite`
on the 1.60 it was set to:  `database_path:
db/blockchain_v2_CHALLENGE.sqlite`

In both instance the chain db sqllite name is
` blockchain_v2_mainnet.sqlite`

4) Yes, the `wallet: database_path` was modified, but differently depending
on which version did the upgrade.
5) It doesn't seem to be an issue with the schema, but how the
database_path parameter in the wallet: section is "used"
- on whatever earlier version of the client it used the one single wallet
db no matter how many keys there were.
- on 1.6.0 it name the multiple wallet DBs are created, but named with a
'v2' version in the filename even though the `database_path` suggests it
should be 'v1'

**Comment by arvidn** [comment]
> 1) No other arguments on the upgrade command

Can you post the complete command line you ran?

**Comment by kiwihaitch** [comment]
Just simply `chia db upgrade`

**Comment by wallentx** [comment]
I would recommend using my tool to update your config interactively
https://github.com/wallentx/farm-and-ranch-supply-depot/tree/main/bin/config-management

**Comment by arvidn** [comment]
it's quite the mystery. I can't find any part of the code that alters the wallet database path. The upgrade command updates the full node database path. The way we handle the config file in general is not great though, so it's possible for changes to be clobbered if another process writes to the file, failing to first read the most recent changes to it.

I can't see a way for that issue to cause this symptom though.

**Comment by emlowe** [comment]
Closing issue that isn't generally reproducible. RIP Kiwi
