### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nono71x** [Chia-Network/chia-blockchain#13594]
### What happened?

Derivation index stuck at 3000, I changed the setting but now I can't lower it, it saturates my cpu

### Version

1.0.6

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by nono71x** [comment]
it worked that way, thanks

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : William ***@***.***>
Envoyé le :jeudi 6 octobre 2022 21:09
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Chia-Network/chia-blockchain] [Bug] (Issue #13594)


You can delete your wallet DB folder at ~/.chia/mainnet/wallet/db, and when you re-sync your wallet, it'll reset the derivation index.

**Comment by emlowe** [comment]
Closing issue
