### ISSUE TITLE
Plotters: Improve visibility of runtime error messages from bladebit/madmax when invoked by `chia plotters`

### ISSUE THREAD

**Issue by paninaro** [Chia-Network/chia-blockchain#13611]
When querying which plotters are installed and which versions, if the plotter crashes when run with --version, we don't see the underlying issue. Instead, we just see that the plotter exited with a non-zero status code. We should improve the visibility of the error messages from the plotter so that the user has a clue of what the issue is (missing library dependency).

**Comment by ChiaMineJP** [comment]
I've create a PR
https://github.com/Chia-Network/chia-blockchain/pull/13704

## How to test

- Prepare test executable which always fails and return non-zero.
```
# bladebit.rs
fn main() {
  panic!("test");
}
```
- Compile it.
```
$ rustc bladebit.rs
# You'll get bladebit or bladebit.exe for Windows
```
- Copy the pseudo bladebit executable to `venv/bin/` or `venv/Scripts` for Windows
- Then run `chia plotters version` with virtualenv.

## Sample output
```
(venv) PS C:\Users\User1\...\chia-blockchain> chia plotters version
Failed to determine bladebit version: thread 'main' panicked at 'test', bladebit.rs:2:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
chiapos: 1.0.11
```

**Comment by ChiaMineJP** [comment]
The PR was merged.
