### ISSUE TITLE
[BUG] Waiting for Network to Launch

### ISSUE THREAD

**Issue by Sutejm** [Chia-Network/chia-blockchain#1362]
Waiting for Network to Launch after loaded new software

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/80568417/111587438-1e7b5c80-87ba-11eb-93f2-19d33e0bed76.png)

- OS:Windows

**Additional context**

**Comment by dorkmo** [comment]
mainnet will start at the soonest 7am pst friday. Maybe be delayed though.
