### ISSUE TITLE
[Bug] Plots not showing after updating 1.5 to 1.6 (Windows)

### ISSUE THREAD

**Issue by im-mike** [Chia-Network/chia-blockchain#13622]
### What happened?

I've updated the Windows app from 1.5.0 to 1.6.0, everything was fine but when I opened the Plots tab it's showing 0 now, there's nothing under Farming tab either... I can still see the list of directories but the plots are not showing anymore...

What's the best thing to do now? Can I just install 1.5.0 over 1.6.0?

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

![Screenshot 2022-10-07 133828](https://user-images.githubusercontent.com/53824760/194555957-08e81a0d-2519-4052-842b-f2c68837df31.png)
![Clipboard011](https://user-images.githubusercontent.com/53824760/194555964-7f652a65-1128-4d30-816e-73959810b463.png)

**Comment by im-mike** [comment]
I've tried to remove one of the folders and I had an error 13, I've checked the log and there was an issue with two folders, removed these two from the config.yaml and the plots are showing again.

This issue has been resolved but this should ideally be fixed to just ignore a broken folder instead of not loading any plots at all.

![Screenshot 2022-10-07 154248](https://user-images.githubusercontent.com/53824760/194580845-c2420181-e6ca-4401-b50e-ca333203e92a.png)

**Comment by joaotomazio** [comment]
> I've just upgraded from 1.5.0 to 1.6.0 and I think the same is happening on Ubuntu ARM (cli only version).
> 
> `chia farm summary` now returns 0 plots. However, `chia plots check` identifies all my plots successfully.

Fixed by deleting `~/.chia` directory and reinitializing using `chia init`.

Tip: save the blockchain db file due to the current long synchronization before deleting the directory.
