### ISSUE TITLE
[Bug] `Coin` deserialization throws exception when `byte32` values do not start with `0x`

### ISSUE THREAD

**Issue by felixbrucker** [Chia-Network/chia-blockchain#13623]
### What happened?

I noticed the following when attempting to upgrade chia in a project where it is used as a library.

Previously (with 1.3.5) i could correctly deserialize a coin from a json dict when the `byte32` values did not start with `0x`:
```py
coin = Coin.from_json_dict({
    "parent_coin_info": "3a6341f3f5b3253918d360de4a832cc22238d8f4ad9abb4db42509b929d4d6f1",
    "puzzle_hash": "7d8be51b8c4df55813f5115e8fbac1e14a5e9d5af921c13e863af856e66e9869",
    "amount": 42,
})
```
Using chia 1.6.0 this does not work anymore and instead throws an exception:
```
ValueError: bytes object is expected to start with 0x
```

Using a custom streamable dataclass with a `byte32` prop works however:
```py
@streamable
@dataclass(frozen=True)
class TestClass(Streamable):
    parent_coin_info: bytes32

test = TestClass.from_json_dict({
    "parent_coin_info": "3a6341f3f5b3253918d360de4a832cc22238d8f4ad9abb4db42509b929d4d6f1",
})
```

It seems to me due to the deserialize of `Coin` happening in `chia_rs` the "regular" deserialize in python is not used and the rs deserialize is not working the same as the python deserialize.

The same might be true for other classes, i only tested `Coin`.

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wallentx** [comment]
Thanks for reporting this. Unfortunately, this is the intended behavior from a change in June.

**Comment by felixbrucker** [comment]
Thats sad to hear because it breaks backwards compatibility, especially when not breaking backwards compatibility would have been just as easy as adding this exception here, as we discard the 0x anyway: https://github.com/Chia-Network/chia_rs/blob/f5fdb37b8c62889695b76ccc9a1fb76caabf1c48/wheel/src/from_json_dict.rs#L18-L22

👎
