### ISSUE TITLE
[Bug] Request failed getting NFT details : `decoding to str: need a bytes-like object, list found`

### ISSUE THREAD

**Issue by vaibhavkulkarni1608** [Chia-Network/chia-blockchain#13631]
### What happened?

I'm not able to see my NFTs inside my wallet which was minted on testnet. When I am trying to mint a new NFT, the transaction is getting successful, but NFT is not showing inside the wallet. And if I checked on Spacescan it is there.

When I'm trying to get the NFT details it shows:- 
"Request failed: {'error': 'decoding to str: need a bytes-like object, list found', 'success': False}"

Can you help me with that?

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you able to provide screenshots, or the NFT ID? If you are able to provide the traceback from your logs that correlate with this, that would be useful as well.

**Comment by vaibhavkulkarni1608** [comment]
Spacescan Link - https://www.spacescan.io/txch10/did/c009e51d657aa2f19b83d3970a5673d0239395f7ab0fd4df87dd528d398fb8ac

Here you can see my all NFTs. I am not able to see these NFTs inside my chia GUI wallet. Also when I tried to call the 'Get NFT' API it shows me - 'Request failed: {'error': 'decoding to str: need a bytes-like object, list found', 'success': False}' this error.

**Comment by paninaro** [comment]
@vaibhavkulkarni1608 can you check your debug.log (make sure debug logging is enabled with `chia configure --set-log-level DEBUG`) when running `chia wallet nft get_info -ni <nft id>`? There should be a full stack trace available around the 'decoding to str' error message.

I'm able to view the collection in the GUI without any trouble, so it could be something local to the wallet db.

![image](https://user-images.githubusercontent.com/339312/201556183-fe7596a9-38c3-4260-abd4-b91a074e083e.png)

**Comment by Svetyr** [comment]
> -ni <nft id>

How can I find out this -ni <nft id> value for my NFT?

**Comment by Svetyr** [comment]
> @vaibhavkulkarni1608Можете ли вы проверить свой файл debug.log (убедитесь, что ведение журнала отладки включено с помощью `chia configure --set-log-level DEBUG`) при использовании `chia wallet nft get_info -ni <nft id>`? Должна быть доступна полная трассировка стека сообщений о деньгах 'decoding to str'.
> 
> Я могу без проблем представить коллекцию в графическом интерфейсе.
> 
> ![изображение](https://user-images.githubusercontent.com/339312/201556183-fe7596a9-38c3-4260-abd4-b91a074e083e.png)

How can I find out this -ni <nft id> value for my NFT?

**Comment by paninaro** [comment]
The `-ni` param can be the NFT identifier (the string beginning with "nft1"). For example, `nft1d20qjmmkfmazlmjvgnrtmvmg5d5227dk9fvqtqfhzsz6ng82007qe5z26z`

`chia wallet nft get_info -ni nft1d20qjmmkfmazlmjvgnrtmvmg5d5227dk9fvqtqfhzsz6ng82007qe5z26z`

**Comment by emlowe** [comment]
Closing issue due to lack of response

**Comment by vaibhavkulkarni1608** [comment]
I tried "chia wallet nft get_info -ni" command and able to see the nft details over there. But still not able to see the nft inside GUI or spacescan.
