### ISSUE TITLE
Bladebit 2.0 plotter occupies much more than 239GiB

### ISSUE THREAD

**Issue by korolevsv** [Chia-Network/chia-blockchain#13652]
### What happened?

Plotting stuck when almost all my free disk space (~350 GB) exhausted.
The picture is from Macbook, but the same was on Windows notebook (but couldn't make a screenshot because all programs were frozen with 100% processor time)
![Temp folder](https://user-images.githubusercontent.com/8134234/196475111-3863899c-80b6-4b39-bc41-bda8ca1417f9.jpg)

### Version

1.6.1b3

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by korolevsv** [comment]
Somebody told me Bladebit requires 316GB, but GUI prompts only 239GiB
![Screenshot 2022-10-18 at 22 56 39](https://user-images.githubusercontent.com/8134234/196531165-320323f1-653e-494e-bc9a-2c557e73bf07.png)

**Comment by emlowe** [comment]
Yes, BB2 requires more temporary space, currently, this is 480GiB. The GUI has been modified to correct this information - see https://github.com/Chia-Network/chia-blockchain-gui/pull/1071

Closign issue
