### ISSUE TITLE
[Bug] High pagefile usage from chia db (70GB+)

### ISSUE THREAD

**Issue by louisphilippe2** [Chia-Network/chia-blockchain#13672]
### What happened?

I noticed that my pagefile on my windows 10 farmer is about 76GB. This seems to be caused solely by the sqlite database of the main blockchain from my analysis of the pagefile. I was wondering if this is even normal to everyone else. And if I'm not alone, is this something that should be fixed? Because 76GB for a pagefile seems rather extremely large. I cannot imagine how large my pagefile will be in a few years when the blockchain will be doubled in size 😬

Thanks in advance!

### Version

1.6

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
I do not have any logs per say. I was hoping someone could verify if they also have a extremely large pagefile because of the chia blockchain db. I used a memory analyser tool to find out that the vast majority of my pagefile is occupied by the blockchain db. 

A tool like VMMap or RamMap should do the trick to confirm my bug
```

**Comment by emlowe** [comment]
The pagefile size is managed by Windows, I believe the maximum is by default configured at 4x your RAM. It won't get any larger than the maximum size configured by Windows. This is an OS setting.
Outside of a possible memory leak, chia has little to do with this
