### ISSUE TITLE
Recommend Update to Ubuntu Install Instructions

### ISSUE THREAD

**Issue by zachlankton** [Chia-Network/chia-blockchain#1367]
Recommend placing a note at the top of the ubuntu install instructions about making sure to kill all old daemons/process before git cloning or git fetching.  (or rebooting the machine).  I have personally experienced stray daemons causing issues and not realizing that it was my mistake and have coached a few others with similar issues.

**Comment by dorkmo** [comment]
im a bit of linux noob so i always restart before updating bc i dont know the first thing about stopping stuff properly lol

**Comment by hoffmang9** [comment]
It is a wiki...

**Comment by zachlankton** [comment]
Ah. Wasn't sure if I was able to edit the wiki. I see now.  I'm closing this and will consider an update to the wiki.  Thanks!
