### ISSUE TITLE
Add offer status in check_offer_validity response

### ISSUE THREAD

**Issue by LCG22** [Chia-Network/chia-blockchain#13706]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/10079

<div type='discussions-op-text'>

<sup>Originally posted by **mikehw** February  3, 2022</sup>
It would be useful to have the offer's status (e.g. accepted vs canceled) returned in the `check_offer_validity` response. This way the offer does not need to be in the wallet's `trade_manager` to determine if the offer was accepted vs canceled.

This is useful for deploying an offer record-keeping system in a micro-service architecture where there isn't a single chia wallet that has all of the offers loaded into the trade manager.</div>

**Comment by trepca** [comment]
If you're building a microservice, it might be better to use full node directly to examine offers vs wallet and track the chain for any acceptances: https://developers.chia.net/t/examining-offers-from-an-explorer-perspective/644
