### ISSUE TITLE
[Bug] DID metadata updates not included in spendbundle transmitted to the blockchain

### ISSUE THREAD

**Issue by RightSexyOrc** [Chia-Network/chia-blockchain#13705]
### What happened?

While DID metadata updates are updated in local wallet storage, the innerpuz put into the spendbundle by create_update_spend() does not include it

in https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/did_wallet/did_wallet.py#L1318

this would be a good test to be added to CI

### Version

1.6.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
To replicate:

create DID (w/ fee = 5 mojos+)

update metadata of DID  (w/ fee = 5 mojos+)

get metadata locally

get DID coin info

get metadata from the blockchain using full node api 

then parse the DID metadata from the blockchain
```

**Comment by ytx1991** [comment]
The metadata is updated, but it is hidden behind the new DID inner puzzle hash. Unless the DID owner does an additional spend, others will not be able to see the latest metadata on the chain. 
A short-term solution for you is asking the DID owner to update the metadata again with exactly the same values.
A mid-term solution for Chia is to add an additional spend in the Chia wallet code to prevent this issue happens in the future.
A long-term solution is to refine the DID Chialisp code to use the same metadata mechanism that NFT is using.

I will work on the mid-term solution for now.

**Comment by ytx1991** [comment]
Fix in https://github.com/Chia-Network/chia-blockchain/pull/13389
