### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mcb0** [Chia-Network/chia-blockchain#1370]
**Describe the bug**
 
Upgraded to v1.0 now software will not sync, status is "Waiting for network to launch" and the Blocks section has waiting circle spinning.  

**To Reproduce**

1. Open Chia app after upgrade
2. App will not sync

**Expected behavior**
App to open and sync

**Screenshots**

**Desktop (please complete the following information):**

OS: [MAC OS Big Sur]
OS Version 11.2.3
CPU: 3 GHz Dual-Core Intel Core i7

**Additional context**

**Comment by hoffmang9** [comment]
As designed and documented:
https://www.chia.net/2021/03/17/Chia-1.0.html
https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md
