### ISSUE TITLE
[Bug]  install-gui.sh not working!

### ISSUE THREAD

**Issue by epudwjuhc** [Chia-Network/chia-blockchain#13719]
### What happened?

sh install-gui.sh

Running git submodule update --init --recursive.

Running git submodule update.

ln: failed to create symbolic link '../node_modules/.bin/npm' -> '': No such file or directory

### Version

1.6

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
sh install-gui.sh

Running git submodule update --init --recursive.

Running git submodule update.

ln: failed to create symbolic link '../node_modules/.bin/npm' -> '': No such file or directory
```

**Comment by emlowe** [comment]
Can you be more specific on what flavour or distro of Linux you are using?

**Comment by ChiaMineJP** [comment]
It seems `npm` command was not recognized at all.
What Linux Distro exactly did you use?
Normally `nodejs` and `npm` will be installed automatically but seems it didn't work on your environment.

**Comment by DaOneLuna** [comment]
I had this same bug while using Arch Linux, solved it by running "pacman -Sy npm" first.

**Comment by ChiaMineJP** [comment]
Closed as the PR below was merged into `main`.
https://github.com/Chia-Network/chia-blockchain/pull/14059
