### ISSUE TITLE
[Bug] Wallet key labels fail to show up when selecting a key after issuing `chia wallet show`

### ISSUE THREAD

**Issue by langhorst** [Chia-Network/chia-blockchain#13714]
### What happened?

After setting wallet key names with: `chia keys label set -f fingerprint -l label`, I would expect these names to show up when selecting a wallet key after issuing a `chia wallet show`. Currently, only the fingerprints show.

The labels show up correctly in the output of `chia keys show`.

### Version

1.6.1b2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
justin@chia:~$ chia keys show
Showing all public keys derived from your master seed and private key:

Label: LanFarmer
Fingerprint: 597510542
...
Label: EppFarmer
Fingerprint: 3322999884

---

justin@chia:~$ chia wallet show
Wallet keys:
1) * 597510542 (Synced)
2)   3322999884
```

**Comment by paninaro** [comment]
PR https://github.com/Chia-Network/chia-blockchain/pull/13936

**Comment by paninaro** [comment]
PR has been merged. Changes will be shown in the next release.
