### ISSUE TITLE
Problems running ./chia plots check

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#13711]
### What happened?

the command does not run
./chia plots check -g ......

### Version

1.6.1-rc2

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by HVNC1** [comment]
https://user-images.githubusercontent.com/95166695/198386902-4d567429-a4d0-4b98-83dd-10b2cee9ae03.mp4

**Comment by emlowe** [comment]
This is fixed in 1.6.1
