### ISSUE TITLE
GUI closes down after screen wake-up, but Chia still writes to disk[BUG]

### ISSUE THREAD

**Issue by nitram-ydna** [Chia-Network/chia-blockchain#1371]
**Describe the bug**
If the screen is allowed to sleep (but of course not the drive), then I experience that the GUI closes down upon screen wake-up.
If GUI is re-started, then the plots are gone, but the chia wallet and farmer processes are still running.
Looking to the disk process and performance tabs, the disk is still being written to, and the space is being depleted, as if the plotting is still working.

**To Reproduce**
Just leave the plotter working and let the screen sleep. 
It should be possible to experience this with some tries.

**Expected behavior**
Usually when I wake up the screen, the plots are still visible in the GUI and I can observe that the disk is being written in performance monitor. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10.0.19042 
- CPU: Ryzen 5800x

![Chia_GUI_fail](https://user-images.githubusercontent.com/80907812/111682109-47d0d280-8824-11eb-9ad8-d2d8b50d2749.png)

**Comment by dorkmo** [comment]
you might double check your sleep settings and make sure its only turning the screen off, and not hibernating or sleeping

**Comment by dotdioscorea** [comment]
I have had this exact thing happen under the same circumstances. The computer has been running for several days with the screens regularly sleeping and everything has ran smoothly, but the most recent wake resulted in the gui going white before crashing, although the processes still seem to be running in the background.

**Comment by mariano54** [comment]
This is covered by https://github.com/Chia-Network/chia-blockchain/issues/1458
