### ISSUE TITLE
Issue with chia plotnft show NOT working

### ISSUE THREAD

**Issue by epudwjuhc** [Chia-Network/chia-blockchain#13718]
No matter what I do, I get:

~/src/chia-blockchain> chia plotnft show
Wallet height: 2738341
Sync status: Synced

NO show of any NFT ID to be used with -c for plotting... so much time gone and this software still can't do basic things!

**Comment by maxjay** [comment]
I mean.. are you sure you've created one to begin with? On that wallet?

**Comment by epudwjuhc** [comment]
sure...

chia plotnft create -s local

then still nothing displayed beyond wallet height & synced

**Comment by wallentx** [comment]
Are you able to provide the output of `chia wallet show -w pooling_wallet`?
Also, what OS are you on, and what version of Chia are you using?
