### ISSUE TITLE
chia plots check not working[Bug] 

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#13728]
### What happened?

chia plots check not working

### Version

1.6.1-rc3

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Please include any relevant log output. Also - when you say not working, can you please provide more details on how it's not working? Perhaps a screen shot would help. Does it hang? Does it return an error?, etc.

**Comment by HVNC1** [comment]
![image](https://user-images.githubusercontent.com/95166695/198385970-a8db446c-f8ee-43d5-8b03-690bd7f60728.png)
nothing happens in the logs, so I didn't add them
if you scan 1 area, the cursor just flashes and after a few seconds the text for entering the command appears
PS C:\Users\User\AppData\Local\Programs\Chia\resources\app.asar.unpacked\daemon>

**Comment by emlowe** [comment]
This seems a dup of #13711 - closing as duplicate

**Comment by HVNC1** [comment]
> Здається, це копія #13711 - закривається як дублікат

1 problem report was for version 1.6.1 of rc2 and the other was for rc3
