### ISSUE TITLE
[Bug] - sending more XCH then in the wallet doesn't return user friendly error

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#13737]
### What happened?

on testnet10, I tried sending TXCH transaction to myself, and when I put in a value (1 XCH) higher then what is in my wallet, I received the following error:

![Screen Shot 2022-10-28 at 12 06 54 PM](https://user-images.githubusercontent.com/93196638/198694075-4e0fb809-369b-4ac2-b257-a4ee4e900f08.png)

The error should return something more user friendly.

### Version

1.6.1rc4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
![image](https://user-images.githubusercontent.com/36589806/198816191-fac83fcf-09b1-44cb-976a-c009d5954453.png)
will also help when your trying to send your full balance to yourself
![image](https://user-images.githubusercontent.com/36589806/198816382-6ea706ae-ff95-4ae7-b4a7-d2f75d01b242.png)

**Comment by paninaro** [comment]
We should check the sending wallet's available balance during validation rather than relying on the not-so-helpful backend messages.
