### ISSUE TITLE
[Bug] Cannot open at least XXX files, please raise maximum open file limit in OS.

### ISSUE THREAD

**Issue by yllierop** [Chia-Network/chia-blockchain#13741]
### What happened?

When trying to use: `./chia plotters madmax -c....` I'm seeing the following error message: ` Cannot open at least XXX files, please raise maximum open file limit in OS.`

I've adjusted the `ulimit` from the defaults. This issue doesn't occur on the directly compiled version of the `Mad Max` plotter.

### Version

Chia 1.6.0

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
Cannot open at least XXX files, please raise maximum open file limit in OS.
```

**Comment by madMAx43v3r** [comment]
How many buckets are you using? Try a lower number.

**Comment by yllierop** [comment]
`-u 512` and `-v 256` the issue is it works fine in the directly downloaded version from the @madMAx43v3r repo just not in the Chia app wrapped version.

**Comment by madMAx43v3r** [comment]
Try 128 buckets for each

**Comment by yllierop** [comment]
`./chia plotters madmax -c` works fine with `128` buckets each. But, I guess what I'm wondering is... why does it behave differently when invoked from a build of: `https://github.com/madMAx43v3r/chia-plotter`

**Comment by yllierop** [comment]
I had originally thought the issue was the same as what is described in:  https://github.com/madMAx43v3r/chia-plotter/issues/385

**Comment by yllierop** [comment]
I think that I might have found the issue with `setrlimit` being hard-coded versus, using the systems `ulimit` settings on the following line of code available at: https://github.com/Chia-Network/chia-blockchain/commit/f550555c7d24202d7a98b435fe59560c5b61104f#diff-8acf0d600784f10ea705fc00078cdd0bc807d5805348e03e6f5cd303a7159898R172

```
  # madMAx has a ulimit -n requirement > 296:
        # "Cannot open at least 296 files, please raise maximum open file limit in OS."
        resource.setrlimit(resource.RLIMIT_NOFILE, (512, 512))
```

**Comment by yllierop** [comment]
@MumfMeisterT — I don't think that this is a `MacOS` only issue and it also effects the `GUI` as well.

**Comment by wallentx** [comment]
@yllierop Did you modify that line on your local system, and did it resolve your situation?

**Comment by yllierop** [comment]
@wallentx — yes, seems to do the trick. But, I think a better solution might be to check the current `ulimit` setting before blindly overwriting it.

**Comment by altendky** [comment]
@madMAx43v3r, would you consider setting the user limit to something appropriate in the madmax plotter itself?  Either your work, or someone else's PR.  This seems better than Chia picking.  It will help more users and be able to be adjusted at the same time as any changes in expected open file needs.  I know there's some variability related to the number of buckets so I would expect a hard coded limit set somewhat above the 'worst case'.

**Comment by madMAx43v3r** [comment]
I'm not touching the limits in the plotter, as this is not easily done in C++. It's platform dependent...

The required number of files is the number of buckets plus some more, so setting the limit to twice the number of buckets should be fine.

**Comment by madMAx43v3r** [comment]
I could add it for Linux though, not sure if that also works on MacOS..

**Comment by madMAx43v3r** [comment]
Strangely the code was already there but disabled... I enabled it again. Apparently it works on MacOS too.
