### ISSUE TITLE
What does "error 1" means in the logs

### ISSUE THREAD

**Issue by Gwhain** [Chia-Network/chia-blockchain#1375]
Hi,

I did run the plot creation all night but uncessfully as it seems.
The logs say:
...
Bucket 34 uniform sort. Ram: 4.440GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 35 uniform sort. Ram: 4.440GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 36 uniform sort. Ram: 4.440GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 37 uniform sort. Ram: 4.440GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
Only wrote 48516 of 226544 bytes at offset 4294853244 to "/Volumes/DATA I/plot-k32-2021-03-18-23-40-e6b4ff31ada3b5fb20ebd7c5b90a42ca5c8b38ab8dae07604d70f875147f6b54.plot.table1.tmp"with length 4294901760. Error 1. Retrying in five minutes.
Only wrote 65536 of 226544 bytes at offset 4294853244 to "/Volumes/DATA I/plot-k32-2021-03-18-23-40-e6b4ff31ada3b5fb20ebd7c5b90a42ca5c8b38ab8dae07604d70f875147f6b54.plot.table1.tmp"with length 4294918780. Error 1. Retrying in five minutes.
Only wrote 65536 of 226544 bytes at offset 4294853244 to "/Volumes/DATA I/plot-k32-2021-03-18-23-40-e6b4ff31ada3b5fb20ebd7c5b90a42ca5c8b38ab8dae07604d70f875147f6b54.plot.table1.tmp"with length 4294918780. Error 1. Retrying in five minutes.
...

Would anyone know how to mitigate this error?

I am using Mac OS Catalina (64 bits) and the plot and temporary file are located on an external hard disk with 928.39 GB free space.
I selected the 101.4GiB plot.

Many thanks.

**Comment by hoffmang9** [comment]
You likely ran out of space in your tempdir.

**Comment by Gwhain** [comment]
Thanks. I'll format the 1TB harddisk and try again.
