### ISSUE TITLE
Bladebit disk error

### ISSUE THREAD

**Issue by neo57500** [Chia-Network/chia-blockchain#13762]
### What happened?

[Bladebit Disk Plotter]
 Heap size      : 3.37 GiB ( 3445.93 MiB )
 Cache size     : 220.00 GiB ( 225280.00 MiB )
 Bucket count   : 256
 Alternating I/O: false
 F1  threads    : 32
 FP  threads    : 32
 C   threads    : 32
 P2  threads    : 32
 P3  threads    : 30
 I/O threads    : 1
 Temp1 block sz : 512
 Temp2 block sz : 512
 Temp1 path     : R:\Tmp
 Temp2 path     : R:\Tmp
 I/O metrices enabled.
 Allocating memory
STDERR: 

STDERR: Fatal Error:  

STDERR: VirtualAlloc failed.

### Version

1.6.1rc4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
[Bladebit Disk Plotter]
 Heap size      : 3.37 GiB ( 3445.93 MiB )
 Cache size     : 220.00 GiB ( 225280.00 MiB )
 Bucket count   : 256
 Alternating I/O: false
 F1  threads    : 32
 FP  threads    : 32
 C   threads    : 32
 P2  threads    : 32
 P3  threads    : 30
 I/O threads    : 1
 Temp1 block sz : 512
 Temp2 block sz : 512
 Temp1 path     : R:\Tmp
 Temp2 path     : R:\Tmp
 I/O metrices enabled.
 Allocating memory
STDERR: 


STDERR: Fatal Error:  


STDERR: VirtualAlloc failed.
```

**Comment by harold-b** [comment]
The error means the system could not offer as much memory as it was asked. You have set a cache size that is much larger than needed at a block size of 512. You may want to change the bucket count to 64 (`-b 64`) and lower the cache to `200G`, though 198G is likely enough.

**Comment by harold-b** [comment]
If you still get the error with `-b 64` then perhaps `-b 128` as it will require around 6GiB or heap instead of 11.5GiB with 64. The cache might safely be lowered to 198G as well
