### ISSUE TITLE
[Bug] NFT cannot display the symbol, the picture cannot be displayed completely

### ISSUE THREAD

**Issue by chiadev** [Chia-Network/chia-blockchain#13785]
### What happened?

NFT cannot display the symbol, the picture cannot be displayed completely

https://mintgarden.io/nfts/nft17dxs59tykzvtapz5hpa40ewaxdsjq507ugt4yxpdprp9twj4v7msv0cskf
![image](https://user-images.githubusercontent.com/45837988/199284990-93eb3e3b-8c02-4584-8e1f-5885b1f91ee0.png)

Pixel Cat #5 🌱
![image](https://user-images.githubusercontent.com/45837988/199285295-4a2461b8-79d5-4244-b8bd-0213096b69fe.png)

### Version

1.6.1rc5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by advlive** [comment]
go to setting and make off Hide objectionable content to show all NFT in ChiaSetup-latest-dev 1.6.1.rc5-dev93
![549898](https://user-images.githubusercontent.com/73825960/199645012-56dab6e3-8e81-4684-a191-ff708385dd5e.jpg)

**Comment by Svetyr** [comment]
> перейдите к настройке и снимите флажок Скрыть нежелательное содержимое, чтобы показать все NFT в ChiaSetup-latest-dev 1.6.1.rc5-dev93 ![549898](https://user-images.githubusercontent.com/73825960/199645012-56dab6e3-8e81-4684-a191-ff708385dd5e.jpg)

this does not fix the error

**Comment by paninaro** [comment]
Metadata character encoding issues have been addressed with https://github.com/Chia-Network/chia-blockchain-gui/pull/1147

**Comment by paninaro** [comment]
Image fitting setting has been added with PR https://github.com/Chia-Network/chia-blockchain-gui/pull/1211
