### ISSUE TITLE
[Bug] nft_mint_nft -j rpc.json cant set fee

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#13808]
### What happened?

im trying to mint nfts with an rpc.
The resulting transaction wont include the fee which makes the process take hours or days per nft and locking up balance.

This is my rpc.json
```
{
    "wallet_id": 4, 
    "uris": ["https://nft.kryptomine.ch/Kryptomine_Basecollection/KryptoMine_Logo.png","https://bafybeicwmyirgdb7cul5jy66rls73ww4fhyb5y7y6qfjjz54qtvepfausu.ipfs.nftstorage.link/"], 
    "hash": "03c23e13df7ce9ab303ed4210bd8d6d7ff9910df928b2a8be779c6ad3d660c71", 
    "meta_uris": ["https://nft.kryptomine.ch/Kryptomine_Basecollection/KryptoMine_Logo.json","https://bafkreidycvdxqbnsevhsngzq2gkbo6sf6hhwvqsnkpkyufvkdjfxol2q5y.ipfs.nftstorage.link/"], 
    "meta_hash": "7815477805b2254f269b30d194177a45f1cf6ac24d53d58a16aa1a4b772f50ee", 
    "license_uris": ["https://nft.kryptomine.ch/Kryptomine_Basecollection/KryptoMine_Logo_License.txt","https://bafkreigj4vrboii67oj2ygmgrjzz4bmig5vfnzlxwfzbkxajhumk7qro2q.ipfs.nftstorage.link/"], 
    "license_hash": "c9e56217211efb93ac19868a739e0588376a56e577b172155c093d18afc22ed4", 
    "royalty_address": "xch1548hhy66czjf026cc9a3efsu2mrjh9he3w5rna3rsrenlyhpe9dq5u7f4g", 
    "royalty_percentage": 900, 
    "target_address": "xch1548hhy66czjf026cc9a3efsu2mrjh9he3w5rna3rsrenlyhpe9dq5u7f4g",
    "edition_number": 1, 
    "edition_total": 1, 
    "fee": 0.0001
}
```
The official documentation https://docs.chia.net/nft-rpc/ specifies a field fee but notably the examples do not include it.
I have verified with other creators that they are using a fee but they may use another process such as cli (which I avoid because creating an rpc is way better automatable for me.

used command:
```
chia rpc wallet nft_mint_nft -j C:\temp\rpc.json
```

Resulting Transactions:
![image](https://user-images.githubusercontent.com/12736950/199732159-e810322f-8202-4906-b54a-6f9b44c74dff.png)

### Version

1.6.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by trepca** [comment]
The fee should be in mojos not XCH.

**Comment by forReason** [comment]
yes. I was able to create nfts after a while.
There were some error messages stating that fee must be a value between 0 and 0.5... 
Tomorrow is the next minting run so I will see if I can reproduce this error message
