### ISSUE TITLE
Chia is trying to start the daemon while it was told to run only the harvester (1.0.0)

### ISSUE THREAD

**Issue by Shekelme** [Chia-Network/chia-blockchain#1381]
**Describe the bug**
When I give the `chia start harvester` command under Windows (following the [instructions](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines)), chia is trying to start the daemon.

**To Reproduce**
Give the `chia start harvester` command inside `app-1.0.0\resources\app.asar.unpacked\daemon` folder under Windows.

**Expected behavior**
There sould only the harverster process be started.

**Screenshots**
![image](https://user-images.githubusercontent.com/26449500/111787651-c5aedf80-88f1-11eb-8d4b-0414831fb0ec.png)
This is a firewall asking for network permissions for chia when it is trying to start the daemon.

**Desktop (please complete the following information):**

- OS: Windows 7 x64 Ultimate

**Comment by mariano54** [comment]
The daemon is required to run any of the services. It is what manages starting and stopping services.
