### ISSUE TITLE
[BUG] 1.0.0 windows installer fails to upgrade / install

### ISSUE THREAD

**Issue by fiveangle** [Chia-Network/chia-blockchain#1382]
Functioning 0.2.9 install is stopped and node shutdown
1.0.0 installer launched and borks on attempting to install discord:

> 2120> 2021-01-09 14:05:00> Program: About to install to: C:\Users\speedster\AppData\Local\Discord
> 2120> 2021-01-09 14:05:00> Program: Install path C:\Users\speedster\AppData\Local\Discord already exists, burning it to the ground
> 2120> 2021-01-09 14:05:00> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\speedster\AppData\Local\Discord\app-0.0.309\Discord.exe' is denied.

1) why TaF is it attempting to install discord  ?
2) so much for the mainnet launch - lol

- OS: windows 10 at current patchlevel
- CPU: ryzen 3600

Uninstalled Discord completely, removed all traces of discord from both AppData Local, LocalLow, and Roaming, same result

![chiafail](https://user-images.githubusercontent.com/2219447/111790156-23eeaa80-887f-11eb-9ef2-52ec89bc2ebb.png)

Install fail log:

[SquirrelSetup.log](https://github.com/Chia-Network/chia-blockchain/files/6171515/SquirrelSetup.log)

**Comment by fiveangle** [comment]
doing the same full-clean + also rebooting allowed install to complete, so suspect likely untracable problem with installer since I don't know how one would be able to reproduce.

One thing that makes no sense is I checked afterward and there is no discord installed, so it really begs the question of what the heck was going on there.

**Comment by fiveangle** [comment]
closing because reviewing the code here, there's no depedance on discord so i suspect this was a local Windows Explorer UI corruption problem where I launched "ChiaSetup-1.0.0.exe" but likely instead launched the Discord installer (also in the same downloads directory) ?  Seems rediculously implausible, esp since the window name above, but not sure anything else makese sense? After rebooting, install worked, no discord was installed, and this was all using the same installer binaries as before.  I've confirmed also that launching the discord installer in fact launched the discord installer (which didn't fail either).  Serious weirdness but as no one else is having the issue, gonna chalk this one up to Windows gremlins.

**Comment by fiveangle** [comment]
Found evidence this was in fact a legitimate error so reopening so can e assigned accordingly

**Comment by hoffmang9** [comment]
Please try the 1.0.1 installer. However, the only thing that could cause anything like that is the Electron components.

**Comment by fiveangle** [comment]
when the horse is dead, dismount... got it.  I'll close this out and leave it to others to find in future if it isn't automagically fixed somewhere along the way :)
