### ISSUE TITLE
[Bug]  Absence of "chia-blockchain" binary in  64-bit Linux deb

### ISSUE THREAD

**Issue by stmuk** [Chia-Network/chia-blockchain#13847]
### What happened?

dpkg -i chia-blockchain_1.6.1_amd64.deb

Gui client is now "/opt/chia/@chiagui" rather than  "chia-blockchain".

Unsure if this is intentional since it's not documented in the  release notes (at least as far as I can see!)

### Version

1.6.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by rinnino** [comment]
same here.

1.6.1 under linux ( updated with apt-get install )

**Comment by wallentx** [comment]
Is it not under `/use/bin/chia`?
@altendky tested the CLI binary locations for both 1.6.0 (old installer) and 1.6.1 (new installer)
https://gist.github.com/altendky/77e51871eeda2ae871e53c511c4b712c

**Comment by altendky** [comment]
> Is it not under `/usr/bin/chia`? @altendky tested the CLI binary locations for both 1.6.0 (old installer) and 1.6.1 (new installer) https://gist.github.com/altendky/77e51871eeda2ae871e53c511c4b712c

I did, and I noted that `chia-blockchain` is missing from 1.6.1 as described in this bug.  `:]`
