### ISSUE TITLE
Install error on Ubuntu 20.04 [BUG]

### ISSUE THREAD

**Issue by namelessperson0** [Chia-Network/chia-blockchain#1384]
**To Reproduce**
Followed introductions in https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL for installing in ubuntu.

Got the below error
`/home/info/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGSEGV
`
**Screenshots**

![Screenshot from 2021-03-19 22-18-33](https://user-images.githubusercontent.com/72940077/111815012-2eea1f00-8901-11eb-9849-2e94eef8f6a4.png)

- OS:  Ubuntu 20.04

**Comment by anieto** [comment]
I'm getting the same error. Tried deleting an reinstalling multiple times. All this on a clean install of Ubuntu.

**Comment by mariano54** [comment]
What node and npm version are you running?
@seeden have you seen this issue?

**Comment by Cryolitecoin** [comment]
You need a gui like xfce or anything and it will work

**Comment by namelessperson0** [comment]
> You need a gui like xfce or anything and it will work

I am trying it on a cloud server which is causing this GUI issue I think. Could you farm and plot without install-gui.sh and with install.sh alone?

**Comment by namelessperson0** [comment]
> I'm getting the same error. Tried deleting an reinstalling multiple times. All this on a clean install of Ubuntu.

Tried thrice on clean Ubuntu.

**Comment by nur-azhar** [comment]
why not try on fedora 33
works flawlessly for me

**Comment by seeden** [comment]
Can anybody try to use DEV version of https://github.com/Chia-Network/chia-blockchain-gui/tree/dev ? We merged one issue related to starting of the GUI a few minutes ago

**Comment by jonassunandar** [comment]
> Can anybody try to use DEV version of https://github.com/Chia-Network/chia-blockchain-gui/tree/dev ? We merged one issue related to starting of the GUI a few minutes ago

I just changed the branch from main to dev in .gitmodules  and still got the exact error sir.

**Comment by hoffmang9** [comment]
Try running `sh install-gui.sh dev` to be sure you actually get the dev branch

**Comment by adamantine-dev** [comment]
Hi @seeden and @hoffmang9.
I have the same issue described in the topic here.

I've switched to the dev branch and run `sh install-gui.sh dev`.
As a result, the GUI is opened:
<img width="1359" alt="Screen Shot 2021-03-20 at 21 00 48" src="https://user-images.githubusercontent.com/21975467/111884162-0c6b0b00-89c0-11eb-81ea-fca00e3d846d.png">
 
But nothing happened after that. I just see the "Connecting to wallet" message.

Meantime, there are errors in the terminal window:
<img width="1346" alt="Screen Shot 2021-03-20 at 21 01 40" src="https://user-images.githubusercontent.com/21975467/111884197-46d4a800-89c0-11eb-8fac-fa9aa4656e88.png">

What can I do else to help you resolve the issue?

**Comment by hoffmang9** [comment]
That last point hints that either you've got a zombie chia daemon running on 55400 or something else is using that port on your machine.

**Comment by jonassunandar** [comment]
> Try running `sh install-gui.sh dev` to be sure you actually get the dev branch

still get the exact same error

**Comment by seeden** [comment]
I will install Ubuntu and try to fix it

**Comment by adamantine-dev** [comment]
@hoffmang9 I did the same steps (build GUI of dev branch) on a fresh Ubuntu instance and the result completely the same as on the screenshots above.
I've checked ports' using and no apps or processes are using it.

CC: @seeden

**Comment by adamantine-dev** [comment]
@seeden @hoffmang9 do you have any updates? :)

**Comment by hoffmang9** [comment]
@adamantine-dev Give this beta installer a try? https://download-chia-net.s3-us-west-2.amazonaws.com/tests/chia-blockchain_1.0.0_amd64.deb

**Comment by adamantine-dev** [comment]
@hoffmang9 have the same error:

<img width="952" alt="Screen Shot 2021-03-23 at 22 43 08" src="https://user-images.githubusercontent.com/21975467/112222738-41c66180-8c29-11eb-8626-c9bceaafe2e9.png">

**Comment by hoffmang9** [comment]
All, please try the 1.0.1 release.

**Comment by seeden** [comment]
I am still working on it. It will be fixed today

**Comment by seeden** [comment]
I see two problems:
1. Starting of the electron application is fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/203
2. Issue related to infinite loading (https://github.com/Chia-Network/chia-blockchain/issues/1384#issuecomment-803456776) is a problem on the backend side.

I check it in virtual computer and I see 2 processes with the name chia_full_node. Just one is closed when I close the electron application. The second one is still there and I need to kill it by myself. @Yostra can you check this issue?

**Comment by adamantine-dev** [comment]
@seeden just checked the latest update on the latest nodejs version.
You are right:
- electron application is opening now.
- but infinite loading still there.

And the issue "attempting to bind on address 55400" also there.

**Comment by Clish254** [comment]
I have the infinite loading issue on ubuntu 18.04 with node 14.16.0 as well.
![Screenshot from 2021-03-25 19-51-02](https://user-images.githubusercontent.com/29974159/112511429-765e2880-8da3-11eb-8867-7eccd7a6c612.png)

**Comment by mariano54** [comment]
These bugs are covered in other things.
Zombies, install error (fixed), connecting to wallet (https://github.com/Chia-Network/chia-blockchain/issues/1622)

**Comment by Tongie969** [comment]
Still getting the same error, did I miss a fix?

**Comment by hoffmang9** [comment]
Fixed in 1.0.5. Are you trying to install as root? That is specifically not supported.
