### ISSUE TITLE
[Bug] Wrong NFT data show when moving NFT to a profile

### ISSUE THREAD

**Issue by Ganbin** [Chia-Network/chia-blockchain#13851]
### What happened?

When I move a NFT to a profile, it show me the correct image, the correct NFT ID, but the wrong metadata.

As you can see here:
NFT ID : `nft1yp5jgsc97my67vag9gpxcvtdk33m3dcjdjxh3s0vy8f230a4yvtst4wksu`
<img width="604" alt="2022-11-07_09-34-30" src="https://user-images.githubusercontent.com/1487962/200263553-74743dbf-e176-4010-afae-8f1df6880832.png">
It should show `Crew Member #0783` but it shows `City Flag #0480`

### Version

1.6.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by aaronscientiae** [comment]
I'm seeing this too. 1.6.1. It shows wrong the first time moving nft to another wallet, then if I reopen the dialog it shows the right text. When I switch to the other wallet that received it, it shows the wrong text from the first wallet, wrong wallet entirely.

**Comment by CommanderMoto** [comment]
<img width="1202" alt="Screen Shot 2022-11-21 at 6 51 26 PM" src="https://user-images.githubusercontent.com/65326/203209674-5378e60a-a50f-45e3-b484-10f3414dc8ef.png">
Just about had a heart attack.
Bump.

**Comment by emlowe** [comment]
Closing old issue - it will be reopened if the problem persists, but numerous related fixes have been implemented since this was originally reported
