### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wangzhenyue** [Chia-Network/chia-blockchain#13864]
### What happened?

For Block 2792181 Not received XCH
![2022-11-08 (7)](https://user-images.githubusercontent.com/6030578/200542504-07475606-1d02-4905-b08f-a8f0ec8a7ef3.png)
But I didn't receive 10.5XCH Total Balance BUG 

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BernardJin** [comment]
您可以在这里说中文，或向中文社区求助。

**Comment by emlowe** [comment]
Closed due to lack of response
