### ISSUE TITLE
Install error Ubuntu 20.04.2 LTS [BUG]

### ISSUE THREAD

**Issue by nickster64** [Chia-Network/chia-blockchain#1387]
I followed the Ubuntu install instructions provided at https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian and receive this error when I run command "npm run electron &"

`error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

![Screen Shot 2021-03-19 at 4 42 32 PM](https://user-images.githubusercontent.com/35485639/111846289-61dee380-88fe-11eb-8ed5-08eb7320a774.png)

![Screen Shot 2021-03-19 at 4 42 12 PM](https://user-images.githubusercontent.com/35485639/111846099-06acf100-88fe-11eb-97f4-1037c5aa85ea.png)

I'm just messing around and testing this out on an Azure virtual machine. Any advice is appreciated. Thanks!

**Comment by hoffmang9** [comment]
You need to install libnss3.so with apt

**Comment by hoffmang9** [comment]
Your bigger problem will likely be that the GUI needs Desktop which I doubt an Azure instance has.
