### ISSUE TITLE
[Bug] Switching Pool Does not Work Until Restarting

### ISSUE THREAD

**Issue by otterslide** [Chia-Network/chia-blockchain#13872]
### What happened?

I click to Join or leave a pool. Press submit.
The status changes to "Pending" and then to "Pooling" for joining.
However, nothing updates after that, points stay at zero, and pool does not receive partials. The view pool URL is empty. 
This remains until the client is restarted, I only waited about 10 minutes each time,.. It used to work right away once Pooling is displayed on previous clients.
When going to self-pooling from Pooling. The "Pooling" status remains until restarted, even after transaction is confirmed and the pool shows many invalid partials.
I tried 1.6.0 and 1.6.1

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by heget** [comment]
I confirm the same issue. Try to join pool and after one hour still nothing.

**Comment by HVNC1** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/13938

**Comment by aqk** [comment]
> the same problem. waited more than an hour. when rebooting after 2-3 minutes the process starts normally

When you reboot, does it change pools?

**Comment by otterslide** [comment]
> 



> > the same problem. waited more than an hour. when rebooting after 2-3 minutes the process starts normally
> 
> When you reboot, does it change pools?

When you reboot it does change the pool finally yes. Just don't try to cancel anything once it's not working, because that will mess things up. Reboot is the fix, not cancel / delete transactions.

**Comment by emlowe** [comment]
Confirmed and reproduced - work in progress on fixes.

**Comment by emlowe** [comment]
This was fixed in 1.6.2

**Comment by otterslide** [comment]
> This was fixed in 1.6.2

What is the expected behavior for leaving a pool and switching to self-pooling? I upgraded to 1.6.2. I just left Space pool, it has been about 10 minutes. Space pool confirms that I have left the pool and my launcher ID is no longer assigned to space pool, however, the client is still sending partials and in Pending state. 
Is this expected? I don't understand why the client would be sending partials after the launcher ID is no longer assigned to the pool?
Also, I'm not sure how it works really, once the launcher ID is not assigned to the pool any more, am I already self-pooling, or is there a transition phase to "join" self-pooling after leaving?
In Either case, sending partials to the pool once the launcher ID is no longer assigned doesn't make sense, and pools end up rejecting those.. but it's really a waste to keep sending them.

**Comment by otterslide** [comment]
>  It took another 5-10min and the client joined self-pooling, so it's working as expected.

One strange this that happened after going to self-pooling from pooling, when I re-joined a pool again, I got an "Unconfirmed transaction" error, so I had to click delete unconfirmed transactions and then it worked. Not sure why that happened, I did not make any additional transactions between leaving and re-joining, and I was self-pooling for a whole day.
I am not sure what the uncofirmed transaction was.. 
It may be a good idea to display pool related transactions in a table on the pool tab, right now I believe they cannot be viewed if they have a 0 fee?

**Comment by otterslide** [comment]
> > It took another 5-10min and the client joined self-pooling, so it's working as expected.
> 
> One strange thing that happened after going to self-pooling from pooling, when I re-joined a pool again, I got an "Unconfirmed transaction" error, so I had to click delete unconfirmed transactions and then it worked. Not sure why that happened, I did not make any additional transactions between leaving and re-joining, and I was self-pooling for a whole day. I am not sure what the uncofirmed transaction was.. It may be a good idea to display pool related transactions in a table on the pool tab, right now I believe they cannot be viewed if they have a 0 fee?

Also the block height the join transaction is waiting for to proceed would be nice to know.
