### ISSUE TITLE
[BUG] Plot setup failing

### ISSUE THREAD

**Issue by kgn** [Chia-Network/chia-blockchain#1389]
I am trying to setup a plot on the same external hard drive I'm using time machine for.

I've tried to create a plot multiple times and when viewing the log always get this error.

```
Caught plotting error: Could not open /Volumes/Time Machine/plot-k32-2021-03-19-14-52-fa38e0a4df1396e6f9516edfbcfefbf595a48efcddb5abccd4cd5ada128e300e.plot.sort.tmp: Permission denied
Traceback (most recent call last):
  File "src/cmds/chia.py", line 63, in <module>
  File "src/cmds/chia.py", line 59, in main
  File "click/core.py", line 1026, in __call__
  File "click/core.py", line 956, in main
  File "click/core.py", line 1518, in invoke
  File "click/core.py", line 1518, in invoke
  File "click/core.py", line 1280, in invoke
  File "click/core.py", line 711, in invoke
  File "click/decorators.py", line 22, in new_func
  File "src/cmds/plots.py", line 134, in create_cmd
  File "src/plotting/create_plots.py", line 164, in create_plots
RuntimeError: std::exception
[13961] Failed to execute script chia
```

- OS: macOS Big Sur
- OS Version: 11.3 Beta (20E5210c)
- CPU: 2.9 GHz Quad-Core Intel Core i7

**Comment by hoffmang9** [comment]
You are trying to plot in a directory you don't have permissions for. It looks like you've chosen your Time Machine directory.

**Comment by bwbloom** [comment]
> You are trying to plot in a directory you don't have permissions for. It looks like you've chosen your Time Machine directory.

Is there a for the process that is happening, or is it just the logged in user?

**Comment by kgn** [comment]
It was a permissions issue, once I fixed that I was able to plot. But it was not clear this was the issue. This was with the 1.0 version of the client so this may have been improved now.

**Comment by bwbloom** [comment]
@kgn I have been running into what I think is that exact same issue over and over and over again. It has been driving me insane for days now. I think you are right it has something to do with permissions (specifically when mounting drives for me). I had it in VM after VM. I ran into it in bare metal. I could not get past it. I am definitely a noob with this stuff, but I am shocked at how little posting I am seeing around this same issue as I think this comes up when I follow the git install instructions verbatim.

I finally have my first drive plotting after following a guide a found on chiadecentral.com but I really only was looking at the mounting process they detail. Once the first plot actually works I am going to try and backtrack and create a more detailed issue. I don't understand how I am the only one that has run into this pervasively.

**Comment by GithuRobson** [comment]
Change how to write and read permissions on properties of the drive or folder you want to read or write.
on the ubuntu terminal
sudo nautilus
then properties of the driver folder or drive.
in permits
> change reading and writing.
save to the guys from BRAZIL / PIRASSUNUNGA-SP

**Comment by praveenkumar2525** [comment]
Read/Write permissions are there, but still I'm getting the same error.  Can any ne help me on how to solve the issue

**Comment by kreaninw** [comment]
I faced this issue today in Ubuntu 21.04. Make sure you only format the drive for both temp and final files in the Disk app. If you happen to format the drive in GParted, for some reason, the drive will belong to root and you won't be able to use it in Chia.

I'm using GUI by the way.
