### ISSUE TITLE
[Bug] Wallet does not show some nfts

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#13898]
### What happened?

My wallet seems to not show some nfts. I was able to create offers for them before (so they were in my wallet)
I can inspect the offer file and it shows the nft

Mintgarden shows that I am the owner of the nft:
https://mintgarden.io/nfts/cryptocrest---templar-order----nft1pyzuhe8yztqn75qkngqsj3ls9cha23c220ur77l7he3nmszggnwsgn80f3
![image](https://user-images.githubusercontent.com/117320700/201477696-c3929812-5af1-488b-a334-04ede25abd27.png)

![image](https://user-images.githubusercontent.com/117320700/201477723-9d230a4b-463a-4dc2-a4ef-93db6af729d1.png)

### Version

1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Is this behavior consistent between launches?

**Comment by KryptomineCH** [comment]
yes the bahavior is consistent.
The NFTs are definitely in the wallet. I can see them on my Laptop which also has 1.6.1 installed.

**Comment by KryptomineCH** [comment]
issue coulnd be reproduced anymore
