### ISSUE TITLE
M1 Mac get buggy when Chia is loaded.

### ISSUE THREAD

**Issue by conquer451** [Chia-Network/chia-blockchain#1392]
**Describe the bug**
New M1 has been dropping drives connected via usb-c. Apple has run every diagnostic possible on the device and claims they can find nothing wrong. Only thing I use the device for is plotting Chia. Have been reduced to only using internal HD and external HD connected via usb 3.1. All drives that are connected via the usb-c ports get ejected by the computer and get the spinning cursor wheel when trying to browse files in them with finder. Even when the devices are brand new with no files on them. Is this something Chia could cause? My older 2018 Mac mini is working perfectly fine with same devices.

**To Reproduce**
Open chia, try to browse usb-c connected devices using finder with simply Chia running. Sometimes spinning wheel, sometimes computer crashes.
Plotting is not even possible. It hangs on the first step and can't even begin table 1.

Internal drive works fine and devices connected through 3.1 ports work fine.

**Desktop (please complete the following information):**

- OS:Big Sur 11.2.3

- CPU: Apple M1

**Comment by hoffmang9** [comment]
Reading between the lines - are you using external SSD? If so, how is your heat management on them? Chia will push their temps and if you don't have good heat sinks and/or fans, they will thermal shut down.

**Comment by conquer451** [comment]
Using nvme mounted in usbc with heat sink and built in fan. Only slightly warm to the touch. It also happens to my spinning disks when I plug them in on the usb-c ports. 

Same devices plugged in usb 3.1 ports next to the usb-c ports and devices work just fine, but sooo slow. 

In all honesty I’m not seeing how Chia could be the cause of these issues and am considering returning the computer. My older 2018 Mac mini is killing it! 4 nvme drives on each usb-c port can all plot simultaneously and generate 8-10 plots in 24 hrs. My biggest bottle neck is the transfer to the spinning disk of the final plot. 

Get some sleep Hoffman, you had a great launch day and have earned it. 
Thanks for the help,
Blake
