### ISSUE TITLE
bugs when connecting and disconnecting to pools [Bug] 

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#13938]
### What happened?

![QIP Shot - Screen 657](https://user-images.githubusercontent.com/95166695/202457115-106ad5e4-3980-402f-ba3a-66f4294fcae7.png)
when I connect to the pool nothing happens for several hours until I restart the chia client. the commission I specify is large (100,000 mojo) and there is no dust storm.

when disconnecting from the pool, the name of the pool remains even though I am solo

### Version

1.7.0 b1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Duplicates #13872 https://github.com/Chia-Network/chia-blockchain/issues/13872
