### ISSUE TITLE
Solo Chia never show up in my wallet.. 

### ISSUE THREAD

**Issue by ramet99** [Chia-Network/chia-blockchain#13933]
Hit a solo plot.  Only got the .25.  I claimed the 1.75, but never show up at my wallet.
https://xchscan.com/address/xch16yf94t4jf2czdn7ehruhsjvmf44zyzxydhvzjz3tc64xz5y48fasaeqqet

**Comment by heget** [comment]
I have the same problem since 1.5.1. version.
Windows, GUI, 1.5.1. > 1.6.1.

**Comment by shaneo257** [comment]
known issue https://github.com/Chia-Network/chia-blockchain/issues/13251

**Comment by ramet99** [comment]
My balance doesn't increase by 1.75 like the others.  I see it send via xchscan.
Do I have to resync my wallet?
https://xchscan.com/address/xch16yf94t4jf2czdn7ehruhsjvmf44zyzxydhvzjz3tc64xz5y48fasaeqqet
