### ISSUE TITLE
[Bug] DataLayer RPC for 'get_owned_stores' returns stores not owned by my key

### ISSUE THREAD

**Issue by ccornick** [Chia-Network/chia-blockchain#13969]
### What happened?

After setting up a new Chia node/datalayer DB (and running some Climate Warehouse commands), when I ran 'chia data get_owned_stores' in CLI, the response returned data stores that I did not recognize and many more stores than I was expecting.

<img width="1728" alt="Screen Shot 2022-11-21 at 9 41 11 AM" src="https://user-images.githubusercontent.com/98057517/203082903-333ecf77-db6a-437a-bb01-bfc965795c35.png">

### Version

Latest Dev 11/18/2022

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
I haven't noticed this in some time, might have been fixed along the way - closing and can re-open if we experience again
