### ISSUE TITLE
[Bug] / Feature Request - Windows GUI no longer autostarts farming since 1.6.1

### ISSUE THREAD

**Issue by Meatball13** [Chia-Network/chia-blockchain#13974]
### What happened?

Starting with v1.6.1, the windows GUI no longer automatically starts up the Wallet and/or Farming on launch.  Instead it pauses on a selection screen waiting for user input to select Wallet mode or Farming Mode.  Not sure if this is by design or an oversight during the latest updates, and while I appreciate this, some of us have Chia set to automatically start up on launch in case of crash/reboot, and would like it to just start farming.  

Can we get a checkbox or something that will allow a default selection to just start on launch without waiting for user input?

### Version

1.6.1 / 1.7.0b2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
Are you still having this problem? @emlowe said that he was helping you in Keybase with a similar issue.

**Comment by Meatball13** [comment]
Ah man, I'm sorry, I forgot to respond.  We did get it fixed, but I basically had to do a complete uninstall/removal of everything and then do a clean install.

**Comment by emlowe** [comment]
Closing issue
