### ISSUE TITLE
[Bug] Re-creating wallet DB takes much longer in 1.7.0-b2

### ISSUE THREAD

**Issue by ghost** [Chia-Network/chia-blockchain#14001]
### What happened?

With 1.7.0-b2: Creating wallet database from scratch takes ~1 hour.

With 1.6.2: Creating wallet database from scratch takes several minutes.

### Version

1.7.0-b2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
This is not generally reproducible - closing
