### ISSUE TITLE
[Bug] Wallet 1.7.0-b2 is missing many transactions

### ISSUE THREAD

**Issue by atomsymbol** [Chia-Network/chia-blockchain#14002]
### What happened?

After updating from 1.6.2 to 1.7.0-b2, if the Chia 1.7.0-b2 node is started with the wallet DB from 1.6.2:

The wallet fails to properly record new transactions. The wallet balance becomes invalid after just a few new transactions.

### Version

1.7.0-b2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by nqzhang** [comment]
Also confirmed in 1.7.0-rc2
@wallentx

**Comment by wallentx** [comment]
Are you able to provide any logs that might help point us in the right direction?

**Comment by nqzhang** [comment]
> Are you able to provide any logs that might help point us in the right direction?

This is the transaction record for wallet  1.6.1

![1 6 1_algold](https://user-images.githubusercontent.com/12559853/206616244-1338a795-7c90-4f6d-87b0-8e1f5df8d8c0.png)

Then upgrade chia to 1.7.0-rc2
delete wallet db
delete log in .chia/mainnet/log/debug.log
resync wallet db
Here are all logs during wallet sync
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/10191578/debug.log)

**Comment by paninaro** [comment]
Can you try to adjust the following setting in your config.yaml?
`  max_subscribe_items: 200000`

Try bumping the value to something like 400000

Because you appear to have an especially large number of CAT wallets, it may be that your full node is hitting this `max_subscribe_items` limit.

Also set `connect_to_unknown_peers` to false to avoid hitting untrusted full node peers that may have a lower limit set.
`  connect_to_unknown_peers: false`

**Comment by paninaro** [comment]
@Quexington the debug log includes a bunch of exceptions like the following:

```2022-12-09T11:20:28.490 wallet chia.wallet.cat_wallet.cat_wallet: WARNING  Not creating wallet for already existing CAT wallet
2022-12-09T11:20:28.491 wallet chia.wallet.wallet_state_manager: ERROR    Error adding state... Wallet already exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/chia/wallet/wallet_state_manager.py", line 1034, in new_coin_state
    wallet_id, wallet_type = await self.determine_coin_type(peer, coin_state, fork_height)
  File "/usr/local/lib/python3.10/dist-packages/chia/wallet/wallet_state_manager.py", line 637, in determine_coin_type
    return await self.handle_cat(cat_curried_args, parent_coin_state, coin_state, coin_spend)
  File "/usr/local/lib/python3.10/dist-packages/chia/wallet/wallet_state_manager.py", line 730, in handle_cat
    cat_wallet = await CATWallet.create_wallet_for_cat(self, self.main_wallet, bytes(tail_hash).hex()[2:])
  File "/usr/local/lib/python3.10/dist-packages/chia/wallet/cat_wallet/cat_wallet.py", line 195, in create_wallet_for_cat
    raise ValueError("Wallet already exists")
ValueError: Wallet already exists
```

Looking at the exception handler in `new_coin_state`, is it possible for coins to be skipped (not added) in the above case?

```python
            except Exception as e:
                self.log.exception(f"Error adding state... {e}")
                if isinstance(e, PeerRequestException) or isinstance(e, aiosqlite.Error):
                    await self.retry_store.add_state(coin_state, peer.peer_node_id, fork_height)
                else:
                    await self.retry_store.remove_state(coin_state)
                continue
```

**Comment by Quexington** [comment]
> Looking at the exception handler in new_coin_state, is it possible for coins to be skipped (not added) in the above case?

Not skipped so much as infinitely retried to no success.  This PR should fix the issue that keeps the coin from getting added successfully: https://github.com/Chia-Network/chia-blockchain/pull/14101

**Comment by Oscillator098** [comment]
I have the same exact issue on issues/13963
It is pretty bad. It messes solo and pool ploting switching. I got commiting partials to non existing pool because i was self pooling.

**Comment by emlowe** [comment]
Closing issue to to lack of response
