### ISSUE TITLE
[Bug] 1.6.1 There is a bug in the transaction fee valuation system, which is too imprecise.

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#14007]
### What happened?

When can Chia be more rigorous, the transaction fee valuation system on the official version 1.6.1 is invalid in the light wallet mode, please don’t make such low-level mistakes. Can you be more rigorous, like you are really doing things.

### Version

1.61

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by geraldneale** [comment]
Imprecise in what way? Overestimates fees required for the times stated? If so, that is also my observation 99.9% of the time. Frankly this looks too much like an attempt at drumming up artificial fee pressure from the wallet client for me NOT to say something at any opportunity. Also, it should default to zero fees for a good long while if we at all care about avoiding this criticism.
