### ISSUE TITLE
accept an offer multiple times [Bug] 

### ISSUE THREAD

**Issue by nqzhang** [Chia-Network/chia-blockchain#14021]
### What happened?

Why an offer can  be accepted multiple times in the wallet, should it only be accepted once?

### Version

1.6.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wallentx** [comment]
The issue described here causes the behavior seen in https://github.com/Chia-Network/chia-blockchain/issues/14020 and https://github.com/Chia-Network/chia-blockchain/issues/14027
