### ISSUE TITLE
"RuntimeError: bad allocation" when setting up a Plot [BUG]

### ISSUE THREAD

**Issue by nickster64** [Chia-Network/chia-blockchain#1402]
I see this error in the log when setting up my first Plot:  "RuntimeError: bad allocation" 

![Screen Shot 2021-03-20 at 1 55 13 PM](https://user-images.githubusercontent.com/35485639/111883505-c3ad5500-89b3-11eb-9fe2-a07cdb3e4f59.png)

- Azure VM instance
- OS: Windows 10 Pro
- OS Version: 2004
- OS Build: 19041.867
- CPU: Intel(R) Xeon(R) Platinum 817M CPU @ 2.60GHz, 4 GB RAM, 64-bit x64-based processor
- Storage: 511 GB SSD

Any advice or tips is appreciated. Thank you!

**Comment by hoffmang9** [comment]
You should start with the settings recommended here: https://www.chia.net/2021/02/22/plotting-basics.html
