### ISSUE TITLE
[Enhancement] The icon on the windows side is too ugly, please optimize the icon to a rounded icon.

### ISSUE THREAD

**Issue by Concord-us** [Chia-Network/chia-blockchain#14048]
### What happened?

The icon on the windows side is too ugly, please optimize the icon to a rounded icon.

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by leokryp** [comment]
lol

**Comment by sethjenks** [comment]
This issue should be resolved with the release of 1.7.1
