### ISSUE TITLE
same issue again: "RuntimeError: bad allocation" when setting up a Plot [BUG]

### ISSUE THREAD

**Issue by nickster64** [Chia-Network/chia-blockchain#1405]
I followed the guidelines here https://www.chia.net/2021/02/22/plotting-basics.html and got this error again when setting up my first Plot: "RuntimeError: bad allocation"

I used these parameters when adding a Plot:

1. Choose Plot Size = 101.4GiB (k=32, temporary space: 332GiB)
2. Choose Number of Plots = 1, 
- Add Plot to Queue = checked
- RAM max usage = 3900 MiB
- Number of threads = 2
- Number of buckets = 128
- Queue Name = default
- Disable bitfield plotting = unchecked

![Screen Shot 2021-03-20 at 4 43 45 PM](https://user-images.githubusercontent.com/35485639/111886503-eba5b400-89c5-11eb-9391-ea6cb22ecb1f.png)

My specs:
Azure VM instance
OS: Windows 10 Pro
OS Version: 2004
OS Build: 19041.867
CPU: Intel(R) Xeon(R) Platinum 817M CPU @ 2.60GHz, 4 GB RAM, 64-bit x64-based processor
Storage: 511 GB SSD

Any advice or tips is appreciated. Thank you!

**Comment by zachlankton** [comment]
This is most likely happening because you don't have enough RAM.  The operating system is using some, so 3900 allocation is probably too much. Try setting this to 2500 minimum as recommended in the guide.  Or upgrade your ram.

On a slightly related note, it is likely your VM instance is not the best for plotting.  Plotting is best done on dedicated hardware.

**Comment by nickster64** [comment]
Thanks for your reply. I set RAM to 2500 and received the same error. Looks like it's a no-go with this set up. 

![Screen Shot 2021-03-20 at 9 18 34 PM](https://user-images.githubusercontent.com/35485639/111891545-cc218200-89eb-11eb-8819-a4cca0829f45.png)

**Comment by zachlankton** [comment]
What version of the software are you using?

**Comment by nickster64** [comment]
> What version of the software are you using?

![Screen Shot 2021-03-20 at 11 13 59 PM](https://user-images.githubusercontent.com/35485639/111893618-ed8a6a00-89fb-11eb-9a04-8677fdf345e5.png)



> This is most likely happening because you don't have enough RAM. The operating system is using some, so 3900 allocation is probably too much. Try setting this to 2500 minimum as recommended in the guide. Or upgrade your ram.

I upgraded the instance to 
<Standard D2s v3 (2 vcpus, 8 GiB memory), 512 GB Standard SSD LRS> 
and restarted a Plot and it looks good so far. This is neat! Glad I spent some time toying around with it today. Realistically, given the specs does this system have a shot at earning block rewards?

![Screen Shot 2021-03-20 at 11 14 05 PM](https://user-images.githubusercontent.com/35485639/111893635-0561ee00-89fc-11eb-9e2f-aa054c67219a.png)

**Comment by zachlankton** [comment]
Good to see you got it working!

Rewards are based on how much space you have plotted.  One k 32 plot is roughly 108 GB.  An expected rewards calculation example using 10TB (100 k 32 plots) of space on 50PB of network space [can be found in the FAQ](https://github.com/Chia-Network/chia-blockchain/wiki/Beginners-Guide) 

If you are currently paying for a cloud VM instance to do plotting on you may run out of money before you can afford the space to keep all of your plots.
