### ISSUE TITLE
Chia Blockchain Blank/White GUI on Pi3

### ISSUE THREAD

**Issue by rafiksheikh** [Chia-Network/chia-blockchain#1411]
**Describe the bug**
Followed installation steps on https://github.com/Chia-Network/chia-blockchain/wiki/Raspberry-Pi for Pi3 using 2020-08-20-raspios-buster-arm64.zip image. Not able to run Chia Blockchain,with nom run electron &.

**To Reproduce**

1. Steps same as https://github.com/Chia-Network/chia-blockchain/wiki/Raspberry-Pi2. Click on '....'
2. Fresh install. Tried twice

**Expected behavior**
Running Chia Blockchain GUI

**logs**

![Screenshot 2021-03-21 at 09 43 01](https://user-images.githubusercontent.com/76747204/111898995-d6fb0780-8a29-11eb-9f0d-0301d2cd8606.png)

**Screenshots**
![Screenshot 2021-03-21 at 09 36 39](https://user-images.githubusercontent.com/76747204/111898955-85527d00-8a29-11eb-95be-449252e58394.png)

**Desktop (please complete the following information):**

- OS: 2020-08-20-raspios-buster-arm64.zip image
- OS Version/Flavor: Raspbian 64bit
- CPU: Raspberry 1373331 Pi 3 Model B+ Motherboard, 1GB

**Comment by Cryolitecoin** [comment]
I get the same problem last week 
What I do is delete everything and reinstall chia 
everything work after that.

**Comment by rafiksheikh** [comment]
I already tried once installing it fresh. i.e. erasing pi image and repeating all steps. I think what you mean is delete / uninstall chia and reinstall chia only. If that is correct, appreciate if you can list down steps you followed.

**Comment by Cryolitecoin** [comment]
rm -rf chia-blockchain
apt update && apt upgrade -y 
reboot
after that follow all install instruction

**Comment by rafiksheikh** [comment]
Unfourtunatley it does not work.

From: Cryolitecoin ***@***.***>
Date: Sunday, 21 March 2021 at 13:51
To: Chia-Network/chia-blockchain ***@***.***>
Cc: rafiksheikh ***@***.***>, Author ***@***.***>
Subject: Re: [Chia-Network/chia-blockchain] Chia Blockchain Blank/White GUI on Pi3 (#1411)

rm -rf chia-blockchain
apt update && apt upgrade -y
reboot
after that follow all install instruction

**Comment by mariano54** [comment]
Can you check 1.0.1? This should be fixed.

**Comment by rafiksheikh** [comment]
When I do fresh install it will install latest version. Isn't it? What do you mean by check 1.0.1?

**Comment by dorkmo** [comment]
gotta git checkout the ner one

**Comment by mariano54** [comment]
Fixed in 1.0.3
