### ISSUE TITLE
Sending a CAT with a fee in the Windows CLI is not producing the same effect as sending a CAT with a fee in the Windows GUI (this might be true on other systems)

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14118]
CAT sent with a fee from the GUI:
![Image](https://user-images.githubusercontent.com/8990544/207227164-62993da6-bbcd-431c-a695-ff076acbeb0d.png)

CAT sent with a fee from the CLI:
![Image](https://user-images.githubusercontent.com/8990544/207227232-36dc8979-a9fe-4c30-a04e-b5d105481eda.png)

**Comment by MumfMeisterT** [comment]
@wallentx Can you confirm this has been fixed in 1.6.2?

**Comment by wallentx** [comment]
I verified that this is now working
