### ISSUE TITLE
[Bug]  Specific NFT not shown correctly and it can affect the formatting of NFT gallery

### ISSUE THREAD

**Issue by blupino** [Chia-Network/chia-blockchain#14126]
### What happened?

I only see this issue with mondo monkey NFT. This NFT contains unusual character and these character don't get displayed correctly. It also can affect the image formating inside the NFT gallery. The  image shown correctly as long as non affecting NFT get displayed, but if you keep scroll down and hit the mondo NFT,  the image scaling for all the NFT suddenly change and shown as zoomed-in.

This issue doesn't happen on 1.6.0, and it start to happen with 1.6.1 and until now 1.7.0rc3

### Version

1.7.0rc3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
I didn't see any meaningful log when the issue happen
```

**Comment by blupino** [comment]
Normal
![image](https://user-images.githubusercontent.com/93529296/207637178-7231baa9-ba06-4fcf-b3b8-1464b473f744.png)

When issue happen
![image](https://user-images.githubusercontent.com/93529296/207637596-b75b329c-9b39-4fca-a818-904612703a8f.png)

The offending mondo nft, shown zoomed-in 
![image](https://user-images.githubusercontent.com/93529296/207637990-6f5f99b5-aaa8-45e7-a608-18207b67f1d2.png)

**Comment by MumfMeisterT** [comment]
Can we get the NFT Identifier? 
This issue should be fixed with 1.6.2 release though.

**Comment by blupino** [comment]
nft13qqcumt9pdqs5hle27x4kcn8hnga26tj23xrf84efzcym5340sjswt7w57

**Comment by blupino** [comment]
The problem still happen with 1.6.2rc1

**Comment by paninaro** [comment]
Here's how it displays for me in 1.6.2rc1:

![image](https://user-images.githubusercontent.com/339312/208155748-2bda3f38-fec3-4dfb-a431-09eadbd027e6.png)

**Comment by blupino** [comment]
You are right, the issue solved. Thanks

**Comment by emlowe** [comment]
Closing as fixed
