### ISSUE TITLE
Congratulations and many thanks to the Chia team

### ISSUE THREAD

**Issue by santivu** [Chia-Network/chia-blockchain#14137]
Hi all,

after suffer several wallet issues, fundamentally due to the fact I was affected by a dust storm and receiving tons of quite small transaccions into my wallet, now after v. 1.6.1 and testing 1.7.0rc3 I tried to recreate my wallet deleting the folder and starting the GUI, thge wallet was fully synchronized in about 15 seconds!! I-M-P-R-E-S-S-I-V-E

Many thanks for your improvements guys.
And Merry Christmas!!

**Comment by MumfMeisterT** [comment]
Thank you for your comments and we're glad the new versions work for you! 
Have a Merry Christmas!
