### ISSUE TITLE
Various CLI issues with chia wallet coins {list,split.combine}

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14131]
Fixed by
https://github.com/Chia-Network/chia-blockchain/pull/14102
https://github.com/Chia-Network/chia-blockchain/pull/14100

**Comment by wallentx** [comment]
Fees are not correct for CATs here

**Comment by emlowe** [comment]
Issues:
Fees are calculated in CAT units in CAT wallets instead of XCH
Different short options for the same option in different commands: see `-b` for `split` and `-x` for `combine`.
Different long options: see `excluded-coin-ids` vs `exclude-coin-ids`
Display issues when listing CATs with `list`

**Comment by emlowe** [comment]
I do think most items are fixed in main with #14172 14172
