### ISSUE TITLE
Switching PlotNFT state falsely working

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14130]
Should be fixed by https://github.com/Chia-Network/chia-blockchain/pull/14090

**Comment by wallentx** [comment]
![Image](https://user-images.githubusercontent.com/8990544/207430589-3316a345-7cb1-4bec-ada1-7383dd3dd913.png)

As I understand the change from https://github.com/Chia-Network/chia-blockchain/pull/14090, this should no longer appear that everything has changed and is fine, but will remain in a Pending state?

There needs to be something that tells the user that they will need to restart Chia services in order for the changed state to take effect. Currently, all of the messaging says to _not_ restart chia until the state change is confirmed.

**Comment by MumfMeisterT** [comment]
This bug was introduced in 1.60. 
Should be fixed in 1.6.2
