### ISSUE TITLE
[Bug] improve wallet recovery after transactions fail to get accepted in mempool

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#14143]
### What happened?

Improve the ability for the wallet to recover any locked coins and get the spendable balance for transactions that don't successfully get accepted in mempool.

1.) multiple offer takers for the same offer, one actually gets the offer when it settles, the others continue to show pending offer transaction, and the wallet doesn't ever eventually reconcile those transactions that didn't make it into mempool. Recovery expectation here is that the wallet after locking coins for the offer will unlock those coins after it's been confirmed that the wallet didn't "win" the offer in this race condition.

2.) canceling an offer on-chain on the maker side is still not guaranteed if the cancellation request is kicked out of mempool (typically due to low/no fees), and the wallet doesn't recover and unlock the coins required for fees to get the spendable balance back to the way it was.

the state today is that the user has to know to go through and delete unconfirmed transactions to help get the wallet's spendable balance back to the way it was and for offers for cats w/ xch as fees (or multiple cats), the user has to go to each token to "delete unconfirmed transactions" to recover.

### Version

1.6.2rc1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by nqzhang** [comment]
mark
