### ISSUE TITLE
[BUG] Stuck on Connecting to wallet

### ISSUE THREAD

**Issue by RandmTask** [Chia-Network/chia-blockchain#1416]
**Describe the bug**
On Chia 1.0.0 on macOS High Sierra, when installing and running Chia for the first time (no previous installations) it gets stuck on Connecting to wallet

**To Reproduce**
Try to open Chia.app

**Expected behavior**
For it to get past the connecting to wallet stage

**Screenshots**
![image](https://user-images.githubusercontent.com/7912017/111915008-bebcd400-8a8d-11eb-8b73-29f2cda62763.png)

**Desktop (please complete the following information):**

- OS: MacOS High Sierra 10.13.6
- CPU: Mac Mini 2011, 2.3 GHz Intel Core i5, 16gb RAM

**Additional context**
Have already tried force quitting and then restarting the computer. Works fine on my MacBook Air

**Comment by hoffmang9** [comment]
Mojave is the oldest MacOS we support.
