### ISSUE TITLE
[Bug] Move multiple nfts to did at once, only the first move will be successful

### ISSUE THREAD

**Issue by nqzhang** [Chia-Network/chia-blockchain#14183]
### What happened?

When moving multiple nfts to did at once, only the first move will be successful, and the other moves will be stuck in "moving confirmation"
Can only move nft one by one after the previous nft moves successfully

### Version

1.6.2-rc1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
This is expected behavior for the time being. Looking towards future enhancements to change this.
