### ISSUE TITLE
how to miner with harvester and use proxy

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-blockchain#1418]
thanks for your magical code 
i have a question about how to miner with harvester 
due to the compacity of HD we need to miner with harvester. 
we have already saw your wiki.，and we check in the log via sed the warnging with info.  we have sure that all machine is  really work. but the main node machine only show the plot within itself，and the chia farm summary does. do you have any idea to see the whole plot in the main node?

we found that your code use aiphttp and asyncio, and we saw in the log file the ip address is mainly the 68* 80*, so we want to use proxy to accelerate the connecting speed,  currently we use ubuntu 20.04LTS.
by simplely export the env file, we run pass the farmer. 
but we don't know whether the aio and asyncio works?
```
export http_proxy=http://127.0.0.1:8118
export https_proxy=http://127.0.0.1:8118
```
[aio_link](https://buildmedia.readthedocs.org/media/pdf/aiohttp/latest/aiohttp.pdf) 

```
async with aiohttp.ClientSession() as session:
async with session.get("http://python.org",
proxy="http://proxy.com") as resp:
print(resp.status)

```
we saw in the above link that the proxy can be set by add this line , can you tell me , which file i should change ?

```
async with aiohttp.ClientSession(trust_env=True) as session:
```
i saw in document that if pass the trust_env with true the aiohttp will use the environment?
@richardkiss @jespino

**Comment by mariano54** [comment]
It's not currently possible to see all plots within chia farm summary.

You can use a proxy, but I'm not sure how that would help. You don't need to have a super fast internet connection to farm chia.
