### ISSUE TITLE
Full Node subscription data optimization?

### ISSUE THREAD

**Issue by joshpainter** [Chia-Network/chia-blockchain#14192]
Currently, the Wallet must register a subscription with the Full Node for each puzzlehash and CAT combo, which results in (DerivationIndex * CATs * 2) (see https://github.com/Chia-Network/chia-blockchain/issues/14002#issuecomment-1344654073) subscriptions that Full Node must maintain for each connected wallet.

Instead, we could subscribe to a puzzlehash and a "TAIL filter" which would be a bitwise AND of all the TAILs in which we are interested. Now when Full Node finds a new CAT coin with our puzzlehash, it will bitwise OR it with the TAIL filter to determine if it should be forwarded to the wallet.

I'm not advanced enough to be able to prove it mathematically, but I *think* this would result in huge savings around subscription records for the most common wallet use-case: XCH plus a handful of CATs.

See also #14142

**Comment by MumfMeisterT** [comment]
We are working to fix this issue. Duplicate issue.
