### ISSUE TITLE
[BUG] Loose plots when adding external hard drives

### ISSUE THREAD

**Issue by berlef80** [Chia-Network/chia-blockchain#1423]
**Describe the bug**
I have three external hard drives with plots on them - 109, 107 and 6 respectively.  When I just add one of the external drives in the plot directory, the exact number of plots shows up.  But when I add a second plot directory, it looses one from that directory. and the same happens to the third plot directory.  So when start with 109 plots, they all show up.  When I add 107, I loose one for a total of 215 and when I add the third one of 6 I have a total of 220.  It doesn't matter which directory I start with, the first always has the total and the subsequent ones have one missing.  Note; there are no invalid plots mentioned in the plot section of the GUI

**To Reproduce**
Start GUI farming and add external hard drives. with plots.

**Expected behavior**
Would expect all the plots to show up and farm

**Desktop (please complete the following information):**
Windows 10 - Chia 1.0.0 GUI

**Additional context**
This was also a problem in the previous version GUI

**Comment by mariano54** [comment]
Maybe you have a duplicate plot in all 3 dirs? Can you check this?

**Comment by berlef80** [comment]
That was it - thank you!  I should have thought of that, but thought it would show an invalid plot rather than just ignore it.
Thanks as always for your help.
