### ISSUE TITLE
[Bug] Sometime cannot cancel offers 

### ISSUE THREAD

**Issue by blupino** [Chia-Network/chia-blockchain#14232]
### What happened?

Intermitent incident of no response when offers being cancelled from GUI.. But ok when cancelled from 1.6.1

This is the log

![image](https://user-images.githubusercontent.com/93529296/209454023-5b718b81-a08f-439b-b2f9-4cb36888de99.png)

![image](https://user-images.githubusercontent.com/93529296/209454033-059264bf-e2aa-4a81-89db-e4eab11e2af7.png)

### Version

1.6.2rc1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Did you happen to add a fee to cancel attempt?

**Comment by blupino** [comment]
No, for this issue I never add fee

**Comment by blupino** [comment]
someone also have same issue

https://github.com/Chia-Network/chia-blockchain/discussions/14275
