### ISSUE TITLE
[Bug] wallet rpc "get_spendable_coins" - http 404 not found error

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#14243]
### What happened?

I am trying to access the wallet api with an http request according to the rpc documentation https://docs.chia.net/wallet-rpc#get_spendable_coins

I am requesting the following data:
```
{
  Method: POST, 
  RequestUri: 'https://192.168.1.132:9256/get_spendable_coins',
  Version: 1.1,
  Content: {"wallet_id":1},
  Headers:
  {
    Content-Type: application/json
  }
}
```

note that half of the chia api wrapper is already working and implemented in https://github.com/KryptomineCH/Chia-Client-API
I suspect that likely something with the uri and specifically `get_spendable_coins` is incorrect due to the 404 not found issue.

### Version

1.6.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
This RPC `get_spendable_coins` was introduced in 1.6.2 - please confirm you have tried this version. It is not available in 1.6.1
