### ISSUE TITLE
transferencia no recibo

### ISSUE THREAD

**Issue by AlexRuso23** [Chia-Network/chia-blockchain#14250]
### What happened?

transferi de huobi 2.23352300 xch a mi cuenta; xch1m7ag0j26j685dgzu2sfyw927v6prztsfjrm9e4hseg2nwrkkjq4s3ch3kf    y no aparece en wallet   TXID    d0580fea6547349aad5061eab02f8f41401052911ee7091853ba1fc9038234a8

### Version

CHIASETUP-1.6.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
TdID d0580fea6547349aad5061eab02f8f41401052911ee7091853ba1fc9038234a8
```

**Comment by shaneo257** [comment]
per https://www.spacescan.io/address/xch1m7ag0j26j685dgzu2sfyw927v6prztsfjrm9e4hseg2nwrkkjq4s3ch3kf it shows 2.233523000100XCH in the wallet
is the wallet in sync?

**Comment by emlowe** [comment]
Closing issue due to lack of response

**Comment by AlexRuso23** [comment]
thank you for your reply! yes, there is a small problem with the wallet not
syncing itself, you have to do everything manually. thank you for your
support

ср, 11 янв. 2023 г., 21:12 Earle Lowe ***@***.***>:
