### ISSUE TITLE
K-32, 101.4GiB still plotting for nearly 24+ hours. How far along am I?

### ISSUE THREAD

**Issue by nickster64** [Chia-Network/chia-blockchain#1425]
I wasn't expecting adding a Plot would take this long and I'm just curious how far along my Plots are.

**At the start of the Plot log I see:**
Starting phase 1/4: Forward Propagation into tmp files... 
Computing table 1

**The most recent printed lines:**
Compressing tables 6 and 7
...
...
First computation pass time: 4466.910 seconds. CPU (27.360%)
...
... 
Bucket 30 uniform sort. Ram: 4.440Gib, u_sort min: 3.000GiB, qs min: 1.003GiB.

No errors in the log though, so that's good.

**Comment by wrosko** [comment]
Be patient! You said it shows `First computation pass time: 4466.910 seconds`, for reference one of my k32 runs going in parallel had its first computation pass time as `782 seconds`. My final time for that plot was `32096.984  seconds` or 8.9 hours (my best has been ~5.5 hours). So you will probably be plotting for a good while still.

**Comment by wjblanke** [comment]
You may be swapping memory to disk. How much RAM do you have? You may need to select less RAM in plot advanced options.

**Comment by nickster64** [comment]
> You may be swapping memory to disk. How much RAM do you have? You may need to select less RAM in plot advanced options.

The plot finally finished and is farming now. I like that the Plot automatically starts farming once complete. Would reducing the RAM allocation in advanced settings have sped things up? My system has 8 GB RAM but in the advanced options I left the default value of ~4 GB.

![Screen Shot 2021-03-22 at 1 48 29 PM](https://user-images.githubusercontent.com/35485639/112043037-1c115d80-8b40-11eb-9f5d-95aa691644b8.png)

My Expected Time to Win is 10 months with a 500 GB disk. If I stop farming and expand the disk to 1 TB or greater would I have to restart the plotting process?

![Screen Shot 2021-03-22 at 1 48 36 PM](https://user-images.githubusercontent.com/35485639/112043228-5975eb00-8b40-11eb-9b8a-e3115ca97d44.png)

**Comment by wrosko** [comment]
Your expected time to win is 10 months for one plot, not for your 500gb disk. Did you read the [Wiki](https://github.com/Chia-Network/chia-blockchain/wiki)? Also consider joining the Keybase.

Each plot takes up ~101GiB of space, you should fill up a disk's unused space with plots. The more unused space you have the more room you have for chia plots. You need to plot in order to create a plot, one plot doesn't magically take up your whole disk's space, nor will duplicating the plot work. You must create new plots.
