### ISSUE TITLE
[Bug] Cannot decrease derivation index in GUI

### ISSUE THREAD

**Issue by heget** [Chia-Network/chia-blockchain#14296]
### What happened?

Cannot decrease derivation index in GUI
This issue was also in 1.6.1. and continue to 1.6.2.
Only increase can be accepted.

### Version

1.6.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by heget** [comment]
![image](https://user-images.githubusercontent.com/14862691/210973799-b6ed4e01-b671-4f69-ae4a-ba916b60d2f5.png)

**Comment by blupino** [comment]
if you decrease, isn't that risk of some coin no longer accounted?
