### ISSUE TITLE
[Bug] Timelord issue when installing on CentOS 9 - Error in install-timelord.sh script

### ISSUE THREAD

**Issue by gibblinhimer** [Chia-Network/chia-blockchain#14307]
### What happened?

when configuring a timelord on CentOS 9 there is an error when running the "intall-timelord.sh" script.

From what I can tell - CentOS names its python3 development package differently. For CentOS its "python3-devel" vs others its libpython3-dev

If I choose the "-n" option to skip the python dev install, it looks like having the extra space in the yum command throws an error. Then the script exits with errors. 

Seems like a simple fix would be change the order of the yum install commands at line 104 and 105 of the install-timelord.sh like this:

from this:
echo "yum install gcc gcc-c++ gmp-devel $PYTHON_DEV_DEPENDENCY libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 cmake -y"
sudo yum install gcc gcc-c++ gmp-devel $PYTHON_DEV_DEPENDENCY libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 cmake -y

to this:
echo "yum install $PYTHON_DEV_DEPENDENCY gcc gcc-c++ gmp-devel libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 cmake -y"
sudo yum install $PYTHON_DEV_DEPENDENCY gcc gcc-c++ gmp-devel libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 cmake -y

of course the above change would fix the issue with the -n option but not fix the package name issues to actually install it if needed.

so a better solution would be to accommodate the dependency package name difference on CentOS.. of course that can be done quite a few ways. Maybe adding another at line 41 like this and matching the YUM command accordingly later in the script.

if [ "$INSTALL_PYTHON_DEV" ]; then
  PYTHON_DEV_DEPENDENCY=lib"$PYTHON_VERSION"-dev
  PYTHON_DEV_DEPENDENCY_RHEL="$PYTHON_VERSION"-devel
else
  PYTHON_DEV_DEPENDENCY=
fi

thanks

### Version

6.0.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) [root@TimeLord1-1 chia-blockchain]# sh install-timelord.sh
Timelord requires CMake 3.14+ to compile vdf_client.
Python version: python3.9
install-timelord.sh: line 75: type: apt-get: not found
dnf is /usr/bin/dnf
Found RedHat.
Installing chiavdf dependencies on RedHat/CentOS/Fedora
yum install gcc gcc-c++ gmp-devel libpython3.9-dev libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 cmake -y
Last metadata expiration check: 1:18:53 ago on Sat 07 Jan 2023 05:11:16 PM EST.
Package gcc-11.3.1-4.3.el9.x86_64 is already installed.
Package gcc-c++-11.3.1-4.3.el9.x86_64 is already installed.
Package gmp-devel-1:6.2.0-10.el9.x86_64 is already installed.
No match for argument: libpython3.9-dev
Package libtool-2.4.6-45.el9.x86_64 is already installed.
Package make-1:4.3-7.el9.x86_64 is already installed.
Package autoconf-2.69-38.el9.noarch is already installed.
Package automake-1.16.2-6.el9.noarch is already installed.
Package openssl-devel-1:3.0.7-2.el9.x86_64 is already installed.
Package libevent-devel-2.1.12-6.el9.x86_64 is already installed.
Package boost-devel-1.75.0-8.el9.x86_64 is already installed.
Package python3-3.9.16-1.el9.x86_64 is already installed.
Package cmake-3.20.2-7.el9.x86_64 is already installed.
Error: Unable to find a match: libpython3.9-dev
(venv) [root@TimeLord1-1 chia-blockchain]#

Or if I choose the -n option.

(venv) [root@TimeLord1-1 chia-blockchain]# sh install-timelord.sh -n
Timelord requires CMake 3.14+ to compile vdf_client.
Python version: python3.9
install-timelord.sh: line 75: type: apt-get: not found
dnf is /usr/bin/dnf
Found RedHat.
Installing chiavdf dependencies on RedHat/CentOS/Fedora
yum install gcc gcc-c++ gmp-devel  libtool make autoconf automake openssl-devel libevent-devel boost-devel python3 cmake -y
Last metadata expiration check: 1:21:08 ago on Sat 07 Jan 2023 05:11:16 PM EST.
Package gcc-11.3.1-4.3.el9.x86_64 is already installed.
Package gcc-c++-11.3.1-4.3.el9.x86_64 is already installed.
Package gmp-devel-1:6.2.0-10.el9.x86_64 is already installed.
No match for argument: 
Package libtool-2.4.6-45.el9.x86_64 is already installed.
Package make-1:4.3-7.el9.x86_64 is already installed.
Package autoconf-2.69-38.el9.noarch is already installed.
Package automake-1.16.2-6.el9.noarch is already installed.
Package openssl-devel-1:3.0.7-2.el9.x86_64 is already installed.
Package libevent-devel-2.1.12-6.el9.x86_64 is already installed.
Package boost-devel-1.75.0-8.el9.x86_64 is already installed.
Package python3-3.9.16-1.el9.x86_64 is already installed.
Package cmake-3.20.2-7.el9.x86_64 is already installed.
Error: Unable to find a match
```

**Comment by MumfMeisterT** [comment]
Please submit a PR for this and we will consider your enhancement. Thank you.

**Comment by gibblinhimer** [comment]
What is a PR? And how would that be submitted?


Thank You,
Leroy Ladyzhensky

440-937-7680

**Comment by johnathon-b** [comment]
[Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
