### ISSUE TITLE
[Bug] RPC Endpoint /nft_set_did_bulk in 1.6.2 is returning Error even though DID is set

### ISSUE THREAD

**Issue by steppsr** [Chia-Network/chia-blockchain#14308]
### What happened?

The release notes for 1.6.2 mention the wallet RPC endpoint /nft_set_did_bulk being added. I tried it out and it returns an error. However, after checking it did actually set the DID on the NFTs.

Note:  I am using _NFT_ID_ instead of _COIN_ID_. The comments in the code seem to indicate the RPC should work for either value.

Error is:   500, message='Internal Server Error', url=URL('https://localhost:9256/nft_set_did_bulk')

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) steve@jabba:~$ chia rpc wallet /nft_set_did_bulk '{"nft_coin_list":[{"nft_coin_id":"nft13069xkqp6f0l96awy5pdqncrtvw75w5dnx7q5exfdw3f6z43a24s2mjmsw","wallet_id":3},{"nft_coin_id":"nft1h3dep24mhmhjerfe624zv025sj6j0fegwqevqgqqn29h35d6hzys29lsg6","wallet_id":3}],"did_id":"did:chia:1lwf5wtluvc5flp2ht46xprwvadyykjsctjcgyl3ffktzmd3d4r9slupmsq","fee":0.00000000001}'
500, message='Internal Server Error', url=URL('https://localhost:9256/nft_set_did_bulk')
```

**Comment by Ganbin** [comment]
Same on my side:
`500, message='Internal Server Error', url=URL('https://localhost:9256/nft_set_did_bulk')`
However the DID was correctly assigned to the NFTs.

**Comment by MumfMeisterT** [comment]
Could you set logging to DEBUG and provide us with the log files after running the command.

**Comment by steppsr** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/10406176/debug.log)
Here is mine. I ran the command a few minutes before grabbed the debug file. Here is my profile on Mintgarden.io, and the 3 Chia CHEF nfts are the ones that I moved to the profile/did. https://mintgarden.io/profile/fb93472ffc66289f85575d74608dcceb484b4a185cb0827e294d962db62da8cb

**Comment by MumfMeisterT** [comment]
The issue looks to be your json file, so you can try running it through a validator, but off the bat, the fee is in mojos, so it would need to 1 instead of 0.000....

**Comment by emlowe** [comment]
Numerous DID fixes have been implemented since this was initially reported. Closing issue - Can be reopened if issues persist
