### ISSUE TITLE
[Bug] 'chia rpc wallet did_find_lost_did' fails 

### ISSUE THREAD

**Issue by DrakoPensulo** [Chia-Network/chia-blockchain#14312]
### What happened?

I have tried to recover my DID using 'chia rpc wallet did_find_lost_did' command. Unfortunately, it failed with the following output:

Request failed: {'error': 'This DID 2ae4957c0044215d7d55c2711a160515090cccee791b8720dcf055fb6c61f52a is not belong to the connected wallet', 'success': False}

Spacescan.io correctly directs 2ae4957c0044215d7d55c2711a160515090cccee791b8720dcf055fb6c61f52a to my profile.

At some point I updated the DID metadata for the namesdao service. However, I do not know whether I lost access to my DID due to that. I have never tried to transfer my DID anywhere. 

This bug is related to the bug   [#14081](https://github.com/Chia-Network/chia-blockchain/issues/14081)

The problem is not in the GUI. GUI shows NFTs minted with this DID correctly. Also, the DID is shown in 'Settings->Profiles'.  The problem is that I cannot mint with my DID or move new NFTs to that DID. See [#14081](https://github.com/Chia-Network/chia-blockchain/issues/14081) for some more details. 

### Version

1.6.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
No relevant log output on the INFO level.
```

**Comment by ytx1991** [comment]
You need to connect to the wallet that owns the DID when you call did_find_lost_did. Otherwise, it will return the error This DID XXX is not belong to the connected wallet.

**Comment by DrakoPensulo** [comment]
> You need to connect to the wallet that owns the DID when you call did_find_lost_did. Otherwise, it will return the error This DID XXX is not belong to the connected wallet.

I am connected to the wallet which owns the DID. I have always minted from that wallet. I did not transfer the DID anywhere, yet I cannot mint using that DID. 
Is there a way to trace the DID coin(s) somehow? Whether it/they was spent and if so, when?

'chia wallet show' gives

```
DID did:chia:19tjf2lqqgss46l24cfc359s9z5ysen8w0ydcwgxu7p2lkmrp754qexeh6l:
   -Total Balance:         0.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DECENTRALIZED_ID
   -DID ID:                did:chia:19tjf2lqqgss46l24cfc359s9z5ysen8w0ydcwgxu7p2lkmrp754qexeh6l
   -Wallet ID:             2
```

**Comment by ytx1991** [comment]
You can use 
chia rpc wallet did_get_info '{"coin_id": "5aee8639fb4fb08904bd5d4c3395d879d1a874f61fe44b7e1022cbec90dfb9b6"}' to see the details.
Your DID is owned by the xch14fll9fkwzcdahjk8q9x9ufhc2nl7rndwm46lhdj7l37dqckm6ccqwa5j3u. Can you verify if this address is belong to you?

**Comment by DrakoPensulo** [comment]
How do I verify whether I own that address? I do not recognize it. Isn't there a chia CLI command to search for addresses (starting from v1.7.0?)  ?

**Comment by DrakoPensulo** [comment]
> You can use chia rpc wallet did_get_info '{"coin_id": "5aee8639fb4fb08904bd5d4c3395d879d1a874f61fe44b7e1022cbec90dfb9b6"}' to see the details. Your DID is owned by the xch14fll9fkwzcdahjk8q9x9ufhc2nl7rndwm46lhdj7l37dqckm6ccqwa5j3u. Can you verify if this address is belong to you?

How do I verify whether I own that address? I do not recognize it. Isn't there a chia CLI command to search for addresses (starting from v1.7.0?) ?

**Comment by ytx1991** [comment]
You can run this:
 chia rpc wallet sign_message_by_address '{"address":"xch14fll9fkwzcdahjk8q9x9ufhc2nl7rndwm46lhdj7l37dqckm6ccqwa5j3u", "message":"test"}'
If it can sign the message successfully then you own the address.

**Comment by DrakoPensulo** [comment]
It did signed correctly:
```
chia rpc wallet sign_message_by_address "{\"address\":\"xch14fll9fkwzcdahjk8q9x9ufhc2nl7rndwm46lhdj7l37dqckm6ccqwa5j3u\", \"message\":\"test\"}"
{
    "pubkey": "PUBKEY",
    "signature": "84cb461ace096dc67593aff4b54cd26ae839275ee82167d250881e051b37d8df1ea372412d7c2b9ae580578c6ab476070a5d8bbaa8e1fed45cab5590e2f7d0bf36adaf674cf6c6a8bcc8eef0d28d29a606ffb7a3691408c118ed951c58f02cc5",
    "success": true
}
```
That is a relief. However, it does not solve the problem.

**Comment by ytx1991** [comment]
Can you check if you can sign with this address? 
xch1r3j0mctp64tlxxh9j28g0swkjja3tql8cvl8ekmgamqtxarvz29q6ar4kg

**Comment by DrakoPensulo** [comment]
No, that one does not sign.

```
chia rpc wallet sign_message_by_address "{\"address\":\"xch1r3j0mctp64tlxxh9j28g0swkjja3tql8cvl8ekmgamqtxarvz29q6ar4kg\", \"message\":\"test\"}"
Request failed: {'error': 'No key for this puzzlehash 1c64fde161d557f31ae5928e87c1d694bb1583e7c33e7cdb68eec0b3746c128a)', 'success': False}
```

**Comment by ytx1991** [comment]
Ok, it may be because your derivation puzzle is not in the database. You can try to increase the Derivation Index.

**Comment by DrakoPensulo** [comment]
I have increased it to 3276 and still nothing. Windows GUI shows 828 transactions on this wallet (that seems to be accurate). There are no more than 500 NFTs.

**Comment by codephunk** [comment]
Possibly the same issue: https://github.com/Chia-Network/chia-blockchain/issues/13691

**Comment by ytx1991** [comment]
Can you check out the did_find branch and then install it from the source code? Then try the chia rpc wallet did_find_lost_did command again.

**Comment by DrakoPensulo** [comment]
I tried that on did_branch (1.7.0b7.dev20) and it did not work
```
chia rpc wallet did_find_lost_did '{"coin_id":"did:chia:19tjf2lqqgss46l24cfc359s9z5ysen8w0ydcwgxu7p2lkmrp754qexeh6l"}'
Request failed: {'error': 'This DID 2ae4957c0044215d7d55c2711a160515090cccee791b8720dcf055fb6c61f52a is not belong to the connected wallet', 'success': False}
```
Similarly as above. The first address signed the test message the second did not.

**Comment by codephunk** [comment]
Same result for me on `did_find`.
`Request failed: {'error': 'This DID 567d6ee0f9520613a96a0fb54229dc07c40a3e925e3a9db5b2d00d180553a85e is not belong to the connected wallet', 'success': False}`

**Comment by codephunk** [comment]
I'm getting a new error now after fetching the latest did_find update.
`Request failed: {'error': 'Cannot recover DID 567d6ee0f9520613a96a0fb54229dc07c40a3e925e3a9db5b2d00d180553a85e because the last spend is metadata update.', 'success': False}`

**Comment by ytx1991** [comment]
> I'm getting a new error now after fetching the latest did_find update. `Request failed: {'error': 'Cannot recover DID 567d6ee0f9520613a96a0fb54229dc07c40a3e925e3a9db5b2d00d180553a85e because the last spend is metadata update.', 'success': False}`

Do you remember what the last operation you did for this DID was? Is it a metadata update?

**Comment by codephunk** [comment]
> Do you remember what the last operation you did for this DID was? Is it a metadata update?

No, I used it to mint my ScrawlGuys NFT collection using my on-demand mint script: https://github.com/codephunk/minft1

Never used it for anything else. After 189 successful mints it stopped and since then it's in the current state.

**Comment by DrakoPensulo** [comment]
I also get this (fresh install of find_did branch, resynced wallet)

```
chia rpc wallet did_find_lost_did '{"coin_id":"did:chia:19tjf2lqqgss46l24cfc359s9z5ysen8w0ydcwgxu7p2lkmrp754qexeh6l"}'
Request failed: {'error': 'Cannot recover DID 2ae4957c0044215d7d55c2711a160515090cccee791b8720dcf055fb6c61f52a because the last spend is metadata update.', 'success': False}
```

I am quite sure that after I updated the metadata I minted some NFTs.

**Comment by DrakoPensulo** [comment]
I ran your command with "num_verification" from 0 to 10 and it did not work. I got 
`Request failed: {'error': 'Cannot recover DID 2ae4957c0044215d7d55c2711a160515090cccee791b8720dcf055fb6c61f52a because the last spend is metadata update.', 'success': False}
`
What is the meaning of "num_verification", "metadata", "recovery_list_hash". You say they are carried parameters. I did not to try to change them intentionally. In particular, I did not try to add anything  to the recovery list (I know that something along these lines is possible, I do not know the details). 
What I did with my DID is the following. 
1) I ran the command 
`chia rpc wallet did_update_metadata '{"wallet_id": 2, "metadata": .... "fee" :5}'`
5 times with different values of the parameter 'metadata' (firs 4 were not working as expected so I had to update). BTW I have a copy of full output after each of these was run (the long json with spend_bundles. Should that be helpful?
2) Transfer some NFTs to my DID (I think 7 of them)

I have also to mention that about 3 XCH disappeared from that wallet around the same time. My suspicion is that there is a bug when you make an offer file with some fee attached and then cancel the offer (after resyncing the wallet db from 0) by sending coins to yourself or spending the coins assigned as fees otherwise (you can find more on that on my Discord in channel 'technical-logs')

**Comment by ytx1991** [comment]
Sorry, I pushed the change to the wrong branch. Can you do git pull and try it again?

**Comment by codephunk** [comment]
> Sorry, I pushed the change to the wrong branch. Can you do git pull and try it again?

Should I try that as well? And what is `num_verification`?

**Comment by DrakoPensulo** [comment]
This time I got
`Request failed: {'error': 'Cannot recover DID 2ae4957c0044215d7d55c2711a160515090cccee791b8720dcf055fb6c61f52a because the last spend updated recovery_list_hash/num_verification/metadata.', 'success': False}
`
I tried num_verification from 0 to 9.

**Comment by ytx1991** [comment]
num_verification: The number of DID you need to rekey the DID
recovery_list_hash: Hash of all DID IDs which can rekey the current DID
metadata: Data you saved in the DID
For your case, it may be the metadata changed. If you haven't deleted the wallet db since the DID coin missing, you can use did_get_metadata to see what is the latest metadata. The point is, previously the latest metadata is saved locally. So there isn't another way to get it unless you recall it.

**Comment by ytx1991** [comment]
If you check your DID on explorer, the puzzle hash keeps changing. If you are only using the DID for set NFT DID, it will not change. 
@DrakoPensulo https://chia.tt/tracker/0x093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da
@codephunk  https://chia.tt/tracker/0x275d0e2ccccbd793834ff84885eae6d8197ddcf5e50e8a7f8c7f6bc30a55a15c
To recover your DID, the first step is figuring out why the puzzle hash changed. Any idea you can provide?

**Comment by DrakoPensulo** [comment]
This is what I get: on a new db as well as on an old db (this old one is from time before I set up metadata)
```
chia rpc wallet did_get_metadata "{\"wallet_id\": 2}"
{
    "metadata": {},
    "success": true,
    "wallet_id": 2
}
```
As I mentioned above, I have a copy of all complete 5 commends I executed (most likely on 12/7/2022) 
`chia rpc wallet did_update_metadata ...`
containing the metadata I was setting up. I hope that may be helpful. 
Also, the link to chia.tt you provided above shows 3 coins. How should I interpret that? Does it mean that the metadata was updated twice? 3 times? or something else?

**Comment by ytx1991** [comment]
According to the explorer, the last several spends of your DID are updating metadata or something else. There is no set NFT DID spend. You can try:
`chia rpc wallet did_find_lost_did '{"coin_id":"093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da", "metadata":{YOUR_LAST_UPDATED_METADATA}}'`

YOUR_LAST_UPDATED_METADATA is the metadata you input for the last did_update_metadata. For example,
`chia rpc wallet did_find_lost_did '{"coin_id":"093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da", "metadata":{"namesdao": "{\"DrakoPensulo.xch\":{\"dns\":{\"default\":[{\"type\":\"CNAME\",\"host\":\"@\",\"value\":\"drakopensulo.github.io/MainWebPage\",\"ttl\":3600,\"priority\":1}]}},\"_DrakoPensulo.xch\":{\"dns\":{\"default\":[{\"type\":\"CNAME\",\"host\":\"@\",\"value\":\"174.80.23.33:8575\",\"ttl\":3600,\"priority\":1}]}}}"}}'`

**Comment by DrakoPensulo** [comment]
The command you provided does not recover my DID. However, I am sure that the metadata in the command is exactly the last one I set up. 

How do I check my last several DID spends on the explorer?  Is there an easy way?

**Comment by ytx1991** [comment]
The example command I provided will not work because the metadata I get from the chain is not the latest one. You need to modify the metadata to the actual latest one. Is it possible that you ran did_update_metadata unintentionally?

The link I sent is the last 3 spends of your DID. https://chia.tt/tracker/0x093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da
As you can see, the address changed after each spending. It means metadata or other curried data is updated after each spending. You can copy the coin ID and use `chia rpc wallet did_get_info '{"coin_id": "567d6ee0f9520613a96a0fb54229dc07c40a3e925e3a9db5b2d00d180553a85e"}'` to see more details, like metadata. It may help you recall something.

**Comment by DrakoPensulo** [comment]
I am sure I did not update metadata unintentionally, and the one which is on-chain the the one set up. 

When I look at the last coin spent from the link you posted, on spacescan under "Transactions", it says that the type of this transaction is NAN
https://www.spacescan.io/address/xch1rex57w30a30v9flwpq3raswwjqwgkdwnc2vqjj7f0mwynyhscrxsyp09jk

Do you know what is that?

**Comment by ytx1991** [comment]
I don't know what that means on Spacescan. You may need to check with them. Since your current metadata is empty, can you try `chia rpc wallet did_find_lost_did '{"coin_id":"093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da", "metadata":{}}'`?

**Comment by DrakoPensulo** [comment]
Unfortunately, the one with empty metadata did not work either.
I mentioned spacescan above because it is interesting to me that it recognizes other DID transactions as DID while it marks the last one as NAN. I reached spacescan once on "NAN" but did not get any information except that it means "not a number".

**Comment by codephunk** [comment]
@ytx1991 I used the DID to mint NFTs via the `mint_nft` function of `WalletRpcClient` in Python. This is the only point in my script where I even use that DID.

```
        await self.wallet_client.mint_nft(
            wallet_id=cfg.wallet.nft_wallet_id,
            royalty_address=cfg.wallet.royalties_address,
            target_address=to_address,
            hash=sha,
            uris=[image_url],
            fee=cfg.wallet.minting_fees,
            meta_hash=metadata_sha,
            meta_uris=[metadata_url],
            license_hash=cfg.collection.license_hash,
            license_uris=[cfg.collection.license_url],
            royalty_percentage=cfg.wallet.royalties_percent,
            did_id=cfg.wallet.did
        )
```

So I have no idea why the metadata or anything else related to the DID could have changed at all. Is a new mint that uses a DID changing the DID metadata or any other parameter of it?

**Comment by codephunk** [comment]
Might the original wallet database help to find out what happened to the DID?

**Comment by blupino** [comment]
I think my issue #14347 is because of the .xch.limo website linking, during the registration it required to rpc call `did_update_metadata`

this is the .xch.limo instruction url.. which I did

https://www.namesdao.org/dnslimo.html

**Comment by ytx1991** [comment]
The issue is because the puzzle hash of the DID changed. This is usually because the metadata changed. Minting with DID or changing NFT's DID will not cause the puzzle hash change.

In order to recover your DID, the program will analyze the last spend of DID and GUESS what are your current curried parameters (e.g metadata). The current parameters are only saved in your local wallet database. If you delete the database it will be very hard to recover your DID, unless you can recall your current parameters.

If you have a backup of the database, you can restore it and read the DID info then override them.

**Comment by codephunk** [comment]
> If you have a backup of the database, you can restore it and read the DID info then override them.

Where in the db do I find these DID infos?

**Comment by ytx1991** [comment]
I updated did_find branch, you can try it again. It will check your old wallet to see if it match the puzzle hash.

**Comment by codephunk** [comment]
I have added the following backup databases to my wallet db folder: 
```
blockchain_wallet_v1_mainnet_518133150.sqlite_new
blockchain_wallet_v1_mainnet_518133150.sqlite_new-shm
blockchain_wallet_v1_mainnet_518133150.sqlite_new-wal
blockchain_wallet_v2_mainnet_518133150.sqlite
```

Then I fetched the `did_find`, installed and ran `chia rpc wallet did_find_lost_did '{"coin_id":"did:chia:12e7kac8e2grp82t2p765y2wuqlzq505jtcafmddj6qx3sp2n4p0qx449ze"}'` again.

Same result as before:
`Request failed: {'error': 'Cannot recover DID 567d6ee0f9520613a96a0fb54229dc07c40a3e925e3a9db5b2d00d180553a85e because the last spend updated recovery_list_hash/num_verification/metadata.', 'success': False}`

**Comment by DrakoPensulo** [comment]
Below, I attach that spacescan.io reports on my last DID spends. The last transaction on my DID is not recognized as DID1 type but as NAN. All the previous transactions are recognized as DID1. It means that there was something essentially different about the last DID transaction than all the previous DID transactions (the formatting below is not the best but readable).


Address xch1rex57w30a30v9flwpq3raswwjqwgkdwnc2vqjj7f0mwynyhscrxsyp09jk


Transaction:

<html>
<body>


Name | Amount | Date & Time | Type | Status | Coin Name | Sender | Recipient
-- | -- | -- | -- | -- | -- | -- | --
  | 0.000000000001 XCH1 Mojo | 12/12/2022 01:01:47 PM | NAN | Received | 0x93c ..... ebe89 | **xch10 ..... 5gld6** | xch1r ..... p09jk


</body>
</html>
Name	Amount	Date & Time	Type	Status	Coin Name	Sender	Recipient
  	
0.000000000001 XCH
1 Mojo	12/12/2022 01:01:47 PM	NAN	Received	[0x93c ..... ebe89](https://www.spacescan.io/coin/0x93cc4a5667056d65902300168605f16af3ca9eec92837fe0e86181c77d3ebe89)	xch10 ..... 5gld6	[xch1r ..... p09jk](https://www.spacescan.io/coin/0x93cc4a5667056d65902300168605f16af3ca9eec92837fe0e86181c77d3ebe89)

Address **xch10qenwmks8huzu7upkyw4wn260dgjpw6m9dxmxgsuuwvmzlmntflql5gld6**


<html>
<body>


Name | Amount | Date & Time | Type | Status | Coin Name | Sender | Recipient
-- | -- | -- | -- | -- | -- | -- | --
  | 0.000000000001 XCH1 Mojo | 12/12/2022 01:01:47 PM | NAN | Sent | 0x93c ..... ebe89 | xch10 ..... 5gld6 | xch1r ..... p09jk
  | 0.000000000001 XCH1 Mojo | 12/12/2022 12:56:08 AM | DID1 | Received | 0x093 ..... a11da | **xch1f ..... 8vypf** | xch10 ..... 5gld6


</body>
</html>Name	Amount	Date & Time	Type	Status	Coin Name	Sender	Recipient
  	
0.000000000001 XCH
1 Mojo	12/12/2022 01:01:47 PM	NAN	Sent	[0x93c ..... ebe89](https://www.spacescan.io/coin/0x93cc4a5667056d65902300168605f16af3ca9eec92837fe0e86181c77d3ebe89)	xch10 ..... 5gld6	[xch1r ..... p09jk](https://www.spacescan.io/coin/0x93cc4a5667056d65902300168605f16af3ca9eec92837fe0e86181c77d3ebe89)
  	
0.000000000001 XCH
1 Mojo	12/12/2022 12:56:08 AM	DID1	Received	[0x093 ..... a11da](https://www.spacescan.io/coin/0x093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da)	xch1f ..... 8vypf	[xch10 ..... 5gld6](https://www.spacescan.io/coin/0x093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da)

Address **xch1funezejvmpw8mnecmd8h8t3cultvedsz50rw65n77p9dfuvfrdkq28vypf**

<html>
<body>


Name | Amount | Date & Time | Type | Status | Coin Name | Sender | Recipient
-- | -- | -- | -- | -- | -- | -- | --
  | 0.000000000001 XCH1 Mojo | 12/12/2022 12:56:08 AM | DID1 | Sent | 0x093 ..... a11da | xch1f ..... 8vypf | xch10 ..... 5gld6
  | 0.000000000001 XCH1 Mojo | 12/12/2022 12:19:41 AM | DID1 | Received | 0x28b ..... b80fb | xch1h ..... cm2mx | xch1f ..... 8vypf


</body>
</html>Name	Amount	Date & Time	Type	Status	Coin Name	Sender	Recipient
  	
0.000000000001 XCH
1 Mojo	12/12/2022 12:56:08 AM	DID1	Sent	[0x093 ..... a11da](https://www.spacescan.io/coin/0x093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da)	xch1f ..... 8vypf	[xch10 ..... 5gld6](https://www.spacescan.io/coin/0x093f00d662564dfa4847aacc64a535d8b52a6ff0b24f198d4b43364ea88a11da)
  	
0.000000000001 XCH
1 Mojo	12/12/2022 12:19:41 AM	DID1	Received	[0x28b ..... b80fb](https://www.spacescan.io/coin/0x28bab8a6e1196b8c377558408b1ccf848a4e1ab420ba62f4b58b36dad4fb80fb)	xch1h ..... cm2mx	[xch1f ..... 8vypf](https://www.spacescan.io/coin/0x28bab8a6e1196b8c377558408b1ccf848a4e1ab420ba62f4b58b36dad4fb80fb)

**Comment by ytx1991** [comment]
@DrakoPensulo I can see the metadata changed in the last several spend. Considering they are very close, I assume the last spend is also a metadata update spend. If you are sure nothing changed in metadata, you can git pull did_find again and try the did_find_lost_did. Just call it without any override.

I added a brute force for guessing the P2 puzzle hash of the DID. It may take a VERY LONG time, depending on how many addresses are in your wallet DB.

**Comment by DrakoPensulo** [comment]
So, this time I got

```
chia rpc wallet did_find_lost_did '{"coin_id":"did:chia:19tjf2lqqgss46l24cfc359s9z5ysen8w0ydcwgxu7p2lkmrp754qexeh6l"}'
{
    "latest_coin_id": "93cc4a5667056d65902300168605f16af3ca9eec92837fe0e86181c77d3ebe89",
    "success": true
}

```
and

```
DID did:chia:19tjf2lqqgss46l24cfc359s9z5ysen8w0ydcwgxu7p2lkmrp754qexeh6l:
   -Total Balance:         1.0  
   -Pending Total Balance: 1.0  
   -Spendable:             1.0  
   -Type:                  DECENTRALIZED_ID
   -DID ID:                did:chia:19tjf2lqqgss46l24cfc359s9z5ysen8w0ydcwgxu7p2lkmrp754qexeh6l
   -Wallet ID:             2

```

So, I guess the problem is solved. Thanks.

**Comment by codephunk** [comment]
> I added a brute force for guessing the P2 puzzle hash of the DID. It may take a VERY LONG time, depending on how many addresses are in your wallet DB.

Went trough pretty quick in my case. But with the same result as before.
```
chia rpc wallet did_find_lost_did '{"coin_id":"did:chia:12e7kac8e2grp82t2p765y2wuqlzq505jtcafmddj6qx3sp2n4p0qx449ze"}'
Request failed: {'error': 'Cannot recover DID 567d6ee0f9520613a96a0fb54229dc07c40a3e925e3a9db5b2d00d180553a85e because the last spend updated recovery_list_hash/num_verification/metadata.', 'success': False}
```

**Comment by ytx1991** [comment]
@codephunk For your case, you may change metadata or something else. You need to override them if you can recall what you changed.
Another possible reason is you don't have enough addresses in your wallet db or they are not consecutive. In this case, you may want to increase the derivation index and resync.

**Comment by codephunk** [comment]
> @codephunk For your case, you may change metadata or something else. You need to override them if you can recall what you changed. Another possible reason is you don't have enough addresses in your wallet db or they are not consecutive. In this case, you may want to increase the derivation index and resync.

As stated before, I only used this DID for minting my NFT collection.
How can I resync while keeping the derivation index? It always resets when I delete the wallet db.
