### ISSUE TITLE
[ERROR] When installing on Ubuntu based OS, print error

### ISSUE THREAD

**Issue by ZurMaD** [Chia-Network/chia-blockchain#1431]
**Describe the bug**

Error when installing GUI after a stopped previous installation

**To Reproduce**

Typical installation

```
sudo apt-get update
sudo apt-get upgrade -y

# Checkout the source and install
git clone https://github.com/Chia-Network/chia-blockchain.git
cd chia-blockchain

sh install.sh

. ./activate

sh install-gui.sh # in this point I break with CTRL+C then I retried later without success

cd chia-blockchain-gui
npm run electron &
```

**Screenshots**

![image](https://user-images.githubusercontent.com/28235457/112036306-7abde380-8b0e-11eb-9af9-3554ad3a2654.png)

When running npm
![image](https://user-images.githubusercontent.com/28235457/112036981-3f6fe480-8b0f-11eb-8b19-1feefb996c7c.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- OS Version/Flavor: 20
- CPU: Intel i7-6500U

**Comment by ZurMaD** [comment]
I removed 

```
print(float(process.stdout) < float(20.04))
```

from 

https://github.com/Chia-Network/chia-blockchain/blob/91f038e2193755e2a6ca22e2160e2c8f547c23fe/install-gui.sh#L45

and works. 

Something about printing booleans or floats was the error

**Comment by hoffmang9** [comment]
What does the output of `lsb_release -rs` give you on that machine?

**Comment by ZurMaD** [comment]
Hello, I got this
![image](https://user-images.githubusercontent.com/28235457/112061360-64268500-8b2c-11eb-8809-ea7464532b12.png)

**Comment by hoffmang9** [comment]
and `lsb_release -a` ?

**Comment by ZurMaD** [comment]
![image](https://user-images.githubusercontent.com/28235457/112061958-3988fc00-8b2d-11eb-9f40-534d1af3c90a.png)
I forget to mention that I'm in an modified Ubuntu OS (kernel level)

**Comment by hoffmang9** [comment]
The script has to assume Ubuntu using the Ubuntu versioning. Going to close as won't fix.
