### ISSUE TITLE
MacAir Farmer Crash Multiple Times just running Chia and NOT plotting  [BUG]

### ISSUE THREAD

**Issue by rytoworks** [Chia-Network/chia-blockchain#1432]
**Describe the bug**

"spinlock acquisition timeout" ??

Maybe it's a bad drive since those are the only things spinning? Then why crash the whole computer?

----- I have 2 old MacAirs one with 4GB Ram the other with 8GB Ram.  I have 120TB on 12 HDD externals attached in 2 USB hubs... after plugging them all in and everything working just fine the computer will restart randomly due to running Chia.  The first day it was after 12hrs... Just recently it was within 2.  Each time some plots still show up and some don't.  So I eject the plots and reload them.  But today one MacAir would not sync at all to the network after this, the node tab just kept spinning for over 15mins.  And the other after crashing just 2hrs into running said "database disk image malformed" when I tried going back into the winning wallet. 

No plotting.  These are purely farmers.  

https://pastebin.com/zA8pqTZz

**To Reproduce**

**Expected behavior**

**Screenshots**

https://pastebin.com/zA8pqTZz

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by wjblanke** [comment]
There's nothing the Chia code can do to cause your computer to restart. It sounds like there are some stability issues with the computer. Maybe do some RAM checks? I don't think the drive would cause the spinlock issue. Maybe that issue is cascading into DB corruption though.

**Comment by rytoworks** [comment]
I agree... I think it's the hardware.. Odd that it's both of them.  These macs have always been very stable.  Which is why I chose them after hearing a Pi should do the trick.  I find this whole situation very odd.  

What can lead to DB corruption?  Corrupting the drives with the plots?

**Comment by wjblanke** [comment]
A machine crash could corrupt the DB. Or memory errors.

WRT stability it may be the USB controller and all the added drives? Likely those laptops arent tested by Apple like that. But thats just a guess. You could try running with less drives as a test. Also hopefully those hubs arent drawing much power from the USB port.

**Comment by wjblanke** [comment]
BTW I agree it is odd that it is both of them. Maybe some HW/OS limitation rather than a failure.

**Comment by rytoworks** [comment]
The USB hub has it's own power supply and it's plugged in now.  So that shouldn't be an issue.  This latest crash the hubs were plugged in to separate power.   I am now only running 4 external drives..  Waiting to see if it will crash and if so how long it will take....

**Comment by rytoworks** [comment]
So far so good.... Thanks for the help.  I'll keep an eye on it and try to migrate to a windows desktop. 

When the Mac would restart it was very strange.  Usually there is a log in screen.  With this situation it would restart and log right back into Chia and keep farming.... only many of the plots would be missing.  Unusual erratic behavior to be sure.  That's how it started.  Then it just couldn't sync anymore.  That's when I knew I needed help.
