### ISSUE TITLE
[Bug] Wrong coin balance

### ISSUE THREAD

**Issue by blupino** [Chia-Network/chia-blockchain#14355]
### What happened?

I have been noticing this few times, quite easy to reproduce. In short just do a normal send XCH to another addres, for my case I sent 1.01 XCH twice to different address, and after they settled it will show incorrect balance. The remedy for this issue is I need to restart chia client and after sync completed, it will show correct balance. 

The balance will never get updated if I just wait it out, I need to restart the client

This is the wrong balance, and it also show the 2 transaction I did
![bug-coin](https://user-images.githubusercontent.com/93529296/212920164-3f42bc2f-0964-41a0-9de9-6a09a344e29b.png)

And this is the correct balance after restart
![bug-coin1](https://user-images.githubusercontent.com/93529296/212919979-1573aa1f-0c1d-43b7-af52-28d58b3295ce.png)

### Version

1.7.0b5.dev29

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by blupino** [comment]
Just now I encounter similar issue again but slighly different. This time it involved "Delete Unconfirmed Transaction". Apparently the previous transaction has completed, but the XCH balance somehow didn't get updated and if I "Delete Unconfirmed Transaction", the balance become incorrect.

**Comment by MumfMeisterT** [comment]
What do you mean by restart the client? Also how many CATs do you have? 
Can you check the CLI to see if the CLI matches the GUI balances? -- Run ```chia wallet show``` and see if amount is correct.

**Comment by blupino** [comment]
1. Previously I was using 1.7.0b5.dev29 from git checkout. Now I change it with 1.7.0b5 from beta release. So far I haven't notice the issue again.
 2. I didn't see discrepancy between CLI and GUI at the moment
 3. Restart client means, I close the client and re-open.
 4. 13 CATs

**Comment by blupino** [comment]
I delete my wallet db and start over. So far seems more stable. Previously even cancelling offer can cause missing coin issue

**Comment by MumfMeisterT** [comment]
Did you happen to save a copy of the wallet db, or did you delete completely?

**Comment by blupino** [comment]
I grep-ed on the log folder `grep -i "adding state" -r *`, and doesn't see any hit. I do keep the wallet db though, but I worry it will be privacy issue :)

So far the issue seems resolved. Previously it was slow even transfer coin to varied address in sequence.

**Comment by blupino** [comment]
The issue still exist. On 1.6.2, I did offer of CAT for XCH. When I cancel the offer, the CAT is not added back to balance. Another case when I make an offer of CAT for XCH, and if I purposely accept this offer myself. The balance of CAT become "stuck/never complete".. and when I `delete unconfirmed transaction` the balance become incorrect

**Comment by HVNC1** [comment]
try increasing the derivation index and wait for the changes to apply
![image](https://user-images.githubusercontent.com/95166695/215271432-43e9657c-796e-4d20-aedc-44d08697b6fa.png)
![image](https://user-images.githubusercontent.com/95166695/215271451-0b87a5f8-7c3e-4791-bb44-c245178efcd7.png)

**Comment by trgarrett** [comment]
I've seen a similar issue, up through and including 1.7.0-rc4. 

I have been gradually gathering CAT tokens for the Tai Chia DAO. I am sending them to the same address so I can review my future dividends activity easily on the blockchain explorer (primarily to properly record income). So, my use case is sending a CAT balance from one address to another address that both belong to the same wallet. The transaction showing the debit will be correctly handled, but the corresponding deposit does not get handled. No amount of waiting will bring it in, although a restart of the wallet process triggering a resync from an earlier block position will fix the issue. 

It seems like debits from any of your addresses are correctly processed while reading from the blockchain, but they are not processed on send from the wallet. Presumably when the transaction is confirmed, it is simply moving the recorded transaction from Pending to Confirmed and not creating the offset for the deposit.

**Comment by blupino** [comment]
So far not happen with newly released 1.7.0, :crossed_fingers:

**Comment by blupino** [comment]
No longer see this problem on1.8.0b3, and it seems more responsive to divide big coin into smaller coin now compared with 1.7.0.
