### ISSUE TITLE
[Bug] WalletAPI "get_coin_records_by_names" does not work

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#14352]
### What happened?

I dont know what im doing wrong or what the issues is. `get_coin_records_by_names` of the full node works. however, the same rpc on the wallet node does not return anything.

Whats the issue?

### Version

1.6.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Could you please include the log file for when you do this? The log is probably producing an error relating to this.
