### ISSUE TITLE
Use the GUI with a non-standard database directory

### ISSUE THREAD

**Issue by aicastell** [Chia-Network/chia-blockchain#14354]
### What happened?

I want to run the GUI using a custom (non-standard) directory, I mean /media/disk/.chia/mainnet

First of all, I used CHIA_ROOT variable to store all the chia database in that custom directory, where an external SSD is mounted. Using that environ variable I could synchronize the database in my custom directory (SSD), and imported my wallet using the seed (24 words). I can see my balance fine. 

Now I want to use the GUI with that custom directory. Whenever I start the GUI, the default directory /home/user/.chia is created. I have tried modifiying the start-gui.sh script, adding CHIA_ROOT before running npm, such as this:

echo "### Starting GUI"
export CHIA_ROOT=/media/disk/.chia/mainnet
cd "${SCRIPT_DIR}/chia-blockchain-gui/"
echo "npm run electron"
npm run electron

But this seems not working as expected.  What is the proper way to do that? Thanks in advance!

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
(venv) <user>@<hostname>:~/Documentos/chia-blockchain$ sh start-gui.sh 
### Checking GUI dependencies
Found npm 8.19.3
### Checking GUI build
Found /home/<user>/Documentos/chia-blockchain/chia-blockchain-gui/packages/gui/build/electron/main.js
### Starting GUI
npm run electron

> root@1.6.2 electron
> npm run start:gui


> root@1.6.2 start:gui
> lerna run start --scope @chia-network/gui

lerna notice cli v5.6.2
lerna notice filter including "@chia-network/gui"
lerna info filter [ '@chia-network/gui' ]
lerna info Executing command in 1 package: "npm run start"
lerna info run Ran npm script 'start' in '@chia-network/gui' in 1.4s:

> @chia-network/gui@1.6.2 start
> npm run electron


> @chia-network/gui@1.6.2 electron
> electron .

Checking if userData migration is needed
/home/<user>/.config/Chia Blockchain/Local Storage/leveldb exists: true
/media/disk/.chia/mainnet/gui/Chia Blockchain/Local Storage/leveldb exists: false
/home/<user>/.config/Chia Blockchain/Local Storage/leveldb/migrated exists: true
Migration needed: false
Setting user data directory to /media/disk/.chia/mainnet/gui/Chia Blockchain
lerna success run Ran npm script 'start' in 1 package in 1.4s:
lerna success - @chia-network/gui
(venv) <user>@<hostname>:~/Documentos
```

**Comment by paninaro** [comment]
@aicastell The GUI should be honoring your `CHIA_ROOT` override, but perhaps there's an issue with having the GUI start services without passing the override through.

Can you try starting chia services with your custom CHIA_ROOT before launching the GUI? `chia start farmer` for instance, and then starting the GUI.

**Comment by aicastell** [comment]
At the end I fixed this symlinking all the .chia directories to the external drive, so

/home/user/.chia/mainnet/db → /media/disk/.chia/mainnet/db
/home/user/.chia/mainnet/config → /media/disk/.chia/mainnet/config
/home/user/.chia/mainnet/cache → /media/disk/.chia/mainnet/cache
/home/user/.chia/mainnet/log → /media/disk/.chia/mainnet/log
/home/user/.chia/mainnet/run → /media/disk/.chia/mainnet/run
/home/user/.chia/mainnet/wallet → /media/disk/.chia/mainnet/wallet

In that way, you can run the CLI and the GUI without definit CHIA_ROOT environ variable at all. 

That seems to work fine. Thanks for your support!
