### ISSUE TITLE
[Bug] Chia wallet consumes max memory

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#14364]
### What happened?

chia wallet happily consumes max memory,  (i have seen up to 90gb in use)

-> how to debug? Im not a linux expert..
![image](https://user-images.githubusercontent.com/117320700/213425786-153e651e-d54d-4b24-a302-fbfc6483bda3.png)

i installed via apt-get install chia-blockchain

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by MumfMeisterT** [comment]
Could you please provide us with logs? 
If you restart the wallet, how long does it take for it to shoot up to this max memory? Does it happen immediately or take a while to get to this? 
- If you delete your wallet db and resync, do you still have the same issue?
