### ISSUE TITLE
[Bug] GUI spins with message "Loading keyring.." . Never finishes.

### ISSUE THREAD

**Issue by weaklysubjective** [Chia-Network/chia-blockchain#14468]
### What happened?

Mac had 1.5 chia.
After stopping daemon and wallet (this was a wallet only install) upgraded to 1.6.2
Changed localhost in config.yaml to point to 192.x.x.x local ip instead of 'localhost'
Started GUI and received the message as in title, and loading never finishes.
QUit out GUI. From command line, start chia node and chia wallet. Both start correctly, only asking for system password , to allow chia access keychain. I allowed Always and it has since stopped asking for password on node startup.
Back to GUI, with node and wallet started from command line, GUI starts up fine, syncs fine and all is well.

Support folks suggested a few things, such as moving .chia_keys, and starting over with mnemonics, removing passphrase, removing any chia entry in keychain etc. None of that made a difference, problem persisted (i.e. GUI spinning with the message if node or wallet weren't already started from command line)

### Version

1.6.2

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
No log output when the problem manifests. Nothing logged.
```

**Comment by weaklysubjective** [comment]
Macos monterey 12.0 beta

**Comment by weaklysubjective** [comment]
All of it. Editing only say self_hostname , or  wallet, or node or both or peer don't work or for me didn't work.

**Comment by weaklysubjective** [comment]
Great , Thanks

**Comment by weaklysubjective** [comment]
Per your instruction : configured DEBUG level. Started GUI (without starting daemon or wallet from CLI). Same issue - loading keyring . Unfortunately no logs.

**Comment by paninaro** [comment]
@weaklysubjective I'm able to repro the issue. The GUI decides whether to launch the daemon based on whether the ui:daemon_host config setting is `"localhost"`, so that's why you're not able to get the GUI to launch the daemon.

I can push a small fix to launch the daemon if `self_hostname === ui:daemon_host`, so you would need your config.yaml to use the same value for both of those keys.

**Comment by weaklysubjective** [comment]
Excellent. Thank you.

**Comment by paninaro** [comment]
@weaklysubjective The fix has been merged into `chia-blockchain-gui` `main`, so the fix will be out in the release _after_ 1.7.0

**Comment by weaklysubjective** [comment]
Thank you. Any chance you can take a look at 14465 under Discussions? This issue and that one are kinda related. 

Request seeks an improvement to the installer to be able to configure what the hostname ought to be in config.yaml. This will make it user-friendly so new users won't have to edit config.yaml and the like. Likewise , Chia GUI also should have an edit field to change the IP Address should the WIFI or other connectivity change within one's LAN.
