### ISSUE TITLE
How do I connect to RPC client without cert

### ISSUE THREAD

**Issue by sibitha-bijesh** [Chia-Network/chia-blockchain#1448]
I want to know how do I connect to RPC client via JsonRpc with public address

**Comment by mariano54** [comment]
You cannot. RPC is only exposed locally and not to the internet, and you need a cert to access it. The wiki explains how you can easily access the RPC by running a local node.
https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces
