### ISSUE TITLE
Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

### ISSUE THREAD

**Issue by sergvdm** [Chia-Network/chia-blockchain#14496]
### What happened?

After upgrade from 1.6.0 to 1.6.3 I unable to claim my 1.75 rewards. After click [Confirm] button on Claim rewards page it displays Error popup with message "Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction." regardless of entered Fee. I tried to delete all unconfirmed transactions on Tokens page (although there are none), still same error.
Also I tried to run cli command but got some another error (see log output). Restart chia services doesn't solve issue as well.
Before upgrade (using 1.6.0) claim works as expected.

### Version

1.6.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
chia plotnft claim -i 4290418599 -m 0.000005

Will claim rewards for wallet ID: 4290418599.
Error performing operation on Plot NFT -f 4290418599 wallet id: 4290418599: {'error': '4290418599', 'success': False}
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 439, in select
RuntimeError: <_overlapped.Overlapped object at 0x0000015F27537540> still has pending operation at deallocation, the process may crash
```

**Comment by sergvdm** [comment]
I found another "Delete unconfirmed transactions" menu item on Claim rewards page. Seems this one does reset some internal state and I was able to claim. Looks like some bug because there was no real unconfirmed transactions but not critical now.

**Comment by hajes** [comment]
I am having same issue as well. Never had that before.

`chia wallet delete_unconfirmed_transactions` doesn't help

how do you delete unconfirmed from CLI, please?

**Comment by sergvdm** [comment]
Before I deleted it from GUI page. Actually GUI should invoke same API command
chia wallet delete_unconfirmed_transactions --id {wallet_id}
but maybe to delete unconfirmed transaction of claim rewards you have to specify explicit wallet id for farm rewards (not default one). I'm not sure but it can explain why two buttons "Delete unconfirmed transactions" on two different GUI pages has different behaviour.
