### ISSUE TITLE
failure to collect rewards 

### ISSUE THREAD

**Issue by pepo19861** [Chia-Network/chia-blockchain#14509]
### What happened?

I have a problem when obtaining a block and entering a request, the 1.75XCH reward is not added to my wallet, but it is deleted from the pool. How should I proceed so that the reward arrives in my wallet?

### Version

1.6.2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
are you self pooling?
if you are, its a known issue thats been lodged already https://github.com/Chia-Network/chia-blockchain/issues/13251

**Comment by BKAUS2001** [comment]
unable to get a mojo to create a pool. When going to the faucet website, I only get this message "already sent". Am supposed to be getting another message? I've been syncing for 4 days now. Am I doing something wrong? should be a setup and that's it?

**Comment by MumfMeisterT** [comment]
> unable to get a mojo to create a pool. When going to the faucet website, I only get this message "already sent". Am supposed to be getting another message? I've been syncing for 4 days now. Am I doing something wrong? should be a setup and that's it?

Hello @BKAUS2001. This seems to be unrelated to the issue above, and sounds like a support question. You may have better luck posting in  `Discussions` here on github, or asking in the `#support`  channel under the `chia_network.public` team in Keybase messenger. If you do believe you have stumbled onto a new bug, please open a new issue here on github. 
Thank you for your submission.
