### ISSUE TITLE
[Bug] GUI frozen on rc6

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#14500]
### What happened?

- downloaded rc6 on m1 mac
- installed
- launched in farming mode, everything normal
- click on nft tab
- screen frozen, no nav buttons clickable, force reset does not reset/resolve

Debug log attached

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/10667867/debug.log)

### Version

1.7.0rc6

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Fixed in the next RC build
