### ISSUE TITLE
[BUG] full node does not sync

### ISSUE THREAD

**Issue by gavraz** [Chia-Network/chia-blockchain#1457]
**Describe the bug**
Full node status is not synced.

**To Reproduce**
The app worked for a while. Had one plot, everything seemed to work.
I closed the app and after reopening, the node is stuck on 'not synced' permanently.

**Expected behavior**
Get fully synced and be able to farm.

**LOG**
Not sure if it is related, but it looks like I only have one connection ("connections: 1").
It appears I get disconnected deliberately by the node itself:
13:12:32.390 wallet src.wallet.wallet_node     : INFO     Will not attempt to connect to other nodes, already connected to {'host': 'localhost', 'port': 8444}
13:12:32.405 wallet src.wallet.wallet_node     : INFO     Closing unnecessary connection to {'host': '121.200.10.155', 'port': 8444}.
13:12:32.420 wallet src.wallet.wallet_node     : INFO     Closing unnecessary connection to {'host': '89.242.86.22', 'port': 8444}.
13:12:32.433 wallet src.wallet.wallet_node     : INFO     Closing unnecessary connection to {'host': '190.94.56.147', 'port': 8444}.
13:12:32.447 wallet src.wallet.wallet_node     : INFO     Closing unnecessary connection to {'host': '102.65.217.162', 'port': 8444}

**Desktop (please complete the following information):**
- OS: Windows 10
- CPU: i7-4790

**Comment by mariano54** [comment]
That's normal, your wallet will only connect to your node, and your node connects to many other people.
