### ISSUE TITLE
[Bug] NFT for NFT offer notification shows up in the offer maker's incoming offer

### ISSUE THREAD

**Issue by cameroncooper** [Chia-Network/chia-blockchain#14589]
### What happened?

I created a NFT for NFT trade offer and tried to send an offer notification. The offer notification came to myself. 

### Version

1.7.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
This is from the offer maker's wallet. You can see that I created the offer in this wallet and it also shows up as an incoming notification:

![Screenshot 2023-02-15 at 5 22 58 PM](https://user-images.githubusercontent.com/93196638/219216570-4d4d9b33-48d0-4869-a818-063ec9bf4002.png)

**Comment by DmitryYamen** [comment]
After the update, part of the NFT disappeared, they are on version 1.6.2, what's the catch?
