### ISSUE TITLE
[BUG] Zombie daemon when app is not closed properly

### ISSUE THREAD

**Issue by Farmer071979** [Chia-Network/chia-blockchain#1458]
When I switched on the screen of my plot/farming devide this morning I saw that windows was in a rebooted state. There was an issue with Norton360 (I run for protection), Chia did not connect to the wallet any more (it seemed). 

Steps taken:
1) I ultimately resolved the Norton issue by restoring the system to a previous recovery point. 
2) I got in the chia application ultimately but the full node tab kept running circles. 
3) I made a backup of the mainnet DB files and after restarting the chia app it started with a fresh sync. 
-> Full node is running again and farming efforts have resumed. 

Unsure of what happened I would love to help making chia blockchain better. I add the debug log:
[debug - info.log](https://github.com/Chia-Network/chia-blockchain/files/6189741/debug.-.info.log)
I hope it gives you guys some valuable insights. If you have any suggestions for me based on the log let me know. 

From my experience I would suggestion this improvement: 
1) Automatic backups of the Mainnet DB. Having to sync again takes a lot of time. Imagine when the blockchain gets real big!

Thanks, if any addition info is needed I am super happy to help where I can. Kind regards, René from the Netherlands.

**Comment by mariano54** [comment]
Looks like you just had a zombie daemon. This bug needs to be fixed.
