### ISSUE TITLE
Harvester Crashed needed restart (asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes)

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#1459]
**Describe the bug**
After encountering the below exception in v1.0 the harvester only needed a restart. It wasn't functional anymore.

00:52:59.066 harvester harvester_server        : INFO     -> farming_info to peer 192.168.1.110 4e1c41e2593f7cffaf05534e8a2acf5127dbf6b40f40f9ec3fec5d9d3cecd25e
00:53:02.598 daemon src.daemon.server          : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/chia/farming/src/daemon/server.py", line 218, in safe_handle
    async for message in websocket:
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/chia/farming/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

- OS: Linux
- OS Version/Flavor: Ubuntu 20
- CPU: Odroid-C4

**Comment by dorkmo** [comment]
did this coincide with the most recent difficulty bump?

**Comment by xorinox** [comment]
Can you tell me at what time (EST)  difficulty moved from 8 to 9?   It only happened on one of 7 harvesters.

**Comment by dorkmo** [comment]
![Screenshot_20210323-093843.png](https://user-images.githubusercontent.com/1923070/112164084-992de880-8bbb-11eb-8e8c-fc7b2f67b836.png)

not sure what time zone

**Comment by xorinox** [comment]
I spoke with fcoleman, chia explorer internally uses utc and browser converts to local time. That means my log error which is in local time to me (EST) is very close to difficulty change

When I look at the Explorer difficulty changed 0:47 EST, harvester error occurred 00:53 EST

Also, why was this error tracked as INFO?

**Comment by mariano54** [comment]
Weird, I wonder why it would happen in difficulty bump.
Can you provide more context? Were you moving files or changing drives?

**Comment by xorinox** [comment]
Plots were not moving around on this specific harvester, in fact the plot hard drives are mounted read-only.

**Comment by xorinox** [comment]
The issue happened again on a different harvester.  I think the exception is thrown by this line of code

https://github.com/Chia-Network/chia-blockchain/blob/91f038e2193755e2a6ca22e2160e2c8f547c23fe/src/daemon/server.py#L247

What is the mechanism by which daemon would restart the harvester just for this case?  The thread was left behind "defunct"

**Comment by xorinox** [comment]
I should note both crashes happened on a remote harvester, with only the harvester/daemon service running on these harvesters, connecting to a remote farmer/node.

**Comment by mariano54** [comment]
This should be fixed. The other remaining error is this crash https://github.com/Chia-Network/chiapos/issues/204
