### ISSUE TITLE
[Request] RPC changes

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14600]
### What happened?

Need to be able to retrieve the `nft_id` from the `chia rpc wallet` endpoint. Currently, you are unable to.

Also, `chia rpc wallet get_transactions` should return something useful other than transaction ID

### Version

*

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by Quexington** [comment]
> Need to be able to retrieve the nft_id from the chia rpc wallet endpoint. Currently, you are unable to.

Can you elaborate what the command you would like to run would look like?

> Also, chia rpc wallet get_transactions should return something useful other than transaction ID

My understanding is that it should: 
```
return {
            "transactions": [
                (await self._convert_tx_puzzle_hash(tr)).to_json_dict_convenience(self.service.config)
                for tr in transactions
            ],
            "wallet_id": wallet_id,
        }
```
can you show what the output currently looks like?

**Comment by Quexington** [comment]
@wallentx can we close this?
