### ISSUE TITLE
[Bug] Offer creation without a requesting asset

### ISSUE THREAD

**Issue by siliconbits** [Chia-Network/chia-blockchain#14604]
### What happened?

When creating an offer users can omit specifying a requesting asset (XCH, Tokens, NFT) by not clicking/expanding any of these options. This results in a valid offer where the user would receive nothing in return. Expectation would be an error notice prompting users to specify a requesting asset for their offer. Note, when clicking/expanding any of the requesting asset options and then leaving the amount/ID field blank an error notice is shown.

### Version

1.7

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
This is an intentional design. We may look to enhancing this in the future with a warning of some sort.
