### ISSUE TITLE
[Bug] Offer disappeared - Coin is frozen

### ISSUE THREAD

**Issue by FreeKopcap** [Chia-Network/chia-blockchain#14609]
### What happened?

Offer disappeared.
Created an offer requesting NFT.
Did not share the offer (created just to test send message to NFT owner but did not know that it is possible only after share on Dexie).
Do not remember if it appeared at the offer list, bur when I switched to another wallet and came back again to cancel the offer - couldn't find.
Total balance decreased, a coin is frozen.

Since I did not share the offer and did not  save it to file - I can not accept the offer and unfreeze the frozen coin. 

Tried to find the offer in CLI but got errors (see in Relevant log output section)

### Version

1.7.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
➜  ~ chia wallet get_offers


Active Wallet Key (*):
   -Fingerprint:           1024930875
   -Label:                 Farmer
   -Sync Status:           Synced

Wallet Keys:
1)  * 1024930875   Farmer
(...skipped...)
Choose a wallet key [1-5] ('q' to quit, or Enter to use 1024930875):
Exception from 'wallet' {'error': 'clvm raise', 'success': False}:
Traceback (most recent call last):
  File "chia/cmds/cmds_util.py", line 100, in get_any_service_client
  File "chia/cmds/cmds_util.py", line 211, in execute_with_wallet
  File "chia/cmds/wallet_funcs.py", line 548, in get_offers
  File "chia/rpc/wallet_rpc_client.py", line 730, in get_all_offers
  File "chia/rpc/rpc_client.py", line 61, in fetch
ValueError: {'error': 'clvm raise', 'success': False}
```
![Coin frozen](https://user-images.githubusercontent.com/125664809/219666846-71614d9c-4aa5-4455-9857-2281a310fb4b.png)

**Comment by siliconbits** [comment]
Delete the wallet db files and resync. That will restore your full balance as coins are only "frozen" locally in your db, not on the chain itself.

On mac the wallet db files are located in: `~/.chia/mainnet/wallet/db`
(exit chia, right click Finder, select Go to Folder and paste the location above, bin the files then re-open chia)

p.s if you did share your offer, then additionally you can send your full balance to yourself to invalidate any previous offers (thus "spending" those coins and being no longer valid for anyone trying to accept the offer).

**Comment by FreeKopcap** [comment]
Thank you, it helped.
But why this happened? If DB got corrupted - maybe a program should delete it by itself and synchronize?

**Comment by FreeKopcap** [comment]
BTW: A strange transactions while I tested offer creation/cancellation.
I created similar offer from my second account (similar to this one: offer requesting NFT to test messaging).
I have successfully cancel it when I understood I couldn't find "send message" option.
But today, when checking there was no problems in DB (similar to the previous case) - I discovered a strange outgoing transaction from my wallet.
I wasn't going to do anything учсузе testing messaging that night an do not remember any transactions I could have made.
I remember sometimes there were some options for transaction fees to make an offer or to cancel it, but the amount of the transaction is too high for a fee: 0.075585999995 XCH.
Could you please inspect transaction # 0xed9b2f12f2a45d5033502ddce28c10d6fef10f435b2ef8c2fd6b285c66bf4fb1 - what is this type of transaction, is there any specific?

**Comment by MumfMeisterT** [comment]
Do you still have your logs from around the time of your initial post? And could you include those here? 
I would also post this in Keybase #support channel as well.
