### ISSUE TITLE
Rewarding Truely on "PROOF OF TIME AND SPACE"

### ISSUE THREAD

**Issue by rkandel** [Chia-Network/chia-blockchain#1460]
I like the concept of "Proof of Time and Space". However, from my understanding Time factor is forgotten when rewarding the farmer.

If we want to be different and resolve the issues experienced by previous blockchains, we need to do things differently. We need to make it harder for people to centrelise the farming process such as creating pools or few people creating data center to farm Chia. what we should do is encourage individual farmers which was the original principal of Blockchain and BitCoin. 

One of the way to do this is by using PROPORTIONATE mechanism rather than PROBABILITY MECHANISM. What I mean by this is take count of the time spent by farmers like in real life. When you go and work in the farm, you get paid by hours. So, someone working for 100 gets paid proportionately as the person working for 1 hours does. Let's say, in addition to the the plots, we keep notice of the time spent by the farmer. So, if the farmer with 100 plots get paid in 1 block a day. The other farmer with 1 plot gets 1 block in 100 days. To implement this concept, we can utilise Timelord severs. PROPORTIONATE mechanism guarantees the payment where PROBABILITY mechanism shows the "chances" of winning like a lottery which means that you may never win in your life even if there is a chance of winning it. The simple solution would be to send the wining block at the end of the queue. Maintaining the known queue becomes a point of attack from malicious players. So, we use a algorithm to send the winning plot at the back of the queue in a random order. Therefore, it is unpredictable users.

**Comment by hoffmang9** [comment]
The math does not work like that. https://www.chia.net/assets/Chia_Proof_of_Space_Construction_v1.1.pdf
