### ISSUE TITLE
[Request] coins for RPC

### ISSUE THREAD

**Issue by nongyehezuoshe** [Chia-Network/chia-blockchain#14617]
### What happened?

for now, there's some coins commands in cli: https://docs.chia.net/wallet-cli#coins
but, there's no rpc commands, it's sholud add to RPC.

### Version

1.7.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
RPC `/split_coins` and `/combine_coins` have been added in 2.4.4 - list coins may not be added - closing
