### ISSUE TITLE
Accepted offer is always pending confirm[Bug] 

### ISSUE THREAD

**Issue by nqzhang** [Chia-Network/chia-blockchain#14621]
### What happened?

Offer accepted by multiple people at the same time - stuck in "Pending Confirm" and cat transactions record stuck in pending

![image](https://user-images.githubusercontent.com/12559853/219931373-87ead178-df10-4f6a-9441-71126cc6db64.png)
![image](https://user-images.githubusercontent.com/12559853/219931386-7a363a56-52ac-4b70-91a4-4d7d3a9f9828.png)
![image](https://user-images.githubusercontent.com/12559853/219931394-02305a9a-08d9-40cd-bc45-d1b86b87013c.png)

### Version

1.7.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by nqzhang** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/11101
https://github.com/Chia-Network/chia-blockchain/issues/11796
https://github.com/Chia-Network/chia-blockchain/issues/10651

**Comment by MumfMeisterT** [comment]
What happens when you delete unconfirmed transactions? 
In the GUI go to Tokens> Send>  Actions> "Delete Unconfirmed Transactions"

**Comment by MumfMeisterT** [comment]
#14632

**Comment by nqzhang** [comment]
Of course, the offer can be canceled, and the unconfirmed transaction can also be canceled. But this state is inappropriate

**Comment by nqzhang** [comment]
fixed in this pr,close this issue
https://github.com/Chia-Network/chia-blockchain/pull/14722
