### ISSUE TITLE
[Bug] Offline/Airgap GUI stuck on loading keyring status

### ISSUE THREAD

**Issue by sbstockmeup** [Chia-Network/chia-blockchain#14622]
### What happened?

I was making a cold wallet on an airgapped machine with brand new windows 10 install and 1.7.0 but I ran into it getting stuck on loading keyring status via the GUI. CLI worked, but tried a bunch of various things. Eventually, just connected to the web thinking it's a time sync issue or something, then it worked right away.

What ultimately found was that changing config.yaml from self_hostname: &self_hostname "localhost" to self_hostname: &self_hostname 127.0.0.1, this change allowed the keyring status to load while the machine is offline. My guess since it's offline it can't figure out what to do.

Kudos to this thread for giving me the idea. https://github.com/Chia-Network/chia-blockchain/issues/4153

I feel like the process should be more simple, load up Chia GUI, generate key. A lot of hassle to find this solution.

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by sbstockmeup** [comment]
Actually, if you do it from scratch windows profile you still can't use GUI to generate coldwallet key. The config.yaml isn't fully setup from that it looks like. Is there a step I'm missing or only CLI?

**Comment by MumfMeisterT** [comment]
On your airgapped machine pull up a terminal and run `ping localhost` and `ping 127.0.0.1` 

This is not necessarily a bug, but we are tracking to fix this in our roadmap here: https://roadmap.chia.net/c/24-cold-wallet-mode?utm_medium=social&utm_source=portal_share 

This looks like an old Windows issue: 
https://social.technet.microsoft.com/Forums/windows/en-US/208622c5-0dba-4b85-8ee8-66f7f0a875de/windows-7-hostname-lookup-fails-if-not-connected-to-the-internet?forum=w7itpronetworking
