### ISSUE TITLE
[Bug] Status doesn't update

### ISSUE THREAD

**Issue by Pandelta** [Chia-Network/chia-blockchain#14639]
### What happened?

The Plotting Status no longer updates unless you click another tab and come back to the Plots tab. It will only update instantly and then no more. The same issue exist when you click the dots and go to View Log. It does not update there either except when you first open it.

### Version

1.7.0

### What platform are you using?

Windows & Linux

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Two bugs logged for this issue - Closing  #14656, and leaving this ticket open.

**Comment by Rickinrogers** [comment]
does version 1.8.0bt fix it?

**Comment by paninaro** [comment]
> does version 1.8.0bt fix it?

This issue hasn't been addressed yet

**Comment by ChiaMineJP** [comment]
Fix is going in.
