### ISSUE TITLE
recursive_plot_scan directive stops scanning and causes 0 plots on harvester when any of subdirs are empty.

### ISSUE THREAD

**Issue by chilio** [Chia-Network/chia-blockchain#14637]
### What happened?

When using `recursive_plot_scan=true` directive  chia stops scanning when any of subdirs is empty, therefore harverster gets zero plots although at least some subdirectories are filled with plots.
Please review this https://github.com/Chia-Network/chia-docker/issues/187

### Version

1.7.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by Starttoaster** [comment]
After some investigating in https://github.com/Chia-Network/chia-docker/issues/187, I believe we need more information to understand what's happening, if it may be something more specific to your setup. I couldn't replicate this with the additional information given in the referenced Issue.

**Comment by emlowe** [comment]
Closing issue
