### ISSUE TITLE
Part of the NFT disappeared, they are on version 1.6.2[Bug] 

### ISSUE THREAD

**Issue by DmitryYamen** [Chia-Network/chia-blockchain#14644]
### What happened?

After the update, part of the NFT disappeared, they are on version 1.6.2

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by djerfy** [comment]
@DmitryYamen, you can try this in GUI?
1. Go to "Settings" and "NFT"
2. Disable "Hide objectionable content"

**Comment by MumfMeisterT** [comment]
Duplicate of #1493. Linking and closing current ticket.
