### ISSUE TITLE
Call to zstd.compress fails on systems with high thread counts

### ISSUE THREAD

**Issue by mwpastore** [Chia-Network/chia-blockchain#14667]
[python-zstd](https://github.com/sergey-dryabzhinsky/python-zstd) includes its own utility function UTIL_countPhysicalCores that tries to figure out the number of logical processors on a system. Unfortunately zstd.compress throws an error if the system has more than 200 logical processors. The utility function appears to ignore process affinity so it's impossible to work around it with e.g. taskset or Process Lasso. Any system with more than 200 threads is unable to run the full node due to this issue. 

zstd.compress accepts additional positions in the arguments tuple for A) a compression level (which can be set to zero to get the default behavior) and B) a thread count. Passing a thread count bypasses UTIL_countPhysicalCores. We could update the call to zstd.compress to include a sane fixed value, or a better estimate for the number of logical processors, or possibly the value of an environment variable or a configurable from config.yaml. 

https://github.com/Chia-Network/chia-blockchain/blob/ff5ef6e073ecd69537bc353c24f1b3a0a50b03f9/chia/full_node/block_store.py#L134

For example:

```py
zstd.compress(bytes(block), 0, 8) 
```

**Comment by emlowe** [comment]
Thanks - this seems fixed in zstd 1.5.4.1 - leaving this open to track that change in setup.py

**Comment by xorinox** [comment]
Updated setup.py to zstd 1.5.4.1, reinstalled (sh install.sh), problem does not occur anymore.

**Comment by emlowe** [comment]
zstd in main is updated - so this should be fixed in the next release from main

**Comment by emlowe** [comment]
Closing issue, fixed in 1.8.2
