### ISSUE TITLE
1.7.0 Cannot connect to host[Bug] 

### ISSUE THREAD

**Issue by DannKenn** [Chia-Network/chia-blockchain#14677]

**Comment by DannKenn** [comment]
I sent partials pool drop more than %30 . i will follow this thread

**Comment by DannKenn** [comment]
I since upgraded 1.7.0 see more (( Block validation time: 2.25 seconds, pre_validation time: 0.30 seconds, cost: 5255897644, percent full: 47.781% header_hash: f616983364661b94dd352bc4335a43265661d69ed201bf5bfde3ac1a1015e16b height: 3303506 ))

**Comment by emlowe** [comment]
Insufficient details provided - please reopen with details and log output
