### ISSUE TITLE
Block has been loading for 24 hours

### ISSUE THREAD

**Issue by andrewlaery** [Chia-Network/chia-blockchain#1468]
Hi Team,

I have a new installation of Chia on an iMac 2015 running MacOS Big Sur 11.2.3. Very excited.

In the Full Node tab the Block section has been loading (the is the circle spinning) for over 24 hours now. I have managed to create a Plot, although the status of the Plot is 'Not Available'...

Is this just a timing issue (I know it takes a long time to set these things up), or do I have an issue here with my installation?

Thanks!
Andrew

<img width="1195" alt="Screen Shot 2021-03-24 at 9 44 52 AM" src="https://user-images.githubusercontent.com/5120738/112215816-ac0cef80-8c85-11eb-842e-288ca6fa997b.png">
<img width="1195" alt="Screen Shot 2021-03-24 at 9 45 21 AM" src="https://user-images.githubusercontent.com/5120738/112215823-afa07680-8c85-11eb-93bd-94d91d2cc6cd.png">

**Comment by Cryolitecoin** [comment]
sometime on Ubuntu I need to restart chia 1,2,3 time and It work

**Comment by mariano54** [comment]
There was a sync issue with 1.0.0. Please try 1.0.1.
