### ISSUE TITLE
[Bug] Block Reward Issue

### ISSUE THREAD

**Issue by Jason816wcc** [Chia-Network/chia-blockchain#14699]
### What happened?

Hi Sir,
My ID found 19 Block but ony got 2.75XCH Block Rewards,

According to Space pool policy the erery Block Reward will get 0.25XCH that the 19 block found should be 4.75 XCH (19x0.25=4.75).

My Space Launcher Id as below:
0x10e85b52eb1abfad0af7d878743e4458dbd6a9fdef0ee5fdbd86d8d248f57eb9

Thanks for your help.

Jason816wcc

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by stefan-lange** [comment]
You can check the farmer address of all Blocks. Your latest won blocks have a different address.

**Comment by Jason816wcc** [comment]
Hi Sir,
I do not know this address ????? I need call police for this case?
xch1u57qhwnrsvacr5trfu3nwrfdzjx27k76tq0uegq2pwrr90kmj3us53nkvh
Any futher suggesttions?
How to change to my Space Launcher Id ?0x10e85b52eb1abfad0af7d878743e4458dbd6a9fdef0ee5fdbd86d8d248f57eb9

Thanks for your help.

Thanks for your great help.

Jason Chou

**Comment by MumfMeisterT** [comment]
Seems this has been resolved. Closing ticket.
