### ISSUE TITLE
[Bug] Could not connect to host

### ISSUE THREAD

**Issue by BarSergey** [Chia-Network/chia-blockchain#14718]
### What happened?

I don't connect to any host
North Asia introducer-apne.chia.net:8444
South Asia introducer-apse.chia.net:8444
Western North America: introducer-or.chia.net:8444
Eastern North America introducer-va.chia.net:8444
Europe: introducer-eu.chia.net:8444

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Those introducers are no longer usable and should not be used - those DNS names don't resolve to anything. You shouldn't try to manually connect to an introducer anyway as those are not for syncing.

Your node will attempt to bootstrap other nodes by querying the introducer and DNS seeder automatically .

You can try to manually add a peer, but you cannot use those listed names. You could try `node.chia.net` - however this node is often full and doesn't accept new connections.

It is best if you just let the software find peers in the automatic way

**Comment by BarSergey** [comment]
software don't find peers in the automatic way.
