### ISSUE TITLE
1.8 B3 Stuck on starting Full Node[Bug] 

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain#14783]
### What happened?

When i upgraded from 1.7 to 1.8 B3 on my testnet machine, when i restart the client, it gets stuck on Starting Services Full Node screen
![image](https://user-images.githubusercontent.com/36589806/223860793-6246b0ef-162d-4097-a42f-46748fe34588.png)

I can uninstall 1.8, and reinstall 1.7 and it loads up fine

### Version

1.8 B3

### What platform are you using?

Linux Ubuntu 22.04.2

### What ui mode are you using?

GUI

### Relevant log output

```shell
Can send a copy of the logs via keybase
```

**Comment by MumfMeisterT** [comment]
Try the branch #14788 and see if that works.

**Comment by shaneo257** [comment]
![image](https://user-images.githubusercontent.com/36589806/224149681-0dee343e-652e-4c0e-ab02-e3772d82bf15.png)
installed and working
