### ISSUE TITLE
[Bug]  what's this?? 

### ISSUE THREAD

**Issue by JustAlias** [Chia-Network/chia-blockchain#14806]
### What happened?

![image](https://user-images.githubusercontent.com/93747660/224497058-f3efad13-585b-4ced-98fa-85dabb62ea95.png)

I have 50 harvesters, the harvester and the farmer are not on the same machine, the harvester connected to the farmer times wrong

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-03-12T00:48:54.054 farmer asyncio                    : ERROR    Task exception was never retrieved

future: <Task finished name='Task-2141' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:568> exception=OSError(22, '??????????????????????', None, 64, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 560, in finish_accept
OSError: [WinError 64] ??????????????????????

2023-03-12T00:48:54.067 farmer asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=744, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 28006)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 819, in loop
  File "asyncio\windows_events.py", line 571, in accept_coro
  File "asyncio\windows_events.py", line 817, in _poll
  File "asyncio\windows_events.py", line 560, in finish_accept
OSError: [WinError 64] ??????????????????????
```

**Comment by JustAlias** [comment]
After the error, other harvesters can no longer connect to the farm

![image](https://user-images.githubusercontent.com/93747660/225026911-e3149cce-92fa-4c11-96e7-8e3d665b55e3.png)

**Comment by MumfMeisterT** [comment]
This sounds like a networking issue, I would try restarting your farmer and rebooting your router to see if that resolves.

**Comment by JustAlias** [comment]
> This sounds like a networking issue, I would try restarting your farmer and rebooting your router to see if that resolves.

Yes, restarting the harvester won't help. Restarting the farmer will reconnect, but it will reappear after a while

**Comment by JustAlias** [comment]
> > This sounds like a networking issue, I would try restarting your farmer and rebooting your router to see if that resolves.
> 
> Yes, restarting the harvester won't help. Restarting the farmer will reconnect, but it will reappear after a while

So it's not a network issue, I'm guessing, it's the farmer's wait to connect process hanging up due to some kind of error, causing the new harvester to fail to connect

**Comment by wallentx** [comment]
Are you able to set your logging to `DEBUG` in your `config.yaml` on both your host that is running the farmer, and on one of the hosts running a harvester that is unable to connect? If you are able to provide us with those logs, that might give us a bit more info.

**Comment by altendky** [comment]
> the harvester connected to the farmer times wrong

Could you say more about this?  I'm not sure quite how to interpret it.

> `OSError: [WinError 64] ??????????????????????`

The error text is literally `??????????????????????`? You didn't redact the text due to it being your IP or such?

**Comment by emlowe** [comment]
Closing due to lack of response
