### ISSUE TITLE
config set not send to the new address, but when the offer is canceled, the derived index will increase [Bug] 

### ISSUE THREAD

**Issue by nqzhang** [Chia-Network/chia-blockchain#14802]
### What happened?

In the latest version, it is set not to send to the new address, but when cancel an anoffer, the derived index will increase

### Version

1.7.1-rc1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by nqzhang** [comment]
![image](https://user-images.githubusercontent.com/12559853/224431763-6f5b50fa-c251-421c-ae47-1ea7225f532b.png)
The reuse_public_key_for_change is set in the settings, and the derived index will not grow when test receiving the offer, but if an offer is created and canceled immediately, the derived index will be increased

**Comment by nqzhang** [comment]
Creating an nft offer will also increase the derived index

**Comment by emlowe** [comment]
This may have been resolved in 2.1.0 in PR https://github.com/Chia-Network/chia-blockchain/pull/16116

Closing issue, can reopen or add new issue if additionals problems remain
