### ISSUE TITLE
Full Node RPC: get_mempool_item_by_coin_name endpoint

### ISSUE THREAD

**Issue by Yakuhito** [Chia-Network/chia-blockchain#14810]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/14809

<div type='discussions-op-text'>

<sup>Originally posted by **Yakuhito** March 13, 2023</sup>
Hello,

The way I see it, a fully 'decentralized' spend aggregation feature (i.e., no central sequencer) would require searching the mempool for spends & building your transaction on top of them. I've tried doing something similar and was surprised to find out that the full node RPC only allows you to get mempool items either by the transaction id (which is the sha256 of the spend bundle) or all at once. I'm writing this message to request a new endpoint that would take a coin name (id) as an argument and return the mempool item that spends that coin, if it exists.

The current workaround is getting all items at once and filtering them, which is very inefficient. I've seen that, for the current ~1700 items on testnet10, my python script took more than 30 seconds to decode the response (that's useless, given that the block time is lower than 60s).

This is not urgent, but I'm sure it would be a great addition to the Full Node RPC API.

Thank you,
yakuhito </div>

**Comment by Yakuhito** [comment]
Update: I don't know what my computer was doing last night, but the JSON response is now decoding in a few seconds. However, this endpoint would still be nice to have.

**Comment by Yakuhito** [comment]
Hey there, GitHub Actions Bot! Thanks for the heads up about my issue being flagged as stale. I know it's been a while since I've updated it, but trust me, it's like a fine wine that only gets better with age. The issue already contains all the relevant details, so there's no need for me to add more grapes to the mix. Let's keep this issue open and fermenting like a good bottle of cabernet sauvignon! 🍷

**Comment by kimsk** [comment]
I have a [PR](https://github.com/Chia-Network/chia-blockchain/pull/15625) ready.
