### ISSUE TITLE
After starting Chia - Stuck on "Connecting to Wallet" 

### ISSUE THREAD

**Issue by rice-gohan** [Chia-Network/chia-blockchain#1482]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by buktor79** [comment]
Hello , I have same problem , today installed Chia on my mac , in the beginning worked well but now I can't start it up again. Program is stuck on "Connecting to wallet" . I tried to install it again but still same . Mac 2,7GHz  4core intel core i5 , Mac OS Catalina version 10.15.7
print screen attached how chia is stuck
![Zrzut ekranu 2021-03-29 o 13 44 37](https://user-images.githubusercontent.com/81565939/112832362-7e64e380-9095-11eb-8fca-e808a5dcacff.png)

thank you for help

**Comment by rice-gohan** [comment]
I ended up erasing the HD and re-installing Big Sur. I then downloaded chia 1.01(latest at the time, might still be?). I was at 1.0 prior.
Following this it worked for me. 

Best of luck!
