### ISSUE TITLE
[Bug] after updating the wallet to version 1.7.0, I can't log in using the keyword. 

### ISSUE THREAD

**Issue by lubarets-evgeni** [Chia-Network/chia-blockchain#14826]
### What happened?

after updating the wallet to version 1.7.0, I can't log in using the keyword. a couple of months ago, I calmly entered the wallet using my SID phrase, then I did not use it and did not delete it, the other day I went in and the wallet requested the sid phrase - after entering a message that the sid phrase is incorrect (which cannot be, it is written only on paper and has been entered correctly on the same device several times). When entering this phrase into other web wallets, it is accepted to the coin balance shows 0. Please help restore the wallet.

### Version

1.7.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
which web wallet did you try?
what version did you upgrade from?

**Comment by lubarets-evgeni** [comment]
Yes, this is a problem with entering my 24-word mnemonic key. I launch the application, then enter the password, then the application asks me to enter a mnemonic key of 24 words, I enter them, but the application writes that the word order is incorrect, although it is correct because I have repeatedly entered my wallet using this key and did not change the mnemonic key.

**Comment by lubarets-evgeni** [comment]
I have tried Goby, Pawket, Frodo web wallets. Goby does not accept my mnemonic key as well as the official Chia wallet. Pawket, Frodo accept the mnemonic key, but the token balance shows 0. The official Chia wallet was updated from version 1.3.559 to version 1.7.0

**Comment by lubarets-evgeni** [comment]
> Yes, this is a problem with entering my 24-word mnemonic key. I launch the application, then enter the password, then the application asks me to enter a mnemonic key of 24 words, I enter them, but the application writes that the word order is incorrect, although it is correct because I have repeatedly entered my wallet using this key and did not change the mnemonic key.

Yes, this is a problem with entering my 24-word mnemonic key. I launch the application, then enter the password, then the application asks me to enter a mnemonic key of 24 words, I enter them, but the application writes that the word order is incorrect, although it is correct because I have repeatedly entered my wallet using this key and did not change the mnemonic key.

**Comment by lubarets-evgeni** [comment]
> I have tried Goby, Pawket, Frodo web wallets. Goby does not accept my mnemonic key as well as the official Chia wallet. Pawket, Frodo accept the mnemonic key, but the token balance shows 0. The official Chia wallet was updated from version 1.3.559 to version 1.7.0

I have tried Goby, Pawket, Frodo web wallets. Goby does not accept my mnemonic key as well as the official Chia wallet. Pawket, Frodo accept the mnemonic key, but the token balance shows 0. The official Chia wallet was updated from version 1.3.559 to version 1.7.0

**Comment by lubarets-evgeni** [comment]
> Before we start getting to far into this, could you please elaborate on exactly what you mean by "SID phrase". We have the 24 word mnemonic key that is the master key that users create at first. Is this a problem with entering your 24 words mnemonic key ?

Yes, this is a problem with entering my 24-word mnemonic key. I launch the application, then enter the password, then the application asks me to enter a mnemonic key of 24 words, I enter them, but the application writes that the word order is incorrect, although it is correct because I have repeatedly entered my wallet using this key and did not change the mnemonic key.

**Comment by lubarets-evgeni** [comment]
> which web wallet did you try? what version did you upgrade from?

I have tried Goby, Pawket, Frodo web wallets. Goby does not accept my mnemonic key as well as the official Chia wallet. Pawket, Frodo accept the mnemonic key, but the token balance shows 0. The official Chia wallet was updated from version 1.3.559 to version 1.7.0

**Comment by MumfMeisterT** [comment]
What Wallet provider did you use to generate the key in the first place? (e.g. chia, Pawket, etc)
Can you please try with Chia version 1.6.2?
If you continue having issues, we recommend you come to the Keybase #Support channel for further assistance. 
https://keybase.io/team/chia_network.public 
I would also run a `chia keys show` and make sure you are on the right key.
