### ISSUE TITLE
[BUG] Debian 9 fails to install as it can't find Python3.7 in apt

### ISSUE THREAD

**Issue by timjrobinson** [Chia-Network/chia-blockchain#1484]
**Describe the bug**
When running `sh install.sh` on Debian 9 it fails with the following errors:

```
E: Unable to locate package python3.7-venv
E: Couldn't find any package by glob 'python3.7-venv'
E: Couldn't find any package by regex 'python3.7-venv'
E: Unable to locate package python3.7-distutils
E: Couldn't find any package by glob 'python3.7-distutils'
E: Couldn't find any package by regex 'python3.7-distutils'
```

Python 3.7 isn't in the debian repositories. 

I already had Python3.8 installed by compiling it myself and so I went into install.sh, commented out the line where it tried to install python3.7, and then installation completed successfully. 

**To Reproduce**

1. Clone repository
2. CD into repository
3. Run `sh install.sh`
 
**Expected behavior**

I expect the installation script to detect that I have python 3.8 already and not try and install python from apt. Python is not always installed from apt so I think this should be the general flow anyway, only install from apt if it's not installed already or an old version.

**Desktop (please complete the following information):**
```
tim@emrakul:~/$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
tim@emrakul:~$ uname -a
Linux emrakul 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux
tim@emrakul:~$ python --version
Python 3.8.6
tim@emrakul:~$ which python
/usr/local/bin/python
```

**Comment by timjrobinson** [comment]
I get a similar issue when running `install-gui.sh` I already have npm and nodejs installed and at latest versions, but its trying to install npm from apt anyway:

**Comment by aqk** [comment]
Great bug report. We have a bit more sophisticated Python detection for Linux now. Would you mind running install.sh again, and seeing if we catch the right version on your setup?

We've moved npm install into `install-gui.sh`
I pushed a test branch here: https://github.com/Chia-Network/chia-blockchain/tree/debian-install


```
git checkout debian-install
bash install.sh
install-gui.sh
```


Please give that shot and see if it fixes install on your system.

Please also be aware that that branch is based off main, for merging purposes. If that does work, please return to `v1.1.2
` or another official branch while awaiting the fix.

**Comment by lvpcguru** [comment]
How did this go in the end? Can the bug be closed? it has been a while
