### ISSUE TITLE
[BUG] WINDOWS GUI

### ISSUE THREAD

**Issue by pjt87uk** [Chia-Network/chia-blockchain#1485]
same problem as last time, no changes in this latest update.
please don't delete this unless it is fixed as im having to retype it out. 
![image](https://user-images.githubusercontent.com/79751624/112297859-483af480-8c8e-11eb-85a2-90de620b3e2d.png)

**Comment by dorkmo** [comment]
you didnt change anything in your config.yaml file did you?

**Comment by pjt87uk** [comment]
Not changed a thing just kept up with updates and plotting got this on main net launch

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mariano54** [comment]
Please do the following: Close chia and all chia processes in the task manager (make sure to check for full_node, daemon, etc).
Then delete this folder:
~/.chia/mainnet
Then reinstall the new version of chia.

Please do this and report back.
