### ISSUE TITLE
[BUG] Cannot connect to wallet

### ISSUE THREAD

**Issue by karsonbraaten** [Chia-Network/chia-blockchain#1486]
Mac had shutdown because of an issue overnight (unsure if Chia related). Chia would've been plotting and farming. When I open Chia now it just hangs on "Connecting to wallet".

I installed Chia v1.0.1, thinking maybe the update would fix it but still same problem. In Chia, tried "Reload" and "Force Reload" to no avail.

Is there a simple way to just install a fresh version of Chia?
Are there any logs I can dig up in case there is something valuable in there?

Thanks!

- OS: Mac 11.2.3
- CPU: 3.1 GHz Dual-Core Intel Core i7

**Comment by mescab** [comment]
I got the same thing, stuck in "connecting to wallet" , after farming overnight and shutdown.

**Comment by mescab** [comment]
> Mac had shutdown because of an issue overnight (unsure if Chia related). Chia would've been plotting and farming. When I open Chia now it just hangs on "Connecting to wallet".
> 
> I installed Chia v1.0.1, thinking maybe the update would fix it but still same problem. In Chia, tried "Reload" and "Force Reload" to no avail.
> 
> Is there a simple way to just install a fresh version of Chia?
> Are there any logs I can dig up in case there is something valuable in there?
> 
> Thanks!
> 
> * OS: Mac 11.2.3
> * CPU: 3.1 GHz Dual-Core Intel Core i7

I removed the .chia directory, and reinitialized over again, everything is OK now, but it took me several hours to get this done.

**Comment by karsonbraaten** [comment]
This worked for me too 👍
