### ISSUE TITLE
[Bug] duplicated short options, `-r`, in `make_offer` CLI causing missing option error.

### ISSUE THREAD

**Issue by kimsk** [Chia-Network/chia-blockchain#14874]
### What happened?

`-r` is already used for `--request` but it's now also used for `--reuse`, `Reuse existing address for the change.`, and this causes `make_offer` error, `Error: Missing option '-r' / '--request'.`

https://github.com/Chia-Network/chia-blockchain/blob/9a4b42b022a31357e36fd92900cf3efc3be8a02d/chia/cmds/wallet.py#L411-L425

### Version

1.7.1-rc3

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
❯ chia wallet make_offer -f $maker_fp -r 1:0.08 -o 2:15.898 -p offer1.offer
Usage: chia wallet make_offer [OPTIONS]
Try 'chia wallet make_offer -h' for help.

Error: Missing option '-r' / '--request'.
```

**Comment by kimsk** [comment]
The work around is to use `--request` instead of `-r`.

**Comment by MumfMeisterT** [comment]
#15004
