### ISSUE TITLE
 loading keyring status on macOS 10.14

### ISSUE THREAD

**Issue by hajes** [Chia-Network/chia-blockchain#14907]
### What happened?

Updated to latest 1.7.1 GUI macOS

"loading key ring status"

Removed all for clean setup...loading config. Installed back 1.7.0 that worked just 10 minutes ago. Result is same.

### Version

1.7.1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
Nothing in log despite "DEBUG" set.
```

**Comment by hajes** [comment]
downgraded to 1.6.2
1.7.0, 1.7.1 doesn't work on macOS either installed via `brew install chia` or dmg from chia.net

**Comment by MumfMeisterT** [comment]
I would backup your .chia folder somewhere else and then delete it entirely. Restarting Chia will regenerate the folder. 
-- If it then works, you can try moving your full node db back in first (.chia/mainnet/db) to see if that is the corrupted db, if so you will need to resync. (you can download from our latest checkpoint here: https://www.chia.net/downloads/#database-checkpoint)

**Comment by hajes** [comment]
That was the first troubleshoot I did...erase everything, clean install. I use light wallet connected to local/remote node. There is no full blockchain.

Anything above 1.6.x version gets stuck either:

loading keyring
loading configuration

I see a new `.chia/mainnet/gui/` folder with content inside...that's all. It is stuck at loading config. No errors, no nothing. No idea how to debug.

It may be Python issue, no idea. I am using the last 1.6.x version, that works.

**Comment by MumfMeisterT** [comment]
You could try from the command line chia keys show` to see if it will load the keyring.

**Comment by hajes** [comment]
How do I use CLI in macOS and LightWallet mode?

**Comment by MumfMeisterT** [comment]
You can open a shell and: `cd /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon` 
and then run `./chia keys show`

**Comment by omzig10** [comment]
Same issue...Windows, v1.7.1 "Loading Keyring Status" forever.

**Comment by hajes** [comment]
> You can open a shell and: `cd /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon` and then run `./chia keys show`

latest version 1.8.1 - as suggested.

/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/chia keys show
Traceback (most recent call last):
  File "chia/cmds/chia.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "chia/cmds/beta.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "chia/cmds/beta_funcs.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "chia/util/chia_logging.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "chia/cmds/init_funcs.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "chia/consensus/coinbase.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "chia/wallet/puzzles/p2_delegated_puzzle_or_hidden_puzzle.py", line 70, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "chia/wallet/puzzles/load_clvm.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "clvm_tools_rs/__init__.py", line 1, in <module>
ImportError: dlopen(/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/clvm_tools_rs/clvm_tools_rs.abi3.so, 2): no suitable image found.  Did find:
	/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/clvm_tools_rs/clvm_tools_rs.abi3.so: cannot load 'clvm_tools_rs.abi3.so' (load command 0x80000034 is unknown)
	/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/clvm_tools_rs/clvm_tools_rs.abi3.so: cannot load 'clvm_tools_rs.abi3.so' (load command 0x80000034 is unknown)
[26726] Failed to execute script 'chia' due to unhandled exception!

**Comment by emlowe** [comment]
What version of macOS are you running and on which CPU (Intel or Apple Silicon).

I can reproduce this error on macOS 10.14 , but not on anything newer.

**Comment by hajes** [comment]
Still old school, and the most stable macOS 10.14 ;-)

**Comment by MumfMeisterT** [comment]
We need to build the chia clvm_tools_rs wheel on MacOS 10.14

**Comment by hajes** [comment]
It would be great if you can keep backward compatibility if possible. Lots programs force new versions of OS

**Comment by emlowe** [comment]
It is possible to manually install chia CLI on macOS 10.14

Assuming you have a working homebrew installed.
- I like to use pyenv for python management: `brew install pyenv` and finish the steps
- install python 3.9.15: `pyenv install 3.9.15` (note you can also any python 3.8.x and up)
- switch to use : `pyenv global 3.9.15`
- make sure python seems correct with `python --version`
- install chia source `git clone -b release/1.8.0 https://github.com/Chia-Network/chia-blockchain.git`
- install chia with `sh install.sh -d`
- activate the venv `source ./activate`
- install rust: https://www.rust-lang.org/tools/install
- force reinstall the clvm_tools_rs wheel: `pip install --force-reinstall clvm_tools_rs==0.1.30 --no-binary :all:`
- wait for compile to finish 
- chia CLI should now work `chia keys show`

**Comment by emlowe** [comment]
Closing issue - per company discussions macOS 10.14 was planned to be deprecated soon and we unfortunately did that somewhat sooner than expected. However, given company resources at this time we don't plan on going back and fixing it.

You can run from source and build as mentioned above
