### ISSUE TITLE
NFTs tab doesn't load

### ISSUE THREAD

**Issue by hwfanatic** [Chia-Network/chia-blockchain#14903]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/14865

<div type='discussions-op-text'>

<sup>Originally posted by **hwfanatic** March 21, 2023</sup>
Clicking on the NFTs tab shows loading icon, but it doesn't actually load or display anything ever. No log entries. It doesn't crash. It just doesn't work.

Please add labels: 1.7.1, GUI, help wanted, Windows</div>

**Comment by maxfrank76** [comment]
the same problem, windows server 2019 system, NFTs tab infinite loading. v1.7.1
![Снимок экрана 2023-03-24 в 22 26 16](https://user-images.githubusercontent.com/77428240/227622162-8263a9e3-d3b8-4a34-8b1f-b90d1bf96fb6.png)

**Comment by WhiteyCWB** [comment]
Confirming on windows 10. Infinite loading screen 
![image](https://user-images.githubusercontent.com/86805182/227681992-3d1d6ec7-30cc-464e-8ab3-2fbde600985b.jpg)

**Comment by 1nvaL** [comment]
Windows 10, Chia v1.7.1
![xchbug](https://user-images.githubusercontent.com/129078560/227961215-1102c4ec-c82b-47b4-a962-8769595ebef9.jpg)

**Comment by MumfMeisterT** [comment]
#14953

**Comment by maxfrank76** [comment]
I will add that the same problem exists in the mac os 13.3 intel, I also checked chia 1.8.0-b4, everything is the same as

**Comment by Amplificator** [comment]
Same for me.

New wallet and just synced up.

**Comment by hwfanatic** [comment]
Looks like it has been fixed in 1.8.0-rc1.

**Comment by maxfrank76** [comment]
tested on mac os 13.3.1, wallet only mode, on chia-1.8.0 rc1 the problem with displaying the NFT tab is solved

**Comment by hwfanatic** [comment]
Closing as completed (fixed).
