### ISSUE TITLE
[Bug] RPC:nft_get_info doesn't work on windows

### ISSUE THREAD

**Issue by nongyehezuoshe** [Chia-Network/chia-blockchain#14909]
### What happened?

RPC: [nft_get_info](https://docs.chia.net/nft-rpc/#nft_get_info) doesn't work on windows.
throw err:
``` bash
Invalid REQUEST JSON: Expecting value: line 1 column 1 (char 0)
```
And, it's works on linux (ubuntu).

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
Invalid REQUEST JSON: Expecting value: line 1 column 1 (char 0)
```

**Comment by MumfMeisterT** [comment]
On windows you need to make sure you escape your double & single quotes.

**Comment by nongyehezuoshe** [comment]
> On windows you need to make sure you escape your double & single quotes.

`chia rpc wallet nft_get_info '{\"coin_id\": \"nft1l3d9p5gxseyhcecgj8zrd9xyecd8xm96ckx20uekwqeckr7yq25qjdac4t\"}'` and `chia rpc wallet nft_get_info \'{\"coin_id\": \"nft1l3d9p5gxseyhcecgj8zrd9xyecd8xm96ckx20uekwqeckr7yq25qjdac4t\"}\'` both cant work.

**Comment by emlowe** [comment]
Using Command Prompt you must use double quotes on the outside:
`chia rpc wallet nft_get_info "{\"coin_id\": \"nft1l3d9p5gxseyhcecgj8zrd9xyecd8xm96ckx20uekwqeckr7yq25qjdac4t\"}"`
Using PowerShell 7.3 you can use single quotes on the outside and not escape the double quotes:
`.\chia rpc wallet nft_get_info '{"coin_id": "nft1l3d9p5gxseyhcecgj8zrd9xyecd8xm96ckx20uekwqeckr7yq25qjdac4t"}'`

In order version of PowerShell you need to do the same as the command prompt
