### ISSUE TITLE
[Bug]  ['chia_harvester']. 257

### ISSUE THREAD

**Issue by azaz111** [Chia-Network/chia-blockchain#14910]
### What happened?

harvester disconnects from node when it sees more than 10,000 plots, currently 22k on harvester, shutdown every 10 minutes

### Version

1,7,1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
daemon chia.daemon.server         : DEBUG    Received message: WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)
2023-03-26T14:37:10.524 daemon chia.daemon.server         : INFO     Unexpected message type. Closing websocket with ['chia_harvester']. 257
2023-03-26T14:37:10.628 harvester harvester               : INFO     Reconnecting to peer PeerInfo(_ip=IPv4Address('5.161.186.11'), _port=8447)
2023-03-26T14:37:10.634 harvester harvester_server        : DEBUG    Connecting: wss://5.161.186.11:8447/ws, Peer info: PeerInfo(_ip=IPv4Address('5.161.186.11')
```

**Comment by MumfMeisterT** [comment]
I would start by changing your plots_refresh interval setting in your config.yaml file. 
`plots_refresh_parameter:
batch_size: 300
batch_sleep_milliseconds: 1
interval_seconds: 120
retry_invalid_seconds: 1200`
I would push out the `interval_seconds` out to an hour if you are done plotting.

**Comment by azaz111** [comment]
this does not help, I want developers to write maximum values ​​for the harvester, and nodes, I have hundreds of petabytes, I can’t work with them because I don’t know how much load one server can withstand, 1 node does not work already with 10 pb, one harvester does not work from 1 pb,

**Comment by MumfMeisterT** [comment]
We cannot provide specific guidance around hardware required to run farms at this scale, we can say that we know of farmers who have a single harvester harvesting a petabyte of data, but we don't collect or manage details on how they are doing that. We advise going to the community to discuss further. thx.
