### ISSUE TITLE
[Bug] fc.compression branch - high >85% stale rate on compressed plots with lower end hardware

### ISSUE THREAD

**Issue by PhillWalker** [Chia-Network/chia-blockchain#14925]
### What happened?

Experiencing high >85% stale rate on compressed plots with lower end hardware, mainly 4 core 4 thread CPUs.

Tested with Alpha3 plots, C01-05

harvested with fc.compression branch, latest build as of 28/03/2023

reported in Keybase, but adding GitHub case to track.

Example CPUs tested (Synology devices)

Intel Celeron N3160 | Synology 716+II
Intel Celeron J3455 | Synology 918+
Intel Celeron J4125 | Synology 920+
AMD Ryzen R1600 | Synology 923+
Intel Atom D2700 | Synology RS2414rp+
INTEL Core i3-2100 | Synology RS3412xs
Intel Atom C3538 | Synology RS2818RP+

Screenshots of examples, 43 C05 plots, with pool difficulty 1
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/72089507/228292282-6385ccb1-2cb8-42a2-95ab-ecfdb53ba1cb.png">

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/72089507/228292489-4cc1f7a8-57e0-464c-91c5-462b866b4f6a.png">

### Version

fc.compression

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by sbrooke** [comment]
Same results on i5-3570k which is a 4c/4t CPU. All partials are 40s+

Ubuntu 22.10

Mostly C05 plotted on fresh Alpha3 code.

**Comment by fchirica** [comment]
The issue should now be fixed by this commit:

https://github.com/Chia-Network/chiapos/commit/965ea16be39ec0dbb177735256d0a79593cb90a1
