### ISSUE TITLE
[Bug] 1.7.1 Increased Plot Lookup Times

### ISSUE THREAD

**Issue by bobbyt2012** [Chia-Network/chia-blockchain#14936]
### What happened?

Switching to 1.7.1 has increased by plot lookup times from about .5 seconds on average to about 1.1 seconds on average. Min/Max lookups are also about 100% higher. Reverting to 1.6.1 alleviated the issue. Did something change to this process? Not necessarily a bug, but I would expect plot lookup times to decrease rather than increase with new versions. 

This coincides with no wins in 3x my TTW since the release of 1.7.0 - although of course that could be a random coincidence. 

### Version

1.7.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by santivu** [comment]
Same here. Around .02-.03 more in average, comparing  with 1.7.0.
Also the wallet is taking a bit more time to get synchronized.

**Comment by emlowe** [comment]
due to the substantial number of changes since this bug was reported, closing issue. Can be reopened as needed, but small increases in lookup times are not generally material to farming effectiveness, particularly with uncompressed plots
