### ISSUE TITLE
Harvester tries to open plot file with zero size

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#1494]
With 1.0 I find errors such as below where the plot file is actually of size 0.

22:42:22.405 harvester src.plotting.plot_tools : ERROR    Failed to open file /chia/plots/disk07/plot-k32-2021-02-08-16-20-72c7217502a09dd40e305555986809fd25e800f7e3fa60fe663115545427f370.plot. Invalid plot header magic Traceback (most recent call last):

Wondering why the logic doesn't report instead:
...We assume the file is being copied.     As for other partial files?

**Comment by mariano54** [comment]
This is because first, we open the file to get the K size (DiskProver). Then we check for expected file size. 
Perhaps we need better logging in chiapos to say that it may be a file of size 0. Anyways this is a won't fix on chia-blockchain.
