### ISSUE TITLE
WARNING  <member 'strerror' of 'OSError' objects>

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#1495]
With 1.0 this error message is a bit confusing, did it not print content of variables? I looked at lines before and after these entries, nothing significant and worth mentioning.

18:53:04.762 harvester src.plotting.plot_tools : WARNING  <member 'strerror' of 'OSError' objects>
18:53:07.770 harvester src.plotting.plot_tools : WARNING  <member 'strerror' of 'OSError' objects>
18:53:16.794 harvester src.plotting.plot_tools : WARNING  <member 'strerror' of 'OSError' objects>

**Comment by mariano54** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/1500
