### ISSUE TITLE
[Bug] the offer is not canceled

### ISSUE THREAD

**Issue by timudjinka** [Chia-Network/chia-blockchain#14960]
### What happened?

I can't cancel an offer I made earlier. Nothing happens, at all. I tried cancellation with a commission - a day has passed and nothing has changed.
![234234](https://user-images.githubusercontent.com/118344524/229277784-80ccf5a4-f415-49fd-85c1-8c06c886babd.JPG)

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by timudjinka** [comment]
https://www.spacescan.io/xch/nft/nft1ta84k0q24tnsm5lxa7lyw2fxzw5gycuhay2shaywtup2zmx00fmsc8phua

**Comment by MumfMeisterT** [comment]
Could you please provide us with DEBUG level logs? thx

**Comment by aaronscientiae** [comment]
I have this in 1.8.0rc1. I had offers outstanding when I moved the NFTs to another wallet. the offers don't seem to be cancellable now. Below the the debug log I get when I try a cancel with no fee.
