### ISSUE TITLE
Test for check hint length in notification manager

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#14976]
_Originally posted by @arvidn in https://github.com/Chia-Network/chia-blockchain/issues/14972#issuecomment-1494632167_
"looks reasonable. if we want to avoid re-introducing problems like this again in the future, we should probably have tests though"

**Comment by Quexington** [comment]
https://github.com/Chia-Network/chia-blockchain/blob/a8569e5e4bb4efe151dea055d8608db8fecc3b9b/tests/wallet/test_notifications.py#L56

I think there are tests now (if there weren't before)
