### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sdipietr** [Chia-Network/chia-blockchain#1499]
Am setting up my first plot on a Mac 14.0.3 with Samsung SSD T5 for the temporary files and My Passport 1TB WD for the permanent.

Getting this message in the log after Bucket 37

	Bucket 36 uniform sort. Ram: 4.440GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 37 uniform sort. Ram: 4.440GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
Only wrote 0 of 226984 bytes at offset 4294946164 to "/Volumes/TESLA/plot-k32-2021-03-25-16-52-ddb8a34f223b2f932418c7ea93d32b75055b17ab0369a7c925449d4257372b1b.plot.table1.tmp"with length 4294946164. Error 1. Retrying in five minutes.

**Comment by hoffmang9** [comment]
Error 1's are hardware errors. On a mac it points to some part of the storage hardware you are using being faulty - though it sometimes can be just a weird out of space response.

**Comment by sdipietr** [comment]
Cool thanks.  I might reformat the disk. It has some other junk on it. Appreciate the response.

**Comment by CocoaPriest** [comment]
For anyone on macOS, this is really the case. You just need to empty bin to suppress this error.
