### ISSUE TITLE
CLI `chia wallet make_offer` has two `-r` shortcut options

### ISSUE THREAD

**Issue by Ganbin** [Chia-Network/chia-blockchain#15004]
If we are using the shortcut `-r` for CLI command `chia wallet make_offer`, we get an error `Error: Missing option '-r' / '--request'`

We can workaround by using the full command `--request`.

https://github.com/Chia-Network/chia-blockchain/blob/5b3343b90e38c02c07d9a6387899c6d5e97f370e/chia/cmds/wallet.py#L423

**Comment by kimsk** [comment]
Same issue here, https://github.com/Chia-Network/chia-blockchain/issues/14874
