### ISSUE TITLE
Wallet Service never starts

### ISSUE THREAD

**Issue by lumberjak2007** [Chia-Network/chia-blockchain#15015]
Ok so I'm just getting back into the swing of things with Chai but i've run into an issue lately that can't seem to figure out, and it's that the Wallet Service never seems to start. I've tried rebooting a couple of times and still same thing the service just never start and i'm kinda just stuck in a loading state. anybody with any idea of what i can try please feel free to let me know cause i'm at a loss.

**Comment by jason-unleashed** [comment]
I have a similar issue since I updated it to 1.7.1.  After a reboot, chia starts from a script `chia start farmer -r` but the wallet doesn't start.  If I enter the command manually a second time the wallet does start.

**Comment by trepca** [comment]
Are you seeing any errors in logs?

**Comment by emlowe** [comment]
Closing due to lack of response
