### ISSUE TITLE
Unable to identify compressed plots

### ISSUE THREAD

**Issue by xiapi007** [Chia-Network/chia-blockchain#15025]
### What happened?

The compressed plot cannot be recognized. The client version is 1.7.1, and the system is ubuntu 22.04 , plot compression level c5. Is there a solution?

### Version

1.7.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by imhotep51** [comment]
For now, compressed plot farming is not available on the main branch. You need to checkout the fc.compression branch. The current release is 1.7.2.dev92

**Comment by xiapi007** [comment]
> For now, compressed plot farming is not available on the main branch. You need to checkout the fc.compression branch. The current release is 1.7.2.dev92
Can't find it 1.7.2.dev92 ， please send me a link, thank you

**Comment by imhotep51** [comment]
You can find all dev release [here](https://downloads.chia.net/dev/). But i will recommend leveraging git to do that for you:
git checkout fc.compression

**Comment by MumfMeisterT** [comment]
This feature has not been released yet.
