### ISSUE TITLE
[Bug] /push_tx wallet RPC only accepts hex representation of SpendBundle

### ISSUE THREAD

**Issue by freddiecoleman** [Chia-Network/chia-blockchain#15034]
### What happened?

- The full node RPC has a `/push_tx` endpoint which accepts a Spend Bundle in JSON form.
- The wallet RPC has a `/push_tx` endpoint which accepts a Spend Bundle serialized as hex.

Generating the serialized hex form of a Spend Bundle is problematic in languages other than Python where the Streamable serialization has not been implemented. JSON is a universally accepted format for transmitting this kind of data.

Changing the wallet RPC to only accept JSON would be a breaking change. Alternatively it is probably possible for the endpoint to accept either format.

### Version

1.7.1

### What platform are you using?

Linux

### What ui mode are you using?

RPC

**Comment by MumfMeisterT** [comment]
PR's welcome!
