### ISSUE TITLE
 i don't have any trade, lost 7 coins!!![Bug] 

### ISSUE THREAD

**Issue by redboathou** [Chia-Network/chia-blockchain#15033]
### What happened?

 i don't have any trade, lost 7 coins!!! around 1 month ago.
i updated the newest version, still no find my coins!

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Unfortunately, there have been some bad download links for the Chia database that have been stealing peoples coins, so this is a possibility if you used a 3rd party to download the db.  
We now have a feature in the GUI where you can resync your wallet `Settings>Advanced>Resync Wallet` to see if they show after that.

**Comment by emlowe** [comment]
Closing issue
