### ISSUE TITLE
Windows synced but do not have any xch reward?

### ISSUE THREAD

**Issue by Sylor-huang** [Chia-Network/chia-blockchain#1503]
Hi 

I have some confusions about window system:

I had synced the chia mainnet， but I  cannot get any xch, I don't is it right or I had missed some setting ?

![image](https://user-images.githubusercontent.com/26167245/112478579-1ff6e700-8daf-11eb-9fc5-85a701193ade.png)

![image](https://user-images.githubusercontent.com/26167245/112478532-13728e80-8daf-11eb-87d1-9bf9c56f2711.png)

Thanks very much~

**Comment by dorkmo** [comment]
What is the total size of your plots? This is the main factor on time.

**Comment by Sylor-huang** [comment]
> What is the total size of your plots? This is the main factor on time.

Thanks for you reply.

My  hard disk total size is 500G. 

- Hard DIsk

![image](https://user-images.githubusercontent.com/26167245/112500626-8423a600-8dc3-11eb-8a46-998c98a32607.png)

- Plots
![image](https://user-images.githubusercontent.com/26167245/112500759-9f8eb100-8dc3-11eb-9f3e-8ace2d36cb1e.png)
- Farm

![image](https://user-images.githubusercontent.com/26167245/112501258-0ca24680-8dc4-11eb-9524-2f23cf6dd358.png)

Do I configure it correctly? Thanks~

**Comment by hoffmang9** [comment]
You have to create plots and farm them to get farming rewards. Start here https://chia.net/2021/02/22/plotting-basics.html
