### ISSUE TITLE
not syncing

### ISSUE THREAD

**Issue by pulverpeter** [Chia-Network/chia-blockchain#1504]
![image](https://user-images.githubusercontent.com/81368230/112478653-801c6780-8d74-11eb-99f1-6315e236c5ba.png)

**Comment by dorkmo** [comment]
how many peers are you connected to?

**Comment by pulverpeter** [comment]
![image](https://user-images.githubusercontent.com/81368230/112480604-7e53a380-8d76-11eb-97d5-f4299a11030a.png)

**Comment by pulverpeter** [comment]
I do all. means new start PC, uninstall Chia, new release installing, nothing help

**Comment by hoffmang9** [comment]
It may take up to 30 minutes to begin syncing

**Comment by pulverpeter** [comment]
ok, but it stay over night , now its startet again and stay still, see picture
yesterda it stopped and stay still by 9624

![image](https://user-images.githubusercontent.com/81368230/112488189-9da1ff00-8d7d-11eb-8966-4d4155199c0f.png)

**Comment by hoffmang9** [comment]
Reopen if it's not synced in a couple hours.

**Comment by dorkmo** [comment]
you might delete some of the nodes with 0/0 Mb updown

**Comment by pulverpeter** [comment]
i delete this nodes with 0/0 Mb updown, but still same not finish syncing, see picture
![image](https://user-images.githubusercontent.com/81368230/112523928-91c73480-8d9f-11eb-85b5-bdde7f0eadfc.png)
![image](https://user-images.githubusercontent.com/81368230/112524188-d3f07600-8d9f-11eb-9d03-ef695061e7dc.png)

**Comment by pulverpeter** [comment]
this one is for hours, still 922 and not counting
![image](https://user-images.githubusercontent.com/81368230/112524368-07cb9b80-8da0-11eb-8048-5779a3ed5a9a.png)

**Comment by pulverpeter** [comment]
sorry 992

**Comment by pulverpeter** [comment]
still not syncing, after1 day, see picture

![image](https://user-images.githubusercontent.com/81368230/112596410-10f25200-8e0c-11eb-9fda-5acce76fc6df.png)
