### ISSUE TITLE
Error "chia cannot be closed

### ISSUE THREAD

**Issue by punx4life85** [Chia-Network/chia-blockchain#15043]
### What happened?

Trying to update to 1.7.1 on win 11.. getting error "chia cannot be closed. Please close it manually and click retry to continue." I have tried restarting, uninstalled everything to try a fresh install, cleared app data folders. What am I missing?
![dbec4a7f-bad8-41dc-9168-1b5602772904](https://user-images.githubusercontent.com/130851625/232234440-a2ffafd7-17f9-401c-813c-0f1f8e78f830.jpg)

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
When you say you restarted, did you restart the install or your machine?

**Comment by emlowe** [comment]
Closing due to lack of response
