### ISSUE TITLE
[Bug] "'Bool' Object has no attribute 'get'" when using misconfigured `reuse_public_key_for_change: True`

### ISSUE THREAD

**Issue by j-kest** [Chia-Network/chia-blockchain#15063]
### What happened?

when the chia client is in sync every wallet shows a red error for the amounts with this message when you hover over it
 "'Bool' Object has no attribute 'get'"
reinstalling the client did not help.
Rebooting did not help.
i removed the last thing i changed in the config file a couple of weeks back.
removing this "  reuse_public_key_for_change: true " fixed it. 
strange thing is, it has been in my config file for a while now and never had this error before.

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
If you put back `euse_public_key_for_change: true` does it happen again? Could you also provide screenshot pls? thx

**Comment by j-kest** [comment]
<img width="1559" alt="Chia Blockchain" src="https://user-images.githubusercontent.com/84345664/233468719-4f950aa9-724f-4573-852a-6d785443d7d3.png">

**Comment by j-kest** [comment]
yes when i add it back in it comes back

**Comment by MumfMeisterT** [comment]
Thank you, @j-kest. Could you please provide debug level logs for us?

**Comment by j-kest** [comment]
sorry that i haven't reacted yet. i will do this tomorrow and get back to you.

**Comment by j-kest** [comment]
2023-05-01T13:43:19.741 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 826, in get_wallet_balance
  File "chia\wallet\wallet.py", line 87, in get_max_send_amount
  File "chia\wallet\wallet.py", line 528, in generate_signed_transaction
  File "chia\wallet\wallet.py", line 347, in _generate_unsigned_transaction
AttributeError: 'bool' object has no attribute 'get'

**Comment by emlowe** [comment]
Oh, this config entry is confusing, but `reuse_public_key_for_change` is not a boolean, that is you cannot put 
`reuse_public_key_for_change: True` in the config.yaml.

Rather you have to list *which* wallet fingerprint to use like this:
```
  reuse_public_key_for_change:
    #Add your wallet fingerprint here, this is an example.
    "2999502625": False
```

if you had multiple wallets, you would list them separately:

```
  reuse_public_key_for_change:
    #Add your wallet fingerprint here, this is an example.
    "2999502625": False
    "4070063073": True
    "2517657857" : True
```
    

```

**Comment by emlowe** [comment]
Leaving issue open as I anticipate this being a common mistake
