### ISSUE TITLE
[Bug] DID disappeared / stopped working

### ISSUE THREAD

**Issue by codephunk** [Chia-Network/chia-blockchain#15079]
### What happened?

Since my issue has been closed without being resolved and I'm not getting responses anymore, I have to open a new Issue.

Detailed description of the bug/issue can be found here: https://github.com/Chia-Network/chia-blockchain/issues/13691

### Version

1.6.0-1.72

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
@codephunk I'm sorry that this was not resolved correctly. I am reopening the previous ticket to direct further assistance and will close this as a duplicate. 

@ytx1991 This member is still experiencing the missing DID issue, can you please reach out to them as soon as possible?
