### ISSUE TITLE
[BUG] Mac Catalina 10.15.7 - Chia 1.01 "connecting to wallet"

### ISSUE THREAD

**Issue by russ-tolman** [Chia-Network/chia-blockchain#1507]
When Chia 1.01 opens, it never gets past the "connecting to wallet" screen. I've restarted, rebooted, reinstalled several times and still "connecting to wallet". I am definitely online so there is nothing I am doing to cause this.

 Mac Catalina 10.15.7

**Comment by mescab** [comment]
there is nothing you can do but: 1) backup your .chia directory; 2) remove .chia; 3) run Chia. Start over again. After hours, everything will be fine.

It's a bug without doubt, but I guess not in priority.

**Comment by russ-tolman** [comment]
I've searched for .chia in Finder but the searches come up empty.
Where do I find it? I also physically looked in my Users directory and see nothing there.


New single: "life"

| See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO)
Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com

 |

 

    On Thursday, March 25, 2021, 04:44:58 PM PDT, mescab ***@***.***> wrote:  
 
 


there is nothing you can do but: 1) backup your .chia directory; 2) remove .chia; 3) run Chia. Start over again. After hours, everything will be fine.

It's a bug without doubt, but I guess not in priority.

**Comment by russ-tolman** [comment]
And there's no .chia in the Chia Blockchain folder.


New single: "life"

| See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO)
Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com

 |

 

    On Thursday, March 25, 2021, 04:44:58 PM PDT, mescab ***@***.***> wrote:  
 
 


there is nothing you can do but: 1) backup your .chia directory; 2) remove .chia; 3) run Chia. Start over again. After hours, everything will be fine.

It's a bug without doubt, but I guess not in priority.

**Comment by hoffmang9** [comment]
It is in your home directory - not in the chia-blockchain directory.

**Comment by jflowers1974** [comment]
I'm glad I read this, after removing said folder/re-install... I seem to be coming back "from the dead"...

**Comment by russ-tolman** [comment]
Hi Jeff, where do you find that folder on your Mac. It doesn't appear on mine.


New single: "life"

| See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO)
Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com

 |

 

    On Thursday, March 25, 2021, 09:58:57 PM PDT, Jeff Flowers ***@***.***> wrote:  
 
 


I'm glad I read this, after removing said folder/re-install... I seem to be coming back "from the dead"...

**Comment by mescab** [comment]
> Hi Jeff, where do you find that folder on your Mac. It doesn't appear on mine. New single: "life" | See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO) Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com | On Thursday, March 25, 2021, 09:58:57 PM PDT, Jeff Flowers ***@***.***> wrote: I'm glad I read this, after removing said folder/re-install... I seem to be coming back "from the dead"... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Usually, if your name is russ, then your mac home dir will be /Users/russ. Open up a terminal, then run:
`cd /Users/russ`
`ls -al`
`cp -r .chia .chia-bak`
`rm -rf .chia`

**Comment by robschwitzer** [comment]
Seeing same issue as OP. Deleted ~/.chia but no difference. Reinstalled the client, still hanging. 

Interesting to note, before this happened, my computer crashed mid-plot with apple logs pointing at chia thread. Immediately after restart, "connecting to wallet" issue came up

**Comment by robschwitzer** [comment]
Dev tools console says:
```
Uncaught Error: socket hang up
    at connResetException (internal/errors.js:610)
    at TLSSocket.socketOnEnd (_http_client.js:453)
    at TLSSocket.emit (events.js:327)
    at endReadableNT (_stream_readable.js:1220)
    at processTicksAndRejections (internal/process/task_queues.js:84)

**Comment by russ-tolman** [comment]
Thanks!



http://www.russtolmanmusic.comhttps://www.facebook.com/russtolmanhttps://www.facebook.com/russtolmanbandTwitter: @RussTolmanInstagram: Truewesterner

On Friday, March 26, 2021, 1:01 AM, mescab ***@***.***> wrote:





Hi Jeff, where do you find that folder on your Mac. It doesn't appear on mine. New single: "life" | See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO) Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com | On Thursday, March 25, 2021, 09:58:57 PM PDT, Jeff Flowers @.***> wrote: I'm glad I read this, after removing said folder/re-install... I seem to be coming back "from the dead"... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Usually, if your name is russ, then your mac home dir will be /Users/russ. Open up a terminal, then run:
cd /Users/russ
ls -al
cp -r .chia .chia-bak
rm -rf .chia

**Comment by pythonclerk** [comment]
another way to show the hidden files on mac is to use Shift+command+. (period) this will show all files and folders. had this same issue and deleted the directory and so far seems to be working fine.

**Comment by russ-tolman** [comment]
Thanks. Had success with deleting .chia.
Just downloaded 1.0.3 and it works fine without muss or fuss.


New single: "life"

| See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO)
Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com

 |

 

    On Wednesday, March 31, 2021, 11:03:08 AM PDT, Gene Hoffman ***@***.***> wrote:  
 
 


Here is an experimental .dmg to try that may fix many of the MacOS GUI startup issues - https://download-chia-net.s3-us-west-2.amazonaws.com/tests/Chia-1.0.4-rc1.dmg

**Comment by russ-tolman** [comment]
After successfully ridding myself of the Mac start-up problem with version 1.0.3 (and removing the .chia file) and smooth sailing for about a week, the "connecting to wallet" start-up problem returned.
I downloaded and tried the 1.0.4-rc1 below and still have the same start-up problem but this time there is no .chia file to delete...
    On Wednesday, March 31, 2021, 11:03:08 AM PDT, Gene Hoffman ***@***.***> wrote:  
 
 


Here is an experimental .dmg to try that may fix many of the MacOS GUI startup issues - https://download-chia-net.s3-us-west-2.amazonaws.com/tests/Chia-1.0.4-rc1.dmg

**Comment by hoffmang9** [comment]
I'm confident that there is a .chia file still. 

Delete the following:
```
~/.chia/mainnet/db/peer_table_node.sqlite
~/.chia/mainnet/wallet/db/*
```

and restart. If that doesn't work you will then need to try deleting `~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite`

**Comment by russ-tolman** [comment]
Thanks



http://www.russtolmanmusic.comhttps://www.facebook.com/russtolmanhttps://www.facebook.com/russtolmanbandTwitter: @RussTolmanInstagram: Truewesterner

On Sunday, April 4, 2021, 12:48 PM, Gene Hoffman ***@***.***> wrote:




I'm confident that there is a .chia file still.

Delete the following:
~/.chia/mainnet/db/peer_table_node.sqlite
~/.chia/mainnet/wallet/db/*

and restart. If that doesn't work you will then need to try deleting ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite

**Comment by russ-tolman** [comment]
Thanks. Deleting the first two worked. And I used CLI. I feel like such a stud!


New single: "life"

| See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO)
Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com

 |

 

    On Sunday, April 4, 2021, 12:48:35 PM PDT, Gene Hoffman ***@***.***> wrote:  
 
 


I'm confident that there is a .chia file still.

Delete the following:
~/.chia/mainnet/db/peer_table_node.sqlite
~/.chia/mainnet/wallet/db/*

and restart. If that doesn't work you will then need to try deleting ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
