### ISSUE TITLE
All coins are gone!Please help

### ISSUE THREAD

**Issue by Giga29** [Chia-Network/chia-blockchain#15096]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/15095

<div type='discussions-op-text'>

<sup>Originally posted by **Giga29** April 21, 2023</sup>
Hello. Please help me figure out where my coins went. I installed a new windows operating system on a new computer, I also installed drivers from the official msi website and from your chia wallet website. That is, the system is clean, without viruses. I transferred some coins from another wallet, they came, the next day I sent more coins, and decided to go in to check if the second part of the coins had arrived. As a result, all the coins were gone. Please help me figure out what happened and where are my coins!?</div>

**Comment by cimrhanzel** [comment]
The wallet will show 0 until the database is fully synced

**Comment by Giga29** [comment]
> Кошелек будет показывать 0, пока база данных не будет полностью синхронизирована.

Please tell me where can I see the status of synchronization?

**Comment by aaronscientiae** [comment]
In the GUI there is a wallet button at upper left, yellow circle while syncing, green when synced.

**Comment by MumfMeisterT** [comment]
@Giga29 After syncing, is your wallet now showing correctly?

**Comment by Giga29** [comment]
Yes, thank you very much for your help
