### ISSUE TITLE
[BUG] Can't load full node

### ISSUE THREAD

**Issue by CocoaPriest** [Chia-Network/chia-blockchain#1512]
**Describe the bug**
After force-quitting Chia 1.0.1, full node tab shows loading spinners and it seems it does nothing for hours.

**Screenshots**
<img width="1071" alt="Screenshot 2021-03-26 at 01 18 25" src="https://user-images.githubusercontent.com/50823/112559538-7bd26780-8dd1-11eb-8ccf-d6ba7b07769d.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina
- OS Version/Flavor: 10.15.7
- CPU: 4 GHz Quad-Core Intel Core i7

**Comment by soundfx42** [comment]
I'm going to suggest the obvious: Have you tried a computer restart. I had this problem (on a Win10 machine) and I think it was due to a zombie chia process still running in the background. I did a system restart and the problem was solved.

**Comment by CocoaPriest** [comment]
Yeah, forgot to mention that. I did a restart, also I deleted my `blockchain_wallet_v1_mainnet_xxx.sqlite` file with no effect. The only thing what helps is to remove entire `~/.chia` directory.

**Comment by mariano54** [comment]
This was probably a configuration issue with the genesis challenge not being in the config, I will close this as there are duplicate issues.
