### ISSUE TITLE
[Bug] dictionary changed size during iteration 

### ISSUE THREAD

**Issue by bramv-chia** [Chia-Network/chia-blockchain#15142]
### What happened?

when switching between wallets 
![wallet_change_error_GUI](https://user-images.githubusercontent.com/116583441/234676534-8ff77ef9-f1ac-4301-b134-2b52bcc1a437.png)
occured.
after clicking [OK] and clicking on the desired wallet, it will load without issue

### Version

1.8.0rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Closing since @xdustinface has made a couple of fixes in this area including https://github.com/Chia-Network/chia-blockchain/pull/15149
