### ISSUE TITLE
still not syncing

### ISSUE THREAD

**Issue by pulverpeter** [Chia-Network/chia-blockchain#1514]
see issue#1504

it is after 1 day connection
still stay at 992, no counting
i install newest release, new start PC, unstall Chia, nothing help
![image](https://user-images.githubusercontent.com/81368230/112596729-7ba38d80-8e0c-11eb-8488-6da12d6d103f.png)

**Comment by mariano54** [comment]
Did you wait for it to start syncing? It takes a while sometimes

**Comment by pulverpeter** [comment]
yes wait 3 days

**Comment by pulverpeter** [comment]
i want do it complety new, but after delete all chia folders, chia software, new install chia my key is already in, where can i delete this to start brand new with type in my key

**Comment by lapestand** [comment]
> Did you wait for it to start syncing? It takes a while sometimes

How long does it take? I waited for a day but it didn't start syncing. Then I upgraded software from 1.0.1 to 1.0.2. I've been waiting for hours to start syncing now. What should I do?
![image](https://user-images.githubusercontent.com/30733590/113080515-b8da9780-91df-11eb-8038-105779cf899c.png)

**Comment by dorkmo** [comment]
looks like youre not getting your first peer node. Might check your firewall settings.

**Comment by lapestand** [comment]
![image](https://user-images.githubusercontent.com/30733590/113095456-21d00880-91fc-11eb-8ceb-9e59e3ef53d8.png)
![image](https://user-images.githubusercontent.com/30733590/113095505-37453280-91fc-11eb-96d0-3a47f3089e3e.png)

Firewall settings look correct
@dorkmo

**Comment by lvpcguru** [comment]
How are you looking now? A lot of slow sync issues seem to have gone away with 1.1.6
