### ISSUE TITLE
[Bug] Networking issues

### ISSUE THREAD

**Issue by maigaoxiang111** [Chia-Network/chia-blockchain#15161]
### What happened?

Código de error del registro

No se puede acceder a la ubicación de la red. La fe en la solución de problemas en la red？？

Se acabó el tiempo de espera de la lámpara de señal.？？
![E4C1014E-1594-481A-82A1-5B8C39DCE635](https://user-images.githubusercontent.com/110707933/235303054-7e807d84-8512-4b0d-bef7-db29a14c96d7.jpeg)
![7312F3FC-F2AE-4E6E-82FE-2C2C1410B77A](https://user-images.githubusercontent.com/110707933/235303057-69aa8bd9-a268-4be7-8a54-80b394cbc25d.jpeg)

### Version

1.7.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
5c443838bed40615190625293€6144070f6da44825. fork f9df41b2dd1e14228fe738eec0e908c2367515261078. tot ow: False, deficit: 13, difficulty: 2144, sub slot iters: 14784 if list size: No tx 5 wallet chia.wallet.wallet state manager: INFO set syl
3 wallet chia.wallet.wallet blockchain: INFO
Peak set tc
3 full node full node server
INFO
Cannot connec
a:b6e4:d4bb:7dea:8444 ssl: <ssI.SSEContext object at
[能访问网络位置。有关网络排除故障的信恩，
•请参阅 Wind
full node chia.full node.full node: INFO
Finished sig
fee33832dd75572f209463928d6b4c7064810ec94784 RC
306c4bcabgfaeb01fd03e3a85eec1fa2010f9463ce7a
I harvester chia.harvester.harvester: INFO
2 plots were e
ound 0 proofs. Time: 0.69262 s. Total 2178 plots. full node chia full node.full node: INFO
Finished sign
eb7287eb8dcf96879cc83aaf9f1406cff70f29af4e5b3e3 RC:
147bfcasb01a15077096d3694539ac23efea93a5fd64
harvester chia.harvester.harvester: INFO
7 plots were eli
und 0 proofs. Time: 0.32090 s. Total. 2178 plots full node full node server
:INFO
Cannot connect t
=sslSSLContext object at 0x0o00015BEO7ODD40-[信号灯超
full node chia,full node. full node:
```

**Comment by aaronscientiae** [comment]
This isn't an error, just INFO, it just couldn't connect to a particular ipv6 node, do you show other ipv4 connections to other nodes? what is not working?

**Comment by emlowe** [comment]
Closing issue; occasional networking issues are expected in a p2p network. Your node will connect to other nodes as needed
