### ISSUE TITLE
[Bug] WalletConnect pairing issues in versions later than 1.7.1

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#15195]
### What happened?

Updates in recent versions of the chia client break functionality of walletConnect.

In the linked doc, I have reviewed a few versions of the chia client and indicated the results.
(doc is private, access will be granted to Chia employees that request)
https://docs.google.com/document/d/1sc5LAg6ybXwr5G5JIivJVk8nRf7aej_uubPT_ZBpv38/edit?usp=sharing

TLDR - potentially the inclusion of a description field in the walletConnect commands is a breaking change and documenting such will aid dApp devs in ensuring their dApps remain functional with different versions of the chia client.

### Version

1.7.1-1.8.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
please refer to linked doc (doc is private, access will be granted to Chia employees that request)
```

**Comment by BrandtH22** [comment]
Just confirmed three reasons wc pairing will fail:
 - Chia Client versions newer than 1.7.1 use a different walletConnect context which prevents pairing on the dApp side (chia reference dApp will need to be updated with new context) - this is covered in the linked doc
 - If additional methods are included in the dApp Chia Default Methods, this will cause a pairing failure (current dApp test includes "CHIA_GET_CAT_WALLET_INFO" which does not have a corresponding method in 1.7.1, commenting out the method in the dApp restores functionality)
 - Client side firewalls/ad blockers can prevent the necessary dApp popups

**Comment by paninaro** [comment]
The release/1.8.1 branch should have fixes for the actionable items that have been discovered. Marking this as closed, but we can reopen or file new issues if there are remaining bugs.
