### ISSUE TITLE
MadMax has error in first line 1.8.

### ISSUE THREAD

**Issue by advlive** [Chia-Network/chia-blockchain#15201]
### What happened?

MadMax Plotting has problem 
Error in first line
was very nice on 1.7.1 

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
I cannot understand what this means - please provide more details. What are you trying to do?. Can you show a screen shot perhaps?

**Comment by darkpretzel** [comment]
I am getting the same error.

Installed 1.8.0 today. The madMAx plotter throws errors when initiating a plot if temp directory 2 is left blank:

```
usage: chia plotters madmax [-h] [-k SIZE] [-n COUNT] [-r THREADS]
                            [-u BUCKETS] [-v BUCKETS3] -t TMPDIR [-2 TMPDIR2]
                            [-w] [-p POOL_KEY] [-f FARMERKEY] [-c CONTRACT]
                            [-G] [-K RMULTI2] -d FINALDIR
chia plotters madmax: error: argument -2/--tmp_dir2: expected one argument
```

To successfully run, I had to manually select temp directory 2 when configuring the plot -- previously I could leave it blank and it would default to same as tempdir1.

**Comment by advlive** [comment]
> usage: chia plotters madmax [-h] [-k SIZE] [-n COUNT] [-r THREADS]
>                             [-u BUCKETS] [-v BUCKETS3] -t TMPDIR [-2 TMPDIR2]
>                             [-w] [-p POOL_KEY] [-f FARMERKEY] [-c CONTRACT]
>                             [-G] [-K RMULTI2] -d FINALDIR
> chia plotters madmax: error: argument -2/--tmp_dir2: expected one argument

**Comment by NewSunSEO** [comment]
> I am getting the same error.
> 
> Installed 1.8.0 today. The madMAx plotter throws errors when initiating a plot if temp directory 2 is left blank:
> 
> ```
> usage: chia plotters madmax [-h] [-k SIZE] [-n COUNT] [-r THREADS]
>                             [-u BUCKETS] [-v BUCKETS3] -t TMPDIR [-2 TMPDIR2]
>                             [-w] [-p POOL_KEY] [-f FARMERKEY] [-c CONTRACT]
>                             [-G] [-K RMULTI2] -d FINALDIR
> chia plotters madmax: error: argument -2/--tmp_dir2: expected one argument
> ```
> 
> To successfully run, I had to manually select temp directory 2 when configuring the plot -- previously I could leave it blank and it would default to same as tempdir1.

Yes, I was having the same issue & duplicated the -t directory to the 2nd -t directory & now the 1.8.0 software is working for me again.  Must be a bug...
