### ISSUE TITLE
[BUG] RuntimeError: Bad Allocation

### ISSUE THREAD

**Issue by glotrix** [Chia-Network/chia-blockchain#1521]
**Describe the bug**
During a 5 parallel plot on one 2TB nvme, one of them errored with "RuntimeError: Bad Allocation"

**To Reproduce**

1. Open powershell and run the following command: Start-Sleep 1200; .\chia.exe plots create -k 32 -b 3500 -e -u 128 -r 2 -t J:\chiatemp -d G:\chiaplot -n 10
2. Open four more powershells and increment start-sleep by 1200 for each.
3. Wait

**Expected behavior**
All the plots should finish fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/81428406/112648418-e5796280-8e1f-11eb-9a6d-4fe13d755b6a.png)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10 20H2
- CPU: 5900X, 32GB RAM

**Additional context**
In the support channel on keybase, someone though it was a memory problem so I turned off XMP and the issue still popped up. I don't think its a memory issue because I have plotters going on another NVMe in the same system and they are working correctly. The other nvme is a 1TB so only 2 plotters there.

I plan to update mobo drivers to see if that is the case.

**Comment by hoffmang9** [comment]
This is a hardware side issue. Usually it is a RAM problem.

**Comment by glotrix** [comment]
Checked the memory with memtest86 overnight and no issues were discovered. A potential solution has been found on my end after further investigation. 

Do not have the Windows Page file on a drive that you are using for plotting. If you are approaching the RAM limit of your system with plotting, the page file must be used by the OS. In my case, the page file was on the same drive as two plots in parallel, this simulated the hardware memory problems.
