### ISSUE TITLE
[Bug] Wallet not syncing

### ISSUE THREAD

**Issue by lukar777** [Chia-Network/chia-blockchain#15213]
### What happened?

Wallet not syncing after upgrade from 1.6.1 to 1.8.0

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
023-05-05T10:48:16.689 wallet chia.wallet.wallet_node    : WARNING  querying DNS introducer failed: The resolution lifetime expired after 32.004 seconds: Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 2.000 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 0.869 seconds
2023-05-05T10:53:22.742 wallet chia.wallet.wallet_node    : WARNING  querying DNS introducer failed: The resolution lifetime expired after 32.003 seconds: Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 2.000 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 2.000 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 2.000 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 0.872 seconds
2023-05-05T10:55:50.931 wallet chia.wallet.wallet_node    : WARNING  querying DNS introducer failed: The resolution lifetime expired after 32.002 seconds: Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 2.000 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 1.999 seconds; Server 127.0.0.53 UDP port 53 answered The DNS operation timed out after 0.866 seconds
```

**Comment by MumfMeisterT** [comment]
What do you have in your config.yaml for `dns_servers`?
Can you try running this command `nslookup dns-introducer.chia.net` and then pasting the output here for us?

**Comment by Cerote6669** [comment]
hello, i got the same issue, 4 days syncing crypto doge

node gui says "Not Synced" in top left corner
3,022,284 height

please advise, any help appreciated


C:\Users\User> nslookup dns-introducer.chia.net
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  192.168.1.1

followed instruction per cmd prompt above

Non-authoritative answer:
Name:    dns-introducer.chia.net
Addresses:  2001:fb1:cf:9963:e50e:3616:355:423
          2001:b011:b002:bc21:628f:429b:5941:2032
          2a01:e11:1004:80c0:d46c:6724:489e:36b5
          2806:103e:29:2d1a:489:edfd:972f:6a0d
          2408:823c:ac10:2da4:28d9:c62:79a4:7688
          2a01:e0a:2a1:b390:1c07:9fbc:5408:e681
          2603:3006:7:6700:b96f:ba0e:e8a0:2b90
          2607:f358:25:6001::f247
          2603:3015:10d9:6000:b994:d295:e9ba:de3a
          2803:9800:90b0:86a6:338f:ba3:479c:c2b4
          2403:6200:89a7:24f4:9ed2:29f9:654d:9c8a
          2001:448a:1082:ba06:3d9a:8cdf:3391:786d
          2001:569:54d7:6000:1e40:3d8c:151b:1b20
          2404:7a84:22e0:3100:f152:d0eb:3362:a0bb
          2408:821a:2f12:ab90:5d65:d48b:b63d:be10
          2800:40:39:49c:9ab1:56ef:7101:fdf2
          240e:385:860:b300:8888:f9aa:f8cf:229a
          240e:345:3b1d:2610:d4fe:26da:be70:7ad8
          2409:8a20:5c43:5e0:b5a7:1aab:6b39:e1e6
          2a01:e0a:838:df0:8848:4ab5:d1c4:da9b
          2603:300a:211a:a600:f4ca:81b0:86c7:b136
          2001:fb1:ba:7ce8:6514:27ff:5f93:c7dc
          240e:379:57bd:7700:1059:cec4:6504:211e
          2601:645:8000:d372:d782:2bb5:8660:31b8
          2a01:e0a:217:aef0:fbc1:a409:9e4a:2008
          2a06:5b05:9000:4e00:717a:6a72:8ee:99ec
          2800:810:478:1d36:69be:245e:6484:45b8
          2001:b011:8009:137c:a8ac:926a:33a7:45de
          2408:8220:8002:df0b:59bc:12e8:85a7:a4a
          2a01:e0a:502:b720:baca:3aff:fe65:f100
          2603:8000:4502:6a34:7c30:b3d1:ab7d:cb24
          2a01:4ff:f0:dd61::1
          90.23.238.148
          192.18.137.159
          76.123.28.218
          90.188.89.164
          178.219.84.181
          95.55.189.50
          73.132.43.107
          94.220.155.122
          24.128.126.250
          175.182.134.87
          94.62.214.72
          103.136.251.207
          73.218.48.127
          71.56.119.167
          87.13.8.81
          79.108.143.151
          67.215.232.2
          83.169.248.65
          82.64.64.152
          94.240.188.46
          135.134.209.48
          160.218.98.164
          170.253.15.242
          47.38.217.73
          85.198.141.135
          109.167.140.137
          46.216.40.140
          98.252.170.225
          109.228.111.118
          94.182.192.156
          96.44.175.162
          46.187.94.211


C:\Users\User>

**Comment by lukar777** [comment]
for dns_servers in config yaml
- dns-introducer.chia.net
  - chia.ctrlaltdel.ch
  - seeder.dexie.space
  - chia-seeder.h9.com
  - chia.hoffmang.com
  - seeder.xchpool.org

**Comment by lukar777** [comment]
nslookup dns-introducer.chia.net showing this

 Truncated, retrying in TCP mode.
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   dns-introducer.chia.net
Address: 27.33.47.44
Name:   dns-introducer.chia.net
Address: 88.130.30.252
Name:   dns-introducer.chia.net
Address: 77.116.143.253
Name:   dns-introducer.chia.net
Address: 77.252.21.66
Name:   dns-introducer.chia.net
Address: 23.233.86.112
Name:   dns-introducer.chia.net
Address: 85.94.8.117
Name:   dns-introducer.chia.net
Address: 87.171.247.53
Name:   dns-introducer.chia.net
Address: 188.6.28.149
Name:   dns-introducer.chia.net
Address: 173.75.24.158
Name:   dns-introducer.chia.net
Address: 78.58.6.47
Name:   dns-introducer.chia.net
Address: 118.209.254.163
Name:   dns-introducer.chia.net
Address: 101.51.201.216
Name:   dns-introducer.chia.net
Address: 38.34.87.29
Name:   dns-introducer.chia.net
Address: 109.126.232.18
Name:   dns-introducer.chia.net
Address: 46.161.168.211
Name:   dns-introducer.chia.net
Address: 207.191.208.171
Name:   dns-introducer.chia.net
Address: 212.20.41.134
Name:   dns-introducer.chia.net
Address: 47.155.60.53
Name:   dns-introducer.chia.net
Address: 135.26.83.180
Name:   dns-introducer.chia.net
Address: 68.118.145.70
Name:   dns-introducer.chia.net
Address: 190.55.173.136
Name:   dns-introducer.chia.net
Address: 95.49.183.64
Name:   dns-introducer.chia.net
Address: 83.167.13.220
Name:   dns-introducer.chia.net
Address: 85.243.237.114
Name:   dns-introducer.chia.net
Address: 88.109.187.22
Name:   dns-introducer.chia.net
Address: 64.147.202.183
Name:   dns-introducer.chia.net
Address: 73.204.132.32
Name:   dns-introducer.chia.net
Address: 46.153.51.62
Name:   dns-introducer.chia.net
Address: 202.186.40.161
Name:   dns-introducer.chia.net
Address: 93.8.73.128
Name:   dns-introducer.chia.net
Address: 84.40.209.156
Name:   dns-introducer.chia.net
Address: 85.94.8.166
Name:   dns-introducer.chia.net
Address: 2803:9800:9028:c1da:8c85:1ee0:4530:29c7
Name:   dns-introducer.chia.net
Address: 2803:9800:b035:7f14:2426:acbf:51ab:a856
Name:   dns-introducer.chia.net
Address: 2001:fb1:ba:7ce8:6514:27ff:5f93:c7dc
Name:   dns-introducer.chia.net
Address: 2a06:4005:608b:0:5dd1:eb28:65f7:2eff
Name:   dns-introducer.chia.net
Address: 2a00:ca8:a15:b1d0:792c:759d:8b18:21e2
Name:   dns-introducer.chia.net
Address: 2408:822a:4412:6fd0:a63b:85a5:3c5:fdc6
Name:   dns-introducer.chia.net
Address: 2803:9800:9887:ae99:7da9:80d4:44b9:c9b3
Name:   dns-introducer.chia.net
Address: 2406:da14:93e:a803:eab9:572:2eab:baad
Name:   dns-introducer.chia.net
Address: 2800:af0:1408:cfa:c085:11a2:946b:4274
Name:   dns-introducer.chia.net
Address: 2404:7a84:22e0:3100:51bb:9128:88df:658d
Name:   dns-introducer.chia.net
Address: 2a01:e0a:b31:bb80:871c:7d0d:d2e3:cd46
Name:   dns-introducer.chia.net
Address: 2600:8805:ab04:2600:cc69:f4bc:9b04:fde6
Name:   dns-introducer.chia.net
Address: 2a01:e0a:435:43e0:cba8:4dd7:1103:926d
Name:   dns-introducer.chia.net
Address: 2a01:4ff:f0:3c5c::1
Name:   dns-introducer.chia.net
Address: 2603:3000:96:8000:f919:b5bd:5870:e9f2
Name:   dns-introducer.chia.net
Address: 2a06:5b05:9000:4e00:8dda:2b16:d6b4:cc1a
Name:   dns-introducer.chia.net
Address: 2403:6200:8867:4cfa:3dc8:7749:3878:9efb
Name:   dns-introducer.chia.net
Address: 2a02:1210:2a6f:2d00:a7fc:e5c5:99c8:2a45
Name:   dns-introducer.chia.net
Address: 2408:821b:3810:3300:c97e:2a9f:d6b8:7ee9
Name:   dns-introducer.chia.net
Address: 240e:38a:6364:f300:5d9:3398:59d8:6612
Name:   dns-introducer.chia.net
Address: 2001:b011:2014:b918:df4:bbe4:7295:dec2
Name:   dns-introducer.chia.net
Address: 2408:824c:6239:29f0::e0f
Name:   dns-introducer.chia.net
Address: 2a01:e0a:67:1ab0:2c75:c346:8fd9:e1ae
Name:   dns-introducer.chia.net
Address: 2a00:1370:81a2:64e4:15bc:afdb:fc71:8f7d
Name:   dns-introducer.chia.net
Address: 2a01:e0a:369:6760:8851:2dc2:db30:af54
Name:   dns-introducer.chia.net
Address: 2a01:e0a:2a1:b390:1c07:9fbc:5408:e681
Name:   dns-introducer.chia.net
Address: 240e:389:2521:800:49f6:29e8:155c:ba55
Name:   dns-introducer.chia.net
Address: 2804:d45:370f:2f00:a997:79f6:19e0:84ac
Name:   dns-introducer.chia.net
Address: 2001:fb1:da:48b6:edf0:a93e:bce1:ca32
Name:   dns-introducer.chia.net
Address: 2a01:e0a:39b:3070:6e4e:aa33:7b36:39a8
Name:   dns-introducer.chia.net
Address: 2408:825c:1e20:c0e:d96e:78bf:e4b9:b9cc
Name:   dns-introducer.chia.net
Address: 2403:6200:8896:3c3:89d4:38eb:b2d8:3ca9

**Comment by Cerote6669** [comment]
so, i have do do some basic port connects or revalidate commands to redirect traffic?

entry level, i just know enough to get in trouble, rouge learner

**Comment by Cerote6669** [comment]
the powers that be started syncing again, i will look deeper into this chia rabit-hole thanks for links

**Comment by MumfMeisterT** [comment]
@lukar777  It's odd that you have dns issues in your log, but it succeeds on the cli. We recommend rebooting your machine to restart the dns service.

**Comment by Cerote6669** [comment]
U were correct.

Thank you for your patience.
Recent insulator/breaker popped on power pole. Sonic boom

I think it knocked out the wifi.

Rebooted per instruction.

Synced in fine.

I will research all the dns tcp server stuff to get more familiar with the
tech dialog.

Thanks again

**Comment by emlowe** [comment]
Closing issue

**Comment by Cerote6669** [comment]
Awesome, thanks!
