### ISSUE TITLE
[Bug] Chia is blocked at loading farming data and doesn't show any plots 

### ISSUE THREAD

**Issue by julianosro** [Chia-Network/chia-blockchain#15220]
### What happened?

This morning the chia ap 1.8.0 stopped working the full node is connected and wallet also but plots disappeared in the plots tab and in farming tab it just says loading farming data for the last 4 hours  and in pooling tab all my plots disappeared  does someone have a clue what's going on  ?

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by julianosro** [comment]
> ### What happened?
> 
> This morning the chia ap 1.8.0 stopped working the full node is connected and wallet also but plots disappeared in the plots tab and in farming tab it just says loading farming data for the last 4 hours  and in pooling tab all my plots disappeared  does someone have a clue what's going on  ?
> 
> ### Version
> 
> 1.8.0
> 
> ### What platform are you using?
> 
> Windows
> 
> ### What ui mode are you using?
> 
> GUI
> 
> ### Relevant log output
> 
> _No response_

Just found the issue. I had to change the ip for the farmer in the config file.

**Comment by shaneo257** [comment]
Did you solve this issue?

**Comment by MumfMeisterT** [comment]
Awesome. Closing per last comment that this is fixed.
