### ISSUE TITLE
add the ability to switch pages without waiting for the preview to finish loading [Bug] 

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#15235]
### What happened?

![image](https://user-images.githubusercontent.com/95166695/237040772-267eb4e8-4e78-44bd-b8a5-5b24c2d1eaf6.png)
add the ability to switch pages without waiting for the preview to finish loading, because if the preview takes a long time to load, it creates inconvenience for some nfts

### Version

2.0.0 b1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Thanks for testing all of the beta builds but this one wasn't ready for testing
