### ISSUE TITLE
incorrect location of the element [Bug] 

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#15234]
### What happened?

с
![QIP Shot - Screen 143](https://user-images.githubusercontent.com/95166695/237039904-9534180e-7226-4fa3-9563-54fc7b9dd5ad.png)

### Version

2.0.0 b1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Thanks for testing all of the beta builds but this one wasn't ready for testing.
