### ISSUE TITLE
token renaming problem [Bug] 

### ISSUE THREAD

**Issue by HVNC1** [Chia-Network/chia-blockchain#15237]
### What happened?

token renaming problem
https://user-images.githubusercontent.com/95166695/237043642-a227bbe5-43b9-4aa9-ab56-facd5d562390.mp4
this only applies to 1 token which i added when syncing the wallet. all others work fine

### Version

2.0.0 b1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by MumfMeisterT** [comment]
Since this is only happening on the one coin, I believe the removal of characters from the token name may not be triggering the change properly. I would test changing the name entirely (e.g. to "Examplecoin") and then change it back to your "DBX" coin name and see if the change works.

**Comment by MumfMeisterT** [comment]
Thanks for testing all of the beta builds but this one wasn't ready for testing
