### ISSUE TITLE
Chia is not synchronising since updated to 1.8.0 [Bug] 

### ISSUE THREAD

**Issue by olisplots** [Chia-Network/chia-blockchain#15242]
### What happened?

Yesterday, Ive updated chia to 1.8.0 and restarted my computer. 
Wallet connected, not synchronising - it is frozen on 3.632.327

![image](https://github.com/Chia-Network/chia-blockchain/assets/133033095/cff9ea89-0318-46db-85fa-07df0478b47d)

Can anyone help me??

Thanks

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Please provide log output from the Chia debug log.

**Comment by olisplots** [comment]
problem solved - i got help in the discord spacepool chat: deinstalled chia, downloaded dbv2, installed new, synchronized new and everything is working smooth !!
