### ISSUE TITLE
[Bug] Unable to use Madmax Plotter through chia with default values

### ISSUE THREAD

**Issue by aleksei772000** [Chia-Network/chia-blockchain#15252]
### What happened?

after updating the 1.8 version -the medmach plotter stopped working - gives the error does not write rafts 

### Version

1.8

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
![Screenshot 2023-05-11 at 12 50 01 PM](https://github.com/Chia-Network/chia-blockchain/assets/30607889/73ee2bf4-459d-40eb-aeeb-9408c1e8f76b)

Issue from discord as reported

**Comment by paninaro** [comment]
Fix is checked into release/1.8.1
