### ISSUE TITLE
[Bug] Upgrade stuck at loading keyring status

### ISSUE THREAD

**Issue by DmitryYamen** [Chia-Network/chia-blockchain#15258]
### What happened?

Uploaded the new version 1.8.0. At startup, it hangs on the loading keyring status, and so it can indefinitely. Tried deleting the keys, deleting everything and reinstalling it didn't help. It started with updates 1.7
Mac OS 10.14.6 on Intel

### Version

1.8.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
farmer chia.farmer.farmer         : WARNING  No keys exist. Please run 'chia keys generate' or open the UI.
```

**Comment by MumfMeisterT** [comment]
You will need to revert to 1.6.1 for this to work on MacOS 10.14. If you're able to upgrade to 10.15 this would also resolve. 
We do anticipate a new release that will support this platform in the future, however, there will be limited support after that.

**Comment by emlowe** [comment]
It is possible to run and build from source - you can look at this and see if it helps: https://github.com/Chia-Network/chia-blockchain/issues/14907#issuecomment-1544754072

**Comment by DmitryYamen** [comment]
OK, thank you!
