### ISSUE TITLE
[BUG] getting a few "Cannot write to closing transport [various IPs] today in the log…

### ISSUE THREAD

**Issue by Teledyol** [Chia-Network/chia-blockchain#1525]
…should I be concerned?

03:55:54.601 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash bf7bacee406c26dde4ad9e479de535b3f9f7df4a149e34db2d2ce039763b4b62

10:13:27.890 full_node full_node_server        : WARNING  Cannot write to closing transport 80.114.134.68

A few more right after I started a new four plot, in parallel,  process after 1am

08:04:16.920 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash bd9b9d73fd6b2796050e9235b82ec88ca08799d391d19a00290b02a6e13963de

23:43:42.714 full_node full_node_server        : WARNING  Cannot write to closing transport 95.170.229.40
00:27:15.502 full_node full_node_server        : WARNING  Cannot write to closing transport 105.243.3.76

00:49:24.794 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0x791b93c3156e70abf8635ac09ceaecac00b666e991a02638637667a68f32def8',

 'index_from_challenge': 63,
 'last_rc_infusion': '0xf5eb40167a7c42b96a34ba33b3d7c088fbd095ddbf5afa47d5621893b0b5f1e9'}
01:58:13.001 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0xb0a1432069773ad410bde9e4a788c36c25f0be7396911510cfed313f745de7cc',

 'index_from_challenge': 61,
 'last_rc_infusion': '0x225bb36af76ca6f36762ab36608ecc10de6dce469dc09b3971aad676eccae4b7'}
01:58:33.390 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0xb0a1432069773ad410bde9e4a788c36c25f0be7396911510cfed313f745de7cc',

 'index_from_challenge': 62,
 'last_rc_infusion': '0x225bb36af76ca6f36762ab36608ecc10de6dce469dc09b3971aad676eccae4b7'}
01:58:33.396 full_node src.full_node.full_node : WARNING  Don't have signage point {'challenge_hash': '0xb0a1432069773ad410bde9e4a788c36c25f0be7396911510cfed313f745de7cc',

 'index_from_challenge': 63,
 'last_rc_infusion': '0x225bb36af76ca6f36762ab36608ecc10de6dce469dc09b3971aad676eccae4b7'}
03:45:59.768 full_node src.full_node.full_node_store: WARNING  Don't have challenge hash ab9dfc613d1e92349560c6131cf6b8949811cd5c890a04083499926752f143c3

 I'm thinking that these are external connection issues. 

Running macOS 11.2.3 GUI

It seems to be going well, even though I haven't seen (except for one sole 1/8 scroll by, momentarily) anything under "Plots Passed Filter"  A bunch of 0s so far. Getting about 4 plots every 14 hours to a 32T raid; I think I will get to 300 plots on this one. One block of four failed yesterday morning and I deleted the four plots from the directory. It seemed to plot OK after that failure:

17:57:42.169 harvester src.plotting.plot_tools : WARNING  Directory: /Volumes/Slim 2/Farm does not exist.
01:19:38.059 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': '[2600:1f14:8f8:6500:6b62:a666:1570:9431]', 'port': 58444}. Maybe the peer is running old software.
02:33:28.625 harvester asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-13975' coro=<WebSocketWriter.ping() done, defined at aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "aiohttp/http_websocket.py", line 673, in ping
  File "aiohttp/http_websocket.py", line 643, in _send_frame
  File "aiohttp/http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
02:33:31.528 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x11330ee80>
02:33:32.626 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-129765' coro=<kill_service() done, defined at src/daemon/server.py:854> exception=AttributeError("'list' object has no attribute 'terminate'")>
Traceback (most recent call last):
  File "src/daemon/server.py", line 862, in kill_service
  File "src/daemon/server.py", line 830, in kill_process
AttributeError: 'list' object has no attribute 'terminate'
02:34:14.962 wallet src.wallet.wallet_state_manager: WARNING  Starting in db path: /Users/RAW/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_2023226772.sqlite
02:34:22.221 wallet src.wallet.wallet_state_manager: WARNING  Starting in db path: /Users/RAW/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_2023226772.sqlite

**Comment by hoffmang9** [comment]
The only real error there is `17:57:42.169 harvester src.plotting.plot_tools : WARNING Directory: /Volumes/Slim 2/Farm does not exist.`

**Comment by Teledyol** [comment]
Thanks for looking at that I described the Slim 2 story elsewhere. I removed that directory.
