### ISSUE TITLE
[Bug] Request 1e9a3c779f2adb77db7f6f45d80c35f6104ca450ae2d81bddb5edbc42e75c467 failed: {"error":"","success":false}

### ISSUE THREAD

**Issue by Sonypig** [Chia-Network/chia-blockchain#15272]
### What happened?

I switched from solo mode to pool farming mode, and the following error message appears

### Version

1.80

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Sonypig** [comment]
![91519d97b0c8c925505ab1f4de945ba](https://github.com/Chia-Network/chia-blockchain/assets/39574092/bfcfc5b0-9f4c-46af-8333-8d954b6f0120)

**Comment by hoffmang9** [comment]
Fixed here and will be out shortly https://github.com/Chia-Network/chia-blockchain-gui/pull/1753

**Comment by Sonypig** [comment]
> Fixed here and will be out shortly https://github.com/Chia-Network/chia-blockchain-gui/pull/1753

Thanks,I've solved this problem:rollback to the old version and swith to the pool ming
