### ISSUE TITLE
[Bug] changing of pool doesn't work 

### ISSUE THREAD

**Issue by dutchmulti** [Chia-Network/chia-blockchain#15278]
### What happened?

i try to change the pool changed the pool adres added a fee and i hit change nothing happens. 
I am now at [spacepool ](https://eu1.pool.space)https://eu1.pool.space/
and i want to move to https://spacefarmers.io/

Do i need to remove my current pool? 

### Version

1.8

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
Hi,
It's a known issue with 1.8, and will be resolved in 1.8.1, as an interim, you can download the dev version from here https://github.com/Chia-Network/chia-blockchain/releases/tag/1.8.1-rc3

**Comment by emlowe** [comment]
Closing as fixed in 1.8.1
