### ISSUE TITLE
[Bug] Profile cannot be created

### ISSUE THREAD

**Issue by zomb1** [Chia-Network/chia-blockchain#15282]
### What happened?

I have everything synced and can't create a profile.

Creating a profile requires 1 mojo
Spendable Balance: 0,0000000121 XCH

ERROR : "Your spendable balance must be greater than 1 mojo to create a profile"

### Version

1.8

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Your spendable balance must be greater than 1 mojo to create a profile
```

**Comment by MumfMeisterT** [comment]
Try version 1.8.1, this issue should be fixed. thx.
