### ISSUE TITLE
[BUG] npm run electron shared library error on Linux 2

### ISSUE THREAD

**Issue by sampleBen** [Chia-Network/chia-blockchain#1529]
**Describe the bug**
When following installation instructions for the gui on AWS Linux 2, 'npm run electron' command fails to run with the following error message: 

/home/ec2-user/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

Installing libatk-1.0.so.0 with 'sudo yum install libatk-1.0.so.0' has no effect. 

**To Reproduce**

1. Launch new AWS Linux 2 instance and SSH to server
2. Follow all steps in install instructions:
`sudo yum update -y
sudo yum install python3 git -y

git clone https://github.com/Chia-Network/chia-blockchain.git
cd chia-blockchain

sh install.sh

. ./activate

# gui
sh install-gui.sh
cd chia-blockchain-gui
npm run build
npm run electron`

3. Execute 'npm run electron' command
4. See error message

**Expected behavior**
The command should execute without error, if the file libatk-1.0.so.0 is present

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux 2
- CPU: t2.xlarge

**Additional context**

**Comment by hoffmang9** [comment]
I don't think you can run X windows application on AWS.

**Comment by sampleBen** [comment]
Why is there an Amazon Linux 2 instruction set on the wiki? Maybe I'm misunderstanding something. 
See instructions below:
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#amazon-linux-2

**Comment by hoffmang9** [comment]
Linux does not come with a graphical user interface by default. Amazon Linux can't run the usual X Windows stuff locally. I'm not sure why someone copy and pasted the GUI stuff to AWS2 but I'll remove it. See eg https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-2-install-gui/
