### ISSUE TITLE
Change command line arguments to follow conventions?

### ISSUE THREAD

**Issue by ast0815** [Chia-Network/chia-blockchain#1531]
Hello,

I just noticed that the command line arguments of the CLI often use underscores to represent spaces, e.g. `--num_threads`. My impression is that the general convetnion is to use dashes instead, e.g. `--num-threads`. This is what the python library `sh` assumes when translating keyword arguments to command line options. Following this convention would make interacting with Chia ever so slightly more convenient.

**Comment by mariano54** [comment]
Thanks, but there are already many farmers using the commandline options as they are. We should try to stick to conventions moving forward though.
