### ISSUE TITLE
[ENHANCEMENT] Feature request: Queue parallel plotting

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#1534]
Hello everyone,

since I belong to the, I call it "GUI Generation", I would love to see some improvements in plotting with the GUI. Right now there a features to parallel and queue plots. But I would like to queue parallel plots with the GUI. I didn't find a way to do it.

I'm plotting on different hard drives and therefore I'm not able to split a job on different drives. I think that is a nice feature that every GUI user would want. 

Edit: I don't know how to add or replace labels. Can you tell me? This thread got a "bug" label but should be "enhancement".

**Comment by Dravenex** [comment]
Oh, I think I've just found out how it works. Since the 1.0 Version there are queue names. But that definitely needs a rework, because it's pretty hard to find out how to use them correctly.

**Comment by Teledyol** [comment]
Well, where do you find that info, and how did you make it work?

**Comment by mariano54** [comment]
Yes you can add 10 plots to a queue, and set the queue name.
Then if you add another 10 to a different queue, they will run in parallel. 
This is already supported.
