### ISSUE TITLE
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address

### ISSUE THREAD

**Issue by garik-code** [Chia-Network/chia-blockchain#1535]
# [ERR] chia start timelord

## Check list

* chia init✅
* chia keys generate✅
* chia plots create -k 32 -n 2✅
* chia start timelord🚫 

## Error

```
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon
```

## Logs

Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-70-generic x86_64)
```



(venv) root@vmi777:~/chia-blockchain# chia start timelord



Daemon not started yet
Starting daemon
Traceback (most recent call last):
  File "/root/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/root/chia-blockchain/src/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/chia-blockchain/src/cmds/chia.py", line 60, in run_daemon_cmd
    asyncio.get_event_loop().run_until_complete(async_run_daemon(ctx.obj["root_path"]))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/chia-blockchain/src/daemon/server.py", line 932, in async_run_daemon
    await ws_server.start()
  File "/root/chia-blockchain/src/daemon/server.py", line 137, in start
    self.websocket_server = await serve(
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '



OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
Daemon not started yet
Failed to create the chia daemon



```

**Comment by hoffmang9** [comment]
Is it possible you had another chia node or daemon running already? If not, you need to find out what is already running on port 55400.

**Comment by garik-code** [comment]
> Is it possible you had another chia node or daemon running already? If not, you need to find out what is already running on port 55400.

![image](https://user-images.githubusercontent.com/33745472/112736621-99d4cf00-8f6d-11eb-8355-3f79e420464b.png)

Are there more options?

**Comment by justin8** [comment]
I'm seeing the same issue here when running `chia start node` on Ubuntu 20.04. No process running on `:55400`

**Comment by justin8** [comment]
Figured it out. So, the default generated `config.yaml` defines `self_hostname` as `self_hostname: &self_hostname "localhost"`.

If you don't have IPv6 enabled in your environment, requests will still resolve `localhost` to mean `::1` and not `127.0.0.1`. Replacing `localhost` with `127.0.0.1` allows the node to start successfully.

I presume this would work fine on an environment with ipv6 enabled.

**Comment by garik-code** [comment]
> Figured it out. So, the default generated `config.yaml` defines `self_hostname` as `self_hostname: &self_hostname "localhost"`.
> 
> If you don't have IPv6 enabled in your environment, requests will still resolve `localhost` to mean `::1` and not `127.0.0.1`. Replacing `localhost` with `127.0.0.1` allows the node to start successfully.
> 
> I presume this would work fine on an environment with ipv6 enabled.

Thx! It worked for me.

**Comment by PachiMc** [comment]
same error here, 127.0.0.1 didnt work

**Comment by bigcat133** [comment]
that bind a ipv6 address ,so you need your docker support it
you can do that if docker version great 20.10.2
edit /etc/docker/daemon.json or create if it dont exist
``` json
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80",
  "experimental": true,
  "ip6tables": true
}
```
restart docker engine
```bash
sudo systemctl restart docker
```

try again

**Comment by zanghu** [comment]
> Figured it out. So, the default generated `config.yaml` defines `self_hostname` as `self_hostname: &self_hostname "localhost"`.
> 
> If you don't have IPv6 enabled in your environment, requests will still resolve `localhost` to mean `::1` and not `127.0.0.1`. Replacing `localhost` with `127.0.0.1` allows the node to start successfully.
> 
> I presume this would work fine on an environment with ipv6 enabled.

THX, nice explaination!
