### ISSUE TITLE
Error when running command " npm run electron &" on CENTOS 8 or UBUNTU 18/20

### ISSUE THREAD

**Issue by danix4u** [Chia-Network/chia-blockchain#1537]
I have spent more than 12 hours trying to fix this error on CentOS 8/unbuntu, with no luck and below is the full error script and the log. Could this be a bug in the script?

(venv) ubuntu@machine4:~/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 13566
(venv) ubuntu@m4:~/chia-blockchain/chia-blockchain-gui$
> chia-blockchain@1.0.0 electron /home/ubuntu/chia-blockchain/chia-blockchain-gui
> electron .

/home/ubuntu/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
The futex facility returned an unexpected error code.
/home/ubuntu/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGABRT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@1.0.0 electron: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chia-blockchain@1.0.0 electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-28T01_23_55_157Z-debug.log

[1]+  Exit 1                  npm run electron
(venv) ubuntu@m4:~/chia-blockchain/chia-blockchain-gui$

Log:

 nano  /home/ubuntu/.npm/_logs/2021-03-28T01_08_05_089Z-debug.log

  GNU nano 4.8                                                                             /home/ubuntu/.npm/_logs/2021-03-28T01_08_05_089Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@1.0.0~preelectron: chia-blockchain@1.0.0
6 info lifecycle chia-blockchain@1.0.0~electron: chia-blockchain@1.0.0
7 verbose lifecycle chia-blockchain@1.0.0~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@1.0.0~electron: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/ubuntu/chia-blockchain/venv/bin:/usr/local/sbin:/u>
9 verbose lifecycle chia-blockchain@1.0.0~electron: CWD: /home/ubuntu/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@1.0.0~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@1.0.0~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@1.0.0~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@1.0.0 electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid chia-blockchain@1.0.0
15 verbose cwd /home/ubuntu/chia-blockchain/chia-blockchain-gui
16 verbose Linux 5.4.0-70-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@1.0.0 electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@1.0.0 electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
****

**Comment by j15marti** [comment]
I've been getting the same error on Ubuntu Server. I assumed that it occurred because I don't have a Ubuntu GUI running, but I could be wrong...

**Comment by danix4u** [comment]
I installed Ubuntu GUI with different flavours the error would be different. Not sure what flavour Chia team used with that script, but it seems it works only with one falvour. I used GNOME, Xubuntu, same issue.

**Comment by gianza** [comment]
Seems to be a duplicate of #1384

**Comment by mariano54** [comment]
This should be fixed in 1.0.3, can you try it?

**Comment by MontajnikRTA** [comment]
~/chia-blockchain$ npm run electron &
[1] 58655
(venv) hyperx@hyperx-MS-7C56:~/chia-blockchain$ npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/hyperx/chia-blockchain/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open
