### ISSUE TITLE
[Bug] Chia 1.8.1 stuck at Loading keyring status when installing on Win10

### ISSUE THREAD

**Issue by Jutean** [Chia-Network/chia-blockchain#15392]
### What happened?

Restarting did not solve this problem, and reinstalling the software did not fix it

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-05-27T20:38:45.124 wallet chia.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
2023-05-27T20:38:45.300 wallet chia.rpc.rpc_server        : ERROR    Starting RPC server failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 438, in start_rpc_server
  File "chia\rpc\rpc_server.py", line 187, in start
  File "chia\util\network.py", line 80, in create
  File "aiohttp\web_runner.py", line 121, in start
  File "asyncio\base_events.py", line 1506, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('::1', 9256, 0, 0): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
```

**Comment by hbroer** [comment]
Does something else run on Port 9256? You can check that with `netstat -aon | findstr 9256`. The outtput should be empty. If chia runs or there is something else running on that port the output looks like this:

```cmd
netstat -aon | findstr 9256
  TCP    127.0.0.1:9256         0.0.0.0:0              LISTENING       33976
  TCP    [::1]:9256             [::]:0                 LISTENING       33976
```

**Comment by Jutean** [comment]
> ```shell
> t chia.rpc.rpc_server        : ERROR    Starting RPC server failed. Exception Traceback (most recent call last):
>   File "chia\rpc\rpc_server.py", line 438, in start_rpc_server
>   File "chia\rpc\rpc_server.py", line 187, in start
>   File "chia\util\network.py", line 80, in create
>   File "aiohttp\web_runner.py", line 121, in start
>   File "asyncio\base_events.py", line 1506, in create_server
> PermissionError: [Errno 13] error 
> ```

thx

**Comment by jjldv** [comment]
im here with the same issue, but upgrading 1.8.1 to 1.8.2, nobody is using the port 9526, using windows 10

![image](https://github.com/Chia-Network/chia-blockchain/assets/6075488/06fc3696-da7d-4b0e-8e53-12a2623d626f)

**Comment by hbroer** [comment]
@jjldv do you have the same error in your logfile, else it is not related to the port

> ```shell
> PermissionError: [Errno 13] error while attempting to bind on address ('::1', 9256, 0, 0)
> ```

**Comment by jjldv** [comment]
After windows update, fixed! thanks
