### ISSUE TITLE
Error 22. Can't add plots

### ISSUE THREAD

**Issue by Chuck000Norris** [Chia-Network/chia-blockchain#1539]
I wiped my app data local and roaming folders and re-installed 1.0.1 and still error 22 diag box. doesn't see any of my plots. If i point to a directory nothing happens. Was working fine. I hard shutdown my pc because it locked up and boinked my wallet. Not i can't fix it.

**Comment by hoffmang9** [comment]
There is most likely a plot directory in your config.yaml that the application can't access. `C:\Users\YOURUSERNAME\.chia\mainnet\config\config.yaml`
