### ISSUE TITLE
[BUG] Wallet Failing to sync

### ISSUE THREAD

**Issue by beagle182** [Chia-Network/chia-blockchain#1541]
After a reboot the wallet is failing to sync is either showing a "Not synced" or "syncing" message after a few minutes string error is displayed. Screen shots provided below.

**To Reproduce**
Rebooted windows 10 
open chia 
await error

**Expected behavior**
Wallet to sync without error

**Screenshots**
![image](https://user-images.githubusercontent.com/81511796/112749110-26a47a80-8fb8-11eb-8eb6-56c6cd841025.png)

**Desktop **
Desktop PC 
windows 10 pro
chia 1.0.1

**Additional context**
all other items appear to be running correctly, i have uninstalled and reinstalled chia 1.0.1 which has done nothing for the issue along with standard trouble shooting i.e. reboot etc.

**Comment by hoffmang9** [comment]
Should be fixed in 1.0.3
