### ISSUE TITLE
[BUG] [WIN-10] No peers

### ISSUE THREAD

**Issue by gavraz** [Chia-Network/chia-blockchain#1542]
**Describe the bug**
My node has no peers.
Sometimes I am able to add a friend manually. Sometimes we get disconnected.
Either way, my node does not discover new peers and I end up with 0-1 peers (hence 'not synced' most of the time).
[In addition, where can I find the IP of Chia's machines?]

**To Reproduce**
No peers even after node restart.

**Expected behavior**
To have a list of peers.

**Desktop (please complete the following information):**
- Windows 10
- Intel i7 4790

**Comment by gavraz** [comment]
Worth noting that UPNP is set and working.

**Comment by mariano54** [comment]
Can you checkout the log and see if there are any error messages there?

**Comment by gavraz** [comment]
Can't see any errors. Looks like the node is not trying to connect to additional peers.
Are there any specific log messages I can look for you? Should I set logging level to 'info'?

Thanks.

**Comment by mariano54** [comment]
Did you manage to find out what the issue was?

**Comment by gavraz** [comment]
Not really, but I managed to fix it.
I closed the node, then removed .chia and then launched the node, and now it works (I have>10 peers and synced).

But:
- Canceling a plot doesn't work. Usually get's stuck. (and files in tmp dir are not deleted).
- The amount of required temp storage stated for k=33 is incorrect. It requires above 600 GB.
- Closing the node sometimes hangs 'forever'.
(all the above are relevant to ver 1.0.2).

**Comment by lvpcguru** [comment]
maybe close this one? seems like the original issue was resolved and the follow-on ones are for several versions back?

> 
> 
> Not really, but I managed to fix it.
> I closed the node, then removed .chia and then launched the node, and now it works (I have>10 peers and synced).
> 
> But:
> 
>     * Canceling a plot doesn't work. Usually get's stuck. (and files in tmp dir are not deleted).
> 
>     * The amount of required temp storage stated for k=33 is incorrect. It requires above 600 GB.
> 
>     * Closing the node sometimes hangs 'forever'.
>       (all the above are relevant to ver 1.0.2).

maybe close this one? seems like the original issue was resolved and the follow-on ones are for several versions back?
