### ISSUE TITLE
Incorrect Earned Percentage in new harvester tab

### ISSUE THREAD

**Issue by Darbletan** [Chia-Network/chia-blockchain#15429]
On latest 4.3 build, the harvester tab is showing a negative number for each of my harvesters in the "Earned" box. 

Ubuntu 22.04 Desktop for primary farmer, Ubuntu 22.04 server for the 3 remote harvesters

![harvy](https://github.com/Chia-Network/chia-blockchain/assets/69985952/0dcfc876-f0f0-40ae-a3fc-4889ddac1dec)

**Comment by ChiaMineJP** [comment]
Thanks for reporting. I'll check the bug.

**Comment by ChiaMineJP** [comment]
I've found and fixed the problematic code. Maybe in the next release you can confirm the fix.
