### ISSUE TITLE
Pooling Server not loading

### ISSUE THREAD

**Issue by Maddsdadd** [Chia-Network/chia-blockchain#15438]
### What happened?

The pool URL "https://pool.poolchia.com" is not working. Is it a pool? Error: Failed to fetch

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
The pool URL "https://pool.poolchia.com" is not working. Is it a pool? Error: Failed to fetch
```

**Comment by hbroer** [comment]
This is not a Blockchain Bug, so this can't be fixed by the Chia devs. The group behind PoolChia did not pay the bills for their servers:

![image](https://github.com/Chia-Network/chia-blockchain/assets/14164004/d38a7ca5-26ae-4422-b6c9-48764eef604e)

Solution: Switch to another pool
