### ISSUE TITLE
1.75 XCH self-pooling reward does not appear in wallet transactions [Bug] 

### ISSUE THREAD

**Issue by joelrb** [Chia-Network/chia-blockchain#15433]
### What happened?

I just won 2 blocks one yesterday and another one today. I claimed both 1.75 XCH rewards but no record in transactions.

This has been raised in Chia forum last 2022.
https://chiaforum.com/t/1-75-xch-claimed-from-selfpooling/17560/13

![Screenshot from 2023-06-02 11-19-58](https://github.com/Chia-Network/chia-blockchain/assets/225284/09ff9443-52f1-43f0-bed2-d47c3218dab6)
![Screenshot from 2023-06-02 10-55-28 (1)](https://github.com/Chia-Network/chia-blockchain/assets/225284/c9b7ec2d-1fa6-49b4-b94f-871214a099d6)

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by heget** [comment]
Hi, 
I mention this problem also here : 
https://github.com/Chia-Network/chia-blockchain/issues/13963
This is probably known issue so maybe one day will be fixed.
Or I'm asking if this could be related to the derivation index setting?

**Comment by joelrb** [comment]
> Hi, I mention this problem also here : #13963 This is probably known issue so maybe one day will be fixed. Or I'm asking if this could be related to the derivation index setting?

Oh ok thanks. It's weird that what was working in early 2022 could be undone by newer versions. 

In Chiaforum.com it was suggested that the only workaround is to delete the wallet database and start over with a new wallet db (do a sync again).

**Comment by heget** [comment]
I need some answer from devs.
Is the derivation setting related to this?
The issue still continue.

**Comment by joelrb** [comment]
> I need some answer from devs. Is the derivation setting related to this? The issue still continue.

Devs should make this one of their priorities. It's important that the right record be reflected and not make users wonder what happened to the 1.75 XCH.
