### ISSUE TITLE
[Bug] MadMax NFT plotting task drops in the middle or towards the end of plotting, NFT Plots get stuck in GUI and MadMax isn't Using CPU Power from assigned Threads as it was with older versions.

### ISSUE THREAD

**Issue by Brydandon** [Chia-Network/chia-blockchain#15440]
### What happened?

I begin plotting 10 in queue on chia versions and find that plotting halts (Sometimes so close to a plot being done at 98%).

I open task manager to watch and all of a sudden the plotting task drops in the middle or towards the end of plotting. Not finishing the plot for K32, K33, or K34.

I have a Threadripper 3960x (Liquid Cooled) w/ Asus Prime-Pro motherboard and 128GB of DDR4 RAM, no overclocks.

This is happening on Windows 10 and on Ubuntu 23.04.

Attempted to plot w/ plot NFT from Samsung Evo 980 2TB NVMe to Western Digital Red 22TB.
Attempted to plot w/ plot NFT directly onto Western Digital Red 22TB.

Both attempts lead to same plot task dropping outcome. % Progression gets stuck in GUI.

This is with stock settings for MadMax Plotter 1.1.6-2092041 (4 number of threads/1 thread multiplier/256 number of buckets/256 number of buckets for phase 3 & 4)

MadMax also isn't using CPU Power from assigned Threads as it was with older versions. In the task manager in both windows and ubuntu I would notice that in pre-1.8 versions CPU % usage would be 10-50% when assigned specific amount of threads, now with 1.8+ versions no matter how many threads I assign it will only utilize between 0.20% to 9% of CPU power and goes extremely slow creating the plot.

Any solutions? Because the only solution I have right now is to use an older versions of chia before the soft fork. I am literally having to plot with madmax on chia version 1.5 for plotting to work 60% of the time without the plotting task drops, ( chia 1.5 just shows me the best results to plot with madmax to nft plot because its worst on chia 1.6 working 30% of the time without task drops and almost always drops plotting task with chia 1.7 and up), and move the hard drive onto a completely different machine with a post soft fork version of chia (1.8.1) to farm. 

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by iTZUNAMI** [comment]
try to format the nvme drive for plotting and make a bench of that drive
also use like 40 thread on settings, not just 4 to have 100% cpu

**Comment by Brydandon** [comment]
> try to format the nvme drive for plotting and make a bench of that drive also use like 40 thread on settings, not just 4 to have 100% cpu

Alright I will give that a try with the threads and by bench the drive do you mean benchmark the health of the drive?

**Comment by iTZUNAMI** [comment]
yes and the write speed of the drive. i got the same problem and formatting the nvme solved the problem because it was very slow to write, and i never used it after plotting months ago..
if you have nvme gen4 check also from bios that is enabled gen4 speed

**Comment by iTZUNAMI** [comment]
you can use crystal bench or hd tune

**Comment by Brydandon** [comment]
> yes and the write speed of the drive. i got the same problem and formatting the nvme solved the problem because it was very slow to write, and i never used it after plotting months ago.. if you have nvme gen4 check also from bios that is enabled gen4 speed



> you can use crystal bench or hd tune

Awesome thank you so much for contributing to a solution, I will report back with my results.

**Comment by Brydandon** [comment]
> try to format the nvme drive for plotting and make a bench of that drive also use like 40 thread on settings, not just 4 to have 100% cpu

You were right. I did the slow and long format of the NVMe, worked like normal without any dropping in the task. The issue didn't fix with "Quick Format", but with the slow "Full Format" everything worked like a charm.

Thank you so much!
