### ISSUE TITLE
MacOS Catalina [BUG] Full Node failing to load/sync

### ISSUE THREAD

**Issue by mwolfe07** [Chia-Network/chia-blockchain#1545]
Was able to plot a single plot, but it went into "not available" status - waiting for synchronization. When I check the wallet it shows not synced, when I check the full node page in the GUI it just has the 3 circles constantly spinning, and has been for hours. I did unplug the HDD accidentally, but when I set everything up again its behaving the same way.

I'm expecting the full node to connect, and sync, and the plot created to be farmable.

![Screen Shot 2021-03-28 at 12 12 05 PM](https://user-images.githubusercontent.com/26875710/112759214-0973aa00-8fc0-11eb-9a7c-0548c6aedf8b.png)

![Screen Shot 2021-03-28 at 12 21 41 PM](https://user-images.githubusercontent.com/26875710/112759253-2dcf8680-8fc0-11eb-9302-1e2c8a75f77e.png)

![Screen Shot 2021-03-28 at 12 21 14 PM](https://user-images.githubusercontent.com/26875710/112759237-1e503d80-8fc0-11eb-82c2-05623fd82fab.png)

On a Mac Laptop (2017, 8GB RAM, i5) w/ a easystore 14TB HDD

**Comment by hoffmang9** [comment]
Which version of Chia is this?

**Comment by mwolfe07** [comment]
its 1.0.1 just downloaded it a couple days ago

**Comment by hoofin22** [comment]
I'm having exactly the same issue

**Comment by hoffmang9** [comment]
Please try this experimental installer - https://download-chia-net.s3-us-west-2.amazonaws.com/tests/Chia-1.0.4-rc1.dmg

**Comment by et477** [comment]
Having the same problem on my two Mac's. Tried 1.0.4 with no success. Still does show 3 circles spinning.

Is there any solution to fix this?

Thx

**Comment by hoofin22** [comment]
Yes, I'm still stuck on this too - been nearly 2 weeks without any fix...?

**Comment by et477** [comment]
I got it syncing now. It takes hours. Not finished yet. What I need to do is add all the plots again. Looking for a way to do this fast. Anyway, I’ve installed 1.0.4 an then renamed ~/.chia folder in case I need it again. Then started chia (it does create a new chia folder) and its syncing now. I trust in a couple of hours I am up and farming again.

**Comment by rdklcryptomgck** [comment]
I am having the same issue iMac: macOS Catalina 10.15.7, 3.4 GHz quad-core i7, 32 GB RAM
