### ISSUE TITLE
XCH stuck in UNCONFIRMED

### ISSUE THREAD

**Issue by the-babaji** [Chia-Network/chia-blockchain#1546]
running multiple harvesters all reporting to a master farmer 
farmer is free bsd
harvesters are ubuntu linux 20.04

last night i noticed 2.0 xch reported as unconfirmed  in wallet #3 on my farmer

that was over 12 hours now and it remains there as unconfirmed

chia explorer also does not show any new XCH

any help would be appreciated.

**Comment by mariano54** [comment]
Can you show a screenshot of the unconfirmed balance?

**Comment by the-babaji** [comment]
sure, where you go
![wallet _screen](https://user-images.githubusercontent.com/20292406/112795514-9fe2b280-9036-11eb-8d8e-e365c0ddc7d4.png)

**Comment by mariano54** [comment]
Oh this is fine. That unconfirmed number is actually (confirmed (2) + unconfirmed (0))

**Comment by the-babaji** [comment]
I am not 100% sure what you are suggesting.

the confirmed(2) was from many days ago when i got my first reward and unconfirmed was zero , and it sayed like that for many days. Now 36 hours ago suddenly unconfirmed was 2, which to me suggest a new block was found.   I don't see how it goes from 

confimred (2)
unconfirmed (0)

to: (some days later)

to confirmed(2)
unconfirmed(2) 

and now has remained that way for over 36 hours. It's my understanding that the unconfirmed 2 should go away after some blocks and be transferred to confirmed balance.
