### ISSUE TITLE
[Bug]   I can't send chia !!!

### ISSUE THREAD

**Issue by Buratino1983** [Chia-Network/chia-blockchain#15479]
### What happened?

I can't send chia tokens to another address I can't even paste the address I copied earlier!! Scam??

### Version

first

### What platform are you using?

macOS

### What ui mode are you using?

GUI

### Relevant log output

```shell
I can't send chia tokens to another address I can't even paste the address I copied earlier!! Scam??
```

**Comment by hbroer** [comment]
"first" is not a version number and you did not provide a log output. But I rly think that you do something wrong. The official Chia Wallet is used by many people and they all can send and receive XCH, Tokens and NFTs. And copy and pasting text also works just fine.

![image](https://github.com/Chia-Network/chia-blockchain/assets/14164004/2f579249-5385-4268-ac1f-a3e7dcdafc32)
This is Windows, but should work on any version on any platform.
