### ISSUE TITLE
[BUG] Chia GUI Whitescreen

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#1552]
Sometimes the Chia GUI just shows a Whitescreen. Chia.exe processes still run, but to get the GUI going I need to restart it which kills all the running plots. I'm running 5 plots parallel on i7-5820k with 32 GB RAM and 2 x 1 TB SSD. Never had the problem before. 

Screenshot: 
![Chia_Whitescreen](https://user-images.githubusercontent.com/79578061/112817632-f07ffd00-9082-11eb-86d7-d7359d51288c.jpg)

I'm on Windows 10 and Version 1.0.1.

**Comment by banguero** [comment]
I have seen this. One workaround is to select View -> Force Reload (that will refresh the UI, and your plots will still continue going)

**Comment by hoffmang9** [comment]
Closing with the assumption that reload works.
