### ISSUE TITLE
GUI Stuck on starting Full Node [Bug] 

### ISSUE THREAD

**Issue by CarlMcFadden** [Chia-Network/chia-blockchain#15531]
### What happened?

![Chia bug](https://github.com/Chia-Network/chia-blockchain/assets/107058693/8b689f53-bab0-4673-8455-fcdcee6a3832)

Computer updated last night. Since then haven't been able to get past starting service.

OS Build 22621.1848

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
have you been able to resolve this issue, and if not, have you checked your log for any issues
