### ISSUE TITLE
[BUG] Multiple Powershell Plots

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#1555]
Because of the pretty unstable GUI right now I want to switch to CLI in Windows 10. Unfortunately I cant't start more than 3 parallel powershells. If I start my script the fourth time, after 5-10 Seconds the window just disappears.

This is my script. I saved it to desktop and open it with right click -> run in powershell

`cd ~\AppData\Local\Chia-Blockchain\app-1.0.1\resources\app.asar.unpacked\daemon\`
`.\chia plots create -k 32 -b 4608 -u 128 -r 2 -n 4 -t D:\ -d F:\`

Is it really a bug or am I doing something wrong? Is it possible to run multiple plots in one powershell?

**Comment by hoffmang9** [comment]
How much system RAM do you have? That looks like the OS is shutting down the last process for out of memory.

**Comment by Dravenex** [comment]
> How much system RAM do you have? That looks like the OS is shutting down the last process for out of memory.

I have 32 GB of RAM. Each plot has 4608 MB assigned. So that shouldn't be a problem. In the GUI I've never had any problems with plotting 5 or 6 parallel.

**Comment by mariano54** [comment]
Were you able to fix or identify this issue @Dravenex?

**Comment by Dravenex** [comment]
I could fix this issue. It had something to do with my pagefile.sys. I needed to set the RAM allocation to "managed by system".
