### ISSUE TITLE
[ENHANCEMENT] CLI get transactions, improve usability

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain#1556]
**Describe the bug**
Farmed 4 blocks, only see transactions for the first 3 in the CLI.

**Comment by mariano54** [comment]
I was not able to replicate this @xdustinface. Can you provide some instructions of how to replicate? Also do you mind using the main branch and seeing if the issue is present here as well?

**Comment by mariano54** [comment]
The CLI is meant to be a more high level user interface, while the RPC is meant to be low level. You can fetch the json like this:
```
curl --insecure --cert ~/.chia/mainnet/config/ssl/wallet/private_wallet.crt \
--key ~/.chia/mainnet/config/ssl/wallet/private_wallet.key -d '{"wallet_id": 1}' \
-H "Content-Type: application/json" -X POST https://localhost:9256/get_transactions | python -m json.tool
```

**Comment by xdustinface** [comment]
Got it :+1: So then i guess it's ok to leave the user input to walk through transactions thing but it should imo at least become a bit more obvious by its wording and a `-o/--offset` or maybe `-s/--start-date` would probably still be good.

**Comment by jespino** [comment]
I think I can easily add that.
