### ISSUE TITLE
[BUG] New plots are not added.

### ISSUE THREAD

**Issue by titusz** [Chia-Network/chia-blockchain#1557]
With Chia 1.0.1 (and 1.0.0) on Windows after running for a while newly generated plots are not added reliably to the farm without restart. Using "Refresh plots" on the plots screen does not fix the issue.

There are actually 52 plots available but Plot Count shows 49, and "Last Attempted Proof" shows mixed results.

![image](https://user-images.githubusercontent.com/278556/112844278-d571b500-90a3-11eb-839e-2f689dcfdd45.png)

- OS: Windows
- OS 10
- CPU: Intel Core i7-770K

**Comment by mariano54** [comment]
@seeden do you know what this is? Is it gui related?
