### ISSUE TITLE
Не пришли на кошелек, какая-то ошибка

### ISSUE THREAD

**Issue by 444Alex** [Chia-Network/chia-blockchain#15585]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/15582

<div type='discussions-op-text'>

<sup>Originally posted by **444Alex** June 22, 2023</sup>
Здравствуйте. Купил на Kucoin и отправил на официальный кошелек 3.9513 XCH на адрес  
xch1567cu7nge4k578dhkwq8uq9sfuqqpqy9np3gk27t6y462m7l5v8swrtkvl       
На Kucoin статус  Завершено . Но на официальный кошелек не пришли . Что делать ? </div>

**Comment by shaneo257** [comment]
closing as its in discussions
