### ISSUE TITLE
On startup, Windows Installed versions that have a missing plot directory give error 13 [BUG]

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#1559]
On startup, the GUI will read the plot directories and if one is e.g. missing because it was unplugged we will show an Error 13. 

Instead we should capture the error and populate the popup with "Error reading directory E:\Plots\"

![paste (5)](https://user-images.githubusercontent.com/30377676/111080596-69485c00-84bc-11eb-9657-e365128fe840.png)

**Comment by 2Jelly2** [comment]
I had the same problem and fixed it by deleting the folder `C:\Users\YOUR_USER_NAME\.chia`.
(You will have to restore keys using your mnemonics and re-locate plots directories afterwards.)

**Comment by r0mande** [comment]
Do you have to resync then?

**Comment by 2Jelly2** [comment]
> Do you have to resync then?

Yes. Probably deleting the entire folder is sufficient but unnecessary.

**Comment by LeeDurant** [comment]
I remedied this in my own install by going into config.yaml and only deleting the parts of the config that refer to the missing directories and replacing them with new directories. It appears I did **not** have to resync to mainnet afterwards.
