### ISSUE TITLE
[BUG] Wallet is not syncing even though full node is synced

### ISSUE THREAD

**Issue by banguero** [Chia-Network/chia-blockchain#1562]
**Describe the bug**
When mainnet first launched, it was syncing ok, but a couple of days ago I switched to running my GUI node to a new machine. It took forever to sync, since there block height was up to 49K. Now it is synced:
![image](https://user-images.githubusercontent.com/1873511/112865286-7a24d000-906d-11eb-964e-d3c1bfa4ad9d.png)
however, the wallet is not syncing (it is being 24+hrs)
![image](https://user-images.githubusercontent.com/1873511/112865374-9163bd80-906d-11eb-8eb2-ed1ca17dbbd7.png)

Anyone knows if there is a work around, or a way to force sync the Wallet? (even if it is running a script, etc.)

**To Reproduce**
See steps in the descriptions

**Expected behavior**
Syncing should not only bring the machine up to date in terms of blocks/height, but it should also sync the wallet

**Screenshots**
inline in description above

**Desktop (please complete the following information):**

- OS: [Windows]
- OS Version/Flavor: [10]
- CPU: [Intel(R) Core(TM) i7]

**Comment by hoffmang9** [comment]
Should be fixed in 1.0.3
