### ISSUE TITLE
payment clawed back while syncing dispalyed incorrectly[Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#15641]
### What happened?

If a payment is actively being clawed back while the recipient's wallet is syncing, the transaction will show up as `Confirmed` in the recipient's wallet, even though the balance will correctly show that the payment did not arrive. The following video shows a sender creating a clawback transaction and then clawing it back. Afterward, the recipient loads their wallet and the transaction is incorrectly displayed. Refreshing the wallet GUI doesn't solve it.

I don't think this is a GUI issue because the payment is also displayed incorrectly in the wallet CLI, as shown in the final seconds of the video.

https://github.com/Chia-Network/chia-blockchain/assets/69756004/9a441897-008f-4e80-8923-e2b2bd37c051

By contrast, the following video shows the scenario where a clawback payment is received and then clawed back before the recipient can claim it (the payment is originated from a wallet on another computer). The recipient's wallet is synced the entire time in this scenario. This time, the transaction vanishes. This is also probably not the most desirable way to show a clawback, either (better would be to indicate that it was clawed back), but at least it doesn't incorrectly show that the transaction has been confirmed.

https://github.com/Chia-Network/chia-blockchain/assets/69756004/01a6916c-8a0f-4dde-89cf-bfb4c2b4c6c0

Both of these videos have been shortened for brevity in viewing.

### Version

1.8.2rc5

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
is this still an issue dan?

**Comment by danieljperry** [comment]
This is fixed in 2.0.0b5.
