### ISSUE TITLE
[Bug] Combine coins

### ISSUE THREAD

**Issue by imba-pericia** [Chia-Network/chia-blockchain#15661]
### What happened?

I decided to shake the dust out of my wallet)
The description of the command on the documentation site says "The number of coins we are combining [default: 500]". But when exceeding 500 coins, an error is displayed, either this is a bug, or the description is not correct.
Two error outputs with and without "-n".

https://docs.chia.net/wallet-cli#combine

![image](https://github.com/Chia-Network/chia-blockchain/assets/102978721/5aee4fda-9326-4491-8505-6ec5337d663c)

### Version

1.8.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia wallet coins combine -a 0.1 --fee 0.000000001 --smallest-first --max-amount 0.1
Exception from 'wallet' {'error': 'Transaction of 100000001000 mojo would use more than 500 coins. Try sending a smaller amount', 'success': False}:
Traceback (most recent call last):
  File "chia/cmds/cmds_util.py", line 116, in get_any_service_client
  File "chia/cmds/cmds_util.py", line 235, in execute_with_wallet
  File "chia/cmds/coin_funcs.py", line 135, in async_combine
  File "chia/rpc/wallet_rpc_client.py", line 348, in select_coins
  File "chia/rpc/rpc_client.py", line 61, in fetch
ValueError: {'error': 'Transaction of 100000001000 mojo would use more than 500 coins. Try sending a smaller amount', 'success': False}
--------------------------------------------------------
chia wallet coins combine -a 0.001 --fee 0.000000001 --smallest-first --max-amount 0.05 -n 1000
Exception from 'wallet' 1000 coins is greater then the maximum limit of 500 coins.:
Traceback (most recent call last):
  File "chia/cmds/cmds_util.py", line 104, in get_any_service_client
  File "chia/cmds/cmds_util.py", line 224, in execute_with_wallet
  File "chia/cmds/coin_funcs.py", line 119, in async_combine
ValueError: 1000 coins is greater then the maximum limit of 500 coins.
```

**Comment by shaneo257** [comment]
due to block size, 500 is the max amount of coins that can combined in a transaction
the docs will be updated shortly advising of this

**Comment by shaneo257** [comment]
docs site has now been updated to advise the max number of coins that can be combined is 500
