### ISSUE TITLE
Fedora [BUG] install script failing on "install-gui.sh: line 82: npm: command not found"

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chia-blockchain#1566]
Fedora OS.
$ git clone https://github.com/Chia-Network/chia-blockchain.git -b latest
$ sh install.sh - all good.

Successfully built aiter bitstring keyrings.cryptfile
Installing collected packages: pycparser, cffi, zipp, jeepney, cryptography, six, SecretStorage, multidict, importlib-metadata, idna, blspy, yarl, typing-extensions, pycryptodome, portalocker, keyring, clvm, chardet, attrs, async-timeout, argon2-cffi, websockets, sortedcontainers, setproctitle, PyYAML, keyrings.cryptfile, concurrent-log-handler, colorlog, clvm-tools, clvm-rs, click, chiavdf, chiapos, chiabip158, bitstring, aiter, aiosqlite, aiohttp, chia-blockchain
  Running setup.py develop for chia-blockchain
Successfully installed PyYAML-5.4.1 SecretStorage-3.3.1 aiohttp-3.7.4 aiosqlite-0.17.0 aiter-0.13.20191203 argon2-cffi-20.1.0 async-timeout-3.0.1 attrs-20.3.0 bitstring-3.1.7 blspy-1.0 cffi-1.14.5 chardet-3.0.4 chia-blockchain chiabip158-1.0 chiapos-0.9 chiavdf-1.0.1 click-7.1.2 clvm-0.9.4 clvm-rs-0.1.4 clvm-tools-0.4.3 colorlog-4.7.2 concurrent-log-handler-0.9.19 cryptography-3.4.6 idna-3.1 importlib-metadata-3.9.1 jeepney-0.6.0 keyring-23.0.0 keyrings.cryptfile-1.3.4 multidict-5.1.0 portalocker-2.3.0 pycparser-2.20 pycryptodome-3.10.1 setproctitle-1.2.2 six-1.15.0 sortedcontainers-2.3.0 typing-extensions-3.7.4.3 websockets-8.1 yarl-1.6.3 zipp-3.4.1

Chia blockchain install.sh complete.

To install the GUI type 'sh install-gui.sh' after '. ./activate'

Type '. ./activate' and then 'chia init' to begin

$ . ./activate 

(venv) [ss@ss-desktop chia-blockchain]$ sh install-gui.sh 
install-gui.sh: line 17: type: apt-get: not found
install-gui.sh: line 21: type: yum: not found
install-gui.sh: line 26: type: yum: not found

Running git submodule update --init --recursive.

Submodule 'chia-blockchain-gui' (https://github.com/Chia-Network/chia-blockchain-gui.git) registered for path 'chia-blockchain-gui'
Cloning into '/home/ss/rpmbuild/SPECS/chia-blockchain/chia-blockchain-gui'...
Submodule path 'chia-blockchain-gui': checked out '8d702e857e673f635223b2bbb6549c8e786dbda9'
Running git submodule update.

install-gui.sh: line 82: npm: command not found <--

**Comment by mariano54** [comment]
Can you try version 1.0.3 and report if that works?

**Comment by Chewbakka-Wakka** [comment]
On 1.0.3, same error.
