### ISSUE TITLE
[BUG] Win10 - "Only wrote 7 of 4194297 bytes at offset 4194297 to..."

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [Chia-Network/chia-blockchain#1567]
On this 1.0.1 rel. Using the GUI in Win 10.

This process seems much slower than expected, but continues to run and will eventually write, but not without many of these errors, for each of the plot.p1.t1.sort_bucket_069.tmp files. - I am using a system with fast storage and the remote M:\ location is an NFS server with SSD on that mount. 

Can I decrease that 5 min delay? Why is this writing so few bytes?

Starting plotting progress into temporary dirs: M:\ and M:\
ID: 184ed99abf66aaff1c54a475e72ebfa4c3b2c3fe1f4d3a0867b111408c25820a
Plot size is: 32
Buffer size is: 64608MiB
Using 128 buckets
Using 12 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Mon Mar 29 21:08:38 2021
Computing table 1
Only wrote 7 of 4194297 bytes at offset 4194297 to "M:\\plot-k32-2021-03-29-21-08-184ed99abf66aaff1c54a475e72ebfa4c3b2c3fe1f4d3a0867b111408c25820a.plot.p1.t1.sort_bucket_069.tmp"with length 4194304. Error 1. Retrying in five minutes.

When using 1 thread again as a test :

Only wrote 0 of 4194297 bytes at offset 0 to "M:\\plot-k32-2021-03-29-21-14-557b4792fbe208b34b6c4f2badd182c005fb52dffbabd884969ed1b37bafffbb.plot.p1.t1.sort_bucket_049.tmp"with length 0. Error 1. Retrying in five minutes

Repeats everytime.

**Comment by hoffmang9** [comment]
This is a hardware issue on your machine.
