### ISSUE TITLE
Node sync issue [Bug] 

### ISSUE THREAD

**Issue by jasg060261** [Chia-Network/chia-blockchain#15674]
### What happened?

After updating chia networks to version 1.8.2, the node is no longer synchronized, it appears in red, and the parcels appear as unavailable, although it does detect them, as well as the amount of the wallet that is ok. I have no way to make the plots appear green as farming, they stay yellow as permanently unavailable.

### Version

1.8.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by hbroer** [comment]
Logs?

**Comment by jasg060261** [comment]
These are the screenshots:
https://drive.google.com/file/d/1NhYCol_gmxLNkW2oREp67gAmEvMZXH2B/view?usp=drive_link
https://drive.google.com/file/d/1_TTC1SeHXnAkTK30zxGbif4qzYfEXnN5/view?usp=drive_link
https://drive.google.com/file/d/1Y8ysb1yFSADNG18do49KmJ8j4x8aZv5w/view?usp=drive_link

**Comment by jasg060261** [comment]
> Logs?

https://drive.google.com/file/d/1NhYCol_gmxLNkW2oREp67gAmEvMZXH2B/view?usp=drive_link
https://drive.google.com/file/d/1_TTC1SeHXnAkTK30zxGbif4qzYfEXnN5/view?usp=drive_link
https://drive.google.com/file/d/1Y8ysb1yFSADNG18do49KmJ8j4x8aZv5w/view?usp=drive_link

**Comment by hbroer** [comment]
That are screenshots, not the log file output. It is normaly located in `~/.chia/mainnet/log/debug.log `

**Comment by whooamiii** [comment]
Same error here, it's frustrating cause I'm syncing my chia client since February, accidentally deleted chia db and had to start from 0, syncing is so Fin slow even with port 8444 open, for six months have this "Syncing 2,328,098/3,889,043"

**Comment by jasg060261** [comment]
Thanks Hauke.

Apparently everything is back to normal after two or three days with
the node out of sync. Finally a while ago after deleting mainnet and
recovering an older one, it started to sync again.


[image: Icono de Validado por la comunidad]

**Comment by whooamiii** [comment]
I cannot afford deleting of mainnet folder, don't have older one, this one is 88gb and it took 6 months to sync that 88gb...

**Comment by hbroer** [comment]
If you kill the db or it is broken for what ever reason you can download a checkpoint it via torrent and start from there:
https://www.chia.net/downloads/#database-checkpoint

**Comment by whooamiii** [comment]
Thank you, I will try with that.

**Comment by wjblanke** [comment]
hope it is working now, if not reopen a new issue. thx!
