### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jasg060261** [Chia-Network/chia-blockchain#15673]
### What happened?

Tras actualizar chia networks a la versión 1.8.2 el nodo ha dejado de estar sincronizado, aparece en rojo, y las parcelas figuran como no disponibles, aunque sí las detecta, igual que la cantidad del wallet que está bien. No tengo forma de hacer que las parcelas aparezcan en verde como cultivando, se quedan en amarillo como no dospibles de forma permanente.

### Version

1.8.2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
closing as duplicate of 15674
