### ISSUE TITLE
[Bug] RPC cmd cancel_offers doesn't work

### ISSUE THREAD

**Issue by nongyehezuoshe** [Chia-Network/chia-blockchain#15739]
### What happened?

The RPC : [cancel_offers](https://docs.chia.net/wallet-rpc#cancel_offers)  doesn't work.
just do nothing.

### Version

1.8.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by Quexington** [comment]
It seems very uncharacteristic for it to do _nothing_.  Are you getting any sort of response or is it hanging or what exactly is the behavior you are seeing?

**Comment by nongyehezuoshe** [comment]
sorry for that.
I am use：
`chia rpc wallet cancel_offers '{"secure": false}'` 
and, return :
``` bash
{
    "success": true
}
```
but, `chia rpc wallet get_all_offers '{"include_completed":false}'` return many offers, so, the `cancel_offers ` doesn't  `cancel` any offer.

**Comment by BrandtH22** [comment]
Hey, just catching up on this. It seems the end result is to cancel all of the offer files associated with the wallet. 
If so, you will want to use the `cancel_all` boolean (ex. `chia rpc wallet cancel_offers '{"cancel_all": true}'`).

This boolean defaults to false which makes the standard behavior to cancel 5 offers (based on the `batch_size` parameter) and all 5 nee to be xch related (based on the `asset_id` variable). Without more context as to what offer files were active prior to and after running the command it seems this might be the case.

Lastly, I generally recommend cancelling offers onchain (`secure` boolean left at default true) to ensure that no one can take those offers in the future ( if the offer is 30 USDS for 1 XCH and someone has that offer they can still take it until those 30 USDS have been spent in some way).

Let us know if this is not the case or if you have additional followup questions but if you want to cancel all offers I recommend using the command at the top of this message then you will need to wait for the block confirmations for them to be cancelled (can add fees to expedite the process if blocks are near full)

**Comment by zimocode** [comment]
@BrandtH22 you are right, ths

**Comment by nongyehezuoshe** [comment]
@BrandtH22 you are right, ths
