### ISSUE TITLE
Problems claiming self-pooling rewards

### ISSUE THREAD

**Issue by a397184189** [Chia-Network/chia-blockchain#15737]
2023-07-14T00:19:03.872 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'DOUBLE_SPEND', 'status': 3, 'txid': '0x0afd82725bd781bf7a013f48e616633027152896acf812a8fd0dfa479fb42240'}

To solve the dual cost problem of Chia, you can try the following steps:

Waiting for network confirmation: Before taking any action, wait enough time for the network to confirm your transaction. Sometimes, the entire node requires more time to verify transaction information.

Check transaction history: Check the transaction history in your wallet software to ensure that you have not attempted two or more transactions using the same currency at the same time. If you find any abnormal transactions, please repair or delete them.

Resynchronizing the wallet: Sometimes, there may be problems during the wallet synchronization process, resulting in incorrect balance or transaction information being displayed. Try resynchronizing your wallet to keep it consistent with the network.

Contact Technical Support: If you still encounter dual cost issues or are unsure about resolving the issue, we suggest that you contact Chia official support or the developer team of the wallet software you are using for professional assistance and guidance.

The reward has been applied for 2 days but has not been received yet. The bill shows that it is currently being processed

Solo CooperatiThe reward has been applied for 2 days but has not been received yet. The bill shows that it is currently being processed

![image](https://github.com/Chia-Network/chia-blockchain/assets/19707344/636b093d-27c9-4385-9c0a-45a4cd5eac91)
![image](https://github.com/Chia-Network/chia-blockchain/assets/19707344/557e5c3e-6556-488d-8cce-2b8165875bce)

**Comment by shaneo257** [comment]
What happens when you click on the Actions button in the Tokens screen, and click on delete unconfirmed transactions?

**Comment by a397184189** [comment]
When deleting an unconfirmed transaction and reapplying it, this operation still cannot be performed. Farming is also normal, but applying for rewards cannot reach the account. I think there is a mistake in my Agricultural cooperative. I want to contact the administrator, but I can't reach them. I am very anxious. Please help me take a look. Thank you.
