### ISSUE TITLE
Bladebit Cuda - Low Proofs Ratio [Bug] 

### ISSUE THREAD

**Issue by FFurno** [Chia-Network/chia-blockchain#15747]
### What happened?

I have created a few uncompressed plots (-z 0) using bladebit cuda (various alpha versions, latest 4.4). The plots look okay and are recognized when farming, but if I run `chia plots check` I get very low ratios despite high `-n` (<0.4). I have win 11, rtx 3080 10gb, a threadripper 1900x, x399 mobo with 256gb ram ddr4. I used chia blockchain 1.8 to check the plots.

### Version

1.8

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
you could try 2.0.0-b5 and see if uncompressed cuda plots result in better proof ratios. for further assistance reach out to discord

**Comment by Ron-ski** [comment]
I've also noticed this, I sometimes get invalid partials, and when checking the logs I find the following, which includes a plot ID.

ERROR Invalid proof of space <plot ID>

When I checked the plots, I get a lot of the following warnings.

WARNING     Quality doesn't match with proof. <Plot path> This can occasionally happen with a compressed plot.

And the ratios are very low.

```
073a9fba4d7d71924ee031dcf46c0af6e8253e1027bc0fd550bff56a1a5bb14a	        = Proofs 9 / 60, 0.15	
7679b2f0838ecdd830e4e7f072dcb05359acd419bf643530153d93ef29c47f9b	= Proofs 5 / 60, 0.0833
a0e27263db5c6c0f45c4b69bffe2249df3d34c8379291c69b2cf742d2b913cb8	        = Proofs 14 / 60, 0.2333
b7abc6feae8d16022f5ab5c0acc0ab7cc20e7c4229a93ade919dee768f5a658b	        = Proofs 16 / 60, 0.2667 
2095ab1561a17d60d4471652ed17703dee05a8897a6715ef7463305a65e4434a	= Proofs 22 / 60, 0.3667
25a1fafd5f44f8d27473e8a1b33adfafc7b58868ab7acf5a30d840b47ffd0746	        = Proofs 14 / 60, 0.2333	
40d8b4630405f737ce0374a37b17f1e8bb81b32b0e7cb2774c437825446cba9d	= Proofs 13 / 60, 0.2167		
09484bfe789caea3ad37a1d826793b98fd0bff675e4b4869fbd48bea90a831fe	        = Proofs 17 / 60, 0.2833
6baf8079269b71d38be544181f25988f5f9c39ca4af00537a182104a8602cec7	= Proofs 24 / 60, 0.4	
```
None of the above plots were deemed invalid, but I've now replaced them, and will see if I get any more errors/invalid partials.

These were plotted on Windows 11, using a 3080 and Bladebit Alpha 4.3
Farmed on Windows 10 on the GUI

**Comment by mjoach** [comment]
I've been trying to find out why the pool underestimates the size of my C7 farm by about 10-15%. I identified hundreds of low proof-ratio plots and replotted them, it helped, but the size is still underestimated. So I did a histogram from 30 challenges test on all plots (slow!). It is not centered on 30, so I think it suggests that it is not just a few bad plots, but rather, I was generating plots with various percentages of invalid proofs and right now I don't see an easy way to identify them. Plotted with Alpha 4.3/4.4/4.5 on Ubuntu 22.04.

<img width="480" alt="plotscheck30" src="https://github.com/Chia-Network/chia-blockchain/assets/31162599/ab4f9c3b-91ba-4e2f-8465-39cd1a9a421a">

**Comment by jmhands** [comment]
we do we want to follow up on this, thanks again for getting the data. From what I can gather with a large sample size (thousands) you really shouldn't be getting under say, 97-98%. But we have no explanation of how this could happen and plot still be not corrupt. We will take a look

**Comment by mjoach** [comment]
Thanks, good to hear. I have seen at least 2 other users report an average of 28/30 for their farms on the Discord channel. So either a plots check specific bug or something potentially more serious, plotting related. Myself, I have never found out why my C7 farm's size is underestimated by the pool, though this could still be related to using GTX 1070 for farming and twice-daily harvester crashes/GRResult errors. Plotting and the above plots check were however all done on 3090.

**Comment by FFurno** [comment]
Tried to plot uncompressed with newly released bladebit 3.0. Same problem as before. Plots are recognized as valid but only have 30-40% valid proofs in Win 11.

**Comment by jmhands** [comment]
I reproduced this internally, but it has a very low occurrence rate. Will be following up on this soon
https://github.com/Chia-Network/bladebit/issues/393

**Comment by llowrey** [comment]
I opened a ticked the other day about non-reproducible plots: https://github.com/Chia-Network/bladebit/issues/390

It seems that `cudaplot` does not produce the same plot data every time when the plot id (seed) is the same (by specifying the plot id using the `-i` parameter when plotting). For `diskplot` the plots are always the same (except for a small bit in the header). Since the point of the `-i` parameter is to reproduce plots, they must be fully deterministic given the plot id. The fact that `cudaplot` does not produce the same contents for a given plot id is concerning.

**Comment by FFurno** [comment]
I have also tried to produce compressed -z 5 plots using bladebit cuda 3.1 beta on the same Threadripper platform described above. Proofs are close to zero, plots are detected as invalid.

**Comment by emlowe** [comment]
I believe the original report was fixed by https://github.com/Chia-Network/bladebit/pull/410

closing
