### ISSUE TITLE
Coverage TODO for compression

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#15750]
```
Failure. Coverage is below 100%.
-------------
Diff Coverage
Diff: origin/main...HEAD, staged and unstaged changes
-------------
chia/harvester/harvester.py (80.0%): Missing lines 104-106
chia/harvester/harvester_api.py (0.0%): Missing lines 140-142,145,150-151,155
chia/plotting/check_plots.py (0.0%): Missing lines 5,58-65,67,191-192,194,210-213,215-216
chia/plotting/manager.py (64.7%): Missing lines 89,94,105,321,327-328
chia/simulator/setup_services.py (100%)
-------------
Total:   59 lines
Missing: 35 lines
Coverage: 40%
-------------
```

_Originally posted by @arvidn in https://github.com/Chia-Network/chia-blockchain/pull/15702#discussion_r1260428165_

_https://github.com/Chia-Network/chia-blockchain/pull/15702#discussion_r1260428766_

_https://github.com/Chia-Network/chia-blockchain/pull/15702#discussion_r1260429360_

_https://github.com/Chia-Network/chia-blockchain/pull/15702#discussion_r1260429908_

_https://github.com/Chia-Network/chia-blockchain/pull/15702#discussion_r1260430177_

_https://github.com/Chia-Network/chia-blockchain/pull/15702#discussion_r1260431010_

_https://github.com/Chia-Network/chia-blockchain/pull/15702#discussion_r1260431407_

**Comment by emlowe** [comment]
Moving to Jira for tracking -
