### ISSUE TITLE
[Bug] Chia v1.8.2rc6.dev114 only farming uncompressed plots!

### ISSUE THREAD

**Issue by toto99303** [Chia-Network/chia-blockchain#15756]
### What happened?

Hello,

After upgrading to v1.8.2rc6.dev114 the SpacePool started reporting drastically lower farm size!
"chia farm summary" command reports the correct size, everything looks normal.
Turns out it's farming only the leftover uncompressed plots... Please investigate!

Thanks!

### Version

v1.8.2rc6.dev114

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by BrandtH22** [comment]
Problem was solved with the recent alpha version update and confirmed in discord:
![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/a695fd5a-7220-498a-bdc7-b18b1e9ab25f)
