### ISSUE TITLE
[Bug] space.pool not displaying full farm size

### ISSUE THREAD

**Issue by softwareuser99** [Chia-Network/chia-blockchain#15789]
### What happened?

As of this and one or two prior releases, there seems to be a problem that space pool is NOT showing the correct farm information when it comes to the plots. Space Pool normally displays the estimated farm size in TiB, which is usually within 5-10% of the real space occupied.

**Encountered behaviour:**

- Local farm shows correct number of plots in the pooling tab
- Difficulty and points levels as well successful % (100%) seem normal.
- When accessing the space pool web ui, only around **40%** of the farm seems to be recognized.
- Valid partials are at 100%
- no firewall settings or any other external network factors have been altereed

**Expected behaviour:**
Space Pool would show roughly the same amount of TiB as main farm, discounting for compressed space of Cx plots
I've been using Space Pool for over 1.5 years and never encountered this issue, which is why I presume there is something in the code of this release that is causing this.

**Environment:**

- 5 harvesters, 1 main farm
- Ubuntu 22.04 on all machines.
- 100% C7 plots, no OG plots
- All machines running the version in question
- All machines using GPU harvesting (also reocgnized in the GUI of the main farmer)
- During upgrade, all .chia folders were deleted and recreated with chia init
- SSL certificates were re-propagated in the LAN and installed with chia init -c ca

### Version

2.0.0b5-dev76

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
no errors being shown, simply encountering this significant discrepancy.
```

**Comment by wjblanke** [comment]
Can u try the 2.0.0-b5 build. it has compression integrated in now. let us know

**Comment by jmhands** [comment]
can you update to rc6 and do a `chia plots check` on a sample of at least 10 plots (preferably on SSD so they go faster) and report back?
