### ISSUE TITLE
[Bug]  Remove_uncofirmed_transaction command

### ISSUE THREAD

**Issue by adlos96** [Chia-Network/chia-blockchain#15792]
### What happened?

hi, on first forry for my bad english **^.^**

i have an a full node installed for mining this coin, i try to learn and study **C#** for comunication on chia network, but have some problem if i try to delete an a transaction maked using **C#** or **cmd** on windows...

if i try to delete it on pending status noting happening, the transaction included normally on blockchain, why that?

i dont understand how to solve it, i have try using **GUI** directly for delete it but same results.

if I use **GUI** to delete a transaction, it is removed from the graphical view, but if we wait a little bit, we see that, chia coins are subtracted, including transaction on blockchain.

what is it that I am doing wrong?

Command tested:
- **chia wallet delete_unconfirmed_transactions** 
- **chia wallet delete_unconfirmed_transactions -f xxxx1xxxx**

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
this is output on cmd - cli mode
Successfully deleted all unconfirmed transactions for wallet id 1 on key xxxx1xxxx
```

**Comment by wjblanke** [comment]
When u delete a transaction from the GUI it removes it from the wallets understanding of pending transactions so it won't retry sending it to the mempool. but chances are, its already been submitted to the mempool and eventually could find its way into the blockchain at which time it is there for eternity. this really only works for transactions that have been rejected by the mempool and u dont want to retry them

**Comment by adlos96** [comment]
creating a transaction via cli command
chia wallet send chia wallet send -a xch_amount -m xch_fee -f wallet_send -i 1 -t wallet_recive

and requesting the cancellation of the transaction 2 seconds after the confirmation of the request, is the transaction included in the mempool? how much should be the delay time between the command and the delete request?
i rember time of block creation is aroud 18.75s (i cant rebember if is it a normal block or transaction block on this time (18.75s))

if i chois to use only cli command or cmd istruction
