### ISSUE TITLE
MacOS Big Sur Not synchronizing

### ISSUE THREAD

**Issue by hoofin22** [Chia-Network/chia-blockchain#1580]
**Describe the bug**
3 spinning circles on the full node tab. I was able to complete my plotting but the (now completed) plots won't farm as the farming status reads "wait for synchronization".
In 'advanced options' both the 'Your Harvester network' and 'Full Node Connection' status is "connected".
I have refreshed and reloaded the plots, I have closed and re-openned Chia, and I have restarted my machine - without success and the same issues (above) persists.
Any thoughts/suggestions to try to resolve please?

![112759214-0973aa00-8fc0-11eb-9a7c-0548c6aedf8b](https://user-images.githubusercontent.com/81606909/112959312-55efee80-9154-11eb-9e3f-7e5a8b9fbbbc.png)

**Expected behavior**
To  synchronize and for the Plots to begin Farming

**Desktop (please complete the following information):**

- OS: Mac OS Big Sur
- OS Version/Flavor: 1.0.1 (latest version)
- CPU: Mac Mini M1

**Comment by hoffmang9** [comment]
Please try this experimental version - https://download-chia-net.s3-us-west-2.amazonaws.com/tests/Chia-1.0.4-rc1.dmg

**Comment by hoofin22** [comment]
Thank you - I've installed this version however the same problem persists

**Comment by hoofin22** [comment]
> Please try this experimental version - https://download-chia-net.s3-us-west-2.amazonaws.com/tests/Chia-1.0.4-rc1.dmg


Thank you - I've installed this version however unfortunately the same problem persists
Originally as part of this issue, the plotting stalled and I deleted the plots (both directly deleting via the chia GUI, and then the .tmp files from the disk that had already been written). Could this have caused this issue? If so, how can we resolve this conflict?

**Comment by mariano54** [comment]
Yes that could have been the issue. GUI plotting has been causing instability in the daemon for some reason.

**Comment by hoofin22** [comment]
This is still outstanding - no resolution. I was plotting on my MacBook Pro as well and now this is affected too. It's been 2 weeks now... anything else I can do here? I'm completely stuck

**Comment by hoffmang9** [comment]
Fixed.
