### ISSUE TITLE
[Bug] 2.0 RC2 Netspace Inaccuracies

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#15906]
### What happened?

Version 2.0 RC2 is displaying a slightly higher netspace than other versions and than that which is displayed on the official chia dashboards.

- No errors are in the logs related to this.
- Reported on Ubuntu 22.04
- CLI and GUI both show the slightly higher netspace

![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/7cb5b248-5956-41b0-b74e-6a76e81e541f)
![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/07a9ab9c-e191-49ef-ba0a-0a7d1eed526f)

Reported on discord (https://discord.com/channels/1034523881404370984/1102690350218354920/1135647745156329532) by Conan.

### Version

2.0 RC2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
NA
```

**Comment by wjblanke** [comment]
We are investigating

**Comment by wjblanke** [comment]
We've updated the constants to correct the netspace value.

**Comment by esaung** [comment]
@wallentx - update release notes for 2.0
