### ISSUE TITLE
Swap Choose Plot and Plot to a Plot NFT on Plotting Screen [Enhancement]

### ISSUE THREAD

**Issue by shaneo257** [Chia-Network/chia-blockchain#15902]
### What happened?

On the Plotting Scrren, can we have Plot to a Plot NFT and Choose Plotter swapped, as when you go through the current way, if when you chose a different plotter from the drop down after chosing your plot NFT, it clears the plot NFT
So it should be 

Step 1: Choose Plotter
Step 2: Plot to a Plot NFT

### Version

2.0.0RC2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
We will take a look

**Comment by jmhands** [comment]
@ChiaMineJP has fixed this
