### ISSUE TITLE
[Bug] 2.0 RC2 Estimated Time to Win Inconsistencies

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#15904]
### What happened?

When users farm compressed plots their estimated time to win will become inconsistent and change constantly (from a few seconds to multiple days).

It seems the client has difficulty in determining true farming space and calculating the estimated time to win from that.

Example images are from a few seconds after one another:
![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/0335f1bb-53b5-48a6-9864-ae480c3d48c2)

![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/6db495bd-f7ca-48e7-8917-7399617ba630)

side note- this user has 1 harvester that reports to the full node from these images

Reported in Discord (https://discord.com/channels/1034523881404370984/1102690350218354920/1135625524509675711) by dachshundad.

### Version

2.0 RC2

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
no errors or warnings present in the logs
```

**Comment by BrandtH22** [comment]
Secondary user with the same experience (estimation is jumping from 1 day , to 3, 6, 7 and back):
2 harvesters with GPU in ubuntu 22.04. 
- Ryzen 7 5700x
- 32Gb RAM  (the full farmer with a nvidia a2000 and the harvester with a nvidia 1650)
- All c05 plots, around 850TiB every one

Reported via Discord (https://discord.com/channels/1034523881404370984/1102690350218354920/1135635775577411605) by Conan.

**Comment by BrandtH22** [comment]
Additional user reported same issue occurs on windows 10 builds (https://discord.com/channels/1034523881404370984/1102690350218354920/1135678834331627691)
Reported by Chi A Coyote

**Comment by ChiaMineJP** [comment]
Currently estimated time to win is calculated like this:
```
proportion = effective_farm_size / total_netspace
average_block_time = (newer_block.timestamp - older_block.timestamp) / (newer_block.height - older_block.height)
estimated_time_to_win = average_block_time * proportion
```
From those screenshots, `effective_farm_size` and `total_netspace` is consistent/stable.
So incostency might be introduced by `average_block_time`.

In order to inspect current average block time, run this command:
`chia rpc full_node get_blockchain_state`
