### ISSUE TITLE
[Bug]  GUI bladebit_cuda doesn't work currently 

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#15945]
### What happened?

The GUI currently forces us to specify a temp directory, but the current 256gb cudaplot throws an error if you specify a temp for for 256gb plots:
```
Generating plot 1 / 1: bf43aa0a1fd485183a010d39c2c91b7b5a98774081b2b68cdc277d5df90248d8
Plot temporary file: -t1/plot-k32-c07-2023-08-05-19-24-bf43aa0a1fd485183a010d39c2c91b7b5a98774081b2b68cdc277d5df90248d8.plot.tmp


Fatal Error:
Failed to open plot file with error: 2
```
It should be noted that for some reason, on windows this makes the folder in the target temp directory `read-only`

### Version

2.0.0-rc3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
The GUI side alerady fixed this issue.
https://github.com/Chia-Network/chia-blockchain-gui/pull/1972

We need to update the GUI submodule ref in `chia-blockchain` side to build a new installer.

**Comment by bramv-chia** [comment]
fixed in RC4
