### ISSUE TITLE
Internal drive used in Windows lost some plots in Lubuntu

### ISSUE THREAD

**Issue by IssaEgvi** [Chia-Network/chia-blockchain#1594]
I hooked up one of my internal drives to Raspberry Pi 4 running Lubuntu and it didn't recognize it from the get go (unlike my external drives, I assume it's all about NTFS/FAT32).
I found a possible fix and ran the ntfsfix command on it.
It was working but out of 17 plots on the drive Chia only recognized 11 (labeled others as irregular).
So I figured I'll put that drive back on Windows but Windows can't see it because it's now a Dynamic drive.

Then I used both Raspberry and TestDisk software to copy the drive's contents to another drive and they yielded the same result - 11 normal sized plots, several with size 0 and several with sizes 40-70Gb.

If ntfsfix messed up this disk is there some other command I can use to un-mess it or should I just make peace with lost plots and format it?

**Comment by hoffmang9** [comment]
I don't think anyone on the development side has a good idea. Better to ask on Keybase in eg #plotting-hardware
