### ISSUE TITLE
Farming Rewars suddenly stop

### ISSUE THREAD

**Issue by TschiAR** [Chia-Network/chia-blockchain#1596]
Hi there, 

I am plotting since July in my Home Office. Some of my friends too at their places. We all have about 20 TB Plots (everybody)

Last week it suddenly stopped with the rewards at my place. Since Friday there are no new rewards incoming.
It shows „Farming "status, the plots are green and plotting and everything is fine. There is no sleep mode etc. everything is just fine!!!

One of my friends ist now plotting for 14 days and has no XCH reward. 
So I asked him to give me his key and his plots.

I installed chia on my second laptop (OSX) and I started to sync and plot with his stuff… and suddenly it shows me 4 XCH???

So I just want to report: At my friends home the chia software was not showing any rewards. When I installed it on my MacBook it shows me his farmed rewards ( Old ones: Confirmed at height 25965)

So i am wondering if we all have more XCH but can not see them in the chia software?

Sorry for my bad English - I hope you understand.

Best regards

**Comment by ayaseen** [comment]
Strange! It needs someone to check this behavior. I am wondering if this is happening to me also :)

**Comment by TschiAR** [comment]
Hi, at the moment 4 of my 5 friends have the same problem. Since friday no new rewards. Wallet and Node is synct. Alle plots are green and farming. Expected time to win is "2 days" by all of us.. now is day 5

**Comment by mariano54** [comment]
It might be a problem of wallet DB not being synced, so you can't see rewards.

Stop chia (even on task manager)
Delete the ~/.chia directory
Restart computer
Start Chia again

Hopefully you will see rewards.
If your plots are going through the plot filter, you are farming correctly.

**Comment by ayaseen** [comment]
Do we have to add the keys again?

**Comment by TschiAR** [comment]
Hi, thanks for your help.

@mariano54: i just did what you wrote yesterday but nothing changed. It shows farmin since friday with 20 TB Plots. nothing happened. No rewards. 

Can someone please post a tutorial here on how to check plots on windows?
the chia software shows all plots are green and farming.

**Comment by TschiAR** [comment]
> 
> 
> It might be a problem of wallet DB not being synced, so you can't see rewards.
> 
> Stop chia (even on task manager)
> Delete the ~/.chia directory
> Restart computer
> Start Chia again
> 
> Hopefully you will see rewards.
> If your plots are going through the plot filter, you are farming correctly.

Hi, thanks for your help.

@mariano54: i just did what you wrote yesterday but nothing changed. It shows farmin since friday with 20 TB Plots. nothing happened. No rewards.

Can someone please post a tutorial here on how to check plots on windows?
the chia software shows all plots are green and farming.

**Comment by TschiAR** [comment]
> 
> 
> Do we have to add the keys again?

i did not enter my key again after deleting the .chia directory

**Comment by mariano54** [comment]
This is normal, there is a high amount of variability in rewards, I think nothing is wrong here.
