### ISSUE TITLE
[Bug]  Error to load compress plot to client chia 1.8.2v:  

### ISSUE THREAD

**Issue by sbc-juangomez** [Chia-Network/chia-blockchain#16009]
### What happened?

I plot 222 compres plots, and will to load on chia client view next error in log:
![image](https://github.com/Chia-Network/chia-blockchain/assets/140556397/bcbcf50f-3632-4c43-b61c-0aee7413afb0)
and the log:
![image](https://github.com/Chia-Network/chia-blockchain/assets/140556397/ac98d764-add3-423c-a06c-e8d1e8b0e593)

version chia:
![image](https://github.com/Chia-Network/chia-blockchain/assets/140556397/82b2673a-85a2-44a0-80fc-5e3578cf69f2)

### Version

1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-08-10T08:34:52.953 harvester chia.plotting.manager   : ERROR  
  Failed to open file J:\plots\plot-k32-c8-2023-08-09-16-38-2042a0bdef83d78780ba1f4994cd428894c00f1ef827ecac20632b3080fc24cd.plot. 
  Invalid plot file format Traceback (most recent call last):
  File "chia\plotting\manager.py", line 274, in process_file
ValueError: Invalid plot file format
```

**Comment by TheSpearman** [comment]
1.8.2 doesn't support compressed plots. You need one of the 2.0.0 versions instead.

**Comment by ukd1** [comment]
@TheSpearman where can you find that?

**Comment by TheSpearman** [comment]
That's them. Please note these are still pre-release versions, and still have issues and may need a little extra work or config changes to get going.

**Comment by BrandtH22** [comment]
For more updated information about compressed plotting and harvester I recommend joining the discord server and keeping an eye on the bladebit-beta channel. There is an overview of the current status and release builds in the pinned message in that channel:
https://discord.com/channels/1034523881404370984/1099818017908592660/1103477864998895730

Since you have the correct build now, do you have any followup questions or are we good to close out this ticket?

**Comment by sbc-juangomez** [comment]
How long do you think it takes for the release version of chia v2 to come out?

**Comment by shaneo257** [comment]
could be a few weeks
you can use it now, but it could have bugs to be ironed out, here is the latest https://github.com/Chia-Network/chia-blockchain/releases/tag/2.0.0-rc4

**Comment by bramv-chia** [comment]
Closing issue; v1.8.2 does not support compressed plots.
