### ISSUE TITLE
[Bug] calling get_routes over WebSocket fails

### ISSUE THREAD

**Issue by dkackman** [Chia-Network/chia-blockchain#16016]
### What happened?

Using the WebSocket via the daemon, and invoking the `get_routes` endpoint from the shared rpc_server class results in this error:

`TypeError: get_routes() takes 1 positional argument but 2 were given`

The same call, invoked via Https works as expected.

### Version

1.8.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-08-11T09:15:52.618 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 328, in ws_api
TypeError: get_routes() takes 1 positional argument but 2 were given
```

**Comment by bramv-chia** [comment]
@dkackman could you provide the command line / CURL arguments you are using ?

**Comment by dkackman** [comment]
> @dkackman could you provide the command line / CURL arguments you are using ?

I am making the call with a dotnet wrapper (https://github.com/dkackman/chia-dotnet). It works for other endpoints but this one fails oddly, but only over wss. An edge case I'm sure.

This is the payload:

```
{
    "command": "get_routes",
    "data": {},
    "origin": "unit_tests",
    "destination": "chia_full_node",
    "ack": false,
    "request_id": "9FBCE907DBF1F7198C0352915CD89E8D2D804421E288BD5E484406D8ADD6177F"
}
```

**Comment by paninaro** [comment]
@dkackman This isn't a regression, right?

The daemon is different from the other chia services in that its API is only exposed over wss. In versions older than 1.8.2, the `chia rpc` CLI wasn't able to call any daemon APIs. So in 1.8.2, I added support for calling daemon APIs, but it's definitely a different beast than the other chia services since the daemon isn't implemented as an RpcServer.

Here's an example where the CLI decides how to call an RPC: https://github.com/Chia-Network/chia-blockchain/blob/main/chia/cmds/rpc.py/#L18-L23

Example calling `get_routes` on the daemon:

```
$ wscat -n --cert ~/.chia/mainnet/config/ssl/daemon/private_daemon.crt --key ~/.chia/mainnet/config/ssl/daemon/private_daemon.key -c wss://0.0.0.0:55400
> { "command": "get_routes", "data": {}, "origin": "unit_tests", "destination": "daemon", "ack": false, "request_id": "9FBCE907DBF1F7198C0352915CD89E8D2D804421E288BD5E484406D8ADD6177F" }
< {"ack": true, "command": "get_routes", "data": {"routes": ["start_service", "start_plotting", "stop_plotting", "stop_service", "is_running", "running_services", "is_keyring_locked", "keyring_status", "unlock_keyring", "validate_keyring_passphrase", "set_keyring_passphrase", "remove_keyring_passphrase", "exit", "register_service", "get_status", "get_version", "get_plotters", "get_routes", "get_wallet_addresses", "get_keys_for_plotting"], "success": true}, "destination": "unit_tests", "origin": "daemon", "request_id": "9FBCE907DBF1F7198C0352915CD89E8D2D804421E288BD5E484406D8ADD6177F"}```

Did calling `get_routes` over wss work previously?

**Comment by dkackman** [comment]
> @dkackman This isn't a regression, right?
> 
> The daemon is different from the other chia services in that its API is only exposed over wss. In versions older than 1.8.2, the `chia rpc` CLI wasn't able to call any daemon APIs. So in 1.8.2, I added support for calling daemon APIs, but it's definitely a different beast than the other chia services since the daemon isn't implemented as an RpcServer.
> 
> Here's an example where the CLI decides how to call an RPC: https://github.com/Chia-Network/chia-blockchain/blob/main/chia/cmds/rpc.py/#L18-L23
> 
> Example calling `get_routes` on the daemon:
> 
> ```
> $ wscat -n --cert ~/.chia/mainnet/config/ssl/daemon/private_daemon.crt --key ~/.chia/mainnet/config/ssl/daemon/private_daemon.key -c wss://0.0.0.0:55400
> > { "command": "get_routes", "data": {}, "origin": "unit_tests", "destination": "daemon", "ack": false, "request_id": "9FBCE907DBF1F7198C0352915CD89E8D2D804421E288BD5E484406D8ADD6177F" }
> < {"ack": true, "command": "get_routes", "data": {"routes": ["start_service", "start_plotting", "stop_plotting", "stop_service", "is_running", "running_services", "is_keyring_locked", "keyring_status", "unlock_keyring", "validate_keyring_passphrase", "set_keyring_passphrase", "remove_keyring_passphrase", "exit", "register_service", "get_status", "get_version", "get_plotters", "get_routes", "get_wallet_addresses", "get_keys_for_plotting"], "success": true}, "destination": "unit_tests", "origin": "daemon", "request_id": "9FBCE907DBF1F7198C0352915CD89E8D2D804421E288BD5E484406D8ADD6177F"}```
> 
> Did calling `get_routes` over wss work previously?
> ```

Honestly not sure. I'm just rounding out some unit tests for completeness sake so can't say for sure it's a regression. (also meaning this isn't urgent from my perspective)

What happens in your wscat test if you use `full_node` as the destination? That's the only difference I can see between our examples.

**Comment by paninaro** [comment]
I did a bit of digging and found that `get_routes` probably has never worked when called over the websocket connection (https works, as originally reported).

What *does* work currently is calling `_get_routes`, as that method is defined in a manner compatible with the calling convention used by APIs accessible over the websocket connection.

I'm testing an experiment with PR #16103 to see if anything blows up by simply switching things around.

**Comment by dkackman** [comment]
yeah i suspect noone has ever tried it before :) and I'm just doing it cause it's there! If it proves problematic it wouldn't impact anything I'm doing to remain unfixed.
