### ISSUE TITLE
[Bug] Datalayer Propagation Server Fails to start, Prevents Client from loading

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#16036]
### What happened?

When the chia client attempts to start the Datalayer Propagation Server it fails to do so causing the client to continually spin while loading.

Steps to reproduce:
1. Download the latest dev version
2. Enable the file propagation server (will need to enable datalayer also)
3. Close the client and reopen it (client will fail to load and will continually spin on "Starting Services...DataLayer File Propagation Server" 
![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/021c2f32-a93e-435b-8139-a953d1290e97)

This was initially reported by nanofarmer in discord (https://discord.com/channels/1034523881404370984/1034870571864948777/1140724141394251827) and reproduced by Brandt H

Logs attached: 
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/12339768/debug.log)

- Logs were deleted prior to testing
- Datalayer and propagation server were enabled before testing
- Logs show at ~3:27 local time the client was launched, the client was left spinning at Starting services for 5 minutes then at ~3:32 local time the client was closed.

Notes:
- There are no issues running the datalayer server and propagation server via cli
- The logs appear to have no errors or warnings and seem to indicate the propagation server launches correctly even though the GUI is still spinning
- I believe this is likely an error in the frontend receiving confirmation that the server has started and therefore not correctly loading

### Version

2.0.1b2-dev25

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by nanohtpc** [comment]
Problem remains on dev34, temporal solution....

downgrade to dev12
or
disable data layer on config.yaml

remember ....
do daily backups 8)

**Comment by BrandtH22** [comment]
Another user (ClumsyLulz) confirmed this issue with the latest dev install and grabbed an error from the dev tools:
![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/cb38b753-014d-4982-a780-1bd353d61139)

More context in discord regarding this second report:
https://discord.com/channels/1034523881404370984/1034870571864948777/1149840710263119882

**Comment by BrandtH22** [comment]
Additional information from ClumsyLulz:
![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/ed73e790-c272-46f4-abe9-635fa621b119)

```
C:\Users\Clumsy>chia wallet show
Error: Connection error: ClientConnectorError: Cannot connect to host localhost:9256 ssl:<ssl.SSLContext object at 0x0000026F8D53E840> [The remote computer refused the network connection]
Check if wallet rpc is running at 9256
This is normal if wallet is still starting up
```

**Comment by paninaro** [comment]
I'll take this. We'll special case the service startup logic in the GUI to handle the DataLayer HTTP service being, a little different...

**Comment by paninaro** [comment]
GUI fix will be in 2.1.0-rc2 or later builds

**Comment by nanohtpc** [comment]
BTW... in the 2.0.1-rc1.. i just have to disable that option to make the wallet loads.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by SleepTheGod** [comment]
> Additional information from ClumsyLulz: ![image](https://private-user-images.githubusercontent.com/48610606/266746729-ed73e790-c272-46f4-abe9-635fa621b119.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTU3MjksIm5iZiI6MTczNjE1NTQyOSwicGF0aCI6Ii80ODYxMDYwNi8yNjY3NDY3MjktZWQ3M2U3OTAtYzI3Mi00NmY0LWFiZTktNjM1ZmE2MjFiMTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA5MjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWViMzFjNDU1NDVlMDMxZjYyNTRlMGEzY2VkMTY2MDNjOWI0NjcwM2YwNDM2ZTUxMjRmNmRjNTY1Zjg5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ZX5JmpiuA_fXlPk6L7VAEmeosGUaOgG-WtfiGIyP_U)
> 
> ```
> C:\Users\Clumsy>chia wallet show
> Error: Connection error: ClientConnectorError: Cannot connect to host localhost:9256 ssl:<ssl.SSLContext object at 0x0000026F8D53E840> [The remote computer refused the network connection]
> Check if wallet rpc is running at 9256
> This is normal if wallet is still starting up
> ```

Yes I did confirm that
