### ISSUE TITLE
[Bug] VCs - unable to update proofs to a VC that has been issued to a holder

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#16049]
### What happened?

VC issuer wallet has minted a VC to the holder's wallet. The holder's wallet is able to see the VC in their wallet.

The VC issuer now wants to update the proofs associated with that VC to make it valid VC. Getting an error when running the CLI command. Tried using both the LauncherID and the CoinID for the VC coin, but command fails.

![Screenshot 2023-08-15 at 1 26 04 PM](https://github.com/Chia-Network/chia-blockchain/assets/93196638/14536934-c1ca-45de-8eff-084d804cb8b5)

### Version

2.0.0rc4

### What platform are you using?

macOS

### What ui mode are you using?

CLI

### Relevant log output

```shell
`(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs update_proofs -l dfd860d692f2fe034653de1255c3b614ef4c3221ee66e8d7f3fed5e84e4df263 -p ac04b2f39be8adbaee0eadb8859cb88e28173fa84cd6a9a658ca98ea6678be8c -m 0.00005

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 EasyFoodHandlers.com (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   County Demo wallet (Issuer)
21) * 87074341     Issuer.com (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Exception from 'wallet' {'error': "Verified credential dfd860d692f2fe034653de1255c3b614ef4c3221ee66e8d7f3fed5e84e4df263 doesn't exist.", 'success': False}:
Traceback (most recent call last):
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 110, in get_any_service_client
    yield node_client, config
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 226, in get_wallet_client
    yield wallet_client, new_fp, config
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/wallet_funcs.py", line 1444, in spend_vc
    txs = await wallet_client.vc_spend(
  File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 1254, in vc_spend
    response = await self.fetch(
  File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': "Verified credential dfd860d692f2fe034653de1255c3b614ef4c3221ee66e8d7f3fed5e84e4df263 doesn't exist.", 'success': False}

(venv) esaung@Chia-Macbook chia-blockchain-gui % chia wallet vcs update_proofs -l dfd860d692f2fe034653de1255c3b614ef4c3221ee66e8d7f3fed5e84e4df263 -p ac04b2f39be8adbaee0eadb8859cb88e28173fa84cd6a9a658ca98ea6678be8c -m 0.00005 -t f2a8d0e68eac92fdac40796b989d181189908db6996ff9a234f946ac673b0c44

Active Wallet Key (*):
   -Fingerprint:           87074341
   -Label:                 Issuer.com (Issuer)
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   County Demo wallet (Issuer)
21) * 87074341     issuer.com (Issuer)
Choose a wallet key [1-21] ('q' to quit, or Enter to use 87074341): 
Exception from 'wallet' {'error': "Verified credential dfd860d692f2fe034653de1255c3b614ef4c3221ee66e8d7f3fed5e84e4df263 doesn't exist.", 'success': False}:
Traceback (most recent call last):
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 110, in get_any_service_client
    yield node_client, config
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/cmds_util.py", line 226, in get_wallet_client
    yield wallet_client, new_fp, config
  File "/Users/esaung/Github/VC/chia-blockchain/chia/cmds/wallet_funcs.py", line 1444, in spend_vc
    txs = await wallet_client.vc_spend(
  File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 1254, in vc_spend
    response = await self.fetch(
  File "/Users/esaung/Github/VC/chia-blockchain/chia/rpc/rpc_client.py", line 61, in fetch
    raise ValueError(res_json)
ValueError: {'error': "Verified credential dfd860d692f2fe034653de1255c3b614ef4c3221ee66e8d7f3fed5e84e4df263 doesn't exist.", 'success': False}

(venv) esaung@Chia-Macbook chia-blockchain-gui % `
```

**Comment by Quexington** [comment]
This is expected: to update the proofs you need to be the holder of the VC.  The correct flow for a VC issuer is to mint it to their wallet, add the proofs, then send it to the user.  It's not impossible conceptually to have the user generate half the transaction and the issuer to provide the other half, but this is not something we support right now.

**Comment by esaung** [comment]
but if the user can update the proofs to anything they want, don't you lose the meaning of the issuer who has the done the verification and issued the VC?

also I tried updating the proofs as the VC holder (issuer did is not owned by this wallet) , and I get the following error message:

esaung@test-macbook-pro daemon % ./chia wallet vcs update_proofs -p b30092e3a2ad6c2132b1bc011e44ab0810b459f24c38b08d6ad7248cb788cb9b -m 0.00005 -l 0x8a465850faca6f10c9becf3217df0b12c91ffd455e63de01a1215317d9ab2968

Active Wallet Key (*):
   -Fingerprint:           4263116386
   -Label:                 Alice VC wallet demo
   -Sync Status:           Synced

Exception from 'wallet' {'error': 'VC could not be updated with specified DID info', 'success': False}:
Traceback (most recent call last):
  File "chia/cmds/cmds_util.py", line 110, in get_any_service_client
  File "chia/cmds/cmds_util.py", line 226, in get_wallet_client
  File "chia/cmds/wallet_funcs.py", line 1444, in spend_vc
  File "chia/rpc/wallet_rpc_client.py", line 1254, in vc_spend
  File "chia/rpc/rpc_client.py", line 61, in fetch
ValueError: {'error': 'VC could not be updated with specified DID info', 'success': False}

**Comment by Quexington** [comment]
Right, as you've seen when testing this, you need BOTH the VC and the issuer DID.  It's possible in the future for VC holders to sign partial transactions and then send it to the DID holder for authorization but we didn't have this in scope yet.

**Comment by esaung** [comment]
ok, I thought the VC issuer would be able to updated the proofs at any point in time regardless if it's in the same wallet as the Issuing DID or in the holder's wallet. This way if there's a format change, or an additional verified data/proof to be added, the issuer can remotely add it to the on-chain coin without the holder needing to do any additional work. Much like how revoking from the Issuer side just removes the proofs from the on-chain VC coin.

So for the current implementation of VCs - if proofs for the same VC need to be updated, the expected process by the issuer would be: 1.) revoke current VC, 2.) issue new VC to same receiving wallet with new proofs, does that sound about right?
