### ISSUE TITLE
[Bug] Cleanup output of `chia data get_root_history`

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#16042]
### What happened?

The output of `chia data get_root_history` is not JSON and is currently difficult to parse and read.

example:
```
❯ chia data get_root_history --id 88603ccd663c14473b2676df9f44d2363be3795dc3b2d9b85e122dd9fc62e217
{'root_history': [{'confirmed': True, 'root_hash': '0x0000000000000000000000000000000000000000000000000000000000000000', 'timestamp': 1678987617}, {'confirmed': True, 'root_hash': '0x0154334ba66919db6634069220165baec8a57de10832920d7e81a20c96ef2aa3', 'timestamp': 1678987836}, {'confirmed': True, 'root_hash': '0x028e5509235f688bbfb5b7975963ae8ce94fe509282d84fdfc3aed2edcf87cc3', 'timestamp': 1678990608}, {'confirmed': True, 'root_hash': '0x189c669a741a96908a44780c424eebae561b77450e7bf3c66a9212c35004e748', 'timestamp': 1682977436}, {'confirmed': True, 'root_hash': '0x64e5def469689dbc80342e3f269a9b97ee083652a23a7e925661cd4491a95813', 'timestamp': 1683057379}], 'success': True}
```

Proposed changes:
- [ ] Change default to output legal JSON
- [ ] pretty print JSON

Optional/Unsure:
- [ ] add pagination? (generally one can pipe to other tools)
- [ ] convert timestamp to human readable?

### Version

all

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
N/A
```

**Comment by altendky** [comment]
I'd vote that the JSON should just be the JSON (indented pleasantly).  A secondary (or primary) human readable output that is tweaked would be separate, at least for now.  Pagination should be left to existing OS tools generally.  At least if all it is going to do is CLI tweaks.  If we're avoiding requests to the backend, then sure, `less` can't help there.
