### ISSUE TITLE
[Bug] VCs - can not revoke a VC that I hold but I am not the issuer

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#16048]
### What happened?

Getting an error in the GUI when trying to revoke a VC that was issued to me from a separate key.
![Screenshot 2023-08-15 at 11 54 50 AM](https://github.com/Chia-Network/chia-blockchain/assets/93196638/4d27129b-c9ac-4cb3-b8f7-e5e5283f4fbd)

### Version

2.0.0 rc4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by Quexington** [comment]
@esaung can you confirm the fix and close this if so?

**Comment by esaung** [comment]
fixed in what I tested, thanks!
