### ISSUE TITLE
[BUG] Full Node Status stay Not Synced, after stop and start UI

### ISSUE THREAD

**Issue by babiboo** [Chia-Network/chia-blockchain#1605]
**Describe the bug**
After I stop UI (version 1.0.0), updated to version 1.0.1 and start again, Full Node Status stay {last 7 hours} in state "Not Synced" with no progress. After one hour without reaction, I restarted the system, but still without change.

**To Reproduce**
I really have no idea how this can be reproduced :(

**Expected behavior**
Status should be "not synced" only if I'm offline (and here it should show when was the last time I was synced). If I'm online, the status should be "syncing" along with information about the status, or maybe "network error" or something similar with an explanation of what to do.

I'm not sure if it's possible for my system to get up and running, or it will stay that way forever.

The minimum you can do is to **create a recommended repair procedure** for such cases (after system restart / or in syncing problems). Publish estimated sync times (is 7 hours without any response still okay, or is it already a lot?), and **publish it on a wiki or blog**.
It would be good to write into this article how to bring the application to its initial state in the worst case.

**Screenshots**
![01](https://user-images.githubusercontent.com/79306780/113049614-210b8800-91a4-11eb-8a0c-093814e6d91c.png)
Last record in Blocks section is 7 hours old.
Connections show two records both from 127.0.0.1, 0.0/0.0 MiB Up/Down
Wallet with port 50320/8449 and Farmer with port 50322/8447.
Wallets is in status "not synced", height: 54723, connections: 1.
Farm Overview showing status "Not Available", and there is no records in Last Attempted Proof and Latest Block Challenges.

Chia process doesn't do anything, sometimes it writes something to disk. the system is not busy at all, it does not communicate over the network.
![02](https://user-images.githubusercontent.com/79306780/113050953-bc512d00-91a5-11eb-9371-9d72a65de2ac.png)

After checking C:\Users\<user>\.chia\mainnet directory. Only file changed in last hours is `db/peer_table_node.sqlite` (last change one hour ago), all other files are 7 hours old.

**Desktop (please complete the following information):**
- OS: Windows
- OS Version/Flavor: 10

**Additional context**
I checked other bug reports here, but elsewhere the problem is that it is small different in other bug reports (I don't see the spinner or the syncing state as in other bug reports).

**Comment by Fintal78** [comment]
I have the same issue with Chia version 1.0.1 and Windows 10.
It also indicated Not synced and does nothing for more than one day now, even after closing and restarting my computer ...

**Comment by babiboo** [comment]
Tested with version 1.0.3 (after almost 5 hours still in "Not Synced" state)
![a](https://user-images.githubusercontent.com/79306780/113139818-e3e8d980-9227-11eb-8a47-7d104b731f9a.png)

Chia process do nothing
![b](https://user-images.githubusercontent.com/79306780/113140192-5c4f9a80-9228-11eb-9965-7ea432edc237.png)

**Comment by Fintal78** [comment]
same here again with version 1.0.3. Pretty annoying that there is absolutely no feedback from the interface about a potential issue.

**Comment by babiboo** [comment]
I think it will be a network problem.
At the time of the first reboot, someone was working on some network reconfiguration. I don't know exactly what happened, but one of the routers was probably replaced.

On a computer on which synchronization did not work, I tried to configure vpn outside my primary local network and since then synchronization has started (very, very slowly, but it is already caused by VPN).

The strange thing is that the fact that the chia GUI reports that it is "Connected" probably does not mean that everything that is needed is actually available. I assume that the term connected means only the availability of the Internet.

This raises two questions for me:

1. Can anyone say **exactly what** (in terms of network settings) **is needed for farming** (especially in terms of network settings)?

2. It is possible to modify the GUI so that **in case it detects a network error, it does not report** the Connection status **only as "Connected"** but "Only internet" or something similar (something that will really help identify the problem), with displaying a help link or describing where the problem is and how it can be get around?

**Comment by mariano54** [comment]
Syncing should start within the first 15 minutes of launching it. If it does not start, something is wrong, so stop the program. 
Things to try:
1. Disable upnp in the chia config.yaml file
2. Delete the ~/.chia/mainnet/wallet/db directory
3. Check task manager for any chia related program (or full_node, or daemon), and shut it down
4. Restart computer
5. Change log level from WARNING to INFO in the config file, and send me the config file (in private keybase message) after running chia for 15 minutes

Also please post your copmuter specs here.

**Comment by babiboo** [comment]
Thanks for the reply mariano 🤗.
Is it not possible for the GUI to perform these tests and repair attempts automatically (of course, except for the restart 😄) ... or, inform user what to do next instead of simple "Connected" state? And only if this known procedure does not help did it need any further intervention...

The current state is that I did steps 2, 3 and 4, which didn't help and now unfortunately I can't do any more tests. What exactly do you need from my system specification, can I display them somehow via the GUI menu and copy here? If the basic info posted down is enough, then I currently use this Ubuntu for farming. Chia 1.0.3 is installed according to the latest procedure for version 1.0.3.

![1](https://user-images.githubusercontent.com/79306780/113419723-4f69ad00-93c8-11eb-8554-d46000b7a2af.png)
![2](https://user-images.githubusercontent.com/79306780/113419729-52649d80-93c8-11eb-90e0-a7fbd1108cbc.png)

**Comment by Fintal78** [comment]
I uninstalled Chia and then made a search on my computer of all files/directories containing "Chia" and removed all of them manually. Then I restarted my computer installed Chia again and after some time it started syncing. And it is still syncing, so it seems to work for now.

**Comment by Fintal78** [comment]
well it synced, synced ... until it reached the current date and then it just went to "Not Synced". So I am in the same spot with no information at all. Pretty disappointing how it all goes, especially since I bought a drive especially for this ...

**Comment by Fintal78** [comment]
I did the steps mentioned by mariano and it is still not syncing. I had no issues until I few days ago, on testnet and mainnet 1.0, so I really don't think it is related to the computer. It should indicate something, not just "Not Synced". It failed just before it was synced so there might be an issue when switching mode between "syncing" to "synced"

**Comment by mariano54** [comment]
Did you try checking the time on your computer? If the time is not synchronized it would cause it to show Not Synced

**Comment by Fintal78** [comment]
oh indeed. I forced the time of my computer to sync and now everything is OK, back to farming :-)
End of March was time change, that probably explains the issue. Thanks, this issue should be documented or handled somehow with an alert. Hope the problem will be solved for babiboo too.

**Comment by mariano54** [comment]
Great! I'll add it to the FAQ

**Comment by babiboo** [comment]
No, none of the above solutions helped me.

I **performed all the steps that Mario wrote**, I also **checked the current time** (it updates automatically).
The Chia GUI is still in the **"Not Synced" and "Connected"** state, but nothing is changed even after few hours.

I continue to say that this will be some type of network problem.
The router behind the computer is completely in my administration, everything is allowed there, but the router above is managed by a company administrator. There are supposed to be only allowed common types of ports (even if everything works normally on the computer - http, https, ftp, ssh, sftp...).

Don't you have any more information for me about **what needs to be allowed**, or **what other can I try** to fix it?

**Is it possible to run a command (something like ping) to verify that the computer running the Chia GUI can communicate with the addresses that contain the data it needs to synchronize?**

**Comment by dompie** [comment]
@marion54
This is very unusual (from the end users point of view) to have to synchronize the time on windows manually. My watch was just synced alsmost 1 hour ago via ntp and chia could not start. Then I pressed "sync now" on the windows Date and Time settings and chia status changed immediatly to "Synced" again and peers started connecting.

**Comment by hoffmang9** [comment]
If your machine time is wrong the software can't determine if it has recent blocks. Keep your computer time accurate and you will be fine.

**Comment by dompie** [comment]
@hoffmang9 My time was perfectly accurate. Can you tell if your system clock is 1 second off sync?

By default windows checks time automatically every hour by ntp. If this is not accurate enough, then chia should set up it's own time system and not pushing users in doing that manually. Most people just don't know there is ntp and do not know where to keep it accurate. And they will tell you that time is accurate - nobody will know if the system clock is 1 second before or behind the time that chia-network expects.

**Comment by hoffmang9** [comment]
You only need to be within a couple minutes of the correct time.

**Comment by joelrb** [comment]
This is still a problem in v1.1.5. I just restarted the router (power off/on) and it no longer syncing. Forced reload many times already still no sync. I can browse websites so internet connection is fine. What a pain.
