### ISSUE TITLE
[Bug] Plots with k-size > 35 aren't cached

### ISSUE THREAD

**Issue by neurosis69** [Chia-Network/chia-blockchain#16063]
### What happened?

The current cache implementation is not allowing plots with a k-size > 35 being cached, due to false positive classification in this condition: 
https://github.com/Chia-Network/chia-blockchain/blob/d36703337a9164ad36ab15772e85ae2cf7ebfc34/chia/plotting/cache.py#L159-L169

I obviously don't know the reasoning why the check is implemented this way and why we even want to exclude certain plots from the caching. But as it is mentioned in the code, plots with k-size > 35 are classified as false-positives, so I guess the if condition can be tweaked somehow.

For my plots with a k-size > 35, I've simply removed this check as a workaround to allow such plots getting cached.

I've also logged the prover size for plots with k-sizes up to 38, maybe this can help some of the devs to adjust the condition?
In our pool we have also farmers with plot sizes > 38, up to 40 I think. If it helps, we can also try to get the prover size for these k-sizes.

| k_size | est_c2_size | memo size | hardcoded | sum (est_c2_size + memo size + hardcoded) | prover size |
|--------|-------------|-----------|-----------|--------------------------------------------|-------------|
| 32     | 172         | 112       | 2000      | 2284                                       | 738         |
| 33     | 356         | 112       | 2000      | 2468                                       | 1083        |
| 34     | 732         | 112       | 2000      | 2844                                       | 1771        |
| 35     | 1505        | 112       | 2000      | 3617                                       | 3147        |
| 36     | 3096        | 112       | 2000      | 5208                                       | 5899        |
| 37     | 6875        | 112       | 2000      | 8987                                       | 11395       |
| 38     | 13081       | 112       | 2000      | 15193                                      | 22395       |

### Version

1.8.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Thanks for the detailed report!

**Comment by emlowe** [comment]
Closing fixed - will be included in the next release off main a PR has been merged
