### ISSUE TITLE
[Bug] decompressor_timeout on RC5 have no effect

### ISSUE THREAD

**Issue by mmitech** [Chia-Network/chia-blockchain#16086]
### What happened?

After upgrading to the latest RC5 and adding the decompressor_timeout to the config file, changing values to any value doesn't make any difference. I've tried changing the value from 20 up to 300 but it doesn't seem to have any effect, I always have a similar amount of plots excluded/timed out.

![image](https://github.com/Chia-Network/chia-blockchain/assets/4456920/1664d962-955e-4e5a-b07b-7f6350fc2ddd)
![image](https://github.com/Chia-Network/chia-blockchain/assets/4456920/2e04bc07-aff9-443c-b13b-2d7202ed5d05)

### Version

2.0.0-rc5

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by jmhands** [comment]
fixed in rc6
