### ISSUE TITLE
Bug 1.0.2 Cant add plot directory

### ISSUE THREAD

**Issue by pauliedi** [Chia-Network/chia-blockchain#1612]
Upon launch get pop warning "13" and ok button. Directories are erased from GUI. When I go to add back in I get a pop up warning. "13" with an ok button. Offline and cant get back on.

**Comment by pauliedi** [comment]
<img width="128" alt="Capture033121" src="https://user-images.githubusercontent.com/79347951/113089377-8c118a80-91b5-11eb-9cb1-c2b5602387ad.PNG">

**Comment by hoffmang9** [comment]
One of your plot directories in config.yaml has a problem.
