### ISSUE TITLE
Chia Blockchain 2.0.0rc6 on CentOS 8 Stream ERROR Proofs 0 / 30, 0.0 [Bug] 

### ISSUE THREAD

**Issue by bjct42** [Chia-Network/chia-blockchain#16123]
### What happened?

Hello,

After installing Chia Blockchain 2.0.0rc6 on CentOS 8 Stream I created C7 compressed plots. The creation goes well but the plots do not appear in the GUI. After a Chia Plots Check I have the error:
WARNING  Not farming compressed plot /mnt/local/temp1/plot-k32-c07-2023-08-20-12-20-xxxxxxxx.plot. Plot compression level: 7, because parallel_decompressor_count is set to 0 in config.yaml. Use a non-zero value to start harvesting compressed plots.
I change the value of "parallel_decompressor_count" from 0 to 7 in config.yaml file and restart the creation of new pads. The new plots appear in the GUI without errors, but after a Chia Plots Check I have the error:
2023-08-20T13:15:35.577  chia.plotting.check_plots        : ERROR    	Proofs 0 / 30, 0.0 Filepath: /mnt/local/temp1/plot-k32-c07-2023-08-20-12-26-xxxxxxxx.plot.

Thank

### Version

Chia Blockchain 2.0.0rc6

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
hi bjct42,

could you try the steps listed here, https://github.com/Chia-Network/chia-blockchain/issues/16098 in particular to the `parallel_decompressor_count` from 0 to 1

**Comment by bjct42** [comment]
I change the value of "parallel_decompressor_count" from 7 to 1 in config.yaml file and restart the creation of new plots, but after a Chia Plots Check I have the same error:
2023-08-20T13:15:35.577 chia.plotting.check_plots : ERROR Proofs 0 / 30, 0.0 Filepath: /mnt/local/temp1/plot-k32-c07-2023-08-20-12-26-xxxxxxxx.plot.

**Comment by jmhands** [comment]
ERROR Proofs 0 / 30 - This is a corrupt plot, just delete it. Please use Bladebit 3.0 release and check. You really only need 1 or 2 parallel decompressors

**Comment by bjct42** [comment]
After update to chia-blockchain-2.0.1b2-1 and install bladebit_cuda 3.0.0 alpha4 from https://downloads.chia.net/bladebit/alpha4.4/bladebit-cuda-plotter, i have the same result

2023-08-21T20:22:23.367  chia.plotting.check_plots        : ERROR    <class 'RuntimeError'>: Destination buffer is too small error in getting challenge qualities for plot /mnt/local/temp1/plot-k32-c07-2023-08-21-20-04-xxxxx.plot
2023-08-21T20:22:23.367  chia.plotting.check_plots        : ERROR    	Proofs 0 / 30, 0.0 Filepath: /mnt/local/temp1/plot-k32-c07-2023-08-21-20-04-xxxxx.plot

**Comment by jmhands** [comment]
need to be on RC6 and Bladebit 3.0, sorry it is confusing but chia-blockchain-2.0.1b2-1 is for the next release and intended for testnet only

**Comment by bjct42** [comment]
1.	Remove all install of chia
2.	Install rc6 : rpm -ivh ./chia-blockchain-2.0.0rc6-1.x86_64.rpm
3.	Copy db and bladebit_cuda 3.0.0 alpha4 
4.	Change parallel_decompressor_count: 0 to 1 in config.yaml
5.	Start chia
6.	Create plots error :
Creating plotters folder within CHIA_ROOT: /home/bruno/.chia/mainnet/plotters
Error: /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda: /opt/chia/resources/app.asar.unpacked/daemon/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda)
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda: /opt/chia/resources/app.asar.unpacked/daemon/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda)
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda: /opt/chia/resources/app.asar.unpacked/daemon/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda)
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda: /opt/chia/resources/app.asar.unpacked/daemon/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda)

7.	For solve : 
              cp -rf /usr/lib64/libstdc++.so.6 /opt/chia/resources/app.asar.unpacked/daemon/
8.	Create plots start 
9.	check error : chia.plotting.check_plots : ERROR Proofs 0 / 30, 0.0

**Comment by jmhands** [comment]
this is the 3.0 release you want, not the alpha version
https://github.com/Chia-Network/bladebit/releases/tag/v3.0.0
https://github.com/Chia-Network/bladebit/releases/download/v3.0.0/bladebit-cuda-v3.0.0-centos-x86-64.tar.gz

**Comment by bjct42** [comment]
I found the solution
1.	Remove all install of chia
2.	Install rc6 : rpm -ivh ./chia-blockchain-2.0.0rc6-1.x86_64.rpm
3.	Copy db
4.	Change parallel_decompressor_count: 0 to 1 in config.yaml
5.	Start chia
6.	creation of plots with the command bladebit_cuda -f xxx -c yyy -z 7 -n 1 -t 8 -v cudaplot /mnt/local/temp2/ not command  chia plotters bladebit cudaplot -f xxx -c yyy --compress 7 -n 1 -r 8 -v -d /mnt/local/temp1/
7.     check plots ok
