### ISSUE TITLE
[Bug] Information Disclosure via Exposed RSA Keys in Chia Authentication Endpoint

### ISSUE THREAD

**Issue by SleepTheGod** [Chia-Network/chia-blockchain#16158]
### What happened?

Report Title: Information Disclosure via Exposed RSA Keys in Chia Authentication Endpoint

Reported by: [Taylor Christian Newsome | ClumsyLulz]

Target URL: https://chia.okta.com/oauth2/v1/keys

Summary:

During a security assessment of the Chia blockchain platform, an exposed RSA keys issue was identified in the authentication endpoint. This vulnerability could potentially allow attackers to abuse the exposed keys for malicious purposes.

Vulnerability Details:

Description:

An insecurely exposed RSA keys issue was identified in the authentication endpoint of the Chia blockchain platform. The endpoint at https://chia.okta.com/oauth2/v1/keys contains JSON data that includes RSA key pairs. This sensitive information could potentially be used by attackers to perform cryptographic attacks and other malicious activities.

Exposed Keys Data:
{
   "keys":[
      {
         "kty":"RSA",
         "alg":"RS256",
         "kid":"eT8jyGToCmTehKWmnl97uyVvRPFGO9DMvaerSm6sPUw",
         "use":"sig",
         "e":"AQAB",
         "n":"1AQeRuQZaaIUJDPVsE3Q4Z3svKDpqfVR-TvimOXjQN4cdkeD4eOT1cjEHRC--bWxmM9-bCutYIw9onVkj_5cWxGf31eiIvcWJLSs99cGbjCu_ywaHjifGcdShFwLPHT78VnRcEJ4axw8sdb17pbqKOFxXsOkwlJp3egRqctDbaINNXnwmQogSzGzbuZQaouP90DTNokvLyBixs0xe8Sgds0bjDUwDkJ02c7jRbK1BdBLUW1tODOYl1ZHeF-YyDwNapEcKiCFczxoK0FxDYpTIQVDu01aJs41kwrlLurrp963KEUpNtNy_8uU6m1hWH_PBhoEjfdB-rNomZ7vLW879Q"
      },
      {
         "kty":"RSA",
         "alg":"RS256",
         "kid":"dhxmfpldNcZMZyigg5IrDBQUkCsNFx1u5or__6PLBQU",
         "use":"sig",
         "e":"AQAB",
         "n":"zjuaYhKokV2qm1me9ueaKNJnru7mXUEfJKJAfTswiRmbSNU16hRjNDjU3798jQ5Glhw2jE6rgYt1idMgefRouz4Q6FbwhGlNa0MXvKGXR8O6akjMEvUHHdA4PH-dcJ_f0ETXuSb8ir4TQmCM8B_Z1yeY0R6p391WR6PptFAttmRlIuyIFwXnjw_ZP7A2WlBKiJgstkdLWBeGYCeTjLbWBGmOeVbZw9XXuHwJQVbAf2mmX6umxmKtPidXKBeGbBO2uqxiw-UUIHa1njM5rHLy-5cWc0mNOx5kc1fDCq174foCqEMvVr9QVgdlfc1ueg8zhmDXZx48dHHWMMdT5FBkVQ"
      }
   ]
}

Vulnerability Type:

Information Disclosure

Affected Endpoint:

https://chia.okta.com/oauth2/v1/keys

Attack Scenario:

An attacker could potentially abuse this vulnerability to gain access to the exposed RSA keys. With these keys, attackers could perform cryptographic attacks, impersonate legitimate users, and potentially bypass authentication and authorization mechanisms in the Chia blockchain platform. This could lead to unauthorized access, data breaches, and other security incidents.

Steps to Reproduce:

Access the endpoint at https://chia.okta.com/oauth2/v1/keys.
Observe the exposed RSA key pairs in the JSON response.
Impact:

This vulnerability poses a serious risk to the security of the Chia blockchain platform. Exposing RSA key pairs could allow attackers to impersonate legitimate users, perform unauthorized actions, and potentially compromise the integrity of the platform's cryptographic mechanisms.

Mitigation:

To mitigate this vulnerability, Chia should:

Securely manage and store RSA keys to prevent unauthorized access.
Review and modify the affected endpoint to ensure that it does not expose sensitive information.
Implement access controls and authentication mechanisms to restrict access to sensitive endpoints.
Regularly audit and monitor the platform for exposed sensitive information.

### Version

Current

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Thank you for your report.
However, you are mistaken.

This endpoint is expected to return PUBLIC keys in JWK format for verifying JWTs. See the okta API here: https://developer.okta.com/docs/reference/api/oidc/#keys and the JWK spec here: https://datatracker.ietf.org/doc/html/rfc7517

The format for the JWK public key includes the modulus "n" and the public exponent "e" as is expected for an RSA public key.
The format for the private key would include the private exponent "d" - which is not present in the returned JSON.

This is entirely expected and normal.

**Comment by emlowe** [comment]
For future reference, if you think you found a security issue, please report it confidentially via bugcrowd

see https://bugcrowd.com/chia-network-bb

**Comment by SleepTheGod** [comment]
Thank you for informing me
