### ISSUE TITLE
[Bug] Every update make the pool nft KO

### ISSUE THREAD

**Issue by Tocard** [Chia-Network/chia-blockchain#16166]
### What happened?

This is the third update I'm doing, each time, My farm is not working anymore because of NFTPLOTS.

The step to reproduce is

install from rpm a version X.
create nft plots, create N plots & start farming.
update to version X+1.

You will see this

```shell
$ chia plotnft show
Wallet height: 4138753
Sync status: Synced
Current state: FARMING_TO_POOL
Current state from block height: 3985665
Launcher ID: *******************************************************
Target address (not for plotting): ************************************************
Number of plots: 0 # here is the errors, should me the number of plot N from the text above
Owner public key: ********************************************
Pool contract address (use ONLY for plotting - do not send money to this address): ******************************
Current pool URL: *************
Relative lock height: 64 blocks

```

The only way to make it work again is to manually delete wallet db and restart chia.

```shell
$ chia plotnft show
Wallet height: 4138753
Sync status: Synced
Current state: FARMING_TO_POOL
Current state from block height: 3985665
Launcher ID: *******************************************************
Target address (not for plotting): ************************************************
Number of plots: 1604 # here is the errors, should me the number of plot N from the text above
Owner public key: ********************************************
Pool contract address (use ONLY for plotting - do not send money to this address): ******************************
Current pool URL: *************
Relative lock height: 64 blocks
```

### Version

2.0.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
[chia@centaur-alpha db]$ chia version
2.0.0
[chia@centaur-alpha db]$ cat /etc/redhat-release
Fedora release 37 (Thirty Seven)
[chia@centaur-alpha db]$ yum info chia-blockchain-cli.x86_64
Last metadata expiration check: 0:00:37 ago on Sat 26 Aug 2023 12:57:16 AM CEST.
Installed Packages
Name         : chia-blockchain-cli
Version      : 2.0.0
Release      : 1
Architecture : x86_64
Size         : 402 M
Source       : chia-blockchain-cli-2.0.0-1.src.rpm
Repository   : @System
From repo    : chia-blockchain-stable
Summary      : Chia is a modern cryptocurrency built from scratch, designed to be efficient, decentralized, and secure.
URL          : http://example.com/no-uri-given
License      : Apache-2.0
Description  : Chia is a modern cryptocurrency built from scratch, designed to be efficient, decentralized, and secure.
```

**Comment by BrandtH22** [comment]
This is likely due to changes that occur to the config file itself (this is where the pool information is stored). 
When updated it is generally recommended to have a new config file created but this also requires that either the pool information is manually added to the config or that the wallet is fully synced from scratched for it to identify the necessary plot NFT coin.

**Comment by wjblanke** [comment]
Number of plots does not require the plot nfts. it sounds like the plot refresh needs more time to complete or maybe is having issues? can you attach your DEBUG log file or the output of chia farm summary. Is your pool showing that you are not farming these plots?

**Comment by Tocard** [comment]
> Number of plots does not require the plot nfts. it sounds like the plot refresh needs more time to complete or maybe is having issues? can you attach your DEBUG log file or the output of chia farm summary. Is your pool showing that you are not farming these plots?

I think I deleted the plot to see what was going on, but next time i will do an update, I will post it.

Yes the pool was making me offline just after the update, until the wallet has been deleted & restored
