### ISSUE TITLE
[Bug] Update to 2.0.0 does not apply some config

### ISSUE THREAD

**Issue by Tocard** [Chia-Network/chia-blockchain#16167]
### What happened?

After upgrading to 2.0.0, some props are not updated on config file. And (I'm using rpm) the update does not provide new config file to proceeed upgrade.

For example, this line was not present into the config file.

```
  parallel_decompressor_count: 0

```

To get the new config, I had to generate a new config wich is not ideal.

### Version

2.0.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by BrandtH22** [comment]
This is as expected, updates do not add information to the config and it is recommended that the config file is recreated with major new versions that have config changes. 

The eng team has been looking into optimizations for the config file to help with this but those will not be available until a future release.

Would it be appropriate to convert this issue ticket into a feature request for these config optimizations?

**Comment by wjblanke** [comment]
closing as per above. there are setting in the GUI to change these options. no reason to edit config.

**Comment by Tocard** [comment]
@wjblanke LMAO, 

What ui mode are you using?
CLI
