### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Floyd6531** [Chia-Network/chia-blockchain#16178]
### What happened?

startup did not port but login after window closed 

### Version

2.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
hi floyd6531
could you clarify the issue you're experiencing

**Comment by Floyd6531** [comment]
yes

**Comment by wjblanke** [comment]
Without more details we can't help. Please resubmit if you have more information.
