### ISSUE TITLE
Chia 2.0.0: Harvester on Win 11 does not send plots to farmer   

### ISSUE THREAD

**Issue by otto0158** [Chia-Network/chia-blockchain#16170]
### What happened?

The farmer is running on a Cloud VPS (Ubuntu 22.04, Chia 1.8.2).
Farmer is a Windows 11 PC running Chia 2.0.0 using IPv6 address of the VPS.

If I run "watch chia farm summary" I can see for a short time the IPv6 of the harvester and 0 plot, then the lines disappear and the process starts over.
If I return the PC to 1.8.2 all is ok.

Is this a bug or does 1.8.2 and 2.0.0 not work together?

### Version

2.0.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
1.8.2 and 2.0.0 have a number of differences that can most certainly lead to incompatibilities.
I recommend updating the harvester to 2.0.0 and having a new config created.

Do note that you will also likely need to run the `chia init -ca [directory]` command on the harvester again :+1:

**Comment by wjblanke** [comment]
with 2.0 you must update harvester farmer and node lockstep
