### ISSUE TITLE
GUI on 2.0.0 is missing GPU relevant settings and features

### ISSUE THREAD

**Issue by scoville07** [Chia-Network/chia-blockchain#16173]
### What happened?

After updating from 1.8.2 to 2.0.0 chia gui does not show the option "Enable GPU harvesting", in the dropdown menu for the available plotters "Bladebit CUDA" is simply missing. (farmer is Windows10, Xeon E5-2697v4, 64GB RAM, RTX3060 12GB, driver and CUDA up to date, running with gigahorse node fine)

### Version

2.0.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
the chia client 2.0.0 requires a system to have at least 256gb of ram, lower ram requirements will be enabled in a future release

**Comment by BrandtH22** [comment]
Also when upgrading to 2.0.0 you need to have a new config created by:

1. Stop chia
2. Rename the config or move it to a different directly
3. In CLI run `chia init`
4. Copy any custom settings from the old config to the new (plot drive directories, pool info, trusted node info, etc) - be careful here as yaml is very picky about formatting including those leading spaces
5. Start Chia

Side note - we can generally provide more thorough and timely support on our discord server: https://discord.gg/chia)

**Comment by wjblanke** [comment]
Closing as per above comment
