### ISSUE TITLE
[Bug] Transaction History incomplete

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#16180]
### What happened?

given the following example:

- Have the same wallet fingerprint on two computers.
- create an offer which is selling a cat token and taking xch in exchange
- accept the offer from another fingerprint
- pull transactions for the cat wallet on the other computer than where the offer was created

Wallet balance result:
```
Wallet height: 3110514
Sync status: Synced
Balances, fingerprint: 3011902820

Chia Wallet:
   -Total Balance:         1.1 txch (1100000000000 mojo)
   -Pending Total Balance: 1.1 txch (1100000000000 mojo)
   -Spendable:             1.1 txch (1100000000000 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1

DataLayer Wallet:
   -Total Balance:         0.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DATA_LAYER
   -Wallet ID:             2

BTF:
   -Total Balance:         1.9  (1900 mojo)
   -Pending Total Balance: 1.9  (1900 mojo)
   -Spendable:             1.9  (1900 mojo)
   -Type:                  CAT
   -Asset ID:              fbaac130d4fe250cd5896e1106d810246feb41a07638e108881fd89f2cf19a74
   -Wallet ID:             3
```

Get_transactions result:
```
chia wallet get_transactions -i 3 -f 3011902820
Transaction 0342c2b2ac2860cda0fc6afb1e2ff903b0bcbc36d42dde2080c9820d4ff1ecee
Status: Confirmed
Amount sent: 0 BTF
To address: txch16vufldsm38f09e3gygmfz8rwu7xawqw2fmm7x5lsmhgphcrhszfsrnegnc
Created at: 2023-08-18 23:36:45

Transaction ee09b40f163a072eaa91d98be2eede822b36a4971eb531933609374f04180c7a
Status: Confirmed
Amount received: 2 BTF
To address: txch1yf5gu6q73m73l60284z6jwhp90sd9acrnn47ahtfw8s2fhd9pspqnvn0mf
Created at: 2023-08-14 23:30:51
```
Transactions do not add up.  the 2 BTF transaction is the initial transfer to the wallet, the 0 BTF transaction is from the previous test of cancelling an offer.

interestingly, the transaction for the accepted offer shows up in the xch wallet (id: 1) but unfortunately thats just half the cake 

---------------------------------

The wallet which created the offer shows the transaction:
```
chia wallet get_transactions -f 3011902820 -i 2
Transaction d8ec62582f105262e98561043fb4b76a802d8815d37a82af9565f2db848df022
Status: Confirmed
Amount received: 1.9 BTF
To address: txch1q97q4w0yrgtxk9gyyvg5fcqp07x26r5ec4rq45gyrx3539t6afys57sakw
Created at: 2023-08-28 11:50:54

Transaction b24f681a4f63be6782b3a237086848209f0ecb0d4d038e21d560cf753708a69b
Status: Confirmed
Amount sent: 2 BTF
To address: txch16vufldsm38f09e3gygmfz8rwu7xawqw2fmm7x5lsmhgphcrhszfsrnegnc
Created at: 2023-08-25 13:40:25

Transaction 0e5c56de8ff55119487ddd39c978ca6379e15831025a3ce58d8504fdf27271f8
Status: Confirmed
Amount received: 2 BTF
To address: txch1yf5gu6q73m73l60284z6jwhp90sd9acrnn47ahtfw8s2fhd9pspqnvn0mf
Created at: 2023-08-21 11:29:25
```

### Version

2.0.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by forReason** [comment]
another one of these mysteries. On the remote (gui) wallet, the transactions are beeing shown. But on the cli wallet they are not. Balance is the same though.
The gui wallet is the same which created the offers but I deleted the wallet db for re sync

**Comment by wjblanke** [comment]
Transaction history is not deterministic due to heuristics we use to counter privacy features of the blockchain. the wallet does a best effort. we are trying to improve this going forward. for accurate records you should keep a local record of TXs made. *If the balance is not the same* (within a mojos because of dust filtering) please let us know.
