### ISSUE TITLE
[Bug]  The plots I created with "chia plotters chiapos --compress 5" are still 102GB ，It's a compressed plot?

### ISSUE THREAD

**Issue by JustAlias** [Chia-Network/chia-blockchain#16186]
### What happened?

The plots I created with "chia plotters chiapos --compress 5" are still 102GB ，It's a compressed plot?

### Version

2.0.0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by shaneo257** [comment]
hi just alias, 

No, the chiapos plotter is unable to product compressed plots, you will need to use bladebit cude plotting

chia plotters bladebit cudaplot -d <destination dir> -f <farmer key> -p <pool key> -c <contract address> -n <number of plots> --compress <compression level>

**Comment by wjblanke** [comment]
closing with shane's response
