### ISSUE TITLE
[Bug] Clawback Stuck in Pending with No Spend Bundle Listed, Unable to Submit New Spend Bundle

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#16198]
### What happened?

Issue reported by Mathis in discord (https://discord.com/channels/1034523881404370984/1034870571864948777/1144321686544580719)

Overview:
User sent two different clawback transactions in 1.8.2 then had to resync wallet. User experienced the clawback bug reported [here ](https://github.com/Chia-Network/chia-blockchain/issues/15703).

User updated to 2.0.0 and attempted the cli command to clawback the transactions with this result: `{'success': True, 'transaction_ids': []}` (NOTE - no transaction ID was listed)

User now sees the clawback in both the GUI and CLI transaction lists but the "clawing back" state has been present for over a week.

User attempted to clear pending transactions and delete the wallet db allowing it to fully resync, then attempted to resubmit the cli  command to clawback the transaction resulting in the attached log (NOTE - the attached error indicates there is already in a pending spend bundle but there is no spend bundle listed).

User has also attempted a full resync while connected to a local trusted full node with the same results

Potential solution:
- Is there a method to force the clawback spend bundle submission and negate the error of there already being a spend bundle in the mempool?

Full context from Mathis:
```
can any one help me with clawback? I sent 2 transactions of xch to an address. there was an internet error durring the transaction and i had to resync my wallet. upon resyncing  i can see the coins went out successfully but not to the right address. and there is no clawback info in my resynced wallet.

Transaction b802896c71e49c0db77e1237d0c63bf1f08be24f5a3398a1e8881654f5af7a64
Status: Pending
Amount received in clawback as sender: 8 XCH
To address: xch1m673ata80q8v36fgkgnyf83dgl7mnacve3whry6mqy3kds56rqpqkjjsr3
Created at: 2023-08-22 12:18:12
Recipient claimable time: 2023-08-24 12:18:12

Transaction 4ffade3c44dcfa7483e697accfc3e661bf752147fa72d134f33a159626907dcf
Status: Pending
Amount received in clawback as sender: 10 XCH
To address: xch1m673ata80q8v36fgkgnyf83dgl7mnacve3whry6mqy3kds56rqpqkjjsr3
Created at: 2023-08-22 12:09:53
Recipient claimable time: 2023-08-24 12:09:53

Transaction ed7860e1bc750627ba982ae7342939f95cc12457b2eba827cbfcffbd32ac7be8
Status: Confirmed
Amount sent: 8 XCH
To address: xch1m673ata80q8v36fgkgnyf83dgl7mnacve3whry6mqy3kds56rqpqkjjsr3
Created at: 2023-08-22 12:17:53

Transaction c2abd386a7dab220e5cd1ff22844080d1a0e52178abdce5296c7ff80c8ebb416
Status: Confirmed
Amount sent: 10 XCH
To address: xch1m673ata80q8v36fgkgnyf83dgl7mnacve3whry6mqy3kds56rqpqkjjsr3
Created at: 2023-08-22 12:06:32

                     after resync 
_

Transaction c1521e528ccad1bc39876e5eb3fb10d593ee6f48d7cd51e4fc190c74195abe26
Status: Confirmed
Amount sent: 8 XCH
To address: xch1a5n0haz8mknscgttzv5tdr555hu2wcsvlwgnnatdvq67h39f5ghszg3x3r
Created at: 2023-08-22 12:18:12

Transaction 34a4de05289a566af9b6d3bacb724805dd5c415da45430e8ed3d1742f6b2cb27
Status: Confirmed
Amount sent: 10 XCH
To address: xch1a5n0haz8mknscgttzv5tdr555hu2wcsvlwgnnatdvq67h39f5ghszg3x3r
Created at: 2023-08-22 12:09:53

I see my pending clawback transactions again...but when i try to run the clawback on the transation id I get {'success': True, 'transaction_ids': []}

the transactions showed up in the gui pending and then disappeared

clawback was submitted with a 2-day clawback period

```

![mathis_clawback_image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/c2dc3e48-be7e-4db1-b0fc-8977a11abfc3)

### Version

2.0.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-08-28T13:18:01.371 wallet chia.wallet.wallet_state_manager: ERROR    Clawback coin b802896c71e49c0db77e1237d0c63bf1f08be24f5a3398a1e8881654f5af7a64 is already in a pending spend bundle. {'additions': [{'amount': 8000000000000,
                'parent_coin_info': '0x47a8d8f532a72f2bf8934b503a3a7c6e1a08111b367342d2d4b1cf1307825d5c',
                'puzzle_hash': '0xed26fbf447dda70c216b1328b68e94a5f8a7620cfb9139f56d6035ebc4a9a22f'}],
 'amount': 8000000000000,
 'confirmed': False,
 'confirmed_at_height': 4123883,
 'created_at_time': 1692724692,
 'fee_amount': 0,
 'memos': [['0xb802896c71e49c0db77e1237d0c63bf1f08be24f5a3398a1e8881654f5af7a64',
            ['0xdebd1eafa7780ec8e928b226449e2d47fdb9f70ccc5d71935b012366c29a1802']]],
 'name': '0xb802896c71e49c0db77e1237d0c63bf1f08be24f5a3398a1e8881654f5af7a64',
 'removals': [{'amount': 33750335663,
               'parent_coin_info': '0xe161057ff7a20bac06b386e282bbb8d592b0d15ec5f5dfb90eb08155e6cb3f66',
               'puzzle_hash': '0x4b1d9e794291555a508b782eb3ec846fbcd24638d9766010c197d06909594b13'}],
 'sent': 1,
 'sent_to': [],
 'spend_bundle': None,
 'to_puzzle_hash': '0xdebd1eafa7780ec8e928b226449e2d47fdb9f70ccc5d71935b012366c29a1802',
 'trade_id': None,
 'type': 7,
 'wallet_id': 1}
```

Side note - after multiple attempts I have not been able to reproduce this issue

**Comment by ytx1991** [comment]
There is a way to force the spend of Clawback. Just use the wallet rpc spend_clawback_coins API.
For example, 
chia rpc wallet spend_clawback_coins '{"coin_ids":[YOUR_CLAWBACK_COIN], force=true, fee=0}'

**Comment by BrandtH22** [comment]
> There is a way to force the spend of Clawback. Just use the wallet rpc spend_clawback_coins API. For example, chia rpc wallet spend_clawback_coins '{"coin_ids":[YOUR_CLAWBACK_COIN], force=true, fee=0}'

Unfortunately, the force flag is not bypassing the "Clawback coin xxxx is already in a pending spend bundle." ERROR (same error as is in original post)

**Comment by BrandtH22** [comment]
This has now been resolved.
To run the clawback rpc with the force flag the user needed to be on the main branch then it works like a charm!

Thank you to all who were involved!

**Comment by 344303947** [comment]
chia rpc wallet spend_clawback_coins "{\"coin_ids\":[\"0xb4f477e6c379c09857542ad943deb0b07e05f40a0582\"],\"force\":true,\"fee\":0}"
{
    "success": true,
    "transaction_ids": [
        "2691dc34a4874ce643acab693946c32fa4f22"
    ]
}
There is a problem with the JSON format above. I used TXID and modified the format to solve this problem
