### ISSUE TITLE
Farming Rewards - Still stopped!!!

### ISSUE THREAD

**Issue by TschiAR** [Chia-Network/chia-blockchain#1619]
Hi,

i just did what you (mariano54 i) wrote yesterday but nothing changed. It shows farming since friday with 21 TB Plots.
Nothing happened. No Rewards shwoing up.

Everything is synced: Connection status connected, Status synced, Full Node, Wallet is synced, Plots are green, every 30-60 seconds "Plots Passed Filter" changes to 1/110

Can someone please post a tutorial here on how to check plots on windows?
the chia software shows all plots are green and farming. 

Last Height Farmed 33609

When i did (read orignal mesage from mariano54 diwn here) it i had not to enter my private key to restore my wallet.
Can that be the problem?

Regards Hillo

Originally posted by @mariano54 in https://github.com/Chia-Network/chia-blockchain/issues/1596#issuecomment-810287859_
It might be a problem of wallet DB not being synced, so you can't see rewards.

Stop chia (even on task manager)
Delete the ~/.chia directory
Restart computer
Start Chia again

Hopefully you will see rewards.
If your plots are going through the plot filter, you are farming correctly.

_Originally posted by @mariano54 in https://github.com/Chia-Network/chia-blockchain/issues/1596#issuecomment-810287859_

**Comment by mariano54** [comment]
Everything is synced: Connection status connected, Status synced, Full Node, Wallet is synced, Plots are green, every 30-60 seconds "Plots Passed Filter" changes to 1/110

This is fine.
