### ISSUE TITLE
macOS Mojave (10.14) support

### ISSUE THREAD

**Issue by davidbarratt** [Chia-Network/chia-blockchain#162]
It would  be great if Chia supported macOS Majave (10.14).

**Comment by hoffmang9** [comment]
As it says at the bottom of the release notes - we will.
See Known issues #1: https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta3

**Comment by davidbarratt** [comment]
tbf, if we add support for Docker (assuming that's possible) #167, I wont need the macOS support. :)
