### ISSUE TITLE
[Bug] plotting tab shows k32 with 130GiBe effective plot size for c0 plots

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#16214]
### What happened?

c0 plots in the GUI are showing as 130GiBe effective plot size for k32.

![Screenshot 2023-08-31 at 9 19 02 PM](https://github.com/Chia-Network/chia-blockchain/assets/93196638/183ac4aa-c17f-4576-a921-7845153ca195)

### Version

2.0.0

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by Ron-ski** [comment]
That 130GiBe shows in a lot of places, for all compression sizes in the plotter, and I'm sure I've seen it elsewhere.
