### ISSUE TITLE
[BUG] "Connecting to wallet" after plotting for about 8+ hours. Console log says "ECONNREFUSED 127.0.0.1:55400"

### ISSUE THREAD

**Issue by mitchdowney** [Chia-Network/chia-blockchain#1622]
**Describe the bug**
After running the GUI and plotting for about 8+ hours, the wallet says "Connecting to wallet", and reloading and force reloading the view does not work. This has happened twice in one day. I'm using Ubuntu 20, and trying to plot on 6 separate queues using all 6 of my computers threads (1 thread per queue).

It appears the app is still plotting as I can see the Date Modified changing for the plot files in the temporary directory.

The console says:

Uncaught Error: connect ECONNREFUSED 127.0.0.1:55400 at TCPConnectWRap.afterConnect [as oncomplete]

**To Reproduce**

1. Leave the wallet open plotting for 8+ hours
2. Eventually the "Connecting to wallet" error happens and never goes away.

**Expected behavior**
The wallet to stay connected.

**Desktop (please complete the following information):**

- OS: Ubuntu 
- OS Version/Flavor: 20.04.2 LTS
- CPU: Intel Core i5-9600K CPU @ 3.70GHz x 6

**Comment by mitchdowney** [comment]
I was overusing my RAM...I had 6 queues using the default 4960RAM setting, but only have 24GB of RAM. I'll try plotting without overusing the RAM, and will close this issue if it doesn't come up again.

**Comment by GForceWeb** [comment]
I got the same Connecting to Wallet issue and matching console error.

For me, this occurred after a system crash and reboot.

**Comment by Bronkow** [comment]
Same here. Version 1.0.3, System (MacOS Big Sure) crashed while ploting (one 33k - iMac Pro - 64 GB ram - no overuse). After automatic reboot i cant connect to wallet when opening GUI. I tried to complete delete chia and reinstalled. After entering mnemonic i got the note "database disk image is malformed" and again no connection to wallet.

**Comment by MCorluka** [comment]
Similar issue.
Was plotting two plots at the same time, slightly stagger. RAM about 4GB/plot, 1 thread, plenty of space. Internet off.
Hour 6. Decided to delete one in-progress plot as it's my main computer and I turned on the internet to quickly check something.
Connecting to wallet" error happens and never goes away.

**Comment by mariano54** [comment]
Probably daemon crashing after running out of memory.

**Comment by stonetwig** [comment]
This happens to me after installation on windows, haven't even setup plotting yet.

**Comment by tleite** [comment]
I'm on a MacOS 10.15.7

**Description:** I've been stuck on "Connecting to Wallet" for 2 days. I tried rebooting several times, but I can't get past this screen.
**How it started:** I was in the middle of a plotting process, and my laptop ended up rebooting for some reason

![Chia Blockchain 2021-04-09 09-06-13](https://user-images.githubusercontent.com/852556/114192358-00b19b00-9913-11eb-83e6-944af63a523e.jpg)

**Comment by justnatural** [comment]
Got the same problem after plotting for about 18 h... 10 plots, 2 threads. I think it was too much for my build to handle...
