### ISSUE TITLE
[Bug] Full Node Connection - Not connected 2.0.1-b3.dev58

### ISSUE THREAD

**Issue by testowebapp** [Chia-Network/chia-blockchain#16230]
### What happened?

I have moved from Chia Blockchain 1.8.2 -> 2.0.1-b3.dev58 and have errors in Plots and Farm dashboard in Chia GUI.

Part plots self-farming, part are on pool. 

With self farming there are plot errors in the status and in Farm Summary dashboard shows farming is not running. 

![image](https://github.com/Chia-Network/chia-blockchain/assets/10099386/041d1a5f-e471-4e0e-a3b0-68639d812eac)

In Advanced Options  >  Your Full Node Connection 
Connection Status: Not connected

However checking from terminal via `> chia farm summary` 

Farming status: Farming

In 1.8.2 version farming worked without any errors. 

### Version

2.0.1-b3.dev58

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by xxsmoo** [comment]
I had the same problem on 2.0.1-b2 (comming from 2.0.0).
I moved back to 2.0.0 without any problems.

**Comment by testowebapp** [comment]
Yep 2.0.0 is working without this bug. Thanks [xxsmoo](https://github.com/xxsmoo)
