### ISSUE TITLE
windows 10 - can't enter mnemonic [BUG]

### ISSUE THREAD

**Issue by pjt87uk** [Chia-Network/chia-blockchain#1623]
getting messages like 'fingerprint' and its is saying that my seed is incorrect length ive done both 12 & 24 triple checked it and still not letting me get on wallet from another pc, also made sure i didnt have two instances of the wallet launch and had same problem. so bit confused as to why this isnt launching, also how and where is the backup file it insists on having?

**Comment by lvpcguru** [comment]
Any luck on this one? did this go away after the several following updates?
