### ISSUE TITLE
[Bug] 爆块后就会报错，必须重启才能正常恢复。无法关闭加载无响应

### ISSUE THREAD

**Issue by heiseshupo** [Chia-Network/chia-blockchain#16240]
### What happened?

升级chia 2.0后，每次爆块完，主钱包都会错误，节点错误，收割机错误，手动关闭主钱包都无响应，用任务管理器可以结束进程，重新打开就正常了。![11aa52a5fd8565cc137298e866ff9295](https://github.com/Chia-Network/chia-blockchain/assets/81500563/4072df3a-5a9b-40cd-8457-99c193706463)
节点错误图片
![e7ddac676df89c7f5d4699ebe7c1f25f](https://github.com/Chia-Network/chia-blockchain/assets/81500563/94ce1c63-b1d2-485e-bfba-1d581a1f3df0)
<img width="873" alt="image" src="https://github.com/Chia-Network/chia-blockchain/assets/81500563/3757c85d-fffe-4b89-9a1d-25560aac7349">
绿色正常→红色百分比（%）→直接显示错误。（出现的规律，都是在爆块后）

环境：win10  
图是否压缩：no
图版本：32 33 34
是否加入矿池：no
合作社：自耕种（solo）
收割机：多台（2.0版本，替换了原始收割机）

### Version

2.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
日志也没找到报错的，都正常
```

**Comment by heget** [comment]
I have the same issue Iam solo as well.

![image](https://github.com/Chia-Network/chia-blockchain/assets/14862691/3b7af718-3d07-4316-8f72-220866ed6e9b)

**Comment by wjblanke** [comment]
Signage points come every 9 seconds so missing 22 is almost expected because of network issues or latency. Think of netflix glitches.
