### ISSUE TITLE
[BUG] Chia Wallet shows incorrect Total Number of XCH

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#1625]
My wallet shows that I have only 6 XCH. But it is 14 XCH. If I connect my wallet on another computer, it shows 14 XCH. I already tried uninstalling Chia in the Win 10 Control Panel and deleted the following folders.

%AppData%\Chia Blockchain
%LocalAppData%\chia-blockchain

After a PC restart and after the fresh installation of V1.0.3 it directly shows me my wallet. Where are those informations stored? Do I need to delete additional folders? Even after this procedure I' am on 6 XCH. The problem is, that this bug belongs to my farming station. I'm not sure right now if farming works, since I didn't get any rewards since the problem occured.

**Comment by hoffmang9** [comment]
Rewards are on the blockchain. Your local copy is in C:\Users\YOURUSER\.chia\mainnet\wallet\db Delete the contents of that directory and wallet will resync after you restart the app.

**Comment by Dravenex** [comment]
Edit: After about 1 hour it shows now 14 XCH. Thanks for the help, Gene!
