### ISSUE TITLE
[Bug] Recursive plot scan ignores hard links

### ISSUE THREAD

**Issue by Fahrenheit2539** [Chia-Network/chia-blockchain#16268]
### What happened?

I have a main plotting directory that has a few mount points and a few hard links.

When I switched to using recursive searching I noticed that plots from mount points were picked fine, but no plots from hard-linked directories were farmed.

Here's the sample directory, I have to specify plot01-plot07 manually as an additional plot paths:

> -rwxrwxrwx+ 1 guest users 108826485488 Oct 10  2021 plot-k32-2021-10-10-05-01-a7279687971312438a432eb673fc13363d52f87aee459445e527701137c50197.plot
-rwxrwxrwx+ 1 guest users 108802486755 Oct 10  2021 plot-k32-2021-10-10-06-02-927a8d973e0f0fc18e67a0f3c9ffea66382c9e17d667f51eef172b993126ed78.plot
-rwxrwxrwx+ 1 guest users 108817698217 Oct 10  2021 plot-k32-2021-10-10-07-40-ff279245c837e85ff014feded1b7a6452d3601f62d4a27043ba5bc53c8d50d5a.plot
-rwxrwxrwx+ 1 guest users 108810943123 Oct 11  2021 plot-k32-2021-10-11-18-20-2da2729d47eae307c9f3a4ef93a0e8a8e95a8176b640d9d475fc37597edea022.plot
-rwxrwxrwx+ 1 guest users  88878366720 Sep  4 12:43 plot-k32-c04-2023-09-04-12-38-442cf42234781fd850739075976926ded7bd8ae0f1ed63fa538ebe507ee38500.plot
-rwxrwxrwx+ 1 guest users  88929333248 Sep  4 13:14 plot-k32-c04-2023-09-04-13-08-da133f47058df6bec61f323d8d779e6399668b33e0a8c37cb3cf04c452be0584.plot
-rwxrwxrwx+ 1 guest users  88847151104 Sep  4 13:48 plot-k32-c04-2023-09-04-13-42-719ff8172974391ca876362785ab006d226cc1d1fa275567d6b3da9161b0344d.plot
-rwxrwxrwx+ 1 guest users  88949571584 Sep  4 14:19 plot-k32-c04-2023-09-04-14-13-9c912efe43b2971edcca1d18aebb985fc9c0031748f45828efa04bda63ac53cc.plot
lrwxrwxrwx+ 1 root  root            16 Sep 29  2021 plots01 -> /volume2/plots01
lrwxrwxrwx+ 1 root  root            16 Sep 29  2021 plots02 -> /volume3/plots02
lrwxrwxrwx+ 1 root  root            16 Sep 29  2021 plots03 -> /volume4/plots03
lrwxrwxrwx+ 1 root  root            16 Sep 29  2021 plots04 -> /volume5/plots04
lrwxrwxrwx+ 1 root  root            16 Oct 16  2021 plots05 -> /volume6/plots05
lrwxrwxrwx+ 1 root  root            16 Sep 29  2021 plots06 -> /volume7/plots06
lrwxrwxrwx+ 1 root  root            16 Oct 14  2021 plots07 -> /volume8/plots07
drwxrwxrwx  4 root  root         16384 Apr  1  2022 plots08
drwxrwxrwx  4 root  root         12288 Apr  1  2022 plots09
drwxrwxrwx  4 root  root         24576 Feb 12  2022 plots10
drwxrwxrwx+ 2 guest users         4096 Sep 30  2021 plots11
drwxrwxrwx+ 2 guest users         4096 Oct  6  2021 plots12
drwxrwxrwx  4 root  root         24576 Apr  1  2022 plots13
drwxrwxrwx  4 root  root         20480 Apr  1  2022 plots14
drwxrwxrwx  4 root  root         16384 Apr  1  2022 plots15
drwxrwxrwx  4 root  root         24576 Apr  1  2022 plots16
drwxrwxrwx+ 2 guest users         4096 Sep  4 12:02 plots17
drwxrwxrwx  4 root  root         20480 Apr  1  2022 plots18
drwxrwxrwx  4 root  root         16384 Apr  1  2022 plots19
drwxrwxrwx  4 root  root         24576 Feb 12  2022 plots20
drwxrwxrwx  1 root  root       2097152 Jul 22 09:58 plots21
drwxrwxrwx  1 root  root       2097152 Jul 23 10:14 plots22
drwxrwxrwx+ 2 guest users         4096 Sep  4 12:02 plots23
drwxrwxrwx+ 2 guest users         4096 Sep  4 12:02 plots24
drwxrwxrwx+ 2 guest users         4096 Sep  4 12:02 plots25
drwxrwxrwx+ 2 guest users         4096 Sep  4 12:02 plots26
drwxrwxrwx+ 2 guest users         4096 Sep  4 12:02 plots27

### Version

2.0.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
We are using pathlib.rglob(*.plot) for resolving plots. Maybe there is an issue in that for hard links.
