### ISSUE TITLE
[Bug] Full Node not synching (v2.0.1)

### ISSUE THREAD

**Issue by ALEXSPINDER** [Chia-Network/chia-blockchain#16284]
### What happened?

Updated from version 1.8.1 to version 2.0.1
Original version was working just fine
New version connects Wallet but [Full Node] is "Connected" but is stuck in synching for 2hrs now. No progress indication.
[Connect to other peers] (e.g. beast.chia.net) is also not working.
Please advise

### Version

2.0.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by duanecato** [comment]
Same behaviour seen on Elementary Linux 5.1.7. Chia 2.0.1 connected to multiple peers, does not sync. Also unable to select final plot folder.

**Comment by nicezic** [comment]
me too.
```
-rw-r--r-- 1 chia chia 6549504  9월 12 17:56 blockchain_wallet_v2_r1_mainnet_1149317241.sqlite
-rw-r--r-- 1 chia chia   32768  9월 12 17:57 blockchain_wallet_v2_r1_mainnet_1149317241.sqlite-shm
-rw-r--r-- 1 chia chia 6052312  9월 12 17:57 blockchain_wallet_v2_r1_mainnet_1149317241.sqlite-wal
```
after deteled wallet dirs. always same.
stoped here.

```
Wallet height: 4219527
Sync status: Not synced

Connections:
Type      IP                                      Ports       NodeID      Last Connect      MiB Up|Dwn
FULL_NODE 127.0.0.1                                8444/8444  06e5c2bc... Sep 12 17:58:58      0.4|31.2
                                                  -Height: No Info    -Hash: No Info    -Trusted: True
                                                  
```

even full_node is synced.

**Comment by xxsmoo** [comment]
I had a similar problem with 2.0.1 on windows (maybe). My db was corrupt. At the moment I'm syncing based on the db (30.06.23). It's working for me. The connections to other peers are connected and chia is syncing

**Comment by wjblanke** [comment]
Can you send the DEBUG debug.log and maybe we can see why the wallet can't make progress.

**Comment by ALEXSPINDER** [comment]
Lo and behold: it mysteriously disappeared.
Steps done: installed v1.8 to no avail. Installed 2.0.1 to no avail. rebooted, let it simmer, it works.
So, probably something serverside? Anyway, I'll close the issue
