### ISSUE TITLE
harvester crashes with segfault - error 4 in lib python3.9.so.1.0

### ISSUE THREAD

**Issue by mharsch** [Chia-Network/chia-blockchain#16294]
### What happened?

harvester crashed after several hours of uptime.

Similar symptom as #6868

### Version

2.0.1 (via docker)

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
Sep  8 14:47:22 deepseven kernel: [258832.925405] chia_harvester[2047504]: segfault at 9 ip 00007f8b0a746985 sp 00007ffe19881e50 error 4 in lib
python3.9.so.1.0[7f8b0a602000+198000]
Sep  8 14:47:22 deepseven kernel: [258832.925416] Code: 00 0f 29 b4 24 b0 00 00 00 0f 29 bc 24 c0 00 00 00 64 48 8b 04 25 28 00 00 00 48 89 44
24 18 31 c0 48 85 ff 0f 84 95 b8 f5 ff <48> 8b 47 08 f6 80 ab 00 00 00 04 0f 84 84 b8 f5 ff 48 85 f6 75 57
```

**Comment by poli5** [comment]
I have encountered the same problem (Windows10)
C3 compression
Version 20.0.1 and RC6
GPU p106-100 537.13 Driver
After using GPU harvesting, it started working normally, but after a few hours it stopped and couldn't earn points. I had to shut down the client and restart, but after a few hours it stopped again.
If I use the CPU, it won't be a problem, but it's too slow. My CPU is Intel 4400t.

**Comment by wjblanke** [comment]
If you have any more info about the crash dump let us know.  I'll try to disassemble based on the binary dump.

**Comment by mharsch** [comment]
Another crash observed today.  Unknown if this is the same issue.
```
Sep 13 11:54:22 deepseven kernel: [680451.596082] chia_harvester[3408970]: segfault at d ip 00007f5383c82f40 sp 00007ffce1cb5868 error 6 in _as
yncio.cpython-39-x86_64-linux-gnu.so[7f5383c7f000+5000]
Sep 13 11:54:22 deepseven kernel: [680451.596092] Code: e9 f7 fd ff ff 48 89 df e8 ed c1 ff ff e9 6b fd ff ff 48 89 df e8 e0 c1 ff ff e9 fe fc
ff ff e9 2c c6 ff ff 66 0f 1f 44 00 00 <48> 83 2f 01 74 0a c3 66 0f 1f 84 00 00 00 00 00 e9 bb c1 ff ff 66
```

**Comment by wjblanke** [comment]
Thanks for the additional report. Can u determine if it is due to a particular plot? We think it may be an edge case since we havent gotten many reports. Can you try to run:

chia plots check
