### ISSUE TITLE
[Bug] Bladebit Cuda "Allocating buffers" runs very slowly after many consecutive plots

### ISSUE THREAD

**Issue by iced-caffeine** [Chia-Network/chia-blockchain#16306]
### What happened?

I am plotting on Windows 11.  I'm using a background helper script in python to launch new plot processes after the prior one has completed via the command line.  This works well for a while, but after some time (somewhere between 4 and 40 successful plots), when I try to launch new plots, the memory allocation during the "Allocating buffers" phase takes a very long time and uses heavy CPU.  Normally this part of the process is very quick.  This happens regardless of if I launch it using the helper script or paste the command directly into cmd.  Available memory on the system is still very high, showing 244GB available right now as this failure is occurring.

Restarting the system resolves this, but obviously this is a big pain since I have over 10k plots.

C:/Users/xxx/AppData/Local/Programs/Chia/resources/app.asar.unpacked/daemon/chia.exe plotters bladebit cudaplot -d //Desktop-xxx/plot_drives/xxx/ -f XXXxxXXX -c xchxxxxx -n 1 --compress 7 -r 32 -v

Normal Buffer Allocation
![normal_buffer_allocation](https://github.com/Chia-Network/chia-blockchain/assets/101305165/6ffbb8c7-8a90-462c-a65f-7db0a3ec0966)

Slow Buffer Allocation
![slow_buffer_allocation](https://github.com/Chia-Network/chia-blockchain/assets/101305165/95a46d40-5bac-46a8-8e51-0595df91c623)

System Idle
![system_idle](https://github.com/Chia-Network/chia-blockchain/assets/101305165/a9d0ff26-0e82-4ce5-b56d-047e5d3d076c)

### Version

2.0.0

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
Bladebit Chia Plotter
Version      : 3.0.0
Git Commit   : 02a8e68dcf0e971c72fc8377b89cdd081b80b843
Compiled With: msvc 19.29.30151

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 32
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : xxxx
 Pool contract address : xchxxxx
 Compression Level     : 7
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 3090
 CUDA Compute Capability   : 8.6
 SM count                  : 82
 Max blocks per SM         : 16
 Max threads per SM        : 1536
 Async Engine Count        : 2
 L2 cache size             : 6.00 MB
 L2 persist cache max size : 4.50 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 24.00 GB
  Free                     : 22.74 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 141733920768 bytes ( 135168.00 MiB or 132.00 GiB )
Total Host RAM required   : 231974445056 bytes ( 221228.07 MiB or 216.04 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers
```

**Comment by iced-caffeine** [comment]
Update, I believe this had something to do w/ the power settings on my system, specifically, letting it turn the monitor off (which was being driven by the GPU).  I disabled letting it turn the monitor off and let it run all night.  No Issues.

**Comment by twistacatz** [comment]
@iced-caffeine I'm running into the same issue. I've disabled any and all power saving features that I've been able to find yet I still run into the issue you described every 10 plots or so. Can you give some more insight to what you changed to fix the issue.
