### ISSUE TITLE
Incorrect DAO balance shown [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16318]
### What happened?

I'm running on the `dao-wallet` branch on testnet10. The balance of the DAO wallet is shown incorrectly. Steps to recreate:
1. Create a new DAO. In this case, the wallet ID is `3`
2. Add funds to the DAO, for example I added 2 XCH with this command:
  `chia dao add_funds -i 3 --funding-wallet-id 1 -a 2 -m 0.00001`
3. After this transaction has completed, show the DAO's balance:
  `chia dao get_balance -i 3`
  This command shows the correct balance:
  `XCH: 2.0`
4. Show the whole Chia wallet's balance:
  `chia wallet show`
  The balance of the DAO wallet (ID 3) is listed as `1.0`, but it should be `2.0`:
  ```
  Chia Wallet:
   -Total Balance:         0.999979899999 txch (999979899999 mojo)
   -Pending Total Balance: 0.999979899999 txch (999979899999 mojo)
   -Spendable:             0.999979899999 txch (999979899999 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1

Profile 1:
   -Total Balance:         1.0
   -Pending Total Balance: 1.0
   -Spendable:             1.0
   -Type:                  DAO
   -Treasury ID:           39fb03206fb249442cb090ceb557dcaad67b5f15705e7fd57a91455d7f5a2b37
   -Wallet ID:             3

CAT d4db1ce73451af4a...:
   -Total Balance:         100.0  (100000 mojo)
   -Pending Total Balance: 100.0  (100000 mojo)
   -Spendable:             100.0  (100000 mojo)
   -Type:                  CAT
   -Asset ID:              d4db1ce73451af4af468a33ef6bb59e364edba4950a02204e7a9e04edf760405
   -Wallet ID:             4

CAT d4db1ce73451af4a...:
   -Total Balance:         0.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DAO_CAT
   -Asset ID:              00000000000000030000000000000004d4db1ce73451af4af468a33ef6bb59e3
   -Wallet ID:             5
  ```

### Version

dao-wallet branch, testnet10, 2.0.1b3.dev256

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by geoffwalmsley** [comment]
fixed to make this consistent with other wallets
