### ISSUE TITLE
[Bug] Unable to plot with cudaplot

### ISSUE THREAD

**Issue by hengic** [Chia-Network/chia-blockchain#16310]
### What happened?

I try to use chia cli to plot. but it gives an error. see messages as blow:

Bladebit Chia Plotter
Version      : 3.0.0
Git Commit   : 02a8e68dcf0e971c72fc8377b89cdd081b80b843
Compiled With: gcc 9.4.0

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 64
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx68869
 Pool contract address : xch1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxrnqu0e8xs
 Compression Level     : 5
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 3080
 CUDA Compute Capability   : 8.6
 SM count                  : 68
 Max blocks per SM         : 16
 Max threads per SM        : 1536
 Async Engine Count        : 2
 L2 cache size             : 5.00 MB
 L2 persist cache max size : 3.75 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 9.77 GB
  Free                     : 9.54 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 141733920768 bytes ( 135168.00 MiB or 132.00 GiB )
Total Host RAM required   : 231974445056 bytes ( 221228.07 MiB or 216.04 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers

Generating plot 1 / 1: 5230caab19055d941c37d4480f31244dce5317fba784b33032e4ab1344fbc844
Plot temporary file: /mnt/storage4/chia2/plot-k32-c05-2023-09-12-13-36-5230caab19055d941c37d4480f31244dce5317fba784b33032e4ab1344fbc844.plot.tmp

Generating F1
Progress update: 0.01
Finished F1 in 1.71 seconds.
Progress update: 0.1
Table 2 completed in 5.17 seconds with 4294960138 entries.
Progress update: 0.2
Table 3 completed in 8.14 seconds with 4294825649 entries.
Progress update: 0.3
Table 4 completed in 11.46 seconds with 4294592401 entries.
Progress update: 0.4
Table 5 completed in 11.97 seconds with 4294170781 entries.
Progress update: 0.5
Table 6 completed in 9.87 seconds with 4293275782 entries.
Progress update: 0.6
Table 7 completed in 6.39 seconds with 4291533552 entries.
Progress update: 0.7
Finalizing Table 7
Finalized Table 7 in 4.21 seconds.
Completed Phase 1 in 58.93 seconds
Progress update: 0.8
Marked Table 6 in 1.91 seconds.
Marked Table 5 in 1.67 seconds.
Marked Table 4 in 1.58 seconds.
Marked Table 3 in 1.56 seconds.
Completed Phase 2 in 6.72 seconds
Progress update: 0.9
Compressing Table 2 and 3...
 Step 1 completed step in 2.76 seconds.
 Step 2 completed step in 4.61 seconds.
Completed table 2 in 7.37 seconds with 3439583755 / 4294825649 entries ( 80.09% ).
Compressing tables 3 and 4...
 Step 1 completed step in 3.39 seconds.
 Step 2 completed step in 6.50 seconds.
STDERR: *** Crashed! ***

STDERR: /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_Z12CrashHandleri+0xaa)[0x55e6b45b1eda]

STDERR: /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7fad8572d210]

STDERR: /lib/x86_64-linux-gnu/libc.so.6(+0x18eb8b)[0x7fad85875b8b]

STDERR: /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_Z22CudaK32PlotPhase3Step3R18CudaK32PlotContext+0x15b7)[0x55e6b457b9e7]

STDERR: /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_Z17CudaK32PlotPhase3R18CudaK32PlotContext+0x10fb)[0x55e6b456f79b]

STDERR: /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_ZN14CudaK32Plotter3RunERK11PlotRequest+0x95b)[0x55e6b455d8bb]

STDERR: /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(main+0x9d5)[0x55e6b45590b5]

STDERR: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fad8570e0b3]

STDERR: /opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_start+0x2e)[0x55e6b455a7be]

STDERR: Dumping crash to crash.log

### Version

2.0.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_Z12CrashHandleri+0xaa)[0x55e6b45b1eda]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7fad8572d210]
/lib/x86_64-linux-gnu/libc.so.6(+0x18eb8b)[0x7fad85875b8b]
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_Z22CudaK32PlotPhase3Step3R18CudaK32PlotContext+0x15b7)[0x55e6b457b9e7]
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_Z17CudaK32PlotPhase3R18CudaK32PlotContext+0x10fb)[0x55e6b456f79b]
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_ZN14CudaK32Plotter3RunERK11PlotRequest+0x95b)[0x55e6b455d8bb]
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(main+0x9d5)[0x55e6b45590b5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fad8570e0b3]
/opt/chia/resources/app.asar.unpacked/daemon/bladebit/bladebit_cuda(_start+0x2e)[0x55e6b455a7be]
```

**Comment by hengic** [comment]
My RAM:

free -m
              total        used        free      shared  buff/cache   available
Mem:         773582        5594      767356          18         631      764011
Swap:         65535           0       65535

GPU: GeForce RTX 3080
Driver: 535.104.05
Cuda: 12.2

**Comment by wjblanke** [comment]
Assigning to Harold

**Comment by emlowe** [comment]
Closing issue as focus on the new plot format takes precedence over prior plot issues
