### ISSUE TITLE
-f option used twice for add_missing files [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16337]
### What happened?

The  `-f, --fingerprint` option was added to several DataLayer commands In 2.1. This includes `chia data add_missing_files`, which contains the following options:
```
 -f, --foldername
 -f, --fingerprint
```
These options both use -f, so the flag is now ambiguous. 

### Version

2.1.0rc2-dev2

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Fixed in https://github.com/Chia-Network/chia-blockchain/pull/16383
