### ISSUE TITLE
[Bug] Farm tab shows sync status as "not running" and plots passing filter as "not running"

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#16343]
### What happened?

Full node is synced, but on the farming tab, the sync status and plots passing filter both show as "not running"

![Screenshot 2023-09-15 at 10 42 10 AM](https://github.com/Chia-Network/chia-blockchain/assets/93196638/868d698b-1009-4c7f-b76c-59cfee762a8f)

Also mentioned here in discord beta group - https://discord.com/channels/1034523881404370984/1102690350218354920/1152209112361341038

### Version

2.1.0rc1

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
I confirmed this is a new issue added in `2.1.0-rc1` release.
I've created a PR for this.
https://github.com/Chia-Network/chia-blockchain-gui/pull/2117

**Comment by shaneo257** [comment]
also have it on 2.0.1b3-dev131 on linux

**Comment by xxsmoo** [comment]
I have the issue on Win  10. I went back to 2.0.1.
