### ISSUE TITLE
Chia Blockchain Version 0.0

### ISSUE THREAD

**Issue by rkandel** [Chia-Network/chia-blockchain#1634]
**Describe the bug**
After upgrading from version 1.0.1 to 1.0.3 on Ubuntu 20.04 LTS, the  GUI version is shown as 0.0.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by hoffmang9** [comment]
It is expected behavior that the GUI does not get a release version unless you use the installers.
