### ISSUE TITLE
[Bug] Memory Leak?

### ISSUE THREAD

**Issue by Pandelta** [Chia-Network/chia-blockchain#16348]
### What happened?

I am trying out the Bladebit Cuda which works pretty good in 128 cli mode. I only have 128GB of memory. The issue I am having is with the GUI, it eats ram up over time and eventually causes the Bladebit process to get killed due to lack of memory. I then have to exit out of the GUI for several minutes and restart the process over again. Time can be as short as 8 or 9 hours but has gone longer than that. I have swap disabled and I am not using the computer for anything else. 

I am using Ubuntu 20. I have not attached any logs. Let me know exactly what you need and where it would be if you need something. I am using 2.0.1

### Version

2.0.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by Pandelta** [comment]
I noticed over the weekend it will run longer if when I close and reload the GUI, I leave it on the default screen (Tokens). If I switch it to one of the screens with the plot count it will run as little 3 hours and kill the Bladebit process. I can switch back and forth to various screens as long as I don't stay on one with plot counts. I believe the memory leak/excessive consumption is related to the new harvest screen.

**Comment by wjblanke** [comment]
Memory is pretty tight so it may be worth trying from the command line instead of the GUI
