### ISSUE TITLE
Full Node status not loading after crash

### ISSUE THREAD

**Issue by andyoyellow** [Chia-Network/chia-blockchain#1638]
Full Node Status/Blocks/Connections have infinite spinner. All plots show not available. Farming Status: Not Available (Wait for synchronization)

Dev Tools:
DevTools failed to load SourceMap: Could not parse content for file:///Applications/Chia.app/Contents/Resources/app.asar/build/static/js/2.6bd1e003.chunk.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///Applications/Chia.app/Contents/Resources/app.asar/build/static/js/main.6668c777.chunk.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///Applications/Chia.app/Contents/Resources/app.asar/build/static/css/main.d4c62d7e.chunk.css.map: Unexpected end of JSON input

**Comment by mariano54** [comment]
Can you check the ~/.chia/mainnet/log/debug.log for any errors?
