### ISSUE TITLE
[BUG] Plots not showing after upgrade to 1.03

### ISSUE THREAD

**Issue by mcb0** [Chia-Network/chia-blockchain#1639]
**Describe the bug**
After upgrading to 1.03 and generating plots, the plot directory is not set therefore plots are not shown. When I try setting the plot directory I get a dialog box with 13 in it and the ok button. This dialog also appears when the app opens. I uninstalled and reinstalled and getting same results, unable to set plot directory.

**To Reproduce**

1. Go to add plot directory
2. Click on add plot directory
3. Select directory 
4. See dialog box with 13 and ok.  press ok and directory does not show.
5. Also, created new plots after upgrade, they appear to complete because they are in the directory but do not show in the app.

**Expected behavior**
Expected to see the plot directory and plots show in app.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: Intel Xeon E5-2680

**Additional context**

**Comment by adaptdefymike** [comment]
I managed to get the app farming again (installed 1.0.3). Then proceeded to add a plot and it got to 100% but got hung up. The .tmp file remains in the temp folder and the final folder has the same .tmp file not the .plot file. The end result is no ability to add additional plots to my farm. Any suggestions?

**Comment by dorkmo** [comment]
yeah i've had a few plots hang at 100% for an unusual amount of time. around an hour?

**Comment by adaptdefymike** [comment]
My Mac just crashed and the plot that was hanging disappeared.
