### ISSUE TITLE
[Bug] chia wallet coins split cli command returning error that wallet needs to be synced when it's already synced

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#16400]
### What happened?

running the cli command to split coins returns an error when it shouldn't.

esaung@Chia-Macbook daemon % ./chia wallet show

Active Wallet Key (*):
   -Fingerprint:           1409356558
   -Label:                 CR CATS TN10 Issuer
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   Bob - Demo wallet (Issuer)
21)   87074341     VC (Issuer)
22)   150642830    David - Restaurant Manager
23)   1477437356
24) * 1409356558   CR CATS TN10 Issuer
Choose a wallet key [1-24] ('q' to quit, or Enter to use 1409356558): 24
Wallet height: 3226643
Sync status: Synced
Balances, fingerprint: 1409356558

Chia Wallet:
   -Total Balance:         29.999994999999 txch (29999994999999 mojo)
   -Pending Total Balance: 29.999994999999 txch (29999994999999 mojo)
   -Spendable:             29.999994999999 txch (29999994999999 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1

VC issuer DID CR Cats:
   -Total Balance:         1.0  
   -Pending Total Balance: 1.0  
   -Spendable:             1.0  
   -Type:                  DECENTRALIZED_ID
   -DID ID:                did:chia:1slf7r2pt83yh5p5hs0844gmnflkdvtkmrxantr589ml7uzyuujls66ugpt
   -Wallet ID:             2

VC issuer DID CR Cats NFT Wallet:
   -Total Balance:         0.0  
   -Pending Total Balance: 0.0  
   -Spendable:             0.0  
   -Type:                  NFT
   -DID ID:                did:chia:1slf7r2pt83yh5p5hs0844gmnflkdvtkmrxantr589ml7uzyuujls66ugpt
   -Wallet ID:             3
 
Connections:
Type      IP                                      Ports       NodeID      Last Connect      MiB Up|Dwn
FULL_NODE 127.0.0.1                               58444/58444 95452eec... Sep 22 14:30:45      0.0|0.0    
                                                  -Height: No Info    -Hash: No Info    -Trusted: True
FULL_NODE 128.140.86.208                          58444/58444 7338393f... Sep 22 14:31:30      0.0|15.8   
                                                  -Height: No Info    -Hash: No Info
esaung@Chia-Macbook daemon % ./chia wallet coins split -n 9 -a 3 -m 0.0000000001 -t 0x822281fc7baa6d5826e303134e85bfdd2e58c0b93ed9e4516770fd45627ea535

Active Wallet Key (*):
   -Fingerprint:           1409356558
   -Label:                 CR CATS TN10 Issuer
   -Sync Status:           Synced

Wallet Keys:
1)    3830434144   main farm
2)    1645933707   esaung hot wallet
3)    2920272449   TN10 - Custody
4)    3049838316   Documentation demo wallet tn10
5)    1964611303   pawket tn10 wallet
6)    233773231    NFT wallet
7)    2618175902   Background wallet
8)    2780699030   test walleth tn10
9)    1783862898   mainnet exp
10)   2803029382   TN10 main wallet
11)   1498393629   TN10 CF bag wallet
12)   965505910    tn10 chia nft use case test wallet
13)   852356298    nucle wallet
14)   107923803    mainnet test wallet
15)   2691838111   Big Big of NFts
16)   2867337490   5k tn10 NFT test wallet
17)   2752540257   Frodo wallet testnet
18)   3208516197   Jeff's CB test wallet
19)   1622336804   jeff cb test wallet 2 untrusted opera
20)   3554663204   Bob - Demo wallet (Issuer)
21)   87074341     VC (Issuer)
22)   150642830    David - Restaurant Manager
23)   1477437356
24) * 1409356558   CR CATS TN10 Issuer
Choose a wallet key [1-24] ('q' to quit, or Enter to use 1409356558): 24
Exception from 'wallet' {'error': 'Wallet needs to be fully synced before sending transactions', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/wallet_rpc_api.py", line 1064, in send_transaction_multi\nValueError: Wallet needs to be fully synced before sending transactions\n'}:
Traceback (most recent call last):
  File "chia/cmds/cmds_util.py", line 119, in get_any_service_client
  File "chia/cmds/cmds_util.py", line 235, in get_wallet_client
  File "chia/cmds/coin_funcs.py", line 245, in async_split
  File "chia/rpc/wallet_rpc_client.py", line 237, in send_transaction_multi
  File "chia/rpc/rpc_client.py", line 61, in fetch
ValueError: {'error': 'Wallet needs to be fully synced before sending transactions', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia/rpc/util.py", line 21, in inner\n  File "chia/rpc/wallet_rpc_api.py", line 1064, in send_transaction_multi\nValueError: Wallet needs to be fully synced before sending transactions\n'}

esaung@Chia-Macbook daemon % 

### Version

2.1.0rc2

### What platform are you using?

macOS

### What ui mode are you using?

CLI

**Comment by shaneo257** [comment]
seems to be a dup of https://github.com/Chia-Network/chia-blockchain/issues/15527

**Comment by esaung** [comment]
closing this issue since it's a dupe
