### ISSUE TITLE
bladebit always reports "Completed Plot 1", regardless of which plot in the run it is

### ISSUE THREAD

**Issue by cross** [Chia-Network/chia-blockchain#16440]
When using bladebit from chia, via `chia plotters bladebit cudaplot`, with a `-n N` (N=2, N=30, whatever), when each plot finishes it always reports "Completed Plot 1".

A grep of interesting [to me] lines from a run log:

```
[Sep 24 10:50:53] Generating plot 1 / 30: e9a0eb597518ddbb97343345983e84566dbd5b93395061dea3441e7b5d4f38cc
[Sep 24 10:51:36] Completed Phase 1 in 42.56 seconds
[Sep 24 10:51:49] Completed Phase 2 in 12.64 seconds
[Sep 24 10:54:58] Completed Phase 3 in 189.95 seconds
[Sep 24 10:54:58] Completed Plot 1 in 245.15 seconds ( 4.09 minutes )
[Sep 24 10:58:26] Completed writing plot in 207.92 seconds
[Sep 24 10:58:26] Generating plot 2 / 30: ce1e7063cfab574a9c82d3762d05eadc3d7254301d8be4a8167ec93296f50fd0
[Sep 24 10:59:09] Completed Phase 1 in 42.96 seconds
[Sep 24 10:59:22] Completed Phase 2 in 12.62 seconds
[Sep 24 11:02:40] Completed Phase 3 in 198.31 seconds
[Sep 24 11:02:40] Completed Plot 1 in 253.89 seconds ( 4.23 minutes )
[Sep 24 11:06:02] Completed writing plot in 202.09 seconds
[Sep 24 11:06:02] Generating plot 3 / 30: d621228d52cf4ca10cb839f3b2ca242f343778bac8cfe27e4e8730da028b0102
[Sep 24 11:06:45] Completed Phase 1 in 42.24 seconds
[Sep 24 11:06:57] Completed Phase 2 in 12.63 seconds
[Sep 24 11:10:10] Completed Phase 3 in 192.69 seconds
[Sep 24 11:10:10] Completed Plot 1 in 247.56 seconds ( 4.13 minutes )
```

(also, the inconsistency of capitalization in these messages is weird, that should be improved.  But, that's not this issue.)

**Comment by wjblanke** [comment]
The plotter runs one by one so this may be hard to fix.

**Comment by cross** [comment]
It is a separate invocation of another app that does each plot?  Otherwise, there should be state at the same level as the app that prints "Generating plot X / Y".
I guess if it is a separate app that doesn't know N != 1, we could just change it to say "Completed Plot", since if N is always 1 there's no need to say it in that line.

**Comment by wallentx** [comment]
It also takes a bit longer for bladebit to allocate buffers for the first plot, which if plotting via the Chia CLI, is every time. The buffer allocation time isn't factored into the recorded plot creation time, so you may overlook this. Executing the `bladebit_cuda` command instead would ensure that you only allocate buffers for the first plot.

**Comment by harold-b** [comment]
I second what @wallentx said. The bladebit executables are bundled w/ the chia setup, or you can find the standalone releases [here](https://github.com/Chia-Network/bladebit/releases).

**Comment by cross** [comment]
Okay.  I suggest this be documented as a recommendation.  Which will of course cause people to suggest what I did, and do it right from chia, but.  :-). 
One thing that's not described here is _why_ it runs separately for each plot?
