### ISSUE TITLE
[Bug] Starting Services - Full Node (Stuck)

### ISSUE THREAD

**Issue by RickyTinno** [Chia-Network/chia-blockchain#16540]
### What happened?

Update do new version (2.1.0)

Starting Services - Full Node (Stuck)

I restarted the machine, repeated the reinstallation (2.1.0) and it didn't solve the problem.

### Version

2.1.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Tomek1127** [comment]
The same here!

**Comment by mavaro** [comment]
The same here! 

Full node is not starting in Windows (Server 2019). I've tried too to restart the server, reinstall de 2.1.0 with no luck. Full node in 2.1.0 is not starting!

**Comment by KickerCZ** [comment]
Same here on Windows 11, help please

**Comment by advlive** [comment]
SAme problem after update wallet synced but full node not

**Comment by shaotaikota** [comment]
Same issue for me also.

**Comment by FedericoLaTorre** [comment]
Same problem on linux.

**Comment by majekqwert** [comment]
Deleting the database and re-synchronizing helped me.

**Comment by Tomek1127** [comment]
> Deleting the database and re-synchronizing helped me.

What you delete exactly??

**Comment by erickaoshoulin** [comment]
Same problem here

**Comment by KickerCZ** [comment]
Confirmed, just stop chia services and renamed .chia\mainnet\db to db.old. Client working and synchronization started. I guess it will take some time...

**Comment by KickerCZ** [comment]
To sync faster after DB erase - use official DB from torrent: https://www.chia.net/downloads/#database-checkpoint

**Comment by BrandtH22** [comment]
Hey all, keep in mind that the v1 db is no longer supported in version 2.1.0 . 

You can update by either running the cli command or by downloading the latest snapshot and replacing the v1 db:
CLI command - https://docs.chia.net/cli/#upgrade
DB Snapshot - https://www.chia.net/downloads/#database-checkpoint

**Comment by mavaro** [comment]
> Hey all, keep in mind that the v1 db is no longer supported in version 2.1.0 .
> 
> You can update by either running the cli command or by downloading the latest snapshot and replacing the v1 db: CLI command - https://docs.chia.net/cli/#upgrade DB Snapshot - https://www.chia.net/downloads/#database-checkpoint

I looked at it and I'm using v1 db... So that's the problem, then.
I'll try to upgrade it and reinstall 2.1.0.
Thanks a lot!

**Comment by guzzi235** [comment]
Full node is not starting in Windows 10. I've tried too to restart the server, reinstall de 2.1.0 with no luck. Full node in 2.1.0 is not starting!

**Comment by majekqwert** [comment]
delete all files from .chia\mainnet\db
Either wait for synchronization or download the database from https://www.chia.net/downloads/#database-checkpoint
If you download the database, you no longer need to upgrade it to v2, it is already v2. Just remember to change the file path in config.yaml

**Comment by mr2guru** [comment]
The same happed to me, so I had to re-install 2.0.0 and everything worked again.

**Comment by advlive** [comment]
I back to 2.01 and worked after 30 min

**Comment by notillfarm** [comment]
I used the CLI command to start the full node and then open the GUI and it worked

**Comment by RickyTinno** [comment]
The problem has been identified and we already know how to resolve it. Thank you all for your help.

**Comment by clamatac** [comment]
same problem, waiting for a fix

**Comment by williamje1** [comment]
Chia update 2.1.0 and 2.1.1 now working after upgrade to blockchain v2.

![Chia V2 upgrade](https://github.com/Chia-Network/chia-blockchain/assets/53337571/0fea4a64-74e6-46f6-a619-551686e2585f)
