### ISSUE TITLE
[Bug] Trouble finding plots on networked drives (windows)

### ISSUE THREAD

**Issue by jbdawinna** [Chia-Network/chia-blockchain#16554]
### What happened?

I upgraded from version 2.0.1 to version 2.1 and it only detected the local hdd's on the computer and none of the network hdds. The network hdds are actually hdds on another machine, they show up as shortcuts and direct to an application "nomachine" which lets me share the screen as well as hard drives between computers on the same network. It has worked for every version until now.

### Version

2.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Can u give us the log output where the plots aren't being found

**Comment by wjblanke** [comment]
Would need to run the previous version to see if a dependency update caused a path regression here. Let us know if u can try that.
