### ISSUE TITLE
[Bug] Stuck on Starting Services: Full Node

### ISSUE THREAD

**Issue by timothykruse** [Chia-Network/chia-blockchain#16559]
### What happened?

I installed the new version from the previous newest version, now Chia won't start.  It gets stuck on the starting services page, full node step.  Everything else gets loaded.

### Version

2.1.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by LJ-Corsica** [comment]
It's the same for me. The new version loads and hangs (on the starting services pages).

**Comment by rolandbezemer** [comment]
same problem for me, I use MacOS Intel. Tried several times, reinstall, restart, MacOS update, but nothing works. No farming all day...

**Comment by pokeplayer2** [comment]
I have the same issue on Windows, which information do you need to find the root cause ... where are the log files located?

**Comment by ALEXSPINDER** [comment]
Yep, here too. Feels like 2.0.1 all over again...

**Comment by liou4768** [comment]
我從之前的最新版本安裝了新版本，現在 Chia 無法啟動。它卡在啟動服務頁面

**Comment by Camulos** [comment]
Same here, going to try roll back to 2.0.1

**Comment by BrandtH22** [comment]
Hey @timothykruse , @LJ-Corsica , @hoholo18 , @racingdario , @rolandbezemer , @pokeplayer2 , @ALEXSPINDER , @liou4768 , and @Camulos: 

Please make sure your blockchain db is upgraded to v2, per the release notes 2.1 no longer supports the v1 db.

To upgrade you can either use the cli commands or download the latest official snapshot.
CLI commands - https://docs.chia.net/cli/#upgrade
Snapshot download page - https://www.chia.net/downloads/#database-checkpoint


Translated using a translation software:
Asegúrese de que su base de datos de blockchain esté actualizada a v2, según las notas de la versión, 2.1 ya no es compatible con la base de datos v1. Para actualizar, puede usar los comandos cli o descargar la instantánea oficial más reciente. 

Comandos de la CLI - https://docs.chia.net/cli/#upgrade 
Página de descarga de instantáneas - https://www.chia.net/downloads/#database-checkpoint


請確保您的區塊鏈資料庫已升級到 v2，根據發行說明 2.1 不再支援 v1 db。 

要升級，您可以使用 cli 命令或下載最新的官方快照。 
CLI 命令 - https://docs.chia.net/cli/#upgrade 
快照下載頁面 - https://www.chia.net/downloads/#database-checkpoint

**Comment by dvd101x** [comment]
Hi, mine is V2 and is experiencing the same issue.

**Comment by xiaomaque69** [comment]
> Same here, going to try roll back to 2.0.1

hello，How to roll back 2.0.1

**Comment by 6PACandOtto** [comment]
Had the same issue, 2.1.0 hangs up in "Starting Services" perpetually. Tried re-downloading the 2.1.0 installer for Windows and re-installed 2.1.0 and experienced the same issue, it won't start services.

I rolled back to 2.0.1 and it immediately worked.

**Comment by rolandbezemer** [comment]
I have no idea on how to upgrade my blockchain db to v2 on MacOS using the instructions given above. The chia website speaks of locating the map /Users/<YOURUSERNAME>/.chia/mainnet/db/. I cannot find it via Finder on my MacBook. Any tips for dummies?

**Comment by rolandbezemer** [comment]
Is there a place where I can download the old v2.0.1??

**Comment by dvd101x** [comment]
To roll back to a previous version you have to install the previous version, you can find the download links in the download section at the bottom of the page on it’s respective release notes for the version you are looking for.

**Comment by BrandtH22** [comment]
Hey @dvd101x , @xiaomaque69 , and @6PACandOtto ; if you already have the v2 db and have given the chia client at least 5 minutes on the starting services screen to no avail can you please provide your log files from ~\.chia\mainnet\logs\ ?

Note - changing your logs to DEBUG mode will be very helpful for us, to do this:
1. Shut down the chia client
2. Run `chia configure -log-level DEBUG`
3. Start the chia client

The goal is for us to gain more information on what might be causing the hangup on the starting services screen, thus far we know of two reasons:
- The db being outdated (needing to upgrade to v2)
- The client rebuilding the height to hash and sub epoch files (hence needing to wait ~ 5-10 minutes on the starting services screen)

Once we have the log files we will have a better idea as to what can solve the issues being experienced. Thank you all!

**Comment by BrandtH22** [comment]
Hey @rolandbezemer , the specifics on upgrading the database on mac are here:

```
1. Stop the chia client (this can be done while chia is running but stopping the client saves from any potential issues)
2. Run the command `chia db upgrade` (you do not need the input or output paths if these are still default)
- NOTE - if you receive an error indicating chia is not found, first run `PATH=/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon:$PATH` then try running the `chia db upgrade` command
- This process will take some time and requires additional space as the v1 db is compacted into the v2 db which leaves the v1 db intact
3. After the above completes start the chia client
4. If all loads up properly (might take ~5-10 minutes to load) then you can safely delete the v1 db found here (~/Users/brandtholmes/.chia/mainnet/db/blockchain_v1_mainnet.sqlite)
- NOTE - you may need to enable hidden files on finder by clicking 'Command' + 'Shift' + '.' (the period key)
```

As for the torrent, I personally use qbittorrent and the speeds for that download are dependent on how many peers are seeding the db and your network speeds. 
Once that file is downloaded, the built in mac tools should allow you to unpack and unzip the file. 
Once unzipped you will need to rename the .sqlite file to remove the date information and move the files to the mainnet db folder (~/Users/brandtholmes/.chia/mainnet/db/)
- NOTE - you may need to enable hidden files on finder by clicking 'Command' + 'Shift' + '.' (the period key)

**Comment by Sohojoe** [comment]
@BrandtH22 - when I start 2.1.1 I see this error which I read as I need to update my database:

```
stderr: RuntimeError: BlockStore does not support database schema v1
```

However, when I run ```chia db upgrade``` It says I do NOT need to migrate:

```
\Chia>chia db upgrade
Checking if userData migration is needed
AppData\Roaming\Chia Blockchain\Local Storage\leveldb exists: true
Chia Blockchain\Local Storage\leveldb exists: true
Chia Blockchain\Local Storage\leveldb\migrated exists: true
Migration needed: false
```

**Comment by BrandtH22** [comment]
Hey @dvd101x  , @xiaomaque69 , @rolandbezemer  , and @6PACandOtto ; another thing to check is that the config file parameter for the db indicates v2:

The config file is found at ~\.chia\mainnet\db
The parameter to search for is in the full_node section:
`database_path: db/blockchain_v2_CHALLENGE.sqlite`

Make sure that indicates v2 and not v1 (leave the "CHALLENGE" indicator as is)

Note you can also have a new config automatically created with the correct parameter by:

```
1. Stop the chia client
2. Rename the current config.yaml to config.yaml.old `~\.chia\mainnet\config\`
3. Run `chia init`
4. (OPT) Copy any custom settings from config.yaml.old to the new config.yaml (drive, trusted peer, and pool information)
5. (OPT) Start the chia client
```

**Comment by rolandbezemer** [comment]
I am sorry @BrandtH22 : but the commands 'chia init' nor 'chia db upgrade' work. All I get on my MacBook is 'command not found: chia'. I did find the path though: `PATH=/Apps/Chia/Contents/Resources/app.asar.unpacked/daemon:$PATH`. 
For the time being I re-installed v2.0.1 to keep farming but I fear I have to unzip the database checkpoint files which will cost me 180 days. Is there another way?

**Comment by Camulos** [comment]
After adding the v2 files in the DB-folder, is the three v1 files still needed?

**Comment by dvd101x** [comment]
Thanks @BrandtH22, followed the steps related to config debug, etc.

I change the config file in `~.chia\mainnet\config` not in `~.chia\mainnet\db`

The change to V2 is something I did when it was implemented by downloading a checkpoint in the database.

The log files show nothing during the period the GUI is stuck, just information from previous days
```
2023-09-27T11:15:50.918 harvester chia.plotting.util      : WARNING  Directory: V:\p does not exist.
2023-09-27T11:15:51.060 harvester chia.plotting.manager   : WARNING  Not farming plot Q:\p\plot-k32-2021-07-09-19-43-a5830f7c9d443c1d438d217819f22f73e1c957875137dd809a892e1adce2b979.plot. Size is 98.09057507663965 GiB, but expected at least: 101.4 GiB. We assume the file is being copied.
2023-09-27T11:17:52.233 harvester chia.plotting.util      : WARNING  Directory: V:\p does not exist.
2023-09-27T11:17:52.358 harvester chia.plotting.manager   : WARNING  Not farming plot Q:\p\plot-k32-2021-07-09-19-43-a5830f7c9d443c1d438d217819f22f73e1c957875137dd809a892e1adce2b979.plot. Size is 98.09057507663965 GiB, but expected at least: 101.4 GiB. We assume the file is being copied.
2023-09-27T11:19:53.343 harvester chia.plotting.util      : WARNING  Directory: V:\p does not exist.
```

I did install the version 2.1.1 and tested the same thing, with no luck. Still stuck for hours in:
> starting services
> - full node

I did roll back to 2.0.1 and it just works.

**Comment by ccynet** [comment]
I also encountered the same issue. My system version is Ubuntu 20.04, and the Chia version is 2.1.1. The db was downloaded from a torrent. It ran normally for several days. However, after a regular computer reboot, when I tried to start Chia again, it constantly remains at 'Starting Services: Full Node'. Additionally, I'd like to point out that I had properly shut down Chia before turning off the computer.

**Comment by arkanoider** [comment]
Same here stuck on Full Node launch with 2.1.0 and 2.1.1 on windows 10.
Roll back to 2.0.1 and works..
Following here for a solution.

**Comment by altendky** [comment]
If anyone could run the full node process directly, not through the gui and also not through `chia start`, it might provide some useful output on stdout.  There's a change that will, in the future, make more of this end up in the log, but for now we have some early errors that don't.

**Comment by wjblanke** [comment]
Can you guys send us your complete DEBUG debug.log file when this happens? That should tell us the reason why node can't start.

**Comment by bitcoinGreece** [comment]
I **FIX** the problem with an easy way, 
It will take time but you need no special skills to do it. 
Delete all your files in db folder and let it sync again from the beginning. 

Your db folder for Windows Systems
C:\Users\<YOURUSERNAME>
└─ .chia/
    └── mainnet/
       └─ db/
       
Your db folder for macOS and Linux Systems
/Users/<YOURUSERNAME>
└─ .chia/
    └── mainnet/
       └─ db/

**Comment by mressler** [comment]
Mine ended up being a corrupted DB issue. When I downloaded the Checkpoint DB and updated my DB, my node started up no problem.

**Comment by dvd101x** [comment]
Tried the same thing and now it's syncing.

**Comment by bitcoinGreece** [comment]
Sync from the beginning is the best solution but it will need up to 4 days

**Comment by OneDayAgency** [comment]
> Solution I **FIX** the problem with an easy way, It will take time but you need no special skills to do it. Delete all your files in db folder and let it sync again from the beginning.
> 
> Your db folder for Windows Systems C:\Users<YOURUSERNAME> └─ .chia/ └── mainnet/ └─ db/
> 
> Your db folder for macOS and Linux Systems /Users/ └─ .chia/ └── mainnet/ └─ db/

This works!

**Comment by mressler** [comment]
Just so everyone knows, syncing from 0 will work, but will take a VERY long time. To overcome this, Chia devs have provided a checkpoint DB. The latest of these checkpoints can always be found in the [downloads page](https://www.chia.net/downloads/) on chia.net.

**Comment by rolandbezemer** [comment]
finally was able to upgrade to 2.1.1. Using Utorrent to download the October 1, 2023 checkpoint, it did download the zip file and with many peers it was done in under an hour. Unzipped the files, removed the "date" from the filename blockchain_v2_mainnet.sqlite, and placed the three files in the .chia/mainnet/db map. Removed the v1-files, installed Chia version 2.1.1 and ran the node. Apparently it has to resync from the start again

**Comment by rolandbezemer** [comment]
I managed to upgrade to v2.1.1, synced allright, but had to add my plots again. For my pooled plots (about 10% of my plots) I do not know how to rejoin my pool. I forgot my pool name. Is there anyway I can rejoin my pool?

**Comment by wzz789** [comment]
My final solution: Download Oct 1,2023 DB from Chia website, unzip, Close Chia 2.0.1, install 2.1.1 but don't run it, create a new subfolder under DB folder named OLD, and move the old V1 DB files into it. Copy unzipped 3 files to the DB folder, renamethe V2 file to _blockchain_v1_mainnet.sqlite_, run 2.1.1, it will start normally and sync from Oct 1,2023. now you can delete OLD V1 DB to free up the space.
