### ISSUE TITLE
[Bug] Not able to mint NFT if reuse_puzhash

### ISSUE THREAD

**Issue by YeungTing** [Chia-Network/chia-blockchain#16558]
### What happened?

Not able to mint NFT if reuse_puzhash

### Version

2.1.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
File "chia\wallet\nft_wallet\nft_wallet.py", line 413, in generate_new_nft
  File "chia\wallet\nft_wallet\nft_wallet.py", line 311, in get_did_approval_info
  File "chia\wallet\did_wallet\did_wallet.py", line 773, in create_message_spend
AssertionError
```

**Comment by YeungTing** [comment]
any updates?

**Comment by BrandtH22** [comment]
Hey @YeungTing , I have just tested both a DID and a non-DID based mint with reuse puzzle hash and both worked without issue on 2.1.0.

I believe the error you are seeing resides in the wallet not being able to create the necessary DID spend for minting with a DID (might be that the DID coin has been lost and needs to be found using the find_lost command).

To verify can you try minting an NFT without a DID (or with a newly created DID)?

**Comment by BrandtH22** [comment]
Troubleshooting and followup is occurring in discord (https://discord.com/channels/1034523881404370984/1034870571864948777/1161351169625571428)

**Comment by YeungTing** [comment]
this is spendable coin record in did wallet, some how it contain invalid information. some coint "amount" = 0. The implementation in 1.8.3 can filter out invalid coin, much better than the implementation in 2.1.0. Please revert it.


{
    "confirmed_records": [
        {
            "coin": {
                "amount": 0,
                "parent_coin_info": "xxxxxxxxxxxxxxxxxxxxx",
                "puzzle_hash": "xxxxxxxxxxxxxxxxxxxxx"
            },
            "coinbase": false,
            "confirmed_block_index": 38XXXXX,
            "spent_block_index": 0,
            "timestamp": 168XXXXXX
        },
        {
            "coin": {
                "amount": 1,
                "parent_coin_info": "xxxxxxxxxxxxxxxxxxxxx",
                "puzzle_hash": "xxxxxxxxxxxxxxxxxxxxx"
            },
            "coinbase": false,
            "confirmed_block_index": 43XXXXX,
            "spent_block_index": 0,
            "timestamp": 169XXXXXX
        },
....
]
