### ISSUE TITLE
ATASCADO Y MUY PRINCIPIANTE

### ISSUE THREAD

**Issue by RIFAURU** [Chia-Network/chia-blockchain#16553]
Buenos días a todas y todos. Actualice a 2,1.0, desafortunadamente no soy programador y quedo girando la bolita toda la noche del sábado (iniciando el servicio nodo completo) y nada. En lo comentarios veo que borrar la base v1 que no es compatible. Alguien tiene un paso a paso (con plastilina) para poder hacerlo. Muchas gracia por su ayuda.

**Comment by RIFAURU** [comment]
ClydeWallace22 Muchas gracias por su colaboración. Como soy un principiante
voy a seguir el paso a paso. Mil y mil gracias. ClydeWallace22 Thank you
very much for your collaboration. Since I am a beginner I will follow the
step by step. A thousand and a thousand thanks.

**Comment by dvd101x** [comment]
Hi @RIFAURU,

Personally in had this issue today when updating to 2.1.0, I swapped back to 2.0.1 and all is working.

I don't think this issue has been accepted yet, you might try this method in the meantime it's resolved.

**Comment by RIFAURU** [comment]
Thank you very much, fortunately I returned to version 2.01 and it is
working fine. Of course it has problems from time to time, because I am
farming, cultivating and transferring plots to other storage units. I thank
you very much for your collaboration. And nice to meet you Ricardo Fandino
U. from Bogota Colombia.

Mil gracias, Si afortunadamente regrese a la version 2.01 y esta
funcionando bien. Claro tiene problemas cada cierto tiempo, porque estoy
farmeando, cultivado y haciendo traslados de parcelas a otras unidades de
almacenamiento. Le agradezco mucho su colaboracion. Y mucho gusto Ricardo
Fandino U. desde Bogota Colombia
