### ISSUE TITLE
install.sh fail on raspberry pi 4

### ISSUE THREAD

**Issue by Guitouille** [Chia-Network/chia-blockchain#166]
Hello,
I am encountering the following issue when following the installation process.
My pi 4 is freshly installed with the Raspbian OS with the required packages (I have followed the Debian/Ubuntu installation process).
Not sure what I can do from here, i will continue to search though.

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
npm is already the newest version (5.8.0+ds6-4).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Python version is 3.7
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in ./venv/lib/python3.7/site-packages (20.0.2)
Looking in indexes: https://hosted.chia.net/simple/, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement miniupnpc==2.0.2 (from versions: none)
ERROR: No matching distribution found for miniupnpc==2.0.2
```

**Comment by Guitouille** [comment]
I thought the problem was from raspbian, but I am reproducing the same problem on an Ubuntu server 19 on the raspberry pi 4. No luck so far :(

**Comment by hoffmang9** [comment]
That particular issue is that there is no binary wheel for ARM re miniupnpc. You can remove if from setup.py as it's not critical or you can enter the venv, and pip install it from source (assuming you have some base development environment installed.)  Try
```
pip install --force-reinstall --ignore-installed --no-binary --nocache miniupnpc==2.0.2
```

I will be reinstalling our test Pi 4 in the next day or two and will put up detailed instructions for it on the wiki if you don't easily get past this until I get a chance to look closely at it.  You can also use some of these hints for BSD: https://github.com/Chia-Network/chia-blockchain/wiki/FreeBSD-Install

**Comment by Guitouille** [comment]
Indeed the pip install from source worked, the only adjustment I had to do is to add the others lib
```pip install --force-reinstall --ignore-installed --no-binary --nocache miniupnpc==2.0.2 setproctitle==1.1.10 cbor2==5.0.1```

So the process has been able to go further, I had to install some other package though: 
`sudo apt-get install python3-dev libgmp-dev libboost-dev`

Now I am facing something else, I have attached some logs. Not sure if this can be fixed with just a missing dependency though.
[log.txt](https://github.com/Chia-Network/chia-blockchain/files/4472107/log.txt)

**Comment by xorinox** [comment]
I know about the issue when compiling on ARM64, this pulls code that isn't compatible with ARM and appears to be optimized for x86 only. I figured for a harvester you don't need to compile chiavdf, so I commented it out in setup.py  (look for line chiavdf = 0.12.3), sure that might not be a workaround for everyone

`  In file included from vdf_client.cpp:2:
  vdf.h:3:10: fatal error: x86intrin.h: No such file or directory
      3 | #include <x86intrin.h>
        |          ^~~~~~~~~~~~~`

**Comment by hoffmang9** [comment]
If you look at https://github.com/Chia-Network/chia-blockchain/wiki/Raspberry-Pi you will see the magic workaround for the x86-64 optimized Timelord.

**Comment by hoffmang9** [comment]
Working for Pi 64bit OSes https://github.com/Chia-Network/chia-blockchain/wiki/Raspberry-Pi

**Comment by robert-claypool** [comment]
Just FYI, `No matching distribution found for miniupnpc==2.1` also happens on Manjaro when running https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chia-gui-git line 37: `pip install --extra-index-url https://download.chia.net/simple/ miniupnpc==2.1`

I'm on a 64bit architecture (`uname -m` returns `x86_64`).

**Comment by AdevelopD** [comment]
Hi @all
 
I found the problem. I use RaspiOS 64bit from 03-04-2021 and was able to execute the script and install everything after changing the access to the internet. Speak instead of LAN and PiHole, Access Point by mobile phone and everything works great! Maybe that will help someone.

**Comment by TCB13** [comment]
> Just FYI, `No matching distribution found for miniupnpc==2.1` also happens on Manjaro when running https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chia-gui-git line 37: `pip install --extra-index-url https://download.chia.net/simple/ miniupnpc==2.1`
> 
> I'm on a 64bit architecture (`uname -m` returns `x86_64`).

I'm also having this issue now in Debian 10 on a 64 bit CPU...

``````
root@chia:~/chia-blockchain# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@chia:~/chia-blockchain# uname -m
x86_64
``````

**Comment by emlowe** [comment]
pip made an update that broke our (not-legal-HTML) simple py repo. However, they then made another update to allow it to work but prints out a deprecation warning. Update to latest pip and it should be working again
