### ISSUE TITLE
Some plots decide to pause with no error and do not continue [BUG]

### ISSUE THREAD

**Issue by deslumoprime** [Chia-Network/chia-blockchain#1660]
**Describe the bug**
Some plots decide to pause with no error and do not continue. GUI reports as "Plotting", but the log hasn't updated since it froze. Requires all TEMP files to be manually deleted and for the plot to be deleted so next one in queue can take its place. This usually solves the problem, but doesn't affect other plots doing the same. After system restart, problem disappears entirely for a while, then comes back. 

**To Reproduce**

1. Create a k32 plot with CPU set to the number of total threads and leave RAM untouched. Repeat however many times your SSD can support. This is to create parallel queues. 

2. Allow plots to finish, eventually, some will stop making progress. You'll see that the progress bars for some plots will be behind others, and the log's last update will be too long ago to justify it making progress. No error codes will be recorded. 

**Expected behavior**

Plotting SHOULD continue without such freezing or pausing, or at the very least leave error messages. 

**Screenshots** (For some context, the time this picture was taken was 17:55, and usually the log updates every couple seconds with new information)

![image (1)](https://user-images.githubusercontent.com/77915441/113463804-fbb58e80-93dc-11eb-8eed-e3489a5284e5.png)

**Desktop:**

- OS: Windows 10 Pro 
- OS Version/Flavor: 19042.867
- CPU: AMD Ryzen 5 5600X
- Memory: 32GB
- Storage: (Temp - 1.6TB RAID 0), (Permanent: 24TB RAID 0)

Thank you!

**Comment by Teledyol** [comment]
I'm getting the same, even with straight parallel plotting with GUI. They are stuck at 40% completion I will have to try cutting back to "3 plots at a time" where I already got to 40 plots using the "4 at a time" setting, I think the [BUG] label shoulf reappear…

Previously I was trying the Queue hack, when this problem appeared:
https://github.com/Chia-Network/chia-blockchain/issues/1654

**Comment by Teledyol** [comment]
Actually, this is the third fail. Previously two plots (of four) failed to complete after 70% https://github.com/Chia-Network/chia-blockchain/discussions/1645

Look in comments section

**Comment by Teledyol** [comment]
Even though they all stuck at 40% six hours ago for a couple hours the progress bar now shows 90%. Is it possible that the issue is with the progress bar?

Six hours ago when it was at 40% the available space on my SSD — without other processes running — was varying between 650 GB available to 150 GB available for the hour and a half that I was watching it; while the progress bar was at 40% the whole time.

Over the last 20 minutes the progress bars (4 plots) have gone from 87% to 90%

**Comment by hoffmang9** [comment]
You are likely trying to do too many in parallel. Usually on Windows that means you start swapping where now your memory, CPU and disk are all fighting as CPU is trying to swap things to disk while plotting things to disk. I'll leave this open a little longer but it's not a bug.

**Comment by Teledyol** [comment]
Others on Reddit feel that a tested process and feature of queueing in parallel needs to be added to the GUI

https://www.reddit.com/r/chia/comments/mgvzwd/save_plotting_profile_execute_plotting_profile_x/?%24deep_link=true&correlation_id=57e66a07-d20a-4464-8fe5-0d6e7689c6c9&post_fullname=t3_mgvzwd&post_index=1&ref=email_digest&ref_campaign=email_digest&ref_source=email&utm_content=post_title&%243p=e_as&_branch_match_id=772486460450704319

**Comment by hoffmang9** [comment]
There is queuing it is just totally hard to use. This is the minimum viable product and will get enhanced but that doesn't change that you are overscheduling your machine.

**Comment by Teledyol** [comment]
After 1.0.3 I saw the 20% plotting speed enhancement doing 4 in parallel with about 1.7TB available space on the SSD. Then I saw a failure of two plots in the following task, which I scrapped and tried the Parallel queue hack for 4 in parallel. After churning at 40% for a few hours, I scrapped that and went back to the regular method. I now longer saw that 20% speed enhancement, it just finished "successfully" (since I still haven't farmed any XCH). I'm now at 46 plots.

I'm trying to stagger 3 queues in parallel to see if your "overscheduling" contention makes a difference.

My perception is that something with the plotting changed about 24hours after the 1.0.3 release and that that change is increasing the amount of space needed for the .tmp files. 

My average plotting performance is decreased by 25% over the last 48hours

**Comment by hoffmang9** [comment]
Nothing changed in the software. SSDs slow as they start to approach total TBW. Something is up with your hardware.

**Comment by Teledyol** [comment]
As far as I know the change in my side is that I was away from this hardware more over the last 48 hours

I changed to the 3 from 4 (which was working for 40 plots. It's queued up and running (at 8% now, which seems faster) so we see what happens ove the next couple days. I set queues at 3, 4 and five each. After the first nine, I plan on adding back to four in parallel (for 2 plots) to see if it slows the average over 24+ hours

**Comment by deslumoprime** [comment]
What's the suggested method for scaling with more in parallel? OS switch? Lower the amount of threads? I've done some plots with less allocated threads, those seemed to be much better in the fact that they didn't freeze. This is probably because there is less fighting for resources?

**Comment by hoffmang9** [comment]
If you look on Reddit or in Keybase the two reasons plots stall is thermal issues with the SSD or bad RAM. It's 80% bad RAM.

**Comment by Teledyol** [comment]
I tested my RAM (128GB) a couple weeks ago with a few testers and it did not report any issues. Doesn't mean that they are flawless, just that I haven't found any issues after looking.

However, I was able to dry out my iPods that my wife threw in the washer with my Trashcan

![Pro_Dry](https://user-images.githubusercontent.com/3718370/113488156-20f3dc80-9471-11eb-9d89-9cd210ac1b43.jpg)

**Comment by deslumoprime** [comment]
Does bad RAM refer to the memory chips being defective or because there's an unstable OC? I am running a DDR4 2133 rated kit of 32GB at around DDR4 2666, system hasn't crashed, but could this be the definition of bad memory?

**Comment by deslumoprime** [comment]
> I tested my RAM (128GB) a couple weeks ago with a few testers and it did not report any issues. Doesn't mean that they are flawless, just that I haven't found any issues after looking.
> 
> However, I was able to dry out my iPods that my wife threw in the washer with my Trashcan
> 
> ![Pro_Dry](https://user-images.githubusercontent.com/3718370/113488156-20f3dc80-9471-11eb-9d89-9cd210ac1b43.jpg)

Should've thrown the Airpods in the dryer. /s

**Comment by hoffmang9** [comment]
Bad RAM is the gamut of overclocking, XMP, and actual bad sticks. Memtest without load can lie to you.

**Comment by Teledyol** [comment]
Gene,

You ever get tired of being right?

![Screen Shot 2021-04-03 at 3 19 27 PM](https://user-images.githubusercontent.com/3718370/113493027-dbdfa280-9490-11eb-8800-22c259cd82f0.png)

Looks like #1 went bad on April Fools Day

**Comment by deslumoprime** [comment]
> You are likely trying to do too many in parallel. Usually on Windows that means you start swapping where now your memory, CPU and disk are all fighting as CPU is trying to swap things to disk while plotting things to disk. I'll leave this open a little longer but it's not a bug.

Holy, you're right! I set my memory back to the DDR4-2133 speed and lowered the threads for each plot, and so far, each plot is working perfectly! Thanks for helping and clarifying the issue!

**Comment by Teledyol** [comment]
…and finally snagged 2 XCH
