### ISSUE TITLE
access ongoing plotting process stdout in new ssh session?

### ISSUE THREAD

**Issue by michaelpalumbo** [Chia-Network/chia-blockchain#1665]
I accidentally closed my ssh session for my plotter running on linux. after logging in again via ssh and running ```. ./activate``` how can I access the stdout from the plotter to continue observing its progress?

Thanks!

**Comment by hoffmang9** [comment]
Unless you had nohupped your plotting process, Linux stops processes that lose a terminal.

**Comment by michaelpalumbo** [comment]
ah ok, very helpful thanks!
