### ISSUE TITLE
[Bug] Can't start Chia 2.1.0 or 2.1.1 on Raspberry Pi 4

### ISSUE THREAD

**Issue by vadd98** [Chia-Network/chia-blockchain#16662]
### What happened?

Hi. I tried to update Chia from 2.0.1 to 2.1.0 and 2.1.1 on my Raspberry Pi 4 but it doesn't start anymore. Downgrading to 2.0.1 it starts again.
My Raspberry is running on Debian Buster.

### Version

2.1.0

### What platform are you using?

Pi4

### What ui mode are you using?

GUI

### Relevant log output

```shell
[4575] Error loading Python lib '/opt/chia/resources/app.asar.unpacked/daemon/libpython3.10.so.1.0': dlopen: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/chia/resources/app.asar.unpacked/daemon/libpython3.10.so.1.0)
```

**Comment by yyolk** [comment]
You might have luck stopping the chia gui, do a system upgrade, and then restarting the device and running the updated version again.

**Comment by stefan-lange** [comment]
If possible you should consider to upgrade your Debian 10/buster at least to the next version 11/bullseye. Debian 10 is (near) EOL (https://wiki.debian.org/DebianReleases). Chia 2.1.0 uses a newer GLIBC version `2.29`.

Debian 10 contains GLIBC `2.28` (https://packages.debian.org/source/buster/glibc)
Debian 11 has `2.31` (https://packages.debian.org/source/bullseye/glibc)

My Pi4 works fine with Debian 12/bookworm, but it depends on your installed software.

**Comment by vadd98** [comment]
Thanks for your suggestion, I'll try to upgrade my Pi to bookworm

**Comment by dvd101x** [comment]
@vadd98 is it as described in #16559 ?

**Comment by vadd98** [comment]
@dvd101x I don't know for sure. I got the error starting the CLI, while on the other issue they talk about the GUI

**Comment by dvd101x** [comment]
@vadd98 sorry, my bad, I thought it was in GUI.

**Comment by mressler** [comment]
The other issue is whether starting from command line or from GUI. What is the error you're seeing when starting from command line?

**Comment by vadd98** [comment]
The error is the one reported in the first comment:

[4575] Error loading Python lib '/opt/chia/resources/app.asar.unpacked/daemon/libpython3.10.so.1.0': dlopen: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/chia/resources/app.asar.unpacked/daemon/libpython3.10.so.1.0)

**Comment by wjblanke** [comment]
Upgrading the OS should let the installer work. You can also build from source. That should use your local version of python/glibc.  Open a new issue if u have more problems.

**Comment by vadd98** [comment]
I forgot to update. I updated my raspberry and now it is working fine
