### ISSUE TITLE
[SECURITY][BUG] -- Do not hardcode CryptFileKeyring keyring_key

### ISSUE THREAD

**Issue by jnaulty** [Chia-Network/chia-blockchain#1667]
**Describe the Bug**
Hardcoding the `CryptFileKeyring` keyring_key seems like it defeats the purpose of using an encrypted keychain for storing private keys on a host.

If an attacker can exfiltrate the file, decryption is trivial since the passphrase to decrypt the keychain is hardcoded here: https://github.com/Chia-Network/chia-blockchain/blob/0252852bc02191892eb5f020f13aeefef5e457b6/src/util/keychain.py#L26-L27

From the keyrings.cryptfile README.md
> The keyring is secured with a keyring password.

This 'password' is the `keyring_key`. 

And this password is the critical component protecting decryption of the data (see cryptfile [README](https://github.com/frispete/keyrings.cryptfile/blob/e874e501371939c9914282b998859dbb668d277c/README.md#discussion):
> The items of the json dict constitute the encryption parameters and value. In theory, it should be sufficiently hard to get back to the plain value of data without knowledge of the password.

**Expected behavior**
I would expect users to be able to use their own keyring_key to encrypt their keychain file on disk. 
An example of using an environment variable is provided in the `keyrings.cryptfile` README under [Notes](https://github.com/frispete/keyrings.cryptfile/blob/e874e501371939c9914282b998859dbb668d277c/README.md#notes).
It would also be nice to be able to delegate this to a Key Management Service (e.g. a physical HSM, Amazon KMS, Hashicorp Vault etc).

```python
from getpass import getpass
from os import getenv
from keyrings.cryptfile.cryptfile import CryptFileKeyring
kr = CryptFileKeyring()
kr.keyring_key = getenv("KEYRING_CRYPTFILE_PASSWORD") or getpass()
keyring.set_keyring(kr)
```

**Desktop (please complete the following information):**

- OS: All Linux Systems

**Comment by hoffmang9** [comment]
Well aware that this is a crappy implementation. See the multiple entries around it in "Fast Follows" listed in https://trello.com/b/ZuNx7sET/engineering-core

**Comment by jnaulty** [comment]
Thanks for sharing, @hoffmang9 
I'll try to find the 'relevant entries' and list them here (for people who might want to help but have a hard time jumping between github, trello, keybase chat, etc

I've discovered the following Trello Entries, but none seem quite related to the issue I'm raising. 
Maybe you could point me directly to the Trello Task/Entry, @hoffmang9?

- https://trello.com/c/2UZTanps/603-allow-password-encryption-of-keys
This seems resolved already (Linux uses use the keyring.cryptfile to encrypt passwords

- https://trello.com/c/0kUZi6g2/602-linux-use-keychain-instead-of-unencrypted-file
This seems related to the Trello Task/Issue above (and also seems resolved)

- https://trello.com/c/k4jQR9w9/920-node-private-key-file-permissions
Not quite relevant, but of interest to me, and possibly something I can verify + help out with if it's not already implemented

- https://trello.com/c/dqFVg5WM/930-private-key-and-mnemonic-secret-linger-in-memory-after-key-deletion
Kind of interesting, not quite related

**Comment by maximilianmikus** [comment]
this issue should stay open until its resolved imho
