### ISSUE TITLE
[Bug] Loading farming data

### ISSUE THREAD

**Issue by Jutean** [Chia-Network/chia-blockchain#16672]
### What happened?

Always display Loading farming data

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Jutean , have you already upgraded your blockchain db to version 2 as outlined with two different methods here:
https://docs.chia.net/faq/#how-do-i-upgrade-my-version-1-blockchain-database-to-version-2

**Comment by Jutean** [comment]
> Hey @Jutean , have you already upgraded your blockchain db to version 2 as outlined with two different methods here: https://docs.chia.net/faq/#how-do-i-upgrade-my-version-1-blockchain-database-to-version-2

conversion failed with error: output file is the same as the input D:\backup\.chia\mainnet\db\blockchain_v2_mainnet.sqlite.
LEAVING PREVIOUS DB FILE UNTOUCHED D:\backup\.chia\mainnet\db\blockchain_v2_mainnet.sqlite
