### ISSUE TITLE
[Bug] Suddenly cannot recieve piad almost one month

### ISSUE THREAD

**Issue by jaysonZhou123** [Chia-Network/chia-blockchain#16671]
### What happened?

Hi Sir,
My Launcher Id:
0x10e85b52eb1abfad0af7d878743e4458dbd6a9fdef0ee5fdbd86d8d248f57eb9
Suddenly cannot recieve piad almost one month, Please help ASAP for this issue.
GUI upgrade from 1.8.1 to 2.1.1 but also cannot recieve daily paid from 28/Sep/2023 until now ?
BTW, Checked anything setting were correcte.
Stange thing is the Block Rewards still can recieved only daily paid sudden diappear almost one month from 28/Sep/2023 till now ??? Thanks for your urgent help.

### Version

1.8.1 to 2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

```[tasklist]
### Tasks
```

**Comment by BrandtH22** [comment]
Hey @jaysonZhou123 , it sounds like you might need to contact the pool you are farming with to verify they're sending the daily payments to the correct address.

On the chia gui side you can chack the farming rewards information on the farm tab's settings in the top right corner (click the three dots and select "Manage Farming Rewards"). These addresses are what the chia client uses but for teh daily payments I recommend reaching out to your pool and confirming with them that they have the correct address and are submitting daily payments (I know one of my pools changed the minimum payout amount recently and that affected when I receive payments)

**Comment by jaysonZhou123** [comment]
Dear BrandtH22,
Checked the "Manage Farming Rewards" were corrected!!! How to contact with space pool ?
Thank you.

**Comment by wjblanke** [comment]
contact spacepool on discord. thanks
