### ISSUE TITLE
[Bug] DAO Wallet Errors in CLI output when Starting GUI - main branch, clean install, wallet-only mode full sync

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#16689]
### What happened?

The below error appears in the cli output (not in the logs) after launching the chia gui from cli:

```
exception: Traceback (most recent call last):
  File "/opt/chia_devs/2.1.2-dev198/chia/wallet/dao_wallet/dao_utils.py", line 672, in match_proposal_puzzle
    c_a, curried_args = uncurry_proposal(curried_args.rest().first())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chia_devs/2.1.2-dev198/chia/wallet/dao_wallet/dao_utils.py", line 597, in uncurry_proposal
    raise ValueError("Not a dao proposal mod.")
ValueError: Not a dao proposal mod.
```

Steps to reproduce (note the below assumes a clean install of chia):
1. `git clone https://github.com/Chia-Network/chia-blockchain.git -b main --recurse-submodules`
2. `cd chia-blockchain`
3. `sh install.sh`
4. `sh install-gui.sh`
5. `chia init` (if you already had chia installed be sure to rename the config.yaml prior to running this command)
6. `bash start-gui.sh &` (if you already had chia installed be sure to remove the wallet db prior to running this command)
7. Wait for the wallet to sync and monitor the CLI output

Notes - 
- to reproduce the wallet needs to be synced from scratch
- this has been confirmed on linux and mac but is not present on windows

### Version

Main (2.1.2-dev198 ef98949a306d9d77b6753511a92d9581c5045ca2)

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
NA - logs do not contain any information regarding this error, it is only present on the CLI output
```

**Comment by d1m1trus** [comment]
```
exception: Traceback (most recent call last):
  File "/opt/chia_devs/2.1.2-dev199/chia/wallet/dao_wallet/dao_utils.py", line 672, in match_proposal_puzzle
    c_a, curried_args = uncurry_proposal(curried_args.rest().first())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chia_devs/2.1.2-dev199/chia/wallet/dao_wallet/dao_utils.py", line 597, in uncurry_proposal
    raise ValueError("Not a dao proposal mod.")
ValueError: Not a dao proposal mod.

```

```
exception: Traceback (most recent call last):
  File "/opt/chia_devs/2.1.2-dev199/chia/wallet/dao_wallet/dao_utils.py", line 739, in match_dao_cat_puzzle
    inner_puz = get_innerpuz_from_lockup_puzzle(uncurried.args.at("rrf"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chia_devs/2.1.2-dev199/chia/wallet/dao_wallet/dao_utils.py", line 279, in get_innerpuz_from_lockup_puzzle
    (
ValueError: not enough values to unpack (expected 5, got 1)

```

**Comment by wjblanke** [comment]
geoff can u take a look at this. not enough values to unpack (expected 5, got 1) seems like a bug

**Comment by geoffwalmsley** [comment]
This was fixed here: https://github.com/Chia-Network/chia-blockchain/pull/16691 Forgot to close this sorry
