### ISSUE TITLE
[Bug] Missing SP "Don't have challenge hash"

### ISSUE THREAD

**Issue by iliasorazov** [Chia-Network/chia-blockchain#16688]
### What happened?

Sometimes node trigger error processing the end of a slot.
```
full_node_store: INFO Don't have challenge hash <hash1>, caching EOS
full_node: INFO End of slot not added CC challenge <hash2>
full_node_store: INFO Don't have challenge hash <hash1>, caching EOS
--- many more identical lines ----
full_node: INFO End of slot not added CC challenge <hash2>
full_node_store: INFO Don't have challenge hash <hash1>, caching EOS
full_node: INFO End of slot not added CC challenge <hash2>
```

This error cause node to miss SP. This used to happen twice a month, but recently it may happen 8 times a day. It coincided with a new ASIC timelord release.

### Version

1.8.0+

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
ASIC timelords will make the network run 10% faster until difficulty resets. Its sounds like things are coming in out of order to your node, possibly because other nodes are having problems keeping up? What kind of system is your node running on?

**Comment by iliasorazov** [comment]
What do you mean under "out of order"? A better challenge hash is coming second and dropped? This is a bug then. The node is getting more such errors if you increase the number of peers it connects to. With 16 connections it may get 4 such errors a day, with 64 connections it is getting 8 errors a day. A better connectivity only make it worse.

**Comment by iliasorazov** [comment]
Do you have plans to fix the bug? Yesterday we've missed 6 SP running two nodes that are connected to around 100 other peers.

**Comment by wjblanke** [comment]
network latency can cause issues with sp order just because of propogation. 6 dropped in a day versus 8500 in all is not bad. the asic speeding up the chain 10% could certainly exacerbate this. network stability, connectivity and cpu performance factors in as well. a powerful node on a cloud instance with great network connectivity and many many peers likely will have no issues, eg. this is not bad tho.

**Comment by iliasorazov** [comment]
> a powerful node on a cloud instance with great network connectivity and many many peers likely will have no issues,

This is exactly what we have. A better connectivity actually cause node to miss more SP due to this error.

This error has nothing to do with propagation delay. Unless you consider a few second delay a critical. This error is caused by the lack of backtracking ability in the node. It receives challenge hashes out of order. Check out the error log. Today we've missed 7 SP because of this. Please reopen the issue and fix it.
