### ISSUE TITLE
Plots stuck

### ISSUE THREAD

**Issue by jansila** [Chia-Network/chia-blockchain#1669]
Hi guys,

I am trying to start farming, but the plot (32k) gets always stuck after a while. I only attempt to run one at a time and currently is stuck at 25%.

```Only read 0 of 262132 bytes at offset 753891632 from "D:\\chia_temp\\plot-k32-2021-04-03-09-55-a11003f9a60eaae72b7b248e878b5e869457edd6c0b8e31b66bb75ea6f8120d0.plot.p1.t4.sort_bucket_033.tmp"with length 872443286. Error 1. Retrying in five minutes.```

During the downloading it has happened a couple of times and then carried on, now it is been hanging there for couple of hours. 

I have a 2TB hardrive, freshly formatted. Since my system SSD is only 100GB large, I created `chia_tmp` and `chia` directories on the 2TB drive. That should not be a problem in general, right? Please, do you have any ideas how to fix this?
The machine has Win 10 (bummer, I know), 24GB RAM (assigned 20GB for the process)

Thanks a lot!

**Comment by hoffmang9** [comment]
This is usually bad RAM. It can be a bad stick or it can be your OC or XMP settings. Also you do not need to give each process anywhere near that amount of RAM. See the RAM section in the middle of this post - https://www.chia.net/2021/02/22/plotting-basics.html
