### ISSUE TITLE
[Bug] Harvester Summary in GUI won't render if harvester has too many plots

### ISSUE THREAD

**Issue by Valeri4n** [Chia-Network/chia-blockchain#16711]
### What happened?

The Harvester Summary tab in the GUI 2.1.1 is having trouble updating the page when a harvester that has a large number of plots attached. It's possible it is because the number of compressed plots might exceed the capability of the GPU in that harvester, haven't tested this. When it does finally render, it shows farm size as 0, although plots tab shows the correct number for each harvester. That page rendered fine until bringing the one larger harvester online.

When reducing the drives mounted on that harvester, it then renders the page. It would be helpful if the page could handle the error and give a warning for the harvester. Seems like it might be an unhandled error.

Ubuntu 22.04 6.2.0-35

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
message size limit is 50 megabytes. maybe we are running into that. can you run

chia rpc farmer get_harvesters

and see if that returns anything. thanks!!

**Comment by ChiaMineJP** [comment]
I'll investigate this issue.

**Comment by ChiaMineJP** [comment]
I tried to simulate RPC APIs to generate dummy responses, mimicking a harvester with 10,000 plots.
More precisely I revised the following RPC APIs to return data with 10,000 dummy plot info items.
- get_harvesters Farmer RPC API
- get_plots Harvester RPC API

Then I opened Farmer/Harvester page in the GUI.
It opened instantly. No lagging nor loading spinner was observed.
This indicates that the root issue is not in the GUI code but `chia-blockchain` itself.

Could you provide information regarding your setup?
- The total number of plots in the problematic harvester
- Plot counts by compression levels. (e.g. C1: 100, C2: 30, ..., C7: 60)

**Comment by wjblanke** [comment]
Closing, if the issue persists please open a new report
