### ISSUE TITLE
[BUG] Chia GUI causes Mac OS to crash and/or restart

### ISSUE THREAD

**Issue by russ-tolman** [Chia-Network/chia-blockchain#1672]
Just plotting along and Chia cause spontaneous restart.

Panic(CPU 0, time 361781396724721): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff80fb3ba050, spinlock owner: 0xffffff80b1d5d000, current_thread: 0xffffff80b1d5d000, spinlock_owner_cpu: 0x0
RAX: 0xffffff80bdb42520, RBX: 0xffffff80ddca2418, RCX: 0x0000000000000266, RDX: 0x0003b31700000000
RSP: 0xffffffa760443a70, RBP: 0xffffffa760443ab0, RSI: 0xffffff80b1d5d000, RDI: 0xffffff80ddca2418
R8:  0xffffffa760443c30, R9:  0xffffff8013b6b2e0, R10: 0x0000000000ffffff, R11: 0xffffff80c623fc00
R12: 0xffffff80b1d5d000, R13: 0x0000000000000000, R14: 0x0003b3182c4c3aae, R15: 0xffffff80bdb42520
RFL: 0x0000000000000082, RIP: 0xffffff8013b2afc0, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 0), Frame : Return Address
0xffffff87282a8f80 : 0xffffff8013c45dfb 
0xffffff87282a8fd0 : 0xffffff8013ac0bed 
0xffffffa760443ab0 : 0xffffff8013b2b154 
0xffffffa760443ae0 : 0xffffff8013b69aa0 
0xffffffa760443b00 : 0xffffff8013b6b319 
0xffffffa760443bb0 : 0xffffff8013b6b821 
0xffffffa760443c20 : 0xffffff8013b6a944 
0xffffffa760443ce0 : 0xffffff8013b6e638 
0xffffffa760443d20 : 0xffffff8014050a44 
0xffffffa760443d40 : 0xffffff8014050b2e 
0xffffffa760443d80 : 0xffffff80140a67ed 
0xffffffa760443db0 : 0xffffff80140a7253 
0xffffffa760443e20 : 0xffffff80140a14a0 
0xffffffa760443ee0 : 0xffffff80140a1260 
0xffffffa760443f40 : 0xffffff8014184be7 
0xffffffa760443fa0 : 0xffffff8013ac1206 

BSD process name corresponding to current thread: Chia Helper (Ren

Mac OS version:
19H2

Kernel version:
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Kernel UUID: 05D51A3D-3A87-3FF0-98C3-9CF3827A3EDD
Kernel slide:     0x0000000013800000
Kernel text base: 0xffffff8013a00000
__HIB  text base: 0xffffff8013900000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 361781396756637
last loaded kext at 348001810095230: @filesystems.exfat	1.4 (addr 0xffffff7f983d9000, size 65536)
last unloaded kext at 333195379091083: @filesystems.exfat	1.4 (addr 0xffffff7f98627000, size 57344)
loaded kexts:
com.avg.PacketForwarder	2.1
com.avg.FileShield	4.0.0
com.Cycling74.driver.Soundflower	2
com.uaudio.driver.UAFWAudio	4.3.1 47542
com.kairos.driver.DuetDisplay	1
com.uaudio.driver.UAD2System	9.13.0
@filesystems.exfat	1.4
@filesystems.smbfs	3.4.4
@fileutil	20.036.15
@kext.AMDFramebuffer	3.1.0
@kext.AMDRadeonServiceManager	3.1.0
@kext.AMDRadeonX4000	3.1.0
>AudioAUUC	1.70
>!AUpstreamUserClient	3.6.8
>!AMCCSControl	1.14
>!AGraphicsDevicePolicy	5.2.6
@AGDCPluginDisplayMetrics	5.2.6
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.4
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
>!AHDA	283.15
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.6f7
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>eficheck	1
>!ALPC	3.1
>!A!ISlowAdaptiveClocking	4.0.0
>!AThunderboltIP	3.1.4
@kext.AMD7000!C	3.1.0
>!AMGPUPowerControl	5.2.6
>!A!IMCEReporter	115
|SCSITaskUserClient	422.120.3
>!U!SCoexistentDriver	489.120.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.141.1
>AirPort.BrcmNIC	1400.1.1
|!ABCM5701Ethernet	10.3.5
@private.KextAudit	1.0
>!AACPIEC	6.1
>!AACPIButtons	6.1
>!AHPET	1.8
>!ARTC	2.0
>!ASMBIOS	2.1
>!AAPIC	1.7
>!A!ICPUPowerManagementClient	222.0.0
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
>!A!ICPUPowerManagement	222.0.0
|EndpointSecurity	1
>!AXsanScheme	3
>!UAudio	323.4
>usb.cdc	5.0.0
>!A!BHIDKeyboard	209
>IO!BHIDDriver	7.0.6f7
>!AHIDKeyboard	209
@kext.AMDRadeonX4030HWLibs	1.0
|IOAccelerator!F2	438.7.3
@kext.AMDRadeonX4000HWServices	3.1.0
>!ASMBus!C	1.0.18d1
@kext.triggers	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IOAVB!F	850.1
@!AGPUWrangler	5.2.6
|IOFireWire!F	4.7.5
|IOSlowAdaptiveClocking!F	1.0.0
>!AHDA!C	283.15
|IOHDA!F	283.15
@kext.AMDSupport	3.1.0
@!AGraphicsDeviceControl	5.2.6
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
@plugin.IOgPTPPlugin	840.3
>!ABacklightExpert	1.1.0
|IONDRVSupport	576.1
|IOGraphics!F	576.1
>!AGraphicsControl	5.2.6
|Broadcom!BHost!CUSBTransport	7.0.6f7
|IO!BHost!CUSBTransport	7.0.6f7
|IO!BHost!CTransport	7.0.6f7
|IO!B!F	7.0.6f7
|IO!BPacketLogger	7.0.6f7
|IOUSBMass!SClass	4.0.4
>usb.!UHub	1.2
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
|IO80211!F	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
|IONVMe!F	2.1.0
|IOEthernetAVB!C	1.1.0
>mDNSOffloadUserClient	1.0.1b8
>usb.!UEHCIPCI	1.2
>usb.!UEHCI	1.2
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.140.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
panic(cpu 8 caller 0xffffff8013c3baa0): "Spinlock acquisition timed out: lock=0xffffff80fb3ba050, lock owner thread=0xffffff80b1d5d000, current_thread: 0xffffff80bdb42520, lock owner active on CPU 0x0, current owner: 0xffffff80b1d5d000, time: 361781396780659"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2/osfmk/i386/locks_i386.c:501
Backtrace (CPU 8), Frame : Return Address
0xffffff8748b0caf0 : 0xffffff8013b1a65d 
0xffffff8748b0cb40 : 0xffffff8013c54a75 
0xffffff8748b0cb80 : 0xffffff8013c465fe 
0xffffff8748b0cbd0 : 0xffffff8013ac0a40 
0xffffff8748b0cbf0 : 0xffffff8013b19d27 
0xffffff8748b0ccf0 : 0xffffff8013b1a117 
0xffffff8748b0cd40 : 0xffffff80142c1a6c 
0xffffff8748b0cdb0 : 0xffffff8013c3baa0 
0xffffff8748b0cdf0 : 0xffffff8013b38f5a 
0xffffff8748b0ce30 : 0xffffff8013b38e7c 
0xffffff8748b0ce60 : 0xffffff8013b6545c 
0xffffff8748b0cf20 : 0xffffff8013c33807 
0xffffff8748b0cf60 : 0xffffff8013c4e663 
0xffffff8748b0cf80 : 0xffffff8013c45dfb 
0xffffff8748b0cfd0 : 0xffffff8013ac0bed 
0xffffffa78d82bda0 : 0xffffff8013b6e431 
0xffffffa78d82be00 : 0xffffff80140a3349 
0xffffffa78d82bf00 : 0xffffff80140a2456 
0xffffffa78d82bf40 : 0xffffff8014184be7 
0xffffffa78d82bfa0 : 0xffffff8013ac1206 

BSD process name corresponding to current thread: Chia Helper (Ren

**Comment by wjblanke** [comment]
Chia can't do anything to cause your Mac to restart. Maybe try updating the OS or see if it is overheating.

**Comment by russ-tolman** [comment]
Ok, but why does the error message mention “Chia Helper”?


Sent from Yahoo Mail for iPhone


On Saturday, April 3, 2021, 9:20 PM, wjblanke ***@***.***> wrote:




Chia can't do anything to cause your Mac to restart. Maybe try updating the OS or see if it is overheating.

**Comment by mcmar47** [comment]
I've had this exact same issue multiple times and others have had as well. I've switched to exclusively using the command line for plotting and farming and my issues have gone away. The GUI Renderer process certainly seems like the culprit.

**Comment by russ-tolman** [comment]
Hi McMahon, thanks for that. I’ve tried the CLI commands for Mac that are on the wiki to no luck. Any idea what I am doing wrong. Do I need to cd to specific directory?



http://www.russtolmanmusic.comhttps://www.facebook.com/russtolmanhttps://www.facebook.com/russtolmanbandTwitter: @RussTolmanInstagram: Truewesterner

On Sunday, April 4, 2021, 7:44 AM, mcmar47 ***@***.***> wrote:




I've had this exact same issue multiple times and others have had as well. I've switched to exclusively using the command line for plotting and farming and my issues have gone away. The GUI Renderer process certainly seems like the culprit.

**Comment by russ-tolman** [comment]
Dang spellchecker, mcmar47



http://www.russtolmanmusic.comhttps://www.facebook.com/russtolmanhttps://www.facebook.com/russtolmanbandTwitter: @RussTolmanInstagram: Truewesterner

On Sunday, April 4, 2021, 8:41 AM, Russ Tolman ***@***.***> wrote:

Hi McMahon, thanks for that. I’ve tried the CLI commands for Mac that are on the wiki to no luck. Any idea what I am doing wrong. Do I need to cd to specific directory?



http://www.russtolmanmusic.comhttps://www.facebook.com/russtolmanhttps://www.facebook.com/russtolmanbandTwitter: @RussTolmanInstagram: Truewesterner

On Sunday, April 4, 2021, 7:44 AM, mcmar47 ***@***.***> wrote:




I've had this exact same issue multiple times and others have had as well. I've switched to exclusively using the command line for plotting and farming and my issues have gone away. The GUI Renderer process certainly seems like the culprit.

**Comment by mcmar47** [comment]
Is your issue the terminal just not finding the command? Just do this to start with : 
export PATH=/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon:$PATH 

For the life of that terminal shell you'll be able to just use the 'chia' command normally.

**Comment by russ-tolman** [comment]
Gotcha. Thanks so much!



New single: "life"

| See the video: RUSS TOLMAN I LOVE LIGHTNING (FEAT. JAWBO)
Catch my radio show, "My Kinda Country," every Thursday, 2pm Pac on GimmeCountry.com

 |

 

    On Sunday, April 4, 2021, 10:32:52 AM PDT, mcmar47 ***@***.***> wrote:  
 
 


Is your issue the terminal just not finding the command? Just do this to start with :
export PATH=/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon:$PATH

For the life of that terminal shell you'll be able to just use the 'chia' command normally.

**Comment by branBeckett** [comment]
I'm also having the same issue on MacOS, and after crashing, the database disk image becomes malformed. When I reopen the Chia GUI, the wallet never opens, so I have to completely remove the ~/.chia directory. After removal, I'm able to open up the Chia GUI again, but then it takes hours for the Full Node to sync.

Is there some file I can copy over from the removed ~/.chia directory into the new one so that I don't have to spend hours syncing the Full Node after each crash?
