### ISSUE TITLE
[BUG] node sometimes does not reconnect to peers

### ISSUE THREAD

**Issue by serpent213** [Chia-Network/chia-blockchain#1676]
**Describe the bug**
My uplink is pretty flaky, I have several DSL reconnects per day. Most of the time the node handles that just fine and is synced again after a few minutes.

Once in a while, though, it takes more than 30 minutes to reconnect to peers (or until I `chia start -r node`).

**To Reproduce**

1. Disrupt your internet access for 90 seconds while staying connected to the router, which receives new dynamic IPs.
2. Repeat until bug shows.

**Expected behavior**
Reconnect ASAP every time.

**Desktop**
- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.2 LTS
- CPU: Intel i7-3770

**Additional context**
INFO level log included, will try to produce a DEBUG level one.

[debug.log.no_reconnect.redacted.txt](https://github.com/Chia-Network/chia-blockchain/files/6254087/debug.log.no_reconnect.redacted.txt)

**Comment by serpent213** [comment]
[My log scanner](https://gist.github.com/serpent213/8518393e521f1a0dd6f7f1c3544590a2) reports:

```
found gap of 24.0 minutes (starting 2021-04-03 23:01:59 +0200)
found gap of 5.0 minutes (starting 2021-04-04 01:11:59 +0200)
found gap of 5.0 minutes (starting 2021-04-04 09:36:59 +0200)
found gap of 53.0 minutes (starting 2021-04-05 03:54:59 +0200)
scanned from 2021-04-03 18:25:59 +0200 to 2021-04-05 09:28:59 +0200 (2343 minutes, 1.63 days)
14157 challenges, {REDACTED} eligible plots, {REDACTED} proofs, response time: min 0.015 s, avg 0.114 s, max 4.884 s
not farming for 105 minutes total (4.48%) 🤬
```

**Comment by Attix2508** [comment]
I added an automatic task in Windows...  i get everyday at the same time a ISP disconnect. 

That task start everyday / at the same time a batch file to add new connections (reconnect Full Nodes / Introducer) to Chia. 

That works fine for me...  Downtime around 5 minutes...

**Comment by Plopsi** [comment]
Yeah would be nice when chia would connect to the introducer on start or after a minute without nodes automatically to exchange peers. Currently it's a loooong waiting or manually add it.
