### ISSUE TITLE
[Bug] Combining coins with fee

### ISSUE THREAD

**Issue by xchChiaFarmers** [Chia-Network/chia-blockchain#16802]
### What happened?

The user wants to combine coins using

1. Run CLI combine
`chia wallet coins combine -f 1269832460 --number-of-coins 100 --id 25 --fee 0.0000001`

2. Response:
```
Combining 7 coins.
Would you like to Continue? (y/n): y
```

3. Response:
```
Exception from 'wallet' {'error': 'Transaction for 100000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too 
high.', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "chia\\rpc\\util.py", line 21, in inner\n  File "chia\\rpc\\wallet_rpc_api.py", line 1072, in send_transaction_multi\n  File "chia\\rpc\\util.py", line 82, in rpc_endpoint\n  File "chia\\rpc\\wallet_rpc_api.py", line 1616, in cat_spend\n  File "chia\\wallet\\cat_wallet\\cat_wallet.py", line 818, in generate_signed_transaction\n  File "chia\\wallet\\cat_wallet\\cat_wallet.py", line 717, in generate_unsigned_spendbundle\n  File "chia\\wallet\\cat_wallet\\cat_wallet.py", line 581, in create_tandem_xch_tx\n  File "chia\\wallet\\wallet.py", line 256, in select_coins\n  File "chia\\wallet\\coin_selection.py", line 57, in select_coins\nValueError: Transaction for 100000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.\n'}
```

However, standard wallet does have enough spendable balance:
```
Chia Wallet:
   -Total Balance:         5.345662453651 xch (5345662453651 mojo)
   -Pending Total Balance: 5.345662453651 xch (5345662453651 mojo)
   -Spendable:             2.311613686008 xch (2311613686008 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1
```

**Running the ``coins split`` command including same fee size works without problems**

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Jack can u make sure the fee is coming from the correct wallet. Thanks for the report!

**Comment by AbandonedLand** [comment]
I get this same issue when trying to combine without a fee.  I have the same setup (windows, 2.1.1).
I also tried to do a 
`chia rpc wallet cat_spend` 
and get the same error.

**Comment by jack60612** [comment]
@xchChiaFarmers a fix should be coming.

**Comment by KryptomineCH** [comment]
same issue here. this is kind of important since 0 fee transactions wont go through as of right now.I need to cancle my offers somehow

**Comment by forReason** [comment]
furthermore the combine command crashes with `No coins to combine.` when trying to combine pending coins. The wallet has to be used from another db or computer.

the coins split command can handle pending coins
