### ISSUE TITLE
[Bug] offer `confirmed_at_index` is always empty

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#16817]
### What happened?

When checking the transaction history, the value of `confirmed_at_index` is always 0.

This leads to confusing replies by CLI and RPC:
```
chia wallet get_offers -id 0xff211040f9b946d1461d1631fcc0c812b7bc24735989cdf58598d9f6dd3b7bfe

Record with id: ff211040f9b946d1461d1631fcc0c812b7bc24735989cdf58598d9f6dd3b7bfe
---------------
Created at: 2023-10-13 23:22:42
Confirmed at: Not confirmed
Accepted at: 2023-10-13 23:22:42
Status: CONFIRMED
---------------
```

Relevant seems to be the status, but `confirmed_at_index` would be important / valuable information

Furthermore, the `accepted_at_time` is only beeing filled when `is_my_offer` = false. This might be a technical limitation.
 

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Quex where do we save this off in the DB?
