### ISSUE TITLE
[Bug] wallet_node: ERROR Traceback - Exception: weight proof response was none

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#16816]
### What happened?

Fresh Arch Linux - feeling fresh.
Fresh Chia install - nice new SSD.
Synced DB from 0 - took a few days.
Started wallet and let it sync - nice all my XCH is still there.
Stopped all, and edited config.yaml for GPU harvesting - there should be a `chia harvester [OPTIONS]` command for this :thinking:.
`chia start farmer` and check my logs - gotta make sure there were no errors.
Found error - better make a weird GH issue.

### Version

31b60e51f7d39d5513706926271745fe75c97bab

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-11-12T23:44:14.220 wallet chia.wallet.wallet_node    : ERROR    Error syncing to PeerInfo(_ip=IPv4Address('91.126.229.143'), _port=8444)
Traceback (most recent call last):
  File "chia-blockchain/chia/wallet/wallet_node.py", line 1158, in new_peak_from_untrusted
    await self.long_sync_from_untrusted(syncing, new_peak_hb, peer)
  File "chia-blockchain/chia/wallet/wallet_node.py", line 1167, in long_sync_from_untrusted
    fork_point_weight_proof = await self.fetch_and_update_weight_proof(peer, new_peak_hb)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "chia-blockchain/chia/wallet/wallet_node.py", line 1291, in fetch_and_update_weight_proof
    raise Exception("weight proof response was none")
Exception: weight proof response was none
```
```

**Comment by wjblanke** [comment]
This could be from a slow node that couldn't return a weight proof in time. Or it may have just been started up and not had one available. Arch for the win! We will let Almog look at this.

**Comment by wallentx** [comment]
Nay, the untrusted node was not me.

**Comment by emlowe** [comment]
I don't think there is enough information here to diagnose any errors.
Closing - you may add new comments and reopen with additional details as needed
