### ISSUE TITLE
не запускається повна нода починаючи з версії 2.1.0

### ISSUE THREAD

**Issue by ScriptVoyageMaster** [Chia-Network/chia-blockchain#16825]
### What happened?

не запускається повна нода починаючи з версії 2.1.0. на версії 2.0.1 все працює нормально

![image](https://github.com/Chia-Network/chia-blockchain/assets/139281125/863093b6-83ce-4ec0-9656-3b064b6e0996)
![image](https://github.com/Chia-Network/chia-blockchain/assets/139281125/71d94882-cc3e-466e-aa51-ea4476cb822a)

### Version

2.1.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by GaJIoDHbI** [comment]
I also have the same bug. Tried to reboot, was waiting much hours. Still the same thing. Can't mine XCH.

**Comment by wjblanke** [comment]
closing with the v1-v2 update suggestion
