### ISSUE TITLE
[Bug] can not accept offer

### ISSUE THREAD

**Issue by nqzhang** [Chia-Network/chia-blockchain#16823]
### What happened?

The log looks like there is insufficient balance, but I have enough balance

![image](https://github.com/Chia-Network/chia-blockchain/assets/12559853/46173754-d0df-452a-822b-1f0d71887a98)
![image](https://github.com/Chia-Network/chia-blockchain/assets/12559853/c7786080-8269-4885-9bfa-9a2e3032e1a2)

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output
[debug.txt](https://github.com/Chia-Network/chia-blockchain/files/13340991/debug.txt)

_No response_
```[tasklist]
### Tasks
```

**Comment by KryptomineCH** [comment]
I think the issue is with your pending balance. You seem to have pending transactions or open offers. Try to Delete pending transactions

**Comment by nqzhang** [comment]
> I think the issue is with your pending balance. You seem to have pending transactions or open offers. Try to Delete pending transactions

This pending offer exists because the offer cannot be accepted. Rather than the prior pending offer

Have you read the log?

**Comment by nqzhang** [comment]
> > I think the issue is with your pending balance. You seem to have pending transactions or open offers. Try to Delete pending transactions
> 
> This pending offer exists because the offer cannot be accepted. Rather than the prior pending offer
> 
> Have you read the log?

WARNING  SpendBundle has been rejected by the FullNode. {'error': 'BLOCK_COST_EXCEEDS_MAX',
 'status': 3,
 'txid': '0x1823df6eb53e4763895148ff6156b83ca088b13285035ccce3423e8027692d2a'}

**Comment by KryptomineCH** [comment]
this seems to be related to the maximum Block cost, not to your wallet balance:
```
 # 7. Check that cost <= MAX_BLOCK_COST_CLVM
        log.debug(
            f"Cost: {cost} max: {constants.MAX_BLOCK_COST_CLVM} "
            f"percent full: {round(100 * (cost / constants.MAX_BLOCK_COST_CLVM), 2)}%"
        )
        if cost > constants.MAX_BLOCK_COST_CLVM:
            return Err.BLOCK_COST_EXCEEDS_MAX, None
```

Have simmilar transactions worked in the Past?
The ones below that one are cancelled in the screenshot.

Did you assign a fee to the offer?

Did you try executing the offer later again?

**Comment by wjblanke** [comment]
As per above, send the CAT balance to yourself to consolidate some of the many small coins into one large coin (doing all of them will run into the same block size issue). Then you will be able to accept the offer because the single coin can fit in the block.

**Comment by nqzhang** [comment]
I understand, but if this is the case, the offer should not be accepted and a prompt will be given.

**Comment by wjblanke** [comment]
we can probably handle this better. we are missing some rpc to get the cost from the node.

**Comment by wjblanke** [comment]
We're going to ask Brandon to support this to change the wallet node protocol to handle this better. We will need logic to tell the user if they exceed these limits

**Comment by wjblanke** [comment]
We think this is related to the number of coins we use for CATs being too high since ALFood is dust. Brandon is going to check this.
