### ISSUE TITLE
[Bug] `chia rpc wallet set_wallet_resync_on_startup` results in an error on next start

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#16852]
### What happened?

I ran `chia rpc wallet set_wallet_resync_on_startup` and at next startup, it did not appear to do a reset, and I saw related errors in my logs.

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2023-11-17T01:02:19.034 wallet chia.wallet.wallet_node    : ERROR    Mismatch in expected schema to reset, found unexpected table: singletons. Please check if you've run all migration scripts.
```

**Comment by wjblanke** [comment]
Geoff fixed the singleton table. Previously you couldn't downgrade versions without deleting your wallet db. should be ok in current main
