### ISSUE TITLE
[Bug] Duplicate Puzzlehashes in offers

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#16853]
### What happened?

I have an issue with my offers. The Coins of Interest contain Duplicate Puzzle hashes for different coins. Where is that coming from and what can I do?

```
{{
  "amount": 1000000000000,
  "parent_coin_info": "0xb728f034b9875e8d36ca7d3aa93943b5a2aa7fbc6e153c57fe9a915e0e357ca9",
  "puzzle_hash": "0x22688e681e8efd1fe9ea3d45a93ae12be0d2f7039cebeedd6971e0a4dda50c02"
}}
```
```
{{
  "amount": 7,
  "parent_coin_info": "0xcdd4b4609e2c2711fb6553ff5426e85dfc569b7e40ed4ba9608d5b02c9ab6ee5",
  "puzzle_hash": "0x22688e681e8efd1fe9ea3d45a93ae12be0d2f7039cebeedd6971e0a4dda50c02"
}}
```
```
{{
  "amount": 7,
  "parent_coin_info": "0x39cc77b649c5748ad599ed9806adf7b4bdc9223b0e61eda091b529ef2613fb44",
  "puzzle_hash": "0x22688e681e8efd1fe9ea3d45a93ae12be0d2f7039cebeedd6971e0a4dda50c02"
}}
```
```
{{
  "amount": 7,
  "parent_coin_info": "0x35c67dc6bb02cce4196b3f51868716eb33e542e90b05b3a4e587a7f009da86b2",
  "puzzle_hash": "0x22688e681e8efd1fe9ea3d45a93ae12be0d2f7039cebeedd6971e0a4dda50c02"
}}
```
```
{{
  "amount": 7,
  "parent_coin_info": "0x2647fe47ebdfb543ac375a7040d49ee8a7dca6da23c575bbfdc86349f772a1ea",
  "puzzle_hash": "0x22688e681e8efd1fe9ea3d45a93ae12be0d2f7039cebeedd6971e0a4dda50c02"
}}
```
```
{{
  "amount": 7,
  "parent_coin_info": "0x8cd1c7973f03604667998842336e53a82cb0e0f30db8bf6ad457a0b056f9ca47",
  "puzzle_hash": "0x22688e681e8efd1fe9ea3d45a93ae12be0d2f7039cebeedd6971e0a4dda50c02"
}}
```
```
{{
  "amount": 7,
  "parent_coin_info": "0xe13b0bf41efac18edc66ddf4e9d611c274edfaa7dac3761542e4137d007fd19c",
  "puzzle_hash": "0x22688e681e8efd1fe9ea3d45a93ae12be0d2f7039cebeedd6971e0a4dda50c02"
}}
```

the amount is always 7 later on because I was testing offer outcomes to build my transaction history. I try to match the offers to the transaction block by comparing puzzle hashes. But then I noticed the offers contain duplicate puzz hashes...

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
the puzzle hashes are always the same. maybe quex has an idea for what ur trying to accomplish

**Comment by KryptomineCH** [comment]
what I am doing now is to match the parent coin id. 
in case this is by design and not a bug, I guess this can be closed. 

notable is that this is on completed offers.

**Comment by Quexington** [comment]
Duplicate puzzle hashes are definitely allowed, most likely someone (or you) sent money to one single address of yours multiple times.  You shouldn't rely on the puzzle hash being unique, and in fact, the only thing that is guaranteed to be unique about a coin is it's ID `sha256(parent_info + puzzle_hash + amount)`.
