### ISSUE TITLE
Incorrect DAO_CAT balance shown after running exit_lockup command [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16916]
### What happened?

I have a DAO with one active proposal:
```
chia dao list_proposals -i 2 -f 4101202912
```
```
############################
Proposal ID: 0x900b9ab90153c3aa0f8f73a74503efc871afd2d3bd538cfaa419d33c57840441
Status: OPEN
Votes for: 350
Votes against: 0
------------------------
Proposals have 2 blocks of soft close time.
############################
```

Notice that 350 votes have been logged so far. Here are my CAT and DAO_CAT wallet balances:
```
CAT 0ba7b225ea0aa595...:
   -Total Balance:         0.0  (0 mojo)
   -Pending Total Balance: 0.0  (0 mojo)
   -Spendable:             0.0  (0 mojo)
   -Type:                  CAT
   -Asset ID:              0ba7b225ea0aa595384239537b055caa0fa8b627b98b6032439d4f2cd1414bf5
   -Wallet ID:             3

CAT 0ba7b225ea0aa595...:
   -Total Balance:         100000.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DAO_CAT
   -Asset ID:              000000000000000200000000000000030ba7b225ea0aa595384239537b055caa
   -Wallet ID:             4
```

The DAO_CAT balance does not reflect the fact that 350 votes have been registered already. It also shows zero-tenths, which is not possible. However, the total balance is equivalent to 100 CATs.

Next, run the `exit_lockup` command:
```
chia dao exit_lockup -i 2 -m 0.0001 -f 4101202912
```
After the transaction has been accepted, show the wallet again:
```
CAT 0ba7b225ea0aa595...:
   -Total Balance:         99.65  (99650 mojo)
   -Pending Total Balance: 99.65  (99650 mojo)
   -Spendable:             99.65  (99650 mojo)
   -Type:                  CAT
   -Asset ID:              0ba7b225ea0aa595384239537b055caa0fa8b627b98b6032439d4f2cd1414bf5
   -Wallet ID:             3

CAT 0ba7b225ea0aa595...:
   -Total Balance:         100000.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DAO_CAT
   -Asset ID:              000000000000000200000000000000030ba7b225ea0aa595384239537b055caa
   -Wallet ID:             4
```

The CAT balance is now correct -- it reflects the fact that 350 votes have been registered for an active proposal. However, DAO_CAT balance has not changed. It should be 350.

### Version

2.1.2.dev292 (main branch)

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by geoffwalmsley** [comment]
I tested this on the latest release branch, and the balance of DAO_CAT wallet shows the correct amount after running `exit_lockup`.

In terms of the tenths of a mojo issue. This isn't specific to DAO_CATs, it's present in any wallet which displays mojos (e.g. a one mojo DID balance is displayed as 1.0). The control of this is in wallet_funcs.py (https://github.com/Chia-Network/chia-blockchain/blob/cc254d9846b70841a04f555592304795eae77fd4/chia/cmds/wallet_funcs.py#L810), and could easily be changed but probably makes sense to do this in a separate PR

**Comment by danieljperry** [comment]
I tested this on rc2 and am now seeing the correct balances. I'll open a separate issue for the tenths-of-mojos display.
