### ISSUE TITLE
DID [Bug] 

### ISSUE THREAD

**Issue by jeherschberger** [Chia-Network/chia-blockchain#16910]
### What happened?

Transferred my DID to a new wallet but did not have full functionality of the DID in the new wallet. I solved this by deleting the .chia folder and then I had full functionality of the DID. Maybe the RPC file did not update or something.

### Version

2.1.1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
What is the missing functionality? by removing the chia folder you essentially synced your wallet again from scratch so maybe the existing wallet didn't pick up the transfered did. let us know what u saw. "full functionality" is confusing us.

**Comment by jeherschberger** [comment]
By full functionality, I mean that I was not able to claim my transferred DID on mint garden or spacescan. This indicates that there was an underlying issue with the chia software. I tried running "chia did find lost -id <did_id>", but I was not able to verify my DID on mint garden or spacescan.

**Comment by wjblanke** [comment]
After resyncing your wallet, are all your issues resolved? we are trying to determine if this is happening during coin sync.

**Comment by jeherschberger** [comment]
Yea I deleted the .chia folder which might have deleted my wallet db and resynced it. Whatever happen after I deleted my .chia folder worked to solve the issue. I am not sure why that solved the issue though.

**Comment by Quexington** [comment]
Do you have information for what mintgarden etc. require from the chia software in order to verify a DID?

**Comment by jeherschberger** [comment]
I just know that mint garden needs wallet connect.

**Comment by Quexington** [comment]
Hey @jeherschberger sorry it's been a while since our last response, is this still an issue for you?  I know some of the services you mentioned had a bug on their end, but that wouldn't explain why resyncing fixed it for you so I'd like to pin that down, but I need more information about what is failing like if there is any suspicious log output when you try to claim the DID on one of those websites.  Do they use wallet connect or some other method to connect to your wallet?

**Comment by jeherschberger** [comment]
Hi @Quexington, No worries! I have not had issues after I resynced the wallet. It has also been a while since I was fiddling with the DIDs on my wallet, so I forget specific details. If I recall correctly, the websites said that the DID signature was invalid. I tried wallet connect and manually signing the DID verification, I think.

**Comment by wjblanke** [comment]
Please open an new issue if you have problems again. Thanks!
