### ISSUE TITLE
[BUG] Plotting always dying after a while

### ISSUE THREAD

**Issue by mhjey** [Chia-Network/chia-blockchain#1692]
**Describe the bug**
No matter what setting I choose after a while my plotting simply stops with a log similar to this
```
Only wrote 50 of 4194294 bytes at offset 20971470 "mnt/ssd/plot-...." with length 20971520. Errror 1. Trying in 5 minutes again
```
What is the problem? The "retry in 5 minutes" **never** works.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- CPU: Intel BXNUC10i7FNH (6 core i7-10710U)
- DRAM: 32GB DDR4 2666 
- Boot SSD:  480GB SATA SSD
- Temp SSD: 2TB NVMe M.2 80mm

**Comment by ardabro** [comment]
My problem is very similar, but happened after hours and says recurrently:
`Only read 670543872 of 1095759314 bytes at offset 0 from "/home/arek/mnt/elements/arek/chia-temp/plot-k32-2021-04-04-15-17-4a02f78ef6a6649962c706ebc70ced2ed042dbffe9d217388ed441efff964c10.plot.p3.t3.sort_bucket_013.tmp"with length 1095759314. Error 1. Retrying in five minutes.
`
There is plenty of space on hdd and enough memory.
BTW: I searched for constant components from this message in project sources but haven't found anything.
Message doesn't say much, and even don't have timestamp (perfect logging!)

**Comment by hoffmang9** [comment]
This is a hardware issue. It's almost always RAM but sometimes it is the drive.

**Comment by thienhieu123** [comment]
@mhjey I meet the same issue. Did you fix it?

**Comment by thienhieu123** [comment]
@ardabro I meet the same issue. Did you fix it?
