### ISSUE TITLE
plotting freeze at 39% [BUG]

### ISSUE THREAD

**Issue by chickenka** [Chia-Network/chia-blockchain#1696]
**Describe the bug**
plotting freezes at 39% . 

i have deleted the files and started again , same issue
i get this at the end of log file 
"scanned time =  536.268 seconds. CPU (10.430%) Mon Apr  5 16:04:15 2021
sorting table 7
Backpropagating on table 6
scanned table 6
scanned time =  539.406 seconds. CPU (27.250%) Mon Apr  5 16:31:52 2021
sorting table 6
sort time =  1105.095 seconds. CPU (49.300%) Mon Apr  5 16:50:17 2021
Backpropagating on table 5"

**Comment by InternetGuy140** [comment]
I'm not sure this is a bug. It's counting down the tables and I'm in the same spot right now. But I have activity on my temp drive. And the log keeps updating eventually with a lower table number.

**Comment by hoffmang9** [comment]
This is a hardware problem on your computer. It could be an issue with your temp drive but it is usually a problem with RAM. It can include using too much buffer per process, a bad stick of RAM, over clocking instability or XMP.
