### ISSUE TITLE
Tenths of mojos displayed in CAT wallet

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16974]
When showing a CAT wallet that is based on mojos, the CLI shows tenths of a CAT, which isn't possible. Note that this is only a display issue.

For example,

I have a `DAO_CAT` wallet with this balance:
```
CAT 80c934b46e745545...:
   -Total Balance:         4000.0
   -Pending Total Balance: 0.0
   -Spendable:             0.0
   -Type:                  DAO_CAT
   -Asset ID:              0000000000000002000000000000000380c934b46e7455455616d312d7b7efa2
   -Wallet ID:             4
```
The 4000 DAO CATs were created from 4 CATs. Thus, the DAO_CATs already are based on mojos. They cannot be divided any further. These CATs are used for voting, so the display makes it look like it's possible to submit one tenth of one vote.

From  @geoffwalmsley in issue 16916:
 This isn't specific to DAO_CATs, it's present in any wallet which displays mojos (e.g. a one mojo DID balance is displayed as 1.0). The control of this is in wallet_funcs.py (https://github.com/Chia-Network/chia-blockchain/blob/cc254d9846b70841a04f555592304795eae77fd4/chia/cmds/wallet_funcs.py#L810)

**Comment by wjblanke** [comment]
This can obviously be fixed with some more specific coding. We will see when we can get to it. Thanks for the report
