### ISSUE TITLE
Delete key from GUI fails [Bug] 

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#16995]
### What happened?

Delete key from the GUI fails, but it succeeds from the CLI.

To recreate:
- create a new key with the GUI
- "logout" to show the `wallet keys` diaglog
- Click the three vertical dots on the new key, and click `Delete`

A new spinner appears, but the key is not deleted. A `WARNING` message appears in the log (see below).

I'm seeing the same behavior on Windows and Linux. The wallet is synced when I attempt to delete it. It doesn't seem to matter whether the node is synced.

The stack trace is from 2.0.1, though I'm also seeing it in 2.1.2-rc2.

### Version

2.0.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2023-12-05T13:35:19.539 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 340, in safe_handle
  File "chia/rpc/rpc_server.py", line 331, in ws_api
  File "chia/rpc/wallet_rpc_api.py", line 462, in check_delete_key
  File "chia/rpc/wallet_rpc_api.py", line 440, in _check_key_used_for_rewards
  File "chia/util/bech32m.py", line 120, in decode_puzzle_hash
ValueError: Invalid Address
```

**Comment by paninaro** [comment]
@danieljperry while the spinner is visible, the GUI is asking the wallet to check if the wallet-to-be-deleted is used for farming or pool rewards. The code in question is:

```
        farmer_target = config["farmer"].get("xch_target_address")
        pool_target = config["pool"].get("xch_target_address")
        address_to_check: List[bytes32] = [decode_puzzle_hash(farmer_target), decode_puzzle_hash(pool_target)]
```

Can you check if your config has valid values for the farmer/pool `xch_target_address`?
