### ISSUE TITLE
Allow limiting number of connections to peers

### ISSUE THREAD

**Issue by flotti455** [Chia-Network/chia-blockchain#1699]
**Describe the bug**
Currently (1.0.3), after a couple of hours of running, a full node may have 40 or more connections to other nodes.

When my Raspberry Pi 4 farm reaches this point, it seems to be more busy with interacting with these peers instead of actually checking for proofs - I mostly see "signage point xyz not added", and signage points don't get finished / are skipped.

Current workaround is to restart farm.

- Ubuntu Server 20 LTS
- Raspberry Pi 4 4 GB

**Comment by hoffmang9** [comment]
You can already limit number of peers in config.yaml. `~/.chia/mainnet/config/config.yaml`

**Comment by flotti455** [comment]
probably
```
full_node:
  peer_connect_interval: 60
```
