### ISSUE TITLE
[BUG] typo in peer host

### ISSUE THREAD

**Issue by johnrees** [Chia-Network/chia-blockchain#1705]
I was trying to understand why `chia show -s` would always return

```
Searching for an initial chain

You may be able to expedite with 'chia show -a host:port' using a known node.

Blockchain has no blocks yet
```

and I looked in my logs and found that `chia start farmer` was trying to initially connect to `beta1_introduer.chia.net:58444` (notice the typo in beta1_introdu[c]er)

```
DEBUG    Connecting: wss://beta1_introduer.chia.net:58444/ws, Peer info: {'host': 'beta1_introduer.chia.net', 'port': 58444}
INFO     Cannot connect to host beta1_introduer.chia.net:58444 ssl:<ssl.SSLContext object at 0x_________> [Name or service not known]
```

I ran `chia show -a beta1_introducer.chia.net:58444` and now the node is starting to sync

1.0.1.dev91

**Comment by hoffmang9** [comment]
Do not check out main. Checkout either `latest` or `1.0.3`.
