### ISSUE TITLE
[Bug] Following wallet delete_unconfirmed_transactions, get_transaction results in untrapped errors

### ISSUE THREAD

**Issue by Qwinn1** [Chia-Network/chia-blockchain#17079]
### What happened?

Due to the recent high mempool usage, I had a no fee transaction stuck in the mempool for over 36 hours.  I wanted to resend it with a fee, and thought running "chia wallet delete_unconfirmed_transactions" would allow me to do so.  After I ran it, when I tried get_transaction in order to view the status of the original transactions, this was the result (see Relevant Log Output).

The coin I tried to send (and the "change" stuck in limbo) seems spendable now according to wallet show, but I'm a bit afraid to try to resend it as I understand the original transaction IS still in the mempool and I've only deleted my wallet's awareness of it.  Do please advise if I can resend with fee and, if I can't, how I can monitor whether that transaction is done.

### Version

2.1.2

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
chia wallet get_transaction -f 3058644224 -tx 0x98cb1278e33bd8c089903d8da686e031a34180f344b3355ee6749b721942f29b
Exception from 'wallet' {'error': 'Transaction 0x98cb1278e33bd8c089903d8da686e031a34180f344b3355ee6749b721942f29b not found', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "/home/qwinn/chia-blockchain/chia/rpc/util.py", line 21, in inner\n    res_object = await f(request_data)\n  File "/home/qwinn/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 953, in get_transaction\n    raise ValueError(f"Transaction 0x{transaction_id.hex()} not found")\nValueError: Transaction 0x98cb1278e33bd8c089903d8da686e031a34180f344b3355ee6749b721942f29b not found\n'}:
Traceback (most recent call last):
  File "/home/qwinn/chia-blockchain/chia/cmds/cmds_util.py", line 119, in get_any_service_client
    yield node_client, config
  File "/home/qwinn/chia-blockchain/chia/cmds/cmds_util.py", line 235, in get_wallet_client
    yield wallet_client, new_fp, config
  File "/home/qwinn/chia-blockchain/chia/cmds/wallet_funcs.py", line 151, in get_transaction
    tx: TransactionRecord = await wallet_client.get_transaction(this_is_unused, transaction_id=transaction_id)
  File "/home/qwinn/chia-blockchain/chia/rpc/wallet_rpc_client.py", line 124, in get_transaction
    res = await self.fetch(
  File "/home/qwinn/chia-blockchain/chia/rpc/rpc_client.py", line 87, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'Transaction 0x98cb1278e33bd8c089903d8da686e031a34180f344b3355ee6749b721942f29b not found', 'success': False, 'traceback': 'Traceback (most recent call last):\n  File "/home/qwinn/chia-blockchain/chia/rpc/util.py", line 21, in inner\n    res_object = await f(request_data)\n  File "/home/qwinn/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 953, in get_transaction\n    raise ValueError(f"Transaction 0x{transaction_id.hex()} not found")\nValueError: Transaction 0x98cb1278e33bd8c089903d8da686e031a34180f344b3355ee6749b721942f29b not found\n'}
```

**Comment by Rigidity** [comment]
This is the easiest way I know of to make sure that your original transaction is invalid:

If you know a minimum of one of the specific coins that were spent as part of the original transaction, you can send it to yourself to invalidate the old transaction on-chain. If you don't know which one, you can send your whole balance to yourself, so that all coins in your wallet are recreated and any old transactions that spent them are invalidated.

Some things to note:
* You should add a fee, to prevent the transaction getting stuck in the mempool.
* This will combine all of your coins into a single output.
* Make sure that you're sending it to _your_ address.
