### ISSUE TITLE
Total assets missing 2.1.3[Bug] 

### ISSUE THREAD

**Issue by jeeminrose** [Chia-Network/chia-blockchain#17088]
### What happened?

Total assets missing 
The reality is that there should be 13
![image](https://github.com/Chia-Network/chia-blockchain/assets/154324734/6890a010-bd3c-4622-a0f2-036bf3813259)

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Can you try resyncing your wallet db? I'm sure the coins are still on the chain.
