### ISSUE TITLE
[Bug] keyring status 2.1.3

### ISSUE THREAD

**Issue by linkin-hub** [Chia-Network/chia-blockchain#17087]
### What happened?

After switching from version 2.1.2 to 2.1.3 on 5 machines, it does not go further than loading the status of the keys.

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Can u try rebooting? Otherwise can u try the suggestions here

https://github.com/Chia-Network/chia-blockchain/issues/17080
