### ISSUE TITLE
2.1.3独自耕种无法申领奖励[Bug] 

### ISSUE THREAD

**Issue by goscc2023** [Chia-Network/chia-blockchain#17121]
### What happened?

2.1.3中，独自耕种，无法申领奖励！过了一天也无法到帐，以前的版本是好的，现在退回到老版本也无法申领奖励！

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by cai1111** [comment]
这个是因为最近网络拥堵的问题，跟版本没关系，手续费设置高一点就可以了0.0005

**Comment by goscc2023** [comment]
我都设置到0.01了，发现根本没有用，等了8个小时了！

**Comment by chentianqi-3** [comment]
二位，请问如何设置手续费？

**Comment by JustAlias** [comment]
我也遇到

**Comment by arde2020** [comment]
从1.xxx版本升级到2.XXX版本，config.yaml文件哪些地方需要做出改变？

**Comment by wjblanke** [comment]
Probably the issue is fee pressure due to the BRC20 tokens. You need to use a large fee since self claiming pool rewards is an expensive CLVM operation.
