### ISSUE TITLE
[Bug] windows server 2012 R2 版本1.8.0升级到2.0以上报错

### ISSUE THREAD

**Issue by Tonyzhu1988** [Chia-Network/chia-blockchain#17142]
### What happened?

![error](https://github.com/Chia-Network/chia-blockchain/assets/109934041/ec771f72-11b6-40a8-9fee-33f6c9987df1)

### Version

1.8.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by goscc2023** [comment]
把系统升级到2016及以上就可以了，win2012里面没有这个函数了！

**Comment by Tonyzhu1988** [comment]
1.8.0更新到2.1.3之后，我的pooling里面没有任何信息（之前加入了H9.com）？

随后我再一次重新加入h9后，目前一直没有贡献值数据

**Comment by arde2020** [comment]
链文件更新了吗？

**Comment by wjblanke** [comment]
Electron 23 no longer supports Windows Server 2012/Windows 8 so you will not be able to run the GUI. You might be able to still run the command line.

https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
