### ISSUE TITLE
Invalid state[Bug] 

### ISSUE THREAD

**Issue by max88pedro** [Chia-Network/chia-blockchain#17165]
### What happened?

The pool switching operation was cancelled, please try again by changing pool, or self pooling!Help me please 

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by bandusz** [comment]
Hello!

We also have this problem, we can't switch pools and in plain private, it just goes on and on and meanwhile we appear in the pool as if we're not active, but it's still mining the pool!!:-))


At this moment, I'm rebuilding the chia program, we'll see what happens, I hope there will be a meaningful improvement soon!!
I saved the blog, if I know more or if there is a result, I will write immediately!!!

**Comment by wjblanke** [comment]
Can you send us logs from when you are attempting the pool switching operation?
