### ISSUE TITLE
[Bug]  CLI make_offer without an asset request is rejected 

### ISSUE THREAD

**Issue by erniesc** [Chia-Network/chia-blockchain#17173]
### What happened?

The Chia GUI allows an offer to be created without an asset request as mentioned in issue #14604 but the CLI does not.  The command "chia wallet make_offer" is rejected with the error response shown below if the request option is not included.  The command line option validation seems to be preventing the creation of the nothing-requested offer but the underlying wallet supports creating the offer.  This issue is open to make the CLI consistent with the GUI for this offer creation.  

```
chia wallet make_offer -o 1:0.000000000001 -p bump_fee_test.offer -m 0.0001
Usage: chia wallet make_offer [OPTIONS]
Try 'chia wallet make_offer -h' for help.

Error: Missing option '-r' / '--request'.
```

The motivation for this issue is the Dexie exchange Bump Fee feature where an offer without an asset request is needed.  I was able to create an offer without an asset request using the CLI by applying the change below on Chia release 2.1.3.  This offer was then successfully uploaded to Dexie to increase the fee on an accepted offer that was stuck pending confirmation due to the full mempool. 

```diff --git a/chia/cmds/wallet.py b/chia/cmds/wallet.py
index 28268fe90..9b85dfde9 100644
--- a/chia/cmds/wallet.py
+++ b/chia/cmds/wallet.py
@@ -441,7 +441,6 @@ def add_token_cmd(wallet_rpc_port: Optional[int], asset_id: str, token_name: str
     "-r",
     "--request",
     help="A wallet id of an asset to receive and the amount you wish to receive (formatted like wallet_id:amount)",
-    required=True,
     multiple=True,
 )
 @click.option("-p", "--filepath", help="The path to write the generated offer file to", required=True)
```

If useful for more information, the Bump Fee feature button can be found on the Inspect page for offers pending confirmation on Dexie.  With the mempool currently full, numerous offers pending confirmation due to low fees can be found on the Dexie site in the Recent Trades page.  

https://dexie.space/trades?hide_low_fee=false&status=1 

### Version

2.1.3

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Quex you had some concerns about this from last week?

**Comment by Quexington** [comment]
@erniesc See the linked PR for a solution to your use case

**Comment by erniesc** [comment]
Thanks for resolving my issue.  The changes in PR #17220 do resolve the problem I had when applied to v2.1.3 or v2.1.4 but  the -o option is duplicated for --offer and --override.   I've opened issue #17371 for the anticipated problem with -o.  The help for chia wallet make_offer also shows the duplication with PR #17220 applied. 


>  -o, --offer TEXT                A wallet id to offer and the amount to offer
> 
>   -o, --override                  Creates offer without checking for unusual values
>
