### ISSUE TITLE
Plotting shows its 100 percent but not moved to farming even after 50 minutes.

### ISSUE THREAD

**Issue by schak83** [Chia-Network/chia-blockchain#1717]
Plotting shows its 100 percent but not moved to farming even after 5 minutes.

My system Config: intel i5-6200U / 12GB RAM/1.5 TB Seagate usb powered.
screenshots attached.Please let me know if any fix.
![image](https://user-images.githubusercontent.com/73795557/113714716-4d486c80-96ae-11eb-81d4-85eb6f3d9997.png)
![NotCompletedEvenAfter100Percentage_2](https://user-images.githubusercontent.com/73795557/113714748-59342e80-96ae-11eb-8221-ed613198d6b5.JPG)

**Comment by schak83** [comment]
its latest version 1.0.3.

**Comment by dorkmo** [comment]
it can take an hour

**Comment by dorkmo** [comment]
ive had it take over an hour

**Comment by hoffmang9** [comment]
This is controlled by the speed of the bus and drive at your final destination.
