### ISSUE TITLE
CHIA Pool [Bug] 

### ISSUE THREAD

**Issue by bandusz** [Chia-Network/chia-blockchain#17179]
### What happened?

Hello!

What happens, you can't change the pool?

If we pay for it, nothing happens and the transfer does not go through!!!!

### Version

2,1,3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by HomeLH** [comment]
same condition, the transaction is pending or in mempool, even given 0.001 xch fee

**Comment by Zeitnot2** [comment]
Same problem. Cannot send transaction with any fee. Always pending and never confirmed.

**Comment by bandusz** [comment]
Hello!
  Which ended up being a solution for me.

I completely redid the server, moved the database from chia.net, and after synchronization, deleted the unpaid unit and switched to another pool, after 2 days I was able to switch and you have to watch the diagram when it curves downward, then it switches. Patience is a game of waiting.

**Comment by wjblanke** [comment]
Can you check your logs? Pending will usually be a result of a failure trying to get the TX in the mempool and will be logged. It will retry the TX every 30 minutes. Let us know what you see.

**Comment by wjblanke** [comment]
Are things working for u now? Apologies, I think these logs are from earlier when u had an issue? Let us know.

**Comment by emlowe** [comment]
Closing
