### ISSUE TITLE
[Bug] MempoolManager.new_peak() fails in case of a re-org where the new tip is not a transaction block

### ISSUE THREAD

**Issue by madMAx43v3r** [Chia-Network/chia-blockchain#17186]
### What happened?

In case of a re-org, `MempoolManager.new_peak()` is only called with the new peak, however the function early exits if the given peak is not a transaction block:
https://github.com/Chia-Network/chia-blockchain/blob/cd78dbafdd8e8b5fc109eadcfcb6c2fbbd49ad5f/chia/full_node/mempool_manager.py#L622

As such the mempool is not updated correctly in case of a re-org where the new peak is not a transaction block. Only at the next transaction block it will be corrected.

### Version

master

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Thanks Arvid will take a look

**Comment by arvidn** [comment]
It's not immediately obvious what the best approach to fixing this is. Maybe we could back-track to find the most recent transaction block to see if it matches the current peak.

Another approach, that might be simpler, would be to update `self.peak` every time we see a block, including non-transaction blocks. That way, a (non-tx) block that doesn't follow in the chain could trigger the mempool reorg

**Comment by arvidn** [comment]
the mempool doesn't have the ability to traverse the blockchain. If it gets a non-tx block that's disconnected from its current peak, it can't step back to find the most recent transaction block.

I think this issue has to be fixed in `full_node.py` and make sure it only passes transaction blocks to `mempool_manager.new_peak()`

**Comment by arvidn** [comment]
I'm addressing this issue here: https://github.com/Chia-Network/chia-blockchain/pull/17370

**Comment by wjblanke** [comment]
Thanks for the report!
