### ISSUE TITLE
[Feature Request] Harvesters should report plot counts to farmer

### ISSUE THREAD

**Issue by wolfrage76** [Chia-Network/chia-blockchain#1718]
It's a bit absurd that when monitoring your plots (I primarily do so through the Windows GUI, unfortunately), the plot count, total plot size, and ETA for reward do not include your harvesters.  That means there is no easy way to monitor your totals in a realistic way.

![image](https://user-images.githubusercontent.com/75458290/113718137-59d2c200-96ba-11eb-8b03-9ebce3cebcb2.png)

I have 110 on a harvester but no way to track that on the GUI dash, along with the ones shown on my main machine.

**Comment by hoffmang9** [comment]
Note that the early part of your feature request is there in that you can see local and remote harvesters in Last Attempted Proofs. Pull requests accepted.

**Comment by wolfrage76** [comment]
My point is that the GUI Plot Count should be reporting total plots including harvesters.  They should not need to go to the Last Attempted Proofs and try to make guesses at how many plots they have total based on Scroll, and the ETA info should include all plots, including harvesters, otherwise it's a poor UX.  Currently the GUI dashboard is showing incomplete, incorrect, data.

**Comment by hoffmang9** [comment]
I look forward to your contribution as everyone agrees.

**Comment by anshengme** [comment]
This is a good feature

**Comment by toxicroadkill** [comment]
I 100% agree, from the main machine, be it the cli, or gui, you should be able to see what harvester, and how many plots they have, right now, if something goes wrong and a harvester is not working, you would not be able to know this easily

**Comment by gborges1982** [comment]
I 100% agree

**Comment by hoffmang9** [comment]
Fixed.

**Comment by wolfrage76** [comment]
I knew you could do it, Gene.

**Comment by toxicroadkill** [comment]
very cool


can you see the harvester counts from the cli also?

**Comment by hoffmang9** [comment]
Yes

**Comment by toxicroadkill** [comment]
very nice

stupid question...how ;)

will chia plot check deal show them?
