### ISSUE TITLE
How to build a pool?

### ISSUE THREAD

**Issue by toadzhou** [Chia-Network/chia-blockchain#1719]
I checked the complete wiki document and did not mention the relevant instructions, but now someone has successfully implemented the pool function (https://www.hpool.com/) and it has started to run. Who can help me answer, how do I make multiple accounts run on a pool.
Thank you!

**Comment by hoffmang9** [comment]
Anyone can take the source here and implement a pooling protocol. Our official implementations will be here in late May/June. https://chia.net/2020/11/10/pools-in-chia.html
