### ISSUE TITLE
The wallet block height keeps going back, and the version is v2.1.3 [Bug] 

### ISSUE THREAD

**Issue by imaiops** [Chia-Network/chia-blockchain#17198]
### What happened?

![1](https://github.com/Chia-Network/chia-blockchain/assets/21233395/f9563889-2b61-4b64-8690-f349cbd3b9f4)
After the wallet height is synchronized to the latest block, the block height will be rolled back, and this cycle continues.

### Version

v2.1.3

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Can u send us logs? What height is your derivation index?

What does this report:

chia wallet coins list | wc -l

**Comment by BrandtH22** [comment]
@imaiops , What I recommend doing is:
1. upgrade to the latest release candidate (there are peer related optimizations): https://github.com/Chia-Network/chia-blockchain/releases/tag/2.1.4-rc2 (this has many optimizations for peer connections and syncing)

2. While installing that I would remove the current peers.dat file in ~\.chia\mainnet\db\peers.dat (this will force the client to connect to new peers upon restarting)

3. Once the latest RC is installed, have a new config file created:
 - Stop chia
 - Rename the config file at .chia\mainnet\config\config.yaml
 - Run chia init
 - Copy any custom settings from the old config to the new one (plot directories, pool information, database path, trusted nodes etc) - there are more automated ways to migrate that info if not comfortable editing the config file, yaml is very picky about formatting.
 - Start chia and let it sync
Let us know if any issues or questions arise during the process :+1:

**Comment by wjblanke** [comment]
You dont have many coins... we are *really interested* in what could be happening here. Can you send us the logs in DEBUG mode? You can also configure wallet to not connect to unknown peers. Then it would only deal with your local trusted full node. Things will run faster and it eliminates any issues with remote nodes. Let us know. What CPU are you running?

**Comment by imaiops** [comment]
> @imaiops , What I recommend doing is:
> 
> 1. upgrade to the latest release candidate (there are peer related optimizations): https://github.com/Chia-Network/chia-blockchain/releases/tag/2.1.4-rc2 (this has many optimizations for peer connections and syncing)
> 2. While installing that I would remove the current peers.dat file in ~.chia\mainnet\db\peers.dat (this will force the client to connect to new peers upon restarting)
> 3. Once the latest RC is installed, have a new config file created:
> 
> * Stop chia
> * Rename the config file at .chia\mainnet\config\config.yaml
> * Run chia init
> * Copy any custom settings from the old config to the new one (plot directories, pool information, database path, trusted nodes etc) - there are more automated ways to migrate that info if not comfortable editing the config file, yaml is very picky about formatting.
> * Start chia and let it sync
>   Let us know if any issues or questions arise during the process 👍

![Uploading image.png…]()
Still the same.

**Comment by imaiops** [comment]
> @imaiops , What I recommend doing is:
> 
> 1. upgrade to the latest release candidate (there are peer related optimizations): https://github.com/Chia-Network/chia-blockchain/releases/tag/2.1.4-rc2 (this has many optimizations for peer connections and syncing)
> 2. While installing that I would remove the current peers.dat file in ~.chia\mainnet\db\peers.dat (this will force the client to connect to new peers upon restarting)
> 3. Once the latest RC is installed, have a new config file created:
> 
> * Stop chia
> * Rename the config file at .chia\mainnet\config\config.yaml
> * Run chia init
> * Copy any custom settings from the old config to the new one (plot directories, pool information, database path, trusted nodes etc) - there are more automated ways to migrate that info if not comfortable editing the config file, yaml is very picky about formatting.
> * Start chia and let it sync
>   Let us know if any issues or questions arise during the process 👍

Still the same.
<img width="707" alt="image" src="https://github.com/Chia-Network/chia-blockchain/assets/21233395/496f6d90-9b04-43a7-b427-1359f5fc06a3">

**Comment by wjblanke** [comment]
We really need to see your DEBUG debug.log to see probably what exceptions are being thrown in the code in order to debug this further.  Resyncing your wallet by deleting it may help too, but would like to fix the state you are currently in.

**Comment by emlowe** [comment]
Closing due to lack of response
