### ISSUE TITLE
Can't send deposite to KuCoin [Bug] 

### ISSUE THREAD

**Issue by Ravaldini** [Chia-Network/chia-blockchain#17190]
### What happened?

Xindows 11
Wallet 2.1.3
Doing: Tokens -> Send:
- Address from KuCoin
- Amount 1 XCH
- Fee 0.000005 XCH
Then I press SEND
I see "Pending balance -1 XCH" for some time (sometimes no, it's can stuck on button SEND)
And then it stuck and I see "Error" in all Balance fields
I can reboot the Wallet and start all over

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by dexter4k10** [comment]
I have the same situation, only sent XCH to the OKX

**Comment by wjblanke** [comment]
Can u attach logs from when this occurs?

**Comment by Ravaldini** [comment]
Don't want to attach my log here. But some guy say me that i can add Fee 0.0005 (exactly 0.0005, not standard 0.000005) and it will work. So it helped.
And also i found some post about hackers that attack Chia mempool and now Chia work only with Fee 0.0005... Do u know something about it?)

**Comment by wjblanke** [comment]
The mempool is full these days, so you need a fee in order to be added.

https://www.chia.net/2024/01/11/getting-to-know-the-mempool-and-transaction-fees/

The debug.log doesn't have any private information contained in it, so it is OK to post here. It may reveal IP addresses of peers and such.

**Comment by emlowe** [comment]
Closing due to lack of response
