### ISSUE TITLE
下載新版登入幣消失

### ISSUE THREAD

**Issue by hamson88** [Chia-Network/chia-blockchain#17229]
### What happened?

下載最新版登入24註記詞，6顆XCH消失
![S__50266120](https://github.com/Chia-Network/chia-blockchain/assets/155788907/e6486fbd-7787-40e3-b726-d8d19567d636)
![1631780154571](https://github.com/Chia-Network/chia-blockchain/assets/155788907/829dc64b-590b-42c3-9a4c-35ec08934fec)

### Version

1.1.7

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by jaysonZhou123** [comment]
我也是這個

**Comment by wjblanke** [comment]
Closing please reopen if you still have issues with 2.1.4
