### ISSUE TITLE
Waiting over one week for the transaction to be confirmed[Bug] 

### ISSUE THREAD

**Issue by jaysonZhou123** [Chia-Network/chia-blockchain#17234]
### What happened?

Waiting over one week for the transaction to be confirmed
![Waiting over one week for the transaction to be confirmed](https://github.com/Chia-Network/chia-blockchain/assets/148750510/332b10e4-8219-4adf-8246-76b545d39fdf)

### Version

1.8.1 to 2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
@jaysonZhou123  , as a heads up we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia).

The chain has seen high utilization leading to fee pressure so any transactions submitted without fees are taking lower priority than those which have fees. Many users have been able to resolve their pending fees by cancelling the previous transaction onchain and resubmitting it with a higher fee. 

We have created this guide of standard transaction types and their minimum effective fees (minimum meaning that time sensitive transactions may require more in fees to be processed accordingly):
https://docs.chia.net/coin-set-costs/#estimated-transaction-costs

Let us know if you have any questions or run into issues when resubmitting the transaction :+1:
