### ISSUE TITLE
[Bug] DID wallet stores multiple unspent coins

### ISSUE THREAD

**Issue by greimela** [Chia-Network/chia-blockchain#17242]
### What happened?

Multiple people experienced this while minting NFTs using `nft_mint_bulk`.
The observed behavior was that the Chia wallet tries to double spend a DID coin.

Internally, it uses `did_wallet.get_coin()` to get the latest DID coin to spend for the mint.
But somehow, the DID wallet manages to track multiple DID coins as unspent, resulting in a wrong internal state.

This is how the `coin_records` table looks like in the simulator:
```
coin_name|confirmed_height|spent_height|coin_parent
e2fc52a3345dce499a572114cda6003c341cda04c18c058f8696a905f857b621|4|5|7c0aed36441f459517bee209ed87c9e35f42d8fd28d4fc56ea33f19d0fed0cdd
7c0aed36441f459517bee209ed87c9e35f42d8fd28d4fc56ea33f19d0fed0cdd|4|4|4355ab75e14291adef4db94298f0f4dc84a8ad7294924bdbdaa83dc942f3cb78
61451c80a1e6131ec639f5d79fad90ad9230d090c77a4f7fc239e1014291b43d|5|7|e2fc52a3345dce499a572114cda6003c341cda04c18c058f8696a905f857b621
90ff0aa75506a85a5f30450f23e1f5d51a195b57eb916a0014f02a94c968ce6f|7|8|61451c80a1e6131ec639f5d79fad90ad9230d090c77a4f7fc239e1014291b43d
7dcd4d2729b43f02619ec06144d8f06699dcba1f9c4992397bb1e99c7374de68|8|0|90ff0aa75506a85a5f30450f23e1f5d51a195b57eb916a0014f02a94c968ce6f
2055d34670c3dcbe4862072565bef6a2f35ce6db2165726d4b238a007fb5f693|9|0|7dcd4d2729b43f02619ec06144d8f06699dcba1f9c4992397bb1e99c7374de68
066749c312f754acf8aea5a3bac98a5155ea859a3e54e3aa26f6abe0d3371e5f|10|0|2055d34670c3dcbe4862072565bef6a2f35ce6db2165726d4b238a007fb5f693
```

This started happening with version 2.0.0, it didn't happen in prior versions.

### Version

2.1.3

### What platform are you using?

macOS

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Quex how is this happening? The parent coin 2055d34670c3dcbe4862072565bef6a2f35ce6db2165726d4b238a007fb5f693 is unspent below

2055d34670c3dcbe4862072565bef6a2f35ce6db2165726d4b238a007fb5f693|9|0|7dcd4d2729b43f02619ec06144d8f06699dcba1f9c4992397bb1e99c7374de68
066749c312f754acf8aea5a3bac98a5155ea859a3e54e3aa26f6abe0d3371e5f|10|0|2055d34670c3dcbe4862072565bef6a2f35ce6db2165726d4b238a007fb5f693
