### ISSUE TITLE
[BUG] Experimental GUI installer on new rpi4 8gb raspbian 64 ran, but then nothing happened.

### ISSUE THREAD

**Issue by salamanders** [Chia-Network/chia-blockchain#1724]
**Describe the bug**
Experimental installer chia-blockchain_1.0.3_arm64.deb installed.
Shows up in Accessories - Chia Blockchain
But when run, I get an hourglass, then nothing

**To Reproduce**
1. do all steps in https://github.com/Chia-Network/chia-blockchain/wiki/Raspberry-Pi including enabling swap space
2. reboot
3. run app

**Expected behavior**
App launches

**Desktop (please complete the following information):**
rpi4 
pi@pi4:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

**Additional context**

**Comment by hoffmang9** [comment]
We think we have this fixed for the next release. I'll try to get you a beta installer later today to confirm.

**Comment by salamanders** [comment]
Extra data: I was able to git checkout and run the GUI from the ubuntu instructions, so I am able to spend the meantime catching up on the blockchain sync.

**Comment by kreaninw** [comment]
I can't reproduce this bug in the latest release (1.20). It seems this bug is fixed.
