### ISSUE TITLE
Node not syncing on slow connection despite getting hundreds of MBs of data

### ISSUE THREAD

**Issue by Ractaros96** [Chia-Network/chia-blockchain#17246]
### What happened?

I moved to another town and temporary I have only free, but very slow Internet connection - 512 kbps. My node is stuck at block before moving and yet it when I'm running it constantly downloads data. If it's not syncing node then what Chia client is doing? Database file is not growing faster than my slow Internet connection allows, so the node should be syncing fine.

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Ractaros96 , the client needs to first ensure the peer connections are of quality before syncing which is one reason it will download data from peers prior to actually syncing.

What I recommend doing is:
1. upgrade to the latest release candidate (there are peer related optimizations): https://github.com/Chia-Network/chia-blockchain/releases/tag/2.1.4-rc2 (this has many optimizations for peer connections and syncing)

2. While installing that I would remove the current peers.dat file in ~\.chia\mainnet\db\peers.dat (this will force the client to connect to new peers upon restarting)

3. Once the latest RC is installed, have a new config file created:
 - Stop chia
 - Rename the config file at .chia\mainnet\config\config.yaml
 - Run chia init
 - Copy any custom settings from the old config to the new one (plot directories, pool information, database path, trusted nodes etc) - there are more automated ways to migrate that info if not comfortable editing the config file, yaml is very picky about formatting.
 - Start chia and let it sync
Let us know if any issues or questions arise during the process :+1:

**Comment by wjblanke** [comment]
I am pretty sure you are timing out downloading the weight proof in order to start syncing. The weight proof is 40 megabytes and you weight_proof_timeout is 360 seconds. You could make that longer. The logs will tell you if that timeout is getting hit.
