### ISSUE TITLE
[Bug] creating plot nft loading

### ISSUE THREAD

**Issue by nyamnyom** [Chia-Network/chia-blockchain#17273]
### What happened?

when i start plotting i use 0,00 xch fee > 5 minutes but it running forever
i tried uninstall install again, removing wallet and enter again, delete folder in local storage 
![image](https://github.com/Chia-Network/chia-blockchain/assets/156171466/92aba194-5a68-47d9-bca6-e827c9f0b7d3)

### Version

2.1.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Unfortunately with the fee pressure it will difficult for plot nft transactions to be put on the chain with 0,00 xch fee. We realize it is hard to get chia for a fee when ur just starting to farm. OG plotting is still an option but doesn't allow you to join a pool. Can you send us the logs?

**Comment by nyamnyom** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/13896876/debug.log)
is this the log ?
that you ask ?

**Comment by nyamnyom** [comment]
then how to stop this creating plot and nft from this pool ?, currently in my plot already have the pooling address

**Comment by nyamnyom** [comment]
before this happened i re install the chia but there is no sign of join a  pool like in the other pc i have

**Comment by nyamnyom** [comment]
i tried to clear install again and now it seems like to run normally
