### ISSUE TITLE
Unable to claim rewards！！！！[Bug] 

### ISSUE THREAD

**Issue by Yuanzidan8877123** [Chia-Network/chia-blockchain#17329]
### What happened?

Due to a pending reversible transaction, I've been unable to claim rewards for over a month. How can I deal with this issue? Please help!
<img width="507" alt="屏幕截图 2024-01-13 170532" src="https://github.com/Chia-Network/chia-blockchain/assets/35284044/dae3b84f-0545-4590-b9b7-1e7d2f94e099">

### Version

2.1.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Closing due to lack of response
