### ISSUE TITLE
Not synced or not connected to peers

### ISSUE THREAD

**Issue by Thanatos-JFJ** [Chia-Network/chia-blockchain#17336]
ubuntu 18.04
chia version: 2.1.4rc3.dev195

Farming status: Not synced or not connected to peers
Total chia farmed: 1642.109158461903
User transaction fees: 0.109158461903
Block rewards: 1642.0
Last height farmed: 4753253
Local Harvester
   0 plots of size: 0.000 MiB on-disk, 0.000 MiBe (effective)
Remote Harvester for IP: 192.168.5.52
   3246 plots of size: 321.304 TiB on-disk, 321.430 TiBe (effective)
Remote Harvester for IP: 192.168.5.49
   2961 plots of size: 293.089 TiB on-disk, 293.208 TiBe (effective)
Remote Harvester for IP: 192.168.5.55
   2740 plots of size: 271.211 TiB on-disk, 271.324 TiBe (effective)
Remote Harvester for IP: 192.168.5.57
   1285 plots of size: 127.194 TiB on-disk, 127.245 TiBe (effective)
Remote Harvester for IP: 192.168.5.50
   2590 plots of size: 256.369 TiB on-disk, 256.471 TiBe (effective)
Remote Harvester for IP: 192.168.5.46
   2700 plots of size: 267.247 TiB on-disk, 267.363 TiBe (effective)
Remote Harvester for IP: 192.168.5.53
   2801 plots of size: 277.258 TiB on-disk, 277.365 TiBe (effective)
Remote Harvester for IP: 192.168.5.56
   2721 plots of size: 269.336 TiB on-disk, 269.443 TiBe (effective)
Remote Harvester for IP: 192.168.5.43
   2276 plots of size: 225.290 TiB on-disk, 225.377 TiBe (effective)
Remote Harvester for IP: 192.168.5.60
   3968 plots of size: 392.771 TiB on-disk, 392.925 TiBe (effective)
Remote Harvester for IP: 192.168.5.41
   3352 plots of size: 331.800 TiB on-disk, 331.927 TiBe (effective)
Remote Harvester for IP: 192.168.5.58
   4310 plots of size: 426.616 TiB on-disk, 426.791 TiBe (effective)
Remote Harvester for IP: 192.168.5.54
   2189 plots of size: 216.677 TiB on-disk, 216.762 TiBe (effective)
Remote Harvester for IP: 192.168.5.59
   2974 plots of size: 294.378 TiB on-disk, 294.496 TiBe (effective)
Plot count for all harvesters: 40113
Total size of plots: 3.877 PiB, 3.879 PiBe (effective)
Estimated network space: 31.328 EiB
Expected time to win: 1 day and 19 hours
Note: log into your key using 'chia wallet show' to see rewards for each key

debug.log
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/13946478/debug.log)

**Comment by Thanatos-JFJ** [comment]
在chia 1.8.0 farming 中，突然就不同步，然后全部harvester和farmer升级到2.1.4，现在还是不同步

**Comment by wjblanke** [comment]
Can you run

chia show -s

and

chia peer -c full_node

**Comment by Thanatos-JFJ** [comment]
> Can you run
> 
> chia show -s
> 
> and
> 
> chia peer -c full_node

(venv) ss@ss:~/.chia/mainnet/log$ chia peer -c full_node
Connections:
Type      IP                                      Ports       NodeID      Last Connect      MiB Up|Dwn
FARMER    127.0.0.1                               34036/8447  d391831c... Jan 17 11:19:26      0.4|0.0    
FULL_NODE 181.164.207.21                           8444/8444  4585b728... Jan 19 18:44:21     22.3|1.0    
                                                  -Height:  4770760    -Hash: d4f1b4f4...
FULL_NODE 47.151.140.83                            8444/8444  4a3ff559... Jan 19 18:44:21     94.9|1.1    
                                                  -Height:  4810538    -Hash: 97c5e4a9...
FULL_NODE 202.90.241.130                           8444/8444  ab94a38c... Jan 19 18:44:22     14.3|0.5    
                                                  -Height:  4755870    -Hash: 35c15e75...
FULL_NODE 66.147.239.151                           8444/8444  7cb1722d... Jan 19 18:43:51     10.4|0.4    
                                                  -Height:  3573445    -Hash: b8ed5889...
FULL_NODE 94.110.136.7                             8444/8444  15e47795... Jan 19 18:44:21      6.3|0.5    
                                                  -Height:  4815771    -Hash: 5f07d577...
FULL_NODE 119.18.24.241                            8444/8444  0e93230d... Jan 19 18:44:21      4.6|0.4    
                                                  -Height:  4763751    -Hash: b9ec632c...
FULL_NODE 188.195.66.138                           8444/8444  4b474780... Jan 19 18:44:21      4.1|0.3    
                                                  -Height:  4807181    -Hash: 2a38f69d...
FULL_NODE 72.130.94.218                            8444/8444  6c77fbc8... Jan 19 18:44:21      0.0|0.1    
                                                  -Height:  4777736    -Hash: 020c0caf...
WALLET    127.0.0.1                               43122/0     545044ad... Jan 19 18:40:47      0.0|0.2  



(venv) ss@ss:~/.chia/mainnet/log$ chia show -s
Network: mainnet    Port: 8444   RPC Port: 8555
Node ID: 0f63452150b7415f3adf9863e18d15ebdb3cfeadacce98e5bf529eb9d42abc47
Genesis Challenge: ccd5bb71183532bff220ba46c268991a3ff07eb358e8255a65c30a2dce0e5fbb
Current Blockchain Status: Not Synced. Peak height: 4821816
      Time: Fri Jan 19 2024 16:28:46 CST                  Height:    4821816

Estimated network space: 31.338 EiB
Current difficulty: 11136
Current VDF sub_slot_iters: 574619648

  Height: |   Hash:
  4821816 | 9e02e80ddc224fa75297b270237132a7553a61f8c3fa45ccfbedb5dcfabef015
  4821815 | 6062bfc82ee532e8c22f764c7889aab512740b5bda2a312608411b0447985f6a
  4821814 | 096a1a71430bfd240370a6ab755de3808c6dc1840215e2bd524bf814d4374273
  4821813 | ec27a83f5638553d21431f2646027f7806e5ce0271007e0b87da7205bc178e32
  4821812 | 86c68bf202d38dea0d7aea2399c2999dd561c0742d41fdf45d60a988d31b8a5e
  4821811 | 22c3d87d60fc387a797321995790bd6de6c9c4952785988990978fe50f2b54dc
  4821810 | a871288942c79b920b8f6c3aa1c2c02d3161d518d81d7677be434aa827af0c43
  4821809 | 1ba2e86af7e60c4c04bee751ba1b23ede899a421d6bba3be4e69cb89657bf8a0
  4821808 | ce29111b1452eab34bccae24fa299f838ee9275e34791423eee7a40f0b2eebdd
  4821807 | a1e62c2668c308d0d096661005694f24e0f3107d36f27378681e302e2ad15a31

**Comment by Thanatos-JFJ** [comment]
thanks for your support, it's ok and faming. thank you!



At 2024-01-25 01:13:18, "wjblanke" ***@***.***> wrote:

Can you stop chia, delete peers.dat in the db folder, and restart chia

We think you have the maximum number of peers (outgoing) but none of the peers has a higher peak than you so there is nothing for you to sync to when starting.
