### ISSUE TITLE
Only 8 peers are able to connect to my farmers at once

### ISSUE THREAD

**Issue by Nathan15038** [Chia-Network/chia-blockchain#17334]
### What happened?

I recently updated to the newest version of Chia GUI (version 2.1.4) windows. It seems like after I updated, my database or node started sinking way slower, and I noticed I could only have a maximum of 8 peers at one time. My port 8444 is open across all my farmers/workers. I also noticed that all my farmers also has 8 peers maximum and they are all updated to versions 2.1.4. The other thing is, I realized before updating all my farmers would have a lot appears without a limit on version 2.1.3. Lastly, on my main farmer where I do all my plotting and stuff I downgraded it to 2.1.3 and I noticed it was able to connect many peers. to confirm this I upgraded it back to 2.1.4 and the same thing happened with only the maximum of 8 peers being able to connect.  I’m wondering if anyone else has this issue too. -Thanks

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by xieyusi9** [comment]
I have encountered the same issue as well.

**Comment by wjblanke** [comment]
Can u tell us the target_peer_count value is when running 2.1.3 and 2.1.4? There were not many changes made between the two versions so we are really interested in the fact that switching between them causes a difference. It might take a while to get back up above 8 peers because you are limited to 8 outgoing so on restart you will need to wait for others to connect. Let us know.

**Comment by Nathan15038** [comment]
@wjblanke I'm sorry I haven't explored that much into Chia GUI and I don't know where the target_peer_count would be located. But overall, I think the problem might've fixed itself because at least my main computer now is actually getting a lot of peer connections and also one of my computers that I was waiting to synchronize to the block chain also connected to peers. Lastly, I have one more computer that needs to be synced to the block chain but to be honest not that much in a rush of that and it's probably gonna take a long time because it is a hard system. The weird thing that I do want to point out is that it used to sync at 60,000 blocks a day and now it's down to about 7,000 blocks a day. I also know I have 8444 open because of the port checker and the fact that a lot of peers are not 8444/8444 but instead, ######/8444.
