### ISSUE TITLE
Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.

### ISSUE THREAD

**Issue by hajes** [Chia-Network/chia-blockchain#17330]
### What happened?

`chia plotnft claim -i 14`

error output

`Error performing operation on Plot NFT -f ..... wallet id: 14: {'error': 'Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.', 'success': False,`

`chia wallet delete_unconfirmed_transactions -i 14 && chia plotnft claim -i 14`

output

`Transaction submitted to nodes: [{'peer_id': '......', 'inclusion_status': 'FAILED', 'error_msg': 'ALREADY_INCLUDING_TRANSACTION'}]`

claimed amount seems to be `in mempool` for 2 hours, and nothing in wallet yet.

### Version

2.1.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Quex we probably need an RBF for this since there is no fee here.

The claim made it into the mempool with no fee but its likely to bump along the bottom as there is so much fee pressure currrently.

**Comment by hajes** [comment]
Third attempt, finally successful. Transaction was "stuck" for a day before it came through. Looks like small fee is needed for claims as well. I always gave small fee for normal transactions. It never happened before, so I guess for 20 XCH amounts, fee is required.

No idea whether it is bug or normal behaviour. Close it guys if needed.

**Comment by wjblanke** [comment]
Glad it worked for you. Keeping open for RBF for now.

**Comment by wjblanke** [comment]
RBF is on the roadmap so closing this as it is being tracked there
