### ISSUE TITLE
not synchronize

### ISSUE THREAD

**Issue by Alanborok** [Chia-Network/chia-blockchain#17372]
### What happened?

It does not synchronize the latest version.

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Please attach DEBUG debug.log so we can try to figure out what is going on

**Comment by Alanborok** [comment]
![Sin título](https://github.com/Chia-Network/chia-blockchain/assets/157296793/da1f1988-b86f-4f1f-8860-717fad019438)

**Comment by Alanborok** [comment]
It always stays like this. but only with this PC.

**Comment by wjblanke** [comment]
Can u post DEBUG debug.log here? Something in the log will say why it is stalled

**Comment by emlowe** [comment]
Closing due to lack of response
