### ISSUE TITLE
deposit did not arrive

### ISSUE THREAD

**Issue by marbush1** [Chia-Network/chia-blockchain#17407]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/17406

<div type='discussions-op-text'>

<sup>Originally posted by **marbush1** January 26, 2024</sup>
Hello, 
that is my transaction ID, from mexc to chia wallet. I can see it in xchscan but nothing in my wallet 0x2ec7f142323a114f229b7e672588ea177ac5abd5be803297c5ef6ba89f0c31b8
what should I do? thanks in advance</div>

**Comment by wjblanke** [comment]
https://alltheblocks.net/chia/coin/2ec7f142323a114f229b7e672588ea177ac5abd5be803297c5ef6ba89f0c31b8

Looks like it moved OK. Are you sure that destination address belongs to your wallet. 



Maybe delete resync your wallet? If the address belongs to you it is fine and on the chain.

**Comment by marbush1** [comment]
Hello, the problem was handled in discord support. It was a system time problem. Thanks for your assistance.

**Comment by wjblanke** [comment]
OK closing as resolved. Thanks for letting us know the resolution.
