### ISSUE TITLE
[BUG] ERROR in reading bytes at offset

### ISSUE THREAD

**Issue by GeorgePapageorgakis** [Chia-Network/chia-blockchain#1742]
I fell on this bug twice. After I left my pc creating plots i found it the next day at the same progress % in plots menu with the following:

...
Bucket 84 uniform sort. Ram: 5.934GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.

Only read 0 of 262132 bytes at offset 0 from "D:\\Chia temp\\plot-k32-2021-04-07-07-59-b43d070a0ca1f5a83453b23d8c0650dfe6b3cb891f257004426a1a65b78e9d39.plot.p1.t4.sort_bucket_084.tmp"with length 872453946. Error 1. Retrying in five minutes.

Only read 0 of 262132 bytes at offset 0 from "D:\\Chia temp\\plot-k32-2021-04-07-07-59-b43d070a0ca1f5a83453b23d8c0650dfe6b3cb891f257004426a1a65b78e9d39.plot.p1.t4.sort_bucket_084.tmp"with length 872453946. Error 1. Retrying in five minutes.
...

At this point, the drive D was inaccessible:
![εικόνα](https://user-images.githubusercontent.com/9392917/113899052-17ea6e80-97d5-11eb-95b6-20e99425a67b.png)
and I had to shut down the chia app and shut down (restart didnt work) the pc.

- OS: Windwos 10 64 pro
- OS Version/Flavor: 20H2
- CPU: i7 6700K, samsung evo 850 1TB.

**Comment by hoffmang9** [comment]
This is a hardware error on your side. It is either the storage but is often unstable RAM.
