### ISSUE TITLE
[BUG] Error: Generated checksum for "electron-v11.3.0-linux-x64.zip" did not match expected checksum.

### ISSUE THREAD

**Issue by zoharHao** [Chia-Network/chia-blockchain#1743]
> electron@11.3.0 postinstall /data/apps/chia-blockchain/chia-blockchain-gui/node_modules/electron
> node install.js

Downloading electron-v11.3.0-linux-x64.zip: [===========================================================================] 100% ETA: 0.0 seconds 
Error: Generated checksum for "electron-v11.3.0-linux-x64.zip" did not match expected checksum.
    at Hash.hasher.on (/data/apps/chia-blockchain/chia-blockchain-gui/node_modules/sumchecker/index.js:133:20)
    at Hash.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):                        
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@11.3.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@11.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gucloud/.npm/_logs/2021-04-07T17_57_34_913Z-debug.log

**Comment by hoffmang9** [comment]
That looks like a problem with your OS getting electron. If it's not that then the error is sooner in the script's output
