### ISSUE TITLE
I am farming 5 plots till now. But no coin is awarded

### ISSUE THREAD

**Issue by schak83** [Chia-Network/chia-blockchain#1745]
is something I am missing. screen shows all 5 plots are farming status. I did not receive a single coin yet. :) it says winning cances is in 5 months.

**Comment by hoffmang9** [comment]
This is working as intended but you will have to wait a while to win with that small a farm.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#i-have-only-10-tb-will-i-ever-win-xch-on-mainnet
