### ISSUE TITLE
[Bug]  Harvester tab in GUI won't render if harvester has a lot of plots

### ISSUE THREAD

**Issue by JamesKrolak** [Chia-Network/chia-blockchain#17455]
### What happened?

The Harvester tab in the GUI won't update fully when the farm has a lot of plots.  It was slow to load, but worked okay when I was at about 95,000 plots and under.  Now that I'm above 96,000 plots, the fields and graphs won't populate.  I have 1 full node with 20k C0 and 36k C5 plots and 1 remote harvester with 40k C5 plots.  I've also had the same problems if I move 10K of those plots from the full node to the remote harvester.  If I take a bunch of those plots out of the farm (by removing a directory from the plot directories managed in the GUI) then the Harvester tab loads okay.

Screenshot:
![harvester tab](https://github.com/Chia-Network/chia-blockchain/assets/38671509/5e54c0a8-e919-443a-aa86-c4c6d335f19e)

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
I believe this is a size problem in the RPC call - you might have success with increasing `daemon_max_message_size` in config.yaml

@ChiaMineJP thoughts here

**Comment by emlowe** [comment]
You should have errors on your Chia log file if you are hitting the maximum message size

**Comment by wjblanke** [comment]
Or you could try making the parent directory name smaller to fit the plots in the message size. Adjusting the message size to be larger is also a solution.

**Comment by ChiaMineJP** [comment]
This issue seems relevant with this https://github.com/Chia-Network/chia-blockchain/issues/16711

**Comment by JamesKrolak** [comment]
> This issue seems relevant with this #16711

Likely.  I had found that other bug report first, but that was closed back in November.  That's why I opened a new one.

**Comment by JamesKrolak** [comment]
> You should have errors on your Chia log file if you are hitting the maximum message size

Shoot.  I missed your comments last week.  I had already switched my farmer and harvester to 2 separate full nodes 'cuz there sometimes were performance issues, but I couldn't see that in the GUI when it was happening.  I think I did that switch on 2/11.  Still have the full node logs from the 11th, but can't find anything with the word "error" in it and only 1 line with "message" in it.

**Comment by JamesKrolak** [comment]
> Or you could try making the parent directory name smaller to fit the plots in the message size. Adjusting the message size to be larger is also a solution.

All of my plots are right at the root of the drive they are on.  So, for example, the full path would be something like:
D:\plot-k32-2022-09-19-12-22-bdd2f4684051499912afe62419c5b1bab2ae51ad655b347715ea5b954b56e846.plot

**Comment by wjblanke** [comment]
I see, then there is nothing else you can do to shorten the path. Maybe try to increase the message size limit in the code if you see the issue again.
