### ISSUE TITLE
Issues on farm setup with Windows DFS 

### ISSUE THREAD

**Issue by robcirrus** [Chia-Network/chia-blockchain#17524]
### What happened?

This is to outline some areas that I believe should be reviewed in the harvesters code related to issues I found while setting up a DFS file sharing system for a farm.

I've setup an environment that is implementing a Windows DFS (Distributed File Service) to turn all the harvesters into file servers sharing the plots and setting up a Windows Server HyperV server with multiple VMs as harvesters, each having a GPU attached. One of the reasons moving to this setup is that most of my harvesters are HP 60-bay SL4540 or 60-bay Apollo 4510 with HP D6000 JBODs attached. The SL4540 systems are E5-24xxv2 systems that have no ability to add GPUs and can only CPU decompress and the Apollo 4510 can only use a GPU that doesn't require external power as no power connectors exist. I set these up way before compressed plots were even contemplated. I had installed NVidia A2000 in Apollo 4510 and they work fine but can't handle a huge load, especially with the filter halving coming up.

Some benefits of using DFS is that I can within minutes within the DFS management tool move the shared drives between any of the VM harvesters, either for load balancing, testing or failure issues. It also helps with centralizing a place to look for issues. Seting up the VM harvesters using a few share names to the DFS system with subfolders containing plots and setting recursive_plot_scan: true allows moving the DFS shared drives between these few share names possible without touching the harvesters. When folders are moved between folders in the DFS, the harvesters automatically pickup the changes on it's next refresh cycle. Also allows placing diffferent plot families (Chia, GH, NoSSD, DrPlotter) on same file servers under different folders and just share them to their respective harvester VMs.  

Benefits of hosting harvesters under VMs is having the ability to setup a system (or more) for multiple VM harvesters sharing power/resources and be able to quickly and easily upgrade or test different GPUs, as I can add the GPU, setup the VM, configure the new VM into DFS, then move the DFS folders to the new VM with the farm only going down while adding the GPU to the system, Or if setting up a 2nd HyperV without the farm going down at all. When filter halving comes around, I can add new VMS for spreading around the load or put in higher-end GPUs easily. Also can move just certain folders within DFS containing different plot compressions to match with the capacity of the GPU. 

Environment:

Windows Server 2022 HyperV hosting VMs
DL580 G9
	4x E7-8880v3
	1TB 2133 ram
	2x 800GB SAS 2.5, raid 1 for OS and VMs
	2x 10GBe setup as virtual switch for Host,VMs
	5x PCIE3 x16 slots, all are spaced to allow double wide in each
	6x 150w GPU power connectors
	3x NVidia 3080ti GPU

Windows Server 2022 DC in a VM (DFS requires a domain setup)
	Hosts the DFS service	
 
14x existing harvesters turned into file servers. 
	111,758 plots, 8.8 PiB raw, 10.9 PiBe
	most volumes are 3x, 4x, 5x drives in raid 0 
		(helps with IO responses especially during copying plots around)
	volume names are ChiaFarm01 - ChiaFarmxx

(have a 2nd farm setup similar with 7.3 Pib raw, 9.3 PiBe and a farm of 35k NoSSD plots) 

DFS folder structure:
\\ChiaDom.local\Plots		(DFS root folder)
	ChiaHarvVM1A		(management group folders for a VM harvester, using 4x (A,B,C,D) for each VM harvester)
		BlankVM1A	(folder reference pointing to local blank folder, related to issue #2)
		Svr1		(group folder for a file server hosting plots)
			PlotsE	(folder linked to a shared volume on the file server 1)
			PlotsF	(folder linked to a shared volume on the file server 1)
			PlotsG	(folder linked to a shared volume on the file server 1)
		Svr2		(group folder for a file server hosting plots)
			PlotsE	(folder linked to a shared volume on the file server 2)
			PlotsF	(folder linked to a shared volume on the file server 2)
			PlotsG	(folder linked to a shared volume on the file server 2)
	ChiaHarvVM1B		(management group folders for a VM harvester, using 4x (A,B,C,D) for each VM harvester)
		BlankVM1B	(folder reference pointing to local blank folder, related to issue #2)
		Svr3		(group folder for a file server hosting plots)
			PlotsE	(folder linked to a shared volume on the file server 1)
			PlotsF	(folder linked to a shared volume on the file server 1)
			PlotsG	(folder linked to a shared volume on the file server 1)
		Svr4		(group folder for a file server hosting plots)
			PlotsE	(folder linked to a shared volume on the file server 2)
			PlotsF	(folder linked to a shared volume on the file server 2)
			PlotsG	(folder linked to a shared volume on the file server 2)
	ChiaHarvVM1C		(management group folders for a VM harvester, using 4x (A,B,C,D) for each VM harvester)
		(same as above)
	ChiaHarvVM1D		(management group folders for a VM harvester, using 4x (A,B,C,D) for each VM harvester)
		(same as above)

VM harvesters config setup for directories:
plot_directories:
- \\ChiaDC1.ChiaDom.local\Plots\ChiaHarvVM1A
- \\ChiaDC1.ChiaDom.local\Plots\ChiaHarvVM1B
- \\ChiaDC1.ChiaDom.local\Plots\ChiaHarvVM1C
- \\ChiaDC1.ChiaDom.local\Plots\ChiaHarvVM1D
recursive_plot_scan: true

Setting up multiple references (A,B,C,D) are to help with an issue that if any of the shared volumes under this grouping goes down, or offline, (like PlotsE of Svr1 of ChiaHarvVM1A) then ALL volumes defined in the same group (A,B,C,C) go offline to harvester, so you loose the whole group. Setting multiple groupings allow for limiting how many shared folders go offline within the group. I first setup just one, and had one volume go offline and entire harvester had no plots to harvest. 

Issue #1:
Related to the recursive group reference bringing related subfolders down: 
I would recommend looking at code to maybe add a table of the recursed folders under each of the plot_directories references, and only removing/tagging suspect just one of the recursed folder references instead of the folder reference in the config file.

Issue #2:
If a DFS folder level like ChiaHarvVM1A above does NOT have any subfolders defined, or ANY grouping folder lower in the structure tree (those not linked to an actual folder somewhere, like SVR1 above), DFS reports a placeholder folder named ".DFSFolderLink". This is not a real folder and can't be accessed. Chia Harvester reports the error below when it sees it and brings down the entire plot_directories reference it was found in. 

2024-01-14T12:52:57.850 harvester chia.plotting.util      : WARNING  Error reading directory \\ChiaDC1.ChiaDom.local\Plots\ChiaHarvVM1B [WinError 53] The network path was not found: '\\\\ChiaDC1.ChiaDom.local\\Plots\\ChiaHarvVM1A\\.DFSFolderLink'

Suggest harvester code to NOT try to traverse a folder named ".DFSFolderLink" so it does not bring down the entire group. 
The workaround is putting a blank folder reference like BlankVM1A in DFS tree above so there is at least one real folder to see.

Issue #3:
DFS references when mapping to the share, they are usually referenced by \\domain_name\DFS_Shared_Folder
When you use the CLI command to add plots with "chia plots add \\ChiaDom.local\Plots\ChiaHarvVM1A"
It converts to the UNC name that includes the DFS server that is currently hosting the DFS folder, "\\ChiaDC1.ChiaDom.local\Plots\ChiaHarvVM1A" and stores it in the config file that way. This is usually fine when you have 1 DFS server, but I setup 2x DFS servers for redundancy and when DFS decided to host it from the 2nd DFS server, the plots were lost. 
I would suggest that the add plots command keep the \\domain_name\DFS_Shared_Folder name while saving the folder reference in the config file and expand it to the UNC format when it reads the config lines in. That way it will pick up the correct DFS server currently hosting the shares. Also, during refresh or errors of ready folders, it go back to the config file directories list and re-evaluate them to expand into UNC names that includes the current DFS server hosting the shares. This would auto-recover finding the plots whenever the DFS system decides to move the current hosting server around.

Found that setting up a windows domain ending in .local has issues for Ubuntu with it's using DFS or windows shared folders. I set mine up with .local and was having issues using Ubuntu harvester VMs. I will need to redo the domain to a name other than .local so I can test using Ubuntu VMs under HyperV. I have testing Ubuntu VM plotters under HyperV and creating plots seems to have only about a 5% degregation from a native Ubuntu plotter on same system. 

It's been a great setup. I've been running under it for over a month with only the issues outlined above. Hosting VM harvesters under HyperV seems to be only about a 3% performance degredation compared to a non-VM server setup with same server/GPU when using bladebit simulate. 

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
It's not likely we will be able to support this in the near term. PRs are always welcome if you can get it working.
