### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yuramarinovsky** [Chia-Network/chia-blockchain#17552]
### What happened?

after update gui to 2.1.4 ... program window stay in Full Node starting
![image](https://github.com/Chia-Network/chia-blockchain/assets/159946450/6e0138d8-a124-4750-93c5-c04d37071a3a)

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Can you send us the logs? Most likely you are using a v1 db from your old version? New builds only work with v2 dbs. Let us know!

**Comment by emlowe** [comment]
closing issue due to lack of response
