### ISSUE TITLE
[BUG] when running command " npm run electron &" on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by zoharHao** [Chia-Network/chia-blockchain#1757]
(venv) gucloud@gucloud:/data/apps/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 85634
(venv) gucloud@gucloud:/data/apps/chia-blockchain/chia-blockchain-gui$ 
> electron
> electron .

/data/apps/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
The futex facility returned an unexpected error code.
/data/apps/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGABRT

- OS: Ubuntu 20.04.2 LTS
-

**Comment by hoffmang9** [comment]
Is Ubuntu Desktop installed?

**Comment by zoharHao** [comment]
> Is Ubuntu Desktop installed?
NO, is Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-26-generic x86_64)

**Comment by hoffmang9** [comment]
You can not run the GUI without a Linux GUI to support it.
