### ISSUE TITLE
[Bug] Installation of ChiaSetup-2.2.0rc3.exe Windows

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/chia-blockchain#17579]
### What happened?

After shutting down Chia and rebooting the server for a fresh state. Installing ChiaSetup-2.2.0rc3.exe and selecting
![image](https://github.com/Chia-Network/chia-blockchain/assets/81637574/ccf1c0b3-dbef-450b-8cf5-c3ff7bf76cce)
The system just spins
![image](https://github.com/Chia-Network/chia-blockchain/assets/81637574/47c4bf93-a8f5-4bcf-842b-4b1f0b389769)
Selecting (Anyone who uses this machine has worked from chia 2.0.0 all the way to ChiaSetup-2.2.0rc2 and just changed when rc3 was released. While trying to load and  spinning
 if you open a CMD windows and run C:\Program Files\Chia\resources\app.asar.unpacked\daemon>chia run_daemon
the GUI will then seem to load.
.
.
When you uninstall chia, reboot the server and reinstall chia and select (Only for me ) it installs differently and comes up. So what changed between rc2 and rc3 on the installation?
 So it seems we need a ChiaSetup-2.2.0rc3B.exe or ChiaSetup-2.2.0rc4.exe before release.

### Version

ChiaSetup-2.2.0rc3.exe

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Drhicom** [comment]
When you look at the source for rc2 and then rc3 and see you left out a cup of flower. Please DM me a link and I will be happy to test the fix and report back.

**Comment by ChiaMineJP** [comment]
I'll check this issue

**Comment by ChiaMineJP** [comment]
It appears to be an issue with the installation path. If any parent folder of the installation directory contains a space in its name, the Chia daemon fails to run.
I selected "Install for anyone on this computer" and specified the installation folder as "C:\aaa\Chia." Following this, the GUI/daemon starts without any issues.

I will continue to investigate.

**Comment by felixbrucker** [comment]
Maybe this helps: https://stackoverflow.com/a/30893153

**Comment by ChiaMineJP** [comment]
@Drhicom @felixbrucker 
Really appreciate your reports and sorry for inconvinience.

Thanks to you both, I was able to create a patch PR for this issue.
https://github.com/Chia-Network/chia-blockchain-gui/pull/2277

**Comment by Drhicom** [comment]
So are you coming out with RC3B or RC4??

**Comment by wjblanke** [comment]
This should be fixed in the next rc. Likely we will remove the feature temporarily since we are fighting electron bugs. Thanks for the report!
