### ISSUE TITLE
Spendable balance 0

### ISSUE THREAD

**Issue by sashapetrr** [Chia-Network/chia-blockchain#17599]
### What happened?

my spendable balance isn't correct, I see 0, but it shoul be like pending, pending total balance = correct.
i don`t have any new transactions, they were all confirmed 6 month ago.
i tried resync - nothing happened
download new version - nothing
sign out - nothing
please help me withdraw XCH
![Знімок екрана 2024-02-23 135129](https://github.com/Chia-Network/chia-blockchain/assets/161030979/65500737-7fcd-43b5-b317-de2f47a79e32)

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
You are probably waiting for change from a previous transaction or an outstanding offer that has locked your coins. That's why the spendable is 0. Once those clear, pending balance should move to spendable balance.
