### ISSUE TITLE
[Bug] XCH still confirming and cannot sent out.

### ISSUE THREAD

**Issue by jaysonZhou123** [Chia-Network/chia-blockchain#17603]
### What happened?

XCH still confirming and cannot sent out.
![XCH still confirming and cannot sent out](https://github.com/Chia-Network/chia-blockchain/assets/148750510/b9d99cdb-cbba-4380-bbc0-d2ce53ae2ea7)

### Version

2.1.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Did you put a fee in with your transaction? If not it may take a while to clear but it should eventually.
