### ISSUE TITLE
[Bug] function `get_host_parameter_limit` is returning a wrong value with Python 3.11

### ISSUE THREAD

**Issue by neurosis69** [Chia-Network/chia-blockchain#17616]
### What happened?

**SQLITE Limits**

According to the sqlite limits [documentation](https://www.sqlite.org/limits.html#max_variable_number) the value for SQLITE_LIMIT_VARIABLE_NUMBER should be 999 for version <  3.32.0 and 32766 for versions >= 3.32.0. 

The last line of this limits documentation states:
_The maximum host parameter number can be lowered at run-time using the [sqlite3_limit](https://www.sqlite.org/c3ref/limit.html)(db,[SQLITE_LIMIT_VARIABLE_NUMBER](https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitvariablenumber),size) interface._

In another sqlite docu about parameters [documentation](https://www.sqlite.org/lang_expr.html#varparam) we can find this last line:
_The maximum parameter number is set at compile-time by the [SQLITE_MAX_VARIABLE_NUMBER](https://www.sqlite.org/limits.html#max_variable_number) macro. An individual [database connection](https://www.sqlite.org/c3ref/sqlite3.html) D can reduce its maximum parameter number below the compile-time maximum using the [sqlite3_limit](https://www.sqlite.org/c3ref/limit.html)(D, [SQLITE_LIMIT_VARIABLE_NUMBER](https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitvariablenumber),...) interface._

**Chia implementation**

The function [get_host_parameter_limit](https://github.com/Chia-Network/chia-blockchain/blob/883b48daca7656c786853e7d1b83335aa4afc353/chia/util/db_wrapper.py#L81-L99) is used to determine the value for `SQLITE_MAX_VARIABLE_NUMBER`.

When using python 3.11 the parameter limit is not directly derived by the sqlite limits from the else branch, but it is derived using the [getlimit](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.getlimit) function. 

Apparently the derived limit is too high when using python 3.11:
```
-- Parameter Limit: 250000
-- SQLITE3 Version: (3, 45, 1)
-- Limit Category for SQLITE_LIMIT_VARIABLE_NUMBER: 9
-- Sys Version: sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
```

Tested using this little script:
```
from chia.util.db_wrapper import get_host_parameter_limit
import sqlite3
import sys
parameter_limit = get_host_parameter_limit()
print(f"-- Parameter Limit: {parameter_limit}")
print(f"-- SQLITE3 Version: {sqlite3.sqlite_version_info}")
print(f"-- Limit Category for SQLITE_LIMIT_VARIABLE_NUMBER: {sqlite3.SQLITE_LIMIT_VARIABLE_NUMBER}")
print(f"-- Sys Version: {sys.version_info}")
```

Ran into the issue when testing a v1 db upgrade for @AmineKhaldi and got this error
```
conversion failed with error: too many SQL variables.
```

### Version

2.0.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
I need to check with Amine on this

**Comment by neurosis69** [comment]
Interesting. So was it a real issue in the end with python 3.11? 
Amine showed me a script 2 weeks ago where it looked like that it worked with 250_000 bind variables.
