### ISSUE TITLE
[Bug] pending transactions are out of sync

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#17627]
### What happened?

the pending Transactions are incorrect. This happened when using the coin combine functionality for a cat token:
- confirmed transactions are shown as pending in the xch wallet (fee transaction)
- some transactions are missing in the cat wallet

XCH wallet (fees):
![image](https://github.com/Chia-Network/chia-blockchain/assets/12736950/cdc23180-6017-4965-b8a9-7403f9995558)

Cat wallet (same transactions, confirmed but some missing):
![image](https://github.com/Chia-Network/chia-blockchain/assets/12736950/e2d8ae5d-69c4-4046-9c24-ab16cd7e5a55)

### Version

2.2.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
The transaction history is using a heuristic and is a best effort. Because of privacy features in chia with the way coins are processed using different addresses it can be difficult to reconstruct the TX history from the chain.
