### ISSUE TITLE
[Bug] Wallet can't sync

### ISSUE THREAD

**Issue by SparklingJim** [Chia-Network/chia-blockchain#17640]
### What happened?

Installed Chia 2.1.4 on Windows 11 to use it as a wallet only. 
Wallet address: 
xch1t7du2erudfd4aut28mvrmqrrseuhu2tj068zs69ycc4sruyxa38seyy8qy
Sent some XCH to it. Hash:
0xaa3bc8531a88b2ce178a72801af24ade533bc43b609e2da705c1c74ce5be4d5a
Shows alight on explorer, but not the wallet itself. 
![image](https://github.com/Chia-Network/chia-blockchain/assets/162157075/2287baef-c8e9-4d49-aac3-a39903dd7fee)
Tried resyncing wallet, deleting the db folder in mainnet/wallet and then tried re-entering the seed on a different device with Windows 10. Tried setting DNS to 8.8.8.8 and tried a different network. Still says 0 and transaction history is empty

### Version

2.1.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2024-03-05T00:13:33.308 wallet chia.server.start_service  : ERROR    fatal uncaught exception: AttributeError: 'int' object has no attribute 'name'
Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 20, in log_exceptions
  File "chia\server\start_service.py", line 321, in async_run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 636, in run_until_complete
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 603, in run_forever
  File "asyncio\base_events.py", line 1871, in _run_once
  File "asyncio\windows_events.py", line 444, in select
  File "asyncio\windows_events.py", line 797, in _poll
  File "chia\server\start_service.py", line 309, in _accept_signal
AttributeError: 'int' object has no attribute 'name'
```

**Comment by wjblanke** [comment]
You could try increasing the derivation index. You could have a gap where there are no coins and the wallet wouldn't sync past that.

The log is from shutdown and isn't related to your issue. If you can attach the full logs maybe we can find something.

**Comment by SparklingJim** [comment]
> First thing to note, the orange/yellow color on "Wallet" (in photo) means its not syncd, so any balance will not be accurate for the current height of the network, it will only show the last point it syncd to (you should be able to click on it to see if you are connected to any peers at the time).
> 
> > Here is the full log, shouldn't be that long since it's a freshly created wallet.
> > [debug.log](https://github.com/Chia-Network/chia-blockchain/files/14515491/debug.log)
> 
> Okay looking at the log I saw 192.168.1.1 was being used for DNS on some entries, I assume thats your home router which is using your ISP default DNS servers? I also saw 150.203.1.3 which when I tried using that DNS server it did not resolve any domain names for me, however maybe thats something that doesn't grant access to external IPs.
> 
> You mentioned using 8.8.8.8 as a DNS server, but I don't see any errors mentioned in the log file with it, did you shutdown and restart Chia after changing the DNS servers? Sometimes I find when changing network settings locally I need to restart the application or the computer entirely for the changes to be reflected. I'm wondering if this is a case of the local ISP blocking certain domains from being resolved and "timing out" eventually.
> 
> Open up a command prompt and type nslookup, this should bring up a quick way to query your current DNS server, you should be able to manually type the default chia introducers below and see if they return an IPv4 and IPv6 results.
> 
> dns-introducer.chia.net chia.ctrlaltdel.ch seeder.dexie.space chia-seeder.h9.com chia.hoffmang.com seeder.xchpool.org
> 
> If you are getting results then I imagine you shouldn't be getting the error messages about failing to resolve, but if you are unable to get results from your query then its definitely something with the DNS settings on your machine (or those servers refusing to resolve them), try rebooting and/or at least restarting Chia when you change to using a different name server. (I just used 1.1.1.2 and 8.8.8.8 public DNS servers for example and all the domains returned results)

Thank you for the detailed step by step guide, changing the DNS on the router worked
