### ISSUE TITLE
[BUG] Caught plotting error: std::bad_alloc                                                                                                                 

### ISSUE THREAD

**Issue by namelessperson0** [Chia-Network/chia-blockchain#1765]
Getting the below error in Debian 10 and Ubuntu 20 while creating plots
```
Computing table 2                                                                                                                                     
Caught plotting error: std::bad_alloc                                                                                                                 
Traceback (most recent call last):                                                                                                                    
  File "/root/chia-blockchain/venv/bin/chia", line 33, in <module>                                                                                    
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())                                                                        
  File "/root/chia-blockchain/src/cmds/chia.py", line 76, in main                                                                                     
    cli()  # pylint: disable=no-value-for-parameter
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs) 
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/chia-blockchain/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/chia-blockchain/src/cmds/plots.py", line 134, in create_cmd
    create_plots(Params(), ctx.obj["root_path"])
  File "/root/chia-blockchain/src/plotting/create_plots.py", line 164, in create_plots
    plotter.create_plot_disk(
RuntimeError: std::exception
```
Command used to create plots is `chia plots create -d /mnt/vol -t /mnt/vol
`
The error occurs in computing table 2.

**Comment by hoffmang9** [comment]
This can be permissions or a problem with your filesystem but often it is showing you that you RAM has an issue - bad sitck/OC/XMP. Closing because it's a hardware problem.

**Comment by namelessperson0** [comment]
> This can be permissions or a problem with your filesystem but often it is showing you that you RAM has an issue - bad sitck/OC/XMP. Closing because it's a hardware problem.

Got same error in 2 different PC's. So must not be a hardware problem. Had used xfs filesytem. That might be an issue I think.

**Comment by namelessperson0** [comment]
> This can be permissions or a problem with your filesystem but often it is showing you that you RAM has an issue - bad sitck/OC/XMP. Closing because it's a hardware problem.

Tried `chmod 777 /mnt/vol` and partitioned with ext4 filesystem. Still got same error.

**Comment by hoffmang9** [comment]
You're going to need to diagnose your RAM. Chia plotting is a better memory test than memtest86 as it is a loaded RAM test.

**Comment by Dravenex** [comment]
@hoffmang9 You're always saying that this kind of problems is due to bad hardware and close the thread. I don't think at all that it is a hardware problem. Everything runs fine except chia. So this kind of threads should first be closed if A) there is a solution to fix the "hardware" issues or B) have a deeper look into this problems to detect some software issues.

I'dont like that this kind of issues get closed asap withouth further inspection.

**Comment by hoffmang9** [comment]
We can't fix your computer hardware and in the past four months every time this issue comes up and it is fully traced down, it's either storage hardware failure or bad RAM. If you can put your physical RAM into this thread then maybe we could help.

**Comment by Dravenex** [comment]
@hoffmang9 I already solved the issue by myself

The problem was that I reduced the size of the pagefile.sys file too much. In Windows there is an option called "virtual RAM" that decides how big the pagefile.sys is. Once I changed the option again to "Managed by system" parallel plotting started working again. No faulty hardware, just a faulty software configuration.

**Comment by hoffmang9** [comment]
A faulty software RAM configuration...

**Comment by namelessperson0** [comment]
> A faulty software RAM configuration...

Had 4 gb RAM when the error occured. Added additional 4 gb RAM and then the error went away.

**Comment by harlay0728** [comment]
> 
> 
> @hoffmang9 I already solved the issue by myself
> 
> The problem was that I reduced the size of the pagefile.sys file too much. In Windows there is an option called "virtual RAM" that decides how big the pagefile.sys is. Once I changed the option again to "Managed by system" parallel plotting started working again. No faulty hardware, just a faulty software configuration.

Thanks,  I solved this problem with your method. Obviously, it's not the problem of hardware.  ≧◔◡◔≦
