### ISSUE TITLE
Did 2.2.0 release get recalled?

### ISSUE THREAD

**Issue by chenrui333** [Chia-Network/chia-blockchain#17661]
👋 looks like the 2.2.0 release is not in the release list anymore, did it get recalled? Thanks!

relates to https://github.com/Homebrew/homebrew-cask/pull/168386

**Comment by chenrui333** [comment]
- also relates to https://github.com/Homebrew/homebrew-cask/pull/167840

**Comment by wjblanke** [comment]
Yes, 2.2.0 has been removed. 2.2.1 should be coming out today.
