### ISSUE TITLE
Latest version of Chia does not open in my PC[Bug] 

### ISSUE THREAD

**Issue by REIS77-COMMITS** [Chia-Network/chia-blockchain#17675]
### What happened?

All the versions after 2.0 is not opening in my PC. 

### Version

2.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @REIS77-COMMITS , can you describe what is occurring when you attempt to open the newer versions of chia?

**Comment by REIS77-COMMITS** [comment]
There is starting screen which reads loading keyring status etc., but it stays at that. For once I uploaded the latest version, started the GUI and went to work, when I got back from work in the evening screen was the same and I have checked my pooling status from space pool page it was not active. This problem is same in my PC for all the versions after 2.0.

**Comment by Tal1555** [comment]
I have the same Problem, still running on 1.8.1, this is the latest version which workes for me.
All other versions are stuck in "loading keyring status", i tried everything.
Running on a AMD CPU Ryzen 5 5600G with Radeon Graphics, do we have still a AMD Problem?

**Comment by wjblanke** [comment]
The AMD K10 issue should be fixed in the latest releases. However, 2.0.0 was the last version to support v1 databases. Can you make sure you are running the v2 DB? If not you'll need to resync or download the v2 torrent.

**Comment by Rempayusan** [comment]
same issue. Chia stuck at starting services after upgrading to V 2.2.1

**Comment by Rempayusan** [comment]
> The AMD K10 issue should be fixed in the latest releases. However, 2.0.0 was the last version to support v1 databases. Can you make sure you are running the v2 DB? If not you'll need to resync or download the v2 torrent.

please more instruction on how to resync

**Comment by Tal1555** [comment]
> The AMD K10 issue should be fixed in the latest releases. However, 2.0.0 was the last version to support v1 databases. Can you make sure you are running the v2 DB? If not you'll need to resync or download the v2 torrent.

Yes I`m on v2 DB, i also tried a clean install - deleted everithing also DB - same problem.
Maybe der is still a K10 AMD Problem with integrated radeon graphics unit in the CPU?

**Comment by wjblanke** [comment]
Can u attach the INFO debug.log. From that we can see why node isn't starting.
