### ISSUE TITLE
one plot that was farming just disappeared 

### ISSUE THREAD

**Issue by NYusmc81** [Chia-Network/chia-blockchain#1769]
had 3 plots farming and one plotting just came back to my comp and one of the plots is gone

**Comment by lvpcguru** [comment]
Please follow the [Contributing Guidelines](https://github.com/Chia-Network/chia-blockchain/blob/main/CONTRIBUTING.md) before posting what you believe to be actual bugs and issues. By default you are given a [bug report template](https://github.com/Chia-Network/chia-blockchain/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Please, try to stick to it, as it helps the developers replicate and solve your problem.

Anything else belongs in the [discussion](https://github.com/Chia-Network/chia-blockchain/discussions) section.

-----------------------------------------------------------------------------------------------------------------------------------
I know its is a really old posting so feel free to close the bug if you have resolved the issue already. 

As you didnt provide detail like OS, version and such its hard to help

However here is at least an attempt, check your plotting logs in your .chia\mainet\plotter directory for any errors or info related to the plot in question.
