### ISSUE TITLE
Version 2.2.1 does not start 

### ISSUE THREAD

**Issue by Karen530972** [Chia-Network/chia-blockchain#17719]
### What happened?

I worked on version 1.7.1, after updating to version 2.2.1 the plotter loads until the Full Node message and the loading process stops there, the loading indicator rotates and nothing happens, what should I do??? I installed the old version, everything works...

### Version

2.2.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by rdwarren13** [comment]
I have the same issues.

**Comment by Karen530972** [comment]
I installed sequentially from 1.7.1 to 2.1.0, the last working version is 2.0.0, any older version does not load, please correct the situation in the new release...

**Comment by Karen530972** [comment]
I already checked all this, downloaded the new database, unpacked it, renamed it as shown in the instructions, installed it in place of my old database - everything is the same...

**Comment by Karen530972** [comment]
All versions after the release of 2.0.0 are defective, please fix the BUG!!!

**Comment by Karen530972** [comment]
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
20.0 GB
Windows 10 Pro
22H2
These are the parameters of my computer, more than enough.

**Comment by wjblanke** [comment]
Check to make sure the config.yaml file is pointing to the new v2 DB. This does sound like a V1 DB problem if the last working version is 2.0

**Comment by Karen530972** [comment]
In fact, the following path was specified in the config file <db/blockchain_v2_CHALLENGE.sqlite>, I corrected it to <db/blockchain_v2_mainnet.sqlite> - They didn’t help at all, it’s still the same...

**Comment by wjblanke** [comment]
CHALLENGE should get replaced by the net, so that should be ok... 

Can you send us the INFO debug.log? Maybe we can see why the node stopped.

**Comment by Karen530972** [comment]
debug.log.1
<https://drive.google.com/file/d/1g6OZlXEkkAW0X8UQ2iK9JlPUWH5mKiUb/view?usp=drive_web>

ср, 27 мар. 2024 г. в 20:31, wjblanke ***@***.***>:

**Comment by wjblanke** [comment]
**This is very concerning. After this BrokenProcessPool error the node will not longer work.**

2024-01-19T12:05:20.005 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 1028, in _sync
  File "chia\full_node\weight_proof.py", line 640, in validate_weight_proof
  File "chia\full_node\weight_proof.py", line 1723, in validate_weight_proof_inner
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 1031, in _sync
ValueError: Weight proof validation threw an error A process in the process pool was terminated abruptly while the future was running or pending.

**also things like this are a bad sign**

2024-01-19T15:46:42.721 harvester chia.plotting.manager   : ERROR    Failed to open file P:\TRIPLE\plot-k32-2021-08-25-09-38-762045069ced7cdb337e7f111e178d1cc3312e3d6d90a809a59d7517bc94507b.plot. Invalid plot header magic Traceback (most recent call last):
  File "chia\plotting\manager.py", line 274, in process_file
ValueError: Invalid plot header magic

**Just to go from simplest first, try to fix all your plot issues. It seems like some are corrupt and that could be stealing resources from your machine. You can do this by running

chia plots check

and see what it returns. Maybe you have a bad drive you can remove from the system. We typically don't recommend network drives.

After that, if you still have issues, please set your logging level to INFO and send us more logs so we can try to fix the issue. It isn't clear what is causing one of the full node workers to crash.**
