### ISSUE TITLE
[Bug] Offers cause derivation bleed, until the wallet is dead

### ISSUE THREAD

**Issue by KryptomineCH** [Chia-Network/chia-blockchain#17721]
### What happened?
I have recently encountered multiple catastrophic wallet failures which almost led to lost cutomer funds of about 15 XCH.
The issue manifested itself at first because the wallet did not show the proper fund amounts or no funds at all.
[#15633](https://github.com/Chia-Network/chia-blockchain/issues/15633)
At that time, the issue was not so bad yet and increasing the derivation index seemed to fix the issue.

However, recently the issue got a lot worse. The wallet would have troubles synchronizing, not display funds and crash.
It was discovered, that the derivation index of the wallet was ~250k. a derivation index of a couple 10k gets critical. It was impossible to recover the funds without the help of the Chia Team which managed to create a spend bundle with my master public key, which I could sign offline in order to send to a full node.
That was roughly 1 Week ago. Yesterday, we had another catastrophic wallet failure, with the wallet derivation index beeing at 130k, after I cancelledsome offers on chain.

Multiple chia devs and I were debugging the issue. At first the suspect was that one of the Systems was compromised and someone withdrew all funds on it. Later on, we found by a lucky accident, that all wallet addresses are unused and the funds sit at a derivation index of 130k.  We were able to recover the wallet

### Root cause
I stopped all on chain offer cancellations yesterday. The derivation index was at 450.
Today I checked that wallet again. The derivation index was at 7500. No on-chain transactions were made.
There is a script on the wallet creating Time-Expiring offers. For testing purposes, I deleted the wallet database and resynced the wallet. The derivation index is back at 450.

Conclusion:
Creating offers increases the derivation index, even if they are expiring and never executed. Slowly that bloats the wallet, until catastropic failure.
Once an offer is then either cancelled or executed, the artificially high derivation index is beeing manifested on chain.
Perhaps this issue is also related to https://github.com/Chia-Network/chia-blockchain/issues/14714

### Version

2.2.1

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by KryptomineCH** [comment]
to mitigate the issue, I have created a service, that once per hour stops the wallet, deletes the wallet db and starts the wallet again. this  will help a lot already but the wallet will still bleed over time with each executed offer, so I will need to monitor, when its time to migrate to a new wallet

**Comment by wjblanke** [comment]
Are you running a trusted full node? Is the full node compiled from source or a package? What version of Python are you running, 3.11? These questions may seem silly but they change how the Chia code acts in conditionals. Please let us know. Also send the logs if you can, maybe we can see if there is a performance issue on the node/wallet? We have discussed extending limiting the incrementing of puzzle hashes to the creation of offers. Maybe you can offer a PR for that?

**Comment by KryptomineCH** [comment]
Trusted Full node:
- chia version: 2.2.1 (apt package)
- python version: 3.10.12

Wallet:
- chia version: 2.2.0 (apt package)
- python version: 3.10.12

**Comment by wjblanke** [comment]
Quex can u take a look at this

**Comment by wjblanke** [comment]
OK so reuse_puzhash applies here as well. This should work for your application i think.
