### ISSUE TITLE
[Bug] Check remote harvester compatibility

### ISSUE THREAD

**Issue by Fahrenheit2539** [Chia-Network/chia-blockchain#17724]
### What happened?

I was running a full 2.1.4 node with 3 remote harvesters on 2.0.0.

After upgrading to 2.2.1 all was looking good, harvesters connected, number of plots was correct. However next day I noticed that the 24-hour farm size dropped to ~50%. Reverting back to 2.1.4 on the full node helped to solve the problem, and farm size is back to normal.

Confirmed in discord that 2.2.1 indeed requires updating harvesters.

Ask is two-fold:
1. Introduce harvester protocol versioning so if unsupported version connects this will be clearly communicated to the user. Don't think in all cases harvesters need to be on the latest version - I was (and is) successfully running 2.0.0 with 2.1.4 full node.
2. Please clearly state in release notes minimum harvester version that'll work (or at least that update is required). I double-checked, could not find anything

### Version

2.2.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by felixbrucker** [comment]
To add to that: software version and protocol version are sent in the handshake, but not evaluated/validated in chia-blockchain

For compatibility we should not check the software version (arbitrary string) but the protocol version.

Note: protocol version is global right now, in the future we might have independent protocol versions for the different protocols

**Comment by wjblanke** [comment]
Arvid is working on separating out the versioning

https://github.com/Chia-Network/chia-blockchain/pull/17791

**Comment by wjblanke** [comment]
This is improved in main due to 17791
