### ISSUE TITLE
[BUG]Allow chia to restart automatically on win10

### ISSUE THREAD

**Issue by bananooo-zhang** [Chia-Network/chia-blockchain#1774]
When I allow the chia software to start P on Win10, it automatically restarts.
My CPU is 9900K + 64G RAM + 7T SSD + 8X8 HDD
I have farmed 20T before, but now I can't keep it running.
 I can enter after deleting all the residues, but restart after a few hours once I start plot. This is true even in the case of a single plot. And my PC doesn't restart if I don't run the chia program

**Comment by aqk** [comment]
Hello, I am sorry, I don't fully understand. Is the problem that the chia program stops running?

Please make sure to leave at least 1TB free empty space on your hard drive, in case you want to plot more, or another program needs some room.

**Comment by lvpcguru** [comment]
> 
> 
> When I allow the chia software to start P on Win10, it automatically restarts.
> My CPU is 9900K + 64G RAM + 7T SSD + 8X8 HDD
> I have farmed 20T before, but now I can't keep it running.
> I can enter after deleting all the residues, but restart after a few hours once I start plot. This is true even in the case of a single plot. And my PC doesn't restart if I don't run the chia program

Is this still an issue? Any progress on your troubleshooting and has it been resolved since the last several updates? 
Make sure to close this issue if it is resolved.
