### ISSUE TITLE
[Bug] CAT sent from Green Wallet not identified in chia reference wallet

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#17827]
### What happened?

Reported in discord: https://discord.com/channels/1034523881404370984/1034870571864948777/1225134086687817748

User surgeon sent three transactions of the GWT CAT. Two transactions (5 GWT and 100 GWT) were sent from the chia reference wallet while one (10 GWT) was sent from the Green wallet. 

The two transactions from the chia reference wallet are visible in the recipient chia reference wallet but the one transaction sent from the Green Wallet wallet is not visible in the chia reference wallet.

User has performed a full wallet resync by renaming the wallet db and ensured automatically_add_unknown_cats is set to true. 
User has confirmed that there are no errors or warnings related to syncing the coin state of the affected transaction (there were other errors related to other tokens).

The coin that is not visible in the users reference wallet:
coin_id - 0x16162bdd27a4d5ecbf1eeb4c77a1dd729503782520b7431ebdfb76f99a903f95
spacescan link - https://www.spacescan.io/en/coin/0x16162bdd27a4d5ecbf1eeb4c77a1dd729503782520b7431ebdfb76f99a903f95
wallet address (to which cat was sent) - xch1v0ulyylps0wzaj2358xxsmxw7hpec3ltueuvtnng39q92jvgjdts83tkec
current puzzle hash of coin (taken from full node coin record by name) - 0xdbb90809454a7a6d142c35e141de85363b231a0cf0296f74206d1364c985cfb1

NOTE - normally when facing something like this I would lean on potential issues with the sending wallet (green wallet) but I have confirmed that other CATs sent from the green wallet are properly identified in the chia client. In addition the CAT sent in this instance is properly identified in coin records

NOTE - user loaded the keyset on an Ubuntu machine and all of the GWT tokens were visible. User also performed a clean install and init of chia on their windows machine then relied on unknown peers to sync (to be in line with the ubuntu test). The user is still unable to see the GWT tokens sent from green wallet in the windows machine wallet.

NOTE - user has similar issues with other tokens sent from Green Wallet.

NOTE - Brandon confirmed that the coin which is not visible is not hinted. Also upon the user resyncing their ubuntu machine the coin is no longer visible there either. We might need to look at potential regressions for unhinted cats.

When checking the above puzzle hash via the full node rpc coin records all three transactions are properly identified:
```
chia rpc full_node get_coin_records_by_puzzle_hash '{"puzzle_hash": "0xdbb90809454a7a6d142c35e141de85363b231a0cf0296f74206d1364c985cfb1", "start_height": 5170000, "end_height": 5170100, "include_spent_coins": true}'
{
    "coin_records": [
        {
            "coin": {
                "amount": 5000,
                "parent_coin_info": "0xa68043acbaecca8188fbc0fc1868338362405b58ff9a4e4979c502c36aac806b",
                "puzzle_hash": "0xdbb90809454a7a6d142c35e141de85363b231a0cf0296f74206d1364c985cfb1"
            },
            "coinbase": false,
            "confirmed_block_index": 5170053,
            "spent": false,
            "spent_block_index": 0,
            "timestamp": 1712164615
        },
        {
            "coin": {
                "amount": 10000,
                "parent_coin_info": "0x4ea2e80872e38bae239adb669e1339ebe1311e4073342488c474c3a8a9a9bbe2",
                "puzzle_hash": "0xdbb90809454a7a6d142c35e141de85363b231a0cf0296f74206d1364c985cfb1"
            },
            "coinbase": false,
            "confirmed_block_index": 5170038,
            "spent": false,
            "spent_block_index": 0,
            "timestamp": 1712164285
        },
        {
            "coin": {
                "amount": 100000,
                "parent_coin_info": "0x693c8e0fe8b8e3c6d79cf261d03ba980b179ec64b9c3e078f002a55e94615730",
                "puzzle_hash": "0xdbb90809454a7a6d142c35e141de85363b231a0cf0296f74206d1364c985cfb1"
            },
            "coinbase": false,
            "confirmed_block_index": 5170013,
            "spent": false,
            "spent_block_index": 0,
            "timestamp": 1712163844
        }
    ],
    "success": true
}
```

### Version

2.2.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output
[debug(25).log](https://github.com/Chia-Network/chia-blockchain/files/14876949/debug.25.log)

_No response_

**Comment by surgus** [comment]
I need to correct the main post that this was not an isolated case, and other CATs sent from the Green Wallet are not identified properly too in the chia client.

**Comment by BrandtH22** [comment]
Bug is due to green wallet not hinting coins and the chia versions 2.x.x no longer check for unhinted coins. 
We have notified the green wallet team and requested they update their client to properly hint coins.
