### ISSUE TITLE
[Bug] tokens disappeared from the official wallet

### ISSUE THREAD

**Issue by KpunTomup** [Chia-Network/chia-blockchain#17840]
### What happened?

Previously, I bought a token on the exchange and transferred it to my wallet, saved the mnemonic phrase, after a while I went to Previously I bought a token on the exchange and transferred it to my wallet, saved the mnemonic phrase, after a while I went to my wallet, and it was empty. There are no more tokens right?

### Version

Version 1.6.0 | 64 bit

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
How can I access my tokens without downloading the entire blockchain worth hundreds of gigabytes? I'm not a miner.
```

**Comment by wjblanke** [comment]
1.6 is very old. There were some migration operations required for keys and DBs. To avoid all that, download the latest version, enter your mnemonic, and then run in wallet only mode. The lite wallet should be able to sync your token without running a full node.

**Comment by KpunTomup** [comment]
I started it, I also don't see any coins on the wallet empty. Although I did not withdraw coins from my wallet and did not give access to anyone either. 2.2.1 version the same result

**Comment by wjblanke** [comment]
Is this token a CAT? It may not be a registered CAT with the Chia desktop and you will have to add it manually in the GUI or set the desktop to find stray CATs. If a CAT and you still have a problem, when did you buy this CAT? Did u ever see this token in your wallet?
