### ISSUE TITLE
[BUG] why my all plot go to "Not found Plots" and cant farm

### ISSUE THREAD

**Issue by controlnow** [Chia-Network/chia-blockchain#1784]
when I reboot my computer
I found all my own plots go to "not found plots"
I cant use them to farm
I tried to reinstall the software, reboot the computer again, and recreate new wallet
all this are fail, I cant add my plot again
all of them go to Not found Plots
who can help me?
![image](https://user-images.githubusercontent.com/82243000/114247338-7119f400-99c7-11eb-9fde-f414fb5e0e7c.png)

**Comment by THe-SP00K** [comment]
Support questions are best handled in the Keybase forum - there are always community members online willing to help troubleshoot https://keybase.io/team/chia_network.public

**Comment by pkwenda** [comment]
I have the same  questions, I use NAS network mapping to windows or macOS

![image](https://user-images.githubusercontent.com/14212375/115135824-0f542c80-a04e-11eb-987f-ec124a1cc0a7.png)
