### ISSUE TITLE
[BUG][GUI Linux] "Help->About Chia Blockchain" shows version 0.0

### ISSUE THREAD

**Issue by THe-SP00K** [Chia-Network/chia-blockchain#1785]
![image](https://user-images.githubusercontent.com/82133929/114250512-476dc680-99e1-11eb-9c0d-c3c2b3b94a68.png)

**Comment by THe-SP00K** [comment]
Installed using "experimental GUI installer (x86_64) for Ubunu"

**Comment by hoffmang9** [comment]
Yeah - this and the icon is not working right for non obvious reasons. I'll leave this open until I can figure it out.

**Comment by easyang** [comment]
me too 
It is actually 1.1.2
<img width="1012" alt="截屏2021-04-26 18 55 54" src="https://user-images.githubusercontent.com/1302980/116071994-22f03a80-a6c1-11eb-849f-6b9b654358ec.png">

**Comment by nul800sebastiaan** [comment]
If anyone is good at debugging Electron, this would make for a nice PR, I personally have no idea where to start though. 

Looks like the code is here: https://github.com/Chia-Network/chia-blockchain-gui/blob/main/src/components/about/About.tsx

**Comment by jeus1609** [comment]
this is not a bug

**Comment by hoffmang9** [comment]
If you build the electron app yourself with `sh install-gui.sh` it will not have a version number. It is only the installer builds that will.

**Comment by hoffmang9** [comment]
Do the installers not have version information on Linux still?

**Comment by jeus1609** [comment]
![image](https://user-images.githubusercontent.com/9904738/125142843-58ac9900-e0de-11eb-8073-c3df36c79080.png)

**Comment by jorge-githuber** [comment]
The bug is still present on version 1.2.3.

**Comment by emlowe** [comment]
This is fixed going forward for the DEB and RPM packages
