### ISSUE TITLE
[Bug] Torrent database-checkpoint unable to load

### ISSUE THREAD

**Issue by bwccnft** [Chia-Network/chia-blockchain#17880]
### What happened?

Torrent database-checkpoint unable to load on uTorrent

https://www.chia.net/downloads/#database-checkpoint

### Version

2.2.1

### What platform are you using?

Windows / Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
What filesystem are you running? FAT32 has issues with large files for example.

**Comment by bwccnft** [comment]
NTFS on Windows and uTorrent is keep getting following message when loading the torrent file:
'Unable to load "mainnet.2024-04-01.tar.gz.torrent": unsupported piece size (64.0MB)!'

**Comment by bwccnft** [comment]
testnet11 is loading fine... just the mainnet torrent..

**Comment by wjblanke** [comment]
https://www.reddit.com/r/torrents/comments/kphoe1/torrent_client_that_supports_64mb_swarm_piece_size/?utm_source=embedv2&utm_medium=post_embed&utm_content=post_title&embed_host_url=https://forum.utorrent.com/index.php

Maybe try a different torrent client. We will work on changing the piece size of our torrent to something that is more supported. Sorry.

**Comment by wjblanke** [comment]
The torrents should now be updated with a smaller piece size. Thanks for the reports!
