### ISSUE TITLE
[Bug] with transaction

### ISSUE THREAD

**Issue by Dmytro899** [Chia-Network/chia-blockchain#17919]
### What happened?

Hello. Yesterday evening, I made a transaction to top up my wallet with 1.99 Chia. I checked the network and the wallet address - everything matches, but my Chia still hasn't arrived in my balance. Transaction hash (ID): 0xe54d882f4824770e95a0941f0b174fc2b518de6e7d9c68e9d54dee5cc3dc4153.

### Version

2.2.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Dmytro899 ,

It looks like the coin associated with that transaction id has already been spent:
https://alltheblocks.net/chia/coin/e54d882f4824770e95a0941f0b174fc2b518de6e7d9c68e9d54dee5cc3dc4153

Are you still having issues with this transaction?

**Comment by wjblanke** [comment]
If its spent it must have arrived so closing
