### ISSUE TITLE
[BUG]  After Client Start and processing Plots, additional plots do not show in GUI

### ISSUE THREAD

**Issue by DSRutherford** [Chia-Network/chia-blockchain#1794]
v1.03
Windows Server 2012 R2
Dell R720 / MD1200
256GB Mem
Dual 8Core Xeons
RAID Card
NVME drive on PCIe adapter card

Start GUI
Run three Plot sessions:
- Plot1: Two in parallel on nvme drive
- Plot2: Four in parallel on sas 10k RAID0
- Plot3: One in parallel on sas 15k RAID0

All plots show up in GUI and complete.
As plots complete (nvme first, then sas15k, then sas10k) -> Add/Start additional plots.

Some will show up but others wont.  The only way to resolve that I've found is letting all Plots finish.  Stop client.  Taskkill all Chia processes.  Restart client.  Repeat.

I dont recall this happening in the beginning.  Makes me consider its a system issue but dont know what that would be.

I am seeing way more services running than I would expect.  is this normal?

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
Chia.exe                      9856 Console                    1    144,256 K
Chia.exe                      2252 Console                    1     35,044 K
Chia.exe                      6236 Console                    1     17,648 K
Chia.exe                      9544 Console                    1    330,476 K
start_wallet.exe              2744 Console                    1    172,592 K
start_full_node.exe           2928 Console                    1    323,276 K
start_farmer.exe              7064 Console                    1     63,960 K
start_harvester.exe           8348 Console                    1     56,264 K
chia.exe                      3500 Console                    1  1,638,500 K
chia.exe                      7684 Console                    1     66,604 K
start_full_node.exe          11116 Console                    1     57,324 K
start_full_node.exe           8504 Console                    1     57,492 K
start_full_node.exe           3536 Console                    1     56,508 K
start_full_node.exe           6132 Console                    1     56,404 K
start_full_node.exe           3324 Console                    1     55,640 K
start_full_node.exe          11012 Console                    1     56,588 K
start_full_node.exe           8856 Console                    1     57,188 K
start_full_node.exe           4652 Console                    1     56,556 K
start_full_node.exe           6404 Console                    1     56,196 K
start_full_node.exe           5328 Console                    1     57,440 K
start_full_node.exe           1784 Console                    1     57,128 K
start_full_node.exe           8164 Console                    1     56,576 K
start_full_node.exe           7676 Console                    1     56,196 K
start_full_node.exe           3944 Console                    1     57,504 K
start_full_node.exe          11136 Console                    1     56,752 K
start_full_node.exe           4240 Console                    1     56,828 K
start_full_node.exe           6012 Console                    1     56,472 K
start_full_node.exe           5360 Console                    1     57,076 K
start_full_node.exe           8200 Console                    1     57,012 K
start_full_node.exe           4020 Console                    1     56,796 K
start_full_node.exe           9048 Console                    1     56,948 K
start_full_node.exe           4728 Console                    1     57,068 K
start_full_node.exe           6568 Console                    1     56,832 K
start_full_node.exe          10100 Console                    1     56,684 K
start_full_node.exe           1280 Console                    1     56,768 K
start_full_node.exe           6984 Console                    1     56,504 K
start_full_node.exe          10212 Console                    1     56,616 K
start_full_node.exe           8956 Console                    1     55,760 K
start_full_node.exe           2132 Console                    1     56,708 K
start_full_node.exe           4592 Console                    1     57,136 K
start_full_node.exe           5640 Console                    1     56,872 K
start_full_node.exe           7592 Console                    1     56,600 K
start_full_node.exe           7560 Console                    1     57,164 K
start_full_node.exe          10656 Console                    1     56,508 K
start_full_node.exe           4244 Console                    1     57,204 K
start_full_node.exe           8648 Console                    1     56,304 K
start_full_node.exe           2724 Console                    1     57,228 K
start_full_node.exe           9780 Console                    1     56,616 K
start_full_node.exe           4196 Console                    1     56,616 K
start_full_node.exe           6160 Console                    1     56,604 K
start_full_node.exe           4528 Console                    1     56,064 K
start_full_node.exe           7648 Console                    1     56,844 K
start_full_node.exe           6836 Console                    1     56,860 K
start_full_node.exe           1756 Console                    1     56,060 K
start_full_node.exe          10716 Console                    1     56,924 K
start_full_node.exe           4492 Console                    1     56,524 K
chia.exe                      6216 Console                    1  2,297,584 K
chia.exe                     10968 Console                    1  2,298,344 K

**Comment by aqk** [comment]
Hello, thank you for your clear bug report.

No, that does not sound like intended behaviour to me. The client UI does have a few update issues.

In this case, the UI waits for a certain log line to signal that the plots are done. This can take quite a while to finish, if you are hitting disk bandwidth limits.

One workaround is to click on the "keys" tab on the lower left, and back to what you wre doing. This forces most UI information to refresh.

Apologies - we are throwing most of our effort at the backend at the moment, and we have one lone hero doing all the front-end work. Thanks for your support.
