### ISSUE TITLE
[Bug] GUI Does not Load on Ubuntu 24.04 with Chia 2.3.0 from packaged installer

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#17956]
### What happened?

Reproduction steps: 
- clean install of ubuntu 24.04
- clean install of chia 2.3.0
- attempt to load the chia gui (no effect from clicking the gui icon, below image is from chiaminejp and uses the cli to run the GUI)

![paste (6)](https://github.com/Chia-Network/chia-blockchain/assets/48610606/a3c4f125-a73e-4d82-af39-14348ccce1d2)

Workaround, thank you chiaminjp!!:

run `sudo chmod 4755 /opt/chia/chrome-sandbox`
then launch the GUI

### Version

2.3.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Note, on ubuntu 24 there is no native GUI software for installing chia. 
Previous versions of ubuntu had the Software Installer application which could be used but ubuntu 24 replaces this with the app store which does not support the .deb files. 

When a user clicks on the downloaded file in firefox:
![click_in_firefox](https://github.com/Chia-Network/chia-blockchain/assets/48610606/1486dcab-b90f-48fb-ac01-77157afed6be)

When a user double clicks in the downloads directory:
![double_click_in_folder](https://github.com/Chia-Network/chia-blockchain/assets/48610606/4229230b-ce39-4384-97f6-6a616bcf6831)

Current workarounds-
GUI: install the gnome software package manager and use that to install the deb
CLI: use the apt package manager to install the deb `sudo apt install ./chia-blockchain_2.3.0_amd64.deb` NOTE - this is really not a workaround for the deb package as apt will actually install the apt package instead so one can just run `sudo apt install chia-blockchain` without ever downloading the deb and have the same result.

**Comment by BrandtH22** [comment]
Additional logs from a user who experienced this:

https://github.com/Chia-Network/chia-blockchain/assets/48610606/f709905a-d9bf-4065-b596-2e5bfd10b44c


[opt_chia_chia-blockchain.1000.crash.txt](https://github.com/Chia-Network/chia-blockchain/files/15192863/opt_chia_chia-blockchain.1000.crash.txt)

**Comment by emlowe** [comment]
Fixed in 2.4.0
