### ISSUE TITLE
Ubuntu 24 does not have native GUI software for installing chia.

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#17957]
Note, on ubuntu 24 there is no native GUI software for installing chia. 
Previous versions of ubuntu had the Software Installer application which could be used but ubuntu 24 replaces this with the app store which does not support the .deb files. 

When a user clicks on the downloaded file in firefox:
![click_in_firefox](https://github.com/Chia-Network/chia-blockchain/assets/48610606/1486dcab-b90f-48fb-ac01-77157afed6be)

When a user double clicks in the downloads directory:
![double_click_in_folder](https://github.com/Chia-Network/chia-blockchain/assets/48610606/4229230b-ce39-4384-97f6-6a616bcf6831)

Current workarounds-
GUI: install the gnome software package manager and use that to install the deb
CLI: use dpkg `sudo dpkg -i ./chia-blockchain_2.3.0_amd64.deb` or use the apt package manager to install the deb `sudo apt install ./chia-blockchain_2.3.0_amd64.deb` NOTE - this is really not a workaround for the deb package as apt will actually install the apt package instead so one can just run `sudo apt install chia-blockchain` without ever downloading the deb and have the same result.

_Originally posted by @BrandtH22 in https://github.com/Chia-Network/chia-blockchain/issues/17956#issuecomment-2091159501_

**Comment by QuintLeo** [comment]
apt is a front-end for dpkg. If you can use it, you already have dpkg.

Sadly, Ubuntu appears to have decided to move away from the Debian package manager dpkg to their SNAP setup instead with 24.04 - but you can still get the debian tools installed on Ubuntu and use them.
FOR NOW.
