### ISSUE TITLE
[Bug]  reuse_public_key_for_change not work when create new did

### ISSUE THREAD

**Issue by nqzhang** [Chia-Network/chia-blockchain#17997]
### What happened?

reuse_public_key_for_change not work when create now did profile.

### Version

2.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by nqzhang** [comment]
When playing with some NFT projects, we need a fixed address. But creating a new did profile will change the address

**Comment by wjblanke** [comment]
This should be fixed in main

**Comment by nqzhang** [comment]
Is this really solved? If I create a new did profile in 2.4.4, the payment address still change?

**Comment by nqzhang** [comment]
@wjblanke  @Quexington
