### ISSUE TITLE
Can I help you find the miner code?

### ISSUE THREAD

**Issue by lh232510** [Chia-Network/chia-blockchain#1803]
I want to do a mine pool, but find your miner source code, whether can provide, thank you very much!

**Comment by hoffmang9** [comment]
There are no miners here, only farmers. Pooling code will be available in late May or Early June.

**Comment by lh232510** [comment]
I want to know where the farmer verification code is？

**Comment by lh232510** [comment]
Is it this https://github.com/Chia-Network/chiapos ？

**Comment by hoffmang9** [comment]
That is the library that creates and verifies proofs of space.

**Comment by lh232510** [comment]
Is there a library for scanning disk space certificates?

**Comment by hoffmang9** [comment]
chiapos reads the plot files where the proofs of space are kept.

**Comment by lh232510** [comment]
thank you very much! I will study first.
