### ISSUE TITLE
[IDEA] Set logging level to INFO by default

### ISSUE THREAD

**Issue by flotti455** [Chia-Network/chia-blockchain#1804]
I think it makes sense to set the [default logging level from `"WARNING"`](https://github.com/Chia-Network/chia-blockchain/blob/660970f53f9f9dfe40db4d6d20e1a07e8544a8a8/chia/util/initial-config.yaml#L63) to `"INFO"`.

Relevant information for both Chia support and Chia health status ("is farming going on smoothly, did I just win a block?") is on INFO level, and the first step for any beginner to professional Chia user is changing the log level to INFO.

With daily log rotation/annihilation active by default, memory consumption for INFO logs also is no problem, with my experience being at most 500 MB of logging on INFO level per day.

**Comment by hoffmang9** [comment]
Most people do not want that and we can't support it. You have to think about how many new questions would arise from all of the benign information.

**Comment by flotti455** [comment]
Hm, I'd rather say the average user doesn't care about logs as long as everything works well. So there aren't any new questions arising from benign INFO information - no one would be looking at it.

But any user wants to peek at logs the moment something is not working (e.g. "height is stuck at x"), at which point it makes sense to look at logs - which right now don't give enough information when set on default WARNING.

**Comment by hoffmang9** [comment]
It does not work that way because regardless of whether people see that they are correctly farming, they nitpick the logs when they're having an unlucky streak. Now if you want to volunteer to answer those questions, we can add your contact information to the logs 😉.
