### ISSUE TITLE
[BUG] GUI on mac stuck on infinite loading loop

### ISSUE THREAD

**Issue by Xaerob** [Chia-Network/chia-blockchain#1805]
**Describe the bug**
I turn on the software, I can choose key, then go to the Full Node tab, and Full Node Status, Blocks and Connections all just have a never ending loading circle spinning.

**Expected behavior**
I expect the software to load and start syncing with the network.

**Desktop (please complete the following information):**

- OS: Mac OSX10.14.6
- CPU: 2.3GHz Intel i7

**Additional context**
I previously could not connect to wallet after upgrading to 10.0.3. And had to delete the mainnet folder as advised in other threads on how to get past it. However I haven't seen a solution on how to get it actually loading again once at this stage.
Please give step-by-step instructions on how to resolve. I bought some new hardware to get farming, but haven't been able to use it at all so money and time being wasted :(

I found this in the log: 
18:47:12.026 wallet src.wallet.wallet_state_manager: WARNING  Starting in db path: /Users/Robert/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_xxxxxxxx.sqlite

And it keeps repeating that warning.

**Comment by et477** [comment]
I have the same problem now on two MacBook Pros. The Full Node Page does show a never ending loading circle spinning.
One Laptop is running Chia 1.0.0 the other 1.0.3.
Any solution out there yet?

**Comment by seeden** [comment]
Can you open the developer console and check if there is any error?

**Comment by lifelongpatsy** [comment]
I am having same/similar problem on Macbook Air (OSx Big Sur 11.2.3), and see anything other than what you see in screenshot. Version 1.0.0 had been working for previous weeks since launch, until the macbook shutdown due to some error. Upon restarting, chia would not get past this initial screen's infinite loop (even after hours or looping). I deleted app, and reinstalled version 1.0.3, which did not change the problem. 
![image](https://user-images.githubusercontent.com/68787588/114603972-fe767600-9c5d-11eb-9c63-258c3628bc2f.png).   

Perhaps there are chia related files somewhere (preferences?) that I should delete to try a clean new install??

I'm not having problem w/ chia on my Macbook Pro w/ same OSX.

**Comment by hoffmang9** [comment]
Please follow these instructions and install 1.0.4 after you've deleted the dbs - https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-is-my-wallet-not-synced-why-can-i-not-connect-to-wallet-from-the-gui

**Comment by et477** [comment]
How do you open the developer console? 
The steps in the link above did not work for me. However I'll try again on my 2nd MacBook Pro with the same problem. 
For my main Mac I got it syncing now. It takes hours. Anyway, I’ve installed 1.0.4 and then renamed ~/.chia folder in case I need it again. Then started chia and it's syncing now. Had to add the plots again but it's working. Don't have much experience with this. Just trying to get this working again.

**Comment by Xaerob** [comment]
I have deleted the db folder, installed v1.04 over 1.03, and started with a new key, and have the same problem still.

**Comment by Xaerob** [comment]
Just an update. I have managed to solve this.
I had to delete everything related to Chia on the computer, not just the database. Then reinstall.
So I dragged the application into trash, and everything inside the ~chia folder too, then installed it again and it worked OK, although still remembered my keys somehow.
It's been syncing for the last 8 hours, and about 70% through the network now.
