### ISSUE TITLE
[Bug] XCH transfer issue

### ISSUE THREAD

**Issue by sekeli** [Chia-Network/chia-blockchain#18084]
### What happened?

Hello, I initiated an XCH delayed transfer on May 20th without setting up automatic confirmation. After the time, I did not manually confirm. The XCH sent so far has not arrived at the specified address and has not been returned to the original wallet. May I ask how to solve this problem?Looking forward to your reply. Thank you!
Is this a new version bug? The current status is that both the sender and receiver's wallets display confirmation in progress, there are no actionable buttons, and unconfirmed transactions cannot be deleted. How should I solve it?
Block ID:0xf44a7f3c3e6ac5975bc13e0bc1b632a693157dadaaa09403883c754effb0733d

### Version

2.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
This clawback related, please let us know if you have issues with the steps outlined to you in discord.

**Comment by BrandtH22** [comment]
This is confirmed as resolved in #18083
