### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nono71x** [Chia-Network/chia-blockchain#18087]
### What happened?

Chia 2.3.0 does not stop at the bottom of the task, the node continues to run, and farming continues too! Since I installed Qt on w11, it only closes the window without anything else. Forced to restart the PC every time

### Version

Chia 2.3.0 Qt 

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Do you have run services in the background checked? that will allow node/farmer/harvester to run in the background if the GUI is closed. See the checkbox below.

<img width="290" alt="Screenshot 2024-05-29 at 9 10 23 AM" src="https://github.com/Chia-Network/chia-blockchain/assets/1206691/2a545da8-7159-4eed-bf24-97969d213bbc">

**Comment by nono71x** [comment]
yes I hadn't seen the small box, I don't speak English and it's small so I hadn't seen it. sorry, thank you
