### ISSUE TITLE
[Bug] 更新2.3.1后卡在启动服务

### ISSUE THREAD

**Issue by Michael121318** [Chia-Network/chia-blockchain#18109]
### What happened?

在更新2.3.0和2.3.1后，启动程序一直卡在启动服务，但回滚2.2.1版本就可以正常登录。数据库版本已经是V2了。
![1](https://github.com/Chia-Network/chia-blockchain/assets/147701612/211a7493-8e7e-467f-8030-94a530d846ff)
[debug.log](https://github.com/user-attachments/files/15541887/debug.log)

### Version

2.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Michael121318** [comment]
debug.log是日志文件

**Comment by Michael121318** [comment]
> config.yaml

 config.yaml 中没有找到reserved_cores，是需要在最后添加吗？

**Comment by Michael121318** [comment]
> > > config.yaml
> > 
> > 
> > config.yaml 中没有找到reserved_cores，是需要在最后添加吗？
> 
> （谷歌翻译）在您的 config.yaml 中查找“full_node：”部分，然后向下滚动到找到“reserved_cores：0”的位置，并根据需要将其更改为使用少于 61 个处理器线程。 ![Screenshot (1784)](https://private-user-images.githubusercontent.com/36348012/336544272-aa9c7993-5299-45f9-ad86-3a7d91645319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDMyNzgsIm5iZiI6MTcxNzU0Mjk3OCwicGF0aCI6Ii8zNjM0ODAxMi8zMzY1NDQyNzItYWE5Yzc5OTMtNTI5OS00NWY5LWFkODYtM2E3ZDkxNjQ1MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDIzMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OWNjOTAwMzJlYjI1YWQ4MjIzMDVhMjVhNzJkMzNlNDA2MWIwZjZjOTE3ODkwMDg0NjYwZmEzYjRlZWMxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1UpHxp7xncK_JX5wlQhwcmBjbnc4D2auKb5GPscJmu4)
![image](https://github.com/Chia-Network/chia-blockchain/assets/147701612/2b470ed6-7c16-41c3-9f72-43b2f47bbf97)
为啥我的config.yaml和你的不一样呢

**Comment by wjblanke** [comment]
You can try the Chia 2.4.0 rc 1. Its not an official release yet but it is basically done. It has a fix for the core issue you are facing (it forces cores down to 61 just as the workaround above does if you can config.yaml configured correctly).
