### ISSUE TITLE
[Bug]  reuse_public_key_for_change not work when cancle offer

### ISSUE THREAD

**Issue by nqzhang** [Chia-Network/chia-blockchain#18142]
### What happened?

reuse_public_key_for_change not work when cancle offer.

### Version

2.3.0

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Quexington** [comment]
@nqzhang what types of assets are involved in the offer?  The offer cancellation does seem to pass this through, but it could be any wallet that is choosing not to listen to it at that point.

**Comment by nqzhang** [comment]
> @nqzhang what types of assets are involved in the offer? The offer cancellation does seem to pass this through, but it could be any wallet that is choosing not to listen to it at that point.

The assets are cat bepe and xch

![1](https://github.com/Chia-Network/chia-blockchain/assets/12559853/7318fe52-d350-4639-8e53-73b3b671d336)
![2](https://github.com/Chia-Network/chia-blockchain/assets/12559853/b89b777c-225f-4dcc-bd67-e871152a1122)
![3](https://github.com/Chia-Network/chia-blockchain/assets/12559853/617caaeb-08e4-4313-9dac-87a176e1bad8)
![4](https://github.com/Chia-Network/chia-blockchain/assets/12559853/eb3f96a7-7a25-42ab-a42a-d06735b36a33)

**Comment by wjblanke** [comment]
This should be in main if you want to try it. Main won't have a new release for a while unfortunately.

**Comment by wjblanke** [comment]
Closing as this is in main, please reopen if you continue to have issues
