### ISSUE TITLE
[BUG] Request wallet related RPC error report ！

### ISSUE THREAD

**Issue by Yangxin-GG** [Chia-Network/chia-blockchain#1816]
**Describe the bug**
Request wallet related RPC error report ：
02:12:46.935 wallet src.wallet.wallet_node     : WARNING  No keys present. Create keys with the UI, or with the 'chia keys' program.
02:14:09.762 wallet src.rpc.rpc_server         : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/chia-blockchain/src/rpc/rpc_server.py", line 81, in inner
    res_object = await f(request_data)
  File "/root/chia-blockchain/src/rpc/wallet_rpc_api.py", line 441, in get_next_address
    assert self.service.wallet_state_manager is not None
AssertionError

**To Reproduce**
All RPC requests related to the wallet are unavailable

**Screenshots**
![image](https://user-images.githubusercontent.com/30194654/114333201-58057480-9b7a-11eb-9431-0b699e3b82fb.png)

**Comment by hoffmang9** [comment]
The RPC assumes you have a key available to enumerate the HD keys. You will need to at least have a throw away key pair on the keychain.

**Comment by Yangxin-GG** [comment]
How should I create this keychain?

**Comment by hoffmang9** [comment]
`chia keys generate` - use `chia -h` and `chia keys -h` to see more.

**Comment by Yangxin-GG** [comment]
Thank you！
