### ISSUE TITLE
Farming Status: Not Available

### ISSUE THREAD

**Issue by jhatchison1** [Chia-Network/chia-blockchain#1818]
I am plotting from a number of different machines and they've all been slowly going to "Farming Status: Not Available". I'm fully updated to 1.0.3 on all devices. It happened on one PC about a week ago, then 2 more PC's just the other day. 

I saw something on another thread mentioning this but it seemed to be resolved by updating or reserved for Test environments. I shut down Chia and restarted. 

I have tried to uninstall and then reinstall. Restarted my PC. And, then I've even tried the waiting game. It hasn't worked for any of these. 

Here is the Screenshot: 
![image](https://user-images.githubusercontent.com/82353861/114335212-4d1af780-9b1a-11eb-8812-c1cc5bfc32b5.png)

Desktop: 
- Windows 10 Home
- AMD Ryzen 7 3700x

**Comment by hoffmang9** [comment]
Are you aware of this? https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-should-i-not-run-more-than-one-node-on-a-home-network-and-whats-this-about-upnp

**Comment by mariano54** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
