### ISSUE TITLE
Unable to detect plots in mounted volume on windows 11[Bug] 

### ISSUE THREAD

**Issue by jbdawinna** [Chia-Network/chia-blockchain#18184]
### What happened?

Previously this worked perfect. I have drives from another machine mounted as folders on my mining machine. However with the latest updates, it no longer recognizes the mounted drives. I new development is now it says: Path doesn't exist: Volume{it has letters here}. 

### Version

2.3.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by jbdawinna** [comment]
I just reinstalled chia version 2.0.1 and it works perfectly fine.

**Comment by jbdawinna** [comment]
but now it wont update the node

**Comment by emlowe** [comment]
Your system needs to have its blockchain database updated from v1 to v2.

NOTE - make sure to stop chia fully before making any changes to the needed files.

To verify if the blockchain db needs to be updated navigate to `~/.chia/mainnet/db/` and look at the `.sqlite file`, if it has `V1` in the filename then we need to update and you can proceed with the steps outlined here:
[docs.chia.net/faq/#how-do-i-upgrade-my-version-1-blockchain-database-to-version-2](https://docs.chia.net/faq/#how-do-i-upgrade-my-version-1-blockchain-database-to-version-2)

As a heads up we can generally provide more timely and thorough support in our discord server ([discord.gg/chia](https://discord.gg/chia))
