### ISSUE TITLE
[BUG] UBUNTU 20.04 dependency bitcoin package is no longer available as a Release

### ISSUE THREAD

**Issue by gotoco** [Chia-Network/chia-blockchain#1822]
**Describe the bug**
Looks like Dependency for Ubuntu 20.04 bitcoin is no longer available thus installation for 20.04 will fail (I tried older Ubuntu 18.04 and it worked fine).

**To Reproduce**
run sh install.sh

```
sh install.sh

Err:19 http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
see:
http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu/dists/

**Desktop (please complete the following information):**

UBUNTU Release:
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```
Archo: AMD64

**Comment by hoffmang9** [comment]
That is not our dependency but focal repositories have been wrong over the last few hours about a lot of things.
