### ISSUE TITLE
Showing incorrect balance when adding public key [Bug] 

### ISSUE THREAD

**Issue by jeherschberger** [Chia-Network/chia-blockchain#18234]
### What happened?

I added a public key to the new reference wallet 2.4.0, but the balance is similar to a wallet with private keys on the same computer. I added a public key from a 2 year wallet and a newly created wallet. Both showed the same wallet as the local wallet. I also obtained the same result in both the GUI and the CLI.

### Version

2.4.0

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Public keys only support unhardened addresses so if you have an older wallet that uses some hardened addresses those coins won't show up. You can resend your balance from a private key wallet to a new address (unhardened by default) and the balance should show up in all wallets, private or public. Let us know how it goes.

**Comment by jeherschberger** [comment]
OK, thanks! I was using ozone to make a new wallet and use that public key. The chia wallet reference wallet reflected the same balance on the wallet with public keys as the wallet with private keys. Later I added the public key of the ozone wallet to the chia reference wallet that had a new private key. Then I used an address derived from the wallet with the public key to send xch from my ozone wallet. The balance was correct after a successful transfer. Thanks!

**Comment by jeherschberger** [comment]
Actually, I thought the wallet updated properly when sending to a new address. However, the send address given when displaying the public key did not provide the correct receive address.

**Comment by wjblanke** [comment]
Can u send a screenshot. The GUI shows the current unused address. Wallets have many, many addresses for privacy reasons.

**Comment by jeherschberger** [comment]
The first image is of the wallet with the public key and the second image is of the wallet with the private key. Both wallets have the same balance and receive addresses.

![Screenshot from 2024-07-03 20-12-26](https://github.com/Chia-Network/chia-blockchain/assets/60515235/785830ee-4392-4894-89ca-6ee44436a41a)

![Screenshot from 2024-07-03 20-11-56](https://github.com/Chia-Network/chia-blockchain/assets/60515235/7bc6bc60-abd0-49e7-afd5-5c6572dd185f)

**Comment by wjblanke** [comment]
Everything looks good here. Are you having any issues anymore? Thanks

**Comment by sadiesue43** [comment]
I was having this issue on 2.4.1; just updated to 2.4.2, still there.

**Comment by jeherschberger** [comment]
I am also still having issues

**Comment by jeherschberger** [comment]
I downloaded the chia version 2.4.2 and it is the same issue. Now the private key and public key have different receive addresses. However, the balances in both wallets remain the same and the receive address provided by the observer wallet is signable by the private wallet.

**Comment by wjblanke** [comment]
The addresses can be different even though the key is the same (public versus private). It depends on how chia chooses which addresses are free given the state that the current machine knows about. But all those addresses should be usable by either machine given there are unhardened (observer) addresses. Since the balances are the same it seems like things are fine. Are you having issues using the addresses from either machine? They should all work. Thinking this is not a bug but will leave open for now for comments and thanks for your concern and report!

**Comment by jeherschberger** [comment]
No, the balances should not be the same because the public key is derived from a different private than the actual private key in the wallet.  Additionally, the receive address from the public (observer) wallet should not be signable by the wallet with the private key if it the observer wallet is derived from a different private key.

**Comment by sadiesue43** [comment]
+1. The UI is absolutely picking up the wrong key on the Select Key screen.

This is 4 separate mnemonics: Green is observable w/ private key, Red is non-observable(?) (very old) w/ private key, Blues are two observable mnemonics with only public key.

![image](https://github.com/user-attachments/assets/ed130438-0e11-4027-8031-60ccba0e7a0c)

Selecting any of them shows this (Green's wallet info):
![image](https://github.com/user-attachments/assets/51d96348-b2f0-4029-94fa-a6e9d7f6a958)
![image](https://github.com/user-attachments/assets/34d82237-91d9-4a8a-9bd3-104ea7d25bc7)

**Comment by sadiesue43** [comment]
Also, while "logged in" to Blue 2024, I was able to send Green Farmer's tokens.

**Comment by wjblanke** [comment]
OK we see now, so there is some kind of aliasing going on between different "keys" when you are using the observer feature for any of them. We will look into this. Thanks for the additional screenshots and determined responses.

**Comment by jeherschberger** [comment]
Thanks!

**Comment by Quexington** [comment]
Hey @jeherschberger or @sadiesue43 can you look in your logs for any errors?  I'm particularly suspecting `KeychainSecretsMissing`.

**Comment by Quexington** [comment]
I believe I have the fix please feel free to install from source and try it out.

**Comment by sadiesue43** [comment]
Awesome! I won't be able to test this until tomorrow, but will let you know.

**Comment by jeherschberger** [comment]
I just tried to install the chia wallet GUI from source and I got this error.

2024-07-25T20:20:28.876 wallet wallet_server  : WARNING  API not ready, ignore request: {'data': 'some long hexcode',
2024-07-25T20:20:28.998 daemon chia.daemon.keychain_server: ERROR

I replaced the actual hexcode with text for privacy reasons.

**Comment by jeherschberger** [comment]
I also deleted the wallet db and rename the .chia_keys folder. Then I added the public key of wallet 1 and it worked. However when I added the wallet 2 by private keys it gave this error.

wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 0eeededcc9c10924a8ebd07902aa4e5e8b69a1681c33c91d9284fcbbc45addf8, puzzle_hash: de7bf599a1b7e217b5ed301c8c8ceb8e255ea50a56aa542232672a42370799dc, amount: 1 }, spent_height: None, created_height: Some(5151458) }, error: 2

**Comment by jeherschberger** [comment]
Ok, it is working after I ran "chia stop -d all".

**Comment by sadiesue43** [comment]
I've tested this and it appears to be working now. Yay!

**Comment by wjblanke** [comment]
Great! Thanks for the information guys
