### ISSUE TITLE
[Bug] Information in Spacepool frozen

### ISSUE THREAD

**Issue by chia-mccolin** [Chia-Network/chia-blockchain#18272]
### What happened?

Hi,

My farm is working correctly with no visible problems on Gui, however the information provided on the spacepool website is frozen and does not update.
Harvester latency is under 1 second

![image](https://github.com/Chia-Network/chia-blockchain/assets/175011075/f0439a02-d2cd-449a-a848-eafe5ca49377)
![image](https://github.com/Chia-Network/chia-blockchain/assets/175011075/ffb955e8-55ac-4870-9275-f38ff8e9862b)
![image](https://github.com/Chia-Network/chia-blockchain/assets/175011075/92ccf318-cda0-47b6-b1df-5b3b452b770a)

### Version

2.4.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by wjblanke** [comment]
Please ask spacepool to look into their autorefresh. We don't control spacepools website. Thanks!
