### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PavelKapranov1990** [Chia-Network/chia-blockchain#18295]
### What happened?

Мои средства отправлены с OKX через блокчейн, но они не поступили мне на этой платформе. Вот детали транзакции:

Криптовалюта: XCH
Сумма к получению: 0,5523477 XCH
Комиссия: 0,0004 XCH
Сеть: Chia
Платформа вывода средств: OKX
Адрес: xch14eqgwyudc0t6vy55tyezf58pmna3jy77ry5alvkpvlequ0ceqe8qcuw5fk
TXID: 0x5268abc4b93dc200088f327dabf4fb660d1b1ced541c479cd9f8850f6680efe6

### Version

Bug

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Мои средства отправлены с OKX через блокчейн, но они не поступили мне на этой платформе. Вот детали транзакции:

Криптовалюта: XCH
Сумма к получению: 0,5523477 XCH
Комиссия: 0,0004 XCH
Сеть: Chia
Платформа вывода средств: OKX
Адрес: xch14eqgwyudc0t6vy55tyezf58pmna3jy77ry5alvkpvlequ0ceqe8qcuw5fk
TXID: 0x5268abc4b93dc200088f327dabf4fb660d1b1ced541c479cd9f8850f6680efe6
```

**Comment by wjblanke** [comment]
I see that the transaction went through to the address via this 3rd party explorer site

https://xchscan.com/address/xch14eqgwyudc0t6vy55tyezf58pmna3jy77ry5alvkpvlequ0ceqe8qcuw5fk

You probably just need to resync the wallet and it should appear.
