### ISSUE TITLE
[QUESTION] Where is the code that fetches credentials from MacOS keychain?

### ISSUE THREAD

**Issue by zoozoothisiszoo** [Chia-Network/chia-blockchain#1833]
I've been looking for some while now, any help would be appreciated! The line-number for the call itself would be a great bonus!

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/util/keychain.py#L24

Which is relying on https://github.com/jaraco/keyring

**Comment by zoozoothisiszoo** [comment]
Thank you so much!
