### ISSUE TITLE
[Bug] Offer accepted or processed after max_height passed.  

### ISSUE THREAD

**Issue by AbandonedLand** [Chia-Network/chia-blockchain#18380]
### What happened?

This may be expected behavior but I found it odd when it happened because it messed with some reporting scripts I have.

My offer file: https://dexie.space/offers/ECPL4jzmqccwBe2QdTgaQiUJEG9gYSU5WvWUJPBarkdG expired on block 5720447, but this block was not a transaction block.  The following transaction block (5720451) it was processed making it effectively accepted after the max_height.

![image](https://github.com/user-attachments/assets/fdcd5192-eecf-4eca-8f38-5dd0daede6bc)

### Version

2.4.2 

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
We look at the previous transaction block to determine if the height or timestamp passes. So this is as designed but agreed a bit uninituitive.

**Comment by wjblanke** [comment]
More information, we use the previous block so that the current farmer cannot play games with which transactions go into his block, all decisions are made from the previous transaction block (like the timestamp, etc).
