### ISSUE TITLE
Can the Chia blockchain database (db) directory .chia/mainnet/ for Windows version be moved to another hard drive?

### ISSUE THREAD

**Issue by RedChimae** [Chia-Network/chia-blockchain#18390]
As we all know, under the default installation method, the database of Chia blockchain is located in the directory C:\Users<YOURUSERNAME>/.chia/mainnet/db/. Due to the huge size of the database (db), storing it on the system partition will occupy a lot of disk space, which may even slow down the operation system until the disk is full and the computer crashes. Therefore, considering that the database (db) will gradually grow larger, is there a way to specifically transfer it to another hard drive, so that the main body of Chia blockchain can run separately from the database?

**Comment by BrandtH22** [comment]
Hey @RedChimae , I have answered this question in the other post you created here:
https://github.com/Chia-Network/chia-blockchain/discussions/18389

I am going to close this ticket as it is a duplicate and we can use the other to discuss further.
