### ISSUE TITLE
[Bug] Sending multiple transactions in a row can mess with shown balances

### ISSUE THREAD

**Issue by chia-rschmidt** [Chia-Network/chia-blockchain#18419]
### What happened?

When sending multiple transactions, the balances would add up to the total but more than the amount that was being sent would get removed from the Spendable Balance. In the test below, 0.1 TXCH was sent twice in a row causing the Spendable Balance to decrease by 1, with the rest going into the Pending Change.

![TC-papa](https://github.com/user-attachments/assets/dea90ffe-049e-48a6-a0b4-0a1a02892188)

### Version

2.4.3-rc1

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @chia-rschmidt , this is for the same reason as described in #18418 . Essentially this is an expected outcome of the coinset model. Let us know if any questions arise 👍
