### ISSUE TITLE
[BUG] Below are the current block challenges. You may or may not have a proof of space for these challenges. These blocks do not currently contain a proof of time.

### ISSUE THREAD

**Issue by zoharHao** [Chia-Network/chia-blockchain#1842]
Below are the current block challenges. You may or may not have a proof of space for these challenges. These blocks do not currently contain a proof of time.

<img width="1058" alt="WechatIMG162" src="https://user-images.githubusercontent.com/18652445/114537219-87080d00-9c84-11eb-92a3-1c421d6bf5c2.png">

**Comment by hoffmang9** [comment]
You have no plots farming so the application can not respond to the incoming challenges.
