### ISSUE TITLE
[Bug] - DIDs do not show up immediately in the GUI

### ISSUE THREAD

**Issue by syedsaif666** [Chia-Network/chia-blockchain#18432]
### What happened?
The DIDs did not show up immediately in the GUI. I had to delete and import the wallet again. Then logout and logged in again to see them. Note that the wallet was synced and still they didn't show up in settings -> PROFILES (DIDS).

### Failing Test Case:
#20 - For a wallet where you have multiple DIDs and NFTs, delete the wallet db, and resync it to ensure that your DIDs and NFTs show up.

### Steps to Reproduce:
Uninstall the Chia wallet
Delete the .chia folder
Reinstall the Chia wallet
Configure for testnet
Relaunch the wallet and wait for it to sync
Navigate to settings -> PROFILES (DIDS)

### Expected Results:
The wallet should display the DIDs

### Actual Results:
The wallet did not show the DIDs

Environment:
Chia Blockchain version: 2.4.3-rc1
Operating System: Microsoft Windows 11 Home
Network: Testnet11

### Attachments:
![image](https://github.com/user-attachments/assets/29e5e532-d5dd-46cd-b4ff-6bb87803659c)

### Version

2.4.3-rc1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @syedsaif666 , did you have any other wallets on the same machine when performing these steps?
I am wondering if this is related to https://github.com/Chia-Network/chia-blockchain/issues/18396 . Essentially if you have another wallet that has no transactions then this issue might already be resolved with https://github.com/Chia-Network/chia-blockchain/pull/18405

**Comment by syedsaif666** [comment]
> Hey @syedsaif666 , did you have any other wallets on the same machine when performing these steps? I am wondering if this is related to #18396 . Essentially if you have another wallet that has no transactions then this issue might already be resolved with #18405

Hey @BrandtH22 , I had a total for 3 other wallets on the machine but all of them had multiple transactions.

**Comment by BrandtH22** [comment]
Hey @syedsaif666 , is this issue reproducible in rc2? It has the fixes for the wallet sync issues that were in rc1 and those likely would have effected this sync as well

**Comment by BrandtH22** [comment]
Hey @syedsaif666 , I have attempted to reproduce in rc3 to no avail and believe this issue is now fixed. 

Can you attempt to reproduce in rc3 with INFO logs? If the issue persists please add that information tot his ticket, if it does not please close the ticket.

Thank you!
