### ISSUE TITLE
[Bug] Offers history didn't show up after complete reset

### ISSUE THREAD

**Issue by syedsaif666** [Chia-Network/chia-blockchain#18441]
### What happened?
I had a wallet with 2 items in offers history in rc1. Upon upgrading to rc2 I reset everything (fully delete all dbs and files, reinstall, re-sync etc).  Everything was in the state it should be in except the offers history which wasn't present

### Steps to Reproduce:
Uninstall the Chia wallet rc1
Delete the .chia folder
Reinstall the Chia wallet rc2
Configure for testnet
Relaunch the wallet and wait for it to sync
Navigate to Offers

### Expected Results:
The wallet should previous offers history

### Actual Results:
The wallet did not show the previous offers history

### Environment:
Chia Blockchain version: 2.4.3-rc2
Operating System: Microsoft Windows 11 Home
Network: Testnet11

### Version

2.4.3-rc1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @syedsaif666 , it is expected that offer file history is not synced upon deletion of the wallet db and resyncing. Currently there is no method of resyncing offer file history from the chain and therefore any full resyncs will yield no offer file history. 

I am closing this ticket as this is an expected occurrence of a full resync but let us know if any other questions arise.
