### ISSUE TITLE
[Bug] Balance is not displayed

### ISSUE THREAD

**Issue by Egorka54** [Chia-Network/chia-blockchain#18507]
### What happened?

I transferred chia tokens from the exchange, but they are not displayed in my wallet on my laptop.  According to the wallet number in chiascan, the balance is correct (2 chia), but in the wallet itself it is not (0 chia). 

### Version

2.4.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Wallet address: xch1jatzhhyej33k0q7djxzesrp9zun642ldme5wz5emsuegyp0ue36q82gh2r
```

**Comment by BrandtH22** [comment]
Hey @Egorka54  , as a heads up we can generally provide more timely, thorough support in our discord server (https://discord.gg/chia).

What I recommend trying is a resync of the wallet:

- If using the gui go to settings -> advanced -> resync . This will close the client and upon reopening it will resync.
- If using the cli then I would stop chia, rename the wallet db folder in ~.chia\mainnet\wallet\db then restart chia.

If the funds are still not visible can you let us know:

- if the wallet icon in the top right is orange or green?
- if orange can you click on the wallet icon and let us know if you see any connected peers?
- can you provide your log file from ~.chia\mainnet\log\debug.log?

**Comment by wjblanke** [comment]
Seems to be there so we just need the wallet to sync

https://xchscan.com/address/xch1jatzhhyej33k0q7djxzesrp9zun642ldme5wz5emsuegyp0ue36q82gh2r

**Comment by Egorka54** [comment]
> Привет, @Egorka54, предупреждаю, что в целом мы можем обеспечить более своевременную и всестороннюю поддержку на нашем сервере discord (https://discord.gg/chia).
> 
> Что я рекомендую попробовать, так это повторную синхронизацию кошелька:
> 
> * При использовании графического интерфейса перейдите в настройки -> дополнительно -> повторная синхронизация. Это закроет клиент, и при повторном открытии он будет повторно синхронизирован.
> * При использовании cli я бы остановил chia, переименовал папку wallet db в ~.chia\ mainnet \ wallet \ db, затем перезапустил chia.
> 
> Если средства по-прежнему не видны, можете ли вы сообщить нам:
> 
> * значок кошелька в правом верхнем углу оранжевый или зеленый?
> * если оранжевый, можете ли вы нажать на значок кошелька и сообщить нам, видите ли вы подключенных партнеров?
> * можете ли вы предоставить свой лог-файл из ~.chia \ mainnet \log \ debug.log?

The wallet in the upper right corner is orange, I tried to press Resync (5 times), it does not help

**Comment by Egorka54** [comment]
> Hey @Egorka54 , as a heads up we can generally provide more timely, thorough support in our discord server (https://discord.gg/chia).
> 
> What I recommend trying is a resync of the wallet:
> 
> * If using the gui go to settings -> advanced -> resync . This will close the client and upon reopening it will resync.
> * If using the cli then I would stop chia, rename the wallet db folder in ~.chia\mainnet\wallet\db then restart chia.
> 
> If the funds are still not visible can you let us know:
> 
> * if the wallet icon in the top right is orange or green?
> * if orange can you click on the wallet icon and let us know if you see any connected peers?
> * can you provide your log file from ~.chia\mainnet\log\debug.log?

The wallet in the upper right corner is orange, I tried to press Resync (5 times), it does not help

**Comment by krayneakkuraten** [comment]
> > Hey @Egorka54 , as a heads up we can generally provide more timely, thorough support in our discord server (https://discord.gg/chia).
> > What I recommend trying is a resync of the wallet:
> > 
> > * If using the gui go to settings -> advanced -> resync . This will close the client and upon reopening it will resync.
> > * If using the cli then I would stop chia, rename the wallet db folder in ~.chia\mainnet\wallet\db then restart chia.
> > 
> > If the funds are still not visible can you let us know:
> > 
> > * if the wallet icon in the top right is orange or green?
> > * if orange can you click on the wallet icon and let us know if you see any connected peers?
> > * can you provide your log file from ~.chia\mainnet\log\debug.log?
> 
> The wallet in the upper right corner is orange, I tried to press Resync (5 times), it does not help

Hi! Any luck with the XCH coin display?  I have the same problem.

**Comment by Egorka54** [comment]
> > > Hey @Egorka54 , as a heads up we can generally provide more timely, thorough support in our discord server (https://discord.gg/chia). What I recommend trying is a resync of the wallet:
> > > 
> > > * If using the gui go to settings -> advanced -> resync . This will close the client and upon reopening it will resync.
> > > * If using the cli then I would stop chia, rename the wallet db folder in ~.chia\mainnet\wallet\db then restart chia.
> > > 
> > > If the funds are still not visible can you let us know:
> > > 
> > > * if the wallet icon in the top right is orange or green?
> > > * if orange can you click on the wallet icon and let us know if you see any connected peers?
> > > * can you provide your log file from ~.chia\mainnet\log\debug.log?
> > 
> > 
> > The wallet in the upper right corner is orange, I tried to press Resync (5 times), it does not help
> 
> Hi! Any luck with the XCH coin display? I have the same problem. And I tried everything above, too.

No... If you find a solution to the problem, write to me

**Comment by krayneakkuraten** [comment]
> No... If you find a solution to the problem, write to me

My issue was solved by enabling VPN

**Comment by BrandtH22** [comment]
> > Hey @Egorka54 , as a heads up we can generally provide more timely, thorough support in our discord server (https://discord.gg/chia).
> > What I recommend trying is a resync of the wallet:
> > 
> > * If using the gui go to settings -> advanced -> resync . This will close the client and upon reopening it will resync.
> > * If using the cli then I would stop chia, rename the wallet db folder in ~.chia\mainnet\wallet\db then restart chia.
> > 
> > If the funds are still not visible can you let us know:
> > 
> > * if the wallet icon in the top right is orange or green?
> > * if orange can you click on the wallet icon and let us know if you see any connected peers?
> > * can you provide your log file from ~.chia\mainnet\log\debug.log?
> 
> The wallet in the upper right corner is orange, I tried to press Resync (5 times), it does not help

Hey @Egorka54 , orange means that the wallet is not synced. please proceed to the last two steps in the recommendations:
- if orange can you click on the wallet icon and let us know if you see any connected peers?
- can you provide your log file from `~.chia\mainnet\log\debug.log`?

**Comment by Egorka54** [comment]
> > Нет... Если вы найдете решение проблемы, напишите мне
> 
> Моя проблема была решена путем включения VPN

Bro, you're the best, it's earned

**Comment by Egorka54** [comment]
it worked with VPN
