### ISSUE TITLE
[Bug] Help Help 

### ISSUE THREAD

**Issue by Dave808654** [Chia-Network/chia-blockchain#18542]
### What happened?

Я зашел в приложения Chia кошелек ,монеты отображались , я решил обновить приложения и столкнулся с проблемой ,у меня перестало отображаться количество монет .Что мне делать в этом случаи ? 

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Dave808654 , as a heads up we can generally provide more timely, thorough support in our discord server (https://discord.gg/chia).

First make sure you are using the latest version of the chia wallet from here: https://www.chia.net/downloads/

What I recommend trying is a resync of the wallet:

- If using the gui go to settings -> advanced -> resync . This will close the client and upon reopening it will resync.
- If using the cli then I would stop chia, rename the wallet db folder in ~.chia\mainnet\wallet\db then restart chia.

If the funds are still not visible can you let us know:

- if the wallet icon in the top right is orange or green?
- if orange can you click on the wallet icon and let us know if you see any connected peers?
- can you provide your log file from ~.chia\mainnet\log\debug.log?

This information has been translated using translation software and might not be entirely accurate
---

Эта информация была переведена с помощью программного обеспечения для перевода и может быть не совсем точной

Привет, @Dave808654 , в качестве предупреждения мы, как правило, можем предоставить более своевременную и тщательную поддержку на нашем сервере Discord (https://discord.gg/chia).

Во-первых, убедитесь, что вы используете последнюю версию кошелька chia отсюда: https://www.chia.net/downloads/

Что я рекомендую попробовать, так это повторную синхронизацию кошелька:

- Если вы используете графический интерфейс, перейдите в настройки -> advanced -> повторите синхронизацию. Это закроет клиент, а при повторном открытии он снова синхронизируется.
- Если бы я использовал cli, то я бы остановил chia, переименовал папку wallet db в ~.chia\mainnet\wallet\db, а затем перезапустил chia.

Если средства по-прежнему не видны, можете ли вы сообщить нам об этом:

    Если значок кошелька в правом верхнем углу оранжевый или зеленый?
    Если оранжевый, вы можете нажать на значок кошелька и сообщить нам, если вы видите какие-либо подключенные пиры?
    Можете ли вы предоставить свой лог-файл из ~.chia\mainnet\log\debug.log?

**Comment by Dave808654** [comment]
Здравствуйте , не знаю что делать показывает оранжевый значок . 
![Безымянный](https://github.com/user-attachments/assets/522df9cf-f2c5-48c4-9a72-2e457364c4b9)

**Comment by Dave808654** [comment]
соединение с кошельком всегда меняются

**Comment by Dave808654** [comment]
Если вы используете графический интерфейс, перейдите в настройки -> advanced -> повторите синхронизацию. Это закроет клиент, а при повторном открытии он снова синхронизируется.   Не сработало 
Если бы я использовал cli, то я бы остановил chia, переименовал папку wallet db в ~.chia\mainnet\wallet\db, а затем перезапустил chia. не понимаю как сделать это

**Comment by Dave808654** [comment]
Спасибо большое , все получилось ! вы лучший

**Comment by BrandtH22** [comment]
Very glad to hear that the balance is visible and it all worked. Thank you for the confirmation!

I am going to close this ticket but do not hesitate to reopen if any questions arise.

---
Очень приятно слышать, что баланс виден и все это сработало. Спасибо за подтверждение! 

Я собираюсь закрыть этот тикет, но не стесняйтесь открывать снова, если возникнут какие-либо вопросы.
