### ISSUE TITLE
[Bug] Linux CLI plotting is way slower then GUI plotting

### ISSUE THREAD

**Issue by oe3gwu** [Chia-Network/chia-blockchain#18582]
### What happened?

I wrote a bash script where I start a plot of 24 or 48 threads. Using the GUI it usually completes in 80 minutes. Using the CLI the plot takes 4-6 hours (I can make tests if needed). As far as I know as stupid user, all the parameters are the same on CLI as are in the GUI. On the CLI I can saturate 2 threads, not more in Phase 1.

If needed I can provide my scripts.

### Version

2.4.3

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
none
```

**Comment by BrandtH22** [comment]
Hey @oe3gwu , can you provide the parameters being used for both the CLI and GUI plotting?

GUI
- What plotter?
- OG or PlotNFT?
- K value?
- Is the temp directory same as final directory?
- Is a RAM disk used for either?
- How many plots in parallel?
- Any advanced settings changed? (threads, buckets, cache size, etc)

For the cli also please provide the command being used but be sure to redact your farmer public key and the contract address or pool public key

**Comment by oe3gwu** [comment]
Hello!

Sorry for the delay. I today came home from hospital and I am sick. I update this call in 1 or 2 days. Sorry again!

**Comment by oe3gwu** [comment]
This was my script. I know I technically dont need so many threads, still I wanted to be as similar as the GUI defaults are.

```
#!/bin/bash

# Define the number of plots to start
PLOTS_COUNT=1

# Define the number of threads to use per plot
THREADS_PER_PLOT=24

# Define directories for plotting and farming
PLOT_DIR="/mnt/void"
FARM_DIR="/mnt/farm01"

# Define the pool information
# Replace <POOL_CONTRACT_ADDRESS> with your actual pool contract address.
# You can get this from your pool operator or from the Chia wallet if you're using self-pooling.
FARMER_PUBLIC_KEY="<redacted>"
POOL_CONTRACT_ADDRESS="<redacted>"

# Function to start a Chia plot
start_plot() {
    local plot_num=$1
    echo "Starting plot $plot_num..."

chia plots create -k 32 \
    -b 3389 \
    -u 128 \
    -r $THREADS_PER_PLOT \
    -n 1 \
    -t $PLOT_DIR \
    -d $FARM_DIR \
    -c $POOL_CONTRACT_ADDRESS \
    -f $FARMER_PUBLIC_KEY &

    echo "Plot $plot_num started."
}

# Start the plots
for i in $(seq 1 $PLOTS_COUNT); do
    start_plot $i
done

# Wait for all plots to finish
wait

echo "All plots have been started."

```

I tried also with bigger cache. It usually takes me approx 80min for a GUI Plot. Using this script it takes 6 - 8 hours.

/mnt/void is a tmpfs ramdisk that is 2tb in size. /mnt/farm01 is a sata hdd with 18tb.

Regarding parallel plotting, this is something I wanna do when this script works fine. But I want to have the same performance as in the GUi. For the GUI plot, I dont have any special options I set. Just the 2 directories, and I makr /mnt/void as RAMDisk. Nothing else.

Thank you!

**Comment by wjblanke** [comment]
chia plots create will use the chiapos original plotter

chia plotters uses the newer high speed plotter both mad max and bladebit. 

I think the issue is the GUI is using a high speed plotter but on the command line you are using chiapos. That would make perfect sense given the speed differences. Let us know! Sorry you have been sick btw!

**Comment by oe3gwu** [comment]
I will try tomorrow. Thanks!

I honestly I thought that the default CLI plotter is the default GUI plotter too. I didnt know that it falls back to `chia plotters chiapos`.

**Comment by oe3gwu** [comment]
It works better now. Still not as fast, but  I guess it is a config thing.
