### ISSUE TITLE
[BUG] Wallet Not synced

### ISSUE THREAD

**Issue by serwiseu** [Chia-Network/chia-blockchain#1859]
Hello.
My wallet is not synced. I've got Full Node Status - Synces, Farming Status - Farming (green) but my wallet is not synced
I've try restart , run again, and always wallet is not synced. 

My balace there is alyays 0 XCH - Expected Time to Win 8 days - but nothing change

Windows 10
Chia Blockchain GUI Version 1.0.3 

![image](https://user-images.githubusercontent.com/52281807/114603449-06530c00-9c98-11eb-8432-9d850b8cad24.png)

![image](https://user-images.githubusercontent.com/52281807/114603522-1ec32680-9c98-11eb-9246-fadf58c84958.png)

**Comment by hoffmang9** [comment]
Upgrade to 1.0.4 and re-open if that doesn't fix it.

**Comment by serwiseu** [comment]
after upgrade there is Syncing status :) Shoul be synced or Syncing? 

I farmed about more than 7 TB and have 0 XCH. Is it normal? What is a reaosn of 0 ? Have I got too low Farming Plot? Or this is a problem with syncing

**Comment by Guzxor** [comment]
I updatet to new version 1.0.4, and i have sumulator situation.


status od change from syncing to not sync over and over again
Height 14420 and growing
Connections 0

**Comment by serwiseu** [comment]
I've updated to 1.0.4 and I had Syncing about 1h, and now there is  No Sync again. 
Farming is Sync, but wallet no. 

![image](https://user-images.githubusercontent.com/52281807/114625233-38716780-9cb2-11eb-8db5-747863c381f9.png)
