### ISSUE TITLE
[Bug] FREEBSD 13.2 jail - chef installation fails on chia-rs 0.10.0 

### ISSUE THREAD

**Issue by ChristopherP1221** [Chia-Network/chia-blockchain#18619]
### What happened?

Running install.sh for latest chia-blockchain version results in a "ChefBuildError" for the chia-rs package in a FREEBSD 13.2 jail. I am running within a python 3.11 venv. I've removed older versions of python within the jail. The error I receive is below. I can git clone the repo and manually build and pip install the chia-rs 0.10.0 wheel. Unfortunately, it seems poetry doesn't like that and tries to change my installed 0.10.0 to its own 0.10.0 fails with this error. I'm out of ideas and looking for some help on things to try!

` (10.5.0)
Installing dependencies from lock file

Package operations: 36 installs, 0 updates, 0 removals

  - Installing chia-rs (0.10.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  Running `maturin pep517 build-wheel -i /tmp/tmpuul6cq92/.venv/bin/python`
  💥 maturin failed
    Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
    Caused by: `cargo metadata` exited with an error: error: failed to parse manifest at `/tmp/tmpttofeuxg/chia_rs-0.10.0/Cargo.toml`

  Caused by:
    no targets specified in the manifest
    either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/tmp/tmpuul6cq92/.venv/bin/python'] returned non-zero exit status 1

  at .penv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with chia-rs (0.10.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "chia-rs (==0.10.0)"'.

`

### Version

2.4.3

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
(10.5.0)
Installing dependencies from lock file

Package operations: 36 installs, 0 updates, 0 removals

  - Installing chia-rs (0.10.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  Running `maturin pep517 build-wheel -i /tmp/tmpuul6cq92/.venv/bin/python`
  💥 maturin failed
    Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
    Caused by: `cargo metadata` exited with an error: error: failed to parse manifest at `/tmp/tmpttofeuxg/chia_rs-0.10.0/Cargo.toml`

  Caused by:
    no targets specified in the manifest
    either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/tmp/tmpuul6cq92/.venv/bin/python'] returned non-zero exit status 1


  at .penv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with chia-rs (0.10.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "chia-rs (==0.10.0)"'.
```

**Comment by wjblanke** [comment]
We're trying to work around some maturin issues with the tar

**Comment by ChristopherP1221** [comment]
Is there anyway for me to make the petry subsystem recognize my mamual installation of version 0.10.0 as a valid one and prevent it from attempting to install over it? I think I could get back up and running,, if so. I'm also happy to be patient and wait for a fix!

**Comment by wjblanke** [comment]
We are working on a source distro for all other platforms. Earle can give u some pointers to work around poetry and good a successful install right now.

**Comment by emlowe** [comment]
`chia_rs` specifically should build from the wheel sdist correctly from version 0.15.0
