### ISSUE TITLE
[Bug] 已幾個月無法進入耕作

### ISSUE THREAD

**Issue by Cinkey588** [Chia-Network/chia-blockchain#18618]
### What happened?

至從礦池突然自行斷線後顯示須更新chia版本，更新後就開始不順，也無法連接礦池，後來就取消礦池自行耕作，chia耕作時會自行斷線，需從新開啟，後來有一次一樣狀況，從新開啟時就卡在(Full Node)畫面進不去了!!版本2.4.3
現在重點是一直卡在(Full Node)畫面轉圈圈進不去，完全無法進入鑰匙畫面

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @Cinkey588  ,

As a heads up we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia).

As for the issue can you please provide your log file from `~/.chia/mainnet/log/debug.log` ?

This has been translated using translation software and may contain errors.

---
作為提醒，我們通常可以在 Discord 伺服器 （https://discord.gg/chia） 中提供更及時和全面的支援。 
至於問題，您能否提供 `~/.chia/mainnet/log/debug.log` 中的日誌檔？ 這是使用翻譯軟體翻譯的，可能包含錯誤。

**Comment by wjblanke** [comment]
Please open a new issue if you are still having problems
