### ISSUE TITLE
[Bug] when I open the chia.exe 2.4.3 still load at the full_node,always load

### ISSUE THREAD

**Issue by peterxu1980** [Chia-Network/chia-blockchain#18620]
### What happened?

[Bug] when I open the chia.exe 2.4.3 still load at the full_node,always load

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by peterxu1980** [comment]
[debug.log](https://github.com/user-attachments/files/17103300/debug.log)

**Comment by BrandtH22** [comment]
Hey @peterxu1980 , the log error `BlockStore does not support database schema v1` indicates that your blockchain db is of version 1 and version 2 is now required. 

Database upgrade steps either via cli or torrent snapshot download:

Steps for the CLI command (requires at least 250GB of free space on the drive):
1. Stop the chia client (this can be done while chia is running but stopping the client saves from any potential issues)
2. Run the command `chia db upgrade` (you do not need the input or output paths if these are still default)
- This process will take some time and requires additional space as the v1 db is compacted into the v2 db which leaves the v1 db intact
3. Verify the config file (`~\.chia\mainnet\config\config.yaml`) has the correct value under the full_node section for `database_path: db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
4. After the above completes start the chia client
5. If all loads up properly (might take upwards of 30 minutes to load) then you can safely delete the v1 db found here (`~\.chia\mainnet\db\blockchain_v1_mainnet.sqlite`)


Steps for using the torrent: 
1. Download the torrent file from https://www.chia.net/downloads/#database-checkpoint
2. Use a torrent client to download the full db
3. Unpack/reassemble the torrent file that was downloaded (on windows I used 7zip, Mac and linux have built in tools that work for this)
4. Move the db to the correct folder (`~\.chia\mainnet\db\`) and update the name to "blockchain_v2_mainnet.sqlite" (removing the date information in the name)
5. Verify the config file (`~\.chia\mainnet\config\config.yaml`) has the correct value under the full_node section for `database_path: db/blockchain_v2_CHALLENGE.sqlite` (should only need to change the v1 to v2)
6. Launch chia and wait for a bit (the height to hash and peers files need to be built so this can take upwards of 30 minutes)

**Comment by peterxu1980** [comment]
i try do it

**Comment by BrandtH22** [comment]
Hey @peterxu1980 , did upgrading the database to version 2 resolve the issues?
