### ISSUE TITLE
Stuck on login screen

### ISSUE THREAD

**Issue by apdredds** [Chia-Network/chia-blockchain#18638]
### What happened?

Hi, when entering my password I am stuck on the loading screen. I am using 2.4.3 version. Can you help please?

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by BrandtH22** [comment]
Hey @apdredds ,

As a heads up we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia).

As for the issue can you please provide your log file from `~/.chia/mainnet/log/debug.log` ?

**Comment by wjblanke** [comment]
Did you just upgrade from an older version? normally this happens because people are running a deprecated version of the DB. In any case, as Brandt asked we need some logs and more background information. Thanks

**Comment by BrandtH22** [comment]
Hey @apdredds , are you still having the issues?

**Comment by apdredds** [comment]
Hi yes sorry

Sorry I'm not great with computers. I'll ask my son to get to provide the log file for me. Thanks for the reminder.

I will get back to you soon.

Kind regards

Asiyah

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wallentx** [comment]
I bet I know why, I'm making an issue right now

**Comment by BrandtH22** [comment]
Hey @apdredds , were you able to get those log files or is chia working as intended now?

**Comment by apdredds** [comment]
Hi

Sorry for the delay. I need to ask my son to do this for me as I have no idea how to. It's been manic. I will try and send over this week.

Kind regards

Asiyah

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
