### ISSUE TITLE
[BUG] Wrong environment for the GUI launch

### ISSUE THREAD

**Issue by gandroz** [Chia-Network/chia-blockchain#1863]
**Describe the bug**

I got an issue with the GUI on Ubuntu and Windows. At startup, it complains in the `api_call` on the `server.py`. What is surprising, is that the `asyncio` package used is not the one in the venv but the one of the python base environment.

**Screenshots**

![image](https://user-images.githubusercontent.com/38106881/114611710-536eb800-9c6f-11eb-809d-f642644048f8.png)

**Comment by mariano54** [comment]
Did you activate? `. ./activate`

**Comment by gandroz** [comment]
@mariano54 why have you closed the issue ?
Because yes, I activated the virtual environment. And as you can see, the server.py module is in the right environment but it calls the asyncio from the wrong one. At said, the issue occurs either on Ubuntu and on Windows (installed with the GUI installer)
