### ISSUE TITLE
[Bug] chia wallet coins combine/split fee problem for CATs

### ISSUE THREAD

**Issue by DrakoPensulo** [Chia-Network/chia-blockchain#18648]
### What happened?

It seems that there is a problem with the --fee parameter when one wants to combine/split CAT coins. Please see the output below. The XCH wallet contained much more xch than the proposed fee. 

chia wallet coins combine -i 8 -n 10 --fee 0.00000000001
Combining 10 coins.
Would you like to Continue? (y/n): y
RPC response failure: {"error": "Transaction for 10 is greater than max spendable balance in a block of 0. There may be other transactions pending or our minimum coin amount is too high.", "success": false}
Traceback:
Traceback (most recent call last):
  File "/home/pi/chia-blockchain/chia/rpc/util.py", line 69, in inner
    res_object = await f(request_data)
  File "/home/pi/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1197, in send_transaction_multi
    response = await self.cat_spend(request, hold_lock=False)
  File "/home/pi/chia-blockchain/chia/rpc/util.py", line 140, in rpc_endpoint
    response: Dict[str, Any] = await func(
  File "/home/pi/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 1774, in cat_spend
    txs = await wallet.generate_signed_transaction(
  File "/home/pi/chia-blockchain/chia/wallet/cat_wallet/cat_wallet.py", line 782, in generate_signed_transaction
    spend_bundle, chia_tx = await self.generate_unsigned_spendbundle(
  File "/home/pi/chia-blockchain/chia/wallet/cat_wallet/cat_wallet.py", line 693, in generate_unsigned_spendbundle
    chia_tx, _ = await self.create_tandem_xch_tx(
  File "/home/pi/chia-blockchain/chia/wallet/cat_wallet/cat_wallet.py", line 569, in create_tandem_xch_tx
    chia_coins = await self.standard_wallet.select_coins(
  File "/home/pi/chia-blockchain/chia/wallet/wallet.py", line 245, in select_coins
    coins = await select_coins(
  File "/home/pi/chia-blockchain/chia/wallet/coin_selection.py", line 57, in select_coins
    raise ValueError(
ValueError: Transaction for 10 is greater than max spendable balance in a block of 0. There may be other transactions pending or our minimum coin amount is too high.

chia wallet coins combine -i 8 -n 10
Combining 10 coins.
Would you like to Continue? (y/n): y
Transaction sent: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
To get status, use command: chia wallet get_transaction -f xxxxxxxxxx -tx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### Version

2.4.2

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

**Comment by BrandtH22** [comment]
Hey @DrakoPensulo the latest RC for 2.4.4 refactors the coin split logic. 
Can you check to see if this version resolves the issue you identified above?

https://github.com/Chia-Network/chia-blockchain/releases/tag/2.4.4-rc1

**Comment by BrandtH22** [comment]
Note it seems we have two different issues regarding the coin split logic that are being reviewed. This one and #18664

**Comment by DrakoPensulo** [comment]
No, it is not fixed. Essentially the same error appears. It seems there is a problem with the correct interpretation of --fee decimal parameter. Instead of being interpreted as 10 mojos of xch it is interpreted as 10 xch or as 10 CATs?

**Comment by BrandtH22** [comment]
Hey @DrakoPensulo thank you for testing and we have been able to reproduce the error on our side. 

The team is looking more into the issue and hopes to have a fix in place for the next RC 👍

**Comment by BrandtH22** [comment]
This should be fixed in https://github.com/Chia-Network/chia-blockchain/pull/18679

**Comment by BrandtH22** [comment]
Hey @DrakoPensulo this appears to be resolved in the latest RC, can you confirm on your side? (I am no longer able to reproduce with the latest RC)
