### ISSUE TITLE
[BUG] No rewards although plot passed filter

### ISSUE THREAD

**Issue by gandroz** [Chia-Network/chia-blockchain#1865]
I got few (14) plots and I saw some plots passing the filter in the farm tab. However, it does not seem to update the wallet. Do those plots win some challenge ? Do they get some reward ? Is that a wallet sync issue (although it is said synced) ?

![image](https://user-images.githubusercontent.com/38106881/114616652-1dcccd80-9c75-11eb-8a4d-5518d8516006.png)

**Comment by maketigers** [comment]
same question ,what does it mean?

**Comment by dorkmo** [comment]
passing the filter is the first step to trying to win an award, its a way of quickly deciding which plots to actually check for a win. if you win a block it will show a 1 under proofs found
