### ISSUE TITLE
[Improvement][PLOT] Faster plot time in phase 4 in the same drive if move is used instead of copy.

### ISSUE THREAD

**Issue by Handri-Kosada** [Chia-Network/chia-blockchain#1868]
It will be much faster if it move the file and rename it instead of copy and rename in phase 4?
Move will be done in few second only if the dst folder is in the same drive / disk.

However, if the temp and dst drive are diff, the it will perform the same time as copy.

```
Copied final file from "/mnt/md0/temp/plot-k32-2021-04-14-00-06-xxxxxxxxxaaa3078f52afe44d363b236e329e103aac57b2f1550bd5a.plot.2.tmp" to "/mnt/md0/plots/plot-k32-2021-04-14-00-06-xxxxxxxxxxaaa3078f52afe44d363b236e329e103aac57b2f1550bd5a.plot.2.tmp"
Copy time = 125.908 seconds. CPU (57.090%) Wed Apr 14 04:48:08 2021

```

**Comment by hoffmang9** [comment]
This is much harder than you'd imagine when supporting it across ~6 platforms. To get the same result set your `-2` directory to the `-d` directory and it will be a rename.
