### ISSUE TITLE
[Bug] chia explorer show 49xch, but my farm wallet show 2xch

### ISSUE THREAD

**Issue by Thanatos-JFJ** [Chia-Network/chia-blockchain#18688]
### What happened?

![chia explorer](https://github.com/user-attachments/assets/65154ddd-ae0a-4bd3-9396-b9d17b79171b)

![farm wallet](https://github.com/user-attachments/assets/de8b4e74-de6d-4108-a06e-ce1229f125c8)

chia explorer：https://xch.dwd.com/

### Version

2.1.4.dev0

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Please open a. new issue if you continue to have problems. thanks!
