### ISSUE TITLE
[Bug] Transfer funds to another wallet.

### ISSUE THREAD

**Issue by KIMB0212** [Chia-Network/chia-blockchain#18696]
### What happened?

I can't transfer wallet funds to another wallet.
The transaction remains pending and does not complete.
Do you have a solution?
How long does it take, days......
I also cleared the cache.
Thanks to anyone who can help me.

### Version

2.4.3

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Julietnacy** [comment]
@KIMB0212 If your transaction remains pending and doesn't complete Sometimes, network congestion can cause delays. sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WAL07638
Please see the link below to our dedicated support line:
[Wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by BrandtH22** [comment]
@KIMB0212 , the other commenter is a spammer. Please do not follow the link they provided and if you did please remove yourself from any websites or platforms they suggested using.

As for the transaction issues:
- is the wallet fully synced?
- are you running a local full node? If so, is that full node full synced?
(sync status can be determined by looking at the full node or wallet icons in the top right, if green hat indicates synced)

- can you provide your log file from `~/.chia/mainnet/log/debug.log`?

**Comment by wjblanke** [comment]
Please open a new issue if u continue to have problems. thanks!
