### ISSUE TITLE
[BUG]1.0.4 version, the SSD hard disk occupied by the K33 model is more

### ISSUE THREAD

**Issue by Thiece** [Chia-Network/chia-blockchain#1872]
![212FDA92-80D9-43F6-82CA-6DC29E72202A.png](https://i.loli.net/2021/04/14/yw8vlEpCUxfBTna.jpg)

![6C524BCB-E795-4A88-A8A2-0DC61A0B547B.png](https://i.loli.net/2021/04/14/nleBwCOYg3qz6fp.jpg)

![56CAF196-418D-4653-BB66-84DFBEA2C857.png](https://i.loli.net/2021/04/14/sOM7BFTcer18jig.jpg)

Windows10，SSD 512G，Four Plots，32G Ram

**Comment by hoffmang9** [comment]
Each k33 requires 462 GB (GiB is smaller) while plotting so you do not have enough space. You should plot k32's instead.

**Comment by Thiece** [comment]
> Each k33 requires 462 GB (GiB is smaller) while plotting so you do not have enough space. You should plot k32's instead.

@hoffmang9 Yes, I understand, but the capacity of each of my SSDs exceeds 462G, and only one Polt task runs on one SSD; the four Polt mentioned above and two SSDs do not appear in the screenshot.

**Comment by hoffmang9** [comment]
Did you disable bitfield plotting? Non bitfield plotting still requires a lot more space.

**Comment by Thiece** [comment]
> Did you disable bitfield plotting? Non bitfield plotting still requires a lot more space.

@hoffmang9 I can confirm that the disable bitfield checkbox is unchecked

**Comment by dorkmo** [comment]
does k32 work?

**Comment by Thiece** [comment]
> does k32 work?

@dorkmo K32 is ok

**Comment by dorkmo** [comment]
you might try to make a raid 0 with the two drives?

**Comment by Thiece** [comment]
> you might try to make a raid 0 with the two drives?

@dorkmo Well, that's one option; but I'm just describing the inconsistency between what the new version of K33 describes and how it actually works
