### ISSUE TITLE
[Bug] Testnet port 58444 is in the ephemeral port range

### ISSUE THREAD

**Issue by madMAx43v3r** [Chia-Network/chia-blockchain#18731]
### What happened?

I tried to run testnet11 node again, but it failed because port 58444 was already used by another application as an outgoing port.

Which is no surprise because 58444 is in the ephemeral port range: 49152 to 65535

My suggestion: Use 48444?

### Version

2.4.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 58444): address already in use
```

**Comment by madMAx43v3r** [comment]
Hmm, well, even for a new testnet you have the problem of old config files...

**Comment by wjblanke** [comment]
We have defaults for undefined config items, such as a new testnet. So you will need the new version of chia to get those of course. Otherwise yes you would have to manually configure it.
