### ISSUE TITLE
Wallet Not synced [BUG] - even after updated to 1.0.4

### ISSUE THREAD

**Issue by serwiseu** [Chia-Network/chia-blockchain#1878]
I have problem with Wallet not synced. 

https://github.com/Chia-Network/chia-blockchain/issues/1859

Even after update and run again, there was "syncing status" - about 1 hour, and after this there is NO SYNC WALET. Farming, and Pltoing working, but I don't get any XCH. I've farmed about 8TB and 0 XCH. Any sugestion ?

**Comment by salamanders** [comment]
possibly same issue: Everything was running fine on 1.0.4, happily plotting and farming, but woke up this morning to "Not Synced"
First time that message has stuck around.  Tried restarting, rebooting+restarting, no change.
Ubuntu.

**Comment by serwiseu** [comment]
after remove chia from programs, and delete folder with c:\users\myuser\.chia , and install anagin chia syncing starting again :). If you have this same problem, do it. It helps.
