### ISSUE TITLE
[Bug] Logging format change has broken downstream log parsers

### ISSUE THREAD

**Issue by dannygoulder** [Chia-Network/chia-blockchain#18799]
### What happened?

Commit 8b96b2331ae83befe60c9c0434aa858968dfb77d appears to have changed the logging format causing downstream log parsers to break.

### Version

2.4.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by wjblanke** [comment]
Oops ya this is needed. We will add a config setting so people can opt back in to the old format that will work with their 3rd party log scraping monitoring tools.

**Comment by wjblanke** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/18810

**Comment by wjblanke** [comment]
This is fixed in main if you'd like to try. You'll need to set a special config option to have backwards compatibility. See the PR.
