### ISSUE TITLE
[BUG] harvester pointing to an address other than mine

### ISSUE THREAD

**Issue by missing-chia** [Chia-Network/chia-blockchain#1882]
I was concerned that I have received no chia after farming 137 k32 plots since launch so I started poking around my settings to make sure everything was running correctly. I discovered my harvester was pointed at a receive address other than my current wallet. When I looked up the address I was farming to on chia explorer there was about the amount of chia I was expecting to have farmed by now.
I am not a coder but I am also not new to crypto. I save all wallet info and back up often. I have been farming since testnet and earned some test chia there. Mainnet launch is the only time I changed my wallet  because release notes said testnet wallets would no longer work.
I have no idea how this happened unless I somehow ended up farming to my testnet address through some kind of config import  however the info from my testnet wallet does not work to restore a wallet with my missing chia. I suspect this wallet mix up is some kind of user error on my part but I have no idea how it happened.

I am using the Windows 10 GUI client having upgraded every time a new version was released currently using 1.04

**Comment by dorkmo** [comment]
the awards go to the wallet address paired to the plots when they were originally created

**Comment by hoffmang9** [comment]
If the rewards are right on chiaexplorer then congratulations as you have farmed them and it is likely that your local wallet database is wrong. Don't delete your blockchain database but do shutdown, delete your wallet database, and restart. The wallet will resync - which does not interrupt farming - and then should show you the same balance you see on chiaexplorer.

**Comment by missing-chia** [comment]
I appreciate the quick response however this did not solve my problem. I
deleted the files in ~\mainnet\wallet\db and resynced my wallet however I
still show a balance of 0. I accept that the xch are non-recoverable and
that I have donated 8 chia to the forever hodl fund. I mainly posted on
github because I could not find anyone else saying they had a similar
problem. I am unsure how this happened and only wanted to point it out as
some small scale (smaller than me i.e. 1 or 2 TiB on a gaming box) might
have to wait months before discovering their client was not pointed at
their wallet. This issue might be somehow unique to me or the result of
some user error I cannot account for.

**Comment by dorkmo** [comment]
im not sure exactly what youre saying you tweaked, did you generate 24 new words at mainnet? did you manually change your wallet key? you might try to install chia on a different computer and input your original 24 words, then sync.
