### ISSUE TITLE
238.3 GiB is not enough space to plot with 1.0.4

### ISSUE THREAD

**Issue by Eldaw** [Chia-Network/chia-blockchain#1883]
The requirements for plotting with 1.0.4 are not precise enough. According to the release notes, 256 GB (**238.3 GiB**) is enough.

I tried plotting to an empty SSD with a free capacity of **256,047,710,208 bytes** (See screenshot). Converted to GB and GiB, this is 256 GB and **238.46 GiB**).

However, the drive ran out of space and the plotting operation failed.

![image](https://user-images.githubusercontent.com/3789849/114685606-f116c580-9d09-11eb-8053-75dcf7eaf714.png)

**Comment by sochajakub** [comment]
Same problem here. I have 1 TB SSD disk(no OS, only for plotting) but I can only plot 2 at same time. I think 1 TB should be enough for 3 plots.

**Comment by abayito** [comment]
I have the same issue.

Edición	Windows 10 Pro
Versión	20H2
Instalado el	‎01/‎04/‎2021
Compilación del sistema operativo	19042.867
Experiencia	Windows Feature Experience Pack 120.2212.551.0

**Comment by StogieC** [comment]
From Plotter Log on 1.0.4:
Approximate working space used (without final file): 269.334 GiB
Final File size: 101.350 GiB

**Comment by hoffmang9** [comment]
The log is definitely wrong on the "too large" side.

**Comment by ChenYCL** [comment]
same bug here

**Comment by hoffmang9** [comment]
Fixed in 1.1.1
