### ISSUE TITLE
[BUG] 3 days no rewards

### ISSUE THREAD

**Issue by Dravenex** [Chia-Network/chia-blockchain#1884]
I don't know if this is a bug or just some bad luck, but I didn't receive some rewards since 3 days. I'm farming 24/7 with about 62 TB plotted and my plots pass the filter. I'm active in a chia community and other people also have this kind of problem. Seems like a pretty annoying bug to me. There are also some people, that received about 10 XCH with only 20 TB plotted in one day. Weird.

![image](https://user-images.githubusercontent.com/79578061/114687756-566fb400-9d14-11eb-9638-d0ee60d1b708.png)

**Comment by hoffmang9** [comment]
If you have all your signage points and last attempted proofs - you are farming correctly and it is simply luck - or a lack thereof. There are many who went through dry spells and then got a block. The error added into this is just another node disconnecting.
