### ISSUE TITLE
[BUG]256G 一P不够啊，但是1T的盘搞3P是确实OK了

### ISSUE THREAD

**Issue by icer1** [Chia-Network/chia-blockchain#1886]
这是我们的CTO敏妃测试的结果，谢谢。

问题版本号：1.0.4

复现概率：必现

**Comment by kevinxu828** [comment]
256G是不够, 完成一个Plot的. 一个Plot 是101.4 GiB. 但是需要临时储存空间是再加238.3 GiB. 你是用专业机器吗?
