### ISSUE TITLE
[Bug] XCH disappear after resync

### ISSUE THREAD

**Issue by xch100** [Chia-Network/chia-blockchain#18881]
### What happened?

Hello! has anyone faced this kind of problem. Today I have tried to send 1 XCH to my okx account, but the message pops up that account must be synchronized. in couple of hours I tried again with 1 XCh, but same thing happened. Then I clicked to Settings>Advanced>RESYNC  and after wallet restarted all my coins disappeared. Please explain what have happened and how I can get my XCH back? Thank you!

### Version

2.4.4

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by Chloebarbers** [comment]
Hello @xch100 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID CHA07638
Please see the link below to our dedicated support line:
[Chia Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by BrandtH22** [comment]
Hey @xch100 , the previous commenter was a spammer please do not follow any guidance provided by them. 

When you are syncing does the wallet sync icon in the top right ever become green or does it stay orange/yellow?

**Comment by BrandtH22** [comment]
Hey @xch100 , as a reminder we can generally provide more timely and thorough support in our discord server (https://discord.gg/chia).

It being orange means the wallet is not fully syncing. What version of chia are you running? 
(version can be identified with the About Chia button when clicking help in the top left or the chia icon if on mac)
