### ISSUE TITLE
Full node wont't sync / Win10 Pro - Chia Version 1.0.4

### ISSUE THREAD

**Issue by ADMIN-2** [Chia-Network/chia-blockchain#1893]
Win10 Pro - Chia Version 1.0.4

Get the following messages in the error log. 

15:28:47.111 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
15:28:50.048 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:477> exception=CancelledError()>
concurrent.futures._base.CancelledError
15:38:50.125 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 449, in wait_for
concurrent.futures._base.TimeoutError

**Comment by mariano54** [comment]
Please port forward 8444 if you need more peers and cant sync:
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
