### ISSUE TITLE
MacOS Crashed using Chia GUI for plotting on external SSD

### ISSUE THREAD

**Issue by fisehara** [Chia-Network/chia-blockchain#1899]
During creation of new plots on external SDD for temp and external HDD as target the Mac OS crashed with a kernel panic.
Plotting stopped obviously.

Panic(CPU 2, time 426107297904762): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff8061d82570, spinlock owner: 0xffffff805a893a40, current_thread: 0xffffff805a893a40, spinlock_owner_cpu: 0x2
RAX: 0xffffff8068472520, RBX: 0xffffff80798254b8, RCX: 0x000000000000017a, RDX: 0x0001f4fe00000000
RSP: 0xffffffa3e8f33a70, RBP: 0xffffffa3e8f33ab0, RSI: 0xffffff805a893a40, RDI: 0xffffff80798254b8
R8:  0xffffffa3e8f33c30, R9:  0xffffff8003b6a2e0, R10: 0x0000000000ffffff, R11: 0xffffff8088b34e00
R12: 0xffffff805a893a40, R13: 0x0000000000000000, R14: 0x0001f4fe828895e2, R15: 0xffffff8068472520
RFL: 0x0000000000000083, RIP: 0xffffff8003b29fad, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 2), Frame : Return Address
0xffffff838c346f80 : 0xffffff8003c44e6b 
0xffffff838c346fd0 : 0xffffff8003abfbed 
0xffffffa3e8f33ab0 : 0xffffff8003b2a154 
0xffffffa3e8f33ae0 : 0xffffff8003b68aa0 
0xffffffa3e8f33b00 : 0xffffff8003b6a319 
0xffffffa3e8f33bb0 : 0xffffff8003b6a821 
0xffffffa3e8f33c20 : 0xffffff8003b69944 
0xffffffa3e8f33ce0 : 0xffffff8003b6d638 
0xffffffa3e8f33d20 : 0xffffff800404f114 
0xffffffa3e8f33d40 : 0xffffff800404f1fe 
0xffffffa3e8f33d80 : 0xffffff80040a4f3d 
0xffffffa3e8f33db0 : 0xffffff80040a59a3 
0xffffffa3e8f33e20 : 0xffffff800409fbf0 
0xffffffa3e8f33ee0 : 0xffffff800409f9b0 
0xffffffa3e8f33f40 : 0xffffff8004183347 
0xffffffa3e8f33fa0 : 0xffffff8003ac0206 

BSD process name corresponding to current thread: Chia Helper (Ren
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19H524

Kernel version:
Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
Kernel UUID: 64F23D6D-4C30-3FC4-B7C2-9EE0BBA0D29A
Kernel slide:     0x0000000003800000
Kernel text base: 0xffffff8003a00000
__HIB  text base: 0xffffff8003900000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO

System uptime in nanoseconds: 426107297934302
last loaded kext at 417351352728256: @filesystems.ntfs	3.14.3 (addr 0xffffff7f8936c000, size 425984)
last unloaded kext at 35825731970748: >usb.realtek8153patcher	5.0.0 (addr 0xffffff7f8537f000, size 20480)
loaded kexts:
com.razer.common.razerhid	21.94
org.virtualbox.kext.VBoxNetAdp	6.1.14
org.virtualbox.kext.VBoxNetFlt	6.1.14
org.virtualbox.kext.VBoxUSB	6.1.14
org.virtualbox.kext.VBoxDrv	6.1.14
@filesystems.ntfs	3.14.3
>usb.!UHostBillboardDevice	1.0
@filesystems.exfat	1.4
|IO!BSerialManager	7.0.6f8
@kext.AMDFramebuffer	3.1.0
@kext.AMDRadeonX4000	3.1.0
@kext.AMDRadeonServiceManager	3.1.0
>!AGraphicsDevicePolicy	5.2.7
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	5.2.7
|IOUserEthernet	1.0.1
>pmtelemetry	1
>!AHV	1
>!AUpstreamUserClient	3.6.8
>AGPM	111.4.4
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@Dont_Steal_Mac_OS_X	7.0.0
>!A!IKBLGraphics	14.0.7
>AGDCBacklightControl	5.2.7
>!AGFXHDA	100.1.429
@kext.AMD9500!C	3.1.0
>BridgeAudioCommunication	6.70.7
>!ABridgeAudio!C	6.70.7
>!A!ISlowAdaptiveClocking	4.0.0
>!ATopCaseHIDEventDriver	3430.1
>!AHIDALSService	1
>!A!ICFLGraphicsFramebuffer	14.0.7
>!AMuxControl2	5.2.7
>!AAVEBridge	6.1
>!A!IPCHPMC	2.0.1
>!AMCCSControl	1.14
>!AThunderboltIP	3.1.4
@filesystems.autofs	3.0
|SCSITaskUserClient	422.120.3
>!U!SCoexistentDriver	489.120.1
>BCMWLANFirmware4355.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
@filesystems.hfs.kext	522.100.5
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
>!ABCMWLANBusInterfacePCIe	1
@filesystems.apfs	1412.141.1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>usb.cdc.acm	5.0.0
>usb.serial	6.0.0
>usb.cdc.ecm	5.0.0
>usb.IOUSBHostHIDDevice	1.2
>!AXsanScheme	3
>!UAudio	323.4
|IOUSBHIDDriver	900.4.2
>usb.!UHub	1.2
@kext.AMDRadeonX4100HWLibs	1.0
@kext.AMDRadeonX4000HWServices	3.1.0
|IOUSBUserClient	900.4.2
|IOAVB!F	850.1
@!AGPUWrangler	5.2.7
>!ABacklightExpert	1.1.0
|IONDRVSupport	576.1
>!AHIDKeyboard	209
@kext.AMDSupport	3.1.0
|IOSlowAdaptiveClocking!F	1.0.0
>!AActuatorDriver	3440.1
>X86PlatformPlugin	1.0.0
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.6f8
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
|IO!BHost!CUARTTransport	7.0.6f8
|IO!BHost!CTransport	7.0.6f8
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
|IOAccelerator!F2	438.7.4
@!AGraphicsDeviceControl	5.2.7
>!AGraphicsControl	5.2.7
>IOPlatformPlugin!F	6.0.0d8
>!ASMBus!C	1.0.18d1
|IOGraphics!F	576.1
@kext.triggers	1.0
|IOUSBMass!SClass	4.0.4
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
>!ABCMWLANCore	1.0.0
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
>!A!ILpssI2C	3.0.60
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
>usb.!UVHCIBCE	1.2
>usb.!UVHCI	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
|IOUSB!F	900.4.2
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|CoreAnalytics!F	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	7.0.6f8
|IO!BPacketLogger	7.0.6f8
>!ASSE	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.140.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!UHostMergeProperties	1.2
>!ABusPower!C	1.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
panic(cpu 10 caller 0xffffff8003c3aaa0): "Spinlock acquisition timed out: lock=0xffffff8061d82570, lock owner thread=0xffffff805a893a40, current_thread: 0xffffff8068472520, lock owner active on CPU 0x2, current owner: 0xffffff805a893a40, time: 426107297959283"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.16/osfmk/i386/locks_i386.c:501
Backtrace (CPU 10), Frame : Return Address
0xffffff83ac944af0 : 0xffffff8003b1963d 
0xffffff83ac944b40 : 0xffffff8003c53ae5 
0xffffff83ac944b80 : 0xffffff8003c4566e 
0xffffff83ac944bd0 : 0xffffff8003abfa40 
0xffffff83ac944bf0 : 0xffffff8003b18d07 
0xffffff83ac944cf0 : 0xffffff8003b190f7 
0xffffff83ac944d40 : 0xffffff80042c01cc 
0xffffff83ac944db0 : 0xffffff8003c3aaa0 
0xffffff83ac944df0 : 0xffffff8003b37f5a 
0xffffff83ac944e30 : 0xffffff8003b37e7c 
0xffffff83ac944e60 : 0xffffff8003b6445c 
0xffffff83ac944f20 : 0xffffff8003c32807 
0xffffff83ac944f60 : 0xffffff8003c4d6d3 
0xffffff83ac944f80 : 0xffffff8003c44e6b 
0xffffff83ac944fd0 : 0xffffff8003abfbed 
0xffffffa3e92c3da0 : 0xffffff8003b6d431 
0xffffffa3e92c3e00 : 0xffffff80040a1a99 
0xffffffa3e92c3f00 : 0xffffff80040a0ba6 
0xffffffa3e92c3f40 : 0xffffff8004183347 
0xffffffa3e92c3fa0 : 0xffffff8003ac0206 

BSD process name corresponding to current thread: Chia Helper (Ren

**Comment by egorgolo** [comment]
I had the same problem yesterday
