### ISSUE TITLE
FAQ needs high-level explanation on how much electricity is saved vs BTC

### ISSUE THREAD

**Issue by alanhamlett** [Chia-Network/chia-blockchain#1900]
The [FAQ](https://github.com/Chia-Network/chia-blockchain/wiki/FAQ) needs more info about electricity savings. Around how much electricity does farming Chia save vs. mining Bitcoin?

**Comment by hoffmang9** [comment]
https://chiapower.org

But yeah - will add.

**Comment by hoffmang9** [comment]
Though it is a wiki so....

**Comment by hoffmang9** [comment]
Wiki updated.
