### ISSUE TITLE
plot has a pool public key that is not in the farmer's pool pk list

### ISSUE THREAD

**Issue by phantom-rabbit** [Chia-Network/chia-blockchain#1909]
Farmer public key (m/12381/8444/0/0):: a87322da5264a1fbdbcdbcee54face82cf1e218f65454af8d09f28a3c111f00c9341be683a330e74435f26ab16659b0e

chia plots create -f a87322da5264a1fbdbcdbcee54face82cf1e218f65454af8d09f28a3c111f00c9341be683a330e74435f26ab16659b0e -d /data1 --num=3 --buffer=18432

The generated file cannot pass the plotos check
I did ploto on another computer and then MV the file to plotos_ dir
![0d7a9939c0b57d60bb38816227579c6](https://user-images.githubusercontent.com/49083897/114809166-44f1df00-9ddc-11eb-95b5-6b91258af3bd.png)

**Comment by anshengme** [comment]
You don't seem to specify the pool public key.

**Comment by chuwt** [comment]
chia plots create -f your_farm_public_key -p your_pool_public_key, you lost your_pool_public_key arg

**Comment by ShilohMy** [comment]
最后怎么解决的，这个plot有效吗
