### ISSUE TITLE
Full Node Status sync error long 4 hours

### ISSUE THREAD

**Issue by tangz777** [Chia-Network/chia-blockchain#1919]
![image](https://user-images.githubusercontent.com/20453529/114817602-e5e89600-9dec-11eb-9549-954432c150ce.png)

**Comment by hoffmang9** [comment]
Which version are you using? Which OS? Which CPU?

**Comment by tangz777** [comment]
> Which version are you using? Which OS? Which CPU?

1.0.4  window 

full_node full_node_server        : ERROR    Exception [WinError 10054] 远程主机强迫关闭了一个现有的连接。, exception Stack: Traceback (most recent call last):

**Comment by llvll0hsen** [comment]
I have a similar issue on Ubunut 18.04.5. I used version 1.0.4 and waited the whole weekend but nothing happend. just upgraded to version 1.0.5. I am running another instant, version 1.0.3, with the same key on my mac book.

**Comment by llvll0hsen** [comment]
I have a similar issue on Ubunut 18.04.5. I used version 1.0.4 and waited the whole weekend but nothing happend. just upgraded to version 1.0.5. I am running another instant, version 1.0.3, with the same key on my mac book.  I also get the following msg when I run the GUI

```
(node:15439) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert

```

**Comment by mariano54** [comment]
Please port forward to 8444 if you need more peers.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
