### ISSUE TITLE
K32 plot takes about 18 hours - no new rewards after 12 days

### ISSUE THREAD

**Issue by TschiAR** [Chia-Network/chia-blockchain#1924]
Hi there,

i have some problems with plotting. First of all I thought it's normal for an K32 Plot to be created at about 24 hours. 
But two of my friends now tell me, that they only need about 6-8 hours.

I use AMD Ryzen 5 3600 6-Core processor 3.60 GHz, 32 GB Ram and the SSD for plotting is an Samsung SSD 860 QVO 2 TB.
There is enough RAM for plotting (about 8TB)

The SSD (bought in July 2020) ist in good condition after benchmark test. (Writing 7271 /Reading 6908)

I can't find the problem. Any ideas what cuses the slow speed?

Thanks for help.

TschiAR

P.S.:  By the way, i have about 25 TB Plots and since last monday there are no new rewards (Day 12 now but Chia software says about 4 days in expectation) Feels strange... Last Chia reward: Confirmed at height 89558

**Comment by dorkmo** [comment]
which software version are you on?

**Comment by TschiAR** [comment]
> which software version are you on?

I am on 1.0.5

**Comment by TschiAR** [comment]
yesterday i plotted 3 K32 paralell on 3 SSDs. The two SSDs i used with SATA were much slower for finishing than The SSD i used with an usb 3.0 outside of my pc. Hoever the time was much better: about 11 hours for 2 plots to be finished.


strange thing is: i don't get any rewards till last monday (05.04.21) - my pc is online nonstop.

**Comment by TschiAR** [comment]
Still no Rewards. 26 TB now

**Comment by maketigers** [comment]
I plotting 2TB no reward yet, it's very hard to get one chia . Would u like to sell me some chia?

**Comment by TschiAR** [comment]
> 
> 
> I plotting 2TB no reward yet, it's very hard to get one chia . Would u like to sell me some chia?

Hi, i can't sell you some. Coins are Locked and we all don't know the price. It is so hard so plot one. i would not sell one single XCH under 500 dollars right now ;-)

**Comment by hoffmang9** [comment]
GitHub issues aren't for coin sales.
