### ISSUE TITLE
Now we have started to dig official coins, but why can't we transfer tokens?

### ISSUE THREAD

**Issue by cppfuns** [Chia-Network/chia-blockchain#1931]
Now we have started to dig official coins, but why can't we transfer tokens? Is there any special reason why we are willing to close them temporarily?

**Comment by mariano54** [comment]
It's called farming. Transactions were disabled for the first few weeks, to make sure the consensus algorithm was stable. Transactions and smart contracts will be enabled within the next few weeks, with the 1.1 release.
