### ISSUE TITLE
GUI Parallel plotting is twice as fast as the Queue Trick

### ISSUE THREAD

**Issue by Teledyol** [Chia-Network/chia-blockchain#1934]
Before I finally got a new set of RAM (4x32) in my Mac Pro Trashcan, I was getting fairly good results using the Queue Trick of setting up several Queue plots with different names.

Once I got the new RAM, it was about the same time as we started using 1.0.4. (the switch was a bit wacky and stepped on one sequence)

I went through a couple failed attempts at setting up four queues at 6750 RAM. So, I decided to just set up the old GUI "plot in parallel" with the four. It ran great, with fewer errors on the log. I got for at an average of 5.4 Hours each

So I'm trying to kick back into the Queue Trick again and currently running much slower with the average at 7.5 hours each with the GUI showing 65% completion (prolly inaccurate). This is comparable to the first two failed attempts. 

I had a lot of errors up to midnight PST last night and it's now almost 8:30, without errors

Is anyone else showing slower plotting using the Queue trick?

**Comment by ful188** [comment]
me to
