### ISSUE TITLE
[BUG] Mac OS plots hang randomly 

### ISSUE THREAD

**Issue by currykinguk80** [Chia-Network/chia-blockchain#1945]
Since 1.0.4 I’ve had issues where the plots have hung during stage 4. Out of 6 plots this has happened to 4 plots.

I’ve attached a screenshot, this also seemed to then hang another plot that was nearing the end of stage 3.

- OS: Mac OS X 
- OS Version/Flavor: Mojave 10.14.6
- CPU: Intel core i7 
![81309E61-C1D0-4A74-9990-9E713B1D1D4C](https://user-images.githubusercontent.com/82612372/114930075-84e0b280-9e2c-11eb-8369-5fa40ac97ecd.jpeg)

**Comment by currykinguk80** [comment]
Just deleted the plot that was stuck at 91% and the one on stage 4 started working!?

**Comment by ebuwiz** [comment]
Same on Ubuntu 20.10, i7 8700k, some stucks at 80~90%, i go back to 1.0.4 and try

**Comment by aqk** [comment]
You may be trying to do too many plots in parallel. Check your temp directory for space issues, and delete old files if old plot jobs were killed.
