### ISSUE TITLE
[Wallet] Opening Wallet to Specific Subnet 

### ISSUE THREAD

**Issue by dendisuhubdy** [Chia-Network/chia-blockchain#1951]
Here is a screenshot on my local chia farm

<img width="835" alt="Screen Shot 2021-04-16 at 11 22 52" src="https://user-images.githubusercontent.com/4477337/114966945-c3fb1c00-9e9d-11eb-89ac-a0bbc31a3538.png">

I see that the wallet is listening on 127.0.0.1:9256. 

So I would want to change the listening host of the wallet from 127.0.0.1 to say something like 10.10.0.1 and allow incoming RPC messages from 10.10.0.1/24. How do you do that for the chia wallet node? Is there a config file where I can set the configurations like bitcoin.conf for bitcoin?

We're running an exchange and we would love to list chia/usd or chia/usdt. Any references to a codeline would be valuable! 

Thanks in advance

**Comment by hoffmang9** [comment]
You can set the listening IP to any valid interface IP in config.yaml in the wallet section. You'll also need the private TLS key pair on the remote machine to connect.

**Comment by hoffmang9** [comment]
Also there are two RPC pages on the wiki that are very useful for exchange applications. 

https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces

https://github.com/Chia-Network/chia-blockchain/wiki/RPCExamples

**Comment by mariano54** [comment]
Wallet port and RPC ports should never be opened to the internet. ONLY open the full node port (8444).

**Comment by dendisuhubdy** [comment]
@mariano54 @hoffmang9 thanks!

**Comment by dendisuhubdy** [comment]
@LmingXie @mariano54 @hoffmang9 told me about a config file, which I haven't found yet

**Comment by LmingXie** [comment]
> 通常在`~/.chia/mainnet/config`目录中。



> @LmingXie @ mariano54 @ hoffmang9告诉我一个配置文件，我还没有找到

I did this by modifying the ```~/.chia/mainnet/config/config.yaml``` file. Unfortunately, I did not find any configuration for opening 8555 and 9256 ports
