### ISSUE TITLE
How to join the testnet

### ISSUE THREAD

**Issue by cppfuns** [Chia-Network/chia-blockchain#1954]
I need to connect to the testnet for testing.Is there a step-by-step document for accessing the testnet?
I need to test k=25 on the testnet, I see a hint that the mainnet does not support k=25, I need a quick test, so I want to use k=25
Is there a block explorer on the testnet?

**Comment by cppfuns** [comment]
![image](https://user-images.githubusercontent.com/7980920/114985098-fec47a80-9ec4-11eb-9126-43843a04e0b6.png)

**Comment by cppfuns** [comment]
Why not add testnet options to chia ui and chia CLI?

**Comment by mariano54** [comment]
you do it with chia root. also make sure youre using main branch
```
CHIA_ROOT="~/.chia/testnet" chia init
# Change selected network
CHIA_ROOT="~/.chia/testnet" chia start all
```

**Comment by cppfuns** [comment]
> you do it with chia root. also make sure youre using main branch
> 
> ```
> CHIA_ROOT="~/.chia/testnet" chia init
> # Change selected network
> CHIA_ROOT="~/.chia/testnet" chia start all
> ```

Why not add an option? It would be more convenient?

**Comment by mariano54** [comment]
Yes we will soon.

**Comment by cppfuns** [comment]
> you do it with chia root. also make sure youre using main branch
> 
> ```
> CHIA_ROOT="~/.chia/testnet" chia init
> # Change selected network
> CHIA_ROOT="~/.chia/testnet" chia start all
> ```

https://github.com/Chia-Network/chia-blockchain/commit/207aed704f428ec1eaf72a6b9786b44d879dab4d#diff-bf989c7a83e9cb573c2819bc1ab944adcb5b0c93b28456b342383d55c612ad61

Has this strategy changed again? What to do now?

**Comment by cppfuns** [comment]
Hurry up to support the testnet option bar, and keep an official stable testnet and browser, which is too painful for developers at present

**Comment by hoffmang9** [comment]
We are aware that this process sucks.
