### ISSUE TITLE
ERROR: No matching distribution found for SecretStorage>=3.2; sys_platform == "linux"

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#1957]
sh install.sh # 
 
ERROR: Could not find a version that satisfies the requirement SecretStorage>=3.2; sys_platform == "linux" (from keyring)
ERROR: No matching distribution found for SecretStorage>=3.2; sys_platform == "linux"

**Comment by aqk** [comment]
Hello, SecretStorage is a dependency of "keyring" https://pypi.org/project/keyring/

This problem might be happening because your Linux distro or your pip version is old.
```
You can try manually installing pip https://pip.pypa.io/en/stable/installing/
And then pip install keyring
```

If you need more help, please run the following commands for the person trying to help:
```
 lsb_release -a
python --version
pip --version
```

Good luck!
