### ISSUE TITLE
[BUG] libstdc++ not found on v1.0.5

### ISSUE THREAD

**Issue by vkz** [Chia-Network/chia-blockchain#1960]
**Describe the bug**
Install v1.0.5 of chia-blockchain
Issue any chia command e.g. `chia version` and get:
```
  File "/home/user/chia/chia-blockchain/chia/util/hash.py", line 1, in <module>
    import blspy
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Install v.1.0.5 of chia-blockchain
2. profit

**Expected behavior**
Obviously missing dep. No problem on e.g. v1.0.1

**Desktop (please complete the following information):**

```
$ uname -a
Linux r730 5.11.10 #1 SMP 1 x86_64 GNU/Linux
```

**Comment by vkz** [comment]
Best guess is probably in blspy you hard-coded one of the expected places to look for these shared libs. That's ... not going to work on every Linux

**Comment by hoffmang9** [comment]
How are you installing?
