### ISSUE TITLE
MacOS doesn't sync

### ISSUE THREAD

**Issue by 17und4** [Chia-Network/chia-blockchain#1961]
**Describe the bug**

The syncing is not working. I am on chia 1.0.5. and I am connected however the sync is not working. I am using MacOS Big Sur 11.2.3.

Thank you for your help

**Comment by 17und4** [comment]
After rebooting 5 times it is working again

**Comment by never-afk** [comment]
Farming Status "Syncing" for 12 hours ,still no change
