### ISSUE TITLE
[HELP] Moving plot files

### ISSUE THREAD

**Issue by CIA-Trash** [Chia-Network/chia-blockchain#1962]
Is it possible to move the existing plot files? 
If so, how do I let the app to locate the new location of the plot file

**Comment by dorkmo** [comment]
you can copy and paste them anywhere you like, you just need to make sure to add the new location using "add plot directory"

**Comment by CIA-Trash** [comment]
Oh, I didn't see that 3 dots next to the add a plot button.
Thanks
