### ISSUE TITLE
[BUG] Node not synced 1.0.5

### ISSUE THREAD

**Issue by MoeGen** [Chia-Network/chia-blockchain#1967]
Status says the blockchain is not synced since one day. I upgraded to version 1.0.5 now and have the same issue. 

- OS: Windows 10 Professional

**Comment by gindind** [comment]
Same Problem here. Sync does not start

**Comment by babiboo** [comment]
The same thing happens to me - synchronization is not possible. On one computer (Ubuntu) stopped synchronization 8 hours ago. The number of external connections is almost permanently zero. Connection Status is Connected. I tried to run a new installation of version 1.0.5 also on windows 10 computer in another network, But even here, synchronization will not start after few hours. A maximum of one external connection is displayed for a minute or two minutes in list of Connections on Full Node card, then disappears and synchronization does not even begin.

I'm afraid that in this state this project is useless (that is, except for the chosen people connected probably to good permanent peers). I really don't know how to sync. It's a shame.

**Comment by alexgoodchild** [comment]
same. have tried deleting the whole blockchain and still the same problem on Ubuntu 20.04.

**Comment by dorkmo** [comment]
might try going back to 1.0.4

**Comment by Teledyol** [comment]
Might try going back to 1.0.1 =8^}

**Comment by mariano54** [comment]
Please port forward router to port 8444 by following instructions here:
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
There are a lot of new users, so more users need to open the ports

**Comment by mariano54** [comment]
Don't go back to a previous version

**Comment by btwiusegentoo** [comment]
Same issue on Linux
Always synced perfectly fine until today, suddenly sync stopped
I first thought it was my network bandwidth but it wasn't
I see a lot of cannot connect to host (ipv6 address) messages on log
And yes, I have opened the ports, never used upnp(upnp never worked for some reason on my router)
Tried deleting entire db but stops at some point

However, sync finally started after downgrading to 1.0.4 right now
gotta see if it sync successfully

**Comment by Mati32167** [comment]
I lost a lot of time to solve this problem. In my case it was a wrong time and data on my Windows....

**Comment by kilianso** [comment]
Same problem here. Since the update to 1.05 it remains on "Not synced" using the MacOS Electron UI. Tried to delete cache and application data, force reload and so on... It doesn't make a difference. Deleting the database is not really a solution since it takes days to catch up from 0.

**Comment by mariano54** [comment]
You only need to delete the peers DB table and port forward your router. It will be easy to get peers after that.

**Comment by erwinpgo** [comment]
> Please port forward router to port 8444 by following instructions here:
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
> There are a lot of new users, so more users need to open the ports

I am using Windows 10 and I can't find in the link to forward it to port 8444

**Comment by dorkmo** [comment]
you need to log in to your network's router and set it up there

**Comment by babiboo** [comment]
Last 2 days, a few hours during the day I'm not synched and no peer exists / is connected to me, but after 5-10 hours it will start sync again. I have no access to router (my farming virtual pc is in vpn).
