### ISSUE TITLE
Reload-Force Reload not working.

### ISSUE THREAD

**Issue by GeorgePapageorgakis** [Chia-Network/chia-blockchain#1969]
whenever I have used reload/force reload it has never worked. It just stands there with the loading icon and does nothing. I think its only UI issue. Farming continues to run in the background.

Also, when pressing exit, it stays forever in the "shuting down node" message and never exits until i force exit the app by clicking X on the window.

windows 10 pro
i7 6700K
chia 1.0.5

**Comment by CryptoSlug** [comment]
Same for me. Windows 10 pro. i7 9700k. 1.0.5 doesn't seem as stable as 1.0.1

**Comment by tbladh** [comment]
Same for me. Clicking those menu items locks up the UI and you have to forcibly shut down (loosing any plots currently in progress). Interestingly the same thing happens if I try to delete a plot.
OS: Win 10 Pro. Chia 1.0.5 (same behavior since at least 1.0.1)
