### ISSUE TITLE
Is there a guide of pipeline about usage on centos?

### ISSUE THREAD

**Issue by NirHeaven** [Chia-Network/chia-blockchain#1973]
I finish plots using chia plots create -d x -t x -2 x -b 40960 -r 64 -f -p, but I don't know how to farm and harvest

**Comment by NirHeaven** [comment]
I run chia start farmer, the output:
Daemon not started yet                                                                                                                                                          
 Starting daemon                                                                                                                                                                   chia_harvester: started                                                                                                                                                           chia_farmer: started                                                                                                                                                              chia_full_node: started                                                                                                                                                           
chia_wallet: started  
and the process exit without anything.

when I run chai show -s, I got: 
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up

How can I fix it?

**Comment by NirHeaven** [comment]
![image](https://user-images.githubusercontent.com/22441230/115100449-4d2e5380-9f6f-11eb-876f-568bc00518a6.png)
how can I sync or just waiting?

**Comment by aqk** [comment]
Hi there,

mainnet is running on port `8444`. I suspect you are on an old version of the client.

You are not syncing, because no other peers are trying to connect to you on `8555`

Please upgrade to 1.1.2 or later.
