### ISSUE TITLE
What is the backup file template, always error reported, unable to view wallet information？

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#1983]
(venv) chunde@chunde-super:~/chia-blockchain$ chia wallet show
No online backup file found, 
 Press S to skip restore from backup 
 Press F to use your own backup file: F
 Please provide the full path to your backup file:   # this

**Comment by mhbates** [comment]
Did you fix this? I'm having the same issue.

**Comment by hoffmang9** [comment]
Press S to skip restore from backup

**Comment by GAS85** [comment]
Would appreciate if it is documented, or explained... What is the expectation from "backup" and why it is ok to skip it?
