### ISSUE TITLE
The mnemonics added are only valid for the current terminal. Do you need to restart the service?

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#1984]
Exception from 'wallet' {'error': "'NoneType' object has no attribute 'tx_store'", 'success': False}
Farming status: Farming
Total chia farmed: Unknown
User transaction fees: Unknown
Block rewards: Unknown
Last height farmed: Unknown
Plot count: 7
Total size of plots: 709.396 GiB
Estimated network space: 346.364 PiB
Expected time to win: 111 days
Note: log into your key using 'chia wallet show' to see rewards for each key

**Comment by shibowe** [comment]
the same error for me ....
