### ISSUE TITLE
[BUG] Plot disappear

### ISSUE THREAD

**Issue by ca0t** [Chia-Network/chia-blockchain#1986]
**Describe the bug**
exit, then open and log in,i will find plot disappear,
add a plot _>choose you origin file path -> create plot
you will find just only one plot, is's syncing ，progress 1%
i try reload,is useless。why is that?

**Comment by ca0t** [comment]
it's not finished ,i'm syncing  , sync to 5% 。only temp file ,no final file

**Comment by errcodex** [comment]
Hello
I'm not sure if I understood your question correctly, there is a description of interrupted plotting on the wiki -- "[My computer/drive went into power save or rebooted while plotting?](https://github.com/Chia-Network/chia-blockchain/wiki/FAQ)" and "[Sleep kills plots](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL)"，The current interruption of plotting cannot be continued and cannot be resumed.
