### ISSUE TITLE
[BUG] Ambiguous warning when running plotcheck

### ISSUE THREAD

**Issue by pieterhelsen** [Chia-Network/chia-blockchain#1988]
**Describe the bug**
When checking plots via the CLI on my harvester, I get a warning telling me the farmer private key must be in the keychain in order to farm them. 

The warning looks like this:

```
10:18:00.707  chia.plotting.check_plots        : WARNING  There are 5 plots with a farmer or pool public key that is not on this machine. The farmer private key must be in the keychain in order to farm them, use 'chia keys' to transfer keys. The pool public keys must be in the config.yaml
```

I think this warning is harmless since I created the plot via the CLI rather than adding my keys to the harvester (per [these instructions](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines))

**To Reproduce**
1. Use `chia plots create` to create a new plot via the CLI on the harvester
2. Pass in your farmer and pool public keys via the -f and -p command line options
3. Wait for the plots to generate
4. Run `chia plots check` on the harvester machine

**Expected behavior**
I would expect one of two things to happen:
- `chia plots check` is aware of the setup of the machine (harvester, not a farmer) somehow and does not list the warning
- The warning is updated to include 'If you are using this machine as a harvester, you may ignore this warning.'

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04

**Comment by N0rdmann** [comment]
Same, followed the official guide to set up additional remote farmer: [Farming-on-many-machines](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines)
 which explicitly tells not to copy over complete key set to the remote machine:

> Warning:
> You cannot copy the entire config/ssl directory from one machine to another. Each harvester must have a different set of TLS
> certificates for your main machine to recognize it as different harvesters. Unintended bugs can occur, including harvesters failing to work properly when the same certificates are shared among different machines.

Guess the warning for the check should at least be modified to tell that this is totally fine on a remote farm-only machine.
