### ISSUE TITLE
[SUGGESTION] An IP segment cannot wining block at the same day

### ISSUE THREAD

**Issue by cielu** [Chia-Network/chia-blockchain#1992]
In my opinion, Chia is a better project than filecoin, but I don't think Chia can be monopolized like filecoin, and can't win more blocks with more plots, which will lead to different opportunities for everyone to win

**Comment by cielu** [comment]
If it is monopolized by big capital like filecoin, ordinary users have no chance to win the block

**Comment by hoffmang9** [comment]
If you read the first 4 pages of the Bitcoin Whitepaper it explains why you can not use IP address to try to create a concept of identity.

**Comment by cielu** [comment]
@hoffmang9  No No No , I'm not mean that . This is my suggest . You know many and many people use big chia pool and organize everyone to join their chia pool , whitch will result the small one don't have any opportunities to win the block . So I suggest one Ip segment only have one chance to win the block at one day

**Comment by hoffmang9** [comment]
There is no way to stop people lying about their IP segment. That's why Proof of Work and now Proof of Space and Time exist - to create virtual identity.

There is no better identity that PoW or PoST and everything else will be gamed.

**Comment by cielu** [comment]
@hoffmang9 This is really Important things , if you let chia like filecoin do , It's against anyone have the same opportunities to win the block .  Finally there would be  only few big pool have the chance to win block

**Comment by hoffmang9** [comment]
Every TB is the same. You are confusing time preference with ability to win. 100TB will win a lot every couple years.

**Comment by cielu** [comment]
@hoffmang9  Yeah , Yeah , that's right . but I'm not mean that. I mean, if an organization's mine pool is bigger and bigger, its chances of winning the block will also be bigger and bigger. He just needs to organize other people to join him, so that many people who are not so big have no chance to win the block award at all

**Comment by cielu** [comment]
Like filecoin . Only big pool have the chance to win block

**Comment by hoffmang9** [comment]
https://www.chia.net/2020/11/10/pools-in-chia.html

**Comment by cielu** [comment]
@hoffmang9  I got it . Thank u

**Comment by cielu** [comment]
@hoffmang9  But there is another possibility, that is, the platform will organize all small farmers to a private key, so that you can divide Chia equally according to how many plots you have

**Comment by hoffmang9** [comment]
That is broad and easy pooling in a nutshell.

**Comment by cielu** [comment]
Yes . So chia is the same like filecoin.If you join the big pool , you will have more chance to win block ... ha

**Comment by hoffmang9** [comment]
No - you will win in proportion to your space. If you join a pool you will win in proportion to your space minus the pool fee.

It is just that simple. Pools charge you for your time preference.
