### ISSUE TITLE
can't sync on the peak hight 145636 

### ISSUE THREAD

**Issue by sunyao920807** [Chia-Network/chia-blockchain#2004]
my chia versin is 1.0.5，now it was stay at 145636,and my network is normal

**Comment by LoudSyncro** [comment]
Almost same here, but at
Peak Height 145698
Lost connection to all externel nodes.
Logging (set on info level) stopped.
Restarting Chia: Still no connect  to other nodes.
Network OK
Internet OK
Ports opened at Internet router (8444)

**Comment by mariano54** [comment]
Please try port forwarding to port 8444.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
