### ISSUE TITLE
[BUG] weird issue with dialogue box popping up with number "13" and plots not farming when complete.

### ISSUE THREAD

**Issue by Bletea** [Chia-Network/chia-blockchain#2005]
**Describe the bug**
When starting up the Chia app a dialogue box pops with "13" and doesn't say anything else. I have to click OK and also click several times outside the box to clear it away. The box pops up again after completing a plot and maybe some other instances too. My plots are also not farming once completed, they disappear from my Chia plots in the app. The plots appear to be valid and working as I can move them to another farming machine where they work.
I was using version Chia 1.03 and now using 1.05 with the same issue.

**To Reproduce**
Starting Chia
or
Completing a plot

**Expected behavior**
Not to have a dialogue box appear (that doesn't really say anything) when starting the program or completing a plot.
For the plots to farm once completed and not disappear from the program.

**Screenshots**
![Chia annoying diaglogue box with number](https://user-images.githubusercontent.com/82740860/115132259-e88ff900-a041-11eb-9cbf-3e31dd8e4662.png)

**Desktop (please complete the following information):**

- OS: Microsoft Windows
- OS Version/Flavor:  10 Pro 64 bit
- CPU: Intel i7-6820HQ
- Device: Lenovo ThinkPad P50

**Comment by hoffmang9** [comment]
We are aware this is a bad dialog but we can tell you that it is caused by something being off about your plot directories in config.yaml
