### ISSUE TITLE
[BUG] Always "Connecting to wallet"

### ISSUE THREAD

**Issue by hailang8635** [Chia-Network/chia-blockchain#2008]
![image](https://user-images.githubusercontent.com/8625086/115132992-613d8800-a037-11eb-9d58-d33ff96d29ba.png)

- OS: [centos]
- OS Version/Flavor: [CentOS 8]

**Comment by hailang8635** [comment]
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]: [74600] Failed to execute script start_wallet
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]: stderr: Traceback (most recent call last):
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]:  File "chia/server/start_farmer.py", line 68, in <module>
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]:  File "chia/server/start_farmer.py", line 63, in main
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]:  File "chia/server/start_farmer.py", line 38, in service_kwargs_for_farmer
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]:  File "chia/farmer/farmer.py", line 73, in __init__
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]: RuntimeError: No keys exist. Please run 'chia keys generate' or open the UI.
Apr 18 10:09:53 r630 chia-blockchain.desktop[74460]: [74604] Failed to execute script start_farmer

**Comment by ittuner** [comment]
Have same trouble. 
OS: Windows 10
CPU: Core-i9 10850K
RAM: 64Gb

![image](https://user-images.githubusercontent.com/48359370/115140007-838ed000-a04e-11eb-846f-919f90b056f6.png)

**Comment by aisu-programming** [comment]
OS: Windows 10
CPU: i7-9700
RAM: 32G

![image](https://user-images.githubusercontent.com/66176726/115166632-be444700-a0e6-11eb-9cc6-6f372b3be418.png)
