### ISSUE TITLE
[BUG] Is this a bug?

### ISSUE THREAD

**Issue by ndcc5** [Chia-Network/chia-blockchain#2009]
![HCK_}{P`Y`}PXYR(Y33JCLH](https://user-images.githubusercontent.com/6286019/115133172-c2199000-a038-11eb-9c7c-1c84b46541ec.png)
![~Y1@I%IX(45RX{XH8R399(M](https://user-images.githubusercontent.com/6286019/115133173-c3e35380-a038-11eb-98bc-a1a69bd548c2.png)

**Comment by Z-fly** [comment]
不是BUG吧

**Comment by ndcc5** [comment]
容量明明够，这是什么原因

**Comment by Billy-Hostage** [comment]
GiB单位和GB不同
1 GiB = 1.07374182 GB

**Comment by Z-fly** [comment]
> GiB单位和GB不同
> 1 GiB = 1.07374182 GB

硬盘厂原则上用1000MB表示1GB，但是win上是1024MB=1GB

**Comment by ndcc5** [comment]
那实际容量到多少才够429GIB?

**Comment by ndcc5** [comment]
465GB怎么算也够429.8GIB了吧

**Comment by jonny77** [comment]
你选择的时候,429G 需要1041的 临时空间.....

**Comment by ndcc5** [comment]
> 你选择的时候，429G需要1041的临时空间.....

了解了
