### ISSUE TITLE
[BUG] Can't sync on centos 7

### ISSUE THREAD

**Issue by NirHeaven** [Chia-Network/chia-blockchain#2014]
![image](https://user-images.githubusercontent.com/22441230/115136292-71faf780-a051-11eb-8906-91b5c88a6588.png)
Block here for one days, how can I fix it?

**Comment by mariano54** [comment]
Please try port forwarding to port 8444.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
