### ISSUE TITLE
[BUG] Installing from `main` it syncs to `testnet3`

### ISSUE THREAD

**Issue by robwedd** [Chia-Network/chia-blockchain#2016]
**Describe the bug**
When I checkout `main` and install, it syncs to `testnet3`. When I install from `dev` I get `mainnet`

**Expected behavior**
I would expect `mainnet` to be off `main`

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 16.0.4LTS
- CPU: Intel  i5-4300U CPU @ 1.90GHz × 4 

**Additional context**

**Comment by mariano54** [comment]
Do not install from main. Make sure to checkout tag 1.0.5.
Follow the install instructions in the wiki.

**Comment by robwedd** [comment]
Thanks. I've been following https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian 

I was looking for a branch v1.0.5 like v1.0.4. I'll use the tag
