### ISSUE TITLE
Plotting extremely slow in 1.0.5 versus 1.0.3 

### ISSUE THREAD

**Issue by Fintal78** [Chia-Network/chia-blockchain#2020]
Plotting with v1.0.5 is extremely slow versus v1.0.3 although apparently it should be faster ...
Roughly two times slower for 2 plots with parallel plotting

**To Reproduce**
Plotting in parallel 2 plots with by default settings.
v1.0.3 : 2 plots in 25 hours 
v1.0.5 : 2 plots in 44 hours

**Desktop (please complete the following information):**
- OS: Windows10
- Processor : Intel(R) Core(TM) i7-8550U CPU @ 1.80 GHz 1.99 GHz
- Installed RAM 16 GB
- External HDD used : Seagate Expansion Desktop Drive 14TB USB 3.0 (STEB14000400)

**Comment by jjhesk** [comment]
@Fintal78 what is your plotting configuration?

**Comment by Fintal78** [comment]
Thanks for reaching out !
k=32
Don't know what is u, n, b ...
I do 2 plots in parallel
Rest was set as by default :
RAM max usage by default : 4608 MiB for v1.0.3 and by default value for v1.0.5 (I don't remember the value since I downgraded to v1.0.3 since then, but it was lower, between 3000 and 4000 MiB I think)
number of threads = 2
Number of buckets = 128
Queue Name = default
Bitfield plotting enabled
If you have better settings that would be great, it really takes a very long time to plot...

**Comment by sargonas** [comment]
closing this as it's an old thread regarding "ancient" versions that have been replaced. If you are still having issues feel free to open up a new Discussion, or file a bug issue if relevant.
