### ISSUE TITLE
[Enhancment] Please kindly add the manually sync button or some thing in the chia client

### ISSUE THREAD

**Issue by wolegecha** [Chia-Network/chia-blockchain#2021]
**Describe the bug**
The Chia client sync very slow and often can not sync, Please kindly add the feature to manually start the sync

And I can not find any trust chia node list in the google. Please kindly also help add that list. Or What is the meaning of feature "connect to other peers." The Chia client version is the latest 1.0.5

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/82750878/115138304-e176e400-a05d-11eb-91d9-c275e2c64f99.png)

**Desktop (please complete the following information):**

- OS: [windows]
- OS Version/Flavor: [windows 10]
- CPU: [ryzen 3500x]

**Additional context**

**Comment by mariano54** [comment]
Please try port forwarding your router to 8444:
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections
