### ISSUE TITLE
[BUG]RuntimeError: bad allocation

### ISSUE THREAD

**Issue by heiheiheibj** [Chia-Network/chia-blockchain#2026]
WIN10 PRO 16G 2THDD

caught plotting error:bad allocation
[14980]Failed to execute script chia
.......
create_polts/py line 176,in create_plots
RuntimeError: bad allocation[](url)

**Comment by hoffmang9** [comment]
This is hardware or software RAM problem. Could be swap, could be your overclock, could be a bad stick of RAM.

**Comment by Jumberto77** [comment]
How to fix this bad problem?

**Comment by heiheiheibj** [comment]
> This is hardware or software RAM problem. Could be swap, could be your overclock, could be a bad stick of RAM.

ok.thx

**Comment by heiheiheibj** [comment]
> How to fix this bad problem?

429.8G(k=34temp space:1041gib) --> 208.8(k=33 ,temp space=521gib) nailed it
