### ISSUE TITLE
A question on filesystems support Copy on Write

### ISSUE THREAD

**Issue by lsylx** [Chia-Network/chia-blockchain#2030]
I found that actually on macOS with apfs support, you can copy a file without using the space of a disk (That file system support CoW). And plot files won't change after generated. So I can copy the plots into infinity without using the space of a disk. Is that possible to earn more coins by farming these copies of plot files but actually I just used only the space of one plot file?

**Comment by stonehenge360** [comment]
Ignoring CoW for a moment....if you simply duplicate a plot, you don't get 2x the coin.  Your plots need to be unique.   CoW would only work if you could run 100 instances of the same plot file which would defeat the purpose of the proof of space.

Correct me if I am wrong though

**Comment by hoffmang9** [comment]
Only the space taken up by unique plot files counts towards your ability to win. Farming two copies of the same k=32 is no different than farming one copy from a winnings perspective.
