### ISSUE TITLE
my MACOS catalina is always "connecting to wallet" but my WIN 10 is OK .

### ISSUE THREAD

**Issue by 99184806** [Chia-Network/chia-blockchain#2031]
My MACOS catalina is always "connecting to wallet" but my WIN 10 is OK .

**Comment by 99184806** [comment]
Chia-1.0.1.dmg
Chia-1.0.3.dmg
Chia-1.0.4.dmg
Chia-1.0.5.dmg

I've tried them al

**Comment by stonehenge360** [comment]
go into user/.chia/mainnet/wallet, and delete the db file. 

Mine does that all the time too.  It is still a bug, but this is a quick solution.

**Comment by 99184806** [comment]
> go into user/.chia/mainnet/wallet, and delete the db file.
> 
> Mine does that all the time too. It is still a bug, but this is a quick solution.


thank you very much ,it works

**Comment by pokemordum** [comment]
I have same problem, but i cant find that path user/.chia/mainnet/wallet
