### ISSUE TITLE
Network lost

### ISSUE THREAD

**Issue by Teledyol** [Chia-Network/chia-blockchain#2038]
02:58:35.687 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 67, in _state_changed
  File "aiohttp/client_ws.py", line 150, in send_str
  File "aiohttp/http_websocket.py", line 687, in send
  File "aiohttp/http_websocket.py", line 643, in _send_frame
  File "aiohttp/http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
02:59:12.812 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 67, in _state_changed
  File "aiohttp/client_ws.py", line 150, in send_str
  File "aiohttp/http_websocket.py", line 687, in send
  File "aiohttp/http_websocket.py", line 643, in _send_frame
  File "aiohttp/http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
02:59:28.255 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 67, in _state_changed
  File "aiohttp/client_ws.py", line 150, in send_str
  File "aiohttp/http_websocket.py", line 687, in send
  File "aiohttp/http_websocket.py", line 643, in _send_frame
  File "aiohttp/http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
.
02:59:39.802 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:39.802 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:39.803 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:40.033 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:41.809 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:41.809 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:41.809 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:42.101 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:43.815 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:43.824 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:44.042 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:44.392 full_node chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:45.827 farmer chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:45.830 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:55400
02:59:46.135 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:55400

**Comment by Teledyol** [comment]
The harvester kept running after Chia GUI was lost

**Comment by atyhieu** [comment]
> 02:58:35.687 full_node chia.rpc.rpc_server : WARNING Sending data failed. Exception Traceback (most recent call last):
> File "chia/rpc/rpc_server.py", line 67, in _state_changed
> File "aiohttp/client_ws.py", line 150, in send_str
> File "aiohttp/http_websocket.py", line 687, in send
> File "aiohttp/http_websocket.py", line 643, in _send_frame
> File "aiohttp/http_websocket.py", line 660, in _write
> ConnectionResetError: Cannot write to closing transport
> .
> 02:59:12.812 full_node chia.rpc.rpc_server : WARNING Sending data failed. Exception Traceback (most recent call last):
> File "chia/rpc/rpc_server.py", line 67, in _state_changed
> File "aiohttp/client_ws.py", line 150, in send_str
> File "aiohttp/http_websocket.py", line 687, in send
> File "aiohttp/http_websocket.py", line 643, in _send_frame
> File "aiohttp/http_websocket.py", line 660, in _write
> ConnectionResetError: Cannot write to closing transport
> .
> 02:59:28.255 full_node chia.rpc.rpc_server : WARNING Sending data failed. Exception Traceback (most recent call last):
> File "chia/rpc/rpc_server.py", line 67, in _state_changed
> File "aiohttp/client_ws.py", line 150, in send_str
> File "aiohttp/http_websocket.py", line 687, in send
> File "aiohttp/http_websocket.py", line 643, in _send_frame
> File "aiohttp/http_websocket.py", line 660, in _write
> ConnectionResetError: Cannot write to closing transport
> .
> 02:59:39.802 wallet chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:39.802 farmer chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:39.803 harvester chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:40.033 full_node chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:41.809 farmer chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:41.809 wallet chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:41.809 harvester chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:42.101 full_node chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:43.815 farmer chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:43.824 harvester chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:44.042 wallet chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:44.392 full_node chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:45.827 farmer chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:45.830 harvester chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400
> 02:59:46.135 wallet chia.rpc.rpc_server : WARNING Cannot connect to daemon at ws://localhost:55400

**Comment by atyhieu** [comment]
Là sao cái này là gì vậy ông ?? Thực sự tôi không biết là gì luôn đó
