### ISSUE TITLE
Problem with Plot on M2 ssd

### ISSUE THREAD

**Issue by Rustamello** [Chia-Network/chia-blockchain#2043]
Im just adding a plot, 1% complete and nothing happens, last log:
File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception
re-creating plot and restart programm not help
help me guys, im stuck :(

**Comment by atyhieu** [comment]
Im just adding a plot, 1% complete and nothing happens, last log:
File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception
re-creating plot and restart programm not help
help me guys, im stuck :(

**Comment by Rustamello** [comment]
im dumb :D

**Comment by lexey22** [comment]
> Я просто добавляю сюжет, 1% завершен, и ничего не происходит, последний журнал:
> файл «chia \ plotting \ create_plots.py», строка 176, в create_plots
> RuntimeError: неизвестное исключение,
> воссоздающее сюжет и перезапуск программы не
> помогают мне, ребята, я застрявший :(



> я тупой: D

Как исправил?
