### ISSUE TITLE
[BUG] Daemon uses too much RAM

### ISSUE THREAD

**Issue by lunamcsv** [Chia-Network/chia-blockchain#2055]
![Screenshot from 2021-04-08 01-56-5011](https://user-images.githubusercontent.com/69607389/115152614-f96d5880-a09b-11eb-8902-187f7f541a37.png)

**Comment by Solitude12345** [comment]
![image](https://user-images.githubusercontent.com/40972612/115153360-1a3bab00-a0a8-11eb-965d-b205b371a243.png)
I encountered the same problem. The deamon process occupies memory indefinitely, and Chia.exe crashes after all the memory is consumed.

**Comment by Solitude12345** [comment]
**These are the three logs that I have viewed**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 336, in _state_changed
  File "websockets\protocol.py", line 567, in send
  File "websockets\protocol.py", line 1083, in write_frame
  File "websockets\protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 340, in _state_changed
ValueError: list.remove(x): x not in list
12:02:43.213 daemon __main__                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 827, in transfer_data
  File "websockets\protocol.py", line 895, in read_message
  File "websockets\protocol.py", line 971, in read_data_frame
  File "websockets\protocol.py", line 1051, in read_frame
  File "websockets\framing.py", line 105, in read
  File "asyncio\streams.py", line 679, in readexactly
  File "asyncio\streams.py", line 473, in _wait_for_data
concurrent.futures._base.CancelledError



18:12:00.761 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError


23:51:10.393 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

**Comment by athkalia** [comment]
I had the same problem the other day as well, but I don't have the logs. I was plotting 16 K32 with 5Gb ram each, and 110GB of ram were occupied in total, with the daemon taking up most of them. I read somewhere in Keybase that this is a known issue. Is that the case?

**Comment by lunamcsv** [comment]
After I rebooted, everything returned to normal. But not sure if it happened again?

**Comment by Solitude12345** [comment]
I am 100% recurring, ploting after a period of time

**Comment by Solitude12345** [comment]
An average increase of 5MB of memory per second is used, which is incredible

**Comment by jjhesk** [comment]
i think there is a vm leak from the daemon. We will need to look into the clvm code.

**Comment by athkalia** [comment]
happened again last night. 
![image](https://user-images.githubusercontent.com/6057808/115190974-b386b380-a0e0-11eb-94f2-a938adc32d20.png)
All my plots should have taken a maximum of 90GB together, yet here they are at 98Gb.

![image](https://user-images.githubusercontent.com/6057808/115191100-e466e880-a0e0-11eb-8d2e-00fc75af2133.png)

I can't find anything in the logs really for this.

Seems to be happening when there are many plots running in parallel, (for me it was 15 to 18 or so)

**Comment by HughRyu** [comment]
![Deamon Mem Usage](https://user-images.githubusercontent.com/34954767/115943412-6a6ca000-a4e2-11eb-92ff-b1eba53d1f17.png)
Same problem，everytime ploting last phase，deamon session usage vary high。
Chia Ver:1.10，Stuck at ploting 100% over 4hrs from now on。

Ploting Log:
Finished writing C1 and C3 tables
	Writing C2 table
	Finished writing C2 table
	Final table pointers:
	P1: 0x10c
	P2: 0x37493b77a
	P3: 0x6b6274b59
	P4: 0x9fe2ea2af
	P5: 0xd569778c9
	P6: 0x10db0f1f8c
	P7: 0x14ece49120
	C1: 0x190e1e9520
	C2: 0x190e38d3d4
	C3: 0x190e38d484
Time for phase 4 = 2085.786 seconds. CPU (85.740%) Sat Apr 24 06:39:17 2021
Approximate working space used (without final file): 269.470 GiB
Final File size: 101.424 GiB

Mem leak or bug？

**Comment by HughRyu** [comment]
![Deamon Mem Usage](https://user-images.githubusercontent.com/34954767/115943848-de0fac80-a4e4-11eb-99e5-6af0c50e3115.png)
Same problem,everytime ploting last phase,deamon session memory highly consumption.
Chia Ver:1.10,Stuck at ploting 100% over 4hrs from now on.

Ploting Log:
Finished writing C1 and C3 tables
Writing C2 table
Finished writing C2 table
Final table pointers:
P1: 0x10c
P2: 0x3749xxxxx
P3: 0x6b62xxxxx
P4: 0x9fe2xxxxx
P5: 0xd569xxxxx
P6: 0x10dbxxxxx
P7: 0x14ecexxxxx
C1: 0x190e1xxxxx
C2: 0x190e3xxxxx
C3: 0x190e3xxxxx
Time for phase 4 = 2085.786 seconds. CPU (85.740%) Sat Apr 24 06:39:17 2021
Approximate working space used (without final file): 269.470 GiB
Final File size: 101.424 GiB

Mem leak or bug?

**Comment by OVERDRIVEZhi** [comment]
Happend to me as well. Using dual Xeon E5v3, 64GB RAM. It causes huge problem for plotting as it happens mostly at 70% or so during the Phase 3, then it crashes and wasted all of my SSD lifespan with it. Please fix ASAP. One of the plotter log and debug log was attached below, hope its helpful.
![Memory usage](https://user-images.githubusercontent.com/65071463/116195533-ed049200-a764-11eb-9467-b90dfa490809.png)
[plotter_log_1b0a28d1-1798-4fa7-ba02-c2bb0bc8aa35.txt](https://github.com/Chia-Network/chia-blockchain/files/6382349/plotter_log_1b0a28d1-1798-4fa7-ba02-c2bb0bc8aa35.txt)
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/6382351/debug.log)

**Comment by hoffmang9** [comment]
We know what this problem is and are working on a fix.

**Comment by athkalia** [comment]
FYI I just started plotting from the CLI, which does not have this issue.

**Comment by OVERDRIVEZhi** [comment]
> FYI I just started plotting from the CLI, which does not have this issue.

Yes, I later also found that CLI is a much better option. But it lacks log file and I have many plotter running at the same time so it is kinda hard to keep track on the plotting progress. Otherwise it's great :)

**Comment by hoffmang9** [comment]
Should be long fixed.
