### ISSUE TITLE
BUG!After plotting 100%, adding the plot file to the farm is stuck

### ISSUE THREAD

**Issue by CallV** [Chia-Network/chia-blockchain#2062]
After plotting 100%, adding the plot file to the farm is stuck

**Comment by jjhesk** [comment]
are you using the testnet config for plotting and switch back to mainnet settings for farming? @CallV

**Comment by CallV** [comment]
now is normal，maybe i use a lot plot in parallel



---Original---
From: "MDCCLXXVI ***@***.***&gt;
Date: Mon, Apr 19, 2021 12:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Chia-Network/chia-blockchain] BUG!After plotting 100%, adding the plot file to the farm is stuck (#2062)




 
are you using the testnet config for plotting and switch back to mainnet settings for farming? @CallV

**Comment by jjhesk** [comment]
is that okay to do so? as i have mentioned.

**Comment by CallV** [comment]
ok
i'm already farming！

---Original---
From: "MDCCLXXVI ***@***.***&gt;
Date: Mon, Apr 19, 2021 14:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Chia-Network/chia-blockchain] BUG!After plotting 100%, adding the plot file to the farm is stuck (#2062)




 
is that okay to do so? as i have mentioned.

**Comment by jonny77** [comment]
i finished one plot in console . but i got error message at gui tools : failed to open (invalid plots)  
![image](https://user-images.githubusercontent.com/1962170/115210855-94644200-a131-11eb-9694-8f653cfb14b8.png)

**Comment by aqk** [comment]
Please join `#beginner` or `#support` on keybase for tech support.
