### ISSUE TITLE
Suddenly won't sync anymore (Win10, 1.0.5)

### ISSUE THREAD

**Issue by IssaEgvi** [Chia-Network/chia-blockchain#2065]
I was plotting as per usual and noticed 'Synced/Farming' turned to Not Synced.
I've since tried re-loading, restarting the client, restarting my computer, detaching and reattaching the drives that store my Plots and nothing worked.
Re-attaching the drives makes it go into yellow for a minute (trying to sync) but it gives up and stays red for hours.

This key is running on two machines (has been like that for a month, no problems), plotter and farmer, and both of them suffered this lack of sync at the same time, implying it has something to do with the Key itself? Is that even possible?

I used to have the issue of random need to sync and the program would retry on its own but it never took several hours like now.

Forgot to add, I've since shut down the Farmer so there's only 1 machine running this key and it's the same. Last attempt was 8h ago.

**Comment by DonContento** [comment]
Same problem here with Windows Client 1.0.5. 
it turned to "not synced". Also tried to re-load (reload get stucked in neverending wallet connection always), restart, network restart - with no positiv result.

**Comment by IssaEgvi** [comment]
> 
> 
> Same problem here with Windows Client 1.0.5.
> it turned to "not synced". Also tried to re-load (reload get stucked in neverending wallet connection always), restart, network restart - with no positiv result.

I hope it started to work out of nowhere in Your case too, mine got back some 2h ago.
