### ISSUE TITLE
I have a problem, I'm connected but not synced

### ISSUE THREAD

**Issue by gabrielRH-pc** [Chia-Network/chia-blockchain#2066]
My connection status is connected but my status node not synced 

![image](https://user-images.githubusercontent.com/61268202/115159925-f2dbe280-a095-11eb-945c-ba34037bd787.png)

- OS: Windows
- OS Version/Flavor: W10
- CPU: i5-10400

**Comment by IssaEgvi** [comment]
Same, 8h of the same exact issue. I've also tried reinstalling the Client and now I've lost Chia icon, it just looks like a sheet of paper. Crazy where all these bugs came from we've been running the same version for 3 days now.

**Comment by thomaswilley** [comment]
+1. Syncing not happening with 1.0.5
Something up with upnp maybe not seeing it anymore, trying to troubleshoot...

**Comment by petrkr** [comment]
I just synced 1.0.5 from scratch today on Windows 10
![image](https://user-images.githubusercontent.com/6428351/115161177-6d0f6580-a09c-11eb-8e59-ec28de47e6d8.png)

**Comment by hoffmang9** [comment]
Make sure your system clocks are accurate.

**Comment by petrkr** [comment]
Also at Gentoo linux also fully synced today

```
(chiacoin) $ chia show -s
Current Blockchain Status: Full Node Synced

Peak: Hash: 620d91db91f69359d4ca64b032b75f1c42b4d2bc21b3316d0f2ccf4cc6bfaa1e
      Time: Sun Apr 18 2021 23:20:19 CEST                  Height:     149728

Estimated network space: 372.665 PiB
Current difficulty: 24
Current VDF sub_slot_iters: 111149056
Total iterations since the start of the blockchain: 499101744440
```

For me bigger question where to exchange potential coins?

**Comment by petrkr** [comment]
Both nodes are behind firewall on IPv4 network without UPnP
Both nodes has IPv6 conectivity (also behind firewall)

**Comment by liszechung** [comment]
i was using 1.03
upgraded to 1.05
not able to sync

**Comment by nitrotm** [comment]
FYI: I also have sync problems since I upgraded from 1.0.1 to 1.0.5 a few days ago. The GUI now shows that the node is sometimes synced and sometimes not synced.

**Comment by petrkr** [comment]
They have some problem with peers propagation. Use manual connect to "node.chia.net" port 8444 or if you have public IP open 8444 port on firewall

**Comment by hoffmang9** [comment]
If you open port 8444 you will get plenty of nodes to sync from - https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
