### ISSUE TITLE
[BUG] Remote GUI stuck on "connecting to wallet"

### ISSUE THREAD

**Issue by vermi** [Chia-Network/chia-blockchain#2078]
**Describe the bug**
When running the GUI with remote settings, it is stuck on "connecting to wallet" and never displays any info.

**To Reproduce**

1. Configure GUI as remote GUI
2. Ensure that settings on the remote end are correct (self_hostname: 0.0.0.0)
3. Open GUI

**Expected behavior**
Expect GUI to fully load and show remote daemon info.

**Screenshots**
![Screenshot](https://i.imgur.com/yt6iCZb.png)

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: Big Sur
- Chia version: 1.0.5

**Additional Context**
GUI works as expected without remote configuration. There is no info in the debug.log

**Comment by iwwwwwwi** [comment]
Perhaps a stupid question but have you checked if there's no firewall on your full node preventing access to 55400?

I'm running farmer on a Linux box, and followed this [this](https://github.com/Chia-Network/chia-blockchain/wiki/Connecting-the-UI-to-a-remote-daemon) to setup GUI on MacOS. I had to export CHIA_ROOT for GUI to work properly.

**Comment by vermi** [comment]
Yes, I am able to connect using netcat.

I have set CHIA_ROOT and the GUI does appear to be grabbing the config (as shown by the web socket IRL in the title bar).

On Apr 19, 2021, at 02:08, Marcin Iwiński ***@***.***> wrote:

﻿

Perhaps a stupid question but have you checked if there's no firewall on your full node preventing access to 55400?

I'm running farmer on a Linux box, and followed this this<https://github.com/Chia-Network/chia-blockchain/wiki/Connecting-the-UI-to-a-remote-daemon> to setup GUI on MacOS. I had to export CHIA_ROOT for GUI to work properly.

**Comment by vermi** [comment]
I am not sure what fixed the issue, but I deleted the Chia GUI and reinstalled it on my Mac and everything seems to be working fine now.
