### ISSUE TITLE
can't start sync, Status show:Not Synced

### ISSUE THREAD

**Issue by lifengllk** [Chia-Network/chia-blockchain#2079]
Status Not Synced  Connection Status Connected
Network Name mainnet  Peak Height 3488 
Peak Time 03/20/2021 下午1:33:36  Difficulty 7
VDF Sub Slot Iterations 134217728 Total Iterations 10481257861
Estimated network space 124.922 PiB

09:15:04.936 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

09:15:13.778 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '190.163.219.76', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

09:19:46.553 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\scott.li\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_3721899428.sqlite
09:22:54.472 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by liszechung** [comment]
same here
stuck forever
not sync ing at all

**Comment by Deadlykipper** [comment]
I seem to have this bug, too.  I've got OP's error and then endless loops of disconnects, e.g.

`09:02:10.318 full_node full_node_server        : INFO     Connected with full_node {'host': '78.xxx.xx.115', 'port': 8444}
09:02:10.319 full_node full_node_server        : INFO     -> new_peak to peer 78.xxx.xx.115 cf5...fa4
09:02:10.321 full_node full_node_server        : INFO     -> request_peers to peer 78.xxx.xx.115 cf5...fa4
09:02:10.322 full_node full_node_server        : INFO     Connection closed: 78.xxx.xx.115, node id: cf5...fa4
09:02:10.323 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '78.xxx.xx.115', 'port': 8444}`

**Comment by dorkmo** [comment]
do you have any other peers? what software version are you on?

**Comment by qisikai** [comment]
+1

**Comment by winstonewen** [comment]
i use VPN and problem is solved.

**Comment by marcosyonaware** [comment]
my note is not in farming either, it is in Not Synced after several hours in syccing back to sysncing but does not leave any batch in sync.
What to do?
Here is the configuration:
Plote machine: Lenovo Legion core i7 9ht gen, 32 gb ram, Temp driveSamsumg NMVE Evo 1TB, Samsumg EVO 2TB final drive
Ubuntu 20.10
 
Harvester machine: Raspberry 4 8gb ram
HDD Seagete Barracuda 4TB
Chia 1.1
Ubuntu 20.04

**Comment by hoffmang9** [comment]
For reliable syncing you need to port forward port 8444 - https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
