### ISSUE TITLE
Stupid request

### ISSUE THREAD

**Issue by toxicroadkill** [Chia-Network/chia-blockchain#2086]
Its very minor, but i think others would find this useful, when creating the plot, going through all 4 phases, when it prints the status, prefix the status message with the phase number, would make it a lot easier to see how well it's going...stupid request, but it would be a handy thing

**Comment by boner-cmd** [comment]
In a terminal, you can always just scroll up to see which phase you're in:

![image](https://user-images.githubusercontent.com/54084132/115265482-e474e180-a0fc-11eb-9ee8-ef3d895575a2.png)

Unless you mean printing the phase for every line? That would be a lot of reminders...

**Comment by toxicroadkill** [comment]
I am using a VNC connection so scrolling up, is not a option...decided to do VNC, that way, prevents stupidity of closing the terminal window and it stopping

perhaps a cli option to enable the messages?

the other issue with scrolling up, depending on the terminal, it may have already filled the buffer and not allow scrolling that far back
