### ISSUE TITLE
[BUG] Running failed on centos

### ISSUE THREAD

**Issue by jkkj1630** [Chia-Network/chia-blockchain#2089]
(venv) [centos@localhost chia-blockchain-gui]$ npm run electron

> chia-blockchain@ electron /run/media/centos/0f5d7ee4-6648-41c3-a5aa-a1a5166dd85b/chia-blockchain/chia-blockchain-gui
> electron .

The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
/run/media/centos/0f5d7ee4-6648-41c3-a5aa-a1a5166dd85b/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/centos/.npm/_logs/2021-04-19T05_08_16_136Z-debug.log

**Comment by driversti** [comment]
Same here on Ubuntu 18.06 with LXDM

**Comment by jkkj1630** [comment]
> Same here on Ubuntu 18.06 with LXDM

i try to modify package.json,
set 

    "electron": "electron .",
to 
    "electron": "electron --no-sandbox .",

disable sandbox, it work.
