### ISSUE TITLE
[BUG]  chia wins stopped

### ISSUE THREAD

**Issue by berlef80** [Chia-Network/chia-blockchain#2091]
**Describe the bug**
I was winning chia at a consistent pace since the mainnet launch, and have been adding plots at a steady pace so my % of total networks has remained the same.  I was winning about once a day.  However, since 4/15 I have not won anything.  Still shows 1-5 passing each filter, and the same %, so maybe I just have to be patient, but seems like something is stuck!  Other than see the farming continue in the GUI, is there any thing else I can do to make sure my farm is really farming?

**Comment by jerwamont** [comment]
It was in a json file downloaded on my calendar

**Comment by jerwamont** [comment]
I did not. It was installed on my phone

**Comment by TschiAR** [comment]
Same Here,

Plotting with 26 TB, all Plots checked with powershell, wallets and node synct... no new rewards for 16 days now. no sleep mode or something else with my windows pc.

**Comment by TschiAR** [comment]
> It was in a json file downloaded on my calendar

???

**Comment by jerwamont** [comment]
pycoin/cmds/block.py

**Comment by jerwamont** [comment]
**[](https://github.com/Chia-Network/chia-blockchain/issues/2091#issuecomment-822266143)** https://github.com/Chia-Network/chia-blockchain/issues/2091#issuecomment-822266143

**Comment by jerwamont** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/2091#issuecomment-822266143[](https://github.com/Chia-Network/chia-blockchain/issues/2091#issuecomment-822266143)

**Comment by ddowhy** [comment]
heh you think you have it bad, I've got 170TB plotted and 0 rewards for 6 days straight.  I think something is broken in the code.

**Comment by hoffmang9** [comment]
If you have connected peers and last attempted proofs is about every 10 seconds, current, and the right total plots - you're just unlucky.
