### ISSUE TITLE
XCH rewards stopped for 15 days now!!!!

### ISSUE THREAD

**Issue by TschiAR** [Chia-Network/chia-blockchain#2101]
Good Morning,

today is day 15 without new XCH rewards. 

It suddenly stopped. so i tested all my plots (175 plots by the way) with powershell after i shutted my wallet down. The result shows: all plots are valid and fine.

so i erased all my chia files and started to sync my wallet /node again after rebboting  my pc. i have about 26 TB plots in k33 and k32. 

the wallet and node are synced, all plots are green and farming.

every 10-15 seconds some of my plots are shown by "Last Attempted Proof" (1/175 oder 2/175).

any ideas?

**Comment by banjuessing** [comment]
Have the same since 10 days. Everything seems legit, besides i am getting no proofs found (either non wining or wining) with 560 plots. Tested everthing... Had this twice before for 5 and 7 days. Thought it was just unlucky. But my farm is highly under the statistical expectations.

**Comment by psun888** [comment]
This is a serious concern, can the developers to clarify on this and work with farmers to resolve this problem? 560 plots without a win for 10 days, that's a grave danger for the whole network properly functioning. That might render Chia useless at the best.

**Comment by hoffmang9** [comment]
If you are receiving 64 signage points every 10 minutes and getting a lst attempted proof about every 10 seconds then it is working correctly and you are simply unlucky. Over longer periods luck tends to turn.
