### ISSUE TITLE
[BUG] Foreign wallet conections

### ISSUE THREAD

**Issue by henningrettenmaier** [Chia-Network/chia-blockchain#2106]
**Describe the bug**
`chia show -c`
Returns not only the local wallet connection from 127.0.0.1 but also for foreign IPs

**To Reproduce**
Run command `chia show -c`

Retrieve list of connections.

> Connections:
> Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
> FARMER    127.0.0.1                              38210/8447  9ca38XXX Apr 15 20:28:12      3.8|0.0    
> WALLET    127.0.0.1                              38232/8449  4bd2f2XXX Apr 19 10:34:37     68.5|0.2    
> WALLET    175.10.XXX.XXX                          62719/8449  f24a2dcb... Apr 19 01:40:17      0.1|0.0  

**Expected behavior**
Only local wallet and farmer connection

- OS: Ubuntu Server
- OS Version/Flavor: 20.04 LTS
- CPU: RspPi4

**Additional context**
I xxx'd out the foreign IPs, but usually they come from China.

**Comment by bjrc** [comment]
Send all rep to Gallon press at this wallet (biv1qccga07eq8avxjkwnxs7qh725g7ve7tvwdfucqu)

**Comment by henningrettenmaier** [comment]
Hi had a look into the debug.log file 
`17:43:42.693 full_node full_node_server        : INFO     -> handshake to peer 118.250.1.108 f24a2dc...
17:43:42.696 full_node full_node_server        : INFO     Connection closed: 118.250.1.108, node id: f24a2dc...
17:43:42.698 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '118.250.1.108', 'port': 8449}`

It shouldn't be possible to connect via port 8449 due to the router doesn't forward the port to the PI.

**Comment by byekity** [comment]
> Returns not only the local wallet connection from 127.0.0.1 but also for foreign IPs

I am having the same issue. Mine are from Russia. Is this just a bug to ignore should we be worried about safety of our wallets? Did you find any explanation or solution?
