### ISSUE TITLE
[BUG] Plotting stuck at 100%

### ISSUE THREAD

**Issue by Metal-joker** [Chia-Network/chia-blockchain#2108]
**Describe the bug**
Plotting stuck at 100%

**To Reproduce**

1. Go to 'plot'
2. Click on 'add a plot'
3. plot 8 plot in parallel
4. plotting
5. stuck at 100%, even system also freezes

**Expected behavior**
successfully plot

**Screenshots**
can't do a screenshot cause TeamViewer stuck and ubuntu also freeze

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- OS Version/Flavor: 18.04
- CPU: AMD 3800x
- SSD: 2*3.84t Intel D7-P5510
- RAM: 4*32G DDR4
- HDD: 1*6T WD HDD

**Additional context**
Happened twice, One is 2 plots in parallel, one 12 plots in parallel, one 8 plots in parallel.

Help plz.

**Comment by trop-joe** [comment]
Have you checked the plot creation log? I found mine was stuck on 100% and trying to copy a finished plot from the temp directory to the destination. Because my permissions on the destination were wrong it was getting an error every 5 minutes when it tried to copy. I changed the ownership/permission on the destination and the next time the 5 minutes came up it copied them properly.

**Comment by shadowzerro** [comment]
Had similar issues stuck at 100% plotting. I checked the view log and the last line said: "Final file size:101.420 Gib." The file was copied to the PLOT drive but it was .tmp file not .plot file. 😣

**Comment by trop-joe** [comment]
Just remove the .tmp which will leave it as a .plot and it should be just fine.

**Comment by Metal-joker** [comment]
I figure out this, I ran 16 plots in parallel without stagger so when it's done, HDD io speed drags down CPU. wait longer and everything will be just fine. closing this.

**Comment by zedzara** [comment]
> Have you checked the plot creation log? I found mine was stuck on 100% and trying to copy a finished plot from the temp directory to the destination. Because my permissions on the destination were wrong it was getting an error every 5 minutes when it tried to copy. I changed the ownership/permission on the destination and the next time the 5 minutes came up it copied them properly.

hey joe! could you expand on how to change the permission on the destination? It may be a really simple task, but for now I'm not clear what you mean by that!
thank you!
