### ISSUE TITLE
"13"

### ISSUE THREAD

**Issue by SanceTb** [Chia-Network/chia-blockchain#2112]
The system is Windows 10 Pro 21H1 64bit.
it worked good, and suddenly, it shows "connecting to the wallet." Then I exit and restart it. Now it makes a pop-up window and displays "13." it might be an error code I guess?

**Comment by SanceTb** [comment]
here is a link of the [screenshot](http://www.sance.xyz/wp-content/uploads/2021/04/QQ截图20210419104202.png).
I click "ok", and then find all plots disappear. the file is still in the drive, but when I try to add it into the software, it displays "13" again. I tried to reinstall the software but it does not help.

**Comment by Jimmyguy** [comment]
I got same issue today... @@"

**Comment by hoffmang9** [comment]
You have an error in the plots section of your config.yaml.
