### ISSUE TITLE
请立刻停止该项目，破坏电脑硬件市场价格

### ISSUE THREAD

**Issue by ppjjzz** [Chia-Network/chia-blockchain#2113]
浪费资源，炒高电脑硬件市场价格，呼吁大家一起抵制

**Comment by litai686** [comment]
顶一个

**Comment by Jasonwu123** [comment]
希捷：啊西呀，隔壁A和I还有N，乘着这波挖矿，卖得老火了，哎，自从固态出来后，我两都快活不下去了，咋办啊？
西数：啊希呀，别慌，我已经想到办法了，既然cpu能挖矿，内存能挖矿，显卡能挖矿，那硬盘就为什么不能挖矿呢？对吧
希捷：啊西啊，你他娘真是人才啊，好啊，真真真是好啊，这样，BT的创始人最近不是也在搞chia项目吗？要不咱两过去跟唠唠嗑？
。。。

**Comment by xyk1993** [comment]
有些人一仓库的硬盘就是不放货，哎，就是憋着，我不卖，哎，就是玩。。。。。

**Comment by hoffmang9** [comment]
有些人一仓库的硬盘就是不放货，哎，就是憋着，我不卖，哎，就是玩。。。。
