### ISSUE TITLE
Runtime error: bad allocation

### ISSUE THREAD

**Issue by poutika974** [Chia-Network/chia-blockchain#2114]
hello I am new to the chiacoin project, I tried to launch my first plot but I still have an error message after a certain percentage. can you help me?

![image](https://user-images.githubusercontent.com/82810822/115221171-ae8a2a00-a109-11eb-8bb6-94d99c1b4596.png)

**Comment by never-afk** [comment]
I got same error，any help?

**Comment by hoffmang9** [comment]
This is a problem with your RAM - either software or hardware.
