### ISSUE TITLE
OMG, I have synced for two days!!![BUG]

### ISSUE THREAD

**Issue by NirHeaven** [Chia-Network/chia-blockchain#2120]
![image](https://user-images.githubusercontent.com/22441230/115232107-f1b7bd80-a148-11eb-9c4e-46b71b91de02.png)
![image](https://user-images.githubusercontent.com/22441230/115232171-01370680-a149-11eb-99d6-a8a48a2a62d0.png)

please help me!

**Comment by litcloud** [comment]
I have the same issue with 1.05 in both Win10 and Ubuntu 20.04. In win10 the console says below errors:
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Administrator/AppData/Local/chia-blockchain/app-1.0.5/resources/app.asar/build/renderer/js/441.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Administrator/AppData/Local/chia-blockchain/app-1.0.5/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

**Comment by NirHeaven** [comment]
> I have the same issue with 1.05 in both Win10 and Ubuntu 20.04. In win10 the console says below errors:
> DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Administrator/AppData/Local/chia-blockchain/app-1.0.5/resources/app.asar/build/renderer/js/441.js.map: Unexpected end of JSON input
> DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Administrator/AppData/Local/chia-blockchain/app-1.0.5/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

Have you fixed it?

**Comment by litcloud** [comment]
> > I have the same issue with 1.05 in both Win10 and Ubuntu 20.04. In win10 the console says below errors:
> > DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Administrator/AppData/Local/chia-blockchain/app-1.0.5/resources/app.asar/build/renderer/js/441.js.map: Unexpected end of JSON input
> > DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Administrator/AppData/Local/chia-blockchain/app-1.0.5/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input
> 
> Have you fixed it?

Not yet. But found something interesting, below is the debug.log:
23:24:12.023 wallet chia.wallet.wallet_state_manager: WARNING  Starting in db path: C:\Users\Administrator\.chia\mainnet\wallet\db\blockchain_wallet_v1_mainnet_2128084581.sqlite
23:24:12.493 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
23:24:19.572 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

**Comment by hickeroar** [comment]
I also have been unable to connect & sync for days with 1.0.5. I'm not sure if I should be downgrading or something else? 1.0.5 is just not working properly, and who knows how many blocks I've missed out on winning in that amount of time.

**Comment by mariano54** [comment]
You need to do port forwarding, please check the wiki FAQ.

**Comment by hickeroar** [comment]
> You need to do port forwarding, please check the wiki FAQ.

I don't need to do port forwarding, and I don't need to read the WIKI. I've been doing this since before launch day, and this just started two days ago. A few days ago loads of people in the discord I'm in all started having the same issue. We're all having a horrible time trying to connect and sync. Nothing was awry until then. There's something wrong...

**Comment by hoffmang9** [comment]
Exponential growth is making it hard to find open nodes. So you have to open your node and if you don't other nodes can't find you.
