### ISSUE TITLE
Since yesterday(18/04/2021) plotting does not use up 100% CPU anymore. 

### ISSUE THREAD

**Issue by ssstev** [Chia-Network/chia-blockchain#2124]
No settings changed compared to previous successful plots, which, when plotting uses pretty much 100% CPU and completes at decent speed.

Today (19th April) CPU and disk are all showing low usage in task manager. Especially CPU which is consistently sitting under 50%. I have made sure:
Disk running at full speed
CPU running very cool at full speed

Not sure what's the problem considering I did not alter any hardware, now plotting is at least two times longer

**Comment by xillkoi** [comment]
yes, my r9 5950x need 1 days,plot 7 files

**Comment by ssstev** [comment]
turns out my first plot went very weird and gave a completely wrong first impression
