### ISSUE TITLE
Estimated Time to Win  Not Available

### ISSUE THREAD

**Issue by modiqitian** [Chia-Network/chia-blockchain#2127]
How can I solve it? My farmland list shows the following:
Estimated Time to Win,Not Available,Wait for synchronization.

"Your Full Node Connection","Your Harvester Network"Show all connected.

**Comment by hoffmang9** [comment]
You have to get in sync to farm.

**Comment by modiqitian** [comment]
> 您必须同步到服务器场。

Thanks, but I don't know how to do this yet.
