### ISSUE TITLE
Failed to open (invalid plots)[BUG]

### ISSUE THREAD

**Issue by jusfbi** [Chia-Network/chia-blockchain#2130]
Failed to open (invalid plots)
These plots are invalid, you might want to delete them.

Filename | Action
-- | --
\\192.168.0.121\CHIA\DASS\plot-k32-2021-04-07-20-12-700000b1fe8094b9d704a0eb955c0bf3d6cb69754d18769be3e750f520151a91.plot |  
\\192.168.0.121\CHIA\DASS\plot-k32-2021-04-07-20-42-0a8e3370d8cc838bb684103ba921488eb4c5db92396231b283c868d4bddba5c4.plot |  
\\192.168.0.121\CHIA\DASS\plot-k32-2021-04-07-21-12-07bf5e190fdc60e8c6b85d9e51ceae917c3369c01ec14bbdaf001e5a01e88e6b.plot |  
\\192.168.0.121\CHIA\DASS\plot-k32-2021-04-08-09-01-3111fe34edd9085da5c73d10718bf24a1a8ed5856f2ac535e1eef2b36f1595c2.plot |  
\\192.168.0.121\CHIA\DASS\plot-k32-2021-04-08-09-31-f2861b053275cf7c1d8285a05af8f96c9539b7ef297e06685c28739842967155.plot |  
\\192.168.0.121\CHIA\DASS\plot-k32-2021-04-08-10-01-36960b6ce63fc28563cc89ab73353e96df35682b83501499ec2986d9592d7311.plot |  
\\192.168.0.121\CHIA\DASS\plot-k32-2021-04-08-18-52-c07028ed0e604c42abd4c72bb09681ac61c9148b6d5618a3c77bb230dc3ccf23.plot
When my chia blockchian closed and open again these plots not work 
BUT  THE HPOOL-CHIA-MINER CAN open it and work

**Comment by wolzche** [comment]
me too, the same problem after restart the computer
