### ISSUE TITLE
[BUG] Data Transfer is 0 for Nodes even hours of Farming

### ISSUE THREAD

**Issue by erwinpgo** [Chia-Network/chia-blockchain#2131]
**Describe the bug** 

**Issue#1**: Farm Tab / Advanced Option:
“Your Full Node Connection” has a Connection Status: Connected but the MiB Up/Down is always 0.0/0.0
I am already running 2 plots for 12 hours but still at 0 Data transfer (Do I need to expect for this to have at least small data transfer and is this considered a bug?)

**Issue#2:** Full Node Tab / Connections:
Connection Type “Farmer” and “Wallet” has only upload data transfer for 12 hours of farming.

Date/Time of Farming: April 19 00:00 to 12:00 (UTC)

....
 Plot Count: 2 Farming, 1 Plotting, 9 Queue
RAM Size of Plots: 3390MiB
K-Size: K-32, 101.4GiB

**To Reproduce** 
Steps to reproduce the behavior of Issue #1:
1. Go to ‘Farm’ tab
2. Click on 'Show Advanced Option'
Screenshot of the problem under “Farm Tab”:
![image](https://user-images.githubusercontent.com/76909621/115258863-f342af00-a163-11eb-873f-c635fa9c2962.png)

Steps to reproduce the behavior of Issue #2:
1. Click on ‘Full Node’ tab
2. See under ‘Connections
Screenshot of the problem under “Full Node Tab”:
![image](https://user-images.githubusercontent.com/76909621/115258924-02296180-a164-11eb-8e49-e690b4affb5b.png)

**Expected behavior** 
Plots should have transfer at least small Upload and Download of ‘Full Node’ tab and ‘Farm’ tab.

Desktop (please complete the following information):
* OS/Version: Windows 10 Home
* CPU: 3.7 GHz Intel Core i3-4170 with 8GB Ram

**Additional context** 
I have issue in syncing yesterday (April 18 UTC) for whole day and I tried experimenting on my router’s “Forwarding Rules” by adding “IPv4 Port Mapping”.
Screenshot of Modem’s Port Forwarding setup:
![image](https://user-images.githubusercontent.com/76909621/115259108-2d13b580-a164-11eb-8a63-83ee4db42205.png)

Not sure if this  additional setup on the router made the syncing worked again. But I have Issue#1 under “Farm” tab which I only noticed today wherein the UP/DL data transfer of “Full Node Connection” with port 8444 is still 0 for 12 hours of farming (Same with “Harvester Network” with port 49743/8448).

Additional Logs under “Developer Tools” after starting up Chia App for reference:
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Win/AppData/Local/chia-blockchain/app-1.0.5/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

**Comment by AquilusZero** [comment]
Same problem for me, i have a flux in upload but not for download, i have open 8444 in the page of the router and in windows firewall. Always only one connection!

<img width="248" alt="Cattura" src="https://user-images.githubusercontent.com/8516154/116045508-65d6f180-a672-11eb-9156-f46eb07d2e8c.PNG">

<img width="137" alt="chia" src="https://user-images.githubusercontent.com/8516154/116045546-6e2f2c80-a672-11eb-96a1-cfe17660aef8.PNG">
