### ISSUE TITLE
Issues related to mining pool development

### ISSUE THREAD

**Issue by HaiChecker** [Chia-Network/chia-blockchain#2133]
If I want to develop such a mining pool, it is currently not supported, right?

**Comment by HaiChecker** [comment]
hpool violates the principle, so there is currently no standard mining pool protocol, right?

**Comment by hoffmang9** [comment]
Official pooling support is coming in late May https://chia.net/2020/11/10/pools-in-chia.html

**Comment by jcodic** [comment]
Do we need to replot all hdds to switch to pools later? Or existing plots k32 are good to go?
