### ISSUE TITLE
Windos 10 "Not Synced" for 1.05 chia [BUG]

### ISSUE THREAD

**Issue by Derek-Kun** [Chia-Network/chia-blockchain#2134]
I  added a plot successfully, but the status is "Not Available",  Then I found my  Node Status is "Not Synced",  the peak time is 04/14/2021, 11:55:38 , peak height is 129219,  is there anyone can fix this issue ?

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-is-my-wallet-not-synced-why-can-i-not-connect-to-wallet-from-the-gui

https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#i-am-seeing-blocks-and-connections-but-my-node-says-not-synced

**Comment by jkkj1630** [comment]
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-is-my-wallet-not-synced-why-can-i-not-connect-to-wallet-from-the-gui
> 
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#i-am-seeing-blocks-and-connections-but-my-node-says-not-synced

I tried all the methods and it didn't solve the problem

**Comment by dorkmo** [comment]
youre still behind the current peak. do you have any nodes in your connections list? you might need to use port forwarding. it can take a while to fully sync, how long have you been waiting?
