### ISSUE TITLE
install timelord with python 3.8

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/chia-blockchain#214]
With 1.0beta5

> python -V
Python 3.8.2

> cd /opt
> git clone https://github.com/Chia-Network/chia-blockchain
> cd chia-blockchain
> sh install.sh
> . ./activate
> chia init
> sh install-timelord.sh

then you you end up with a broken link vdf_bench pointing to Python 3.7 instead of 3.8
> ls -l
vdf_bench -> venv/lib/python3.7/site-packages/vdf_bench

The script install-timelord.sh has Python version 3.7 hard-coded in it, lines 27, 36 and 43. Can that be made parameterized?

> ln -s venv/lib/python3.8/site-packages/vdf_bench -f

Addresses the issue

**Comment by hoffmang9** [comment]
Fix coming in beta 1.6

https://github.com/Chia-Network/chia-blockchain/commit/b61d09f5398a2a258c7ae281d26710742554cd3f#diff-edf49b75ab62aa4036280584d81912ab
