### ISSUE TITLE
How to autostart chia in ubuntu 20.04 

### ISSUE THREAD

**Issue by Daeamon** [Chia-Network/chia-blockchain#2151]
- OS: Ubuntu
- OS Version/Flavor: Ubuntu 20.04

Hello, how to correctly autostart chia for synch and farming in Ubuntu 20.04 without logon

**Comment by aqk** [comment]
Hello!

Here is an article I found very helpful:
https://askubuntu.com/questions/9382/how-can-i-configure-a-service-to-run-at-startup

Note that `chkconfig` is no longer used in Ubuntu, so you can ignore articles about that.

Another thing you can search for is `crontab`

https://www.cyberciti.biz/faq/linux-execute-cron-job-after-system-reboot/
