### ISSUE TITLE
Ubuntu 20.04 Crash After Launching chia-blockchain-gui [BUG]

### ISSUE THREAD

**Issue by Daeamon** [Chia-Network/chia-blockchain#2158]
**Describe the bug**
After launching chia-blockchan-gui on Ubuntu 20.04 system crashed.

**To Reproduce**

1. Open terminal
2. Run commands below
```
cd chia-blockchain
. ./activate
cd chia-blockchain-gui
npm run electron &
```
**Expected behavior**
System stuck without any responses

**Desktop:**
- OS: Linux
- OS Version/Flavor: Ubuntu LTS 20.04
- CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
- Hypervisor: ESXi-6.5.0-20170104001-standard

**Comment by Daeamon** [comment]
Presumably the problem is with the package xorgxrdp.

**Comment by oeeckhoutte** [comment]
Hello guys, same issue for me on Ubuntu 20. There is no particular error in logs...

**Comment by anban4u** [comment]
i am seeing my ubuntu continuously crashing at 2% plotting. Investigating if its a overheat issue.

Has anyone else the computer crashes on linux?

**Comment by Daeamon** [comment]
> i am seeing my ubuntu continuously crashing at 2% plotting. Investigating if its a overheat issue.
> 
> Has anyone else the computer crashes on linux?

I'm tryinguse Debian distributive and it work fine

**Comment by anban4u** [comment]
Thank for the quick reply. Issue was with my hardware.

**Comment by KeyMyran** [comment]
> **Describe the bug**
> After launching chia-blockchan-gui on Ubuntu 20.04 system crashed.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open terminal
> 2. Run commands below
> 
> ```
> cd chia-blockchain
> . ./activate
> cd chia-blockchain-gui
> npm run electron &
> ```
> 
> **Expected behavior**
> System stuck without any responses
> 
> **Desktop:**
> 
> * OS: Linux
> * OS Version/Flavor: Ubuntu LTS 20.04
> * CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
> * Hypervisor: ESXi-6.5.0-20170104001-standard

not root priv start  or add --no-sandbox
