### ISSUE TITLE
restarting macos app/ui brings up password prompt[BUG]

### ISSUE THREAD

**Issue by martyschoff** [Chia-Network/chia-blockchain#2166]
**Describe the bug**

since i never gave macos app a password, only the word key, i now have lost access to the client/chia

**To Reproduce**

exit and restart app

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

macos

- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by hoffmang9** [comment]
The password it is asking for is to the MacOS keyring and is thus your mac login password.

**Comment by martyschoff** [comment]
sorry to be a noob

by your response, i believe you are saying this is legitimate.
though i've never seen this (gui'ed) style of request from my mac

but it also doesn't accept that password

which made it more odd
