### ISSUE TITLE
[BUG] GUI cannot see SMB drive

### ISSUE THREAD

**Issue by WyattLiu** [Chia-Network/chia-blockchain#2171]
**Describe the bug**
Using Xubuntu 20.04, while selecting the paths in the GUI, only "On This Computer" Tab is available in the GUI pop-up.
Tried to switch file manager, file manager on the side can browse the SMB share I have.

**Screenshots**
If applicable, add screenshots to help explain your [problem.](url)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Xubuntu 20.04 LTS
- CPU: 3700X

**Comment by NerfWhatKilledMe** [comment]
I really need an answer to this prblem
