### ISSUE TITLE
[BUG]Chia farming status "Earning beer money" ver1.0.5(win). Not mining?

### ISSUE THREAD

**Issue by headware** [Chia-Network/chia-blockchain#2172]
**Describe the bug**
Node status showing "Synced, earning beer money", and Farming status is "Earning beer money".  No mining status updated on the "Farm" tab.  “Estimated Time to Win” shows "2 years" with hint "you have 0.0000% space on the network ...".

![Snipaste_2021-04-20_16-17-46](https://user-images.githubusercontent.com/9377208/115346815-043b0100-a1f4-11eb-893a-0c8d82ea4336.png)

**Desktop **
- OS: Windows
- OS Version/Flavor: Win 10 Pro
- CPU: i7 16G memory
- Disk 12T

**Comment by hoffmang9** [comment]
![image](https://user-images.githubusercontent.com/30377676/115358769-d6fa3e80-a172-11eb-8325-929ef9748c4e.png)

![image](https://user-images.githubusercontent.com/30377676/115358744-d06bc700-a172-11eb-8d29-c28564ce4b82.png)

You have accidentally set your GUI to English (Australian). Change it to English.

**Comment by headware** [comment]
Thanks. It turned to "Farming" after change language. But is it normal to show: “Estimated Time to Win” shows "2 years" with hint "you have 0.0000% space on the network ..."?

**Comment by dorkmo** [comment]
it shows you have 1 plot. if you divide 101.387 / 401,578,000 = close to zero . all reqards are relative to total size of network space
