### ISSUE TITLE
Ports used by farmer not documented

### ISSUE THREAD

**Issue by actuallymentor** [Chia-Network/chia-blockchain#2178]
Based on the documentation I pieced together that my firewall should allow for `8444`, but when I ran `sudo lsof -i -P -n | grep LISTEN` I noticed that the farmer used `8447` as well.

For those of us that use a firewall:

1. What are all needed ports for successful farming?
2. Shall I make a PR against the Wiki with this info?

**Comment by dorkmo** [comment]
that might only be between the node and farmer... but worth having it well documented

**Comment by actuallymentor** [comment]
The listener is on `*:8447` as opposed to the internal `127.0.0.1:*` listeners. Hence my hesitation in dismissing it.
