### ISSUE TITLE
Where is the function to issue XCH? I want to see what mechanism Chia uses to issue XCH?

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#2182]

**Comment by hoffmang9** [comment]
Are you asking about how coinbase rewards work or the tokenomics?

**Comment by qian-fei** [comment]
> Are you asking about how coinbase rewards work or the tokenomics?

I want to know the reward cycle?

**Comment by qian-fei** [comment]
> Are you asking about how coinbase rewards work or the tokenomics?

The actual time of XCH is different from the estimated time. I want to know the details?

**Comment by qian-fei** [comment]
> Are you asking about how coinbase rewards work or the tokenomics?

For example, the official estimate is five hours to reward, sometimes two hours to reward, but sometimes eight hours to reward

**Comment by hoffmang9** [comment]
The target difficulty is to have 4608 blocks per 24 hours. Since space is growing nearly 40% per week, it is accelerating the daily blocks by about 8% before the difficulty reset that happens each 4608 blocks.

**Comment by qian-fei** [comment]
> The target difficulty is to have 4608 blocks per 24 hours. Since space is growing nearly 40% per week, it is accelerating the daily blocks by about 8% before the difficulty reset that happens each 4608 blocks.

Sorry, I don't quite understand. Can you explain it in detail, or tell me where this part is implemented in the source code

**Comment by qian-fei** [comment]
> The target difficulty is to have 4608 blocks per 24 hours. Since space is growing nearly 40% per week, it is accelerating the daily blocks by about 8% before the difficulty reset that happens each 4608 blocks.

There is an error between the actual reward time and the official estimated time. What causes this part of the error?

**Comment by qian-fei** [comment]
> The target difficulty is to have 4608 blocks per 24 hours. Since space is growing nearly 40% per week, it is accelerating the daily blocks by about 8% before the difficulty reset that happens each 4608 blocks.

I currently have about 400t, sometimes XCH in three hours, sometimes XCH in one hour

**Comment by qian-fei** [comment]
> The target difficulty is to have 4608 blocks per 24 hours. Since space is growing nearly 40% per week, it is accelerating the daily blocks by about 8% before the difficulty reset that happens each 4608 blocks.

Help me!

**Comment by hoffmang9** [comment]
That variance is natural luck.
