### ISSUE TITLE
[BUG] Process killed - Computing table 4

### ISSUE THREAD

**Issue by mdtanrikulu** [Chia-Network/chia-blockchain#2185]
**Describe the bug**
When try plotting on RPI 4, process killed always on same spot. I couldn't find much info, only this;

```bash
Computing table 4
        Bucket 0 QS. Ram: 1.940GiB, u_sort min: 3.250GiB, qs min: 0.813GiB. force_qs: 0                                                                                
        Bucket 1 uniform sort. Ram: 1.940GiB, u_sort min: 1.625GiB, qs min: 0.812GiB.                                                                                  
Killed
```
 
**To Reproduce**
Run plotting on RPI 4 4GB version. 

**Expected behavior**
It should continue plotting.

- OS: [e.g. Linux]
- OS Version/Flavor: Debian GNU/Linux 10 (buster)
- CPU: ARM Cortex-A72

**Comment by hoffmang9** [comment]
This is usually the OS killing the process as it thinks it's about to run out of memory.

**Comment by mdtanrikulu** [comment]
Thank you for pointing that out. Decreasing memory with `-b` flag solved the issue.
