### ISSUE TITLE
[BUG] wallet_server exception during starting the client

### ISSUE THREAD

**Issue by hcieslewicz** [Chia-Network/chia-blockchain#2188]
**Describe the bug**
During starting client there is an exception in logs for the wallet_server. This could be a reason why my client is not synced and why I can't add manually any peer.
Chia version: 1.0.5

**To Reproduce**
1. Start Chia.exe client
2. Check log located at C:\Users\hubert\.chia\mainnet\log\debug.log

> 11:56:18.918 wallet wallet_server              : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 519, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError
11:56:18.920 wallet wallet_server              : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 353, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 989, in create_connection
  File "asyncio\base_events.py", line 1017, in _create_connection_transport
concurrent.futures._base.CancelledError

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10

**Additional context**
I tried to delete wallet db ( https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-is-my-wallet-not-synced-why-can-i-not-connect-to-wallet-from-the-gui ), but it didn't help.

**Comment by InB4DevOps** [comment]
Same problem here with Windows 10.

**Comment by VII-kral** [comment]
Having exactly the same, sometimes syncing starts for few minutes then drops. 
Tried
App restart, reinstall, (also deleted from %appdata%)
windows reinstall
different network

nothing worked so far... plotting is working tho

**Comment by InB4DevOps** [comment]
> Having exactly the same, sometimes syncing starts for few minutes then drops.
> Tried
> App restart, reinstall, (also deleted from %appdata%)
> windows reinstall
> different network
> 
> nothing worked so far... plotting is working tho

Are you having this problem when trying to connect a harvester to a full node? That's my problem here..

**Comment by VII-kral** [comment]
I think I am a bigger noob than I expected... I am not sure, I am also plotting on the same device and using windows GUI.
Btw after a few hours of restartnig it started to connect to peers. Now still syncing. 
I have also the client running on another device where the syncing staryed roughly at the same time (also still syncing).
