### ISSUE TITLE
Configurable or dynamic rpc_host

### ISSUE THREAD

**Issue by freddiecoleman** [Chia-Network/chia-blockchain#219]
There is currently an issue when running a chia node with the rpc server in a docker container. It is [hard coded to listen on localhost](https://github.com/Chia-Network/chia-blockchain/blob/0eae1e0a6b9ad3dd0d12e5892a9089b16c20f190/src/rpc/rpc_server.py#L277).

<img width="1438" alt="Screenshot 2020-05-15 at 07 08 20" src="https://user-images.githubusercontent.com/4749434/82017402-fa6f5c00-967a-11ea-83fa-f78ebc8049df.png">

This is based on one of the main [ubuntu images](https://github.com/freddiecoleman/docker-chia/blob/master/Dockerfile#L1) and the `/etc/hosts` it is like this:

<img width="450" alt="Screenshot 2020-05-14 at 22 39 01" src="https://user-images.githubusercontent.com/4749434/81988742-dfc5c480-9633-11ea-97f5-1061a333d13e.png">

`localhost` is `127.0.0.1` which is the host machine and fails. I have given my container a hostname of `chia`.

I think there are two potential ways to fix this;

- Work out the hostname/ip of the container instead of having a hardcoded `localhost`
-  Ability to configure `rpc_host` in `config.yaml`

**Comment by freddiecoleman** [comment]
I have hacked my way around this issue by using `sed` to replace `localhost` with `chia` in the docker image https://github.com/freddiecoleman/docker-chia/commit/0536a0eefc8ee1dee86bc28d29fa326f93772ffd#diff-3254677a7917c6c01f55212f86c57fbfR15

I then use nginx for access from the host machine:

```
upstream chia_rpc {
    server chia:8555;
}

server {
    listen 80;

    access_log      /var/log/nginx/development.access.log;
    error_log       /var/log/nginx/development.error.log;

    proxy_set_header X-Forwarded-For "";

    location /chia/ {
        resolver 127.0.0.11 ipv6=off;
        proxy_pass  http://chia_rpc/;
        proxy_set_header        Host            $host;
    }
}
```

Not ideal but works for now.

**Comment by hoffmang9** [comment]
However your point is well taken and we'll try to address it in this or the next release.

**Comment by freddiecoleman** [comment]
The same issue affects the rpc client here https://github.com/Chia-Network/chia-blockchain/blob/2fc2caf2a7f982f4f87eaf2070fdba033cbab9e9/src/rpc/rpc_client.py#L29

This is an issue when using scripts that run commands such as netspace which use the rpc client from within a docker container.

**Comment by freddiecoleman** [comment]
Been playing around on dev branch. These are the following places currently affected by the issue;

```
src/daemon/client.py - 127.0.0.1
src/daemon/server.py - localhost
src/rpc/abstract_rpc_server.py - 127.0.0.1 AND localhost
src/wallet/websocket_server.py - 127.0.0.1
src/server/server.py - host=None
```

**Comment by mariano54** [comment]
Ah this is a very good point. At the very least, we can have a variable in the config file that is:
localip: 127.0.0.1 (or localhost)
And use that everywhere as opposed to hardcoding the ip address.
Docker users can change that config file. Or is there an easy way to detect the ip for a docker container?

**Comment by freddiecoleman** [comment]
Closing as this has been fixed in the next release. Thanks guys.
