### ISSUE TITLE
[BUG] Not Synced in testnet 

### ISSUE THREAD

**Issue by sibitha-bijesh** [Chia-Network/chia-blockchain#2192]
I connected to testnet as described in #1954 .  but my GUI still showing not synced after 15 min. F

FYI: I am in main branch.  I run these commands 

````
git checkout main
git pull
sh install.sh
. ./activate

CHIA_ROOT="~/.chia/testnet" chia init
# Change selected network
CHIA_ROOT="~/.chia/testnet" chia start all

sh install-gui.sh

cd chia-blockchain-gui
npm run electron &
````

**Comment by weisnc** [comment]
![image](https://user-images.githubusercontent.com/8621713/115402654-2ea1b400-a21e-11eb-8abb-35501744dbf8.png)

I have the same issue

**Comment by jkkj1630** [comment]
i have same issue,how can i do?

**Comment by dorkmo** [comment]
do you guys want to be on the testnet or the real mainnet? you gotta checkout 1.0.5, dont use main

**Comment by sibitha-bijesh** [comment]
@jkkj1630  I did port forwarding and it starts to sync

**Comment by aqk** [comment]
Make sure you are using port 58444 in your config, and that you are on a new enough branch.

When testnet is updated with a breaking change, all the updated clients leave, and you are in an empty room, by yourself.

https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#testnets

**Comment by github332638015** [comment]
@sibitha-bijesh How do I do port forwarding?

**Comment by github332638015** [comment]
@sibitha-bijesh How do I do port forwarding? Before you can synchronize
