### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aboyit** [Chia-Network/chia-blockchain#2193]
![image](https://user-images.githubusercontent.com/20743425/115406089-0c596780-a219-11eb-9bed-0a0507ffa254.png)

**Comment by dorkmo** [comment]
looks like you ran out of RAM

**Comment by aboyit** [comment]
> e

thank you ,i'm trying again

**Comment by mariano54** [comment]
Check your ram also, sometimes you have bad ram
