### ISSUE TITLE
[BUG] [Resolved]    failed to sync after 6 hours 

### ISSUE THREAD

**Issue by GoPerry** [Chia-Network/chia-blockchain#2194]
I would strongly recommend one button to start syncing from the GUI.
I have four systems mining, 3/4 system has problem to sync after a few hours 

I cannot stop and reboot the system, there are some ploting task 40% progress.

How can i fix the syncing issue from the mainnet?

**Comment by leidie123a** [comment]
我也一样 半个小时都没有同步 状态一直都是未同步 不工作！该怎么解决呢？
![360截图20210420220351481](https://user-images.githubusercontent.com/82888881/115409672-8cd19580-a224-11eb-80e8-fcb71a9239ad.jpg)

**Comment by mfoglio** [comment]
Same for me.

**Comment by dorkmo** [comment]
make sure you have port forwarding enabled on your router

**Comment by leidie123a** [comment]
> 确保您的路由器上启用了端口转发

之前都好好的  今天重启了电脑就不行了！之前可以同步的  也已经同步完成 下午开始 就无法同步了！

**Comment by hcieslewicz** [comment]
Same for me. Port 8444(tpc) is forwarded, upnp enabled.

**Comment by WyattLiu** [comment]
Same issue. Does it have something to do with NAT? basically, we cannot have more than 1 node in the same subnet

**Comment by jdelgadoesteban** [comment]
same issue here.

**Comment by ZwaZo22** [comment]
Same here. Was working fine until couple of days ago.

**Comment by GoPerry** [comment]
Hello Guys.
I read the README doc, and I  have found one workaround to fix this.
Because I aready have one Node in the local network which has finished syncing
So I connect my another system which cannot sync to this GOOD node with 8444 port

You can use  "CONNECT TO OTHER PEERS" to fix the sync issue.

It works for me .

COOL.

You can have a try if you have the same issue and one good Node.

**Comment by GoPerry** [comment]
> Same issue. Does it have something to do with NAT? basically, we cannot have more than 1 node in the same subnet

I have 5 nodes in the local network with subnet IP 192.168.1.xxx
All nodes can sync now .

**Comment by berlef80** [comment]
> Hello Guys.
> I read the README doc, and I have found one workaround to fix this.
> Because I aready have one Node in the local network which has finished syncing
> So I connect my another system which cannot sync to this GOOD node with 8444 port
> 
> You can use "CONNECT TO OTHER PEERS" to fix the sync issue.
> 
> It works for me .
> 
> COOL.
> 
> You can have a try if you have the same issue and one good Node.

Can you explain how to do this using the GUI?  how do I port forward?

**Comment by mariano54** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by GoPerry** [comment]
> > Hello Guys.
> > I read the README doc, and I have found one workaround to fix this.
> > Because I aready have one Node in the local network which has finished syncing
> > So I connect my another system which cannot sync to this GOOD node with 8444 port
> > You can use "CONNECT TO OTHER PEERS" to fix the sync issue.
> > It works for me .
> > COOL.
> > You can have a try if you have the same issue and one good Node.
> 
> Can you explain how to do this using the GUI? how do I port forward?

I believe that you have known how to add peer nodes to sync ..
