### ISSUE TITLE
Not Synced and connecting to wallet 

### ISSUE THREAD

**Issue by gokhan174** [Chia-Network/chia-blockchain#2200]
**Describe the bug**
not connecting and  Not Synced

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/82893478/115422220-5df7f700-a205-11eb-8143-ce234d13983e.png)
![2](https://user-images.githubusercontent.com/82893478/115422321-77993e80-a205-11eb-8f7c-84c888b83983.png)

**Desktop (please complete the following information):**

- OS: [win 10 x64 ]
- OS Version/Flavor: 20H2   19042.928
- CPU: [Amd R7 2700x ]
- Ram ddr4 16 gb 3200 mhz

**Additional context**

not connecting and  Not Synced

**Comment by dorkmo** [comment]
are you connected to any nodes? is your port 8444 forwarded on your network router settings?

**Comment by Bouldouklu** [comment]
Exactly same issue for me as well..

**Comment by GoPerry** [comment]
same issue for me
I have another system in the local network which can sync well.

**Comment by wanghongqi8548488** [comment]
This will take time to wait slowly

**Comment by gokhan174** [comment]
> are you connected to any nodes? is your port 8444 forwarded on your network router settings?

No.
![Adsızs](https://user-images.githubusercontent.com/82893478/115431817-63a60a80-a20e-11eb-9a4a-10b6fc3d92df.png)

**Comment by leidie123a** [comment]
和我一样！！

**Comment by EvgeniyKorepov** [comment]
Same problem. It appeared a few hours ago. Before that everything worked fine

**Comment by EvgeniyKorepov** [comment]
After several hours of downtime, one node appeared and synchronization began
![image](https://user-images.githubusercontent.com/35364901/115439931-ca7bf180-a217-11eb-8644-497ee1e23c6e.png)

**Comment by dorkmo** [comment]
cherish that node and treat it right

**Comment by jdelgadoesteban** [comment]
Exactly the same issue for me since I upgraded to 05.

**Comment by dorkmo** [comment]
you might try to connect to that node that evgeniy just posted?

**Comment by handsomedude** [comment]
I had that. Shut it down and opened it again and it resumed syncing. It's fine now

**Comment by VII-kral** [comment]
Adding 35.80.8.179 to peers helped me. After you add it should show as introducer ... I guess it is a server which introduce you to oyher peers/full nodes... i duuno I am kind of a noob

**Comment by mariano54** [comment]
Do port forwarding, or upnp, or you will keep going out of sync:
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
