### ISSUE TITLE
[BUG] "chia farm summary" does not return same amount of plots as "chia plots check"

### ISSUE THREAD

**Issue by MattLoyeD** [Chia-Network/chia-blockchain#2201]
**Description**
When doing `chia farm summary`, number of actives plots is different from `chia plots check`.

**To Reproduce**
I use 3 16 TB HDD, there is in each :
11T     ./hd1
6.8T    ./hd2
4.0T    ./hd3

All are plots of currently moved plots from another machines via rsync. `chia farm summary` replies 112 plots and `chia plots check` replies 196 active plots.  All folders are added since a while via `chia plots add -d`  ...

**Screenshots**
Screens from summary and check :
![image](https://user-images.githubusercontent.com/3109820/115423361-0a35df80-a1fe-11eb-9570-dfc157c9ace7.png)

![image](https://user-images.githubusercontent.com/3109820/115423471-246fbd80-a1fe-11eb-8ef0-8c3effaee190.png)

**Desktop (please complete the following information):**

- OS: Ubuntu Server 20.04
- CPU: AWS VM, t3a.large server

**Additional context**
We rsync from 20 other farmer to theses folders to make a unique farm. I also wonder if this is the good way to farm. Maybe i missed something ?

**Comment by 2019jack** [comment]
i have this is problem, @hoffmang9 you can help ?

**Comment by netherstar** [comment]
after moved plots you can run this command "chia start -r harvester" to make it load new plots

**Comment by MattLoyeD** [comment]
Wow it worked perfectly :). This shall be added to Wiki of CLI Commands !
