### ISSUE TITLE
List of what exes to allow through firewall?

### ISSUE THREAD

**Issue by douglas24** [Chia-Network/chia-blockchain#2202]
What exes in the install folder do I need to allow through my firewall? By default it's set to block everything and Chia just hangs on wallet creation since one of its many processes can't get through to the internet. I looked in the wiki but couldn't find a list of what to allow.

**Comment by fullet-tortuga** [comment]
I allowed all executables to go through the firewall but it still fails, sometimes the install program doesn't even create all the files. Funny thing how it works ok in a clean machine with no Internet connection. I assume the problem is somewhere else not related to connectivity.

**Comment by netherstar** [comment]
```
8444/tcp    chia_full_node                          /usr/bin/python3.9
8447/tcp   chia_farmer                             /usr/bin/python3.9
8555/tcp   chia_full_node                          /usr/bin/python3.9
8555/tcp   chia_full_node                          /usr/bin/python3.9
8559/tcp   chia_farmer                             /usr/bin/python3.9
8560/tcp   chia_harvester                          /usr/bin/python3.9
9256/tcp   chia_wallet                             /usr/bin/python3.9
```
