### ISSUE TITLE
Why my node shows im syncing with "testnet1"?

### ISSUE THREAD

**Issue by CipherCodecs** [Chia-Network/chia-blockchain#2204]
My OS is Ubuntu,and I have just made up 8 k32 plots.When I was just try to start farming,the gui shows me that it is in "testnet1",where "Network Name"shows in,not “mainnet" in usual,Besides,it have already synced at about few hours which still show "Not Synced".Have I did anything wrong?

**Comment by hoffmang9** [comment]
You should not checkout main. Instead checkout either latest or 1.0.5.
