### ISSUE TITLE
RuntimeError: bad allocation

### ISSUE THREAD

**Issue by corviato1** [Chia-Network/chia-blockchain#2207]
Anyone know what happened?

- OS: Windows 10
- CPU: AMD threadripper, 64 threads

![4-20-chiacoin](https://user-images.githubusercontent.com/44780076/115446657-63851b00-a1cc-11eb-83c1-83f54172140b.png)

**Comment by hoffmang9** [comment]
This is a RAM problem. It can be related to your swap settings or hardware RAM settings.

**Comment by corviato1** [comment]
What settings do you recommend for 256 RAM, 60 threads, 4 TB NVMe?
