### ISSUE TITLE
Plot > Add a Plot #2 Advanced Options

### ISSUE THREAD

**Issue by corviato1** [Chia-Network/chia-blockchain#2208]
Do the boxes "RAM max usage" and "Number of threads" boxes want the total number, or the numbers of each plot build?

**Comment by dorkmo** [comment]
for each plot, so if youre parallel plotting, you need to add up the ram per queue

**Comment by corviato1** [comment]
So if I have 60 cores and 238419 MiB of ram do you recommend as input points on parallel Plots?

**Comment by dorkmo** [comment]
do you have multiple temporary ssd drives? that might be your limiting factor. youll probably have to try different settings to see if it crashes. thats a lot of threads and ram, you could try a lot of parallel plots, but if you only have one temp drive, you might still be limited on speed

**Comment by corviato1** [comment]
@dorkmo 
I have one 2 TB(1.4 TB available) NVMe in the rig, but i have a 4 TB NVMe I can add or, four 2 TB NVMes I can add.  
If i add the 4 NVMes, would it be best to raid 0 them, or run it on each of the drives?
@hoffmang9 your input is appreciated

**Comment by dorkmo** [comment]
im not an expert, but i wouldnt raid 0 them. try doing 2 plots on each one and see if it runs? thats where i'd start :-D

**Comment by dorkmo** [comment]
If you wanted to do a vanity k size you could raid them and shoot for the stars
