### ISSUE TITLE
About node synchronization and transparent transmission

### ISSUE THREAD

**Issue by errcodex** [Chia-Network/chia-blockchain#2215]
I noticed that many people have problems with node synchronization. I have an idea to synchronize nodes through a public network server.

 **If the server has a public network IP, there is no need to worry about the synchronization problem, and then manually add the server's IP and port on the client to achieve node synchronization.**

Because of the NAT translation problem, in my country, even if UPNP is turned on, it is difficult to establish a link with other points.If this idea is feasible, please tell me how to implement it--the server is only used to synchronize nodes and transfer nodes to other points.

English is not good, the above is from Google Translate.Thanks!

**Comment by hoffmang9** [comment]
Until we deploy the DNS introducers we will be making peers available at peer.chia.net

**Comment by errcodex** [comment]
Thanks for your answers and work, please make it available as soon as possible.
