### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by olegshishkin** [Chia-Network/chia-blockchain#2226]
**Describe the bug**
Current Blockchain Status: Not Synced. Peak height: 159426

**To Reproduce**

1. Just stopped sync. I tried git pull, but no result.

**Expected behavior**
Sync successfull

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Linux]
- OS Version/Flavor: [Ubuntu 20 lts]
- CPU: [VCPU Digital Ocean]

**Additional context**

**Comment by dorkmo** [comment]
make sure you port 8444 is being forwarded on your router

**Comment by olegshishkin** [comment]
I guess, my problem is system clock. Thank you)
