### ISSUE TITLE
Constant White Screen?

### ISSUE THREAD

**Issue by Shahzadqayyum** [Chia-Network/chia-blockchain#2230]
I am getting a weird problem and cant figure it out.
http://prntscr.com/11s1ok2

please see above screenshot. chia is running in background. temp directory is growing.
but I cant get rid of this white screen?
tried CTRL+R and CTRL+SHIFT+R but no luck? Do I need to close it and restart process?
thanks in advance

**Comment by dorkmo** [comment]
might restart your computer. you could wait until you see the plot finish in the temp folder
