### ISSUE TITLE
[BUG] Stuck on "Connecting to Wallet"

### ISSUE THREAD

**Issue by chiauserrich** [Chia-Network/chia-blockchain#2232]
**Describe the bug**
Opening Chia Blockchain the screen gets stuck at "Connecting to Wallet" with the wheel spinning. Have let is sit for 36hrs with no result. Force quit and reboot computer. Delete and reinstall Chia. Nothing works.  

**To Reproduce**

1. Open Chia Blockchain
2. See wheel spin and "Connecting to Wallet" forever

**Expected behavior**
Chia Blockchain to open and access to wallet, full node, plots and farms. 

**Desktop (please complete the following information):**

- OS: Mac Big Sur

**Additional context**
I have been plotting and farming Chia in this wallet for months and now cannot get in. It was operating perfectly until April 16.

**Comment by darkodus** [comment]
See #2218 for potential fix!

**Comment by chiauserrich** [comment]
This worked. Thank you.
