### ISSUE TITLE
[BUG]ubuntu2004 alway show Not Synced

### ISSUE THREAD

**Issue by godot0413301** [Chia-Network/chia-blockchain#2233]
**Describe the bug**
chia 1.0.5 on ubuntu2004 always shows "Not Synced".

**To Reproduce**

1. in Full Node
2. always show Not Synced

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44113641/115484604-9a961380-a242-11eb-9e81-9ff935856be7.png)

**Desktop (please complete the following information):**

- OS: [ubuntu]
- OS Version/Flavor: [Ubuntu20.04.2LTS]
- CPU: [AMD® Ryzen 5 2400g]

**Comment by kernel1983** [comment]
similiar here
