### ISSUE TITLE
[HELP] about testnet and test farming

### ISSUE THREAD

**Issue by chuwt** [Chia-Network/chia-blockchain#2234]
i run testnet0 on my machine, and is there an easy way to farm with less plots or test plots?
how should i make my testnet start to generate blocks

**Comment by dorkmo** [comment]
testnet is only for testing, coins generated there wont have any value

**Comment by chuwt** [comment]
@dorkmo what i want to do is running a test net on my own machine, that i can test generating block step by step.
Now, i don't know how to farm with test plots.

**Comment by dorkmo** [comment]
im affraid i dont know much about running on the testnet, might have to ask on keybase

**Comment by chuwt** [comment]
@dorkmo thanks, i will focus on it

**Comment by aqk** [comment]
Thank you @chuwt 

@dorkmo, please try chia_network.public#testnet

You can also look at
https://github.com/Chia-Network/chia-blockchain/tree/main/tests/blockchain
and
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#testnets
