### ISSUE TITLE
[BUG]Farming status: Not synced or not connected to peers

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#2240]
bug Farming status: Not synced or not connected to peers

**Comment by hoffmang9** [comment]
Make sure your clock is set correctly and try direct connecting node.chia.net on port 8444

**Comment by liya558** [comment]
> 确保您的时钟设置正确，然后尝试在端口8444上直接连接node.chia.net

is there any time zone requirement?

**Comment by hoffmang9** [comment]
Your clock needs to be accurate in the machine's timezone.

**Comment by liya558** [comment]
> Your clock needs to be accurate in the machine's timezone.

Thank you. I found the reason. I can't access it node.chia.net
