### ISSUE TITLE
[BUG] Sync stuck on block 156412

### ISSUE THREAD

**Issue by creotiv** [Chia-Network/chia-blockchain#2251]
**Describe the bug**
Sync stuck on block 156412

**To Reproduce**
Hell i know?

**Expected behavior**
Sync works without problems

**Screenshots**

![image](https://user-images.githubusercontent.com/250125/115516173-87a93080-a28e-11eb-9798-c9e366327969.png)

- OS: Windows 10 Pro
- CPU: i7-6700HQ

**Additional context**
Tried to add nodes manually, they connected, but sync not proceed

**Comment by fgielow** [comment]
I am stuck too, at block 27808

**Comment by petrkr** [comment]
Try add manual node node.chia.net port 8444

**Comment by fgielow** [comment]
> Try add manual node node.chia.net port 8444

After restarting, reinstalling, and adding that node manually, it's syncing again here. 

Not sure what did the trick.

**Comment by creotiv** [comment]
Added node, it showed syncing, then downloaded 14Mb, last block not changed
and node disconnected. Same thing was with other nodes that i added manually

Kindly yours,
Andrey Nikishaev

Areas         ML/DS/CV/Soft Dev/BizDev/Growth Hacking/Customer Rel/IT
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by mariano54** [comment]
You all need to do port forwarding on 8444 to get connections and stay synced:
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by petrkr** [comment]
> You all need to do port forwarding on 8444 to get connections and stay synced:
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

maybe you are happy on this world to have public IP, but rest of world is behind NAT. So your solution is NOT apply to all and it is only workaround.

**Comment by hoffmang9** [comment]
You can make your node available and have good connectivity to the peer to peer network. Or not. Your choice.

**Comment by creotiv** [comment]
1) So you think problem with port forwarding. Then how i got downloaded
150k of blocks?

2) i have port forwarding enabled, so problem not there.

**Comment by creotiv** [comment]
Would be grate if you add some logs for the windows client, so i can see
what happens

**Comment by creotiv** [comment]
@mariano54 why are you closed bug, while it not solved?

**Comment by petrkr** [comment]
> You can make your node available and have good connectivity to the peer to peer network. Or not. Your choice.

Bitcoin is also p2p and there is no problem with NAT. There is more issue with peer propagation, for example my node is then public IP and do not have many connections, my other node is behind NAT and I had to connecti manually my other node, this should be done by automatic peer discovery process.

**Comment by hoffmang9** [comment]
Bitcoin dropped uPnP over security concerns. The major difference is that it's a basically static peer network. It has about 80,000 nodes and chia passed that about 3 days ago and was 110,000 and climbing - many of which don't have 8444 open so everyone is inundating any peer that is open. Those open peers run great and stay solidly synced.

**Comment by rawbar** [comment]
I have 8444 open and tested open.  I have literally lost days and days of productivity trying to sync.  Any time there is a new release and I have to stop and restart chia, I have to resync.  When 1.1.0 came out, I updated and was never able to sync again.  Now 1.1.1 is out, I'm trying to sync, I saw it move once and now it's just sitting here 162176/170458.  At times I've watched it not move in 48 hours.  The implementation of relying on people to open 8444 *DOES NOT WORK*.  This isn't a scalable approach and needs to be rethought.  Unless devs have a better solution than open 8444 and cross your fingers, I give up.  I've wasted way too much time on this to only have 64 plots after 2 weeks with 120TB of storage ready to go and my farmer unsynched most of the time.

**Comment by rawbar** [comment]
> You all need to do port forwarding on 8444 to get connections and stay synced:
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

Even this DOES NOT WORK.  It can take days with 8444 verified as open.

**Comment by rawbar** [comment]
So it seems with 1.1.1 when I get stuck, if I quit and restart (and add node.chia.net:8444) that I gain another couple thousand before things grind to a halt.  Then I quit and restart and repeat.  I'm up to 165896 now from 162176 after doing this 5 or 6 times.

**Comment by dorkmo** [comment]
@creotiv how many peers are you showing connected to?

**Comment by creotiv** [comment]
one or zero because they disconnected fast

**Comment by petrkr** [comment]
I,do not know if my node still has free slots,  but u can try chia.yacp.net:8444

**Comment by stevenvegar** [comment]
I had the same issue and I tried everything to solve this!!! UPnP was not, port forwardin was neither. Just put the correct time and zone configuration under Windows settings and that was all!!
Credits: https://youtu.be/bvZcNfz4hEc

**Comment by rawbar** [comment]
fwiw, had nothing but problems with windows farming thru 1.1.5.  windows is now just plotting.  moved farming to ubuntu and have had absolutely zero issues.  the windows client is just broken when it comes to staying synched.
