### ISSUE TITLE
Problem Harvester: plot has a farmer public key that is not in the farmer's pk list

### ISSUE THREAD

**Issue by xguya** [Chia-Network/chia-blockchain#2255]
Hello I have a problem, I follow your instruction on https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines but I get follows warning and I think my Harvester doesn't works. 
In config.yam I have CHIA_ALERTS_PUBKEY I don't understand what's this key ? Could be this the problem ? 

I added Pool public key of my plots and my Main in  pool_public_keys: !!set    it's right?

Someone could help me ?  Thank you in advance

**chia plots check  result:**

chia.plotting.plot_tools         : WARNING  Plot /plot/plot-k32-2021-04-21-01-01-XXXXXe1c64068e8183d722e360b28d28424e99d7fb490317da835547487ec1df.plot has a farmer public key that is not in the farmer's pk list.

WARNING  There are 3 plots with a farmer or pool public key that is not on this machine. The farmer private key must be in the keychain in order to farm them, use 'chia keys' to transfer keys. The pool public keys must be in the config.yaml

**debug.log** 

10:10:46.685 harvester chia.plotting.plot_tools: WARNING  Plot /plot_3/plot-k25-2021-04-21-09-46-XXXXXXfe8835e759b0c9b4ddd56f42f2c9908c9ce4a4fc8a39ba43c3d14194a.plot has a farmer public key that is not in the farmer's pk list.
10:10:46.685 harvester chia.plotting.plot_tools: INFO     Loaded a total of 0 plots of size 0.0 TiB, in 0.05639767646789551 seconds
10:10:46.686 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.

**I created pots with this way:**
chia plots create -b 4096 -r 6 -k 32 -t /plot_temp -d /plot_3 -f Farmer_public_key_MAIN -p Pool_public_key_MAIN 

**On main server debug log with harvester ip I have only:**
12:19:52.063 farmer farmer_server              : INFO     -> handshake to peer xxx.198.65.xxx cd87f37f732f7cf7d200bd658e3ab4fff54218b0dec3ed79801bffbbxxxxxxxx
12:19:52.063 farmer farmer_server              : INFO     -> harvester_handshake to peer xxx.198.65.xxx cd87f37f732f7cf7d200bd658e3ab4fff54218b0dec3ed79801bffbbxxxxxxxx

and not new_signage_point to peer

**Comment by etimes2008** [comment]
me too,copy plot file to farmer machine

**Comment by VisualWebTech** [comment]
Same here not sure what to do about it

2021-05-09T05:44:47.924 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-10T07:03:40.364 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-05-10T07:03:48.291 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-05-10T07:03:55.793 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-05-10T07:03:56.076 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-05-10T08:11:48.425 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting
2021-05-10T08:11:56.649 harvester harvester_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: new_signage_point_harvester, port 8447 but not disconnecting

**Comment by ndurchx** [comment]
Same here plots created at a remote machine, described at the first comment, give the "has a pool public key that is not in the farmer's pool pk list." warning.
Local created plots are working. Total uses space is 2TB and "chia farm summary" shows 1.3 TB size of plots. The plots with the warning are not counting towards total size of plots.

**Comment by cryptoshaman007** [comment]
plot has a farmer public key that is not in the farmer's pk list

its a very comom bug here too. happens with some frequency out of nowhere. driving me crazy

**Comment by jonathanhatch** [comment]
I too am having this problem now.

**Comment by khituras** [comment]
I just noticed I have the same issue. I did follow the instructions on  https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines so I'm not sure what's happening

**Comment by cryptoshaman007** [comment]
Could be the ip change. Put manual ip

Em sáb, 15 de mai de 2021 14:34, Erik Fäßler ***@***.***>
escreveu:

**Comment by khituras** [comment]
> Could be the ip change. Put manual ip

I don't think so, this is not about the connection but about authentication. Also, my IPs are fixed. The `chia plots check` tool does not require any connection.
However, I have observed that my logs seem OK. The farmer sends out messages to the harvesters, those check their plots in the correct number and send the result back. So it _seems_ to me everything would be working. But I'm still not sure because of this warning.

**Comment by cryptoshaman007** [comment]
For me sometimes just restarting computers and internet resoslves.

But when main node changes IP or is not reachable I get this error.

Em seg, 17 de mai de 2021 02:49, Erik Fäßler ***@***.***>
escreveu:

**Comment by swanky831206** [comment]
You have to add seed from farm private key. 
chia keys add -t (file with mnemonic seed)

**Comment by khituras** [comment]
> You have to add seed from farm private key.
> chia keys add -t (file with mnemonic seed)

The instructions at  https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines explicitly tell you not to. It is safer to have the keys only on one machine. It seems that this warning can be ignored on harvester-only machines, or so I was told on reddit. You need the keys to farm, but harvesters don't farm themselves. Here the dialog I had on Reddit: https://www.reddit.com/r/chia/comments/nb7x6c/13_may_2021_19_may_2021_weekly_discussion_support/gyjh5fa/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

**Comment by winkee01** [comment]
The debug.log on the harvester machine shows that none of my plots are eligible to proof

```
2021-06-10T00:03:26.989 harvester chia.harvester.harvester: INFO 0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00041 s. Total 5 plots
2021-06-10T00:03:36.083 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00042 s. Total 5 plots
2021-06-10T00:03:44.350 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00033 s. Total 5 plots
2021-06-10T00:03:53.397 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00043 s. Total 5 plots
2021-06-10T00:04:03.644 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00032 s. Total 5 plots
2021-06-10T00:04:11.991 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00039 s. Total 5 plots
2021-06-10T00:04:20.440 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00055 s. Total 5 plots
```

**Comment by khituras** [comment]
> The debug.log on the harvester machine shows that none of my plots are eligible to proof
> 
> ```
> 2021-06-10T00:03:26.989 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00041 s. Total 5 plots
> 2021-06-10T00:03:36.083 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00042 s. Total 5 plots
> 2021-06-10T00:03:44.350 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00033 s. Total 5 plots
> 2021-06-10T00:03:53.397 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00043 s. Total 5 plots
> 2021-06-10T00:04:03.644 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00032 s. Total 5 plots
> 2021-06-10T00:04:11.991 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00039 s. Total 5 plots
> 2021-06-10T00:04:20.440 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 99eb3e36c0... Found 0 proofs. Time: 0.00055 s. Total 5 plots
> ```

Don't worry, this is perfectly normal. Most plots do not pass the first eligibility filter, i.e. they aren't even posed the question, they just cannot help to solve the block (I don't know the technical and mathematical specifics behind this mechanism). I see this message most of the time. But sometimes, there are 1 or more plots eligible - but don't win anyway, most of the time.

Don't worry, your farm is up and running. You only need more plots and you will see more plots being eligible.

**Comment by jjbaker4** [comment]
Not sure why this issue is closed. It doesn't seem like anyone here solved the problem. I am having this issue now, myself. When running Chia plots check on my harvester/plotter (not my main node), I get 
"Plot /media/jesse/dest/<filename>.plot has a pool public key that is not in the farmer's pool pk list" for any plot that was created on this machine. This was not a problem on Windows, but it is happening since I switched to Ubuntu. Just for clarity, these plots are most definitely not farming. Interestingly, the plots I created on this machine in Windows are actually still farming.
When I set it up on Windows, and when I set it up on Ubuntu, I followed the directions here:
https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines

If anyone has made progress with this issue, please let me know. Thank you.

**Comment by khituras** [comment]
Because it is a non-issue. It just means that the private key for the plots is not in the key storage of the local installation.
When I check my harvester logs, I can see that the right amount of plots is being farmed. I also already received 2XCH with just 250 plots or so. This was extremely lucky but still, everything seems to be in order.

**Comment by jjbaker4** [comment]
In my case, the incorrect number of plots were being farmed in my harvester and main node logs. However, I was able to solve the problem by turning off upnp in the harvester config. Weird that this wasn't a problem in Windows.

**Comment by vicentemangas** [comment]
> chia keys add -t (file with mnemonic seed)

Hey you commented on 17 june that there is not issue with it, but I cannot see those plots on the pool at all... is there anything that we are missing? we have 2 pcs with the same account pointing to the same pool.

**Comment by aarcro** [comment]
I'd added a new key, but had not restarted the farmer. Only after `chia start -r farmer-only` did the harvesters start using the plots from the additional key.
