### ISSUE TITLE
AMD CPU 5950X is very slow...

### ISSUE THREAD

**Issue by xillkoi** [Chia-Network/chia-blockchain#2256]
AMD CPU 5950X compatibility is very poor, 64GB memory, 2*2TB SSD(pcie 4.0), CPU usage is only 20%~40% fluctuating, plot 7 files takes more than a day, what should I do? 
![企业微信截图_20210421165351](https://user-images.githubusercontent.com/82936603/115526141-4e8ab380-a2c2-11eb-9e67-354ebb23ccd8.jpg)

**Comment by botanegg** [comment]
Seems like your SSDs is bottleneck
I've 5950X too and saw same things

**Comment by xillkoi** [comment]
> 
> 
> 好像您的SSD成为瓶颈
> 我也有5950X并看到了相同的东西

Why? My SSD is pcie4.0 (Uscorsair MP600 CORE), Read speed 4700MB/S,Write speed 3700MB/s,Do you  think it is a problem with the SSD?

**Comment by botanegg** [comment]
Im not a developer of Chia
But I used `strace` to inspect I/O patterns of plotting process
It looks like fully random read/writes via temporary files
So you need to see random IO performance for your drives

Just check your SSD tab in windows task manager
If you see unstable disk latency and 100% load time - it may be overload

Also SSDs can overheat and throttle

**Comment by xillkoi** [comment]
> 我不是Chia
> 的开发人员 但我过去常检查绘图过程
> 的I/O模式 它看起来像完全随机读取/写入通过临时文件（由4k，328k和1020k块）
> 因此，您需要查看驱动器的随机 IO 性能`strace`
> 
> 只需在窗口任务管理器
> 中检查您的SSD选项卡，如果您看到不稳定的磁盘延迟和100%加载时间-它可能是超载
> 
> 此外，SSD可以过热和油门



> 我不是Chia
> 的开发人员 但我过去常检查绘图过程
> 的I/O模式 它看起来像完全随机读取/写入通过临时文件（由4k，328k和1020k块）
> 因此，您需要查看驱动器的随机 IO 性能`strace`
> 
> 只需在窗口任务管理器
> 中检查您的SSD选项卡，如果您看到不稳定的磁盘延迟和100%加载时间-它可能是超载
> 
> 此外，SSD可以过热和油门

Ok,I try it!Thanks guy!

**Comment by xillkoi** [comment]
> 我不是Chia
> 的开发人员 但我过去常检查绘图过程
> 的I/O模式 它看起来像完全随机读取/写入通过临时文件（由4k，328k和1020k块）
> 因此，您需要查看驱动器的随机 IO 性能`strace`
> 
> 只需在窗口任务管理器
> 中检查您的SSD选项卡，如果您看到不稳定的磁盘延迟和100%加载时间-它可能是超载
> 
> 此外，SSD可以过热和油门

Thanks! I try again tonight!

**Comment by xillkoi** [comment]
> Im not a developer of Chia
> But I used `strace` to inspect I/O patterns of plotting process
> It looks like fully random read/writes via temporary files (by 4k, 328k and 1020k blocks)
> So you need to see random IO performance for your drives
> 
> Just check your SSD tab in windows task manager
> If you see unstable disk latency and 100% load time - it may be overload
> 
> Also SSDs can overheat and throttle

How can I change if my ssd is throttling?

**Comment by Franpepper** [comment]
> 
> 
> > Im not a developer of Chia
> > But I used `strace` to inspect I/O patterns of plotting process
> > It looks like fully random read/writes via temporary files (by 4k, 328k and 1020k blocks)
> > So you need to see random IO performance for your drives
> > Just check your SSD tab in windows task manager
> > If you see unstable disk latency and 100% load time - it may be overload
> > Also SSDs can overheat and throttle
> 
> How can I change if my ssd is throttling?

Add a cooling solution for better performance.

I use this [cooling solution](https://www.amazon.com/dp/B0827PM9VR?tag=systoaellc-20&linkCode=ogi&th=1&psc=1) for my nvme

**Comment by xillkoi** [comment]
> > > 我不是Chia的开发人员，但我过去常检查绘图过程的I/O模式它看起来像完全随机读取/写入通过临时文件（由4k， 328k和1020k块）因此，您需要查看驱动器的随机IO性能 只需在窗口任务管理器中检查您的SSD选项卡，如果看到不稳定的磁盘延迟和100%加载时间-它可能是超载SSD也可以过热和油门`strace`
> > 
> > 
> > 如果我的ssd正在限制，如何更改？
> 
> 添加冷却解决方案，提高性能。
> 
> 我使用这个[冷却解决方案](https://www.amazon.com/dp/B0827PM9VR?tag=systoaellc-20&linkCode=ogi&th=1&psc=1)为我的nvme



> > > 我不是Chia的开发人员，但我过去常检查绘图过程的I/O模式它看起来像完全随机读取/写入通过临时文件（由4k， 328k和1020k块）因此，您需要查看驱动器的随机IO性能 只需在窗口任务管理器中检查您的SSD选项卡，如果看到不稳定的磁盘延迟和100%加载时间-它可能是超载SSD也可以过热和油门`strace`
> > 
> > 
> > 如果我的ssd正在限制，如何更改？
> 
> 添加冷却解决方案，提高性能。
> 
> 我使用这个[冷却解决方案](https://www.amazon.com/dp/B0827PM9VR?tag=systoaellc-20&linkCode=ogi&th=1&psc=1)为我的nvme

Ok,thank you bro! You are right,the SSD temperature is too high affect the performance!  Thank you again!!!

**Comment by jan3657** [comment]
Hey @botanegg I have a similar problem like the one mentioned in the post, but my drives are not overheating. I noticed that you used strace to inspect I/O patterns of plotting process, would you mind explaining your troubleshooting process ? I have  a gigabyte m.2 2280 NVMe, and it should have 2.5GB read and 2.1GB write. but with dd i only get around 1GB.

**Comment by 4thFourthHorseman** [comment]
> Im not a developer of Chia
> But I used `strace` to inspect I/O patterns of plotting process
> It looks like fully random read/writes via temporary files (by 4k, 328k and 1020k blocks)
> So you need to see random IO performance for your drives
> 
> Just check your SSD tab in windows task manager
> If you see unstable disk latency and 100% load time - it may be overload
> 
> Also SSDs can overheat and throttle

Is the plotting processed sequentially or random regarding the creation of the plots in the plotter harddrive and the transfer from the plotter to the destination hd?

**Comment by infinitywings** [comment]
> > 好像您的SSD成为瓶颈
> > 我也有5950X并看到了相同的东西
> 
> Why? My SSD is pcie4.0 (Uscorsair MP600 CORE), Read speed 4700MB/S,Write speed 3700MB/s,Do you think it is a problem with the SSD?

It seems you have too many tasks working in parallel. It is better to set an interval between every two tasks to be longer than 10 mintues. Also, the labeled performance of SSD is acquired considering the acceleration of cache. For plotting, too much data are written to the disk and the cache (DRAM/SLC) is used up. It is better to check your SSD's sustained writing speed (缓存外写入速度). My 970EVO has the labeled writing speed of 3000MB/s, but the actual speed decreases to 1300MB/s after writing 100GB data continuously.

**Comment by bouncytoaster** [comment]
> > > 好像您的SSD成为瓶颈
> > > 我也有5950X并看到了相同的东西
> > 
> > 
> > Why? My SSD is pcie4.0 (Uscorsair MP600 CORE), Read speed 4700MB/S,Write speed 3700MB/s,Do you think it is a problem with the SSD?
> 
> It seems you have too many tasks working in parallel. It is better to set an interval between every two tasks to be longer than 10 mintues. Also, the labeled performance of SSD is acquired considering the acceleration of cache. For plotting, too much data are written to the disk and the cache (DRAM/SLC) is used up. It is better to check your SSD's sustained writing speed (缓存外写入速度). My 970EVO has the labeled writing speed of 3000MB/s, but the actual speed decreases to 1300MB/s after writing 100GB data continuously.

what do you mean by set an interval between every two tasks?

**Comment by MachiAngel** [comment]
> > > > 我不是Chia的开发人员，但我过去常检查绘图过程的I/O模式它看起来像完全随机读取/写入通过临时文件（由4k， 328k和1020k块）因此，您需要查看驱动器的随机IO性能 只需在窗口任务管理器中检查您的SSD选项卡，如果看到不稳定的磁盘延迟和100%加载时间-它可能是超载SSD也可以过热和油门`strace`
> > > 
> > > 
> > > 如果我的ssd正在限制，如何更改？
> > 
> > 
> > 添加冷却解决方案，提高性能。
> > 我使用这个[冷却解决方案](https://www.amazon.com/dp/B0827PM9VR?tag=systoaellc-20&linkCode=ogi&th=1&psc=1)为我的nvme
> 
> > > > 我不是Chia的开发人员，但我过去常检查绘图过程的I/O模式它看起来像完全随机读取/写入通过临时文件（由4k， 328k和1020k块）因此，您需要查看驱动器的随机IO性能 只需在窗口任务管理器中检查您的SSD选项卡，如果看到不稳定的磁盘延迟和100%加载时间-它可能是超载SSD也可以过热和油门`strace`
> > > 
> > > 
> > > 如果我的ssd正在限制，如何更改？
> > 
> > 
> > 添加冷却解决方案，提高性能。
> > 我使用这个[冷却解决方案](https://www.amazon.com/dp/B0827PM9VR?tag=systoaellc-20&linkCode=ogi&th=1&psc=1)为我的nvme
> 
> Ok,thank you bro! You are right,the SSD temperature is too high affect the performance! Thank you again!!!

請問你SSD 溫度幾度過高呢

**Comment by ruixingchen** [comment]
> Im not a developer of Chia
> But I used `strace` to inspect I/O patterns of plotting process
> It looks like fully random read/writes via temporary files (by 4k, 328k and 1020k blocks)
> So you need to see random IO performance for your drives
> 
> Just check your SSD tab in windows task manager
> If you see unstable disk latency and 100% load time - it may be overload
> 
> Also SSDs can overheat and throttle

Hello, would you mind show us the `strace` result snapshot? I am interested in the result badly, to help choosing SSDs 😄

**Comment by jimmywong123** [comment]
it's about discard, you shuld add discard mode to your disk.
