### ISSUE TITLE
x-api-key is empty

### ISSUE THREAD

**Issue by alexgarret** [Chia-Network/chia-blockchain#2263]
Hello everyone,

Not sure this is the correct place for this issue, but I've just set-up my Chia Explorer developer account and the public API key is empty, so I am unable to call the REST HTTP API.
Is it an expected behaviour with v0.1? 
Any idea when my API key will be visible from my account?

Thank you in advance.

Best,

**Comment by hoffmang9** [comment]
Chiaexplorer is a third party. There is a channel in Keybase.
