### ISSUE TITLE
[BUG] After PC reboot unfinished ploot is gone...

### ISSUE THREAD

**Issue by Peter82kr** [Chia-Network/chia-blockchain#2264]
...im using ubuntu,when i rebooted i saw that my plots tab is empty, and chia gui ask me to add plot.So i added previously used plot folders. But it STARTS PLOT FROM ZERO STATE.Why?

**Comment by botanegg** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-computerdrive-went-into-power-save-or-rebooted-while-plotting

**Comment by Peter82kr** [comment]
Thanks for explanation.

**Comment by botanegg** [comment]
@hoffmang9 this issue seems to be closed

**Comment by BuzilovDorin** [comment]
The fact that there is so much dedicated time to plotting and with a short interruption this time can be made redundant is a huge turn off for anyone...

**Comment by DavidRadan** [comment]
> The fact that there is so much dedicated time to plotting and with a short interruption this time can be made redundant is a huge turn off for anyone...

I totally agree , it's not a friendly coin after all .

**Comment by rjoffs** [comment]
more like a complete waste of time
