### ISSUE TITLE
 Keep showing no synchronization or not connected to peers

### ISSUE THREAD

**Issue by falsemail** [Chia-Network/chia-blockchain#2273]
when chia farm summary
i got this:
Farming status: Not synced or not connected to peers
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 1
Total size of plots: 429.962 GiB
Estimated network space: 0.000 TiB
Expected time to win: Unknown
Note: log into your key using 'chia wallet show' to see rewards for each key

is this normal？

when chia show -s
i got this:
Searching for an initial chain

You may be able to expedite with 'chia show -a host:port' using a known node.

Blockchain has no blocks yet

**Comment by mariano54** [comment]
See the FAQ, you need to do port forwarding https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by spammenotinoz** [comment]
> See the FAQ, you need to do port forwarding https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

That's not this.  Suppose most people would not notice as it self corrects after a few hours.
Manually adding in a peer can sometimes help.  Looks to be linked to the availability of the helpers (down or under DDoS)
