### ISSUE TITLE
[BUG] Plotting hangs without error if system has bad RAM

### ISSUE THREAD

**Issue by zcomputerwiz** [Chia-Network/chia-blockchain#2274]
**Describe the bug**
Plot window is still active with the last sort message, but it does not progress. No error is displayed, disk IO stops. CPU use may continue, or reduce. Memory use may remain the same, or reduce.

**To Reproduce**
Start plotting on a system with bad RAM.

**Expected behavior**
Plotting with bad RAM should produce an error.

**Desktop (please complete the following information):**
- OS: Windows
- OS Version/Flavor: Windows 10 Home x64
- CPU: Intel i7 10700

**Comment by zcomputerwiz** [comment]
Tested memory and ( unexpectedly ) found defects. Issue is caused by bad RAM.

**Comment by hoffmang9** [comment]
Chia plotting... Better than memtest...
