### ISSUE TITLE
[BUG] Connecting to wallet..................

### ISSUE THREAD

**Issue by penlion** [Chia-Network/chia-blockchain#2275]
**Describe the bug*
After reload stop at Connecting to wallet..................

**To Reproduce**

2. Click on 'reload'

**Expected behavior**

**Screenshots**

![96151200-CB62-4C0F-9DD2-383DE967CB21](https://user-images.githubusercontent.com/77721549/115570228-87418180-a2f0-11eb-85b5-618e4b907790.jpeg)

**Desktop (please complete the following information):**

- OS: [e.g. Windows 12 sr]
- OS Version/Flavor: 
- CPU: [e.g. Intel Xeon 6130]

**Additional context**

**Comment by NickUfer** [comment]
I would suggest using the CLI. The GUI is just unreliable.

**Comment by penlion** [comment]
> I would suggest using the CLI. The GUI is just unreliable.

What’s CLI

**Comment by NickUfer** [comment]
The Command Line Interface

https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference

**Comment by hbroer** [comment]
It does not help to say "use cli" if someone has a problem with the gui. If the gui is not useable then it should not be there. Or at least the cli should be useable without adding the path by hand and change that path manually with every update (version in path).

Btw. same problem. And wallet is out of sync stuck at height 2.

**Comment by penlion** [comment]
> The Command Line Interface
> 
> https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference

How to use it

**Comment by NickUfer** [comment]
> It does not help to say "use cli" if someone has a problem with the gui. If the gui is not useable then it should not be there.

Well, it certainly can help because it is a possible workaround for problems which could or could not occur. It was too unreliable for me, for others it might be enough to work with.

I plot on 10 hard drives in parallel and to setup these plot jobs every time something with the gui is wrong wasn't something for me. The graphical interface controls the other services like node, farmer, wallet, etc starts them and stops them and that's the problem.
The GUI should work independently and interface with apis of the services and not control their life cycle. This way you could do whatever you want with the gui but the farmer, queue, wallet, etc stay online.

**Comment by hbroer** [comment]
"The GUI should work independently and interface with apis of the services and not control their life cycle."

True that. I think that is the main problem here.

**Comment by darkodus** [comment]
I don't have exact steps for Windows, but check out #2218 for some reasoning around this. There's basically a couple of problems that might lead to this state: the database corrupts due to a sudden application or computer crash, or the port it tries to use is reserved by some other application (vmware or hyperv seem to be common culprits). If it's the database problem then the steps I mentioned in the comment there should have Windows equivalents as well if you can figure them out.

**Comment by DougieC** [comment]
I've got the same as OP. Stuck connecting to wallet on startup. This only happens with my main rig (plotter), my laptop (farm hub) connects no problem. Was running fine yesterday, exited app to use the rig for something else, went to restart chia and couldn't connect to wallet. Left it overnight, still not connected.

I've wiped chia app and app data, no difference.

Task manager also shows 4 instances of chia running when opening, 3xchia and 1x chia blockchain. No daemon / wallet / farm.

If you need any logs for debug etc just shout.

**Comment by MayBankCH** [comment]
It work for me uninstall and also remove .chia folder.

**Comment by DougieC** [comment]
Figured that out about 20 minutes after I posted here! All good now.

**Comment by miron** [comment]
Could anyone plotting try out if it helps to stop the start_wallet process and start it again?
Steps to do it:

Stop via task manager or:
C:\Users\<username>\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe stop wallet
C:\Users\<username>\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe start wallet

Does it work?
Plotting still undergoing or did it interrupt it?

**Comment by drakunov** [comment]
> Could anyone plotting try out if it helps to stop the start_wallet process and start it again?
> Steps to do it:
> 
> Stop via task manager or:
> C:\Users\username\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe stop wallet
> C:\Users\username\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe start wallet
> 
> Does it work?
> Plotting still undergoing or did it interrupt it?

Not working. Plotting still works. tryed

C:\Users\alx\AppData\Local\chia-blockchain>chia stop all
C:\Users\alx\AppData\Local\chia-blockchain>chia start farmer
C:\Users\alx\AppData\Local\chia-blockchain>chia stop wallet
C:\Users\alx\AppData\Local\chia-blockchain>chia start wallet
C:\Users\alx\AppData\Local\chia-blockchain>chia stop all
C:\Users\alx\AppData\Local\chia-blockchain>chia restart all

nothing changes Win 10 64 1.1.2

in console-- Already connected, not reconnecting.

**Comment by q5sys** [comment]
I tried those CLI stop and start commands as well...

> ${path}chia.exe start wallet
> Daemon not started yet
> Starting daemon
> Traceback (most recent call last):
>   File "chia\cmds\chia.py", line 81, in <module>
>   File "chia\cmds\chia.py", line 77, in main
>   File "click\core.py", line 829, in __call__
>   File "click\core.py", line 782, in main
>   File "click\core.py", line 1259, in invoke
>   File "click\core.py", line 1066, in invoke
>   File "click\core.py", line 610, in invoke
>   File "click\decorators.py", line 21, in new_func
>   File "chia\cmds\chia.py", line 60, in run_daemon_cmd
>   File "asyncio\base_events.py", line 587, in run_until_complete
>   File "chia\daemon\server.py", line 944, in async_run_daemon
>   File "chia\daemon\server.py", line 145, in start
>   File "websockets\server.py", line 965, in __await_impl__
>   File "asyncio\base_events.py", line 1389, in create_server
> OSError: [Errno 10013] error while attempting to bind on address ('::1', 55400, 0, 0): an attempt was made to access a socket in a way forbidden by its access permissions
> [14568] Failed to execute script chia
> Daemon not started yet
> Failed to create the chia daemon

**Comment by Ed-Yang** [comment]
I have problem to connect to wallet in Ubuntu, finally I kill all the daemons and restart chia to get it work.

killall chia_daemon

**Comment by sxpert** [comment]
> "The GUI should work independently and interface with apis of the services and not control their life cycle."
> 
> True that. I think that is the main problem here.

the GUI should have a command line option where you specify an ip address to connect to an already running set of daemons

**Comment by oktaysar16** [comment]
Stop Chia (Kill Task)

Delete these folders:
C:\Users\!yourusername!\.chia
C:\Users\!yourusername!\AppData\Local\chia-blockchain
C:\Users\!yourusername!\AppData\Roaming\Chia Blockchain

Reinstall Chia. It should now work.

**Comment by Maritims** [comment]
I did the horrible mistake of trying to reload the Chia GUI window and am now stuck with this problem. Are we getting any closer to an actual fix rather than the aforementioned workarounds?

**Comment by jmcgonegal** [comment]
Ok, I wasn't able to get the gui to start but I fixed this error in windows 10 enough to be able to keep my wallet and farm running in the windows command line:
`> C:\Users\<username_here>\AppData\Local\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon\chia.exe start wallet`
`OSError: [Errno 10013] error while attempting to bind on address ('::1', 55400): an attempt was made to access a socket in a way forbidden by its access permissions`

Steps to fix the wallet not starting:
1. Run the command
`netsh interface ipv4 show excludedportrange protocol=tcp`

```
Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5357        5357
     10243       10243
     10801       10801
     49713       49812
     50000       50059     *
     50160       50259
     50260       50359
     50369       50468
     52184       52283
     54217       54316
     54317       54416
     55110       55209
     55310       55409
     55410       55509
     55610       55709
     55710       55809
     59887       59986
     59987       60086

* - Administered port exclusions.

```
2. Determine a port not in that excluded range ( 10000 was not in the ranges listed for me )
3. Find/replace `55400` with a port in the excluded range from above. There should be 2 entries in your config file. You can also optionally replace localhost with your computername. 
`C:\Users\<username_here>\.chia\mainnet\config\config.yaml`

4. Run to verify everything works.
`C:\Users\john\AppData\Local\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon\chia.exe start all`

5. Accept all the popups for private network firewall access for each service.


In my case I cannot get chia_timelord_launcher to work at all. But my wallet and farms now work in the background and I can use the CLI.

**Comment by vittorio88** [comment]
What works for me is deleting the following folder (with the app closed):
`C:\Users\yourusername\.chia\mainnet\wallet`

To be safe, I would move this to your desktop rather than delete it.
Somehow it still "remembers" my wallet after doing this in my testing.

**Comment by farmerer** [comment]
I think they should rename reload and force reload into WARNING, DON'T CLICK HERE with capital red letters preferably.
I also tried to reload the GUI because sync was lagging. Now I have to wait until my current plots have finished plotting blind in the background so I can restart the GUI. 
Or does anybody have any better solutions?

**Comment by Fekha** [comment]
> What works for me is deleting the following folder (with the app closed):
> `C:\Users\yourusername\.chia\mainnet\wallet`
> 
> To be safe, I would move this to your desktop rather than delete it.
> Somehow it still "remembers" my wallet after doing this in my testing.

This is the first thing I tried and it worked after going to task manager and closing the chia background processes. It reconnected to my wallet just fine with no need to save or readd.

**Comment by lyl-freeman** [comment]
I got the same bug. Deleting the 3 mentioned folders and reinstrall didn't work

**Comment by webaholic123** [comment]
Hi there,
this is my first post, let me share my experience, maybe it can help you.
For last 3 days I've been fighting sync issues with both node and wallet, everything was working like a charm before just using GUI.
I checked all posts on whole internet and tried everything imaginable with no luck. Until now.
I am not sure what exactly did the trick so here are all step I consider important:
1) Uninstall chia and sweep registry with a tool like ccleaner
2) Delete all chia folders in AppData\Local, AppData\Roaming and users
3) On your router disable Upnp and set port forward to your machine 8444/8444, make sure it works with some port checker or telnet
4) Restart router and PC
5) Install latest chia.exe and start GUI, just to initiate wallet and end the programm
6) Now use CLI , I started with simple windows cmd, no powershell needed. 
7) In CLI set upnp to FALSE, log to INFO a start node
8) Now be patient, it was whole day for me, maybe you can speed it up by adding new connections but that didn't work for me, I got 16 peers and only one of them had any traffic 
7) When you are fully synced according to chia show -s, you can exit CLI and start GUI
8) Again, be patient, it will take some time to sync here as well AND what I couldn't achieve in CLI - it will slowly sync your wallet 
9) My plots are passing filter, everything is green and waiting for some chia:)
Good luck

**Comment by danielshoo** [comment]
> uninstall and also remove .chia folder.

 - For BigSur 11.3.1 & mainnet 1.1.5 -

This worked for me after the app (gui & cmd line) suddenly started failing after a week of plotting

**Comment by jakuba1909** [comment]
Ubuntu 20.04 here, got the gui stuck a few times already and solved the problem like this via process manager:

1. never, i repeat: never close a "chia" process, as those are the plots.. you dont want them to stop, do you?

2. close all related chia processes like "chia_harvester" and "start_wallet" and so on, so that the remaing processes of chia are "chia" and "chia-blockchain"

3.  close all chia-blockchains.. one always shows the exit toolbar "do you want to end plotting", press no.. kill all the other "chia-blockchain" processes and then redo the one with the toolbar, it should work now without any toolbar popping up

4. start the gui again, all processes but the plots should restart and work again 

works like a charm for my rig, hope it does so for you, too

**Comment by ArthurWang833** [comment]
close all chia process. go C:\Users\you\.chia\mainnet\wallet delete everything in there. and restart chia gui. it works for me

**Comment by qbol69** [comment]
Not sure if that will help you, but i did helped me. I've opened task manager, went to details and there were 4 chia.exe processes. Closed randomly last of them and it caused the gui to become full white, then I was able to click on view -> reload and it works smoothly since then.

**Comment by PMExtra** [comment]
I found the chia daemon cannot start because the port 55400 has been reserved. ref: https://github.com/microsoft/WSL/issues/5514

**Comment by IanWorthington** [comment]
> What works for me is deleting the following folder (with the app closed):
> `C:\Users\yourusername\.chia\mainnet\wallet`
> 
> To be safe, I would move this to your desktop rather than delete it.
> Somehow it still "remembers" my wallet after doing this in my testing.

This works.  As far as I can see deleting .chia (specifically .chia\mainnet\db) would involve having to resync the entire blockchain.

**Comment by samy63** [comment]
![image](https://user-images.githubusercontent.com/84105006/119280361-55924200-bc31-11eb-9bf2-2e08e5749c8d.png)

**Comment by PMExtra** [comment]
@samy63 It seems as same as I met. Please ref microsoft/WSL#5514, for shortly:
Execute `netsh stop winnat` in Administrator Command Prompt to stop winnat, then restart chia, then you can restart winnat after chia work correctly (`netsh start winnat`)

**Comment by xazes** [comment]
same problem here.

**Comment by PMExtra** [comment]
@xazes Do you check the port? run `netsh interface ipv4 show excludedportrange protocol=tcp` and check if it contains 55400.

**Comment by xazes** [comment]
@PMExtra the only solution was that i delete the wallet. then it works again.

**Comment by rodrigolaa** [comment]
What worked for me is to delete the wallet database via PowerShell as admin. Found this tip in Chia's documentation on GitHub
Code:
del ~\.chia\mainnet\wallet\db\blockchain*
link below:
https://github.com/Chia-Network/chia-blockchain/wiki/Windows-Tips-and-Tricks
![image](https://user-images.githubusercontent.com/50839107/120573647-4a3ed380-c3f4-11eb-8de9-60bb00f4493d.png)

**Comment by taddogdog** [comment]
> What works for me is deleting the following folder (with the app closed):
> `C:\Users\yourusername\.chia\mainnet\wallet`
> 
> To be safe, I would move this to your desktop rather than delete it.
> Somehow it still "remembers" my wallet after doing this in my testing.

i did this and its work fine for me. Thanks so much.

**Comment by dogan2893** [comment]
FİX
Turn off everything related to chia mining in task manager.
The reason for this error is that you delete or delete the plots that have occurred or will occur on the discs while chia mining is turned off.
