### ISSUE TITLE
[BUG] chia_daemon keeps running after `chia stop all`

### ISSUE THREAD

**Issue by NickUfer** [Chia-Network/chia-blockchain#2276]
**Describe the bug**
chia_daemon keeps running after `chia stop all` or `chia stop node` or `chia stop harvester`

**To Reproduce**

1. start chia
2. stop chia

**Expected behavior**
It should stop

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux] Linux
- OS Version/Flavor: [e.g. CentOS 7.2] Kubuntu 20.10
- CPU: [e.g. Intel Xeon 8175M] AMD Ryzen 7 3700X

**Comment by Teledyol** [comment]
I'm getting the same, and it is interfering with new OS update, I have been running 11.3 beta, would like to run gold standard for a bit

**Comment by hoffmang9** [comment]
The stop all command takes a -d to also stop daemon.
