### ISSUE TITLE
Invalid plots are farming

### ISSUE THREAD

**Issue by bunjicat** [Chia-Network/chia-blockchain#2282]
I moved several plots to a different drive.  Plots are indicated as being farmed but also shows plots as failed to open (invalid plots).  Plot count is correct for the total number and after I deleted a reported invalid plot the total (valid) plot count went down.  So they appear to be good plots but being reported as invalid after the move.

**Comment by bunjicat** [comment]
1.1 fixed.

**Comment by OldButtKicking** [comment]
I'm still seeing the same problem on 1.1.7.
I copied the plots from one drive to another then through the ui I removed the old drive as a farm location and added the new drive. 

They now show up as currently farming and also in the failed to open (Invalid plots).

Do I just need to open close the UI? I'm reluctant at the moment too many plots in progress.
