### ISSUE TITLE
0 plots were eligible for farming

### ISSUE THREAD

**Issue by avb1213** [Chia-Network/chia-blockchain#2288]
Hello.
I have one remote harvester service with one plot file for testing purposes.
Have this messages in debug.log on remote harvester service.
`20:12:38.267 harvester chia.harvester.harvester: INFO 0 plots were eligible for farming faef4c1b15... Found 0 proofs. Time: 0.00029 s. Total 1 plots`
It is normal that: "0 plots were eligible for farming"?
`chia plots check` on harvester look's good:
```
20:24:59.661  chia.plotting.check_plots        : INFO     Summary
20:24:59.661  chia.plotting.check_plots        : INFO     Found 1 valid plots, total size 0.09900 TiB
20:24:59.661  chia.plotting.check_plots        : INFO     1 plots of size 32
```

**Comment by mariano54** [comment]
Yes its fine, see the faq for plot filter https://github.com/Chia-Network/chia-blockchain/wiki/FAQ
