### ISSUE TITLE
[BUG] chia show -c doesn't show connections to harvester

### ISSUE THREAD

**Issue by BasilHorowt** [Chia-Network/chia-blockchain#2292]
`chia show -c` shows connections to everything else except a remote harvester on my own network, however the logs on farmer and harvester indicate they are communicating.

1. Follow [setup guide](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines)
2. Tail the logs on both harvester and farmer to make sure they are communicating
3. `chia show -sc` on farmer
4. Note that harvester is not listed

I understand that `chia farm summary` does not factor in plot space from harvester (yet?), but ideally the connections between the farmer and the harvester would be indicated in some way.  Having to monitor the logs to ensure correct remote harvesting is not ideal.

OS: MacOS 11.2.3 on harvester/plotter and Raspberry pi 64bit on farmer

**Comment by mariano54** [comment]
Yeah chia show -c only shows the full node connections, not the farmer connections. There will be an update hopefully within the next few weeks to add harvester information.
