### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tttomate** [Chia-Network/chia-blockchain#2300]
**Describe the bug**
A pop up with 22 written on it if i click ok then it just appear again ( i cant use any of the things on the node)

**To Reproduce**
I dont know it just appeard 

**Expected behavior**
IDK

**Screenshots**
![!a](https://user-images.githubusercontent.com/82970862/115610741-907b2000-a2e9-11eb-987e-29229c104bcb.PNG)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Wind. 10
- CPU:AMD ryzen 5 3600

**Additional context**
it just appeard and i dont know how to fix it restart and reboot doesnt help

**Comment by hoffmang9** [comment]
You have a bad entry in the plots section of config.yaml

**Comment by tttomate** [comment]
ok how do i fix it 
(sry i am new to this )

**Comment by tttomate** [comment]
yes i dont know how to fix it

**Comment by hoffmang9** [comment]
Please ask in #beginner or #support on Keybase. GitHub issues are for bugs and not configuration errors. We know the error dialog sucks and it will get fixed.

**Comment by tttomate** [comment]
ok thx for ur help
