### ISSUE TITLE
my first plot are finish at 100% but dont move files to definitive directory

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#2308]
HI

I Finish my first plot but GUI dont move my files to the definitive directory. Im in windows10
Its possible move it manually?
what happen?
Can i shutdown my PC?
Plot key missing ( pic1)
Why i have two directories one of them in disk C: (operating system). i only put two directories both in de same DISK g:

Tnx
[Nuevo Documento de Microsoft Word.docx](https://github.com/Chia-Network/chia-blockchain/files/6354373/Nuevo.Documento.de.Microsoft.Word.docx)

**Comment by trop-joe** [comment]
Have you looked in the log? I ran in to this problem on Linux and it was unable to write to the destination and had log entries explaining why and that it was continuing to try again every 5 minutes. In my case it was a permissions issue on the destination folder, probably not the same problem on Windows but may be the same path to a solution.

**Comment by realbluefish** [comment]
I think that is not the problem. the plot was created correct and the file
was kept simultaneously in both directories, temporary and definitive. On
the other hand, I closed the application but the chia.exe process is still
active (although GUIA is closed) and my hard drive is running through that
process.
in any case:
my plot is created and save in the final directory. I download the latest
version and try to access the plot indicating the directory and no farm is
shown. Can I delete all the users data (mainnet etc ...) install again and
recover my plot that is finished and start with the farm? What ?
Thank you so much

**Comment by realbluefish** [comment]
the procedure I am looking for is to recover a finished plot on a hard
drive if the pc breaks. new pc new installation and recover plots.
I use the GUI to tell you where I have them but they don't show up. i use
windows 10.
Could you tell me how to proceed?


---------- Forwarded message ---------
De: eduardo vazquez soto ***@***.***>
Date: jue., 22 abr. 2021 17:52
Subject: Re: [Chia-Network/chia-blockchain] my first plot are finish at
100% but dont move files to definitive directory (#2308)
To: Chia-Network/chia-blockchain <
***@***.***>


I think that is not the problem. the plot was created correct and the file
was kept simultaneously in both directories, temporary and definitive. On
the other hand, I closed the application but the chia.exe process is still
active (although GUIA is closed) and my hard drive is running through that
process.
in any case:
my plot is created and save in the final directory. I download the latest
version and try to access the plot indicating the directory and no farm is
shown. Can I delete all the users data (mainnet etc ...) install again and
recover my plot that is finished and start with the farm? What ?
Thank you so much

**Comment by realbluefish** [comment]
Solved
Extension file is wrong. *.plot2.temp
I rename to *.plot and voila i have my first plot

Tnx

Eduardo
