### ISSUE TITLE
Why sometimes stuck at 31% sometimes not

### ISSUE THREAD

**Issue by mzhu46** [Chia-Network/chia-blockchain#2309]
I noticed there is a scanning process sometimes will happen at around 31% of plotting process.
Is this avoidable?

"Forward propagation table time: 1586.864 seconds. CPU (145.140%) Wed Apr 21 18:39:11 2021
Time for phase 1 = 10210.805 seconds. CPU (144.090%) Wed Apr 21 18:39:11 2021

Starting phase 2/4: Backpropagation into tmp files... Wed Apr 21 18:39:11 2021
Backpropagating on table 7
scanned table 7
scanned time =  28.400 seconds. CPU (92.860%) Wed Apr 21 18:39:39 2021
sorting table 7
Backpropagating on table 6
scanned table 6"

**Comment by generalhaar** [comment]
I have been encountering the same thing on ubuntu. I have not been able to complete a plot yet because of it. My logs look exactly the same.

Starting phase 2/4: Backpropagation into tmp files... Thu Apr 22 00:59:02 2021
Backpropagating on table 7
scanned table 7
scanned time =  528.834 seconds. CPU (19.660%) Thu Apr 22 01:07:52 2021
sorting table 7
Backpropagating on table 6
scanned table 6
scanned time =  436.657 seconds. CPU (46.210%) Thu Apr 22 01:45:09 2021
sorting table 6
sort time =  1307.194 seconds. CPU (53.230%) Thu Apr 22 02:06:56 2021
Backpropagating on table 5
scanned table 5
scanned time =  543.170 seconds. CPU (40.130%) Thu Apr 22 02:16:09 2021
sorting table 5
sort time =  1364.188 seconds. CPU (48.930%) Thu Apr 22 02:38:53 2021
Backpropagating on table 4
scanned table 4
scanned time =  525.626 seconds. CPU (38.940%) Thu Apr 22 02:47:53 2021
sorting table 4

**Comment by madmmmax** [comment]
Its pretty normal, The progress is usually increased when the table 2 is sorted.

**Comment by Christopherkynn** [comment]
Do i need to stop the plot if this happens or is it a long pause ?

**Comment by mzhu46** [comment]
> Do i need to stop the plot if this happens or is it a long pause ?

probably not, it just takes some time to pass that stage. Once pass that stage, it will go much smoother.

**Comment by akashkatare5** [comment]
My Internet connection was lost, so I reconnected it, but when I saw the logs, it was stuck at 31% and wasn't moving forward:

I have read that plotting does not require Internet, but my plotting is stuck in this phase for so long as you can see the time on the right side:

Forward propagation table time: 5508.986 seconds. CPU (44.880%) Sat Apr 24 07:50:11 2021
Time for phase 1 = 29391.886 seconds. CPU (57.300%) Sat Apr 24 07:50:11 2021

Starting phase 2/4: Backpropagation into tmp files... Sat Apr 24 07:50:11 2021
Backpropagating on table 7
scanned table 7
scanned time =  994.599 seconds. CPU (2.490%) Sat Apr 24 08:06:46 2021
sorting table 7
Backpropagating on table 6

Should I delete all temp files and start again? or let it run like this only?

**Comment by mzhu46** [comment]
> My Internet connection was lost, so I reconnected it, but when I saw the logs, it was stuck at 31% and wasn't moving forward:
> 
> I have read that plotting does not require Internet, but my plotting is stuck in this phase for so long as you can see the time on the right side:
> 
> Forward propagation table time: 5508.986 seconds. CPU (44.880%) Sat Apr 24 07:50:11 2021
> Time for phase 1 = 29391.886 seconds. CPU (57.300%) Sat Apr 24 07:50:11 2021
> 
> Starting phase 2/4: Backpropagation into tmp files... Sat Apr 24 07:50:11 2021
> Backpropagating on table 7
> scanned table 7
> scanned time = 994.599 seconds. CPU (2.490%) Sat Apr 24 08:06:46 2021
> sorting table 7
> Backpropagating on table 6
> 
> Should I delete all temp files and start again? or let it run like this only?

I am also a green hand so my suggestion may be incorrect. However, if you can see the countdown is continuing and the log page is not freeze. You definitely can wait for the completion of this plot. scanned time = 994.599 seconds is just normal but CPU (2.490%) is too low and maybe that indicate you can plot more in parallel.

**Comment by akashkatare5** [comment]
> > My Internet connection was lost, so I reconnected it, but when I saw the logs, it was stuck at 31% and wasn't moving forward:
> > I have read that plotting does not require Internet, but my plotting is stuck in this phase for so long as you can see the time on the right side:
> > Forward propagation table time: 5508.986 seconds. CPU (44.880%) Sat Apr 24 07:50:11 2021
> > Time for phase 1 = 29391.886 seconds. CPU (57.300%) Sat Apr 24 07:50:11 2021
> > Starting phase 2/4: Backpropagation into tmp files... Sat Apr 24 07:50:11 2021
> > Backpropagating on table 7
> > scanned table 7
> > scanned time = 994.599 seconds. CPU (2.490%) Sat Apr 24 08:06:46 2021
> > sorting table 7
> > Backpropagating on table 6
> > Should I delete all temp files and start again? or let it run like this only?
> 
> I am also a green hand so my suggestion may be incorrect. However, if you can see the countdown is continuing and the log page is not freeze. You definitely can wait for the completion of this plot. scanned time = 994.599 seconds is just normal but CPU (2.490%) is too low and maybe that indicate you can plot more in parallel.

Actually, it continued for the next line, so will keep it running:


Forward propagation table time: 5508.986 seconds. CPU (44.880%) Sat Apr 24 07:50:11 2021
Time for phase 1 = 29391.886 seconds. CPU (57.300%) Sat Apr 24 07:50:11 2021

Starting phase 2/4: Backpropagation into tmp files... Sat Apr 24 07:50:11 2021
Backpropagating on table 7
scanned table 7
scanned time =  994.599 seconds. CPU (2.490%) Sat Apr 24 08:06:46 2021
sorting table 7
Backpropagating on table 6
scanned table 6
**scanned time =  687.552 seconds. CPU (21.760%) Sat Apr 24 09:04:08 2021
sorting table 6**


Also, I have set the below settings for plotting:

**4770 MiB RAM and 4 threads**

I have 8 GB RAM and an Intel i5-9th gen processor...
Will I be able to plot in parallel?

I saw that sometimes my CPU uses fluctuate between 25% to 125% but not stable.

**Comment by mzhu46** [comment]
> > > My Internet connection was lost, so I reconnected it, but when I saw the logs, it was stuck at 31% and wasn't moving forward:
> > > I have read that plotting does not require Internet, but my plotting is stuck in this phase for so long as you can see the time on the right side:
> > > Forward propagation table time: 5508.986 seconds. CPU (44.880%) Sat Apr 24 07:50:11 2021
> > > Time for phase 1 = 29391.886 seconds. CPU (57.300%) Sat Apr 24 07:50:11 2021
> > > Starting phase 2/4: Backpropagation into tmp files... Sat Apr 24 07:50:11 2021
> > > Backpropagating on table 7
> > > scanned table 7
> > > scanned time = 994.599 seconds. CPU (2.490%) Sat Apr 24 08:06:46 2021
> > > sorting table 7
> > > Backpropagating on table 6
> > > Should I delete all temp files and start again? or let it run like this only?
> > 
> > 
> > I am also a green hand so my suggestion may be incorrect. However, if you can see the countdown is continuing and the log page is not freeze. You definitely can wait for the completion of this plot. scanned time = 994.599 seconds is just normal but CPU (2.490%) is too low and maybe that indicate you can plot more in parallel.
> 
> Actually, it continued for the next line, so will keep it running:
> 
> Forward propagation table time: 5508.986 seconds. CPU (44.880%) Sat Apr 24 07:50:11 2021
> Time for phase 1 = 29391.886 seconds. CPU (57.300%) Sat Apr 24 07:50:11 2021
> 
> Starting phase 2/4: Backpropagation into tmp files... Sat Apr 24 07:50:11 2021
> Backpropagating on table 7
> scanned table 7
> scanned time = 994.599 seconds. CPU (2.490%) Sat Apr 24 08:06:46 2021
> sorting table 7
> Backpropagating on table 6
> scanned table 6
> **scanned time = 687.552 seconds. CPU (21.760%) Sat Apr 24 09:04:08 2021 sorting table 6**
> 
> Also, I have set the below settings for plotting:
> 
> **4770 MiB RAM and 4 threads**
> 
> I have 8 GB RAM and an Intel i5-9th gen processor...
> Will I be able to plot in parallel?
> 
> I saw that sometimes my CPU uses fluctuate between 25% to 125% but not stable.

I remember the default setting is to use two threads and divide the # of the cores of your CPU by 2 is a suitable way to calculate the number of parallel ploting which will hit the CPU's maximum capacity. For me, I once plotted 4 in parallel using a i7-9700k although I feel destressed for seeing my CPU always run at 100 percent for hours and later I cut down to do 3.

**Comment by vildonfoo** [comment]
Hi all, I've encountered the same issue as above. I have an Acer Predator i7 7700hq 2.80ghz 32 ram 4 core 8 processor notebook. Plotting one on the laptop HDD and second plot on an external SSD 1TB. 

The 2nd plot have been stuck at 31% propagating table 7 for the past 2 hours. 

I've seen to be stuck here for the past 3 days. And reduced the ram (4000+ to 3990) and thread count (4 to 2) and number of plots (3 to 2). Anyone know if it's the issue of my laptop?

**Comment by hoffmang9** [comment]
It's a problem on your laptop. It could be that your swap is interfering or it could be hardware problems with your storage or RAM.

**Comment by vildonfoo** [comment]
> It's a problem on your laptop. It could be that your swap is interfering or it could be hardware problems with your storage or RAM.

Thanks. I'm trying to plot without the internal drive and see that goes. Ram was checked no issues.

**Comment by akashkatare5** [comment]
Guys, so as my plotting was stuck at 31% I simply let it run and after some hours my plot was successfully created.

so don’t worry it shows as stuck but actual work is going on background.

**Comment by vildonfoo** [comment]
> Guys, so as my plotting was stuck at 31% I simply let it run and after some hours my plot was successfully created.
> 
> so don’t worry it shows as stuck but actual work is going on background.

How long did your work get stuck there?

**Comment by akashkatare5** [comment]
> > Guys, so as my plotting was stuck at 31% I simply let it run and after some hours my plot was successfully created.
> > so don’t worry it shows as stuck but actual work is going on the background.
> 
> How long did your work get stuck there?

For almost 4 hours and later it started showing progess.

**Comment by vildonfoo** [comment]
> > > Guys, so as my plotting was stuck at 31% I simply let it run and after some hours my plot was successfully created.
> > > so don’t worry it shows as stuck but actual work is going on the background.
> > 
> > 
> > How long did your work get stuck there?
> 
> For almost 4 hours and later it started showing progess.

Good to know this. Thank you!

**Comment by modlab515** [comment]
Has anyone run into an issue where plotting freezes at 31%. I've tried plotting on a couple different drives including v-nand ssd, a WD external 2tb drive, and direct to my WD 8TB drive.  All have gotten stuck at around 31%.  I let my v-nand SSD sit and spin on that 31% mark over night and though it said it got to 35% this am, it was displaying the same error in in the log over and over.  I should have screen shot it, but it said something like only wrote 74505 or 85606 blocks will try again in 5min.  Has anyone run into a similar error?  I've read some forums saying that many people have run into a slow down at 31%, but that leaving the drive to plot over several more hours did the trick.  Mine did not, unfortunately.  I've checked the recommended specs on the here https://github.com/Chia-Network/chia-blockchain/wiki/FAQ and don't see any issues.  I've tried different RAM and Thread setups.  I'm running on a 2019 Macbook Pro with 8 core i9 and I have 16g of RAM.  Could use your help as I've been trying to plot for 3 days now and have nothing to show for it.

**Comment by ngxiaoyi** [comment]
> Has anyone run into an issue where plotting freezes at 31%. I've tried plotting on a couple different drives including v-nand ssd, a WD external 2tb drive, and direct to my WD 8TB drive. All have gotten stuck at around 31%. I let my v-nand SSD sit and spin on that 31% mark over night and though it said it got to 35% this am, it was displaying the same error in in the log over and over. I should have screen shot it, but it said something like only wrote 74505 or 85606 blocks will try again in 5min. Has anyone run into a similar error? I've read some forums saying that many people have run into a slow down at 31%, but that leaving the drive to plot over several more hours did the trick. Mine did not, unfortunately. I've checked the recommended specs on the here https://github.com/Chia-Network/chia-blockchain/wiki/FAQ and don't see any issues. I've tried different RAM and Thread setups. I'm running on a 2019 Macbook Pro with 8 core i9 and I have 16g of RAM. Could use your help as I've been trying to plot for 3 days now and have nothing to show for it.

Same error + 1

**Comment by felisucoibi** [comment]
Same problem here, using a i7 7700hq laptop and the same it got stucked at 31 for a while, doing that phase....

**Comment by vildonfoo** [comment]
I had the same issue and ultimately after a few days of no show.. I even left the 31% to sit for more than a day, I bought a Mac to plot. Wish I had the answer but it just stopped working for me.

**Comment by zakiio** [comment]
yup same happening to me with i9 10900f, I had 10 plots staggered and running in parallel, I thought maybe it hit the CPU limit. left it for 2-3 hours and it was stuck on 31%. I deleted the temp and rebooted then started one plot only and it is still hang on 31% I am not sure what to do and I am basically having my CPU fired up while doing nothing. any suggestions?

**Comment by julianoviedo1** [comment]
Same

**Comment by devtrf** [comment]
Seems like I'm joining this group! Will update if anything changes.

**Comment by brezapour81** [comment]
RESOLVED:
So guys, I had the same issue and this was driving me mad as i'm sure it has been for others.

@hoffmang9 was correct, but I managed to narrow this down to memory module issue.

I have x2 32GB RAM and so i ran a windows memory diag on one at a time. To my surprise, it turned out one of the modules had a hardware fault.

I have since replaced that memory module and have not had the same issue since.

***If Interested, Seedpool.org is launching a new Chia Pool using the Officical Chia protocol's once released. Visit and register your interest in you are considering joining a Pool. The Pool will be UK Hosted.****

**Comment by dajevtic** [comment]
I had a similar (or actually the same) problem, however it was not due to a defect memory, but rather a misconfigured memory. After several hours of trying around, I noticed that my memory specs and the settings in the bios were not aligned. System seemed stuck at 31% where in fact it was so slow that phase 2 took several hours.
After reading my memory specs and adjusting the Bios (in my case XMP settings) I am now at approx. 4000s for phase 2.

Hope it helps anyone!

**Comment by mousakefa62** [comment]
Starting phase 2/4: Backpropagation into tmp files... Fri Jul  2 09:29:10 2021
Backpropagating on table 7
scanned table 7
scanned time =  1199.083 seconds. CPU (6.110%) Fri Jul  2 09:49:11 2021
sorting table 7
