### ISSUE TITLE
Any info on this warning?

### ISSUE THREAD

**Issue by corviato1** [Chia-Network/chia-blockchain#2314]
![Untitled](https://user-images.githubusercontent.com/44780076/115641734-8c8dd480-a2ce-11eb-8307-def2ae19335d.png)

**Comment by S0litaire** [comment]
A new version 1.1.0 released today. It's a warning you need to update the app before you reach that block.

https://github.com/Chia-Network/chia-blockchain/releases/tag/1.1.0

**Comment by Xorboo** [comment]
Introduced in [1.0.4](https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0.4), in a few days current version won't be able to farm it seems

**Comment by subz390** [comment]
Suggestion: Would be helpful for all the new people joining and anyone who wants reference to the policy, if messages like this had the option to open on the reference https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0.4 they relate to.

**Comment by amirdt22** [comment]
The application will stop working at block height 193536

(adding this text for search engines)

**Comment by mariano54** [comment]
You need to update before that height, the node will stop working at that point (since transactions will start)
