### ISSUE TITLE
Debian upgrade chia, git pull failed

### ISSUE THREAD

**Issue by syouko** [Chia-Network/chia-blockchain#2319]
Current version: 1.0.5

Current situation: After the installation without GUI is complete, no other changes have been made.
Only the automatic synchronization block has been completed

Use the upgrade method provided by the WIKI

> cd chia-blockchain
. ./active
chia stop -d all
deactivate
git fetch
git checkout latest
git pull

Then :
Automatic merge failed; fix conflicts and then commit the result.

Not familiar with using git, please help. thanks!

**Comment by lvcivs** [comment]
Your git repo got into a conflicted state somehow. Maybe try a fresh install? You could try the experimental GUI installer, then you don't have to mess with git: https://download.chia.net/latest/x86_64-Ubuntu-gui

If you want to continue with git, I would recommend to rename the folder `chia-blockchain` to `chia-blockchain.old`, then follow the instructions for a fresh install here (from `git clone ...` ): https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian
Your config and so on live in `~user/.chia/...`, so they will carry over even if you do a fresh install.

**Comment by syouko** [comment]
> Your local git repo got into a conflicted state somehow. Maybe try a fresh install? You could try the experimental GUI installer, then you don't have to mess with git: https://download.chia.net/latest/x86_64-Ubuntu-gui
> 
> If you want to continue with git, I would recommend to rename the folder `chia-blockchain` to `chia-blockchain.old`, then follow the instructions for a fresh install here (from `git clone ...` ): https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian
> Your config and so on live in `~user/.chia/...`, so they will carry over even if you do a fresh install.

So even I delete ALL git files. The node information I synced will not disappear?
That's so good
