### ISSUE TITLE
[BUG] Pop up message : the application will stop working at block height 193536, using chia 1.0.5

### ISSUE THREAD

**Issue by Last-Airbender** [Chia-Network/chia-blockchain#2322]
**Describe the bug**
I've already upgraded to chia 1.0.5 a few days ago but the app just showed the message today.

**To Reproduce**
The warning pop up message was shown this morning when the machine was farming and plotting.

**Expected behavior**
The warning message should only be occurred in 1.0.4, why is it in 1.0.5?

**Desktop (please complete the following information):**
- OS: Windows 10 64
- CPU: intel 8700k

**Additional context**
What should I do?

Thanks before,

**Comment by hoffmang9** [comment]
The warning message is working as intended and it is supposed to be in 1.0.5 as well.

**Comment by Last-Airbender** [comment]
Thank you
