### ISSUE TITLE
[BUG] Unable to Update/Upgrade from 1.0.3 to Latest on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by bubblequeen** [Chia-Network/chia-blockchain#2328]
**Describe the bug**
Unable to successfully update from 1.0.3 to Latest on Ubuntu 20.04.2 LTS.

**To Reproduce**

1. Successfully Plot and Farm on 1.0.3
2. Follow instructions To Update/Upgrade
3. See the results from Update below:

christian@NUC10i7FNH:~$ cd chia-blockchain
christian@NUC10i7FNH:~/chia-blockchain$ chia stop -d all

Command 'chia' not found, did you mean:

  command 'chi2' from deb paml (4.9j+dfsg-1)

Try: sudo apt install <deb name>

christian@NUC10i7FNH:~/chia-blockchain$ deactivate
deactivate: command not found
christian@NUC10i7FNH:~/chia-blockchain$ git fetch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), 425 bytes | 106.00 KiB/s, done.
From https://github.com/Chia-Network/chia-blockchain
   ccb42704..2c1386f7  torrent-workflow -> origin/torrent-workflow
christian@NUC10i7FNH:~/chia-blockchain$ git checkout latest
M	chia-blockchain-gui
Previous HEAD position was abc08721 changelog for 1.0.3
Switched to branch 'latest'
Your branch and 'origin/latest' have diverged,
and have 72 and 207 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
christian@NUC10i7FNH:~/chia-blockchain$ git pull

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'christian@NUC10i7FNH.(none)')
christian@NUC10i7FNH:~/chia-blockchain$ sh install.sh
apt-get is /usr/bin/apt-get
Installing on Ubuntu/Debian 20.04 LTS or newer
[sudo] password for christian: 
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease            
Ign:5 http://ppa.launchpad.net/bluetooth/bluez/ubuntu focal InRelease
Err:6 http://ppa.launchpad.net/bluetooth/bluez/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/bluetooth/bluez/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
christian@NUC10i7FNH:~/chia-blockchain$ . ./activate
(venv) christian@NUC10i7FNH:~/chia-blockchain$ chia init
Traceback (most recent call last):
  File "/home/christian/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/christian/chia-blockchain/venv/bin/chia", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.cmds.chia'
(venv) christian@NUC10i7FNH:~/chia-blockchain$ sh install-gui.sh
apt-get is /usr/bin/apt-get
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxss1 is already the newest version (1:1.2.3-1).
nodejs is already the newest version (10.19.0~dfsg-3ubuntu1).
npm is already the newest version (6.14.4+ds-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Installing on Ubuntu 20.04 LTS or newer: Using installed node.js version
Running git submodule update --init --recursive.

error: Your local changes to the following files would be overwritten by checkout:
	package-lock.json
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '1dcfd1e8c057a3decee76a59dad60ecb673d5318' in submodule path 'chia-blockchain-gui'
(venv) christian@NUC10i7FNH:~/chia-blockchain$ cd chia-blockchain-gui

**Expected behavior**
GUI should open

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.2 LTS
- CPU: Intel NUC10i7FNH

**Additional context**

**Comment by lvcivs** [comment]
The `chia stop` command fails because you are not in the python `venv`. Try running ". ./activate" first in that directory.

You haven't set up `git` properly yet. That's why `git pull` fails. Follow the instructions printed in the terminal to add at least an e-mail address.

The `install.sh` script then fails as a result of the previous problem: not having checked out properly.
