### ISSUE TITLE
Where is the bottleneck of plotting

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#2329]
I have solved all the bottleneck problems needed for drawing, including CPU computing power, IO and DRAM. These utilization rates are very rich. Why hasn't the drawing efficiency been improved.

Use DRAM to allocate to TMP (about 450gib). It takes about 12 hours to view the current progress.
hardware configuration：CPU 48Core,memory 500 GiB。
The parameters I use are:
create -k 32 -b 4608 -u 128 -r 2 -n 10  and 
create -k 32 -b 4608 -u 32 -r 32 -n 10

**Comment by mariano54** [comment]
Please see the wiki for plotting tips, or read the articles in https://chiadecentral.com/
