### ISSUE TITLE
Pagination for unspent coins?

### ISSUE THREAD

**Issue by freddiecoleman** [Chia-Network/chia-blockchain#233]
Currently the `get_unspent_coins` endpoint of the RPC server is returning 1069 results and is 301KB in size. This is OK for now but I guess it is going to keep getting bigger and pagination will eventually be useful.

Low priority.

**Comment by mariano54** [comment]
Yes that's a good point. Let's see if we can add this without breaking anything for 1.7

**Comment by mariano54** [comment]
Working on changing this to be called get_coins, and take limit and offset arguments. Perhaps also adding a flag for unspent/spent.

**Comment by mariano54** [comment]
Do you have a specific form you would like for get_unspent_coins? @freddiecoleman 

How about specifying a start_height and end_height. So you can get unspent coins for that puzzle hash  between blocks 100k and 120k for example. This would be the simplest from the backend, and does require storing progress state in memory.

The more complicated way would be that you request 1000 at a time, we return the 1000 entries and a cursor. For the next call, you just provide the cursor and we return another 1000, etc. It seems better but also requires storing state in the backend so we don't read the DB over and over, and to return a consistent result.

**Comment by mariano54** [comment]
Fixed in https://github.com/Chia-Network/chia-blockchain/pull/989
