### ISSUE TITLE
[BUG] 1.1.0 not farming

### ISSUE THREAD

**Issue by berlef80** [Chia-Network/chia-blockchain#2331]
**Describe the bug**
Upgraded to 1.1.0 and it is showing as the last plot synched being a few minutes ago, but does not show as synced and so is not farming.  Closed it out and reopened and now 25 minutes later it is not synced at all from when I closed it

Using GUI - going to downgrade so I can farm, but

**Comment by berlef80** [comment]
Downgraded - now also stuck there at 8:09pm.  Super frustrating

**Comment by maomingyang1314** [comment]
It seems that my Mac and Windows have also encountered this problem, so I chose to downgrade. Write slowly

**Comment by fueler** [comment]
I'm experiencing the same issue.

**Comment by maomingyang1314** [comment]
It is estimated that this is a new version, there are some problems, you can wait for the next version.

**Comment by mariano54** [comment]
Please do port forwarding on 8444 if you cannot get peers

**Comment by mariano54** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by Trololosha17** [comment]
everything is the same, only on version 1.0.5 now also does not farm

**Comment by Trololosha17** [comment]
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

Of course we are all dumb, but version 1.1.1 came out by accident right?
