### ISSUE TITLE
[BUG] Connecting To Wallet on Mac

### ISSUE THREAD

**Issue by egorgolo** [Chia-Network/chia-blockchain#2333]
**Describe the bug**
"Connecting to wallet" screen doesn't disappear. 

**To Reproduce**
I have tried installing and reinstalling all versions but it didn't help. I tried deleting mainnet folder each time I installed and launched new version of blockchain, didn't help. I tried to delete db folder separately too and it didn't help. 

**Expected behavior**
Access the miner. 

**Screenshots**
![Снимок экрана 2021-04-21 в 20 57 11](https://user-images.githubusercontent.com/82991798/115653867-d4b7f180-a2e4-11eb-9f3a-60142b6d1705.png)

**Desktop
- OS: MacOS Mojave 
- OS Version 10.14.6 (18G103)
- CPU 2,8 GHz Intel Core 2 Duo
- 4 GB 1067 MHz DDR3

**Comment by j4ys0n** [comment]
Having the same issue. Different hardware. On 10.15. No error message other than it can't connect in dev tools.

**Comment by radvansky-tomas** [comment]
Thats probably related https://github.com/Chia-Network/chia-blockchain/issues/2313

**Comment by j4ys0n** [comment]
Not sure - I'm on a Ryzen hackintosh.

**Comment by saschaeggi** [comment]
Also #2269

**Comment by saschaeggi** [comment]
And #2275

**Comment by kilianso** [comment]
These steps resolved the issue for me on Catalina 10.15.7

1. Close Chia Client
2. Upgrade to Chia Version 1.1
2. Delete the "wallet" folder in `.chia/mainnet/`
3. Delete the "peer_table_node.sqlite" in `.chia/mainnet/db` (Do not delete the mainnet one. It will take a long time to sync if you have to start from zero again)
4. Reopen Chia Client

I turned off UPnP but I don't think this makes a difference.
Hope that helps.

**Comment by egorgolo** [comment]
> These steps resolved the issue for me on Catalina 10.15.7
> 
> 1. Close Chia Client
> 2. Upgrade to Chia Version 1.1
> 3. Delete the "wallet" folder in `.chia/mainnet/`
> 4. Delete the "peer_table_node.sqlite" in `.chia/mainnet/db` (Do not delete the mainnet one. It will take a long time to sync if you have to start from zero again)
> 5. Reopen Chia Client
> 
> I turned off UPnP but I don't think this makes a difference.
> Hope that helps.

![Снимок экрана 2021-04-22 в 9 13 59](https://user-images.githubusercontent.com/82991798/115748635-30b56100-a34b-11eb-9d16-754b1072ea5e.png)
I have tried your method but unfortunately it didn't help. I can't find  "peer_table_node.sqlite" in .chia/mainnet/db.

**Comment by egorgolo** [comment]
> Having the same issue. Different hardware. On 10.15. No error message other than it can't connect in dev tools.

![Снимок экрана 2021-04-22 в 9 24 57](https://user-images.githubusercontent.com/82991798/115750124-ae2da100-a34c-11eb-89b8-349db188071c.png)

**Comment by kilianso** [comment]
@egorgolo Hmm the only thing I could think of as a quickfix is to backup the mainnet database file, then delete the entire `.chia` folder and then reopen the client. But as I said, it could take a very long time to create a new mainnet database file. So you could try to use the backup instead. However, I am not a maintainer of this project, so I don`t know what causes these issues in the first place and if this is the right solution.

**Comment by egorgolo** [comment]
@kilianso i've tried that too, but the problem didn't disappear unfortunately. Anyways, thanks for advice

**Comment by egorgolo** [comment]
Update: 

I think I found the problem. Before launching chia in my home network through this computer, I opened it first at my newer MAC. The app probably assigned port 8444 to the computer where I at first opened the app. Anyways, check if your port 8444 is open. If it's closed, you need to open it and the app should start working. It won't work if port 8444 is closed.

 *Note one port can only be assigned to one IP. (That's why I wasn't able to open port 8444 through terminal on the Mac that I wanted to use for mining) Please correct if I'm wrong.
