### ISSUE TITLE
[BUG] OS disk cache on Windows limiting I/O performance

### ISSUE THREAD

**Issue by zhaoyangwx** [Chia-Network/chia-blockchain#2337]
**Describe the bug**
Windows disk cache writes in serial, leave only one disk fully loaded and other disks idle. Please disable system cache for plotting.

**To Reproduce**

Plot in parallel using different disks for cache

**Expected behavior**
All disks can be fully loaded simultaneously.

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by stackisok** [comment]
I met this problem too.

**Comment by stackisok** [comment]
how can i contact with you? email，wechat or qq

**Comment by zhaoyangwx** [comment]
> I met this problem too.
You may try my modified version of ProofOfSpace for HDD plotting.
https://github.com/zhaoyangwx/chiapos/actions/runs/825267787
This version empties OS cache every 30 turns of flush operation, and forces bitfield on.

**Comment by stackisok** [comment]
> > I met this problem too.
> > You may try my modified version of ProofOfSpace for HDD plotting.
> > https://github.com/zhaoyangwx/chiapos/actions/runs/825267787
> > This version empties OS cache every 30 turns of flush operation, and forces bitfield on. Plus modifying tmp file directory structure (i.e. for symlink compatibility) and output info with phase #.

Thanks.I'll try it.

**Comment by Audionut** [comment]
I'm seeing the same issue.

It feels like a chipset, or bus limitation, as in, starting a new plot on a different cache drive slows down other plots. I can clearly see the cache drive speeds slowing on my fast NVME if I start a plot entirely on HDD's.
