### ISSUE TITLE
[BUG] Syncing forever... and the aplicattion closes and stays on background working (kind of a crash)

### ISSUE THREAD

**Issue by elcabezon22** [Chia-Network/chia-blockchain#2338]
S.O: Windows 10 x64.
ryzen 5 3400g, 16gb ram at 3000mhz, 1 ssd 250gb and other hdd 2Tb.

I have reconfigured the temp folder in my ssd and mining 600mb plots (because my sdd is small)... and the final node goes to the 2Tb hdd folder.

When i left the machine mining always crashes, but when i search in the task manager i can see "star_full_node.exe" working... anyways when i run the app it looks like crashed, and i have to start all over again.

when i start a plot i configure the default ram usage (512 Mb) to 2000Mb and i put 29 plots.

 Also there's being 4 days since I've started with this and the app says "Syncing" it never changes.
 
 i appreciate any help.

 regards and i love what you are doing for the community.

**Comment by mariano54** [comment]
Did you do port forwarding as explained in the wiki FAQ?

**Comment by mariano54** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by elcabezon22** [comment]
Hello, suddenly everything started working fine today. all the plots are connected and farming now (i didn't do nothing).

Thanks for the help, if something change i will write about it.
