### ISSUE TITLE
Does this warning affect the reward？

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#2346]
14:22:21.425 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:22:55.177 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:23:23.771 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:24:47.149 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:24:47.483 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:25:16.899 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:25:17.892 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:25:19.206 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:25:55.137 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:26:10.385 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:26:23.769 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:27:29.846 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:27:46.424 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:27:50.546 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting
14:27:55.419 timelord timelord_server          : WARNING  Peer surpassed rate limit 127.0.0.1, message: 2, but not disconnecting

**Comment by furkan16** [comment]
hi, there is a problem i'm trying to understand warning is this is blocking xch gains?
