### ISSUE TITLE
How to upgrade Chia running with docker？

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#2358]
①docker pull ...

②docker run ...

③chia keys add ...

Is this how docker upgrades？

**Comment by botanegg** [comment]
What container do you use?

**Comment by qian-fei** [comment]
> What container do you use?

docker pull ghcr.io/chia-network/chia:latest

**Comment by qian-fei** [comment]
> What container do you use?

The image you provided

**Comment by qian-fei** [comment]
> What container do you use?

How to upgrade from an old version

**Comment by dmifly** [comment]
just pull and run a new is ok

**Comment by qian-fei** [comment]
Add previous wallets through Chia add keys?

**Comment by botanegg** [comment]
If you are **sure** that you have forwarded all directories (keys, plots and etc), you can simply delete the old container and just pull again

**Comment by dmifly** [comment]
@botanegg Hi. I am doing as your said. And I need to do the docker CLI ' chia plots check' every time. Otherwise the farmer can not recognize his already has a plots file for it to farm.

**Comment by botanegg** [comment]
Did you run new container with `-e farmer="true"`??

**Comment by botanegg** [comment]
I suggesting to @justinengland and `Chia-Network/chia-docker` is adding `docker-compose.yml` for better configuring and easily updating

I can try to make this file on the weekend, but I have low-experienced  in `docker-compose` configuration

**Comment by botanegg** [comment]
@dmifly It seems like you need to run `docker exec -it chia venv/bin/chia plots add -d /plots` after updating
