### ISSUE TITLE
Plots config file is not updated correctly when running multiple concurrent plotting processes

### ISSUE THREAD

**Issue by LeonidShamis** [Chia-Network/chia-blockchain#236]
I had 4 plots configured and farmed and I started plotting 6 more plot files in parallel by starting 6 chia-create-plots separate background processes (Ubuntu 20.04, beta-1.0b5). After plotting has completed I could see all 10 plot files at their expected destination locations, BUT I only found 5 plot files defined in config/plots.yaml 😟 There must be a bug with multiple concurrent processes trying to write to config/plots.yaml file. I notices that the only new plot file that was written to plots.yaml was one created by last out of 6 plotting processes that I has running in parallel.

I suspect that all concurrent plotting processes loaded the same plots configuration https://github.com/Chia-Network/chia-blockchain/blob/0eae1e0a6b9ad3dd0d12e5892a9089b16c20f190/src/cmds/create_plots.py#L99 and then started preparing their respective changes. https://github.com/Chia-Network/chia-blockchain/blob/0eae1e0a6b9ad3dd0d12e5892a9089b16c20f190/src/cmds/create_plots.py#L100 After long plotting time https://github.com/Chia-Network/chia-blockchain/blob/0eae1e0a6b9ad3dd0d12e5892a9089b16c20f190/src/cmds/create_plots.py#L113 each processes updated new plots configuration https://github.com/Chia-Network/chia-blockchain/blob/0eae1e0a6b9ad3dd0d12e5892a9089b16c20f190/src/cmds/create_plots.py#L132 and saved it, https://github.com/Chia-Network/chia-blockchain/blob/0eae1e0a6b9ad3dd0d12e5892a9089b16c20f190/src/cmds/create_plots.py#L135 essentially overriding configuration saved by other processes that completed earlier.

(keybase://chat/chia_network.public#testnet/10332)

**Comment by hoffmang9** [comment]
Found and will be fixed in beta 1.6 - https://github.com/Chia-Network/chia-blockchain/pull/244/commits/760e52703ff4e3a327fa7665401735c2f9a58ce6
