### ISSUE TITLE
windows server 2019

### ISSUE THREAD

**Issue by 815584445** [Chia-Network/chia-blockchain#2366]
![image](https://user-images.githubusercontent.com/54569978/115688150-75fa8280-a38d-11eb-8f11-7c31158eb71b.png)

**Comment by calxibe** [comment]
I have the same issue, works fine on windows 10, but both windows server 2016 & 2019 isn't working.

Found any workaround? (i have disabled firewall without any more luck)

**Comment by m-holler** [comment]
Same issue in my case, it wont work. On Win10 no Problem. Is there a bugfix or workaround ?

**Comment by gunshit** [comment]
I use Server 2019 and the client is working properly

**Comment by compidoc** [comment]
I'm running Win Server 2016 and Client is working, but sync is VERY slow. Its out of sync for over a week now with port 8444 reachable and connected to 50+ nodes. On my Win10 Laptop its running fine even without port 8444.

**Comment by gunshit** [comment]
> I'm running Win Server 2016 and Client is working, but sync is VERY slow. Its out of sync for over a week now with port 8444 reachable and connected to 50+ nodes. On my Win10 Laptop its running fine even without port 8444.

Same here but... I'm on Server 2019. Sync is a nightmare. 10 plots and no sync for 3 days now. About peers, only 8 connected and 8444 port is open and reachable from outside. I don't know what else to check :-\. I followed this guide just in case if of any use to you: https://thechiafarmer.com/2021/04/20/syncing-problems-on-windows/

Regards

**Comment by omjanu** [comment]
What would y’all recommend. Win10 or Win server 2019 for a 4U server to plot and farm chai

**Comment by gunshit** [comment]
> What would y’all recommend. Win10 or Win server 2019 for a 4U server to plot and farm chia

Well, I don't see any advantage on using WServer over W10. W10 is cheaper and the configuration is easier. I use Wserver just because I already have a mini server with that OS installed.

Regards

**Comment by compidoc** [comment]
> What would y’all recommend. Win10 or Win server 2019 for a 4U server to plot and farm chia

I would recommend win10, because many people have problems with win server. My actual solution is that my win servers only plot and I have a virtual win 10 machine as a full node where all plotters are connected.
