### ISSUE TITLE
[BUG] pip/pip3 in install.sh on Debian

### ISSUE THREAD

**Issue by TiAM0** [Chia-Network/chia-blockchain#2367]
By default install.sh tries to use 'pip' while in Debian by default it's pip3

To solve it I did    ln -s /usr/bin/pip3 /usr/bin/pip   but I guess   alias pip=pip3   could also have worked.

But a better solution may be for the install.sh script to check whether it should use pip or pip3 for the installation.

Debian amd64 10.9

**Comment by hoffmang9** [comment]
Install.sh should drop into a compatible venv before calling pip. In that venv pip will be the right version. Something else did not work?

**Comment by TiAM0** [comment]
Nope, that was it, everything else worked as expected.

**Comment by hoffmang9** [comment]
Can you give me the full output of install.sh without pip3 aliased and not in the venv?
