### ISSUE TITLE
Slow copy time at the end of plot creation

### ISSUE THREAD

**Issue by haowang1013** [Chia-Network/chia-blockchain#2368]
Hi,

I noticed that the final copy step is very slow when the plot is finally created. For example I have this in the log

```
Copied final file from "/mnt/raid0/chia-temp/0/plot-k32-2021-04-11-22-49-0b1fdac8f584bf9705fbfb9a9eb9259b68f96b02a3ada595d9aef2e002ff7797.plot.2.tmp" to "/mnt/USB/chia-staging/plot-k32-2021-04-11-22-49-0b1fdac8f584bf9705fbfb9a9eb9259b68f96b02a3ada595d9aef2e002ff7797.plot.2.tmp"

Copy time = 1942.756 seconds. CPU (6.550%) Thu Apr 22 17:32:16 2021
```

So it took over half an hour to copy the plot from a raid0 SSD into a USB 3.0 SSD drive.

The funny thing is that it only took about 8 minutes to rsync the same file from the USB 3.0 SSD drive to a USB 3.0 HDD drive.

I'm wondering if that 1942.756 seconds is only used for the copy, or is there any other operations involved that can cause the slow down? If there any way to improve the copy speed?

Thanks

**Comment by botanegg** [comment]
chiapos uses `fs::copy` method for this
https://github.com/Chia-Network/chiapos/blob/ce6ccc28ea300bfbad7e054a3f30433eb6090cf5/src/plotter_disk.hpp#L385
Gcc compiller can convert `fs::copy` to `sendfile` on Linux for copying file content.
`sendfile` is typically very fast (is more efficient than the combination of `read` and `write`)

Your speed is ~52MB per second, it is typically for overload SSD
So you need to check your SSD RAID to overload, I think you are creating a large number of parallel plotters
Every plotter makes a lot of writes and **reads**

**Comment by hoffmang9** [comment]
Your other option is to use another tool to move completed files from the SSD instead.
