### ISSUE TITLE
After the abnormal interruption of plots, the TMP file is still there. How to continue with plotstting?

### ISSUE THREAD

**Issue by Gump-II** [Chia-Network/chia-blockchain#2373]
After the abnormal interruption of plots, the TMP file is still there. How to continue with plotstting?

**Comment by erwinpgo** [comment]
I have issue in plotting, I tried 2 parallel and it is working fine, then I tried to add 1 plot in queue but it start running. Now it is plotting 3 at the same time now the Delete button is not working.  Do you have this issue also? My Temp SSD cannot support 3 plots at the same time

**Comment by errcodex** [comment]
I think you should try to delete manually

**Comment by ychost** [comment]
i also have the same question, but the process is continue, so wait until the process complete
