### ISSUE TITLE
[BUG] can't run cli command Windows 10 Chia client version 1.1.1

### ISSUE THREAD

**Issue by koleg** [Chia-Network/chia-blockchain#2376]
I try to run any CLI command in powershell  like in previous version
./chia plots check
but run GUI version client 

1. Start PS
2. cd  C:\Users\...\AppData\Local\chia-blockchain\app-1.1.1\
3.  ./chia plots check
4. run GUI client

**Comment by hoffmang9** [comment]
That is the wrong executable. This shows the correct path https://github.com/Chia-Network/chia-blockchain/wiki/Windows-Tips-and-Tricks#1-parallel-plotting-using-powershell
