### ISSUE TITLE
[BUG] Client 1.1.1 not syncing 

### ISSUE THREAD

**Issue by guarnacciaa** [Chia-Network/chia-blockchain#2377]
After upgrade from 1.0.5 to 1.1.1 on my Windows 10 machine, my Status keeps showing "Not Synced".

**Comment by ruddles** [comment]
I'm getting the same in 1.0.5
![image](https://user-images.githubusercontent.com/325764/115700955-29984e00-a35f-11eb-9477-84df07c7977e.png)

**Comment by ruddles** [comment]
So after 10 minutes of not syncing I posted that and it immediately started syncing.....

**Comment by rolandbezemer** [comment]
I installed V1.1 a few hours ago and it still is not syncing.

**Comment by rolandbezemer** [comment]
Can you force syncing?

**Comment by rolandbezemer** [comment]
After pressing the "Keys" button, and reselecting my private key, it started syncing.

**Comment by rolandbezemer** [comment]
And then it stopped syncing again.

**Comment by bakabakayaro** [comment]
I can sync now on 1.1.1 but for some reason my cpu temps are very high while farming. Not plotting or doing anything else

**Comment by IT2core** [comment]
same issue

**Comment by davidzyx** [comment]
Same here. There are multiple instances of the logs shown below at the `INFO` level
```
2021-04-22TXXXXXX full_node full_node_server        : INFO     -> handshake to peer XXX.XXX.XXX.XXX <node-id-XXX>
2021-04-22TXXXXXX full_node full_node_server        : INFO     Connected with full_node {'host': 'XXX.XXX.XXX.XXX', 'port': 8444}
2021-04-22TXXXXXX full_node full_node_server        : INFO     -> new_peak to peer XXX.XXX.XXX.XXX <node-id-XXX>
2021-04-22TXXXXXX full_node full_node_server        : INFO     Connection closed: XXX.XXX.XXX.XXX, node id: <node-id-XXX>
2021-04-22TXXXXXX full_node chia.full_node.full_node: INFO     peer disconnected {'host': 'XXX.XXX.XXX.XXX', 'port': 8444}
2021-04-22TXXXXXX full_node full_node_server        : INFO     Cannot connect to host XXX.XXX.XXX.XXX:8444 ssl:<ssl.SSLContext object at 0x0000015165261E48> [Connect call failed ('XXX.XXX.XXX.XXX', 8444)]

```

**Comment by joaopna** [comment]
Same error here, and I keep getting the following error:
Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: xxxxxxxxx

And also:
ConnectionResetError: Cannot write to closing transport

**Comment by pedronahum** [comment]
Same issue -- version 1.1.1. More than 4 hours trying to synch... Status doesn't show anything...

**Comment by rolandbezemer** [comment]
Partly syncing, and then stopping again.

**Comment by tdaubs** [comment]
Same issue as reported here. After upgrading to 1.1.1 client stops syncing.

**Comment by pedronahum** [comment]
I am using an external hard-drive and was almost full. By deleting 1 plot, the GUI managed to synch... I guess the GUI requires some space to synch?

**Comment by Dravenex** [comment]
I am having the same issues. On the 1.1.1 version and on versions before. Every time I upgrade to a newer version, syncing won't start again. I always need to delete the .chia/mainnet folder and start syncing again. This takes a lot of downtime with farming... Having this issue on Win 10 and Raspbian 64 bit.

**Comment by kikichilouis** [comment]
> I am having the same issues. On the 1.1.1 version and on versions before. Every time I upgrade to a newer version, syncing won't start again. I always need to delete the .chia/mainnet folder and start syncing again. This takes a lot of downtime with farming... Having this issue on Win 10 and Raspbian 64 bit.
> 
> Sounds like a network problem since I am having this issue on different OS. Maybe the router is blocking some connections to chia?

Dravenex
How to delete
.chia/mainnet folder. 
You mean to uninstall directly. and reinstall again?

  Got SAME issue here.
I don’t want to encounter the same problem every time when released upgrade

thanks

**Comment by rolandbezemer** [comment]
it suddenly started syncing up to 168227 / 168330 and then stopped again. Missing valuable farming time today..

**Comment by bobfredarctor** [comment]
I have the same problem. actually it doesn't connect to any nodes other than my computer. First time having this problem.

**Comment by hoffmang9** [comment]
You all need to open port 8444 to be able to let other nodes connect to you. Once you do, syncing becomes very reliable. https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by Dravenex** [comment]
Thanks for the info gene. But once I start the GUI on any Win machine, the GUI starts all of the services, including full node. How can I disable the automatic full_node start from my plotting machines?

**Comment by hoffmang9** [comment]
You can't yet but you can plot in PowerShell https://github.com/Chia-Network/chia-blockchain/wiki/Windows-Tips-and-Tricks#1-parallel-plotting-using-powershell
