### ISSUE TITLE
can i rename the final temp file to .plot?

### ISSUE THREAD

**Issue by jonny77** [Chia-Network/chia-blockchain#2378]
ploting  to   100% ,but the final disk has 90GB only. so  i stop the client and cleaned up the disk , but the ploting task is missing while i restart   client.   can i rename the .tmp file to .plot directly?

**Comment by chenzhao-py** [comment]
nah you just lost it, need to start over

**Comment by Franpepper** [comment]
Just wait a few minutes, my client crash at 99% ploting, i restarted, and after 20 minutes, my plot is ready

**Comment by lvcivs** [comment]
Check whether the temp file has the right size (ca. 101.4 GiB for a k32). If the process was interrupted during the final phase of copying the plot to the final destination, it should work to simply rename the temp file. 

You can make sure whether the plot is OK by running `chia plot check` from the Terminal: https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#check

**Comment by Dravenex** [comment]
Ignore the previous comments. If your plot made it through all 4 phases, you can rename the file from ".plot.2.tmp" to ".plot". The plot works fine. Check with `chia plot check` afterwards. I did it several times and never had any problems with it.

**Comment by phtp** [comment]
I can confirm the last two comments. I had to do this multiple times and all pass when performing the checks.

**Comment by jonny77** [comment]
> Check whether the temp file has the right size (ca. 101.4 GiB for a k32). If the process was interrupted during the final phase of copying the plot to the final destination, the plot may in fact be finished and it should work to simply rename the temp file.
> 
> You can make sure whether the plot is OK by running `chia plot check` from the Terminal: https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#check

how can i do this on windows?
