### ISSUE TITLE
Computer memory is very high

### ISSUE THREAD

**Issue by hesen2006cn** [Chia-Network/chia-blockchain#2379]
centos 8
chia plots create -k 32 -e -b 2000 -r 2 -t /home/plots-tmp -d /home/plots-final >> plots1.log 2>&1 &

![image](https://user-images.githubusercontent.com/909288/115706820-a26bca00-a3a0-11eb-9dd8-c689861e5a96.png)

**Comment by maomingyang1314** [comment]
Do you use SSD to draw pictures?

**Comment by hesen2006cn** [comment]
no, use HDD
