### ISSUE TITLE
Full node will never sync if another peer establishes a connection during startup

### ISSUE THREAD

**Issue by freddiecoleman** [Chia-Network/chia-blockchain#238]
I am using the peer protocol to handshake and establish a connection (I do other stuff later on but that is not relevant to the issue).

It all works fine as long as I do this on a chia node that is already up and running. The thing is that I am doing this with docker containers so what happens is I will tear everything down and start from the beginning and it will try to connect and handshake immediately while the chia node is still booting up.

When I do this it prevents the node from ever being able to sync and get up to date. It happens every single time, but if I do not do the handshake during the startup everything works and it syncs as expected, I can then connect after this has happened and it continues to work while I am connected. I tried increasing the desired peer count before I realised this was the issue and that did not make a difference.

I see the following error which might be relevant:

```
FullNode asyncio                : ERROR    23:09:00.521 _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
asyncio.exceptions.CancelledError
```

It seems I can also interfere with the node while it is still syncing by connecting to it. Without looking at the code I am guessing nodes do not normally become discoverable until after they are up to date? Which would prevent this from normally happening.

**Comment by mariano54** [comment]
Can you send me a log of that node on keybase?
So if I understand what you are saying, the node is in a docker container, and while it is booting up you connect to it, and that crashes it somehow? 
Which phase is the full node in, is it already syncing to some other node when you connect to it?

Nodes become discoverable right away (on first contact with introducer) and they accept connection during sync too. You should be able to get new connections while you are syncing, that is not a problem. (However syncing peers disconnect from peers that don't have the requested blocks)
