### ISSUE TITLE
When reloading the screen gets stuck on "connecting to wallet"

### ISSUE THREAD

**Issue by ElrondElvenKind** [Chia-Network/chia-blockchain#2383]
**Describe the bug**
When clicking reload or force reload it doesn't actually reload it just does an infinite loop of "connecting to wallet"
**To Reproduce**

1. Go to view
2. Click on reload or force reload
3. See error

**Expected behavior**
I mean I expected it to reload or refresh the GUI

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: Ryzen 3600
**Additional context**

I'm using 1.1.1 but the exact same thing happened on 1.0.5

**Comment by dexter74** [comment]
Fix : https://github.com/Chia-Network/chia-blockchain/issues/2148

**Comment by garyhkirk** [comment]
Did you have problems with plotting before trying the refresh? I had a plotting fail and then refresh went into an infinite loop. If you force a quit and restart, please check the logs on any plots that were running. If you find they broke please post screenshots of the last part of the log. I think there are overflow errors that are breaking things

**Comment by Ivaylo-Lafchiev** [comment]
Also experiencing this, I really want to know how to fix this without having to restart the app and cancel all the running plots.

**Comment by dexter74** [comment]
My Batch reload :

```
@echo off

taskkill /f /im chia.exe		
taskkill /f /im start_wallet.exe		
taskkill /f /im start_full_node.exe		
taskkill /f /im start_farmer.exe		
taskkill /f /im start_harvester.exe		
taskkill /f /im start_farmer.exe		
taskkill /f /im daemon.exe		

:: Plotting - Hard Disk
rd /S /Q D:\

rd /S /Q "C:\Users\teste\.chia\mainnet\config"

C:\Users\teste\AppData\Local\chia-blockchain\Chia.exe


```

**Comment by Ivaylo-Lafchiev** [comment]
> Can you upgrade client ? (1.1.1 is a last release and the version bug : 1.0.5)
> 
> CMD : Kill & reload CHIA (Plottings is lost)
> 
> ```
> @echo off
> 
> taskkill /f /im chia.exe		
> taskkill /f /im start_wallet.exe		
> taskkill /f /im start_full_node.exe		
> taskkill /f /im start_farmer.exe		
> taskkill /f /im start_harvester.exe		
> taskkill /f /im start_farmer.exe		
> taskkill /f /im daemon.exe		
> 
> :: Plotting - Hard Disk
> rd /S /Q D:\
> 
> rd /S /Q "C:\Users\teste\.chia\mainnet\config"
> 
> C:\Users\teste\AppData\Local\chia-blockchain\Chia.exe
> ```

I am already running 1.1.1

It looks to me like this batch script will delete the plotting progress, so it doesn't really solve the problem.

**Comment by BestNgineering** [comment]
I'm facing the same problems.

And I'm wondering what should I do. Will the plotting process stop and do I need to restart plotting process?

**Comment by dexter74** [comment]
Hello,
My solution is useful for closing and relaunching the CHIA, its only vocation.

I'm just sharing my point of view on how to relaunch the CHIA when it crashes.

Currently since the tool does not delete the plots, my delete command is very useful but extremely dangerous if you don't know what you are doing. (It purges the hard disk corresponding to the CHIA)

**Comment by BestNgineering** [comment]
Thanks, I had solved it.

I just minimize the window and use other programs for about 30 minutes, then get back to the Chia gui. Then it connected, and get back to plotting.

**Comment by Ivaylo-Lafchiev** [comment]
Why was this closed? Waiting 30 minutes and hoping that the GUI will reconnect is hardly a resolution.

**Comment by BestNgineering** [comment]
> Thanks, I had solved it.
> 
> I just minimize the window and use other programs for about 30 minutes, then get back to the Chia gui. Then it connected, and get back to plotting.

To be clear, wait for 30 minutes doesn't work, unless the window is minimized. And I don't think we should let it be like this, so it shouldn't be closed!
