### ISSUE TITLE
32 bit Integer overflow causing Unknown exception (and other issues) on Windows 10 - Chia 1.1.1 and 1.1.0

### ISSUE THREAD

**Issue by garyhkirk** [Chia-Network/chia-blockchain#2384]
Resubmission of a **potentially critical error** outlined by another user in https://github.com/Chia-Network/chia-blockchain/issues/2249 - I added to the report when using 1.1.0 but have had the same issue with 1.1.1 so I think it's worth flagging. Apologies if that's not the way it works... just trying to help (and get plotting!)

**Describe the bug**
When plotting on a Windows 10 machine with either 1.1.0 or 1.1.1 there is an intermittent bug that (very likely given the screenshots) triggers when write entries pass the limit for a 32-bit unsigned integer. The count of written entries no longer matches the tally of created entries, this causes an Unknown exception that breaks several things. You cannot then delete the broken plot via the GUI (have not tried command line as a new user), you also cannot gracefully shut down the node (it hangs on shutdown requiring a forced quit).

**To Reproduce**

1. Start plotting a K-32 on a Windows 10 (possibly only Pro, that's my setup) via the GUI 
2. Wait for the bug to happen (sorry, I don't know how to trigger it) - screenshots below

**Expected behavior**
I expected the plot to run but it didn't, and it didn't report any problems... I had to manually check the progress to see that the process had failed.

**Screenshots**
<img width="727" alt="ChiaError" src="https://user-images.githubusercontent.com/8881383/115724133-93712180-a378-11eb-81a2-dd2dd40a9628.png">
<img width="727" alt="ChiaError2" src="https://user-images.githubusercontent.com/8881383/115724134-9409b800-a378-11eb-9fe5-61bcc9927fbe.png">
<img width="728" alt="ChiaError3" src="https://user-images.githubusercontent.com/8881383/115724135-9409b800-a378-11eb-970c-4d42fe6746b3.png">

**Desktop (please complete the following information):**

- OS: Win 10 Pro
- CPU: Ryzen 5800X
- RAM: 80GB
- Temp: 1TB NVME
- Target: 2TB SATA 3.5" 

**Additional context**
The system does have a 3090 installed and mining via lolminer, this doesn't seem to impinge on the resources needed for Chia but might help with diagnosis. All permissions were allowed for Chia, it's not a network access issue. I think it's an issue with a 32 bit integer comparison happening in the code somehow.

**Comment by wbkys** [comment]
me too

**Comment by evansrightherecoding** [comment]
same error here. 
I was using an external nmve drive enclosure. 
The error happens every time when I use an external drive as the temporary directory.
It got fixed after I installed it on the board as an internal drive.
I'm not sure if the error is related to macOS's USB hard drive sleep mechanism.

**Comment by hoffmang9** [comment]
These are hardware and sometimes swap errors but sadly not bugs in the plotter.

**Comment by hoffmang9** [comment]
Meant to leave this open just to have more review of the possibility of a 32 bit number being where it shouldn't be on Windows.

**Comment by garyhkirk** [comment]
I am plotting on a different drive to see if that works, I will update as soon as I get the result. One worrying thing is that the Windows GUI has now semi-crashed on me for the first time - it opens but there are no graphics, just white space apart from the menu items. Minimising then maximising doesn't work, don't want to do any more as the plotting still seems to be active.

**Comment by x3style** [comment]
I have the same issue:

OS: Win 10 Pro
CPU: Intel Core I7-5820K
RAM: 32GB
Temp: 2TB SATA 3.5"
Target: 2TB SATA 3.5"

I'm doing more testing as I have a lot of Samsung Spinpoint HDD's. I've noticed it mainly fails when I start plotting in parallel on multiple drives. I started it on 2 and one seems to, so far, be working while the other gives me that error.

The drive has no errors and has worked fine for years and still does I even did a surface scan the other day. I've now repartitioned it and reformatted it just to be sure, will let you know how it goes.

**Comment by x3style** [comment]
Same error on same drive even after surface scan, partition deletion and reformatting.
![Chia_Plot_Fail_3](https://user-images.githubusercontent.com/84071923/117962630-58c72d00-b317-11eb-9e95-3f2a72e7621e.JPG)
Meanwhile on the same system a different drive works perfectly. Worth nothing all attempts where parallel plotting.

**Comment by x3style** [comment]
So far seems to be happening to a single drive out of 4. But it is consistent, it will error out around the same time every time I start it. The drive is connected to the same controller like the others that work, so it has to be something individual to the drive. The drives are as follows:

Samsung Spinpoint F1 - 1TB - Works
2x Samsung Spinpoint F3 2TB - Works
Samsung Spinpoint F4  2TB - Fails consistently around 6%.

I've Plotted on the other drives so far and want to see if I can farm from the drive post plotting.

**Comment by x3style** [comment]
I wonder what problem the drive has, it works perfectly fine and it does not give any errors on any software, no chkdsk errors, no surface scan errors or bad sectors, same controller like the working drives, and can hold the plots for farming no problem.

What is the nature of the problem here?

**Comment by prophetz2021** [comment]
i have the same problem. are there any way to fix it?

**Comment by x3style** [comment]
> I have the same problem. are there any way to fix it?

I just stopped plotting on that drive, i have no idea why it does not work for this work specifically but it works just fine for anything else. Maybe a hardware issue, cable issues, no idea really. But its just plotting that has an issue with the drive.

**Comment by prophetz2021** [comment]
Hey guys i think i have a solution for this error.i can plot 100% complete now. all i did is format a drive that use for temp. 
"Full format not quick format". i also change a sata cable too. i use a same ram stick as before, everything work fine. 
just try it guys hope this can help you all.
