### ISSUE TITLE
Add farmland is not allowed to delete

### ISSUE THREAD

**Issue by yzn5555** [Chia-Network/chia-blockchain#2388]
Update to the latest version today, add multiple farms, and found that the tasks in the queue and the farming land cannot be deleted，There is no such problem in version 1.0.5, is there something wrong?
There is also how to check the version number in the software. I did not find a place to check the version number, and I am not sure whether I have updated to the latest version.
![image](https://user-images.githubusercontent.com/36029121/115729345-eddda280-a3b7-11eb-8277-ad1388e587ef.png)

**Comment by vladymyrkulinich** [comment]
1) Same issue I have:
![2021-04-22_17h26_16](https://user-images.githubusercontent.com/44829988/115732575-c45d5080-a390-11eb-9fa5-0981aac9849d.png)
2) Is there any way to use plots created from another account (key)?

**Comment by jayMcBee** [comment]
Deleting is currently disabled - see project board

**Comment by dorkmo** [comment]
The delete button had a bug and was not working. so they temporarily disabled until it is fixed
