### ISSUE TITLE
Windows 10 chia GUI crashes after running for ~18 hours

### ISSUE THREAD

**Issue by bill-95** [Chia-Network/chia-blockchain#2393]
Based on event log:
Faulting application name: Chia.exe, version 1.0.5.0
Faulting module name was KERNELBASE.dll (C:\WINDOWS\System32\KERNELBASE.dll)
Exception code: 0xe0000008

This has happened 2 days in a row now.

For the most recent time, I had 5 plots running at the time the GUI and daemon process suddenly closed.

The daemon process was consuming ~9GB of memory at the time before crashing, some kind of memory leak?

It seems to not affect the plotting processes since they are still running in background.

**Comment by wct097** [comment]
I am having the same issue.  Persisted with version 1.1.1.0 this morning.
![error1](https://user-images.githubusercontent.com/38669643/116085874-425d7800-a66d-11eb-9518-14e20da95fec.PNG)
![error2](https://user-images.githubusercontent.com/38669643/116085956-54d7b180-a66d-11eb-8084-8cd70d310c37.PNG)
![erro3](https://user-images.githubusercontent.com/38669643/116086085-72a51680-a66d-11eb-9faf-17f8e192d7a6.PNG)

I can add the crash report from Windows if that would be useful

**Comment by bill-95** [comment]
After updating to version 1.1.2 and starting plotting processes from CLI, have not experienced the error since then.

**Comment by hoffmang9** [comment]
The GUI has a resource leak that we are working to fix. This is also a duplicate though.
