### ISSUE TITLE
Is unclear when (if?) we get a reward on the UI

### ISSUE THREAD

**Issue by mamcx** [Chia-Network/chia-blockchain#2394]
I have been running the UI for some days now and is not clear to me if I will get rewards or not.

In the Farm section, it says "3 years to win". If that is the case is not worth it for me :).

In plots, I have one and say "farming". The balance in the wallet is zero.

----

I have run miners in the past and this is not similar to them. I get rewards daily (even if very small) and the UIs/command line shows it. Also, is not clear to me if "Farm" & "Plots" is the same things or 3 different ways to get chias.

For people doing this know if/when get rewards is the most useful info IMHO.

**Comment by dorkmo** [comment]
if you dont plan on having a large amount plotted, it will probably be best to join a pool when they are available

**Comment by mamcx** [comment]
According to the wording https://www.chia.net/faq/:

> Farming is more decentralized because it relies on empty hard disk space and anyone with a mobile phone, laptop, or corporate network tends to have extra space not currently being used. Unlike mining, once you’re done farming your storage you can repurpose it to, for example, store your family photos.

So if this is only for people that invest a lot on the hardware then is not for "anyone". 

P.D: With K-32 is it truly 3 years to get 1 chia?

**Comment by liyan1241** [comment]
could i delete the plots in my hardrive once they have been synced online? maybe this is the way to save a lot of investment for the hard-disk purchase as we could ploting in the same hard-disk over and over again, maybe is more environmentally friendly too.

**Comment by liyan1241** [comment]
could i delete the plots in my hard-disk once they have been synced online? maybe this is the way to save a lot of investment for the hard-disk purchase as we could ploting in the same hard-disk over and over again, maybe is more environmentally friendly too.

**Comment by handsomedude** [comment]
I've created 8 k32plots so far and saying 5months.
Can't create plots fast enough and I'm parallel plotting on a top end ryzen machine.

Created 3 plot last run and time went down one month.

So guess is you gonna need a lot of HDD.

Be nice if someone did actually say on average what you need currently for a daily reward.

Otherwise people will keep plotting and never getting anywhere.

There should be a limit on a single machine how many plot can be used.

Not fair in the new people trying to catch up plotting.

**Comment by dorkmo** [comment]
New plots are being created faster and faster right now. It will eventually slow down, but the estimates are calculated on the "current" size of all plots, not what theyll be in the future unfortunately.

**Comment by hoffmang9** [comment]
The reward process is exactly fair and directly proportional to the space you have plotted versus the total space plotted. If your time preference is high, and it sounds like it is, you will be able to plot new plots to a pool soon. That will smooth out your rewards at the cost of a pool fee.
