### ISSUE TITLE
stuck on connecting to wallet 

### ISSUE THREAD

**Issue by Maran6** [Chia-Network/chia-blockchain#2396]
When tryaing to delete plot that started to plot, after confirming delete, opens window with text "Connecting to wallet" and stays forewer. I can only close program but then I loose al  my uncomplete plots. It happend twice.

**To Reproduce**

1. Go to Plots
2. Click on Delete plots
3. SConfirm deletion
4. Connecting to Wallet
5. And it stays so forewer

**Expected behavior**
To delete plot and continue to plot other plots

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- OS 10
- CPU: AMD FX-6350

**Additional context**

**Comment by Allesios** [comment]
Same here.. did u solved it?

**Comment by kyleyip** [comment]
Same...

**Comment by kyleyip** [comment]
DO NOT wanna lose my p files

**Comment by kaymick8** [comment]
same........

**Comment by capitanIIsalamiYT** [comment]
Same

**Comment by dragonfly-net** [comment]
Same

**Comment by PSiKoTiC** [comment]
Same. Running v1.1.1 closed Chia blockchain. shut down. installed another video card. Rebooted. Tried reinstalling chia, checked for new version. spinning progress bar never connected to wallet upon chia execution win 10

**Comment by hoffmang9** [comment]
You need to forward port 8444 on your router https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
