### ISSUE TITLE
The 1.1.1 version cache file exceeds 239G and reaches 316G

### ISSUE THREAD

**Issue by houzk** [Chia-Network/chia-blockchain#2397]
I chose a farmland size of 101.4G, and the loaded cache file exceeds 316G and is still downloading. Isn't it 239G?

**Comment by salamanders** [comment]
(Disclaimer: not an expert)

* By downloading, it sounds like you mean the blockchain history, which yes, gets really big.  Unbounded big.
* If you meant the temp file space for "plotting" a single K32 plot (101.4G), if you are doing one at a time, yes, the temp file size should stay under 300G.  Do you have the latest version?  (It doesn't "download" 300G, it makes them from scratch using maths)

**Comment by SametBasturkk** [comment]
Same for me. 6 plot filled 2 tb m2ssd

**Comment by stonehenge360** [comment]
1.0.3 was creating over 300gb temp files for the K-32 plot.  This was reduced to mid 200gb temp files in 1.0.5.   Just to confirm: Are you saying that 1.1.1 is back to the old larger temp file requirements?

**Comment by hoffmang9** [comment]
Check for things like not actually emptied trash cans and other things actually taking space. The k32 temp needed numbers are accurate.
