### ISSUE TITLE
Chia does not connect

### ISSUE THREAD

**Issue by Eros65** [Chia-Network/chia-blockchain#2404]
I installed chia blockchain program this morning and after few hours I had to do a boot in the computer. When I tried to reconnect it stopped in "connecting". In the developers area, console,  I found the follow message: 
Already connected, not reconnecting.
main.js:1 0
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Usu%C3%A1rio/AppData/Local/chia-blockchain/app-1.1.1/resources/app.asar/build/renderer/js/441.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Usu%C3%A1rio/AppData/Local/chia-blockchain/app-1.1.1/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 

Could you please give me some orientation what I can do to reconnect?
Tks, Eros65

**Comment by Eros65** [comment]
Describe the bug
When clicking reload or force reload it doesn't actually reload it just does an infinite loop of "connecting to wallet"
To Reproduce
Steps to reproduce the behavior:

Go to view
Click on reload or force reload
See error
Expected behavior
A clear and concise description of what you expected to happen.
I mean I expected it to reload or refresh the GUI

Desktop (please complete the following information):

OS: Windows 10
I'm using 1.1.1

**Comment by egorgolo** [comment]
I have the same issue but I have different hardware. MacOS Mojave 10.14.6 (18G103). I tried all version from 1.0.0 to 1.1.1 and still the same "Connecting to wallet" screen.

**Comment by antenape** [comment]
> I have the same issue but I have different hardware. MacOS Mojave 10.14.6 (18G103). I tried all version from 1.0.0 to 1.1.1 and still the same "Connecting to wallet" screen.

Still having same issue. Can't connect on Windows 10 64bits

**Comment by capitanIIsalamiYT** [comment]
same issue

**Comment by warrior97** [comment]
Same issue

**Comment by shiaju** [comment]
Same here

**Comment by hoffmang9** [comment]
You need to forward port 8444 on your router https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
