### ISSUE TITLE
Ubuntu GUI stock at loading wallet

### ISSUE THREAD

**Issue by Tongie969** [Chia-Network/chia-blockchain#2405]
Hi there!

I am trying to set up chia-blockchain on Ubuntu. GUI is loading, but stocks at loading wallet. I did not create one for now. Browser did not open a window for setting one up.

Here is the console output, with error.

(venv) $ npm run electron &
(venv) $

chia-blockchain@ electron /Chia/chia-blockchain/chia-blockchain-gui
electron .

/Chia/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
startUrl file:///Chia/chia-blockchain/chia-blockchain-gui/build/renderer/index.html
/Chia/chia-blockchain/app.asar.unpacked/daemon
false
/Chia/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../chia/daemon/server.py
child process success
(node:51957) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron. See electron/electron#23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
File "../chia/daemon/server.py", line 962, in
main()
File "../chia/daemon/server.py", line 958, in main
return run_daemon(DEFAULT_ROOT_PATH)
File "../chia/daemon/server.py", line 952, in run_daemon
return asyncio.get_event_loop().run_until_complete(async_run_daemon(root_path))
File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "../chia/daemon/server.py", line 944, in async_run_daemon
await ws_server.start()
File "../chia/daemon/server.py", line 138, in start
self.websocket_server = await serve(
File "/Chia/chia-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in await_impl
server = await self._create_server()
File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address
closing code: 1

Thanks in Advance!

Tongie
![image](https://user-images.githubusercontent.com/63996344/115763858-2c1d9680-a3a5-11eb-8b42-9b434f6416dd.png)

**Comment by hoffmang9** [comment]
This is the issue - `OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address`

This can be about three thrings.
1. Try replacing localhost with 127.0.0.1 in `~/.chia/mainnet/config/config.yaml`
2. Enable IPv6 - even if you don't use it
3. Disable any firewall or other process making it impossible to connect to port 55400

**Comment by Tongie969** [comment]
> This is the issue - `OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address`
> 
> This can be about three thrings.
> 
> 1. Try replacing localhost with 127.0.0.1 in `~/.chia/mainnet/config/config.yaml`
> 2. Enable IPv6 - even if you don't use it
> 3. Disable any firewall or other process making it impossible to connect to port 55400

Hello Sir, thanks for your fast reply. There is no active firewall and Ipv6 is enabled. But in the chia folder is no main net folder. 


How can I fix this? 

Thanks a lot!

**Comment by Tongie969** [comment]
> This is the issue - `OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address`
> 
> This can be about three thrings.
> 
> 1. Try replacing localhost with 127.0.0.1 in `~/.chia/mainnet/config/config.yaml`
> 2. Enable IPv6 - even if you don't use it
> 3. Disable any firewall or other process making it impossible to connect to port 55400

Thanks for your fast response Sir! 

I check if IPv6 is enabled true
No firewall is enabled

But checking config.yaml confused me. See attached pleas. Is this looking fine? 

And is it important to know that I use static IP?


Great, thanks! 
![image](https://user-images.githubusercontent.com/63996344/115773148-414bf280-a3b0-11eb-84aa-a73f1719366c.png)

**Comment by Tongie969** [comment]
> This is the issue - `OSError: [Errno 99] error while attempting to bind on address ('::1', 55400, 0, 0): cannot assign requested address`
> 
> This can be about three thrings.
> 
> 1. Try replacing localhost with 127.0.0.1 in `~/.chia/mainnet/config/config.yaml`
> 2. Enable IPv6 - even if you don't use it
> 3. Disable any firewall or other process making it impossible to connect to port 55400

All points checked, still not loading GUI. It would help me a lot.

**Comment by elarkasi** [comment]
disable IPV6 if you don't use it and then delete the ipv6 mapping table in /etc/hosts, should be good to go.

**Comment by Tongie969** [comment]
> disable ipv6 if you don't use it and then delete the ipv6 mapping table in /etc/hosts, should be good to go.

Thanks mate, I will check out later!
