### ISSUE TITLE
[BUG] install script won't ever reach ubuntu 21.04

### ISSUE THREAD

**Issue by eyao** [Chia-Network/chia-blockchain#2412]
**Describe the bug**
```
        elif [ "$UBUNTU" = "true" ] && [ "$UBUNTU_PRE_2004" = "0" ]; then
		echo "Installing on Ubuntu/Debian 20.04 LTS or newer"
		sudo apt-get update
		sudo apt-get install -y python3.8-venv python3-distutils
	elif [ "$UBUNTU" = "true" ] && [ "$UBUNTU_2100" = "1" ]; then
		echo "Installing on Ubuntu/Debian 21.04 or newer"
		sudo apt-get update
		sudo apt-get install -y python3.9-venv python3-distutils
```

If it's 21.04, it won't pass 20.04 and attempt to use 3.8 which will fail.

**To Reproduce**
run install.sh on 21.04

**Expected behavior**
install without errors

**Desktop (please complete the following information):**

- OS: Ubuntu Server 21.04
- CPU: 10900

**Comment by hoffmang9** [comment]
Oops - this should fix it. Expect it next release - https://github.com/Chia-Network/chia-blockchain/pull/2418

**Comment by xxxcrow** [comment]
Same here 👋
