### ISSUE TITLE
[BUG] Lack of developer engagement with valid and important bugs

### ISSUE THREAD

**Issue by garyhkirk** [Chia-Network/chia-blockchain#2421]
**Describe the bug**
A clear lack of focus on reported bugs, what is going on?

**To Reproduce**

1. Report a bug with a full description
2. Wait for any response or allocation of dev to investigate/fix the issue
3. Keep on waiting
4. Give up and be forced to complain in a channel (GitHub) that's not suitable for it

**Expected behavior**
I expected devs to respond to urgent issues, more fool me...
I would also expect, given the time spent on building the system and imminent listing on exchanges, that devs would be keen to irradicate issues

**Screenshots**
Insert picture of anyone having an issue that's beyond annoying

**Desktop (please complete the following information):**
Desktop has shattered components of keyboard due to complete lack of interaction/support

**Additional context**
I think devs should get it by now... The whole project risks failing if critical errors are ignored

**Comment by hoffmang9** [comment]
Complaint noted.

**Comment by garyhkirk** [comment]
Apologies for the tongue-in-cheek (and possibly overly sarcastic) message. I am new to Chia and think it has great potential, hence I wanted to shine a light on an issue that could deter new miners from entering the network. I'm aware (to some degree, as I haven't taken on such a big project) that devs will be very busy (and many bug reports are not detailed enough to look into) but there are critical issues that seemingly (publicly at least) are not getting attention. I wish all of the devs well and thank Gene for noting the complaint.
