### ISSUE TITLE
[BUG] Not synced after loosing internet connection for 2minutes

### ISSUE THREAD

**Issue by radvansky-tomas** [Chia-Network/chia-blockchain#2424]
I've rebooted my router, after that is my app in Non Synced state.
I cannot restart it, as I am in the middle of plotting process.
Which is really annoying as now I am not farming...

**Comment by dorkmo** [comment]
probably more profitable to be farming than plotting right now. Id restart and fix connection. Best of luck!

**Comment by radvansky-tomas** [comment]
No this app is really buggy, you have just no idea what it is doing, and why...you cannot restart things, you are basically stuck with restarts and hope

**Comment by radvansky-tomas** [comment]
Now its again, "Not Synced" . No explanation what so ever....then maybe it will start syncing in 30mins time...maybe...whilst I cannot restart my farm...or I am stopping my plots everytime something like this happen (which is always)

**Comment by dorkmo** [comment]
how many nodes are you showing a connection to?
