### ISSUE TITLE
[BUG] Chia setup 1.1.1 installation failed windows

### ISSUE THREAD

**Issue by robertwt7** [Chia-Network/chia-blockchain#2425]
![image](https://user-images.githubusercontent.com/15647967/115793695-e9dd6f00-a40f-11eb-83bd-879d5bae78b4.png)

The setup log doesn't really make any sense though...

**Comment by yzn5555** [comment]
Please turn off the computer and turn it on again. This problem will not occur after installation.

**Comment by rawbar** [comment]
Try reinstalling again,.  I had this happen to me as well, but on the 2nd attempt it worked fine.  Make sure all your chia processes are killed as well in task manager.

**Comment by robertwt7** [comment]
Yeah this works after I restarted my computer. It's fine now..
