### ISSUE TITLE
[BUG] Missing timelord_launcher in deb

### ISSUE THREAD

**Issue by shwuhk** [Chia-Network/chia-blockchain#2426]
I installed chia by the deb released in Github.The log reported missing timelord_launcher when I `chia start all`

**Comment by hoffmang9** [comment]
Chia start all is intended for developers running simulations. You should almost always use `chia start farmer`

**Comment by shtse8** [comment]
So do we need timelord service to run for harvesting or farming?

**Comment by hoffmang9** [comment]
No.
