### ISSUE TITLE
[BUG]Connected but not Synced in mac OS

### ISSUE THREAD

**Issue by 9517zy** [Chia-Network/chia-blockchain#2429]
![image](https://user-images.githubusercontent.com/70366378/115798448-9e2fc300-a419-11eb-9b6e-6b4fd011e993.png)

Since I updated the 1.1.1 version, my wallet status has been shown as Not Synced. I went to find out if it might be a system time problem, but I am pretty sure that my system time is synchronized with the local time.

- OS: [macOS]
- OS Version/Flavor: [macOS Big Sur 11.2.3]
- CPU: [Intel Core i7]

**Comment by hoffmang9** [comment]
That suspiciously looks like a system time problem as you seem to be close to the correct block height for the time of your report.

**Comment by 9517zy** [comment]
> That suspiciously looks like a system time problem as you seem to be close to the correct block height for the time of your report.

I am not sure whether the displayed block time is before or after the update. How should I fix this problem? Because I am sure that my system time is synchronized with the local time.

**Comment by Bugerman58** [comment]
and I have the same after update chia to v1.1.1

![Screenshot 2021-04-23 at 10 47 19](https://user-images.githubusercontent.com/15684023/115815521-4a28dc80-a421-11eb-81b4-a8707376a400.png)

os: Big Sur 11.2.3
time: UTC+7

**Comment by Bugerman58** [comment]
gui client its connected  but speed is very low

**Comment by RichJac** [comment]
I just upgraded to 1.1.1 on MacOS Mojave and I'm getting the same Not Synced.  Has anyone found a fix?

**Comment by Bugerman58** [comment]
I just left it on and after a while the client connected

**Comment by RichJac** [comment]
Actually I was just coming back to comment here.  I guess I was too quick.  It just synced.  It took 20-30 minutes but it looks like I'm good again.

Thanks!
