### ISSUE TITLE
"Finished signage point" lines in the debug.log starts counting at 1/64 and end at 63/64

### ISSUE THREAD

**Issue by Eldaw** [Chia-Network/chia-blockchain#2430]
If you grep the debug.log for "Finished signage point" you will notice that the sequence starts at 1/64 and ends at 63/64 before the cycle starts again.

Surely it should either start at 0/63 and go up to 63/63, or it should start at 1/64 and end at 64/64.

At the moment, the way it's written to the log (1/64 to 63/64), it appears that the final step in the sequence (64/64) is always missing.

**Comment by ben-willmore** [comment]
I'm no expert but I think the 64th step is `Finished sub slot, SP 64/64`, where SP stands for "signage point". If you grep the logs for `Finished s`, you should see it.

**Comment by Eldaw** [comment]
Thanks @ben-willmore you are correct. I'll leave this issue open, though, as I think it would be a good idea for consistency in the logs to make it write something in the same format for the 64th step. Maybe something like:
`Finished signage point 64/64. Sub slot complete.`
