### ISSUE TITLE
How can I delete tasks in the queue?

### ISSUE THREAD

**Issue by sansky33** [Chia-Network/chia-blockchain#2434]
I run the wrong Queue task, but I can't delete it after updating 1.1.1. How can I delete the task in the queue?

**Comment by rawbar** [comment]
it seems like it was broken in 1.1.0.  I can no longer delete jobs from the queue either.

**Comment by handsomedude** [comment]
Close app and open it againm. Ques gone.then.
Pain you can't delete something that simply qued up!

**Comment by sansky33** [comment]
We have temporarily disabled the "Delete Plots" button in the Windows GUI as we are still working on debugging upstream issues that are causing it.
Close app and open it againm. Ques gone
