### ISSUE TITLE
[BUG] V1.1.0 (win 10) unable to finish a k32 plot due to temp files filling every byte of a 500gig drive.

### ISSUE THREAD

**Issue by Bigfoots44** [Chia-Network/chia-blockchain#2437]
**Describe the bug**
I upgraded to v1.1.0 (windows) last night an was had some plots queued to start. I came back in the morning with one machine stalled at 19% and another stalled at 32% with an error message on both about unable to copy to my tmp folder. I checked the drive and it was completely full.

**To Reproduce**
Attempt to make a new plot in v1.1.0 on windows, wait for drive to fill

**Expected behavior**
Plot to complete as earlier versions have

**Screenshots**
Will add once I reproduce the failure, I already emptied the drives.

**Desktop (please complete the following information):**

- OS: [win 10]
- OS Version/Flavor: [professional]
- CPU: [Intel 8650u and Ryzen 7 3800x]

**Additional context**

**Comment by Bigfoots44** [comment]
Cannot Recreate. Please skip this one.

**Comment by Bigfoots44** [comment]
![image](https://user-images.githubusercontent.com/26718965/115946973-8be57180-a479-11eb-9503-05873f9cf82d.png)

**Comment by garyhkirk** [comment]
If you had failed plots before they would have still been in the temp folder, failures don't get to do tidying up. If you check the temp folder, clear it and check there's nothing in the recycle bin then try a new plot it should be OK if all else is well. However, I'm experiencing problems that might indicate an issue with the filesystem on Windows (particularly if you plot to the windows system drive). I'll report back here if I learn anything more

**Comment by Bigfoots44** [comment]
I am plotting on 2 computers, one on the file system drive and one on a separate drive. I ensure that there is enough free space when I start and the will fill all the way up if I am running v1.1.0. Downgrading to 1.0.5 seems to have remedied the issue (1.0.0 and 1.1.0 were causing the issue). I will upgrade to 1.1.2 and test once the current batch of plots is done.
