### ISSUE TITLE
The plotting task is always automatically aborted, and there is no error logs.

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#2440]
Why do my drawing tasks always stop automatically? 
The number of attempts is always the same. When I stop to Computing table N, I don’t see any error logs when I check the log, which is very unfriendly.

**Comment by sansamh** [comment]
From last night to now, the processing has been stopped in the middle of the process  ALWAYS. There is no error log. WTF!!!

**Comment by oswaldzc** [comment]
Since i updated to V1.1.1,this problem often occurs

**Comment by pubyun** [comment]
same issue

**Comment by errcodex** [comment]
It's the same with me

**Comment by hoffmang9** [comment]
If you use the cli you need to save your own plotting logs. The GUI saves plotting logs in `~\.chia\mainnet\plotter\`

**Comment by liya558** [comment]
I did not use GUI.

**Comment by errcodex** [comment]
When I use cli to plot, I often don't have any crash or error, but it's stuck there and doesn't continue. I'm sure it's not caused by the "Quick Edit" blocking of the command window.
