### ISSUE TITLE
[BUG] chia 1.1.1 taking too much CPU

### ISSUE THREAD

**Issue by schak83** [Chia-Network/chia-blockchain#2441]
chia 1.1.1 taking too much CPU

and its taking allot of time to sync existing plots when evern I start using new chia version

![image](https://user-images.githubusercontent.com/73795557/115814875-8590c000-a3bb-11eb-925b-91edc99d33a1.png)

**Comment by hoffmang9** [comment]
Phase 1 is one of the most CPU intensive phases and syncing is also CPU intensive.
