### ISSUE TITLE
Temp folder 649 files while plotting K-32

### ISSUE THREAD

**Issue by Lockenfrosch** [Chia-Network/chia-blockchain#2444]
Hello, when i start a plot with K-32 temp space 239GiB and a the rest standart 128 buckets ect, after some hours my folder is full of temp files. now iam at 649 files and 229GB foldersize but if i look at my hard drive it says 465 GB. and there`s nothing more stored on this hard drive. the plot stop at 34% i tryed this multiple times. when i start a new plot, i deleted the temp folder. what am i doing wrong?

**Comment by jonny77** [comment]
you can not delete them. they will be deleted after the plot file generated

**Comment by Lockenfrosch** [comment]
I had to delete it cuz it stopped at 35% my hard drive is 500 and 465 is used with the plot instead of 239

**Comment by cidevant** [comment]
have same problem... I had 239gb ssd, created small partition of 10GB on my system ssd, added as second SSD  for tmp plot. When 239 is full, its stops... 10Gb partition is not filled at all.

**Comment by Lockenfrosch** [comment]
> have same problem... I had 239gb ssd, created small partition of 10GB on my system ssd, added as second SSD for tmp plot. When 239 is full, its stops... 10Gb partition is not filled at all.

Yeah u need full 330gb temp for plotting, when finished u need 110gb, ur ssd is to small with 239gb
