### ISSUE TITLE
node not synced

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#2447]
Hi
my node is not syncing. Yesterday I left it at 67000 and this morning it was at 75000. On the other hand I did not get more than 4 or 5 nodes in connection. This morning I tried various things like recharging but it got stuck. He also warned that although the GUI closed, many processes remain running with chia and many others such as wallet.
Restart PC and I'm still the same
It does not sync.
Can you help me?
Thanks

**Comment by Lockenfrosch** [comment]
Maybe open port 8444 could help

**Comment by realbluefish** [comment]
I had open.
Now i connect with 2 full nodes and i sync 74439/171758 and too slow.
Whai cam do to get sync speed and have a lot of node connections??
I try connect manually with friendas node wroting your ip and port but dont
works.
Tnx
Eduardo

**Comment by dorkmo** [comment]
you might double check your local network ip address hasnt changed, and that its still forwarded to that ip
