### ISSUE TITLE
Must Timelords be started? If not, will XCH be affected?

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#2448]

**Comment by toadzhou** [comment]
I'm open. I'm not sure if I don't open it will affect the income. But Timelords takes up a lot of performance. I hope the official can give me a correct answer.

**Comment by hoffmang9** [comment]
Almost no one needs to run a timelord. https://github.com/Chia-Network/chia-blockchain/wiki/Timelords
