### ISSUE TITLE
How to delete failed records in Version 1.1.1

### ISSUE THREAD

**Issue by 75204-hzq** [Chia-Network/chia-blockchain#2449]
![image](https://user-images.githubusercontent.com/76607573/115827054-5a02e980-a43e-11eb-8330-d92068da4be2.png)
![image](https://user-images.githubusercontent.com/76607573/115827090-625b2480-a43e-11eb-945f-49da295d286c.png)

**Comment by gdias1992** [comment]
Just close and reopen the chia application.

**Comment by 75204-hzq** [comment]
> 只需关闭并重新打开chia应用程序即可。
> 
> 至少那是我所做的...
> 
> 您也可以在Chia应用程序关闭的情况下删除您的临时文件夹。
谢谢，我知道这样可以，但是在绘图中不方便关闭，而且关闭后再次同步要很很久
