### ISSUE TITLE
GUI Full Node Mac OS not Syncing

### ISSUE THREAD

**Issue by iEddie-cmd** [Chia-Network/chia-blockchain#2454]
GUI Full Node Mac OS not Syncing. I has synced about 70% yesterday. After restart today no more sync.

**Comment by spencerhite** [comment]
I'm having the same problem. I've gone ahead and reinstalled chia and still says 'not synced' and doesn't move.

**Comment by Bugerman58** [comment]
at the same issue #2429

**Comment by bruelleerre** [comment]
Same here. With 1.0.5 everything works well

**Comment by Bugerman58** [comment]
> Same here. With 1.0.5 everything works well

try leaving the gui(1.1.1) open and wait 20-30 minutes

**Comment by bruelleerre** [comment]
thanks, it worked, then again no connection and now again sync. thank you <3

**Comment by bruelleerre** [comment]
Ok, seems to work stable. thank you again

**Comment by iEddie-cmd** [comment]
Not for me. How did you fixed it?
