### ISSUE TITLE
[FEATURE] Trezor support

### ISSUE THREAD

**Issue by petrkr** [Chia-Network/chia-blockchain#2458]
Do you plan to support hardware wallet Trezor? Will be nice to have private keys at one place with other crypto.

can not remove bug label.

**Comment by petrkr** [comment]
Ledger is not Trezor. If you closed this issue, it means it is already implemented ? That was quick.

**Comment by hoffmang9** [comment]
We'd love your PR for Trezor. Do you have any idea if they've implemented IETF BLS - especially in G2?

**Comment by petrkr** [comment]
Yes if day will have 50 hours and I do not need to sleep then I can make PR for every project myself and for free. Do not know if they implemented that. I have to look for specification and see if it is even possible do to it there. Trezor team mostly not focus to not mainstream coins by themself, but they are also open for PR's..

So from your answer I feel "No we do not plan to support it, but you can do it yourself".

**Comment by hoffmang9** [comment]
Some projects have to struggle to be supported by the ecosystem and some do not.

**Comment by petrkr** [comment]
Good is your implementation is in Python and most of Trezor's firmware is also in micropython. So probably there could be used some part of open source code / libraries. You have really huge documentation so will be nice to point to some part of needed stuff to understand whole ecosystem. Like what keys must be where. Becaues Trezor (even ledger) are offline wallets, there must not be requirement of access to private keys by anything else than wallet.

As I wrote before, have to read specification, but do not know where to start.

**Comment by hoffmang9** [comment]
Are you aware that IETF BLS is a totally new signature scheme and elliptical curve unlike the signature schemes and curves that Trevor and Ledger have historically supported?

**Comment by dorkmo** [comment]
probably be better to make a pull request on the trezor github for chia support. it is hard to gain adoption of new tech!

**Comment by petrkr** [comment]
Trezor team works like if any altcoin wants to be there, they are that one who make support and push PR. Because they can not handle all altcoins at world. Of course if Chia will become worldwide like ethereum or litecoin, they will do it themself. But it is impossible to implement every fork or coin on world for such team.

**Comment by dorkmo** [comment]
true true, its difficult to be an altcoin! i was hoping for Bisq to support chia, but they arnt accepting any new coins :(
