### ISSUE TITLE
Check if farming correct - chia.log missing?

### ISSUE THREAD

**Issue by sysadt** [Chia-Network/chia-blockchain#2461]
Hi,

According to [Chia.net Space Farmer](https://www.chia.net/2020/02/25/so-you-want-to-be-a-space-farmer.en.html) you can check if your plots are farming correctly by checking the chia.log file and see if all the plots show up time to time.

I am running 1.0.5 and cannot find chia.log file.
Can you please advise where to find it, and if the file does not exist anymore, how to check if you are farming correctly?
Plots have been checked via `chia plots check`

**Comment by qqqcai** [comment]
my be ~ it is  
C:\Users\<yourusername>\.chia\mainnet\log\debug.log
