### ISSUE TITLE
What is the cause of this error and how can I solve this problem

### ISSUE THREAD

**Issue by AsherHuu** [Chia-Network/chia-blockchain#2462]
![image](https://user-images.githubusercontent.com/32830348/115847773-db19ab00-a455-11eb-8a6d-f6b5ff80a209.png)

root@chia:~# cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

**Comment by tajchert** [comment]
Please copy and paste text instead of the image so other looking for that issue will find you ticket

**Comment by AsherHuu** [comment]
root@chia:~/chia-blockchain# . ./activate 
(venv) root@chia:~/chia-blockchain# sh install-gui.sh

Running git submodule update.


> electron-winstaller@5.0.0 install /root/chia-blockchain/chia-blockchain-gui/node_modules/electron-winstaller
> node ./script/select-7z-arch.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/chia-blockchain/chia-blockchain-gui/node_modules/electron-winstaller/script/select-7z-arch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of react-refresh@>=0.8.3 <0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN @use-it/event-listener@0.1.6 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-scroll-to-bottom@4.1.1-master.2780945 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-simple-code-editor@0.10.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN use-dark-mode@2.3.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-winstaller@5.0.0 install: `node ./script/select-7z-arch.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-winstaller@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T11_12_57_586Z-debug.log
(venv) root@chia:~/chia-blockchain#

**Comment by AsherHuu** [comment]
How can i fix it
