### ISSUE TITLE
Is it possible to provide an option to change blockchain data directory?

### ISSUE THREAD

**Issue by CreeperKong** [Chia-Network/chia-blockchain#2464]
![image](https://user-images.githubusercontent.com/28486081/115848399-64c97880-a456-11eb-971b-fdc323e666fe.png)
I don't want blockchain data be forced to store into `~/.chia` with the GUI app, although this can be solved with a symbolic link.
Hope to improve that😊

**Comment by halokid** [comment]
great question :-)

**Comment by Minecon724** [comment]
you can use a symlink

**Comment by CreeperKong** [comment]
> you can create a symlink

Windows requires administrator privilege to create symlink, but I uses my own user on other's PC without that.

**Comment by hoffmang9** [comment]
Symlinks work and are supported. You can also set the environment variable CHIA_ROOT.
