### ISSUE TITLE
[BUG]Catastrophic bug，Plot Count get  More with out Plotting。

### ISSUE THREAD

**Issue by kai-chia-fff** [Chia-Network/chia-blockchain#2470]
**Describe the bug**
i am a Chinese，My English is so poor，sorry。
My friend accidentally triggered this bug
when you Plotting 100%，but  the Plot was not finalized，change file name *.tmp to *.plot
then Start again application program，
Plots Passed Filter  Auto increase，about 50 Count every single day。
This is a serious bug. Fix it
I have photos. You can leave them to me by email if you need。

**Comment by kai-chia-fff** [comment]
My friend won some XCH in this way, which is unfair

**Comment by maomingyang1314** [comment]
In other words, your friend does not need to draw the plot completely, just modify the suffix of the zero-time file to get HCX?

**Comment by maomingyang1314** [comment]
This is too unfair to us, it is a fraud

**Comment by maomingyang1314** [comment]
I tested it. In the initial stage of file creation, I directly modified the suffix of the zero-hour file. After restarting the software, the program was not recognized as farming. It should be that when it reaches 100%, the program is packaged into one and the suffix is modified. That should work

**Comment by kai-chia-fff** [comment]
他没有每次都操作，他操作了一次之后，初筛的那个地方数量每天都在增长，自动涨的，比如今天通过初筛那里显示1/90，第二天就变成1/150，但是他只挖了十块地

**Comment by maomingyang1314** [comment]
能够更加详尽的说一下么，我没有明白您的意思，画图到100时候，程序将所有文件打包，成一个文件，我曾经也遇到过100的时候程序卡住，然后关闭程序，有一个101G的tmp文件，您说修改后缀就能获得耕地么？还是说，其他办法，去欺骗了程序。理论上开发的时候都会考虑这个的。

**Comment by Teledyol** [comment]
> **Describe the bug**
> i am a Chinese，My English is so poor，sorry。

**Comment by Teledyol** [comment]
What's wrong with the Chinese language? Nothing to apologize for…

There are more articulate "English" speakers in China than there are people in the USA. If you can teach me basic Chinese, I'll pay you two XCH. Now, that's something to value.

RAW

**Comment by maomingyang1314** [comment]
Unlike English, Chinese has no obvious grammar. Chinese is more concerned with meaning. A meaning can be expressed in many ways. People in different regions have differences in grammar, so you can try to communicate with the Chinese.

**Comment by maomingyang1314** [comment]
I want to know how many terabytes you have used. I am now 3TB and it will take a month to get out of coins

**Comment by kai-chia-fff** [comment]
只需要操作一次，再文件卡到100%的时候，实际上文件已经完成，但是没有更改文件名后缀，这时把文件名后缀改了，操作一次之后，就不用操作，电脑程序会自动增加地块
You only need to operate once. When the file card reaches 100%, the file has actually been completed, but the file name suffix has not been changed. At this time, the file name suffix has been changed. After one operation, there is no need to operate. The computer program will automatically add lots

                         Plots Passed Filter                       
day1                            0/50
day2                           2/100
day3                           3/150

Plots Passed Filter add without Plotting！！！！！！！！！！！！

**Comment by kai-chia-fff** [comment]
If the authorities let go of such a serious bug, I can only expose it through the platform, which will cause a disastrous blow to the credibility of Chia. I don't want this to happen, I want to be fair

**Comment by hoffmang9** [comment]
如果绘图过程在最后被挂起，你通常可以把二级临时文件的名称从.tmp改为.plot。这样做的时间与绘制其他文件的时间相同。没有什么特别的快捷方式。

**Comment by Teagan-pace** [comment]
According to the issue of kai-chia-fff, the conditions for this bug to occur:
1. Change the temp file of the final destination to .plot when the  temp file migrate to the final destination (plotting progress is 100%),
2. Restart Chia main program

Result: The Chia program will auto increase the number of farmland in the "Plots Passed Filter" for some reasons, or even double it every day, which will be a way of cheating to increase the chance of winning.

As in the following example, assume that Total Network Space does not increase but keeps farming for 3 days:

1st day:
Plot Count: 70
Total Size of Plots: 8Tib
Estimated Time to Win: 16 days
Plots Passed Filter: 0/70

2nd day:
Plot Count: 70
Total Size of Plots: 8Tib
Estimated Time to Win: 8 days
Plots Passed Filter: 0/140

3rd day:
Plot Count: 70
Total Size of Plots: 8Tib
Estimated Time to Win: 5 days
Plots Passed Filter: 0/210

@kai-chia-fff  Is the above example correct?


So need your clarification @hoffmang9  ,
1. Is this a security breach in the program, which caused the wrong file to pass the Proof of Space?
2. Is it just a bug displayed by the GUI client, which does not actually increase the chance of winning?

**Comment by Teagan-pace** [comment]
@hoffmang9 
Because I tried a similar operation, the Chia system can auto increase the "Plots Passed Filter", although there is no proof whether this can increases the chance of winning

**Comment by hoffmang9** [comment]
If you duplicate the same file, the GUI will show you have more space but you are lying to yourself. Only unique plots compete in the competition. If you have a good proof of space and you have 3 k32s that have that proof of space, then only one plot can win that block. Use `chia plots check` to find duplicates and delete them.

**Comment by maomingyang1314** [comment]
This problem should be resolved quickly. If HCX can be obtained in this way, it will be a disaster for chia.

**Comment by maomingyang1314** [comment]
I want to know whether the names of the extra disks are repeated. If they are repeated, they should not be rewarded. If the names of the files generated out of thin air are not the same, they may be deceived and rewarded.

**Comment by hoffmang9** [comment]
If a plot is repeated it will not win more rewards. 4 of the exact same proofs of space win exactly once.

**Comment by KaiZhang1206** [comment]
> **Describe the bug**
> i am a Chinese，My English is so poor，sorry。
> My friend accidentally triggered this bug
> when you Plotting 100%，but the Plot was not finalized，change file name *.tmp to *.plot
> then Start again application program，
> Plots Passed Filter Auto increase，about 50 Count every single day。
> This is a serious bug. Fix it
> I have photos. You can leave them to me by email if you need。

Hi, can send me the images, thanks. E-mail addr:  zucker0012@163.com

**Comment by QinJunHong** [comment]
嗨，可以给我发图片，谢谢。电子邮件地址：284482121@qq.comqq.com

**Comment by QinJunHong** [comment]
Hi, can send me the images, thanks. E-mail addr：284482121@qq.com
