### ISSUE TITLE
SN550 500GB very slow during ploting.

### ISSUE THREAD

**Issue by QuantumLiu** [Chia-Network/chia-blockchain#2471]
My pc:
i5-10400 6c12t, 32gb RAM, SN550 500GB for cache.
Chia version 1.1.1

Test with `crystalmark` got read 2gb/s+ and write 1.5gb/s+

But during the ploting , the hard disk activity time is always between 10%-20%, write speed is between 0-200 mb/s
Ploting option is 1 mission, k32, memory 4gb, threads 2.
![c4157a4882d53e919df30f195cefde9](https://user-images.githubusercontent.com/21980268/115867680-f85a7380-a46d-11eb-8ca1-6967a196d5d5.png)

**Comment by maomingyang1314** [comment]
I am the SN550 1T version. I drew three pictures at a time, and I felt that the SSD performance was saturated. I feel that three are enough. The 500G version has shrunk, not great.

**Comment by maomingyang1314** [comment]
I guess that the number of threads you set is not enough, I draw a picture, generally set 4-6 threads. The CPU is not fully performing.

**Comment by garyhkirk** [comment]
The SN550, like many consumer drives, is fast for short bursts of activity so you can get fast reads and writes if the file is a few gigabytes. If you write a very large file you will normally see the speed drop to 350-500MB per second. With many writes happening one after another (low queue depth) you get another hit, especially if it is a drive that has the operating system on it (Windows in this case). Windows will be competing for drive resources.

The relatively low and uneven speed graph is normal for your setup. Even consumer-grade pcie4 nvme drives (e.g. Corsair MP600) without windows installed on them slow down dramatically compared to burst speeds. The recommended temp drives are commercial grade SSDs, some use faster NAND and all of them have longer lifespans than consumer drives. The warranty for a 500GB SN550 is a total of 300TB written in its lifetime - it might still work after that but the manufacturer knows the drive will degrade with more writes and won't replace drives that go over the write limit no matter how old they are. 

I hope that helps

**Comment by dorkmo** [comment]
its possible you might be overheating and hitting a throttle too.

**Comment by QuantumLiu** [comment]
> The SN550, like many consumer drives, is fast for short bursts of activity so you can get fast reads and writes if the file is a few gigabytes. If you write a very large file you will normally see the speed drop to 350-500MB per second. With many writes happening one after another (low queue depth) you get another hit, especially if it is a drive that has the operating system on it (Windows in this case). Windows will be competing for drive resources.
> 
> The relatively low and uneven speed graph is normal for your setup. Even consumer-grade pcie4 nvme drives (e.g. Corsair MP600) without windows installed on them slow down dramatically compared to burst speeds. The recommended temp drives are commercial grade SSDs, some use faster NAND and all of them have longer lifespans than consumer drives. The warranty for a 500GB SN550 is a total of 300TB written in its lifetime - it might still work after that but the manufacturer knows the drive will degrade with more writes and won't replace drives that go over the write limit no matter how old they are.
> 
> I hope that helps

Got it, thank you so much.
