### ISSUE TITLE
[BUG]help me

### ISSUE THREAD

**Issue by ndcc5** [Chia-Network/chia-blockchain#2475]
Install chia-blockchain_1.1.1_amd64.deb and run report this ：
![1619183083(1)](https://user-images.githubusercontent.com/6286019/115875393-bdf5d400-a477-11eb-9fad-4ba8fe9c393e.png)

**Comment by dorkmo** [comment]
you might try to install from terminal using git pull. https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian

**Comment by hoffmang9** [comment]
Which Linux version and which platform type?

**Comment by ndcc5** [comment]
> Which Linux version and which platform type?

ubuntu-20.04.2.0-desktop-amd64.
