### ISSUE TITLE
[BUG] error 1. retrying in five minutes

### ISSUE THREAD

**Issue by EcoVitek** [Chia-Network/chia-blockchain#2477]
When two plots are running in parallel, plots stuck on 61%, 91%, 57%, 48% with "error 1. retrying in five minutes" and dont go futher  

**To Reproduce**
Choose Plot Size: k=32
Choose Number of Plots:2
Plot in Parallel
standart params
Select Temporary Directory: SSD 1TB
Select Final Directory: HDD 2 TB

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS 20H2
![WhatsApp Image 2021-04-23 at 14 55 48](https://user-images.githubusercontent.com/58548862/115875875-59724f00-a44e-11eb-9d78-a838abc06b63.jpeg)

- CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz   3.00 GHz

**Additional context**

**Comment by vladymyrkulinich** [comment]
Same problem for me when parallel plotting. It stuck on 91%

**Comment by ragnarokna** [comment]
Use SSD not HDD as temp let me  solved this problem.

**Comment by dorkmo** [comment]
how much ram do you have? might be running out?

**Comment by hoffmang9** [comment]
Those retries only occur when it can't write to the disk. That can be because you are out of space or because you don't have permissions.

**Comment by thienhieu123** [comment]
@EcoVitek Did you find a way to fix this problem? I have the same issue. Please help me
