### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by karimdr2** [Chia-Network/chia-blockchain#2478]
The chia application unexpectedly close when plotting.

**Comment by maomingyang1314** [comment]
Which version, on which platform

**Comment by karimdr2** [comment]
V 1.1.1 on Windows10 Entreprise LTSC

**Comment by hoffmang9** [comment]
What is the output of the plotting logs? They are in `~\.chia\mainnet\plotter\`

**Comment by jzmexec** [comment]
@hoffmang9 ,In V 1.0.5 on Windows10 .
plotter log like this:
`
Computing table 5
...	
Bucket 44 uniform sort. Ram: 4.533GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
Bucket 45 uniform sort. Ram: 4.533GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
Bucket 46 uniform sort. Ram: 4.533GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
Bucket 47 uniform sort. Ram: 4.533GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
Bucket 48 uniform sort. Ram: 4.533GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.`

this log last modify time is 2021/4/24 2:26:53
Can you give me any informations for this issue? And is it in other OS such as Fedora、Ubuntu..?

**Comment by karimdr2** [comment]
Plotting works correctly in the background even if the application has crashed. the annoying thing is that I no longer have any visibility on the progress of the plotting and the farming stops.
