### ISSUE TITLE
I use hpool tool create plot file.when I want to solo do I have to recreate the plot file?

### ISSUE THREAD

**Issue by wscgogogo** [Chia-Network/chia-blockchain#2479]
hi:
  I joined hpool to mining and I followed this https://hpool.com/help/tutorial/Chia%E6%8C%96%E7%9F%BF%E6%95%99%E7%A8%8B
used thiers tool crate plot file. I don't know if I want to solo mining files created by hpool's tool will affect me?
should I recreate this file? Create plot file is so hard I don't want to create them again.

**Comment by dorkmo** [comment]
unfortunately you would need to replot if you want to change the key that gets the award. if you are still growing your plots you could continue to farm the hpool plots on a different computer.

**Comment by wscgogogo** [comment]
Ok, but can I use the plot file with my solo key to join hpool mining?

**Comment by dorkmo** [comment]
im not sure how the hpool software works, sorry. typically if you plot to a solo key it will only work with that key. the Chia team will release a new pool protocol soon and the pool setup might change.

**Comment by wscgogogo** [comment]
Many thanks! by the way,how can I distinguish the plot file use my solo key

**Comment by dorkmo** [comment]
you might try doing `chia plots check -h` to get the checker help to find the right command. You might be able to find someone on keybase that has done it before. good luck!
https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#check

**Comment by wscgogogo** [comment]
ok,thank you very much
