### ISSUE TITLE
[BUG]All plots showing as "Not found plot" after upgrading to 1.1.1

### ISSUE THREAD

**Issue by noisymime** [Chia-Network/chia-blockchain#2480]
**Describe the bug**
After upgrading from 1.0.5 to 1.1.1, all plots now show as "Not found plot". I have verified that the correct key is being used, the files are accessible, have run a plot check etc but all are OK. 

Within the log I see:
```
Plot /chia2/plot-k32-2021-04-17-21-40-7775b93ecb074d9abaeead0bb31506670b3b278df6d4afb89de5c8589e7fe14c.plot has a farmer public key that is not in the farmer's pk list.
```

When I run `chia keys show` I see:
```
Farmer public key (m/12381/8444/0/0):: b0e9b66ed8d9b33ce8cff0453b6dc925f5ffa500d749da6d199380874ece99abbb75a322f9ba09a0e7c3cf4ec23aa7a2
```

When I run `chia plots check`, the entry for this same plot shows:
```
Testing plot /chia2/plot-k32-2021-04-17-21-40-7775b93ecb074d9abaeead0bb31506670b3b278df6d4afb89de5c8589e7fe14c.plot k=32
Pool public key: 97e34e1004d7c291b12490c47c8ea3c106a6c4ff4d757c37fe118d3e0152c04c3f16c02843830a95d3fb5c580a29992d
Farmer public key: b0e9b66ed8d9b33ce8cff0453b6dc925f5ffa500d749da6d199380874ece99abbb75a322f9ba09a0e7c3cf4ec23aa7a2
```

Farmer public keys match across both both the check and the key, yet still the error is received in the log file indicating that the pk does not match.  

I can still load these same plots on a Windows machine using the same key and they display correctly, the issue is only occurring on this instance. 

- OS: Ubuntu 18.04

**Additional context**
Install method was from here https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian (ie not using the .deb file)

**Comment by noisymime** [comment]
For anyone else coming across this, shutting down the daemon and removing the `~/.chia` folder fixed this. Still appears to be an issue with why this happens in the first place given all the public keys match, but that may help. 

(Note you'll have to resync from scratch when you remove that directory)

**Comment by toadzhou** [comment]
Check your synchronization status, if it has not been synchronized, please check the network, or chia show -a IP: 8444 try another routine
```
chia farm summary 
chia netspace
```
Check if CHIA_ROOT has changed before and after the upgrade

**Comment by jcx123123** [comment]
This problem recurs over and over again, and many miners have encountered it. Deleting the DB file temporarily solves this problem, but it takes a day to resychronize. What's more, I just deleted the DB file and resynchronized it the day before yesterday, and it happened again today.

**Comment by max918** [comment]
**make sure you have backup your mnemonic (24 words) **

chia keys delete_all
chia keys add
(Enter the mnemonic)
chia farm summary

Plot count column should be updated.

**Comment by noisymime** [comment]
> chia keys delete_all
> chia keys add
> (Enter the mnemonic)
> chia farm summary

I forgot to mention, but i did go through deleting the key in the GUI and re-adding it, but this also made no difference. Does the CLI equivalent that you mentioned do something  different to what the GUI is doing?

**Comment by noisymime** [comment]
> Check your synchronization status

Yes, I was fully synced when I was experiencing this issue.
