### ISSUE TITLE
full_node chia.full_node.full_node: ERROR

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#2488]
systemOS:CentOS Linux release 7.9.2009 (Core)
CPU:Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
memory:128G

full_node chia.full_node.full_node has a lot of error logs, and The drawing task always stops automatically.

The error log is as follows
21:10:16.505 full_node full_node_server        : WARNING  Banning 116.207.17.221 for 600 seconds
21:10:16.506 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/full_node/full_node.py", line 604, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 116.207.17.221

21:21:58.361 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/full_node/full_node.py", line 604, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 74.135.4.11

22:30:30.135 full_node full_node_server        : WARNING  Cannot write to closing transport 93.74.42.123
22:37:36.780 full_node full_node_server        : WARNING  Cannot write to closing transport 207.189.245.240

**Comment by zrjaa1** [comment]
+1 seeing similar logs in Ubuntu 20.04 TLS with chia version `1.1.1`. Full node syncing forever.

**Comment by zrjaa1** [comment]
> +1 seeing similar logs in Ubuntu 20.04 TLS with chia version `1.1.1`. Full node syncing forever.

Followed the instruction here worked for me: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-this-upnp-error. Basically, you want to enable uPnP for only 1 node and disable it for other nodes. Also make sure you opened port 8444 for that node.
