### ISSUE TITLE
Latest Update is causing multiple errors [BUG]

### ISSUE THREAD

**Issue by jrescobarp** [Chia-Network/chia-blockchain#2489]
**Describe the bug**
I ran the update commands on my terminal like I have many times before, but this time I have received multiple errors and am unable to finish the update or re-open the GUI to continue farming. This is very disappointing as I have a large amount of plots and don't want to miss out on any potential wins.  

**To Reproduce**
Almost every command of the update script gives me an error:
git checkout latest gives me this:
  `.github/workflows/build-linux-arm64-installer.yml: needs merge
.github/workflows/build-linux-installer.yml: needs merge
.github/workflows/upload-pypi-source.yml: needs merge
CHANGELOG.md: needs merge
build_scripts/build_linux.sh: needs merge
chia/cmds/chia.py: needs merge
chia/cmds/farm.py: needs merge
chia/cmds/farm_funcs.py: needs merge
chia/cmds/init.py: needs merge
chia/cmds/init_funcs.py: needs merge
chia/cmds/keys.py: needs merge
chia/cmds/keys_funcs.py: needs merge
chia/cmds/netspace.py: needs merge
chia/cmds/netspace_funcs.py: needs merge
chia/cmds/plots.py: needs merge
chia/cmds/start.py: needs merge
chia/cmds/start_funcs.py: needs merge
chia/cmds/stop.py: needs merge
chia/cmds/wallet.py: needs merge
chia/cmds/wallet_funcs.py: needs merge
chia/consensus/block_body_validation.py: needs merge
chia/consensus/block_creation.py: needs merge
chia/consensus/blockchain.py: needs merge
chia/consensus/blockchain_check_conditions.py: needs merge
chia/consensus/condition_costs.py: needs merge
chia/consensus/cost_calculator.py: needs merge
chia/consensus/multiprocess_validation.py: needs merge
chia/daemon/server.py: needs merge
chia/full_node/block_store.py: needs merge
chia/full_node/bundle_tools.py: needs merge
chia/full_node/full_node.py: needs merge
chia/full_node/full_node_api.py: needs merge
chia/full_node/full_node_store.py: needs merge
chia/full_node/mempool.py: needs merge
chia/full_node/mempool_check_conditions.py: needs merge
chia/full_node/mempool_manager.py: needs merge
chia/introducer/introducer.py: needs merge
chia/plotting/plot_tools.py: needs merge
chia/rpc/wallet_rpc_api.py: needs merge
chia/rpc/wallet_rpc_client.py: needs merge
chia/server/introducer_peers.py: needs merge
chia/server/node_discovery.py: needs merge
chia/server/start_service.py: needs merge
chia/server/ws_connection.py: needs merge
chia/timelord/timelord.py: needs merge
chia/types/announcement.py: needs merge
chia/types/blockchain_format/program.py: needs merge
chia/types/coin_solution.py: needs merge
chia/types/condition_opcodes.py: needs merge
chia/types/condition_var_pair.py: needs merge
chia/types/condition_with_args.py: needs merge
chia/types/full_block.py: needs merge
chia/types/mempool_item.py: needs merge
chia/types/name_puzzle_condition.py: needs merge
chia/types/spend_bundle.py: needs merge
chia/util/block_tools.py: needs merge
chia/util/chain_utils.py: needs merge
chia/util/condition_tools.py: needs merge
chia/util/initial-config.yaml: needs merge
chia/util/wallet_tools.py: needs merge
chia/wallet/cc_wallet/cc_utils.py: needs merge
chia/wallet/cc_wallet/cc_wallet.py: needs merge
chia/wallet/cc_wallet/debug_spend_bundle.py: needs merge
chia/wallet/puzzles/cc.clvm.hex.sha256tree: needs merge
chia/wallet/puzzles/chialisp_deserialisation.clvm.hex: needs merge
chia/wallet/puzzles/chialisp_deserialisation.clvm.hex.sha256tree: needs merge
chia/wallet/puzzles/condition_codes.clvm: needs merge
chia/wallet/puzzles/generator_for_single_coin.clvm: needs merge
chia/wallet/puzzles/generator_for_single_coin.clvm..hex.sha256tree: needs merge
chia/wallet/puzzles/generator_for_single_coin.clvm.hex: needs merge
chia/wallet/puzzles/generator_for_single_coin.clvm.hex.sha256tree: needs merge
chia/wallet/puzzles/lowlevel_generator.py: needs merge
chia/wallet/puzzles/p2_delegated_conditions.clvm.hex.sha256tree: needs merge
chia/wallet/puzzles/prefarm/spend_prefarm.py: needs merge
chia/wallet/puzzles/puzzle_utils.py: needs merge
chia/wallet/puzzles/rl.clvm.hex.sha256tree: needs merge
chia/wallet/puzzles/rl_aggregation.clvm.hex: needs merge
chia/wallet/puzzles/rl_aggregation.clvm.hex.sha256tree: needs merge
chia/wallet/sign_coin_solutions.py: needs merge
chia/wallet/util/trade_utils.py: needs merge
chia/wallet/wallet.py: needs merge
chia/wallet/wallet_block_store.py: needs merge
chia/wallet/wallet_blockchain.py: needs merge
chia/wallet/wallet_node.py: needs merge
chia/wallet/wallet_puzzle_store.py: needs merge
chia/wallet/wallet_state_manager.py: needs merge
chia/wallet/wallet_transaction_store.py: needs merge
setup.py: needs merge
src/cmds/farm.py: needs merge
src/cmds/init.py: needs merge
src/cmds/keys.py: needs merge
src/cmds/netspace.py: needs merge
src/cmds/start.py: needs merge
src/cmds/wallet.py: needs merge
src/types/condition_var_pair.py: needs merge
tests/blockchain/test_blockchain.py: needs merge
tests/blockchain/test_blockchain_transactions.py: needs merge
tests/clvm/coin_store.py: needs merge
tests/clvm/test_chialisp_deserialization.py: needs merge
tests/clvm/test_clvm_compilation.py: needs merge
tests/clvm/test_serialized_program.py: needs merge
tests/core/full_node/test_coin_store.py: needs merge
tests/core/full_node/test_full_node.py: needs merge
tests/core/full_node/test_mempool.py: needs merge
tests/core/full_node/test_mempool_performance.py: needs merge
tests/core/full_node/test_node_load.py: needs merge
tests/core/make_block_generator.py: needs merge
tests/core/test_cost_calculation.py: needs merge
tests/core/util/test_streamable.py: needs merge
tests/simulation/test_simulation.py: needs merge
tests/util/benchmark_cost.py: needs merge
tests/wallet/rpc/test_wallet_rpc.py: needs merge
tests/weight_proof/test_weight_proof.py: needs merge
error: you need to resolve your current index first`

git pull gives me an error based on the previous error:
 `error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.`

Neither of the above errors occurred the first time I ran them, but they have popped up every time I have tried since then.When they did not pop up the first time I received this error on the sh install.sh command:

`:~/chia-blockchain$ sh install.sh
apt-get is /usr/bin/apt-get
Installing on Ubuntu/Debian 20.04 LTS or newer
[sudo] password for rodri: 
Ign:1 http://dl.google.com/linux/chrome-remote-desktop/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease   
Hit:3 http://dl.google.com/linux/chrome-remote-desktop/deb stable Release
Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]      
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]                 
Get:7 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [600 B]
Fetched 324 kB in 1s (449 kB/s)       
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-distutils is already the newest version (3.8.5-1~20.04.1).
python3.8-venv is already the newest version (3.8.5-1~20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Python version is 3.8
Requirement already satisfied: pip in ./venv/lib/python3.8/site-packages (21.0.1)
Requirement already satisfied: wheel in ./venv/lib/python3.8/site-packages (0.36.2)
Looking in indexes: https://pypi.org/simple, https://pypi.chia.net/simple/
Requirement already satisfied: miniupnpc==2.1 in ./venv/lib/python3.8/site-packages (2.1)
Looking in indexes: https://pypi.org/simple, https://pypi.chia.net/simple/
Obtaining file:///home/rodri/chia-blockchain
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/rodri/chia-blockchain/venv/bin/python3.8 /home/rodri/chia-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpzosgo0f_
       cwd: /home/rodri/chia-blockchain
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/home/rodri/chia-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/rodri/chia-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/rodri/chia-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-y5l3wbfg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-y5l3wbfg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-y5l3wbfg/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 4
      <<<<<<< HEAD
      ^
  SyntaxError: invalid syntax
  ----------------------------------------
WARNING: Discarding file:///home/rodri/chia-blockchain. Command errored out with exit status 1: /home/rodri/chia-blockchain/venv/bin/python3.8 /home/rodri/chia-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpzosgo0f_ Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/rodri/chia-blockchain/venv/bin/python3.8 /home/rodri/chia-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpzosgo0f_ Check the logs for full command output.`

When I received this error the first time I attempted to just open the GUI to continue farming and it never connected to my wallet.

**Expected behavior**
I expected a working update.

**Screenshots**
I could include screenshots of the errors upon request, but the raw text from the errors is included above.

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor:#56~20.04.1-Ubuntu SMP 
- CPU: AMD Ryzen 7 2700X Eight-Core Processor

**Additional context**
I have been on the Chia network for a couple of months and have updated many times within that time frame, I have never had this issue so I don't believe it is an issue of me running the command in the wrong order or incorrectly. Whatever is happening came from the latest git fetch and has postponed y farming.

**Comment by hoffmang9** [comment]
Try
```
git fetch
git checkout latest
git reset --hard FETCH_HEAD
```

**Comment by jrescobarp** [comment]
Just ran those commands.
Git fetch did not return anything
git checkout returned the same error as before
git reset returned this:
`HEAD is now at ad29ac6f Changelog for 1.1.1 (#2341)`

Do I just continue with the update script from here? (git pull->sh install.sh->etc.)

**Comment by jrescobarp** [comment]
No need to answer my previous comment, I ran the rest of the commands and it worked!
Thank you very much!
