### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ggrichard** [Chia-Network/chia-blockchain#2494]
**Describe the bug**
I plotted 8 files today and chia application stucked, so I closed it and reboot my computer. When I open chia again, my plot files all missing. I don't know what happened(T＿T)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: win10
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by bstock84** [comment]
Did you re-add the plot output directory to the farm? Have you checked the plot output directory to see if the physical .plot files are there?

**Comment by lipalong** [comment]
Were the plot files finished plotting when you restarted your computer?
