### ISSUE TITLE
If there is no polt file on the local hard disk, the interface will not show "Last Attempted Proof"

### ISSUE THREAD

**Issue by xzknet** [Chia-Network/chia-blockchain#2498]
If there is no polt file on the local hard disk, the interface will not show "Last Attempted Proof"

**Comment by dorkmo** [comment]
you cant attempt a proof if you do not have any plots

**Comment by salsaly4** [comment]
But if it's a farmer node only with remote harvesters? Seems that I've got exactly this situation.

**Comment by ddowhy** [comment]
I think this is the same as https://github.com/Chia-Network/chia-blockchain/issues/2522 .   

> you cant attempt a proof if you do not have any plots

what he means is that all the plots are on remote harvesters, and no plots locally on the machine thats running the full node.  in theory this should work fine, as this is following the 'farming on multiple machines' instructions provided by the devs.  And this is my exact situation too.  I've got 1700+ plots and zero blocks found for 6 days now.  I think the code for finding blocks on remote harvesters is bugged.
