### ISSUE TITLE
Full Node Won't Stay Synced

### ISSUE THREAD

**Issue by CryptoKnightMining** [Chia-Network/chia-blockchain#2499]
My Full Node won't stay synced. If I reboot my system and restart the chia GUI everything will sync back up but then about 1-2 hours later it will then become "Not Synced". I have been struggling with this for 2 days now. prior to that everything was running uninterrupted. The suggested ports are confirmed open (8444, 8447, 8449) on both the computers plotting and the router. Any help with this frustration would be greatly appreciated.

**Comment by dorkmo** [comment]
are you plotting computers also running full nodes? you should try to only have one full node on your network.

**Comment by CryptoKnightMining** [comment]
Thanks! I think this was a huge help! To turn my plotting computers into plotters only do I just remove the full node connection at the bottom of the full node page? (Using Windows 10 Pro). Thanks for any suggestions.

**Comment by dorkmo** [comment]
i'd just try ctrl alt delete and end the full_node.exe haha might have to do `chia stop node`
