### ISSUE TITLE
[Optimization]

### ISSUE THREAD

**Issue by PMVX** [Chia-Network/chia-blockchain#2500]
When plotting is finished at 100% it can take several minutes 30mins to almost an hour to move the tmp file to it's final destination. When plotting to the same drive, can we instead have a move + rename command instead of copy command so that it's instantaneous and save 30mins-1hr vs copying + renaming?

Use case:
Multiple separate plots to different drives.
24 plots x 3 separate queues:
1st queue has temp and final directory X
2nd queue has temp and final target to Y
3rd queue has temp and final target Z

With the move method, this can easily save time.
Right now a work around to save time would be to close the app when it reaches 100%, move the file to final destination on same drive instantly then rename it. The problem with this is that you have to check regularly to see when it's finished so you can manually move them. Isn't it more efficient for the plotter do a move instead of copy if the temp and final directory is the same drive? This would be a good option for those that do not have dedicated plotting machines with fast SSDs and just using ext USB drives.

**Comment by dimitrus** [comment]
1 tmp folder: plot.p*.t*.sort_bucket_*.tmp
2 tmp folder: plot.sort.tmp
3 tmp folder: plot.table*.tmp
4 tmp folder: plot.2.tmp
