### ISSUE TITLE
[BUG] After update 1.1.1 - full node status unsynchronized 14 hours

### ISSUE THREAD

**Issue by korolkraski** [Chia-Network/chia-blockchain#2501]
Hello.

I had version 1.05 After update 1.1.1 - full node status unsynchronized 14 hours.
What should I do?

- OS: Win10
- CPU: [Intel 6800k]

**Comment by dorkmo** [comment]
double check that your port 8444 is forwarded to your node computer's ip address

**Comment by lexzz** [comment]
I'm seeing the same issue on Ubuntu. After updating tot 1.1.1 the client will not sync

**Comment by IT2core** [comment]
Same issue here.
![image](https://user-images.githubusercontent.com/6873720/115926912-e5eb3480-a483-11eb-82c9-e0ea7afcd19a.png)

**Comment by dorkmo** [comment]
how many nodes are you connected to?

**Comment by Jared-woodruff** [comment]
I had the same issue, had to delete the database/copy it over from another healthy node/farmer.

**Comment by dompie** [comment]
> I had the same issue, had to delete the database/copy it over from another healthy node/farmer.

I just started with chia, how am I supposed to solve this problem? I'm waiting for 2 days now to get synced, but there is almost no progress.

![not-syncing](https://user-images.githubusercontent.com/706491/115932747-d670e900-a48d-11eb-9aba-d67aa22ea06d.jpg)
![connections](https://user-images.githubusercontent.com/706491/115932755-da047000-a48d-11eb-81ea-b1da4ec25fb2.jpg)

**Comment by dorkmo** [comment]
@dompie you should have more peers, double check your network router for port forwarding to your computer

**Comment by dompie** [comment]
> @dompie you should have more peers, double check your network router for port forwarding to your computer

I disabled windows firewall and exposed the host for about 10 minutes to the internet, deleteing and readding already present peers. With no noticeable effect.

![open-ports](https://user-images.githubusercontent.com/706491/115938024-a0d1fd00-a499-11eb-9c88-671a81fc0e90.jpg)

**Comment by jcx123123** [comment]
I had the same issue

**Comment by dompie** [comment]
Oh, somehow the firewall changes worked over night. I'm almost in Sync now. Although the numbers (MiB Up/Down) did not really change much and I still have only 5 connections to remote peers.

**Comment by korolkraski** [comment]
> дважды проверьте, что ваш порт 8444 перенаправлен на IP-адрес вашего узла

Спасибо за совет, я не представляю, как и где это сделать ))

**Comment by thentd** [comment]
使用105版本的时候，根本不会要求什么8444端口打开，现在111、112的时候 不打开  节点都链接不起来。

**Comment by hoffmang9** [comment]
> 使用105版本的时候，根本不会要求什么8444端口打开，现在111、112的时候 不打开 节点都链接不起来。

首先，1.0.5版将在一个小时左右停止工作。第二，与1.1.2版相比，它的网络性能实际上较差。第三，网络的增长是如此强烈，以至于任何人在他们的路由器上打开8444端口，他们所有的连接都会立即被填满，然后可以保持同步。
