### ISSUE TITLE
unable to delete in progress plotting sets

### ISSUE THREAD

**Issue by coolpro313** [Chia-Network/chia-blockchain#2503]
i kept getting a offset error with the ending text retry in 5 minutes on a plotting set so when i go to delete to try it again the delete option is greyed out and being unable to click on the delete option

**Comment by ddegirmenci** [comment]
> We have temporarily disabled the "Delete Plots" button in the Windows GUI as we are still working on debugging upstream issues that are causing it.

https://github.com/Chia-Network/chia-blockchain/releases/tag/1.1.0

**Comment by coolpro313** [comment]
oh ok what about this error that i get from time to time is that in the works for a fix or a way for me to fix it?

Only wrote 0 of 678672 bytes at offset 15256126140 to "E:\\plot-k32-2021-04-23-10-17-ea5a0163f60a5aabec464b80ee993f8935c6426af49471b5f241b42e54b28fdc.plot.table5.tmp"with length 15256129536. Error 1. Retrying in five minutes.

**Comment by coolpro313** [comment]
@ddegirmenci

**Comment by ddegirmenci** [comment]
I don't know, sorry. I saw the issue title and remembered the release note is all.

**Comment by coolpro313** [comment]
oh ok no worries thx for the help i'll just use version 1.1.0 until the delete option is back enabled
