### ISSUE TITLE
[BUG] [v1.1.1] [GUI] [Windows] | Invalid plots stay in the GUI even after been deleted.

### ISSUE THREAD

**Issue by Jared-woodruff** [Chia-Network/chia-blockchain#2505]
In the main plot GUI screen, Invalid plots persist even though they have been removed from the target disk. 
A reload of the client is required to resolve this misreporting.

**System:**
**CPU:** AMD Ryzen 5800x
**RAM:** 32 GB 3200MHz
**DISK:** 4TB VOLUME (x2 Gen4 M.2 in RAID0)
**OS:** Win10 Pro 20H2 (19042.928)

**Comment by maomingyang1314** [comment]
The deletion task of win10 is disabled, as mentioned in the update report of version 1.1.0

**Comment by sargonas** [comment]
This function was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21
