### ISSUE TITLE
Full node synce, bu the "last Attemted Proof" stop its feed in the gui, is this an issue?

### ISSUE THREAD

**Issue by mtxprime** [Chia-Network/chia-blockchain#2510]
see the gap between 6:04 and 6:11

![image](https://user-images.githubusercontent.com/52265994/115938725-2f765800-a461-11eb-8ed7-ec48e1ce9f25.png)

**Comment by dorkmo** [comment]
looks like you added a lot of plots, you might restary just to get everything fresh

**Comment by mtxprime** [comment]
so it should update every minute or so?

**Comment by dorkmo** [comment]
should be 10 seconds, but i think youve got something going wrong

**Comment by mtxprime** [comment]
found to must latency to plots, unix is more reliant that the windows gui, changing the logging to info the looking in debug log for error solved the issue
