### ISSUE TITLE
why is there no way to resume plots

### ISSUE THREAD

**Issue by Hemenguelbindi** [Chia-Network/chia-blockchain#2511]
When you close the application, plots are not saved, you have to start over from scratch.
screan before closing
![image](https://user-images.githubusercontent.com/20486626/115939268-0e405680-a4b7-11eb-83da-a12dc513c554.png)
screan after closing
![image](https://user-images.githubusercontent.com/20486626/115939387-72631a80-a4b7-11eb-85e5-d0657fd3b836.png)
The plots remain on the system, but there is no way to resume the process from the break.
![image](https://user-images.githubusercontent.com/20486626/115939792-b86cae00-a4b8-11eb-8372-ecbf80b31a72.png)

- OS Windows 10 
- CPU: Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz   2.00 GHz 
- RAM 8 Gb

**Additional context**

**Comment by hoffmang9** [comment]
Resuming plots is on the roadmap.
