### ISSUE TITLE
[BUG] [WINDOWS] [v1.1.1] Synchronization 

### ISSUE THREAD

**Issue by Gantris3** [Chia-Network/chia-blockchain#2515]
When I enter the program again, and try to synchronize my plot, chia does not recognize it and I get a message that says "13" and nothing happens. 

![chia](https://user-images.githubusercontent.com/83099154/115939321-c34d2180-a46b-11eb-9e5d-c51f634f8a04.JPG)
**Expected behavior**

**Comment by hoffmang9** [comment]
One of your directories listed in the plots section of config.yaml has a problem.

**Comment by Gantris3** [comment]
And how do I fix that?

**Comment by hoffmang9** [comment]
Use notepad to edit `~\.chia\mainnet\config\config.yaml`. If the problem is not obvious pasting the contents of the file into  http://www.yamllint.com/ can help.

**Comment by Gantris3** [comment]
Thanks for the help

**Comment by Gantris3** [comment]
Sorry for my ignorance but I don't know what I have to open with the editor, nor what to edit. 

> Use notepad to edit `~\.chia\mainnet\config\config.yaml`. If the problem is not obvious pasting the contents of the file into http://www.yamllint.com/ can help.

Sorry for my ignorance but I don't know what I have to open with the editor, nor what to edit.

**Comment by Gantris3** [comment]
I already got it, he says "Valid YAML!"
