### ISSUE TITLE
[BUG] Significantly slower plotting performance on 1.1.1 compared to 1.0.5

### ISSUE THREAD

**Issue by GefeiSHEN** [Chia-Network/chia-blockchain#2517]
- OS: Windows
- OS Version/Flavor: Windows 10 19042.928
- CPU: Intel i7-7700K
- RAM: 8G 2133MHz x2
- Temp SSD: Samsung 980 Pro 1TB
- Temp HDD: WD Velociraptor 500G x2 (raid 0)
- Plotting Setting: 4 plots concurrently (2 for each drive) All default settings except each uses 6 CPU threads.

In previous version 1.0.5, plotting takes 7-8 hours to finish, but the 1.1.1 takes significantly more time to finish plotting (6 hours still at 23%). The CPU is also not maximizing its load during phase 1 in the new version.

**Comment by bluedusk** [comment]
same here 4 plots in parallels, take 11hours for 50%. basically unusable

**Comment by Jared-woodruff** [comment]
I believe this is due to the compression that was added in version 1.1.1 but I could be wrong.
On my Ryzen system I've noticed an additional hour for all plots in this version.

**Comment by BasilHorowt** [comment]
@Jared-woodruff are you talking about this from the changelog?

> Farmers now compress blocks using code snippets from previous blocks. This saves storage space and allows larger smart coins to have a library of sorts on chain.

I have no idea about this change, or the internals of Chia, but that doesn't sound like something that should impact plotting...

**Comment by psun888** [comment]
Confirmed. Much slower than early versions, and also when plotting in parallel, some processes stopped in the middle, and never happened with early versions.

**Comment by hoffmang9** [comment]
Blockchain compression when a farmer wins a block has nothing to do with the plotter that has not changed since 1.04.

**Comment by hoffmang9** [comment]
Often this means your SSD is nearing the end of it's life. You may also need to enable TRIM.
