### ISSUE TITLE
[Optimization] Can you support a version that only runs in large memory without -t?

### ISSUE THREAD

**Issue by Evi5** [Chia-Network/chia-blockchain#2521]
If they are all in memory, it should be faster when plotting like this
I tried ramdisk（Read:6.1 GB/s, Write 3.2 GB/s）, it takes 6 hours to plot, which is about the same as nvme
---------------Samsung ddr4 3200. ramdisk create and speed test--------------
CREATE RAM DISK:
sudo mkdir -p /test/ramdisk
sudo vi /etc/fstab
	tmpfs /test/ramdisk tmpfs defaults,size=250G 0 0
reboot

WRITE TEST:
sudo dd if=/dev/zero of=/test/ramdisk/zero bs=4k count=50000
50000+0 records in
50000+0 records out
204800000 bytes (205 MB, 195 MiB) copied, 0.0634264 s, 3.2 GB/s

READ TEST:
sudo dd if=/test/ramdisk/zero of=/dev/null bs=4k count=50000
50000+0 records in
50000+0 records out
204800000 bytes (205 MB, 195 MiB) copied, 0.03376 s, 6.1 GB/s

---------------------------------------------------------------------------------

**Comment by hoffmang9** [comment]
All memory plotting is faster per plot but slower per day.

**Comment by Evi5** [comment]
> All memory plotting is faster per plot but slower per day.

slower per day? why? If the memory is the same size as the nvme space

**Comment by hoffmang9** [comment]
You can plot in parallel on NVMe and your total output per day per $ will be much higher
