### ISSUE TITLE
[BUG] Docker automatically creates a new key on every boot even passed key in

### ISSUE THREAD

**Issue by isilcala** [Chia-Network/chia-blockchain#2523]
used
-v ~/.local/share/python_keyring/:/root/.local/share/python_keyring/
to pass my keyring in but docker still creates a new key on every start and throws me a warning:
WARNING: using a pool address which we don't have the private keys for. We searched the first 500 addresses. Consider overriding yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy with xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Tried docker version 1.0.5 to 1.1.1 it's the same.

how to prevent it from creating a new key on every boot? what does this warning mean? does it mean I'm farming into another wallet? and how to 'override' the address?

Thanks.

**Comment by KickCellarDoor** [comment]
By default the "keys" environment in the Dockerfile is set to "generate" which means it will generate a new key, you need to change it to the actual path of your key.

**Comment by 007** [comment]
Still a bug - no reason that a mapped folder should regenerate a new key every run.

**Comment by 007** [comment]
Still a bug - no reason that a mapped folder should regenerate a new key every run.

**Comment by 007** [comment]
Still a bug - no reason that a mapped folder should regenerate a new key every run.

**Comment by emlowe** [comment]
you need to override "keys" as was mentioned earlier in a comment. For example `-v /path/to/key/file:/path/in/container -e keys="/path/in/container"`

Closing issue

**Comment by 007** [comment]
It's still a bug that you need to do this. Why would I expect to override the env if I already mapped the path?
