### ISSUE TITLE
[BUG] can't delete polt in china 1.1.1

### ISSUE THREAD

**Issue by flytingke** [Chia-Network/chia-blockchain#2525]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md

`We have temporarily disabled the "Delete Plots" button in the Windows GUI as we are still working on debugging upstream issues that are causing it.`
