### ISSUE TITLE
[BUG]First start chia.harvester.harvester: WARNING

### ISSUE THREAD

**Issue by AckerPaul** [Chia-Network/chia-blockchain#2526]
**Describe the bug**
The first startup log shows, is this normal?
2021-04-24T09:17:27.685 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.

Does it affect my creation of P tasks ？

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/discussionsTech support on Keybase or

**Comment by AckerPaul** [comment]
Link won't open

**Comment by hoffmang9** [comment]
Don't know why that got messed up. 

https://github.com/Chia-Network/chia-blockchain/discussions

or Keybase #support
