### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zzgls** [Chia-Network/chia-blockchain#2530]
![image](https://user-images.githubusercontent.com/32196288/115943549-17dfb380-a4e3-11eb-8837-a32cb390a2fa.png)

Why before the synchronization good state will become not synchronized, do I have to keep the computer synchronization? Previous versions didn't

**Comment by hoffmang9** [comment]
This is usually caused by your computer's clock being inaccurate.

**Comment by maomingyang1314** [comment]
I am also curious. My computer is syncing normally, and then I took a look at it at noon today. Check it out at night, shouldn't it be a big problem?

**Comment by manageryzy** [comment]
> This is usually caused by your computer's clock being inaccurate.

I think aws connection is not stable in some isp in chia
