### ISSUE TITLE
[BUG] [v1.1.1] [GUI] [Windows] | Valid Plots marked as invalid, become Valid on Chia client restart.

### ISSUE THREAD

**Issue by Jared-woodruff** [Chia-Network/chia-blockchain#2532]
To reproduce the issue perform the following:

1. Have a valid Plot on [Hard-Disk-01] (which is NOT being monitored by a Chia client)
2. Copy the valid Plot to another disk [Hard-Disk-02] (which is being monitored by a Chia client)
3. During the copy operation the chia client will report the plot is invalid (because its still copying).
4. Once the copy is complete, refresh the chia client (it will still show the copied plot as invalid).
5. Close down Chia and reopen (the formerly invalid plot is now valid and advertised.)

**Comment by flyhigao** [comment]
same. use rsync solve

**Comment by maomingyang1314** [comment]
It should be when copying, this file exists in both directories at the same time. (The copy destination address will first create a file with the same name, and then transfer the data), so there will be an invalid block. After copying, the program should not be updated, but it does not affect it.

**Comment by sunyao920807** [comment]
you could reset the path of plot
