### ISSUE TITLE
RPC Error

### ISSUE THREAD

**Issue by cnwendaosi** [Chia-Network/chia-blockchain#2536]
![image](https://user-images.githubusercontent.com/83105189/115945982-e7067b00-a4f0-11eb-8e78-8983b2729f53.png)

What's wrong with me?

**Comment by CarryWZ** [comment]
hi guy,
     I'm very pity that I don't know how to solve your problem.Now I'm very confuse some problem as following image. Do you have the following problem？ or  Do you know how to solve this problem？
![image](https://user-images.githubusercontent.com/16461050/115959525-3bd0e280-a53f-11eb-8524-222d9cf690e6.png)

**Comment by Godfather95** [comment]
Same Problem here:

curl -X POST https://localhost:8555/get_blockchain_state --cert ~/.chia/mainnet/config/ssl/full_node/private_full_node.crt --key ~/.chia/mainnet/config/ssl/full_node/private_full_node.key -H "Content-Type: application/json" --insecure

500 Internal Server Error

Server got itself in trouble

**Comment by qqqcai** [comment]
same problem~~
curl version is 7.76.1-win64

**Comment by TaylorWenOne** [comment]
> Same Problem here:
> 
> curl -X POST https://localhost:8555/get_blockchain_state --cert ~/.chia/mainnet/config/ssl/full_node/private_full_node.crt --key ~/.chia/mainnet/config/ssl/full_node/private_full_node.key -H "Content-Type: application/json" --insecure
> 
> 500 Internal Server Error
> 
> Server got itself in trouble

hi,mate,did you fix the problem?
