### ISSUE TITLE
How to add a private key through mnemonics in Linux

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#2541]
How to add a private key through mnemonics in Linux.
The mnemonic is a set of hexadecimal characters, and when adding, you need to use the F parameter to specify the text file. How is the format of the text file defined?

**Comment by lvcivs** [comment]
I haven't looked into this but probably just a text file with space separated words?

**Comment by hoffmang9** [comment]
@lvcivs is correct.
