### ISSUE TITLE
How to make a backup of the wallet?

### ISSUE THREAD

**Issue by elmans1961** [Chia-Network/chia-blockchain#2545]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by elmans1961** [comment]
How to make a backup of the wallet particuarly in Windows?No such a function in the menu of the wallet neither the wallet makes a backup file automatically as it is in other crypto wallets.

**Comment by royimous** [comment]
This is not the place for questions. This is a question, not a bug. Please respect how things are organized here and do some work to find the proper channels to ask questions.
