### ISSUE TITLE
Tasks need to wait a long time 31% of the time. Can the progress bar be more linear? Convenient for us to arrange time

### ISSUE THREAD

**Issue by maomingyang1314** [Chia-Network/chia-blockchain#2549]
In the past few days, I used 3700X with 32GB RAM, 8 cores and 16 threads. For drawing, I want to know how many threads are best allocated to each drawing when I draw 8 drawings at the same time. And how long it takes you to draw a picture.

**Comment by hoffmang9** [comment]
GitHub Issues are not for technical support. Try Keybase or https://github.com/Chia-Network/chia-blockchain/discussions
