### ISSUE TITLE
Sync long time

### ISSUE THREAD

**Issue by joshepvn** [Chia-Network/chia-blockchain#2553]
Hi, I waiting for sync 2 days but not completed, any problem?

**Comment by joshepvn** [comment]
Syncing 115694/173958

**Comment by maomingyang1314** [comment]
Computer configuration, and whether you are drawing. If the drawing work is too heavy, the cpu may not have extra performance to synchronize, right?

**Comment by Bob3666** [comment]
I got the same Problem as @joshepvn  Syncing for two days and only 57941/177381
please help.

@maomingyang1314  I do not understand your comment.

Is there a way to improve the syncronisation speed?

**Comment by maomingyang1314** [comment]
Are you adding pictures drawn by other computers to the new computer? That may cause a long synchronization problem. If not, you can try to restart the program or restart your computer

**Comment by Bob3666** [comment]
where can i get the version 1.0.5 ?

**Comment by hoffmang9** [comment]
Version 1.0.5 will stop working in three days.

**Comment by maomingyang1314** [comment]
But the 1.1.1 version problem is quite serious.

**Comment by maomingyang1314** [comment]
I want to know when the next version will be updated

**Comment by Bob3666** [comment]
Is it possible to download theneeded PiB as a seperate File?
I could insert it into my Chia folder and theproblem would be solved.

**Comment by Bob3666** [comment]
I will try it today with version 1.0.5

**Comment by Bob3666** [comment]
Now it says not syncronised. I started to reload chia.

It is really slow and buggy. I do not no what to do. 
My hardware will come on monday but i doubt the blockchain will be syncronised

**Comment by maomingyang1314** [comment]
My accessories will also arrive tomorrow, but there is a problematic program that we cannot use.

**Comment by hoffmang9** [comment]
Open 8444 on your router and you'll be inundated with nodes https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by maomingyang1314** [comment]
The router needs to open port 8444. I will test the 1.1.1 version of the program on my MAC later. My router opens the port. Huffman does not want to close this question for now. I will test it. I will also test it under win10. @ @hoffmang9

**Comment by maomingyang1314** [comment]
I will test the 1.1.1 synchronization issue later, please do not close the issue. Thank you

**Comment by hardhub** [comment]
What is normal time for syncing?

**Comment by maomingyang1314** [comment]
It should be network time, right? I don't care about time, I'm normal

**Comment by maomingyang1314** [comment]
I tested it and updated the program from 1.0.5 to 1.1.1. I restarted my computer, opened the program again, and it was never synchronized. Synchronize normally. Later, I will use the 1.1.1 version for drawing to test whether there is a problem with the synchronization of the new drawing. I will continue to update my tests in #2555. @hoffmang9

**Comment by maomingyang1314** [comment]
Program synchronization should be normal. Friends who have synchronization, can try to see if port 8444 of the router is open.

**Comment by anderzheng** [comment]
I have open 8444 on my router, and test the port opened successfully by [yougetsignal](https://www.yougetsignal.com/tools/open-ports/).
But my chia 1.1.1 cann't synced from 4/24 5:17 am(with the height 175306).
It's has been 11 hours, what should I do?

**Comment by maomingyang1314** [comment]
I think I should know where the problem is. I am verifying my guess. It will take about 20 to 30 minutes.

**Comment by anderzheng** [comment]
> I think I should know where the problem is. I am verifying my guess. It will take about 20 to 30 minutes.
Have you found the problem?

**Comment by Bob3666** [comment]
how Do i openPort 8444 correctly?
I changed my settings on the router and i thought it might be open but yougetsignal says its closed

**Comment by maomingyang1314** [comment]
There is no problem with the 1.1.1 program under win10. The problem you mentioned may be that another device under the network occupies port 8444. That is, under a network, only one computer is allowed to run chia

**Comment by Bob3666** [comment]
I only have one computer. CMD -> netstat -an says Port 8444 is activated 
but you getsignal says no. What does that mean?

**Comment by maomingyang1314** [comment]
Maybe you need to wait for a while.

**Comment by joshepvn** [comment]
> Computer configuration, and whether you are drawing. If the drawing work is too heavy, the cpu may not have extra performance to synchronize, right?

draw what?

**Comment by maomingyang1314** [comment]
Mining must require a public IP. It is impossible to mine without a public IP. I only know now that I am in China and the network is NAT, so it cannot be synchronized. Can only connect to the mining pool

**Comment by maomingyang1314** [comment]
@hoffmang9I'm connected to the mining pool now, it's normal, and I only use software to draw pictures.

**Comment by anderzheng** [comment]
> @hoffmang9I'm connected to the mining pool now, it's normal, and I only use software to draw pictures.

where is the mining pool?

**Comment by maomingyang1314** [comment]
https://www.hpool.com/

**Comment by qfishpear** [comment]
same here, I can't connect to any peer now and can't get synced. It's for more than 2 hours

**Comment by hoffmang9** [comment]
Version 1.1.2 was released to help finding and syncing to peers.
