### ISSUE TITLE
我一直同步不了

### ISSUE THREAD

**Issue by Autumnfruit-qq** [Chia-Network/chia-blockchain#2554]
我一直同步不了

**Comment by maomingyang1314** [comment]
I did not encounter this problem in version 1.0.5. I used to update to 1.1.0, but there was a problem with the program, so I went back to 1.0.5. Maybe the new version is unstable. You can try, install the 1.0.5 version of the program

**Comment by hoffmang9** [comment]
Version 1.0.5 will stop working in three days.

**Comment by maomingyang1314** [comment]
I want to know whether 1.1.1 is running normally, and I have seen many people have problems in the problem area. And, when will these bugs be fixed?

**Comment by hoffmang9** [comment]
Follow these instructions and you will sync https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
