### ISSUE TITLE
The 1.1.1 version has synchronization problems, and the stable 1.0.5 will expire in three days

### ISSUE THREAD

**Issue by maomingyang1314** [Chia-Network/chia-blockchain#2555]
Dear Hoffman, I have been studying in the problem area in recent days, watching bugs, and answering some questions that I can solve. However, I knew not long ago that version 1.0.5 was about to lose support, version 1.1.1, several people were reporting that there was a synchronization problem. Will these problems be fixed in the short term?

**Comment by junyuewang** [comment]
same issue here, both windows 10 and ubuntu 20.

**Comment by maomingyang1314** [comment]
I think the official should solve the problem. If after three days, no new version is released to solve some problems. That will be our disaster.

**Comment by maomingyang1314** [comment]
Now, only 1.0.5 is safe. If you have any questions, you can install version 1.0.5, which can protect you for up to 3 days

**Comment by maomingyang1314** [comment]
Later, I will test version 1.1.1. I will pay attention to the synchronization of the program.

**Comment by maomingyang1314** [comment]
Program synchronization should be normal. Friends who have synchronization, can try to see if port 8444 of the router is open.

**Comment by maomingyang1314** [comment]
Later I will test whether there is a problem with the drawing function of MAC version 1.1.1. It takes about 8 hours. I will update the test results as soon as possible

**Comment by maomingyang1314** [comment]
I think I should know where the problem is. I am verifying my guess. It will take about 20 to 30 minutes.

**Comment by maomingyang1314** [comment]
My win10 and mac are on the same network. The mac1.1.1 version of the program can be synchronized normally, but win10 can not be synchronized. I looked at the router. The router port 8444 is mapped to the Mac port 8444. I guess the port 8444 is occupied by the Mac, and then the Mac network is closed. After about ten minutes, win10 still does not sync. There is only one picture under win10 @hoffmang9

**Comment by maomingyang1314** [comment]
I have now deleted all the files under the Mac, and the Mac should stop syncing. I'm waiting now, I don't know if win10 can synchronize successfully.

**Comment by maomingyang1314** [comment]
1.1.1 Is the drawing machine updated? How do I feel, as if drawing is faster than 1.0.5. I will call the log to take a look.

**Comment by hoffmang9** [comment]
If you have two machines on the same home network you must disable upnp on one as explained in the wiki faq

**Comment by anderzheng** [comment]
> If you have two machines on the same home network you must disable upnp on one as explained in the wiki faq

I have only one machine (win10) with upnp on, and it's a fullnode + harvester.
other machines are centos with upnp off, and only run harvester.
Is there anything incorrect?
My win10 has been not synced from this morning 5:17 with height 175306.

**Comment by maomingyang1314** [comment]
Okay, it will be tested later.

**Comment by anderzheng** [comment]
And 8444 is opened on my router.
One reason I guessed, is that the nodes I connected are all with lower height. So I cann't sync to the lastest.

**Comment by maomingyang1314** [comment]
Are two computers allowed to harvest under the same home network? @hoffmang9

**Comment by Bob3666** [comment]
how do i openPort 8444 correctly?
I changed my settings on the router and i thought it might be open but yougetsignal says its closed

**Comment by maomingyang1314** [comment]
You can try to restart the router. The software is estimated to be synchronized every 10 minutes, right

**Comment by heartoftokyo** [comment]
Version 1.1.1

I've tried on both UNBUNTU and Windows 10.  Windows 10 marginally better.

Port 8444 is open, I've checked from another network.

There are frequent connections, but usually no traffic in either direction, and then the connections drop.
When it does connect, most often, it is to a peer that has less information for syncing than my machine, and my machines do not appear to be sending much, if anything to them.

Sometimes it does sync.  I have over 20TB of plots, have been running for about a month now, and no hits either.  The estimated time to win hovers around 5- to 7days.

**Comment by lvcivs** [comment]
For those having pesistent issues, you can try this: stop the app, delete the peer DB which is located at `~/.chia/mainnet/db/peer_table_node.sqlite`, and start up again. The software will start looking for peers from zero and you may be luckier this time with getting good, up-to-date peers.

**Comment by heartoftokyo** [comment]
I uninstalled 1.1.1 and re-installed 1.0.5 on Windows, and it is working again.

**Comment by maomingyang1314** [comment]
There is a more serious bug, you can add plot without drawing, and it has been confirmed that you can get HCX, if this bug has not been fixed. The chia project will die.#2589 @hoffmang9

**Comment by hoffmang9** [comment]
Attempting to farm duplicate plots will fail even though the application may show both duplicates in your total. Timelords will only prove time on one copy of the same proof of space. Two or more of the same plots will always create the exact same proof of space.

**Comment by darwinjobchia** [comment]
> Now, only 1.0.5 is safe. If you have any questions, you can install version 1.0.5, which can protect you for up to 3 days

It seems once installed the newest one, cant use the old version again

**Comment by maomingyang1314** [comment]
Thanks to Hoffman, I tested it last night and this bug did not appear. But I found that the 1.1.1 version of the program can not delete tasks on win10. This problem did not occur under Mac and Ubuntu @hoffmang9I am deeply sorry for what happened last night.

**Comment by maomingyang1314** [comment]
This problem does not occur on Mac and Ubuntu

**Comment by maomingyang1314** [comment]
The deletion task of win10 is disabled, as mentioned in the update report of version 1.1.0

**Comment by mktsai** [comment]
when I upgrade to 1.1.2, I got Not Synced too.
port 8444 is open, BIOS and system time all correct, try to remove ~/.chia/mainnet/db/peer_table_node.sqlite and restart, reinstall 1.1.1 or 1.1.2, all not work. T_T
https://imgur.com/Zq1Qm1g

**Comment by darwinjobchia** [comment]
Mine windows 10 after install new version 1.1.2,  all back to normal and keep syncing now, I tried everything before as most ppl said, all not work, but aft updated back to normal.....

**Comment by hoffmang9** [comment]
Version 1.1.2 should fix this.
