### ISSUE TITLE
Isn't it a safety problem that can see the 24 momery words in your desktop?

### ISSUE THREAD

**Issue by muthubaby** [Chia-Network/chia-blockchain#2556]
Imaging you're farming in the office then your words could be easily exposed if somebody control your computer

**Comment by muthubaby** [comment]
Should we hide the 24 memory words on the software,  farmers I believe wouldn't like to have their words shown by clicking the eye

**Comment by maomingyang1314** [comment]
Yes, I think so too. We need to better hide our 24 words, at least allow us to need a password to view

**Comment by Teagan-pace** [comment]
It really needs to be hidden, it's silly to expose it directly on the screen

**Comment by muthubaby** [comment]
@hoffmang9 obviously need to improve in next release

**Comment by hoffmang9** [comment]
Your keys are secured by the OS Keyring. Don't leave your machine unlocked.

**Comment by muthubaby** [comment]
@hoffmang9  but why is it neccesary to show the words?  For farming we frequently use several computuers for me I using 10, if any one of those has leak the words it would be a very big saftey concern for the wallet

**Comment by hoffmang9** [comment]
Some users need to see the words later because they were to lazy to write them down the first time.
