### ISSUE TITLE
Backup of chia environment and wallets

### ISSUE THREAD

**Issue by hardhub** [Chia-Network/chia-blockchain#2557]
Is it enough to backup _.chia_ directory, and plots files to move it to new hardware or restore it due to crash or over reason?

I did not find any commands related to backups here: 
https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference

**Comment by hoffmang9** [comment]
All you need is your 24 words.

**Comment by hardhub** [comment]
> 
> 
> All you need is your 24 words.

I have read a lot of documentation (wiki, faq) but it is not clear anything regarding backup and which 24 words you mentioned.

**Comment by timjrobinson** [comment]
Had to do a bit of digging to find this. You can print your 24 words with:

```
chia keys show --show-mnemonic-seed
```

**Comment by hardhub** [comment]
> chia keys show --show-mnemonic-seed

Thanks ))

**Comment by ataman79** [comment]
OK, I have Chia wallet (old one 1.1.1) with some chia. I installed on another PC again the latest Chia Wallet (1.1.5) and all is sync, I entered my 24 words, it asked me for a backup file, I press skip and I can not see the chia ammount on my second PC. Why is that

**Comment by DMS-1981** [comment]
I have the same problem, could you solve it?

**Comment by l69zeroday94** [comment]
after sync is still 0 ?

ned, 16. svi 2021. u 01:42 DMS-1981 ***@***.***> napisao je:

**Comment by DMS-1981** [comment]
Yes, I can't think of what to do

**Comment by wongrembang** [comment]
i have same problem, i have uninstalled the chia application, delete ./chia folder and reinstall again. then i copy paste wallet and db folder to the new mainnet folder.....but it doesn't work...😥

**Comment by perguth** [comment]
Same here.

**Comment by Zeesy** [comment]
Check this out: https://github.com/Chia-Network/chia-blockchain/discussions/1753#discussioncomment-582137
`chia wallet show` then press S
