### ISSUE TITLE
write eror 1 - retry in 5 minutes

### ISSUE THREAD

**Issue by sduong77** [Chia-Network/chia-blockchain#2558]
I'm plotting 2 plots paralell but all 2 plots stand at 9% and the log say : " Only wrote 0 of 338640 bytes at ofset ....      . Error 1 . Retry in five minutes ."

-I ploted 4 plots and farming .
-Temp disk is 1TB Samsung SSD enterprise type
-Ram 16GB
-Win 10 64bit
-Final disk 10 TB Seagate

Please help me to pass this error ! Thanks !

![z2452363727910_391e8d00c43fc43f3fb9aa8828d451df](https://user-images.githubusercontent.com/83115318/115953873-3ca24e00-a518-11eb-8dae-067d279e3518.jpg)
![z2452363627197_a57c21d88fdaed71f9d85873da3cd44e](https://user-images.githubusercontent.com/83115318/115953878-41ff9880-a518-11eb-8ae1-ee5e2ed97978.jpg)
![z2452363626410_42f457f8984c4f18b77bdce5a0e945ad](https://user-images.githubusercontent.com/83115318/115953881-44fa8900-a518-11eb-84df-aa2d109bbf53.jpg)

**Comment by hoffmang9** [comment]
You are out of space or don't have permissions or you have a storage hardware problem.

**Comment by sduong77** [comment]
Thank Mr Hofmang9 !
I think the prolem is that ; the app Chia don't erase the old files of ploting for the newer to write .
I try to format the temp disk --> now I can plot to 70% ( 2 plots parallel ) .
Is it bug ?
Thanks !

> You are out of space or don't have permissions or you have a storage hardware problem.

**Comment by ggrichard** [comment]
Hi, I found same problem last night and my tmp disk is full. It recover to plotting after delete old tmp files.

**Comment by sduong77** [comment]
@ggrichard : yes , the problem I mean here is that : why the Chia app don't delete old file on temp disk automaticly , we must delete manually . Is this a bug ?

**Comment by hoffmang9** [comment]
It is a feature that we have not implemented yet. Your pull request to add it is welcome!

**Comment by thienhieu123** [comment]
@hoffmang9 I always remove manually temp file when they have issue, but I still meet the same issue. Sometimes it stuck in 1%, 11%, 32%,...
Can you help me? I format 2 disk (SSD, HDD) to ext4 but it's not better anymore

I try plot with 3390 MiB, 4000MiB, 6000MiB, 8000Mib (usage storage), 2 / 4 (threads). I just try to plot 1 file per time. But I notice when I increase more RAM (6000/8000) it will stuck in 32%, and with 3390, it almost stuck in 1%
P/s: 
CPU: intel core i5 5200U
OS: ubuntu 20
Ram: 16GB
SSD: 2TB
HDD 6TB
