### ISSUE TITLE
[BUG] Farming don't start

### ISSUE THREAD

**Issue by baltazar119** [Chia-Network/chia-blockchain#2559]
Hello there. I Abdulgazi ŞİMŞEK from Turkey. I started add the plot for Chia Coin yesterday. But the plots I created do not work. The plots show in the "Not Found Plots" section. It also always shows up as "not synced". I may not be able to figure it out because I am new. What can I do?
 Forgive me if I was wrong. Thanks in advance.

Win10

R5 3500x
GTX 1660 Super
PNY CS3030  500GB M.2 SSD
WD Blue WD40EZRZ 3.5 '' 4Tb, 64MB, 5400Rpm, Desktop HDD

![fullnode](https://user-images.githubusercontent.com/83115933/115954139-0523a980-a4f8-11eb-9885-083164222549.PNG)
![farmol](https://user-images.githubusercontent.com/83115933/115954141-05bc4000-a4f8-11eb-92bb-fb33b07fa0ff.PNG)

**Comment by maomingyang1314** [comment]
Dear Turkish friends, mining requires drawing. Your last picture shows that you are drawing. You need about 8 hours to draw a picture and you can mine before you can mine.

**Comment by baltazar119** [comment]
> Dear Turkish friends, mining requires drawing. Your last picture shows that you are drawing. You need about 8 hours to draw a picture and you can mine before you can mine.

Thanks for your answer. Why are the 3 plots I drew not farming?

**Comment by baltazar119** [comment]
I deleted everything. I started again. My plots are gone: /.
Hope it works this time. :(

**Comment by maomingyang1314** [comment]
I have access to the mining pool. I don’t have a public IP here, so I can only access the mining pool.

**Comment by baltazar119** [comment]
> Maden havuzuna erişimim var. Burada halka açık bir IP'ye sahip değilim, bu yüzden sadece madencilik havuzuna erişebiliyorum.

I'm sorry, i did not understand. 
 - 3 arazi neden çiftçilik yapmıyor? (2nd picture)-

**Comment by maomingyang1314** [comment]
Sorry, I misunderstood your meaning. This bug. It seems quite common.

**Comment by baltazar119** [comment]
> Üzgünüm, anlamınızı yanlış anladım. Bu hata. Oldukça yaygın görünüyor.

Do you know about the solution? Will it have any effect if I format it?

**Comment by maomingyang1314** [comment]
You can try to uninstall this version and install version 1.0.5. Version 1.0.5 is now considered safe, but it will expire after 2 days. I hope that after that, the official version can be released with modified bugs
