### ISSUE TITLE
"not found plots"

### ISSUE THREAD

**Issue by tiagocal** [Chia-Network/chia-blockchain#2560]
Hi guys,

I have a problem with the chia coin app I tried to create several plots and whenever it finishes loading it appears in a list of "not found plots". already tried to delete and install the application again but it does not solve .. it seems to me to have something to do with the private keys because i had to delete and create again a few times .. but i always create the new plot in my current private key, however, it seems to me that he insists on linking the new plots to old privates keys. As much as I delete and reinstall the app and delete all of its tracks from my computer whenever I reinstall it, it manages to see the history of plots and other directories. Does anybody know how to solve this ?

UPDATED:

when i check the keys at the powershell got this message:

WARNING: using a farmer address which we don't have the private keys for. We searched the first 500 addresses. Consider overriding xch18n03y2zrdln334z7tznlzrlv5dnxn5k4zvyhwr2nrtj72mx4dyvsgugvkn with xch1glu67e4unvurzg2z6pzw3ljjmq3dfwcvnu530spypkqduzfe0vpsa8znpe
WARNING: using a pool address which we don't have the private keys for. We searched the first 500 addresses. Consider overriding xch18n03y2zrdln334z7tznlzrlv5dnxn5k4zvyhwr2nrtj72mx4dyvsgugvkn with xch1glu67e4unvurzg2z6pzw3ljjmq3dfwcvnu530spypkqduzfe0vpsa8znpe

how do i fix this ?

**Comment by turing1988** [comment]
retry  to load

**Comment by hoffmang9** [comment]
Did you create more than one private key pair?

**Comment by Cumulo56** [comment]
I have a similar problem with two private keys. (see #25979

**Comment by tiagocal** [comment]
@hoffmang9 i really dont know.. im just trying to use for the first time.. 
when i installed the app, i must have created new keys to do tests, however, i can't delete all the keys to start one from scratch .. it seems like always when i delete the app (even deleting all the other folders in the appdata and others places) he always recognizes this old private key and keeps giving this bug ..
