### ISSUE TITLE
"Delete" a plot function does not work after upgrading to a version 1.1.1[BUG]

### ISSUE THREAD

**Issue by elmans1961** [Chia-Network/chia-blockchain#2565]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by elmans1961** [comment]
"Delete" a plot function does not work after upgrading to a version 1.1.1

**Comment by huiyi-gun** [comment]
me too

**Comment by aresstokrat** [comment]
same here at windows 10. Can i delete plot in CLI when runing gui? I dont wanna loose all plotting processes couse of 2 failing.

**Comment by PresidentCake** [comment]
me too, and it's terrible!

**Comment by hoffmang9** [comment]
As the release notes say we temporarily disabled the delete plots function because it was crashing before and we have not yet been able to fix the dependency we use that is causing the crash.

**Comment by Timpetu81** [comment]
This issue is not fixed in 1.1.6 Windows and a very annoing thing. Is there a workaround to abort queued plots (parallel or not)?

**Comment by hoffmang9** [comment]
A fix is coming in 1.1.7
