### ISSUE TITLE
[BUG] rclone google drive not working

### ISSUE THREAD

**Issue by jakejakeho** [Chia-Network/chia-blockchain#2566]
**Describe the bug**
Show 22 error when add rclone mounted drive

**To Reproduce**

1. setup google drive as G:\ by rclone
2. chia->Plots->Add Plot Directory->Select "G:\plots"

**Expected behavior**
Should be able to read the directory

**Screenshots**
![image](https://user-images.githubusercontent.com/34710113/115955529-96f7da80-a529-11eb-92ff-ef3575a1f4e2.png)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: windows 10 latest
- CPU: AMD Ryzen 5800x

**Additional context**

**Comment by Zanooda** [comment]
I am not related to the development of this project but: Please don't do this. You are fucking the service for all of us.

**Comment by jakejakeho** [comment]
I was just trying to use the spare space on google drive.

**Comment by hoffmang9** [comment]
It is not supported and if you get it to work Google will shut it down.
