### ISSUE TITLE
[BUG] chia network status  not synced

### ISSUE THREAD

**Issue by kahraman66** [Chia-Network/chia-blockchain#2567]
hello

program does not sync
can you help me
I tried vpn it didn't work
I updated the program did not work
I restarted the computer did not work
I reset the internet it didn't work
I closed and opened the program did not work
I've been waiting for 48 hours
can you help me

![image](https://user-images.githubusercontent.com/83118074/115955681-b595ab80-a500-11eb-8546-b22cd2c26679.png)
![image](https://user-images.githubusercontent.com/83118074/115955689-c6deb800-a500-11eb-85ea-139f8a2c2f1f.png)

**Comment by maomingyang1314** [comment]
I answered this question in #2555

**Comment by junyuewang** [comment]
which version of your chia is?

**Comment by kahraman66** [comment]
![image](https://user-images.githubusercontent.com/83118074/115956009-17571500-a503-11eb-8df1-dce9440fe37b.png)

**Comment by kahraman66** [comment]
I looked at the link you directed me to but I dont have any ıdea for #8444 about this can you help me
@maomingyang1314

**Comment by kahraman66** [comment]
> which version of your chia is?

1.1.1

**Comment by westerxddd** [comment]
I had to delete files from: ~/.chia/mainnet/db/
then the synchronization worked but had to be done completely from scratch

**Comment by kahraman66** [comment]
> chia/mainnet/db

![image](https://user-images.githubusercontent.com/83118074/115956679-deb93a80-a506-11eb-9166-2323e2d962c5.png)

from where

**Comment by hoffmang9** [comment]
This is not a support forum.
