### ISSUE TITLE
Advantage over faster hard drive?

### ISSUE THREAD

**Issue by the-oaks** [Chia-Network/chia-blockchain#2571]
I am new to Chia and got a few questions if this is possible.
Will a slower hard drive (e.g. connect via a USB ) be in a less competitive in mining? Thanks

**Comment by lvcivs** [comment]
This is an issue tracker for the software, not a support forum. You may want to head over to keybase (beginner channel) or the chia subreddit.

But to answer your question: No, a USB-connected drive is not less competitive. Your farmer has plenty of time to check the plots even on slow, external drive.

**Comment by the-oaks** [comment]
thanks for your answer, could you please give me a bit more hints on keybase? I tried to google (which lead me to a messaging app) but cannot find chia specific? while I am still "polluting" GitHub issue, may I ask another question? 

Does it mean the hard drive space will never be recovered until a chain is proven to be invalid/claimed?

**Comment by lvcivs** [comment]
Yes, it's a messaging app. You download, install and join the chia_network team.

Not sure if I understand your question. The finished plot takes up a certain amount of disk space. It will continue to take up space as long as you keep it. If you stop farming at some point, you can delete it and recover the space. Even if you win a block from this plot, it does not become invalid and you can continue farming it.

**Comment by the-oaks** [comment]
@lvcivs thank you very much for your explianation !
