### ISSUE TITLE
chia-blockchain-gui Start error

### ISSUE THREAD

**Issue by mrhu1314** [Chia-Network/chia-blockchain#2574]
chia-blockchain-gui After installation, use the command "run electron &",Can't start, the error prompt needs a library file. Where can I get this file?The error is as follows:
> chia-blockchain@ electron /home/ubuntu/chia-blockchain/chia-blockchain-gui
> electron .

/home/ubuntu/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-04-24T09_45_13_779Z-debug.log

[1]+  Exit 1                  npm run electron

**Comment by lvcivs** [comment]
Did you run the install scripts? Were there any errors during install?

Which version of Ubuntu are you on?

**Comment by mrhu1314** [comment]
Ubuntu 20 python3.8 .All the previous installations are normal. This is the last step to report this error

**Comment by hoffmang9** [comment]
Do you have Ubuntu Desktop installed?

**Comment by Tongie969** [comment]
I have exactly the same error, Ubuntu Desktop installed.

**Comment by Tongie969** [comment]
> Ubuntu 20 python3.8 .All the previous installations are normal. This is the last step to report this error

Is it a normal pc? Or something bigger?

**Comment by v2past** [comment]
ok ?

**Comment by haoge1214** [comment]
Ubuntu 20.04   python3.8    gui  start error !!!
error info  file


chia-blockchain/chia-blockchain-gui/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
[
[2021-05-03T15_55_41_696Z-debug.log](https://github.com/Chia-Network/chia-blockchain/files/6416026/2021-05-03T15_55_41_696Z-debug.log)
](url)

**Comment by pogla** [comment]
The same happened to me. I started a fresh CentOS 7 install and followed instructions. When I run `npm run electron &`, I get this in the output:

```sh
(venv) [root@3bm3 chia-blockchain-gui]# npm run electron &
[1] 27196
(venv) [root@3bm3 chia-blockchain-gui]#
> chia-blockchain@ electron /chia/chia-blockchain/chia-blockchain-gui
> electron .

/chia/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-04T07_36_42_568Z-debug.log
```

The logs look like this:

```sh
(venv) [root@3bm3 chia-blockchain-gui]# cat /root/.npm/_logs/2021-05-04T07_36_42_568Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/chia/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/chia/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /chia/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 info lifecycle chia-blockchain@~electron: Failed to exec electron script
12 verbose stack Error: chia-blockchain@ electron: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1022:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid chia-blockchain@
14 verbose cwd /chia/chia-blockchain/chia-blockchain-gui
15 verbose Linux 2.6.32-042stab145.3
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
17 verbose node v12.22.1
18 verbose npm  v6.14.12
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error chia-blockchain@ electron: `electron .`
23 error spawn ENOENT
24 error Failed at the chia-blockchain@ electron script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by Darkonyks** [comment]
All you need to do is 
```sudo chmod -R 777 /yourProjectDirectoryName```

it is all about permissions on folder....

**Comment by sonpython** [comment]
what is the compatible node version for Chia GUI? I did all the suggestions above but not work.

**Comment by Darkonyks** [comment]
> what is the compatible node version for Chia GUI? I did all the suggestions above but not work.

I' not sure. But one question: did you install gui as root user? If so, delete everything and star over as regular user.

**Comment by sonpython** [comment]
> > what is the compatible node version for Chia GUI? I did all the suggestions above but not work.
> 
> I' not sure. But one question: did you install gui as root user? If so, delete everything and star over as regular user.

I install as non-root user. It used to work but after upgrade to the latest version (1.1.17dev) I got that error. Trying to remove everything and start over with different node version (v12.22.1, v14.17.0, v16.2.0) but no luck.
any suggesntion?

**Comment by sonpython** [comment]
OK. I found the reason.

That's because I trying to open it on a ssh session. 

The GUI only available when you run it on a Gnome environment.

**Comment by gilmotta** [comment]
I have the same exact issue and I am running on Gnome environment.

**Comment by emosGambler** [comment]
Hello guys,
I've had experienced that issue literally yesterday and fix was simply rerunning the installation script for GUI:
`sh install-gui.sh`

**Comment by hoffmang9** [comment]
Fixed
