### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wanghongqi8548488** [Chia-Network/chia-blockchain#2577]
I have p a total of 5 files, and it has been synchronized for a day since the p is finished. Is it normal?
![16192644234878113099110388925139](https://user-images.githubusercontent.com/82766513/115957426-f5768600-a534-11eb-9760-e758ea53350a.jpg)
![16192644469854087749000515608996](https://user-images.githubusercontent.com/82766513/115957435-00c9b180-a535-11eb-89f3-1a145e0906b2.jpg)

**Comment by lvcivs** [comment]
Your node probably has problems finding peers. Read this: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

You can try adding this peer manually: `node-apne.chia.net:8444` (Asia)
