### ISSUE TITLE
[BUG]  atualizei  o chia, devo sinncronizar tudo de novo? si a cada hora que atualizar  o aplicativo pra uma nova versao,estavo com dificultade 39,quando atualizou voltou pra dificuldade 9, muito tempo. tem algum modo de acelerar o sncronzacao? 

### ISSUE THREAD

**Issue by adrianodr** [Chia-Network/chia-blockchain#2583]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by lvcivs** [comment]
If I understand your question correctly, then the answer is no: When you upgrade to the newest release, you do not need to sync again from the beginning. You only need to sync a little bit that you missed during the time your node was offline while upgrading. 

There is no way to speed up the syncing.

I am not sure what you are saying about the difficulty. It has been more or less constant at 39.
