### ISSUE TITLE
[BUG] Chia 1.1.2.dev0 is installed when pulling in -latest on fresh Ubuntu 20 LTS

### ISSUE THREAD

**Issue by Mogera** [Chia-Network/chia-blockchain#2588]
**Describe the bug**
Install procedure installs 1.1.2.dev0 instead of 1.1.1

After following official install instruction on freshly installed Ubuntu 20 LTS system I'm following official install steps from Wiki. I end up with a dev version installed on my system which seems to be broken.

**To Reproduce**
Steps to reproduce the behaviour:

**Clean up local install by** 

- Remove /chia-blockchain/ (remove entire Chia Git directory and contents)
- Removed ~/.chia/ (remove local Chia settings)
- Removed ~/.cache/ (remove pip caches)
- Ensure VENV is no longer active by running 'deactivate'
- Reboot system ensuring no Chia processes are running

**Redo official installation steps from guide for Ubuntu**

- git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
- (also tried pulling in specific _-b 1.1.1_ tag and _-b main_ but keep getting inconsistent results)
- cd chia-blockchain
- sh install.sh
. ./activate

**Check resulting installed version**
> chia version
1.1.2.dev0

**Expected behavior**

1.1.1 to be installed instead of 1.1.2.dev0

- OS: Linux Ubuntu 20 LTS
- CPU: AMD Ryzen 7 3700X

**Additional context**

Would love to hear what I am missing or could try..

**Comment by hoffmang9** [comment]
This is fine. It's annoying git behavior that we plan to address a different way later.

**Comment by Mogera** [comment]
Would be interested to hear how to circumvent the issue.

**Comment by hoffmang9** [comment]
You have to go into chia-blockchain-gui and usually delete the package-lock.json that gets created in there.
