### ISSUE TITLE
Change wallet address not working

### ISSUE THREAD

**Issue by ChenYCL** [Chia-Network/chia-blockchain#2592]
hello, i use two pc  plot farm , use  same  private key .Today i clicked button  get new wallet address, another show pc not synced.
two pc get different wallet address , if i continue plot farm to romote disk. What impact will  have?

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-should-i-not-run-more-than-one-node-on-a-home-network-and-whats-this-about-upnp
