### ISSUE TITLE
[Question]Do the farming takes...

### ISSUE THREAD

**Issue by Peter82kr** [Chia-Network/chia-blockchain#2594]
...same amount of ram as plotting?I got only 16 gig ram and im wonder how many paralell farmings (k-32) i can run?I know value of ploting but its the same for each farming queue?Thanks in advance for any answers.

**Comment by maomingyang1314** [comment]
The memory only needs to follow the default settings, and the number of threads can be set to 4. For parallel tasks, if the memory is 32G, it is best not to exceed 8. 8 tasks, preferably with two M.2 NVMe

**Comment by Peter82kr** [comment]
8 tasks for 32gb but what tasks?Plotting or farming? Farming consumes same amount of ram as ploting or not?

**Comment by maomingyang1314** [comment]
I’m talking about drawing, farming does not require performance, or in other words, performance requirements are very low

**Comment by Peter82kr** [comment]
Ok that was what im asking for.Thanks :)

**Comment by maomingyang1314** [comment]
Please close the question. I am not an administrator, I have no way to close the question

**Comment by Peter82kr** [comment]
I got slow machine used before as network attached storage.Im switching nas to chia farm.Ok im closing.
