### ISSUE TITLE
[BUG]dead lock

### ISSUE THREAD

**Issue by jackge0323** [Chia-Network/chia-blockchain#2596]
The normal running process will suddenly freeze, and it must be deleted and restarted.

<img width="1003" alt="iShot2021-04-24 21 51 49" src="https://user-images.githubusercontent.com/25917176/115961107-7fc7e580-a547-11eb-8e1e-832463904ce0.png">

- OS: Mac Bigsur 11.23
- CPU: 10850k

**Comment by hoffmang9** [comment]
Are you using the default settings for a k32? How much RAM does your machine have?

**Comment by jackge0323** [comment]
Yes,I'm using default settings,my machine RAM 32GB.

**Comment by razamataz** [comment]
The same thing I have, in the third phase, one of the processes freezes. There is a lot of free memory.

**Comment by hoffmang9** [comment]
These are problems with you machine.
