### ISSUE TITLE
[BUG] unit of plot create buffer

### ISSUE THREAD

**Issue by pubyun** [Chia-Network/chia-blockchain#2598]
chia plots create -h
  -b, --buffer INTEGER            Megabytes for sort/plot buffer  [default:  4608]

should the unit be MiB? and the default should be 3389 now?

please refer to class DiskPlotter of plotter_disk.hpp:
        uint64_t memory_size = ((uint64_t)(buf_megabytes - sub_mbytes)) * 1024 * 1024;

**Comment by hoffmang9** [comment]
Yes and that change is already in the next version.
