### ISSUE TITLE
plots al 100% dont move at the final directory and next plots are queued

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#2600]
good afternoon
I have the following problem
I recently launched to plot 2 groups of plotting. I have finished the first with 3 plots at 100% (in parallel) and the second group of 4 that was not in parallel has finished me 1 at 100% and the following have not started.
the problem is that although it has already copied the files (the 4 finished ones) to the temporary folder, the chia process continues to control them and they are in both directories all with extension plot.2.temp and I don't know if I should wait or change the extension. I don't know why it doesn't do it automatically. Even if I change the extension to those that are in the plotting directory (which Chia no longer controls) I can pass them to the definitive directory but the plot.2.temp does not let me delete them because they are still controlled and therefore they take up space. If I close the chia I will desynchronize myself and I will lose the plots that I am creating and the 5 pending plots of the second group do not start either
Can you help me?
Thanks

**Comment by maomingyang1314** [comment]
If the progress reaches 100, you can look at the log. If the display is successful, you can close the program and manually modify the suffix. Then open the program. Maybe it can trigger a bug

**Comment by realbluefish** [comment]
Yes but i lose work of current plotting and lose sync....my bad

**Comment by handsomedude** [comment]
Once 100% is reached, it then stays like that until the temp file has copied over to the final drive.

Open taskamager on windows and look at the hard drive usage on chai task.
You can see if hard drive is being used and copying over file.
Can take 10-60 mins depending on the speed of you destination drive.

I have a usb 3.1 8tb drive and that copies the 101gb file over in about 15-20 mins

**Comment by aresstokrat** [comment]
If move plots manualy changing suffix (.temp), and if you are using pool mining this plots will not work, this is error u will get::
Exactly this plots i moved manualy changing suffix.

`An exception was caught in __except.1/Download3/plots (9/22) 40%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-21-13-53-d6e106d20933ec9b2726c3a409610e906cb25eaa27948eff1ceb524a3b3ab8d3.plot" tid=1
An exception was caught in __except.1/Download3/plots (10/22) 45%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-21-13-53-e333c4106a7cfe6142e88f5b1121805a8f6ff9301b2ad3cc5fa01b90079c1e0f.plot" tid=1
An exception was caught in __except.1/Download3/plots (11/22) 50%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-21-13-55-21bae630199559f1bce2a4ebb3d13691f264a5e75f32d5fd59cf15c87f5b51b2.plot" tid=1
An exception was caught in __except.1/Download3/plots (12/22) 54%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-02-03-c9c0cc708b9796d80f763820377a97981d7c20c180865a522a3ef4af1fc81801.plot" tid=1
An exception was caught in __except.1/Download3/plots (13/22) 59%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-02-03-e9301f29320c46ae8f37e8892ae1f0e6e43d19af6a79df2afc5c173ac18c81ae.plot" tid=1
An exception was caught in __except.1/Download3/plots (14/22) 63%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-02-26-b26c888a96ccc9224720025f4fa20f33f605354be4843664b42d177eecee1da2.plot" tid=1
An exception was caught in __except.1/Download3/plots (15/22) 68%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-03-01-5002ec81901d9db099bf5228b198d8316d6080642c14c598aea59d5672ae0dca.plot" tid=1
An exception was caught in __except.1/Download3/plots (16/22) 72%
time="2021-04-26T00:12:05+03:00" level=error msg="add plot file" error="open fail" f7="{loggers.go,logging.CPrint,156}" f8="{plotterSpace.go,chia.(*PlotterSpace).Load,120}" f9="{plotterSpace.go,chia.NewPlotterSpace,59}" file="\\\\192.168.1.101\\Download3\\plots\\plot-k32-2021-04-22-03-01-b00563ad751cd4fbae88f44462e5d2c8b18dca1310190cee6a36168e77d71a11.plot" tid=1`

**Comment by hoffmang9** [comment]
Sometimes a rename works and sometimes it does not. You have to delete the bad plot. These are not bugs and do not belong in Issues.
