### ISSUE TITLE
Failed to convert unwritten extents to written extents

### ISSUE THREAD

**Issue by GiverDead** [Chia-Network/chia-blockchain#2601]
![photo_2021-04-24_16-28-20](https://user-images.githubusercontent.com/15796944/115962758-86456580-a525-11eb-9074-8dc0032a3b7e.jpg)

command : chia plots create -t ... -d ... -r 3 -b 3000
file system is ext4

**Comment by hoffmang9** [comment]
Something is wrong with your file system.
