### ISSUE TITLE
[BUG]new gui 1.1.1  version can't delete plot in progress

### ISSUE THREAD

**Issue by chiabetatester** [Chia-Network/chia-blockchain#2603]
Had to upgrade from windows gui 1.05 to 1.1.1 as it stopped connection to wallet and lost 2 plots in progress :(
started new plots 4 in parallel and then queued another 4 in parallel , however it did not queue the 2nd 4 plots , it started the 1st plot of the 2nd queue and queued the remaining 3.
i tried to stop the 5th plot because i cannot possibly have enough hdd temporary space to do 5plots in parallel but the function to delete the 5th plot in progress is greyed out :( i can view the log but not delete the plot in progress. in version 1.05 i could delete a plot in progress. 
what is going to happen to the plotting in progress when it runs out of space ?

**Comment by hoffmang9** [comment]
Please read the release notes where we explained this.

**Comment by chiabetatester** [comment]
it still doesn't explain why the 2nd batch of the queue started the 1st plot of the 2nd batch when it is supposed to be queued. nor have u explained what is going to happen when my hard drive runs out of space because i can't delete the plot in progress ????
