### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by sujiansj** [Chia-Network/chia-blockchain#2606]
why?
![image](https://user-images.githubusercontent.com/20200528/115964283-48146a00-a556-11eb-9102-446fe1b35cc9.png)
![image](https://user-images.githubusercontent.com/20200528/115964321-73975480-a556-11eb-87da-2de87fcd2665.png)

**Comment by hoffmang9** [comment]
The plot is bad. Bad plots are usually caused by faulty RAM settings or RAM sticks.
