### ISSUE TITLE
[BUG] Failing due to 0 bytes written to one of the temp buckets

### ISSUE THREAD

**Issue by garyhkirk** [Chia-Network/chia-blockchain#2613]
**Describe the bug**
Plotting fails with the following issue:

Only wrote 0 of 1048554 bytes at offset 238021758 to "C:\\Users\\Gary\\Desktop\\ChiaTemp\\plot-k32-2021-04-24-16-51-eb45972440274248e609870256406a3d74167746b3699dd2769e70d9e1bffb3c.plot.p1.t4.sort_bucket_088.tmp"with length 238022656. Error 1. Retrying in five minutes.

(This was the 10th retry)

**To Reproduce**
Was a single test plot as I was having other issues...
I tried from PowerShell with all correct parameters
There was 800B of space on the NVME temp drive (and still plenty of room)
The destination drive is 2TB SATA, correctly formatted, working fine, empty  

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- CPU: Ryzen 5800x
- RAM: 80GB (eigthy)

**Additional context**
Not having issues with any other program or using the drives in question

**Comment by hoffmang9** [comment]
There is a hardware or filesystem issue. Sometimes it is RAM but the retries are usually due to storage errors.

**Comment by garyhkirk** [comment]
Thank you for the swift response, I am trying out a different drive on the troublesome machine. If that works it's probably the NVME drive (new) that caused another issue that I will update and close.

**Comment by mylastore** [comment]
@garyhkirk I have the same issue and I have two different SSD m.2 and both are giving me errors for the last 2 days and won't let me create plots no more. Using the latest git repo for Mac M1 chips
