### ISSUE TITLE
[BUG] Message 22

### ISSUE THREAD

**Issue by Einstein098** [Chia-Network/chia-blockchain#2619]
I can not open my Plot diretory. 

I can not open the plot-directory if I want do this there come a Massage it shows "22" an a "OK" Button 
This Massage also come by start of the App

If i reload it only shows "Connecting to wallet"

- OS: Windows10 
- OS Version/Flavor: 20H2
- CPU: Intel Core i7-4770K 

![chia](https://user-images.githubusercontent.com/83136144/115969155-d2030980-a53b-11eb-96ca-acaa1f44baf1.PNG)

**Comment by hoffmang9** [comment]
One of the plot directories in your config.yaml is wrong or inaccessible. Horrible dialog box - we know.
