### ISSUE TITLE
Chia on Mac constantly shows loading spinner

### ISSUE THREAD

**Issue by liegeandlief** [Chia-Network/chia-blockchain#262]
I have installed Chia on my Mac with the new installer but when I open the Chia application all that shows is a constant loading spinner and there are the following errors in the console:

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/12057877/83633396-cbbd1500-a598-11ea-952d-2cc22cd0932b.png">

My Macbook Pro is running MacOS Catalina 10.15.14.

**Comment by mariano54** [comment]
Thanks for the bug report. Can you close the app and check if there are any chia server running in the Activity Monitor?

**Comment by liegeandlief** [comment]
The chia server is not running in Activity Monitor

**Comment by andyoyellow** [comment]
I'm experiencing the same error on a similar system, Catalina 10.15.5
Chia server also not running

**Comment by burnardia** [comment]
It seems I'm having the same issue on Windows. Possibly related to the pre-2014 CPU?

**Comment by hoffmang9** [comment]
The windows issue is well documented everywhere. A fix will be forthcoming shortly.

**Comment by burnardia** [comment]
@hoffmang9 thanks for confirming. I'll be on the lookout for an update.

**Comment by hoffmang9** [comment]
Fix is here: https://github.com/Chia-Network/chia-blockchain/wiki/Windows-pre-Haswell-1.8-workaround

Closing this issue as the MacOS items have been handled in 1.8 and the unrelated Windows issue patch is above.

**Comment by burnardia** [comment]
worked like a charm
