### ISSUE TITLE
Why does the GUI close the node on exit?

### ISSUE THREAD

**Issue by TarekJ03** [Chia-Network/chia-blockchain#2623]
I understand that it's useful if you're only interacting with Chia from the GUI, but if I e.g. start farming from the terminal and then start the GUI to look at the progress of a plot (in percent, because why not), after leaving the GUI the node gets shut down, even though it wasn't even initiated by it. And even without that, why is there no choice to keep the node running in the background, like in the Monero GUI, for instance? It's not like there's no point to keeping the node synchronised, so why force the shutdown? Or is there maybe a flag to be set when starting the GUI?

**Comment by hoffmang9** [comment]
It is an enhancement that is coming. We had to back it out earlier.

**Comment by TarekJ03** [comment]
Alright, thank you!
