### ISSUE TITLE
[BUG] Since installing 1.1.1 on my MacBook syncing is not working. The solutions presented in this forum are not clear to me, as I am not that computer minded. Up till 1.1.1 farming went automatically, now it seems I have to open port 8444. I have no clue as to how to do that on a MacBook Pro (Big Sur). Unless a clear and understandable solution is available, farming (and thus the CHIA project) stops here for me.

### ISSUE THREAD

**Issue by rolandbezemer** [Chia-Network/chia-blockchain#2625]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
