### ISSUE TITLE
Plots moved to a new harvester are not appearing on Latest Block Challenges in main node GUI

### ISSUE THREAD

**Issue by maco1717** [Chia-Network/chia-blockchain#2626]
Hi,

I have a hosted baremetal server that is running in main mode.

I want this node to be used as a plotter and then have a slower disk server to be used as a harvested.

I have not started plotting on the main node server yet, its a new install.

I already had some plot that where generated earlier from another server that was running on full mode.

I am now trying to move the plots to the harvester server but they are not appearing in the farms "Latest Block Challenges" how ever the harvester does appear under "Your Harvester Network"

I am not sure what I am doing wrong, I have followed [this ](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines)to create the harvester [this ](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian) to install chia.

I have enabled INFO logging in both the main node and the harvester. In the harvester I see **new_signage_point** with the IP of my main node, on my main node how ever I don't see **new_signage_point** INFO entries with the IP of my harverster, I do see however other IPs, should I block the port 8447 to the world on my main node and only have it open to my harverster?

I have set farmer-peer on the harverster to the main node IP using `chia configure --set-farmer-peer MAIN_NODE_IP:8447` 
ports are open, I used the main node ca cert to generate the harverster node's cert and added the keys I used to create the plot to the harvester node.

running `chia plots check` in the harverster show me the plots that have been loaded in the harvester as expected.

I have tried restarting the harverster and the GUI but no luck.

I just put some added some plot to be generated on my main mode I can see in the farms **Last Attempted Proof** the message

> None of your plots have passed the plot filter yet. But you are currently farming 304.123 GiB

Any advices would be appreciated, also please let me know if there is any information I should provice.

Thanks.
\M

**Comment by joehuchina** [comment]
same issue here.  Could not check  the plot  on main-node  from harverster . But i could see the connection to mainode:8447  there .

**Comment by dorkmo** [comment]
did you add the plot folder to the directory? you can check your config.yaml file and it should show all the folders its looking for plots.

**Comment by maco1717** [comment]
> did you add the plot folder to the directory? you can check your config.yaml file and it should show all the folders its looking for plots.

you mean on the harvester? if so then from my original comment
> running chia plots check in the harverster show me the plots that have been loaded in the harvester as expected.

I have ended up setting up the harverster as a main node, I will experiment with this setup else and when I figure it out I will change it
