### ISSUE TITLE
[BUG] full node wont start/doesnt listen on port

### ISSUE THREAD

**Issue by altered-beast** [Chia-Network/chia-blockchain#2630]
**Describe the bug**
when i run

`chia show -s`

i get this error

```
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up 
```   

i have started the full node but it isnt listening on any ports any ideas on how to fix?

**To Reproduce**
unsure

**Expected behavior**
node starts and begins to sync

**Desktop (please complete the following information):**

- OS: linux
- OS Version/Flavor: ubuntu 20.04
- CPU: Intel Xeon X3430

**Additional context**
using cli client

**Comment by hoffmang9** [comment]
You need to open port 8444 on your router - https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by altered-beast** [comment]
the port is already opened and the issue is that the node does not run at all

**Comment by kaspar030** [comment]
did you solve this? hitting it too with 1.1.15dev from docker.

**Comment by happy1989525** [comment]
I fix it, it may cause by different user you are login, for example, you use root user to "chia start all", but next time you use different user to check "chia show -s", it will return the bellow error.
`Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up `

**Comment by Au7arch** [comment]
I'm seeing this error also, except I'm the only user, and I'm only using my admin account for chia installation and executing.  This is during the initial full node sync.  The port is open on my router.
