### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by YDDY1** [Chia-Network/chia-blockchain#2631]
Hi, I'm new to Chia and I've been watching several tutorials to learn how to plot but I've found conflicting information and it's not clear to me how to configure the options in the program. I need help. I have an i7 10700k 8/16 threads processor, 128GB ram, 2tb nvme ssd , and a 10 tb hdd, I want to do all the plots that I can in parallel. I think I read that I can do up to 7 in the last update. What is not clear to me is what to select in the following

Plot in Parallel or Add Plot to Queue?

RAM max usage?

Number of threads?

Number of buckets?

Disable bitfield plotting?

Exclude final directory?

**Comment by hoffmang9** [comment]
Issues aren't for technical support. Try - https://github.com/Chia-Network/chia-blockchain/discussions
