### ISSUE TITLE
white screen in windows app

### ISSUE THREAD

**Issue by omg1hereiam** [Chia-Network/chia-blockchain#2644]
Hi all, 
Got an issue when Chia Blockchain screen turned white on Windows. I pressed Reload, it finished with white screen again. 
Then another press on Reload just stuck in "Logging in" state. 
Then I pressed Force Reload and it stuck in "Connecting to wallet" state. After this no matter what I pressed Reload or Force Reload it just stuck in "Connecting to wallet". 
Checking Task Manager indicates that my RAM is ~80% in use and my disks are in use as well, So my guess that issue is with Windows GUI of the app mostly.   
Thanks

**Comment by corviato1** [comment]
Having the same problem.  Am hours into making Plots and don't want to reboot.  Anyone know if it should just be left alone, or is a restart needed?   Also, how much RAM does the node(not Plotting) require?

**Comment by Crypto-78** [comment]
follow... i have the same problem. Reload and Force reload not working

**Comment by corviato1** [comment]
@Crypto-78, yeah Reload and Force reload not working for me too :/

**Comment by zsp00** [comment]
> Having the same problem, it just says connecting to wallet after not touching the app for several hours. Am hours into making Plots and don't want to reboot. Anyone know if it should just be left alone, or is a restart needed? Also, how much RAM does the node(not Plotting) require?

top menu click reload item

**Comment by Crypto-78** [comment]
🤣🤣🤣🤣🤣

Il sab 24 apr 2021, 21:51 zsp ***@***.***> ha scritto:

**Comment by maomingyang1314** [comment]
If this problem occurs when you are drawing, then it is probably caused by insufficient computer performance, right?

**Comment by omg1hereiam** [comment]
> If this problem occurs when you are drawing, then it is probably caused by insufficient computer performance, right?

what drawing? just to clarify, I am plotting on my separate PC where there is nothing happening during weekend. Peak load of CPU was up to 60%-70%, RAM up to 70%-80%, Disk obviously up to 100%. Remaining resources should be more than enough to run PC and issue seems to be with Chia client only, where Reload buttons just didn't do anything.

**Comment by PresidentCake** [comment]
This kind of problem also appeared last time when my computer performance was about to crash, and finally I had to close the application and try again. So it is best not to push your computer performance to the limit, and the allocated memory and cpu thread usage should be left over.

**Comment by hoffmang9** [comment]
We believe we know what is causing this and are working on a fix.

**Comment by corviato1** [comment]
@hoffmang9 what do you think is causing this issue?

**Comment by hoffmang9** [comment]
It is a resource leak in how the plot logs get handed around.

**Comment by trinitiwowka** [comment]
есть какие-то новости?

**Comment by tajchert** [comment]
I can confirm this. It happens literally each day and results in having to restart whole Chia app as refresh doesn't solve it (it freezes on "connecting to wallet". I'm on 1.1.2 (updating to 1.1.3 as anyway chia app hang itself again so had to restart it anyway).
This is pretty frustrating as whole current batch of work is lost.

**Comment by rochonno** [comment]
I just encountered this as well. White page on the windows chia app, fails to reload (or rather does so indefinitely), and a whopping 28GB ram usage by daemon. 

I copied the mainnet\log\debug.log information from when new errors started happening into a separate txt file. If this would find a solution for the root cause rather than just solving the memory leak I would be more than happy to share it

**Comment by madrigo64** [comment]
The same problem after night on Windows 10, and after "Reload" option  working fine.

**Comment by madrigo64** [comment]
Ok, so I reinstalled Windows 10 with all updates to 20H2
and it's seems problem disappears.

**Comment by hoffmang9** [comment]
Fixed a while ago.

**Comment by bobyturk** [comment]
i have the same problem now ! with chia 1.2.7 !!! whiutescreen after about 3-4 hour minig , im not plotting just mining

**Comment by omg1hereiam** [comment]
Had same issue again today, during db syncing this time, but so far only it happened only once. chia 1.2.7, windows

**Comment by Flimshady** [comment]
I have the same issue using Chia Wallet 1.2.11 on Windows 10. I let it run for some time and the app goes into a whitescreen, I can only recover my wallet using my security phrase in order to use the app again.

**Comment by Bulli** [comment]
I have this issue since version 1.4.
ATM I'm on 1.5 and every 2-3 days this happens. "chia farm summary" indicates that the farm is still running. It's only a GUI thing.

**Comment by luotinen** [comment]
Bug confirmed in 1.6.0 (on Windows)
