### ISSUE TITLE
[RESOLVED] Plots not passing proofs in 5-6 weeks (5-7 days estimate to win) 

### ISSUE THREAD

**Issue by heartoftokyo** [Chia-Network/chia-blockchain#2645]
**Describe the bug**
I am assuming this is a bug, but it is hard to tell.

I've been farming for 7 weeks, and for the last 5-6 weeks have been about 5-8 days to "win", but have not won any Chia.
(My machines are plotting not quite fast enough to keep up with the growth of the network)

At this point about 1/3rd of the plots pass the first filter (just 22 TB of plots).  There were a few bad plots found by Chia plots check, which have been deleted.

I assume expected days to win means a 95% confidence interval, based on the probability of winning each challenge.
If that's the case then there is only a 5%^5.5 or .00006% chance of it randomly happening this way, versus it being a bug or security issue.

**To Reproduce**
Create a bunch of Chia plots, and wait 5x the "expected days to win" without a win.

**Expected behavior**
Several wins during that period.

**Screenshots**

**Desktop (please complete the following information):**
1/2 of the time was Ubuntu 20x, AMD machine 128GB, etc.
the other half I moved it to a windows machine, windows 10 pro, Intel i9 series 9.

**Additional context**
Version 1.1.1 wouldn't connect to peers correctly, so I reverted to version 1.0.5 which seems to work fine.
Port 8444 is open and working fine.  Under linux there were never more than 2 peers connected.  Under windows there are about 20 full node peers.
The certificates/etc seem to have been copied fine between machines, and there are no warnings about mismatches or missing private keys.
It is a single machine running with the fullnode/etc.

**Comment by ilyabez** [comment]
I have exactly the same problem.   Running on Windows, and I have 440 plots.   Expected time to win is 2-3 days,  but I have not won a single CHIA in 3 weeks. I checked the logs and everything looks ok with messages like that:

2021-04-24T20:04:30.902 harvester chia.harvester.harvester: INFO     3 plots were eligible for farming 845029fb2d... Found 0 proofs. Time: 0.24989 s. Total 440 plots

Not sure what the problem is and why I am not winning any CHIA

**Comment by tsaohao** [comment]
I meet the same issue.  

Is there any possible reasons to make one very "unlikely" to win a reward? May be hardware limit or network settings etc. ?

**Comment by heartoftokyo** [comment]
When a pool shows up in the "is_transaction_block" does that just mean they validated a transaction?
&
Where do I find the private key for the pool?
Could the pool be messed up on our machines?  Is the pool tied to the reward address?

**Comment by heartoftokyo** [comment]
Resolved:
Somewhere along the way, I had set up a different wallet on one machine.  The pool I am using is attached to that wallet (which I deleted from all of the machines.)

How did I figure this out/How can you check?

Go to:  https://www.chiaexplorer.com/blockchain/search
And enter your pool public address (starting with 0x before the other hexidigits)

This showed me 6 search results.  I opened them and saw the "is_tranaction_block" had my pool number, from there saw the wallet being paid to, and looked through my notes and saw the key and mneumonic written down.

Looking closer there are other questions though.

Most of the entries had:  "unfinished_reward_block_hash" in them
Does that mean the other blocks might have passed but it timed out? 

Also, there were a number of "Reward claims incorporated" entries with some pretty large wallets (100 to 22,000 chia).

**Comment by mariano54** [comment]
Are your plots passing the filter and doing so in a quick time? (<5 seconds)?

**Comment by ilyabez** [comment]
Yes, all plots passing in real time
I can send you a chia log file if you have time to take a look
Ilya
    On Sunday, April 25, 2021, 02:48:57 AM CDT, Mariano Sorgente ***@***.***> wrote:  
 
 


Are your plots passing the filter and doing so in a quick time? (<5 seconds)?

**Comment by hoffmang9** [comment]
Not a bug.

**Comment by ilyabez** [comment]
I discovered source of the problem.   Farmers's address in "farming configuration settings" was different from the "wallet address" on the dashboard.
According to chia explorer I have 24 XCH farmed already that all went to the "farmers address".  But they do not show on the dashboard that only shows "wallet address" and that is empty
I manually changed "farmers address" in the Chia configuration settings to my wallet address, hopefully in the future all farmed XCH goes to the wallet
Now need to figure out how to move 24 XCH from the "farming address" to the wallet




    On Sunday, April 25, 2021, 12:40:09 PM CDT, Gene Hoffman ***@***.***> wrote:  
 
 


Closed #2645.
