### ISSUE TITLE
Plotting in WSL2 consumes more space than expected in temp drive.

### ISSUE THREAD

**Issue by zrjaa1** [Chia-Network/chia-blockchain#2647]
Hi, I followed the [installation instruction for WSL2](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#WSL2). Increased the maximum capacity of WSL2 to 2TB(`Disk /dev/sdb: 1.98 TiB, 2147483648000 bytes, 4194304000 sectors`) and started 2 processes to run `chia plots create -k 32 -b 6750 -t /mnt/p -d /mnt/d -n 1 -r 4`. The temp drive(`/mnt/p`) has 1.8TB available space and was empty before plotting. Now I can see that 865GB are consumed when both processes are in phrase 1, computing table 5 (complete log files attached below). According to the wiki, with k=32 plot the temp space used is 256.6GB, and this matches the behavior when I plot in Windows with GUI. So I have no idea why more than 2*256.6 GB is used with 2 plots in WSL2. Confirmed that there is no other plotting process running.

For debugging purposes, I stopped plotting processes and move temp files to the trash. I still see that there is 771GB space used, although I cannot see any file in it through windows, with hidden files visible. I have to format the disk to make it empty again.

I see a similar issue happened in another windows PC with WSL2 plotting so I think it's not an intermittent issue. I suspect that some of my configurations are wrong or Windows couldn't identify the space correctly when the WSL2 is operating on it. Did anyone else encounter similar issue?

[logfile-1.txt](https://github.com/Chia-Network/chia-blockchain/files/6370921/logfile-1.txt)
[logfile-2.txt](https://github.com/Chia-Network/chia-blockchain/files/6370922/logfile-2.txt)

**Comment by Doom4535** [comment]
I can't guaranteed that this is your issue, but I faced something similar when I pushed my system to the limit on RAM and the windows paging file ballooned to close to 60GB.  If you are plotting on the same drive that your paging file is on (should usually be the host disk), this could explain why the system has ballooned and you haven't been able to locate where the files are (the default disk space usage tools seem to ignore the paging file).  I used [WinDirStat](https://windirstat.net/) to view my disk usage, and it did detect the paging file and displayed its size; other similar tools will likely do this as well.

Here is a guide to change the paging file size, it also shows how to view the current size: https://computerinfobits.com/adjust-page-file-windows-10/

**Comment by zrjaa1** [comment]
> I can't guaranteed that this is your issue, but I faced something similar when I pushed my system to the limit on RAM and the windows paging file ballooned to close to 60GB. If you are plotting on the same drive that your paging file is on (should usually be the host disk), this could explain why the system has ballooned and you haven't been able to locate where the files are (the default disk space usage tools seem to ignore the paging file). I used [WinDirStat](https://windirstat.net/) to view my disk usage, and it did detect the paging file and displayed its size; other similar tools will likely do this as well.
> 
> Here is a guide to change the paging file size, it also shows how to view the current size: https://computerinfobits.com/adjust-page-file-windows-10/

Hi @Doom4535 , the temp drive that I used is different from the host system(windows) drive. I have 48GB RAM on my machine and limit the WSL2 to use 44GB of them, plus each plotting process has maximum of 6750MB RAM usage so I think what you described is not my case.

Although, thanks to the hint that you provide, I reproduced the issue and use the disk analysis utility to find out it's actually some temp files not correctly deleted during the plotting process. I'll put more details in the next thread. Thanks a lot!

**Comment by zrjaa1** [comment]
Reproduced the issue by creating 5 plot processes `chia plots create -k 32 -b 6750 -t /mnt/p -d /mnt/d -n 1 -r 4`. The 1.83 temp drive gets full really quick and I see some logs similar to `Only wrote 0 of 340764 bytes at offset 7900263522 to "/mnt/p/plot-k32-2021-04-24-16-47-872e01a27f1c03db0ac531020ac3defaa8ff40b31c60992c9c397a58000e941c.plot.table4.tmp"with length 7900266496. Error 1. Retrying in five minutes`. With an disk analysis utility called `wiztree` I get something like this:

![image](https://user-images.githubusercontent.com/9897686/115978713-49359f00-a536-11eb-8d44-f7581d26d7f7.png)

Please note that although it shows only 9.8GB occupied by `P:\$Extend\$Deleted` at the moment of the screenshot, when I first check the analysis it says 1TB in total. According to [The “\$Extend\$Deleted” directory](https://dfir.ru/2020/03/21/the-extenddeleted-directory/#:~:text=In%20the%20Linux%20world%2C%20a,files%20is%20named%20%E2%80%9Cunlink%E2%80%9D.&text=When%20the%20last%20handle%20to,closed%2C%20it's%20deleted%20as%20usual.), this indicates that a delete operation on those files has been performed but at least one process is still using them at the time so they're actually deleted later. Apprantly it goes away fast(about 10 minutes after the disk is full), but I'm wondering if it's expected behavior of plotting because 5 plots actually occupy more(at least 1.83TB used) than 5 * 256.6GB = 1.283TB of temp drive space.

**Comment by netherstar** [comment]
i have same issue

**Comment by Doom4535** [comment]
This almost sounds like a Windows garbage collection issue, I am not familiar with how the system calls work, but I wonder if the current deletes use a delayed system call that goes through the normal windows GUI trash like delete process rather than an actual *instant* delete.  Or we could just be seeing issues related to the serious IO involved with Chia plotting that delays the systems ability to removed the inodes or what every Windows uses to track actual files?

**Comment by zrjaa1** [comment]
> This almost sounds like a Windows garbage collection issue, I am not familiar with how the system calls work, but I wonder if the current deletes use a delayed system call that goes through the normal windows GUI trash like delete process rather than an actual _instant_ delete. Or we could just be seeing issues related to the serious IO involved with Chia plotting that delays the systems ability to removed the inodes or what every Windows uses to track actual files?

Yes, this is my understanding as well: it's like removing the symlink in the directory but not actually delete the file until all the links pointing to the file are released. Before that, the file are stored in the `$Extend$Deleted` folder temporarily. The weird thing is that I never see this behavior in Windows GUI, only in WSL2.

**Comment by zeroarst** [comment]
I have exactly the same issue. I have 1TB NVMe SSD ram. I ran 3 plots in parallel. Then all ate up all space. I used GUI with the same approach dose not give me the problem.

**Comment by hellofaduck** [comment]
I have same problem in LXC Ubuntu container running on Proxmox, i run 3 plotting processes in parallel on dedicated 1Tb NVME Ext4 drive and when processes goes to 2nd phase they starts to consume 333G each and stuck, because running out of space. 333 !=256G written in wiki!

**Comment by schehata** [comment]
I am having same problem, I am using the GUI, separate 1TB SATA SSD for plotting. running 1 plot at the mean time, its around 30% and used up around 500GB in temp space, As far as I understand it should just use 256GB. I am running 1 plot because I ran 2 in parallel earlier and they failed because all the SSD space was filled up by them. (the drive was empty, no old temp files or anything)

whats the problem here, any idea on how to fix it?

**Comment by wardencliffe** [comment]
Hello guys. I am not sure you have faced the same issue I was some time ago in different case, but this link can help you:
[https://superuser.com/questions/1606213/how-do-i-get-back-unused-disk-space-from-ubuntu-on-wsl2](https://superuser.com/questions/1606213/how-do-i-get-back-unused-disk-space-from-ubuntu-on-wsl2)
Also, I have noticed in my further experience that this issue is not happened when I use "host" disk instead of "wsl" once (/mnt/X instead of /dev/sbX).

**Comment by schehata** [comment]
A quick update, I was able to solve my problem by disabling the `compression` feature on my SSD. 

More info here:
https://github.com/Chia-Network/chia-blockchain/issues/3405

**Comment by leollizo** [comment]
Same problem here.

Running several 'git plots create' commands in parallel on WSL2. 

-n 3  runs fine.

-n 6  fills up the disk space and git create commands stall.

Docs say '-n' creates as many plots in sequence, so not sure how this affect this issue.

No files to be seen anywhere.  Only solution is to reformat NTFS SSD drive.
