### ISSUE TITLE
[BUG] debug info: Weight proof did not arrive in time from peer: node.chia.net

### ISSUE THREAD

**Issue by zsp00** [Chia-Network/chia-blockchain#2649]
**Describe the bug**
Weight proof did not arrive in time from peer: node.chia.net

**To Reproduce**
1.1.1 version not synced
add node  node.chia.net
debug file: Weight proof did not arrive in time from peer: node.chia.net

**Desktop (please complete the following information):**

- OS: Windows
- OS win10
- CPU: i7 10850H

**Additional context**
zhusipu123@163.com

**Comment by zsp00** [comment]
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/full_node/full_node.py
line:624
this line throw RuntimeError

I tried to read the code to solve the problem, but it was never successful

**Comment by royimous** [comment]
Have you updated to 1.1.2? I hear that is fixing the network issues some people are having.
