### ISSUE TITLE
Install FreeBSD Error: Failed to build blspy

### ISSUE THREAD

**Issue by cr0n-dist0rti0n** [Chia-Network/chia-blockchain#265]
System Install: FreeNAS jail w/ 11.3-RELEASE-p9

Command Exited with Error: 

`BUILD_VDF_CLIENT=N CXX=g++9 CC=gcc9 pip install chia-blockchain==1.0b5`

Log file attached:
[chia_install_FreeBSD.log](https://github.com/Chia-Network/chia-blockchain/files/4728573/chia_install_FreeBSD.log)

**Comment by mariano54** [comment]
https://github.com/Chia-Network/bls-signatures/pull/115
This has been merged into blspy, so it will be included in next release!

**Comment by mariano54** [comment]
Actually it's a fix for OpenBSD but not FreeBSD

**Comment by n1000** [comment]
The following 3 pull requests bring in similar changes for FreeBSD. I was able to build the command line tools on FreeBSD 11.3 and 12.1 with these additional changes:

- chia-blockchain: https://github.com/Chia-Network/chia-blockchain/pull/288
- bls-signatures / blspy: https://github.com/Chia-Network/bls-signatures/pull/116
- chiapos: https://github.com/Chia-Network/chiapos/pull/40

To build from source I had to install the following prerequisite packages using these commands:

```bash
pkg install git gmake cmake node npm py37-sqlite3-3.7.7_7
```

**Comment by hoffmang9** [comment]
Please add your build instructions to the Install section of the repo wiki under other platforms.

**Comment by n1000** [comment]
I split [this wiki page](https://github.com/Chia-Network/chia-blockchain/wiki/FreeBSD-Install) into two sections, leaving the old text under a "Method 1" heading, and adding the procedure I followed under "Method 2".

**Comment by hoffmang9** [comment]
This related change has been merged in: https://github.com/Chia-Network/bls-signatures/pull/116

**Comment by n1000** [comment]
@cr0n-dist0rti0n when you get a chance, could you try to build the latest bls-signatures code (tip of the master branch, up to and including https://github.com/Chia-Network/bls-signatures/commit/fcc10ef18106017b506c4aa29a3624558eefc8dc )? Hopefully it works now.

**Comment by cr0n-dist0rti0n** [comment]
Yes. I will try that tonight or tomorrow. Thanks a bunch!

Cheers,
Jeremy

**Comment by cr0n-dist0rti0n** [comment]
Going good but received the following error, screenshot provided as
attachment:

(venv) BSDjail# git clone git@github.com:Chia-Network/chia-blockchain.git

Cloning into 'chia-blockchain'...

Permission denied (publickey).

fatal: Could not read from remote repository.


Please make sure you have the correct access rights

and the repository exists.

(venv) BSDjail# git clone
https://github.com/Chia-Network/chia-blockchain.git

Cloning into 'chia-blockchain'...

remote: Enumerating objects: 3, done.

remote: Counting objects: 100% (3/3), done.

remote: Compressing objects: 100% (3/3), done.

remote: Total 18559 (delta 0), reused 1 (delta 0), pack-reused 18556

Receiving objects: 100% (18559/18559), 35.80 MiB | 1.36 MiB/s, done.

Resolving deltas: 100% (12998/12998), done.

(venv) BSDjail# ls

chia-blockchain known_hosts

(venv) BSDjail# mv chia-blockchain ..

(venv) BSDjail# ls

known_hosts

(venv) BSDjail# cd ..

(venv) BSDjail# ls

.cache          .cshrc          .history        .k5login        .local
    .login          .mysql_history  .profile        .python_history .ssh
        chia-blockchain wordpress

(venv) BSDjail# cd chia-blockchain

(venv) BSDjail# sh install.sh

Python version is 3.7

Collecting pip

  Using cached
https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl

Installing collected packages: pip

  Found existing installation: pip 19.2.3

    Uninstalling pip-19.2.3:

      Successfully uninstalled pip-19.2.3

Successfully installed pip-20.1.1

Collecting wheel

  Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)

Installing collected packages: wheel

Successfully installed wheel-0.34.2

Looking in indexes: https://download.chia.net/simple/

Collecting miniupnpc==2.1

  Downloading
https://download.chia.net/simple/miniupnpc/miniupnpc-2.1.tar.gz (67 kB)

     |████████████████████████████████| 67 kB 84 kB/s

  Installing build dependencies ... error

  ERROR: Command errored out with exit status 1:

   command: /root/chia-blockchain/venv/bin/python3.7
/root/chia-blockchain/venv/lib/python3.7/site-packages/pip install
--ignore-installed --no-user --prefix /tmp/pip-build-env-hy2uh2vl/overlay
--no-warn-script-location --no-binary :none: --only-binary :none: -i
https://download.chia.net/simple/ -- 'setuptools>=42' wheel

       cwd: None

  Complete output (3 lines):

  Looking in indexes: https://download.chia.net/simple/

  ERROR: Could not find a version that satisfies the requirement
setuptools>=42 (from versions: none)

  ERROR: No matching distribution found for setuptools>=42

  ----------------------------------------

ERROR: Command errored out with exit status 1:
/root/chia-blockchain/venv/bin/python3.7
/root/chia-blockchain/venv/lib/python3.7/site-packages/pip install
--ignore-installed --no-user --prefix /tmp/pip-build-env-hy2uh2vl/overlay
--no-warn-script-location --no-binary :none: --only-binary :none: -i
https://download.chia.net/simple/ -- 'setuptools>=42' wheel Check the logs
for full command output.

(venv) BSDjail#

**Comment by hoffmang9** [comment]
It looks like you tried to install master. You'll need to `git checkout dev` after `git clone`

**Comment by n1000** [comment]
I updated the wiki page for OpenBSD and FreeBSD to mention that the dev branch must be used for now (will remove the note later when the changes make it into master).

**Comment by cr0n-dist0rti0n** [comment]
Excellent. Installed like a charm. Time to get to work playing with Chia.
Thanks!

**Comment by hoffmang9** [comment]
Closing due to the release of Beta 1.8 having these fixes in it - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta8
