### ISSUE TITLE
Chia full node not synced/syncing timely 

### ISSUE THREAD

**Issue by darwinjobchia** [Chia-Network/chia-blockchain#2652]
soneone can explain how to do following steps  in windows 10?

Step 2: You might need to disable upnp in the config file (~/.chia/mainnet/config/config.yaml) or by using the cli command chia configure -upnp false. You might have multiple nodes running on the same machine, or in the same wifi network. Make sure to close all chia applications on your computer. Also check your firewall or antivirus software, which might be blocking connections.

Step 3: Try deleting your peer DB which is located at ~/.chia/mainnet/db/peer_table_node.sqlite.

Step 4: Edit ~/.chia/mainnet/config/config.yaml, search for weight_proof_timeout and increase it from 180 to 400. If that value is not there, you can add it under the full_node section.

**Comment by overdoignism** [comment]
Same here. I can't find those file on windows 10, is it a joke?

**Comment by HiKarry** [comment]
Hi man, open `C:\Users\*UserName*\.chia\mainnet\config`.

**Comment by hoffmang9** [comment]
Issues are not for tech support. Discussions and Keybase are.
