### ISSUE TITLE
Error Access Denied

### ISSUE THREAD

**Issue by danjon56** [Chia-Network/chia-blockchain#2655]
I have a plot which has reached 100% plotting, but has not been added to my farm. When checking the log, it says:

 "Could not copy "D:\\plot-k33-2021-04-23-21-45-b44c741670a8caea216cd5f17952b955e6682bcc0e1a303e137f226dd40b9429.plot.2.tmp" to "C:\\plot-k33-2021-04-23-21-45-b44c741670a8caea216cd5f17952b955e6682bcc0e1a303e137f226dd40b9429.plot.2.tmp". Error Access is denied.. Retrying in five minutes."

Does anyone know what this means, and how I can fix it? I can't delete the plot, so it is stuck there until I can fix this.

I appreciate any thoughts you may have!

**Comment by maomingyang1314** [comment]
You can try the 1.1.2 version, it is said that the synchronization problem has been updated

**Comment by hoffmang9** [comment]
You have a permissions problem in one of your directories.
