### ISSUE TITLE
[BUG] chia plot create crashes without logging any error

### ISSUE THREAD

**Issue by tsaohao** [Chia-Network/chia-blockchain#2657]
**Describe the bug**
When I was plotting using CLI, about 10 processes in parallel, some of the processes just crashed with return code **3221226505** and not print any error message.

**To Reproduce**
I wrote a script to manage multiple plotting jobs, simply to catch return code and redirect stdout and stderr to my local log file.

Usually I run 10 jobs in parallel, most jobs worked well but 1 or 2 jobs always crashed with return code `3221226505`. The running phase of crashed jobs is quite random, can be from phase 1 to phase 4, which is quite confusing. The log seems to be quite normal and not any error message can be found in it.

The plotting command is `chia.exe plots create -k 32 -b 3400 -r 2 -u 128 -t D:\ -d F:\`
D:\ is the SSD driver and F:\ is the HDD driver

To exclude the possible problem of my manage script, I tried to run the above command in 10 independent windows cmd.exe, the crashes still happened.

The problem can be reproduced in both two of my machines, and can be reproduced by chia version of 1.0.5 and 1.1.1

**Expected behavior**
All jobs don't crash or print error message before crashing.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: [Windows]
- OS Version/Flavor: [Windows10]
- CPU: [Intel Xeon E5-2680 v4 & AMD 5900x]

**Additional context**
The space of temporary driver (4T) and RAM (64G) are both large enough.

My problem is quite similar with #2440 

**Update**
I checked windows event manager and got the following log:
```
EventData 

   chia.exe 
   0.0.0.0 
   5ffec122 
   ucrtbase.dll 
   10.0.19041.789 
   2bd748bf 
   c0000409 
   000000000007286e 
   2d2c 
   01d739a9a8c099a9 
   C:\Users\Tsaoh\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon\chia.exe 
   C:\WINDOWS\System32\ucrtbase.dll 
   6c59f35a-7305-454d-bd93-88b7aec03e00 
```
Does this information help?

**Comment by 2crazydr0ne** [comment]
I have experienced the exact same issue. I think it happens if there is too much load on the processor, because I had more than enough RAM and tempspace. The EventData is exactly the same, so pretty sure it is a bug.

This bug should be open still... Please reopen it, unless there is either a solution or resolution to it.

Windows 10 Pro x64 19041.985
temp was an Gigabyte nvme m.2 drive
i7-4790S/32G

<script>
  
    function Toggle(node)
    {
      if (!window.fullyLoaded) return;

      // Expand the branch?
      if (node.nextSibling.style.display == 'none')
      {
        // Change the sign from "+" to "-".
        var tBodyNode = node.childNodes[0];
        var trNode = tBodyNode.childNodes[0];
        var tdNode = trNode.childNodes[0];
        var bNode = tdNode.childNodes[0];
        var textNode = bNode.childNodes[0];
        if (textNode.nodeType == 3 /* Node.TEXT_NODE */) {
          var s = textNode.data;
          if (s.length > 0 && s.charAt(0) == '+') {
            textNode.data = '-' + s.substring(1, s.length);
          }
        }

        // show the branch
        node.nextSibling.style.display = '';
      }
      else // Collapse the branch
      {
        // Change the sign from "-" to "+".
        var tBodyNode = node.childNodes[0];
        var trNode = tBodyNode.childNodes[0];
        var tdNode = trNode.childNodes[0];
        var bNode = tdNode.childNodes[0];
        var textNode = bNode.childNodes[0];
        if (textNode.nodeType == 3 /* Node.TEXT_NODE */) {
          var s = textNode.data;
          if (s.length > 0 && s.charAt(0) == '-') {
            textNode.data = '+' + s.substring(1, s.length);
          }
        }

        // hide the branch
        node.nextSibling.style.display = 'none';
      }
    }

    // Toggle "System" element by default so that it's default status is to hide its children
    function ToggleSystemElement()
    {
      var body = document.getElementById("body");
      var anchor = body.getElementsByTagName("table")[0];
      Toggle(anchor);
    }

    // If binary data is present in event XML, show it in friendly form.
    function ProcessBinaryData(binaryString, binaryDataCaption, wordsFormatString, bytesFormatString, normalFont, fixedWidthFont)
    {
      var bodyNode = document.getElementById("body");

      // Add a <hr> at the end of the HTML body.
      bodyNode.appendChild(document.createElement("hr"));      

      // This paragraph (p element) is the "Binary data:" literal string.
      var p = document.createElement("p");
      p.style.fontFamily = normalFont;
      var b = document.createElement("b");
      b.appendChild(document.createTextNode(binaryDataCaption));
      p.appendChild(b);
      p.appendChild(document.createElement("br"));
      bodyNode.appendChild(p);

      //
      // Show binary data in Words format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(wordsFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      var i = 0;
      var j = 0;
      var s, tempS;
      var translatedString;
      var charCode;
      var byte1, byte2;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte; 4 characters for a word.
      while (i < binaryString.length) {

        s = (i / 2).toString(16);    // To hex representation.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // DWords representation is simply a rearrangement of the original binaryString
        // For example, from:
        // 
        // 0000000002005600000000000f000540
        //
        // (which is 00 00 00 00 02 00 56 00 00 00 00 00 0f 00 05 40).
        //
        // to:
        //
        // 0000: 00000000 00560002 00000000 4005000f
        // 8 words per line, 4 DWords per line.
        for (j = 0; j < 4; j++) {
          s += binaryString.substring(i + 6, i + 8);
          s += binaryString.substring(i + 4, i + 6);
          s += binaryString.substring(i + 2, i + 4);
          s += binaryString.substring(i, i + 2) + " ";
          i += 8;
        }

        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);

      //
      // Show binary data in bytes format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(bytesFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      i = 0;
      j = 0;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte.
      while (i < binaryString.length) {
        translatedString = "";
        // 2 characters in binaryString to form a byte
        s = (i / 2).toString(16);   // to hex representation.

        // Prefix with '0' until its length is 4.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // Show 8 bytes per line
        for (j = 0; j < 8; j++) {
          tempS = binaryString.substring(i, i + 2); // 2 for 1 byte
          i += 2;
          s += tempS + " ";

          // Treat tempS as hex integer
          charCode = parseInt(tempS, 16);
          if (charCode < 32) {
            translatedString += ".";
          } else {
            translatedString += String.fromCharCode(charCode);
          }
        }

        while (s.length < 32) {
          s += " ";
        }
        s += translatedString;
        
        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);
    }
  
  </script>


<div>

chia.exe
--




&nbsp; | &nbsp; | &nbsp; | 0.0.0.0
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | 5ffec122
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | ucrtbase.dll
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | 10.0.19041.789
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | 2bd748bf
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | c0000409
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | 000000000007286e
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | 60d8
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | 01d750ce8abee701
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | C:\Users\peter\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | C:\WINDOWS\System32\ucrtbase.dll
-- | -- | -- | --




&nbsp; | &nbsp; | &nbsp; | 59462498-b9a1-4bf5-bc10-167c6a01cdb4
-- | -- | -- | --


</div>

**Comment by tsaohao** [comment]
> I have experienced the exact same issue. I think it happens if there is too much load on the processor, because I had more than enough RAM and tempspace. The EventData is exactly the same, so pretty sure it is a bug.
> 
> This bug should be open still... Please reopen it, unless there is either a solution or resolution to it.
> 
> Windows 10 Pro x64 19041.985
> temp was an Gigabyte nvme m.2 drive
> i7-4790S/32G
> 
> Application Error
> EventData:
> chia.exe
> 0.0.0.0
> 5ffec122
> ucrtbase.dll
> 10.0.19041.789
> 2bd748bf
> c0000409
> 000000000007286e
> 60d8
> 01d750ce8abee701
> C:\Users\peter\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe
> C:\WINDOWS\System32\ucrtbase.dll
> 59462498-b9a1-4bf5-bc10-167c6a01cdb4

My problem was not a bug of Chia, but a bug of my manage script.

Specifically, I wrote a python script to watch plotting process using package `psutil`. There is a bug of this package when trying to gather opened file of a process, which will cause the process crash.

So please check if there is any 3rd-party software may cause the crash. (can be your own script or pool software)

Chia.exe works fine itself.
