### ISSUE TITLE
Feature Request: Symlink to 'current' version in Windows

### ISSUE THREAD

**Issue by TheFiZi** [Chia-Network/chia-blockchain#2661]
I have some scripts that call `C:\Users\<USERNAME>\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon\chia.exe` to get some information and send notifications.

Every time there is an update to Chia I have to manually updated my scripts.

Could your installer create a symlink in `C:\Users\<USERNAME>\AppData\Local\chia-blockchain\` called `current` that points to `.\app-<CURRENT VERSION>`

Then those of us with scripts can simply called `C:\Users\<USERNAME>\AppData\Local\chia-blockchain\current\resources\app.asar.unpacked\daemon\chia.exe` in our scripts regardless of what version is installed.

This would also be useful for other operating systems as well

**Comment by hoffmang9** [comment]
I have looked into this once as we hate the numbering too but there is no obvious way to fix it soon. We plan to switch installers and that may fix it. We are aware.

**Comment by TheFiZi** [comment]
For anyone looking for a work around for PowerShell in the short term:

```powershell
$chiaVersion = $(Get-ChildItem C:\Users\<USERNAME>\AppData\Local\chia-blockchain\ |Where-Object -Filter { $_.Name -like "app-*" }).Name
$chaiCommand = "C:\Users\<USERNAME>\AppData\Local\chia-blockchain\$chiaVersion\resources\app.asar.unpacked\daemon\chia.exe farm summary"
$chiaFarmSummary = Invoke-Expression $chaiCommand
```

In this example replace `<USERNAME>`  with the username you have Chia installed under and `farm summary` at the end of `$chaiCommand` with whatever you want.

**Comment by Ron-ski** [comment]
Having the app version in the file path is a right pain, multiple things need updating every time.

OS Firewall rules for port 8444
Any scripts that we use need updating (multiple scripts here)
Any plot managers that we use need updating

@hoffmang9  Glad to hear you plan on switch installers, but that was over a month ago.
