### ISSUE TITLE
Chia version 1.1.1 crashed when running several parallel plotting 

### ISSUE THREAD

**Issue by Tiger-Stone** [Chia-Network/chia-blockchain#2664]
Chia Window 10 version 1.1.1 crashed when running several parallel plotting.

There was not error message after crashing. 
But it seems that that some Chia processes are stilling running in the background and the disks are busying. Not sure I should wait and see if the plotting plan could be finished by the Chia background processes.

![image](https://user-images.githubusercontent.com/83153410/115981890-14096b00-a58f-11eb-8e34-6144d46e4f6e.png)

**Comment by psun888** [comment]
I have a dozen of servers running parallel plotting with version 1.1.1, every server's Chia UI crashes after running a little more than three hours. About 70% of plotting processes continues to the end, and 30% plotting processes die with the Chia UI crash. The memory leak of Chia UI seems very serious. Plotting from command line might be better for now.

**Comment by hoffmang9** [comment]
We isolated this issue and are working on a fix for 1.1.3.

**Comment by wjblanke** [comment]
Please try 1.1.2. It may help as well. Let us know if this works for you.

**Comment by Tiger-Stone** [comment]
Many thanks for the replies. I am using 1.1.2 now, it seems works fine without crashing but seems response slightly slower than the previous versions.
