### ISSUE TITLE
[BUG] No sync after internet connection restored

### ISSUE THREAD

**Issue by elxander** [Chia-Network/chia-blockchain#2665]
Status Not Synced 
Connection Status Connected

will stay forever.

**To Reproduce**

Pull out the ethernet cable. (Not necessary, also happens on internet connection problems)
Insert it back after some time.
Status always shows connected to 127.0.0.1 

Also, even after restarting the application does not show any activity in sync for a long time

**Expected behavior**

Should try to detect if the internet connection restored and continue syncing.
I believe it should show more detailed and frequently updated information

**Desktop (please complete the following information):**

- OS: Win 10

**Comment by qfishpear** [comment]
same here, have been waiting for hours

**Comment by overdoignism** [comment]
Same here. please fix it asap.

**Comment by hbroer** [comment]
I was still on 1.0.5 but shows "not synced" and "connected" too this morning. I upgraded to 1.1.2 and it is still the same. No connections.

Last Block is 181608 without timestamp. Last Block with timestamp is 181606 at 04/25/2021 5:18:23 AM.

**Comment by hoffmang9** [comment]
For the people piling in here, upgrade to 1.1.2. For the original issue, I am leaving it open so we can confirm it or not.

**Comment by zewort** [comment]
What happen with synchronization? Sometimes i see "not synced" in the full nodes (connection status: connected always) and i cant restart chia because im plotting and i dont want lose this.

So, finally, i close chia, restart my PC, delete temporal files, and restart chia...

Not synced... wait 2min...5min...nothing, and restart Chia again... 2 or 3 times the same problem, and maybe in 4th i try to open chia and "synced" in 1 second! ¿what?

PD: 8444 port is open / Win 10 / Chia 1.1.2

**Comment by elxander** [comment]
1.1.2 no changes

![chia](https://user-images.githubusercontent.com/83152951/116053944-27fbbc80-a6b6-11eb-9e5b-f4915c53e5ab.jpg)

**Comment by hbroer** [comment]
This morning again no connections and last timestamp is 04/30/2021 5:15:07 AM. Now it is 8:47 AM (UTC +2). Network is fine, everything else is working (also running a miner on CPU and one on GPU). Connection Status is "connected". Version 1.1.2 (on Windows 10).

**Comment by elxander** [comment]
The problem is clearly visible when the ethernet connection is LAN, and the internet is over a USB modem.
Shows syncing but no progress over a long period. Required several restarts to run it again
![chia1](https://user-images.githubusercontent.com/83152951/116978985-640acf00-acff-11eb-9060-ed9d2c5b2492.jpg)

**Comment by elxander** [comment]
1.1.4 - unsync for 2-3 hours is still common
![chiasync](https://user-images.githubusercontent.com/83152951/117237801-a39ffb00-ae66-11eb-92b2-55065737498d.jpg)

**Comment by jurkov** [comment]
I think this is happening because of a missing retry to connect to the introducer after a forced disconnect by the local internet provider. After a disconnect of all connections on the internet it stops. See #3903

**Comment by elxander** [comment]
1.1.5 no changes

as for me waiting for 6 hours for sync is inappropriate

![chia1](https://user-images.githubusercontent.com/83152951/117611872-36120880-b19f-11eb-9de3-747c23315b22.jpg)
![chia2](https://user-images.githubusercontent.com/83152951/117611891-3e6a4380-b19f-11eb-9863-dfa2cc1e3beb.jpg)

**Comment by elxander** [comment]
Breaking record. Usually,  it took about 2 hours, now it seems it is going to be a day to resync.
![chia day](https://user-images.githubusercontent.com/83152951/118354402-e28c2a00-b5a5-11eb-996a-aac9f1d73e24.jpg)

**Comment by jurkov** [comment]
I am able to get it working again with a restart of the node. I use `chia start -r node` on ubuntu. After some minutes the node is syncing again.
