### ISSUE TITLE
Using docker to build a farmer, a wallet will be created automatically after each restart.

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#2666]

**Comment by KickCellarDoor** [comment]
Check -e keys=".." option for Docker, make sure it is not "generate"

**Comment by qian-fei** [comment]
> Check -e keys=".." option for Docker, make sure it is not "generate"

Does this key refer to wallet public keys？

**Comment by KickCellarDoor** [comment]
@qian-fei It should be the path of the key file in the docker container.

**Comment by KickCellarDoor** [comment]
Check this [instruction](https://github.com/orgs/Chia-Network/packages/container/package/chia) .
