### ISSUE TITLE
[BUG] Plots done and copied, but are stuck at 100% for hours

### ISSUE THREAD

**Issue by modsoft** [Chia-Network/chia-blockchain#2674]
**Describe the bug**
Windows, GUI
Chia 1.1.0
Plots appear complete, but get stuck in 100%. Log shows phase 4 complete, and "final size: xx".
The tmp files appear to be copied to the plot directory. Files appear complete and correct size. However, the tmp files are not deleted and the files in the final dir are not renamed.
I have to shut down the node, rename the .tmp files to .plot, and then delete the temp files.
If I return to my PC and start clicking around the app, or wait long enough, the plots will eventually get moved to farm. I feel it takes way too long to happen for some reason.

this was all happening automatically on the last software version.
Any tips?

**Expected behavior**
Plots complete, the app moves the tmp file to the final dir, renames, deletes tmp file, and the plot is complete.

**Screenshots**
![chia_plot_complete_issue](https://user-images.githubusercontent.com/1141446/115984668-2e2a5580-a55d-11eb-8576-20e0ec721b16.jpg)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: AMD Ryzen 9 3900x

**Comment by yuk320** [comment]
It depends on the write speed of your final disk,
For me, 200mib/s takes more than 500 seconds

**Comment by Falacio** [comment]
I had same issue as @modsoft with version 1.1.0. Stuck at 100% for hours, with log showing the same he shows. I tried same solution (deleting temp file and renaming the one on Plot folder to .plot) and it worked. 
When restarting Node, Plot was added to farm, but wallet had to synchronize like 15k or 20k blocks (still syncing). Maybe because I had to kill the process the blockchain wasn't stored?

I'm using Windows 10 on an i7-6820HK @2.70Ghz with 16 GB de RAM

**Comment by PresidentCake** [comment]
I encountered a similar situation last time. However, when the application is stuck, the suffixes of my two files are the same,  but the application does not respond.

**Comment by yuk320** [comment]
> I encountered a similar situation last time. However, when the application is stuck, the suffixes of my two files are the same, but the application does not respond.

You can repair it in another way, and then copy a copy from the temporary disk to the target disk. After the full copy, rename it

**Comment by hoffmang9** [comment]
Tech support should be in Discussions or Keybase.
