### ISSUE TITLE
Plotting get much slower

### ISSUE THREAD

**Issue by tim-ma-1987** [Chia-Network/chia-blockchain#2675]
almost 6-7hours to make a Plot file in version 1.0.3
while it takes almost 16hours when updated to 1.1.1

**Comment by ilylx** [comment]
Maybe your ssd is more slower

**Comment by ldjdsc** [comment]
> Maybe your ssd is more slower

no set -b 10000 ,then will use swap,so  Plotting get much slower.
![image](https://user-images.githubusercontent.com/20770432/115988658-51044a80-a5ed-11eb-8e0b-1ff1c8370ab2.png)

**Comment by tim-ma-1987** [comment]
> Maybe your ssd is more slower

ssd is a new 3600mbps

**Comment by tim-ma-1987** [comment]
> > Maybe your ssd is more slower
> 
> set -b 10000 ,then will use swap,so Plotting get much slower.
> ![image](https://user-images.githubusercontent.com/20770432/115988658-51044a80-a5ed-11eb-8e0b-1ff1c8370ab2.png)
![image](https://user-images.githubusercontent.com/78263184/115991128-a6deef80-a5f9-11eb-804a-d78c17e37ce2.png)
setting like this

**Comment by sansky33** [comment]
I couldn't agree with you anymore

**Comment by hoffmang9** [comment]
Issues are not for tech support.

**Comment by ldjdsc** [comment]
> Issues are not for tech support.

But 1.0.5 do not has this problem.

**Comment by hoffmang9** [comment]
There was no change to the plotter between those versions.

**Comment by ldjdsc** [comment]
> > Maybe your ssd is more slower
> 
> set -b 10000 ,then will use swap,so Plotting get much slower.
> ![image](https://user-images.githubusercontent.com/20770432/115988658-51044a80-a5ed-11eb-8e0b-1ff1c8370ab2.png)
> ![image](https://user-images.githubusercontent.com/78263184/115991128-a6deef80-a5f9-11eb-804a-d78c17e37ce2.png)
> setting like this

恢复默认配置试试，应该会会在8.9个小时左右。

**Comment by ldjdsc** [comment]
> There was no change to the plotter between those versions.

thanks. I have 1000G memery,48 threads ,it is enough. result: 
cmd1:-b 10000 -r 4 -u 64 use those settings ,10 parallels will use 16hours (1.0.5 use 6-7hours)
cmd2:-b 4608 -r 2 -u 128 use those settings ,10 parallels will use 9hours  (1.0.5 use 8hours)
