### ISSUE TITLE
[BUG] Is this possible?

### ISSUE THREAD

**Issue by ilylx** [Chia-Network/chia-blockchain#2676]
https://www.chiaexplorer.com/blockchain/address/xch1f0ryxk6qn096hefcwrdwpuph2hm24w69jnzezhkfswk0z2jar7aq5zzpfj

This address "Won 26.98% of the last 10,000 blocks"
Now whole network space is 650PiB, so this address has about 175PiB ?

**Comment by overdoignism** [comment]
should be hpool.

**Comment by yuk320** [comment]
actually,this pool has 269.87 PiB

**Comment by PresidentCake** [comment]
and increasing so fast

**Comment by PresidentCake** [comment]
but it is not a bug, that pool is managed by an existing company

**Comment by fabitom** [comment]
But self-pooling is only possible for now, right ? or I miss something...

**Comment by overdoignism** [comment]
> But self-pooling is only possible for now, right ? or I miss something...

So the hpool tell user to send private key for them. 

The chia pool protocol is really need to implement ASAP.

**Comment by Last-Airbender** [comment]
Need a clarification from the technical team

**Comment by PresidentCake** [comment]
Because there is no officially certified pool, it is normal for many individuals to join the only hpool

**Comment by hoffmang9** [comment]
It is a hacked together pool of 6000 plus farmers.
