### ISSUE TITLE
Last Attempted Proof once every half hour instead of once every 10 seconds

### ISSUE THREAD

**Issue by KotSk8er** [Chia-Network/chia-blockchain#2678]
Your blockchain is not working. The proof tests don't come. But total network spase is update. And this is not the first time. Your software is shit.
<a href="https://ibb.co/Rbc6D5Q"><img src="https://i.ibb.co/nmj1LWQ/2021-4-25-12-26-4.png" alt="2021-4-25-12-26-4" border="0"></a>

-

**Comment by hoffmang9** [comment]
I'm sorry you don't like our free beer.
