### ISSUE TITLE
[BUG] Chia reload can't connect page And daemon.exe use ram 85G?

### ISSUE THREAD

**Issue by JimRK** [Chia-Network/chia-blockchain#2679]
Chia gui can't connect 
![image](https://user-images.githubusercontent.com/10102325/115989023-befd4180-a5ee-11eb-9b7a-5cfc6795413e.png)
websockets error(?

daemon.exe use ram  85G (?
![image](https://user-images.githubusercontent.com/10102325/115989096-3337e500-a5ef-11eb-87dd-38959d599b0f.png)

- OS: [Windows Server]
- OS Version/Flavor: [2019/1809]
- CPU: [E5-2630v2*2]

Sorry my english is not very good

**Comment by royimous** [comment]
Do you have port 8444 forwarded? If not, look at the FAQ to get guidance on that.

**Comment by jaedongjuly** [comment]
where is the log file？ 
I dont find the file path?

**Comment by JimRK** [comment]
> Do you have port 8444 forwarded? If not, look at the FAQ to get guidance on that.

Chia.exe Restart regular

**Comment by JimRK** [comment]
> where is the log file？
> I dont find the file path?
> 
> I have same problem
path : C:\user\[your username ]\.chia\mainnet\log\debug.log

I Restart Can regular
