### ISSUE TITLE
[BUG] Don't connect

### ISSUE THREAD

**Issue by SeruousMax** [Chia-Network/chia-blockchain#2682]
Version 1.1.2
i have 2 computers. First - connect to chia, and second - don't after update to 1.1.1. Today i'am update to version 1.1.2. Sometimes show synchronization and after - not connected.
I am wait about 1 day for connect.
In First machine i wait connection about 6 hours, synchronization is fast butlung time show don't connect

**Comment by maomingyang1314** [comment]
Under a network, there can only be one device for mining

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-should-i-not-run-more-than-one-node-on-a-home-network-and-whats-this-about-upnp
