### ISSUE TITLE
Plotting fail

### ISSUE THREAD

**Issue by ManuelP276** [Chia-Network/chia-blockchain#2683]
Hello,
I get "Runtime Error: unknown exception" at 1 percent.

**Comment by garyhkirk** [comment]
Please give a more detailed explanation. There are many factors that can cause issues. System specifications, Operation System, Chia Version, Dirves being plotted to and destination drive. Also, if you still have the log, it would be helpful to include the lines above the error as they may give more information. If you don't have the log then please try another plot and use that if the same error occurs.

**Comment by SrMalta** [comment]
my plot is showing on the observation screen "loading" and does not start, does anyone know what it might be?
