### ISSUE TITLE
[BUG] Not Synced

### ISSUE THREAD

**Issue by stratis123** [Chia-Network/chia-blockchain#2684]
Fresh install here. 
Tried everything on google, from yesterday, still have this issue. Wallet and node is not syncing.
Tried 1.05, 1.1.0 ,1.1.1 ,1.1.2 

I did portforward 8444 in my router, disabled AV-Firewall, tried manually ''18.168.101.107:8444'' still have not a single connection in the GUI.
I did restart several times also.
Windows 10 running on Ryzen 5 1600X

![Annotation 2021-04-25 150833](https://user-images.githubusercontent.com/83167136/115992840-61f69100-a5d8-11eb-9b63-c4e87e5daaaa.png)
![Annotation 2021-04-25 150736](https://user-images.githubusercontent.com/83167136/115992843-6753db80-a5d8-11eb-8413-7f7b74cf5fba.png)

**Comment by sansky33** [comment]
bad mood :<

**Comment by stratis123** [comment]
Sorry, did not sleep at all! :)

**Comment by keliew** [comment]
Tried a completely fresh installation?

I once delete the peer database, and then it started to work. Same for the wallet database.

**Comment by stratis123** [comment]
> 
> 
> Tried a completely fresh installation?
> 
> I once delete the peer database, and then it started to work. Same for the wallet database.

Yeah, everytime i was trying different releases, first i uninstalled and then removed alla leftovers in the appdata...RegKeys also.
