### ISSUE TITLE
Not Synced is going to be the biggest problem！

### ISSUE THREAD

**Issue by sansky33** [Chia-Network/chia-blockchain#2687]
To be honest, this has affected my confidence in Chia. I'm getting bored

**Comment by lvcivs** [comment]
Try version 1.1.2, it has a fix for syncing.

**Comment by rawbar** [comment]
the fix only works if everyone else installs it

**Comment by royimous** [comment]
> the fix only has the potential to work if everyone else installs it. it fixes their nodes from disconnecting you.

I don't get the point of you saying this? As time goes on of course more people are going to install the updated version.

**Comment by hoffmang9** [comment]
Thanks @royimous !
