### ISSUE TITLE
[BUG]: Synced more than i should

### ISSUE THREAD

**Issue by tawfik741** [Chia-Network/chia-blockchain#2688]
**Describe the bug**
I am syncing 28864/179811 which is very wierd

**To Reproduce**

1. create a plot
2. lose internet connection for some hours
3. get internet connection again

**Expected behavior**
syncing just what needs to be synced

**Screenshots**
![image](https://user-images.githubusercontent.com/37041878/115993431-9f542200-a5ca-11eb-94d9-c842388b1c4e.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- OS Version/Flavor: Windows 10
- CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz

**Additional context**
I two first plots yesterday and forgot  to put my pc on charge before going to sleep. i opened my pc this morning and after some time syncing got this error

**Comment by tawfik741** [comment]
now it's  30304/179811

**Comment by tawfik741** [comment]
i guess it's because it's temporary data, i need to read the paper ASAP

**Comment by tawfik741** [comment]
and now it's not synced

**Comment by lvcivs** [comment]
It might be easier to understand if you put an apostrophe after three digits from the right: syncing 28'864/179'811.

It just means that you are in the process of syncing the whole blockchain and it is taking a long time.

**Comment by tawfik741** [comment]
@lvcivs since syncing means downloading the whole blockchain, can i just copy what i downloaded to a new directory when adding a new node?

**Comment by tawfik741** [comment]
it would save me time re-downloading all the blockchain from the internet
