### ISSUE TITLE
[BUG] Нет синхронизации. 

### ISSUE THREAD

**Issue by ESKCOBAR** [Chia-Network/chia-blockchain#2689]
Нет синхронизации, почему в чём проблема?
![Нет синхранизацииjpg](https://user-images.githubusercontent.com/83168230/115993563-d804f300-a5ec-11eb-801a-c55ad304efd0.jpg)

**Comment by hoffmang9** [comment]
Did you upgrade to 1.1.2 which was released to fix syncing problems? 

Вы обновились до версии 1.1.2, которая была выпущена для устранения проблем с синхронизацией?

**Comment by kosyar** [comment]
у меня тоже самое на версии 1.1.2 
same problem in 1.1.2

**Comment by ESKCOBAR** [comment]
> Вы обновились до версии 1.1.2, которая была выпущена для устранения проблем с синхронизацией?
> 
> Вы обновились до версии 1.1.2, которая была выпущена для устранения проблем с синхронизацией?

Добрый день, да обновил до версии 1.1.2,  и всё та же проблема, удивительно ведь всё до этого работало идеально, помогите разобрать, за ранее благодарен.
![Нет синхранизацииjpg](https://user-images.githubusercontent.com/83168230/116041874-354d8280-a687-11eb-8aa0-06f2f7167c65.jpg)

**Comment by kosyar** [comment]
> > Вы обновились до версии 1.1.2, которая была выпущена для устранения проблем с синхронизацией?
> > Вы обновились до версии 1.1.2, которая была выпущена для устранения проблем с синхронизацией?
> 
> Добрый день, да обновил до версии 1.1.2, и всё та же проблема, удивительно ведь всё до этого работало идеально, помогите разобрать, за ранее благодарен.
> ![Нет синхранизацииjpg](https://user-images.githubusercontent.com/83168230/116041874-354d8280-a687-11eb-8aa0-06f2f7167c65.jpg)

у меня синхронизаниця прошла но гдето чеса через 2-3 так это скорей всего сеть штормит

**Comment by ESKCOBAR** [comment]
Я жду уже более 5 часов после обновления, синхронизация стоит всё на том же месте.

**Comment by kosyar** [comment]
> Я жду уже более 5 часов после обновления, синхронизация стоит всё на том же месте.

перезапусти комп и попробуй еше. мне так помогло

**Comment by RivIrk** [comment]
Здравствуйте, примерно в это же время пропала синхронизация. До сих пор не появилась, как быть? В фаерволе 8444 открыл... Прописываю адреса что в гайде - ничего не происходит и не добавляется.. Помогите плз.. 50 плотов простаивают..

**Comment by savelkasolik** [comment]
Здраствуйте таже проблема все перепробовал , синхронизации нет что делать плоты стоят

**Comment by RivIrk** [comment]
> Здраствуйте таже проблема все перепробовал , синхронизации нет что делать плоты стоят

Я нашёл причину, мой провайдер блокирует..

**Comment by savelkasolik** [comment]
И как сделать чтобы они разблокировали, и что конкретно блокирует какой провайдер?

**Comment by ESKCOBAR** [comment]
вышла новая версия 1.1.3 установите её перезагрузите компьютер.

**Comment by savelkasolik** [comment]
> вышла новая версия 1.1.3, установите её перезагрузите компьютер.

Версия приложения стоит самая последняя 1.1.3

**Comment by ramzai23rus** [comment]
> > Здраствуйте таже проблема все перепробовал , синхронизации нет что делать плоты стоят
> 
> Я нашёл причину, мой провайдер блокирует..

порты ?
У меня через мобильный интернет работает, а через домашний не синхронизируется. Думаю что настройки роутера или провайдера...

**Comment by extraangell** [comment]
версия 1.1.5 чет зависла перезагрузил комп синхронизация пошла заново,че за нах? если каждый раз сутками синхронизировать то что намайнишь? исправьте пожалуста ато какойто геморой получается!

**Comment by extraangell** [comment]
вроде пока норм работает)

**Comment by extraangell** [comment]
не синхронизирован уже больше часа висит,перезагрузка не помогла(

**Comment by extraangell** [comment]
обновился и заработало,я так понял в старых версиях синхронизацию выключают,мож в целях безопасности хз.
