### ISSUE TITLE
changing from 2 nodes to 1 on same network

### ISSUE THREAD

**Issue by drewmullen** [Chia-Network/chia-blockchain#2691]
I started farming with 2 machines with 2 unique private keys. One was for me, one for a friend; and it worked fine on 1.0.5. what are our options for combining to a single node with multiple harvesters? Initially my buddy was going to manage his own hardware but after doing this a few days, we decided it would be best if I managed it

is it possible to migrate the plots from 1 key to the other so we can combine?

We'd like to move to 1 node / multi harvester on the same network without losing the plots from the 2nd key we used initially
- can I import both keys to a node and continue as normal?
- can we migrate existing plots from 1 key to the other?

**Comment by hoffmang9** [comment]
Issues aren't for technical questions. Discussions and Keybase are.
