### ISSUE TITLE
How to check the integrity of plot files, and make sure it is not corrupted due to some reason?

### ISSUE THREAD

**Issue by chinaxry** [Chia-Network/chia-blockchain#2694]
Hi everyone, I would like to know how to determine if the plot files were corrupted or incomplete because of Disk I/O error, unawareness interruption of final copy stage or any other reason? Is there any mechanism like hash/checksum to do this job?
  I know there is a command `chia plots check`, but does it take care of this? Seems that this command won't go through the whole plot file.
  Also what is the file structure of the plot file? Any help is welcome, thank you!

**Comment by lvcivs** [comment]
You use `chia plots check`: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#how-do-i-know-if-my-plots-are-ok

**Comment by hoffmang9** [comment]
Plot errors are almost always caused by unstable RAM
