### ISSUE TITLE
Does the node need to be online to get the reward?

### ISSUE THREAD

**Issue by chinaxry** [Chia-Network/chia-blockchain#2695]
If I go offline for several days, will the potential rewards for any previously generated plot files during these days still belong to me and show up in my wallet when I'm online again? If not, although I'm online, there should be an allowing time span for the node to check if any of the plot files can get the reward and then submit something to the chain, what's the detail of this process? Any help is welcome, thank you!

**Comment by lvcivs** [comment]
You cannot win any rewards while your node is offline. So you will miss out on those rewards. 

Yes, there is a certain time that your farmer has to check whether any of your plots have a winning proof. It's like 30 seconds or something like that.
