### ISSUE TITLE
The number of barrels  //  桶的数量问题

### ISSUE THREAD

**Issue by A0000rlo** [Chia-Network/chia-blockchain#2696]
Can I only set the number of buckets to 128? Can't you set it to 256,512 or something like that? What errors do I throw in, and can I be more efficient by setting a larger multiple? What does it take up more？
//我只能设置桶的数量为128吗？不能设置为256，512之类的吗？会引发什么错误，设置大倍数能让我的效率更高吗？它会占用更多的什么？

**Comment by keliew** [comment]
Those are already explained...
https://github.com/Chia-Network/chia-blockchain/wiki/Beginners-Guide#create-a-plot
https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create

**Comment by HectorChow** [comment]
-u [number of buckets]: More buckets require less RAM but more random seeks to disk. With spinning disks you want less buckets and with NVMe more buckets. There is no significant benefit from using smaller buckets - just use 128.
good.
