### ISSUE TITLE
[BUG]my plot is showing on the observation screen "loading" 

### ISSUE THREAD

**Issue by SrMalta** [Chia-Network/chia-blockchain#2697]
my plot is showing on the observation screen "loading" and does not start, does anyone know what it might be?

**Comment by lvcivs** [comment]
Your question is a little hard to understand for me. Could you perhaps explain it more clearly, or provide a screenshot?

**Comment by SrMalta** [comment]
Before I was able to plot, now it doesn't come out of the load.

https://uploaddeimagens.com.br/imagens/NG6m9h4

**Comment by SrMalta** [comment]
<a href="https://ibb.co/YBVjNpp"><img src="https://i.ibb.co/WvRKHgg/chia-loadin.jpg" alt="chia-loadin" border="0"></a>
