### ISSUE TITLE
[BUG] Daemon.exe use unexpected RAM on Win GUI

### ISSUE THREAD

**Issue by BassLineHUN** [Chia-Network/chia-blockchain#2704]
**Describe the bug**
After 20% parallel plotting use Win GUI the daemon.exe starting to use many RAM, which unexpected.

**To Reproduce**
- Run parallel plots and see the RAM usage.

**Expected behavior**
We set the RAM usage for every Plots, but daemon.exe use much more!

**Screenshots**

![image](https://user-images.githubusercontent.com/6533334/115997361-1c8b9100-a5e3-11eb-9932-6f8c2e4c5e13.png)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Windows7
- CPU: Xeon X5680
- RAM:  24Gb

**Comment by BassLineHUN** [comment]
Some additional info:

Chia version: 1.1.2
In phase 2 the daemon.exe starting to use more RAM.

![image](https://user-images.githubusercontent.com/6533334/116001837-ee17b100-a5f6-11eb-8bbe-d6854026d0a2.png)

**Comment by hoffmang9** [comment]
We figured out why this is happening over the weekend and are working on a fix.

**Comment by BassLineHUN** [comment]
Some more info:

After starting to phase 3 it reverts back to the first stage amount.

So:
Phase 1 ~ 4Gb
Phase 2 ~ 9Gb
Phase 3 ~ 4Gb

![image](https://user-images.githubusercontent.com/6533334/116005860-1dcfb480-a609-11eb-9d93-92d4d9e70055.png)

**Comment by aqk** [comment]
This issue now has a patch waiting to be integrated between the daemon and GUI.

**Comment by hoffmang9** [comment]
Closing as fixed.
