### ISSUE TITLE
Not Sunced and farm not available

### ISSUE THREAD

**Issue by tanbosin** [Chia-Network/chia-blockchain#2707]
I installed the Chia manager yesterday. After 20 hours of processing he created the file but was unable to synchronize.
The blocks are updated.
Plots appear as not available.
The farm appears as unavailable.
![chia3](https://user-images.githubusercontent.com/83174290/115998450-462dc380-a5b5-11eb-8084-f4b5b4ab29f2.png)
![chia4](https://user-images.githubusercontent.com/83174290/115998452-475ef080-a5b5-11eb-9367-bb9f1b1c5168.png)
![chia1](https://user-images.githubusercontent.com/83174290/115998453-47f78700-a5b5-11eb-91dc-6291572aaa8b.png)
![chia2](https://user-images.githubusercontent.com/83174290/115998454-47f78700-a5b5-11eb-9d34-4e9f2b8841cc.png)

**Comment by lvcivs** [comment]
You are not synced yet, as you can see in the status field. Just leave it running and it should eventually get synced.

If you have problems connecting to peers, read this: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
