### ISSUE TITLE
if I don't open my 8444 port I won't have a chance to win?

### ISSUE THREAD

**Issue by muthubaby** [Chia-Network/chia-blockchain#2708]
as title

**Comment by lvcivs** [comment]
You can win just fine withoutt opening that. As long as you get enough connected peers, you are fine.

**Comment by hoffmang9** [comment]
Thanks for all your help @lvcivs

**Comment by jonny77** [comment]
> You can win just fine without opening the port. As long as you get enough connected peers, you are fine.
so ,  do you mean that  more  peers   i connected to , the more chance to win the chia ? how to connect more peers?
