### ISSUE TITLE
Installation has failed

### ISSUE THREAD

**Issue by tryingtochia** [Chia-Network/chia-blockchain#2714]
I uninstalled chia from my computer and tried to reinstall and installation fails...
last line in setup log is .....

2021-03-23 17:56:56> RegistryService: TryDeleteRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\PreventInstallationFromMsi not found

can someone help?

**Comment by hoffmang9** [comment]
Try rebooting and installing again.

**Comment by Dan1138** [comment]
Make sure you have the right log file opened, for me, when the Chia installer failed, it opened the wrong log file when I clicked view log!  For me, the wrong log file it opened was %LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log while the real Chia error log it should have opened was at %LOCALAPPDATA%\SquirrelTemp\Squirrel-Install.log. If you look at the correct log file, you may get a better idea of what exactly is failing.

For me, what was failing was that NVIDIA Share.exe was locking the DLL's libcrypto-1_1.dll and libssl-1_1.dll (found at %LOCALAPPDATA%\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon). I could not delete these files myself even after closing as much NVIDIA crap as I could.

My fix was to reboot into safe mode and delete those two files. After rebooting back into normal Windows (no longer safe mode) the installer then ran fine.
