### ISSUE TITLE
Writing error during plotting [BUG]

### ISSUE THREAD

**Issue by mattuso83** [Chia-Network/chia-blockchain#2717]
**Describe the bug**
The plotting process is suddenly stopped because it can't write on the temp disc.

**Expected behavior**
It says "Retrying in five minutes", which is what happens, but the plotting doesn't restart despite the disc is connected and running

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/67392171/116000839-223ca300-a5f2-11eb-990e-dac9497a7326.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: 20H2
- CPU: Intel i5-8350U

**Additional context**
I'm plotting 2 plots.
The disc is external, connected via USB-C, it has more than 1 Tb free and all the power saving option have been disabled.
Unplugging and plugging back the cable didn't help.

**Comment by LoudSyncro** [comment]
Check if disc D: has enough free space.
This message usually occurs then.

**Comment by hoffmang9** [comment]
Issues is not for tech support. Discussions or Keybase.
