### ISSUE TITLE
Moving Plots to another machine

### ISSUE THREAD

**Issue by damkettle** [Chia-Network/chia-blockchain#2725]
I have just upgraded to 1.1.2 and I am using two machines to plot. When I transfer plots from one machine to another, they show an error "Failed to Open (Invalid Plot)" This hasn't happened before and I have been plotting for 4 weeks now.

**Comment by royimous** [comment]
Did you read the wiki page on moving plots? It explains this there: https://github.com/Chia-Network/chia-blockchain/wiki/Moving-plots
