### ISSUE TITLE
Running install.sh fails, network timeout error

### ISSUE THREAD

**Issue by damian101** [Chia-Network/chia-blockchain#273]
I'm using Feren OS (Ubuntu 18.04). Running install.sh always results in an error like this: `npm ERR! network timeout at: https://registry.npmjs.org/@babel/plugin-proposal-json-strings/-/plugin-proposal-json-strings-7.8.3.tgz`. The link is always a different one, and they all worked fine in a browser.

**Comment by damian101** [comment]
I fixed it by installing pnpm (`npm install -g pnpm`) and changing the line `npm audit fix` in install.sh to `pnpm audit fix`.

**Comment by hoffmang9** [comment]
Since 18.04 has such an ancient node.js, we're detecting that and upgrading node automatically in the next release - https://github.com/Chia-Network/chia-blockchain/blob/dev/install.sh
