### ISSUE TITLE
[BUG] : WALLET can't SYNC - connections : 0 

### ISSUE THREAD

**Issue by casa10** [Chia-Network/chia-blockchain#2730]
**Describe the bug**

OS : windows 10 pro 64 bits
Chia version : 1.1.2

I closed chia gui to switch off computer
I start computer and after launch chia gui.
He took little time to sync the full node. 
Farming status became "Farming"
Local hovester Plot passed to "farming" 
BUT 
Wallet status : not synced
Wallet Height :183979     whereas height on full node status equal 185009
Wallet Connections : 0

 I looked on debug files and it's written
2021-04-25T20:50:41.869 wallet wallet_server : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Expected behavior**
I would like to know why this error.
Even with restarting chi gui or computer : same problems.
Questions : 
- how to repair this thing to have synced wallet
- if wallet not synced, how  can i know i win ? Maybe we can win and it will not appear or maybe it's impossbile to win because impossible to sync wallet.
Thank you.

**Comment by royimous** [comment]
Do you have port forwarding set up on your router? You need to forward port 8444

You can use this site to check if port 8444 is open: https://portchecker.co/

**Comment by speedmann** [comment]
@royimous thats wrong. You do not need to portforward to be able to sync.

**Comment by royimous** [comment]
> @royimous thats wrong. You do not need to portforward to be able to sync.

You're technically right, except, opening port 8444 does solve a lot of the sync issues. 

Quoting the chia-blockchain README:
> If you are behind a NAT, it can be difficult for peers outside your subnet to reach you when they start up. You can enable UPnP on your router or add a NAT (for IPv4 but not IPv6) and firewall rules to allow TCP port 8444 access to your peer.

Connecting to more peers speeds up the sync and you can help this by opening port 8444.

**Comment by hoffmang9** [comment]
@royimous is precisely correct.

However the original issue is something we see in rare cases where the App can't get it's preferred ports. Often that means there are zombie versions and a computer restart is in order on Windows.

**Comment by casa10** [comment]
Hye,
My port 8444 is opened.
I make you screenshot of my problem

Ful node
![image](https://user-images.githubusercontent.com/8081413/116010814-b8d48880-a621-11eb-908c-25236a655985.png)


Wallet 
![image](https://user-images.githubusercontent.com/8081413/116010845-d99cde00-a621-11eb-9b93-a2a7dd7679d0.png)

Rules of router
![image](https://user-images.githubusercontent.com/8081413/116010978-92631d00-a622-11eb-9db6-05dbf526943e.png)
