### ISSUE TITLE
my wallet not sync for days...

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#2731]
my wallet not sync for days...

what happen?

![image](https://user-images.githubusercontent.com/82982237/116005999-ae0df980-a609-11eb-989a-da79485df195.png)
![image](https://user-images.githubusercontent.com/82982237/116006009-be25d900-a609-11eb-81b8-82e1a90d8e06.png)

0.0/0.0 in connections

Tnx

**Comment by hoffmang9** [comment]
Is it only your wallet that is not synced? You can often get it to update by choosing Keys and then your current key again.

If your node is not synced, you should upgrade to 1.1.2 but it looks like you have plenty of connections.

**Comment by Gargo** [comment]
@hoffmang9 it doesn't work

**Comment by Andrewbono** [comment]
Same thing with me... the wallet is not syncing.
Node is working fine and added more plotting work. However, the wallet remains not synced.

**Comment by hoffmang9** [comment]
There have been lots of wallet sync improvements. Closing as fixed.
