### ISSUE TITLE
Mining Chia on 2 computers at the same Network

### ISSUE THREAD

**Issue by egorgolo** [Chia-Network/chia-blockchain#2732]
Hello everyone, 

I have recently had a problem with app "connecting to wallet" on my older Mac. The problem was due to the fact that I installed and launched chia on my newer Mac previously. In this way, port 8444 was assigned to the IP of my newer Mac, where I first launched chia. Since I can't assign one port to 2 different IPs, the question is: Can I mine Chia on 2 computers at the same network?

**Comment by hoffmang9** [comment]
Please don't use issues for tech support. Your question is an FAQ answered on the wiki here.
