### ISSUE TITLE
my plots lost ? when I create 10 plots then I cant see when they R on %23 how can find on this program[BUG]

### ISSUE THREAD

**Issue by serhatrda** [Chia-Network/chia-blockchain#2733]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by hoffmang9** [comment]
Issues are not for tech support. Try Discussions of Keybase.
