### ISSUE TITLE
wallets

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#2740]
Hi
How i can know in with address my rewards are paid?

The plots and rewards are associated at wallet? or the rewars are keep in the plot ...

tnx

**Comment by royimous** [comment]
Hello, this is not an issue. This is you not taking the time to read the ample documentation on the main chia site and the wiki pages.

Please look at this page the the ways it lists how to figure out answers to your problems: chia.net/faq/
