### ISSUE TITLE
is it possible to install on linux without GUI?

### ISSUE THREAD

**Issue by mendisobal** [Chia-Network/chia-blockchain#2741]
how to install chia-blockchain on headless linux server?

**Comment by royimous** [comment]
This is not a bug. Delete this. 

You did not take the time to figure this out. The answer to your question is literally in this Github.

**Comment by speedmann** [comment]
```
git clone https://github.com/Chia-Network/chia-blockchain
cd chia-blockchain/
sh install.sh
source ./activate
chia init
chia start node farmer harvester
```

Thats what i did

`chia plots create -k 32 -r 2 -u 128 -b 4608 -t /temp -d /destination` to start plotting, for more advanced plotting, see guides
`chia show -c -s` for status
`chia farm summary` for farm status

**Comment by mendisobal** [comment]
Thanks for the information, it was just not clear whether it is possible to do without GUI

**Comment by royimous** [comment]
=

> ```
> git clone https://github.com/Chia-Network/chia-blockchain
> cd chia-blockchain/
> sh install.sh
> source ./activate
> chia init
> chia start node farmer harvester
> ```
> 
> Thats what i did
> 
> `chia plots create -k 32 -r 2 -u 128 -b 4608 -t /temp -d /destination` to start plotting, for more advanced plotting, see guides
> `chia show -c -s` for status
> `chia farm summary` for farm status
> 
> @royimous i feel your comment is unappropriate. Even though the label is wrong, there is very little information available to run chia headless.

There is a lot information online. I found the install guide on this page + a few web pages with instructions for various steps I had issues with. I set up Chia headless last night on Ubuntu server. Google is our friend :)
