### ISSUE TITLE
wishlist: write final tmp-file directly to destination folder

### ISSUE THREAD

**Issue by alfs** [Chia-Network/chia-blockchain#2743]
In stage 4, the final plot is constructed as a tmp-file, later renamed to *plot, and copied to the destination folder.

This causes an additional 100 GB of SSD write, as well as increasing the overall storage requirement on small SSDs.

I suggest an option to instead write the final tmp-file directly to the destination folder (possibly a slow disk), and then rename it when it is complete.

Will it be slower than the current approach? I think not, or at least not much. Instead of the final plot being copied at the end, it is instead copied in pieces as it is assembled.

On the upside - save SSD wear, reduce SSD space utilization (e.g., allowing for more parallell plots).

(edit - not a bug per se, but I can't remove the bug label)

**Comment by royimous** [comment]
Not a bug :-)

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-secondary-temp-directory--2-and-how-should-i-set-it
