### ISSUE TITLE
[BUG] Temp space reported required definitely wrong on Windows 10, Chia 1.0.5

### ISSUE THREAD

**Issue by garyhkirk** [Chia-Network/chia-blockchain#2744]
**Describe the bug**
Plotting 3 * K-32 fills a previously empty 1TB Corsair MP600 temp drive  

**To Reproduce**

Note: I have not tried this on later versions as I have two machines and other issues prevent me from updating the farmer until the last minute. I have had no issues on this machine before - I was only plotting two at a time until I freed all of the space on it to allow for 3.

1. Plot 3 K-32's to an empty 1TB Corsair MP600, destination drive is SATA HDD
2. Wait for 33% progression
3. Get error about not being able to write
4. Check temp drive and see it's full

**Expected behavior**
1TB of temp space is far beyond the stated requirements for 3 plots

**Desktop (please complete the following information):**
- OS: Windows 10 Pro
- OS Version: All updates installed as of 25 April 2021
- CPU: Ryzen 3600
- RAM: 32GB

**Additional context**
Max RAM for each plot was 6750MB, each started as a separate queue with 10 plots to run sequentially - meaning that 3 queues were only ever going to run one plot each at a time. **Could the allocation of more RAM cause larger temp space requirements? It's not documented that way**

**Comment by royimous** [comment]
Upgrade to 1.1.2 first. Your version is very old.

**Comment by hoffmang9** [comment]
Make sure your temp disk is actually empty and not just hiding undeleted files from you. Closing because tech support not in Issues.
