### ISSUE TITLE
[BUG] Split tmp files

### ISSUE THREAD

**Issue by radvansky-tomas** [Chia-Network/chia-blockchain#2746]
I assumed that when I provide 2 tmp locations I will not run out of space...

ie.

1. I selected main tmp file on my main NVME disk
2. I selected empty external SSD disk as secondary tmp location
3. I selected my HDD to store plots as destination

Plots failed multiple times with error:
Could not write tmp file etc...retry in 5mins

I mean I would expect that:
1. process will not use ALL available space (ie my OS ended up with no free space at all)
2. process will be able to make decision, when write fails to move next writes to secondary location, when I have already specified it !

**Comment by hoffmang9** [comment]
This is not a tech support forum.

**Comment by radvansky-tomas** [comment]
Sure, tech support forum will fix your code

**Comment by hoffmang9** [comment]
But the documentation is a wiki you can edit to warn others away from your mis-read.
