### ISSUE TITLE
[BUG] plots not found

### ISSUE THREAD

**Issue by rustx11** [Chia-Network/chia-blockchain#2747]
I cant see the plots on farm

![Sin título2](https://user-images.githubusercontent.com/83190926/116013355-35f20480-a606-11eb-9ed7-e7927abf1037.png)
![Sin título](https://user-images.githubusercontent.com/83190926/116013365-3f7b6c80-a606-11eb-96b6-d624864b0ce2.png)
![Sin título3](https://user-images.githubusercontent.com/83190926/116013371-430ef380-a606-11eb-9114-df7a5ba92cf2.png)

**Comment by hoffmang9** [comment]
You can't farm until the plot is complete. This is not the place for tech support.

**Comment by rustx11** [comment]
In the first image you can see 2 finished plotts. I'm going for the third and nothing
