### ISSUE TITLE
[BUG] can see anything on my gui just get a spinning circle and says connecting to wallet been this way for hours

### ISSUE THREAD

**Issue by hjason7812** [Chia-Network/chia-blockchain#2750]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Crypto-78** [comment]
The software is still under development and still has some bugs, when this happens to you or the nodes do not synchronize it is useless to wait hours, go to powershell enter the folder where Chia is installed

....\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon>

launch the command:

.\chia stop all -d

the command will respond:
Daemon not started yet
Couldn't connect to chia daemon

and reopen the application.

This solves most of the problems

**Comment by anton-generalov** [comment]
> 
> 
> The software is still under development and still has some bugs, when this happens to you or the nodes do not synchronize it is useless to wait hours, go to powershell enter the folder where Chia is installed
> 
> ....\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon>
> 
> launch the command:
> 
> .\chia stop all -d
> 
> the command will respond:
> Daemon not started yet
> Couldn't connect to chia daemon
> 
> and reopen the application.
> 
> This solves most of the problems

**Comment by royimous** [comment]
Why would anyone want to help you when you haven't even filled out the basic form asking for more info?
