### ISSUE TITLE
[BUG] Chia Windows Environment Variable

### ISSUE THREAD

**Issue by filzek** [Chia-Network/chia-blockchain#2753]
CURRENT Windows install has missed some basic rules for an application deployment, it shall require under the install to set the accurate CHIA_APP version and update it on new updates versions being installed.

As Users need to run any kind of command in chia, it shall accurate find the APP version so they can fast CF to it.

See the example below:
cd C:\Users\%USERNAME%\AppData\Local\chia-blockchain\%CHIA_APP%\resources\app.asar.unpacked\daemon

So as the CHIA BLOCKCHAIN changes the application  directory name, it is a must to use an ENVIRONMENT VARIABLE to correct instruct any kind of automated task and system under user control.

Please take this very carefully in appreciation as for CHIA.EXE run it is a must.

Thanks and hopefully expecting your acceptance!

**Comment by hoffmang9** [comment]
PRs welcome. Changing installers is on the roadmap.
