### ISSUE TITLE
Not found Plots!!!!!!!!

### ISSUE THREAD

**Issue by chizhenming** [Chia-Network/chia-blockchain#2758]
![image](https://user-images.githubusercontent.com/9978933/116019707-66be5200-a677-11eb-9200-340d31dc1293.png)
![image](https://user-images.githubusercontent.com/9978933/116019798-9b320e00-a677-11eb-9c31-0de10b73c05e.png)
vserion:1.1.0

**Comment by keliew** [comment]
Upgrade to 1.1.2

Remove the plot directory, and add it back.

**Comment by vvs374** [comment]
Такая-же ошибка,после перезапуска не видит 5 плотов которые прекрасно работали ранее((

**Comment by hoffmang9** [comment]
This is a tech support question and not a bug.
