### ISSUE TITLE
Sometimes draw error

### ISSUE THREAD

**Issue by ZRory** [Chia-Network/chia-blockchain#2760]
Starting plotting progress into temporary dirs: D:\ and D:\
ID: d08b8daee53e225b0a41b03d3dc9f6dfbcae95ea69c39462a53590916b752370
Plot size is: 32
Buffer size is: 4096MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Mon Apr 26 10:22:54 2021
Computing table 1
F1 complete, time: 146.902 seconds. CPU (173.54%) Mon Apr 26 10:25:21 2021
Computing table 2
Caught plotting error: bad allocation

**Comment by hoffmang9** [comment]
FAQ - https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation

**Comment by ZRory** [comment]
> 常见问题解答-https: [//github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation](https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation)

It doesn’t seem to be a RAM problem. The other 13 tasks on my same machine are running normally.
<img width="901" alt="微信图片_20210426105756" src="https://user-images.githubusercontent.com/31235873/116023223-4d6cd400-a67e-11eb-93fe-ea02c1992e8f.png">

**Comment by hoffmang9** [comment]
It could be swap related but it is RAM.
