### ISSUE TITLE
[BUG]Program window feign death

### ISSUE THREAD

**Issue by mlpig** [Chia-Network/chia-blockchain#2761]
chi![AAAAA](https://user-images.githubusercontent.com/82919510/116022373-a76c9a00-a67c-11eb-8432-02ed09ec7170.png) blockchain
Cultivated land in the process of window program feign death, a v![AAAAA](https://user-images.githubusercontent.com/82919510/116022373-a76c9a00-a67c-11eb-8432-02ed09ec7170.png)st white. State unknown

**Comment by keliew** [comment]
Edit (编辑) > Reload

**Comment by hoffmang9** [comment]
We know the root cause and are working on a fix.
