### ISSUE TITLE
None of your plots have passed the plot filter yet. But you are currently farming 5.84 TiB

### ISSUE THREAD

**Issue by HettyPatel** [Chia-Network/chia-blockchain#2764]
I have about 60 plots and they were working fine. In the Farm tab on the GUI under Last Attempted Proof and Latest Block Challenges things were updating. In the last attempted proof I would usually see a 0/# and it would update pretty often. 

I had to turn the application down to install a new ssd but after the upgrade it does not update anymore. Just says "None of your plots have passed the plot filter yet. But you are currently farming 5.84Tib"

Things I have tried:
Uninstalling and reinstalling chia. 
Downgrading to 1.0.5 (currently am on 1.1.1)
Deleted the .chia folder and brought it in from my 2nd computer on which the plots seem to be working fine on the GUI 
Restarted the application. 
Restarted PC
Tried reloading the wallet from the app but that just gets stuck on connecting to wallet 
Ran a plots check and they seem to be fine. 

not sure what the issue is I have the port 8444 open as well and is port forwarded. 
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/6374105/debug.log)

**Comment by r00t9** [comment]
I also have the same issue maybe 6-7 hours now

**Comment by HettyPatel** [comment]
> I also have the same issue maybe 6-7 hours now

yep its been a while same thing tried a bunch of different things nothing seems to be working. I networked the drive to my gaming pc and tried farming the plots there and seems to farming on my main rig over the network but idk how to fix it.

**Comment by Rafgt** [comment]
Shutdown Chia try to delete the file "peer_table_node.sqlite" in chia->mainnet->db folder and open Chia. 
Also you could turn off upnp in full node config file

**Comment by keliew** [comment]
Make sure you upgrade to 1.1.2. There are fixes that should solve your issue.

**Comment by Rafgt** [comment]
On Windows upgrade 1.1.2 did not resolve that for sure - even it is worse. I back to 1.1.1 and this solution works.

**Comment by HettyPatel** [comment]
Was not able to track down what caused / solved the issue but I just let the GUI run over night and it fixed itself.
