### ISSUE TITLE
Only read xxxx of xxxxx bytes at offset[BUG]

### ISSUE THREAD

**Issue by imziwen** [Chia-Network/chia-blockchain#2765]
**Describe the bug**
Only read xxxx of xxxxx bytes at offset xxxxx from "E:\\xxxxxxxx" with length 738093048. Error 1. Retrying in five minutes.

**To Reproduce**

Perform three tasks side by side, and the other two will succeed. One of them will prompt the following error. What is the reason for this?

Thank you very much.

**Screenshots**
![image](https://user-images.githubusercontent.com/14174105/116026603-a429dc00-a685-11eb-8730-9fdebacb027b.png)

![image](https://user-images.githubusercontent.com/14174105/116026684-c3286e00-a685-11eb-947a-2b3c0d9a0f09.png)

**Desktop (please complete the following information):**

- OS: windows
- OS Version/Flavor: windows 10
- CPU:  Intel i7-10700k
- Chia Blockchain Version 1.1.2

**Additional context**

**Comment by hoffmang9** [comment]
Out of space or some other filesystem issue.

**Comment by juhi24** [comment]
Seems to have happened to me too simultaneously on two separate disks. Disk utilization is under 1% on both.
