### ISSUE TITLE
[错误]钱包和节点都是未同步

### ISSUE THREAD

**Issue by zyf456123789** [Chia-Network/chia-blockchain#2766]
![1](https://user-images.githubusercontent.com/82851644/116027016-68434680-a686-11eb-9008-24fc5759e7a3.png)
![2](https://user-images.githubusercontent.com/82851644/116027019-69747380-a686-11eb-9b5a-98fbb831d111.png)
节点和钱包已经好几天是 未同步的状态，软件也已经更新到1.12

**Comment by threebowrice** [comment]
do u open 8444 port on your router ?

**Comment by zyf456123789** [comment]
> 您是否在路由器上打开 8444 端口？

sorry，i don‘t know how to do this.

**Comment by keliew** [comment]
> > 您是否在路由器上打开 8444 端口？
> 
> sorry，i don‘t know how to do this.
From your router (路由器).

You can also manually add the node and see if it starts to sync: node-apne.chia.net:8444

**Comment by xiaohui1997** [comment]
Opening a router port 8444 doesn't help either

**Comment by xiaohui1997** [comment]
The application should appear bugs

**Comment by vipwzw** [comment]
> > > 您是否在路由器上打开 8444 端口？
> > 
> > 
> > sorry，i don‘t know how to do this.
> > From your router (路由器).
> 
> You can also manually add the node and see if it starts to sync: node-apne.chia.net:8444

how to fixed the node on config.yaml

**Comment by keliew** [comment]
> Opening a router port 8444 doesn't help either
Disabled UPNP?

> > > > 您是否在路由器上打开 8444 端口？
> > > 
> > > 
> > > sorry，i don‘t know how to do this.
> > > From your router (路由器).
> > 
> > 
> > You can also manually add the node and see if it starts to sync: node-apne.chia.net:8444
> 
> how to fixed the node on config.yaml
You can't.

**Comment by darwinjobchia** [comment]
I had same issue before, it seems not relate to 8444, maybe your wallet crashd, you have to reinstall your wallet, before that you have to delete the db file(.chia>mainnet>wallet>db) first, then install new 1.1.2 chia
