### ISSUE TITLE
opcion delete is not functional

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#2768]
The delete option is not available on farms, on invalid plots, or on invalid plots.
![image](https://user-images.githubusercontent.com/82982237/116031440-f6ef9d80-a65d-11eb-8c8b-10dcf4528984.png)

**Comment by qq253044370** [comment]
me too。。

**Comment by John98798986** [comment]
The same after update to ver 1.1.2. The delete bottom is not active

**Comment by qq253044370** [comment]
> The same after update to ver 1.1.2. The delete bottom is not active

1.1.1 have the problem

**Comment by John98798986** [comment]
I have number of broken plots that should be deleted. Is this a system bug? Could it be fixed in a next version, or the delete button intentionally blocked by developer? Any ideas?

**Comment by hoffmang9** [comment]
As the release notes tell you, the delete button is temporarily disabled as it would otherwise crash the entire application.
