### ISSUE TITLE
[BUG]RPC problem

### ISSUE THREAD

**Issue by kencani** [Chia-Network/chia-blockchain#2773]
**Describe the bug**
I use the full node RPC，like get_additions_and_removals,get_blocks,get_coin_records_by_puzzle_hash. It's return like

```json 
"coin_records":[
{
"coin":{
"amount":250000000000,
"parent_coin_info":"0x3ff07eb358e8255a65c30a2dce0e5fbb00000000000000000000000000013927",
"puzzle_hash":"0x86ace7d6d38c3d1949c28eefc54e093bdc0249a7a07057f1374e134e7485e883"
},
"coinbase":true,
"confirmed_block_index":80169,
"spent":false,
"spent_block_index":0,
"timestamp":1617554786
},

```

But i can't find any param about the coin hash and the address,Which interface method should I use to query the coin hash and address？

**Comment by aqk** [comment]
Thank you for your bug report. You have run into a last minute change!

We changed the definition of coins from (amount, coin_id, puzzlehash) to (amount, parent_coin_id, puzzlehash)

To get information on how to get a coin's parent_id, and how to set the address for a transaction,

Please install https://keybase.io/download
And then come to keybase://chat/chia_network.public#dev
for more discussion on RPC use and other development.

**Comment by kencani** [comment]
> #dev

it has #annou #beginner #general #random #support but not #dev.....

**Comment by zhaozhijun1988** [comment]
parent_coin_info is the parent coin id? coinid = sha256(parent_coin_info, puzzle_hash, value),how to get coin id by rpc interface, thanks

**Comment by sibitha-bijesh** [comment]
have you find the way yo create coin id . The above method not giving correct output

**Comment by PrernaPadhee** [comment]
hey, have you figured a way to get  coinid = sha256(parent_coin_info, puzzle_hash, value), i am unable to get the expected result. Is there an RPC call for the same ?

**Comment by uranik777** [comment]
How to get coin name 0x0784eb43d9059d7a530c8a5bcbd7772705d4897e9ea78643726b8f7a19081d2b from coin object
"coin": {
            "amount": 3293826240000,
            "parent_coin_info": "0x8b6b9557d83b9697abfdfc44963d6a6beb65f942530fb50d8da51fee449cec5e",
            "puzzle_hash": "0x670e02175a4bf98033840e92e2c0a963ee2d6275f54804db797730b97273cf8d"
        }


`
from hashlib import sha256

parent_coin = b'0x8b6b9557d83b9697abfdfc44963d6a6beb65f942530fb50d8da51fee449cec5e'
puzzle_hash = b'0x670e02175a4bf98033840e92e2c0a963ee2d6275f54804db797730b97273cf8d'
amount = b'3293826240000'

def test_coin_name() -> None:
    print(sha256(parent_coin + puzzle_hash + amount).hexdigest())

test_coin_name()
`
this sample return wrong result 20aaf2955c9e2c2a7282e3f335c84638c66b463989838388c4d6bcaac5dce84e

**Comment by kimsk** [comment]
@uranik777  Try this code below instead:
```python
from chia.types.blockchain_format.sized_bytes import bytes32
from chia.util.hash import std_hash
from clvm.casts import int_to_bytes

parent_coin = bytes32.from_hexstr('0x8b6b9557d83b9697abfdfc44963d6a6beb65f942530fb50d8da51fee449cec5e')
puzzle_hash = bytes32.from_hexstr('0x670e02175a4bf98033840e92e2c0a963ee2d6275f54804db797730b97273cf8d')
amount = int_to_bytes(3_293_826_240_000)

std_hash(
    parent_coin +
    puzzle_hash +
    amount
).hex()
```
