### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kpoboctok11** [Chia-Network/chia-blockchain#2774]
![Безымянный2222](https://user-images.githubusercontent.com/83204935/116040060-30330800-a674-11eb-87df-0fc06d0fec25.png)

Не синхронизирует клиент,версия клиента 1.1.2

**Comment by sognev** [comment]
Открой и пробрось порт на роутере 8444 и пропиши в фаерволе windows разрешения на входящие и исходящий трафик для этого порта 

Open and forward the port on the 8444 router and write permissions for incoming and outgoing traffic for this port in the windows firewall

**Comment by kpoboctok11** [comment]
> Открой и пробрось порт на роутере 8444 и пропиши в фаерволе windows разрешения на входящие и исходящий трафик для этого порта
> 
> Open and forward the port on the 8444 router and write permissions for incoming and outgoing traffic for this port in the windows firewall

Я рядовой пользователь,у меня ничего не получилось.

**Comment by kpoboctok11** [comment]
> Открой и пробрось порт на роутере 8444 и пропиши в фаерволе windows разрешения на входящие и исходящий трафик для этого порта
> 
> Open and forward the port on the 8444 router and write permissions for incoming and outgoing traffic for this port in the windows firewall

[
![Безымянный223123123](https://user-images.githubusercontent.com/83204935/116049325-d552de00-a67e-11eb-9b77-c2cdbc67912b.png)
](url)

**Comment by keliew** [comment]
Manually at this node: node-eu.chia.net:8444

If it still doesn't sync after 30mins, could you check if Windows' firewall or defender is blocking Chia?

**Comment by kpoboctok11** [comment]
> Manually at this node: node-eu.chia.net:8444
> 
> If it still doesn't sync after 30mins, could you check if Windows' firewall or defender is blocking Chia?

Пока-что вса работает.Спасибо за совет.
![image](https://user-images.githubusercontent.com/83204935/116065148-629e2e80-a68f-11eb-8ed7-850b55163c9e.png)
