### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YujinBii** [Chia-Network/chia-blockchain#2775]
At the end (plotting 100%) of sowing the site, Windows 10 crashes. At the same time, it gives an error: "An operating system wasn't found. Try disconnecting any drivers that don't contain an operating system"
This is repeated for the second time.

![Screenshot_1](https://user-images.githubusercontent.com/83204561/116041218-a126ef80-a675-11eb-8652-ca87121e9bc1.png)
![Screenshot_2](https://user-images.githubusercontent.com/83204561/116043510-6c686780-a678-11eb-9386-f2426402471a.png)
![Screenshot_3](https://user-images.githubusercontent.com/83204561/116043513-6d00fe00-a678-11eb-8423-847179d90afd.png)
![an_operating_system_wasnt_found](https://user-images.githubusercontent.com/83204561/116043576-83a75500-a678-11eb-9839-c8d26a7cabdc.png)

**Comment by YujinBii** [comment]
![an_operating_system_wasnt_found](https://user-images.githubusercontent.com/83204561/116041665-23171880-a676-11eb-9ccd-9686174d8b69.png)

**Comment by YujinBii** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/83204561/116042595-40001b80-a677-11eb-8125-5a6711133230.png)

**Comment by YujinBii** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/83204561/116043420-4e026c00-a678-11eb-8d38-eef54c5d4217.png)

**Comment by keliew** [comment]
HDD failure? Have you ran SMART?

**Comment by YujinBii** [comment]
> Сбой жесткого диска? Вы запускали SMART?

I'm sorry, what is it SMART?

**Comment by YujinBii** [comment]
> Сбой жесткого диска? Вы запускали SMART?

I didn't run it SMART.

**Comment by dorkmo** [comment]
are you plotting on your C: drive? try not to do that if so.
