### ISSUE TITLE
[BUG] Chia fresh install pulling dev version - listed fix does not work

### ISSUE THREAD

**Issue by heartoftokyo** [Chia-Network/chia-blockchain#2779]
**Describe the bug**
Do a clean install of Chia to Ubuntu, and you get a .dev version
Do an update, and you get a .dev version
Apply to suggested fix of deleting the .json file, and you still get a dev version

**To Reproduce**
Install or update Chia-blockchain on Unbuntu

**Expected behavior**
Version 1.05, 1.0, 1.1, 1.2 -- always getting a dev version (this time .dev11)

**Desktop (please complete the following information):**

- OS: Ubuntu 20

**Additional context**
There are weird problems usually with the dev versions

**Comment by keliew** [comment]
It's 'normal' for Debian/Ubuntu. It's just cosmetics.

FWIW, am on `1.1.2.dev11`.

**Comment by hoffmang9** [comment]
This is `git` being a pain. Safe to ignore.
