### ISSUE TITLE
[BUG]Nodes not syncing even after the upgrade 1.1.2 and port 8444 resolve - MacOS Big Sur

### ISSUE THREAD

**Issue by fernandosac91** [Chia-Network/chia-blockchain#2780]
I have opened the port 8444 manually, restarted the mac upgraded the chia app to 1.1.2 but none of this is helping it is still not syncing. 

Plots are not farming ("Not Available") it says

But the wallet seems to be syncing 

Please advice on this matter.

**Comment by iEddie-cmd** [comment]
same on macos

**Comment by Linusten** [comment]
Same here on Win 10

**Comment by AkiraDX** [comment]
same here with Win 10

**Comment by PangPangSukoy** [comment]
> 
> 
> same here with Win 10

Me too.

**Comment by RichJac** [comment]
Same here on Mojave.

**Comment by Gargo** [comment]
same on windows 10

**Comment by royimous** [comment]
Are you running the CLI as well as the GUI at the same time?

Are you sure port 8444 is open? Check here: https://portchecker.co/

If you want to get help, read the FAQ for the proper support areas. This isn't a bug as far as I can tell. 

Also consider using the CLI. It has less problems than the GUI.

**Comment by royimous** [comment]
Also: look in your config.yaml file. If the directories with the plots are not in there, the GUI won't see them.

**Comment by AkiraDX** [comment]
it's getting worse. My client can't sync the whole morning.
Downgraded to 1.1.1 still can't get it sync.

**Comment by sergibarroso** [comment]
Had the same problem here with Debian.

Seeing this on my logs:

```
2021-04-27T09:12:12.988 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/home/giga/Downloads/chia-blockchain/chia/full_node/full_node.py", line 624, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 95.49.47.131
```

**Comment by thentd** [comment]
我也是一样的 更新到最新的111、112都是一样的无法连接，105版本没得这个问题，直接就可以跑

**Comment by bobfredarctor** [comment]
same problem. haven't been able to sync since 1.1.1 update. i tried it both on linux and windows. port is open btw.

**Comment by sergibarroso** [comment]
This worked for me:

https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
