### ISSUE TITLE
Cannot run chia.exe in more than 2 powershell.

### ISSUE THREAD

**Issue by CryingFor** [Chia-Network/chia-blockchain#2782]
When I tried to run many chia.exe instance in more than 2 Windows Power Shells by command. I found the 3rd Power Shell's chia.exe will not take any CPU/memory/Disk. And it will stuck in the 1 Phase which is "Computing table 1".
![image](https://user-images.githubusercontent.com/22956440/116057467-68a50700-a6b1-11eb-8186-552d91c6f867.png)
Command : 
chia.exe plots create -k 32 -b 6000 -r 4 -u 128 -t J:\ -d I:\
I have run this command on these three Power Shell instance. Does I use a wrong parameters for parallel ploting?

CPU: E3-1231V3
MEM: 32G
DISK: 1T SSD + 8T HDD
WINDOWS 10
![image](https://user-images.githubusercontent.com/22956440/116057981-f1bc3e00-a6b1-11eb-8646-3681ac0ed6df.png)

**Comment by keliew** [comment]
Seems like you're hitting a bottleneck from your hardware. #support on Keybase should be able to help you debug further.

**Comment by CryingFor** [comment]
> Seems like you're hitting a bottleneck from your hardware. #support on Keybase should be able to help you debug further.

When I use GUI tools to build 3 plots in the same time, it works.
But the GUI tools on my PC often stuck at the "连接到钱包"(maybe it means "connecting to wallet"), and I must restart the GUI tools. If I restart the GUI, I will lose my plot which have not been built successfully yet.
So I am trying to build plot with command. It should be the same as the GUI about the bottleneck.

**Comment by CryingFor** [comment]
Update:
When I change the parameters from 
"chia.exe plots create -k 32 -b 6000 -r 4 -u 128 -t J:\ -d I:\ " 
to
"chia.exe plots create -k 32 -b 9000 -r 4 -u 128 -t J:\ -d I:\ "
at the 3rd Windows Power Shell. It works again.
But I still cannot know why. Maybe the memory parameter will also across the instance?

**Comment by HailongZhu** [comment]
I'm having the exact same problem today. Two plotter process died in power shall, one at the end of phase 1, the other in phase 2.

You: 3rd process on a E3-1231V3 (4 core 8 thread), -r 4
Me: 7th process on a 3600x (6 core 12 thread), -r 2

Looks like this will happen when chia requests more threads than currently available.
Why changing the size of the buffer fixes this problem is beyond me.

**Comment by hoffmang9** [comment]
Issues are not for tech support.

**Comment by CryingFor** [comment]
> Issues are not for tech support.

It maybe a medium CR for the command.  Stability issues will waste a lot of time when building the plot.
