### ISSUE TITLE
硬碟跑100% 還沒變成農地

### ISSUE THREAD

**Issue by jackykuso** [Chia-Network/chia-blockchain#2786]
![螢幕擷取畫面 2021-04-26 182653](https://user-images.githubusercontent.com/83216391/116068607-005c2280-a6bd-11eb-8930-6de701655411.png)

"D:\\CHIA1\\plot-k32-2021-04-25-19-47-334460e1cca3c8cc0e1be84a0825d2a2eff83de4f396f270ed9a92280c65d5ca.plot.2.tmp" to "F:\\CHIA1\\plot-k32-2021-04-25-19-47-334460e1cca3c8cc0e1be84a0825d2a2eff83de4f396f270ed9a92280c65d5ca.plot.2.tmp". Error 信號等待逾時。. Retrying in five minutes.

**Comment by jackykuso** [comment]
D:\\CHIA1\\plot-k32-2021-04-25-19-47-334460e1cca3c8cc0e1be84a0825d2a2eff83de4f396f270ed9a92280c65d5ca.plot.2.tmp" to "F:\\CHIA1\\plot-k32-2021-04-25-19-47-334460e1cca3c8cc0e1be84a0825d2a2eff83de4f396f270ed9a92280c65d5ca.plot.2.tmp". Error 因為 I/O 裝置錯誤，所以無法執行請求。. Retrying in five minutes.

**Comment by muthubaby** [comment]
可能 路径错或盘满了?

**Comment by maomingyang1314** [comment]
Files are being transferred from the temporary directory to the target directory, it takes time
