### ISSUE TITLE
[BUG] узел не синхронизирован с сетью

### ISSUE THREAD

**Issue by Alekcsandr516** [Chia-Network/chia-blockchain#2789]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Alekcsandr516** [comment]
продолжает засеивать , но но не синхронизирует , не фармит версия 1.1.1 но ОС Windows

**Comment by ESKCOBAR** [comment]
админы говорят установить новую версию 1.1.2 но если честно и она тупит не синхронизирует у меня уже второй день!

**Comment by angry-mammoth** [comment]
Открываем порт 8444 и будет всё работать :)

**Comment by stalit1** [comment]
Cылка на ютуб https://www.youtube.com/watch?v=f4PS6ut6fQ8
