### ISSUE TITLE
Wiki can't be fully cloned on Windows

### ISSUE THREAD

**Issue by Autorojo** [Chia-Network/chia-blockchain#2793]
Hello!

I am trying to clone the Wiki of this project to read it offline on Windows. The Wiki can't be cloned correctly because an invalid file name - Windows doesn't like question marks on file/directory names.

The file is: [Is-my-farm-healthy?-I-am-not-finding-proofs.md](https://github.com/Chia-Network/chia-blockchain/wiki/Is-my-farm-healthy%3F-I-am-not-finding-proofs)

PowerShell output:
```
PS D:\github> git clone https://github.com/Chia-Network/chia-blockchain.wiki.git
Cloning into 'chia-blockchain.wiki'...
remote: Enumerating objects: 3948, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 3948 (delta 49), reused 0 (delta 0), pack-reused 3846
Receiving objects: 100% (3948/3948), 1.08 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (2506/2506), done.
error: invalid path 'Is-my-farm-healthy?-I-am-not-finding-proofs.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

PS D:\github> cd .\chia-blockchain.wiki\
PS D:\github\chia-blockchain.wiki> git restore --source=HEAD :/
error: invalid path 'Is-my-farm-healthy?-I-am-not-finding-proofs.md'
```

I am using [Git for Windows](https://github.com/git-for-windows/git) version 2.31.1.windows.1 on Windows 10 Home (20H2).

**Comment by hoffmang9** [comment]
Fixed but also it is a wiki so don't hesitate to make changes.
