### ISSUE TITLE
what does it mean of CPU 100% ,80% or 150%?

### ISSUE THREAD

**Issue by muthubaby** [Chia-Network/chia-blockchain#2795]
which is best percentage of CPU?
For example, in plot finish it shows total time 20000s, CPU 120%, is this normal? Or we still can use more resource of the CPU

**Comment by climba03003** [comment]
If I understand correctly, 100% of CPU usage means one core. If it exceed 120%, it use the power more than one core.
100% = 1 Core / Thread of CPU
120% = 1.2 Core / Thread of CPU

Normally see this presentation on Linux.

**Comment by muthubaby** [comment]
> If I understand correctly, 100% of CPU usage means one core. If it exceed 120%, it use the power more than one core.
> 100% = 1 Core / Thread of CPU
> 120% = 1.2 Core / Thread of CPU
> 
> Normally see this presentation on Linux.

I'm using i9 10900k 10 core 20 threads 
Then 120% means I have fully used 1.2core and 2.4 threads ?

**Comment by climba03003** [comment]
> 
> 
> > If I understand correctly, 100% of CPU usage means one core. If it exceed 120%, it use the power more than one core.
> > 100% = 1 Core / Thread of CPU
> > 120% = 1.2 Core / Thread of CPU
> > Normally see this presentation on Linux.
> 
> I'm using i9 10900k 10 core 20 threads
> Then 120% means I have fully used 1.2core and 2.4 threads ?

It should be 1.2 Threads if I remembered correctly.

**Comment by hoffmang9** [comment]
Issues are not for tech support.
