### ISSUE TITLE
[BUG] Не синхронизируется 

### ISSUE THREAD

**Issue by ESKCOBAR** [Chia-Network/chia-blockchain#2796]
Синхронизация видимо включается, но дело дальше не заходит, сбрасывается и пишет не синхронизировано, прилагаю скрин. Так же хочу сказать что обновил до версии 1.1.2, всё работало до последних обновлений программы не понимаю в чём проблема, при этом засеивание  проходит без проблем.
![Нет синхранизацииjpg](https://user-images.githubusercontent.com/83168230/116084179-eddeea80-a6b6-11eb-9ba0-1a9b38a8d751.jpg)

![Нет синхранизацииjpg — копия](https://user-images.githubusercontent.com/83168230/116084282-0f3fd680-a6b7-11eb-856f-52ca2bee7994.jpg)

**Comment by angry-mammoth** [comment]
Попробуйте открыть порт 8444 (в настройках роутера, либо модема). Если не получится, то скорей всего порт закрыт у вашего провайдера.

**Comment by ESKCOBAR** [comment]
Всё получилось при смене провайдера.

**Comment by ESKCOBAR** [comment]
Да верно, сейчас работает только порт 8444, открываем его и всё отлично работает, но только в том случаи если этот порт открыт у вашего провайдера.
