### ISSUE TITLE
Бесконечное подключение к кошельку

### ISSUE THREAD

**Issue by Akim4XXX** [Chia-Network/chia-blockchain#2798]
После перезагрузки пк, при запуске Chia Blockchain бесконечное подключение к кошельку

**Comment by angry-mammoth** [comment]
Какая версия клиента?

**Comment by EvgeshaCryptofarmer** [comment]
1.1.2

**Comment by dimbuk0** [comment]
При установке кошелька висит бесконечное подключение более 12 часов

**Comment by EvgeshaCryptofarmer** [comment]
Перезагрузил ПК,всё пришло в норму

**Comment by Lardana** [comment]
Такая же проблема, но перезагрузкой не лечится. Версия 1.1.6

**Comment by ConstantineJ** [comment]
Такая же проблема 1.1.7
![image](https://user-images.githubusercontent.com/11784902/120935837-5638d700-c70d-11eb-9317-d0441faacc48.png)

**Comment by Lardana** [comment]
Как-то все смог пофиксить удаляя что попало. На 1.2 повторилась проблема но подобным способом не фиксится
