### ISSUE TITLE
How much RAM, and how many CPU threads does the node/daemon need?

### ISSUE THREAD

**Issue by corviato1** [Chia-Network/chia-blockchain#2800]
Also, what is the GPU load, if at all?

**Comment by HailongZhu** [comment]
It's about 10% on a 5600x, the CPU load is comparable to one plotter process.
GPU is not relevant (at least for now)

**Comment by corviato1** [comment]
> It's about 10% on a 5600x, the CPU load is comparable to one plotter process.
> GPU is not relevant (at least for now)

So like 2 threads then?
What about RAM?
Thanks, good to know about the GPU

**Comment by hoffmang9** [comment]
Not the place for tech support questions.
