### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YujinBii** [Chia-Network/chia-blockchain#2802]
At the end (plotting 100%) of sowing the site, Windows 10 crashes. At the same time, it gives an error: "An operating system wasn't found. Try disconnecting any drivers that don't contain an operating system"
This is repeated for the second time.
![photo_2021-04-26_16-44-58](https://user-images.githubusercontent.com/83204561/116095893-7b1f4080-a6b1-11eb-9676-1e39043914f5.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/83204561/116095999-91c59780-a6b1-11eb-96a6-ce75071e6487.png)
![Screenshot_2](https://user-images.githubusercontent.com/83204561/116096023-968a4b80-a6b1-11eb-8ae7-13a5c6174fba.png)
![Screenshot_3](https://user-images.githubusercontent.com/83204561/116096048-9c802c80-a6b1-11eb-94cc-e90946589f54.png)
![Screenshot_5](https://user-images.githubusercontent.com/83204561/116096148-b588dd80-a6b1-11eb-85fa-91e0718aaf6f.png)

**Comment by hoffmang9** [comment]
We know what this problem is and are working on a solution. This is a duplicate issue however.
