### ISSUE TITLE
[BUG] old ChiaPlot Directory does not exist WARNINGs

### ISSUE THREAD

**Issue by dial-888** [Chia-Network/chia-blockchain#2804]
I moved plot files from one drive to another and they got recognised in GUI farm, but I get WARNINGs in .chia\mainnet\log\debug.log

2021-04-26T13:23:17.315 harvester chia.plotting.plot_tools: WARNING  Directory: E:\ChiaPlot does not exist.

So I'm not sure if my plots from old ChiaPlot directory is actually farming. Any solution/advice?

Win10 / Chia 1.1.2

**Comment by qianmyth** [comment]
Has the service been restarted?

**Comment by hoffmang9** [comment]
Issues is not for tech support.

**Comment by dorkmo** [comment]
might restart computer?
