### ISSUE TITLE
Wondering of the Plots Passed Filter with the new release 1.1.2

### ISSUE THREAD

**Issue by lakymoon** [Chia-Network/chia-blockchain#2811]
<img width="746" alt="捕获" src="https://user-images.githubusercontent.com/83230629/116104245-dddd0000-a6e2-11eb-8941-240f52f74fb9.PNG">

Is that mean I have only half chance to win the XCH?

Thanks.

**Comment by hoffmang9** [comment]
Something is up with - probably - your remote harvester. Issues is not for tech support though.
