### ISSUE TITLE
[BUG]VERY SLOW!!!

### ISSUE THREAD

**Issue by leochang36** [Chia-Network/chia-blockchain#2812]
CPU：i3-10100
RAM：64GB
Disk：NVME 1T+16THDD（Through NFS to my NAS)
Environment：
windows 10 in ESXi7.0,Plot a file maybe need 50 HOURS....
I tested my SSD Speed and RAM speed all normally....
So,I don't know what problem with this plotting....
plotting one plot maybe 40+hours
Thanks!

**Comment by hoffmang9** [comment]
This is your computer and this is not a place for tech support.
