### ISSUE TITLE
we got 4791 plot files and got 0 coins 

### ISSUE THREAD

**Issue by chiafuns** [Chia-Network/chia-blockchain#2817]
hi all,
we have finished 4000 more plot files by many computers together(use the same fingerprint).
we got 1754 plot files and got 2 coins in 2021/4/22
we got 2376 plot files and got 2 coins in 2021/4/23
we got 2966 plot files and got 0 coins in 2021/4/24
we got 3312 plot files and got 0 coins in 2021/4/25
we got 4791 plot files and got 0 coins in 2021/4/26
what's the problem with me? could you help me fix the problem? Thanks!

**Comment by hoffmang9** [comment]
Issues are not for tech support.

**Comment by dorkmo** [comment]
are they all on the same network? Are the nodes synced?

**Comment by chiafuns** [comment]
yes!every computer use the same wallet ,all the nodes synced!

---Original---
From: ***@***.***&gt;
Date: Tue, Apr 27, 2021 01:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Chia-Network/chia-blockchain] we got 4791 plot files and got 0 coins  (#2817)




 
are they all on the same network? Are the nodes synced?

**Comment by dorkmo** [comment]
Do you see them passing the plot filter? sounds like something weird might be wrong.

**Comment by chiafuns** [comment]
we think we can get 8 coins one day,but we got 0 coin 3 days recently!



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 27, 2021 02:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Chia-Network/chia-blockchain] we got 4791 plot files and got 0 coins  (#2817)




 
Do you see them passing the plot filter? sounds like something weird might be wrong.

**Comment by dorkmo** [comment]
Check to see how many are passing the filter.
