### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Vaalerbonde** [Chia-Network/chia-blockchain#2821]
Stuck at Connecting to wallet 

i have tried to reinstall, turn on and off the computer, but it have not helped. 

what to do 
![Capture](https://user-images.githubusercontent.com/83236249/116117565-aa877a80-a6bc-11eb-8398-d310ddd2e0fc.JPG)

**Comment by Tanki90** [comment]
i have the same problem.

**Comment by hoffmang9** [comment]
Delete the peer databases in db/ and wallet/db/
