### ISSUE TITLE
[BUG] Not Synced on 1.1.2

### ISSUE THREAD

**Issue by jonnywindows** [Chia-Network/chia-blockchain#2822]
Not Synced.   First time I've had this issue in weeks! 
<img width="1025" alt="Screen Shot 2021-04-26 at 12 56 37 PM" src="https://user-images.githubusercontent.com/83238136/116121698-e1df3280-a68e-11eb-8f69-f859b1877a2e.png">

**Comment by dorkmo** [comment]
how many peer nodes are you connected to?

**Comment by jonnywindows** [comment]
[image: Screen Shot 2021-04-26 at 1.19.15 PM.png]

**Comment by jonnywindows** [comment]
<img width="993" alt="Screen Shot 2021-04-26 at 1 19 15 PM" src="https://user-images.githubusercontent.com/83238136/116124357-2f10d380-a692-11eb-8b73-247dbf9bf481.png">

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by jonnywindows** [comment]
it has 1 other node but thats it now.... It's not my network - I haven't changed settings /firewall is open and its been working fine for weeks!

<img width="1010" alt="Screen Shot 2021-04-26 at 1 43 05 PM" src="https://user-images.githubusercontent.com/83238136/116127070-6765e100-a695-11eb-923f-e9f239e08de9.png">

**Comment by jonnywindows** [comment]
It's kicked into life now - Thanks for your help!
