### ISSUE TITLE
[BUG] harvester keeps crashing when running on python3.9 (Ubuntu 21.04)

### ISSUE THREAD

**Issue by fiveangle** [Chia-Network/chia-blockchain#2826]
harvester keeps crashing

```
ProblemType: Crash
Architecture: amd64
Date: Sun Apr 25 17:44:00 2021
DistroRelease: Ubuntu 21.04
ExecutablePath: /usr/bin/python3.9
ExecutableTimestamp: 1617565124
ProcCmdline: chia_harvester
ProcCwd: /home/speedster/dev
ProcEnviron: 
ProcMaps:

[stacktrace hexdump contents redacted]

ProcStatus:
 Name:  chia_harvester
 Umask: 0002
 State: D (disk sleep)
 Tgid:  15158
 Ngid:  0
 Pid:   15158
 PPid:  14910
 TracerPid:     0
 Uid:   1000    1000    1000    1000
 Gid:   1000    1000    1000    1000
 FDSize:        64
 Groups:        4 24 27 30 46 121 132 133 1000 
 NStgid:        15158
 NSpid: 15158
 NSpgid:        14891
 NSsid: 14820
 VmPeak:         2460356 kB
 VmSize:         2427072 kB
 VmLck:        0 kB
 VmPin:        0 kB
 VmHWM:   101600 kB
 VmRSS:   101600 kB
 RssAnon:          90672 kB
 RssFile:          10928 kB
 RssShmem:             0 kB
 VmData:          390240 kB
 VmStk:      132 kB
 VmExe:     2628 kB
 VmLib:    12760 kB
 VmPTE:      532 kB
 VmSwap:               0 kB
 HugetlbPages:         0 kB
 CoreDumping:   1
 THP_enabled:   1
 Threads:       33
 SigQ:  0/31013
 SigPnd:        0000000000000000
 ShdPnd:        0000000000000000
 SigBlk:        0000000000000000
 SigIgn:        0000000001001000
 SigCgt:        0000000180004002
 CapInh:        0000000000000000
 CapPrm:        0000000000000000
 CapEff:        0000000000000000
 CapBnd:        000001ffffffffff
 CapAmb:        0000000000000000
 NoNewPrivs:    0
 Seccomp:       0
 Seccomp_filters:       0
 Speculation_Store_Bypass:      thread vulnerable
 SpeculationIndirectBranch:     always enabled
 Cpus_allowed:  f
 Cpus_allowed_list:     0-3
 Mems_allowed:  00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
 Mems_allowed_list:     0
 voluntary_ctxt_switches:       114106
 nonvoluntary_ctxt_switches:    43557
Signal: 6
Uname: Linux 5.11.0-16-generic x86_64
UserGroups: adm cdrom dip lpadmin lxd plugdev sambashare sudo
CoreDump: base64

[crash hexdump contents redacted]
```

Farm has approx 1000 plots across 28 plot directories

I have full standard Ubuntu crashdump but suspect there may be private keys buried within it so not uploading.  I can scrape any relevant info you want out of it as necessary if you can tell me what, if any, I need to redact out of the crashdump.

Thanks,

-=dave

**Comment by nirajpatel2402** [comment]
Did you find any workaround?

**Comment by fiveangle** [comment]
Nope.  I wrote a watchdog script to monitor the harvester and relaunch when it crashes

**Comment by fiveangle** [comment]
and just logged in while on vacation and found my watchdog script failed to restart, so 2000+plots have been sitting idle unfarmed the last 6 days 😭

**Comment by nirajpatel2402** [comment]
I made the following 3 changes.

I am doing a staggered start on a single SSD.
I also updated my bios of the MSI 490 A PRO motherboard.
I replaced my 4tb ssd with 2x 2tb. 

My ubuntu is no longer crashing. Most likely first 2 changes resolved my issue.

**Comment by fiveangle** [comment]
@nirajpatel2402 - thank you for your input but that your anecdotal results have zero relevance to the issue.  There is no mechanism for those two things to affect this issue.  I'm sorry.

**Comment by fiveangle** [comment]
DIdn't even stay up over a day this time.  From the silence on this crashing harvester issue, it's clear there is no interest in resolving so I supposed the only solution is to try other distributions until one is found that does not crash. 

![Screen Shot 2021-06-07 at 00 33 07](https://user-images.githubusercontent.com/2219447/120978529-6ced2700-c729-11eb-94b8-6c9289d46d2f.jpg)

**Comment by fiveangle** [comment]
.

**Comment by fiveangle** [comment]
I provided the actionable info but no one is interested in investigating, so i'll close this as i'm no longer interested either
