### ISSUE TITLE
Don't copy plot from the same HDD

### ISSUE THREAD

**Issue by Nitexus** [Chia-Network/chia-blockchain#2828]
Can you please add feature when HDD using as temporary directory and target HDD is the same, dont copy at last stage whole plot, but only change FAT allocation for the file? It will save 10-30 mins for plot at least.

**Comment by JordyBaylac** [comment]
which version are you using? this is already implemented afaik
check https://github.com/Chia-Network/chiapos/blob/baf4042f1c1adc484d54b41f17c959c421cab2be/src/plotter_disk.hpp#L372

**Comment by hoffmang9** [comment]
You can do this yourself by setting `-2` to the `-d` directory.
