### ISSUE TITLE
Feature request: Update farm overview to include distributed harvester information.

### ISSUE THREAD

**Issue by j4ys0n** [Chia-Network/chia-blockchain#2830]
As a user, I'd like to be able to see an accurate Farming overview in the GUI wallet that includes my harvesters running on separate machines.

Right now, the only place harvester information is displayed is in the "Last Attempted Proof" panel.

The overview should include a summed plot count and size.
The "Your Harvester Network" panel should show connections to other nodes/harvesters.

**Comment by hoffmang9** [comment]
Duplicate enhancement request. We know and agree.

**Comment by j4ys0n** [comment]
I might try to tackle this if that's ok. Mostly because I don't want to have to keep doing math to figure out the overview :)
I'm fully capable of this. If you wouldn't mind pointing out the relevant parts of the codebase that would be super helpful and would save me the time of searching for it. I already know how to run the wallet in a local dev env.

**Comment by hoffmang9** [comment]
I'll get you a roadmap in about an hour.

**Comment by hoffmang9** [comment]
Sorry for the delay. Start here to see how we're doing LCP - https://github.com/Chia-Network/chia-blockchain/blob/1f16bca87f038d883c051094088a588d11646c87/chia/harvester/harvester_api.py#L202

**Comment by j4ys0n** [comment]
honestly i was planning on doing this in the electron app if all the numbers are there. i'm assuming you guys are putting off the "proper" implementation because it's tedious or time consuming. i don't have time for that either, but i can add some numbers together on the front end if the data is available :)

**Comment by puffincreek** [comment]
@hoffmang9 , which ticket actually tracks this problem if this is a duplicate?

**Comment by hoffmang9** [comment]
Fixed in 1.2.0
