### ISSUE TITLE
When making plots can't connect to wallet[BUG]

### ISSUE THREAD

**Issue by valden1978** [Chia-Network/chia-blockchain#2832]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by lvcivs** [comment]
There's not enough info to help you, sorry.

Maybe you are having connection issues? Read: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by royimous** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Linux]
> * OS Version/Flavor: [e.g. CentOS 7.2]
> * CPU: [e.g. Intel Xeon 8175M]
> 
> **Additional context**
> Add any other context about the problem here.

Why would anyone try to help you when you don't even include the basic information the form asks for?
