### ISSUE TITLE
Different directories for parallel plots

### ISSUE THREAD

**Issue by lschong** [Chia-Network/chia-blockchain#2833]
Issue: Chia does not remember the temporary drive, uses the latest job instead.
Platform: Windows GUI

I am trying to launch multiple jobs to 2 different drives/directories.  For example, I sent 5 queued plots to drive A.  Then another 5  plots to drive B.  I check the log and they are correct.  However, after drive A completes the first plot, the second plot begins on drive B instead of drive A.

I'm not sure if this is intended but it prevents me from setting up multiple queued jobs for each drive.

**Comment by Muffexx** [comment]
Have you thought about using different queues?
The default queue is called "default" but you can use different ones. Otherwise all plots are added to the same queue.
When you "Add a Plot" you can set the "Queue Name" in the Advanced Options of 2 (Choose Number of Plots).

**Comment by lschong** [comment]
AH!  Learnt something new about queue name.  That should indeed solve my problem.  I will give it a whirl once the current plot completes.  Thank you!
