### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gringofer** [Chia-Network/chia-blockchain#2836]
![Captura de pantalla de 2021-04-26 15-33-27](https://user-images.githubusercontent.com/83243219/116134706-946ebf80-a6a6-11eb-8388-260108e2821e.png)
Hello good day.
I'm trying to create a plot on Ubuntu 20.04, I have a 500GB NVMe and a 500GB HDD, 16GB of RAM and a Ryzen 5 3600. When I start plotting, it stops at 2% and the log shows: " Only wrote 50703 of 226488 bytes at offset 4294916592 to "/media/fer/Parcelas te/Parcelas temporales/plot-k32-2021-04-26-15-14-eedacda76f1348d431402d18ca5d1ceed7c7d0567622b6c8f014631d44b35fab.plot.table1.tmp"with length 4294967295. Error 1. Retrying in five minutes."

Does anyone know how to fix it? Thank you

**Comment by lvcivs** [comment]
This usually happens when you run out of disk space. Make sure the disk where the temp folder is has enough free space.

**Comment by gringofer** [comment]
> Esto suele ocurrir cuando te quedas sin espacio en disco. Asegúrese de que el disco donde se encuentra la carpeta temporal tenga suficiente espacio libre.

Hi, thanks for your response.
If you have space, the disk is new ... finally I tried it in windows 10 and if it works, there I do not have that problem.

A shame because I had understood that Ubuntu was 20% faster.

Thanks!!
