### ISSUE TITLE
Connecting to wallet - infinitely

### ISSUE THREAD

**Issue by EvgeniyKorepov** [Chia-Network/chia-blockchain#2837]
After clicking Reload (Ctrl + R), does not connect to wallet.
I have waited for about 40 minutes, but there is no result.

![image](https://user-images.githubusercontent.com/35364901/116140577-319a1a00-a6e0-11eb-959d-3bd31e606199.png)

**Comment by Azothx** [comment]
same problem here...

**Comment by royimous** [comment]
You're on the old version. Update to 1.1.2 first then see if that resolves the issue.

**Comment by ESKCOBAR** [comment]
Всё верно обновитесь до версии 1.1.2, так же по возможности откройте порт 8444.

**Comment by EvgeniyKorepov** [comment]
> Всё верно обновитесь до версии 1.1.2, так же по возможности откройте порт 8444.

Same. The port is open, locally and from the internet.
![image](https://user-images.githubusercontent.com/35364901/116423494-683f7400-a849-11eb-952d-69b9cca44a34.png)

**Comment by DenisAlliswell** [comment]
Same problem, @EvgeniyKorepov how do you solve this one?

**Comment by EvgeniyKorepov** [comment]
> Та же проблема, @EvgeniyKorepov, как вы ее решаете?

I wait for a very long time, and then I try not to close the application)))
