### ISSUE TITLE
[BUG] Infinite loop: connecting to the wallet

### ISSUE THREAD

**Issue by CesarBarros** [Chia-Network/chia-blockchain#2841]
### **Infinite loop: connecting to the wallet**
After the computer restarts and the chia.app application is in an infinite loop: connecting to the wallet.

**To Reproduce**
1. I downloaded version 1.1.2;
2. Installed on Applications;
3. I opened Chia.app (1.1.2);
4. Synchronization has started;
5. Around 18k I received the error / [BUG] Not Synced;
6. I closed and reopened Chia.app and resynchronized;
7. At around 140k my computer crashed and restarted;
8. I opened Chia.app and did not leave the "Connecting to wallet" screen.

**Note:** This is the first time that I downloaded Chia.app (1.1.2), before I had not installed any other version on the computer.

Log
```tail -f ~/.chia/mainnet/log/debug.log```
```powershell
  File "websockets/protocol.py", line 803, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

2021-04-26T14:52:55.155 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-04-26T14:53:27.285 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x113e2dd30>
2021-04-26T15:59:33.669 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-04-26T16:04:56.634 full_node asyncio                 : ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x109760730>
2021-04-26T16:55:59.776 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-04-26T17:03:04.486 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 624, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 110.155.253.158
```

**Expected behavior**
Open the Chia.app application so that I can choose my wallet and continue synchronizing and immediately after creating the plots.

**Screenshots**
![Image of Error](https://i.ibb.co/yg4nwg1/Screen-Shot-2021-04-26-at-17-22-23.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave
- OS Version 10.14.6
- CPU: 2,9 GHz Intel Core i5
```python --version```: Python 3.7.3

**Comment by flynn-buc** [comment]
Similar issues here on macOS Big Sur, i9-9900k, python 3.9.2. I'm fully synced, but every so often I'll get kicked out of the UI & stuck on connecting to wallet screen.

My fixes so far: run `chia start -r waller`, then refresh the page with cmd+r. Generally works, but connection is slow and takes a long time.

Problem seems to occur more frequently the longer the UI has been open, and performance drastically decreases.

**Comment by ESKCOBAR** [comment]
Попробуйте открыть порт 8444, у самого были проблемы с подключением, после открытия порта проблема исчезла.

**Comment by FreeDooMF1** [comment]
> Попробуйте открыть порт 8444, у самого были проблемы с подключением, после открытия проблема исчезла.

какая на ккой ОС По установлено было? обновился, порт открыт, висит все равно (windows 10 с последнеми обновами)

**Comment by CesarBarros** [comment]
I managed to solve my problem: 🥳 🙌

I did the following.
1. Backed up the folder `~/.chia/mainnet/wallet/db`
2. I deleted the file `~/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_NUMBER.sqlite`
3. I opened chia.app (v.1.1.2) again

The application opened and connect wallet, but, got a problem with `Not Synced`
![Image of Not Synced](https://i.ibb.co/9sHWG99/Screen-Shot-2021-04-28-at-23-56-41.png)

1. I opened the file: `~/.zshrc`
2. I added the lines
```
export CHIA_ROOT=~/.chia
export PATH=/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon:$PATH
```
3. update zshrc: `source ~/.zshrc`
4. I unlocked door `8444` in the mold; suggestion from @ESKCOBAR 
5. I checked that port 8444 was unlocked [check your door here!](https://www.yougetsignal.com/tools/open-ports/)
![Image of open port](https://i.ibb.co/fCvrGZZ/Screen-Shot-2021-04-29-at-00-03-39.png)
6. I opened chia.app (v.1.1.2) again
![Image of Syncing](https://i.ibb.co/Y7szmxK/Screen-Shot-2021-04-28-at-23-57-07.png)
7. After awhile he resynchronized

I want this to help other people.
let me know if it helped you! leave a review! 👍
