### ISSUE TITLE
[BUG] Full Node drastically reduce system performance (blocking CPU frequency at low value)

### ISSUE THREAD

**Issue by adamsky-01** [Chia-Network/chia-blockchain#2845]
My system performance drastically slows down when Chia Blockchain 1.1.2 is running under Windows (GUI), no other heavy processes are running in the background. Once it's OFF the system performance will back to the full speed. I can do plotting without any issue on this system with PowerShell, single plot - 4h 31m. It seems like Chia GUI is locking my CPU frequency at low value and its affecting everything else. 

When Chia Blockchain 1.1.2 is running (no plotting or farming, just syncing, very slow syncing) under GUI Windows 10 the Ryzen CPU stucks at low frequency:
![image](https://user-images.githubusercontent.com/60489596/116151746-eb8f8700-a6dc-11eb-8b14-1f9b7d2e69ef.png)

My SSD 970 EVO NVMe M.2 500GB slows down a good few times:
![image](https://user-images.githubusercontent.com/60489596/116152705-2645ef00-a6de-11eb-8ad6-66b338925f06.png)

- OS: [Windows]
- OS Version/Flavor: [10 Pro]
- CPU: [AMD Ryzen 5600X]

**Comment by fiveangle** [comment]
`<developereque response>works on my box !</developeresque response>` 😉 3600 w/CTR2.0:

![3600](https://user-images.githubusercontent.com/2219447/116167522-3b5a5800-a6b5-11eb-8a99-3fc57fdcc1f6.png)

**Comment by adamsky-01** [comment]
> `<developeresque response>works on my box !</developeresque response>` 😉 3600 w/CTR2.0. PM953 NVMe SSD, MSI B450 G AC+, 6x concurrent plots:
> 
> ![3600](https://user-images.githubusercontent.com/2219447/116167522-3b5a5800-a6b5-11eb-8a99-3fc57fdcc1f6.png)

Are you running it with Chia GUI or CLI?

**Comment by fiveangle** [comment]
cli but the gui launches the cli process (you can see it in the logs) so it seems more a problem with your specific system rather than a problem with chia

**Comment by adamsky-01** [comment]
I can run everything from CLI (chia start all) and I do not have this issue. So it's GUI which causing above described problem.

**Comment by fiveangle** [comment]
i used the gui with identical results but if its different for you at least you've narrowed it down to not being the plotting process

**Comment by ByronAP** [comment]
check your bios settings, there is no way a cpu should go down to such a low speed even at dead idle. Turn off frequency scaling and see what happens.

**Comment by adamsky-01** [comment]
Nothing to do with bios as the CPU frequency boosting well in any other program.

**Comment by afromanplay** [comment]
> My system performance drastically slows down when Chia Blockchain 1.1.2 is running under Windows (GUI), no other heavy processes are running in the background. Once it's OFF the system performance will back to the full speed. I can do plotting without any issue on this system with PowerShell, single plot - 4h 31m. It seems like Chia GUI is locking my CPU frequency at low value and its affecting everything else.
> 
> When Chia Blockchain 1.1.2 is running (no plotting or farming, just syncing, very slow syncing) under GUI Windows 10 the Ryzen CPU stucks at low frequency:
> ![image](https://user-images.githubusercontent.com/60489596/116151746-eb8f8700-a6dc-11eb-8b14-1f9b7d2e69ef.png)
> 
> My SSD 970 EVO NVMe M.2 500GB slows down a good few times:
> ![image](https://user-images.githubusercontent.com/60489596/116152705-2645ef00-a6de-11eb-8ad6-66b338925f06.png)
> 
> * OS: [Windows]
> * OS Version/Flavor: [10 Pro]
> * CPU: [AMD Ryzen 5600X]

dude how you get a plot every 4 hours???! i’ve got amd 3700x 32 gb ram 3200 and 2 1tb mp600 gen4 but still struggling!! any advice??? pls

**Comment by adamsky-01** [comment]
One plots takes usually between 4h15m to 4h40m on my PC: Ryzen 5600x, RAM: 32GB (3200MHz, 14CL), Samsung 970 EVO 500GB. No OC (excluding XMP RAM profile) or any special tricks. I'm running plot under Windows 10 PowerShell: `chia plots create -k 32 -b 4000 -t D:\plots -d E:\`

**Comment by afromanplay** [comment]
thank dude , i’ll try it  , are u doing in parallel ?and if yes , how long did u put for daly  
thanks anyway for ur respond

**Comment by adamsky-01** [comment]
I'm just waiting till Tuesday for much better components to start a massive ;) parallel plotting.

**Comment by afromanplay** [comment]
the best i could get is 7 plot every 8 hour with this components and single plot every 6 best case scenario  ! with this components i expected 3 tb a day or am i just dreaming of it??

**Comment by afromanplay** [comment]
i think there is something wrong with the ssd either the over heating or the way i made them raid0

**Comment by adamsky-01** [comment]
I just suspect it might be a SSD thermal throating in your case. I've just a little experience with all this chia thing, so I'm not the best person to give you an advise.

**Comment by afromanplay** [comment]
still a big help ;)
