### ISSUE TITLE
Problem to connect the wallet

### ISSUE THREAD

**Issue by Azothx** [Chia-Network/chia-blockchain#2846]
![image](https://user-images.githubusercontent.com/13544926/116158409-03f3a780-a6c5-11eb-84f6-3c0ba5b150ee.png)

I tried to uninstall and install the application again, but without success

![image](https://user-images.githubusercontent.com/13544926/116158594-4f0dba80-a6c5-11eb-9643-5c0cdb15ab58.png)

I also noticed the high memory consumption

**Comment by hoffmang9** [comment]
Known issue being worked on and a duplicate.
