### ISSUE TITLE
[BUG][WINDOWS][v1.1.2.] Error 13

### ISSUE THREAD

**Issue by Gantris3** [Chia-Network/chia-blockchain#2852]
When upgrading to version 1.1.2. when entering again I get error 13 and it does not synchronize my plots, restart the pc, reinstall chia, but still the error continues. Anyone know anything about this?

![115939321-c34d2180-a46b-11eb-9e5d-c51f634f8a04](https://user-images.githubusercontent.com/83099154/116165673-597e8300-a6ca-11eb-9feb-cf67f9f56c23.jpg)

**Comment by hoffmang9** [comment]
It is a bad error message fixed in the next version. Something is wrong with one of your plot directories.

**Comment by Gantris3** [comment]
It is a bad error message fixed in the next version. Something is wrong with one of your plot directories.

**Comment by Evanbr12** [comment]
If you changed the HDD sata port sata the directory was, go back to the sata port where the directory was created.

**Comment by Evanbr12** [comment]
Corrected my problem by returning the hdd to the sata port where the directory was created.

**Comment by Gantris3** [comment]
> Corrected my problem by returning the hdd to the sata port where the directory was created.

I think that is the provisional solution, I hope that in future updates they will solve that, Thank you Evanbr12 you were very helpful
