### ISSUE TITLE
More 200 connections yesterday.today at zero

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#2867]
Hello
Yesterday I went to sleep and had the GUI running with more than 200 node connections. Fully synchronized (the envy of my neighbors).
this morning when i wake up i'm out of sync. zero nodes.
keeps plotting normal but does not sync.
How can I know what has happened?
Tnx

**Comment by ESKCOBAR** [comment]
попробуйте обновить до версии 1.1.2, так же откройте порт 8444

**Comment by thentd** [comment]
这种很是正常，111、112都有这问题，105的时候 都是正常的，升级后 就不正常了，路由器开不开8444端口105都是正常的，升级就不行了，
