### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GiverDead** [Chia-Network/chia-blockchain#2870]
Compressing tables 4 and 5 at Second computation

Only wrote 4096 of 1048576 bytes at offset 230686720 to "/media/capuchin/plot-k32-2021-04-25-06-21-1cb4eac56381967172da949cc66b6e83b26c5606065a0e46b7210d2f467acd1b.plot.p3s.t5.sort_bucket_002.tmp"with length 230690816. Error 1. Retrying in five minutes.    
After 40 hours of plotting

[plotting.log](https://github.com/Chia-Network/chia-blockchain/files/6382014/plotting.log)

- OS: Raspberry OS 64
- Raspberry Pi 4 B
- FS : ntfs

**Comment by grinbucks** [comment]
I had this issue when the temp SSD had no space left. Was there enough space in yours?

**Comment by GiverDead** [comment]
> I had this issue when the temp SSD had no space left. Was there enough space in yours?

Yes i have 155 Gb used of 450 Gb

**Comment by GiverDead** [comment]
I bought new SSD disk 480Gb and format in ntfs
Now It's Failed on Phase 1 Table 3 Bucket 18

**Comment by mani00132** [comment]
Hey there I have exactly the same problem, I am on ubuntu desktop gui version. For me it always stops at bucket 37 of the first table, is there any solution?

**Comment by GiverDead** [comment]
> Hey there I have exactly the same problem, I am on ubuntu desktop gui version. For me it always stops at bucket 37 of the first table, is there any solution?

No, i install Ubuntu Desktop with GUI. Now crushed at Phase 1 Table 4 Bucket 2 - 11...

**Comment by GiverDead** [comment]
> Hey there I have exactly the same problem, I am on ubuntu desktop gui version. For me it always stops at bucket 37 of the first table, is there any solution?

https://github.com/Chia-Network/chia-blockchain/issues/3936 - check comments here. Try to use 1/3 of your RAM on device.
I started new plot now with 1GB of 4GB RAM, will be try..

**Comment by mani00132** [comment]
I cant take 1/3 of my ram as I am plotting 8-12 plots in parallel and 1 of 4 is 1/4 lol

**Comment by GiverDead** [comment]
I was install windows on rpi
