### ISSUE TITLE
Several issues need to be confirmed here

### ISSUE THREAD

**Issue by cppfuns** [Chia-Network/chia-blockchain#2873]
Several issues need to be confirmed here
1. Does multiple Farmers load the same plots affect the reward?
2. How many plots can be loaded at most for a single harvester on the premise that the efficiency is satisfied,
3. Is it allowed to run multiple harvesters on the same machine?
4. Is it allowed to run multiple Farmers on the same machine?

**Comment by hoffmang9** [comment]
No tech support in Issues. Keybase or Discussions.

**Comment by cppfuns** [comment]
Can you reply first? Wait anxiously.
For chia, I believe that the main battlefield is still China, but it is forbidden to use the Chinese Internet Keybase or Discussions, even if the VPN is used. Hope to have a wechat contact

**Comment by dorkmo** [comment]
A plot can only win once per block, so making a copy does not help.

**Comment by cppfuns** [comment]
How many plots can be loaded at most for a single harvester on the premise that the efficiency is satisfied,

**Comment by dorkmo** [comment]
not sure thats a pretty advanced question, you might get on keybase and ask
