### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oinhuang** [Chia-Network/chia-blockchain#2878]
After digging for many days, there is still no gain. This character will appear every time you open the wallet. what is the reason? Thank you/
![0427_3_recompress](https://user-images.githubusercontent.com/35126084/116197080-d7906780-a766-11eb-8dad-06769de8869e.jpg)
![0427_2_recompress](https://user-images.githubusercontent.com/35126084/116197088-d95a2b00-a766-11eb-9cd2-e48a9e3d4f1f.jpg)
![0427_1_recompress](https://user-images.githubusercontent.com/35126084/116197093-dbbc8500-a766-11eb-8371-79fd5e2dc7c0.jpg)

- OS: [e.g. W10]

- CPU: [e.g. Intel i9/10940k

**Additional context**

**Comment by Grokzen** [comment]
This is how solo mining works. You are not part of a pool so there is no constant small payouts like there is in ETH with a pool or BTC with a pool for example.
Think of this mode of farming solo as just taking 1 or 2 graphics card and just start to solo mine ETH outside a pool, you might be super lucky and get one eth block in 1 week or in 3 years. The same thing applies here. There is no guarantees just a lottery on who gets the coins.

**Comment by denisprovost** [comment]
yes, but in this case why the pools are not available for us?

**Comment by hoffmang9** [comment]
Not out yet.
