### ISSUE TITLE
[BUG]full node status is well，but the wallets status is not synced!

### ISSUE THREAD

**Issue by threebowrice** [Chia-Network/chia-blockchain#2884]
**Describe the bug**
[BUG] full node status is well，but the wallets status is not synced!
full node status is good:
![111](https://user-images.githubusercontent.com/62165712/116214070-52ff1280-a781-11eb-9459-89d2217fc251.png)

but the wallets status is not work!!!
![222](https://user-images.githubusercontent.com/62165712/116214172-69a56980-a781-11eb-9661-ad65c1a98965.png)

**Expected behavior**
Will this situation affect mining?

if it is a trouble ,how to fix it ? tks

**Comment by foreverDC** [comment]
I have the same problem,in this situation can i get reward?

**Comment by michaelpalumbo** [comment]
it appears that i have the same issue on Raspbian CLI

**Comment by MBadberg** [comment]
same here. It switches every now and then to synchronizing for about half a second.

![image](https://user-images.githubusercontent.com/15139464/116519279-9a94b400-a8d1-11eb-8732-048b4d3b3ff1.png)

Are there any logs, we could provide? I found no logs or other information yet.
