### ISSUE TITLE
[BUG] Ploting error in Line 176

### ISSUE THREAD

**Issue by bw-man** [Chia-Network/chia-blockchain#2889]
**Describe the bug**
i try to plot and get this error in log. I use the version 1.1.2

**To Reproduce**

**Expected behavior**
i try to plot and get this error in log.

**Screenshots**

![error_log_version112](https://user-images.githubusercontent.com/83279067/116222024-78bef400-a74e-11eb-9591-c96311bb4f70.JPG)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: 
- CPU: Intel i9-10900K

**Additional context**

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#my-plotting-attempt-ended-with-runtimeerror-bad-allocation
