### ISSUE TITLE
[BUG] What can make syncing crazy fast?

### ISSUE THREAD

**Issue by darwinjobchia** [Chia-Network/chia-blockchain#2890]
windows 10
i3-8100
1T SSD
DDR4-2400 16G

I have plotted 1T size , unfortunatly  the wifi interupt and stop,  I need to do re-syncing, it took me almost 24 hours to completed syncing. What can make it faster? better cpu or faster internet? or all same?

**Comment by wanghongqi8548488** [comment]
You can replace the node to solve this problem

**Comment by darwinjobchia** [comment]
it can be syncing, I mean how to make it faster

**Comment by wanghongqi8548488** [comment]
How fast are you going? My synchronization was very slow at that time. Later, I changed a node and it was much faster

**Comment by darwinjobchia** [comment]
My height is 193539, it is syncing from the 0 point, when it reaches half of it, it almost took me half day

**Comment by darwinjobchia** [comment]
so why I am asking, a better cpu or better internet can make it syncing faster?

**Comment by wanghongqi8548488** [comment]
It has nothing to do with CPU, but the node relationship of the block is relatively large

**Comment by darwinjobchia** [comment]
if you got 20 T size hard disk plotted, once you got internet mess up, you need to spend a week to get syncing back ?

**Comment by darwinjobchia** [comment]
辛辛苦苦耕了20T, 不小心一個斷網那不就要從頭開始同步一星期?

**Comment by Mlalosevic** [comment]
try : chia show -a (IP:8444) - just add as much as (IP adresses) you can get from friends who are sync on full node. They can check it with: chia show -c -s . I had lot of issues with a harvester and needed to restart whole comp becuse harvester process could not been killed  (even -9 did not worked). Then sometimes the sync would take really long time and wallet even more. I used as much IP adresses I could get and it just hooked to one and then the sunc was really fast.

**Comment by lipalong** [comment]
The sync speed depends on cpu speed.
