### ISSUE TITLE
[BUG] chia does not seed the disk

### ISSUE THREAD

**Issue by 4abick** [Chia-Network/chia-blockchain#2891]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by lvcivs** [comment]
Low effort bug reports are getting lower.
