### ISSUE TITLE
This version of Chia is no longer compatible with the blockchain and can not safely farm.

### ISSUE THREAD

**Issue by Richardszwz** [Chia-Network/chia-blockchain#2898]
When all is well, this prompt suddenly appears and the status shows Not Synced.

**Comment by gitsang** [comment]
update to 1.1.2

**Comment by climba03003** [comment]
At least update to 1.1.0

**Comment by Richardszwz** [comment]
i have updated to 1.1.2 and fixed the issue. Thank so much!
