### ISSUE TITLE
[BUG] Forced cancellation of plot creation 

### ISSUE THREAD

**Issue by MikhailZelenkov** [Chia-Network/chia-blockchain#2900]
Really need a button action to cancel the creation of a new plot.

**Comment by darwinjobchia** [comment]
yes, it stops at 15% for a long time, but no way to delete it

**Comment by denisprovost** [comment]
Stop chia, clean content of ssd temporary, restart chia.

**Comment by bw-man** [comment]
i have the same bug. I have version 1.1.2 and windows 10 and in create plot, in action you have the button show log, and delete.
the delete is grey, and i can not use it.
Why ?

**Comment by sargonas** [comment]
The Delete Plot function in the GUI was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21
