### ISSUE TITLE
[BUG] Статус полного узла Не синхронизирован

### ISSUE THREAD

**Issue by alexJew322** [Chia-Network/chia-blockchain#2904]
Перерыл кучу форумов, но ничего кроме как открыть порт 8444 не нашел, но он у меня по дефолту открыт, все было норм, с 25го числа висит статус не синхронизирован и все,ничего не помогает, есть решение какое то?, переустановка,перезапуски компа и тд и тп ничего не дают. Мб просто ждать некст обновления?
![d7SErac1KQA](https://user-images.githubusercontent.com/83288564/116247717-cc900400-a773-11eb-9ea9-0b9e45964627.jpg)

**Comment by Mlalosevic** [comment]
What version you are running? add IP adresses as much as you can remember it will speed the sync. Do not panic if the wallet sync later on

**Comment by baybekovtimur** [comment]
Решил проблему синхронизации с помощью NO-IP.

**Comment by alexJew322** [comment]
> Решил проблему синхронизации с помощью NO-IP.

можно по подробнее

**Comment by baybekovtimur** [comment]
> > Решил проблему синхронизации с помощью NO-IP.
> 
> можно по подробнее

Пробросил порт 8444 на роутере не помогло. потом зарегистрировался на сайте No IP установил программу DUC.  Ввел туда учетную запись No IP. Потом на сайте No IP в меню No IP hostname изменил белый IP адрес на локальный IP. в программе CHIA добавил node-eu.chia.net;8444 после этого пошла синхронизация.
![Безымянный](https://user-images.githubusercontent.com/83324835/116438932-65a04700-a868-11eb-8b9a-ac9048655cc5.png)

**Comment by baybekovtimur** [comment]
![Uploading Безымянный.png…]()
