### ISSUE TITLE
[BUG] Proof of Sync. ??

### ISSUE THREAD

**Issue by adamsky-01** [Chia-Network/chia-blockchain#2906]
The last few days all my chia resources like time, hardware are wasted on syncing. My 8444 port is open (verified) but it seems like syncing will take forever. Even when connected to introducers syncing is extremally slow. 
Is there any official comment on this, like ...stop using version 1.1.2, it will never sync. or this version only works under linux, etc.?  

I was planning to do plotting but instead I'm trying to sync the last few days.

![image](https://user-images.githubusercontent.com/60489596/116252199-41a90c80-a767-11eb-8e57-6669fe14c309.png)

**Comment by sunyao920807** [comment]
You may be in multiple NAT, you can try to change to public IP address

**Comment by adamsky-01** [comment]
> You may be in multiple NAT, you can try to change to public IP address

It cannot be a case if all port testers reporting that the port 8444 is open on my IP, right?
