### ISSUE TITLE
Plots not synchronizing

### ISSUE THREAD

**Issue by DarkRiverBeats** [Chia-Network/chia-blockchain#2908]
My node is connected but my status is: Not Synced. The node quit downloading blocks on 4/23. I have restarted the node and recooted my device a number of times. The node was funstioning fine until the 23rd so I do not think my router is blocking the traffic. Does anyone have any idea about what might be happening?

**Comment by royimous** [comment]
This is not the place to get support. Read the FAQ for proper support channels.

**Comment by dorkmo** [comment]
probabbly need to update the software though

**Comment by DarkRiverBeats** [comment]
Thank you dorkmo! That was it. I'll be sure to manually check for updates in the future.
