### ISSUE TITLE
[BUG] Not found Plots, after switching the SSD

### ISSUE THREAD

**Issue by Parkey18** [Chia-Network/chia-blockchain#2917]
For a better mining process I changed my M.2 SSD 1 TB to a 2TB. And had to reinstall windows. After installing Chia again, and it fully synced, my **plots couldn`t be found** after setting the right directory.

All I see under the tab "Plots" in the GUI is "**Not found plots. Caution, deleting these plots will delete them forever. Check that the storage devices are properly connected.**"

There are 29 Plots I can`t use right now. I worked for days to get 29 and now I am crushed. 

**What I tryed:**
-> install chia.exe again
-> install an older version of Chia.exe
-> deleting the .chia folder 
-> Crying and rolling on the floor

I used Windows 10, and the GUI.

![Unbenannt](https://user-images.githubusercontent.com/83296039/116267285-91460300-a77c-11eb-8daa-b34b2a2fc306.jpg)

**Comment by lvcivs** [comment]
Have you checked the file `config.yaml` ? Check for `plot_directories` in that file, you might have an old path in there.

**Comment by Parkey18** [comment]
Can you tell me, where I can find this file ?

**Comment by Crypto-78** [comment]
Follow... I have the same problem 😭

**Comment by lvcivs** [comment]
Is it possible that you are on a different set of keys after reinstalling? The plots are tied to your keys.

**Comment by Parkey18** [comment]
> Is it possible that you are on a different set of keys after reinstalling? The plots are tied to your keys.

The key is the same. I always had one and registered it with this 20 words. So it should be the same.

**Comment by Crypto-78** [comment]
I have installed the software again, restarted the PC and now everyone can see it

**Comment by Parkey18** [comment]
Mhh, doesnt worked for me :(

**Comment by Alexkizz82** [comment]
Same bug...
