### ISSUE TITLE
[BUG] can't sych and add node failed!

### ISSUE THREAD

**Issue by FireLoveInIce** [Chia-Network/chia-blockchain#2918]
![image](https://user-images.githubusercontent.com/32660493/116268638-1565ae00-a7b0-11eb-9091-5463b8877816.png)
![image](https://user-images.githubusercontent.com/32660493/116268659-1991cb80-a7b0-11eb-85b2-543ad1712e48.png)
nothing happend after i do that，help！

**Comment by Mlalosevic** [comment]
Just add IP adresses - ask friend who are synchronized. It will take time . Even more for wallet
