### ISSUE TITLE
[BUG] Wallet İs Not Connected

### ISSUE THREAD

**Issue by Kusey86** [Chia-Network/chia-blockchain#2922]
I cannot connect my wallet and start chia 

This console error ı have.

![image](https://user-images.githubusercontent.com/83300326/116276475-3ff23f80-a78d-11eb-9287-8fa05006a7d5.png)

**Comment by jeremytiu** [comment]
same problem here...

**Comment by royimous** [comment]
This is not the place to get support. 

Update to 1.1.2

**Comment by Kusey86** [comment]
anyone help ?

**Comment by Kusey86** [comment]
Iııııöm

**Comment by Kusey86** [comment]
> same problem here...

can u solve?

**Comment by royimous** [comment]
This is not a bug. Close this. Read the FAQ to see the proper support channels.
