### ISSUE TITLE
Still having issues connecting in GUI

### ISSUE THREAD

**Issue by nitram-ydna** [Chia-Network/chia-blockchain#2930]
Soon arriving at May 3rd and just updated to newest release.
Lo and behold...same problem showing up as before.

I do not know what is the problem, but ever since 1.0.1 or 1.0.3, the GUI suddenly loses connection. 
Then, when I try to reload, the GUI just hangs indefinitely...
It is extremely frustrating, since the only way to resolve the issue is to restart GUI.
Only problem is that I cannot see where my plots are and if they are still plotting, farming or anything else.

This problem needs urgent resolve, most people prefer a GUI...
An I have already tried the CLI daemon, it is not any better in this respect.
The issue is with apparently with json file, but I have exhausted all workarounds to resolve this.

![chia112_hanging](https://user-images.githubusercontent.com/80907812/116290852-d45ba280-a78b-11eb-8d2b-ba97a3ed7758.PNG)

**Comment by jeremytiu** [comment]
same problem here...

**Comment by Mlalosevic** [comment]
update to latest one, sync it first to the full node (you can add some IP adresses to speed it up). Wallet will sync bit later, do not worry. Had same issue couple of times

**Comment by royimous** [comment]
This isn't the place to get support. Read the FAQ on how to get support.

**Comment by nitram-ydna** [comment]
Read the post.
It's already newest version, so that's not gonna do any good.
Adding IPs doesn't help once the node loses sync with network, I know, because I used to do that as a workaround. Now, it doesn't work anymore. 

Support? 
I am reporting an issue. An issue that continues to be issue, even when we are closing in on market launch. 

The issue here is two-fold: 
1. The node loses sync suddenly. 
2. Trying to reload results in an endless loop in the script, upon which the GUI cannot reroute to main. 

These are issues that needs resolve. Not something that support can solve for each user.
