### ISSUE TITLE
https://github.com/ethereum/go-ethereum/issues/22646#issue-855143390[BUG]

### ISSUE THREAD

**Issue by linhhai997** [Chia-Network/chia-blockchain#2931]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by royimous** [comment]
There's nothing here. Close this.
