### ISSUE TITLE
How can I  reconnect the GUI to the chia plott process?

### ISSUE THREAD

**Issue by tkmbe99** [Chia-Network/chia-blockchain#2935]
Hello

Mi GUI crashed.
The chia plotting process is still working but after opening the GUI I have no data avaiable.
So I do not have any idea who long would it take to terminat (first plott generation) and I don't know if the process
will leave reallt a valid plot at end...
So is there any solution to attach the process again to the GUI?
No one had this problem?

**Comment by royimous** [comment]
This is not the place to get support. Look at the FAQ to find the proper support channels.

**Comment by dorkmo** [comment]
a lot of peoples gui's are crashing because of rpc errors, you might search the repository and see if you are having a similar issue

**Comment by sargonas** [comment]
If the GUI crashes but your plotting is still running in the background, it's likely that your plots will complete on their own so long as you do not kill their processes or restart your system.  That said, I'm not aware of any method at this time that would allow you to reconnect the orphaned processes to the GUI

*Migrating this to the support discussions
