### ISSUE TITLE
OpenSuse Support

### ISSUE THREAD

**Issue by tkmbe99** [Chia-Network/chia-blockchain#2936]
Hello

I'm interested in an OpenSuse version and can contribute with some help.
Is there any interest?

**Comment by garyhkirk** [comment]
You might get a response here but it's probably better to offer the help on the Keybase group, https://keybase.io/team/chia_network.public

**Comment by aqk** [comment]
Thanks @garyhkirk 

@tkmbe99, please join the `#dev` channel on keybase.

We'll be happy to merge complete working installers (install build scripts for Linux) or modifications to the install scripts that don't break existing platforms, and to help to the extent that we can.

Thank you!

**Comment by tkmbe99** [comment]
Ok thansk will have a look tomorow there
