### ISSUE TITLE
Unable to retrieve unfinished temporary plots. This is a big problem in the event of a power outage or equipment problems. This should be corrected immediately.[BUG]

### ISSUE THREAD

**Issue by mitora1** [Chia-Network/chia-blockchain#2937]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by znsoftm** [comment]
Nod.

**Comment by royimous** [comment]
This is not a bug. Close this.
