### ISSUE TITLE
move instead of copy

### ISSUE THREAD

**Issue by chriszahrt** [Chia-Network/chia-blockchain#2941]
It would be hugely beneficial to have the program move the complete plot once finished instead of copied.  Would accomplish the same thing and be instant on same drive temp and store locations.  I know same drive setups are not recommended but they get the job done.  Just recommending a way to get it done faster.  Or at last give users the option to move vs copy or maybe do it when same drive situations are auto detected.

**Comment by aqk** [comment]
Hello, Thank you for your comment. We definitely agree.

The reason we are moving slowly on this one is that there is a bit of complexity when you consider the number of platforms we support. Some libraries make it easy, but are not supported everywhere. Some OSes have ... complexities about mount points.

This one is definitely on our to do soon (after pooling, better peer connectivity, and multi-sync).

Thanks for your input!
