### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by goldenwolf1971** [Chia-Network/chia-blockchain#2942]
I cannot add a new plot directory. Nothing happens after selecting a plot directory.  

- OS: Windows 10 Pro
- OS Version/Flavor: 20H2
- CPU: AMD Ryzen 7 3800X

**Comment by Mlalosevic** [comment]
First try in file manager do you see it. Then try to add a plot . It worked form me

**Comment by royimous** [comment]
Learn to use PowerShell and the CLI. You get way more control and can actually see what is going on.

**Comment by sargonas** [comment]
Tagging this issue for migration to a discussion. Apologies in advance, but you will be best served by moving this over there and out of the issue tracker, where the community can better assist you. (Ideally the issue tracker should be used to focus on bugs and development problems that need to be addressed, with general user support handled in Discussions and Keybase)

^MigrateToDiscussion
