### ISSUE TITLE
[BUG] Failed to open (invalid plots)

### ISSUE THREAD

**Issue by maximus1218** [Chia-Network/chia-blockchain#2945]
After every plot gets finished, I am unable to farm the plot file. I have checked my keys, changed my plotting tactics, yet every single plot is invalid and unable to farm. What causes this to happen and how should I go about fixing it?

I am on windows OS, plotting on an SSD, and putting plot files on an external USB.

I also noticed that the plot files are completing the 4th phase in the log, and are remaining loaded at 100% for about five hours before they all end up in the Invalid Plots list.

**Comment by royimous** [comment]
Why would anyone help you when you haven't taken the time to fill out the basic info bug form?

**Comment by lvcivs** [comment]
What does `chia plots check` return?

Are there any error messages in the log file?

**Comment by sargonas** [comment]
adding to the above response, if you are still having this issue.... knowing the output from `chia plots check` as well as editing your config.yml to change log level from WARNING to INFO may result in some extended context in the log file. Please share both of those here and I might be able to point you in the right direction.

(Also moving this over to the community support discussions area)
