### ISSUE TITLE
Window GUI crash and ploting program is still running [BUG]

### ISSUE THREAD

**Issue by jackykwandesign** [Chia-Network/chia-blockchain#2948]
**Describe the bug**

Chia blockchain window application crash and disappear and ploting program is still running.
This is the bug report from window's event

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-04-27T22:26:23.5574317Z" /> 
  <EventRecordID>1445</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-4HK3UOF</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Chia.exe</Data> 
  <Data>1.1.2.0</Data> 
  <Data>607608dd</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.906</Data> 
  <Data>2f2f77bf</Data> 
  <Data>e0000008</Data> 
  <Data>0000000000034b59</Data> 
  <Data>369c</Data> 
  <Data>01d73afbb095589c</Data> 
  <Data>C:\Users\3990x\AppData\Local\chia-blockchain\app-1.1.2\Chia.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>a7890790-d97d-406b-8411-a40492d2ae13</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

Mining:
29*K32 parallel with 12 minutes delay per SSD + HDD
total 58 plot at the same time

Room is with air-conditioner and CPU temp between 67-74 degree celcius
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: window
- OS H2 latest
- CPU: 3990x, 256GB RAM, 2 * p4610 7.6TB SSD

**Additional context**
This also happened to my 5900x with 64GB RAM and 2 * 970 evo plus too

**Comment by zyz0110** [comment]
I met the same bug this morning. what should I do? open the gui and let the background plotting run?

**Comment by jackykwandesign** [comment]
> I met the same bug this morning. what should I do? open the gui and let the background plotting run?

change to CLI, problem solved
