### ISSUE TITLE
Memory leak in daemon.exe in v1.1.2 when plotting with the Windows GUI

### ISSUE THREAD

**Issue by Eldaw** [Chia-Network/chia-blockchain#2949]
The issue with the memory leak in daemon.exe when plotting with the GUI is still present in v1.1.2.

On my Windows full node, which I was using for plotting with the GUI, I noticed the GUI had become unresponsive / out-of-date. When I checked Task Manager I saw that daemon.exe was using 5GB RAM and climbing.

I know one of the developers mentioned on Keybase that there was a known issue with a memory leak in daemon.exe when using the GUI for plotting. But I thought that was past tense. I'm logging this issue to let you know that it's still a problem in v1.1.2. It seems you can't use the Windows GUI for much plotting before daemon.exe eventually consumes all your RAM and the GUI stops working.

**Comment by MasterAssailant** [comment]
Just wondering: do you know if a mem leak problem will lead to a plot fail? I am having issues with plotting which will get stuck at ard 80 to 90% randomly...

**Comment by jackykwandesign** [comment]
i think i face the same with you. 
While i am ploting with 58 plots, it should consume 192GB RAM
But in fact it eat all my 256GB RAM and leads to Chia blockchain crash.

Spec: 
CPU: 3990x with PBO
RAM: 256GB, no OC
SSD: p4610 7.6TB * 2
HDD: toshiba 14TB MG series * 2

Same with my 5900x, when i go  for 10*K32 + 2*K33, chia will crash, but 12 * K32 will be fine
Spec: 
CPU: 5900x with PBO
RAM: 64GB, no OC
SSD: Samsung 970 evo plus * 2
HDD: toshiba 14TB MG series *2

**Comment by jackykwandesign** [comment]
I think i should swap to Command line version before it waste my resouce for too much.

**Comment by royimous** [comment]
Yeah use the CLI. It's way better.

**Comment by MasterAssailant** [comment]
To those who are still facing this issue, another brilliant friend found out a possible solution in solving this issue (https://github.com/Chia-Network/chia-blockchain/issues/2951#issuecomment-835732970). Feel free to try this out!
