### ISSUE TITLE
Issue in Farming Last attempted proof are not coming in Time stamp sequence

### ISSUE THREAD

**Issue by Jai-Khandelwal** [Chia-Network/chia-blockchain#2957]
Date and Time of Last attempted proof are not coming sequential 
while Node Status is **Synced** and Farming Status is **Farming**

![image](https://user-images.githubusercontent.com/83308484/116334299-92197c00-a7f2-11eb-90fb-cbb26d4e01af.png)

**Comment by mtxprime** [comment]
get off of wifi

**Comment by comquer77** [comment]
experiencing the same, and I am on 1GB network cable connection.
