### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cca313** [Chia-Network/chia-blockchain#2962]
**Describe the bug**
 field connections always show 0 in Tab wallets

**To Reproduce**

**Expected behavior**
status show synced, and connections should not be 0

**Screenshots**
![image](https://user-images.githubusercontent.com/6041493/116337695-1973e900-a80d-11eb-96ca-5d25771f29e4.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- OS Version/Flavor: [e.g. Windows 10]
- CPU: [e.g. AMD 3600]

**Additional context**
i got 0 XCH if there is problems with the "connections"

**Comment by royimous** [comment]
This isn't a bug. Close it. Read the Wiki on port 8444 and the FAQ for proper support channels.

**Comment by cca313** [comment]
> This isn't a bug. Close it. Read the Wiki on port 8444 and the FAQ for proper support channels.

i read alot,and my ip address is dynamic,actually,a lot of users in chia will be up agianst with this.i wonder this will cause any problems?

**Comment by sargonas** [comment]
Tagging this issue for migration to a discussion. Apologies in advance, but you will be best served by moving this over there and out of the issue tracker, where the community can better assist you. (Ideally the issue tracker should be used to focus on bugs and development problems that need to be addressed, with general user support handled in Discussions and Keybase)

^MigrateToDiscussion
