### ISSUE TITLE
how to use the main machine for unified management and farmer? 

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#2966]
Follow https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines for multi-machine Plots, and then how to use the main machine for unified management and farmer? 
Or how to manage it through a mining pool.

**Comment by liya558** [comment]
I use the remote sharing method, I don't know if it is feasible.
Perform plots on the host of other nodes, and then share to the host computer to find plots through chia plots check

**Comment by royimous** [comment]
This isn't the place to get support. Read the FAQ on proper support channels.

**Comment by liya558** [comment]
Found a way
