### ISSUE TITLE
Transferred disk to another PC - empty disk

### ISSUE THREAD

**Issue by tom77g** [Chia-Network/chia-blockchain#2970]
I transferred my disk containing my plots to a new PC. loaded Chia and imported from Mnemonic, but my plots are gone. In fact the entire drive is empty. its like it got formatted? does anyone know what or why this happened or if this is recoverable?

**Comment by dorkmo** [comment]
is it a different operating system? you might plug it back into the original computer to check

**Comment by lvcivs** [comment]
Plot files are like any other files, so if the disk appears empty on a new PC it is definitely not a problem with chia. 

Maybe it is just not mounted properly. But to say any more, we'd need to know what OS, what filesystem on the disk, whether you can access it via File Manager etc.

**Comment by lipalong** [comment]
Chia plots are just large files, so if you cannot see the plots using your operating system's file browser, then Chia won't be able to access those plots.
