### ISSUE TITLE
[BUG] Chia requires manual restart after IP force disconnect by provider 

### ISSUE THREAD

**Issue by DatDraggy** [Chia-Network/chia-blockchain#2983]
**Describe the bug**
I live in germany and over here providers force-reconnect your router after 24h. This will result in a minute of downtime and usually happens at night. I can see that the last blocks synced are always around 3am when I wake up, which is the time the router reconnects.
The problem is, that after the reconnect something inside chia has died. It's not finding any nodes (8444/TCP is open) and upon adding a node manually following error appears in the logs:
```
2021-04-28T09:36:46.144 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set
```

**To Reproduce**

Get a new IP, I guess? I'm not sure if a simple disconnect results in the same issue.

**Expected behavior**
After a force reconnect chia should start finding nodes again and continue to sync.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Windows 10
- CPU: i9 9900k

**Comment by CTOzhujintao** [comment]
same question

**Comment by LoudSyncro** [comment]
I can approve this error / (mis)behaviour

**Comment by jayMcBee** [comment]
Same issue (macOS 10.14, losing connection every night after ISP force reconnect)

**Comment by Grosbof** [comment]
Same issue here.
