### ISSUE TITLE
[BUG] WALLET RPC  not work

### ISSUE THREAD

**Issue by 1971192997** [Chia-Network/chia-blockchain#2989]
wallet rpc apis

curl --insecure --cert ~/.chia/mainnet/config/ssl/wallet/private_wallet.crt \
--key ~/.chia/mainnet/config/ssl/wallet/private_wallet.key -d  '{"wallet_id": 1, "new_address":true}' \
-H "Content-Type: application/json" -X POST https://localhost:9256/get_next_address | jq

{
  "error": "0",
  "success": false
}

curl --insecure --cert ~/.chia/mainnet/config/ssl/wallet/private_wallet.crt \
--key ~/.chia/mainnet/config/ssl/wallet/private_wallet.key -d '{"wallet_id": 0}' \
-H "Content-Type: application/json" -X POST https://localhost:9256/get_wallet_balance | jq

{
  "error": "0",
  "success": false
}

===============================================================
here is the steps:
launch the node  and access the node api   wallet api

the full_node api works normal

but  wallet api  not works

**Comment by huzhengkui** [comment]
@1971192997  How to fix this error?
