### ISSUE TITLE
No sync anymore after weeks of working. (After ip change through provider)

### ISSUE THREAD

**Issue by DeeJay58** [Chia-Network/chia-blockchain#2992]
**Describe the bug**
No synching after I got a new IP from provider

**To Reproduce**

Maybe change iP?

**Desktop (please complete the following information):**

- OS: Win10
- OS Version/Flavor: 10
- CPU: ryzen i9

**Additional context**
Couldn't solve it yet - still no sync

**Comment by dorkmo** [comment]
Make sure to update to latest software and open port 8444

**Comment by DeeJay58** [comment]
Thank you. I've got the newest one since 2 or three days and the port was always and is open.

I only was able to solve it  by deleting the SQL files. No it is redownloading the blockchain and I hope then it will sync again.
But this is not really a solution for the future. 

It worked fine for weeks but after an ip-adress change from my provider it stopped.

**Comment by DatDraggy** [comment]
Simply restarting chia and adding nodes manually should work. There is a known issue where chia stops working after a disconnect/ip change.

**Comment by jayMcBee** [comment]
Same here - losing sync after couple hours every night when DSL is reconnecting;
This is very common in Europe and will limit farming for pretty much everybody using a standard internet provider in Europe.

From the log file it's apparent that Chia doesn't even try to re-establish the connection once it's lost after running OK (i.e. synced, normal operation) for a couple of hours..

MAJOR issue!

**Comment by jayMcBee** [comment]
` chia show -a node.chia.net:8444`

(also: https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference)

**Comment by DeeJay58** [comment]
After I did nothing happens. Still not connected Am 12.05.21 um 11:27 schrieb jayMcBee
                
            
            
                
                    Von: "jayMcBee" ***@***.***>Datum: 12. Mai 2021An: "Chia-Network/chia-blockchain" ***@***.***>Cc: "DeeJay58" ***@***.***>,"Author" ***@***.***>Betreff: Re: [Chia-Network/chia-blockchain] No sync anymore after weeks of working. (After ip change through provider) (#2992)
                
                
 chia show -a node.chia.net:8444
(also: https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Chia-Network/chia-blockchain/issues/2992#issuecomment-839617722",
"url": "https://github.com/Chia-Network/chia-blockchain/issues/2992#issuecomment-839617722",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
