### ISSUE TITLE
XCH balance became ZERO, previously it was 2

### ISSUE THREAD

**Issue by Tiger-Stone** [Chia-Network/chia-blockchain#2996]
**Describe the bug**
XCH balance became ZERO, previously it was 2 after Chia (Windows10; version 1.1.2) crashed when plotting , the Chia on my another PC, which is not crashed, still shows 2 XCH.

**Comment by ilylx** [comment]
Maybe you need sync

**Comment by Ratlord** [comment]
Hello,

I have the same issue. My wallet stopped showing my 2 Chia, it still shows on Chia Explorer, just not on the wallet in the gui. 
I have done a full resync to no avail 
![image](https://user-images.githubusercontent.com/29106925/116582920-1b759f00-a916-11eb-92e4-3a0fb9975afd.png)

**Comment by mariano54** [comment]
Multiple people have reported this issue.

**Comment by Ratlord** [comment]
This issue is GUI only - the XCH is there.
My wallet got corrupted, most likely when upgrading from 1.1 to 1.1.2 and the XCH was gone. I have deleted the .chia and %appdata%'s chia folder and reinstalled.

After a full wallet resync XCH was **still missing** but **a Gui restart after this** has restored XCH, leading me to believe that this is purely Front End issue.

**Comment by Tiger-Stone** [comment]
THanks for this.
can you please let me know how to check my XCH balance on Chia Explorer?
After more than 30 hours after restaring version 1.1.2, my wallet is still not synced!
[cid:f0037189-ff29-467b-8273-d01df2a2b6f4]

________________________________

**Comment by Ratlord** [comment]
My recommendation: Add an automatic front end refresh in the gui once wallet finishes syncing. Will prevent a lot of panic :)

**Comment by Tiger-Stone** [comment]
> My recommendation: Add an automatic front end refresh in the gui once wallet finishes syncing. Will prevent a lot of panic :)

How to add an automatic front-end refresh in the windows gui? Thanks

**Comment by lsanthosh1999** [comment]
i am facing the same issue

**Comment by lsanthosh1999** [comment]
> **Describe the bug**
> XCH balance became ZERO, previously it was 2 after Chia (Windows10; version 1.1.2) crashed when plotting , the Chia on my another PC, which is not crashed, still shows 2 XCH.

did you got them back
