### ISSUE TITLE
Window GUI on reload System Got stuck on Connecting to Wallet for 4 hours

### ISSUE THREAD

**Issue by Jai-Khandelwal** [Chia-Network/chia-blockchain#2997]
Window GUI on reload System Got stuck on Connecting to Wallet for 4 hours , i have plots in process so not able to shut down the appliation and sreen got stuck

**Comment by Khunmatthew** [comment]
I have same problem, even reload it,  it Still doesnt connect.

**Comment by Khunmatthew** [comment]
![IMG_20210428_225339.jpg](https://user-images.githubusercontent.com/83352450/116434425-9ab29680-a874-11eb-8541-2da2ab785344.jpg)

**Comment by Tupuren** [comment]
I have same problem, even force reload it, it Still doesnt connect.

**Comment by Tupuren** [comment]
I have same problem, even reload it, it Still doesnt connect.

**Comment by renanbebm** [comment]
I have the same problem in version 1.1.2
The wallet loading and not connect

**Comment by coderev3** [comment]
I also have the same problem in version 1.1.2
The wallet loading and not connect

**Comment by oktaysar16** [comment]
Stop Chia (Kill Task)

Delete these folders:
C:\Users\!yourusername!\.chia
C:\Users\!yourusername!\AppData\Local\chia-blockchain
C:\Users\!yourusername!\AppData\Roaming\Chia Blockchain

Reinstall Chia. It should now work.
