### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by myth2loki** [Chia-Network/chia-blockchain#3002]
plot process became 0 IO writes after run few hours. UI shows process 31%, cpu loads 6.8%。 I have got a few the cases

updated:
I tried single plotting, still got the same issue. Nooooooooooooo，I can't  plot anymore now

**Desktop (please complete the following information):**

- OS: win
- OS Version/Flavor: 10
- CPU: [e.g.amd 5800x 48g B550 1T m2 ssd]

**Additional context**

**Comment by razamataz** [comment]
+
