### ISSUE TITLE
[BUG] CRITICAL ISSUE - Forever trying to Connect to a Single IP Address (AFK Farming will not be possible 24/7)

### ISSUE THREAD

**Issue by erwinpgo** [Chia-Network/chia-blockchain#3003]
Major Issue:
I noticed after few hours of farming on Windows, the connection is stucked in trying to connect to a single IP only, it is not banning it which results into decreasing connection count from 10 to 0 after few hours. I experienced this on all Chia version. Only solution I can see is always restart Chia which is not good way of farming because you will always start to sync then farm.
Is there a file I can delete or restart anything without impacting my existing connections?

Plot Count: 32 Farming
RAM Size of Plots: 3390MiB
K-Size: K-32, 101.4GiB

Desktop Information:

OS/Version: Windows 10 Home
CPU: 3.7 GHz Intel Core i3-4170 with 12GB Ram

![image](https://user-images.githubusercontent.com/76909621/116405408-31298c80-a862-11eb-81d9-520348052231.png)

debug log:

  TCP    192.168.254.123:60232  58.241.110.109:8444    ESTABLISHED
  TCP    192.168.254.123:61426  cpe-70-115-155-96:8444  ESTABLISHED
  TCP    192.168.254.123:62546  a89-153-16-32:8444     ESTABLISHED
  TCP    192.168.254.123:65182  218.51.34.14:8444      SYN_SENT
  TCP    127.0.0.1:8444         DESKTOP-FARM:59298      ESTABLISHED
  TCP    127.0.0.1:8444         DESKTOP-FARM:59301      ESTABLISHED
  TCP    127.0.0.1:59298        DESKTOP-FARM:8444       ESTABLISHED
  TCP    127.0.0.1:59301        DESKTOP-FARM:8444       ESTABLISHED
  TCP    192.168.254.123:60118  host-79-53-23-65:8444  ESTABLISHED
  TCP    192.168.254.123:60232  58.241.110.109:8444    ESTABLISHED
  TCP    192.168.254.123:61426  cpe-70-115-155-96:8444  ESTABLISHED
  TCP    192.168.254.123:62546  a89-153-16-32:8444     ESTABLISHED
  TCP    127.0.0.1:8444         DESKTOP-FARM:59298      ESTABLISHED
  TCP    127.0.0.1:8444         DESKTOP-FARM:59301      ESTABLISHED
  TCP    127.0.0.1:59298        DESKTOP-FARM:8444       ESTABLISHED
  TCP    127.0.0.1:59301        DESKTOP-FARM:8444       ESTABLISHED
  TCP    192.168.254.123:60118  host-79-53-23-65:8444  ESTABLISHED
  TCP    192.168.254.123:60232  58.241.110.109:8444    ESTABLISHED
  TCP    192.168.254.123:61426  cpe-70-115-155-96:8444  ESTABLISHED
  TCP    192.168.254.123:62546  a89-153-16-32:8444     ESTABLISHED
  TCP    192.168.254.123:65197  218.51.34.14:8444      SYN_SENT
  TCP    127.0.0.1:8444         DESKTOP-FARM:59298      ESTABLISHED
  TCP    127.0.0.1:8444         DESKTOP-FARM:59301      ESTABLISHED
  TCP    127.0.0.1:59298        DESKTOP-FARM:8444       ESTABLISHED
  TCP    127.0.0.1:59301        DESKTOP-FARM:8444       ESTABLISHED
  TCP    192.168.254.123:60118  host-79-53-23-65:8444  ESTABLISHED
  TCP    192.168.254.123:60232  58.241.110.109:8444    ESTABLISHED
  TCP    192.168.254.123:61426  cpe-70-115-155-96:8444  ESTABLISHED
  TCP    192.168.254.123:62546  a89-153-16-32:8444     ESTABLISHED
  TCP    192.168.254.123:65201  218.51.34.14:8444      SYN_SENT
  TCP    127.0.0.1:8444         DESKTOP-FARM:59298      ESTABLISHED
  TCP    127.0.0.1:8444         DESKTOP-FARM:59301      ESTABLISHED
  TCP    127.0.0.1:59298        DESKTOP-FARM:8444       ESTABLISHED
  TCP    127.0.0.1:59301        DESKTOP-FARM:8444       ESTABLISHED
  TCP    192.168.254.123:60118  host-79-53-23-65:8444  ESTABLISHED
  TCP    192.168.254.123:60232  58.241.110.109:8444    ESTABLISHED
  TCP    192.168.254.123:61426  cpe-70-115-155-96:8444  ESTABLISHED
  TCP    192.168.254.123:62546  a89-153-16-32:8444     ESTABLISHED
  TCP    192.168.254.123:65209  218.51.34.14:8444      SYN_SENT
  TCP    127.0.0.1:8444         DESKTOP-FARM:59298      ESTABLISHED
  TCP    127.0.0.1:8444         DESKTOP-FARM:59301      ESTABLISHED
  TCP    127.0.0.1:59298        DESKTOP-FARM:8444       ESTABLISHED
  TCP    127.0.0.1:59301        DESKTOP-FARM:8444       ESTABLISHED
  TCP    192.168.254.123:60118  host-79-53-23-65:8444  ESTABLISHED
  TCP    192.168.254.123:60232  58.241.110.109:8444    ESTABLISHED
  TCP    192.168.254.123:61426  cpe-70-115-155-96:8444  ESTABLISHED
  TCP    192.168.254.123:62546  a89-153-16-32:8444     ESTABLISHED

**Comment by liuzhongsheng** [comment]
对，各种问题，永远不解决

**Comment by erwinpgo** [comment]
I experienced this again on Chia 1.1.3, my farming was smooth for the past days but this BUG is happening again.

I have 10 connections and it start to decrease to 1. I always experience this before on all Chia version but it is my first time to record the logs. How to prevent this because this bug will stop your farming after you don't have connections anymore due to looping connection error.

2021-05-03T17:03:48.723 full_node full_node_server : INFO Cannot connect to host 202.65.95.233:8444 ssl:<ssl.SSLContext object at 0x000002A73D2A6828> [Connect call failed ('202.65.95.233', 8444)

![image](https://user-images.githubusercontent.com/76909621/116873420-3d3e9100-ac4a-11eb-9345-a3a6280fb486.png)


C:\Users\User>netstat 2 | findstr 202.65.95.233
TCP 192.168.254.117:55845 202-65-95-233:8444 SYN_SENT
TCP 192.168.254.117:55850 202-65-95-233:8444 SYN_SENT
TCP 192.168.254.117:55851 202-65-95-233:8444 SYN_SENT
TCP 192.168.254.117:55888 202-65-95-233:8444 SYN_SENT
TCP 192.168.254.117:55954 202-65-95-233:8444 SYN_SENT

**Comment by ragnarokna** [comment]
> 对，各种问题，永远不解决

对,就是不解决,不爱用就滚.

**Comment by liuzhongsheng** [comment]
哪来的小韭菜，赶紧洗干净让人家收割去


&nbsp;

 少年辛苦终身事，莫向光阴惰寸功。



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月3日(星期一) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Chia-Network/chia-blockchain] [BUG] CRITICAL ISSUE - Forever trying to Connect to a Single IP Address (AFK Farming will not be possible 24/7) (#3003)





  
对，各种问题，永远不解决
  
对,就是不解决,不爱用就滚.

**Comment by ragnarokna** [comment]
> 哪来的小韭菜，赶紧洗干净让人家收割去 &nbsp; 少年辛苦终身事，莫向光阴惰寸功。 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月3日(星期一) 晚上8:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Chia-Network/chia-blockchain] [BUG] CRITICAL ISSUE - Forever trying to Connect to a Single IP Address (AFK Farming will not be possible 24/7) (#3003) 对，各种问题，永远不解决 对,就是不解决,不爱用就滚. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


不好意思,我们台湾没有镰刀.

**Comment by ragnarokna** [comment]
> 哪来的小韭菜，赶紧洗干净让人家收割去 &nbsp; 少年辛苦终身事，莫向光阴惰寸功。 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月3日(星期一) 晚上8:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Chia-Network/chia-blockchain] [BUG] CRITICAL ISSUE - Forever trying to Connect to a Single IP Address (AFK Farming will not be possible 24/7) (#3003) 对，各种问题，永远不解决 对,就是不解决,不爱用就滚. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

看您长的跟马云一样,莫不是马云的私生子?

**Comment by liuzhongsheng** [comment]
感谢您的耐心解答，我已经解决掉了，处理方式就是重启软件



 少年辛苦终身事，莫向光阴惰寸功。



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 晚上8:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] [BUG] CRITICAL ISSUE - Forever trying to Connect to a Single IP Address (AFK Farming will not be possible 24/7) (#3003)





 
I experienced this again on Chia 1.1.3, my farming was smooth for the past days but this BUG is happening again.
 
I have 10 connections and it start to decrease to 1. I always experience this before on all Chia version but it is my first time to record the logs. How to prevent this because this bug will stop your farming after you don't have connections anymore due to looping connection error.
 
2021-05-03T17:03:48.723 full_node full_node_server : INFO Cannot connect to host 202.65.95.233:8444 ssl:<ssl.SSLContext object at 0x000002A73D2A6828&gt; [Connect call failed ('202.65.95.233', 8444)
 

 
C:\Users\User&gt;netstat 2 | findstr 202.65.95.233
 TCP 192.168.254.117:55845 202-65-95-233:8444 SYN_SENT
 TCP 192.168.254.117:55850 202-65-95-233:8444 SYN_SENT
 TCP 192.168.254.117:55851 202-65-95-233:8444 SYN_SENT
 TCP 192.168.254.117:55888 202-65-95-233:8444 SYN_SENT
 TCP 192.168.254.117:55954 202-65-95-233:8444 SYN_SENT

**Comment by ragnarokna** [comment]
> 感谢您的耐心解答，我已经解决掉了，处理方式就是重启软件 少年辛苦终身事，莫向光阴惰寸功。 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Chia-Network/chia-blockchain" ***@***.***&gt;; 发送时间:&nbsp;2021年5月3日(星期一) 晚上8:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Chia-Network/chia-blockchain] [BUG] CRITICAL ISSUE - Forever trying to Connect to a Single IP Address (AFK Farming will not be possible 24/7) (#3003) I experienced this again on Chia 1.1.3, my farming was smooth for the past days but this BUG is happening again. I have 10 connections and it start to decrease to 1. I always experience this before on all Chia version but it is my first time to record the logs. How to prevent this because this bug will stop your farming after you don't have connections anymore due to looping connection error. 2021-05-03T17:03:48.723 full_node full_node_server : INFO Cannot connect to host 202.65.95.233:8444 ssl:<ssl.SSLContext object at 0x000002A73D2A6828&gt; [Connect call failed ('202.65.95.233', 8444) C:\Users\User&gt;netstat 2 | findstr 202.65.95.233 TCP 192.168.254.117:55845 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55850 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55851 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55888 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55954 202-65-95-233:8444 SYN_SENT — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

哎呀,这不是大校生吗?怎么只会重启软件,怎么不自己去修复bug呀?难道是梁家河大校毕业的?只会满脸喷粪扛麦子走山路吗?

**Comment by erwinpgo** [comment]
> 感谢您的耐心解答，我已经解决掉了，处理方式就是重启软件 少年辛苦终身事，莫向光阴惰寸功。

It is not solved since the bug is it keep on happening on all Chia version I used, is there a way to force stop the connection on a single IP like putting a limit?

**Comment by ragnarokna** [comment]
> 感谢您的耐心解答，我已经解决掉了，处理方式就是重启软件 少年辛苦终身事，莫向光阴惰寸功。 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Chia-Network/chia-blockchain" ***@***.***&gt;; 发送时间:&nbsp;2021年5月3日(星期一) 晚上8:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Chia-Network/chia-blockchain] [BUG] CRITICAL ISSUE - Forever trying to Connect to a Single IP Address (AFK Farming will not be possible 24/7) (#3003) I experienced this again on Chia 1.1.3, my farming was smooth for the past days but this BUG is happening again. I have 10 connections and it start to decrease to 1. I always experience this before on all Chia version but it is my first time to record the logs. How to prevent this because this bug will stop your farming after you don't have connections anymore due to looping connection error. 2021-05-03T17:03:48.723 full_node full_node_server : INFO Cannot connect to host 202.65.95.233:8444 ssl:<ssl.SSLContext object at 0x000002A73D2A6828&gt; [Connect call failed ('202.65.95.233', 8444) C:\Users\User&gt;netstat 2 | findstr 202.65.95.233 TCP 192.168.254.117:55845 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55850 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55851 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55888 202-65-95-233:8444 SYN_SENT TCP 192.168.254.117:55954 202-65-95-233:8444 SYN_SENT — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

天天用小学生开发的软件自己不害臊吗?小学生都能开发的软件你一个大校生自己不会开发吗?

**Comment by erwinpgo** [comment]
I am still experiencing this almost everyday, is there a config I can fix?

**Comment by xklech** [comment]
Same for me. Every few hours I stop farming. Unusable for me.
