### ISSUE TITLE
[BUG] Failed to migrate to another PC if just copying `~/.chia` folder

### ISSUE THREAD

**Issue by ChipZhang** [Chia-Network/chia-blockchain#3005]
**Describe the bug**
I want to migrate the existing Chia setup to another PC, without having to type the 20 words.

**To Reproduce**
1. Install and setup Chia GUI 1.1.2 wallet/sync/plots in PC 1 (Ubuntu 20.04)
2. I want to migrate the Chia setup to PC 2 (Ubuntu 20.04)
3. I install Chia GUI 1.1.2 in PC 2
4. copy folders `~/.chia` and `~/,config/Chia Blockchain` from PC 1 to PC 2
5. I have the same linux account name / UID / GID / home folder file system permissions on PC 1 and PC 2
6. I launch Chia in PC 2, the original wallet does not appears in the app, I need to restore the wallet using the 20 words. Copying config files is no use.

**Expected behavior**
After copying config files, when I launch the Chia GUI, the original wallet should already be there.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Comment by dorkmo** [comment]
the wallet keys are securely stored in your operating system's key database after you enter the 24 words. its not saved as a file in the chia folder.

**Comment by ChipZhang** [comment]
> the wallet keys are securely stored in your operating system's key database after you enter the 24 words. its not saved as a file in the chia folder.

Thanks for the reply.
Is there any to force the app to store the key in the config folder (I KNOW THIS IS RISKY)?

**Comment by dorkmo** [comment]
i havent heard of this, not sure sorry
