### ISSUE TITLE
难道就不能为中国人提供一个非常好用的节点么？[BUG]

### ISSUE THREAD

**Issue by liuzhongsheng** [Chia-Network/chia-blockchain#3006]
这么多人反应同步有有问题，为什么不能改进下？不能为中国人提供合适的节点？

**Comment by ragnarokna** [comment]
為什麼特意要給中國人提供合適的節點?你們付費嗎?

**Comment by liuzhongsheng** [comment]
> 為什麼特意要給中國人提供合適的節點?你們付費嗎?

因为用户主要是中国大陆人，呆蛙你懂吗？

**Comment by ragnarokna** [comment]
你們可以選擇不用.愛用不用.沒有專門給支那人特供的防火牆專用節點,真可憐.

**Comment by liuzhongsheng** [comment]
> 你們可以選擇不用.愛用不用.沒有專門給支那人特供的防火牆專用節點,真可憐.

做美国人的的狗都做出优越感了，做个人不好么？

**Comment by ragnarokna** [comment]
同步不上就去找你們的網絡供應商,是聯通還是移動來著,給你們提供更大的國際網絡接入.真可憐.用撥號上網小區寬帶就不要學人家玩什麼數字貨幣.

**Comment by ragnarokna** [comment]
啊呀,做美國的狗還有狗權呢,做支那人連人權都沒有,還不如美國狗.

**Comment by ragnarokna** [comment]
或者你們這麼牛逼,去山寨一個嘛.找你的馬爸爸給你山寨一個,讓你們在牆裡玩的開心.

**Comment by liuzhongsheng** [comment]
> 啊呀，做美国的狗还有狗权呢，做支那人连安全都没有，还不如美国狗。

来叫一声给我听听，听听你们台湾这帮井底蛙的叫声

**Comment by liuzhongsheng** [comment]
> 或者你们这么牛逼，去山寨一个嘛。找你的马爸爸给你山寨一个，让你们在墙里玩的开心。

我们这墙是有形的，而你们的狗链子是无形的

**Comment by liuzhongsheng** [comment]
> 啊呀，做美国的狗还有狗权呢，做支那人连安全都没有，还不如美国狗。

是挺安全的，有死亡的权利，几十万人因为新冠死亡，真安全

**Comment by ragnarokna** [comment]
哈哈哈,不論是有形的還是無形的牆,你都在裡面爬不出來呦,小支那蛆蛆.

**Comment by ragnarokna** [comment]
啊呀,我們台灣死了這麼多人嗎?哎呀,我好怕怕呀.啊呀,好怕怕.

**Comment by ragnarokna** [comment]
你們中國死的少呢,我知道,你們中國有14億人,死幾萬,四捨五入等於沒死.我知道.你們好棒棒呀.好厲害.

**Comment by ragnarokna** [comment]
既然這麼厲害還敲什麼羅呢,在微博上殺豬一樣叫什麼呢?多棒棒呀.

**Comment by liuzhongsheng** [comment]
> 啊呀，我们台湾死了这么多人吗？哎呀，我好怕怕呀。啊呀，好怕怕。

你们台湾可没人，狗比较多，当然，剩下的都是娘娘腔，说话能不能有点阳刚之气，男人不像男人

**Comment by ragnarokna** [comment]
好棒棒的中國人跑出來玩什麼外國人的數字貨幣呢,還不回家玩習大大給你們開發的數字貨幣去,別在網上感染了武漢肺炎.

**Comment by ragnarokna** [comment]
啊呀呀,我知道你們中國狗少,因為都被吃了嗎.而且你們中國人不僅吃狗,還喜歡吃兩腳羊呢.今天你吃了嗎,兩腳羊?

**Comment by liuzhongsheng** [comment]
> 好棒棒的中国人跑出来玩什么外国人的数字货币呢，还不回家玩习大大给你们开发的数字货币去，别在网上感染了武汉肺炎。

娘娘腔，赶紧滚回去吃美国的猪肉吧哈哈，垃圾桶就是收废物的

**Comment by ragnarokna** [comment]
獻忠哥哥今天有沒有帶你吃兩腳羊啊.

**Comment by ragnarokna** [comment]
啊呀呀,你被收進垃圾桶裡了嗎?

**Comment by ragnarokna** [comment]
我剛給你們支那人提供了新的節點,就埋在你老母的逼裡.你快去把它挖出來用.

**Comment by liuzhongsheng** [comment]
> 我剛給你們支那人提供了新的節點,就埋在你老母的逼裡.你快去把它挖
台湾人也自剩下意淫了，要什么没什么，跟乡下一样，还成天自认为自己多发达^_^，快滚回你的井你，爸爸不爱搭理你
