### ISSUE TITLE
[BUG] The .deb GUI installer doesn't show the version

### ISSUE THREAD

**Issue by C4** [Chia-Network/chia-blockchain#3012]
**Describe the bug**
When installing the .deb file on Ubuntu (20.04) it doesn't show the version in Help -> About Chia Blockchain. This is useful when upgrading versions of chia and verifying that they are the version that's expected 

**To Reproduce**

1. Download the .deb from the github **OR** `wget https://github.com/Chia-Network/chia-blockchain/releases/download/1.1.2/chia-blockchain_1.1.2_amd64.deb`
2. Install the package: `sudo dkpg -i chia-blockchain_1.1.2_amd64.deb`
3. Start the GUI: `chia-blockchain &`
4. In the GUI: click `help` -> `About Chia Blockchain`
5. Chia Blockchain is 0.0

**Expected behavior**
The current version should reflect the current version in this case 1.1.2

**Screenshots**
![image](https://user-images.githubusercontent.com/800740/116424073-13264280-a7f6-11eb-973f-4674fc935536.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: Intel(R) Celeron(R) CPU 3865U

**Additional context**
N/A

**Comment by wjblanke** [comment]
We will look into this. Thank you.

**Comment by lvcivs** [comment]
It shows 0.0 for me as well, and I have installed from git. 

Ubuntu 21.04.

**Comment by Leonardo-Fiori** [comment]
Yup, updated to latest version and now is version 0.0, is this a time warp? lol
Hope it's just a visual glitch anyways

**Comment by jchleb** [comment]
can confirm, brand new 21.04 install on 2 machines.
chia install from command line or from .deb, chia gui displays 0.0 as version.

**Comment by Muffexx** [comment]
The bug persists with version 1.1.4

**Comment by jssdesarrollo** [comment]
The bug persist with version 1.1.6

**Comment by mattremay** [comment]
> The bug persist with version 1.1.6

for me not. The same after upgrade on Ubuntu.

**Comment by Cinorid** [comment]
me too

**Comment by kzsolt4444** [comment]
The bug persist with version 1.1.7

**Comment by kzsolt4444** [comment]
On v1.2 on windows it is good, but on ubunto is still showing 0.0

**Comment by jbastidacano** [comment]
It shows 0.0 for me as well, and I have installed from git too.

![image](https://user-images.githubusercontent.com/77586474/126876189-f692eac7-9517-441b-8d2d-667569e47c89.png)

**Comment by emlowe** [comment]
This should be fixed in the DEP and RPM packages going forward in new versions.
(It still doesn't work right if you pull from git)
