### ISSUE TITLE
GUI huge GPU consumption

### ISSUE THREAD

**Issue by EvgeniyKorepov** [Chia-Network/chia-blockchain#3013]
GUI consumes GPU resources as a miner. 
11% of RTX 3090 just to show the gray rectangle and endless progress.
Maybe you should optimize the GUI a little, or change the framework?

![image](https://user-images.githubusercontent.com/35364901/116424721-6e822000-a84a-11eb-8b6c-d290181b269a.png)

**Comment by wjblanke** [comment]
We're using nodejs for our GUI which uses Chrome as a rendering engine. Unfortunately it looks like it is a bit heavy in GPU usage. You can use the command line if you want to avoid the GUI overhead.
