### ISSUE TITLE
Have to delete all traces of Chia and reinstall every time I reboot/lose wifi[BUG]

### ISSUE THREAD

**Issue by Fallout556** [Chia-Network/chia-blockchain#3015]
**Describe the bug**
If I restart the computer or lose wifi, my status to the node becomes permanently "Not Synced". I had no issues until about a week ago. No I have to delete all traces of the program from my computer, reinstall, and then it will work. I did try using it with a VPN since I am on my apartment's wifi and cannot access the router, but that did not help. Only a clean sweep works. 

**To Reproduce**

1. Start Chia Network.
2. Restart computer, shutdown chia network, or lose wifi
3. Restart chia network

**Expected behavior**
Network will not synch

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: 20H2
- CPU: Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz

**Comment by DatDraggy** [comment]
Have you tried adding nodes manually?
There is a known issue when losing a connection where you have to restart chia. After that you can add nodes to start syncing.
Also make sure to open TCP Port 8444.

Try these:
Introducers addresses:

North Asia introducer-apne.chia.net:8444
South Asia introducer-apse.chia.net:8444
Western North America: introducer-or.chia.net:8444
Eastern North America introducer-va.chia.net:8444
Europe: introducer-eu.chia.net:8444

And then add these nodes addresses:
North America: node-or.chia.net:8444
Europe: node-eu.chia.net:8444
Asia: node-apne.chia.net:8444

**Comment by Fallout556** [comment]
I have and it worked on one of my computers, but I had to add an introducer
a second time after it lost synch again. I'm away from my rigs for a couple
of days but will let you know if I have any more problems.

Also, I wiped everything on my computer that had anything to do with Chia
except my plots and may have deleted two coins I had. Will they reappear
after I resync?

**Comment by DatDraggy** [comment]
If you are using the same wallet as before then yes. Your coins are stored on the blockchain. As long as you kept your backup phrase which Chia gave you when creating the wallet, you can always restore from that and get your coins back on any computer.

**Comment by Fallout556** [comment]
Ok, when will they reappear? After network full synchs?

**Comment by DatDraggy** [comment]
They will appear once you have synced the block you got them in, so probably close to fully synced

**Comment by Fallout556** [comment]
Great thanks!
