### ISSUE TITLE
[BUG] Harvester Incorrect Checksum

### ISSUE THREAD

**Issue by akeslo** [Chia-Network/chia-blockchain#3024]
**Describe the bug**
Mac 1.1.2 Harvester Error stops Farming

**To Reproduce**
Just run Farming, happens constantly

**Expected behavior**
No error and farming works without issue

**Screenshots**
`start_harvester(16196,0x70000e3e6000) malloc: Incorrect checksum for freed object 0x7faa304af3c8: probably modified after being freed.
Corrupt value: 0xfe6b545375f4a05b
start_harvester(16196,0x70000e3e6000) malloc: *** set a breakpoint in malloc_error_break to debug
`
**Desktop (please complete the following information):**

- OS: Mac
- OS Version/Flavor: 10.15.7
- CPU: I7

**Additional context**

**Comment by lipalong** [comment]
Can you set the log level to INFO, and then restart, and then post the logs? You can also check for any bad plots.

**Comment by akeslo** [comment]
[debug.txt](https://github.com/Chia-Network/chia-blockchain/files/6398607/debug.txt)
@lipalong here is the log, thanks!
