### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hardware-79** [Chia-Network/chia-blockchain#3027]
![微信图片_20210429010934](https://user-images.githubusercontent.com/82661474/116447666-d0627a00-a88a-11eb-9fd6-b7b83d0b9288.jpg)
绘图时出现上面的报错，请问是什么原因

**Comment by dorkmo** [comment]
looks like it says it couldnt open the file? did you move or delete anything while plotting?

**Comment by nolan6363** [comment]
got the same ...

**Comment by hardware-79** [comment]
> 看起来像它无法打开文件？绘图时您是否移动或删除了任何内容？

开始绘图后没有做任何操作，只移动了鼠标
