### ISSUE TITLE
[REQUEST] Restore the removal button

### ISSUE THREAD

**Issue by sykmer** [Chia-Network/chia-blockchain#3030]
I have a big request. Could you please restore the removal button for plots generation?
To remove one of the generated plots, I have to turn off the client chia for windows 10, which causes the loss of the remaining generated plots. So I have to start all over again.
Could you please restore the remove plots button?
Thank you.

**Comment by Muffexx** [comment]
AFAIK they want to bring it back any time soon.

> We have temporarily disabled the "Delete Plots" button in the Windows GUI as we are still working on debugging upstream issues that are causing it.

[Changelog of 1.1.0 - Changed](https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21)

**Comment by sargonas** [comment]
The Delete Plot function in the GUI was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21
