### ISSUE TITLE
Bitfield plotting not supported by CPU

### ISSUE THREAD

**Issue by 8PotatoChip8** [Chia-Network/chia-blockchain#3034]
I was just looking for clarification to weather my CPU is actually supported or not. Is there a supported CPU post or somthing?
Anyways.

Fedora 33 Workstation Edition
CPU (x2): Intel Xeon E5430 @ 2.66GHz

Wondering if CPU is supported.

Thanks

**Comment by sargonas** [comment]
I don't believe your CPU will support bitfield. The documentation states that BF requires a cpu "roughly" less than a decade old, so using 2010 as a general benchmark, give or take a year, without digging deeper into the specific technologies at play, still puts your CPU older than that by 3 years, as they came out in Nov 2007. I think it's safe to assume they are not compatible.

**Comment by 8PotatoChip8** [comment]
> I don't believe your CPU will support bitfield. The documentation states that BF requires a cpu "roughly" less than a decade old, so using 2010 as a general benchmark, give or take a year, without digging deeper into the specific technologies at play, still puts your CPU older than that by 3 years, as they came out in Nov 2007. I think it's safe to assume they are not compatible.

Alright, that kinda sucks. It will still be supported for framing though?

**Comment by dorkmo** [comment]
bitfield only effects plotting. its a few percentage boost to plotting speed, but is not required.

**Comment by sargonas** [comment]
> > I don't believe your CPU will support bitfield. The documentation states that BF requires a cpu "roughly" less than a decade old, so using 2010 as a general benchmark, give or take a year, without digging deeper into the specific technologies at play, still puts your CPU older than that by 3 years, as they came out in Nov 2007. I think it's safe to assume they are not compatible.
> 
> Alright, that kinda sucks. It will still be supported for framing though?

yup, you can farm just fine.. and you can plot just fine too, it will just be slower than it would be with BF enabled!

**Comment by 8PotatoChip8** [comment]
> > > I don't believe your CPU will support bitfield. The documentation states that BF requires a cpu "roughly" less than a decade old, so using 2010 as a general benchmark, give or take a year, without digging deeper into the specific technologies at play, still puts your CPU older than that by 3 years, as they came out in Nov 2007. I think it's safe to assume they are not compatible.
> > 
> > 
> > Alright, that kinda sucks. It will still be supported for framing though?
> 
> yup, you can farm just fine.. and you can plot just fine too, it will just be slower than it would be with BF enabled!

Oh, I didnt realize you can disable bitfield

**Comment by sargonas** [comment]
Yup! Default mode on both CLI and GUI is enabled, but you can override to turn it off in both cases for special needs, such as yours.

**Comment by 8PotatoChip8** [comment]
Alright, thanks everyone. I will disable bitfield.
