### ISSUE TITLE
None of your plots have passed the plot filter yet.  You are currently farming 1.089 TiB

### ISSUE THREAD

**Issue by lpenrod** [Chia-Network/chia-blockchain#3035]
I have 2 chia rigs set up. 
Both Windows 10
*chia1 is the master full node - 192.168.1.30
*chia2 is a second full node - 192.168.1.29

I moved the CA from chia1 to chia2 and did the chia init -c [directory] and that was successful.

chia1 I originally opened TCP port 8447, but during trouble shooting, it is now open TPC/UDP ANY ANY

chia2 I've disabled UPNP and added under Harvester, farmer_peer, host:, the IP of the chia 1 machine.

Both rigs sync their block-chain.  Both rigs are downloading plots (cli).  Both rigs say they are Farming.  chia1 is regularly receiving "Last Attempted Proof" and  "Latest Block Challenges".  chia2 under farming says "None of your plots have passed the plot filter yet. But you are currently farming 1.089 TiB"

I've ran TCPview on both machines.  I see a connection from chia2 to chia1 on port 8447 and packets sent and recieved.

I've changed the logging to both machines to info.

Looking at the logs chia2 I see:
2021-04-28T14:38:38.016 harvester harvester_server        : INFO     <- new_signage_point_harvester from peer [value] 192.168.1.30
2021-04-28T14:38:38.063 harvester chia.plotting.plot_tools: INFO     Searching directories ['E:\\Plots']
2021-04-28T14:38:38.063 harvester chia.plotting.plot_tools: INFO     Loaded a total of 11 plots of size 1.0888025345248025 TiB, in 0.04686236381530762 seconds
2021-04-28T14:38:38.063 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 511bb59b66... Found 0 proofs. Time: 0.04686 s. Total 11 plots
2021-04-28T14:38:38.063 harvester harvester_server        : INFO     -> farming_info to peer 192.168.1.30 
I see the above over and over.

Looking at the logs of chia1 I see:
2021-04-28T15:06:23.461 farmer farmer_server              : INFO     -> new_signage_point_harvester to peer 192.168.1.29 [value]
2021-04-28T15:06:23.461 farmer farmer_server              : INFO     <- farming_info from peer [value] 192.168.1.29
I see the above over and over.

On chia2 I have deleted  delete the file "peer_table_node.sqlite" in chia->mainnet->db folder and restarted.

All along the way I have stopped and started chia on both servers.  They do their handshake and then communicate on port 8447.

I'm lost at this point.

**Comment by lpenrod** [comment]
I never see any new_prof_of_space in any of the logs.

**Comment by lvcivs** [comment]
Why do you want to run two full nodes in the same LAN?

**Comment by lpenrod** [comment]
Inexperience maybe.  I want to plot on both rigs.

**Comment by lpenrod** [comment]
I noticed on my router:

Active | Protocol | Int. Port | Ext. Port | IP Address
YES | TCP | 8444 | 8444 | 192.168.1.29  (address of chia2)

**Comment by lpenrod** [comment]
That was the only item in the upnp portmap table.

**Comment by lvcivs** [comment]
No need for another full node, then. On the plotting machine you can plot from the CLI using `chia plots create` without running a full node / farmer.

Having two full nodes behind the same public IP is going to cause problems. How do your peers know which full node they are talking to?

**Comment by lpenrod** [comment]
So I have a powershell script running the chia plot create on both machines.  Is it as simple as just shutting down the GUI on chia2?  Right now, chia1 only sees the plots on its machine.  chia2 only sees the plots on it's machine.

**Comment by lpenrod** [comment]
Is it as simple as moving the plots from chia2 to chia1 for farming?

**Comment by lvcivs** [comment]
Yes, if you have used the same keys on both machines.

**Comment by lpenrod** [comment]
I have.  I will try now.

**Comment by ddowhy** [comment]
> Having two full nodes behind the same public IP is going to cause problems. How do your peers know which full node they are talking to?

because the port would be different.

**Comment by lpenrod** [comment]
chia1 says "Failed to open (invalid plots)" for a couple that I copied over.

**Comment by lpenrod** [comment]
I'm following: https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines

**Comment by lpenrod** [comment]
I needed to add the -f farmer_key and -p pool_key then store/move the plot to chia1.  I think I am good.  I appreciate your help!
