### ISSUE TITLE
class 'RuntimeError'>: Src size is incorrect error in getting challenge qualities for plot[BUG]

### ISSUE THREAD

**Issue by brezapour81** [Chia-Network/chia-blockchain#3037]
**Describe the bug**
I got error 13 earlier today and decided to run the chia plots check command and got the below error against two of my plots.

**"<class 'RuntimeError'>: Src size is incorrect error in getting challenge qualities for plot F:\plot...."**

**To Reproduce**
Steps to reproduce the behaviour:

1. open command prompt --> run chia.exe plots check -g k32 -n 10 in the daemon local directory.
2. You will see the error (assuming you get the same issue) with the following details:
<class 'RuntimeError'>: Src size is incorrect error in getting challenge qualities for plot F:\plot...."

**Expected behavior**
I just wanted to find out what caused this. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
Intel i3
64GB RAM
1tb M.2 for temp
8TB WD drive for final plot files.

**Additional context**
N/A

**Comment by buzuloiu** [comment]
I'm seeing this as well - I plotted in Windows 10 through the GUI

Intel i7
12GB RAM
Just a random HDD folder for temp
40TB SMB share on TrueNAS for final plot files. 

In the GUI the plots say they're farming, but on my 2015 Macbook pro through the CLI when I run `chia plots check` I get the same error.

**Comment by dnsgram** [comment]
Is anyone work on this problem?  

I run this on linux and get 14 file report this error,  is this file valid for farm ?  (or should I delete it ?)

**Comment by dnsgram** [comment]
@arvidn @Nikolaj-K  any one from chia team care give a comment ?

**Comment by arvidn** [comment]
This error message "Src size is incorrect" comes from the `FiniteStateEntropy` library, used to run a general purpose compression of the plot. This suggests that the plot file is corrupt or truncated.

It would make sense for the error message to be more descriptive and intuitive.
