### ISSUE TITLE
Sync constantly disconnecting

### ISSUE THREAD

**Issue by dasiit** [Chia-Network/chia-blockchain#3050]
CHIA Node is not synced. Connection status is connected.

How do I get back to sync?
![image_2021-04-28_203450](https://user-images.githubusercontent.com/83380042/116488767-2f12fe00-a861-11eb-877d-f15132f5808b.png)

**Comment by lipalong** [comment]
How long has the connection status been connected? Syncing takes a bit of time.

**Comment by royimous** [comment]
This is not a bug. Please close. 

Read the FAQ to learn how to find support.
