### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tfarhanrizq** [Chia-Network/chia-blockchain#3058]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**
kenapa peak height nya udh banyak tapi coin xch nya belum diterima

**Comment by lipalong** [comment]
Winning Chia block rewards is probabilistic, and the probability varies by individual setup. There is no guarantee to win at any particular block height.
