### ISSUE TITLE
[help]how can I sell or transfer my plots  since my data driver got some problem ?

### ISSUE THREAD

**Issue by HectorChow** [Chia-Network/chia-blockchain#3070]
**Describe the issue**
PLEASE NOTE!: The issue tracker is NOT a place to seek general support. You are better served starting a conversation in the Discussions area at https://github.com/Chia-Network/chia-blockchain/discussions or in the Keybase.io #support channel. If you create a support request here, it may or may not receive a response before being closed, and we cannot guarantee a timely response, or one at all. In the event that your issue is deemed to be the result of a bug, we will endeavor to review and update it accordingly as such instead of closing it.

**To Reproduce**
Steps that led up to your issue.

**Expected behavior**
A clear and concise description of what you expected to happen before you encountered your issue.

**Screenshots**

**Additional context**

**Comment by DatDraggy** [comment]
Plots are bound to your private key. Simply move them to a new disk and add the disk to the known farming spaces.
