### ISSUE TITLE
Chia plots keep freezing up[BUG]

### ISSUE THREAD

**Issue by dondiablo** [Chia-Network/chia-blockchain#3082]
**Describe the bug**
Plots freeze up at random % and random phases (11%,43%,88%) on HDD and SSD. parallel or not. Sometimes 1 plot continues and the other freezes up.  logs do not show anything they just stop logging. 

**To Reproduce**
I plot on a 1TB sebrante rocket nvme. I plot 1 queue with name "A" standard settings. And plot a second queue next to it with name "B". (so 2 plots in parallel on a 1TB SSD) and the final plot gets written on a 10TB HDD. 
but about 90% of my plots freeze up.

**Expected behavior**
not applicable

**Screenshots**
Not applicable (as mentioned the logs are just showing "Bucket 120....etc" as the last message. 

**Desktop (please complete the following information):**

- OS: Windows 64 bit laptop
- OS Version/Flavor: 10 home
- CPU: I7 7700hq / 16GB ram

**Additional context**
Task manager conirms the plots seem to have stopped. i waited 10+ hours on some plots but nothing changed.

**Comment by Peter82kr** [comment]
Same but on linux.Stuck at 31% with single plot (not parallel).

**Comment by myth2loki** [comment]
same here

**Comment by sllvertlger** [comment]
Same, randomly freezing. Sometimes 75% sometimes 90%, 50%. Just restart computer delete temp files and start over again. Every 4-5. attempt makes working plot to 100%.

**Comment by jackge0323** [comment]
same problem.

**Comment by horizon6969** [comment]
Same here on AMD, and in Linux Ubuntu 20. I reinstalled system on Windows- then vmware Ubuntu machine, same issue. I was working few days ago without issues. I tried few different plotting options, different drive setups and I Am not ale to finish any plot. process still runs and using one core of CPU. I am using screen and session is still active. 
Most of cases last log message is :
Starting phase 2/4: Backpropagation without bitfield into tmp files... Thu Apr 29 16:22:51 2021
Backpropagating on table 7

Amd Ryzen 7 8 cores, 32g ram , 2x nvme 500G  , Ubuntu LTS 20.4 , with fresh install of chia from git.

easy to spot when it hangs with dstat

**Comment by sllvertlger** [comment]
There is no reason to stop ploting, no error code nothing, Its just using ram and cpu but disk usage 0%, waited for 10hours no change. I have Win10 AMD Ryzen 5 3600, 16gb ram ddr4. Ssd or hdd doesnt matter.

**Comment by Peter82kr** [comment]
I waited whole day and during one day chia gui ploted 0% on ssd.Stuck at 31%. Tried to delete plot and start again and now ploting stucks at 0%. .

**Comment by razamataz** [comment]
+

**Comment by horizon6969** [comment]
i was using -e option. When I removed it , it seems to work ok. Please check if you are also using it. 
-e [bitfield plotting]: Using the -e flag will disable the bitfield plotting algorithm, and revert back to the older b17 plotting style. After 1.0.4 it’s better to use bitfield for most cases (not using -e). Before 1.0.4 (obsolete) using the -e flag (bitfield disabled) lowers memory requirement, but also writes about 12% more data during creation of the plot. For now, SSD temp space will likely plot faster with -e (bitfield back propagation disabled) and for slower spinning disks, i.e SATA 5400/7200 rpm, not using -e (bitfield enabled) is a better option.

Thanks !

**Comment by Peter82kr** [comment]
@horizon6969 how to disable that -e option in gui on linux?

**Comment by horizon6969** [comment]
i am using linux CLI plotting, and was referring to that type. I am guessing in GUI it maybe in advanced tab ?

**Comment by razamataz** [comment]
Always with no -e option

**Comment by Peter82kr** [comment]
Checked that -e option in gui. -e option is the "Disable bitfield plotting" in advanced plotting options. But that was not checked so no -e option was used. Still no success with ploting. Plots stucks. Now im checking with that -e option in gui because info says that if i have processor maded before year 2010 i may disable bitfield plotting.Sorry for my english its not my native language.

**Comment by minosandro** [comment]
Same here, Ubuntu, AMD FX, ssd Crucial. This thing is too much buggy, giving up.

**Comment by pmarson** [comment]
I'll add a "me too". Win10 , tmp and destination are on external 16TB RAID drive. Single plot frozen at 84% for at least 8 hours. Using default settings for everything.
Very frustrating.

**Comment by LaZpanyoL** [comment]
yea when plotting %87 its frozen everytime 3 days. no error but frozen

**Comment by andrewdaviesj** [comment]
Same here. I just upgraded ram and also 1.1.2 to 1.1.5 and so far every plots hangs. Some at 54%, 56%, 78% and 90% for me all in phase 3. CPU and memory are still busy but 0 disc action. W10, 80gb, i9 10850k, 2x2tb raid 0.

**Comment by ijf313-github** [comment]
Same here. Similar symptoms to described above. LInux Mint. Experimental GUI installer. Ryzen Threadripper 3970X. Happens even with plenty of memory and temp space available.

**Comment by tseiff** [comment]
Also having this issue, Intel 10850K, Windows 10 and Ubuntu 20.04, on different temp disks, any number of parallel plots, any number of threads, usually see plots "freeze" in stage 3, they seem to be "running" but no disk usage, the plot never finishes.  Happens to about 30% of my plots.

**Comment by sredouane** [comment]
same problem with me on ubuntu 20 and AMD Ryzen 7 3600X, freeze most of time at random places and only one made it to 100% out of(2,3,..8 parallels plots ).
there is a solution that worked for some people which is lowering ram frequency from the BIOS. it worked for me only once with 3 parallels plots. then stopped working

**Comment by pmarson** [comment]
I have since shifted to plotting on two ssds, and farming on a big external HDD. And it has run flawlessly. These drives are not used for anything else.  I did notice I had immense trouble (lockups and 5 minute  delays) if I tried to use file explorer on the external drive at the same time as the chia gui was trying to access it. Could it be flooding the drive interface and failing to play nice when other apps are also attempting to access the drive? I could see antivirus scans possibly creating extra drive accesses - I currently have all the plotting drives excluded from virus scanning.

**Comment by zhifmjoy** [comment]
same problem.

**Comment by drexample** [comment]
same problem

**Comment by katopotato-sac** [comment]
hello, similar problem for me. 

ryzen 5 2600, Ubuntu 21.04, Chia GUI 
5 parallel plots, 1/5 stuck at 100%, 4/5 stuck at 11%-20%

completed 2 plots prior to starting the 5 plots which have been stuck for 12+ hours.

**Comment by ArtemProc** [comment]
Same problem, started recently.

NVME Drive Viper VPN100 - TBW 3115  TB - written 700 TB
Parallel plotting - some of process simply freeze with NO disk activity and CPU still consumed.

**Comment by gnoyk9** [comment]
I had the same problem, 30-40% of my plotting jobs would freeze  and never finish for no apparent reason.

A user reported that he fixed the problem by replacing his RAM.
https://github.com/Chia-Network/chia-blockchain/issues/4264

I replaced mine with a spare set I had laying around and have not plotted for 5 days straight with no frozen jobs.

**Comment by ijf313-github** [comment]
Same. Ran several iterations of MemTest86+ and found bad RAM. Removed the offending stick/module and seems better now.

**Comment by tseiff** [comment]
I detected SSD over-heating to be a problem, fixed that, and I see some improvement, so for me SSD temp seems to have been the problem, I hope; I upgraded my M.2 heatsink and put a fan under my 2.5" WD Gold.  I saw threads freeze when the SSD reached 70C, the SSD would throttle, the temp would drop significantly, but the plotter processes never picked up the drive again, so that is probably a bug.

Check your SSD temp while plotting.

> Could it be flooding the drive interface and failing to play nice when other apps are also attempting to access the drive?

"Flooding" the drive interface should only slow everything down, unless you have a faulty drive or a bad file system, there would be no error here.

However, based on my observation of temp issues, the increased disk access COULD be raising the temperature to the point that the disk throttles and kills the plot process (but not other apps), so check that.

**Comment by realdevnullius** [comment]
I'd like to join the band wagon :( I've had this happen a few times (Windows 10, Chia 1.1.6 + 1.1.7)... I have my PCs plotting away (on 2x 1.7TB SSD, with temp 2 on my nvme system disk of 1TB) and go to bed. When I wake up I move my mouse, the screen wakes up and I'll see in my task manager HDD activity and RAM drop instantly. After that, the processes for all intends and purposes are dead. Yes, there's CPU activity. But that's about it. Power savings are set to Performance and sleep has been disabled. 

I'll start monitor my SSD temperatures too but they should max out at 50C - and that's my nvme, which says it can go up to 90C... 

This is a real setback to my plans I must say :(

I installed Acronis Drive Monitor and it detects no warnings in the windows logs concerning disk errors.

Fracking Chia :(

**Comment by realdevnullius** [comment]
Hmm... Reading along with the comments... I did buy A-Data RAM from China. I'd expect blue screens but a proper RAM test couldn't hurt... I'll look into that one too. I never should have trusted RAM with leds in them :(

**Comment by realdevnullius** [comment]
> Also having this issue, Intel 10850K, Windows 10 and Ubuntu 20.04, on different temp disks, any number of parallel plots, any number of threads, usually see plots "freeze" in stage 3, they seem to be "running" but no disk usage, the plot never finishes. Happens to about 30% of my plots.
> 
> chia version 1.1.6.dev0

I had several plots in parallel on 2x SSD and *all* my tasks froze this morning, half were in phase 1, the other half reached phase 3.

**Comment by mibsmibs** [comment]
This was happening to me too, and it was painful to freeze at 96% and other high %ages. I didn't want to do it, because my SSDs are new but I reformatted them and lost some plots in the process. But I found and fixed 2 errors on brand new SSDs. I have since had no problems at all. May be worth reformatted and starting over.

**Comment by ascandal** [comment]
Same issue. Very frustrating.

chia 1.1.7
Windows 10 and Ubuntu 20.04
Brand new system with lots of resources.
Case open with external fan pointed straight at the board.

Other simpler more resource limited Alienware works fine.

**Comment by ascandal** [comment]
Update. I was able to solve this issue by disabling overclocking in bios.

### System:
ASUS ROG Zenith II Extreme Alpha
32GB DDR4 3600 -28800 TridentZ Neo
Dual Boot Ubuntu 20.04 and Windows 10.

### BIOS changes:
Ai Overclock Tuner [D.O.C.P. Standard] --> [Auto]
Memory Frequency [DDR4-3200MHz] --> [Auto]
DRAM CAS# Latency [18] --> [Auto]
Trcdrd [22] --> [Auto]
Trcdwr [22] --> [Auto]
DRAM RAS# PRE Time [22] --> [Auto]
DRAM RAS# ACT Time [42] --> [Auto]
DRAM AB Voltage [1.35000] --> [Auto]
DRAM CD Voltage [1.35000] --> [Auto]

System is stable now but I'm concerned the RAM is **under** clocked now.
