### ISSUE TITLE
[BUG]  Pot file has a farmer public key that is not in the farmer's pk list.

### ISSUE THREAD

**Issue by nad010286** [Chia-Network/chia-blockchain#3086]
**Describe the bug**
I have a farm machine and about 5 plot machines connected in 10Gbps network. One of the plotter got upgraded and running v1.1.2 and its the only one has the issue: "has a farmer public key that is not in the farmer's pk list." Other plot machines work fine and in v1.1.1
Im running Ubuntu Server 18.04

**Comment by cryptoshaman007** [comment]
I get plot has a farmer public key that is not in the farmer's pk list, out of nowhere, one moment all works ok, then stop working.
