### ISSUE TITLE
Constant Not Synced

### ISSUE THREAD

**Issue by filippovpa** [Chia-Network/chia-blockchain#3087]
Since today its always Not Synced, and there is no connection to Full Node peer
I can manualy add connection, its go OK for about hour or so, and then again Not Synced, and connection just gone from the list

Windows 10, time sync - OK

**Comment by Cast39** [comment]
Have you tried adding a port forwarding in your router on port 8444 to your PC? Or maybe add a different introducer:

**Introducer**

- North Asia introducer-apne.chia.net:8444
- South Asia introducer-apse.chia.net:8444
- Western North America: introducer-or.chia.net:8444
- Eastern North America introducer-va.chia.net:8444
- Europe: introducer-eu.chia.net:8444

**Nodes**

- North America: node-or.chia.net:8444, 
- Europe: node-eu.chia.net:8444, 
- Asia: node-apne.chia.net:8444

**Comment by filippovpa** [comment]
> Have you tried adding a port forwarding in your router on port 8444 to your PC? Or maybe add a different introducer:
> 
> **Introducer**
> 
> * North Asia introducer-apne.chia.net:8444
> * South Asia introducer-apse.chia.net:8444
> * Western North America: introducer-or.chia.net:8444
> * Eastern North America introducer-va.chia.net:8444
> * Europe: introducer-eu.chia.net:8444
> 
> **Nodes**
> 
> * North America: node-or.chia.net:8444,
> * Europe: node-eu.chia.net:8444,
> * Asia: node-apne.chia.net:8444

Yeah i did 
It connect, go for sync, and then Not Synced again
Strange thing, that for 2 days it works perfectly fine, i got fully synced, and start Farming...

**Comment by Cast39** [comment]
> Yeah i did
> It connect, go for sync, and then Not Synced again
> Strange thing, that for 2 days it works perfectly fine, i got fully synced, and start Farming...

is the height in the Wallets tab as high as the peak height in the Full Node tab? If it does, here ends my wisdom, sorry

**Comment by rjulius23** [comment]
Ok my experience is that node.chia.net is super flaky. Sometimes i can connect to it forcefully, sometimes it just rolls and nothing happens. I think the issue is central, do not think it is a client issue.

**Comment by rjulius23** [comment]
Can we prioritize this issue ? @bramcohen If the central backbone is unstable it is impossible to farm :(

**Comment by filippovpa** [comment]
i cant even ping node-eu.chia.net
is it down ?

**Comment by rjulius23** [comment]
(venv) m@m-Super-Server:~/chia-plotting-scripts$ telnet node.chia.net 8444
Trying 54.71.94.197...

(venv) m@m-Super-Server:~/chia-plotting-scripts$ telnet node-apne.chia.net 8444
Trying 18.179.127.148...

(venv) m@m-Super-Server:~/chia-plotting-scripts$ telnet node-or.chia.net 8444
Trying 54.191.64.151...

(venv) m@m-Super-Server:~/chia-plotting-scripts$ telnet node-eu.chia.net 8444
Trying 18.130.174.242...

**Comment by rjulius23** [comment]
None of them works currently and the Farming status also changed to : Farming status: Not synced or not connected to peers

**Comment by filippovpa** [comment]
> None of them works currently and the Farming status also changed to : **Not synced or not connected to peers**

thx, guess we just have to wait....

**Comment by rjulius23** [comment]
Has been down for 2 hours now... :(

**Comment by Wardus** [comment]
I have this same problem.  It shows me as connected, but my status is Not Synced.  HELP!

**Comment by fiveangle** [comment]
Seeing same thing here.  All non-port mapped nodes fall out of sync regardless of the introducer.  Also, `chia show -a <local peer IP that has 8444 portmapped to the internet>:8444` results in that node refusing to stay connected.

Seems the P2P part of the Chia network is fundamentally not functioning consistently.

**Comment by filippovpa** [comment]
Still down?

**Comment by rjulius23** [comment]
Using **chiadb.net:8444** solved it for me, however the root cause is still unknown as **node.chia.net:8444** worked fine for 2 weeks.

**Comment by rjulius23** [comment]
Looking deeper into the issue, I think something with UPnP went fishy. I will play around with the UPnP settings in my router and in the chia node to see if that is the culprit.

**Comment by filippovpa** [comment]
> Using **chiadb.net:8444** solved it for me, however the root cause is still unknown as **node.chia.net:8444** worked fine for 2 weeks.

Finaly got sync in progress!! Thx a lot mate, ur my savior =)

**Comment by RollingRoland** [comment]
I have a similar problem. After I installed Chia 10 days ago things worked without any special router setup. But since 24 hours it is not syning or farming anymore. I tried everything in my shitty router to open the ports. It is a TP Link Archer C7. The closest I could find there was a port trigger option where tried to open the port. It does not seem to work. I also tried to manually add nodes and introducers in the GUI. After a few circles the window just disappeared and nothing happened. And on the 2 try on manually adding an introducer the window just hung itself and kept circling. After clicked the "restart" option the whole GUI is hung circling now. The Chia GUI is so full of bugs like I have never seen before. Unfortunately I am not an IT or Network specialist. So can't say I grasp on how to use CLI properly. I am really at the end of my wits. Any help would be much appreciated.

**Comment by filippovpa** [comment]
well....its Not Synced again...and chiadb.net not work anymore
why they call it 1.1.2 when its 0.0.1 at most...

**Comment by rjulius23** [comment]
I think the issue is with UPnP, do you have UPnP enabled on your router ? If yes i would suggest try to disable it and also run:

chia configure —upnp false

and restart the node.

**Comment by rjulius23** [comment]
If you disable UPnP port forwarding needs to be setup properly.

**Comment by filippovpa** [comment]
Can u help about  chia configure —upnp false ?

When i first run Chia, there was no Upnp, port 8444 was closed, but it works just fine
Then i got No Synced, trying to get Static IP, Upnp - ON, port OPEN, it works for some time, then it broke connection with all peers

Today i was able to connect to chiadb.net in like 5-6 tryes

How can u farm with this bugged coin if it keeps disconnecting with no reason...
