### ISSUE TITLE
ЗАСЕИВАНИЕ 0%

### ISSUE THREAD

**Issue by therealshurik** [Chia-Network/chia-blockchain#3092]
Я пробовал перезапускать много раз с разными настройками участков , у меня ноутбук  ryzen 5 3550h / ram16gb /ssd512/hdd10tb, пробовал повышать и понижать количество используемой ram и количество потоков,что делать ?кто то еще сталкивался с этим? у меня еще идет синхронизация , но на сколько я знаю при синхронизации засеивание должно работать одновременно

**Comment by paulpaul9740** [comment]
+1, только что столкнулся с той же проблемой, синхронизация тоже висела
сейчас синхронизация прошла, но плоттинг все так же 0% уже около часа, до этого проценты шли почти сразу

**Comment by paulpaul9740** [comment]
should we speak in english here?

**Comment by paulpaul9740** [comment]
> 
> 
> Я пробовал перезапускать много раз с разными настройками участков , у меня ноутбук ryzen 5 3550h / ram16gb /ssd512/hdd10tb, пробовал повышать и понижать количество используемой ram и количество потоков,что делать ?кто то еще сталкивался с этим? у меня еще идет синхронизация , но на сколько я знаю при синхронизации засеивание должно работать одновременно

о, только что заработало. проверьте у себя

**Comment by paulpaul9740** [comment]
Если не сработает, то добавьте сюда лэйбл Support

**Comment by therealshurik** [comment]
нет, у меня до сих пор 0%

**Comment by filippovpa** [comment]
а у вас синхронизация с сетью есть? уже полдня Not Synced

**Comment by therealshurik** [comment]
> а у вас синхронизация с сетью есть? уже полдня Not Synced

синхронизация идет ,соединение с сетью есть ,синхронизация 61824/204118

**Comment by mariano54** [comment]
Can you please create a new issue in english? Sorry for that, but it makes things simpler for other people needing support, and for us to help you.
