### ISSUE TITLE
[help] Ich bekomme die Synchronisation nicht hin

### ISSUE THREAD

**Issue by DrScamp** [Chia-Network/chia-blockchain#3100]
Ich habe die agnze Zeit die meldung das meine Node nicht Synchronisiert ist . Ich habe auch versucht alle möglichen verbindungen mit dem Port: 8444 einzugehen. manchmal verbindet es sich aber dann nach einiger Zeit kommt wieder nicht Synchronisiert. kann mir jemand helfen bitte , bin schon echt am verzweifeln

**Comment by lvcivs** [comment]
Kann verschiedene Ursachen haben. Oft liegt es daran, dass Chia zuwenige Verbindungen zu Peers hat. Du kannst im GUI checken, wie viele es aktuell sind. Vielen hilft es, im Router das UPNP für die Maschine, auf der Chia läuft, freizuschalten. Alternativ kann man auch von Hand den Port 8444 freigeben. Ob deine Node auf Port 8444 erreichbar ist, kannst du hier testen: https://www.yougetsignal.com/tools/open-ports/

Du kannst von Hand eine offizielle Node hinzufügen, das hilft manchmal: `node-eu.chia.net:8444`

Ferner kannst du auch versuchen, die Datei `~/.chia/mainnet/db/peer_table_node.sqlite` zu löschen, da sie manchmal in einen korrupten Zustand gerät. Beim nächsten Neustart der Software fängt die Suche nach Peers bei Null an.

**Comment by RollingRoland** [comment]
Chia ist echt eine verdammte Scheisse! Habe eine Woche verschwendet um das Plotten in den Griff zu bekommen. Und wenn ich eindlich ein paar Terra Byte Plots zum Farmen habe, dann funktioniert das Syncing natürlich nicht mehr. Das GUI ist so voll von Bugs ich weiss echt nicht mehr was sagen. Habe alles versucht in meinem Router 8444 frei zu schalten. Das Checking Tool das lvcivs gelistet hat sagt aber immer er sei geschlossen. Dann habe ich versucht die nodes und introducters manuell im GUI hinzuzufügen. Bei den Nodes hat das Fenster ein paar mal gezirkelt und dann ist nichts passiert. Als ich einen introducer ein zweites mal versucht habe hat sich das Fenster im zirkeln aufgehängt. Und als ich die restart option gewählt habe bleibt auch nur ein zirkelndes Fenster hängen. Und ich habe 3 plots die im Hintergrund kreiert werden. Das ganze kotzt mich echt an! Gestern hatte der Demon Prozess ein Meromry Leak bis das GUI bank weiss war. Wenigstens ist eas nach dem restart wieder rauf gekommen. Um einen Chia Coin zu farmen muss man offebar nicht nur dicke Kohle für Hardware haben sonder auch Netzwerk und IT Spezialist sein.
Es ist nun über 24 Stunden mein Chia das letzte mal synced war. Um DrScamp zu zitieren: Ich bin echt am verzweifeln !

**Comment by lvcivs** [comment]
Please close this.

**Comment by Hellek1** [comment]
> Ich habe die agnze Zeit die meldung das meine Node nicht Synchronisiert ist . Ich habe auch versucht alle möglichen verbindungen mit dem Port: 8444 einzugehen. manchmal verbindet es sich aber dann nach einiger Zeit kommt wieder nicht Synchronisiert. kann mir jemand helfen bitte , bin schon echt am verzweifeln

1.) Was lvcivs geschrieben hat.
2.) Schau in die FAQ. Versuche die dort angegebenen Introducer hinzuzufügen: https://github.com/Chia-Network/chia-blockchain/wiki/Port-8444
