### ISSUE TITLE
[BUG] Could not install packages due to an OSError: [Errno 13] Permission denied: 'WHEEL'

### ISSUE THREAD

**Issue by yazh2636** [Chia-Network/chia-blockchain#3108]
Ubunt20.04

(venv) chia@ubuntu:/chia/chia-blockchain$ ./install-timelord.sh 
Timelord requires CMake 3.14+ to compile vdf_client
Python version: python3.8
apt-get is /usr/bin/apt-get
Found Ubuntu/Debian
Installing chiavdf from source on Ubuntu/Debian
Ubuntu 20.04LTS and newer support CMake 3.16+
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.16.3-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
apt-get install libgmp-dev libboost-python-dev libpython3.8-dev libboost-system-dev build-essential -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-system-dev is already the newest version (1.71.0.0ubuntu2).
libgmp-dev is already the newest version (2:6.2.0+dfsg-4).
libboost-python-dev is already the newest version (1.71.0.0ubuntu2).
build-essential is already the newest version (12.8ubuntu1.1).
libpython3.8-dev is already the newest version (3.8.5-1~20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
venv/bin/python -m pip install --force --no-binary chiavdf chiavdf==1.0.1
Collecting chiavdf==1.0.1
  Using cached chiavdf-1.0.1.tar.gz (639 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (PEP 517) ... done
  Created wheel for chiavdf: filename=chiavdf-1.0.1-cp38-cp38-linux_x86_64.whl size=1213905 sha256=7b6321ba3691567500e450473d63c90c59c3e66698d0ba6851fcde08ef7ae273
  Stored in directory: /home/chia/.cache/pip/wheels/8e/15/81/325f90e9fd8d2ecc5e46e59a553c4905054c3204a3eddf8012
Successfully built chiavdf
Installing collected packages: chiavdf
  Attempting uninstall: chiavdf
    Found existing installation: chiavdf 1.0.1
    Uninstalling chiavdf-1.0.1:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'WHEEL'
Check the permissions.

**Comment by lvcivs** [comment]
Why are you trying to install a timelord? Most likely you just want to install and run a full node. For plotting and farming, that's all you need.
