### ISSUE TITLE
[REQ] Enhance config.yaml to allow control over debug.log rotation

### ISSUE THREAD

**Issue by scriptmasterflash** [Chia-Network/chia-blockchain#3114]
Would it be hard to add configuration of log rotation (for debug.log) into the Logging section of config.yaml?  
Would like (in priority order) to configure/control:

1) use of a different suffix for the log files other than .1, .2, etc.  like a date/time stamp.
2) the number of logs retained
3) the size of each log
4) option to compress the log files after they are rotated

And extra salt on my fries please!  Thanks for all the great work, loving this project!

**Comment by scriptmasterflash** [comment]
Forgot to check previous PRs, etc.  and noticed that #2 above has already been addressed.  Thank you!

**Comment by scriptmasterflash** [comment]
for Item#1 above, something like
debug.yyyy-mm-dd.hh.mm.log 
would be great!  using the date/time of the rotation or some other date/time stamp that is convenient?

**Comment by keliew** [comment]
Maybe see: https://github.com/Chia-Network/chia-blockchain/pull/2502

**Comment by scriptmasterflash** [comment]
Additional log files reduce the need for this enhancement request, closing.
