### ISSUE TITLE
[help] chia plots passed filter 1/8 why?

### ISSUE THREAD

**Issue by mobinparsian** [Chia-Network/chia-blockchain#3116]
hi .. im setup chia and fullnode and sync wallet and all of the page perview synced in the plots passed filter just show 1/8 a few times.. and in proof found 0 . why my plots passed filter not 8/8 ? 
and how can im undrestand how much i get cxh ? always show 0 .. im install chia about 2 week

**Comment by dorkmo** [comment]
the filter is a quick way to reduce the number of plots that are eligible to win. its normal to see 0/8 or 1/8. it would be very rare to see all of your plots pass the filter.

**Comment by sargonas** [comment]
Tagging this issue for migration to a discussion. Apologies in advance, but you will be best served by moving this over there and out of the issue tracker, where the community can better assist you. (Ideally the issue tracker should be used to focus on bugs and development problems that need to be addressed, with general user support handled in Discussions and Keybase)

^MigrateToDiscussion
