### ISSUE TITLE
[BUG]farm date no move

### ISSUE THREAD

**Issue by Laconiss** [Chia-Network/chia-blockchain#3119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**
![IMG_20210429_203503](https://user-images.githubusercontent.com/81981907/116601289-9e085980-a92a-11eb-8dd3-431710887415.jpg)
![IMG_20210429_203514](https://user-images.githubusercontent.com/81981907/116601300-a365a400-a92a-11eb-9bcf-02c1f29d9449.jpg)

**Comment by Laconiss** [comment]
Farm date no move..plz help me.. im block here 4day

**Comment by Laconiss** [comment]
Look date.. last Proof date no move.. my system time u see?

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dorkmo** [comment]
you might have lost your last node peer? do you have any connections?
