### ISSUE TITLE
[help] 1T SSD, staggered plot 3 or 4 is faster

### ISSUE THREAD

**Issue by benkywong** [Chia-Network/chia-blockchain#3134]
I got a R730 with H730mini RAID, 2*2683v4, 256G RAM, 2*1TB SSD (SATA)

Which one is the fastest?
2x1T RAID 0, 6plots, 1 hr stagger
2x1T RAID 0, 8plots, 1 hr stagger
Non-RAID 1T+1T, 6plots, 1 hr stagger
Non-RAID 1T+1T, 8plots, 1 hr stagger

Actually, I got 4x1T, 2x256G, 1x500G running. I think the RAID is the reason that causes me 24h+ to complete a plot

**Comment by lipalong** [comment]
You can get advice about performance optimization in our Keybase chat channels. Feel free to ask this question there to get more assistance.

**Comment by benkywong** [comment]
where is it? link?

**Comment by benkywong** [comment]
Where is it? link?
Regards
Ben


Lipa ***@***.***> 於 2021年4月30日 週五 上午8:40寫道：
