### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by JosestebanPorrasV** [Chia-Network/chia-blockchain#3136]
**Describe the issue**
I've been on this page for ten hours, it doesn't happen to me right there, how can I solve it?

**Screenshots**

![chia](https://user-images.githubusercontent.com/60045487/116624516-a900c100-a90d-11eb-9df3-6a5ef8ea17cd.png)

**Comment by lipalong** [comment]
Which version of the Chia application are you running?

**Comment by JosestebanPorrasV** [comment]
1.1.2

**Comment by joanarijo** [comment]
I'm having the same issue. Version: 1.1.2 as well. Nothing in logs.

**Comment by dorkmo** [comment]
this guy suggests deleting some files and reinstalling

https://github.com/Chia-Network/chia-blockchain/issues/2997#issuecomment-830406282

**Comment by joanarijo** [comment]
Delete, Reinstall and then Restart the PC - worked for me. Thank you! @dorkmo
