### ISSUE TITLE
Connecting to wallet 

### ISSUE THREAD

**Issue by sllvertlger** [Chia-Network/chia-blockchain#3142]
While ploting gui crashed, or whatever, just white screen, for no reason I did not do anything, so I did what I shouldn't..... reload..... 

Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0
main.js:1 Already connected, not reconnecting.
main.js:1 0

**Comment by ikumi90s** [comment]
bump, this problem is the main vain problem, I'm having this for like since 1.0 and still not having any solve in most cases. it would be nice if there's a solution to disconnect that "already connected" problem...

**Comment by vladborovtsov** [comment]
same issue :/

**Comment by tommy1735** [comment]
same, too bad i cannot restart couz its plotting but i cannot see the progress

**Comment by yenkij** [comment]
It happened to me in 1.1.3 and i still don't know how to solve this :(

**Comment by vladborovtsov** [comment]
I discovered that reload/force reload usually causing this. 
And the reason for reload was that I stuck on keys tab. 
So once chia software is running, don't visit keys tab and you are good :)

**Comment by mate3** [comment]
Same situation. Does anyone knows will plotting finish successfully as it works in backend even GUI doesn't?
