### ISSUE TITLE
[BUG]Failed to open (invalid plots) after update from 1.0.5 to 1.1.2

### ISSUE THREAD

**Issue by Firesuiry** [Chia-Network/chia-blockchain#3144]
**Describe the bug**

I use 1.0.5 to generate many plots.
but when I update the software to 1.1.2
all the plots become invalid.

**To Reproduce**

1. generate plots using ver1.0.5
2. update to 1.1.2
3. see error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux] Windows10
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M] i7 6700k

**Additional context**

**Comment by leewi9** [comment]
same here, waiting for the solution.

**Comment by keliew** [comment]
Delete the plot directory **path** on the GUI.

**Not** the plots itself.

Then re-add the plot directory.

**Comment by Firesuiry** [comment]
> Delete the plot directory **path** on the GUI.
> 
> **Not** the plots itself.
> 
> Then re-add the plot directory.

I tryed it and it has no use. QAQ

**Comment by leewi9** [comment]
finally I’m ok 
It says plots unusable maybe because the net hasn’t synced enough to recognize them, so I synced all the net and restart the client, now it’s ok:)


Sent from Yahoo Mail for iPhone


On Saturday, May 1, 2021, 23:14, Firesuiry ***@***.***> wrote:





Delete the plot directory path on the GUI.

Not the plots itself.

Then re-add the plot directory.


I tryed it and it has no use. QAQ

**Comment by caishubao** [comment]
换台电脑尝试一下

**Comment by Farmingfool** [comment]
Here's what I did to resolve this issue:
If you have any pending plots, you will have to wait them to finish before you can move on, or you can sacrifice the current plotting progress.
1.  Remove all plot directories (DO NOT DELETE THE PLOTS on the file system)
2.  Exit Chia, ensure ALL processes are stopped
3.  REBOOT plotting machine
4.  Remove ANY .tmp files in both the TMP and Final destination directories
5.  Launch chia and add plotting directories back in
6.  Wait for sync

**Comment by extrasolarCHIA** [comment]
After updating to 1.2.0 more than 100 plots suddenly turned invalid for me. I have to run plots check yet but the gui says so.

**Comment by extrasolarCHIA** [comment]
plots check gives me this

`2021-07-11T00:52:00.605  chia.plotting.plot_tools         : ERROR    Failed to open file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot. Invalid file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot
`
