### ISSUE TITLE
how to build chia-blockchain-gui for windows

### ISSUE THREAD

**Issue by zhuibm1** [Chia-Network/chia-blockchain#3147]
how to build chia-blockchain-gui for windows

chia-setup.exe how to build

**Comment by royimous** [comment]
This is not the place to get support. Read the FAQ.

**Comment by keliew** [comment]
Maybe start by reading...
https://github.com/Chia-Network/chia-blockchain/blob/main/build_scripts/build_windows.ps1

**Comment by Piet0816** [comment]
Has anyone managed to build the executables in Windows 10 with the Powershell Script?
Im alwaysa running into Errors.

What Powershell/Python versions are recommended?

**Comment by Thimo1996** [comment]
Any good sources to guide me through the steps of building the exe? the build_windows script seems to be needing some setup
