### ISSUE TITLE
wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 

### ISSUE THREAD

**Issue by chris8783** [Chia-Network/chia-blockchain#3151]
I'm beyond frustrated with this whole project. What's the point in giving errors when they don't let you know what they mean or how to fix them? 😡😡😡😡
![20210429_231052](https://user-images.githubusercontent.com/83440584/116644883-8dfc7400-a942-11eb-9d26-2cca7d8b3254.jpg)

**Comment by psych131** [comment]
Did you get this figured out, the same issue is killing me
