### ISSUE TITLE
Install Issue Windows

### ISSUE THREAD

**Issue by burnardia** [Chia-Network/chia-blockchain#319]
### Issue Details

* **Electron Version:**
  *  0.1.8 -->
* **Operating System:**
  * Windows 10 (10.0.18363 Build 18363) -->
* **Last Known Working Electron version:**
  * 

### Expected Behavior

I simply downloaded and installed. The first time I went to make a new wallet and would not proceed when hitting the "next" button after getting my seed key. The next time I launched in admin mode it would not load anything. See attached screenshots. I've tried reinstalling with no luck. I need help deciphering the errors. Thanks. 
### Screenshots

![1](https://user-images.githubusercontent.com/44145906/87740020-cdd4df00-c7a6-11ea-9be8-cbd15157a6a6.PNG)
![2](https://user-images.githubusercontent.com/44145906/87740030-d3322980-c7a6-11ea-8198-174d73ee0b4c.PNG)

**Comment by hoffmang9** [comment]
Please try this fix: https://github.com/Chia-Network/chia-blockchain/wiki/Windows-pre-Haswell-1.8-workaround

**Comment by A-Caccese** [comment]
I'm having the same problem as burnardia on Chia 0.1.7 and also on Chia 0.1.8. The patch didn't fix it. Moreover, my processor is a Pentium G4520 (Skylake microarchitecture) post-Haswell. The UI does nothing when I click "next" in both the creation and import windows.

**Comment by burnardia** [comment]
@A-Caccese Have you tried running as admin? Also what errors are you getting?

**Comment by A-Caccese** [comment]
> @A-Caccese Have you tried running as admin? Also what errors are you getting?

Yes, I'm running it as admin. I modified the config file to keep logs with DEBUG level. When I click "next", I see this in the logs
```
20:16:08.384 daemon websockets.protocol        : DEBUG    server < Frame(fin=True, opcode=1, data=b'{"command":"add_key","data":{"mnemonic":["arm","teach","trash","rhythm","album","echo","magnet","frost","provide","hobby","pioneer","unaware","regular","royal","front","anger","pudding","cinnamon","view","copy","license","honey","purity","park"]},"ack":false,"origin":"wallet_ui","destination":"chia-wallet","request_id":"5041229300985b0bec6f855eec32946e6547c067a6a83417ef4a25b39baf2562"}', rsv1=False, rsv2=False, rsv3=False)
20:16:08.607 daemon websockets.protocol        : DEBUG    server - event = data_received(<66 bytes>) 
```

**Comment by burnardia** [comment]
@A-Caccese not sure if that was you who asked the question on the livefeed but Gene is active https://www.chia.net/contact/

**Comment by A-Caccese** [comment]
I don't know if it's related but I see also this message in the logs:
```
20:13:00.479 daemon __main__                   : INFO     About to ping: wallet_ui
20:13:00.489 daemon websockets.protocol        : DEBUG    server > Frame(fin=True, opcode=9, data=b'\xe0n\xf6\x8e', rsv1=False, rsv2=False, rsv3=False)
20:13:00.502 daemon __main__                   : INFO     Ping error: 'chia-wallet'
```

**Comment by A-Caccese** [comment]
> @A-Caccese not sure if that was you who asked the question on the livefeed but Gene is active https://www.chia.net/contact/

No, it's not me.

**Comment by hoffmang9** [comment]
Assuming you are on Windows please try this in powershell and report back the error:

```
cd \AppData\Local\Chia-Blockchain\app-0.1.8\resources\app.asar.unpacked\daemon\
.\chia generate keys
```

**Comment by wjblanke** [comment]
Try this

go to
AppData\Local\Chia-Blockchain\app-0.1.812\resources\app.asar.unpacked\daemon

rename mpir.dll mpirold.dll
rename mpir_gc.dll mpir.dll
reboot

see if it works now

**Comment by A-Caccese** [comment]
> .\chia generate keys

The output of `.\chia keys generate` is `Generating private key`. So this doesn't seem to be the problem.

**Comment by A-Caccese** [comment]
> Try this
> 
> go to
> AppData\Local\Chia-Blockchain\app-0.1.8\resources\app.asar.unpacked\daemon
> 
> rename mpir.dll mpirold.dll
> rename mpir_gc.dll mpir.dll
> reboot
> 
> see if it works now

This fixed the problem! However, for Windows the commands are 
`cd ~\AppData\Local\Chia-Blockchain\app-0.1.8\resources\app.asar.unpacked\daemon`
`mv mpir.dll mpirold.dll`
`mv mpir_gc.dll mpir.dll`

So the problem seems to be the library mpir.dll

**Comment by hoffmang9** [comment]
Added it to the 1.8 workaround page:
https://github.com/Chia-Network/chia-blockchain/wiki/Windows-pre-Haswell-1.8-workaround
