### ISSUE TITLE
[REQ] Displays total plot size information and estimated winning times for the entire farm

### ISSUE THREAD

**Issue by vanthoi** [Chia-Network/chia-blockchain#3194]
I see the main machine only shows what is in the main machine only. 
Why don't we show the total plot size information and the winning time estimate for the whole system, when there are multiple harvesters on the same farm!

**Comment by sargonas** [comment]
this request is already tracked in https://github.com/Chia-Network/chia-blockchain/issues/1461, feel free to follow there to see if/when it can be implemented.
