### ISSUE TITLE
[REQ]How can I Send coins in the testnet?

### ISSUE THREAD

**Issue by kencani** [Chia-Network/chia-blockchain#3195]
We need to develop wallet tools for Chia.So I want to know the part of the test transaction.How Can I get the testnet coins ?

**Comment by mariano54** [comment]
Yes, message me on keybase (sorgente711) or post address here.

**Comment by kencani** [comment]
> 是的，请在密钥库（sorgente711）上给我发消息或在此处发帖。

Hello, I want to generate the address of the test network now. It should be possible to convert the address from the public key to the puzzle hash. At present, there are still problems in the conversion from the public key to the puzzle hash. I'm not a python developer and I'm not familiar with the python language. It's hard to read the source code. Can you provide the algorithm project of public key conversion puzzle hash? It's better to have a go language version. thanks

**Comment by kencani** [comment]
> 是的，请在密钥库（sorgente711）上给我发消息或在此处发帖。

We extend the public key for BLS algorithm by extending the public key, so if we want to be compatible with this algorithm to generate addresses, we will open the source after completion

**Comment by mariano54** [comment]
We are using bech32 (with bech32m mode). Look for the functions `decode_puzzle_hash` and `encode_puzzle_hash` to convert from and to addresses.

**Comment by 1044740162** [comment]
> 我们需要为Chia开发钱包工具。所以我想知道测试交易的一部分。如何获得测试网硬币？

Hey, have you found the solution now, I have the same problem now

**Comment by yaoyf888** [comment]
你们找到合适的方法了么？我也遇到这个问题了，怎么从公钥转换成puzzle_hash？

**Comment by yaoyf888** [comment]
@mariano54 Hello,Can you provide the procedure for converting the private key to the public key and then to the address?

**Comment by itorry** [comment]
> 我们正在使用 bech32（使用 bech32m 模式）。查找函数`decode_puzzle_hash`并`encode_puzzle_hash`从地址转换为地址。

 I want to generate the address of the main network now. It should be possible to convert the address from the public key to the puzzle hash. At present, there are still problems in the conversion from the public key to the puzzle hash. I'm not a python developer and I'm not familiar with the python language. It's hard to read the source code. Does anyone know any other way to get the puzzle hash from the public key, such as RPC, or the Java language or JS language,thanks
