### ISSUE TITLE
[BUG] Black Screen when Plotting

### ISSUE THREAD

**Issue by thanhdonguet** [Chia-Network/chia-blockchain#3196]
I'm making a plot. When it goes about 10%. Chia windows turn to black. Everything I see in the task manager is normal. It is plotting. I think this is UI issue.
![IMG_20210430_144041](https://user-images.githubusercontent.com/17382258/116665192-a5c80c80-a9c3-11eb-9a17-30827c504dcc.jpg)

- OS: Windows 10
- i5 10400f
- 16GB ram 
- nvme 980 1TB plot maker
- wd purple 6TB plot will be saved here
- gtx 1050 (just to export image)
- Making 3lot parallel: 4GB ram, 4 Thread, K32

I am waiting for it to continue plotting but this is annoying.

**Comment by keny-phong** [comment]
Hi,
I had the same issue.
I think that the issue occured when the application CHIA uses too much memory then few ram is left for displaying.
There is no restriction for CHIA to use all the ram it needs ?
I dont know if we can check with a command line ?
