### ISSUE TITLE
all plots were blocked，please tell me the reason，

### ISSUE THREAD

**Issue by xiaoluoabc123** [Chia-Network/chia-blockchain#3199]
**Describe the bug**
all plots were blocked，please tell me the reason，

**Screenshots**

![image](https://user-images.githubusercontent.com/58470835/116669740-83d58680-a9d1-11eb-9c10-368dfec8fd6d.png)
![image](https://user-images.githubusercontent.com/58470835/116669817-99e34700-a9d1-11eb-93a9-a5c9c9a5d94f.png)

**Desktop (please complete the following information):**

- CPU: [e.g. Intel Xeon 2700x]

**Additional context**

**Comment by kongkx** [comment]
I get into a similar situation. "phase 3:6 stop".  

Desktop (please complete the following information):

- CPU:   i5 11400
- RAM: 32G DDR4
- SSD:  WD Black SSD 2T (/mnt/cache),  1T kioxia SSD (/mnt/cache2)

My guess: SWAP triggered.

<img width="1162" alt="截屏2021-05-01 上午7 07 37" src="https://user-images.githubusercontent.com/3049272/116762004-b45a0680-aa4b-11eb-94cc-ca073186e189.png">

<img width="710" alt="截屏2021-05-01 上午7 09 13" src="https://user-images.githubusercontent.com/3049272/116762097-fbe09280-aa4b-11eb-8b72-893a26baeb0f.png">

<img width="825" alt="截屏2021-05-01 上午7 10 35" src="https://user-images.githubusercontent.com/3049272/116762150-203c6f00-aa4c-11eb-9a6f-fc22f89c9545.png">

**Comment by keliew** [comment]
It's not blocked. It's taking its time...

Plotting can take from 4 hours up to days to complete depending on the hardware setup, how many parallel plots, etc.

**Comment by kongkx** [comment]
days.... ，I would like to give it a shot, how many days it would take.

**Comment by Olimiax** [comment]
i have same issue, and i wait n wait , but find out the ssd were not writing/reading at all.
pretty much can say its  Stucked.

**Comment by keliew** [comment]
I had one (K32) that took 3 days.

If it fails, it should normally throw an error message. Haven't seen otherwise.

**Comment by kongkx** [comment]
Should i kill them all....

Just kind of like a dead loop.

![截屏2021-05-04 上午11 19 53](https://user-images.githubusercontent.com/3049272/116957653-f80e7380-acca-11eb-8105-45e4c867e4b8.png)

![截屏2021-05-04 上午11 23 12](https://user-images.githubusercontent.com/3049272/116957711-1eccaa00-accb-11eb-8dc3-b9f9344c43dc.png)

**Comment by sotnikop** [comment]
> I had one (K32) that took 3 days.
> 
> If it fails, it should normally throw an error message. Haven't seen otherwise.

Interesting, You really notice that much variance with how long plots can take? Even though most take 8-10 hrs, some can take 3 days and arent stuck?

**Comment by keliew** [comment]
> > I had one (K32) that took 3 days.
> > If it fails, it should normally throw an error message. Haven't seen otherwise.
> 
> Interesting, You really notice that much variance with how long plots can take? Even though most take 8-10 hrs, some can take 3 days and arent stuck?

That was during the early days when I was doing various tests. And yes, I just left it running. That one that took the longest was plotted over a network.

**Comment by sotnikop** [comment]
> > > I had one (K32) that took 3 days.
> > > If it fails, it should normally throw an error message. Haven't seen otherwise.
> > 
> > 
> > Interesting, You really notice that much variance with how long plots can take? Even though most take 8-10 hrs, some can take 3 days and arent stuck?
> 
> That was during the early days when I was doing various tests. And yes, I just left it running and it completed fine. That one that took the longest was plotted over a network.

My working theory right now is that its thermal throttling on the NVME SSDs. Were you running more than 5-6 plots per SSD by chance? So far 4 is the most stable concurrent plots per SSD for me.

**Comment by keliew** [comment]
> > > > I had one (K32) that took 3 days.
> > > > If it fails, it should normally throw an error message. Haven't seen otherwise.
> > > 
> > > 
> > > Interesting, You really notice that much variance with how long plots can take? Even though most take 8-10 hrs, some can take 3 days and arent stuck?
> > 
> > 
> > That was during the early days when I was doing various tests. And yes, I just left it running and it completed fine. That one that took the longest was plotted over a network.
> 
> My working theory right now is that its thermal throttling on the NVME SSDs. Were you running more than 5-6 plots per SSD by chance? So far 4 is the most stable concurrent plots per SSD for me.

Really depends on the entire setup, not just the SSD.
