### ISSUE TITLE
farm question Beta 8 Released

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [Chia-Network/chia-blockchain#320]
I have been farming  Beta 8 Released and I have some good questions:

what it is more important the Total size of local plots or the size of each plot?

I have No blocks farmed yet after 5 hours.

Total size of local plots :18 GB

11 plots 26 (1.301GB)
6 plots 25 (0.628GB)

can you guys help me with this? thank you.

**Comment by hoffmang9** [comment]
Total size of local plots is all that matters. However note that there will be a plot size minimum in the k = 30 to 32 range for mainnet. These questions are better addresses in the testnet channel on our Keybase channels
