### ISSUE TITLE
When trying to add "introducer-apne.chia.net" the GUI hangs itsel.

### ISSUE THREAD

**Issue by RollingRoland** [Chia-Network/chia-blockchain#3200]
![ChiaCPHang](https://user-images.githubusercontent.com/83419258/116669329-07db3e80-a9d1-11eb-95ef-516ab8f8c31d.jpg)

This has happened for the second time now. When I enter "introducer-apne.chia.net" GUI just gets stuck at the circling Window. The first time I tried the "reload" option which just caused it to be hung a white page with a circle.

Is it possible that the GUI gets stuck, if you try to make the same entry for a second time ?
I can't get my router to permanently to open port 8444 so I am struggling a bit on keeping Chia updating.

**Comment by KinChungE** [comment]
It just mean the introducer is too busy now.
I see you already have many connections properly connected via port 8444, so you don't need to use the introducer
