### ISSUE TITLE
[BUG] Disabling upnp on Windows 10 doesn't stop farming on 1.1.2

### ISSUE THREAD

**Issue by garyhkirk** [Chia-Network/chia-blockchain#3208]
**Describe the bug**
I have a main Win10Pro plotter/farmer that is working fine. The second Win10Pro machine, which has had its upnp for chia disabled (and chia services stopped and restarted) is plotting but also farming. This might be causing confusion according to the chia tips for Windows article.

I know not to expect support here but pointing me to any changes that would cause this to now be expected behaviour would be handy.

**To Reproduce**

1. Set up 2 Win10Pro machines on the same network
2. Allow port 8444 for main machine via router
3. Start plotting and farming on main machine
4. Disable upnp via power shell for secondary machine
5. Close any chia services and start chia GUI on secondary machine
6. Start plotting on secondary machine using same wallet as primary
7. Wait to see that farming starts when a plot completes

**Expected behavior**
Farming should not be possible if upnp is disabled

**Desktop (please complete the following information):**

- OS: Windows 10 Pro, 20H2, fully updated up to yesterday before updates paused for plotting
- CPU: Ryzen 5800x and 5950x

**Comment by JasperHorn** [comment]
Turning off upnp means that some parts are less efficient. It does not mean you turned off farming.

**Comment by vvavepacket** [comment]
How do we turn off farming on the GUI? Like say if we got two machines (farmer, plotter)?

Currently the GUI auto runs the farmer.

**Comment by JasperHorn** [comment]
Remove all plot directories, and make sure to check "Exclude final directory" when making new plots.

**Comment by dorkmo** [comment]
Should be able to go to tak manager and end everything but plotter and daemon
