### ISSUE TITLE
[REQ] Pause function and resume working from .tmp files

### ISSUE THREAD

**Issue by DavidSin02** [Chia-Network/chia-blockchain#3213]
It would be better to functions that can pause the plotting jobs and could resume progress from those tmp files.

**Comment by lvcivs** [comment]
This has been discussed many times already and the developers are well aware that users want this. They are just focused on other things right now but it will likely happen at some point.

**Comment by sargonas** [comment]
as mentioned, this is on the roadmap as discussed in https://github.com/Chia-Network/chia-blockchain/issues/1772
