### ISSUE TITLE
Plot File Error: Invalid Plot Header Magic

### ISSUE THREAD

**Issue by lmitchell94** [Chia-Network/chia-blockchain#3214]
I tried to recovery plot files from a hard drive and copy them to another and now my log is giving me this error message on all the plot files. Are these plot files corrupted and unrecoverable? 

2021-04-29T15:28:27.534 harvester chia.plotting.plot_tools: ERROR    Failed to open file H:\plot-k32-2021-04-14-15-05-fd767242bdb06a65269ab00d28f6c428ea9702fb4e4780b124b3cd902219a44c.plot. Invalid plot header magic Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 183, in process_file
ValueError: Invalid plot header magic

**Comment by Laconiss** [comment]
Me too.i have this probleme too

**Comment by parko86** [comment]
Same here. But seems still farming

**Comment by Laconiss** [comment]
He is not farming...
Normally, it beats every ten seconds

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shibowe** [comment]
Does anyone have to solve this issue ?

**Comment by zx0922** [comment]
same issue

**Comment by lmcke169** [comment]
Same thing happens every time I have to restart chia I lose plots. Just restarted to update to .13 and went from 5 invalid plots to 9.

**Comment by RollingRoland** [comment]
I just encountered this problems for 3 files. 
1) I don't think the drive is the problem. All the plot files that are created on that machine and written on that drive are OK.
2) Only plot files that have been created on another machine and moved manually on that drive are showing up as "Invalid".
3) Files that were created more that 3 days ago and moved in such a way are OK. This makes me suspect that the move from 1.1.2 to 1.1.3 I made around that time has something to do with this issue appearing.

**Comment by opiswahn** [comment]
I also have this issue, but after recovering files from a drive that accidently got it's partition table deleted. So i managed to recover all files, moved them to a new drive but none of the plots is recognized by the chia client...

**Comment by Khunmatthew** [comment]
I have same problem!

**Comment by kc-codepole** [comment]
I have same also 1 plot with: Invalid Plot Header Magic

**Comment by lmcke169** [comment]
Solved most of my issues my reformatting the drives. They were on a sata adapter card that was doing some wacky raid stuff.

**Comment by shibowe** [comment]
> Solved most of my issues my reformatting the drives. They were on a sata adapter card that was doing some wacky raid stuff.

and, Would you like share more details log ? I have the same issues ;

**Comment by davidesan** [comment]
I have a full 10Tb HDD with plots having this error.
If there is a solution, I take it..

**Comment by cantak** [comment]
Help! Same issue on a K35 plot. Thing is 900 GB and took forever to plot. I have 800+ K32s that worked.
