### ISSUE TITLE
Full node stopped syncing

### ISSUE THREAD

**Issue by dkackman** [Chia-Network/chia-blockchain#322]
# environment: 
- 1.0beta8
- windows 10
- installed version
- full node with gui
## symptoms
The full node stopped syncing and filled up the log file with:
```
03:11:23.251 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
03:11:27.129 farmer farmer_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
```

Deleting the blockchain db and restarting seems to have fixed it.

[db.zip](https://github.com/Chia-Network/chia-blockchain/files/4948791/db.zip)
[debug.log.1.zip](https://github.com/Chia-Network/chia-blockchain/files/4948792/debug.log.1.zip)

_
## related
I can't attest to this but prior to this happening but well before i noticed that the sync was not working I had been adding a harvester on a remote machine. At one point as I was figuring out how that was supposed to work I tried manually adding the harvester as a peer on the Framing page. The harvester wasn't configured correctly and the GUI did report an internal error. After deleting the blockchain db both the local harvester and remote harvester seem to be working. So their peer connections recovered along with everything else.

## side note
This put the system into an error state that generated 24MB of logs in about 12 hours. you might want to check the log rotation scheme to ensure it doesn't fill up someones disk if left unattended

**Comment by mariano54** [comment]
From the log file, it looks like you experienced the windows old CPU issue:
ValueError: Given G1 element failed g1_is_valid check

This will be fixed in 1.9, now you can fix this with this workaround 
https://github.com/Chia-Network/chia-blockchain/wiki/Windows-pre-Haswell-1.8-workaround

If you see the error again after the patch, please reopen this ticket. Thanks for the bug report
