### ISSUE TITLE
[help] Wallets Balance not sync

### ISSUE THREAD

**Issue by jeremytiu** [Chia-Network/chia-blockchain#3221]
Dear Support,

I have 2 server which installed Chia.
Server A got 2 coins but server B balance not sync.
Both server confirmed insync status.

**Comment by DerHuette** [comment]
I have the same problem! Is there a way to resync the wallet?

**Comment by keliew** [comment]
Wallet and Farmer do not share the same blockchain locally. So even if the Farmer is synced, the Wallet isn't necessarily synced.

Usually, the wallet takes a longer time to sync...

**Comment by DerHuette** [comment]
jeremytiu, did you copy the blockchain database-file from the first to the second computer? So did I. If so, you have to copy the wallet database-file, too. Now everything is fine and the balance is correct.

**Comment by jeremytiu** [comment]
> jeremytiu, did you copy the blockchain database-file from the first to the second computer? So did I. If so, you have to copy the wallet database-file, too. Now everything is fine and the balance is correct.

how can I copy the db file? Thanks.
First computer have 2 coin, second computer have 2 coin, if I copy the DB file to 2nd computer, will the 2nd cpmuter lost 2 coin?

**Comment by jeremytiu** [comment]
> Wallet and Farmer do not share the same blockchain locally. So even if the Farmer is synced, the Wallet isn't necessarily synced.
> 
> Usually, the wallet takes a longer time to sync...

ststus is sync, but the balance not sync.

**Comment by DerHuette** [comment]
I did a copy of the blockchain database-file (blockchain_v1_mainnet.sqlite) from the directory ...\.chia\mainnet\db from the first to the second computer. And also a copy of the wallet database file (blockchain_wallet_v1_mainnet_xxxxxxxxxx.sqlite) from the directory ...\.chia\mainnet\wallet\db
First shut down chia on both machines.
