### ISSUE TITLE
[REQ]not synced

### ISSUE THREAD

**Issue by penlion** [Chia-Network/chia-blockchain#3224]
**Describe the request**
Full Node- Status： synced
Wallets- Status：not synced

**Images**
![09275819-A492-4823-950E-4B0A610AC0EE](https://user-images.githubusercontent.com/77721549/116723000-a5566280-aa11-11eb-8220-b0a43245e858.jpeg)

![F9B8FBDA-305A-443D-B3BE-7E1BC2C15B45](https://user-images.githubusercontent.com/77721549/116723032-aa1b1680-aa11-11eb-82f0-03d4c4d46bba.jpeg)

why？ how can i solve it

**Comment by RivIrk** [comment]
Такая же проблема...

**Comment by keliew** [comment]
See https://github.com/Chia-Network/chia-blockchain/issues/3221#issuecomment-830622435
