### ISSUE TITLE
[BUG] Daemon Taking up a lot of ram

### ISSUE THREAD

**Issue by harley19801** [Chia-Network/chia-blockchain#3226]
Plotting 10 plots in parallel - default settings. 
2 CPU * 12 cores.  96GB RAM.

process Daemon occupied 50GB RAM
Looks like it happens at 31% plotting

Windows server 2012. Chia 1.1.2

**Comment by idf3d** [comment]
Seems like this is Multiplatform issue. It happens from time to time randomly also on MacOS (GUI version, installed from DMG).
