### ISSUE TITLE
[help] Run CLI on Chia GUI

### ISSUE THREAD

**Issue by KeramxD** [Chia-Network/chia-blockchain#3227]
Hello,
I have installed Chia GUI via dpkg. Where it installs Chia? How can I run Chia CLI?

**Comment by KeramxD** [comment]
Can I run CLI somehow? When I try `. ./activate` in these directories it shows `-bash: ./activate: No such file or directory`

**Comment by sargonas** [comment]
I could be wrong in my memory, but I believe when you install in that method, I don't think the python venv method is needed or included.
