### ISSUE TITLE
[BUG] Plotting throws Offset too large exceptions

### ISSUE THREAD

**Issue by claudiumusat** [Chia-Network/chia-blockchain#3236]
Hello,

It's my first time plotting and on my main machine things are going haywire:

**Describe the bug**
On an 8 core machine with an external Sandisk 2TB SSD, plotting always results in an InvalidStateException:

Log:
2021-04-30T18:35:39.568  chia.plotting.create_plots       : [32mINFO    [0m Creating 1 plots of size 32, pool public key:  8b306efdc4eabdb7adc1251657e8fd05e35a7e7b54aa71c25f6a9c08f10f0a6e27359d3de80f8c059ee6510475171563 farmer public key: b2c74a8b2bdbc6080fdacb02ca3705ae32d3ff757ec89bc4da73a583c068d82b6565aa2b83acb2c131fb86630599864e[0m
2021-04-30T18:35:39.574  chia.plotting.create_plots       : [32mINFO    [0m Memo: 8b306efdc4eabdb7adc1251657e8fd05e35a7e7b54aa71c25f6a9c08f10f0a6e27359d3de80f8c059ee6510475171563b2c74a8b2bdbc6080fdacb02ca3705ae32d3ff757ec89bc4da73a583c068d82b6565aa2b83acb2c131fb86630599864e6c7f8a19e35ae3cae93332c6feb1c2b96cd8dfea6207685c85f628da4ec5bd78[0m
2021-04-30T18:35:39.575  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m

Starting plotting progress into temporary dirs: /media/c/Extreme SSD/chia-temp3 and /media/c/Extreme SSD/chia-temp3
ID: fe60cea616db31b574697341172dd1983a6a9e2735c10581df7e6038e9b2d6d2
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Fri Apr 30 18:35:39 2021
Computing table 1
F1 complete, time: 123.079 seconds. CPU (141.71%) Fri Apr 30 18:37:42 2021

Computing table 2
	Bucket 0 uniform sort. Ram: 3.251GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.

....

	Bucket 124 uniform sort. Ram: 3.251GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 125 uniform sort. Ram: 3.251GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 126 uniform sort. Ram: 3.251GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 127 uniform sort. Ram: 3.251GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Total matches: 4294983014
Forward propagation table time: 1474.752 seconds. CPU (141.820%) Fri Apr 30 19:02:17 2021
Computing table 3
	Bucket 0 uniform sort. Ram: 3.251GiB, u_sort min: 2.250GiB, qs min: 0.563GiB.
terminate called after throwing an instance of 'InvalidStateException'
  what():  Offset too large: 41894

**To Reproduce**
it is not always reproducible - sometimes plotting stops with no error logged.

**Expected behavior**
Plotting stops at 6%

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.4 64bit
- CPU: Intel i7-7700K

**Note: Plotting on the same machine on the internal HDD works flawlessly.**

Thanks for your help!

**Comment by razamataz** [comment]
do not use EXTERNAL disks for plotting

**Comment by sargonas** [comment]
This is likely due to the sleep state or other power saving functionality stemming from using an external drive. It's highly ill advised for plotting as a combination of the latency of going over USB controllers, power saving features of the devices, and more are going to compound a lot of bad news into your reliability.
