### ISSUE TITLE
[REQ] option for less verbose plotting log/output

### ISSUE THREAD

**Issue by bathrobehero** [Chia-Network/chia-blockchain#3238]
I'd love to have an option to omit individual bucket operations.

So no "Bucket X uniform sort. Ram: X.XXXGiB, u_sort min: X.XXXGiB, qs min: X.XXXGiB." lines.

It's a very minor thing but logs would be that much more human readable if we'd only see phases and tables.

The default log is about 207,000 characters (-k 32 -u 128) but without individual bucket progress entries it would only be about 7,000 characters. That's only like a page or two. Please consider it. Cheers!

**Comment by ilylx** [comment]
Good idea!

**Comment by jespino** [comment]
I can do this I think. @hoffmang9 what do you think is the best option here? something like `--verbose` and remove that from the default, maybe something like `--log-level` or maybe something like `--output` that can be `simple` and `full`, but in the future can be something like `jsonl` or `csv` or maybe `progressbar`.

**Comment by jespino** [comment]
I added a preliminary PR here: Chia-Network/chiapos#223 that would allow to disable that "verbose" level in the chiapos library, after that adding the flag in the cli would be very straight forward :)
