### ISSUE TITLE
Very Volatile Speed

### ISSUE THREAD

**Issue by kajode** [Chia-Network/chia-blockchain#3241]
Hey guys,

I got my first plotter up and running now, but the writing keeps on stopping and starting which severly hinders the amount of plots that I can plot.

My specs are: Ubuntu 20.04LTS Chia 1.1.2, i7 6700, 64GB RAM, 2x 1TB NVME

This is what I see using dstat : (the CPU usage seems fine to me with ~70%)

<img width="554" alt="Bildschirmfoto 2021-04-30 um 22 15 16" src="https://user-images.githubusercontent.com/59487189/116753283-23f9d280-aa07-11eb-9de4-446c29f3fd87.png">

Does anyone have an idea what the issue might be?

Thank you in advance!

**Comment by sargonas** [comment]
*auto converting this over to a Discussion to continue community support there, as this does not appear to be an actual development bug at this time.
