### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Crypto-78** [Chia-Network/chia-blockchain#3242]
**Describe the bug**
From today the software no longer synchronizes and this pop up appears as shown in the screenshot with the number 22, if I press OK it reappears after a short time, I uninstalled Chia software and reinstalled, but the problem returns. Can anyone help me? 

**To Reproduce**

1. uninstalled
2. re-installed version 1.1.2
3. a pop up appears after I click on my key
4. Error 22

**Screenshots**
Scroll down for screenshot error

**Laptop Dell**

- OS: Widows 10 PRO
- OS Version/Flavor: PRO
- CPU: Intel I7 11° Generation

![image](https://user-images.githubusercontent.com/83140217/116756138-9ce23580-a9d9-11eb-8b89-32b98b96e4eb.png)

**Comment by Crypto-78** [comment]
Silver. You can close

**Comment by DeanBoucher** [comment]
how could the error be corrected?

**Comment by Crypto-78** [comment]
> how could the error be corrected? 

Sorry, I had to write it down. It was a VPN service that started automatically, when I deactivated it the error disappeared. However there are several bugs on synchronization with nodes,  have to solve I hope.
