### ISSUE TITLE
[BUG] Chia Windows 10 GUI 1.1.2 wallet does NOT synchronize

### ISSUE THREAD

**Issue by Tiger-Stone** [Chia-Network/chia-blockchain#3245]
**Describe the bug**
After updating China GUI (Windows 10) to  v1.1.2, the wallet can not be synchronized. The wallet height freezes at 128 for several days! 
Will this affect farming?
![image](https://user-images.githubusercontent.com/83153410/116757308-bf8a4380-aa05-11eb-9e4c-c4901ae5f7ca.png)

**Comment by CRYPTO-GENIK** [comment]
Same issue here 
reinstalled and no effect

**Comment by lermarck** [comment]
![image](https://user-images.githubusercontent.com/10919704/116768226-2a1b9d80-aa5f-11eb-816f-431512750293.png)

**Comment by joanventura** [comment]
I restarted my PC today.. and i got this.

![image](https://user-images.githubusercontent.com/22986852/116768356-04ad7600-aa04-11eb-9fff-47b1522fd8f1.png)

**Comment by GoPerry** [comment]
> ![image](https://user-images.githubusercontent.com/10919704/116768226-2a1b9d80-aa5f-11eb-816f-431512750293.png)
> I can't syn for 2 day, May i need to reinstall ?

wow, 2days.
I have some Nodes synced in local network.
When one of the Nodes cannot sync, I can connect that to anther local nodes.
Most of time, it can work for me.
JFI.

**Comment by bryankeithflynn** [comment]
Not sure if this will help anyone else but I was having the same problem, so I uninstalled Chia. Then I deleted the C:\Users\User\AppData\Local\chia-blockchain\ directory as well as the C:\Users\User\.chia directory. I reinstalled Chia and it took several minutes but it is Synced and Farming again for now.

**Comment by firstrakly** [comment]
I have same problem. I downgrade to use version 1.1.1 and no problem and fast Sync.

**Comment by Fjorian** [comment]
For me is not syc , and stay a little bit sync and go again not syc in wallet not in full node ,in full node is everything perfect , how ti fix the wallet any idea ?

**Comment by Vizionz** [comment]
Windows 10
Chia Blockchain 1.1.7

Wallet was syncing, but will no longer start syncing.
- Full node is completely synced.
