### ISSUE TITLE
[错误]

### ISSUE THREAD

**Issue by fasl3** [Chia-Network/chia-blockchain#3249]
Why do you always disconnect at three in the morning？

**Comment by dorkmo** [comment]
some people have an ISP that releases and renews everyone IP every night. someone in germany was saying it was causing them issues everyday.

**Comment by fasl3** [comment]
But my other computer was working just fine, all on the same network

> 有些人有一个ISP，每天晚上发布和更新每个人的IP。德国有人说这每天都给他们带来问题

**Comment by fasl3** [comment]
> some people have an ISP that releases and renews everyone IP every night. someone in germany was saying it was causing them issues everyday.

But my other computer was working just fine, all on the same network
