### ISSUE TITLE
farmer_server connection error

### ISSUE THREAD

**Issue by matthijsb** [Chia-Network/chia-blockchain#325]
I installed beta-1.0b8 using the windows installer and generated some plots.. i noticed i dindt farm any chia, so when i looked into the log i noticed that the farmer is not running/connected:

22:52:37.394 farmer farmer_server              : WARNING  Connection error by peer ('127.0.0.1', 57857), closing connection.
22:52:37.401 farmer farmer_server              : WARNING  Connection error by peer ('127.0.0.1', 8444), closing connection.
22:53:31.489 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
22:53:34.454 farmer farmer_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
22:53:36.555 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
22:53:39.492 farmer farmer_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.

I enabled UPnP on my router and removed all firewall restrictions from windows and my router, but still get this error message.. what could i be missing?

**Comment by yllierop** [comment]
Did you happen to get this issue figured out? I just tested in my lab and couldn't duplicate the issue.

**Comment by hoffmang9** [comment]
I helped one of the community members help debug it. It was a toxic interaction between running two full nodes - both using upnp - and having the gateway do "bad things" to the other machine when it handed out a uPnP to the next machine.
