### ISSUE TITLE
[BUG] Pressing "View->Reload" causes application to freeze on "Connecting to Wallet" 

### ISSUE THREAD

**Issue by groovysnake** [Chia-Network/chia-blockchain#3261]
**Describe the bug**

Using version 1.1.2; However, the issue was also present in 1.1.1.
It doesn't matter what I am doing, pressing the Reload or Force Reload causes the application to attempt "Connecting to Wallet..." indefinitely and never continues. The console seems to indicate it is stuck in a bad loop somewhere.

**To Reproduce**

1. Go to 'View'
2. Click on 'Reload'
3. See error

**Expected behavior**

The screen will reload properly, showing up to date stats and information.
![Screenshot 2021-04-30 202123](https://user-images.githubusercontent.com/22457927/116765231-2dc50b00-a9f2-11eb-9182-d74fba987ad5.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 
- OS Version/Flavor: Version	10.0.19042 Build 19042
- CPU: AMD Ryzen 5 5600X

**Additional context**

UPDATE: Still present in 1.2.1.

**Comment by berlef80** [comment]
+1 but this was not only an issue on 1.1.2.  It has been an ongoing issue - so I have never reloaded after two times that it froze everything!

**Comment by DM4DS** [comment]
+1 

Desktop (please complete the following information):

- OS: Win 10
- Build: 20H2
- CPU: AMD Ryzen 9 5900X

**Comment by JoNiLiGhT** [comment]
+1
S.O win 10 pro
Version 20H2
CPU: i9 10900F

**Comment by ssdjet** [comment]
f you get stuck on the "Connecting to wallet" spinner for more than 60 seconds, you will probably want to exit the app, delete your wallet database with Powershell, and then start the app again.
  del ~\.chia\mainnet\wallet\db\blockchain*

**Comment by groovysnake** [comment]
> if you get stuck on the "Connecting to wallet" spinner for more than 60 seconds, you will probably want to exit the app, delete your wallet database with Powershell, and then start the app again.
> del ~.chia\mainnet\wallet\db\blockchain*

I mean, yeah, the way to get around this and get back into the app is to close the app and open it again (which allows it to run again, no need to delete database). However, the button is still broken
