### ISSUE TITLE
Never get proof （about quality_str）

### ISSUE THREAD

**Issue by andy1994220** [Chia-Network/chia-blockchain#3271]
I checked the source code and added the log.
I found that the required_iters calculated by my polt is much larger than sp_interval_iters.
example:
required_iters:4979954281 sp_interval_iters:1728512
I observed that the ultimate reason was because of the get_qualities_for_challenge(sp_challenge_hash) method.

I think my computer configuration is very high.

I want to ask, why I can’t get the proof, can you give me any comments?

**Comment by GoPerry** [comment]
ridiculous thing,  NOTHING got  after two weeks.
each day has 2T Plot adding.

**Comment by keliew** [comment]
probably just means you don't have the winning bingo card(s)...

**Comment by andy1994220** [comment]
> probably just means you don't have the winning bingo card(s)...

I add 200+T plots every day, but I haven't got a proof. Is this normal?

**Comment by andy1994220** [comment]
> ridiculous thing, NOTHING got after two weeks.
> each day has 2T Plot adding.



> ridiculous thing, NOTHING got after two weeks.
> each day has 2T Plot adding.

I add 200+ T plots everyday😣

**Comment by keliew** [comment]
200 plots and 200 TB are two very different things...but either way, yes, it can be normal. Since it's a bingo game (彩票机制).

Are you sure your plots are K32 and above? If you're plotting at K25, those are **all** useless.

**Comment by andy1994220** [comment]
> 200 plots and 200 TB are two very different things...but either way, yes, it can be normal. Since it's a bingo game (彩票机制).
> 
> Are you sure your plots are K32 and above? If you're plotting at K25, those are **all** useless.

Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 7026
Total size of plots: 695.451 TiB
Estimated network space: 1517.316 PiB
Expected time to win: 10 hours and 43 minutes
Note: log into your key using 'chia wallet show' to see rewards for each key

my plots are k32

**Comment by cdm14cn** [comment]
the same issue , I get nothing,it's bug 
version:1.1.2

**Comment by cdm14cn** [comment]
the same issue , I get nothing,it's bug 
version:1.1.2

**Comment by keliew** [comment]
> Farming status: Farming
> Total chia farmed: 0.0
> User transaction fees: 0.0
> Block rewards: 0.0
> Last height farmed: 0
> Plot count: 7026
> Total size of plots: 695.451 TiB
> Estimated network space: 1517.316 PiB
> Expected time to win: 10 hours and 43 minutes
> Note: log into your key using 'chia wallet show' to see rewards for each key
> 
> my plots are k32
So then it's OK and working. Don't be impatient.

**Comment by sdalmeida** [comment]
@andy1994220 did you end up winning any XCH? I would expect you to at least have 2 XCH by now.
If not, check your chia logs and see if your time is less than 5 seconds

```
tail -f ~/.chia/mainnet/log/debug.log | grep "proofs"
```

PS: Keep in mind that you need to enable INFO logs in your config.yaml file (located at  `~/.chia/mainnet/config`)

**Comment by andy1994220** [comment]
> @andy1994220 did you end up winning any XCH? I would expect you to at least have 2 XCH by now.
> If not, check your chia logs and see if your time is less than 5 seconds
> 
> ```
> tail -f ~/.chia/mainnet/log/debug.log | grep "proofs"
> ```
> 
> PS: Keep in mind that you need to enable INFO logs in your config.yaml file (located at `~/.chia/mainnet/config`)

![Screenshot_2021-05-04-11-27-48-91](https://user-images.githubusercontent.com/47084415/116958038-eed1d680-accb-11eb-9bc6-0eb6f639ad75.jpg)
It's always 0.
I have added logs about required_iters and sp_interval_iters. The required_iters is too small to pass the judgment.
![Uploading Screenshot_2021-05-04-11-35-56-98.jpg…]()

**Comment by coder-lb** [comment]
@andy1994220 Have you solved this issue?
