### ISSUE TITLE
[BUG]1.1.2 plotting problem

### ISSUE THREAD

**Issue by hzxiaoyu** [Chia-Network/chia-blockchain#3277]
**Describe the bug**
My setup is amd r5 3600 24G memory 1TB nvem and hdd. win10 system.
I found when I run 4 plotting  at same time(but start one by one after every 20 min) use CMD or powershell , one or two process will random froze,cpu and hdd road at 0%   ,but when I  switch to the CMD window ,put ENTER key,the process will active. I don't know how to fix it. Thank you.
  

scanned table 4
scanned time =  179.950 seconds. CPU (78.430%) Sat May  1 00:53:38 2021
sorting table 4
sort time =  1250.775 seconds. CPU (41.360%) Sat May  1 03:39:02 2021  （it takes 3 hours!)
Backpropagating on table 3
scanned table 3
scanned time =  223.889 seconds. CPU (73.850%) Sat May  1 03:42:46 2021
sorting table 3
sort time =  1456.859 seconds. CPU (36.640%)

**Comment by keliew** [comment]
It's not stuck. It's still running...

**Comment by hzxiaoyu** [comment]
> It's not stuck. It's still running...

If I didn't put the ENTER, the process will keep stuck. You can see sorting table 4 to table 3 ,take 3hours,if I did't put ENTER ,maybe will takes 6 hours.

**Comment by keliew** [comment]
Maybe you need something to keep pressing ENTER.

No, that's not how plotting works.

**Comment by kenelf** [comment]
what is the CMD you mentioned and how to use it? I got a similar problem, the plotting stop during phase 3 compressing table files, no error is popped up, it just stop running, CPU and memory load are unchanged.

**Comment by hzxiaoyu** [comment]
> what is the CMD you mentioned and how to use it? I got a similar problem, the plotting stop during phase 3 compressing table files, no error is popped up, it just stop running, CPU and memory load are unchanged.

wiki_cli command

**Comment by kenelf** [comment]
I am not a programmer, don't know how to use it, do you have any command lines I can copy and paste to run it?
