### ISSUE TITLE
[REQ] Use C++ to revamp the `chia-blockchain`

### ISSUE THREAD

**Issue by liho00** [Chia-Network/chia-blockchain#3278]
**Describe the request**
Python definitely slower than C++ in term of speed, performance. Python is higher level language which I think not suitable for this kind of project (python mostly for researchers for AI modelling). I suggest to use lower level language like C++ to perform those plotting and mining.

Python consume a lot of resources as its higher level language compare to C++, we can use cpython to compile the algorithm calculation or the kernel of the program in order to enhance the performance.

Besides, most of the client computer are windows based, run python on windows 10 is typically much slower than linux-based.

**Comment by qian-fei** [comment]
Brother, the bottom layer is C++

**Comment by liho00** [comment]
> Brother, the bottom layer is C++

Proof me

![Uploading image.png…]()

**Comment by qian-fei** [comment]
> > Brother, the bottom layer is C++
> 
> Prove to me
> 
> ![image](https://user-images.githubusercontent.com/77238199/116781123-7bee1300-aab3-11eb-9964-b348fffabc8a.png)

![image](https://user-images.githubusercontent.com/59504432/116781161-c8395300-aab3-11eb-9a25-fe51290dcfa4.png)
You are so funny

**Comment by qian-fei** [comment]
> > Brother, the bottom layer is C++
> 
> Prove to me
> 
> ![image](https://user-images.githubusercontent.com/77238199/116781123-7bee1300-aab3-11eb-9964-b348fffabc8a.png)

Do you look at the source code? Just look at the source code

**Comment by liho00** [comment]
![image](https://user-images.githubusercontent.com/77238199/116781181-f74fc480-aab3-11eb-8264-bd8c111d87c8.png)

**Comment by liho00** [comment]
> > > Brother, the bottom layer is C++
> > 
> > 
> > Prove to me
> > ![image](https://user-images.githubusercontent.com/77238199/116781123-7bee1300-aab3-11eb-9964-b348fffabc8a.png)
> 
> Do you look at the source code? Just look at the source code

yeah, i did not found any c++ source code.

**Comment by qian-fei** [comment]
> > > > Brother, the bottom layer is C++
> > > 
> > > 
> > > Prove to me
> > > ![image](https://user-images.githubusercontent.com/77238199/116781123-7bee1300-aab3-11eb-9964-b348fffabc8a.png)
> > 
> > 
> > Do you look at the source code? Just look at the source code
> 
> yeah, i did not found any c++ source code.

It's a C + + library called by python. It seems that you don't know python.

**Comment by liho00** [comment]
> > > > > Brother, the bottom layer is C++
> > > > 
> > > > 
> > > > Prove to me
> > > > ![image](https://user-images.githubusercontent.com/77238199/116781123-7bee1300-aab3-11eb-9964-b348fffabc8a.png)
> > > 
> > > 
> > > Do you look at the source code? Just look at the source code
> > 
> > 
> > yeah, i did not found any c++ source code.
> 
> It's a C + + library called by python. It seems that you don't know python.

LMAO, i do know python is based on c++, since python rely on c++, why dont just use c++? python is a programming language not library, u r the one who dont know on python, just show me the c++ code. Give me the link

**Comment by liho00** [comment]
> > > Brother, the bottom layer is C++
> > 
> > 
> > Prove to me
> > ![image](https://user-images.githubusercontent.com/77238199/116781123-7bee1300-aab3-11eb-9964-b348fffabc8a.png)
> 
> ![image](https://user-images.githubusercontent.com/59504432/116781161-c8395300-aab3-11eb-9a25-fe51290dcfa4.png)
> You are so funny

give me the link, lets see am I funny or not

**Comment by qian-fei** [comment]
> give me the link, lets see am I funny or not

https://github.com/Chia-Network/chiapos

**Comment by liho00** [comment]
Ok, its in another repos, my bad. I am funny 🌝
