### ISSUE TITLE
updating beta7 to beta8 - privkey / plots

### ISSUE THREAD

**Issue by dschense** [Chia-Network/chia-blockchain#328]
I tried to update from beta7 to beta8. Iam not able to use my wallet or anything what is working with beta7 on beta8. Iam also not able to use any of my working plots - only new created plots are working.
Iam on Ubuntu 20.04. Is there any working upgrade howto?

**Comment by hoffmang9** [comment]
As the documents point out, 1.8 is a complete breaking change. All old keys and plots no longer work. However new plots should work on mainnet.
