### ISSUE TITLE
[REQ]Add a command line parameter to mark the process

### ISSUE THREAD

**Issue by ilylx** [Chia-Network/chia-blockchain#3281]
I use command line to plot, and generally run multiple processes at the same time.
Sometimes I need to find a specific process, kill it and then delete the temp files because my hard drive is full.
But I can't find it, because inside the task manager, the parameters are the same for each process.
I tried to add custom parameters , but I get the following error:
"Error: Got unexpected extra argument (this_is_p1)"
Is it possible to add a parameter that will allow me to mark these processes.
According to the log, Then I can find the temp files and delete them.
Thanks.

**Comment by sargonas** [comment]
Based on the fact you speak of task manager, I assume you are on windows? Plotman does this really well, it has the ability to kill a plot and nuke all of the files related to it with one command, the only problem is plotman doesn't work smoothly on Windows yet and is still in an experimental state on the WSL platform with less than great results.

**Comment by ilylx** [comment]
I forgot to mention that I am developing a plot management software too, by calling chia.exe to execute task.
