### ISSUE TITLE
[BUG] The cache uses more than 256.6 GB that was claimed on 1.0.4

### ISSUE THREAD

**Issue by hysci** [Chia-Network/chia-blockchain#3282]
**Describe the bug**

The cache uses much more than 256.6 GB that was claimed on 1.0.4. Command-line was executed on ubuntu. 

**To Reproduce**

1. git clone chia-blockchain repo, switch to 1.1.2 branch
2. Execute command 
`. ./activate && chia plots create -e -k 32 -b 3390 -r 1 -u 128 -n 1 -t /cache/01 -2 /cache/02 -d /chia`
3. Monitor /cache/02 and /cache/01 with ` while true; do du . --max-depth=1 >> test.log; sleep 600; done`

**Expected behavior**
The cache used at `/cache/01` should be 256.6GB, not >300GB

**Screenshots**

![image](https://user-images.githubusercontent.com/6468488/116772455-cbb3e680-aa81-11eb-96c1-b77dd412cc66.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- OS Version/Flavor: 20.04
- CPU: AMD EYPC 7302

**Additional context**
Reference:
https://chiadecentral.com/chia-plotting-improvements-in-version-1-04/

**Comment by max918** [comment]
according to Plot Sizes (k-sizes) in Wiki page
create K32 plot should use 332GB during creating temporary space

**Comment by sargonas** [comment]
your command example has `-e` in it, which is the flat to disabled Bitfield Plotting. Doing so generates about 12% or more data, which would account for your size increase. Try it again without the -e (assuming your CPU supports it) and I suspect the results will be more in line with what you expect.
