### ISSUE TITLE
[help]Отваливается подключение от других узлов

### ISSUE THREAD

**Issue by helixn** [Chia-Network/chia-blockchain#3285]
Отваливается подключение от других узлов, как решить проблему
![2021-05-01_08-49-39](https://user-images.githubusercontent.com/30460422/116772860-71535f80-aa5a-11eb-92d2-08b0f1a997d1.png)
![2021-05-01_08-53-24](https://user-images.githubusercontent.com/30460422/116772910-bf686300-aa5a-11eb-8911-b5f6678c0428.png)

**Comment by karlvilkas** [comment]
та же проблема, походу нет решения

**Comment by pokemordum** [comment]
Аналогично

**Comment by filippovpa** [comment]
Вот что предположительно помогло мне
-Получил статичный IP у провайдера
-Открыл 8444 порт(обязательно чекаем на спец сайте)
-Переустановил прогу
-На роутере включил UPNP

Иногда бывает Not Synced, но обычно в течении 10-30 минут находит пиры
