### ISSUE TITLE
[REQ]哪里请来的小学生做的软件，一堆不符合正常逻辑的行为

### ISSUE THREAD

**Issue by RagnarokChan** [Chia-Network/chia-blockchain#3289]
1：P盘期间没有任何暂停操作，现在新版还不能删除，一个不小心操作错了等全部仆街
2：缓存中途出了问题一直占盘还要自己删，莫名其妙的行为逻辑
3：Plot文件在种田的时候要删居然可以随便删？不是应该被软件占用？
4：奇奇怪怪的断同步，半天连不回去，1.12号称改善却不觉得改善了啥
5：P盘并发和队列好像个NT一样，同样K32并发P5个，再加队列居然就直接开始了。那你们了解啥叫队列啥叫并发了么？
6：关了GUI还在P盘，重新打开GUI上的进度就没了。那你们搞GUI干嘛？

你们是不是找小学生来写程序的啊？还是不会写GUI就别搞UI了。

**Comment by liuzhen1984** [comment]
C:\Users\liuzh>chia.exe version
1.1.2

C:\Users\liuzh>chia.exe show -s
Current Blockchain Status: Not Synced. Peak height: 211318

Always this status:  Not Synced

**Comment by nqzhang** [comment]
暴躁老哥

**Comment by GoPerry** [comment]
暴躁老哥当场发飙

逐个软件的bug 非常多，最明显的就是一个同步问题

不能同步，种多少田都枉然。

**Comment by RagnarokChan** [comment]
> 暴躁老哥当场发飙
> 
> 逐个软件的bug 非常多，最明显的就是一个同步问题
> 
> 不能同步，种多少田都枉然。

都2年了还这种水平,你说是不是活该被骂

**Comment by ilylx** [comment]
用命令行操作吧，比软件方便很多。

**Comment by RagnarokChan** [comment]
> 用命令行操作吧，比软件方便很多。

我把现在的P完了都打算这样操作了。UI太蠢

**Comment by ragnarokna** [comment]
白嫖屁还这么多，你这么牛逼怎么不去自己写呀，玩一个小学生写的软件是因为你tm幼儿园没毕业吗？

**Comment by ragnarokna** [comment]
啊，忘了，你国家主席也是小学生。

**Comment by RagnarokChan** [comment]
> 白嫖屁还这么多，你这么牛逼怎么不去自己写呀，玩一个小学生写的软件是因为你tm幼儿园没毕业吗？

笑，你这逻辑连幼儿园都不如，有问题还不给说？你去做产品就这水平？低能

**Comment by ragnarokna** [comment]
> > 暴躁老哥当场发飙
> > 逐个软件的bug 非常多，最明显的就是一个同步问题
> > 不能同步，种多少田都枉然。
> 
> 都2年了还这种水平,你说是不是活该被骂

人家两年开发出来这东西还算好的了。给你20来年你不也照样活成现在这傻逼样。

**Comment by ragnarokna** [comment]
> > 白嫖屁还这么多，你这么牛逼怎么不去自己写呀，玩一个小学生写的软件是因为你tm幼儿园没毕业吗？
> 
> 笑，你这逻辑连幼儿园都不如，有问题还不给说？你去做产品就这水平？低能

你去做产品？先做个人吧。

**Comment by RagnarokChan** [comment]
> > > 白嫖屁还这么多，你这么牛逼怎么不去自己写呀，玩一个小学生写的软件是因为你tm幼儿园没毕业吗？
> > 
> > 
> > 笑，你这逻辑连幼儿园都不如，有问题还不给说？你去做产品就这水平？低能
> 
> 你去做产品？先做个人吧。

笑死我了还做人，洗涤狗PRPR？不好意思我侮辱狗了

**Comment by RagnarokChan** [comment]
> > > 暴躁老哥当场发飙
> > > 逐个软件的bug 非常多，最明显的就是一个同步问题
> > > 不能同步，种多少田都枉然。
> > 
> > 
> > 都2年了还这种水平,你说是不是活该被骂
> 
> 人家两年开发出来这东西还算好的了。给你20来年你不也照样活成现在这傻逼样。

看来你应该是开发者啊？戳到你那G点了？要是每个人做开发把用户都当傻逼那还得了哦。你尽管吠吧傻狗。反正我说出来也预料不会改。笑。你就继续洗涤吧工具人

**Comment by ragnarokna** [comment]
这么牛逼就去自己做产品啊，我看两年以后你能做个什么清明上坟图出来😫。怕不是连个HelloWorld都是copy的吧。😫

**Comment by ragnarokna** [comment]
> > > > 暴躁老哥当场发飙
> > > > 逐个软件的bug 非常多，最明显的就是一个同步问题
> > > > 不能同步，种多少田都枉然。
> > > 
> > > 
> > > 都2年了还这种水平,你说是不是活该被骂
> > 
> > 
> > 人家两年开发出来这东西还算好的了。给你20来年你不也照样活成现在这傻逼样。
> 
> 看来你应该是开发者啊？戳到你那G点了？要是每个人做开发把用户都当傻逼那还得了哦。你尽管吠吧傻狗。反正我说出来也预料不会改。笑。你就继续洗涤吧工具人

然而傻逼的并不是用户，傻逼的只是你自己而已。估计是你爹妈死的早，没教过你做人是吧。🤔

**Comment by ragnarokna** [comment]
> > > > 白嫖屁还这么多，你这么牛逼怎么不去自己写呀，玩一个小学生写的软件是因为你tm幼儿园没毕业吗？
> > > 
> > > 
> > > 笑，你这逻辑连幼儿园都不如，有问题还不给说？你去做产品就这水平？低能
> > 
> > 
> > 你去做产品？先做个人吧。
> 
> 笑死我了还做人，洗涤狗PRPR？不好意思我侮辱狗了

啊，原来你侮辱了你爹。🤔

**Comment by ragnarokna** [comment]
满嘴喷粪的蜘蛛不要老跳出来丢人献眼。🤔汉字都被你用脏了。😫还礼仪之邦哩。

**Comment by ragnarokna** [comment]
啊，忘记了，是小学生之邦。看来爹妈死的早，小学老师又没教你怎么做个人呀。😏要不你去当个国家主席看看？

**Comment by ragnarokna** [comment]
什么来着，习近平小熊维尼。

**Comment by hoffmang9** [comment]
把它关掉。 GUI中的资源分配中存在一个已知问题，该问题将在今天发布。

**Comment by hoffmang9** [comment]
See https://github.com/Chia-Network/chia-blockchain/commit/0f57b11af5294115450c5c1775c22c7ee3fe4af8

**Comment by kenelf** [comment]
> > 用命令行操作吧，比软件方便很多。
> 
> 我把现在的P完了都打算这样操作了。UI太蠢

怎样用命令行P盘？

**Comment by kenelf** [comment]
> 用命令行操作吧，比软件方便很多。

请问怎样用命令行操作？

**Comment by potato1992** [comment]
简直不能同意更多，庄家手握2100w个币如此巨额的收益，就做出来这么个玩意，看他实现功能的进度，活跃研发人员估计最多就两个人吧，设计的这个逻辑说明他们肯定没产品经理，更别提测试人员了。一个进度中断恢复进度到现在都没实现，打着P2P之父的名号，结果连个同步都做不稳定。只会Python的都是垃圾程序员，结果python都能弄出来这么多bug。这一群只想着钱的庄家你说后天上市他们甩了2100w币跑路我都信。

**Comment by RagnarokChan** [comment]
> > 用命令行操作吧，比软件方便很多。
> 
> 请问怎样用命令行操作？

谷歌上面教程很多的，稍微搜下就行

**Comment by RagnarokChan** [comment]
> 简直不能同意更多，庄家手握2100w个币如此巨额的收益，就做出来这么个玩意，看他实现功能的进度，活跃研发人员估计最多就两个人吧，设计的这个逻辑说明他们肯定没产品经理，更别提测试人员了。一个进度中断恢复进度到现在都没实现，打着P2P之父的名号，结果连个同步都做不稳定。只会Python的都是垃圾程序员，结果python都能弄出来这么多bug。这一群只想着钱的庄家你说后天上市他们甩了2100w币跑路我都信。

哈哈，还有莫名其妙的恨国党+洗涤狗出现我也是很佩服。我也就是挂闲置硬盘就不搞了。都能试出这么多问题。

**Comment by wanningfe** [comment]
GUI 的行为在 windows 和 UNIX/LINUX 下不一致：windows无法删除 P图任务，但是 Linux 和 macOS 都可以。windows 下加入任务到同名队列会导致第一个加入的任务立刻开始，但是 Linux 和 macOS 下向同名队列增加任务会正确排队。windows 下退出钱包会继续挖矿消耗资源，其他平台退出钱包后会自动停止挖矿。在 Linux 平台下如果 plot 目标文件夹是 samba 挂载点，会导致一个操作不支持的错误，在 macOS 及 windows 下则不存在这个问题。

**Comment by wanningfe** [comment]
钱包的 GUI 是纯 JS编写的，我 debug 了一下。有些功能只提供了 UNIX 兼容的方法，所以 windows 下行为不同。

**Comment by RagnarokChan** [comment]
> 钱包的 GUI 是纯 JS编写的，我 debug 了一下。有些功能只提供了 UNIX 兼容的方法，所以 windows 下行为不同。

dalao厉害，学习了。这么看来Win是真不太适合用官方软件。

**Comment by WyattLiu** [comment]
plot用的C++ library，中断恢复不是写点python调试一下就能搞得。我现在queue都是自己用Perl来fork和管理的。 GUI崩了三四次了。

**Comment by potato1992** [comment]
> plot用的C++ library，中断恢复不是写点python调试一下就能搞得。我现在queue都是自己用Perl来fork和管理的。 GUI崩了三四次了。

不管是不是C++，我都不明白有啥难的，设置多个里程碑节点，每个里程碑保存当前必要的内存数据，中断了，读取上次里程碑位置，继续就行了。 只是他们不想做。

**Comment by GrayXu** [comment]
> 钱包的 GUI 是纯 JS编写的，我 debug 了一下。有些功能只提供了 UNIX 兼容的方法，所以 windows 下行为不同。

electron提供的接口不是跨平台的？我也觉得挺奇怪的…明明只是CLI套个壳子，为啥基础功能还经常出问题。。  

----

@WyattLiu 做resume的逻辑和是cpp实现的pos lib也没太强关系吧。。就像 @potato1992 说的直接暴力保存一个上下文状态就是一个最简单的实现。

----

btw, the trash talk between ragnarokna and RagnarokChan is meaningless and away from tech details

**Comment by changpeng75** [comment]
CLI for Linux也没有好多少，会hang住，会出错跳出。

**Comment by potato1992** [comment]
> CLI for Linux也没有好多少，会hang住，会出错跳出。

是的，我同时有win和ubuntu机器，一开始我以为我写个Windows脚本就行了，结果ubuntu那边也碰到不少问题，今天我把Linux脚本也给写了。。。

**Comment by potato1992** [comment]
> CLI for Linux也没有好多少，会hang住，会出错跳出。

是的，我同时有win和ubuntu机器，一开始我以为我写个Windows cmd脚本就行了，结果ubuntu那边也碰到不少问题，今天我把Linux bash脚本也给写了。。。早知道Linux这边也不好用我一开始用python写算了。

**Comment by changpeng75** [comment]
单盘单任务都会hang住，还是在Linux命令行模式，这软件做得像屎一样。

**Comment by hoffmang9** [comment]
> 单盘单任务都会hang住，还是在Linux命令行模式，这软件做得像屎一样。

您几乎肯定会遇到硬件问题，并且由于它是免费的开放源代码，因此您的请求很值得期待。

**Comment by changpeng75** [comment]
发现一般是hang在阶段转换的位置，这次实在compressing tables 3 and 4结束的时候，下面是进程的堆栈信息：
#0  0x00007fa07c0c6144 in ?? () from /root/chia-blockchain/venv/lib/python3.7/site-packages/chiapos.cpython-37m-x86_64-linux-gnu.so
#1  0x00007fa07c0ca29e in ?? () from /root/chia-blockchain/venv/lib/python3.7/site-packages/chiapos.cpython-37m-x86_64-linux-gnu.so
#2  0x00007fa07c0d602f in ?? () from /root/chia-blockchain/venv/lib/python3.7/site-packages/chiapos.cpython-37m-x86_64-linux-gnu.so
#3  0x00007fa07c0f5e66 in ?? () from /root/chia-blockchain/venv/lib/python3.7/site-packages/chiapos.cpython-37m-x86_64-linux-gnu.so
#4  0x000000000043a58c in _PyMethodDef_RawFastCallKeywords (method=0xe2ec80, self=0x7fa07d842cc0, args=args@entry=0xe884c0, nargs=13, kwnames=kwnames@entry=0x0) at Objects/call.c:694
#5  0x000000000043a8c6 in _PyCFunction_FastCallKeywords (kwnames=0x0, nargs=<optimized out>, args=0xe884c0, func=0x7fa07d845a00) at Objects/call.c:734
#6  _PyObject_FastCallKeywords (callable=0x7fa07d845a00, stack=0xe884c0, nargs=<optimized out>, kwnames=0x0) at Objects/call.c:156
#7  0x00000000004259c7 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4619
#8  _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3093
#9  0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0xe88280) at Python/ceval.c:547
#10 _PyEval_EvalCodeWithName (_co=0x7fa07d588270, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kwnames=0x0, kwargs=0xd37080, kwcount=0, kwstep=1, defs=0x7fa07d840428, defcount=2, kwdefs=0x0, closure=0x0, name=0x7fa07e1c0cb0, qualname=0x7fa07e1c0cb0) at Python/ceval.c:3930
#11 0x000000000043a113 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#12 0x0000000000425fb2 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#13 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3124
#14 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0xd36de0) at Python/ceval.c:547
#15 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fa07e1c10c0, globals=globals@entry=0x7fa07e1bd6e0, locals=locals@entry=0x0, args=args@entry=0x7fa082f8d628, argcount=argcount@entry=1, kwnames=kwnames@entry=0x7fa07debd848, kwargs=0x7fa07debd850, kwcount=34, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fa07e1c0df0, qualname=0x7fa07e1c0df0) at Python/ceval.c:3930
#16 0x0000000000439f53 in _PyFunction_FastCallDict (func=0x7fa07df0a950, args=0x7fa082f8d628, nargs=1, kwargs=0x7fa07deb7500) at Objects/call.c:376
#17 0x000000000042159f in do_call_core (kwdict=0x7fa07deb7500, callargs=0x7fa082f8d610, func=0x7fa07df0a950) at Python/ceval.c:4645
#18 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3191
#19 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0x7fa07deb8210) at Python/ceval.c:547
#20 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fa07e2b0030, globals=globals@entry=0x7fa07e295af0, locals=locals@entry=0x0, args=args@entry=0x7fa083081068, argcount=argcount@entry=0, kwnames=kwnames@entry=0x7fa07debd6f8, kwargs=0x7fa07debd700, kwcount=34, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fa07e1c5550, name=0x7fa07e1c0df0, qualname=0x7fa07e1c0df0) at Python/ceval.c:3930
#21 0x0000000000439f53 in _PyFunction_FastCallDict (func=0x7fa07df16c20, args=0x7fa083081068, nargs=0, kwargs=0x7fa07e2e4cd0) at Objects/call.c:376
#22 0x000000000042159f in do_call_core (kwdict=0x7fa07e2e4cd0, callargs=0x7fa083081050, func=0x7fa07df16c20) at Python/ceval.c:4645
#23 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3191
#24 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0xd9b5c0) at Python/ceval.c:547
#25 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fa07e2abe40, globals=globals@entry=0x7fa07e2985a0, locals=locals@entry=0x0, args=args@entry=0x7fffbf331b40, argcount=argcount@entry=2, kwnames=kwnames@entry=0x7fa07debd1b8, kwargs=0x7fa07debd1c0, kwcount=34, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fa07e2af030, qualname=0x7fa07e2af070) at Python/ceval.c:3930
#26 0x0000000000439f53 in _PyFunction_FastCallDict (func=0x7fa07e27a050, args=0x7fffbf331b40, nargs=2, kwargs=0x7fa07deb4a00) at Objects/call.c:376
#27 0x000000000043b41a in _PyObject_Call_Prepend (callable=0x7fa07e27a050, obj=<optimized out>, args=0x7fa07ed43c10, kwargs=0x7fa07deb4a00) at Objects/call.c:908
#28 0x000000000043b122 in PyObject_Call (callable=0x7fa07e3117d0, args=0x7fa07ed43c10, kwargs=0x7fa07deb4a00) at Objects/call.c:245
#29 0x000000000042159f in do_call_core (kwdict=0x7fa07deb4a00, callargs=0x7fa07ed43c10, func=0x7fa07e3117d0) at Python/ceval.c:4645
#30 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3191
#31 0x000000000041e953 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>) at Objects/call.c:283
#32 0x000000000043a237 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:415
#33 0x0000000000426b75 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#34 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#35 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0xd24280) at Python/ceval.c:547
#36 _PyEval_EvalCodeWithName (_co=0x7fa07e2b3930, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kwnames=0x0, kwargs=0xd23d80, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fa07e2af030, qualname=0x7fa07e2b1a30) at Python/ceval.c:3930
#37 0x000000000043a113 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#38 0x0000000000426b75 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#39 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#40 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0xd23b90) at Python/ceval.c:547
#41 _PyEval_EvalCodeWithName (_co=0x7fa07e2b3930, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>, argcount=2, kwnames=0x0, kwargs=0xda7820, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fa07e2af030, qualname=0x7fa07e2b1a30) at Python/ceval.c:3930
#42 0x000000000043a113 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:433
#43 0x0000000000426b75 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#44 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3110
#45 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0xda7650) at Python/ceval.c:547
#46 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fa07e2b0540, globals=globals@entry=0x7fa07e2985a0, locals=locals@entry=0x0, args=args@entry=0x7fffbf3324f0, argcount=argcount@entry=1, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x7fa07e2a4428, defcount=4, kwdefs=0x0, closure=0x0, name=0x7fa082f837f0, qualname=0x7fa07e2aea80) at Python/ceval.c:3930
#47 0x0000000000439e5f in _PyFunction_FastCallDict (func=0x7fa07e27a560, args=0x7fffbf3324f0, nargs=1, kwargs=<optimized out>) at Objects/call.c:376
#48 0x000000000043b41a in _PyObject_Call_Prepend (callable=0x7fa07e27a560, obj=<optimized out>, args=0x7fa083081050, kwargs=0x7fa081a0e690) at Objects/call.c:908
#49 0x000000000043b122 in PyObject_Call (callable=0x7fa07edb0c80, args=0x7fa083081050, kwargs=0x7fa081a0e690) at Objects/call.c:245
#50 0x000000000042159f in do_call_core (kwdict=0x7fa081a0e690, callargs=0x7fa083081050, func=0x7fa07edb0c80) at Python/ceval.c:4645
#51 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3191
#52 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0x7fa07e5c1ad0) at Python/ceval.c:547
#53 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fa07e2b05d0, globals=globals@entry=0x7fa07e2985a0, locals=locals@entry=0x0, args=args@entry=0x7fffbf332850, argcount=argcount@entry=1, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fa0830811b0, qualname=0x7fa07e2aeb20) at Python/ceval.c:3930
#54 0x0000000000439e5f in _PyFunction_FastCallDict (func=0x7fa07e27a5f0, args=0x7fffbf332850, nargs=1, kwargs=<optimized out>) at Objects/call.c:376
#55 0x000000000043b41a in _PyObject_Call_Prepend (callable=callable@entry=0x7fa07e27a5f0, obj=obj@entry=0x7fa07df2bdd0, args=args@entry=0x7fa083081050, kwargs=kwargs@entry=0x0) at Objects/call.c:908
#56 0x000000000048b6b9 in slot_tp_call (self=0x7fa07df2bdd0, args=0x7fa083081050, kwds=0x0) at Objects/typeobject.c:6402
#57 0x000000000043a7e1 in _PyObject_FastCallKeywords (callable=0x7fa07df2bdd0, stack=<optimized out>, nargs=<optimized out>, kwnames=0x0) at Objects/call.c:199
#58 0x0000000000421a7f in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4619
#59 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3124
#60 0x000000000041e953 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>) at Objects/call.c:283
#61 0x000000000043a237 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Objects/call.c:415
#62 0x0000000000425fb2 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at Python/ceval.c:4616
#63 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3124
#64 0x00000000004e130c in PyEval_EvalFrameEx (throwflag=0, f=0xa7b950) at Python/ceval.c:547
#65 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fa081cc51e0, globals=globals@entry=0x0, locals=locals@entry=0x7fa083037c80, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:3930
#66 0x00000000004e1553 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=locals@entry=0x7fa083037c80, globals=globals@entry=0x0, _co=_co@entry=0x7fa081cc51e0) at Python/ceval.c:3959
#67 PyEval_EvalCode (co=co@entry=0x7fa081cc51e0, globals=globals@entry=0x7fa083037c80, locals=locals@entry=0x7fa083037c80) at Python/ceval.c:524
#68 0x0000000000512a82 in run_mod (arena=0x7fa08304e390, flags=0x7fffbf332ddc, locals=0x7fa083037c80, globals=0x7fa083037c80, filename=0x7fa081ccab70, mod=0xa78538) at Python/pythonrun.c:1035
#69 PyRun_FileExFlags (fp=<optimized out>, filename_str=<optimized out>, start=<optimized out>, globals=0x7fa083037c80, locals=0x7fa083037c80, closeit=1, flags=0x7fffbf332ddc) at Python/pythonrun.c:988
#70 0x0000000000512c03 in PyRun_SimpleFileExFlags (fp=fp@entry=0xa2d310, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffbf332ddc) at Python/pythonrun.c:429
#71 0x000000000051308b in PyRun_AnyFileExFlags (fp=fp@entry=0xa2d310, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7fffbf332ddc) at Python/pythonrun.c:84
#72 0x000000000042ec51 in pymain_run_file (p_cf=0x7fffbf332ddc, filename=<optimized out>, fp=0xa2d310) at Modules/main.c:456
#73 pymain_run_filename (cf=0x7fffbf332ddc, pymain=0x7fffbf332eb0) at Modules/main.c:1635
#74 pymain_run_python (pymain=0x7fffbf332eb0) at Modules/main.c:2896
#75 pymain_main (pymain=pymain@entry=0x7fffbf332eb0) at Modules/main.c:3057
#76 0x000000000042ee69 in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:3092
#77 0x00007fa081f917b3 in __libc_start_main () from /lib64/libc.so.6
#78 0x0000000000428d5e in _start () at Objects/call.c:287

**Comment by changpeng75** [comment]
Process Status：
Name:   chia
Umask:  0022
State:  R (running)
Tgid:   5544
Ngid:   0
Pid:    5544
PPid:   1
TracerPid:      6805
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 512
Groups:  
NStgid: 5544
NSpid:  5544
NSpgid: 5543
NSsid:  5445
VmPeak:  4647664 kB
VmSize:  4320908 kB
VmLck:         4 kB
VmPin:         0 kB
VmHWM:   4048620 kB
VmRSS:      6124 kB
RssAnon:            4240 kB
RssFile:            1884 kB
RssShmem:              0 kB
VmData:  4206236 kB
VmStk:       544 kB
VmExe:      2460 kB
VmLib:     14268 kB
VmPTE:      8368 kB
VmSwap:  4059644 kB
HugetlbPages:          0 kB
CoreDumping:    0
THP_enabled:    1
Threads:        1
SigQ:   2/95420
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000001001006
SigCgt: 0000000180000000
CapInh: 0000000000000000
CapPrm: 0000003fffffffff
CapEff: 0000003fffffffff
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
NoNewPrivs:     0
Seccomp:        0
Speculation_Store_Bypass:       thread vulnerable
Cpus_allowed:   ffff
Cpus_allowed_list:      0-15
Mems_allowed:   00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:      0
voluntary_ctxt_switches:        745032
nonvoluntary_ctxt_switches:     57825

**Comment by GoPerry** [comment]
> > 单盘单任务都会hang住，还是在Linux命令行模式，这软件做得像屎一样。
> 
> 您几乎肯定会遇到硬件问题，并且由于它是免费的开放源代码，因此您的请求很值得期待。

看着像是翻译器回复的

**Comment by hzjsea** [comment]
附议
