### ISSUE TITLE
Sync with LAN peers / Specify external port

### ISSUE THREAD

**Issue by javierin** [Chia-Network/chia-blockchain#3293]
I run 4 different workers at home. They all share the same plots final directory, but each has its own SSD for plotting. However, I can only open port 8444 for a single VM and would like to know what is the best approach in this scenario

Is there a way to open a different port for every VM and configure it in the local vm config?
Is there a way to prioritize sync with local LAN peers?

I have found myself trying to manuall add a peer to sync with a local LAN IP and port and it just simply ignores it, even though that peer I am configuring is synced.

Thanks

**Comment by GoPerry** [comment]
not just you, all of us have the same problem
The SYNC is very big problem to fix.

Developers should find one solution to resolve the syncing issue for all farmers.

**Comment by ilylx** [comment]
I'm not sure it's helpful to do so:

1. Search "8444" in config/config.yaml, replace it to another port.
2. Disable upnp.
3. Set up port forwarding on your router.

**Comment by kswtch** [comment]
You only ever need one full node reachable by port 8444. All your other nodes do not need to be run as a full node. Just run the plotter or harvester daemons as needed. See https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines

**Comment by Xziped** [comment]
ilylx is right, you just have to disable upnp and choose a different port for any node.
there is also an option to set a thrusty network, that can connect even when you have reached your node-connectionlimit :
https://github.com/Chia-Network/chia-blockchain/search?q=exempt_peer_networks
but unfortunally it does not priorytize the local node. it just connect for about 10 minutes, does nothing with the node, and disconnect again ...
