### ISSUE TITLE
The number of connections is very small, some of which have satisfied the block but can't? Is there a stable node to connect?

### ISSUE THREAD

**Issue by lh232510** [Chia-Network/chia-blockchain#3297]

**Comment by lh232510** [comment]
There are few connection nodes, some of which have satisfied the block but can't?

**Comment by lh232510** [comment]
Why refuse my connection?

**Comment by kswtch** [comment]
by default a full node accepts 60 connections. If that limit is reached every other new connection is refused. That is why people should open or forward port 8444 to their full node. There are only so many full nodes people can connect to.

**Comment by lh232510** [comment]
In this case, it's hard to find the right one
