### ISSUE TITLE
Wallet Stuck on connecting to wallet[BUG]

### ISSUE THREAD

**Issue by mrskizo** [Chia-Network/chia-blockchain#3312]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by mrskizo** [comment]
wallet stuck on connecting to wallet.
how to fix this issue.
note that if you delete chia files in user files, roaming and local folder you need to input again your plots and sync the wallet again.
when they will find a fix for this loop

the plotting still in process even the wallet does not connet.

**Comment by bertybassett** [comment]
Are you port forwarding 8444

**Comment by mrskizo** [comment]
hello,
on my router im not port forwarding port 8444.

my windows firewall is off and no antivirus installed.
im using windows 10.
note that plotting is still working and in process even im stuck in this loop.
to fix this issue each time im deleting chia folder in user folder and local folder and roaming folder and re install chia.

once re installed i should import again plots and wait for them to sync.

i guess they need to fix this bug many users are facing same problem.

**Comment by bertybassett** [comment]
you need to forward 8444 or suffer like you are.

**Comment by mrskizo** [comment]
forward it on my router to my pc ip.

or i ahould enable upnp on the router right?

**Comment by mrskizo** [comment]
upnp is enabled on my router

**Comment by bertybassett** [comment]
why not port forward UPNP is a bag of rubbish and if you have 2 PCs doing chia UPNP will not work.

**Comment by bertybassett** [comment]
its worth a try, it free of charge

**Comment by mrskizo** [comment]
so you mean i should forward the port to my main pc.

i have 8 pcs on the network plotting so i should disable ipnp on chia with all of them.and keep it on the main one.

**Comment by bertybassett** [comment]
stop UPNP it bag of rubbish.  Port forward to the farmer's IP.  the plotter don't need 8444.

**Comment by mrskizo** [comment]
but the other stations will work as farmers also i do have hdds installed on these machines too.
my question is can i run at the same.tame ploting and farming on all of these machines on the same network?

**Comment by bertybassett** [comment]
answer no but I have a fudge?  Port forward to computer a for an hour  then port forward to b for an hour and so on and so on.

**Comment by mrskizo** [comment]
so in order to farm the plots on all these machines i must use 1 machine as farmer and add to it as mapped drived the hdds installed on the other machines.

**Comment by bertybassett** [comment]
that is the best easy way or setup farmer and harvesters

**Comment by mrskizo** [comment]
harvester isnonly for farming right?

but what can we do if i want the 8 machines  to plot and farm at the same time the plots they are genetating using the same wallet on the same network.

is it possible?

**Comment by bertybassett** [comment]
you don't

**Comment by mrskizo** [comment]
but why when u remove chia folders and reinstall it after restart the wallet will oepn again.

whitout forwarding 8444

**Comment by bertybassett** [comment]
long story but in short chia is swamped.

**Comment by mrskizo** [comment]
what do you mean

**Comment by bertybassett** [comment]
your wasting mine and your time trying to fight what is a network issue.  You can not port forward or UPNP to more than 1 PC on the same port number.  IS this a design fault on chia's part maybe but they don't advice people to farm on more than 1 PC.
