### ISSUE TITLE
[BUG] You can't delete jobs to create plots

### ISSUE THREAD

**Issue by ARomarioA** [Chia-Network/chia-blockchain#3314]
**Describe the bug**
You can't delete jobs to create plots

**To Reproduce**

1. Go to Plots
2. Click on "Create Plots", and Create
3. Click the ellipsis at the Plots being created or waiting
4. The "Delete" label is not active

**Expected behavior**
I want the ability to delete tasks, both in the queue and in progress

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 7, 10
- Chia Version: 1.1.2

**Comment by JoNiLiGhT** [comment]
Me too

**Comment by lvcivs** [comment]
It is just temporarily disabled while they sort out some issues with it.

**Comment by sargonas** [comment]
The Delete Plot function in the GUI was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21
