### ISSUE TITLE
[BUG] Plots continue to be built when the GUI is closed. Continues to work Chia.exe

### ISSUE THREAD

**Issue by ARomarioA** [Chia-Network/chia-blockchain#3316]
**Describe the error**
Plots continue to be built when the GUI is closed. Continues to work Chia.exe

** Play back**

1. Go to Plots
2. Click on "Create Plots", and Create
3. Close the app, confirm the stop of creating Plots and Farming

** Expected behavior**
Closing the application, stopping all executable files.

** Desktop (please fill in the following information):**

- OS: Windows 7/10
- -Chia Version: 1.1.2

**Comment by rcamarda390** [comment]
I noticed this behavior today was well.

**Comment by deslumoprime** [comment]
The easy workaround is to restart your system and delete the .tmp files when you get back.

**Comment by dmerriman11** [comment]
Or use task manager to kill the chia.exe running processes and delete the tmp files on the temp drives.

**Comment by ARomarioA** [comment]
> The easy workaround is to restart your system and delete the .tmp files when you get back.



> Or use task manager to kill the chia.exe running processes and delete the tmp files on the temp drives.


Your method is not the solution to the problem. I have designated a BUG. BUG requires a solution.

**Comment by ilylx** [comment]
chia.exe continue plotting when GUI crash,  
Is this bad?

**Comment by ChazyTheBest** [comment]
This also happens on Linux, whenever I close the GUI (File -> Exit), I notice that all processes are still open.
