### ISSUE TITLE
要怎么查看P好的田是否完整可用

### ISSUE THREAD

**Issue by yuqingrui520** [Chia-Network/chia-blockchain#3317]
希望可以稍微详细点，不太懂。

**Comment by ilylx** [comment]
命令： chia plots check

**Comment by GrayXu** [comment]
check wiki  
[https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#check](https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#check)
