### ISSUE TITLE
[BUG]not synced

### ISSUE THREAD

**Issue by wu-dennis** [Chia-Network/chia-blockchain#3318]
version number:1.1.2
connections:
(1)IP:127.0.0.1   port 49193/8447
(2)IP:127.0.0.1   port 49202/8449
Do you need to add new nodes?
peak time:05/01/2021 am4:42:49

**Comment by JoNiLiGhT** [comment]
+1

**Comment by macstibs** [comment]
+1

**Comment by alexJew322** [comment]
change time on ur pc on (GMT+3) or smth same its work for me

**Comment by eguill342** [comment]
check if port 8444 is open on your router and add an introducer. worked for me.
https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444

**Comment by Einstein098** [comment]
same Problem at this time there was a reconnect to the internet (new IP)

**Comment by wu-dennis** [comment]
> 
> 
> change time on ur pc on (GMT+3) or smth same its work for me



> 
> 
> change time on ur pc on (GMT+3) or smth same its work for me

make sure you set GMT+3?Can you set GMT+8?

**Comment by wu-dennis** [comment]
> 
> 
> check if port 8444 is open on your router and add an introducer. worked for me.
> https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444

Port is ok.Restarting CHIA is synchronizing but i don't know if the line will drop.

**Comment by wu-dennis** [comment]
> 
> 
> same Problem at this time there was a reconnect to the internet (new IP)

ok.i trying

**Comment by wu-dennis** [comment]
> 
> 
> same Problem at this time there was a reconnect to the internet (new IP)

The system creates 12  IPs by itself

**Comment by hefenglim** [comment]
same i have this issue, connection status show connect, and syncing abt few hours, no peer connected and it change to unsync.

**Comment by wu-dennis** [comment]
> 
> 
> same i have this issue, connection status show connect, and syncing abt few hours, no peer connected and it change to unsync.

After a few hours of syncing,it didn't work.i went to update 1.1.4
