### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JoNiLiGhT** [Chia-Network/chia-blockchain#3321]
**Describe the bug**
does not sync

**Screenshots**

![no sincroniza](https://user-images.githubusercontent.com/83502298/116784969-7372e980-aa6d-11eb-8400-6183efe3e1b6.PNG)

**Desktop (please complete the following information):**

- OS: [Windows 10 pro]
- OS Version20H2 19042.928]
- CPU: [Intel i9 10900f]

**Comment by Einstein098** [comment]
Same Problem since 03:39 

Also Windows 10

**Comment by restre17** [comment]
I have the same problem

Windows 10 pro 20H2
Ryzen 7 5800X

**Comment by Einstein098** [comment]
today the same 
at this time there was a reconnect to the internet (new IP)
