### ISSUE TITLE
增加一个农田文件页面卡住

### ISSUE THREAD

**Issue by yonggu888** [Chia-Network/chia-blockchain#3322]
增加一个农田文件页面卡住了，绘图期间，在点击删除一个文件夹时卡住了，近一个小时还没有反应。

**Comment by yonggu888** [comment]
请教大神帮助指导，如何关掉这个页面而不影响绘图进程？

**Comment by yonggu888** [comment]
[C:\Users\000\Pictures\Saved Pictures](url)

**Comment by JoNiLiGhT** [comment]
omg. write in english please

**Comment by yonggu888** [comment]
Adding a farmland file page got stuck. During drawing, it got stuck when clicking to delete a folder. It hasn't responded for nearly an hour.

**Comment by ragnarokna** [comment]
这种时候还是果断选择结束绘图重启软件吧。没有解决办法。
