### ISSUE TITLE
[BUG]the 1.1.2 update is making me quit this shit!

### ISSUE THREAD

**Issue by Olimiax** [Chia-Network/chia-blockchain#3323]
fix your not syn bug!! or you lose tons player within few day!

**Comment by JoNiLiGhT** [comment]
sure!

**Comment by bertybassett** [comment]
Port forward 8444

**Comment by dmerriman11** [comment]
Already have port 8444 open, two of my wallets stopped syncing 1.1.2, while one on 1.1.1 is still synced. It seems to be an issue with the current version.

**Comment by bertybassett** [comment]
Strange because you can only port forward 8444 to a single machine.

**Comment by dmerriman11** [comment]
I was able to do this to get the wallet to resync. 

If you have a wallet synced, grab the block chain .db file and copy it to your machine that is out of sync.
Windows ("C:\Users\<User profile>\.chia\mainnet\db\blockchain_v1_mainnet.sqlite"

Then manually connect to this node
107.131.74.12 on port 8444

**Comment by simondarrens** [comment]
Almost works, starts to sync but then goes to Not Synced after 5-10 minutes. 
![2021-05-01 16_51_36-Chia Blockchain](https://user-images.githubusercontent.com/83518066/116795976-67535000-aa9e-11eb-834b-ded17a616eac.png)

**Comment by simondarrens** [comment]
upgraded to 1.1.2 appears to be syncing without stopping. so far.

**Comment by alexJew322** [comment]
change time on ur pc for (GMT+3) or smth same. its work for me instantly

**Comment by Dravenex** [comment]
No problems with 1.1.2 at all. Sounds like you need to fix your network and Open Port 8444 to a machine an disable upnp.

**Comment by bertybassett** [comment]
on problem in 1.1.3 either once 8444 is port forwarded.

**Comment by simondarrens** [comment]
yes, mine upgraded to 1.1.2 is fully synced now.

**Comment by spacewaffles309** [comment]
> 
> 
> Strange because you can only port forward 8444 to a single machine. its not possible to port forward to 2 farmers.

But once a single farmer sync's with the outside world, then others on the LAN can sync to the first farmer, right?

**Comment by BannanaDJoe** [comment]
if no farmers there one get all the rewards go for super job....

**Comment by simondarrens** [comment]
mine stopped syncing again on its own.  will try to manually force a connect.

**Comment by simondarrens** [comment]
> mine stopped syncing again on its own. will try to manually force a connect.

I'm back synced. WOW THO. the space leap just in the last few days is crzy.
