### ISSUE TITLE
[BUG] Windows version, can't delete the plot in queue,

### ISSUE THREAD

**Issue by wilsonwu** [Chia-Network/chia-blockchain#3326]
I can understand the plotting can't be deleted, but why the plot in queue also does not allowed to delete?

The same version 1.1.2, mac version can do it.

**Comment by sargonas** [comment]
The Delete Plot function in the GUI was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21

**Comment by wilsonwu** [comment]
If possible please add it back for only delete a plot in queue, I think maybe it has no runtime and files issues, thank you.
