### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by slebedev1976** [Chia-Network/chia-blockchain#3327]
How to add already saved plots for further farming? When specifying a folder with parcels, parcels are not added.

**Comment by lvcivs** [comment]
It is not clear what you mean by 'parcels'. You can add plot directories in the GUI or add them manually to your `config.yaml` file.

**Comment by sargonas** [comment]
Migrating this issue to the Support section in the Discussion forums. You will be best served by moving this over there and out of the issue tracker, where the community can better assist you. (Ideally the issue tracker should be used to focus on bugs and development problems that need to be addressed, with general user support handled in Discussions and Keybase)
