### ISSUE TITLE
[help]How to view my [peer id - 64 char hexadecimal] on main machine

### ISSUE THREAD

**Issue by namen3645** [Chia-Network/chia-blockchain#3332]
[help]How to view my [peer id - 64 char hexadecimal] on main machine, thank you for answer

**Comment by sargonas** [comment]
Migrating this issue to the Support section in the Discussion forums. You will be best served by moving this over there and out of the issue tracker, where the community can better assist you. (Ideally the issue tracker should be used to focus on bugs and development problems that need to be addressed, with general user support handled in Discussions and Keybase)
