### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by zhaozhijun1988** [Chia-Network/chia-blockchain#3335]
how to get coin id from rpc?
parent_coin_info is the parent coin id? coinid = sha256(parent_coin_info, puzzle_hash, value),how to get coin id by rpc interface, thanks

**Comment by sargonas** [comment]
Migrating this issue to the Support section in the Discussion forums. You will be best served by moving this over there and out of the issue tracker, where the community can better assist you. (Ideally the issue tracker should be used to focus on bugs and development problems that need to be addressed, with general user support handled in Discussions and Keybase)
