### ISSUE TITLE
[REQ] add delete plot to windows gui..with also will delete current temp file..

### ISSUE THREAD

**Issue by matralf** [Chia-Network/chia-blockchain#3339]
cannot delete plot in windows gui is a trouble adding new disk without disturbing current farm progress. 

please enable delete plot with also will delete the temp file in the disk.

**Comment by sargonas** [comment]
This function was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21
