### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ElorparTheAncap** [Chia-Network/chia-blockchain#335]
Hi,

I am trying to install CHIA on 18.04 LTS following all the steps of your tutorial.

I have the latest python and electron versions, however I get this error.. any suggestion?

elorpar@elorpar-HP:~/chia-blockchain/electron-react$ npm run electron

> Chia-Blockchain@ electron /home/elorpar/chia-blockchain/electron-react
> electron .

/home/elorpar/chia-blockchain/app.asar.unpacked/daemon
false
/home/elorpar/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../src/daemon/server.py
child process success
file:///home/elorpar/chia-blockchain/electron-react/build/index.html
stderr:   File "../src/daemon/server.py", line 52
    path = f"{application_path}/{executable}.exe"
                                                ^
SyntaxError: invalid syntax
closing code: 1

**Comment by hoffmang9** [comment]
Which install instructions are you following - precisely?

Reading between the lines this should have been your command flow after git clone:
```
cd chia-blockchain
sh install.sh
. ./activate
cd electron-react
npm run build
npm run electron
```
It's also possible you missed the `. ./activate`

**Comment by ElorparTheAncap** [comment]
This instructions: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian

Indeed, no activation :-(

thx
