### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dmerriman11** [Chia-Network/chia-blockchain#3356]
Sorry if this has been answered, I searched the forum before posting.

Is there a reason we are no longer allowed to delete the plot that's been queued? 1.1.0 allowed this, however since 1.1.1 this option has been greyed out.

Am I missing something? Thank you in advance.

**Comment by sargonas** [comment]
This function was temporarily removed in 1.1.0 due to a bug, and is intended to be restored once resolved.

https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md#110-chia-blockchain-2021-04-21
