### ISSUE TITLE
failed to start using chia cmd on Win10

### ISSUE THREAD

**Issue by lyhistory** [Chia-Network/chia-blockchain#336]
got the following error
```
C:\Users\Admin\AppData\Local\Chia-Blockchain\app-0.1.9\resources\app.asar.unpacked\daemon>chia.exe -r "d:\miner\chia" start all
Exception connecting to daemon: Multiple exceptions: [Errno 10061] Connect call failed ('::1', 55400, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 55400)
chia_harvester: started
chia_timelord_launcher: chia_timelord_launcher failed to start. Error: start failed
chia_timelord: chia_timelord failed to start. Error: start failed
chia_farmer: started
chia_full_node: started
chia_wallet: started
```

**Comment by lyhistory** [comment]
I figured out I need to run_daemon first, then start all will not prompt that error, but got the other two errors:
```
chia_timelord_launcher: chia_timelord_launcher failed to start. Error: start failed
chia_timelord: chia_timelord failed to start. Error: start failed
```

**Comment by lyhistory** [comment]
and also the start all command doesn't open up the gui wallet for me

**Comment by hoffmang9** [comment]
The windows install can't be run solely from the command line. You need to launch it from the start menu.

**Comment by lyhistory** [comment]
@hoffmang9 ok, then is it possible to change the default data directory, now the default is C:\Users\Admin\.chia\beta-1.0b9, I successfully migrate it by chia.exe -r "d:\miner\chia" init, but the problem is when I launch the wallet from start menu, it still using the default directory

**Comment by hoffmang9** [comment]
You can set the directory that the harvester farms in the UI or add it to config.yaml

**Comment by lyhistory** [comment]
yes, it works, thanks
