### ISSUE TITLE
[version number: 1.1.3]

### ISSUE THREAD

**Issue by Marcio1964MWPR** [Chia-Network/chia-blockchain#3370]
version number: 1.1.3 is not synchronizing for more than 20 minutes and nothing.

**Comment by alvaropietro** [comment]
Me too

**Comment by Trymon1980** [comment]
Same here. 1.1.2 worked like a charm but after updating to 1.1.3 it's not synching anymore. For a brief second I saw the status synched but it fall back to not synced after that.

**Comment by lvcivs** [comment]
Read: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

**Comment by Trymon1980** [comment]
> Read: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections

I'm aware of this FAQ but wasn't helpful. 1.1.3 doesn't sync. After rolling back to 1.1.2 everything went back to fine and sync was established.
