### ISSUE TITLE
[BUG] Every time when a new version is silently released, my Chia GUI is out of sync. 

### ISSUE THREAD

**Issue by biostone** [Chia-Network/chia-blockchain#3372]
**Describe the bug**

Every time when a new version is silently released, my Chia GUI is out of sync and gets stuck. 

**Expected behavior**

We need Chia GUI auto update itself. Or at lease we need such a option, in case some people want their Chia out of sync all the time. 

**Desktop (please complete the following information):**

This is on Windows 10. I believe the other platforms have the same issue.

**Comment by mariano54** [comment]
Make sure to open port 8444 and you will never go out of sync
