### ISSUE TITLE
[REQ] [Windows] Change the path of Chia CLI that the version number is not included.

### ISSUE THREAD

**Issue by htg1889** [Chia-Network/chia-blockchain#3374]
In the Windows environment, the CLI path is as follows.

```
~\AppData\Local\chia-blockchain\app-1.1.1\resources\app.asar.unpacked\daemon\chia.exe
```

references:
https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference

I think this path is not good because it includes version number like `app-1.1.1`. 
If the path contains a version number, every time you change the version of Chia, we need to modify the path of the environment variable of Chia CLI.

Therefore, I suggest you change the Chia CLI path so that it does not include the version number.

**Comment by biostone** [comment]
Yes! I think this is good enhancement.

**Comment by ilylx** [comment]
Good!
another way: You can add the path to the system environment variable PATH.

**Comment by krifalk** [comment]
Yes, this is a must to allow for proper automation on windows. Would also see that the CLI directory is added to PATH as above. And the possibility to install under Program Files instead of the user space.

**Comment by fullet-tortuga** [comment]
I agree on the path issue, it makes absolutely no sense to change the path in every version plus it makes testing this program a nightmare.

**Comment by leegee333** [comment]
Just use a wildcard in your path string
