### ISSUE TITLE
Chia version 1.1.2 and 1.1.3 [BUG]

### ISSUE THREAD

**Issue by firstrakly** [Chia-Network/chia-blockchain#3380]
When i use Chia version 1.1.2 or 1.1.3 I can sync in 30min. but 30-60min it not Sync again and can't Sync I don't know why.

Now I use Chia version 1.1.1 don't have a problem about Sync
***My desktop***
- OS: window10 
- CPU: AMD Ryzen 7 2700X Eight-Core Processor
- RAM 32.0 GB DDR4 BUS 3200
- internet fiber 1Gbps

**Comment by yapwenbin** [comment]
I just updated an hour ago and the version is 1.1.4 now, but I didn't saw 1.1.4 in the release page
[https://github.com/Chia-Network/chia-blockchain/releases](url)

`chia version
1.1.4.dev0
`

**Comment by firstrakly** [comment]
Thank you, I will wait to use it.
