### ISSUE TITLE
[BUG] moved plots not seen by chia

### ISSUE THREAD

**Issue by WyattLiu** [Chia-Network/chia-blockchain#3387]
**Describe the bug**
over SMB, there are 32 plots are moved from one disk to the shared disk.
However, after adding the paths to the chia-gui, those moved ones are missed.

What kind of permission does chia require to check and see there is a moved/copied plot sitting in a fuse-mounted disk?

**Comment by alvaropietro** [comment]
me too

**Comment by WyattLiu** [comment]
I am able to farm locally with the GUI/CLI, but the thing is that I want there is one light load machine to farm all other plotting machines over SMB. What should I do, please advise.

**Comment by royimous** [comment]
Did you mount the remote folder on your main machine?

**Comment by WyattLiu** [comment]
> Did you mount the remote folder on your main machine?

Yes, standard fuse mount. I can cad and ls and count how many plots I have. In fact, if the mounted volume has partial copied and partial “native” (I.e. 30vs 20)chia will completely ignore 30 plots and only say there is 20 plots. Run chia plots check, it will only show 20 plots Found and then do the rest of the checks.

**Comment by kismonguz** [comment]
In my case i created few plots on an external HDD with my laptop. Disconnect the HDD and attach it to my NUC and all of my plots are not found. If I move back to the original Laptop, the plots seems OK.
Both machine runs Ubuntu and fresh version of Chia.

**Comment by cjcoopertag** [comment]
Did anyone come up with a solution on this?  I am having the same issues.  I plotted over 600 plots in Windows and moving system to Ubuntu.  When the plot directories are added they show up but the GUI does not recognize that they are there.

**Comment by pcebo** [comment]
Is it really impossible to move HDDs from one machine to another? I have some internal and external HDDs with over 300 plots on them. I rebuilt the system they were plotted on ... same CPU but different mobo. Chia 1.1.6 set up in the same way it was set on my previous plotter: disabled upnp; copied the ca directory from full node; chia init -c... Everything seems fine and I'm happily plotting again. BUT... when I add the drives ("Add Plot Directory") that have my 329 plots, they go show as "Not Found Plots" as if the drive is not attached. Refresh does nothing. Reboot does nothing.

I can run plots check fine. They all pass. And mind you, my GUI (on the newly built plotter to which the drivers are connected) is not yet showing sync... but that shouldn't matter. Or the plots should at least show as "unavailable"... not "Not Found".

My main rig (full node) does NOT see the 329 plots... so wtf? Are they gone? I thought they were supposed to just be files that can be moved????

**Comment by pcebo** [comment]
As an FYI to those experiencing this issue... I remember reading in the documentation that the ca directory from main machine might have to be re-copied as chia updates. I haven't had to update the dir on any of my running harvesters (they seem to be farming fine). However, I decided to try re-doing the "chia init -c <directory of main machin ca dir>" command, with a fresh copy.

Not sure if it was just the fact that I redid it... or if it was the fact that I needed the fresh copy of the ca dir... but either way, plots now correctly showing as "unavailable" (cuz still out of sync) and visible/farming on my main rig.

Hope that helps someone.... cuz that was really annoying/scary.
