### ISSUE TITLE
[BUG]I found a serious problem. I tested it here and it clearly reached the block standard. But when I broadcast the block, some chains rejected my request. Do you want to know what the problem is?

### ISSUE THREAD

**Issue by lh232510** [Chia-Network/chia-blockchain#3396]

**Comment by mariano54** [comment]
Can you message me privately on keybase? @sorgente711

**Comment by lh232510** [comment]
What is keybase? Wallet address?

**Comment by lh232510** [comment]
> Can you message me privately on keybase? @sorgente711
?

**Comment by lh232510** [comment]
> Can you message me privately on keybase? @sorgente711

xch12xvzxk8kzxz7v3zkk6ueddvfuy6ed5dzt87v75u32upase79vg8s735mma
