### ISSUE TITLE
Ожидаемое время до выигрыша 3 года

### ISSUE THREAD

**Issue by Dmitriy875** [Chia-Network/chia-blockchain#3398]
Я знаю, что мой компьютер устарел, но не на столько ведь!
3 года фарминга до первого вознаграждения или я что-то неправильно понял?
Или дело в том, что участки засеивались до синхронизации?

**Comment by ifrite-hub** [comment]
> Я знаю, что мой компьютер устарел, но не на столько ведь!
> 3 года фарминга до первого вознаграждения или я что-то неправильно понял?
> Или дело в том, что участки засеивались до синхронизации?

сколько плотов создано? Сейчас сеть растёт с космической скоростью... Имея 1 плот, время добычи больше 5 лет...

**Comment by Dmitriy875** [comment]
3 плота пока что.

**Comment by ifrite-hub** [comment]
> 3 плота пока что.

Я думаю, за май, сеть вырастет в 3-4 раза, время добычи соответственно тоже... Чтобы хоть что-то добывать, нужно пространство не меньше 30Тб.

**Comment by Dmitriy875** [comment]
Это прискорбно. Учитывая цены на жёсткие диски, уже сейчас заиметь 30 Тб обойдётся в стоимость под сотню тысяч RUR.
Рассчитывать мне явно не на что. Остаётся только терпеливо добывать, 3 года комп не перезагружая, а то и это пропадёт, как я понял )
