### ISSUE TITLE
[BUG] Missing plots

### ISSUE THREAD

**Issue by genGrievouz** [Chia-Network/chia-blockchain#3408]
**Describe the bug**
Can't see 3 plots. I have successfully update from version 1.1.2 to 1.1.3. I had plotted 12 plot which were farming. After update chia does not recognize 3 of my plots. What should I do ?

**Desktop**
- OS: Windows 10
- CPU: [i5 4200U]

**Comment by lvcivs** [comment]
Are they in the same directory? Have you tried re-adding the plot directory?

**Comment by Skilloo34000** [comment]
Same bug here !

**Comment by genGrievouz** [comment]
> Are they in the same directory? Have you tried re-adding the plot directory?

Yes. I did that. I still have them in Not found Plots category.

**Comment by jasonq77** [comment]
Same bug here ! 50plots not recognize message 'failled to open’. How to fix it ?

**Comment by Skilloo34000** [comment]
ok my plots are back ! just unistall all chia on your deskstop ,  reinstal 1.13 and  sync since the beginning . add your plot folder . after that , you can seee again error message.  But when you restart chia.exe all plots  farming !   20 on 20 !    I hope that help you guys :)
