### ISSUE TITLE
git下来的1.1.3版本，安装完成后就变成了1.1.4 dev0版

### ISSUE THREAD

**Issue by arde2020** [Chia-Network/chia-blockchain#3409]
> 
> Installing collected packages: chia-blockchain
>   Attempting uninstall: chia-blockchain
>     Found existing installation: chia-blockchain 1.1.4.dev0
>     Uninstalling chia-blockchain-1.1.4.dev0:
>       Successfully uninstalled chia-blockchain-1.1.4.dev0
>   Running setup.py develop for chia-blockchain
> Successfully installed chia-blockchain-1.1.4.dev0

**Comment by yapwenbin** [comment]
Same issue here, upgraded from 1.1.2 and `chia version` now shows `1.1.4.dev0`. I followed this guide to upgrade:
[https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian](url)

There is no 1.1.4 in the release page: [https://github.com/Chia-Network/chia-blockchain/releases](url)

Is there any issue running on 1.1.4?

**Comment by mariano54** [comment]
This is fine, you can assume you are on 1.1.3 if you get 1.1.4 in the version

**Comment by jpfocus** [comment]
i have the same issue.  
>>$ chia version
>>1.1.4.dev0

by the way , why the ubuntu version contains "xxx.dev"?
is [dev] the same with windows ui version without [dev]?
can i farm chia using this [dev] version?
thanks.

**Comment by Ethavn** [comment]
You are on the branch 'latest' followed the official WIKI. Checkout to main
