### ISSUE TITLE
[BUG] GUI reports incorrect date in Wallet > History

### ISSUE THREAD

**Issue by akrobet** [Chia-Network/chia-blockchain#3411]
When doing a re-sync of the blockchain the timestamp in the Wallet > History menu shows the timestamp of when the given block was synced, not when the actual transaction happened, which is wrong, imo.

**To Reproduce**
Re-sync the database.

**Screenshot**
https://imgur.com/a/sKBxbHs

**Expected behavior**
Date is always the time of the transaction has occurred.

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: not relevant

**Comment by ukrainets** [comment]
I was resyncing my wallet and noticed the same issue.
- OS Mac 11.4 (20F71) Intel, 
- Chia 1.2.1

**Comment by loppefaaret** [comment]
bumb

**Comment by loppefaaret** [comment]
bumb

**Comment by pictin** [comment]
This is not a GUI bug. Command `chia wallet get_transactions` yields the same incorrect result.

**Comment by akrobet** [comment]
Any news on this bug? Imo it is not too much to expect the transaction timestamps to be correct.. As @pictin says, it's also incorrect in the CLI, which really is worrying.

**Comment by emlowe** [comment]
In my testing, this is resolved in 1.3.x - the timestamps should all be the timestamp of the block height at which it was confirmed
