### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jaydenkv** [Chia-Network/chia-blockchain#3414]
**Keep on Connecting to wallet**

**Originally I was tried to plot to the temp folder in SSD and final to the folder in external HDD. However my internal SSD is too small and plotted to a limit of SSD max capacity, so the plotting is stop running. Then, I have deleted the content (plots) in temp folder of SSD. Then, I try to re-plotting again, but the network is not synch and take forever to connect to wallet. Please help**

**Desktop (please complete the following information):**

- OS: Windows 
- OS Version/Flavor: Windows 10 Pro
- CPU: AMD Ryzen 5 Pro 3400G

**Comment by Jaydenkv** [comment]
Current status, still try to connecting to wallet... but CPU and external HDD is running non-stop, I believe the plotting is continue although it is not connect to wallet. Please assist with easy language as I don't have any experience on computer coding, thanks.

**Comment by isis59** [comment]
just check you don't have any running chia services : 
- chia.exe which is in charge of plotting
- start_full_node.exe
- start_harvester.exe
- start_wallet.exe

etc....

Or just reboot your machine. 
Once reboot, clean your temp folder. Just launch GUI and waiting until sync

**Comment by remiliacn** [comment]
if you are using windows, use win+R to invoke the Run window, and enter cmd, then click enter button.

In the command prompt, run following commands:
`taskkill /im chia.exe /f`
`taskkill /im start_full_node.exe /f`
`taskkill /imstart_wallet.exe /f`
