### ISSUE TITLE
[BUG] sabotage in code

### ISSUE THREAD

**Issue by inigosola** [Chia-Network/chia-blockchain#3415]
There is a sabotage in code in latest version.
In previous version spanish translation for `farming` was `cultivando` (it is right), but latest version has a very wrong translation `joseando`.

Please, review all code because there could be more dangerous sabotages.

**Comment by inigosola** [comment]
I think the sabotage is in gui but it is important to review the code of the blockchain as wel.

**Comment by Nadeon** [comment]
right, I also noticed. someone wanted to play a "joke"

**Comment by wwwroth** [comment]
Looks like it was committed by @hoffmang9 last week. I'm sure it was just an honest mistake.

https://github.com/Chia-Network/chia-blockchain-gui/commit/1701ae94b7e8471eb476aa8c601f936ecd33b52c#diff-6c2d74923f168d63d9c119c885a9f4d77f0804eaf14376f4651df85999c7cc06R670

https://github.com/Chia-Network/chia-blockchain-gui/pull/297

**Comment by hoffmang9** [comment]
That's an automatic commit from crowdin and means it was changed there. Create an account and change it back as its very easy.

**Comment by Nadeon** [comment]
The correct translation in Spanish is "cultivando" from the verb "cultivar"

**Comment by seeden** [comment]
Hi @inigosola, @Nadeon  and @wwwroth. Please log in to https://crowdin.com/project/chia-blockchain and vote for correct Spanish translations. It will be used in the next release automatically.
