### ISSUE TITLE
[BUG] harvester doesn't connect with <ssl.SSLContext object at 0x000001742EB45748> from UAE only

### ISSUE THREAD

**Issue by MarvinFS** [Chia-Network/chia-blockchain#3417]
**Describe the bug**
I'm trying to run remote harvester in UAE with direct connection via public internet to main node and I get this:

```
2021-05-02T14:22:42.561 harvester harvester_server        : INFO     Cannot connect to host 212.220.xxx.xxx:8447 ssl:<ssl.SSLContext object at 0x000001742EB45748> [Connect call failed ('212.220.xxx.xxx', 8447)]
2021-05-02T14:22:45.577 harvester harvester               : INFO     Reconnecting to peer {'host': '212.220.xxx.xxx', 'port': 8447}
```

If trying the same through VPN via internal IP to internal IP of the main node everything works fine, but VPN is officially forbidden in UAE unless it's government provided VPN...

```
2021-05-02T14:56:42.418 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming d9b418ddac... Found 0 proofs. Time: 0.00000 s. Total 0 plots
2021-05-02T14:56:42.433 harvester harvester_server        : INFO     -> farming_info to peer 192.168.0.6 dfed90ff464b5129d7c74cexxxxx0a5893b3d9b504cc14d348fxxxx
```

Is there anything I can do about it other than changing country which is not a option as hardware is there? I haven't experienced that issues in other countries... only UAE location is affected... No chances of changing ISP either as there is only one company - government related ISP. (well technically 2 ISP companies, but second one is just consumer trademark for the first)

Second question: impossible to install chia linux version in UAE location - install.sh scrip stalls on pip install commands saying network is not accessible, which probably means python repositories are blocked on ISP level... but is there any workarounds? as windows version works fine and syncs fine.... but managing whole windows VM for chia only is a nightmare... 

**Expected behavior**
Chia harvester connects to main node via public internet and it's possible to install linux version

- OS: Ubuntu 20.04 LTS, Windows 2016 server

**Comment by yapwenbin** [comment]
Looks like your ISP blocking port 8447, or any firewall rules / port forwarding not bring setup correctly.

**Comment by MarvinFS** [comment]
no it doesn't connect that I tested already, whether from all other countries I have telnet connects just fine... only UAE is affected... So I'm kinda stuck, not sure what to do in that case...

**Comment by LaHood0815** [comment]
i have the same problem. But on windows machines. The ports 8444 - 8447 are open at the Plotmachine. Checked it with Test-NetConnection and it was true. 
On the windows farming machine i copied the plot machine ca folder and linked it to the farming machine. But if i start the harvester i get the same connection errors:

harvester harvester_server        : INFO     Cannot connect to host 192.168.xxx.xxx:8447 ssl:<ssl.SSLContext object at 0x000001742EB45748> [Connect call failed ('192.168.xxx.xxx', 8447)]
2021-05-02T14:22:45.577 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.xxx.xxx', 'port': 8447}

I use local ip adresses.

**Comment by lapestand** [comment]
I'm also getting similar error when I'm trying to connect harvester and full node remotely, as you see in following:

```
2021-05-05T01:50:07.081 daemon chia.daemon.server         : INFO     Starting Daemon Server
2021-05-05T01:50:07.082 daemon chia.daemon.server         : INFO     Not implemented
2021-05-05T01:50:07.091 daemon chia.daemon.server         : INFO     Waiting Daemon WebSocketServer closure
2021-05-05T01:50:09.877 harvester harvester               : INFO     Started harvester service on network_id: mainnet
2021-05-05T01:50:09.878 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
2021-05-05T01:50:09.895 daemon chia.daemon.server         : INFO     Register service {'service': 'chia_harvester'}
2021-05-05T01:50:09.896 daemon chia.daemon.server         : INFO     registered for service chia_harvester
2021-05-05T01:50:31.093 harvester harvester_server        : INFO     Cannot connect to host myip:8447 ssl:<ssl.SSLContext object at 0x00000201AF1F7978> [Connect call failed ('myip', 8447)]
2021-05-05T01:50:34.097 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
2021-05-05T01:50:55.158 harvester harvester_server        : INFO     Cannot connect to host myip:8447 ssl:<ssl.SSLContext object at 0x00000201AF358438> [Connect call failed ('myip', 8447)]
2021-05-05T01:50:58.175 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
2021-05-05T01:51:19.390 harvester harvester_server        : INFO     Cannot connect to host myip:8447 ssl:<ssl.SSLContext object at 0x00000201AF358668> [Connect call failed ('myip', 8447)]
2021-05-05T01:51:22.399 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
```

Tried to restart harvester and full node, didn't solved.

**Comment by SKYBILLS** [comment]
me too port 8447 is closed , how to open it ?

**Comment by MarvinFS** [comment]
Ok so I figured out what was the issue with only one of my remote harvesters... It was same old stupid me! :) Everything works fine - that harvester had the same keys as main node for some reason, that prevented it to connect to main node... Possibly maybe to check that if fingerprints are the same on both sides to avoid that confusion... I just removed all keys generated new ones, imported main CA certs and here we go - everything works perfectly fine. Now the question why it DID work via LAN even with same certs of both sides, but NOT via public Internet... hmmmm

**Comment by mrzana** [comment]
I still have the same problem, even after deleting the keys:

2021-05-10T00:46:18.699 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2021-05-10T00:46:18.702 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:8447 ssl:<ssl.SSLContext object at 0x106cf1ec0> [Connect 

Any ideas?

**Comment by JokerGT** [comment]
i also have this problem... 
i even downgraded to version 1.1.2 to see if it worked earlier. 
i followed this tutorial: https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines
(btw the config files has changed a bit in the latest version. this turoial needs a tweak i guess)

i get on main node and on the harvester node this ssl error

2021-05-10T08:47:20.677 harvester harvester               : INFO     Reconnecting to peer {'host': '10.0.0.16', 'port': 8447}
2021-05-10T08:47:20.680 harvester harvester_server        : INFO     Cannot connect to host 10.0.0.16:8447 ssl:<ssl.SSLContext object at 0x7f9997210940> [Connect call failed ('10.0.0.16', 8447)]


anyone know how to se this up ?

**Comment by DIlbert25** [comment]
I had the same problem here, on windows 10.

I followed every procedure but there was an error in the connection.

After installing and uninstalling several times, I realized that it was the windows firewall that was blocking the port.

I created a rule for port 8447 and the problem was resolved.

**Comment by tksalarzai** [comment]
> **Describe the bug**
> I'm trying to run remote harvester in UAE with direct connection via public internet to main node and I get this:
> 
> ```
> 2021-05-02T14:22:42.561 harvester harvester_server        : INFO     Cannot connect to host 212.220.xxx.xxx:8447 ssl:<ssl.SSLContext object at 0x000001742EB45748> [Connect call failed ('212.220.xxx.xxx', 8447)]
> 2021-05-02T14:22:45.577 harvester harvester               : INFO     Reconnecting to peer {'host': '212.220.xxx.xxx', 'port': 8447}
> ```
> 
> If trying the same through VPN via internal IP to internal IP of the main node everything works fine, but VPN is officially forbidden in UAE unless it's government provided VPN...
> 
> ```
> 2021-05-02T14:56:42.418 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming d9b418ddac... Found 0 proofs. Time: 0.00000 s. Total 0 plots
> 2021-05-02T14:56:42.433 harvester harvester_server        : INFO     -> farming_info to peer 192.168.0.6 dfed90ff464b5129d7c74cexxxxx0a5893b3d9b504cc14d348fxxxx
> ```
> 
> Is there anything I can do about it other than changing country which is not a option as hardware is there? I haven't experienced that issues in other countries... only UAE location is affected... No chances of changing ISP either as there is only one company - government related ISP. (well technically 2 ISP companies, but second one is just consumer trademark for the first)
> 
> Second question: impossible to install chia linux version in UAE location - install.sh scrip stalls on pip install commands saying network is not accessible, which probably means python repositories are blocked on ISP level... but is there any workarounds? as windows version works fine and syncs fine.... but managing whole windows VM for chia only is a nightmare...
> 
> **Expected behavior**
> Chia harvester connects to main node via public internet and it's possible to install linux version
> 
> * OS: Ubuntu 20.04 LTS, Windows 2016 server

TO EVERYONE FACING THIS PROBLEM,
this is what worked for me , Just go to cmd and type "ipconfig" check your Ip address of both harvester and full node/farmer and then telly these with your config.yaml (harvester), and also in router settings for port forwarding. As my ISP provides dynamic ip so by detecting the ip change i solved this problem

**Comment by sheirys** [comment]
> I'm also getting similar error when I'm trying to connect harvester and full node remotely, as you see in following:
> 
> ```
> 2021-05-05T01:50:07.081 daemon chia.daemon.server         : INFO     Starting Daemon Server
> 2021-05-05T01:50:07.082 daemon chia.daemon.server         : INFO     Not implemented
> 2021-05-05T01:50:07.091 daemon chia.daemon.server         : INFO     Waiting Daemon WebSocketServer closure
> 2021-05-05T01:50:09.877 harvester harvester               : INFO     Started harvester service on network_id: mainnet
> 2021-05-05T01:50:09.878 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
> 2021-05-05T01:50:09.895 daemon chia.daemon.server         : INFO     Register service {'service': 'chia_harvester'}
> 2021-05-05T01:50:09.896 daemon chia.daemon.server         : INFO     registered for service chia_harvester
> 2021-05-05T01:50:31.093 harvester harvester_server        : INFO     Cannot connect to host myip:8447 ssl:<ssl.SSLContext object at 0x00000201AF1F7978> [Connect call failed ('myip', 8447)]
> 2021-05-05T01:50:34.097 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
> 2021-05-05T01:50:55.158 harvester harvester_server        : INFO     Cannot connect to host myip:8447 ssl:<ssl.SSLContext object at 0x00000201AF358438> [Connect call failed ('myip', 8447)]
> 2021-05-05T01:50:58.175 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
> 2021-05-05T01:51:19.390 harvester harvester_server        : INFO     Cannot connect to host myip:8447 ssl:<ssl.SSLContext object at 0x00000201AF358668> [Connect call failed ('myip', 8447)]
> 2021-05-05T01:51:22.399 harvester harvester               : INFO     Reconnecting to peer {'host': 'myip', 'port': 8447}
> ```
> 
> Tried to restart harvester and full node, didn't solved.

Make sure that you do `chia start farmer`. `chia start node` does not start farmer. I think command like `chia status` would be very helpful where information about running services would be displayed.

You can check if farmer is running with telnet.

**Comment by krlabs** [comment]
Have the same probles when check SecurityTrails:

`theHarvester -d domain.com -l 50 -b securityTrails`

`An exception has occurred: Cannot connect to host api.securitytrails.com:443 ssl:<ssl.SSLContext object at 0x7f208ee2f800> [Temporary failure in name resolution]
An exception has occurred: Cannot connect to host api.securitytrails.com:443 ssl:<ssl.SSLContext object at 0x7f208ee2f410> [Temporary failure in name resolution]
An exception has occurred: Cannot connect to host api.securitytrails.com:443 ssl:<ssl.SSLContext object at 0x7f208ee2f890> [Temporary failure in name resolution]
        Done Searching Results`
