### ISSUE TITLE
[BUG]同步正常，但是证明停留在了8:15分，就不动了。

### ISSUE THREAD

**Issue by kis888** [Chia-Network/chia-blockchain#3424]
**Describe the bug**
同步正常，但是证明停留在了8:15分，就不动了。
同步正常，但是证明停留在了8:15分，就不动了。
同步正常，但是证明停留在了8:15分，就不动了。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by BILLFANLL** [comment]
Just close Chia and shutdown chia's processing daemon, then open chia again. I have encountered this bug on 1.1.2 verson
关了chia然后结束chia的deamon进程，再打开就正常了，我也遇到过在1.1.2版本。deamon进程有个bug，他会不断占用内存直到系统崩溃。我plotting了一半自动重启很崩溃。
