### ISSUE TITLE
[bug] WARNING Will not infuse [hash]

### ISSUE THREAD

**Issue by r1235613** [Chia-Network/chia-blockchain#3428]
My debug log is full of the following warnings, is this normal?
![螢幕擷取畫面 2021-05-02 225246](https://user-images.githubusercontent.com/14368787/116817537-618e6500-ab99-11eb-9720-16ee296c74d4.png)
` timelord chia.timelord.timelord   : WARNING  Will not infuse 02ab15add0dfa2834855b43111e73719ab20ad76ad6977475638423ec6430051 because its reward chain challenge is not in the chain`

**Comment by siphonelee** [comment]
Same issue with chia version 1.1.3.

**Comment by bigmisiu** [comment]
Same here :/

**Comment by whitetechnologies** [comment]
same here

**Comment by Dien0** [comment]
still same on 1.1.4

**Comment by slawomir-sikora** [comment]
whether this in any way threatens the process of farming etc?

**Comment by eguill342** [comment]
same for me ! any help or advise ?

**Comment by Dien0** [comment]
the only solution i see which has been used since ancient times **RESTART EVERY SERVICES** 😄

**Comment by Sojtin** [comment]
bump

**Comment by QthePirate** [comment]
I solved this issue on my farm.

I'm running a single farm with two harvesters on separate boxes. 
-All on v1.1.3.
-Farm/Full Node is on Ubuntu 18.04
-Harvesters are on Ubuntu 20.04

I stopped all services. Upgraded everything to 1.1.4. Started everything. No longer received the error.

It is uncertain whether the restart solved it or if the upgrade did. The issue went away.

**Comment by jh442** [comment]
I saw this issue come up randomly while using the UI (full node) on 1.1.5

**Comment by greg-fischer** [comment]
Same here. Restarted services, all systems on 1.1.5. It will clear up, but the next morning I'll find 20-25 of these in the logs. Seems to grow over time.  

This doesn't appear to effect farming , but I'd sure like to know if it does.  I see logs for eligible plots still, but I also haven't seen any rewards in a couple weeks. (which is still understandable at only 200+ plots)

**Comment by Sojtin** [comment]
> I saw this issue come up randomly while using the UI (full node) on 1.1.5

i'm using cli only and getting lots of this warnings.

**Comment by QthePirate** [comment]
It would be nice to get an understanding from devs on what this actually means

**Comment by whitetechnologies** [comment]
This is clearly a bug and we need some clarity. Is this something irrelevant and if so should be removed from WARNING log? Or does this actually affect farming/block creation and thus degrading the network. @hoffmang9 sorry to do this but I think we would appreciate a 5 min look at this and a response.

**Comment by QthePirate** [comment]
@whitetechnologies: to hop on that bandwagon, I think the first thing we care about is:

"Does it impact farming?"

from there it becomes

"How do I make this message go away (if I can)?"

**Comment by zhengzhang2040** [comment]
I also meet this warning. I've got 100T plots and farming for more than 1 week, but I haven't got any coins so far. I deeply doubt .

**Comment by FVierra27** [comment]
Same issue here. 1.1.5. Hoping it isn't affecting my ability to get coins...

**Comment by QthePirate** [comment]
> Same issue here. 1.1.5. Hoping it isn't affecting my ability to get coins...

This is the absolutely the concern. Based on @zhengzhang2040's plots (10-14 days per win estimate), they've got a few days (statistically) for coins to show up for them. So we'll absolutely know soon whether it affects or not.

**Comment by zhengzhang2040** [comment]
> > Same issue here. 1.1.5. Hoping it isn't affecting my ability to get coins...
> 
> This is the absolutely the concern. Based on @zhengzhang2040's plots (10-14 days per win estimate), they've got a few days (statistically) for coins to show up for them. So we'll absolutely know soon whether it affects or not.

2 weeks for now . currently I have 110T, still haven't seen any coins .

**Comment by greg-fischer** [comment]
Just checking my farmer today and finding about 100 of these showing up in the logs now and I can't get any peer connections.  I keep manualy adding new ones and none of them keep a connection.  I hope these "infuse" issues are not related.   Also, I'm just short of 300 plots, still quite small, but 3 weeks and no more rewards.  I guess that's still possible though because its showing a time of 1 month.

**Comment by Noob-granit** [comment]
My logs are also full of the same warning. Just over 80 plots now and no rewards.

Does anyone actually know what this means and how it effects farming, if at all?

**Comment by QthePirate** [comment]
@zhengzhang2040 That's 110 TB of plots, not 110 plots, correct?

**Comment by QthePirate** [comment]
Ok, so I think I found what causes it.

Searching through the Chia code for this warning, I found it here: 

https://github.com/Chia-Network/chia-blockchain/blob/cbc9141689dab3272f4a45358ddb65c42c3fe318/chia/timelord/timelord.py#L157

` def _can_infuse_unfinished_block(self, block: timelord_protocol.NewUnfinishedBlockTimelord) -> Optional[uint64]:
...
...
 if found_index == -1:
                    log.warning(f"Will not infuse {block.rc_prev} because its reward chain challenge is not in the chain")
`

Which leads me to believe it may not be cause by our plots, but from unfinished blocks in the chain.

If anyone in this thread WITH this error receives coins soon, please post it here.

**Comment by zhengzhang2040** [comment]
@QthePirate   oh ,I deeply doubt , is Chia using a new language, but all I see Chia is using  is Python ...  it's just a fake ?

**Comment by JsBergbau** [comment]
Interessting: After 16 days still no official statement. A good question is: Why should developers still be motivated for a (quick) fix? They prefarmed 20 Million (!) Chias. And when reading the tutorial here https://github.com/Chia-Network/chia-blockchain/wiki/Reference-Farming-Hardware#diy-farms with a large HDD farm they even farmed a lot more themselfes. 20 Million Chias is currently much more then 20 Billion Dollars. They started right at the top of a pyramid scheme https://www.cnbc.com/2021/04/23/bitcoin-a-gimmick-and-resembles-a-ponzi-scheme-black-swan-author-.html so they are rich man and they managed to make people think they could also get rich. The price for one chia is insane. They did a good marketing job to convince people to pay so much for it.

**Comment by chrmei** [comment]
Just FYI: I got this warning when I manually started timelord service on my farming machine. Once timelord was disabled again, warning disappeared. As timelord does not seem to be required, disable it. However, read somewhere that with a fast timelord you may have a higher chance to get chia.

**Comment by rcamarda390** [comment]
I am getting this error a lot and I am on 1.2, pooling on space pool

**Comment by hoffmang9** [comment]
This is a normal log message if you are running a timelord. Almost no one needs to or should run a timelord and we suggest you don't. Closing this issue.
