### ISSUE TITLE
[BUG] connection to the wallet outside the local network

### ISSUE THREAD

**Issue by majekqwert** [Chia-Network/chia-blockchain#3454]
Hi,
I get a connection in (Full Node) - wallet to an external ip address 5.141.84.108 I don't know why? Is it on purpose or is it some kind of bug? Someone opened (port) their wallet outside? Of course, I still have a connection to my local wallet and farmer 127.0.0.1

**Comment by djdookie** [comment]
It's worse, this as an incoming connection to YOUR full node.
From manual: "chia show -c" means: "
`-c, --connections     List nodes connected to this Full Node"`

I just also saw this on my connections and opened a discussion here: https://github.com/Chia-Network/chia-blockchain/discussions/4050

**Comment by cartano** [comment]
have the same issue, using chia full node windows UI 1.1.5., showing external IP connections of type wallet to my full node. was able to delete those.

**Comment by maxbelz** [comment]
same here, any ideas?

**Comment by pgreenland** [comment]
Same here, just noticed a few appear while the connection list was building following a restart. Should we be concerned?
