### ISSUE TITLE
[BUG]Instale la ultima version de chia network, y no logra iniciar la aplicación queda tildado en conectando a monedero 

### ISSUE THREAD

**Issue by RiveraEnzo** [Chia-Network/chia-blockchain#3457]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by luismriq** [comment]
I think that i have the same error.
I installed chia on Windows 10, and it stays for hours on this screen
![image](https://user-images.githubusercontent.com/50973317/116830088-cafc7c80-ab75-11eb-8b00-443b9c0c90d4.png)

And trying with the CLI interface I have these errors
![image](https://user-images.githubusercontent.com/50973317/116830180-4e1dd280-ab76-11eb-9900-0d141385a17d.png)
