### ISSUE TITLE
Syncing Issue[BUG]

### ISSUE THREAD

**Issue by Jaydenkv** [Chia-Network/chia-blockchain#3460]
**Syncing Issue, I am not sure whether this is bug or lot. I has been noticed from Full Node Status. My status keep changing from Not Synced to Syncing and to Not Synced. Sometime it's showed Syncing, but sometime it shows Not Synced. However, the connection status remains in Connected. Is that something that I need to worry or pending to fix? Secondly, I am noticed my wallet status always show Not Synced, is that normal? Please advise, thanks. **

- OS: Windows
- OS Windows 10 Pro
- CPU: AMD Ryzen 5 Pro 3400G

**Comment by Shnurockvova** [comment]
+1

**Comment by elforin22** [comment]
me pasa lo mismo y de la nada nunca mas conecto alguna solucion?

**Comment by elforin22** [comment]
en este foro nadie atiende los problemas?
