### ISSUE TITLE
请问绘图好了 出现未找到绘图  是有设定错误吗

### ISSUE THREAD

**Issue by YOU-OPI** [Chia-Network/chia-blockchain#3463]
![camphoto_342241519](https://user-images.githubusercontent.com/83553830/116825088-3b2ff000-abc0-11eb-8d9f-1e2f3fa46b6d.jpg)

**Comment by killerfrost22** [comment]
Check the folder container address

**Comment by YOU-OPI** [comment]
> 檢查文件夾容器地址
文件夾容器地址?  能解釋什麼意事嗎? 麻煩了

**Comment by GrayXu** [comment]
or use CLI instead...
