### ISSUE TITLE
Chia 1.1.3 Centos 8 (зависает на "подключение к кошельку")

### ISSUE THREAD

**Issue by azerikt** [Chia-Network/chia-blockchain#3471]
Установку производил по официальному руководству. При запуске Chia Blockchain, появляется окно запуска и зависает на "подключение к кошельку"... в чем может быть проблема?

**Comment by alexs20** [comment]
> Установку производил по официальному руководству. При запуске Chia Blockchain, появляется окно запуска и зависает на "подключение к кошельку"... в чем может быть проблема?

[RU]
Такая-же лажа. Тотже баг что и тут [https://github.com/Chia-Network/chia-blockchain/issues/2265](#2265), только обойти заменой localhost на 127.0.0.1 не получается. 
[EN]
I have the same issue and seems like the same bug as described here [https://github.com/Chia-Network/chia-blockchain/issues/2265](#2265), but with small difference that workaround of replacing localhost by 127.0.0.1 doesn't work anymore.

**Comment by Romas125** [comment]
1.15 hangs on wallet connections

**Comment by Lardana** [comment]
Were you able to solve this problem?

**Comment by RomanSelischev** [comment]
> Were you able to solve this problem?

Yes

**Comment by Lardana** [comment]
How?😁

**Comment by RomanSelischev** [comment]
> How?😁

🤑🤑🤑 💵💳

**Comment by RomanSelischev** [comment]
> How?😁 

Ok, I copy folder wallet from from another pc with the same key, i think you can install chia on another pc and weigh your key, and then copy the folder

**Comment by 74ls00** [comment]
Chia 1.2.3  Win7 64
Только что скачал. Висит в самом начале
