### ISSUE TITLE
[BUG]请问为什么农场的最新的收割区块高度一直是0？怎么修复？

### ISSUE THREAD

**Issue by wuqing3066** [Chia-Network/chia-blockchain#3473]
请问为什么农场的最新的收割区块高度一直是0？怎么修复？

cpu: i7-4790K
主板：华硕z97_c
系统：Windows 10 专业版 20H2

**Comment by ragnarokna** [comment]
是什么让你认为它在你那里不该是0呢?如果你切换到英文界面并拷贝Last Height Farmed到google搜索引擎你将在第一个结果看到关于Last Height Farmed的解释.而为什么你要到这里提交一个明显不是bug的bug?
