### ISSUE TITLE
[REQ] Farming pool support at protocol level

### ISSUE THREAD

**Issue by zjshen14** [Chia-Network/chia-blockchain#3479]
At the moment of creating this issue, the netspace is said to be over 1.7EiB according to the explorer. It's no longer friendly to solo family farmers given hundreds GiB or single digit TiB spared disk on their PC. This discourages normal people to participates into Chia network, and preventing it from being more decentralized.

Pooling would be a good option for small participants to get consistent incentive day-over-day. It would be helpful if there's farming pool support at the protocol level that meets the following goals:

1. Farmers don't need to unveil the private key (or other credentials) to join a pool.
2. Farmers don't need to re-plot disks to join a new pool, and they could switch the pools by unregistering the plots from one pool and registering them into another.
3. It should be publicly verifiable for a farmer's share in the pool's space at the block time when the pool wins such a block.

**Comment by sargonas** [comment]
Pooling plans have already been announced in previous discussions, and devs have already stated they intend to target a May/June timeframe hopefully to roll it out

**Comment by zjshen14** [comment]
@sargonas glad to hear that. would you please link the announcement or discussion thread?

**Comment by FSys77** [comment]
It is a shame that there are still no non-Chinese farming pools.

The Chia devs should have taken care of a pooling protocol months ago, before the release of main net. Now small miners are fucked and can only watch how the big Chinese mining farms mine all the Chia.

Very disapointed in Chia :-(

**Comment by diveinstructor** [comment]
What do you think about the Chinese Chia "pool" solution like hpool.com?
Executable posted here:
https://github.com/hpool-dev/chia-miner/releases
Without source code of course...

But according to chiaexplorer.com their address
xch1f0ryxk6qn096hefcwrdwpuph2hm24w69jnzezhkfswk0z2jar7aq5zzpfj
is the biggest earner, apparently representing 31% of the network space...

Thank you for your thoughts

-Oliver

**Comment by FSys77** [comment]
> What do you think about the Chinese Chia "pool" solution like hpool.com?

I am using hpool.com right now. I am very well aware that its a bad idea to give them (possibly?) access to the mnemonic (private key), but it is better than nothing. Solo farming is dead for 99% of us.

At least I am making some Chia right now.

I minimized the risk by immediately withdrawing funds from hpool.com to an offline wallet. In the worst case I have to re-plot my files if hpool.com decides to go rogue, but I'm not losing any Chia.

**This is really a sad situation where 99% of all small Chia farmers are in now. Chia developers should have addressed this problem much, much earlier.**

**Comment by diveinstructor** [comment]
> > What do you think about the Chinese Chia "pool" solution like hpool.com?
> 
> I am using hpool.com right now. 

Where you able to actually withdraw any of the Chia you earned there?

I started running hpool.com on a separate clean system about a week ago and then the withdraw limit was 0.1 XCH.
When I just reached this amount the limit was miraculously increased to 0.2 XCH.
I will reach this soon too, and I will be curious if I can transfer my XCH to the Chain.io wallet...

Any experience appreciated.

Cheers Oliver

**Comment by FSys77** [comment]
> Where you able to actually withdraw any of the Chia you earned there?

Yes, but its a real rip off. My earnings are only about 50% of what I should earn according to chiacalculator.com

hpool only gets away with this because they are the only operational pool at the moment. **Again: Shame on the Chia devs for this fucked up situation!**

**Comment by diveinstructor** [comment]
In hpool you need to farm 0.2 XCH to be able to withdraw anything.

**Comment by diveinstructor** [comment]
> My 2c: it’s not necessary to judge a pool based on Chinese or non-Chinese. 

Hey, my concerns are not related to the nationality of hpool. If it is a scam than it virtually does not matter where it is located.
My question was if there are any real world people who were actually been able to withdraw any XCH from hpool.
Their minimum withdraw was raised recently to 0.2 XCH, an amount that is not easy to reach for "small" farmer. Besides this they seemingly keep manipulating the timing of the "recognition" of farming results and the release of the actual withdraw.

This could be a fraud scheme as any small farmers might abandon their farmed XCH at the pool after being unable to produce results within several weeks. As I cannot read most of the comments on the project I am not sure what is going on. I guess most of the farmers who are using Hpool are from China. 

What do you think?

**Comment by zjshen14** [comment]
> Their minimum withdraw was raised recently to 0.2 XCH, an amount that is not easy to reach for "small" farmer. 

Agree. Like I mentioned above, it's not perfect, actually far away. However, the other side of the coin that it's already ~10X more predictable than luckily mining a block to win 2 XCH. More predictable revenue stream but at the risk of losing some (or all) vs less predictable revenue stream but no risk -- this is a tradeoff many smaller farmers have to make before a better solution. And a better solution is what this thread is aiming for.


> This could be a fraud scheme as any small farmers might abandon their farmed XCH at the pool after being unable to produce results within several weeks. As I cannot read most of the comments on the project I am not sure what is going on. I guess most of the farmers who are using Hpool are from China.

These are all good points. My recommendation is to give them feedback to improve, similar to what we did here. Meanwhile, if core dev and community could make solid progress on launching other better pooling service, they will be pressured to improve.

**Comment by Flame36** [comment]
so apparently pool plotting support is getting added the 17th?
source:https://twitter.com/bramcohen/status/1390407484179763202

**Comment by zjshen14** [comment]
@Flame36, I saw it too.

But I didn't find out pool related code commits recently: https://github.com/Chia-Network/chia-blockchain/commits/main. Maybe core team is developing it somewhere else or currently in confidential way.

Does anyone find a thread to track the progress?

**Comment by DuDlikSPB** [comment]
> @Flame36, I saw it too.
> 
> But I didn't find out pool related code commits recently: https://github.com/Chia-Network/chia-blockchain/commits/main. Maybe core team is developing it somewhere else or currently in confidential way.
> 
> Does anyone find a thread to track the progress?

Same question, zero information about pool code

**Comment by Flame36** [comment]
> @Flame36, I saw it too.
> 
> But I didn't find out pool related code commits recently: https://github.com/Chia-Network/chia-blockchain/commits/main. Maybe core team is developing it somewhere else or currently in confidential way.
> 
> Does anyone find a thread to track the progress?

maybe its so people dont get an advantage by using the code and starting to plot before its released for everyone? idk just speculating
