### ISSUE TITLE
No connection to Full Node or Farmer

### ISSUE THREAD

**Issue by mydniteryda** [Chia-Network/chia-blockchain#348]
I had run the beta versions with no issues acquiring coins. I never downloaded V 1.8 but went to 1.9. Now it doesn't seem to be farming coins and never shows a connection to the Full Node. I'm not a coder and running on windows but not sure what the issue might be. Any help would be appreciated. 
![image](https://user-images.githubusercontent.com/61520201/89699696-90bbc280-d8f6-11ea-9ebb-8717e46882a7.png)
[Chia.docx](https://github.com/Chia-Network/chia-blockchain/files/5044484/Chia.docx)

**Comment by hoffmang9** [comment]
The first thing to check is to make sure you don't have zombie Chia processes running. Shut down the GUI and use task manager to make sure there is nothing chia related running. Then restart.

**Comment by mydniteryda** [comment]
Thanks. I uninstalled my who chia program and made sure nothing was left
and it works fine now.
