### ISSUE TITLE
After plotting the plot dont show on farm!

### ISSUE THREAD

**Issue by Gomes1990** [Chia-Network/chia-blockchain#3491]
Since Chia 1.1.2 i need to restart my GUI to plots be count...any help?

**Comment by genGrievouz** [comment]
well same happened to me :( so that I am trying to reinstall, than sync whole network again.
[BUG] Missing plots #3408 
Here is my post... few days ago.

**Comment by Gomes1990** [comment]
any time i finish a plot i need to restart GUI for the plot enter on farm :(

**Comment by Gomes1990** [comment]
maybe because i have login in another pc?

**Comment by genGrievouz** [comment]
Did you diasable upnp ? I had done that. I still having a problem.  Currently I am syncing from 0. I will let you know if that helps.
