### ISSUE TITLE
My balance is gone Help :(

### ISSUE THREAD

**Issue by hbtpoprock** [Chia-Network/chia-blockchain#3494]
I notice it in the morning that chia has new version 1.1.3 so I uninstall the 1.1.2 and reinstall the new version, and now my balance is gone.  My total balance and spendable balance are 0 in the chia app windows10. Is there anyway to recover it? https://www.chiaexplorer.com/blockchain/address/xch13sddwzhzwa28xh8wy8m57jzmrgv2zaz2akct593xrq3lvz4xjmqqvzxfhr

**Comment by caelumdev** [comment]
Same issue, wallet won't sync

**Comment by laochuan** [comment]
Bug is more

**Comment by SS20201978** [comment]
Don't worry. Once wallet is synced fully, you will see the actual balance. It should not be a bug.

**Comment by hbtpoprock** [comment]
@SS20201978 from my point of view, it should show my balance once it found my transaction in one of those blocks, Does it really require fully synced, or just fully downloaded that specific block which contains my txn?

**Comment by dorkmo** [comment]
in order to properly know your balance, it has to scan every block to see when it was created and if any additions and subtractions were  made
