### ISSUE TITLE
when delete a plot in 1.1.3 GUI Crash

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#3497]
I lost my plots. GUI 1.13 crashed when i trying delete 2 plots.
GUI crash and all process of creating plots close too.
My bad...12 plots wasted

**Comment by ksulfa** [comment]
Was this solved? I was facing the same problem

**Comment by SS20201978** [comment]
A quick fix solution is to delete plots only from the harddisk. Never from GUI

**Comment by ksulfa** [comment]
Oh ok i see but i guess that should be resolved because you have to check and be sure you are deleting the exact plot otherwise you will mistakenly delete an almost finished plot. Hope in the future update it will be resolved

**Comment by realbluefish** [comment]
No..the gui crashed

**Comment by yingchenlee** [comment]
Deleting a working plot always crashes in my case. (Both gui and actual plotting)

When 1.1.2 crashes, the background plotting would be working if gui crashes.

**Comment by realbluefish** [comment]
Yes...its true
