### ISSUE TITLE
[Stupid Question] What to drag and drop for chia backup file [help]

### ISSUE THREAD

**Issue by hbtpoprock** [Chia-Network/chia-blockchain#3512]
I'm very new to chia net, just build a system and test the app feature, remove all key. When I try re-login back to my own wallet, the app asks to drag and drop the backup file. What is it for? And where is it stored in my system?

I think the downloaded ledger is stored somewhere in my system because it was fully synced once, and that screen asks me to point the app to that directory, but I don't know where it is stored in windows 10

System: Windows 10

**Comment by lvcivs** [comment]
I guess you mean the dialog for colored coins when restoring your keys from the 24 words. That's optional and you can simply skip it.

**Comment by hbtpoprock** [comment]
@lvcivs If I skip it, does it mean that I have to resync the whole chia db? I think once it was synced, it's fully downloaded and no need to sync the whole ledger again, just need the partial of it continuing from where you left off, isn't it?

**Comment by edtecnologia** [comment]
I also have this doubt because I had to format the PC and I don't know what the backup file is after I put the key.

**Comment by vanthoi** [comment]
> @lvcivs Yes, after you input the 24 words seed, there is the very first or second screen where the app ask to drag and drop the backup file. If I skip it, does it mean that I have to resync the whole chia db again which is time consume? I think once it was synced, it's fully downloaded and no need to sync the whole ledger again, you just need the partial of it to continue from where you left off, isn't it? There must be the data stored in the system that actually help reduce the resync time

Open Run enter %userprofile%/.chia/mainnet/ enter, then copy overwrite folders db and wallet folder to other pc is no need to synchronize again.

**Comment by hbtpoprock** [comment]
> > @lvcivs Yes, after you input the 24 words seed, there is the very first or second screen where the app ask to drag and drop the backup file. If I skip it, does it mean that I have to resync the whole chia db again which is time consume? I think once it was synced, it's fully downloaded and no need to sync the whole ledger again, you just need the partial of it to continue from where you left off, isn't it? There must be the data stored in the system that actually help reduce the resync time
> 
> Open Run enter %userprofile%/.chia/mainnet/ enter, then copy overwrite folders db and wallet folder to other pc is no need to synchronize again.

@vanthoi I'm closing this ticket with many thanks :)
