### ISSUE TITLE
[BUG] En cours de connexion au porte monnaie

### ISSUE THREAD

**Issue by garskull** [Chia-Network/chia-blockchain#3517]
bonjour à tous

depuis hier quand je veux lancer chia blockchain j'ai le message **en cours de connexion au porte-monnaie** qui tourne en boucle.

quelqu'un a déjà eu le même problème ?

merci

![image](https://user-images.githubusercontent.com/83585386/116870571-1022bc00-ac13-11eb-8847-22518f6054c5.png)

**Comment by Aerya** [comment]
Salut,

Oui c'est fréquent même hélas. Fais comme moi, ça marche (à peu près) : 
 - Dernière version (1.1.3)
 - Tu la stoppes
 - Tu vas dans C:\Users\toi et tu fais un backup puis supprimes le dossier .chia
 - Tu relances ton Windows
 - Tu relances CHIA et ça repart
Attention  : 
 - Tu perds tous les plots en cours de création
 - Tu dois indiquer le dossier de tes plots finalisés dans l'onglet Farm pour les reprendre
 
En général ça repart bien. Parfois non alors faut réitérer l'opération quelques fois...
C'est plus simple de faire ça en CLI, en tous cas j'ai pas plantage comme ça sous Linux.

**Comment by garskull** [comment]
j'ai l'impression que sa viens de mon ssd avec les fichier temporaire j'ai que 80go de libre pour le fichier temporaire et il en faut 239go pour créer un plot

**Comment by Aerya** [comment]
Je doute que ce soit lié mais en effet il faut prévoir un SSD ou NVMe de 1To pour plotter à l'aise par 4 ou 5.
