### ISSUE TITLE
[BUG] all plots listed as "Not found Plots" in GUI

### ISSUE THREAD

**Issue by joduncan** [Chia-Network/chia-blockchain#3522]
**Describe the bug**
I have 9 plots that I have plotted on this machine and on 2 other machines. I know it's not recommended in the docs, but I plotted them all by adding my key on each of the 3 machines.

machine A: original full node/farmer/GUI, 2 plots
machine B: originally a 2nd full node/farmer/GUI, 5 plots
machine C: originally not a full node, not a farmer, not a GUI. 2 plots.

At one point, I re-created the SSL/TLS certs on machine C using machine A's ca, per the docs, and connected it as a remote harvester. After reading that the GUI onm achine A will not show plots on harvester C, I moved all plots to machine C.

I started the full node, farmer, and GUI on machine C and added the plots directory in the GUI. After syncing the mainnet blockchain, the "Plots" portion of the GUI shows "these are your Not found Plots:" and lists all 9 plots.

`chia plots check` shows all 9 are valid plots, and shows that all 9 have the same pool & farmer public keys that is present on all 3 machines.

removing the plot directory in the GUI and re-adding it results in the same result: all plots are listed as not found plots. Farm pane of UI shows no farming information, only the "add a plot" wizard card.

**To Reproduce**

see above. it is unclear to me if recreating the machine C's TLS certs with machine A's CA has somehow made it not able to use the plots.

**Expected behavior**
All plots are shown available for use in the GUI, farm tab shows network info and estimate of time to win.

**Screenshots**
I have removed all my ~/.chia directory and am re-downloading the blockchain after re-running "chia init". (Plots are not added yet in GUI, will add them after mainnet sync is complete) If the behavior persists after that, I will add a screenshot to this bug report.

- OS: linux
- OS all hosts are ubuntu 20.04.1
- CPU: Xeon's and Ryzen

**Comment by genGrievouz** [comment]
Well, I am having the same problem but plotting and farming just on one machine.

**Comment by timothy-kimothy** [comment]
I am having the same issue with a different reason.
updated to 1.1.3.
Opened Chia GUI and all my plots are not recognised now.
The CLI plot check is fine.

reinstalled 1.1.3 for the same result.

OS: Windows 10

**Comment by genGrievouz** [comment]
Try to check with Windows Shell. I executed command `chia plot check`, run some tests `.\chia plots check -g E:\plots --challenge-start 120`  and fortunately I have them all farming. GUI works in a pretty buggy way.

**Comment by joduncan** [comment]
@genGrievouz I was using linux machines exclusively, no windows. All the plots were verified valid when they weren't showing up in the farming UI.

Thankfully, removing my chia config, re-init'ing, re-adding my key/wallet, and then re-downloading the blockchain fixed my issue, and my farmer is now recognizing all the local plots (as well as others I am copying over from machines where I am only generating plots)

**Comment by runechronos** [comment]
@genGrievouz did you still copied your cert files (in \.chia\mainnet\config\ssl\ca) from your 1st computer to your others ? cause I have the same issue, the plots were recognized, and the blockchain was synced but i had a "**SSL Certificate error**" on my 2nd computer where i'm farming (I just create plots with my first computer, and send them via the network to my 2nd computer who is actually farming), the 2 computers uses the full node with the same keys.

I didn't have this error before, but as it was not working and i started to have this SSL error, i thought i had to copy the cert files from computer 1 to computer 2, but since  then nothing is working anymore.

**Comment by yourtechcare** [comment]
hey guys :)

I got stuck with same issue, and when i execute command "chia plots check" in Ubuntu 21 with activate (venv)

I got error that my farmer keys and private keys doesn't match with plots, so I kept backup of all my keys and seeds, 

Then used command to check keys "chia keys show"

It was not matching with my first key and seeds,

I did removed all keys from wallet and added first key/seeds using which i did generated plots.

& then reboot my machine and re-added plot directory.

It resolved my issues. All my plots back to farming now.

Hope ! this will help you guys.

**CAUTION** Kindly do it on your own risk and keep back-up of everything before doing this method.

Thanks

**Comment by MrG0rby** [comment]
> I have the same issue, but no matter what I do, the plots won't add. Just shows EVERY plot as "Not found plot". They were made on this machine, with no changes to the machine since it worked last. Windows 10. I'm at a loss. 27 plots that I can't use.

Got same problem here. Any suggests someone?

**Comment by HiwaLee** [comment]
go to users\"usename"\.chia\mainnet\db. copy everything in that folder and save it on your desktop. then close chia program and stop all services in task manager that relates to chia. then uninstall chia from control panel, after that delete the .chia folder mentioned above, finally clean your registry (you can use ccleaner free version or default windows programs) restart pc, install latest chia version and log in to your wallet using your 24 word key and add your plot directories, right after that close chia and don’t let it sync. again go to users"usename".chia\mainnet\db and paste everything you copied from that folder before deleting it and everything will be just fine. this buys alot of time cuz syncing from zero will take about one day now.

**Comment by HiwaLee** [comment]
> 
> 
> **Describe the bug**
> I have 9 plots that I have plotted on this machine and on 2 other machines. I know it's not recommended in the docs, but I plotted them all by adding my key on each of the 3 machines.
> 
> machine A: original full node/farmer/GUI, 2 plots
> machine B: originally a 2nd full node/farmer/GUI, 5 plots
> machine C: originally not a full node, not a farmer, not a GUI. 2 plots.
> 
> At one point, I re-created the SSL/TLS certs on machine C using machine A's ca, per the docs, and connected it as a remote harvester. After reading that the GUI onm achine A will not show plots on harvester C, I moved all plots to machine C.
> 
> I started the full node, farmer, and GUI on machine C and added the plots directory in the GUI. After syncing the mainnet blockchain, the "Plots" portion of the GUI shows "these are your Not found Plots:" and lists all 9 plots.
> 
> `chia plots check` shows all 9 are valid plots, and shows that all 9 have the same pool & farmer public keys that is present on all 3 machines.
> 
> removing the plot directory in the GUI and re-adding it results in the same result: all plots are listed as not found plots. Farm pane of UI shows no farming information, only the "add a plot" wizard card.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> see above. it is unclear to me if recreating the machine C's TLS certs with machine A's CA has somehow made it not able to use the plots.
> 
> **Expected behavior**
> All plots are shown available for use in the GUI, farm tab shows network info and estimate of time to win.
> 
> **Screenshots**
> I have removed all my ~/.chia directory and am re-downloading the blockchain after re-running "chia init". (Plots are not added yet in GUI, will add them after mainnet sync is complete) If the behavior persists after that, I will add a screenshot to this bug report.
> 
>     * OS: linux
> 
>     * OS all hosts are ubuntu 20.04.1
> 
>     * CPU: Xeon's and Ryzen

go to users"usename".chia\mainnet\db. copy everything in that folder and save it on your desktop. then close chia program and stop all services in task manager that relates to chia. then uninstall chia from control panel, after that delete the .chia folder mentioned above, finally clean your registry (you can use ccleaner free version or default windows programs) restart pc, install latest chia version and log in to your wallet using your 24 word key and add your plot directories, right after that close chia and don’t let it sync. again go to users"usename".chia\mainnet\db and paste everything you copied from that folder before deleting it and everything will be just fine. this buys alot of time cuz syncing from zero will take about one day now.

**Comment by HiwaLee** [comment]
> 
> 
> > I have the same issue, but no matter what I do, the plots won't add. Just shows EVERY plot as "Not found plot". They were made on this machine, with no changes to the machine since it worked last. Windows 10. I'm at a loss. 27 plots that I can't use.
> 
> Got same problem here. Any suggests someone?

go to users"usename".chia\mainnet\db. copy everything in that folder and save it on your desktop. then close chia program and stop all services in task manager that relates to chia. then uninstall chia from control panel, after that delete the .chia folder mentioned above, finally clean your registry (you can use ccleaner free version or default windows programs) restart pc, install latest chia version and log in to your wallet using your 24 word key and add your plot directories, right after that close chia and don’t let it sync. again go to users"usename".chia\mainnet\db and paste everything you copied from that folder before deleting it and everything will be just fine. this buys alot of time cuz syncing from zero will take about one day now.

**Comment by HiwaLee** [comment]
> 
> 
> I have the same issue, but no matter what I do, the plots won't add. Just shows EVERY plot as "Not found plot". They were made on this machine, with no changes to the machine since it worked last. Windows 10. I'm at a loss. 27 plots that I can't use.

go to users\username\.chia\mainnet\db. copy everything in that folder and save it on your desktop. then close chia program and stop all services in task manager that relates to chia. then uninstall chia from control panel, after that delete the .chia folder mentioned above, finally clean your registry (you can use ccleaner free version or default windows programs) restart pc, install latest chia version and log in to your wallet using your 24 word key and add your plot directories, right after that close chia and don’t let it sync. again go to users"usename".chia\mainnet\db and paste everything you copied from that folder before deleting it and everything will be just fine. this buys alot of time cuz syncing from zero will take about one day now.

**Comment by marrik96** [comment]
Also important to note.  With GUI version 1.2.3 if you restart your full node and you have a plot directory offline or missing it appears that none of the plots will come online.  This was my experience.  As soon as I fixed network issue with one of my NAS all plots came online.
