### ISSUE TITLE
[BUG] runtime error: unknown exception or hang when plotting 2-3 farms

### ISSUE THREAD

**Issue by fhwsuper** [Chia-Network/chia-blockchain#3527]
Runtime error: unknown exception or hang when plotting 2-3 farms at the same time

**To Reproduce**

plotting 2 queues:
assign 4500mb, 3processes, k=32 for each plotting

Or plotting 3 queues:
1. assign 3390mb, 3processes, k=32
2. assign 3390mb, 3processes, k=32
3. assign 3390mb, 2processes, k=32

Problems:
No1. view log: "Runtime error: unknown exception" at the bottom
No2. sometimes log hasn't Runtime error, and then I checked taskmgr of windows, the chia.exe process has xx cpu usage%, xx mem usage %, but zero value of hard disk usage. I think it's hang. 

**Expected behavior**
the plotting tasks should be completed successfully. 

**Desktop (please complete the following information):**
- OS: [Win10]
- CPU: [e.g. Intel i7 4790, 4cores/8processes]
- mem: 16GB
- sSD: 1TB

**Additional context**
It's ok when only plotting one farm. After upgrade to 1.1.2 and 1.1.3, it often happen plotting task hang or runtime error in log. 

For my computer, could you suggest me a plotting configuration(how many mem/process for each plotting) when plotting 2 farms at the same time?

**Comment by serunos** [comment]
I have the same issue while plotting 1 plot of 101.4GiB
The log look like : 
Starting plotting progress into temporary dirs: C:\ and C:\
```
ID: 64e12423fdc5038a9b73b4f1b14b6f4d92684421722ecf0ec9c2069f95e8593e
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536
Caught plotting error: Could not open C:\plot-k32-2021-05-04-09-41-64e12423fdc5038a9b73b4f1b14b6f4d92684421722ecf0ec9c2069f95e8593e.plot.sort.tmp: Permission denied.
[18500] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception
```
I have a Desktop :
OS: [Win10]
CPU: [Intel i7 10700K, 4cores/8processes]
mem: 16GB
sSD: 1TB

I'm on the latest version of chia blockchain
