### ISSUE TITLE
Screen is always "Connecting to wallet"[BUG]

### ISSUE THREAD

**Issue by Gomes1990** [Chia-Network/chia-blockchain#3528]

**Comment by drauka2** [comment]
stuck on connecting to wallet
![image](https://user-images.githubusercontent.com/60499967/116899488-97693300-ac05-11eb-8cd1-373d602bf786.png)

**Comment by drauka2** [comment]
> stuck on connecting to wallet
> ![image](https://user-images.githubusercontent.com/60499967/116899488-97693300-ac05-11eb-8cd1-373d602bf786.png)

been on that screen for 6 hours. gave up and reopened still stuck

**Comment by dorkmo** [comment]
likely one of your database files got corrupted last shutdown. will need to delete chia folders and reinstall

**Comment by drauka2** [comment]
Ok I'll try it again
