### ISSUE TITLE
[REQ] Enable Chia executable to write plotter logfiles from CLI

### ISSUE THREAD

**Issue by djdookie** [Chia-Network/chia-blockchain#3530]
A lot of people that use CLI for plotting start using tools for analyzing and controlling the plotting process via plotter logfiles to better balance resources.
As far as I can see, it's up to the user right now to manually capture CLI output consistently, some struggling to do so.

I propose to enable the existing logging mechanisms in the chia executable, using a parameter if necessary, to write a plotter log file to .chia\mainnet\plotter, like the GUI does.
The debug.log is also written by the chia executable while using CLI only, so I don't see a reason why it shouldn't write a plotter log also.
Additionally it would also be great to be able to configure the plotter logfile path.

This feature should have a great value for a lot of CLI users, while the implementation should be straightforward, because the plotter logging logic does exist in general.

**Comment by BigUncle** [comment]
I couldn't agree more!
I am using `create_plots_command >> log_file_name` temporarily.

**Comment by whitetechnologies** [comment]
Yes please, that would be very helpful as most users eventually migrate to CLI on windows

**Comment by algo7** [comment]
+1
