### ISSUE TITLE
Exception from 'wallet' {'error': "'NoneType' object has no attribute 'tx_store'", 'success': False}

### ISSUE THREAD

**Issue by epudwjuhc** [Chia-Network/chia-blockchain#3531]
> chia farm summary gives:

Exception from 'wallet' {'error': "'NoneType' object has no attribute 'tx_store'", 'success': False}
Farming status: Farming
Total chia farmed: Unknown
User transaction fees: Unknown
Block rewards: Unknown
Last height farmed: Unknown

then it will also not show the amount of farmed coins!

**Comment by dmifly** [comment]
I meet the same issue with you. And maybe you can take a look at this issue.

https://github.com/Chia-Network/chia-blockchain/issues/1750

**Comment by xrobau** [comment]
The solution is to run `chia wallet show` and push S to skip restoring.

**Comment by T3th** [comment]
I got the same error.` chia wallet show` didn't give give me a skip restore option it gave `Exception from 'wallet'`

Reset wallet by removing wallet\db in linux docker setup does seem to have brought me back to a working state.

**Comment by bakongi** [comment]
Check config.yam. Search for **plot_directories:** if its empty and no dir paths under it, then add []
It should be **plot_directories: []** if no plots dirs or 
**plot_directories:
 - H:\Plots**
for example

**Comment by luckyluke113** [comment]
> Check config.yam. Search for **plot_directories:** if its empty and no dir paths under it, then add []
> It should be
> `plot_directories: []`
> if no plots dirs or
> 
> ```
> plot_directories:
>  - H:\Plots
> ```
> 
> for example

it works for me :)

**Comment by dskvr** [comment]
Having same issue. keys are added and confirmed with `chia keys show`. `chia wallet show` gives `Exception from 'wallet'`. Cannot find any information on paths, so cannot delete `wallet/db` or identify where `config.yml` is.

**Comment by 0Bu** [comment]
> The solution is to run `chia wallet show` and push S to skip restoring.

Thanks, that worked. But the wallet db had to be deleted before `rm .chia/mainnet/wallet/db/*`.
