### ISSUE TITLE
[BUG] RPI4 1.1.3 Tag, no synk after 10:00 PDT

### ISSUE THREAD

**Issue by kshyshkin** [Chia-Network/chia-blockchain#3547]
1.1.3 Tag
**Describe the bug**
After 10:00 PDT, RPI4 Rasbian OS, have no sync (very slow). In logs i see many errors.

**Screenshots**
![Screenshot from 2021-05-03 20-48-56](https://user-images.githubusercontent.com/44696221/116912657-2d767b00-ac51-11eb-9bb4-a146056ce187.png)

- OS: Rasbian OS

**Comment by jonny77** [comment]
it happend to me also , lost sync at 10PM ....

**Comment by mariano54** [comment]
Performance fix coming soon (1.1.4)
