### ISSUE TITLE
[BUG] "Error loading config" - replace with default?  Find and fix error?

### ISSUE THREAD

**Issue by salamanders** [Chia-Network/chia-blockchain#3548]
**Describe the bug**
When starting the app in Ubuntu via command line, I consistently get "Error loading config - using defaults"
It doesn't seem to hurt anything.  (the GUI still runs, the network still plots and farms)

```
/chia-blockchain/chia-blockchain-gui$ npm run electron &
[1] 4043
(venv) ME@MACHINE:~/Documents/chia-blockchain/chia-blockchain-gui$ 
> electron
> electron .

/home/ME/Documents/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
```

**To Reproduce**
Start app via command line.

**Expected behavior**

* No error OR 
* Instructions on how to fix the error / which file to replace it with.

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu

**Additional context**

**Comment by liya558** [comment]
me too

**Comment by vaheed** [comment]
me too

**Comment by tonybadguy** [comment]
Seems like the core code and GUI code are out of sync in terms of where they expect the config files to be.

chia-blockchain: ```~/.chia/mainnet/config/config.yaml```
chia-blockchain-gui: ```~/.chia/1.1.5/config/config.yaml```

Setting the CHIA_ROOT environment var before running the GUI seems to work for me
```
export CHIA_ROOT=~/.chia/mainnet/
```

Relevant code locations:
* https://github.com/Chia-Network/chia-blockchain/blob/59de4ffe9f98de62d281695d1f519d65ef2e2ece/chia/util/default_root.py#L4

* https://github.com/Chia-Network/chia-blockchain-gui/blob/75c00f307fe21b2f25750c9ed1dcefdf311acf9f/src/util/config.js#L23

**Comment by salamanders** [comment]
That feels like a big bug, no?

**Comment by Leesanel** [comment]
Is this problems solved already?
