### ISSUE TITLE
trascaction says 'MEMPOOL_NOT_INITIALIZED'

### ISSUE THREAD

**Issue by muthubaby** [Chia-Network/chia-blockchain#3550]
can't finish a transcation of "MEMPOOL_NOT_INITIALIZED"
![无标题](https://user-images.githubusercontent.com/83113109/116913417-07b29b80-ac7c-11eb-96f4-aaba7fa43fc7.png)
![无标题1](https://user-images.githubusercontent.com/83113109/116913423-08e3c880-ac7c-11eb-9353-7cab06621d97.png)

**Comment by dorkmo** [comment]
are you on 1.1.3?

**Comment by muthubaby** [comment]
> are you on 1.1.3?

yes

**Comment by jcx123123** [comment]
me too ,on 1.1.3

**Comment by dorkmo** [comment]
https://github.com/Chia-Network/chia-blockchain/blob/17c45bf64e8627b1abb49fa305573d2a04dec806/chia/full_node/mempool_manager.py#L237

looks like its here, someone self.peak = none ... not sure what the means

**Comment by jcx123123** [comment]
> 您是否在1.1.3上？
Help, this is a very important time for transactions, but this bug prevents me from transferring xch

**Comment by Muslix** [comment]
What is the transaction fee if i send something ?!?!?

it just gives me this


![Unbenannt](https://user-images.githubusercontent.com/11888941/116915522-6bbd6b80-ac4c-11eb-966d-0b6cb1b3a2bb.JPG)

**Comment by jcx123123** [comment]
![image](https://user-images.githubusercontent.com/83081596/116915860-2cf4d900-ac7f-11eb-8b5c-1b4b72f17512.png)

**Comment by Muslix** [comment]
ok confirmed but never reached the other address xD  thats sad

**Comment by fenyuchenabc** [comment]
![image](https://user-images.githubusercontent.com/56098703/116946703-cead0380-ac48-11eb-8490-0c6fd0b65b1d.png)
你解决了吗 还是pending吗

**Comment by jcx123123** [comment]
依然还是pending

**Comment by fenyuchenabc** [comment]
其他帖子里也有这个情况 可能是fee=0所以卡在队尾了... 不晓得怎么修复 应该最后会退回的 要等更新了

**Comment by muthubaby** [comment]
@hoffmang9 have been waiting for more than 7 hours for the pending transfer, anything is wrong？

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up
