### ISSUE TITLE
[help] about trascaction fee.

### ISSUE THREAD

**Issue by dazhoudotnet** [Chia-Network/chia-blockchain#3553]
Transferred 0.01 to another wallet. But 1.75 was deducted.

![1](https://user-images.githubusercontent.com/45910169/116916085-6fb6b100-ac7f-11eb-83cc-84d3e11995a0.png)
![2](https://user-images.githubusercontent.com/45910169/116916089-70e7de00-ac7f-11eb-8f36-4c3a49693061.png)

**Comment by Leozolt** [comment]
I have send 1.99 xch with 0.01 fee
Wallet says -2 xch with an additional 1.5 xch "change" thing that I sended to myself.

Unfortunately the transaction is still pending so for 2 xch sended, 3,5 xch are deducted.

**Comment by dorkmo** [comment]
what does the wallet drop down details say about your balances? is anything pending?

**Comment by laochuan** [comment]
呵呵，10000USD/XCH。。。。。nonononono

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up
