### ISSUE TITLE
[BUG]now you have money, please hire some real talents to fix the tons of bug reported

### ISSUE THREAD

**Issue by potato1992** [Chia-Network/chia-blockchain#3554]
AS SHOWN IN THE TITLE

**Comment by epudwjuhc** [comment]
yeah the software is very badly written, unfortunately

**Comment by ivanbey** [comment]
I think is a must.

**Comment by mariano54** [comment]
Yep, we're working on expanding the team and getting all the bugs fixed

**Comment by fullet-tortuga** [comment]
Are Chia's programmers full time paid employees or is this a hobbyist project?
