### ISSUE TITLE
[BUG]Why did transaction stop at pending state for 35 min

### ISSUE THREAD

**Issue by Jimmy01240397** [Chia-Network/chia-blockchain#3556]
![image](https://user-images.githubusercontent.com/57281249/116918218-33d11b00-ac82-11eb-90dd-6e4a72001e67.png)

Can I cancel my transaction and resend it with 0 fees?

**Comment by fenyuchenabc** [comment]
same here.

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Restart computer
4. Make sure you have upgraded to the latest version
5. Start the application and wait for the wallet to sync up

**Comment by victordetarragon** [comment]
Can you provide the location of this wallet / db on Windows ? I didnt find it in App/Local neither in App/Roaming.

Thank you.
