### ISSUE TITLE
[BUG] Transactions stay in pending state

### ISSUE THREAD

**Issue by flotti455** [Chia-Network/chia-blockchain#3557]
**Describe the bug**
I have initiated several transactions since the end of freeze time / transaction start. As of now (1 hour and 41 minutes since transaction start), all my transactions are stuck in pending state:

```
$ chia wallet get_transactions -f  "${WALLET_FINGERPRINT}"
...
Transaction f00bl4
Status: Pending
Amount: X.Y xch
...

```

**Comment by Leozolt** [comment]
Can you find any adress you send the xch to on chiaexplorer.
I also have a pending transaction and can not find the adress or puzzle on chiaexplorer.
My wallet says it has 1 connection, and the full node shows a "Wallet" connection to 127.0.0.1

I suspect the transactions not getting posted to a full node other than localhost node?

**Comment by ricerocketfu** [comment]
is there anything to do with the fee?

**Comment by Leozolt** [comment]
> is there anything to do with the fee?

My transaction was for 1.99 XCH with a 0.01 fee.
There are transactions that go trough with or without fee right now.

I still suspect the wallet connection (127.0.0.1) not posting the transaction to the real network but I do not know what I could do to verify that. I do not know if it is safe to try to connect the wallet to an online node instead to the local one.

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Restart computer
4. Make sure you have upgraded to the latest version
5. Start the application and wait for the wallet to sync up
