### ISSUE TITLE
[help] Chia transaction fee and stuck transactions!

### ISSUE THREAD

**Issue by D4rk4** [Chia-Network/chia-blockchain#3560]
I'm tried to send some coins to OKEx and set Amount 1.95 and Fees = 0.05.

I waited about 40 minutes and transaction still not mined, as I know transactions from other peoples with zero fees already mined. WUT? How I can cancel this transaction and resend it with 0 fees?

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by tonaaguirre** [comment]
Any update? 0 fees then?
