### ISSUE TITLE
Errors on debug file :  Invalid response for slot None + WARNING Looking up qualities 

### ISSUE THREAD

**Issue by casa10** [Chia-Network/chia-blockchain#3562]
Hello,
Someone can explain these differents errors prenset in debug file :

1) full_node chia.full_node.full_node: WARNING Invalid response for slot None

2) harvester chia.harvester.harvester: WARNING  Looking up qualities on folder\plot-k32-2021-04-27-05-04-xxxxxxxxxxxxxxx.plot took: 13.443154335021973. This should be below 5 seconds to minimize risk of losing rewards.
This one means that i can lost ? Because i believed it's 30 seconds to answer to challenge.

Thank you

**Comment by xguya** [comment]
I have the same problem:  xxxx  This should be below 5 seconds to minimize risk of losing rewards.

**Comment by Bluebrain2000** [comment]
me too:

WARNING  Invalid response for slot None
WARNING  Looking up qualities on F:\CHIA Farming\plot-k32-2021-05-02-20-07-11...c6.plot took: 6.929471254348755. This should be below 5 seconds to minimize risk of losing rewards.
WARNING  Looking up qualities on F:\CHIA Farming\plot-k32-2021-05-02-19-17-94...15.plot took: 7.0556557178497314. This should be below 5 seconds to minimize risk of losing rewards.
WARNING  Looking up qualities on F:\CHIA Farming\plot-k32-2021-04-30-17-34-5a...b4.plot took: 9.966350793838501. This should be below 5 seconds to minimize risk of losing rewards.
WARNING  Looking up qualities on F:\CHIA Farming\plot-k32-2021-05-03-04-19-cd...56.plot took: 9.000458478927612. This should be below 5 seconds to minimize risk of losing rewards.
WARNING  Looking up qualities on F:\CHIA Farming\plot-k32-2021-05-02-20-07-11...c6.plot took: 6.7773823738098145. This should be below 5 seconds to minimize risk of losing rewards.

**Comment by C4** [comment]
I'm getting the same. Looking for a way or workaround to solve this. (External HDDs)

**Comment by spammenotinoz** [comment]
Same, checked all the usual, HDD is not going to sleep and its directly attached.
CPU is < 25% but possible a spike occurred, will move to a dedicated Harvester.

**Comment by C4** [comment]
Are you using rsync over sshd? (I am) it's possibly causing the spike in CPU.

**Comment by casa10** [comment]
i use NAS and put plot directly on him.
I suppose that arrives when plots are finished and are transfered to him.
After, sometimes i see this thing on one or 2,4 plots. It's rarely for moment.
I plug NAS directly to my computer and it'smore ralrely now. I think it's network. I need to look more near.
NAS uses SMB.

**Comment by dnavamosler** [comment]
Same problem around here ... working with combine harvesters

**Comment by dorkmo** [comment]
NAS has been found to be able cause more than 30 second delay. If using NAS keep a close eye on delay.

**Comment by Bluebrain2000** [comment]
> NAS has been found to be able cause more than 30 second delay. If using NAS keep a close eye on delay.

I've got the same problem and the plots are on an internal WD Red.

**Comment by dorkmo** [comment]
> > NAS has been found to be able cause more than 30 second delay. If using NAS keep a close eye on delay.
> 
> I've got the same problem and the plots are on an internal WD Red.

ooo thats not good. You might post your full specs.

**Comment by spammenotinoz** [comment]
> > NAS has been found to be able cause more than 30 second delay. If using NAS keep a close eye on delay.
> 
> I've got the same problem and the plots are on an internal WD Red.

2021-05-05T06:00:39.429 harvester chia.harvester.harvester: WARNING  Looking up qualities on K:\Chia\Farm\plot-x.plot took: 15.582046031951904. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-05T06:16:06.391 harvester chia.harvester.harvester: WARNING  Looking up qualities on K:\Chia\Farm\plot-x.plot took: 16.665660858154297. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-05T07:40:22.869 harvester chia.harvester.harvester: WARNING  Looking up qualities on K:\Chia\Farm\plot-x.plot took: 72.95221161842346. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-05T07:47:11.223 harvester chia.harvester.harvester: WARNING  Looking up qualities on K:\Chia\Farm\plot-x.plot took:  97.52372026443481. This should be below 5 seconds to minimize risk of losing rewards.

Windows 10 Pro [Version 10.0.19041.928] 32gb RAM
i7-6700
K: Drive is a USB attached WD Ext HDD 1021 (1tb) with 9 plots to USB 3.0 port.
Disk Spin Down \ Power Down set to Never
Has an older Intel Sata Enterprise SSD for plotting.

I plot and farm on the same machine (CPU is relatively low).

Next steps will be to try a dedicated farm machine.
What should I pick, intention is to have 4 x 16GB external USB drives.

- old Intel NUC 3rd Gen i3, but it's only USB 2.0
- my gaming PC, refurbed SFF Dell OptiPlex 9020 (okay it's very low spec, older i7 and 16gb), but it has 4 SS USB 3 ports, was going to use this for plotting has an older Intel Enterprise SSD.
- Purchase a dedicated machine for harvesting, perhaps Raspberry Pi 4?

**Comment by Bluebrain2000** [comment]
> > > NAS has been found to be able cause more than 30 second delay. If using NAS keep a close eye on delay.
> > 
> > 
> > I've got the same problem and the plots are on an internal WD Red.
> 
> ooo thats not good. You might post your full specs.

It's a pretty high end desktop machine. Core i7 8700K 6C/12T, 64GB RAM, 2 NVMW drives, WD Red Raid.

**Comment by Bluebrain2000** [comment]
@spammenotinoz 
> 2021-05-05T07:40:22.869 harvester chia.harvester.harvester: WARNING Looking up qualities on K:\Chia\Farm\plot-x.plot took: 72.95221161842346. This should be below 5 seconds to minimize risk of losing rewards.
> 2021-05-05T07:47:11.223 harvester chia.harvester.harvester: WARNING Looking up qualities on K:\Chia\Farm\plot-x.plot took: 97.52372026443481. This should be below 5 seconds to minimize risk of losing rewards.

Over A MINUTE? 😮 
There really must be someting wrong!

**Comment by SKYBILLS** [comment]
Me also got this warning but its 5.++ seconds , dont know could admin fixed this or not

**Comment by 1995es** [comment]
Same problem here with a RPi 4

**Comment by Zeggi** [comment]
Same issue over here.
5950x normally running 14 plots in parallel but also tried single plot, same issue, constantly seeing this error and on top of that even seeing error "plot has a farmer public key that is not in the farmer's pk list."
Setup linux, 2x2tb nvme firecuda in raid0 for plotting, pool storage WD HC550 18TB drives in raid6.
64mb ECC ram.
0 swap.
scratching my head trying to figure out what is the issue only thing i haven't tried is a clean install of the chia-blockchain, mentioning this because I've done a total of 3 upgrades and also just recently switched over to using command line plotting hence why i found the issue, doesn't show anywhere in GUI

**Comment by danktankk** [comment]
same issue here...  running in an array on unraid.  I am going to try and run it off internal drivers on a dedicated node

**Comment by danktankk** [comment]
This is still an issue and we really need someone to explain how to correct this!  I cant get much more local than a PC with brand new 14TB drives attached directly to the motherboard!

**Comment by danktankk** [comment]
2021-05-07T15:58:20.659 harvester chia.harvester.harvester: WARNING  Looking up qualities on D:\plots\plot-k32-2021-04-28-04-<truncated>.plot took: 6.4244513511657715. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-07T16:01:17.099 harvester chia.harvester.harvester: WARNING  Looking up qualities on D:\plots\plot-k32-2021-04-26-01-<truncated>.plot took: 9.005711078643799. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-07T16:06:14.870 harvester chia.harvester.harvester: WARNING  Looking up qualities on D:\plots\plot-k32-2021-05-02-18-<truncated>.plot took: 5.844118356704712. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-07T16:07:30.943 harvester chia.harvester.harvester: WARNING  Looking up qualities on D:\plots\plot-k32-2021-05-01-11-<truncated>.plot took: 6.391903638839722. This should be below 5 seconds to minimize risk of losing rewards.
2021-05-07T16:18:28.590 harvester chia.harvester.harvester: WARNING  Looking up qualities on D:\plots\plot-k32-2021-05-06-16-<truncated>.plot took: 7.734356880187988. This should be below 5 seconds to minimize risk of losing rewards.

**Comment by SilentGloves** [comment]
I'll also throw my hat into this ring.  Ubuntu 20.04 LTS.  Warnings seem to range from 6 to 43 seconds.  Not great!  All drives are shucked WD white label SATA HDDs.

I've run the following in order to prevent hibernate and sleep, but I do not expect this to help a lot:
`sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target`

**Comment by SilentGloves** [comment]
Actually, I have a working theory that for me, this error only occurs during the plotting write to said drive.  This is because I have plots on several drives, but only the drive being actively plotted to appears to be throwing this warning.  I'm going to watch the log, plotting status, drive space, etc. during the next write and determine if these errors show up then.  If this turns out to be the case, then the condition is expected, and shouldn't be a cause for concern.  I will report my findings here.

**Comment by spammenotinoz** [comment]
> **Possible Explanation**
> 
> So I watched the debug.log and plotter status over the course of two write cycles (writing the plot itself to storage). During this time, I only saw the `Looking up qualities on WARNING` thrown during the write cycles, with no instances of the error in between write cycles. My theory is that NVME to SATA read/write bandwidth is sufficient to saturate spinning disk drives such that reads against that drive are substantially delayed during the write.
> 
> I see no instances of this warning for drives that are not being actively written to by the plotter. Though a relatively small sample size, this for me adequately explains this warning message. The possible consequence of losing rewards only appears to happen in the small window of a write, so I see no need to take further action. I would suggest investigating this for yourself on your machine.

I posted the same thought (5th post), but turned out the issue was still occurring, just reduced instances.   Definitely associated with resource contention though, as it doesn't happen on a high-spec harvester that isn't plotting,

**Comment by Muffexx** [comment]
I also have
`full_node chia.full_node.full_node: WARNING Invalid response for slot None`
but mostly without the
`harvester chia.harvester.harvester: WARNING Looking up qualities...`

**Comment by 527593036** [comment]
me too:
2021-05-12T04:19:04.264 harvester chia.harvester.harvester: WARNING  Looking up qualities on /data2/chialabsplots/xxxx.plot took: 5.80071496963501. This should be below 5 seconds to minimize risk of losing rewards.

I use s3(aws), oss(aliyun) for storage plots.
Does the plots need to be append write on farming time? When using cloud vendors' s3(aws), oss(aliyun), etc., append write is not supported, does it affect revenue? 

please help me

**Comment by jedocampo** [comment]
where you guys able to find some fix on this? im using external HDD aswell 3.0 plugged in directly to mobo... my HDD are set to "0" so they dont go to sleep mode.

**Comment by Muffexx** [comment]
Hey @jedocampo,
what does 'HDDs are set to "0"' mean exactly? 
regards
muffexx

**Comment by jedocampo** [comment]
> Hey @jedocampo,
> what does 'HDDs are set to "0"' mean exactly?
> regards
> muffexx

go to your power plan settings and set the HDD timer to "0" so they dont sleep when they aren't being used. (they will keep on spinning even on idle"

**Comment by Muffexx** [comment]
Oh, okay.
I'm farming on Linux. 
Thanks, anyway.

**Comment by inigosola** [comment]
I'm getting the same.

**Comment by frogotoro** [comment]
I'm having the same problem too. My question is, will the log show if it's under 5? 
If so, how do we enable the log to show "Not just the warning"?

**Comment by ebeng** [comment]
I do have the same warning. Pushover notifications are getting me a bit crazy. 
I do get these messages when the NAS is receiving data from one of the Harvesters. 
However, the daily notification is showing a search less than 20mili-seconds.. which is perfect for me. 
Is it still something to worry about or what??

**Comment by digitalillusion** [comment]
I resolved the slow "Looking up qualities issue" with an external hdd going to sleep. I created a cron job that keeps it awake

*/5 * * * * /bin/touch /{path_to_the_hdd}/poke

**Comment by Fort1991** [comment]
> **Possible Explanation**
> 
> So I watched the debug.log and plotter status over the course of two write cycles (writing the plot itself to storage). During this time, I only saw the `Looking up qualities on WARNING` thrown during the write cycles, with no instances of the error in between write cycles. My theory is that NVME to SATA read/write bandwidth is sufficient to saturate spinning disk drives such that reads against that drive are substantially delayed during the write.
> 
> I see no instances of this warning for drives that are not being actively written to by the plotter. Though a relatively small sample size, this for me adequately explains this warning message. The possible consequence of losing rewards only appears to happen in the small window of a write, so I see no need to take further action. I would suggest investigating this for yourself on your machine.

U right for 100%. I was looking for a reason for about a week. 
When I read your post I decided to chek it. And now I can confirm ur theory. So tnh.

**Comment by lrlbh** [comment]
我使用的USB连接硬盘。我也有这个问题，为此我换过很多台电脑，包括运行p图的5800和i7-8750h电脑，没有任务的3020e，树莓派4B，i5-6xxxU。同时也使用过linux系统和windows系统。这个问题一直都在出现，我还没有找到具体的原因。

1、目前可以确定的是原装的外置硬盘和移动硬盘不会出现该问题。
2、出现该问题的都是使用了易驱线和硬盘盒子的硬盘。
3、我使用的硬盘基本都是4T的西数紫盘和4T希捷酷鹰，我不确定是硬盘有问题还是硬盘盒和易驱线有问题。
4、个别盒子和易驱线会频繁的发生问题。
