### ISSUE TITLE
[BUG] ERROR NO CARGA

### ISSUE THREAD

**Issue by cristiancalle** [Chia-Network/chia-blockchain#3567]
ya tengo este problema de hace 2 días que quedó asi y no logra sincronizar, tengo la versión 1.1.3, la tengo encendida todo el tiempo, ya desinstale eh instale de nuevo reinicie e hice de todo nunca sincroniza
![image](https://user-images.githubusercontent.com/83609059/116923345-84199000-ac24-11eb-9001-2d951771e690.png)

**Comment by Chiaderck** [comment]
Has logrado solventar? Que has hecho?

**Comment by cristiancalle** [comment]
si, logre resolverlo hice de todo reinstalando apagando la pc, pero la
solución cómo lo resolví fue borrando todo dato sobre chia y todo registro
de caché sobre chia, y al final limpiando con ccleaner, luego volví a
instalarla y funcionó, pero tuvo que volver a sincronizar desde 0 tardo 2
días, ayer descargue la última versión y la instale y de nuevo me sale
cargando, mi router no tiene para abrir ese puerto 8444 de chia, y no se
como resolverlo otra vez, ya que para instalarlo de nuevo volverá a cargar
desde 0 otros 2 días y con futuras actualizaciones me volvera hacerlo

[image: image.png]

**Comment by Jhonny3126** [comment]
Normalmente es error de sincronizacion se debe a que no esta configurada la hora del computador....!  Verifiquen que la hora de su ordenador corresponda a su zona horaria y no utilizen VPN
