### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Light2808** [Chia-Network/chia-blockchain#3568]
- OS: windows 10
- CPU: Ryzen 3600
- Chia Blockchain 1.1.3

**Additional context**
1,75 XCH Confirmed at height 185560
0,25 XCH Confirmed at height 185560
04/26/2021 00:29:53

1,75XCH still not confirmed and i can't transfer this balance

![1](https://user-images.githubusercontent.com/83609284/116923278-222a4c00-ac5f-11eb-9f07-36ac330c6961.PNG)
![2](https://user-images.githubusercontent.com/83609284/116923280-235b7900-ac5f-11eb-9d23-88fdf9413885.PNG)
![3](https://user-images.githubusercontent.com/83609284/116923397-42f2a180-ac5f-11eb-9c6e-8abfe92d3f61.PNG)

**Comment by Light2808** [comment]
problem solved

**Comment by Somnusochi** [comment]
How to solve this problem？

**Comment by Light2808** [comment]
> How to resolve this problem？
after the issue was created, the amount became available. if someone helped me - thanks to him!
