### ISSUE TITLE
[BUG] Synchronization Bounce

### ISSUE THREAD

**Issue by YZTao1** [Chia-Network/chia-blockchain#3569]
**Describe the bug**
When sync the node, the synchronization is bouncing. Eg: 1 mins ago, it was syncing 100000 and now it is syncing 90000. Is this normal behavior？
当同步的时候，同步的高度不是线性递增的， 而是一会儿同步100000 然后再跳转回90000 请问这个正常吗？

**Screenshots**
![image](https://user-images.githubusercontent.com/83611154/116924937-cf4d9600-ac58-11eb-948d-fd5983071fbe.png)
**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Windows 10
- CPU: AMD Ryezen 7 5800x

**Additional context**

**Comment by mariano54** [comment]
Check out the wiki on how to port forward and get more connections: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections.
Also there is a recent bug which will be fixed in the next version (1.1.4), related to peer connections.
