### ISSUE TITLE
[BUG] Can't send more than 0 in a single transaction

### ISSUE THREAD

**Issue by Somnusochi** [Chia-Network/chia-blockchain#3571]
**Describe the bug**
Can't send more than 0 in a single transaction.
 How can i resolve this problem？Transactions stay in pending state.
Can I cancel my transaction and resend it with 0 fees?

**Screenshots**
<img width="887" alt="微信图片_20210504034914" src="https://user-images.githubusercontent.com/14160184/116925467-cc1fcd80-ac8b-11eb-9d72-56e9cdaa7de8.png">

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Windows 10
- CPU:AMD Ryzen 7 5900x

**Comment by TrendyPerson** [comment]
Same prob! (May 5th 2021)

- OS: Win10
- Chia Blockchain: v1.1.3
- status: synced
