### ISSUE TITLE
[BUG] Transaction still pending after 3 hours

### ISSUE THREAD

**Issue by ChemEngo** [Chia-Network/chia-blockchain#3575]
![image](https://user-images.githubusercontent.com/26014489/116927808-0ec5b380-ac54-11eb-836d-5b319732440b.png)

Still pending after roughly 3 hours. (time zone London)

- OS: [Windows10]

- CPU: [3950x]

**Additional context**

**Comment by dorkmo** [comment]
hard to know the state of the mempool at this point, but if you choose 0 Fee, you are for sure putting yourself at the back of the line.

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by Drummersmitty** [comment]
@mariano54 Hello Mariano I have a transaction pending now that I can't solve.  I can't find the file .chia/mainnet/wallet/db to delete and reset. How can I fix this? I really don't want to loose my 2 chia!
