### ISSUE TITLE
I sent my 02 XCH to MXC with no fee, and it's disppear.

### ISSUE THREAD

**Issue by DIlbert25** [Chia-Network/chia-blockchain#3576]
I sent my 02 XCH to MXC with no fee, and it's disppear.

More than 60 minutes and notyhing happenned.

Didn´t come back, neitherm appear in MXC.

On Chia, in History, say 
"no previous transations".

Where my 02 XCH ?

* Windows 10

**Comment by fenyuchenabc** [comment]
same.

**Comment by ChemEngo** [comment]
You can check your farmer reward address on the chia explorer to see if any transaction happened.

**Comment by DIlbert25** [comment]
> You can check your farmer reward address on the chia explorer to see if any transaction happened.

I check , and appear "Unspent"

**Comment by DIlbert25** [comment]
How I put my chia cois back on wallet?

**Comment by fenyuchenabc** [comment]
Mine is the same as yours, the explorer says 'unspent' but the wallet shows pending still.

**Comment by DIlbert25** [comment]
> Mine is the same as yours, the explorer says 'unspent' but the wallet shows pending still.

We need to know how to rebuild rhe wallet. What we need???

**Comment by 1971192997** [comment]
finish yet?

**Comment by 1971192997** [comment]
> I sent my 02 XCH to MXC with no fee, and it's disppear.
> 
> More than 60 minutes and notyhing happenned.
> 
> Didn´t come back, neitherm appear in MXC.
> 
> On Chia, in History, say
> "no previous transations".
> 
> Where my 02 XCH ?
> 
> * Windows 10
@DIlbert25 and  this tx finished?

**Comment by DIlbert25** [comment]
Nothing change.

But seems that the wallet don´t stop sync...

**Comment by wjblanke** [comment]
Try this

Stop chia
delete ~/.chia/mainnet/wallet
reboot
update to Chia 1.1.3

Let the wallet sync from 0 to the top of the chain

**Comment by DIlbert25** [comment]
> Try this
> 
> Stop chia
> delete ~/.chia/mainnet/wallet
> reboot
> update to Chia 1.1.3
> 
> Let the wallet sync from 0 to the top of the chain

I had did that.

I upgrade do 1.1.3 many hours aftrer the problem.

**Comment by DIlbert25** [comment]
I think all hpennde after upgrade to 1.1.3

**Comment by DIlbert25** [comment]
Anybody knows if I can downgrade to anterior version?
