### ISSUE TITLE
[BUG] Repeat transaction leads to negative balance

### ISSUE THREAD

**Issue by ChemEngo** [Chia-Network/chia-blockchain#3578]
![image](https://user-images.githubusercontent.com/26014489/116931756-53078280-ac59-11eb-961f-2bffb6add0fa.png)

![image](https://user-images.githubusercontent.com/26014489/116931727-4b47de00-ac59-11eb-951a-ce1efcb39225.png)

**Additional context**
The transaction is still pending after 3 hours

**Comment by dorkmo** [comment]
one of them might have been rejected as a double spend? hard to say

**Comment by mariano54** [comment]
What version are you on? There was an issue before version 1.1.3

**Comment by mariano54** [comment]
If it does not fix itself, Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by daowudi123** [comment]
这是一个共性问题。已经按照建议进行，但是还没有同步完成。

**Comment by qq812291236** [comment]
同步完成后，xch没了。
