### ISSUE TITLE
[BUG] Sent 2 XCH with 0 FEES and on chiaexplorer it shows my total net coins are lowered by 3.5

### ISSUE THREAD

**Issue by tokodev** [Chia-Network/chia-blockchain#3580]
GUI Wallet balance was bugged and is still bugged (Showed 8 instead of 10 and now shows 6 instead of 8)

I'm using windows GUI 1.1.3 and it always showed 2 less coins of the total farmed, but chiaexplorer was OK. Now after my first transaction, my net coins went from 10 to 6.5, and in my GUI went from 8 to 6.

![image](https://user-images.githubusercontent.com/55535804/116932973-3bcd9280-ac63-11eb-939d-c35c5e579192.png)
![image](https://user-images.githubusercontent.com/55535804/116933039-4c7e0880-ac63-11eb-9081-cd0107b56173.png)
![image](https://user-images.githubusercontent.com/55535804/116933124-67507d00-ac63-11eb-88da-2e82cdc893cf.png)

**Comment by fenyuchenabc** [comment]
Same here! I sent 2 xch to Okex and the explorer show that I spent two '1.75 xch'

**Comment by tokodev** [comment]
Same, 2 blocks of 1.75 xch spent on that transaction

**Comment by dorkmo** [comment]
does okex show they recieved 2 or 3.5?

**Comment by 1971192997** [comment]
@tokodev any update?

**Comment by mariano54** [comment]
You are spending two 1.75 coins for a total of 3.5, but there is a "change" transaction which goes back to your wwallet, on a new address. Check that your wallet has the correct balance. 



Also, there is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by tokodev** [comment]
Thanks @mariano54, as soon as my plots end I will try to resync my wallet and see if it shows 8 XCH instead of 6 XCH.

@dorkmo the 2 XCH were correctly received in OKEX in about 15-20 minutes.

**Comment by kennylbj** [comment]
@tokodev How many fees did you spent for sending 2 XCH?

**Comment by tokodev** [comment]
> @tokodev How many fees did you spent for sending 2 XCH?

0 fees

**Comment by kennylbj** [comment]
> > @tokodev How many fees did you spent for sending 2 XCH?
> 
> 0 fees

Great, and how long did you wait for this transaction to complete?
