### ISSUE TITLE
Why am I still wallet zero XCH [help]

### ISSUE THREAD

**Issue by hmz06967** [Chia-Network/chia-blockchain#3581]
Hi there, 
I've been farming for a few days. What is the min chia reward I will see in my wallet? still 0 for example 0.05 XCH vs

**Comment by yannickpschroeder** [comment]
It work like a diet. You don't eat much for a day and the next day you expect to be thinner. But its a process my friend and takes some time ;)

**Comment by hmz06967** [comment]
Well,
But I'm just saying, is there a minimum limit? 
Like Min 1 chia coin

**Comment by henricavalcante** [comment]
Since you are not farming in a pool, you will bet for a whole prize, 2 XCH, each 10 seconds people are winning, so you have to wait your lucky time.

They said that pool protocol is one of the priorities now, so it will b better in a few days when we have official pools to farm together.

**Comment by Muffexx** [comment]
Hello @hmz06967,

when you win, you will always win 2 coins. The higher the total size of your plots, the higher is your chance to win. The estimated time to win is visible in your farming overview. But keep in mind that this estimate depends heavily on the network growth (the greater the network the lower your chance to win). 

regards
muffex

**Comment by hmz06967** [comment]
Thank you for answer guys good farmingg

**Comment by 1971192997** [comment]
hi,  what is the decimal for xch?     8 or 12?
