### ISSUE TITLE
[help]unable to sync

### ISSUE THREAD

**Issue by Johan79s** [Chia-Network/chia-blockchain#3585]
**Describe the issue**
For about 7h now my node has not been able to sync, internet is working without any problems and i had been plotting and farming for about a week, i am on the latest version and i have tried restarting the program and computer but nothing changes, its just not synced for roughly 7h now and force reload wont do anything either.

**To Reproduce**
I have no idea why it stopped working or what changed other than wallet going live.

**Expected behavior**
PC was plotting and farming when i checked it earlier, then later on it suddenly had stopped working and i been unable to resolve the issue

Regards,
Johan

**Comment by bleusakura** [comment]
Seems to be a widescale network thing, I am getting the same thing and so are many people. Upgrading and Restarting does not fix it. Currently on Debian 10

**Comment by mariano54** [comment]
Check out the wiki on how to port forward and get more connections: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections.
Also there is a recent bug which will be fixed in the next version (1.1.4), related to peer connections.

**Comment by horizon6969** [comment]
I Am using raspberry pi 4 with 4G ram as farmer. It stopped syncing at :
Current Blockchain Status: Not Synced. Peak height: 225697

when i do this: 
chia show -s -c
Current Blockchain Status: Full Node syncing to block 228803
   Time: Mon May 03 2021 19:01:21 CEST                  Height:     225697


I am seeing nodes - not suspecting issues with ports, etc. 

It was working fine for last 7 days with no issues. 

I did push update , using git process, and currently running 1.1.3. all went fine.
 Can you help. ?
