### ISSUE TITLE
PLOTS in GROUPS

### ISSUE THREAD

**Issue by realbluefish** [Chia-Network/chia-blockchain#3587]
I know this may not be an error but currently it is not possible to do the following:
After doing many tests and finding the optimal configuration, I decided to launch groups of 4 plots in parallel with a delay between them. If I want to schedule an equal group for when the first one ends, this is not possible.
If I try to launch a second group of 4 plots that starts after the first with the same configuration, it is NOT possible because if I launch 4 plots on standby, it will take them out individually and if I take them in parallel they start simultaneously. I think they should implement the possibility to do this. For this they should assume that groups are always launched (even if it is 1) and keeping the option of parallel or at the end of the queue would allow doing what I say.

**Comment by Muffexx** [comment]
Hello @realbluefish,

this question has been answered multiple times (e.g. [#2833](https://github.com/Chia-Network/chia-blockchain/issues/2833).
You can setup different queues. This way you can create different 'pipelines' that allow for _parallel_ plotting.

E.g.:

- Add 5 Plots to Queue1 and use "Add Plot to Queue"
- Add 5 Plots to Queue2 and use "Add Plot to Queue"
--> This way there will always be 2 plots in the making. (Add more queues as necessary.)

A queues name can be set in Advanced Options of (2) "Choose Number of Plots".

regards
muffexx
