### ISSUE TITLE
[BUG] Wallet not conect.

### ISSUE THREAD

**Issue by dailtonfarmer** [Chia-Network/chia-blockchain#3589]
I can´t connect in the wallet in 3 hours ago.

Windows 10
i5 8400 
24gb
M.2 512gb

**Comment by Leozolt** [comment]
Omgosh I am so drunk I see the problem with Windows 10. Probably some firewall shinanigans. Backup your files. Install Ubuntu and Chia 1.1.3.

If that doesn't help I can't help you :)

**Comment by Leozolt** [comment]
@dailtonfarmer 
Help resolving issues by giving more information like a screenshot, maybe log file snippets.
