### ISSUE TITLE
Coins simply disappear

### ISSUE THREAD

**Issue by DIlbert25** [Chia-Network/chia-blockchain#3590]
![image](https://user-images.githubusercontent.com/83551408/116942875-d371b780-ac48-11eb-803b-29a15d8cd3d8.png)

![image](https://user-images.githubusercontent.com/83551408/116942956-f7cd9400-ac48-11eb-8da4-b79b3307581c.png)

![image](https://user-images.githubusercontent.com/83551408/116943105-44b16a80-ac49-11eb-900d-dfeea2389834.png)

I try to sell may two Chia coins;

System send rhat msg ( up image  );

And my cois simply disappear !!!

No histrory of transation.

Nothing ar MXC.

Chia coin explorer shows no transations for my two coins....

Does The Matrix  have a flaw?

- OS: Windows
- OS 10
- CPU: [Intel Xeon 2620v3]

**Additional context**

**Comment by Leozolt** [comment]
If you are on height 19009 and farmed your 2 xch later it is normal that your balance is 0.

Did you try adding node.chia.net 8444 to the connections?

**Comment by DIlbert25** [comment]
But the system seem to sync:

![image](https://user-images.githubusercontent.com/83551408/116944095-2fd5d680-ac4b-11eb-841d-1fcc8dd6b762.png)

**Comment by DIlbert25** [comment]
Here its stay "syncing"

![image](https://user-images.githubusercontent.com/83551408/116944156-4c720e80-ac4b-11eb-832f-c4794b023e12.png)

**Comment by Leozolt** [comment]
It doesn't really help to post cropped images that hide peak Height or pending balances etc. You already posted a picture with your balance and a transaction to xch1yc....pyfze which might be enough to see your real balance.
Can you post a picture of your node connections under full node?

**Comment by dorkmo** [comment]
your wallet sync is different from your wallet sync sometimes

**Comment by mariano54** [comment]
Yes you need to wait for your wallet to sync

**Comment by DIlbert25** [comment]
> If you are on height 19009 and farmed your 2 xch later it is normal that your balance is 0.
> 
> Did you try adding node.chia.net 8444 to the connections?

I do that.

I open 8444 port.

All problemsn happened after I update to 1.1.3.

Seems wallet, and now, full node, don´t sync.

**Comment by DIlbert25** [comment]
Very slow sync. Almost freeze.

![image](https://user-images.githubusercontent.com/83551408/116996177-6d6d4a80-acb1-11eb-86a1-468d3e034012.png)

![image](https://user-images.githubusercontent.com/83551408/116996238-7f4eed80-acb1-11eb-87d9-824e32caba30.png)

**Comment by DIlbert25** [comment]
Wallet and node so slowly to sync.

One week to sync?

I open ports

![image](https://user-images.githubusercontent.com/83551408/116996829-65fa7100-acb2-11eb-9b9a-3ede3dd18499.png)

I include node.chia.net 8444 to the connections, and others.

Nothing works.

**Comment by dorkmo** [comment]
you might trash that node youre getting huge download from

**Comment by Leozolt** [comment]
Not sure if the open 8444 port really should be required but instead of FTP use TCP and UDP
