### ISSUE TITLE
[BUG]Connecting to wallet

### ISSUE THREAD

**Issue by AdyDubz** [Chia-Network/chia-blockchain#3603]
So i have 3 Pcs and i run same wallet in all of them, but in 1 its says connecting to wallet and after 6 hours still not available to connect, reinstalled chia, restarted computer and nothing...
![bug](https://user-images.githubusercontent.com/64424141/116951984-c5905680-ac89-11eb-8cfa-93e70fe2e502.PNG)

**Comment by G4LLITO** [comment]
Hola pudiste solucionarlo? me pasa lo mismo, tengo 2 pc y de una no me deja, capas sacaron eso de tener 2 cuentas a la vez, la actualización trajo problemas por lo visto

**Comment by mariano54** [comment]
Try updating to latest version and restarting PC

**Comment by dreggroll** [comment]
Have the same issue on 1 of my 2 computers. Already have the latest version. The program just gets stuck in that screen. No amount of uninstalling or restarting did anything. I imagine its tied to the IP address working with the chia server to create a wallet code bugging

**Comment by dreggroll** [comment]
Uninstalled chia, found a hidden path, (/Users/…name…/.chia), deleted. (SOLVED)
