### ISSUE TITLE
[BUG] **Rate Limiting / Retries / Or Both impair stability of nodes*

### ISSUE THREAD

**Issue by tedshroyer** [Chia-Network/chia-blockchain#3605]
**Rate Limiting / Retries / Or Both impair stability of nodes*

Rate limiting is causing my home node to drop off the network repeatedly such that I have not been able to farm a block since upgrading on April 24, 2021.  (~75TiB)

Full node I run in AWS also has stability issues and drops off until I manually updated rate limits as show in PR3474.

**To Reproduce**

1. Install version 1.1.3
2. Turn on DEBUG level logging
2. chia start node
3. expose 8444 to internet
4. tail debug.log for Rate limiting messages

**Expected behavior**
Rate limiting should be abnormal or rare

**Screenshots**

**Desktop (please complete the following information):**

- OS:  Linux
- OS Version/Flavor:  AWS Linux 2 and Pop OS
- CPU: aarch64 and amd x64

**Additional context**
Related PRs
https://github.com/Chia-Network/chia-blockchain/pull/3474
https://github.com/Chia-Network/chia-blockchain/pull/3508
https://github.com/Chia-Network/chia-blockchain/pull/3518

**Comment by tedshroyer** [comment]
@hoffmang9 / @arvidn / @mariano54 
Seeing issuing with request_signage_point_or_end_of_sub_slot and not just respond_peer now.

This is quite annoying as I can't keep my home node online and sync since 1.1.1.  Should I roll back and run that version?

**Comment by arvidn** [comment]
are you seeing outgoing signage point request be rate limited?
There was a bug in the rate limiter affecting outgoing packets that were fixed in 1.1.4. You might want to check if that solved it.

**Comment by tedshroyer** [comment]
@arvidn Launching new AWS nodes to test.  Overall, I would say behavior has improved for my home node.  Still some symptoms.
`(venv) ts@pop-os:~/Development/chia-blockchain$ chia version
1.1.4
(venv) ts@pop-os:~/Development/chia-blockchain$ git diff
diff --git a/chia/server/ws_connection.py b/chia/server/ws_connection.py
index 19af8ba2..db89c652 100644
--- a/chia/server/ws_connection.py
+++ b/chia/server/ws_connection.py
@@ -349,7 +349,7 @@ class WSChiaConnection:
         assert len(encoded) < (2 ** (LENGTH_BYTES * 8))
         if not self.outbound_rate_limiter.process_msg_and_check(message):
             if not is_localhost(self.peer_host):
-                self.log.debug(
+                self.log.warning(
                     f"Rate limiting ourselves. message type: {ProtocolMessageTypes(message.type).name}, "
                     f"peer: {self.peer_host}"
                 )
(venv) ts@pop-os:~/Development/chia-blockchain$ grep 'Rate' ~/.chia/mainnet/log/debug.log*
/home/ts/.chia/mainnet/log/debug.log.2:2021-05-05T13:35:59.067 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 1 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:36.134 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:37.136 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:38.137 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:39.139 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:40.140 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:41.142 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:42.143 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:43.145 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:44.146 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:45.151 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:46.153 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:47.155 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:48.156 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:49.157 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:50.159 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:51.160 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:52.162 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:53.163 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:54.166 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:55.167 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:56.168 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:57.168 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:58.170 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T03:19:59.171 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_block, peer: {{ peer 2 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:01:06.703 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 3 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:01:06.703 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 4 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:01:07.141 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 3 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:20:51.513 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 3 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:20:51.513 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 3 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:20:51.513 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 4 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:20:51.514 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 4 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:23:13.235 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 3 }}
/home/ts/.chia/mainnet/log/debug.log.5:2021-05-05T04:23:13.236 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: {{ peer 4 }}`

**Comment by tedshroyer** [comment]
Symptoms / Rate limiting may be related to old software on peers.  Is there a convenient way to add the peer software version?

**Comment by tedshroyer** [comment]
@arvidn AWS node showing almost no errors.  

2021-05-06T01:22:45.333 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: { peer 1 }
2021-05-06T01:25:31.670 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: { peer 1 }
2021-05-06T01:25:31.671 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: { peer 1 }
2021-05-06T03:11:59.643 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: { peer 2 }
2021-05-06T03:11:59.643 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: { peer 1 }
2021-05-06T03:11:59.656 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: { peer 2 }
2021-05-06T03:11:59.656 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: respond_peers, peer: { peer 1 }`

**Comment by tedshroyer** [comment]
@arvidn logs still contain very few "Rate limiting" lines.  FULL_NODE staying connected hovering lower than before (13 now instead of 51)

Also seeing lots of DOUBLE_SPEND warnings now which I haven't seen before

**Comment by tedshroyer** [comment]
@arvidn closing.  all my nodes are staying connected now and not dropping off like before.
