### ISSUE TITLE
同步！！！！同步！！！！同步！！！！！！

### ISSUE THREAD

**Issue by Autumnfruit-qq** [Chia-Network/chia-blockchain#3608]
我已经5天没有同步了！！！！！

**Comment by 1971192997** [comment]
升级节点吧

**Comment by 1971192997** [comment]
大佬 有没有xch社群    技术问题  

xch主网精度多少        （最多几位小数点转账）

**Comment by Leozolt** [comment]
add connection to node.chia.net 8444

**Comment by mariano54** [comment]
Check out the wiki on how to port forward and get more connections: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections.
Also there is a recent bug which will be fixed in the next version (1.1.4), related to peer connections.
