### ISSUE TITLE
[help]On the issue of trading

### ISSUE THREAD

**Issue by dashu578** [Chia-Network/chia-blockchain#3609]
Setting 0 in the expense can get to the account quickly. But setting 0.01 or 0.001 in the expense will not get to the account for a long time

**Comment by dashu578** [comment]
![qqq](https://user-images.githubusercontent.com/82652593/116957198-d95bad00-acc9-11eb-8b9a-c8ecbf2f5126.png)

**Comment by Leozolt** [comment]
You want to say that making a transaction with a fee 0.001 0.01 takes forever but a transaction with 0 fee is fast? I can just say that when my transactions finally got mined, the one with no fee was 8 blocks faster than the one I made one hour before with 0.01 transaction fee.
weird

**Comment by dashu578** [comment]
How long does it take for me to set 0.01 to confirm.. I didn't know the cost was 0

**Comment by dashu578** [comment]
It's almost 12 hours since the transaction was sent

**Comment by dashu578** [comment]
> 
> 
> You want to say that making a transaction with a fee 0.001 0.01 takes forever but a transaction with 0 fee is fast? I can just say that when my transactions finally got mined, the one with no fee was 8 blocks faster than the one I made one hour before with 0.01 transaction fee.
> weird

Hello

**Comment by Leozolt** [comment]
> > You want to say that making a transaction with a fee 0.001 0.01 takes forever but a transaction with 0 fee is fast? I can just say that when my transactions finally got mined, the one with no fee was 8 blocks faster than the one I made one hour before with 0.01 transaction fee.
> > weird
> 
> Hello

Seriously I do not know what is wrong. My initial transaction didn't get mined for 2-3 hours. then I made another transaction but that time with no fee. After that I got to my command center and opened port 8444 to my mining rig that also hast my wallet for now and the transactions got mined after a while. If it was the second transaction that helped, or the exposure of port 8444 to the internet.. I do not know. But i KNOW that exposure of a specific port to the internet should not be required to submit a transaction to the network.

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by Leozolt** [comment]
If you want to try a transaction I can provide a receiving adress! jk

Strange that the wallet syncing is different from node syncing. "This will require syncing up your wallet, but not your node."

**Comment by Leozolt** [comment]
I think it could be easier get the seed, to rename the chia-blockchain folder an make a fresh install?
