### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LordGuspex** [Chia-Network/chia-blockchain#3610]
👋 Hi, I’m @LordGuspex I created some plots, however after I upgraded the Chia Blockchain to version 1.1.3, these plots don’t load into the farm!
![issue plots](https://user-images.githubusercontent.com/83625614/116957057-41c87100-ac6d-11eb-8478-f40c78ba3bf2.png)

**Comment by mariano54** [comment]
Please check that your keys are added, by clicking on the "Key" tab, and adding the keys which you used to make the plot.

**Comment by LordGuspex** [comment]
Is the same key, i not change, just update the version.
