### ISSUE TITLE
Waiting for Synchronization [help]

### ISSUE THREAD

**Issue by waasela** [Chia-Network/chia-blockchain#3612]
Plotting is done and it's 100%
But after plotting is completed, the full node status turned to ' Not Synced'.  How I do rectify this issue? Please help me. Thank you.

**Comment by gitcnd** [comment]
same. even after days - "Not Synced".

**Comment by Leozolt** [comment]
1.1.3 installed? reboot. . .activate .. if no node shows up under connections add node.chia.net 8444. Can you post a picture of your node connections or if you use the command line can you check if you have node connections?

**Comment by mtxprime** [comment]
don't plot and farm on the same unit if you are over a certain plot count

**Comment by minhquang93** [comment]
help me. 150 plot 3 days fram not see XCH

**Comment by mariano54** [comment]
Check out the wiki on how to port forward and get more connections: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections.
Also there is a recent bug which will be fixed in the next version (1.1.4), related to peer connections.

**Comment by Revanchist522** [comment]
> help me. 150 plot 3 days fram not see XCH

The estimated time to win (ETW) with 150 plots (14.85 TiB) is around 2 months and that will change as the network grows when you farm solo.
