### ISSUE TITLE
Lets Talk about fees

### ISSUE THREAD

**Issue by roderick2021** [Chia-Network/chia-blockchain#3613]
Let's talk about the fees ..

when we create a transaction .. what fee do we have to put 0.001? I hope you can help us with this since there is not much information

For example for send 1 Xch

**Comment by dorkmo** [comment]
right now there is no minimum

**Comment by roderick2021** [comment]
In other words, I enter what I think and if the network accepts it, the transaction is made?

**Comment by mariano54** [comment]
It first goes into the mempool. If it has too low fees it will be rejected from the mempool. Then it goes into a block. As of now, 0XCH fee is sufficient to enter the mempool.
