### ISSUE TITLE
[REQ] Missing 1 XCH

### ISSUE THREAD

**Issue by zp2321187** [Chia-Network/chia-blockchain#3619]
**Describe the request**
When I create a new Transaction in Chia Blockchain software(GUI), I put '1' into the fee box. May I request the 1 XCH getting back? It is unclear that I don't know it is 1 XCH or 1% transaction cost. There is 1 XCH missing after the transaction as it is tooooo huge transaction cost, in this transaction I only transfer 0.1 XCH but it charged me 1 XCH.

My address is xch1vnhw2pdygch4r9r5fcmpvpr2yruqykwg0rttvaypt95nxpumvmzs2e3p76

**Images**
![image](https://user-images.githubusercontent.com/31069131/116963223-d1f0cf80-acda-11eb-8601-b90ad853be5c.png)

**Additional notes**
Add any other closing comments here.

**Comment by mariano54** [comment]
Sorry you paid a 1XCH fee to the farmer of that block. There is no way of getting that back.

**Comment by dorkmo** [comment]
Be careful my friend! hope you can farm 2 more.
