### ISSUE TITLE
[REQ] Prometheus exporter

### ISSUE THREAD

**Issue by Shm013** [Chia-Network/chia-blockchain#3622]
I'm interesting in monitoring and want to monitor chia wallet/farmer.

Is it possible to integrate Prometheus exporter endpoint into chai? For example I want to get info about such metrics as "Total size of plots", "Estimated network space", "Expected time to win" and others metrics from `chia farm summary` and `chia wallet show` commands.

**Comment by kswtch** [comment]
You already get all the information from the existing API. More details here: https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces
