### ISSUE TITLE
[BUG] Plotting randomly frozed without any error in log.

### ISSUE THREAD

**Issue by XarisY** [Chia-Network/chia-blockchain#3623]
**Describe the bug**
My system is i7 10700kf, 48GB ram, 2x1TB ssd, 24TB HDD. Windows10
When i plot in parallel with any lenght of time delay, I found that my plots will randomly frozed usually around 60%-90% of the progress. 
For example 
I plot 2 plot in parallel with 8 plots in total,
Q1 with 4plots 180Delay, 3Thread, 6750Gb memory,
Q2 with 4plots -same as above-

This has happen several times now, without any error logs.

**Comment by c4lib4n** [comment]
I have the lame problem .-.

**Comment by lorado** [comment]
Same here. It happens almost at the end of phase 3. 
What PC Setup do you have? RAM overclocking? 
I overclocked RAM to 3600, it is stable and works, but dunno, maybe plotting has issue with this. Gonna try to remove overclocking tomorrow

**Comment by sotnikop** [comment]
I find its more likely to occur with higher concurrency on the same SSD, Dropping parallel plots from 7 to 5 on my 2tb MP600 seems to have made it more stable.

When the issue occurs the chia plot processes seem to be stuck in D  (locked state) or S

Using AMD XMP profile on my RAM

**Comment by XarisY** [comment]
> I find its more likely to occur with higher concurrency on the same SSD, Dropping parallel plots from 7 to 5 on my 2tb MP600 seems to have made it more stable.
> 
> When the issue occurs the chia plot processes seem to be stuck in D (locked state) or S
> 
> Using AMD XMP pro
The thing with my case is the maximum plotting will happen on 1 ssd at a time, At least until it reach about 60-70% or around 200minutes delay before new plot started. While the other ssd will start around 15 minutes after the first plot started on the previous ssd. Therefore it is kot a lot of concurrency on ssd at all.
