### ISSUE TITLE
[help] Узел не синхронизирован с сетью уже более 12 часов

### ISSUE THREAD

**Issue by ramzai23rus** [Chia-Network/chia-blockchain#3628]
Обновился на версию 1.1.3 и нет синхронизации.

Ноды 
node-eu.chia.net 8444
node-or.chia.net 8444
node.chia.net 8444
Не добавляются

![Скриншот 04-05-2021 094309](https://user-images.githubusercontent.com/29545081/116968464-30a75080-acbd-11eb-97f0-a90ce8d67f34.jpg)

Может кто как решил данную проблему ?

**Comment by vbr07** [comment]
Same problem

**Comment by steplish** [comment]
тоже самое, автор, решил проблему?

**Comment by steplish** [comment]
заработало само

**Comment by madrigo64** [comment]
Узлы для подключения
node-apne.chia.net
introducer-apne.chia.net
introducer-apse.chia.net
introducer-or.chia.net
introducer-va.chia.net
introducer-eu.chia.net
2.154.179.57
68.188.6.62

порт 8444
