### ISSUE TITLE
macos: check for minimum disk space before allowing to start plot

### ISSUE THREAD

**Issue by eFishCent** [Chia-Network/chia-blockchain#363]
Plots can start even if there isn't enough disk space for the temp and final file.

Process will continue until entire drive is filled up and macos may have unpredictable behavior when this occurs.

**Comment by hoffmang9** [comment]
So far there is no checking on user input to see if the user has chosen a filesystem that can handle the plotting process.

There is checking to wait 5 minutes if a filesystem is out of space to attempt to give a user time to clear up some space.

This is why it's still beta.

**Comment by eFishCent** [comment]
Gotcha, not an issue relevant for beta. Closing issue.
