### ISSUE TITLE
NODE NOT SYNCED AND PORTS WELL OPEN [BUG]

### ISSUE THREAD

**Issue by vbr07** [Chia-Network/chia-blockchain#3630]
**Describe the bug**

Once or twice the day the node lost the sync
(It remains connected).

**To Reproduce**
Happens all time... cannot stay alive more than 12 hours...
Version of soft : 1.1.3 (latest)

**Desktop (please complete the following information):**

- OS:  windows 10
- OS  18.09
- CPU: intel i5-8400

**Additional context**
Go throught firewall and vpn
(Ports 8444 well opens input and outpout)

**Comment by firstrakly** [comment]
recommend using version 1.1.1 // I have a problem with Sync in version 1.1.2 and 1.1.3
