### ISSUE TITLE
[BUG] [Error 13] Permission denied.

### ISSUE THREAD

**Issue by vasya37** [Chia-Network/chia-blockchain#3636]
[Error 13] Permission denied. You are trying to access a file/directory without having the necessary permissions. Most likely one of the plot folders in your config.yaml has an issue.

Hello! Error number 13 appeared. Now I can't add my own directories with plots, how can I solve this problem? Program version 1.1.3. System version Windows 10 pro 64 bit. Before that, everything worked fine, after the update, this problem appeared.

**Comment by vladimircicovic** [comment]
Same issue here

**Comment by Alfed777** [comment]
++  same

**Comment by vladimircicovic** [comment]
Hi people, do this:
Before doing this make backup of config.yaml first ! 
1. Go to C:\Users\{YOUR_USERNAME}\.chia\mainnet\config\
2. Backup and THEN edit config.yaml 
3. find inside of yaml: plot_directories: 
4. Remove paths that are you not using or not existing or remove all (this is just where are directory for plot are)
5. save config.yaml
6. Start Chia app - if missing plot dir - add them

I just fixed and it works now.

**Comment by vasya37** [comment]
It works, thank you! There I had a few disks that I took out.

**Comment by vladimircicovic** [comment]
CLOBUG CLOBUG
(close the bug)

**Comment by htcll411** [comment]
Still can't be identified with this method!

**Comment by salvarez1988** [comment]
> Hi people, do this:
> Before doing this make backup of config.yaml first !
> 
> 1. Go to C:\Users{YOUR_USERNAME}\.chia\mainnet\config\
> 2. Backup and THEN edit config.yaml
> 3. find inside of yaml: plot_directories:
> 4. Remove paths that are you not using or not existing or remove all (this is just where are directory for plot are)
> 5. save config.yaml
> 6. Start Chia app - if missing plot dir - add them
>

Thank you very much, works!! I realize what happened and why this error happen!

**Comment by vladimircicovic** [comment]
> Still can't be identified with this method!

Please describe what is happening. Could you remove all paths from config.yaml as I wroted ? And then add path by path.

**Comment by htcll411** [comment]
I  remove all paths from config.yaml and add path, but  it's still not recognized

**Comment by htcll411** [comment]
My wallet generates a new address,But the  Manage Farming Rewards  address is old, inconsistent.

**Comment by ramiali1994** [comment]
Hello

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 81, in <module>
  File "chia/cmds/chia.py", line 77, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "chia/cmds/plots.py", line 135, in create_cmd
  File "chia/plotting/create_plots.py", line 96, in create_plots
  File "chia/util/path.py", line 23, in mkdir
  File "pathlib.py", line 1312, in mkdir
PermissionError: [Errno 13] Permission denied: '/Volumes/Chia - Temp'
[20582] Failed to execute script chia

MacOS Big Sur
Hard drive External 20TB 
ExFAT 

I need Command to create Ploting in My mac but the main pc doing farm in windows then i have my pool key and my farm key 

please help

thank you !

**Comment by eagle283** [comment]
I had this same issue today. I'm running Win 10 and had 5 plots stuck because of permission denied. I looked at the log of the first plot that was stuck, found the file that had permission issues and copied the name to notepad. I went to my ssd temp plotting directory and searched for the file name and copied that file to a different directory, deleted the old one in the temp plotting directory and than copied it back to the plotting directory. All of the plots that were stuck are now continuing. I hope this helps you.

**Comment by baronduke** [comment]
J'ai eu le même bug aujourd'hui . Suite au retrait d'un disque dur usb. Mais une nouvelle erreur s'affiche après avoir supprimer les lignes  du fichier config.yaml

Erreur : argument of type "none Type" is not iterable 

Que dois-je faire ?

**Comment by Alexcrte4** [comment]
> I remove all paths from config.yaml and add path, but it's still not recognized

in my case my wallet address were missing after restart windows.

I solved doing the following:
1- In config.yaml search "xch_target_address: null"  (it appears 2 times)
2- Replase "null" with your wallet address. 
3- Save config.yaml.
4- Start chia app, check your plots they should be working.
