### ISSUE TITLE
[BUG] RuntimeError: Unknown exception while plotting my first farm

### ISSUE THREAD

**Issue by serunos** [Chia-Network/chia-blockchain#3637]
Describe the bug :
I start plotting and when i reach 1% the log printed RuntimeError:RuntimeError: Unknown exception
and it seems to appear on any of the plot sizes

To Reproduce : 

1. Go to 'Plot > Add plot > Plot Sizes 101.4GB'
2. Select 101.4GB and 1 plot
3. See error RuntimeError:RuntimeError: Unknown exception

Expected behavior :
It should make a plot

Screenshots :
![image](https://user-images.githubusercontent.com/72872185/116974139-ebcfe980-acbd-11eb-978f-4d8a7cea3be3.png)
**Desktop (please complete the following information):**

- OS: [Win 10]
- CPU: [I7 10700k]
- RAM 16GB
- SSD 1To (Two partitions)

Additional context
I use the 1 partition for the temp file an another for the final file. It's the first time I make a plot

**Comment by vanthoi** [comment]
You view the log has been permission denied the right to see the line. Drive C cannot be a plot creation place. Or choose a folder or a drive that you have rights to. Or you must run under Administrator to create the plot on cell C.
