### ISSUE TITLE
[BUG] Stuck on Connecting to wallet

### ISSUE THREAD

**Issue by Igor-Shuginin** [Chia-Network/chia-blockchain#3642]
**Describe the issue**
I am stuck on Connecting to wallet

**To Reproduce**
I installed the new Chia version because it showed Wait for Synchronization, after installing I still had this "Wait for Synchronization" so I clicked CTRL+R to reload and check if it works, at it got stuck at connecting to the wallet. When I try to close the app is says: "Are you sure you want to quit? GUI Plotting and farming will stop." but I don't want that, because it could lead to an issue

**Expected behavior**
I thought if I reload Chia it would synchronize

**Screenshots**
![image_2021-05-04_102218](https://user-images.githubusercontent.com/76914246/116977341-9ba75600-acc2-11eb-8031-598b8f906e97.png)

**Additional context**
I installed the 1.1.3 version and after that it started and everything was OK, until I reloaded.

**Comment by fga352** [comment]
I have the same problem

**Comment by maks-okhmatenko** [comment]
Same issue here. Mac OS Catalina 10.15.7

**Comment by andrew-kratik** [comment]
same issue 
windows 10
Chia v1.1.2
![image](https://user-images.githubusercontent.com/2760937/116994569-8c83d080-ace1-11eb-8a4c-0a9471ea42bf.png)

**Comment by Igor-Shuginin** [comment]
Guys, I fixed it, you have to kill the chia task from the task manager and completely delete it(don't delete the plots though), and then install the newest version. Don't reload chia, just wait for synchronization it takes around 1 hr.

To the people who didn't understand

1) Kill the Chia task from task managers

2) Completely delete chia - 
            C:\Users\yourusername\AppData\Local\chia-blockchain
            C:\Users\yourusername\AppData\Roaming\Chia Blockchain
            - Delete those
            
3) Download the latest version(1.1.3)
           - https://github.com/Chia-Network/chia-blockchain/releases
          
Note that any plot that was plotting will stop and get deleted, you will keep the plots that are already plotted and finished, but not the ones that were plotting.

**Comment by STetsing** [comment]
For Mac users

After some analysis, this problem occurs during a repeated installation or an abnormal plotting break. 
On my side (macOS 10.15.5), I spotted the open files and port the chia application was reading from and discovered a directory `.chia/` on my home directory `/Users/<user>/`. 

1. I deleted the `.chia/` directory using `rm -rf /Users/<user>/.chia/`. Caution: this could delete permanently your wallet. Make sure you have your wallet backed up!!! 
2. Then I installed the chia project from the source following the official instructions made here: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#MacOS. I guess you could also download the binaries and it would work.
3. Check your firewall settings, if some requests are not getting blocked 

With all that being done, it ended up working again with my previous wallet configuration.

**Comment by mumtazali2** [comment]
Well above suggestions may temporarily fix the issue, which can be done by rebooting your system as well, but not a solution for the issue which comes back again.
