### ISSUE TITLE
[BUG] chia client doesn't work

### ISSUE THREAD

**Issue by fga352** [Chia-Network/chia-blockchain#3644]
**Describe the bug**
chia is stuck in "connecting to wallet"

**Desktop (please complete the following information):**

- OS:Win10
- CPU: Ryzen 3 3300x
- client: 1.1.3 (but I have reinstalled the 1.1.2 and the same situation is reproduced)

**Comment by 89856389797** [comment]
Та-же хрень. Вообще китайца чета странное придумали, опять недосперли
