### ISSUE TITLE
[BUG]Why cant synced?

### ISSUE THREAD

**Issue by CannotSync** [Chia-Network/chia-blockchain#3646]
Debug log :

 File "chia\rpc\rpc_server.py", line 212, in safe_handle
 File "chia\rpc\rpc_server.py", line 200, in ws_api
 File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

OS: win10 

I5-8500 16G ram

ver: 1.1.3

**Comment by johny182** [comment]
I have same issue. So far no luck...

**Comment by mrd0n** [comment]
Following this guide worked for me:
https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444

I'm not sure if it was adding one of the listed introducer node or opening up inbound access to TCP port 8444

**Comment by dorhivert** [comment]
same for me

**Comment by tacci101** [comment]
same issue on ubuntu...
