### ISSUE TITLE
[BUG] 1.1.3 - Not farming while syncing

### ISSUE THREAD

**Issue by iLexGit** [Chia-Network/chia-blockchain#3647]
Windows GUI
In the patch release notes it said the node would farm while syncing but it is not happening.

**Comment by gdias1992** [comment]
Same here.

**Comment by potato1992** [comment]
Same here, I have to wait for more than 9 hours syncing now as I re-installed my OS and thought it would farm. Have the team performed the development test before claiming that it's implemented?

**Comment by mariano54** [comment]
The notes are wrong, it will farm while syncing if you are already synced (and syncing to some point in the future). it's mostly a security feature. Sorry about the misunderstanding, i'll fix the release notes.
