### ISSUE TITLE
Connecting to wallet

### ISSUE THREAD

**Issue by en3my666** [Chia-Network/chia-blockchain#3648]
![image](https://user-images.githubusercontent.com/45823639/116981625-74578580-acd0-11eb-97cd-edac31ca9719.png)
During the operation of the application after the update to 1.1.3, this problem began to appear. Plotting farming continues its work.
Rebooting will solve this problem for a while but mess up the plots.
LOG
![image](https://user-images.githubusercontent.com/45823639/116981949-e203b180-acd0-11eb-9113-5a9059c74a9e.png)

**Comment by Chia-Blockchain** [comment]
I have the same Problem since 1.1.3. With 1.1.2 it worked.

**Comment by Maritims** [comment]
I experience this if I just close the GUI and open it again.

**Comment by Mehonoshin** [comment]
Same for me

**Comment by aldaron838** [comment]
Where do i find the logs? My wallet has "not synced" and getting the new 1.1.4 has not worked, nor has a restart worked either.

**Comment by freddygusto** [comment]
Deleting the .chia folder fixed it and I was able to restore my wallet. 
on macOS, the .chia folder was in my user directory. It's a hidden folder so you'll have to either remove it through terminal or show hidden files and delete it through finder.
