### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by able099** [Chia-Network/chia-blockchain#3649]
After Chia software is updated, more than 1t fields cannot be identified

**Describe the bug**
Not found Plots
Caution, deleting these plots will delete them forever. Check that the storage devices are properly connected.”

**Expected behavior**
Deal with this problem.

**Screenshots**
<img width="1147" alt="9378C40A-BF61-4CA8-8EF9-DF49D3310876" src="https://user-images.githubusercontent.com/83638683/116982250-24da7f00-acfb-11eb-9169-d589e7ac8096.png">

**Desktop (please complete the following information): After Chia software is updated, more than 1t fields cannot be identified

- OS: [ win10]
- CPU: [AMD Ryzen Threadripper 1920X 12-Core Processor	3.50 GHz]

**Additional context**
Please！

**Comment by vladimircicovic** [comment]
Hi,
Try same as described here https://github.com/Chia-Network/chia-blockchain/issues/3636 
In short: remove inside of config.yaml path for plot dir. And then add them when you start chia app
