### ISSUE TITLE
How to configure open remote connection RPC[help]

### ISSUE THREAD

**Issue by wanming851** [Chia-Network/chia-blockchain#3650]
How to configure open remote connection RPC

**Comment by cccat6** [comment]
I found there is a way without modifying code and compiling you could do that.
Change your `hosts` file.
Edit `127.0.0.1 localhost` to `0.0.0.0 localhost`.
It will listen to all the incoming requests but not just local requests.
This change might harm something else on your computer. Don't do it unless you know what you are doing.
