### ISSUE TITLE
[help] Missing XCH

### ISSUE THREAD

**Issue by zp2321187** [Chia-Network/chia-blockchain#3658]
**Describe the bug**
From History page I can see 0.65 XCH incoming, but there's no XCH in wallet. 

![image](https://user-images.githubusercontent.com/31069131/116994414-43487680-ad0b-11eb-93ac-4e946c93d2a0.png)

address: xch1lcuftflkk7s0tptshncnq7f44qrtasxyfw9ddqu73ner3qynqa9qflez73

**Comment by moertel187** [comment]
Have the same Problem.

The first incoming Chia was shown in the Wallet, but the third didn´t arrived and also has a different wallet?

![Bildschirmfoto 2021-05-06 um 16 58 45](https://user-images.githubusercontent.com/83774160/117320522-9bf34d00-ae8c-11eb-963e-0f8db23d0d14.png)

**Comment by teeks822828** [comment]
i have this same issue 1.45 chia incomming into a wallet, but its not going into my sending wallet

**Comment by teeks822828** [comment]
its been 3 days , funny tho as its height is the same height as one of my sending transactions
