### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jaichhabra** [Chia-Network/chia-blockchain#3659]
After the latest update when you restart your desktop and run the app again from scratch it gets stuck on the connecting to wallet screen for hours and doesn't move ahead.
When you try to close it the same thing happens and disconnecting and shutting down the node takes forever
![Screenshot (57)](https://user-images.githubusercontent.com/43894928/116998478-e98c8000-acfb-11eb-9a27-a0cceab126d5.png)
![Screenshot (58)](https://user-images.githubusercontent.com/43894928/116998502-f3ae7e80-acfb-11eb-968d-6dfddda065f8.png)

**Comment by mengxianyi000** [comment]
me too，
![image](https://user-images.githubusercontent.com/83649179/117003654-b3f59000-ad17-11eb-8083-abb44bcbdd7f.png)

**Comment by jaichhabra** [comment]
yes it's not working

**Comment by jaichhabra** [comment]
still there
