### ISSUE TITLE
Same here. It happens almost at the end of phase 3.

### ISSUE THREAD

**Issue by XarisY** [Chia-Network/chia-blockchain#3665]
Same here. It happens almost at the end of phase 3. 
What PC Setup do you have? RAM overclocking? 
I overclocked RAM to 3600, it is stable and works, but dunno, maybe plotting has issue with this. Gonna try to remove overclocking tomorrow

_Originally posted by @lorado in https://github.com/Chia-Network/chia-blockchain/issues/3623#issuecomment-831852205_

Yes i enable Xmp profile 3200 with lower cl, Also my ram are from 2 modules of 32GB (16x2)and 16GB (8x2) so this might be the main reason, I will try to remove 16Gb ram first and see what happen.

**Comment by parko86** [comment]
Same here.

**Comment by pwagma** [comment]
Same situation, my memory is 3600mhz, mother goes maximum 2933, but it reads them as 2133.
What do you suggest?

**Comment by XarisY** [comment]
I solved the issue by disable xmp profile, So far work without anymore issue.
