### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qq812291236** [Chia-Network/chia-blockchain#3666]
**Describe the bug**
昨天开放转账的时候，我不会操作。我不小心给自己的钱包转账了，然后点了跟换地址，我还能找到自己的钱币么。希望国外的friend给与解答。不胜感激。thinks，作为一个热爱奇亚的朋友，我不想失去我人生中第一个chia币。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: widow
- OS Version/Flavor: [e.g. win10]
- CPU: [e.g. 不重要，我只想找回自己的币。]

**Additional context**

**Comment by qq812291236** [comment]
thinks friend，

**Comment by qq812291236** [comment]
@Chia-Network

**Comment by qq812291236** [comment]
作为非常重要的钱包地址，我觉得不应该如此轻易的能变更，对于我们这种新手朋友来说。这是非常不友好的，这让我失去了chia失去了xch，失去的人生中很重要的一个环节。变更地址甚至没有一个提示，和警示，当朋友往你旧钱包充钱时。你可能失去你的xch@Chia-Network

**Comment by mariano54** [comment]
Hello, can you explain where you sent the XCH? Did you sent it to someone else's address? Or to an exchange? You can ask that exchange for a refund.

**Comment by qq812291236** [comment]
Thank you for your reply, I send you the address is the address I copy of the current, is also my first wallet system default address. I wanted to extract on okex yesterday when can trade deals, but enter his wallet address by mistake, I was hurriedly midpoint update personal address, cause my personal wallet address change now. I am very panic, don't know what to do

**Comment by qq812291236** [comment]
Thank you for your reply, I send you the address is the address I copy of the current, is also my first wallet system default address. I wanted to extract on okex yesterday when can trade deals, but enter his wallet address by mistake, I was hurriedly midpoint update personal address, cause my personal wallet address change now. I am very panic, don't know what to do

**Comment by qq812291236** [comment]
My English is not good, the machine, hope you can understand what I mean.


> Hello, can you explain where you sent the XCH? Did you sent it to someone else's address? Or to an exchange? You can ask that exchange for a refund.

**Comment by qq812291236** [comment]
@Chia-Network按其他帖子删除库以后，同步完成后，xch没了，就算之前转到自己的钱包里。我这个情况是再也找不回我的xch了吧？也没交易记录了。

**Comment by qq812291236** [comment]
> Hello, can you explain where you sent the XCH? Did you sent it to someone else's address? Or to an exchange? You can ask that exchange for a refund.

@Chia-Network按你的其他帖子删除库以后，同步完成后，xch没了，就算之前转到自己的钱包里。我这个情况是再也找不回我的xch了吧？也没交易记录了。
