### ISSUE TITLE
[BUG] Always "Connecting to the wallet" keep loading

### ISSUE THREAD

**Issue by JessePinkmanVN** [Chia-Network/chia-blockchain#3668]
**Describe the bug**
Always "Connecting to the wallet", it keeps loading forever, I tried to let it load for many hours (3-4 hours), and still keep loading "Connecting to the wallet"

There's many times I was plotting and the Chia (Windows application) went blank (white screen), but the drive still plotting, I tried to click View -> Reload (or Force Reload too), it still keep loading forever, I had to close Chia and restart and delete everything and plot again, I hate this bug. Even I don't get white screen but I click Reload it still shows "Connecting to wallet" and it just loading forever again

**To Reproduce**
1. Go to 'View'
2. Click on 'Reload (or Force Reload)'
3. See error

**Expected behavior**
Loading forever, end of my life and it still loading
**Screenshots**

![image](https://user-images.githubusercontent.com/83649220/117004542-5d388800-ad10-11eb-8682-f8178d460909.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 64bit
- CPU: AMD Ryzen 9 5900

**Comment by ju113n91** [comment]
Same issue...

**Comment by gnukleus** [comment]
Same Issue Ryzen 8 5800x W10 64 Pro

Processor	AMD Ryzen 7 5800X 8-Core Processor                3.80 GHz
Installed RAM	16,0 GB

Edition	Windows 10 Pro
Version	20H2
Installed on	‎31. ‎10. ‎2020
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

Temp C:
Main folder D:

**Comment by G4LLITO** [comment]
mismo problema, se pudo arreglar'?

**Comment by dorkmo** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/2269#issuecomment-830409321

**Comment by efgi1** [comment]
#3739

**Comment by fritol** [comment]
yo fix it. AMD ryzen3600 16gb ram win10pro

**Comment by filoalves** [comment]
Same problem with Threadripper and Win10. Worked for about one week.
Getting the following:

DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Fil%20A/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar/build/renderer/js/80.js.map: Unexpected end of JSON input

DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Fil%20A/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

**Comment by intelmib** [comment]
aqui mesmo problema nao vai no linux

**Comment by IT2core** [comment]
Same issue from 24/10/2021 - on version 1.2.9 and now same on 1.2.10

![image](https://user-images.githubusercontent.com/6873720/140414556-a478b52a-4be1-42a8-9db6-c79680fd2cb7.png)
