### ISSUE TITLE
[BUG]XCH three times lost 

### ISSUE THREAD

**Issue by zhyf918** [Chia-Network/chia-blockchain#3669]
**Describe the bug**
I receive three XCH , 1.5 XCH, 1.749 XCH ，1.74 XCH  but I cannot see it in my wallet （ the GUI  ）. This is my account:Fingerprint: 556999751 and  lost 3 XCH:
xch15lyuquuwn75ej2ntsv7dtqhvy6w52f2sxeve9m6pv08wmjelaszqvwy9k8 1.5 XCH  ,Wallet height:226672,
xch1mljtuyw0856vx0c25vdnxg50v98f62crr760lmh0swaxgpgtz9mqav674p 1.749 XCH,Wallet height:226613
xch1trmj8evn5urkdqcqy4y4gkz0274l00r3rncy3wv8lvnhhuhpq6uql6q52a 1.74 XCH Wallet height: 226565
Screenshots: https://user-images.githubusercontent.com/7028950/117004889-76532180-ac9b-11eb-9439-42a0a68e5a4b.png

**To Reproduce**

1. one account and login five computer 
2. plots and farming
3. see history record show the info，lost three times

 
**Screenshots**
![image](https://user-images.githubusercontent.com/7028950/117004889-76532180-ac9b-11eb-9439-42a0a68e5a4b.png)

**Desktop (please complete the following information):**

- OS: [e.g. windows]
- OS Version/Flavor: [windows server 2016 standard]
- CPU: [e.g. Intel Xeon  cpu D-1541 2.10Ghz]

**Additional context**
one account and 4 computer ,the soft version 1.1.2

**Comment by mariano54** [comment]
Can you provide more details? It looks like the second and third addresses received chia, but then they were spent in block 226672.
The first address received funds in 226672 and was spent in 226902.

https://www.chiaexplorer.com/blockchain/address/xch15lyuquuwn75ej2ntsv7dtqhvy6w52f2sxeve9m6pv08wmjelaszqvwy9k8

Maybe someone else has your keys?

**Comment by zhyf918** [comment]
I send 4 xch ( 0.01 xch, 0.001 xch , 1.989 xch, 2 xch) to okex xch1gtenvljuftezxeh8j6wr2d6wee3dmtwkj2ws2s9rzk7ws5saw03suen7ug

the keys only me know

**Comment by mariano54** [comment]
Resolved after some conversation. There are no missing funds.
