### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ToughBODY** [Chia-Network/chia-blockchain#3671]
![image](https://user-images.githubusercontent.com/83630049/117007008-b2c66200-ad1b-11eb-898e-fa572517c4e0.png)

![image](https://user-images.githubusercontent.com/83630049/117006442-07b5a880-ad1b-11eb-8156-1b18ee29bbdb.png)

xch1s7kgcckynfgzak57jrrt9yfcuxf656q98z586nrjpsy9072d3qes2ejszk

It's been 17 hours. How to solve it

**Comment by mariano54** [comment]
What version?

There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by ToughBODY** [comment]
thanks man !I'll try it right away

**Comment by ToughBODY** [comment]
> 什么版本？
> 
> 待处理交易被卡住存在问题。请按照以下步骤操作：
> 
> 1. 关闭您的钱包和节点
> 2. 删除您的钱包db文件：位于。这将需要同步您的钱包，但不是您的节点。然后您可以重新提交交易。`~/.chia/mainnet/wallet/db`
> 3. 请确保已升级到最新版本
> 4. 启动应用程序并等待钱包同步

thanks man I'll try it right away
