### ISSUE TITLE
Farming Status and Estimated Time to Win says Wait for Synchronization

### ISSUE THREAD

**Issue by somedumbguy** [Chia-Network/chia-blockchain#3672]
I currently have 2 plots. I obtained the first one over 12 hours ago and I'm still seeing the Waiting for Synchronization messages

Farming Status and Estimated Time to Win says "Wait for Synchronization"

**Comment by dorkmo** [comment]
Are you synced?

**Comment by somedumbguy** [comment]
No. It says under Full Node Status, Status: Not Synced.

How long should the Sync take?

Thank you

**Comment by dorkmo** [comment]
do you see any peers in your connections? you should have about 50. if not you might benefit from forwarding port 8444 to your computer

**Comment by somedumbguy** [comment]
I had to forward port 8444. Right now I have 4 that I entered manually other then the local ones. 

How do I get up to 50?
