### ISSUE TITLE
problemas al cultivar en dos maquinas

### ISSUE THREAD

**Issue by fernandowaco** [Chia-Network/chia-blockchain#3674]
quiero cultivar en dos portátiles, descargué e instale el programa de chia en los dos portátiles, ingrese las misma 24 palabras 
en los dos portátiles, estoy creando parcelas en los dos portátiles, pero solo en uno de los portátiles me aparece cultivando en el otro me aparecen sincronizando las parcelas creadas pero nunca se sincronizan, entiendo que hay una guía de agricultura en varias maquinas, pero es muy técnico para mi. me gustaría me ayuden solucionar mi inconveniente de paso se que estarían ayudando a muchos usuarios.

**Comment by lalaxP** [comment]
El mismo problema tengo yo, esperemos a ver si en una nuea actualizacion lo permite adjuntar.
parece que vaya al id de la placa con la que se crea el Plot.
A ver si nos ayudais.
Gracias
