### ISSUE TITLE
[BUG] Meet the conditions but not out of the block, almost the whole collapse of this problem

### ISSUE THREAD

**Issue by lh232510** [Chia-Network/chia-blockchain#3676]

**Comment by mariano54** [comment]
Can you provide more details? Or message me on keybase @sorgente711.

**Comment by lh232510** [comment]
I have reached the location of the broadcast block, and then other nodes rejected my request. I don't know why

**Comment by lh232510** [comment]
I have about 40p hard disk, but I can't get one

**Comment by lh232510** [comment]
![image](https://user-images.githubusercontent.com/19657622/117017228-050c8080-ad26-11eb-8d89-d99fd0e1f0a5.png)

**Comment by mariano54** [comment]
Can you send me the debug.log file on keybase? Please do not upload it here.

**Comment by mariano54** [comment]
I am sorgente711 on keybase.

**Comment by lh232510** [comment]
oK， More, can I have your email
