### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by daowudi123** [Chia-Network/chia-blockchain#3677]
**Describe the bug**

Before, there was a 10 transaction and the coin was received, but the display was being sent. Then I sent a 100 trade, but the system sent 200 trades. Causes a negative number to exceed the total amount of the account. The transaction was not completed and my currency was lost. I don't know what to do, it's been four or five hours。

My address：xch19wd34spn9tcc4ggzzqjfnj332py4jymd52y76pkr8skcpappvnrql5n65k

![IMG_20210504_214548](https://user-images.githubusercontent.com/83652462/117014530-772f9600-ad23-11eb-8aca-ffa83fd90431.jpg)

**Additional context**

**Comment by mariano54** [comment]
What version of the software are you using? Please make sure to use version 1.1.3.

There is an issue with pending transactions being stuck. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction.
3. Make sure you have upgraded to the latest version
4. Start the application and wait for the wallet to sync up

**Comment by daowudi123** [comment]
Thank you, I'll give it a try

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
