### ISSUE TITLE
[BUG-Fixed] Connected, but not synced. Since yesterday evening.

### ISSUE THREAD

**Issue by Thyrann82** [Chia-Network/chia-blockchain#3678]
**Describe the issue**
Since yesterday evening my sync did not resync. The connection is there, but the sync is simply not established. Restarting the program did not help either.

**Screenshots**
https://prnt.sc/12hcsc6

**System**
Win10 64bit
Intel i9 9900KS on MSI MEG Z390 ACE (MB)
4x8GB G.Skill DDR4 Ram

**Comment by dorkmo** [comment]
you might have to delete the mainnet database, it can get corrupted

**Comment by Thyrann82** [comment]
1. where can i find the mainnet db?
2. did i lost my XCH if i delete the mainnet db?

**Comment by rtorrado80ing** [comment]
The same thing happens to me, what can be done to solve it?

**Comment by dorkmo** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/2269#issuecomment-830409321

in the past i have also switched computers if i wasnt have luck with one

**Comment by Thyrann82** [comment]
I have now deleted the files (backed up beforehand so that nothing is lost) and I noticed that the connections I only had "Farmer" and "Wallet" were, all connections to "Full Node" were not available.

Can I adjust it somewhere so that my data accesses the "Full Node" connections again and is thus synced?

**Comment by Thyrann82** [comment]
HEUREKA! I think I found / fix it!

I cannot add new connections while my old / main connection is established.

After I deleted my old connection, I was able to insert a new connection!

Now the status has changed to "Syncing 227610/230477" and there is hope that a sustained sync will then be available.

**Workaround:**
1. go to C:\Users\yourusername\
2. rename the folder **.chia** to **.chia_**
3. start chia and wait until the status changed to "syncing..."
4. go to connections in Full Node
5. make a screenshot of the connections to "Full Node", you need this one, which has set a "height"
6. close / exit chia
7. go back to C:\Users\yourusername\
8. delete the folder .chia (**not your renamed** ".chia_")
9. rename the folder **.chia_** back to **.chia**
10. start chia and wait if you get all your connections (Farmer, Wallet and Full Node)
11. if you don't get synced, delete your connection to "Full Node"
12. now add a new connection with "connect to other peers" and add the IP+Port which you've screenshoted.

Now your status should be set to "Syncing..." until the highest/actual peak.

I hope it will work, I'll give you feedback, if my syncing process is done.

**Comment by DIlbert25** [comment]
My Nodes don´t stop sync, 24 hours syncing.... My coins disappear...

Until the day the coin was launched, everything worked perfectly.

I smell cheating.

**Comment by Frank-1996** [comment]
Kill all the chia's task and reloaded,,,wait about 30-40 minutes,,

**Comment by GuilhermeFeijo** [comment]
Thanks, it worked for me

**Comment by DIlbert25** [comment]
> HEUREKA! I think I found / fix it!
> 
> I cannot add new connections while my old / main connection is established.
> 
> After I deleted my old connection, I was able to insert a new connection!
> 
> Now the status has changed to "Syncing 227610/230477" and there is hope that a sustained sync will then be available.
> 
> **Workaround:**
> 
> 1. go to C:\Users\yourusername\
> 2. rename the folder **.chia** to **.chia_**
> 3. start chia and wait until the status changed to "syncing..."
> 4. go to connections in Full Node
> 5. make a screenshot of the connections to "Full Node", you need this one, which has set a "height"
> 6. close / exit chia
> 7. go back to C:\Users\yourusername\
> 8. delete the folder .chia (**not your renamed** ".chia_")
> 9. rename the folder **.chia_** back to **.chia**
> 10. start chia and wait if you get all your connections (Farmer, Wallet and Full Node)
> 11. if you don't get synced, delete your connection to "Full Node"
> 12. now add a new connection with "connect to other peers" and add the IP+Port which you've screenshoted.
> 
> Now your status should be set to "Syncing..." until the highest/actual peak.
> 
> I hope it will work, I'll give you feedback, if my syncing process is done.
> 
> **//Update:** IT WORKED! I'm synced again! I hope the developers can find a way to "simplify" this detour if someone recurs.

And your wallet? Sync normally????

My nodes are OK.

But wallet are syncing veryyyyy slowwwwww, like 3 days do complet sync...

**Comment by Thyrann82** [comment]
Yep, all fine now / again. :-)

In the case I was "not synced", everything was not synced.

**Comment by racabu** [comment]
Any solution that requires you to close the app or do anything else is NOT a solution. It's a workaround.
Something must be done in order for the app not to lose sync in the first place. And if it does, reconnect automatically.
