### ISSUE TITLE
[help] how to disable ssl certificate?

### ISSUE THREAD

**Issue by anysoft** [Chia-Network/chia-blockchain#3680]
**Describe the issue**
**we do not need ssl to protect connections. For more concise access to the API we want to disable the ssl.
How can I achieve this goal?**

**To Reproduce**
Steps that led up to your issue.

**Expected behavior**
A clear and concise description of what you expected to happen before you encountered your issue.

**Screenshots**

**Additional context**

**Comment by lcgogo** [comment]
@anysoft have the same requirement. Is there any tricky method to bypass the ssl verification?
