### ISSUE TITLE
has anyone else run in to this issue on the mac. when plotting it would give me this error at 6% everytime. can anyone please help 

### ISSUE THREAD

**Issue by Khowell101** [Chia-Network/chia-blockchain#3682]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**
![Screen Shot 2021-05-04 at 11 25 43 AM](https://user-images.githubusercontent.com/83658910/117028312-9995c500-accb-11eb-92dc-fac588081413.png)

**Comment by Leozolt** [comment]
I had this once when my temp drive was slightly too small.

**Comment by Khowell101** [comment]
Thanks 
i was writing the temp and final to the same 2TB drive. I will now put the temp on it own drive and the final on it own also
thanks again will let post again if it works.

**Comment by Leozolt** [comment]
> Thanks
> i was writing the temp and final to the same 2TB drive. I will now put the temp on it own drive and the final on it own also
> thanks again will let post again if it works.

2TB should be more than enough to plot 2x k32. I tried to plot a k33 on 2x 300GB drives in raid0 so 600GB for temp1 folder.

But if you try on the destination drive you can see If it succeds on that drive even if it is slower.

Maybe check the 2TB drive for write/read errors?

**Comment by Khowell101** [comment]
Ok 

I will teat the drive now and reformat it, then try plotting again and see what happens.
