### ISSUE TITLE
[BUG] Connecting to wallet

### ISSUE THREAD

**Issue by esstein** [Chia-Network/chia-blockchain#3688]
**Describe the bug**
Interface say only "Connecting to wallet"

**To Reproduce**
Start many plots with enough space when disk full try to stop it

**Additional context**
I tried to uninstall e install again, but keeping to say "Connecting to wallet"

**Comment by pitipi1** [comment]
Same Problem , can't connect to the wallet. Reinstall doesen't fix it

**Comment by beammeupjesus** [comment]
Same here. Been trying to connect for hours..

**Comment by PC101guy** [comment]
This might be whaats happening to me, can't connect, when you guys try to close the program does it get suck on closing down node and server for forever?

**Comment by beammeupjesus** [comment]
> This might be whaats happening to me, can't connect, when you guys try to close the program does it get suck on closing down node and server for forever?

Yes, precisely the same

**Comment by PC101guy** [comment]
> 
> 
> > This might be whaats happening to me, can't connect, when you guys try to close the program does it get suck on closing down node and server for forever?
> 
> Yes, precisely the same

The last thing I did before this issue, and its been running fine for me for about 5 days, was before I went to bed I tried plotting paraelle, I have 2 nvme's only 500gb each, normally I would plot 1 on each in que but this time I did paraell and I set 1 temp location as 1 nvme and a 2nd temp file as the other nvme and then I went to bed.   When I woke up this morning it was only at 14% with a windows message running low on disk space.  When I looked at my nvme's 1 was completely full, while it seemed like the 2nd temp location i selected didn't do anything.   I tried to close the program down from this state but it just hung forever so I forced shutdown my pc, and now here I am.

**Comment by pitipi1** [comment]
> > > This might be whaats happening to me, can't connect, when you guys try to close the program does it get suck on closing down node and server for forever?
> > 
> > 
> > Yes, precisely the same
> 
> The last thing I did before this issue, and its been running fine for me for about 5 days, was before I went to bed I tried plotting paraelle, I have 2 nvme's only 500gb each, normally I would plot 1 on each in que but this time I did paraell and I set 1 temp location as 1 nvme and a 2nd temp file as the other nvme and then I went to bed. When I woke up this morning it was only at 14% with a windows message running low on disk space. When I looked at my nvme's 1 was completely full, while it seemed like the 2nd temp location i selected didn't do anything. I tried to close the program down from this state but it just hung forever so I forced shutdown my pc, and now here I am.

Did the same and now it's broken

**Comment by PC101guy** [comment]
Still can't get it up, also noticed in task manager theres like 26 start_full_node.exe even after I close the program

**Comment by pitipi1** [comment]
Tryed to install the software at another PC and see there... no Problems. I can instantly connect to the wallet.

**Comment by PC101guy** [comment]
> 
> 
> Tryed to install the software at another PC and see there... no Problems. I can instantly connect to the wallet.

I ended up deleting all 3 folder locations on pc for chia and did a fresh install, let me enter my 24 word pass and now its up, but its syncing again so that will take awhile.... but atleast now im plotting again.  not sure what caused it but i didn't wanna wait for a fix when i need to get plotting.

**Comment by esstein** [comment]
> > Tryed to install the software at another PC and see there... no Problems. I can instantly connect to the wallet.
> 
> I ended up deleting all 3 folder locations on pc for chia and did a fresh install, let me enter my 24 word pass and now its up, but its syncing again so that will take awhile.... but atleast now im plotting again. not sure what caused it but i didn't wanna wait for a fix when i need to get plotting.

Which folders are they? Where the wallet data is saved?

**Comment by PC101guy** [comment]
I don't wanna suggest something that could screw you up but make sure you know your 24 word passphrase and this is what i did.  I deleted the chia folders in Appdata local and appdata Roaming and i also deleted the folder under my main drive Users then my user (yours would be different), then folder called called .chia, but inside that folder i copy and saved the db folder with 6 files in it, blockchain and peer files.  I then downloaded and installed the program again and entered my 24 phrase code , once the program began to sync again say 2000/209000 ect, i closed the program and opened up the new user/.chia/manfest/db folder and seen there was 3 files in there already, I then moved over the other 3 files I had saved from my old db folder into that one and restarted chia and it worked for me.  again this worked for me but you can do it at your own risk.

**Comment by PC101guy** [comment]
> 
> 
> > > Tryed to install the software at another PC and see there... no Problems. I can instantly connect to the wallet.
> > 
> > 
> > I ended up deleting all 3 folder locations on pc for chia and did a fresh install, let me enter my 24 word pass and now its up, but its syncing again so that will take awhile.... but atleast now im plotting again. not sure what caused it but i didn't wanna wait for a fix when i need to get plotting.
> 
> Which folders are they? Where the wallet data is saved?

why, do you still have the issue?

**Comment by esstein** [comment]
> > > > Tryed to install the software at another PC and see there... no Problems. I can instantly connect to the wallet.
> > > 
> > > 
> > > I ended up deleting all 3 folder locations on pc for chia and did a fresh install, let me enter my 24 word pass and now its up, but its syncing again so that will take awhile.... but atleast now im plotting again. not sure what caused it but i didn't wanna wait for a fix when i need to get plotting.
> > 
> > 
> > Which folders are they? Where the wallet data is saved?
> 
> why, do you still have the issue?

Yes. I didn't find the control files on windows and the "Connecting to wallet" never stops.

**Comment by esstein** [comment]
> I don't wanna suggest something that could screw you up but make sure you know your 24 word passphrase and this is what i did. I deleted the chia folders in Appdata local and appdata Roaming and i also deleted the folder under my main drive Users then my user (yours would be different), then folder called called .chia, but inside that folder i copy and saved the db folder with 6 files in it, blockchain and peer files. I then downloaded and installed the program again and entered my 24 phrase code , once the program began to sync again say 2000/209000 ect, i closed the program and opened up the new user/.chia/manfest/db folder and seen there was 3 files in there already, I then moved over the other 3 files I had saved from my old db folder into that one and restarted chia and it worked for me. again this worked for me but you can do it at your own risk.

It works, thanks. 

I uninstall Chia and removed almost everything on %homepath%\.chia leaved only the %homepath%\.chia\mainnet\wallet\db\wallet_peers.sqlite file. I didn't lose may keys and my old plots is syncing.

**Comment by PC101guy** [comment]
nice, Ya i think i went overboard deleting everything, some of those files don't have to be deleted like you stated.  glad it's doing something for ya know instead of trying to connect 24/7.

**Comment by Ocram35** [comment]
Situation 
- Chia does not stop and close down after error / memory overrun in plotting
- Can be forced down, but then does not reconnect anymore, runs for hours

First solution   # the issue happened twice so far, so i tried to improve the solution
- just deleted everything in the %homepath%.mia folder on a whim and restarted. Chia got up running, remembered the wallet. Could restart plotting normally.
- had to resync from scratch. Except for the resync from scratch I was happy.

Second solution
- in the %homepath%.mia/log foldert here was a file called .__debug.lock showing empty, which was the only file I deleted on a whim. Chia got up running remembering wallet, allowing to plot
- has still to resync but shows Peak Height etc. as when it crashed, so I hope the resync will go quicker.

Hope this helps and maybe there is a code solution which erases the  .__debug.lock file in case of a crash.

**Comment by horifaydo** [comment]
same on me.
