### ISSUE TITLE
[help]how to recover the mnemonic-seed？

### ISSUE THREAD

**Issue by bugxzhu** [Chia-Network/chia-blockchain#3689]
I used the docker image，and restart the docker image ，the container generate the new one。
And I found the rewards go to the old wallet address. I think this is a bug? why delete the fingerprint , the wallet address in the config file doesn't change?
So, how to recover the mnemonic-seed of the old one through wallet key?

**Comment by cliveflint** [comment]
Did you save the seed when prompted to do so?

**Comment by Leozolt** [comment]
Do you have a backup of the old system? Hasd-disk space shouldn't be an issue for proof of space farmers... Montly disk image or so helps avoiding bigger losses.

**Comment by cryptomec** [comment]
Restart should keep your files, maybe you created a new container instead. Show output of `docker ps -a`.

**Comment by bugxzhu** [comment]
> Restart should keep your files, maybe you created a new container instead. Show output of `docker ps -a`.

no,I prune all containers。。。
I have wallet key and wallet address.

**Comment by bugxzhu** [comment]
> Do you have a backup of the old system? Hard-disk space shouldn't be an issue for proof of space farmers... Montly disk image or so helps avoiding bigger losses.

I only backup wallet key and wallet address.
