### ISSUE TITLE
[help]SOLVED :-) all my 4 XCH are non spendable since days and still pending  SOLVED

### ISSUE THREAD

**Issue by masterbab99** [Chia-Network/chia-blockchain#3697]
**Describe the issue**
PLEASE NOTE!: The issue tracker is NOT a place to seek general support. You are better served starting a conversation in the Discussions area at https://github.com/Chia-Network/chia-blockchain/discussions or in the Keybase.io #support channel. If you create a support request here, it may or may not receive a response before being closed, and we cannot guarantee a timely response, or one at all. In the event that your issue is deemed to be the result of a bug, we will endeavor to review and update it accordingly as such instead of closing it.

**To Reproduce**
Steps that led up to your issue.

**Expected behavior**
A clear and concise description of what you expected to happen before you encountered your issue.

**Screenshots**

**Additional context**
![Capture](https://user-images.githubusercontent.com/83661496/117035244-602d7b80-ad04-11eb-98b4-e54892491b3a.PNG)
Hello

I have won 2 blocks since several weeks but there are still pending. I thought it was because transaction was off, but event after 1 day after transaction started my XCH are still pending.
What is the problem and how fix it please

for exemple why this one still not spendable ?
0xe758b62479d462b4388ceb098f60690b57ea5596abd655ada643dd5b2d379b8d

REGARDS

**Comment by DIlbert25** [comment]
You have luck. You can still see your coins ... And I don’t see mine anymore?

**Comment by masterbab99** [comment]
i am waiting for sync after shutting down the app and relanch

**Comment by cjhudlin** [comment]
I have also the same situation

**Comment by masterbab99** [comment]
I tried to wait , close the app, reboot the computer, then to delete and restore the memonics........Still the same 4 XCH pending. What can be cause such issue?? Is it possible that situation last for years or forever?

**Comment by masterbab99** [comment]
> I have also the same situation, but using linux gui

are they still pending for now ? Mine still pending

**Comment by fxfxfx2019** [comment]
you wallet status is not synced    ,It has to be consistent .

**Comment by masterbab99** [comment]
> you wallet status is not synced ,It has to be consistent .

Hello, 
1- thx for the anwser
2 Do you know how to force the sync of the wallet ? deleting , then importing back the mnemonics did nothing

regards
