### ISSUE TITLE
Can't connect to wallet

### ISSUE THREAD

**Issue by sozinet** [Chia-Network/chia-blockchain#3700]
I can't connect to my wallet: 
endless "Connecting to wallet"

Win 10, 19042.928
Chia Blockchain 1.1.3

**Comment by PC101guy** [comment]
something must of happened overnight because theres multiple people including myself that this issue is happening too.  do you remember the last thing you did?  did a plot fail or any issues before you last restarted program

**Comment by sozinet** [comment]
Just turn off my PC. Now finally i come in, byt now I have another problem:
![image](https://user-images.githubusercontent.com/67073001/117038743-4b52e700-ad08-11eb-8ba2-a47d530eae32.png)

**Comment by cliveflint** [comment]
I did a refresh of the gui and have had a spimming circle for the last 2 hours. 
As restarting seems to waste the blockchain creations I will have to wait for them to finish.

**Comment by PC101guy** [comment]
I ended up completely deleting all chia folders on pc and fresh reinstall and entered my 24 word pass.  its up now just have to do the entire blockchain sync again but atleast i can start plotting again.

**Comment by DIlbert25** [comment]
My Nodes don´t stop sync, 24 hours syncing.... My coins disappear...

Until the day the coin was launched, everything worked perfectly.

I smell cheating.
