### ISSUE TITLE
[help] Turn off farming on GUI

### ISSUE THREAD

**Issue by vvavepacket** [Chia-Network/chia-blockchain#3703]
I'm not getting support from the keybase channel so might as well github

Basically I have 2 machines, a plotter and a farmer. Currently, both GUIs are farming. Is there a way to disable farming on one of the GUI (disable farming on plotter).

Is there any config file to edit? If not, is there any port to block? I assume the GUI connects to some introducer so Im thinking if I could block that port or put an invalid introducer addres on startup, it will never farm.

I'm unable to use CLI so it will be GUI

**Comment by kshyshkin** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines

**Comment by kshyshkin** [comment]
in second machine add connection manual to your first machine ip address and 8444, it will get sync nodes actual from first farmer machine

**Comment by vvavepacket** [comment]
Question, if both machines were farming previously, do I need to still re initialize or copy the CA certs?

**Comment by kshyshkin** [comment]
Yes, need get CA from main machine you will use. Main mean in that harvester will work.
