### ISSUE TITLE
[REQ] Be able to move the application to another drive

### ISSUE THREAD

**Issue by GabesDark** [Chia-Network/chia-blockchain#3704]
**Describe the request**
As a low-capacity SSD User, its starting to be a problem to keep the chia application on my C: as the blockchain keeps increasing everyday, My main drive is 256gb of space, when i placed chia it had about 40gb of free space, now its starting to get to about 20gb easily within one week, I would really suggest that when installing chia, it should be able to install in another folder instead of it anyways setting it to the C:/ Drive, And if had installed it already, should be able to move the blockchain and the application to somewhere else to avoid the drive being full and stop syncing(and waste precious time to wait it to resync again).

**Additional notes**
Its going to be a issue in few months mainly because some users run their OS on a 128gb SSD drive.

**Comment by dustyjones49** [comment]
Chia let me install on another drive without any problems. 

Dusty Jones

**Comment by GabesDark** [comment]
Forgot to mention that this issue happens on windows only.

**Comment by fullet-tortuga** [comment]
Should be able to be installed as a portable application.

**Comment by avm-xandry** [comment]
The problem is still actual. Guys on reddit do some hints with symlinks, but would be better to have option in GUI.
