### ISSUE TITLE
Better GUI for easy setup of main nodes, farmers, and harvesters and swap their roles

### ISSUE THREAD

**Issue by pluto2021** [Chia-Network/chia-blockchain#3707]
**Describe the request**
The entire setup for the main node, farming, and harvesting computer network is not straight forward. It is like navigating in a jungle. In order to make this block chain more accessible to more people that might not have the skills to go through every single details, a user friendly set of GUIs is important. 

Would be great if there is a button on the GUI interface to enable main node, farming/harvesting node, and being able to toggle their roles (say main node migrating, or maintenance) with their IP addresses explicitly shown.  Provide information on how to resolve any connectivity issues.

Provide any warning on the GUI interface that would affect the ability to receive rewards, such as: Cannot receive rewards due to port #### closed, or due to too long a time to fetch the plot, any errors when communicating with peer that affects the rewards, or any rewards that one have missed due to computer maintenance or network issues, etc.

**Images**
If applicable (but not required), add diagrams or wireframes to help explain your request if it is GUI related.

**Additional notes**
I could not get port 8555 opened. Tried to open it on the router, and windows 10 firewall. But the port still show as closed when checking at https://www.yougetsignal.com/tools/open-ports/

**Comment by night-lurker** [comment]
could split it up into more programs... like a plotter only, and a farmer only 
so you only had to close 1 of the programs if anything was wrong , some might also just want a wallet
