### ISSUE TITLE
[help] XCH Balance is gone after re-setup windows

### ISSUE THREAD

**Issue by LeoJeong88** [Chia-Network/chia-blockchain#3711]
Hi, I downloaded and restored my Chia blockchain with my private key but all my balances are gone after I did format my windows 10. (My original plots are in the same HDD drive. I only did format my SDD where OS is there.)
Is there any way I can get back my balance? or Should it be back to my wallet after Syncing is done?

Thanks

**Comment by night-lurker** [comment]
well if lets say you won XCH at block 1000 , but you have only synced to block 900, it wont show, but when your sync passes the winning block the XCH should show up

**Comment by LeoJeong88** [comment]
@night-lurker 
I was also guessing this might be sync issue but thanks for confirming.

**Comment by DIlbert25** [comment]
My Nodes don´t stop sync, 24 hours syncing.... My coins disappear...

I smell cheating.

**Comment by night-lurker** [comment]
> My Nodes don´t stop sync, 24 hours syncing.... My coins disappear...
> 
> Until the day the coin was launched, everything worked perfectly.
> 
> I smell cheating.

well you should go wash ;)
but alot of people have trouble sync'ing ...
but did you upgrade to newest version 1.1.3 ?
also when it sync, do you see a xxx/yyyyyy where xxx gets higher ?
if not you might need to add some node connections on your own like node.chia.net port 8444

**Comment by DIlbert25** [comment]
> > My Nodes don´t stop sync, 24 hours syncing.... My coins disappear...
> > Until the day the coin was launched, everything worked perfectly.
> > I smell cheating.
> 
> well you should go wash ;)
> but alot of people have trouble sync'ing ...
> but did you upgrade to newest version 1.1.3 ?
> also when it sync, do you see a xxx/yyyyyy where xxx gets higher ?
> if not you might need to add some node connections on your own like node.chia.net port 8444

Yeah

All problems start after upgrade to 1.1.3...
I added many connections like node.chia.net port 8444, and others...

" also when it sync, do you see a xxx/yyyyyy where xxx gets higher ? "

I don´t understand.

What I saw is that a big diference on wallet numbers and nodes, peak height very diferent.

I´m waitting nodes syc to do this:
![image](https://user-images.githubusercontent.com/83551408/117073069-c798fa80-ad07-11eb-8bef-73517e323e4b.png)

**Comment by night-lurker** [comment]
> > > My Nodes don´t stop sync, 24 hours syncing.... My coins disappear...
> > > Until the day the coin was launched, everything worked perfectly.
> > > I smell cheating.
> > 
> > 
> > well you should go wash ;)
> > but alot of people have trouble sync'ing ...
> > but did you upgrade to newest version 1.1.3 ?
> > also when it sync, do you see a xxx/yyyyyy where xxx gets higher ?
> > if not you might need to add some node connections on your own like node.chia.net port 8444
> 
> Yeah
> 
> All problems start after upgrade to 1.1.3...
> I added many connections like node.chia.net port 8444, and others...
> 
> " also when it sync, do you see a xxx/yyyyyy where xxx gets higher ? "
> 
> I don´t understand.
> 
> What I saw is that a big diference on wallet numbers and nodes, peak height very diferent.
> 
> I´m waitting nodes syc to do this:
> ![image](https://user-images.githubusercontent.com/83551408/117073069-c798fa80-ad07-11eb-8bef-73517e323e4b.png)

Have you tried to reboot the computer... if not some of the programs from chia might still be running.. can look in task manager 

and when syncing... do you see like 600/250000 how far it is in the sync

**Comment by DIlbert25** [comment]
> > > > My Nodes don´t stop sync, 24 hours syncing.... My coins disappear...
> > > > Until the day the coin was launched, everything worked perfectly.
> > > > I smell cheating.
> > > 
> > > 
> > > well you should go wash ;)
> > > but alot of people have trouble sync'ing ...
> > > but did you upgrade to newest version 1.1.3 ?
> > > also when it sync, do you see a xxx/yyyyyy where xxx gets higher ?
> > > if not you might need to add some node connections on your own like node.chia.net port 8444
> > 
> > 
> > Yeah
> > All problems start after upgrade to 1.1.3...
> > I added many connections like node.chia.net port 8444, and others...
> > " also when it sync, do you see a xxx/yyyyyy where xxx gets higher ? "
> > I don´t understand.
> > What I saw is that a big diference on wallet numbers and nodes, peak height very diferent.
> > I´m waitting nodes syc to do this:
> > ![image](https://user-images.githubusercontent.com/83551408/117073069-c798fa80-ad07-11eb-8bef-73517e323e4b.png)
> 
> Have you tried to reboot the computer... if not some of the programs from chia might still be running.. can look in task manager
> 
> and when syncing... do you see like 600/250000 how far it is in the sync

I reboot many times.

Now, finelly, after 20 hours, nodes sync

And I do a Force Reload , to re-sync wallet...

System is more then 30 minutes trying to sync.... just wait... and pray....

**Comment by LeoJeong88** [comment]
My balance got back when sync is completed. More percisely, it was back to the wallet before its completion when the height number was hit where the XCH founded. I think the version is irrelevant but syncing should be completed to the same height level in XCH.

**Comment by night-lurker** [comment]
Well god its back...

the reason the wallet was empty is because...
A fresh(non synced) wallet have no idea what have happen since block 1

when it sync’s the wallet learn what have happened every block...
So if you won like 2 xch in block 100, the wallet need to read/learn about block 100 before it can see the reward arrived at your wallet address 

It have to be this way, else someone could just make a file that told your wallet it had 1000 xch

**Comment by DIlbert25** [comment]
> My balance got back when sync is completed. More percisely, it was back to the wallet before its completion when the height number was hit where the XCH founded. I think the version is irrelevant but syncing should be completed to the same height level in XCH.

How long did it take to sync?

**Comment by LeoJeong88** [comment]
> > My balance got back when sync is completed. More percisely, it was back to the wallet before its completion when the height number was hit where the XCH founded. I think the version is irrelevant but syncing should be completed to the same height level in XCH.
> 
> How long did it take to sync?

I guess it takes round 6-7 hrs? but this should be related to your peak height. The higher peak, the longer.

**Comment by DIlbert25** [comment]
My wallet has been in sync for over 10 hours and hasn't even arrived in half.

**Comment by night-lurker** [comment]
Hi,
It depend on the people you connect to

i hope in the future there Will be made a “image” of the wallet dB, we can download, so we dont need to Sync it all, i know some other coins have this
