### ISSUE TITLE
Syncing stuck [BUG]

### ISSUE THREAD

**Issue by bazzah111** [Chia-Network/chia-blockchain#3713]
**Describe the bug**
Status is 'Syncing 225755/231166' and hasn't moved in over 24 hours. I am connected to lots of full nodes but nothing changes. I have tried 1.1.1, 1.1.2 and 1.1.3 and have the same problem in all. Port 8444 is open. I tried deleting the peer database but it made no difference. 

My log is showing this error, roughly every 30s.

full_node chia.full_node.full_node: ERROR    Error: Err.UNKNOWN_UNSPENT, Invalid block from peer:

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.7
- CPU: 3.5GHz Intel Core i5

**Comment by tomekjarosik** [comment]
similar for me stuck at 225691 since 3rd May. My call stack:
```
2021-05-04T20:31:19.427 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 225691-225723 <class 'ValueError'>, closing connection {'host':'10.123.45.1', 'port': 8444}. Traceback (most recent call last):
  File "/root/src/chia-blockchain/chia/server/server.py", line 531, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/root/src/chia-blockchain/chia/server/server.py", line 528, in wrapped_coroutine
    raise e
  File "/root/src/chia-blockchain/chia/server/server.py", line 521, in wrapped_coroutine
    result = await coroutine
  File "/root/src/chia-blockchain/chia/full_node/full_node_api.py", line 104, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/root/src/chia-blockchain/chia/full_node/full_node.py", line 374, in new_peak
    if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 6, 0)), request.height):
  File "/root/src/chia-blockchain/chia/full_node/full_node.py", line 250, in short_sync_batch
    raise ValueError(f"Error short batch syncing, failed to validate blocks {height}-{end_height}")
ValueError: Error short batch syncing, failed to validate blocks 225691-225723
```

**Comment by tomekjarosik** [comment]
I started from scratch and it's syncing again. Let's see if it gets past 225000 (syncing it's very slow...)

**Comment by sky758570168** [comment]
I have the same problem as you..

**Comment by bazzah111** [comment]
> I started from scratch and it's syncing again. Let's see if it gets past 225000 (syncing it's very slow...)
@tomekjarosik 
Did you manage to fully sync? Dumb question - what did you do to start from scratch?

**Comment by tomekjarosik** [comment]
No. It it stuck at exact same block as before:
```
chia show -s
Current Blockchain Status: Full Node syncing to block 233923
Currently synced to block: 225697
Current Blockchain Status: Not Synced. Peak height: 225697
      Time: Mon May 03 2021 17:01:21 UTC                  Height:     225697
```

**Comment by tomekjarosik** [comment]
Fixed in version 1.1.4

**Comment by bazzah111** [comment]
I upgraded to 1.1.4 and still had the problem. I have deleted the files and started from 0 again. Sync is on track to take about 15-20 hours so I don't know if it will complete properly, fingers crossed!

**Comment by bazzah111** [comment]
I'm now fully synced and farming again! The GUI is showing 0 XCH, where I previously had 4, but they are still there if I query the address so I think it is all ok.

**Comment by aminlv** [comment]
i have 1.1.4 and since morning my sync stuck @ 255143/?
is there solution for this

**Comment by stevenvegar** [comment]
I had the same issue and I tried everything to solve this!!! UPnP was not, manual introducer configs was not, port forwarding was neither. Just put the correct time and zone configuration under Windows settings and that was all!!
Credits: https://youtu.be/bvZcNfz4hEc
