### ISSUE TITLE
Connecting to wallet

### ISSUE THREAD

**Issue by Bakvet90** [Chia-Network/chia-blockchain#3714]
**Describe the issue**
PLEASE NOTE!: The issue tracker is NOT a place to seek general support. You are better served starting a conversation in the Discussions area at https://github.com/Chia-Network/chia-blockchain/discussions or in the Keybase.io #support channel. If you create a support request here, it may or may not receive a response before being closed, and we cannot guarantee a timely response, or one at all. In the event that your issue is deemed to be the result of a bug, we will endeavor to review and update it accordingly as such instead of closing it.

**To Reproduce**
Steps that led up to your issue.

**Expected behavior**
A clear and concise description of what you expected to happen before you encountered your issue.

**Screenshots**

**Additional context**

**Comment by Bakvet90** [comment]
After updating from 1.1.2 to 1.1.3 it says connecting to wallet. I have let my PC run for a hour in the hope that it does connect it hasn't.

To Reproduce
Updating from 1.1.2 to 1.1.3

Expected behavior
Start up as usually

Screenshots
![image](https://user-images.githubusercontent.com/83671701/117062365-a6460780-ad23-11eb-9446-1c1d1970a0ba.png)

**Comment by brijmart1** [comment]
I have been facing same issue.

**Comment by cipy** [comment]
from CLI you could try

`chia show -a node.chia.net:8444`

**Comment by KsandeR1987** [comment]
I have the same issue. I had to emergency stop the GUI while it was plotting. I restarted the computer via the reset button. 
And after Chia begins to "eat" RAM
![Screenshot_1](https://user-images.githubusercontent.com/83676879/117078515-b28d8d00-ad42-11eb-81ed-2c9e03daff49.png)
