### ISSUE TITLE
已经同步但是耕地不进行尝试证明，等于是没耕种

### ISSUE THREAD

**Issue by dasgdvchgajs** [Chia-Network/chia-blockchain#3715]
耕种界面在已同步的情况下不进行证明

**Comment by cjhudlin** [comment]
Translation: The farming interface does not prove when it is synchronized

Please can you attach screenshot for others to help you?

**Comment by dasgdvchgajs** [comment]
> 翻译：同步时无法证明耕作界面
> 
![image](https://user-images.githubusercontent.com/83671107/117089241-7a5c6d80-ad87-11eb-959a-db92cd7aad1c.png)

> 请您附上截图以供其他人使用吗？



> 翻译：同步时无法证明耕作界面
> 
> 请您附上截图以供其他人使用吗？

![image](https://user-images.githubusercontent.com/83671107/117089289-94964b80-ad87-11eb-84ae-e37b3c247b83.png)
而且新绘图无法在耕种界面体现{绘图数没有变化}似乎耕种界面完全停止工作了

**Comment by zky001** [comment]
me too
