### ISSUE TITLE
Plotting[help]

### ISSUE THREAD

**Issue by MikePe1988** [Chia-Network/chia-blockchain#3716]
*My Plotting it is stock at 77% for the past 30 hours.
What to do?

**Comment by night-lurker** [comment]
try press the action : View Log ... 
have you stopped a couple of times and hav'nt removed old files, your harddrive could be full, need to delete em yourself

**Comment by MikePe1988** [comment]
I stopped the Plotting at 77% by exiting from the program. Now he doesn't recognize the plot and I have to start from the beginning. It is any other way? 
Thank you!

**Comment by night-lurker** [comment]
If you stop program, the plot is lost, can’t continue it..
So you have to delete the files for that plot or they will just use space

it’s a real killer to stop, or the computer crash, all non done plots are lost
