### ISSUE TITLE
[REQ] parallel batch plotting with delay with GUI

### ISSUE THREAD

**Issue by cjhudlin** [Chia-Network/chia-blockchain#3719]
**Describe the request**
A clear and concise description of your suggested enhancement, as well as some basic rationale to allow us to balance the effort/reward for the work, if possible.

It would be really great if we would get the possibility to parallel plot in batches with the GUI (i dont know if this is already applicable in the cli)

**Comment by night-lurker** [comment]
I’m not sure if you talk about this...
10 plot in queue , name set 1
Then 10 more in queue, name set 2
Then 10 more in queue, name set 3
Then 10 more in queue, name set 4

this will make 4 plots go at the same time, if 1 is done first another from that queue list is started, this way no more then 4 plots will run at a time

**Comment by cjhudlin** [comment]
thanks, yes something like that, but instead of making 4 runs of 10, i could say for example, 40 plots at 4 plot increments

**Comment by night-lurker** [comment]
> thanks, yes something like that, but instead of making 4 runs of 10, i could say for example, 40 plots at 4 plot increments, and make sure that those 4 plots complete before the next 4 will run... thinking about it, i guess i could queue them rather han parallel.. didnt think of that

It will do the same, but you can start em a bit after each other so all 4 plots don’t need to read/write like crazy at the same time on hard drive

**Comment by pluto2021** [comment]
This scheme has a serious drawback. If something goes wrong in the middle of the plotting, the entire plotting queue will be messed up and the GUI will become a nightmare shortly, as you cannot stop the plotting. You stop one, another in the queue will start. Just like a solid booster rocket, once you light it up, no stopping.
