### ISSUE TITLE
[REQ] Windows client should have default settings for temp and final dirs

### ISSUE THREAD

**Issue by auc0le** [Chia-Network/chia-blockchain#3721]
We should not have to set the temp and final dirs each time.  Their should be a global setting we can set the default on and then over ride if we need.

**Comment by MikhailZelenkov** [comment]
That's bullshit.
Let's say you installed a wallet on a 128 Gb disk (let it be with с:\), and you have 5 more disks.
And where do you think the wallet will have to "come up" with default directories for you? ;)

**Comment by auc0le** [comment]
You are misunderstanding the request.  They won't 'come up' with anything.  You will have a setting where you put in what you want your DEFAULTS to be.   Then when you add a plot the temp and final dirs will DEFAULT to these settings but just like you can now, you'll be able to override them.

With the system not supporting a resume, manually creating plots is garbage but would be a tad easier if I could default the paths.

**Comment by MikhailZelenkov** [comment]
In that case, yes.
I will say more - after canceling the block being created (well, I just wanted to delete it), the wallet tries to reboot and freezes, and all the work (if something is generated) goes to hell ...
