### ISSUE TITLE
[REQ] Change the unit of reward and do not ask users to re-generate the plot to join in the official pool

### ISSUE THREAD

**Issue by potato1992** [Chia-Network/chia-blockchain#3723]
I have plots that's sum to 65TB and farmed **0** XCH, I just wonder who designed the rule, why not change the 2 XCH in each block into 0.01 and deliver more blocks each day?

The original idea of Chia is to utilize **spare disks** for farming. However, how many **spare disks** does a normal user have? It's really ridiculous that the designers were not aware of those professional players who own PC cluster and tons of disks in PB.

And it's really foolish design that I have to replace all of my plot when I join the official pool in the future. You are pushing your users to the unsafe third-party pools. Have you noticed that almost 1/2 of your users have already joined the [HPOOL](https://www.hpool.com) ? Is this your original intention? Have you thought about the potential risk that half of your users are controlled by another company? Do you really want a better long run development for the Chia project, or just want to earn some fast money？

Please hire some real talents that have enough experience and change the design. Re-generating all plots is a waste of the precious SSD that human being produce.

**Comment by mariano54** [comment]
Working on this, will be released soon. There's a lot involved in making secure, decentralized pools.

**Comment by caiqinghua** [comment]
@mariano54 We want to run a pool and how can we get the info of official pool?
