### ISSUE TITLE
[BUG] Статус кошелька. Подключения: 0

### ISSUE THREAD

**Issue by mrzlak** [Chia-Network/chia-blockchain#3726]
Полный узел - синхронизирован
Кошелек - синхронизирован
Но в статусе кошелька - подключения: 0
Почему? Это нормально?
![image](https://user-images.githubusercontent.com/83674880/117072869-c7b1ee00-ad39-11eb-9f8c-6f3e83b47321.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by MikhailZelenkov** [comment]
Для синхронизация кошелька добавьте записи следующих узлов (хост - порт):

node-eu.chia.net - 8444
node-or.chia.net - 8444
node-apne.chia.net - 8444

После этого, через какое-то непродолжительное время, кошелёк "подватит" синхронизацию с ближайших полных нод.
