### ISSUE TITLE
[BUG] install-gui not work on Fedora 34

### ISSUE THREAD

**Issue by tarathon** [Chia-Network/chia-blockchain#3727]
**Describe the bug**
I can't install GUI on Fedora 34

**To Reproduce**
Follow all instruction after the line sh install-gui.sh

**Expected behavior**
## Inspecting system...
It's shown

Continuing in 20 seconds ...
## Inspecting system...
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m
## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: no package provides redhat-release
no package provides centos-release
no package provides cloudlinux-release
no package provides sl-release. 

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Fedora 34
- CPU: Ryzen 4700H

**Comment by tarathon** [comment]
It's might be Node and Fedora problem according to https://github.com/nodesource/distributions/issues/1188

**Comment by Triplelexx** [comment]
https://github.com/nodesource/distributions/pull/1214

**Comment by int128fly** [comment]
for people that are impatient edit the install-gui.sh file and replace CentOS/Redhat. installation else if for this

```
elif type yum && [ ! -f /etc/rocky-release ] && [ -f /etc/redhat-release ] || [ -f /etc/centos-release ]; then
                # CentOS or Redhat
                echo "Installing on CentOS/Redhat./Fedora"
                sudo dnf module install nodejs:12
```
