### ISSUE TITLE
[help] Is the Raspberry Pi 4 2GB fast enough for farming

### ISSUE THREAD

**Issue by gilMotta1** [Chia-Network/chia-blockchain#3728]
Here is my setup

I would like to commit 100TB to this project but I will separate my HDDs into 10 clusters. Each cluster with a Pi with 2GB RAM, 120GB SSD and 10TB HDD.

Is this good enough or will I waste time? Do I need a Xeon for farming? Is it true that the faster the CPU the faster I plot therefore ARM devices will not be competitive even if I have a Pi with 8GB and 100TB?

Another way to put this is:

Which is best to farm? One 2GB Pi with 20TB or One Xeon 32GB RAM with 20TB?

Unless I got the wrong idea, it is about the space, not the CPU power, correct?

Thank you for the clarification.

**Comment by dorkmo** [comment]
do you have a computer for plotting?

**Comment by Plopsi** [comment]
Farming does not need much, so the pi is sufficient. Plotting is the hazard ;).

With 100TB maybe 4GB - or even 8GB, if you run a full-node on it - would be better, but 2GB should do fine too, once synced.

**Comment by CobaltGit** [comment]
Go for 4GB just to be safe
