### ISSUE TITLE
Full Node 8444 port activation

### ISSUE THREAD

**Issue by iamstevefury** [Chia-Network/chia-blockchain#3732]
<img width="521" alt="Capture" src="https://user-images.githubusercontent.com/83677609/117079708-e2528a00-ad6e-11eb-9b25-3084c055d562.PNG">

Dear all

After I installed the 1.1.3 windows gui, i am having problems of the full node. Its seems not having any comm.
as the kib is 0. How should i go about solving this? I dont think my plot is in farming mode now

thank a lot! appreciated
I am currently running on windows with gui software for plotting and farming

**Comment by MikhailZelenkov** [comment]
To synchronize the wallet, add the records of the following nodes (host - port):

node-eu.chia.net - 8444
node-or.chia.net - 8444
node-apne.chia.net - 8444

**Comment by acknologia** [comment]
adding connections worked for me yday but today the new connections don't show up for me on the list even after i add them

**Comment by iamstevefury** [comment]
I managed to find the solution, it was my router's port issue. I had three seperate routers, to had this enabled i need to reserve my IP and forward there of from a static ID, never the less, its done, happy farming!

**Comment by justnewbiem** [comment]
> I managed to find the solution, it was my router's port issue. I had three seperate routers, to had this enabled i need to reserve my IP and forward there of from a static ID, never the less, its done, happy farming!

hey...after solving the pb can u get the data from 8444 port..?
![8444port](https://user-images.githubusercontent.com/83545158/117519446-30a09c80-afac-11eb-8a53-e16f68b7ea97.png)

**Comment by iamstevefury** [comment]
> > I managed to find the solution, it was my router's port issue. I had three seperate routers, to had this enabled i need to reserve my IP and forward there of from a static ID, never the less, its done, happy farming!
> 
> hey...after solving the pb can u get the data from 8444 port..?
> ![8444port](https://user-images.githubusercontent.com/83545158/117519446-30a09c80-afac-11eb-8a53-e16f68b7ea97.png)

Yeah I can, I ran a check of my port it is open. And on the home page of the GUI app, at the bottom I am connected to many other peers full mode. You need to set your router right and your IP for the 8444 be direct and enabled, best of luck
