### ISSUE TITLE
[BUG] Connecting to wallet loop

### ISSUE THREAD

**Issue by efgi1** [Chia-Network/chia-blockchain#3739]
**Describe the bug**
The GUI gets stuck in a loop trying to reconnect to a wallet that it is already connected to.

**To Reproduce**

1. Go to View after connected to a wallet
2. Click on Reload/Reload (or force reload) 
3. In development tools/console it will show "Already connected, not reconnecting" stuck on loop
4. The GUI will keep saying "Connecting to wallet"

**Expected behavior**
Since the wallet is already connected, it should simply load the normal GUI info. Instead, it gets stuck trying to connect to a wallet that it is already connected to.

**Screenshots**
![bug](https://user-images.githubusercontent.com/47036497/117086644-64f52e00-ad0a-11eb-9544-86f716534c38.jpg)

**Desktop (please complete the following information):**
- OS: Windows 10

- OS Version/Flavor:  19042.964
- CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GH

**Comment by bombdi** [comment]
Same issue, I guess it because XCH just launched on OKEx, please fix it ASAP.

**Comment by bombdi** [comment]
> Same issue, I guess it because XCH just launched on OKEx, please fix it ASAP.

![螢幕擷取畫面 2021-05-05 100746](https://user-images.githubusercontent.com/73331550/117090072-e50ea880-ad89-11eb-8fe3-2b7b6cc2b101.png)

**Comment by bombdi** [comment]
> > Same issue, I guess it because XCH just launched on OKEx, please fix it ASAP.
> 
> ![螢幕擷取畫面 2021-05-05 100746](https://user-images.githubusercontent.com/73331550/117090072-e50ea880-ad89-11eb-8fe3-2b7b6cc2b101.png)

**It has solved by uninstalled and reinstalled Chia Client, now is working, never mind.**

**Comment by adamz01h** [comment]
Same issue as above

**Comment by efgi1** [comment]
@bombdi Uninstalling and reinstalling is NOT a fix. It will happen again if you click reload. Also, a more efficient temporary fix is to simply close and reopen chia. Obviously this is not a good solution in the middle of plotting. Note, it does continue plotting when this is displaying.

**Comment by bombdi** [comment]
> @bombdi Uninstalling and reinstalling is NOT a fix. It will happen again if you click reload. Also, a more efficient temporary fix is to simply close and reopen chia. Obviously this is not a good solution in the middle of plotting. Note, it does continue plotting when this is displaying.

Thanks reply. My computer often crashes and auto restarts recently, I'm not sure it because Chia client or other reason, I'll try to close Chia for one day test.

**Comment by dalvarez94** [comment]
urn off the computer and it stays in connecting with the wallet and does not advance

**Comment by Khunmatthew** [comment]
i have a same problem!!!!

**Comment by efgi1** [comment]
@adamz01h That seems to be a good temporary fix, but each time this reload button is pressed it "locally corrupts the data". It's very consistent.
