### ISSUE TITLE
Help Not able to download the new 1.1.4 for windows installer

### ISSUE THREAD

**Issue by daniel8800** [Chia-Network/chia-blockchain#3741]
Hello, I have a problem, I'm not getting able to download the new release, so my chia stoped farming.
When I try to download the new 1.1.4 sofgtware, I get this error

Download link: https://download.chia.net/latest/Setup-Win64.exe
It redirects me to: https://download-chia-net.s3-us-west-2.amazonaws.com/install/ChiaSetup-1.1.-4.exe

I get the following message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>install/ChiaSetup-1.1.-4.exe</Key>
<RequestId>PV946K80ZDCWF1TA</RequestId>
<HostId>zFRWMIV+L97rr6/Ya1R8NwnUI6UmiLEvqLFAsVCSNIjipQam+BdIANcIKTLKlfSm6UsubjmW5h8=</HostId>
</Error>

Please I need the new sowftware.

Regards.

**Comment by Plopsi** [comment]
As far as I can see they didn't create installers (yet) for 1.1.4, only sourcecode-download in the release. I guess something went wrong :D - or someone was lazy.

**Comment by daniel8800** [comment]
I was able to download it using my 4g connection on my phone.. maybe... my ISP has some troubles to get to the download site or there are any restriction. but now... I think it's all fine! sorry to bother and thanks for all!
