### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Makusm1990** [Chia-Network/chia-blockchain#3755]
Hi there!

so in Germany its common thats your internet provider gives you once in every 24h a new IP-Adress...
and i notice that i have to restart pc and Chia Gui to get synced again...what is very frustrating when u are still plotting...

Port 8444 is open and firewall rules are set.
any workarounds?

- OS: Windows 10
- CPU: Intel 8700k

**Comment by Plopsi** [comment]
Also mein GUI auf windows 10 reconnected danach wieder, dauert aber 1-2 minuten. Und dann noch länger um wieder nodes zu finden - du kannst probieren nach einem reconnect manuell einen node einzutragen, dann ist's in der regel sofort wieder sync. Das Peer-Discovery ist etwas lahm bei chia - noch, ändert sich hoffentlich.

**Comment by Makusm1990** [comment]
> Also mein GUI auf windows 10 reconnected danach wieder, dauert aber 1-2 minuten. Und dann noch länger um wieder nodes zu finden - du kannst probieren nach einem reconnect manuell einen node einzutragen, dann ist's in der regel sofort wieder sync. Das Peer-Discovery ist etwas lahm bei chia - noch, ändert sich hoffentlich.

**Comment by Makusm1990** [comment]
Wo finde ich denn eine Liste mit den nodes?
Oder was genau meinst du?

**Comment by Plopsi** [comment]
ne echte liste gibt's nicht kannst aber den offiziellen EU mega node von chia probieren:

node-eu.chia.net
8444

oder den EU introducer:

introducer-eu.chia.net
8444

**Comment by Makusm1990** [comment]
Die füge ich immer manuell nach einem Neustart ein... Aber das scheint seit 1.1.3 auch nix mehr zu bringen...
Kann mich jetzt seit dem 03.05 nicht mehr sync 😭

**Comment by Plopsi** [comment]
check mal das log, ich hatte vorhin auch nen komischen fehler dadrin stehen, da war irgend ne file wohl defekt - ich glaub das war die DB der blockchain selbst...

**Comment by Makusm1990** [comment]
Bin jetzt at Work... Kann ich später schauen...
Wo finde ich die Log? . Chia/Roaming?

**Comment by Plopsi** [comment]
C:\Users\<deinbenutzer>\.chia\mainnet\log unter windows
