### ISSUE TITLE
[help] 5 Parallel Plots with 60mins staggering, all stuck at 32%

### ISSUE THREAD

**Issue by cyz122409** [Chia-Network/chia-blockchain#3756]

**Comment by Plopsi** [comment]
32% is the peak of time and space. Check the plot-log if it's waiting for space on drive, just in case your drive got full.

**Comment by Lex-0001** [comment]
I have a similar problem. Stops at 32% with error:
Only wrote 0 of 794 760 bytes at offset 47466110112 to "D: \\ 1 \\ plot-k32-2021-05-04-17-35 - (......) plot.table7.tmp" with length 47466110976. Error 1. Retrying in five minutes.

I am trying to create a Plot on an HDD (there is only 240 GB SSD and this is not enough). Another 2.52 TB is free on the HDD.

This is the second time I have encountered this problem (also by 32% and the same error). As a result, I have never been able to create a Plot yet.
Does anyone know how to solve it?

**Comment by Plopsi** [comment]
Is your D: a single drive or some Smart, JBOD, Virtual or RAID volume created in the windows drivemanger in the controlpanel?

**Comment by Lex-0001** [comment]
Single drive.
Maybe it's because NTFS compression is enabled on it?

**Comment by Plopsi** [comment]
Hmm possible - everything is possible to be honest.
I used NTFS on an NVME M.2 without compression - no problems... try to deactivate the compression and try again.
And I used a USB3 HDD with exFat, very slow, but also no problems. So give it a try.

**Comment by Lex-0001** [comment]
Thank you. I'm just now turning off compression.
