### ISSUE TITLE
不能同步！！！不能同步！！不能同步！！！

### ISSUE THREAD

**Issue by Autumnfruit-qq** [Chia-Network/chia-blockchain#3761]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by chenjiahong365** [comment]
开一个晚上就好了

**Comment by jonny77** [comment]
update your app to the latest version

**Comment by Autumnfruit-qq** [comment]
已经6天没同步了

**Comment by Autumnfruit-qq** [comment]
才升级了1.1.4

**Comment by jonny77** [comment]
> 才升级了1.1.4

delete all your db files  in the .chia dir and retry .

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck in 1.1.3. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction
3. Make sure you have upgraded to the latest version (1.1.4)
4. Start the application and wait for the wallet to sync up
