### ISSUE TITLE
[BUG] Missing XCH

### ISSUE THREAD

**Issue by stalker3k595** [Chia-Network/chia-blockchain#3768]
From History page I can see 0.75 XCH incoming, but there's no XCH in wallet.

![w1](https://user-images.githubusercontent.com/83692707/117106672-f1decc80-ad88-11eb-913b-c7f15dd0af30.jpg)

address:xch1xrxx3ssf02at36kc54lus2akdw9qwprjjlpsetv5ydhft2jm04us5q3k2k

**Comment by iLexGit** [comment]
You're in the blockchain:
https://www.chiaexplorer.com/blockchain/address/xch1xrxx3ssf02at36kc54lus2akdw9qwprjjlpsetv5ydhft2jm04us5q3k2k

You have those chia, the wallet GUI is super buggy

**Comment by stalker3k595** [comment]
So I can make a transaction from my wallet at 0.75?

ср, 5 мая 2021 г. в 11:03, iLexGit ***@***.***>:

**Comment by iLexGit** [comment]
Idk if doing it from a wallet that has not been updated will work...

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck in 1.1.3. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction
3. Make sure you have upgraded to the latest version (1.1.4)
4. Start the application and wait for the wallet to sync up

**Comment by stalker3k595** [comment]
Thanks for the help!!!  Everything appeared.

ср, 5 мая 2021 г. в 11:50, Mariano Sorgente ***@***.***>:
