### ISSUE TITLE
[help] Stuck at 'Connecting to Wallet' 

### ISSUE THREAD

**Issue by minssey** [Chia-Network/chia-blockchain#3769]
I can't get out of the screen 'connecting to wallet'
Reinstalled, restarted all but to fail. Latest version installed.

**Comment by iLexGit** [comment]
SAME!!!!!

**Comment by MtechBasics** [comment]
i klick on reload and now i stuck in there too.
I can see that my system is still plotting in taskmanager but there are no outgoing or incoming connections.
I do not restart the client while i have giant plots that would make me loose hours of plotting if i restart client!

**Comment by BLalov** [comment]
+1 stuck at wallet on Windows machine with the GUI, version: 
![image](https://user-images.githubusercontent.com/57322607/117120876-8e5e9a00-ad9c-11eb-8c88-dd9c975a947f.png)

**Comment by MustDhiMust** [comment]
Mine also, but after updated to 1.1.4 it back to normal, and also please adjust your computer clock, sometime it won't sync when computer clock was not right

**Comment by BLalov** [comment]
> +1 stuck at wallet on Windows machine with the GUI, version:
> ![image](https://user-images.githubusercontent.com/57322607/117120876-8e5e9a00-ad9c-11eb-8c88-dd9c975a947f.png)

++ Update, after restart and deletion of the db in C:\Users\<user>\.chia\mainnet\db and C:\Users\<user>\.chia\mainnet\wallet\db and starting the GUI, FIxed the issue!

**Comment by adamz01h** [comment]
Great this is the fix, you only have to wait for the entire database to re-sync
