### ISSUE TITLE
Delayed plotting in GUI

### ISSUE THREAD

**Issue by pluto2021** [Chia-Network/chia-blockchain#3770]
**Describe the request**
Would be great to be able to schedule plotting to happen at a specific time in the GUI

**Images**
N/A

**Additional notes**
N/A

**Comment by lvcivs** [comment]
For such a use case you are probably better off using the CLI. For example, you can use a bash script like the following to start one plot now and schedule a second one to start in 10min:
```

#!/bin/bash

cmd0="cd /home/aaa/chia-blockchain; . ./activate; chia plots create -k 32 -b 3600 -t /media/aaa/ChiaPlotTmp -d /media/aaa/ChiaPlot"
cmd1="sleep 10m; cd /home/aaa/chia-blockchain; . ./activate; chia plots create -k 32 -b 3600 -t /media/aaa/ChiaPlotTmp2 -d /media/aaa/ChiaPlot"

xfce4-terminal -e "bash -c '$cmd0; $SHELL'"
xfce4-terminal -e "bash -c '$cmd1; $SHELL'"
```

**Comment by pluto2021** [comment]
The CLI in windows is grossly slower than the GUI. Tried and wasted a lot of time!
