### ISSUE TITLE
[BUG]A transaction is pending since May 3 2021.

### ISSUE THREAD

**Issue by Evansoso** [Chia-Network/chia-blockchain#3772]
**Describe the bug**
A pending transaction since May 3 2021.
I made three transactions sending some XCH to ONE receiving address. Two of them were successfully received, but one keeps pending for two days.

**To Reproduce**

**Expected behavior**
clear the transaction.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/20409306/117108865-cd1b3280-ad51-11eb-8265-f406ca2956cc.png)

**Desktop (please complete the following information):**

- OS: Window 10
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**
Wallet address:
xch10agrlmnz27f7v7j9mjqkf6v4a3n8jwpv8ew977fawmcxfme040wqy3rc28
Coin:
0xef5012924b35124a414eaaf375502bc18841d746e32dc4547442b5b82f2c9643

**Comment by mariano54** [comment]
There is an issue with pending transactions being stuck in 1.1.3. Please follow the following steps:

1. Shut down your wallet and node
2. Delete your wallet db files: located at `~/.chia/mainnet/wallet/db`. This will require syncing up your wallet, but not your node. And then you can resubmit the transaction
3. Make sure you have upgraded to the latest version (1.1.4)
4. Start the application and wait for the wallet to sync up
