### ISSUE TITLE
[BUG] Wallet not synced since 1.1.3

### ISSUE THREAD

**Issue by iLexGit** [Chia-Network/chia-blockchain#3774]
WINDOWS GUI: Ever since I updated to 1.1.3 my wallet says "1 connection" and "not synced". My node is synced and farming correctly but my wallet is stuck there. I even uninstalled chia and I updated to 1.1.4 as soon as it was out but nothing changed.

Also, not clear what the wallet connections are. I'm seeing_
 "Don't have rc hash ....."
 "Signache point XX not added"
Constantly showing up on my logs now, something I have never seen before, maybe it has something to do with it??

**Expected behavior**
No error, wallet syincing

**Comment by CHiEFROKKA** [comment]
Same Problem. Please Fix the Bug..

**Comment by MustDhiMust** [comment]
Did you updated to 1.1.4?

**Comment by iLexGit** [comment]
Yes I explain that in the first post. Also, don't know if that has nothing to do with all this but I saw a guy doing a 1.1.3 review on youtube and he was able to delete plots from the GUI as before 1.1.1 but I can't. I'm now at 1.1.4 and nothing has changed

**Comment by hzceo** [comment]
harvester not working.any guys suffer that

**Comment by MustDhiMust** [comment]
Mine also, but after updated to 1.1.4 it back to normal, and also please adjust your computer clock, sometime it won't sync when computer clock was not right

**Comment by iLexGit** [comment]
> Mine also, but after updated to 1.1.4 it back to normal, and also please adjust your computer clock, sometime it won't sync when computer clock was not right

Yeah I already did that... Everything is fine, the node is working, It's just the wallet that is not syncing whatsoever. It says i have one connection, but I don't know what wallet connections are or how many I am supposed to have. Either way it says not synced and hasn't changed for DAYS no matter what I try

**Comment by DIlbert25** [comment]
After upgrading to version 1.1.3, the system lost all synchronization.

After several attempts, uninstallations and folder removal, many reboots, disable uPnp, delete my wallet database with Powershell... the full node started to synchronize SLOWLY and after more than 24 hours, it finally synchronized, height 234000.

Now, the wallet, even more slowly, is syncing. The speed will take about 03 to 04 days. Start from 0 and, after 12 hours, are in 50.000

How to increase this wallet synchronization speed?

I managed to open port 8444;
I have the 60 connections "conect to other peers";
I made the inclusion of several connection servers;
I tried to install, from scratch, on another computer, but the low speed continued.
No error messages in debug.log

I updated to 1.1.4... Nothing change...

**Comment by iLexGit** [comment]
Still nothing... it's been days, wallet height is not going up one bit...

**Comment by ervin20** [comment]
> Still nothing... it's been days, wallet height is not going up one bit...

Same problem

**Comment by bashar1988** [comment]
i have 1.1.5 and same problem
