### ISSUE TITLE
[BUG] Segmentation fault

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Chia-Network/chia-blockchain#3779]
**Describe the bug**
Segmentation fault

**To Reproduce**
```
sudo apt-get update
sudo apt-get upgrade -y

# Install Git
sudo apt install git -y

# Checkout the source and install
git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
cd chia-blockchain

sh install.sh

. ./activate

# The GUI requires you have Ubuntu Desktop or a similar windowing system installed.
# You can not install and run the GUI as root

chmod +x ./install-gui.sh
./install-gui.sh

cd chia-blockchain-gui
npm run electron &
```

**Expected behavior**
To Work

**Screenshots**
![image](https://user-images.githubusercontent.com/15908060/117118537-2c4c6780-ad91-11eb-807d-6aa73923f416.png)
**Desktop (please complete the following information):**

![image](https://user-images.githubusercontent.com/15908060/117118582-38d0c000-ad91-11eb-9827-55b39f88aa67.png)

**Additional context**

**Comment by codergoblin** [comment]
I have the same issue, initially in older versions, but persists in 1.2.1

**Comment by emlowe** [comment]
The initial report appears to be a crash in apt-get - not much we can do about that
