### ISSUE TITLE
[REQ] GUI from Docker

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Chia-Network/chia-blockchain#3781]
Dear all,

How to use the GUI from Docker?

Cheers, 

Francesco

**Comment by kswtch** [comment]
Short answer: You don't.

If your docker image has the GUI compiled you could export your host X11 display to your container using docker -e DISPLAY:$DISPLAY

**Comment by FrancescoSaverioZuppichini** [comment]
Cool, I will create the docker file with the GUI and make a PR :)

**Comment by FrancescoSaverioZuppichini** [comment]
All the scripts needed use `sudo` inside so they can't be directly called from docker

**Comment by FrancescoSaverioZuppichini** [comment]
I removed all the `sudo` and replace the `python` call with `python3`. Everything was installed correctly, but when I run `npm run electron` I got 

```
/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron: error while loading shared libraries: libatk-1.0.so.0:
`` @kswtch

**Comment by kswtch** [comment]
> How it is possible that you don't provide it now, this is one of the key components to sharability
Well, I am not involved in the project. There is absolutely no incentive for me to provide a docker container that includes the GUI. 

Also most people use docker to heavily automate the process of plotting and/or harvesting. You don't use the GUI for that. The CLI has everything you need and is far superior for using scripts or shell snippets to set up your harvesters and plotters. I can't think of any valid use case for a GUI to be available in the docker image. 

In my first reply I just wanted to point you in the right direction if you want to get started creating your own docker image with a GUI.

**Comment by FrancescoSaverioZuppichini** [comment]
@kswtch I thought you were involved since you replied very soon, fair enough :) 

What if I want to use the GUI? This should be possible, but running electron on Docker is a pain in the ass. I think for a beginner is way easier to see/setup everything with the GUI, but this discussion is off topic. Thanks!

**Comment by guydavis** [comment]
I was looking for this a while back and couldn't find one either so wrote my own.  Checkout [Machinaris](https://github.com/guydavis/machinaris).

**Comment by FrancescoSaverioZuppichini** [comment]
Amazing mate 🚀

**Comment by devtestnet** [comment]
Y

**Comment by devtestnet** [comment]
Mypf 

 बायको १;  DC

  Gu।    : १( 

LrlqhbbyhuTT  ₹।  रीछ
 

 L

₹।     -- sf. Was  By
C 
PCP


L roz
Y
B l
Timi
Lunga

 

Fly 
D 
 
L 
 
I
M

I

 Uppyp
- uLpNhri
