### ISSUE TITLE
[BUG] Low velocity of sync

### ISSUE THREAD

**Issue by DIlbert25** [Chia-Network/chia-blockchain#3785]
After upgrading to version 1.1.3, the system lost all synchronization.

After several attempts, uninstallations and folder removal, many reboots, disable uPnp, delete my wallet database with Powershell... the full node started to synchronize SLOWLY and after more than 24 hours, it finally synchronized, height 234000.

Now, the wallet, even more slowly, is syncing. The speed will take about 03 to 04 days. Start from 0 and, after 12 hours, are in 50.000

How to increase this wallet synchronization speed?

I managed to open port 8444;
I have the 60 connections "conect to other peers";
I made the inclusion of several connection servers;
I tried to install, from scratch, on another computer, but the low speed continued.
No error messages in debug.log

**Desktop (please complete the following information):**

- OS: [ Win 10]
- CPU: [Intel Xeon 2620v3]

**Comment by mariano54** [comment]
Please upgrade to 1.1.4, it's faster. But yeah sync speed is something we need to work on soon. It should take less than 1 day now.
