### ISSUE TITLE
Wallet balance and Farming are inconsistent

### ISSUE THREAD

**Issue by digitalillusion** [Chia-Network/chia-blockchain#379]
I see that the sum of Pending Total Balance and Pending Farming Rewards from Wallet balance screen is no longer consistent with 
Total chia farmed from Farming screen. I wonder if this is a problem and if it is symptom of further impacts since the last farmed block happened last week which is way beyond the expectation (around 40h)
Please let me know if there is any other information needed to understand what's going on. Thanks

![farming](https://user-images.githubusercontent.com/94325/91287602-3c3a9300-e790-11ea-9e2c-a00518891fcd.png)
![wallet](https://user-images.githubusercontent.com/94325/91287624-465c9180-e790-11ea-9934-1bf4540971b9.png)

**Comment by hoffmang9** [comment]
The wallet somehow missed the reward. You can try two things. First you can choose reload in the view menu. If that doesn't fix it, stop the app, delete the ~/.chia/1.0b11/wallet/db/* and restart.

**Comment by mariano54** [comment]
Let's leave this open and investigate what caused this. @digitalillusion could you possibly send us your wallet DB file?

Both the farmer screen and wallet screen use the wallet DB to get the rewards. so they must be counting it differently.

**Comment by digitalillusion** [comment]
There are 2 files in ~/.chia/beta-1.0b10/wallet/db/*

[blockchain_wallet_v18.zip](https://github.com/Chia-Network/chia-blockchain/files/5135215/blockchain_wallet_v18.zip)

I did not yet update to b11

**Comment by digitalillusion** [comment]
So, I installed b11, deleted the two files in ~/.chia/beta-1.0b11/wallet/db and restarted.
The client synced but there is still a discrepancy between the two balances, as shown in the attached pictures.
This time, the newly created wallet db file is only one, attached in a zip.
And it seems to me that indeed the client did not farm anything in the last week or so, despite the expectation.

[blockchain_wallet_v18_2.zip](https://github.com/Chia-Network/chia-blockchain/files/5145253/blockchain_wallet_v18_2.zip)


![Schermata del 2020-08-29 15-38-34](https://user-images.githubusercontent.com/94325/91638185-c93e5000-ea0d-11ea-9351-c7788497c15d.png)

![Schermata del 2020-08-29 15-37-56](https://user-images.githubusercontent.com/94325/91638174-c2174200-ea0d-11ea-845b-a64a67bea155.png)

**Comment by digitalillusion** [comment]
All balances became coherent at last, so the problem was in my opinion related to the duplicated wallet db. Feel free to close this issue.

**Comment by hoffmang9** [comment]
May have been fixed in Beta 13. Closing this.
