### ISSUE TITLE
[BUG] Install Raspberry Pi 4 

### ISSUE THREAD

**Issue by benisdev-py** [Chia-Network/chia-blockchain#3791]
**Describe the bug**
I get an error if I try to install Chia With the Raspberry PI installer (https://github.com/Chia-Network/chia-blockchain/wiki/Raspberry-Pi)
and also I saw that the "blspy " Lib. has a problem with build...
I hope some one can help me.

**To Reproduce**

1. Go to 'Install Path'
2. Type in 'sh ./install.sh'

**Expected behavior**
I just execute the install.sh

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77000141/117122070-bbf41500-ad95-11eb-8a49-0d49bd6da174.png)
![grafik](https://user-images.githubusercontent.com/77000141/117122106-cca48b00-ad95-11eb-944e-dfaa4fe9710b.png)
![grafik](https://user-images.githubusercontent.com/77000141/117122144-db8b3d80-ad95-11eb-86d1-d57262cf59fb.png)
![grafik](https://user-images.githubusercontent.com/77000141/117123856-d8914c80-ad97-11eb-9429-70d842b4ab26.png)

**Desktop (please complete the following information):**

- OS: aarch64 GNU/Linux
- OS Version/Flavor: 5.10.33-v8+
- CPU: Quadcore Prozessor Broadcom BCM 2837

**Additional context**
//

**Comment by Plopsi** [comment]
No such file or directory 'cmake'

looks like 'cmake' is not installed on you pi. if your pi-image has apt-get it should work with 'sudo apt-get install cmake' to install it.

**Comment by benisdev-py** [comment]
I just installed cmake but I get the same error.
But thanks.

**Comment by benisdev-py** [comment]
Can any one Help me?

**Comment by dorkmo** [comment]
you might try on ubuntu server just to see if its an os thing

**Comment by leaiannotti** [comment]
Same problem here. Can anyone has an answer?
