### ISSUE TITLE
Endless wallet connection [BUG]

### ISSUE THREAD

**Issue by Flaberik** [Chia-Network/chia-blockchain#3793]
**Describe the bug**
Endless wallet connection. Restarting doesn't help.

**To Reproduce**
Plated for the night.
The ssd was full, the unfinished rafts had to be removed.
Now, when you try to open the chia blockchain, it hangs on the "connect to the wallet" page

**Expected behavior**
Connect and re-plot

**Desktop (please complete the following information):**

- OS: windows 10
- CPU: rayzen 5 2600
- RAM 16 gb 2400

**Comment by DIlbert25** [comment]
Here, same thing.

**Comment by ColorfulGhost** [comment]
Here, same thing.
dev console:
Already connected, not reconnecting.
0

**Comment by dalvarez94** [comment]
I'm the same, just connect to the wallet

**Comment by zufax** [comment]
Same problem

**Comment by Khunmatthew** [comment]
same problem!!! my plot is wasted !!!

**Comment by oliman** [comment]
Well I have a crappy fix, try at your own risk.
I deleted my entire chia blockchain folder... the .chia/mainnet one.
I was then able to log-in to the chia program but now I'm SLOWLY re-syncing the entire blockchain... 6976 and counting
