### ISSUE TITLE
[BUG]  npm ERR! Failed at the chia-blockchain@ electron script.

### ISSUE THREAD

**Issue by yuzhongrong** [Chia-Network/chia-blockchain#3794]
(venv) ipfsnets@r730-202:~/chia/chia-blockchain/chia-blockchain-gui$ npm run electron

> chia-blockchain@ electron /home/ipfsnets/chia/chia-blockchain/chia-blockchain-gui
> electron .

sh: 1: electron: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ipfsnets/.npm/_logs/2021-05-05T10_16_38_820Z-debug.log

**Comment by yuzhongrong** [comment]
the detail log  :



(venv) ipfsnets@r730-202:~/chia/chia-blockchain/chia-blockchain-gui$ cat  /home/ipfsnets/.npm/_logs/2021-05-05T10_16_38_820Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ipfsnets/chia/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/ipfsnets/chia/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/ipfsnets/chia/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 info lifecycle chia-blockchain@~electron: Failed to exec electron script
12 verbose stack Error: chia-blockchain@ electron: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid chia-blockchain@
14 verbose cwd /home/ipfsnets/chia/chia-blockchain/chia-blockchain-gui
15 verbose Linux 5.4.0-42-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
17 verbose node v10.19.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error chia-blockchain@ electron: `electron .`
23 error spawn ENOENT
24 error Failed at the chia-blockchain@ electron script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by warcos2** [comment]
I have same bug. Any solutions?
