### ISSUE TITLE
[BUG] Unable to add plot directory + message box 22 always appearing

### ISSUE THREAD

**Issue by MagicienFr** [Chia-Network/chia-blockchain#3795]
**Describe the bug**
I'm unable to add my plot directory.

**To Reproduce**
When launching the windows client, a messagebox containing the text "22" appears.
I'm obliged to press OK to makje it disappear.

Then, after selecting the private key,  (and pressing multiple times OK in the messagebox), no plots are available. 
Pressing the link "Add Plot Directory" opens the window 'Add a plot" to select the folder (button "Add plot directory".
After pressing multiple times OK on the "22" messagebox, nothing happens !

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: 20H2
- CPU: Intel Core i7 - 8086K

**Additional context**
This happened after a PC crash while creating additional plots to an existing set of plots

**Comment by MagicienFr** [comment]
Version 1.1.2 uninstalled
Version 1.1.4 installed

MessageBox "22" is now "[Error 22] File not found. Most likely one of the plot folders in your config.yaml has an issue"

**Comment by lvcivs** [comment]
duplicate of #2692, see there for comments.

**Comment by MagicienFr** [comment]
Removing all plots directory in the config file make other issues. 
But removing the config file and relaunch the windows client solved the issue !

Thx a lot !

**Comment by MagicienFr** [comment]
Removing all plots directory in the config file make other issues.
But removing the config file and relaunch the windows client solved the issue !

Thx a lot !
