### ISSUE TITLE
[BUG] Low velocity sync wallet

### ISSUE THREAD

**Issue by DIlbert25** [Chia-Network/chia-blockchain#3796]
After upgrading to version 1.1.3, the system lost all synchronization.

After several attempts, uninstallations and folder removal, many reboots, disable uPnp, delete my wallet database with Powershell... the full node started to synchronize SLOWLY and after more than 24 hours, it finally synchronized, height 234000.

Now, the wallet, even more slowly, is syncing. The speed will take about 03 to 04 days. Start from 0 and, after 12 hours, are in 50.000

How to increase this wallet synchronization speed?

I managed to open port 8444;
I have the 60 connections "conect to other peers";
I made the inclusion of several connection servers;
I tried to install, from scratch, on another computer, but the low speed continued.
No error messages in debug.log

I just upgrade to 1.1.4, and, after more than one hour, nothing change...

Desktop (please complete the following information):

OS: [ Win 10]
CPU: [Intel Xeon 2620v3]

**Comment by DIlbert25** [comment]
Open port 8449 ( wallet port ) would help ?

**Comment by THe-SP00K** [comment]
No - the full node talks to the wallet (locally) - you should have
127.0.0.1   <high port number>/8449    Wallet
in your connection list.

**Comment by BenJ3D** [comment]
same problem, soon to 24h of synch and I am height 186000
