### ISSUE TITLE
[BUG]  err  after  npm run electron & 

### ISSUE THREAD

**Issue by yuzhongrong** [Chia-Network/chia-blockchain#3799]
(venv) ipfsnets@r730-202:~/chia/chia-blockchain/chia-blockchain-gui$ cat  /home/ipfsnets/.npm/_logs/2021-05-05T10_55_22_010Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ipfsnets/chia/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/home/ipfsnets/chia/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /home/ipfsnets/chia/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 silly lifecycle chia-blockchain@~electron: Returned: code: 1  signal: null
12 info lifecycle chia-blockchain@~electron: Failed to exec electron script
13 verbose stack Error: chia-blockchain@ electron: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid chia-blockchain@
15 verbose cwd /home/ipfsnets/chia/chia-blockchain/chia-blockchain-gui
16 verbose Linux 5.4.0-42-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error chia-blockchain@ electron: `electron .`
22 error Exit status 1
23 error Failed at the chia-blockchain@ electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by IIPoliII** [comment]
I have the same bug, found any solution?

**Comment by vanlongme** [comment]
I have the same bug on Ubuntu 20.04 desktop ltsc

**Comment by IIPoliII** [comment]
I was able to make it run using the .deb package but yeah..

**Comment by ebeng** [comment]
same issue here, with Ubuntu Server and Ubuntu Desktop, both v 20.04

Would really appreciate if somebody could check out what is happening here

**Comment by ebeng** [comment]
> I was able to make it run using the .deb package but yeah..

https://www.youtube.com/watch?v=Y5gwBl-7dkM

with the deb file I was also able to get it to work in a few sec's
