### ISSUE TITLE
soy de windows y no me deja entrar a chia, se queda en conectando al monedero[BUG]

### ISSUE THREAD

**Issue by alanzolot** [Chia-Network/chia-blockchain#3801]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by dalvarez94** [comment]
I'm the same, just connect to the wallet

**Comment by alanzolot** [comment]
Cómo hago eso?

**Comment by josmeras** [comment]
te pasa lo mismo que a mi, a ver si alguien nos ayuda...

**Comment by alanzolot** [comment]
> Soy igual, solo conéctate a la billetera

como me conecto si no puedo entrar a la aplicacion

**Comment by Ingecomp** [comment]
Después de mucho investigar e intentar, lo que me ha resultado es algo bastante contra indicado y solo lo comento pues a mi me funciona. He dejado horas que la aplicación se conecte y esto realmente no me ha resultado, además otras opciones como borrar los archivos sqlite nos fuerza a reconectarse nuevamente desde cero 😖, lo cual puede demorar dias!!.
Mi método es :
1.- Entrar, esperar máximo 2 minutos y si no conecta, empezar por a lo menos 1 minuto a presionar Ctr + R (Reload) y ver si conecta
2.- Pasado un tiempo prudente (2 o 3 minutos mas) si no conecta, salir de la aplicación
3.- Repetir nuevamente desde el punto 1
Así a lo menos en 15 o 20 minutos logra conectarse y no pierdo lo ya sincronizado.

Espero a alguien le sirva
