### ISSUE TITLE
Port 8444 is closed [help]

### ISSUE THREAD

**Issue by hbtpoprock** [Chia-Network/chia-blockchain#3802]
Do I really need to open the port for 8444 even my wallet status is Synced?

**Comment by uwerui** [comment]
Port 8444 is not open, is it not exploded？

**Comment by hbtpoprock** [comment]
> Port 8444 is not open, is it not exploded？

@uwerui I've been following this project for a while and seen people saying you must open port/do port forwarding for 8444 to allow other peers to connect to your node, so I'm curious that do I really need to open the port for 8444 even my wallet status is Synced?

**Comment by uwerui** [comment]
How to open port 8444？

**Comment by uwerui** [comment]
> > 端口8444未打开，是否未爆炸？
> 
> @uwerui我一直在关注这个项目一段时间，看到有人说您必须打开8444的端口/端口转发功能，才能允许其他对等方连接到您的节点，所以我很好奇我是否真的需要打开端口8444，即使我的钱包状态为“已同步”？


How to open port 8444？
