### ISSUE TITLE
[bug] Chia CLI: plotting in queue doesn't finish

### ISSUE THREAD

**Issue by Chiqui1234** [Chia-Network/chia-blockchain#3803]
**Describe the issue**
When I want make several plots in queue with Chia CLI commands and parameter *-n 15* (for example), the finished plot never appear in the disk.

**To Reproduce**

```bash
chia plots create -k 32 -b 3390 -u 128 -r 2 -t /your/temporal -d /your/final -n 7 -f yourFarmerKey -p yourPoolKey
```

Then, you need to wait at least one plot finished and check if is moved to final directory... In my case this didn't happened.

You can check something is happening because *df -h* will throw more space used in your disks. However any new plot are appearing in the final plot directory. Maybe the temporal files with keep there until 7 plots finished and then Chia will convert to final plot? The problem is I don't sure if HDD can store 7 tmp files and then, add final plot :P

**Expected behavior**
Final plot need to be moved to final directory when finished. Right now I don't see my finished plots and yes, I saw my console and several plots was in phase 4/4 **a day** ago.

**Additional context**
Ryzen 5 1600AF, 2x8GB 3000MHz, Adata Falcon 512GB NVME, 1x 1TB Toshiba 3.5", 1x 1TB HGST 2.5", Debian 10.9 (fresh install)

**Comment by Plopsi** [comment]
check the plot logs in ~/.chia/mainnet/plotter

**Comment by changpeng75** [comment]
> check the plot logs in ~/.chia/mainnet/plotter

no plot log on CLI。

**Comment by Chiqui1234** [comment]
> check the plot logs in ~/.chia/mainnet/plotter

I checked the TB written to my nvme and are only 930GB. I think Chia CLI freezes with *-n* parameter higher than 1.
Weird thing is, plotter logs doesn't exists for these plots started by the command:

```bash
chia plots create -k 32 -b 3390 -u 128 -r 2 -t /your/temporal -d /your/final -n 7 -f yourFarmerKey -p yourPoolKey
```

I have plot logs only for my first 4 plots created (these was created with *-n 1* and HDD, the NVME is a recent addition to the setup).

However, I was plotting in my 1TB HDD at the same time (while plotting with my new NVME), and the Chia CLI instance for HDD freezes too! Just like the NVME. The command are the same for both NVME and HDD.

The system, however, was working well without hangs or anything, besides Chia CLI freeze. I tried read S.M.A.R.T of NVME and HDD just for check possible disconnection but no, these devices was working ok.

**Comment by Chiqui1234** [comment]
No, the command I'm using have the same behaviour on my second Ryzen 5 machine... :(

**Comment by bszabo27** [comment]
Same happened to me today
`chia plots create -k 32 -b 3500 -r 2 -u 128 -t H:\PlotTemp -d J:\Plots -n 1` and `chia plots create -k 32 -b 3500 -r 2 -u 128 -t H:\PlotTemp -d J:\Plots -n 2` were running in parallel in 2 cli windows, they 'finished' about the same time with the first plot, but both only got copied to the final destination as .tmp files. Cli with -n 2 didn't start the 2.n plotting.
