### ISSUE TITLE
[help] full node stops proofing its plots and not showing itself in harvester network

### ISSUE THREAD

**Issue by drewmullen** [Chia-Network/chia-blockchain#3810]
**UPDATED ISSUE DESCRIPTION**
------------------------------------------------
The original issue setup has been changed per discussion but the same issue still persists. The latest description of the issue should be found [HERE](https://github.com/Chia-Network/chia-blockchain/issues/3810#issuecomment-833004991). Basically i stopped using a NAS but the problem described below still happens; harvester process goes `defunct` with no errors found in the logs

**ORIGINAL ISSUE DESCRIPTION**
------------------------------------------------

**Describe the issue**

I have:
- 1 full node - windows, gui, plotting and farming a NAS 
- 2 plotters/harvesters (fedora)
- 1 only plotter (ubuntu, copying to nas) 

all are on version `1.1.4`. after a couple hours the windows node:
- stops showing accurate count of plots on the nas
- stops showing plots its responsible for farming in `Last Attempted Proof`
- stops showing itself (`127.0.0.1`) in "Your Harvester Network"

GUI does show the harvester node IPs in Harvester network & it does show their plot counts in Last attempted proofs

I dont see any obvious errors with `Get-Content ~\.chia\mainnet\log\debug.log -wait`

I've let it run for hours and it stays the same. a restart of the app resolves all 3 of those bullets

should i be concerned? is there a way i can validate that the full node **IS** actually farming those plots & attempting proofs with them?

**Comment by dnavamosler** [comment]
same problem here

**Comment by dorkmo** [comment]
NAS has been reported to cause farming read delays.

**Comment by drewmullen** [comment]
@dorkmo 
> NAS has been reported to cause farming read delays.

Are you suggesting that:
- this is an issue i should be concerned with?
- using a NAS will cause this issue?

---- additional info below

working:
![image](https://user-images.githubusercontent.com/3812162/117159325-2ef98d80-ad8e-11eb-9292-90d283a6d6fd.png)
![image](https://user-images.githubusercontent.com/3812162/117159900-ac250280-ad8e-11eb-8a66-9d958de4a04f.png)

stops working (there should now be 272 in the full node plot count):
![image](https://user-images.githubusercontent.com/3812162/117159486-4f294c80-ad8e-11eb-9894-a272dc163329.png)
![image](https://user-images.githubusercontent.com/3812162/117159570-6405e000-ad8e-11eb-86db-b5b4477b93d4.png)

**Comment by drewmullen** [comment]
i moved most of my plots off the full node NAS and plugged directly to a harvester. i still have some plots on the nas though so we can troubleshoot... this feels like a bug to me though. either a GUI bug (not reporting accurately) or a **really** nasty bug causing me to lose a _ton_ of farm time on plots

**Comment by dorkmo** [comment]
yeah if those 270 arnt passing the filter you might have a delay issue. I dont have a nas so not sure, but you might search NAS in the github repository issues/discussipns.

**Comment by drewmullen** [comment]
thanks for the advice @dorkmo ... i think i can close this for now. maybe someone will solve the NAS issues at some point but im fine with plugging them into my harvester

gl @dnavamosler

**Comment by drewmullen** [comment]
This is definitely a bug... i noticed the harvester stopped reporting in my gui, not showing anything in proofs

![image](https://user-images.githubusercontent.com/3812162/117198222-bf4bc880-adb6-11eb-9f82-076108af9741.png)

last reported item from debug.log (1 hour old)
```
2021-05-05T14:02:22.415 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 6b47f46136... Found 0 proofs. Time: 0.15059 s. Total 320 plots
2021-05-05T14:02:22.415 harvester harvester_server        : INFO     -> farming_info to peer 192.168.2.61 f07013a9f08d05bc278ca590b45fcbe12f16810329487f6900718cdee760002e
```

```
$ ps aux | grep chia
...
Z    10:57   0:38 [chia_harvester] <defunct>
```

**Comment by dorkmo** [comment]
might read over this thread https://github.com/Chia-Network/chia-blockchain/discussions/3188 too

might have lost connection between node and harvester? are you able to plug your NAS into your node computer via usb?

does the harvester have a log? unfortuantely i've got a real basic setup so i dont know much about advanced stuff. not sure how to get help, i'd just try to gather as much info as possible and post here.

**Comment by drewmullen** [comment]
after you pointed out the issue with NAS' i moved all those external hdds and plugged them directly into a harvester (fedora). Here is the adjusted setup:

- 1 full node: windows, managing about 30 plots that are on a nas
- 1 harvester: fedora, managing about 325 plots
- 2 other harvesters (not important)

after i switched from having ~300 plots managed on the NAS to plugged directly into the fedora box, i figured that would solve the issue, closed the ticket. HOWEVER, i actually saw the exact same behavior. the harvester with 300+ plots was dropped from my local harvester network, and i was no longer getting proof attempts from those plots. thats what [this post](https://github.com/Chia-Network/chia-blockchain/issues/3810#issuecomment-832953261) describes. 

you can see in that post that linux actually shows the `chia_harvester` process as `defunct` and theres no error in `debug.log`.

**Comment by drewmullen** [comment]
at this point... im about to write a cron job that runs `chia start harvester -r` every hour... seems to happen after about 2 hours. this smells very strongly like a bug in the harvester daemon

**Comment by drewmullen** [comment]
14 hours later and the process is still running. not sure what caused it to go `defunct` last time but ill close for now

thanks again for the advice

**Comment by drewmullen** [comment]
i feel like im taking crazy pills here... the process died `defunct`. I think what i saw this morning was that the logs _appeared_ to still be going but *actually* `tail` had just stalled and when i pressed return it caught up

last attempted proof was actually just b4 4am...
`2021-05-06T03:40:30.130 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 2a6c4a5fb2... Found 0 proofs. Time: 0.02273 s. Total 336 plots`

```
$ ps aux | grep chia
3:13 [chia_harvester] <defunct>
```

**Comment by drewmullen** [comment]
`# malloc(): corrupted top size` then -> 
```
farmer3   241404  0.0  0.1 413920 48408 pts/2    Sl   09:57   0:02 chia_daemon
farmer3   241619  0.4  0.0      0     0 pts/2    Z    09:57   0:16 [chia_harvester] <defunct>
```

**Comment by drewmullen** [comment]
`corrupted double-linked list`  was sent to stdout and the process is now defunct

logs now read:
```
2021-05-06T12:01:57.485 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/farmer3/chia-1.1.4/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/farmer3/chia-1.1.4/chia-blockchain/venv/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by drewmullen** [comment]
closing this to open a bug report
