### ISSUE TITLE
[help] WALLET NEVER CONNECT

### ISSUE THREAD

**Issue by Einargn** [Chia-Network/chia-blockchain#3814]
**Describe the issue**
PLEASE NOTE!: The issue tracker is NOT a place to seek general support. You are better served starting a conversation in the Discussions area at https://github.com/Chia-Network/chia-blockchain/discussions or in the Keybase.io #support channel. If you create a support request here, it may or may not receive a response before being closed, and we cannot guarantee a timely response, or one at all. In the event that your issue is deemed to be the result of a bug, we will endeavor to review and update it accordingly as such instead of closing it.

**To Reproduce**
Steps that led up to your issue.

**Expected behavior**
A clear and concise description of what you expected to happen before you encountered your issue.

**Screenshots**

**Additional context**

**Comment by MegaKocur** [comment]
My wallet says connecting for hours than show white screen, cpu usage 23% and mem about 6-5GB than dropping to iddle...

**Comment by Einargn** [comment]
> My wallet says connecting for hours than show white screen, cpu usage 23% and mem about 6-5GB than dropping to iddle...


The solution I found was to delete EVERYTHING except the chia installer in windows

**Comment by L0rDAst3r1X** [comment]
Same error since i updated from 1.1.3 to 1.1.4., now is stucked at connectig to wallet, did the port thing and didnt worked,  tried to roll back to 1.1.3 but that releas is faling to connect as well

**Comment by oliman** [comment]
Same here, I have seen 3 other bugs created by others with the same problem

**Comment by oliman** [comment]
Well I have a crappy fix, try at your own risk.
I deleted my entire chia blockchain folder... the .chia/mainnet one.
I was then able to log-in to the chia program but now I'm SLOWLY re-syncing the entire blockchain... 6976 and counting

**Comment by Aspisen** [comment]
It's literally the sync file inside the wallet in your Chia files that are blocking you from logging in.

If you go to your directory, mine is at C:\Users\Username.chia\mainnet\wallet\db
Note^: It's the hidden file directory so you might need make sure hidden files are displayed.

And remove the largest file you will be allowed to log in again, but all your sync is removed.
You can copy the file out and keep it somewhere else for now if they come up with a fix later on.

I'm re-syncing right now and plotting. No reinstall needed.

**Comment by L0rDAst3r1X** [comment]
Oliman n aspisen where right, that worked!!!
