### ISSUE TITLE
[help]my wallet never synced

### ISSUE THREAD

**Issue by ywwz** [Chia-Network/chia-blockchain#3819]
I'm plotting in 4 PCs and farm one PC, use the same chia account. I found  my wallet on farming machine never synced and I can found many same message in debug.log

the  wallets status like 
"status: not synced
connections:0"
and Connections panel show
"127.0.0.1  xxxx/8449   Wallet"
the wallet port number is increasing...

how can i fix it?

debug.log like 
`2021-05-05T08:46:06.260 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-05T08:46:09.269 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-05T08:46:12.277 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError
`

**Comment by yuzhongrong** [comment]
me to  !!    about  the log 



(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ chia wallet show
Wallet height: 7040
Sync status: Not synced
Balances, fingerprint: 2331392080
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable: 0.0 xch (0 mojo)
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$

**Comment by yuzhongrong** [comment]
in  1.1.4

**Comment by yuzhongrong** [comment]
end height  7040

**Comment by ywwz** [comment]
> end height 7040

can I reply in Chinese?
为什么我的钱包面板那显示的状态是“未同步 0连接"? 这样不正常吧？
不知道和我4台主机P图 1台主机种田的环境有没有关系。 老是感觉不正常 也很久都没产出。

**Comment by yuzhongrong** [comment]
me to

**Comment by yjghddp** [comment]
> > end height 7040
> 
> can I reply in Chinese?
> 为什么我的钱包面板那显示的状态是“未同步 0连接"? 这样不正常吧？
> 不知道和我4台主机P图 1台主机种田的环境有没有关系。 老是感觉不正常 也很久都没产出。

请问你是使用windows平台还是linux啊，有GUI吗

**Comment by ywwz** [comment]
> > > end height 7040
> > 
> > 
> > can I reply in Chinese?
> > 为什么我的钱包面板那显示的状态是“未同步 0连接"? 这样不正常吧？
> > 不知道和我4台主机P图 1台主机种田的环境有没有关系。 老是感觉不正常 也很久都没产出。
> 
> 请问你是使用windows平台还是linux啊，有GUI吗

windows,我比较菜用gui

**Comment by ywwz** [comment]
> me to

我把p图机关闭upnp以后 现在种田机的钱包”已同步“了。 但是连接为0， 不知道正常不。

**Comment by yuzhongrong** [comment]
需要关闭farmer？

**Comment by mhonorato84** [comment]
same issue, any solution?

**Comment by Emperornero** [comment]
Also having this issue on multiple PCs, both Windows and Linux.

Why doesn't the wallet use the full node to sync?  All my nodes are synced, but the wallets are stuck at various block heights anywhere from 32k all the way up to 250k.

Considering there are no 3rd party cloud node Chia wallets, we really should move this up for priority fixing.
