### ISSUE TITLE
[help] Operation not supported when Chia copies files in network drive

### ISSUE THREAD

**Issue by vvavepacket** [Chia-Network/chia-blockchain#3820]
I'm getting `Operation not permitted. Retying in five minutes` when a plot is at 100% and tries to copy it to a network drive.
My network drive is via Samba and its a raspberry drive attached to external drive over the local network.

![image](https://user-images.githubusercontent.com/8295642/117155068-767e1a80-ad8a-11eb-80bb-3c7071666c79.png)

I tried copying files manually via Files manager, and it works.. I wonder why chia couldn't copy files over the network. What command does it use in unix, is it a cp command?

How can we troubleshoot this? I tried seeking help on keybase channel but didn't get any help.

**Comment by NerfWhatKilledMe** [comment]
I am having this exact same issue and have yet to solve it yet. From what I gather it has to do with our version of samba not being compatible with chia and the solution seems only possible through chia CLI. I'm gonna try that and get back to you if I can.

**Comment by vvavepacket** [comment]
@NerfWhatKilledMe  I'm still blocked on this.. Currently I just do manual transfer. Any luck on your end?

**Comment by LostVector** [comment]
This fixed it for me.  https://chiaforum.com/t/chia-plot-copy-fail/1210

**Comment by HsiangSun** [comment]
I meet the same problem.I used Linux platform Centos 8 to plot and transfer it to windows for mining. I have gave the mount point right and copy file to windows by manual.
