### ISSUE TITLE
[BUG]After internet connection down, Chia stops farming

### ISSUE THREAD

**Issue by huzeyfecoskun** [Chia-Network/chia-blockchain#3821]
**Describe the bug**
After adsl disconnect, chia never start farm again.

**To Reproduce**
start farming, drop adsl connection, activate adsl connection

**Expected behavior**
after adsl signal on, chia should start farming again.

version 1.1.2

**Comment by msowilo** [comment]
I use a 4G internet connection and it does the same behavior. Seems like Chia GUI needs to be closed and open again for it to synchronize, after an internet outage.

Auto-restart after sync fails or something similar would be great. 
Perhaps this could be set through CLI? 

Looking forward for an answer.
