### ISSUE TITLE
[help] After trying to setup harvester with "chia init -c xxx", chia wont start anymore

### ISSUE THREAD

**Issue by DeXtmL** [Chia-Network/chia-blockchain#3824]
**Describe the issue**
Not sure if this is a bug.

**To Reproduce**
1. on harvester machine, "chia keys add xxxx"   --> successfully added my key, and it's correct
2. copy the ".chia/mainet/config/ssl/ca" folder from the farmer machine to this harvestor machine as "~/farmer-ca"
3. on the harvester machine, execute "chia init -c ~/farmer-ca". This command completes successfully.
4. on the harvester machine, execute "chia start harvester -r", it shows: 

`Daemon not started yet`
`Starting daemon`
`Daemon not started yet`
`Failed to create the chia daemon`

And the debug.log is empty. I dont know about the cause.

**Screenshots**

**Additional context**
Ubuntu 20.04

**Comment by zombie665** [comment]
> 3. on the harvester machine, execute "chia init -c ~/farmer-ca". This command completes successfully.
What was the answer after this command?

**Comment by doubleUTF** [comment]
I'm having the same problem:

> > 1. on the harvester machine, execute "chia init -c ~/farmer-ca". This command completes successfully.
> >    What was the answer after this command?

This is what is logged in console:
`λ chia init -c ca\
Deleting your OLD CA in C:\Users\doubleUTF\.chia\mainnet\config\ssl\ca
Copying your CA from ca to C:\Users\doubleUTF\.chia\mainnet\config\ssl\ca
C:\Users\doubleUTF\.chia\mainnet\config\ssl\ca\chia_ca.crt
C:\Users\doubleUTF\.chia\mainnet\config\ssl\ca\chia_ca.key
C:\Users\doubleUTF\.chia\mainnet\config\ssl\ca\private_ca.crt
C:\Users\doubleUTF\.chia\mainnet\config\ssl\ca\private_ca.key
Found private CA in C:\Users\doubleUTF\.chia\mainnet, using it to generate TLS certificates
`

**Comment by zombie665** [comment]
In the config.yaml
_log_filename: log/debug.log
    log_level: INFO(?)

**Comment by doubleUTF** [comment]
I tried this still not much help:

`chia run_daemon
Chia directory C:\Users\doubleUTF\.chia\mainnet
No keys are present in the keychain. Generate them with 'chia keys generate'
C:\Users\doubleUTF\.chia\mainnet already exists, no migration action taken
`

`{"ca_crt": "C:\\Users\\doubleUTF\\.chia\\mainnet\\config\\ssl\\ca\\private_ca.crt", "cert": "C:\\Users\\doubleUTF\\.chia\\mainnet\\config\\ssl\\daemon\\private_daemon.crt", "key": "C:\\Users\\doubleUTF\\.chia\\mainnet\\config\\ssl\\daemon\\private_daemon.key", "message": "cert_path", "success": true}
daemon: already launching`

> λ chia start harvester -r
> Daemon not started yet
> Starting daemon
> Daemon not started yet
> Failed to create the chia daemon

Updated config.yaml, no logs are output to debug.log, only console output.

>   logging: &id001
    log_filename: log/debug.log
    log_level: ALL
    log_maxfilesrotation: 7
    log_stdout: true

**Comment by zombie665** [comment]
i had problems running on linux mint 19.3 i386.  There were no problems on the x64.  Reinstalling chia - did not start correctly?

**Comment by doubleUTF** [comment]
This was a fresh install of 1.1.4 on Windows 10. I could try uninstalling and re-installing, though I'm plotting right now, will try tomorrow.

**Comment by doubleUTF** [comment]
Just found the problem, there was a hung chia process and I had to end it manually.

**Comment by zombie665** [comment]
> Just found the problem, there was a hung chia process and I had to end it manually.

I also noticed that the farmer wallet harvester always hangs manually

**Comment by doubleUTF** [comment]
Yea, the code isn't perfect and there are frequent unhandled errors during runtime. For now we farmers can only keep an eye on the logs and processes. The devs got their hands full, can barely reply to open issues.

**Comment by zombie665** [comment]
CLI rules))

**Comment by Bobarshad** [comment]
> 3\. chia init -c ~/farmer-ca

Thanks
