### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mastershake3** [Chia-Network/chia-blockchain#3825]
**Describe the bug**
Connecting to wallet
**To Reproduce**
started last night May 4th and is unable to connect when opening. I was running 1.1.3 and just downloaded and installed 1.1.4 got the same issue. Restarted twice already and let it load for over 2 hours now.
<img width="1201" alt="Screen Shot 2021-05-05 at 8 32 18 AM" src="https://user-images.githubusercontent.com/83717684/117167822-74ad5a80-ad7c-11eb-970b-6f6ac4462ce6.png">
<img width="1202" alt="Screen Shot 2021-05-05 at 8 32 27 AM" src="https://user-images.githubusercontent.com/83717684/117167833-770fb480-ad7c-11eb-8bd6-b2b843e805ab.png">

**Expected behavior**
expect it to work 

**Screenshots**
attached is two screen shots

**Desktop (please complete the following information):**

- OS: 2019 15" MBP
- OS MacOS 11.3.1
- CPU: [2.4 GHz 8-Core Intel Core i9]

**Additional context**
I noticed there was a problem when the Mac says that my farming would take 13 years to complete. that seamed way to high... I restarted the computer and tried opening and got this issue.

**Comment by zombie665** [comment]
This is a BUG of the century

**Comment by vbarot87** [comment]
I'm having the same issue connecting to wallet in GUI. CLI shows an error connecting to wallet 
![CLI_Wallet_Error](https://user-images.githubusercontent.com/82550405/117172078-76394b80-ad99-11eb-90a9-bc5cc6e6ca41.PNG)

**Comment by zombie665** [comment]
I think it has to do with rights/permissions

**Comment by Mastershake3** [comment]
Any update on this or progress this is ridiculous!!!

**Comment by mariano54** [comment]
@vbarot87 you might have to delete your database in ~/.chia/mainnet/db

You can backup your DB, delete your entire ~/.chia folder, and re run the GUI. You might have to resync though. sorry about that.

**Comment by oliman** [comment]
^^ Thx @mariano54 - that allowed me to log-in. I just have to re-sync the entire block chain now

**Comment by vbarot87** [comment]
Mariano, thank you so much! that worked. I uninstalled and reinstalled
multiple times not realizing that the .Chia folder does not get deleted. I
assume this is a feature.

Thank you!

**Comment by Mastershake3** [comment]
I've tried several times even searching the entire library folder for addition .plist and data files and its still not working.

I made a test user account and thats giving the same "connecting to wallet"

**Comment by Mastershake3** [comment]
Oh it’s still a bug I NEVER got any support. Do I deleted the app and started investing in Doge and safemoon.
