### ISSUE TITLE
[BUG] China cannot list all plot files when the plot folder is shared thru SMB 

### ISSUE THREAD

**Issue by DeXtmL** [Chia-Network/chia-blockchain#3827]
**Describe the bug**
In chia GUI (Ubuntu), add a plot folder with 100 plots that's on another machine thru SMB, like  
` /run/user/1000/gvfs/smb-share:server=host1.local,share=plot_dst1/`
Chia only list several of the plots, both in GUI, or using 'chia plots -l'

**To Reproduce**
1. Prepare two machines with the same chia wallet.
2. On the other machine, create a samba shared folder with 100 plots in it. Check them by executing "chia plots check", verify everything is working properly.
3. on the main machine, open Ubuntu Files and connect to that shared folder anonymously, and check all files are intact,
4. On the main machine's the chia GUI, click "add plot directory", then in the folder selection dialog, choose "other locations" then choose the shared folder which step 2 connected.
5. The folder path is system generated: `` /run/user/1000/gvfs/smb-share:server=host1.local,share=plot_dst1/``
6. Close "add plot directory" panel, and observe that only a few (about 5~7) plots are added to the GUI
7. Using command line "chia plots -l", it also only lists very few plots.

**Expected behavior**
Chia correctly list all plot files in the remote folder

**Desktop (please complete the following information):**
Both machines:
- OS: Ubuntu
- OS Version: 20.04

**Additional context**
All plots are valid.

**Comment by DeXtmL** [comment]
Under the same config, using NFS share doesn't exhibit such issue

**Comment by pgconlin** [comment]
@DeXtmL please post full (remove identifying information if you like) path of the NFS share. I'm assuming it doesn't have the special characters that the gvfs path has.

I'm also having this issue and believe it could be due to the chia client not properly escaping the special characters in the gvfs path when it attempts to perform the copy operation from the temp directory to the destination directory.  Something about how the python or javascript parser involved in the "copy from temp to final" operation handles : or , or = in the path.

This is my error (including gvfs path):

Could not copy "/home/user1/chiaWork/plot-k32-2021-05-05-17-05-86719a98016b754577a7229fa1b9f9e727125907d4e8f263dd92462daf6babab.plot.2.tmp" to "/run/user/1000/gvfs/smb-share:server=truenas.local,share=chiaplots/plot-k32-2021-05-05-17-05-86719a98016b754577a7229fa1b9f9e727125907d4e8f263dd92462daf6babab.plot.2.tmp". Error Operation not supported. Retrying in five minutes.

**Comment by pgconlin** [comment]
Dang. Also failed via symlink, although does have the "simplified" path in the error message:

Could not copy "/home/user1/chiaWork/plot-k32-2021-05-06-07-30-649ebdda639d00b3042da46a06cdc6a78435aaa2ad62d9eae7d73980619624c7.plot.2.tmp" to "/home/user1/chiaWork/chiaPlots/plot-k32-2021-05-06-07-30-649ebdda639d00b3042da46a06cdc6a78435aaa2ad62d9eae7d73980619624c7.plot.2.tmp". Error Operation not supported. Retrying in five minutes.

**Comment by ManuMCoupe** [comment]
> 
> 
> Dang. Also failed via symlink, although does have the "simplified" path in the error message:
> 
> Could not copy "/home/user1/chiaWork/plot-k32-2021-05-06-07-30-649ebdda639d00b3042da46a06cdc6a78435aaa2ad62d9eae7d73980619624c7.plot.2.tmp" to "/home/user1/chiaWork/chiaPlots/plot-k32-2021-05-06-07-30-649ebdda639d00b3042da46a06cdc6a78435aaa2ad62d9eae7d73980619624c7.plot.2.tmp". Error Operation not supported. Retrying in five minutes.

Did you fix it?

I have a similar issue i think. I've done 20 plots on my Windows 10 computer, and now i want to transfer all Chia stuff to a new mini pc running Ubuntu. I've entered my 24 words on new Ubuntu machine, added the network path of these 20 plots, but Chia GUI says that plots are not found...

**Comment by pgconlin** [comment]
@ManuMCoupe so yeah bad news/good news.

Bad news is it does look like it's an issue with Python and fancy path characters although I was not able to find a specific smoking gun. Lots of stuff out there though about python-based application-specific issues and gvfs paths.

Good news is I was able to mount the same share with cifs instead and get a path acceptable to chia plots create.

[This article](https://unix.stackexchange.com/questions/68079/mount-cifs-network-drive-write-permissions-and-chown) and specifically the following command for the win:

`sudo mount -t cifs -o user=file-share-username,uid=$(id -u),gid=$(id -u) //remote-server/smb-share-name /local-mount-point`

Also you can force a much smaller/faster plot for testing purposes with something like this:

`chia plots create --override-k -k 25 -b 4000 -r 2 -u 16 -t /your-temp-path -d /your-final-path`

**Comment by ManuMCoupe** [comment]
> @ManuMCoupe so yeah bad news/good news.
> 
> Bad news is it does look like it's an issue with Python and fancy path characters although I was not able to find a specific smoking gun. Lots of stuff out there though about python-based application-specific issues and gvfs paths.
> 
> Good news is I was able to mount the same share with cifs instead and get a path acceptable to `chia plots create`
> 
> [This article](https://unix.stackexchange.com/questions/68079/mount-cifs-network-drive-write-permissions-and-chown) and specifically the following command for the win:
> 
> `sudo mount -t cifs -o user=file-share-username,uid=$(id -u),gid=$(id -u) //remote-server/smb-share-name /local-mount-point`
> 
> Also you can force a much smaller/faster plot for testing purposes with something like this:
> 
> `chia plots create --override-k -k 25 -b 4000 -r 2 -u 16 -t /your-temp-path -d /your-final-path`

Thanks for the answer!

My big problem now is that Ive plotted 20 on my windows system on a Qnap Nas. I install Ubuntu on a new machine, to free my main windows pc. I installed chia, import keys with 24 words. Launch GUI, added my SMB path to Snap where plots are. And nothing... My plot are not recognised :-S I've done a chia plots check, and I've got a warning that says "not same public pool and public adresses".... But I don't found the way to add my old famer and pool public adresses to new computer. Any idea to how to do that? Thanks for you help, I appreciate it! Have a nice day!
