### ISSUE TITLE
[help] Able to plot perfectly but my plots never are seen to farm.  They just go to "no found plots"

### ISSUE THREAD

**Issue by wingman264** [Chia-Network/chia-blockchain#3832]
![chiaissue](https://user-images.githubusercontent.com/35613892/117174442-b7caf600-ad9b-11eb-84c2-e19f941b158e.png)

Plotting works fine, plots are the correct size.  Nothing was done to disrupt the process.  Plots do not show up in the farming area.  Just has the prompt there to add plots when I go to farming.  Please help!

**Comment by ThalesC** [comment]
I'm not running the GUI, but I had this problem before, and my "solution" was to restart the harvester.

**Comment by wingman264** [comment]
thank you!  that worked...I feel so stupid..

**Comment by ThalesC** [comment]
> I feel so stupid..

Don't feel this way, this is not by any means a solution, just a way to make it work, I don't think the harvester is made to be restarted everytime a new plot is made.
I guess a chia dev could hop in here and help us, but in the meantime I guess we stick to restarting the harvester.
