### ISSUE TITLE
[BUG] - more than 24 hrs to sync 

### ISSUE THREAD

**Issue by tobiasncorso** [Chia-Network/chia-blockchain#3833]
I am new in the chia network. 

I am syncing for the 1st time, after more than 24 hrs the process still with status = 159072/235646.

The wallet still syncing.

I just tested the port 8444 and it is open. 

- OS: windows 
- Chia 1.1.4 
- Status - connect 
- wallet = syncing

**Comment by ThalesC** [comment]
Mine took 3~4 days to fully sync, but I could check if it was really syncing by running `chia show -sc`, so I just waited and it did its thing.
