### ISSUE TITLE
[help] multiple nodes behind same NAT router with a different wallet

### ISSUE THREAD

**Issue by olafbuitelaar** [Chia-Network/chia-blockchain#3834]
I recently started farming, and made by brother enthusiastic as well. But we're both behind the same NAT router, but want to farm individually with our own wallet. This document describes; https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines how you can farm on multiple machines, but they seem to share the same wallet. Currently the port 8444 is forwarded to my node, how can i achieve that both our nodes can farm, with a different wallet?

**Comment by ThalesC** [comment]
I guess you need to open port 8444 to one of the farmers and let the other farmer with this port closed, at least that's what I would do.

**Comment by kswtch** [comment]
Have you tried changing the port of the second full_node to something else in config.yaml? The Handshake the full_node is doing with other nodes includes the port for others to connect to.
See https://github.com/Chia-Network/chia-blockchain/wiki/Networking-and-Serialization for more information.

**Comment by olafbuitelaar** [comment]
Thank you for the good suggestion, i've checked the config.yaml, and in de full_node section i see the ```port: 8444``` property. Also throughout the config.yaml i see multiple references to it self;
```yaml
full_node_peer:
    host: localhost
    port: 8444
```
i suppose all these needs to be updated, with the new port configuration? Are there any other places to check for this port setting?

Also this document (https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444) seems to indicate port 8444 is solely used so other peers could download/sync the block-data. I thought it was also used for receiving challenges. So i theory (if understood correctly) it could work without port 8444 being available to the public. But it's rather not really social, since you cannot participate in distributing the blockdata.

So if i would configure a second port ex. 8445, an introducer node would know, on my public ip the sync is available both on port 8444 and 8445?
