### ISSUE TITLE
Err.DOUBLE_SPEND full_node

### ISSUE THREAD

**Issue by datarte** [Chia-Network/chia-blockchain#3837]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Muffexx** [comment]
Hello @datarte

Check [this](https://github.com/Chia-Network/chia-blockchain/issues/3773#issuecomment-832559304) out.
Might not be an issue.

Regards
Muffex

**Comment by mariano54** [comment]
This is fine
