### ISSUE TITLE
WARNING  Wasn't able to add transaction with status 3 error: Err.DOUBLE_SPEND

### ISSUE THREAD

**Issue by datarte** [Chia-Network/chia-blockchain#3840]
I install 1.1.4 and start having this prolem

full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id status 3 error: Err.DOUBLE_SPEND
all the time

**Comment by Muffexx** [comment]
This bug has been reported more than three times.
Consider searching before creating new issues. 
AFAIK it has not been resolved by now.

**Comment by mumtazali2** [comment]
Well this is an issue. If it is not then why it is keep generating warnings and filling up the log confusing people?
