### ISSUE TITLE
[help] do i have to open port?

### ISSUE THREAD

**Issue by rangerov** [Chia-Network/chia-blockchain#3848]
I can not open port because i have dynamic IP rather than static. The program is open since 5 hours and it says Not Synced with red color. 
![ch1a](https://user-images.githubusercontent.com/45858496/117193359-69454800-adeb-11eb-86bf-00ffddf86143.png)

**Comment by MrRaven13** [comment]
I have the same problem from update release 1.1.2. I was hoping it would turn out fine at 1.1.3 and 4. But unfortunately that is not the case. I haven't changed anything in my port settings since 1.0.5.

**Comment by Gohsteu** [comment]
check your ports with Telnet command in CMD but nromaly should be fine got same issue after update have checked also my ports and done already a many plots

https://kb.acronis.com/content/7503

**Comment by Gohsteu** [comment]
Hope that they will fix fast this issue due to Difficulty is incrasing fast due to hype and China farmers

**Comment by rangerov** [comment]
> check your ports with Telnet command in CMD but nromaly should be fine got same issue after update have checked also my ports and done already a many plots
> 
> https://kb.acronis.com/content/7503

That actually solved my issue now it is syncing. Thank you, you are legend
