### ISSUE TITLE
[help] No Snyc but Connected after update to new Version

### ISSUE THREAD

**Issue by Gohsteu** [Chia-Network/chia-blockchain#3849]
**Describe the issue**
Status is on Not Synced in Full Node Status (Since 2h) , Farmers are wokring but Farming Status is not Available

**To Reproduce**
Update to new Version

**Expected behavior**
No Sync in "Full Node Status" and Farming Status is "not Available"

**Screenshots**
![image](https://user-images.githubusercontent.com/83727277/117195422-8b3bcc00-ade5-11eb-9d4a-0a46deb7924c.png)
![image](https://user-images.githubusercontent.com/83727277/117195480-9abb1500-ade5-11eb-809d-d67bbc944f70.png)

**Additional context**
Any once facing the same after the Update?

**Comment by Yabankazi** [comment]
I had the same issue after Manuel connecting to 

node-eu.chia.net

was the connection immediately possible? but I have only one connection now.
I still don t know is that good or bad.
but it seems that its works. I cant see many peers connected.

**Comment by rangerov** [comment]
open cmd and type telnet node-eu.chia.net 8444 
if you don't have telnet enabled you can enable it by searching telnet on windows search bar
that solved my issue

**Comment by HectorChow** [comment]
problem solved?

**Comment by Gohsteu** [comment]
No i changed back to the version beofre this new upate is nor working.

Workarround is go back to old Version

**Comment by rangerov** [comment]
> open cmd and type telnet node-eu.chia.net 8444
> if you don't have telnet enabled you can enable it by searching telnet on windows search bar
> that solved my issue

This doesn't work anymore, i can't connect using telnet. i don't know what happened
