### ISSUE TITLE
[BUG] Plotting process does not check for sufficient disk space prior to plotting

### ISSUE THREAD

**Issue by Nielsbishere** [Chia-Network/chia-blockchain#3852]
**Describe the bug**
Chia plotting can destroy existing functionality of OS by not validating remaining disk space and writing until 0 bytes are left.
If it has no space left it won't clean up either, resulting in weird issues in hiveos after reboot or while running (it was my problem because I didn't resize the folder after resizing the partition, but can be an issue for people low on space).

**To Reproduce**
Install something with a small partition, not big enough to fit the plots, or just have a small disk almost out of space.

**Expected behavior**
Chia should do a quick check to see if the disk has enough space for plotting.

**Screenshots**
N.A.

**Desktop (please complete the following information):**

- OS:  5.4.0-hiveos
- CPU: N.A.

**Additional context**
N.A.

**Comment by fullet-tortuga** [comment]
Agree. Since the file size is know, the program must preallocate the needed space. Otherwise all kind of malfunctions are guaranteed.

**Comment by Nielsbishere** [comment]
Still present afaik

**Comment by smasharov** [comment]
1.2.3 the same issue, what is the point of retrying in 5 minutes if the plot is already ruined?

Final File size: 101.412 GiB
Total time = 53492.182 seconds. CPU (123.070%) Wed Jul 28 05:33:13 2021
Could not copy "t:\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot.2.tmp" to "\\\\t1\\plots\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot.2.tmp". Error There is not enough space on the disk.. Retrying in five minutes.
Copied final file from "t:\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot.2.tmp" to "\\\\t1\\plots\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot.2.tmp"
Copy time = 1366.729 seconds. CPU (1.950%) Wed Jul 28 05:56:00 2021
Removed temp2 file "t:\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot.2.tmp"? 1
Could not rename "t:\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot.2.tmp" to "\\\\t1\\plots\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot". Error The system cannot find the file specified.. Retrying in five minutes.
Could not rename "t:\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot.2.tmp" to "\\\\t1\\plots\\plot-k32-2021-07-27-14-41-5b116650cb9df08f5c9b9192b6681ad01dabd5fc21238b9c0a97d1f065c850fc.plot". Error The system cannot find the file specified.. Retrying in five minutes.
