### ISSUE TITLE
[BUG] XCH Block Rewards lost from wallet

### ISSUE THREAD

**Issue by danrol** [Chia-Network/chia-blockchain#3859]
I had problems with sync. Tried to restart. Program was stuck on connection to wallet. Removed db as advised in FAQ. Chia loaded but my XCH coins (2 coins out of 2) are missing. 
Help please.

Windows 10 pro

Chia 1.1.3

**Comment by Muffexx** [comment]
Hello danrol,

the coins should show up if the block that contained the transaction is re-synced.
You could try checking your wallet address in the [chia explorer](https://www.chiaexplorer.com/blockchain/search) to ensure that they are still there.

regards
Muffexx

**Comment by danrol** [comment]
Thank you very much! It is still there
