### ISSUE TITLE
Queued plot jobs start immediately

### ISSUE THREAD

**Issue by Puppington** [Chia-Network/chia-blockchain#3862]
**Describe the bug**
After update to 1.1.4 when adding to queue, jobs start immediately and do not queue up behind jobs with same unique queue name that are currently running.

**To Reproduce**
1. Update from 1.1.3 to 1.1.4.
2. Create plot job with queue name "Q1".
3. Allow to start, but not complete.
4. Create new plot job with 3 plot count and same queue name "Q1"
5. Start new job.

**Expected behavior**
When adding a queued job with same unique queue name as a job already running I expect the newest job to wait until completion of the original job.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- OS 10
- CPU: Intel i9-11900F

**Additional Context**
Using Chia Wallet application

**Comment by ivaneftimov** [comment]
More specific example:

1. Add 4 plots in parallel to "Q1"
2. Add another 4 plots to the "Q1"
3. Only one plot of the new batch starts  ... 3 are still in the queue

If I repeat the same with one plot in step 1 and 2 above, there is no issue.
