### ISSUE TITLE
[help]我有一个同步的问题

### ISSUE THREAD

**Issue by jiangyouwang6** [Chia-Network/chia-blockchain#3863]
我有一个服务器，是无限流量，我想为更多的peer服务，提供高度文件，应该如何设置？

**Comment by threebowrice** [comment]
whow your ip and full node port

**Comment by chijinchao** [comment]
我也有一个自用的部署在公网，需要可以自取
141.164.58.204:8444

**Comment by zengyunsi** [comment]
![123](https://user-images.githubusercontent.com/79102897/117365296-ac89de80-aef1-11eb-9bc0-87cb566444e4.gif)
thank you

**Comment by jiangyouwang6** [comment]
> ![123](https://user-images.githubusercontent.com/79102897/117365296-ac89de80-aef1-11eb-9bc0-87cb566444e4.gif)
> 谢谢你

我并不存在同步困难的问题，我只是想帮助其他人

**Comment by jiangyouwang6** [comment]
> 显示您的IP和完整节点端口

已经开放了8444端口，但似乎最多只能有40个设备连接
