### ISSUE TITLE
Version number doesn't show up in About window (Ubuntu, 1.1.something)

### ISSUE THREAD

**Issue by cbc-uk** [Chia-Network/chia-blockchain#3866]
Running under Ubuntu, v1.1.2 (or possibly 1.1.3. I can't tell if I successfully upgraded or not), it just shows the version number as 0.0

![Screenshot from 2021-05-05 23-29-02](https://user-images.githubusercontent.com/26034547/117218493-2a1ef300-adfb-11eb-95ea-79a568831f45.png)

**Comment by rdprosser** [comment]
I have same thing on Ubuntu (but not on windows) I just did upgrade and still did not change from showing 0.0

**Comment by sargonas** [comment]
This is a known issue resulting from certain linux install paths (I believe namely if you install from source via git or if you use the "experimental" GUI installer) You can check your version on the CLI in the interim until it is addressed, using the command `chia version`.
