### ISSUE TITLE
Plotting stuck at final step

### ISSUE THREAD

**Issue by dragon0087** [Chia-Network/chia-blockchain#3867]
I was running plotting from chia.exe CLI in Windows. Every once in a while the plotting got stuck in the final step which is renaming the file to .plot in the final destination. I can see the output shows "total time for phase 4", and I see the tmp files in both the temp folder and destination folder. But it just stopped at that for more than 1 hour. I ended up killing the process and manually rename the file in the final destination. After that my farmer picks up the plot and everything seems to be fine. Looks like the rename step for some reason can't be executed. I also see people saying plotting from GUI stuck at 100%, I think that is the same issue.

**Comment by GiverDead** [comment]
Do you check user on final file, maybe chia move file with wrong permissions? my guess its wrong directory or file owner

**Comment by dragon0087** [comment]
> Do you check user on final file, maybe chia move file with wrong permissions? my guess its wrong directory or file owner

Pretty sure it's not a permission issue since the same source/destination only fails intermittently. All process are run with the same user who created the folders in Windows

**Comment by chenwei791129** [comment]
i have same issue, stuck "Plotting" status, and i check log seems ok
```
	Bucket 125 uniform sort. Ram: 4.823GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 126 uniform sort. Ram: 4.823GiB, u_sort min: 1.125GiB, qs min: 0.282GiB.
	Bucket 127 QS. Ram: 4.823GiB, u_sort min: 1.125GiB, qs min: 0.281GiB. force_qs: 1
	Finished writing C1 and C3 tables
	Writing C2 table
	Finished writing C2 table
	Final table pointers:
	P1: 0x10c
	P2: 0x3748cd200
	P3: 0x6b6153827
	P4: 0x9fe09c299
	P5: 0xd5647c99e
	P6: 0x10da758203
	P7: 0x14ebc8df97
	C1: 0x190c7ee397
	C2: 0x190c991f03
	C3: 0x190c991fb3
Time for phase 4 = 474.637 seconds. CPU (76.640%) Fri May  7 09:58:32 2021
Approximate working space used (without final file): 269.421 GiB
Final File size: 101.398 GiB
Total time = 22711.268 seconds. CPU (114.370%) Fri May  7 09:58:32 2021
```

**Comment by vannhazy** [comment]
Same issue here. I had 5 Powershell-Windows running at a time on my Win10 machine, 2 of them were supposed to write the plot to HHD e: - and both are stuck for hours. The other 3 prozesses wrote the plot-file to HDD f: and g: without a problem.

I guess I have to terminate?

**Comment by dragon0087** [comment]
> Same issue here. I had 5 Powershell-Windows running at a time on my Win10 machine, 2 of them were supposed to write the plot to HHD e: - and both are stuck for hours. The other 3 prozesses wrote the plot-file to HDD f: and g: without a problem.
> 
> I guess I have to terminate?

yeah, as long as you see the tmp file in your final destination(make sure it's the same size as the one in tmp folder, or do a md5 checksum to be sure) it's okay to kill the process and just rename it to .plot
Don't forget to delete the tmp file in your tmp folder

**Comment by chenwei791129** [comment]
> > Same issue here. I had 5 Powershell-Windows running at a time on my Win10 machine, 2 of them were supposed to write the plot to HHD e: - and both are stuck for hours. The other 3 prozesses wrote the plot-file to HDD f: and g: without a problem.
> > I guess I have to terminate?
> 
> yeah, as long as you see the tmp file in your final destination(make sure it's the same size as the one in tmp folder, or do a md5 checksum to be sure) it's okay to kill the process and just rename it to .plot
> Don't forget to delete the tmp file in your tmp folder

oh, i delete it....haha.
thank for your info, i will rename it at next time
