### ISSUE TITLE
[BUG] Node stops to sync

### ISSUE THREAD

**Issue by philiplin2345** [Chia-Network/chia-blockchain#3868]
**Describe the bug**
Cannot Sync. The program got stuck 10 hours ago and wouldn't resume

**To Reproduce**

Not sure how to reproduce, but I think I got disconnected to my network once

**Expected behavior**
Syncing should continue

**Screenshots**
![image](https://user-images.githubusercontent.com/38632265/117221543-0d56df80-ae3c-11eb-94f3-e9cb3879c266.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Windows 10
- CPU: 3900X Ryzen

**Additional context**

I am running the 1.1.4 version of the app

**Comment by HectorChow** [comment]
suddenly failed to sync node, I don't know what is going on

**Comment by Deses** [comment]
I can't sync either.

**Comment by capsule9123** [comment]
syncing fine in 1.1.2 - Had to restart, updated to 1.1.3, stuck syncing, updated to 1.1.4, stuck syncing still, its been over 24 hours

**Comment by OdinSun35** [comment]
I cant sync. More than 24 hour. Problem start after change internet IP. I think. My provider shotdown internet then, return connect , and that all 60 hour i cant sync.

**Comment by OdinSun35** [comment]
How change or open or tornon 8444 in windows or router? it need to do?

**Comment by DefiantMiner** [comment]
Same issue - won't connect to nodes >12hrs. after upgrading to 1.1.4 and 1.1.5.   I manually entered a node I know I can connect to and it remains the only one that connects.  He goes down, I go down.   This a a serious issue.

**Comment by macaryus** [comment]
Same issue, i think after provider reset connection every night. The problem is if you are plotting i can't restart chia client. I think is serious bug this.
