### ISSUE TITLE
[help] Failed at the chia-blockchain@ electron script.

### ISSUE THREAD

**Issue by ZIODIOZIO** [Chia-Network/chia-blockchain#3870]
Hello i am installing it on my ubuntu server. 
I am getting this error after running
'npm run electron &'

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'preelectron', 'electron', 'postelectron' ]
5 info lifecycle chia-blockchain@~preelectron: chia-blockchain@
6 info lifecycle chia-blockchain@~electron: chia-blockchain@
7 verbose lifecycle chia-blockchain@~electron: unsafe-perm in lifecycle true
8 verbose lifecycle chia-blockchain@~electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/chia-blockchain/chia-blockchain-gui/node_modules/.bin:/root/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chia-blockchain@~electron: CWD: /root/chia-blockchain/chia-blockchain-gui
10 silly lifecycle chia-blockchain@~electron: Args: [ '-c', 'electron .' ]
11 info lifecycle chia-blockchain@~electron: Failed to exec electron script
12 verbose stack Error: chia-blockchain@ electron: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1048:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13 verbose pkgid chia-blockchain@
14 verbose cwd /root/chia-blockchain/chia-blockchain-gui
15 verbose Linux 4.15.0-22-generic
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron"
17 verbose node v14.16.1
18 verbose npm  v6.14.12
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error chia-blockchain@ electron: `electron .`
23 error spawn ENOENT
24 error Failed at the chia-blockchain@ electron script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by ArhonTs** [comment]
+1
