### ISSUE TITLE
My receiving adress cannot be found on explorer[BUG]

### ISSUE THREAD

**Issue by GBourb** [Chia-Network/chia-blockchain#3871]
Receiving adress :

xch12k5nxj0w8845cdnmph74c9n7yam6qjrgj0u38secayh45lma3eps9xtlde

**Comment by Leozolt** [comment]
The address will only exist in the blockchain after a transaction occurred.

**Comment by GBourb** [comment]
I did receive 60 chia since the start of mainnet. did some transactions tuesday.

**Comment by Leozolt** [comment]
Did you receive the chia on that exact address or did you transact to that exact address or is that only a newly created receive address?
