### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by AmirBesharati** [Chia-Network/chia-blockchain#3872]
we have issue with plotting progress.
but today when we start plotting , the progress shows 1% but tmp hard drive is being filled over time in half hour we have over

![WhatsApp Image 2021-05-06 at 05 06 44](https://user-images.githubusercontent.com/32610410/117226561-26569500-ae2a-11eb-9fe6-d6753dd25dc6.jpeg)

![WhatsApp Image 2021-05-06 at 05 06 23](https://user-images.githubusercontent.com/32610410/117226522-12ab2e80-ae2a-11eb-8325-b9c27e5f1a2e.jpeg)

 21gb of data on our NVME but data log shows nothing and stucks in computing table 1 
is there an issue ? we have two external NVME and 10hdd runnig on hp proliant dl380e g8 32g ram

**Comment by Deses** [comment]
Come on, make a better title for this issue.
