### ISSUE TITLE
harvester harvester_server        : ERROR  

### ISSUE THREAD

**Issue by drch90** [Chia-Network/chia-blockchain#3878]
harvester harvester_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-05-06T09:55:49.275 timelord chia.timelord.timelord   : ERROR    Not active for 60 seconds, restarting all chains

**Comment by akinLiu** [comment]
I have the same error any one can help?

**Comment by tangdasan** [comment]
+1

**Comment by happy1989525** [comment]
I have same issue here, don't know how to fix it.

**Comment by lacostya86** [comment]
+1
Is this error is worth solving or we can just ignore? By the way, I see this error in log since I have started farming first plot and my node is still syncing (about 2 days).
Debian 10 (server, no gui)
chia 1.1.7.dev0
