### ISSUE TITLE
[help] [NVME] Error 1. Retrying in five minutes

### ISSUE THREAD

**Issue by Chiqui1234** [Chia-Network/chia-blockchain#3881]
**Describe the issue**
When phase 2/4 at table three or so, Chia CLI throws this error
```bash
Only wrote 968474 of 1048570 bytes at offset 317716710 to "/falcon1/chia-tmp/plot-k32-2021-05-05-17-29-8409e4afa392ee01e019c080ff4eed5007cb1d619f4f3276e67224aecadb4ddc.plot.p2.t3.sort_bucket_009.tmp"with length 318685184. Error 1. Retrying in five minutes.
```

When running *sudo dmesg*, the last message was:

```bash
may 05 19:06:50 PC-PINNACLE1 kernel: perf: interrupt took too long (2507 > 2500), lowering kernel.perf_event_max_sample_rate to 7975
```

Note: this kernel message was 2 hours ago before Chia's error 1.

**To Reproduce**
```bash
cd /route/to/your/chiaCLI
. ./activate
chia plots create -k 32 -b 3390 -u 128 -r 2 -t /ruta/temporal -d /ruta/final -n 1 -f yourFarmerKey -p yourPoolKey
```

Indeed, this error happen with my laptop (i7 10750H + Intel 660P as tmp drive + Chia GUI) and my PC (Ryzen 5 1600 + Adata Falcon 512GB as tmp drive + Chia CLI). This post is created with Ryzen 5 as example.
The error is the same: **Error 1** and "trying in five minutes".

This is really anoying because my new NVME has 4TB written but didn't finish any plot because of this. I don't have a clue why NVME refuses plotting... 

**Expected behavior**
Finished plotting process without errors.

**Additional context**

**Comment by Chiqui1234** [comment]
lol, that nvme is my plotting disk (for store temp files) and doesn't have space available. WHY? K32 occupies only 239GiB... or that says the Chia official documentation.

**Comment by viiiduarte** [comment]
Damn, I bought an Adata Swordfish of 1TB for the same purpose and I am encountering the same error.

**Comment by Chiqui1234** [comment]
> 
> 
> I'm having this same issue. NVME drive is not the issue as I've used the same drive on multiple other machines w/out issue. Drive is freshly formatted too when I run into this issue. Launching the plot from the GUI. @Chiqui1234 were you ever able to get this resolved?

Hi. Yes, I delete the files in the temp folder. Because first plot fails, the temp files still there and Chia "can't write" without available space hehe.
Deleting those files solves the problem for me. Then, start over with a new plot.

Also check NVME temperatures, safe range are 40~50c.

Good luck!
