### ISSUE TITLE
农田显示未找到农田是为什么

### ISSUE THREAD

**Issue by For-LD** [Chia-Network/chia-blockchain#3885]
农田里P完了 但是显示未找到农田
显示注意，删除这些农田的操作是永久的。请检查存储设备连接正常。

**Comment by Khunmatthew** [comment]
Failed to open (invalid plots)

i have same problem?

even i restart the application

**Comment by chijinchao** [comment]
提供的信息根本不足以让开发人员定位问题，除非你能肯定这是一个bug并给出复现条件，否则这样提交issue毫无意义，建议首先尝试通过论坛和讨论群寻找答案

**Comment by Khunmatthew** [comment]
> 提供的信息根本不足以让开发人员定位问题，除非你能肯定这是一个bug并给出复现条件，否则这样提交issue毫无意义，建议首先尝试通过论坛和讨论群寻找答案

感谢解答。

My situation:

i have ploted for 6 plot then i upgraded to 1.1.4 from 1.1.3

the plot shows available even i restart the application.

**Comment by SourFJ** [comment]
> > 提供的信息根本不足以让开发人员定位问题，除非你能肯定这是一个bug并给出复现条件，否则这样提交issue毫无意义，建议首先尝试通过论坛和讨论群寻找答案
> 
> 感谢解答。
> 
> My situation:
> 
> i have ploted for 6 plot then i upgraded to 1.1.4 from 1.1.3
> 
> the plot shows inavailable even i restart the application.

I ran into the same problem, did you solve it?

**Comment by SourFJ** [comment]
> 农田里P完了 但是显示未找到农田
> 显示注意，删除这些农田的操作是永久的。请检查存储设备连接正常。

请问你怎么解决啊
