### ISSUE TITLE
Clean install of 1.1.4 does not allow entering of keys via GUI

### ISSUE THREAD

**Issue by chiabug** [Chia-Network/chia-blockchain#3891]
**Describe the bug**
1.1.4 clean install to Windows presents gui but never proceeds to allow the entering of keys

**To Reproduce**
Fresh install of 1.1.4 to clean Windows 10 or Windows 7
No internet connection to machine
After install the GUI will be stuck trying to connect.
It never allow the entering of keys.
The logs show cannot connect to dameon

**Expected behavior**
Gui should be presented and keys should be enterable without a need for any other connections

**Desktop (please complete the following information):**
OS Win 10 and Win 7

**Comment by guillaumeeeeeeee** [comment]
Hello, since the 1.1.4 update, I can't access my wallet, it's stuck on 'while connecting to the wallet' ad infinitum I tried to launch chia with 1.1. 3 is the same, how to uninstall chia completely?

**Comment by oliman** [comment]
Same problem here

**Comment by guillaumeeeeeeee** [comment]
I have reset windows and change IP and re install chia 1.1.4 same beug....

**Comment by oliman** [comment]
Well I have a crappy fix, try at your own risk.
I deleted my entire chia blockchain folder... the  .chia/mainnet one.
I was then able to log-in to the chia program but now I'm SLOWLY re-syncing the entire blockchain... 6976 and counting
