### ISSUE TITLE
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/gomez/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar/build/renderer/js/80.js.map: Unexpected end of JSON input

### ISSUE THREAD

**Issue by carlitosg93** [Chia-Network/chia-blockchain#3894]
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/gomez/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar/build/renderer/js/80.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/gomez/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

**Comment by cdnkrypto** [comment]
Same error I get with looped connecting to wallet

**Comment by cdnkrypto** [comment]
So the fix for me was to delete the .chia folder and a clean install

**Comment by carlitosg93** [comment]
hello what do you mean with clean installation?
