### ISSUE TITLE
[BUG] Chia plots are created with a different Public Key - Major Bug

### ISSUE THREAD

**Issue by SS20201978** [Chia-Network/chia-blockchain#3897]
**Describe the bug**
When plots are created, the Farmer public key is not matching with that of the Chia Public Key

**To Reproduce**
When I run the command, chia plots check -n 100
The following data are available against each plot:
Pool public key: 
Farmer public key:
Local sk: <PrivateKey ....>
Pool public key:  & Farmer public key: are same in all plots
Local sk: <PrivateKey ....> are uniques in each plot 

I have used following for creating plots:
chia plots create -k 32 -b 4000 -t /path/to/temporary/directory -d /path/to/final/directory
Also I had created plots using GUI

**Desktop (please complete the following information):**
OS: Windows 10
Chia 1.1.14 and earlier versions as well

**Additional context**
Everybody should check their plots

**Comment by casalebrunet** [comment]
you should use the -a option in order to specify which key you have to use

**Comment by steven-b89** [comment]
Hi!

Have a question about this one, used the exact same command as you to create my plots.
When I run chia plots check -n 30 and chia keys show my pool public key and farmer public key are matching, so I guess I do not have this issue?

**Comment by SS20201978** [comment]
> 
> 
> you should use the -a option in order to specify which key you have to use

However when plots are created from Windows GUI, from it should pick automatically. and i have only 1 wallet? So from where Chia plot is picking the wrong public key?
