### ISSUE TITLE
[help] Transaction Pending

### ISSUE THREAD

**Issue by grandblade8407** [Chia-Network/chia-blockchain#3900]
I tried to send 1 xch to exchange wallet from the windows aplication.
In the wallets tap, i pasted the exchange wallet address in the adress bar under "create transaction". I entered the amount - 1 and clicked send.
my spendable balance has droped by more than 1 - total bance shows 2xch. spendable balace 0.25 xch.
In history - outgoing still shows pending 12hrs later.

![balance](https://user-images.githubusercontent.com/83728571/117251182-37a89d00-ae3c-11eb-9f85-f54f4ca12983.JPG)
![pending](https://user-images.githubusercontent.com/83728571/117251207-3e371480-ae3c-11eb-9a39-d36187d840e1.JPG)
![exchange wallet](https://user-images.githubusercontent.com/83728571/117251437-953ce980-ae3c-11eb-83cc-1bbc8140b629.JPG)

**Comment by mariano54** [comment]
Are you on version 1.1.4? Have you tried restarting the application?

**Comment by grandblade8407** [comment]
Hi. Thanks for the prompt reply. It is currently on 1.1.3. I have restarted
both the application and the pc multiple times. No luck.

**Comment by mariano54** [comment]
Can you send me a message on keybase? My username is sorgente711
