### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Camelito67** [Chia-Network/chia-blockchain#3907]
**Describe the bug**
When I try to open the "Chia Blockchain" program, it just appear to me that it is connecting to wallet and I left the program loading a couple of hours but it doesn't open.

**To Reproduce**

1. Go to 'The program file'
2. Click on 'Open'
3. Scroll down to 'Wait until it appears the program window'

**Expected behavior**
I expected to let it load 1 min maximum or a normal time in any application to start, and just open and see the home screen of the program.

**Screenshots**
![image](https://user-images.githubusercontent.com/83752485/117259056-4fb7f680-ae13-11eb-8c8e-600b846628d2.png)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: Intel(R) Core(TM) i5-3320M

**Additional context**
It is rare to me because before this issue appear, I used the application as expected but when I closed it and tried to re-lauch it, it just stayed in there loading, and I already unistall the program and install it again but this isue still happening.

**Comment by guillaumeeeeeeee** [comment]
same problem for me :(

**Comment by migelrestrepo** [comment]
same problem for me in Mac Big Sur

**Comment by migelrestrepo** [comment]
It worked for me on mac. I did the following.
Run the following command in terminal to show hidden files
defaults write com.apple.Finder AppleShowAllFiles -bool YES
Then this command
killall Finder
Then I have gone to the path User /.chia/mainnet/Wallet/db and I have eliminated the largest file. 
With that it has worked for me again.
