### ISSUE TITLE
[BUG]  Estimated network space: different values

### ISSUE THREAD

**Issue by casalebrunet** [Chia-Network/chia-blockchain#3908]
**Describe the bug**
I see two different network estimation size values, depending on the command I'm running.

**To Reproduce**

`chia farm summary`
-> Estimated network space: 2484.549 PiB

`chia show -s`
-> Estimated network space: 2.427 EiB

**Expected behavior**
If the two values are different, the definition is misleading.
If they represent the same thing, then the ambiguity must be resolved.  

**Setup**

- OS: Ubuntu 20.04
- Git commit:  a56796c5878efdf14db7c2b426800e4a1113d741 (i.e., release 1.1.3)

**Comment by night-lurker** [comment]
The word “estimated” kind of say it all, plots jump on and off all the time
We would be spammed with info it it should be live updated every second

**Comment by casalebrunet** [comment]
I see your point and totally agree. But are these two pieces of information the same thing? If yes IMHO they shall be represented in the same way.

**Comment by grinbucks** [comment]
Both value are the same. One is in Pebibyte and the other one is in Exbibyte.
Divide the 2484.549 PiB by 1024 and you'll get 2.427 EiB

**Comment by casalebrunet** [comment]
That's clear :) My point is the representation IMHO should be the same: or both in Exbibyte or both in Pebibyte.
