### ISSUE TITLE
[help] . ./activate does not exist

### ISSUE THREAD

**Issue by altered-beast** [Chia-Network/chia-blockchain#3909]
**Describe the issue**
when installing chia from cli i get the error ``-bash: ./activate: No such file or directory

**To Reproduce**
follow the install instructions for ubuntu 20.04

**Expected behavior**
i expect for . ./activate to put me into a venv and allow me to run chia commands

**Additional context**
tested on a another similar machine with same results

**Comment by TimFoerster** [comment]
Are you in the correct folder and have the correct git branch?

what does `ls` gives you?

**Comment by altered-beast** [comment]
i  am in the correct folder and ls gives this 

`azure-pipelines.yml  BUILD_TIMELORD.md  chia                 CODE_OF_CONDUCT.md  install-gui.sh  install.sh           LICENSE     mypy.ini        README.md        setup.py
build_scripts        CHANGELOG.md       chia-blockchain-gui  CONTRIBUTING.md     INSTALL.md      install-timelord.sh  mozilla-ca  pyproject.toml  run-py-tests.sh  tests`

**Comment by TimFoerster** [comment]
did u run `sh install.sh` before?

**Comment by altered-beast** [comment]
yes and it finished with no errors
