### ISSUE TITLE
[help] Telnet doesn't work after a while

### ISSUE THREAD

**Issue by rangerov** [Chia-Network/chia-blockchain#3910]
I was using telnet to get synced and after i restart my pc it is not working right now. Anyone having same issue?

Connecting To node-eu.chia.net...Could not open connection to the host, on port 8444: Connect failed
Connecting To node.chia.net...Could not open connection to the host, on port 8444: Connect failed

Did:
Restart
Removing telnet and reinstalling
Created inbound/outbound 8444 ports tcp/udp
Tried to ping chia server, 0 response

**Comment by Leozolt** [comment]
A lot of poeple get this issue but it has nothing to do with chia.

Try:
traceroute or tracert  "node hostname or ip" -T -p 8444

and

traceroute or tracert  "node hostname or ip" -p 8444

and

traceroute or tracert  "node hostname or ip"

**Comment by rangerov** [comment]
![image](https://user-images.githubusercontent.com/45858496/117446190-6447dc00-af44-11eb-8845-4b27184bec39.png)
it seems to be fixed after disabling upnp but i accidentally added north america server should i remove it though
