### ISSUE TITLE
[help] Unfinished ploting

### ISSUE THREAD

**Issue by doublelefthands** [Chia-Network/chia-blockchain#3912]
Hi, has anyone had a similar problem I left 3 plot for the night (when it probably fell current) now at the temp ssd are files (did not go to hdd) when turn on the program chia is already a place for one plot and those can not see whether it can somehow be restored or are these files to be thrown away? (In addition, I'm in the process of syncing if it matters) or manually flipping them to hdd will change something?

**Comment by doublelefthands** [comment]
Ok i found its cannot be recovered. Sorry please close topic.

""My computer/drive went into power save or rebooted while plotting?
Unfortunately, resuming a plot is not yet supported but likely will be later in 2021. We suggest that you disable power saving mode - especially for external drives - and try to limit other possible causes of interruptions. Plotting a k=32 is going to take between 6 and 20 hours, depending on your hardware, so these interruptions can be painful. They are also a part of why we don't recommend plotting plots larger than k=32 as each increment in k generally doubles the time to complete a single plot.""

**Comment by shobukle** [comment]
> 
> 
> Ok i found its cannot be recovered. Sorry please close topic.
> 

You are the author. Please close this issue.
