### ISSUE TITLE
When a queued task is executed, it runs immediately instead of checking whether the previous task with the same name has completed[BUG]

### ISSUE THREAD

**Issue by sansky33** [Chia-Network/chia-blockchain#3913]
I have a 1T SSD. First, I assign three concurrent tasks, with an interval of 15 minutes, and set the queue name to Q1. Later, I need to add more tasks into Q1, but every time I add a task, it will automatically run instead of checking whether the previous task has been completed, which affects the overall progress and leads to process failure. Can this be repaired? Because it affects the efficiency of p-chart very much

- OS: [Win10]
- CPU: [e.g. Intel Xeon E5-2696V2]

**Comment by Puppington** [comment]
Already raised as: Queued plot jobs start immediately #3862

**Comment by sansky33** [comment]
Already raised as: Queued plot jobs start immediately #3862
