### ISSUE TITLE
[help] chain start node fail

### ISSUE THREAD

**Issue by 1044740162** [Chia-Network/chia-blockchain#3914]
After I cloned the chain-blockchain, I tried to go to the venv/bin/ directory using the following command
./chia init
./chia keys generate
Then I changed the self_hostname in ~/.chia/config/config.yaml to 127.0.0.1

Then execute
./chia start node

I got this error

`Daemon not started yet
Starting daemon
chia_full_node: chia_full_node failed to start. Error: start failed`

log
`FileNotFoundError: [Errno 2] No such file or directory: 'chia_full_node': 'chia_full_node'`

**Comment by jmakov** [comment]
Since you've closed the ticket, can you share what the solution was?

**Comment by 1044740162** [comment]
> Since you've closed the ticket, can you share what the solution was?

I did not fully follow the official documentation. When I entered venv, I tried again and it succeeded. This error is caused by my mistake in operation. If you follow the documentation, you shouldn’t have this problem

**Comment by Horndev** [comment]
@1044740162 So, I am (I think) following the documentation, and I still get that error.  What exactly did you miss?
