### ISSUE TITLE
When "Syncing 4928/239508"，it always becomes "not synced"

### ISSUE THREAD

**Issue by morpheusblack** [Chia-Network/chia-blockchain#3916]
Hi,
When "Syncing 4928/239508"，it always becomes "not synced"

![Image 1](https://user-images.githubusercontent.com/83757269/117272826-7ac23a80-ae53-11eb-97cd-ca1162339195.jpg)
![Image 2](https://user-images.githubusercontent.com/83757269/117272837-7c8bfe00-ae53-11eb-94dd-49a26ddbc349.jpg)
![Image 3](https://user-images.githubusercontent.com/83757269/117272850-7e55c180-ae53-11eb-83ef-9f8674206ae9.jpg)

**Comment by Gohsteu** [comment]
Go back to old version. new version is buggy

**Comment by dedmazai1987** [comment]
Было так же. помогло удаления папки chia (в пользователях).

**Comment by HectorChow** [comment]
the windows gui is shit with bunches of bugs

**Comment by acknologia** [comment]
> Go back to old version. new version is buggy

which old version? 1.1.2 had the same problem for me
