### ISSUE TITLE
[BUG]同步问题

### ISSUE THREAD

**Issue by Autumnfruit-qq** [Chia-Network/chia-blockchain#3924]
![image](https://user-images.githubusercontent.com/60422868/117286846-4626a100-ae9c-11eb-9ac8-45aad9f2fb17.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Gohsteu** [comment]
i ask my slef why start in 同步问题  and continue in ENG

**Comment by Autumnfruit-qq** [comment]
![image](https://user-images.githubusercontent.com/60422868/117287367-d8c74000-ae9c-11eb-972e-c7466f8c237f.png)

**Comment by Autumnfruit-qq** [comment]
每次都不一样
