### ISSUE TITLE
Plotting stopped without any reason and error in log

### ISSUE THREAD

**Issue by GiverDead** [Chia-Network/chia-blockchain#3936]
I have 
Raspberry 4B 4GB x64
Ubuntu Desktop 21 x64 for rpi
1GB swap space

400 GB disk space available 160 used during plotting
Its second time today when plotting stopped on 11% Phase 1 Computing table 4, first on Bucket 9, now on Bucket 1.
Ubuntu is working, not freeze, System Monitor show 15% CPU usage and 1.1GB RAM usage, 672MB used.

Please help, i cant create plot a month)
i was bought new ssd drive for that.. 

where i can see error log or something like that ?

**Comment by chiabug** [comment]
For what it is worth...I had similar problems when using basic hardware and it is usually related to the amount of space available on the temp drives or the amount of memory actually being used.  I had to resort to command line plotting where you have better control over what is happening.  You need to keep the plotting ram specified with -b well below the amount of memory you have available when the machine is running -- not the amount of ram installed in the machine.  The temp space -t needs to be a minimum of 360GB in my experience.  When it is less hangs like this seem to occur.   Remember these are k32 plots which means the final plot needs over 100 gig in addition to whatever space is used during plotting.

**Comment by GiverDead** [comment]
> For what it is worth...I had similar problems when using basic hardware and it is usually related to the amount of space available on the temp drives or the amount of memory actually being used. I had to resort to command line plotting where you have better control over what is happening. You need to keep the plotting ram specified with -b well below the amount of memory you have available when the machine is running -- not the amount of ram installed in the machine. The temp space -t needs to be a minimum of 360GB in my experience. When it is less hangs like this seem to occur. Remember these are k32 plots which means the final plot needs over 100 gig in addition to whatever space is used during plotting.

Ty for answer, i keep 400GB of temp space available, and on Raspberry OS x64 without GUI start plotting with -b 3000, so 1GB was available for the system.

**Comment by sharyuke** [comment]
The same reason. Chia stop without any logs.

**Comment by GiverDead** [comment]
I was install windows on rpi
