### ISSUE TITLE
[BUG] Failed to open (invalid plots) after i force shut down gui and upgrade the gui

### ISSUE THREAD

**Issue by Khunmatthew** [Chia-Network/chia-blockchain#3937]
**Describe the bug**

my gui was forced shut down after meeting a problem of endless wallet connection, 
after upgading and restarting gui, the gui cannot recoginize my plots and shows as above, "Failed to open (invalid plots)"

i also open the hpool application. no idea if it results in the problems.

version is 1.1.3. now 1.1.4..

**Screenshots**
![image](https://user-images.githubusercontent.com/83352450/117299659-fb5c5780-aea2-11eb-8b2d-fea5cd35e13e.png)

**Desktop (please complete the following information):**

- OS: windows 
- OS Version/Flavor: windows 10
- CPU: e.g. Intel Xeon 2970v4

**Comment by CaptainNicodemus** [comment]
I have a similar issue on windows, but it looked like the plot was still farming?

![Capture](https://user-images.githubusercontent.com/22399685/117344857-83266f80-ae6b-11eb-94e6-398d8109cfe9.PNG)

restarted and upgraded to 1.1.3 from 1.1.4 and it cleared the list, I still had 2 on there that were being moved to a "farming" folder. ill come back and add anything if they start stacking up again

**Comment by tspimentel** [comment]
@Khunmatthew i had the same problem. After search for a solution on internet and lost any chance to recovery my files or resolve the problem i stoped and think..... And if i reboot my computer ?

I restarted my PC and the problema was resolved!

Try the same and tell me if the problem was resolved.

**Comment by elanguidogeo** [comment]
I have the same problem and it started to happen after upgrading from 1.1.3 to 1.1.4.

When I open the gui it shows some invalid plots. I close GUI, restart PC and it shows a different number of invalid plots, which may be higher or lower than the previous time. Hopefully after 3-4 reboots all plots are valid.

Something is definitely not right.

**Comment by Khunmatthew** [comment]
Reboot the pc, then the plot recover
