### ISSUE TITLE
[BUG]can not Sync

### ISSUE THREAD

**Issue by fanxue** [Chia-Network/chia-blockchain#3950]
My ISP does not provide a public IP, so even if port 8444 is opened on the router, it does not have much effect. Prior to version 1.1, synchronization was still possible, but since the upgrade to 1.1.0, synchronization has become very difficult. The 1.1.3 version has been slightly improved, but after upgrading to 1.1.4, it has become very bad.

**Comment by alekisminerador** [comment]
upgrading to 1.1.4 not syncing

**Comment by MtechBasics** [comment]
whenever we are not synced we dont farm right? why the hell you dont get this fixed? i am always on the go with the latest client but every day i get out of sync... its so boring

**Comment by fanxue** [comment]
If you have a public IP, then any version can be synchronized normally. But most ISPs cannot provide you with a public IP.

**Comment by sobertram** [comment]
Just wanted to add the blockchain synchs but the wallet doesnt.

**chia show -s**
Current Blockchain Status: Full Node Synced

Peak: Hash: 11d000a76406f90ebeaaa60a225bdb28d594977e7004c780cbd09d1fae1554e5
      Time: Thu May 06 2021 10:58:13 EDT                  Height:     240700

Estimated network space: 2.463 EiB
Current difficulty: 170
Current VDF sub_slot_iters: 110100480
Total iterations since the start of the blockchain: 779610279721

**chia wallet show**
Wallet height: 31838
Sync status: Not synced

I had installed new blockchain and noticed that my wallet does increment but after a while it stops.

**Comment by xxasj** [comment]
same with me- I had version 1.1.2 and it stoped sync  during ploting. Upgrade to 1.1.4 didn't help. I have Public static IP and enterprise level connection so that's not an issue here.

**Comment by MarcoLeti** [comment]
same problem for me version 1.1.2

**Comment by masoudmatrix** [comment]
same problem in 1.1.4 - not syncing

**Comment by Yabankazi** [comment]
I have the same problem... Ports are open. If I use manually connect to peers
node-eu.chia.net - 8444
node-or.chia.net - 8444
node-apne.chia.net - 8444
it starts sync but after a while, it stops and syncing. A wallet is connected.
**Your Full NOde Connection is Connected** Up / 0 Down 740.2
**Your Harvester Network Connected**  Up/ 541.3 Down 559.8
A firewall is Open for Chia 
Everything it seems OK. 
But why I can't Sync by starting Chia. Why it works manually for a while and ends ... ????

**Comment by cdub3d** [comment]
Gig fiber, with public IP. It drops sync for seemingly no reason at all. Telnet to node.chia.net 8444 works just fine, but the program itself won't connect to it. Eventually, after adding it manually a dozen or so times, it will connect and everything is peachy again for the next 18-24 hours or so until it does it again.  Version doesn't seem to matter.
It does this with or without plotting going on. No rhyme or reason, just stops syncing. (It really sucks when it is plotting though... however many hours into that job it is... it's just lost time. delete and start over.)

**Comment by hapablap** [comment]
Theoretical you should not need a static IP. It works peer-to-peer. So, if you connect to another peer, he esablish a connectio to you, too, as long as your port is open. You simply change your public IP address from time to time. But I'm not a chia developer, so I don't know how they implemented peer connection. I have the same issues with syncing and can't understand why this is such a huge problem at chia.

**Comment by masoudmatrix** [comment]
any help about 1.1.4 ?
still not syncing

**Comment by sobertram** [comment]
Use 1.1.3 that one is working fine wrt synchronization.

**Comment by DanielYWoo** [comment]
+1

**Comment by hbtpoprock** [comment]
+1

**Comment by Centny** [comment]
+1

**Comment by gaiyaa** [comment]
+1

**Comment by mrnguyenphuc** [comment]
Already work fine with old version 1.1.3. After 2 days update to 1.1.4 i get same issue. Status synced just few moment after that so many new block show Unfinished and it show STATUS NOT SYNCED. What problem happend with new version of chia?
Can anyone help for this?

**Comment by afontan** [comment]
+1

**Comment by jimicze** [comment]
Same here
after updating to 1.1.5 i basically lost the sync of node .. 
and wallet cant sync anyway

```
Wallet height: 1391
Sync status: Not synced
Balances, fingerprint: 2216819945
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable: 0.0 xch (0 mojo)
```

```
(venv) root@chia-1:~/chia-blockchain# tail -F ~/.chia/mainnet/log/debug.log
    raise ValueError("no active connection")
ValueError: no active connection

2021-05-09T22:58:34.603 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 1376-1408. Traceback (most recent call last):
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 509, in sync_job
    await self._sync()
  File "/root/chia-blockchain/chia/wallet/wallet_node.py", line 606, in _sync
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 1376-1408
```

```
(venv) root@chia-1:~/chia-blockchain# cat ~/.chia/mainnet/log/debug.log | grep -i 'error'
2021-05-09T22:33:15.084 wallet asyncio                    : ERROR    Unclosed client session
2021-05-09T22:33:17.451 wallet chia.rpc.wallet_rpc_api    : ERROR    error 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://backup.chia.net/download_backup')
2021-05-09T22:35:35.375 full_node asyncio                 : ERROR    Unclosed client session
2021-05-09T22:37:23.610 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
    raise ValueError("Start client failed, or server is not set")
ValueError: Start client failed, or server is not set
2021-05-09T22:37:50.998 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
2021-05-09T22:37:52.428 full_node asyncio                 : ERROR    Unclosed client session
2021-05-09T22:58:34.599 wallet chia.wallet.wallet_blockchain: ERROR    Error during db transaction: 
2021-05-09T22:58:34.602 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:no active connection Traceback (most recent call last):
asyncio.exceptions.CancelledError
    (result, error, fork_h,) = await self.wallet_state_manager.blockchain.receive_block(
    raise ValueError("no active connection")
ValueError: no active connection
2021-05-09T22:58:34.603 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 1376-1408. Traceback (most recent call last):
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 1376-1408

```

**Comment by torokunotame** [comment]
same problem for me version 1.1.5

**Comment by VitorGultzgoff** [comment]
+1

**Comment by spodee4** [comment]
+1. Are they going to fix this?  This is bogus. With huge investments from the community on hardware and you cannot sync you wallet. Crazy

**Comment by sobertram** [comment]
> > Just wanted to add the blockchain synchs but the wallet doesnt.
> > **chia show -s**
> > Current Blockchain Status: Full Node Synced
> > Peak: Hash: 11d000a76406f90ebeaaa60a225bdb28d594977e7004c780cbd09d1fae1554e5
> > Time: Thu May 06 2021 10:58:13 EDT Height: 240700
> > Estimated network space: 2.463 EiB
> > Current difficulty: 170
> > Current VDF sub_slot_iters: 110100480
> > Total iterations since the start of the blockchain: 779610279721
> > **chia wallet show**
> > Wallet height: 31838
> > Sync status: Not synced
> > I had installed new blockchain and noticed that my wallet does increment but after a while it stops.
> > **UPDATE:**
> > So I restart the wallet and it started updating again.
> > **chia wallet show**
> > Wallet height: 34557
> > Sync status: Not synced
> > After sometime it throws this error and then stops updating.
> > 2021-05-06T11:14:22.959 full_node full_node_server : ERROR Exception: <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
> > File "~/chia-blockchain/chia/server/server.py", line 531, in api_call
> > response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
> > File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
> > raise exceptions.TimeoutError()
> > asyncio.exceptions.TimeoutError
> > 2021-05-06T11:14:22.960 full_node full_node_server : WARNING Trying to ban localhost for 10, but will not ban
> > 2021-05-06T11:14:22.961 wallet chia.wallet.wallet_node : ERROR Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
> > File "~/chia-blockchain/chia/wallet/wallet_node.py", line 596, in _sync added, advanced_peak = await self.fetch_blocks_and_validate( File "~/chia-blockchain/chia/wallet/wallet_node.py", line 635, in fetch_blocks_and_validate
> > raise ValueError("Peer returned no response")
> > ValueError: Peer returned no response
> > 2021-05-06T11:14:22.962 wallet chia.wallet.wallet_node : ERROR Loop exception in sync Was not able to add blocks 34557-34589. Traceback (most recent call last):
> > File "~/chia-blockchain/chia/wallet/wallet_node.py", line 509, in sync_job await self._sync() File "~/chia-blockchain/chia/wallet/wallet_node.py", line 606, in _sync
> > raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
> > RuntimeError: Was not able to add blocks 34557-34589
> 
> if wallet is not synced and full node is synced and farming too , will it affect farming coins ?

I am not an expert but from what I see they are separate and you can farm without the wallet being synched. You just wont accurately see your balance in your wallet if you solve a challenge. 

So there is another bug entered for this error message:

**Comment by digibobdeluxe** [comment]
1.1.5 on Mac does not sync to blockchain at all - just a spinning wheel.

**Comment by homerts95** [comment]
i am facing the exact same problem although i did ebeng mentioned i get connection error check if wallet is running at 9256
then i did `chia wallet show` same not synced again

**Comment by nslsa661** [comment]
Just a follow-up.  I deleted my Chia folder, and syncing seems to be working reliably again.  It was a pain, as I had to re-add my hard drives and re-sync from 0 (which took nearly 24 hours) but so far so good.  Knock on wood.

**Comment by raptuspl** [comment]
1. Solution: (helped me)

Did you sync your timezone? - Yes? also on your Router Settings? - No? .. here you go. oh and Timezone+Location matter and have to be precise matched!

For my example i am living on GMT +1 (Warsaw, Sarajevo..) on my Router/+Repeater while my Windows 10 Settings Timezone was set on GMT +1 (Berlin, Wien etc.) .. the moment i set both on GMT +1 (Warsaw, Sarajevo..) it got synced again instantly.
(The Error is in the location timezone, they still differ, even on the same timezone)

Guys, the Timezones **AND** Cities matter. _They all have to be on the Same Timezone+Citylocations_ 

Log into your router/Repeater Settings and set em on the same location as your Windows (or other way around)
Yea i know, if you are living in a different timezone, just let em match. 
If you cant change the Settings on your router/repeater, try to switch it around in windows settings until it syncs.

Still deactivate "assign automatically timeszones" and if youre on Summertime settings, this can cause also errors in that. right now ive activated summertime

Thank me  later. lol

**Comment by fdf7771** [comment]
Thank you, that helped, it worked for me.

**Comment by spodee4** [comment]
A lot of really good suggestions on here. For me the only thing that fixed it was running version 1.1.3, all other version created this problem for me. I have multiple machines running so if this is your situation make sure you are disabling upnp on those extra machines, this makes a difference, you also need to set up those machines to run as harvesters and not full nodes. Also make SURE you are open on 8444 on your router. This will immediately make a difference. Also if you have other machines on your network, connect to them, this helps syncing as well. Good luck.

**Comment by SavageStyle** [comment]
```
2021-05-18T19:54:21.852 full_node full_node_server        : WARNING  Banning 73.125.114.248 for 600 seconds

2021-05-18T19:54:30.094 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync

RuntimeError: Weight proof did not arrive in time from peer: 73.125.114.248
```

Not Synced.
Log flooded with those errors, anything to fix this?

**Comment by miguelfsm** [comment]
Setting the correct time worked for me.

**Comment by Yuvix25** [comment]
Okay so I had this issue as well, and I had to change the time manually every time, but it happened a lot so here is a simple python script for windows which fixes this:
```python
import datetime
import win32api
import os
import time

MONTH_TO_NUM = {
    "Jan" : 1,
    "Feb" : 2,
    "Mar" : 3,
    "Apr" : 4,
    "May" : 5,
    "Jun" : 6,
    "Jul" : 7,
    "Aug" : 8,
    "Sep" : 9,
    "Oct" : 10,
    "Nov" : 11,
    "Dec" : 12,
}

DAY_TO_NUM = {
    "Sun" : 1,
    "Mon" : 2,
    "Tue" : 3,
    "Wed" : 4,
    "Thu" : 5,
    "Fri" : 6,
    "Sat" : 7,
}


timezone_offset = time.timezone if (time.localtime().tm_isdst == 0) else time.altzone
timezone_offset //= 60 * 60 * -1
last_time = ()

while True:
    output = os.popen('chia show -s').read()
    if "Current Blockchain Status: Full Node Synced" not in output:
        output = output[output.find("Time:")+6:output.find("\n", output.find("Time:")+6)].split()
        year = int(output[3])
        month = MONTH_TO_NUM[output[1]]
        day_of_week = DAY_TO_NUM[output[0]]
        day = int(output[2])
        hour = int(output[4].split(":")[0]) - timezone_offset
        minute = int(output[4].split(":")[1])
        second = int(output[4].split(":")[2])
        milliseconds = 0

        time_tuple = (year, month, day_of_week, day, hour, minute, second, milliseconds)
        print(time_tuple)
        # pywin32.SetSystemTime(year, month , dayOfWeek , day , hour , minute , second , millseconds )
        if last_time != time_tuple:
            win32api.SetSystemTime(*time_tuple)

        last_time = time_tuple
    else:
        print("already synced")

    time.sleep(20)
```

**Comment by VanQz** [comment]
Anyone has any solutions for my issue my error is as follows:
```
2021-05-19T16:01:50.712 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 305065, None. Traceback (most recent call last):
2021-05-19T16:01:50.713 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 305065 <class 'ValueError'>, closing connection None. Traceback (most recent call last):
2021-05-19T16:02:09.551 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 305065 <class 'ValueError'>, closing connection {'host': 'xxxxxxxx', 'port': 8444}. Traceback (most recent call last):
2021-05-19T16:02:09.554 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 305065, {'host': 'xxxxxxxx', 'port': 8444}. Traceback (most recent call last):
```

**Comment by bleehome** [comment]
same issue with 1.1.6, wallet not Not synced. but full node is synced.
2021-06-02T16:54:27.144 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 90020-90052. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 515, in sync_job
  File "chia\wallet\wallet_node.py", line 614, in _sync
RuntimeError: Was not able to add blocks 90020-90052

**Comment by Gigko** [comment]
2021-10-30T14:37:40.644 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Was not able to obtain solution {'coin_name': '0xf2381f7e787884542c3191dbc53d28b3fcd53c5ac4483df03164e809b96e5c4b', 'height': 1028139} Traceback (most recent call last):

and

2021-10-30T14:37:26.162 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 1028137-1028169. Traceback (most recent call last):

**Comment by codephunk** [comment]
I also suddenly found this ERROR in my logs. Wallet stopped syncing. I'm on a Raspberry Pi 4 running Raspbian. I didn't change anything in the config or in the OS. Just added new plots from time to time.

```
wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "/home/pi/chia-blockchain/chia/wallet/wallet_node.py", line 563, in batch_sync_to_peak
    added, advanced_peak = await self.fetch_blocks_and_validate(
  File "/home/pi/chia-blockchain/chia/wallet/wallet_node.py", line 695, in fetch_blocks_and_validate
    raise ValueError("Peer returned no response")
ValueError: Peer returned no response

2022-01-27T13:42:10.512 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 885140-885172. Traceback (most recent call last):
  File "/home/pi/chia-blockchain/chia/wallet/wallet_node.py", line 616, in sync_job
    await self._sync()
  File "/home/pi/chia-blockchain/chia/wallet/wallet_node.py", line 676, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/pi/chia-blockchain/chia/wallet/wallet_node.py", line 573, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 885140-885172
```

**Comment by codephunk** [comment]
UPDATE: After stopping the service, killing ghost processes and restarting it seems to work again now. Took some time to start syncing again though.
