### ISSUE TITLE
[BUG] Plotting on Raspberry Pi 4 

### ISSUE THREAD

**Issue by raceface1** [Chia-Network/chia-blockchain#3951]
Plotting on Raspberry Pi 4 fails every time after few hours, looks like plotting process gets killed 

Raspberry Pi 4 - 4GB version

Starting phase 2/4: Backpropagation into tmp files... Thu May  6 08:36:22 2021
Backpropagating on table 7
scanned table 7
scanned time =  596.860 seconds. CPU (29.230%) Thu May  6 08:46:21 2021
sorting table 7
Backpropagating on table 6
scanned table 6
scanned time =  1053.566 seconds. CPU (82.630%) Thu May  6 09:30:06 2021
sorting table 6
sort time =  4051.678 seconds. CPU (54.730%) Thu May  6 10:37:38 2021
Backpropagating on table 5
scanned table 5
scanned time =  862.661 seconds. CPU (95.830%) Thu May  6 10:52:05 2021
sorting table 5
sort time =  3705.220 seconds. CPU (55.990%) Thu May  6 11:53:50 2021
Backpropagating on table 4
scanned table 4
scanned time =  855.177 seconds. CPU (94.100%) Thu May  6 12:08:12 2021
sorting table 4
sort time =  3756.554 seconds. CPU (54.690%) Thu May  6 13:10:48 2021
Backpropagating on table 3
scanned table 3
scanned time =  842.955 seconds. CPU (95.810%) Thu May  6 13:24:53 2021
sorting table 3
sort time =  3680.357 seconds. CPU (56.140%) Thu May  6 14:26:14 2021
Backpropagating on table 2
scanned table 2
scanned time =  869.055 seconds. CPU (95.890%) Thu May  6 14:40:52 2021
sorting table 2
sort time =  3657.098 seconds. CPU (56.930%) Thu May  6 15:41:49 2021
table 1 new size: 3425196920
Time for phase 2 = 25536.406 seconds. CPU (60.440%) Thu May  6 15:41:59 2021
Wrote: 268

Starting phase 3/4: Compression from tmp files into "/media/Temp/plot-k32-2021-0                                                                                                                                                             5-05-11-44-74a627d1f68d9c33482f4fc3601577c04e037b9916e4c0291a4a3789e18bfc26.plot                                                                                                                                                             .2.tmp" ... Thu May  6 15:41:59 2021
Compressing tables 1 and 2
        Bucket 0 uniform sort. Ram: 1.894GiB, u_sort min: 1.250GiB, qs min: 0.31                                                                                                                                                             3GiB.
Killed

**Comment by chiabug** [comment]
Check the amount of space available in the temp folder.
