### ISSUE TITLE
[BUG] Can't connect to the wallet

### ISSUE THREAD

**Issue by Lampo0309** [Chia-Network/chia-blockchain#3955]
**Describe the bug**
The app is trying to connect to my wallet for an hour without success. The app version is 1.1.4. Yesterday it started the synching process but I had to travel and now I am at a different location and I thought I can restart the synching process while working but I only got to the "Connecting to wallet" sign. What should I do?

**Desktop (please complete the following information):**

- OS: Win10 Pro
- CPU: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz

**Comment by abbail** [comment]
Maybe related to [https://github.com/Chia-Network/chia-blockchain/issues/3851](https://github.com/Chia-Network/chia-blockchain/issues/3851)

I was able to work round this myself with editing the sqllite database
