### ISSUE TITLE
[help] I have opened port but still can't add peers/can't synchronize

### ISSUE THREAD

**Issue by rangerov** [Chia-Network/chia-blockchain#3956]
Anyone having same issue? 

Chia Nodes | PORT | BLOCK
5.189.201.93 | 8444 | [LOCAL*]
188.233.133.89 | 8444 | [240524]
84.106.156.127 | 8444 | [240523]
81.217.130.233 | 8444 | [240524]

introducer-apne.chia.net:8444
introducer-apse.chia.net:8444

introducer-or.chia.net:8444
introducer-va.chia.net:8444
introducer-eu.chia.net:8444

Tried all of these, nothing can be added to other peers. 

Success: I can see your service on **.***.**.** on port (8444)
Your ISP is not blocking port 8444

**Comment by Leozolt** [comment]
at what point does tracert (windows) / traceroute (linux) fail probing for port 8444

example: traceroute node-eu.chia.net -p 8444

P.S. dont post your public IP here.. If the packet fails on the way you have some info to ask your ISP for assistance. If the packet fails before reaching your public IP gateway there is something wrong with your local network.

**Comment by rangerov** [comment]
i didnt post my ip, i censored myself. this is tracert result
15     *        *        *     Request timed out.
16     *        *        *     Request timed out.
17     *        *        *     Request timed out.
18     *        *        *     Request timed out.
19     *        *        *     Request timed out. 
20     *        *        *     Request timed out.
21   158 ms   144 ms   152 ms  chia.keva.app [5.189.201.93]

there are some failing like this and before that everything is normal

**Comment by Leozolt** [comment]
traceroute to 5.189.201.93 (5.189.201.93), 30 hops max, 60 byte packets
 1  fritz.box (192.168.1.1)  0.590 ms  0.912 ms  1.083 ms
 2  ***my public ip gateway***  19.777 ms  21.709 ms  23.668 ms
 3  213.135.247.10 (213.135.247.10)  26.034 ms  27.028 ms  35.137 ms
 4  213.135.247.5 (213.135.247.5)  31.233 ms  32.831 ms  34.345 ms
 5  * * *
 6  ipv4.de-cix.fra.de.as31133-frnkt-pe-mx960-1.megafon.ru (80.81.192.236)  45.588 ms  37.630 ms  39.552 ms
 7  83.169.204.57 (83.169.204.57)  136.712 ms  126.461 ms  127.923 ms
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  chia.keva.app (5.189.201.93)  107.339 ms  108.403 ms  110.545 ms

**Comment by chiabug** [comment]
Those timeouts are likely just normal for tracert given that it did get to the destination.
