### ISSUE TITLE
[BUG] coneccting to wallet message for few hours

### ISSUE THREAD

**Issue by AnSen555** [Chia-Network/chia-blockchain#3959]
I have an "connecting to wallet" message for a few hours

All CHIA Versions checked, same problem

Windows 10 64 bit

PS is it possible that I get this trouble after I use my mnemonic phrase on second PC?

Have deleted Chia from second PC but still have a same problem.

Checked delete Chia and checked another Version it’s not working.......

[
![Screenshot (1)](https://user-images.githubusercontent.com/83773692/117327527-fbecf200-ae92-11eb-8e03-9d11dd9ecf4a.png)
](url)

**Comment by blusave** [comment]
I have same issue - infinite connecting to wallet

**Comment by chiabug** [comment]
Change the config.yaml log level to "info" and then restart and examine the logs for more clues.

**Comment by ValerioFoddai** [comment]
I have the same issue, and I lost 12 hours of plotting... I hope they will fix this bug soon.

**Comment by blusave** [comment]
> Change the config.yaml log level to "info" and then restart and examine the logs for more clues.

Please explain how to do this

Probably easier to just uninstall and start from scratch...

**Comment by blusave** [comment]
FYI uninstalling and reinstalling fixed the issue for me

**Comment by mattmodene** [comment]
It's possible one of the ports Chia uses is being automatically excluded within Windows. To prevent that from happening and reserve the port, you can try this command in PowerShell.

netsh int ipv4 add excludedportrange tcp startport=55400 numberofports=1 store=persistent

I had the same issue after updating to v1.1.3 and this fixed the problem for me. No need to uninstall Chia or remove any files.

**Comment by purefloyd** [comment]
same here.

**Comment by HaveANiceDayM** [comment]
Same here- ive tried to uninstall Chia couple of time, or using the command from @mattmodene , but still cant connect. :(

**Comment by Jostream** [comment]
same here

**Comment by jtichile** [comment]
same here, I have to tried uninstall and install the new release downloaded. Same results...

**Comment by mdrodge** [comment]
You don't need to uninstall. Just delete the wallet folder in c:/users/"user name"/.chia

**Comment by AnSen555** [comment]
> You don't need to uninstall. Just delete the wallet folder in c:/users/"user name"/.chia

Wallet folder completely? Thanks

**Comment by mdrodge** [comment]
I just deleted everything apart from the config folder in /"username"/.chia
Including the wallet folder but I'm assuming that the wallet folder would
be enough if you are having a wallet related issue. (Not sure if that'll
effect any coins you may have)

**Comment by AlDrum** [comment]
I have the same problem, pls help!

**Comment by AlDrum** [comment]
![image](https://user-images.githubusercontent.com/83807383/117411627-10bd9a00-af14-11eb-876c-e3875b37be21.png)

**Comment by AnSen555** [comment]
> I just deleted everything apart from the config folder in /"username"/.chia Including the wallet folder but I'm assuming that the wallet folder would be enough if you are having a wallet related issue. (Not sure if that'll effect any coins you may have)
> […](#)

It helps!!!!! Thank you very much;-)

**Comment by AnSen555** [comment]
> I just deleted everything apart from the config folder in /"username"/.chia Including the wallet folder but I'm assuming that the wallet folder would be enough if you are having a wallet related issue. (Not sure if that'll effect any coins you may have)
> […](#)

This way helps me to fix a bug, thank you!
