### ISSUE TITLE
retry on creating plot not working

### ISSUE THREAD

**Issue by aminlv** [Chia-Network/chia-blockchain#3965]
to be short it said retry after 5 minutes but nothing continue even after hours and i had to restart whole thing from zero again!
quiet annoying 
it doesnt read previous progress after reloading thats major flaw 
so every little issue causing redo the whole process all over again

**Comment by PC101guy** [comment]
Yep, it sucks but one fix that worked for me is to check all your overclocks (cpu, ram) A bad overclock will do this 9/10.  My ram was clocked horribly so I had to go into bios and load defaults, been working fine ever since.

**Comment by night-lurker** [comment]
after closing the program with plots still going... you remember to delete temp files from those plots.. 
or you will end up with alot of temp files taking all the space
