### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KIMB0212** [Chia-Network/chia-blockchain#3977]
In short, the plots all stop at 31%.
Log:
Forward propagation table time: 2428.408 seconds. CPU (125.110%) Thu May  6 18:36:17 2021
Time for phase 1 = 14798.856 seconds. CPU (130.460%) Thu May  6 18:36:17 2021

Starting phase 2/4: Backpropagation into tmp files... Thu May  6 18:36:17 2021
Backpropagating on table 7
scanned table 7
scanned time =  50.867 seconds. CPU (52.740%) Thu May  6 18:37:08 2021
sorting table 7
Backpropagating on table 6
scanned table 6
scanned time =  325.223 seconds. CPU (94.530%) Thu May  6 18:46:30 2021
sorting table 6
ecc.........

**Comment by MustDhiMust** [comment]
it's normal, at least on my machine

**Comment by KIMB0212** [comment]
Thanks, my thought comes from the fact that everyone started at different
times 30 minutes, as I have a slow HDD on output, what will happen if in
the end everyone transfers the plot at the same time?

Il Gio 6 Mag 2021, 20:05 MustDhiMust ***@***.***> ha scritto:

**Comment by MustDhiMust** [comment]
just keep mind that "temp" folder is on faster drive platform

**Comment by KIMB0212** [comment]
Everything works fine !!! The plots are restarted at different times from how they stopped. Great.....

**Comment by KIMB0212** [comment]
Excellent!!!
