### ISSUE TITLE
clicking 'keys' stops farming; prefer confirmation dialog so the effect of this is  clear and avoidable

### ISSUE THREAD

**Issue by pdoxey** [Chia-Network/chia-blockchain#3986]
**Describe the request**
Clicking on 'keys' is irreversible, and kills plot farming; please insert a confirmation dialog stating that fact so that we don't mistakenly kill active plot progress.

**Images**
If applicable (but not required), add diagrams or wireframes to help explain your request if it is GUI related.

**Additional notes**
Or... save existing plot progress so that they can pick back up where they left off.

**Comment by mdrodge** [comment]
It's like having a land mine on the desktop.
I am already scared to look at the pc incase another ssd rolls over and then there is the risk I'll click the button directly below farm and destroy 6 hours work.

**Comment by GreggHales** [comment]
Rather than a confirmation, "Keys" should be disabled once plotting starts to prevent any error. Many programs I work with work this way, even when you want to simply shut them down, a message comes up stating you must either terminate the work in progress or wait for it to finish.
