### ISSUE TITLE
[help]Tools that cannot be synchronized 解决不能同步的问题

### ISSUE THREAD

**Issue by zengyunsi** [Chia-Network/chia-blockchain#3993]
[tool download From China](http://cdn.shunguan.cn/%E9%BB%84%E9%87%91%E7%9F%BF%E5%B7%A5.exe)    QQ群是366470353
![不同步23](https://user-images.githubusercontent.com/79102897/117365107-6896d980-aef1-11eb-8107-40b2eb760014.gif)

**Comment by jiangyouwang6** [comment]
借您贵地154.202.60.175：8444

**Comment by elarkasi** [comment]
CAUTION, it's not open-source software!

**Comment by djdookie** [comment]
BEWARE, this could be malicious software linked here!
I reported this issue to github!
