### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mdrodge** [Chia-Network/chia-blockchain#3997]
Chia Full Node Syncing extremely slow.
Version 1.1.4

I'm almost never in sync. (It is Syncing but it's only ever been in a synchronised state for a few hours on the 3rd (on Version 1.1.2)
Since V1.1.4 i have never been in sync.
(Even after I reinstalled Windows to free up an extra ssd)

Router Firewall has 8444 udp and tcp set to pass to my local static ip.
Windows firewall was set with local and external privilege during Chia setup.

With a 60Mb fibre-to-node connection this shouldn't be so painful.

I see this was closed as an issue 13 days ago but it's not fixed.
I'm plotting with no chance of ever winning when I should be selling my computer and paying my water bill.
I need a win!!!!!!!!!!

**Comment by zengyunsi** [comment]
Friend, you may need this
![123](https://user-images.githubusercontent.com/79102897/117372569-4fdff100-aefc-11eb-9c78-34022c7cd992.gif)

**Comment by mdrodge** [comment]
I don't understand what I'm looking at.
Is that a tool?
Looks interesting.
Where can I find it please?

**Comment by lvcivs** [comment]
try the steps described here: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
