### ISSUE TITLE
[BUG] No sincroniza

### ISSUE THREAD

**Issue by nitaaaa** [Chia-Network/chia-blockchain#3999]
Version 1.1.4

**Comment by DoeDoes** [comment]
same to me and don't know why

**Comment by babanana009** [comment]
same here 
driving me crazy

**Comment by lvcivs** [comment]
It is usually because you don't have enough connections to peers. Read this: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-does-my-node-have-no-connections-how-can-i-get-more-connections
