### ISSUE TITLE
[help] XCH went missing after making transfers.

### ISSUE THREAD

**Issue by ioanvm** [Chia-Network/chia-blockchain#4003]
**Describe the issue**
Long story short: made some transfers and some XCH disappeared.

**To Reproduce**
I have one single key with one wallet, with the following transfers:
- some block rewards, amounting to 18 XCH
- 4 transfers to an exchange, amounting to 2 XCH
- 4 "change" transfers, amounting to 4.75 XCH

However, doing a `chia wallet show` only shows 7 XCH remaining. I think 7 results from 2.25 XCH (which can be seen on chiaexplorer) + 4.75 XCH the change. However, I'd expect to have 18-2=16 XCH in my wallet.

**Expected behavior**
See the expected wallet balance of 16 XCH.

**Additional context**
I've checked both chiastatus.com and `chia wallet get_transactions` and there's nothing unexpected, just what I listed above. I've tried using both the linux CLI and mac GUI (1.1.x versions), with the same result. I've discussed this in keybase#support but without any result, only found more people with the same problem.

**Comment by ioanvm** [comment]
RPC get_wallet_balance shows the same problem.

**Comment by ioanvm** [comment]
I think I just paid 9 XCH as transaction fees.... rip

**Comment by DatDraggy** [comment]
Please close your issue
