### ISSUE TITLE
[help] App stucked on "Connecting to wallet"

### ISSUE THREAD

**Issue by christopheSF** [Chia-Network/chia-blockchain#4004]
<img width="1181" alt="Screen Shot 2021-05-06 at 3 52 01 PM" src="https://user-images.githubusercontent.com/8023832/117374986-099a7b80-ae83-11eb-940d-15f84edd7922.png">

See attached

**Comment by chienvache87** [comment]
Me too!!

**Comment by juancruz0912** [comment]
I have the same problem, I was trying for 2 weeks and it don't connect if someone have a solution please told me

**Comment by tvffty** [comment]
This worked for me.

1. Close the app
2. Make sure that all chia.exe's are not running (check task manager)
3. Restart the farmer
4. Done

**Comment by chienvache87** [comment]
Ok I try!

Le 6 mai 2021 à 20:05, tvffty ***@***.******@***.***>> a écrit :



This worked for me.

  1.  Close the app
  2.  Make sure that all chia.exe's are not running (check task manager)
  3.  Restart the farmer
  4.  Done

**Comment by christopheSF** [comment]
I am running the mac app

**Comment by chienvache87** [comment]
Me too!

Le 6 mai 2021 à 20:17, christopheSF ***@***.******@***.***>> a écrit :


I am running the mac app

**Comment by TonyCollins** [comment]
First Time,, I was trying to delete  a PLOT cos of PLOT C:/ Red overflowing with PLOT files...
Then sort or Crashed for 5 hours can not open dam wallet...I deleted some of the FILES in .chia like debug files and config... BUT still no luck.. I hope in Morning things will be Better other wise LAST resort , REINSTALL WINDOWS fresh CURES most things..

**Comment by JRymcgur** [comment]
The exact same thing happened to me with the red overflowing and now same problem.  Has anyone solved this after overestimating drive space?

**Comment by AlexArzon** [comment]
![Screen Shot 2021-05-06 at 6 32 43 PM](https://user-images.githubusercontent.com/83790857/117392068-47b59080-aebf-11eb-8e1d-2f3837680433.png)

**Comment by Andy151782** [comment]
I had the same Problem for 24h.

delete the wallet folder in c:/users/"user name"/.chiaWallet folder completely? 
This help for me!

BR Andy

**Comment by JRymcgur** [comment]
> 
> 
> I had the same Problem for 24h.
> 
> delete the wallet folder in c:/users/"user name"/.chiaWallet folder completely?
> This help for me!
> 
> BR Andy

That worked perfectly!  Thank you!

**Comment by TonyCollins** [comment]
Thanks very much,,,,

Delecting wallet worked……Shame I have messed syncing up, but next time I will know what to do and hope it wil sync straight away… Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by christopheSF** [comment]
Still stuck on the same issue... Anyone else found a workaround on Mac?

**Comment by TonyCollins** [comment]
Deleting Wallet, I would say was a BIT overkill...And all the Syncing fully again sucked....I would chek in TASK Manager...Sometimes I find LOADS of Chia ruuing Multiple nodes wallets e.t.c.. I think its because I am impatiant... Hitting X button instead of waiting 20 seconds to fully close Chia Properly...SO YEAH, 100 Percent.. use MORE in Task manager close all CHIA related sub programmes running...Also this fixed Wallet syncing Problems...
