### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tkmbe99** [Chia-Network/chia-blockchain#4015]
**Describe the bug**
This is the second time a plot hangup at 87% when compressing  table 6&7

**Screenshots**
How can I add pictures I see no option and cut and paste does not work?

**Desktop (please complete the following information):**

- OS: Win 10 Home
- OS Version/Flavor: 20H2
- CPU: Intel Core i5 760

**Additional context**
After 1h30min I shutdown the gui. The temp files was not touched 1h30min.
Current chia version 1.1.4
Created one plot with 4M 2 threads on an empty SSD disk with 512G space.
The same worked several plots before.
In the past it was the same problem and same table compression but with V 1.1.3

**Comment by Gnomuz** [comment]
Most likely you ran out of RAM
