### ISSUE TITLE
[BUG] Connecting to wallet hang, takes hours or never to even succeed... reload/force reload wont work, closing the application will destroy 80-90% of my plot progress

### ISSUE THREAD

**Issue by Indocryptomaniac** [Chia-Network/chia-blockchain#4022]
**Describe the bug**
Connecting to the wallet hangs, it keeps on having the cursor rotating... I click reload/force reload several time on the GUI with no success. Last time I solved this is to delete all end process all the chia application and delete all files in the SSD that has plots going on. Currently, I have plots ongoing with 70-80% progress just now so I don't want to do the hassle and end process. Does anyone knows how to solve this? The reason why I reloaded was because my farming time was way behind on the farming tab. It was 6am in Jakarta time and last farmed in the screen showed at like 3:30am we should be happening? As I thought when the PC is on, farming should keep on running while I'm asleep? What do you guys think? Thank you in advance for any help and advice!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by dEMonaRE** [comment]
same here 
OS: win10 enterprise - v 2004 - IS 19041
cpu : i5-7300hq

**Comment by Pluto1212** [comment]
same here
OS Win10 pro
CPU AMD 5 3600, 24GB
Plotting go´s on, but connecting to the wallet hangs, it keeps on having the cursor rotating

**Comment by Indocryptomaniac** [comment]
yes i ended up deleting all the ram plots, and restarting everything... 12 hours it will still have cursor rotating.. pointless already... and then try restart and hopefuly after 10-15mins it succeed to synching..
