### ISSUE TITLE
[BUG] Connections are extremely broken, my node keep rejecting 99.9999999999% of the connections right after SYN and unable to sync since updated to 1.1.4 HELP please.

### ISSUE THREAD

**Issue by megablue** [Chia-Network/chia-blockchain#4023]
my full node is keep rejecting most of connections right after receiving SYN, there is only 1 connection able to stay with my node..
it was fine on 1.1.2 and 1.1.3....

[this is screenshot of a few example of the connections that got rejected/failed.](https://imgur.com/a/xK5tQLZ)

**Comment by racabu** [comment]
After an internet outage, the node does not sync back. Stays in "Not Synced"
