### ISSUE TITLE
[help]Offline wallet

### ISSUE THREAD

**Issue by 1044740162** [Chia-Network/chia-blockchain#4026]
How to use nodejs to implement an offline wallet, create an address and sign transactions。
I did not find the relevant information, please help me

**Comment by xw332** [comment]
same

**Comment by 1044740162** [comment]
> same

Is it the same as what?

**Comment by LmingXie** [comment]
Can detailed documentation on offline signing be provided as soon as possible, regardless of programming language implementation .
