### ISSUE TITLE
[BUG] Increased swap usage over time on ARM64, possible memory leak?

### ISSUE THREAD

**Issue by jfikar** [Chia-Network/chia-blockchain#4032]
I'm running recent chia node and farmer on ARM64 SoC (Odroid HC4, 4GB RAM, Ubuntu 20.04.2) and I discovered that swap usage grows to 1GB during approximately 12 hours. After restarting with `chia start -r farmer` the swap usage drops to almost 0 (more precisely to 40MB).

The processes using the most swap space are:

```
chia_full_node 405780 kB
chia_full_node 404244 kB
chia_full_node 403684 kB
chia_wallet 168188 kB
chia_full_node 40464 kB
chia_daemon 30380 kB
chia_farmer 29040 kB
chia_harvester 11952 kB
```

as evidenced by a simple script
`
for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r | less`

Is the growing swap usage normal/expected, or is it a sign of a memory leak?

**Comment by arvdrpoo** [comment]
I have noticed a similar thing. Over the course of a day, the memory consumption slowly increases after a restart.
Attached is a screenshot of the Netdata memory graph, combining all chia processes.  
Real memory starts at 1.80GiB, 24 hours later it is at 1.94GiB.

![afbeelding](https://user-images.githubusercontent.com/6959074/117413209-f8e71580-af15-11eb-9f17-3dad2ba57b71.png)

My farmer is at chia 1.1.4 and runs on an ODroid N2+ 4GB running Debian Buster

**Comment by jfikar** [comment]
The swap usage stays all the time around 1GB. It looks like it is not a memory leak. The chia_full_node probably needs so much memory. If you have 4GB RAM, have at least 1.5GB swap.

**Comment by vladimir-velinov** [comment]
I had similar suspicion, about memory leak as I have Nano Pi Neo 3 with 2GB ram and 1 GB swap. I run it as full node only and wallet and leave it unattended. After some time, like couple of days I find that node is not responsive, although port 8555 is opened and complete swap file is being used. After restart everything is fine. Unfortunately I have not watched it closely, but may be it takes 2-3 days to enter into this mode.

**Comment by kochinc** [comment]
I set vm.swappiness to 10, so I haven't seen much swapping on my Raspberry Pi 4 (4GB). However, I have been observing a steady increase on the memory usage. I restarted chia-blockchain when the memory usage was over 2GB, and the memory usage dropped to over 1GB. But, it's again steadily increasing. Should we expect the memory usage will keep increasing as the blockchain getting longer?

**Comment by arvdrpoo** [comment]
Since my last post here, I added 1GB of swap. 
Again, I notice similar behavior. The swap space fills up in about two days, thanks to chia processes

![afbeelding](https://user-images.githubusercontent.com/6959074/120003045-a7dab680-bfd5-11eb-8b9e-cd793837a60e.png)

**Comment by jfikar** [comment]
It could be vm.swappiness as @kochinc suggests, as I had it set 90. But meanwhile I migrated the full node to 8GB Raspberry Pi4 and there after a week I see only 538MB swap (vm.swappiness=90). I'll try to lower it to 10 and see, what happens. Maybe also with only 4GB RAM again.

On the other hand, the full node seems to work fine even with large swap allocated. There is no I/O. It seems that the swapped out memory is not needed. Maybe the full node can be more memory optimized?
