### ISSUE TITLE
How to transfer xch through Linux

### ISSUE THREAD

**Issue by aaronnfisher** [Chia-Network/chia-blockchain#4037]
I lose my Private key。。but my linux wallet had 3 xch，how to transfer xch through linux？
help me thanks！

**Comment by DatDraggy** [comment]
Use your recovery phrase which you wrote down when creating the wallet to recover the wallet.
There is no other way

**Comment by aaronnfisher** [comment]
> Use your recovery phrase which you wrote down when creating the wallet to recover the wallet.
> There is no other way

but i cann't use linux wallet transfer xch？only use windows？？

**Comment by DatDraggy** [comment]
You can use any wallet. You just need to import it.
https://github.com/Chia-Network/chia-blockchain/wiki/Moving-plots#moving-plots-to-a-different-machine
`chia keys add`

**Comment by aaronnfisher** [comment]
> You can use any wallet. You just need to import it.
> https://github.com/Chia-Network/chia-blockchain/wiki/Moving-plots#moving-plots-to-a-different-machine
> `chia keys add`

i lose my key...

**Comment by DatDraggy** [comment]
Then use your 24 word recovery phrase.

**Comment by aaronnfisher** [comment]
> Then use your 24 word recovery phrase.

Thanks!
