### ISSUE TITLE
Standalone Farming System doesnt find Plots on Network Drive

### ISSUE THREAD

**Issue by blackpearlla** [Chia-Network/chia-blockchain#4041]
On a single standalone Farming System the Plots on the Network Drive always listed by "Plots not found"

**Comment by kaisersose1995** [comment]
Is saw this issue today as well. Out of 5 plots, 2 were found and appeared under farming with a green status. 3 were under “plots not found”.. tried quitting and relaunching GUI but couldn’t get them to show under farming.
