### ISSUE TITLE
[help] CONNETION TO WALLET

### ISSUE THREAD

**Issue by Robin69CH** [Chia-Network/chia-blockchain#4042]
Goodmorning everyone,

yesterday I started my farm, unfortunately I didn't have much space.

Today after the upgrade of my pc, for several hours the system has been trying to connect to the wallet and is always waiting.

Why this problem?
How can I fix it?
CHIA USE 1.1.4

**Comment by xguya** [comment]
same problem today. I cannot solve...

**Comment by Berlin1907** [comment]
I have the same problem...

**Comment by lee20210503** [comment]
I have the same problem for few days.....

**Comment by jimmylaos1982** [comment]
I cannot connect to my wallet it takes for along time and no connect.

**Comment by fabin1** [comment]
Hi, I have the same problem. I could not connect on linux via cmd line. Thanks.

**Comment by alex27riva** [comment]
Same problem here, and I have this error on Linux: https://ibb.co/0yFKcj2

**Comment by mariushamiltonro** [comment]
Yes. Same here. Uninstall worked only.
Used 1.1.4, connected, got a prompt to add metadata backup file, skipped and now hopefully it will synch. 
Kind of a pain since it worked day before 
 fine with no changes to the pc.

**Comment by fabin1** [comment]
If full node is OK and wallet has problem with sync, hope there is no problem of win XCH lotery, isn´t it?
