### ISSUE TITLE
[help]On a single standalone Farming System the Plots on the Network Drive always listed by "Plots not found"

### ISSUE THREAD

**Issue by luica1carosia** [Chia-Network/chia-blockchain#4056]
On a single standalone Farming System the Plots on the Network Drive always listed by "Plots not found"

**Comment by josungo88** [comment]
Same issue, i've read in other post it works to restart the GUI, I haven't tried it because im still plotting but i've seen 2 or 3 other ppl with this issue and this seems to work.
