### ISSUE TITLE
[REQ] Windows GUI:  Option for plotter only

### ISSUE THREAD

**Issue by TopSecretGunner** [Chia-Network/chia-blockchain#4061]
Request:  Option on the Windows GUI which will run the plotter without the additional services that run on the first Chia install (farmer, wallet, blockchain)

Benefits:  
Reduced network traffic due to not synching multiple blockchains.
Elimination of multiple farmers watching the same set of plots.

**Comment by lvcivs** [comment]
If you are going to plot only, just use the CLI.

**Comment by pluto2021** [comment]
Windows CLI is significantly slower somehow!
