### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by glaucocm** [Chia-Network/chia-blockchain#4063]
After update 1.1.4 Sync is failing.

**Comment by AlbyGNinja** [comment]
same problem

**Comment by BaraoVlask** [comment]
About 5 minutes ago, my node stoped sync

**Comment by BaraoVlask** [comment]
And no one introducer are working

```
➜  ~ chia show -a introducer-apne.chia.net:8444
Connecting to introducer-apne.chia.net, 8444
Failed to connect to introducer-apne.chia.net:8444
➜  ~ chia show -a introducer-apse.chia.net:8444
Connecting to introducer-apse.chia.net, 8444
Failed to connect to introducer-apse.chia.net:8444
➜  ~ chia show -a introducer-or.chia.net:8444  
Connecting to introducer-or.chia.net, 8444
Failed to connect to introducer-or.chia.net:8444
➜  ~ chia show -a introducer-va.chia.net:8444
Connecting to introducer-va.chia.net, 8444
➜  ~ chia show -a introducer-eu.chia.net:8444
Connecting to introducer-eu.chia.net, 8444
Failed to connect to introducer-eu.chia.net:8444
```

**Comment by gotblindside** [comment]
same problem
i'm on windows

**Comment by phild2h** [comment]
Same issue here, tried to connect to 8444 but nothing... was working just fine yesterday. Also on Windows 10

**Comment by secco04** [comment]
Same here on Win10 and 1.1.5 
` farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x000001F3DE1FCC88> [Connect call failed ('127.0.0.1', 8444)]`
And full node state is not syncing 

I have temporarely fixed it adding some other full nodes  like 

`node-eu.chia.net:8444
node.chia.net:8444
chia.yacp.net:8444`
but after reboot i have to re-add the hosts...
