### ISSUE TITLE
After upgraded 1.1.4 mac always connecting to wallet [BUG]

### ISSUE THREAD

**Issue by hzcm123** [Chia-Network/chia-blockchain#4068]
After upgraded 1.1.4 mac always connecting to wallet. Tried different computers. Win10  works normal, another mac has same problem.
<img width="1198" alt="123" src="https://user-images.githubusercontent.com/83824126/117464720-caf9d500-af05-11eb-8e10-50b6d68bb549.png">

**Comment by rexodor** [comment]
Mee too, same bug

**Comment by rexodor** [comment]
> yo con windows 10 no puedo sincronizarme

Probe en Windows 10 y pude sincronizar bien. Dime si pudiste.

**Comment by hipolitolp** [comment]
> > yo con windows 10 no puedo sincronizarme
> 
> Probe en Windows 10 y pude sincronizar bien. Dime si pudiste.

Todavia estoy creandoi una parcela, voy a esperar a que termine para reiniciar y probar si sincroniza

**Comment by rexodor** [comment]
> > > yo con windows 10 no puedo sincronizarme
> > 
> > 
> > Probe en Windows 10 y pude sincronizar bien. Dime si pudiste.
> 
> Todavia estoy creandoi una parcela, voy a esperar a que termine para reiniciar y probar si sincroniza

De cuanto espacio y/o disco duro libre estas haciendo las parcelas?

**Comment by hipolitolp** [comment]
Estoy haciendo la k32

1 sola, con un ssd de 512gb (1700/1500) 
y la guardo en un Hdd de 8tb que apenas llevo 1tb lleno
