### ISSUE TITLE
[BUG Unable to connect to wallet, always waiting. Network connection is normal, how to solve it?, port is open

### ISSUE THREAD

**Issue by AlexArzon** [Chia-Network/chia-blockchain#4084]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by AlexArzon** [comment]
Unable to connect to wallet, always waiting. Network connection is normal, how to solve it?, port is open

**Comment by techaura** [comment]
The same problem today

**Comment by wilis2104** [comment]
same problem.....almost 2 hours waiting..
OS: WİN 10 PRO
CPU  :İ7 4790k intel

**Comment by elforin22** [comment]
cansado de que no ande el programa o ande mal

**Comment by juancruz0912** [comment]
please a solution

**Comment by cheungfe** [comment]
![472B3906-CF5A-4BE8-B32E-6F7336F148DE](https://user-images.githubusercontent.com/34437898/118386164-fc7e4900-b647-11eb-95af-17dcb9d82898.jpeg)
I’ve got the same problem on one of my computers... so sad waiting an eternity later... still won’t connect...

**Comment by AlexArzon** [comment]
I put in a bug request to see what happens ??
