### ISSUE TITLE
[REQ] [GUI] start next plot after phase 1 automatically (auto-delay)

### ISSUE THREAD

**Issue by cswxaq** [Chia-Network/chia-blockchain#4088]
**GUI > Plots > Choose Number of Plots:**
Add option to start next plot after multithreading phase (1) _automatically_ when plotting in parallel.

This would make setting up stagged plotting alot easier.

**Comment by Bigfoots44** [comment]
To add to this, start after phase x or start after %x

**Comment by coolpro313** [comment]
i'm not a developer but i agree that would be a great option to add into the software instead of comparing between 2-3 plot sessions on the time it takes to complete phase 1 and dividing that time by 60 and set the answer to the delay setting

**Comment by luotinen** [comment]
Good idea! This would reduce the amount of guesswork involved.

**Comment by amirdt22** [comment]
Check out https://github.com/ericaltendorf/plotman and there is another version if you are on windows: https://github.com/wolfrage76/windows-plotman

**Comment by coolpro313** [comment]
@amirdt22 also is there a easier way to run this software for the windows version at all? i'm no good with command prompt type softwares including terminal for linux and powershell for windows i'm just a beginner type with that type of programs. can be a template that i can edit and just execute either with a double click or opening the folder in command prompt and enter the program name.exe that type

**Comment by amirdt22** [comment]
> @amirdt22 so basically that program will automatically start phase 1 of the next plot right after phase 1 on previous plot finishes without having to use the GUI and guessing the delay time or what i'm dojng running a plot 1 at a time and noting down the time for first 4 files and using the calculator and doing the time in seconds divided by 60 and entering the answer into the delay box?

plotman will manage the plotting in a different way and allow you to tune the delay and parallelism in a few ways, not exactly as you have stated but with a similar goal.

> @amirdt22 also is there a easier way to run this software for the windows version at all? i'm no good with command prompt type softwares including terminal for linux and powershell for windows i'm just a beginner type with that type of programs. can be a template that i can edit and just execute either with a double click or opening the folder in command prompt and enter the program name.exe that type

I'm not familiar with the windows version, it claims to be beta right now so maybe it needs some time.  Just wanted to make you aware of it as another project that might help you.

**Comment by coolpro313** [comment]
@amirdt22 oh what about for the linux version  i can create a virtual machine on my windows PC and run it in the background

**Comment by coolpro313** [comment]
@amirdt22 i kept getting this error when i try to plot on both softwares main gui cli and plot man do you know any fixes for this at all?

latest ubuntu cli and plotman and entered everything correctly and have enough ram and storage 
![66534479-B038-4380-B448-BC88E3B8D1B7](https://user-images.githubusercontent.com/56607498/117673025-65614f00-b178-11eb-9f49-24ab4b31602d.jpeg)
