### ISSUE TITLE
[REQ]8444

### ISSUE THREAD

**Issue by uwerui** [Chia-Network/chia-blockchain#4089]
Port 8444 is not opened, but it has been synchronized. Does XCH block rewards have it？

**Comment by Fexiven** [comment]
Opening port 8444 is only that someone else can connect to your IP/Full Node.
You are still connected to the Blockchain an receive new blocks and rewards.

Blocking port 8444 outgoing is another case...

**Comment by uwerui** [comment]
> 打开端口8444只是其他人可以连接到您的IP /完整节点。
> 您仍然连接到区块链并获得新的区块和奖励。
> 
> 阻止端口8444传出是另一种情况...

How to check if it's blocked

**Comment by Muffexx** [comment]
You can try this [tool](https://www.yougetsignal.com/tools/open-ports/) and enter your public ip and port 8444.
