### ISSUE TITLE
[REQ] Smarter plotting failure handling for memory allocation

### ISSUE THREAD

**Issue by abale** [Chia-Network/chia-blockchain#4091]
**Describe the request**
Memory usage varies substantially for a given plotting process depending on it's current state of plotting.  Currently, to be safe and ensure no plots fail during allocation attempts, one should allocate 3380MB of ram PER desired concurrent plot.  During testing with staggered plotting, it is possible to never exceed 12GB of private working set with 6 plots, provided they do not overlap during peak memory phases.  

The current logic of create plot is to fail and die when allocation fails, as per below.  My findings imply that if the allocation fails, the plot can be salvaged by simply waiting until memory in the total pool frees up from another sibling plot.  Simply wait 1  minute and try again.  To avoid deadlock scenario where all processes need to allocate memory and can't since the pool is full and they are waiting - if after several attempts (30-120 seems sane) there is still no memory available in pool to allocate, the process should flush it's memory and die (or suspend), making room for a sibling to move forward before resuming.

This would allow for a lot of waste reduction in failed plotting attempts and much better success rate.

Once work to "resume" a failed plot is landed, that same checkpointing/recovery could be used with this logic to recover even a worst-case situation where the process terminates.

**Images**
with 20GB memory allocation on 8 parallel plots (15min delay):
![image](https://user-images.githubusercontent.com/12463120/117483671-001d1c00-af34-11eb-815a-427a069b7f15.png)

less than 6GB private working set for 5 active plots:
![image](https://user-images.githubusercontent.com/12463120/117483692-0612fd00-af34-11eb-99e6-0b337010239f.png)

**Additional notes**
System:
R9 3900x
32GB ram
90GB swap
3.2TB ultrastar nvme temp (HUSMR7632BHP301)

`Caught plotting error: bad allocation
[22824] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: bad allocation`

**Comment by JPiqu** [comment]
+1
