### ISSUE TITLE
[help] I get Error 1

### ISSUE THREAD

**Issue by dangerousmoon** [Chia-Network/chia-blockchain#4093]
Hello. I have a problem.

I got this error with my 228 GB SSD and 8 TB HDD.

Only wrote 256 of 1048572 bytes at offset 67108608 to "E:\\Quick\\plot-k32-2021-05-07-19-53-932e65de2fd675701f1f67b8fb46605903ebaf1640243e616cc9b48c43961bc0.plot.p1.t1.sort_bucket_126.tmp"with length 67108864. Error 1. Retrying in five minutes.

**Comment by olafbuitelaar** [comment]
are you sure you have enough free disk-space left?

**Comment by dangerousmoon** [comment]
> are you sure you have enough free disk-space left?

Yes, I have enough free disk-space.
