### ISSUE TITLE
[BUG] Missing "First Wallet Key" when running Chia Keys Show

### ISSUE THREAD

**Issue by TeddyKGBee** [Chia-Network/chia-blockchain#4096]
When in the CLI, I run a Chia Keys Show command. The command shows the following:

Master public key
Farmer public  key
Pool public key
First Wallet Address

But no "First Wallet Key".

Why would this be missing? What impact would it have on winning? and How should this be corrected?

**Comment by yuk320** [comment]
you should use  '--show-mnemonic-seed'
