### ISSUE TITLE
[REQ]does not connect wallet

### ISSUE THREAD

**Issue by elforin22** [Chia-Network/chia-blockchain#4102]
**Describe the request**
The wallet keeps loading as soon as I open the program

![Sin título](https://user-images.githubusercontent.com/83556986/117491966-59db1180-af47-11eb-9074-dfb975fd2cda.png)

I've been trying to enter the program for a while and it says saying loading the wallet, I already tried restarting my computer, Reinstalling chia blockchain, deleting permanent parcels and nothing. what solution?

Ryzen 5 5600x windows 10
32gb RAM

**Comment by lvcivs** [comment]
Did you check for errors in the log file?

**Comment by elforin22** [comment]
how is that?

**Comment by lvcivs** [comment]
`C:\Users\<yourusername>\.chia\mainnet\log\debug.log`

**Comment by josua1001** [comment]
se tiene que borrar el archivo?

**Comment by elforin22** [comment]
sigo con el problema hace horas...

**Comment by Trybouw** [comment]
I had the same problem. And just found an old thread [here](https://bleepcoder.com/chia-blockchain/803231682/bug-cannot-connect-to-wallet-connecting-just-hangs)

You need to delete all "blockchain_wallet_v1_mainnet_NUMBER" files in this folder:

C:\Users\<yourusername>\.chia\mainnet\wallet\db

That fixed it for me.
