### ISSUE TITLE
Full node synced, but wallet NO (see pic.)

### ISSUE THREAD

**Issue by voipcall** [Chia-Network/chia-blockchain#4105]
Full node always synchronized but wallets NO 

Full Node tab:
![1](https://user-images.githubusercontent.com/23130666/117492694-d1e50f80-af26-11eb-9851-af66665f9fbb.PNG)
=========================================

Wallets tab:
![2](https://user-images.githubusercontent.com/23130666/117492729-db6e7780-af26-11eb-8393-455cfb323e52.PNG)

**Comment by tonghan1100** [comment]
my wallet stop at 227094.

**Comment by spodee4** [comment]
Same
