### ISSUE TITLE
Full node -- Status: Not Synced but Connection Status Connected

### ISSUE THREAD

**Issue by ledez-dev** [Chia-Network/chia-blockchain#4111]
Is this a known issue? My full node was connected but I restarted my PC and it's unable to connect anymore..

Please help..

**Comment by zacek80** [comment]
You solved it????

**Comment by tekken64** [comment]
Same here......the program suck....hope to have not wasted money and time........Hey Team....wake up!!!!!

**Comment by Thund3rst0rm89** [comment]
same problem ^^ not sync but connected

**Comment by unsolvent** [comment]
Try this. worked for me.
close chia gui
open task manager and stop every chia task still running
go to C:\Users\your_username\.chia\mainnet\db and delete all db except  **mainnet.sqlite** (your biggest file)
start chia again and wait few minutes. you should connect to a node and sync

note:
if you delete **blockchain_v1_mainnet.sqlite** you'll to resynch the wall thing. Be carefull.

**Comment by tekken64** [comment]
> Try this. worked for me.
> close chia gui
> open task manager and stop every chia task still running
> go to C:\Users\your_username.chia\mainnet\db and delete all db except **mainnet.sqlite** (your biggest file)
> start chia again and wait few minutes. you should connect to a node and sync
> 
> note:
> if you delete **blockchain_v1_mainnet.sqlite** you'll to resynch the wall thing. Be carefull.

Thx mate......i will try it but this software sucks anyway

**Comment by Kusey86** [comment]
> > Try this. worked for me.
> > close chia gui
> > open task manager and stop every chia task still running
> > go to C:\Users\your_username.chia\mainnet\db and delete all db except **mainnet.sqlite** (your biggest file)
> > start chia again and wait few minutes. you should connect to a node and sync
> > note:
> > if you delete **blockchain_v1_mainnet.sqlite** you'll to resynch the wall thing. Be carefull.
> 
> Thx mate......i will try it but this software sucks anyway

This is solved this problem?

**Comment by ledez-dev** [comment]
alright, i got sycned again by just keep on trying, relaunching, open/close. dunno if it was a server issue or something

**Comment by Kusey86** [comment]
close this please
