### ISSUE TITLE
[BUG]'chia wallet get_address' output is not my own address[major bug]

### ISSUE THREAD

**Issue by Yugosi** [Chia-Network/chia-blockchain#4127]
**Describe the bug**
chia wallet get_address is giving an address which is not mine!

**To Reproduce**
type chia wallet get_address in CLI

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/83486159/117516316-c9acc480-af66-11eb-8083-4daa38b57f6a.png)

**Desktop (please complete the following information):**

- OS: Window
- OS Version/Flavor: Win10
- CPU: i9-10900k

**Additional context**
I know this address is not mine because it was listed in the block that I transferred my chia yesterday and also my other two machines' chia GUI shows this address has a income of 1.7 chia in the wallet history (in the same block that I transferred my chia) but of course I have not received this 1.7 chia since this is not my address.
Is there a way in windows to check if the receiving address is corresponding to your private key? If so please let me know the command. THANKS!

**Comment by Yugosi** [comment]
Not sure if this was hacked by someone.

**Comment by mariano54** [comment]
Are you sure that is not yours? The wallet generates many different addresses that are all linked to your private key.

**Comment by jcr240** [comment]
same issue on chia 1.1.16
