### ISSUE TITLE
[help] download speed 

### ISSUE THREAD

**Issue by gipsydanger1903** [Chia-Network/chia-blockchain#4131]
Hello to everyone
k32 When I create a 101 GB file, the download speed is very slow. I have 100 Mbps speed but this process takes a long time, what should I do about it?

Sorry for the translation.

**Comment by 413303105** [comment]
Upgrade your computer

**Comment by gipsydanger1903** [comment]
GPU: ASUS GeForce GTX1660Ti ROG STRIX GDDR6 6GB
CPU: Ryzen 5 2600
M.2 SSD : Samsung 970 evo plus 250 GB
SDD:  Samsung 860 evo 500 GB
HDD: 500 GB Seagate Green
MB: MSI B450M GAMING PLUS
RAM:  2x Corsair 16GB  3000MHZ
PSU: Xigmatek 700 W 80+ Bronze 
Kasa: Xigmatek VenomX 
Soğutucu: XIGMATEK Aurora 240
Monitör: Aoc 23,5 inc
İnternet: TURKNET 100 MBPS
