### ISSUE TITLE
Wallet Won't Sync from the start but farming is going on[BUG]

### ISSUE THREAD

**Issue by SantaClausishere** [Chia-Network/chia-blockchain#4132]
**Describe the bug**
I am new to Chia Farming, I just started a few days ago. After I made my first plot, nothing would sync. I searched how to resolve it and I finally got it working, I had to reboot and restart a few times and followed some other suggestions and it finally synced and farming started. Unfortunately, the wallet didn't sync. When I click Wallets is says 
Status
status:
not synced
height:
207658
connections:
1
![image](https://user-images.githubusercontent.com/83849067/117521343-d6213380-afdf-11eb-962e-8596541a9ab9.png)

When I click on Full Node, scroll down to Connections I see
![image](https://user-images.githubusercontent.com/83849067/117521394-1da7bf80-afe0-11eb-95ba-97be8d1d74d9.png)

**To Reproduce**
The wallet never synced from the start. I am using Chia Blockchain 1.1.4

**Expected behavior**
I expected the wallet to sync.

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor:10
- CPU: Intel Core i7-8700 @ 3.20GHz

**Additional context**
When I was able to make my first plot a few days ago, it wouldn't sync. I tried restarting both the computer and the Chia program a few times and it still wouldn't work. I tried checking if the Port 8444 was open and it wasn't. I followed the instructions to Forward the port to 8444 in my router. I did, but when I do use the site to check port 8444 it still says it is closed. But when I restarted the program after forwarding the port to 8444 in the router, it successfully synced the plot and started to farm. But the wallet remains unsynced. I am not sure what to do next.

**Comment by Pluto1212** [comment]
same Problem

**Comment by spodee4** [comment]
same problem hope it gets fixed soon, I've tried all the fixes suggested, I've tried loading/reloading, installing/uninstalling, upgrading downgrading versions.  I finally just got synced after 24 hours of 'waiting to sync'. Oh mother.
