### ISSUE TITLE
[BUG]转账一直在待处理，两个钱包都已经同步了。

### ISSUE THREAD

**Issue by BekeOracle** [Chia-Network/chia-blockchain#4134]
**Describe the bug**
我从5月4号凌晨1点申请的转账到另外一个钱包，一直到今天5月8号，还是显示待处理。希望可以撤销这笔转账或者处理到账。

发起转账地址：xch1darqutwhnjjdz9en9fg264psdjzk4awx66fskgjxlgwzjj4fnugqc87xyp
接受转账地址：xch13ezdedam77ppt2ceejvyf7u4kuu8edhu5zzz7de752zu7my42k9s8l08qj

**Comment by r1235613** [comment]
這不是Bug，這是區塊鏈的特性。
你有在轉帳時支付手續費嗎？

**Comment by pokerface0206** [comment]
> 這不是Bug，這是區塊鏈的特性。
> 你有在轉帳時支付手續費嗎？

手续费为0，但很多人都是0，并且都可以成功

**Comment by pokerface0206** [comment]
![1620467483(1)](https://user-images.githubusercontent.com/22659475/117534934-13a8af80-b026-11eb-8f28-489c45f5167d.png)
