### ISSUE TITLE
[BUG] CLI: `chia wallet get_address` returns the same address every time

### ISSUE THREAD

**Issue by cmatthias** [Chia-Network/chia-blockchain#4135]
**Describe the bug**
According to my read of #996, `chia wallet get_address` should return a new address every time. But in my testing, repeatedly running `chia wallet get_address` returns the same address every time.

**To Reproduce**

1. Execute `chia wallet get_address` from the cli
2. Execute the command a second (or third, or more...) time
3. Observe that the returned address is the same each time.

**Expected behavior**
As a rule of thumb, addresses should not be reused, so this command should return a new address every time.

**Additional context**
This is especially annoying because as far as I can tell, there is no way to generate a new address from the CLI; the only way (aside from custom-crafting commands to send to the wallet RPC endpoint) is to fire up the GUI and click the "New Address" button in the Wallet tab, which then calls the wallet RPC endpoint with the correct parameter to generate a new address.

Could I get a confirmation from one of the project owners that my assumption about the intended behavior of the CLI is correct? If so, I can take a stab at a PR to fix this.

**Comment by r1235613** [comment]
Same Problem at 1.1.4

**Comment by sargonas** [comment]
Can confirm this isn't working as intended. Also tracking this in #4869 so I'll flag this as a duplicate and redirect you there.

**Comment by LouisLoudogTrottier** [comment]
This seems to be also true on 1.2.6

**Comment by ruixingchen** [comment]
this even not get fixed in 1.2.11 @ 2022, gods please

**Comment by sargonas** [comment]
Please follow up on additional comments on this issue under the issue number #4869 as this issue has been closed as a duplicate of that one.
