### ISSUE TITLE
[REQ]Not Wallet Sync

### ISSUE THREAD

**Issue by zacek80** [Chia-Network/chia-blockchain#4142]
**Describe the request**
the program does not sync a full day so I already open port 8444 and 55400 and nothing attached error

![Captura de pantalla 2021-05-07 212603](https://user-images.githubusercontent.com/83850664/117522788-dcc98f80-af7a-11eb-8860-719341368d41.png)
![Captura de pantalla 2021-05-07 212701](https://user-images.githubusercontent.com/83850664/117522842-13070f00-af7b-11eb-91cc-5c6344a9cb9c.png)

**Comment by Gomes1990** [comment]
IN THE LAST DAY MY NODLE GO DONW 50 TIMES....I THINK THAT PROBLEM IS ON CHIA SERVER
