### ISSUE TITLE
[help] Wallet traceback error in CLI

### ISSUE THREAD

**Issue by holdenprkr** [Chia-Network/chia-blockchain#4144]
**Describe the issue**
Any time I run `chia-start farmer` in the CLI I receive this back:

> C:\Users\[my-user]\AppData\Local\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon>chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
C:\Users\[my-user]\AppData\Local\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon>Traceback (most recent call last):
  File "chia\server\start_wallet.py", line 97, in <module>
  File "chia\server\start_wallet.py", line 92, in main
  File "chia\server\start_service.py", line 218, in run_service
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "chia\server\start_service.py", line 212, in async_run_service
  File "chia\server\start_service.py", line 156, in run
  File "chia\server\start_service.py", line 127, in start
  File "chia\wallet\wallet_node.py", line 152, in _start
  File "chia\wallet\wallet_state_manager.py", line 143, in create
  File "chia\wallet\wallet_blockchain.py", line 106, in create
  File "chia\wallet\wallet_blockchain.py", line 117, in _load_chain_from_store
  File "chia\wallet\wallet_block_store.py", line 283, in get_peak_heights_dicts
KeyError: b'\x989\x03\xec\x19L\x91\xf7\x12\xda\xd5\x8dk p{\x08\xf3\xc9\xae\xb52H\xbc\xa1\xf2%m\xd3|\xd6U'
[27184] Failed to execute script start_wallet

Any time I run `chia wallet show` I receive this connection error:

> Connection error. Check if wallet is running at 9256

**To Reproduce**
Switching to CLI after GUI gets stuck loading. Ran `chia init` with no migration action needed, and run `chia wallet show` to receive wallet connection error or `chia start farmer` to receive traceback error.

**Expected behavior**
Wallet should connect and shouldn't receive traceback error.

**Additional context**
I've switched to the CLI after my GUI gets stuck loading any time I've tried to re-open it after the initial installation. The initial installation is the only time chia has seemed to work properly to me. When the GUI was working I plotted a k-33 plot that successfully finished plotting and a k-34 plot that never finished. I have since deleted the k-34 but still run into this same issue.

**Comment by zdoehling** [comment]
I'm having the same issue. Commenting here to follow up if someone finds a solution.

**Comment by DonielMoins** [comment]
Same issue here

**Comment by DonielMoins** [comment]
I am having the same issue here. Please help.

**Comment by holdenprkr** [comment]
Hey guys, I found this fix for reloading the GUI in issues here. It is the following:

> Kill process or reloading PC;
Delete these folders:
"C:\Users\ !yourusername!\ .chia"
"C:\Users\ !yourusername!\AppData\Local\chia-blockchain"
"C:\Users\ !yourusername!\AppData\Roaming\Chia Blockchain"
Restart Chia app

Weird thing to me was that I wasn't able to 'Restart Chia app' but I just ran my 1.1.4 exe to install again and it opened my GUI believe it or not. Better yet I'm not receiving this traceback error and my wallet connects in the CLI now. The only thing I'm afraid of is that someone said they weren't able to sync after doing this but have only seen this once. Unfortunately I'm fairly busy at the moment so I'll give an update when available.

**Comment by holdenprkr** [comment]
Ok I will add now, that I'm running into a syncing error it seems. In the CLI, if I run `chia show -s` I receive this error:

> Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up

I believe my node is not still starting up, but it seems that recently a lot of people are having syncing issues so I'm going to leave this ticket open for the time being as I'm still unable to farm and could very well be related.

**Comment by corner22** [comment]
I'm getting the exact same error with chia start farmer. windows 10, v1.1.4 of chia

**Comment by jhoglin** [comment]
One solution is to stop everything, backup your .chia folder, chia init so you get new stuff. I don't know how to restore the wallet using your words from the  cli so using the gui I recover using the secret words. Shut everything down again, copy the database files from your backup to the new .chia folder. Start everything again and you should have a short time to complete sync and both wallet and farmer should work again.

I know this is not a solution but its a work around the problem. This worked nice for me so I don't have this issue anymore.

**Comment by corner22** [comment]
> One solution is to stop everything, backup your .chia folder, chia init so you get new stuff. I don't know how to restore the wallet using your words from the cli so using the gui I recover using the secret words. Shut everything down again, copy the database files from your backup to the new .chia folder. Start everything again and you should have a short time to complete sync and both wallet and farmer should work again.
> 
> I know this is not a solution but its a work around the problem. This worked nice for me so I don't have this issue anymore.

Thanks @jhoglin That worked for me :-) I didn't need to recover wallet keys as they were still present after chia init.  For others reading this, to be clear about which database folder you copy back from your backup copy - it is ~\.chia\mainnet\db and NOT ~\.chia\mainnet\wallet\db
