### ISSUE TITLE
Found  proofs , but no chia  win??

### ISSUE THREAD

**Issue by jonny77** [Chia-Network/chia-blockchain#4145]
2021-05-05T17:47:36.613 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming cd930260e9… Found 1 proofs. Time: 0.43085 s. Total 65 plots

 about 20 logs like above  ,  bu no chia win , so what's wrong ??

**Comment by jonny77** [comment]
how many proofs should i have , to win a chia?

**Comment by mariano54** [comment]
This is normal. Check the FAQ for reasons why this might happen

**Comment by jonny77** [comment]
> This is normal. Check the FAQ for reasons why this might happen

> This is normal. Check the FAQ for reasons why this might happen

thanks for your help , and  I read the FAQ page, as you can see , it just cost 0.43085 s, so it is not due to network . and this happened for many times(>=20) . I can not figure out the reason

**Comment by achalkov** [comment]
check #3141
most likely you farming into wrong reward address

**Comment by x1957** [comment]
> > This is normal. Check the FAQ for reasons why this might happen
> 
> > This is normal. Check the FAQ for reasons why this might happen
> 
> thanks for your help , and I read the FAQ page, as you can see , it just cost 0.43085 s, so it is not due to network . and this happened for many times(>=20) . I can not figure out the reason

Do you resolve the problem? I have the same issue.

**Comment by seertenedos** [comment]
same issue but only 1 plot. that said i am running the same private key/farm keys with different plots in 2 locations. Nothing says that should cause an issue as it is different public ip and internet connections but does make me wonder now i have noticed this
