### ISSUE TITLE
Connecting to wallet

### ISSUE THREAD

**Issue by hayallerde** [Chia-Network/chia-blockchain#4148]
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/skvin/AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

What is problem ?

![image](https://user-images.githubusercontent.com/82336836/117526511-5c347e80-afce-11eb-9b15-42686c362731.png)

**Comment by ssucnj** [comment]
Same situations..;

**Comment by gregoriob** [comment]
ditto.
It appears plotting is running still but I would expect them to have finished by now. Can't kill it as it stops plotting... is this going to be fixed sometime soon? V1.1.4 maybe?

**Comment by Kusey86** [comment]
delete c:/users/username?/.chia 
and re-install miner.
It will go

**Comment by gregoriob** [comment]
> delete c:/users/username?/.chia 
> 
> and re-install miner.
> 
> It will go

And not kill the plotting?

**Comment by hoonkai** [comment]
Same. OSX 10.13.6.

**Comment by hayallerde** [comment]
Thank you for your answers. I provided the solution by deleting all the files.
