### ISSUE TITLE
Cancel button on Plotting tab unexpected behavior

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain#415]
steps to reproduce

1. be plotting (in my case k=32)
2. press Cancel button
3. result: no immediate response, after a little while you get the spinner of death and the text "Connecting to wallet"

**Expected behavior**

Expected: plotting to cancel in a more normal way

Please put a confirmation dialog here as I discovered the problem when I accidentally pressed the button

**Desktop (please complete the following information):**

Windows 10 Pro
Chia Blockchain 1.0 beta 13

**Comment by seeden** [comment]
Confirmation dialog added https://github.com/Chia-Network/chia-blockchain/pull/545

**Comment by ordtrogen** [comment]
When can I test it? Beta 18 or later?

**Comment by hoffmang9** [comment]
It will be in the new consensus release which will be either beta 19 or beta 20. Out within in the next 7-10 days.

**Comment by hoffmang9** [comment]
Try Beta 21 - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta21
