### ISSUE TITLE
How to delete future plots on same queue in GUI?

### ISSUE THREAD

**Issue by vvavepacket** [Chia-Network/chia-blockchain#4150]
So lets say I added 3 plots in parallel to queue 1.. now how can i add a plot to the same queue where it will not plot immediately but instead will wait for some time?

Currently if i add a plot to the same queue it starts immediately.. how can I make it either:

1. Start after all the plotting is done on that queue
2. Start after some delay

This is done using the GUI

**Comment by cracker0dks** [comment]
I think you can't. Just start normal plotting 3 times (with plot count of more then 1) and a different queue Name each (Advanced option). Then you have 3 plotters parallel with queue.
