### ISSUE TITLE
How to group three PC plotting together 

### ISSUE THREAD

**Issue by crazyhei82** [Chia-Network/chia-blockchain#4151]
If I have 3 pc both login same 24 words

It is mean all.the plotting space will gp together. 

Or what should I do to make sure all plotting space will migrate together?

3 PC plotting put inside the same Nas together .

I have check all the public key is the same ..

please advice ~

**Comment by r1235613** [comment]
Just save plot file to same place.

**Comment by crazyhei82** [comment]
if i have 2 pc for Chia PC .

1 at office 1 at in home,If i copy all the farming  from office and import to the  one at home

Can I need to keep the farming  in office or just deleted it ok ?

I am very confuse have the farming .

If i keep both have use or not ?
