### ISSUE TITLE
Installation from sources fails on Debian

### ISSUE THREAD

**Issue by durdin85** [Chia-Network/chia-blockchain#4152]
**Describe the bug**
The installer scripts install.sh, activate and install-gui.sh have built in checks for detecting ubuntu and Debian.
On Ubuntu, the lsb_release -rs returns number, however on Debian it returns string, like "stable", "testing", "wheezy" etc.. and same is valid for python-based check on the install GUI. This breaks the script and on Debian it fails to install.

**To Reproduce**

1. Follow the install guide on https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian
2. Failure on running install.sh and install-gui.sh

**Expected behavior**
Installation should succeed

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Debian testing
- CPU: x86_64

**Additional context**
The Debian testing is similar to latest Ubuntu, so changing script so it thins it is on Ubuntu >2100 on Debian testing solves the problem. Also it could be solved by manually removing the checks entirely and keeping only Debian related parts, but this is not what to expect on normal installer behaviour (just workaround for someone installing).

**Comment by elarkasi** [comment]
plotting on debian10.9.  and everything looks fine.
you have to provide more detail about the error you encountered.

**Comment by durdin85** [comment]
problem is with this part, where all Debian flavours would be treated as ubuntu pre 2004:
```
 LSB_RELEASE=$(lsb_release -rs)
....
 UBUNTU_PRE_2004=$(echo "$LSB_RELEASE<20" | bc)
 UBUNTU_2100=$(echo "$LSB_RELEASE>=21" | bc)


$ echo $UBUNTU_PRE_2004
1
$ echo $UBUNTU_2100
0
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```

which results in attempt of install python 3.7 related things:
```
...if [ "$UBUNTU" = "true" ] && [ "$UBUNTU_PRE_2004" = "1" ]; then
                # Debian/Ubuntu
                echo "Installing on Ubuntu/Debian pre 20.04 LTS"
                sudo apt-get update
                sudo apt-get install -y python3.7-venv python3.7-distutils
```

This might not be a problem in case of older Debian where python3.7 is default, or on system where the two above packages are already installed.
But as the above packages were not installed  on my system starting python venv failed which failed entire install.

```
$ dpkg -l python3
ii  python3        3.9.2-3 
```

Debian testing is basically on ubuntu 21.00 level. 
Btw on my system meta package 'python-venv' exist which always points to correct version, so no need to do version detect. 


There's similar issue on the gui install script, but this time the detection is not done via calling bc to eval, but using python running lsb_release:
```
$ python3 -c 'import subprocess; process = subprocess.run(["lsb_release", "-rs"], stdout=subprocess.PIPE); print(float(process.stdout) < float(20.04))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: could not convert string to float: b'testing\n'
```
btw there's lsb_release module in python3 already, so no need to exec any extra commands:
```
>>> import lsb_release
>>> (ver,linux,id) = (lsb_release.get_distro_information()[x] for x in ['RELEASE', 'OS', 'ID'])
>>> if id == 'Debian' and isinstance(ver, float):
...     print('Debian {}'.format(ver))
... else:
...     print('Debian non-numeric {}'.format(ver))
... 
Debian non-numeric testing
>>> 
```

**Comment by N0rdmann** [comment]
Same here on Debian Bullseye/testing, commenting out the quoted if clause for UBUNTU_PRE_2004 = 0 "fixes" the issue

**Comment by mmu-acid21** [comment]
same problem in the install-gui.sh - hasnt been fixed yet...

**Comment by gnaaromat** [comment]
same problem in the install-gui.sh - hasnt been fixed yet...
