### ISSUE TITLE
[BUG] Plotting always crashes at 12-13%

### ISSUE THREAD

**Issue by Pwet1** [Chia-Network/chia-blockchain#4155]
I am plotting parallel with standard settings (bitfield plotting enabled), but at 12-13% it always crashes with a message like this 

"Only read 261770 of 262134 bytes at offset 419676534 from "G:\\Plotting\\plot-k32-2021-05-07-21-53-4ef64b836011239bb8a948b5821e5a401a3cb2992b08c5376f8322ec38506858.plot.p1.t2.sort_bucket_107.tmp"with length 604067040. Error 1. Retrying in five minutes."  

It started to happen since I use a SSD, before I plotted on the HDD only, but that is way too slow.

- OS: Windows 10
- CPU: i7 4790K
- Ram: 16GB ddr3
- SSD: 1TB WD red SA500 NAS
- HDD: 10TB Seagate external Storage

**Comment by FlavioCimetta** [comment]
Hi, I don't have too much experience, but I had almost the same issue.
Try the follow:

- Attention to computer's sleep mode. If Pc enters this mode, the plotting will stop, and you will have to restart.
- Try to use default plott settings, not in parallel. (2 threads, with 4500 RAM)
- If you use this PC for another thing when plotting, I mean, something that uses too much RAM, or something that uses spikes of RAM, the plotting proccess will crash also.

Well, I don't have too much experience, and maybe the solution for this error will not come doing this at all, but i'm just talking about my issue, and the way I did to fix it. 
Just trying to help, please feedback us.

Good day.

**Comment by grinbucks** [comment]
I had the same issue in 2 different cases.

The first one was due to SSD not having enough free space.

The second case was the SSD showing abnormal average response time (>500ms) before became unaccessible by windows (a device which does not exist specified error). I still haven't found any solution for this. For now I suspect the motherboard (old B250) is the culprit.

**Comment by Pwet1** [comment]
I have tried that all now, and still have the same issue. No RAM spikes, enough space on the SSD, and normal response times for both SSD and HDD.
It weirdly only happens when I use my SSD to plot and my HDD to store, the HDD starts to make rumbling noises and the plotting is for the bin. (each one separately works fine)

**Comment by munitech4u** [comment]
I am experiencing similar issue. I have ~327 temp files created in SSD occupying 304GB, using plot size (k=32). About 20 files are empty. I assume the rest are useless, unless they can be resumed(a functionality which I guess would be added later this year). 
Happened couple of times, even tried the options above
: 1. Adding plot to queue 2. putting computer to never sleep 3. no other heavy process is running. 

Any ideas for the workarounds? I am giving up for now :(

**Comment by runxcode** [comment]
> I am plotting parallel with standard settings (bitfield plotting enabled), but at 12-13% it always crashes with a message like this
> 
> "Only read 261770 of 262134 bytes at offset 419676534 from "G:\Plotting\plot-k32-2021-05-07-21-53-4ef64b836011239bb8a948b5821e5a401a3cb2992b08c5376f8322ec38506858.plot.p1.t2.sort_bucket_107.tmp"with length 604067040. Error 1. Retrying in five minutes."
> 
> It started to happen since I use a SSD, before I plotted on the HDD only, but that is way too slow.
> 
> * OS: Windows 10
> * CPU: i7 4790K
> * Ram: 16GB ddr3
> * SSD: 1TB WD red SA500 NAS
> * HDD: 10TB Seagate external Storage

Perhaps there's a failure in SSD at specific storage location because of hardware wear-out/defect? Maybe try to reformat the SSD, but of course don't forget to move/backup your important data on that SSD.

**Comment by Pwet1** [comment]
> > I am plotting parallel with standard settings (bitfield plotting enabled), but at 12-13% it always crashes with a message like this
> > "Only read 261770 of 262134 bytes at offset 419676534 from "G:\Plotting\plot-k32-2021-05-07-21-53-4ef64b836011239bb8a948b5821e5a401a3cb2992b08c5376f8322ec38506858.plot.p1.t2.sort_bucket_107.tmp"with length 604067040. Error 1. Retrying in five minutes."
> > It started to happen since I use a SSD, before I plotted on the HDD only, but that is way too slow.
> > 
> > * OS: Windows 10
> > * CPU: i7 4790K
> > * Ram: 16GB ddr3
> > * SSD: 1TB WD red SA500 NAS
> > * HDD: 10TB Seagate external Storage
> 
> Perhaps there's a failure in SSD at specific storage location because of hardware wear-out/defect? Maybe try to reformat the SSD, but of course don't forget to move/backup your important data on that SSD.

The SSD is completely new, and I bought it only for it to plot, there is nothing else on it and as i said both work separately  on their own just fine.

Anyway, thank you all for your help so far!
