### ISSUE TITLE
Connecting to Wallet but nothing happens. (HELP pls)

### ISSUE THREAD

**Issue by MagicRoss7** [Chia-Network/chia-blockchain#4167]
**Describe the bug**
I am running Chia on my MacBook Air.
My wallet screen constantly says connecting to wallet but nothing happens after that.

I am running the latest Chia software.

![Screenshot 2021-05-08 at 5 03 51 PM](https://user-images.githubusercontent.com/83862485/117533432-62068000-b01f-11eb-846d-b24152998b5a.png)

Any help?

**Comment by davidkoid** [comment]
Same here...and plotting k35 halfway
if restart might waste the time and efford

**Comment by pokerci** [comment]
![chia fail](https://user-images.githubusercontent.com/82796942/117535644-658a0f00-afff-11eb-80ed-2e67eb0e538a.png)

same problem on w10 using all my memory 5x restart machine nothing happens

**Comment by hzcm123** [comment]
Same issue on my MacBook Pro and iMac.

**Comment by Berlin1907** [comment]
Same problem since yesterday...
