### ISSUE TITLE
Chia won't sync

### ISSUE THREAD

**Issue by mitchkuilder** [Chia-Network/chia-blockchain#4169]
everytime i open chia the syncing progress won't go any further that this.
is there a way to fix this issue ?

kind regards, 
Mitch

![image](https://user-images.githubusercontent.com/56294526/117533797-06bc9980-afef-11eb-8185-9cf93b53c781.png)

**Comment by Fudnut** [comment]
Having exactly the same issue. Was working fine for last month 24/7, rebooted and now sync is stuck. I know of others having same issue too.

**Comment by cracker0dks** [comment]
You both have port 8444 TCP forwarded to your machine?
From the readme: `If you are behind a NAT, it can be difficult for peers outside your subnet to reach you when they start up. You can enable UPnP on your router or add a NAT (for IPv4 but not IPv6) and firewall rules to allow TCP port 8444 access to your peer. These methods tend to be router make/model specific.`
This works great on my end.

**Comment by Fudnut** [comment]
Yes. As I wrote, it's been working 24/7 until I re-booted.  It's not moved off the  Syncing 249165 in hours. When I can node IP's the 2nd half i.e. total blocks updates, just not  my Db
https://gyazo.com/16e6ecd4eb28eb52dc78d84db7512b4a

Other are having the same issues with very slow or nil synching as above. I'm in Australia, so not sure if a network connectivity thing, but doesn't appear to be.

**Comment by cracker0dks** [comment]
Have you tried to connect to one of the peers here https://chia.keva.app/  manually? Maybe this helps.

**Comment by cracker0dks** [comment]
You also saw this then?: https://github.com/Chia-Network/chia-blockchain/issues/2271#issuecomment-827251187

**Comment by Fudnut** [comment]
> 
> 
> You also saw this then?: [#2271 (comment)](https://github.com/Chia-Network/chia-blockchain/issues/2271#issuecomment-827251187)

yes, they were on my list.

**Comment by cracker0dks** [comment]
hardcore... do you have set the correct time (timezone) on your pc?

**Comment by Fudnut** [comment]
> 
> 
> hardcore... do you have set the correct time (timezone) on your pc?

yes, that's ok. I appreciate you trying to help

**Comment by meesterdude** [comment]
i am here trying to resolve a sync issue as well. everything was fine up until now - this must be a network issue because it doesn't make sense for so many people to have the same issue all of a sudden otherwise.

**Comment by goliad13** [comment]
I have the same issue.

**Comment by Fudnut** [comment]
Still no sync, and appears no one has any idea what the issue is

**Comment by cracker0dks** [comment]
Try this: https://github.com/Chia-Network/chia-blockchain/issues/4211

**Comment by Fudnut** [comment]
Thnaks, still not synching. debug-log shows it's connected https://gyazo.com/1bf551c4cb918891936a967a2073bf11

**Comment by Fudnut** [comment]
> 
> 
> Try this: #4211

Tried that and it's synced 768/251750 and stalled. debug log shows this error. Any clue? https://gyazo.com/ad93747f221a69eabf2bc0fa5b1cb20f

**Comment by Fudnut** [comment]
> 
> 
> > > Try this: #4211
> > 
> > 
> > Tried that and it's synced 768/251750 and stalled. debug log shows this error. Any clue? https://gyazo.com/ad93747f221a69eabf2bc0fa5b1cb20f
> 
> updated debug log https://gyazo.com/35f59200baeee1e5f7581998b2999dbe

finally synched, after nearly 24 hrs

**Comment by ashlend1** [comment]
hello Everyone, same issue here, stuck at height 257595, not sync
