### ISSUE TITLE
[BUG] Timelord can't find vdf_client library after starting services

### ISSUE THREAD

**Issue by npalamar** [Chia-Network/chia-blockchain#4172]
Hi! I had an error when started services. It appears after several seconds after start (FileNotFoundError: can't find vdf_client binary). Also I've checked library in pip and all looked fine.

```
$ (venv) d@desktop: chia start all
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
$ (venv) d@desktop:~/chia-blockchain$ Traceback (most recent call last):
  File "/home/npalamar/chia-blockchain/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/home/npalamar/chia-blockchain/chia/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/npalamar/chia-blockchain/chia/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/home/npalamar/chia-blockchain/chia/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/home/npalamar/chia-blockchain/chia/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary
```

**Comment by dicoolx** [comment]
I have the same issue on Ubuntu Desktop 20.04 LTS

**Comment by colinwebber** [comment]
+1 Ubuntu Server 20.04 LTS chia v1.1.4

Can't start up at all due to this issue. Tried, node, farmer, wallet in isolation - none start.

@npalamar I got it running by following the upgrade process here: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian
Make sure you're using 'latest' branch not 'main'

**Comment by lvcivs** [comment]
The command `chia start all` with attempt to start everything, including a timelord. You most likely don't want to run a timelord, as it is an advanced use case. Use `chia start farmer` instead.

**Comment by francocores** [comment]
Hello,
It solves it like this:

1- Backup the folder .chia -> .chia-bkp

2- Reinstall CHIA (without starting)
`sudo apt-get update
sudo apt-get upgrade -y

# Install Git
sudo apt install git -y

# Checkout the source and install
git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
cd chia-blockchain

sh install.sh

. ./activate

# The GUI requires you have Ubuntu Desktop or a similar windowing system installed.
# You can not install and run the GUI as root

chmod +x ./install-gui.sh
./install-gui.sh`

3- Launch chia init command

4- Copy from .chia-bkp / mainnet / db to .chia / mainnet / db

5- Start CHIA
`. ./activate
chia init
cd chia-blockchain-gui
npm run electron &`

**Comment by SoMoney** [comment]
Those of us running swar or plotmanager don't want anything to do with chia-blockchain-gui
