### ISSUE TITLE
[help]8444 is not open, but it is already in sync. Can you get block reward?

### ISSUE THREAD

**Issue by uwerui** [Chia-Network/chia-blockchain#4173]
8444 is not open, but it is already in sync. Can you get block reward?

**Comment by cracker0dks** [comment]
Yes, should be no problem. Check if you see "last Attempted Proof" `date` with the current time.
![image](https://user-images.githubusercontent.com/1816621/117550605-88d5ae00-b041-11eb-993d-beb5009a9f86.png)
And once in a while you should see a "plots passed filter" `(1 or more) / "your plot count"` Like the 2/212 in the screenshot.

**Comment by uwerui** [comment]
> 是的，应该没问题。检查`date`当前时间是否看到“上次尝试证明” 。有时 您应该会在屏幕截图中看到类似“ 2/212 ”的“曲线通过过滤器” 。
> ![图像](https://user-images.githubusercontent.com/1816621/117550605-88d5ae00-b041-11eb-993d-beb5009a9f86.png)
> `(1 or more) / "your plot count"`

Have you ever received any rewards?

**Comment by cracker0dks** [comment]
Yes

**Comment by uwerui** [comment]
> 是的

How many?
