### ISSUE TITLE
4 plots have taken me a week  - what have I done wrong?

### ISSUE THREAD

**Issue by Dominus-Nox** [Chia-Network/chia-blockchain#4179]
Hi,

I have a new B550 board with a Ryzen 5 3600 and 32GB of RAM. My plot drive is a Corsair M600 M2 and my storage drive is a 12gB Ironwolf. My OS is Windows 10 and I have decent broadband.

I installed Chia and set to default to create 4 plots, but it's averaging around 12-15% a day with the machine left on. Is it supposed to take that long? I only use my pc for college work so there isn't much else going on. The plot drive shows as maxed out in windows - can I do anything to fix it please? Any help would be great!

**Comment by cracker0dks** [comment]
Should be more of 2-3 per day with your equipment (k=32 blocks). What does the task-manager say about read/write speed of the ssd when maxed out?

**Comment by Dominus-Nox** [comment]
Thanks for the reply - I've checked the task manager and it's showing as more or less nothing going on
![SSD Task Manager](https://user-images.githubusercontent.com/83859390/117546185-1fde3e00-b021-11eb-84a6-c357e9b953d3.png)

**Comment by cracker0dks** [comment]
mmm I thought it is "maxed out" in windows? Can you show the log for the plot you try to create?
![image](https://user-images.githubusercontent.com/1816621/117550170-1a8fec00-b03f-11eb-93ad-f2836b4a5710.png)

**Comment by michael-trinity** [comment]
It shouldn't take that long for sure, I have a 3800x, with a Samsung 980 pro (2tb), and I plot 6 in parallel and can do about 12 a day.
The only reason mine stops is if the drive is full (happened because I wasn't paying attention selecting the drive)

**Comment by Dominus-Nox** [comment]
Okay here's the log 
![SSD Log](https://user-images.githubusercontent.com/83859390/117552617-727d2180-b044-11eb-9beb-a08fa35e81be.png)

**Comment by michael-trinity** [comment]
It means your drive is full yes, each plot (k-32) takes ~240GB of space, but if you quit the program the old .tmp files will still be there taking up space.

if you have a 1TB drive, that is more like 0.9TB. 4x240GiB = 960GiB, which means it exceeds the drive's capacity.
