### ISSUE TITLE
[BUG] Connecting To Wallet while plotting ...

### ISSUE THREAD

**Issue by Boulhech** [Chia-Network/chia-blockchain#4187]
I'm trying to use chia to farm on my laptop and it's been 24 hours that I'm trying to create a plot.
After a while a message saying "Connecting To Wallet" appears from no where and doesn't go and to go back to plotting I need to close the program
and re-open it to start the process all over again

My Laptop Specs :
 CPU : i3-4005U
Ram : 4GB
500 GB HDD
Is there any problem with my laptop ?

**Comment by tksalarzai** [comment]
> I'm trying to use chia to farm on my laptop and it's been 24 hours that I'm trying to create a plot.
> After a while a message saying "Connecting To Wallet" appears from no where and doesn't go and to go back to plotting I need to close the program
> and re-open it to start the process all over again
> 
> My Laptop Specs :
> CPU : i3-4005U
> Ram : 4GB
> 500 GB HDD
> Is there any problem with my laptop ?

SAME PROBLEM WITH ME , i have to close and restart the app again to get it started

**Comment by gpsrai09** [comment]
I'm trying to use chia to farm on my laptop and it's been 24 hours that I'm trying to create a plot.
After a while a message saying "Connecting To Wallet" appears from no where and doesn't go and to go back to plotting I need to close the program
and re-open it to start the process all over again

same problem with me too 
i have 2 desktop with LAN connection both facing above problem.
PLEASE SOLVE IT THANKS

**Comment by Boulhech** [comment]
> I'm trying to use chia to farm on my laptop and it's been 24 hours that I'm trying to create a plot.
> After a while a message saying "Connecting To Wallet" appears from no where and doesn't go and to go back to plotting I need to close the program
> and re-open it to start the process all over again
> 
> same problem with me too
> i have 2 desktop with LAN connection both facing above problem.
> PLEASE SOLVE IT THANKS

I saw a YouTube video where it said we should wait to get synced before ploting and I don't really know so if someone tried with the chia synced let me know TY 😁

**Comment by AlexArzon** [comment]
SAME PROBLEM WITH ME , Connecting To Wallet" appears from no where and doesn't go and to go back to plotting 
![Screen Shot 2021-05-06 at 6 32 43 PM](https://user-images.githubusercontent.com/83790857/117547294-e85d9a80-affc-11eb-9b7e-af44783a4174.png)

**Comment by yuzhongrong** [comment]
me to
