### ISSUE TITLE
[REQ] Remember folders

### ISSUE THREAD

**Issue by luotinen** [Chia-Network/chia-blockchain#4189]
On the Chia Blockchain 1.1.4 Windows GUI:
Once the user has set the temporary (and 2nd temporary) and permanent folders, the GUI should remember those and use the last folder as a default. This way the user does not have to re-enter the same directory over and over again but if the folder has changed it can be changed when needed.

**Comment by Gnomuz** [comment]
Fully agreed, browsing the temp and destination folders each time a plot is to be launched is a real pain, after a while
