### ISSUE TITLE
Endless wallet connection [BUG]

### ISSUE THREAD

**Issue by Flaberik** [Chia-Network/chia-blockchain#4191]
Describe the bug
Endless wallet connection. Restarting doesn't help.

To Reproduce
Plated for the night.
The ssd was full, the unfinished rafts had to be removed.
Now, when you try to open the chia blockchain, it hangs on the "connect to the wallet" page

Expected behavior
Connect and re-plot

Desktop (please complete the following information):

OS: windows 10
CPU: rayzen 5 2600
RAM 16 gb 2400

**Comment by tksalarzai** [comment]
> Describe the bug
> Endless wallet connection. Restarting doesn't help.
> 
> To Reproduce
> Plated for the night.
> The ssd was full, the unfinished rafts had to be removed.
> Now, when you try to open the chia blockchain, it hangs on the "connect to the wallet" page
> 
> Expected behavior
> Connect and re-plot
> 
> Desktop (please complete the following information):
> 
> OS: windows 10
> CPU: rayzen 5 2600
> RAM 16 gb 2400

same is the problem with me , when i press reload or force reload it just goes on "connecting wallets" loading screen forever

**Comment by arepeace82** [comment]
Similar issue keep connecting,  have tried reinstall  - Clean all cache and temp file ( similar keep connecting )

**Comment by eymenkose** [comment]
i have same problem

**Comment by HelloNetWorld** [comment]
I FOUND SOLUTION: 
1) Kill process or reloading PC;
2) Delete these folders:
C:\Users\<username>\.chia
C:\Users\<username>\AppData\Local\chia-blockchain
C:\Users\<username>\AppData\Roaming\Chia Blockchain
3) Restart Chia app

**Comment by arepeace82** [comment]
Thanks bro for the solution it works for me

**Comment by karmakan** [comment]
> I FOUND SOLUTION:
> 
> 1. Kill process or reloading PC;
> 2. Delete these folders:
>    "C:\Users\ !yourusername!\ .chia"
>    "C:\Users\ !yourusername!\AppData\Local\chia-blockchain"
>    "C:\Users\ !yourusername!\AppData\Roaming\Chia Blockchain"
> 3. Restart Chia app

Thanks you bro! well done

**Comment by spodee4** [comment]
Didn't work for me, endless 'syncing - - -  not syncing' problem for me
