### ISSUE TITLE
[BUG] XCH LOST when giving 0 fee for transaction 

### ISSUE THREAD

**Issue by zxc00747** [Chia-Network/chia-blockchain#4192]
SOLVED!
@pokerface0206
@JsBlueCat

After I installed chia GUI on another computer and restore backup with men-words.
When the wallet is synced the amount is back.
Looks like the 0 fee transaction was canceled and returned to the wallet.
![image](https://user-images.githubusercontent.com/31769399/117570369-63f24100-b0fc-11eb-9b0b-f93f7cf59ae4.png)

**Describe the bug**
Try to send XCH to another wallet and marked 0（zero) for the fee, and the transaction is pending forever.

**To Reproduce**

1. Go to 'wallets'
2. Create transaction by fill in the address and amount, and 0 (zero) for fee
3. the transaction goes pending forever

**Screenshots**

![image](https://user-images.githubusercontent.com/31769399/117540481-4cef1880-b042-11eb-8317-5143b1b7df95.png)

**Desktop (please complete the following information):**

- OS: windows 10
- OS Version/Flavor: 20H2
- CPU:  Intel 9900k

**Comment by pokerface0206** [comment]
I have the same problem as you ！！！    I started the transfer on May 1st, and it's still here.

**Comment by pokerface0206** [comment]
If you solve this problem, please tell me the way.

**Comment by JsBlueCat** [comment]
same as this problem 

```
2021-05-08T21:51:40.275 wallet chia.wallet.wallet         : WARNING  Record: {'additions': [{'amount': 6000000000000,
                'parent_coin_info': '0x07fe3377dd2b136756ee1b1b06312f2d8d292e5b35999eef552193ad6b11a330',
                'puzzle_hash': '0x6db78f43976c8661ec9ee4be9fbb458492831875c8ae42d8b23bcded5f1659cb'},
               {'amount': 1000000000000,
                'parent_coin_info': '0x07fe3377dd2b136756ee1b1b06312f2d8d292e5b35999eef552193ad6b11a330',
                'puzzle_hash': '0x3317da6153eb1840f5197dfdba6003405b47cafaaa9e35431468b2ffc7fd46b1'}],
 'amount': 6000000000000,
 'confirmed': False,
 'confirmed_at_height': 0,
 'created_at_time': 1620476245,
 'fee_amount': 0,
 'name': '0xadb082d85327cc8c3ec93904ec77a0ee1e985e7e425f6056fb69a36b3ae04238',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001f0fe',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
              {'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000033c98',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
              {'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000002e8b',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
              {'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001287b',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'}],
 'sent': 0,
 'sent_to': [],
 'spend_bundle': {'aggregated_signature': '0xa30e5a06b77d8d4c264e00d25d0b5c006c3693a64f69c116c54ba23f015f642bd56f316bbcaefa7bc56a1f231f2b2a4d057d0ae0de4e05f4182ee121010129c24e87f0b5b7de5bee46c2d6a1473d0e910486fd37a145efdd1f1b641b8b320328',
                  'coin_solutions': [{'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001f0fe',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff33ffa06db78f43976c8661ec9ee4be9fbb458492831875c8ae42d8b23bcded5f1659cbff860574fbde600080ffff33ffa03317da6153eb1840f5197dfdba6003405b47cafaaa9e35431468b2ffc7fd46b1ff8600e8d4a5100080ffff3cffa040d5732b7f89da07e01880c803759d9132f9112a7a69cc061079764f5a988b518080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000033c98',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff3dffa03d2cab7e8ce7532ba18cb9d252e142a1d5c2a8fe8399a8acecf70d8c044ac8db8080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000002e8b',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff3dffa03d2cab7e8ce7532ba18cb9d252e142a1d5c2a8fe8399a8acecf70d8c044ac8db8080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001287b',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff3dffa03d2cab7e8ce7532ba18cb9d252e142a1d5c2a8fe8399a8acecf70d8c044ac8db8080ff8080'}]},
 'to_puzzle_hash': '0x6db78f43976c8661ec9ee4be9fbb458492831875c8ae42d8b23bcded5f1659cb',
 'trade_id': None,
 'type': 1,
 'wallet_id': 1} not in mempool
2
```

**Comment by zxc00747** [comment]
tried restart the computer. The same problem.  
It looks like  the XCH pending is lost forever.
It is just ridiculous that such a minimal mistake like a transaction with zero fee will just banish the XCH forever

**Comment by JsBlueCat** [comment]
> tried restart the computer. The same problem.
> It looks like the XCH pending is lost forever.
> It is just ridiculous that such a minimal mistake like a transaction with zero fee will just banish the XCH forever

agree ， but even if i restart my compute, and i do any thing i could do , i don't find any way to cancel the dead transactions.

dame it! fuck xch

**Comment by zxc00747** [comment]
> > tried restart the computer. The same problem.
> > It looks like the XCH pending is lost forever.
> > It is just ridiculous that such a minimal mistake like a transaction with zero fee will just banish the XCH forever
> 
> agree ， but even if i restart my compute, and i do any thing i could do , i don't find any way to cancel the dead transactions.
> i don't know start another transaction may do a favor?? but i affread to that , it may cause another xch lock.
> i have try 1.1.4 amd 1.1.5.dev1
> dame it! fuck xch @richardkiss @wbendick @sargonas @snikch @AdrianScott

Did you try to delete the wallet database and sync again?

**Comment by zxc00747** [comment]
> If you solve this problem, please tell me the way.

have you tried any solutions?

**Comment by pokerface0206** [comment]
> > 如果您解决了这个问题，请告诉我方法。
> 
> 您尝试过任何解决方案吗？

I've tried almost everything except delete wallet and import it again. This may be a good idea. If still fails, it may have to wait for the official solution. I hope this problem can be seen by Chia developers

**Comment by variableresults** [comment]
I see this as both a bug and an enhancement. 

There isn't any current cryptocurrency that I'm aware of where you can have free transactions. They all have a fee (or "gas") to make it worthwhile for the transaction processors' time. With ETH, the higher the fee you're willing the pay, the faster you can have your transaction processed. But in no world would you enter 0 for your transfer fee.

What should be probably be the enhancement side is the Chia network needs to calculate a reasonable fee based on the overall liquidity and market forces, similar to how BTC and ETH do it. It should be telling you what the minimum fee is to process your transaction, and not allowing you to go below that fee, but also allowing you to offer a higher fee to get your transaction processed faster. 

If the mainnet is operating well (which it should be with the ever increasing storage & plotting), then fees should by the nature of market forces be very low. If it's not, we'll see the sort of issues that ETH and BTC have had when it wasn't worth mining them on POW, where low-fee transactions would take forever to process due to the lack of miners to validate them. 

The bug, on the other hand, is that the code shouldn't ever allow you to enter "0" for a fee--it should error out. And the devs need to find a way to process any stale transactions given that XCH is now worth >$1000 per token, otherwise we can't say that they're operating in good faith (it begs the question--where exactly IS the 0 fee XCH that is stuck and not processed? On the blockchain? If so, how is it recorded in the ledger?).

**Comment by JsBlueCat** [comment]
> > > 如果您解决了这个问题，请告诉我方法。
> > 
> > 
> > 您尝试过任何解决方案吗？
> 
> I've tried almost everything except delete wallet and import it again. This may be a good idea. If still fails, it may have to wait for the official solution. I hope this problem can be seen by Chia develop

can you delete it? and tell us the result?

**Comment by snikch** [comment]
I've had no issues with sending XCH with a 0 fee.

**Comment by JsBlueCat** [comment]
> I've had no issues with sending XCH with a 0 fee.

but since i look through in my log file 

```
2021-05-08T21:51:40.275 wallet chia.wallet.wallet         : WARNING  Record: {'additions': [{'amount': 6000000000000,
                'parent_coin_info': '0x07fe3377dd2b136756ee1b1b06312f2d8d292e5b35999eef552193ad6b11a330',
                'puzzle_hash': '0x6db78f43976c8661ec9ee4be9fbb458492831875c8ae42d8b23bcded5f1659cb'},
               {'amount': 1000000000000,
                'parent_coin_info': '0x07fe3377dd2b136756ee1b1b06312f2d8d292e5b35999eef552193ad6b11a330',
                'puzzle_hash': '0x3317da6153eb1840f5197dfdba6003405b47cafaaa9e35431468b2ffc7fd46b1'}],
 'amount': 6000000000000,
 'confirmed': False,
 'confirmed_at_height': 0,
 'created_at_time': 1620476245,
 'fee_amount': 0,
 'name': '0xadb082d85327cc8c3ec93904ec77a0ee1e985e7e425f6056fb69a36b3ae04238',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001f0fe',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
              {'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000033c98',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
              {'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000002e8b',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
              {'amount': 1750000000000,
               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001287b',
               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'}],
 'sent': 0,
 'sent_to': [],
 'spend_bundle': {'aggregated_signature': '0xa30e5a06b77d8d4c264e00d25d0b5c006c3693a64f69c116c54ba23f015f642bd56f316bbcaefa7bc56a1f231f2b2a4d057d0ae0de4e05f4182ee121010129c24e87f0b5b7de5bee46c2d6a1473d0e910486fd37a145efdd1f1b641b8b320328',
                  'coin_solutions': [{'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001f0fe',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff33ffa06db78f43976c8661ec9ee4be9fbb458492831875c8ae42d8b23bcded5f1659cbff860574fbde600080ffff33ffa03317da6153eb1840f5197dfdba6003405b47cafaaa9e35431468b2ffc7fd46b1ff8600e8d4a5100080ffff3cffa040d5732b7f89da07e01880c803759d9132f9112a7a69cc061079764f5a988b518080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000033c98',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff3dffa03d2cab7e8ce7532ba18cb9d252e142a1d5c2a8fe8399a8acecf70d8c044ac8db8080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a00000000000000000000000000002e8b',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff3dffa03d2cab7e8ce7532ba18cb9d252e142a1d5c2a8fe8399a8acecf70d8c044ac8db8080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xccd5bb71183532bff220ba46c268991a0000000000000000000000000001287b',
                                               'puzzle_hash': '0xc4e180cf01d0cff2ab9344f9cb24e8138d3740061c4318da12e77943e712faab'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0b896e5583489d58b80ae42281d729be1c010f4c10ae310be5798e6c668a3873d163a36a49d664ac4c4d07dac1003b8d6ff018080',
                                      'solution': '0xff80ffff01ffff3dffa03d2cab7e8ce7532ba18cb9d252e142a1d5c2a8fe8399a8acecf70d8c044ac8db8080ff8080'}]},
 'to_puzzle_hash': '0x6db78f43976c8661ec9ee4be9fbb458492831875c8ae42d8b23bcded5f1659cb',
 'trade_id': None,
 'type': 1,
 'wallet_id': 1} not in mempool
```
and the wallet will pending the amount ...

how can i cancel this transaction ?

**Comment by zxc00747** [comment]
> I see this as both a bug and an enhancement.
> 
> There isn't any current cryptocurrency that I'm aware of where you can have free transactions. They all have a fee (or "gas") to make it worthwhile for the transaction processors' time. With ETH, the higher the fee you're willing the pay, the faster you can have your transaction processed. But in no world would you enter 0 for your transfer fee.
> 
> What should probably be the enhancement side is the Chia network needs to calculate a reasonable fee based on the overall liquidity and market forces, similar to how BTC and ETH do it. It should be telling you what the minimum fee is to process your transaction in a reasonable amount of time, and not allowing you to go below that fee, but also allowing you to offer a higher fee to get your transaction processed faster.
> 
> If the mainnet is operating well (which it should be with the ever increasing storage & plotting), then fees should by the nature of market forces be very low. If it's not, we'll see the sort of issues that ETH and BTC have had when it wasn't worth mining them on POW, where low-fee transactions would take forever to process due to the lack of miners to validate them.
> 
> The bug, on the other hand, is that the code shouldn't ever allow you to enter "0" for a fee--it should error out. And the devs need to find a way to process any stale transactions given that XCH is now worth >$1000 per token, otherwise we can't say that they're operating in good faith (it begs the question--where exactly IS the 0 fee XCH that is stuck and not processed? On the blockchain? If so, how is it recorded in the ledger?).

A transaction system without any mistake-proofing mechanism to protect your crypto asset is unacceptable. I do hope the dev team notice and solve this flaw.

**Comment by zxc00747** [comment]
> > > > 如果您解决了这个问题，请告诉我方法。
> > > 
> > > 
> > > 您尝试过任何解决方案吗？
> > 
> > 
> > I've tried almost everything except delete wallet and import it again. This may be a good idea. If still fails, it may have to wait for the official solution. I hope this problem can be seen by Chia develop
> 
> can you delete it? and tell us the result?

I deleted the wallet database and now it can’t sync

**Comment by JsBlueCat** [comment]
> > > > > 如果您解决了这个问题，请告诉我方法。
> > > > 
> > > > 
> > > > 您尝试过任何解决方案吗？
> > > 
> > > 
> > > I've tried almost everything except delete wallet and import it again. This may be a good idea. If still fails, it may have to wait for the official solution. I hope this problem can be seen by Chia develop
> > 
> > 
> > can you delete it? and tell us the result?
> 
> I deleted the wallet database and now it can’t sync

i deleted and it is syncing now

**Comment by pokerface0206** [comment]
> > > > > > 如果您解决了这个问题，请告诉我方法。
> > > > > 
> > > > > 
> > > > > 您尝试过任何解决方案吗？
> > > > 
> > > > 
> > > > 除了删除钱包并再次导入外，我几乎尝试了所有其他操作。这可能是一个好主意。如果仍然失败，则可能必须等待官方解决方案。我希望这个问题能被Chia发展看到
> > > 
> > > 
> > > 可以删除吗？告诉我们结果吗？
> > 
> > 
> > 我删除了钱包数据库，现在无法同步
> 
> 我删除了，现在正在同步

I delete the private key and wallet software and download, install and import them again, but the situation remains unchanged, which may be caused by the local cache. I tried to import it on another new computer.

**Comment by zxc00747** [comment]
> > > > > > > 如果您解决了这个问题，请告诉我方法。
> > > > > > 
> > > > > > 
> > > > > > 您尝试过任何解决方案吗？
> > > > > 
> > > > > 
> > > > > 除了删除钱包并再次导入外，我几乎尝试了所有其他操作。这可能是一个好主意。如果仍然失败，则可能必须等待官方解决方案。我希望这个问题能被Chia发展看到
> > > > 
> > > > 
> > > > 可以删除吗？告诉我们结果吗？
> > > 
> > > 
> > > 我删除了钱包数据库，现在无法同步
> > 
> > 
> > 我删除了，现在正在同步
> 
> I delete the private key and wallet software and download, install and import them again, but the situation remains unchanged, which may be caused by the local cache. I tried to import it on another new computer.

Tried another computer, and the same issue goes on. It seems that the XCH block is sent to the blockchain and blocked because of no fee. If so I wonder whether there would be a way to retrieve the XCH sent.
I hope the dev team notice the problem as it devastate the blockchain users’ asset security as you may easily lose your money by minor mistakes.

**Comment by pokerface0206** [comment]
> 解决了！
> @ pokerface0206
> @JsBlueCat
> 
> 在另一台计算机上安装chia GUI并用men-word恢复备份之后。
> 钱包同步后，金额又回来了。
> 看起来0费用交易已取消并返回到钱包。
> ![图像](https://user-images.githubusercontent.com/31769399/117570369-63f24100-b0fc-11eb-9b0b-f93f7cf59ae4.png)
> 
> **描述该错误**
> 尝试将XCH发送到另一个钱包，并标记为0（零）作为费用，并且该交易永远待定。
> 
> **重现**
> 步骤来重现行为：
> 
> 1. 转到“钱包”
> 2. 通过填写地址和金额创建交易，手续费为0（零）
> 3. 交易永远待定
> 
> **屏幕截图**
> 
> ![图像](https://user-images.githubusercontent.com/31769399/117540481-4cef1880-b042-11eb-8317-5143b1b7df95.png)
> 
> **桌面（请完成以下信息）：**
> 
> * 操作系统：Windows 10
> * 操作系统版本/版本：20H2
> * 处理器：Intel 9900k

Thank you. I'll try it tomorrow.

**Comment by JsBlueCat** [comment]
> > 解决了！
> > @ pokerface0206
> > @JsBlueCat
> > 在另一台计算机上安装chia GUI并用men-word恢复备份之后。
> > 钱包同步后，金额又回来了。
> > 看起来0费用交易已取消并返回到钱包。
> > ![图像](https://user-images.githubusercontent.com/31769399/117570369-63f24100-b0fc-11eb-9b0b-f93f7cf59ae4.png)
> > **描述该错误**
> > 尝试将XCH发送到另一个钱包，并标记为0（零）作为费用，并且该交易永远待定。
> > **重现**
> > 步骤来重现行为：
> > 
> > 1. 转到“钱包”
> > 2. 通过填写地址和金额创建交易，手续费为0（零）
> > 3. 交易永远待定
> > 
> > **屏幕截图**
> > ![图像](https://user-images.githubusercontent.com/31769399/117540481-4cef1880-b042-11eb-8317-5143b1b7df95.png)
> > **桌面（请完成以下信息）：**
> > 
> > * 操作系统：Windows 10
> > * 操作系统版本/版本：20H2
> > * 处理器：Intel 9900k
> 
> Thank you. I'll try it tomorrow.

thanks, i have solved, by deleting the .chia/mainnet/wallet
using 
```
rm -rf ~/.chia/mainnet/wallet
``` 
and syncing the wallet while farming, that's may be help ,thanks you.
by the way, there is no need to backup another computer do that. 
i have done with single machine.
