### ISSUE TITLE
 Using a virtual disk (RAM disk)

### ISSUE THREAD

**Issue by slebedev1976** [Chia-Network/chia-blockchain#4195]
Using a virtual disk (RAM disk)
Why not add a RAM disk function to extend the lifespan of the SSD, i.e. will the main operations be performed in RAM and periodically saved to an SSD (like AMD Radeon RAMDISK)?
![RAMDisk](https://user-images.githubusercontent.com/83506506/117543222-8b75da80-b024-11eb-8015-4eb6b6e75df8.jpg)

**Comment by wirespeed43** [comment]
You have 300gb ram?

**Comment by slebedev1976** [comment]
Many users have PCs with 32, 64, 128 gb of RAM. Sharing and using RAM
for writing to an SSD can significantly extend its life.


сб, 17 июл. 2021 г., 14:12 github-actions[bot] ***@***.***>:

**Comment by slebedev1976** [comment]
Many users have PCs with 32, 64, 128 gb of RAM. Sharing and using RAM for writing to an SSD can significantly extend its life.
