### ISSUE TITLE
[REQ] how to cancel a transactions

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-blockchain#4196]
when the transaction being pending, is there any method to cancel it ?

**Comment by zxc00747** [comment]
I don’t think so. Transaction with zero fee will lend forever and the XCH is locked

**Comment by giang21199z** [comment]
Hi. I faced to this issue.
I wait 7 for a transaction with transaction fee is 0.001.
It doesn't complete. So could I cancel it?
Please help me.
