### ISSUE TITLE
[BUG] Sync problem

### ISSUE THREAD

**Issue by praveenkumar2525** [Chia-Network/chia-blockchain#4199]
Plotting and farming for the past couple of days. From today morning, I'm unable to sync. I have not changed any settings. Earlier it was working fine but for the past 10 hors, unable to sync

**Comment by JsBlueCat** [comment]
> Plotting and farming for the past couple of days. From today morning, I'm unable to sync. I have not changed any settings. Earlier it was working fine but for the past 10 hors, unable to sync

start upnp in the wiki, it may help

**Comment by OdinSun35** [comment]
same problemm/

**Comment by Rapcore66** [comment]
same Problem...

**Comment by ChristmasWoe** [comment]
Can confirm the same issue. For last 2 weeks had no problems with sync, but since last 10 hours got not synced. Please fix it, it doesn’t allow to farm

**Comment by degrott** [comment]
same :/

**Comment by Fudnut** [comment]
same issue https://github.com/Chia-Network/chia-blockchain/issues/4169

**Comment by Fudnut** [comment]
> 
> 
> same issue #4169

finally synched, after nearly 24 hrs

**Comment by lexxfreeman** [comment]
Same issue

**Comment by PC101guy** [comment]
Same just woke up this morning everything was working fine over night, plots are still going but no longer synced.   Took the chance and restarted gui killing my plots but wanted to get farming online and still won't sync.
