### ISSUE TITLE
Second Computer in the Same Network Can't Connect to Peers

### ISSUE THREAD

**Issue by ozanatmar** [Chia-Network/chia-blockchain#4205]
I want to use 2 computers connected to same router (both are Windows 10).
The first computer runs perfect, plotting, farming etc. But the second computer doesn't connect to any peers. It connects to 1-2 but then loses them again. So sync status is always Not synced or syncing(while it is connected to a peer).
Why the second computer doesn't farm as well as the first computer?
Thank you.

**Comment by yuzhongrong** [comment]
me to

**Comment by OdinSun35** [comment]
me to. first pc
