### ISSUE TITLE
[help] How to merge plots from two different machine with own keys and node?

### ISSUE THREAD

**Issue by iamstevefury** [Chia-Network/chia-blockchain#4206]
**Describe the issue**
I had started plotting a week ago and I install the Chia Gui for windows on the two machines
Both has its private keys setup and I had being plotting ever since. However as I am scaling up
I understand it is much efficient to have own plot/farm/harvest machine separately setup and I would like to arrange this
However I am not sure how to merge the plot of both machine and ID into one, is this doable?
I would not want to lose the plot i worked on either machines :(

thanks in advance!

**Comment by tksalarzai** [comment]
You must use the same keys if you ever want to merge plots (like using all plots on one pc in future for farming) , and just for the time being that you want to farm on 2nd machine too before shifting plots to the main pc just Disable Upnp on harvester machine

**Comment by iamstevefury** [comment]
Thank you, I kinda suspect this. Appreciated
