### ISSUE TITLE
[help] how to activate chia enviornment  

### ISSUE THREAD

**Issue by maogo** [Chia-Network/chia-blockchain#4209]
I installed GUI(.deb)  but use  CLI tools  In  /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/,  I  don't want to go to that folder every time , Is there any way to run “chia” command  anywhere ?

**Comment by pureevans** [comment]
I’m having the issue that i can’t even activate the chia environment in that directory. That works for you if I understood correctly? I've also installed the GUI with the experimental installer. Do you simply go into that directory and type . ./activate and you have (venv) active?

**Comment by pureevans** [comment]
but i may have found an answer for your question https://github.com/Chia-Network/chia-blockchain/discussions/3747

**Comment by maogo** [comment]
> I’m having the issue that i can’t even activate the chia environment in that directory. That works for you if I understood correctly? I've also installed the GUI with the experimental installer. Do you simply go into that directory and type . ./activate and you have (venv) active?

not really activated, just run an executable  like ./chia...
