### ISSUE TITLE
[BUG] Invalid number of bytes 2 on retreived plots

### ISSUE THREAD

**Issue by DaFresh** [Chia-Network/chia-blockchain#4212]
**Describe the bug**
Context: a farmer and a harvester, both with same keychain (.chia copied from farmer to harvester), (initialized on the farmer, added to the harvester with the mnemonic words) . The harvester creats plots and send them over internet to the farmer.

When the farmer check plots (chia plots check), I get the error on every plots produced by the remote harvester:

```
Failed to open file /nfs2/ok/plot-k25-2021-05-08-18-02-e0a0db86bf4fe95dce65e6b30257a6b2793eda58079e3fc746431dda02a8b1ab.plot. Invalid number of bytes 2 Traceback (most recent call last):
  File "/home/ubuntu/chia-blockchain/chia/plotting/plot_tools.py", line 208, in process_file
    ) = parse_plot_info(prover.get_memo())
  File "/home/ubuntu/chia-blockchain/chia/plotting/plot_tools.py", line 82, in parse_plot_info
    raise ValueError(f"Invalid number of bytes {len(memo)}")
ValueError: Invalid number of bytes 2
```

MD5 if files match on farmer and harvester. I have also tried all possibility with "-a" "-f" and "-p" 

**To Reproduce**

1. install a farmer and a harvester with the same .chia
2. produce a plot on the harvester and transfer it to the farmer
3. "chia plots check" on the farmer

**Expected behavior**
Plots received on the farmer from the harvester are OK

**Screenshots**

- OS: Linux
- OS Ubuntu Focal
- chia 1.1.5.dev0 on the farmer, 1.1.4 on the harvester

**Comment by DaFresh** [comment]
Anyone on this ?

**Comment by arfycat** [comment]
I had the same thing happen on two new plots.  Other plots created by the same host are OK.  I changed line 82 to:

`raise ValueError(f"Invalid number of bytes {len(memo)}" + str(len(memo)))
`

The output for my two bad plots was the same:

`ValueError: Invalid number of bytes 22
`

I plotted with 1.1.3 and have full node, harvester, and farmer 1.1.5.  The plotter host has created about 60 good plots and these two bad ones.

**Comment by stigmat4j** [comment]
Same problem. 

@DaFresh did you solve this problem?

**Comment by DaFresh** [comment]
Yes, I had used a wrong plublic farmer key (actually a bug in my script, using a int instead of the key).

**Comment by stigmat4j** [comment]
@DaFresh you don't know if it is possible to fix plots without a public key?
