### ISSUE TITLE
[BUG] chia.exe gives up plotting during Phase 2/3 on Win10 

### ISSUE THREAD

**Issue by variableresults** [Chia-Network/chia-blockchain#4220]
I have a weird issue where every now and then chai.exe will hang after Phase 1 completes. It stops iterating through the log files but doesn't report any actual error. 

Jobs are being kicked off by Chia Manager. No resource conflicts that I can see.

chia.exe behavior is that it seems to permanently halt and then give back all its allocated RAM till Task Manager says it's only using 64kb. Happens on multiple temp drives, all PCI-E 4.0 NVME SSDs that plot between 6-8 hours. 

This is obviously annoying, especially since I can be 75%+ when it decides to stop, at which point I have to go back and wait for other jobs to finish before I delete the stale tmp files.

**Comment by variableresults** [comment]
Screenshots of behavior:

![image](https://user-images.githubusercontent.com/34286809/117592779-8d609c00-b0ff-11eb-8a01-63238e2eb0dc.png)
![image](https://user-images.githubusercontent.com/34286809/117592793-981b3100-b0ff-11eb-801d-1b15a94fe839.png)

**Comment by disfruto** [comment]
Yup, same here. Windows 10, my 5 plots all stuck in the "Compression from tmp files" at 36%, "Bucket 89 uniform sort [...]", stuck for several hours now.

**Comment by aa15032261** [comment]
I have the same issue! When the issue occurs, it always stuck at "Compressing tables X and Y"

**Comment by NicChoo96** [comment]
This happened to me plotting the new NFT plots. I am a small plotter with my 500 GB SSD trying to parallel plot, but my interval plotting met into problems and my first plot which happens to be in phase 3 compressing tables 1 and 2 just hangs when my SSD ran out of space. I tried to free up some space by deleting the plots that have just started. But, to no avail, the first plot didn't start back up after a long long time.

I suspect that this feature was not coded to take resuming plots at phase 3 into account when compressing tables.

By the way, if any dev came across this post, please add a manual restart for the plots that need to wait 5 minutes to plot again after freeing up spaces. Really helps small chia farmers like me. Thank you!

**Comment by x3style** [comment]
Potentially the same issue here: https://github.com/Chia-Network/chia-blockchain/issues/7643
