### ISSUE TITLE
[BUG] XCH coins disappeared

### ISSUE THREAD

**Issue by vasil-github** [Chia-Network/chia-blockchain#4221]
COINS MISSING.

I did farm2 XCH coins on my PC. On Wallet - Ballance - Total Balance i did have 2 XCH. 

After 1 days the PC did reboot (power outage) and CHIA GUI was unable so sync any more (stuck at connecting to wallet)
After 12 hours of just "connecting to wallet" i decided to read how to fix the issue.
In one of your guides I did read to delete c:\Users\Username\.chia\mainnet\wallet\db

And Yes, The gui did start successfully again, but in wallet the  BALLANCE WAS 0 ? :-O

Wallet is with status synced, plots are available and status is farming.... 

- OS: Win10
- OS Version/Flavor: 20H2
- CPU: Ryzen 3600, 32GB 2933 ram

Any way to fix/restore my coins? A way to track what happened?

P.S. the old blockchain_wallet_v1_mainnet_2111174469.sqlite was 1500 MB and more and the new one is only 30MB.

**Comment by SGABR** [comment]
Hello.

The files blockchain_wallet_v1_mainnet_2111174469.sqlite have the same name? This numers in the end is the number of your wallet. If this numbers is the same in the new file, I belive that question of time for the file sincronize until it reaches the original size and you to see your coins. But if the files not have the same name, you created a new wallet and those coin are lost.

**Comment by SGABR** [comment]
Sorry, the coins may not be lost, as you just need to log into the same wallet in which they were created, using the 24 security words and wait for synchronization

**Comment by zombie665** [comment]
few years later...

**Comment by vasil-github** [comment]
> 
> 
> Hello.
> 
> The files blockchain_wallet_v1_mainnet_2111174469.sqlite have the same name? This numers in the end is the number of your wallet. If this numbers is the same in the new file, I belive that question of time for the file sincronize until it reaches the original size and you to see your coins. But if the files not have the same name, you created a new wallet and those coin are lost.

YES, the number blockchain_wallet_v1_mainnet_2111174469 is the same.

**Comment by vasil-github** [comment]
> 
> 
> Sorry, the coins may not be lost, as you just need to log into the same wallet in which they were created, using the 24 security words and wait for synchronization

I hope so. I have not have any/similar issues on Bitcoin or Litecoin...

**Comment by typ1111** [comment]
Same problem, did you restore your coins?

**Comment by vasil-github** [comment]
Unfortunately not.
Sad thing is that I have made a backup of the files before deleting them, but restoring then back just make the app get stuck at CONNECTING TO wallet.

**Comment by typ1111** [comment]
Did you checked if you had XCH in to your address on chiaexplorer?

**Comment by Magicwalker** [comment]
I also having same issue. When I see from wallet previously have the coin, i using chia explorer can see the coin but its just disappear from wallet and its said spend. I unable to find back the coin any more

**Comment by typ1111** [comment]
Anybody form team could solve this issue?

**Comment by vasil-github** [comment]
I like to report back that after deleting any file related to chia, and 48 h sync of the wallet coins appeared back.

**Comment by Magicwalker** [comment]
> 
> 
> I also having same issue. When I see from wallet previously have the coin, i using chia explorer can see the coin but its just disappear from wallet and its said spend. I unable to find back the coin any more

i found the issue is that the xch credit to old wallet address.. Now i unable to retrieve the coin from old addreess. The GUi only credited to old address but its did not go wallet new address. I go chia explorer check the old wallet address its said spend

**Comment by majekqwert** [comment]
This is a problem with Full Node syncing with Wallet. I have synced in Full Node. At Wallet, I have syncing

**Comment by blackflash** [comment]
I have same issue. Chia explorer shows me coins, but eve after full sync I cant see my coins in wallet

**Comment by OmarGC** [comment]
I have the same problem, the GUI shows me 0 xch when I already had a few thousand mojos
:S
After some time, the real amount appeared?
How do you see Chia Explorer?

**Comment by maxchock** [comment]
Hi all,

Any update to the XCH not showing issue? I supposed to have 0.1 XCH from Hpool, chiaexplorer showed the transaction, status is UNSPENT, but still not showing in my wallet. Any idea?

**Comment by perguth** [comment]
Same here.
