### ISSUE TITLE
[BUG] app crash and you loose all current plot that you are planted...

### ISSUE THREAD

**Issue by MTXDevp** [Chia-Network/chia-blockchain#4228]
**Describe the bug**
If you delete a plot with the gui, the app crash and you loose all current plot that you are planted

**To Reproduce**

If you delete a plot with the gui, the app crash and you loose all current plot that you are planted

**Comment by MatveyFV** [comment]
This only happens when you are trying to close the active plotting process.

**Comment by tgadberry1** [comment]
> This only happens when you are trying to close the active plotting process.

I don't exactly recall, but that was probably the case. I accidentally added the plots to the wrong queue while others were running. It all locked up when I tried to cancel it. Still, a bug to be addressed.

**Comment by jnjus** [comment]
Can confirm, just happened to me on Windows Home 20H2 (Build 19042.985). Lost a good amount of plots. 
![image](https://user-images.githubusercontent.com/76278125/118194190-fe14fa80-b416-11eb-8d2d-e8d8f84a7f9a.png)

Chia will end up in a "connecting to wallet" loop. Only solution is to quit and delete the partial plots.
