### ISSUE TITLE
Chia losts when transfer from wallet to wallet !!

### ISSUE THREAD

**Issue by chaUAV** [Chia-Network/chia-blockchain#4229]
I transfer 0.2 XCH to my backup wallet. I comfimed in
https://www.chiaexplorer.com/blockchain/coin/0xa0dfd23379add08716ee59a49731551ebaca782a022e05959befca55145f83c3
but when I check in my wallet it shown 0 XCR
![image](https://user-images.githubusercontent.com/67619154/117553362-652f5980-b07b-11eb-9c17-e910a42aac83.png)
![image](https://user-images.githubusercontent.com/67619154/117553375-8132fb00-b07b-11eb-9292-6cf6d0a4cbac.png)

**Comment by zxc00747** [comment]
> I transfer 0.2 XCH to my backup wallet. I comfimed in
> https://www.chiaexplorer.com/blockchain/coin/0xa0dfd23379add08716ee59a49731551ebaca782a022e05959befca55145f83c3
> but when I check in my wallet it shown 0 XCR
> ![image](https://user-images.githubusercontent.com/67619154/117553362-652f5980-b07b-11eb-9c17-e910a42aac83.png)
> ![image](https://user-images.githubusercontent.com/67619154/117553375-8132fb00-b07b-11eb-9292-6cf6d0a4cbac.png)

Is your backup wallet fully synced?
