### ISSUE TITLE
[BUG] Bootlop

### ISSUE THREAD

**Issue by IWantOriginalName** [Chia-Network/chia-blockchain#4234]
**Describe the bug**
When I delete wrong plot, I was getting a Bootloop. I wating 20 minutes, but nothing changes.

**To Reproduce**

1. Create wrong plot
2. Click 3 dots near wrong plot
3. Click "Delete"
4. Bootloop

**Expected behavior**
Delete plot without bootloop.

**Screenshots**
![image](https://user-images.githubusercontent.com/23551637/117554193-c4cb3c00-b05e-11eb-93cf-7a43ab3ad89d.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: 20H2
- CPU: Intel i7-10700K

**Additional context**

**Comment by gignasty** [comment]
I'm having the same problem. Maxing out 32GB of RAM then goes to white screen. is there any fix for this?
