### ISSUE TITLE
[help] Full Node Connection

### ISSUE THREAD

**Issue by Kusey86** [Chia-Network/chia-blockchain#4235]
The full node connection appears to be connected, but there is no data transfer. I did not have any problems with IP address and port opening. My port 8444 is open. Can you help me?

![image](https://user-images.githubusercontent.com/83300326/117554385-f1cc1e80-b05f-11eb-8a5c-eb1d858e71d5.png)

**Additional context**

**Comment by paynemusik** [comment]
How u make this port open (8444)? I don’t understand this my full node stuck loading

**Comment by Kusey86** [comment]
in router settings you can open this port. And let windows defender apply this port

**Comment by paynemusik** [comment]
Im on Mac mini m1... and i Dont understand this in my router settings...

**Comment by choduprogramer** [comment]
I was able to solve this just now by going into Windows Firewall advanced settings and noticing that a couple of rules for Chia were disabled. (One was for tcp port 6 I think and other I don't remember) 

I enabled both those and it immediately synced.

**Comment by Kusey86** [comment]
> I was able to solve this just now by going into Windows Firewall advanced settings and noticing that a couple of rules for Chia were disabled. (One was for tcp port 6 I think and other I don't remember)
> 
> I enabled both those and it immediately synced.
can you please explain. We need a lot
