### ISSUE TITLE
[BUG] "failed to get block from None, timed out" & "weight proof did not arrive from peer (IP)" error & cannot see queued plots

### ISSUE THREAD

**Issue by cjhudlin** [Chia-Network/chia-blockchain#4240]
**Describe the bug**
A clear and concise description of what the issue is.

Node not synchronising and showing queued plots in gui

**Expected behavior**

Node synchronization and plot overview in gui

- OS: Ubuntu server 
- OS Version/Flavor: 20.10
- chia ver: xx 4 (latest)

**Additional context**

Works with second server running older version, also Ubuntu server

**Comment by jakub-polak** [comment]
@cjhudlin solved?

**Comment by cjhudlin** [comment]
Nope, not that I'm aware anyway, recently my raid card failed again, and so I wasn't able to check since the server won't start and I'm away till MondayAm 15.05.2021 23:01 schrieb Jakub Polak ***@***.***>:
@cjhudlin solved?
