### ISSUE TITLE
[BUG] RuntimeError: std::exception [8311] Failed to execute script chia

### ISSUE THREAD

**Issue by PNWcybertruck** [Chia-Network/chia-blockchain#4241]
**Describe the bug**

When I start a plot I'm only getting to 1% and after viewing the log I see the error code. I updated my computer I'm fully synced am I missing other settings?

Macbook Pro with M1 1TB internal SSD 892GB free.

RuntimeError: 

std::exception
[8311] Failed to execute script chia

1. Go to 'Plot'
2. Click on 'Macintosh HD' for the SSD
3. Click on 'Seagate HDD' for the HDD - after plotting
3. Scroll down to 'View Log is where i see error code'
4. See error: [8311] Failed to execute script chia 

 ** Typically the error number is different **

**Expected behavior**

Wondering why this wont plot, do i need to reformat the internal SSD? is the internal SSD not applicable? 

**Screenshots**

I can add one if needed

**Desktop (please complete the following information):**

- OS: MacOS
- OS 11.3.1 (20E241)
- CPU: M1 

**Additional context**
Using x3 Seagate Backup plus hub - 8TB external HDD connected via Insignia 4-port USB-C Hub (NS-PCHC4A)

**Comment by djkoelkast** [comment]
I have also got this problem on my ARM Ubuntu machine. It has a 100% empty SSD and a 100% empty HDD.
![chia](https://user-images.githubusercontent.com/83341743/117565905-0f2ad800-b0b4-11eb-8382-6bd9e55e82e8.jpg)

**Comment by xiaogan18** [comment]
I have same problem
