### ISSUE TITLE
[BUG] CLI plotting in Windows 10 is significantly slower comparing with GUI

### ISSUE THREAD

**Issue by pluto2021** [Chia-Network/chia-blockchain#4247]
**Describe the bug**
The CLI plotting in Windows 10 is significantly slower than the GUI plotting. CLI plotting would sometimes halt for no reason in the middle of plotting.

**To Reproduce**
(1) Start single plot in CLI
(2) Start single plot in GUI with a same setting at about a same time
It does not matter if (1) or (2) would go first. 
(3) Check the plotting log side by side.

**Expected behavior**
CLI should be able to plot as efficiently as GUI under Windows 10

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Latest build + updates
- CPU: Intel

**Additional context**
Tried using the normal Windows command shell, as well as Windows powershell. The same issue.

**Comment by JoshuaLukeBray** [comment]
I have had the same experience as this, the GUI plotted many times faster than the command line.

**Comment by oe3gwu** [comment]
I got the same issue using Linux.
