### ISSUE TITLE
Plot created 100% but not appear in farm[help]

### ISSUE THREAD

**Issue by Chiazz** [Chia-Network/chia-blockchain#4257]
PLease i don't understand

my plot K32 are created and i can saw it in my HDD but nothing appear in farm.
i don't understand what's the problem

please somebody can help me ???

**Comment by runxcode** [comment]
Have you try to add it manually? I see theres a link to do it (Add Plot Directory).
<img width="703" alt="Screen Shot 2021-05-09 at 12 04 09" src="https://user-images.githubusercontent.com/60741359/117561204-ca586e80-b0be-11eb-967f-e6f7b6eba709.png">

**Comment by Chiazz** [comment]
yes i add the disk manualy but nothing in farm. Make me crazy

**Comment by Chiazz** [comment]
> i have the same problem, plots are saved and i can see it, but farming is not starting. i also add it manually, but it dident work

HO im glad im not alone

**Comment by thomaskneifel** [comment]
lets wait for help 😄

**Comment by Chiazz** [comment]
my log files:

2021-05-09T07:27:57.419 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-05-09T07:28:44.823 harvester chia.plotting.plot_tools: WARNING  Not farming plot /media/pol/HDD1/plot-k32-2021-05-08-20-17-5ece998512a1bbf554371d9382e081281c60bd59c0979e50f6927e86f803fb16.plot. Size is 3.9999999990686774 GiB, but expected at least: 99.06 GiB. We assume the file is being copied.

**Comment by Chiazz** [comment]
I need help pls my block at 100% and just 4Go on HDD......

**Comment by thomaskneifel** [comment]
at mee it is working now.
after plotting was finish, in the final storage the ending file name was      .plot.2.temp      an it did not workt no farming possible.

now i switched the ending file just        .plot                    no it is farming

**Comment by Chiazz** [comment]
> at mee it is working now.
> after plotting was finish, in the final storage the ending file name was .plot.2.temp an it did not workt no farming possible.
> 
> now i switched the ending file just .plot no it is farming

My plot is 4Go i don't understand the problem! nobody help

**Comment by Omnikron13** [comment]
If the file had .tmp/temp at the end it was probably still being copied from the temporary location to the final location. Renaming it probably broke the copying resulting in an incomplete plot. You need to wait for the plotter to copy the file and remove the .tmp extension itself.

**Comment by Chiazz** [comment]
> If the file had .tmp/temp at the end it was probably still being copied from the temporary location to the final location. Renaming it probably broke the copying resulting in an incomplete plot. You need to wait for the plotter to copy the file and remove the .tmp extension itself.

Thx but I didn't rename any files. It's just go in my HDD 4Go

**Comment by emosGambler** [comment]
> 
> 
> If the file had .tmp/temp at the end it was probably still being copied from the temporary location to the final location. Renaming it probably broke the copying resulting in an incomplete plot. You need to wait for the plotter to copy the file and remove the .tmp extension itself.

Probably this is the right answer. I've also experienced plot being 100% and not farming, but I've noticed that indeed it was being copied to the HDD. It took around 15-20 mins. I guess this will be my time to go between starting plots.

Just wait, don't remove any "temp" sufix, it's there for a reason. Make sure you have enough disk space to perform the copying and that the directory you are working on has got privilages to do so.
