### ISSUE TITLE
[help]Plot Stuck on 1 %

### ISSUE THREAD

**Issue by tomke3sgte** [Chia-Network/chia-blockchain#4259]
This is eror i get always and my ploting not starting

Starting plotting progress into temporary dirs: D:\Ploting and D:\Ploting
ID: 12b724f6a38414930638e2e5833e716f4eb69b0155d875307340d0522799f282
Plot size is: 32
Buffer size is: 3390MiB
Using 128 buckets
Using 2 threads of stripe size 65536

Starting phase 1/4: Forward Propagation into tmp files... Sun May  9 07:25:25 2021
Computing table 1
Only wrote 0 of 1048572 bytes at offset 0 to "D:\\Ploting\\plot-k32-2021-05-09-07-25-12b724f6a38414930638e2e5833e716f4eb69b0155d875307340d0522799f282.plot.p1.t1.sort_bucket_007.tmp"with length 0. Error 1. Retrying in five minutes.
Only wrote 0 of 1048572 bytes at offset 0 to "D:\\Ploting\\plot-k32-2021-05-09-07-25-12b724f6a38414930638e2e5833e716f4eb69b0155d875307340d0522799f282.plot.p1.t1.sort_bucket_007.tmp"with length 0. Error 1. Retrying in five minutes.

**Comment by gignasty** [comment]
I'm getting the same

**Comment by F83D** [comment]
Same for me on Ubuntu.
