### ISSUE TITLE
[help] Main machine not showing harvester

### ISSUE THREAD

**Issue by Kukyn92** [Chia-Network/chia-blockchain#4260]
I have setted up a harvester, in the main machine everything seems to be running smooth, on main pc under Farm tab- at the bottom select "Hide Advanced Options"- scroll down and " Your Harvester Network"  shows (2) Node ID-- (1) my main pc and (2)  harvester; also under farm tab under "Last Attempted Proof" my qty of plots on  harvester  also show up there. But after a while the harvester is not shown anymore, even when I can see "Last Attempted Proof" showing the correct amount of plots . If i restart the gui everything fix for a while but again the harvester disappear after some time. Although I have noticed my harvester reads HDD when the farmers shows an attempt, I would like to know how to fix that issue
Another thing I have noticed is that there are at least 70 peers connected to my harvester node, is that amount normal?
I setted up the harvester following the instructions on this article https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines
Am using GUI for windows an my port 8448 is open in main machine. Thanks for your help

**Comment by zombie665** [comment]
In cmd on main pc _netstat_

![Снимок экрана 2021-05-09 175057](https://user-images.githubusercontent.com/83660122/117573181-fcce8f80-b0ef-11eb-893f-d60ec88c5c6d.png)
![Снимок экрана 2021-05-09 175654](https://user-images.githubusercontent.com/83660122/117573172-f7714500-b0ef-11eb-96d5-27dfcc9ae04b.png)
