### ISSUE TITLE
Ctrl + R will reload the "page" and stuck on connecting to wallet

### ISSUE THREAD

**Issue by ettouzany** [Chia-Network/chia-blockchain#4261]
![Capture](https://user-images.githubusercontent.com/68807471/117562835-7d11d800-b091-11eb-8362-e620f6c891de.PNG)

**Comment by baclijad** [comment]
Same here, restarted few times app and windows

**Comment by ettouzany** [comment]
> Same here, restarted few times app and windows

Now when is it's stuck on this message even after restarting my computer

**Comment by bloodzzero** [comment]
same here,stop at sync wallet

**Comment by alemba** [comment]
Same here when removing a not-finished plot

**Comment by Uuno-t** [comment]
same here

**Comment by K0P0HABupyc** [comment]
Тоже самое

**Comment by steelsteed92** [comment]
same issue 

![Untitled](https://user-images.githubusercontent.com/83909929/117572718-7b8af300-b117-11eb-82ea-1db4b7c80598.jpg)

**Comment by baclijad** [comment]
Is there any update of this issue? Anyone have some solution?

**Comment by sayfersif** [comment]
I see the developers do not care about this problem. I have the same problem. Nowhere is there a clue how to fix
