### ISSUE TITLE
[BUG] FULL NODE IS LOADING PLOTS READY FARM 0%

### ISSUE THREAD

**Issue by paynemusik** [Chia-Network/chia-blockchain#4265]
** Full Node is loading**

Im not synced, my plots are ready, and I don’t understand why this shit don’t work. Click on full node and I Waiting a long time and it’s not begin to show me I’m synced I’m not synced I don’t no. Plot works fine but farming 0% well I’m not synced

i have read the Problem with the Port 8444 it is a thing that can I do for my problem? But I don’t no where I can make this. 

Please help me and sorry for my English I’m from Germany 😉

**Comment by secco04** [comment]
Welche Version hast du installiert?
Schau mal bitte in den Logs nach  ob du was findest .    c:\users\%username%\.chia\mainnet\log\debug.log
ändere ggf. die Ausgabe der Logs in der config.yaml von WARNING auf INFO um mehr infos zu bekommen 

Füge mal im Fullnode reiter folgendes hinzu:
node-eu.chia.net Port 8444
node.chia.net Port 8444
chia.yacp.net Port 8444

Hoffe irgendwas hilft :D
