### ISSUE TITLE
My new plots will not be detected

### ISSUE THREAD

**Issue by Bardylis123** [Chia-Network/chia-blockchain#4273]
When I'm creating new plots the problem appears:  

"plot has a farmer public key that is not in the farmer's pk list" 

What can I do ?

**Comment by Gnomuz** [comment]
Create your plots with your keys ...

**Comment by Bardylis123** [comment]
First, thank you. But I had the last days problems with the synced. I delete everything and reinstalled everything again. At this moment I had 5 plots. Then I created a new key and plot 2 new plots. But now these two new plots will not be detected, but the old 5. Should I use again the old key?

As you see I am really a noob :D

**Comment by Bardylis123** [comment]
If I understand everything correctly I have made 5 plot with the old key. With the new key i created 2 plots. Why then are the old 5 plots displayed with the new key but not the two new plots, which are created with the new key?

I think I understand something completely wrong haha

**Comment by Bardylis123** [comment]
If I understand everything correctly I have made 5 plot with the old key. With the new key i created 2 plots. Why then are the old 5 plots detected with the new key but not the two new plots, which are created with the new key?

I think I understand something completely wrong haha
