### ISSUE TITLE
[BUG] CPU utilization

### ISSUE THREAD

**Issue by piroznoe** [Chia-Network/chia-blockchain#4275]
**Issue**

When plotting `n` plots in parallel CPU load is not uniform with default settings (4 ram, 2 thread) 
I have 8 cores, 16 threads, and plotting 7 plots in parallel

From: 3 plot form SSD,  3 plot form SSD, 1 plot from NVMe
To: 1 HDD

**Expected behavior**
Uniform cpu utilization
 

**Screenshots**

![Screen Shot 2021-05-09 at 13 30 47](https://user-images.githubusercontent.com/44473742/117568734-c7637b00-b0ca-11eb-9669-36204e8cefac.png)

**Desktop:**

- OS: MacOS
- OS Version/Flavor: 11.2.3
- CPU: i9 9900k

64 ram 2666

**Comment by KinChungE** [comment]
I think it is completely normal
1. Only phase 1 uses multi-thread, while other phases can do single-thread only
2. Your CPU is hyper-threaded, and each physical core is responsible for one plot
