### ISSUE TITLE
[REQ]what can I do ?

### ISSUE THREAD

**Issue by chiaersssss** [Chia-Network/chia-blockchain#4278]
**Describe the request**
A clear and concise description of your suggested enhancement, as well as some basic rationale to allow us to balance the effort/reward for the work, if possible.

**Images**
If applicable (but not required), add diagrams or wireframes to help explain your request if it is GUI related.
![1](https://user-images.githubusercontent.com/83908338/117571169-dfa1bd00-b0ff-11eb-91e1-64d2c3022598.jpg)
![2](https://user-images.githubusercontent.com/83908338/117571173-e4667100-b0ff-11eb-8a0a-c162a7a7abd0.jpg)

**Additional notes**
Add any other closing comments here.

**Comment by max918** [comment]
is your 8444 port open for public connection ?

get your ip from
https://www.whatismyip.com/
online tools for check opening port
https://www.yougetsignal.com/tools/open-ports/
input your ip address and port 8444
it will show you are opening (green flag) or closed (red flag)

**Comment by chiaersssss** [comment]
thanks , red flag

**Comment by max918** [comment]
red flag means other people can not find you.
this may cause by router, firewall setting.

you may need to add other people by youself manually.

click conenct to other peers
Ip address / host: node.chia.net
Port: 8444

by the way, you need to keep connect with other to keep node sync and get chance to win, so this manual step is not solve the problem, you need to solve the connection port issue.
