### ISSUE TITLE
[BUG]build mac client by build_macos.sh,the client run white screen

### ISSUE THREAD

**Issue by TaylorWenOne** [Chia-Network/chia-blockchain#4279]
**Describe the bug**
build mac client by build_macos.sh,the client run white screen
**To Reproduce**

1. Go to /build_scripts/build_macos.sh
![image](https://user-images.githubusercontent.com/35680539/117572358-21813200-b105-11eb-9f76-3f9356b8355d.png)

2. wait build result
![image](https://user-images.githubusercontent.com/35680539/117572425-673dfa80-b105-11eb-99fb-c0cee7cf759c.png)

3. go build result dir
![image](https://user-images.githubusercontent.com/35680539/117572440-83419c00-b105-11eb-9123-d6d343d16885.png)

4. open build client
![image](https://user-images.githubusercontent.com/35680539/117572477-abc99600-b105-11eb-9a92-f7af0015c390.png)

**Expected behavior**
white screen,waitting connect wallet for ever,it stay in this state

**Screenshots**
as those screenhots.

**Comment by ChiaDoge-Network** [comment]
could dev group give some respond？
