### ISSUE TITLE
Windows, multiple screens opened. [PR bug report]

### ISSUE THREAD

**Issue by Yostra** [Chia-Network/chia-blockchain#428]
Moved from PR, from reference.

https://github.com/Chia-Network/chia-blockchain/pull/427

I had left Chia for plotting.
Issue 1) After a day i can find around 5 windows opened up with "keys" screen displayed.
![image](https://user-images.githubusercontent.com/71882331/94329282-ada57580-ffca-11ea-8db8-171bbf4bc663.png)
Issue 2) When i selected the private key it went to "wallet" screen. When i clicked "plot" screen existing lot information is no more there.
All the five screens same state.
Issue 3) I closed 1 screen. All five screens got closed after a warning:
![image](https://user-images.githubusercontent.com/71882331/94329340-38867000-ffcb-11ea-9fa2-bf72be4d9087.png)
![image](https://user-images.githubusercontent.com/71882331/94329343-3c19f700-ffcb-11ea-8626-6129064399ae.png)

**Comment by wjblanke** [comment]
I've seen multiple windows as well

**Comment by hoffmang9** [comment]
We've put protections in Beta 26 to keep this from happening with the GUI - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta26
