### ISSUE TITLE
Requesting Feature: Add Pause option to plotting

### ISSUE THREAD

**Issue by vashero** [Chia-Network/chia-blockchain#4284]
A Pause option during plotting would be beneficial, especially to those of us who are plotting on our gaming PC's

**Comment by DroneNR** [comment]
This would be amazing

**Comment by danktankk** [comment]
+100

**Comment by Flashtekuk** [comment]
Another +1 from me... It would also be really helpful if you could "finish up current plot, don't accept more, pause" so you can finish your current work and perform maintenance such as a reboot in a controlled manner, then resume once you've rebooted *at your leisure*
