### ISSUE TITLE
Possible Network Split - Blockchain stuck at block #255108

### ISSUE THREAD

**Issue by mandees** [Chia-Network/chia-blockchain#4287]
I'm running 2 full nodes, one of which has 50+ connections with other full-nodes.     
Latest complete block for everybody is 255108.     
However, challenges are still arriving and the farming algorithm seems to be in place, as I can see my plots regularly passing the filter.
I've doublechecked with chiaexplorer.com and it also shows block # 255108 as the latest block.

Is anybody else experiencing the same issues?

**Comment by ArtiskOnGit** [comment]
same

**Comment by Akaino** [comment]
https://www.reddit.com/r/chia/comments/n8dvec/chia_network_out_of_sync_critical/

**Comment by bugxzhu** [comment]
same

**Comment by tangdasan** [comment]
+1 

Believe me，Short sale

**Comment by PC101guy** [comment]
same

**Comment by McCalm** [comment]
Agree! Latest complete block for everybody is 255108.

Since this time the Node is in synchronisation status. No more working, only the connections to other Nodes are life.

**Comment by anderzheng** [comment]
+1

**Comment by donaloconnor** [comment]
It's back. 255111 now.

**Comment by McCalm** [comment]
^agree, now running...

**Comment by PC101guy** [comment]
> 
> 
> ^agree, now running...

Running yes, but it's not stable, it seem's like the connection is still struggling, falling out of sync for a few seconds, blocks taking way longer then they should.  what is going on.

**Comment by McCalm** [comment]
^+1

**Comment by McCalm** [comment]
> 
> 
> ^+1 .. and stucking on 255118

**Comment by PC101guy** [comment]
> 
> 
> > ^+1 .. and stucking on 255118

Same, stuck unstuck, then stuck again, Really hope this is to do with them getting ready for pools and maybe something went wrong, or this could be a sign of bigger issues.  im just gonna call today an only plotting day lol, farming is out the window.

**Comment by wct097** [comment]
That block was stuck for something like an hour on my side.  Had that showing as peak height on three different nodes and most of the connected nodes.

**Comment by r1235613** [comment]
same issue at chiaexplorer
https://www.chiaexplorer.com/blockchain/blocks

**Comment by ArtiskOnGit** [comment]
solved now, install 1.1.15
