### ISSUE TITLE
status out of sync 

### ISSUE THREAD

**Issue by Flexcrypto1** [Chia-Network/chia-blockchain#4291]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by PC101guy** [comment]
They are having network issues today, its all over reddit and the dev's posted they are aware of it.
