### ISSUE TITLE
Connecting to wallet

### ISSUE THREAD

**Issue by Uuno-t** [Chia-Network/chia-blockchain#4295]
DevTools failed to load SourceMap: Could not parse content for file:

**Comment by felixbaumeister** [comment]
same (see two bugs before 😃 )

**Comment by Uuno-t** [comment]
AppData/Local/chia-blockchain/app-1.1.4/resources/app.asar/build/renderer/js/80.js.map: Unexpected end of JSON input

**Comment by putinbra** [comment]
It always say (30 min) that Chia connects to Wallet. I was plotting it was already at 71% and then I was logged out and trying to log in again ...

**Comment by firstfsx** [comment]
how to reconnect to wallet and recovery pollting percent？

**Comment by Uuno-t** [comment]
What is this problem?

![image](https://user-images.githubusercontent.com/83900672/117582450-5b9d0480-b102-11eb-8392-fc0863728faf.png)
![Skärmbild 2021-05-09 200932](https://user-images.githubusercontent.com/83900672/117582489-82f3d180-b102-11eb-9227-d2fbf1ec2440.png)

**Comment by fabianhild** [comment]
Same problem on mac (solved):
Uninstalled chia, found a hidden part, (/Users/…/chia) deleted.
Then restart the Mac, intall chia again.

You have the same problems in "Sources", but after a few minutes it´s Syncing again
