### ISSUE TITLE
Can not synced

### ISSUE THREAD

**Issue by tanliang1** [Chia-Network/chia-blockchain#4296]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Muffexx** [comment]
Duplicate of: #4291

**Comment by HardyIII** [comment]
Status Not Synced, Was Synced just morning at about 9 AM EST. the I recheck every couple of hours to make sure the PC is running. I have 4 farming and 1 plotting.

**Comment by Stanley899** [comment]
also not synced height 25513

**Comment by Muffexx** [comment]
There seems to be a problem with the whole network: [chia explorer](https://www.chiaexplorer.com/blockchain/blocks)

**Comment by gushome7** [comment]
Something is happening. Status not Synced since block 255143 a lot of minutes ago. chiaexplorer too on same block,

**Comment by aHairball** [comment]
Agreed, same here.....Not Synced, Peak Height of 255143, GUI ver=1.1.4

**Comment by EminSONGUL** [comment]
Same problem block 255143

**Comment by JonathanZheng** [comment]
Same at 255143

**Comment by mrnguyenphuc** [comment]
Chia get stuck at height 255143. version 1.14. 
What the hell?

**Comment by doubleUTF** [comment]
Yup
![image](https://user-images.githubusercontent.com/17230520/117577577-30cd9480-b09f-11eb-913d-0be07b17ba3e.png)

**Comment by marcelo74mayo** [comment]
Same at 255143

**Comment by TimFoerster** [comment]
https://github.com/Chia-Network/chia-blockchain/tree/1.1.4-hotfix

**Comment by dumpstar85** [comment]
Same problem - Chia GUI "Not Synced" at height 255143 version 1.14

**Comment by rhernaus** [comment]
![image](https://user-images.githubusercontent.com/20721834/117577651-f689e480-b0ea-11eb-95a8-a0c91d1b1f50.png)

**Comment by JessePinkmanVN** [comment]
Same issue here, thought only me, turns out lots of people getting this bug

**Comment by dumpstar85** [comment]
Is there a hotfix for the windows gui @rhernaus

**Comment by dumpstar85** [comment]
Mine just synced back up on its own accord

**Comment by DFAnk1** [comment]
It just synced again !

**Comment by Muffexx** [comment]
Mine too. But I already built the 1.1.4-hotfix.

**Comment by rhernaus** [comment]
they added another commit to that hotfix branch
so maybe built again

**Comment by AkiraDX** [comment]
It was re-synced and now out of sync again.

**Comment by aHairball** [comment]
OK, mine is now steady  and in sync at height

255296
