### ISSUE TITLE
stuck  with Connecting to wallet[help]

### ISSUE THREAD

**Issue by mola326** [Chia-Network/chia-blockchain#4301]
stuck  with Connecting to wallet page for long time~~~~

**Comment by magnusmyklebost** [comment]
same. my plots were at 92%. On the CPU it seems like its still going. how long to wait?

**Comment by keithsavage777** [comment]
me also, both PCs

**Comment by keithsavage777** [comment]
should i del the chia temp files. would that work

**Comment by justinlovato** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/4102#issuecomment-834884010

This is issue seems open on multiple threads.
