### ISSUE TITLE
Unable to Sync

### ISSUE THREAD

**Issue by AK1244** [Chia-Network/chia-blockchain#4302]
I am unable to Farm due to the app not syncing. On the home page it says “not synced” but in the wallet under wallet status is says “synced”. I am on Windows 10 using Chia Version 1.1.4.

**Comment by JessePinkmanVN** [comment]
Same issue here

**Comment by mrnguyenphuc** [comment]
see at post #4296 , we have so many people get this issue today. All get stuck at block 255143.

**Comment by dumpstar85** [comment]
Same

**Comment by dutchmulti** [comment]
I gues if you wait it will sync again? i have 6 almost done plots...

**Comment by DFAnk1** [comment]
Syncing now works again !

**Comment by dutchmulti** [comment]
I plot in one day 2tb and thats still superslow if you want to mine some chia.. Also i wonder if the plots can move to a pool?

**Comment by Muffexx** [comment]
Hello @AK1244,
if your issue is resolved please consider closing this thread.
regards
muffexx
