### ISSUE TITLE
[BUG] GUI on Ubuntu causes systemwide and severe graphical glitches

### ISSUE THREAD

**Issue by pgroyal22** [Chia-Network/chia-blockchain#4307]
**Bug Description:**
Graphical glitches both in the Chia GUI and other apps that are open while the Chia GUI is open. Graphical glitches come in the form of misplaced divisions within apps, misplaced text, flashing and even freezing of the whole system GUI. 

**Steps to reproduce the behavior:**

1. Install the Chia GUI either through downloading the .deb package and installing through apt, or following installation guide and running the shell scripts provided
2. Open the Chia GUI
3. Start plotting (happens with both parallel and sequential) or syncing current plots, then move out of the app
4. Graphical glitches start cropping up within and outside of the GUI, sometimes entirely freezing entire system GUI
5. Graphical issues persist until reboot

**Screenshot**
![image](https://user-images.githubusercontent.com/57504772/117578198-376a0500-b0bb-11eb-9bdb-af2299a7dc89.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version: Ubuntu 20.04.2 (default display drivers)
- CPU: Intel i7-4790k

**Additional context**
Uninstalling the GUI entirely fixes the problem, while closing out of the application seems to leave some lingering effects until the next reboot

**Comment by as1543100166** [comment]
I met once in Debian

**Comment by JaNd3eS** [comment]
I also had an episode like this. In my case the whole system freezed, even if the plotting processed were still running in the background.     
My advice is to don't mess too much with GUI. 
Avoid using it, except from setting up plotting queues and monitoring them.     
Prefer the CLI. With 4 commands you have almost full control of what's going on: 

1. chia farm summary 
2. chia show -s
3. chia show -c
4. chia show -a ip:port 

Personally, I also check debug.log file for errors and for blocks to correctly pass the plot filter, once in a while.

cat ~/.chia/mainnet/log/debug.log | grep error
cat ~/.chia/mainnet/log/debug.log | grep eligible

Hope it helps.
