### ISSUE TITLE
[BUG] Обрывается синхронизация

### ISSUE THREAD

**Issue by sl777va** [Chia-Network/chia-blockchain#4311]
**Describe the bug**

**To Reproduce**

1. Постоянно обрывается синхронизация, слетает фарминг. Длится это около 1 часа, появилось после обновления до версии 1.1.4, через час восстанавливается, и снова обрывается, параллельно идёт плоттинг. Новые соединения не добавляются, просто ничего не происходит. Как быть кто то подскажет? Или это вся сеть так логает?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [Intel Xeon E5-2620 v4 @ 2.10GHz]

**Additional context**

**Comment by zombie665** [comment]
Сегодня проблемы в сети... на рэддит пишут.
