### ISSUE TITLE
Chia Blockchain

### ISSUE THREAD

**Issue by Kabalista** [Chia-Network/chia-blockchain#4316]
Статус - Не синхронизирован, хотя соединение с интернетом есть.

![chia](https://user-images.githubusercontent.com/83918792/117580351-3d360980-b100-11eb-8d02-26e6737d4c6a.jpg)

**Comment by knightblackm** [comment]
you have some option.
1. upgrade to 1.1.4 or downgrade to 1.1.1;
2. if you know a friend have synced app take the df file and then its faster;
3. wait more! it have bug on 255,175 From 2 hours ago.

**Comment by Kabalista** [comment]
Thanks a lot)

вс, 9 мая 2021 г., 19:58 knightblackm ***@***.***>:
