### ISSUE TITLE
[BUG]Can't download version 1.1.5

### ISSUE THREAD

**Issue by engeldan** [Chia-Network/chia-blockchain#4319]
By click this link: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#Windows 
starting download a 1.1.4 version. Please, fixit

**Comment by abueide** [comment]
its not done building the release, please be patient and don't open issues like this. instead ask in keybase, the forum or on reddit.

**Comment by engeldan** [comment]
> its not done building the release, please be patient and don't open issues like this. instead ask in keybase, the forum or on reddit.
Please, see the chia.net. New version has been released 1 hour ago

**Comment by engeldan** [comment]
I resolved this problem. New version on this page:
https://download.chia.net/?prefix=install/

**Comment by mauver** [comment]
https://download-chia-net.s3-us-west-2.amazonaws.com/install/ChiaSetup-1.1.5.exe try this

**Comment by abueide** [comment]
ah you're right it seems the ci/cd is done now, maybe it doesn't autopush the builds to the github artifacts?
