### ISSUE TITLE
Stuck at 11%

### ISSUE THREAD

**Issue by HunteHax** [Chia-Network/chia-blockchain#4321]
For some days I have been looking and reading about chia and how it actually it works. Problem is that after successfully setting up the GUI version and getting my 24 mem.words I end up stuck at 11%. At my first try I left the plotting for more than 25 hours just to find it at 11%. Restarted the process by deleting both temp and final folders and stared again. At my second try I am again at 11%. This time I checked both the log file and the task manager.  Task manager seems to show that the program is running, but in the log file for 3 hours now nothing is happening.

**Comment by AloeKing** [comment]
Do you have enough space on plotting SSD/HDD? k32 requires ~270GB empty space to be able to plot.

**Comment by grayfallstown** [comment]
Take a look at `<your user folder>\.chia\mainnet\plotter\*` and `<your user folder>\.chia\mainnet\log\debug.log` to see what is causing it.

**Comment by HunteHax** [comment]
> Do you have enough space on plotting SSD/HDD? k32 requires ~270GB empty space to be able to plot.

I am using an ex mining rig with a spare WD 750gb hdd. I know that SSD is recommended for the temp folder. However, I am just doing this as a test run to determine if I want to jump in the farming.

**Comment by HunteHax** [comment]
> Take a look at `<your user folder>\.chia\mainnet\plotter\*` and `<your user folder>\.chia\mainnet\log\debug.log` to see what is causing it.

![chialog](https://user-images.githubusercontent.com/59821086/117583781-c4d84400-b111-11eb-88d2-3e37e24985d6.PNG)

here is an image from my second plot run. From 4 a.m today till now 9 p.m nothing has moved, I believe this is not normal. Checked log txt file and nothing like it has stopped in time.

**Comment by grayfallstown** [comment]
Did you check running tasks? The process might be dead. You can expect one new log line at least every 15 minutes in phase 1 on hdds.. (given k32) this is not normal

**Comment by HunteHax** [comment]
> Did you check running tasks? The process might be dead. You can expect one new log line at least every 15 minutes in phase 1 on hdds.. (given k32/128 buckets) this is not normal

Well chia process is nowhere to be seen. Guess I will try for a third time now. Let's hope tomorrow morning I will have better luck

**Comment by grayfallstown** [comment]
Are you running on windows, linux or mac? There might be out of memory problems? Enough free ram? (Look both at virual and actual memory)

**Comment by HunteHax** [comment]
Windows 10 with a single 4 gb memory stick. Virtual memory set to 16 gb due to pc being an ex eth miner

**Comment by grayfallstown** [comment]
Set you buffer to about 2500 MB then. This will be slower, but not run out of memory. If your system has 4, windows takes 1 and you might use the default buffer settings of 3,75GB... that does not add up and not everythink can end up in the pagefile/virtual memory.
Consider setting the buckets to 160 if it lets you, than it should be able to handle that memory just fine.
In the gui you have to click on advanced options to see buffer and bucket sizes if I remember correctly

**Comment by HunteHax** [comment]
Thanks for the help. Will try it and let you know if I have been able to pass the 11% mark

**Comment by quantum8** [comment]
I'm having the same issue, running on ubuntu 20.04 and stuck at 11% with the same log as [above](https://github.com/Chia-Network/chia-blockchain/issues/4321#issuecomment-835864358)

Updated to 1.1.5 and re-running through the GUI hoping that it doesn't get stuck this time.

**Comment by HunteHax** [comment]
> Set you buffer to about 2500 MB then. This will be slower, but not run out of memory. If your system has 4, windows takes 1 and you might use the default buffer settings of 3,75GB... that does not add up and not everythink can end up in the pagefile/virtual memory.
> 
> Consider setting the buckets to 160 if it lets you (with buffer at 2500MB!), than it should be able to handle that memory just fine.
> 
> In the gui you have to click on advanced options to see buffer and bucket sizes if I remember correctly
> 
> Expect > 24h plotting time for one k32 plot..

Quick update, thanks to your tip I am finally able to see an improvement and I am already at 50% which is perfect for me. Thanks again!

**Comment by quantum8** [comment]
Update for me too: using 1.1.5 and it finally was able to complete a plot.

**Comment by grayfallstown** [comment]
Good to hear, can this be closed now?

**Comment by quantum8** [comment]
It got stuck around the 40% mark on the next plot I tried. So something still isn't right.

I'm attempting again and it's up to 84% so far.

Are there any further logs that can be provided, or added into the code? Each time it fails there doesn't seem to be anything apparent in the logs.

**Comment by KaLul** [comment]
Hi!
Iam using Ubuntu 21.04 64 bit and i cant parallel plot. Its always stuck at 11% or/and 4%.

I started 3 plots. When i woke up today , 1 was 100% and was moved to my external hdd.
The other 2 at 4 and 11%.

So i tried to just make 2 parallel.
One is doing well so far but the other also stuck at 11% which stopped at bucket 0 on table 4.

**Comment by quantum8** [comment]
@KaLul I've managed to do a few more plots now that I'm using the commandline. Something must be broken on the GUI side for it to freeze up like this.

**Comment by KaLul** [comment]
> @KaLul I've managed to do a few more plots now that I'm using the commandline. Something must be broken on the GUI side for it to freeze up like this.

ok then. can you please give me a start up on using commandlines please?
im absolutely fresh on Ubuntu but i know about terminal a little.

**Comment by quantum8** [comment]
@KaLul from the docs on [this page](https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference), I use:

`chia plots create -k32 -b 4000 -t <tempdir> -d <plotsdir>`

Where <tempdir> is the temporary directory, eg: ~/chia/tempPlots
and <plotsdir> is the final directory where finished plots go:, eg: ~/chia/plots
