### ISSUE TITLE
my existing plot not showing up in chia

### ISSUE THREAD

**Issue by andre855duarte** [Chia-Network/chia-blockchain#4326]
i had written a plot and it got to 100 percent but never moved on. I checked the destination location and the file matched the size of the temp file on the ssd, so i assumed it was done. left it like this for a few hours but no change so i just closed the program and restarted. my files are present but do not show up in the program. I tried to add file destinations but still nothing.

**Comment by caishubao** [comment]
右键硬盘属性 选择安全 全部勾上就可以写入了。

**Comment by grayfallstown** [comment]
Take a look at `<your user folder>\.chia\mainnet\log\debug.log` and also run `chia plots check` on your cli to see what is going on.
