### ISSUE TITLE
I can´t finish any plot - não consigo finalizar mais nenhum plot

### ISSUE THREAD

**Issue by FranciscoRAR** [Chia-Network/chia-blockchain#4327]
Hey guys, how are you doing?

Since version 1.14, i can't I can't finish any plot.

I noticed that the initial message, which previously informed the temporary directory and the final one, now only presents the temporary directory twice (same thing for version 1.15).

Fact is the plots stop at 81% and do not complete anymore.

Dou you have some hint to help?

Tks!

Olá pessoal. Há uns dois dias, depois da versão 1.14, não consigo terminar nenhum plot. Percebi que a mensagem inicial, que antes informarva o diretório temporário e o final, agora só apresenta duas vezes o diretório temporário (mesma coisa para a versão 1.15). Fato é que os plots param com 81% e não completam mais.

Se alguém puder ajudar, agradeço.

Abçs.

**Comment by josinaldobarbosa** [comment]
Vê se retorna algum erro em `<your user folder>\.chia\mainnet\log\debug.log`

**Comment by FranciscoRAR** [comment]
> Vê se retorna algum erro em `<your user folder>\.chia\mainnet\log\debug.log`

Oi Josinaldo, obrigado.

Existem 7 arquivos de lote, todos com o mesmo conteúdo, mas não sei o que significa. Eu estou com a versão 1.15 e comecei um novo lote, para testar. Olha o conteúdo do arquivo:


2021-05-09T14:02:32.976 farmer asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 119, in _read_from_self
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
2021-05-09T14:02:32.989 farmer asyncio                    : ERROR    Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 119, in _read_from_self

**Comment by FranciscoRAR** [comment]
It´s ok in version 1.15

Está ok na versão 1.15
