### ISSUE TITLE
[BUG] Help - Plot stopped

### ISSUE THREAD

**Issue by Yajiinn** [Chia-Network/chia-blockchain#4330]
My pc ; 
Cpu: i7 8700k
Ram: GSKILL 16GB (2x8GB) Trident Z Neo RGB 3600MHz CL16 DDR4 Dual Kit Ram
m2:  XPG 1TB SX8200 PRO ( i used for temp )
m2: WD Blue SN550 NVMe SSD ( i used for temp )

Plot stops at 87% and does not continue. I wait 3-4 hours but it doesn't change. I delete plot and create a new plot but it stop at 87%. I formatted the computer but it didn't work. I am using port 8444 but it did not work. No errors in the log file. No problem in sync. Please help. Thanks.
![Bug](https://user-images.githubusercontent.com/83921458/117583657-0f0cf580-b111-11eb-80e8-f1ca010bf8b5.png)
![Bug2](https://user-images.githubusercontent.com/83921458/117583661-16340380-b111-11eb-8e24-835d90c97b5e.png)

**Comment by FranciscoRAR** [comment]
> My pc ;
> Cpu: i7 8700k
> Ram: GSKILL 16GB (2x8GB) Trident Z Neo RGB 3600MHz CL16 DDR4 Dual Kit Ram
> m2: XPG 1TB SX8200 PRO ( i used for temp )
> m2: WD Blue SN550 NVMe SSD ( i used for temp )
> 
> Plot stops at 87% and does not continue. I wait 3-4 hours but it doesn't change. I delete plot and create a new plot but it stop at 87%. I formatted the computer but it didn't work. I am using port 8444 but it did not work. No errors in the log file. No problem in sync. Please help. Thanks.
> ![Bug](https://user-images.githubusercontent.com/83921458/117583657-0f0cf580-b111-11eb-80e8-f1ca010bf8b5.png)
> ![Bug2](https://user-images.githubusercontent.com/83921458/117583661-16340380-b111-11eb-8e24-835d90c97b5e.png)

The same proble

**Comment by FranciscoRAR** [comment]
Same problem as mine.

I was creating the plots normally, but as of version 1.14, the problems started.

Now I am plotting the first plot in version 1.15. Let's hope.

**Comment by Yajiinn** [comment]
I'm trying again with version 1.1.5 . I entered  number of buckets as 64.  I'll write the result.

**Comment by variableresults** [comment]
Can you check the Details tab of Task Manager when this happens? You have the same issue I've reported if you see chia.exe with only something like 50-64kb of RAM usage. 

Also, the port # doesn't matter for plotting since that's purely local. You can do it while not connected to the mainnet. 

A couple posts on the same / similar issue: https://github.com/Chia-Network/chia-blockchain/issues/4264 https://github.com/Chia-Network/chia-blockchain/issues/4220

**Comment by Yajiinn** [comment]
Thank you for your interest.

**Comment by njtnestor** [comment]
Same problem in 1.1.5 when i run in paralel some freeze

**Comment by Yajiinn** [comment]
I had the same problem in 1.1.4 version. This problem is not solved :(  .   I'm still waiting and looking for a solution

**Comment by Yajiinn** [comment]
I think I found the problem 


2021-05-13T12:15:02.954 daemon _main_                   : ERROR    Unexpected exception trying to send to websocket: code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "websockets\protocol.py", line 838, in transfer_data
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chia\daemon\server.py", line 187, in safe_handle
  File "websockets\protocol.py", line 555, in send
  File "websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by Yajiinn** [comment]
I solved the problem. I tested the ram and it was faulty. The problem was solved when I used new ram.
 
![rams](https://user-images.githubusercontent.com/83921458/118361757-76092f00-b595-11eb-8413-22ecfa03d57b.jpg)
