### ISSUE TITLE
[BUG] Total Plot size shown on Plots is false

### ISSUE THREAD

**Issue by yumus84** [Chia-Network/chia-blockchain#4331]
Hello, even if I have 12 plots in total, total plot size is showing 1.188 TiB.

As  my 11th plot was completed, it has shown that I have 11 Plots, but the total plot size was still about 9 TiB..

I expected that, it would show 1.188 TiB with 11 plots.

After my 12th plot was completed, it showed that 12 Plots, but the total plot size inscreased to 1.188 TiB.

In conculusion it shows after many hours still the same plot size: 1.188 TiB with 12 plots. It means the showned total plot size is 1 plot less than it should be.

I deleted the pilot directory and added my pilot directory to solve the problem again, but noting changed. 

![Farm Overview](https://user-images.githubusercontent.com/73252464/117584355-c18e8980-b10c-11eb-8132-323b5446af6a.PNG)
![Total Plot size](https://user-images.githubusercontent.com/73252464/117584357-c2272000-b10c-11eb-9547-02d4480f251b.PNG)

thank you for any help.

**Comment by grayfallstown** [comment]
try to run `chia plots check`. Maybe the plots are broken (4 of mine were)

**Comment by yumus84** [comment]
thanks for your fast reply, what do you mean with chia plots check? It is a software to check if all plots are ok? What should I do, if one plot is broken? Any way to repair it or it is useless?

**Comment by grayfallstown** [comment]
It is a command line tool chia brings with it. On windows you find it at `C:\Users\<your username>\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe` Run it from the command line (windows key -> cmd) and run `C:\Users\<your username>\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe plot check`.
If you have 1.1.4 or another version installed, replace the 1.1.5 with it. 
chia.exe plot check will then test all plots it finds and tell you what is wrong or if everything is ok.

**Comment by yumus84** [comment]
thanks a lot for your quick reply,  I have 1.1.4  installed, I will replace the 1.1.5 with it after all my plots finished in order to check, whats is wrong.

**Comment by grayfallstown** [comment]
You can check it with 1.1.4, too, you just need to replace the version number in the command I posted

**Comment by yumus84** [comment]
I run the plots check. All of the plots  seem to be valid. But somehow i do not understand the total plot size of 1.18768, because

12*101.4 GiB= 1.216.8 TiB  not 1.18768 TiB or maybe its true the relation os GiB and GByte is confusing...

**Comment by yumus84** [comment]
![Uploading Plot Check.PNG…]()

**Comment by yumus84** [comment]
The plot check report 
![Plot Check](https://user-images.githubusercontent.com/73252464/117586351-efc59680-b117-11eb-8709-9c3a049e8537.PNG)

**Comment by gromran** [comment]
> 12*101.4 GiB= 1.216.8 TiB not 1.18768 TiB or maybe its true the relation between GiB and GByte (1x1024) is confusing...
Thats the problem... only morons and non IT use GiB etc

**Comment by Plopsi** [comment]
> 12*101.4 GiB= 1.216.8 TiB not 1.18768 TiB or maybe its true the relation between GiB and GByte (1x1024) is confusing...

Actually 12*101.4GiB are 1216.8GiB which are ~1.188TiB - as the plots all have slightly different sizes this seems correct

GiB -> TiB you need to divided by 1024.

**Comment by yumus84** [comment]
yes, thanks for the information
