### ISSUE TITLE
[help] Address changed after updating to 1.1.5

### ISSUE THREAD

**Issue by HououinKyouma01** [Chia-Network/chia-blockchain#4336]
**Describe the issue**
After updating to 1.1.5 my wallet address changed.
Console shows new one too. Not to mention that explorer is showing something strange on that address.

**To Reproduce**
Update to 1.1.5 from 1.1.4

**Expected behavior**
Having old address?

**Screenshots**
-

**Additional context**
What to do now? Do I need to update farmer and pool addresses to get the rewards of new blocks?

**Comment by caglart85** [comment]
hi,

[https://github.com/Chia-Network/chia-blockchain/issues/4300](url)

the address for receiving the prize is changing
Coins going to those changed addresses are not added to the wallet balance.
nobody answers the question.
we are left to our destiny

**Comment by HououinKyouma01** [comment]
So what to do? Generate new address and change farming and pool address to that new one?
And what after? Do I get the newly generated address when I import my passphrase on new device?

**Comment by caglart85** [comment]
I know that plots do not work at any other address than the one from which they were created.
I could not find an answer to this question either.
it's pretty simple actually.
Will plots created at one address continue to run when they are moved to another address?

**Comment by caglart85** [comment]
everyone is left to their fate.
people try to solve problems by trial and error.

**Comment by piszpunta** [comment]
I have the same problem

**Comment by HououinKyouma01** [comment]
Bitcoin has something like sub-addresses that belong to main address (if I understand it correctly) so maybe this is similar too?
The best way to test it is to send 0.001 chia to "old" address and see if it appear on your balance. Unfortunately I have 0 chia (thankfully I sent everything to the exchange immediately after receiving rewards of the blocks that I found).

**Comment by ytx1991** [comment]
same issue here. The new address has 1.25 XCH which not belong to me I believe. Currently, the wallet cannot sync so I cannot do anything for that unexpected xch.

**Comment by caglart85** [comment]
Can a friend of the developers look at this issue now?

I can send him a screenshot if he wants.


[https://github.com/Chia-Network/chia-blockchain/issues/4300](url)

**Comment by ytx1991** [comment]
I think I figured out, it doesn't matter, since one private key can manage multiple public keys. You can hover on the ? icon in the GUI and see the explaination. But it's still weird to change the public key of the wallet without user confirm.
