### ISSUE TITLE
[help] upgraded to 1.1.5 chia version showing 1.1.6.dev0

### ISSUE THREAD

**Issue by nicholaslane** [Chia-Network/chia-blockchain#4342]
Is this to be expected.

running on ubuntu 20.04. command from cli "chia version"

**Comment by caglart85** [comment]
hi,

[https://github.com/Chia-Network/chia-blockchain/issues/4300](https://github.com/Chia-Network/chia-blockchain/issues/4300)

**Comment by nicholaslane** [comment]
dev0 is a git error that can be ignored. sync is passing plots.

**Comment by jszetoo** [comment]
> hi,
> 
> #4300
> 
> the address for receiving the prize is changing
> Coins going to those changed addresses are not added to the wallet balance.
> nobody answers the question.
> we are left to our destiny

better double check ! mine happen the same too ( a different address )
