### ISSUE TITLE
[help] Cannot sync ... Stucked at 254848

### ISSUE THREAD

**Issue by ozgurcengiz2008** [Chia-Network/chia-blockchain#4350]
**I Cannot sync with server. I Stucked at 254848**

My farm has been out of sync since one and a half days. I also downloaded the new version (1.1.5) but it hasn't improved. What could be the source of the problem? How can I fix.

Os: Windows 10

**Comment by secco04** [comment]
try adding node-eu.chia.net:8444  at connect to peer 
maybe the local full node has a bug in 1.1.5 ?

**Comment by ozgurcengiz2008** [comment]
> node-eu.chia.net:8444'ü eşe bağlanırken eklemeyi deneyin
> yerel tam düğümde 1.1.5'te bir hata olabilir mi?

secco04...I've tried you said, but not a chance :(

**Comment by benavidca** [comment]
I followed this procedure and works for me every time my syncying is stopped by X unknown reasons
- Verify you are using the latest version
- Stop the GUI and kill all processes related to chia network
- Delete the C:\Users\YourUser\.chia\run\ folder

**Comment by ozgurcengiz2008** [comment]
> I followed this procedure and works for me every time my syncing is stopped by X unknown reasons
> 
> * Verify you are using the latest version
> * Stop the GUI and kill all processes related to chia network
> * Delete the C:\Users\YourUser.chia\run\ folder
> 
> After that, all of the peer connections are automatically added

Unfortunately, this method didn't work either. I am connecting with another node and it is establishing a connection with the node. However, even if it sees the top height of the node, there is no change in my value. Here below is the debug log:

.....
2021-05-10T01:59:22.045 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-05-10T01:59:22.051 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<ChiaServer.incoming_api_task.<locals>.api_call() done, defined at chia\server\server.py:482> exception=CancelledError()>
concurrent.futures._base.CancelledError
2021-05-10T02:09:46.942 full_node chia.full_node.weight_proof: ERROR    failed validating weight proof recent blocks
2021-05-10T02:09:47.008 full_node full_node_server        : WARNING  Banning node-eu.chia.net for 600 seconds
2021-05-10T02:09:47.011 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 651, in _sync
ValueError: Weight proof validation failed
.....

**Comment by benavidca** [comment]
Did you delete a plot? Or what did you do to get this error?
My best working peer is 71.237.22.222:8444 try adding it

**Comment by ozgurcengiz2008** [comment]
> Did you delete a plot? Or what did you do to get this error?
> My best working peer is 71.237.22.222:8444 try adding it

Only power was cut while creating plot. But then the system was working. I also had one k-25 plot, I deleted it.

Right now, I've reloaded everything, loaded plots, wallet. Let's see it started synchronizing. It started from 0, I hope it doesn't stop at 254848 again :))

**Comment by nothinglastsforever** [comment]
> > Did you delete a plot? Or what did you do to get this error?
> > My best working peer is 71.237.22.222:8444 try adding it
> 
> Only power was cut while creating plot. But then the system was working. I also had one k-25 plot, I deleted it.
> 
> Right now, I've reloaded everything, loaded plots, wallet. Let's see it started synchronizing. It started from 0, I hope it doesn't stop at 254848 again :))

Did it resolve for you? Having the same issue.

**Comment by ozgurcengiz2008** [comment]
> Did it resolve for you? Having the same issue.

yes, it works. But, whole sync process takes two days ;) In addition this, try this peer nodes:
93.32.37.31
61.68.243.206
68.150.217.182
159.69.138.138 
35.186.176.169
116.41.82.20
