### ISSUE TITLE
[help]  is: issue is: open Lots not found there were 23 lots, I made 3 more and do not appreciate it, now the 3 appear and do not identify the 23 ???

### ISSUE THREAD

**Issue by ra339282** [Chia-Network/chia-blockchain#4356]
**Describe the issue**
PLEASE NOTE!: The issue tracker is NOT a place to seek general support. You are better served starting a conversation in the Discussions area at https://github.com/Chia-Network/chia-blockchain/discussions or in the Keybase.io #support channel. If you create a support request here, it may or may not receive a response before being closed, and we cannot guarantee a timely response, or one at all. In the event that your issue is deemed to be the result of a bug, we will endeavor to review and update it accordingly as such instead of closing it.

**To Reproduce**
Steps that led up to your issue.

**Expected behavior**
A clear and concise description of what you expected to happen before you encountered your issue.

**Screenshots**

**Additional context**

**Comment by ra339282** [comment]
is: issue is: open Lots not found there were 23 lots, I made 3 more and do not appreciate it, now the 3 appear and do not identify the 23 ???

**Comment by Plopsi** [comment]
I'm just guessing but he/she is missing 23 (P)lots while there should now be 26 :D

Check that the plot directory is still set. on linux try chia plot check -n 5 that way it rereads the plot-directory. If your plot is on USB or NAS or other external drives, check if it has not been gone into power saving mode or disconnected. Try to restart chia and check again (also that the plot-file-directory is set). Chia retries the plot-folder every 5min if i'm not wrong.

**Comment by ra339282** [comment]
Directory is defined in the correct way, excludes the directory and added a few times and the program does not recognize itself, I quit the program and installed
new version is synchronizing but still recognizing only 3 lots, the operating system is win. Grateful for the attention.

**Comment by ra339282** [comment]
> Estou apenas supondo, mas ele / ela está perdendo 23 (P) lotes, enquanto agora deveria haver 26: D
> 
> Verifique se o diretório de plotagem ainda está definido. no linux, tente chia plot check -n 5 para que ele releia o diretório de plotagem. Se sua plotagem estiver em USB ou NAS ou outras unidades externas, verifique se ela não foi para o modo de economia de energia ou desconectada. Tente reiniciar o chia e verifique novamente (também se o diretório do arquivo de plotagem está definido). Chia tenta novamente a pasta de plotagem a cada 5 minutos, se não estou errado.

Directory is defined in the correct way, excludes the directory and added a few times and the program does not recognize itself, I quit the program and installed
new version is synchronizing but still recognizing only 3 lots, the operating system is win. Grateful for the attention.

**Comment by ZorgWbm** [comment]
Same problem on my site
