### ISSUE TITLE
Stuck on Connecting to wallet

### ISSUE THREAD

**Issue by Mdiallo2001** [Chia-Network/chia-blockchain#4360]
Hey can anybody please help me. The chia app was working fine until this morning. When i started the app, my screen is stuck on connecting to wallet for hours
![Capture](https://user-images.githubusercontent.com/70229942/117588990-10302980-b0f5-11eb-9f7f-9b3873487641.PNG)

**Comment by sdickert** [comment]
Same here.  On M1 and tried both with the development method and the DMG version for Mac.   I am wondering if I need to delete the wallet details in my keychain.

**Comment by Mdiallo2001** [comment]
It worked for me

**Comment by qanei** [comment]
Same here.

**Comment by qanei** [comment]
When i started the app, my screen is stuck on connecting to wallet for hours
