### ISSUE TITLE
[help] Do I have to upgrade the chia version in harvester+plot only machine to 1.1.5?

### ISSUE THREAD

**Issue by potato1992** [Chia-Network/chia-blockchain#4361]
As 1.1.5 fix a bug of negative values in  uint64, I can understand I have to upgrade the software in my full node machine.
But do I have to upgrade the chia software in other harvester+plot machine for this version?

**Comment by buildingwatsize** [comment]
> making this update not mandatory but is recommended

You can found it in [](https://github.com/Chia-Network/chia-blockchain/releases/tag/1.1.5)
