### ISSUE TITLE
not synced

### ISSUE THREAD

**Issue by EmilianH** [Chia-Network/chia-blockchain#4364]
synchronizes 5 minutes and then cuts off for hours, it works very badly

Version 1.1.5

**Comment by PC101guy** [comment]
all by design to drop the price just intime for major exchanges to pic up the coin,  just keep plotting and don't mind the politics.

**Comment by Plopsi** [comment]
Best to keep a local node, on a laptop for example, synced and update them successively and only when the other one has peers again. The peer discovery seem to take often ages.

**Comment by secco04** [comment]
try adding a full  node at connect to other peers in gui : node-eu.chia.net:8444 for me it worked... but i dont know if its fine ;D

**Comment by EmilianH** [comment]
> try adding a full node at connect to other peers in gui : node-eu.chia.net:8444 for me it worked... but i dont know if its fine ;D

thanks but no working, the node autodelete y 1 minute

**Comment by EmilianH** [comment]
still no synced

**Comment by Plopsi** [comment]
try

213.171.214.61:8444
or
68.195.189.55:8444

not mine, but the best I have in my list.

**Comment by EmilianH** [comment]
> try
> 
> 213.171.214.61:8444
> or
> 68.195.189.55:8444
> 
> not mine, but the best I have in my list.

my friend I write the ip but they auto delete after 5 seconds

**Comment by Plopsi** [comment]
maybe they are full.. I just fished them out of my list with the most MBit down :) - hope you not only wrote the ip but also the port :D - chia doesn't seem to be capable yet to just try the default port ^^

**Comment by EmilianH** [comment]
> maybe they are full.. I just fished them out of my list with the most MBit down :) - hope you not only wrote the ip but also the port :D - chia doesn't seem to be capable yet to just try the default port ^^

Of course i wrote the port but doesnt work, still not synced :(

**Comment by Plopsi** [comment]
try one of these:

https://chia.keva.app/

last time i got working ones which were pretty fast

**Comment by EmilianH** [comment]
> try one of these:
> 
> https://chia.keva.app/
> 
> last time i got working ones which were pretty fast

Thanks i will try

**Comment by 11118** [comment]
https://www.youtube.com/watch?v=ffJXcfUZ6FY

I solved it according to the method on YouTube

You guys try this method

Someone in the comments also used this method and quickly forgot to sync

《 Wasted 128 minutes of my time! The investigation solves the problem that the Chia Blockchain full nodes have been unable to synchronize during the Chia coin mining. Take a look at this, and maybe you can save 2 hours of exploring time by avoiding detours! 》

**Comment by EmilianH** [comment]
nothing works!!! what happend?

**Comment by EmilianH** [comment]
i try all ip list and not wornking

> > try one of these:
> > https://chia.keva.app/
> > last time i got working ones which were pretty fast
> 
> Thanks i will try
