### ISSUE TITLE
[BUG] Plotting Error on Windows beta 14

### ISSUE THREAD

**Issue by dorkmo** [Chia-Network/chia-blockchain#437]
**Describe the bug**
"Caught plotting error: Do not have enough memory. Need 3079.200000 MiB"

**To Reproduce**
When starting a new plot

**Desktop**
- OS: Windows 
- CPU: Intel® Core™ i7-9700K
- 16MiB Ram

**Comment by hoffmang9** [comment]
You will probably need to work around this with a minimum -b of 3592 for the rest of the otherwise default values on a k=33. We'll think about how to handle this for 33+ for next release.

**Comment by dorkmo** [comment]
hasnt happened again since that first time...

i was attempting k33's so maybe it was that

no issues on beta15, the new auto ram selector is nice.
