### ISSUE TITLE
[BUG] wallet not_initialized of testnet5

### ISSUE THREAD

**Issue by yuzhongrong** [Chia-Network/chia-blockchain#4374]
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ CHIA_ROOT="~/.chia/testnet" chia wallet show

No online backup file found, 
 Press S to skip restore from backup 
 Press F to use your own backup file: Exception from 'wallet' 'not_initialized'

**Comment by mariano54** [comment]
Please use testnet7 if you want to join testnet, or mainnet.

**Comment by yuzhongrong** [comment]
not testnet7 in 1.1.4 version

**Comment by yuzhongrong** [comment]
need to upgrade to  1.1.5?
