### ISSUE TITLE
[REQ] Always hide private keys and mnemonic

### ISSUE THREAD

**Issue by ytx1991** [Chia-Network/chia-blockchain#4380]
**Describe the request**
In case of some third-party software trying to use the CLI tool to access the users private keys, the CLI shouldn't show any sensitive information. There are many third-party plotting/mining tools may cause many users in a risk!

**Comment by latinvm** [comment]
This makes a lot of sense, it was something that surprised me quite a bit. The private keys / mnemonic should be encrypted and password protected, being able to export them using a simple CLI command is asking for problems. A malicious 3rd party tool could easily wipe out entire wallets.

**Comment by ytx1991** [comment]
Exactly, I'm surprised too. This could be a serious security issue for everyone. Any software which has Internet access can steal the private keys potentially.

**Comment by latinvm** [comment]
I'm surprised this discussion has not gained more traction yet, basically all private keys should be password protected... when you start any Chia wallet/daemon that requires access to a private key it should be unlocked using a password.
