### ISSUE TITLE
[BUG] Err.COIN_AMOUNT_NEGATIVE

### ISSUE THREAD

**Issue by Spider4896** [Chia-Network/chia-blockchain#4381]
Hi, 

Do I need to be concern with this error in the logs?  If so, how is it resolved?

2021-05-09T21:28:01.451 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id **_CENSORED_**, status 3 error: Err.COIN_AMOUNT_NEGATIVE

This error is continuously popping up.

Thanks!

**Comment by Glutamat42** [comment]
I'm quite sure you don't have to worry about this. There was a bug causing some problems today with negative coin amounts and as far as i understand it this is just a notification about an invalid transaction you received. 

Here are two links about this issue

- https://github.com/Chia-Network/chia-blockchain/releases
- https://chiaforum.com/t/fyi-network-is-down-block-255108-upgrade-to-1-1-5-asap/2292/21

Note: I'm not a chia dev

**Comment by mariano54** [comment]
That's fine, as long as you are on version 1.1.5. Older versions might have problems farming.

**Comment by gntz555** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/6454209/debug.log)

Hi, I have the same issues, plus some more. Did I lost chia coins??

**Comment by Glutamat42** [comment]
> 
> 
> [debug.log](https://github.com/Chia-Network/chia-blockchain/files/6454209/debug.log)
> 
> Hi, I have the same issues, plus some more. Did I lost chia coins??

It looks like you have some serious issues with your installation. You probably didn't loose coins, but you won't farm (log says: not farming) which also means "loosing coins" in some terms. 
I would try to reinstall the wallet, but make sure to back up your mnemonics (and better also create a backup of your .chia folder). 

I think your question about COIN_AMOUNT_NEGATIVE should be answered by @mariano54, your other issues don't belong to the topic of this ticket. Also this is a bug/issue tracker, not a help forum. You might consider to ask somewhere else (eg reddit) for help.

**Comment by Prawate** [comment]
There is a problem too (v15)

**Comment by blackflash** [comment]
I confirm issue on version 1.1.5 -> 2021-05-20T17:27:21.959 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id 5e0fd02fa737a16dd9252f00973c1de56ebd70a947592925f1389673e4a78c2a, status 3 error: Err.COIN_AMOUNT_NEGATIVE

**Comment by gallem7777** [comment]
This bug still exists, even in v1.1.6

2021-06-02T20:03:24.508 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id ..., status 3 error: Err.COIN_AMOUNT_NEGATIVE
