### ISSUE TITLE
[BUG] Cannot delete plot properly and reserved storage still remains

### ISSUE THREAD

**Issue by kaizvn** [Chia-Network/chia-blockchain#4384]
**Describe the bug**
I try to remove a plot to reconfigure, but it freeze my PC and then stop responding. After close it and reopen I can access the app but the reserve storage still remain and I cannot clear it.

**To Reproduce**

1. Go to 'Plot'
2. Click on 'New Plot'
3. Config and create new Plot.
4. Then remove it
5. App was not responding.
6. Try to close and reopen it.
7. The reserve storage (about >200GB) still remain and cannot clear.

**Expected behavior**
I can clear the temporary files/folders that Chia created to get back 200Gbs.

**Screenshots**
![image](https://user-images.githubusercontent.com/3988087/117601559-e4568780-b178-11eb-8015-46a56685d11a.png)

**Desktop (please complete the following information):**

- OS:  windows
- OS Version/Flavor: Windows 10 Pro 120.2212.551.10
- CPU: AMD Ryzen 5 3600
- Chia client:  windows version 1.1.5

**Comment by MustDhiMust** [comment]
close all Chia program through task manager

**Comment by kaizvn** [comment]
> close all Chia program through task manager

I did and uninstall chia also but it didn't work.

**Comment by dtuk327** [comment]
Boot into Windows 10
Double-click on Computer (My Computer) to open it
Select the drive you want to run a check on, e.g. C:\
Right-click on the drive
Click Properties
Go to the Tools tab
Select Check, at the Error checking section
Restart if needed.

Then you will see files in exTemp Chia folder
Delete it.
and U will see your space back!

**Comment by kaizvn** [comment]
> Boot into Windows 10
> Double-click on Computer (My Computer) to open it
> Select the drive you want to run a check on, e.g. C:
> Right-click on the drive
> Click Properties
> Go to the Tools tab
> Select Check, at the Error checking section
> Restart if needed.
> 
> Then you will see files in exTemp Chia folder
> Delete it.
> and U will see your space back!

thank you for your helping but it didn't work, too.
Could not see exTemp folder.
