### ISSUE TITLE
Farming tab: "Delete invalid plot" appears to do nothing

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain#439]
**Describe the bug**
When clicking on the waste basket icon next to an "invalid" plot, a confirmation dialog appears. Regardless of which button in it is pressed, nothing appears to happen. The two buttons are labeled "Back" and "Delete". I think the "Back" button should be labeled "Cancel"

**To Reproduce**

1. Use Chia Blockchain 0.1.14 for plotting on Machine A
2. I have an external drive which I use to transfer plots from Machine A to a target machine. 
3. This means that Chia Blockchain on Machine A discovers the plot (Farming tab) after it's been transferred to the  external drive
4. After disconnection the drive and moving the plot to a target machine, the external drive no longer has the plot (obvisously)
5. Next time I connect I connect the drive to Machine A, Chia Blockchain (Farming tab) lists the plot under "Failed to open (invalid plots)"
6. There's a waste bin icon with a cross that you're supposed to press to get rid of the "invalid" plot but it appears to do nothing.

PS: I think the term "invalid" is not good, since technically the plot is not invalid, but no longer exists in the location where it was discovered.

**Screenshots**
![image](https://user-images.githubusercontent.com/15184875/95056157-99612700-06f4-11eb-8a6d-f5596aa9702a.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- CPU: Intel Core i5-2520M

**Comment by hoffmang9** [comment]
I believe this is fixed in Beta 21 - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta21

**Comment by glaucocm** [comment]
It has happened to me today! I am using v.1.1.5

**Comment by Thoth45** [comment]
having the same problem today.
