### ISSUE TITLE
[BUG] get_block How do I get all related Transaction IDs from the block information ?

### ISSUE THREAD

**Issue by LmingXie** [Chia-Network/chia-blockchain#4390]
**Describe the bug**

I want to get the Transaction details, but I cannot get the Transaction ID from the get_block API. What should I do

I used ```get_block```、```get_block_record_by_height```.

**Comment by mariano54** [comment]
There are no transactions in blocks, you can only get coins, with `get_additions_and_removals`

**Comment by LmingXie** [comment]
@mariano54 How should I get the transaction ID from the information in ```get_additions_and_removals``` ?I need to get the Transaction ID for the unique identification.

**Comment by fullet-tortuga** [comment]
Correct me if I'm wrong but the whole point in a blockchain is to be able to register and track each and every transaction that has ever taken place and all participants involved. So there must be way to inspect that data. Right?
