### ISSUE TITLE
[help]not synced and wont start

### ISSUE THREAD

**Issue by jessehuynh95** [Chia-Network/chia-blockchain#4395]
**Describe the issue**
Reset my pc to make some hardware changes, restarted and chia refuses to sync after. I can connect to full nodes and it even connects to random ones for me still but it wont change from not synced. Peak height and the height of my connections are changing, and I show MiB up and down but it doesnt sync.  

Updated to 1.1.5, reset computer and chia, made sure port 8444 was open in windows firewall as well as my router but i still cannot get the gui to sync.

**Comment by RoySmits** [comment]
Keeps randomly de-syncing over here, no specific time frames, all ports checked, which makes me think it a Chia network issue and not an issue on my end.

**Comment by 11118** [comment]
@Today857 @anderzheng

 
我是按照YouTube 上面的这个办法解决的

《浪费了我 128 分钟时间 ！排查解决了 奇亚币挖矿时 Chia Blockchain 全节点一直无法同步的问题，看看这个，也许能让你少走弯路节省 2 个小时摸索时间 !》

https://www.youtube.com/watch?v=ffJXcfUZ6FY
