### ISSUE TITLE
[help]using a farmer address which we don't have the private keys for

### ISSUE THREAD

**Issue by maginaro** [Chia-Network/chia-blockchain#4398]
**Describe the issue**
system version: ubuntu20.04
chia version: 1.1.5
After running "chia keys add", I got a prompt: WARNING: using a farmer address which we don't have the private keys for. We searched the first 500 addresses. Consider overriding xch1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx with xch1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

Is there an impact on my keys or wallet?

**To Reproduce**
1. Install chia then activate vitualvenv
2. chia keys add
3. input my mnemonic
4. Got the warnning message: WARNING: using a farmer address which we don't have the private keys for. We searched the first 500 addresses. Consider overriding xch1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx with xch1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Expected behavior**
No warning message

**Comment by mariano54** [comment]
Do you have more than 1 key? Make sure to add the other key as well.

**Comment by maginaro** [comment]
> Do you have more than 1 key? Make sure to add the other key as well.

No, I newly install chia, and just import key by  chia keys add

**Comment by maginaro** [comment]
> sepparate

My architecture is indeed one fulnode plus multiple harvester, but this Warning message is reported from FullNode.

**Comment by Thomvh** [comment]
> Do you have more than 1 key? Make sure to add the other key as well.

I have the same issue as the issue opener. For me, it happened after updating to 1.1.5.
Only one key active. The plots all return without any errors. So I am at a bit of a loss here. But it seems to only impact my ability to move coins from the wallet (Not that I have any atm).

**Comment by maginaro** [comment]
I found the reason for the problem, because I have imported a key before, then write into the mining wallet address, and report this fault when I imported again, it is necessary to manually modify the configuration file.

**Comment by Thomvh** [comment]
> I found the reason for the problem, because I have imported a key before, then write into the mining wallet address, and report this fault when I imported again, it is necessary to manually modify the configuration file.

Which edits did you make to the configuration file?

**Comment by yeahhway** [comment]
> > I tried that as well, but still wasn't able to send money from the wallet etc.
> 
> @Thomvh You should find you previous key then import, for me is `xch1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy `

to be clear, the newer key is xch1xxxxetc and the older key is xch1yyyyyyetc and you had to change the xxxx to yyyyy?

**Comment by maginaro** [comment]
> > > I tried that as well, but still wasn't able to send money from the wallet etc.
> > 
> > 
> > @Thomvh You should find you previous key then import, for me is `xch1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy `
> 
> to be clear, the newer key is xch1xxxxetc and the older key is xch1yyyyyyetc and you had to change the xxxx to yyyyy?

@yeahhway Yes
