### ISSUE TITLE
[BUG]testnet7 is not asyned

### ISSUE THREAD

**Issue by yuzhongrong** [Chia-Network/chia-blockchain#4404]
Connecting to beta1_introducer.chia.net, 58444
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ CHIA_ROOT="~/.chia/testnet" chia wallet show
Wallet height: 0
Sync status: Not synced
Balances, fingerprint: 2331392080
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 txch (0 mojo)
   -Pending Total Balance: 0.0 txch (0 mojo)
   -Spendable: 0.0 txch (0 mojo)
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ 
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ 
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ 
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ CHIA_ROOT="~/.chia/testnet" chia show -s 

Searching for an initial chain

You may be able to expedite with 'chia show -a host:port' using a known node.

Blockchain has no blocks yet

**Comment by yuzhongrong** [comment]
the log

(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ CHIA_ROOT="~/.chia/testnet" chia  show -s -c

Searching for an initial chain

You may be able to expedite with 'chia show -a host:port' using a known node.

Blockchain has no blocks yet

Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
WALLET    127.0.0.1                              38458/8449  17c6623c... May 10 16:06:50      0.0|0.0    
INTRODUCER beta1_introducer.chia.net              58444/58444 27b07e13... May 10 18:01:12      0.0|0.0

**Comment by z3002** [comment]
UPD
testnet-node.chia.net:58444   works
