### ISSUE TITLE
[BUG]Err.DOUBLE_SPEND

### ISSUE THREAD

**Issue by MrChenGG** [Chia-Network/chia-blockchain#4405]
![image](https://user-images.githubusercontent.com/26245882/117635534-7af36a80-b1b2-11eb-875d-87132ffad95e.png)

**Comment by Muffexx** [comment]
Hello @MrChenGG ,

please consider searching before creating new issues.
There are several issues regarding this topic e.g. #4281 #4164 #3917 #3696

regards
muffexx
