### ISSUE TITLE
[BUG] Sync is extremely slow and can take roughly 4 days to sync

### ISSUE THREAD

**Issue by krasher9** [Chia-Network/chia-blockchain#4409]
As the topic says, i have 5 harvestor machines and i decided to make a main PC to connect them all.
The sync is moving but at an extremely slow rate, its currently at 90k / 250k since i started the chia app.
If i close the app and reboot and try to relaunch it might take another 4-5 days to resync at this speed if it doesnt somehow fix it to go faster.  Is this normal ? Does the main PC need to have good specs to make sure it syncs faster?

**Comment by baizuchong-net** [comment]
Please add the nearest node to you

**Comment by krasher9** [comment]
They are all Added,  Still syncing since i made this post and i started this from yesterday lol....

![image](https://user-images.githubusercontent.com/83899298/117650355-a883e800-b1a1-11eb-8d45-1e706fea2066.png)

**Comment by MrZepto** [comment]
![image](https://user-images.githubusercontent.com/43267889/117781317-cce2d180-b240-11eb-8f15-bf37373de54f.png)
Same here. Been a few days now....

**Comment by j2d3** [comment]
I am trying to sync a full node (cli, no gui) and it has been running all day.
```
Current Blockchain Status: Full Node syncing to block 263197
Currently synced to block: 261888
Current Blockchain Status: Not Synced. Peak height: 261888
      Time: Tue May 11 2021 02:28:23 UTC                  Height:     261888

Estimated network space: 3.134 EiB
Current difficulty: 167
Current VDF sub_slot_iters: 100139008
Total iterations since the start of the blockchain: 848668987116

  Height: |   Hash:
   261888 | 5661f07355a7acf5d395787d727e6c40f50370b2c38a2948ffb39c6724ff9cee
   261887 | 74c2731695b700989d52e2d6bf14f6330dd7370c861adedfd949689595c7d662
```

**Comment by killerfrost22** [comment]
Is plotting affecting syncing? I am having this issue as well on my i7- 9700k win 10

**Comment by kleenxcoder** [comment]
I have installed windows on my machine on a different drive. port forwarding 8444 working and windows firewall opened for Chia.exe and now I have the same problem as other people. Sync is processing all the time :(

**Comment by Koprix** [comment]
Hello, 

Did you resolve the issue??

**Comment by rizlah** [comment]
this seems to be a growing problem for many people, they have to fix this issue soon or I will be out, I already know many people who have abandoned the project because of this issue, I will be following them soon if it is not resolved.

**Comment by wizbowes** [comment]
Additionally to having this issue, start_full_node.exe is running my CPU at around 50% whilst it's trying to sync - greatly reducing my ability to plot.  I assume they are related this only started since syncing failed......

**Comment by freemandealer** [comment]
same problem here, too slow

**Comment by accelerator2** [comment]
I had to reboot my node and now it synching again. The funny part as it sync slower then blocks are added (i'm verifying on chia explorer). I have many nodes connected, but it seems like only few are up to date

**Comment by tikumo** [comment]
Same problem, just installed newest version yesterday (could not plot with previous version, memory problems each time!, this is fixed)

**Comment by socketpair** [comment]
Same problem. chia_wallet and chia_full_node both eat 100% CPU. What are they doing during syncing ?

**Comment by meawoppl** [comment]
Same problem here. This is a project killer IMHO.

**Comment by 155trimmer** [comment]
Having trouble here too. Syncing seems to take forever. It's actually getting slower since I started 2 days ago. It's also gobbling up system resources. Can't imagine why it needs so much power. 
Also can't imagine why this issue is closed...

**Comment by mlamoglia** [comment]
I have two nodes in different locations (different infrastructure). Both has 8444 opened to the internet. One behind Xfinity and other behind a dedicated fiber where I manage the firewall. No filter are applied to 8444. Both are very slow to sync. Slower then the block discovery... what makes syncing pointless. It's not an infrastructure issue, it's not a connection issue. I have more then 20 nodes connected to my node.

**Comment by 155trimmer** [comment]
> I have two nodes in different locations (different infrastructure). Both has 8444 opened to the internet. One behind Xfinity and other behind a dedicated fiber where I manage the firewall. No filter are applied to 8444. Both are very slow to sync. Slower then the block discovery... what makes syncing pointless. It's not an infrastructure issue, it's not a connection issue. I have more then 20 nodes connected to my node.

It's absolutely nuts. Exact same situation here. Port open, over 30 peers, sync cannot keep up. Until this is fixed I will never be able to farm. I'm just plotting in the meantime in the hopes that this gets figured out.

**Comment by mlamoglia** [comment]
After updating it to the new version 1.1.6 released today it just started sync. After two hours both sites started to farm. Problem resolved.

**Comment by geoffmyers** [comment]
Confirming that version 1.1.6 fixes this problem, at least for me. Syncing performance greatly improved after updating.

**Comment by 155trimmer** [comment]
I updated to 1.1.6 first this this morning. It started to sync or about 10 minutes and then stopped. Any chance you guys would be willing to share some peers with me? Maybe the ones that have a little mojo, lol

**Comment by mlamoglia** [comment]
Try to connect to the nodes using IP instead. 18.169.12.98:8444, 202.61.226.20:844
Maybe you have firewall, antimalware or those local IPS installed. Since it's not a normal daily operation for a workstation, those systems tries to intercept the communication and block. Also don't forget when opening 8444 port in the router (port forwarding) you also have to create an inbound rule on windows firewall to permit traffic on 8444. Test from another host (like the internet from your phone) the access to your IP at 8444 (telnet yourip 8444) to guarantee that chia nodes has clear path to your node.

**Comment by 155trimmer** [comment]
> Try to connect to the nodes using IP instead. 18.169.12.98:8444, 202.61.226.20:844
> Maybe you have firewall, antimalware or those local IPS installed. Since it's not a normal daily operation for a workstation, those systems tries to intercept the communication and block. Also don't forget when opening 8444 port in the router (port forwarding) you also have to create an inbound rule on windows firewall to permit traffic on 8444. Test from another host (like the internet from your phone) the access to your IP at 8444 (telnet yourip 8444) to guarantee that chia nodes has clear path to your node.

Thanks for the peer IPs. I've got all that setup. Port is open everywhere, etc. 8444 tested successfully on multiple test sites. For good measure, I also have UPNP disabled on router and in Chia config file.

**Comment by hkarakose** [comment]
I have installed v1.1.6 on an ubuntu instance. It is up for 4-5 hours and only 1/3 of blocks has been synched. A full sync will take 14-15 hours.

Is it an expected speed?

**Comment by rizlah** [comment]
Yes this expected speed. Can actually take a few days to sync for the first time.

**Comment by hkarakose** [comment]
I installed the previous version on macos last week. it opened much quicker.

**Comment by enly1** [comment]
> Yes this expected speed. Can actually take a few days to sync for the first time.

Yes, I've just started today and based on current sync rate, i'm expecting 80+ hour sync duration from blank install.

Burning 100% CPU on the relatively low spec machine, so no plotting in the background for me.

**Comment by ikonduktor** [comment]
I'm syncing for 6 days already with 100% cpu.
Very user friendly crypto (no)

**Comment by enly1** [comment]
> > Yes this expected speed. Can actually take a few days to sync for the first time.
> 
> Yes, I've just started today and based on current sync rate, i'm expecting 80+ hour sync duration from blank install.
> 
> Burning 100% CPU on the relatively low spec machine, so no plotting in the background for me.

FYI - I gave up syncing - was getting there, but was taking too long, so got a trusted copy of the databases and swapped out.

**Comment by sljgjj** [comment]
> > > Yes this expected speed. Can actually take a few days to sync for the first time.
> > 
> > 
> > Yes, I've just started today and based on current sync rate, i'm expecting 80+ hour sync duration from blank install.
> > Burning 100% CPU on the relatively low spec machine, so no plotting in the background for me.
> 
> FYI - I gave up syncing - was getting there, but was taking too long, so got a trusted copy of the databases and swapped out.

how to do this one?

**Comment by leoibbani** [comment]
still not working, any suggestions?

**Comment by M4ketech** [comment]
After 2 full days (48 hours) im at "Syncing 1,028,192/1,177,520".

Only thing what boosted the speed, was adding this to peers:
node.chia.net:8444

Im not sure about this, but maybe the speed is getting better at end of the sync or not.

**Comment by leoibbani** [comment]
No, speed is always the same, but at least once is synced only takes a few minuts to sync again (maybe the next day)

**Comment by oleksiikoshlatyi** [comment]
SQLite gets slower and slower the larger it gets. 
But [here is](https://www.chiachain.link) the way around solution for syncing Chia full node quickly. You can pre-download blockchain_v1_mainnet.sqlite file, put it to the right directory instead of existing and sync-up during hour, not days

**Comment by emlowe** [comment]
I removed the link to any db downloads, as we do not recommend you download the DB from any site unless you have complete trust in that site.

**Comment by amochkin** [comment]
To me slow sync speeds are caused by lack of NAT traversal mechanisms because the sync process solely relies on nodes that are exposed to the internet (I mean 8444 port).

**Comment by Park-Milbern** [comment]
trusted [Chia Database Download](https://chiadb.co/)

**Comment by emlowe** [comment]
Deleting link to DB - Do not trust links to the DB - you should sync from the network
