### ISSUE TITLE
Uncorrect link in Windows Chia client

### ISSUE THREAD

**Issue by leckt3r** [Chia-Network/chia-blockchain#4412]
20 min ago link changed to https://bit.ly/3xXqmrB instead of off client and trying to download 9.4 MB RAR archive
![изображение](https://user-images.githubusercontent.com/83952609/117641274-a3696d80-b18e-11eb-9f2c-62ed2def7deb.png)

**Comment by vladderb** [comment]
#4413

**Comment by vladderb** [comment]
@leckt3r please add "documentation" and "bug" labels to the issue

**Comment by vladderb** [comment]
This questionable URL was added to the wiki by commit 9b3a733. The link is correct at the moment.
