### ISSUE TITLE
Be careful, the windows installer download url in the wiki page has been replaced with a virus exe (possible)

### ISSUE THREAD

**Issue by eddy16112** [Chia-Network/chia-blockchain#4413]
In https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL, the Install the Windows installer - Chia Blockchain Windows's url is https://bit.ly/3xXqmrB, which is definitely not the correct windows installer! 

Please check it.

**Comment by baizuchong-net** [comment]
del c:/user/.chia/

**Comment by zombie665** [comment]
Virus or **NOT?**

**Comment by vladderb** [comment]
#4412

**Comment by vladderb** [comment]
@eddy16112 please also add "documentation" label to your issue

**Comment by eddy16112** [comment]
> @eddy16112 please also add "documentation" label to your issue

Looks like I do not have the privilege to add the label after the issue is created.

**Comment by vladderb** [comment]
This questionable URL was added to the wiki by commit 9b3a733. The link is correct at the moment.

**Comment by eddy16112** [comment]
> Virus or **NOT?**

I am not sure if it is a virus or not. What I can tell is after I unzipped the rar file and clicked installer, I got several warnings from my antivirus software, and it seems like the installer tried to modified the system file and registry file.

**Comment by JonathanSamelson** [comment]
I also clicked the installer. The executable opened a windows for a short while and then closed.
I ran an offline analysis and I'm now running a complete analysis by Windows Defender. I also checked recently installed programs, programs running in the brackground, recently modified files... I found nothing relevant at the moment.

**Comment by DartCoder** [comment]
When the link changed? I and my friend using one wallet and he installed chia on Sunday. Does his pc in danger?

**Comment by staviq** [comment]
The link lead to a domain in Nepal ?

Can we please get some statement on this from the devs ?

**Comment by eddy16112** [comment]
> I also clicked the installer. The executable opened an installation window for a short while and then closed.
> I ran an offline analysis and I'm now running a complete analysis by Windows Defender. I also checked recently installed programs, programs running in the brackground, recently modified files... I found nothing relevant at the moment.

I reset my windows, so I do not have the access to the log file of my antivirus software now. I will try to reproduce in my virtual machine and come back with more details later, but it is necessary to figure out who posted this url.

**Comment by staviq** [comment]
> It could be some kind of internal build of a utility for updating the client, or something like that. There can be a lot of options why it is on some file hosting service (and the link looks exactly like a file hosting service).

I would like to point out to the fact, that the link lead to a zip file hosted on the Rural Village Water Resources Management Project... In Nepal... That does not look very hosting service to me...

**Comment by zombie665** [comment]
In my Download folder is nothing...
![Screenshot_1](https://user-images.githubusercontent.com/83660122/117657880-885d2480-b1b3-11eb-8c5b-b4c301e501b3.png)

**Comment by vladderb** [comment]
After decrypting the short link, I really saw where this file is. But if you look at the history, then there was even a full link to this file and only a little later a short link was added.

![image](https://user-images.githubusercontent.com/34345978/117658011-e6cdd700-b1a2-11eb-9e78-449e758b21c2.png)

**Comment by DartCoder** [comment]
> After decrypting the short link, I really saw where this file is. But if you look at the history, then there was even a full link to this file and only a little later a short link was added.
> 
> ![image](https://user-images.githubusercontent.com/34345978/117658011-e6cdd700-b1a2-11eb-9e78-449e758b21c2.png)

Could you say when the original link was changed to this suspicious link?

**Comment by vladderb** [comment]
> > After decrypting the short link, I really saw where this file is. But if you look at the history, then there was even a full link to this file and only a little later a short link was added.
> > ![image](https://user-images.githubusercontent.com/34345978/117658011-e6cdd700-b1a2-11eb-9e78-449e758b21c2.png)
> 
> Could you say when the original link was changed to this suspicious link?

https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL/_history

Here you can see the history by selecting commits. The change took place about 2 hours ago. Look at the changes from the user
"Bitmexbot". If your friend downloaded and installed the executable file and opened the standard Chia client, then I believe that he is fine. Because the "virus" archive weighed only 9MB, and the client was much more.

**Comment by DartCoder** [comment]
> > > After decrypting the short link, I really saw where this file is. But if you look at the history, then there was even a full link to this file and only a little later a short link was added.
> > > ![image](https://user-images.githubusercontent.com/34345978/117658011-e6cdd700-b1a2-11eb-9e78-449e758b21c2.png)
> > 
> > 
> > Could you say when the original link was changed to this suspicious link?
> 
> https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL/_history
> 
> Here you can see the history by selecting commits. The change took place about 2 hours ago. Look at the changes from the user
> "Bitmexbot". If your friend downloaded and installed the executable file and opened the standard Chia client, then I believe that he is fine. Because the "virus" archive weighed only 9MB, but the Chia client is much larger.

Thank you very much 😊

**Comment by mariano54** [comment]
It seems like it was a file that decompressed to an infinite size file (decompression bomb), so you would notice it if you saw it.

**Comment by fullet-tortuga** [comment]
The short URL points to https://rvmis.com/vendor/ChiaSetup-1.1.4.rar which is definitively a suspicious domain. I'm not downloading anything from there. If it's not on chia.com then it's not legit to me.

**Comment by fullet-tortuga** [comment]
I meant .net, somehow I can't edit.
