### ISSUE TITLE
[help] Not found Plots

### ISSUE THREAD

**Issue by WestCoastxz** [Chia-Network/chia-blockchain#4414]
**Describe the issue**
I'm adding to the system new HDD drivers, and begin to planting to old one and new HDDs, planting to the old place working good, but in new one it is "Not found Plots". 

Tried to replace the path, any way the same thing, doesn't recognize. 

OLD HDD is "E:\" desk

**Screenshots**
![t1](https://user-images.githubusercontent.com/83952116/117641714-28ed1d80-b18f-11eb-8f01-8a9181378193.png)
![t2](https://user-images.githubusercontent.com/83952116/117641734-2c80a480-b18f-11eb-8a3a-14a57cc4f44a.png)
![t3](https://user-images.githubusercontent.com/83952116/117641741-2ee2fe80-b18f-11eb-84e2-d13ea136c8a8.png)

**Comment by xr3nan** [comment]
Same problem here!
![Captura de tela 2021-05-10 114447](https://user-images.githubusercontent.com/83978942/117705410-64451780-b1a2-11eb-9e09-1a52fb0e478e.png)

**Comment by WestCoastxz** [comment]
After updating from 1.1.4 to 1.1.5 will help

**Comment by xr3nan** [comment]
Updated here.. still the same.

**Comment by SourFJ** [comment]
> Updated here.. still the same.

Has the problem been solved?

**Comment by Yoken0S** [comment]
I got the same problem is someone has an idea
