### ISSUE TITLE
Not farming any plots on this harvester. Check your configuration

### ISSUE THREAD

**Issue by ayanokj** [Chia-Network/chia-blockchain#4417]
Hey! I have a problem. I do not understand the solution to this problem.

I am using use one computer for both Plotting and Farming. 

Created plots through the program itself. I did not change anything in the settings. That is, I installed it, opened the program, clicked "create a new key" and clicked "add a plot". Version 1.1.4

**debug.log**
_plot has a farmer public key that is not in the farmer's pk list._

_Not farming any plots on this harvester. Check your configuration._

Deleting all keys, reinstall clean chia didn't help. 

I do not understand at all what the problem is, similar problems were experienced by those who were farming on several computers, but I only have one PC.

Would appreciate help resolving this!

**Comment by Dravenex** [comment]
When you say "clean chia" did you delete all folders? Especially the .chia folder in C:\Users\YOURUSERNAME\.chia?

**Comment by ayanokj** [comment]
Yes, delete all folders.
