### ISSUE TITLE
[BUG] [GUI] NVMe SSD is unaccessible midway plotting (reproduced in 2 rigs, 3 NVMe SSDs)

### ISSUE THREAD

**Issue by grinbucks** [Chia-Network/chia-blockchain#4418]
GUI stopped plotting with this error "Only read 0 of 262134 bytes at offset 0 from "T:\\plot..."

I found out that the SSD was no longer accessible  with "A device which does not exist was specified" error.

On the Disk Management, there appeared to be 1mb unallocated space on that disk (see screenshot). 
Before plotting, there was only 1 partition and there was no unallocated space at all.

![Screen Shot 2021-05-03 at 1 06 42 PM](https://user-images.githubusercontent.com/83256537/117648237-2e129280-b1b8-11eb-9d92-9d6f952aa5e5.png)

The disk appears back to normal (1 partition, no unallocated space) after restart.

But the problem persists when plotting.

The error is reproduced in both single and parallel plottings (2,3,4 plots parallel)

The error is reproduced in 2 rigs (B550/Ryzen 3900X and B250/i7-6700)

The error is reproduced in 3 nvme SSDs: 2x Transcend S220 2TB (Gen3) and 1x Aorus 2TB (Gen4)

Before this error, all three SSDs were doing fine plotting for 1 week or so.

GUI versions 1.1.3, 1.1.4, 1.1.5

- OS: Win 10 
- OS Version/Flavor: 20H2 Build 19042.631
- CPU: i7-6700 (with B250 mobo, 40GB DDR4) and Ryzen 3900x (with B550 mobo, 72GB DDR4)

Any help is highly appreciated.

**Comment by michael-trinity** [comment]
@grinbucks try using crystaldiskinfo and see the health of it while plotting, it might just get too hot.

**Comment by grinbucks** [comment]
Noted with thanks @michael-trinity Just restarted plotting and monitoring the temp on rig B550/3900x. Will update on the result.

> @grinbucks try using crystaldiskinfo and see the health of it while plotting, it might just get too hot.
