### ISSUE TITLE
Wallet not connected.

### ISSUE THREAD

**Issue by Drwbog** [Chia-Network/chia-blockchain#4419]
Hello guys.
I have some problems. 
My synchronization is okay, but wallet still not connected and I don't know is it big problem or not.
I tryed a lot of things to fix it, but nothing help.
I reboot chia programm, reboot my computer and of course install new version 1 1 5.
Help me please :)
Thank you
![1](https://user-images.githubusercontent.com/83956383/117651280-74f18f80-b19a-11eb-966e-3b5bfae204e4.JPG)

**Comment by rmreeves09** [comment]
Just hit “keys” on the GUI and click your key and it should show as connected

**Comment by yusufaydemir** [comment]
same problem...

**Comment by Drwbog** [comment]
> Just hit “keys” on the GUI and click your key and it should show as connected

Thanks a lot!!!!!!!!
