### ISSUE TITLE
Rewards does not add-up

### ISSUE THREAD

**Issue by taoxer** [Chia-Network/chia-blockchain#4421]
history shows that i ve got 10.5, but only farmed 8. 

deleted wallet files and re-synced from height 0, still the same. 
total balance and pending balance also shows as 8 aswell, did NOT show the "missing" 1.5 and 0.75 at the 3rd and 4th line of history.

![222222](https://user-images.githubusercontent.com/25659007/117654329-307ce880-b1c8-11eb-9cfa-9fbb49c0828f.png)
![1111111](https://user-images.githubusercontent.com/25659007/117654320-2a870780-b1c8-11eb-954f-4a7ab1893571.png)

**Comment by night-lurker** [comment]
well 1.5 and 0.75 i guess ;)
