### ISSUE TITLE
Reload Problem [BUG]

### ISSUE THREAD

**Issue by sam1man** [Chia-Network/chia-blockchain#4429]
**Describe the bug**

**To Reproduce**

1. Go to 'Top menu'
2. Click on 'View'
3. Scroll down to 'Reload OR To Force Reload'
4. Still Loading The Page & Get Message Connecting To Wallet 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83960042/117659931-344b4380-b1a5-11eb-946a-b2ee69c4581b.png)
**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- OS Version/Flavor: [e.g. 20H2]
- CPU: [e.g. AMD 1950X ]

**Additional context**

**Comment by farmerer** [comment]
Same problem here. Thankfully it keeps plotting in the background though.

**Comment by VICSTOC** [comment]
I've got the same problem

**Comment by assaedi** [comment]
same problem!!

**Comment by racabu** [comment]
same problem. Even if not plotting, the problem happens.

**Comment by sam1man** [comment]
‫בתאריך יום א׳, 18 ביולי 2021 ב-14:08 מאת ‪github-actions[bot]‬‏ <‪
***@***.***‬‏>:‬
