### ISSUE TITLE
[help]Does the receiving address in the wallet have to be the same as the planting reward address in the farm?

### ISSUE THREAD

**Issue by uwerui** [Chia-Network/chia-blockchain#4442]
Does the receiving address in the wallet have to be the same as the planting reward address in the farm?

**Comment by uwerui** [comment]
> 不必要。它可以是您有权访问的任何地址。

At which address are XCH rewards received?

**Comment by uwerui** [comment]
> 不必要。它可以是您有权访问的任何地址。

At which address are XCH rewards received?

**Comment by uwerui** [comment]
> 不必要。它可以是您有权访问的任何地址。

At which address are XCH rewards received?

**Comment by mariano54** [comment]
By default the rewards go to your first address. But you can set rewards to go to any address.

**Comment by uwerui** [comment]
> 默认情况下，奖励将转到您的第一个地址。但是您可以设置奖励去任何地址。

Where can I check my first reward address?

**Comment by uwerui** [comment]
> By default the rewards go to your first address. But you can set rewards to go to any address.

I clicked the new address and updated a new address. Do I need to change the address in the cultivation reward?

**Comment by uwerui** [comment]
> 不必要。它可以是您有权访问的任何地址。

I clicked the new address and updated a new address. Do I need to change the address in the cultivation reward?

**Comment by cihansardaslar** [comment]
so should we write our own address
