### ISSUE TITLE
annoy

### ISSUE THREAD

**Issue by wanghongqi8548488** [Chia-Network/chia-blockchain#4443]
I didn't back up Chia's mnemonics and key public keys. Only P good files, are these files useless

**Comment by Dreiser** [comment]
If you don't have any access to private keys, you have no way of using your existing plots or accessing your coins.

**Comment by wanghongqi8548488** [comment]
> 如果你没有任何私人钥匙，你就没有办法使用你现有的阴谋或获得你的硬币。

That's basically invalid?

**Comment by wanghongqi8548488** [comment]
5t
