### ISSUE TITLE
Signage point N not added

### ISSUE THREAD

**Issue by iwex** [Chia-Network/chia-blockchain#4447]
Hello! 
I have a lot of "Signage point N not added" and also "End of slot not added CC challenge xxxx" in my logs.
What can cause this error in the log? Network latency or some bug or even system performance?
I'm running a full node on VPS with 16GB ram and 4vCPU, network performance is also good.
I have 6 harvesters, is it possible that this message caused by latency to my harvesters?
Thanks!

**Comment by trippyguy** [comment]
same me

**Comment by ramkom9** [comment]
same for me
