### ISSUE TITLE
[BUG]全节点无响应，连接其他节点同样无响应，四个圆圈太可笑了

### ISSUE THREAD

**Issue by dasgdvchgajs** [Chia-Network/chia-blockchain#4448]
![image](https://user-images.githubusercontent.com/83671107/117689296-2b319500-b1ec-11eb-8f1b-9358979ebc4b.png)
糟糕开始于更新1.1.5，之后重装系统、其他版本gui，都无法解决问题

**Comment by elarkasi** [comment]
where is the port number ?

**Comment by qqeip** [comment]
port 4444
