### ISSUE TITLE
[REQ] Move instead of Copy after Phase4 if temp drive same as destination drive

### ISSUE THREAD

**Issue by benkywong** [Chia-Network/chia-blockchain#4456]
Please add an option that can MOVE the plot file instead of COPY after Phase4 if temp drive is same as the destination drive.
I am running 20+ process which I would like to use scheduled FastCopy instead of built-in copy to my NAS which limit speed 1Gbps. But I found that chia.exe would still COPY C:\Temp tmp file to C:\Plot which the drive letter is the same, it cost extra time and extra disk space which is stupid and unnecessary

**Comment by gblikas** [comment]
> But I found that chia.exe would still COPY

@benkywong Do you have code, or process logs, that show this is the case? I'm curious if this is the case on Linux. I feel like I've noticed the same thing, but have no way to verify (show) it.

**Comment by secco04** [comment]
Before i had my nvme i used my truenas as tmp and store location trought smb  it was okayish from speed but ive seen this behavior too ... but i cant show you logs since ive not doing this anymore...

**Comment by VRn00b** [comment]
+1

**Comment by ByronAP** [comment]
move is just copy followed by a delete, the OS controls this. Depending on the filesystem and OS it will perform a rename instead of a  copy which doesn't require copying the data.

**Comment by benkywong** [comment]
> > But I found that chia.exe would still COPY
> 
> @benkywong Do you have code, or process logs, that show this is the case? I'm curious if this is the case on Linux. I feel like I've noticed the same thing, but have no way to verify (show) it.

I use Windows with powershell. It is simple to proof as I can see there is plot.tmp on C:\Temp and C:\Plot as the same time, and the copy process need 8~10min. I don't think NVMe SSD need 8min or even 8sec to move a file right?

my code with -d and -t is the same drive: 
$cmd = -join("C:\Users\", $user, "\AppData\Local\chia-blockchain\app-", $app, "\resources\app.asar.unpacked\daemon\chia.exe plots create -k 32 -a 3708411712 -f 8d078ef34888db10c540906db3766ee040ddbb6b517da2ce89ec6176e70139f5ab406a3eb997f18612897c82cb13efc7 -p 8e425186c5c39e922cf1c4724adf51db90c0a215abea7a96e95670a6b0a711e79940634f41cd6271ec1fe90fdabb9bd7 -n 1 -d ", $drive, ":\Plot_", $drive, " -t ", $drive, ":\Temp\", $folder, " -b ", $ram, " -r ", $cpu, " -u 128 | tee -filepath C:\plotter\plots-", ((get-date).ToLocalTime()).ToString("MM-dd-HHmmss"), $drive, ".txt")

**Comment by esaba** [comment]
I'm seeing this behavior on a Mac as well. When temp and destination directories are different but are on the same drive, it treats it no differently than if the two directories were on two different drives, meaning there is needles copy time and 2 full copies of the same file will exist on the same drive at one point.

A workaround is to use the exact same directory for the temp and destination directories. In that case, there is no copy time and the file is just renamed

So, currently...

If the temp and destination directories are different but are on the same drive, it does:
1. Finish Phase 4
2. Copy file from temp to destination (there are now 2 copies of the same file on the same drive, unnecessarily taking 2x space)
3. Delete temp file
4. Rename destination file

If the temp and destination directories are the same directory on the same drive, it does:
1. Finish Phase 4
2. Rename file

**Comment by benkywong** [comment]
I found the solution: set -2 as the same as -d which is the final place for the plot
eg.
-t C:\Temp
-2 C:\Plot
-d C:\Plot

It would do rename only instead of copy

**Comment by benkywong** [comment]
Case closed. Please have some remarks on the wifi so It would be clear for other users

**Comment by danny-wu** [comment]
Why is this closed? This is an active and real bug

**Comment by danny-wu** [comment]
> benkywong Do you have code, or process logs, that show this is the case? I'm curious if this is the case on Linux. I feel like I've noticed the same thing, but have no way to verify (show) it.

@gblikas This is the case on Linux (Ubuntu 20.04 LTS). It is simple to verify because it's taking me 8 minutes to move from one folder on a nvme to another nvme.

Renames don't take 8 minutes. Only moves do.

**Comment by esaba** [comment]
> I found the solution: set -2 as the same as -d which is the final place for the plot
> eg.
> -t C:\Temp
> -2 C:\Plot
> -d C:\Plot
> 
> It would do rename only instead of copy

That's a workaround, not a solution.

**Comment by benkywong** [comment]
> > I found the solution: set -2 as the same as -d which is the final place for the plot
> > eg.
> > -t C:\Temp
> > -2 C:\Plot
> > -d C:\Plot
> > It would do rename only instead of copy
> 
> That's a workaround, not a solution.

It is not a workaround and a solution. It is an unclear setting and no special remark on Wiki.
