### ISSUE TITLE
[help] after plotting successful now status "NOT AVAILABLE" 

### ISSUE THREAD

**Issue by avsamuel87** [Chia-Network/chia-blockchain#4461]
[help] after plotting successful now status "NOT AVAILABLE" 
Can some body help with this issue?[
![Capture](https://user-images.githubusercontent.com/83975101/117696441-f90f3b80-b1c9-11eb-9644-c0a4fe39d66d.PNG)

**Comment by nicholasradovic** [comment]
I have the same concern! And how can we check the status of the plot on mac?

**Comment by dungla2011** [comment]
I have the same problem!
