### ISSUE TITLE
out of sync

### ISSUE THREAD

**Issue by asit27** [Chia-Network/chia-blockchain#4462]
I've been digging synchronously for 3 days, and last night it gave sync error and the digging stopped and it never synchronized
![Screenshot_2](https://user-images.githubusercontent.com/83970201/117693167-6751ff00-b1c6-11eb-8f57-a20a4c2e010c.png)

Desktop
OS: windows
OS Version: Windows 10 Pro
CPU: AMD Ryzen 7 1700 Eight-Core Processor  3.00 GHz

no link is added to other peers in any way

**Comment by schmiddim** [comment]
Desktop
OS: Linux
OS Version/Flavor: Linux Mint 20.1
CPU: AMD Ryzen 9 3900X 12-Core Processor
Chia Version: 1.1.5

**Comment by PZminer85** [comment]
i have same issue

**Comment by winduser1** [comment]
i have the same issue. sometimes the sync stops when a plot is done and gets moved. sometimes just out of nowhere.
hope updating on 1.15 helps

**Comment by marcin1990** [comment]
Same problem here, Chia cannot reconnect automatically when Internet access is resumed while network interface is working without issues. There is no entries in the event log.

**Comment by asit27** [comment]
> Buradaki aynı sorun, ağ arayüzü sorunsuz çalışırken İnternet erişimi sürdürüldüğünde Chia otomatik olarak yeniden bağlanamaz. Olay günlüğünde giriş yok.

What to do? What is the solution to the problem?
