### ISSUE TITLE
uupool steals coins / SCAM POOL

### ISSUE THREAD

**Issue by anton85798** [Chia-Network/chia-blockchain#4466]
the reward that should be, according to the official page of the pool  2.12 CHIA/PB chia
I was paid for 12 TB 0.0083 chia
but should be 2,12/1000 tb=0,00212 chia/1 tb
0,00212*12=0,02544 chia

POOL steals OVER 60% COINS

**Comment by trwbox** [comment]
Well pools aren't officially supported yet, and it's not a pool from this dev, so they can't do much about it

**Comment by Dariux1991** [comment]
like 7€ per days?
