### ISSUE TITLE
[BUG] Wallet STILL NOT SYNCED (7+ days)

### ISSUE THREAD

**Issue by iLexGit** [Chia-Network/chia-blockchain#4467]
**Describe the bug**
Hey guy i'm sorry but i have to bring this up again because i received no answer. My wallet hasn't synced for over a week. My node is connected and up to height correclty but my wallet is always behind BY A LOT. I tried everything, even deleted the whole software and all my wallet dbs etc, everything, and it is still not syncing. How is it possible that my node is up to date but my wallet is stuck at 20k height and not going up????

**Expected behavior**
Wallet syncing normally... i guess

- OS: Windows 10

**Comment by TorMazila** [comment]
Try checking your UPnP and windows firewall.
Seems chia is definitely far from production quality in many aspects.

**Comment by gillopillo** [comment]
same here. frustrating. fix?

**Comment by w780215** [comment]
Same problem here, The syncing suddenly stop for no reason.

**Comment by Yabankazi** [comment]
same here, it needs again a restart the PC to activate chia syncing. It s a big problem. I think if you are not connected for longer days to mainnet, there are no chances to get ever any XCH.

**Comment by iLexGit** [comment]
No... restarting doesn't help either

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993
