### ISSUE TITLE
[help] Connecting to wallet is to very long time

### ISSUE THREAD

**Issue by kimmaster444** [Chia-Network/chia-blockchain#4468]
Connecting to wallet is to very long time.

I'm waiting Chia Blockchain Connecting to wallet after run program it to long time ( very much > 1 day) , I'm try restart program many time. I'm try restart my PC many time. But it don't work

**Comment by otnoukra** [comment]
I've had the same problem for 5 hours. never connects.

**Comment by TorMazila** [comment]
Seems this happens due to database damage. The usage of sqlite makes this product very demanding, to say the least.
In my case I had to delete both mainnet/wallet and mainnet/db folders and have to resync :(.
Stupid situation.

**Comment by variableresults** [comment]
I recently had to delete my db as well due to a stuck transaction that wasn't posting to the blockchain. 

The sync takes WAY too long. This needs to be addressed ASAP as the wallet is  useless unless it stays stable and synced. Chia can't succeed if you can't process transactions reliably.

**Comment by Ewerthon111** [comment]
✅ Eu descobri um jeito de n perder os arquivos haha, primeiro eu segui o conselho do TorMazila mas no final eu voltei com o arquivo mainnet/db/blockchain_v1_mainnet.sqlite e assim não perdi o sincronização. Se alguém for fazer algum vídeo pode falar meu nome? 😜

**Comment by kimmaster444** [comment]
> Almost for me deleting `mainnet/db/peer_table_*` has solved it

Please teach me , How to delete that ?

**Comment by Isanderthul** [comment]
I tried this, and it solved nothing, maybe just made it worse?!
https://arstech.net/how-to-fix-chia-connecting-to-wallet-problem/

**Comment by jaxnz** [comment]
I have the same issue, but my `blockchain_v1_mainnet.sqlite` file is getting bigger, been running for around 24 hours and is 1.8GB and growing slowly

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993
