### ISSUE TITLE
[BUG] Strange things happening when running on mining rig

### ISSUE THREAD

**Issue by tboy1337** [Chia-Network/chia-blockchain#447]
Im running the newest version and while its syncing its somehow kicking the fans of my 6 card mining rig up a lot and messing with my hashrate and its making the power useage massively fluctuate from its normal 800W to 300-500W.

**Comment by hoffmang9** [comment]
This is as currently designed - it will use as many vCPUs as you have to get synced and then quiet right down.

**Comment by tboy1337** [comment]
It's messing up the functionally of my mining rig so I wouldn't just close
this, this is a massive problem for me, there's no option to disable this
and as I use my mining rig to heat my house.

**Comment by hoffmang9** [comment]
Most users want to be synced to the chain as fast as possible so they can either start using it or start farming it. There are two easy work arounds. You do not need to run fullnode on your plotting machine. Just use the same private key and you can plot from the cli with no local full node. Optionally, sync on another machine and then copy the contents of the two db/ directories in ~/.chia/VERSION/

**Comment by tboy1337** [comment]
Can't you just add a checkbox to disable GPU acceleration?

**Comment by hoffmang9** [comment]
It's not GPU acceleration. It's using your CPU cores available so you can get synced and actually farm or use the chain.

**Comment by tboy1337** [comment]
Then the new version is definitely an issue, before it would max out the
CPU, then version change sorted that and it wasn't too bad but with the
newest one it's definitely messing with the GPUs somehow.

**Comment by hoffmang9** [comment]
The only thing that changed around sync from b13 to b14 was a speedup in wallet initial sync.

**Comment by tboy1337** [comment]
Well idk man it was doing something to mess up the GPUs, it's fine now that
it's synced.
