### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RogiIN** [Chia-Network/chia-blockchain#4478]
Logo ao ligar o programa, diz que está conectando a carteira e não sai disso.
![image](https://user-images.githubusercontent.com/83970472/117712777-239dcc00-b1ab-11eb-80d3-9816b8a2510e.png)
![Error Chia Blockchain](https://user-images.githubusercontent.com/83970472/117713037-7ecfbe80-b1ab-11eb-8674-44fc239cb9c7.jpg)

**Comment by abedae** [comment]
yea i have same problem  only on my laptop

**Comment by marciomdg** [comment]
I have the same problem. ver 1.1.5

**Comment by Ewerthon111** [comment]
✅Eu descobri um jeito de n perder os arquivos haha, primeiro depois do conselho do TorMazila, mas não no final eu voltei com o arquivo mainnet / db / blockchain_v1_mainnet.sqlite e assim não perdi a sincronização. Se alguém para fazer algum vídeo pode falar meu nome?😜

**Comment by Ewerthon111** [comment]
✅Eu descobri um jeito de não perder os arquivos haha, primeiro você exclui as duas pastas mainnet/db & mainnet/wallet e abre o programa para recriar as pastas, mas no final eu voltei com o arquivo antigo mainnet / db / blockchain_v1_mainnet.sqlite e assim não perdi a sincronização. Se alguém for fazer algum vídeo pode falar meu nome?😜

**Comment by evertonmirassol** [comment]
Também estou com esse problema "Conectando à carteira" e não sai dessa tela. Meu HD do sistema onde armazenava o temporario encheu e travou o aplicativo. fechei forçadamente o aplicativo e reiniciei o pc. Apaguei os arquivos da pasta temporaria e quando abri o programa nao sai disso. Outro detalhe é que o tema dark que tinha escolhido voltou para o claro e o idioma voltou para o inglês. Vou tentar reinstalar o programa e fazer o que o meu chará no comentario acima disse. Senão vou perder a sincronização. :(

**Comment by evertonmirassol** [comment]
Infelizmente no meu caso não deu certo! tive que apagar a pasta do chia e reinstalar tudo.

**Comment by ramark2** [comment]
Eu também mesmo problema!!!
Alguém ajuda
