### ISSUE TITLE
[help] How to change my plots public addresses please help 

### ISSUE THREAD

**Issue by hmz06967** [Chia-Network/chia-blockchain#4479]
Hi,
I transferred my old wallet information to a pool and I don't trust the pool so I got a new address.
So, later, for the plots I created with my old wallet, "farmer public key that is not in the farmer's pk list." I got the error. How can I change the public keys of these lands? I don't want to use my old wallet key.

**Comment by kazim0690** [comment]
You can't touch the land, but you can farm by holding the key, then adding a new key to the config file by adding the wallet address of that key. 
https://github.com/Chia-Network/chia-blockchain/wiki/Chia-keys-management
