### ISSUE TITLE
[BUG] Plotter: -2 and -d directories pointing same location but tries to move files and gets stuck

### ISSUE THREAD

**Issue by etemiz** [Chia-Network/chia-blockchain#448]
**Describe the bug**
Running these commands
```
cd ~/plots
chia plots create -t . -2 . -d ~/plots  .........

```

we get this:
Could not copy "./plot-k32-2020-10-03-16-40-a1031bccc7cb5332197ff7576c126aeea68996cd8a637983f5b729e752f9c0fc.plot.2.tmp" to "/home/dead/plots/plot-k32-2020-10-03-16-40-a1031bccc7cb5332197ff7576c126aeea68996cd8a637983f5b729e752f9c0fc.plot.2.tmp". Error Invalid argument. Retrying in five minutes.

**To Reproduce**

-t or -2 and -d should resolve to same dir but should be given differently in command line

**Expected behavior**
Not stuck.

**Desktop (please complete the following information):**

- OS: Ubuntu
- OS Version/Flavor: 18
- CPU: Threadripper

**Comment by hoffmang9** [comment]
This is the OS telling you it can't copy a file over itself. ~/plots/foo.tmp is the same as ./foo.tmp when you're in the ~/plots/ directory aka ~/plots/foo.tmp.

**Comment by nathang21** [comment]
I'm seeing the same issueIs there a way to cancel, choose a different final directly and retry again without regenerating the entire plot? 

```
Could not copy "/Users/nathang21/Temp/plot-k32-2021-03-18-07-33-0fd1ad106f012e4373e1aeee59c768eae824b34aa79441836c65e6c9e667e9c8.plot.2.tmp" to "/Volumes/Time Machine Backup/plot-k32-2021-03-18-07-33-0fd1ad106f012e4373e1aeee59c768eae824b34aa79441836c65e6c9e667e9c8.plot.2.tmp". Error Permission denied. Retrying in five minutes.
```

It took all day and now i'm hitting this error, hopefully I can save that progress. Will report back if I try it.
