### ISSUE TITLE
[BUG] chia init complains that chia init wasn't run.

### ISSUE THREAD

**Issue by stolk** [Chia-Network/chia-blockchain#4481]
**Describe the bug**
chia init will complain that chia init was not run.

**To Reproduce**
copy ssl/ca dir from other machine.

```
$ /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia init -c ./ca/
** /home/bram/.chia/mainnet does not exist **
** Please run `chia init` to migrate or create new config files **
```

*NOTE: I WAS RUNNING THE EXACT SAME COMMAND THAT IT WANTS ME TO RUN!*

**Expected behavior**
chia will initialize using the provided ca.

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Linux
- OS Ubuntu
- CPU: Xeon
- Chia: 1.1.5 

**Additional context**

**Comment by adonig** [comment]
As a workaround run `chia init` and then `chia init -c`.

It will create a new ca, then delete it and copy the one you provided.
