### ISSUE TITLE
[BUG] Harvester crashing

### ISSUE THREAD

**Issue by bw-man** [Chia-Network/chia-blockchain#4485]
**Describe the bug**
i installed the version 1.1.1 till to 1.1.5, and always i have on all system a problem, an 2x mac and 1x windows server 2012 r2.
The problem is, that i see in Farm--> Advanced Option --> Your Harvester Network, i see that the port is scanning. every second he check a new port. And after some time, it will be crashed with a error windows from: start_harvester.exe 

**To Reproduce**
Steps to reproduce the behavior: only start chia --> select my key --> look at the Full Node screen --> hands on the table and wait. after some minutes, i get the crash window. All other services are still running.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux] Windows Server 2012 R2 and Mac Big sur
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by ramkom9** [comment]
I have same after update from 1.1.3 to 1.1.4. So roll back to 1.1.3 and stop changing ports. Now updated to 1.1.5 and seems ok. On win10pro as vm.
