### ISSUE TITLE
[BUG] chia_timelord_launcher failed to start. Error: start failed

### ISSUE THREAD

**Issue by cgreening** [Chia-Network/chia-blockchain#4486]
**Describe the bug**
Installed Mac version 1.1.5 

```
$ chia start all
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: chia_timelord_launcher failed to start. Error: start failed
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
```

**To Reproduce**

1. Run command `chia start all`
2. Everything seems to start apart from chia_timelord_launcher`

**Expected behavior**
Everything should start up

**Screenshots**
```
$ chia start all
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: chia_timelord_launcher failed to start. Error: start failed
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
```

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- OS 11.2.3
- CPU: Intel

**Additional context**
I don't know if this is a problem or not. It says `chia_timelord` has started.

**Comment by lvcivs** [comment]
Use `chia start farmer` instead. You don't need the timelord in a usual scenario (there are only a handful of those, run by advanced users).

**Comment by cgreening** [comment]
Thanks!
