### ISSUE TITLE
[BUG] pc unschedules a restart randomly only when chia client is open

### ISSUE THREAD

**Issue by itsinhaleyo** [Chia-Network/chia-blockchain#4489]
**Describe the bug**

pc unschedules a restart randomly only when chia client is open even after a factory reset

**To Reproduce**

1. Open Chia
2. Wait long enough

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: 19041.928
- CPU: I7 8700k 3.70GHz

**Additional context**

I am going to try using an m.2 ssd to run windows 10 from and see if the ssd im using is the issue.

**Comment by michael-trinity** [comment]
check temperatures of your CPU and drives

**Comment by itsinhaleyo** [comment]
> check temperatures of your CPU and drives

The cpu temp is running a solid 40-45° when it happens and all the drives are running fine, especially the one the operating system is on

**Comment by itsinhaleyo** [comment]
> Could be PSU issue

I will have to look into this, im getting a new psu soon and ill try and see if the psu is the issue
Ill keep this open and reply when i find out if the psu was the culprit or not

**Comment by itsinhaleyo** [comment]
It was a Power issue, my pc didnt have enough power to run everything in my case without having to restart from lack of power since im also gpu mining on this pc

**Comment by ramkom9** [comment]
there you go, glad you sort this out

**Comment by bmilanov1** [comment]
I experience the same. Plenty of power on the PC. I have 2 PSUs one 1600W and one 850W powering the PC. And the PC only draws like 830W so it can't be the PSU. I have added the second PSU of 850 and powered few components from it but still restarting constantly only when the chia GUI runs. the CPU is at about 5% temperature doesn't exceed 65C. It reboots sometimes every 5 minutes sometimes every few hours.

**Comment by itsinhaleyo** [comment]
best fix is reinstalling windows if you havent done that already, worked
for me

**Comment by bmilanov1** [comment]
I am beginning to think it is temperature-related. Most of the reboots happen mid-day. Pretty much never at night. I have installed an additional fan next to the CPU. So far it is holding.
