### ISSUE TITLE
[BUG]I get my XCH to my wallet，but but none

### ISSUE THREAD

**Issue by AZ663** [Chia-Network/chia-blockchain#4498]
![2021-05-11_073241](https://user-images.githubusercontent.com/83150987/117736960-6c956500-b22b-11eb-9065-4f579b69b413.jpg)
![2021-05-11_073259](https://user-images.githubusercontent.com/83150987/117736967-6e5f2880-b22b-11eb-913d-5ca05c8595b0.jpg)
![2021-05-11_073339](https://user-images.githubusercontent.com/83150987/117736968-6ef7bf00-b22b-11eb-9a14-f5eb1e8195e3.jpg)

Could it be that the wallet cannot be less than 1？

**Comment by canhmai** [comment]
your wallet syncing , height 1441 . you need to wait full synced !

**Comment by AZ663** [comment]
> You need to wait for the sync. Each key has a different balance (since it controls different addresses)

Why can't we share nodes? 
If I have multiple sets of private keys，that will be a terrible
