### ISSUE TITLE
[BUG] GPU usage close to 50% (RTX2060) while GUI window is maximised

### ISSUE THREAD

**Issue by n8f4LL** [Chia-Network/chia-blockchain#4505]
**Describe the bug**
If I have the GUI window open/maximised my GPU Load (RTX2060 (Laptop) goes up to 50%. If i minmize the window GPU usage is close to 0. (RAM load is from ETH mining)

**To Reproduce**

**Expected behavior**

**Screenshots**
![GPU usage of Chia window](https://user-images.githubusercontent.com/83985402/117739476-ba47a880-b1fe-11eb-9096-bc785f9451dd.png)

**Desktop (please complete the following information):**

- OS: Windows 20
- OS Version/Flavor: 20H2
- CPU: Ryzen 4800H

**Additional context**

**Comment by cracker0dks** [comment]
Yes, I noticed this as well, this is bad.

**Comment by senorgoofle** [comment]
I have the same problem. Just having the Chia Gui open reduces hashrate by 6 MH/s on my GTX 1060 with Quickminer. Win10 2004 latest Nvidia driver.

**Comment by KoborOld** [comment]
I have found that games and sometimes browsers got stucked (lagged) for a few seconds while program is running.
Fully Synced now and making plots.
Tried to run game from a different SSD than where plots are creating, it not helped.

**Comment by SirGlitchAlot** [comment]
This issue is still occurring and really needs to be addressed. This will throw shade onto chia and people will thank you are gpu mining.
