### ISSUE TITLE
GUI NOT WORKING

### ISSUE THREAD

**Issue by agustinmono** [Chia-Network/chia-blockchain#4513]
![image](https://user-images.githubusercontent.com/50418223/117746213-675ff800-b1e2-11eb-99bf-1addefed36ad.png)

**Comment by MatiasCheverry** [comment]
I have the same bug, already updated and reinstalled. None of these worked :(

**Comment by andrewhayter** [comment]
getting the same error.

**Comment by agustinmono** [comment]
> I have the same bug, already updated and reinstalled. None of these worked :(



> getting the same error.
> 
> running 1.1.5.dev0

I did this:
https://github.com/Chia-Network/chia-blockchain/issues/4245#issuecomment-836586679

But now its "Not Synced"

Ill wait a few hours but i need a solution asap
