### ISSUE TITLE
Full node is showing a losing block as winning - makes leaderboard incorrect [BUG]

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#454]
**Describe the bug**

**To Reproduce**

I'm running master on testnet-status.chia.net. I've written a hacky python script to crawl the node rpc every minute and build the leaderboard html.

It counts block 11409 as won by pool public key 0x95243baa02da3186... from blockheader e60b18b7138ee771c6a750a0678aa150e405f9cfe388938515444c6833d41419

However chiaexplorer.com and eFishCent's mac nodes show it as won by 0x81fc9ff8464....

My laptop running current dev agrees with the testnet-status node.

eFishCent's mac shows `e60b18b7138ee771c6a750a0678aa150e405f9cfe388938515444c6833d41419 not found` for `chia show -b` but `chia show -bh 11409` gave him the blockheader of e60b18b7138ee... too.

**Expected behavior**
Full nodes should agree on the blocks in the heaviest chain..

**Screenshots**
![Screen Shot 2020-10-11 at 1 42 43 PM](https://user-images.githubusercontent.com/30377676/95690057-e0a25880-0bc9-11eb-9dc5-7d27bff2db73.png)

**Desktop (please complete the following information):**

- OS: MacOS and Ubuntu
- OS 10.15.6 and 20.04.1
- CPU: N/A

Added my script here:
[leaderboard-html.py.gz](https://github.com/Chia-Network/chia-blockchain/files/5362045/leaderboard-html.py.gz)

**Additional context**

**Comment by mariano54** [comment]
This was the result of two issues:
- Calling chia show -bh instead of -b leads to block not found
- The algorithm in chiaexplorer.com is not handling deep reorgs correctly

The final issue of wrong wallet transactions in reorg is documented here:
https://github.com/Chia-Network/chia-blockchain/issues/455
