### ISSUE TITLE
[BUG] Reorged transactions are not deleted in wallet

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain#455]
**Describe the bug**
When there is a reorg, blocks and coins are properly reversed, but transactions are not (coinbase transactions)

**To Reproduce**
Revert an LCA block and change the winner of the block, and look at the wallet DB in the old winner.

**Expected behavior**
The old winner should not see the old transactions.

**Additional context**
The issue is in the reorg_rollback method, when it rolls back tx, it should not re-add coinbase txs to the DB, and it should set confirmed=False for non coinbase txs.

**Comment by hoffmang9** [comment]
I believe this is fixed here - https://github.com/Chia-Network/chia-blockchain/commit/dd8589bf97580b92486a00b78a25c1a7cf023cc3
