### ISSUE TITLE
I use my pool key to search on chia explore and find 2 XCH, but nothing in my wallet

### ISSUE THREAD

**Issue by dinosaurgg** [Chia-Network/chia-blockchain#4556]
I use my pool key to search on chia explore and find 2 XCH, but nothing in my wallet
![1111](https://user-images.githubusercontent.com/62789793/117793738-194d0200-b27f-11eb-9ddf-b5765eff2e49.png)
![222222](https://user-images.githubusercontent.com/62789793/117793769-1fdb7980-b27f-11eb-82b2-8e080294d40c.png)

**Comment by mariano54** [comment]
Are you sure you are logged in to the correct wallet? if you have multiple keys, you need to select the right key

**Comment by chrisi30330** [comment]
yes synchronized. Is the same client who farmed. I still have a second client there, but upnp is deactivated.
Version 1.1.5

**Comment by azufr3** [comment]
Hi, I have the same problem, mine two chia and I do not have them available in my wallet.

![image](https://user-images.githubusercontent.com/84026841/117830313-e5a3b500-b249-11eb-87d6-aba4c0879e63.png)

![image](https://user-images.githubusercontent.com/84026841/117830391-f5bb9480-b249-11eb-9db7-6d0d8ad125d0.png)

**Comment by andreb2021** [comment]
I have the same problem;

**Comment by andreb2021** [comment]
> > use my pool key to search on chia explore and find 2 XCH
> 
> How do you use your pool key to search XCH? I need to check mine as well. Thanks!

Just go to farm tab, options and click Manage Your Farming Rewards Target Addresses;

**Comment by biostone** [comment]
> > > use my pool key to search on chia explore and find 2 XCH
> > 
> > 
> > How do you use your pool key to search XCH? I need to check mine as well. Thanks!
> 
> Just go to farm tab, options and click (Manage Your Farming Rewards Target Addresses), copy and then search in: https://www.chiaexplorer.com/blockchain/search

If I use my wallet address, I can find the XCH I earned before. If I use the pool key to search, I get nothing. I guess your pool key collides with someone's wallet address?

**Comment by andreb2021** [comment]
> > > > use my pool key to search on chia explore and find 2 XCH
> > > 
> > > 
> > > How do you use your pool key to search XCH? I need to check mine as well. Thanks!
> > 
> > 
> > Just go to farm tab, options and click (Manage Your Farming Rewards Target Addresses), copy and then search in: https://www.chiaexplorer.com/blockchain/search
> 
> If I use my wallet address, I can find the XCH I earned before. If I use the pool key to search, I get nothing. I guess your pool key collides with someone's wallet address?

Is your Farming Rewards Target Addresses the same as your wallet address?

**Comment by biostone** [comment]
> > > > > use my pool key to search on chia explore and find 2 XCH
> > > > 
> > > > 
> > > > How do you use your pool key to search XCH? I need to check mine as well. Thanks!
> > > 
> > > 
> > > Just go to farm tab, options and click (Manage Your Farming Rewards Target Addresses), copy and then search in: https://www.chiaexplorer.com/blockchain/search
> > 
> > 
> > If I use my wallet address, I can find the XCH I earned before. If I use the pool key to search, I get nothing. I guess your pool key collides with someone's wallet address?
> 
> Is your Farming Rewards Target Addresses the same as your wallet address?

Yes

**Comment by andreb2021** [comment]
> > > > > > use my pool key to search on chia explore and find 2 XCH
> > > > > 
> > > > > 
> > > > > How do you use your pool key to search XCH? I need to check mine as well. Thanks!
> > > > 
> > > > 
> > > > Just go to farm tab, options and click (Manage Your Farming Rewards Target Addresses), copy and then search in: https://www.chiaexplorer.com/blockchain/search
> > > 
> > > 
> > > If I use my wallet address, I can find the XCH I earned before. If I use the pool key to search, I get nothing. I guess your pool key collides with someone's wallet address?
> > 
> > 
> > Is your Farming Rewards Target Addresses the same as your wallet address?
> 
> Yes

Mine is not the same, i will change it asap

**Comment by dinosaurgg** [comment]
> > > > > > > use my pool key to search on chia explore and find 2 XCH
> > > > > > 
> > > > > > 
> > > > > > How do you use your pool key to search XCH? I need to check mine as well. Thanks!
> > > > > 
> > > > > 
> > > > > Just go to farm tab, options and click (Manage Your Farming Rewards Target Addresses), copy and then search in: https://www.chiaexplorer.com/blockchain/search
> > > > 
> > > > 
> > > > If I use my wallet address, I can find the XCH I earned before. If I use the pool key to search, I get nothing. I guess your pool key collides with someone's wallet address?
> > > 
> > > 
> > > Is your Farming Rewards Target Addresses the same as your wallet address?
> > 
> > 
> > Yes
> 
> Mine is not the same, i will change it asap

how to change it?

**Comment by prichiyak** [comment]
Why don't Farming Rewards Target Addresses match the wallet address?

**Comment by gblikas** [comment]
> Why don't Farming Rewards Target Addresses match the wallet address?

@dinosaurgg @prichiyak This [reddit link](https://www.reddit.com/r/chia/comments/n4pz7s/crucial_bug_please_check_your_chia_config_asap/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) seems like it really pertains to this issue; see #3141

**Comment by dinosaurgg** [comment]
> Why don't Farming Rewards Target Addresses match the wallet address?

yes, i just checked my wallet address is different with my farm reward address, that's why i can't get my XCH

**Comment by jdumont0201** [comment]
> > Why don't Farming Rewards Target Addresses match the wallet address?
> 
> yes, i just checked my wallet address is different with my farm reward address, that's why i can't get my XCH

This is a different topic from OP. Multiple addresses can be associated to your wallet. You can create new ones on the fly via the GUI. They will all redirect your rewards to your wallet.

**Comment by dinosaurgg** [comment]
> > > Why don't Farming Rewards Target Addresses match the wallet address?
> > 
> > 
> > yes, i just checked my wallet address is different with my farm reward address, that's why i can't get my XCH
> 
> This is a different topic from original post. Multiple addresses can be associated to your wallet. You can create new ones on the fly via the GUI. They will all redirect your rewards to your wallet..
no, when I manage my "farming reward address",it warning"No private keys for one or both addresses. Safe only if you are sending rewards to another wallet ".  Both farm/poll reward address are my old wallet address. But I can't access to my previous wallet anymore.

**Comment by dinosaurgg** [comment]
> > > > Why don't Farming Rewards Target Addresses match the wallet address?
> > > 
> > > 
> > > yes, i just checked my wallet address is different with my farm reward address, that's why i can't get my XCH
> > 
> > 
> > This is a different topic from original post. Multiple addresses can be associated to your wallet. You can create new ones on the fly via the GUI. They will all redirect your rewards to your wallet..
> > no, when I manage my "farming reward address",it warning"No private keys for one or both addresses. Safe only if you are sending rewards to another wallet ".  Both farm/poll reward address are my old wallet address. But I can't access to my previous wallet

**Comment by prichiyak** [comment]
> 
> 
> > > > > Why don't Farming Rewards Target Addresses match the wallet address?
> > > > 
> > > > 
> > > > yes, i just checked my wallet address is different with my farm reward address, that's why i can't get my XCH
> > > 
> > > 
> > > This is a different topic from original post. Multiple addresses can be associated to your wallet. You can create new ones on the fly via the GUI. They will all redirect your rewards to your wallet..
> > > no, when I manage my "farming reward address",it warning"No private keys for one or both addresses. Safe only if you are sending rewards to another wallet ".  Both farm/poll reward address are my old wallet address. But I can't access to my previous wallet

I can't access my coins either, and now they are lying dead weight.
Because when you create the first wallet, the address is saved in the second wallet, in config.yaml.  The FAQ doesn't say anything about this.

**Comment by prichiyak** [comment]
> 
> 
> > > > > > Why don't Farming Rewards Target Addresses match the wallet address?
> > > > > 
> > > > > 
> > > > > yes, i just checked my wallet address is different with my farm reward address, that's why i can't get my XCH
> > > > 
> > > > 
> > > > This is a different topic from original post. Multiple addresses can be associated to your wallet. You can create new ones on the fly via the GUI. They will all redirect your rewards to your wallet..
> > > > no, when I manage my "farming reward address",it warning"No private keys for one or both addresses. Safe only if you are sending rewards to another wallet ".  Both farm/poll reward address are my old wallet address. But I can't access to my previous wallet
> 
> I can't access my coins either, and now they are lying dead weight.
> Because when you create the first wallet, the address is saved in the second wallet, in config.yaml. The FAQ doesn't say anything about this.

Video Proof 
[https://www.youtube.com/watch?v=mvi6ksh2_dY](url)

**Comment by andreb2021** [comment]
> > > > > > Why don't Farming Rewards Target Addresses match the wallet address?
> > > > > 
> > > > > 
> > > > > yes, i just checked my wallet address is different with my farm reward address, that's why i can't get my XCH
> > > > 
> > > > 
> > > > This is a different topic from original post. Multiple addresses can be associated to your wallet. You can create new ones on the fly via the GUI. They will all redirect your rewards to your wallet..
> > > > no, when I manage my "farming reward address",it warning"No private keys for one or both addresses. Safe only if you are sending rewards to another wallet ".  Both farm/poll reward address are my old wallet address. But I can't access to my previous wallet
> 
> I can't access my coins either, and now they are lying dead weight.
> Because when you create the first wallet, the address is saved in the second wallet, in config.yaml. The FAQ doesn't say anything about this.

I can access my old wallet, but nothing is there, i´ve tryed login from another computer, the same computer... now i´m trying to resync from 0... :/

**Comment by 42x42x42** [comment]
> И у меня такая же проблема, в chiaexplorer есть, а в кошельке нету

скорее всего ты создавал ранее другой кошелек. Если да то монеты на нем лежат

**Comment by prichiyak** [comment]
> 
> 
> > И у меня такая же проблема, в chiaexplorer есть, а в кошельке нету
> 
> скорее всего ты создавал ранее другой кошелек. Если да то монеты на нем лежат
> https://www.reddit.com/r/chia/comments/n4pz7s/crucial_bug_please_check_your_chia_config_asap/

Да уже понял.. Вот только сид от первого кошелька не сохранил, не думал что траблы такие будут...

**Comment by achalkov** [comment]
> Да уже понял.. Вот только сид от первого кошелька не сохранил, не думал что траблы такие будут...

Да уж, баг логики из разряда критических. Если бы я на реддите не отписал (собственно линк в сообщении выше - ведет на мой пост) так люди бы и фармили в пустоту. Правда монеты это, к сожалению, уже не вернет.
