### ISSUE TITLE
[BUG] Part of the RPC interface call failed

### ISSUE THREAD

**Issue by Fenguoz** [Chia-Network/chia-blockchain#4557]
**Describe the bug**
Part of the RPC interface call failed

**To Reproduce**

1.  Click on 'terminal'
2.  Send to 'curl --insecure --cert ~/.chia/mainnet/config/ssl/wallet/private_wallet.crt \
--key ~/.chia/mainnet/config/ssl/wallet/private_wallet.key -d '{"wallet_id": 1, "new_address":true}'\
-H "Content-Type: application/json" -X POST https://localhost:9256/get_next_address'
3. See error '500 Internal Server Error. Server got itself in trouble'

**Screenshots**
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/28383092/117794265-aa23dd80-b27f-11eb-8fab-fc9f13d9716b.png">

**Desktop (please complete the following information):**

- OS: macOS
- OS Version/Flavor: macOS Big Sur
- Chia App Version: 1.1.5

**Comment by carfnann** [comment]
For your information, I had the same issue when doing Curl RPC with parameter.
when you put \ on the parameter, it is working : -d '{\"wallet_id\": 1}'

**Comment by Fenguoz** [comment]
> For your information, I had the same issue when doing Curl RPC with parameter.
> when you put \ on the parameter, it is working : -d '{"wallet_id": 1}'

I added it, and this is the result。Must contain these two parameters -d '{"wallet_id": 1,"new_address":true}'

**Comment by Fenguoz** [comment]
I found the problem. When I created the farmland, it worked normally.

**Comment by TaylorWenOne** [comment]
> I found the problem. When I created the farmland, it worked normally.

I can't understand how you fix it. Can you give more detailed explanation
