### ISSUE TITLE
Incorrect Number of Plots Under Farm Tab

### ISSUE THREAD

**Issue by kushariforyou** [Chia-Network/chia-blockchain#4562]
I've found this morning the display of number of plots in the farm tab is 1 less than it should be. Screenshot attached. It shows 151, while there are 152 as you can see right below in the Last Attempted Proofs Section. Also the final destination folder has 152 plot files
![Chia](https://user-images.githubusercontent.com/12114909/117803205-59cb6200-b224-11eb-9e04-0909927928cf.png)

**Comment by kushariforyou** [comment]
Eventually caught up at 156 to the correct number 156.

**Comment by BigSilverOrb** [comment]
May I reopen this? I received my first reward two days ago, and since then I'm having the very same issue, excepting that my gap is now approaching 100!
