### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by obldn** [Chia-Network/chia-blockchain#4563]
**Describe the bug**
I open the Chia Blockchain, and the page doesn't load - it stays on 'Loading wallet'. this has been happening for nearly 24 hours now.

**To Reproduce**

**Expected behavior**
It usually loads to my Chia Blockchain account

**Screenshots**
<img width="1231" alt="Screenshot 2021-05-11 at 11 41 38" src="https://user-images.githubusercontent.com/84016348/117802873-e2aac380-b24d-11eb-864c-e8cf4ae95872.png">

**Desktop (please complete the following information):**
- macOS: Big Sur

**Additional context**

**Comment by keremciu** [comment]
same problem with my windows

**Comment by obldn** [comment]
have you worked out how to fix this issue?
