### ISSUE TITLE
[BUG] Create Plot in Mac with Pool Key and Farm Key 

### ISSUE THREAD

**Issue by ramiali1994** [Chia-Network/chia-blockchain#4565]
Hello

chia plots create -k 32 -r 4 -t "/Volumes/Chia - Temp/" -d "/Volumes/Chia"

Traceback (most recent call last):
File "chia/cmds/chia.py", line 81, in
File "chia/cmds/chia.py", line 77, in main
File "click/core.py", line 829, in call
File "click/core.py", line 782, in main
File "click/core.py", line 1259, in invoke
File "click/core.py", line 1259, in invoke
File "click/core.py", line 1066, in invoke
File "click/core.py", line 610, in invoke
File "click/decorators.py", line 21, in new_func
File "chia/cmds/plots.py", line 135, in create_cmd
File "chia/plotting/create_plots.py", line 96, in create_plots
File "chia/util/path.py", line 23, in mkdir
File "pathlib.py", line 1312, in mkdir
PermissionError: [Errno 13] Permission denied: '/Volumes/Chia - Temp'
[20582] Failed to execute script chia

MacOS Big Sur
Hard drive External 20TB
ExFAT

I need Command to create Ploting in My mac but the main pc doing farm in windows then i have my pool key and my farm key

please help

thank you !

**Comment by gldecurtins** [comment]
Hello

You got a PermissionError. Mac OS protects the filesystem - there will be a pop-up asking for user consent in order to get access.
Have a look at System Preferences - Security & Privacy - Privacy. Either "Full Disk Access" or "Files and Folders" would need to contain "Terminal".

**Comment by KrugST** [comment]
Sudo chia plots create -k 32 -r 4 -t "/Volumes/Chia - Temp/" -d "/Volumes/Chia"

**Comment by ramiali1994** [comment]
rami@Ramis-Mac-mini-2 ~ % /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/chia -h
Usage: chia [OPTIONS] COMMAND [ARGS]...

  Manage chia blockchain infrastructure (1.1.4)

Options:
  --root-path PATH  Config file root  [default: /Users/rami/.chia/mainnet]
  -h, --help        Show this message and exit.

Commands:
  configure   Modify configuration
  farm        Manage your farm
  init        Create or migrate the configuration
  keys        Manage your keys
  netspace    Estimate total farmed space on the network
  plots       Manage your plots
  run_daemon  Runs chia daemon
  show        Show node information
  start       Start service groups
  stop        Stop services
  version     Show chia version
  wallet      Manage your wallet

  Try 'chia start node', 'chia netspace -d 192', or 'chia show -s'
rami@Ramis-Mac-mini-2 ~ % chia plots create -k 32 -r 4 -t "/Volumes/Chia - Temp/" -d "/Volumes/Chia"


zsh: command not found: chia
