### ISSUE TITLE
[BUG] Does your main ( Farmer ) need to have plots?

### ISSUE THREAD

**Issue by krasher9** [Chia-Network/chia-blockchain#4569]
Does your main ( Farmer ) need to have plots ? Because i have 5 Computer  ( Harvesters ) That are plotting and connected to my network node.  Everything is synced up but i want to confirm if a Farmer PC must have a plot to be able to get rewarded with XCH Coins.  I dont see "last attempted proof " part appearing on my FARMER because i dont have a plot on that mian Computer. Anyone knows if it matters?

**Comment by F1DNA** [comment]
Did you tell your farm system that the harvesters exist?  And where the harvested plots live on them?
