### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dariux1991** [Chia-Network/chia-blockchain#4583]
Hi,
from yesterday when i open CHIA 1.1.5 there is no connection with wallet. Some people have same problem? Someone solved this?

![problema chia](https://user-images.githubusercontent.com/83975004/117822955-4395c400-b26d-11eb-8023-3e628870df36.jpg)

**Comment by michael-trinity** [comment]
make sure you kill all chia tasks in the task manager

**Comment by Dariux1991** [comment]
I don't any chia task opened in tank manager. i tried to install chia network in other pc and i can easy open my wallet. i tried to unistall and install chia network but every time same problem
