### ISSUE TITLE
[BUG] Plotting process freezes at random % and loses memory

### ISSUE THREAD

**Issue by markferreiro** [Chia-Network/chia-blockchain#4587]
**Describe the bug**
I've experienced that sometimes (randomly), a chia plotting process gets stucked at a specific percentage. When I check the logs it doesn't have any error but it doesn't move anymore. Then, checking the process it has lost all the ram memory. The CPU consumption keeps moving as it would be doing something but it never moves from the percentage. (I kept like 5 hours stucked with no move in the %).

**To Reproduce**
There's no way to reproduce. It happens randomly and it's frustrating because I'm losing a lot of time...

**Expected behavior**
I would expect an error in the plotter log. Why the process is losing all the assigned memory but it keeps using CPU and keeps stuck in the same %?

**Screenshots**
![image](https://user-images.githubusercontent.com/9654240/117830191-af7b2b00-b273-11eb-9d14-74478c04bbdf.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: 20H2 (19042.928)
- CPU: AMD Ryzen 5 3600XT

**Additional context**
No more context could be added.

**Comment by markferreiro** [comment]
I'm plotting on a m.2 1tb disk. It's pretty new, so wouldn't be any issue with it. It's at 60ºC all time. Doesn't seems to be a problem. All the procedures are plotting in the same m.2, yes. But the issues doesn't seems to be with it, as the process is losing all assigned memory. Doesn't makes sense without any error in logs...

**Comment by Mikiish** [comment]
I have the same probleme, basically every day at least one is freezing this way. Also when this happen some of the other plots (that still manage to complete) find theimself unvalid when doing plot check.

I don't know where it comes from but I think it's a RAM problem. Maybe it's XMP profile ?

**Comment by michael-trinity** [comment]
what brand of SSD are you using?

**Comment by night-lurker** [comment]
you use 
temp 1, temp 2, final drive ?
or just temp 1, final drive

**Comment by markferreiro** [comment]
I'm using the sabrent 1TB Rocket and it's practically at 95% of its life. I'm just using it as temp 1. I'm not using temp 2.

**Comment by night-lurker** [comment]
if you have like a SSD or some crap with 512gb, try and use it as temp2, you wont loose that much speed.. and well right now your not getting anything at all

**Comment by variableresults** [comment]
I reported this bug here:

https://github.com/Chia-Network/chia-blockchain/issues/4220

It's not a drive problem. I've seen it on both Inland and Corsair NVME SSDs that weren't overheating and weren't close to being full. This is a bug the devs need to resolve as it's wasting precious TBW. It's been posted on Reddit, Chia Forum and here and nobody from the dev team has acknowledge it yet.

**Comment by zeafynx** [comment]
I reported the same bug here: #4118

**Comment by changpeng75** [comment]
Use Memtest86+ to test memory.
