### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by CoachKevinD** [Chia-Network/chia-blockchain#4589]
Unable to sync blockchain or wallet.  tried killing tasks, restarting, clearing all tmp files.  I installed the blockchain on a second machine and imported my wallet and it works fine.  version 1.1.5 installed.  first time user as of yesterday.

tried adding specific inclusions to firewall.  tried port forwarding 8444 from router.  no change.  machine has been in this state for 4 hours.

any ideas?
![chianode](https://user-images.githubusercontent.com/84027419/117831931-0c122200-b243-11eb-8a82-12de76f2d4d3.PNG)

**Comment by Dmitriylunohod** [comment]
У меня получилось перезапустить синхронизацию! Удалил все подключения, прописал ноды, всё заработало!!!!

**Comment by Wedaras** [comment]
Same problem over here...
![image](https://user-images.githubusercontent.com/84043316/117875612-a8b7dc80-b2a2-11eb-95a1-0b011559082b.png)

**Comment by Wedaras** [comment]
It's got worse after updating to 1.1.5 
Any ideas how to fix this? Plotting on Laptop, functions without problem...
Farming on NAS and it keeps switching to Not Synced, i'm always waiting till plotting is done, then restart the node, it switches to synced in 15-20 min, then everything is fine, farming like a pro :D but after I add new plots and few hours of plotting it switches again to not synced, have tryed to manually connect to node.chia.net / 8444, not working...

**Comment by Apostle44** [comment]
> Renamed the DB folder under the .chia in user profiles and its now re syncing. fingers crossed.
> ![image](https://user-images.githubusercontent.com/63976368/117884622-f4996e80-b300-11eb-9300-3f795a196920.png)

Nope this didn't work. Upgrading to 1.1.5 from 1.1.2 to see if that helps

**Comment by Wedaras** [comment]
> Syncing is working slowly as it rebuilds the local Db's Looks promising.
> ![image](https://user-images.githubusercontent.com/63976368/117888331-029dbe00-b306-11eb-8487-4a2969e1ec8b.png)

Looking promising after update to 1.1.5? In my case, worked fine just for few hours, then same problem as abowe, connected bit not synced and not farming. So all i am doing now is making new plots and not farming... hopefully this issue will be solved in nearly future. Gonna play tomorrow with CLI, maybe it will work

**Comment by Leozolt** [comment]
What does traceroute node.chia.net -T -p 8444 report?

**Comment by blackmennewstyle** [comment]
> traceroute node.chia.net -T -p 8444

I have the same issue as reported here.

In my case, here the result of that command:

```
traceroute to node.chia.net (18.181.21.197), 30 hops max, 60 byte packets
 1  *.*.*.1 (*.*.*.1)  1.417 ms  1.388 ms  1.380 ms
 2  *.*.*.1 (*.*.*.1)  12.445 ms  13.513 ms  13.497 ms
 3  159.192.12.84 (159.192.12.84)  7.074 ms  7.067 ms  7.061 ms
 4  159.192.15.135 (159.192.15.135)  5.285 ms  5.278 ms  7.041 ms
 5  110.78.188.6 (110.78.188.6)  7.034 ms 110.78.188.5 (110.78.188.5)  7.027 ms  7.022 ms
 6  110.78.188.1 (110.78.188.1)  14.918 ms 110.78.188.2 (110.78.188.2)  7.088 ms  7.649 ms
 7  122.155.224.189 (122.155.224.189)  8.919 ms 122.155.226.165 (122.155.226.165)  6.087 ms 122.155.224.189 (122.155.224.189)  8.856 ms
 8  61.19.7.14 (61.19.7.14)  9.786 ms 61.19.7.82 (61.19.7.82)  8.840 ms *
 9  61.19.9.174 (61.19.9.174)  83.705 ms 16509.sgw.equinix.com (27.111.228.215)  82.495 ms  82.489 ms
10  61.19.9.102 (61.19.9.102)  82.482 ms 16509.sgw.equinix.com (27.111.228.215)  79.913 ms  79.287 ms
11  52.93.8.124 (52.93.8.124)  81.377 ms 16509.sgw.equinix.com (27.111.228.215)  79.209 ms 52.93.8.80 (52.93.8.80)  88.060 ms
12  52.93.8.87 (52.93.8.87)  82.294 ms 52.93.8.124 (52.93.8.124)  82.288 ms *
13  52.93.8.47 (52.93.8.47)  80.483 ms 54.239.43.115 (54.239.43.115)  152.458 ms 52.93.131.83 (52.93.131.83)  153.389 ms
14  * * 150.222.240.94 (150.222.240.94)  152.388 ms
15  * * 150.222.240.96 (150.222.240.96)  146.257 ms
16  * 52.93.72.109 (52.93.72.109)  155.113 ms 52.93.72.107 (52.93.72.107)  149.135 ms
17  52.93.72.210 (52.93.72.210)  153.232 ms * *
18  52.93.72.226 (52.93.72.226)  155.444 ms 52.95.31.234 (52.95.31.234)  148.393 ms 52.93.72.225 (52.93.72.225)  155.060 ms
19  52.95.31.212 (52.95.31.212)  155.053 ms 52.93.72.255 (52.93.72.255)  160.488 ms 52.95.31.206 (52.95.31.206)  154.201 ms
20  52.93.72.206 (52.93.72.206)  151.292 ms 52.93.250.36 (52.93.250.36)  149.078 ms 52.95.31.218 (52.95.31.218)  148.273 ms
21  52.93.250.36 (52.93.250.36)  147.450 ms 52.93.73.232 (52.93.73.232)  147.823 ms 52.93.73.230 (52.93.73.230)  150.434 ms
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * ec2-18-181-21-197.ap-northeast-1.compute.amazonaws.com (18.181.21.197)  152.310 ms
28  ec2-18-181-21-197.ap-northeast-1.compute.amazonaws.com (18.181.21.197)  146.869 ms  153.665 ms  150.621 ms
```

**Comment by hajes** [comment]
> > > It's got worse after updating to 1.1.5
> > > Any ideas how to fix this? Plotting on Laptop, functions without problem...
> > > Farming on NAS and it keeps switching to Not Synced, i'm always waiting till plotting is done, then restart the node, it switches to synced in 15-20 min, then everything is fine, farming like a pro :D but after I add new plots and few hours of plotting it switches again to not synced, have tryed to manually connect to node.chia.net / 8444, not working...
> > 
> > 
> > you don't need to wait for plotting is finished...simply run it from CLI, it is plotted offline anyway and you can restart node at any time
> 
> But if you restart a node through gui all you plotting process is gone or can you keep on going through CLI?

I run all plotting via CLI because Win GUI is unstable for me. Restarting GUI, node does not affect plotting.

**Comment by Wedaras** [comment]
> > > > It's got worse after updating to 1.1.5
> > > > Any ideas how to fix this? Plotting on Laptop, functions without problem...
> > > > Farming on NAS and it keeps switching to Not Synced, i'm always waiting till plotting is done, then restart the node, it switches to synced in 15-20 min, then everything is fine, farming like a pro :D but after I add new plots and few hours of plotting it switches again to not synced, have tryed to manually connect to node.chia.net / 8444, not working...
> > > 
> > > 
> > > you don't need to wait for plotting is finished...simply run it from CLI, it is plotted offline anyway and you can restart node at any time
> > 
> > 
> > But if you restart a node through gui all you plotting process is gone or can you keep on going through CLI?
> 
> I run all plotting via CLI because Win GUI is unstable for me. Restarting GUI, node does not affect plotting.

Well it does by my, if i restart node in a process of plotting all the progress is gone and i have to start plotting again from 0%

**Comment by Wedaras** [comment]
This worked for me:
https://www.youtube.com/watch?v=Wuy-OWOtdbQ
