### ISSUE TITLE
[BUG] My plot keeps crashing and i get this error.

### ISSUE THREAD

**Issue by krasher9** [Chia-Network/chia-blockchain#4599]
Caught plotting error: Matches do not match with number of write entries 4294494469 4294494447
[5456] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in _call_
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 176, in create_plots
RuntimeError: Unknown exception

**Comment by gromran** [comment]
> File "chia\plotting\create_plots.py", line 176, in create_plots

this is in that statment:
> if not full_path.exists():
So check your paths

**Comment by riskarb** [comment]
I'm getting the same error.  

"Only wrote 1686 of 1048570 bytes at offset 294648170 to "D:\\plot-k32-2021-05-11-19-22-d6c81c9b371d9d57b8b92c252357b1fcdfee92b51618f469710b7f366cc4af43.plot.p2.t3.sort_bucket_025.tmp"with length 294649856. Error 1. Retrying in five minutes."

This is occurs at ~34% plot completion during phase 2/4.  

I'm also getting crashes when I attempt to delete a plot.  It has crashed about 4 times on me in the last day.  I've lost about 10 plots in the last day.   Quite a few which were almost complete.  Sad.

**Comment by MaxW90** [comment]
> Caught plotting error: Matches do not match with number of write entries 4294494469 4294494447
> [5456] Failed to execute script chia
> Traceback (most recent call last):
> File "chia\cmds\chia.py", line 81, in
> File "chia\cmds\chia.py", line 77, in main
> File "click\core.py", line 829, in _call_
> File "click\core.py", line 782, in main
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1259, in invoke
> File "click\core.py", line 1066, in invoke
> File "click\core.py", line 610, in invoke
> File "click\decorators.py", line 21, in new_func
> File "chia\cmds\plots.py", line 135, in create_cmd
> File "chia\plotting\create_plots.py", line 176, in create_plots
> RuntimeError: Unknown exception

I Had the same error when I chose the drive directly but not a folder inside, it used to stop at 1%. I created a folder and selected it as plot location and now it seems to work.

**Comment by krasher9** [comment]
I have tried new folders, formatting the computer, and nooowww i finally decided to change the ram completely and so far fingers crossed its working fine. I will confirm on my 3rd cycle of plotting if anything crashes or not.
