### ISSUE TITLE
sh install.sh error

### ISSUE THREAD

**Issue by AdrianScott** [Chia-Network/chia-blockchain#46]
ubuntu 18

g++ -o vdf_server.o -c vdf_server.cpp $compile_flags $opt_flags
vdf_server.cpp:194:26: error: variable or field ‘server’ declared void
 void server(boost::asio::io_context& io_context, unsigned short port)
                          ^~~~~~~~~~
vdf_server.cpp:194:26: error: ‘io_context’ is not a member of ‘boost::asio’
vdf_server.cpp:194:26: note: suggested alternative: ‘connect’
 void server(boost::asio::io_context& io_context, unsigned short port)
                          ^~~~~~~~~~
                          connect
vdf_server.cpp:194:38: error: ‘io_context’ was not declared in this scope
 void server(boost::asio::io_context& io_context, unsigned short port)
                                      ^~~~~~~~~~
vdf_server.cpp:194:38: note: suggested alternative: ‘sigcontext’
 void server(boost::asio::io_context& io_context, unsigned short port)
                                      ^~~~~~~~~~
                                      sigcontext
vdf_server.cpp:194:50: error: expected primary-expression before ‘unsigned’
 void server(boost::asio::io_context& io_context, unsigned short port)
                                                  ^~~~~~~~
vdf_server.cpp: In function ‘int main(int, char**)’:
vdf_server.cpp:211:18: error: ‘io_context’ is not a member of ‘boost::asio’
     boost::asio::io_context io_context;
                  ^~~~~~~~~~
vdf_server.cpp:211:18: note: suggested alternative: ‘connect’
     boost::asio::io_context io_context;
                  ^~~~~~~~~~
                  connect
vdf_server.cpp:213:12: error: ‘io_context’ was not declared in this scope
     server(io_context, std::atoi(argv[1]));
            ^~~~~~~~~~
vdf_server.cpp:213:12: note: suggested alternative: ‘sigcontext’
     server(io_context, std::atoi(argv[1]));
            ^~~~~~~~~~
            sigcontext
vdf_server.cpp:213:5: error: ‘server’ was not declared in this scope
     server(io_context, std::atoi(argv[1]));
     ^~~~~~
vdf_server.cpp:213:5: note: suggested alternative: ‘servent’
     server(io_context, std::atoi(argv[1]));
     ^~~~~~
     servent
g++ -o vdf_server vdf_server.o asm_compiled.o $link_flags
g++: error: vdf_server.o: No such file or directory

**Comment by wjblanke** [comment]
I guess you are using an old version of boost? Try updating to the latest version. Cheers!

https://stackoverflow.com/questions/47895520/io-context-error-in-boost-library
