### ISSUE TITLE
[CONGRATULATIONS!!] Bug record in Github (846 issues)- Wallet Sync BIG PROBLEM !!

### ISSUE THREAD

**Issue by datak0w** [Chia-Network/chia-blockchain#4607]
I was about to post that my wallet is unable to sync...
My wallet cannot sync.... plotting stops for no reason... Win 10 client is unable to clean farmed plots /temp directory... I would give you more technical details, but I think all of the issues are 
But, as a developer, and CTO of a quite big company myself, I have to say I have never seen a buggiest software in my life, not even in aplha stages.
Do you need REAL developers, guys, or is Chia client just some kind of joke/scam? 
My wallet cannot sync.... plotting stops for no reason... Win 10 client is unable to clean farmed plots /temp directory... 
Support sucks ... well, really, no support.
Can we expect a proper software soon? Do you need any coding lessons/help? Just ask, guys, we can help.
And I dare you, say 'open your router' s port' one more time... Static IP and 25+ years dev/sec/networking experience here....
Solutions?

**Comment by datak0w** [comment]
> _"Do you need REAL developers, guys, "_
> 
> I know this devpshop well, they would hire real developers, both male and female.
> 
> _"Chia client just some kind of joke/scam"_
> 
> -Is Chia like

**Comment by BrianAMartin221** [comment]
"Code is code"
- Subhas Ramsaywack

[https://www.imdb.com/name/nm3656953/]

**Comment by night-lurker** [comment]
My wallet cannot sync:
--->yes alot of people have problems sync.. butdid you try some of the help there is ?

plotting stops for no reason:
--->have never happened to me ... you remember to clear temp files when your system crash or you close it yourself ?

Win 10 client is unable to clean farmed plots /temp directory:
--->clean farmed plots(why would you)... or move plots you made... farming is when you actual try to win wint your plots

**Comment by BrianAMartin221** [comment]
> I see you do not fully understand how Chia works. To delete the plot folder you have to kill all process named Chia and it will be black. The plot creation is stopped: I think it is not stopped and is still running. So you cannot delete plot temporary folder. To see if they are running you should check the log. Or see CPU and Disk. Sync Wallet: I found sync well, though a bit slow. Opening ports helps to connect other nodes faster. If your are not showing sync, don't sync instead. If restart the machine on Chia wait 15 minutes if nothing changes. You should turn off Chia and proceed to delete db and db wallet. For deleting plot or temporary folders, if updating 1.1.4 or later you can delete them.



Don't forget to have the port open as well.

**Comment by EstebanFuentealba** [comment]
Welcome to Open source, Send PR @datak0w

**Comment by steven-b89** [comment]
Switch to Powershell, it's really simple...
Life is great now <3

**Comment by felixbrucker** [comment]
@datak0w im just curios, do you plot via the gui? if yes try plotting via the cli and see if that fixes the issues

**Comment by fullet-tortuga** [comment]
Now imagine being a QAM like myself. I'm sure I was Gengis Khan in a previous life and Chia is my punishment now.

**Comment by datak0w** [comment]
> Welcome to Open source, Send PR @datak0w

20 years in Open Source development...and busy and with NDA-exclusivity agreement currently, sorry...

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993
