### ISSUE TITLE
Full node shows synced and connected - but no data [BUG]

### ISSUE THREAD

**Issue by dorkmo** [Chia-Network/chia-blockchain#462]
**Describe the bug**
full node not showing any info

**Screenshots**
![image](https://user-images.githubusercontent.com/1923070/96022782-01132280-0e17-11eb-8920-4caa3cb0641c.png)

**Desktop (please complete the following information):**
- OS: Windows
- CPU:  Intel i7

**Additional context**
Wallet was showing no connections, so i clicked the "Keys" button, then my key. After that the wallet connected and updated to most recent transaction. But after that the Full Node info went to "0"s.

**Comment by dorkmo** [comment]
"reloading" with Ctrl+R seems to fix it after a few tries. keeps happening randomly

**Comment by dorkmo** [comment]
looking at debug.log, getting the same message over and over

16:48:35.682 farmer farmer_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
16:48:36.604 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.

even though the farmer page says connected, and wallet shows synced

![image](https://user-images.githubusercontent.com/1923070/96189670-8b867f80-0f06-11eb-8e9e-3a51426037de.png)

![image](https://user-images.githubusercontent.com/1923070/96189686-93462400-0f06-11eb-8ad5-fd80db235875.png)

**Comment by dorkmo** [comment]
09:47:21.521 farmer farmer_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
09:47:22.648 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
09:47:24.749 wallet src.wallet.wallet_node     : ERROR    Exception in create outbound connections: 
09:47:24.755 wallet src.wallet.wallet_node     : ERROR    Traceback: Traceback (most recent call last):
  File "src\server\node_discovery.py", line 207, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

09:47:24.758 wallet src.wallet.wallet_node     : ERROR    Exception in process message: 
09:47:24.839 farmer farmer_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'concurrent.futures._base.CancelledError'>. Aborting and removing peer.
09:48:29.441 wallet src.wallet.wallet_node     : ERROR    Exception in create outbound connections: 
09:48:29.447 wallet src.wallet.wallet_node     : ERROR    Traceback: Traceback (most recent call last):
  File "src\server\node_discovery.py", line 268, in _connect_to_peers
  File "asyncio\tasks.py", line 595, in sleep
concurrent.futures._base.CancelledError

09:48:29.451 wallet src.wallet.wallet_node     : ERROR    Exception in process message: 
09:48:30.438 wallet wallet_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.
09:48:33.042 farmer farmer_server              : WARNING  Could not connect to {'host': '127.0.0.1', 'port': 8444}. <class 'ConnectionRefusedError'>[Errno 10061] Connect call failed ('127.0.0.1', 8444). Aborting and removing peer.

**Comment by hoffmang9** [comment]
Should be fixed in this release but do keep an eye out for it and re-open this (or start a new one) if you see it again. https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta16

**Comment by dorkmo** [comment]
it was the 11996 jam up! all fixed in 16, thanks!

![11996](https://user-images.githubusercontent.com/1923070/97009501-c772a380-1509-11eb-9c98-9185b99a0529.png)

**Comment by japaweiss** [comment]
I think I have a similar issue:
v0.1.15 gets stuck:
![Screenshot 2020-10-24 173510](https://user-images.githubusercontent.com/13430816/97085931-cb451980-1620-11eb-9f40-b859ed026468.png)
![Screenshot 2020-10-24 173533](https://user-images.githubusercontent.com/13430816/97085933-ced8a080-1620-11eb-9b87-8e6cc9152113.png)

v0.1.17 does not connect:
![Screenshot 2020-10-24 173921](https://user-images.githubusercontent.com/13430816/97085943-dac46280-1620-11eb-959b-3ca827b4daff.png)
![Screenshot 2020-10-24 173937](https://user-images.githubusercontent.com/13430816/97085948-dc8e2600-1620-11eb-946b-892932df96d7.png)

**Comment by hoffmang9** [comment]
This was fixed in beta 16 though beta 17 is the current version. Upgrade.

**Comment by japaweiss** [comment]
I upgraded to beta 17 and then have the issue in the last two screenshots

**Comment by hoffmang9** [comment]
I think you're running Windows? I suggest a reboot and then see if you sync. Optionally try beast.chia.net:8444 as a peer and see what happens.

**Comment by japaweiss** [comment]
Windows is correct. Restart did not help and the peer just vanished after hitting enter

**Comment by hoffmang9** [comment]
Are you or have you run another node on another computer on the same local network? Upnp may be confused at your router.

**Comment by japaweiss** [comment]
Did a clean reinstall (deleted all folders) and received the windows firewall notification (private/public) again. No it works. Thanks for your help!

**Comment by japaweiss** [comment]
> Are you or have you run another node on another computer on the same local network? Upnp may be confused at your router.

Yes
