### ISSUE TITLE
[BUG] Plotting uses all available memory regardless of buffer settings and crashes VM

### ISSUE THREAD

**Issue by Birdup** [Chia-Network/chia-blockchain#4622]
When trying to plot with `chia plots create -k 32 -n 1 -t /home/wes/chia-1 -d /home/wes/chiaplots_share` the vm slowly uses all its memory until it crashes. The plotting "hangs" at this step 
```
Starting phase 1/4: Forward Propagation into tmp files... Wed May 12 01:01:24 2021
Computing table 1
```
The -t filesystem does have files propagate during this phase before the crash. 

**To Reproduce**
* This can be reproduced simply by trying to plot on any drive on the vm with the above command. I have also tried with smaller -b values to define the buffer. 

**Expected behavior**
* The temporary plot to be in /home/wes/chia-1 and after completeion move to chiaplots_share

**Desktop (please complete the following information):**

- OS: Ubuntu
- OS Version/Flavor: 20.04
- CPU: L5640 x 2 
- chia 1.1.5

**Comment by Bigman397** [comment]
How much memory are you allocating to the VM? Is there a swap file specified?

**Comment by Birdup** [comment]
@Bigman397 the VM has 12GB of memory

```
wes@chia-farm:~$ cat /proc/swaps
Filename                                Type            Size    Used    Priority
/swap.img                               file            4194300 0       -2
wes@chia-farm:~$ grep Swap /proc/meminfo
SwapCached:            0 kB
SwapTotal:       4194300 kB
SwapFree:        4194300 kB
```

**Comment by Bigman397** [comment]
Odd, maybe throw -e in there to not do bitfield?

**Comment by Birdup** [comment]
My mistake, my VM was consuming more memory than was available on the physical machine.

Ubuntu using all the memory available is an expected behavior https://www.linuxatemyram.com/ 

Resolved by reducing VM memory.

Thanks @Bigman397
