### ISSUE TITLE
[BUG]double spend

### ISSUE THREAD

**Issue by 13616557022** [Chia-Network/chia-blockchain#4631]
I sent the same amount of xch to the same address .It displayed "double_spend".
After that,I sent two different addressed again. now always pending. already 3 hours

**Comment by Glutamat42** [comment]
i guess it'll be hard to say something about that (at least for me) with only the provided information. Maybe append the log?
C:\Users\<yourusername>\.chia\mainnet\log\debug.log
~/.chia/mainnet/log/debug.log
