### ISSUE TITLE
[Enhancement] Switch to use the Click framework

### ISSUE THREAD

**Issue by unparalleled-js** [Chia-Network/chia-blockchain#464]
The CLI code would be much smaller, more manageable, and easier to add commands to if we make the switch to using the Click framework. Since this is python 3.7+ requirement, it seems like it would be compatible.  It would be a major refactor however.

https://click.palletsprojects.com/en/7.x/

I am willing to make the migration myself (as I have experience using this framework) but without haste or priority, but on the weekends when I have time.

**Comment by mariano54** [comment]
I'm not opposed to this, we really need to have a consistent way to add CLI programs, parameters, etc. I would really like to have a CLI that is simple and fun to use

**Comment by mariano54** [comment]
@unparalleled-js do you happen to have some free time to help out with this? We could definitely use some help

**Comment by unparalleled-js** [comment]
Yes, I have some time probably Sunday this week... [Here](https://github.com/unparalleled-js/in3cli) is one I made for in3 that can be roughly copied I presume.

**Comment by mariano54** [comment]
Yeah that looks great!
We have the rpc clients which can be used to easily access the functions of the node and wallet. It would be cool to be able to send a transaction, and check farmer status using the CLI. (which only the UI can do atm)

**Comment by hoffmang9** [comment]
Command line transaction management is underway here - fyi - https://github.com/Chia-Network/chia-blockchain/pull/516

**Comment by unparalleled-js** [comment]
Here is a start: https://github.com/unparalleled-js/chia-blockchain/blob/use-click/src/cmds/keys.py

**Comment by mariano54** [comment]
Look really cool, it's a big improvement over what we currently have now

**Comment by mariano54** [comment]
If anyone is interested in taking @unparalleled-js 's example and expanding it to the other cli programs, this would be an exellent contribution :+1:

**Comment by jespino** [comment]
I'll give it a try

**Comment by mariano54** [comment]
Finished by @jespino
