### ISSUE TITLE
Wallet logs out when deleting a broken half-done plot

### ISSUE THREAD

**Issue by icehawker** [Chia-Network/chia-blockchain#4640]
**Describe the bug**

Chia 1.1.5 (did not observe this bug before)
Tried to plot on USB SSD for a portion of my new plots, but somehow it's experiencing instability during the process. When it inevitably fails to detect the drive for one moment during plotting, the existing TMP files cannot be reacquired by the "wait 5 minutes" process.

So since the plot could no longer progress even though the USB SSD was already re-detected, I had no choice but to delete plot. But every time (past 3 out of 3 times) I delete the waiting plot, it logs me out of Wallet (message: Connecting to Wallet) and ruins my other perfectly well progressing plots.
I could only reproduce this log-out bug on one computer (described below) and not the other (even though I matched the requisite problem of USB drive causing stuck plotting).

**Expected behavior**

Two things I'd expect.
In the first place, a drive disconnect/reconnect during plotting hopefully shouldn't cause the whole plot to permanently freeze if it can be helped in a future update.
But the main issue here is that deleting a plot should not cause a log out (i.e. all parallel plotting processes gone) even if there is difficulty deleting. A delete error should be shown instead.

Bug found on:
- OS: Windows 10 64 bit
- 20H2
- CPU: i7-9750H

Could not reproduce on:
- OS: Windows 10 64 bit
- 20H2, Windows Ameliorated
- CPU: Ryzen 2700

**Comment by GustavoPAlmeida** [comment]
Same problem here.

**Comment by Ratzoletto** [comment]
> But the main issue here is that deleting a plot should not cause a log out (i.e. all parallel plotting processes gone) even if there is difficulty deleting. A delete error should be shown instead.

THIS. By deleting an existing plot (1% or more) my chia app hangs up.
