### ISSUE TITLE
[BUG] Lost sync and connection to Full-Node

### ISSUE THREAD

**Issue by Thyrann82** [Chia-Network/chia-blockchain#4648]
**Describe the bug**
I often lost the connection to the FullNode and in this case the whole sync. Don't know why it don't add for himself a new FullNode, I've to try for myself to find a connection to an FullNode. :(

**To Reproduce**
Its the same like my last bug I've reported: https://github.com/Chia-Network/chia-blockchain/issues/3678

**System**
Win10 64bit
Intel i9 9900KS on MSI MEG Z390 ACE (MB)
4x8GB G.Skill DDR4 Ram
Chia: bug present since version 1.1.3 / 1.1.4 / 1.1.5

**Comment by racabu** [comment]
again the same issue as always, please give a high priority on this.

**Comment by Thyrann82** [comment]
how can i set the priority? :(
