### ISSUE TITLE
[BUG] chia.exe crashing at 61-62% plotting

### ISSUE THREAD

**Issue by Djole501** [Chia-Network/chia-blockchain#4649]
**Describe the bug**
chia.exe stops working while plotting at 61-62% every time. The GUI is still working, sync is also working, plotting stops. 

Windows gives this:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	chia.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5ffec122
  Fault Module Name:	VCRUNTIME140.dll
  Fault Module Version:	14.0.24234.1
  Fault Module Timestamp:	5a8ba5e6
  Exception Code:	c0000005
  Exception Offset:	000000000000c80e
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	6170
  Additional Information 1:	4712
  Additional Information 2:	471229ae094732f6847e6d1cff17f0a1
  Additional Information 3:	db93
  Additional Information 4:	db93856e81abe1a5502b5503bcd036ed

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Event viewer:

Faulting application name: chia.exe, version: 0.0.0.0, time stamp: 0x5ffec122
Faulting module name: VCRUNTIME140.dll, version: 14.0.24234.1, time stamp: 0x5a8ba5e6
Exception code: 0xc0000005
Fault offset: 0x000000000000c80e
Faulting process id: 0x1350
Faulting application start time: 0x01d74652c30a0137
Faulting application path: C:\Users\DELL t7500\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\chia.exe
Faulting module path: C:\Users\DELL t7500\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\VCRUNTIME140.dll
Report Id: 80a9d7db-b2a6-11eb-a913-002564b3628c

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Windows 7
- CPU:  Intel Xeon 5650

I dont see any error in chia log at this timestamp, this is clearly related to VCRUNTIME140.dll which is part of C++ Runtime.

**Comment by russ-tolman** [comment]
I am having this problem too. What version of Chia are you on?

**Comment by russ-tolman** [comment]
yep, me too!


New EP: Russ Sings Fred: The Songs of Fred Neil

www.russtolmanmusic.com



Catch my radio show My Kinda Country, every Thursday, 2pm Pacific on GimmeCountry.com 

    On Wednesday, May 12, 2021, 08:03:48 AM PDT, Djole501 ***@***.***> wrote:  
 
 



I am having this problem too. What version of Chia are you on?


I am running the latest, 1.1.5

**Comment by PMVX** [comment]
I have a similar issue. More jobs die than finish. Not sure around what percentage but when I look at the temp files usually they're quite large around 300MB to 500MB. The process would just die without any error. You would only notice it because progress has stopped. Happens whether using GUI vs CLI using Swar manager. This is on a Ryzen 9 5900X 64GB RAM. I have tried running it in XPG Gammix S11 Pro 2TB and Samsung 980Pro 2TB and get the same issue. Right now trying it with ioDrive2Duo to see if I get the same issue. I have another dedicated plotting machine a 10850K and it has never had this problem with any of the drives mentioned. So much TBW wasted on both XPG and 980Pro :(

**Comment by Djole501** [comment]
I have tried my temp disk on another pc and it completed a plot. I will try reinstalling the problematic machine.

**Comment by Djole501** [comment]
I think i solved this problem. Installed c++ redistributable for x86 and have done some successful plots since.
