### ISSUE TITLE
[BUG] GUI stops working after it was shut down by Windows 10 Update!!!

### ISSUE THREAD

**Issue by pluto2021** [Chia-Network/chia-blockchain#4653]
**Describe the bug**
Windows 10 forces periodic mandatory installation of various updates that involved rebooting the system a couple of times each time this happens. When Chia GUI is running and got shut down abruptly by Windows 10, especially during plotting, it would stop working. The GUI would get stuck at loading wallet for ever!!! The only current remedy is to delete the .chia directory and restart the entire syncing process from zero! As the blockchain gets larger and larger by the minutes, if there is no fast syncing service, it will become a nightmare quickly. This has resulted in significant loss of up time.

**To Reproduce**

Wait for accumulated Windows updates, while keeping the Chia GUI running. Once the auto update would start, it would force shutting down every program including the Chia GUI without permission. After the updates, start the Chia GUI, it would stuck at loading wallet indefinitely.

Alternatively to mimic an event like this, run Chia GUI with active plotting as usual. Either shutting the computer by holding the power button, or manually apply any updates that would require rebooting.  Not sure of the results, as there is no time to experiment with these alternatives. But they might help the developer team to be able to reproduce the issue quicker.

**Expected behavior**
Actively looking for windows 10 update activities periodically within the GUI. Gives a warning message somewhere in the GUI Red or Orange colored waning the user that Windows might shutdown the machine at anytime and prompt user to stop plotting activities asap, close the GUI safely, manually go through the mandatory updates, reboot the system and restart the Chia GUI. At least this can be a temporary solution in the near term.

Ideally, the GUI need to be able to prevent the forced shutdown by Windows 10, or when such an request is detected, shutting down the GUI in a safe manner automatically to allow Windows 10 doing its things without impacting messing up with the locally stored blockchain, or at least lock down the blockchain to prevent file corruption.

In order to prevent the blockchain file become too large, would advise to break it down into separate files with each covering certain length. This can help to minimize the re-syncing issue when the file would get corrupted due to an unexpected system anomaly event.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: Latest updates
- CPU: Intel
- Chia GUI version: 1.1.4

**Additional context**
GUI robustness is of crucial importance for Windows users to keep the blockchain running more smoothly.

**Comment by pegazuss** [comment]
Same here after a windows update this night
i'm now unable to launch "chia blockchain 1.1.5 gui"
electron 11.4.3
chrome 87.0.4280.141
Node 12.18.3
V8 8.7220.31-electron.0
on a 
windows 10 pro
10.0.19042
ryzen 9.

**Comment by TRASHCOMPANY** [comment]
El mismo error, durante una actualización forzosa de Windows el sistema deja de funcionar y se pierden todos los trazados que estaban activos, es un error critico, hasta incluso parece a propósito. una gasto de recursos sin sentido. esto solo demuestra la vulnerabilidad de nuestra datos, aunque a muchos les parezca mera coincidencia para mi no lo es. estamos muy lejos de conseguir privacidad y libertad digital. el proximo paso dejar de lado el centralismo de los sistemas operativos.
