### ISSUE TITLE
Infinite "connecting to wallet" when opening application. [BUG]

### ISSUE THREAD

**Issue by foulballguy** [Chia-Network/chia-blockchain#4654]
when i open the app i just get a loading screen saying connecting to wallet forever. help please?

**Comment by walter-esposito** [comment]
me too on a pc the same thing, on others everything works, I await a solution

**Comment by bigmaddog** [comment]
I have the same problem. I solved the problem by deleting the directory .chia

**Comment by laozhang713** [comment]
I also have this problem, but I am a mac computer and I can’t find the .chia file

**Comment by russ-tolman** [comment]
WIN GUI 1.1.5, same issue. However wallet sometimes syncs if I am online.

**Comment by YTC72** [comment]
clear the temp directory, reinstall GUI, and make sure Program Files (x86)/user/username/.chia is deleted

**Comment by russ-tolman** [comment]
Thanks!

New EP: Russ Sings Fred: The Songs of Fred Neil

www.russtolmanmusic.com



Catch my radio show My Kinda Country, every Thursday, 2pm Pacific on GimmeCountry.com 

    On Wednesday, May 12, 2021, 07:27:31 AM PDT, YTC72 ***@***.***> wrote:  
 
 


clear the temp directory, reinstall GUI, and make sure Program Files (x86)/user/username/.chia is deleted

**Comment by qanei** [comment]
When i started the app, my screen is stuck on connecting to wallet for hours
mac 
i delete and install again , and not work

**Comment by itongx** [comment]
just only wallet db need to remove if this issue happening but when db size is bigger syncing become an issue as right now db size is 4GB

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993
