### ISSUE TITLE
[BUG]Error 22

### ISSUE THREAD

**Issue by lsx77474747** [Chia-Network/chia-blockchain#4660]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

1. Go to Plots
2. Click on Add Plot Directory
3. Scroll down to my plot directory

**Expected behavior**
Because one of my hard drives failed, I removed the failed hard drive. After removing the hard drive, I restarted the computer, and an error code 22 was prompted.

**Screenshots**
![image](https://user-images.githubusercontent.com/84068941/117944086-698b9900-b33f-11eb-8d2f-6990966ebd11.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Windows 10 Pro for Workstations
- CPU: Intel Xeon E5-2699 V4

**Additional context**
I tried restarting the computer again and reinstalling Chia, but the problem was not resolved

**Comment by secco04** [comment]
try removing the missing plot directory from config.yaml while chia and all services are down

**Comment by lvcivs** [comment]
duplicate of #3586

**Comment by mehmetsisoglu** [comment]
same problem.

**Comment by damianmadeira** [comment]
other problem whit Win10
hello everybody, i did what you sey but i can't add the plot directory. Also install version 1.1.7 and i get the same error "argument of type 'NoneType' is not iterable ".

![image](https://user-images.githubusercontent.com/56444256/120947102-0eb64900-c715-11eb-8a2c-efc47e3ad1f8.png)

**Comment by damianmadeira** [comment]
new error when starting to create plots:
![image](https://user-images.githubusercontent.com/56444256/120947502-23dfa780-c716-11eb-91bb-ce07e883e7cc.png)
