### ISSUE TITLE
After update 1.1.5 no syncing 

### ISSUE THREAD

**Issue by MrChia** [Chia-Network/chia-blockchain#4666]
Been sitting here for almost 5 hours and no syncing, it has not even started. 

Have I done something wrong?

**Comment by droidfirmwares** [comment]
Update 1.1.5 work perfectly last few days, But today happened this "Not Synced" issue. Now more than 12 hours gone, still the same issue.

**Comment by fborrell23** [comment]
In my logs i'm seeing logs go well and then get lots of 
```
2021-05-12T12:01:00.881 full_node full_node_server        : INFO     Cannot connect to host 49.66.201.179:8444 ssl:<ssl.SSLContext object at 0x0000020A1CF81438> [Connect call failed ('49.66.201.179', 8444)]
2021-05-12T12:01:06.208 full_node full_node_server        : INFO     Cannot connect to host 49.66.201.179:8444 ssl:<ssl.SSLContext object at 0x0000020A1A24AEB8> [Connect call failed ('49.66.201.179', 8444)]
```
That is very weird, usually i got a few connections and a few errors. But this is preventing the app to work correctly.

**Comment by duckduckwho** [comment]
Same issue ! Yesterday works , today not.
<a href="https://ibb.co/nQVq1ZJ"><img src="https://i.ibb.co/nQVq1ZJ/testtttttt.png" alt="testtttttt" border="0"></a>

**Comment by duckduckwho** [comment]
Okay now is Orange : "Status Syncing 179784/269024" ....

**Comment by devilden89** [comment]
Ich habe das selbe Problem seit 1.1.5. Sobald Chia Blockchain am Nachmittag läuft geht es bis Morgens, aber dann morgens ständig keine Synchronisierung mehr. Bis ich Nachmittags/Abends das Programm 4-5 mal neu starte, dann plötzlich fängt er schleppend an zu Synchronisieren ....

Bitte um update.

Schönen Tag noch,

**Comment by duckduckwho** [comment]
+1

**Comment by vercanax** [comment]
Yeah me too, Stocked at 264192, it is 6 hours now... :/

**Comment by cnwolrd** [comment]
> 坐在这里将近5个小时，并且没有同步，甚至还没有开始。
> 
> 我做错什么了吗？

我加一  我更新后就没同步过

**Comment by bo3b** [comment]
Looks like a regression in 1.1.5.  After I uninstalled 1.1.5 and reinstalled 1.1.4 I was able to Sync again.

**Comment by nplanchart** [comment]
Hi, try -Run as administrator-.

**Comment by nplanchart** [comment]
> Been sitting here for almost 5 hours and no syncing, it has not even started.
> 
> Have I done something wrong?

Try -run as administrator-.

**Comment by szuwar32** [comment]
My Full Node 1.1.5 is running under Linux and I have the same problem. After few minutes it loses the synchronization. After the restart sometimes it goes back. I will try downgrade to 1.1.4.

**Comment by Emerson4br** [comment]
hey guys, same here with 1.1.5,  past 15 hours looking yellow bars..
