### ISSUE TITLE
[Bug] Connecting to wallet

### ISSUE THREAD

**Issue by nismanVive** [Chia-Network/chia-blockchain#4674]
After deleting plots from a queue the wallet it stucks on reconnect,
 
reload or force reload do not work, the only way around it is to close it and re open it, 
  
loosing all de lots plotted ( as I just did, lost a 98% K33 plot)
 
 
![image](https://user-images.githubusercontent.com/56160252/117969983-7b991780-b2fe-11eb-8b4d-c96bef8e3d63.png)

Cheers

**Comment by ONEK1LO** [comment]
Seems like if the plot is at 0%, it will likely be removed successfully. But if there is any progress display, the wallet would crash and cause all plots to be lost. The only way to get back is to close the wallet, clean the drives, and start from square 1.

**Comment by toli81** [comment]
I am having the same problem. I updated and restarted windows. Still stuck in loading wallet screen.

**Comment by adrianr85** [comment]
Having the same problem ,clean install, my  first start. :(

**Comment by toli81** [comment]
so if i reinstall chia with my seed phrases, i can still use my plots correct?

**Comment by nismanVive** [comment]
I'm adding that I just tested it again, and it only happens if you delete more than one plot at the same time, at least for me

**Comment by nismanVive** [comment]
> so if i reinstall chia with my seed phrases, i can still use my plots correct?

Yes, this is correct

**Comment by toli81** [comment]
damn, uninstalled, restarted computer, downloaded updated chia version, still stuck connnecting to wallet loop.

**Comment by Sergey201381** [comment]
и что делать народ? не может подключиться к кошельку

**Comment by Suvix5** [comment]
Same problem here. Already reinstall and didn't solve...

**Comment by tonimonton** [comment]
mismo problema. alguna solucion? tengo la version 1.1.5

**Comment by Coopercry** [comment]
same problem

**Comment by UnitedMiddle31** [comment]
Same Problem on Windows.

**Comment by toli81** [comment]
my other pc thats plotting has been stuck on same % since last night, is the chia mainnet having issues?

**Comment by Alienrogal** [comment]
Hi, I was creating 4 plots and decide to remove one of them. After it the wallet cannot connect with server :( Too much time lost

**Comment by tonimonton** [comment]
La solucion ha sido borrar la carpeta .chia(C:\Users\user\.chia)

**Comment by Basil43** [comment]
Same problem.  Supposedly deleted all, but trying to reinstall just has me at waiting to connect to wallet to even do so.  I don't know how to wipe it any more clean than deleting the program at uninstall.

**Comment by progenitorepic** [comment]
> La solucion ha sido borrar la carpeta .chia(C:\Users\user.chia)

DAMN! It`s working!

**Comment by Plopsi** [comment]
If it's only the wallet you can try to just delete C:\Users\youruser\.chia\mainnet\wallet\db - that way only the wallet need to resync and not the whole chain, you not even need to reenter the seed

**Comment by progenitorepic** [comment]
> If it's only the wallet you can try to just delete C:\Users\youruser.chia\mainnet\wallet\db - that way only the wallet need to resync and not the whole chain, you not even need to reenter the seed

I completely deleted the folder and now i need to resyns chain only.

**Comment by Suvix5** [comment]
> La solucion ha sido borrar la carpeta .chia(C:\Users\user.chia)

Gracias 🙏

**Comment by toli81** [comment]
so is it possible to download the last version of chia somewhere, and try reinstalling that?

**Comment by chia888** [comment]
Until Now im stuck ini connecting wallet, any idea.

**Comment by Plopsi** [comment]
> 
> 
> Until Now im stuck ini connecting wallet, any idea.

Have you tried https://github.com/Chia-Network/chia-blockchain/issues/4674#issuecomment-840054122 or https://github.com/Chia-Network/chia-blockchain/issues/4674#issuecomment-840060705 ?

**Comment by Plopsi** [comment]
> 
> 
> so is it possible to download the last version of chia somewhere, and try reinstalling that?

Yes of course:

https://www.chia.net/releases/

**Comment by toli81** [comment]
https://github.com/Chia-Network/chia-blockchain/releases/tag/1.1.4     Found the older version, gonna try it.

**Comment by chia888** [comment]
same problem to try 1.1.4

**Comment by xie1986** [comment]
using VPN its working or no

**Comment by Sergey201381** [comment]
Thank God!!!!! I figured it out

**Comment by Sergey201381** [comment]
All this problem was arranged by your brandmair Windows. In order to reset it, you need to go to the command line (с:windows/sis32/cmd) as administrator and enter this (netsh advfirewall reset)

**Comment by rlgdreis** [comment]
> If it's only the wallet you can try to just delete C:\Users\youruser.chia\mainnet\wallet\db - that way only the wallet need to resync and not the whole chain, you not even need to reenter the seed

Now I’m missing from XCH from my wallet.

**Comment by Plopsi** [comment]
Your wallet now resyncs with your local full node - give it a while, you can check the status and sync-height of the wallet under wallets

![grafik](https://user-images.githubusercontent.com/17942998/118129328-5559a180-b3fc-11eb-9bcd-93d206c5408d.png)
