### ISSUE TITLE
[BUG] None of your plots have passed the plot filter yet. But you are currently farming xxx TiB update pic

### ISSUE THREAD

**Issue by aircoolza** [Chia-Network/chia-blockchain#4675]
**Describe the bug**
my account show Syncing on green  and wallet and plot show syncing on green too 

but in <h1>Last Attempted Proof  </h1>it show  None of your plots have passed the plot filter yet. But you are currently farming xxx TiB

![รูปที่1](https://www.img.in.th/images/95488bbeb55b0e355614b6a897ad5da3.png) 

in box it not show any thing T^T

please help me how to fix 

i try to change down version but not ok    

thank you for help

**Comment by Bigman397** [comment]
This is expected and means things are working as intended. You can continue to add more plots to increase you chances of passing those filters, its just waiting game at this point.
