### ISSUE TITLE
Node Status Not Synced

### ISSUE THREAD

**Issue by TheGod5** [Chia-Network/chia-blockchain#4676]
I have starting farming on chia network. I have download app and start. I am waiting last 6 hours wallet status is not synced yet.

**Comment by asit27** [comment]
Since 6 days, it is not synchronized, there is no explanation nor anything else, I received static IP service just because of this, but it did not happen again.

**Comment by teejayen** [comment]
Generally the initial synchronisation can take ~24-48 hours I have found across different machines.

**Comment by TheGod5** [comment]
It is showing not synced not syncing.

**Comment by TheGod5** [comment]
I mean it os showing '' Status -   Not Synced'' not showing 'Syncing'.

**Comment by asit27** [comment]
My first synchronization process took 36 hours and I farm for 3 days, but the synchronization broke down on 06.05.2021 and it never started again.They need to publish an application that will trigger this synchronization event, the number of people who are victims of this problem is not less.

**Comment by TheGod5** [comment]
My syncing started for 1 time. I have done these step god C: drive>users>current user (admin) >Delete .chia folder and then go app data>Local and delete chia-blockchain.  Then i restart my app then my syncing is started but again status is not syncing
