### ISSUE TITLE
Found proof but no reward

### ISSUE THREAD

**Issue by eterne92** [Chia-Network/chia-blockchain#4679]
Just found a proof but did not get the reward by having a NO_OVERFLOWS_IN_FIRST_SUB_SLOT_NEW_EPOCH error, any idea on what's going wrong with my machine?
log is like
full_node chia.full_node.full_node: ERROR    Error farming block Error code: NO_OVERFLOWS_IN_FIRST_SUB_SLOT_NEW_EPOCH

**Comment by gromran** [comment]
which version?

**Comment by eterne92** [comment]
> which version?

1.1.6dev0 at that moment

**Comment by ddowhy** [comment]
This is an issue.  Just had this happen to me.  Same error code.
