### ISSUE TITLE
Double Spend and Negative Balance

### ISSUE THREAD

**Issue by xSwarth** [Chia-Network/chia-blockchain#4683]
Yesterday i had to reinstall the wallet from 0 (version 1.1.5), after a good 16h it synced and i noticed that while i should have had 0 in the balance, it was showing 225.75 (in the GUI and also from CLI), out of curiosity i tried to do a transaction and got a Double Spend message.

This was the Wallet balance after i tried the transaction, before also the Pending Total Balance was showing 225.75:

![image](https://user-images.githubusercontent.com/36101429/117980534-5a531e00-b334-11eb-95b5-5ab264fbc9ec.png)

After i restarted the wallet the balance on the GUI is showing correctly while if i check from CLI this is the result, negative balance:

![image](https://user-images.githubusercontent.com/36101429/117980733-8f5f7080-b334-11eb-878c-efb36cd07744.png)

Now my log is also being spammed with some transaction error, guess it's cause the double spend transaction i tried.
Attached you can find the log file at info level.

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/6466385/debug.log)

**Comment by Shigma** [comment]
I just ran into exactly the same problem.

**Comment by 13616557022** [comment]
me too. it shows  double spend and lost some coin (I dont know the exact amonut)

**Comment by alexander9019** [comment]
i lost 1 xch ,when making a transaction. I wanted to pass a coin to another wallet and the system discounted two coins instead of one, someone knows who
can you help me?

**Comment by JsBlueCat** [comment]
delete the wallet in .chia/mainnet/wallet. and do sync please
