### ISSUE TITLE
[BUG] It is showing March 2021 date and time 

### ISSUE THREAD

**Issue by TheGod5** [Chia-Network/chia-blockchain#4689]
**Describe the bug**
When i open this app this is showing March 2021 Date and Time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 10]
- OS Version/Flavor: [Latest Version]
- CPU: [Intel i5 10400]

**Additional context**

**Comment by MustDhiMust** [comment]
check your computer time and date

**Comment by TheGod5** [comment]
That was right
