### ISSUE TITLE
[BUG] Wallet Status in not synchronise any port

### ISSUE THREAD

**Issue by TheGod5** [Chia-Network/chia-blockchain#4693]
**Describe the bug**
Wallet Status in not synchronise any port. I have tried all ports but synchronisation is not started.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 10]
- OS Version/Flavor: [ Latest Version]
- CPU: [Intel i5 10400]

**Additional context**

**Comment by racabu** [comment]
This synchronization issue is getting out of hand. I'm almost giving up... every day I check and the node is not synched anymore... I have to keep manually trying to reconnect over and over for almost an hour and then it synchronizes back again.
And who knows for how long it was not farming... really frustrating.

**Comment by AlexJofer** [comment]
Same here, ...and I don´t know why! It´s so frustating

**Comment by AlexJofer** [comment]
I've tried all this Ip´s and none of them are working with my wallet! It´s a pain in the ass

Introducers addresses:

North Asia introducer-apne.chia.net:8444
South Asia introducer-apse.chia.net:8444
Western North America: introducer-or.chia.net:8444
Eastern North America introducer-va.chia.net:8444
Europe: introducer-eu.chia.net:8444

And then add these nodes addresses:
North America: node-or.chia.net:8444
Europe: node-eu.chia.net:8444
Asia: node-apne.chia.net:8444

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
