### ISSUE TITLE
[BUG]Consensus error 124 when Creating new plots

### ISSUE THREAD

**Issue by GaoDeGan** [Chia-Network/chia-blockchain#4694]
**Describe the bug**
The GUI shows "connecting to wallet" and ALL plotting jobs shut down sometimes when creating a new plots

**To Reproduce**

1. some plots are now being plotting
2. create a new plot
3. select path or plotting paraments
4. probably crash

**Expected behavior**
The GUI shows "connecting to wallet" and ALL plotting jobs shut down.
In Log file it is recorded as Consensus error 124

**Desktop (please complete the following information):**

- OS: Win 10
- OS Version/Flavor: 2004
- CPU: intel i7-9750H

**Comment by AndersStruck** [comment]
Consensus error 124 #4339 is not related to your own plots. but rather other peers using an old client when connecting to your node.

**Comment by GaoDeGan** [comment]
> Consensus error 124 #4339 is not related to your own plots. but rather other peers using an old client when connecting to your node.

But I ran into this error several times. Each time that happened, I was setting paraments of new plots. It doesn't make sense.
