### ISSUE TITLE
[BUG] Plot hits 100% complete - then hangs

### ISSUE THREAD

**Issue by forkmiester** [Chia-Network/chia-blockchain#4699]
**Describe the bug**
A plot has completed and then has issues converting the plot to a farm and hangs at 100% done indefinitely. (On both of my plotting/farming machines)

**To Reproduce**
1. Create a plot (.
2. Advanced. Select 4 threads. 7168 memory. All else defaults
3. select 400Gb SSD as temp
4. select 1 Tb storage serial drive.
5. Start Plot
6. Click Refresh - it hangs on "Connecting to Wallet"

**Expected behavior**
Plot continues for about 8 hours up to 100%, then converts to farm. Next plot starts.
**Screenshots**
I have them but there is no way to attach an image here.

**Desktop (please complete the following information):**
-OS: Windows 10
-OS Version: 20H2
- CPU: AMD FX-4130 Quad-Core
- RAM: 16Gb DDR3
- Hard drives: 1 Solid state (500Gb), lots of SATA drives
**Additional context**

**Comment by ninthwalker** [comment]
Don't click that refresh button imo. Causes issues right now.

**Comment by LewyMaster** [comment]
Please check if finished plot (101GiB) is in temp directory. if plot is finished but not copied properly then i think you can copy this final .plot.tmp file and rename it by removing postfix .tmp (Please let some developer correct me if I'm wrong). I had one that situation in the past and it worked for me.

**Comment by forkmiester** [comment]
Happened again on my next plot. So weird. The file is in the final directory but still a temp file. I'm going to close it down and rename it and see if it appears.

**Comment by countyuk** [comment]
Hi, following.    Same issue and tried the above to no avail.

**Comment by ivensaugusto** [comment]
Same here.
using standart settings: 3390 ram and two threads.
