### ISSUE TITLE
My chia no synced.

### ISSUE THREAD

**Issue by lcmrose** [Chia-Network/chia-blockchain#4702]
I run chia node 10 days, and suddenly shows no synced . it happened twice, and I closed my computer firewall last time and it was back synced again. What happened this time? I checked my firewall still off. How can I fix the problem this time? Thank you.

**Comment by dennissky** [comment]
same to you.when i chia stop all -d  re start all failed. version 1.1.5

**Comment by gregoriob** [comment]
Same. Never reaches synced status. Days like this now, firewall cleared, using official peers which don't seem to help. Bored of waiting for this every day. V1.1.5
