### ISSUE TITLE
[BUG] connected, not synced. 

### ISSUE THREAD

**Issue by zorro9527** [Chia-Network/chia-blockchain#4716]
empty

**Comment by hajes** [comment]
chia 1.1.6 still intermittent sync issues...no sync for over 3 hours

**Comment by mikail0698** [comment]
Modem arayüzünden port oluşturmama rağmen hala senkronize edemedim. Araştırmadığım site denemediğim yöntem kalmadı. Çözümü bilen yardımcı olacak birisi varsa çok memnun olurum.

**Comment by michael-trinity** [comment]
try adding these peers on port 8444
39.108.98.240
24.101.133.109
31.43.194.89
121.13.108.190

**Comment by hajes** [comment]
it looks like the only way to get stable sync is to open port 8444 in router. So far, no sync issues with port forward.
