### ISSUE TITLE
[BUG] [GUI] chrome-sandbox is owned by root and has mode 4755

### ISSUE THREAD

**Issue by Youness-e** [Chia-Network/chia-blockchain#4721]
I have this error on my fresh install Debian Buster. I followed the installation guide (from source code), but i have this error when i try to launch gui

`[5017:0512/191633.734238:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/farmer/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.`
`/home/farmer/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGTRAP`
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: 'electron '.
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.`

**Comment by elarkasi** [comment]
you can follow the info to change the owner and mode.

**Comment by Youness-e** [comment]
> you can follow the info to change the owner and mode.

Already done, but no change (and i don't like the idea of giving root permission to this executable :disappointed: )

**Comment by lemugen** [comment]
this work for me
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox

**Comment by rn185124** [comment]
this work for me
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox

**Comment by emlowe** [comment]
keepalive

**Comment by emlowe** [comment]
keep-alive

**Comment by akshayknz** [comment]
I get this on my WSL

**Comment by emlowe** [comment]
This seems to be working on Ubuntu for both manual installation and the DEB 
The RPM needed some adjustments - #9421

**Comment by restufauzi697** [comment]
how about using the --no-sandbox flag
for me it works,
```bash
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Visual Studio Code
Exec=/usr/bin/chromium --no-sandbox --profile-directory=Default --app-id=jhdpafkbedbgckdnecbbppbpboebapeb
Icon=code
StartupWMClass=crx_jhdpafkbedbgckdnecbbppbpboebapeb
```

**Comment by Centurion95** [comment]
> 

Worked on Debian 10!

**Comment by Centurion95** [comment]
> this work for me sudo chown root:root chrome-sandbox sudo chmod 4755 chrome-sandbox

Worked on Debian 10

**Comment by algarsal** [comment]
> this work for me sudo chown root:root chrome-sandbox sudo chmod 4755 chrome-sandbox

For  me it worked only with second line: 
sudo chmod 4755 chrome-sandbox

**Comment by raddevus** [comment]
The unfortunate part of this is that for every electron app you run you will get a new path that needs the file modifications.
For example when I run an app at: `~/electron/<MyApp>` then I get the error message that states: 
`/electron/<MyApp>/node_modules/electron/dist/chrome-sandbox`  where the <MyApp> portion changes for every app you create.

So (of course) I wrote a `bash` script.  
1. If you don't give it a path then it will tell you and return (doing nothing).
2. If you give it a bad path then it will tell you the path doesn't exist
3. If you give it a valid path it will run the `chown` & `chmod` on the path for you.

```
dirPath=$1
echo $dirPath
if [ -z "$dirPath" ]; then
	echo "Please provide a valid path. Exiting..."
	exit 1
fi
sudo chown root:root $dirPath
sudo chmod 4755 $dirPath
```

Hope this helps you.
