### ISSUE TITLE
Unable to synchronize Full Node. 

### ISSUE THREAD

**Issue by RRP1479** [Chia-Network/chia-blockchain#473]
Full Node not updating past Max Tip Block Height: 11996 10/13/2020 3:11:53 AM LCA Time on current beta .15.
I've gone back to the previous versions, as far as .13, with the same results.
![chiab15](https://user-images.githubusercontent.com/72996104/96298464-b5e04780-0faf-11eb-9bbe-bc520749bb43.png)

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/5393792/debug.log)

**Comment by hoffmang9** [comment]
This is a known issue - search 11996 in the Keybase #testnet where you can find a database copy that will get you past this issue. Basically shut the app down and copy the database into `~./chia/beta-1.0b15/db/` directory

**Comment by RRP1479** [comment]
Found it. Thanks 👍
