### ISSUE TITLE
[BUG]please help, when I go into the wallet these three circles are spinning and nothing else, the rafts are seeded, but the wallet is not synchronized and shows nothing but these spinning circles

### ISSUE THREAD

**Issue by Chiauser** [Chia-Network/chia-blockchain#4731]
please help, when I go into the wallet these three circles are spinning and nothing else, the rafts are seeded, but the wallet is not synchronized and shows nothing but these spinning circles
![изображение_2021-05-12_215151](https://user-images.githubusercontent.com/84098950/118028875-42978c00-b36c-11eb-8727-00c54a976508.png)

**Comment by Popi-Hunter** [comment]
I have same issue... i just shutdown software in background and start it again.... use task manager

**Comment by ZIKYN** [comment]
> У меня такая же проблема ... я просто выключаю программное обеспечение в фоновом режиме и запускаю его снова ... используйте диспетчер задач

Does the plotting process stop and all progress flies? is not it ?

**Comment by Chiauser** [comment]
> > У меня такая же проблема ... я просто выключаю программное обеспечение в фоновом режиме и запускаю его снова ... используйте диспетчер задач
> 
> Does the plotting process stop and all progress flies? is not it ?

I can plotting but my plots that i already have -don't farming

**Comment by Chiauser** [comment]
> I have same issue... i just shutdown software in background and start it again.... use task manager


It helps? tell me more about how to do it!!!
