### ISSUE TITLE
[BUG] Rubbish Software

### ISSUE THREAD

**Issue by SKYBILLS** [Chia-Network/chia-blockchain#4732]
Wallet Sync stop at half way , i already delete wallet db and re-sync also same halt at half way , after restart software then sync little time after stop again , really make people headache , already at version 1.1.5
![Screenshot (8)](https://user-images.githubusercontent.com/33307099/118028956-3f18fa80-b396-11eb-9fda-34e7f9ff3408.png)

**Comment by centrd** [comment]
This is not the place to vent.. Nor is this a bug.

**Comment by boner-cmd** [comment]
Wallet failing to sync is a bug that many other users have. So while it's not a great bug report... it sure is a bug.

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
