### ISSUE TITLE
[BUG] Reload wallet leads to freeze: stuck on "Connecting to wallet"

### ISSUE THREAD

**Issue by magnusmyklebost** [Chia-Network/chia-blockchain#4739]
**Describe the bug**
Pressed CRTL + R to reload chrome page, when I didnt realize chia window was active. Now it froze on connecting to wallet again. Using latest 1.1.5 and having 14 parallel plots going. As time consuming this activity is to set up we need more stable software. this is driving me crazy... Please let me diable hotkeys when this happens when you reload! This happened in 1.1.4, and still happens.

**To Reproduce**
Go to wallet
Press reload (ctrl + R)

**Expected behavior**
Stuck on connecting to wallet.
**Screenshots**
![image](https://user-images.githubusercontent.com/36155808/118035572-ab323900-b36b-11eb-8497-49cf2feb9946.png)

**Desktop (please complete the following information):**
Windows 10 latest
AMD 5900x
Chia 1.1.5

**Additional context**

**Comment by mxmgit** [comment]
delete the folder '.chia' at 'C:\Users\YOUR_USERNAME' , and run it again, this should help

**Comment by ZIKYN** [comment]
I have the same problem every day. You have to wait a long time for the plotting process to end and restart the application or computer. This problem is ubiquitous and cannot be solved in any way!!

**Comment by Zurginator** [comment]
Same here..., I had a number of Plots going, had to delete 1 ... yes I just had to delete 1.... now I am in the same Connecting to wallet screen, lol. 
Seriously horribly unstable wallet.

**Comment by Joedogga** [comment]
same here i was maxing out my ssd and had to make rood i deleted 1 plot and poof been loading for 15 hours now

**Comment by chia888** [comment]
more than 16 hours cant connect my wallet, i dont know how

**Comment by Khunmatthew** [comment]
you are not alone, dont try to reload or force reload !!!! it cannot solve any problem except stuck at syncing the wallet

**Comment by magnusmyklebost** [comment]
yea, i didnt reload on purpose. its crazy that they have such a common hotkey for reload when its so unstable. 
press ctrl r to crash your plotting? smart🤦

**Comment by Snuups** [comment]
So the solution to this problem is giving up until a version is released which fixes this bug?

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
