### ISSUE TITLE
[BUG] Chia wallet fails to start

### ISSUE THREAD

**Issue by evilstack** [Chia-Network/chia-blockchain#4741]
**Describe the bug**
Chia wallet fails to start. The wallet process will run if `chia start wallet` is issued, but does not listen on any port. Traceback output is in attached file.

**To Reproduce**
```
# . ./activate
# chia start node
# chia wallet show
# chia start wallet
# chia wallet show
# chia stop wallet
```
**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Manjaro
- CPU: Intel i5-6600k

**Additional context**
```
# git status
On branch main
Your branch is up to date with 'origin/main'.  
# python -V
Python 3.9.4
```
Output of troubleshooting attached
[chia.log](https://github.com/Chia-Network/chia-blockchain/files/6469009/chia.log)

**Comment by michael-trinity** [comment]
what are your firewall settings? Or is that disabled?

**Comment by evilstack** [comment]
I doubt firewall has anything to do with it since I'm getting a traceback when starting the wallet and the socket isn't opening, but no I do not have a host firewall enabled.

**Comment by evilstack** [comment]
Duplicate of #4245
