### ISSUE TITLE
[BUG] Less than 100% on plotting finish when set less than 128 buckets 

### ISSUE THREAD

**Issue by LewyMaster** [Chia-Network/chia-blockchain#4743]
**Description**
I see 52% when plotting is finished with 64 buckets in settings.

**Steps to reproduce**
Try to "add a plot" with less than 128 buckets.
(Additional set 1 core and 4806 MiB RAM but on other settings i had the same results)

**Expected behavior**
100% on plotting finish

**Current result**
Plotting finish at 52%.

**Screenshots**
![image](https://user-images.githubusercontent.com/84103248/118043002-1a605b00-b375-11eb-8b48-9d70b8b448da.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Education
- OS Version/Flavor: 1909 (compilation 18363.1500)
- CPU: Intel Core i5-8600K (3.6 GHz)
- Chia-blockchain: 1.1.5

**Additional context**
It is not critical. Plot was copied to destination folder successfully but at first time i was suprised when i saw 40-50% and then new plot started, so i decided to check it and catch screenshot on finish.
I creating plots in queue (not parallel)

**Comment by baizuchong-net** [comment]
这是正常的，只要最终能生成 地块就行

**Comment by sargonas** [comment]
Further info discovered in #4946 adds to the subject that changing both buckets and other advanced parameters like memory and cores in the GUI has an effect on percentage accuracy calculation.
