### ISSUE TITLE
Estimated Time to Win[BUG]

### ISSUE THREAD

**Issue by capschia** [Chia-Network/chia-blockchain#4749]
**Describe the bug**
Estimated Time to Win not changing 
when I plotting 5tib it showed 5 month now i have reached almost 7 Tib it still shows 5 month  why?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by kennylbj** [comment]
That's because the space for the entire network is also growing.

**Comment by night-lurker** [comment]
its because over 1 month it dont show days 
so 55 days might be a month
