### ISSUE TITLE
Status: Not Synced [BUG]

### ISSUE THREAD

**Issue by foulballguy** [Chia-Network/chia-blockchain#4751]
ive had to repeatedly delete my chia file info to get it to connect to wallet, and now i am back in i can not get it to sync any plots and all new attempts at creating a new plot will not finish or sync either. both pc's i am plotting with just freeze and refuse to sync. 

running windows 10: virus protection off, firewall down.
16gb ram
ryxen 5800x
evga 1650 s
8tb sandisk external

**Comment by omarattia2** [comment]
i have the same issue if you did fix it please help

**Comment by HudsonProdigy** [comment]
same issue. I even tried switching from windows to linux. same problem syncs all blocks up to date but then says not synced...

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
