### ISSUE TITLE
[BUG]Removal of a plot does not work and hangs forever

### ISSUE THREAD

**Issue by lsherring** [Chia-Network/chia-blockchain#4752]
**Describe the bug**
When you try to remove a plot due to an error you made and others are plotting, it never removes anything and stays in removal mode never changing.  You then try to shut Chia down and it just stays hung in the 'closing down node & server' and never shuts down. On some occasions it gets to connecting to wallet and hangs there.  Waited over 30 minutes.

**To Reproduce**
Windows 10 Pro
Ryzen 9 3950
64GB Ram
5TB SSD
116TB HDD space

Happens every time.  The plotting on one group was at 17% when the other was at 10% and I noticed I put to many plots on one SSD and wanted to remove it, but this issues occurs.  Need to reboot the server, format the SSD's and start all over.

I ran DVT for 14 years where we made the first commercial RAID product in the world.  This is a bug probably due to some interaction with Windows.  Linux usually no issues like this.

![Capture](https://user-images.githubusercontent.com/84110776/118065103-3e11aa00-b351-11eb-8452-f4bedcbcacd4.PNG)

**Comment by Blueforcer** [comment]
Same problem,
As soon you want to remove a plotting process while another one is still plotting, all deamons and nodes etc are closed immediately.
You can see it in the taskmanager, only GUI ist still alive. This is reproducible at any time

**Comment by Ratzoletto** [comment]
I have an error and a freeze on one plot. I don't delete it (32%) because of ongoing plots on other disks and the bug reported in this topic. 

V 1.1.5; Win 10
