### ISSUE TITLE
conectar con el monedero

### ISSUE THREAD

**Issue by Gabrielduran** [Chia-Network/chia-blockchain#4753]
tengo ya 1 mes intentando entrar con el blockchain de chia pero cando abro el programa solamente se queda en conectando con monedero y nunca termina de cargar, lo he dejado incluso mas de 12 horas cargando y nunca conecta, mi internet funciona bien, la pc igual, todo normal pero no conecta, me podrian brindar una solucion por favor, gracias

**Comment by Gadd88** [comment]
Same problem here... i

**Comment by agueromauro** [comment]
pudiste solucionarlo?

**Comment by juanieto** [comment]
buenas tardes, es un poco complicado encontrar la solución por que el problema es que la mayoría de información esta en ingles
 yo tenia el mismo problema, la cuestión es (en Windows) es permitir al firewall ejecutar el programa a través de este. firewall resulto ser el causante de mi problema. ojala le sirva de ayuda a alguien 
salu2
