### ISSUE TITLE
[BUG] Status not sync

### ISSUE THREAD

**Issue by paritad99** [Chia-Network/chia-blockchain#4754]
i've had to repeatedly delete my chia file info to get it to connect to wallet, and now i am back in i can not get it to sync any plots and all new attempts at creating a new plot will not finish or sync either. both pc's i am plotting with just freeze and refuse to sync.

running windows 10: virus protection off, firewall down.
4gb ram
intel core i5 
SSD 512 : R/W 500/500 
5tb sandisk external

**Comment by baizuchong-net** [comment]
me to

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
