### ISSUE TITLE
[BUG]Error Operation not permitted. Retrying in five minutes.

### ISSUE THREAD

**Issue by langubtc** [Chia-Network/chia-blockchain#4756]
Hello my plot server is ubuntu 20.04 and mount windows ntfs device .But copy tmp file alert error message
Could not copy "/temp/chia1/plot-k32-2021-05-13-01-44-334b63f7ce0000157356fa1774741ecafdea77a4ca320a8190f3e9dc20d16424.plot.2.tmp" to "/work/plot-k32-2021-05-13-01-44-334b63f7ce0000157356fa1774741ecafdea77a4ca320a8190f3e9dc20d16424.plot.2.tmp". Error Operation not permitted. Retrying in five minutes.

**Comment by awright69** [comment]
Check to see if your process has rights to the target (destination) for your plot. In my case,I had my external hard drive formatted as Mac OS Extended and it would not write to it; reformatting as APFS or ExFAT made it work just fine.

**Comment by FoZo** [comment]
Same issue with ubuntu 20.04 under windows.
Both drives are formatted as ntfs.
Manual copy with the same user works fine.

**Comment by Tamerz** [comment]
I'm hitting something similar. I have a Ubuntu 20.04 machine and the plots are on an SMB share. I also can copy the file manually no problem with the same user.

**Comment by andymarden** [comment]
Similar problem for me. Ubuntu 21.04. Internal temp disk is NVME, final destination is exfat (formatted through Ubuntu).
Plots get to 100% and have "trying every 5 mins" in the log. The destination has the a 0 byte tmp file created but then it seems that it cannot copy any data over beyond that. 
Cancelling the plot and then manually copying the tmp file over manually and renaming works fine.
It seems to the way that the copy over is done in Python but can't see where that is in the code or I could try something different.
Can someone look at this and see if we can get a different method used?

**Comment by andymarden** [comment]
Just tried it out with an ext4 fs on the farm disk - that works fine. Phew! At least I have a way forward but there is def a bug in there somewhere for other fs types

**Comment by langubtc** [comment]
> Just tried it out with an ext4 fs on the farm disk - that works fine. Phew! At least I have a way forward but there is def a bug in there somewhere for other fs types

Yes ext4 is ok

**Comment by elforesto** [comment]
I'm getting the same error. VM guest, Ubuntu Server 20.04.2 LTS on byhve hypervisor, destination is a mounted Samba share from the TrueNAS 12 host. I have a Docker container on a different guest, same host, no problems with copying on it. As others have described, I can copy it manually without any issue, it's only the chia plotter that runs into this defect.

Interesting note, I get the following when I move it manually which may be related.

`(venv) elforesto@chiamain:/mnt/chia-temp2$ mv *.tmp ../chia-plots/
mv: preserving times for '../chia-plots/plot-k32-2021-05-20-19-35-159bb6da3376fd79c02778fae7dffa4917f4faa99771ad3451c931552dce3b54.plot.2.tmp': Operation not permitted
mv: preserving permissions for ‘../chia-plots/plot-k32-2021-05-20-19-35-159bb6da3376fd79c02778fae7dffa4917f4faa99771ad3451c931552dce3b54.plot.2.tmp’: Operation not permitted`

The source directory is ext4. Maybe that's a factor?

**Comment by Tamerz** [comment]
> 
> 
> I'm getting the same error. VM guest, Ubuntu Server 20.04.2 LTS on byhve hypervisor, destination is a mounted Samba share from the TrueNAS 12 host. I have a Docker container on a different guest, same host, no problems with copying on it. As others have described, I can copy it manually without any issue, it's only the chia plotter that runs into this defect.
> 
> Interesting note, I get the following when I move it manually which may be related.
> 
> `(venv) elforesto@chiamain:/mnt/chia-temp2$ mv *.tmp ../chia-plots/ mv: preserving times for '../chia-plots/plot-k32-2021-05-20-19-35-159bb6da3376fd79c02778fae7dffa4917f4faa99771ad3451c931552dce3b54.plot.2.tmp': Operation not permitted mv: preserving permissions for ‘../chia-plots/plot-k32-2021-05-20-19-35-159bb6da3376fd79c02778fae7dffa4917f4faa99771ad3451c931552dce3b54.plot.2.tmp’: Operation not permitted`
> 
> The source directory is ext4. Maybe that's a factor?

Have you tried adding the `uid=username,gid=groupname` option to your fstab when mounting? That did the trick for me. When I only specified the group I had the exact same errors as you.

**Comment by joseasrocha** [comment]
Same error here. Ubuntu Server 20.04.2 LTS on HP ProLiant BL460c Gen8, destination is a mounted cifs share from Windows Server 2016. 
The user running Swar Plot Manager can copy the files manually without any issue, it's only the chia plotter that runs into this error.

My setup:

Temp file: /plots/temp (mounted internal SSD)
Plot destination files: /plots/farm (mounted windows server cifs share, with full permissions on files and directories) as you can see from the following fstab line:
`//112.24.1.15/plots01 /plots/farm cifs credentials=/etc/win_cred,file_mode=0777,dir_mode=0777,rw,nounix,iocharset=utf8 0 0`

I'm doing manual copies on each server .... anyone has a clue about how to fix this?

**Comment by Tamerz** [comment]
> 
> 
> Same error here. Ubuntu Server 20.04.2 LTS on HP ProLiant BL460c Gen8, destination is a mounted cifs share from Windows Server 2016.
> The user running Swar Plot Manager can copy the files manually without any issue, it's only the chia plotter that runs into this error.
> 
> My setup:
> 
> Temp file: /plots/temp (mounted internal SSD)
> Plot destination files: /plots/farm (mounted windows server cifs share, with full permissions on files and directories) as you can see from the following fstab line:
> `//112.24.1.15/plots01 /plots/farm cifs credentials=/etc/win_cred,file_mode=0777,dir_mode=0777,rw,nounix,iocharset=utf8 0 0`
> 
> I'm doing manual copies on each server .... anyone has a clue about how to fix this?

Try these mount options. My user and group is just 'chia' so I put that for uid and gid. Replace with your own.
`//112.24.1.15/plots01 /plots/farm cifs uid=chia,gid=chia,file_mode=0664,dir_mode=0775,credentials=/etc/win_cred,iocharset=utf8,vers=3.0 0 0`

**Comment by randhomejoe** [comment]
Do we please have a final resolution for the issue? 

Hi,

I run Swar manager on Ubuntu and have mounted drive (formated as exfat) over the network to windows. (mnt/disks/D) via CIFS

I mounted as follwing : `mount -t cifs -o username=HASPOBA,dir_mode=0777,file_mode=0777,nounix //192.168.1.223/e2 /mnt/win_share/E`

I can copy the files manually without any issues but Swar does not copy them and gives me :

Error Operation not permitted. Retrying in five minutes.

**Comment by randhomejoe** [comment]
> Same error here. Ubuntu Server 20.04.2 LTS on HP ProLiant BL460c Gen8, destination is a mounted cifs share from Windows Server 2016.
> The user running Swar Plot Manager can copy the files manually without any issue, it's only the chia plotter that runs into this error.
> 
> My setup:
> 
> Temp file: /plots/temp (mounted internal SSD)
> Plot destination files: /plots/farm (mounted windows server cifs share, with full permissions on files and directories) as you can see from the following fstab line:
> `//112.24.1.15/plots01 /plots/farm cifs credentials=/etc/win_cred,file_mode=0777,dir_mode=0777,rw,nounix,iocharset=utf8 0 0`
> 
> I'm doing manual copies on each server .... anyone has a clue about how to fix this?

Have you pleae find a solution for it mate?

**Comment by mad-cookie** [comment]
Same Error here with my drive formatted to exFat. I'll try to format the drive to ext4 and see if it works.
However, can I save the plot that's been (almost) fully done?

**Comment by cspace001** [comment]
Problem is not solved. Still having problem on QNAP NAS shared drive to Uubuntu.
