### ISSUE TITLE
Extremely slow plotting on powerfull computer

### ISSUE THREAD

**Issue by Deutscher7** [Chia-Network/chia-blockchain#4772]
I have a computer that is doing the plots extremely slow. I have an identical computer creating the plots in 5-6 hours. Same system, same configuration, same specs in both computers. Has anyone experienced the same issue? All temperatures are good. I'm lost

**Comment by twitchplaystrading** [comment]
Wie viel hast du den RAM-Speicher und Threads zugeordnet? Der beste Konfiguration ist +4GB RAM und 4 Threads habe ich gehoert.

**Comment by JessePinkmanVN** [comment]
5-7 hours is normal, I took 6 hours to complete a plot (of course in parallel), 32 gb ram, amd ryzen 9 5900 24 threads and nvme samsung 2tb

**Comment by TorMazila** [comment]
check out your disk i/o stats in windows task manager or similar tools in other OS's.
It's likely the SSD is oversaturated with i/o during a plot.

**Comment by Deutscher7** [comment]
I have a amd 5900 (12 cores)with 64gb ram and 2X 2TB nvme. I honestly don't understand what is wrong. 6 hours and 45 min and I'm still on 2:1 phase
I m using 
Starting plot job: chia plots create -k 32 -r 10 -u 128 -b 5000 -t /mnt/ssd1 -d /mnt/hdd4. Thanks for the help
![Screenshot from 2021-05-13 10-07-04](https://user-images.githubusercontent.com/42296222/118137356-1ebb6100-b3d3-11eb-82bf-7e73bf696329.png)

**Comment by Deutscher7** [comment]
> check out your disk i/o stats in windows task manager or similar tools in other OS's.
> It's likely the SSD is oversaturated with i/o during a plot.

**Comment by Deutscher7** [comment]
> check out your disk i/o stats in windows task manager or similar tools in other OS's.
> It's likely the SSD is oversaturated with i/o during a plot.

I do see that the io are really low in comparison with the other computer. in 6 hours and 45 min phase 2:1 it says 0:23 io. I'm using linux. The other pc has much higher numbers in 6 hours like 1:16 in the io. How can I improve that?

**Comment by Deutscher7** [comment]
> 5-7 hours is normal, I took 6 hours to complete a plot (of course in parallel), 32 gb ram, amd ryzen 9 5900 24 threads and nvme samsung 2tb

you have my same cpu and I have 64gb ram and still I complete a plot in 11 hours. Do you use windows or Linux?

**Comment by TorMazila** [comment]
I do suggest running something that shows how loaded with i/o is your SSD. Maybe it's overheating or just "something is wrong".
iostat and looking at iowait may give some clues. In FreeBSD there's gstat - but it's "geom"-specific tool. There are iotop, dstat, atop - try them.

Try trimming your SSD before launching plotting.

**Comment by danarbraz** [comment]
Firstly, "r 10" is pretty useless at the moment (and on your system, not wise for parallel jobs). Only the first phase is multithreaded. Try backing that down to 4 or 2 (I don't see a  _ton_ of diff between 2 and 4). Secondly, as others are saying, inspect your io. From your screenshot, your jobs are io-bound. Your last job alone has been waiting _23 mins_ on io and it's only in phase 2. I generally start with a low-ish number of parallel jobs where I see **zero** iowait through _all_ phases. From there, I increase parallel jobs up to the point where I start to see some iowait (sub 10 secs) and leave it there.

**Comment by jimmywong123** [comment]
it's about discard, you shuld add discard mode to your disk.
