### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ABSPereira** [Chia-Network/chia-blockchain#4773]
MEu programa da chia custa a conectar e quando abre, abre com tela branca. 

![image](https://user-images.githubusercontent.com/84117989/118082785-2ad3fe00-b394-11eb-9b0b-3a0f9b39b9bb.png)

**Comment by FlavioCimetta** [comment]
Usando a última versão da blockchain?
Qual a config do PC?
Ja tentou desinstalar e instalar novamente a blockchain, apagando os dados da atual ?

**Comment by ABSPereira** [comment]
> Usando a última versão da blockchain?
> Qual a configuração do PC?
> Já tentou desinstalar e instalar novamente a blockchain, apagando os dados da atual?

Boa tarde Flávio. 
Consegui resolver o problema acima. 

Estou com uma dúvida nova aqui:
O FAQ Chia. Diz que as tentativas de verificação devem ter menos de 5 segundos entre elas. Melhor se for menos de 2 segundos . 
Mas meu programa está fazendo em média 10 segundos entre elas . 
o que eu devo fazer para diminuir esse tempo?

**Comment by FlavioCimetta** [comment]
Que bom que resolveu.
Olha, vou ficar te devendo essa informação, viu.
Eu meio que deixei de lado a plotagem, pois estou aguardando o protocolo da pool.

Entao estou meio por fora do que tá rolando atualmente.
Espero que resolva.

Abraços, ótimo dia !
________________________________
De: ABSPereira ***@***.***>
Enviado: sexta-feira, 28 de maio de 2021 20:09
Para: Chia-Network/chia-blockchain ***@***.***>
Cc: FlavioCimetta ***@***.***>; Comment ***@***.***>
Assunto: Re: [Chia-Network/chia-blockchain] [BUG] (#4773)


Usando a última versão da blockchain?
Qual a configuração do PC?
Já tentou desinstalar e instalar novamente a blockchain, apagando os dados da atual?

Boa tarde Flávio.
Consegui resolver o problema acima.

Estou com uma dúvida nova aqui:
O FAQ Chia. Diz que as tentativas de verificação devem ter menos de 5 segundos entre elas. Melhor se for menos de 2 segundos .
Mas meu programa está fazendo em média 10 segundos entre elas .
o que eu devo fazer para diminuir esse tempo?
