### ISSUE TITLE
Wallet not syncing.

### ISSUE THREAD

**Issue by clanseven** [Chia-Network/chia-blockchain#4780]
Wallet status says "syncing" but "height" number not increasing. Full node is synced and connected. I'm using the GUI. This is my third day of continuous farming and although the height number has increased over that period, it is still some 3,000 behind the Full Node height number and randomly seems to stop increasing. Sometimes starts syncing after restarting the software or rebooting, but has not been synced once in three days...

**Expected behavior**
I expect it to sync in tune with the Full Node status. I expect it to work!

Windows 10 64-bit, 20H2 fully updated.
Intel i7-8700K
32 GB RAM
8444 port open.

**Comment by Isanderthul** [comment]
I have the same issue, please check your log file if there is any info. 
in my case I get this message
```
2021-05-13T10:27:11.381 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 96302-96334. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 509, in sync_job
  File "chia\wallet\wallet_node.py", line 606, in _sync
RuntimeError: Was not able to add blocks 96302-96334
```

**Comment by clanseven** [comment]
> I have the same issue, please check your log file if there is any info.
 Dear Isaderthul, I am sorry, but I am a noob to this and don't know how to check the log file. Could you tell me how?

**Comment by clanseven** [comment]
Ok, this seems to have solved itself now as Wallets are now synced.
