### ISSUE TITLE
[BUG]what happen why it show "None of your plots have passed the plot filter yet""Your Full node Connection"  in Farm Overview 

### ISSUE THREAD

**Issue by googgiig9908** [Chia-Network/chia-blockchain#4781]
![Screenshot (2)_LI](https://user-images.githubusercontent.com/82992332/118094401-e29af700-b3f8-11eb-8964-9a5df8f06e85.jpg)
![Screenshot (3)_LI](https://user-images.githubusercontent.com/82992332/118094411-e595e780-b3f8-11eb-9d0f-f67e58b6abdc.jpg)

I have been try uninstall 1.1.5 and renew install try to connect port 8444 and many thing  but still not work.

11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz   2.59 GHz
RAM 16 GB

**Comment by deslumoprime** [comment]
Probably because you're 400 and change years in the future. Tell me, what's the price of Bitcoin and Ether in your time?

**Comment by ZirconSK** [comment]
I have the same issue but correct date set.

**Comment by synchronz** [comment]
It's B.C. 2564 so the date is corrected. I'm having the same issue. Anyone have any solution?

**Comment by cantak** [comment]
Anyone have a solution here? There's a 1/512 chance of a plot passing a filter. With 4608 per day I should have passed something even with one single plot. I have 120 plots on this machine and NO plots have passed the filter.

**Comment by Kevchat** [comment]
Ha guys I have the same problem they were there but after i had internet outage  it shows same as above .

**Comment by seppass** [comment]
You have to sync the clock on the machine.
![Screenshot 2021-05-31 223155](https://user-images.githubusercontent.com/56783257/120266886-0ca94180-c260-11eb-97f2-1692234754f7.png)

**Comment by cristi71000** [comment]
Same thing started to happen all of a sudden. worked perfectly before. Clock is synced

**Comment by alireza-hossein** [comment]
Me too have same problem with mention message " none of your plots .... " very bad sense :(
