### ISSUE TITLE
[BUG] Ubuntu install scripts fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by nattydread69** [Chia-Network/chia-blockchain#4797]
The installation script fails: 

sh install.sh
apt-get is /usr/bin/apt-get
Installing on Ubuntu/Debian 20.04 LTS.
Hit:1 http://ppa.launchpad.net/apandada1/plots/ubuntu focal InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu focal InRelease                                                                                                                                     
Hit:3 http://archive.canonical.com/ubuntu focal InRelease                                                                                                                                     
Ign:4 http://cz.archive.ubuntu.com/ubuntu saucy InRelease                                                                                                                                     
Hit:5 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                                                             
Hit:6 http://ppa.launchpad.net/fengestad/stable/ubuntu focal InRelease                                                                                                               
Err:7 http://cz.archive.ubuntu.com/ubuntu saucy Release                                                                                                                                       
  404  Not Found [IP: 2001:67c:1360:8001::23 80]
Hit:8 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                                                           
Hit:9 http://ppa.launchpad.net/linuxuprising/shutter/ubuntu focal InRelease                                                                                                                   
Hit:10 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                                                    
Ign:11 http://linux.dropbox.com/ubuntu disco InRelease                                                                         
Get:12 http://linux.dropbox.com/ubuntu disco Release [6,598 B]                                                                 
Hit:13 http://ppa.launchpad.net/micahflee/ppa/ubuntu focal InRelease                                     
Get:14 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]                               
Hit:15 https://repo.nordvpn.com/deb/nordvpn/debian stable InRelease                                                 
Hit:16 http://ppa.launchpad.net/openmw/openmw-daily/ubuntu focal InRelease                                          
Ign:17 http://ppa.launchpad.net/phablet-team/tools/ubuntu focal InRelease
Hit:18 http://ppa.launchpad.net/rednotebook/stable/ubuntu focal InRelease
Hit:19 http://ppa.launchpad.net/rock-core/qt4/ubuntu focal InRelease
Err:20 http://ppa.launchpad.net/phablet-team/tools/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::19 80]

**Comment by lvcivs** [comment]
This is an issue with apt, you have a repository configured that does not exist or can't be reached. You need to sort this out before installing chia.

**Comment by nattydread69** [comment]
Ah OK I'll look into that.
