### ISSUE TITLE
[BUG] Exception Trying to connect to a peer ({'host': 'chiadb.net', 'port': 8444}) with the same peer_id:

### ISSUE THREAD

**Issue by dazhazit** [Chia-Network/chia-blockchain#4812]
I have not yet been able to connect to any peers since installing this piece of horse puckey and In truth I'm about to give up on it.
Line 273 of server.py  seems to be checking some kind of peer id and crapping out. What's that all about eh? People say it's your firewall or port forwarding etc. but what I see in the code is a check of GUIDs.

Port 8444 is correctly opened via uPnP on my router and at least some of the hosts are pingable.
chiadb.net and node.chia.net etc have both been tried but I have never been able to connect from the very get go on the windows client. 

To be quite honest this is not what I was expecting for something trading on the crypto market now and not very professional or polished from supposed experts in the crypto field.

Seriously unimpressed.
You need to sort this and pretty rapidly. As with Elon Musk suddenly going green and Lambasting Bitcoin (thusly causing it to crash slightly) this could end up blowing up pretty soon as people look for alternatives as I have been.

**Comment by fereehu** [comment]
I have the same problem. On my Windows machine, it works, but it's not for farming/plotting, so I disabled 8444 there, this way it's not syncing correctly, but I could live with that.
I tried to add on my ubuntu machine, which connects to only the windows machine (the IP address shows 192.168.1.1), but stops syncing around 13800. Other peers cannot connect to it, only the local windows pc, but I shutdown that sometimes, so no syncing on ubuntu 20.04. 

Tried to reinstall with .deb, followed the install method using git clone, using other private keys, opened manually the port, disabling/enabling upnp, but the errors are the same:

```
2021-05-15T13:36:24.930 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0c2b1cd7a4a2ca3a02d7c1f2d238c4b49986a345f025dffce79b7416dd7393fd, exception Stack: Traceback (most recent call last):
  File "chia/server/server.py", line 373, in start_client
RuntimeError: Trying to connect to a peer ({'host': 'introducer.chia.net', 'port': 8444}) with the same peer_id: 0c2b1cd7a4a2ca3a02d7c1f2d238c4b49986a345f025dffce79b7416dd7393fd
```
The same errors happening when connecting only to IP's, and I couldn't add other peers via GUI. Even, when the peer_id somehow changes, the same error is happening. 

Buggy, very buggy.
