### ISSUE TITLE
Carrier-grade NAT (CGN or CGNAT) 8444 port opening issue for many users

### ISSUE THREAD

**Issue by salimbasar** [Chia-Network/chia-blockchain#4815]
As you know in many countries ISSs are using CGN for the ips. So we can not not open ports.Modem that i used is Airties VAW- 275. With this modem got iptv and internet. Has two connection one is for the internet and other for the iptv. so connects to 2 different ips.
Because there is a main ip starting with 100.. than we can see our normal ip.
I have tried some solutions like ngrok open vpn. but i couldnt manage.

I know that getting a static ip is the best solution. But in our country is not cheap. 

do you suggest any different solutions for this?

**Comment by Jutean** [comment]
一看就是祖国用户了，同遇到了，老板尝试了DDNS解决么？

**Comment by salimbasar** [comment]
> 看就是祖国用户了，同遇到了，老板尝试了DDNS解决么？我要了公网ip也是同步不了

Actually modem is getting dynamic ip but as main ip show allways a fix ip whic starts with100. Which is different than my ip when i check on whatismyip.com.

to open a port ı have to have main ip and and dynamic i must be same. ıt is opening but it isnot working. it shows allways closed

**Comment by salimbasar** [comment]
ın my tests of tcp port check i got these results.

PORT   8444/tcp
STATE     filtered
SERVICE  pcsync-http
nch i see that only one full node is downloading and may wallet port is uploading.. 
filtered means closed i think. During the synch sometimes i see other peers 0.1, 0.2maximum

**Comment by HitLuca** [comment]
I would also like a way to overcome this. For now I am trying to use a vpn with port forwarding enabled, and I'm trying to find a way to run the node on a different port

**Comment by salimbasar** [comment]
> I would also like a way to overcome this. For now I am trying to use a vpn with port forwarding enabled, and I'm trying to find a way to run the node on a different port

did you make it work with port forward vpn?

**Comment by HitLuca** [comment]
Looks like,  so my vpn offers me port forwarding on port 22300, I edited `config.yaml` in `.chia/mainnet/config` and replaced all the `port`  field of `full_node_peer` from `8444` to `22300`. This makes sure that wallet, farmer etc. can all connect to your node. I also changed the `port` field in the `full_node` section in the same way, and this is the port you will run the node at. 
After running it the entire night it seems that it all works

**Comment by salimbasar** [comment]
Which VpN you are using?

is it possible to share a photo of peer connections to see port connections?
are they in format

8444/22300 or 22300/8444
?
thanks

**Comment by HitLuca** [comment]
I'm using Private Internet Access, peer connections are all in the form 8444/8444. I am fairly sure this setup works, because [](https://canyouseeme.org/) sees my service running on port 22300

**Comment by salimbasar** [comment]
ı got a vpn and that gave me 61528 as port.

and ı have changed this lines at config file.

line 13
line 211
line 251

and for the full node
line 117

after saving. i have closed chia client and restarted.
now  i cannot see farmer and wallet connections. did ı made wrong changes?
![resim](https://user-images.githubusercontent.com/25376052/118263642-396b0400-b4bf-11eb-8445-0b573c5fe766.png)

**Comment by HitLuca** [comment]
ok you messed up the last piece, you updated the `farmer_peer` entry, but you should change the `port` value, like this
```python
full_node:
  database_path: ...
  enable_upnp: ...
  farmer_peer:
    ...
  introducer_peer:
    ...
  ...
  ...
  port: 22300
```

**Comment by mikeyriver2** [comment]
> ok you messed up the last piece, you updated the `farmer_peer` entry, but you should change the `port` value, like this
> 
> ```yaml
> full_node:
>   database_path: ...
>   enable_upnp: ...
>   farmer_peer:
>     host: localhost
>     port: 8447
>   introducer_peer:
>     ...
>   ...
>   ...
>   port: 61528
> ```

hi, are you able to get more peers by doing this? does this solve syncing for you? I am able to somewhat tunnel my nodes using my VPN but I am still unable to properly connect to peers.

**Comment by HitLuca** [comment]
When I restart my chia client I usually add the ips that are on [this website](https://chia.keva.app/) just to kickstart everything, plus  I add `introducer-eu.chia.net`. After that I am able to run all day without any manual intervention

**Comment by HitLuca** [comment]
No worries, I usually sit at 10-15 peers, but there's some variance to that
