### ISSUE TITLE
Wallet not syncing after force reconnect by ISP[BUG]

### ISSUE THREAD

**Issue by SamuG1** [Chia-Network/chia-blockchain#4818]
The Wallet loses all connections and does not reconnect to peers after the 24h reconnect from ISP / router. Adding peers manualy also doesn't work. Only restarting the Wallet works but that also stops all running Plots.

**To Reproduce**
I havent tested this but it should work. I only saw that the time my wallet stops syncing is the same time my router does the daily reconnect. I would test it but I'm running two plotts at the moment.
1. Run the wallet and let is sync
2. make the router reconnect to internet
3. Wallet stops syncing and does not connect to any peers anymore

**Expected behavior**
The Wallet should reconnects to peers and start syncing again.

**Desktop (please complete the following information):**

- OS: Windows 10
- Wallet version 1.1.5
- also observed this behavior in older versions

**Comment by gyarros** [comment]
Me too

**Comment by gyarros** [comment]
Wallet versión 1.1.5
Ubuntu 20.04
Internet connection perfect

**Comment by JoJ123** [comment]
Check this:
https://github.com/Chia-Network/chia-blockchain/issues/4836

**Comment by paulshark30** [comment]
остановить командой и запустить заново start node

**Comment by N00bl0rd999** [comment]
I have the exact same problem.
After rebooting, restarting Chia and waiting for a looooong time (more than 1h), it might probably sync again - but not always.

Win 10, port is open, internet is great.

**Comment by N00bl0rd999** [comment]
> 
> 
> Check this:
> #4836

Or maybe don't check this, because it does not help at all.

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
