### ISSUE TITLE
Connection error Raspberry PI 4

### ISSUE THREAD

**Issue by Tefor** [Chia-Network/chia-blockchain#4824]
Hi guys, I cant sort out this connection problem. My setup is a Raspberry pi 4 8GB RAM as my farming/harvester (UBUNTU Server OS) and my main PC (WINDOWS 10) which is full node, plotting and farming.

I've already done this [Farming on many machines · Chia-Network/chia-blockchain Wiki · GitHub] https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines

When run `chia start harvester` on the Raspberry it seems like everything is ok, in main PC shows Last attempted proof 0/54 (my plots connected on the Raspberry), but if run `chia farm summary` on the RasPI, I get this

![asasas](https://user-images.githubusercontent.com/26451058/118155970-2f79d000-b3ef-11eb-82f0-b4ab37b60b7e.png)

Ports are open on the main PC and upnp is false on RasPI, I don't know if am I forgetting sth.

Btw, thanks

**Comment by sargonas** [comment]
So real quick to clarify based on the above:

You have a farmer running on *both* the windows 10 pc with the full node AND on the pi... with a harvester on each of those devices as well? Are each of those harvesters talking to their respective farmer on the same device, and both devices talking to the windows 10 node? or... at least... is that the *intended* way they should be working?

Let me know and we can try to poke at some stuff from there, but I will lead off with if that IS the case, is there a particular reason you chose to not have the pi harvester use the win10 farmer as it's authoritative farmer? having less farmers in the mix might help reduce room for issues, for a start, if so.

**Comment by Zeesy** [comment]
I'm experiencing similar issues, and believe it's because I haven't figured out how to run the pi off the win10 full node. Chia harvester is running. Here's some results:
```
chia show -a host:port
failed to connect to host:port
```

```
chia farm summary
Connection error. Check if wallet is running at 9256
Connection error. Check if wallet is running at 8559
```

```
chia wallet show
Connection error. Check if wallet is running at 9256
```

**Comment by Tefor** [comment]
> I'm experiencing similar issues, and believe it's because I haven't figured out how to run the pi off the win10 full node. Chia harvester is running. Here's some results:
> 
> ```
> chia show -a host:port
> failed to connect to host:port
> ```
> 
> ```
> chia farm summary
> Connection error. Check if wallet is running at 9256
> Connection error. Check if wallet is running at 8559
> ```
> 
> ```
> chia wallet show
> Connection error. Check if wallet is running at 9256
> ```
> 
> I set my pi up using [this tutorial](https://medium.com/geekculture/how-to-use-your-raspberry-pi-as-a-chia-harvester-66440c17d318).

I think that I was confused.. If u just want to use the PI as a harvester and check that everything is working, you should open config.yaml and write INFO in log_level

e.g:
 ` logging: &id001
    log_filename: log/debug.log
    log_level: INFO
    log_stdout: false`

Then copy this on the Terminal to check if is working `cat  ~/.chia/mainnet/log/debug.log`

The output should be like this `2021-05-22T21:54:02.898 harvester chia.harvester.harvester: INFO [number] plots were eligible for farming [key]` Time: 0.23380 s. Total x plots`

From what I know `chia show -a` or `chia farm summary ` is used if you have your PI configured as Full Node, Wallet or Farmer.
