### ISSUE TITLE
[BUG]I hope I am wrong but it seams like this a chaep fake way to block others with growing farming cappasity...

### ISSUE THREAD

**Issue by Yabankazi** [Chia-Network/chia-blockchain#4836]
Hi, I have a peering problem, Ports and Firewall are for 8444 open. I can synchronize after starting Chia GUİ in about 3-10 min. I have sometimes like 5-7 peers. Start-full_note.exe works fine. But after 1-2 hours happens something that I don't understand. My Peers are not getting more.

So used the CurrPorts free software ( recommendation for every farmer) to see what happens behind the dors and Ports.

I saw that one Remote Address IP is blocking the work of start_full_node. exe

The node is in an endless loop, the Lokalports are changing by every try but Remote Adress (IP= Peer) does not change. This is blocking the GUİ to get in connection with other following Peer s.

Could you give me an idea of how to fix this Issue... Is this on your farming the same?....

I think this is an unknown problem for Chia farmers. Could you check and give us how your farming is peering.

I have a shot of my CurrPorts tool the green line is the Problamatik Ip which blocks the check of another peer IP s.

**Comment by Yabankazi** [comment]
I think I found a big weakness of the Chia peering. Because the ıp which was blocking the peering with others, Is a Chinese IP. My friend has checked he s blocking IP to and it was a Chinese IP to.

I don't know how many of you are blocked by peering with these problematic IP s.

I am not sure but this could be a way to block other Chia Farmer to have more Luck to get an XCH...

Please check your connection with free software CurrPorts ... and if a Remote Address does not change. Copy the IP and follow the owner.

I hope I am wrong but it seems like this a cheap fake way to block others with growing farming capacity...

Notis the IP s ... We can use this as proof ... and can send this to the Chia team.

**Comment by JoJ123** [comment]
I have the same since yesterday evening.
The blocked IPs are also from China. Can you share the IP?

**Comment by Yabankazi** [comment]
I think we shouldn't share these IP s , because we don t know if this bug used by others as known or is it a system issue.
Just make a notice. I have already sent an E mail to Chia team. If they want proof we can give them the IP.
Can you imagine how many Farmer you can block this way. You can only manage that the IP s from Europe or the US or somewhere else has to bound in this endless loop.

**Comment by paulshark30** [comment]
в  программного обеспечения CurrPorts можно убить повторяющийся SYN-SET и запустить start node повторно

**Comment by padik11** [comment]
Можете выложить скриншот, как это сделать?

**Comment by paulshark30** [comment]
> Можете выложить скриншот, как это сделать?
 
скачай прогу CurrPorts, на цикличном ip правой кнопкой убить процесс,! Синхронизация слетит, после смд командой start node запуск узла , что тут скринить ))) мне помогает ! плотинг не слетает

**Comment by paulshark30** [comment]
вопрос как это исправить? Надеюсь разработчики оборотят внимание  на данную проблему, так как в любом случае после определенного количества подключения попадается опять же цикличный ip

**Comment by padik11** [comment]
Спасибо

**Comment by padik11** [comment]
К сожалению, это не помогло. Вы знаете другую причину?

**Comment by JoJ123** [comment]
@Yabankazi @paulshark30 
Do you have the same stuff in your debug.log:
I have tons of entries like that. My network keeps ongoing with the sync but it's always behind and never farmin.

```
2021-05-14T05:19:06.622 full_node full_node_server        : WARNING  Banning 120.XX.XX.44 for 10 seconds
2021-05-14T05:20:11.212 full_node full_node_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '180.XXX.XXX.218', 'port': 8444}. Traceback (most recent call last):
  File "/chia-blockchain/chia/server/server.py", line 521, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=600)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

2021-05-14T05:20:11.214 full_node full_node_server        : WARNING  Banning 180.XXX.XXX.218 for 10 seconds
2021-05-14T05:20:11.784 full_node full_node_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '223.XXX.XXX.114', 'port': 8444}. Traceback (most recent call last):
  File "/chia-blockchain/chia/server/server.py", line 521, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=600)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

2021-05-14T05:20:11.787 full_node full_node_server        : WARNING  Banning 223.XX.XX.114 for 10 seconds
2021-05-14T05:21:01.379 full_node full_node_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '116.XXX.XXX.27', 'port': 8444}. Traceback (most recent call last):
  File "/chia-blockchain/chia/server/server.py", line 521, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=600)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

**Comment by Yabankazi** [comment]
My problem is if the GUİ checking to connect with other peers. Some of the Remote IP is keepes my system in an endless loop. It is not connecting with me as a peer and it doesn't disappear from the port. I hope I could explain it. 
I found a name for it " Infinity Loop" check it.
