### ISSUE TITLE
[BUG] Plot page doesn't have a scrollbar - Dark mode issue

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#484]
**Describe the bug**
When you kick off a k=32 in the GUI Plot tab, there is no scrollbar to move down to the Progress window. Also, if you are in dark mode, the progress menu font is white on white.

**To Reproduce**
Plot a k=32 in MacOS

**Expected behavior**
There should be a scroll bar on the right - especially once you kick off a plot.

The plotting output font color should be dar/contrasting in night mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/30377676/96688782-68a90080-1336-11eb-973a-cd6d8a63a45f.png)
![image](https://user-images.githubusercontent.com/30377676/96688821-7199d200-1336-11eb-89fa-e5d3bf586a18.png)

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: 10.16.7
- CPU: Intel

**Additional context**

**Comment by seeden** [comment]
I created a pull request for this issue https://github.com/Chia-Network/chia-blockchain/tree/issue-484

**Comment by hoffmang9** [comment]
Re-opening until released

**Comment by hoffmang9** [comment]
Now closing with the release of https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta17
