### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by ukdomainers** [Chia-Network/chia-blockchain#4846]
ive followed the instructions but it still says in the about chia blackchain 0.0
am using centos stream 8 
![Screenshot from 2021-05-13 20-33-27](https://user-images.githubusercontent.com/79455669/118177250-55709600-b42a-11eb-8cfa-9ca036d21411.png)
thanks in advance anyone can help

**Comment by sargonas** [comment]
This is a known issue resulting from certain linux install paths (I believe namely if you install from source via git or if you use the "experimental" GUI installer) You can check your version on the CLI in the interim until it is addressed, using the command `chia version`.

**Comment by ukdomainers** [comment]
1.1.5 thanks for your reply
