### ISSUE TITLE
[BUG] Stuck on “Connecting to Wallet”

### ISSUE THREAD

**Issue by gusosborne** [Chia-Network/chia-blockchain#4861]
Stuck on “Connecting to Wallet”. 
GUI for Blockchain version 1.1.5

windows 10 Pro
2x quad core Xeons, 16GB RAM. 

have uninstalled/ reinstalled with same results. Was @36 plots with 14 more queued up when this happened. Believe a windows update auto-rebooted the machine during plotting. 
![B0FBFAFA-5BCE-4BF0-BF25-7709E8914297](https://user-images.githubusercontent.com/25893043/118191656-86d96980-b40a-11eb-8e01-fcfb4e5da6be.jpeg)

Please let me know what other information I can provide.

**Comment by Snuups** [comment]
I have the same problem. I View/Reload and then Chia is dead.

I have no solution apart reinstalling the whole thing. What I won't do.

**Comment by gusosborne** [comment]
Yes, Id rather not lose weeks of plotting if at all possible. At some point I suppose it's a wash though..

**Comment by Froliskop** [comment]
i have same problem

**Comment by deniz3446** [comment]
aynı sorun bende de var çözüm lütfen

**Comment by MossP** [comment]
@gusosborne I assume that your plots are stored safely and you have copied down your mnemonics for your wallet? If so, reinstalling won't lose your plots (other than any currently plotting when you terminate tasks). It will however lose the blockchain history that has downloaded to your machine so will take a while to redownload again, but you can continue plotting whilst this is happening.

Stop Chia (Kill Task)

Delete these folders:
C:\Users\!yourusername!\.chia
C:\Users\!yourusername!\AppData\Local\chia-blockchain
C:\Users\!yourusername!\AppData\Roaming\Chia Blockchain

Reinstall Chia. It should now work.

**Comment by deslumoprime** [comment]
This will happen sometimes. If you want to avoid the issue, switch to Linux. My experience with Linux has been ten-fold better than the Windows experience. If you'd still like to stick to Windows, then this is a very common and known issue that occurs when you use the GUI. Just restart the bloody thing. Or switch to Linux, as that seems to be the solution for everything these days.

**Comment by gusosborne** [comment]
Thanks for the help(s)! I believe I will just go ahead and switch to Linux now, rather than continuing to fight with 'doze.

**Comment by cezse** [comment]
> aynı sorun bende de var çözüm lütfen

Dostum problemi çözebildin mi
