### ISSUE TITLE
[BUG] full node goes out of sync

### ISSUE THREAD

**Issue by shobukle** [Chia-Network/chia-blockchain#4866]
**Describe the bug**
- OS: Debian Linux, 64-bit
- CLI only

Full node seems to randomly stop working.  Getting a `farm summary` results in `Exception from 'full node'`.

The wait time when I try any command is horrendous, presumably because it's timing out. When I monitor the system, CPU usage is low and memory usage is normal.

Stopping via `stop farmer` leaves the daemon running (expected) and also several full_node processes (unexpected).

Right now, it's supposedly syncing but the current block is not going up.

**To Reproduce**

1. Start the Chia farmer (full node, harvester, farmer, wallet)
`chia start farmer`
2. Wait

**Expected behavior**
The full node stays connected to the network.

**Actual behavior**
The node loses sync (disconnects, falls behind, etc.), causing farming to stop.

**Additional context**

**Comment by bandit8623** [comment]
do you have port 8444 open to your farming machine?

**Comment by baizuchong-net** [comment]
必须要 8444开放，且同一内网只能有一个！

**Comment by shakeme** [comment]
Something similar here. The number of connected full nodes is going down slowly. Currently only 9 connected full nodes. I usually had 50.

**Comment by stipus** [comment]
Can you tell me if your chia database ( .chia/mainnet/db directory) is on a spinning drive ?
If so, can you check the MB reads/s and MB writes/s on the same disk during slowness / ressync issue...
Using glances, you can filter on "chia_full_node" and get the MB/s read and written by the chia_ful_node process to the database.

**Comment by shakeme** [comment]
For me the db is located on a sata ssd with very low usage. If needed i can add some fio logs.

**Comment by stipus** [comment]
I don't think there can be any problem if the database is on a SSD. There might be a problem on a spinning disk because of the large number of small reads.

**Comment by tibbon** [comment]
I'm having a similar problem in Windows. I get disconnected from other nodes. It had been working, but as of sometime yesterday/today it's gotten flakey. I've manually added nodes and introducers but they go away quickly. 

All drives are SSD/NVMe's except the final transfer drives, so that's not an issue. Lots of errors in my logs :(

**Comment by DartCoder** [comment]
> I'm having a similar problem in Windows. I get disconnected from other nodes. It had been working, but as of sometime yesterday/today it's gotten flakey. I've manually added nodes and introducers but they go away quickly.
> 
> All drives are SSD/NVMe's except the final transfer drives, so that's not an issue. Lots of errors in my logs :(

same porblem

**Comment by simondarrens** [comment]
adding manually did work but nothing works at this point.  no sync in days.
