### ISSUE TITLE
i lost 1 xch ,when making a transaction.

### ISSUE THREAD

**Issue by alexander9019** [Chia-Network/chia-blockchain#4871]
i lost 1 xch ,when making a transaction. I wanted to pass a coin to another wallet and the system discounted two coins instead of one, someone knows who
can you help me?

**Comment by ck15921579280** [comment]
is there any err info in the log?

**Comment by lvcivs** [comment]
You may have accidentally added 1 XCH as a fee.

**Comment by mariano54** [comment]
Can you provide more details about the transaction? And send me screenshots to my keybase account sorgente711.
Also try deleting your wallet DB, sometimes there are stuck pending transactions

**Comment by giang21199z** [comment]
> Can you provide more details about the transaction? And send me screenshots to my keybase account sorgente711.
> Also try deleting your wallet DB, sometimes there are stuck pending transactions

Hi @mariano54 
I faced to in this case. My transaction very slow. I sent 1XCH into MXC market but I didn't receive it.
I checked my transaction via CLI chia wallet get_transactions. It's pending.
Could you help me explain why is so slow :(.
Addition,  I made transaction fee is 0.001.
Look forward to your response.
Thank you so much.

**Comment by alexander9019** [comment]
> You may have accidentally added 1 XCH as a fee.

Yes, that is exactly what happened, it really is something that can happen a lot for which the system in the wallet part is not very clear, it only indicates the amount that is understood as # of coins and the rate that one would think. is the value you want to transfer

now the question is reversible or did I just lose my money?

**Comment by giang21199z** [comment]
> > You may have accidentally added 1 XCH as a fee.
> 
> Yes, that is exactly what happened, it really is something that can happen a lot for which the system in the wallet part is not very clear, it only indicates the amount that is understood as # of coins and the rate that one would think. is the value you want to transfer
> 
> now the question is reversible or did I just lose my money?

Unlucky. How about when I used transaction fees is 0.001.
I also sent 1XCH to other wallet. But I check on my GUI I have zero available XCH. :(
![image](https://user-images.githubusercontent.com/11538834/118345471-da5ccc00-b55e-11eb-8283-bdc1e1cb95fc.png)

**Comment by blathor** [comment]
The same thing just happened to me, when I put fee 0 it did not respond, and by mistake I put 1 fee, what does not expect me is that it is 1 delivery chia. I wanted to send to test send 0.05 chia and expense of 1 chia.
is there any way to recover?

**Comment by giang21199z** [comment]
> The same thing just happened to me, when I put fee 0 it did not respond, and by mistake I put 1 fee, what does not expect me is that it is 1 delivery chia. I wanted to send to test send 0.05 chia and expense of 1 chia.
> is there any way to recover?

We can't recover. My transaction is successed. 
https://www.chiaexplorer.com/blockchain/search help full very much for me.
I think you can check your wallet or transaction at this.

**Comment by mariano54** [comment]
There's nothing we can do about that. If you set the fee to 1 XCH, that has been paid out to the farmer.
If you experience stuck funds (or stuck pending transaction or an incorrect balance) try following the steps on the wiki:

https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-do-i-have-a-negative-balance-why-is-my-pending-transaction-not-confirming

Sorry about that
