### ISSUE TITLE
[BUG]I found an error in the log, but it is in 100% plotting state at present

### ISSUE THREAD

**Issue by lianjy357** [Chia-Network/chia-blockchain#4879]
I found an error in the log, but it is in 100% plotting state at present
What can I do to restart? Or delete the error file
The error log is as follows
![image](https://user-images.githubusercontent.com/38170938/118206642-82a65e00-b495-11eb-845d-0508eeb8f063.png)

**Comment by lianjy357** [comment]
only read 0 of 262143 bytes at offset 138149361 from "xxxxx" with length 604068444. error 1. retrying in five minutes

**Comment by deslumoprime** [comment]
What version are you using? I believe there was a version that had a buggy progress bar and would get to 100% WAY too early. Also, that error might be because you're out of space, I don't pay much attention to the errors because I haven't dealt with one in a long time. Check your temp drives and final drives. Do they have enough capacity? Are they filled to the brim? Hope this helps.

**Comment by Plopsi** [comment]
read 0 could also be a lost network mount. if possible try to remount that share - chia will wait for another 5min, and another, and... ;D

**Comment by JariNestel** [comment]
Same error here:
`Only read 121324 of 125370 bytes at offset 603432468 from "D:\\Chia\\plot-k32-2021-06-11-08-22-bb1c3d18b097fd18518c3af5444e8649364fd544888df8167ecd86aab777fa10.plot.p1.t6.sort_bucket_019.tmp" with length 603557838. Error 0. Retrying in five minutes.`
The file size is 603.553.792 = 603.432.468 + 121.324 meaning it reads until the file end expecting more.
Installed Version: 1.1.7
OS: Windows 10
Also, it took me way longer than usual to get to 100% more than a week.

**Comment by JariNestel** [comment]
Still happens in 1.2.0: 
`Could not open D:\Chia_temp\plot-k34-2021-08-18-22-26-e17ed948b80987a4801a2614007552365118c0267c5ed97b7a75299a25a9c36b.plot.p1.t6.sort_bucket_110.tmp: No such file or directory. Retrying in five minutes.
Only wrote 1688 of 1048572 bytes at offset 1516235112 to "D:\\Chia_temp\\plot-k34-2021-08-18-22-26-e17ed948b80987a4801a2614007552365118c0267c5ed97b7a75299a25a9c36b.plot.p1.t6.sort_bucket_081.tmp" with length 1516236800. Error 1. Retrying in five minutes.
Only wrote 854 of 340872 bytes at offset 53031746730 to "D:\\Chia_temp\\plot-k34-2021-08-18-22-26-e17ed948b80987a4801a2614007552365118c0267c5ed97b7a75299a25a9c36b.plot.table5.tmp" with length 53031747584. Error 1. Retrying in five minutes.`
The disk was magically unmounted too, had to reconnect it physically.
