### ISSUE TITLE
[BUG] Using CLI mode PROBELM

### ISSUE THREAD

**Issue by HectorChow** [Chia-Network/chia-blockchain#4897]
If I create sevral powershell tasks to  plotting at the same time , sometimes one of theses tasks will be paused by itself until I check 
 it and type enter in  the task window again . It has happened sevral times.

**Comment by HectorChow** [comment]
the pause time span is about hours.

**Comment by Plopsi** [comment]
how many? what settings? HW specs? Maybe you just overload your system?
