### ISSUE TITLE
[BUG] Remover plotting will kill all plot is creating!

### ISSUE THREAD

**Issue by vanthoi** [Chia-Network/chia-blockchain#4898]
**Describe the bug**
If I need to delete a plot that is creating. Due to this plot can cause my temporary drive to be full. I decided to delete it before the temporary drive got full. When I hit delete it killed all my other creating plots. Then the gui started showing connecting the wallet. For previous version 1.1.4 I didn't get this error. 

**To Reproduce**

1. Go to '... action (plot is creating)'
2. Click on 'delete'
3. See error

**Expected behavior**
I want when deleting a plot is being created. Just kill that process. and delete the temporary files of that process.

**Screenshots**
no need

**Desktop (please complete the following information):**

- OS: Windows 10 pro
- OS Version/Flavor: 20H2
- CPU: AMD Ryzen 9 5950X
- RAM: 64GB

**Comment by RadioactiveDeuterium** [comment]
Same issue here, happens every time. Only way to stop a plot is to kill the entire software which stops all plots.

System:
Windows 10 pro
20H2
Ryzen 9 3900X
32GB Ram

**Comment by Pafolo** [comment]
Same exact issue for me. It locks up the GUI then kicks out to a connecting to wallet page and stops all plotting. It cancelled 3 other plots at 40% because of the bug kicking me out of the gui.
