### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KryptonCoin** [Chia-Network/chia-blockchain#4901]
Upon plotting on my main plotter / farmer PC which runs a 10900k and two network drives for storage the Chia software my only plotting one plot crashed the window system Explorer. EXE and rpc. EXE. This caused my plot from my other plotter to fail when trying to upload 7 100% complete files to the network drives Gus hanging the rest of my plots that were in the second computer plotting as well as store in corrupted temp files on my network drive. Thus corrupting the network drive which led me to having to completely format 18 TB drive with 10 GB with a Plus on it as well as deleting all of the completed plots on the second PC as well as those that were in the middle of plotting. There's no point trying to restart cheat on the second PC it gave me error 13 my config. Yaml file path directory was corrupted. Not allowed meme I reload the Chia software without completely uninstalling it and resetting it up. On top of that there was no possible way for me to redirect the files that were hung trying to find the network path to another location which seems pretty idiotic coming from software Engineers to not give the ability to redirect a file. So needless to say my damn near 20 terabytes of plots that I had I'm down to about six terabytes now. The poor engineering on this software has led to unneeded useless waste of nvme drives because they had no way to redirect a simple file in their software. Or that I had now have two dead nvme drives with no plots a corrupted software and me having to rebuild my entire farm.  Not sure why in this day and age software Engineers do not think ahead but only think as far as the end of their nose.

Pc-1 running Windows 10 Pro I9 10900k 32GB of RAM 2tb nvme with 218 TB external hard drive Network map
PC number two running Windows 10 Pro AMD ryzen 5 3600 with two 2tb nvme

Redirecting a file because either a corrupted failed or full hard drive should have been your first thought when creating the software not having the ability to do that from the gooey or Powershell seems to leave a lot of people at risk for losing their plots wasting hard drives wasting electricity and wasting their time. I highly suggest you start fixing this before you upset too many other people with the crappy design of your software.
![20210513_194431](https://user-images.githubusercontent.com/84167311/118219856-30325680-b42f-11eb-817d-a274feacd88a.jpg)
![20210513_175830](https://user-images.githubusercontent.com/84167311/118219908-48a27100-b42f-11eb-8840-20b955af07d6.jpg)

**Comment by cuichangan** [comment]
![image](https://user-images.githubusercontent.com/13313633/118221822-f144e500-b4b0-11eb-80ca-701a26664cfe.png)
![image](https://user-images.githubusercontent.com/13313633/118221835-f73ac600-b4b0-11eb-9ff5-6c50133bda9f.png)
![image](https://user-images.githubusercontent.com/13313633/118221848-fc981080-b4b0-11eb-89b2-2cb07728ea27.png)
![image](https://user-images.githubusercontent.com/13313633/118221863-01f55b00-b4b1-11eb-9080-641edcc1e4aa.png)
是不是的就是报这种异常 
顺带附上 钱包log 跟windows 应用事件错误

**Comment by Plopsi** [comment]
@KryptonCoin As far as I can read from that textwall is that one PC which plotted crashed. And, why ever, you formatted all other PCs, too. Question here: why?

Chia plotter uses a simple copy command from OS to copy plots from A to B. If B is not available or out of memory it waits 5min and tries again, it does this until the OS returns a finish.

Myself experience connectionlosts to the Network drives before or even while copying - especially the laptop I normally let plot one or two plots overnight. As it's only connected via WiFi it sometimes shortly loosing connections and disconnectets the drive.
On the next morning I just reconnect the drive and chia continues/restart copying as normal - after max 5min as mentioned in the message.
