### ISSUE TITLE
我SOLO爆块了，但是XCH币已经一天了还没到账

### ISSUE THREAD

**Issue by 13430662839** [Chia-Network/chia-blockchain#4903]
我在高度272765挖到了两个XCH，
奖励地址填写为xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2
但是现在已经一天了，怎么奖励还没到账呢？

**Comment by Plopsi** [comment]
https://www.chiaexplorer.com/blockchain/address/xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2 looks good for me (approved on 272.768), check if your wallet is sync (not only full_node but also your wallet)

![grafik](https://user-images.githubusercontent.com/17942998/118226383-2f2d1380-b487-11eb-929d-e554c40ef826.png)

or `chia wallet show `
