### ISSUE TITLE
[BUG] "chia farm challenges" formatting error

### ISSUE THREAD

**Issue by kekropp** [Chia-Network/chia-blockchain#4922]
There is a missing space in the `chia farm challenges` output

**To Reproduce**
Type:
`chia farm challenges`

**Expected behavior**
A space between the hash and the word "Index"

**Screenshots**
[Screenshot](https://imgur.com/br5QXY9)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04 LTS
- CPU: AMD Ryzen 3 3100

**Comment by sargonas** [comment]
I took a dive in to fix this and realized it already has! :) Looks like this was fixed 2 days ago in PR #4038 and will presumably go out in the next release.
