### ISSUE TITLE
[BUG]What's the situation

### ISSUE THREAD

**Issue by mfgcs** [Chia-Network/chia-blockchain#4923]
![image](https://user-images.githubusercontent.com/62247746/118231629-f8c0ba00-b4c1-11eb-8af8-af3f5d440be0.png)

**Comment by Plopsi** [comment]
I don't think you have multple harvesters? In that case every harvester would report in one line at the 2nd red square.

Also be aware that there seems currently a UI bug that does not update the number in the upper right square properly until you chang the tab (to full node and back for example) or refresh the plotting directires under plots.

If nothing of the upper things fit there could also be a connectionproblem, as long as the files are on a different network device like a NAS, which can be hard to track down, so first check for the first two possiblities.
