### ISSUE TITLE
Not receiving XCH rewards

### ISSUE THREAD

**Issue by limsinsiong** [Chia-Network/chia-blockchain#4924]
Hello, I would like to report an issue with the reward system. In my wallet history, I saw that I have 0.75 XCH coin incoming but it is sent to another wallet address. Can I know where it is sent to as i cant seem to find it in my balance?

I have yet to receive my rewards and it has been a few days.

Would like to receive a reply as soon as possible regarding this issue.

I have attached files relevant to this issue below, please advice accordingly.

![644F14DB-AB3D-4D1F-9811-1B0BA2E7D564](https://user-images.githubusercontent.com/84131655/118231405-aed7d400-b4c1-11eb-8301-0ff540cf5bf4.jpeg)
![D22A664F-B1B4-48AE-AE0A-A2BAC4AD7CE7](https://user-images.githubusercontent.com/84131655/118231416-b26b5b00-b4c1-11eb-82ce-544049ea76a4.jpeg)

![FC4EF0C3-72C5-456F-9450-BBF8CF662D55](https://user-images.githubusercontent.com/84131655/118231422-b39c8800-b4c1-11eb-9915-19064ca7baab.jpeg

**Comment by IEthMiner** [comment]
I'm also having a similar issue, on the chia explorer it shows I have a small amount of Chia in my wallet, 

I do not see this in my Chia Node wallet

**Comment by 13430662839** [comment]
我也是，在Chia Explorer中可以看到有奖励记录，是转到抹茶的钱包的，挖到矿的区块高度是是272765，但是一天多了，我抹茶钱包还没提示到账

**Comment by Plopsi** [comment]
which wallet address it was send to? have you checked it with chiaexplorer.com? If you know the source address, with some effort you can follow the coin and it's parents directly. The informations in the screenshots are not useful. It's not even visible whether the wallet is synced or not on the last screen as it's cut off on the left.

**Comment by IEthMiner** [comment]
I've just noticed my wallet still shows "Syncing" under the wallet tab of my node 

On searching I've come across this - https://github.com/Chia-Network/chia-blockchain/issues/4348

So appears there's quite a few people be affected by this at the moment 

To confirm on chia explorer my wallet **does** show balance but currently **not** showing within my chia node

**Comment by Plopsi** [comment]
Is your fullnode sync?

**Comment by 13430662839** [comment]
寄到的钱包地址是&nbsp;&nbsp;xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2&nbsp; ，这个地址是交易所的钱包地址，交易所地址是： https://www.mxc.la/


我有在chiaexplorer查到他发了奖励了，就是没有收到。因为这个钱包是属于交易所的，所以我不清楚是否有同步。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
which wallet address it was send to? have you checked it with chiaexplorer.com? If you know the source address, with some effort you can follow the coin and it's parents directly. The informations in the screenshots are not useful. It's not even visible whether the wallet is synced or not on the last screen as it's cut off on the left.

**Comment by 13430662839** [comment]
是的，已经同步了。现在我的钱包都还在耕种着




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
Is your fullnode sync?

**Comment by Plopsi** [comment]
@13430662839 ok then check that the wallet is sync. if not check the logs, there are posiblities that the wallet/db got stuck on itself. If you have time you *could* to shutdown chia and delete that folde (wallet(**!**)\db) and restart chia - the wallet will resync from your full_node, but still takes a while.

**Comment by 13430662839** [comment]
还有一个问题，我用的是集群模式，在收割机上收割到的BLOCK是否会在主机钱包上显示呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
@13430662839 ok then check that the wallet is sync. if not check the logs, there are posiblities that the wallet/db got stuck on itself. If you have time you could to shutdown chia and delete that folde (wallet(!)\db) and restart chia - the wallet will resync from your full_node, but still takes a while.

**Comment by Plopsi** [comment]
@13430662839 as long as the plots were created with the public farmer and pool key of the wallet yes.

----
PS: you could at least try to write in english :D

**Comment by 13430662839** [comment]
My English is very poor.


I have reinstalled the program, but there is still nothing in the wallet.


The wallet I used was bound to the following mine pool address:


0xb4dde7c3db6ccb760d6319877f2d3bfb673acf574fb15a37b57cb7db959851dee25c741b7050cd826e9504e196a88c3d


Block height: 272765;


Sent to the address of the wallet is: xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2, this address is belong to the following network: https://www.mxc.la/






Now more than a day later, the XCH has not been sent to the Trading Network account, and the Chia wallet shows no mining proceeds.






So I'm wondering, what's the problem?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
@13430662839 as long as the plots were created with the public farmer and pool key of the wallet yes.
 
 
PS: you could at least try to write in english :D

**Comment by Plopsi** [comment]
Ok again:

1. is you node sync? 
![grafik](https://user-images.githubusercontent.com/17942998/118244624-09603880-b4a0-11eb-85c2-fb695c7733a5.png)


if so:

2. is your wallet already sync?
![grafik](https://user-images.githubusercontent.com/17942998/118244661-14b36400-b4a0-11eb-8432-b38c4e81d03d.png)



if not - does it progress on syncing?

if not- check the debug log for errors. But not every little ones, repeating errors in the end of the debug.log

----
The debug log can be found under ~\.chia\mainnet\logs where ~ is your user home direct. under linux just cd ~ , same in powershell. Otherwise under windows it's C:\Users\youruser\\.chia

**Comment by 13430662839** [comment]
They're all in sync。


Can you tell me&nbsp;Where is the&nbsp; debug.log？


And the header hash of&nbsp; 272765 is&nbsp;&nbsp;0xfaf6b8063353cd72e04c6d811f8f322b59c65e43299fae9d471acce6bc65f3a9 。
It can be found directly in Chia.exe







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
Ok again:
  
is you node sync?
 
  
if so:
  
is your wallet already sync?
 
  
if not - does it progress on syncing?
 
if not- check the debug log for errors. But not every little ones, repeating errors in the end of the debug.log
 
 
The debug log can be found under ~.chia\mainnet\logs where ~ is your user home direct. under linux just cd ~ , same in powershell. Otherwise under windows it's C:\Users\youruser\.chia

**Comment by limsinsiong** [comment]
Hi Plopsi, I have just checked and my full node is synced, so is my wallet.



The address is a newly created one linked to my new PC, so there was a mistake on my part.


However, may I know roughly how long it takes for the XCH reward to be credited into the account? As shown in the picture i provided, my new PC was rewarded with 0.75 XCH on the 13th of May 2021 at 6:59PM. 


I checked the Pending balances and they are at 0XCH so I am looking for a way to find out where the reward went.


Thank you for your assistance with this issue

**Comment by Plopsi** [comment]
> 
> 
> Hi Plopsi, I have just checked and my full node is synced, so is my wallet.
> 
> The address is a newly created one linked to my new PC, so there was a mistake on my part.
> 
> However, may I know roughly how long it takes for the XCH reward to be credited into the account? As shown in the picture i provided, my new PC was rewarded with 0.75 XCH on the 13th of May 2021 at 6:59PM.
> 
> I checked the Pending balances and they are at 0XCH so I am looking for a way to find out where the reward went.
> 
> Thank you for your assistance with this issue

Yeah, I see it here:

https://www.chiaexplorer.com/blockchain/block/0xda0bde84653791bf45b8898a1a7bdf218bfa5c1f9b4394d1f6309d2dec8334dd

moved to https://www.chiaexplorer.com/blockchain/address/xch1l8del4z0zj42me6sax35n7l5wgpmc4scr06scacp4nc4j9k70ghqr7mfsk

block height was 274.240

when following the coin itself
https://www.chiaexplorer.com/blockchain/coin/0x6d0793a334bea1995f2158b62bfd2ac3535ee2f3aab6c76044005a06c4a2c32d

you see again it was confirmed on 274.240
and spent on 274.310

following the parentcoin we also see the 0.75 where cut from a pool reward (the 1.75 of 2 XCH on a win) which where rewarded to https://www.chiaexplorer.com/blockchain/address/xch1j2uvys2fr2aqt8r24a7kzztnavd6t8xa5yqxswm7qprxp9pqu7yqxcpxf9

so far to the origin of the coin.

Lets see where it traveled:

So back to https://www.chiaexplorer.com/blockchain/address/xch1l8del4z0zj42me6sax35n7l5wgpmc4scr06scacp4nc4j9k70ghqr7mfsk
We see it was spend on 274.310:
https://www.chiaexplorer.com/blockchain/block/0xdeea8a8382ed89f306263976e0c8c16e915cb4a93637371701e39bee05cc7488

There we also see the removal from the wallet. Finding the correct addiont is a click and error as coins are aggregated and chiaexplorer currently only shows und links to the parentcoin. But the coin moved via https://www.chiaexplorer.com/blockchain/block/0xdeea8a8382ed89f306263976e0c8c16e915cb4a93637371701e39bee05cc7488 to https://www.chiaexplorer.com/blockchain/address/xch1l8del4z0zj42me6sax35n7l5wgpmc4scr06scacp4nc4j9k70ghqr7mfsk on block 274.310

But that's still not the final position. Via https://www.chiaexplorer.com/blockchain/coin/0x59b53d5532ce83262e5a653e89121c9d049222e58c22683082e5dafd0ff7a3b4 it was merged with antoher 0.25 and moved to https://www.chiaexplorer.com/blockchain/address/xch1cn4jt2jg2z85m3yw9vfu3w4y9n5snc83zzykdq7hsau0lf7t7chs3cmkx6

As we see only incoming and unspent.. so your 0.75XCH are on xch1cn4jt2jg2z85m3yw9vfu3w4y9n5snc83zzykdq7hsau0lf7t7chs3cmkx6 currently.

----

PS: so far as I can tell this should be correct, as long I didn't took a wrong turn somewhere.
PPS: I think It stepped a little bit forward an backward inbetween, sry for that, lost my tabs :D

**Comment by limsinsiong** [comment]
Hi again Plopsi,



Thank you for your detailed tracking of the coins' addresses. I am able to see the 0.75XCH through the links you sent.


However, as you have mentioned, the coins are currently in another address now correct? And that is why I am unable to see any pending transactions in my Chia Blockchain.


Will the coins be transferred back to me? Or is there something I have to do to redirect the coins back?

**Comment by Plopsi** [comment]
address yes, but in chia the address is only a... let's call it "number" - all addresses from a private key should be determinable, so no matter which address it is, when it is created from the same private key your wallet should catch it up

**Comment by limsinsiong** [comment]
His Plopsi,



So basically I just need to wait for the wallet to catch on and bring the coin back?

**Comment by 13430662839** [comment]
Could you please help me to check whether my mining reward has been successfully mailed to the following address?


xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
address yes, but in chia the address is only a... let's call it "number" - all addresses from a private key should be determinable, so no matter which address it is, when it is created from the same private key your wallet should catch it up

**Comment by Plopsi** [comment]
@limsinsiong Yes, normally totally yes.

**Comment by Plopsi** [comment]
@13430662839 currently chiaexplorer hangs on my side:

![grafik](https://user-images.githubusercontent.com/17942998/118257514-03be1f00-b4af-11eb-9df8-97ef9bdd1ae7.png)


you can try to follow it yourself, check the dest-address if it is not already there.

If not start at the sender and follow the coin and transactions.

**Comment by limsinsiong** [comment]
Hi Plopsi,



I see, so the other XCH rewards I have gotten are probably in other addresses temporarily then. 



I will learn how to track it based on your tracking steps.

**Comment by 13430662839** [comment]
I don't know how to check, so I'll have to trouble you again later




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
@13430662839 currently chiaexplorer hangs on my side:
 

 
you can try to follow it yourself, check the dest-address if it is not already there.
 
If not start at the sender and follow the coin and transactions.

**Comment by Plopsi** [comment]
it's not temprarily, that is the current final address

**Comment by 13430662839** [comment]
I also want to know how to do it. I want to know if XCH will come back on its own




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
Hi Plopsi,
 
I see, so the other XCH rewards I have gotten are probably in other addresses temporarily then.
 
I will learn how to track it based on your tracking steps.

**Comment by limsinsiong** [comment]
Hi Plopsi,



May I know if this is a system error? 



As you have mentioned previously, the XCH will be credited to my wallet later on but if this continues would the system not be considered unstable?

**Comment by Plopsi** [comment]
I think there is a slight instability on local caching (the sqlite dbs), or better not instability, but how to fix faulty entries - especially when the files are not closed properly due to crash or forced app shutdowns via task-manager. But that's only my experience, and it's gone rare.

When the wallet/node starts to stop syncing even with new (manually added) peers and some heavily repeating errors/warnings in the log I normally shutdown chia and delete the wallet/db folder (and only that one).

Afterwards the node syncs usually normally and after a couple of hours - depending on systemload - also the wallet has resynced.

But that's only my experience and current strategy. The Wallet-DB-problems have significally reduced from version to version on my side. And once more, it's only the local caching/saving of the wallet - the chain itself works fine and the wallet can resync itself.

I would even say that most problems are currently I/O problems on the user system itself, as people plotting on the same machine the wallet(s) are, and overdoing it in terms of systemresources.

- my 2 mojos *laugh*

**Comment by Plopsi** [comment]
> 
> Could you please help me to check whether my mining reward has been successfully mailed to the following address? xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2

Here we go, that one was easy :D

https://www.chiaexplorer.com/blockchain/address/xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2

There is a block reward confirmed on height 272.768.

**Comment by 13430662839** [comment]
Yes, I know。


But my wallet did not receive XCH ，So I would like to know the reason why I did not receive it and whether I sent it to where







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





  
Could you please help me to check whether my mining reward has been successfully mailed to the following address? xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2
  
Here we go, that one was easy :D
 
https://www.chiaexplorer.com/blockchain/address/xch1eg3pmlvqaj4p5228kaqed6dlrhg49hc8gc9t0qayckmfug9qduvqp0gnf2
 
There is a block reward confirmed on height 272.768.

**Comment by Plopsi** [comment]
I don't know the reason :D I'm just a user like you, I can only guess ^^ If your wallet is sync with the private key for that wallet you should see it. Check that you mnemonics for that wallet are correct or the PK if you remember it, the fingerprint is a slight hint....

Are you sure you have the right wallet loaded? I know sounds a bit stupid, but who knows - everyone does mistakes and would put his hand in fire to swear everything is correct, even me *giggles* :D

All I can say the coins are definitely on that address.

**Comment by 13430662839** [comment]
I'm sure the address is correct ，You can search for "272765" and click on "farmer_reward_address" ,The page that pops up is the transaction record at this address. Coins Received is correct。
The trading record a few hours ago is more specific. The last screenshot is the one I took earlier. Except for 1.75xch and 0.25, all the trading records are correct。





But there was a hitch ，this address is not for CHIA&nbsp;&nbsp;wallet。This&nbsp; address is from&nbsp; https://www.mxc.la 。So I don't have a private key。












------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
I don't know the reason :D I'm just a user like you, I can only guess ^^ If your wallet is sync with the private key for that wallet you should see it. Check that you mnemonics for that wallet are correct or the PK if you remember it, the fingerprint is a slight hint....
 
Are you sure you have the right wallet loaded? I know sounds a bit stupid, but who knows - everyone does mistakes and would put his hand in fire to swear everything is correct, even me giggles :D
 
All I can say the coins are definitely on that address.

**Comment by Plopsi** [comment]
If you created a wallet you have a private key, also represented by the mnemonic :)

But if that address is of a trading platform you should ask there why it is not valued, in chiaexplorer you have a point of trust to show that it is there - hope you were not scammed :/

**Comment by 13430662839** [comment]
Hi&nbsp;
&nbsp; &nbsp;Do you know how to contact the CHIA customer service？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月15日(星期六) 凌晨0:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)





 
If you created a wallet you have a private key, also represented by the mnemonic :)
 
But if that address is of a trading platform you should ask there why it is not valued, in chiaexplorer you have a point of trust to show that it is there - hope you were not scammed :/

**Comment by heiseshupo** [comment]
![未到账1](https://user-images.githubusercontent.com/81500563/118387266-263b6e00-b650-11eb-891c-cee70fe55433.png)

地址为：
xch1uwhd8qhfe07sz5mjwrajcnr6wj2m4nh2nkq682963va98l8mr2gsn7kn93

xch1uwhd8qhfe07sz5mjwrajcnr6wj2m4nh2nkq682963va98l8mr2gsn7kn93

xch1cw6dl9mwhunf0cf3hlkl83wqkr40dg9dmwr53mkfduljzyh9tk3qhzpyy6

xch1xxynl05fs35y6aqaml4pa854pfzl9vv28kqrrx3jhx9v7897jnqsh5qy34

第三个第四个地址更奇特，居然还是2020年的块，杂质是啥意思。还有在区块链浏览器上公钥无法搜索到数据。

请大神，指导一下。我这个钱包至今币没到账，是1.15版本点新地址的bug？还是网络没同步（本地显示同步，8444也开了）？

还是被盗走了？本人未加入任何矿池，一直用官方软件p图，挖矿，没有用第三方软件。唯一就公网ip映射不会操作，让人远程了一次。

![DCBCBF56409D89C33B7D613D812CBC76](https://user-images.githubusercontent.com/81500563/118387298-5edb4780-b650-11eb-97c8-69231442898d.jpg)



中国大陆的百度贴吧有很多用户，都是1.1.5版本点击新地址，钱包同步没有币，历史记录提示收到币了，币到底去哪里了，不得而知。钱包地址也改不回来了，我一个私钥和助记词在两个电脑上登陆p盘，但是他们钱包地址不一样。管理收割地址是一直的，密钥也是一样的

希望项目方能补发一下
我农田奖励地址为：xch1uwhd8qhfe07sz5mjwrajcnr6wj2m4nh2nkq682963va98l8mr2gsn7kn93
钱包地址为：xch1mgj5v2yd3kegfygrllk6rc83trete28vp3wl0pggxwggkqeqmhes0w9y2h

**Comment by zhangfangchao2021** [comment]
@ 黑雪树浦  请问你的问题解决了吗 我也是大陆用户 遇到了和你相同的问题 如果您已经收到币了 希望您能分享一下经验

**Comment by 13430662839** [comment]
解决了，我的地址是直接指向交易所的，找到你的交易哈希值，找到交易链接的地址。将信息给到他们就行了。现在我都不敢把地址直接指向交易所了，还是让官方先发自己钱包会比较好



---Original---
From: ***@***.***&gt;
Date: Wed, May 19, 2021 11:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Chia-Network/chia-blockchain] Not receiving XCH rewards (#4924)




 
@ 黑雪树浦  请问你的问题解决了吗 我也是大陆用户 遇到了和你相同的问题 如果您已经收到币了 希望您能分享一下经验

**Comment by marc1968** [comment]
my wallet it show incoming 1.73999999999 and 0.000199999998 and 0.00013999999988
however, all this balance is not on my wallet balance anyone face this issue before?

![Capture](https://user-images.githubusercontent.com/27962753/121365092-efb0f480-c96a-11eb-8ba7-219f88127af2.JPG)

**Comment by REIS77-COMMITS** [comment]
Hello all,

I am having the same problem. Can anyone help me with it? I have this showing up in my wallet history: Incoming | xch16s6mvftf7w528u336rrggt8594594e7zmn3d58nz2nz6dej85yyswm86q4 | 07/10/2021 18:05:37 | Confirmed at height 552369 | 1,749999999999 but no such amount in my wallet. My full node and wallet are synced. I am using chia blockchain in two different computers with the same seed phrases. My second computer does not show that transaction in wallet history.

Thanks

**Comment by Peppins32** [comment]
Same issue for me too (i have two different income key btw but aren't those:

xch1ea9nsfsj8mmz6pna9w7557lamuglyj7yfwefc8kxyp2dvsrrwctsphpnm9
xch19eh9q2ys7yl9774surprs557rj0u8kr0hk2uv9ed4rhslh22jhdq4juewd

I have those two confirmed incoming transaction 23/07 but nothing in my wallet (no pending too). I also use two machine on different places (so different ip) BUT with same wallet, i only see those transactions with one machine but not on the second one. Of course both are synched (wallet and node). ADMIN please help!!
