### ISSUE TITLE
Server Chia Do not start to sync, last version install 1.1.5 [BUG]

### ISSUE THREAD

**Issue by Chiaderck** [Chia-Network/chia-blockchain#4929]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Plopsi** [comment]
Do you have peers? If not or to less/with to less height try to manually connect to one of this:

North Asia introducer-apne.chia.net:8444
South Asia introducer-apse.chia.net:8444
Western North America: introducer-or.chia.net:8444
Eastern North America introducer-va.chia.net:8444
Europe: introducer-eu.chia.net:8444

try to use the nearest one for your location to keep latency as low as possible.

**Comment by sllvertlger** [comment]
Just install 1.1.4 back, worked for me.
