### ISSUE TITLE
[BUG] Windows GUI stuck while cancel plotting

### ISSUE THREAD

**Issue by OscarSheng** [Chia-Network/chia-blockchain#4933]
Can not cancel plotting

**Comment by pluto2021** [comment]
Never cancel plotting in windows GUI. It is a bug that has been since day 1! You would be lucky if you can close out the GUI normally when it would kill the plotting process you want to stop. Plotting in windows GUI is like lighting up a solid rocket booster. Once it is on, it will not stop.

**Comment by OscarSheng** [comment]
So the are not going to fix it?

**Comment by Waloumi** [comment]
Don't use GUI for plotting, unreliable until fixed.
