### ISSUE TITLE
Master public key for -f

### ISSUE THREAD

**Issue by krafrijo** [Chia-Network/chia-blockchain#4941]
Hey,

i started creasting plots over the command line, and used my Master public key for -f (Farmer public key)

Now i cant´t use the plots i created for farming.

Is there any way to still use them, or are all my created plots broken?

Greetings

Jonny

**Comment by johny182** [comment]
If you farming on same machine, you don't have to use -f option. Was it Master or Farmer key? I am not really sure, but i think you have to use your Farmer public key.

For instace, my script look like this:
```
.\chia.exe plots create -k 32 -b 4300 -u 128 -r 4 -t X:\Chia -d Z:\Chia;
```
I am plooting on one machine and then farming on different one with same cert on both.
