### ISSUE TITLE
Possible issue with random access to the sqlite database on a SATA spinning hard drive

### ISSUE THREAD

**Issue by stipus** [Chia-Network/chia-blockchain#4943]
I have been investigating the latest de-synchronizations of my chia full_node, and I think I may have found a possible reason: My setup is a 500GB system hard drive with Ubuntu, 32GB RAM, 2x2TB NVME for plotting, and N x 18TB for farming. Nothing else than Ubuntu and Chia plotting/farming is installed on this computer.

I found there are sometimes too many small reads on the 500GB system hard drive. Because of this, the chia_full_node process is getting a lot of CPU IOWAIT, and after a while it may time out (exceptions are logged to debug.log), and I'm getting unsynced for a while.

Those small reads are all in the 2.3GB sqlite database located in the .chia/mainnet/db subdirectory, and are sometimes exhausting a spinning drive read capability for small chunks of data. I'm wondering if the indexes in this database are correctly optimized for the SQL queries the chia_full_node process is requesting at such a high rate...

I planned to move this database to a SSD asap to fix this problem, but you have to know you may have the same problem if your .chia/mainnet/db subdirectory is located on a standard 6Gb/s SATA 7200rpm hard drive.
NB: This used to work fine for weeks with the same setup... but the database (which was 1.4GB last week) is today at 2.3GB... This may explain why this is suddenly happening..

**Summary:**
- Random 4K reads for a standard 7200rpm drive: 500KB/s to 1MB/s
- chia_full_node process random reads from the sqlite database: sometimes up to 12MB/s

**Conclusion:**
Database should be kept on a disk with fast 4K-block random access (SSD), unless its indexes can be optimized.
If I'm right, this may explain many of the reported bugs these last few days (random unsync, difficult to resync, slow CLI, hung GUI...)

**Desktop (please complete the following information):**

- OS: [e.g. Linux]: Linux
- OS Version/Flavor: Ubuntu Server 21.04
- CPU: AMD 5900X
- RAM: 32GB
- BLOCKCHAIN: 1.1.5 (CLI only. GUI not installed).

**Comment by centrd** [comment]
I have a couple machines with 10K drives, albeit older ones, and I have noticed them struggling with the database too. It has not caused sync issues yet.

As a workaround, you may be able to enable RAM/SSD caching for the database. This may not be as simple as moving it to faster storage.

(I know that this is not something the devs want to do, but it would be really nice if the db was engine agnostic, or at least an option was provided to run on a user provided mariadb/postgres/... instance. If it has to be very tightly coupled to sqlite, then oh well.)

**Comment by stipus** [comment]
I noticed the "chia farm summary" command is very long to execute.

Yesterday I removed that "farm summary" from my dashboard  (watch -n 30 chia farm summary).
When I woke up this morning, I checked the log and found full_node has been synced all night (eligible plots every few seconds).
I typed "chia farm summary" to see if I got any reward..The command took more than a minute to respond... immediately I saw a lot of disk activity on the database... Glances showing critical CPU_IOWAIT warnings... and I got unsync'ed !

**Comment by Warmduscher** [comment]
I stumpled across the same issue. Using docker on a Synology NAS for the fullnode and i noticed that the blockchain sync stalled. I came across this issue and tested a few things. I moved the `.chia` directory to an external ssd drive (860 Pro via USB3) and looked at the monitoring. The drive reached 4-5K IOPS on read operations. This is way to much for a SATA spinning drive, but is a lot for an SSD as well. I noticed, that neither the blockchain nor the wallet advanced and stayed at the same height.

I then moved the `blockchain_v1_mainnet.sqlite` (and the other files in the directory) to a RAM-Disk and restarted everything. Afterwards it seems to reach to the current height in the blockchain. At least i have something like:

```
2021-05-15T19:31:38.021 wallet chia.wallet.wallet_blockchain: INFO     <F0><9F><92><B0> Updated wallet peak to height 280392, weight 16906976,
```

in my logfile again. Also `chia show -s` and `chia farm summary` now takes a second or two to respond again and not a minute.

**Comment by stipus** [comment]
I haven't been able to sync for the past 48 hours with my system SATA spinning hard drive.
This morning, I removed the spinning drive, replaced it with a fast SATA SSD (Samsung pro 960). I reinstalled Ubuntu 20.04.2 LTS from scratch, reinstalled chia-blockchain, restored the backup of the .chia directory... and after a few minutes "chia show -s" showed I was synced...

**Comment by benv666** [comment]
Ha, that's a night and day difference, thanks for this hint!

**Comment by babafgd** [comment]
Great ! I will try it !

**Comment by babafgd** [comment]
Best 

> I stumpled across the same issue. Using docker on a Synology NAS for the fullnode and i noticed that the blockchain sync stalled. I came across this issue and tested a few things. I moved the `.chia` directory to an external ssd drive (860 Pro via USB3) and looked at the monitoring. The drive reached 4-5K IOPS on read operations. This is way to much for a SATA spinning drive, but is a lot for an SSD as well. I noticed, that neither the blockchain nor the wallet advanced and stayed at the same height.
> 
> I then moved the `blockchain_v1_mainnet.sqlite` (and the other files in the directory) to a RAM-Disk and restarted everything. Afterwards it seems to reach to the current height in the blockchain. At least i have something like:
> 
> ```
> 2021-05-15T19:31:38.021 wallet chia.wallet.wallet_blockchain: INFO     <F0><9F><92><B0> Updated wallet peak to height 280392, weight 16906976,
> ```
> 
> in my logfile again. Also `chia show -s` and `chia farm summary` now takes a second or two to respond again and not a minute.

Thanks for the hint !   I have followed the advice and moved the `blockchain_v1_mainnet.sqlite` to a `ramdisk `and now I'm syncing faster and get CPU usage nearly 100%. I had a lot less IO_WAIT :)
