### ISSUE TITLE
[BUG] Percentage for plotting progress is wrong if advanced options are not standard

### ISSUE THREAD

**Issue by subsonic80** [Chia-Network/chia-blockchain#4946]
Progress bar and percentage for plotting will be wrong if advanced options are changed

**To Reproduce**
- add a plot
- change advanced options (mine are) RAM usage 26000; Number of threads 8; Number of Buckets 32;
- start plotting
- plotting will be finished when 30% are reached 

**Expected behavior**
Progress bar should be calculated correct for the complete range of options

**Screenshots**
![grafik](https://user-images.githubusercontent.com/84179283/118253117-d28f2000-b4a9-11eb-9d5a-db7af7b6c4ef.png)**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: 20H2
- CPU: Ryzen 7 5800X
- Chia Version: 1.1.5

**Comment by LewyMaster** [comment]
I think it is duplicated Issue ( https://github.com/Chia-Network/chia-blockchain/issues/4743 ) :) I think the progress bar is calculated based on the number of buckets (looks that other settings not counted).

**Comment by sargonas** [comment]
I concur this looks related to issue #4743. I'll close this one out as a duplicate and add relevant notes on both so it can be tracked in one place.
