### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kupaliadam** [Chia-Network/chia-blockchain#4953]
When my computer shut down for some reason my last unfinished plots stopped but their (unfineshed plots’) temp files still cover  size on my harddisk. And if i restart plotting my harddisk the temp files from last unfineshed plotting isn’t deleted from my harddisk and plotting starts in beginning (from 0%) 

i think you can update the chia farming program to start plotting where it stopped to avoid the missings of accidently shutting down of the farming machines.

**Comment by stipus** [comment]
This is currently in the documentation. If you stop a plotting process, you have to manually clear the temp files.
