### ISSUE TITLE
DevTools failed to load SourceMap: Could not parse content for file:///Applications/Chia.app/Contents/Resources/app.asar/build/renderer/js/399.js.map: Unexpected end of JSON input

### ISSUE THREAD

**Issue by AlexArzon** [Chia-Network/chia-blockchain#4956]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by mcgclt** [comment]
Running into same error. Mid plot get the circle saying connecting to wallet and have to delete all the temp files and start over. Happened 3 times in a row now. Have tried the other solution mentioned of deleting .chia folder and reinstalling miner but still getting the error.
