### ISSUE TITLE
[BUG]  height is different from  wallet and main tab

### ISSUE THREAD

**Issue by qu6an** [Chia-Network/chia-blockchain#4965]
For a day now, my farm is online and synced, as shown in the first tab...
But the wallet tab is still syncing and the height is different from the main tab.

Does that mean I couldn't catch the coin? Different height of the wallet and what is shown in the main section-should it be the same?

**Comment by HughRyu** [comment]
Me too,also main tab different with wallet height.
wallet still sycing in up 3days,sycing extremly slow!

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
