### ISSUE TITLE
Windows GUI always creates plots using first key

### ISSUE THREAD

**Issue by Sarkoon** [Chia-Network/chia-blockchain#498]
**Describe the bug**
In the Windows GUI, regardless of what Key you select when you create a plot it always uses the first key.

**To Reproduce**

1. In the Windows GUI, click on Keys
2. Select any key besides the first one in the list.
3. Click the Plot button
4. Create a plot.

**Expected behavior**
The plot should be created with the key you selected.

**Desktop (please complete the following information):**

- OS: Windows 10 Build 18363
- CPU: Intel Core i7 8700K
- Chia 1.0b17

**Comment by Sarkoon** [comment]
@eFishCent - tagging you as reqeusted!

**Comment by eFishCent** [comment]
Notes to GUI developer @seeden:
Latest dev branch has new argument for `chia plots create -a [fingerprint]` to create plot with farmer + pool key associated with fingerprint.
Based on brief review of dev branch GUI code, looks like the following needs to be updated:
`export const startPlotting` in plotter_messages.js needs to add -a argument
`dispatch(startPlotting` in plotter.js calls should pass -a argument with fingerprint

@seeden I am not familiar enough with js and GUI development to make changes, as I am afraid I'll break something. Let me know if I missed something so I can learn a bit more in the future.

**Comment by seeden** [comment]
Thanks, @eFishCent for the description. I will take a look

**Comment by seeden** [comment]
This is fixed via https://github.com/Chia-Network/chia-blockchain/pull/545
