### ISSUE TITLE
[BUG] parallel plotting fails?

### ISSUE THREAD

**Issue by acknologia** [Chia-Network/chia-blockchain#4989]
I haven't changed my setup at all for the past few days but i keep getting different outcomes. Before 1.1.5 came out i could parallel plot 7 plots no issues at all. but recently 1 of 7 just stops at like 10-15%. Most recently 5 of 7 stopped.
I do allocate 1 thread and 4 gib ram for each plot with a 15 minute offset between plots.

I am currently still on 1.1.4. Just too scared to update because i haven't had syncing issues in days and well i feel like even breathing near my machine will cause it 😅

- OS: linux
- OS Version/Flavor: ubuntu
- CPU: i7 8700k
**Additional context**

**Comment by ronny332** [comment]
How are you using Chia? In combiation with GUI "Installer", or as package e.g. from Pypi.org? I use it as simple package without any gui and from this point of view I can say: there is no "parallel plotting" in Chia. Each plotting process is fully independent from an other. The only shared data is the key set you are using.
My setup is similar to yours, but without any desktop involved. Chai's wallet is fully synced/working, plotting works fine (I have an PCIE and an SATA SSD for plotting, 100gb Plots, 4 Threads, 16GB RAM max each).

**Comment by acknologia** [comment]
I am using the gui version. Not the most familiar with linux, first time using it since i couldn't resolve syncing issue at all on windows.

I have a nvme ssd which i use for plotting (2tb sabrent).
i have 32gb of ram. I have a 5 bay das which i move my plots to. I farm on the same machine if that makes any difference?
750w psu, 1080ti (used to be a gaming machine), 8700k with an aio cooler oc'd to 5ghz
Is there any other hardware things i forgot to mention?

**Comment by room101-dev** [comment]
**chia1_1_.log:Caught plotting error: Matches do not match with number of write entries 4292221214 429221325**

yes, this is a new problem with '15' prior to that I have not seen this problem, many manifestations, started with the 'mis-match', then I saw stuff freeze at funny numbers like 32.9gb in the temps, always the same number on different plots

Been plotting 6 plots parallel on cmd-line for a long time

I would be interesting  if more people could report back, about falling back to old version for just running 'chia plot create' perhaps pre 13?? We know the file format doesn't change, and we know that this is a new problem, a software problem, and not a 'memory problem'.

Will go back to the source myself, and investigate whether the code on generating the 'mismatch' message & hard exit was changed in the past few weeks leading to this problem in plot creation failure.
