### ISSUE TITLE
[BUG] "farm challenges" command shows just one hash repeated many times

### ISSUE THREAD

**Issue by leptonsys** [Chia-Network/chia-blockchain#4994]
When I'm running the "chia farm challenges" command, I'm getting the same hashes repeated, instead to see unique ones. For example:

$ chia farm challenges
Hash: 0x61dc6460f61364ba39a14da9ad34dbd9ac6240c0098bb3b53499064601e460e8Index: 53
Hash: 0x61dc6460f61364ba39a14da9ad34dbd9ac6240c0098bb3b53499064601e460e8Index: 52
...
Hash: 0x61dc6460f61364ba39a14da9ad34dbd9ac6240c0098bb3b53499064601e460e8Index: 35
Hash: 0x61dc6460f61364ba39a14da9ad34dbd9ac6240c0098bb3b53499064601e460e8Index: 34

What does it mean? 
Is my farmer running correctly?

My chia version:
1.1.6.dev0

**Comment by franc29** [comment]
Si
