### ISSUE TITLE
It appears we no longer honor setting uPnP=false in config.yaml

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#501]
https://github.com/Chia-Network/chia-blockchain/blob/8a13535937d70eb58c50409dca2e2f42c43231aa/src/server/start_service.py#L111

End users must be able to disable uPnP as some wish to run two nodes behind one SMB/SOHO router.

**Comment by wjblanke** [comment]
https://github.com/Chia-Network/chia-blockchain/pull/522

**Comment by Jonas-ben** [comment]
can you explain that again 

because in line 111 i have : self .upnp: Optional[UPNP] = None 
in Line 130:  for port in self ._upnp_ports:
                    if self .upnp is None:
                    self .upnp = UPnP()
in Line 196: for port in self ._upnp_ports:
                    if self .upnp is not None:
                    self .upnp. release(Port)
Which line do i have to edit
