### ISSUE TITLE
[BUG]  incoming XCH not added up to the total XCH farmed

### ISSUE THREAD

**Issue by yyqqwang** [Chia-Network/chia-blockchain#5015]
**Describe the bug**

Today  I found my total income (XCH Total Chia Farmed) displayed in the 'Farm' page  is  24 XCH ,  but the total income in the incoming history displayed in the 'Wallets' page adds up to  27 XCH .   I  checked the incoming history then I found that  on 05/14/2021  11:04 am , I got 1.5 XCH incoming ， and on 05/14/2021  11:02 am  I got 1.5 XCH incoming，and it seems that  these 3  XCH are not added up to the total income.     Meanwhile  the full node and the wallet are connected and synced.
        I  have no idea how to solve this disorder. Hope someones can help.
       The OS  version  is Windows 10, and the Chia full node version is 1.1.5.

**To Reproduce**
       
        not resolved yet .

**Expected behavior**
      
             Total Chia Farmed  should be equal to the total income in the incoming histroy.

**Screenshots**
                   
                   
![11](https://user-images.githubusercontent.com/17003231/118325525-2e06ef80-b536-11eb-960c-a7ec8b5e11ad.jpg)
![2a](https://user-images.githubusercontent.com/17003231/118325537-319a7680-b536-11eb-8084-e8b4fbf74c9e.jpg)
![2b](https://user-images.githubusercontent.com/17003231/118325542-33643a00-b536-11eb-84a5-707f04357a2e.jpg)

**Desktop (please complete the following information):**

- OS:  win10
- OS Version  windows 10  version 1909
- CPU: AMD 5950x / 3960x

**Additional context**

**Comment by pietruha8** [comment]
Hi mate, 
Are you farming on pool?

**Comment by yyqqwang** [comment]
> Hi mate, 
> Are you farming on pool?

no, I am farming alone

**Comment by lvcivs** [comment]
What's your wallet balance? I am guessing it is 27. 

The two 1.5 XCH transactions were not farmer rewards (wrong amount), that's why they are not listed in the Farm Overview. So it looks like you simply reveived two transactions from another user, possibly by mistake?

**Comment by lvcivs** [comment]
Here is the block where the first of the 1.5 XCH transactions is included. https://www.chiaexplorer.com/blockchain/block/0xf6df23db1309752fc4641784a349083ed6fe78bf8e9fe7b7671db3abd1c34fd1
