### ISSUE TITLE
WARNING  Wasn't able to add transaction with id ... status 3 error: Err.DOUBLE_SPEND and Err.COIN_AMOUNT_NEGATIVE

### ISSUE THREAD

**Issue by pietruha8** [Chia-Network/chia-blockchain#5018]
While greping the log for warning I'm getting lots of 
WARNING  Wasn't able to add transaction with id  ...., status 3 error: Err.DOUBLE_SPEND

and

WARNING  Wasn't able to add transaction with id ....., status 3 error: Err.COIN_AMOUNT_NEGATIVE

Should I be worried about them?

**To Reproduce**

Grep the log

**Expected behavior**
Clear explanation of what it means?

- OS: Ubuntu
- OS Version - Ubuntu 20.04.2 LTS
- CPU AMD Ryzen 7 5800x

**Comment by sargonas** [comment]
This is likely coming from old nodes that have not yet updated to 1.1.5 and are stuck on the bad blocks with the bad data from before last sunday's update. You can safely ignores these in your log... this is your node doing it's job and rejecting the bad data as not being acceptable via consensus.

**Comment by pietruha8** [comment]
Thanks for your time and help.
