### ISSUE TITLE
[BUG] GUI Wallet History reports outgoing transactions loaded from blockchain as incoming with wrong amount

### ISSUE THREAD

**Issue by keeperlink** [Chia-Network/chia-blockchain#5022]
**Describe the bug**
When I send XCH, GUI shows correct transaction on machine I did the transaction. But on other machines GUI wallet shows those transactions as incoming. Amount is wrong as well.

**To Reproduce**
Have two machines running GUI with the same key.
Create outgoing transaction on one machine.
Wait for other machine to sync up.
Notice that other machine shows that transaction incorrectly.

- OS: Windows 10
- Chia ver. 1.1.5

**Example:**
Original machine shows in GUI:
**Outgoing | xch... | 05/14/2021 ... | Confirmed at height ...32 | 0.2 | 0**
Second machine shows the same transaction as:
**Incoming | xch... | 05/14/2021 ... | Confirmed at height ...32 | 1.55 | 0**

**Comment by nenedelnorte** [comment]
chiastatus

**Comment by appsheld** [comment]
Same on my machines. Thirst is Win 10 second is Linux.
