### ISSUE TITLE
[help] Chia stuck transactions!

### ISSUE THREAD

**Issue by giang21199z** [Chia-Network/chia-blockchain#5040]
I'm tried to send 1 to MXC and set Amount 1 and Fees = 0.001.

I waited about 7 hours and transaction still not mined.
How I can cancel this transaction and resend it?
Please help me.

**Comment by nenedelnorte** [comment]
intenta enviar otra monto 0.001 y fee 0 pero estas 24hs varios tenemos problema de acreditaciones en todos lado. a esperar q sincronize bien la block-

**Comment by Candepc** [comment]
Transfer with a fee of 0.001 in the status of pending more than 24 hours. After that, I made a transfer 0.1 without fee - it took 5 minutes
