### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bentallea** [Chia-Network/chia-blockchain#5062]
**Describe the bug**
Plotting on 2 drive fails when using small drives

**To Reproduce**
Setup plotting with 2 write locations on separate drives. the first drive must be smaller than the plot size. 
Chia will fill the first drive, and not be able to write to the second because chia is waiting for free space on the first drive.

**Expected behavior**
Have the working files written to both disks in proportion to the free space available on both drives.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: Ryzen 2700X

**Additional context**

**Comment by centrd** [comment]
The behaviour you're expecting is not in line with the design, and is not how the temp dirs work. This is not a bug. Please review the plotting documentation.
