### ISSUE TITLE
DevTools failed to load SourceMap: Could not parse content for file:///Applications/Chia.app/Contents/Resources/app.asar/build/renderer/js/399.js.map: Unexpected end of JSON input

### ISSUE THREAD

**Issue by AlexArzon** [Chia-Network/chia-blockchain#5084]
DevTools failed to load SourceMap: Could not parse content for file:///Applications/Chia.app/Contents/Resources/app.asar/build/renderer/js/399.js.map: Unexpected end of JSON input

**Comment by suiri573035185** [comment]
same problem here when after reload the chia gui

**Comment by Oscillator098** [comment]
I have the same issue.
It is stuck to "Connecting to wallet" screen.
Windows 10
Port 8444 is open, running only 1 client.
Client version Chia Blockchain 1.1.5.
Electron 11.4.3.
Node 12.18.3
V8 8.7.220.31-electron.0

**Comment by NavaLibuS** [comment]
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/alptk/AppData/Local/chia-blockchain/app-1.1.5/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

my plots at %94 and i have that message, and it is stuck to "connecting to wallet" screen.
