### ISSUE TITLE
Linux key storage major security flaw

### ISSUE THREAD

**Issue by AlexSSD7** [Chia-Network/chia-blockchain#5089]
Storing keys on Linux is super unsafe. First, it is COMPLETELY unencrypted. Anyone who has access to the filesystem can steal all funds. Moreover, what is really huge, is that permissions set to the Keystore files allow read access to ALL users in the system.

```
$ ls -l ~/.chia/mainnet/wallet/db/
-rw-r--r-- 1 ******** ********  ******** ******** ********
....
```

What should be done:
* Keys should be encrypted
* Permissions should be set to 600 instead of 644

**Comment by lvcivs** [comment]
The folder you mention contains only the blockchain and peers databases. Do you perhaps mean `~.chia/mainnet/config/ssl/wallet`?

**Comment by AlexSSD7** [comment]
Ah, yes this. It is even set to 664 :scream:

**Comment by gromran** [comment]
>  Anyone who has access to the filesystem

If someone gets access to the FS, it's too late anyway

**Comment by lvcivs** [comment]
> If someone gets access to the FS, it's too late anyway

Disagree heavily with this. Unix systems have been designed as multiuser system from the ground up and permissions matter. This is why the permissions are built very deeply into the system. Think of servers on a university campus, share hosters etc. It is absolutely normal and expected that someone might be on the same filesystem who is not necessarily trustworthy.

**Comment by lvcivs** [comment]
This is an unsolved security related issue and should remain open.
