### ISSUE TITLE
harvester exit without warning, gui still display farming. NO FARMING REWARD

### ISSUE THREAD

**Issue by knightli2003** [Chia-Network/chia-blockchain#5093]
gui status is farming, everything is OK
![1](https://user-images.githubusercontent.com/878190/118359941-238d3a00-b5b8-11eb-91e1-8e1c4fb1734a.png)

harvester can not connected
xxx@xxxxxxxxx:/media/plot/ST_4T_01/farm2$ chia farm summary
Connection error. Check if harvester is running at 8560
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: Unknown
Total size of plots: Unknown
Estimated network space: 5020.860 PiB
Expected time to win: Unknown
Note: log into your key using 'chia wallet show' to see rewards for each key

in syslog
May 15 01:25:41 xxxxxxxxxxxxx kernel: [383060.769999] chia_harvester[122631]: segfault at 7f3970113bbb ip 00007f39b16e31e2 sp 00007f39acc868f8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f39b1676000+b8000]
May 15 01:25:41 xxxxxxxxxxxxx kernel: [383060.770011] Code: d9 48 8b 7c 24 c8 49 89 d3 0f bd c0 83 f0 1f 8d 74 c8 29 e9 fb fc ff ff 48 85 c9 0f 84 5a ff ff ff 48 8d 5a 08 48 89 54 24 e0 <0f> b6 74 0a ff 48 89 5c 24 e8 48 83 f9 07 0f 86 5a 02 00 00 4c 8d

package: chia-blockchain_1.1.5_amd64.deb
os: ubuntu x86-64 20.04

**Comment by ramkom9** [comment]
at this point more possibility are to win loto then block here, just saying

**Comment by laszlojanosek** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/2356#issuecomment-850158235
