### ISSUE TITLE
Cant connection to wallet 

### ISSUE THREAD

**Issue by paritad99** [Chia-Network/chia-blockchain#5094]
i cant connection to wallet Chia 1.1.5

**Comment by mcbrian710** [comment]
i cant connect, too.

**Comment by PavelLaktn** [comment]
The same problem as well after rebooting my PC

**Comment by chiamillonarie** [comment]
Same here :(

**Comment by erickstryck** [comment]
After receiving the latest changes from the 'main' branch the connection to the wallet is not being established, I have the following errors on the command lines when I try to retrieve the wallet address:

`chia wallet get_address
Traceback (most recent call last):
  File "/home/miner/chia-blockchain/venv/bin/chia", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')())
  File "/home/miner/chia-blockchain/chia/cmds/chia.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/miner/chia-blockchain/chia/cmds/wallet.py", line 115, in get_address_cmd
    from .wallet_funcs import execute_with_wallet, get_address
  File "/home/miner/chia-blockchain/chia/cmds/wallet_funcs.py", line 12, in <module>
    from chia.server.start_wallet import SERVICE_NAME
  File "/home/miner/chia-blockchain/chia/server/start_wallet.py", line 7, in <module>
    from chia.rpc.wallet_rpc_api import WalletRpcApi
  File "/home/miner/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 33, in <module>
    from chia.wallet.wallet_node import WalletNode
  File "/home/miner/chia-blockchain/chia/wallet/wallet_node.py", line 28, in <module>
    from chia.server.node_discovery import WalletPeers
  File "/home/miner/chia-blockchain/chia/server/node_discovery.py", line 13, in <module>
    import dns.asyncresolver
ModuleNotFoundError: No module named 'dns'
`
this error happens for any wallet related action.

The error started to occur after obtaining the most recent data from the 'main' branch

`From https://github.com/Chia-Network/chia-blockchain
 * branch              main       -> FETCH_HEAD
   4fc32cb5..39ef6964  main       -> origin/main
Updating 0b91005c..39ef6964
`

**Comment by erickstryck** [comment]
> After receiving the latest changes from the 'main' branch the connection to the wallet is not being established, I have the following errors on the command lines when I try to retrieve the wallet address:
> 
> `chia wallet get_address Traceback (most recent call last): File "/home/miner/chia-blockchain/venv/bin/chia", line 33, in <module> sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia')()) File "/home/miner/chia-blockchain/chia/cmds/chia.py", line 77, in main cli() # pylint: disable=no-value-for-parameter File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/miner/chia-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/home/miner/chia-blockchain/chia/cmds/wallet.py", line 115, in get_address_cmd from .wallet_funcs import execute_with_wallet, get_address File "/home/miner/chia-blockchain/chia/cmds/wallet_funcs.py", line 12, in <module> from chia.server.start_wallet import SERVICE_NAME File "/home/miner/chia-blockchain/chia/server/start_wallet.py", line 7, in <module> from chia.rpc.wallet_rpc_api import WalletRpcApi File "/home/miner/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 33, in <module> from chia.wallet.wallet_node import WalletNode File "/home/miner/chia-blockchain/chia/wallet/wallet_node.py", line 28, in <module> from chia.server.node_discovery import WalletPeers File "/home/miner/chia-blockchain/chia/server/node_discovery.py", line 13, in <module> import dns.asyncresolver ModuleNotFoundError: No module named 'dns' `
> this error happens for any wallet related action.
> 
> The error started to occur after obtaining the most recent data from the 'main' branch
> 
> `From https://github.com/Chia-Network/chia-blockchain
> 
>     * branch              main       -> FETCH_HEAD
>       [4fc32cb](https://github.com/Chia-Network/chia-blockchain/commit/4fc32cb5a8ffe8adb8cf96deb78983e8359e81ae)..[39ef696](https://github.com/Chia-Network/chia-blockchain/commit/39ef69643b0bcaf4309866df3802850903275b92)  main       -> origin/main
>       Updating [0b91005](https://github.com/Chia-Network/chia-blockchain/commit/0b91005c6b448ab6b5aaf1125bdfc5e38fd8f511)..[39ef696](https://github.com/Chia-Network/chia-blockchain/commit/39ef69643b0bcaf4309866df3802850903275b92)
>       `

[UPDATE] In linux I solved the problem just by running 'install.sh' again.

**Comment by mysstra** [comment]
The same thing is happening to me in windows 10. It does not connect to the wallet.
I have re-installed, rebooted and it remains the same. any possible solution? Thank you

**Comment by nenedelnorte** [comment]
yo intento volviendo a bajar block entera desde cero
por el bloque 200100 aparecio mis 2 chia. y en 270002 envie pero no aparece en waller pero si blockchain  chiastatus estan mis chia, espero pq estoy en cero. no se si es mejor billetera 24 palabra o un exchanger.

**Comment by Justin-chr** [comment]
I have the same Problem... The Log says that somting is banned...
`2021-05-15T21:04:24.732 full_node full_node_server        : WARNING  Peer 178.69.4.200 is still banned, not connecting to it
2021-05-15T21:04:32.092 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:04:32.494 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:04:56.397 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:05:22.730 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:06:53.037 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-15T21:07:57.402 full_node full_node_server        : WARNING  Peer 151.26.89.13 is still banned, not connecting to it
2021-05-15T22:02:08.033 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 356, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

2021-05-15T22:29:31.459 full_node full_node_server        : WARNING  Banning 151.26.89.13 for 600 seconds
2021-05-15T22:29:31.465 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 151.26.89.13
`
Can anybody help???

**Comment by Alpejohn** [comment]
I got this problem yesterday do. Was not able to open the blockchain.. Ended up deleting the .chia folder and reinstalling. Now its working, but it has to sync everything and it take ages.. And I only get 10-15 peers. My port is open and upnp is disabled. Even tried to add the introducer but it does not help at all.

**Comment by Justin-chr** [comment]
> I have the same Problem... The Log says that somting is banned...
> 
> `
> 2021-05-15T12:32:48.767 wallet wallet_server : WARNING Trying to ban localhost for 10, but will not ban
> 2021-05-15T12:32:51.767 wallet wallet_server : ERROR Exception: , {'host': '127.0.0.1', 'port': 8444}. Traceback (most recent call last):
> File "chia\server\server.py", line 521, in wrapped_coroutine
> File "chia\wallet\wallet_node_api.py", line 49, in new_peak_wallet
> File "chia\wallet\wallet_node.py", line 437, in new_peak_wallet
> File "chia\wallet\wallet_node.py", line 368, in complete_blocks
> File "chia\wallet\wallet_state_manager.py", line 825, in get_filter_additions_removals
> AssertionError
> 
> 2021-05-15T21:04:24.732 full_node full_node_server : WARNING Peer 178.69.4.200 is still banned, not connecting to it
> 2021-05-15T21:04:32.092 full_node chia.full_node.full_node: WARNING Invalid response for slot None
> 2021-05-15T21:04:32.494 full_node chia.full_node.full_node: WARNING Invalid response for slot None
> 2021-05-15T21:04:56.397 full_node chia.full_node.full_node: WARNING Invalid response for slot None
> 2021-05-15T21:05:22.730 full_node chia.full_node.full_node: WARNING Invalid response for slot None
> 2021-05-15T21:06:53.037 full_node chia.full_node.full_node: WARNING Invalid response for slot None
> 2021-05-15T21:07:57.402 full_node full_node_server : WARNING Peer 151.26.89.13 is still banned, not connecting to it
> 2021-05-15T22:02:08.033 full_node full_node_server : ERROR Exception , exception Stack: Traceback (most recent call last):
> File "chia\server\server.py", line 356, in start_client
> File "aiohttp\client.py", line 763, in _ws_connect
> File "aiohttp\client.py", line 521, in _request
> File "aiohttp\connector.py", line 535, in connect
> File "aiohttp\connector.py", line 892, in _create_connection
> File "aiohttp\connector.py", line 1032, in _create_direct_connection
> File "aiohttp\connector.py", line 969, in _wrap_create_connection
> File "asyncio\base_events.py", line 949, in create_connection
> File "asyncio\selector_events.py", line 473, in sock_connect
> concurrent.futures._base.CancelledError
> 
> 2021-05-15T22:29:31.459 full_node full_node_server : WARNING Banning 151.26.89.13 for 600 seconds
> 2021-05-15T22:29:31.465 full_node chia.full_node.full_node: ERROR Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
> File "chia\full_node\full_node.py", line 628, in _sync
> RuntimeError: Weight proof did not arrive in time from peer: 151.26.89.13
> `
> Can anybody help???

After syncing two more devices, they have exactly the same problem ...

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
