### ISSUE TITLE
[BUG] Why are some display abnormal？

### ISSUE THREAD

**Issue by yuzhongrong** [Chia-Network/chia-blockchain#5114]
![image](https://user-images.githubusercontent.com/7382234/118369801-64e11200-b5d7-11eb-8b4d-5aceaec20590.png)

**Comment by lvcivs** [comment]
It's just a very small number. 1E-12 = 0.000000000001

**Comment by yuzhongrong** [comment]
i  have a post request

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/118371394-0fa8fe80-b5df-11eb-9147-dfa5bd320544.png)
{"amount":1.0,"fee":0.002,"to":"txch14wzqhehqputnul7yjlyg5rqenhmsz3mj823hcgvyqaz336ym379s3yt6e0"}

Too small this amount  ?   need to change 100000000000=1 txch?

**Comment by yuzhongrong** [comment]
thanks。 i see
