### ISSUE TITLE
[BUG] GUI is not updating "height" for connected peers and lags behind

### ISSUE THREAD

**Issue by boettges** [Chia-Network/chia-blockchain#5121]
**Describe the bug**
Despite new block hashes coming in timely and frequently and the overall status of my node is disaplyed as "synced" in the GUI, the displayed "height" for connections to peers often lags behind.
It seems as if the height for peer connections is not updating at least in the Windows version of the app (1.1.5).

Example:
The "peak height" of my "full node status" could be at 285575, but the height of connected nodes remains stuck at 284511.

**To Reproduce**

1. Use the GUI of 1.1.5 for windows
2. Wait for the node to sync
3. Observe the height of your own "full node status" drifting apart from the heights displayed for peer connections to other nodes in the "connections" section of the "full node" tab.
4. If you use `chia show -c` the heights are properly displayed.
5. If you hit the "keys" tab and switch back to the full node (still active in the background) by clicking on your private key the connections' heights will be updated due to a **full GUI refresh**.

**Expected behavior**
Connection height is updated live.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro

I know that this is not the most critical bug to fix right now. Yet, the displayed difference between the heights can give the impression that the node might be connected to "lagging" peers. This leads to a lot of confusion amongst those that suspect faulty connections being the reason for not finding the proof of a block. 

Thanks a lot in advance!

**Comment by gromran** [comment]
> displayed "height" for connections to peers often lags behind

not a bug, only a delayed update (or not synced peer wallets)
