### ISSUE TITLE
[BUG] Sync got stuck - RuntimeError: Weight proof did not arrive in time from peer

### ISSUE THREAD

**Issue by jakub-polak** [Chia-Network/chia-blockchain#5125]
**Describe the bug**
I can not sync from about 48 hours. Sync is stuck at 271024 (when I delete `db` dir I got stuck at 0).

I see in the logs a lot of
```
RuntimeError: Weight proof did not arrive in time from peer
```

I do have connections to many peers and I can see transactions.

Ubuntu 20.04 LTS
Chia 1.1.5

**Comment by hotab** [comment]
Any update on this?

**Comment by jakub-polak** [comment]
The update is a really sad one - a lot of folks have this issue and really no one knows how to solve it.

**Comment by hotab** [comment]
Just in case - I checked manually that port 8444 is open. This still does not work.

**Comment by jakub-polak** [comment]
It is not port-related for sure.

**Comment by profitraff** [comment]
I have the same problem today

**Comment by grabypoker** [comment]
me too

**Comment by Maniek73** [comment]
Today 1:53 my  sync stuck on 302024 and no way to resume syncing. Many peers connected, but still error:
RuntimeError: Weight proof did not arrive in time from peer: . After deleting all db same situation but on height 0, sync not start.
Time settings OK, win10.
Any idea?

**Comment by hotab** [comment]
So, this bug fixed itself after I did the following:
1. Updated chia to 1.1.5 following the process in the wiki.
2. Moved the db file in and out while restarting chia multiple times
3. Left it waiting
4. Manually added peers from the past
5. Messed with system clock
6. Validated port 8444 was open, also opened udp 8444.

After doing these in random order, I just gave up, left it running for a day, and it finally synced. I am not quite sure what the problem is or was, but if this helps dev team track this issue down - would be great.

**Comment by hotab** [comment]
Just in case - for me it sill works and is still proceeding with sync. Not sure why.

**Comment by rikva** [comment]
Same problem here, unfortunately.

**Comment by mariano54** [comment]
Please update to 1.1.6

**Comment by dperdhana** [comment]
Same here. It has been three days now and my nodes never synced. I have two machines running two different versions: 1.1.6 and 1.1.7dev0 (both just upgraded from version 1.1.5). Both showing "Syncing x/x" on the Full Node screen but the peak height number never change. Peer connection section show tens of peers are connected. Debug.log inform the following messages repeatedly:

```
2021-05-21T18:56:13.103 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/home/chiafarm/Downloads/chia-blockchain/chia/full_node/full_node.py", line 640, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: <PEER_IP_HERE>
```

I have tried to restart the chia node even reboot the computer many times but still no luck. I have ensured that the clock of those computers are automatically synced to NTP. Port 8444 is open and can receive connection from internet with no issue. At this point, I don't have any idea what should I try to address this issue.

**Comment by CoderArgentina** [comment]
I update to 1.1.6 and now the wallet is syncing and the node is synced.. i think it work ok at least now

**Comment by dperdhana** [comment]
I tried to move the .chia directory under my homedir and created an empty directory to start over, unfortunately it did not help. So I removed the new directory and restored the old one. Finally, I reinstalled the chia and it work. It is now synced.

**Comment by rikva** [comment]
After upgrading to 1.6.1, restarting and removing the peers database several times and manually adding peers, my node is finally sinced now.

**Comment by mariano54** [comment]
Sometimes you have to wait a bit until you get a peer that will respond with a weight proof faster. I would leave it on for a few hours
