### ISSUE TITLE
[BUG] - Restored wallet not showing Chia Amount

### ISSUE THREAD

**Issue by ataman79** [Chia-Network/chia-blockchain#5147]
I installed latest Chia Wallet 1.1.5 on another PC. And restored my wallet with the 24 words. The wallet is sync, but it not shows the chia amount. On my other PC the wallet is 1.1.1 and it shows me my chia amount

I am running windows 10

What is the problem, what should I do ?

**Comment by l69zeroday94** [comment]
Is it the same after synchronization?

**Comment by DMS-1981** [comment]
after synchronization same problem wallets any ideas

**Comment by ataman79** [comment]
> Is it the same after synchronization?

Yes, this is after synchronization

**Comment by l69zeroday94** [comment]
Can you try again on the virtual machine?
Duplicate of ##863
