### ISSUE TITLE
[BUG] - Transaction between two chia wallets is successful but the amount is not visible on the second wallet

### ISSUE THREAD

**Issue by ataman79** [Chia-Network/chia-blockchain#5148]
I sent two days ago some chia amount to my another wallet which is installed on another PC. After the second wallet sync , the chia amount I've send from wallet 1 is not visible. When I check it on the blockchain explorer and look at the address of my wallet 2 it shows me that I must have some chia, but in wallet it's not visible  - here is the transaction https://www.chiaexplorer.com/blockchain/coin/0x649d02ec837f20ca5bd01399096db8ada4d0b4c856859209d7b10cd3a44794d8

I am running wallets on Windows 10

**Comment by fckngguy** [comment]
I have this same issue. Bought CHIA from DigiFinex (withdraw confirmations and successes confirmed), sent it to my "RECEIVE" address in my wallet. Full Node is synced. Shows up on the block explorer, but no balance in wallet. What do we think? Just wait?

https://www.chiaexplorer.com/blockchain/address/xch12sn97lacza2ggfr3zd9kypjm39tsdglzufaawhqhjpwf3c4l2suqx09mhw

**Comment by neodiX42** [comment]
Hi, same issue as by @fckngguy, with OKEX only. Tx in explorer 

https://www.chiaexplorer.com/blockchain/address/xch1w3kxq8kmmgnlfam0es2upmapynjgrukm4cr6y0gpdxjkx0qljckqsdlgf8

**Comment by Cminer3207** [comment]
Did any of you clowns figure this out yet?
