### ISSUE TITLE
[BUG] Refresh always hangs on Windows

### ISSUE THREAD

**Issue by JamesMcGhee** [Chia-Network/chia-blockchain#5153]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

Open the app and click refresh or force refresh
Wait forver
Observer that it never progresses

**Expected behavior**
It should progress at some point

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: Ryzen 9 5950X

**Additional context**

**Comment by killerfrost22** [comment]
Same issue here but resolved!
Steps tried:
Delete these folders:
C:\Users\yourusername.chia
C:\Users\yourusername\AppData\Local\chia-blockchain
C:\Users\yourusername\AppData\Roaming\Chia Blockchain

**Comment by JamesMcGhee** [comment]
Thanks will give that a go next I can and update accordingly

**Comment by KoborOld** [comment]
Happened to me for Refresh it stucked, needed to close GUI and kill all processes to start it over.
Lost Plot progressions.

**Comment by JamesMcGhee** [comment]
More updates ... it seems to hange on add plot from directory and either hangs or just ignores "delete" from the plot context menu.
