### ISSUE TITLE
[BUG] Plotter needs '-maxtemp' switch so that NVME's don't burn up post 1.1.4 - needs logs on stall&mismatch early

### ISSUE THREAD

**Issue by room101-dev** [Chia-Network/chia-blockchain#5159]
**Describe the bug**

The big problem with 'plotting' is there is no tracking of over-heating on the nvme/ssd/hdd when plotting so the plotter (miner) just keep burning up the drive until the plot hangs, and only message ever seen is 'mis-match', but not seen until full 108gb has been processed 6-24 hr, so you have wasted lots of time. There is only one check and that is at the end of process.

DEV seems to have wanted to make stuff 'fast', but if it burns up drives and it wastes time/resources its not fast, you don't make something fast, until you have made it work.

At this point when plotting

1.) hold back on older solid version, before they made it 'fast', as all plots are the same you don't need latest broken software to make plots
2.) seems that it is better not to have blockchain (npm run electron) even running on plotting machine
3.) expect to have your nvme's fry every 10-20 days, holds lots of these $200 USD puppys on stock

**To Reproduce**

Just run lots of plots on the cmd-line, say stagger 4+ plots on a 1TB & let it run a week, see how long your NVME lasts.

Monitor the Temp of all NVME's on the system, monitor the 'errors' logged on all internal NVME devices, look for signs of instability like 'wait-times' to go 10x good sign the NVME has become unstable

**Expected behavior**
Just like mining on GPU boards, once a GPU exceeds 72C quit using it, same here once a NVME hits +80C stop-using suspend the process log, 

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**
Best way to save plots during shutdown of 'gui' is to NEVER use gui to make plots

Use the cmd-line to make plots, that way it has NOTHING to do with the blockchain

Use linux, never use windows
That's about it, another thing is hold-back on 1.1.3 I call '13' for plots as post 14 the plotter seems to burn up NVME's in about two weeks and will kill a hdd  or sdd in a day

The big problem with 'plotting' is there is no tracking of over-heating on the nvme/ssd/hdd when plotting so the plotter (miner) just keep burning up the drive until the plot hangs, and only message ever seen is 'mis-match', but not seen until full 108gb has been processed 6-24 hr, so you have wasted lots of time. There is only one check and that is at the end of process.

DEV seems to have wanted to make stuff 'fast', but if it burns up drives and it wastes time/resources its not fast, you don't make something fast, until you have made it work.

At this point when plotting

1.) hold back on older solid version, before they made it 'fast', as all plots are the same you don't need latest broken software to make plots
2.) seems that it is better not to have blockchain (npm run electron) even running on plotting machine
3.) expect to have your nvme's fry every 10-20 days, holds lots of these $200 USD puppys on stock

It's not good, but one has to do what works.

This is going to be a long and painful process, not unlike the birth of 'bit-torrent' took years to get it right.

**Comment by vladimir7777777** [comment]
the chart of the raft constantly freezes and does not reach the end tested 1 raft at 440 ssd
