### ISSUE TITLE
Automatic copying of completed plots to destination is slower than manual copying

### ISSUE THREAD

**Issue by thestevekoch** [Chia-Network/chia-blockchain#5169]
On Ubuntu 20.04 the final process where the plots are copied to the destination is slower than if the user copies the same plots to the same destination manually using the GUI.

For instance, two plots completed phase 4 (plot 1 and plot 2) and they started transferring to _dest1_ at ~8:50 PM. At 9:10 PM I manually copied plot 1 into a temporary folder in _dest1_ which completed in 30 minutes at 9:40 PM. The copy process chia started is still ongoing at 9:50 PM with plot 1 and plot 2 at 33 GB and 27 GB completed, respectively.

**Comment by josinaldobarbosa** [comment]
are you copying more than one plot at the same time?

**Comment by thestevekoch** [comment]
Yes

**Comment by ITPrism** [comment]
I have just completed a plot. It is in phase of coping the compressed file from second temporary folder to the permanent one.
This is really slow because the second temporary folder and the constant folder are on the same disk.

Is there an option to move the file instead of copying when the temporary compressed file and the permanent folder are on the same disc?

I guess, the OS will only edit the boot record and would not copy the whole file bytes by bytes.
This approach could save time and will keep the disk healthy longer.

**Comment by ITPrism** [comment]
I guess, this Pull Request could be a solution.
https://github.com/Chia-Network/chiapos/pull/211

**Comment by thestevekoch** [comment]
> On Ubuntu 20.04 the final process where the plots are copied to the destination is slower than if the user copies the same plots to the same destination manually using the GUI.
> 
> For instance, two plots completed phase 4 (plot 1 and plot 2) and they started transferring to _dest1_ at ~8:50 PM. At 9:10 PM I manually copied plot 1 into a temporary folder in _dest1_ which completed in 30 minutes at 9:40 PM. The copy process chia started is still ongoing at 9:50 PM with plot 1 and plot 2 at 33 GB and 27 GB completed, respectively.

Performed additional testing. A single plot copy performed by the chia process from the temp disk to the destination disk takes 60 minutes. The same copy (same file, same source, same destination) performed using the file manager takes 15 minutes. 

Environment info:

Chia 1.1.5
Ubuntu 20.04 Desktop
AMD Threadripper 1950x
64 GB memory
Temp disk: 4TB nvme (2x2TB Inland Premium in RAID0)
Dest disk: Western Digital My Book 14 TB connected via USB 3.1

**Comment by ITPrism** [comment]
Your case could be a problem with the PCI bus limits.
Your system would disable a drive if there are too many drives connected to your PC.
I had similar problem. When I connect a HDD via USB, the system disabled my inner network card.
There was an internet but it was too slow.
Check the documentation of your motherboard to find which drives shares PCI buses.

In my case, the problem is the process of files copy. Chia should move the file instead to copy it when the file has to be moved to a folder in the same partition.

**Comment by redbaron** [comment]
Why copy file at all? IMHO it's best to create file plot in the final destination, avoiding unnecessary IO all together even if tmp and output directories are on different disks.

**Comment by ITPrism** [comment]
You are right. Everyone must create plots in the permanent folder if he does not use second temporary folder (temporary folder on another drive). I have made a mistake starting a plot with second temp folder on the drive where the permanent folder is located. I entered wrong drive name.

So, the Plotter must take this into account and warn if someone does the same thing. It must prevent creation of plots if the second temporary folder and the permanent folder are located on same drive and partition.

If this approach is not accepted by you, the Plotter must move the file instead copy when the second temporary folder is located on same drive and portion with the permanent one.

That will avoid unnecessary IO if someone make similar mistake. :)

**Comment by redbaron** [comment]
No I mean regarding of the location of tmp and destination directories, always create final file in the destination directory.

So instead of this at the end of plotting:
- write file `$TMP/plot` 
- copy file `$TMP/plot` to `$DESTDIR/plot.tmp`
- rename `$DESTDIR/plot.tmp` to `$DESTDIR/plot`

Do this:
- write file `$DEST/plot.tmp` 
- rename `$DESTDIR/plot.tmp` to `$DESTDIR/plot`

**Comment by thestevekoch** [comment]
> Your case could be a problem with the PCI bus limits.
> Your system may be disable a drive if there are too many drives connected to your PC. If several drives share a bus.
> I had similar problem. When I connect a HDD via USB, the system disabled my inner network card.
> There was an internet but it was too slow.
> Check the documentation of your motherboard to find which drives shares PCI buses.
> 
> In my case, the problem is the process of files copy. Chia should move the file instead to copy it when the file has to be moved to a folder in the same partition.

I may not be explaining this clearly, so hopefully this clarifies what is occurring.

The only difference between the slow file copy and and fast file copy is whether Chia is performing it via a python call (fs::copy) or whether the Ubuntu file manager is performing the copy.

ALL other variables are the same and both fast and slow copies are occurring at the same time, using the same files. 

I have resolved the issue for myself by disabling the chia copy and instead using a bash script to monitor the temp directory and mv the file to the destination.

**Comment by chialeux** [comment]
> > Your case could be a problem with the PCI bus limits.
> > Your system may be disable a drive if there are too many drives connected to your PC. If several drives share a bus.
> > I had similar problem. When I connect a HDD via USB, the system disabled my inner network card.
> > There was an internet but it was too slow.
> > Check the documentation of your motherboard to find which drives shares PCI buses.
> > In my case, the problem is the process of files copy. Chia should move the file instead to copy it when the file has to be moved to a folder in the same partition.
> 
> I may not be explaining this clearly, so hopefully this clarifies what is occurring.
> 
> The only difference between the slow file copy and the fast file copy is whether Chia is performing it via a python call (fs::copy) or whether the Ubuntu file manager is performing the copy.
> 
> ALL other variables are the same and both fast and slow copies are occurring at the same time, using the same files.
> 
> I have resolved the issue for myself by disabling the chia copy and instead using a bash script to monitor the temp directory and mv the file to the destination.

Hi @thestevekoch can you explain how you disabled the chia copy? I also want to disable it and move the file manually. Thanks!

**Comment by thestevekoch** [comment]
> > I have resolved the issue for myself by disabling the chia copy and instead using a bash script to monitor the temp directory and mv the file to the destination.
> 
> Hi @thestevekoch can you explain how you disabled the chia copy? I also want to disable it and move the file manually. Thanks!

Sure, I'm using plotman, so I've uncommented out the tmp2 directory path and set it to a folder on my plotting NVMe. I've then set the destination path to the same folder. It's important that tmp2 and destination are on the same drive as this will perform a move instead of a copy. If you're not using plotman, you can do this by adding the _-2_ switch .

I've then created a short script that monitors the destination directory for plots and moves them into the final directory one at a time. Here's some example syntax of the plot command and a bash script.

Plot command example:
`chia plots create -k 32 -r 4 -u 128 -b 4000 -t /mnt/4tb -d /mnt/4tb/plottemp -2 /mnt/4tb/plottemp
`

Monitoring script example:

```
#!/bin/bash
while :
do
        echo "Checking for plots"
        for f in /mnt/4tb/plottemp/*.plot;
        do
                echo "Plot found. Moving plot to External Drive"
                mv -n "$f" "/mnt/extDrive"
        done

        echo "Sleeping 10 minutes"
        sleep 10m
done
```

**Comment by chialeux** [comment]
> I've then set the destination path to the same folder.

That was the missing key here! Thanks, I'll use the bash script too, It seems fine but i'll remove the `while` loop and use cron with a `*/10` entry.
