### ISSUE TITLE
No scroll bar on viewing a trade [BUG]

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#517]
**Describe the bug**
When viewing a trade offer, if the GUI window is not wide enough, there is no horizontal scroll bar.

**To Reproduce**
Grab a trade and attempt to view it.

**Expected behavior**
Horizontal scrollbar should come up

**Screenshots**
![image](https://user-images.githubusercontent.com/30377676/98657959-539d0d00-22f7-11eb-8c8f-a4e40099f517.png)

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: Catalina newest
- CPU: some i7

**Additional context**

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain/pull/537
