### ISSUE TITLE
My plot is not detecting [BUG]

### ISSUE THREAD

**Issue by krasher9** [Chia-Network/chia-blockchain#5174]
So i have a PC that is plotting fine but when i changed my HDD and put WD PURPLE, after successfully plotting 6 plots, it would not show as detected..  I tried manually locating the plots but it still wont detect my plots after selecting the folder. 

Is WD PURPLE Causing the issue? Before that i was using Seagate Ironwolf and it was detecting all my 14tb plots. Now i shifted my plots to another PC and added a new WD Purple there but everytime a plot is done it wont detect... This is very strange.

Any Advice?

**Comment by krasher9** [comment]
I am trying now to plot with another Fresh 14TB HDD Seagate ironwolf to see if the PLOT will detect or not..  
I hope that the WD Purple is not the cause to not able to use for chia farming as i have alot of them.

**Comment by aDilly** [comment]
> but when i changed my HDD and put WD PURPLE

Where did you move your plots too before removing the (old) HDD?
Did you transfer your plots back to the new HDD (WD Purple), and then point your farmer to the new location?

**Comment by krasher9** [comment]
@aDilly i just removed the HDD completly and put it on a different PC for farm only since it got filled up. 
This is a new opened HDD basically but a different brand this time, and yes i did click "Add plot directory"  and it wouldnt show me the plots :S

**Comment by krasher9** [comment]
![image](https://user-images.githubusercontent.com/83899298/118387410-8241ca80-b62f-11eb-9065-bc92738e422e.png)

**Comment by krasher9** [comment]
it just happened again, now i can confirm its not the WD Purple... something is wrong....  its not detecting my plots.

**Comment by krasher9** [comment]
after uninstalling , and deleting the .chia file ,  and fresh installation with reboot, everything worked and detected. Nice application , so much bugs ffs. what a waste of time .

**Comment by Laurence040605** [comment]
hello i have a same issue now what did you do and did you plots all read my plots is not reading my chia is this cause about hpool because i join in hpool or just a bug please answer krasher 9 

Krasher 9 please small information helps me a lot and big information helps me a big a lot please
