### ISSUE TITLE
Chia GUI randomly loses 10 or more connections and remains unsynced

### ISSUE THREAD

**Issue by BluefireXD** [Chia-Network/chia-blockchain#5175]
**Describe the bug**
Chia GUI looses for unknown reason all connections and stays unsynced. Other computers stay connected in the same network but the main machine with all the plots gets unsynced. Means its not a problem with internet connection. It s ab bug in the software which somehow ends in a infinity loop of not (re)connecting to nodes. This bug should be fixed asap. Else Chia farming is just a waste of money and time for small "newbie" farmers. 

**To Reproduce**
1. Start Chia GUI
2. Sync it and wait some hours if it stays synced
3. If its synced you can go to sleep
4. Wake up and everything is unsynced^^

**Expected behavior**
Wake up and Chia GUI stays synced or resync if connections lost

**Desktop (please complete the following information):**
- OS: Windows 10
- Chia GUI: 1.1.5
- Ports 8444 open, UPNP disabled on not farming machines

**Additional context**
A Problem which so many PPL have and its still not fixed. Ppl are wasting their money for others because even if they have some TB of space they never get a 100% working sync and farming state.  

Example error Msgs:
`2021-05-16T06:12:15.638 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '54.254.119.192', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError`

or

`2021-05-16T01:08:43.861 full_node full_node_server        : ERROR    Exception: Failed to fetch block 286883 from {'host': '66.234.202.186', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '66.234.202.186', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "chia\server\server.py", line 528, in wrapped_coroutine
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 286883 from {'host': '66.234.202.186', 'port': 8444}, timed out`

or 

`2021-05-16T01:08:44.517 full_node full_node_server        : ERROR    Exception: Failed to fetch block 286883 from {'host': '2.50.207.84', 'port': 8444}, timed out, {'host': '2.50.207.84', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 521, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 104, in new_peak
  File "chia\full_node\full_node.py", line 361, in new_peak
  File "chia\full_node\full_node.py", line 310, in short_sync_backtrack
  File "chia\full_node\full_node.py", line 295, in short_sync_backtrack
ValueError: Failed to fetch block 286883 from {'host': '2.50.207.84', 'port': 8444}, timed out`

**Current workaround**
Take some IP addresses/connections from synced PC (delete them there) and manually add them to the unsynced main machine. Sometimes it works. Still it seems main machine isn't able to reconnect and stays in a infinity loop of not connecting automatically.

**Comment by auzhuntr** [comment]
exactly the same thing is happening to me. very frustrating.

**Comment by roadrunner35** [comment]
i have that problem to what we gone do about

**Comment by BluefireXD** [comment]
Yes currently i know only two workarounds:
1.) Restart PC and Chia GUI (bad solution if you are plotting) 
2.) Write down/save some working IP addresses and manually connect to them if you lost connection (needs ~10-20mins until syncing)

But anyway... still a really frustrating bug which should be fixed asap!

**Comment by luotinen** [comment]
I can confirm this is happening. It happened to me today. So sad to restart and lose 4 plots.

**Comment by b1son13** [comment]
Same problem ... many time lost Sync and it take long hours to back ... Its boring to loose time like that !

**Comment by BluefireXD** [comment]
Im not sure but maybe the auto reconnect of my internet provider is the cause.
Currently it looks like i get unsynced and stay unsynced between 1 and 2 o'clock. That's the time of auto reconnect. 

... But still an software bug because its not automatically reconnecting for a sync :( 

Maybe the devs should have a look on the reconnect function after loosing the internet connection.
