### ISSUE TITLE
Ubuntu 20.04 new install chia gui

### ISSUE THREAD

**Issue by meaverick** [Chia-Network/chia-blockchain#5183]
Ubuntu 20.04 new install chia gui, please help

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'electron' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose stack Error: ENOENT: no such file or directory, open '/chia-blockchain/package.json'
5 verbose cwd /chia-blockchain
6 verbose Linux 5.8.0-53-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
8 verbose node v10.19.0
9 verbose npm  v6.14.4
10 error code ENOENT
11 error syscall open
12 error path /chia-blockchain/package.json
13 error errno -2
14 error enoent ENOENT: no such file or directory, open '/chia-blockchain/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

**Comment by meaverick** [comment]
(venv) root@chia:/chia-blockchain# chia stop -d all
Daemon not started yet
Couldn't connect to chia daemon
(venv) root@chia:/chia-blockchain# ps -Af | grep chia
avahi        665       1  0 15:01 ?        00:00:00 avahi-daemon: running [chia.local]
root       31311    2322  0 16:08 pts/0    00:00:00 grep --color=auto chia

**Comment by turekjiri** [comment]
Delete your chia folder and reinstall it.

**Comment by meaverick** [comment]
reinstall 20.04 ubuntu again when i run "sh install-gui.sh" get following erro

> yarn@.22.10 preinstall /chia-blockchain/chia-blockchain-gui/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)


> electron-winstaller@5.0.0 install /chia-blockchain/chia-blockchain-gui/node_modules/electron-winstaller
> node ./script/select-7z-arch.js

Selecting 7-Zip for arch x64
/chia-blockchain/chia-blockchain-gui/node_modules/electron-winstaller/script/select-7z-arch.js:16
    throw err;
    ^

Error: EACCES: permission denied, copyfile 'vendor/7z-x64.exe' -> 'vendor/7z.exe'
    at Object.copyFileSync (fs.js:1728:3)
    at Object.<anonymous> (/chia-blockchain/chia-blockchain-gui/node_modules/electron-winstaller/script/select-7z-arch.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-winstaller@5.0.0 install: `node ./script/select-7z-arch.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-winstaller@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-16T10_29_47_554Z-debug.log

**Comment by turekjiri** [comment]
https://www.reddit.com/r/chia/comments/ma7nwx/issues_with_installation_on_ubuntu/ :
"You are probably running the installation process as root user.
Checkout the installation docs, it explicitly states: "You can not install and run the GUI as root".
So retry the process again as a non-root user and it should work.
The errors in the initial question didn't come up again, when I re-ran the installation as a non-root user."

**Comment by meaverick** [comment]
You are correct and Thank you. The guide should insert sudo for gui install

**sudo** sh install-gui.sh

**Comment by meaverick** [comment]
sudo sh install-gui.sh
