### ISSUE TITLE
[BUG] Accepting a coloured coin fails in dev

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#519]
**Describe the bug**
Upon accepting an offer, there seems to be a type error when accepting.

**To Reproduce**
Un gzip the attached offer and attempt to accept the trade.
See the error screen shot.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/30377676/98676315-4d675a80-2310-11eb-9b1e-c8d94fab38ad.png)

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

[Grich-coin.gz](https://github.com/Chia-Network/chia-blockchain/files/5517332/Grich-coin.gz)

**Comment by jespino** [comment]
Tried it and I'm getting the error `Given G2 element must always have 48th byte start with 0b000`. not the shown one.
