### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KeimaTenryuu** [Chia-Network/chia-blockchain#5190]
**Describe the bug**
Every time I try to plot about 3 or 4 in parallel, the 1st and second plot get bugged and don't plot properly after about 30% for the 1st plot and the 2nd plot varies but that one also gets bugged and would stop plotting. The 3rd plot usually does fine but feels slower

![messed Chia plotting 3](https://user-images.githubusercontent.com/84268552/118393151-7e18ab80-b635-11eb-81f1-dc3855e9b0d5.jpg)

- OS: Windows 10
- CPU: [e.g. AMD Ryzen 7 3800XT 8-Core Processor 3.90 GHz

The settings I'm using are all default except I'm using 4 threads and I'm using a 1TB external NVMe

**Comment by maxmamort** [comment]
Same thing on Ryzen 2700X for me. No problem at all on all intel platform on my side

Everything default, windows 10 pro, plotting on 3 tasks on 3 different temp drives
