### ISSUE TITLE
VDF Client: Got stop signal before completing the proof!

### ISSUE THREAD

**Issue by yancymsg** [Chia-Network/chia-blockchain#5193]
I haven't received any rewards in my wallet recently ，Current cultivation size 2P ，There is no reward for 3 days ，
Wallet status syncd。

log print：
VDF Client: Sending proof
VDF Client: Sent proof
VDF Client: Running proving for iter: 12066291
VDF Client: Got stop signal!
VDF Client: Got stop signal before completing the proof!
VDF loop finished. Total iters: 10220676
VDF Client: Got stop signal before completing the proof!
VDF Client: Got stop signal before completing the proof!
VDF Client: Got stop signal before completing the proof!
VDF Client: Got stop signal before completing the proof!
VDF Client: Got stop signal before completing the proof!
VDF Client: Stopped everything! Ready for the next challenge.

what is the impact of this？

**Comment by miwi-fbsd** [comment]
facing the same, any idea?

**Comment by M3dS0** [comment]
Same here!
I've no idea what is it but maybe it's about the wining process, I mean maybe the current plots isn't enough to win, so they send the stop signal, in continue to that message chia prints this message:
"Not skipping peak, don't have. Maybe we are not the fastest timelord"

I don't know if they're related.

**Comment by miwi-fbsd** [comment]
Yea, Kind of weird that nobody else gives feedback..

**Comment by JsBlueCat** [comment]
same problem

**Comment by M3dS0** [comment]
it is so cool no one have the answer for this, I've searched everywhere for the answer but no luck!

**Comment by miwi-fbsd** [comment]
strange also that none of the devs feels like answering this :)
