### ISSUE TITLE
Exception from 'wallet' [BUG]

### ISSUE THREAD

**Issue by CocoaPriest** [Chia-Network/chia-blockchain#5195]
**Describe the bug**
Running
`❯ chia wallet show`

returns unclear message
```
Exception from 'wallet' {'error': "b']\\xf2\\xe0=\\x9b:\\x13$5\\x02\\xbaN\\xefz}K\\x195\\xcb*t\\x86\\xaf\\x04\\x07\\xd0Cq\\xdd\\xcd\\x08\\x01'", 
'success': False}
```

**To Reproduce**
chia wallet show

**Expected behavior**
A clear error message

**Desktop (please complete the following information):**

- OS: macOS
- OS Version/Flavor: BigSur 11.3
- CPU: Intel Core i7

**Comment by komitov** [comment]
I have a very similar error with Rocky Linux release 8.3 and FreeBSD 13 (with mnemonic key import)

**Comment by komitov** [comment]
Exception from 'wallet' "b'\\x83-[\\...(some more sequences)\\x91:\\x96'"

**Comment by komitov** [comment]
1.1.7 fixed this issue for me.
