### ISSUE TITLE
[BUG] Not synced from few days ago

### ISSUE THREAD

**Issue by inigosola** [Chia-Network/chia-blockchain#5196]
**Describe the bug**
I get `Not synced` message after try to sync.

**To Reproduce**

1. Run GUI
2. Wait for it 

**Expected behavior**
Sync

**Desktop (please complete the following information):**

`Linux pop-os 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux`

Chia version (latest): `1.1.5`

I have rebooted pc several times. I have installed latest version. I have checked clock sync. I have removed `.chia` folder and run `chia init`.

**Comment by jakub-polak** [comment]
Try to run `tail -F ~/.chia/mainnest/log/debug.log | grep "WARNING\|ERROR" -A 5`

Are there `RuntimeError: Weight proof did not arrive in time from peer X.X.X.X` errors?

**Comment by inigosola** [comment]
I get the following messages when I run chia gui:

```
chia-blockchain@ electron /home/user/chia-blockchain/chia-blockchain-gui
> electron .
/home/user/chia-blockchain/app.asar.unpacked/daemon
false
Error loading config - using defaults
startUrl file:///home/user/chia-blockchain/chia-blockchain-gui/build/renderer/index.html
/home/user/chia-blockchain/app.asar.unpacked/daemon
false
/home/user/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../chia/daemon/server.py
child process success
(node:17570) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

Not synced and "blocks" section does not load (spiner does not finish).

> Try to run `tail -F ~/.chia/mainnest/log/debug.log | grep "WARNING\|ERROR" -A 5`

`~/.chia/mainnest/log/debug.log` does not exist


> Are there `RuntimeError: Weight proof did not arrive in time from peer X.X.X.X` errors?

**Comment by jakub-polak** [comment]
Sorry for the typo - it should go `tail -F ~/.chia/mainnet/log/debug.log | grep "WARNING\|ERROR" -A 5`

**Comment by inigosola** [comment]
> Sorry for the typo - it should go `tail -F ~/.chia/mainnet/log/debug.log | grep "WARNING\|ERROR" -A 5`

```
2021-05-16T15:21:25.793 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-16T15:25:47.750 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/full_node/full_node.py", line 628, in _sync
    raise RuntimeError(f"Weight proof did not arrive in time from peer: {weight_proof_peer.peer_host}")
RuntimeError: Weight proof did not arrive in time from peer: 210.20.188.237
```

What about my preious meessage? (app.asar.unpacked/daemon false) is it wrong?

Thank you very much!

**Comment by jakub-polak** [comment]
I have the same issue since couple of days...

**Comment by korobov-e** [comment]
> I have the same issue since couple of days...

do u solve it?

**Comment by jakub-polak** [comment]
> > I have the same issue since couple of days...
> 
> do u solve it?

No 😭 😭 😭

**Comment by xy00869474** [comment]
same i too
