### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by Marigold5** [Chia-Network/chia-blockchain#5199]
As of 1220 BST (1120 UTC) Sync stopped. There is no apparent reason for this.
My router has port forwarding on 8444. Sync has worked fine since that was set a couple of weeks ago.
As far as I can tell, my ISP (Vodafone) has not suddenly switched on the IP sharing protocol.
There are two nodes operating via this router (mine and my son's), both have lost sync. His isnt even plotting, just two farm plots.
However my 206 plots are a more serious (to me) matter.
The only two reasons I could find in help are port and IP sharing.
HELP PLEASE

**Comment by Marigold5** [comment]
PANIC OVER...sync re-established...still mystified as to why it dropped though. First time it has happened to me since 8444 was opened

**Comment by Redlumxof** [comment]
Seguramente tu y yo tenemos el mismo problema, cuantas conexiones tienes en tu nodo ?
menos de 10 ?
