### ISSUE TITLE
Chia stuck on 'connecting to wallet'

### ISSUE THREAD

**Issue by Russell217** [Chia-Network/chia-blockchain#5210]
I shut down the GUI and reopened it. now the GUI will not open at all.
Is it possible that the GUI got corrupted?

**Comment by arielk3998** [comment]
Similar issue, except I did not even shut it down.

**Comment by Alan911Black** [comment]
mine also, its when i over work the computer and use its max... the GUI is not connecting just spinning. it was like that in the earlier version. sometime i am able to get some plots out. because i think its still working at the background

**Comment by la-mikkamakka** [comment]
Same here, overnight it just got stuck on connecting to wallet spinning screen. Tried to refresh page, restart Chia, restart computer, but nothing is working.

**Comment by Alan911Black** [comment]
you can save the plots, look at what is running and let it finish. i just saved 4 plots

**Comment by srf81** [comment]
My power went out during the build and thats when I reopened and the GUI is also stuck on connecting to wallet and circling. Uninstall and reinstall didn't work.

**Comment by markecx** [comment]
I got the same issue and the Windows GUI is stuck on Connecting to wallet. I've tried creating 3 plots at the same time and it was working fine (but really slow) until I switched the tabs and when I tried to go back to the farming tab, the issue happened. I will leave the pc on while I'm at work as I can see that the chia processes are still running in the Task Manager

**Comment by PavelUvarov** [comment]
after the next opening of the wallet, hang on the connection

**Comment by camun0** [comment]
Same problem, solved deleting .chia folder and chia-blockchain, reboot and reinstalling chia.

**Comment by ruanye** [comment]
same problem

**Comment by mcbrian710** [comment]
> 
> 
> Same problem, solved deleting .chia folder and chia-blockchain, reboot and reinstalling chia.

Tryed this several times. on Windows didnt work. Whitch is the .chia folder?

**Comment by la-mikkamakka** [comment]
You probably have to do a win registry scrub too to get rid of previous chia entries.


Will try that tonight. Thanks


Sent from my T-Mobile 5G Device

Get Outlook for Android

**Comment by killerfrost22** [comment]
Same issue here but resolved!
Steps tried:
1. Exit the chia blockchain GUI completely
2. Delete these folders:
C:\Users\yourusername.chia
C:\Users\yourusername\AppData\Local\chia-blockchain
C:\Users\yourusername\AppData\Roaming\Chia Blockchain
3. restart the GUI

**Comment by ruanye** [comment]
mac gui  has  same problem  how to  fix it

**Comment by niutao** [comment]
mac gui has same problem how to fix it

**Comment by markecx** [comment]
In my case I just restarted the PC and it came back. The only thing I lost was the plotting progress.
