### ISSUE TITLE
[BUG] Deleting plot issue

### ISSUE THREAD

**Issue by nikredrec** [Chia-Network/chia-blockchain#5215]
**Crashed while deleting plot**
Crashed twice in one week while trying to delete the plot while plotting, and all active plots gone!

**To Reproduce**

1. Clicked on delete
2. Showed "removing"
3. Then crashed - showed "connecting to wallet" or  "reconnecting to wallet" 
4. Couldn't reconnect so I closed it and open again, all active plots were gone!

**Expected behavior**
Not to crash.

**Screenshots**
No error to show, it just crashed and tried to reconnect.

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Windows 10
- CPU: AMD Ryzen 7, 32gb RAM

**Additional context**
Currently using 1.1.4, will update to 1.1.5 and hope I will not loose any more plots.

Best regards, and have a great week!

**Comment by nejat76** [comment]
GUI is full of bugs... It's better to use a plot manager for plotting... if you want to cancel one then you note the process id of the plot process and kill it... 1.1.5 also has the same bug...

**Comment by BluefireXD** [comment]
Confirmed. Deleting plots is still buggy in 1.1.5

**Comment by wbendick** [comment]
post your log
