### ISSUE TITLE
Serious problem in chia money transfer.

### ISSUE THREAD

**Issue by avitron78** [Chia-Network/chia-blockchain#5216]
In my history it appears that I have received 1,739 chia but they have not been added to my wallet. Neither does a transfer that I made of 0.011 chia appear to another wallet which was accepted. 

My account balance should be : 3,7390000001 XCH
I currently have 2,0000000001 XCH

![chia](https://user-images.githubusercontent.com/84282684/118404249-05801200-b66a-11eb-83c0-d59e9b4332a3.JPG)

- OS: WINDOWS 10 x64
- CPU: Ryzen 7
-

**Comment by avitron78** [comment]
Here is the same account but on my other computer, in this one if the transfer of 0.011 XCH appears
![chia2](https://user-images.githubusercontent.com/84282684/118404903-d5863e00-b66c-11eb-88a3-44f23ecf652f.JPG)

**Comment by rleitaob** [comment]
Hello are you using a third party pool or just the official platform?

**Comment by avitron78** [comment]
Thanks for answering, no, I'm farming alone, I don't use any pool.

**Comment by rleitaob** [comment]
Was the CHIA you won a return from your plots or was it an effect of luck?
How many plots do you already own?
I am sorry for the question, I want to understand if it was the luck factor that made you obtain the CHIA, or if it was the results of your plots.

**Comment by avitron78** [comment]
I haven't bought chia, all that I own has been won with 259 plots. Approximately one month. :)

**Comment by rleitaob** [comment]
ok! Thanks for the clarification!

**Comment by mariano54** [comment]
You only won 1 block. You only have 2 XCH. The second wallet is showing a "change" transaction, which is a transaction to yourself, which looks like new funds received. Please read up on the UTXO model of bitcoin to understand this a little better. Sorry we have not made it very clear in the GUI.

**Comment by avitron78** [comment]
Exactly, I transferred 0.011 XCH from one account to another, but as you can see in the image they have not reached the new account and it is at 0.
![nueva_cuenta2](https://user-images.githubusercontent.com/84282684/118443001-449e7980-b6e3-11eb-886a-c8ae20764ac2.jpg)

**Comment by mariano54** [comment]
You need to be synced to see the received funds. Wait for it to reach the same height.

**Comment by avitron78** [comment]
ok Mariano54, gracias por tu ayuda.

**Comment by kruiescody** [comment]
> I haven't bought chia, all that I own has been won with 259 plots. Approximately one month. :)

How much space do you have? I’m trying to build a rig

**Comment by kruiescody** [comment]
How much have you won with 259 plots?

**Comment by kruiescody** [comment]
As long as the space is available in the computer for a k-32 plot then when it’s done you just add it to the farming protocol?

**Comment by kruiescody** [comment]
I’m trying to figure it out but my laptop is shitty and doesn’t have enough space for a plot. I’m going to start buying 18tb hard drives. I don’t understand why I need SSDs tho?
