### ISSUE TITLE
[BUG] Wallet not synced since 2 days

### ISSUE THREAD

**Issue by inigosola** [Chia-Network/chia-blockchain#5218]
**Describe the bug**
Full node status is `Synced` but wallet is not synced and it shows 0 XCH.

**To Reproduce**

1. Open chia GUI
2. I view status `Synced` in Full node status.
3. My wallet shows `0 XCH`
4. If I run `chia wallet show` I get the following:

```
Wallet height: 198653
Sync status: Not synced
Balances, fingerprint: 3387251898
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable: 0.0 xch (0 mojo)
```

`chia show -s`:
`Current Blockchain Status: Full Node Synced`

**Expected behavior**
Wallet synced

**Desktop (please complete the following information):**
`Linux pop-os 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux` 

**Additional context**
It did work fine two days ago

Log (`~/.chia/mainnet/log/debug.log`):

```
2021-05-16T19:11:27.976 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 197918-197950. Traceback (most recent call last):
  File "/home/user/chia-blockchain/chia/wallet/wallet_node.py", line 509, in sync_job
    await self._sync()
  File "/home/user/chia-blockchain/chia/wallet/wallet_node.py", line 606, in _sync
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 197918-197950
--
2021-05-16T19:18:22.897 full_node chia.full_node.full_node: WARNING  Wasn't able to add transaction with id b10f995f0a6fef4ac94cc73b00e0213ed45a9fd4784d8aea96b727fd842360b6, status 3 error: Err.UNKNOWN_UNSPENT
2021-05-16T19:21:44.735 full_node chia.full_node.full_node: ERROR    Consensus error 124, not disconnecting
```

**Comment by jh442** [comment]
I'm having the same problem. Also try deleting my wallet DB to reset that. Sometimes I see very slow progress, but sometimes not connected. Good thing I'm small time and didn't earn any chia yet!

**Comment by pangchia** [comment]
I have the same problem too.

**Comment by auzhuntr** [comment]
Have tried everything, same thing keeps happening to me. 

Chia = waste of time

**Comment by wbendick** [comment]
does the "Wallet height" increase over time?

**Comment by 035uros** [comment]
> 
> 
> does the "Wallet height" increase over time?

I have the same problem, my Wallet height increase over time. What should I do?

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
