### ISSUE TITLE
Missing incoming XCH in wallet from farming block [BUG] 

### ISSUE THREAD

**Issue by Tihon02** [Chia-Network/chia-blockchain#5220]
**Describe the bug**
Missing in the wallet 1,25ХСH Confirmed at height 288143 received after rebooting the system. 

**To Reproduce**

**Expected behavior**
Get XCH for a wallet.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please check screenshots.
![Balance](https://user-images.githubusercontent.com/84286911/118408055-61f42900-b68c-11eb-83e7-b953a21993af.PNG)
![Balance](https://user-images.githubusercontent.com/84286911/118408057-64568300-b68c-11eb-85ad-993be74c7601.PNG)
![Transaction](https://user-images.githubusercontent.com/84286911/118408060-66204680-b68c-11eb-9cfb-dc9d12835598.PNG)

**Desktop (please complete the following information):**

- OS: Windows 
- OS Version/Flavor: [10/64]
- CPU: [Intel Core i7-10700KF ]

**Additional context**

**Comment by avitron78** [comment]
I've the same problem as you, I have received 1,739xch but haven't been added to my wallet.

**Comment by Tihon02** [comment]
> I've the same problem as you, I have received 1,739xch but haven't been added to my wallet.

Support help for you with your problem?

**Comment by avitron78** [comment]
It's my problem.

https://github.com/Chia-Network/chia-blockchain/issues/5216

I'm waiting for some solution too.

**Comment by meaverick** [comment]
i have receive 0.75 xch but not added to my wallet. but another 2 xch no problem.
<img width="655" alt="xch" src="https://user-images.githubusercontent.com/2944598/118445346-e7c1b400-b720-11eb-8620-526f3ab3fea5.png">

**Comment by mariano54** [comment]
These transactions are change transactions, they are not new coins that you received. Please read up on Bitcoin's UTXO model, which is similar to Chia's. We will be adding more guides explaining what change transactions are in the future.
