### ISSUE TITLE
Error while moving plot from temp storage to NFS share

### ISSUE THREAD

**Issue by Rukahs** [Chia-Network/chia-blockchain#5236]
When moving files from local storage to NFS share permissions cannot preserved and throws an error, but the move completes successfully. NFS client is linux and NFS server is FreeBSD. client can read/write correctly to the NFS share.

The chia plotter sees the error and throws error message saying cannot copy, retrying in 5 minutes. Never finishing the plot.

python open() and file.write() commands work correctly. 
shutil.move() throws an exception and does not move the file. (I think this is the problem)
shutil.copy() does move (copy) the file successfully with no errors.

**Comment by JuEnPeHa** [comment]
Its lost, It happen to me, plots lost if the connection fail for a little bit.

**Comment by Rukahs** [comment]
Connection to NFS share is never interrupted, and connection to the TMP storage is never interrupted. 
Plotter just errors (i think on the inability to preserve file permissions) and re-tries in 5 minutes... continuously.

I skimmed through create_plots.py but didn't see where it does the final move from tmp storage to destination.
