### ISSUE TITLE
[BUG] Sync problem

### ISSUE THREAD

**Issue by potato1992** [Chia-Network/chia-blockchain#5238]
I fully understand that there are so many reasons that can cause the **not sync** situation. 

But, when I try to connect to one peers, even another peer owned by myself, nothing happens at all. Can you just put some log on the GUI to show what the hell have happened?????? 

Do you really have product manager? Please be serious, this is not school homework.

**Comment by Chiqui1234** [comment]
My Chia GUI says "Not synced" and the log says:

```bash
2021-05-16T20:10:14.596 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection None. Traceback (most recent call last):
  File "chia\server\server.py", line 531, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError
```

Python error?

**Comment by paritad99** [comment]
i same you guy, i install python 3.7 not error

**Comment by sky168888** [comment]
i got same problem, i delete .chia folder and re-launch again. start syncing again and see what happen after fully sync.

**Comment by Chiqui1234** [comment]
Ok, I removed all inside .chia/mainnet, except wallet's folder. The GUI is slow and weird, so I'm moving back to CLI.

```bash
chia show -a chiadb.net:8444
```

This add chiadb.net as a peer. After 5 or 10 minutes it starts syncing :)
Then, you can check the blockchain sync with

```bash
chia show -s
```
