### ISSUE TITLE
Loosing synch at same time every day [BUG]

### ISSUE THREAD

**Issue by KaAProjekt** [Chia-Network/chia-blockchain#5248]
**Describe the bug**
It seems like my internetprovider is resetting my connection every night between 3:50am and 4am.
I will loose synch after that (which seems okay), yet after being connected again, node stays "not synched" for 5 and more hours.

When I close the node completely and restart it, it eventually gets synched and is fully online again after 10-15 Minutes.

I have had restarts of the router during the day without any issues related to synching, or after shortly loosing synch being reconnected by the node itself. But it does not recover itself at that specific time.

I mean, why can node recover a regular disconnection/reset but not that one during the night? 
Is there any way to get the node to correct this issue? Even just pressing reload on node doesn't do anything. Only thing that works is the shutdown and restart of node.
It's a giant pain in the butt to loose synch in the midle of the night and needing to manually restart node every night.

This issue seems to occur only with the version 1.1.4/1.1.5 ; before I had some disconnects and not being synched, but node recovered itself all the time.

**To Reproduce**

- OS: [Win 10 Pro 64]
Using GUI for windows

**Comment by boombel666** [comment]
i have the same problem. does anyone know how to fix it ?

**Comment by Tom29a** [comment]
Maybe a fix ip adress can help

**Comment by KaAProjekt** [comment]
> 
> 
> Maybe a fix ip adress can help

Was one of my first thoughts as well, yet doesn't seem to work...
