### ISSUE TITLE
[BUG] Lost coin

### ISSUE THREAD

**Issue by zoquile19901228** [Chia-Network/chia-blockchain#5251]
I can still view the unsettled rewards on May 15, 2021, but when I go online at 4:00 p.m. on May 16, 2021, I find that the income is gone. May I ask if the account is blocked or displayed incorrectly? Account number: 418094790@qq.com

Block coverage: 283550，283520，283500，283430

**Comment by nuistzj2014** [comment]
the same as you , you can search whether having transaction informations or not!

**Comment by zoquile19901228** [comment]
> 和你一样，你可以搜索是否有交易信息！
There is no transaction information.
