### ISSUE TITLE
No block reward

### ISSUE THREAD

**Issue by Dieria14** [Chia-Network/chia-blockchain#5261]
Hello. There was such a problem 29.04.21 knocked out the block (at the height of 201641, address xch1j8vkxknuakd6lf2guefr8qpc3g9h0d3sujycq2u55zgkyw9q9egskjg3t2) But in the nodes tab, the wallet is on balance 0, there are receipts in the history. In the farm tab, there are also received coins. What could be the problem and where to turn?

Здравствуйте. Возникла такая проблема 29.04.21 выбил блок (на высоте 201641, адрес xch1j8vkxknuakd6lf2guefr8qpc3g9h0d3sujycq2u55zgkyw9q9egskjg3t2) Но во вкладке ноды кошелек на балансе 0, в истории есть поступления. Во вкладке ферма так же есть полученные монеты. В чем может быть проблема и куда обратиться?

![Cash](https://user-images.githubusercontent.com/84122851/118440934-dfa64c00-b701-11eb-9b79-9ed54d8312d6.JPG)
![Farm](https://user-images.githubusercontent.com/84122851/118440938-e1700f80-b701-11eb-9906-6e4e8208f55b.JPG)

**Comment by handsomedude** [comment]
Well that's not fair.  I have lots more plots than you, my remaining time is half Yours and I haven't found any rewards yet!!!
