### ISSUE TITLE
Sync procedure is fundamentally broken

### ISSUE THREAD

**Issue by antst** [Chia-Network/chia-blockchain#5270]
You can see that there is a number of sync bugs and discussions. And they are appearing with increasing rate. 
I looked into it for last 2 days and outcome is simple. Once number of transactions increased, sync speed is lagging speed of grows of blockchain.

In my test which goes for last 36 hours which I started from scratch, I can't catch current block, and this is happening on hardware you can't blame: threadripper, very SSD for DB, real 1GbE connection.
This means once typical node got out of sync for whatever reasons, it is difficult to catch up. And this should be reason of this massive surge of out of sync issues.

**Comment by markusmazurczak** [comment]
What out of sync timeframe you are talking about? I am able to catch up after beeing out of sync for 6 hours easily with an old i5 processor and an low budget SSD

**Comment by antst** [comment]
To me it looks it depends on your "luck" and peers you are connected to before you reached limit of peers.

**Comment by antst** [comment]
this is example from farmer node (no harvesters)
```
Mon 17 May 2021 09:38:18 AM UTC Block Height: 275398
Mon 17 May 2021 09:42:49 AM UTC Block Height: 275405
```

47 seconds per block.

**Comment by markusmazurczak** [comment]
Ja, that sound legit. Take a look into https://github.com/Chia-Network/chia-blockchain/issues/3298. I am currently trying to hard-ban peers that I can get no connection to so that the garbage collector can remove them from ChiaServer's internal peer-list

**Comment by antst** [comment]
Also, chia_full_node is bounded by CPU, it shows 100% CPU usage, while in this terrible sync.

**Comment by antst** [comment]
Another thing I see from logs, I am feeding known blocks to other nodes with speed of light, but this also, probably, one of reasons at CPU bounding.

**Comment by leefarg** [comment]
I echo this same problem - got out of sync a few days ago, and unable to regain sync. After restart multiple times and complete db delete, in 24 hours, I am only a little over half-sync'd.

**Comment by antst** [comment]
One more thing, looks like sometimes it just getting stuck on particular block, I presume, waiting something from particular peer and not getting

**Comment by tojefest** [comment]
> Ja, that sound legit. Take a look into #3298. I am currently trying to hard-ban peers that I can get no connection to so that the garbage collector can remove them from ChiaServer's internal peer-list

at this moment this solution work... I think this only peers problem. If i have luck, sync work great, bad peer and not synced for 6hours. Synchronization is broken, totally. This isn`t problem of db, cpu or ssd, network. Only app have big problem. Manually wallet restart can helps but it afffect farming...

**Comment by antst** [comment]
Can you point towards procedure?

**Comment by tojefest** [comment]
i work on it...
at this moment i use simply powershell script:

this is sample :)
loop
.\chia start wallet -r
.\chia.exe show --add-connection lucky_peer_ip:8444
.\chia.exe show --add-connection lucky_peer_ip:8444
.\chia.exe show --add-connection node-eu.chia.net:8444
ping -n 960 gatewayip
reloop

App looks like use only first added peer, but that is bad solution for farming.

**Comment by antst** [comment]
> i work on it...
> at this moment i use simply powershell script:
> 
> this is sample :)
> loop
> .\chia start wallet -r
> .\chia.exe show --add-connection lucky_peer_ip:8444
> .\chia.exe show --add-connection lucky_peer_ip:8444
> .\chia.exe show --add-connection node-eu.chia.net:8444
> ping -n 960 gatewayip
> reloop
> 
> App looks like use only first added peer, but that is bad solution for farming.

What speed of sync you have in this case? number of seconds per block

**Comment by antst** [comment]
> 40s per block as long as i`m lucky

it is still slower than chain grows.

**Comment by antst** [comment]
Protocol and software are terminally ill.
If chia will remain popular another week, that's will be end of it :)

**Comment by antst** [comment]
I managed to squeeze to 2 seconds per block (even less), but I will not even publish this, as this will kill it all, once gets out into the wild.

**Comment by tojefest** [comment]
Yes,
but as i said:
that only one solutions work for me to stay synced. Some peers look like zombie, architectural for p2p mistakes, and stupid app for full node connections.

**Comment by antst** [comment]
> Yes,
> but as i said:
> that only one solutions work for me to stay synced. Some peers look like zombie, architectural for p2p mistakes, and stupid app for full node connections.

There is more to that.
In fact, bad peers alone will not kill average sync speed, from what I see. Other stuff combined with bad peers - this is what kills.

**Comment by markusmazurczak** [comment]
> Protocol and software are terminally ill.
> If chia will remain popular another week, that's will be end of it :)
> It looks like there are architectural mistakes.

Would you share your thoughts about the architectural mistakes?

**Comment by antst** [comment]
It looks like you either pull or give, once you share to peers who has less than you, your own sync suffers a lot. There is architectural bottleneck somewhere in the software. Most likely, this is related to CPU bounding I see.
But if people will stop to share, then chia is as good as dead.

I am approaching 1s/block sync speed with quite specific setup. Which is decent. But then again, if/once number of transactions grows 20-fold, then nobody can keep up, from looks of it :)

**Comment by antst** [comment]
From what I see also, most of people who suffer from sync issue (I've seen so far) are from Europe, where people started to get on board later, so there is huge pool of people who wants to get synchronized, and, possible, they are introduced to "closest" European peers as shortest route, which kills it for Europe ;)

**Comment by tojefest** [comment]
libtorrent works better in eu:)

**Comment by Noodleyman** [comment]
Having kept a real close eye on it today, the past 12 hours I've only been able to successfully farm for 1 hour. "Not Synched", even though the connection to peers are established. then randomly it'll sync, farm for a short while and die again.  Trying all the tricks listed, manually connecting, clearing the historic connection data etc isn't working that well anymore. 

Getting a little frustrated with it, making me wonder is there any point continuing to plot at the moment. As more users join the network, it'll creek further until it dies unless something is urgently done to fix the issue. It's pointless plotting if you can't farm your plots reliably...

**Comment by antst** [comment]
> Having kept a real close eye on it today, the past 12 hours I've only been able to successfully farm for 1 hour. "Not Synched", even though the connection to peers are established. then randomly it'll sync, farm for a short while and die again.  Trying all the tricks listed, manually connecting, clearing the historic connection data etc isn't working that well anymore. 
> 
> 
> 
> Getting a little frustrated with it, making me wonder is there any point continuing to plot at the moment. As more users join the network, it'll creek further until it dies unless something is urgently done to fix the issue. It's pointless plotting if you can't farm your plots reliably...
> 
> 
> 
>  

Thus is what happening for for 2 weeks already, once network hit bigger.

And yes, bigger it is - lower chance it will work.
What kills is exactly number of peers which tries to synchronize. If number non-synchronized users will grow above some limit - then they will kill the rest of network by their sync attempts.

Unsync peers pulling from you blocks kill your full_node and it can't keep up with network anymore. Then it gets some air to breeze, sometimes manages to get in sync, but then again killed, as becoming attractive to pull fresh blocks. 
Effectively, in current form network pulls everyone to the "average" height, not to maximal.
Miss-design of software. In fact, total separation of in- and out- with meaningful synchronization would solve it.

**Comment by grasuu** [comment]
Same here ...
In the last 24 hours my Full Node was not able to catch up ... it does not stop completely but runs (almoust exactly) 90 minutes behind.
Like Noodleyman I tried "all the tricks listed", without success. And my setup did work since release of 1.1.5.
Yep, located in Europe, too.

**Comment by antst** [comment]
We need a team to write new implementation, as I doubt we can get much further with current one. Performance target was completely missed.

**Comment by antst** [comment]
With my test setup I managed to get sync speed as low as 1.107 sec per block so far (at the end of chain, with fattest blocks). Despite of doing nothing specific about "bad peers".
So, bad peers aren't a real problem.

**Comment by Noodleyman** [comment]
I've tested connecting direct to a friend also running Chia, connected.. no bandwidth or latency issues between my machine and his. he's up to date. it just can't seem to process the data fast enough to get in sync.

**Comment by antst** [comment]
> I've tested connecting direct to a friend also running Chia, connected.. no bandwidth or latency issues between my machine and his. he's up to date. it just can't seem to process the data fast enough to get in sync.

Yep. CPU bottleneck.

**Comment by Noodleyman** [comment]
hmmm.... well, that could be an issue. will test bumping the CPU priority of the app.

**Comment by antst** [comment]
Just bumping up priority will not give you much.

**Comment by Noodleyman** [comment]
I wish. I'm not following why it's now an issue. I've been plotting and farming just fine until the past few days with no config changes. so I guess the trade off would be plot less to actual be able to farm... or, offload the farming to another machine as a test..

**Comment by antst** [comment]
> I wish. I'm not following why it's now an issue. I've been plotting and farming just fine until the past few days with no config changes. so I guess the trade off would be plot less to actual be able to farm... or, offload the farming to another machine as a test..

I also was plotting and farming for a month. At some point we stopped to keep up with network.
Surge of chia users in EU, who needs to get synchronized and introduced to our (former in sync) nodes killed our nodes. And now neither we nor they can get in sync back :) It is irrelevant to plotting, as I tested with "just farming" node (ie wallet and farmer, no harvester or plotting).

**Comment by antst** [comment]
And, BTW, all stories about "fast sync" comes only because majority of blocks still has no transactions :)
In a 1-2 months it will take at least a week to synchronize from scratch in ideal conditions (ballpark estimation).
Think about what will happen by the end of year :)

**Comment by m1kaj** [comment]
Same experience for me , located in EU, (win 10 , 1.1.5, gaming PC with 32GB RAM, SSD). I was running fine for many weeks, plotting and farming on same PC. 3-4 days ago I made the fatal mistake and wiped my database, thinking I can easily re-sync just like I did earlier. After days of trying all tricks, I cannot get synced. I stay 30-90 minutes behind, it seems. In the beginning I had 15-30 minute periods of getting synced, usually after restarting all Chia services or adding good connections manually. I haven't been plotting at all during this out-of-sync time.

**Comment by antst** [comment]
Yep, current implementation pulls everyone to "average block height" as I told :)
Even if you would not wipe, there is a good chance you'd get out of sync today/tomorrrow.

**Comment by antst** [comment]
My test sync is now 35 min behind "current". Let see )

**Comment by antst** [comment]
OK, there is something else fundamentally sick. Apparently "bad peers" help you to get out of sync. Due to delay of block from bad peer, node get on hold just enough to unable to catch up because of performance bottleneck after delay.

**Comment by Noodleyman** [comment]
I managed to get within 15 mins of current block, and now back to not synced and progress ended. so will sync up to 15 mins in the past and can't get much further, so will have to go peer hunting. it shouldn't be this hard...

**Comment by antst** [comment]
I truly hope it not someone on a purpose screw up everybody else.
As once I approached  approximately 30 min mark, amount of "holding due to bad peer" suddenly increased. And those delays suddenly got longer.

**Comment by antst** [comment]
"~1024 blocks behind" is magic limit and a dead end.
I have 270 peers which are further in chain than me, and they can't serve me newer blocks. Or, to be exact, they serve exactly with the same rate as chain grows. taking into account 270 peers, I doubt it number of bad peers, as the rest would let me to catch up. They must be just bottlenecking, all of them :)

**Comment by Noodleyman** [comment]
So, in theory and so sum up...
<insert wobbly sausage meme> 

:)

**Comment by antst** [comment]
OK, I got to 15 min mark :)

**Comment by antst** [comment]
OK, restarting with debug level "warn" instead of info, as I afraid debug output adds to bottleneck.

**Comment by tojefest** [comment]
how and where you change peer limit?
does anyone changed something in config.yaml?
  num_sync_batches: 50
  peer_connect_interval: 60
  recent_peer_threshold: 6000

**Comment by Noodleyman** [comment]
well, I got with 15 mins.. and now back to over 30 mins behind. I guess it's luck of the draw at this stage. a case of the intake of new users in such volume over a small space of time, means the network topology can't seem to cope. (or so I am guessing). I should probably go do some more in depth debugging...

**Comment by antst** [comment]
target_peer_count

**Comment by antst** [comment]
519 blocks mark, hanging again...

**Comment by antst** [comment]
time of those delays rapidly increases once you get close to "current".
they were at max 10 seconds back in time, then were about 2 min at ~4000 blocks mark, now they are about 10 min at ~500 blocks mark. 
If it is no "evil on purpose" then those nodes which are in sync hits bottlenecks at scale.

**Comment by antst** [comment]
128 blocks behind. stuck again.

**Comment by antst** [comment]
1st conclusion. full_node should be NEVER used with loglevel=INFO. Just NEVER. Those people create problem for themselves and for everybody else. As enabling INFO immediately introduces performance cap. As simple as that.

**Comment by tojefest** [comment]
-1: always
    log_level: WARNING

**Comment by antst** [comment]
stuck again at "85 blocks behind" :)

**Comment by antst** [comment]
> -1: always
> log_level: WARNING

It is not about what you run. it is about what some peers run. There are number of advices and additions to chia which recommends INFO.

**Comment by tojefest** [comment]
ok, now i understand

**Comment by antst** [comment]
so, end of story. at "-77 blocks mark" I have 108 active peers, all of them have newer blocks, but ALL of them gave me
```full_node chia.full_node.full_node: WARNING  Invalid response for slot None```

**Comment by antst** [comment]
literally, ALL of them refused me

**Comment by tojefest** [comment]
2021-05-17T20:03:21.395 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:21.398 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:21.400 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:31.390 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:31.582 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:31.727 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:31.729 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:31.731 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T20:03:31.981 full_node chia.full_node.full_node: WARNING  Invalid response for slot None

**Comment by tojefest** [comment]
and multi:
full_node full_node_server        : WARNING  Banning xx.81.175.114 for 600 seconds

**Comment by antst** [comment]
> and multi:
> full_node full_node_server : WARNING Banning xx.81.175.114 for 600 seconds

How do you see those?

**Comment by antst** [comment]
still managed to get to "-65".
But now every few blocks there is a delay for about 5-10 min. With this rate, with my modified setup which seriously pushes to get it all (and accepts only peers which has something to offer and do not waste resources on sharing)

**Comment by tojefest** [comment]
> > and multi:
> > full_node full_node_server : WARNING Banning xx.81.175.114 for 600 seconds
> 
> How do you see those?

from debug.log file

**Comment by antst** [comment]
> Banning

ah, yes.

**Comment by antst** [comment]
-55

Now delay is happening every second block. 
I presume few blocks further it will happen every block and time will grow, which means "current" will be reachable only in theoretical limit of infinite time )))

**Comment by Noodleyman** [comment]
> so, end of story. at "-77 blocks mark" I have 108 active peers, all of them have newer blocks, but ALL of them gave me
> `full_node chia.full_node.full_node: WARNING Invalid response for slot None`

and from my log also:
2021-05-17T19:12:36.042 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T19:12:36.059 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T19:12:36.184 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T19:12:36.185 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T19:12:36.358 full_node chia.full_node.full_node: WARNING  Invalid response for slot None
2021-05-17T19:12:36.553 full_node chia.full_node.full_node: WARNING  Invalid response for slot None

So, nothing we can really do from a client perspective at the moment. ruled out a CPU issue on my rig. we're at the mercy of the peer we connect to and IF that peer wants to give away some data.

I'm  not sure how this would improve at the moment, if those peers who are fully in sync are being bottlenecked, then they are just going to get worse as more machines come online.

**Comment by antst** [comment]
nope, it is, but at this point on their side :)
1) CPU limit does makes it slow to get to "proximity to current" on syncing client side. 
2) if local limit is removed, you hit CPU limit of peers who are "on the edge" and we can do nothing about it, indeed,

**Comment by antst** [comment]
I am at "-39" now.

**Comment by antst** [comment]
what is happening, I need to get lucky that one of peers will respond. So, it is keeping to go through the list of peers (10 seconds per each) till it gets.

**Comment by antst** [comment]
"-6" seconds mark! :)

**Comment by antst** [comment]
So, all we can do is 
1) no INFO and more detailed log leves
2) reduce number of peers which are feeding from you (really bad for network)
3) set ridiculously high limit of peers
4) configure to not wait longer than 1-2 sec from peer.

**Comment by antst** [comment]
at -15 blocks mark there are only 15 peers which are better than me. And now new coming.

**Comment by Noodleyman** [comment]
which property is for the max wait time?

**Comment by antst** [comment]
so, I reached to the current.
And....not farming.
there are NO nodes which are at the edge anymore :) SO, I can not get jobs

**Comment by antst** [comment]
funny, now al nodes in my peer list show
```-SB Height:        0```

**Comment by Noodleyman** [comment]
so, that's a big **F**..  

Something is VERY wrong.....

**Comment by antst** [comment]
```FULL_NODE 14.153.77.43                            1765/8444  23309468... May 17 18:51:16      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 18.218.161.62                          50823/8444  e5c1074e... May 17 18:51:17      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 5.104.216.20                           11959/8444  b79ddedc... May 17 18:52:19      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 223.91.32.244                          65193/8444  acd9e699... May 17 18:52:14      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 178.26.141.228                         59302/8444  70f2d770... May 17 18:52:00      0.3|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 31.141.33.7                            55543/8444  0e9e4a4a... May 17 18:52:21      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 73.135.178.190                          5043/8444  ed9268b2... May 17 18:52:24      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 187.9.112.98                           65431/8444  95ece483... May 17 18:51:44      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 92.247.223.234                         43557/8444  3b564cc6... May 17 18:52:16      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 106.6.168.60                           14001/8444  6b5953dd... May 17 18:51:50      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 36.61.180.96                           16636/8444  bdbf96e7... May 17 18:52:21      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 61.152.143.65                          32448/8444  29c84b94... May 17 18:52:07      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 1.20.10.13                             20106/8444  de4f4a64... May 17 18:52:08      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 145.255.172.185                         4089/8444  754c6003... May 17 18:52:12      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 113.14.253.233                         60841/8444  aa7e7f0b... May 17 18:52:21      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 72.216.167.73                          55884/8444  56cd8b19... May 17 18:52:21      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 184.90.225.49                          50220/8444  cb36b735... May 17 18:52:22      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 125.46.169.70                           8444/8444  ef010f26... May 17 18:52:24      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
FULL_NODE 109.49.244.87                           8444/8444  f1c67678... May 17 18:52:23      0.0|0.0
                                                 -SB Height:        0    -Hash:  Info...
```
this is the best I could get :)
at the same time, I am at the edge. But it gives no fun )

**Comment by tojefest** [comment]
which property is for the max wait time?

**Comment by antst** [comment]
Have no clue. Didn't find.
