### ISSUE TITLE
[BUG] Full Node Status / Peak Time - Implausible Data

### ISSUE THREAD

**Issue by nflows** [Chia-Network/chia-blockchain#5271]
**Describe the bug**
I wanted to share some issue with you regarding the Blockchain Sync. Chia mentioned, that they hardcoded a 30 seconds timeout for proofing a block. I observed the following issues with that:
I have a 1.0 Gbit/s  (1.000 Mbit/s) connection here. If my Chia GUI "Full Node" tab gets updated it shows me currently at the peak time:  05/17/2021 11:25:05 - but my system time (freshly synced) is already at 11:25:45. This mismatch is ALWAYS above 30 seconds. 

Next thing is, why does my Wallet / Full Node shows me a Netspace about  5.851 EiB while https://www.chiaexplorer.com/ shows already  5.97 EiB. This is a huge difference no? Even if you give the chia.exe / farmer / harvester the Realtime performance via Taskmanager it doesn't affect this issues.

Now the strange thing happens: 
I watched this "Peak Time" and also my "Real Time System Time". Now it was not 30 seconds BEHIND but almost 45 seconds IN FUTURE... This is totally impossible guys! What the heck are you doing with this network?

Within 10-20 Minutes of observing you can observe / see the network to be up to 1 minute in Future and 2 minutes behind. 
How can you guarantee, that our plotting / harvesting is working correctly? This looks so unstable. 

**Expected behavior**
Peak Time shall be always within <30 seconds behind System Time, if network and system is capable to handle (performance).

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro (latest update, 10.0.19042 Build 19042)
- CPU: Core i) 10900KF
- 64GB DDR4 - 3600 
- Full Node on NVMe SSD (Samsung 980 Pro)

**Comment by shque** [comment]
Mine is also over 30 seconds. It's sometimes even 1-2 minutes. Do I need to worry about it? My friend said that port forwarding helps, but I don't have a static IP so I can't do it.

**Comment by Sabcoll** [comment]
Yeah i got IPv6 IP and can't forward ports.
this is utterly BS ...

**Comment by nflows** [comment]
I could disable IPv6 via my provider so now I'm using IPv4 - but already since 2-3 months. I don't believe it's only the protocol thing. Something is currently very strange with the Blockchain. Extreme massive growth + different number in Chiacaltulator.com and https://www.chiaexplorer.com. Currently listed as "6.10 EiB" Netspace - my Wallet / Full Node tells me (Synchronized: 5.982 EiB). 
Really? What the hell is going on here...

**Comment by akmost** [comment]
My pc is 10 mins behind. How do i fix this?
