### ISSUE TITLE
Slow sync - peer issue?

### ISSUE THREAD

**Issue by leefarg** [Chia-Network/chia-blockchain#5274]
Many people have been reporting slow sync and loss of sync with unable to resync issues over the last several days. Some have postulated that perhaps it is a "bad peers" issue.

I'm currently very slowly resyncing after losing sync a few days ago. Tried all the usual - stopping node, completely shutting down, restarting computer, deleting mainnet db and restarting, etc. Running 1.1.5 Windows GUI (issue started on 1.1.3).

I notice on my list of connections, that the top one after mine has 0.1/465.7 MiB Up/down. A few others have 0.0/0.9, 0.0/0.5, etc. And lots are at 0/0.

Is this normal operation? Should I try deleting some of the 0/0 nodes and see what happens?

Thanks.

**Comment by Tibi38** [comment]
me the same, and trying in gui to use "connect to other peers"-Button is without any results.
