### ISSUE TITLE
Version is not showed on Help > About [Debian]

### ISSUE THREAD

**Issue by rul3s** [Chia-Network/chia-blockchain#5276]
**Describe the bug**
When you go to check version on the software it shows Version 0.0

**To Reproduce**

Go to Help > About Chia BlockChain

**Desktop (please complete the following information):**

- OS: Raspbian arm64 and also Ubuntu 18.04 on amd64
- 
![chia](https://user-images.githubusercontent.com/1013395/118482121-97445980-b714-11eb-9ca9-f3bb628bebb8.JPG)

**Comment by sargonas** [comment]
This is expected behavior under Linux if you install via source from Git or if you use the "experimental GUI installer". You can do `chia version` on the CLI to get your version number if needed.
