### ISSUE TITLE
Node syncing - wallet is not syncing - what to do?

### ISSUE THREAD

**Issue by chrismikefowler1** [Chia-Network/chia-blockchain#5283]
**Describe the bug**
Wallet wont sync, the node has fully synced. I am unable to farm and i have over 100 plots!!! what do i do?

click on the wallet page.  My number is stuck at 66501, when my node is up to date - but also says not synced(thought its synced).  Ive tried reinsatalling. I've port forwarded. Ive reinstalled chia.  ive done everything ive seen online.  what can i do? Its been going on for me for 3 days.

**Comment by FSys77** [comment]
> Wallet wont sync, the node has fully synced. I am unable to farm and i have over 100 plots!!! what do i do?

Relax :-)

With your meager 100 plots your chance to win a block in the next 7 days is 2%

**Comment by chrismikefowler1** [comment]
well i dont know about that - thats good odds if true. but i'm trying to sync...is everything having this issue? i have 1 computer left thats staying synced.

**Comment by HackerSteak** [comment]
I had the Problem too, but my solution was to create Plots, i dont know why but the wallet doesnt sync if you don't have any plots on your System.

**Comment by chrismikefowler1** [comment]
i deleted the .chia folder and started over syncing.  it did not help - because not i'm at full sync on the node and again stuck at the same spot on the wallet

**Comment by chrismikefowler1** [comment]
i created a new wallet and its starting to sync - good thing i'm a baby

**Comment by casa10** [comment]
Hello,
More and more have same problem: lost synced suddendly without reason. After, difficult to synced again.
Technical support here are often same problem described.
Just hope they will find solution to this problem, because a lot can't farm well.
