### ISSUE TITLE
[BUG] Wrong rounding for percentage in progress bar

### ISSUE THREAD

**Issue by jrial** [Chia-Network/chia-blockchain#5291]
**Describe the bug**
It appears that the percentage calculation on the progress bar does scientific rounding (where .5 and up gets rounded up to the next integer). This results in plotting operations remaining "stuck" at 100%, plotting. From a user perspective, 100% means finished, so this is a bit confusing for people without a math background. Even to people who understand what's going on, it just looks weird.

**To Reproduce**

1. Create a new plot
2. Wait until it's nearly done
3. Observe that at a certain point, it will spend quite some time at 100%, while still having the status of "plotting".

**Expected behavior**
The percentage calculation should round down to the nearest lower integer. Rather than casting the result of the division to int, math.floor should be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/570247/118499453-3c682d80-b727-11eb-97e9-5865ac11d0c6.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Debian Bullseye
- CPU: Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz

**Additional context**
N/A

**Comment by torokunotame** [comment]
When 100%, it performs a copy from the temporary folder to the folder where the plots are saved.  This process is fast or slow depending on your computer and hard drive speed.

**Comment by Rascal** [comment]
But in fact it is 100%, because the plotting is done, and now the file is copied to another location.

**Comment by ramkom9** [comment]
30 to 60 min in 100% status for me using NVMe to HDD 7200rpm

**Comment by Plopsi** [comment]
Yepp, would be nice for an copy progress-indicator, but here just wait - If it takes too long check the log if there is something like retrying in 5min. That indicates that eithere the target drive is full or not available (not available mostly due to disconnected network drives).

**Comment by jrial** [comment]
I'm plotting and farming on the same disk? A move of a large file, no matter how large, just involves updating the inode table which takes a fraction of a second. Even large folder trees get copied in a fraction of a second. But moving a plot file should take over an hour? That explanation doesn't make sense.

**Comment by jrial** [comment]
Nope, same disk. But I just finished another plot, and I see what's going on. It first copies the temp file from the temp folder to the final folder, then renames the target file, and finally removes the source file. I get why you'd want to move the file prior to renaming (so it doesn't get picked up by the farmer before it's fully written when moving across disks or the network). Not sure why the move uses copy & delete though, although I may have an inkling.

Anyway, I'll close this issue. And if there's no existing issue dealing with the copy job, I'll create a new one.
