### ISSUE TITLE
[BUG] Lost coin during sending, outgoing transaction disappeared

### ISSUE THREAD

**Issue by ChiaIssue2** [Chia-Network/chia-blockchain#5297]
Hello.

I tried to send CHIA from one wallet to another.
I didn't try to reproduce it, because it can cause CHIA loss.
I did steps below:

1. I typed address of wallet2 in wallet1, amount (I think it was with dot, not with comma), and 0 transaction fee.
2.  Then I clicked "send" and appeared "Outgoing transaction". I remember that is was confirmed.
State on wallet1: balance was for example 10 - 1 = 9.
State on wallet2: balance was for example 0.
3. Then on wallet1 outgoing transaction disappeared and appeared incomming with less amount that I sent, for example 0.8.
State on wallet1: balance was 10 + what I sent + what it was in incomming transaction = 11.8.
State on wallet2: balance was 0
4. After some time I have now one less coin on wallet1 and nothing on wallet2 - to sum up, I lost 1 coin.
Also, there is no trace after outgoing transaction and there is incomming transaction which I did not start!

- OS: Windows
- CHIA Blockchain 1.1.5
If developer need more private info like address, block number and precise balance flow, please leave me priv contact.
I will be grateful for solving that - I think that I didn't do anything wrong but I lost coin...

**Comment by pesi1874** [comment]
**I got the same quesion too!** 

- I send 0.1 xch from wallet A to wallet B.At the beginning I can see the transaction log which is to my wallet B receive address, and it succeed after a while.
- But in fact, my wallet B didn't receive any xch and my wallet A loss 0.1 xch,my transaction log in wallet even gone,like nothing happened.

The only thing I can prove it is my inconing and outgoing log.
![image](https://user-images.githubusercontent.com/17676949/118531295-436b5c00-b778-11eb-9085-a1b0ed1159fe.png)

**Comment by ChiaIssue2** [comment]
Update.
Wallet2 received CHIA, but in my opinion (note for developers), transaction data is inconsistent.
Maybe remove blockchain data from wallet1 will help, but I am not an expert in changing file one by one and I can break something.
I hope that my report will be usefull.

Regards

**Comment by dobromir2** [comment]
I have the same problem. Sent 0.1/+Fee 0.0000005 and transaction stays in Outgoing for the last 9 hours. Nothing in my seccond wallet.
