### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leol4** [Chia-Network/chia-blockchain#5307]
Status: synchronization, but I still have 250000, and I only send signals to the network, but I do not receive them

![image](https://user-images.githubusercontent.com/84341741/118527562-17d17d00-b74a-11eb-99fb-bb364e1f096c.png)
![image](https://user-images.githubusercontent.com/84341741/118527610-2324a880-b74a-11eb-8437-8a6a3d28cf5e.png)

**Comment by leol4** [comment]
![image](https://user-images.githubusercontent.com/84341741/118527851-5c5d1880-b74a-11eb-9d20-39faa1a168f2.png)
now its look like this

**Comment by leol4** [comment]
My MiB Down so slow
![image](https://user-images.githubusercontent.com/84341741/118528173-b5c54780-b74a-11eb-8990-cdb0960e768e.png)

**Comment by leol4** [comment]
sometimes he hiding
![image](https://user-images.githubusercontent.com/84341741/118528288-d42b4300-b74a-11eb-87af-cce7a9e03fca.png)

**Comment by leol4** [comment]
![image](https://user-images.githubusercontent.com/84341741/118528349-e4432280-b74a-11eb-9554-720070ccfbad.png)

**Comment by inigosola** [comment]
> ![image](https://user-images.githubusercontent.com/84341741/118527851-5c5d1880-b74a-11eb-9d20-39faa1a168f2.png)
> now its look like this

I'm getting the same.

**Comment by kshyshkin** [comment]
Seems like 8444 port closed. Check it. I have see same if close upnp and disable 8444 port forwarding. When port forwarding or upnp enable on router, first row port not 8444, different as o. Your wallet and farmer.

**Comment by leol4** [comment]
> Seems like 8444 port closed. Check it. I have see same if close upnp and disable 8444 port forwarding. When port forwarding or upnp enable on router, first row port not 8444, different as o. Your wallet and farmer.

а где это посмотреть, я искал в инете, но так и не нашёл

**Comment by kshyshkin** [comment]
https://portchecker.co/

**Comment by leol4** [comment]
> https://portchecker.co/

Port 8444 is closed.
вот что выдало, как его открыть?

**Comment by kshyshkin** [comment]
В настройках роутера или активировать upnp, или если нет такой настройки port forwarding, 8444 внешний, на 8444 на ip компьютера в локальной (внутренней) сети

**Comment by leol4** [comment]
> port forwarding

![image](https://user-images.githubusercontent.com/84341741/118537595-d050ee00-b755-11eb-93eb-736426914ce6.png)
Я зашёл, upnp нету в настройках, зашёл в portforwarding, не пойму что куда писать

**Comment by kshyshkin** [comment]
Напиши модель роутера. Настройки похожи не на те

**Comment by leol4** [comment]
f660 zte

**Comment by kshyshkin** [comment]
http://online-anna.ru/remont-kompyutera-01/otkryt-port-na-routere-zte-f660.php там и upnp есть

**Comment by wbendick** [comment]
did opening the port work for you?

**Comment by leol4** [comment]
> http://online-anna.ru/remont-kompyutera-01/otkryt-port-na-routere-zte-f660.php там и upnp есть

А можешь подсказать что значит время до выигрыша в чиа????

**Comment by leol4** [comment]
я вроде открыл порта как ты говорил и только сегодня синхронизировался

**Comment by leol4** [comment]
Спасибо
