### ISSUE TITLE
[BUG] Synced and then Not Synced randomly

### ISSUE THREAD

**Issue by Spshulem** [Chia-Network/chia-blockchain#5308]
Had this issue twice. Tried nearly everything. Restarting, deleting mainnet db, reinstalling, removing nodes, adding nodes back (things like introducer-apne.chia.net:8444), port forwarding, time zone, etc.

<img width="681" alt="Screen Shot 2021-05-17 at 10 42 15 AM" src="https://user-images.githubusercontent.com/1703265/118533143-b1cb0280-b715-11eb-9893-8221d59a6a6a.png">

I will wake up some days and it goes from full synced to Not Synced. Restarting the computer a few times seems to work. The thing that worked last time was renaming .chia folder to .chia_old, getting a fresh DB open, copying and pasting the new node IP, deleting .chia and renaming .chia_old to .chia and then copying and pasting the NEW IP to the old .chia.

I'm using the GUI because I can't seem to get the CLI working.

I'm getting tired of closing and restarting all of my plots. Has anyone found a solution to fix the "not synced" without restarting Chia? Because replotting 15 plots when they're all 50% done is like one or two days wasted everytime I restart. 

Is there a way to force resync without reporting?

**Comment by KaAProjekt** [comment]
kinda having the same issue here, but no need to reboot or so. i just close the node and then restart it, try to connect to peers a couple time. after like 10 to 15 minutes you can notice some movement in the synched peak, but it still says, not synched... but it is a pain in the butt to deal with that to not loose synch for too long...

**Comment by rizlah** [comment]
I too am having this issue, just since about 4pm GMT.

I am farming on Ubuntu and its as if suddenly I lose connection to any peer that has a higher block sync than I do, all my connections appear to be to people with 0 blocks except for a few that are still synced less than I am.

If I restart the node a couple of times, eventually I get synced up again, but only to lose it again a short while later and upon investigation its the same issue.

Would be keen to understand why this suddenly started happening at about 4pm GMT.

**Comment by speeder2005** [comment]
same here. I have tried almost everything. the issue started few days ago when total netspace is 4EiB, now is 6EiB. my plots are sitting there and watching the growing.

**Comment by Spshulem** [comment]
I did something that seemed to fixed the problem this time around.

I removed all "Full Node" that had a height tied to them, and then added:

introducer-or.chia.net:8444 & chiadb.net:8444
(find the right location here: https://thechiafarmer.com/2021/04/20/syncing-problems-on-windows/)

And then I just let it sit for an hour, and it showed synced again. It came online and appears to be working. No refreshing, no restarting, just came back to life.

**Comment by speeder2005** [comment]
let me try my luck.  I am also in US west coast.  am using that introducer for a long time.

**Comment by BluefireXD** [comment]
Have the same issues. 
It seems its a bug in the software with resync after internet connection loss and a problem with the internet provider. My provider auto disconnects my internet every 24h. So after disconnect I have to add manually some peers to resync. SOmhow not all my clients have this issue. some auto resync for unknown reason.
 If you have also a 24h disconnect by your provider maybe call your provider or check your router to disable this auto disconnect.

**Comment by Kali123411** [comment]
I'm having the same problem. Was sync'd and now it randomly became disconnected and now won't get sync'd again.

**Comment by BluefireXD** [comment]
did you have a 24h disconnect by your inet provider?

**Comment by rizlah** [comment]
i do not have the internet issue that you mention, I did try adding the European introducer, but kept telling me it couldn't connect, so I have just added the NA one, lets see if that helps

**Comment by rizlah** [comment]
try adding this node chiadb.net:8444

i have added and I am syncing again, hopefully it completes

**Comment by BluefireXD** [comment]
Someone knows who is providing this chiadb.net address? It seems not to be like the "official" address node.**chia.net**

**Comment by Spshulem** [comment]
> Someone knows who is providing this chiadb.net address? It seems not to be like the "official" address node.**chia.net**

References where I got the URLs:

https://github.com/Chia-Network/chia-blockchain/issues/5028
https://github.com/Chia-Network/chia-blockchain/issues/5238

@chiqui1234 suggested the chiadb.net url

**Comment by mrchen911** [comment]
I lost internet for 5 minutes today and it wouldn't recover and sync. I had to reboot.

**Comment by sansky33** [comment]
why I just output data and never accept data??

**Comment by kruiescody** [comment]
What’s the ideal amount of storage I need?

**Comment by auzhuntr** [comment]
I've had this  same issue over and over for the last two weeks. Am over chia now

**Comment by speeder2005** [comment]
> Have the same issues.
> It seems its a bug in the software with resync after internet connection loss and a problem with the internet provider. My provider auto disconnects my internet every 24h. So after disconnect I have to add manually some peers to resync. Somhow not all my clients have this issue. some cleints auto resync for unknown reason.
> If you have also a 24h disconnect by your provider maybe call your provider or check your router to disable this auto disconnect.
> 
> Just to connect them.
> Link to my issue: #5175

not like my ISP. I was good for at least two weeks.  and I do see a lot of connected peers. just no way to get data from them.

**Comment by rizlah** [comment]
well adding chiadb.net did nothing for me, left it attempting to sync overnight and still its never catching up with itself.  It was perfectly synced for weeks.  I had 1.15 installed since it came out, never had any issue until about 18 hours ago and now it is always lagging about an hour or two behind, says its synced to 5:45gmt and its currently 7:45.  

tried stopping and restarting daemons, full_node, etc
tried rebooting
tried reinstalling

still the same, surely one of the developers will have seen how many times this has been reported and give a solution.

**Comment by wbendick** [comment]
post your debug.log

**Comment by Chiqui1234** [comment]
> 
> 
> well adding chiadb.net did nothing for me, left it attempting to sync overnight and still its never catching up with itself. It was perfectly synced for weeks. I had 1.15 installed since it came out, never had any issue until about 18 hours ago and now it is always lagging about an hour or two behind, says its synced to 5:45gmt and its currently 7:45.
> 
> tried stopping and restarting daemons, full_node, etc
> tried rebooting
> tried reinstalling
> 
> still the same, surely one of the developers will have seen how many times this has been reported and give a solution.

Post your debug.log, and just for the record, here I found some usefull chia nodes: https://chia.keva.app/

**Comment by Spshulem** [comment]
What has worked for me is to add a full node, randomly deleting nodes... and then waiting an hour or two, and it starts syncing again. I think whatever I do when I add and delete nodes forces it to resync eventually.

**Comment by qpirsel** [comment]
> Have the same issues.
> It seems its a bug in the software with resync after internet connection loss and a problem with the internet provider. My provider auto disconnects my internet every 24h. So after disconnect I have to add manually some peers to resync. Somhow not all my clients have this issue. some cleints auto resync for unknown reason.
> If you have also a 24h disconnect by your provider maybe call your provider or check your router to disable this auto disconnect.
> 
> Just to connect them.
> Link to my issue: #5175

I can confirm this behaviour. Although it seems not happening every time but when the application looses the sync it correlates with the moment my provider forces a reconnect.

**Comment by Spshulem** [comment]
This version has worked for me: https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

**Comment by rizlah** [comment]
the latest 1.1.6 build fixed this for me

**Comment by BluefireXD** [comment]
> the latest 1.1.6 build fixed this for me

Same to me. Seems i have stable connections with 1.1.6
