### ISSUE TITLE
Farming health check

### ISSUE THREAD

**Issue by Dreiser** [Chia-Network/chia-blockchain#531]
I would like to see expected wins vs. actual wins (to verify that probability matches reality) and if the farmer "skipped" any challenges (maybe wifi was down at that time and the farmer couldn't participate even though it was running)

**Comment by mariano54** [comment]
With the new consensus algorithm, there will be 64 challenges within each 10 minute slot, (approximately one every 10 seconds). Each one will have a plot filter of 512, which means only on average 1/512 plots will be eligible.  After that, the plots have to be checked to see if there actually is a proof for each one. After that, each proof has to be "lucky" and be eligible for inclusion in the blockchain. Finally, the proof has to be included into the chain by nodes.


I will post here when i have the new RPC for the farmer, so we can discuss how to implement this. Most likely the farmer can notify the UI every time a new challenge is received, and the UI can keep track of how many it got, how many plots passed the filter, and how many good proofs there actually were, in those plots that passed the filter. 

The only thing that cannot be checked by the farmer is whether the proof actually made it on chain. For this, we will have to use the full node RPC. Then you can compare expected rewards with received rewards. (As well as expected proofs passing the plot filter vs actual proofs passing the plot filter).

**Comment by Axadiw** [comment]
@mariano54 quick question - this new consensus algorithm will be implemented in beta 19, right?

if so - could you compare it to the current one? I mean how many challenges are there every 10 minutes right now.

And BTW. - wasn't chia's block time a 5 minutes (not 10 as you've mentioned above) ?

**Comment by hoffmang9** [comment]
@Axadiw Full details are here - https://docs.google.com/document/d/1tmRIb7lgi4QfKkNaxuKOBHRmwbVlGL4f7EsBDr_5xZE/edit

We used to reset the vdf every 5 minutes and rewarded 16 chia in that time period to one farmer. Now we'll reset the longer running vdf every 10 minutes and offer 32 chia in 32 sub blocks to 32 farmers in those same 10 minutes.

**Comment by Axadiw** [comment]
Soo - it would be 32 challenges every 10 minutes, not 64? Or every sub block would require 2 challenges to solve?

**Comment by hoffmang9** [comment]
it is 32 sub blocks every 10 minutes.

**Comment by mariano54** [comment]
There are 64 challenges (called signage points) every 10 mins. However, not all signage points will have winning sub-blocks. On average, each signage point will have 0.5 winning sub-blocks.

The farmer RPC now includes all the recent signage points, as well as proofs of space that have won for each signage point. So all this information can be displayed in the UI to show how the slot is progressing, and whether we have skipped any signage points. 
Pinging @seeden so he is aware of this.

**Comment by Axadiw** [comment]
ok, thanks for clarification Guys - 64 challenges per 10 minutes (on average)
But to be clear - right now (beta 18) there's one challenge every 5 minutes ?

**Comment by mariano54** [comment]
There is more than 1 every 5 minutes due to the chain having multiple tips, but maybe it's around 3-5 every 5 minutes

**Comment by hoffmang9** [comment]
A farm's response to each signage point is now shown in the GUI in Beta 26 - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta26
