### ISSUE TITLE
[BUG]Double Spend Bug

### ISSUE THREAD

**Issue by MarsRabbit666** [Chia-Network/chia-blockchain#5323]
It's cannot cancel or pending for a long time.
![1](https://user-images.githubusercontent.com/84350322/118549216-bc28e300-b78d-11eb-9cfd-fc959a6cf893.png)
![2](https://user-images.githubusercontent.com/84350322/118549219-bd5a1000-b78d-11eb-8e59-c51018d7c4cf.png)

**Comment by MarsRabbit666** [comment]
It locked me more than 9 xch ....

**Comment by MarsRabbit666** [comment]
I have not enough 80 xch , but this message is create..... and now , it's locked me 9 xch in the message pool.
When would be cancel ??

**Comment by MarsRabbit666** [comment]
and I tried to get 100 xch to pending massage, but It's still locked ..

**Comment by cai1111** [comment]
del ~\.chia\mainnet\wallet\db\blockchain*
