### ISSUE TITLE
[BUG] Bad Syncro Solved! but why i need to be -1 Minute late of the wolrd Clock to start Syncronice fast?

### ISSUE THREAD

**Issue by madjin-zz** [Chia-Network/chia-blockchain#5327]
**Describe the bug**
Node, Farmer, Wallet Not Syncroniced

**To Reproduce**
1 -Windows updated the Time on my PC.
2 - After that i started to have Problems whith Syncronization.

**Expected behavior**
Client gets Syncroniced and geting the lastest challenges.

- OS: Windows
- OS Version/Flavor: 10
- CPU: ASUS H310M ER2.0 Core i5 9400

**Solution & Workarround
I checked to another PC on my Net Running Chia node and Noted that te Clock whas diferent (-1Minute of the Wolrd Clock)
the difference of this 2 PCs its that the late clock syncroniced fast and get challenges without problems but the another its allways behind the network Blocks

** Worrys
Stay at -1 Minute the World clock 
is ok for farming?
this will make me late for the challenges?
Why we arent Advised of this Time issue in the UI or CLI?

**Comment by BluefireXD** [comment]
Hmm i checked the time right now on 4 clients. Every windows 10 client has another time (~3-4 Sek difference)
But in my case also the client with second newest time stays connected while newest time and furthest behind client are unsynced. 
In my case it seems to be also an issue with 24h disconnect of internet provider and a bug in chia which does not auto reconnect/resync after this disconnect. 

Just to connect them.
Link to my issue: https://github.com/Chia-Network/chia-blockchain/issues/5175

**Comment by nucleon-oz** [comment]
This is strange. If I understand correctly, the OP needed to adjust his time to be 1min deviation from NTP server for it to sync.
To use a poker metaphor I 'see' your worry, and raise you my concerns.
With this post, and my experience with chia sync errors as well. It 'feels' like there's a number of nodes out there with a time deviation. And all the recent resolutions with sync issues are basically race conditions. That is, if you install and your time is within those who connect - then happy days. Even if your own time is bad.
So I'm curious - what's the time tolerances with the sync process. How much deviation is allowed for sync to be successful?
How many chia nodes out there are operating with poor time sync.
Does the chia client monitor time deviations of nodes?
Should we have an NTP client in the chia install to check the time deviations, and notify the user. (I don't think chia should modify the system clock - only notify)
Given the number of posts here on git with sync in the subject. I think this is a significant issue to look into.
Any thoughts appreciated.

**Comment by BluefireXD** [comment]
> This is strange. If I understand correctly, the OP needed to adjust his time to be 1min deviation from NTP server for it to sync.
> To use a poker metaphor I 'see' your worry, and raise you my concerns.
> With this post, and my experience with chia sync errors as well. It 'feels' like there's a number of nodes out there with a time deviation. And all the recent resolutions with sync issues are basically race conditions. That is, if you install and your time is within those who connect - then happy days. Even if your own time is bad.
> So I'm curious - what's the time tolerances with the sync process. How much deviation is allowed for sync to be successful?
> How many chia nodes out there are operating with poor time sync.
> Does the chia client monitor time deviations of nodes?
> Should we have an NTP client in the chia install to check the time deviations, and notify the user. (I don't think chia should modify the system clock - only notify)
> Given the number of posts here on git with sync in the subject. I think this is a significant issue to look into.
> Any thoughts appreciated.

mhh yea there are so many qustions about chia and how it works but seems nobody knows if this software works correct or not... :/

**Comment by azaryc2s** [comment]
While there could be some issues connecting to peers with their time behind you, i would not be so sure about whether this actually is the issue here. I would be worried more about multiple full_nodes on the same network. (the OP said he checked the OTHER pc on his Net, which would explain his issues if he either forwarded 8444 to a specific client or has UPnP enabled), which in both cases causes problems with peer connections.

But the sys-time thing should definietly be looked at and considered by the dev team.
