### ISSUE TITLE
Node Status/Sync - extremely slow

### ISSUE THREAD

**Issue by mccombs** [Chia-Network/chia-blockchain#5328]
In an effort to speed up the Node Status/Sync, I copied over my db folder from my fast computer (i7 9700) to my slower computer (i5 7400) and relaunched the Chia GUI.

Even though it's a fully populated db, it's still verifying each hash individually. Why?
 
At the current rate, I'd estimate it won't be complete for another ~48-60  hours before it's complete.

Shouldn't this be a simple check and update? What can I do to speed this process up?

I realize this isn't a top performing rig but having to wait almost 4 days to get a 2nd computer caught up feels super broken. This isn't scaleable as the blockchain grows.

**Comment by baizuchong-net** [comment]
验证这个步骤是必须的，必须保证每个账本没有被篡改
