### ISSUE TITLE
The problem of Chia transfer

### ISSUE THREAD

**Issue by tomlcb888** [Chia-Network/chia-blockchain#5354]
I have a Chia transfer on 2021 / 05 / 02, but the wallet has not received any data and transfer records, and the wallet data has been synchronized in place.

![zhuazhangjilv](https://user-images.githubusercontent.com/82565397/118570021-c9ee6080-b7ad-11eb-9685-7e521044cea7.png)
![J4@3@N}D@WTKQO (41}MLH8](https://user-images.githubusercontent.com/82565397/118570039-d2469b80-b7ad-11eb-93d2-eec4aaa64207.png)
![D5NKRZM%XP``8LN@我2021/05/02有一笔chia转账，但钱包未收到任何数据和转账记录。

![zhuazhangjilv](https://user-images.githubusercontent.com/82565397/118570021-c9ee6080-b7ad-11eb-9685-7e521044cea7.png)
![J4@3@N}D@WTKQO (41}MLH8](https://user-images.githubusercontent.com/82565397/118570039-d2469b80-b7ad-11eb-93d2-eec4aaa64207.png)
3FG6F](https://user-images.githubusercontent.com/82565397/118570045-d4105f00-b7ad-11eb-8cb0-2e4c568a25d4.png)
![$1{$%VOEVD3U1P5VYOM O_K](https://user-images.githubusercontent.com/82565397/118570130-0d48cf00-b7ae-11eb-8f34-ea692fc7d883.png)
![0)0DMLBR`XK72S9 DS$Z_1M](https://user-images.githubusercontent.com/82565397/118570135-1174ec80-b7ae-11eb-85f0-a4f7704c8165.png)

**Comment by baizuchong-net** [comment]
说明你的节点 高度 还未同步成功

**Comment by fckngguy** [comment]
I have this same issue. Bought CHIA from DigiFinex (withdraw confirmations and successes confirmed), sent it to my "RECEIVE" address in my wallet. Full Node is synced. Shows up on the block explorer, but no balance in wallet. What do we think? Just wait?

https://www.chiaexplorer.com/blockchain/address/xch12sn97lacza2ggfr3zd9kypjm39tsdglzufaawhqhjpwf3c4l2suqx09mhw

**Comment by tomlcb888** [comment]
看截图，节点和钱包数据是当下最高位置。



---Original---
From: ***@***.***&gt;
Date: Tue, May 18, 2021 08:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Chia-Network/chia-blockchain] The problem of Chia transfer (#5354)




 
说明你的节点 高度 还未同步成功

**Comment by tomlcb888** [comment]
Looking at the screenshot, the node and wallet data are the highest positions at present.

**Comment by tomlcb888** [comment]
> 说明你的基线高度尚未同步成功

Screenshots show that they have been synchronized, how can they be considered successful?
