### ISSUE TITLE
[BUG]Transaction stuck at pending total balance state

### ISSUE THREAD

**Issue by Talentboybb** [Chia-Network/chia-blockchain#5357]
![捕获](https://user-images.githubusercontent.com/84359210/118574741-a29c9100-b7b7-11eb-872b-802a02695845.PNG)
for 3 days a transaction still stucked at the pending total balance state.
i've del ./chia/mainret/wallet/db and resync the wallet db, the same problem.
How can i fix this.

**Comment by paappraiser** [comment]
Same bug.

**Comment by accelerator2** [comment]
Same

**Comment by aprattes** [comment]
same..

**Comment by jannson** [comment]
Same
