### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by joestud69** [Chia-Network/chia-blockchain#5358]
**Describe the bug**
I am trying to set up multiple farms using my same wallet address, however the wallet balance is not showing up on the other systems, the only system that is showing the wallet balance is the initial system where the wallet was created. 

**To Reproduce**
S
<img width="953" alt="Screen Shot 2021-05-17 at 8 00 29 PM" src="https://user-images.githubusercontent.com/84359395/118574696-96c6b580-b74a-11eb-9d15-46cc41eef725.png">
<img width="953" alt="Screen Shot 2021-05-17 at 8 00 29 PM" src="https://user-images.githubusercontent.com/84359395/118574728-a5ad6800-b74a-11eb-9ed0-5b837810aa7f.png">

et up multiple systems on the same wallet to plot and farm chia, sync multiple systems on the same wallet, after receiving XCH look at all system balances. 

1. Go to chia 1.1.5
2. Click on wallet
3. Scroll down to balence
4. See error no XCH

**Expected behavior**
XCH to show up in wallet address on whatever system I log into to see wallet balance. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: MAC Big Sur 11.3.1 and Windows 10

- CPU: [3.5 GHz Quad-Core Intel Core i5]

**Additional context**
Using multiple CPUs my smallest system, is the one showing the wallet balance as I was using that one for farming has 2 cores and 2 gb ram

**Comment by wbendick** [comment]
is your wallet synced?

**Comment by joestud69** [comment]
> is your wallet synced?

Yes
