### ISSUE TITLE
[BUG]how to build local test of chia network?

### ISSUE THREAD

**Issue by chengjia2016** [Chia-Network/chia-blockchain#5378]
hi there,
how to build local test of chia network?

iI have deployed FRAMER TIMELORD and other . modify config create the genesis
all server is ok ,but NO genesis block ,and local farmer not dig

**Comment by azaryc2s** [comment]
How is this a bug you troll? It's because of ppl like you spamming with "issues" like that and tagging it as bug, that real bugs go undetected under the radar...if you're unable to create a cheap fork of this project, that's on you, not a bug. You might ask for help, but it's definietly not a bug.

**Comment by TaylorWenOne** [comment]
> hi there,
> how to build local test of chia network?
> 
> iI have deployed FRAMER TIMELORD and other . modify config create the genesis
> all server is ok ,but NO genesis block ,and local farmer not dig

hello，may i ask you how to  deployed FRAMER TIMELORD ？And how to create the genesis block？hope your reply
