### ISSUE TITLE
DOUBLE_SPEND and operation pending forever

### ISSUE THREAD

**Issue by tiby76** [Chia-Network/chia-blockchain#5384]
**Describe the bug**
I received 2 XCH, I sent them to my exchange and they remained pending forever with a DOUBLE_SPEND error 

**To Reproduce**

I received 2 chia XCH
I transferred them to an exchange
The operation was not executed, it was pending and continues like this 2 days later.
Now the 2 XCH of the Total Balance do not appear, but they do appear in the Total Chia Farmed
In the wallet it appears as Pending Total Balance -2 XCH, when the operation was not carried out.
They have not arrived at the exchange and in the history the operation appears pending. 

**Expected behavior**
That the XCH be transferred to the exchange normally. 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/84367533/118592176-d4a4f780-b7a5-11eb-8e71-1ce424088d39.png)
![imagen](https://user-images.githubusercontent.com/84367533/118592310-0c13a400-b7a6-11eb-8796-bd471b7b688d.png)
![imagen](https://user-images.githubusercontent.com/84367533/118592421-336a7100-b7a6-11eb-9acf-f899984428cf.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS 64 bits
- CPU: Intel Core I9 10900K

PS:  This is the computer from which I create the plots, which is a mirror of the farm. I already had 2 XCH last week on the computer that I have CHIA farming and everything went well.

**Comment by wbendick** [comment]
is your wallet synced?

**Comment by tiby76** [comment]
yes
