### ISSUE TITLE
[BUG]Add a new task to the queue, and an error will be reported after the start

### ISSUE THREAD

**Issue by Hoinor** [Chia-Network/chia-blockchain#5402]
**Describe the bug**
Add a new task to the queue, and an error will be reported after the start

**To Reproduce**
1. Create a queue A
2. Add a new task to queue A
3. When the first task in queue A is completed, the first one in queue A added later will start. After waiting for a few minutes, check the log and you will find an error message ‘’RuntimeError: bad allocation’’

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows]
- OS Version/Flavor: [Windows10]
- CPU: [AMD 5600X]

**Additional context**

**Comment by wbendick** [comment]
How much ram do you have? How much is being used by plotting?

**Comment by Hoinor** [comment]
> How much ram do you have? How much is being used by plotting?

24G RAM, I now see that plotting 4 occupies 7.5G RAM. I have been observing the ram usage. Even after a long period of operation, it can still maintain the occupancy below 80%.
