### ISSUE TITLE
Not staying in Sync

### ISSUE THREAD

**Issue by cyrus104** [Chia-Network/chia-blockchain#5407]
**Describe the bug**
My ISP blocks all incoming ports, so I cannot do any port forwarding. I have added the western-us introducer but I never get more than 2-5 full nodes. I have tested adding more nodes manually which works for a while but then they eventually drop off too.

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10 20H1
- CPU: Intel i7-8800k

**Additional context**

**Comment by nahoi83** [comment]
2021-05-18T12:54:44.930 full_node full_node_server        : WARNING  Banning 111.235.231.100 for 600 seconds
2021-05-18T12:54:44.931 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 628, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 111.235.231.100
I am getting this erors to

**Comment by SirVladislav** [comment]
> 2021-05-18T12:54:44.930 full_node full_node_server : WARNING Banning 111.235.231.100 for 600 seconds
> 2021-05-18T12:54:44.931 full_node chia.full_node.full_node: ERROR Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
> File "chia\full_node\full_node.py", line 628, in _sync
> RuntimeError: Weight proof did not arrive in time from peer: 111.235.231.100
> I am getting this erors to

If you have 2 farming device try to connect them correctly using wallet key sync and allow using network while 1st run GUI

**Comment by cyrus104** [comment]
I would like to see if we can address my issues and not another issue in the bug post.

**Comment by wbendick** [comment]
can you post your debug.log
