### ISSUE TITLE
[Enhancement] Suggestion on chia plots check command/CLI

### ISSUE THREAD

**Issue by toastygunn** [Chia-Network/chia-blockchain#541]
I was going through my currently plotted files to check their quality (n=1000 checks) before placing them in the farm and noticed that when you specify a directory in linux OR windows for the (-g /path/to/plotfiles), that /path/to/plotfiles MUST be in the config.yaml file or its NOT checked.

Q: It was a minor annoyance to have to add the path to the config.yaml file on that system but why is this required?

Some folks have dedicated machines just to plotting are NOT farming or harvesting so their config.yaml files have been largely ignored. Why can't I just specify any mount point (under linux) or folder (under windows) to check those files?

-g

PS. Is there any reason I can only add the label bug instead of (IMO correctly) labeling this as an enhancement request?

**Comment by hoffmang9** [comment]
Not sure why you couldn't label it enhancement but I went ahead and did it.

**Comment by hoffmang9** [comment]
Bump.
