### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jinhuikeji** [Chia-Network/chia-blockchain#5414]
**Describe the bug**
Dear engineer, hello.I am a miner of Chia coins. Recently, I met a problem that could not be solved. My computer winner configuration is:AMD5900X, Kingston Hackster 16G*4, Samsung 980 1T 2, Kingston 1T SATA 3 solid disks, Asus TUF Gameing X570 Plus, 10 open task under Windows10 (the default configuration) runs very slowly, about 20 hours to complete a round,In addition, it is possible to encounter a run time error.In the Linux system will not report error, but the occupancy rate of the processor has been very low, the highest will not reach 50%, the process is very slow, the same memory hard disk on the Intel platform can run normally, look forward to you can help me.thank you
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows10 ]
- OS Version/Flavor: [2004 pro]
- CPU: [AMD 5900X]

**Additional context**
I also have a set of AMD3600 processor, the motherboard is ASUS TUF B450, the same problem, is not CHIA for AMD platform compatibility is not good?

**Comment by wbendick** [comment]
What is the errror?

**Comment by jinhuikeji** [comment]
Dear engineer,

First of all, I am very glad to receive your reply. The problem with my computer has been found. It is the problem with the three solid state drives of Kingston.Only use the M2 interface of Samsung 980 solid-state drive will not have problems. Finally, thanks for your reply and wish you a happy life!

 

 

发件人: ***@***.*** ***@***.***> 代表 Will Bendick
发送时间: 2021-05-18 22:59
收件人: Chia-Network/chia-blockchain ***@***.***>
抄送: jinhuikeji ***@***.***>; Author ***@***.***>
主题: Re: [Chia-Network/chia-blockchain] [BUG] (#5414)

 

What is the errror?
