### ISSUE TITLE
Plotting stopped but no error code. 

### ISSUE THREAD

**Issue by justmemo** [Chia-Network/chia-blockchain#5420]
**Describe the bug**
I was trying plot process but i got the same situation every day. 
Plot stops in different percentages. Not the same percentages. No error code
What can i do for that's situation?   
99 Percentages waiting from 6 hours , WHY ? 

**Screenshots**

![WhatsApp Image 2021-05-18 at 8 29 14 AM](https://user-images.githubusercontent.com/84389361/118653311-636d4080-b7b5-11eb-8467-106dcf859e46.jpeg)

![WhatsApp Image 2021-05-18 at 8 29 14 AM (1)](https://user-images.githubusercontent.com/84389361/118653240-505a7080-b7b5-11eb-97cd-9c82448a37bc.jpeg)

**Comment by kushariforyou** [comment]
What settings are you using for the plots, and what drives are you writing to? Also what versio of Chia are you running?

**Comment by justmemo** [comment]
**> What settings are you using for the plots, and what drives are you writing to? Also what version of Chia are you running?**
Usually, I'm using it like that. ( Screenshot)
Temporary Directory: Samsung 980 pro 1tb 
Equipment : 
Cpu: Intel i7 11700K
Ram: Corsair 16 gb 3200 Mhz
I have 1.1.15 version
 **Screenshot**
![WhatsApp Image 2021-05-18 at 10 02 55 AM](https://user-images.githubusercontent.com/84389361/118665863-ada7ef00-b7c0-11eb-8b5b-acedd1969d30.jpeg)

**Comment by kushariforyou** [comment]
Are you running low on space? I'd only do around 2 plots max for a 1TB drive at the same time.

**Comment by justmemo** [comment]
Maybe but I had more than 300 Gb of storage

**Comment by kushariforyou** [comment]
Try with 1 or 2 plots instead of 3 and see if that helps.

**Comment by justmemo** [comment]
im will try in a day and i will share update . Thanks
