### ISSUE TITLE
[BUG] faucet.chia.net

### ISSUE THREAD

**Issue by chrismikefowler1** [Chia-Network/chia-blockchain#5429]
I use my receive address, and it keeps saying already received.

![image](https://user-images.githubusercontent.com/84326972/118680646-c4941480-b7b3-11eb-8a44-61adff215b74.png)

**Comment by sargonas** [comment]
Have you tried looking your wallet address up on Chia Explorer to see if the transaction is logged? It's possible it went through, but your local wallet is somehow out of sync and therefore not reflected in your GUI.
