### ISSUE TITLE
[BUG] PLOTS CHECK NOT REDIRECTED TO FILE

### ISSUE THREAD

**Issue by qpirsel** [Chia-Network/chia-blockchain#5438]
**Describe the bug**
I can't redirect the standart output of **chia plots create** with CMD or Powershell to a file. It creates an empty file. Same behaviour with powershell and **| tee**. When I redirect Stderr I get the output but with strange sequences (s. screenshot)

**To Reproduce**
Open a Windows command prompt and enter:
chia plots check -g a_plot_file.plot > %HOMEPATH%\Desktop\log.txt

**Expected behavior**
File shoud contain the same output as the command without redirection

**Screenshots**
![STDERR redirection](https://user-images.githubusercontent.com/17856684/118411554-6f61e100-b695-11eb-8a44-5d9f77c8a086.png)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 8.1 / 10
- CPU: i7/Ryzen7

**Additional context**
Commands like chia show -s >  %HOMEPATH%\Desktop\log.txt work as expected.

**Comment by azaryc2s** [comment]
It's because a logger writes to stderr, not stdout, so > doesn't work. Either use &> in bash, or 2> in any POSIX-complient shell.
