### ISSUE TITLE
[BUG] No more space

### ISSUE THREAD

**Issue by kicsiko** [Chia-Network/chia-blockchain#544]
**Describe the bug**
No more space

**To Reproduce**
No more space on plotting. The temporary work space is 3GB on K=25 and more than 480GB (this is my limit) on K=32
Version: b18 with GUI

**Desktop (please complete the following information):**
- OS: Linux
- OS Version/Flavor: Debian 10
- CPU: Ryzen 2700

**Comment by mariano54** [comment]
Please install beta17, there is a known bug in the new version (18).
