### ISSUE TITLE
[BUG] SOCD report detected: (AP watchdog expired)

### ISSUE THREAD

**Issue by radvansky-tomas** [Chia-Network/chia-blockchain#5452]
I know that its probably not directly related to chia, but my m1 always crash while farming
https://discussions.apple.com/thread/252437781

**Comment by sargonas** [comment]
Very interesting... so reading through that thread, if I understand correctly having an external Western Digital USB drive attached to your Mac Mini was causing the crashes? Very odd indeed. You're right that its probably not related, but not a terrible idea to include this info here. I've re-stating the apple support thread here for that very reason, so I can close this but leave it in the database for other people to perhaps find while searching issues they have in hopes it might save them some effort.

**Comment by radvansky-tomas** [comment]
I have seagate 14TB drive and Gdrive4TB both connected using USB3

I hope they will resolve it via OSX updates...
