### ISSUE TITLE
[BUG]'dict' object has no attribute 'get_current_derivation_record_for_wallet'

### ISSUE THREAD

**Issue by Ziaduxx** [Chia-Network/chia-blockchain#5463]
When i open the Chia Gui in Windows I keep getting the following error on one machine.

'dict' object has no attribute 'get_current_derivation_record_for_wallet'
'dict' object has no attribute 'get_confirmed_balance_for_wallet'
'dict' object has no attribute 'get_current_derivation_record_for_wallet'
'dict' object has no attribute 'get_confirmed_balance_for_wallet'

I'm unclear why and also there appears to be two wallets under status. One with my real key and the other completely blank of any information.

I don't know if this issue has been logged as I went through a wack to see and didn't see it.

Thanks for any help.

**Comment by Buzzmovies** [comment]
I get the exact same messages every time I launch the application. Not a huge deal but I just hope nothing is wrong with the work (plots) I create. Thanks for looking into this.
