### ISSUE TITLE
[BUG] Support Linux command line operations，Don't need GUI.

### ISSUE THREAD

**Issue by peterwillcn** [Chia-Network/chia-blockchain#5478]
Support linux command line operations，Don't need GUI.

**Comment by freemandealer** [comment]
They already did it, but documents concerning CLI is confusing somehow.

**Comment by joelrb** [comment]
> Support command line operations，Don't need GUI.

https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference
