### ISSUE TITLE
[BUG] installer for osx runs on all platforms but errors internally

### ISSUE THREAD

**Issue by Hardcore-fs** [Chia-Network/chia-blockchain#5481]
installer for osx is only built for osx 10.15
the program runs on other versions , but it it internal erroring

`[3260] Error loading Python lib '/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libpython3.9.dylib': dlopen: dlopen(/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libpython3.9.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libintl.8.dylib
`

**Comment by arunzn** [comment]
I am facing same issue in 10.13

log:

Running python executable: 
child process success
(node:1121) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
stderr: [1128] Error loading Python lib '/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libpython3.9.dylib': dlopen: dlopen(/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libpython3.9.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libintl.8.dylib
closing code: 255
