### ISSUE TITLE
[BUG] Error 22 will not allow me to add any plot directories

### ISSUE THREAD

**Issue by berlef80** [Chia-Network/chia-blockchain#5486]
**Describe the bug**
[Error 22] File not found. Most likely one of the plot folders in your config.yaml has an issue.   I shut down Chia, restarted and all my plot directory went away.  When I try to add a plot directory I get that error.

Using Windows GUI

**Comment by aDilly** [comment]
Open up the config.yaml file and check the directories listed for mistakes? Should be around line 150.
located in C:\users\USERNAME\.chia\mainnet\config

**Comment by KeypressHAPPY** [comment]
same thing happened to me, if attempting fix is no good, just rename your config.yaml to config.yaml.bak and relaunch the chia main node, click into your wallet, it will create another config file for you automatically.
