### ISSUE TITLE
[BUG] wallet chia.wallet.wallet_state_manager: INFO confirmed balance amount is 100

### ISSUE THREAD

**Issue by Prawate** [Chia-Network/chia-blockchain#5487]
Log file inform: chia.wallet.wallet_state_manager: INFO Confirmed balance amount 100
---------
What does this message say?
![image](https://user-images.githubusercontent.com/83258628/118760994-e23da880-b89d-11eb-8d1f-94e8652425a4.jpeg)

**Comment by ramkom9** [comment]
same here
