### ISSUE TITLE
[BUG] Chia GUI randomly selects reward wallet

### ISSUE THREAD

**Issue by kkourmousis** [Chia-Network/chia-blockchain#5502]
**Describe the bug**
I had 2 wallets connected in my Chia GUI. The 1st one had 7 plots and the 2nd one had 2100 plots.

Over the past 8 days I was waiting for reward and I was (obviously) focusing on the 2nd wallet with the 2100 plots. My 1st wallet was left out of sync. Today I decided to check my 1st wallet on chiaexplorer.com and I saw that I had 4 XCH rewards.

Why am I really pissed then? I am really pissed because I plotted on the cloud, trying to overpass the netspace growth. After 8 days with 0 rewards I gave up and I deleted all the plots and servers.

Now, with the price drop and netspace crazy growth, I can't say that I would/should have done otherwise, but I could at least wait for another block. All I got now was a break-even (actually I am a few hundreds in but it's much better than paying the whole debt out of my pocket).

To conclude, my dear Chia developers, WHY THE F0C|< would Chia GUI deposit the earnings of a plot created with farmer and pool keys of my 2nd wallet to an address that belongs to my 1st wallet????

**To Reproduce**

1. create/import 2 wallets
2. on the second wallet (I don't know order by what, I suppose by the order they were created/imported) create many plots
3. upon reward check your 1st wallet balance

**Expected behavior**
Rewards should go to the wallet that was used to make the plots.

**Desktop (please complete the following information):**
- OS: Windows 10
- CHIA GUI v.1.1.5

**Comment by ramkom9** [comment]
lucky you that you have any reward, I am about to quit no worth to breaking hardware and pay for electricity bill for something which may OR may not earn anything.

**Comment by kkourmousis** [comment]
with 2100 plots on an initial  2EiB netspace, being payed back twice within a week is reasonable.

as for your decision, it is your money my friend. but ask your self if you would do the same if CHIA price was 10,000$ each

**Comment by kkourmousis** [comment]
There is a possible security issue here as well, a major one... I hope the developers give this the attention it needs

**Comment by kevindstanley1988** [comment]
Not sure if this is actually the problem, but if you look at your GUI. There is a button on the farm page in the top right ellipses called 'Manage Farming Rewards'. If you click that and review the addresses in that management window it should be the address you got rewarded to. Now its possible it is setup with the address where you have 7 plots, then that is where it is going to send it on reward. You can manually change these values. If not, then it sure sounds like a bug to me.
