### ISSUE TITLE
[BUG] Start node fail on Ubuntu 20.04

### ISSUE THREAD

**Issue by duyk16** [Chia-Network/chia-blockchain#5521]
I followed install here
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL

It works on Centos 7 but doesn't work on Ubuntu 20.04 without any error log

**Screenshots**
<img width="658" alt="ảnh" src="https://user-images.githubusercontent.com/35636235/118814794-b7257a00-b8da-11eb-81e0-b20f24740689.png">

- OS: Ubuntu 20.04

**Comment by MontajnikRTA** [comment]
I have the same problem

**Comment by lvcivs** [comment]
I think you need to generate keys first before starting the node.

**Comment by lvpcguru** [comment]
Looks like you missed a step. the CLI is some python virtual wrapped instance so you must type '. ./activate' as it says in your screenshot. you cant just add the path and directly call chia.

**Comment by lvpcguru** [comment]
> 
> 
> I followed install here
> https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL
> 
> It works on Centos 7 but doesn't work on Ubuntu 20.04 without any error log
> 
> **Screenshots**
> <img alt="ảnh" width="658" src="https://user-images.githubusercontent.com/35636235/118814794-b7257a00-b8da-11eb-81e0-b20f24740689.png">
> 
>     * OS: Ubuntu 20.04

Looks like you missed a step. the CLI is some python virtual wrapped instance so you must type '. ./activate' as it says in your screenshot. you cant just add the path and directly call chia.

**Comment by sargonas** [comment]
you want to first do `. ./activate` from within the chia-blockchain folder, and then after that you should see "(env)root@vultr" showing you are inside the python environment for chia. At that point you need to do a `chia init` to finish the install process, and then you are good to go from there to continue on.

**Comment by duyk16** [comment]
> you want to first do `. ./activate` from within the chia-blockchain folder, and then after that you should see "(env)root@vultr" showing you are inside the python environment for chia. At that point you need to do a `chia init` to finish the install process, and then you are good to go from there to continue on.
> 
> On Ubuntu you need to make sure you use the python env wrapper, trying to set paths and the like won't work in this setup.

I was reinstall my OS and it's work. Thanks for your help

<img width="516" alt="ảnh" src="https://user-images.githubusercontent.com/35636235/118934964-28b20680-b975-11eb-9dbd-0f1b0825ae5e.png">
