### ISSUE TITLE
[BUG]Chia GUI in Win10 no response straight after deleting a ploting job

### ISSUE THREAD

**Issue by flaginwind** [Chia-Network/chia-blockchain#5528]
**Describe the bug**
In Chia Gui Win 10 version, there is multiple ploting jobs in place, once deleting one of them, the Chia GUI will display 'connecting to wallet' with a circling icon for a long time, the only way is to close it and lost all the ploting jobs in progress. 

**To Reproduce**

1. Go to 'Ploting'
2. Click on 'button at right side in a ploting job'
3. Click delete
4. See "connecting to wallet"

**Desktop (please complete the following information):**

- OS: Win 10 professional with latest OS patch installed
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: i5 9400F

**Comment by madimozg** [comment]
I have the same problem, don't know what to do.

**Comment by louiscoetzee** [comment]
the gui is very buggy, happened to me too. it's still running, just minimize the app and use this app to check plot progress: https://github.com/grayfallstown/Chia-Plot-Status once completed restart the gui. hope it helps.

**Comment by madimozg** [comment]
> the gui is very buggy, happened to me too. it's still running, just minimize the app and use this app to check plot progress: https://github.com/grayfallstown/Chia-Plot-Status once completed restart the gui. hope it helps.

Did not help. Even reinstalling the program did not help.

**Comment by brezapour81** [comment]
I've had the same issue. Not seeing anything in the logs either to explain. Looks like a bug.

**If people are interest, we are launching a Chia Pool soon called [https://www.seedpool.org/](https://www.seedpool.org/) . Check it out**.

**Comment by janwarming** [comment]
@brezapour81 do we need to re-plot all our disks or can we use our existing plots with your pool?

**Comment by brezapour81** [comment]
> @brezapour81 do we need to re-plot all our disks or can we use our existing plots with your pool?

Unfortunately you will need to re-plot, but from the information we have read about the new protocol, your plots will not be exclusive to a pool. I.e. you can move them around if you wish. In other words, when the release comes out from Chia to allows this, you should begin to plan replacing the existing plots one by one so as to not start from scratch and thus lose potential wins.



********If people are interest, we are launching a Chia Pool soon called https://www.seedpool.org/ . Check it out.**********
