### ISSUE TITLE
chia cpu 100% ssd 30% [BUG]

### ISSUE THREAD

**Issue by jefersonrosa10** [Chia-Network/chia-blockchain#5535]
good afternoon, when i enter china it consumes 100% of the CPU and 60% of the memory only 30% of the SSD, the ssd are too slow to plot and Nmve is spending more than 20 hours for 1 plot, wait for me to help you with that ?

![image](https://user-images.githubusercontent.com/84423114/118847212-e1a81080-b8a3-11eb-9340-886521121d20.png)

**Comment by room101-dev** [comment]
Run on linux, only fools run plotting on windows. Use the cmd-line tool 'chia plot create -t ... -2. ...'

Run 'sudo fstrim -v /dev/nvmeNNN' frequently to trim your ssd ak NVME for chia plotting, as this deletes used space, which if you don't do this, then over time say every 2-3 plots your speed will drop to zero. WIndows is supposed to use 'discard' automatically, but its garbage, like I already said real men don't plot chia on windows, they use cmd-line on linux.
The problem with NVME/SSD is that the HDD drivers use the HD model of a bitmap marking bad & used sectors, and of course on an NVME its all memory, so you need a house-keeping tool to 'clean house', other wise the shit comes to a halt, windows is 1980's arch, anybody using this stuff deserves to fail.

Why people cling to windows to do a mans job begs the question? WHY? Windows doesn't even support the correct file-format for plotting which should be NFS, I don't think a single NAS server on earth uses windows? The world is linux, the tools are linux.

A man is known by his tools, you don't bring windows to a gun fight.

You will known when your NVME is kaput, your log will have mis-match errors, right now you just have an un-tidy NVME, there are tools on windows, but seriously what the hell are you doing on this on windows? For what? Ok I can see if your just playing, and doing a one time plot, and a one time play around and test the chia block-chain, but if your serious about lots of plots and some serious CHIA mining, get the hell off windows.
