### ISSUE TITLE
[BUG] plotting with 2 temp space not working

### ISSUE THREAD

**Issue by louisaiva** [Chia-Network/chia-blockchain#5536]
Hello !
I am trying to create plots on my 2 TB HDD, with one 256 GB SSD and a 512 GB SSD.
my first SSD is in reality 238 GB (D:/) and my second is almost full with 50 GB left.
I created a new partition E:/ for the 50 GB left on my 512 GB SSD

As I need ~256 GB temp space to create a 108 GB plot, I tried to used D:/ and E:/ as temp space.
But the plotting is stucked at 32% with Error 1. In fact, it filled entirely D:/ but didn't use E:/ at all...
`Only wrote 0 of 1048570 bytes at offset 332396690 to "D:" ... . Error 1. Retrying in five minutes.`

Is here any way for me to use 2 temp space to create plots ? It's like it does not work..
Maybe by using the cli chia ?

Thanks for help.
I am using Chia Gui 1.1.5

**Comment by jefersonrosa10** [comment]
you will enter the folder where you are plotting on the hd with the largest space, you will copy plot.table1.tmp of 15 gb and plot.table2.tmp of 21 gb, to the hd with 50 gb of space, after you finish copying the file you will delete the file you are plotting from, when plotting an error message from the plots that you delete right in front and just copy it again to the plotting folder

**Comment by wbendick** [comment]
Your temp space wasn't big enough. Temp space cannot be split up.

**Comment by louisaiva** [comment]
> Your temp space wasn't big enough. Temp space cannot be split up.

So... what is the point in proposing a second temps disk in the Gui whike creating a New plot ?
