### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by MohZou** [Chia-Network/chia-blockchain#554]
I am making plots on 5 different PC and farming on one of them. Starting from b17 after clicking the reload button the screen becomes white and is not coming back so I need to restart Chia completely. Is happening on all 5 PCs not just one so I think it is a bug. I tough it will be repaired with b18 but the problem persists. With previous versions (before b17) it worked normally and I was using it sometimes.

![reload1](https://user-images.githubusercontent.com/71387757/101690499-a3453480-3a6d-11eb-8850-ca419ae55e61.jpg)
![reload2](https://user-images.githubusercontent.com/71387757/101690502-a4766180-3a6d-11eb-814a-1d5d8e0059f2.jpg)

**Comment by seeden** [comment]
I will verify it, but I think that I already pushed a fix for this issue.
