### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dusti0777** [Chia-Network/chia-blockchain#5541]
**Describe the bug**
when closing the gui while plotting the temp-files are not removed or re-used  and plotting does not continue

**To Reproduce**

1. add a plot
2. close the gui
3. restart gui
4. temp files are not removed, and an unfinished plot is not restarted

**Expected behavior**
either save state of plot OR remove the temp files

**Screenshots**
NA

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Debian 10.9
- CPU: Xeon lxc 

**Additional context**
new plot couldn't continue because old tmp-files took too many space on disk

**Comment by lvpcguru** [comment]
I ran into an issue with the destination disk that caused my lost plots to sit in the xxxx.plot.2.tmp name waiting to be moved. I would not want those deleted automatically as I was able to save them with a manual rename and move.

**Comment by TarekJ03** [comment]
That's just the way it apparently is with the GUI. You stop it, all Chia processes started by the GUI are killed along with it. I'd generally recommend using the CLI over the GUI.

**Comment by LuanSouza28** [comment]
TOO SLOW TO CONNECT THE WALLET.
