### ISSUE TITLE
Another stupid bug when i delete a plot [BUG]

### ISSUE THREAD

**Issue by TranceDevCode** [Chia-Network/chia-blockchain#5544]
**Problem when i delete a plot**

What is the problem with the app? when i need delete a plor because i have 0MB in my NVME, the app restart the sync and try to connect to wallet, so never return with a stable connection and lost all my other plots, i have 6 plots and lost all for this stupid problem. this is really bad.... fix that...

**Desktop (Details):**

- OS: [Windows 10]
- OS Version/Flavor: [Windows 10 Pro]
- CPU: [Ryzen 5 3600x, 32GB Ram...]

🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by Yuvix25** [comment]
Yeah happened to me as well, just move to [swar-chia-plot-manager](https://github.com/swar/Swar-Chia-Plot-Manager), it has better control on the plots and it doesn't just die from time to time...

**Comment by lvpcguru** [comment]
Found this out as well. the GUI refresh almost always fails on refresh following an early plot delete. and that of course kills the other plots. lost 4 plots in parallel twice before I moved on to the CLI as a workaround.

**Comment by VioletGiraffe** [comment]
I have the same problem, as described by @lvpcguru. Removing the plot that's in progress (not queued up) is guaranteed to crash the whole Chia system, losing all other plots that are in progress. I don't mean an actual crash, but the plotter and farmer processes disappear, and GUI gets stuck refreshing forever.

**Comment by alex-oden** [comment]
Try always to work with plots trough the Power Shell on windows. Because GUI is very buggy and with Power shell you can easily stop plotting process - look in official wiki about that
