### ISSUE TITLE
[BUG] chia install.sh not working

### ISSUE THREAD

**Issue by tedshroyer** [Chia-Network/chia-blockchain#555]
**Describe the bug**
https://download.chia.net/simple/ does not provide versions required by setup.py in this PR https://github.com/Chia-Network/chia-blockchain/commit/7051102ae64aab5c219c8f19d0d2f398ac18c2ae

**To Reproduce**

1. Follow Centos/RHEL setup on new install: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#centosrhel-77-or-newer
2. After running sh install.sh the following error is presented
`Looking in indexes: https://pypi.org/simple, https://download.chia.net/simple/
Obtaining file:///home/ts/chia/chia-blockchain
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Could not find a version that satisfies the requirement chiavdf==0.12.26 (from chia-blockchain)
ERROR: No matching distribution found for chiavdf==0.12.26
`
**Expected behavior**
pip install steps work

**Screenshots**
`[ts@rhel76 chia-blockchain]$ sh install.sh 
install.sh: line 6: type: apt-get: not found
yum is /usr/bin/yum
yum is /usr/bin/yum
Installing on CentOS/Redhat
which: no python37 in (/home/ts/.local/bin:/home/ts/bin:/home/ts/.local/bin:/home/ts/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin)
which: no python3.7 in (/home/ts/.local/bin:/home/ts/bin:/home/ts/.local/bin:/home/ts/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin)
which: no python38 in (/home/ts/.local/bin:/home/ts/bin:/home/ts/.local/bin:/home/ts/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin)
which: no python3.8 in (/home/ts/.local/bin:/home/ts/bin:/home/ts/.local/bin:/home/ts/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin)
Python version is 3
Requirement already satisfied: pip in ./venv/lib/python3.6/site-packages (20.3.1)
Requirement already satisfied: wheel in ./venv/lib/python3.6/site-packages (0.36.1)
Looking in indexes: https://pypi.org/simple, https://download.chia.net/simple/
Requirement already satisfied: miniupnpc==2.1 in ./venv/lib/python3.6/site-packages (2.1)
Requirement already satisfied: setproctitle==1.1.10 in ./venv/lib/python3.6/site-packages (1.1.10)
Looking in indexes: https://pypi.org/simple, https://download.chia.net/simple/
Obtaining file:///home/ts/chia/chia-blockchain
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Could not find a version that satisfies the requirement chiavdf==0.12.26 (from chia-blockchain)
ERROR: No matching distribution found for chiavdf==0.12.26
`

**Desktop (please complete the following information):**

- OS: Linux
- OS RHEL 8.3
- CPU: AMD Ryzen 9

**Comment by hoffmang9** [comment]
This almost has to be a network problem.

This is that version on pypi - https://pypi.org/project/chiavdf/0.12.26/

Can you try running again and try viewing that URL from that machine? You could also manually install it in the venv.

**Comment by tedshroyer** [comment]
@hoffmang9 I ran pip with -v flag and got this.  My python versions didn't upgrade to 3.7.  Closing.

`  Link requires a different Python (3.6.8 not in: '>=3.7'): https://files.pythonhosted.org/packages/a6/af/36376a30ba02acb9876c8355040f90be8ebc3d83302cbbeaa0a2e8cc5c24/chiabip158-0.17.tar.gz#sha256=3f082c4e15d5f500108b3a0680d7049e3e84041733f17ff2f88c22e4d1ac230b (from https://pypi.org/simple/chiabip158/) (requires-python:>=3.7)`
