### ISSUE TITLE
Failed to open (invalid plots)[BUG]

### ISSUE THREAD

**Issue by CalvinDay** [Chia-Network/chia-blockchain#5555]
I have 20 plots ... 10 were made on one drive and 10 more on another.

All were moved to a third drive 8TB and all 20 show farming.

However, the lower part of the screen says:

Failed to open (invalid plots) for 10 plots which are **also shown** as farming.

**Comment by lvpcguru** [comment]
How did you move the plots? when moving plots on active farms you have to change the name to .tmp or something until the transfer is done. this should stop the farmer daemon from reading the plots as bad.

If your done moving things try and restart your daemons

**Comment by CalvinDay** [comment]
I used windows explorer cut and paste.

I don't think Chia Blockshain was running when I moved them.

I just removed the drive completely and they are not farming (of course) but they still show up in the Failed to open area. Same 10 and not the full 20. Must be queued somewhere.

**Comment by lvpcguru** [comment]
Sounds about right I believe its the harvester and farmer you need off not the bockchain. Try to stop chia and reattach the drive.

if your on GUI close it and reopen

if your on CLI
chia stop all
chia start all
