### ISSUE TITLE
[BUG] Not Synced from block 302287 05/18/2021 21:07:19

### ISSUE THREAD

**Issue by ivanbey** [Chia-Network/chia-blockchain#5559]
- OS: Windows 10 64 Pro
- OS Version/Flavor: 20H2
- OS compilation: 19042.985
- CPU: AMD Ryzen 5 3600 6-Core Processor   3.59 GHz
- Chia Gui ver 1.1.5

**Additional context**
He reiniciado varias veces chia GUI, he reiniciado Windows, he apagado el pc, desconectado de la fuente de energia por unos minutos. Sigue el mismo error ya va casi un día.

No he borrado plots, me indica la cantidad correcta de plots y la cantidad correcta de TB. Solo no sincroniza ni puedo farmear. 

![bugchia](https://user-images.githubusercontent.com/9868688/118889111-a4a34480-b8ca-11eb-998c-f12f57fb908a.png)
Saludos

**Comment by lvpcguru** [comment]
what does your log show? and how are you seeing any connections?

**Comment by ivanbey** [comment]
Now is synced. The logs shows error in connections. Only one peers from 10 (I added aprox 10 peers) are connected.
Chia are connected rigth now with : 
78.156.126.29 | 8444

but if i ping this, cant reach that host.

And logs send INFO cannot connect with at least 492 hosts:
60.54.91.105:8444
61.48.169.115:8444
34.64.235.6:8444
213.127.118.245:8444
70.67.134.138:8444
123.15.53.179:8444
151.38.210.221:8444
36.148.64.82:8444
.....

and log show too a lot of connection closed. why?

[debug_forgit.log](https://github.com/Chia-Network/chia-blockchain/files/6512151/debug_forgit.log)

**Comment by jgonzalor** [comment]
Como solucionaste tu error de syncronizacion?

**Comment by MustDhiMust** [comment]
try these peers

2.238.73.140
103.89.83.214
51.154.10.127
14.207.86.218
100.2.123.232
185.102.189.229
222.238.86.72
149.28.228.172

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/

**Comment by ivanbey** [comment]
> Como solucionaste tu error de syncronizacion?

Se conecto solo, pero solo a un peer.

**Comment by ivanbey** [comment]
> try these peers
> 
> 2.238.73.140
> 103.89.83.214
> 51.154.10.127
> 14.207.86.218
> 100.2.123.232
> 185.102.189.229
> 222.238.86.72
> 149.28.228.172

Thanks, I added all.

Now chia is only connected with
2.238.73.140
103.89.83.214
51.154.10.127
14.207.86.218

**Comment by ivanbey** [comment]
> Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection
> 
> https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813
> 
> Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...
> 
> (Also if you have not opened or forward on your router port 8444) You need to do that - here some help
> https://portforward.com/

Thanks a lot, for now meanwhile chia is synced i keep the 1.1.5 release. But this beta seems to correct the problem.

And thanks for the portforward, the port 8444 are open in windows, and router but is a good site for help!

**Comment by lvpcguru** [comment]
If this is resolved dont forget to close the issue :)
