### ISSUE TITLE
Estimated Time to Win and Total Size of Plots for networked harvester and farmer is wrong [BUG]

### ISSUE THREAD

**Issue by joelrb** [Chia-Network/chia-blockchain#5572]
**Describe the bug**
I have a network of a farmer and several harvesters. The Estimated time to win and Total Plot Size displayed in the farmer node should be based on the total of all plots in the network. Currently it displays only for the plots in the farmer machine only. 

**To Reproduce**
Create a farmer node. Add harvesters to the node.

**Expected behavior**
Display Estimated time to win and total plot size based on all the plots in the harvester network.

**Screenshots**
Refer to GUI.

**Desktop (please complete the following information):**

- OS: Any
- OS Version/Flavor: Any
- CPU: Any

**Additional context**

**Comment by roadev** [comment]
I think this could be a very useful feature. Most of plots I have are stored in a harvester machine.
