### ISSUE TITLE
[BUG] Does not sync. Always "not synced"

### ISSUE THREAD

**Issue by Shiro-hige** [Chia-Network/chia-blockchain#5574]
The status was always "syncing". Try to solve it by myself, reinstalled it and now it's stuck on "Not Synced" 
Here's some prints from the app and my log
![Captura de tela 2021-05-20 020934](https://user-images.githubusercontent.com/84492173/118923609-31252580-b912-11eb-8c58-b4404b2031a4.png)
![Captura de tela 2021-05-20 021109](https://user-images.githubusercontent.com/84492173/118923612-32565280-b912-11eb-9365-5520d2b1bd76.png)
![Captura de tela 2021-05-20 021206](https://user-images.githubusercontent.com/84492173/118923614-32565280-b912-11eb-91f4-7edd3182278c.png)

**Comment by hhenrry501** [comment]
has similar issue, able to connect to peers but not syncing..
2021-05-20T12:00:44.234 full_node chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

**Comment by BaraoVlask** [comment]
In my experience with synchronization problems, have two nodes, when one stops working stop the node delete the files located in .chia / mainnet / db / and copy only the blockchain_v1_mainnet files from the other node. And don't use the chiadog.

**Comment by velmirion** [comment]
same problem

**Comment by ArtemBahniuk** [comment]
Have the same issue, here is the log ftom mainnet
2021-05-20T00:48:38.203 full_node full_node_server        : INFO     Cannot connect to host 219.77.183.57:8444 ssl:<ssl.SSLContext object at 0x7fea45ef1d40> [Connect call failed ('219.77.183.57', 8444)]
Looks like the server are not available for now

**Comment by thederpinator** [comment]
Same issue as #5513. Detailed log there, plus proof that the time of desync aligns with the error.

**Comment by DjawadNowrouzi** [comment]
Same...

**Comment by MustDhiMust** [comment]
try these peers

2.238.73.140
103.89.83.214
51.154.10.127
14.207.86.218
100.2.123.232
185.102.189.229
222.238.86.72
149.28.228.172

hope help..

**Comment by DjawadNowrouzi** [comment]
Port 8444?

**Comment by wu-dennis** [comment]
> 
> 
> Port 8444?

yep
2.238.73.140✔
51.154.10.127✔

**Comment by DjawadNowrouzi** [comment]
Merci!

**Comment by wu-dennis** [comment]
> 
> 
> Merci!
There is a public node share the available 8444 peers every hour.
chia.keva.app

**Comment by HudsonProdigy** [comment]
how do we add peers with cli. same way we add introducer?

**Comment by nmmmnu** [comment]
chia show -a 2.238.73.140:8444

**Comment by fl1ck3r** [comment]
> how do we add peers with cli. same way we add introducer?

On the "Full Node" tab, scroll down , click on "Connect to other peers"

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/
