### ISSUE TITLE
[BUG] Chia app gets out of sync when I send plots over the network

### ISSUE THREAD

**Issue by Thorgrlm** [Chia-Network/chia-blockchain#5579]
when i send plots by network from a machine to farmer's machine it gets out of sync chia app
I'm work with ubuntu desktop 18.04

**Comment by nmmmnu** [comment]
No, this is not the reason.
Chia have sync issue right now.
I have spare machine with nothing but FULL_NODE. It is always out of sync.
If I sync it, it go out of sync 30-40 min after that.

**Comment by Thorgrlm** [comment]
Are you sure?, I get desynchronized whenever I send plots by lan to my farmer machine, if I don't send plots, my farm is synchronized

**Comment by nmmmnu** [comment]
Can not be 100% sure, but many people are not synchronized. My farmer goes out of sync every 2-3 h and I don't do anything else there.

**Comment by Thorgrlm** [comment]
ok, I will test my farm more frecuency and i say you something, thanks you

**Comment by lvpcguru** [comment]
> 
> 
> when i send plots by network from a machine to farmer's machine it gets out of sync chia app
> I'm work with ubuntu desktop 18.04

It could still be the transfer that is doing it. while the transfers run you may be choking your only network link causing the node to lose internet access. Do you have a second NIC? I have been playing with moving my farms plot shares to a separate dedicated link. 
Make sure you are not connecting over WIFI as its much easier to use up all the bandwidth with a transfer.
This will especially be an issue if you have a low end switch or router that your transfer is going through the same path the node uses to get to the internet. Many consumer grade switches cant do full speed on all ports at the same time.

**Comment by fl1ck3r** [comment]
same issue, i have noticed that the io usage of chia_full node is quite high. On a vps with an ssd. 

Not sure if this is related, but i had a similar issue on my Pi4 farmer at home, ended up moving the database to mechanical drive (from the sd card), and at  least the high cpu usage was resolved. But now i am unable to sync, even adding 100 known nodes via a script, issue is most nodes are not synced. 

![image](https://user-images.githubusercontent.com/13870076/119001729-8867dc00-b98c-11eb-830d-a50f6eecd5d8.png)

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/

**Comment by Thorgrlm** [comment]
i had test the internet when i send a plot a mi farm, in my farm i can see videos in youtube but the app chia synchronised out

**Comment by lvpcguru** [comment]
@Thorgrlm hows your progress? still getting the issue?

**Comment by Thorgrlm** [comment]
hello , yes, i had to change my OS from Ubuntu desktop version to ubuntu server version and the issue is fixed

**Comment by lvpcguru** [comment]
> 
> 
> hello , yes, i had to change my OS from Ubuntu desktop version to ubuntu server version and the issue is fixed

Nice! close this issue then please.
