### ISSUE TITLE
synchronization never ends [BUG]

### ISSUE THREAD

**Issue by bar5599** [Chia-Network/chia-blockchain#5580]
![image](https://user-images.githubusercontent.com/27418220/118950413-da940780-b962-11eb-9271-60707220c251.png)

There is constant synchronization. It has been working for 3 days and is still not over. Am I doing something wrong. Or is there an error in the program? 

Synchronizing right now 59776/308474

**Comment by bar5599** [comment]
os 
Windows 10 Pro
Sürüm	: 20H2
Yüklenme tarihi	‎05.‎05.‎2021
İS derlemesi	19042.985
Deneyim	Windows Feature Experience Pack 120.2212.2020.0

cpu Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz   2.60 GHz
ram 16 gb ddr3L

**Comment by Nikolaj-K** [comment]
@bar5599 For what it's worth the info: I'm on a (weak) Windows 10 machine, started syncing 5 days ago and am at around 82%.

**Comment by lvpcguru** [comment]
Your almost there :) current height is 309427 thats a loooong way to go

one option is to download a mostly completed database and restart chia. Its risky as you cant validate the source but it may help in a pinch. 

Find a friend with a synced db, sync on a better machine and move it over(i did this) or try this site [https://chiazero.com/pages/chia-network-snapshot](https://chiazero.com/pages/chia-network-snapshot)

**Comment by lvpcguru** [comment]
Also It looks like some of the new code being tested right now might speed up syncing considerably on the next release.
"In the tests, with really small vdf blocks, it improved from 0.016 seconds to 0.003 seconds.

The wallet sync speedup is massive for some computers. It improved request_header_blocks from 8 seconds to 0.2 seconds on my mac. The spent index in sqlite was not helping because there were only two values (true or false) I suppose?"
https://github.com/Chia-Network/chia-blockchain/pull/5590

**Comment by nmmmnu** [comment]
Then again, when 1.1.6 will be released?

**Comment by nmmmnu** [comment]
Things get really frustrating.
Now even https://www.chiaexplorer.com/blockchain/blocks is not synchronized.

**Comment by alex-oden** [comment]
Hi, I have installed this version of chia (beta build as I understand) and all working fine and stable with lot of connection from another peers. As I understand and see in logs - if there is some failure in connection it will not stop with sync and beginning with new connection but stays stable with existing peer connection

https://github.com/Chia-Network/chia-blockchain/actions/runs/853387813

Right now by me it working very good without any issues and Full node don't take a lot of power with CPU consumption. Already in Sync about 6 hours stable and FINALLY it sees my another local harvester...

(Also if you have not opened or forward on your router port 8444) You need to do that - here some help
https://portforward.com/

**Comment by q5sys** [comment]
> For me this has been resolved by using the latest dev/beta version:
> https://download-chia-net.s3-us-west-2.amazonaws.com/devops-test/ChiaSetup-1.1.6105.exe

Random direct link to exe given instead of link to where people can download it... yea that's not suspect at all.

**Comment by mariano54** [comment]
Yes please do not link to s3 or any other non official links (and don't install these)

**Comment by cayolblake** [comment]
@mariano54 

Since you're a dev @ Chia, can you propose a solution/workaround?

I've been at this state since 35 hours for the wallet and my node is fully synced already.

May be add an indicator like the one in the node sync? Showing the targeted height versus the current?

```
Wallet height: 219094
Sync status: Not synced
Balances, fingerprint: 4041547562
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 xch (0 mojo)
   -Pending Total Balance: 0.0 xch (0 mojo)
   -Spendable: 0.0 xch (0 mojo)
```

**Comment by melsom** [comment]
Sorry, link updated.

**Comment by Hardcore-fs** [comment]
Problem is that upgrading kills any plots in progress.

I had no syncs for a day
chia stop wallet
chia start wallet

cleared it straight up & now its syncing again.

ill be rinse & repeat until the plots finish.

**Comment by falconshadow21** [comment]
same problem here.  endless not synced.  ports open, yada yada.      junk

**Comment by Tianxinya2021** [comment]
I have been running 1.1.5 for days with sync full node in win10. When I changed my win login password, the full node sync stops. I tried to restart win10 and full node, the sync did not work at all. The sync is running, but always delayed with a rather fixed time period. no matter how I tried (delete peer/wallet) to let it run for many hours, it is always delayed by a fixed time. When I installed 1.1.6105, the sync is done within 2 minutes to catch up the delayed 40 min. Thanks for the new version.

**Comment by falconshadow21** [comment]
installed version 1.1.6.  Same as Tianxinya2021 it synced right up.  However now I'm not able to create plots.  The log shows  this 

"Starting phase 1/4: Forward Propagation into tmp files... Fri May 21 14:57:39 2021
Computing table 1"

Stuck at 0% for 25 minutes now.
