### ISSUE TITLE
[BUG] Node reports different time then system. leading to sync issue

### ISSUE THREAD

**Issue by HudsonProdigy** [Chia-Network/chia-blockchain#5592]
I have been having issues syncing for some time, once i get to 100% it says not synced. have tried everything on this forum to try to solve. Today i noticed that "chia show -s" is reporting a time about 30 minutes behind system time. Im thinking this could explain why Im getting the "Not synced once at 100%"

in chia environment (Ubuntu 20.04 - chia 1.1.5):
chia show -s
date

results:
`
(venv) hp@hp-ubuntu:~/chia-blockchain$ chia show -s
Current Blockchain Status: Not Synced. Peak height: 309130
      Time: Thu May 20 2021 07:30:35 EDT                  Height:     309130

Estimated network space: 7.054 EiB
Current difficulty: 494
Current VDF sub_slot_iters: 112197632
Total iterations since the start of the blockchain: 1000893977824

  Height: |   Hash:
   309130 | 7794b425240b4e91e41c50672114c1180ebf41470a8c1cd3d1a93c3e65505dd0
   309129 | 8ff12136f37ae353c9f339673e64da0b971ac6d7b006d4cde606b45c7ffaac01
   309128 | 220b7b16a900b3cc2136689ab6b23cd3167ec6a8ae59f03fcde83f9168f10bcf
   309127 | c8cd96cc781feef4ca7e4981f5298c0ea21f40564e8142acb09ed74c830c41dd
   309126 | b0e815b14257d370066f48f10f6904c0ad200975fb00c3a9232c93a033a3a405
   309125 | 5d68972369d73ae88106594a51bb52e1bfc915cd58603323791d18137095b290
   309124 | b47321379b3957f3faad6984830ac720882a970c716969c4d85aac241b9a0b31
   309123 | 5f2fa613c933bae2f7a390232e2d3a4944f341cb71256b0814009e1aa58b26b7
   309122 | b0b67e3343526f164bb2fa11f701764d556d17e6e485ba6e215648fd8f1a175f
   309121 | e95cdb4fb5425ad371ed7af82bb30bb9349aff12b1cb9ee96fb0ac294122a522
(venv) hp@hp-ubuntu:~/chia-blockchain$ date
Thu 20 May 2021 07:59:13 AM EDT
(venv) hp@hp-ubuntu:~/chia-blockchain$ 
`

Chia Reports 7:30:35
System reports 7:59:13

**Comment by Fragger** [comment]
The time reported there by chia is the time of the block height you are currently at.  So in this case it's just showing you are about 29 minutes behind real-time.

**Comment by mariano54** [comment]
Make sure you put your system clock at the right time, otherwise it will show "not synced".
