### ISSUE TITLE
[BUG] chia  linux  stuck at 1% no errors

### ISSUE THREAD

**Issue by Hardcore-fs** [Chia-Network/chia-blockchain#5593]
ver 1.1.5
setup client on linux centos , built from source, pulled from git.

setup storage directories assigned to root
start chia, as user  it shows processing 1%
still 1 hour at 1% no errors

the rights on the storage directory block the correct functioning of the program
both for plot building & storage, no errors in  log files (/var/log/messages)

program should do a test read write against all  storage & build directories & flag an error is it cannot utilize.

**Comment by MasumovRamin** [comment]
Hello, did you find a fix? I am having the same issue.
