### ISSUE TITLE
Mac 10.13 (High Sierra) stuck at connecting to wallet

### ISSUE THREAD

**Issue by arunzn** [Chia-Network/chia-blockchain#5600]
Mac OS 10.13.6
Macbook Pro  Early 2011

GUI stuck at connecting to wallet

Log:

Running python executable: 
child process success
(node:1121) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
stderr: [1128] Error loading Python lib '/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libpython3.9.dylib': dlopen: dlopen(/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libpython3.9.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon/libintl.8.dylib
closing code: 255

**Comment by Hardcore-fs** [comment]
you are using wrong version of osx.......
i had same issue...
fastest way to fix it , is to pull from the git repository.
ensure you have the correct version of python (use installer from python site)

BUT !!!!! BE CLEAR, it will destroy your mackbook.

you can expect cpu temps at about 90deg.... whilst building, even with fans on max
and the farming will destroy your SSD.

I did a test where i actually removed the back off the macbook and used 2 stand fans to blow air directly on the back of the motherboard as a test... still over 85 deg!!!

**Comment by mariano54** [comment]
Many bugs related to wallet syncing have been fixed. Please update and follow the steps here https://github.com/Chia-Network/chia-blockchain/issues/6993, and continue discussion in that thread instead.
