### ISSUE TITLE
Repeated Block Challenges Index

### ISSUE THREAD

**Issue by Hubert51** [Chia-Network/chia-blockchain#5603]
May I ask if I have repeated index in block challenges, does it matter? Should I do something to try to avoid this situation? I attached the image to this issue.  Thank you!

![Capture](https://user-images.githubusercontent.com/21988107/119007494-46747100-b95f-11eb-9a74-42e8f58e6554.JPG)

**Comment by mariano54** [comment]
Fixed in 1.1.6!
