### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yihao1997** [Chia-Network/chia-blockchain#5605]
**Describe the bug**

"2021-05-20T23:53:46.164 harvester chia.plotting.plot_tools: WARNING  Have multiple copies of the plot D:\1008388682\plot-k32-2021-05-18-03-43-228d423b60695fdc054581435fa76e9f92e679c858ae14682201330c5cf219b2.plot, not adding it."
From the Debug.log

**Expected behavior**

**Screenshots**
There are so much error in each second，i am so confused ,but my  Status / Peak height is ok,what`s wrong with my PC pls ?

**Desktop (please complete the following information):**

- OS: Windows 10 
- OS profession 2009
- CPU: intel i5-9400f
- GUI : chia 1.1.5

**Additional context**
![Uploading 捕获.PNG…]()

![3](https://user-images.githubusercontent.com/42529926/119012476-a94e2280-b9c8-11eb-872a-7735bcffd877.PNG)

**Comment by Steinweber** [comment]
Please check your plot files. You have some plot files twice.
