### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nmmmnu** [Chia-Network/chia-blockchain#5620]
**Describe the bug**
Full node loses synchronization every 40-50 min.

**To Reproduce**
Start chia and let it run. It will synchronize after 4-5 hours or more, but soon after that it loses synchronization.

**Expected behavior**
Full node to say synchronized.

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: CentOS 7
- CPU: i7-6700

**Comment by alexminingrig** [comment]
I'm also facing this issue. I have Chia blockchain 1.1.5 and it has been syncing for 3 days and a half. Right now I'm at  310308/310539 and the difference between the blocks found and blocks synced continues to grows but always with a 200-300 blocks difference and sometimes even more than a thousand blocks difference.

System specs:
Windows 10 2004 (19041.985)
AMD Ryzen 7 3800XT
16GB DDD4 @ 2666Mhz

**Comment by meawoppl** [comment]
See also #4409
