### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pouryarafieerakii** [Chia-Network/chia-blockchain#5625]
Are the plots we build in Chia wallet the original plots?
And canConnect them to the  pool or not?
What is the original plot and the portable plot?
How toBuild them?
If we want to connect to the original Chia pool, We have to start plotting on May 31st?

**Comment by hb020** [comment]
Have you read https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-FAQ ? As pooling is rather new, I imagine this document will be updated over time.

There are 2 types of plots:
The plots that you can create now are called "original" in that document. 
The plots that can participate in a pool are called "portable". You cannot create them yet: the software that will allow you to create portable plots has not yet been released. The release date is probably by the end of this month. You will need to install that new software version before being able to create portable plots.  

And please, this is not a bug. Please close this issue.

**Comment by hb020** [comment]
#5626
