### ISSUE TITLE
What is the original plot and the portable plot?

### ISSUE THREAD

**Issue by pouryarafieerakii** [Chia-Network/chia-blockchain#5626]
Are the plots we build in Chia wallet the original plots?
And canConnect them to the pool or not?
What is the original plot and the portable plot?
How toBuild them?
If we want to connect to the original Chia pool, We have to start plotting on May 31st?

**Comment by gromran** [comment]
what?

**Comment by Plopsi** [comment]
Let me try ^^

1. Yes
2. Yes but only the pool wallet you plotted them for, no pooling yet - just for you and friends.
3. We will se when it's out, if they a distigueshable
4. Not sure, maybe on testnet
5. There is no original chia pool, currently the farmer and pool address should be the same, except if you pooling with friends with a friend wallet.

Bram clarified that the pooling protocol will most probaly go to testnet until end of may, without promise.

Hope that helped ^^

PS: should be discussion not bug

**Comment by pouryarafieerakii** [comment]
thanks for you're attention.
