### ISSUE TITLE
[BUG]There is no way to download version 1.1.6

### ISSUE THREAD

**Issue by lexxfreeman** [Chia-Network/chia-blockchain#5652]
There is no way to download version 1.1.6
![image](https://user-images.githubusercontent.com/54878790/119080078-03cc9a80-ba2c-11eb-9ba8-478c2bea94d3.png)

![image](https://user-images.githubusercontent.com/54878790/119080176-2c549480-ba2c-11eb-974f-63977dd0eab6.png)

**Comment by Marshal27** [comment]
seems the merge went on the main branch vs the latest branch... noticed the update instructions for Ubuntu aren't applicable for installing 1.1.6 either

**Comment by raizac** [comment]
can't get connect to wallet 1.6

**Comment by ShadowXVII** [comment]
Binaries for latest versions aren't immediate. Check back soon.

**Comment by lexxfreeman** [comment]
Apparently the information appeared on the site earlier than on Github

**Comment by lexxfreeman** [comment]
> Binaries for latest versions aren't immediate. Check back soon.

But in fact they should be

**Comment by VincentChuaJiaLe** [comment]
It is available now

https://download.chia.net/latest/Setup-Win64.exe
