### ISSUE TITLE
[BUG] Following update procedure to install 1.1.6, but got 1.1.7 dev 0 installed

### ISSUE THREAD

**Issue by SandboChang** [Chia-Network/chia-blockchain#5655]
**Describe the bug**
Trying to follow the description to install 1.1.6 on ubuntu 20.04.2 on the wiki

**To Reproduce**
Follow the procedure here:
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian

**Expected behavior**
1.1.6 is installed, and chia version should show 1.1.6

**Screenshots**
```
$ chia version
1.1.7.dev0
```

**Desktop (please complete the following information):**

- OS: ubuntu 20.04.2
- OS Version/Flavor: 20.04.2
- CPU: AMD Threadripper 1950X

**Comment by rizlah** [comment]
i got this too on ubuntu, i tried it a second time and got the same issue, so decided to run with it, so far it is syncing, but I did have a sync bug that was stopping me from ever getting to the end, so lets see what happens once I eventually do.

watching this now to see if this is a bug or expected behaviour

**Comment by rthorntn** [comment]
`git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules`

should put you on stable, when I cloned I followed instructions here:

`https://chiadecentral.com/budget-plotting-build/`

And I got dev branch with this "bare" command:

`git clone https://github.com/Chia-Network/chia-blockchain.git`

**Comment by Marshal27** [comment]
+1 on version  1.1.7.dev0 after updating Ubuntu.

Watching thread, I too wonder if this is a trivial oversight in the release or not.

**Comment by Guillaumevk** [comment]
+1 on Debian Buster
I get version 1.1.7.dev0 after following the update instructions available on this page: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL

**Comment by Pockles** [comment]
Getting the same thing.  My remote harvester is acting real strange on this version :D

**Comment by rvp8762446** [comment]
Hi I noticed the same thing before when upgrading from 1.14 to 1.15 (it showed 1.16.dev0). Apparently this can be ignored. Not sure what causes it to show the version to be a ' next release dev0' on Ubuntu/linux, (can't remember exactly), but I've read it is of no concern.

**Comment by chrisalavoine** [comment]
Same issue here. Everything seems work and Sync up ok though.

**Comment by obie73** [comment]
Same issue here.

I wonder if the branch with the 1.1.6 tag could be cloned, instead of cloning the branch with the latest tag.

**Comment by afsarctg** [comment]
same issue here was wondering why always have bug issues with the version in ubuntu 20.04 or latest in GUI go about version 0.0 in CLI checked version 1.1.7.dev0 doesnt looks right am i doing something wrong? point me if i m missing something please thanks.

**Comment by azaryc2s** [comment]
samesies

**Comment by staviq** [comment]
> samesies
> 
> This is what the update instructions on the wiki say tho:
> # If you get RELEASE.dev0 then delete the package-lock.json in chia-blockchain-gui and install.sh again

Nope, does not work.

**Comment by SandboChang** [comment]
> 
> 
> samesies
> 
> This is what the update instructions on the wiki say tho:
> 
> "If you get RELEASE.dev0 then delete the package-lock.json in chia-blockchain-gui and install.sh again"

should have mentioned that I tried this and no joy

**Comment by Eammon** [comment]
Dont worry about this its just a visual bug and doesn't affect any functionality. 1.1.7.dev0 is just an exact mirror of 1.1.6 so nothing to worry about

**Comment by Aesir7924** [comment]
> Getting the same thing. My remote harvester is acting real strange on this version :D

me too My remote harvester cant connect farmer in 1.1.6

**Comment by staviq** [comment]
It seems that this is a problem with the update procedure, if you simply rename the directory, and re-do git clone and reinstall, it works fine, and no working data is lost as it's all kept in the .chia directory.

Just  rename/remove the directory where binaries are, and reinstall.

Reinstall causes no downtime, no re-sync needed, just the couple of minutes that it takes to install from git.

**Comment by pds12345** [comment]
@staviq did this and I am now showing as 1.1.6

unsure why the update procedure kept putting me on 1.1.7.dev0, but a fresh install from source resolved the issue and I lost no data as it is all kept in ~/.chia/

**Comment by alian-win** [comment]
> > Getting the same thing. My remote harvester is acting real strange on this version :D
> 
> me too My remote harvester cant connect farmer in 1.1.6

My remote harvester in 1.1.5, My farmer in 1.1.6. Can't find INFO log in farmer machine, but INFO log in remote harvester seems to be fine

**Comment by alian-win** [comment]
1. deactive
2. get out of the chia-blockchain directory
3. delete the chia-blockchain directory
4. follow the install guide instead of update guide in https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL
Don't worry your keys,db and wallet, They all well protected by the install.sh.

**Comment by andrewmantovani** [comment]
if we rename directory and currently plotting wont that cause an issue?

**Comment by azaryc2s** [comment]
> > > Getting the same thing. My remote harvester is acting real strange on this version :D
> > 
> > 
> > me too My remote harvester cant connect farmer in 1.1.6
> 
> My remote harvester in 1.1.5, My farmer in 1.1.6. Can't find INFO log in farmer machine, but INFO log in remote harvester seems to be fine

if you followed the patch notes, you'd notice, that several INFO logs were moved to DEBUG. This includes the "challenge sent to peer" and "received from peer" for communication between the farmer and harvesters

**Comment by medellin9** [comment]
Also on Ubuntu and got 1.1.7.dev0 version

**Comment by Gnomuz** [comment]
> Also on Ubuntu and got 1.1.7.dev0 version, but doing a fresh install as mention above worked

Same here, the only way to get 1.1.6 version was a fresh install after renaming the old ~/chia-blockchain directory. It's not really a problem, as all static data (keys, config.yaml, databases, ...) are stored under ~/.chia/mainnet and preserved, but I do hope the upgrade process will be more controlled in a near future, as it may lead to disasters when upgrading to major releases, e.g. the one with the pool functionalities ...
Btw, there's exactly the same issue with the docker images where pulling either tags '1.1.6' or 'latest' install 1.1.7.dev0 in the container. As the images are obviously built from the same repo, it may be somehow related.

**Comment by pikolos** [comment]
same here on Ubuntu folowing the upgrade instructions, deleting and doing a fresh clone fixed it.

**Comment by sveip** [comment]
The `latest` tag is probably why this happens, you could try `git checkout 1.1.6` and then install, I would assume that should give you the exact version.

**Comment by ebeng** [comment]
Same here. Installed with git 1.1.7dev0

**Comment by mariano54** [comment]
This is fine, you can ignore that.
