### ISSUE TITLE
[Reloading chia blockchain]

### ISSUE THREAD

**Issue by allzima** [Chia-Network/chia-blockchain#5671]
I reloaded the Chia Blockchain and it got started to connect to the wallet as its written 1 hour still. please tell what to do ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by hb020** [comment]
there is not enough information here for anyone to try to help you. Please provide more context, or close this issue.

**Comment by wbendick** [comment]
Try rebooting
