### ISSUE TITLE
[BUG] Cant conect main node

### ISSUE THREAD

**Issue by Terran976** [Chia-Network/chia-blockchain#5676]
**Describe the bug**
After updating 1.1.6 i cant connect main node. It get almost hour but its still loading

**To Reproduce**

1. Update to 1.1.6
2. Click on "chia"
4. See endless connection

**Expected behavior**
I expected openning my main node, but see only loading

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 10 pro
- OS Version/Flavor: up to date
- CPU: ryzen 3600x

**Additional context**
It happens befor even on 1.1.5, but it always connected after reboot of system. Now reboot doesnt help.

![изображение](https://user-images.githubusercontent.com/84562805/119099283-6cf9e100-ba1f-11eb-8cef-1f45e504a395.png)

**Comment by haroon889** [comment]
it's same as mine. please fix it.pleaseeeee developerrrr

**Comment by wbendick** [comment]
Try rebooting

**Comment by caminotr** [comment]
Same Here!
