### ISSUE TITLE
[BUG] Syncing is fundamentally flawed

### ISSUE THREAD

**Issue by FSys77** [Chia-Network/chia-blockchain#5691]
The Chia blockchain is still relatively young/small, only 3GB - still syncing takes ages. Just imagine how long it would take to start a fresh new client a year from now, with a blockchain size of 50 GB. It would **never** sync.

Please fundamentally rework the syncing process.

**Comment by HighTide** [comment]
I'm not sure how you got the 3TB? Because if I check all the storage used by the blockchain it's only 9GB (the blockchain_v1_mainnet files)

**Comment by FSys77** [comment]
> 
> 
> I'm not sure how you got the 3TB? Because if I check all the storage used by the blockchain it's only 9GB (the blockchain_v1_mainnet files)

Typo :-D 

Changed it to "GB" (since working with Chia everything seems to be TB)

**Comment by miketweaver** [comment]
This is pretty normal among blockchains. Take a look at trying to sync a dogecoin node. A lot of times people will pre-seed the majority of your blockchain using something else, such as bittorrent or a http download.
