### ISSUE TITLE
Remote harvesting is unable to farm blocks.

### ISSUE THREAD

**Issue by jcasc** [Chia-Network/chia-blockchain#5697]
I've been running around 10 remote harvesters with a bunch of people, we have around 2000 plots in total now and have never gotten a single reward since we started plotting. A multiple of the expected time per reward has passed (which had converged quickly and stayed relatively constant throughout). We have now reached the point at which this lack of rewards is highly statistically significant.

There are regular signage point log lines received by all harvesters.
The farmer regularly receives farming_info packages from all harvesters including a realistic number of plots passing tests. (modified the code to show these in log, PR #3600)
The latency of harvesters' responses is below 1 second, in fact there is no discernible difference in the log between the localhost, the local network and the internet harvesters, their responses are often within a few ms.
I am starting to suspect that there is some bug that ignores harvesters after the first one responding or some latency issue that just makes it unlikely or impossible to ever get a block this way.

There are reports like these coming up on social media: https://www.reddit.com/r/chia/comments/nh9jqg/something_wrong_with_multiple_harvestersor_am_i/
(This is not me but seeing it inspired me to write this issue because I'm experiencing the same)

Can anyone confirm that remote harvesting, especially over internet, actually works for them?

**Comment by wbendick** [comment]
I have verified remote harvesting works. What is the total size of your farm?

**Comment by jcasc** [comment]
Slightly over 200TiB now, started plotting around 4 weeks ago, after a short convergence period the expected time stayed between 7 to 9 days over the last slightly over 3 weeks.
