### ISSUE TITLE
Plots missing from my wallet

### ISSUE THREAD

**Issue by Sutejm** [Chia-Network/chia-blockchain#5700]
Hi There i completed 9 plots (100%) and I needed to upgrade the Chia application to 1.16. After the update date the Plots which were completed are no in my walltet. I can see the plot files in the NAS hard drives. Please can you assit.

**Comment by fabitom** [comment]
click Plots tab then on right top click three dots and add plot directory

**Comment by Sutejm** [comment]
> click Plots tab then on right top click three dots and add plot directory

Thank you. I tried this but still didn’t sync.

**Comment by Sutejm** [comment]
I managed to fix the issues, for some reason all my final plots got saved at .2.Tmp file . I just deleted .2.tmp and they are now plot files
