### ISSUE TITLE
Harvesters can not connect to farmer/node since upgrade to 1.1.6 [BUG]

### ISSUE THREAD

**Issue by lucvanbraekel** [Chia-Network/chia-blockchain#5706]
Harvesters on separate machines can not connect to full node after upgrading to 1.1.6.
Error message in harvester log:

> 2021-05-21T12:56:22.291 harvester harvester_server        : DEBUG    Connecting: wss://192.168.1.240:8447/ws, Peer info: {'host': '192.168.1.240', 'port': 8447}
> 2021-05-21T12:56:22.293 harvester harvester_server        : INFO     Cannot connect to host 192.168.1.240:8447 ssl:<ssl.SSLContext object at 0x7f96618e4d40> [Connect call failed ('192.168.1.240', 8447)]
> 

This error started when the farmer node was upgraded from 1.1.5 to 1.1.6.
The error remained after upgrading the harvesters.

**Comment by alian-win** [comment]
1. change the log level in your harveste rmachine to INFO
2. restart harvester
3. check the harvester machine's debug.log

**Comment by lucvanbraekel** [comment]
@alian-win 
```

> 2021-05-21T13:59:44.320 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.1.240', 'port': 8447}
> 2021-05-21T13:59:44.323 harvester harvester_server        : INFO     Cannot connect to host 192.168.1.240:8447 ssl:<ssl.SSLContext object at 0x7fca81ba3440> [Connect call failed ('192.168.1.240', 8447)]


```

**Comment by Aesir7924** [comment]
> Harvesters on separate machines can not connect to full node after upgrading to 1.1.6.
> Error message in harvester log:
> 
> > 2021-05-21T12:56:22.291 harvester harvester_server        : DEBUG    Connecting: wss://192.168.1.240:8447/ws, Peer info: {'host': '192.168.1.240', 'port': 8447}
> > 2021-05-21T12:56:22.293 harvester harvester_server        : INFO     Cannot connect to host 192.168.1.240:8447 ssl:<ssl.SSLContext object at 0x7f96618e4d40> [Connect call failed ('192.168.1.240', 8447)]
> 
> This error started when the farmer node was upgraded from 1.1.5 to 1.1.6.
> The error remained after upgrading the harvesters.

same issuse 
when I switched to 1.1.5, it returned to normal

**Comment by DaanJesus** [comment]
> > Colheitadeiras em máquinas separadas não podem se conectar ao nó completo após a atualização para 1.1.6.  Mensagem de erro no registro da colheitadeira:
> > > 2021-05-21T12:56:22.291 colheitadeira harvester_server : DEBUG Conexão: wss://192.168.1.240:8447/ws, Informações de pares: {'host': '192.168.1.240', 'porto': 8447}  2021-05-21T12:56:22.293 colheitadeira harvester_server : INFO Não é possível conectar-se ao host 192.168.1.240:8447 ssl:
> > 
> > 
> > Esse erro começou quando o nó do agricultor foi atualizado de 1.1.5 para 1.1.6.  O erro permaneceu após a atualização das colheitadeiras.
> 
> mesmo issuse
> quando mudei para 1.1.5, ele voltou ao normal

Como volta para a versão 1.1.5? 
O meu parou de sincronizar depois da atualização...

**Comment by Aesir7924** [comment]
> > > Colheitadeiras em máquinas separadas não podem se conectar ao nó completo após a atualização para 1.1.6.  Mensagem de erro no registro da colheitadeira:
> > > > 2021-05-21T12:56:22.291 colheitadeira harvester_server : DEBUG Conexão: wss://192.168.1.240:8447/ws, Informações de pares: {'host': '192.168.1.240', 'porto': 8447}  2021-05-21T12:56:22.293 colheitadeira harvester_server : INFO Não é possível conectar-se ao host 192.168.1.240:8447 ssl:
> > > 
> > > 
> > > Esse erro começou quando o nó do agricultor foi atualizado de 1.1.5 para 1.1.6.  O erro permaneceu após a atualização das colheitadeiras.
> > 
> > 
> > mesmo issuse
> > quando mudei para 1.1.5, ele voltou ao normal
> 
> Como volta para a versão 1.1.5?
> O meu parou de sincronizar depois da atualização...

uninstall 1.1.6 and then install 1.1.5

**Comment by lucvanbraekel** [comment]
OK I think discovered the reason:
after upgrading, on the main node I did "chia start node" and "chia start harvester" but I forgot "chia start farmer".
Can anyone confirm that the problem goes away after starting the farmer?
On my side it seems to be solved, and it doesn't look like it's a problem with the software.

**Comment by DaanJesus** [comment]
> Ok eu acho que
> descobri o motivo: depois de atualizar, no nó principal eu fiz "chia start node" e "chia start harvester" mas eu esqueci "chia start farmer".
> Alguém pode confirmar que o problema desaparece depois de começar o fazendeiro?
> Do meu lado parece estar resolvido, e não parece ser um problema com o software.

Estou instalando a v1.1.5 para sincronizar. Depois disso irei atualizar novamente e testar. O problema é que eu utilizo o GUI, então terei de criar as variaveis na maquina para rodar no cmd

**Comment by Aesir7924** [comment]
> OK I think discovered the reason:
> after upgrading, on the main node I did "chia start node" and "chia start harvester" but I forgot "chia start farmer".
> Can anyone confirm that the problem goes away after starting the farmer?
> On my side it seems to be solved, and it doesn't look like it's a problem with the software.

No ...

**Comment by Aesir7924** [comment]
> OK I think discovered the reason:
> after upgrading, on the main node I did "chia start node" and "chia start harvester" but I forgot "chia start farmer".
> Can anyone confirm that the problem goes away after starting the farmer?
> On my side it seems to be solved, and it doesn't look like it's a problem with the software.

I try one more time and still cant work, but use 1.1.5 is normal

**Comment by clreinki** [comment]
I have the exact same issue.

**Comment by alian-win** [comment]
> OK I think discovered the reason:
> after upgrading, on the main node I did "chia start node" and "chia start harvester" but I forgot "chia start farmer".
> Can anyone confirm that the problem goes away after starting the farmer?
> On my side it seems to be solved, and it doesn't look like it's a problem with the software.

on the main node ,i alaways "chia start farmer",because i don't need timelord.

**Comment by brezapour81** [comment]
I had to recreate my .chia folder and resync from scratch. All working now.

If people are interest, we are launching a Chia Pool soon called https://Seedpool.org. Check it out.

**Comment by adonig** [comment]
Same problem here after an update from 1.1.5 to 1.1.6. The remote harvesters running on 1.1.6 log:

`2021-05-27T23:29:50.413 harvester harvester_server        : DEBUG    Timeout error connecting to wss://172.31.0.42:8447/ws`

The farmer running on 1.1.6 is up and it's possible to connect from the harvesters using telnet to the 8447 port. The harvester on the farmer's localhost is also able to connect without a problem.

Downgrading the harvesters to 1.1.5 again solves the connection problem, but it feels a bit wrong to run the harvesters on a different version than the farmer.
