### ISSUE TITLE
After upgrade to 1.1.6, I can't find INFO log while farming on mulitple machines

### ISSUE THREAD

**Issue by alian-win** [Chia-Network/chia-blockchain#5709]
according to this article : https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines
while using 1.1.5, I can find INFO log like 'new_signage_point_harvester to peer 'and 'farming_info from peer' in my main machine's debug.log
after upgraded to 1.1.6, I can't find INFO log like above in my main machine's debug.log, But log in my havester machine which is in 1.1.5 seems to be fine.
my config.yaml is like this:
```yaml
farmer:
  full_node_peer:
    host: localhost
    port: 8444
  harvester_peer:
    host: localhost
    port: 8448
  logging: &id001
    log_filename: log/debug.log
    log_level: INFO
    log_maxfilesrotation: 7
    log_stdout: false

**Comment by MachiAngel** [comment]
same

**Comment by MachiAngel** [comment]
Comfrimed , try set log_level to DEBUG

**Comment by miketweaver** [comment]
> Many safe warnings have been changed to DEBUG, and the INFO level log has been simplified and made smaller
https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md

**Comment by michael-pptf** [comment]
As a peer has pointed out, some INFO level log info was moved to DEBUG category. However, this isn't reflected anywhere in the changelog.

I spent hours troubleshooting my farmer, just because of this change.

**Comment by alian-win** [comment]
thx everybody~,

**Comment by joncav** [comment]
Thx for this report - helpful.
