### ISSUE TITLE
[BUG] not found plots ubuntu 20.04

### ISSUE THREAD

**Issue by filip73** [Chia-Network/chia-blockchain#5714]
Everything was ok, and from one moment to the next after restarting the pc he stopped recognizing 50 plots. After continuing to mine and plot he only recognized a few plots on any of the discs. I have several disks with entire plots that you don't recognize. Now I am plotting with the swars for the disks that after updating the wallet and being syncro still without recognizing any plot. The settings were done well in swars and it works without fail. Can you help? Thanks

**Comment by filip73** [comment]
what bothers me is not losing plots now it’s almost 100, the problem is that the 2 machines are plotting well and they’re all lost in the wallet. I already turned off the computers until I realized what was going on ...

**Comment by wbendick** [comment]
Can you verify the top level directories the plots are in, are present in config.yaml?

**Comment by 18650nerd** [comment]
Ubuntu doesn’t automount, click on every drive in the file manager to be sure they are mounted, and wait 30sec for chia to catch-up.

**Comment by mandees** [comment]
If you have multiple disks mounted, chances are that after a restart the mnemonic paths when the disks are mounted changed, while the ones in the chia config file remained the same.    

Add the directories once again and you'll be good to go.
