### ISSUE TITLE
[BUG] 1.1.6 will only show outgoing connections.

### ISSUE THREAD

**Issue by stolk** [Chia-Network/chia-blockchain#5725]
**Describe the bug**
Chia 1.1.5 would show all connections with `chia show -c`

As of Chia 1.1.6 it seems that it will only show a few, which I suspect are the outgoing connections only?

**To Reproduce**
* upgrade to 1.1.6
* Do: `chia show -c`

**Expected behavior**
Al connections listed.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- Ubuntu 20.10
- CPU: Xeon W2140B

**Additional context**
-

**Comment by mariano54** [comment]
looks like your port 8444 is not open

**Comment by stolk** [comment]
Thanks @mariano54 that was indeed the case. Not sure what happened there, it used to be open.

**Comment by stolk** [comment]
I've disabled uPnP, I have forwarded the port 8444 to the right PC on my LAN. I've verified with both a telnet publicIP 8444 and this website: 
![image](https://user-images.githubusercontent.com/455280/119175265-759de780-ba1e-11eb-9eb8-d8112b48d97a.png)

And yet, much fewer connections than on 1.1.5 ?

**Comment by stolk** [comment]
I noticed that `chia start all` will not start introducer, and does start timelord. Am I supposed to run the introducer as well, on the full node?

**Comment by stolk** [comment]
The list is slowly growing again.
