### ISSUE TITLE
[BUG] Windows is leaving hanging processes - preventing restarts or GUI reload

### ISSUE THREAD

**Issue by digplan** [Chia-Network/chia-blockchain#5726]
**Describe the bug**
(Windows 10, Chia v1.1.6 and previous) 
After chia stop all command, cannot restart harvester. Also symptom, GUI hangs on 'Connecting to Wallet'

**To Reproduce**

1. Go to command line and enter chia stop all
2. Attempt to restart the harvester and daemon "chia start harvester -r"
3. Error "cannot connect to daemon" - local port is already bound (hanging process) 

1. Attempt to Reload the GUI. View-Force Reload
2. GUI hangs on Connecting to Wallet

**Expected behavior**
Harvester should restart. GUI should reload.

Resolution:
In Task Manager, kill all start_wallet.exe, start_harvester.exe, daemon.exe processes.  Then start the GUI.  Works successfully.  Please allow stop all to kill all open processes, or at least release ports to allow restart.

**Comment by cristi71000** [comment]
same for me

**Comment by Connor-Knabe** [comment]
> same for me

If restarting doesn't fix it you can try moving all of the files in C:\Users\%username%\.chia\mainnet\wallet\db to a new folder called backup in that same directory and try starting again

This fixed it for me
