### ISSUE TITLE
[BUG]Failed connection to wss://loacalhost:55400

### ISSUE THREAD

**Issue by yigehaobb** [Chia-Network/chia-blockchain#5727]
Failed connection to wss://loacalhost:55400
![QQ截图20210522002312](https://user-images.githubusercontent.com/8196320/119169084-314d2e80-ba94-11eb-86d8-0346d3dbefad.png)

**Comment by ArcadeKIlla** [comment]
Getting the same thing repeated in my logs files.

**Comment by gribliq** [comment]
same problem, I thought that the update would solve

**Comment by gribliq** [comment]
It seems that I have the solution, the only thing I did is overwrite the initial-config.yaml file
here it is
https://github.com/Chia-Network/chia-blockchain/edit/main/chia/util/initial-config.yaml#L273

**Comment by yigehaobb** [comment]
> 看来我有解决方法，我唯一要做的就是覆盖initial-config.yaml文件，
> 这里是
> [https://github.com/Chia-Network/chia-blockchain/edit/main/chia/util/initial -config.yaml＃L273](https://github.com/Chia-Network/chia-blockchain/edit/main/chia/util/initial-config.yaml#L273)

I've replaced it, but I still can't

**Comment by anderzheng** [comment]
same problem

**Comment by pfinazzo** [comment]
this is happening to me on version 1.2.11, can't connect to wallet :(
