### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DaanJesus** [Chia-Network/chia-blockchain#5731]
Ja faz 1 semana que estou tentando minerar, porém o Chia Blockchain não sai do "Não Sincronizado". Percebi também que o "start_full_node" não inicia nos processos... Alguém pode me ajudar?

**Comment by lucasca73** [comment]
Olá @DaanJesus nao sou da equipe do chia mas passei por algo parecido talvez possa te ajudar. Primeiramente vc poderia compartilhar o log da chia? de repente a gente consegue encontrar alguma pista. Para encontrar a pasta de log no windows ela fica em um diretorio parecido com esse C:\Users\lucas\.chia\mainnet\log

caso nao tenha muita informaçao de log nos arquivos seria interessante primeiro alterar o arquivo de configuraçao que ficam em C:\Users\lucas\.chia\mainnet\config\config.yaml

especificamente na parte  log_level de WARNING que é o padrao, para INFO.
log_level: INFO

fecha o GUI do chia e abre de novo para ele pode gerar os logs no level que a gente quer. Depois posta o log aqui.
