### ISSUE TITLE
[BUG] Full Node menu is not loading

### ISSUE THREAD

**Issue by Orest-rt** [Chia-Network/chia-blockchain#5732]
Hello!

I have a problem for several days. When i start Chia client i can see just loading circles in Full Node. Farming doesn't working and writes "wait for sync". How can i fix it?

Thank you!

PC: Win10, Core i5 10400, 16 GB RAM
![123](https://user-images.githubusercontent.com/84587871/119171408-36e34e00-ba6d-11eb-9e84-b058507fe5da.png)

**Comment by adriansilviu10** [comment]
same problem with 5 dais.......y not open the port 8444...its no posible....y dont to resoved

**Comment by rdklcryptomgck** [comment]
Same problem here on iMac: macOS Catalina 10.15.7, 3.4 GHz Quad-Core Intel Core i7, 32 GB RAM

**Comment by adriansilviu10** [comment]
> Same problem here on iMac: macOS Catalina 10.15.7, 3.4 GHz Quad-Core Intel Core i7, 32 GB RAM

I solved the problem:
 first step done: restart the modem directly from the net operator after windows new full ubgrade and after chia 1.1.5 and it worked
the problem is from the net modem
