### ISSUE TITLE
1.1.6 BORRAR PLOTS[BUG]

### ISSUE THREAD

**Issue by torresllados** [Chia-Network/chia-blockchain#5745]
HOY ACTUALIZE LA VERSION 1.1.6 Y E INTENTADO BORRAR DESDE LA GUI LOS PLOTS EN ESPERA PARA CANCELARLOS PERO EL BOTON ELIMINAR APARECE BUGEADO.

**Comment by russer-cba** [comment]
No es bug, lo dice las notas de la versión, la única forma que encontré fue forzar cerrar la app que plotea (en el administrador de tareas -> más detalles -> detalles -> chia.exe (ahí tenés que tener la columna de tiempo de CPU visible y buscás la que se coincida con la fecha/hora del plot.que quieras borrar) -> luego vas a la carpeta temporal y borrás los .tmp del plot de la fecha/hora que querias borrar y listo...esto te sirve si te quedás sin espacio o memoria ram disponible por algún tema y par que no dejen de funcionar todos los demás plots (ej: más plots simultáneos de los que soporta tu máquina que con el delay funcionaba ok, lo que si, hasta que no reinicies la app/gui, en el harvester va a aparecerte la parcela borrada en el porcentaje que cerraste el proceso)

**Comment by JorgeOctavioNA** [comment]
> No es bug, lo dice las notas de la versión, la única forma que encontré fue forzar cerrar la app que plotea (en el administrador de tareas -> más detalles -> detalles -> chia.exe (ahí tenés que tener la columna de tiempo de CPU visible y buscás la que se coincida con la fecha/hora del plot.que quieras borrar) -> luego vas a la carpeta temporal y borrás los .tmp del plot de la fecha/hora que querias borrar y listo...esto te sirve si te quedás sin espacio o memoria ram disponible por algún tema y par que no dejen de funcionar todos los demás plots (ej: más plots simultáneos de los que soporta tu máquina que con el delay funcionaba ok, lo que si, hasta que no reinicies la app/gui, en el harvester va a aparecerte la parcela borrada en el porcentaje que cerraste el proceso)

No se refiere a los Plots que están en proceso, sino a los que están en COLA y estoy de acuerdo con él, debería poder ser eliminados pues no están iniciados.

**Comment by russer-cba** [comment]
> > No es bug, lo dice las notas de la versión, la única forma que encontré fue forzar cerrar la app que plotea (en el administrador de tareas -> más detalles -> detalles -> chia.exe (ahí tenés que tener la columna de tiempo de CPU visible y buscás la que se coincida con la fecha/hora del plot.que quieras borrar) -> luego vas a la carpeta temporal y borrás los .tmp del plot de la fecha/hora que querias borrar y listo...esto te sirve si te quedás sin espacio o memoria ram disponible por algún tema y par que no dejen de funcionar todos los demás plots (ej: más plots simultáneos de los que soporta tu máquina que con el delay funcionaba ok, lo que si, hasta que no reinicies la app/gui, en el harvester va a aparecerte la parcela borrada en el porcentaje que cerraste el proceso)
> 
> No se refiere a los Plots que están en proceso, sino a los que están en COLA y estoy de acuerdo con él, debería poder ser eliminados pues no están iniciados.

Y obviamente que deberían poder ser eliminados como en versiones anteriores, sólo digo lo que dicen las notas de la versión 1.1.6, que si las leés o el op, no preguntarían pavadas...lo mismo, si ponés la versión 1.1.5 o anterior vas a poder borrar los plots en cualquier estado, sean en la COLA o ya PLOTEANDO o en su defecto, si dejan la 1.1.6 pueden hacer eso que dije para borrar los plots que ya iniciaron o estan en la cola y listo, y repito la primera frase de mi respuesta, NO es un BUG, esta deliberadamente desactivado...
