### ISSUE TITLE
So which is the latest version?

### ISSUE THREAD

**Issue by q1k** [Chia-Network/chia-blockchain#5746]
I updated on windows and it shows 1.1.6
But on linux it shows 1.1.7dev

Where is 1.1.7 for windows?

And what is different?

**Comment by heus12** [comment]
use git，you can fetch the latest version

**Comment by q1k** [comment]
how do i do that on windows?

**Comment by danarbraz** [comment]
# If you get RELEASE.dev0 then delete the package-lock.json in chia-blockchain-gui and install.sh again

https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL

**Comment by jneuhauser** [comment]
Same here...
Updated to latest, which is 1.1.6 according to latest git commit but `pip list` shows `chia-blockchain       1.1.7.dev0`.
I couldn't find anythin related to 1.1.7 in the git repo, so from where does this come from?
