### ISSUE TITLE
[BUG] --root-path not working

### ISSUE THREAD

**Issue by wiryonolau** [Chia-Network/chia-blockchain#5752]
**Describe the bug**
--root-path options only available for init command, other command default to .chia/mainnet

**To Reproduce**
```bash
$ chia --root-path=/opt/chia init 
Chia directory /opt/chia
Can't find private CA, creating a new one in /opt/chia to generate TLS certificates
No keys are present in the keychain. Generate them with 'chia keys generate'

To see your keys, run 'chia keys show'

$ ls -l /opt/chia
-rw-r--r--  1 chia chia 14202 May 21 23:10 config.yaml
drwxr-xr-x 10 chia chia  4096 May 21 23:10 ssl

$ chia --root-path=/opt/chia keys generate
Generating private key
Added private key with public key fingerprint **** and mnemonic ****
Setting the xch destination address for coinbase fees reward to ****
Setting the xch destination address for coinbase reward to ****

$ chia --root-path=/opt/chia keys show
can't find /home/chia/.chia/mainnet/config/config.yaml
** please run `chia init` to migrate or create new config files **
```

Other command also doesn't respect root path options

**Expected behavior**
--root-path should be available for other command as well.

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- Chia Version: 1.1.5 and 1.1.6
- CPU: -

**Additional context**
-

**Comment by wiryonolau** [comment]
Apparently the generated key are save in ~/.local/share/python_keyring. It disregard --root-path.
Still testing

**Comment by vrs** [comment]
I was having a similar problem - don't set --chia-root, instead set the following in your environment to something reasonable: CHIA_ROOT (for chia) and XDG_DATA_HOME (for the keyring).

**Comment by wiryonolau** [comment]
Ah i see. Will test it again, this will make docker run without root better.
