### ISSUE TITLE
Chia Blockchain version is not show

### ISSUE THREAD

**Issue by gonbressan** [Chia-Network/chia-blockchain#5785]
OS: Ubuntu 20.04.5 LTS

![Captura de pantalla de 2021-05-22 08-20-25](https://user-images.githubusercontent.com/20097548/119224799-94f84b80-bad6-11eb-866b-8732da45c39c.png)

**Comment by lvpcguru** [comment]
I am getting the correct 1.1.6 version on windows. following the upgrade
Following the GUI upgrade from [https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian) it upgraded fine and is running 100% better than 1.1.5 but the 1.1.6 gui on Ubuntu shows 0.0 for the version

**Comment by gonbressan** [comment]
My OS is **Ubuntu 20.04.5 LTS**

**Comment by fereehu** [comment]
same for me, but it was a fresh install
cli shows the correct 1.1.6

**Comment by cypressheart** [comment]
Mine was a fresh install and showing the same 0.0 as well.

**Comment by kzsolt4444** [comment]
The bug persist with version 1.1.7

**Comment by gonbressan** [comment]
Hi, when i write "chia version" after update to 1.1.7, i get 1.1.6 yet :(. What happen with you?

Thanks.

**Comment by kzsolt4444** [comment]
Still active on a clean installation on u ubuntu with version 1.2.0

**Comment by marklysze** [comment]
Continues to being an issue on ubuntu with version 1.2.1

**Comment by kzsolt4444** [comment]
Still persist on ubuntu v 1.2.2

**Comment by emlowe** [comment]
This is fixed now in main.
