### ISSUE TITLE
[BUG] Chia Wallet != Chia Explorer

### ISSUE THREAD

**Issue by Blackcode** [Chia-Network/chia-blockchain#5788]
My wallet is empty starting v.1.1.6 and does not reflect the actual value. On 1.1.5 my faucet was visible.

https://www.chiaexplorer.com/blockchain/address/xch1yutpsdz28nsh0z95d6vrps0829njq9d24tv57vts47n7p3lljj8sewzte5

![image](https://user-images.githubusercontent.com/516789/119226907-c0e1f400-bb0b-11eb-8700-ae66f1cd650d.png)

**Comment by blackflash** [comment]
@Blackcode can you try to use `chia wallet show` ?
Seems like its a GUI issue, I have the same issue on Windows 10 GUI 1.1.6 version.

On GUI:
<img width="668" alt="Capture2" src="https://user-images.githubusercontent.com/1943404/119252198-2f29c380-bbab-11eb-9da9-2609f3a34945.PNG">

via command line is correct:
<img width="334" alt="Capture" src="https://user-images.githubusercontent.com/1943404/119252200-33ee7780-bbab-11eb-9b98-b851771bd12d.PNG">

**Comment by katmai** [comment]
i don't think ports 8447,8449 need to be opened for the public, do they?

**Comment by lvpcguru** [comment]
> 
> 
> i don't think ports 8447,8449 need to be opened for the public, do they?

No the only port that should be exposed to the internet is 8444
