### ISSUE TITLE
[BUG] Impossible to get synced: same peer_id error

### ISSUE THREAD

**Issue by fereehu** [Chia-Network/chia-blockchain#5789]
On a freshly installed Ubuntu 20.04, I get the same errors every time like before. Because of struggling to get synced, I reinstalled the system, but getting the same errors. 
8444 port is open, on the router I see connections, but impossible to get connected to other peers, get synced.

Followed the install section here: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian

For the sake of getting synced, I created a new private key, and I'm not using my main one. On my local network, there are right now 0 connections to chia.net. Adding peers doesn't help.

In the config I disabled upnp, modified the WARNING to INFO and the introducer.chia.net to introducer-eu.chia.net, but not helping, the same peer_id still exists. I already got this on my Windows computer, but right now in my local network only this is "online", so I don't think that was the problem before. 

Chia version 1.1.6, but got the same on 1.1.5 as well, but sometimes I could get synced with that.

**Screenshot:**
![image](https://user-images.githubusercontent.com/23026825/119227829-2932d480-bb10-11eb-9d5f-ee52999c6c7d.png)

**Log:**
```
2021-05-22T14:59:56.484 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
  File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
    raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e

2021-05-22T15:00:03.851 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
  File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
    raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e

2021-05-22T15:00:06.037 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-348' coro=<WebSocketWriter.ping() done, defined at /home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-05-22T15:00:11.219 full_node chia.full_node.full_node: INFO     Received 32 peers from DNS seeder.
2021-05-22T15:00:13.035 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-349' coro=<WebSocketWriter.ping() done, defined at /home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-05-22T15:00:13.582 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
  File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
    raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e

2021-05-22T15:00:20.944 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
  File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
    raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e

2021-05-22T15:00:23.036 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-360' coro=<WebSocketWriter.ping() done, defined at /home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-05-22T15:00:25.305 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 0
2021-05-22T15:00:25.306 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 0
2021-05-22T15:00:28.305 full_node chia.full_node.full_node: INFO     Received 32 peers from DNS seeder.
```

What should I do? Why is this happening every time? Should I modify the computer name, or should I get a new IP from the ISP (already have a public IP)?

**Comment by fereehu** [comment]
Getting the same error with CentOS8-stream (fresh installation on the same system)

**Comment by ydipeepo** [comment]
I'm also encountered the same error on:

- Ubuntu 21.04 (GNU/Linux 5.11.0-1008-raspi aarch64)
- Running on docker-ce 20.10.6

And I cleared my DNS caches for routers and nodes, but still get the same error:

```
2021-05-23T18:23:20.452 full_node chia.full_node.full_node: [31mERROR   [0m Exception while querying DNS server: The DNS operation timed out after 32.002888917922974 seconds[0m
```

```
2021-05-23T18:23:49.406 full_node full_node_server        : [32mINFO    [0m Cannot connect to host introducer.chia.net:8444 ssl: [Temporary failure in name resolution][0m
2021-05-23T18:24:18.436 full_node full_node_server        : [32mINFO    [0m Cannot connect to host introducer.chia.net:8444 ssl: [Temporary failure in name resolution][0m
```

Yesterday It was able to sync without any problems tho.

**Comment by lvpcguru** [comment]
> 
> 
> On a freshly installed Ubuntu 20.04, I get the same errors every time like before. Because of struggling to get synced, I reinstalled the system, but getting the same errors.
> 8444 port is open, on the router I see connections, but impossible to get connected to other peers, get synced.
> 
> Followed the install section here: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian
> 
> For the sake of getting synced, I created a new private key, and I'm not using my main one. On my local network, there are right now 0 connections to chia.net. Adding peers doesn't help.
> 
> In the config I disabled upnp, modified the WARNING to INFO and the introducer.chia.net to introducer-eu.chia.net, but not helping, the same peer_id still exists. I already got this on my Windows computer, but right now in my local network only this is "online", so I don't think that was the problem before.
> 
> Chia version 1.1.6, but got the same on 1.1.5 as well, but sometimes I could get synced with that.
> 
> **Screenshot:**
> ![image](https://user-images.githubusercontent.com/23026825/119227829-2932d480-bb10-11eb-9d5f-ee52999c6c7d.png)
> 
> **Log:**
> 
> ```
> 2021-05-22T14:59:56.484 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
>   File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
>     raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
> RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e
> 
> 2021-05-22T15:00:03.851 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
>   File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
>     raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
> RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e
> 
> 2021-05-22T15:00:06.037 full_node asyncio                 : ERROR    Task exception was never retrieved
> future: <Task finished name='Task-348' coro=<WebSocketWriter.ping() done, defined at /home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
> Traceback (most recent call last):
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
>     await self._send_frame(message, WSMsgType.PING)
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
>     self._write(header + mask + message)
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
>     raise ConnectionResetError("Cannot write to closing transport")
> ConnectionResetError: Cannot write to closing transport
> 2021-05-22T15:00:11.219 full_node chia.full_node.full_node: INFO     Received 32 peers from DNS seeder.
> 2021-05-22T15:00:13.035 full_node asyncio                 : ERROR    Task exception was never retrieved
> future: <Task finished name='Task-349' coro=<WebSocketWriter.ping() done, defined at /home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
> Traceback (most recent call last):
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
>     await self._send_frame(message, WSMsgType.PING)
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
>     self._write(header + mask + message)
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
>     raise ConnectionResetError("Cannot write to closing transport")
> ConnectionResetError: Cannot write to closing transport
> 2021-05-22T15:00:13.582 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
>   File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
>     raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
> RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e
> 
> 2021-05-22T15:00:20.944 full_node full_node_server        : ERROR    Exception Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e, exception Stack: Traceback (most recent call last):
>   File "/home/xxx/chia-blockchain/chia/server/server.py", line 378, in start_client
>     raise RuntimeError(f"Trying to connect to a peer ({target_node}) with the same peer_id: {peer_id}")
> RuntimeError: Trying to connect to a peer ({'host': 'introducer-eu.chia.net', 'port': 8444}) with the same peer_id: 4044b6396f0881850b566317bf13ec6b89de15ffba10fdcc76cb081dbe85f80e
> 
> 2021-05-22T15:00:23.036 full_node asyncio                 : ERROR    Task exception was never retrieved
> future: <Task finished name='Task-360' coro=<WebSocketWriter.ping() done, defined at /home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
> Traceback (most recent call last):
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
>     await self._send_frame(message, WSMsgType.PING)
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
>     self._write(header + mask + message)
>   File "/home/xxx/chia-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
>     raise ConnectionResetError("Cannot write to closing transport")
> ConnectionResetError: Cannot write to closing transport
> 2021-05-22T15:00:25.305 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 0
> 2021-05-22T15:00:25.306 wallet chia.wallet.wallet_state_manager: INFO     Confirmed balance amount is 0
> 2021-05-22T15:00:28.305 full_node chia.full_node.full_node: INFO     Received 32 peers from DNS seeder.
> ```
> 
> What should I do? Why is this happening every time? Should I modify the computer name, or should I get a new IP from the ISP (already have a public IP)?

Did you complete your prot forward? you need 8444 NAT and open on the firewall
