### ISSUE TITLE
[BUG]Last Attempted Proof I'm not show how to fix 1.1.6

### ISSUE THREAD

**Issue by Fatoute** [Chia-Network/chia-blockchain#5790]
v. 1.1.6
synce on
connect yes
farming on

last attemted proof : not show
advance : not show

help me please how to fix

**Comment by chenjie** [comment]
If you are on Windows, check your network settings and make sure it's on private network, and also check your firewall.

**Comment by comquer77** [comment]
does not help! I even got the firewall shutdown, but it still stop after enough time.
