### ISSUE TITLE
Final plot gets saved at .2.tmp[BUG]

### ISSUE THREAD

**Issue by Sutejm** [Chia-Network/chia-blockchain#5794]
Not sure why but since I started to plot to my NAS hard drive the final plots are saved as plot.2.tmp. Any reason why this is?

**Comment by joelrb** [comment]
> Not sure why but since I started to plot to my NAS hard drive the final plots are saved as plot.2.tmp. Any reason why this is?

That means it's not done yet. Check the file size it will keep increasing until it's fully written.
