### ISSUE TITLE
[BUG] Impossible to DELETE a PLOT in QUEUE!

### ISSUE THREAD

**Issue by ramsesdeux** [Chia-Network/chia-blockchain#5798]
**Describe the bug**
Select the three dots on a waiting plot in any queue.
The DELETE feature is **greyed out**.

**To Reproduce**

1. Go to 'PLOTS'
2. Click on 'ADD A PLOT'
3. Create a new PLOT QUEUE with at least two plots or more.
4. Start Queue
5. Try to select any plots in queue

**Expected behavior**
Plot in queue should be deleted

**Desktop (please complete the following information):**

- OS: WINDOWS
- OS Version/Flavor: 10

**Comment by casa10** [comment]
Already asked on another topic :  #414
It will be treated soon.

**Comment by MiningforLOLs** [comment]
Also suffering from this after accidentally adding too many parallel plots to the queue. Waiting to see how many finish before the crash. LOL I'm Scared
