### ISSUE TITLE
Old plot suddenly become a huge file full of "\x00" and error "Invalid plot header magic"

### ISSUE THREAD

**Issue by dmazurok** [Chia-Network/chia-blockchain#5826]
I used a plot created back on 06.05.2021. I use hpool, but I don't think it could cause a problem.
The last modification plot date is 06.05.2021 still, but if I read it with python (open(plot).read(100)) I get "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00".
Any ideas how it could happen?
I can't realize how without changing exif it suddenly becomes full of zeros. But I'm pretty sure this plot has been used till today with no problems!
I updated today to 1.1.6 from 1.1.5, maybe that's somehow related to the issue.

**Comment by M3dS0** [comment]
Same Here
