### ISSUE TITLE
Centos 8 GUI installation

### ISSUE THREAD

**Issue by AlexNoxious** [Chia-Network/chia-blockchain#5836]
Hello,

I am trying to install a Chia full node in Centos 8 GUI and after executing the following instructions:

```
curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
sudo yum install -y nodejs

python3.9 -m venv venv
ln -s venv/bin/activate
. ./activate
pip install --upgrade pip
pip install -i https://hosted.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10
```

it returns the error:

```
(venv) [protoss666@chia-node-main ~]$ pip install -i https://hosted.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10
Looking in indexes: https://hosted.chia.net/simple/
ERROR: Could not find a version that satisfies the requirement miniupnpc==2.1 (from versions: none)
ERROR: No matching distribution found for miniupnpc==2.1
(venv) [protoss666@chia-node-main ~]$
```

What could be happening?
I am using Python 1.9.5. I have tried with previous versions but it gives me the same problem.

Regards

Alex

**Comment by aarcro** [comment]
https://hosted.chia.net/simple/miniupnpc/ Looks like you should use 3.8 not 3.9 if you want to use this package repository.

**Comment by lvpcguru** [comment]
have you tried 3.7? the guide doesnt call for 3.9.

also try: 
pip install --extra-index-url https://hosted.chia.net/simple/ chia-blockchain==1.1.6 miniupnpc==2.1


the 1.1.10 doesnt look right to me.

**Comment by AlexNoxious** [comment]
Thank you very much I was able to solve it.
I have installed Python version 3.8.9:

```
...
sudo wget https://www.python.org/ftp/python/3.8.9/Python-3.8.9.tgz
sudo tar -zxvf Python-3.8.9.tgz ; cd Python-3.8.9
...
```

Then I run:

```
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
sudo yum install -y nodejs


python3.8 -m venv venv
ln -s venv/bin/activate
. ./activate
pip install --upgrade pip
pip install --extra-index-url https://hosted.chia.net/simple/ chia-blockchain==1.1.6 miniupnpc==2.1
```

The problem has been solved. Thanks @lvpcguru and @aarcro
