### ISSUE TITLE
Getting a new receive address

### ISSUE THREAD

**Issue by q1k** [Chia-Network/chia-blockchain#5838]
**Describe the bug**
I clicked on the get new receive address button, and the address changed. But in the config files it still shows the old address even after using the mnemonic to login to a clean install of chia. 
So I'm wondering if I can still receive rewards (transactions in general). And will both of these addresses work (same wallet)?

**To Reproduce**
Click on get new receive address in wallet

**Software**
PC is Windows 10,
Chia version was 1.1.5, and 1.1.6 didn't change anything.

==
Will both of these addresses add to my wallet? If not, is there anything to do to fix this?

**Comment by joesdu** [comment]
both working , but i would like to delete my later-generated receiving address.

**Comment by q1k** [comment]
> both working , but i would like to delete my later-generated receiving address.

Same.
If I had known it's gonna be like this, full of inconsistencies, I wouldn't have clicked that button.
The worst part is that there is no confirmation.

**Comment by joesdu** [comment]
> > both working , but i would like to delete my later-generated receiving address.
> 
> Same.
> If I had known it's gonna be like this, full of inconsistencies, I wouldn't have clicked that button.
> The worst part is that there is no confirmation.

Yes, I think so too. I hope it will be optimized later.
