### ISSUE TITLE
[BUG] How to Save CHIA from its current death trajectory - CHINA Problem  &  GUI Problem

### ISSUE THREAD

**Issue by room101-dev** [Chia-Network/chia-blockchain#5839]
**Describe the bug**
GUI is broken, Needs to be dropped until internals are working

**To Reproduce**

chia start -r all

**Expected behavior**

Stop using the GUI

The main problem with chia-net is this Universal GUI that trys to be everything, but is nothing. It trys to manage plots, wallets, and run the block-chain.

You must follow the bitcoind way of doing things, get the cmd-line tools to work first, the GUI should only be for the wallet, but then like bitcoin you need a 'electrum server' for chia, and then you have a wallet gui client, communicating to that wallet-server

Some body early in DEV decided to have this universal GUI that did all, well now  you got nothing, almost 90% of all the reported bugs are related to the GUI not working,  not to the actual internals not working.

I myself quit using anything related to this GUI weeks ago.

CHIA marketing is great you brought in all these new people to crypto with BS about green, plots, farms, haresters, and farmers. The  trouble is that marketing doesn't make great software, and noobs and illiterate technical people shouldnt' be driving the project.

The only familiar name I see here is Richard Kiss, who has done real good work, but all at the cmd-line level. Certainly right now  its questionable whether the block-chain even works or syncs, that should be first priority of all effort. Simply tell people having GUI problems to either wait, or drop down the cmd-line and actually learn how the stuff works.
Determine exactly which cmd-line tools arent working, and fix the problems.

Then of course you have the CHINA problem, where they're doing 90% of the XCH win's, and they're running their own miner that is just collecting XCH, but isn't even running the chia daemon, so in effect 90% of the chia-world is not even collectively working on the block-chain, only a small minority of morons who have been told "You can't use Hpool"

This is a big problem, a problem that is un-recoverable IMHO. At this point to date the CHINESE sent the XCH price to $1600 by IOU out of the loop of chia-dev,  at this point all of ASIA is running the hpool miner, and they're running the hpool plotter, meaning that 90% of the world isn't even running this DUMB CHIA-NET software, this is how pathetic this project has become.

You rushed 5may2021 to bring main-net online, but it was and still is non-functional, then you bring in 10's of 1,000's of newbs pay youtube influencers to tell them to buy 100's of 1,000's of disk components, and now you have 10's of 1,000's of pissed off woke millenial morons.

How can any of  this be fixed? Well priority must be set.

1.) Fixing the china problem? IMHO CHIA must be split chia-classic, and chia-portable ( the cohen  bs he preaches )

2.) Stopping all work on cmd-line and getting the tools to work

3.) Don't work on wallet until you get the block-chain working

5.) Pooling ain't your job, on bitcoin you provide the block_template() call to the miner, or pool, they do the rest. Given that China at this point will NEVER use Chia-NET software going forward and being the one ring that rules them all is kaput.

People need pull their head out of their arse, and declare how they go from here. It's already too late for chia-net to get that 90% CHINA-MINING that hpool has, why in the hell should they give it away, they earned it, they worked for it.

Chia is not the first 'space miner', and certainly it had the best marketing, but you screwed up delivery. It can be recovered but its going to take a long-long time, and then the few cultists who remain will be pissed forever once they discover they got screwed by losing their time & money. 

...

The outcome here is simple. STOP the GUI fix the software, move forward, deliver get_template() to the 100's of people in the USA waiting to create mining-pools for CHIA. You have infinite XCH, let CHINA keep doing what theyre doing, go ahead and obsolete old plots you'll just piss off the world forever on CHIA, and HPOOL & CHINA will never quit using the CHIA classic plots, get over it. They'll figure out a way to redeploy the plots and sell the 10EB as online storage, e.g. rent out other peoples HD space in exchange for nickels, today on HPOOL right now one chia plot earns 7 cents per day.

**Comment by room101-dev** [comment]
It's difficult to solve the block-chain problem, when there are no pools, when the noobs can't correctly run the daemon. Like a 100 horses are waiting for the pool-interface, but CHIA-NET wants to control 100% of the mine-pool, they want to be the centralized master of the 'PLOT". I can see why, its because they want to control how the plot data storage area gets used, and they want to control how people are priced for storage, they also want to make sure they have access to all the data. BIG MAMA, let's call Chia.

The file-coin model is already there, people can choose their pool, people can choose to rent their space, and people can choose to collect a % of the rent. I think for chia-net this is way too much power, the CHIA-NET folks want to control it all, this is why they now have NOTHING. 

China on the other hand has it all, but they don't have open source, everybody is using their source, but its easy to mod the 'call home to mom' and repurpose the mining to yourself, or your pool, and using the HPOOL software, and HPOOL plotter. The important thing is NOBODY is using the chIA-net sw, well except morons influenced by youtube.

The file-chain model is de-centralized, cohen&hoffman want to be the CIA-NSA of all plots in the world, this makes perfect sense, but its un-realistic because the world is not dumb.

Given to date that Chia-NET (hoffman&cohen) have had 6+ months to release the get-template() pool block-chain interface and haven't done so show that either they don't know what they're doing, or they're in collusion with the chinese in the first place, who knows at this point? A few years ago a chinese billionaire funded a team  in UKRAINE called bitcoin-gold, they're still around, chinese billionaires funding money laundering ops in the west is not new.

Maybe that's the entire deal here, run this bitch into the ground then just say, ah shucks we screwed up. Yep, you sure did.

But back to the point, the point that they never released the standard-interface to pooling-miners in the first place, shows they never had any intention to do so. Chew on that, so all you woke-waiters, waiting for the portable pooling protocol, what the hell is it that your actually waiting for?

Had the chia-net release the get-template() interface six months ago, there would now be 100's of pools in the USA, china would have never taken over 90% of chia; The fact that this all transpired IMHO is rather clear that this outcome may have been the desire all along.

**Comment by robo145** [comment]
Simillar thoughts here

**Comment by hidoba** [comment]
With the network growth the money you make from one single plot per day ON AVERAGE is proportionally declining over time.

It means, in solo mining mode if you're not winning anything consistently (say once per week), you're actually loosing on the opportunity to make more money while the network was smaller, unless you use pool.

I wish somebody told that to me 2 weeks ago.

**Comment by CryHenry** [comment]
Al you need to decide if Chia was a well planned project or just a joke, is that we will all have to replot soon to join pools to have any chance of ever seeing any type of reward. Chia is dead and has no future.

**Comment by fullet-tortuga** [comment]
Best and only hope is to shut down the project for at least a year and manage it properly with professional projectmanagement and quality assurance. Start with writing proper software requirements and the rest is the ususal software project life cycle.
