### ISSUE TITLE
not ignoring case sensitify by -d and -t

### ISSUE THREAD

**Issue by Tibi38** [Chia-Network/chia-blockchain#5851]
**Describe the bug**
I try to create a plot under win10 from command prompt. By parameter -t I gave F:\ and by -t I gave f:\
after a lot of hours it start copying the tmp-file from F to f and runs in endlos-error (retrying every 5 minutes) because file already exists.

**To Reproduce**

chia plots create -k 32 -b 4000 -t F:\ -d f:\

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: AMD 8-core

**Comment by gromran** [comment]
Windows drive letters aren't case sensitive

**Comment by Tibi38** [comment]
yes, i know, but the programm seams to make a problem with the parameters

**Comment by gromran** [comment]
use sub dirs

**Comment by Tibi38** [comment]
the workaround is mire easier with correct writing, seams to be the same on linux: #5863

**Comment by Marandil** [comment]
@Tibi38 yup, seems to be essentially the same as #5863 / Chia-Network/chiapos#256, see the latter PR for more details.
