### ISSUE TITLE
[BUG] chia does not test the read/writability of directories before using them, or if the go off line

### ISSUE THREAD

**Issue by Hardcore-fs** [Chia-Network/chia-blockchain#5852]
1. The program should test the read/write ability of any work areas /storage before it uses it for long running processes

failure to do so ends up in plots failing to start , but show processing, or failure at end of job during copy.

2. possible need for "fall back" system when a plot is completed , if the  destination directory is different
 ensure it is still online, if not  allow recovery of finished plot in temp directory, when it is back on line.

**Comment by aarcro** [comment]
I've had this happen. You'll see the errors in the plotter log, saying it will retry in 5 minutes (at least with full disks). I use plotman to suspend the plot, unmount the full disk. and Either mount a replacement, or replace the mount point with a symlink. Then resume the plot, and it manages to finish copying
