### ISSUE TITLE
Lost my chia on my wallet + cannot connect any plots

### ISSUE THREAD

**Issue by ReyStark** [Chia-Network/chia-blockchain#5855]
Dear Sir or Madam, after I moved my hundred of plots to an external harddrive and update to v1.1.6, I have my wallet which shows 0 XCH. Moreover, it becomes impossible to use my plots (0 farming). In  fact they are shown as "invalid". Can you imagine, hundred of plots gone + loosing all my Chia...

Therefore problem:
1. I would like to fix the "not found plots"
2. I would like to fix the "invalid plots"
3. recover my XCH

Thanks for the help

**Comment by blackflash** [comment]
@ReyStark try to check my comment here maybe it will help https://github.com/Chia-Network/chia-blockchain/issues/5788

**Comment by lvpcguru** [comment]
what OS?  

try the CLI. run: cmd 'chia plots show' is your new directory showing there?

**Comment by ReyStark** [comment]
I am on windows 10. Using the CLI chia plots check I get:

"File "chia\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid plot header magic"

**Comment by lvpcguru** [comment]
Try to reconnect to \\MYNAS2\ and restart chia.

Looks like your Nas drive got disconnected, maybe when you rebooted?

**Comment by ReyStark** [comment]
Not it is on. Even my local disks are " not founded"

**Comment by pinnedjoint** [comment]
I have a similar problem. My wallet is stuck at "Connecting to wallet" and all my plots are gone from the wallet, although they are on my drive!! Pretty frustrating!!

(Version 1.1.7)

**Comment by pinnedjoint** [comment]
If i choose the Reload command the wallet simply "hangs"!!!
