### ISSUE TITLE
chia-blockchain: error while loading shared libraries: libasound.so.2:

### ISSUE THREAD

**Issue by sattva2020** [Chia-Network/chia-blockchain#5856]
root@firebird3:~# chia-blockchain
chia-blockchain: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory

**Comment by lvpcguru** [comment]
OS? Version? steps your taking? 

Also what is the chia-blockchain command? are you sure you dont want 'cd chia-blockchain' or something like that? what are you trying to do?
