### ISSUE TITLE
Issue with my Plot[BUG]

### ISSUE THREAD

**Issue by Sutejm** [Chia-Network/chia-blockchain#5857]
Hi - Please can someone help me.

I received this messsage that there is an [Error 22] File not found. Most likely one of my plot folders in Config.yaml has an issue

![image](https://user-images.githubusercontent.com/80568417/119252135-6b0c5b00-bba2-11eb-9dbd-73b365c6d98e.png)

**Comment by lvpcguru** [comment]
what does your config show for plot directories? I hear that issue can show up when you have directories that dont exist, like a share drive that doesnt connect after reboot.

**Comment by Sutejm** [comment]
Thanks Ivpcguru. I figured out what is the issue was. As you just said my Nas Directory went offline and i needed to bring it back on for Chai App to sync the plots.
