### ISSUE TITLE
Why are there records of income, but no money in the wallet?

### ISSUE THREAD

**Issue by shendejun** [Chia-Network/chia-blockchain#5873]
Why are there records of income, but no money in the wallet?
version 1.1.6

**Comment by kennylbj** [comment]
The same issue to me, I got a 1.4998XCH income with miscellaneous type listed in my transaction history but got 0 in my wallet. 

It seems like a bug in 1.1.6, can any developer confirm this?

**Comment by kennylbj** [comment]
Also, refer to this https://github.com/Chia-Network/chia-blockchain/discussions/4138 discussion.
