### ISSUE TITLE
 When creating new plots Failed to open (invalid plots)[BUG]

### ISSUE THREAD

**Issue by StandaKotov** [Chia-Network/chia-blockchain#5877]
**Describe the bug**
Good day. Immediately I apologize for my English and if I am blunt)))
Problem:
When creating plots, they immediately become inoperable.
The old version 1.1.3 did not have these problems
More details:
I always create 14 queues of N plots (ssd 2 tb * 2) Yesterday I managed to sow 28 plots, and I went to sleep peacefully seeing that everything by itself automatically continues to be sown. In the morning I saw that the next 14 plots in the queue are already displayed not in the farming but below as incorrect.
I already have more than 70 incorrect plots and I can't do anything about it

What I did in order to fix this problem:
1. Rebooted Chia and the computer
2. Completely uninstalled Chia and reinstalled
3. Checked RAM for errors

Desktop (please complete the following information

- OS: Win 10
- CPU: Amd 5800x 80gb Ram

Thanks in advance for your understanding and help.

**Comment by lvpcguru** [comment]
What do your plotter logs show for the completed and incomplete plots?

**Comment by StandaKotov** [comment]
> Что показывают ваши журналы плоттера для завершенных и незавершенных участков?

Tell me in more detail where it is. Perhaps I know but I do not understand you

**Comment by lvpcguru** [comment]
> 
> 
> > Что показывают ваши журналы плоттера для завершенных и незавершенных участков?
> 
> Tell me in more detail where it is. Perhaps I know but I do not understand you

Sure thing, plotting logs generated by the GUI are sent to C:\Users\<your_username_here>\.chia\mainnet\plotter\ by default.

**Comment by StandaKotov** [comment]
> > > Что показывают ваши журналы плоттера для завершенных и незавершенных участков?
> > 
> > 
> > Tell me in more detail where it is. Perhaps I know but I do not understand you
> 
> Sure thing, plotting logs generated by the GUI are sent to C:\Users<your_username_here>.chia\mainnet\plotter\ by default.
> 
> You can also read teh log from the GUI on the plot themselves

Thanks, I didn't know that. But unfortunately I can’t see it anymore, because I completely reinstalled Chia ((((

**Comment by StandaKotov** [comment]
> > > Что показывают ваши журналы плоттера для завершенных и незавершенных участков?
> > 
> > 
> > Tell me in more detail where it is. Perhaps I know but I do not understand you
> 
> Sure thing, plotting logs generated by the GUI are sent to C:\Users<your_username_here>.chia\mainnet\plotter\ by default.
> 
> You can also read teh log from the GUI on the plot themselves
Here's what I think .. I have 5800x and I create 14 graphs at once (7 + 7 2tb + 2tb). But on my processor there are only 16 threads .. earlier I specified 2 threads per 1 section. Is this possible due to the fact that I specified more threads than I have?

**Comment by lvpcguru** [comment]
so any changes after the update and a new run with less threads? dont forget you can stagger them so they dont all fight for cpu in the phase 1

**Comment by StandaKotov** [comment]
> so any changes after the update and a new run with less threads? dont forget you can stagger them so they dont all fight for cpu in the phase 1

The adventure continues ((I set 1 thread per process. The first batch of plots did fine .. the second one like this:
 #[
![IMG_20210526_180254](https://user-images.githubusercontent.com/75047677/119695046-17259e80-be4e-11eb-914d-1506a1c339d8.jpg)
![IMG_20210526_180305](https://user-images.githubusercontent.com/75047677/119695052-17be3500-be4e-11eb-9ce5-dfe62aeb2124.jpg)
![IMG_20210526_180400](https://user-images.githubusercontent.com/75047677/119695053-17be3500-be4e-11eb-808e-1bf6463323e4.jpg)


](url)

**Comment by StandaKotov** [comment]
[plotter_log_2ac15d02-a93d-4347-8bbb-8094ef57d75d.txt](https://github.com/Chia-Network/chia-blockchain/files/6548280/plotter_log_2ac15d02-a93d-4347-8bbb-8094ef57d75d.txt)
[plotter_log_3f8a50a8-57fe-4e95-b127-b7f3b6d58e04.txt](https://github.com/Chia-Network/chia-blockchain/files/6548281/plotter_log_3f8a50a8-57fe-4e95-b127-b7f3b6d58e04.txt)
[plotter_log_3fe47c48-45c5-4fd2-99cd-52e200a457cc.txt](https://github.com/Chia-Network/chia-blockchain/files/6548282/plotter_log_3fe47c48-45c5-4fd2-99cd-52e200a457cc.txt)
[plotter_log_4f8f7a4f-53f4-46e9-ab3c-7aacd64a40d0.txt](https://github.com/Chia-Network/chia-blockchain/files/6548283/plotter_log_4f8f7a4f-53f4-46e9-ab3c-7aacd64a40d0.txt)
[plotter_log_5c389bc0-d554-47a4-b7b9-4951a2f25e3d.txt](https://github.com/Chia-Network/chia-blockchain/files/6548284/plotter_log_5c389bc0-d554-47a4-b7b9-4951a2f25e3d.txt)
[plotter_log_6dedb513-fdb6-4ae9-9908-388a373c7178.txt](https://github.com/Chia-Network/chia-blockchain/files/6548285/plotter_log_6dedb513-fdb6-4ae9-9908-388a373c7178.txt)
[plotter_log_7f81e118-aa18-4c3f-8fee-3e77626a033c.txt](https://github.com/Chia-Network/chia-blockchain/files/6548286/plotter_log_7f81e118-aa18-4c3f-8fee-3e77626a033c.txt)
[plotter_log_33fe9e27-e538-423e-bf76-9249048989e2.txt](https://github.com/Chia-Network/chia-blockchain/files/6548288/plotter_log_33fe9e27-e538-423e-bf76-9249048989e2.txt)
[plotter_log_47a5f922-3145-4d7c-a634-2eb42dac45a5.txt](https://github.com/Chia-Network/chia-blockchain/files/6548289/plotter_log_47a5f922-3145-4d7c-a634-2eb42dac45a5.txt)
[plotter_log_68ee8f3e-f112-4194-86fd-c2ad63a707a8.txt](https://github.com/Chia-Network/chia-blockchain/files/6548290/plotter_log_68ee8f3e-f112-4194-86fd-c2ad63a707a8.txt)
[plotter_log_75c9d37d-0e4f-4497-915e-47c4ce54a3d8.txt](https://github.com/Chia-Network/chia-blockchain/files/6548291/plotter_log_75c9d37d-0e4f-4497-915e-47c4ce54a3d8.txt)
[plotter_log_96e3042c-21ea-4ea6-8af6-d753179973a1.txt](https://github.com/Chia-Network/chia-blockchain/files/6548293/plotter_log_96e3042c-21ea-4ea6-8af6-d753179973a1.txt)
[plotter_log_1119212e-9de0-429e-8c2b-e337f19d80a8.txt](https://github.com/Chia-Network/chia-blockchain/files/6548294/plotter_log_1119212e-9de0-429e-8c2b-e337f19d80a8.txt)
[plotter_log_27385302-1055-4480-9de5-ee610ea4f5bb.txt](https://github.com/Chia-Network/chia-blockchain/files/6548295/plotter_log_27385302-1055-4480-9de5-ee610ea4f5bb.txt)
[plotter_log_60131992-cf8b-4be0-a759-2250b6575d1c.txt](https://github.com/Chia-Network/chia-blockchain/files/6548296/plotter_log_60131992-cf8b-4be0-a759-2250b6575d1c.txt)
[plotter_log_a7f98982-aa26-4e61-9bcb-8b21e7cbcaea.txt](https://github.com/Chia-Network/chia-blockchain/files/6548297/plotter_log_a7f98982-aa26-4e61-9bcb-8b21e7cbcaea.txt)
[plotter_log_a132e772-f3a2-454e-9396-a9b19f25dfe3.txt](https://github.com/Chia-Network/chia-blockchain/files/6548298/plotter_log_a132e772-f3a2-454e-9396-a9b19f25dfe3.txt)
[plotter_log_aa30fe9a-314f-4f1b-940a-652f43bdf114.txt](https://github.com/Chia-Network/chia-blockchain/files/6548299/plotter_log_aa30fe9a-314f-4f1b-940a-652f43bdf114.txt)
[plotter_log_ac46eb2e-ee7f-4574-8ed4-89c66c82fe0c.txt](https://github.com/Chia-Network/chia-blockchain/files/6548300/plotter_log_ac46eb2e-ee7f-4574-8ed4-89c66c82fe0c.txt)
[plotter_log_b9d53096-0a6d-42fa-8724-f8b971257256.txt](https://github.com/Chia-Network/chia-blockchain/files/6548301/plotter_log_b9d53096-0a6d-42fa-8724-f8b971257256.txt)
[plotter_log_b40f6fcb-92f2-4371-b1c0-6309973d302f.txt](https://github.com/Chia-Network/chia-blockchain/files/6548302/plotter_log_b40f6fcb-92f2-4371-b1c0-6309973d302f.txt)
[plotter_log_ba94d349-856e-492f-a118-5611448cd9f3.txt](https://github.com/Chia-Network/chia-blockchain/files/6548303/plotter_log_ba94d349-856e-492f-a118-5611448cd9f3.txt)
[plotter_log_bdb62392-7d94-43d8-8a31-76371f70298e.txt](https://github.com/Chia-Network/chia-blockchain/files/6548304/plotter_log_bdb62392-7d94-43d8-8a31-76371f70298e.txt)
[plotter_log_c31fc165-788b-49b2-a766-14dcc8f54785.txt](https://github.com/Chia-Network/chia-blockchain/files/6548305/plotter_log_c31fc165-788b-49b2-a766-14dcc8f54785.txt)
[plotter_log_d0da5da0-6915-46f2-b2fe-efeaa6f73ec7.txt](https://github.com/Chia-Network/chia-blockchain/files/6548306/plotter_log_d0da5da0-6915-46f2-b2fe-efeaa6f73ec7.txt)
[plotter_log_da9566c0-a372-43d2-ab5e-eebabe11e9b6.txt](https://github.com/Chia-Network/chia-blockchain/files/6548307/plotter_log_da9566c0-a372-43d2-ab5e-eebabe11e9b6.txt)
[plotter_log_e41cb693-6aa3-409b-bb5a-f827b3636689.txt](https://github.com/Chia-Network/chia-blockchain/files/6548308/plotter_log_e41cb693-6aa3-409b-bb5a-f827b3636689.txt)
[plotter_log_eac78b51-0e9c-4588-82ac-e029878fcfd6.txt](https://github.com/Chia-Network/chia-blockchain/files/6548309/plotter_log_eac78b51-0e9c-4588-82ac-e029878fcfd6.txt)
[plotter_log_f3ba769a-90bd-44b9-ab64-7fa6a47ddded.txt](https://github.com/Chia-Network/chia-blockchain/files/6548310/plotter_log_f3ba769a-90bd-44b9-ab64-7fa6a47ddded.txt)
[plotter_log_ff45e4c0-7bf5-41af-9628-c35a967a48a2.txt](https://github.com/Chia-Network/chia-blockchain/files/6548311/plotter_log_ff45e4c0-7bf5-41af-9628-c35a967a48a2.txt)

**Comment by StandaKotov** [comment]
As soon as I solve one problem, another arises ((Thank God that those plots that were shown in the photo were workers
