### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zaphrodbblbrx** [Chia-Network/chia-blockchain#5884]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

1. Go to '...' Chia Blockchain, Start Plotting
2. Click on '....' Delete a plot in que that hasnt started yet
4. See error Connecting to wallet. stuck in loop indefinitely. plotting processes in progress never finish

**Expected behavior**
A clear and concise description of what you expected to happen.        Expecting to mine crypto and not deal with broken software

**Screenshots**

**Desktop (please complete the following information):**

- OS:  win 10 fully updated
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [i7 8700

**Additional context**

**Comment by sargonas** [comment]
closing as empty issue with default template
