### ISSUE TITLE
[BUG] chiaexplorer displays incorrect total netspace

### ISSUE THREAD

**Issue by gregjhogan** [Chia-Network/chia-blockchain#5891]
The API appears to return total netspace in PiB (at least that is how that data is displayed [here](https://www.chiaexplorer.com/charts/netspace))
```
https://api2.chiaexplorer.com/chart/netSpace?period=24h
# last data point is 9813.518520011767
```

But the UI shows this value / 1000 as EiB (should be divided by 1024)
https://www.chiaexplorer.com/
![image](https://user-images.githubusercontent.com/4112046/119273738-2217cf00-bbc1-11eb-9984-9c5e3feca929.png)

**Comment by sargonas** [comment]
chiaexplorer.com is not owned or operated by Chia Network, so you'll need to send this their way I'm afraid.
