### ISSUE TITLE
ERROR plot "badbit or failbit after reading"

### ISSUE THREAD

**Issue by pragent** [Chia-Network/chia-blockchain#5895]
2021-05-23T23:41:32.728  chia.plotting.plot_tools         : ERROR    Failed to open file D:\chia\plot-k32-2021-05-18-20-14-1e0fd5101284f1446b9b29dad830613715e444f3786fdc8af53a2b47d09102ef.plot. badbit or failbit after reading size 104 at position 0 Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 189, in process_file
RuntimeError: badbit or failbit after reading size 104 at position 0

I have this error with 30% plots.

I have this setup (windows all)
1) Plotter - server with 16 SAS (install chia and enter 24 words)
2) Remote harvester - copy by lan plots from harvester (connect to main node by /ca)
3) main node - GIU (enter 24 words)

Yesterday all plots are farming good on remote harvester.
Today I power off remote harvester, turned off HDD's and insert them to main node. (main node powered off too)

After start chia, I have this problem

**Comment by turekjiri** [comment]
Your plots are probably corrupted, check them with 'chia plots check'.

**Comment by lvcivs** [comment]
I am seeing such messages too, since upgrading to 1.1.6.

I noticed a couple of times that it popped up while I was copying a plot to the plot directory, so it might be related to that.

**Comment by pragent** [comment]
I solved this problem.
The thing is, I have a cheap LSI installed which works fine with 2TB HDD. When I put 4+ TB in it, it recognized the HDD, but only loaded 2 TB plots. The rest were sent to invalid.

**Comment by lvpcguru** [comment]
> 
> 
> I solved this problem.
> The thing is, I have a cheap LSI installed which works fine with 2TB HDD. When I put 4+ TB in it, it recognized the HDD, but only loaded 2 TB plots. The rest were sent to invalid.

Nice good find. please close the issue as resolved.

**Comment by pragent** [comment]
resolved

**Comment by mjsr** [comment]
I've got plots showing the following error:

## The error
```
$ chia plots check -g plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot
...
2021-06-02T08:22:06.310  chia.plotting.plot_tools         : INFO     Only loading plots that contain "plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot" in the file or directory name
goodbit, failbit, badbit, eofbit: 0402
2021-06-02T08:22:06.323  chia.plotting.plot_tools         : ERROR    Failed to open file /chia/tmp/nvme0/plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot. badbit or failbit after reading size 4 at position 107566584101 Traceback (most recent call last):
  File "/chia/chia-blockchain/chia/plotting/plot_tools.py", line 189, in process_file
    prover = DiskProver(str(filename))
RuntimeError: badbit or failbit after reading size 4 at position 107566584101

2021-06-02T08:22:06.324  chia.plotting.plot_tools         : INFO     Loaded a total of 0 plots of size 0.0 TiB, in 0.03621101379394531 seconds
...
```

## Plot logs

Checking the logs for this specific plot, no apparent errors. (disregard the encoding details related to using tmux):

```
...
Approximate working space used (without final file): 269.388 GiB
Final File size: 101.380 GiB
Total time = 30469.598 seconds. CPU (109.180%) Wed Jun  2 05:28:16 2021
Copied final file from "/chia/tmp/inland0/plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot.2.tmp" to "/chia/tmp/nvme0/plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot.2.tmp"
Copy time = 3085.894 seconds. CPU (3.230%) Wed Jun  2 06:19:42 2021
Removed temp2 file "/chia/tmp/inland0/plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot.2.tmp"? 1
Renamed final file from "/chia/tmp/nvme0/plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot.2.tmp" to "/chia/tmp/nvme0/plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot"
2021-06-02T06:19:45.521  chia.plotting.create_plots       : ^[[32mINFO    ^[[0m Summary:^[[0m
2021-06-02T06:19:45.521  chia.plotting.create_plots       : ^[[32mINFO    ^[[0m Created a total of 1 new plots^[[0m
```

The are no warnings or errors:

```
$ grep -i "\(warning\|error\)" /chia/logs/swar/2021-06-01T21_00_24.862026-07_00.log | wc -l
0
```


## Size differences

The size differs from other plots created on my machine:
```
$ ls -la /chia/tmp/nvme0/*.plot | awk '{print $5 " - " $9}'
99128864768 - /chia/tmp/nvme0/plot-k32-2021-06-01-21-00-49d69aeb863dada31a905c26e0a8c7b0b233e94ff95a0ff46bc98fd2ccb4c51f.plot
97240715264 - /chia/tmp/nvme0/plot-k32-2021-06-01-21-01-f0d1b5463ce5db8193c393bdd855457d490430df3a0378772db8f0949d807e34.plot
91659915264 - /chia/tmp/nvme0/plot-k32-2021-06-01-21-02-6b01bea4fcad87f6d3f8da7dcf4cbbcb8ef1b9d6f19472cbf7dc4fb903fa902f.plot
90653331456 - /chia/tmp/nvme0/plot-k32-2021-06-01-21-02-7985374d502c869bb30a1aa0218dc4f4efad7a2ef8227acf433bbbba2e8fd536.plot
97123041280 - /chia/tmp/nvme0/plot-k32-2021-06-01-21-02-e3de6288f059bf0b3607a85a31fafcaa7cc32ca72054e69a1f496edd63147293.plot
```

Example size of good plots:
```
$ ls -la /chia/final/hdd5/*.plot | awk '{print $5 " - " $9}'
108864350183 - /chia/final/hdd5/plot-k32-2021-05-31-21-19-98bdc5d450f1bbdd15d1dbfe79b978517ca352f928a415027a934f94806ac5f1.plot
108849062123 - /chia/final/hdd5/plot-k32-2021-05-31-21-39-b86449c85d83a4843af127e5c9622088b40d254fc96f21c4f2f77cc211c44e94.plot
```

**Comment by tayanov** [comment]
check your task manager. i see two instanse process of miner. but gui only one. kill em all and restart miner, and it help make invalid plots to efective

**Comment by mjsr** [comment]
> check your task manager. i see two instanse process of miner. but gui only one. kill em all and restart miner, and it help make invalid plots to efective

Not using GUI.

**Comment by maxrozenblum2020** [comment]
> > check your task manager. i see two instanse process of miner. but gui only one. kill em all and restart miner, and it help make invalid plots to efective
> 
> Not using GUI.

Did you ever figure this out? I am having the same issue.

**Comment by cantak** [comment]
This happens to me because HPool locks the plot files. I was not double farming with Chia, rather I was using HPool plus the copy cat Spare.

**Comment by Zeesy** [comment]
> 
> 
> I solved this problem.
> The thing is, I have a cheap LSI installed which works fine with 2TB HDD. When I put 4+ TB in it, it recognized the HDD, but only loaded 2 TB plots. The rest were sent to invalid.

Can you explain a bit more how you resolved this? I am having the same issue with pool plots, 1TB SSD temp, 8TB HDD dest.

**Comment by jacoblroberts** [comment]
I noticed this too.  The bottom line is everything is okay and it typically happens on a new file.  Perhaps it sees it before it's finished copying or perhaps it is a coding error.  You will notice it shows in the 'Plots Passed Filter' count but the farm overview will show differently.  This means the plot is being farmed and you can assume this issue is a false positive.  Even in the venv running 'chia farm summary', it will show the wrong count.   Running a 'chia plot check' shows it as being valid so if you see otherwise, it may be a bad plot.  It all started showing correctly after I restarted the GUI but it may have corrected itself eventually.   I'll post back if I notice it again and let it ride to see what happens.  The key take away from this  is, don't worry about it if it passes the plot check, you are farming it.

**Comment by bingdianchen** [comment]
> 您的绘图可能已损坏，请使用“chia plots check”进行检查。

使用“chia plots check”可以检查到这个问题，这个有办法解决吗？

**Comment by Mr-ARB** [comment]
guys anyone can really help here, the issue doesn't seem to solve, in fact out of 16 drives 6 to 7 gives this issue of plot load time 10 sec and above, hdd are perfectly fine, what am i missing here? 
Error using prover object badbit or failbit
Plot time are like 7 to 20 seconds
This happened for old drives initially i thought so 
2 of my old 2 tb n 6 tb drive
But i checked log onceagain in 8 to 10 days any random of my new 16 tb drives also but the error isn't shown for new drives it just shows 7 to 8 sec for any of the new drive randomly

i dont want to miss a block man coz of this issue, anyone can help here.

Tried ding
plot check all valid plots
restart pc no effects
made new plots no effects
