### ISSUE TITLE
[BUG] Segmentation Fault when doing first plot

### ISSUE THREAD

**Issue by cinderblock** [Chia-Network/chia-blockchain#5899]
**Describe the bug**

When trying to setup a first plot on a linux machine with the cli, I get a segmentation fault after some number of hours.

**To Reproduce**

1. Install chia from git on headless system (no gui install step)
2. Run chia plots create -k 34 -e -b 8000 -r 2 -u 64 -t /mnt/md0/personal/cameron/chia -d /mnt/md0/personal/cameron/temp/chia

(Yes, for now, I'm plotting on an HDD RAID. I know, I'll move away from it)

**Expected behavior**
A plot to be created without error

**Logs**

```log
[...]
        Bucket 62 QS. Ram: 7.752GiB, u_sort min: 28.000GiB, qs min: 7.001GiB. force_qs: 0
        Bucket 63 QS. Ram: 7.752GiB, u_sort min: 28.000GiB, qs min: 7.000GiB. force_qs: 0
        Total matches: 17179275394
Forward propagation table time: 12454.573 seconds. CPU (113.500%) Sun May 23 11:49:32 2021
Computing table 5
        Bucket 0 QS. Ram: 7.752GiB, u_sort min: 14.000GiB, qs min: 7.000GiB. force_qs: 0
Segmentation fault (core dumped)
```

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- CPU: Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
- 32GB RAM (31 GB available)

**Comment by lvpcguru** [comment]
First why are you plotting a k34? And is this a really old processor? If its not you shouldn't use -e

So segmentation faults usually mean you overan the memory. How much RAM does that device have? and is this the only plot your running? 

Try it again but without the -u(the default bucket count is important) and a much lower amount of RAM.

try this one:
`chia plots create -b 4096 -r 2  -t /mnt/md0/personal/cameron/chia -d /mnt/md0/personal/cameron/temp/chia`

**Comment by cinderblock** [comment]
- k34? Why not?
- Because this is the CPU I have on my server. Is there a problem? Even if it's too old, I expect an error message, not a segfault.
- I got the command from the getting started. Just wanted to try something and see what happened.
- Only plot. 31GB of RAM available.
- Trying the suggested command.

**Comment by lvpcguru** [comment]
This is why I wouldnt do larger plots unless its the last plot and intended to fill all the remaining space on the drive:

[https://www.chia.net/2021/02/22/plotting-basics.html](https://www.chia.net/2021/02/22/plotting-basics.html)
"You really never need to plot a plot with a k size larger than 32. Those who do plot larger are either doing them to show off (and we encourage this for fun) or to optimally fill the open space on a specific drive."

**Comment by lvpcguru** [comment]
> 
> 
>     * k34? Why not?
> 
>     * Because this is the CPU I have on my server. Is there a problem? Even if it's too old, I expect an error message, not a segfault.
> 
>     * I got the command from the getting started. Just wanted to try something and see what happened.
> 
>     * Only plot. 31GB of RAM available.
> 
>     * Trying the suggested command.

Ohh and there is nothing wrong with your CPU I intended to so that you only need the -e on really really old ones that throw an error. Its not something you use unless you need to.

**Comment by lvpcguru** [comment]
> 
> 
>     * k34? Why not?
> 
>     * Because this is the CPU I have on my server. Is there a problem? Even if it's too old, I expect an error message, not a segfault.
> 
>     * I got the command from the getting started. Just wanted to try something and see what happened.
> 
>     * Only plot. 31GB of RAM available.
> 
>     * Trying the suggested command.

How did it go? Please remember to close out the issue when its resolved.

**Comment by cinderblock** [comment]
Still going. (Yes, this is not an optimal machine) Looks like it's in the final phase of writing files to the final plot locations:

```log
[...]
Starting phase 3/4: Compression from tmp files into "/mnt/md0/personal/cameron/chia/plot-k32-2021-05-24-11-14-5[...].plot.2.tmp" ... Mon May 24 15:48:25 2021
Compressing tables 1 and 2
        Bucket 0 uniform sort. Ram: 3.940GiB, u_sort min: 1.250GiB, qs min: 0.382GiB.
```

Even if this finishes successfully for me, I would still think this is considered a "bug". So I don't see this as a "support ticket" that should be closed once my particular problem is worked through.

Am I wrong in thinking that, no matter what, a segmentation fault should never happen?

PS. I don't understand your point "unless it's the last plot and intended to fill all the remaining space on the drive". A larger plot would take up more space and not "fit" into the smaller spaces that might be left near the end of filling up a drive.

**Comment by lvpcguru** [comment]
Its a whole thing with the plot sizes. Firstly the min size of 32 plots way faster and need a lot less memory to do it. faster plots mean you get farming with them the whole time you are busy plotting the other half of the next size up.

lets say:

9*32 size fills a 1000GB space because a 32 is like 104-108GB. that leaves 615ish GB just sitting there
there is no functional plot smaller than k32 so you mix k32(108GB) with K33(461GB)
3xk32 and 3xk33 fills 999.192 GB


so basicly "because math" :)

play with this for a better feel [https://plot-plan.chia.foxypool.io/](https://plot-plan.chia.foxypool.io/) plots do vary a little

**Comment by lvpcguru** [comment]
> 
> 
> Still going. (Yes, this is not an optimal machine) Looks like it's in the final phase of writing files to the final plot locations:
> 
> ```
> [...]
> Starting phase 3/4: Compression from tmp files into "/mnt/md0/personal/cameron/chia/plot-k32-2021-05-24-11-14-5[...].plot.2.tmp" ... Mon May 24 15:48:25 2021
> Compressing tables 1 and 2
>         Bucket 0 uniform sort. Ram: 3.940GiB, u_sort min: 1.250GiB, qs min: 0.382GiB.
> ```
> 
> Even if this finishes successfully for me, I would still think this is considered a "bug". So I don't see this as a "support ticket" that should be closed once my particular problem is worked through.
> 
> Am I wrong in thinking that, no matter what, a segmentation fault should never happen?
> 
> PS. I don't understand your point "unless it's the last plot and intended to fill all the remaining space on the drive". A larger plot would take up more space and not "fit" into the smaller spaces that might be left near the end of filling up a drive.

and no its not a bug if your setting are bad :) cant defend the cli from everyone.

**Comment by cinderblock** [comment]
Oh, it's because each block is not an exact power of 2 bigger than the previous. So you can use a few more bytes of available space to give to the network.

I'm curious, is the chance of winning from a k33 polt exactly twice the chance of winning a k32 plot? Or is the chance of winning actually proportional to the exact number of bytes that one manages to allocate? If the former, there seems to be little reason to use larger plots, except to not have to replot once k32 is banned from the network. (I'm sure I can go find this out on my own, but if you can answer quickly, that would be nice)

> and no its not a bug if your setting are bad :) cant defend the cli from everyone.

Does Python not have a way to fail gracefully if too much memory is used or catch other segfault causing software issues?

For some programs, I can see segfaults being expected in some cases. For a popular, entirely userspace, application, imho, it should be impossible to trigger a segfault (unless hardware failures).

**Comment by codergoblin** [comment]
Still have this issue in chia 1.2.1 Ubuntu 20.04.2 LTS x86_64
