### ISSUE TITLE
[BUG]Stuck on connecting to wallet after update to 1.1.6

### ISSUE THREAD

**Issue by StevenZhengTaiwan** [Chia-Network/chia-blockchain#5906]
The title is my problem. 
I just want to add some plots. But I stuck on there.
I am trying to roll back to 1.1.5 and It is working.

I suspect it is about network. I had sync problem before. It is resolved after I open 8444 Port.
Does the wallet on 1.1.6 need to open specific network port?

OS: Win10
CPU  AMD Ryzen 7 3800XT

**Comment by Ozarkstacker** [comment]
My wallet won't even open now. Any help?  Spools with "Connecting to Wallet". What happened?

**Comment by zhangbolily** [comment]
ImportError: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chiavdf.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned

This is the error info output by the wallet on my computer, running on fedora 33.

Obviously the dynamic library is broken, cause the wallet can't start the backend daemon. This is a real bug.

**Comment by lvpcguru** [comment]
> 
> 
> The title is my problem.
> I just want to add some plots. But I stuck on there.
> I am trying to roll back to 1.1.5 and It is working.
> 
> I suspect it is about network. I had sync problem before. It is resolved after I open 8444 Port.
> Does the wallet on 1.1.6 need to open specific network port?
> 
> OS: Win10
> CPU AMD Ryzen 7 3800XT

Looks like a few people tryed to hijack your issue post.... 

Anywho :) do you have anything in your logs?

Also are you able to start the Daemons in the cli? or do those error?

**Comment by siaarzh** [comment]
Save your mnemonic and do a complete reinstall (delete the `chia-blockchain` folder). Without knowing what you did during rollbacks it is impossible to troubleshoot. Just start over, your plots are safe if you know where you stored them.

Consider deleting `peer_table_node.sqlite` (usually located in `~/.chia/mainnet/db/` folder) to refresh nodes list and use the latest [version](https://github.com/Chia-Network/chia-blockchain/releases/). You can also add a bunch of peers manually from this [list](https://chia.keva.app/)

**Comment by ramkom9** [comment]
I had same issue and uninstalled Chia (don't delete any left over files or you will have to sync from 0) then restart PC and install 1.1.6

**Comment by StevenZhengTaiwan** [comment]
> I had same issue and uninstalled Chia (don't delete any left over files or you will have to sync from 0) then restart PC and install 1.1.6

Does it work?

**Comment by ramkom9** [comment]
> > I had same issue and uninstalled Chia (don't delete any left over files or you will have to sync from 0) then restart PC and install 1.1.6
> 
> Does it work?

yep it does
![chia16](https://user-images.githubusercontent.com/31524426/119546737-28a67200-bd8c-11eb-80c0-f5624e443445.jpg)

**Comment by lvpcguru** [comment]
great news. please close this bug then. we need the real bugs visible for developers :)

**Comment by StevenZhengTaiwan** [comment]
I did it same as you. But it is still not working. I try to install in another computer, and it is not working.  I suspect it is network problem. I change my network to mobile 4G network. It is working now.
