### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by netmanno1** [Chia-Network/chia-blockchain#5908]
**Describe the bug**
1. There will be income from PM3:05:12 to PM10:01:08 on 05/23/2021, totaling 2.009XCH. But the total balance and available balance of my wallet is only 0.009XCH. Thanks please fix. 2. Another machine's wallet withdrawal appears to be in a pending state. 3. The account cannot be received in the wallet withdrawal (with photos)。

**To Reproduce**

1. Go to 'wallets'
2. Click on 'Create Transaction'
3. Scroll down to 'History'

**Expected behavior**
I harvested Chia coins in total, and I withdrew them separately. However, 2 CHIA withdrawals appeared to be processed, 1 machine was successfully withdrawn, and 1 machine Farming showed 2xch, but the total wallets were only 0.009。

- OS: [Windows10]
- OS Version/Flavor: [Windows10 Professional]
- CPU: [Intel i7-9700]

**Additional context**

**Comment by lvpcguru** [comment]
What is the address? you can look it up in the blockchain and track down whats going on. Keep in mind this is blockchain so transactions have to be validated and added to a block for them to be available.

Also you mentioned pictures but there are none on this issue?
