### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liuxinsc2008** [Chia-Network/chia-blockchain#5911]
When I'm on a task, there are always a few tasks that show failure，and it shows“RuntimeError: bad allocation”

**Comment by liuxinsc2008** [comment]
OS:server 12r2
CPU:2650V1*2,DDR3 REG ECC 96G

**Comment by siaarzh** [comment]
Please follow the [Contributing Guidelines](https://github.com/Chia-Network/chia-blockchain/blob/9e21716965f6f6250f6fe4b3449a66f20794d3d9/CONTRIBUTING.md) before posting what you believe to be actual bugs and issues. By default you are given a [bug report template](https://github.com/Chia-Network/chia-blockchain/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Please, try to stick to it, as it helps the developers replicate and solve your problem.

**Anything else belongs in the [discussion](https://github.com/Chia-Network/chia-blockchain/discussions) section.**

**Comment by lvpcguru** [comment]
> 
> 
> Please follow the [Contributing Guidelines](https://github.com/Chia-Network/chia-blockchain/blob/9e21716965f6f6250f6fe4b3449a66f20794d3d9/CONTRIBUTING.md) before posting what you believe to be actual bugs and issues. By default you are given a [bug report template](https://github.com/Chia-Network/chia-blockchain/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Please, try to stick to it, as it helps the developers replicate and solve your problem.
> 
> **Anything else belongs in the [discussion](https://github.com/Chia-Network/chia-blockchain/discussions) section.**

I love this response. Do you think github has a way to auto respond with this? Seems like something a script can check easily to validate someone filled out the template and actually made changes to it.

**Comment by siaarzh** [comment]
> > Please follow the [Contributing Guidelines](https://github.com/Chia-Network/chia-blockchain/blob/9e21716965f6f6250f6fe4b3449a66f20794d3d9/CONTRIBUTING.md) before posting what you believe to be actual bugs and issues. By default you are given a [bug report template](https://github.com/Chia-Network/chia-blockchain/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Please, try to stick to it, as it helps the developers replicate and solve your problem.
> > **Anything else belongs in the [discussion](https://github.com/Chia-Network/chia-blockchain/discussions) section.**
> 
> I love this response. Do you think github has a way to auto respond with this? Seems like something a script can check easily to validate someone filled out the template and actually made changes to it.

OFF TOPIC WARNING:

I understand what you mean, but unfortunately modern heuristic algorithms will require more than necessary effort to categorize every type of issue. I try not to use this text everywhere so it seems less "robotic" but at the same time professional, so the answer is probably a "yes"... I'm sure someone made a script that can recognize how much (percentwise) the bug template deviates from the actual post and automatically make a bit post a comment, but again - this would discourage people from taking the message seriously.
