### ISSUE TITLE
[BUG]How to manage my receiving address?

### ISSUE THREAD

**Issue by joesdu** [Chia-Network/chia-blockchain#5912]
**Describe the bug**
I would like to delete my later-generated receiving address, but currently there is no entry or command to use. I've tried reinstalling the GUI client and the single sync is still not the original recipient address after completion. Is it possible to support receiving address management in the future? Can anyone help me? Thanks very much!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:  [Windows 10]
- OS Version/Flavor: [21387]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by lvpcguru** [comment]
this is not a bug. you will have more luck in the discussions getting input.
