### ISSUE TITLE
[BUG]BLANK screen while plotting

### ISSUE THREAD

**Issue by BLADLust1** [Chia-Network/chia-blockchain#5920]
Have an error while plotting. After 6-13 hours chia-blockchain stack with blank screen (see iamge).
All process in task manager wroks (using a memory and a processor rresources) but I can`t see progress and the last file didnt creates.
Have:
Ryzen 3900X, 32GB RAM, 1 SSD 512Gb, 5 HDD 6-8TB
Windows 10 last updated
Chia 1.1.6
![QIP Shot - Screen 024](https://user-images.githubusercontent.com/84702153/119309317-d0318080-bc76-11eb-99e8-4a530c4ca1d9.png)

**Comment by lvpcguru** [comment]
Do you have plot logs in this folder? 
C:\Users\<your_username_here>\.chia\mainnet\plotter\

**Comment by BLADLust1** [comment]
Yes, I have. Logs shows that all ok

**Comment by lvpcguru** [comment]
> 
> 
> Yes, I have. Logs shows that all ok

OK best thing to do is to monitor the plots by checking the logs until they are all completed. then restart chia. if you restart before the plots are done they will fail.

does the debug.log file have anything in it of note? I will say as the GUI is not stable for plotting, and cant close without ending the plots the CLI is the way most people end up getting it done.

**Comment by BLADLust1** [comment]
OK, Thanks. 
Debug log shows nothing with GUI.
Why this trouble appears?

**Comment by lvpcguru** [comment]
no clue. without errors to troubleshoot there isn't much to go on.

**Comment by bcw2235** [comment]
I have this same issue, but it happens on a machine that is not plotting.
