### ISSUE TITLE
[BUG]xch coins are missing

### ISSUE THREAD

**Issue by fengyezhiwu** [Chia-Network/chia-blockchain#5931]
xch coins are missing ver:1.1.6

![a8018abd89e293d421929ebacf7a637](https://user-images.githubusercontent.com/84707525/119326780-db0b0600-bcb4-11eb-9030-dca90cbd825d.jpg)
![d47bf73f67ad363dbc390e388ffba68](https://user-images.githubusercontent.com/84707525/119326804-e1997d80-bcb4-11eb-858c-f7df7d93f8df.jpg)
![7d6a8c6e1ea21163c44bc05e8669670](https://user-images.githubusercontent.com/84707525/119326827-e9592200-bcb4-11eb-9e09-a9c72455fb70.jpg)

address:xch1q3d9np83g3uur2jq65j06xqtnvnjmhq8cr2svkdjvj27rl90l6ps6lvf4v

**Comment by fengyezhiwu** [comment]
I farmed on my own.Previously normal suddenly lost。

**Comment by lvpcguru** [comment]
The explorer show that coin all that coin was spent in block 247,272 and 246,161 did you move it between wallets? or did your pool? Your wallet matches the explorer in that that address had 6 coins and they have all been transferred.

**Comment by casa10** [comment]
> 
> 
> xch coins are missing ver:1.1.6
> 
> ![a8018abd89e293d421929ebacf7a637](https://user-images.githubusercontent.com/84707525/119326780-db0b0600-bcb4-11eb-9030-dca90cbd825d.jpg)
> ![d47bf73f67ad363dbc390e388ffba68](https://user-images.githubusercontent.com/84707525/119326804-e1997d80-bcb4-11eb-858c-f7df7d93f8df.jpg)
> ![7d6a8c6e1ea21163c44bc05e8669670](https://user-images.githubusercontent.com/84707525/119326827-e9592200-bcb4-11eb-9e09-a9c72455fb70.jpg)
> 
> address:xch1q3d9np83g3uur2jq65j06xqtnvnjmhq8cr2svkdjvj27rl90l6ps6lvf4v

really lucky already 6 XCH !! i have 0 for more than 500 plots.

**Comment by fengyezhiwu** [comment]
> The explorer shows that coin all that coin was spent in block 247,272 and 246,161 did you move it between wallets? or did your pool? Your wallet matches the explorer in that that address had 6 coins and they have all been transferred.
> 
> ![image](https://user-images.githubusercontent.com/4685333/119338279-ce0ef800-bc5d-11eb-9d8f-1256e0fb09a7.png)
> 
> those six coins minus the fees got sent to address xch13jzm94939qaamxqyy0he8pgkhg4nvmj6h6nhvqeek02jqgd9f8jslk7mds and then distributed.

No movement.  xch13jzm94939qaamxqyy0he8pgkhg4nvmj6h6nhvqeek02jqgd9f8jslk7mds,Where is the address。What should I do to get it back。

**Comment by fengyezhiwu** [comment]
> really lucky already 6 XCH !! i have 0 for more than 500 plots.

Can not find

**Comment by fengyezhiwu** [comment]
My wallet matches the explorer in that that address had 6 coins and they have all been transferred.xch13jzm94939qaamxqyy0he8pgkhg4nvmj6h6nhvqeek02jqgd9f8jslk7mds,Where is the address。What should I do to get it back。

**Comment by fengyezhiwu** [comment]
Wallet history has no expense record

**Comment by lvpcguru** [comment]
> 
> 
> Wallet history has no expense record

the blockchain explorer says there are expense records. did you not transfer funds? Did you provide anyone else with your public keys of mnemonic phrase?

**Comment by Tinphan76123** [comment]
có thể là lỗi ổ cứng không nhỉ?

**Comment by fengyezhiwu** [comment]
> > Wallet history has no expense record
> 
> the blockchain explorer says there are expense records. did you not transfer funds? Did you provide anyone else with your public keys of mnemonic phrase?

provide anyone else with your public keys of mnemonic phrase.What should I do to get it back。

**Comment by fengyezhiwu** [comment]
Delete DB folder, resynchronize or not

**Comment by nuistzj2014** [comment]
So do I. The same phenomenon，chiaexplorer show spent status. I've never send tx.

**Comment by lvpcguru** [comment]
> 
> 
> So do I. The same phenomenon，chiaexplorer show spent status. I've never send tx.

Its not a phenomenon, the reason chiaexplorer can see it at all is that its the public block chain. By design you cant send anything without access to your private keys, and you generally cant reverse a transaction that is approved and recorded by the network.

I am sorry for your loss, it looks like its starting to happen a lot which means malware is likely starting to make the rounds that understands chia. 

- Dont ever share your mnemonic with anyone
- Dont install anyone elses scripts or wallet software you cant confirm as safe(ie. review the source)
- Dont leave your systems open to the internet

**Comment by keliew** [comment]
Most likely have used a different plotting software which knows your mnemonics and/or part of a pool, whom you believed that you aren't compromised by giving your mnemonics.
