### ISSUE TITLE
Problem view or real problem ? (plots/harvest)

### ISSUE THREAD

**Issue by xguya** [Chia-Network/chia-blockchain#5932]
Hello.  I have about 3000 plots (98 on my main machine where running gui client and 2900 on 20 harvest machine), I see this in Farm. Is normal or I'm losing challenge? 

![plots](https://user-images.githubusercontent.com/34923071/119313671-1f29e680-bc74-11eb-8221-07e7d49f704f.png)

**Comment by lvpcguru** [comment]
This is normal, each harvester is individually reporting for each challenge. Please take a look at the wiki for more information on how this works: [https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-plot-filter-and-why-didnt-my-plot-pass-it](https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-plot-filter-and-why-didnt-my-plot-pass-it)

In short. this screenshot says: 
for this challenge one harvester had 0 plots that made it past the magic filter and a few did (1/90,1/50,1/104) and then out of those you found 0 proofs.
