### ISSUE TITLE
O programa não abre

### ISSUE THREAD

**Issue by juliootoni** [Chia-Network/chia-blockchain#5944]
O programa não abre fica so carregando

fica com a tela branca carregando

processador xeon e32220v6

- OS: windows 10 8gb de ram 1 tb ssd
- OS atualizado
- CPU:  Intel Xeon e32220v6
![Captura de Tela (1)](https://user-images.githubusercontent.com/83351576/119360018-92395a00-bc80-11eb-88fa-e0e6e69aa09d.png)
![Captura de Tela (1)](https://user-images.githubusercontent.com/83351576/119360204-c0b73500-bc80-11eb-83bc-500c30b15654.png)

-

**Comment by ddecoBA** [comment]
você está com a versão 1.1.6?

**Comment by juliootoni** [comment]
Sim, tentei outras versões mas não funcionou.
Realizei o processo de apagar a wallet e voltou a funcionar.
https://youtu.be/836HaeLLpxA


Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado:segunda-feira, 24 de maio de 2021 19:34
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [Chia-Network/chia-blockchain] O programa não abre (#5944)


você está com a versão 1.1.6?
