### ISSUE TITLE
[BUG] Lost all my coin, Please help

### ISSUE THREAD

**Issue by khangtroc** [Chia-Network/chia-blockchain#5948]
Hello bothers
today i open my wallet and it show 0 xch, i was farmed 12 xch this month, where are my coin gone ? how can i get it back ? pls help me, how i can contact support team ? i very sad now
my first address: xch1qulu7j09s8n77tv2wv8rf9e90k34rd5q7wvh5uwcj2zavfmcsxxsyrk6mk
the second : xch12y66t88lymp8kp0atrcfqrv754dulhrapstf6efaqt2hajjaqkgq68k9g3
Chia explorer show they spent at height 312052, same with my second address , i very confuse :((
![1](https://user-images.githubusercontent.com/84728824/119373032-2ee01400-bce2-11eb-994b-6e60e30fed8d.jpg)
![2](https://user-images.githubusercontent.com/84728824/119373036-30a9d780-bce2-11eb-9fd7-cbf82147b793.jpg)
![3](https://user-images.githubusercontent.com/84728824/119373039-31426e00-bce2-11eb-91a4-7071e4900473.jpg)
![4](https://user-images.githubusercontent.com/84728824/119373043-31db0480-bce2-11eb-9dd5-efb9ea27b154.jpg)
![5](https://user-images.githubusercontent.com/84728824/119373047-32739b00-bce2-11eb-8254-e2e605aae93d.jpg)

**Comment by lvpcguru** [comment]
As several of these popped up over the last few hours I am wondering if there is a bug causing accidental transactions. It is also possible that someone is remotely triggering the transaction if an [RPC port is left open](https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces#push_tx).

The ports that should NEVER be accessible from the outside:
Daemon: 55400
Full Node: 8555
Farmer: 8559
Harvester: 8560
Wallet: 9256

If someone forwards all ports to their node and not just the 8444 one needed to sync this could easily be open to the internet. check https://www.yougetsignal.com/tools/open-ports/ to make sure those are not open.

Example of an api call [https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces#send_transaction](https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces#send_transaction)

I am going to play with it a little today and see what authentication is required for the API. If anyone already has this info please speak up.

other issues possibly related to this one: [https://github.com/Chia-Network/chia-blockchain/issues/5947](https://github.com/Chia-Network/chia-blockchain/issues/5947),  [https://github.com/Chia-Network/chia-blockchain/issues/5931](https://github.com/Chia-Network/chia-blockchain/issues/5931),  [https://github.com/Chia-Network/chia-blockchain/issues/5908](https://github.com/Chia-Network/chia-blockchain/issues/5908), [https://github.com/Chia-Network/chia-blockchain/discussions/5956](https://github.com/Chia-Network/chia-blockchain/discussions/5956)

**Comment by harvestpool** [comment]
>  all the fun API stuff requires the certs

But those certs are located without encryption in easy-to-access locations.  Anyone with remote access, or malware, can easily hijack the Chia node since none of the sensitive information is encrypted/password protected.

**Comment by fengyezhiwu** [comment]
I have the same problem. I don't know how to solve it. Who knows how to solve it

**Comment by nuistzj2014** [comment]
So do I. That's a big bug , maybe a UTXO bug.

**Comment by mariano54** [comment]
It's possible you have some malware on your computer. I recommend reinstalling chia farmer on a new computer. For anyone else, please try to send coins to an offline wallet or to a computer that is not often connected to the internet.

**Comment by khangtroc** [comment]
Why my last reward is 0.2499 while all my previous rewards were 0.25+1.75 ? 
Why when I received last reward all my coin gone too at same time ? 
Why i reinstall os and app chia, after synced my receive address always show 2nd address while it show my first address during syncing ?  
If i was haked why the hacker only take my xch when i have some eth in my computer still safe ?
And why my some rig farming eth in my LAN always safe a year ago, never  been changed wallet address in bat file
Why i scan my pc by some software they said my computer not attacked and i still lost coin. 
why the xch wallet has not password or 2fa security?

**Comment by harvestpool** [comment]
> why the xch wallet has not password or 2fa security?

Yeah.  It's completely open and unencrypted.  Very little attention to security in this client.

**Comment by fengyezhiwu** [comment]
> Why my last reward is 0.2499 while all my previous rewards were 0.25+1.75 ?
> Why when I received last reward all my coin gone too at same time ?
> Why i reinstall os and app chia, after synced my receive address always show 2nd address while it show my first address during syncing ?
> If i was haked why the hacker only take my xch when i have some eth in my computer still safe ?
> And why my some rig farming eth in my LAN always safe a year ago, never been changed wallet address in bat file
> Why i scan my pc by some software they said my computer not attacked and i still lost coin.
> why the xch wallet has not password or 2fa security?

I have the same problem. I don't know how to solve it.

**Comment by NeverTeaser** [comment]
Waiting for some solution

**Comment by keliew** [comment]
Most likely have used a different plotting software which knows your mnemonics and/or part of a pool, whom you believed that you aren't compromised by giving your mnemonics.

**Comment by khangtroc** [comment]
> Most likely have used a different plotting software which knows your mnemonics and/or part of a pool, whom you believed that you aren't compromised by giving your mnemonics.

I plot and farm only by chia app

**Comment by harvestpool** [comment]
@khangtroc
> I plot and farm only by chia app

The app is not secure.  If you want to plot securely, pass just the public keys to the plotter.  Farm on a machine with good perimeter security.

**Comment by Leyzuo** [comment]
I had 20 XCHs stolen,You also might have given away your keys,

**Comment by verabeniel** [comment]
I have the same problem . Last week I open the chia app and my wallet shows 0xch when I had 2xch until this day. There is no security for us! I am farming solo and only have the chia blockchain official client, so the problem is from the developers of chia blockchain and they don't do nothing to recover our xch!!!

**Comment by Leyzuo** [comment]
I am victim as well,I have no idea how to solve it.With numerous
searchings，I have to confess I l have lost them.

verabeniel ***@***.***> 于 2021年6月10日周四 00:10写道：

**Comment by PatMateluna** [comment]
I lost 15 xch coin after doing software update to latest version 1.5.0
