### ISSUE TITLE
[BUG] Wallet show wrong XCH incomming outgoing

### ISSUE THREAD

**Issue by mech2you** [Chia-Network/chia-blockchain#5950]
Here i became 2 XCH... I sold it an this day.
![image](https://user-images.githubusercontent.com/61209759/119377275-380aba00-bcbd-11eb-8791-3e5dc6cc413f.png)

This Image ist now... I synct 2 times my wallet on different PC but the wrong number of the income an outcome ist still there. I use version number 1.1.6 of chia now. 
![image](https://user-images.githubusercontent.com/61209759/119377024-ec581080-bcbc-11eb-8125-93eb9d7ae77e.png)

**Comment by n404an** [comment]
Think about how the developers will look for what you show.
What data can they take from these screenshots?
How can I find you on the blockchain?
Just think ...

**Comment by mech2you** [comment]
hi, the black picture ist made on 05.03.2021. You can see that i transferred 1.75 and 0.25 XCH to a other Wallet. The second one is now. Ther ist only income no outgoing... The wallet coins are right but the outgoing coins are not showing. Here ist the full screen with the wallet adress ;) sorry i am new in this stuff  
![image](https://user-images.githubusercontent.com/61209759/119402404-2df8b380-bcdd-11eb-8401-28172adf9374.png)

**Comment by fengyezhiwu** [comment]
same here, I can see they are transferred in chia explorer, but I can't see it in my wallet even it shows "sycned"
