### ISSUE TITLE
KernelBase error

### ISSUE THREAD

**Issue by filipejsbrandao** [Chia-Network/chia-blockchain#5952]
Plotting with chia 1.1.5 GUI on Windows 10 and had a crash of the GUI app but the plotter seems to be running in the background. The crash coincided with one of the plots finishing. When I noticed there were 2 plots waiting to be copied to the destination drive but this disk is showing very little activity.

Windows events shows the following  application error, preceded by two warnings about resource exhaustion:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-05-24T11:27:36.6552652Z" /> 
  <EventRecordID>10131</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>TR1920-FILIPE</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Chia.exe</Data> 
  <Data>1.1.5.0</Data> 
  <Data>607608dd</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.964</Data> 
  <Data>812662a7</Data> 
  <Data>e0000008</Data> 
  <Data>0000000000034b89</Data> 
  <Data>1838</Data> 
  <Data>01d7481467fe48b2</Data> 
  <Data>C:\Users\Filipe\AppData\Local\chia-blockchain\app-1.1.5\Chia.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>8bc3c1a5-f331-4147-b2cb-d0dfaaca8348</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by thestevekoch** [comment]
Experiencing a similar issue on 1.1.6 with Ubuntu 20.04 with a hard crash immediately following the first plot completing but before it's able to transfer to the destination disk. I'm able to recreate the issue (four times so far) by booting the machine, starting plotman and then waiting ~5 hours for the first of the series to finish and for the machine to crash.

**Comment by filipejsbrandao** [comment]
I have some more details about the issue. Eventually, the ongoing plot in each queue ended (I had 7 queues) and was copied to the destination drive, but no new plot was started even tough each queue had more plots scheduled. After the first 4 plots cleared the disk activity became normal and the last 3plots were copied as normally in about 10min. In the end I had to kill all chia.exe processes, start_full_node.exe, start_farmer.exe and start_harvester.exe.
