### ISSUE TITLE
[BUG] Invalid Plots after Nas Disconnect

### ISSUE THREAD

**Issue by tonaci** [Chia-Network/chia-blockchain#5959]
![IMG_5973](https://user-images.githubusercontent.com/41871945/119408268-4a273100-bc9a-11eb-9b5c-da89d842f8ec.jpg)
**Describe the bug**
I have a NAS containing finished plots (500+) that were happily farming.
I accidentally disconnected the NAS and every plot on the NAS shows as in valid now. 
As you can see from the dates, the plots were completed last week. 
I restarted the machine and the plots from this drive still show invalid. 
Any help appreciated.
OS - Windows

**Comment by Hardcore-fs** [comment]
They will be....
Chia works by reading & writing to the plots. EXCESSIVELY.....
you disconnect an attached store whilst writing and it's game over. (cheap assed NAS, use RAM caches to make them look faster, also  QNAP software is really garbage for file integrity, too many writes queued)
(i'm surprised we don't see a lot more file corruption)

you might try running the "chia" validation against them to sort out any good ones and be double sure they are corrupted.

**Comment by tonaci** [comment]
problem solved, I had to reboot the NAS entirely a second time along with my head node computer and all is happy again. I actually had completely finished plots (they weren't in progress). I tried one reboot and while it could access the NAS it was showing up as invalid. Did a power cycle of the nas and all is well. Thanks for chiming in though. Appreciate it.
