### ISSUE TITLE
[BUG] DO NOT USE CHIA GUI for anything - The Cmd Line "Chia start -r all" is working

### ISSUE THREAD

**Issue by room101-dev** [Chia-Network/chia-blockchain#5960]
**Describe the bug**

**Major problems here, I would say 99% of reported bugs is this problem that the entire CHIA-GUI is crap.
99% of the entire crypto-universe, just fires up the daemon, and lets it run, and sync.
Chia is very slow, expect 4-5 days from virgin to sync the blockchain, and expect another two days to sync & build the 'wallet', so total almost a week from scratch. Be patient.

Don't even install the GUI 'sh install-gui.sh', its all crap. They tried to do something never done before put mining, wallets, monitors, everything in one gui for all operating-systems, IT DOESNT WORK.

In the real world, just like POOLS its done outside, a third party usually provides wallet GUI, and wallet server. Here chia not only tried to monopolize the pool, but they tried to monopolize the wallet GUI**

**To Reproduce**

**Don't use the GUI**

**Expected behavior**
The GUI is crap.

**Screenshots**

**Desktop (please complete the following information):**

Install "sh install.sh" per instructions
. ./activate
chia init
chia start -r all

**[ sit back and find another activity for a week ]**

run a few cmd lines for status

chia show -c , will show connections
chia show -s , will show blockchain server sync status
chia wallet show, will show status of the wallet server

That's essentially it; You can get an estimate of % done, by calculating how far you are from the top of the blockchain. The blockchain will sync first, then a few days later the wallet will finish, after that just leave the stuff running, and always use 'chia start -r all' to start & stop, ignore the stuff about 'vdf/timelord' don't use it, you must have a super-computer & 68gb to run timelord, and it doesn't help you at all.

If you want to earn money on mining plots, then run hpool (dot com) they're the only working mining pool for chia on the planet earth.
**Additional context**
On the subject of port-8444 I have no problem on any other blockchain, and I run dozens, I have never had a problem with port 8444 when running chia blockchain, you should check your router 192.168.1. and make sure upnp is enabled, you could add the port for that IP where your blockchain machine is running and make sure that its a static IP to bind the incoming port to chia blockchain, lots of people say this is the problem, but I don't think so, but then I only use linux.

**Comment by rangerov** [comment]
gui is good so speak for yourself

**Comment by joelrb** [comment]
"They tried to do something never done before put mining, wallets, monitors, everything in one gui for all operating-systems"... so????

Just because it's never done before so don't do it? Nobody creates a perfect software in one go...

**Comment by xazes** [comment]
at hpool at time nothings works.

**Comment by elfatherbrown** [comment]
"monopolize"

Man... some guys....
