### ISSUE TITLE
1.16bug  Several serious problems

### ISSUE THREAD

**Issue by Today857** [Chia-Network/chia-blockchain#5966]
status  synced               connection  status     connected
connections  is  ok   about   10net
**wallets    not   synced    
connections     0**
**last  attempted  proof**     **It's empty    No any  information**
**Latest Block Challenges       It's empty    No any  information    too**

Farming Status     Farming

**It's been like this since 1.1.6**

win  10    x64
i10850k

**Comment by lvpcguru** [comment]
This is a common issue with several discussions you can find in that tab. 

- try deleting your wallet sync db
- make 100% sure that port 8444 is being NATd correctly
- try reloading your keys from mnemonic

**Comment by PapiDot** [comment]
> This is a common issue with several discussions you can find in that tab.
> 
> * try deleting your wallet sync db
> * make 100% sure that port 8444 is being NATd correctly
> * try reloading your keys from mnemonic

I'd like to report that deleting sync db and reloading keys are not the root causes, because I build a second machine from scratch. The machine is dedicated for plotting and farming, absolutely clean.

But the GUI sync is on and off, pretty much the same as the other computer or even worse because the second on runs on a newer version presumably.

**Comment by lvpcguru** [comment]
Dont forget that two farmers on the same external IP can cause issues of their own. which node did you forward your 8444 port to? 

[https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines)

**Comment by keliew** [comment]
Maybe because your plots aren't added...?
