### ISSUE TITLE
Harvester Error

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#5968]
ERROR    Failed to open file /plots1/sdaf/plot-k32-2021-05-10-10-14-bda326a1c1f0290b4800f3ae5f69a406117a5de4df61e0011acad6664824341c.plot. badbit or failbit after reading size 4 at position 107538631865 Traceback (most recent call last):
  File "/chia-blockchain/chia/plotting/plot_tools.py", line 189, in process_file
    prover = DiskProver(str(filename))
RuntimeError: badbit or failbit after reading size 4 at position 107538631865

**Comment by siaarzh** [comment]
Please follow the [Contributing Guidelines](https://github.com/Chia-Network/chia-blockchain/blob/9e21716965f6f6250f6fe4b3449a66f20794d3d9/CONTRIBUTING.md) before posting what you believe to be actual bugs and issues. By default you are given a [bug report template](https://github.com/Chia-Network/chia-blockchain/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Please, try to stick to it, as it helps the developers replicate and solve your problem.
