### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RobTree1** [Chia-Network/chia-blockchain#5975]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**
Steps to reproduce the behavior: Create multiple plots, eventually one will fail and you cannot delete it.

**Expected behavior**
Cannot exit or terminate a plot that is being created, or that has failed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/84761844/119442522-dce8bf80-bcdc-11eb-8e9c-a38652829ae0.png)

**Desktop (please complete the following information):**

- OS: windows 10 
- OS Version/Flavor: 1.1.6 
- CPU: amd ryzen 5800x 

**Additional context**

**Comment by lvpcguru** [comment]
This is a feature that has been disabled for now. It causes a hang in the GUI that forces a reload killing the rest of your plots as well. Most people are plotting with CLI right now.

Here is the change log [https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md](https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md)

As its not an actual issue please close.
