### ISSUE TITLE
ERROR 22

### ISSUE THREAD

**Issue by umanginang** [Chia-Network/chia-blockchain#5978]
after update to 1.1.6 all plot can not detected and this error occur. message as below.

[Error 22] File not found. Most likely one of the plot folders in your config.yaml has an issue.

- OS: window 10
- OS Version/Flavor: 2004
- CPU: Intel i7 990x

**Comment by lvpcguru** [comment]
check your config.yaml and make sure you dont have any old plot paths in it.
also check all your plot directories and mounts to make sure they are all accessible before you run chia
