### ISSUE TITLE
How to plot on the same account with different computers on not the same lan

### ISSUE THREAD

**Issue by almog975** [Chia-Network/chia-blockchain#5979]
Hey guys
I want to run some plots with my friend on the same account this is possible?
We have a different lan of Course

**Comment by Tinphan76123** [comment]
theo mình nghĩ là được, tạo plots riêng trên máy khác rồi copy file plot bỏ vào máy chạy farming.

**Comment by almog975** [comment]
> theo mình nghĩ là được, tạo plots riêng trên máy khác rồi copy file plot bỏ vào máy chạy farming.

I mean i want them to run them both do plots and then farm the same plots my friend farm or shit like that to double the chances

**Comment by lvpcguru** [comment]
Chia doesnt work like that sorry. the plots are all generated by design to be tied to a single farm key, pool and wallet destination. you two can share a wallet and both farm for it and then split up winnings later if you like. 

Once pools are done it is likely that you can just pool your chances and the network will split the profits for you automatically

**Comment by almog975** [comment]
That is what we want to. Do,
He statred to plot already but i don't see that. 
We use the same keys

**Comment by siaarzh** [comment]
Please follow the [Contributing Guidelines](https://github.com/Chia-Network/chia-blockchain/blob/9e21716965f6f6250f6fe4b3449a66f20794d3d9/CONTRIBUTING.md) before posting what you believe to be actual bugs and issues. By default you are given a [bug report template](https://github.com/Chia-Network/chia-blockchain/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Please, try to stick to it, as it helps the developers replicate and solve your problem.

**Anything else belongs in the [discussion](https://github.com/Chia-Network/chia-blockchain/discussions) section.**
