### ISSUE TITLE
[BUG]DevTools failed to load SourceMap: Could not parse content for file:///Applications/Chia.app/Contents/Resources/app.asar/build/renderer/js/399.js.map: Unexpected end of JSON input

### ISSUE THREAD

**Issue by AlexArzon** [Chia-Network/chia-blockchain#5988]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by siaarzh** [comment]
Please follow the [Contributing Guidelines](https://github.com/Chia-Network/chia-blockchain/blob/9e21716965f6f6250f6fe4b3449a66f20794d3d9/CONTRIBUTING.md) before posting what you believe to be actual bugs and issues. By default you are given a [bug report template](https://github.com/Chia-Network/chia-blockchain/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Please, try to stick to it, as it helps the developers replicate and solve your problem.

**Comment by AlexArzon** [comment]
this is not the 1st time this was reported

**Comment by hellegaard1** [comment]
Fixed this exact same problem by deleting every file in .chia/mainnet/wallet/db then restarting gui. Hope this helps.
