### ISSUE TITLE
CMake version

### ISSUE THREAD

**Issue by wpasieka** [Chia-Network/chia-blockchain#5996]
Make Error at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
    CMake 3.14 or higher is required.  You are running version 3.5.1
_____________

How to overcome it?, I have restarted computer, but the problem remains.

Description:	Ubuntu 16.04.7 LTS  Release:	16.04 Codename:	xenial
Linux PressAI-Mind 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:26:57 UTC 2021 i686 athlon i686 GNU/Linux

**Comment by lvpcguru** [comment]
install CMake 3.14?

**Comment by joelrb** [comment]
You restarted the pc but did not do the thing being required? The error is obvious and the solution has been provided before your eyes... :)

**Comment by siaarzh** [comment]
> You restarted the pc but did not do the thing being required? The error is obvious and the solution has been provided before your eyes... :)

Please refrain from condescending language and try to follow the [code of conduct](https://github.com/Chia-Network/chia-blockchain/blob/main/CODE_OF_CONDUCT.md#our-standards) when helping other community members.

**Comment by siaarzh** [comment]
> Make Error at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
> CMake 3.14 or higher is required. You are running version 3.5.1
> 
> How to overcome it?, I have restarted computer, but the problem remains.
> 
> Description: Ubuntu 16.04.7 LTS Release: 16.04 Codename: xenial
> Linux PressAI-Mind 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:26:57 UTC 2021 i686 athlon i686 GNU/Linux

Follow the instructions mentioned [in the Ubuntu forums](https://askubuntu.com/a/865294/788101) to update to the latest version of `cmake`.

**Comment by wpasieka** [comment]
Thank You for all suggestions, but I think the problem is different.

I  purged cmake 3.5.1 and went down to 3.4.1, but the problemes persists:

CMake Error at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):                                                                                     
    CMake 3.14 or higher is required.  You are running version 3.4.1                                                                            
   
  It is easy to overlook, but I have a  HIGHER version than required.
   I didn't  try this specific 3.1.4. because it is the old one, and it will break other packages.
 ______
 If You could help, please, maybe this is a bug in Chia package.

**Comment by wpasieka** [comment]
Sorry, You are right, this  3.14 is higher than 3.5, just tired. Thank You.

**Comment by wpasieka** [comment]
Before closing let me put all together for others, please.

Using apt install cmake  brings it to version 3.5 (somehow I saw it as 3.50 hence the mistake).

To get a version higher than 3.14 we need to us the APT from a link provided by @siaarzh to the ubuntu forums, or directly from https://apt.kitware.com/. 

Cake is also getting embedded in emacs:
 
Setting up cmake-data (3.20.2-0kitware1) 
Install cmake-data for emacs24
install/cmake-data: Byte-compiling for emacs24
Wrote /usr/share/emacs24/site-lisp/cmake-data/cmake-mode.elc
