### ISSUE TITLE
Can't able to Delete Plots in UI[BUG]

### ISSUE THREAD

**Issue by ramanamoorthy** [Chia-Network/chia-blockchain#6013]
**Describe the bug**
I'm using Windows10. Updated to 1.1.6. I cann't able to delete the plots in Chia Blockchain UI. 

**To Reproduce**

1. Go to 'Plots'
2. Click on 'Plots - Actions Burger dots (Verticale three dots)'
3. Scroll down to 'Delete'
4. The Icon is in a **disabled state**.

**Expected behavior**
The Delete button/option should be in enabled/active state. When we click on the Delete Button, it should ask to confirm and if the user confirms it should delete the specific Plot.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- CPU: AMD Ryzen 5 3600
- RAM: 32GB

**Comment by lvpcguru** [comment]
Please search before opening new bugs...

[https://github.com/Chia-Network/chia-blockchain/issues/5982](https://github.com/Chia-Network/chia-blockchain/issues/5982)

**Comment by lvpcguru** [comment]
This is a feature that has been disabled for now. It causes a hang in the GUI that forces a reload killing the rest of your plots as well. Most people are plotting with CLI right now

Here is the changelog https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md

as its not an actual issue please close

**Comment by vanthoi** [comment]
Actually, to handle this problem is very simple. I don't understand why they disabled it. Just add the pid of each plot to the log file. If the user proceeds to delete them just kill that pid and start deleting. It won't cause any errors. I usually do this manually when I'm not using the cli.

**Comment by lvpcguru** [comment]
> 
> 
> Actually, to handle this problem is very simple. I don't understand why they disabled it. Just add the pid of each plot to the log file. If the user proceeds to delete them just kill that pid and start deleting. It won't cause any errors. I usually do this manually when I'm not using the cli.

the problem is that the GUI becomes nonfuntional not that the plot wont remove. I like the idea about the pid tracking. you should code it up and submit a pr. Thats the fun with open source.

**Comment by vanthoi** [comment]
> > Actually, to handle this problem is very simple. I don't understand why they disabled it. Just add the pid of each plot to the log file. If the user proceeds to delete them just kill that pid and start deleting. It won't cause any errors. I usually do this manually when I'm not using the cli.
> 
> the problem is that the GUI becomes nonfuntional not that the plot wont remove. I like the idea about the pid tracking. you should code it up and submit a pr. Thats the fun with open source.

Thank you for the suggestion! But I don't know all about programming, can't help. I can only offer suggestions or describe how to solve them.
