### ISSUE TITLE
[BUG] Plot duplication

### ISSUE THREAD

**Issue by big-chia** [Chia-Network/chia-blockchain#6020]
copy plot
use hex editor to replace plot id and memo
????
profit!!!

use something like this for valid id and memo instead of random

`from secrets import token_bytes
from blspy import AugSchemeMPL, G1Element, PrivateKey
from chia.plotting.plot_tools import add_plot_directory, stream_plot_info_ph, stream_plot_info_pk
from chia.types.blockchain_format.proof_of_space import ProofOfSpace
from chia.types.blockchain_format.sized_bytes import bytes32
from chia.wallet.derive_keys import master_sk_to_farmer_sk, master_sk_to_local_sk, master_sk_to_pool_sk

pool_public_key = G1Element.from_bytes(bytes.fromhex('<pool public key here>'))
farmer_public_key = G1Element.from_bytes(bytes.fromhex('<farmer public key here>'))
sk = AugSchemeMPL.key_gen(token_bytes(32))
plot_public_key = ProofOfSpace.generate_plot_public_key(master_sk_to_local_sk(sk).get_g1(), farmer_public_key)
plot_id: bytes32 = ProofOfSpace.calculate_plot_id_pk(pool_public_key, plot_public_key)
plot_memo: bytes32 = stream_plot_info_pk(pool_public_key, farmer_public_key, sk)
plot_memo_str: str = plot_memo.hex()
plot_id_str: str = plot_id.hex()
print(f"Memo: {plot_memo_str}")
print(f"Plot ID: {plot_id_str}")`

**Comment by keliew** [comment]
But the generated hashes will be the same, and with the filter, you'd most likely only win once.

It's a nice trick to fake Plotting as a Service on total farm size though.

**Comment by big-chia** [comment]
> It's a nice trick to fake Plotting as a Service on total farm size though.

Yes, hpool is 100% vulnerable

**Comment by justinengland** [comment]
reproducing plots is intentionally allowed. they do not count twice with official software.

**Comment by FrankSent** [comment]
> > It's a nice trick to fake Plotting as a Service on total farm size though.
> 
> Yes, hpool is 100% vulnerable

Wouldent you get quickly banned? It should be relatively easy to detect that two plots match each other, no?
When i open a plot in a hex editor only the first line is readable and it says "Proof of Space P" all the other lines are random letters. No mention of a memo or id

**Comment by big-chia** [comment]
> reproducing plots is intentionally allowed. they do not count twice with official software.

They do :)
