### ISSUE TITLE
[BUG] Removing a Plot directory on Win10 GUI delets all your plots inside this directory!

### ISSUE THREAD

**Issue by TheVino** [Chia-Network/chia-blockchain#6029]
> Apparently this bug appears to be only on 1.1.6

### Bug details:
When you remove a plot directory from the GUI the entire directory disapears, deleting your plots from computer.

### Steps to reproduce the behavior: (please don't test it)
1. Open GUI (Win10)
2. Go to `Plots`
2. Click on `Add Plot Directory`
3. Click on the trash icon on right of the plot directory (i.e.: `F:\Plots 8TB_1`:wastebasket:)
4. The directory is removed from GUI list and deleted from the drive.

### Expected behavior:
Only remove the plot diretory from GUI, so the farmer would not farm this directory.

### **Additional context**
I use my personal computer to plot on SSD and copy to HDs, then I move this HDs to my rigs.
This also happened on my farming rig (same Chia version and deleted all 2 plots in the directory with same steps).

- ![Original directory chia deleted the plots](https://user-images.githubusercontent.com/47784023/119581785-a58c1880-bd99-11eb-95d4-8e508ed37765.jpg)
Here you can see the directory in which the plots were. Clicked on this trash icon to stop (remove) this directory from farming.

- ![Directory with no content](https://user-images.githubusercontent.com/47784023/119581782-a4f38200-bd99-11eb-945a-447bcfa7da96.jpeg)
Here it shows the directory with neither folders nor plots inside, but...

- ![Full directory but no plot](https://user-images.githubusercontent.com/47784023/119581784-a58c1880-bd99-11eb-85ef-934c1919fbcd.jpg)
The Vol. inform. says it is full, even without files inside.

Plots are not on Windows Recycle Bin. Even tried a file recover SW, but no success.

### Desktop:
- **OS**: Windows 10
- **CPU**: i5-8400
- **Chia Version**: 1.1.6

**Comment by room101-dev** [comment]
> > Apparently this bug appears to be only on 1.1.6
> 
> ### Bug details:
> When you remove a plot directory from the GUI the entire directory disapears, deleting your plots from computer.
> 
> ### Steps to reproduce the behavior: (please don't test it)
> 1. Open GUI (Win10)
> 2. Go to `Plots`
> 3. Click on `Add Plot Directory`
> 4. Click on the trash icon on right of the plot directory (i.e.: `F:\Plots 8TB_1`🗑️)
> 5. The directory is removed from GUI list and deleted from the drive.
> 
> ### Expected behavior:
> Only remove the plot diretory from GUI, so the farmer would not farm this directory.
> 
> ### **Additional context**
> I use my personal computer to plot on SSD and copy to HDs, then I move this HDs to my rigs.
> This also happened on my farming rig (same Chia version and deleted all 2 plots in the directory with same steps).
> 
> * ![Original directory chia deleted the plots](https://user-images.githubusercontent.com/47784023/119581785-a58c1880-bd99-11eb-95d4-8e508ed37765.jpg)
>   Here you can see the directory in which the plots were. Clicked on this trash icon to stop (remove) this directory from farming.
> * ![Directory with no content](https://user-images.githubusercontent.com/47784023/119581782-a4f38200-bd99-11eb-945a-447bcfa7da96.jpeg)
>   Here it shows the directory with neither folders nor plots inside, but...
> * ![Full directory but no plot](https://user-images.githubusercontent.com/47784023/119581784-a58c1880-bd99-11eb-85ef-934c1919fbcd.jpg)
>   The Vol. inform. says it is full, even without files inside.
> 
> Plots are not on Windows Recycle Bin. Even tried a file recover SW, but no success.
> 
> ### Desktop:
> * **OS**: Windows 10
> * **CPU**: i5-8400
> * **Chia Version**: 1.1.6

NEVER use the CHIA GUI, its a criminal software app designed to kill drives and steal XCH

If you must add/remove folders then use the 'cmd line' "Chia plots add/remove -d", or better yet edit the config.yaml yourself, and remove the diapers, and get real.
Config.Yaml is in ~/.chia/mainnet/config, windows has an equivalent, its a text file, easy to find the lines for the plot-files

Lastly, NEVER use the chia-GUI, its the work of the devil.

**Comment by keliew** [comment]
`F:\Plots 8TB_1` is not quite the same as `F:\`..?

**Comment by TheVino** [comment]
> NEVER use the CHIA GUI, its a criminal software app designed to kill drives and steal XCH
> 
> If you must add/remove folders then use the 'cmd line' "Chia plots add/remove -d", or better yet edit the config.yaml yourself, and remove the diapers, and get real.
> Config.Yaml is in ~/.chia/mainnet/config, windows has an equivalent, its a text file, easy to find the lines for the plot-files
> 
> Lastly, NEVER use the chia-GUI, its the work of the devil.

I stopped since lot of people recommended CLI. Thanks!
btw my harvesting rig is using ubuntu and I really recommend.
