### ISSUE TITLE
 Chia wallet plot error, there will be repeated progress, causing the plot task to stop [BUG]

### ISSUE THREAD

**Issue by CoolJie2001** [Chia-Network/chia-blockchain#6030]
My computer configuration is 
AMD R7 3700x
KUSO 32G DDR 4 2666
MSI B450M PRO-VDH MAX
WD 40EFRX 4TB
Kingston SATA SA400537480G
It is almost impossible for a single plot task to succeed, and it will stop at a random percentage of progress, and the observation log will be repeated, as shown in the figure below
<img width="367" alt="1" src="https://user-images.githubusercontent.com/3133908/119586799-f33b6c00-bdff-11eb-8cd7-801ab68a52a4.png">

**Comment by vanthoi** [comment]
Your error sounds like mine: #6044

**Comment by CoolJie2001** [comment]
A repetitive process began to appear on line 1075, and the problem may have started from here
[plotter_log_10fb53c3-9ca6-4a8f-969f-f51c8344f6e3.txt](https://github.com/Chia-Network/chia-blockchain/files/6547324/plotter_log_10fb53c3-9ca6-4a8f-969f-f51c8344f6e3.txt)
