### ISSUE TITLE
[BUG]-Chia stop do K32 Plot after few minutes

### ISSUE THREAD

**Issue by GBourb** [Chia-Network/chia-blockchain#605]
**Describe the bug**
Everithing just stop with no error message.
I tried B16, B17, B18 with the same problem.

Before it was working great.

My computer : R5 2600, B350 bazooka MB, Windows 10 pro, 16 g ram

It was working great before i did install my Nas (NSA 325 v2). Tried to uninstall it w/o any changes (still stop doing plot at random moment) 

Chia is still syncing the block chain, so the program still work

QUESTION

What can i do to clear everithing and start from the begenning ? maybe this can help

EDIT: I added an exclusion in windows security (antivirus) 
K32 did not work
K25, K26 :  Working
SSD health : 96%

**Comment by hoffmang9** [comment]
What -b/buffer size were you using? If it was failing under Beta 18 and you had enough buffer size it usually means you have a memory or drive problem on the system.

**Comment by GBourb** [comment]
Probably a drive faliure. i had some error in this drive. Thanks
