### ISSUE TITLE
[BUG] "Chia Plots Check" destroyed my HDD containing 51 plots, wrote over sector-0 wiping out linux EXT file record

### ISSUE THREAD

**Issue by room101-dev** [Chia-Network/chia-blockchain#6052]
**Describe the bug**
I was just running 'chia plots check' per the 'chia start farmer' log request to verify plots

**To Reproduce**

Create plots on physcial HDD, then run Farmer

**Expected behavior**
I expected not to have a drive destroyed.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor:ubuntu 18
- CPU amd 6core

**Additional context**
Been using chia many months, past few weeks since version 1.3 things unstable, since 1.6 terrible, now running 1.7
Got the node to sync blockchain, got the wallet to sync, then ran the farmer, and it generated tons of 'plot fail' delay, having to do with the new 5 second rule to verify plots
This is a new drive, and a good system, I run bitcoin on other drives, the chia instance is running on its own sata-ssd, the HDD was destroyed, and nothing else was using it accept chia-farmer & chia plot check.

I also run GETH on this system as well as BITCOIND, but all was turned off for CHIA, even turned off HPOOL. Nothing but CHIA was running.

**There is a serious bug in the 'chis start farmer', and super serious bug in 'chia plots check'**

I run chia on four systems, of which one is for plot's only. I have seen lots of crazy stuff with chia, but it just keeps getting worse, this is the first time it destroyed plots.

**Comment by room101-dev** [comment]
I know hoffman will say 'don't run cmd-line', or memory problem, ran memtest just this am, and the gui don't work, so I have to use cmd-line to make chia plots.

**Comment by Inguiotar** [comment]
Why guess? The code is right here on github, at your disposal.

And no, of course Chia does not use low-level HDD access (that'd be utterly silly for software that needs to work across networked drive space). Your disk is broken because it was faulty - it's that easy.

**Comment by hoffmang9** [comment]
Your HDD was not destroyed by Chia.
