### ISSUE TITLE
[BUG] harvester trying to reach full node

### ISSUE THREAD

**Issue by yrjo** [Chia-Network/chia-blockchain#606]
on:
chia version
1.0b19.dev1

-->

having one full node with farmer,
and multiple harvesters,
described here:
https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines
and
here
https://github.com/Chia-Network/chia-blockchain/wiki/Network-Architecture

on harvester i am getting:

`Connection error. Check if full node is running at 8555`

seems like its trying to connect to node instead of using harvester protocol only to the farmer.
ofc on farmer/full node machine, its  (tcp/8555) exposed to localhost only, which is by-default behaviour:

```
telnet localhost 8555
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

```

**Comment by hoffmang9** [comment]
This is now outdated due to a large refactor
