### ISSUE TITLE
Plots Passed Filter Out of Date

### ISSUE THREAD

**Issue by mjdaran** [Chia-Network/chia-blockchain#6063]
I'm seeing irrelevant and outdated dates in the plots Passed Filter table. The time just keeps changing. Not in real time.

![IMG_20210526_071924.jpg](https://user-images.githubusercontent.com/43126571/119657719-e3e11080-be49-11eb-9624-53ce2bad5157.jpg)

**Comment by keliew** [comment]
chia version?

**Comment by mjdaran** [comment]
1.1.6

**Comment by keliew** [comment]
Seems like an unstable connection. You must see that jumping around every 10 seconds.

What does the debug.log say?

**Comment by mjdaran** [comment]
No Warnings except for some empty plot directories! But I can see frequent "Diconnected" and "Connected" msgs from local host. Is it an issue??

**Comment by keliew** [comment]
Make sure it's `chia configure -log-level INFO` The default `WARNING` doesn't quite say much useful things when there are (potential) issues.

Those disconnect and connect messages may or may not be a problem...I'd imagine most of them is about your peers disconnecting.

You need to stay connected (to farm stably), that's important.

**Comment by mjdaran** [comment]
Okay, log level is INFO. Actually, the version 1.1.6 syncs faster than the earlier versions, the problem is Although synced, the peak time and peak height always lags when compared to the explorer! Might be an issue with the syncing, I guess. But the status says Synced all the time.

**Comment by keliew** [comment]
If you are a few seconds behind, I think that's fine. You probably just need more quality peers who are keeping good heights constantly.

The explorer is a few blocks behind, more than 30 seconds behind from what I noticed last time, I wouldn't take that as standard.

Any background applications running that may 'steal' resources? Sleep mode, etc are turned off?

**Comment by mjdaran** [comment]
Peers showing up to date block height [as in explorer]. But my peak height [in wallet] is outdated by a lot. Sleep mode is off in power option.

**Comment by keliew** [comment]
Wallet uses a separate db, so it's a non-issue.

**Comment by mjdaran** [comment]
Okay. let me check my internet connection! and restart the wallet.
