### ISSUE TITLE
HDD Error during Stage 4: terminate called after throwing an instance of 'std::filesystem::filesystem_error'

### ISSUE THREAD

**Issue by francovico** [Chia-Network/chia-blockchain#6094]
Hello everybody,

Im running Chia in HiveOS Linux through CLI.
I have mounted 2 mechanical HDDs, one EXT4 as temp and one NTFS as final destination.

Everything happens normally until stage 4, where in the end I get the following error:

terminate called after throwing an instance of 'std::filesystem::filesystem_error'
  what():  filesystem error: cannot remove: Read-only file system [/media/chiatemp/plot-k32-2021-05-25-12-35-10b7bfa16c82d40441e9933b1944d39cb7e1afb4e6fcf1575d15dca46314fa54.plot.p3.t4.sort_bucket_000.tmp]
Aborted (core dumped)

Initially both disks are correctly mounted as rw. After that error, when checking the status it changes to ro.

Im attach one image of error.

I repeated the process a couple of times and I get the same error.

What could be happening?

![Chia](https://user-images.githubusercontent.com/47440458/119751100-ea36b300-be70-11eb-8301-579d2ae9c28b.png)

_Originally posted by @francovico in https://github.com/Chia-Network/chia-blockchain/discussions/6090_

**Comment by sobertram** [comment]
Check your fstab and see if you have something on the mount that causes it to remount-ro. For example

UUID=XXXXX   /               ext4    `errors=remount-ro` 0       1

That would explain the change in perms. In my case if there is an error it will remount read only. You may have something similar. Then you will just need to figure out what condition is triggering it to remount. Or you can just remove it and see how it progresses.
