### ISSUE TITLE
[BUG]no Delete option in GUI Plots Chia 1.1.6

### ISSUE THREAD

**Issue by TomaszWM** [Chia-Network/chia-blockchain#6105]
I have no Delete option in GUI Plots Chia 1.1.6

![image](https://user-images.githubusercontent.com/84909392/119817810-b306e700-beee-11eb-9747-7c41d0dae78f.png)

**Comment by gromran** [comment]
rtfm...
changelog 1.1.6
> Disabled deletion of running plot for Windows users as the crash/lockup bug has returned.

**Comment by Ratzoletto** [comment]
they also disabled deletion of plots in queue - THIS is annoying.

**Comment by gromran** [comment]
You can also delete them via the file system, that's not rocket science

**Comment by Alexwsc** [comment]
> You can also delete them via the file system, that's not rocket science

No,This doesn't work, and when multiple tasks are running at the same time, you don't know which process it is

**Comment by Kevster92** [comment]
delete plot works under linux ? bat way not under windoes ... is same version
