### ISSUE TITLE
[BUG]chia master can not recieved any message from remote harvesters any more

### ISSUE THREAD

**Issue by teamhi** [Chia-Network/chia-blockchain#6118]
**Describe the bug**
harvesters have the issue about "Unexpected exception trying to send to websocket: code = 1006 " and  after upgrade the lastest code 1.1.6,then the issue seems not appear again. but i check the master debug.log, already can not see any messages like "[time stamp] farmer farmer_server   : DEBUG   -> new_signage_point_harvester to peer" from harvester any more. 

- OS: linux
- OS Version/Centos7.9
- CPU:Intel Xeon

**Comment by teamhi** [comment]
already resoved

**Comment by ShilohMy** [comment]
how to resoved?
