### ISSUE TITLE
[BUG] Running harvester dose not recognize new copyed plots

### ISSUE THREAD

**Issue by isipisi281** [Chia-Network/chia-blockchain#6121]
I dont know if this is a bug or not but,
when i only run the harvester like "chia harvetser start -f" the harvester starts and looks if there are plots in the directory.

When the harvester is running (startet from the terminal not from the gui)
and i copy a new plot into the harvesting directory the plot is not recognized.

When i restart the harvester from terminal like "chia harvetser start -f" and the harvester is RESTARING
the new copyed plot is now recognized.

Is there a way to refresh the plot directory automated?

My harvester is running on a sappared machine connected to the main machine via ip.

Running Linux 20.04 
chia 1.1.6

**Comment by ppolewicz** [comment]
harvester looks for new plots every few minutes (2 or 5, I forgot). Did you wait to see if a plot will get recognized?
