### ISSUE TITLE
[BUG] Lost wallet income after reinstall windows 

### ISSUE THREAD

**Issue by raf-cr** [Chia-Network/chia-blockchain#6133]
Hi.
I had worked chia blockchain and some income in wallet, then I reinstalled windows server OS and installed current chia blockchain 1.1.6 and provide my mnemonic key.

After that i have 0 in my wallet, before reinstall i had income.
I have copy of data before windows was reinstalled.

How to retrive lost wallet ?

**Comment by lvpcguru** [comment]
The wallet needs to sync. As it does it will catch up with the latest transaction records.

**Comment by lvpcguru** [comment]
Also welcome to the world of blockchain

**Comment by raf-cr** [comment]
Thank you for fast response. Now i can sleep well :)
