### ISSUE TITLE
plotting error1

### ISSUE THREAD

**Issue by xiaozhi24** [Chia-Network/chia-blockchain#6152]
The journal always shows “Error 1. Retrying in five minutes”，But there's actually no progress
![image](https://user-images.githubusercontent.com/50169742/119942019-e8c9cf80-bfc3-11eb-8473-e4c0b6529eba.png)

**Comment by xazes** [comment]
ssd full?

**Comment by lvpcguru** [comment]
> 
> 
> ssd full? this error comes to me when temp disks are full

yes its saying it isnt able to write to the disk and is waiting 5 min to try again. generally that happens when the drive is full or disconnects

**Comment by xiaozhi24** [comment]
The hard disk is not full yet, which may be the reason why some hardware of the computer automatically shut down, because this error occurred after I left the computer and did not operate for a while, but in fact, I have turned off the hard disk and hibernated the monitor
