### ISSUE TITLE
RPC curl failed to receive handshake, SSL/TLS connection failed

### ISSUE THREAD

**Issue by yuhaiqing0707** [Chia-Network/chia-blockchain#6154]
![image](https://user-images.githubusercontent.com/23378168/119945093-9be7f800-bfc7-11eb-9ab4-bc726253247f.png)

**Comment by txunda** [comment]
你好我也遇到这个问题， 请问你那边是怎么解决的？

**Comment by yuhaiqing0707** [comment]
证书需要转下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chia-Network/chia-blockchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chia-Network/chia-blockchain] RPC curl failed to receive handshake, SSL/TLS connection failed (#6154)





 
你好我也遇到这个问题， 请问你那边是怎么解决的？
