### ISSUE TITLE
Initial installation and startup of chia start farmer will report an error

### ISSUE THREAD

**Issue by GGsu** [Chia-Network/chia-blockchain#6167]
![image](https://user-images.githubusercontent.com/32504699/119978263-01e67680-bfec-11eb-96c6-027f3e5cefb9.png)

- OS: centos
- OS Version/Flavor: CentOS 8.0
- CPU:Intel(R) Xeon(R) CPU E5-2680 v2

**Comment by BonTron1** [comment]
Does this message only show with chia stop farmer, and not chia stop all?

**Comment by GGsu** [comment]
> Does this message only show with chia stop farmer, and not chia stop all?

I just installed the chia -1.1.6 version and this error occurred when I started the farmer

**Comment by GGsu** [comment]
> Does this message only show with chia stop farmer, and not chia stop all?

Where the error is reported chia_full_node and chia_wallet

**Comment by BonTron1** [comment]
Have you run $chia init

**Comment by GGsu** [comment]
> Have you run $chia init

I have executed chia init and restarted the chia start farmer, and it reports an error.

**Comment by BonTron1** [comment]
stop all running services and exit root user to then . ./activate

**Comment by GGsu** [comment]
> stop all running services and exit root user to then . ./activate

I know the solution, but this happens every time I redeploy. How can I solve this?

**Comment by BonTron1** [comment]
To me it appears you're starting your node, then stopping it before the node is initialized. To solve your problem, start your node and and let it sync. The screen shot you posted shows the node being stopped.

**Comment by GGsu** [comment]
> To me it appears you're starting your node, then stopping it before the node is initialized. To solve your problem, start your node and and let it sync. The screen shot you posted shows the node being stopped.

My operation process,
1.git chia-blockchain
2.. ./Activate
3. chia init
4. chia keys add
5.chia start farmer reported an error

**Comment by BonTron1** [comment]
So I can help, please post error from 

$chia start farmer

The screen shot shows error from 

$chia stop farmer

**Comment by GGsu** [comment]
> So I can help, please post error from
> 
> $chia start farmer
> 
> The screen shot shows error from
> 
> $chia stop farmer

You mean, my mistake is because of my chia stop farmer?
How can I not fail to encounter this error?

**Comment by GGsu** [comment]
> Don't
> 
> $chia stop farmer
> 
> If you
> 
> $chia show -s
> $chia show -c
> 
> You'll know if you're connected

My error occurred because I stopped the farmer?
No, I installed chia on a new computer. This error occurred when I started it. I haven't started the chia node yet. When I was about to start it, this error occurred. Can you understand what I mean? Or you tell me the reason for this error, my English is not very good, sorry

**Comment by BonTron1** [comment]
Yes, error is because you stopped the farmer. 

I'm having trouble understanding but want to help. 

More important than that error is 

$chia show -c 

Are you connected to other full nodes?

**Comment by GGsu** [comment]
Okay thank you

**Comment by GGsu** [comment]
> Yes, error is because you stopped the farmer.
> 
> I'm having trouble understanding but want to help.
> 
> More important than that error is
> 
> $chia show -c
> 
> Are you connected to other full nodes?

I know how to solve this problem, but I don’t know why it happened. Thank you for your patience.

**Comment by MontajnikRTA** [comment]
Similar problem with installation and startup, whether on a new PC or on a clean system makes no difference
