### ISSUE TITLE
plotting error, random stop of task  [BUG]

### ISSUE THREAD

**Issue by CoolJie2001** [Chia-Network/chia-blockchain#6171]
random stop of task, Unable to plot task at all

**Screenshots**
[plotter_log_3be58626-7d08-4b92-a228-ec3638664d69.txt](https://github.com/Chia-Network/chia-blockchain/files/6561080/plotter_log_3be58626-7d08-4b92-a228-ec3638664d69.txt)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: 21H1
- CPU: AMD R3700x

The mission failed more than 90% of the time, It's never going to produce

**Comment by caishubao** [comment]
在进程里面查看一下是不是磁盘不跑了，更新1.1.6我也发生5-6次这样了，删除掉重新开任务

**Comment by CoolJie2001** [comment]
> 在进程里面查看一下是不是磁盘不跑了，更新1.1.6我也发生5-6次这样了，删除掉重新开任务

是你描述的这种症状, 磁盘不再有IO, 但是我在1.1.5版本也出现这样的情况
