### ISSUE TITLE
[BUG]绘图错误信息

### ISSUE THREAD

**Issue by wangtao123-www** [Chia-Network/chia-blockchain#6179]
![微信图片_20210528231909](https://user-images.githubusercontent.com/84981418/120006020-0cfccf00-c00b-11eb-9080-afd43560397f.jpg)
![微信图片_20210528231909](https://user-images.githubusercontent.com/84981418/120006053-15550a00-c00b-11eb-8ff5-dc965bdaf67f.jpg)

**Comment by wangtao123-www** [comment]
请管理员和高手解决一下我这个问题。。经常出现这个错误日志

**Comment by sornku** [comment]
da gai lv shi nei cun wen ti,ce shi yi xia nei cun 
run memtest
