### ISSUE TITLE
chia WARNING Invalid handshake with peer. Maybe the peer is running old software[BUG]

### ISSUE THREAD

**Issue by Groug101** [Chia-Network/chia-blockchain#6182]
I reformated windows 10 pro 
Reinstalled everthing then went to download Chia for windows did that loged back into my account 
And started to plot and waited i see my Chia is stuck on Syncing and nothing going any were 
 
then i look at good and it told me how to find whats going on

and i got **chia WARNING Invalid handshake with peer. Maybe the peer is running old software**
 
does this fix on it own or how do i fix it?

**Comment by katmai** [comment]
it tells you in the error message. the peer is using old software. what do you wanna do? ask them to update?

**Comment by Groug101** [comment]
i got it working it

**Comment by qq674684107** [comment]
WARNING Invalid handshake with peer. Maybe the peer is running old software
Hello, how to deal with this problem? Can you tell me the specific operation method?

**Comment by tydeno** [comment]
> WARNING Invalid handshake with peer. Maybe the peer is running old software
> Hello, how to deal with this problem? Can you tell me the specific operation method?

Cal the owner of the node that runs old software and tell him to update. No seriuosly, this is out of your control. Ignore it.
