### ISSUE TITLE
[BUG] Windows 10 cmd plotting randomly dies at various stages

### ISSUE THREAD

**Issue by sitoryp** [Chia-Network/chia-blockchain#6203]
**Describe the bug**
I've been trying to track down this bug since upgrading to version 1.1.5 and also version 1.1.6. When plotting via the chia cli `chia.exe plots create` or in the wallet GUI occasional plots will get seemingly stuck. The disk IO stops but the process in the task manager is still alive allocating CPU and RAM resources to the process.

**To Reproduce**

1. open cmd
2. run `<path/to/chia>/chia.exe plots create -k 32 -n 1 -b 8000 -r 4 -t <temp Drive 1> -2 <temp Drive 2> -d <final Drive> -f <public farm key> -p <public pool key>`

3. Doesn't happen every time, but typically at least 1 plot a day will freeze and no longer progress.

**Expected behavior**
The plot should finish as expected and be relocated to the final drive location.

**Screenshots**
![image](https://user-images.githubusercontent.com/16514798/120071349-d8b1fe80-c05c-11eb-8edd-f8fbb628dc12.png)

See attached log file for reference.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- OS Version/Flavor: 20H2
- CPU: Ryzen 9 5950x
- RAM: 128GB G.Skill 3600
- Temp Drive: 2x 1TB Samgsung 980 pro Raid-0

**Additional context**
I Created a plotting program to spawn the command in the cmd prompt for me. The last line of the data in the code block above came from adding the standard error output and logging it to the file. Without logging the standard error output it appears to just hang and die at a random bucket at for a random table, typically in phase 3 compression.

**EDIT formatting issues made the copy/paste unreadable.
[k32_05_28_2021-18_39_30_15_log.txt](https://github.com/Chia-Network/chia-blockchain/files/6564720/k32_05_28_2021-18_39_30_15_log.txt)

**Comment by joolzg** [comment]
I have the same problem but on Ubuntu 20.04.

I have a program which monitors each instance of the "chia plot create" and watched the output and I get random crashes of the system.

When the crash happens i get the following in dmesg
[305428.406643] python[481284]: segfault at 7f830186fd84 ip 00007f8301821036 sp 00007ffc3c824e88 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f83017b5000+b8000]
[305428.406663] Code: b6 4b 02 49 01 d8 47 0f b7 14 44 4c 8d 44 cd 00 41 8b 48 04 4d 63 00 48 01 f9 48 c1 f9 10 49 d3 f9 41 8d 1c 0e 89 c9 4d 01 c8 <41> 8b 4c 8d 00 89 5c 24 dc 47 0f b7 0c 44 45 0f b6 43 01 48 21 cf


[330878.314266] python[545744]: segfault at cc197a6e ip 00007f18f22b309d sp 00007ffd54539db8 error 4 in chiapos.cpython-38-x86_64-linux-gnu.so[7f18f2247000+b8000]
[330878.314282] Code: 44 24 dc 43 8b 54 85 00 89 c1 46 8d 34 00 48 63 03 4c 21 d2 48 d3 e2 44 89 c1 48 09 d7 49 d3 fa 41 0f b6 13 44 89 f1 49 01 c2 <43> 0f b7 04 54 4c 8d 54 d5 00 45 8b 42 04 4d 01 c8 49 c1 f8 10 43

**Comment by Vladkarok** [comment]
I have the same bug, but it started 2 days ago.

**Comment by joolzg** [comment]
@Vladkarok Did you do an upgrade of ubuntu or chia?

Im sure mine started when I upgraded to 1.1.6 a few days ago, weird thing is my 2nd machine has not had this problem once. Lost 1 plot overnight, so the slow machine is losing 1 or every 3 plots started.

**Comment by Vladkarok** [comment]
@joolzg I have Windows 10 20H2 and I've been on 1.1.6 almost a week, so I don't think it is related to updating.
But, there are some people that says it can be hardware problem, specially RAM overclocking, they advise to reduce frequency to default values. So we can try.
