### ISSUE TITLE
[BUG] 1.1.6 Cannot delete a Queued Plot

### ISSUE THREAD

**Issue by mjbservices** [Chia-Network/chia-blockchain#6205]
Upgraded Chia from 1.1.5 to 1.1.6 - Now cannot delete a Queued Item from the "Plots" tab - The option is greyed out.

**Comment by Spshulem** [comment]
Also cannot delete plots current plotting

**Comment by number435398** [comment]
This was deliberate by the Devs.  They did this because there's a crash bug that kept causing your entire set of plotting plots and the program, to disappear when you tried to delete a single plot. This was their temporary fix. This is not a bug.
