### ISSUE TITLE
node db and wallet db file size design limits

### ISSUE THREAD

**Issue by wishwanto** [Chia-Network/chia-blockchain#6206]
apologies for posting a question rather than an issue, however if there is no design limitations on how big either of these DB files can grow to, then we will run into technical issues.. 

Currently my fully synced node db is 3.83 GB and my wallet db is 2.56GB, we are not yet at a complete month since go live. How much space should be dedicated to the db files?

Anyone know how big these db's are supposed to grow to? syncing is already a major issue in the time it takes for a clean build to get to full sync status.. Creating a new wallet to hold chia separately from the farming/harvesting node (to add a little bit of security), results in a long delay before the new wallet db sync's with the network. 

Is it only me, or is there a problem that is starting to rear its head here?

**Comment by mariano54** [comment]
The DBs will grow linearly over time. As they get large, we will optimize the DB formats to use less data. This is not a bug
