### ISSUE TITLE
[BUG] Plotting is writing to the system disk, not the selected temp directory

### ISSUE THREAD

**Issue by Jin87** [Chia-Network/chia-blockchain#6208]
**Describe the bug**
Somehow plotting is writing to my system disk (partition C). Although I selected my temp folder on another disk (partition F).
I am using Chia Blockchain UI on Windows 10

**To Reproduce**

1. Create a new plot and select the temp folder on a data disk (not system disk/partition)
2. Let's Chia UI plot and wait for it to compute tables (Phase 1)
3. The systems disk is 100% busy or at least 70%
4. The temp disk only takes 1%, some time 0%

I checked this using CrystalDiskInfo app. My system disk's Total Host Writes increased like it is being used for plotting. 

**Expected behavior*
Plotting should write to the temp folder only

**Screenshots**
![It uses systems disk to plot](https://user-images.githubusercontent.com/85030491/120078028-9974c380-c0d7-11eb-94fc-94dc7c0b7465.png)

![It just wrote a bit data to the temp disk ](https://user-images.githubusercontent.com/85030491/120077817-73025880-c0d6-11eb-87b3-762e64a6fb6d.png)

![Plotting configured to disk F instead of C](https://user-images.githubusercontent.com/85030491/120077939-1b182180-c0d7-11eb-91ba-9df3e85b9ee9.png)

- OS: Windows
- OS Version/Flavor: 10
- CPU: Core i3 3220

**Comment by gromran** [comment]
Your problem is different: You have far too little RAM and Windows just writes a lot to the swap file

**Comment by Jin87** [comment]
Thanks @gromran, let me install more RAM and observe
