### ISSUE TITLE
[BUG] Chia not properly closing and won't reopen until restart

### ISSUE THREAD

**Issue by Spshulem** [Chia-Network/chia-blockchain#6217]
The Chia Blockchain GUI and node services don't actually close when you close down the app... they linger. You can't end task on them, and you also can't open another instance or reinstall Chia... you have to just restart the computer. This would be fine if it wasn't that I do most of my Chia mining remotely, so restarting this is a massive pain in the ass.

Screenshot below is what it looks like when Chia is closed, and refuses to close down it's nodes and the main app even though they aren't doing anything. 

![image](https://user-images.githubusercontent.com/1703265/120087727-653dda80-c0b8-11eb-9172-afac9e1c79cf.png)

Any ideas on how to force close it other than restarting the computer?

**Comment by pestxxo** [comment]
I often see you like this. I don't know if it's the bug of Chia or the problem of my computer. It's really a headache. I hope to reply. Thank you
