### ISSUE TITLE
[BUG]Many plots becoming invalid bug

### ISSUE THREAD

**Issue by pestxxo** [Chia-Network/chia-blockchain#6218]
Many plots becoming invalid bug, this kind of situation is not once or twice, but often occurs. I don't know whether it is the bug of Chia or the problem of my computer. It's really a headache. I hope to reply. Thank you

![PO0X{JXFU{` ~984XYP4Z@E](https://user-images.githubusercontent.com/58849942/120088761-96ed8a80-c126-11eb-91a7-cf4d2a926316.png)
![OOHXV`(E~T5$D4EBIT2 UDJ](https://user-images.githubusercontent.com/58849942/120088762-9b19a800-c126-11eb-8a26-ba8e7832a8c2.png)
![M EG@B4`RF@U3MFG`0NM1`V](https://user-images.githubusercontent.com/58849942/120088765-9d7c0200-c126-11eb-974f-b9c3e8a0b8ab.png)

**Comment by wangtao123-www** [comment]
温度过高

**Comment by JMacPro** [comment]
How to upload the screenshot?
