### ISSUE TITLE
[BUG]Two computers use the same account number, why does not the total number of farmland display (the node has been synchronized)

### ISSUE THREAD

**Issue by w1511025** [Chia-Network/chia-blockchain#6228]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Krepton** [comment]
Confirmed.
Displayed like this:
1/50
1/55
should be selected: 2/105

**Comment by w1511025** [comment]
![image](https://user-images.githubusercontent.com/69225246/120107831-20d43c80-c195-11eb-82dc-4f251438f2c5.png)我是指这里，为什么我一台机器上有8块，一台机器上有103块，为什么不显示总的数据

**Comment by Fawkex** [comment]
这个东西不会显示总的 你又不是矿池
收益不会受到影响 是正常的
不过我估计你这一点点算力 可能等个一两年都出不来块
