### ISSUE TITLE
[BUG]谁能和我说一下，怎么验证我P出来的图能不能使用，是不是正确的

### ISSUE THREAD

**Issue by w1511025** [Chia-Network/chia-blockchain#6235]
谁能和我说一下，怎么验证我P出来的图能不能使用，是不是正确的？？？
使用什么方法验证，如果有官方文档就更好了，我才接触，希望得到帮助，谢谢您的帮助！！

**Comment by isilcala** [comment]
RTFM
看文档

**Comment by max918** [comment]
chia plots check -n 5

the final message will show you how many plots are valid
including list out the invalid plots

**Comment by w1511025** [comment]
> RTFM
> 看文档

朋友来个地址可否，给个网址！

**Comment by playzhou** [comment]
chia plots check -n 5
楼上说让你试试这个命令
