### ISSUE TITLE
[BUG] GUI incorrectly displays "0.0" as version on Linux

### ISSUE THREAD

**Issue by mitchweaver** [Chia-Network/chia-blockchain#6237]
Not sure if this is already known, but on Linux the "Help -> About" displays "0.0" as the version

![image](https://i.redd.it/1rnr8weh55y61.jpg)

Discussed here a few weeks ago: https://old.reddit.com/r/chia/comments/n8kpu5/chia_gui_not_showing_version_fetch_latest_from

**Comment by lvcivs** [comment]
duplicate of #3012

**Comment by kzsolt4444** [comment]
The bug persist with version 1.1.7

**Comment by lvcivs** [comment]
This bug persists in version 1.2.2 and the issue should remain open.
