### ISSUE TITLE
I think they are stealing my plots, I had 28 on my disk D and 1 on my disk C and now I only have 25, what happens?[BUG]

### ISSUE THREAD

**Issue by josemacedove** [Chia-Network/chia-blockchain#6247]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by joelrb** [comment]
Stealing your plots is useless unless they have your keys too. They can't use it to farm using their own wallets.... and downloading 100gb+ file from you isn't worth a try :). Understand what's happening in your own setup. Read the wiki, faq, etc.

**Comment by josemacedove** [comment]
THANK YOU, IF YOU WERE RIGHT, THE PLOTS WERE ONLY THAT THE SYSTEM DOES NOT RECOGNIZE IT, SOLVED THANKS
