### ISSUE TITLE
security

### ISSUE THREAD

**Issue by 1562102481** [Chia-Network/chia-blockchain#6252]
How to find the stolen Chia coin

**Comment by tiny0little** [comment]
one good  place to start - [chiaexplorer.com](https://www.chiaexplorer.com/)

**Comment by 1562102481** [comment]
> 一个很好的起点 - [chiaexplorer.com](https://www.chiaexplorer.com/)
Money was stolen by this wallet address xch1vfnvlcu5nr6qepu5kykj2652akznx8tukl6seehhucryvf3q66gqfxl4j3, please find,
14 COINS

**Comment by tiny0little** [comment]
I can confirm that this address has 14xch. please tell your story, to teach us how not to loose

**Comment by 1562102481** [comment]
My wallet is address is xch1s9km6fu9y55wcrec5h6jrw6jr5eqn9aqptrl5d5rs3802ws3tctq5dek80, In the afternoon on May 30 xch1vfnvlcu5nr6qepu5kykj2652akznx8tukl6seehhucryvf3q66gqfxl4j3 this purse stolen address the 14 c

**Comment by tiny0little** [comment]
how this person gained access to your wallet?

**Comment by 1562102481** [comment]
I don't know, please help me to get my money back, thank you

**Comment by tiny0little** [comment]
at this point I would worry about loosing more. I would generate new key and transfer all your farm rewards to new wallet. also made sure nobody will be able to access it by keeping private key and mnemonic seed very well protected

recovering your losses won't be possible using chia tools, you can't even prove that this 14xch are transferred from you. this is the other side of most of cryptocurrencies

**Comment by 1562102481** [comment]
I can prove that the money transferred from my purse, left on the height of 357012 turn, you can see my wallet address xch1s9km6fu9y55wcrec5h6jrw6jr5eqn9aqptrl5d5rs3802ws3tctq5dek80

**Comment by tiny0little** [comment]
yes, I can see that on chiaexplorer.com

**Comment by 1562102481** [comment]
Please help me recover the loss, thank you

**Comment by 1562102481** [comment]
You have to give an explanation

**Comment by tydeno** [comment]
Theres no way to get it back. The question is, how did they access your keys?
Did you run some 3rd Party Software for plotting and or monitoring? Or any 3rd Party script/SW you found on the web? 

If so, which ones?

**Comment by tydeno** [comment]
> You have to give an explanation

Theres no way to get it back. The question is, how did they access your keys?
Did you run some 3rd Party Software for plotting and or monitoring? Or any 3rd Party script/SW you found on the web?

If so, which ones?
