### ISSUE TITLE
[BUG] Full node uses 100% cpu on one thread, possibly IO overload

### ISSUE THREAD

**Issue by HarukaMa** [Chia-Network/chia-blockchain#6256]
**Describe the bug**
The full node occasionally (or almost always if you have too many connections) use about 100% cpu on one thread. 

The 100% cpu usage comes from the first thread full node spawns(on my env it's usually process pid + 2). Tried to profile the process:

![image](https://user-images.githubusercontent.com/861659/120166767-ea9bc900-c237-11eb-94a0-ff48ed9feca0.png)

It seems the CPU usage mainly comes from disk operations. `drop_cache` then `iotop` shows the full node is reading disk at moderate speed with almost full disk IO%.

It's possible that something caused excessive disk operations that overloaded the node, thus preventing the node from working correctly: `Don't have rc hash` errors only happen when the CPU usage is stuck at 100%. My speculation is that the node has been overloaded and new blocks could not be processed in time, so the full node could not process new SPs as they depend on the pending block. As a result, farmers connected to this node could not get those SPs. (It seems any SPs being cached will not be sent to farmers even after they are processed.)

From monitoring `top` output, it seems the main thread and the offending thread in this case will together use at most 100% CPU, so the code responsible should be in python runtime (GIL effect?).

EDIT: forgot to add that it’s more likely to stuck at 100% CPU if you have too many connections. I tried to accept up to 150 connections and the full node stopped handing SPs to farmers for more than 5 minutes. I’m keeping only less than 20 connections right now, and the CPU usage is considerably lower.

**To Reproduce**

1. Run the synced full node with more than 50 nodes connected.

**Expected behavior**
CPU usage should be below 50%. At least not kept at 100%.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04
- CPU: Intel(R) Xeon(R) Platinum 8259CL (from AWS)

**Additional context**
Possibly related issues: #6204 #3774

**Comment by gromran** [comment]
100% in top means 100% of one Core not 100% of the CPU

**Comment by HarukaMa** [comment]
> 100% in top means 100% of one Core not 100% of the CPU

Please assume 100% as 100% of one core as only Windows use 100% as whole CPU and obviously we are not talking about Windows here.

**Comment by gromran** [comment]
You didn't understand ...

**Comment by HarukaMa** [comment]
@gromran Unless you have more constructive content to add please don’t comment things like this.

**Comment by gromran** [comment]
You didn't understand ...
100% on a core means that the program is CPU bound at that point, and 100% on a core is no problem

**Comment by HarukaMa** [comment]
@gromran the issue here is the full node SHOULD NOT BE CPU BOUND at that time. It causes farmers to miss SPs.

Also from profiling result the CPU usage mainly comes from disk reads / kernel - user land overheads. It would stuck at 100% when it’s reading from memory cache.

So here is the question for you: I didn’t understand what? Do you understand what this issue is about?

**Comment by HarukaMa** [comment]
![image](https://user-images.githubusercontent.com/861659/120271076-9c450380-c2e5-11eb-91ee-1ef8d17dac43.png)

Python profiling shows the issue is actually on sqlite part. It seems some database operations are taking too long to complete (insert blocks?) and causing nodes to miss SPs.

**Comment by HarukaMa** [comment]
It seems this was already addressed in 1.1.6; however when upgrading my node `chia stop all` did not completely kills everything - `chia_daemon` was still running in background thus some old code was still being used.

Killing the daemon and restarting the node fixed it.
