### ISSUE TITLE
[BUG] why not synced of two wallet ,only one wallet syeced?

### ISSUE THREAD

**Issue by yuzhongrong** [Chia-Network/chia-blockchain#6266]
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ CHIA_ROOT="~/.chia/testnet" chia wallet show
Choose wallet key:
1) 2331392080
2) 2522762654
3) 454193403
Enter a number to pick or q to quit: 2
Wallet height: 95248
Sync status: Not synced
Balances, fingerprint: 2522762654
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 txch (0 mojo)
   -Pending Total Balance: 0.0 txch (0 mojo)
   -Spendable: 0.0 txch (0 mojo)
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ CHIA_ROOT="~/.chia/testnet" chia wallet show
Choose wallet key:
1) 2331392080
2) 2522762654
3) 454193403
Enter a number to pick or q to quit: 3
Wallet height: 6173
Sync status: Not synced
Balances, fingerprint: 454193403
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 0.0 txch (0 mojo)
   -Pending Total Balance: 0.0 txch (0 mojo)
   -Spendable: 0.0 txch (0 mojo)
(venv) ipfsnets@r730-202:~/chia/chia-blockchain$ CHIA_ROOT="~/.chia/testnet" chia wallet show
Choose wallet key:
1) 2331392080
2) 2522762654
3) 454193403
Enter a number to pick or q to quit: 1
Wallet height: 139554
Sync status: Synced
Balances, fingerprint: 2331392080
Wallet ID 1 type STANDARD_WALLET
   -Total Balance: 3.832 txch (3832000000000 mojo)
   -Pending Total Balance: 3.832 txch (3832000000000 mojo)
   -Spendable: 3.832 txch (3832000000000 mojo)

**Comment by yuzhongrong** [comment]
2331392080 of fingerprint is synced   other not synced

**Comment by sptty** [comment]
Does anyone know how to solve the problem？
