### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ahonesty** [Chia-Network/chia-blockchain#6274]
can not join wallet
![image](https://user-images.githubusercontent.com/85128611/120226428-62d2b080-c271-11eb-8acd-0a528fa6aee8.png)
3hours still connecting to wallet, how to solve?

**Comment by XIII39** [comment]
Are you on Windows?
Close the Chia software.
Open Task Manager and ensure that all of the processes are stopped;
```
start_wallet.exe
start_harvester.exe
start_full_node.exe
daemon.exe
Console Window Host
Chia Blockchain
Chia
```

Then re-start the Chia GUI, it should reconnect.

**Comment by MontajnikRTA** [comment]
me to
