### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lwloo** [Chia-Network/chia-blockchain#6292]
**Describe the bug**
I am using a S3 bucket (via goofys) and gets the following error:
Could not copy "/tempchiaraid0/plot-k32-2021-05-31-20-24-884cd963a00856fc8428b721cabacdaf343619119b7f16c28cab948324fbb9f0.plot.2.tmp" to "/xxx/chia-pc1/plot-k32-2021-05-31-20-24-884cd963a00856fc8428b721cabacdaf343619119b7f16c28cab948324fbb9f0.plot.2.tmp". Error Operation not permitted. Retrying in five minutes.

I am able to use non-roor user to create directory/write file into the DST directory specified with no issue, I can see that plotman/chia written the file but it's 0 bytes.

![image](https://user-images.githubusercontent.com/16340329/120259547-bf13ef80-c2c6-11eb-9e53-8ae6f8bfb513.png)

Please help....

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Additional context**
Using Goofys connecting to S3 bucket with full policy permission.

**Comment by hoffmang9** [comment]
Not a bug
