### ISSUE TITLE
[BUG] Syncing stops every night 

### ISSUE THREAD

**Issue by JurgyR** [Chia-Network/chia-blockchain#6299]
since 1.1.5, syncing stops every night 3 am MESZ.
did not occur in 1.1.4 - until bug fix, I will return to this.

**Comment by JurgyR** [comment]
"connect to other peers" does not help, full restart needed

**Comment by room101-dev** [comment]
> since 1.1.5, syncing stops every night 3 am MESZ.
> did not occur in 1.1.4 - until bug fix, I will return to this.

I fell back to 1.3 weeks ago, last stable version; Now I have quit altogether I just use the plotter 1.3, and MINE on HPOOL +1,000 plots, now earning a whopping $9/day.

Even at the best times I never saw chia not drop every few hours, in fact I have never seen chia stay online +8 hours, it usually on for 6 and off for 2, 24/7 and post 1.5, it quit working, and then 1.6 they added the 5 second rule which killed farming, and 'chia plots check' which even destroys plot drives.

**Comment by JavierOrzaiz** [comment]
A mi me ocurre igual hacia las 00:00 hora española, y despues no hay manera de arrancar

**Comment by keliew** [comment]
Maybe, upgrade to 1.1.6?

**Comment by JurgyR** [comment]
Yes, tried 1.1.6 a few days, without issues. Topic seems to  be fixed.
