### ISSUE TITLE
[BUG] Full Node interface not loading / Plots still unavailable 

### ISSUE THREAD

**Issue by achaps** [Chia-Network/chia-blockchain#6310]
Hi guys,

So as you see in the title I have a bug pretty complicated to resolve, my full node interface is permanently loading and all of my 12 plots are «Not Available ». I’ve already tried almost everything I’ve seen here : 

* Change date/time to sync it automatically 
* My port forwarding is OK 
* Add permissions in the Windows firewall
* Delete UpNp from my isp router 
* Execute the Chia.exe in administrator 
* Try to reinstall Chia blockchain in 1.1.16

Nothing work for me, I don’t understand … When I go in the «advanced parameter » of the Farm section I see that everything have the «connected » status, and I have one local IP in the harvesting network section. 

![E09FEEC4-CB1D-4E6F-9459-FD2C8A056893](https://user-images.githubusercontent.com/85167091/120314514-9b0ed900-c2db-11eb-86d1-154b11357825.jpeg)

If you have any other idea or recommandation let me know, I’m sure some of you have resolved the same issue. 

Thank you guys, I hope we will find a solution :) 

OS : Win 10 professional 
CPU : 2x Intel Xeon E5-2603V4

**Comment by eliolonghi** [comment]
have you ever tried to connect to node.chia.net:8444 peer?
