### ISSUE TITLE
Gui will not load [BUG]

### ISSUE THREAD

**Issue by Chevdevi76** [Chia-Network/chia-blockchain#6311]
<img width="1202" alt="chia problem" src="https://user-images.githubusercontent.com/85167907/120314878-b3fe9680-c2a9-11eb-97c6-666ad65d573e.PNG">
After I shut down yesterday and windows auto-updated, I cant load the gui. After it times out it just stays on a white screen. I have tried Reinstalling the program.

**Comment by movbx** [comment]
so am I

**Comment by boybun** [comment]
me too

**Comment by aradesl766** [comment]
mee too

**Comment by sawicpx** [comment]
me too

**Comment by Muasin94** [comment]
For Windows:
Shut down Chia GUI
User\YOURNAME\.chia\mainnet\wallet\db
and delete all the file with: BLOCKCHAIN_WALLET
Then restart GUI.

**Comment by Chevdevi76** [comment]
> For Windows:
> Shut down Chia GUI
> User\ YOURNAME\ .chia \ mainnet \ wallet \ db
> and delete all the file with: BLOCKCHAIN_WALLET
> Then restart GUI.

I tried that from another board, it doesn't seem to change anything.

**Comment by Muasin94** [comment]
> > For Windows:
> > Shut down Chia GUI
> > User\ YOURNAME\ .chia \ mainnet \ wallet \ db
> > and delete all the file with: BLOCKCHAIN_WALLET
> > Then restart GUI.
> 
> I tried that from another board, it doesn't seem to change anything.

then I don't know how to help you, this method worked for me

**Comment by boybun** [comment]
i try it and it worked
thank you

**Comment by Muasin94** [comment]
> i try it and it worked
> thank you

np, happy to have helped

**Comment by mariano54** [comment]
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue
