### ISSUE TITLE
[BUG] Wallet Not Syncing (Mac Os)

### ISSUE THREAD

**Issue by chiafarmer2021** [Chia-Network/chia-blockchain#6320]
I am using Mac OS and having an issue with the wallet.

Using Mac Os Catalina 10.15.3
Using Chia Blockchain 1.1.6

I am 'synced' to the FULL NODE but the wallet is not synced.

I do not see anywhere to update settings for the wallet or troubleshoot.

Does anyone know how to resolve it?

**Comment by litterGuy** [comment]
Got the same problem

**Comment by mariano54** [comment]
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check and discuss in that issue
