### ISSUE TITLE
[BUG] Bad Allocation

### ISSUE THREAD

**Issue by gabrieldeina** [Chia-Network/chia-blockchain#6321]
Hey!

**Description**
I'm having always the same problem when I try to start a plot creation. I've already done 10 plots, but since I got the 10 plots, the problem to create more apeared. The image show everything that I have on View Log. My Node Status is Synced. I have enough RAM to create, it's the same of I was using on the creation of the first 10 plots.

**How to reproduce**

1. Go to 'Plots'
2. Click on 'Add a Plot'
3. Choose Number of Plots: Advanced Options - RAM max 3390 MiB, Number of threads 2 (default of chia)
4. Temporary is an empty SSD and Final directory has more than 2TB free space
4. View log below

**Screenshots**
![image](https://user-images.githubusercontent.com/40798190/120365099-681d1300-c2e4-11eb-930f-20438c557bb4.png)

**PC Configuration**
- OS: Windows 10
- CPU: Phenom II X4
- RAM: 6.0GB
- Creating Plots SSD: 500GB
- Done Plots Storage: 3TB

**Comment by gromran** [comment]
disabled swap file?

**Comment by wtj1206** [comment]
The memory configuration exceeds the total?

**Comment by gabrieldeina** [comment]
> disabled swap file?

How do I do this?

**Comment by gabrieldeina** [comment]
> The memory configuration exceeds the total?

I discovered that it was exceeding the RAM, and I changed from 6gb to 8gb ram.
When I was using the last version, before the actual. I was doing plots with 4MiB and it was fine.
But when I updated the Chia GUI, the program was using more RAM.
The main problem was resolved.
