### ISSUE TITLE
[BUG] CHIA Blog say's that Corsair MP600 is best for plotting - I'm not finding that outcome

### ISSUE THREAD

**Issue by room101-dev** [Chia-Network/chia-blockchain#6347]
**Describe the bug**
Once again, what we read from chia-team/dev is that they siphon up manufacturers claims, get their check, and never test themselves.

**To Reproduce**

Buy a MP600 and do plots on it, its the best NVME for plotting, yada so say the plotting experts at chia-net-dev wonderland.

Yes, I stagger 1hr on each process begin, but I have +20min is fine, as its the HHD final write that is the bottle-neck.

**Expected behavior**

Well I expected it to perform better than the EVO-PRO 980, which always burn-up when plotting, post +100 plots.

**Screenshots**

**Desktop (please complete the following information):**

32 core, 512mb ram, 3 nvme, 2 sata-ssd, six hdd's

**Additional context**
Well the problem is HEAT, and heat kills, I already learned the hard way not to push the samsung evo 980 past 4x plots at once, lucky I started with five on the MP600, cuz it alread temp sky-rocketed, and I had to pull the covers off the desktop, and put bigger fans blowing on the MP600
I will continue with 5, and see if the plots terminate, and watch stat's IMHO I'll probably be doing 4x, just like the samsung, as its clear the mp600 isn't any better.

**Comment by bunkaq** [comment]
Frankly system optimalization is not bug. You need to tune your setup as per our HW and find bottle neck if required, but i do not see how advice of some blog is BUG ;-)

**Comment by 24601** [comment]
Not. A. Bug. This is the second spam "Bug" from this user, can we ban/limit people like this? 

@room101-dev
