### ISSUE TITLE
[BUG]CHIA DEV Promised that Corsair MP600 was the Best - Died first use Plotting- Worst than EVO PRO 980

### ISSUE THREAD

**Issue by room101-dev** [Chia-Network/chia-blockchain#6352]
**Describe the bug**
I usually see my NVME's die at 100 plots, but this is the first time I saw first plot, the entire reason I bought the MP600 is the chia-blogs rave its the best, near enterprise, ... blah blah, obviously that was a PAID advert like all chia

**To Reproduce**

BUY MP600, plot as directed, DIE over heat +70C right away

**Expected behavior**
I expected NVME not to die first use

**Screenshots**

**Desktop (please complete the following information):**

cpu 32 core, 512mb ram, 3 nvmes, 2 ssds, 8 hdds

**Additional context**
So  now its back to the Samsung EVO 980, which I know I can plot 4x with 1hr stagger, its a known known, and sometimes I get more than 100 plots.

It's clear the MP600 is garbage, that it cannot handle chia-plotting, its clear that nobody ever tested the drive before they endorsed it as the best on chia-blog, best NVME drives.

**Comment by gromran** [comment]
thats not an issues or bug! already the second spam post from you

**Comment by 24601** [comment]
Not. A. Bug. How can we ban spammers like this?
