### ISSUE TITLE
Plot becomes invalid with "AssertionError" 

### ISSUE THREAD

**Issue by whitetechnologies** [Chia-Network/chia-blockchain#6354]
**Describe the bug**
Plot a plot (this one was plotted on 5/18) and run plot check on it. Plot initially passes plot check. 

**To Reproduce**
Farm plot for some time. Eventually the plot will become invalid and plot check will return: "2021-06-02T08:38:17.921  chia.plotting.check_plots        : ERROR    <class 'AssertionError'>:  error in proving/verifying for plot H:\ChiaFarmingC-1\plot-k32-2021-05-18-06-58-val43813469fd0dcf4ba70ad322d685dbd2ecfd44e88a858f48e51e65773eaed.plot"

To eliminate computer specific error, hardrive was moved to another PC running chia and returned the same error when using plot check. 

Chkdsk on the drive did not return any errors in this file

**Expected behavior**

Plots should not go bad over time. Understandable that hardware issues can occur. However, this is a plot on an HDD that is brand new, is not used as a a plotting drive (final dir only), and has 70 other plots on it that are all ok (for now). 

Plots should be a bit more resistant to small bit errors and not die completely like this. This indicates that plots are inherently unstable, and unless saved on Enterprise grade HDDs, they do have a life expectancy (again, talking about farming here, not plotting, which we all understand is much more hardware intensive). 

- OS: Win 10
- CPU: Core i-5 9600k and core i5 5600

**Comment by maxbelz** [comment]
same here.

**Comment by Jaga-Telesin** [comment]
Had this happen today to 2 plots.  One was generated in the last 8 hours, one was more than 3 days old and had been passing challenges since creation.  Both simply started failing in the plot checker spontaneously.  Drives check out fine.

**Comment by whitetechnologies** [comment]
Most likely a hard drive issue. With the plots on which this happened, the hard drive eventually died completely. It was a Seagate Barraccuda which is 10/10 deaths from Chia at this point. Other HDDs seem to be much better and no issues so far with 1000+ plots

**Comment by Jaga-Telesin** [comment]
Running all WDs here, 8TBs each and only ~3 years old (with zero error rates hosting other content via DrivePool).  You could be right, but SMART on the drives isn't reporting any issues at this time, not even reallocated sectors.
