### ISSUE TITLE
[BUG] Plotting no longer progress (SEGFAULT in first phase)

### ISSUE THREAD

**Issue by codergoblin** [Chia-Network/chia-blockchain#6357]
**UPDATE** 

When I attempt to create a plot from command line, I immediately get a segmentation fault, which would explain why UI does not show any progress after initialization 

**Command** `chia plots create -n 1 -r 4 -t  /media/ben/sandisk_ssd/chia-tmp/default -d /media/ben/ac056a7c-a298-4f38-a059-c65e4a220614/chia/plots`

**Output:**
```
2021-06-04T14:17:55.913  chia.plotting.create_plots       : INFO     Creating 1 plots of size 32, pool public key:  8d2e21cc910680046cd5a294b7c101c6d6e94c402c35579f241daadb2ed78ba85426ec406ee6a16961daed8184db17d5 farmer public key: a3afb4c3ef70d9b95124729d933be28ce5c24f2776dc2e89761ba808a0d268ebbdabdc71934babe657af6d46a636aa14
2021-06-04T14:17:55.919  chia.plotting.create_plots       : INFO     Memo: 8d2e21cc910680046cd5a294b7c101c6d6e94c402c35579f241daadb2ed78ba85426ec406ee6a16961daed8184db17d5a3afb4c3ef70d9b95124729d933be28ce5c24f2776dc2e89761ba808a0d268ebbdabdc71934babe657af6d46a636aa140032770550dc48c656112d18636c1e4565a3eea2d9da2822a58e8d2294cf60b6
2021-06-04T14:17:55.919  chia.plotting.create_plots       : INFO     Starting plot 1/1

Starting plotting progress into temporary dirs: /media/ben/sandisk_ssd/chia-tmp/default and /media/ben/sandisk_ssd/chia-tmp/default
ID: 01189a20f22dde8e5726eb13d91f1a7f1c13493a23c783a58b0b47e2ed9e2bb8
Plot size is: 32
Buffer size is: 3389MiB
Using 128 buckets
Using 4 threads of stripe size 65536
[1]    2618212 segmentation fault (core dumped) 
```

same thing happens for different drives for both output and tmp dirs, so I don't think it's disk related

---------------------------

**Describe the bug**
After latest update plotting staggers immediately after start. All started plots stay at 0% indefinitely. Logs display no errors, just normal initialization message of the plot start.

**Version**
Chia blockchain: 1.1.6 Thu May 20 19:28:09 2021
Chia blockchain gui: 444c6966fe50183c8d72cbc972c5403db341739c (HEAD -> main)  Thu May 20 20:29:01 2021 +0200

**I tried:** 
* Different tmp and destination locations. (500 GB SSD, 4TB HDD, 8TB external HDD)
* Using different amount of ram, threads and plots in queue
* Restarting the wallet
* Restarting the computer
* Waiting for 24 hours
* Reinstalling chia from scratch

**To Reproduce**

1. Go to plots tab in the wallet gui
2. Click on add a plot
3. Issue a plot creation with any parameters
4. Wait to see the plot do not progress over 0%

**Expected behavior**
For the plot to progress normally

**Screenshots**

![image](https://user-images.githubusercontent.com/72735596/120526260-4ea9c300-c3d9-11eb-82c7-a45c9d426480.png)

![image](https://user-images.githubusercontent.com/72735596/120798684-01933180-c53e-11eb-9409-340c5a419023.png)

![image](https://user-images.githubusercontent.com/72735596/120798804-2f787600-c53e-11eb-8346-00c03b2abcc9.png)

**Desktop (please complete the following information):**

- OS: GNU/Linux
- OS Version/Flavor:  Ubuntu 20.04.2 LTS 64bit
- Kernel: 5.8.0-61-generic
- CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

-----------------------------------------------

**Comment by faheem2100** [comment]
I also have the same issue.  My first plot is stuck at 1% from the last 10 days.  Please help me resolve it.

Thanks

**Comment by codergoblin** [comment]
@faheem2100 Can you paste your logs? If it progressed and staggered it's possibly a different issue.

**Comment by ziggy1001** [comment]
Same here
![Chia_FZksKhEEo5](https://user-images.githubusercontent.com/85291307/120639634-c50ef980-c49b-11eb-96ed-54461ebb55e8.png)

**Comment by faheem2100** [comment]
> @faheem2100 Can you paste your logs? If it progressed and staggered it's possibly a different issue.

![Plotting Error](https://user-images.githubusercontent.com/85276668/120755193-a3356700-c4db-11eb-8ed8-9ef43b8cecc7.JPG)

Hi,

This is the image of Error Log.  Please advise how to correct it.

**Comment by codergoblin** [comment]
@faheem2100 @ziggy1001 Both of you have an error in the log and are stuck at 1% instead of 0%, which means you have completely different problem from what's described in the bug. Perhaps you should create a new issue.

**Comment by faheem2100** [comment]
@codergoblin Please let me know how to correct this issue ?

Best Regards

**Comment by madmmmax** [comment]
> @codergoblin Please let me know how to correct this issue ?
> 
> Best Regards

We need CHIA fix it instead us. tons of miners have this issue, kinda like the sync issue before.

**Comment by codergoblin** [comment]
> @codergoblin Please let me know how to correct this issue ?
> 
> Best Regards

I posted the link for an issue that matches yours, please go to the correct issue to continue the topic. Don't spam this thread with off topic messages, it's not my job to fix issues.

**Comment by codergoblin** [comment]
Upgraded chia network to 1.2.0, the issue persists
