### ISSUE TITLE
Failed to Open (invalid plots)

### ISSUE THREAD

**Issue by beged** [Chia-Network/chia-blockchain#6376]
hi there, I still was not able to solve copied invalid plots issue: I do run plotting on my several machines, but when copy them to the other machine with large disk running full node I got the  “Failed to Open (invalid plots)” message in UI (win10) keys are OK, check shows no error, no duplicate plots, restart the full node does not help as it appear after a while again... 
I searched and read all post on that, but it seems to be no longer term solution yet.
no I have no error, they are copied and they are there
I also examined debug.log in info mode, but no significant entry regarding this issue, no errors

could you add some log entry where this message is triggered? to be able to understand the root cause of this

**Comment by wtj1206** [comment]
Try to use the same wallet?

**Comment by chengyap98** [comment]
i also faced this issue few minutes ago. anyone can help? 
![image](https://user-images.githubusercontent.com/79273533/120621935-f2a27580-c490-11eb-92fb-26af1a314975.png)

**Comment by beged** [comment]
yes I used the same wallet and keys (imported from 24 words) on all machines I made the plots...

**Comment by beged** [comment]
it seems to be that after restart the application (full node UI) it disappear, but after a while it will show again as invalid the copied plots from other drive/machine

**Comment by chengyap98** [comment]
mine is all on the same machine, this happen after i restarted the Chia GUI

here's the error:

2021-06-03T17:49:40.969  chia.plotting.check_plots        : INFO     Loading plots in config.yaml using plot_tools loading code

2021-06-03T17:49:41.033  chia.plotting.plot_tools         : INFO     Searching directories ['D:\\farm', 'E:\\Farm', 'H:\\farm']
2021-06-03T17:49:41.038  chia.plotting.plot_tools         : INFO     Only loading plots that contain "E:\Farm" in the file or directory name
goodbit, failbit, badbit, eofbit: 0201
2021-06-03T17:49:41.053  chia.plotting.plot_tools         : goodbit, failbit, badbit, eofbit: 0201
ERROR   goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201
 Failed to open file E:\Farm\plot-k32-2021-04-16-03-24-22827c79340b36e74e2a83a483da95ef64306853c79de574400c96ed2e02429b.plot. badbit or failbit after reading size 104 at position 0 Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 189, in process_file
RuntimeError: badbit or failbit after reading size 104 at position 0
goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201

goodbit, failbit, badbit, eofbit: 0201
2021-06-03T17:49:41.054  chia.plotting.plot_tools         : goodbit, failbit, badbit, eofbit: 0201
ERROR   goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201

**Comment by eliolonghi** [comment]
> hi there, I still was not able to solve copied invalid plots issue: I do run plotting on my several machines, but when copy them to the other machine with large disk running full node I got the “Failed to Open (invalid plots)” message in UI (win10) keys are OK, check shows no error, no duplicate plots, restart the full node does not help as it appear after a while again...
> I searched and read all post on that, but it seems to be no longer term solution yet.
> no I have no error, they are copied and they are there
> I also examined debug.log in info mode, but no significant entry regarding this issue, no errors
> 
> could you add some log entry where this message is triggered? to be able to understand the root cause of this

I had this problem and I solved by formating my HDD as NTFS (not fat, neighter fat32). Then the copy process go fine!
