### ISSUE TITLE
Failed to open (invalid plots)

### ISSUE THREAD

**Issue by chengyap98** [Chia-Network/chia-blockchain#6379]
Please anyone can help me. All my plots go invalid after I restarted the Chia GUI. 

![image](https://user-images.githubusercontent.com/79273533/120628972-e2da5f80-c497-11eb-8534-0328b182c144.png)

here is what it showed when I do the plots check

2021-06-03T17:49:40.969 chia.plotting.check_plots : INFO Loading plots in config.yaml using plot_tools loading code

2021-06-03T17:49:41.033 chia.plotting.plot_tools : INFO Searching directories ['D:\farm', 'E:\Farm', 'H:\farm']
2021-06-03T17:49:41.038 chia.plotting.plot_tools : INFO Only loading plots that contain "E:\Farm" in the file or directory name
goodbit, failbit, badbit, eofbit: 0201
2021-06-03T17:49:41.053 chia.plotting.plot_tools : goodbit, failbit, badbit, eofbit: 0201
ERROR goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201
Failed to open file E:\Farm\plot-k32-2021-04-16-03-24-22827c79340b36e74e2a83a483da95ef64306853c79de574400c96ed2e02429b.plot. badbit or failbit after reading size 104 at position 0 Traceback (most recent call last):
File "chia\plotting\plot_tools.py", line 189, in process_file
RuntimeError: badbit or failbit after reading size 104 at position 0
goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201

goodbit, failbit, badbit, eofbit: 0201
2021-06-03T17:49:41.054 chia.plotting.plot_tools : goodbit, failbit, badbit, eofbit: 0201
ERROR goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201
goodbit, failbit, badbit, eofbit: 0201

**Comment by slash236** [comment]
Well i got the same problem... its happen because i dont turn off Hpool Miner Gui before reopen Chia Gui, I think the sistem consider invalid because the plots already been used in the pool.

**Comment by bashar1988** [comment]
the same problem the GUI also the Hpool dose not read the Plots

**Comment by bossturk** [comment]
I have that same problem

**Comment by tiagodog21** [comment]
Same here.    Mesmo problema . Somente reiniciei o sistema e 40% dos plots corromperam .

**Comment by Zeesy** [comment]
I have this issue with Space Pool. I had plotted 3 plots already, was still hanging at 100% plotting after 12 hours after my second round of 3 plots. Only 3 invalid plots were found running `chia plots check` at this point, although 3 valid plots existed before. After shutting down both GUIs, number of plots under Pooling Plots is still 0.
