### ISSUE TITLE
missing xch fund in wallet

### ISSUE THREAD

**Issue by nedotolj** [Chia-Network/chia-blockchain#6384]
Dear all

I want to advice you after reinstaling windows and instaling new windows 10 and also chia blockchain for win 10 instaling again.
I open my chia blockchain after sync of this there is missing 0.013XCH i already had in wallet.
i enter the same 24 mnemonic words.everything is the same but 0.013xch in my wallet missing.

Brgds

N.Tolj

**Comment by joelrb** [comment]
Wait for full sync.

> Dear all
> 
> I want to advice you after reinstaling windows and instaling new windows 10 and also chia blockchain for win 10 instaling again.
> I open my chia blockchain after sync of this there is missing 0.013XCH i already had in wallet.
> i enter the same 24 mnemonic words.everything is the same but 0.013xch in my wallet missing.
> 
> Brgds
> 
> N.Tolj

Wait for sync to complete.

**Comment by nedotolj** [comment]
Dear Mr.Ballesteros

My full sync is completed but still the same.0.013xch missing.

Brgds

N.Tolj

**Comment by hashTor** [comment]
same thing, the Chia explorer shows the full amount. I tried to use fully sync machine it does not shows the full amount.

**Comment by badandybrew** [comment]
I can confirm that I am missing 2 XCH that I farmed.  I am running Ubuntu.

**Comment by badandybrew** [comment]
I just reinstalled the gui says synced and I am farming away under the Full Node tab, however I noticed that the wallet still says syncing and a height way less than the height on Full Node tab.  I am missing 2 XCH in the wallet right now.   chia wallet show confirms the wallet is Not Synced.  Is there a command that sync the wallet?

**Comment by keliew** [comment]
Just need to wait for wallet to sync...

**Comment by nedotolj** [comment]
Wallet is sinc completed.but still missing.

**Comment by mariano54** [comment]
Have you tried deleting the wallet DB and resyncing? 
Check the steps here:
https://github.com/Chia-Network/chia-blockchain/issues/6993
