### ISSUE TITLE
[BUG] Command 'chia farm summary' sometimes displaying 'total chia farmed' and 'block rewards' as 0

### ISSUE THREAD

**Issue by aXZhbg** [Chia-Network/chia-blockchain#6385]
There is a slight (?) chance when command 'chia farm summary' is ran that 'total chia farmed' and 'block rewards' are 0.
Most of the time it works properly showing actual values, but sometimes it would show them as 0.
Running the command 10 seconds later it shows the proper values again.

1. Run command 'chia farm summary'
2. Observe 'total chia farmed' and 'block rewards' fields

The properties in question should always reflect real values.

OS: Ubuntu 20.04

This bug doesn't happen in any way that is obvious to me, sometimes it happens, 10 seconds later it may not.

**Comment by baizuchong-net** [comment]
你的账本是否更新到最高高度，如果没有，那就是0

**Comment by aXZhbg** [comment]
> Is your ledger updated to the highest height, if not, it is 0

It is updated to the latest block, as I said, sometimes when I run the command it shows the right value, after 10 seconds when I rerun the command it may show 0.

**Comment by q1k** [comment]
I had problems with ubuntu, switched to windows and no problems
