### ISSUE TITLE
Greetings. Guys, help me figure it out. When entering the wallet, it requires dragging and dropping a backup file, but during registration, I did not save or register any such files. I am writing in support of the official website - silence. Has anyone encountered such a problem? please unsubscribe. Thank you in advance

### ISSUE THREAD

**Issue by Art0305** [Chia-Network/chia-blockchain#6387]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**
![chia1](https://user-images.githubusercontent.com/85294196/120650585-9a667600-c486-11eb-8be1-2e6fe89587cd.png)

**Comment by joelrb** [comment]
Just skip.

**Comment by Art0305** [comment]
Excluded
![chia2](https://user-images.githubusercontent.com/85294196/120651540-91c26f80-c487-11eb-88cb-f7c226e490d3.png)

**Comment by Art0305** [comment]
> Just skip.

Excluded

**Comment by q1k** [comment]
I've always been skipping that

**Comment by Art0305** [comment]
> I've always been skipping that

The problem is that after the money is credited to the account, the wallet does not let me in

**Comment by q1k** [comment]
weird, i've used the mnemonic multiple times, skipped that screen (safe to skip), and apart from the occasional infinite loading it always loads into the wallet. Never got any errors.
