### ISSUE TITLE
5950x 8tssd

### ISSUE THREAD

**Issue by b6121061** [Chia-Network/chia-blockchain#6388]
My 5950x 8tm. 2 can only write 4.5t a day and write 10 pictures simultaneously. After that, the speed of SSD drops seriously

**Comment by b6121061** [comment]
> 我的 5950x 8tm。2 一天只能写4.5ta，同时写10张图。之后SSD速度下降严重

It takes 10 hours to finish

**Comment by zhangxxyz** [comment]
ssd的问题，这个没办法啊

**Comment by b6121061** [comment]
> ssd的问题，这个没办法啊



> ssd的问题，这个没办法啊

我觉得应该不是ssd问题，因为我前面8张是写在一张ssd上面，后面追加的图是写在别的ssd
