### ISSUE TITLE
[BUG] Failed to open (invalid plots) When plots are moving to External HD

### ISSUE THREAD

**Issue by eliolonghi** [Chia-Network/chia-blockchain#6390]
[Description]
Every time I try to create some plots happen the same error: Failed to open (invalid plots) both of mine machines.

I saw at the destination folder that final plot size on external HD is just 4,3gb. Temp files gets around 240gb.

I have two machines both with Ubuntu 20.04 LTS Focal Fossa:
1) Machine 1: Ryzen 5 2400g / 16gb RAM / 1T nvme / 4 External HD 6T each
2) Machine 2: Dell G7 i7 / 16gb RAM / 2T nvme / 6 External HD 6t each.

I've never had a good plot. All of them goes as invalid.

[To Reproduce]
1. Installed with deb file
2. Tried to upgrade by terminal
3. Uninstall and reinstalled by terminal
4. Tried to exclude plot directories restart GUI and put them back
5. Tried differents External HD

None of this worked

[Plot Config]
Tried a plenty of combination

Mem RAM: 2640 (medium capacity as sugested at FAQ) / full capacity (14000) of computer
Threads: 2 / 4 / 10 (10 just on dell g7)

[Error Message]
In the terminal I tried this: chia plots check -l
and gets:

2021-06-03T11:54:16.509  chia.plotting.check_plots        : WARNING  Checking for duplicate Plot IDs
2021-06-03T11:54:16.509  chia.plotting.check_plots        : INFO     Plot filenames expected to end with -[64 char plot ID].plot
2021-06-03T11:54:16.509  chia.plotting.check_plots        : INFO     Loading plots in config.yaml using plot_tools loading code

2021-06-03T11:54:17.590  chia.plotting.plot_tools         : INFO     Searching directories ['/media/srvchia/Q7G7']
goodbit, failbit, badbit, eofbit: 0400
2021-06-03T11:54:17.593  chia.plotting.plot_tools         : ERROR    Failed to open file /media/srvchia/Q7G7/plot-k32-2021-06-02-20-03-e012f6a7e13b641cc01c0278b82c4f86d723bfbbc2be56ac1b5deec939162bdf.plot. badbit or failbit after seeking to 107593480766 Traceback (most recent call last):
  File "/home/srvchia/chia-blockchain/chia/plotting/plot_tools.py", line 189, in process_file
    prover = DiskProver(str(filename))
RuntimeError: badbit or failbit after seeking to 107593480766

2021-06-03T11:54:17.593  chia.plotting.plot_tools         : INFO     Loaded a total of 0 plots of size 0.0 TiB, in 0.034284353256225586 seconds
2021-06-03T11:54:17.593  chia.plotting.check_plots        : INFO     
2021-06-03T11:54:17.593  chia.plotting.check_plots        : INFO     
2021-06-03T11:54:17.593  chia.plotting.check_plots        : INFO     Summary
2021-06-03T11:54:17.594  chia.plotting.check_plots        : INFO     Found 0 valid plots, total size 0.00000 TiB
2021-06-03T11:54:17.594  chia.plotting.check_plots        : WARNING  1 invalid plots found:

[Expected behavior]
After finish plotting plot going to farm. But never gone.

**Comment by bashar1988** [comment]
i have the same problem since today the GUI do not read the plots

**Comment by d4rkhunta** [comment]
This is how i fix it:

Dont copy the Plots to the finale Plot Folder because your farmer will try to open the unfinished Files an you get the error.  Create a New Folder and insert your plots files here. When youre done copying move it to your final Plot Folder and set the Folder in the chia Gui again. 
Now you shouldnt see any Errors

**Comment by eliolonghi** [comment]
> This is how i fix it:
> 
> Dont copy the Plots to the final Plot Folder because your farmer will try to open the unfinished Files an you get the error. Create a New Folder and insert your plots files here. When youre done copying move it to your final Plot Folder and set the Folder in the chia Gui again.
> Now you shouldnt see any Errors.

Understood i will try it. 
just one doubt, do i need to stop plot to make the folder change or simple keep the same folder for temp and final when create the plot?

**Comment by d4rkhunta** [comment]
I may have misunderstood you.
Are you plotting directly to the external HDD? Have you deactivated standby in the power management for the HDD? Are your plots not even finished?
Or is it just about that you get the error when copying from one HDD to another HDD.

**Comment by eliolonghi** [comment]
> I may have misunderstood you.
> Are you plotting directly to the external HDD? Have you deactivated standby in the power management for the HDD? Are your plots not even finished?
> Or is it just about that you get the error when copying from one HDD to another HDD.

no, were right at first.
 i am plotting at nvme setted on "Creat Plot" as tmp destination. the HDD is setted as final directory. 

and yes, when plot get to 100% became as "invalid plot"

what i didnt understood about your problem solution is about the folder. should i create the temp and the final destination to the nvme and then move manually?

**Comment by d4rkhunta** [comment]
> no, you were right at first.
> i am plotting at nvme setted on "Creat Plot" as tmp destination. the HDD is setted as final directory.
> 
> and yes, when plot get to 100% became as "invalid plot"
> 
> what i didnt understood about your problem solution is about the folder. should i create the temp and the final destination to the nvme and then move manually?

Ok my solution was actually related to copying from one hard drive to another. But you should try to create the final directory on the Nvme as a test, but you have to abort the current plotting. It is just very tedious to copy the finished plots every time.

**Comment by eliolonghi** [comment]
> > no, you were right at first.
> > i am plotting at nvme setted on "Creat Plot" as tmp destination. the HDD is setted as final directory.
> > and yes, when plot get to 100% became as "invalid plot"
> > what i didnt understood about your problem solution is about the folder. should i create the temp and the final destination to the nvme and then move manually?
> 
> Ok my solution was actually related to copying from one hard drive to another. But you should try to create the final directory on the Nvme as a test, but you have to abort the current plotting. It is just very tedious to copy the finished plots every time.

Awsome!
I setted the temp and final folder to the NVME and worked!! But I cant move nvme>HDD it said that "too large file".

I will test changing right now to create the new folder. Lets see if i understood correctly:
1. add a plot
2. set the temp file on nvme
3. set the final on new folder like hdd root
4. then move to final folder

am i correct?

**Comment by d4rkhunta** [comment]
> Awsome!
> I setted the temp and final folder to the NVME and worked!! But I cant move nvme>HDD it said that "too large file".
> 
> I will test changing right now to create the new folder. Lets see if i understood correctly:
> 
>     1. add a plot
> 
>     2. set the temp file on nvme
> 
>     3. set the final on new folder like hdd root
> 
>     4. then move to final folder
> 
> 
> am i correct?

Correct.

What file system is the external hard drive formatted with? FAT 32 ? It should be NTFS

**Comment by eliolonghi** [comment]
I will set up to plot right now and as soon as it ends i tell you the results.

The HDD is formated as ntfs but still gets the messge. I am thinking of unmount, format with gparted and mount again.

**Comment by d4rkhunta** [comment]
> I will set up to plot right now and as soon as it ends i tell you the results.
> 
> The HDD is formated as ntfs but still gets the messge. I am thinking of unmount, format with gparted and mount again.

Maybe your NVME is formated with EXFAT ?

**Comment by eliolonghi** [comment]
> > I will set up to plot right now and as soon as it ends i tell you the results.
> > The HDD is formated as ntfs but still gets the messge. I am thinking of unmount, format with gparted and mount again.
> 
> Maybe your NVME is formated with EXFAT ?

Its ext4

**Comment by d4rkhunta** [comment]
> > > I will set up to plot right now and as soon as it ends i tell you the results.
> > > The HDD is formated as ntfs but still gets the messge. I am thinking of unmount, format with gparted and mount again.
> > 
> > 
> > Maybe your NVME is formated with EXFAT ?
> 
> Its ext4

That should be the mistake. My NVME were also formatted with EXFAT by default. I then also formatted it with NTFS via GPARTED. After that, you shouldn't have any more problems. 
Have an nice day ;-)

**Comment by eliolonghi** [comment]
Nice!!
I will try it!!
Thank you so much!
Have a nice day too
