### ISSUE TITLE
Plotting/Farming Tabs Loading

### ISSUE THREAD

**Issue by jsantanajr21** [Chia-Network/chia-blockchain#6394]
The plotting/farming tabs in the Chia GUI are loading consistently and no information is displayed on the screen. Is there something that we should be aware of, or is this a user driven error regarding the hardware/equipment utilized?

**Comment by eliolonghi** [comment]
have u ever tried the 3 button on right to see the log?

**Comment by jsantanajr21** [comment]
No, I didn’t, but what exactly am I looking for? At the time this was happening, the plot tab had no information, it was just a black screen. It did however load up after a few hours. 

In addition, I’ve had to remove a hard drive, and I’ve been having additional issues creating new plots. It’s been twice now that a plot reaches 100% and it doesn’t pass through for the farming process. I am plotting just 1 plot right now to see if it completely finishes and transitions to farming. Prior to that, I was doing two plots in parallel which roughy takes around 28 hours. Any information you can provide would be greatly appreciated, thank you.

**Comment by eliolonghi** [comment]
> No, I didn’t, but what exactly am I looking for? At the time this was happening, the plot tab had no information, it was just a black screen. It did however load up after a few hours.
> 
> In addition, I’ve had to remove a hard drive, and I’ve been having additional issues creating new plots. It’s been twice now that a plot reaches 100% and it doesn’t pass through for the farming process. I am plotting just 1 plot right now to see if it completely finishes and transitions to farming. Prior to that, I was doing two plots in parallel which roughy takes around 28 hours. Any information you can provide would be greatly appreciated, thank you.

I see you have different problems.


I’ve misunderstood you about the black screen.
Which is your os?

About the plot process.
Please check if they are marked as invalid plot. If so go to your final plot folder and see if the plot size is about 4,3gb and tell me.

**Comment by eliolonghi** [comment]
28 hours plotting progress could be bottleneck. How did you set up to create plot? How many ram how many threads?

**Comment by jsantanajr21** [comment]
I am on windows 10

2 plots in parallel, with a 12 hour delay. 4g of ram, and 2 threads. I have an i5, but i have a total of 12g of ram, so maybe I should be setting the ram to 8g. I figured it would allow the first plot to finish to fully earlier than usual so that both plots had enough to complete the file efficiently. 

I tried smaller delays, but after several plots it really extended the amount of time. Initially I was having the two just fine, and that WAS roughly under 24 hrs. So I changed it up to what I stated above after some of my plots didn’t crossover to farming. Not sure what I’m doing wrong. I thought I had the right idea based on the documentation related and video media online among other users in the network.

**Comment by eliolonghi** [comment]
If you have 4gb and 2 threads for 2 plots could be the bottleneck.

Your system use a little of ram and at least 2 threads for sys op, I mean, if you have 12gb, free u will have less then it. ctrl+alt+del to enter on task manager to see the real free space od ram.

Try it step by step:
1) create new plot
1b) select the number of queue plots
2) set the "net" ram. If you have 12 but your system use 2,3 u just have 9,7ram. but the chia docs says you would use a MAX ram of 3600mb for each plot or medium use of 2460 and the minimum 900. 
3) threads is 2 or 4. Chia docs says if you use less is bad and if use more than 4 doesnt afect results.
4) set the name as Q1 (just a exemple)
5) mark as queue
6) select folders
7) create

now the trick.
your plot nvme/ssd/hdd has free 1,8T u need the calcs by the limitation of your ram and threads to set more plots in parallel.

and u will repeat the step by step above.

The time of your plotting process could be releated to the plot drive if it is nvme, ssd or hdd. nvme is the fastest.

did u solve the 100% not farming issue?
