### ISSUE TITLE
GET_PLOTS to be avaliable on harvester by a multi farm call  [enhancement]

### ISSUE THREAD

**Issue by filzek** [Chia-Network/chia-blockchain#6402]
The current design of the command GET_PLOTS relay only inside the current machine, if you are in a multifarm cenario the main farmer cant know exactly the numbers and info from the plots in the system.

It is very important to also add in the 8447 farmer connection list the ability that the farmer post a request in GET_PLOTS so all plots will be know by the farmer on the multi farm.

Please advise about this resource as it is very simple to add and very necessary for the currently Plots system.

This enhancement could help the main farmer to know all plots, plots healty, ids, and info on their harvesters machines!

**Comment by filzek** [comment]
So, the idea is to have the multifarm more simplified:

1) All connections made to the Farmer node from the certified TLS connection from the Harverster shall be add to a peer connected list.
2) All peer connected list shall have the request to send all Plots list to the Farmer
3) All plots with a valid Farmer Key shall be validated.
4) A testing plot shall be done to validate the plot and check if the plot pass all checks and be good or if the plot is within erro, so the harvester side test the plots and mark it as good or not.
5) the list of plots on the Farmer node be updated by each new changes in the harvester automatic.

I do not program in Python or I could help to program it and add it to all the files and propose a push to the main code, sorry to do not program in Python.

If it was in C, C++ or C# I could help a lot.

Changes proposed are extremely good and also could be also be good for the new protocol as well, as the Pool should know all plots on the user side as well.

**Comment by emlowe** [comment]
This is resolved in 1.2; there is a new RPC get_harvesters that provide this information
