### ISSUE TITLE
[BUG] Creating plot nft

### ISSUE THREAD

**Issue by ConDish** [Chia-Network/chia-blockchain#6405]
**Describe the bug**
When I try to create a plot using this command chia plotnft create -u

**To Reproduce**

1. chia plotnft create -u farm-testnet.pool.garden
2. Error creating plot NFT: {'error': "create_pooling_inner_puzzle() missing 1 required positional argument: 'owner_pubkey'", 'success': False}

**Screenshots**
![Screenshot from 2021-06-03 19-51-26](https://user-images.githubusercontent.com/29387286/120729565-18d21080-c4a5-11eb-93cf-f2fdbea477a3.png)

**Desktop (please complete the following information):**

- Ubuntu 18.04

**Comment by LouisLoudogTrottier** [comment]
I have the same issue on ubuntu 20.04, Or did we missed something? Please Advise.

I was follow this procedure https://github.com/Chia-Network/pool-reference#install-and-run-testnet
And ran chia plotnft create -u 127.0.0.1:80 -f [farmer fingerprint here]

And at step #9, the procedure says to use «poolnft» but it sems to be now «poltnft»

![Screenshot from 2021-06-04 20-57-34](https://user-images.githubusercontent.com/56370085/120875013-89e1f880-c577-11eb-8182-86da60ce116a.png)

**Comment by LouisLoudogTrottier** [comment]
LAtest update resolved the issue for me
