### ISSUE TITLE
[BUG] Stuck at 32% Step 3/4

### ISSUE THREAD

**Issue by rkho** [Chia-Network/chia-blockchain#6410]
**Describe the bug**
In the most recent plot I've attempted with the GUI, it has been stuck at 32% for roughly twenty hours, which is shortly after phase 3/4.

There are, noticeably, **no runtime errors**.

Here are the last couple lines of the log:
```
Starting phase 3/4: Compression from tmp files into "/mnt/ssd1/plot-k32-2021-06-02-23-18-32b770001387bfd5bb7fe887fc80d1928b9ead03eaa2a90bdb87442aea12ca92.plot.2.tmp" ... Thu Jun  3 02:12:48 2021
Compressing tables 1 and 2
	Bucket 0 uniform sort. Ram: 3.251GiB, u_sort min: 1.250GiB, qs min: 0.313GiB.
	Bucket 1 uniform sort. Ram: 3.251GiB, u_sort min: 1.250GiB, qs min: 0.313GiB.
	Bucket 2 uniform sort. Ram: 3.251GiB, u_sort min: 1.250GiB, qs min: 0.313GiB.
	Bucket 3 uniform sort. Ram: 3.251GiB, u_sort min: 1.250GiB, qs min: 0.313GiB.
```

If you require the entire log, I've made it available via [this gist](https://gist.github.com/rkho/85cea57a0e1dde1345551e19335293b1) to save others from scrolling through this thread.

**Desktop (please complete the following information):**

- OS: Ubuntu v20.04 LTS
- CPU: AMD Ryzen 5950X

**Additional context**

I began plotting approximately two weeks ago and was successful for a few days in having parallel plots at a one-hour offset to ten separate drives. A total of sixty plots were created this way. However, one day the system stopped completing existing plots for no apparent reasons I can foresee. 

I have since reformatted the temp SSD multiple times in an attempt to restart the process, but I have not been able to plot ever since. 

I just pulled down the latest version of chia-blockchain before beginning this most recent plot attempt.

**Comment by Grodahn** [comment]
I got the same problem several times on different Machines reproducable: 
Plots got Stuck somewhere in Step 3/4, running one Core on full load, no disc activity. 
Everytime i could dedicate the problem to HW-Problems: 
 - defective RAM
 - worn out SSD

If REALY needed i can force a Plot to get Stuck like this!

**Comment by vanthoi** [comment]
I also use 5950x and have this problem frequently. it's random, maybe 1 to 3 plots. Most of the time I see AMD-powered machines with bouncing errors. Same hardware ssd vs Ram then using intel no error. I have reported but no one has resolved.

**Comment by rkho** [comment]
@Grodahn thanks for the insight, how do you confirm if it's the RAM and/or SSD?

@vanthoi I'll try a few other plots and see what happens in this case. It's just really odd that everything worked for the first sixty or so plots before finally consistently failing.

**Comment by rkho** [comment]
I re-seated the RAM last night and started two new plots:

1. **Plot A**. Temp drive: SSD (U.2 drive -> M.2 adapter), Destination drive: HDD1
2. **Plot B**, Temp drive: HDD2, Destination drive: HDD2

Plot A stalled at **35%** on `Bucket 74 uniform sort`
Plot B stalled at **57%** on `Bucket 63 uniform sort`

Running SMART checks on the U.2:

```
walterspc@walter:~/Git/chia-blockchain/chia-blockchain-gui$ sudo smartctl -a /dev/nvme0n1
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.8.0-55-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       INTEL SSDPE2KE032T8
Serial Number:                      PHLN106002Q93P2BGN
Firmware Version:                   VDV10152
PCI Vendor/Subsystem ID:            0x8086
IEEE OUI Identifier:                0x5cd2e4
Total NVM Capacity:                 3,200,631,791,616 [3.20 TB]
Unallocated NVM Capacity:           0
Controller ID:                      0
Number of Namespaces:               128
Namespace 1 Size/Capacity:          3,200,631,791,616 [3.20 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            5cd2e4 d1c2300100
Local Time is:                      Sat Jun  5 12:49:20 2021 PDT
Firmware Updates (0x18):            4 Slots, no Reset required
Optional Admin Commands (0x000e):   Format Frmw_DL NS_Mngmt
Optional NVM Commands (0x0006):     Wr_Unc DS_Mngmt
Maximum Data Transfer Size:         32 Pages
Warning  Comp. Temp. Threshold:     70 Celsius
Critical Comp. Temp. Threshold:     80 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +    16.00W       -        -    0  0  0  0        0       0

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         2
 1 -    4096       0         0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        43 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    278,654,936 [142 TB]
Data Units Written:                 293,209,862 [150 TB]
Host Read Commands:                 2,149,630,889
Host Write Commands:                1,265,916,815
Controller Busy Time:               2,192
Power Cycles:                       6
Power On Hours:                     306
Unsafe Shutdowns:                   1
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    1838
Critical Comp. Temperature Time:    0

Error Information (NVMe Log 0x01, max 64 entries)
No Errors Logged
```
High warning temperature times on the U.2 from past plotting is concerning. I think I've alleviated the problem by adding a sixth fan to the case however.

**Comment by Grodahn** [comment]
@rkho

First time i had this issu i got the Stall everytime i run 2 plots in parallel on the machine. memtest64 showed a memory-problem, i swapped the ram and after this everything was fine.

Second stalling machine, memtest was okay. All SSD-Smart-Infos was okay, two. But on one SSD the wearleveling was at 10% left (nevertheless smart-status was fine). After changing the ssd, no more stalls.

**Comment by rkho** [comment]
@Grodahn Thanks for the additional details. Yes, I had suboptimal cooling at the time and have since added another fan which seems to have alleviated the issues I was experiencing with SSD temperatures.

Wanted to close the loop on this thread -- I replaced the RAM with a new pair off Newegg (exact same model) and that seems to have reoslved the issue; I'm back to full plotting capacity.
