### ISSUE TITLE
Receive Address wallet

### ISSUE THREAD

**Issue by MrPong76** [Chia-Network/chia-blockchain#6411]
1.How many Receive Address can be generated by one Private Key?
2. If I create a new receive address, will the old receive address still be mine?
3. If coins are transferred to my old address, will I still have coins?
3. If I change to a new wallet but my Farming Rewards Wallet is the same address, will I still have coins if I receive a reward?
Thanks for the answer

**Comment by q1k** [comment]
I had the same questions. Here's what I learned.
1. As many as you want.
2. All addresses will work.
3. Yes.
4. Not sure what you mean with this one. But, if you change the wallet, you will receive rewards to the new one.

**Comment by tomuGo** [comment]
> I had the same questions. Here's what I learned.
> 
> 1. As many as you want.
> 2. All addresses will work.
> 3. Yes.
> 4. Not sure what you mean with this one. But, if you change the wallet, you will receive rewards to the new one.

hi,does chia has any api to edit the address,i joined a pool,and i found the pool edit my address!!! so i want edit it automatic
