### ISSUE TITLE
[BUG] Can’t see the plots on gui even though it shows in cli

### ISSUE THREAD

**Issue by shourya080** [Chia-Network/chia-blockchain#6419]
I switched on my server today and started my plots on plot man but when i opened my gui it didn’t show any of my plots but it did show them in the hdds

i have my gui on windows and plot man on ubuntu, yesterday I could see my plots on gui and they were farming but today they disappeared 

![F0C4A2BC-A730-4547-8613-B45CCF9B868F](https://user-images.githubusercontent.com/85233235/120787180-b6cce600-c54c-11eb-9a3e-77a1a419efdc.jpeg)

**Comment by eliolonghi** [comment]
was it plotted in the same keys?
did you try to add plot directory?

**Comment by shourya080** [comment]
No, i had changed the keys
Is there any way for me to recover them ?

**Comment by eliolonghi** [comment]
I guess not. Mneumonics is like your identity. Can’t change. If there is a way to recover I don’t know
