### ISSUE TITLE
Can I just use 1.1.7.dev0 for my normal farming?  

### ISSUE THREAD

**Issue by martinlandcruiser** [Chia-Network/chia-blockchain#6420]
Hi there,
Follow the part of "To Update/Upgrade from previous version" in https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian, I always upgrade it to 1.1.7.dev0 （ the originally was 1.1.5 and I am out of patient for the sync issue of 1.1.5 and want to use the latest release 1.1.6) . 
Actually I have 2 questions:
First can I just use 1.1.7.dev0? Is this version OK be used for my normal farming?
Second if I have to use 1.1.6, how to retreat to 1.1.6 from 1.1.7.dev0?
thanks for the help and clarification. Have a good day.

**Comment by keliew** [comment]
Yes, it's fine. It's just a cosmetic 'bug' from github.
