### ISSUE TITLE
PLOTS MISSING

### ISSUE THREAD

**Issue by PatMateluna** [Chia-Network/chia-blockchain#6447]
I'm plotting in parallel with multiple SSD drives, when one finishes I re start that drive with a new parallel plot. that was working fine before, now I go thru the hole process of creating a new plot and when the plot is created it does not show on the local harvest plots. please advice

**Comment by ebi2000us** [comment]
me to
i have ploted one of my hdd and then when i rebot my pc and come back there is no ploted file i rechecked my directory of plot and bring some file and attempt me to delete .they have no use for me. but i spend many days for plot them , what i must do?

**Comment by staredgar87** [comment]
I have the same problem with my created plots. It does not detect them with the last 2 updates v 16 and 17.
