### ISSUE TITLE
stuck on different percentage[BUG]

### ISSUE THREAD

**Issue by strikeforce89** [Chia-Network/chia-blockchain#6448]
I start 4 or 5 or 6 parallel plotting(it doesn't matter how many i start) some of them finish and some of them stuck in different percentage for so long!!

my system:
win 10
cpu: 8700k
ram: 32gb 4000mhz
2 nvme Samsung 970 evo plus hardware raid

What can I do ?

**Comment by TarantulaENERGY** [comment]
Hey,

plotting is extremely memory sensitive and if your RAM is not 100% rockstable you will face that all the time. I know, proper stability testing is time consuming, but you better go for it. All your applications will benefit from it.

To check if this is the right guess I made, you can clock down your memory a bit, may 4000 > 3800mhz and start plotting like you did before. If this works fine, you should spend some time to get your 4000mhz run properly.

**Comment by strikeforce89** [comment]
Is it possible because of ram overheating?
I have 4 gskill trident z 4000mhz cl 19
How can I clock down memory?
