### ISSUE TITLE
Wallet Not Syncing Compilation [BUG]

### ISSUE THREAD

**Issue by boner-cmd** [Chia-Network/chia-blockchain#6452]
**Describe the bug**
Wallet doesn't sync correctly, either as an issue in itself or cascading to cause other issues.

**To Reproduce**
Use a variety of different Chia versions, Operating Systems, hardware configurations, and network setups, but encounter the same error across all of them without a clear resolution other than deleting the wallet files and praying it works the next time, sometimes even temporarily.

**Expected behavior**
Expect the wallet to connect and sync correctly when the node is also able to sync.

**Additional context**
Please make this a priority, since it keeps coming up and there's no consistent solution.

### open

- #6409 is a proposed workaround to wallet sync issues
- #6391 is a wallet sync issue
- #6384 includes wallet syncing issues as a component of "missing" XCH due to wallets being out of sync
- #6348 is a wallet sync issue
- #6320 is a wallet sync issue
- #6311 is a wallet sync issue
- #6254 is a wallet sync issue
- #6251 is a wallet sync issue
- #6206 is a question regarding issues with wallet sync
- #6161 is a wallet sync issue
- #6076 is a wallet sync issue
- #6031 is a wallet sync issue
- #5914 is a wallet sync issue
- #5904 is a wallet sync issue
- #5883 is a wallet sync issue
- #5868 is a wallet sync issue
- #5864 is a wallet sync issue
- #5840 is a wallet sync issue, albeit one wrapped in hate mail
- #5802 is a wallet sync issue
- #5795 is a wallet sync issue
- #5755 is a wallet sync issue
- #5749 is a wallet sync issue
- #5707 is a wallet sync issue
- #5687 is a wallet sync issue
- #5600 is a wallet sync issue
- #5413 is a wallet sync issue
- #5218 is a wallet sync issue
- #5154 is a wallet sync issue
- #5094 is a wallet sync issue
- #4965 is a wallet sync issue
- #4818 is a wallet sync issue
- #4792 is a pretty esoteric issue, but still related to wallet syncing
- #4768 is a wallet sync issue
- #4739 is a wallet sync issue
- #4751 is a wallet sync issue
- #4754 is a wallet sync issue
- #4732 is a wallet sync issue, albeit a very poorly reported one
- #4703 is a wallet sync issue
- #4693 is a wallet sync issue
- #4654 is a wallet sync issue and also has a guy promoting his country music in the comments. "Los Angeles" was okay. He needs a new producer though, some of those frequencies grate on the ears.
- #4607 is a wallet sync issue, and also someone ranting about the number of bug reports
- #4637 is a wallet sync issue
- #4467 is a wallet sync issue
- #4455 is a wallet sync issue
- #4468 is a wallet sync issue

### resolved but still open

- #5947 was a wallet sync issue
- #5788 was a wallet sync issue
- #5660 was a wallet sync issue
- #5221 was a wallet sync issue
- #4838 was a wallet sync issue

I'm on the 9th of 19 pages of open Issues containing the world "wallet" and having to read through them and all the comments so I hope I made my point

**Comment by willemwild** [comment]
I am running 2 independent systems on different networks and both having major wallet sync issues all of a sudden.  Neither will sync at all.  (bothe full nodes are fully synced)   Must be a serious bug.

**Comment by DocFraggle** [comment]
With 1.1.7 everything works again

**Comment by Orantz-vn** [comment]
It happened to me too, with version 1.1.7 it synchronizes but it takes a long time

**Comment by willemwild** [comment]
why could they not make a note here and just tell us that they were working on 1.1.7 fix.  I spend an entire day reloading and shuffling stuff, to try and get the wallet to sync.

**Comment by boner-cmd** [comment]
still waiting to see if it works
________________________________

**Comment by MrUFOHunter** [comment]
> With 1.1.7 everything works again

It certainly does not, not for everyone at least. I had no sync issues for my wallet what-so-ever until recently downloading the 1.1.7 version. I understand its a work in progress though so for me, I'm patient and calm about it, I'm sure plenty of people are working very hard to perfect it as much as humanly possible :)

**Comment by litterGuy** [comment]
It`s syncing again with 1.1.7 , but afraid be stucked like 1.1.6

**Comment by boner-cmd** [comment]
I am synced for now on 1.1.7
________________________________

**Comment by engine-off** [comment]
> > With 1.1.7 everything works again
> 
> It certainly does not, not for everyone at least. I had no sync issues for my wallet what-so-ever until recently downloading the 1.1.7 version. Ive had it attempting to sync for 72hrs now, full node no problem, wallet, problem. I understand its a work in progress though so for me, I'm patient and calm about it, I'm sure plenty of people are working very hard to perfect it as much as humanly possible :)

I have both wallets synced on my PC but trying to get 2nd wallet synced on RP4 running Ubuntu is impossible.  I've tried literally everything, it doesn't work.

**Comment by LouisLoudogTrottier** [comment]
Ubuntu-Server 20.04
pools.dev branch
Node is synced (and syncing) up to 291040 
wallet is stuck at 544 for over 16 hours.

**Comment by mariano54** [comment]
I am closing all related issues and consolidating discussion here: 
 https://github.com/Chia-Network/chia-blockchain/issues/6993

**Comment by boner-cmd** [comment]
Is there a reason you chose to consolidate wallet syncing issues on an issue with someone who has a working wallet on one machine but not another? That sounds like a "don't run multiple full nodes on a single network" thing, whereas iirc the examples here we're people who have trouble even getting a _single_ node to work.

**Comment by boner-cmd** [comment]
Unrelated to that and just curious but, any reason you didn't want to consolidate into the existing consolidated issue? You know, this one? 😅

**Comment by mariano54** [comment]
I hadn't seen this ticket until now, but that ticket is the most recent one so that is why I chose it (it's at the top).
It's most likely the same root cause, like a corrupt wallet DB.

Also, there are a few more wallet fixes coming with pooling, so hopefully some of these issues are fixed. Please understand that having so many tickets makes it very hard to keep track and to help people. Closing these tickets will make it much easier to help people.

**Comment by boner-cmd** [comment]
Sure, that's why I made _this_ ticket, to make it easier for devs to see how widespread this issue is over several consecutive versions. I guess "it's the newest ticket" is as good a reason as any.

**Comment by mariano54** [comment]
Thank you for the help, that was pretty helpful

**Comment by loststone2** [comment]
I never had any issues with 1.1.7 only been with 1.1.6 & 1.2.0 . Where Chia doesn't sync correctly.  I tried the instructions #6993 and still been having issues.

**Comment by ilyakooo0** [comment]
Still an issue

**Comment by LouisLoudogTrottier** [comment]
Stale? No... The only thing stale is the wallet syncing.
