### ISSUE TITLE
Harvester plotting half way and no respond[BUG]

### ISSUE THREAD

**Issue by mvchia** [Chia-Network/chia-blockchain#6458]
**Describe the bug** [solved]
I do total 15 plotting in the same time. queue list, each queue got 3 plots so total is 45 plots, each 5 queue list put in 2tb nvme and i had 3 nvme.
ram put 4096, threats use 2.

some queue list of 3 plots the fist and second plot it's finished well but 3th plot it stuck at 46% then later on no respond anymore.
some queue list of 3 plots the fist plot never finish stuck at 89% and later on no respond anymore.
some queue list of 3 plots the fist plot finished but 2nd plot never finish stuck at 87% and later on no respond anymore.

need some help here. what's the problem for this?

![stuck at plotting](https://user-images.githubusercontent.com/85393483/120888711-6e84f500-c62c-11eb-9c95-a79c93691aa2.JPG)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: win10 21H1
- CPU: Ryzen 9 5950x
- MOBO: Asrock x570 Taichi
- Ram: XPG D50 64gb 3600mhz
- NVME: Corsair MP600 pro
- HDD: Seagate Exos 16tb
- PSU: Asus Thor 1600w

**Additional context**

**Comment by caishubao** [comment]
我有一台电脑断电后 也这样子，数量P少点，可能是固态或者内存问题

**Comment by mvchia** [comment]
> 我有一台电脑断电后 也这样子，数量P少点，可能是固态或者内存问题

很可能是内存，我把XMP 3600mhz换成XMP 3200mhz，然后从15个plotting换成12个plotting，问题就没了。
