### ISSUE TITLE
[BUG] GUI is a piece of shit - please replace it ASAP

### ISSUE THREAD

**Issue by FSys77** [Chia-Network/chia-blockchain#6459]
Unfortunately, there is no way to put this more kindly: **The Chia GUI is a piece of shit**

It is to blame for so many problems with Chia. Even on Windows, Chia works reasonably reliably - if you use the command line.

With the GUI: problems upon problems! 
- Blockchain doesn't sync
- Wallet does not sync
- Close Chia via GUI, but it still continues to run in the background and causes strange states when restarted
- etc. etc.

Chia developers have pre-farmed 12 million coins! They should be able to invest a few thousand Dollars in a working GUI.

**Comment by zhangyadong88888** [comment]
哎~ 我的就断网3个小时，钱包就不同步了，以后是个项目 大家都不要参加了，精力和金钱投入的多，没有回报

**Comment by df1ech** [comment]
I totally agree, lost so many plots just in the edge of completing. It just stopped controlling the plotter or wallet and randomly lose sync. Also delete button trashes everything you got going on. The Linux version works completely fine though!
