### ISSUE TITLE
[BUG]CHIA项目真烂到家了，妈的，就断了3个小时，钱包就更新不了了，官方项目方去死把！

### ISSUE THREAD

**Issue by zhangyadong88888** [Chia-Network/chia-blockchain#6461]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by baizuchong-net** [comment]
等，时间会修复一切

**Comment by crh2021** [comment]
别在这里丢人现眼
