### ISSUE TITLE
[BUG] XCH Missing from Wallet, FULLY SYNCED, 51% Network atk? Or all XCH Stolen?

### ISSUE THREAD

**Issue by kingbbs990** [Chia-Network/chia-blockchain#6462]
Can someone please help. I've only used SWAR(https://github.com/swar/Swar-Chia-Plot-Manager) + PSChiaPlotter(https://github.com/MrPig91/PSChiaPlotter) <<< careful w/ these then if this was stolen.

Checked the wallet today, fully synced, blockchain also sycned
I should have about 5.6XCH on balance but saids 0. I've checked the chia explorer, it also says 0 Net.
I don't see any transactions going out, doesn't seems like its got stolen? Is this a bug or some sort? Any advice would greatly appreciated. Thanks! 

even though 1st screenshot and 3rd seems wallet at different height due to timing of the screenshots, but they are synced in my end.

Upon checking, https://www.chiaexplorer.com/blockchain/address/xch14y526hj72ew7fxfs2lmd8zev7r7gm2edyw8vfx6elfqdpptxunyq8hw89z
(i made the 6/5 transaction for testing)

It looks like it spent on block 384,133 to address:
https://www.chiaexplorer.com/blockchain/address/xch1cnm0qj7j9403yhs4wxqwqpk5cuku2n78lrtc3406nwlsmer2jrdsha9g7s

Question is, why would the wallet not show the transaction in both gui or CLI but somehow my coin got spent on the block 384,133? If my wallet or coins indeed got stolen, wouldnt I be able to see the actual transaction from a with to b with xcoins within the gui or cli txn history?   how was the coins taken from my account then if I have not initiated the transaction?

![image](https://user-images.githubusercontent.com/85395860/120890489-db11dc80-c5b7-11eb-84e7-c78e258733fa.png)

![image](https://user-images.githubusercontent.com/85395860/120890560-6be8b800-c5b8-11eb-8a06-ca3fb56db477.png)

![image](https://user-images.githubusercontent.com/85395860/120890672-2f698c00-c5b9-11eb-9407-e4d1ad042a31.png)

**Comment by verabeniel** [comment]
Hello, I have the same problem.
I had two chias until yesterday night, suddenly they disappear from my wallet and 
It looks like it spent on block 384,135 and in chia explorer says the two chias are spent; so I am very angry and don`t know what to do.
I am always farming solo, so I don´t understand nothing.
If you discover what is the problem please answer to me.
Good luck

**Comment by verabeniel** [comment]
This is my chia explorer link : 
https://www.chiaexplorer.com/blockchain/address/xch12x0ke62mery35jarwwnglkvvjsgg593sycuslpfsmnefw0avdtaqvu9gpn

**Comment by verabeniel** [comment]
How do you know the address to where your chias are sent?

**Comment by kingbbs990** [comment]
> This is my chia explorer link :
> https://www.chiaexplorer.com/blockchain/address/xch12x0ke62mery35jarwwnglkvvjsgg593sycuslpfsmnefw0avdtaqvu9gpn

It looks like you have the same issue. Please tell me what scripts you have installed in your PC? I got SWAR & PSCHIAPLOTTER both from original github links that I mentioned in my post.

It got spent on block 384,137 and to the same address:
![image](https://user-images.githubusercontent.com/85395860/120902260-234ef000-c5f4-11eb-9bb6-1bc842401ad4.png)

**Comment by verabeniel** [comment]
I have nothing of these scripts. I only have the Chia Blockchain official client and Claymore Ethereum mining for eth.

So I think your scripts aren`t the problem. 

I don`t know how we can solve this problem because it`s horrible what is happening.

Do you anything more about this?

**Comment by verabeniel** [comment]
A moderator says to me it´s probably that someone stole my keys and stole my chias but I dont`t understand that because I always farm solo and don`t have any script , only Official Chia Blockchain so if people can steal chias so easily, What kind of security and protection Chia developers give us? It`s shameful...

**Comment by verabeniel** [comment]
And I don`t have any outgoing transaction in my history , only the incomings, so It`s weird that someone steal the chias so easily and without marks.
The moderator also says to me that if i can find out the address of the person who steal the chias and track it, we must do it, but do you think is possible that we recover the chias if the address you send to me is the thief? What can we do?

**Comment by verabeniel** [comment]
Can we do anything with this information for recover the chias?

![Address of my chias now](https://user-images.githubusercontent.com/57694573/120905590-61c7c780-c653-11eb-96c8-181a70876b60.PNG)

**Comment by kingbbs990** [comment]
> And I don`t have any outgoing transaction in my history , only the incomings, so It`s weird that someone steal the chias so easily and without marks.
> The moderator also says to me that if i can find out the address of the person who steal the chias and track it, we must do it, but do you think is possible that we recover the chias if the address you send to me is the thief? What can we do?

it went to the same address: xch1cnm0qj7j9403yhs4wxqwqpk5cuku2n78lrtc3406nwlsmer2jrdsha9g7s
https://www.chiaexplorer.com/blockchain/address/xch1cnm0qj7j9403yhs4wxqwqpk5cuku2n78lrtc3406nwlsmer2jrdsha9g7s

whats funny is you and I are in the same block at the same time if it was stolen... without any transaction history, i dont think its stolen, something is wrong with the network randomly taking/spending coins from our wallets.. otherwise it would show the transactions in our wallets

**Comment by verabeniel** [comment]
I think same , but do you think they will solve the problem and restore our chias?

**Comment by kingbbs990** [comment]
no idea, wait for the dev to respond, technically hpool seem to have alrdy 50% network space if not more anyway and that they moved all 21m of their premined reserves within last 48 hrs seems something is going on behind the curtain

**Comment by verabeniel** [comment]
Do you think the developer could answer to this conversation?
Or do you have any other way for contact him? like an email or something like that.

**Comment by verabeniel** [comment]
In the other support conversation I have, they have just answered me this : 

There accident is a transaction history. If you look at the block in which the coins were transferred out, you will see a transaction call to transfer the coins from your respective wallets to another wallet. The fact they both happened at the exact same time would seem to reinforce my belief that it was a deliberate action taken by someone with keys to multiple wallets who was trying to “sweep” them.
It’s possible that you won’t see a transaction on your side because it’s likely when they used your keys to load the wallet on their side that they generated a new wallet public address that was tied to the same base wallet key, and initiated the transfer from there.
I can assure you that the core fundamental technology in the Chia Blockchain is the same general concept and technology used in by various blockchains over the last decade, and it’s highly improbable there is a bug allowing non-transactional removal of coins from a wallet. All evidence so far indicates that this was clearly a case of compromised keys being used by a bad actor, if you did indeed have no agency over this transaction.
It’s possible for keys to be compromised in a multitude of way even if you are using the official software, countless malware and viruses completely unrelated to chia will deep dive a users system and look for anything remotely resembling a password or security key or keyphrase that is sent back home to a central server and applied to every known platform until a valid use for it is found.

**Comment by kingbbs990** [comment]
> In the other support conversation I have, they have just answered me this :
> 
> There accident is a transaction history. If you look at the block in which the coins were transferred out, you will see a transaction call to transfer the coins from your respective wallets to another wallet. The fact they both happened at the exact same time would seem to reinforce my belief that it was a deliberate action taken by someone with keys to multiple wallets who was trying to “sweep” them.
> It’s possible that you won’t see a transaction on your side because it’s likely when they used your keys to load the wallet on their side that they generated a new wallet public address that was tied to the same base wallet key, and initiated the transfer from there.
> I can assure you that the core fundamental technology in the Chia Blockchain is the same general concept and technology used in by various blockchains over the last decade, and it’s highly improbable there is a bug allowing non-transactional removal of coins from a wallet. All evidence so far indicates that this was clearly a case of compromised keys being used by a bad actor, if you did indeed have no agency over this transaction.
> It’s possible for keys to be compromised in a multitude of way even if you are using the official software, countless malware and viruses completely unrelated to chia will deep dive a users system and look for anything remotely resembling a password or security key or keyphrase that is sent back home to a central server and applied to every known platform until a valid use for it is found.

that is not true, in fact I have tested sending transactions with generating new public key with same base wallet, regardless of what new public key it is, the gui / cli will still show the transactions as long as base wallet is same. So if this was a comprised wallet, and he restore with new pub key in his end then transfer, it will not show in chiaexplorer but it will definitely show in my wallet history. I suspected this and did tested this myself.

**Comment by verabeniel** [comment]
I have just answer them in Support by resending the answer you gave me, saying that you tested all and its not true what they say.
I hope they could help us it seems very difficult because of the answer they gave me.

**Comment by kingbbs990** [comment]
https://www.reddit.com/r/chia/comments/n90s9q/virus_warnings_after_installing_chia_114/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

after checking my chrome downloads and the addresses, it appear to be similar issue here where 1.14 was a rar downloaded. O well, official github downloads a malicious version of the client, those genius then locked the wiki after but now thought of it before. can conclude this got stolen, not gonna waste more time checking. just keep farming
