### ISSUE TITLE
[BUG]china 的官方项目方，去吃屎吧，去死吧，昨天钱包同步还好好的，今天就不行，去死吧！

### ISSUE THREAD

**Issue by zhangyadong88888** [Chia-Network/chia-blockchain#6463]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by pe82643** [comment]
别生气。。。注意我们中国人的影响嘛。。。1.1.5的时候的确经常断，不过我更新了1.1.6之后就很好  没有断过
