### ISSUE TITLE
My Chias coin disappeared from my wallet after formatted my PC 

### ISSUE THREAD

**Issue by byturra** [Chia-Network/chia-blockchain#6474]
After formatted my PC and installed the Chia App and logged in with my account, the chia I had disappeared.
![2021-06-05_163955](https://user-images.githubusercontent.com/26169024/120897195-d0d5f980-c61c-11eb-967a-ae77542a35d7.png)

**Comment by byturra** [comment]
![2021-06-05_164430](https://user-images.githubusercontent.com/26169024/120897322-64a7c580-c61d-11eb-88c5-db1f2c3d1cfb.png)

**Comment by FSys77** [comment]
Wait til your wallet is synced again then your coins will show up again.

P.S.
Good luck with syncing your wallet. Many users spend days and weeks to do this - without success.

**Comment by Hellfall1** [comment]
You need to be on the latest release to get a full sync. Are you on 1.1.7?

(Windows version just got fixed some hours ago. They released 1.1.7. for linux, but windows was still 1.1.6 but stated 1.1.7 donwload. So much incompetence, *sigh*)

**Comment by byturra** [comment]
After update to 1.1.7
![2021-06-07_072712](https://user-images.githubusercontent.com/26169024/120969272-de48cc00-c761-11eb-9d9d-7b980988490f.png)

**Comment by byturra** [comment]
Can someone solve the problem, or is this chia a bullshit?
