### ISSUE TITLE
[BUG]: Transation withdraw.

### ISSUE THREAD

**Issue by KIMB0212** [Chia-Network/chia-blockchain#6481]
I tried to create a transaction by entering the destination address and the total, but as a commission cost by putting 0 or 0.001 or 0.001 or 0.002 or 0.002 a popup opens that tells me to enter a valid value and does not let me go forward. I can't transfer .....

**Comment by gromran** [comment]
Try comma

**Comment by KIMB0212** [comment]
Hi, but to create the transaction I need to enter the address / hash Puzzle.
My question is: what would Puzzle hash be where I find it?
Thanks to those who answer me ....

**Comment by gromran** [comment]
> Puzzle hash

https://www.chiaexplorer.com/tools/address-puzzlehash-converter

**Comment by KIMB0212** [comment]
Thank you very much, where to try but at the moment I can't because I have plots in progress ... I'll let you know ... why I should close and reopen another wallet ....

**Comment by KIMB0212** [comment]
Ok, I managed to make the transaction, it works with a period not a comma (0.12345....)
