### ISSUE TITLE
not synced on chai full node

### ISSUE THREAD

**Issue by lcmrose** [Chia-Network/chia-blockchain#6489]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by DavideFranceschin** [comment]
I have a wallet connection problem after a reload of page.
![BUG connection wallet](https://user-images.githubusercontent.com/85416578/120905749-82dce800-c654-11eb-9dd1-4d533971d2cd.jpg)
It has been like this for 1 day and even trying to reinstall Chia 1.1.6 program you don't want to connect.
What can I do about it?

**Comment by StevenZhengTaiwan** [comment]
you may try to delete  the file in path C:\Users\username\.chia\mainnet\db
or change network

**Comment by MarcusB2105** [comment]
The ChiaSetup 1.1.7 is now available on the official chia.net download section. This should solve the problem.

**Comment by DavideFranceschin** [comment]
Yes, it is now solved! Thanks
