### ISSUE TITLE
[BUG]1.1.7 Why is there no Windows version

### ISSUE THREAD

**Issue by jlfsccm** [Chia-Network/chia-blockchain#6493]
1.1.7 Why is there no Windows version

**Comment by tryer50** [comment]
I ask the same. With the days that I have not been able to synchronize the wallet in any of the PCs: S: S

**Comment by MarcusB2105** [comment]
I just tried to download chia 1.1.7 for windows but the downloaded file from 06.06.2021 is called chia 1.1.6 and when I executed it, it just started my already installed chia verion 1.1.6. I checked github if there are new files available but the last change is alread 3 days ago and not a new version of chia? (see attached screenshots)
![Chia 1 1 7](https://user-images.githubusercontent.com/50211324/120910791-28f31700-c682-11eb-8d0b-bac753c673e9.PNG)
![Chia 1 1 7-2](https://user-images.githubusercontent.com/50211324/120910792-298bad80-c682-11eb-8e10-cc163fe375bb.PNG)
![Chia 1 1 7-3](https://user-images.githubusercontent.com/50211324/120910793-298bad80-c682-11eb-99d7-d983f5504d4d.PNG)

**Comment by jlfsccm** [comment]
需要自己编译吧  我编译后 无法执行

**Comment by MarcusB2105** [comment]
I just found a release of 1.1.7 on github: https://github.com/Chia-Network/chia-blockchain/releases/tag/1.1.7

Can I just download the Chia.exe and execute it?

**Comment by tomuGo** [comment]
ffmpeg.dll can not found ,when install chia.1.1.7.exe

**Comment by abueide** [comment]
I would recommend not downloading this release yet. It looks incredibly sketchy. It might be an attack on the build system or github repo. Not to mention it has a Chia.exe when normally its a chia-setup file. I think justin's account may have gotten hacked especially since its late at night and he normally doesn't create the releases.

**Comment by tryer50** [comment]
> Recomendaría no descargar esta versión todavía. Parece increíblemente incompleto. Podría ser un ataque al sistema de compilación o al repositorio de github. Sin mencionar que tiene un archivo Chia.exe cuando normalmente es un archivo de configuración de chia. Creo que la cuenta de Justin puede haber sido pirateada, especialmente porque es tarde en la noche y normalmente no crea los lanzamientos.

notice the same, I was looking at those details

**Comment by leewi9** [comment]
omg I just download it and run it, would I lost all my XCH???

**Comment by MarcusB2105** [comment]
Hey justinengland attached the ChiaSetup1.1.7 and I risked it and it is running. Node and Wallet are synced and I haven´t got any errors on my default.log so far. I will get back in a cpl minutes if my computer hasn´t buned down by then. :-)

**Comment by abueide** [comment]
@leewi9 transfer all your funds to a different wallet on a machine not connected to the internet asap.

**Comment by tryer50** [comment]
the high hours is what attracts the most attention

**Comment by abueide** [comment]
please upvote this post on reddit and downvote any 1.1.7 announcement posts until we get confirmation on keybase

https://www.reddit.com/r/chia/comments/ntcn37/psa_do_not_download_the_117_release/

**Comment by kennylbj** [comment]
https://github.com/Chia-Network/chia-blockchain/commit/5882ba69cf27dbff515d62a1c801dc1aa3962375 is the major change in 1.1.7. It does not seem like an attack IMO.

**Comment by MarcusB2105** [comment]
So far it looks like it is running fine. At least everything is synnced and I do not get any errors anymore.

But you guys made me nervouse...well since I don´t own any XCHs it might be worth the risk.

**Comment by abueide** [comment]
my post on reddit voicing why it was sketchy got deleted. take from that what you will.

**Comment by MarcusB2105** [comment]
> 
> 
> my post on reddit voicing why it was sketchy got deleted. take from that what you will.

I hope this means that I haven´t got compromised. But thx for the effort.

**Comment by MarcusB2105** [comment]
Just found this: https://thechiaplot.net/2021/06/05/chia-1-1-7-released/

**Comment by MarcusB2105** [comment]
On the official chia-website it says 1.1.7 is released but when you follow the downloadlink and download the windows installation file it is still the chasetup 1.1.6. But when you follow the release notes and follow further the notes to Chia Blockchain 1.1.7 you end up at the githup page for release 1.1.7 that i posted above. So it is highle doubtable that someone hacked the github useraccount and the main website...
![Chia 1 1 7-5](https://user-images.githubusercontent.com/50211324/120912112-d23f0a80-c68c-11eb-8470-ee3f3a4784be.PNG)
![Chia 1 1 7-4](https://user-images.githubusercontent.com/50211324/120912114-d2d7a100-c68c-11eb-8482-a78965ada144.PNG)

**Comment by tryer50** [comment]
Hours more or hours less does not change me at all, I prefer to wait for the announcement in keybase

**Comment by MarcusB2105** [comment]
The ChiaSetup 1.1.7 is now available on the official chia.net download section.

**Comment by Dcrownn** [comment]
Fortunately, I didn't take any action. I was just looking at how everyone took action. I also had a block that didn't arrive today. I don't know why
