### ISSUE TITLE
[BUG] - Following Ubuntu Install/Update procedure remains on version 1.1.6

### ISSUE THREAD

**Issue by laszlojanosek** [Chia-Network/chia-blockchain#6497]
Despite the update is released and on GitHub the latest chia-blockchain is 1.1.7, when following the official installation steps it will clone version 1.1.6. chia version will also show chia is 1.1.6

I could clone 1.1.7 by the following command:
git clone https://github.com/Chia-Network/chia-blockchain.git -b 1.1.7 --recurse-submodule
and then following the rest of the procedure the result is chia shows version 1.1.7

**To Reproduce**
Follow Chia installation procedure for Ubuntu (potentially for other distros as well). I tested it by updating the previously installed/used folder and deleting the previous folder and starting installation from scratch.

**Expected behavior**
Chia clones latest 1.1.7 version.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 
- OS Version/Flavor: Ubuntu Desktop 20.04
- CPU: Intel i7 11700

**Additional context**
When running modified git clone command the following output received:

git clone https://github.com/Chia-Network/chia-blockchain.git -b 1.1.7 --recurse-submodules
Cloning into 'chia-blockchain'...
remote: Enumerating objects: 47252, done.
remote: Counting objects: 100% (3903/3903), done.
remote: Compressing objects: 100% (1424/1424), done.
remote: Total 47252 (delta 2945), reused 3280 (delta 2463), pack-reused 43349
Receiving objects: 100% (47252/47252), 21.31 MiB | 23.33 MiB/s, done.
Resolving deltas: 100% (36249/36249), done.
Note: switching to 'b075e5bb8cfaf7d866a43201d6cc00646411e7d5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Submodule 'chia-blockchain-gui' (https://github.com/Chia-Network/chia-blockchain-gui.git) registered for path 'chia-blockchain-gui'
Submodule 'mozilla-ca' (https://github.com/Chia-Network/mozilla-ca.git) registered for path 'mozilla-ca'
Cloning into '/home/...../chia-blockchain/chia-blockchain-gui'...

**Comment by txr13** [comment]
Also affected by this.

**Comment by Liberticide** [comment]
me too

**Comment by Liberticide** [comment]
personally I did this:
git checkout 1.1.7
git reset --hard FETCH_HEAD

and I ended up in version 1.1.8.dev0

**Comment by txr13** [comment]
Doing a `git checkout 1.1.7` puts me into a detached HEAD state, because 1.1.7 is a tag and not a branch.

The command sequence below did switch me into the correct branch and brought me up to date:
`git checkout batch_sql_1.1.6`
`git fetch`
`git reset --hard FETCH_HEAD`

The fetch between checking out the correct branch and resetting the tree seems to be important for making sure FETCH_HEAD is set correctly.

**Comment by MarcusB2105** [comment]
> 
> 
> Doing a `git checkout 1.1.7` puts me into a detached HEAD state, because 1.1.7 is a tag and not a branch.
> 
> The command sequence below did switch me into the correct branch and brought me up to date:
> `git checkout batch_sql_1.1.6`
> `git fetch`
> `git reset --hard FETCH_HEAD`
> 
> The fetch between checking out the correct branch and resetting the tree seems to be important for making sure FETCH_HEAD is set correctly.
> 
> Of course, updating the `latest` branch to point to 1.1.7 would also be nice, but in the meantime... :)

That worked for me aswell. But for all the newbies out there (like me): after you done the above you have to run 'sh install.sh' again. Now you have to activate venv again '. ./acitvate' and can check if it is correct with 'chia version'. It should show '1.1.7'

**Comment by katmai** [comment]
does it matter if the farmer is on 1.1.8-dev ? will it break anything or?

**Comment by Liberticide** [comment]
> 
> 
> does it matter if the farmer is on 1.1.8-dev ? will it break anything or?

No no, it's ok.

**Comment by DavidJ68** [comment]
> > does it matter if the farmer is on 1.1.8-dev ? will it break anything or?
> 
> No no, it's ok.

thanks I will leave as 1.1.8.dev0
