### ISSUE TITLE
[BUG] 1.1.7 UPnP doesn't work Win 10 x64

### ISSUE THREAD

**Issue by sergree** [Chia-Network/chia-blockchain#6504]
**Describe the bug**
It seems UPnP doesn't work after 1.1.7 update (Windows 10 x64).
I have `enable_upnp: true` in `config.yaml` 
But i don't see successful UPnP mapping in my router console.
Also, I now have several times fewer Сonnections in Full Node tab.

**To Reproduce**
Run 1.1.7 on Windows 10 x64.

**Comment by SirIain** [comment]
Just tried to update to 1.1.7 and it wont work. 
Saying blocked because it could harm your device??
Any ideas

**Comment by yeeezy2k** [comment]
I'm having the same issue. It used to automatically open 8444 ports for me with upnp enabled. Now with 1.1.7 nothing has changed with my config but I'm not seeing the same port configuration in my router either. Went from having max peers now I cant break 10.
