### ISSUE TITLE
[BUG]why "delete" button is inactive

### ISSUE THREAD

**Issue by Landers1037** [Chia-Network/chia-blockchain#6509]
"delete" button is inactive
![image](https://user-images.githubusercontent.com/32225052/120920042-6641be00-c6ef-11eb-896a-100bb5755d43.png)

reboot or update chia-gui to 1.17 is not working!

**Comment by sholinaty** [comment]
the Delete button has been disabled for several versions now.

**Comment by df1ech** [comment]
It got disabled in 1.1.6 before it was there but trashing the GUI manager when used.
