### ISSUE TITLE
All plots suddenly disappeared

### ISSUE THREAD

**Issue by MEConnectify** [Chia-Network/chia-blockchain#6518]
I maxed 2 8Tb hard drives with plots, I turned off my PC to add another hard drive, when I turned it back on and turned the Chia GUI app on my plots weren't there, I tried reimporting them, it would find them and list them all under "Not Found", I even unplugged the hard drive i put in but they still won't show back

**Comment by Muasin94** [comment]
same problem here. Update to vers. 1.1.7 and now my plots are 'Not found'.
I have used 'plots check' for see if everthing work and all the plots are valid.

**Comment by MEConnectify** [comment]
Yep same thing, checked all the plots using "chia plots check" and everything is valid

**Comment by Leonid-l** [comment]
Close App del .\chia folder and then start App

**Comment by Muasin94** [comment]
> Close App del .\chia folder and then start App

done, don't work.

**Comment by Hellfall1** [comment]
Did you re-add the paths to the plots?

**Comment by MEConnectify** [comment]
Yeah, did remove & readd them, does not work

**Comment by Muasin94** [comment]
Guys, the problem solved itself.
Just wait (I waited 5 hours) and the plots will go back to farm on their own.

**Comment by Muasin94** [comment]
if you have coins, do not delete the \ .chia folder.
inside is the node with your wallet and if you have coins they disappear from the wallet until the next node synchronization (it could take days).

**Comment by killerfrost22** [comment]
I have the same problem as well;(

**Comment by Muasin94** [comment]
> I have the same problem as well;(

Just wait (I waited 5 hours) and the plots will go back to farm on their own.

**Comment by Lazymin3r** [comment]
@Muasin94 is this after you installed Chia Blockchain 1.1.7?

**Comment by Muasin94** [comment]
> @Muasin94 is this after you installed Chia Blockchain 1.1.7?

no, it happened after windows update. (I still had Chia 1.1.6)
I restarted the pc and the plots had stopped farming, I installed the new version of Chia (1.1.7) and the plots did not farm.
I turned 1000 posts on github looking for a solution and read that one user solved it by just waiting.
I tried reinstalling the certificates as the problem was only on the second harvester and that didn't work either (last time reinstalling the certificates had worked).
In the end I decided to wait and after 5 hours they went back to farm alone. 😅

**Comment by Lazymin3r** [comment]
> > @Muasin94 is this after you installed Chia Blockchain 1.1.7?
> 
> no, it happened after windows update. (I still had Chia 1.1.6)
> I restarted the pc and the plots had stopped farming, I installed the new version of Chia (1.1.7) and the plots did not farm.
> I turned 1000 posts on github looking for a solution and read that one user solved it by just waiting.
> I tried reinstalling the certificates as the problem was only on the second harvester and that didn't work either (last time reinstalling the certificates had worked).
> In the end I decided to wait and after 5 hours they went back to farm alone. 😅

Okay, well I am glad that they became available for farming again. I was a little worried there, I noticed even new plots were not available to the farm. I will give it some time and hope for the best.

**Comment by markimusprime** [comment]
same, windows said i had updates avail so i figured before i reset i would upgrade to 1.1.7  did that, reset windows with the update reset came back all plots are gone.  Deleted all folder pointers and re-added them still gone, downgraded to 1.1.6 still gone, upgraded to 1.1.7 still gone
nice upgrade

**Comment by Muasin94** [comment]
> > > @Muasin94 is this after you installed Chia Blockchain 1.1.7?
> > 
> > 
> > no, it happened after windows update. (I still had Chia 1.1.6)
> > I restarted the pc and the plots had stopped farming, I installed the new version of Chia (1.1.7) and the plots did not farm.
> > I turned 1000 posts on github looking for a solution and read that one user solved it by just waiting.
> > I tried reinstalling the certificates as the problem was only on the second harvester and that didn't work either (last time reinstalling the certificates had worked).
> > In the end I decided to wait and after 5 hours they went back to farm alone. 😅
> 
> Okay, well I am glad that they became available for farming again. I was a little worried there, I noticed even new plots were not available to the farm. I will give it some time and hope for the best.

don't worry, let the GUI create new plots .. the old plots will be added by themselves in a couple of hours

**Comment by markimusprime** [comment]
> > > > @Muasin94 is this after you installed Chia Blockchain 1.1.7?
> > > 
> > > 
> > > no, it happened after windows update. (I still had Chia 1.1.6)
> > > I restarted the pc and the plots had stopped farming, I installed the new version of Chia (1.1.7) and the plots did not farm.
> > > I turned 1000 posts on github looking for a solution and read that one user solved it by just waiting.
> > > I tried reinstalling the certificates as the problem was only on the second harvester and that didn't work either (last time reinstalling the certificates had worked).
> > > In the end I decided to wait and after 5 hours they went back to farm alone. 😅
> > 
> > 
> > Okay, well I am glad that they became available for farming again. I was a little worried there, I noticed even new plots were not available to the farm. I will give it some time and hope for the best.
> 
> don't worry, let the GUI create new plots .. the old plots will be added by themselves in a couple of hours

i'll give it a few hours and see, this is stupid though, I'm potentially missing out on rewards while this thing catches up to some invisible process.

**Comment by Muasin94** [comment]
> same, windows said i had updates avail so i figured before i reset i would upgrade to 1.1.7 did that, reset windows with the update reset came back all plots are gone. Deleted all folder pointers and re-added them still gone, downgraded to 1.1.6 still gone, upgraded to 1.1.7 still gone
> nice upgrade

I think this time it was the Windows update that created some problem with Chia.
The Gui obviously is not at the top of perfection but I understand that it is a completely new system and some bugs are normal.
Install Chia 1.1.7, add the folder with the plots and leave the Gui open (create new plots in the meantime).
In a few hours the problem will resolve itself.

**Comment by Muasin94** [comment]
> > > > > @ Muasin94 è questo dopo aver installato Chia Blockchain 1.1.7?
> > > > 
> > > > 
> > > > no, è successo dopo l'aggiornamento di Windows. (avevo ancora Chia 1.1.6) 
> > > > Ho riavviato il pc e le parcelle avevano smesso di coltivare, ho installato la nuova versione di Chia (1.1.7) e le parcelle non hanno funzionato. 
> > > > Ho girato 1000 post su github alla ricerca di una soluzione e ho letto che un utente l'ha risolto semplicemente aspettando. 
> > > > Ho provato a reinstallare i certificati poiché il problema era solo sulla seconda mietitrice e nemmeno questo ha funzionato (l'ultima volta che la reinstallazione dei certificati aveva funzionato). 
> > > > Alla fine ho deciso di aspettare e dopo 5 ore sono tornati all'allevamento da soli.😅
> > > 
> > > 
> > > Ok, sono contento che siano tornati disponibili per l'agricoltura. Ero un po' preoccupato lì, ho notato che anche i nuovi appezzamenti non erano disponibili per l'agriturismo. Gli darò un po' di tempo e spero per il meglio.
> > 
> > 
> > non preoccuparti, lascia che la GUI crei nuovi grafici .. i vecchi grafici verranno aggiunti da soli in un paio d'ore
> 
> gli darò qualche ora e vedrò, questo è stupido però, mi sto perdendo potenzialmente le ricompense mentre questa cosa raggiunge un processo invisibile.

honestly i have more than 500 plots and in 3 months i never got anything, i don't think 6 hours makes a difference 😂😂

**Comment by Muasin94** [comment]
> > > > > @Muasin94 is this after you installed Chia Blockchain 1.1.7?
> > > > 
> > > > 
> > > > no, it happened after windows update. (I still had Chia 1.1.6)
> > > > I restarted the pc and the plots had stopped farming, I installed the new version of Chia (1.1.7) and the plots did not farm.
> > > > I turned 1000 posts on github looking for a solution and read that one user solved it by just waiting.
> > > > I tried reinstalling the certificates as the problem was only on the second harvester and that didn't work either (last time reinstalling the certificates had worked).
> > > > In the end I decided to wait and after 5 hours they went back to farm alone. 😅
> > > 
> > > 
> > > Okay, well I am glad that they became available for farming again. I was a little worried there, I noticed even new plots were not available to the farm. I will give it some time and hope for the best.
> > 
> > 
> > don't worry, let the GUI create new plots .. the old plots will be added by themselves in a couple of hours
> 
> i'll give it a few hours and see, this is stupid though, I'm potentially missing out on rewards while this thing catches up to some invisible process.

honestly i have more than 500 plots and in 3 months i never got anything, i don't think 6 hours makes a difference 😂😂

**Comment by MEConnectify** [comment]
Been waiting for 8+ hours, nothing showed back up

**Comment by MEConnectify** [comment]
Result of the "chia plots check"

2021-06-06T17:57:19.846  chia.plotting.check_plots        : INFO     Summary
2021-06-06T17:57:19.848  chia.plotting.check_plots        : INFO     Found 143 valid plots, total size 14.15465 TiB
2021-06-06T17:57:19.849  chia.plotting.check_plots        : INFO     143 plots of size 32

**Comment by Muasin94** [comment]
> Result of the "chia plots check"
> 
> 
> 
> 2021-06-06T17:57:19.846  chia.plotting.check_plots        : INFO     Summary
> 
> 2021-06-06T17:57:19.848  chia.plotting.check_plots        : INFO     Found 143 valid plots, total size 14.15465 TiB
> 
> 2021-06-06T17:57:19.849  chia.plotting.check_plots        : INFO     143 plots of size 32
> 
> 
> 
> To be clear, my plots do show up in the GUI but they show up here
> 
> 
> 
> ![Untitled](https://user-images.githubusercontent.com/36010056/120939955-45935b80-c723-11eb-9a69-320e5aa35d0e.png)
> 
> 

is the problem on the main machine or harvester?

**Comment by markimusprime** [comment]
been waiting several hours, still the GUI shows none of my 900 plots.

**Comment by Muasin94** [comment]
> been waiting several hours, still the GUI shows none of my 900 plots.

I don't know guys, my problem occurred on the second machine and besides copying the certificates from the main machine I waited 5 hours and the problem solved itself.
Take a look at the debug.log file and check for further problems.

**Comment by Muasin94** [comment]
> been waiting several hours, still the GUI shows none of my 900 plots.

ps: I don't know how it works, but I know that on Keybase you can ask the developers questions directly, maybe they can help you.

**Comment by MEConnectify** [comment]
> > Result of the "chia plots check"
> > 2021-06-06T17:57:19.846  chia.plotting.check_plots        : INFO     Summary
> > 2021-06-06T17:57:19.848  chia.plotting.check_plots        : INFO     Found 143 valid plots, total size 14.15465 TiB
> > 2021-06-06T17:57:19.849  chia.plotting.check_plots        : INFO     143 plots of size 32
> > To be clear, my plots do show up in the GUI but they show up here
> > ![Untitled](https://user-images.githubusercontent.com/36010056/120939955-45935b80-c723-11eb-9a69-320e5aa35d0e.png)
> 
> is the problem on the main machine or harvester?

Using 1 machine for everything

**Comment by markimusprime** [comment]
> > been waiting several hours, still the GUI shows none of my 900 plots.
> 
> ps: I don't know how it works, but I know that on Keybase you can ask the developers questions directly, maybe they can help you.

I can't get keybase to work.  Thanks for trying to help but I'm giving up.  If I ever get this working again I'm never updating chia again.

**Comment by Muasin94** [comment]
if I find some useful information around I write to you, I'm sorry that you have not been able to solve the problem.

**Comment by markimusprime** [comment]
> if I find some useful information around I write to you, I'm sorry that you have not been able to solve the problem.

So mine is working now.  I tried plotting some new plots into the directories where my existing .plot files were and that didn't work.  I uninstalled and reinstalled both 1.1.6 and 1.1.7 multiple times that didn't work either. I deleted my second private key that i had in case it was messing up my main private key that didn't work, I moved everything in my .chia folder to a temp folder then uninstalled chia app using windows uninstaller then redownloaded 1.1.6 and installed it, I then moved my large sqlite db file into the new folder so i didin't have to wait for a full sync and then started the app and it found my plots this time.  What a headache.  Not going to update to any new releases for the chia network unless it's mandatory, what a fail on your part.

**Comment by Muasin94** [comment]
> > if I find some useful information around I write to you, I'm sorry that you have not been able to solve the problem.
> 
> So mine is working now. I tried plotting some new plots into the directories where my existing .plot files were and that didn't work. I uninstalled and reinstalled both 1.1.6 and 1.1.7 multiple times that didn't work either. I deleted my second private key that i had in case it was messing up my main private key that didn't work, I moved everything in my .chia folder to a temp folder then uninstalled chia app using windows uninstaller then redownloaded 1.1.6 and installed it, I then moved my large sqlite db file into the new folder so i didin't have to wait for a full sync and then started the app and it found my plots this time. What a headache. Not going to update to any new releases for the chia network unless it's mandatory, what a fail on your part.

I did not understand the part where you explain your private keys .. do you create plots with two different private keys? however the Chia 1.1.7 update serves to solve a SQL problem that prevented the wallet from being online.
If your wallet works with version 1.1.6 then it's perfect!

**Comment by MEConnectify** [comment]
I put some plots in the queue yesterday and went to sleep, just woke up to find out that even new plots show up under the "Not Found" category, what's really surprising is that the new plots are in a separate hard-drive, completely new directory

**Comment by markimusprime** [comment]
> > > if I find some useful information around I write to you, I'm sorry that you have not been able to solve the problem.
> > 
> > 
> > So mine is working now. I tried plotting some new plots into the directories where my existing .plot files were and that didn't work. I uninstalled and reinstalled both 1.1.6 and 1.1.7 multiple times that didn't work either. I deleted my second private key that i had in case it was messing up my main private key that didn't work, I moved everything in my .chia folder to a temp folder then uninstalled chia app using windows uninstaller then redownloaded 1.1.6 and installed it, I then moved my large sqlite db file into the new folder so i didin't have to wait for a full sync and then started the app and it found my plots this time. What a headache. Not going to update to any new releases for the chia network unless it's mandatory, what a fail on your part.
> 
> I did not understand the part where you explain your private keys .. do you create plots with two different private keys? however the Chia 1.1.7 update serves to solve a SQL problem that prevented the wallet from being online.
> If your wallet works with version 1.1.6 then it's perfect!

I have a private key that i use as my main key for plotting and pooling with core pool but i made a second private key to have a wallet address that I will use for the official pool plots that I make when that is released and also will use that address as the payout for my core pool payouts.  Doesn't matter though, that second wallet would never sync but I didn't care that much and it ended up not mattering when I deleted it off of my gui anyways.  Only thing that fixed my issue was what i mentioned above

**Comment by markimusprime** [comment]
> I put some plots in the queue yesterday and went to sleep, just woke up to find out that even new plots show up under the "Not Found" category, what's really surprising is that the new plots are in a separate hard-drive, completely new directory

yes when mine was broken same thing happened to me, even new plots would immediately go to "not found plots"  only thing that fixed it was what I mentioned above you should try that.

**Comment by Muasin94** [comment]
> > > > if I find some useful information around I write to you, I'm sorry that you have not been able to solve the problem.
> > > 
> > > 
> > > So mine is working now. I tried plotting some new plots into the directories where my existing .plot files were and that didn't work. I uninstalled and reinstalled both 1.1.6 and 1.1.7 multiple times that didn't work either. I deleted my second private key that i had in case it was messing up my main private key that didn't work, I moved everything in my .chia folder to a temp folder then uninstalled chia app using windows uninstaller then redownloaded 1.1.6 and installed it, I then moved my large sqlite db file into the new folder so i didin't have to wait for a full sync and then started the app and it found my plots this time. What a headache. Not going to update to any new releases for the chia network unless it's mandatory, what a fail on your part.
> > 
> > 
> > I did not understand the part where you explain your private keys .. do you create plots with two different private keys? however the Chia 1.1.7 update serves to solve a SQL problem that prevented the wallet from being online.
> > If your wallet works with version 1.1.6 then it's perfect!
> 
> I have a private key that i use as my main key for plotting and pooling with core pool but i made a second private key to have a wallet address that I will use for the official pool plots that I make when that is released and also will use that address as the payout for my core pool payouts. Doesn't matter though, that second wallet would never sync but I didn't care that much and it ended up not mattering when I deleted it off of my gui anyways. Only thing that fixed my issue was what i mentioned above

your plots would never have worked with any other private key than the one you created the plots with.
Only when the 'portable plots' come out will it be possible to transfer them from one wallet to another.
I have always farmed and plotted with a single key in several machines.
I think, from how you described what you did, the problem is that you gave your plots to a second key that did not create them and therefore would never find them.

**Comment by markimusprime** [comment]
> > > > > if I find some useful information around I write to you, I'm sorry that you have not been able to solve the problem.
> > > > 
> > > > 
> > > > So mine is working now. I tried plotting some new plots into the directories where my existing .plot files were and that didn't work. I uninstalled and reinstalled both 1.1.6 and 1.1.7 multiple times that didn't work either. I deleted my second private key that i had in case it was messing up my main private key that didn't work, I moved everything in my .chia folder to a temp folder then uninstalled chia app using windows uninstaller then redownloaded 1.1.6 and installed it, I then moved my large sqlite db file into the new folder so i didin't have to wait for a full sync and then started the app and it found my plots this time. What a headache. Not going to update to any new releases for the chia network unless it's mandatory, what a fail on your part.
> > > 
> > > 
> > > I did not understand the part where you explain your private keys .. do you create plots with two different private keys? however the Chia 1.1.7 update serves to solve a SQL problem that prevented the wallet from being online.
> > > If your wallet works with version 1.1.6 then it's perfect!
> > 
> > 
> > I have a private key that i use as my main key for plotting and pooling with core pool but i made a second private key to have a wallet address that I will use for the official pool plots that I make when that is released and also will use that address as the payout for my core pool payouts. Doesn't matter though, that second wallet would never sync but I didn't care that much and it ended up not mattering when I deleted it off of my gui anyways. Only thing that fixed my issue was what i mentioned above
> 
> your plots would never have worked with any other private key than the one you created the plots with.
> Only when the 'portable plots' come out will it be possible to transfer them from one wallet to another.
> I have always farmed and plotted with a single key in several machines.
> I think, from how you described what you did, the problem is that you gave your plots to a second key that did not create them and therefore would never find them.

That's not what I'm saying, I only ever have plotted to a single key, almost a thousand plots to one key.  The only reason i have a second private key with a new set of mneumonics was so that I could have a key that I could use for deposits.

**Comment by Muasin94** [comment]
> > > > > > if I find some useful information around I write to you, I'm sorry that you have not been able to solve the problem.
> > > > > 
> > > > > 
> > > > > So mine is working now. I tried plotting some new plots into the directories where my existing .plot files were and that didn't work. I uninstalled and reinstalled both 1.1.6 and 1.1.7 multiple times that didn't work either. I deleted my second private key that i had in case it was messing up my main private key that didn't work, I moved everything in my .chia folder to a temp folder then uninstalled chia app using windows uninstaller then redownloaded 1.1.6 and installed it, I then moved my large sqlite db file into the new folder so i didin't have to wait for a full sync and then started the app and it found my plots this time. What a headache. Not going to update to any new releases for the chia network unless it's mandatory, what a fail on your part.
> > > > 
> > > > 
> > > > I did not understand the part where you explain your private keys .. do you create plots with two different private keys? however the Chia 1.1.7 update serves to solve a SQL problem that prevented the wallet from being online.
> > > > If your wallet works with version 1.1.6 then it's perfect!
> > > 
> > > 
> > > I have a private key that i use as my main key for plotting and pooling with core pool but i made a second private key to have a wallet address that I will use for the official pool plots that I make when that is released and also will use that address as the payout for my core pool payouts. Doesn't matter though, that second wallet would never sync but I didn't care that much and it ended up not mattering when I deleted it off of my gui anyways. Only thing that fixed my issue was what i mentioned above
> > 
> > 
> > your plots would never have worked with any other private key than the one you created the plots with.
> > Only when the 'portable plots' come out will it be possible to transfer them from one wallet to another.
> > I have always farmed and plotted with a single key in several machines.
> > I think, from how you described what you did, the problem is that you gave your plots to a second key that did not create them and therefore would never find them.
> 
> That's not what I'm saying, I only ever have plotted to a single key, almost a thousand plots to one key. The only reason i have a second private key with a new set of mneumonics was so that I could have a key that I could use for deposits.

ahh ok, sometimes the translator doesn't work. lol
However, I'm happy that you managed to get your plots back

**Comment by MEConnectify** [comment]
> > I put some plots in the queue yesterday and went to sleep, just woke up to find out that even new plots show up under the "Not Found" category, what's really surprising is that the new plots are in a separate hard-drive, completely new directory
> 
> yes when mine was broken same thing happened to me, even new plots would immediately go to "not found plots" only thing that fixed it was what I mentioned above you should try that.

Your solution worked, thanks to anyone who participated in this conversation! going to close this issue.

**Comment by MEConnectify** [comment]
Going to reopen this so chia developers can be aware of this issue

**Comment by D2BO** [comment]
I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.

C:\Users\name.chia\mainnet\config
there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.

pool:
logging: *XXXX
network_overrides: *XXX
selected_network: mainnet
xch_target_address: Null

Open Config.yaml or (Config_bak.yaml) forgot which one.
ctrl-F and search the word Null. It should looks like the one above.
Change "Null with main wallet address.
Let me know if this helps.

**Comment by D2BO** [comment]
> I maxed 2 8Tb hard drives with plots, I turned off my PC to add another hard drive, when I turned it back on and turned the Chia GUI app on my plots weren't there, I tried reimporting them, it would find them and list them all under "Not Found", I even unplugged the hard drive i put in but they still won't show back


I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.

C:\Users\name.chia\mainnet\config
there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.

pool:
logging: *XXXX
network_overrides: *XXX
selected_network: mainnet
xch_target_address: Null

Open Config.yaml or (Config_bak.yaml) forgot which one.
ctrl-F and search the word Null. It should looks like the one above.
Change "Null with main wallet address.
Let me know if this helps.

**Comment by MEConnectify** [comment]
The issue was solved by users, although we'd like developers to prevent this from happening in the first place, that's why the issue is still open

**Comment by JoseCoco** [comment]
Good night my plots also disappeared, I tried everything mentioned above and nothing worked. Could anyone solve the problem? Thank you.

**Comment by Lazymin3r** [comment]
> > I maxed 2 8Tb hard drives with plots, I turned off my PC to add another hard drive, when I turned it back on and turned the Chia GUI app on my plots weren't there, I tried reimporting them, it would find them and list them all under "Not Found", I even unplugged the hard drive i put in but they still won't show back
> 
> I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.
> 
> C:\Users\name.chia\mainnet\config
> there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.
> 
> pool:
> logging: *XXXX
> network_overrides: *XXX
> selected_network: mainnet
> xch_target_address: Null
> 
> Open Config.yaml or (Config_bak.yaml) forgot which one.
> ctrl-F and search the word Null. It should looks like the one above.
> Change "Null with main wallet address.
> Let me know if this helps.

@D2BO This worked, for me thanks man! btw the config_bak I believe is just a backup of the config file(I updated mine just in case lol).


@JoseCoco Have you tried the fix by D2BO it is the only one that worked for me. One thing I found is that there where two locations in the config.yaml file that have the field 'xch_target_address:' which I had to update(both), might be something to look at if you only replaced Null value for your xch(chia) address. Hope that helps.

**Comment by JoseCoco** [comment]
> > > I maxed 2 8Tb hard drives with plots, I turned off my PC to add another hard drive, when I turned it back on and turned the Chia GUI app on my plots weren't there, I tried reimporting them, it would find them and list them all under "Not Found", I even unplugged the hard drive i put in but they still won't show back
> > 
> > 
> > I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.
> > C:\Users\name.chia\mainnet\config
> > there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.
> > pool:
> > logging: *XXXX
> > network_overrides: *XXX
> > selected_network: mainnet
> > xch_target_address: Null
> > Open Config.yaml or (Config_bak.yaml) forgot which one.
> > ctrl-F and search the word Null. It should looks like the one above.
> > Change "Null with main wallet address.
> > Let me know if this helps.
> 
> @D2BO This worked, for me thanks man! btw the config_bak I believe is just a backup of the config file(I updated mine just in case lol).
> 
> @JoseCoco Have you tried the fix by D2BO it is the only one that worked for me. One thing I found is that there where two locations in the config.yaml file that have the field 'xch_target_address:' which I had to update(both), might be something to look at if you only replaced Null value for your xch(chia) address. Hope that helps.

IT WORRKSSSS! at last, my man, thanks. I download and try too  "windows power shell" and try to check the plots and they were ok:

2021-06-10T00:34:37.849  chia.plotting.check_plots        : INFO     Summary
2021-06-10T00:34:37.849  chia.plotting.check_plots        : INFO     Found 5 valid plots, total size 0.49492 TiB
2021-06-10T00:34:37.849  chia.plotting.check_plots        : INFO     5 plots of size 32

But still not recognice them in the chia program. So after remplace in the  "Config.yaml" and replaced Null value for your xch(chia) address (both), There are two lines whit   : " xch_target_address: Null ", I only replace one and didnt work, but replace the two and works. Thanks again man. Me and my 10 plots xD.

**Comment by ali-fro** [comment]
> > I maxed 2 8Tb hard drives with plots, I turned off my PC to add another hard drive, when I turned it back on and turned the Chia GUI app on my plots weren't there, I tried reimporting them, it would find them and list them all under "Not Found", I even unplugged the hard drive i put in but they still won't show back
> 
> I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.
> 
> C:\Users\name.chia\mainnet\config
> there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.
> 
> pool:
> logging: *XXXX
> network_overrides: *XXX
> selected_network: mainnet
> xch_target_address: Null
> 
> Open Config.yaml or (Config_bak.yaml) forgot which one.
> ctrl-F and search the word Null. It should looks like the one above.
> Change "Null with main wallet address.
> Let me know if this helps.

It is work........
Copy wallet and close chia then replace null with wallet address
Thanks alotttttttt

**Comment by Azerione** [comment]
Thanks the procedure above works for me too just experienced it now with 1.1.7
