### ISSUE TITLE
[BUG] Linux/Ubuntu: 1.1.7 dont install (classic way no GUI-Installer)

### ISSUE THREAD

**Issue by blaupert** [Chia-Network/chia-blockchain#6519]
Hi,

Im on Ubuntu 21.04

The classic terminal install via Git dont install 1.1.7!

The Update Routine dont either!

The Experimental GUI installer seems to do 1.1.7 ... at least the download file is named 1.1.7 ;)

Pleas fix.
Thx

**Comment by Liberticide** [comment]
personally I did this:
git checkout 1.1.7
git reset --hard FETCH_HEAD

and I ended up in version 1.1.8.dev0

**Comment by txr13** [comment]
Duplicate of #6497.

**Comment by CoMMyz** [comment]
git clone https://github.com/Chia-Network/chia-blockchain.git --branch 1.1.7 --recurse-submodules

**Comment by daleaag2020** [comment]
Here is my command lines for you, I also changed the configurations to install chiapos 1.0.3:

> mkdir chia-blockchain
> 
> cd chia-blockchain
> 
> git init
> 
> git remote add origin https://github.com/Chia-Network/chia-blockchain.git
> 
> git pull
> 
> git checkout batch_sql_1.1.6
> 
> git fetch
> 
> git reset --hard FETCH_HEAD
> 
> sed -i ‘/chiapos==/c\ “chiapos”, # proof of space’ setup.py
> 
> chmod +x ./install.sh
> 
> sh install.sh
> 
> . ./activate
> 
>
