### ISSUE TITLE
[BUG] Chia wallet not synced, while full node is synced

### ISSUE THREAD

**Issue by Edge0410** [Chia-Network/chia-blockchain#6526]
**Describe the bug**
Hello. I just installed the chia blockchain and everything was fine, until while syncing the node the wallet got stuck at a constant height, while the node continued to sync. The thing is it said it is "syncing" but after restarting chia it says "not synced" and seems like there are no peer connections to the wallet. I tried reinstalling (with the exact same result, it got stuck at the exact same height value of the wallet), port forwarded the router to both 8444 and 8449 ports, not using any software besides the windows firewall, which I did not get involved with. 

![image](https://user-images.githubusercontent.com/64250100/120929913-a1de8700-c6f3-11eb-9358-9bf15945168e.png)

![image](https://user-images.githubusercontent.com/64250100/120929926-b15dd000-c6f3-11eb-9255-88900a3e9337.png)

![image](https://user-images.githubusercontent.com/64250100/120929933-c3d80980-c6f3-11eb-8110-26b87468fd4a.png)

-- Note that I even tried to connect to introducer nodes, no result

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: Build 2004
- CPU: Ryzen 5 1600x

**Comment by Hellfall1** [comment]
Did you upgrade to 1.1.7 already? (released some hours ago).

**Comment by Edge0410** [comment]
> Did you upgrade to 1.1.7 already? (released some hours ago).

Yes I did, same result. I get this bug since last monday, when 1.1.6 was the latest one.

**Comment by Edge0410** [comment]
Okay, actually, just started syncing again after 1 hour of waiting after the update to 1.1.7

**Comment by Hellfall1** [comment]
It will stuck, be patient!
(The network is flooded and the peering is sh*t.)

Add my node to speed up, if you like to: lorado.synology.me:8444
