### ISSUE TITLE
[BUG] Wallet stuck at "Not Synced" height 386,083, Connections 1 while Node is Fully Synced

### ISSUE THREAD

**Issue by Wontell** [Chia-Network/chia-blockchain#6540]
Hello,
I have this idiotic issue, im still on 1.16
My wallet just shows Not Synced and the height number doesn't gets updated, its been like this for 2 days, its stuck at height 386,083, shows connections 1 [thats normal, it always showed connections 1]
the Full Node is synced and no issues.
I tried moving the database file from the wallet to let it re-sync from start but it would not sync and just stuck at 0, so i put the database back.
Any ideas how to resolve it?

**Comment by tryer50** [comment]
download version 1.1.7 solves the wallet problem

**Comment by Mrcryptokwanza** [comment]
o download da versão 1.1.7 resolve o problema da carteira
![carteira](https://user-images.githubusercontent.com/85462352/120995164-0d206b80-c77d-11eb-8aa6-68ad3f339a20.png)
![carteira2](https://user-images.githubusercontent.com/85462352/120995169-0db90200-c77d-11eb-94de-29324d45b6b6.png)

**Comment by lixiaodong** [comment]
![image](https://user-images.githubusercontent.com/1568575/121114720-c008cc00-c846-11eb-81df-5f557f514583.png)

I have the same problem.Already upgrade to 1.1.7
