### ISSUE TITLE
how to Farming on many machines of check the hash

### ISSUE THREAD

**Issue by workboy** [Chia-Network/chia-blockchain#6546]
i use https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines to harvest
but i'cant confirm my hash
how do I confirm on the host the total hash of my current harvest network

我目前在使用全节点网络进行收割，如何在主机上确定我整个网络上的总算力

**Comment by happycouak** [comment]
In relation with https://github.com/Chia-Network/chia-blockchain/discussions/6467

**Comment by workboy** [comment]
i use `chia farm summary` have

`Farming status: Farming
Total chia farmed: 16.00000006
User transaction fees: 6e-08
Block rewards: 16.0
Last height farmed: 389468
Plot count: 5311
Total size of plots: 525.708 TiB
Estimated network space: 20080.240 PiB
Expected time to win: 1 week and 1 day
Note: log into your key using 'chia wallet show' to see rewards for each key`
but now i cant confirm my harvest network hash....
