### ISSUE TITLE
[BUG] Setting parallel plotting to a delay only applies at the start, then all jobs start simultaneously

### ISSUE THREAD

**Issue by akaczinski** [Chia-Network/chia-blockchain#657]
**Version**
b19 

**Describe the bug**
If a parallel plotting job is started with a delay > 0, all parallel jobs start after that delay has elapsed, rather than subsequent jobs waiting for the prior to begin the delay countdown. Furthermore, the delay is also applied at the beginning of the job, rather than starting the first job immediately.

**To Reproduce**
1. Go to Plots
2. Add a Plot
3. Select a plot count of 2
4. Plot in Parallel
5. Set a delay of 1 minute
6. Set temp/dest folders
7. Begin

**Expected behavior**
Plotting should begin immediately for the first plot. The second plot should begin after the delay has elapsed.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: Intel i5-6600

**Comment by seeden** [comment]
Already updated via https://github.com/Chia-Network/chia-blockchain/tree/ui-plotting

**Comment by hoffmang9** [comment]
In for next release. https://github.com/Chia-Network/chia-blockchain/pull/717
