### ISSUE TITLE
[BUG] LOST BALANCE?

### ISSUE THREAD

**Issue by Kryptoand** [Chia-Network/chia-blockchain#6571]
I changed computer and when I installed the new version of chia the chia balance which was 2 xch disappeared. Does it reappear when the node is fully synchronized? or when it appears?

**Comment by top4ic34** [comment]
I have the same problem. After preinstalling the Windows, the wallet was synchronized but the coin did not appear.

**Comment by Kryptoand** [comment]
how to recover our balance? help from the creators?

**Comment by top4ic34** [comment]
> как восстановить баланс? помощь от создателей?

Думаешь разработчики помогут нам? Ребята не держите свои монеты в кошельках chia, выводите сразу на биржу. Всё сырое и не понятно вернется баланс или нет. Дырявый кошелек.

**Comment by Kryptoand** [comment]
It is very serious if the wallet balances disappear. the blockchain does not work

**Comment by ozerozay** [comment]
Wait for wallet sync, not full node sync. They are not same and check your address on chiaexplorer

**Comment by Kryptoand** [comment]
In chia explorer the balance appears but not in chia app in windows

**Comment by ozerozay** [comment]
![walletsync](https://user-images.githubusercontent.com/7784735/121065977-0bcd5e00-c7d2-11eb-8914-728d7d095d92.PNG)
then its okay, check this image

**Comment by Kryptoand** [comment]
ok perfect. I wai. thanks. I wait 12hours

**Comment by top4ic34** [comment]
> Ок, прекрасно. Я вай. Благодарю. Я жду 12 часов



> ![walletsync](https://user-images.githubusercontent.com/7784735/121065977-0bcd5e00-c7d2-11eb-8914-728d7d095d92.PNG)
> тогда все в порядке, проверьте это изображение

У меня синхронизация кошелька прошла. Но на балансе 0.

**Comment by Kryptoand** [comment]
I will write here in 12 hours the result of the synchronization

**Comment by max918** [comment]
you can check you latest balance online

https://www.chiaexplorer.com/blockchain/address/<< your wallet address >>

**or** wait for wallet sync

**Comment by top4ic34** [comment]
Баланс появился. после синхронизации надо было перезагрузить компьютер.

**Comment by Kryptoand** [comment]
I have reinstalled the chia I have restarted. At the end of the synchronization, the balance appeared. Thanks for your help friends

**Comment by Kryptoand** [comment]
all it's ok if you wait the complety sync!!!
