### ISSUE TITLE
my plots disappear  101 plots lost, Not found Plots[BUG]

### ISSUE THREAD

**Issue by yggdrasileu** [Chia-Network/chia-blockchain#6580]
I restart my PC and when i start chis GUI i have no plots in my acount, i only have one PC and i only have ONE KEY no more

I try to reinstall all versions of chia GUI ,i try to replot and update plots i try to restart PC and i try delete key and do all the easy process .
i try to replos and w8 for 1 day but nothing happens i need help 101 plot is to mutch for loss it. Y_Y
i need a solution please^^

PD: when i try to replot all the new plots are going to the same list of not found plots....

![Sin título](https://user-images.githubusercontent.com/85521279/121085105-c022b080-c7e1-11eb-85bf-be273fe9fd4c.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10 Home
- OS Version/Flavor: last version
Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz   2.70 GHz
16,0 GB RAM DDR4

**Comment by D2BO** [comment]
I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again. 

C:\Users\name\.chia\mainnet\config 
there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address. 

pool:
  logging: *XXXX
  network_overrides: *XXX
  selected_network: mainnet
  xch_target_address: Null

1. Open Config.yaml or (Config_bak.yaml) forgot which one.
2. ctrl-F and search the word Null. It should looks like the one above.
3. Change "Null with main wallet address.

**Comment by D2BO** [comment]
> I restart my PC and when i start chis GUI i have no plots in my acount, i only have one PC and i only have ONE KEY no more
> 
> I try to reinstall all versions of chia GUI ,i try to replot and update plots i try to restart PC and i try delete key and do all the easy process .
> i try to replos and w8 for 1 day but nothing happens i need help 101 plot is to mutch for loss it. Y_Y
> i need a solution please^^
> 
> PD: when i try to replot all the new plots are going to the same list of not found plots....
> 
> ![Sin título](https://user-images.githubusercontent.com/85521279/121085105-c022b080-c7e1-11eb-85bf-be273fe9fd4c.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows 10 Home
> * OS Version/Flavor: last version
>   Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz   2.70 GHz
>   16,0 GB RAM DDR4

I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.

C:\Users\name.chia\mainnet\config
there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.

pool:
logging: *XXXX
network_overrides: *XXX
selected_network: mainnet
xch_target_address: Null

Open Config.yaml or (Config_bak.yaml) forgot which one.
ctrl-F and search the word Null. It should looks like the one above.
Change "Null with main wallet address.
Let me know if this helps.

**Comment by yggdrasileu** [comment]
> > I restart my PC and when i start chis GUI i have no plots in my acount, i only have one PC and i only have ONE KEY no more
> > I try to reinstall all versions of chia GUI ,i try to replot and update plots i try to restart PC and i try delete key and do all the easy process .
> > i try to replos and w8 for 1 day but nothing happens i need help 101 plot is to mutch for loss it. Y_Y
> > i need a solution please^^
> > PD: when i try to replot all the new plots are going to the same list of not found plots....
> > ![Sin título](https://user-images.githubusercontent.com/85521279/121085105-c022b080-c7e1-11eb-85bf-be273fe9fd4c.png)
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. Windows 10 Home
> > * OS Version/Flavor: last version
> >   Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz   2.70 GHz
> >   16,0 GB RAM DDR4
> 
> I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.
> 
> C:\Users\name.chia\mainnet\config
> there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.
> 
> pool:
> logging: *XXXX
> network_overrides: *XXX
> selected_network: mainnet
> xch_target_address: Null
> 
> Open Config.yaml or (Config_bak.yaml) forgot which one.
> ctrl-F and search the word Null. It should looks like the one above.
> Change "Null with main wallet address.
> Let me know if this helps.

OK i will try now tnx for the info i tell you if it work

**Comment by yggdrasileu** [comment]
> main wallet address

where i can find main wallet address ?

**Comment by yggdrasileu** [comment]
> I had the same problem and I fixed it by going to config file in my chia mainnet folder and pasting my wallet again.
> 
> C:\Users\name.chia\mainnet\config
> there should be two config file and one have your main wallet. The other one says "Null". you have to replace "Null" with your actual wallet address.
> 
> pool:
> logging: *XXXX
> network_overrides: *XXX
> selected_network: mainnet
> xch_target_address: Null
> 
> Open Config.yaml or (Config_bak.yaml) forgot which one.
> ctrl-F and search the word Null. It should looks like the one above.
> Change "Null with main wallet address.
> Let me know if this helps.

sorry dont work for me T_T ,3 days traying everything.

**Comment by yggdrasileu** [comment]
> I think there may be more to this than just a wallet address. When you add a plot directory, it finds all the plots in it, and even lists them for you. So it obviously FOUND the plots, but proceeds to say they aren't "FOUND" anyway. Stupid thing is, if you copy the path/name for a plot, it leads directly to the actual plot. So this program is full of SH1T. I feel like this GUI was hacked together, and really doesn't get old bugs fixed, just adds new, usually broken, features.

the bad thing is i dont have support for this, i try to uninstall 100000 times all the versions and now i cant farming and i cant generate new plots because the new plots are going to the same list and the GUI said me he cant found them.....

**Comment by gacz81** [comment]
You must reinstall the Chia app. It happen sometimes when you change some in your hard config. My case was when I change my disk from sata1 conector to sata2 for better airflow or for adding a new disk.
Solution: 
1) make a copy backup of directory  C:\Users\yourusername\.chia\mainnet\db
2) uninstall chia (dont worry it keeps your keys, but backup your seed words anyway)
3) install chia again 
4) copy you backed up directory in step 1 to the same old place and replace (this for not to sync all again). Or just waint to sync.
5) run chia
6) add your plots directories again

Hope it help

**Comment by M1dn1ghtN1nj4** [comment]
I'll try that.  I've been down for two days.  I have a new NVMe drive on
the way, b so if I NEED to replot, I guess I can, but I shouldn't have to
sacrifice my GOOD plots.... I'll try this evening

**Comment by gacz81** [comment]
did you try erase directory  C:\Users\yourusername\.chia\ 
before uninstall and install again?

**Comment by haracena** [comment]
> You must reinstall the Chia app. It happen sometimes when you change some in your hard config. My case was when I change my disk from sata1 conector to sata2 for better airflow or for adding a new disk.
> Solution:
> 
> 1. make a copy backup of directory  C:\Users\yourusername\.chia\mainnet\db
> 2. uninstall chia (dont worry it keeps your keys, but backup your seed words anyway)
> 3. install chia again
> 4. copy you backed up directory in step 1 to the same old place and replace (this for not to sync all again). Or just waint to sync.
> 5. run chia
> 6. add your plots directories again
> 
> Hope it help

Thank you so much! this is the solution.
