### ISSUE TITLE
no sinced

### ISSUE THREAD

**Issue by josemacedove** [Chia-Network/chia-blockchain#6582]
Hello greetings, I do not know what to do, I had a month working well, then this became a headache, I can not synchronize my desktop and less my laptop w10 Pro., it remains red, not synced. already enabled the pto. 8444, I even enabled the DMZ of my router, I have the permissions enabled on the computers and nothing, I desistalo and install and the 1.1.7 is the same, sometimes it says wait until peak height 399.478 and I wait two days and everything remains the same it does not synchronize, Well this seems like a joke to me, I imagine that the big investors and the Chinese do not happen this and it is not just me, there are thousands, if not millions, if some administrator gives me a solution, I appreciate it, thank you help

**Comment by WavJaby** [comment]
make sure your internet have no problems, such as having a high ping, slow download speed or low upload speed

to connect other peers you can go here https://chia.keva.app/
paste the code to chrome DevTools > Console
```javascript
let list = document.getElementsByTagName('tbody')[0].getElementsByTagName('td');
let result = '';
for(let i = 3; i < list.length; i+=3){
    result += 'chia show -a ' + list[i].textContent + ":"+ list[i+1].textContent + ' &\n';
}
console.log(result);
```
paste the output to windows cmd (how to execut chia command see https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#locate-the-chia-binary-executable)
it should do things like this
![image](https://user-images.githubusercontent.com/51706075/121124703-ee42d780-c857-11eb-84a5-c7819e794a23.png)

**Comment by josemacedove** [comment]
Hello, thank you all, but I have already solved the problem. It did not synchronize because it had the hour in 12 hours and when I changed it to a long time of 24 hours and restarted, there I synchronize, I hope this experience will serve someone, thank you
