### ISSUE TITLE
GUI plot progress percent is wrong (v1.1.7)

### ISSUE THREAD

**Issue by joelrb** [Chia-Network/chia-blockchain#6585]
**Describe the bug**
There's now a bug plotting in GUI which did not happen in previous versions. The percentage shown is wrong.

**To Reproduce**

Add a plot

**Expected behavior**
Show correct plot progress percent.

**Screenshots**
![Screen Shot 2021-06-08 at 8 16 06 AM](https://user-images.githubusercontent.com/225284/121103697-06543000-c833-11eb-85af-6b67e0bcf3c8.png)
![Screen Shot 2021-06-08 at 8 17 15 AM](https://user-images.githubusercontent.com/225284/121103705-09e7b700-c833-11eb-9d07-3d186e9d1620.png)

**Desktop (please complete the following information):**

- OS: MacOS
- OS Version/Flavor: Big Sur
- CPU: Mac mini (2018) 

**Additional context**
Yesterday's plot show correct percentage but this new one has an issue.

**Comment by WavJaby** [comment]
I seems like you just change the bucket size right? (to 64)
I have the same problem too
but I think that is not very important XD

**Comment by joelrb** [comment]
> I seems like you just change the bucket size right? (to 64)
> I have the same problem too
> but I think that is not very important XD

Yes, increased memory and reduced bucket size to 64 to lessen IO on disk which I have been doing to other plots with no issue. I did not encounter this in 1.1.6.

**Comment by seeden** [comment]
Fix for this issue was already merged and will be part of the next release.
