### ISSUE TITLE
[BUG] Plot status is "Error" with Red bar when node is syncing

### ISSUE THREAD

**Issue by eFishCent** [Chia-Network/chia-blockchain#659]
**Describe the bug**
When the node is syncing, the status of plots shows an "Error" with Red bar when the node is syncing.
 
**To Reproduce**
Delete blockchain_v22.db
Start client
Go to Plots tab
See plots status of "Error" with Red bar.

**Expected behavior**
Recommend status be "Node syncing" with Yellow bar color.

**Desktop (please complete the following information):**
- OS: macOS
- OS Version/Flavor: Catalina 10.15.7
- CPU: 3 GHz 6-Core Intel Core i5

**Comment by seeden** [comment]
The farming state is related also to farmer connection.
We are showing an error when the farmer is not connected or is not running. Maybe a better idea is to show something else.

**Comment by seeden** [comment]
Plot state is updated via https://github.com/Chia-Network/chia-blockchain/pull/755
