### ISSUE TITLE
Add a Contribute.md

### ISSUE THREAD

**Issue by RichardLitt** [Chia-Network/chia-blockchain#66]
Are you looking for contributions to this project? What would they look like? What would you like people who install this software to do; do you want them to report bugs, or to ask for features? Are you open to contributors becoming maintainers?

All of these questions could be answered in a Contribute.md. :) Let me know if you want help fashioning one.

**Comment by mariano54** [comment]
We definitely want contributors. Good idea, thanks :). I'll address it.

**Comment by RichardLitt** [comment]
Thanks, @mariano54 :)
