### ISSUE TITLE
[BUG] Delete plot from queue in GUI not available in 1.1.7.

### ISSUE THREAD

**Issue by SrkaDDD** [Chia-Network/chia-blockchain#6605]
**Describe the bug**
When plots queued, can not delete them. This was not bug in previous versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/85565405/121197303-7f727800-c871-11eb-923a-67fccdaf65b5.png)

- OS: Windows Server 2012 R2
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: Intel xeon X5680

**Comment by gromran** [comment]
read the changelog of version 1.1.6...

**Comment by Muasin94** [comment]
> **Describe the bug**
> When plots queued, can not delete them. This was not bug in previous versions.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/85565405/121197303-7f727800-c871-11eb-923a-67fccdaf65b5.png)
> 
> * OS: Windows Server 2012 R2
> * OS Version/Flavor: [e.g. CentOS 7.2]
> * CPU: Intel xeon X5680

Already from version 1.1.6 the plots could not be deleted.
In version 1.1.5 when you deleted a plot created in parallel, the other plots were often blocked, which is why the "delete" button was blocked.
