### ISSUE TITLE
[BUG] Статус кошелька -  не синхронизирован

### ISSUE THREAD

**Issue by Dzhuga** [Chia-Network/chia-blockchain#6609]
Баг появился несколько дней назад. Не синхронизируется именно кошелек (скриншот), Сам узел отлично синхронизируется, соединение так же подключено (скриншот).

Порты на роутере проброшены (56621, 8449, 8444)

В чём может быть дело и как решить? Не могу получить свои монеты уже 5 день...

![Буфер обмена-1](https://user-images.githubusercontent.com/35343398/121223260-8ae59380-c8b1-11eb-8a44-288938709c7b.jpg)
![Буфер обмена-2](https://user-images.githubusercontent.com/35343398/121223373-a9e42580-c8b1-11eb-884f-2d13bd4268cd.jpg)

**Comment by setar** [comment]
Нужно анализировать лог

win + r и вводишь cmd
команды выполнять в (заменить имя пользователя и правильно версию кошелька указать)
C:\Users\ имя пользователя \AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon
чтобы включить уровень логирования info:
chia configure -log-level=INFO

логи читать тут:
C:\Users\ имя пользователя \.chia\mainnet\log

**Comment by timnbv** [comment]
Translation: 
Only wallet is not synchronized (see the screenshot - Wallet status - not synced). The node itself works fine (see screenshot)
Ports forwarded: 56621, 8449, 8444.

What might be the problem and how to solve it?  I can't receive my coins for 5 days...

**Comment by VitaliyAT** [comment]
Такая же ботва... только он при заходе на кошелёк мне пишет попап с какими то просто цифрами. И пишет что кошелёк не синхронизирован. Версия Чиа 1.2.11
