### ISSUE TITLE
[BUG] eternal wallet loading...

### ISSUE THREAD

**Issue by dextercheco** [Chia-Network/chia-blockchain#6636]
For several days I have had connection problems, my wallet does not synchronize and sometimes it's even the Chia tool that crashes completely like here for about 45 minutes, it loads but nothing happens.

I don't want to restart the tool because I'm plotting and I'm more than halfway through. I also installed the new version 1.1.7

![Wallet](https://user-images.githubusercontent.com/85617272/121336885-388d8c80-c91c-11eb-8e97-93cbebf7fc4c.png)

- OS: Window 10 64bit Pro
- CPU: Intel i7

**Comment by dextercheco** [comment]
I also installed the new version 1.1.7

**Comment by Muasin94** [comment]
if from the activity management the chia process shows that it is still plotting I advise you not to touch anything until it ends, but I do not assure you that the existing plots are being farmed.
Take a look at the \ .chia \ mainnet \ log DEBUG.LOG file and see if there are any errors.

**Comment by hpoolparachia** [comment]
I´ve checked this issue, and i think that the cause of this is that the application try to read temp plots files and can´t do it well. After some tests, i´ve deteled al my temp plot files (in this case, i´ve lost al my plotting works) and after this, i´ve started the chia program whitout problems, fast and clear. I´ve do it 3  times to be sure, and the scenario is the same in all cases.

**Comment by cafsantos7** [comment]
I still use the version 1.1.5 and it works for me.
