### ISSUE TITLE
[BUG] Wallet queda eternamente cargando 

### ISSUE THREAD

**Issue by AlexTestingqa** [Chia-Network/chia-blockchain#6674]
**Describe the bug**
Al ingresar a Chia coin la wallet se queda cargando, y no me permite realizar ningun detalle ni visualizar nada.

Adjunto evidencia.
<img width="959" alt="Captura" src="https://user-images.githubusercontent.com/85709479/121596870-6820bf80-ca16-11eb-94d0-0449a769d3a4.PNG">

**Comment by rentero** [comment]
Me pasa exactamente lo mismo. He borrado, reinstalado, borrado, probado otras versiones y nada. Se queda cargando... aparte solo me deja crear una parcela, las siguientes no me aparecen ni en cola..

**Comment by rentero** [comment]
ahora resulta que por probar la opcion de crear en paralelo para averiguar si funcionaba le di a shift comando R para forzarlo a reactualizar/refrescar el cliente y ahora ni me entra. se ha quedado en conectar a cartera ... 
![WALLET ](https://user-images.githubusercontent.com/85710254/121601290-0a0bd080-ca46-11eb-8b32-b26f165f681f.jpg)

**Comment by ricacale** [comment]
Hola Rentero, me paso hoy lo mismo que a vos, pudiste solucionarlo?

**Comment by behzadiazad** [comment]
سلام من بعلت حذف و نصب شدن مجدد گوشی از برنامه های خود خارج شدم لطفاً مجدداً من را قبول کنید
