### ISSUE TITLE
Something really wrong with my wallet. Reward and payments / Hacked?

### ISSUE THREAD

**Issue by Andreeeeww** [Chia-Network/chia-blockchain#6681]
Well, I installed my full node about 3 months ago on my laptop to test the system and satrted farming since then.

Later I purchased 3 more computers and invested into chia network.

And recently I won first block and been happy.

So I decided to create new wallet and send money there for security reason. I tried to send 0.0000000000000001 as test before sending full reward and recieved nothing. Then 0.0000000000000010 and recieved nothing since.

Okay, that made me bit nervous, but what.. its just a few cents. So I waited. Nothing happend for about 10 hours now.

I was thinking, maybe its to low amount or low fee. So started investigating.

So today, I have noticed that I have won another block! But recieving wallet is different then mine. I never typed that wallet.

I don't see block in pending balances, still have only 2 chia farmed in my full node and only see incomming 0,25 and 1.75 in incomming transactions.

Well.. maybe its a bug. maybe I'm hacked. But strange is that block rewards are recieved almost the same time I've sent the test payment.

Guys, it makes me very nervous. I can't send any money from my wallet.

Yes, those .000xxx1 coins did went out. But I have no reward comming. I can't recieve my coins to my new wallet. 

Asking for help.

I have 3 computers running full node. I didn't do any kind of special settings. Just run a full node and plot and farm on each one.

Can this be because I'm trying to send money from one of the computers? 

Confusing. Can povide logs and more data.

Thank you.
Andrew

**Comment by Andreeeeww** [comment]
This is the wallet recieving my rewards xch1kwdcfgqta08ydnqwfasrgnwk3zj6crce24fap5jr39uwwrl0p7gsuw4mru

**Comment by Andreeeeww** [comment]
Far I do research. From my wallet it went to xch1kwdcfgqta08ydnqwfasrgnwk3zj6crce24fap5jr39uwwrl0p7gsuw4mru
and from that wallet my rewards went to xch1pjm58q39vhr73pqfvanz4yczztv908mnaj9cwpwr7dxmn2mze5vqu0tehc

I did test beta version of programkom software https://www.programkom.net/en/portfolio/programkoms-chia-plotter/

This is the only plotter I've tested.

**Comment by Andreeeeww** [comment]
Seems my money are now on the wallet 0x6dac591c97d2dcb65c0de4c72f916faa4c714199c2f430f8b5bb682b760ea3ba

Devs, please help.

**Comment by Andreeeeww** [comment]
If my wallet been compromised. What I should do now? Can I do new security key? Or I need to replot everything now?

**Comment by joelrb** [comment]
Check your config.yaml in ./chia/mainet/config/.

What is set in the two 'xch_target_address:'? Is it xch1kwdcfgqta08ydnqwfasrgnwk3zj6crce24fap5jr39uwwrl0p7gsuw4mru? Then change it to your wallet.

You may have created a new private key that's why you got this xch1ztezzjkvcnr7hfwye2pvsks7dq9cv7xwqucmd7tdqc48agp30kqqqzgej0 and did not update the config.yaml?

If you have the mnemonic for the rewards wallet just go Keys and do an import.
