### ISSUE TITLE
[BUG] World readable private keys

### ISSUE THREAD

**Issue by JakeHillion** [Chia-Network/chia-blockchain#6691]
**Describe the bug**

Private keys created on Unix operating systems are world readable. This is incredibly dangerous for privilege separation reasons. It completely defeats the point of one having a separate farming and plotting user.

**To Reproduce**

1. Install chia-blockchain (`pip install chia-blockchain`).
2. Run `chia init`.

**Expected behavior**

Any private keys generated should be accessible only by the user who created them.

**Screenshots**

  drwxr-xr-x  2 root root 4096 Jun 11 22:50 .
  drwxr-xr-x 10 root root 4096 Jun 11 22:50 ..
  -rw-r--r--  1 root root 1159 Jun 11 22:50 private_wallet.crt
  -rw-r--r--  1 root root 1679 Jun 11 22:50 private_wallet.key
  -rw-r--r--  1 root root 1159 Jun 11 22:50 public_wallet.crt
  -rw-r--r--  1 root root 1675 Jun 11 22:50 public_wallet.key

NOTE: These are only owned by root as this was created on a testing system, solely for the purpose of this bug report.

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Debian 10
- CPU: N/A
- chia-blockchain Version: 1.1.7

**Additional context**
Not platform specific, also occurs on MacOS and other Linux systems.

**Comment by lvcivs** [comment]
duplicate of #5089
