### ISSUE TITLE
El programa está conectado pero no sincroniza, está continuamente en estado de SINCRONIZANDO

### ISSUE THREAD

**Issue by Amardito221170** [Chia-Network/chia-blockchain#6700]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by Amardito221170** [comment]
![image](https://user-images.githubusercontent.com/85770222/121776122-8ba45100-cb61-11eb-9996-27361de47430.png)
Windows 10, AMD Athlon II x 4 640

**Comment by IgnaciusMaximus** [comment]
Tienes que alcanzar el bloque en que se encuentra actualmente la blockchain.

En la foto que subiste vas en el bloque 200352 y tienes que llegar al bloque 418127, por lo general la sincronización demora varias horas
