### ISSUE TITLE
[BUG]fake plots and proofs！@Chia-Network

### ISSUE THREAD

**Issue by lzy605** [Chia-Network/chia-blockchain#6708]
**Describe the bug**

Many people are packet capturing to make fake proofs.
**To Reproduce**
I donot know the process.

**Expected behavior**
those fake plots must be forbidden or the whole project is meaningless.

**Screenshots**
![image](https://user-images.githubusercontent.com/85816890/121795511-2a08e300-cc44-11eb-8e6d-468baa52f511.png)
![image](https://user-images.githubusercontent.com/85816890/121795519-355c0e80-cc44-11eb-934f-737e06c62cfa.png)

**Comment by Hardcore-fs** [comment]
you should go do more research......
this is a valid plot process.
there is no "packet capture" 
as you said "i don't know the process".

it is just a highly optimized way to generate plot files.
and they are NOT fake proofs, they fully validate with the chia plot checker

**Comment by mrecats** [comment]
Highly Optimised!?
20 minutes to create a plot?

I didn't think this was supposed to be possible.
Can you tell me more about the mechanics of this please.

**Comment by ramkom9** [comment]
Is that mean there is option to have advantage of all others? That mean bunch of people creating plots in 20 min and getting wining just cuz others have no idea it is even possible. NO FAIR sound like scam right now.

**Comment by qweqwqsqwwew** [comment]
This is not bug,it use multi-threaded in cpu to plot a block,this github address is https://github.com/madMAx43v3r/chia-plotter,i use it to create it to plot very fast ,and it can be validated by  chia plot checker.

**Comment by qweqwqsqwwew** [comment]
https://github.com/madMAx43v3r/chia-plotter

**Comment by Hardcore-fs** [comment]
it's the bitcoin fiasco all over again.......
just highly compressed down from 4 years to 4 weeks.......

**Comment by fgc0109** [comment]
哈哈哈 20分钟算什么
有人已经 60s 一张图了
https://www.reddit.com/r/chia/comments/nyysby/k32_plots_broken_by_oak_ridge_national_laboratory/

**Comment by Hardcore-fs** [comment]
you mean the video where they DON't show the files being verified....
and the video cuts before the end.

What is surprising.. is that people actually think, that would be the performance of a computer at oak ridge......

**Comment by adevcoder** [comment]
> 哈哈哈 20分钟算什么
> 有人已经 60s 一张图了
> https://www.reddit.com/r/chia/comments/nyysby/k32_plots_broken_by_oak_ridge_national_laboratory/

384 threads. Wish I have that kind of computing power.

**Comment by Hardcore-fs** [comment]
stop perpetuating potential scams... to drive traffic to a youtube video.

I can EASILY beat those figures... maybe get it down to 5 seconds...
all by removing code from the plotter.
since there is no validation of the final file by an approved method, this video is just dross, and highly unscientific  FUD
as i said.. it cuts just before the critical time.
