### ISSUE TITLE
the height of blockchain is growing, but local sync is stopped

### ISSUE THREAD

**Issue by GerhardMcG** [Chia-Network/chia-blockchain#6722]
the height of blockchain is growing, but local sync is stopped, Peak height is stuck at previous value and syncing status at another height and not able to sync.

**Comment by giannoug** [comment]
Same here, stuck at 426,456 and not syncing further. I have some exceptions logged but not sure if they are related.

```
2021-06-14T01:47:23.035 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 640, in _sync
RuntimeError: Weight proof did not arrive in time from peer: xxx.xxx.xxx.xxx
```

This one too:
```
2021-06-14T01:37:52.431 full_node asyncio                 : ERROR    Future exception was never retrieved
future: <Future finished exception=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')>
Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 656, in _sync
  File "chia\full_node\weight_proof.py", line 606, in validate_weight_proof
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2021-06-14T01:44:20.553 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 200, in ws_api
  File "chia\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set
```

**Comment by GerhardMcG** [comment]
This is an absolute nightmare and you can agree, by the time it has been sorted out it will take days to get synced again. Due to this also my plots are not completing properly gets to a point and just hangs. So you are losing farm, you are unable to plot and unable to sync. BIG mess!!! Please let me know if you manage to find a solution. HAHA I have even sent them an email, don't think anything would come of it. It does say for support so lets see what happens.

**Comment by giannoug** [comment]
It sorted itself overnight, it is now synced and farming. Downtime was about ~6h for me.

**Comment by GerhardMcG** [comment]
Hi George, very glad for you. Mine is still a mess :(. And did you change anything or did you just leave it?

**Comment by giannoug** [comment]
Just did a restart of the farmer but the exceptions stopped on their own. It might be worth checking your debug.log file.

**Comment by GerhardMcG** [comment]
To be honest, I can check the debug log file, but having a full understanding of what is going on is another thing. I might send you the screenshot if you don't mind as I see you have knowledge of that process if you would not mind. I need to get this thing up and running as soon possible.

**Comment by GerhardMcG** [comment]
sqlite3.databaseerror: database disk image is malformed, this is the error I found in my log file. no idea what it is or how to fix it. Any idea from your side?
