### ISSUE TITLE
chia blockchain app there is endless opportunity to get chia through faucet.chia.net.

### ISSUE THREAD

**Issue by SWICTH13** [Chia-Network/chia-blockchain#6731]
To the chia blockchain app  There is endless opportunity to get chia through faucet.chia.net. It is enough just to change your ip address using vpn apps.  fix  to this error

**Comment by qq89008222** [comment]
兄弟你怕是傻子吧，你是国人吧。一次空投1mojo是0.0000000001xch，全世界有42.9亿个ip地址，你把全世界的ip地址都领一遍也才0.049xch，也就价值20多美金。你这智商也不适合这个项目啊

**Comment by SWICTH13** [comment]
> 兄弟你怕是傻子吧，你是国人吧。一次空投1mojo是0.0000000001xch，全世界有42.9亿个ip地址，你把全世界的ip地址都领一遍也才0.049xch，也就价值20多美金。你这智商也不适合这个项目啊

this is my guess and keep your opinion to yourself.  insulting a stranger is at least wrong.  if you had an IQ, you would have enough brains to answer adequately
