### ISSUE TITLE
[BUG] Mac GUI never fully initializes and syncs.

### ISSUE THREAD

**Issue by DCSuns** [Chia-Network/chia-blockchain#6744]
Running 1.1.7 latest release. Feels like the issue started when I upgrade my Mac to latest version.  Able to log in and says it connects to wallet, but then the home (Full Nude) screen constantly sits at this screen with spinning circles like it's trying to connect. Not able to sync even after leaving it in this state for days. Tried to downgrade back to 1.1.6 and 1.1.5 with same issues. Assuming it is due to latest Mac upgrade.  Still able to plot, but not farming.

- OS: Mac OS Big Sur 11.4
- CPU: 2017 Macbook Pro, 2.8 Ghz Quad-Core Intel core i7, 16GB 2133Mhz LPDDR3 Ram

![Image 6-14-21 at 11 58 AM](https://user-images.githubusercontent.com/85900324/121945008-2474d100-cd08-11eb-83d3-11aeab7faf40.jpg)

**Comment by Hardcore-fs** [comment]
its your config.
works perfectly fine on mine
1. open your firewall & redirection to your mac
2. drop into the folder, use . ./activate
chia show -a syncnode.chiafactory.com:7444
chia show -a introducer-eu.chia.net:8444
chia show -a introducer-va.chia.net:8444
chia show -a introducer-or.chia.net:8444 
chia show -a introducer-apse.chia.net:8444
chia show -a introducer-apne.chia.net:8444

3. chia show -s -c
4. chia farm summary

**Comment by DCSuns** [comment]
> its your config.
> works perfectly fine on mine
> 
> 1. open your router firewall & redirection to your mac (turn off mac firewall if on)
> 2. drop into the folder, use . ./activate
>    chia show -a syncnode.chiafactory.com:7444
>    chia show -a introducer-eu.chia.net:8444
>    chia show -a introducer-va.chia.net:8444
>    chia show -a introducer-or.chia.net:8444
>    chia show -a introducer-apse.chia.net:8444
>    chia show -a introducer-apne.chia.net:8444
> 3. chia show -s -c
> 4. chia farm summary

**Comment by DCSuns** [comment]
@Hardcore-fs. Any chance you can explain that a bit more simpler for a guy who just uses the GUI primarily?

**Comment by Hardcore-fs** [comment]
Hi,
how are you working?
build from source or using the prebuilt app ?

if prebuilt app:
1. find your app
2. RIGHT click it (show packet contents)
3. open the folder "MacOS" ,inside is a program called "Chia"
4.  Open a terminal window.
5. Drag the "Chia" to the terminal window (don't worry it will NOT move it), you should now see a long "path name"
6. press "space" and add a "&" then press return

Did it throw any errors in the terminal  window?
