### ISSUE TITLE
No Plots loading in GUI

### ISSUE THREAD

**Issue by CavrosEU** [Chia-Network/chia-blockchain#6745]
I have 800+ plots, About 16 hrs ago they are now not displaying in the GUI at all. 
I have reinstalled CHIA BLOCKCHAIN. 
Re-entered fileshares to the GUI. 
The GUI is fully sync'd, 
Im running the 1.1.7. 
Only one full node on my network. 
No changed were made to my setup prior to PLOTs not loading.

**Desktop (please complete the following information):**

- OS: Windows Server
- OS Version/Flavor: Server 2019
- CPU: [e.g. Intel i7 6700

**Additional context**

**Comment by seeden** [comment]
can you try to remove and add the plot directory again?

**Comment by kozalat** [comment]
i m having the same problem

**Comment by kozalat** [comment]
i try remove and add plot directory but nothing has changed

**Comment by pinnedjoint** [comment]
Same here!!!

**Comment by luckynickell89** [comment]
literally just swapped motherboards to an x570 with 23 m.2 slots and now all of my plots are not showing in gui! I removed directories and re-added them and still won't show!! not cool man

**Comment by luckynickell89** [comment]
2021-06-18T08:54:01.806 harvester chia.plotting.plot_tools: WARNING  Plot D:\Plot farming\plot-k32-2021-06-17-22-39-68fa04afee2c3116a410ab53bdf0c5945d5fdedd5e78fb0f0017b0dcbe4d7a97.plot has a farmer public key that is not in the farmer's pk list. is 1 of my errors? how do i fix this

**Comment by Joleks** [comment]
I have the same problem? how to fix it ?

**Comment by luckynickell89** [comment]
I have no idea. I've been trying to fix it all day.

**Comment by pinnedjoint** [comment]
I deleted all chia folders (actually save them in another directory) and reinstall everything. I manage to get all my plots but the balance is gone!!!! I'm surprised that by restoring my wallet from the mnemonic seeds my balance would disappear!!! 

I don't know whether to luff or cry!!!

**Comment by luckynickell89** [comment]
> I deleted all chia folders (actually save them in another directory) and reinstall everything. I manage to get all my plots but the balance is gone!!!! I'm surprised that by restoring my wallet from the mnemonic seeds my balance would disappear!!!
> 
> I don't know whether to laugh or cry!!!  
what exact folders did u save? im about to do the same

**Comment by luckynickell89** [comment]
what exact folders did u save in another location? im about to do the same\

**Comment by kopairl** [comment]
i have similar problem. GUI stops read plots. getting msg: ot found Plots
Caution, deleting these plots will delete them forever. Check that the storage devices are properly connected.
and all my plots listed below.\
Any solutions??

**Comment by hbheiner** [comment]
> i have similar problem. GUI stops read plots. getting msg: ot found Plots
> Caution, deleting these plots will delete them forever. Check that the storage devices are properly connected.
> and all my plots listed below.
> Any solutions??

me too, remove and add again does not change this... plots are not found anymore... but they are all there

**Comment by ppsirius** [comment]
I update to the newest version and have a loading spinner on plots. Issue still exists, anyone from core developers checks what's going on?

**Comment by mnzer1987** [comment]
i have same issue come up today , and i don't know how to solve it i have 7500 plots

**Comment by seeden** [comment]
I will check the latest version if there is any new issue.

**Comment by ppsirius** [comment]
new version still have this issue 🤬

**Comment by jeremywhd** [comment]
same issue still exist. Keeps showing nothing with the circle keeps spinning

**Comment by palroland** [comment]
Same problem for over a month now. So there's no solution or nobody cares about this?

**Comment by ppsirius** [comment]
Looking at the chia price not only dev working on the project.

I find the solution in other topics. In the chia config file some null-s appear. 
When you delete these nulls everything should work ok.

**Comment by Janokapapa** [comment]
> Looking at the chia price not only dev working on the project.
> 
> I find the solution in other topics. In the chia config file some null-s appear. When you delete these nulls everything should work ok.

really its a config problem:
look up the chia folder
look for 'config' folder
open config.yaml
I had the line 'xch_target_address' value null
I had old config files saved here, config.xxx
in the saved old configs there was a real address here, I put back instead of null and now its working
