### ISSUE TITLE
[BUG] Error message unexpectedly repeating

### ISSUE THREAD

**Issue by vexr** [Chia-Network/chia-blockchain#675]
Using the “Search block by header hash” function at the bottom of Full Node in the UI throws up an error if the search query is not a valid block hash.  The bug is the error message is repeated twice, requiring you to click “ok” twice to exit.

This behavior has been confirmed to persist on the Windows and Linux 1.0beta19

**Comment by mariano54** [comment]
Moved to https://github.com/Chia-Network/chia-blockchain-gui/issues/25
