### ISSUE TITLE
My wallet has 0 balance, my chia is gone [BUG]

### ISSUE THREAD

**Issue by PatMateluna** [Chia-Network/chia-blockchain#6757]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by tydeno** [comment]
Is your wallet synced?

**Comment by PatMateluna** [comment]
I was able to get a new wallet address and sync that with my target addresses for Farmers and Pool rewards.. everything it’s ok 

Thank you so much !! 

Pat Mateluna.    Cell. (661)212-3704
Mateluna Productions
Producer / Director / Cinematographer 
Pat@MatelunaProductions.com
***@***.***
http://www.patmateluna.com


The information contained in this e-mail and any attached 
documents may be privileged, confidential and protected from 
disclosure. If you are not the intended recipient you may not 
read, copy, distribute or use this information. If you have 
received this communication in error, please notify the sender 
immediately by replying to this message and then delete it 
from your system.

**Comment by siaarzh** [comment]
> I was able to get a new wallet address and sync that with my target addresses for Farmers and Pool rewards.. everything it’s ok Thank you so much !! Pat Mateluna. Cell. (661)212-3704 Mateluna Productions Producer / Director / Cinematographer Pat@MatelunaProductions.com ***@***.*** http://www.patmateluna.com The information contained in this e-mail and any attached documents may be privileged, confidential and protected from disclosure. If you are not the intended recipient you may not read, copy, distribute or use this information. If you have received this communication in error, please notify the sender immediately by replying to this message and then delete it from your system.
> […](#)
> Sent from my iPhone
> On Jun 15, 2021, at 4:27 AM, tydeno ***@***.***> wrote: ﻿ Is your wallet synced? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

close the issue, please
