### ISSUE TITLE
eternal wallet loading[BUG]

### ISSUE THREAD

**Issue by mitya325** [Chia-Network/chia-blockchain#6760]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by mitya325** [comment]
win 10

**Comment by ramsesdeux** [comment]
Same issue here.

Please advise!

![image](https://user-images.githubusercontent.com/2408288/125109155-8fea6c80-e115-11eb-88d1-4b48bd98d491.png)
