### ISSUE TITLE
My wallet has 0 balance, I change my account from OS version

### ISSUE THREAD

**Issue by jan2025** [Chia-Network/chia-blockchain#6767]
I was having same issues with ubuntu 20 so I downgrade to 18. 
When I start the gui I have no Chias on my wallet!

What can I do?

What I do wrong?

This is very disappointing....

Thanks in advance!

**Comment by tydeno** [comment]
Is your wallet synced?

**Comment by jan2025** [comment]
not yet 138,784 over 433,975 in this very moment

**Comment by tydeno** [comment]
Maybe check your wallet balance using chiaexplorer.
If its still there, just wait for the sync.

**Comment by jan2025** [comment]
I'll wait for the full sync
I'll let you know what happens

Thanks your help!

**Comment by jan2025** [comment]
when sync was 80% Chias suddenly appear in to the wallet!
