### ISSUE TITLE
[BUG] Failed Plots on Mac M1

### ISSUE THREAD

**Issue by jooooooooooe** [Chia-Network/chia-blockchain#6769]
**Describe the bug**
I get failed Plots on my MacMini M1. Errors happen in various Phases and are not reproducible. Error rate is between 5-15%

**To Reproduce**

#1. Go to '...'
#2. Click on '....'
#3. Scroll down to '....'

**Expected behavior**

**Screenshots**
Error Message in Log:
	Bucket 123 uniform sort. Ram: 3.840GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
	Bucket 124 uniform sort. Ram: 3.840GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
	Bucket 125 uniform sort. Ram: 3.840GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
	Bucket 126 uniform sort. Ram: 3.840GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
	Bucket 127 uniform sort. Ram: 3.840GiB, u_sort min: 3.250GiB, qs min: 0.813GiB.
	Total matches: 4285665956
Caught plotting error: Matches do not match with number of write entries 4285665956 4285643839

**Desktop :**

- OS: MacOs 
- OS Version/Flavor: Big Sur 11.3.1
- CPU: M1 16 GB Ram

**Additional context**
Are these Errors related to the x86 Code on ARM? When can we expect a M1-Version?
The Mac is only used for plotting, bought it brand new. I'm not sure if the Mac ist faulty, defect Ram maybe?   Apple Hardwaretest ran without problems.

**Comment by jooooooooooe** [comment]
Updated the machine to Big Sur 11.4, seems to get worse. Since the update, 5 out of seven plots are failing. What I forgot to mention: I did update python, which was suggested (somewhere) due to the M1 Processor. Could that be related to my errors?

**Comment by mariano54** [comment]
It could be bad RAM or SSD

**Comment by jooooooooooe** [comment]
That was my second thought. Well, had a call with Apple Support, did the Hardware-test. Nothing to be found. I then removed the updated Python Version, and since then, I had only one failed plot, which might have happened, because there were too many plots in parallel, which exceeded my 8 threads. I'm still watching, right now plotting is pused until the official Pools are ready ;-)
There are so may test-tools available for other OSes, but I cant find any for MacOs. Do you know any tools?
