### ISSUE TITLE
[BUG] About Chia Blockchain version not showing in the Linux client.

### ISSUE THREAD

**Issue by vexr** [Chia-Network/chia-blockchain#678]
**Describe the bug**
About Chia Blockchain “version” environment variable not showing up in the Linux client. (1.0beta19)

**To Reproduce**
Help > About Chia Blockchain (shows 0.0) vs the Windows client showing 0.1.19 (1.0beta19)

**Comment by hoffmang9** [comment]
I'm going to close this as it's an enhancement request. Building the GUI directly means you aren't creating the installer - which is where you inject all of the nice bits like version and icon. We will create a multi-linux binary version too at some point - but most linux hacks are comfortable with the rougher ride.
