### ISSUE TITLE
[BUG] No more Block Challenges after a few hours

### ISSUE THREAD

**Issue by Spike22022** [Chia-Network/chia-blockchain#6798]
**Describe the bug**
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/6661010/debug.log)
System: Ubuntu 20.04
Client version: 1.1.7 (installed from Github and retry with client)

Device: HP Server

After sync, the system always runs stable for a few hours and then after some time still receives blocks but no longer triggers challenges. First I assumed that the GUI hangs but also from the logs it is obvious that no more challenges are executed.
I have attached the log accordingly.

The ports are all correctly released and there are no other harvesters on the system. The plots are connected via storages (Windows Server).

I have also completely rebooted the system after several attempts and even then this problem occurs.
It is also interesting that the client briefly loses connection to the server once every 3h during the night.

The system is operated via a UMTS stick.

If you need more info, just send me a short message and I will send you all the necessary info.

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85986401/122175413-f4ead380-ce83-11eb-8955-f9262ae0c8bb.png)

**Comment by sobertram** [comment]
Your issue might be you loose synch with the chain. I am on unix and this also happens time and again. I have setup a cron job to check every hour if im in sync and if not to restart the node. 

Here is my script:

#/bin/bash

. ~/chia-blockchain/activate
if [ -z "`chia show -s | grep "Full Node Synced"`" ]
then
   echo `date` "Not synched need restart"
   chia stop all -d
   chia start all
   echo `date` "Chia farming restarted"
else
   echo `date` "Node synchronized"
fi

I have it redirect the output to a file and below is what that looks like. This is all of Wednesday into today so you get an idea of how often it occurs. It's not uniform in it's occurrence and I have gone for more than 24 hours without a restart before. I am on 1.1.6 but i don't think it will be different for 1.1.7.

Wed 16 Jun 2021 12:30:04 AM EDT Node synchronized
Wed 16 Jun 2021 01:30:04 AM EDT Node synchronized
Wed 16 Jun 2021 02:30:03 AM EDT Not synched need restart
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '505a9ed804f05f23a75c31cd4c8d8791afd51f7900200472961a7a86df189147'}
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Wed 16 Jun 2021 02:30:25 AM EDT Chia farming restarted
connect: Connection timed out
connect: No route to host
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
Wed 16 Jun 2021 03:30:05 AM EDT Node synchronized
Wed 16 Jun 2021 04:30:04 AM EDT Node synchronized
Wed 16 Jun 2021 05:30:02 AM EDT Not synched need restart
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '680786ecb2a1da02c0cc819dfbe803bda2fc2730960671be877bcfb83efdf122'}
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Wed 16 Jun 2021 05:30:24 AM EDT Chia farming restarted
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: No route to host
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
Wed 16 Jun 2021 06:30:02 AM EDT Node synchronized
Wed 16 Jun 2021 07:30:03 AM EDT Node synchronized
Wed 16 Jun 2021 08:30:04 AM EDT Node synchronized
Wed 16 Jun 2021 09:30:03 AM EDT Node synchronized
Wed 16 Jun 2021 10:30:04 AM EDT Node synchronized
Wed 16 Jun 2021 11:30:04 AM EDT Node synchronized
Wed 16 Jun 2021 12:30:03 PM EDT Node synchronized
Wed 16 Jun 2021 01:30:02 PM EDT Node synchronized
Wed 16 Jun 2021 02:30:03 PM EDT Node synchronized
Wed 16 Jun 2021 03:30:05 PM EDT Node synchronized
Wed 16 Jun 2021 04:30:03 PM EDT Node synchronized
Wed 16 Jun 2021 05:30:05 PM EDT Node synchronized
Wed 16 Jun 2021 06:30:03 PM EDT Node synchronized
Wed 16 Jun 2021 07:30:05 PM EDT Node synchronized
Wed 16 Jun 2021 08:30:03 PM EDT Node synchronized
Wed 16 Jun 2021 09:30:04 PM EDT Node synchronized
Wed 16 Jun 2021 10:30:03 PM EDT Node synchronized
Wed 16 Jun 2021 11:30:04 PM EDT Not synched need restart
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': '420d6bd410f3f29b772ff855edad59ea2d434a5352d6b4aec4c8e17597d79aa5'}
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Wed 16 Jun 2021 11:30:26 PM EDT Chia farming restarted
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
Thu 17 Jun 2021 12:30:02 AM EDT Not synched need restart
daemon: {'ack': True, 'command': 'exit', 'data': {'success': True}, 'destination': 'client', 'origin': 'daemon', 'request_id': 'adeec5a2c06dcd33e3074e76e8c46b8d93df9ac1c7d265b1a34df843820436b8'}
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Thu 17 Jun 2021 12:30:12 AM EDT Chia farming restarted
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
Thu 17 Jun 2021 01:30:03 AM EDT Node synchronized
Thu 17 Jun 2021 02:30:03 AM EDT Node synchronized
Thu 17 Jun 2021 03:30:02 AM EDT Node synchronized
Thu 17 Jun 2021 04:30:02 AM EDT Node synchronized

**Comment by Spike22022** [comment]
Thank you for your comment. Im not familar with crome Jobs. I get "/tmp/crontab.AjploM/crontab":24: bad minute
errors in crontab file, can't install.
 
When i use your crone Job. Im Using Ubuntu 20.4 any ideas how to fix. It should be a nice Workaround for me. BUt i hope they will fix the bug soon.
Thank you for your time Sir!

**Comment by sobertram** [comment]
Sure. i use this site to make sure my entry matches what i want to do.
https://crontab.guru/

To do every hour at the top of the hour, https://crontab.guru/#0_*_*_*_*

So the script i gave you, you want to create a file with that contents and then make an entry in crontab like this:

0 * * * * /location_of_script/script >> /some_location/script.log 2>&1

">>" appends to the log file. "2>&1" redirects error and standard output to the log file.

so add:
#/bin/bash

. ~/chia-blockchain/activate
if [ -z "`chia show -s | grep "Full Node Synced"`" ]
then
echo `date` "Not synched need restart"
chia stop all -d
chia start all
echo `date` "Chia farming restarted"
else
echo `date` "Node synchronized"
fi

to a file, make it an executable, "chmod +x <script>" and then add the cronjob above, "crontab -e" and you should be set.

**Comment by Spike22022** [comment]
Thank you very much , but finall I get zero challenges. SYstem is synced Job is running but no challenges are accepted 
Chia makes me crazy 2k Plots an nothing is working.

you have  some ideas how to fix it ?

**Comment by sobertram** [comment]
Why do you think you aren't getting any challenges? Run this command it should show you the current challenges if you are synched. (not the exact ones i am showing here but you should get 20 challenges).

$ chia farm challenges
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 47
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 46
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 45
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 44
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 43
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 42
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 41
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 40
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 39
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 38
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 37
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 36
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 35
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 34
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 33
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 32
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 31
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 30
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 29
Hash: 0x17becedc0283f0ddce8c387ba585d52019256733483abb4148a3f60c9550c4d3Index: 28

Use the explorer to see what the latest block is:
https://www.chiaexplorer.com/blockchain/blocks

and then run "chia show -s" and your latest block should be same or close to the block in the explorer. if that is the case you should be getting challenges.

Your log file should also show the following: (turn debug on in your log).
in ~/.chia/mainnet/config/config.yaml
farmer:
  full_node_peer:
    host: localhost
    port: 8444
  harvester_peer:
    host: localhost
    port: 8448
  logging: &id001
    log_filename: log/debug.log
    **log_level: DEBUG**

If it wasn't set before you need to restart to pick up the log level change. you should then see:

$ grep eligible debug.log
2021-06-18T18:39:17.780 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 2fca096532... Found 0 proofs. Time: 0.17000 s. Total 188 plots
2021-06-18T18:39:28.511 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 2fca096532... Found 0 proofs. Time: 0.00471 s. Total 188 plots
2021-06-18T18:39:37.030 harvester chia.harvester.harvester: INFO     1 plots were eligible for farming 2fca096532... Found 0 proofs. Time: 0.08246 s. Total 188 plots

Also
$ grep challenge debug.log
2021-06-18T18:48:29.530 full_node chia.full_node.full_node: INFO     Signage point 20 not added, CC challenge: 37b905b71c3e6e564f58adcb4b257f19f1973fcf01440dea054d44015d99a54a, RC challenge: 03db469f8982cc40f02b4969c5d3bb004ef389f86941cf952843a7229e662a3b
2021-06-18T18:48:29.640 full_node chia.full_node.full_node: INFO     Signage point 20 not added, CC challenge: 37b905b71c3e6e564f58adcb4b257f19f1973fcf01440dea054d44015d99a54a, RC challenge: 03db469f8982cc40f02b4969c5d3bb004ef389f86941cf952843a7229e662a3b

If you are synched and not getting challenges then that is another issue that i have not encountered or know how to resolve.

**Comment by Spike22022** [comment]
Hi my friend,
thank you for your time and ideas.
Finally i have installed it to my second server and it is working BUT. the disconecction every 1-2 hours still alive but with the script i'm able to recover and it is working then .
But the disconects suck also but i have no idea why connection is lost. 
Internet is still fine and my other Ether Farming is working all the time. 
Maybe some problem with the Chia Servers.
Im looking forward that they fix the Server problem with the new patch maybe! 

Thank you!

**Comment by sobertram** [comment]
No worries. Also check you cpu usage. I have noticed as well that when cpu usage is very high, less than 20% idle, it affects the node and throw's it out of synch.

Good luck.
