### ISSUE TITLE
Disappearance of the money I had in the Wallet even if it was reinstalled with the seeds

### ISSUE THREAD

**Issue by alegomcor** [Chia-Network/chia-blockchain#6809]
My computer is a PC with an AMD Ryzen 5 processor and I work on Windows.
After problem to stop detecting the Parcels. I reinstall everything from the seeds. But the money he had accumulated through the Faucets is gone. My deposit address has changed. How can that happen if I log in with my seeds? How do I recover the money I had in my Wallet?

**Comment by night-lurker** [comment]
Wallet is fully synced ?

**Comment by alegomcor** [comment]
If it is completely synchronized. But even so, the Chia that he had still does not appear.

**Comment by alegomcor** [comment]
> ¿Wallet está completamente sincronizado?

If it is completely synchronized. But even so, the Chia that he had still does not appear.

**Comment by Hardcore-fs** [comment]
This can happen if you start chia from a different account or different directory....
it fails to pick up the correct ".chia" directory and so rebuilds it.
