### ISSUE TITLE
China wallet acceptance address

### ISSUE THREAD

**Issue by tracy32792** [Chia-Network/chia-blockchain#6829]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/6826

<div type='discussions-op-text'>

<sup>Originally posted by **tracy32792** June 17, 2021</sup>
Click the new address under the receipt address of Chia wallet, which causes the wallet receiving address to change. How can he change it to the original wallet receiving address before？</div>

**Comment by mariano54** [comment]
to get the original address, do `chia keys show` on the command line. Otherwise you can keep using newer addresses, they are all controlled by the same wallet.
