### ISSUE TITLE
[BUG] Estado del Nodo Completo, Estado nunca termina de sincronizarse, siempre 2 horas y llevo semanas.

### ISSUE THREAD

**Issue by Tuchominer** [Chia-Network/chia-blockchain#6835]
Buenas a todos.

Tengo un problema grave de sincronización que véo que es problema del programa, pues tengo fibra de 1000 Mb/seg simetrica, PC con 32 Gb de RAM, un procesador de 16 nucleos, un m.2. para archivos temporales y 2 discos de 8 Tb disponibles y nunca termina de sincronizar.

La primera vez que instalé el programa, se sincronizó todo perfectamente, mantengo el PC siempre encendido, 24 horas., pero hace unas 2 o 3 semanas, empezó a desincronizarse solo, cuantas más parcelas creaba, peor era la sincronización, llegando al punto de decirme que no estaba sincronizado, y no hay manera de sincronizar, he probado a parar la creación de parcelas y tampoco, llega siempre a estar a casi 2 horas a falta de finalizar, por ejemplo, ahora son las 20:30, pues está sincronizado a las 18:11 minutos...., y cuando sean las 22 horas, la sincronización se ajusta a las 20 horas o así.

Tambien he probado a cerrar el programa y volver a encenderlo asegurandome de haberlo cerrado completamente y consigue sincronizarse pero se queda a unas 2 horas para llegar a finalizar y nunca finaliza la sincronización.

¿Alguien sabe o conoce alguna solución a este problema?, pues estoy minando parcelas sin obtener ningún beneficio mientras la dificultad no para de subir y a cada día que pasa desincronizado, dejo de ganarle.

He de decir, que tengo 87 parcelas por el momento y subiendo a cada día que pasa, pero es que no he recibido ni 0,00000001 Chia desde que empecé a minar hace casi 1 mes.

Gracias.
-----------------------------------------------------------------------------------------
Good morning everyone.

I have a serious synchronization problem that I see as a problem with the program, because I have a 1000 Mb / sec symmetric fiber, a PC with 32 Gb of RAM, a 16-core processor, a m.2. for temporary files and 2 disks of 8Tb available and never finish syncing.

The first time I installed the program, everything was perfectly synchronized, I keep the PC always on, 24 hours, but about 2 or 3 weeks ago, it began to desynchronize itself, the more plots it created, the worse the synchronization, reaching the point of Tell me that it was not synchronized, and there is no way to synchronize, I have tried to stop the creation of plots and neither, it always reaches almost 2 hours in the absence of finishing, for example, now it is 20:30, as it is synchronized at 18:11 minutes ...., and when it is 22 hours, the timing is adjusted to 20 hours or so.

I have also tried to close the program and turn it on again making sure I have closed it completely and it manages to synchronize but it takes about 2 hours to finish and the synchronization never ends.

Does anyone know or know any solution to this problem? Well, I am mining plots without obtaining any benefit while the difficulty does not stop rising and with each day that passes out of sync, I stop beating it.

I have to say that I have 87 plots at the moment and going up every day, but I have not received 0.00000001 Chia since I started mining almost 1 month ago.

Thanks.

**Comment by IgnaciusMaximus** [comment]
Tienes tu computador con la hora sincronizada al reloj mundial?
