### ISSUE TITLE
needed help for plots

### ISSUE THREAD

**Issue by basunjoy3849** [Chia-Network/chia-blockchain#6838]
all my plots are showing this what to do
![Screenshot 2021-06-18 001832](https://user-images.githubusercontent.com/83465336/122458450-6f733a80-cfcd-11eb-992b-bd27e1a542be.png)

**Comment by matrix101** [comment]
Your plots were created by a private key that is not imported in your private keys list.

Use: `chia keys add`  to add your mnemonic seed

**Comment by luckynickell89** [comment]
> Your plots were created by a private key that is not imported in your private keys list.
> 
> Use: `chia keys add` to add your mnemonic seed

in powershell>? command line? i have this same issue but i have never made a new key. ive had the same 24 words and same keys since the day i installed the gui.
