### ISSUE TITLE
Can't add additional folders in plot folders to Chia

### ISSUE THREAD

**Issue by OvalPiston** [Chia-Network/chia-blockchain#6846]
After about 10 folders of approx 40 chars for each folder, I tried adding another plot folder in the GUI, and also from the command line. 

Both ways didn't let me add a plot

It seems once the character count of all the plot folder names exceeds about 400 characters, you can't add any more.

Please fix this so I can add more folders. Suggestion: make it 8192 or some value that won't "ever" be exceeded.

Thank you.

**Comment by kozalat** [comment]
+1

**Comment by OvalPiston** [comment]
Is this fixed yet?
