### ISSUE TITLE
INTERFACE AND SYNC

### ISSUE THREAD

**Issue by Jakops6** [Chia-Network/chia-blockchain#6852]
Hello there
Although I reinstalled your program many times and installed the current version, the interface still does not update, I have a synchronization problem and my plots are not visible in the farm section, can you help?
![1](https://user-images.githubusercontent.com/67397547/122594964-68513880-d070-11eb-87e4-f644a9f17430.png)
![2](https://user-images.githubusercontent.com/67397547/122594969-68e9cf00-d070-11eb-992a-e9a135ef386d.png)
![3](https://user-images.githubusercontent.com/67397547/122594971-6a1afc00-d070-11eb-984a-3ebc51517026.png)

**Comment by mariano54** [comment]
You will need to delete your ~/.chia folder and reinstall, looks like a corrupt DB.
