### ISSUE TITLE
chia wallet 0 [BUG]

### ISSUE THREAD

**Issue by gwa1972** [Chia-Network/chia-blockchain#6856]
**Describe the bug**
chia wallet shows 0 coins despite chiaexplorer show coin rewards 

![chiaexplorer coins](https://user-images.githubusercontent.com/85962464/122614982-90bf3f80-d03c-11eb-8ab8-8422a2f679a9.jpg)
![wallet 0 on gui](https://user-images.githubusercontent.com/85962464/122614984-91f06c80-d03c-11eb-844a-a5ae44800690.jpg)
![wallet](https://user-images.githubusercontent.com/85962464/122614986-92890300-d03c-11eb-8a82-f8c5a30e710e.jpg)
wn to '....'

**Expected behavior**
how can I solve this problem? I'm using chia 1.1.7 on windows 10, hotspot wifi, laptop ryzen 5 16gb + ssd

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by joelrb** [comment]
If you're not yet fully synced just wait. If already synced, try sending some mojos, use get from faucets. This happened to me too. Only when I received some mojos that the GUI got refreshed. A GUI bug for sure nothing to worry as it's in the blockchain.

**Comment by gwa1972** [comment]
thank you joelrb. but i'm not expert, could you please explain in detail how to send mojos and faucet???
thank you for your kind feedback

**Comment by joelrb** [comment]
> thank you joelrb. but i'm not expert, could you please explain in detail how to send mojos and faucet???
> thank you for your kind feedback

Select from here to send mojos to your wallet... https://chialinks.com/faucets/

**Comment by gwa1972** [comment]
joelrb I tried as per your instruction and I have received mojo, I hope that chia wallet refresh because I have XCH farmer rewards that I would see in the wallet. Do you think that is necessary reboot the computer? or just wait.
Thank you again.
p.s. If you agree, I will send to you some xch, when pronblem is solved
 

![mojo received](https://user-images.githubusercontent.com/85962464/122645810-1ee50580-d0d1-11eb-8e66-b8824c930724.jpg)

**Comment by gwa1972** [comment]
@github sorry I forgotten  I will read again contributing guideline and code of conduct and if possible I will contribute to @github.
Please allow discussion on progress with Joelrb

**Comment by gwa1972** [comment]
@joelrb I tried as per your instruction and I have received mojo, I hope that chia wallet refresh because I have XCH farmer rewards that I would see it in the wallet. Do you think that is necessary reboot the computer? or just wait.
Thank you again.

**Comment by gwa1972** [comment]
@github  I have read contributing guide line and code of conduct. I apologies, I was in good faith offering contribution, I will never do this behavior please allow me to continue solve the problem that I have: chia wallet 1.1.7 does not show any farmed plot rewards, no coins xch are showed in my wallet except emoji from faucet. Chia explorer.com show me coins and rewards what I have to do to solve this problem?

**Comment by gwa1972** [comment]
@joelrb today I received emoji from faucet but my wallet still 0 coin xch do you have other idea?

**Comment by pinnedjoint** [comment]
I have the same problem. the "mojdo: dolution didn't work!!

**Comment by joelrb** [comment]
Fully synced? Wallet still has the XCH by searching through ChiaExplorer?
Try another computer. Install Chia, enter your mnemonic and wait for full
sync.

**Comment by gwa1972** [comment]
Thank you I will try
--
Inviato da Libero Mail per Android domenica, 20 giugno 2021, 05:20PM +02:00 da Joel Ballesteros  ***@***.*** :

>Fully synced? Wallet still has the XCH by searching through ChiaExplorer?
>Try another computer. Install Chia, enter your mnemonic and wait for full
>sync.
>

**Comment by gwamendola** [comment]
@joelrb I have installed in a new computer chia 1.1.7 but still sinch wallet show 0 xch
I dont know what to do. May be some previous release of chia is better?

**Comment by FrysCrypto** [comment]
I am currently having this issue, not sure why
