### ISSUE TITLE
Chia crashing during plotting [BUG]

### ISSUE THREAD

**Issue by Abremalin** [Chia-Network/chia-blockchain#6861]
**Describe the bug**
Chia crashes. I've only seen this happen twice. 

**To Reproduce**

Run Chia.
Plot 32 plots with 4 nvme 2TB drives. 70 minute delay. 4 threads per plot.  
(This is the same thing I do every time. Out of multiple successes, I've seen 2 crashes.

**Expected behavior**
I expect it to complete the plots so I can start more up.

**Screenshots**
Not applicable. 

**Desktop (please complete the following information):**

- OS: Windows 10 64 bit
- CPU: AMD Ryzen Threadripper 3960X 24-Core Processor 3.80 GHz
- RAM: 64 GB

**Additional context**
Nothing else is running except Chia. When Chia crashes, it is only Chia. Windows stays running.

**Comment by remssx** [comment]
hello i have a blue sreen in windows 10 64 during the file compression phase can you help me please

**Comment by remssx** [comment]
OS: Windows 10 64 bit
CPU: i7 8700k
RAM: 32GB

**Comment by remssx** [comment]
Plot k32 plots with 2 nvme 1TB

**Comment by mariano54** [comment]
Check your RAM for errors. Also it could be an SSD hardware issue, try a different SSD
