### ISSUE TITLE
My plots disappeared[BUG]

### ISSUE THREAD

**Issue by Lumturii** [Chia-Network/chia-blockchain#6863]
**Describe the bug**
My plots disappeard. I have 220 plots but chia app can't see it. 2 days ago i restart my chia, after this i have no plots but my HDD disk has this plots. I tried to reinstall it, add a plot directory. Install older version, or wait some time, but still nothing. Could sb help me please?

**Screenshots**

**Desktop (please complete the following information):**

- OS: [WINDOWS]
- OS Version/Flavor: [10 pro]
- CPU: [Intel core i5 10th 10400f]

**Additional context**

**Comment by Alekssander85** [comment]
WINDOWS
10 PRO
Intel(R) Xeon(R) CPU E5-2678 v3
![Снимок](https://user-images.githubusercontent.com/86187746/122670513-2557a800-d1cb-11eb-8f24-2710c04f60e8.PNG)

**Comment by adrsc200** [comment]
na pasta confg dentro dos arquivos da .CHIA  tem 2 blocos de notas ,eu exclui e abri o app CHIA  ,add os lotes e apareceram novamente.
