### ISSUE TITLE
[BUG] Plot within several seconds is now available, will the project go dead?

### ISSUE THREAD

**Issue by potato1992** [Chia-Network/chia-blockchain#6874]
see https://github.com/achow1o1/chia-plotter, plot with GPU, it is already proven that plot can be made within 10 seconds, I believe the first phase even takes less time than that.

Thus, as the [issue](https://github.com/Chia-Network/chia-blockchain/issues/6710) claimed, is it possible for someone to do the plot in real-time using the challenge hash as input, and take away every coin?

If so, we no longer need any HDD, it's just a race of GPU investment.

**Comment by VercauterenK** [comment]
Has anyone bought the software. Is there proof of it working?

**Comment by Elentary** [comment]
There is no proof, another scam I guess

**Comment by ekkkkki** [comment]
ProofOfSpace Algorithm is rigorous. GPU plotting is just cheating themselves and can earn no reward from mainnet.
But hard to say whether those Plots can cheat the mining pool...

**Comment by potato1992** [comment]
> ProofOfSpace Algorithm is rigorous. GPU plotting is just cheating themselves and can earn no reward from mainnet.
> But hard to say whether those Plots can cheat the mining pool...

See https://www.chia.net/assets/Chia_Proof_of_Space_Construction_v1.1.pdf, the grinding attacks section. It's not self-cheatting, the guy who can generate the plot within 30 seconds (if possible) will have the ability to take away every coin. 

That's why K=32 is the minimal requirement.

**Comment by never-afk** [comment]
I do not believe it.

**Comment by gromran** [comment]
its a fake/scam...

**Comment by ubearline** [comment]
Don't let too many people know please

**Comment by watler-peng** [comment]
Who tested it ？
