### ISSUE TITLE
Plotting software could not recover from temporary loss of a network/shared drive

### ISSUE THREAD

**Issue by joelrb** [Chia-Network/chia-blockchain#6876]
**Describe the bug**
Plotting from a Mac and writing final file to another pc via a shared network folder.

I inadvertently restarted the other machine where the plot is to be written to. But Chia software could not reconnect to the shared drive although it is already accessible via Mac Finder after the machine has been restarted.

Adding the shared drive to plot directory did not fix the issue.

**To Reproduce**
Plot in Mac.
Add final plot directory from a shared folder of another pc.

**Expected behavior**
Chia software should be able to reconnect to shared network drive where the plot is to be written.

**Screenshots**
Log of plot showing error connecting to the shared network drive.
![Screen Shot 2021-06-21 at 12 24 15 PM](https://user-images.githubusercontent.com/225284/122707646-015c9b00-d28d-11eb-803d-be30db2c8da1.png)

The pc with the shared network drive has been restarted. I am already able to connect to it via Mac Finder (file explorer). Still Chia software is looking for the network drive and cannot locate or connect to it.

![Screen Shot 2021-06-21 at 12 27 34 PM](https://user-images.githubusercontent.com/225284/122707734-2ea94900-d28d-11eb-94bd-e915e76f6cba.png)

**Desktop (please complete the following information):**

- OS: Mac OS (plotter) ... Ubuntu (drive share)
- OS Version/Flavor: Big Sur, Ubuntu 20.04
- CPU: 

**Additional context**
Simple issue that Chia team should be able to resolve immediately.

**Comment by LoudSyncro** [comment]
Could be realted 7 connected to bug:
[[BUG] plotfiles not available for farming when a mapped drive is missing #1759](https://github.com/Chia-Network/chia-blockchain/issues/1759)
