### ISSUE TITLE
One wallet syncs, other one doesn't - bug

### ISSUE THREAD

**Issue by engine-off** [Chia-Network/chia-blockchain#6880]
I've installed the Chia GUI on my RP4 running Ubuntu.  The main wallet syncs fine, and the Full Node Status is Synced.  If I click on my secondary wallet, the Full Node Status still says synced, but the wallet says Not Synced, Height=0, Connections=1.  It doesn't seem to matter what I do, I have deleted the old wallets and created new ones, but only the original wallet will sync.  What's going on here?

I have also tried to delete the sqlite.shm and sqlite.wal files but that didn't help either.  I don't want to delete the main sqlite file because it's 5GB and will take probably a week or 2 on the pi to re-sync.  Port 8444 is definitely open.

**Comment by mariano54** [comment]
You can only sync one Key at a time. If you log in to your second wallet, you will need to wait for it to sync. Sometimes it takes 10 minutes to start syncing.

Alternatively, it might be something wrong with the full node. If you could provide more details from the error log file, that might be  useful `~/.chia/mainnet/log/debug.log`
