### ISSUE TITLE
Requesting Help Testing Potential Chia GUI Bug in Testnet?

### ISSUE THREAD

**Issue by Jrschellenberg** [Chia-Network/chia-blockchain#6886]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/6365

<div type='discussions-op-text'>

<sup>Originally posted by **Jrschellenberg** June  2, 2021</sup>
I was sending a Transaction a couple of days ago using the Chia GUI Version 1.1.5 on Windows 10

![Screenshot 2021-06-02 155713](https://user-images.githubusercontent.com/6064137/120551049-3925a080-c3bb-11eb-9308-e17f16f78e12.png)

I had 4.00000005 Chia in my Wallet

I Set the transaction to be

Transaction: 3 XCH    Fee: 0.00000001

However, When the Transaction went through, it Sent 1 XCH as a Transaction Fee instead.

Now in my mind, it's either:

A.) Human Error
B.) a Bug

So looking to see if someone may help me Replicate this issue in TestNet

![Screenshot 2021-05-30 202655](https://user-images.githubusercontent.com/6064137/120551407-9c173780-c3bb-11eb-9c57-0f6fae4aed7a.png)

The Transaction is on the Network, I tracked down the TX here:

https://www.chiaexplorer.com/blockchain/block/0x3656cf2bfa1cca85bb1ece3ba884db076ac844ae93f06f38c60cfcb8723328f7

Steps to Replicate:

1.) Windows 10 OS
2.) Download Chia GUI 1.1.5
3.) Have 4.00000005 or Greater in Wallet
4.) Send a TX of 3 XCH with a Fee blank
5.) Receive UI Feedback saying fee requires Numeric input
6.) Enter Fee of 0.00000001
7.) Click Send

I figured it is better to be safe than sorry, as I have seen another Tx's gone through with high fee's

![Screenshot 2021-06-02 160244](https://user-images.githubusercontent.com/6064137/120551790-08923680-c3bc-11eb-8e8f-040ed0f810c9.png)

I do hope it's Human error on my part. But I do check the TX's I send 5-10x before sending them as I know once it's sent, if it's gone, it's gone and I feel confident that I had 0.00000001 set in the Fee field. 

If it is a bug, Could possibly be a floating-point precision error but before going down that Avenue, would like to see if this issue can be at least replicated!

Thank you for any Help Support you may be able to provide!

</div>

**Comment by Jrschellenberg** [comment]
potential duplicate of


#4871
#6550

**Comment by mariano54** [comment]
I don't think this is a bug. This has been thoroughly tested and the fee provided in that field is what is used.
I'm sorry but those coins cannot be recovered. We definitely need to add a confirm screen and warn if fee is too large: https://github.com/Chia-Network/chia-blockchain-gui/issues/357
