### ISSUE TITLE
Chia stuck in connecting wallet then crashes[BUG]

### ISSUE THREAD

**Issue by Azerione** [Chia-Network/chia-blockchain#6889]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: intel i5 3rd gen

**Additional context**

**Comment by mariano54** [comment]
Duplicate of https://github.com/Chia-Network/chia-blockchain/issues/6993, please check that issue
