### ISSUE TITLE
App is blank[BUG]

### ISSUE THREAD

**Issue by Azerione** [Chia-Network/chia-blockchain#6891]
![Chia Window](https://user-images.githubusercontent.com/86253772/122808237-ae5f0400-d2dd-11eb-84c8-551260422f50.PNG)
![Chia Window 2](https://user-images.githubusercontent.com/86253772/122808259-b8810280-d2dd-11eb-8f63-77274e8ac7d4.PNG)
![windows](https://user-images.githubusercontent.com/86253772/122808275-bd45b680-d2dd-11eb-9572-1eaaf4a446ee.PNG)

**Comment by Azerione** [comment]
I have de-installed and reinstalled but no luck.

**Comment by marcostraderminer** [comment]
O meu fica somente carregando e nao aparece minha fazenda de mineração

**Comment by Azerione** [comment]
Hi anyone here for a solution my farm is already 1 day down?

**Comment by thunka81** [comment]
for me the same for 1 computer from 3pcs

**Comment by mariano54** [comment]
Can you look at the file `~/.chia/mainnet/log/debug.log` and see if any errors show up there when you start the application?

**Comment by szarkivach** [comment]
Had same issue. Just delete the whole chia blockchain folder which includes the GUI folder and reset computer then reinstall from scratch worked for me
