### ISSUE TITLE
sent transaction was pending, but explorer was confirmed

### ISSUE THREAD

**Issue by coboywei** [Chia-Network/chia-blockchain#6909]
1,i sent a transaction, it is pending in my wallet as follows:
Transaction 8ac76efa3b860fff755e252cf98587948dd3b42a4176d74579c42a57e0d2e5c3
Status: Pending
Amount: 0.2 xch
To address: xch17ev5mcp5c8me9kd8jzwzlt2f6gqndrfp56hnncmke55m2xu7zkdqajfsy3
Created at: 2021-06-21 19:00:14

2, but it is confirmed in explorer:
https://www.chiaexplorer.com/blockchain/address/xch17ev5mcp5c8me9kd8jzwzlt2f6gqndrfp56hnncmke55m2xu7zkdqajfsy3

i don't know why, and what to do next

**Comment by mariano54** [comment]
There is an issue with stuck pending transactions. The only way to fix this right now is to delete your wallet DB (files under `~/.chia/mainnet/wallet/db`. However this will have a better fix in the next release.
