### ISSUE TITLE
Plots show as invalid when using Temp Dir 2[BUG]

### ISSUE THREAD

**Issue by virgiltu** [Chia-Network/chia-blockchain#6918]
**Describe the bug**
For the longest time I used only directory 1 for temp and than send the plot to the final destination. I added more drives for "staging" and now I use the Temp1 and Temp2 directory option in the GUI and than move to the final directory. However out of 26 plots only 4 were valid. the rest of 22 plots show as invalid. 

The error for plot check is 

invalid plot header magic 

I stopped using the Temp2 directory and it all works ok again. The issue has to be with this Temp2 option. 

**Desktop (please complete the following information):**

- OS: Ubuntu Mint 20.4
- CPU: Latest version of the Chia UI

**Comment by gromran** [comment]
it works fine. The problem is of your side/hardware.

**Comment by mariano54** [comment]
yes, please check RAM, SSD, hdd, you probably have a faulty component
