### ISSUE TITLE
Problem with config.yaml file[BUG]

### ISSUE THREAD

**Issue by merwisgsd** [Chia-Network/chia-blockchain#6928]
I can't add none plot directory everything was working just fine yesterday and today I woke up and realese that my Chia client it's not Farming because don't have any plot directory added and gave me this message, no matters if I pick another disk with any fold that I choose I seee this message.

![Screenshot_2](https://user-images.githubusercontent.com/85741292/123036553-8e1e6a80-d3ed-11eb-85cf-4a394b95f7a2.png)

**Comment by joelrb** [comment]
Close Chia GUI. Edit config.yaml. Remove the directories under plot_directories:

Or fix them like:
plot_directories:
  - /Volumes/Disk1/plots
  - /Volumes/Disk2/Plots

Above is for linux/mac. If you're on Windows then do c:/folder1/plots

Then restart Chia GUI.

**Comment by mariano54** [comment]
Thank you for the fix. @joelcho
