### ISSUE TITLE
my wallet status is not synchronized, please help synchronize the wallet ...

### ISSUE THREAD

**Issue by Stalker0691** [Chia-Network/chia-blockchain#6959]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by mariano54** [comment]
Please provide more details and make a new issue, or check:
https://github.com/Chia-Network/chia-blockchain/issues/6993
