### ISSUE TITLE
[BUG]The node is not synced

### ISSUE THREAD

**Issue by tyinsomnia** [Chia-Network/chia-blockchain#696]
The node is not synced,Not Synced

1.Start Chia
2.Add Plots
3.Status Not Synced, but can see Blocks and Connections
4.Farming Status is Error

- OS: Win10
- node 12.13.0
- Chia 0.1.19

**Comment by hoffmang9** [comment]
Blockchain stall from ~4AM PST to 20:00 PST 1/16

**Comment by krispipeleers** [comment]
Still having this issue today. Height keeps going up, but node status is still saying Not synced.
Connection status = connected

OS: Win10
node 12.13.0
Chia 0.1.20
