### ISSUE TITLE
How do I get all transaction hashes from the block?

### ISSUE THREAD

**Issue by luis360** [Chia-Network/chia-blockchain#6968]
I need to scan each block, and then get the transaction of each block, but I found that the data returned by get_block does not have the hash of each transaction.
How do I get all transaction hashes from one block?

**Comment by gromran** [comment]
there are blocks and tx_blocks
"is_transaction_block"

**Comment by mariano54** [comment]
There are no transactions in chia, only removed and added coins. You can use `get_block_additions_and_removals` RPC
