### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '%user%\\.chia\\mainnet\\config\\ssl\\wallet\\public_wallet.crt'

### ISSUE THREAD

**Issue by fullet-tortuga** [Chia-Network/chia-blockchain#6978]
Actually, the whole "wallet" directory is missing under "ssl".

Found in version 1.1.7. both after upgrade or clean install when executing "start_wallet.exe".

**Comment by mariano54** [comment]
Can you try uninstalling and reinstalling chia?

**Comment by fullet-tortuga** [comment]
My fault, clean install meant deinstall + install.

**Comment by emlowe** [comment]
Closing issue

**Comment by fullet-tortuga** [comment]
Yo can't close an issue that is not fixed.

**Comment by emlowe** [comment]
My mistake, I believe your earlier comment "My fault..." meant that there wasn't really an issue

**Comment by fullet-tortuga** [comment]
No worries, my message was indeed prone to confusion. Thanks :-)
