### ISSUE TITLE
[BUG/Support] Chia rewards dont add up

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#6982]
**Describe the bug**
The [English FAQ](https://www.chia.net/faq/) of the Webpage states:

> After the Chia pre-farm, Chia offers farming rewards of 64 chia every 10 minutes. Over the first 12 years the farming rewards will be halved at the end of each 3rd year. From year 13 to infinity, the rewards will remain constant at 4 chia every 10 minutes leading to ever decreasing inflation rates. Chia’s inflation falls through the 0.50% rate 22 years after mainnet launch.

The [German FAQ](https://www.chia.net/de/faq/) States (Translated):

> After the Chia pre-farm, Chia offers agricultural rewards of 16 chia every 5 minutes. For the first 15 years, the farming rewards are halved at the end of every 5th year. From the 16th to the Infinite Year, rewards remain constant at 2 chia every 5 minutes, resulting in lower and lower inflation rates. Chia inflation drops by 0.50% 42 years after the start of the mainnet.  

Meanwhile, I recognize rewards of two (2) chia per 18.75 seconds. How does that add up?

**Comment by Plopsi** [comment]
10min with a 2 XCH every 18.75s are 64 XCH within 10min. The FAQ explanation is a bit misleading and the german FAQ ist totally out of sync (pun intended).

**Comment by mariano54** [comment]
Yes, the german is out of date.
