### ISSUE TITLE
Weird harvester error with no explanation of error[BUG]

### ISSUE THREAD

**Issue by number435398** [Chia-Network/chia-blockchain#6989]
harvester chia.harvester.harvester: ERROR    File: XXX Plot ID: XXXX challenge: e2f6d2804ea943cb8091435d6e00aa5a13d9f4b59b2f0973964d1c570aa72af4, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0xffff9db79930>, pool_public_key=<removed>, pool_contract_puzzle_hash=None, plot_public_key=<removed>, file_size=108824636642, time_modified=1623558123.9414935)

I discovered this in my log file. I don't see any description of what the actual issue is.  This is running on a raspberry pi 4 w/ gui in ubuntu.

**Comment by mariano54** [comment]
This happens when a lookup fails. most likely that is a faulty plot. If you get that again for that plot, you can delete it.

**Comment by number435398** [comment]
Shouldn't that reflect in the GUI as an invalid plot?
