### ISSUE TITLE
`chia configure` doesn't show the latest options

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#699]
I pulled down 1.0b21 and tried to start up the GUI, and noticed it was stuck at loading the wallet forever, as mentioned in https://github.com/Chia-Network/chia-blockchain/issues/694

I check the logs and saw:

> 03:38:40.911 wallet src.wallet.wallet_node     : INFO     Loop start in sync job
> 03:38:40.911 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 58444}
> 03:38:40.912 wallet wallet_server              : INFO     Connecting: wss://127.0.0.1:58444/ws, Peer info: {'host': '127.0.0.1', 'port': 58444}
> 03:38:40.924 wallet wallet_server              : WARNING  Cannot connect to host 127.0.0.1:58444 ssl:<ssl.SSLContext object at 0x7f4abdcbe340> [Connection refused]
> 03:38:41.552 full_node src.server.upnp         : INFO     UPnP failed. This is not required to run chia, but it allows incoming connections from other peers.

I figured it had to do with the new UPnP setting, so I tried to find it in list of configure arguments, but it did not show up by default. It appears that the new info on setting UPnP only shows up when `--help` is passed to it.

![2021-01-17_03-52](https://user-images.githubusercontent.com/8990544/104837199-94c21800-5878-11eb-9fe1-15819f1a1adf.png)

After setting `chia configure --enable-upnp True`, I started up the GUI and the wallet connected right away.

**Comment by hoffmang9** [comment]
That was a fluke as uPnP didn't have anything to do with connecting to wallet or not.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-this-upnp-error
