### ISSUE TITLE
I transferred the coins to my first wallet address, but get_wallet_balance cannot get the balance

### ISSUE THREAD

**Issue by luis360** [Chia-Network/chia-blockchain#6990]
chia keys show
Showing all public keys derived from your private keys:

Fingerprint: 301783476
Master public key (m): 80920f0eaf3e9a2e2f494533bbdb25a380e469ae81fc2ee32a20ebded8c9be70fab20074efa036709ef198ed2607747c
Farmer public key (m/12381/8444/0/0): 865d117732a71af0a75ab04ec887684bb077f17d2f7fb38d42b014b840e4400219ac43a58e8c7c84ae359a71d0eae986
Pool public key (m/12381/8444/1/0): 84b36d1be122638772d1fe3d0b47f415a906df0907f5f817a325077357379b668313175cafc5c31c941d93fae706031e
First wallet address: xch1zlf3kwc7ky2he38tz252pjsys4jpwat4w0yglde9rk2939sqgskqme9aap

signed_tx:
{
  signed_tx: {
    additions: [ [Object] ],
    amount: 19460000000,
    confirmed: false,
    confirmed_at_height: 0,
    created_at_time: 1624693175,
    fee_amount: 0,
    name: '0x785cdc8407f34a561c51d9cfe166a0d48e04674d5790dd90eff7700b178c37ed',
    removals: [ [Object] ],
    sent: 0,
    sent_to: [],
    spend_bundle: {
      aggregated_signature: '0xa6f8c6995257afed599b2a7c906c02c4f8d0836ca05fe1f40f0fa3a735b69e3459753c8753c5dd28134bfa7b5eee68de19d8de399833930ca2eb7220d4311ea4ca16e8be9a8ac8a0c3cc9996f6c7abb7795e817a7b536a32c9c124ea38177857',
      coin_solutions: [Array]
    },
    to_puzzle_hash: '0x17d31b3b1eb1157cc4eb12a8a0ca04856417757573c88fb7251d94589600442c',
    trade_id: null,
    type: 1,
    wallet_id: 1
  },
  success: true
}

![image](https://user-images.githubusercontent.com/38502473/123506741-669efa80-d698-11eb-89ff-f34b7b5809bf.png)

curl -s --insecure --cert ~/.chia/mainnet/config/ssl/wallet/private_wallet.crt --key ~/.chia/mainnet/config/ssl/wallet/private_wallet.key -d '{"wallet_id": 1}' -H "Content-Type: application/json" -X POST https://localhost:9256/get_wallet_balance | python -m json.tool
{
    "success": true,
    "wallet_balance": {
        "confirmed_wallet_balance": 0,
        "max_send_amount": 0,
        "pending_change": 0,
        "pending_coin_removal_count": 0,
        "spendable_balance": 0,
        "unconfirmed_wallet_balance": 0,
        "unspent_coin_count": 0,
        "wallet_id": 1
    }
}

**Comment by mariano54** [comment]
You need to sync the wallet first.
