### ISSUE TITLE
Swimming pool

### ISSUE THREAD

**Issue by nabiesl** [Chia-Network/chia-blockchain#6992]
Hello, did you make these settings for the pool?

Install latest chia software version, and create a wallet, and copy/paste your wallet address.
Then go to faucet.chia.net
Send 100 mojos to your wallet address
Once the 100 mojos are received in your wallet create a (Chia) pool NFT (enter pool.xchpool.org as the chia pool URL)
What is the meaning of this Send 100 mojos to your wallet address?

(https://xchpool.org/guide-to-chia-farming/)

**Comment by nabiesl** [comment]
![join-chia-pool](https://user-images.githubusercontent.com/86523027/123515901-42b6c700-d64e-11eb-962f-9cf3cccc7ff0.png)

**Comment by nabiesl** [comment]
How is the pool option added to the program?

**Comment by joelrb** [comment]
You are fooled by their screenshot. That's the GUI of a version still under development with focus on pools. It's not yet released. Wait when Chia release the official pool protocol, then everyone can join pools. No exact timeline for this. Just wait for official announcement...

Sending 100 mojos? It's like sending cents to your friends... :)

The smallest unit of chia, a trillionth of a chia, is called a mojo, as a tribute to Mojo Nation, a decentralized file storage platform created in the early 2000s by Zooko Wilcox, Bram Cohen, and others.
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ

You guys should read the guides first before doing something... or re-read them again and again..

**Comment by nabiesl** [comment]
Thank you very much

**Comment by mariano54** [comment]
Pools will be released soon, along with instructions on how to use them.
