### ISSUE TITLE
[BUG]chia gui show wrong farmer public key data

### ISSUE THREAD

**Issue by lpf763827726** [Chia-Network/chia-blockchain#7005]
**Describe the bug**
if i have two wallet, chia-gui show farmer only show the first one keys

**To Reproduce**

1. Create two wallet
2. Plot and farmer in first wallet, log report the pool contranct address: `txch1xnw8t******` and farmer public key: `a16f43f0858*****`
3. Switch second wallet(i don't know why can i still can see the first wallet of the farmer)
4. Plot and farmer in second wallet, log report the pool contranct address: `txch1tr2r0xf******` and farmer public key: `a16f43f0858*****`
5. It show they are same farmer public key, and pool contranct address are not the same
6. But when i `chia keys show` it show the farmer public key are not the same

**Expected behavior**
I think gui show maybe only show the first farmer public key data, because when i switch second wallet i still can see the first wallet of the farmer, if i want to create in chia gui with second wallet, it can't plot the second farmer public key

**Screenshots**
![Screenshot from 2021-06-28 10-46-01](https://user-images.githubusercontent.com/43004977/123572654-24dc9400-d7ff-11eb-8b95-85b1db431959.png)
![Screenshot from 2021-06-28 10-47-13](https://user-images.githubusercontent.com/43004977/123572673-2a39de80-d7ff-11eb-9882-08053182e432.png)
![Screenshot from 2021-06-28 10-49-47](https://user-images.githubusercontent.com/43004977/123572688-2efe9280-d7ff-11eb-898f-fd0341da688e.png)
![Screenshot from 2021-06-28 10-53-25](https://user-images.githubusercontent.com/43004977/123572695-31f98300-d7ff-11eb-91a5-11c19bc12720.png)

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20

**Additional context**

**Comment by mariano54** [comment]
Yes, the GUI only farms with the first key. The latest GUI version (for pool) will allow you to choose farmer and pool keys.
