### ISSUE TITLE
[BUG] when launch Chia

### ISSUE THREAD

**Issue by consaltus** [Chia-Network/chia-blockchain#701]
when I launch the latest version ChiaSetup-0.1.21, the window hangs on "Connecting to wallet". And I see endless loading

**Comment by wallentx** [comment]
@consaltus if you close everything and run `chia configure --enable-upnp True`, and relaunch, does this resolve it?
I had a similar experience that I noted in https://github.com/Chia-Network/chia-blockchain/issues/699, and doing this resolved it.

**Comment by consaltus** [comment]
I restarted and reinstalled several times and it worked))

**Comment by hoffmang9** [comment]
if you try to run more than one node on a home network, only one can have `chia configure --enable-upnp True`. The rest need `chia configure --enable-upnp False`

**Comment by hoffmang9** [comment]
Sometimes - and right now especially due to the wallet sync not working very well - your wallet database can get corrupted. I've added item item 6 to this to explain how - https://github.com/Chia-Network/chia-blockchain/wiki/Windows-Tips
