### ISSUE TITLE
Dir plotter

### ISSUE THREAD

**Issue by Sky1414** [Chia-Network/chia-blockchain#7014]
Hello
If Chia is never used, directory "plotter "is not created , and show error with PSChiaPlotter
![image](https://user-images.githubusercontent.com/83701847/123637281-1f427680-d81e-11eb-9219-d631acca94c7.png)

**Comment by gromran** [comment]
third party tool... why you think here ist place for support for this?

**Comment by mariano54** [comment]
No support for third party tools
