### ISSUE TITLE
[BUG] faucet.chia.net

### ISSUE THREAD

**Issue by SAMiner2017** [Chia-Network/chia-blockchain#7017]
Good Day,

I have setup the Chia Gui, created a new wallet and went to faucet.chia.net to get the 0.000001XCH that is needed and every time I submit a request it states already sent.

I am not sure what is going on.

Thanks

**Comment by MustDhiMust** [comment]
it only valid for once

**Comment by SAMiner2017** [comment]
The issue is It was an brand new wallet and i have never even used the Key and it told me already sent.

**Comment by mariano54** [comment]
It's checking your IP I think. Use a different IP address

**Comment by SAMiner2017** [comment]
Thanks
