### ISSUE TITLE
节点经常无法同步，找不到原因的丢失节点

### ISSUE THREAD

**Issue by t7aliang** [Chia-Network/chia-blockchain#7019]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/7018

<div type='discussions-op-text'>

<sup>Originally posted by **t7aliang** June 28, 2021</sup>
作过端口转发的设置，用外网扫描8444端口是打开的状态，然而6月下旬以来，经常无故的掉节点最终无法同步，严重应影响收割的效率！通过KEVA.APP添加节点和用VPS自建节点的方法都无济于事，手动添加节点的时候一闪就没了。VPN也无法奏效。莫名其妙，过去的两个月基本不怎么出现这个问题，现在每天要断线好几次，无法正常运转了。网络：联通500M。HELP！Chia版本：Linux-GUI</div>

**Comment by lpf763827726** [comment]
你的chia有更新过么？我之前也遇到过类似的情况，但是更新过后就同步得上了

**Comment by devtestnet** [comment]
P  I am really p opening the details   . Le you will lo tul I
I'll oilsp or not bqhtv I y you

**Comment by devtestnet** [comment]
💰 MurAll PAINT Giveaway 💰

200K PAINT tokens each will be rewarded to:

5 lucky winners
1 top-inviter with most referrals
1 Most engaged tweet's author

It'll take less two minutes to test your luck!
➡️ https://go.latoken.com/64sI am real pthankful 🥲 you this is all this you are doing all right that now you will never 👎 you again again this year is not going for me you odemo imp psizipnpt p

**Comment by devtestnet** [comment]
Reply's please send this to https://github.com/Chia-Network/chia-blockchain/issues/7019#issuecomment-870166460 reply stop all your reply stop stop r✋ reply button stop to cancel 😩 reply reply button please send reply me or or password for WhatsApp photo stop ✋ stop to reply please

**Comment by t7aliang** [comment]
My problem was solved by a instead of CLI client. So I suggest buddys to use CLI if had a command skill level.
我的问题解决了。用命令行的程序节点的问题就不再出现了，当然了，我指的是其他环境条件都完全相同。所以，建议有能力的同学还是使用CLI版本为好。
