### ISSUE TITLE
[BUG]Transaction failed, unable to use my coin

### ISSUE THREAD

**Issue by ubearline** [Chia-Network/chia-blockchain#7031]
**Describe the bug**
I can't use my coins because the transaction transfer failed

**To Reproduce**

1. Transfer to an address
2. It's a long wait
3. The coin didn't reach the target wallet, and it didn't go back to my own
4. This bug locked my wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/32406183/123727942-1062cf00-d8c5-11eb-87d7-d34f3ba6a9de.png)

**Desktop (please complete the following information):**

- OS: linux
- OS Version/Flavor: ubuntu 20.04
- CPU: Intel i9 11900kf

**Additional context**

**Comment by mariano54** [comment]
Try deleting the wallet DB and resync the wallet, follow the instructions here: https://github.com/Chia-Network/chia-blockchain/issues/6993

**Comment by ubearline** [comment]
> 尝试删除钱包数据库并重新同步钱包，请按照此处的说明进行操作：#6993

It is an irritating bug
