### ISSUE TITLE
Farm doesn't stay synced

### ISSUE THREAD

**Issue by dabookie09** [Chia-Network/chia-blockchain#7041]
Farm isn't staying synced.  Every time I launch it starts syncing and maybe two out of five times doing so, it successfully starts farming.  Every other time it sits at not synced, despite showing connected.  

Anyone else having this issue?  Been going on for about 3 weeks.

![image](https://user-images.githubusercontent.com/85043523/123804915-41d29f00-d8b3-11eb-90aa-ab192fbaef36.png)

**Comment by mariano54** [comment]
Are you using the latest version?

**Comment by Dartellum** [comment]
> Farm isn't staying synced. Every time I launch it starts syncing and maybe two out of five times doing so, it successfully starts farming. Every other time it sits at not synced, despite showing connected.
> 
> Anyone else having this issue? Been going on for about 3 weeks.
> 
> ![image](https://user-images.githubusercontent.com/85043523/123804915-41d29f00-d8b3-11eb-90aa-ab192fbaef36.png)

Did you port forward 8444 in your router? UPnP on? https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444

**Comment by w4d3j** [comment]
> > Farm isn't staying synced. Every time I launch it starts syncing and maybe two out of five times doing so, it successfully starts farming. Every other time it sits at not synced, despite showing connected.
> > Anyone else having this issue? Been going on for about 3 weeks.
> > ![image](https://user-images.githubusercontent.com/85043523/123804915-41d29f00-d8b3-11eb-90aa-ab192fbaef36.png)
> 
> Did you port forward 8444 in your router? UPnP on? https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444

That doesn't have anything to do with the client syncing, that only affects seeding others who are trying to sync.

**Comment by devtrf** [comment]
I have also been unable to sync for the last ~4 weeks. Nothing works, regardless of what it is. New VM, new db sync, new peers.db.

End result is still "Not synced"; "Connected". 

Worked previously for a solid month until we hit this wall.
