### ISSUE TITLE
[BUG]A block produces more than 2 coins. Is there a triple reward mechanism?

### ISSUE THREAD

**Issue by ubearline** [Chia-Network/chia-blockchain#7054]
**Describe the bug**
I'm mining in testnet9, but some blocks produced the wrong coins. I'm not sure if it's a GUI display bug or if it's really generating extra coins. It sounds good to have extra coins

**Screenshots**
![image](https://user-images.githubusercontent.com/32406183/123892424-21771300-d98d-11eb-99af-9bcb3c4148c0.png)

i got six coins at 27982. Is there a triple reward mechanism

**Comment by s3171103** [comment]
how many plots do you have??

**Comment by ubearline** [comment]
> how many plots do you have??

I don't think it has anything to do with the number of plots

**Comment by mariano54** [comment]
That's normal. Only transaction blocks can include rewards, so many blocks don't have any rewards. (about one in 3 blocks is a transaction block)
