### ISSUE TITLE
[BUG]Problem with plots

### ISSUE THREAD

**Issue by TomekLBN** [Chia-Network/chia-blockchain#7058]
After rebooting chia blockchain ver. 1.1.7 I do not see my parcels, I tried to add parcels heal it did not help I uninstalled and reinstalled chia blockchain and nothing please fix adding parcels and what should I do now? 
![image](https://user-images.githubusercontent.com/84026721/123904794-ff6b9980-d968-11eb-8aa2-127a17cba0f3.png)

**Comment by Fraquen1** [comment]
Same problem to me. I have 198 plots and only recognize 9 plots.

**Comment by lemon-Star** [comment]
The hard disk was unplugged and reinserted

**Comment by lemon-Star** [comment]
> Same problem to me. I have 198 plots and only recognize 9 plots.

The hard disk was unplugged and reinserted

**Comment by brolly30** [comment]
> After rebooting chia blockchain ver. 1.1.7 I do not see my parcels, I tried to add parcels heal it did not help I uninstalled and reinstalled chia blockchain and nothing please fix adding parcels and what should I do now?
> ![image](https://user-images.githubusercontent.com/84026721/123904794-ff6b9980-d968-11eb-8aa2-127a17cba0f3.png)

same problem, but for me it happened after i rebooted the computer without closing chia.

**Comment by TomekLBN** [comment]
Hi i fix problem. Must find file config.yaml backup and copy all and move to config.yaml . start miner and should be working
