### ISSUE TITLE
chia wallet doesnt connect[BUG]

### ISSUE THREAD

**Issue by brunoosuna8** [Chia-Network/chia-blockchain#7072]
chia wallet doesnt connect.it starts loading and  its freeze .and later starts again but with low frames in the loading animation.
and a few minutes later show up a white screen(image below).
i tried restart windows,forcing the program to close,and nothing.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 10 pro 64]
- OS Version/Flavor: [20H2]
- CPU: [AMD ryzen 7 3700x]

**Additional context**
![sds](https://user-images.githubusercontent.com/86745936/124028001-e0512400-d9c9-11eb-9b07-f641017f7140.png)

**Comment by mariano54** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/6993
