### ISSUE TITLE
[BUG] Chia and madmax plotter waits until any key is pressed to go on, no log message

### ISSUE THREAD

**Issue by tkmbe99** [Chia-Network/chia-blockchain#7076]
**Describe the bug**
Chia plotter from gui seems to hang. Now with madmax plotter passed the same. After trying to kill it goes on.
This passed several times. Now trying the command version from normal plotter shows that's the same.
Stays until a key is pressed.
There is no error log.
Mostly occurs in compress phases but now it was in phase1. Took 11h instead of 5h of course lost time until I pressed the key to go on...

**To Reproduce**
Not reproduceable. Sporadic error.

**Screenshots**

**Desktop (please complete the following information):**

 OS: Win10 Pro
 OS Version/Flavor: 20H2
 CPU: i5 760 with 16GB

**Additional context**
This is not a general problem. On  pc with i5-9400F with 8MB now 32MB works always, on the i5 first generation fails to often.
Memory is ok, disc ok. There seems to be an processor/win10 issue on this host.
But a friend of me has the same problem with an ryzen 3 220g y 16gb ram.
How could this be traced? Is it possibl to enable more debug output?

**Comment by gryan315** [comment]
If you are using powershell for both the chia plotter and madmax plotter, it's possible you are accidentally clicking in the window while "quick edit mode" is active, which pauses all running commands until the cursor is returned to the end.

**Comment by janki-87** [comment]
There is a workaround for this issue. In Command Promt, you can go to Properties and on Options tab, disable these two:
QuickEdit Mode
Insert Mode

You will lose ability to scroll in the window while it is working but at least it will not get stuck. 😉
