### ISSUE TITLE
I cannot find any document which states how to start the Timelord (plus other info missing) [BUG]

### ISSUE THREAD

**Issue by number435398** [Chia-Network/chia-blockchain#7077]
Several issues: The documentation I've found in this repository doesn't specify the steps on how to install a timelord on Windows (though it does state that it doesn't work on all versions of windows).  The documentation doesn't specify what command in what folder (or if it needs to be in the "venv" thing) to start a timelord.  It also doesn't explain the difference between a "Regular" timelord and a "Bluebox" timelord. The bluebox timelord instructions are also missing step by step instructions on how to setup such a timelord (it says what needs to be done, but not how to do it).

**Comment by mariano54** [comment]
Timelords are not supported on windows at this time

**Comment by number435398** [comment]
That's not what the documentation states, hence, a Bug. 

Even then, as I specified, other information is missing for the Linux install. This should not have been closed.

**Comment by fullet-tortuga** [comment]
The bug is legit. Please do reopen.
