### ISSUE TITLE
Wallet does not sync

### ISSUE THREAD

**Issue by GBourb** [Chia-Network/chia-blockchain#708]
Windows 10 pro
R5 2600
Full node 
              Status not synced
              Connection status : Connected

Wallets
              Status : Not synced
              Height : 220
             Connections : 2 

Chia : 0.1.21

I have 9.106TIB (92X K32)
Status of each plot : ERROR

The node have syced, i took aroud 12 hours
But the walklet start to sync and than stops.

My wallet does not sync and stops after some blocks
after a reboot, it's start again and stop after some blocks.

**Comment by GBourb** [comment]
I did add an exclusion on windows defender

**Comment by hoffmang9** [comment]
Wallet is known to be badly broken. Will be fixed in the next release.

**Comment by GBourb** [comment]
Thanks a lot

**Comment by hoffmang9** [comment]
Should be fixed in this release - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta22
