### ISSUE TITLE
[BUG]Wallet can only query 50 transaction records

### ISSUE THREAD

**Issue by ubearline** [Chia-Network/chia-blockchain#7081]
**Describe the bug**
As a full node client, I think I should be able to check all the records through my wallet. But now the query limit is 50.

**Screenshots**
![image](https://user-images.githubusercontent.com/32406183/124097853-8ebe9d00-da8e-11eb-838a-9bc2f993b245.png)
I'm sure I have more than 50 records.

**Comment by zhangyadong88888** [comment]
**玛德，这奇亚真垃圾，我也看不到50条之后的，还几把共享存储，其实不是，就是一个套******

**Comment by ubearline** [comment]
> **玛德，这奇亚真垃圾，我也看不到50条之后的，还几把共享存储，其实不是，就是一个套******

暴躁老哥，慢慢等chia更新吧，一堆bug，哈哈哈
