### ISSUE TITLE
[BUG] too many values to unpack

### ISSUE THREAD

**Issue by neal-zhu** [Chia-Network/chia-blockchain#7087]
**Describe the bug**
gui not working
**To Reproduce**
install gui with branch pools.testnet9

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34360891/124136501-6c8d4500-dab7-11eb-8456-0aab767c8bb7.png)

**Desktop (please complete the following information):**

- OS: macos

**Additional context**

**Comment by mariano54** [comment]
Looks like you have an old singleton. Please create a new key and test with a new key.
