### ISSUE TITLE
[BUG] Full node doesn't load reset the whole system and rebooted the system but no luck.uck.

### ISSUE THREAD

**Issue by 19Face66** [Chia-Network/chia-blockchain#7089]
#### ### **Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by loppefaaret** [comment]
Please tell is what version you are using, and what OS you are using it on ?

**Comment by loppefaaret** [comment]
do you have any ERROR or WARNING reported in `debug.log` located under your users folder `~\.chia\mainnet\log\` ?

**Comment by 19Face66** [comment]
I have no warning or error reports in( debug.log) I have deleted the program reset it making sure I had the latest version.    Sent from Mail for Windows 10 From: loppefaaretSent: 09 July 2021 06:56To: Chia-Network/chia-blockchainCc: 19Face66; AuthorSubject: Re: [Chia-Network/chia-blockchain] [BUG] Full node doesn't load reset the whole system and rebooted the system but no luck.uck. (#7089) do you have any ERROR or WARNING reported in debug.log located under your users folder ~\.chia\mainnet\log\ ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
