### ISSUE TITLE
[BUG] Estimated Time to Win

### ISSUE THREAD

**Issue by Krasy76** [Chia-Network/chia-blockchain#7094]
**Describe the bug**
I have 20.094 TiB with 203 plods and Estimated Time to Win - a year

**To Reproduce**
1. Go to 'Farming.'
2. Click on 'Farm'
3. Scroll down to 'Estimated Time to Win'
4. a year

**Expected behavior**
Other people with 200 plots and 20 TiB have Estimated Time to Win - 10 months
Last week mine Estimated Time to Win was also 10 months for a while with less than 200 plots and the same Total Network Space! Then returned to a year again. 
For me this is a bug - more plots, the same Total Network Space and longer Time to Win at the same time!

**Screenshots**
![YEAR](https://user-images.githubusercontent.com/86805188/124189076-d6621a80-dac8-11eb-825d-518ed3a6b85c.jpg)

**Desktop (please complete the following information):**
- OS: Windows 10
- OS Version: Windows 10 Enterprise
- CPU: i7-3770 CPU @ 3.40GHz

**Comment by ubearline** [comment]
It's not a bug. The whole network space is growing every day. Your estimated time will be two years, three years or more if you don't continue to increase your space

**Comment by PC101guy** [comment]
plows my mind, chia may be green, but its not green on your wallet.... god help us all! how can anyone make a buck doing this? pools? sure pools... and what? 100tb make you $50 a month.  Trying to stay positive isn't easy.

**Comment by Gazza7zs** [comment]
Got to admit, struggling to see the point. Must be missing something. All this infrastructure to what ends? 
Keep thinking I'm missing something that will at the very least enable me to see the ultimate goal for all this hardware. Utilization of redundant storage capacity has to be the biggest crook out. You cant tell me the creators just envisioned that, come on. Still, till I'm more informed I'll leave my final judgment.

**Comment by mariano54** [comment]
Working on pool, chialisp, and tons of important stuff! This is long term project, it's not a get rich quick scheme. Please be patient
