### ISSUE TITLE
[BUG]  ERROR <chia.server.ws_connection.WSChiaConnection object at 0x000001CCBB32D788> requested compact vdf we don't have, height: 300871

### ISSUE THREAD

**Issue by Gazza7zs** [Chia-Network/chia-blockchain#7095]
**error log entries**
2021-07-02T12:50:14.687 full_node chia.full_node.full_node: ERROR    <chia.server.ws_connection.WSChiaConnection
object at 0x000001CCBB32D788> requested compact vdf we don't have, height: 300871

**To Reproduce**
Has just started appearing in the last two days while checking the log file for errors and warnings via command line

**Expected behavior**
not to be reported?

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 
- OS Version/Flavor: 10 Pro
- CPU: Intel I7 2.6Ghz

**Additional context**

**Comment by mariano54** [comment]
This is fine, you can ignore this error

**Comment by Gazza7zs** [comment]
Thanks for the prompt reply, appreciated
