### ISSUE TITLE
[BUG] can not synchronize

### ISSUE THREAD

**Issue by zorro9527** [Chia-Network/chia-blockchain#7100]
1.1.7 
synchronization stuck at 476349.

why always the Fking synchronization issue. I can't always keep my eyes open on the stupid program for the synchronization, why the fking program can't work correctly? 

why u guys never fix this?

**Comment by loppefaaret** [comment]
update to 1.2.0, if the problem persist, please fill in the missing info, such as OS, installation method used, and perhaps try and check `debug.log` under your users folder `~/.chia/mainnet/log/` and see if you got any ERROR or WARNING from the full_node
