### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tonybeesknees** [Chia-Network/chia-blockchain#7114]
i have same problem on 3  computers 
one a i5 with 8gb ram
one i5 with12gb ram
one i7 with 12gb ram

all 3 were not connected at the same time 
all 3 had the port forwarded to them 
al 3 i let the chain sync

put 10 plots on there drives from a portable dive and 100 on a nas server 
all 3 started to show the last attempt at proof and worked fine 
until i tried to send plots from my nas to the computer 
all 3  stopped last proof and showed nothing for the time that the plots were moving
once the move finished the proof started to work again 
it was not due to network congested as i could download files off the net at top speed at the same time 

i have tried putting verus coin desktop and few other programs that need internet connections and all run fine with the files being moved no problems 
i can even watch a movie over plex from my nas at same time moving the files 
everything works fine but chia stops when there is network traffic
and it is not just from the nas its from other computers running windows 10 sending plots from shared drives same results  

i have been farming hundreds of plots for 7 or 8 months now and never won anything 
because  most of the time it says its happy and running fine all synced up but its not doing anything no proof happening

**Comment by loppefaaret** [comment]
try and deploy remote harvester instead of using a network share!
if the problem persist with remote harvester, please reopen the issue
