### ISSUE TITLE
[BUG] Error shown when clicked on Pool icon

### ISSUE THREAD

**Issue by flame1833** [Chia-Network/chia-blockchain#7120]
1. Click on pool
2. Create own pool
3. Chia accidentally shutdown when the pool still creating (pc turn off etc)
4. Re-open chia program
5. Click on Pool icon
6. Error shown

![image](https://user-images.githubusercontent.com/14892945/124420117-79e55080-dd91-11eb-9e62-ced784d4cee4.png)

**Comment by mariano54** [comment]
Try uninstlaling chia, restarting your computer, and updating to the latest version. Also which version did you install? Pools are not released yet.
