### ISSUE TITLE
You will need to specify the version as we do not support anything less than python 3.7.9

### ISSUE THREAD

**Issue by duongxuantuan154** [Chia-Network/chia-blockchain#7127]
You will need to specify the version as we do not support anything less than python 3.7.

__Originally posted by @hoffmang9 in https://github.com/Chia-Network/chia-blockchain/pull/7105#discussion_r663289753__

**Comment by duongxuantuan154** [comment]
- [ ]

**Comment by mariano54** [comment]
Please stop spamming
