### ISSUE TITLE
[BUG] CA Private key in github?

### ISSUE THREAD

**Issue by turbotas** [Chia-Network/chia-blockchain#7129]
**Describe the bug**
Surprised to see CA Private Key in github.  
It could be that this is a dummy key - I have no easy way to test.

**To Reproduce**
Steps to reproduce the behaviour:
Look at https://github.com/Chia-Network/chia-blockchain/tree/main/chia/ssl
Open "chia_ca.key"

**Expected behavior**
I would have expected this key to not be within the public repo - but this could be a dummy key.

**Screenshots**
Not Relevant

**Desktop (please complete the following information):**

- OS: Not relevant
- OS Version/Flavor: Not relevant
- CPU: Not relevant

**Additional context**

**Comment by mariano54** [comment]
This is just for having self-signed certificates.

**Comment by turbotas** [comment]
Self signed certificates for what?  If this key is actually used for anything, what was the point of using SSL as this key has become public?
