### ISSUE TITLE
Big problem INC when canceling the transaction to create a puzzle hash 

### ISSUE THREAD

**Issue by Tongie969** [Chia-Network/chia-blockchain#7131]
Hi, as the headline spoilers. I fucked it up :1st_place_medal: 

My test net wallet was out of sync when I started to create the puzzle hash. Two hours later, I aborted the transaction. 

Now when I open the pool tab on the GUI it say can't find transaction code ... 

All freezes black screen  and when I try to close it, it reopens. 

I there anything I can do to make my wallet happy again? 

Thanks in advance

**Comment by mtam8x** [comment]
same problem .

**Comment by Tongie969** [comment]
What have you done so far?  I am about to install everything new and and start with a new wallet. But you need to delete it first otherwise the bug continues with the new one.

**Comment by Tongie969** [comment]
I can't even use a new wallet key as it generates the same error. 

I did a fresh install and deleted the .chia folder, but still it is giving the same error. 

Please, what could I do to delete this Puzzle hash?

**Comment by Tongie969** [comment]
> same problem .

I hope you are on Linux to, go to .config and delete chia-blockchain folder. Do a fresh install and after some hours syncing you can start again.

**Comment by loppefaaret** [comment]
seems this issue is resolved ? if not, please open it again, but try and include some clues as to versions, which testnet and such
