### ISSUE TITLE
[BUG] Pooling plots not usable for pooling on other chains without breaking consensus protocol changes

### ISSUE THREAD

**Issue by flax-dev** [Chia-Network/chia-blockchain#7134]
In the current iteration, the official pooling protocol on the `pools.testnet9` branch works as follows:

1. Users create a "Plot NFT" which is a "singleton" on the Chia mainnet chain. What this (roughly) means is that a coin is sent to the special [singleton_launcher](https://github.com/Chia-Network/chia-blockchain/blob/pools.testnet9/chia/wallet/puzzles/singleton_launcher.clvm) contract (which acquires a coin ID subsequently referred to as the `launcher_id`) which subsequently creates the singleton, which comprises [singleton_top_layer](https://github.com/Chia-Network/chia-blockchain/blob/pools.testnet9/chia/wallet/puzzles/singleton_top_layer.clvm) that wraps an inner puzzle (like [pool_member_innerpuz](https://github.com/Chia-Network/chia-blockchain/blob/pools.testnet9/chia/wallet/puzzles/pool_member_innerpuz.clvm) if you intend to farm to a specific pool). The `singleton_top_layer` contract enforces certain security guarantees about the lineage of that coin, for example that it's a direct descendant of the launcher with the curried in `launcher_id`. As a pool member, the `pool_member_innerpuz` contract grants the pool owner the right to claim any pool rewards by asking the inner puzzle to signal by creating a puzzle announcement (see below).
2. Once the Plot NFT singleton is created on the Chia mainnet chain, the user will use the address of a [p2_singleton_or_delayed_puzhash](https://github.com/Chia-Network/chia-blockchain/blob/pools.testnet9/chia/wallet/puzzles/p2_singleton_or_delayed_puzhash.clvm) contract with the specific `launcher_id` baked in, as the target puzzle hash for plotting. This target puzzle hash (with the `launcher_id`) is then baked in and lives forever in the plots (though the singleton may morph).
3. When the pool member earns a reward, the `pool_member_innerpuz` contract signals via a puzzle announcement, which is asserted by the coin with the `p2_singleton_or_delayed_puzhash` puzzle before being disbursed to the pool operator. This process requires the exact singleton with the same `launcher_id` to be used to signal.

Now, note that this protocol relies on the `launcher_id` being present as the coin ID of the launcher coin, and this can't be changed because it is baked into the plots. Under existing consensus rules, because any non-farmed coins have their coin IDs generated as some hash of its parent coin info and amount, a singleton with this `launcher_id` can only exist on the Chia mainnet chain. This means for example, that under the current consensus rules and pooling protocol, no Plot NFTs can be portable between testnet and mainnet (so that plots created with this new scheme, under current consensus rules, can only ever work on Chia mainnet). For other chains, the only feasible way to support pooling for these new plots (as I understand it) is to change the consensus rules and add a limited mechanism for importing a "foreign" Chia-mainnet-chain singleton at its existing `launcher_id` address.

I'm not an expert here so this is sort of schematic, but one could imagine an approach here that could be more portable across chains. For example, instead of committing to the `launcher_id` in the puzzle baked into the plots, we could instead commit to a puzzle with some public key. The corresponding private key could be used to create (potentially many) singletons that track the user's pooling state. It's likely this could be done in a way that it's possible to enumerate all the singletons that derive from the public key, and the pool operator in this case could be expected to follow the first-created valid singleton for the public key as authoritative. The pool operator could require all other valid singletons be set to an invalid inner puzzle (disallowing pool reward claims) with a waiting room before exiting. This should be secure in the same way because to exit a pool, the user needs to first transition to the waiting room, before the authoritative singleton is either changed or melted. This has the advantage of being more "symmetric" with respect to the network in which the Plot NFT is created, and naturally allows Plot NFTs to be portable across chains, for example only requiring a registration for moving between testnet and mainnet. This also more naturally handles the case where the singleton is melted: the handling right now disallows these plots from ever being used for pooling again.

In recent announcements, it was declared that the pooling plots were going to be designed with "cofarming" in mind, so that they could be used across chains, in order to promote usage of a single set of plots for PoST chains. However as described above, this is not actually possible under current consensus rules / CLVM semantics, so a protocol hard fork would be needed to allow for cofarming on other chains. Is it intentional that breaking changes to consensus rules will be needed to cofarm with pooling on chains other than Chia mainnet, and would a more portable approach like the one described above be considered instead for the pooled farming puzzle?

@mariano54 @richardkiss @hoffmang9 @bramcohen

**Comment by mariano54** [comment]
Thank you for your ideas and post. We have finalized the singleton specification so we are not going to make further changes. You are correct that the current approach requires consensus changes on other blockchains. 

That said, I believe there are significant drawbacks to doing it in the way you are describing. If there can be multiple singletons per public key, then the pool needs to be aware of all singletons, to make sure that a specific farmer is not farming to another pool at the same time. This requires scanning the entire blockchain, and also requires the farmer to sign with their private key when creating the plotNFT, in order to prevent attackers from using the farmer's key.

With the current approach, a user only has to provide the launcher_id, and the pool can find everything from there. 

This would also make the chialisp for singletons  more complex, since we have to deal with creation waiting periods, and the singletons wouldn't be globally unique, which makes them less useful for other applications as well. There are more considerations that I also have not thought about, since I was not part of the team that designed them. Perhaps they can comment on other reasons why it was done this way.

**Comment by hoffmang9** [comment]
Other chains absolutely can use the new plot NFT style plots but it's not a free lunch. Those chains will have to manage some additional state on chain. We think any solid project will be able to do their own development to support co farming.

**Comment by bramcohen** [comment]
We made some changes to the way plot keys are generated to support exactly what you're talking about. With the new approach the local and farmer public keys can be revealed and the farmer key basically acts like a pool key does in the non-NFT plot format. The difference from how it was done before is that there might have been ways of generating multiple sets of local and farmer keys to make the same plot key, which isn't possible with the new technique for combining them.

**Comment by mariano54** [comment]
Oh okay. So what you're saying bram, is that a user would "register" their farmer public key on the second blockchain (let's say flax) by providing a signature. Then on that blockchain, you can create a singleton for that public key, and all block rewards that have that farmer public key would go into that singleton. 
This would also require consensus changes because you have to ignore the `pool_contract_puzzle_hash` in the proofs of space, but it would not require creating fake coin IDs, right?

**Comment by mariano54** [comment]
Some other ways you could do it include:
- Use the delay_puzzle_hash that is committed to in the creation of the p2_singleton_puzzle_hash
- Use the launcher's parent coin public key (the public key for the coin that was used to create the singleton on chia)

**Comment by flax-dev** [comment]
I understand that there are many constraints which have been very meticulously considered in the singleton and protocol design. Thank you for all your replies.

**Comment by diomark** [comment]
per discussions, an NFT reward should get at least 0.25.. I'm not even getting that -
`2021-07-28T02:52:23.376 harvester flax.harvester.harvester: INFO     6 plots were eligible for farming fb00e0f53e... Found 1 proofs. Time: 5.78068 s. Total 1706 plots
2021-07-28T02:52:23.387 farmer flax.farmer.farmer         : ERROR    Invalid proof of space {'challenge': '<removed>',
 'plot_public_key': '<removed>',
 'pool_contract_puzzle_hash': '<removed>',
 'pool_public_key': None,
 'proof': '<long string - removed>',
 'size': 32}
`

wallet reads 0:( it's happened last 3 times i've 'won' a block..

**Comment by keliew** [comment]
> per discussions, an NFT reward should get at least 0.25.. I'm not even getting that -
> `2021-07-28T02:52:23.376 harvester flax.harvester.harvester: INFO 6 plots were eligible for farming fb00e0f53e... Found 1 proofs. Time: 5.78068 s. Total 1706 plots 2021-07-28T02:52:23.387 farmer flax.farmer.farmer : ERROR Invalid proof of space {'challenge': '<removed>', 'plot_public_key': '<removed>', 'pool_contract_puzzle_hash': '<removed>', 'pool_public_key': None, 'proof': '<long string - removed>', 'size': 32} `
> 
> wallet reads 0:( it's happened last 3 times i've 'won' a block..

It says you have an "invalid proof of space"...

**Comment by diomark** [comment]
> > per discussions, an NFT reward should get at least 0.25.. I'm not even getting that -
> > `2021-07-28T02:52:23.376 harvester flax.harvester.harvester: INFO 6 plots were eligible for farming fb00e0f53e... Found 1 proofs. Time: 5.78068 s. Total 1706 plots 2021-07-28T02:52:23.387 farmer flax.farmer.farmer : ERROR Invalid proof of space {'challenge': '<removed>', 'plot_public_key': '<removed>', 'pool_contract_puzzle_hash': '<removed>', 'pool_public_key': None, 'proof': '<long string - removed>', 'size': 32} `
> > wallet reads 0:( it's happened last 3 times i've 'won' a block..
> 
> It says you have an "invalid proof of space"...

what does that mean? (these plots are fine in chia and the mnemonic keys are the same between chia and flax)

**Comment by altendky** [comment]
The recent messages here look like Flax support questions, not a continuation of the completed discussion above.  Could this newer discussion please be moved to a Flax support venue?

**Comment by diomark** [comment]
Sorry just adding my input here. NFT plots don't appear to work. Not even for the smaller 0.25 reward.
