### ISSUE TITLE
[BUG]VER1.1.784 test version error

### ISSUE THREAD

**Issue by 122474363** [Chia-Network/chia-blockchain#7162]
IMG：[https://z3.ax1x.com/2021/07/07/RH5GU1.png](https://z3.ax1x.com/2021/07/07/RH5GU1.png)
Unsuccessful creation of mining pool using 1.1.784 will prompt an error of unsuccessful creation.
The newly created mining pool cannot be deleted.
Then switch back to the release version. This error will occur.

**Comment by mariano54** [comment]
That is a very old version, you should not be using that
