### ISSUE TITLE
Transaction 0x4b5a6d54d6b9a0adce0b629ad697fc6502358d953c2887f9de7a54918f639d79 not found

### ISSUE THREAD

**Issue by ukrainer8** [Chia-Network/chia-blockchain#7168]
Chia Blockchain 1.1.784, Windows 10 Pro x64
Error is repeating continuously in the Pool division of GUI in result of try the new NFT creation. The situation leaded to the problem: I tried to create Plot NFT for self pooling, but that process frizzed because of some network issues. So waiting about 10 minutes without any success I decided to stop this process somehow and start again, but don't know how to do that and just deleted unconfirmed transactions in the wallet division, after that restarted the app. 
As I understand to stop appearing this error I need to stop somehow the Plot NFT creating. Do anybody know how to manage that?

**Comment by deutschmannstefan** [comment]
Same here. No Error in 1.2 but creating NFT stuck. 
<img width="532" alt="Bildschirmfoto 2021-07-08 um 08 56 53" src="https://user-images.githubusercontent.com/1485139/124876613-7e487e00-dfca-11eb-89df-9914d0401704.png">

**Comment by jessy1092** [comment]
Same here,

I create self pool nft GUI first, but wating 30 minutes without any success. And I stop GUI.

Then use the CLI to create plot nft with success, but still have creating progress on GUI. and has error `transaction was not found` on debug log.

![螢幕擷取畫面 2021-07-08 182531](https://user-images.githubusercontent.com/4408071/124907105-5bde5100-e01a-11eb-83e8-76af914fdf75.png)



debug.log
```
2021-07-08T18:30:30.297 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 203, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 626, in get_transaction
ValueError: Transaction 0x2f337a40fdbcbf7337abdd64c21d5b92e2faeed566513478ba05e29a629a1e74 not found
```

**Comment by gyy930918** [comment]
i have the same issue
Creating Plot NFT for Self Pooling
`2021-07-08T19:06:47.397 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 203, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 626, in get_transaction
ValueError: Transaction 0xaadae1f84932d7a7fad8cc6aba64d35503f5b1b7612bc4e77998e8949dbb4b4d not found`

**Comment by loppefaaret** [comment]
This issue is on a developer release, you should update to release 1.2.0

**Comment by deutschmannstefan** [comment]
I already use the release Version 1.2.0. 
<img width="392" alt="Bildschirmfoto 2021-07-08 um 14 30 41" src="https://user-images.githubusercontent.com/1485139/124921834-207f5a80-dff9-11eb-80d2-f77e8ffecfed.png">

**Comment by jessy1092** [comment]
@loppefaaret I already use the release Version 1.2.0, too

![螢幕擷取畫面 2021-07-09 131636](https://user-images.githubusercontent.com/4408071/125026840-ef199400-e0b7-11eb-840d-c2ff73d101ed.png)
