### ISSUE TITLE
Will not connect to Wallet[BUG]

### ISSUE THREAD

**Issue by MineShapht** [Chia-Network/chia-blockchain#7174]
**Describe the bug**
Checked PC this morning after a plot failed to complete due to insufficient storage.  Restarted Chia app and message for hours is "Connecting to Wallet" with spinning circle.  From the log...

2021-07-07T09:23:37.162 full_node full_node_server        : ERROR    Exception , exception Stack: Traceback (most recent call last):
  File "chia\server\server.py", line 361, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 521, in _request
  File "aiohttp\connector.py", line 535, in connect
  File "aiohttp\connector.py", line 892, in _create_connection
  File "aiohttp\connector.py", line 1032, in _create_direct_connection
  File "aiohttp\connector.py", line 969, in _wrap_create_connection
  File "asyncio\base_events.py", line 949, in create_connection
  File "asyncio\selector_events.py", line 473, in sock_connect
concurrent.futures._base.CancelledError

**To Reproduce**

1. Open Chia
2. See error

**Expected behavior**
The Chia app will load the start screen with the menu to pick the key to start plotting/farming with.

**Screenshots**
![image](https://user-images.githubusercontent.com/87091091/124808608-c0b77f80-df24-11eb-9544-9b3d870462cc.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Version/Flavor: Pro 20H2
- CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB (31.9 GB usable)

**Additional context**

**Comment by Zap0** [comment]
Can confirm that this happens to me too on W7. I ran an older version of the gui previously and didn't do anything but download the new 1.2.0 release and run it.

Output in the electron browser console:
```
Already connected, not reconnecting.
main.js:1 0
events.js:292 Uncaught Error: connect ECONNREFUSED 127.0.0.1:55400
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141)
```

**Comment by loppefaaret** [comment]
is this persistant after a rboot ? if so, try this:
WINDOWS WALLET DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!

**Comment by figvam** [comment]
@Zap0:
Chia 1.2.0 uses Python 3.9 which doesn't run on Windows 7 because of a missing DLL (api-ms-win-core-path-l1-1-0.dll): https://bugs.python.org/issue40740
You can confirm that if you run chia.exe from a command line. Fortunately someone has created a shim DLL based on Wine code that also allows Chia to run on Windows 7: https://github.com/nalexandru/api-ms-win-core-path-HACK

Obviously the issue author has another problem as he uses Windows 10.

**Comment by MineShapht** [comment]
Correct, this is a Windows 10 device.  Everything was fine up until a few days ago.  This particular node had been running for several weeks without issue.

Reviewing for Windows updates around that time provided nothing.

Can confirm that following the steps from @loppefaaret allowed me to get Chia up and running again, albeit, I'm having to completely resync the node from scratch.

**Comment by Zap0** [comment]
> @Zap0:
> Chia 1.2.0 uses Python 3.9 which doesn't run on Windows 7 because of a missing DLL (api-ms-win-core-path-l1-1-0.dll): https://bugs.python.org/issue40740
> You can confirm that if you run chia.exe from a command line. Fortunately someone has created a shim DLL based on Wine code that also allows Chia to run on Windows 7: https://github.com/nalexandru/api-ms-win-core-path-HACK
> 
> Obviously the issue author has another problem as he uses Windows 10.

I was able to confirm this as you said and the workaround by dropping in that dll worked for me. OP has a different issue than I do, and I'll be thanking for your reply and bowing out here then :-)

**Comment by loppefaaret** [comment]
Clsoing this issue as authors issue is reported as resolved
