### ISSUE TITLE
Value -1999999999900 of does not fit into uin128 [BUG]

### ISSUE THREAD

**Issue by skandats** [Chia-Network/chia-blockchain#7188]
On clicking on Pool tab,  dialog box "Value -1999999999900 of does not fit into uin128" is thrown continuously
![Chia Error](https://user-images.githubusercontent.com/87111862/124868264-223b2500-dfdd-11eb-9001-1d88b3232ba1.jpg)

**Comment by HououinKyouma01** [comment]
Not just this. It doesn't see my plots too. Every tab that I click on is generating "Value -SOMENUMBERS of does not fit into uin128"

**Comment by GSXswe** [comment]
Same bug for me when upgrading from 1.17 > 1.20, but I can see my plots. Seems that the wallet crash for me after a while too...  👎  This is not very fun when I wanted to start plotting pool plots and keep my other plots working at the sametime.

**Comment by skandats** [comment]
After deleting my local wallet DB and re-syncing, its working fine now.
