### ISSUE TITLE
[BUG] Exception from 'wallet' Incorrect version: 1, should be 1

### ISSUE THREAD

**Issue by Ketrupik** [Chia-Network/chia-blockchain#7201]
**Describe the bug**
I upgraded Chia to version 1.2.0, to start plotting pooled plots. I successfully restarted it, synced it and obtained some mojos. But when I tried to create the nft, I got this weird error:

(venv) user@chia:~/chia-blockchain$ chia plotnft create -u https://europe.ecochia.io -s pool
Exception from 'wallet' Incorrect version: 1, should be 1

**To Reproduce**

1. Go to your chia running on Linux in CLI
2. Issue command `chia plotnft create -u https://europe.ecochia.io -s pool`
3. See error

**Expected behavior**
I do not expect an error.

**Desktop**
- OS: Linux
- OS Version/Flavor: Debian 10.10
- CPU: Intel Pentium G3220

**Additional context**
No GUI, running in CLI

**Comment by mariano54** [comment]
Sounds like a problem with ecopool

**Comment by Ketrupik** [comment]
> Sounds like a problem with ecopool

truly, when I tried another pool, it works

disregard this error report, it's not a Chia error
