### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pchacker** [Chia-Network/chia-blockchain#7202]
**Describe the bug**
lost file  api-ms-win-core-path-l1-1-0.dll

**To Reproduce**

1.  cmd line :chia.exe start all

**Expected behavior**

**Screenshots**
https://user-images.githubusercontent.com/10546338/124886144-8de5b800-e006-11eb-8362-3a3792d61a59.png

**Desktop**

- OS: Windows
- OS Version/Flavor: Server 2008 SP2

**Additional context**

**Comment by loppefaaret** [comment]
Yup, we are no longer able to support windows 7 and server 2008
