### ISSUE TITLE
Still unable to display harvester information on other machines

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#7203]
venv) root@e4d9da736833:/chia-blockchain# chia farm summary
Farming status: Farming
Total chia farmed: 69.756610030009
User transaction fees: 0.006610030009
Block rewards: 69.75
Last height farmed: xxx
Local Harvester
   4659 plots of size: 461.172 TiB
Plot count for all harvesters: 4659

I deployed 10 harvester nodes on other machines, and successfully communicated with farmers to harvest normally, but the farmer node only displayed the local harvester node information.

**Comment by qian-fei** [comment]
`chia farm summary` Still can't see if the remote is the harvester

**Comment by janreges** [comment]
I have same issue. I have 6 successful working remote harvesters (all updated to verson 1.2.0) and their logs contains continually __X plots were eligible for farming X ... Found X proofs.__ - so all harvesters works properly.

But `chia farm summary` shows only one remote harvester:

```
Last height farmed: 542067
Local Harvester
   899 plots of size: 88.982 TiB
Remote Harvester for IP: 10.111.0.8
   2524 plots of size: 249.838 TiB
Plot count for all harvesters: 3423
Total size of plots: 338.820 TiB
Estimated network space: 30.104 EiB
```

**Comment by qian-fei** [comment]
> I have same issue. I have 6 successful working remote harvesters (all updated to verson 1.2.0) and their logs contains continually **X plots were eligible for farming X ... Found X proofs.** - so all harvesters works properly.
> 
> But `chia farm summary` shows only one remote harvester:
> 
> ```
> Last height farmed: 542067
> Local Harvester
>    899 plots of size: 88.982 TiB
> Remote Harvester for IP: 10.111.0.8
>    2524 plots of size: 249.838 TiB
> Plot count for all harvesters: 3423
> Total size of plots: 338.820 TiB
> Estimated network space: 30.104 EiB
> ```

I don't have one

**Comment by qian-fei** [comment]
I use docker
version: 1.2.1.dev0

**Comment by loppefaaret** [comment]
if you are using docker, ensure you are exporting the RPC port

**Comment by qian-fei** [comment]
> if you are using docker, ensure you are exporting the RPC port

I exposed the port, the remote harvester node communicates with the farmer node normally, but I can't view the remote harvester information`chia farm summary`

**Comment by mariano54** [comment]
@xdustinface , maybe it's performance related? all users seem to have a large number of plots

**Comment by qian-fei** [comment]
> @xdustinface , maybe it's performance related? all users seem to have a large number of plots

There are 10 remote harvesters, each with 150t plots

**Comment by dgfmdrv** [comment]
I have two remote harvesters. Both on 1.2.0 but on farmer log shows:
```
2021-07-08T13:36:28.265 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
```
chia farm summary shows two harvester but **sometimes** only shows one.

harvester logs contains "plots were eligible for farming"

**Comment by xdustinface** [comment]
> I deployed 10 harvester nodes on other machines, and successfully communicated with farmers to harvest normally, but the farmer node only displayed the local harvester node information.

> I have same issue. I have 6 successful working remote harvesters (all updated to verson 1.2.0) and their logs contains continually X plots were eligible for farming X ... Found X proofs. - so all harvesters works properly.

@qian-fei @janreges Interesting..  i have it running here with 4 harvesters with a range of 100-1700 plots for more than a week without issues. One thing to note is that how it works right now is that the farmer caches the responses of the harvester and tries to request them in the background every 60 seconds. Did you wait at least a few minutes after restarting the farmer to see if they appear after a while?

What maybe could be an issue here is this [5 seconds timeout](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/farmer/farmer.py#L555). Might be the harvester being blocked for too long with other stuff and not be able to respond in time. Can someone with this issue here test it with a higher timeout like 30s or so please? :)  

> chia farm summary shows two harvesters but **sometimes** only shows one.
> 
> harvester logs contain "plots were eligible for farming"

The reason why i would show only one sometimes may be one of:
1. The harvester did not respond to the farmer for 10 minutes
2. The harvester is not connected to the farmer when you run `chia farm summary`

**Comment by qian-fei** [comment]
> > I deployed 10 harvester nodes on other machines, and successfully communicated with farmers to harvest normally, but the farmer node only displayed the local harvester node information.
> 
> > I have same issue. I have 6 successful working remote harvesters (all updated to verson 1.2.0) and their logs contains continually X plots were eligible for farming X ... Found X proofs. - so all harvesters works properly.
> 
> @qian-fei @janreges Interesting.. i have it running here with 4 harvesters with a range of 100-1700 plots for more than a week without issues. One thing to note is that how it works right now is that the farmer caches the responses of the harvester and tries to request them in the background every 60 seconds. Did you wait at least a few minutes after restarting the farmer to see if they appear after a while?
> 
> What maybe could be an issue here is this [5 seconds timeout](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/farmer/farmer.py#L555). Might be the harvester being blocked for too long with other stuff and not be able to respond in time. Can someone with this issue here test it with a higher timeout like 30s or so please? :)
> 
> > chia farm summary shows two harvesters but **sometimes** only shows one.
> > harvester logs contain "plots were eligible for farming"
> 
> The reason why i would show only one sometimes may be one of:
> 
> 1. The harvester did not respond to the farmer for 10 minutes
> 2. The harvester is not connected to the farmer when you run `chia farm summary`

Do you need to restart the farmer every time you add a harvester?It feels strange

**Comment by xdustinface** [comment]
> Do you need to restart the farmer every time you add a harvester?It feels strange

No you don't.

**Comment by xdustinface** [comment]
@qian-fei does it work now for you? If so, what changed?

**Comment by qian-fei** [comment]
> @qian-fei does it work now for you? If so, what changed?

I restart my farmer node, then query again, and the remote harvester information will appear

**Comment by janreges** [comment]
@xdustinface - after i restart farmer node by `chia start farmer -r`, all harvesters were displayed. Same as mentioned by @qian-fei.

Btw, all harvesters works fast for whole time, with proof-check under 0.1s. In addition, one of the harvesters won the chia, although the summary did not show him at the time.

All harvesters are on same LAN, same switch, with locally connected drives and fast AMD Ryzen 5, 7 or 9. There was no timeout/connectivity/slowdown issues.
