### ISSUE TITLE
I've been waiting for a long time, how can I delete them?

### ISSUE THREAD

**Issue by usengel** [Chia-Network/chia-blockchain#7213]
I've been waiting for a long time, how can I delete them?

![asd](https://user-images.githubusercontent.com/85193032/124911061-00e63300-dff5-11eb-9fb1-fa2d6b170e81.png)

I've been waiting for a long time, how can I delete them?

**Comment by gyy930918** [comment]
Its a bug 
Pool shows:Creating Plot NFT for Self Pooling
`2021-07-08T19:06:47.397 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 203, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 626, in get_transaction
ValueError: Transaction 0xaadae1f84932d7a7fad8cc6aba64d35503f5b1b7612bc4e77998e8949dbb4b4d not found`

**Comment by mariano54** [comment]
Looks like the tx didn't go through. What happens when you restart wallet?

**Comment by WiseGuyNL** [comment]
> Looks like the tx didn't go through. What happens when you restart wallet?

Stays the same, I have the same issue

**Comment by usengel** [comment]
it doesn't improve and my wallet address changes every time

**Comment by Tongie969** [comment]
I had a quite similar problem. Luckily, I had a backup of my .chia folder before the transaction went true. So a reinstallation would fix it. Delete all data in .config/Chia-Blockchain and better also in .chia folder. But don't forget to back up db and wallet! Do fresh installation, start it, it will say syncing. Close it after that. Restart your system over, copy db and wallet in .chia > happy farming 

If you are running on Windows, fix that first :D

**Comment by loppefaaret** [comment]
otherwise, there is now under the "Wallet" tab, in the top right, 3 `...` dots, that lets you delete unconfirmed transactions

**Comment by Tongie969** [comment]
> otherwise, there is now under the "Wallet" tab, in the top right, 3 `...` dots, that lets you delete unconfirmed transactions

In my case, that didn't work.

**Comment by WiseGuyNL** [comment]
> > otherwise, there is now under the "Wallet" tab, in the top right, 3 `...` dots, that lets you delete unconfirmed transactions
> 
> In my case, that didn't work.

same here, didn't work
