### ISSUE TITLE
Two plots have log showing error

### ISSUE THREAD

**Issue by BillAntonacchio** [Chia-Network/chia-blockchain#7214]
_Only wrote 0 of 227172 bytes at offset 6370012840 to "E:\\Plot17\\plot-k32-2021-06-29-05-09-4f08d391a80449d340691e41bf225b2dbc2a2e1bb5dfcf417098bfac3295f545.plot.table1.tmp" with length 6370013184. Error 1. Retrying in five minutes.
Only wrote 0 of 227172 bytes at offset 6370012840 to "E:\\Plot17\\plot-k32-2021-06-29-05-09-4f08d391a80449d340691e41bf225b2dbc2a2e1bb5dfcf417098bfac3295f545.plot.table1.tmp" with length 6370013184. Error 1. Retrying in five minutes.
Only wrote 0 of 227172 bytes at offset 6370012840 to "E:\\Plot17\\plot-k32-2021-06-29-05-09-4f08d391a80449d340691e41bf225b2dbc2a2e1bb5dfcf417098bfac3295f545.plot.table1.tmp" with length 6370013184. Error 1. Retrying in five minutes.
Only wrote 0 of 227172 bytes at offset 6370012840 to "E:\\Plot17\\plot-k32-2021-06-29-05-09-4f08d391a80449d340691e41bf225b2dbc2a2e1bb5dfcf417098bfac3295f545.plot.table1.tmp" with length 6370013184. Error 1. Retrying in five minutes._

What do I do. Can these be repaired, or how do I delete bad plots from dashboard?

Please help.

Thanks
Bill Antonacchio

**Comment by loppefaaret** [comment]
An `Error 1` is an indication that something outside the chia program is causing the problem - in this case, it is trying to write data to a plot file, but was unable to write any data at all - this could potential be cause the drive in use is filled completely ? it could also be that the drive had other issues ? 
anyways, it is not an issue as such with the chia program, and as such, im closing this issue
perhaps try and get support from our support discussions, or our keybase:
https://github.com/Chia-Network/chia-blockchain/discussions/categories/support
https://keybase.io/team/chia_network.public
