### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dmontes46** [Chia-Network/chia-blockchain#7215]
**Describe the bug**
Create 2 NFT pool to  Self Pooling, trying to delete the pools and not possible

\chia plotnft leave -i 3 -y
Will start self-farming with Plot NFT on wallet id 3 fingerprint 3433947002.
Error performing operation on Plot NFT -f 3433947002 wallet id: 3: {'error': 'Attempted to self pool when already self pooling', 'success': False}

<br class="Apple-interchange-newline">
</body>
</html>

**To Reproduce**

\chia plotnft leave -i 3 -y
Will start self-farming with Plot NFT on wallet id 3 fingerprint 3433947002.
Error performing operation on Plot NFT -f 3433947002 wallet id: 3: {'error': 'Attempted to self pool when already self pooling', 'success': False}
**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 

**Additional context**

**Comment by mariano54** [comment]
You cannot delete plot NFTs.
You can join a pool, or leave a pool if you joined.
