### ISSUE TITLE
[BUG] 1.2.0 release doesn't run on Windows 7 anymore

### ISSUE THREAD

**Issue by figvam** [Chia-Network/chia-blockchain#7222]
**Describe the bug**
After 1.2.0 update, Chia doesn't run on Windows 7 anymore. GUI is stuck at "Connecting to wallet" while throwing these errors in the developer tools log:
`events.js:292 Uncaught Error: connect ECONNREFUSED 127.0.0.1:55400
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141)`
and CLI throws a popup error about missing api-ms-win-core-path-l1-1-0.dll, while complaining about Python39.dll in console.

**To Reproduce**
1. Install/update to 1.2.0 on Windows 7.
2. Run GUI or CLI and observe the described behaviour

**Expected behavior**
Chia should run on Windows 7.

**Desktop**
- OS: Windows 7
- CPU: any

**Additional context**
It is caused by the use of Python 3.9 which doesn't support Windows 7: https://bugs.python.org/issue40740
But there is a workaround. Someone has created a replacement api-ms-win-core-path-l1-1-0.dll based on Wine code to run Blender 2.93 (which also uses Python 3.9) on Windows 7: https://github.com/nalexandru/api-ms-win-core-path-HACK
I've copied that replacement DLL to the Chia command line folder and that allowed me to run Chia 1.2.0 GUI and CLI.

**Comment by figvam** [comment]
This user has the same issue: https://github.com/Chia-Network/chia-blockchain/issues/7174#issuecomment-876363643

**Comment by AleksRaider** [comment]
Can you drop this DLL and in which folder should you put it?

**Comment by emlowe** [comment]
We no longer support windows 7

**Comment by figvam** [comment]
@emlowe: There is nothing about Windows 7 in the FAQ, Wiki or release notes. You should probably state somewhere that Windows 7 is unsupported.

**Comment by AleksRaider** [comment]
> Мы больше не поддерживаем Windows 7

So it is necessary to write about this, that Windows 7 is not supported anyway, otherwise it is not really written about it anywhere

**Comment by AcidBurnSB** [comment]
Windows 7, Windows Server 2008 R2, not support Python 3.9 :(

**Comment by hardhub** [comment]
> 
> 
> @emlowe: There is nothing about Windows 7 in the FAQ, Wiki or release notes. You should probably state somewhere that Windows 7 is unsupported.

https://github.com/nalexandru/api-ms-win-core-path-HACK

Hack to run it on Win7
