### ISSUE TITLE
[BUG] The total of Plot Count is not displayed correctly

### ISSUE THREAD

**Issue by we-akri** [Chia-Network/chia-blockchain#7223]
**Describe the bug**
The total of Plot Count is not displayed correctly

**Screenshots**

![001](https://user-images.githubusercontent.com/83537373/124928650-74457000-e008-11eb-8c9f-0c2808b0d60f.jpg)
![002](https://user-images.githubusercontent.com/83537373/124928652-75769d00-e008-11eb-981b-587469aafea9.jpg)

**Desktop**

 - chia blockchain 1.2.18
- OS:   Microsoft Windows 10 Pro OS Version:10.0.19042 N/A Build 19042 
- CPU: e.g. Intel Xeon 2680v3

**Comment by aliaredo** [comment]
seam isse and no pool

**Comment by besssx** [comment]
Same here

**Comment by Sagittarius** [comment]
But I change main node log level to DEBUG，it works immediately
