### ISSUE TITLE
[BUG] windows defender threat flagged

### ISSUE THREAD

**Issue by dorkmo** [Chia-Network/chia-blockchain#723]
**Describe the bug**
With installation, got a trojan warning. 

**To Reproduce**
install 22

**Screenshots**
![image](https://user-images.githubusercontent.com/1923070/105177195-f63ded00-5aeb-11eb-9912-6571de849c03.png)

**Desktop (please complete the following information):**

- OS: Win10

**Comment by hoffmang9** [comment]
It's a known issue and a false positive. It's been reported.

**Comment by coderev3** [comment]
I had something similar.

I recently was syncing a Full Node.
In the process it flagged the following:

-Blocked Website Details-
Malicious Website: 1
, C:\Users\REV\AppData\Local\chia-blockchain\app-1.0.5\resources\app.asar.unpacked\daemon\start_full_node.exe, Blocked, -1, -1, 0.0.0, , 

-Website Data-
Category: Trojan
Domain: 
IP Address: 113.88.208.3
Port: 8444
Type: Outbound
File: C:\Users\REV\AppData\Local\chia-blockchain\app-1.0.5\resources\app.asar.unpacked\daemon\start_full_node.exe

This IP I traced back to China
