### ISSUE TITLE
CHIA钱包里面的收支和支出记录怎么只显示50条，浏览器只显示收入的没有支出的，赶快加账目记录，垃圾垃圾[BUG]

### ISSUE THREAD

**Issue by zhangyadong88888** [Chia-Network/chia-blockchain#7232]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by loppefaaret** [comment]
the GUI only shows 50 records currently, and upon resyncing the wallet, only incoming transactions are listed cause of they way coin ID's are handled on chain
