### ISSUE TITLE
[BUG] chia plotnft inspect does not produce valid JSON

### ISSUE THREAD

**Issue by dutchgecko** [Chia-Network/chia-blockchain#7236]
**Describe the bug**

According to the `--help` the command `chia plotnft inspect` should produce JSON output. Instead it outputs what appears to be the python representation of a named tuple.

**To Reproduce**

1. Create a plot NFT
2. `chia plotnft inspect`

**Result**

    {'pool_wallet_info': PoolWalletInfo(current=PoolState(version=1, state=1, target_puzzle_hash= [...]

**Expected behavior**

Valid JSON output

**Comment by aqk** [comment]
Hey there,

Thank you for your report. You are completely right that this dumps Python, not JSON. I  stuck this command in there for debugging, but of course it is released now.

I initially wrote this to output JSON, but a few of the objects in that output don't JSON-serialize yet, and I decided writing serializers was a distraction from what I was doing at the time.

at-mention me if you submit a PR for this issue, and I'll get it some attention.
