### ISSUE TITLE
Windows 7 v1.2.0 -"api-ms-win-core-path-l1-1-0.dll is missing from your computer"

### ISSUE THREAD

**Issue by spalt** [Chia-Network/chia-blockchain#7246]
![image](https://user-images.githubusercontent.com/2190693/124975742-53771d80-dffc-11eb-8abb-bc92a55765d8.png)

Getting this running the CLI from a Win7 command line.
The GUI doesn't seem to be working either, just spinning when connecting to wallet....

**Comment by pausto** [comment]
Same problem. There was no problem on the command line in 1.1.7.
The main application does not start (probably cannot start start_wallet and other programs.
I have multiple python versions installed. Probably confused somewhere.

**Comment by HotDrive69** [comment]
Expect a world of problems using Chia software on Windows 7 machines. The software now runs on Python 3.9, that does not work on Windows 7...

**Comment by emlowe** [comment]
Windows 7 is not supported - we forgot to update the release notes

**Comment by pausto** [comment]
And what to do now? Many people have Windows 7 and for a number of reasons cannot upgrade to Windows 10.
Was it critical to upgrade to Windows 8 +?
Updates for Windows 7 are still coming out, for example, a critical update was released today

**Comment by fullet-tortuga** [comment]
I foresee a huge drop in fanbase because of that. Which is kind of sad because I've seen other projects die because an external component developed by others stopped to work. Oh well, this is the last nail and totally normal when you use third party code.

**Comment by HotDrive69** [comment]
My wallet is still working, on a Windows 10 machine. Only lost the chance to create plots on a Windows 7 machine. Still, excluding Windows 7 users is a very bad move...

**Comment by figvam** [comment]
FYI #7222 has a workaround in the additional notes.

**Comment by HotDrive69** [comment]
IT.... WORKS!!!!! Thanks figvam for the tip!
