### ISSUE TITLE
Chia GUI does not update NFT plot count automatically

### ISSUE THREAD

**Issue by aslanteh** [Chia-Network/chia-blockchain#7247]
The plot count on the pool tap does not update automatically, manually refreshing plots on the plots tab seems to rectify this issue however.

**Comment by ramin-afshar** [comment]
indeed, I have the same problem here.

**Comment by heilwood** [comment]
same issue, on beta version was everything fine

**Comment by ramin-afshar** [comment]
I did some further investigation and I think it's just a graphical bug. When looking up my pooling stats in the explorer page of the pool (xchpool in my case) I see my netspace increasing with each added plot, even though it's not reflected in the GUI.

**Comment by JobbeDK** [comment]
I can confirm it looks like a bug in the UI. When looking in the logs, new plots show up as expected. But UI does not update count automatically.

**Comment by aslanteh** [comment]
I thought it was a graphical bug too at first but my total plot size went up on the pool website as soon as I refreshed the plots manually. Maybe it was just a coincidence though and yea the beta version didn't have this issue.

**Comment by bopres** [comment]
Same issue here .. Any solution till now? I'm using madmax for plotting.

**Comment by loppefaaret** [comment]
giving it 10 minutes+ to pass a timeout, and then doing CTRL+R to force reload the GUI seems to work for some users

**Comment by mbaric1** [comment]
See #7262 and  Chia-Network/chia-blockchain-gui#487

**Comment by emlowe** [comment]
Duplicate of #7262
