### ISSUE TITLE
Using chia.exe via CLI gets error on Python DLL[BUG]

### ISSUE THREAD

**Issue by HotDrive69** [Chia-Network/chia-blockchain#7252]
When trying to use the CLI, there is an error in the execution of a python DLL.

I tried the command <chia.exe -h> and the result is:
Error loading Python DLL 'C:\Users\...\resources\app.asar.unpacked\daemon\python39.dll'.
No error messages generated.
FormatMessageW: O parÔmetro estß incorrecto. (translation: "The parameter is incorrect")
LoadLibrary: PyInstaller: FormatMessageW failed.

- OS: Windows
- OS Version/Flavor: 7 pro 64bit
- CPU:  XEON X3470

**Comment by HotDrive69** [comment]
GUI version 1.2.0 uses python 3.9, not supported in Windows 7?!?

**Comment by emlowe** [comment]
Windows 7 is no longer supported - unfortunately we forgot to note this is a few places
