### ISSUE TITLE
[BUG] Exception from 'wallet'

### ISSUE THREAD

**Issue by Dartellum** [Chia-Network/chia-blockchain#7255]
**Describe the bug**
 Wallet is not opening after upgrade to 1.2.0.

**To Reproduce**

1. chia wallet show from CLI
2. Wait a few minutes
4. See error -> Exception from 'wallet'

**Expected behavior**

- OS:  Linux
- OS Version/Flavor:  Ubuntu 20.04.2
- CPU:  Intel i7 3770k

**Additional context**
 I do not see anything in debug.log about wallet. I also searched issues but did not see an exact match for this issue.

**Comment by Dartellum** [comment]
> **Describe the bug**
> 
> Wallet is not opening after upgrade to 1.2.0.
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. chia wallet show from CLI
> 2. Wait a few minutes
> 3. See error -> Exception from 'wallet'
> 
> **Expected behavior**
> 
> * OS:  Linux
> * OS Version/Flavor:  Ubuntu 20.04.2
> * CPU:  Intel i7 3770k
> 
> **Additional context**
> 
> I do not see anything in debug.log about wallet. I also searched issues but did not see an exact match for this issue.

Fouund existing installation: chia-blockchain 1.2.1.dev0 <-- the version I did this afternoon by doing latest. 
    Uninstalling chia-blockchain-1.2.1.dev0:
      Successfully uninstalled chia-blockchain-1.2.1.dev0
  Running setup.py develop for chia-blockchain
Successfully installed chia-blockchain-1.2.1.dev4 < -- Figured I would try the latest on main. Starting up now.

**Comment by emlowe** [comment]
On linux, when updating, after you fetch/pull from git, you need to remember to `chia stop -d all`, then deactivate, sh install.sh, . ./activate, and finally 'chia start wallet' (or farmer, or whatever you want to start)

**Comment by Dartellum** [comment]
> On linux, when updating, after you fetch/pull from git, you need to remember to `chia stop -d all`, then deactivate, sh install.sh, . ./activate, and finally 'chia start wallet' (or farmer, or whatever you want to start)

Did that, twice now. Wallet still not working. I just removed the wallet/db/ files so they resync.

**Comment by Dartellum** [comment]
Over and over in the debug log:
```
2021-07-08T23:21:34.614 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most>
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 581, in sync_job
    await self._sync()
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 661, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 538, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 0-32
```

**Comment by Dartellum** [comment]
Okay, removing chia-blockchain and reinstalling fresh fixed the syncing problem. Although, I had to remove my wallet db for it to work. Closing as syncing and no errors returning.
