### ISSUE TITLE
Ubuntu Upgrade Wiki should specify git reset with --recurse-submodule

### ISSUE THREAD

**Issue by myst3k** [Chia-Network/chia-blockchain#7257]
Updating all my nodes and plotters today to 1.2.0. 
At first, each of them ran into the issue where the RELEASE.dev0 was specified as the version after the upgrade. I attempted to remove the package.json, then re-install which also did not work.

I believe changing the upgrade command on the wiki for the "git reset" to include "--recurse-submodule" should prevent this from happening and keep the branch and all required submodules inline.

Ubuntu/Debian Update/Upgrade Section
```
cd chia-blockchain
. ./activate
chia stop -d all
deactivate
git fetch
git checkout latest
git reset --hard FETCH_HEAD --recurse-submodule
```

**Comment by adobito** [comment]
I was having issues updating and this fixed it for me on each computer.

**Comment by gryan315** [comment]
I've just been deleting the directory and cloning a fresh one from scratch.

**Comment by gryan315** [comment]
I'm not particularly experienced with the wiki section of github, but would a pull request be appropriate for changing this, or is that just for changes to files in the code section?

**Comment by emlowe** [comment]
Yes, this helps with clearing out the modified translation files inside chia-blockchain-gui. I have added it to the wiki. Thanks for the suggestion.

**Comment by gryan315** [comment]
Should it be `--recurse-submodule` or `--recurse-submodules`?

**Comment by emlowe** [comment]
git docs indicate it is plural - however, I tested it, and either seems to work. I updated the wiki to make it plural.
