### ISSUE TITLE
Chia init not found, wallet not connecting

### ISSUE THREAD

**Issue by ProfyTourny** [Chia-Network/chia-blockchain#726]
Dear
I am using latest Ubuntu distrib
In Beta 19, i was able to create plots with chia plots create
now the command returns "Chia command not found"
and when I launch the GUI, it stuck on "Connecting to Wallet" after pop up say start failed
Kindly

**Comment by dorkmo** [comment]
have you tried on beta 22 yet? same result?

**Comment by mariano54** [comment]
Try again with the latest release, beta 23, feel free to reopen if it's not working.
