### ISSUE TITLE
v1.2.0 Does not auto refresh plot directories

### ISSUE THREAD

**Issue by CryptoBlockchainTechnologies** [Chia-Network/chia-blockchain#7262]
This came up during the roll out today after upgrading and the solution was to hit the refresh button. However this is now a bug when comparing to prior versions in that as you add more plots to a directory either from a network connection or from a CLI client plotter (MadMax etc) the GUI does not see the plots both on the Plots tab and the Pool tab on the NFTs. This is after starting the GUI for the first time and hitting that refresh button.

I now have to constantly refresh all of my plotters hourly since updating to 1.2.0. I run 12 plotters and produce quite a few plots each hour. Remoting into12 plotters and hitting the refresh button is not what I consider an automated application. Refreshing plots is important so that I can start pooling and to also verify the plots are valid. I plot into 18TB drives that hold 165 plots each and they take about 2 days to fill. Waiting to pool almost 2000 plots until they are ready to move to harvestor is not ideal. The only solution now is to manually keep refreshing.

I have this issue in the Linux version. Windows users are reporting no issues.

Anyone adding feedback to this issue whether you are not seeing it or not, please include which OS you are using.

**Comment by Tongie969** [comment]
Same for me. I was thinking about a downgrade, as this was not a problem with the latest build before stable.

**Comment by antonmakarenko** [comment]
I tested on a setup where main farmer machine runs GUI, and plotter is a different machine that only runs harvester CLI against the target directory being plotted (connecting to the farmer machine via local network). Refresh on the harvester works correctly, and is properly reflected on the GUI -> Farm tab

**Comment by CryptoBlockchainTechnologies** [comment]
> I tested on a setup where main farmer machine runs GUI, and plotter is a different machine that only runs harvester CLI against the target directory being plotted (connecting to the farmer machine via local network). Refresh on the harvester works correctly, and is properly reflected on the GUI -> Farm tab

I am using Ubuntu and having this issue, what OS are you using?

**Comment by CryptoBlockchainTechnologies** [comment]
> Same for me. I was thinking about a downgrade, as this was not a problem with the latest build before stable.

What OS?

**Comment by jlfsccm** [comment]
我也是同样问题

**Comment by jlfsccm** [comment]
我也是同样问题windows 10   、windows server 2019同样问题

**Comment by mbaric1** [comment]
Same here, but I am on Windows 10. 

Noticed that plots created using MadMax are not added on the list of the plots, farm overview is not updated, and plot count on the pool isn't updated on the GUI. But if you take a look under `Farm - Last Attempted Proof - Plots Passed Filter` you can see that table is regularly updated and plot count is increased (e.g. x/250, x/251).

Think this is pure GUI issue where statuses are not being updated, but your plots are detected by harvester and farming.

**Comment by Tongie969** [comment]
Hi, I am on Ubuntu 20.4 as well. I was using the mainnet realest before, and it was all fine. A new bug for stable release or .....

**Comment by Tongie969** [comment]
Did someone try if a downgrade would fix it?

**Comment by Armageus** [comment]
> Same here, but I am on Windows 10.
> 
> Noticed that plots created using MadMax are not added on the list of the plots, farm overview is not updated, and plot count on the pool isn't updated on the GUI. But if you take a look under `Farm - Last Attempted Proof - Plots Passed Filter` you can see that table is regularly updated and plot count is increased (e.g. x/250, x/251).
> 
> Think this is pure GUI issue where statuses are not being updated, but your plots are detected by harvester and farming.

Can confirm this is the case - My Plots Passed Filter increases, but the GUI "plot count" and Pool "Number of Plots" do not, until you manually "Refresh Plots"

**Comment by fereehu** [comment]
I have the same problem on Ubuntu 20.04 with version 1.2.0.

For a workaround, what is the CLI command for "Refresh plots" button? Does anyone know this? Maybe I could add this to cron to refresh it in every x minutes.

**Comment by Tongie969** [comment]
Good point, hopefully there is one. If you need to restart the hole farmer, it takes a way to long.

**Comment by CryptoBlockchainTechnologies** [comment]
> Think this is pure GUI issue where statuses are not being updated, but your plots are detected by harvester and farming.

I am beginning to think the same thing. Hopefully we can get a developer to weight in soon so we can all go back to sleep and stop refreshing our machines every hour. I am beginning to think this is payback, not intentional, for all the sleepless nights they went through to get this release out so fast. :)

**Comment by Tongie969** [comment]
Yes, true farmer and harvester are getting them, but not the pool. So you won't get points for those new plots. :(

**Comment by CryptoBlockchainTechnologies** [comment]
> Yes, true farmer and harvester are getting them, but not the pool. So you won't get points for those new plots. :(

Not sure sure though because my understanding is the pool does not know how many plots you have and the points are generated based on partials, which come from passing the filter. I am hoping as long as they are being passed through the filter, it might just be two displays that need to get refreshed.

**Comment by mbaric1** [comment]
I've checked the logs. Harvester searches for directories and finds new plot and harvester is aware of that. It is just that GUI stats are not updated.

There is similar issue raised Chia-Network/chia-blockchain-gui#487 .
@seeden said it's a known issue and team is working on it.

**Comment by CryptoBlockchainTechnologies** [comment]
> There is similar issue raised [Chia-Network/chia-blockchain-gui#487](https://github.com/Chia-Network/chia-blockchain-gui/issues/487) .
> @seeden said it's a known issue and team is working on it.

Brilliant, thanks I can go to sleep now and rest assured I my machines are doing what they were designed to do.

**Comment by Kryptoand** [comment]
The solution for plots that disappear with version 1.2 is this: You have to uninstall version 1.2 and delete the following folders: C: \ Users \ username \ .chia and C: \ Users \ username \ AppData \ Local \ Chia-Blockchain \ restart the pc and reinstall version 1.2. folders with plots and recognizes them. It is a bug of version 1.2 that when you install with the previous version it is as if it blocked your plots folders.

I agree with a previous comment that says it is a disgrace. The plots that we small farmers have been making for months now do not work .... This version is a disgrace to the general public. Plot again? where is the emblem of the 'eco' coin? spend light to plot again? will this happen every time they change the version? friends I think this is not normal!

**Comment by Andyaj** [comment]
Same here.. the plots are coming in from madmaxplotter from across network but the chia software does not detect in the pool and i need to refresh the plots in the plots tab for it to reflect back on pool. Running 1.2.0 on window  2012 R2

**Comment by softwareuser99** [comment]
agree and confirm this only happens with 1.2

**Comment by temicus** [comment]
@Kryptoand the solution doesn't work. I deleted everything and cleaned up and reinstalled. Problem remains.

**Comment by brasrox** [comment]
same on Windows 10 ,  chia v1.2
using madmax on 2 machines but all new plots doesnt auto refresh in farmer and pool tab, 
but in filter its refresh

**Comment by Kryptoand** [comment]
parcels appear until the chia blockchain syncs in 1.2v . once the program is synchronized it is blocked. The program has an error and does not allow deleting even the locations (folders) of the plots. They also do not allow you to add the old plots to your own pool ... they said they would not work for the pools but they also do not work for solo plotting. BRAVO

**Comment by 85256638** [comment]
bugs after bugs

**Comment by jlacroix82** [comment]
Can confirm this is happening on all of my clients, running the full UI as individual farmers/harvesters in pool mode now.  But the good thing is at least the pool can see my active plots despite the UI not seeing them.

![image](https://user-images.githubusercontent.com/87331774/125330626-01dcd480-e315-11eb-963c-2efb73ac2e52.png)

**Comment by mladenperisic** [comment]
Have the same issue on all my computers (Windows 10 Pro 64-bit).

**Comment by Armageus** [comment]
Not sure that 1.2.1 has actually fixed this. After deleting 2 plots the Plots passed filter display decreased almost instantly, however the Plot Count did not change even when waiting ~3 minutes. A manual refresh of plots did however work "first time"

**Comment by brasrox** [comment]
![image](https://user-images.githubusercontent.com/21345109/125434158-dc69cd67-23c8-46e4-95a6-1baf4b83ef13.png)

**Comment by xludodx** [comment]
is there a CLI command to refresh plots list ?
Tx

**Comment by Tongie969** [comment]
@xludodx I think that wouldn't change a thing. Harvester updates them and offers those to the network. The singleton token doesn't recognize them. Please have a look at it, chia team :rotating_light:

**Comment by adic20** [comment]
same issue with windows OS, after v1.2.0 update auto refresh not working.

**Comment by adic20** [comment]
> 
> 
> same issue with windows OS, after v1.2.0 update auto refresh not working. 
updated to v1.2.1 issue still there no auto refresh

**Comment by zhouchiyan82** [comment]
使用PSchiaPlotter也是一样的，更新到1.2.1，当plot绘制完成后不会加到矿池中，每次都要手动刷新

**Comment by Andyaj** [comment]
Seriously.. I really don't know who's listening ar chia development.!!?!!
Same issue.

**Comment by Jacek-ghub** [comment]
The same issue on Win10/chia v1.2.2.  Actually, today "Refresh Plots" stopped working.  All back to normal after restarting the full node.

**Comment by Tongie969** [comment]
> > same issue with windows OS, after v1.2.0 update auto refresh not working.
> > updated to v1.2.1 issue still there no auto refresh

Confirmed same for me Ubuntu 20.04 server and desktop.

**Comment by Zeesy** [comment]
I'm not getting any updates to my pool tab, even after restarting. Win10. `chia check plots` shows 18 valid plots.

**Comment by coolpro313** [comment]
same for me too on windows 10 but in my case it wouldn't update when i add drives that has the plots files remove them for either maintenance or transfer to another drive as a replacement or even when creating new plot files requiring me to add the drives close reopen just to update same for removing and after a new plot is created both from mad max and regular slow plotter

**Comment by emlowe** [comment]
We believe this is improved with 1.2.3

**Comment by Jacek-ghub** [comment]
Is there a release document that lists the changes in v1.2.3?

**Comment by coolpro313** [comment]
oh ok i just saw that the update got released 3 hours ago from the time that i sent this comment i'll update the wallet now and see if it got fixed or not @emlowe @Jacek-ghub

**Comment by Jacek-ghub** [comment]
@emlowe Is there a reason, why the old folder (...\app-1.2.2) is not removed?  Previous upgrades were doing that.

**Comment by emlowe** [comment]
Closing issue - fixed in v1.2.3
