### ISSUE TITLE
[BUG] Mac-User "Current Difficullty" not show in pool section

### ISSUE THREAD

**Issue by Manintorn** [Chia-Network/chia-blockchain#7269]
1) Updated and synced Chia 1.2.0 both Windows and Macs
2) Used Madmax v0.1.1 through Windows 
3) Created pool url on Mac
4) Add finished 19 Plots on Mac
5) No Current Difficulty shown
6) Was trying to add another pool, same problem

![213184334_960689717808048_6025250632343297685_n](https://user-images.githubusercontent.com/84113906/125033035-00af6b80-e0b9-11eb-8630-d50c5ba9fe9e.jpg)

**Comment by Manintorn** [comment]
Windows has no problem with the same 19 plots

![212409664_231828675284346_741452962309616133_n](https://user-images.githubusercontent.com/84113906/125033296-55eb7d00-e0b9-11eb-9e1b-043c4ae04882.jpg)

**Comment by loppefaaret** [comment]
could you tell us what macos version - and if 11.x BigSur, is it the m1 arm based machine ?

**Comment by korawong** [comment]
i have same problem, macos version:big sur 11.4,macbook Air M1

**Comment by Manintorn** [comment]
I've got 3 Macs with the same lan line
1st Mac Mini 2020 with 11.4 BigSur - "Current Difficulty" not shown
2nd Mac Mini 2012 with 10.15.7 Catalina - "Current Difficulty" not shown
3rd Macbook Air with 11.4 BigSur - Work just find


![1](https://user-images.githubusercontent.com/84113906/125066447-36664b80-e0dd-11eb-974a-14b0ac4c4d27.png)
![2](https://user-images.githubusercontent.com/84113906/125066464-3b2aff80-e0dd-11eb-9c0f-57adee56d9c4.png)
![3](https://user-images.githubusercontent.com/84113906/125066469-3c5c2c80-e0dd-11eb-9223-3c9762b58f7b.png)


> could you tell us what macos version - and if 11.x BigSur, is it the m1 arm based machine ?

**Comment by Portago9** [comment]
I also have this issue on Win10

![Hvataj](https://user-images.githubusercontent.com/87185868/125074285-600f7a80-e0bd-11eb-8328-d190c4651814.PNG)

Tried adding on a diffrent, new wallet, but same result, not adding the difficulty and not farming...

Debug saying:

> ERROR    Exception in GET /pool_info https://eu1.pool.space, [ASN1] nested asn1 error (_ssl.c:4174)
2021-07-09T13:54:23.532 farmer chia.farmer.farmer         : WARNING  No pool specific authentication_token_timeout has been set for 35871076c61e54e5dcd7258ef79f1edc084df65c9759e1ea9579e668f2785e4b, check communication with the pool.


> WARNING  No pool specific difficulty has been set for 35871076c61e54e5dcd7258ef79f1edc084df65c9759e1ea9579e668f2785e4b, check communication with the pool, skipping this signage point, pool: https://eu1.pool.space

**Comment by loppefaaret** [comment]
ahh, this might stem from a CA certificate problem we have already solved, and is to be included in 1.2.1 release

**Comment by Manintorn** [comment]
> ahh, this might stem from a CA certificate problem we have already solved, and is to be included in 1.2.1 release

sound good
will wait for new release
Cheers
