### ISSUE TITLE
The added pool cannot be deleted or changed添加的矿池无法删除 无法变更 

### ISSUE THREAD

**Issue by jlfsccm** [Chia-Network/chia-blockchain#7271]
The added pool cannot be deleted or changed
添加的矿池无法删除 无法变更

**Comment by loppefaaret** [comment]
Any chance you get provide a screenshot of the problem, to bypass language barrier ?

**Comment by jlfsccm** [comment]
> Any chance you get provide a screenshot of the problem, to bypass language barrier ?

Cannot delete POOL

**Comment by glukkon24** [comment]
I've had same problem once you add a pool you are stuck and even after adding another I can't switch to another pool.

**Comment by loppefaaret** [comment]
no, you cannot delete a plot NFT once it is created - you can however switch a plot NFT to any pol you want, or self pool

**Comment by chiazhang** [comment]
删除不了，只有solo或者更换，钱包要完全同步才能操作

**Comment by Lowestofttim** [comment]
I have needed to reinsatall the chia gui twice today, there is no option to "sign back into" the NFT  pool? The only option is to "join a pool" so if you do that and for me its space pool, it creates another pool NFt and your old one will then pop up. 
So now i have three pool NFT's for space pool but only use/need one.
I think thats what this thread is talking about
![88888](https://user-images.githubusercontent.com/86534160/125338574-47ff5b80-e348-11eb-9972-b21dda1463b5.PNG)

Not sure if this effects the actuall pools stats? I.e it thinks it has more farmers than it actuall has?

**Comment by loppefaaret** [comment]
as you can see, only coffee echidna has plots tied to it, the other too are doing nothing- the points should be correct

**Comment by Lowestofttim** [comment]
So the pool won't even see the other two?

That's great then.

It would be good to be able to get rid of them though, or hide them bat least.

**Comment by elarkasi** [comment]
hide and show button should be a reasonable option for history.

**Comment by emlowe** [comment]
Closing issue  - They cannot be deleing. An enhancement to hide NFTs is planned
