### ISSUE TITLE
[BUG]Error creating plot NFT: 'transaction'

### ISSUE THREAD

**Issue by oneforalone** [Chia-Network/chia-blockchain#7279]
**Describe the bug**
Get error while running `chia plotnft create -s local`: **Error creating plot NFT: 'transaction'**

1. Update Chia to V1.2.0: `git pull`
2. Re-run `install.sh` script: `bash install.sh`
3. Activate the venv: `. ./activate`
4. Execute command: `chia plotnft create -s local`
5. And then got the error.

The screenshots show the steps and some related info.

**Screenshots**
![image](https://user-images.githubusercontent.com/41844215/125059932-6e21c300-e0de-11eb-89d7-3136ff902fe3.png)

**Desktop**
- OS: Linux
- OS Version: Ubuntu 18.04.5 LTS
- CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
- Chia Version: 1.2.0

**Comment by emlowe** [comment]
try stopping all services (chia stop -d all) and then starting the farmer (chia start farmer) - this will start the wallet and full node as well

**Comment by oneforalone** [comment]
Thanks, that's work. However, it takes me a while to sync wallet.
