### ISSUE TITLE
[BUG] - "chia farm summary" on a harvester no longer shows total plot count

### ISSUE THREAD

**Issue by mercupgrades** [Chia-Network/chia-blockchain#7287]
I run 1 farmer, 2 harvesters and 2 plotters that rcp plots to the harvesters, all Ubuntu.  Theres about 1600 plots on each harvester.

In 1.1.17 on the harvesters you could do "chia farm summary" and it would show the plot count on that harvester.
With 1.2.1.dev0  this no longer works, and plot count is shown as "Unknown"

chia@chia-harvester2:~$ chia version
1.2.1.dev0
chia@chia-harvester2:~$ chia farm summary
Connection error. Check if farmer is running at 8559
Connection error. Check if full node is running at 8555
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2de29796a0>
Connection error. Check if farmer is running at 8559
Farming status: Not available
Plot count: Unknown
Total size of plots: Unknown
Estimated network space: Unknown
Expected time to win: Unknown
For details on farmed rewards and fees you should run 'chia start wallet' and 'chia wallet show'
chia@chia-harvester2:~$ 
For details on farmed rewards and fees you should run 'chia start wallet' and 'chia wallet show'
chia@chia-harvester2:~$ 

- OS: Linux
- OS Version/Flavor: Ubuntu 21.04
- CPU: Intel Core i7-3770 on harvesters, Core i7-2600 on Farmer (all @3.40Ghz)

**Additional context**
This code has clearly been extended for 1.2.0 as the farmer now shows harvester info, but it seems to be a shame to have lost the info on the harvesters themselves.

**Comment by happycouak** [comment]
Same here

**Comment by whitetechnologies** [comment]
Same here on 1.2.0

This is definitely the case at least for official pool plots. Directory added, chia plots check detects them and they are valid. However, chia farm summary does not detect them.

**Comment by youngfong13** [comment]
This is case for non pool plots as well, running Ubuntu with version 1.2.0 plots are recognized using MacOS 1.2.0 GUI but no chia farm summary. Plots show as valid when running chia plots check.

**Comment by hhenrry501** [comment]
> Same here on 1.2.0
> 
> This is definitely the case at least for official pool plots. Directory added, chia plots check detects them and they are valid. However, chia farm summary does not detect them.

Same here.

**Comment by anguschang007** [comment]
> This is case for non pool plots as well, running Ubuntu with version 1.2.0 plots are recognized using MacOS 1.2.0 GUI but no chia farm summary. Plots show as valid when running chia plots check.

Same issue!!
