### ISSUE TITLE
[BUG] NFT not syncing over multiple nodes

### ISSUE THREAD

**Issue by secco04** [Chia-Network/chia-blockchain#7305]
I have multiple chia gui clients just for having a backup and synced node if for whatever reason one fails... 
i have created 2 nft on the Windows node which helds my plots
on the second Windows node they synched flawlessly 

on my ubuntu node they dont appear.
so to cross test the whole thing ive created a nft on the linux node - it synced flawlessly to the windows nodes.
but the nft created on the windows nodes wont appear on the linux node 

i had v 1.1.7446 installed on both windows nodes to preview and start plotting nft plots.

the linux node was on 1.1.7 till official release - wich got updated to 1.2.0 recently

on linux my result when i type chia plotnft show - shows me only wallet id 2  with launcher id 0xbd2xxx ...
on win my result when i type it shows me 
Wallet id 2:
Launcher ID: 6a6xxxx....
Wallet id 3:
Launcher ID: 8d0xxxx....
Wallet id 4:
Launcher ID: bd2xxxx....

**Expected behavior**

nfts should sync across any node win/linux/whatever

**Screenshots**
![image](https://user-images.githubusercontent.com/42780357/125117859-1ccdff80-e0ef-11eb-9f01-618ce60a829a.png)

- OS:windows 10 /ubuntu 21

**Comment by emlowe** [comment]
You will need to resync your wallet on your linux machine - likely the NFTs were synced on that machine while it was running the previous version. So you need to resync with the new version and they will appear

**Comment by secco04** [comment]
how is the process?
stop chia client
delete .chia/mannet/wallet/db
start client?

ive done it and it stays at wallet status syncing (0)

**Comment by secco04** [comment]
ok had to delete the db folder aswell  -.- now it will take forever again  :D thanks
