### ISSUE TITLE
Where are all my 10000 plots? (1000Tb / 1Pb) [BUG]

### ISSUE THREAD

**Issue by Kryptoand** [Chia-Network/chia-blockchain#7308]
Hello everybody! We have been making plots for 2 months. Since we have installed the new version 1.2 when we open the program there is not a single plot. We have added a pool like space.pool to see if this was the problem but no. The 10000 plots that we have been doing during these 2 months do not work? They said there would be no re-plots... someone can help me? Thanks!

#bramcohen @bramcohen
It cannot be that they have made us plot for months with chia blockchain, that they tell us that it would not be necessary to return to plott and now it seems that we have to start over? Explain a little more. are we going to have to re-plot every time they release a new version? NOTE: very ecological it is not with the light that is used to plot

**Comment by youngfong13** [comment]
My plots aren't recognized via the CLI in version 1.2.0 (running Ubuntu) but they are recognized via the GUI.

**Comment by ookyou** [comment]
i currently facing the same issue, i did complete removal of chia and install 1.2 and while i was adding my "plot directories" in windows gui, it loaded some plots like 130 then adding more "plot directories" made my farm completely empty also the plot count is 0 i cant find any of my plots in the gui i checked the confgue file and my "plot directories" are listed there even in windows gui i can see some of my "plot directories" but no plots are showing at all!  note: while running "chia plots check" or "chia plots show" they are listed!, someone please help me!

**Comment by iamzhanghao** [comment]
Same issue here. Reverted to beta 1.1.795 then works again....

**Comment by dominick01234** [comment]
Re-update via command line and launch GUI via command line. Update instructions on GitHub that haven’t changed. I had an issue as well but somehow was on 1.2.0.dev version. Check your version if interested and then reinstall everywhere. You don’t need to delete you .chia folder which keeps your config intact. About 5 minutes per harvester to update. Should work smoothly. Good luck

**Comment by Kryptoand** [comment]
I have found the solution. You have to uninstall version 1.2 and delete the following folders: C: \ Users \ username \ .chia and C: \ Users \ username \ AppData \ Local \ Chia-Blockchain \ restart the pc and reinstall version 1.2. folders with plots and recognizes them. It is a bug of version 1.2 that when you install with the previous version it is as if it blocked your plots folders.

**Comment by Kryptoand** [comment]
however I certify that the plots of version 1.7 do not work with the pools. They clearly said that the plots from version 1.7 would work in version 2.0 but it is not totally true because they do not work for pools....

**Comment by extrasolarCHIA** [comment]
`2021-07-11T00:52:00.605  chia.plotting.plot_tools         : ERROR    Failed to open file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot. Invalid file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot
`
what does this mean?

**Comment by youngfong13** [comment]
> Same issue here. Reverted to beta 1.1.795 then works again....

I reverted to 1.1.6 and my plots are recognized via CLI.

**Comment by HoracioF** [comment]
After I upgraded to 1.2.1 I don't see my plots, when I any command it shows some output (most likely incomplete) but they return  ¨Segmentation fault (core dump)" message at the end, like this one:
![image](https://user-images.githubusercontent.com/8117289/125202589-3df33500-e242-11eb-870f-533fe306d2c7.png)

**Comment by Kryptoand** [comment]
parcels appear until the chia blockchain syncs. once the program is synchronized it is blocked. The program has an error and does not allow deleting even the locations (folders) of the plots. They also do not allow you to add the old plots to your own pool ... they said they would not work for the pools but they also do not work for solo plotting. BRAVO

**Comment by HoracioF** [comment]
That looks bad

**Comment by dominick01234** [comment]
Perhaps the '@FinalPlots' folder name is an issue? I would try remove the
'@' and test. Did you file names change? Did you update to chia 1.2 using
the update process or a full reinstall? Can you access the file yourself?
Good luck. The only issue I have had so far was starting the GUI using the
previous GUI launch icon vs npm electron &. All of my plots and harvester
show up accurately. 'chia farmer summary' shows a nice summary broken out
by IP of harvesters.

**Comment by HoracioF** [comment]
I got the latest from github and compile, but I keep getting the Segmentation fault message when trying the chia command, I assume it is related to my issue of not displaying all my plots.

**Comment by HoracioF** [comment]
I found that I was using Python 3.6 and not 3.7, that seems to be the whole issue all the time :) my bad.
Now I have chia 1.3.0 and Python 3.7 (as indicated as the minimum version) and no more errors, back in business :)

**Comment by emlowe** [comment]
Per earlier comments, this issue appears solved - marking closed
