### ISSUE TITLE
Config.yaml cannot update payout instruction for NFT [BUG]

### ISSUE THREAD

**Issue by whitetechnologies** [Chia-Network/chia-blockchain#7311]
**Describe the bug**

According to https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-User-Guide, to update the XCH address to which pools should send your payouts, you simply update it in config.yaml at pool/xch_target_address

However, updating that address does not change the result of plotnft show. It appears that because the plot NFT is saved to the blockchain, including the payout address, it cannot be changed by config.yaml and requires some sort of process to change it on chain, so devs should document this process

**To Reproduce**

1. Change xch_target_address in config.yaml (in pool section)
2. Restart chia
3. Run chia plotnft show
4. Payout insutrctions will display old address, not the updated one in config.yaml

**Expected behavior**
Config.yaml should allow update of pool payout insutrctions as per the wiki

Ubuntu 20.04 but same on windows.

**Comment by hoffmang9** [comment]
The config.yaml pool receive address is the pool receive address for self pooling plots and not plotNFT plots. The GUI and CLI manage plotNFT plots. This is behaving as expected with the caveat that the existing name for the plot receive address is a little confusing here but deprecating/changing that would have wide ranging consequences to farmers still farming OG plots.

**Comment by ariegrossman** [comment]
Ok. So how does one change the payout instructions?

**Comment by gWOLF3** [comment]
lol no response... thanks @hoffmang9

**Comment by hoffmang9** [comment]
This is an issue on a set of code that was entirely re-written between 1.2.11 and 1.3.0. It is irrelevant to the current issue.
