### ISSUE TITLE
"Add Plot Directory" Issues in Windows GUI

### ISSUE THREAD

**Issue by security01** [Chia-Network/chia-blockchain#7314]
Running v1.2.0 on Windows Server 2012 R2

As the number of configured plot directories increases, trying to add or remove using the GUI (Plots page / three dots in upper right next to the "+ ADD A PLOT" button / Add Plot Directory / ADD PLOT DIRECTORY) results in an unreasonably long wait time for the operation to complete - either adding or removing a directory.  It'll eventually snap out of it, but often results in no change to the visible list - although it seems to actually modify the config.yaml file.

I've been experiencing this issue for many releases now - I think as far back as 1.3.0.

**Comment by hhenrry501** [comment]
im having this issue as well.
debug.log showing multiple copies for plots warning and harvestor not respond warning..
dont know what to do

**Comment by hoffmang9** [comment]
This is a known issue that's being worked on. It's at the GUI level and not actually impacting the lower level.
