### ISSUE TITLE
fixup

### ISSUE THREAD

**Issue by tomardkeen** [Chia-Network/chia-blockchain#7317]
to fix! please 
1. option to delete created nft pool in gui
2. status of choosen pooling pool should be shown in gui
- in gui, all nft pools show status of pooling at the same time - even if one was selected
3. ploting in gui is waste of time - everybody uses madmax
- could be nice to have madmax integrated in gui. isnt it?
4. solo plots and nft plots should have different color or name in case of moving or sending them to different space / hdd
5. joining nft pool should be notified by some info from gui as confirmation
best regards guys and have nice work :)

**Comment by MaximusChia** [comment]
Wish to Customize contract names so its better to organize plots. No more Random names like Red Falcon, Blue Whale, ... names without any meaning to us.

**Comment by loppefaaret** [comment]
1: a plotnft is a transaction on the blockchain, we cannot delete transactions on the blockchain
2: what exactly do you mean by "selected" ? all the plot NFT are transactions on the blockchain, and are all active ?
3; close to 10% of the blocks won are by plots madmax is incapable of creating (k33+) and i think a significant bigger part is being created through the GUI still
4: they are currently distinguished by public pool key - nft plots have no public pool key
5: joining a pool is done through a transaction - it should already show a plot nft as "Pending" when it is waiting for a transaction to complete ?

that being said, work to adding 3rd party plotters to the GUI is already up on our board
the concern about plot NFT's being able to either be hidden, or entirely invalidated somehow is being discussed
custom names for plot NFT's is also being discussed
