### ISSUE TITLE
[BUG] Plot count: Unknown and Farming status: Not available

### ISSUE THREAD

**Issue by PirateDigger** [Chia-Network/chia-blockchain#7323]
**Describe the bug**
Local node doesn't show plots 

**To Reproduce**

Configure slave node by using this article https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines
execute command on slave node chia farm summary

~/chia-blockchain$ chia farm summary
Connection error. Check if farmer is running at 8559
Connection error. Check if full node is running at 8555
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2a0eff49a0>
Connection error. Check if farmer is running at 8559
Farming status: Not available
Plot count: Unknown
Total size of plots: Unknown
Estimated network space: Unknown
Expected time to win: Unknown
For details on farmed rewards and fees you should run 'chia start wallet' and 'chia wallet show'

**Expected behavior**
I'm expecting plot count on local node but i see total on master node

~/chia-blockchain$ chia farm summary
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Local Harvester
   62 plots of size: 6.137 TiB
Remote Harvester for IP: 192.168.8.40
   99 plots of size: 9.799 TiB
Plot count for all harvesters: 161
Total size of plots: 15.936 TiB
Estimated network space: 30.992 EiB
Expected time to win: 1 year and 2 months
Note: log into your key using 'chia wallet show' to see rewards for each key

**Comment by rhernaus** [comment]
You are using terms 'master' and 'slave' that do not exist in Chia architecture. See [Network-Architecture](https://github.com/Chia-Network/chia-blockchain/wiki/Network-Architecture).
The
```
chia farm summary
````
command communicates to farmer and full-node processes that you are not running on your harvester node. If you set 
```
log_level: INFO
```
in your config file then you can see lines like these in your log file.
```
2021-07-10T09:27:21.960 harvester chia.harvester.harvester: INFO   17 plots were eligible for farming cf5c6f3da5... Found 0 proofs. Time: 0.83076 s. Total 10187 plots
```

**Comment by PirateDigger** [comment]
> You are using terms 'master' and 'slave' that do not exist in Chia architecture. See [Network-Architecture](https://github.com/Chia-Network/chia-blockchain/wiki/Network-Architecture).
> The
> 
> ```
> chia farm summary
> ```

> ```

on previous version it show local plots on slave harvester (right now i can see only master) and the better to add new command like 
chia plots summary  
or add to chia plots show informaion about count of plots 

Also, i think the better to add information about harvester status

**Comment by loppefaaret** [comment]
remote harvesters are only meant to be running the harvester service - we have added a communication lin between the farmer and harvester, although we are having a bit of trouble with it currently, the future is to be able to see relevant information about remote harvesters on the main farmer machine.
at best, this is an enhancement request, that aint happening, therefore im closing it down.
we already have multiple issues regarding various places with display issues of the new setup
