### ISSUE TITLE
join pool 

### ISSUE THREAD

**Issue by nabiesl** [Chia-Network/chia-blockchain#7324]
Hello, good morning, despite the pool in the new version, we have to remove the plots made from the cubes and create new plots?
![join-chia-pool](https://user-images.githubusercontent.com/86523027/125153767-e3a38880-e10a-11eb-865d-89127ecfcca8.png)

**Comment by rhernaus** [comment]
You can still solo farm your 'legacy' plots. 
If you want to use the official Chia pooling protocol that is shown in your screenshot then you have to make new plots with your Plot NFT encoded in them.

**Comment by nabiesl** [comment]
What is the reason for these names in the pool section? Amaranth aardwolf & scarlet squirrel
