### ISSUE TITLE
New NFT plots don't show on pool tab without refreshing plots [BUG]

### ISSUE THREAD

**Issue by Lowestofttim** [Chia-Network/chia-blockchain#7331]
**Describe the bug**
New NFT plots don't show on pool tab without refreshing plots

**To Reproduce**

Add a new NFT plot

**Expected behavior**
Does not appear in Pool tab plot count.

No matter how long i wait it will not update until i refresh plots in plots tab.

**Comment by Kryptoand** [comment]
all the same problem
https://github.com/Chia-Network/chia-blockchain/issues/7308

**Comment by Kryptoand** [comment]
the solucion it's the same-> https://github.com/Chia-Network/chia-blockchain/issues/7308

**Comment by almazrouei86** [comment]
Same issue with the same solution

**Comment by Andyaj** [comment]
same issue !! Please fix fast we cannot be awake 24/7

**Comment by extrasolarCHIA** [comment]
I got lots of invalid plots after update 1.2.0 all of a sudden

**Comment by extrasolarCHIA** [comment]
```
2021-07-11T00:52:00.605  chia.plotting.plot_tools         : ERROR    Failed to open file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot. Invalid file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot Traceback (most recent call last):
  File "chia\plotting\plot_tools.py", line 189, in process_file
ValueError: Invalid file E:\@FINALPLOTS\plot-k32-2021-07-07-21-11-54179b37bbbd16674b4d7e3c2d23bd60852822623ed1e56a5126b0a6aa12f637.plot

```
plots check shows them as invalid too

**Comment by Andyaj** [comment]
seriously this issue is over for 2days !! why would you create and issue with a release !! The only reason why i still stick to Hpool is that the main chia network is just not making enough effort to deliver anything on time and bug free !!! pool took for ever and ever and after all that i killed some basic functionalities and now we again wait around for fix.

**Comment by loppefaaret** [comment]
closing, dupe

**Comment by Keikunbr** [comment]
This problem persist in release 1.2.1.
