### ISSUE TITLE
[BUG]钱包连接不上

### ISSUE THREAD

**Issue by 988387069** [Chia-Network/chia-blockchain#7335]
打开1.2.0版本钱包一直在连接当中,持续了1个小时.我应该怎么处理.
![QQ图片20210710183224](https://user-images.githubusercontent.com/82623800/125159986-3766ae00-e1ad-11eb-85b3-903f2b5f0d60.png)

**Comment by LYY-LYY** [comment]
我的也连接不上， 是不是因为win7的缘故呀

**Comment by fireboy0526** [comment]
> 我的也连接不上， 是不是因为win7的缘故呀

Gene 在1.2.0出的时候已经有说win7已经不在支援了

**Comment by chiazhang** [comment]
备份或者删了用户文件夹的.chia目录试试咯

**Comment by LYY-LYY** [comment]
> 备份或者备份了用户文件夹的.chia目录实用程序

删除了，没用，看来需要更新系统了

**Comment by chiazhang** [comment]
文件多时间会长些，1小时实在太长了，删.chia并且联网还打不开的话，只有装新系统咯

**Comment by loppefaaret** [comment]
WINDOWS WALLET DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!

if the issue persists, please reopen - but please provide OS and Chia version used, and what CPU you have
