### ISSUE TITLE
[BUG]Plot always crash at 68% (bucket 57)

### ISSUE THREAD

**Issue by kikocaramelo** [Chia-Network/chia-blockchain#7336]
Plot always crash at 68% (bucket 57)
I'm in Chia 1.2.0, plotting for a pool. I'm using a Mac mini Intel withMacOs 10.15.7
I tried several plots all blocked.
I'm also using a PC with the same wallet and it works, everything OK on the PC.

**Comment by loppefaaret** [comment]
around 68% sounds like you are into phase3, where memory usage is topping - are you potentially running out of memory ?
could you provide the last few lines of the failed plotting log ? that could provide valuable information
turning this into a support discussion for now
