### ISSUE TITLE
no plots no pool [BUG]

### ISSUE THREAD

**Issue by aliaredo** [Chia-Network/chia-blockchain#7338]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by aliaredo** [comment]
![plots1](https://user-images.githubusercontent.com/49101164/125161802-b72c5280-e184-11eb-8703-5f40804f7e62.JPG)
![plots2](https://user-images.githubusercontent.com/49101164/125161804-b7c4e900-e184-11eb-8b5b-8896315bfbc6.JPG)
![pltos](https://user-images.githubusercontent.com/49101164/125161805-b85d7f80-e184-11eb-87b7-bafc623c3cf4.JPG)

**Comment by darekSTS** [comment]
Same issue here. Anybody has the solution to fix this ?

**Comment by guntoro2001** [comment]
yes i'm same problem

**Comment by loppefaaret** [comment]
what OS ?

**Comment by aliaredo** [comment]
windows 10

**Comment by loppefaaret** [comment]
try these 3 things, one at a time, and see if they help? 
WINDOWS COMPLETE CONFIG RESET

Close down the Chia app, and open up a PowerShell window, and execute the below commands one at a time:
```
mv ~\.chia\mainnet ~\.chia\old
cd ~\AppData\Local\chia-blockchain\app-1.2.0\resources\app.asar.unpacked\daemon\
.\chia.exe init
mv ~\.chia\old\db ~\.chia\mainnet\
mv ~\.chia\old\wallet ~\.chia\mainnet\
```

WINDOWS WALLET DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!

WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!

**Comment by jackdrod** [comment]
mv ~\.chia\mainnet ~\.chia\old
cd ~\AppData\Local\chia-blockchain\app-1.2.0\resources\app.asar.unpacked\daemon\
.\chia.exe init
mv ~\.chia\old\db ~\.chia\mainnet\
mv ~\.chia\old\wallet ~\.chia\mainnet\



ok this command 
my chia is good now 
farm and pool is ok now
thankyou
