### ISSUE TITLE
pool

### ISSUE THREAD

**Issue by nabiesl** [Chia-Network/chia-blockchain#7340]
What is the reason for these unusual names in the pool section? Amaranth aardwolf & scarlet squirrel
![Untitled](https://user-images.githubusercontent.com/86523027/125163497-3e0c0b80-e142-11eb-90eb-799eaef4add6.png)

**Comment by denisprovost** [comment]
Not a bug, just a choice of Chia team ;)

**Comment by loppefaaret** [comment]
Random names based on hash value

**Comment by nabiesl** [comment]
I deleted all my previous plots and connected the new plot to the pool and built nft why did not receive chia
There is something wrong with my work
I will send the image of the pool I created
But as before, the time to win shows, for example, 6 years, despite the construction of plots connected to the pool
    On Monday, July 12, 2021, 04:47:53 AM PDT, loppefaaret ***@***.***> wrote:  
 
 


Closed #7340.
