### ISSUE TITLE
[BUG] Creating Plot NFT for Self Pooling keeps waiting

### ISSUE THREAD

**Issue by tongtian0925** [Chia-Network/chia-blockchain#7344]
created self pooling when my node is not fully synced

The transaction is not confirmed because of the sync.

Then I choose delete unconfirmed transactions

The self pool keeps hung there , there is no way to delete them

If we can have a feature to delete those pools

![chia-bug](https://user-images.githubusercontent.com/44788098/125167026-6872be80-e16c-11eb-89c8-40f046f71615.png)

**Comment by ShadXo** [comment]
Mine was gone after deleting the "AppData\Roaming\Chia Blockchain" folder, I think its caching it somewhere.

**Comment by damonsro** [comment]
Mismo problema
