### ISSUE TITLE
[BUG]CHIA团队是脑残吗

### ISSUE THREAD

**Issue by 988387069** [Chia-Network/chia-blockchain#7346]
钱包白屏久不久白屏或者卡顿
现在打开钱包,一直都连接中.
这些问题从3月19日至今还存在.

真系脑残

**Comment by ajie1015** [comment]
脑残的 一P ，这个。1.2.0 就tm 没测试过，升级版本后 所有的收割机和主节点全部断了，提示 无效的协议消息。日

**Comment by chiazhang** [comment]
白屏一般是超资源了，例如内存不够，p盘时资源占满的时候特别容易白屏。打开钱包连接中一般是没网，第一次启动最好连下网，以后不用。收割机估计是1.2有变化需要重弄咯

**Comment by overlords** [comment]
多线程P图和官方客户端一起跑就死机。 资源跑满，一个挖矿客户端要开全节点，技术是不是比hp还垃圾

**Comment by loppefaaret** [comment]
potential dupe of #7335
