### ISSUE TITLE
[BUG]plot NFTs not show on another computer using same key

### ISSUE THREAD

**Issue by brianjojoray** [Chia-Network/chia-blockchain#7347]
**Describe the bug**
plot NFTs not showed on another machine using same private key after synced.

**To Reproduce**

I have computer A and B,using the same private key
1. on computer A, I use Chia GUI to Create plot NFTs and farm.
2. on computer B, I opened Chia GUI and synced. and I click pool tab, there isn't any plot NFTs showed.

**Expected behavior**
plots NFTs will be showed on another machine use same key.

**Screenshots**

**Desktop**

- OS:  windows
- OS Version/Flavor:  windows 10 pro
- CPU: Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz

**Additional context**

**Comment by iWhiteHatt** [comment]
I have exactly the same issue, help

**Comment by denisprovost** [comment]
Same issue for me!
OS: Ubuntu 21.06

**Comment by pchacker** [comment]
I have exactly the same issue, help

**Comment by zeldax54** [comment]
I have the same problem. I have one pc with a NTF then i create a second node in other pc and import 24 words, NTF from "main" pc is not showing there but if i create a nft in second machine is synced to "main" ina  few minutes

**Comment by iWhiteHatt** [comment]
> I have the same problem. I have one pc with a NTF then i create a second node in other pc and import 24 words, NTF from "main" pc is not showing there but if i create a nft in second machine is synced to "main" ina few minutes

I made the exactly same thing and the result was the same

**Comment by Hbitvof** [comment]
Same problem here.

**Comment by emlowe** [comment]
If your second computer was running the prior version (1.1.7 or below) at the time you made your PlotNFT, it will likely not appear when you upgrade your second computer to 1.2 - this is because your second computer will sync past the point on the blockchain where the PlotNFT is created while on the old version. The fix to this is to resync your wallet.

**Comment by brianjojoray** [comment]
> If your second computer was running the prior version (1.1.7 or below) at the time you made your PlotNFT, it will likely not appear when you upgrade your second computer to 1.2 - this is because your second computer will sync past the point on the blockchain where the PlotNFT is created while on the old version. The fix to this is to resync your wallet.

it sounds like the way of mine
how i can do that?
can i delete the files under $home$\.chia\mainnet\wallet\db\ on my second computer.
and copy there files from the first one?

**Comment by denisprovost** [comment]
The two solutions has been tested:

- Delete wallet db on second machine and copy wallet db of first machine for fast resync -> FAIL
- Delete wallet db on second machine and start normal resync -> FAIL

best regards

**Comment by Hbitvof** [comment]
That was not the complete solution for me. I did the resync part but the NTF didn't show up. I took the part of the config.yaml that contains the NFT configuration from my original system and copied it to the new one. This solved the problem for me.

**Comment by zeldax54** [comment]
the @emlowe solution work for mi, after a day of wallet sync I am able to see my nft in the second machine, copy wallet db from one computer to another will fail.

**Comment by brianjojoray** [comment]
> the @emlowe solution work for mi (delete all inside wallet folder and re-sync), after a day of wallet sync I am able to see my nft in the second machine, copy wallet db from one computer to another will fail.

But i am fixed the problem by copying wallet db from my first computer.
I do that by closed my chia application at first .
My question:
1. There are 4 files under wallet db,  do you copy all of that?
2. Number of Plots not synced to the second computer, is that normal?
3. Current Points Balance is synced to the second computer,  is the Points Balance add all of my plots on different computer?

**Comment by zeldax54** [comment]
Well, the solution of copy wallet files don't work for me, about the plotter count, after refresh plotters under plotter tag I can see all plots updated(local and harvester), all info about plots and points(local and harvester) can be see in the nft card. Also you can see the connected harversters under farm->show advanced options

**Comment by shamil1973** [comment]
Same problem on Windows 10 -> Windows 10

**Comment by emlowe** [comment]
Check your config.yaml file under the pool:pool_list section. The PlotNFT information is locally stored in the config.yaml file - under the pool: pool_list section in the config.yaml. It is derived from the blockchain during syncing. You cannot copy over the wallet.db to resolve this, as this does not cause a resync which should put the information in the config.yaml. You can, however, copy over the pool_list section of the config.yaml file - and this should resolve your issue.
