### ISSUE TITLE
Loading Plot NFT................

### ISSUE THREAD

**Issue by neurocodigomecatronica** [Chia-Network/chia-blockchain#7369]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

Greetings, since I installed version 1.2, I only get the message (loading NTF) this has been going on for days. The node is 100% synchronized. However in the pool section I can not advance, nor create. I need your help

**Comment by loppefaaret** [comment]
how about the wallet, is that the same height as the node ?

**Comment by emlowe** [comment]
Duplicate of #7361
