### ISSUE TITLE
 Only this loading plot NFT

### ISSUE THREAD

**Issue by neurocodigomecatronica** [Chia-Network/chia-blockchain#7371]
**Describe the bug**

![chia erro nft](https://user-images.githubusercontent.com/20406848/125195658-3ae54e00-e21c-11eb-8ce6-545d50c285c5.png)

**Comment by loppefaaret** [comment]
if you select the wallet, is the wallet synced to the same height as the full node ?

**Comment by emlowe** [comment]
Duplicate of #7361
