### ISSUE TITLE
GUI keep pop up wallet status

### ISSUE THREAD

**Issue by maxchock** [Chia-Network/chia-blockchain#7372]
Hi, I've updated to version 1.2.0. and the GUI keep popping out the wallet status.

![image](https://user-images.githubusercontent.com/59406510/125199068-23977680-e297-11eb-9625-6cd892d668ad.png)

**Comment by loppefaaret** [comment]
first try and reset your configuration, while preserving your databases
WINDOWS COMPLETE CONFIG RESET

Close down the Chia app, and open up a PowerShell window, and execute the below commands one at a time:
```
mv ~\.chia\mainnet ~\.chia\old
cd ~\AppData\Local\chia-blockchain\app-1.2.0\resources\app.asar.unpacked\daemon\
.\chia.exe init
mv ~\.chia\old\db ~\.chia\mainnet\
mv ~\.chia\old\wallet ~\.chia\mainnet\
```
if it did not work, try removing the wallet database:
WINDOWS WALLET DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!
