### ISSUE TITLE
[BUG]PlotNFT not automatically being entered into config.yaml on client reinstall

### ISSUE THREAD

**Issue by gryan315** [Chia-Network/chia-blockchain#7373]
Two users in the pool I am in have lost their initial chia install and had to reinstall and re-sync from scratch. When synced, they became concerned because their pools tab did not show their pool contract. I walked them through looking up the plotnft details via command line and how to manually add those values to the config.yaml, but it seems like this is something the client should be able to do on it's own.

1. Remove entire .chia directory (as would be the case with a drive failure containing this directory)
2. Re-initialize chia client with 24 word mnemonic
3. Sync blockchain and wallet
4. See no pool contracts under pools tab

**Expected behavior**
Since the plotnft is on the blockchain and tied to your key, it should automatically be able to populate itself in the config.yaml on initial sync. If there is a way to force it to do so, it should be documented.

- OS: Both users were on windows 10

**Comment by emlowe** [comment]
To clarify, these users in the UI had nothing in the Pool "Tab" - however, if you did `chia plotnft show` everything looked correct?

**Comment by Lowestofttim** [comment]
Same issue, had to re install and only way to find my old NFT pool is to create a new one for the same pool. I now have three NFT plots for the same pool

**Comment by gryan315** [comment]
> To clarify, these users in the UI had nothing in the Pool "Tab" - however, if you did `chia plotnft show` everything looked correct?

Yes, I walked them through the commands and they were able to see their pooling information with `chia plotnft show`. One of them was going to attempt to manually input the hashes into their config.yaml, but I have not heard back if they were successful.

**Comment by emlowe** [comment]
That is very strange because `chia plotnft show` *also* pulls the information from config.yaml - if the CLI is working there must be a pools_list in config.yaml

**Comment by gryan315** [comment]
Just heard back, using command line to join a different pool caused all 3 of their plotnfts to repopulate the config.yaml and then show up in GUI.

**Comment by mariano54** [comment]
You should never change the config.yaml manually do add pool info. This is done automatically by the Chia app. Perhaps they needed to do a restart so the 24 word mnemonic gets added to the farmer

**Comment by gryan315** [comment]
> You should never change the config.yaml manually do add pool info. This is done automatically by the Chia app. Perhaps they needed to do a restart so the 24 word mnemonic gets added to the farmer

In both cases the original installation was lost, so they had to reinstall, input the private key, and sync from scratch. The pool info was not automatically added until one user used the command line to switch pools.

**Comment by Lowestofttim** [comment]
I have not updated to 2.1 yet but i susspect i will have to do the same again and I will then have four NFT's created for one pool. I will update when i have updated.

**Comment by TheRealAngelus** [comment]
I have the same issue. I transferred full-node to another pc. They are both Windows 10. I re-initialize chia client with a 24-word mnemonic. My node and wallet are synced but under the pool tab, there are no NFT's. However, when I type ".\chia plotnft show" I can see 2 NFT's one of them is self pooling, the other is farming to pool

**Comment by gryan315** [comment]
> I have the same issue. I transferred full-node to another pc. They are both Windows 10. I re-initialize chia client with a 24-word mnemonic. My node and wallet are synced but under the pool tab, there are no NFT's. However, when I type ".\chia plotnft show" I can see 2 NFT's one of them is self pooling, the other is farming to pool. BTW I'm using 1.2.1

One possible solution to at least get it to show up is to use your solo plotnft to join and leave a pool by CLI. Hopefully an actual fix will be found instead of a workaround.

**Comment by TheRealAngelus** [comment]
Now, I create a new NFT. After that, all NFT's I have shown up under pool tab and points balance is increasing.
