### ISSUE TITLE
[BUG] ¨Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by HoracioF** [Chia-Network/chia-blockchain#7385]
**Describe the bug**
After not seeing any of my plots I created before upgrading to 1.2.1 on the GUI, I started trying the  chia CLI commands, they return some output but at the end they show ¨Segmentation fault (core dumped)" 

**To Reproduce**

Open a terminal
Go to your chia-blockchain folder
. ./activate
chia plotnft show   

**Expected behavior**
No faults and see my plots on the chia GIUI

**Screenshots**
![image](https://user-images.githubusercontent.com/8117289/125222018-314cfc00-e297-11eb-8c92-dd111cbe7039.png)

**Desktop**

- OS: Centos 8
- CPU: Intel i7 10Gen

**Additional context**
Upgraded to 1.2.1.dev0
Still plot with no errors on each plot log

**Comment by loppefaaret** [comment]
could you provide anything on the seg fault itself, from the system logs ?

**Comment by HoracioF** [comment]
Hi @loppefaaret Let me know if this helps
![image](https://user-images.githubusercontent.com/8117289/125291166-18703500-e2ef-11eb-8e15-46f0fc757264.png)

**Comment by HoracioF** [comment]
I noticed that the Chia harvester process is in zombie status, so I checked the logs and found this:
Process 5761 (chia_harvester) of user 1000 dumped core.

Stack trace of thread 5761:
#0  0x00007f928f5fa47b simplequeue_dealloc (_queue.cpython-37m-x86_64-linux-gnu.so)
#1  0x0000000000464916 delitem_common (python3.7)
#2  0x0000000000466057 _PyDict_DelItem_KnownHash (python3.7)
#3  0x0000000000420a87 _PyEval_EvalFrameDefault (python3.7)
#4  0x00000000004e130c PyEval_EvalFrameEx (python3.7)
#5  0x0000000000439e5f _PyFunction_FastCallDict (python3.7)
#6  0x000000000043ba8e object_vacall (python3.7)
#7  0x000000000043bddc PyObject_CallFunctionObjArgs (python3.7)
#8  0x00000000004d905f handle_callback (python3.7)
#9  0x0000000000481e22 subtype_dealloc (python3.7)
#10 0x0000000000479baa set_dealloc (python3.7)
#11 0x0000000000462fed dict_dealloc (python3.7)
#12 0x0000000000481cbf subtype_dealloc (python3.7)
#13 0x000000000041eab4 frame_dealloc (python3.7)
#14 0x00000000004e0e0a _PyEval_EvalCodeWithName (python3.7)
#15 0x000000000043a113 _PyFunction_FastCallKeywords (python3.7)
#16 0x0000000000425fb2 call_function (python3.7)
#17 0x0000000000599c42 gen_send_ex (python3.7)
#18 0x000000000042560e _PyEval_EvalFrameDefault (python3.7)
#19 0x0000000000599c42 gen_send_ex (python3.7)
#20 0x000000000042560e _PyEval_EvalFrameDefault (python3.7)
#21 0x0000000000599c42 gen_send_ex (python3.7)
#22 0x00007f928f8837cf task_step_impl (_asyncio.cpython-37m-x86_64-linux-gnu.so)
#23 0x000000000043a7e1 _PyObject_FastCallKeywords (python3.7)
#24 0x000000000050cada context_run (python3.7)
#25 0x000000000043ad55 _PyMethodDef_RawFastCallDict (python3.7)
#26 0x000000000043b03e _PyCFunction_FastCallDict (python3.7)
#27 0x0000000000426ff0 do_call_core (python3.7)
#28 0x000000000041e953 function_code_fastcall (python3.7)
#29 0x0000000000426b75 call_function (python3.7)
#30 0x000000000041e953 function_code_fastcall (python3.7)
#31 0x0000000000426b75 call_function (python3.7)
#32 0x000000000041e953 function_code_fastcall (python3.7)
#33 0x0000000000426b75 call_function (python3.7)
#34 0x000000000041e953 function_code_fastcall (python3.7)
#35 0x0000000000426b75 call_function (python3.7)
#36 0x00000000004e130c PyEval_EvalFrameEx (python3.7)
#37 0x000000000043a113 _PyFunction_FastCallKeywords (python3.7)
#38 0x0000000000428747 call_function (python3.7)
#39 0x00000000004e130c PyEval_EvalFrameEx (python3.7)
#40 0x0000000000439f53 _PyFunction_FastCallDict (python3.7)
#41 0x000000000042159f do_call_core (python3.7)
#42 0x000000000041e953 function_code_fastcall (python3.7)
#43 0x0000000000425fb2 call_function (python3.7)
#44 0x00000000004e130c PyEval_EvalFrameEx (python3.7)
#45 0x00000000004e1553 PyEval_EvalCodeEx (python3.7)
#46 0x0000000000512a82 run_mod (python3.7)
#47 0x0000000000512c03 PyRun_SimpleFileExFlags (python3.7)
#48 0x000000000042ec51 pymain_run_file (python3.7)
#49 0x000000000042ee69 _Py_UnixMain (python3.7)
#50 0x00007f9293cac493 __libc_start_main (libc.so.6)
#51 0x0000000000428d5e _start (python3.7)

Stack trace of thread 5968:
#0  0x00007f92947e0206 start_thread (libpthread.so.0)
#1  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5885:
#0  0x00007f92947e8bd6 do_futex_wait.constprop.1 (libpthread.so.0)
#1  0x00007f92947e8cc8 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x000000000051d5e2 PyThread_acquire_lock_timed (python3.7)
#3  0x00007f928f5fa688 _queue_SimpleQueue_get_impl (_queue.cpython-37m-x86_64-linux-gnu.so)
#4  0x00007f928f5fa856 _queue_SimpleQueue_get (_queue.cpython-37m-x86_64-linux-gnu.so)
#5  0x000000000043a500 _PyMethodDef_RawFastCallKeywords (python3.7)
#6  0x000000000043a62a _PyCFunction_FastCallKeywords (python3.7)
#7  0x0000000000428223 call_function (python3.7)
#8  0x000000000041e953 function_code_fastcall (python3.7)
#9  0x000000000043a06c _PyFunction_FastCallDict (python3.7)
#10 0x000000000042159f do_call_core (python3.7)
#11 0x000000000041e953 function_code_fastcall (python3.7)
#12 0x0000000000426b75 call_function (python3.7)
#13 0x000000000041e953 function_code_fastcall (python3.7)
#14 0x0000000000426b75 call_function (python3.7)
#15 0x000000000041e953 function_code_fastcall (python3.7)
#16 0x000000000043a06c _PyFunction_FastCallDict (python3.7)
#17 0x000000000043b41a _PyObject_Call_Prepend (python3.7)
#18 0x000000000043b122 PyObject_Call (python3.7)
#19 0x0000000000561253 t_bootstrap (python3.7)
#20 0x000000000051d317 pythread_wrapper (python3.7)
#21 0x00007f92947e014a start_thread (libpthread.so.0)
#22 0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5886:
#0  0x00007f92947e8bd6 do_futex_wait.constprop.1 (libpthread.so.0)
#1  0x00007f92947e8cc8 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x000000000051d5e2 PyThread_acquire_lock_timed (python3.7)
#3  0x00007f928f5fa688 _queue_SimpleQueue_get_impl (_queue.cpython-37m-x86_64-linux-gnu.so)
#4  0x00007f928f5fa856 _queue_SimpleQueue_get (_queue.cpython-37m-x86_64-linux-gnu.so)
#5  0x000000000043a500 _PyMethodDef_RawFastCallKeywords (python3.7)
#6  0x000000000043a62a _PyCFunction_FastCallKeywords (python3.7)
#7  0x0000000000428223 call_function (python3.7)
#8  0x000000000041e953 function_code_fastcall (python3.7)
#9  0x000000000043a06c _PyFunction_FastCallDict (python3.7)
#10 0x000000000042159f do_call_core (python3.7)
#11 0x000000000041e953 function_code_fastcall (python3.7)
#12 0x0000000000426b75 call_function (python3.7)
#13 0x000000000041e953 function_code_fastcall (python3.7)
#14 0x0000000000426b75 call_function (python3.7)
#15 0x000000000041e953 function_code_fastcall (python3.7)
#16 0x000000000043a06c _PyFunction_FastCallDict (python3.7)
#17 0x000000000043b41a _PyObject_Call_Prepend (python3.7)
#18 0x000000000043b122 PyObject_Call (python3.7)
#19 0x0000000000561253 t_bootstrap (python3.7)
#20 0x000000000051d317 pythread_wrapper (python3.7)
#21 0x00007f92947e014a start_thread (libpthread.so.0)
#22 0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5891:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5892:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5893:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5895:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5896:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5904:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5897:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5898:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5905:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5915:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5947:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5937:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5969:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5917:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5939:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5940:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5936:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5941:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5935:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5957:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5938:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5931:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5916:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5970:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5932:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5971:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5903:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

Stack trace of thread 5914:
#0  0x00007f92947e962c __lll_lock_wait_private (libpthread.so.0)
#1  0x00007f92947df4bf __deallocate_stack (libpthread.so.0)
#2  0x00007f92947e03dc start_thread (libpthread.so.0)
#3  0x00007f9293d85dc3 __clone (libc.so.6)

**Comment by HoracioF** [comment]
I restarted the machine, and this is what I get when starting chia:
(venv) [hfilet@CoinFS chia-blockchain]$ chia start all
Daemon not started yet
Starting daemon
chia_harvester: started
chia_timelord_launcher: started
chia_timelord: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Segmentation fault (core dumped)
(venv) [hfilet@CoinFS chia-blockchain]$ Traceback (most recent call last):
  File "/home/hfilet/chia-blockchain/venv/bin/chia_timelord_launcher", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_timelord_launcher')())
  File "/home/hfilet/chia-blockchain/chia/timelord/timelord_launcher.py", line 107, in main
    loop.run_until_complete(spawn_all_processes(config, net_config))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/hfilet/chia-blockchain/chia/timelord/timelord_launcher.py", line 85, in spawn_all_processes
    await asyncio.gather(*awaitables)
  File "/home/hfilet/chia-blockchain/chia/timelord/timelord_launcher.py", line 45, in spawn_process
    path_to_vdf_client = find_vdf_client()
  File "/home/hfilet/chia-blockchain/chia/timelord/timelord_launcher.py", line 39, in find_vdf_client
    raise FileNotFoundError("can't find vdf_client binary")
FileNotFoundError: can't find vdf_client binary
(venv) [hfilet@CoinFS chia-blockchain]$ cd chia-blockchain-gui
(venv) [hfilet@CoinFS chia-blockchain-gui]$ npm run electron &
[1] 4762
(venv) [hfilet@CoinFS chia-blockchain-gui]$ 
> electron
> electron .

/home/hfilet/chia-blockchain/app.asar.unpacked/daemon
false
startUrl file:///home/hfilet/chia-blockchain/chia-blockchain-gui/build/renderer/index.html
/home/hfilet/chia-blockchain/app.asar.unpacked/daemon
false
/home/hfilet/chia-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../chia/daemon/server.py
child process success
(node:4786) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Chia directory /home/hfilet/.chia/mainnet
/home/hfilet/.chia/mainnet already exists, no migration action taken
No cert
Have cert
closing code: null

**Comment by HoracioF** [comment]
I restarted after upgrading to 1.2.2.dev0

**Comment by hoffmang9** [comment]
Do not `start all` - you only need `start farmer` as running a timelord is not recommended.

**Comment by HoracioF** [comment]
> `start farmer`

Now I'm on chia 1.2.2, I stopped everything and then just tried ¨chia start farmer":
(venv) [hfilet@CoinFS chia-blockchain]$ chia start farmer
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
**Segmentation fault (core dumped)**
and the harvester still shows as a zombie keep getting the Segmentation fault.

2021-07-19T00:17:10.715 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version

**Comment by HoracioF** [comment]
I found that I was using Python 3.6 and not 3.7, that seems to be the whole issue all the time :) my bad.
Now I have chia 1.3.0 and Python 3.7 (as indicated as the minimum version) and no more errors, back in business :)

**Comment by HoracioF** [comment]
It seems the whole  issue was caused by an older version of Python, I had 3.6.8, so after I upgraded to Python 3.7.7 and also chia 1.3.0 no more issues.
