### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PositiveK** [Chia-Network/chia-blockchain#7386]
Latest version
Node synced
Wallet synced
*Plots (loading forever)
*Farm Overview (loading forever)
*Pool (loading forever)

tried everything i could think of, no joy.
any suggestions

Windows 10

**Comment by loppefaaret** [comment]
try these 3 steps, one after the other, checking if one step worked:
WINDOWS COMPLETE CONFIG RESET

Close down the Chia app, and open up a PowerShell window, and execute the below commands one at a time:
```
mv ~\.chia\mainnet ~\.chia\old
cd ~\AppData\Local\chia-blockchain\app-1.2.0\resources\app.asar.unpacked\daemon\
.\chia.exe init
mv ~\.chia\old\db ~\.chia\mainnet\
mv ~\.chia\old\wallet ~\.chia\mainnet\
```

WINDOWS WALLET DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!

WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!

**Comment by loppefaaret** [comment]
just noting that if you have reset the `config.yaml` file as i descripbed above, you need to resync you wallet db!

**Comment by PositiveK** [comment]
Thanks, i replaced the db with one from another farmer, synced really fast

Regards Al

**Comment by loppefaaret** [comment]
im assuming that means this is a closed issue now

**Comment by PositiveK** [comment]
thanks again for your help

Regards Al

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
