### ISSUE TITLE
[BUG] 我在尝试用两个钱包地址切换，点击后无法成功切换；windows 1.2.0

### ISSUE THREAD

**Issue by supercating** [Chia-Network/chia-blockchain#7396]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by loppefaaret** [comment]
what happens after you click the other key in the "Keys" tab ?
