### ISSUE TITLE
[BUG]我用新钱包P好的图，依然可以用老钱包进行耕种.......

### ISSUE THREAD

**Issue by xiaoduola666** [Chia-Network/chia-blockchain#7397]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by obeykarma** [comment]
应该是p图内置了pool contract的原因吧

**Comment by loppefaaret** [comment]
I'm not sure how this is a problem ? i afraid something is lost in translation
perhaps you could provide screenshot of the acutal bug that is happening ?

**Comment by xiaoduola666** [comment]
我再次确认了一下，发现问题已经小时，应该是我新钱包没有同步完成，所以我依然可以看到我之前的plot文件；
