### ISSUE TITLE
[BUG] After update to Chia 1.2.0 Wallet balance shows 0

### ISSUE THREAD

**Issue by mateuszdgrobelny** [Chia-Network/chia-blockchain#7401]
After install new 1.2.0 Chia blockchain my wallet balance shows 0XCH, neither it shows any history etc.
I had 2XCH mined on this wallet and 1xch send to exchange. Remaining 1 is missing. 
Gui does not show any plots either and when i try manually add folder it just do nothing
I have another wallet that still shows balance but im afraid to update gui as it ma be cleared as well.

**Comment by BluefireXD** [comment]
hmm did you try a clean install (deleting chia folders etc) ? maybe this will solve the wallet issue

**Comment by mateuszdgrobelny** [comment]
its running sync now. and after few hours i can see wallet balance being update. it shows all i earned so far but does not show what i spend jet.

**Comment by mariano54** [comment]
You need to wait for it to sync to see all transactions.

**Comment by navyfeng** [comment]
> You need to wait for it to sync to see all transactions.

Same problem(version 1.2.11)。Reinstalled wallet has been synced and shows all transactions, but the balance show zero. After received  1000 mojo  , wallet show just 1000mojo. The previous balance disappeared

**Comment by keliew** [comment]
> > You need to wait for it to sync to see all transactions.
> 
> Same problem(version 1.2.11)。Reinstalled wallet has been synced and shows all transactions, but the balance show zero. After received 1000 mojo , wallet show just 1000mojo. The previous balance disappeared

Good to check the transaction records.

**Comment by navyfeng** [comment]
> > > You need to wait for it to sync to see all transactions.
> > 
> > 
> > Same problem(version 1.2.11)。Reinstalled wallet has been synced and shows all transactions, but the balance show zero. After received 1000 mojo , wallet show just 1000mojo. The previous balance disappeared
> 
> Good to check the transaction records.

Wallet synced to peak, and show all transactions.

**Comment by keliew** [comment]
> > > > You need to wait for it to sync to see all transactions.
> > > 
> > > 
> > > Same problem(version 1.2.11)。Reinstalled wallet has been synced and shows all transactions, but the balance show zero. After received 1000 mojo , wallet show just 1000mojo. The previous balance disappeared
> > 
> > 
> > Good to check the transaction records.
> 
> Wallet synced to peak, and show all transactions.

So, am sure the transaction records would show that there was an (unknown) activity. It didn't disapppear?

**Comment by navyfeng** [comment]
> > > > > You need to wait for it to sync to see all transactions.
> > > > 
> > > > 
> > > > Same problem(version 1.2.11)。Reinstalled wallet has been synced and shows all transactions, but the balance show zero. After received 1000 mojo , wallet show just 1000mojo. The previous balance disappeared
> > > 
> > > 
> > > Good to check the transaction records.
> > 
> > 
> > Wallet synced to peak, and show all transactions.
> 
> So, am sure the transaction records would show that there was an (unknown) activity. It didn't disapppear?

Yes, transaction records are normal, but the balance is zero. The wallet is installed on a new machine.
