### ISSUE TITLE
xch

### ISSUE THREAD

**Issue by nabiesl** [Chia-Network/chia-blockchain#7414]
My pool has been created and a number of plots have been built and plots are being built.
![Untitled](https://user-images.githubusercontent.com/86523027/125307977-641de100-e2e5-11eb-8ebf-6c4860e08e96.png)
![Untitled1](https://user-images.githubusercontent.com/86523027/125307995-6718d180-e2e5-11eb-9313-296baf5c810b.png)
Is there a problem or is the procedure correct?

**Comment by emlowe** [comment]
Please specify what the defect or bug is - there is no bug here
