### ISSUE TITLE
[BUG] New Receive address in wallet after starting "solo" pool plotting. Missing 1,74XCH income in history?

### ISSUE THREAD

**Issue by BluefireXD** [Chia-Network/chia-blockchain#7415]
**Describe the bug**
After starting plotting with the new 1.2.0 version i selected "solo ..." because i dont want to join a pool right now and it seems chia automatically created a new NFT in the background. 
After that i saw that on the plotter machine there is an outgoing transaction of 0,000...1XCH and on my farmer machine suddenly an incoming transaction of 1,74999.. XCH appears. This 1,74 XCH went to a receive address which is not listed as my receive address in my wallet (its also not the address of the plot nft) and i also have this 1,74 XCH not in my wallet, only in the history. The 1,74 XCH are missing :( 
Also my shown receive address in the walled  changed. All my solo farmed coins with old plots went to a different receive address then the current receive address in my wallet. Means my receive address changed after starting with pool plotting??? 
What happend with my old receive address? 

P.S i don't use third party tools for plotting/farming. i only use vanilla chia gui.

**To Reproduce**

1. Install Chia 1.2.0
2. Start the first time pool plotting but select "solo.." and don't join a pool
3. wait a few min and check your wallet history 
4. confusing stuff will appear in the history on plotting and farmer machines 

**Expected behavior**
Getting the 1,74 XCH or a correct wallet history

**Screenshots**
![Chia Blockchain](https://user-images.githubusercontent.com/12106363/125315421-6872ea00-e337-11eb-8f21-64a165374ec1.png)

**Desktop**
- OS: Windows
- OS Version/Flavor: 10
- CPU: i7 8700k
- Chia: 1.2.0
- Third party plotting/farming software: No

**Comment by shamil1973** [comment]
I see the same thing, but I can't understand what it is

**Comment by MaximusChia** [comment]
Bad adresses management, yes there is no reason to create a new wallet adress. but your older adresses must be own to you.
Lacking feature to show a list of my adresses.

**Comment by mariano54** [comment]
This is not a bug, it's due to change transactions: https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-coin-model

Your wallet will not show outgoing transactions when syncing back up. When you create a plot NFT, you spend a 1.75 coin and create two coins: a 1 mojo coin for the NFT and a 1.74999.. change coin back to yourself
