### ISSUE TITLE
[BUG] windows 7 can't running on Chia 1.20, but 1.17 is no problem.

### ISSUE THREAD

**Issue by apeter0** [Chia-Network/chia-blockchain#7417]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by emlowe** [comment]
Windows 7 is no longer supported and is deprecated in 1.2 (this is because Python 3.9 has deprecated Windows 7)

**Comment by figvam** [comment]
@apeter0: FYI #7222 has a workaround in the additional notes.
