### ISSUE TITLE
Joining Pool before Sync - Pool Stuck in "Waiting for the transaction to be confirmed" due to Chia application closed [BUG]

### ISSUE THREAD

**Issue by Ad31an** [Chia-Network/chia-blockchain#7421]
**Describe the bug**
Joining Pool before Sync: Pool Stuck in "Waiting for the transaction to be confirmed" due to Chia Blockchain application closed.

**To Reproduce**

1. Go to Pool before Sync is done.
2. Click on Add a Plot NFT | Connect to pool | CREATE
3. Message appear: Waiting for the transaction to be confirmed 
4. Close "Chia Blockchain"
5. Open "Chia Blockchain"

**Expected behavior**
Wait for "Chia Blockchain" to be Sync.
Transaction will be confirmed | Pool successfully joined.

**Screenshots**
![image](https://user-images.githubusercontent.com/68820422/125331082-2efaa880-e350-11eb-8d5a-6c472e03c93c.png)

**Desktop**
Desktop OptiPlex 7040

- OS: Windows 10 Pro 64-bit
- OS Version/Flavor: 10.0, Build 19043
- CPU: i7-6700 CPU @ 3.40GHz (8CPUs)
**Additional context**
After 24 hours "Chia Blockchain" was reinstalled and Pool remain stuck with the subject message. 
Issue due not appear on second PC that is using the same private key.
Pool cannot be removed.

**Comment by Plopsi** [comment]
you could try the CLI with "chia wallet delete_unconfirmed_transactions"

without warranties

**Comment by Ad31an** [comment]
Without success (unconfirmed transaction NOT deleted)
![image](https://user-images.githubusercontent.com/68820422/125356276-a9d2bc00-e36e-11eb-9148-333e1c07137f.png)

**Comment by Plopsi** [comment]
it says your wallet was not started... give it some time and let it sync up - you can let the GUI running when using the CLI

**Comment by Zeesy** [comment]
Having the same issue after joining before sync. Wallet and full node are synced, but I'm stuck in "Waiting for the transaction to be confirmed".

**Comment by Xziped** [comment]
i have the same problem for about 2 weeks now with full syncronized node/wallets. following error get spamed every second in the debug.log :
2021-07-15T07:45:05.407 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/x/chia-blockchain/chia/rpc/rpc_server.py", line 212, in safe_handle
    response = await self.ws_api(message)
  File "/home/x/chia-blockchain/chia/rpc/rpc_server.py", line 203, in ws_api
    return await f(data)
  File "/home/x/chia-blockchain/chia/rpc/wallet_rpc_api.py", line 626, in get_transaction
    raise ValueError(f"Transaction 0x{transaction_id.hex()} not found")
ValueError: Transaction 0x11a3e23ff3abfd48ad94ac00f88cd2a0c3eacbb7cfcc8356740fd43c9f2ef536 not found

i didnt find any way to delete the pending transaction, not even with "chia wallet delete_unconfirmed_transactions"

**Comment by Ad31an** [comment]
> it says your wallet was not started... give it some time and let it sync up - you can let the GUI running when using the CLI

I wait for 2 days and try couple of times but subject issue still reproduce, I didn't find any way to delete the pending transaction.

**Comment by flashpoint1985** [comment]
Have same issue here, it's been there since days, but only on 1 of my PCs, I have 3 PCs with same account key.
![Capture](https://user-images.githubusercontent.com/68688805/126037922-307c0f66-fed2-454a-9cb6-dbc39731cc34.PNG)

**Comment by MarielaEckl** [comment]
The same thing happens to me, my wallet does not synchronize and that is why the pool never receives the payment and therefore I cannot make anything progress ...

**Comment by austinborden** [comment]
I was having this issue until I clicked "Add a Plot NFT" and tried to re-add the same pool. Once the transaction went through the original pending transaction no longer appeared.

**Comment by flashpoint1985** [comment]
I have same problem and that's eu1.pool.space too. It's been weeks it's working fine and sure everything is synced but this annoying waiting screen is yet there.
Are you guys get this error too when you try to connect to this pool again?
![Capture](https://user-images.githubusercontent.com/68688805/130315453-5801b0da-12ec-47aa-a06e-9116d176f09b.PNG)

**Comment by flashpoint1985** [comment]
Never mind I found the solution:
https://github.com/Chia-Network/chia-blockchain/issues/7581#issuecomment-883826414

**Comment by Ad31an** [comment]
Found the solution: #7581 (comment)

1. Close GUI
2. Enter "C:\Users\**USERNAME**\AppData\Roaming\Chia Blockchain\Local Storage"
3. Delete folder "leveldb"
4. Start GUI
