### ISSUE TITLE
[BUG] New chia version 1.2.1 cant be downloaded. It still downloads 1.2.0

### ISSUE THREAD

**Issue by BluefireXD** [Chia-Network/chia-blockchain#7423]
https://www.chia.net/download/ 
Still shows and downloads version 1.2.0

**Comment by ogunkakisim** [comment]
i think not added yet. calm down :)

**Comment by Plopsi** [comment]
the windows installer is already on the AWS bucket (but not officially linked yet) - but the docker is still old :/ - 1 hr and counting, they need to streamline the release-workflow :D

**Comment by Plopsi** [comment]
https://download-chia-net.s3-us-west-2.amazonaws.com/install/ChiaSetup-1.2.1.exe (windows)
https://download-chia-net.s3-us-west-2.amazonaws.com/install/Chia-1.2.1.dmg (intel mac)
https://download-chia-net.s3-us-west-2.amazonaws.com/install/Chia-1.2.1-arm64.dmg (M1 mac)
https://download-chia-net.s3-us-west-2.amazonaws.com/install/chia-blockchain_1.2.1_amd64.deb (ubuntu/debian x64)
https://download-chia-net.s3-us-west-2.amazonaws.com/install/chia-blockchain_1.2.1_arm64.deb (ubuntu/debian arm64)
https://download-chia-net.s3-us-west-2.amazonaws.com/install/chia-blockchain-1.2.1-1.x86_64.rpm (centos/redhat)

everything without waranties ;)

**Comment by emlowe** [comment]
There is some lag for all the artifacts to get updated (in particular getting the MacOS build notarized is a slow process)
