### ISSUE TITLE
chia plotnft show doesn't show the updated info

### ISSUE THREAD

**Issue by kreaninw** [Chia-Network/chia-blockchain#7430]
**Describe the bug**

When I run `./chia plotnft show`, it doesn't show the updated pooling information. It always shows the same **points balance** which is contrary to the pool dashboard that I log in using my launcher ID.

I do not have this problem when using the GUI. Therefore this is limited to `./chia plotnft show` command line.

**To Reproduce**

1. Run `./chia plotnft show` command line and see the **points balance** value.
2. Waiting until you found a new proof (in the pool).
3. Run `./chia plotnft show` command line again.
4. The **points balance** value will be the same (not update).

**Expected behavior**

`./chia plotnft show` command line should always shows the updated information.

**Screenshots**

It's a command line issue, no screenshot.

**Desktop**

- OS: Linux
- OS Version/Flavor: Ubuntu 21.04
- CPU: BCM2711 (Raspberry Pi 4 B)

**Additional context**

**Comment by mariano54** [comment]
Can you show screenshot of CLI and GUI?

**Comment by kreaninw** [comment]
> Can you show screenshot of CLI and GUI?

I checked again in Chia 1.2.1. I can't reproduce this issue anymore.
