### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nabiesl** [Chia-Network/chia-blockchain#7438]
I deleted all my previous plots and connected the new plot to the pool and built nft why did not receive chia
There is something wrong with my work
I will send the image of the pool I created
But as before, the time to win shows, for example, 6 years, despite the construction of plots connected to the pool
We were supposed to join the pool no longer have to wait for time and have a steady income
![2](https://user-images.githubusercontent.com/86523027/125404961-126c6980-e36c-11eb-877e-e8e3dfa3050d.png)
![Untitled3](https://user-images.githubusercontent.com/86523027/125405003-1ac4a480-e36c-11eb-9311-5197c52d4f3c.png)

**Comment by nabiesl** [comment]
Join a pool and get consistent XCH farming rewards. The average returns are the same, but it is much less volatile. Assign plots to a plot NFT. You can easily switch pools without having to re-plot.
Isn't that what you said?

**Comment by nabiesl** [comment]
With 30 plots in the pool, it shows a time of 6 years without a pool as in the past

**Comment by mariano54** [comment]
You need to click "join pool". Please follow the user guide: 
https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-User-Guide
