### ISSUE TITLE
make a new plot with 1.1.7 version

### ISSUE THREAD

**Issue by Jimmy01240397** [Chia-Network/chia-blockchain#7440]
I accidentally used an old version to create plots. Are these plots valid?
![image](https://user-images.githubusercontent.com/57281249/125412376-708f6000-e3f1-11eb-8495-ee8457cdc631.png)
![image](https://user-images.githubusercontent.com/57281249/125412411-7ab15e80-e3f1-11eb-9170-fe73b5d2d262.png)
ps:(I used chia plots check with 1.2.0 is pass)

**Comment by emlowe** [comment]
They are valid but not portable (and this is not a bug)
