### ISSUE TITLE
[BUG] cc_wallet can't handle fees correctly

### ISSUE THREAD

**Issue by AndreHe02** [Chia-Network/chia-blockchain#7443]
NOTE: I had to follow https://github.com/Chia-Network/chia-blockchain/issues/6477 to get cc_spend to work in the first place. 

When I call the cc_spend function (part of the rpc api) with a nonzero fee, it returns error "input and output amounts don't match". I'm guessing this is because in cc_utils.py/spend_bundle_for_spendable_ccs, the loop that counts output amount only counts CREATE_COIN outputs but not RESERVE_FEE outputs.

Also, perhaps there should be the option of offering XCH instead of colored coins as fee?

**Comment by emlowe** [comment]
There will be a new standard called Chia Asset Token (CAT) and related support programs. Closing this as it has no relationship to this new work.
