### ISSUE TITLE
[BUG] No Pool, No Farm, No Pool

### ISSUE THREAD

**Issue by nitry** [Chia-Network/chia-blockchain#7448]
**Screenshots**
![image](https://user-images.githubusercontent.com/39399480/125468139-580535d6-5eb1-49d5-8df7-149bad2bb219.png)

![image](https://user-images.githubusercontent.com/39399480/125468074-29c245b1-9a2b-465d-90dd-1475b0a9eef6.png)

![image](https://user-images.githubusercontent.com/39399480/125468204-e14ac9cd-4cd1-4f35-8813-71671b92741c.png)

**Desktop**

- OS: Windows 10
- OS Version/Flavor: 19043.1083
- CPU: AMD Ryzen 7 5800H

**Additional context**
Help me for this error, 2 Week i cannot farming

**Comment by jackdrod** [comment]
my chia same pls help

**Comment by oudi74** [comment]
Same for me since 1.2.1, downgraded 1.2.0 but problem still there.
I never had issues since 3 months before that

**Comment by BOOGgalo** [comment]
+1 pls help
