### ISSUE TITLE
Points change to zero after restarting PC l, while I have not rewarded any Chia

### ISSUE THREAD

**Issue by MHsafari** [Chia-Network/chia-blockchain#7451]
Hi 
Whenever I restart my PC "current points Ballance" and "points found since start" change to zero , whereas I have not rewarded any chia.
I am wondering wether this is normal or this is the pool/chia client bug? Will I be rewarded Chia for the points I have get before restarting? If yes, is there any way to see my overall points that have net been rewarded yet?
I am using space pool.

**Comment by StrawberryOG** [comment]
Space pool doesn't payout until you reach .01 XCH unpaid balance. Just keep farming you'll get payout when you hit threshold.
