### ISSUE TITLE
Pool not accepting 2nd harvester partials (full node)

### ISSUE THREAD

**Issue by ASPANSolutions** [Chia-Network/chia-blockchain#7453]
**Describe the bug**
My plotter node is successfully creating plots and testing them, and farming them. My second farming full node (1.2.1) can see the plots, test the plots successfully, synced etc; however, the pool does not accept any of the partials and therefore although displays points found state them as 0% successful. The nodes are of different IP addresses/address blocks due to being on different sites. Mainnet log debug does not show any warnings.

**Expected behaviour**
Expecting the pool to accept approx 85% of partials, and then the pool to add the results from both nodes together.

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/86829189/125484221-b27220e3-7cd2-4155-8fe2-53174a3a9a98.PNG)

**Desktop**
- OS: Windows Server 2019
- CPU: Xeon E3-1230 3.3Ghz

**Comment by mariano54** [comment]
Have you tried on a different pool? Try switching and see what happens

**Comment by ASPANSolutions** [comment]
Following advice had to rebuild Wallet which took time.  That solved the issues it was trying to address.  I installs 1.2.2 to ensure all updates were in place.  I was going to then follow the advice of moving pool to see if that would work to discover all the plots on the 2nd node can't be seen by the GUI.  So now I've trying to work out how to get it to see the plots in order to get back to test this issue.  Feel like I'm chasing problems.

**Comment by ASPANSolutions** [comment]
Not managing to get the system to see plots.  Writing a new plot to make sure 1.2.2 can see a plot it has made with all the current settings.
