### ISSUE TITLE
1.2.1 - What happened to the NFT UI?

### ISSUE THREAD

**Issue by joelrb** [Chia-Network/chia-blockchain#7455]
**Describe the bug**
I am trying a pool with just 2 plots. This has been running for 3 days now so I got points and a graph.

Installed the new version 1.2.1 but the points are gone and there's no more graph. 

It's been 5 hours since I installed. I restarted the computer as well as Chia. Still no data and graph.

**To Reproduce**

1. Install new version 1.2.1 over 1.2.0 with NFT and pooling.

**Expected behavior**
Show previous data in UI and graph.

**Screenshots**
![Screen Shot 2021-07-14 at 12 00 51 AM](https://user-images.githubusercontent.com/225284/125487458-fa7534c4-857e-4dab-afb8-26d9b08f6b99.png)

**Desktop**

- OS: Mac OS
- OS Version/Flavor: Big Sur
- CPU: Mac-mini

**Additional context**

**Comment by joelrb** [comment]
I keep refreshing the plots and this happened. The points still wrong. There is really a bug.

![Screen Shot 2021-07-14 at 1 30 06 AM](https://user-images.githubusercontent.com/225284/125498703-cdf9a39b-1132-4466-a1cc-d925a0f5e2b9.png)

**Comment by joelrb** [comment]
14 hours later. It seems the points counting has restarted after upgrading Chia. The old points before 1.2.1 are gone.

![Screen Shot 2021-07-14 at 1 51 00 PM](https://user-images.githubusercontent.com/225284/125570344-86cbf6c1-1e9d-4269-8303-e95cce42709a.png)

**Comment by joelrb** [comment]
Everytime Chia is restarted everything goes back to zero including the Points Found Since Start which shouldn't be the case.

**Comment by emlowe** [comment]
It's tracking points found since start of the farmer - restarting the UI restarts the farmer. The points are really tracked by the pool in any event - they are not "gone"
