### ISSUE TITLE
[BUG]upgraded to latest version and all i get on plots, farm and pool is a spinning wheel. i have deleaded and re downloaded several times and get the same thing

### ISSUE THREAD

**Issue by jman3345** [Chia-Network/chia-blockchain#7490]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by madmmmax** [comment]
I got same issue couple times...no matter how many hours I have waited, it drives me to die...
unfortunately I have to delete all Chia related files and reintall to fix it. All files include DB files, which means you have to re-sync after reinstall.
I think there is no other way around it.
If you got a better way to fix it, please let me know, I got a feeling I'll meet it again..

**Comment by itongx** [comment]
not sure it relating or not but remove all chia relate and re-install with admin it work for me

**Comment by malikmarcel** [comment]
Really? I need to resync all chia for 9999 time?

**Comment by malikmarcel** [comment]
Guys! probably solved the problem.

1. Turn off Chia, delete off task's from menager
2. Delete the config and config.bak
2. Turn on Chia
3. Turn off Chia and kill all task's
4. Copy the path with plots or add manually in Chia app!

**Comment by richkravh** [comment]
> Guys! probably solved the problem.
> 
> 1. Turn off Chia, delete off task's from menager
> 2. Delete the config and config.bak
> 3. Turn on Chia
> 4. Turn off Chia and kill all task's
> 5. Copy the path with plots or add manually in Chia app!

Can you do with images?

**Comment by richkravh** [comment]
This will fix the problem of your 'annoying menus are loading', 
1. Close Chia until you see 'Waiting for Node and Server blabla...' - At this time, do not close the lil' window, end it through Task Manager > Chia > End Task.
2. Procceed to your '.chia' - it will be at your C:/Users/YOU/.chia
3. You will find config folder, delete both config and config_bak
4. Re-run Chia, you will b able to see your menus back.

**Comment by malikmarcel** [comment]
> This will fix the problem of your 'annoying menus are loading',
> 
> 1. Close Chia until you see 'Waiting for Node and Server blabla...' - At this time, do not close the lil' window, end it through Task Manager > Chia > End Task.
> 2. Procceed to your '.chia' - it will be at your C:/Users/YOU/.chia
> 3. You will find config folder, delete both config and config_bak
> 4. Re-run Chia, you will b able to see your menus back.

You don't need wait on this window on point 1. It's just goin on closing all task from Chia.
