### ISSUE TITLE
points reset in pool with no payout.  why does this happen?

### ISSUE THREAD

**Issue by chrismikefowler1** [Chia-Network/chia-blockchain#7510]
i'm in space pool. i had 700 points. now i only have 100, with no payout.  anyone else having this issue? does it take a while to recieve the payout?

**Comment by max918** [comment]
point will convert to unpaid amount and reset when block found each round.
copy your launcher id and go to pool website to see your account summary.

**Comment by loppefaaret** [comment]
This is up to the pool, and how they configure their points and payouts
