### ISSUE TITLE
[Error13]

### ISSUE THREAD

**Issue by keybil7091** [Chia-Network/chia-blockchain#7514]
[Error 13] Permission denied. You need to keep using a file/directory that doesn't have permissions in it. There is probably something wrong with the folders in your config file.yaml.

Help Please..

**Comment by hoffmang9** [comment]
Duplicate - https://github.com/Chia-Network/chia-blockchain/issues/7522

This is saying that one of your folders listed in `~/.chia/mainnet/config/config.yaml` is either missing or you don't have permissions to see it - just as the error message says.
