### ISSUE TITLE
[BUG]无法领取奖励，导致无法进行切换池

### ISSUE THREAD

**Issue by baofu8881** [Chia-Network/chia-blockchain#7520]
农业合作社领取：0.00000100001xch   手续费填写0 或者不填写  都无法领取
提示：
{'amount': 1, 'parent_coin_info': '0xf7e70006ca21b44f1d9b49db60e0437*********', 'puzzle_hash': '0x1f2bf93a6abecd5b775581047611bdeda5e99b21b*********'}

**Comment by baofu8881** [comment]
能否提升同步速度，例如高度采用云端，每次同步9-10小时才可以开始工作

**Comment by chiazhang** [comment]
可以用已同步完的局域网机器同步，或者云上自己的节点ip同步咯
