### ISSUE TITLE
[BUG] GUI not detection the plots even i creat a new polt using GUI still it not detecting Plot or any HDD

### ISSUE THREAD

**Issue by AjPanchal02** [Chia-Network/chia-blockchain#7556]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by emlowe** [comment]
Duplicate (probably) of #7262
