### ISSUE TITLE
[BUG] websockets.exceptions.ConnectionClosedError

### ISSUE THREAD

**Issue by bobhellen** [Chia-Network/chia-blockchain#7563]
What is the problem? This error was frequently reported in my log，Because of its existence, the time for me to find the space proof is very delayed, and the last space to find the space proves to be delayed.

<img width="928" alt="WX20210716-194649@2x" src="https://user-images.githubusercontent.com/87216887/125942837-bab9174e-db31-4db2-b43a-8cc53354bfde.png">
<img width="916" alt="WX20210716-195142@2x" src="https://user-images.githubusercontent.com/87216887/125943316-dc26c497-c6d9-443e-8181-eb2bc3612348.png">

**Comment by cryptosven76** [comment]
i found a way to provoke this 100% of the time with running commands in a script --> https://github.com/Chia-Network/chia-blockchain/discussions/7710

maybe that helps get to the bottom of this
