### ISSUE TITLE
[BUG] WARNING Cannot write to closing transport

### ISSUE THREAD

**Issue by arturotrenard** [Chia-Network/chia-blockchain#7566]
**Describe the bug**
hello guys, have any idea why this error happens? 2021-07-16T06:18:09.783 full_node full_node_server        : WARNING  Cannot write to closing transport 67.183.106.77

**To Reproduce**

I have been plotting since the new protocol came out and from yesterday to today I have 3 messages like these

**Expected behavior**

**Screenshots**

**Desktop**

- OS: Linux
- OS  Ubuntu 20.04
- CPU: AMD Ryzen Threadripper 3960X

**Additional context**

This is the version of the client that I am using 1.2.2 Chia blockchain 2021-07-14

**Comment by arturotrenard** [comment]
![Screenshot from 2021-07-16 07-49-48](https://user-images.githubusercontent.com/65082809/125950434-513a9c32-64e9-4a99-a000-59bd6a13ad83.png)

**Comment by emlowe** [comment]
These are expected from time to time, some of your peers that you are connected to have closed their connections abruptly - likely those nodes were restarted, or had some other network issue. As long as your node is fully synced there are no concerns here
