### ISSUE TITLE
[BUG] plots have been created for an NTF pool and they are not showing up as shares

### ISSUE THREAD

**Issue by horriganpt** [Chia-Network/chia-blockchain#7575]
4.949TiB of plots have been created for an NTF pool and they are not showing up as shares.  The following error occurs in the debug logs:

farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 12, Invalid authentication token

AND

farmer chia.farmer.farmer         : ERROR    Error in pooling: (7, 'The aggregate signature is invalid

Reproduce:
This has been exhibited on both ubuntu 20.04 and Windows 2016.

1. Create NTF
2. Create Plots to NFT
3. Refresh Plots
4. Check Pool Website

**Expected behavior**
The points show up on the pooling site.

**Screenshots**
![image](https://user-images.githubusercontent.com/17617028/126017447-ad5d22c8-d94a-4a37-b65c-1a117203c9d5.png)
Point are being gathered with a 76.43%

**Desktop**
This is a Dell Poweredge R720xd with 8TiB of storage in a RAID 10

- OS: ubuntu 20.04
- OS 20.04
- CPU: Intel Xeon E5-2690 @ 2.90Ghz

**Additional context**
The version of Chia is 1.2.2.

**Comment by emlowe** [comment]
Both the mentioned errors are from the pool operator - you should inquire with them
