### ISSUE TITLE
[BUG] Creating Plot NFT and Joining the Pool... Waiting for Transaction to be Confirmed

### ISSUE THREAD

**Issue by vdx660** [Chia-Network/chia-blockchain#7581]
**Describe the bug**
"Creating Plot NFT and Joining the Pool... Waiting for Transaction to be Confirmed" has been running for weeks even when uninstalling and reinstalling Chia

1. Install Chia
2. Goto Pool > Add Plot NFT > Connect to Pool
3. Enter "https://us-east.maxiopool.io" or "https://pool.xchpool.org" in the URL
4. Click Create
5. At this point in time a proper Pool is created
6.  Repeat by Going to Pool > Add Plot NFT > Connect to Pool
7. Enter whatever you entered in (3) in the URL (either "https://us-east.maxiopool.io" or "https://pool.xchpool.org" )
8. Click Create
9. The second pool of the same name will not be created instead you will see a message "Creating Plot NFT and Joining the Pool... Waiting for Transaction to be Confirmed"
10. Uninstall Chia
11. Remove .chia folder
12. Reinstall Chia
13. Wait until Wallet and Full Node is Synched
14. Goto Pool you will still see the same message "Creating Plot NFT and Joining the Pool... Waiting for Transaction to be Confirmed"

**Expected behavior**
A Pool should be created when wallet and full node are synched. I have been waiting for a week already.

**Screenshots**
![image](https://user-images.githubusercontent.com/23503436/126019385-36a3844f-7116-4e3a-8018-67c9ec245ce0.png)

**Desktop**
- OS: Windows 10
- CPU: Intel Core(TM) i5-2400 CPU @ 3.10GHZ

**Additional context**

**Comment by emlowe** [comment]
Why are you creating multiple Plot NFT? There is especially no point to create a Plot NFT to a pool where you already have a Plot NFT.

**Comment by vdx660** [comment]
> Why are you creating multiple Plot NFT? There is especially no point to create a Plot NFT to a pool where you already have a Plot NFT.

It was unintentional. When I first created the Plot NFT it didn't appear so I tried to do it again and the plots only appeared when I restarted the Chia application. There's no way of deleting the duplicates.

**Comment by erol-y** [comment]
Hello,
Could you try these steps?

1. close gui
2. enter "C:\Users\_USERNAME_\AppData\Roaming\Chia Blockchain\Local Storage"
3.  delete folder "leveldb"
4. start gui

**Comment by vdx660** [comment]
This resolve the issue. Thanks

**Comment by tgroff** [comment]
@erol-y **_YES!_** This resolved my issue too! This was easier than deleting my wallet db (_which didn't fix the issue anyhow_). No more phantom transactions waiting to be confirmed, THANK YOU! 

`%userprofile%\AppData\Roaming\Chia Blockchain\Local Storage`
