### ISSUE TITLE
[BUG] Chia-GUI won't start Raspberry Pi, "Depends: node-gyp (>= 3.6.2~) but it is not going to be installed"

### ISSUE THREAD

**Issue by VivaLaRobo** [Chia-Network/chia-blockchain#7599]
**Describe the bug**
Raspberry Pi - 64 bit 

Everything was working fine until I tried to install NVM and update Node to the latest version. Then I tried to install the GUI again for Chia but ran into this error:
`Depends: node-gyp (>= 3.6.2~) but it is not going to be installed`

**Things I have tried**
Uninstall NVM, Node, NPM
Reinstall NVM, Node, NPM
Fully Uninstall NVM and re-try with same error

**To Reproduce**
git clone of Chia repo, run through install scripts, try to run the install-gui script but fails with an error about "Node-Gyp"

**Screenshots**
https://i.imgur.com/Z7WAd8v.png

**Desktop**

Raspberry PI 64 Bit

**Additional context**
This was working until I tried to install NVM and then update Node to the latest version. Then everything started breaking. Removing NVM, Node, and NPM now still does not resolve the issue. Does this have anything to do with the latest update to Chia?

**Comment by hoffmang9** [comment]
This is your local apt configuration. A much easier work around is to use the installer for ARM64 linux.
