### ISSUE TITLE
Chia GUI Bug

### ISSUE THREAD

**Issue by jsantanajr21** [Chia-Network/chia-blockchain#7602]
Just right before I updated to latest version that was recently released, my farming, plots, and pool tabs were not displaying any data.  All you see is the loading icon on the plot and pool tabs, the farm tab displays a chart with only the latest block challenges and its empty, and right above it, the farm overview also has the loading icon. I've already restarted it numerous times, and also reloaded (forced too) from the menu bar in the GUI. I'm guessing a fresh install, which is my next step; just thought I should report it to see if there are others experiencing the same.

**Comment by krandall-01** [comment]
I confirm the bug. Also I have updated to the latest version and the gui is always loading. 
These are the screenshots:

![WhatsApp Image 2021-07-18 at 21 34 33 (3)](https://user-images.githubusercontent.com/62471937/126080135-20bb6639-7418-4c50-ae11-78e09caf7a34.jpeg)
![WhatsApp Image 2021-07-18 at 21 34 33](https://user-images.githubusercontent.com/62471937/126080140-edd02a05-bb22-401b-a007-43807956f39f.jpeg)
![WhatsApp Image 2021-07-18 at 21 34 33 (1)](https://user-images.githubusercontent.com/62471937/126080143-93824629-7478-45db-969c-6146ea45b1c1.jpeg)
![WhatsApp Image 2021-07-18 at 21 34 33 (2)](https://user-images.githubusercontent.com/62471937/126080147-f30d576f-732f-4c0d-90f7-b2bf09dfd798.jpeg)

**Comment by madrigo64** [comment]
Press Ctrl+Shift+I  and maybe then you will see errors

**Comment by krandall-01** [comment]
I read this in console:

DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Krand/AppData/Local/chia-blockchain/app-1.2.2/resources/app.asar/build/renderer/js/main.js.map: Unexpected end of JSON input

**Comment by madrigo64** [comment]
try this command  in PowerShell
 `C:\Users\Krand\AppData\Local\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon\chia.exe start all`
for see all status of services  chia
and this
`C:\Users\Krand\AppData\Local\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon\chia.exe start all -r`
for restart them.
Check log for errors  [https://github.com/Chia-Network/chia-blockchain/wiki/How-to-Check-If-Everything-is-Working-(or-Not)](https://github.com/Chia-Network/chia-blockchain/wiki/How-to-Check-If-Everything-is-Working-(or-Not))
Check if you have free space on drive where located confing folder .chia 
In the last step will be sync from zero it will take 4-5 days.
And I recommend to do backup of config folder .chia where is located DB when all is working fine sometimes

**Comment by krandall-01** [comment]
Thanks for support:
all service are started, 
Now only first tab is in 'loading mode', the other tabs are active as always.

![image](https://user-images.githubusercontent.com/62471937/126124128-627f91d3-b27d-430b-ace2-37c11a7e5816.png)

**Comment by madrigo64** [comment]
> 
> 
> Thanks for support:
> all service are started,
> Now only first tab is in 'loading mode', the other tabs are active as always.
> 
> ![image](https://user-images.githubusercontent.com/62471937/126124128-627f91d3-b27d-430b-ace2-37c11a7e5816.png)
> 
> isn't there a way to download the db file differently? ... to avoid 4-5 downs.

I don't no. 
I'm not sure if you have problem with DB
It can be problem with connection.
first of all check errors in log  maybe there you will se problem
and if you can't find it only then start from zero.

**Comment by madrigo64** [comment]
Create empty file with name pears.bat
insert this code  (ignore all error messages it's normal)
`echo off
cd /d %LOCALAPPDATA%\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon

chia show -a node-apne.chia.net:8444

chia show -a introducer-apne.chia.net:8444

chia show -a introducer-apse.chia.net:8444

chia show -a introducer-or.chia.net:8444

chia show -a introducer-va.chia.net:8444

chia show -a introducer-eu.chia.net:8444

chia show -a chiadb.net:8444

chia show -a pyl.dk:8444

chia show -a node.chia.net:8444

chia show -a 81.83.5.50:8444

chia show -a 118.189.201.184:8444

chia show -a 63.86.188.28:8444

chia show -a 70.67.4.75:8444

chia show -a 159.28.171.166:8444

chia show -a 37.145.52.144:8444

chia show -a 123.57.42.226:8444

chia show -a 76.251.32.219:8444

chia show -a 70.224.19.232:8444

chia show -a 73.252.215.180:8444

chia show -a 205.134.173.77:8444

chia show -a 84.107.167.248:8444

chia show -a 86.57.236.161:8444

chia show -a 211.227.132.15:8444

chia show -a 72.39.161.212:8444

chia show -a 201.131.68.254:8444

chia show -a 90.222.8.93:8444

chia show -a 178.82.152.5:8444

chia show -a 24.24.132.82:8444

chia show -a 80.212.44.58:8444

chia show -a 37.193.78.56:8444

chia show -a 65.24.91.237:8444

**Comment by krandall-01** [comment]
yes i tried this before and it didn't work out. I deleted the db, and everything resumed ... even the list of nodes you proposed works.
Now I will look for some pious soul who can host the db file in order to download it quickly. thanks in the meantime

**Comment by emlowe** [comment]
Closing issue
