### ISSUE TITLE
Chia start farmer : port 55400 already in use on startup without reason

### ISSUE THREAD

**Issue by denisprovost** [Chia-Network/chia-blockchain#7606]
**Describe the bug**
After a new installation on ubuntu 21.04, impossible to launch the farm, port 55400 already in use. I did not create any cron or init on startup, nothing reason that Chia run a process on the port 55400 on startup. I have to kill the process to be able to launch chia farm. This is my second install Ubuntu with my PI4, with version 1.2 everything worked fine. 

**To Reproduce**
1. Installed ubuntu 21.04 and chia-blockchain 1.2.2 on Raspberry pi 4 
2. Acces by SSH
2. cd chia-blockchain
3. . ./activate
4. chia start farmer

**Screenshots**
When i start the system, i check the port 55400, is already in use an a chia process without reason ...
https://ibb.co/HdQGy2R

When i try start 'chia start farmer' command by cli-> port 55400 already in use.
https://ibb.co/Mf15Nm3

**Infos**
- OS: Ubuntu server 21.04
- Hardware: Raspberry Pi4 model B
- Chia blockchain 1.2.2

I thank in advance whoever can help me solve this problem!

**Comment by hoffmang9** [comment]
Try `chia stop -d all` first. There is nothing in the app that would cause it to autostart on its own.

**Comment by denisprovost** [comment]
'chia stop -d all' after reboot send no 'deamon started', but a process 'chia' run on the port 55400.

**Comment by emlowe** [comment]
If you have ever used alternative CHIA_ROOT locations - you may need to set CHIA_ROOT and then run `chia stop -d all`. Do you have directories other than "mainnet" under ~/.chia?

**Comment by denisprovost** [comment]
Yes of course, not chia_root changed and alls files are in nice locations.

If i stop the process on this port and run 'chia start farmer', chia start the sync. 
Some things start chia and lock this port on boot...

**Comment by hoffmang9** [comment]
OS support is better done in the Keybase support channel or on chia forum.
