### ISSUE TITLE
[BUG] Wrong EIP2333 implementation

### ISSUE THREAD

**Issue by majudev** [Chia-Network/chia-blockchain#7608]
**Chia has bad implementation of EIP2333**

**To Reproduce**

How to find out about the issue

1. Go to [EIP2333](https://eips.ethereum.org/EIPS/eip-2333) reference implementation (on the bottom of the page)
2. Derieve master key using your Chia mnemonic (as string) and empty password ("", 0-byte empty string)
3. Compare to your actual master key shown by `chia keys show --show-mnemonic-seed`

**Expected behavior**
Keys should be the same.

**Error in implementation**
I have managed to successfuly locate the mistake. Chia doesn't hash salt in HKDF_mod_r implementation, as it should. EIP2333 reference states that `HKDF_mod_r` (which Chia implements inside `derive_master_SK` I believe) should be:
1. salt = "BLS-SIG-KEYGEN-SALT-"
2. SK = 0
3. while SK == 0:
4.     salt = H(salt)
5.     PRK = HKDF-Extract(salt, IKM || I2OSP(0, 1))
6.     OKM = HKDF-Expand(PRK, key_info || I2OSP(L, 2), L)
7.     SK = OS2IP(OKM) mod r
8. return SK
9. 
However Chia's implementation is missing step 4, which is hashing salt using SHA-256 algorithm. Instead salt stays `"BLS-SIG-KEYGEN-SALT-"` forever.

**Comment by emlowe** [comment]
Please see https://github.com/Chia-Network/bls-signatures/issues/216
"The EIP changed after we shipped the final version of BLS that locks in our plot format. Key encryption will be at a higher level in the application."
