### ISSUE TITLE
Transaction Pending Forever - Same To and From Wallet Address

### ISSUE THREAD

**Issue by rkandel** [Chia-Network/chia-blockchain#7613]
**Describe the bug**
It seems like the wallet does not prevent the user from accidentally sending coins to it's own wallet address, meaning that the From and To address being same.

I ACCIDENTALLY sent few XCH to my own address (Receive Address on the sending wallet) where as I meant to send it to another address. The XCH did not appear to the anticipated address even after few days and I started investigating. It appears that I sent to the same address as sending address and it's on PENDING status even after three days.

I understand that this my my mistake. However, these days we try to make the applications more IDIOT proof to minimise human address. In my view, there should be simple validation to check if the sending and receiving wallet address is same. Going one step further, the wallet should be able to check if the receiving address is valid XCH address or not.

In a typical system, the trasaction with same To and From address should either be rejected or should be send to the same address. It should not be sitting as PENDING forever.

COULD ANYONE HELP ME ON HOW TO RELEASE THIS PANDING TRANSACTION?

**To Reproduce**

1. Send XCH to the same wallet address as Receive Address.

**Expected behavior**
Transaction PENDING forever.

**Screenshots**

![Pending Transaction](https://user-images.githubusercontent.com/6655937/126059144-926c7813-ddea-485d-8f35-de58021ea6dc.png)

**Desktop**
Windows 10, Chia 1.2.0

**Comment by hoffmang9** [comment]
If the transaction is not out on the chain - you don't see it on the various explorers - then worst case you should stop the app and delete your wallet database (don't delete the blockchain db) and restart.
