### ISSUE TITLE
[ENHANCEMENT] Prevent 2nd instance of the app

### ISSUE THREAD

**Issue by krispipeleers** [Chia-Network/chia-blockchain#762]
Prevent the Chia app to start a new instance (after clicking the icon) when it is already running.

**Comment by hoffmang9** [comment]
Added in Beta 26 thanks to @dkackman ! https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta26

**Comment by krispipeleers** [comment]
Tested and looks good! Thanks!
