### ISSUE TITLE
[ENHANCEMENT] Request to include full plot file names being farmed in GUI

### ISSUE THREAD

**Issue by toastygunn** [Chia-Network/chia-blockchain#763]
I just checked in beta23 and the suggestion I made on Keybase doesn't seem to be on the Trello project list so I thought it might be useful to document this suggestion here:

Right now, beta23 shows the unique ID or seed for the plotname in the GUI instead of the actual path/filename. This makes it a lot harder to figure out which plots are being farmed when you have multiple drives.

I think the GUI from B17 shared this information. FWIW, I would find the full file pathname more useful than the other columns.

**Comment by hoffmang9** [comment]
Added back in Beta 26 - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta26
