### ISSUE TITLE
Reward error[BUG]

### ISSUE THREAD

**Issue by yangxyi740920** [Chia-Network/chia-blockchain#7631]
Confirm to block level 64287
1.75 no incentives
Receiving address: hdd1f0lyn6y5rpkfk6qqz546dgmv9v3rylp34pe4h0j0cva7ggt9lf8sgnh996

**Comment by keliew** [comment]
Ask https://github.com/HDDcoin-Network/hddcoin-blockchain
You're in the wrong blockchain.
