### ISSUE TITLE
[BUG] plotting stuck

### ISSUE THREAD

**Issue by pablosaiful** [Chia-Network/chia-blockchain#7649]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by hoffmang9** [comment]
This is usually a hardware problem. Either way, you will need to give us a lot more details to be able to help you. The better way to get assistance is in the public Keybase #support channel.
