### ISSUE TITLE
[BUG]The wallet is not synchronized, and FULL NODE are synchronized normally

### ISSUE THREAD

**Issue by tracy32792** [Chia-Network/chia-blockchain#7663]
2021-07-20T14:22:01.213 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 8449}. Traceback (most recent call last):
sqlite3.OperationalError: too many SQL variables

**Comment by vdx660** [comment]
1. Try removing the wallet
![image](https://user-images.githubusercontent.com/23503436/126574189-6eb0a262-9c70-4ecd-83f3-6378d2b269c4.png)

2. If it doesn't work goto to C:\Users\\[user]\\.chia\mainnet\wallet\db 
3. Backup or Delete all files in that folder to restart the wallet sync

**Comment by tangdasan** [comment]
> 1. 尝试取出钱包
>    ![图像](https://user-images.githubusercontent.com/23503436/126574189-6eb0a262-9c70-4ecd-83f3-6378d2b269c4.png)
> 2. 如果它不起作用转到 C:\Users\[user]\.chia\mainnet\wallet\db
> 3. 备份或删除该文件夹中的所有文件以重新启动钱包同步

When I have two keys, I can't do this, which will cause my other key to lose synchronization
