### ISSUE TITLE
[BUG] Caught plotting network error: resize_file failed

### ISSUE THREAD

**Issue by MasterJames** [Chia-Network/chia-blockchain#7664]
**Describe the bug**
Can't plot. Error at end.
**To Reproduce**
Run Win10 Chia GUI and plot (for pool) on remote Network Drive.
At 97% it fails.
Open Log and see error.

**Expected behavior**
To work and complete the plotting task, and not to crash after Compressing tables 5 & 6 at 97% complete.

**Desktop**
- OS: Win10
- CPU: Not new

**Additional context**
Finally.
Caught plotting error: resize_file: An unexpected network error occurred: "P:\Temp\Plotting\plot-k33.blahblahblah.plot.table5.tmp"
chia.py line 83 in module
...
core.py, lines, 829, 782, 1259, 1259, 1066, 610
decorators.py line 21 in new_func
plots.py line 135 in create_cmd
create_plots.py line 168 in create_plots
RuntimeError: resize_file: An unexpected network error occurred.

**Comment by emlowe** [comment]
Plotting over a network drive is not recommended. Network errors are common and result in starting over

**Comment by MasterJames** [comment]
Well that sounds like a bug to me. It errors and crashes and no recovery.

**Comment by MasterJames** [comment]
It also should be noted that it fails with k33 but not k32 regardless.
