### ISSUE TITLE
[suggestion] Don't bother submitting partials way above time limit

### ISSUE THREAD

**Issue by babipanghang** [Chia-Network/chia-blockchain#7666]
If i understood correctly, a pool may ban a node if it submits partials too late for a number of times. There are of course numerous reasons why a node may be too late submitting results, but wouldn't it be better if a node simply did report no partials found in time instead of waiting for a slow harvester and submitting a partial too late?

**Comment by reb0rn21** [comment]
I agree there should be option in ini so we can set time frame limit .......
I also noticed that if I restart harvester with many slow plots i send few very slow shares

**Comment by mariano54** [comment]
Good point, this can be added as a feature in farmer.py.

**Comment by AndyRPH** [comment]
Then again, if we didn't submit these late/stale partials, we would lose out on information that we had a problem that could keep us from claiming a vaild full proof in time.  Unless there's some way the system can periodically run partial proofs to check the response time once a day or such?

**Comment by babipanghang** [comment]
@AndyRPH I assume a log entry would be made in the sense of "timeout of ## seconds exceeded on harvester <harvestername>, submitting no partials found to pool."
