### ISSUE TITLE
[suggestion]Option for Harvester to keep plots info/cashed at local disk after restart

### ISSUE THREAD

**Issue by reb0rn21** [Chia-Network/chia-blockchain#7669]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/7667

<div type='discussions-op-text'>

<sup>Originally posted by **reb0rn21** July 20, 2021</sup>
If you have large number of plots per harvester if you restart/update, it need 1-2h+ to rescan all plots from star!? (sure slow network etc etc..)

I plan to have 5-10x more plots that would mean initial and each harvester restart/update would take me a big part of day to scan all plots
1. option to not rescan on start (if possible)
2. keep scanned info offline on HDD so restart just load from it and check for new plots</div>

**Comment by superman00111** [comment]
me too，I have an 80p harvester，It  is not  finish took a week.
