### ISSUE TITLE
[BUG] Can't leave for self-farming, or join another pool

### ISSUE THREAD

**Issue by bitflying** [Chia-Network/chia-blockchain#7685]
Hi, friends,

From very beginning, I join the poolchia with command "chia plotnft create -u https://pool.poolchia.com -s pool",  use the pool contract address to plot some plots.

Now, I want to try self-farming or joining another pool, but both of them do not work!

1. Leave for self-farming
```
$ chia plotnft leave -i 1
Will start self-farming with Plot NFT on wallet id 1 fingerprint 331*****1.
Confirm [n]/y: y
Error performing operation on Plot NFT -f 331*****1 wallet id: 1: {'error': "'Wallet' object has no attribute 'self_pool'", 'success': False}
```

2. Join another pool
```
$ chia plotnft join -i 1 -u https://eu1.pool.space

{'authentication_token_timeout': 5,
 'description': 'Welcome to Space Pool. By creating this Plot NFT, you agree '
                'to the following terms https://pool.space/terms',
 'fee': 0,
 'logo_url': 'https://pool.space/logo-250.png',
 'minimum_difficulty': 1,
 'name': 'Space Pool',
 'protocol_version': 1,
 'relative_lock_height': 64,
 'target_puzzle_hash': '0x2f2c9ba1b2315d413a92b5f034fa03282ccba1767fd9ae7b14d942b969ed5d57'}

Will join pool: https://eu1.pool.space with Plot NFT 331*****1.
Confirm [n]/y: Aborting.

```

So, did I do some something wrong? and what is correct way?

Thanks in advance!

- OS: Linux
- OS Version/Flavor: Ubuntu Server 20.04
- CPU: AMD 5600X
- Chia: version 1.2.2 git from source code

**Comment by mariano54** [comment]
You are using the wrong wallet ID. 
do `chia plot nft show` to sell wallet IDs.
