### ISSUE TITLE
农业合作社不能变更[BUG]

### ISSUE THREAD

**Issue by yangshu8919** [Chia-Network/chia-blockchain#7719]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**
农业合作社不能变更

**Comment by chiazhang** [comment]
变更也需要一点xch，另外需要等几十分钟生效咯

**Comment by hoffmang9** [comment]
如果 chiazhang 没有回答你的问题，请随时重新打开这个。
