### ISSUE TITLE
Mempool corruption causes node bans/disconnects - was Cannot farm

### ISSUE THREAD

**Issue by ewan1983** [Chia-Network/chia-blockchain#7720]
One the appearance everything on GUI seems normal, but pool's estimated space keep dropping, last partial submitted was long time ago and then I check log around the time of last submitted partial and see ERROR:

2021-07-21T19:42:23.897 full_node full_node_server        : ERROR    Exception: list index out of range, {'host': '198.72.183.54', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 229, in respond_transaction
  File "chia\full_node\full_node.py", line 1649, in respond_transaction
  File "chia\full_node\mempool_manager.py", line 415, in add_spendbundle
  File "chia\full_node\mempool_manager.py", line 483, in add_to_potential_tx_set
IndexError: list index out of range

2021-07-21T19:42:23.899 full_node full_node_server        : ERROR    Exception: list index out of range <class 'IndexError'>, closing connection {'host': '198.72.183.54', 'port': 8444}. Traceback (most recent call last):
  File "chia\server\server.py", line 533, in api_call
  File "asyncio\tasks.py", line 481, in wait_for
  File "chia\server\server.py", line 530, in wrapped_coroutine
  File "chia\server\server.py", line 523, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 229, in respond_transaction
  File "chia\full_node\full_node.py", line 1649, in respond_transaction
  File "chia\full_node\mempool_manager.py", line 415, in add_spendbundle
  File "chia\full_node\mempool_manager.py", line 483, in add_to_potential_tx_set
IndexError: list index out of range

**Comment by ParadiseFace** [comment]
Hi, it’s the same for me.
Did you fix the problem?
![111](https://user-images.githubusercontent.com/87923685/126894912-f7f2df81-e499-4044-b02e-ab9ffd7cbc42.png)
![222](https://user-images.githubusercontent.com/87923685/126894914-958bea00-a354-462c-959e-66beab9f83a4.png)

**Comment by ParadiseFace** [comment]
> По внешнему виду все в графическом интерфейсе кажется нормальным, но предполагаемое пространство пула продолжает уменьшаться, последний частичный отправленный был давно, а затем я проверяю журнал во время последнего отправленного частичного и вижу ОШИБКА:
> 
> 2021-07-21T19: 42: 23.897 full_node full_node_server: ERROR Исключение: индекс списка вне допустимого диапазона, {'host': '198.72.183.54', 'port': 8444}. Traceback (последний вызов последним):
> файл "chia \ server \ server.py", строка 523, в wrapped_coroutine
> Файл "chia \ full_node \ full_node_api.py", строка 229, в
> файле response_transaction "chia \ full_node \ full_node.py" , строка 1649, в
> файле response_transaction "chia \ full_node \ mempool_manager.py", строка 415, в
> файле add_spendbundle "chia \ full_node \ mempool_manager.py", строка 483, в add_to_potential_tx_set
> IndexError: индекс списка вне допустимого диапазона
> 
> 2021-07-21T19: 42: 23.899 full_node full_node_server: ERROR Исключение: список индекса вне диапазона <class 'IndexError'>, закрытие соединения {'host': '198.72.183.54', 'port': 8444}. Traceback (последний вызов последним):
> файл "chia \ server \ server.py", строка 533, в api_call
> Файл "asyncio \ tasks.py", строка 481, в wait_for
> Файл "chia \ server \ server.py", строка 530, в
> файле wrapped_coroutine «chia \ server \ server.py», строка 523, в
> файле wrapped_coroutine «chia \ full_node \ full_node_api.py», строка 229, в
> файле response_transaction «chia \ full_node \ full_node.py», строка 1649, в
> файле response_transaction "chia \ full_node \ mempool_manager.py", строка 415,
> 
> IndexError: список индекса вне допустимого диапазона

Hi, it’s the same for me.
Did you fix the problem?
![111](https://user-images.githubusercontent.com/87923685/126894952-dd746606-d1f9-481c-af0c-9b33c237e577.png)
![222](https://user-images.githubusercontent.com/87923685/126894954-2305b4f5-3cce-40e8-aa61-04106679c20d.png)

**Comment by skweee** [comment]
I traced back through the code and it looks like this issue may be caused by a mempool corruption, which unfortunately isn't self-healing (`self.potential_cache_cost` is never reset when the exception occurs). A full-node restart should fix the issue, at least until mempool gets corrupted again (still haven't found the root cause).

**Comment by skweee** [comment]
https://github.com/Chia-Network/chia-blockchain/blob/b593f55dcd35ef6ca48a4db0c3f57a46947da767/chia/full_node/mempool_manager.py#L479-L485
This is the problematic piece of code. It looks like `self.potential_cache_cost` remains greater than `self.potential_cache_max_total_cost`, even though `list(self.potential_txs.keys())`is empty.

**Comment by skweee** [comment]
And some more info on the effect of this issue: whenever the exception occurs, the connection to a peer node is closed and the node gets banned for a while. I've seen this reduce the number of connected nodes from about 60 to 5, which will cause sync issues in the long run.

Quick fix seems to be to restart the node, but whatever was the root cause may come up again any time. So mempool should be a little more resistant.

**Comment by arvidn** [comment]
I think this would fix it: https://github.com/Chia-Network/chia-blockchain/pull/8054

**Comment by emlowe** [comment]
Fixed in 1.2.4
