### ISSUE TITLE
[BUG]The farm has been rewarded, but the wallet has not arrived.

### ISSUE THREAD

**Issue by liya558** [Chia-Network/chia-blockchain#7722]
**Describe the bug**
1.The farm has been rewarded, but the wallet has not arrived.
2.The farme is in the Farming state, and the Wallet is in the Synced state.
3.KEY is the same as the wallet Fingerprint, but the reward no have the wallet.

**Desktop**
Rock PI 4A
-OS:Debian GNU/Linux 10 
-CPU: Rockchips RK3399

chia version:1.2.2.dev0

![image](https://user-images.githubusercontent.com/41668985/126583149-06a06974-6358-4b51-a8c5-233f0879aef6.png)

![image](https://user-images.githubusercontent.com/41668985/126583193-e9669cbd-67e2-45e8-9f12-099ab425eb78.png)

![image](https://user-images.githubusercontent.com/41668985/126583234-cddea46e-94ca-496d-bf4d-ccbf9218dc99.png)

**Comment by liya558** [comment]
![image](https://user-images.githubusercontent.com/41668985/126583480-4dd85084-e573-468d-a9f5-3d3d022951c9.png)

**Comment by keliew** [comment]
because it went to HPool..? You used/use/using HPool?

**Comment by liya558** [comment]
> because it went to HPool..? You used/use/using HPool?

I do not use hpool

**Comment by keliew** [comment]
> > because it went to HPool..? You used/use/using HPool?
> 
> I do not use hpool

That's strange, because at that block height, the coins went to HPool...

**Comment by liya558** [comment]
> > > because it went to HPool..? You used/use/using HPool?
> > 
> > 
> > I do not use hpool
> 
> That's strange, because at that block height, the coins went to HPool...
> https://xchscan.com/blocks/450734

okay, thank you.
Why is my trading time July 21? It may be a bug.

**Comment by keliew** [comment]
> Why is my trading time July 21? It may be a bug.

Fantasising is also a type of bug.

**Comment by liya558** [comment]
close
