### ISSUE TITLE
[BUG] CONTRIBUTING.md links to a private GDrive doc

### ISSUE THREAD

**Issue by dudeofawesome** [Chia-Network/chia-blockchain#7723]
**Describe the bug**

CONTRIBUTING.md links to a private GDrive doc, specifically the [git workflow diagram](https://drive.google.com/file/d/1r7AXTrj7gtD0Xy-9BtTZR6yv7WXMPgeM/view?usp=sharing)

**Expected behavior**

I suspect this document is supposed to be public?

**Comment by sargonas** [comment]
Yeah this was an oopsie on our part. if it isn't fixed already as of now, it will be soon!
