### ISSUE TITLE
CLI "chia plotnft inspect"  return "state=3",  Does this mean mining?

### ISSUE THREAD

**Issue by Luuuxury** [Chia-Network/chia-blockchain#7727]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/7726

<div type='discussions-op-text'>

<sup>Originally posted by **Luuuxury** July 22, 2021</sup>
`(venv) root@lux:~/chia-blockchain# chia plotnft inspect -i 3
{'pool_wallet_info': PoolWalletInfo(current=PoolState(version=1, state=3, target_puzzle_hash=<bytes32: 2f2c9ba1b2315d413a92b5f034fa03282ccba1767fd9ae7b14d942b...... bala bala ..........`

---
### Q:

**The thing that confuses me is how do I know I'm already mining in a pool just use CLI? 
Does a status of 3 mean there is no problem? I mean I'm mining now?</div>**

Thanks so much for your help.

**Comment by emlowe** [comment]
Answered in discussion
