### ISSUE TITLE
The chia app is stuck on connecting to wallet.[BUG]

### ISSUE THREAD

**Issue by Adeel0610** [Chia-Network/chia-blockchain#7732]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by keliew** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-is-my-wallet-not-synced-why-can-i-not-connect-to-wallet-from-the-gui

**Comment by Adeel0610** [comment]
the wallet is not showing my paid chia balance and my pool has been deleted. what to do now?

**Comment by Rasandr** [comment]
I have just installed Chia Blockchain 1.2.2 ver. and launched it. For more than 5 hours it is stuck on the menu "Connecting to wallet".
I have Windows 10 and Python 3.9 installed. I have tried to delete files from db folder. No results. What is the problem?

**Comment by goyometeojorito** [comment]
> I have just installed Chia Blockchain 1.2.2 ver. and launched it. For more than 5 hours it is stuck on the menu "Connecting to wallet".
> I have Windows 10 and Python 3.9 installed. I have tried to delete files from db folder. No results. What is the problem?

I have the same problem: "Connecting to wallet" all the time, 3 days and dont change 

I run in "Windows Server 2008 R2 Enterprise 64 bits"

![connecting](https://user-images.githubusercontent.com/13981294/127442310-a059a7c8-da76-4a6e-9788-9203688b0946.png)

**Comment by brano1990** [comment]
hi after restarting the pc i have the same problem 

```
child process success
(node:2511) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Chia directory /home/pc/.chia/mainnet
/home/pc/.chia/mainnet already exists, no migration action taken
No cert
Have cert
```
