### ISSUE TITLE
[BUG] Cannot see any plots! v1.2.3

### ISSUE THREAD

**Issue by hijak** [Chia-Network/chia-blockchain#7749]
**Describe the bug**
All plot directories are added but chia does not see any plots

```
(venv) ubuntu@nuc01:~/chia-blockchain$ chia farm summary | grep ^Plot
Plot count for all harvesters: 0
```

**To Reproduce**

1. Go to plots
2. Click on refresh dirs nothing happens

**Expected behavior**
i have over 200 plots which were fine before i upgraded

**Desktop**

- OS: ubuntu
- OS Version/Flavor: 20.04
- CPU: intel i7

**Additional context**
debug log is filled with

```
2021-07-23T11:58:08.575 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
```
i am not using a remote harvester tho ?

**Comment by emlowe** [comment]
Please try 1.2.3 as various fixes were made in this area
