### ISSUE TITLE
[BUG] GUI cannot auto add plots

### ISSUE THREAD

**Issue by shojiang** [Chia-Network/chia-blockchain#7763]
**Describe the bug**

I've made 2 nft plots today through CLI, but when i'm checking the status in GUI, those two plots are neither in Plots nor Pool option until I restarted the GUI.

**To Reproduce**

- OS: Windows
- OS Version/Flavor: Windows 10

**Additional context**
GUI version:1.2.2

**Comment by maxcom99** [comment]
Going into plots and selecting refresh plots is mandatory to farm/harvest the new plots.

**Comment by emlowe** [comment]
Version 1.2.3 fixes this issue

**Comment by shojiang** [comment]
thanks a lot
