### ISSUE TITLE
[BUG]Beta 23 still got stuck multiple times in ful node load, since yesterday, even with restart 

### ISSUE THREAD

**Issue by YNation1** [Chia-Network/chia-blockchain#777]
- OS: Windows 10
- Chip: Intel Core i5-6200U CPU 2.4 GHz
![Chia Bug](https://user-images.githubusercontent.com/78245186/106346385-7eaf5100-6295-11eb-9ff7-4f0327958808.jpg)
![Chia Bug](https://user-images.githubusercontent.com/78245186/106346388-8a027c80-6295-11eb-922e-2424b29fac9c.jpg)

**Comment by mariano54** [comment]
Can you provide the log file?

**Comment by hoffmang9** [comment]
Should be fixed in https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta26
