### ISSUE TITLE
[BUG] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by n4ndo** [Chia-Network/chia-blockchain#7776]
**Describe the bug**

After some blackout, my farmer wont start.

```PS C:\Users\inghe\AppData\Local\chia-blockchain\app-1.2.2\resources\app.asar.unpacked\daemon> Traceback (most recent call last):```

 ``` File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 68, in <module>```
  ```File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 63, in main```
  ```File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 38, in service_kwargs_for_farmer```
  ```File "chia\farmer\farmer.py", line 125, in __init__```
  ```File "chia\util\bech32m.py", line 114, in decode_puzzle_hash```
  ```File "chia\util\bech32m.py", line 70, in bech32_decode```
```TypeError: 'NoneType' object is not iterable```

**To Reproduce**
./chia.exe start farmer

**Expected behavior**

Starting daemon
chia_harvester: started OK
chia_farmer: started OK
chia_full_node: started OK
chia_wallet: started OK

**Screenshots**

![image](https://user-images.githubusercontent.com/820868/126889617-8184d37f-2b2c-40fb-883c-961efc3823ac.png)

If i try to start from the GUI, the node and wallet start correctly, but the farmer wont start:

![image](https://user-images.githubusercontent.com/820868/126889815-fc4051fe-1d77-433c-8e53-01735eed1648.png)
![image](https://user-images.githubusercontent.com/820868/126889802-dee77ac5-6888-4f66-9b3d-4b8a7f6c1b24.png)
![image](https://user-images.githubusercontent.com/820868/126889838-ddd9bcf3-c311-4649-9911-76514056110a.png)

**Desktop**

- OS:  Windows
- OS Version/Flavor: 10
- CPU:  i9 9900k

**Additional context**

I try to restart... force reload... nothing can start the farmer... ¿Any Help?

**Comment by Nauyks** [comment]
try delete .\.chia\mainnet\config\config.yaml and restart
