### ISSUE TITLE
[BUG]PlotNFT in config.yaml but missing from GUI and CLI

### ISSUE THREAD

**Issue by Comput3rSaysNo** [Chia-Network/chia-blockchain#7781]
We have a user lost his PlotNFT after 2,500 plots were created with it... From the config.yaml file he shared with me, I can clearly see the missing plotnft in the pool_list, he even farmed it with us for a short period which our database record matches his entry. But this plotnft is not coming up in the GUI or the cli command "chia plotnft show". After a clean install with full node resync, this plotnft entry disappeared completely from the newly generated config.yaml file.

**Steps to reproduce the behavior:**

1. User created a plotnft A for https://eu.maxiopool.io
2. Created 2,500 plots for plotnft A
3. Farmed for a little while (we have record in our database)
4. Changed the plotnft A to https://eu1.space.pool
5. Switched plotnft A back to https://eu.maxiopool.io
6. User realized the pool contract address has changed! so instead of plotnft A he now has plotnft B instead (A has gone missing)
7. User then created plotnft C for https://eu.maxiopool.io in the attempt to restore A
8. Now neither plotnft B and C matches the 2,500 plots the user created

**Expected behavior**
The plotnft A should show up in the GUI but it is not there. A clean install with full node & wallet resync should restore the plotnft A but thats not the case.

- OS: Windows 10
- Client verion: 1.2.0 later upgraded to 1.2.2

**Additional context**
Triple checked with the user that he has only ever used one set of 24 words secret on the farmer PC

Things we have tried
1. Upgraded to 1.2.2
2. Deleted wallet db and forced it to resync
3. Deleted the entire ".chia" directory, then clean install of 1.2.2
4. Also tried creating a new plotnft
5. Tried changing the remaining two plotnft B & C to self-pooling then back to pooling with maxiopool

**Comment by chrisfree1381** [comment]
i have been trying to make a plot for over a week. usually at the half =way mark is said something about failing trying in 5 min. never restarted. today this...
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 83, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 79, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 55, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE
[17240] Failed to execute script chia

**Comment by Comput3rSaysNo** [comment]
User got back to me today that he actually had a another private key on the same pc which the plotnft A belongs to.
