### ISSUE TITLE
[BUG] Pool list won't showup after reinstall

### ISSUE THREAD

**Issue by Trypt88** [Chia-Network/chia-blockchain#7787]
So for some reason I have to re-installl Chia client, and so I was running cli for a day or two, but then I found out I wasn't pooling anymore.... And chia poolnft show didn't work at all... so I load up to GUI again and trying to check in the Pool tab, and there was nothing there... My pool contract isn't there, and there's nothing I could've done other then click the only button in the Pool tab... resulting another pool contract at the same pool, this is so stupid... How can I get rid of the new one? There's no delete button either.

**Comment by dragohqbw** [comment]
Tengo la misma problema,no reconoce mis plots

**Comment by keliew** [comment]
NFT can't be deleted. It's on the blockchain.

You'd need to be fully synced to see it, normally.
