### ISSUE TITLE
account does not recognize nft plots[BUG]

### ISSUE THREAD

**Issue by mjrima** [Chia-Network/chia-blockchain#7793]
my account just stoped recognizing my nft plots

![image](https://user-images.githubusercontent.com/87980507/126985840-6dfc4db4-3028-4547-9fae-0bc504af3141.png)

i had to reinstall the chia, and when i did the import words , i got this ploblem with the nft plots
 and i am using windows

**Comment by keliew** [comment]
synced?

**Comment by mjrima** [comment]
yes this synchronized but does not recognize the nft plots

**Comment by mjrima** [comment]
was everything ok before i reinstall the chia app,

**Comment by keliew** [comment]
wallet is synced too?

**Comment by mjrima** [comment]
yes it is
