### ISSUE TITLE
HELP !!! [BUG]

### ISSUE THREAD

**Issue by neuro1978** [Chia-Network/chia-blockchain#7814]
Dopo aggiornamento 1.2.3 apre e sincronizza ma non funzionano più le pagine plot, pool e farming .
Provato ad aggiornare , chiudere , riaprire , riavviare e anche creare nuovo wallet , sempre lo stesso problema .

![Cattura](https://user-images.githubusercontent.com/82379754/127137031-a83569d6-aae9-4dc9-93ff-6f7002c6dc34.PNG)
![Cattura1](https://user-images.githubusercontent.com/82379754/127137042-fcf1a6d9-83b6-4194-9bf0-ceff03ebfc80.PNG)
![Cattura2](https://user-images.githubusercontent.com/82379754/127137056-fbde7332-45ae-469c-84bb-7d9505894a60.PNG)

**Comment by Anton-Komi** [comment]
Добрый день! Подскажите пожалуйста, почему не отображаются участки при засевании на прямую или даже через мэдмакс. 
Пул Space pool и Hpool PP

**Comment by tfrs15** [comment]
I have the same problem!

**Comment by keliew** [comment]
Only run Chia, and see if it has the same results.

Make sure everything else is completely closed.

Otherwise, check `debug.log` on what the actual situation is.

**Comment by Anton-Komi** [comment]
Да, все тоже самое, при обновлении участков нет

**Comment by keliew** [comment]
What does `debug.log` say?

**Comment by Anton-Komi** [comment]
а как его запустить debug.log ?

**Comment by neuro1978** [comment]
I deleted and reinstalled the program, first saving the db folder and the synchronizations which I later repositioned in the mainet folder.  Now everything works.  thank youInviato dal mio Galaxy
-------- Messaggio originale --------Da: Anton-Komi ***@***.***> Data: 28/07/21  12:58  (GMT+01:00) A: Chia-Network/chia-blockchain ***@***.***> Cc: neuro1978 ***@***.***>, Author ***@***.***> Oggetto: Re: [Chia-Network/chia-blockchain] HELP !!! [BUG] (#7814) 

а как его запустить debug.log ?

**Comment by Anton-Komi** [comment]
подскажите, как это поэтапно сделать?

**Comment by keliew** [comment]
@Anton-Komi this is for the `debug.log` https://github.com/Chia-Network/chia-blockchain/wiki/Windows-Tips-and-Tricks#2-take-a-good-look-at-log-files

For what @neuro1978 has done, the `db` folder  is more or less at the same path...

The fix may also be as simple as deleting `config.yaml`, run `chia init` then start chia again...
