### ISSUE TITLE
[BUG] Harvester exited abnormally

### ISSUE THREAD

**Issue by laonadev** [Chia-Network/chia-blockchain#7845]
**Describe the bug**

Chia 1.2.2 (git version: e24baa620d1f5ee13373baf065c024bd05a41b90)

log from `.chia/mainnet/log/debug.log`:
```
2021-07-28T19:18:57.198 harvester chia.harvester.harvester: INFO     3 plots were eligible for farming 9f8b144fd5... Found 0 proofs. Time: 0.38578 s. Total 1191 plots
2021-07-28T19:18:57.202 harvester harvester_server        : DEBUG    -> farming_info to peer ***.***.888.888 3afd5404cd867153f733e1c20cc9a10965c428efcef7aedeba0ac791dd43a507
2021-07-28T19:18:57.290 daemon chia.daemon.server         : INFO     Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rock/chia-blockchain/chia/daemon/server.py", line 172, in safe_handle
    async for message in websocket:
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/rock/chia-blockchain/venv/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
**Expected behavior**
keep running all the time.

**Desktop**
- Uname: Linux rockpi4c95 4.4.154-111-rockchip-g39b306a41b2d #1 SMP Wed Jul 8 15:03:52 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
- CPU: Rock Pi 4c

**Comment by SomePlayer** [comment]
I started having crashes with 1.2.1 after 1.2.3 came out, updating fixed it

**Comment by mariano54** [comment]
Yes please try 1.2.3 as there were various fixes.

**Comment by zlatovlas** [comment]
See my notes & temporary solution at #7458 .

Despite all advice, 1.2.3 did not seem to fix it for me.

**Comment by greg-fischer** [comment]
My error too. Websocket exception. Closing websocket with chia_harvester code = 1006 (connection closed abnormally [internal]), no reason Traceback (most recent call last):
(I don't see a traceback)

I posted on another (closed) issue about segfaults. I thought maybe it was a bad plot, which was the advice on that thread. Found 1, removed, still happens.  I just matched up the segfaults time and the debug log shows this error.  Everything's been running fine until yesterday at some point, not I keep having segfaults and farming stops and drops out of the pool. all plots are NFT on this farmer.

My system is Debian 10, CLI , Chia 1.2.3. Using Space pool.

Also note, I had chia 1.2.2 originally, things were fine.  Only this afternoon I upgraded to 1.2.3, and still have the issue.  I'm currently waiting for plot check on all plots just to be sure that's ok.

**Comment by greg-fischer** [comment]
Reporting back after a long wait to check all plots...   looks like my problem has been resolved after finding some bad plots and removing them. I was having crashes every 10min to 1hr, haven't had any more in 5 hours.

That's great, but it would be nice if a bad plot could be error trapped and logged instead of crashing the harvester.

**Comment by emlowe** [comment]
If anyone can save their bad plots, I can give you a place to upload them so we can improve the error handling. Agreed, we don't want to crash here.

**Comment by berlef80** [comment]
> Reporting back after a long wait to check all plots... looks like my problem has been resolved after finding some bad plots and removing them. I was having crashes every 10min to 1hr, haven't had any more in 5 hours.
> 
> That's great, but it would be nice if a bad plot could be error trapped and logged instead of crashing the harvester.

Can you share how you are determining bad plots.  I run check plots and all my plots come back without warning.  When I keep plot checks running they are "healthy" above .7 but I have not let the full plot checks run because it takes for ever on 3000 plots.  Before I run it completely I just want to make sure that is the correct place to find "bad" plots and what I should be looking for specifically.  Thanks!!

**Comment by berlef80** [comment]
Also I keep getting this error
"farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version"
before the plot filter freezes.  I am on 1.2.3 so there is no updated version.  The other strange thing is that the start_harvester will not shut down - not even forced.  I have to turn off the whole computer to get it to shut down after this error.  Any help would be appreciated.

**Comment by greg-fischer** [comment]
> > Reporting back after a long wait to check all plots... looks like my problem has been resolved after finding some bad plots and removing them. I was having crashes every 10min to 1hr, haven't had any more in 5 hours.
> > That's great, but it would be nice if a bad plot could be error trapped and logged instead of crashing the harvester.
> 
> Can you share how you are determining bad plots. I run check plots and all my plots come back without warning. When I keep plot checks running they are "healthy" above .7 but I have not let the full plot checks run because it takes for ever on 3000 plots. Before I run it completely I just want to make sure that is the correct place to find "bad" plots and what I should be looking for specifically. Thanks!!

On linux I think I ran this:
chia plots check &> ~/plotcheck.log

And I started that in a "screen" session.  So basically I can start it, then come back a day later and check that log.  I was the same way, way too long to check plots. I have 1200, and that took about 8-10 hours.  In the end, I had 25 on one disk that failed.  (and I know why, user error on my part)

It does cause a few partials to fail while checking plots, fyi.  But it wasn't too bad.  But you'll be waiting about 2 days! Sorry. ;)

**Comment by berlef80** [comment]
> > > Reporting back after a long wait to check all plots... looks like my problem has been resolved after finding some bad plots and removing them. I was having crashes every 10min to 1hr, haven't had any more in 5 hours.
> > > That's great, but it would be nice if a bad plot could be error trapped and logged instead of crashing the harvester.
> > 
> > 
> > Can you share how you are determining bad plots. I run check plots and all my plots come back without warning. When I keep plot checks running they are "healthy" above .7 but I have not let the full plot checks run because it takes for ever on 3000 plots. Before I run it completely I just want to make sure that is the correct place to find "bad" plots and what I should be looking for specifically. Thanks!!
> 
> On linux I think I ran this:
> chia plots check &> ~/plotcheck.log
> 
> And I started that in a "screen" session. So basically I can start it, then come back a day later and check that log. I was the same way, way too long to check plots. I have 1200, and that took about 8-10 hours. In the end, I had 25 on one disk that failed. (and I know why, user error on my part)
> 
> It does cause a few partials to fail while checking plots, fyi. But it wasn't too bad. But you'll be waiting about 2 days! Sorry. ;)

Thanks - I will go ahead and let that run.  What error did you get that showed you they failed.  Was there an actual error in that plot check log or was there something else you were looking for like the ratio being under .7?  Thanks!

**Comment by greg-fischer** [comment]
Actually it showed the listed bad plots at the end summery of the log.  So it was easy to pick them out.  
WARNING  25 invalid plots found: 
... then listed each plot file.

**Comment by berlef80** [comment]
> Actually it showed the listed bad plots at the end summary of the log. So it was easy to pick them out.
> WARNING 25 invalid plots found:
> ... then listed each plot file.

Great - I will wait for it to finish then! Thanks so much for your help with this.

**Comment by emlowe** [comment]
Closing this issue as there is no further information available.
