### ISSUE TITLE
[BUG] Last attempted Proof order display is reversed?

### ISSUE THREAD

**Issue by MaximusChia** [Chia-Network/chia-blockchain#7856]
**Describe the bug**
Looks like it started from 1.2.3
Last attemted proof display is showing challenges fom bottom to top. Newest challenges appear on bottom of the list
**To Reproduce**
Just started Chia 1.2.3 and start farming
Start Chia GUI and look on Farm section, wait for Challenges displaying.

**Expected behavior**
Before 1.2.3 the new challenges were updated upside down, with newest at the top. 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/84356558/127464753-3292541c-d242-44c7-97df-7943f12c06e9.png)

- OS: Win 10
Chia GUI 1.2.3

**Comment by xdustinface** [comment]
@emlowe didn't you apply this change in GUI recently?

**Comment by emlowe** [comment]
Closing - this was fixed at some point, newer challenges are at the top of the list again
