### ISSUE TITLE
[BUG] Stuck in Startup screen "Connecting to wallet"

### ISSUE THREAD

**Issue by thientd87** [Chia-Network/chia-blockchain#7857]
**Describe the bug**

**To Reproduce**

1. Click to App
2. Stuck in Connection to wallet too long

**Expected behavior**
show my wallet.

**Screenshots**

![Screenshot 2021-07-29 165950](https://user-images.githubusercontent.com/7514574/127472731-5caed87a-a431-4741-827c-97f9ae5aafa4.png)

**Desktop**

- OS: Window 10 21H1
- OS Version/Flavor: 
- CPU: Intel Core i5-8500

**Additional context**

**Comment by Alekssander85** [comment]
I have the same problem

**Comment by JerryLerman** [comment]
I also have the same problem

**Comment by SidneyMeles** [comment]
I have the same problem...

**Comment by goyometeojorito** [comment]
I have the same problem...

**Comment by joejordan** [comment]
Also have the same problem, v1.2.3.
