### ISSUE TITLE
 Error in log:   8, local variable 'farmer_string' referenced before assignment

### ISSUE THREAD

**Issue by Aidan24** [Chia-Network/chia-blockchain#7858]
**Describe the bug**
Multiple instances of the following in the log:

2021-07-29T10:30:32.167 farmer chia.farmer.farmer         : ERROR    update_pool_farmer_info failed: 8, local variable 'farmer_string' referenced before assignment

Connecting to 2 pools. Both seem to be working, but one is showing fairly consistent below 100% plot success rate since getting these errors.

**Desktop**
Windows 10
Intel i9

**Comment by emlowe** [comment]
This error is from your pool. The error code 8 and the string `local variable 'farmer_string' referenced before assignment` are both being sent back to from the pool.

**Comment by Aidan24** [comment]
Thanks. Do you think it would be possible to also include in the log which pool is sending the message back? I guess if people are using many pools this would be hard to work out from the current log entries.
