### ISSUE TITLE
having problem connect to the wallet[BUG]

### ISSUE THREAD

**Issue by vishwaphansal7** [Chia-Network/chia-blockchain#7874]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by alex19852202** [comment]
1. I'm open chia blockchain like administrator.
2. Beginning to connecting to wallet.
3. Connecting to wallet not doing.

OS: Windows 10 home version
CPU: rayzen 5 3600

P.S. file config.YAML and debug.log were reinstall, acsess to the folder mainnet open
