### ISSUE TITLE
[BUG] Failed to update 'payout_instructions'

### ISSUE THREAD

**Issue by GregoryGum** [Chia-Network/chia-blockchain#7875]
In ver 1.2.3 was added option to change payout instructions in the GUI.
As I understand this option to configure the destination wallet to recieve XCH from pool (like cold-wallet)

Steps:
1) Select 'Pool' tab
2) Click on '...' option to expand menu
3) Select option 'Edit Payout Instractions'
4) Set value and save

Problem: I see following ERROR in log.
```
INFO     GET /farmer response: {'authentication_public_key': '0xb274a6b6356764aa03890f1e335b1e929ac1744791548b01f592e9e3171a3162f2023448e88c19d6c66a6cdc74901360', 'payout_instructions': '60647ebb9a49d2a89a9618f552c432e2be024f4018e923b2bc4af18381c5ae38', 'current_difficulty': 18, 'current_points': 458}
INFO     PUT /farmer response: {'authentication_public_key': False, 'payout_instructions': False, 'suggested_difficulty': False}
ERROR    Failed to update farmer information on the pool https://na1.pool.space
INFO     Added unfinished_block 4cae27d8c5adc6fc435b2e89e5b2c5de82b6ec56df33e788b77021e4f370af9f, not farmed by us, SP: 52 farmer response time: 2.913397789001465, Pool pk xch1wzvp2xh83psjv97hd7re8jey8hjw00aqmh0yvhhnee2mvcn29s3s5uaydn, validation time: 0.15179920196533203, cost: 256086026, percent full: 2.328%
```

**Comment by xdustinface** [comment]
@GregoryGum You should ask the pool operator here if they implemented `PUT /farmer` properly. As you can see in the log the pool returns `'payout_instructions': False` which means they either didn't fully implement it or reject your payout instructions for some reason.

**Comment by zecasa** [comment]
i think i found the cause of this problem.  In the 'pool' tab and 'view  pool login link'  and click on the link that opens, Add the address where you will receive payment on the page that opens. 
The address from which you will receive payment is the same as your wallet address.  this is how i got rid of the error message. 'Failed to update farmer information on the pool https://na1.pool.space'
