### ISSUE TITLE
[BUG] Stuck in 1-10 hours, no reasons

### ISSUE THREAD

**Issue by LuckyMirror** [Chia-Network/chia-blockchain#7882]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by joelrb** [comment]
Please learn how to use the bug report. Add details. We don't understand what you're reporting so no one will be able to help you.
