### ISSUE TITLE
[BUG] Partials submitted to previous pool during wallet sync

### ISSUE THREAD

**Issue by F1DNA** [Chia-Network/chia-blockchain#7892]
**Describe the bug**

While syncing a fresh wallet DB, I noticed that when I got to around 540k block height where I initially created my nft and soon after joined xchpool, my node began submitting partials to pool.xchpool.org which is not the current pool I am with.  Is this really bad?  No, not currently.  But it shouldn't happen.  And, perhaps, the way the NFT's are setup it is unavoidable but then this should have been considered during design.

**To Reproduce**

1. Start a new wallet DB
2. Wait
3. Observe logs
4. See partials being submitted where they should not be going

**Expected behavior**

Partials not being sent to a pool the farmer no longer belongs to?

**Screenshots**

Not needed

**Desktop**

Not relevant

**Additional context**

Nope

**Comment by emlowe** [comment]
This is expected behaviour when syncing the wallet fresh again. One way to avoid this is to not start the farmer and only sync the wallet until complete - but this is only possible with CLI tools and not the UI.
