### ISSUE TITLE
chia app problem 

### ISSUE THREAD

**Issue by ayman992** [Chia-Network/chia-blockchain#7898]
Hello, this obvious problem appears in the picture three days ago and I could not find a solution. Please help
![555](https://user-images.githubusercontent.com/88268728/127765055-3435c054-8c1c-4f35-b12a-a1d91ff4aedd.jpg)
![666](https://user-images.githubusercontent.com/88268728/127765059-c645684e-0cdb-453d-bf5f-5cf14de3c608.jpg)
![بدون عنوان](https://user-images.githubusercontent.com/88268728/127765060-b1b4cb85-81b0-4cb9-9229-9cbc3ca4f61f.jpg)

**Comment by albert23** [comment]
Same here.

**Comment by Marcin19810623** [comment]
I have the same problem

**Comment by albert23** [comment]
Fixed uninstalling, moving .chia folder, installing and moving .chia folder again again...

**Comment by Marcin19810623** [comment]
how do it this?

**Comment by loppefaaret** [comment]
WINDOWS COMPLETE CONFIG RESET

Close down the Chia app, and open up a PowerShell window, and execute the below commands one at a time:
```
mv ~\.chia\mainnet ~\.chia\old
```
This will remove all settings you had, you will have to resync you wallet. You will have to re-add any plot directories and other settings you may have had set.

if this works for you, you can try and close down the Chia app, and execute the below line one at a time in a PowerShell window:
```
mv ~\.chia\old\db ~\.chia\mainnet\
```
this will try and move the old blockchain database back in, and save you having to sync the blockchain from 0
if this causes you to have spinning circles again, you have to do this is PowerShell after closing down Chia app:
```
del -force ~\.chia\mainnet\db\block*
```

**Comment by Marcin19810623** [comment]
I have like this    
            
          
     
      
       
        Dnia 2 sierpnia 2021 16:08 loppefaaret ***@***.***&gt; napisał(a):
       
    
       
         
 WINDOWS COMPLETE CONFIG RESET 
 Close down the Chia app, and open up a PowerShell window, and execute the below commands one at a time: 
 mv ~\.chia\mainnet ~\.chia\old
 
 This will remove all settings you had, you will have to resync you wallet. You will have to re-add any plot directories and other settings you may have had set. 
 if this works for you, you can try and close down the Chia app, and execute the below line one at a time in a PowerShell window: 
 mv ~\.chia\old\db ~\.chia\mainnet\
 
 this will try and move the old blockchain database back in, and save you having to sync the blockchain from 0  
if this causes you to have spinning circles again, you have to do this is PowerShell after closing down Chia app: 
 del -force ~\.chia\mainnet\db\block*
