### ISSUE TITLE
[BUG]Wallet import mnemonic words do not see roll out records

### ISSUE THREAD

**Issue by wanming851** [Chia-Network/chia-blockchain#7900]
Wallet import mnemonic words do not see roll out records

**Comment by loppefaaret** [comment]
could you perhaps try and better explain exactly what your problem is ?
i think it might be that after importing a 24 word mnemonic on a new machine, you don't see outgoing wallet transactions ?
the wallet does not list outgoing transactions after a resync!

**Comment by wanming851** [comment]
> could you perhaps try and better explain exactly what your problem is ?
> i think it might be that after importing a 24 word mnemonic on a new machine, you don't see outgoing wallet transactions ?
> the wallet does not list outgoing transactions after a resync!

Yes, the new machine imported the mnemonic words, no roll-out records

**Comment by keliew** [comment]
Probably means your wallet (not node) isn't sync-ed.
