### ISSUE TITLE
MacOs forever connecting wallet

### ISSUE THREAD

**Issue by deanh2k** [Chia-Network/chia-blockchain#7903]
I keep trying different versions of Chia but never get connected to wallet.

Where is wallet stored?

I don't find .chia folder even if hidden

I made sure firewall is okay with chia and accepts incoming connections.

Should I see a .chia folder under /Users/{username} ?

Chia version 1.23

Mac OS 10.13.6  High Sierra

**Comment by loppefaaret** [comment]
macOS Mojave (10.14.x) or newer is required.
