### ISSUE TITLE
Can't connect new instance to existing pool [BUG]

### ISSUE THREAD

**Issue by i00** [Chia-Network/chia-blockchain#7909]
**Describe the bug**

**To Reproduce**

1. I had two harvesters both with the wallet fully sync'ed and added the pool and created plots for this pool to one; it automatically came in for the other instance.
2. I fired up another computer, installed chia interface, fired it up and waited till it sync'ed.
3. The existing pool isn't listed under "Pools"!

**Expected behavior**

Pools get listed after the wallet sync finishes

**Screenshots**

**Desktop**

- OS: Windows
- OS Version/Flavor: 10
- CPU: E5-2680V3

**Additional context**

**Comment by loppefaaret** [comment]
is this with version 1.2.3 ? did you try and restart the app, or even reboot ?

**Comment by i00** [comment]
Yes 1.2.3 ... I deleted the wallet and blockchain database and is currently resyncing.

**Comment by puppetmm** [comment]
I have the same problem。
I edit the config.yaml ,add pool parameter。Then I can see the "pool"，but can't harvest.
2021-08-03T13:22:50.105 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://chia.migpool.com, Cannot connect to host chia.migpool.com:443 ssl:<ssl.SSLContext object at 0x0000028E5AA959C0> [信号灯超时时间已到]
2021-08-03T13:29:43.567 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://chia.migpool.com, Cannot connect to host chia.migpool.com:443 ssl:<ssl.SSLContext object at 0x0000028E5AB65EC0> [信号灯超时时间已到]

**Comment by i00** [comment]
Ok ... finished resyncing today ... pool appeared as expected ... don't know why it didn't the first time!
Should be investigated!

**Comment by Anturaju93** [comment]
It only appears only after wallet db resync. It should work with a copy of the wallet db, from another full node, but it does not. A quick fix I found is to copy wallet and blockchain db, wait to resync and if pools NFT don't appear just click on create a new NFT. In 2 minutes the old NFTs are showing and pooling, but this way you spent 1 mojo and have another useless NFT.

**Comment by emlowe** [comment]
Closing issue per comment that resyncing resolves this. We are tracking issues where they don't always appear
