### ISSUE TITLE
[BUG] chia start farmer-no-wallet + NFT plots

### ISSUE THREAD

**Issue by bb-hendrik** [Chia-Network/chia-blockchain#7926]
**Describe the bug**
chia start farmer-no-wallet will not give a warning that you can't farm NFT plots. 

**To Reproduce**

chia start farmer-no-wallet
chia farm summary -> farming status: farming, shows plot count (OG+NFT), gives error about can't show reward info because no wallet, but no error that you are not farming the NFT plots, only OG plots. 

**Expected behavior**
being able to farm without keeping wallet DB in sync. or at least being warned about the consequences of no wallet DB

- OS: debian 11

**Comment by mariano54** [comment]
You should be able to farm those NFT plots, but you cannot see any info about them because your wallet is not synced / running.

I agree a better error message would be helpful here

**Comment by bb-hendrik** [comment]
Ok. thanks. I'll check the log. The fact that chia plotnft show also doesn't work without wallet might confused me then
