### ISSUE TITLE
[BUG] Connection to wallet  stuck

### ISSUE THREAD

**Issue by aspasoj** [Chia-Network/chia-blockchain#7953]
Describe the bug

To Reproduce

Click to App
Stuck in Connection to wallet too long
Expected behavior
show my wallet.

Screenshots

Desktop

OS: Big Sur 
OS Version/Flavor:11.5.1 (20G80)
CPU: M1

**Comment by loppefaaret** [comment]
You might have gotten corrupted the blockchain database, and unfortunately have to remove it, and resync from 0.
To do this, try these isntructions:
MacOS BLOCKCHAIN DATABASE RESET

Close down Chia, and open up a terminal, and execute the below command:
```
mv ~/.chia/mainnet/db/block* ~/Desktop/
```
Then try opening up the Chia again
if it worked, you can remove the files we put on the Desktop!

**Comment by aspasoj** [comment]
> You might have gotten corrupted the blockchain database, and unfortunately have to remove it, and resync from 0.
> To do this, try these isntructions:
> MacOS BLOCKCHAIN DATABASE RESET
> 
> Close down Chia, and open up a terminal, and execute the below command:
> 
> ```
> mv ~/.chia/mainnet/db/block* ~/Desktop/
> ```
> 
> Then try opening up the Chia again
> if it worked, you can remove the files we put on the Desktop!

it is still the same whether there is another option

**Comment by loppefaaret** [comment]
ok, then i would try and completely remove all the working data, and try letting the Chia app generate a new config folder
this will need you to redo all previous settings you had, only thing it will remember is your key!
you will also be syncing from 0:
MacOS COMPLETE CONFIG RESET

Close down Chia, and open up a terminal, and execute the below command:
```
mv ~/.chia/mainnet ~/Desktop/
```
Then try opening up the Chia again
This will remove all working data, and you will need to redo any settings you had, and sync both the blockchain and your wallet(s) from 0 again.
If it worked, you can remove the files we put on the Desktop.
