### ISSUE TITLE
`chia wallet show` says "No keys loaded" even after importing a key

### ISSUE THREAD

**Issue by buhrmi** [Chia-Network/chia-blockchain#7954]
Hi there,

I have installed chia on a Raspberry Pi following [Toms Hardware Guide](https://www.tomshardware.com/how-to/raspberry-pi-chia-coin).

I have imported my key via `chia keys add`. `chia keys show` displays the correct fingerprint. However, `chia start farmer` crashes with `Failed to connect to keychain service` in [farmer.py#133](https://github.com/Chia-Network/chia-blockchain/blob/fa71f91f4cbef4e28aac670e7ed0b27402be6036/chia/farmer/farmer.py#L133). Also, `chia wallet show` only displays the message `No keys loaded`. I'm not sure what is going on there. Any hint on what I could try to make it work?

**Comment by Anturaju93** [comment]
Just install the GUI for Raspberry Pi, it works great, even won my a block. I'm running my farm on Raspberry Pi 4 with 8 GB RAM, using the Chia GUI.

**Comment by FedericoLaTorre** [comment]
Same issue here with ubuntu 20.04 with a desktop.

**Comment by buhrmi** [comment]
> Just install the GUI for Raspberry Pi, it works great, even won my a block. I'm running my farm on Raspberry Pi 4 with 8 GB RAM, using the Chia GUI.

That results in the following (probably also related) error after entering the mnemonic
![image](https://user-images.githubusercontent.com/51177/128407380-42c2d038-1660-4418-add6-58a11622f110.png)

**Comment by loppefaaret** [comment]
@buhrmi could you figure this out ? if not, please confirm that you are on pi4 with ubuntu 21.04 ? do you have any other usage other than chia prior on the system ? (perhaps something that uses the keychain to store password / keys?)

**Comment by buhrmi** [comment]
@loppefaaret unfortunately I am still having this issue. Yeah, it's a completely fresh system (pi4 with ubuntu 21.04) with no prior usage whatsoever.

**Comment by emlowe** [comment]
Which version did you install - did you install using using git?

**Comment by paninaro** [comment]
@buhrmi there was a fix that was applied to the main branch shortly after you opened this issue. Can you verify that you're using the main branch? 'latest' should be safe to use.

**Comment by buhrmi** [comment]
@paninaro thank you, I pulled the latest code and now it seems to work
