### ISSUE TITLE
[BUG] 2021-08-06T01:10:56.972 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):   File "chia\rpc\rpc_server.py", line 81, in inner   File "chia\rpc\rpc_server.py", line 164, in open_connection ValueError: Start client failed, or server is not set

### ISSUE THREAD

**Issue by LuckyMirror** [Chia-Network/chia-blockchain#7958]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by loppefaaret** [comment]
This is usualy an entry that appears after a manual connection attempts fails
I'm closing this issue - if you need further assistance, we got our https://github.com/Chia-Network/chia-blockchain/discussions/categories/support 
We also have an Official Keybase chat here:
https://keybase.io/team/chia_network.public
