### ISSUE TITLE
Люди, я заебался. Эта хуета может проработать трое суток, а потом отваливается. Подключается, синхронизируется и через 1,2,3 минуты всё останавливается. Ноды-хуёды, порты-хуерты - всё нахуй. Я делал всё, что нашёл. Есть идеи?

### ISSUE THREAD

**Issue by LuckyMirror** [Chia-Network/chia-blockchain#7960]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by MatveyFV** [comment]
Хотелось бы побольше конкретики, характеристики ПК например, количество плотов...

**Comment by keliew** [comment]
Knowing what `debug.log` say may be helpful too.

**Comment by loppefaaret** [comment]
I can understand that you get frustrated when stuff doesn't work as expected, but please try to and refrain from this level of language in the future... closing and locking it down
I can recommend our support discussions here:
https://github.com/Chia-Network/chia-blockchain/discussions/categories/support
Or our official Keybzase chat here:
https://keybase.io/team/chia_network.public
