### ISSUE TITLE
[BUG]: ERROR    Harvester did not respond. You might need to update harvester to the latest version

### ISSUE THREAD

**Issue by Gazza7zs** [Chia-Network/chia-blockchain#7963]
Started recieving the following error:

2021-08-06T04:10:33.871   farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need   to update harvester to the latest version
--
2021-08-06T04:13:39.879 full_node   asyncio                 : ERROR    Exception in callback   _ProactorBasePipeTransport._call_connection_lost(None)
ConnectionResetError: [WinError 10054] An   existing connection was forcibly closed by the remote host
2021-08-06T04:12:38.070 farmer   chia.farmer.farmer         : ERROR    Harvester did not respond. You might need   to update harvester to the latest version

websockets.exceptions.ConnectionClosedError:   code = 1006 (connection closed abnormally [internal]), no reason

System: Windows 10 Pro
Chia, latest version 1.2.3
No remote harvesters, all running from single system

**Comment by keliew** [comment]
And it's fine after a complete restart?

**Comment by Nusstoertchen** [comment]
I have the same problem.
Plot Check is done, all plots are ok
restart has brought nothing.
I've only had the problem since version 1.2.3

**Comment by ShilohMy** [comment]
2021-08-07T09:19:33.833 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version

**Comment by Gazza7zs** [comment]
issue has gone, no restart required, issue had not appeared since upgrading well over a week ago, so likely not a local issue??

**Comment by ShilohMy** [comment]
v1.2.3， this issue has gone?

**Comment by ShilohMy** [comment]
But I can't make a block

**Comment by Nusstoertchen** [comment]
what kind of update?
I only have the problem since version 1.2.3, I am not aware of a newer version.

**Comment by Gazza7zs** [comment]
This issue come up a week AFTER updating to the latest version 1.2.3.
Checking for errors and warning again today revealed no further instances and haven't done a restart. This leads me to think it is not an issue locally (my system), but a glitch. Need someone with authority to respond. Again for ME this only occurred with the latest version which was installed over a week ago.

**Comment by Drakanus** [comment]
> This issue come up a week AFTER updating to the latest version 1.2.3.
> Checking for errors and warning again today revealed no further instances and haven't done a restart. This leads me to think it is not an issue locally (my system), but a glitch. Need someone with authority to respond. Again for ME this only occurred with the latest version which was installed over a week ago.

same here

**Comment by loppefaaret** [comment]
This is the new expansion of the farmer <-> harvester protocol, and the harvester did not respond to status requests from the farmer - hence the above log entry... 
If you have some entries of these in the logs, it would indicate a communication problem during the period of the messages.
as you say the entries stopped again, the issue would have passed, and i assume no longer an issue ?
if you are able to reproduce the issue somehow, we would love to hear more about it

**Comment by cccat6** [comment]
Same issue here.
I guess it is the problem of harvester loading plots.
I have PiB of plots on a single machine. It will have this problem. I can solve this problem with split the plots into two harvesters. The threshold that will cause this problem in my place is 800TiB plots on a single harvester.
I do not have this problem before 1.2.0. It might be caused by some new features in NFT plots. Previously a single harvester can handle about 2PiB of plots.

**Comment by keliew** [comment]
> Same issue here.
> I guess it is the problem of harvester loading plots.
> I have PiB of plots on a single machine. It will have this problem. I can solve this problem with split the plots into two harvesters. The threshold that will cause this problem in my place is 800TiB plots on a single harvester.
> I do not have this problem before 1.2.0. It might be caused by some new features in NFT plots. Previously a single harvester can handle about 2PiB of plots.

You could pull [main and test](https://github.com/Chia-Network/chia-blockchain/commit/53149f2e57743e203aba1d25a89786edcf1f78ab) the new stuff for plot management (https://github.com/Chia-Network/chia-blockchain/pull/8009).

**Comment by berlef80** [comment]
I have the exact same issue on one of my computers.  I have the exact same set up on two laptops - exactly same laptop, same type of HDD USB drives, USB hubs, and one has the issue of crashing ever 1-12 hours and the other one runs fine.  I have checked for bad plots and removed all of them. It works if I restart the whole computer, but I am lost at this point as to what could be causing it.

**Comment by Gazza7zs** [comment]
@loppefaaret 
Was not able to reproduce but have just had the following errors appearing. followed by a new warning?
Not sure if the final error is related 
Appreciate your assistance 



PS C:\Users\gazza\AppData\Local\chia-blockchain\app-1.2.3\resources\app.asar.unpacked\daemon> Get-Content -Path "~\.chia\mainnet\log\debug.log" | Select-String -Pattern "error"

2021-08-16T15:32:08.478 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-16T15:33:39.496 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-16T15:35:10.506 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-16T15:36:41.536 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-16T15:38:12.567 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-16T15:38:54.765 harvester chia.harvester.harvester: ERROR    Error using prover object badbit or failbit after reading size 4 at position 107551054919
2021-08-16T15:38:54.769 harvester chia.harvester.harvester: ERROR    File: L:\plot-k32-2021-08-12-22-05-e11160432109f6e2504386b1306552dfbfb460cca7bb06542f3e72a043e7f7b4.plot Plot ID:
e11160432109f6e2504386b1306552dfbfb460cca7bb06542f3e72a043e7f7b4, challenge: 2285e067292200eecc200c8335b45be2c1e520de843665a680533a77bbb958f1, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x00000213637C3CB0>,
pool_public_key=None, pool_contract_puzzle_hash=<bytes32: cfd5c5433b97fca99a595b6c3ba564419cd4db2ae2674ec14234e3eb89db139e>, plot_public_key=<G1Element
ae4f1ad17a985d237fd6981719259e7ba19d8902944223c96d32fcfb6daa1094211fa2a0fe80cb30a13d80d47b70b1ee>, file_size=108841187251, time_modified=1628803929.6338675)

**Comment by JefrenAbalos-kumu** [comment]
I have the same problem everything was working fine until august 26 (computer had been running fine for weeks), when I saw in my logs that I suddenly stopped getting partials from my pool. Saw the error and updated to 1.2.5 but still no luck.

**Comment by keliew** [comment]
> I have the same problem everything was working fine until august 26 (computer had been running fine for weeks), when I saw in my logs that I suddenly stopped getting partials from my pool. Saw the error and updated to 1.2.5 but still no luck.

Could be the pool? Is self-pooling working fine?
