### ISSUE TITLE
my plots are not showing in gui

### ISSUE THREAD

**Issue by k-firoda** [Chia-Network/chia-blockchain#7969]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by loppefaaret** [comment]
What Operating System are you on ? Are you on the latest Chia version ? When did this issue start ? are you able to replicate the issue ? what have you tried to remedy the issue ?
