### ISSUE TITLE
Version 1.1.7, solo, after the explosion of 1.75 coins were hit to a new address, the coins were lost

### ISSUE THREAD

**Issue by daowudi123** [Chia-Network/chia-blockchain#7976]
![-23c04293bd3ef5df](https://user-images.githubusercontent.com/83652462/128601981-a5a0799e-7a38-4a8c-8366-bbc91b42ae33.png)
![IMG_20210807_204605](https://user-images.githubusercontent.com/83652462/128601989-d887f27f-00e9-408a-9bc6-c54d7eb6916f.jpg)
![IMG_20210807_195555](https://user-images.githubusercontent.com/83652462/128601995-2d5f4e14-b37a-40ee-93e2-dd2964f114f5.jpg)
burst a block. However, only 0.25 coins were received. Another 1.75 was called to a new address. Never joined any mine pools, nor did it disclose passwords. It is suspected that the system automatically generates a new mine pool address. But the wallet can't see the address

**Comment by daowudi123** [comment]
Upgrade to 1.2.3, 1.75 coins still do not appear. Upon enquiry, 1.75 coins were hit to a new address, which contained only this transaction

**Comment by daowudi123** [comment]
The mine pool address in the wallet is the same as the miner's address. But I don't know why 0.75 coins would be hit at a new address. Never joined any mine pools

**Comment by loppefaaret** [comment]
Please see #7982
