### ISSUE TITLE
[BUG] chia wallet get_transactions command only returns the last 50 transactions

### ISSUE THREAD

**Issue by w5lee** [Chia-Network/chia-blockchain#7978]
**Describe the bug**
chia wallet get_transactions command only returns the last 50 transactions

**To Reproduce**

run the command chia wallet get_transactions it will only give you 10 screens of 5 transactions

**Expected behavior**
I expect it to show me all transactions that have occured

**Screenshots**
If needed will provide. I don't think they are necessary.

**Desktop**

- OS: Linux
- OS Version/Flavor: Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

- CPU: AMD Ryzen 9 5950X 

**Additional context**
I need this information to report mining income. It would be nice to have a command to run that would produce a file with the following info:
transactionid,date,amount,(optional usd value)
even better yet an api to call to have the wallet tied into tax software

**Comment by altendky** [comment]
I'm taking a look at this already.  Hopefully I'll get a PR in today.

**Comment by w5lee** [comment]
Thanks Kyle

**Comment by sergiosurvival** [comment]
no sincroniza wallet

**Comment by sergiosurvival** [comment]
![2021-08-08](https://user-images.githubusercontent.com/83919237/128629493-2854ec3a-cd83-4e2e-897b-1c4208cfb6a1.png)

**Comment by sergiosurvival** [comment]
no sincroniza wallet aque se deve alguien le pasa un saludo

**Comment by altendky** [comment]
@sergiosurvival, your comment and screenshot seem unrelated to the issue reported here.  For support, please [open a new discussion](https://github.com/Chia-Network/chia-blockchain/discussions/new?category=support).

From Google Translate:
> @sergiosurvival, su comentario y captura de pantalla parecen no estar relacionados con el problema reportado aquí. Para obtener ayuda, abra una nueva discusión.

**Comment by sergiosurvival** [comment]
okk

**Comment by altendky** [comment]
This is not stale.  There is a PR in progress that addresses this.
