### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by riga212** [Chia-Network/chia-blockchain#7980]
**Describe the bug**

**To Reproduce**

**Expected behavior**

<img width="1173" alt="Screen Shot 2021-08-07 at 6 22 43 PM" src="https://user-images.githubusercontent.com/88573141/128615204-91bdfadb-1b02-44d6-9d33-9b55a2f67ee0.png">
<img width="1177" alt="Screen Shot 2021-08-07 at 6 26 30 PM" src="https://user-images.githubusercontent.com/88573141/128615277-d00ac92d-eec2-4261-9810-2319f7817d8e.png">
<img width="1194" alt="Screen Shot 2021-08-07 at 6 26 52 PM" src="https://user-images.githubusercontent.com/88573141/128615290-d401ffec-580e-4abf-94a2-5177f320d9a8.png">
<img width="1189" alt="Screen Shot 2021-08-07 at 6 27 40 PM" src="https://user-images.githubusercontent.com/88573141/128615305-576c1e2c-a978-4914-b1d2-989960ad01d8.png">

**Screenshots**

**Desktop**

- OS: <11.5-- BIG SUR -->
- OS Version/
- CPU: < -->

**Additional context**

**Comment by loppefaaret** [comment]
This might be a sign of a corrupted blockchain database - which will require you to remove the blockchain database, and resync from 0:
MacOS BLOCKCHAIN DATABASE RESET

Close down Chia, and open up a terminal, and execute the below command:
```
mv ~/.chia/mainnet/db/block* ~/Desktop/
```
Then try opening up the Chia again
if it worked, you can remove the files we put on the Desktop!

**Comment by riga212** [comment]
Hello Loppefaaret, You are genius! For two week no-one from a space pool could help me. but you just gave me a simple command and everything start worked !!! I am just cry! I owe you! 
Also , would like to ask one more question if it make sense to open up a port 8444 as many people advising, even official chia says this. If it advisable you may know what should I insert in table? I did it but now opens. I have inserted my local IP address because my external it doesn't allow me to insert in this table. Thank you very much for your help!!!!!!!!!!!!!!!!!!!!!!!


<img width="1197" alt="Screen Shot 2021-08-13 at 9 58 18 PM" src="https://user-images.githubusercontent.com/88573141/129431098-af8954de-ee14-4da0-8d7e-83284b49eebb.png">
