### ISSUE TITLE
[BUG]Block rewards of 1.75 coins were not received. No mine pools have been joined. But the coin was hit at a new address. There was no new address for any transactions before

### ISSUE THREAD

**Issue by daowudi123** [Chia-Network/chia-blockchain#7982]
Previously, version 1.1.7. Only 0.25 coins were received after harvesting the block. The address of the mine pool in the wallet has not changed. After re-updated version 1.2.3. 1.75 coins are still not seen。
Was the computer hacked? Now everything's fine with your wallet. How to find the missing 1.75 coins reward. How to make sure the next time is right
![IMG_20210807_195555](https://user-images.githubusercontent.com/83652462/128618645-9db01509-464f-4e11-abdf-9e67910c333b.jpg)
![IMG_20210807_204605](https://user-images.githubusercontent.com/83652462/128618650-e73dd399-8648-44d6-a885-6c1d2b1cd9e3.jpg)
![-23c04293bd3ef5df](https://user-images.githubusercontent.com/83652462/128618652-72361ab6-d1fa-464b-a5dd-a05a5c41ba61.png)

**Comment by eusergiopt** [comment]
I have an identical problem. never joined any pools and solo mining from beginning.
I can see the coin in my wallet but it does not add up to my balance and I'm unable to use it...
https://github.com/Chia-Network/chia-blockchain/discussions/7999

**Comment by loppefaaret** [comment]
Have you used 3rd party software from other places than chia.net or our github ? 
have you ever joined a pool ?
have you run unreleased developer versions on mainnet ? 
the block you farmed is https://xchscan.com/blocks/678261
and it clearly shows the pool reward going to a seperate address
are you using plots tied to a plotnft that is pointing to a pool ?

**Comment by eusergiopt** [comment]
I have never joined any pool, never gave any keys unless I was hacked. But I guess in that case they would wipe the wallet...
it seems the chia coin is still in the adress I see in my wallet..
Also I see the coin incoming and not going out!

**Comment by eusergiopt** [comment]
but I guess my case seems somewhat different..

**Comment by loppefaaret** [comment]
Have you created new plots pointing to a plotNFT under the "Pools" tab ? 
if you are solo farming with a plotNFT, you would have to click "Claim Rewards" on the plotNFT

**Comment by emlowe** [comment]
The 1.75 pool rewards were sent to a different address because your plots have that pool key baked into the plot when the plot was created (either using the UI to set the pool public key or the -p CLI option). You can check this with `chia plots check` - it will show your farmer key and pool key. Feel free to re-open issue with more details
