### ISSUE TITLE
[BUG] Farm not loading

### ISSUE THREAD

**Issue by Mitch2208** [Chia-Network/chia-blockchain#7983]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

  
Chia Blockchain application is open and connected to my wallet, it will not load plots tab or the farm tab, have restarted computer and application multiple times, nothing is fixing this issue, pls help

**Comment by sd016808** [comment]
I remove the config.yaml and restart chia.exe can solve the plots/farm tabs disappear problem. 
But for the pool tab to disappear, I need to join a new pool then the old pool info can be shown.
This is very troubling.
