### ISSUE TITLE
Chia Blockchain application is open and connected to my wallet, it will not load plots tab or the farm tab, have restarted computer and application multiple times, nothing is fixing this issue, pls help[BUG]

### ISSUE THREAD

**Issue by kryshal** [Chia-Network/chia-blockchain#7986]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by sergiosurvival** [comment]
![2021-08-08](https://user-images.githubusercontent.com/83919237/128629237-9299f33c-a4e9-4a70-8b39-46cf3c70dd27.png)

**Comment by sergiosurvival** [comment]
me envian todos los forks saldo menos chaingreen me pone que no esta sincronizada y si lo esta en la ultima version y sincronizado me lee las parcelas pasaron la prueba a la hora de reloj

**Comment by sergiosurvival** [comment]
no se a que se deve ese error

**Comment by loppefaaret** [comment]
I'm going to close this issue, and transfer it to a Support discussion instead - if we find a bug there, we can open up a propper issue report
