### ISSUE TITLE
My plots will not load 

### ISSUE THREAD

**Issue by kryshal** [Chia-Network/chia-blockchain#7992]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

![Plots](https://user-images.githubusercontent.com/81988164/128642903-18a2d4f7-de52-4da9-b268-85c482485b11.jpg)
![Pool](https://user-images.githubusercontent.com/81988164/128642904-383fa170-507e-4e1b-8fc6-2b62821c54a1.jpg)

My plots are constantly loading and won't load , My OS is Windows 10

**Comment by n00bator** [comment]
Same problem here.

Debug.log says:
2021-08-09T09:27:56.189 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2021-08-09T09:27:58.221 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:8447 ssl:<ssl.SSLContext object at 0x0000023B90B5F5C0> [The remote computer refused the network connection]
2021-08-09T09:28:01.237 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8447}
2021-08-09T09:28:01.851 full_node chia.full_node.full_node: INFO      Updated peak to height 690199, weight 751925856, hh e11ebed4a045ea0eae4db2e12d79ad7a788124e788f93c765568595e22434f04, forked at 690198, rh: b5a32c354d298e75b0d7698fb7d7e502a4ae72d239b67b26c7449830a49b742d, total iters: 2407739380064, overflow: False, deficit: 0, difficulty: 2624, sub slot iters: 129499136, Generator size: No tx, Generator ref list size: No tx

DevTools:
DevTools failed to load SourceMap: Could not parse content for file:///C:/Users/Robert/AppData/Local/chia-blockchain/app-1.2.3/resources/app.asar/build/renderer/js/493.js.map: Unexpected end of JSON input

**Comment by alebeierbach** [comment]
I have the same problem.. Please help!!

**Comment by Mitch2208** [comment]
Same Problem

**Comment by n00bator** [comment]
I solved it this way:
1. I uninstalled Chia Blockchain,
2. deleted folder c:\Users\[user_name]\AppData\Local\chia-blockchain
3. deleted folder c:\Users\Robert\AppData\Roaming\Chia Blockchain
4. than I renamed c:\Users\Robert\.chia to e.g. c:\Users\Robert\.chia-OLD
5. installed Chia app again
6. launched Chia app and closed it after checking if Plot tab works.
7. Than moved files blockchain_v1_mainnet.sqlite from ...\.chia-OLD\mainnet\db\ to ...\.chia\mainnet\db\
8. Launched GUI app again and it worked.

:D
Please let me know if it worked for you?
TNX

**Comment by alebeierbach** [comment]
> I solved it this way:
> 
> 1. I uninstalled Chia Blockchain,
> 2. deleted folder c:\Users[user_name]\AppData\Local\chia-blockchain
> 3. deleted folder c:\Users[user_name]\AppData\Roaming\Chia Blockchain
> 4. than I renamed c:\Users[user_name].chia to e.g. c:\Users[user_name].chia-OLD
> 5. installed Chia app again
> 6. launched Chia app and closed it after checking if Plot tab works.
> 7. Than moved files blockchain_v1_mainnet.sqlite from ....chia-OLD\mainnet\db\ to ....chia\mainnet\db\
> 8. Launched GUI app again and it worked.
> 
> :D
> Please let me know if it worked for you?
> TNX

Now it works, thanks bro

**Comment by rossh2os** [comment]
So 3 out of my 6 locations came up. When I copied the DB over it all broke again and did not resolve the issue.  It is right back to being the piece of ____ that was before. Also my wallet says it is empty now so I am not sure how that happened. It was all good until the DB replacement happened.

**Comment by rossh2os** [comment]
Tried it again with deleting everything and without the DB copy and all plots showed up. I am just going to let the system sync online. I think my database got screwed up. I upgraded from 1.1.7 to 1.2.3 and I am guessing something didn't go right. I will say GPU and ASCI mining is much easier and more profitable at this moment.
