### ISSUE TITLE
your config.yaml has an issue.[BUG]

### ISSUE THREAD

**Issue by noonondang** [Chia-Network/chia-blockchain#7996]
**Describe the bug**

**To Reproduce**

Error 13] Permission denied. You are trying to access a file/directory without having the necessary permissions. Most likely one of the plot folders in your config.yaml has an issue.

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by markusmazurczak** [comment]
Please close this one as you opened another one with the same problem
