### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by charleybin** [Chia-Network/chia-blockchain#7998]
**Describe the bug**

**To Reproduce**
can't add a plot. My system is win 10. it stopped at 8% for a whole day. this is more than 5 times failed to add a plot on my machine. I'v been successful added 5 plot before. you may check the time  from screenshots.

![image](https://user-images.githubusercontent.com/1089391/128730510-36f0a23a-433e-477f-ad6d-63adbda2de0f.png)

Starting plotting progress into temporary dirs: D:\chia_temp and D:\chia_temp
ID: 2c2752db0a8ba93e87a35be88a714863064560faf0e0e0e011cefdfcabb70a19
Plot size is: 32
Buffer size is: 6000MiB
Using 128 buckets
Final Directory is: F:\chia
Using 4 threads of stripe size 65536
Process ID is: 13908

**Expected behavior**

can success add plot.

**Screenshots**

![image](https://user-images.githubusercontent.com/1089391/128728259-cb1ab285-dc05-41af-9a11-c1fc1b9be1ef.png)

![image](https://user-images.githubusercontent.com/1089391/128728489-3926bea8-7dcd-49d0-aa6d-5721bf4feb11.png)

currenlty files in D:\chia_temp:
![image](https://user-images.githubusercontent.com/1089391/128729157-35cdd879-6901-4278-a0a2-1fe42beb99cc.png)

![image](https://user-images.githubusercontent.com/1089391/128729049-02112a45-a9da-421c-b0b8-a53bf3fdac99.png)

disk info:
![image](https://user-images.githubusercontent.com/1089391/128729420-01d7cd7a-dc16-4815-9d2e-b574b5012c8b.png)

![image](https://user-images.githubusercontent.com/1089391/128729476-9d1b0015-60ca-40f1-9444-c13bac41cdc1.png)

system info:
![image](https://user-images.githubusercontent.com/1089391/128728844-20184787-d91b-4df2-ac32-b4cb387c3520.png)

![image](https://user-images.githubusercontent.com/1089391/128728917-a1430bde-07af-403b-b68f-ad9a5bda2d60.png)

**Desktop**

- OS:   Windows 10
- OS Version/Flavor:  Education Version
- CPU:   Intel 6700K 

**Additional context**

**Comment by loppefaaret** [comment]
This can sometimes be sign of an not entirely stable overclock - could you try and reboot into your BIOS, and try and disable XMP and/or enhance core profiles (CPU overclocks) and try again ? or you could perhaps try and run a memory test like `memtest86` ?
