### ISSUE TITLE
BUG[BUG]

### ISSUE THREAD

**Issue by noonondang** [Chia-Network/chia-blockchain#8000]
**Describe the bug**

**To Reproduce**

[Error 13] Permission denied. You are trying to access a file/directory without having the necessary permissions. Most likely one of the plot folders in your config.yaml has an issue.

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by markusmazurczak** [comment]
Did you check the permissions of your plot folder(s)?
