### ISSUE TITLE
chia wallet show error

### ISSUE THREAD

**Issue by chriszahrt** [Chia-Network/chia-blockchain#8011]
I have a script that runs chia wallet show every 10 seconds on a windows 2016 Server.
For the most part it returns good data regularily but occasionally it errors out with the following output.
It has been doing this to my knowledge with every version of chia since at least 1.1.7

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F1AB323790>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 746, in call_soon
  File "asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

I found this link when looking around.  It might be helpful.
https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop

**Comment by kemal24** [comment]
selam cüzdanımda tam node durumumda ,açılmıyor sürekli dönerek arama yapıyor .sebebi nedir.
