### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mohammadsabet** [Chia-Network/chia-blockchain#8018]
hi all. my wallet stoped at ( Connecting to wallet... ) what should i do to improve this?! 
 its for 2 days :((

**Comment by a7reza** [comment]
me too

**Comment by a7reza** [comment]
منم مث تو به نظرت چرا اینجوری شده؟؟

**Comment by a7reza** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/58534694/128935723-391c1e1d-7f74-4209-8bdd-b90f74678b47.png)

**Comment by loppefaaret** [comment]
please see #8019
