### ISSUE TITLE
Need a way to check a single plot

### ISSUE THREAD

**Issue by i00** [Chia-Network/chia-blockchain#8023]
You should be able to specify individual plots to check via filename.

I have occasional plots come up as being invalid in the Chia interface...
And when I check all of the plots ... guess what they are fine (I suspect the network share was down for a second)!
It would be nice to be able to check them individually.

**Comment by keliew** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#check

See `-g`.

**Comment by loppefaaret** [comment]
Issue is resolved, closing.
