### ISSUE TITLE
Multiple Wallets problem on same Gui Node SW

### ISSUE THREAD

**Issue by jawadakr** [Chia-Network/chia-blockchain#8024]
I have 2 wallets / keys added on my main node server gui.

Key 1 contains roughly around 100 og plots which I am still mining. The reason is that I am still plotting new nft plots on spare drives and decided to come back to those og drives in the end.

Key 2 contains new nft plots.

The issue I am seeing is that gui sw only work with one key / wallet at a time.

If I selected my NFT key to check that status and farming data then it appears that my og plot farming is stopped and wallet sync is also out of order or stopped totally.

I tested it by not opening OG wallet key for 24 hours and when I click on it to view its progress then their was a huge gap between the blockchain and wallet sync like 1000 or more and it seems that it also stopped farming / mining with og plots.

Their should be threading or some process which sync both or many keys or allow us to stop syncing on one key or allow it depending on the available resources.

**Comment by loppefaaret** [comment]
At the moment, you can only have 1 wallet "active" at a time.
The wallet status is irrelevant when it comes to farming OG old plots.
When it comes to new portable plots pointing at a ploNFT, the wallet has to be synced passed the last transaction that modified the plotNFT (pool / self farming).
If the above requirement is met, the wallet process has no effect on successfully farming.
So in essence, this is an enhancement issue, and we already have it planned as an future upgrade here:
https://trello.com/c/T1OrNzU7

**Comment by Motophan** [comment]
is there a cli command to make a wallet active?

**Comment by Motophan** [comment]
oh that's brilliant.

can we put that in the docs?
I'll close if I need to make a new issue.
