### ISSUE TITLE
[BUG]12p power hasn't been blocked for 4 days in a row, version 1.1.7

### ISSUE THREAD

**Issue by wanming851** [Chia-Network/chia-blockchain#8031]
12p power hasn't been blocked for 4 days in a row, version 1.1.7

**Comment by loppefaaret** [comment]
as i understand this issue, you are complaining about your luck with 12 PB of plots, not winning the last 4 days ?
we have our discussions here:
https://github.com/Chia-Network/chia-blockchain/discussions
feel free to take it over there, unless you can actually point at anything
