### ISSUE TITLE
[BUG] Farming with 6.7TB for some time without a win

### ISSUE THREAD

**Issue by krispipeleers** [Chia-Network/chia-blockchain#804]
Farming with 6.7TB for some time, app is estimating a win every 3 hours. Running it for 4 days without a win. How can I test this?

**Comment by hoffmang9** [comment]
There are known sync issues in 23 that should get better in 24

**Comment by hoffmang9** [comment]
Should be fixed in https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0beta26
