### ISSUE TITLE
 I haven't been rewarded for 11 days

### ISSUE THREAD

**Issue by tracy32792** [Chia-Network/chia-blockchain#8069]
I have 17000 OG plots ，It has been abnormal since 1 month ago。

My network, computer system and Chia farming interface display are all farming, and the log display does not exceed 5 seconds。

**Comment by rckjhn** [comment]
Same here 15000 OG plots last reward 24 days ago. chia version 1.2.1.  Ran usual diagnostics and logs look normal.
Any ideas?

**Comment by LYXQQ** [comment]
I have 8000 OG plots and 5000 NFTs，received 2 XCH after more than 30 days with ETW 5 days，since 1.2.0.

**Comment by lumiamax** [comment]
22200 OG plsts,received xch half month ago,and there is lots of my friends （at least 2piB） didn't get coins more than 15days,so wahts going on there?

**Comment by rckjhn** [comment]
Collectively that's about 50k plots so ETW is about a day. This is good evidence for some sort of bug.
