### ISSUE TITLE
Wallet Fails To Sync Until Restart

### ISSUE THREAD

**Issue by WookieHouse** [Chia-Network/chia-blockchain#8090]
**Describe the bug**

Wallet Fails To Sync Until Restart - Any Credits are not shown to the account since last restart

**To Reproduce**

Start Chia
Add 12 queues with 29 plots per queue
Note current chia balance in wallet
After being notified of a credit to wallet by pool, check chia wallet transactions and balance

**Expected behavior**
Pool credit should show in wallet, both the transaction and correct balance

**Desktop**

- OS: Windows 
- OS Version/10, fully up to date
- CPU: Ryzen 5900X

**Additional context**
Reboot the machine and restart chia, credits are shown in wallet and balance is correct.

Running latest Chia Version.

**Comment by loppefaaret** [comment]
This might just be that you are overloading the CPU with plotting, not ahving enough CPU free for the regular chia processes when they need them ? do you see the same behavior if you make sure not to overload the CPU as much ?
