### ISSUE TITLE
Chia does not sync

### ISSUE THREAD

**Issue by nahuelnahuelnahuel** [Chia-Network/chia-blockchain#8095]
I had an error in a ploot disk and chia stopped synchronizing enter my keywords but it stopped working it does not synchronize neither the walet nor the ploots

**Comment by nqk968** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/8095#issue-972142854

**Comment by shaneo257** [comment]
have you followed the steps outlined here
https://github.com/Chia-Network/chia-blockchain/wiki/Resolving-Sync-Issues---Port-8444
