### ISSUE TITLE
[BUG] Log does not indicate which harvester is responding late

### ISSUE THREAD

**Issue by jayhohoho2019** [Chia-Network/chia-blockchain#8097]
**Describe the bug**
2021-08-16T08:50:11.180 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-08-16T19:59:39.386 farmer chia.farmer.farmer         : WARNING  Respond plots came too late

Lines from farmer node's debug.log.  No idea which harvester it is, or which respond plots they are.

**To Reproduce**

1. Go to: tail ~/.chia/mainnet/log/debug.log

**Expected behavior**
Maybe provide the harvester IP and the plot file path/name?

**Screenshots**

**Desktop**

- OS: Ubuntu Server 20.04.02 LTS
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by Jacek-ghub** [comment]
I would like to second @jayhohoho2019 request.  Also, as it is marked as enhancement, I would suggest that the UI group will add Harvester info blocks (similar to Plot info blocks) that would be a placeholder for info like that (e.g., how many times in the last 24 hours a given harvester was late, etc.)

It is kind of a nuisance to fish through those logs for what can be easily displayed in the UI.

**Comment by jayhohoho2019** [comment]
Here is another one I've noticed.  In addition to showing harvester ID, what does this error message mean? Is this harvester low on memory? 
2021-08-15T12:37:39.509 harvester chia.harvester.harvester: ERROR    Error using prover object Destination buffer is too small
