### ISSUE TITLE
[BUG] Farm summary does not show last height farmed when using a different wallet for xch_target_address

### ISSUE THREAD

**Issue by gryan315** [Chia-Network/chia-blockchain#8103]
**Describe the bug**
When using a separate wallet/cold wallet as the xch_target_address in the config.yaml, the farmer does not seem to recognize that a block was won other than the log entry for the farmer creating the unfinished block.

**To Reproduce**

1. Set xch_target_address to a wallet from a different private key
2. Win a block
3. `chia farm summary` will not update "total chia farmed" or "last height farmed."

**Expected behavior**
At a minimum, the "Last height farmed" should be detected by the farmer and updated. It would be nice to also have the "Total chia farmed" update as well, but I could see why that might not update due to the payout going elsewhere.

**Desktop**

- OS: Ubuntu 20.04, Linux 5.4 LTS
- CPU: Xeon E5 1620

**Comment by cryptosven76** [comment]
i see the same issue
