### ISSUE TITLE
Add tests for harvesters similar to chia plot check

### ISSUE THREAD

**Issue by rckjhn** [Chia-Network/chia-blockchain#8115]
Chia plot check will check an individual plot:

```
2021-08-15T00:54:36.514  chia.plotting.check_plots        : INFO     	Pool public key: <...>
2021-08-15T00:54:36.528  chia.plotting.check_plots        : INFO     	Farmer public key: <...>
2021-08-15T00:54:36.528  chia.plotting.check_plots        : INFO     	Local sk: <...>
2021-08-15T00:54:43.568  chia.plotting.check_plots        : INFO     	Proofs 29 / 30, 0.9667
```

So clearly it is possible to send challenges on the plot level and expect proofs to be found.
Is it not possible to send a challenge to a harvester that is expected to produce a proof and see that it actually finds it?
"chia harvester check". This check would be a level up in the sense it would check the plots collectively and would likely have to be tagged as a test challenge so there is no economic effect.

For the smaller farmer with longer ETW there is considerable anxiety around "is my farm working" or "am I just being unlucky". This test would answer "is my harvester working at least as well as my plots" and would provide significant peace of mind to many farmers.

**Comment by Jacek-ghub** [comment]
I would also like to see in the logs (or better, in the UI) which plot generated proofs/partials.  

I see a lot of value having the farm issued challenges, but my take is that the ultimate challenge is to see which disks are "preferred" in getting those partials, when plots belong to some pool (whether a self pool or a third party pool).  It should be fairly easy to create a heatmaps app that would highlight harvesters/drives that are the most active.
