### ISSUE TITLE
[BUG]Missing XCH Coins from Chia.

### ISSUE THREAD

**Issue by Wutchira** [Chia-Network/chia-blockchain#8116]
**Describe the bug**

> In the morning of 18 August 2021, I woke up and checked Chia as usual but found that 4.242002068422 coins were missing. At first, there was no trace of outgoing transfer but after my thorough examination, I learnt that the coins were transferred to the mysterious wallet address unknown to me. (I searched with https://xchscan.com/) Now, I still do not know whether the missing coins were erroneously transferred to that wallet address due to the bug or theft.>

**Questions:**

- Is there any possible way to solve this problem / get my coins back?
- Is there any possible way that I can follow-up this particular issue?

**Desktop**
- OS: Windows 10 Pro
- OS Version: 21H1
- CPU: Intel Xeon E5-2658 v3 (2 processors) Ram 64GB

**Comment by htcll411** [comment]
me too

**Comment by keliew** [comment]
Using unofficial software and poor security practise may result in theft.

It's not possible to recall those transactions...

**Comment by shaneo257** [comment]
please follow this blog post to help secure your future rewards
https://www.chia.net/2021/05/28/securing-your-chia-how-to-be-a-hard-target.en.html

**Comment by diederikus** [comment]
i am missing some xch too.

**Comment by Wutchira** [comment]
@keliew I understood for your mean.  But I still wonder why that coins in wallet address do not transferring for sale or convertible coins (Common sense)

**Comment by keliew** [comment]
> @keliew I understood for your mean. But I still wonder why that coins in wallet address do not transferring for sale or convertible coins (Common sense)

Yeah, I think he should just give it to me. :D

**Comment by isipisi281** [comment]
just farm your coins in a new wallet. simple. your coins are gon byby arividerschti

**Comment by Wutchira** [comment]
@shaneo257 You mean let me stop figuring out how to recall the coins. then create a new seed?

**Comment by Wutchira** [comment]
@diederikus Where are you live. The you coins how many is missing. What do you have solve of issue.

**Comment by Wutchira** [comment]
@shaneo257  I assumed that is maybe program bug. Because the coins remains in it no movement in wallet. By common sense if theft must has outgoing transfer. Now the number of victims found is increasing day by day. (last total 26XCH)

**Comment by hoffmang9** [comment]
How many forks and which ones were you also farming - if any? Did you use your 24 words with any software or service that was not the official Chia software?

**Comment by Wutchira** [comment]
@hoffmang9 I just joined the Space Pool last month. Also never used 24 words with anything else. Now, The coin is stuck in wallet address:xch1x8yswru2ahlzce40pcuuga3yurhadg8l5elwr7uvf5rnanzea52qv09dks

**Comment by diederikus** [comment]
> @Wutchira  i live in netherlands i'm only missing a very small amount, somewhere in the range of 0.000035  mojos

**Comment by Wutchira** [comment]
@diederikus Even a small should not be missing. If the issue is not from user side. Mr.Bram Cohen and Chia team he should be open official contact for solve.

**Comment by keliew** [comment]
so because your wallet is not synced, you lost your coins...
why not keep it in synced?

**Comment by Wutchira** [comment]
@keliew At first my wallet was fully synced. But later I found that coins was missing. So I try to recover my coins by method deleting folder wallet on Mainnet folder. (Some detail had already told @Mrhoffmanh9)

**Comment by Wutchira** [comment]
This is details that my coins are missing. Do you see anything wrong with pic?
<img width="1432" alt="Screen Shot 2564-08-20 at 20 06 22" src="https://user-images.githubusercontent.com/89126576/130238537-149c8a49-9ca1-447c-9853-fceffbb4b841.png">

**Comment by keliew** [comment]
Am not exactly sure, because there's no (public) identification on each wallet address...

Are you sure you aren't confused by the UTXO coin model? https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-coin-model

**Comment by Wutchira** [comment]
@keliew Yes, I'm sure aren't confused.
