### ISSUE TITLE
Ubuntu 21.04 sh install.sh wont install

### ISSUE THREAD

**Issue by Mladja99** [Chia-Network/chia-blockchain#8135]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8127

<div type='discussions-op-text'>

<sup>Originally posted by **Mladja99** August 19, 2021</sup>
I cant install chia blockchain on my PC. When i run sh install.sh i get this (info on screenshot)
![error](https://user-images.githubusercontent.com/26867461/130091767-b65b1bb3-b272-4e89-bb77-4b012b3639d7.png)
Can someone help with installing it ?</div>

**Comment by geoffwalmsley** [comment]
Did you try removing the libvllvm11 package with `sudo apt autoremove`, and then try running the install script again?

**Comment by Mladja99** [comment]
> Did you try removing the libvllvm11 package with `sudo apt autoremove`, and then try running the install script again?

I did try it, but it doesn't delete anything and still same. Looks like its forcing python 3.8 but i have python 3.9. Maybe there is a problem, cause script updates 3.9 python but forces 3.8.

**Comment by hoffmang9** [comment]
I can confirm this issue on 21.04. I had to create the 3.9 venv by hand and then run `sh install.sh` in there.

It has something to do with @richardkiss 's python finding logic running into something odd on 21.04 here - https://github.com/Chia-Network/chia-blockchain/blob/main/install.sh#L82

Someone should make sure that only python 3.9 is installed on 21.04 as that could be the underlying challenge
