### ISSUE TITLE
[BUG] Missing 1.75 chia.

### ISSUE THREAD

**Issue by kingaPadavan** [Chia-Network/chia-blockchain#8141]
Today 08/20/2021, 01:51:57 I received 0.25 chia at an altitude of 739514. 
![transaction](https://user-images.githubusercontent.com/89276838/130287465-f42b48d4-d9c5-477e-bff2-ae62061b7990.png)
As I understand it, my plots were found 1 block of chia. But in that case, I haven't received another 1.75 chia. I am not a member of the pool (but i was on hpool 2 months ago, and i was banned for double mining). I have old plots. My GUI of Chia blockchain client is on 1.2.3 version.
My farmer adress - xch1t6fcdcf3vc9x2lvjnypv7zu5lgxdhwxzdcqwtngd6chs5r32fgkq562at8. 
![my wallet](https://user-images.githubusercontent.com/89276838/130287464-8a0c5f11-8b26-4b6c-8a06-3f9c23be5195.png)
But looking at the information on block 739514 I see that the farmer adress is not mine (xch1xd5j2rknaspu2lda3472q464vp6aseadw2dt9e6quqa0fwrnex6q4k2yvk). 
![wrong wallet of block](https://user-images.githubusercontent.com/89276838/130287470-b7c8558f-cabd-4cf6-91d0-808d57293413.png)
But in the information about all blocks of this foreign address block 739514 is missing. 
![wrong farmers trnsactions](https://user-images.githubusercontent.com/89276838/130287468-88d511c9-56d5-4d20-95b8-10733cf12452.png)
At the same time, the information about my farmer adress contains this information, but only about 0.25 chia. 
![my transactions](https://user-images.githubusercontent.com/89276838/130287461-b4946cad-8fa4-43b3-8d1b-790b4de2df73.png)
![log](https://user-images.githubusercontent.com/89276838/130287458-afe1a5e0-b5f6-45d8-95f6-e18812b5cb41.png)
How it possible? Where can I find my 1.75 chia?

**Comment by emlowe** [comment]
xchscan tells you that for this block there were 4 rewards, but doesn't let you look at them. However chiaexplorer does in fact.

So for this block there was a farmer reward sent to `xch1t6fcdcf3vc9x2lvjnypv7zu5lgxdhwxzdcqwtngd6chs5r32fgkq562at8` and the pool reward for that was sent to `xch1c7mwvl9rq2hh65mpfyupegsuup37zj3uu6r63r9qh3ph8qmx0cms4qyxuf`
![Screen Shot 2021-08-20 at 1 27 57 PM](https://user-images.githubusercontent.com/30607889/130290163-3d4cddd1-0602-41e4-94a7-a4565d0ed64a.png)

**Comment by kingaPadavan** [comment]
That is, the award was divided into several different people? I didn't know what was happening. It is not bug?

**Comment by emlowe** [comment]
Are you on OG plots or PoolNFT plots?

**Comment by kingaPadavan** [comment]
> Are you on OG plots or PoolNFT plots?

OG

**Comment by emlowe** [comment]
Check your plots - the 1.75 will go to the pool address that was specified if you used "-p" when you created the plot. `chia plots check` should tell you the pool address if one is set on the plots.

**Comment by emlowe** [comment]
By design rewards are split into two - farmer rewards 0.25 and pool rewards 1.75. When solo OG farming, typically both rewards go to the same address. However, they don't have to - as seen

**Comment by kingaPadavan** [comment]
> Check your plots - the 1.75 will go to the pool address that was specified if you used "-p" when you created the plot. `chia plots check` should tell you the pool address if one is set on the plots.

All my plots were created on may 2021. I didn't used "-p" when created the plots.

**Comment by kingaPadavan** [comment]
> However, they don't have to - as seen

It's very sad if so

**Comment by emlowe** [comment]
Did you check with `chia plots check`? Did you make these plots yourself? What software did you use? The pool rewards didn't just go to that other address by accident.

My recommendation since you were with hpool is to create new keys and replot and make your farmer key is set correctly and leave the pool key blank - or switch to NFT plots.

**Comment by kingaPadavan** [comment]
> Did you check with `chia plots check`?

pool key and farmer key are differents.


> Did you make these plots yourself?

yes



> What software did you use?

only GUI Chai Blockchain

**Comment by emlowe** [comment]
There you go, your plots have a pool key set - so the 1.75 is always going to go to that pool key every time you win a block. Perhaps you have some old keys that you used to use? Maybe you have an old wallet for that pool key (or 24 words)

You will need to replot if that pool key doesn't belong to you or you no longer have access to that wallet. 

Do not set the pool key when you plot - or make sure it's the same as your farmer key. But I think it's easiest to just leave it off. Since you will need to replot, I might recommend using the plotting using the new PoolNFT. This will let you self-pool as well as join an official pool protocol pool at any time.

**Comment by kingaPadavan** [comment]
> There you go, your plots have a pool key set - so the 1.75 is always going to go to that pool key every time you win a block. Perhaps you have some old keys that you used to use? Maybe you have an old wallet for that pool key (or 24 words)
> 
> You will need to replot if that pool key doesn't belong to you or you no longer have access to that wallet.


I understand it. But how is this possible? I've already got 2 chia on the same plots. I have not reworked them. I don't have any other wallets or keys, just this one. Apparently the chia network still has vulnerabilities.


> But I think it's easiest to just leave it off. Since you will need to replot, I might recommend using the plotting using the new PoolNFT. This will let you self-pool as well as join an official pool protocol pool at any time.

Of course, after what happened, I will redo my plots.
In any case, thanks for the clarification and dialogue.

**Comment by emlowe** [comment]
This isn't a vulnerability - your plot was created with that pool key - so things are working as designed. The 1.75 goes to the pool key and the 0.25 to the farmer key. Seems to me like it's all working as expected.

The only way a plot can get created with the pool key is if it was created as such from the beginning. The pool key cannot be changed on a plot after creation.
