### ISSUE TITLE
[Enhancement] - Support for 2-factor wallet

### ISSUE THREAD

**Issue by atrinpc** [Chia-Network/chia-blockchain#8156]
With respect

We had almost all the old wallets in Hpool and the early pools ...

And we gave them our private key

And now we need two-step approval to maintain our assets !!!

This confirmation is absolutely necessary both for entering the wallet and for transferring Chia currency

Please consider this option in the new version

Thanks to Chia's powerful team

**Comment by markusmazurczak** [comment]
Can you please describe what feature you are seeking for. Giving someone your private key is, at least in my opinion, something nobody should every do. Never.

**Comment by emlowe** [comment]
Once someone else has your private key, there is no 2-factor solution that would help.
Your only solution is to generate a new key/wallet, move any XCH you have to this new wallet and forget about your old one.

Marking enhancement for a 2-factor wallet

**Comment by keliew** [comment]
why not just create a new wallet?

**Comment by Jacek-ghub** [comment]
> @keliew 
> why not just create a new wallet?

I don't think that you answered the primary question.  Of course, once you know that your keys are leaked (to HPool,, Flax, etc.) you know that you need to abandon those old keys/plots.  So that is obvious.  As there were no design provision for additional level authentication, that is the only option for all those people that "trusted" those third party services.

However, virtually everything has kind of 2-factor authentication, if not enforced than optional.  Just look at SSH, you can just use the private key (and be screwed when it is leaked), but you can also add password to that key (and be semi-screwed, but at least you _may_ have some extra time to recover).  That is what is needed for Chia (optional password).

The fact that there is no similar design provision for forks like Flax, Goji as for joining pools needs to be addressed, as those forks are not going away, and possibly not harming the ecosystem (where HPool was from the beginning dubious).

**Comment by keliew** [comment]
If you follow the PRs and Trello, you'd notice that it has already been in development. So...what's your point?

**Comment by Jacek-ghub** [comment]
Two points.  First, I don't need to follow PRs and Trello, and same applies to majority of people.  The second, and more important, if that is the case (is already in development), then @emlowe should reply like that and close this case.  As he is not doing his job, we all waste our time here.  Instead of that he was just trying to talk from the high horse, and further convolute this thread.

**Comment by emlowe** [comment]
Putting a passphrase on your SSH private key **after someone already has your SSH private key** doesn't do anything.

Yes, anyone with your private key can transfer all your XCH - adding confirmation to the UI does nothing for this. The horse is out of the barn, it's too late. This is not fixable with any amount of additional technology.

**Comment by Jacek-ghub** [comment]
> @emlowe 
> Putting a passphrase on your SSH private key **after someone already has your SSH private key** doesn't do anything.
> 

Why do you continue to muddy the water?  No one was talking about adding the passphrase "**after someone already has your SSH private key**"

The point is that the current design can do nothing in case private keys are leaked, period.  Therefore, it is obvious that people need create new keys.  

We are talking about the new design that will have that passphrase built in from the start, but will require new keys to be generated to make it work (well, yes replot will be in order).

It just looks like Chia team rushed a rather immature product out, and is putting the blame right now on everyone else for not following things that should not be required in the first place.

**Comment by emlowe** [comment]
I am answering OP's question "_Does it make sense that anyone who has my private key (seed) can easily transfer all my inventory ???_"

Yes, that's how it works.

**Comment by Jacek-ghub** [comment]
Well, then you answer is rather wishy washy.  You are just putting some hopes that maybe, just maybe there will be an option to do something about that.  This is the exact reason we have this long worthless exchanges here.

Also, you will need to repeat that BS for everyone that is doing Goji, Flax, etc., now, as again you rushed the product, and there is no provision to make it work properly.

Just answering OP honestly that for time being everyone is SOL, and giving us some ETA when you will have a real solution would be much more appreciated.

You need to own your design mistakes, and be honest about the road forward.  We are all here looking for the best for the Chia ecosystem.

**Comment by keliew** [comment]
If forks can provide true value, they would have provided PRs...

Going around in circles about design fault and timeline operations is really futile. Neither you nor I are in the position to deeply criticise about an organisation that we aren't in. We are passer-bys.

That said, I don't think the Chia team is ignoring the good suggestions. The development of Chia _is_ changing at a rapid pace. I doubt anyone can deny that. I think that some people are just frustrated about the silence, which again, isn't wrong either from an enterprise perspective.

Even Tesla don't need to give you an answer about their design faults; they just sell you more dogecoin with a rocket to the moon. And am glad Chia isn't doing that.

**Comment by Jacek-ghub** [comment]
I agree with you.  And, as I stated above, when you mentioned that Chia team is working on improving those private keys behavior, that should be the first answer from @emlowe.  Just telling the guy that he screwed up and dwelling on that is not really helping him (or anyone else), as he knows it by now.

Also, as we agreed in the other thread, some improvements seems like just a coffee break (e.g., showing harvesters ratios, their health (even on/off), even a notification in the UI that a new version is out, or that a given harvester is running old version).  

Maybe it would be helpful to have a list of issues/enhancements with priorities that Chia team put on those, so we would not need to regurgitate those issues every other day.

**Comment by atrinpc** [comment]
It is clear that no one understands my language

**Comment by markusmazurczak** [comment]
Dear people, you really need to reach the next level in your discussion culture and critical faculties. It's really scary to see how the community is tearing itself apart here and everyone always feels directly attacked.

Leave your ego at home for a second and try to make things better by clever discussions and taking other points of view.
