### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TeodorRage** [Chia-Network/chia-blockchain#8157]
Hi, I have the following problem, I will be in sol, I passed the filter, I found the proof, but I did not receive the block reward, please help! I attach an extract from the log
2021-08-21T07: 59: 20.973 harvester chia.harvester.harvester: INFO 1 plots were eligible for farming e41bdb76d3 ... Found 1 proofs. Time: 0.76800 s. Total 67 plots
2021-08-21T07: 59: 20.979 full_node chia.full_node.full_node: INFO Block validation time: 0.6210017204284668, cost: None

**Comment by markusmazurczak** [comment]
Are you participating in a pool or solo mining?

**Comment by TeodorRage** [comment]
> Are you participating in a pool or solo mining?

Solo mining

**Comment by emlowe** [comment]
For solo farming, please keep in mind that finding a proof does not constitute to winning a plot (getting a payout). Even if you find a proof, it needs to compete with other proofs and win to actually receive a reward.
Generally the fastest response wins - what this means is that somone else found the proof and got it out on the network before you did
