### ISSUE TITLE
Missing 1 XCH in cold storage address by checking chiaexplorer.com

### ISSUE THREAD

**Issue by chenus1** [Chia-Network/chia-blockchain#8161]
Describe the bug

In the morning of 22 August 2021, I just checked the https://www.chiaexplorer.com/  for my cold storage address and find that 1 xch was spent and missing (see the snapshot of screen) and it is not show in the net balance. I did transfer this XCH on August 19, 2021 from my farmer address to this cold storage address.  My screen also shows that threat secured and we have successfully aborted connection tcp://125.68.143.131:8444
![image](https://user-images.githubusercontent.com/45975235/130358393-d6068c94-c985-4fe3-889b-2a614eb669ab.png)
![image](https://user-images.githubusercontent.com/45975235/130358464-7bc66e37-46c6-46eb-b828-0cd7eae6e194.png)

here is the snapshot of the coin 

![image](https://user-images.githubusercontent.com/45975235/130358580-a0088552-b935-4c88-9c39-1a68a242e9a3.png)
I traced that spend block index is 734446, which is linked to some pool address as below

![image](https://user-images.githubusercontent.com/45975235/130358701-13977319-73cf-41d4-bef0-b921f6864036.png)

Questions:

Is there any possible way to solve this problem / get my coins back?

Desktop

OS: Windows 8.1 Pro

CPU: AMD FX 8150 Ram 16GB

**Comment by loppefaaret** [comment]
`xch16dh6v6kg0t7d36gkkwmcxeqtaf77yagy7w828mugrkh8vjha8ujq8q4fqn`
First off, the fact that an outgoing transaction has taken place, this is _no longer a cold wallet_!
If you are 100% sure that you have not created a transaction from this wallet, *imidiately* transfer the balance out of the wallet!

**Comment by loppefaaret** [comment]
https://xchscan.com/address/xch16dh6v6kg0t7d36gkkwmcxeqtaf77yagy7w828mugrkh8vjha8ujq8q4fqn
This shows a initial 0.01 XCH going in 3~ months ago, and then activity in the last week...
are you absolutely sure that you have not by mistake imported this key on an online client, and started syncing the wallet ?
perhaps even mistakenly created the transaction itself ? it has taken the 1.00 XCH and split it into 0.01 & 0.989 as you can see on the above link
the 0.01 went to https://xchscan.com/address/xch1rg97f3dvk7wjlsjdcvrtxujv606swa42hpplfwlakuhqfaz0j4fs5x2p8y which is a very active address, and the 0.989 went to a unique address, which might be belonging to your "not so cold wallet any more" ?

**Comment by loppefaaret** [comment]
https://xchscan.com/address/xch1rg97f3dvk7wjlsjdcvrtxujv606swa42hpplfwlakuhqfaz0j4fs5x2p8y is also the same address that initially seeded the "not so cold wallet address" 3 months ago i see now. 
i guess you synced the "not so cold wallet" and sent back the 0.01 XCH from where it came ?
