### ISSUE TITLE
[BUG]Last Attempted Proof stop updating every few hours

### ISSUE THREAD

**Issue by michaelyu16** [Chia-Network/chia-blockchain#8167]
**Describe the bug**
Please see the image, every few hours "last attempted proof " stopped, then the pool can't detect my plots.
Anyone can help me? 
Thank you so much!
<img width="460" alt="111" src="https://user-images.githubusercontent.com/84205362/130393000-e58d887c-8fee-4c3f-980f-b65bca8c5ba4.png">

**Comment by loppefaaret** [comment]
It is possible that the "Full Node" tab is showing that is has lost sync ? 
You might be able to gather more information on the issue by taking a look in the `debug.log` file located under your user folder, in `~\.chia\mainnet\log\`

**Comment by michaelyu16** [comment]
Great Thank you so much!

loppefaaret ***@***.***>于2021年8月23日 周一上午9:48写道：

**Comment by Drakanus** [comment]
Same situation over here

**Comment by berlef80** [comment]
same here - if the node has lost connection what is the fix?
