### ISSUE TITLE
[BUG]stopped syncing 

### ISSUE THREAD

**Issue by hhenrry501** [Chia-Network/chia-blockchain#8171]
I got this on WIN 10 GUI debug log. it just stopped syncing and all infos are just circling.

\node_discovery.py:701> exception=AttributeError("'WalletPeers' object has no attribute 'connection'")>
Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 704, in ensure_is_closed
  File "chia\server\node_discovery.py", line 118, in _close_common
AttributeError: 'WalletPeers' object has no attribute 'connection'
2021-08-23T21:23:55.808 harvester chia.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-08-23T21:24:24.548 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-18' coro=<WalletPeers.ensure_is_closed() done, defined at chia\server\node_discovery.py:701> exception=AttributeError("'WalletPeers' object has no attribute 'connection'")>
Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 704, in ensure_is_closed
  File "chia\server\node_discovery.py", line 118, in _close_common
AttributeError: 'WalletPeers' object has no attribute 'connection'

**Comment by loppefaaret** [comment]
It could be a sign of a corrupted blockchain database, if the chia app is able to open up, but has a couple of spinning circles under the "Full Node" tab, but that would also leave other ERROR or WARNING from the "full_node" in the `debug.log` file.
You might have a corrupted wallet database, which would possibly prevent the chia app for opening up, and leave you with a spinning circle and a "Connecting to wallet..." message ?
The errors you are listing here are possible to have had happened during starting up, or closing down the app
and if you also could mentioned which OS you are on, that may make further help easier to provide

**Comment by hhenrry501** [comment]
> It could be a sign of a corrupted blockchain database, if the chia app is able to open up, but has a couple of spinning circles under the "Full Node" tab, but that would also leave other ERROR or WARNING from the "full_node" in the `debug.log` file.
> You might have a corrupted wallet database, which would possibly prevent the chia app for opening up, and leave you with a spinning circle and a "Connecting to wallet..." message ?
> The errors you are listing here are possible to have had happened during starting up, or closing down the app
> and if you also could mentioned which OS you are on, that may make further help easier to provide

I am using Windows 10. 
![微信截图_20210824105336](https://user-images.githubusercontent.com/83000063/130548364-c9a8a1cb-4a85-4e7a-b633-ecf8b3092189.png)

**Comment by loppefaaret** [comment]
that is almost guaranteed a corrupted blockchain database, and you need to remove it, and resync from 0:
WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!

**Comment by hhenrry501** [comment]
I think it worked. sorry for the late reply. 
Thank you!
