### ISSUE TITLE
Chia coins are gone((((

### ISSUE THREAD

**Issue by ANDRIY19861210** [Chia-Network/chia-blockchain#8189]
Yesterday I opened the Chia Blockchain and discovered that my 0.6 Chia coins had disappeared. The balance as of today is 0.02 Chia. There is no information about the original transactions in the transaction list. The wallet is synchronized. At the same time property on hpool. If this is a program error, how can I fix it? If it is a theft, how to confirm it?

**Comment by ANDRIY19861210** [comment]
From this purse was stolen my 0,56 chia coin - xch1knw4wjy64yv9ghjh9l2ahe83eldxg4a06x75dzwwem47qrkpj9vs2qe8cq.

**Comment by loppefaaret** [comment]
if another machine is used to do outgoing transactions, they will not be listed in the transactions list of other clients.
if you did not yourself make an outgoing transaction, im afraid someone else has gotten hold of your 24 word mnemonic key, and is transferring the funds out of the wallet!
either someone has tricked you into revealing it, or perhaps you have run 3rd party software that has stolen the key.
i would recommend that you create a new wallet / 24 word mnemonic, and transfer any remaining funds out to the new wallet.
try and identify how anyone else might have gotten a hold of your 24 words.
if you are unable to identify the method, i can only recommend a full OS reinstall.
