### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by fantasylincen** [Chia-Network/chia-blockchain#8220]
界面太简单， 我希望在下个版本里面有更详细的设置和提示信息，以及更详尽的数据可供查阅界面太简单， 我希望在下个版本里面有更详细的设置和提示信息，以及更详尽的数据可供查阅

The interface is too simple. I hope there will be more detailed settings and prompts in the next version, as well as more detailed data for reference

**Comment by hoffmang9** [comment]
We intend to make the GUI simpler and simpler. For complexity, please use the CLI, RPCs, and code.
