### ISSUE TITLE
Never got my .25 reward for finding block

### ISSUE THREAD

**Issue by serg3140** [Chia-Network/chia-blockchain#8233]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8218

<div type='discussions-op-text'>

<sup>Originally posted by **EVILTIM58** August 26, 2021</sup>
I found a block..   i was supposed to get .25 chia "automatically from the blockchain, but I did not.

![image](https://user-images.githubusercontent.com/89432385/130974892-000904bc-ea90-4ffc-af75-c62734c18c86.png)

![image](https://user-images.githubusercontent.com/89432385/130974956-5b9c9b83-a6b5-4111-a6bb-4c16a39695d1.png)

![image](https://user-images.githubusercontent.com/89432385/130975087-c3214cfd-08d1-42b4-87d0-cfe15496a3ee.png)

Ideas?</div>

**Comment by hejz0r** [comment]
> ### Discussed in #8218
> Originally posted by **EVILTIM58** August 26, 2021
> I found a block.. i was supposed to get .25 chia "automatically from the blockchain, but I did not.
> 
> ![image](https://user-images.githubusercontent.com/89432385/130974892-000904bc-ea90-4ffc-af75-c62734c18c86.png)
> 
> ![image](https://user-images.githubusercontent.com/89432385/130974956-5b9c9b83-a6b5-4111-a6bb-4c16a39695d1.png)
> 
> ![image](https://user-images.githubusercontent.com/89432385/130975087-c3214cfd-08d1-42b4-87d0-cfe15496a3ee.png)
> 
> Ideas?

@serg3140 : check your config.yaml ... i lost 2 XCH, because config.yaml is not updating xch wallet addres, you must enter address manually

**Comment by EVILTIM58** [comment]
What address should be in there?

**Comment by loppefaaret** [comment]
_any_ receive address from a wallet you control - you can go to the wallet tab, copy the receive address, and input that

**Comment by serg3140** [comment]
> @ serg3140 : проверьте свой config.yaml ... я потерял 2 XCH, потому что config.yaml не обновляет адреса кошелька xch из графического интерфейса, вы должны ввести адрес вручную в config.yaml

  start_rpc_server: true
  xch_target_address: xch1jkjxz23uywcqzvjeuwdxpr654djc6jsg5lzry54x9kzvjd872frqeqfrpj
the file contains the working address of the wallet.
0.25 coins were sent to this address.
Do I need to change it to a different address?

**Comment by hejz0r** [comment]
@serg3140 is it your address?

https://www.chiaexplorer.com/blockchain/address/xch1jkjxz23uywcqzvjeuwdxpr654djc6jsg5lzry54x9kzvjd872frqeqfrpj

**Comment by EVILTIM58** [comment]
ok I updated my config.yaml to show my new address... is that first reward just lost at this point?

**Comment by serg3140** [comment]
> @ serg3140 это твой адрес?
> 
> https://www.chiaexplorer.com/blockchain/address/xch1jkjxz23uywcqzvjeuwdxpr654djc6jsg5lzry54x9kzvjd872frqeqfrpj

yes my

**Comment by loppefaaret** [comment]
@serg3140 first, make sure your wallet is synced - if so, and it is missing transactions, please try and move the current wallet database out, and resync it - there is a small possibility that the wallet missed the transaction
shut down chia, move the `~/.chia/mainnet/wallet/db/block*` file to your desktop or somewhere else, and start chia again, and let the wallet do a full resync

**Comment by serg3140** [comment]
> @serg3140 first, make sure your wallet is synced - if so, and it is missing transactions, please try and move the current wallet database out, and resync it - there is a small possibility that the wallet missed the transaction
> shut down chia, move the `~/.chia/mainnet/wallet/db/block*` file to your desktop or somewhere else, and start chia again, and let the wallet do a full resync

ok, I'll try

**Comment by serg3140** [comment]
> @serg3140 first, make sure your wallet is synced - if so, and it is missing transactions, please try and move the current wallet database out, and resync it - there is a small possibility that the wallet missed the transaction
> shut down chia, move the `~/.chia/mainnet/wallet/db/block*` file to your desktop or somewhere else, and start chia again, and let the wallet do a full resync

the wallet started syncing, reached block 788 345 and stopped syncing ...

**Comment by loppefaaret** [comment]
im not sure your are on the correct wallet, it is not any wallet on the farming machine, as clearly shown here:
![image](https://user-images.githubusercontent.com/32275244/131506223-b4c4701d-a232-47c9-9d0e-c51e04c592e1.png)
if you do not have a secondary key/wallet on some other machine, or cold wallet that this address belogns to, the 0.25 reward is lost.
to fix this, take a receive address from any wallet that you do control, and input it into both of the above boxes, and save

**Comment by serg3140** [comment]
> Я не уверен, что у вас правильный кошелек, это не какой-либо кошелек на сельскохозяйственной машине, как ясно показано здесь: если у вас нет вторичного ключа / кошелька на какой-то другой машине или холодного кошелька, к которому этот адрес относится, 0,25 награды потеряны. чтобы исправить это, возьмите адрес получения из любого кошелька, которым вы управляете, введите его в оба поля выше и сохраните
> ![изображение](https://user-images.githubusercontent.com/32275244/131506223-b4c4701d-a232-47c9-9d0e-c51e04c592e1.png)

what does it mean, not the right wallet? I downloaded it from the official site.
If it has problems, help me to solve them :)

**Comment by serg3140** [comment]
![image](https://user-images.githubusercontent.com/37830229/131544544-d9c0b63c-4f1e-4db0-a9a8-4ec1e5fa7059.png)

**Comment by loppefaaret** [comment]
It means your addresses in Farmer / pool reward address is belonging to a key that you do not have imported!
go to your "Wallet" tab, copy the receive address, and overwrite the "Farmer / Pool Reward Addresses"
if you have done it correctly, the above message will go away!

**Comment by serg3140** [comment]
Where can I get a secondary key? Where is it stored? and how to use it to get back 0.25 chia?
Write to serg3140@gmail.com please

**Comment by loppefaaret** [comment]
did you ever remove any keys from the client ? it could be that you delete the original first key that you used, and the 0.25 is in the wallet belonging to this key - if you dont have the 24 words for the key, the 0.25 is lost forever, and can never be restored
whatever key the `frpl` address belongs to, controls those 0.25 - if you dont have the key, no control
all you can do then is to do as i described above

**Comment by serg3140** [comment]
there is another wallet that I am not using. I have 24 phrases. Do I need to restore it? No problem :) I'll try

**Comment by serg3140** [comment]
Thanks for the tip! I found 0.25 Chia !!! They came to the address of the old wallet.
I am very happy!!!

**Comment by supercating** [comment]
想请问是怎么找到的，我和楼主遇到同样的问题，我也同步了我现有的钱包和之前的钱包，但是依然没有找到我的0.25个

**Comment by serg3140** [comment]
Посмотрите внимательно старый кошелек15.11.2021, 20:19, "super cat" ***@***.***>:
想请问是怎么找到的，我和楼主遇到同样的问题，我也同步了我现有的钱包和之前的钱包，但是依然没有找到我的0.25个

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- С уважением,Сергей Баданов+7-919-665-92-60
