### ISSUE TITLE
Bug error in wallet entry accounting Please help me

### ISSUE THREAD

**Issue by LuizC1171** [Chia-Network/chia-blockchain#8254]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8252

<div type='discussions-op-text'>

<sup>Originally posted by **LuizC1171** August 27, 2021</sup>
I have a problem in my wallet tha i can't and do not know how to solve. Please help me. My wallet pops up the entries but it doesn't appear on the balance sheet. What's wrong? I stayed 3 days farm and did not receive anything. Today entered the entries but did not account in the total balance sheet. I Win in 12 hour.

![Seo](https://user-images.githubusercontent.com/89670580/131201984-cbf8f869-e791-487d-9b1f-4518c6f0e2ae.png)
![Seo2](https://user-images.githubusercontent.com/89670580/131201990-2019236f-76ee-400d-807e-3837b78a5393.png)

I earned every 12 hours, and I stayed 3 days without having any input. Today had entries but did not change the balance of 5760 from 3 days ago.PLEEEEESE HELP ME.

I Have this diagnostics on CMD:

C:\WINDOWS\system32>cd C:\Users\WCHLC10\AppData\Local\chives-blockchain

C:\Users\WCHLC10\AppData\Local\chives-blockchain>type saida.txt

C:\Users\WCHLC10\AppData\Local\chives-blockchain\app-1.1.904\resources\app.asar.unpacked\daemon
true
Error loading config - using defaults
startUrl file:///C:\Users\WCHLC10\AppData\Local\chives-blockchain\app-1.1.904\resources\app.asar\build\renderer\index.html
C:\Users\WCHLC10\AppData\Local\chives-blockchain\app-1.1.904\resources\app.asar.unpacked\daemon
true
C:\Users\WCHLC10\AppData\Local\chives-blockchain\app-1.1.904\resources\app.asar.unpacked\daemon
true
Running python executable:
child process success
(node:10168) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron. See electron/electron#23506 for more information
No cert
Have cert
stderr: E:\chives-blockchain\venv\Lib\site-packages\chives\daemon\server.py:690: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.

C:\Users\WCHLC10\AppData\Local\chives-blockchain></div>

**Comment by shaneo257** [comment]
you're having an issue with the chives gui, this is chia
please lodge an issue with them
