### ISSUE TITLE
Wallet don't receive XCH

### ISSUE THREAD

**Issue by reza646464** [Chia-Network/chia-blockchain#8256]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by reza646464** [comment]
hi all
i send some XCH3 time to my wallet but i don't get it after tow week

**Comment by vOBLA86** [comment]
Same here, I haven't received a pool payout, and besides that "chia wallet show" shows me 0.0 XCH

**Comment by keliew** [comment]
> Same here, I haven't received a pool payout, and besides that "chia wallet show" shows me 0.0 XCH

check with the pool?

**Comment by keliew** [comment]
> hi all
> i send some XCH3 time to my wallet but i don't get it after tow week

the sender confirmed that it left his/her wallet?

**Comment by reza646464** [comment]
yes
