### ISSUE TITLE
GUI only shows spinners and does not properly start

### ISSUE THREAD

**Issue by taweesakpintakam** [Chia-Network/chia-blockchain#8260]
I've had the same issue as @jsantanajr21. In the past, I've just left the app open and running, and it would just magically start working after 24 hours. This time, Everything looks find when I clock on full node or wallets, but plots, farm, and pool sections all show me a spinning notification (e.g. - nothing). On v1.2.3, Win10, using OG plots (was about to start plotting some new NFT plots, but now I cant).

_Originally posted by @friedjeff in https://github.com/Chia-Network/chia-blockchain/issues/8146#issuecomment-903385997_

**Comment by loppefaaret** [comment]
dupe #8146

**Comment by mariano54** [comment]
Can you find the file ~/.chia/log/debug.log and send this to me on keybase? My username is sorgente711.

**Comment by Grevious1one** [comment]
I'm having the same problem.  is there a fix for this.  I'm running windows 10 with Chia 1.2.7
<img width="889" alt="Screenshot 2021-09-19 135551" src="https://user-images.githubusercontent.com/87335561/133926613-7b9e9490-a85e-49b4-be07-0f59606ecbb7.png">
?

**Comment by loppefaaret** [comment]
> I'm having the same problem. is there a fix for this. I'm running windows 10 with Chia 1.2.7

This looks like a corrupted blockchain database:
WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
if it worked, you can remove the files we put on the Desktop!
