### ISSUE TITLE
[BUG] Since 1.2.5 update no more incoming pool  transactions

### ISSUE THREAD

**Issue by Thierry-G** [Chia-Network/chia-blockchain#8264]
**Describe the bug**
Since 1.2.5 update there is no more transaction incoming payement in the wallet.

**To Reproduce**
Update from version 12.3 to 1.2.5

**Expected behavior**
Dayly rewards feeds the wallet

**Screenshots**
n/a

**Desktop**

- OS: Windows 10 
- OS Version/Flavor: 21H1 built: 19043.1165
- CPU:  Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz   3.40 GHz

**Additional context**
Same bug occurs on Ubuntu 20.02.3 LTS / intel core i-5-6500 CPU @3.2Ghz x4 and on farmer:
raspberry pi4 / ubuntu

**Comment by loppefaaret** [comment]
are you sure you got the correct wallet selected ? is the wallet synced ?

**Comment by Thierry-G** [comment]
Hi
Thanks for the reply, 
The wallet is synchronized and  I made no change in my wallet.
What can I do ?
Regards

**Comment by loppefaaret** [comment]
check chiaexplorer.com or xchscan.com for incoming transactions - check the pool for transactions - make sure that there actually are transactions incoming that are not shown in the client

**Comment by Thierry-G** [comment]
Hi thanks for your support
Hopefully this is not a bug, I've just been notified that the pool has chaged its rules without notifications for non discord users.
Feel free to close this topic or inform others users.
Kind regards from France

**Comment by loppefaaret** [comment]
what pool ?

**Comment by Thierry-G** [comment]
It is the following:
https://pool.poolchia.com/

Solely users who are using discord have been noticed on the change which occured the August 26th. And also users who have been visited their web site.
