### ISSUE TITLE
Update the Debian GUI icon

### ISSUE THREAD

**Issue by jim4067** [Chia-Network/chia-blockchain#8270]
I installed the desktop client and it looks like the default react/typescript/electron icon is being used.

**Comment by mariano54** [comment]
Perhaps this is because the Chia.icons file is actualy lowercase, and here it's specified with a capital C:
https://github.com/Chia-Network/chia-blockchain/blob/main/build_scripts/build_linux_deb.sh#L63

**Comment by paulhainsworth-chia** [comment]
Added to backlog https://trello.com/c/lGFo619w

**Comment by emlowe** [comment]
This seems fixed sometime along the way
