### ISSUE TITLE
[BUG] Installer fails on Ubuntu 20.04.3 64bit Server on Raspberry Pi4

### ISSUE THREAD

**Issue by jayhohoho2019** [Chia-Network/chia-blockchain#8288]
**Describe the bug**
Installer fails with a gcc error message.

**To Reproduce**

1. Follow the INSTALL guide for Ubuntu.
2. Error appears after running install.sh in dir chia-blockchain
3. See error
...
Collecting zipp>=0.5
  Using cached zipp-3.5.0-py3-none-any.whl (5.7 kB)
Collecting idna>=2.0
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Building wheels for collected packages: argon2-cffi
  Building wheel for argon2-cffi (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/chia-blockchain/venv/bin/python /home/ubuntu/chia-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp_jgr8f9m
       cwd: /tmp/pip-install-7arc51f4/argon2-cffi_6b94d2a9fbc54ee69baaaac23dc795cb
  Complete output (23 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.8
  creating build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/__main__.py -> build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/_legacy.py -> build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/exceptions.py -> build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/low_level.py -> build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/__init__.py -> build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/_utils.py -> build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/_password_hasher.py -> build/lib.linux-aarch64-3.8/argon2
  copying src/argon2/_ffi_build.py -> build/lib.linux-aarch64-3.8/argon2
  running build_clib
  building 'argon2' library
  creating build/temp.linux-aarch64-3.8
  creating build/temp.linux-aarch64-3.8/extras
  creating build/temp.linux-aarch64-3.8/extras/libargon2
  creating build/temp.linux-aarch64-3.8/extras/libargon2/src
  creating build/temp.linux-aarch64-3.8/extras/libargon2/src/blake2
  aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iextras/libargon2/src/../include -Iextras/libargon2/src/blake2 -c extras/libargon2/src/argon2.c -o build/temp.linux-aarch64-3.8/extras/libargon2/src/argon2.o
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for argon2-cffi
Failed to build argon2-cffi
ERROR: Could not build wheels for argon2-cffi which use PEP 517 and cannot be installed directly

**Expected behavior**

**Screenshots**

**Desktop**

- OS: Linux harvester15 5.4.0-1042-raspi #46-Ubuntu SMP PREEMPT Fri Jul 30 00:35:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
- OS Version/Flavor: 
- CPU: Hardware        : BCM2835 Revision        : d03114  Model           : Raspberry Pi 4 Model B Rev 1.4

**Additional context**
Appears to be a new issue as I successfully installed 1.2.5 just a few days ago.  Or may be it was an upgrade from 1.2.3.  Sorry can't remember for sure. 

Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux

**Comment by jayhohoho2019** [comment]
anyone looking into this?

**Comment by jayhohoho2019** [comment]
Would a full copy of chia-blockchain from another host (exactly the same hardware and OS) where 1.2.5 had been installed successfully work?

**Comment by emlowe** [comment]
can you try to install argon2-cffi manually? `pip3 install argon2-cffi -v`

**Comment by drlr85** [comment]
Hi, I had the same problem since yesterday on RaspiOS arm64  
`apt install python3.7-dev`
fixed it.

This was in my error log:  
`build/temp.linux-aarch64-3.7/_ffi.c:50:14: fatal error: pyconfig.h: No such file or directory  `
`#    include <pyconfig.h>`
`                           ^~~~~~~~~~~~  `

python3.7-dev provided missing pyconfig.h

**Comment by jayhohoho2019** [comment]
pip3 install argon2-cffi -v   inside the chia-blockchain dir completed without errors.

**Comment by jayhohoho2019** [comment]
afterwards . ./install.sh was able to complete as well.

**Comment by ALTracer** [comment]
@jayhohoho2019 Why are you compiling `argon2-cffi` from source when binary wheels exist at [PiWheels](https://www.piwheels.org/project/argon2-cffi/)? Raspberry Pi OS aarch64 uses them while Ubuntu might not. If so, be prepared with all the headers and `-dev` packages.

**Comment by cmmarslender** [comment]
I believe this should be resolved now for both ARM (Pi) and any M1 users that were seeing this issue. Wheels for these platforms have been updated on Chia's PyPI

**Comment by jayhohoho2019** [comment]
> @jayhohoho2019 Why are you compiling `argon2-cffi` from source when binary wheels exist at [PiWheels](https://www.piwheels.org/project/argon2-cffi/)? Raspberry Pi OS aarch64 uses them while Ubuntu might not. If so, be prepared with all the headers and `-dev` packages.

I wasn't doing anything different from what I had done before.  I just ran install.sh on Ubuntu 64bit Server on a RasPi4.

**Comment by jayhohoho2019** [comment]
> I believe this should be resolved now for both ARM (Pi) and any M1 users that were seeing this issue. Wheels for these platforms have been updated on Chia's PyPI

I can close this if you confirm this is tested and fixed.   install.sh finished successfully for me after I ran pip3 install argon2-cffi -v  but I should have needed to.
