### ISSUE TITLE
[BUG] Dont change xch_target_address

### ISSUE THREAD

**Issue by DmitryRS** [Chia-Network/chia-blockchain#8302]
Dont change xch_target_address in config.yaml

**Comment by loppefaaret** [comment]
could you explain a little better what your issue is ? this is not enough to go on

**Comment by DmitryRS** [comment]
When you change the "Payout Address" on the Pool tab, it does not change in config.yaml (xch_target_address) and the payment is made to the old address, although the new one is specified in the Payout Address. Sorry for my English.

**Comment by DmitryRS** [comment]
Thanks, I didn’t know, but it’s not very convenient.

**Comment by loppefaaret** [comment]
to clarify bit more, the "pool reward target address" would direct wins from OG plots pool part
the "farmer reward target address" will direct farmer part of wins from both OG plots, and plotNFT's
and finally, the payout address on a plotNFT, is where any rewards from the plotNFT goes (solo farming or pooling)

**Comment by DmitryRS** [comment]
And in order not to create a new theme, is it possible to delete unnecessary pools through the chia interface? Without editing config.yaml?

**Comment by loppefaaret** [comment]
no, not currently - we are creating an option to hide unwanted plotNFT's in a future update!
that being said, ill close this issue
