### ISSUE TITLE
[BUG] unhandled exception

### ISSUE THREAD

**Issue by spamkutu** [Chia-Network/chia-blockchain#8318]
**Describe the bug**
	Bucket 120 uniform sort. Ram: 3.739GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 121 uniform sort. Ram: 3.739GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 122 uniform sort. Ram: 3.739GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 123 uniform sort. Ram: 3.739GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 124 uniform sort. Ram: 3.739GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 125 uniform sort. Ram: 3.739GiB, u_sort min: 0.563GiB, qs min: 0.281GiB.
	Bucket 126 uniform sort. Ram: 3.739GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Bucket 127 uniform sort. Ram: 3.739GiB, u_sort min: 1.125GiB, qs min: 0.281GiB.
	Total matches: 4294855134
Caught plotting error: Matches do not match with number of write entries 4294855134 4294854857
Traceback (most recent call last):
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 132, in <module>
  File "D:\a\chia-blockchain\chia-blockchain\venv\Lib\site-packages\chia\cmds\chia.py", line 128, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 153, in create_cmd
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "chia\plotting\create_plots.py", line 247, in create_plots
RuntimeError: Unknown exception
[21328] Failed to execute script 'chia' due to unhandled exception!

**To Reproduce**

Time to time its self

**Desktop**

- OS: Windows 10
- OS Version/Flavor:  Pro
- CPU: Intel(R) Core(TM) i7-10710U CPU

**Comment by dreamboatcap** [comment]
[``](https://chiaforum.com/t/1-1-6-plotting-hangs-with-matches-do-not-match-with-number-of-write-entries-error/4789/3)

**Comment by spamkutu** [comment]
Thank you i will follow there

**Comment by loppefaaret** [comment]
This mostly down to hardware - likely memory, try and cool them better, turn off XMP or overclocking, and see if you get through plotting

**Comment by loppefaaret** [comment]
any luck ?

**Comment by spamkutu** [comment]
no luck after deleted my config.yaml and restarted the system its now see the pilot and its look good like working to produce but all my pilot was nft pilot and this time there is no pool i made alot nft but my pilot belong to nfts. so this time its not show me the my contracted nft pools its always say join a pool, i dont need to join any more nfts pool atm. i just want to recall my old conractted nfts pool how that will be possible? I am totaly stuck now on this hardvester its show my pilot all green and working produce state but there no any pool or nfts how that is possible? And also i cannot produce my new pilots since i dont see my nfts contracted pool so i am realy stuck atm, help me to recall my conracted pools to back please,
many many thanks loppefaaret,
i not follow this since there told me to goo ill check there so sorry to my latency answer and waiting your new clue thank you so so much to you!!
https://chiaforum.com/t/1-1-6-plotting-hangs-with-matches-do-not-match-with-number-of-write-entries-error/4789/3
