### ISSUE TITLE
Chia GUI marks plots as invalid and stops farming them even though they are fine [BUG]

### ISSUE THREAD

**Issue by Oscillator098** [Chia-Network/chia-blockchain#8331]
**Describe the bug**
When doing some copying/moving and shuffling of plots, Chia GUI detects them as "Failed to open (invalid)" plots in GUI and stops farming them. After copy/moving is complete plots still remain as invalid and Chia won't farm them. 
Doing ".\chia check" they are just fine.
I have to close Chia GUI completely and open it again to continue to farm these wrongly marked "invalid" plots. Chia continues to farm them just fine.
Removing particular Farming directory and Adding it again doesn't help, only closing GUI helps to solve the problem.

I noticed that Flax doesn't suffer from this bug. It just can't farm the plot while inaccessible but automatically continues to do so once it is accessible again.

**To Reproduce**
1. Start moving/copying some active farming plots until they show up on "Failed to open (invalid plots)" window of GUI.
2. Check those "invalid plots" with ".\chia check".
3. Try removing and adding farming directory in question and even Refresh plots.
4. Close and reopen GUI to see that it starts working just fine.

**Expected behavior**
When farmer comes across temporarily unusable plot due to copying/moving/manipulating it is ok to be marked as invalid but there should be option in GUI to "check it" and remove it from that "invalid list" so it can continue to be farmable again.

**Desktop**

- OS: Windows 10
- CPU: Core i7-11700, 32B RAM

**Additional context**
Chia GUI 1.2.5.

**Comment by diaconom** [comment]
We discussed this last week they are looking into the problem. 

one can run ‘chia start harvester -r’ in cli - to restart the harvester. No need to shutdown the whole farm.

Hope the fix in next release.

**Comment by xdustinface** [comment]
See #8279
