### ISSUE TITLE
[BUG] Harvester not seeing looking for new plots after initial check

### ISSUE THREAD

**Issue by hancooo** [Chia-Network/chia-blockchain#8332]
Once the harvester has done its initial search for plots on startup it doesn't check again.

For example: 
I am adding 2 plots every 30 minutes currently. 
The Chia client is showing my harvester has 1283 plots, which was true at the time of starting the harvester. 
![image](https://user-images.githubusercontent.com/20757683/132109265-e36ef027-9ba8-405e-a2f2-f09c7979cabf.png)

I now actually have 1288 valid plots. I also have Flax running and you can see these plots are valid and showing fine in Flax: 
![image](https://user-images.githubusercontent.com/20757683/132109289-72f4977c-4e96-42d9-8c0d-28655a2e6e61.png)

Farmer version 1.2.5 on Windows client
Harvester version 1.2.5 on Windows ran through cmd (chia start harvester -r)

This may happen with the farmer aswell, but I have only been adding plots to harvester so unsure.

**Comment by xdustinface** [comment]
> I am adding 2 plots every 30 minutes currently.

I assume you just copy them over. This has been fixed #8279.
