### ISSUE TITLE
Popup window with 805702 / 797355 [BUG]

### ISSUE THREAD

**Issue by jackob007** [Chia-Network/chia-blockchain#8339]
**Describe the bug**

**To Reproduce**

After upgrade to 1.2.5 the popup window with 797355 or 805702 appears each few minutes.
It's associated with Not syncing status :(
After closing the window Syncing starts, but then stops again.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/39448244/132130349-441749dd-b173-478a-87d1-29d5c85b63e3.png)

**Desktop**

- OS: Widows 10
- OS Version/Flavor: Windows 10 Pro
- CPU: AMD Ryzen

**Comment by mariano54** [comment]
Can you find the file ~/.chia/log/debug.log and send this to me on keybase? My username is sorgente711.
