### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jmhands** [Chia-Network/chia-blockchain#834]
**Describe the bug**
output of `chia wallet` incorrect units

**To Reproduce**

run `chia wallet` command from Linux CLI

**Expected behavior**
supposed to be 10^12 (1 trillion) Mojo per Chia. An enhancement would be the output in Chia, not Mojos.

**Screenshots**
```$ chia wallet
Balances
Wallet ID 1 type STANDARD_WALLET Chia Wallet
   -Confirmed: 110625000000.0
   -Unconfirmed: 110625000000.0
   -Spendable: 110625000000.0
   -Frozen: 0.0
   -Pending change: 0.0
```

**Desktop (please complete the following information):**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.1
- CPU: Intel Xeon SP (Skylake)

**Additional context**
appears that GUI wallet is showing the correct value
https://github.com/Chia-Network/chia-blockchain/blob/main/src/consensus/block_rewards.py
`1 Chia coin = 1,000,000,000,000 = 1 trillion mojo.`

**Comment by kiwihaitch** [comment]
To elaborate on the report:
bug - the output of chia wallet is displaying the balance as if there are 1 billion mojo/chia, not 1 trillion. ie is a factor of 1,000 off.
enhancement - display the balance in chia, not mojos - there are too many digits to make it easily readable.

**Comment by hoffmang9** [comment]
One tip on your next bug report - add a title before the [BUG] label.
