### ISSUE TITLE
GG Blockchain

### ISSUE THREAD

**Issue by GGsilvergold** [Chia-Network/chia-blockchain#8350]
Start diagnosis...
App name: Smart Life
App version: 3.31.0
App build: 20210817140403
App bundle ID: com.tuya.smartlife
App Key: fvsrjwtvqs4wpuy8r9qd
Device type: iPhone 12 Pro Max
System version: 14.7.1
User account: ggsilvergold@icloud.com
Country code: 65
Region code: EU
Carrier name: Singtel
VPN: off
isoCountryCode: sg
mobileCountryCode: 525
mobileNetworkCode: 01

Network type: WIFI
Device IP Address: fd70:68d:2313:5:1440:5223:2c17:a365
Wifi geteway address: 192.168.79.1
DNS server address: 192.168.79.1
-----------------------------------------
Diagnosis domain: API Domain
Start analysis domain...
DNS analysis result: 18.185.165.38, 3.125.101.18, 52.57.89.19 (18ms)

Ping 18.185.165.38...
64 bytes from 18.185.165.38 icmp_seq=#0 type=ICMPv4TypeEchoReply time=256ms
64 bytes from 18.185.165.38 icmp_seq=#1 type=ICMPv4TypeEchoReply time=306ms
64 bytes from 18.185.165.38 icmp_seq=#2 type=ICMPv4TypeEchoReply time=307ms
64 bytes from 18.185.165.38 icmp_seq=#3 type=ICMPv4TypeEchoReply time=306ms
Ping finished
Ping 3.125.101.18...
64 bytes from 3.125.101.18 icmp_seq=#0 type=ICMPv4TypeEchoReply time=308ms
64 bytes from 3.125.101.18 icmp_seq=#1 type=ICMPv4TypeEchoReply time=303ms
64 bytes from 3.125.101.18 icmp_seq=#2 type=ICMPv4TypeEchoReply time=306ms
64 bytes from 3.125.101.18 icmp_seq=#3 type=ICMPv4TypeEchoReply time=307ms
Ping finished
Ping 52.57.89.19...
64 bytes from 52.57.89.19 icmp_seq=#0 type=ICMPv4TypeEchoReply time=305ms
64 bytes from 52.57.89.19 icmp_seq=#1 type=ICMPv4TypeEchoReply time=241ms
64 bytes from 52.57.89.19 icmp_seq=#2 type=ICMPv4TypeEchoReply time=269ms
64 bytes from 52.57.89.19 icmp_seq=#3 type=ICMPv4TypeEchoReply time=310ms
Ping finished

Start tracerouter...
1	192.168.79.1		2.77ms	1.97ms	2.86ms	
2	192.168.1.254		3.72ms	3.45ms	2.95ms	
3	121.6.47.254		5.60ms	5.36ms	5.04ms	
4	202.166.123.130		5.53ms	5.30ms	5.55ms	
5	202.166.123.129		5.10ms	5.32ms	5.41ms	
6	202.166.121.101		5.77ms	5.76ms	6.12ms	
7	202.166.120.109		5.51ms	7.66ms	4.97ms	
8	202.166.123.70		5.84ms	6.16ms	5.81ms	
9	203.208.191.197		5.75ms	6.01ms	5.91ms	
10	203.208.153.246		5.74ms	5.53ms	5.53ms	
11	203.208.173.22		179.40ms	179.31ms	179.56ms	
12	********	
13	64.125.27.42		344.64ms	406.08ms	410.42ms	
14	64.125.26.19		208.09ms	318.81ms	290.90ms	
15	64.125.26.165		194.69ms	218.16ms	304.41ms	
16	64.125.26.42		408.36ms	409.62ms	409.45ms	
17	********	
18	********	
19	********	
20	64.125.29.24		313.74ms	356.17ms	409.07ms	
21	64.125.29.7		409.20ms	409.60ms	409.45ms	
22	52.95.217.48		409.34ms	409.48ms	409.62ms	
23	********	
24	********	
25	********	
Tracerouter finished

-----------------------------------------
Diagnosis domain: MQTT Domain
Start analysis domain...
DNS analysis result: 18.194.10.142, 18.197.183.192, 18.196.142.136 (21ms)

Start tracerouter...
1	192.168.79.1		2.30ms	2.01ms	2.88ms	
2	192.168.1.254		2.56ms	2.43ms	2.20ms	
3	121.6.47.254		4.69ms	4.62ms	4.27ms	
4	202.166.123.130		6.05ms	5.07ms	5.24ms	
5	202.166.123.129		4.54ms	8.22ms	5.37ms	
6	202.166.121.101		5.04ms	5.35ms	5.10ms	
7	202.166.120.109		4.93ms	4.75ms	5.15ms	
8	202.166.123.70		13.57ms	5.29ms	5.10ms	
9	203.208.191.197		5.38ms	5.16ms	5.14ms	
10	203.208.153.246		5.14ms	4.97ms	5.00ms	
11	203.208.173.22		178.81ms	178.92ms	178.93ms	
12	********	
13	64.125.27.42		413.81ms	366.25ms	350.05ms	
14	64.125.26.19		204.32ms	208.01ms	304.08ms	
15	64.125.26.165		204.43ms	205.12ms	204.31ms	
16	64.125.26.42		324.88ms	391.71ms	415.21ms	
17	********	
18	********	
19	********	
Tracerouter finished

-----------------------------------------
Diagnosis domain: Apple Domain
Start analysis domain...
DNS analysis result: 23.74.222.80 (30ms)

Ping 23.74.222.80...
64 bytes from 23.74.222.80 icmp_seq=#0 type=ICMPv4TypeEchoReply time=6ms
64 bytes from 23.74.222.80 icmp_seq=#1 type=ICMPv4TypeEchoReply time=6ms
64 bytes from 23.74.222.80 icmp_seq=#2 type=ICMPv4TypeEchoReply time=5ms
64 bytes from 23.74.222.80 icmp_seq=#3 type=ICMPv4TypeEchoReply time=5ms
Ping finished

Start tracerouter...
1	192.168.79.1		2.26ms	1.91ms	1.88ms	
2	192.168.1.254		6.25ms	3.52ms	2.32ms	
3	121.6.47.254		4.64ms	4.37ms	4.43ms	
4	202.166.123.130		7.22ms	5.23ms	5.12ms	
5	202.166.123.129		5.03ms	4.92ms	5.57ms	
6	202.166.121.101		5.22ms	5.74ms	6.01ms	
7	202.166.120.109		5.19ms	4.86ms	5.33ms	
8	202.166.123.70		5.46ms	5.27ms	5.71ms	
9	203.208.177.177		5.63ms	4.99ms	4.76ms	
10	203.208.166.234		6.07ms	5.59ms	5.84ms	
11	********	
12	********	
13	********	
Tracerouter finished

Diagnosis finished!

**Comment by jack60612** [comment]
> Start diagnosis...
> App name: Smart Life
> App version: 3.31.0
> App build: 20210817140403
> App bundle ID: com.tuya.smartlife
> App Key: fvsrjwtvqs4wpuy8r9qd
> Device type: iPhone 12 Pro Max
> System version: 14.7.1
> User account: [ggsilvergold@icloud.com](mailto:ggsilvergold@icloud.com)
> Country code: 65
> Region code: EU
> Carrier name: Singtel
> VPN: off
> isoCountryCode: sg
> mobileCountryCode: 525
> mobileNetworkCode: 01
> 
> ## Network type: WIFI
> Device IP Address: fd70:68d:2313:5:1440:5223:2c17:a365
> Wifi geteway address: 192.168.79.1
> DNS server address: 192.168.79.1
> Diagnosis domain: API Domain
> Start analysis domain...
> DNS analysis result: 18.185.165.38, 3.125.101.18, 52.57.89.19 (18ms)
> 
> Ping 18.185.165.38...
> 64 bytes from 18.185.165.38 icmp_seq=#0 type=ICMPv4TypeEchoReply time=256ms
> 64 bytes from 18.185.165.38 icmp_seq=#1 type=ICMPv4TypeEchoReply time=306ms
> 64 bytes from 18.185.165.38 icmp_seq=#2 type=ICMPv4TypeEchoReply time=307ms
> 64 bytes from 18.185.165.38 icmp_seq=#3 type=ICMPv4TypeEchoReply time=306ms
> Ping finished
> Ping 3.125.101.18...
> 64 bytes from 3.125.101.18 icmp_seq=#0 type=ICMPv4TypeEchoReply time=308ms
> 64 bytes from 3.125.101.18 icmp_seq=#1 type=ICMPv4TypeEchoReply time=303ms
> 64 bytes from 3.125.101.18 icmp_seq=#2 type=ICMPv4TypeEchoReply time=306ms
> 64 bytes from 3.125.101.18 icmp_seq=#3 type=ICMPv4TypeEchoReply time=307ms
> Ping finished
> Ping 52.57.89.19...
> 64 bytes from 52.57.89.19 icmp_seq=#0 type=ICMPv4TypeEchoReply time=305ms
> 64 bytes from 52.57.89.19 icmp_seq=#1 type=ICMPv4TypeEchoReply time=241ms
> 64 bytes from 52.57.89.19 icmp_seq=#2 type=ICMPv4TypeEchoReply time=269ms
> 64 bytes from 52.57.89.19 icmp_seq=#3 type=ICMPv4TypeEchoReply time=310ms
> Ping finished
> 
> Start tracerouter...
> 1 192.168.79.1 2.77ms 1.97ms 2.86ms
> 2 192.168.1.254 3.72ms 3.45ms 2.95ms
> 3 121.6.47.254 5.60ms 5.36ms 5.04ms
> 4 202.166.123.130 5.53ms 5.30ms 5.55ms
> 5 202.166.123.129 5.10ms 5.32ms 5.41ms
> 6 202.166.121.101 5.77ms 5.76ms 6.12ms
> 7 202.166.120.109 5.51ms 7.66ms 4.97ms
> 8 202.166.123.70 5.84ms 6.16ms 5.81ms
> 9 203.208.191.197 5.75ms 6.01ms 5.91ms
> 10 203.208.153.246 5.74ms 5.53ms 5.53ms
> 11 203.208.173.22 179.40ms 179.31ms 179.56ms
> 12 ********
> 13 64.125.27.42 344.64ms 406.08ms 410.42ms
> 14 64.125.26.19 208.09ms 318.81ms 290.90ms
> 15 64.125.26.165 194.69ms 218.16ms 304.41ms
> 16 64.125.26.42 408.36ms 409.62ms 409.45ms
> 17 ********
> 18 ********
> 19 ********
> 20 64.125.29.24 313.74ms 356.17ms 409.07ms
> 21 64.125.29.7 409.20ms 409.60ms 409.45ms
> 22 52.95.217.48 409.34ms 409.48ms 409.62ms
> 23 ********
> 24 ********
> 25 ********
> Tracerouter finished
> 
> Diagnosis domain: MQTT Domain
> Start analysis domain...
> DNS analysis result: 18.194.10.142, 18.197.183.192, 18.196.142.136 (21ms)
> 
> Start tracerouter...
> 1 192.168.79.1 2.30ms 2.01ms 2.88ms
> 2 192.168.1.254 2.56ms 2.43ms 2.20ms
> 3 121.6.47.254 4.69ms 4.62ms 4.27ms
> 4 202.166.123.130 6.05ms 5.07ms 5.24ms
> 5 202.166.123.129 4.54ms 8.22ms 5.37ms
> 6 202.166.121.101 5.04ms 5.35ms 5.10ms
> 7 202.166.120.109 4.93ms 4.75ms 5.15ms
> 8 202.166.123.70 13.57ms 5.29ms 5.10ms
> 9 203.208.191.197 5.38ms 5.16ms 5.14ms
> 10 203.208.153.246 5.14ms 4.97ms 5.00ms
> 11 203.208.173.22 178.81ms 178.92ms 178.93ms
> 12 ********
> 13 64.125.27.42 413.81ms 366.25ms 350.05ms
> 14 64.125.26.19 204.32ms 208.01ms 304.08ms
> 15 64.125.26.165 204.43ms 205.12ms 204.31ms
> 16 64.125.26.42 324.88ms 391.71ms 415.21ms
> 17 ********
> 18 ********
> 19 ********
> Tracerouter finished
> 
> Diagnosis domain: Apple Domain
> Start analysis domain...
> DNS analysis result: 23.74.222.80 (30ms)
> 
> Ping 23.74.222.80...
> 64 bytes from 23.74.222.80 icmp_seq=#0 type=ICMPv4TypeEchoReply time=6ms
> 64 bytes from 23.74.222.80 icmp_seq=#1 type=ICMPv4TypeEchoReply time=6ms
> 64 bytes from 23.74.222.80 icmp_seq=#2 type=ICMPv4TypeEchoReply time=5ms
> 64 bytes from 23.74.222.80 icmp_seq=#3 type=ICMPv4TypeEchoReply time=5ms
> Ping finished
> 
> Start tracerouter...
> 1 192.168.79.1 2.26ms 1.91ms 1.88ms
> 2 192.168.1.254 6.25ms 3.52ms 2.32ms
> 3 121.6.47.254 4.64ms 4.37ms 4.43ms
> 4 202.166.123.130 7.22ms 5.23ms 5.12ms
> 5 202.166.123.129 5.03ms 4.92ms 5.57ms
> 6 202.166.121.101 5.22ms 5.74ms 6.01ms
> 7 202.166.120.109 5.19ms 4.86ms 5.33ms
> 8 202.166.123.70 5.46ms 5.27ms 5.71ms
> 9 203.208.177.177 5.63ms 4.99ms 4.76ms
> 10 203.208.166.234 6.07ms 5.59ms 5.84ms
> 11 ********
> 12 ********
> 13 ********
> Tracerouter finished
> 
> Diagnosis finished!

what is this?

**Comment by jack60612** [comment]
Im assuming this was accidental so i'm closing it. If it isnt then simply reopen it
