### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by haroon889** [Chia-Network/chia-blockchain#8369]
**Describe the bug**

**To Reproduce**

How to fix this? i have been tried it so hard.
![241490015_4669720956393409_4928244495280621317_n](https://user-images.githubusercontent.com/84036790/132382856-f11c9ec2-02e5-474d-9766-2ad6e58a7a6c.jpg)

how can i do?
![Screenshot 2021-08-22 124743](https://user-images.githubusercontent.com/84036790/132382708-0d5ad4e2-fe88-4f7f-85e1-6157025580c0.png)

**Comment by mariano54** [comment]
Can you find the file ~/.chia/log/debug.log and send this to me on keybase? My username is sorgente711.
