### ISSUE TITLE
[BUG] with the farmer

### ISSUE THREAD

**Issue by VerdaderoKiwi** [Chia-Network/chia-blockchain#8378]
**Describe the bug**
The farmer stops farming eventually. I need to restart chia client.

**To Reproduce**
I can't reproduce, it happens eventually. I have not yet established any pattern of occurrence. 

- OS: Windows 10
- CPU: Intel Pentium Silver J5005 1.5Ghz

**Additional context**
All disks connected via USB

**Comment by loppefaaret** [comment]
do you have any kind of `ERROR` or `WARNING` reported by the harvester in your `debug.log` file, located in you users folder `~\.chia\mainnet\log\` ?

**Comment by mariano54** [comment]
Can you find the file ~/.chia/log/debug.log and send this to me on keybase? My username is sorgente711.

**Comment by VerdaderoKiwi** [comment]
Hello for the answer. Today it happened again. The farmer stops at about 8:45am and i noticed about it at 15:00 I reviewed debug.log and at the time that the stop happened it doesn't show any harvester error, but i have found in the windows events monitor, an error in start_harvester.exe process:
-------------------------
Nombre de la aplicación con errores: start_harvester.exe, versión: 0.0.0.0, marca de tiempo: 0x61062589
Nombre del módulo con errores: python39.dll, versión: 3.9.6150.1013, marca de tiempo: 0x60d9ead7
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x00000000000579e9
Identificador del proceso con errores: 0x27e4
Hora de inicio de la aplicación con errores: 0x01d7a4e2b97f9935
Ruta de acceso de la aplicación con errores: C:\Users\mgarc\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon\start_harvester.exe
Ruta de acceso del módulo con errores: C:\Users\mgarc\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon\python39.dll
Identificador del informe: c5a97a2b-5249-4593-9a0c-5f823db82505
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores: 
-----------------------------------------------
Sorry, i'm from Spain :-)

And in the details panel:
-------------------------------------------------
- System 
  - Provider 
   [ Name]  Application Error 
  - EventID 1000 
   [ Qualifiers]  0 
   Version 0 
   Level 2 
   Task 100 
   Opcode 0 
   Keywords 0x80000000000000 
  - TimeCreated 
   [ SystemTime]  2021-09-09T07:43:14.3615304Z 
   EventRecordID 16905 
   Correlation 
  - Execution 
   [ ProcessID]  0 
   [ ThreadID]  0 
   Channel Application 
   Computer MiniW10 
   Security 
- EventData 
   start_harvester.exe 
   0.0.0.0 
   61062589 
   python39.dll 
   3.9.6150.1013 
   60d9ead7 
   c0000005 
   00000000000579e9 
   27e4 
   01d7a4e2b97f9935 
   C:\Users\mgarc\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon\start_harvester.exe 
   C:\Users\mgarc\AppData\Local\chia-blockchain\app-1.2.5\resources\app.asar.unpacked\daemon\python39.dll 
   c5a97a2b-5249-4593-9a0c-5f823db82505
------------------------------------------------
After this error, i can see an information event about the error event:
--------------------------------------------
Depósito con errores 1250620614921310701, tipo 4
Nombre de evento: APPCRASH
Respuesta: No disponible
Identificador de archivo .cab: 0

Firma del problema:
P1: start_harvester.exe
P2: 0.0.0.0
P3: 61062589
P4: python39.dll
P5: 3.9.6150.1013
P6: 60d9ead7
P7: c0000005
P8: 00000000000579e9
P9: 
P10: 

Archivos adjuntos:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD195.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD33C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD36C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD36A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD3A9.tmp.txt

Es posible que estos archivos estén disponibles aquí:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_start_harvester._f84ffc4074ab689517a8ab18b7e54dd46166495_b153e886_b788078c-00fd-4224-b71a-919fc1d06672

Símbolo de análisis: 
Nueva búsqueda de una solución: 0
Id. de informe: c5a97a2b-5249-4593-9a0c-5f823db82505
Estado del informe: 268435456
Depósito con algoritmo hash: a88d583269eee476015b18d2bd2a51ed
GUID de archivo .cab: 0
-------------------------------------------------
Thanks for all!
