### ISSUE TITLE
[BUG] GUI Wallet History doesn't show more then 50 transactions

### ISSUE THREAD

**Issue by second-one** [Chia-Network/chia-blockchain#8392]
**Describe the bug**
When you go to the Wallet History in the GUI and set "Rows per page:" to 100 it still shows only the last 50 transactions.

**To Reproduce**

Just go to Wallet History in the GUI and set "Rows per page:" to 100

**Expected behavior**

It should show the last 100 transactions if you have 100 or more transactions.

**Desktop**

Windows 10

**Additional context**

It would be nice to be able to see ALL transactions not just the last 50 or 100.

**Comment by loppefaaret** [comment]
this depends on #7978

**Comment by emlowe** [comment]
Tracked as https://github.com/Chia-Network/chia-blockchain-gui/issues/525
