### ISSUE TITLE
Not found Plots

### ISSUE THREAD

**Issue by DimstrBarboss** [Chia-Network/chia-blockchain#8408]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8407

<div type='discussions-op-text'>

<sup>Originally posted by **DimstrBarboss** September  8, 2021</sup>
Does not see part of the plots, I suspect that all the plots are made in the GUI. The sections made by Mad max work. This happened after a sudden restart of the computer. Newly made sections in the GUI are visible and working.

![Not found Plots](https://user-images.githubusercontent.com/90198409/132552395-708c10b2-6f17-44ca-9fe7-318d18976dfa.png)
</div>

**Comment by DimstrBarboss** [comment]
When checking for validity, it issues such a warning:
There are 1 plots with a farmer or pool public key that is not on this machine. The farmer private key must be in the keychain in order to farm them, use 'chia keys' to transfer keys. The pool public keys must be in the config.yaml

**Comment by loppefaaret** [comment]
lets take it to #8407 for now, and if we can pinpoint an actual issue, we can open up issue
