### ISSUE TITLE
[BUG] Avast reports Botnet threat

### ISSUE THREAD

**Issue by yeahgaga** [Chia-Network/chia-blockchain#8427]
avast free antivirus version 21.7.2481
windows 10 
chia1.2.5
process start_full_node.exe
infection tcp://85.234.12.242:8444

![virus](https://user-images.githubusercontent.com/90428636/132778374-b8c7e460-2069-4c6c-acfc-a419ee7fab9b.png)

**Comment by jack60612** [comment]
It's a false flag that is common with many crypto apps.
Avast is bad anyway. Switch to Malwarebytes.
