### ISSUE TITLE
[BUG] - Chia version 1.2.6.dev27 Farmer stoped farming

### ISSUE THREAD

**Issue by rsbehrends** [Chia-Network/chia-blockchain#8435]
**Describe the bug**
After upgrading to latest Chia version 1.2.6.dev27 Farmer stoped farming to NFT plot. 
An error can be seeing at the end of `chia plotnft show` command. And last, in the pool I can confirm it is not farming at all.

**To Reproduce**

1. Execute `chia plotnft show`

**Expected behavior**
Farm to a pool.
Get full detailed output.

**Screenshots**
Following Wallet ID status. I'm getting:

```
Wallet id 3: 
Current state: FARMING_TO_POOL
Current state from block height: 803986
Launcher ID: <launcherdid>
Target address (not for plotting): <address>
Number of plots: 110
Owner public key: <key>
Pool contract address (use ONLY for plotting - do not send money to this address): <address>
Current pool URL: https://na1.pool.space
Relative lock height: 64 blocks
Exception from 'wallet' <bytes32: LauncherID>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8a66a2b190>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f8a661b4700>, 104706.41662279)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f8a66a2b0a0>
```

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.3 LTS
- CPU: Intel i7 11700K

**Additional context**
Farming to pool

**Comment by rsbehrends** [comment]
Looks like I found a workaround. 
I had leaved and joined the pool and at least the error on the plotnft command is gone.
Will keep an eye on the pool side to see if it is now working.

**Comment by rsbehrends** [comment]
I do have an hypothesis ... To upgrade both the farmer and the harvester I have deleted everything and installed latest version. But restored both the DB and the Wallet files.

**Comment by loppefaaret** [comment]
yup, there was an issue in this dev version that had some problems with plotNFT's... if you are farming, i suggest you stick to release versions atleast
if you are testing dev versions, perhaps come by our #testnet channel on keybase
just going to close down this for now, as PR's are incoming for this
