### ISSUE TITLE
[Speedup sync]synced mainnet and wallet db files migaration between local network machines.

### ISSUE THREAD

**Issue by HomeLH** [Chia-Network/chia-blockchain#8437]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8436

<div type='discussions-op-text'>

<sup>Originally posted by **HomeLH** September 11, 2021</sup>
1. On the full synced machine, stop chia deamon `chia stop -d all`. Check dbs files at `~/.chia/mainnet/db` and `~/.chia/mainnet/wallet/db`, make sure that only exists  `blockchain_v1_mainnet.sqlite`, not `*.sqlite-wal, *.sqlite-shm`. If exists `*.sqlite-wal, *.sqlite-shm`, try `chia start famer`, then ` chia stop -d all`.
2. On the target machine, make sure no chia process is running. Remove all files at `~/.chia/mainnet/db` and `~/.chia/mainnet/wallet/db`.
3. Copy  source machine `~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite` `~/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_*.sqlite` into target machine `~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite` ,`~/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_*.sqlite`
on linux, use `scp` with `scp user@host:/home/user/.chia/mainnet/db/blockchain_v1_mainnet.sqlite ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite`.
4. If "pool_list" section in your config.yaml is missing your current pool settings, it will produce "Exception from 'wallet' Unclosed client session & Unclosed connector". Slove this problem with https://github.com/Chia-Network/chia-blockchain/issues/7210#issuecomment-878508674. Just copy the whole "pool_list:" section from old machine to the new one and it works fine. Check it with `chia plotnft show`
5. Check 'chia show -cs`, good luck</div>

**Comment by loppefaaret** [comment]
lets just stick to #8436 for now...
