### ISSUE TITLE
[BUG] 25 words instead of 24 when creating a new wallet

### ISSUE THREAD

**Issue by harambasapp** [Chia-Network/chia-blockchain#8439]
**Describe the bug**
I was playing around with adding a new wallet to my chia. I clicked on "Create new private key" but instead of 24 fields with 24 words, I saw 25 of them. 

**To Reproduce**

1. Click on the "Create new private key"
2. go back
3. Click on the "Create new private key"
4. go back
5. Click on the "Create new private key"
6. go back
7. Click on the "Create new private key"
8. go back
9. Click on the "Import from mnemonic (24 words)"
10. go back
11. Click on the "Create new private key"
12. go back
13. Click on the "Create new private key"
14. go back
15. Click on the "Create new private key"
16. That additional 25. field should appear

**Expected behavior**
As I know there should always be 24 words for mnemonic

![25 words wallet01](https://user-images.githubusercontent.com/90500744/132941954-4268b4d1-10fc-49bc-a00c-342755929c02.PNG)
![25 words wallet02](https://user-images.githubusercontent.com/90500744/132941956-ca43b018-3caa-49b0-a3d4-88d96d4a15f0.PNG)

**Screenshots**

**Desktop**
- OS: Windows 10 PRO
- OS Version: 21H1
- OS Build: 19043.1202
- CPU: Ryzen 7 3700x

[chia w01.zip](https://github.com/Chia-Network/chia-blockchain/files/7147473/chia.w01.zip)

**Additional context**
Please check the video I have sent to you in the zip file.
Added steps for reproducing the issue are not 100% sure. It may depend on how much times do you have to click on these buttons and to go back.

**Comment by harambasapp** [comment]
Now I got 26 words with repeating numbers 07 and 14 with different words in them
![26 words wallet01 marked](https://user-images.githubusercontent.com/90500744/132942147-269eecc0-e7f2-4f04-a1c2-8e37ebbdc021.PNG)

**Comment by jack60612** [comment]
Ok this is bad

**Comment by jack60612** [comment]
> Now I got 26 words with repeating numbers 07 and 14 with different words in them
> ![26 words wallet01 marked](https://user-images.githubusercontent.com/90500744/132942147-269eecc0-e7f2-4f04-a1c2-8e37ebbdc021.PNG)

what chia version are you running?

**Comment by jack60612** [comment]
Seems like a gui issue

**Comment by harambasapp** [comment]
It's 1.2.5
![chia info](https://user-images.githubusercontent.com/90500744/132954313-d91130fa-a14c-4066-901e-743092de6440.PNG)

**Comment by jack60612** [comment]
> It's 1.2.5
> ![chia info](https://user-images.githubusercontent.com/90500744/132954313-d91130fa-a14c-4066-901e-743092de6440.PNG)

install the latest version. 1.2.6

**Comment by jack60612** [comment]
@harambasapp

**Comment by harambasapp** [comment]
Same issue present on 1.2.6
![chia 1 2 6](https://user-images.githubusercontent.com/90500744/132954788-175675fa-0840-4058-b9e8-74ff1a35eb5d.PNG)
![1 2 6 26 words](https://user-images.githubusercontent.com/90500744/132954791-8665fad3-0118-4687-9243-a5289a069e8a.PNG)

**Comment by zhangxxyz** [comment]
I was stunned

**Comment by jack60612** [comment]
I can reproduce this

**Comment by loppefaaret** [comment]
oh wow

**Comment by paulhainsworth-chia** [comment]
Thanks for reporting this so thoroughly. This is now added to top of the list of our blockchain engineering team's backlog. https://trello.com/c/vXOCDlIG

**Comment by jack60612** [comment]
> Thanks for reporting this so thoroughly. This is now added to top of the list of our blockchain engineering team's backlog. https://trello.com/c/vXOCDlIG

Im also working on it

**Comment by harambasapp** [comment]
Seems like it is enough to click on "Create a new private" key and "back" multiple time.
No need to click on "Import from mnemonic (24 words)"

**Comment by jack60612** [comment]
@paulhainsworth-chia fixed it https://github.com/Chia-Network/chia-blockchain/issues/8439

**Comment by jack60612** [comment]
@harambasapp the fix has been made and it will be included in the next update.
Thanks!
