### ISSUE TITLE
[BUG] Windows Paged Pool possible leak

### ISSUE THREAD

**Issue by BlakkaBob** [Chia-Network/chia-blockchain#8442]
Every time I open the Chia client or CLI and start farmer, my paged pool starts filling up. Paged pool stays around 250-500mb, and 800mb at most, when I do anything else. The minute I open the Chia client or start farmer via CLI on my PC, my paged pool jumps to about 4GB then slowly increases to about 150GB until my computer stops harvesting. My 2 harvesters running Windows 10 Home also have the same slowly increasing paged pool issue. Eventually my Farmer stops harvesting but still farms from my 2 harvesters. Once my Farmer's harvester stops working, I can't even restart my PC so I have to do a hard shutdown. All systems are running Chia 1.2.6.

1. Open Chia client or start farmer via CLI.

![image](https://user-images.githubusercontent.com/90521482/132954836-815c8181-364f-49e8-a520-3e00f23decaf.png)

- OS: Windows
- OS Version/Flavor: 10 Pro
- CPU: AMD 5950x
- RAM: 128GB 3600
- OS Drive: 1TB Samsung 980 Pro

**Comment by loppefaaret** [comment]
could you perhaps try and identify which process is leaking memory ? 
under details in task manager, you might have to add columns

**Comment by BlakkaBob** [comment]
I added the Paged Pool column and nothing seems to show up. When I stop Chia, it doesn't go any higher. When I restart Chia, it starts climbing again. Same on all 3 PCs, which I can only assume is start_harvester.exe

**Comment by Aidan24** [comment]
Wow, the same thing seems to happen to me. I've never checked before, but now I can see the Paged pool visibly growing as I look at it with Chia running (and just about nothing else running on this machine). It's adding about 100Mb per 20 seconds or so. 
![image](https://user-images.githubusercontent.com/41297044/133488493-9c16ba8e-9979-4beb-a86c-ac33e761c7ba.png)
Windows 10 Pro (21H1)
Intel i9-7980XE 
128 GB Ram

**Comment by emlowe** [comment]
I don't think this is caused directly by Chia. Windows paged pool is allocated by the kernel and kernel drivers (of which Chia has none). It's possible the farming process is causing the windows kernel and/or the filesystem drive to cache substantial information in the paged pool, but this isn't something Chia has any control over. Chia does not directly allocate any memory in the paged pool, as this can only be done inside the kernel.

**Comment by BlakkaBob** [comment]
> I don't think this is caused directly by Chia. Windows paged pool is allocated by the kernel and kernel drivers (of which Chia has none). It's possible the farming process is causing the windows kernel and/or the filesystem drive to cache substantial information in the paged pool, but this isn't something Chia has any control over. Chia does not directly allocate any memory in the paged pool, as this can only be done inside the kernel.

What settings could be changed in Windows to fix this?

**Comment by emlowe** [comment]
We might be able to use PoolMon to see which "Tag" is using this memory. (see https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/poolmon)

You don't need to enable pool tagging, as it's already enabled by default in newer Windows.

**Comment by emlowe** [comment]
Just a thought - do you possibly have any third party software like A/V or anti-malware that might have installed any file system drivers?

**Comment by Aidan24** [comment]
Nothing other than the default Windows Defender for me. I am using FlexPool which keeps the difficulty at 1 so may cause additional disk access.

**Comment by BlakkaBob** [comment]
> Just a thought - do you possibly have any third party software like A/V or anti-malware that might have installed any file system drivers?

No

**Comment by Aidan24** [comment]
Not sure if this is helpful but the results from Poolmon give me this (truncated):
Memory:133910608K Avail:120237644K  PageFlts:    58   InRam Krnl:15528K P:2213780K
 Commit:115287556K Limit:192630864K Peak:115295108K            Pool N:553556K P:101762656K
 System pool information
 Tag  Type     Allocs            Frees            Diff       Bytes                  Per Alloc

 MmSt Paged    231294 (   0)     57186 (   0)   174108 103457628256 (          0)      594215
 NtfF Paged    441306 (   0)    366967 (   0)    74339   118942400 (          0)        1600
 FMfn Paged    759457 (   0)    593014 (   0)   166443    80908448 (          0)         486
 Ntff Paged     47460 (   0)     22302 (   0)    25158    35422464 (          0)        1408
 CM25 Paged      5216 (   0)         0 (   0)     5216    23535616 (          0)        4512
 FIcs Paged    486941 (   0)    387423 (   0)    99518    19107456 (          0)         192
 MmRe Paged      5935 (   0)      3661 (   0)     2274    18234832 (          0)        8018
 Ntfo Paged    489912 (   0)    415760 (   0)    74152    17753344 (          0)         239
 NtFs Paged   3477160 (   0)   3344940 (   0)   132220    13125056 (          0)          99
 MPsc Paged     27375 (   0)      4316 (   0)    23059    12175152 (          0)         528
 hibr Paged         5 (   0)         4 (   0)        1     8675328 (          0)     8675328
 ClfI Paged        79 (   0)        18 (   0)       61     7459936 (          0)      122294
 Toke Paged    796483 (   0)    792697 (   0)     3786     6737088 (          0)        1779
 IoNm Paged  12529875 (   0)  12502583 (   0)    27292     6401264 (          0)         234
 Vi54 Paged      3599 (   0)      2148 (   0)     1451     6368512 (          0)        4389
 RvaL Paged      2662 (   0)       605 (   0)     2057     6271360 (          0)        3048
 Ntf0 Paged   1131352 (   0)   1031931 (   0)    99421     5564320 (          0)          55
 DxgK Paged   1269722 (  13)   1264255 (  13)     5467     5529104 (          0)        1011
 MPhc Paged     84776 (   0)     60947 (   0)    23829     4956432 (          0)         208

**Comment by Aidan24** [comment]
From https://techcommunity.microsoft.com/t5/ask-the-performance-team/getting-to-know-the-mmst-pool-tag/ba-p/374971

Most Common Root Causes for high MmSt pool usage
The Memory Manager cannot trim paged pool memory quickly enough before allocations start failing
Heavy file I/O because too many files or large files are opened simultaneously
Outlook .PST/Lotus Notes .NSF files being stored on the server and opened over the network
VSS (Volume Shadow Copy) snapshots aren’t dismounting
Large $MFT due to fragmentation or many files on the volume

**Comment by Aidan24** [comment]
All my disks are showing 0% fragmentation and I'm not running Outlook

**Comment by Aidan24** [comment]
Is it possible files are being opened and not closed (resource leak)?

**Comment by emlowe** [comment]
I'll note just because your Paged Pool appears high doesn't necessarily mean anything is wrong. However, the initial report was talking about needing to hard reset machines. It's possible these things are not related, however.

Are you actively plotting? Are you farming any forks?

**Comment by Aidan24** [comment]
> I'll note just because your Paged Pool appears high doesn't necessarily mean anything is wrong. However, the initial report was talking about needing to hard reset machines. It's possible these things are not related, however.
> 
> Are you actively plotting? Are you farming any forks?

I'm neither plotting nor farming any forks. I did a "patch Tuesday" restart yesterday evening and my paged pool is now already 113Gb and still increasing. I'll see if anything dies in a day or so if it reaches the max possible without being trimmed.

**Comment by BlakkaBob** [comment]
> I'll note just because your Paged Pool appears high doesn't necessarily mean anything is wrong. However, the initial report was talking about needing to hard reset machines. It's possible these things are not related, however.
> 
> 
> 
> Are you actively plotting? Are you farming any forks?
> 
> 

I'm not plotting or farming any forks. Sometimes my farmer's harvester will go down for like 30 minutes and fix itself but half the time, it doesn't fix itself and requires a hard restart. When I use a ramdisk of 105gb for plotting, the system has a normal paged pool and functions fine.

**Comment by BlakkaBob** [comment]
I have an update. I switched from self pooling to using FlexFarmer from FlexPool and the issue is still occurring. The paged pool file usage must be something to do with windows searching my drives for plots.

**Comment by Aidan24** [comment]
I can confirm my paged pool does not seem to exceed 144Gb, so it does look like a Windows thing. I can't see how this is efficient as presumably all the plots are already well indexed and not fragmented, but I guess there's no easy way in Python for lower level access to the file system.
