### ISSUE TITLE
SSL Context 8444 error after each full reboot

### ISSUE THREAD

**Issue by denisprovost** [Chia-Network/chia-blockchain#8451]
**Describe the bug:**
After restarting OS and starting the chia process by CLI, the log shows failed attempts for farmer_server  (Cannot connect to host 127.0.0.1:8444) -> ssl.SSLContext object while ***19 minutes***. The reboot takes too long ... 

**To Reproduce:**
- Reboot system
- "source /home/XX/chia-blockchain/venv/bin/activate; chia start farmer"
- Show log after "registered for service chia_farmer -> {'success': True}"
   
**System:**
- Chia version: 1.2.6
- OS: Ubuntu 21.04 server on Pi4 (8gigas) (full node + haverster)

**Infos:**
- Port 8444 is well open
- I have always had this problem from the start regardless of the version 
- Maybe mistake on my part in the chia config file (I bet on it)
- The full node starts ONLY after these attempts are finished

**Steps infos:**
After start chia process:
![A](https://user-images.githubusercontent.com/10295449/132989973-53b6840d-56d4-4db4-8907-eb454294912c.PNG)

At the moment, check  port using:
![avant](https://user-images.githubusercontent.com/10295449/132990208-bc24d3fe-bfb8-4276-a2bd-f9ede831d324.jpg)

After service chia_farmer started, failed attempts SSL on 8444:
![B](https://user-images.githubusercontent.com/10295449/132990112-7578cf89-7c44-47b2-a97a-e6382af8d20b.PNG)

 ***AFTER 19 minutes*** of failed !!! The full node finally starts and the syncing begin
![C](https://user-images.githubusercontent.com/10295449/132990338-57fe1a47-e132-4e8f-a536-30c753dbd8cb.jpg)

Re-check  port using:
![apres](https://user-images.githubusercontent.com/10295449/132990393-a028f263-cfcc-41b8-b6b2-905e6fb241d2.png)

**Comment by xporterfield** [comment]
Also having this issue, port 8444 forwarded

**Comment by maxcom99** [comment]
same exact problem

**Comment by loppefaaret** [comment]
it is normal to see this in the beginning of starting up the program, as the other services start faster than the `full_node` does...
![image](https://user-images.githubusercontent.com/32275244/133113779-219e1b69-f8f3-4de9-87ed-fb257fcdf2eb.png)

**Comment by denisprovost** [comment]
19mn for restart system its normal for you? look at what is present in my images before the full node starts

**Comment by maxcom99** [comment]
@loppefaaret  this is NOT closed. Let it run for over 30 min and it never came up

**Comment by loppefaaret** [comment]
if your issue is different than the one here, i suggest you create your own issue instead - but this is not abnormal behavior currently - i just spend about 20 minuted waiting on the node to come up my self, with the database on a mechanical HDD - yes, it is not optimal start up time, 100%, but it is what it is currently, we are looking at improving it, but as such, it is not an issue that is a fault as such - the node does come up, the error is only reported as long as the node is loading the database...

**Comment by denisprovost** [comment]
ok thank you for the details and glad that it is known and that you are working on it, it's the main thing.

Syncing of farmer after the full node synced is not possible easily? even by cli on our side if it is necessary?
