### ISSUE TITLE
Chia plot not going past %20

### ISSUE THREAD

**Issue by FrozenOwl1** [Chia-Network/chia-blockchain#8453]
\I started mining chia and my plot won't go past %20 and on computation table 4. my final destination drive has been stuck at 100% for the last day and a half.

**Comment by jack60612** [comment]
> \I started mining chia and my plot won't go past %20 and on computation table 4. my final destination drive has been stuck at 100% for the last day and a half.

100% what?

**Comment by FrozenOwl1** [comment]
its been stuck at 100% usage but nothing has gotten done

**Comment by FrozenOwl1** [comment]
is it possible that this stage is based on ram because if it is that might be my issue

**Comment by hoffmang9** [comment]
This is almost always one of a handful of hardware issues. It is usually that your RAM is faulty in one of two ways. It either has bad BIOS settings or you have a faulty RAM stick.

**Comment by FrozenOwl1** [comment]
did a little more digging and I think it's just I don't have enough ram because it's moving at 1 bucket a day so I am gonna try and try some more ram and see about XMP and maybe a little overclock.

**Comment by loppefaaret** [comment]
ohhh, yes, that makes sense, you are most likely swapping, and that is why your drive is going 100%, but nothing is happening.
either as you suggested add additional memory, or turn down the amount of memory allocated to the plotter - are you on a 4GB system ? 
https://www.chia.net/2021/02/22/plotting-basics.html
this is a writeup that might be worth a read, it also has memory needs for plotting k32 listed.

**Comment by FrozenOwl1** [comment]
Yes I am on a single 4Gb stick so I will try that

**Comment by jack60612** [comment]
> Yes I am on a single 4Gb stick so I will try that

im not sure 4gb will work at all to be honest

**Comment by FrozenOwl1** [comment]
> im not sure 4gb will work at all to be honest

I didn't think it would work either but it is the maximum you can do for a plot

Also i restarted the plot allocated max ram and allocated two more threads and now in a couple hours i have done 6 buckets instead of one a day.

**Comment by loppefaaret** [comment]
this is turning into a support issue, and not a code issue
therefor im closing th issue, and transferring it to our support discussions instead
