### ISSUE TITLE
[BUG]not secronized what can I do when I'm getting this error for a long time

### ISSUE THREAD

**Issue by Tlhadnc** [Chia-Network/chia-blockchain#8456]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by hoffmang9** [comment]
Which error? You need to fill out your bug report.

**Comment by 988387069** [comment]
> 哪个错误？您需要填写错误报告。

![image](https://user-images.githubusercontent.com/82623800/133033988-a3fc4d7b-311b-4bbf-895d-76b0f89e1ad2.png)
这个问题不解决?

**Comment by Tlhadnc** [comment]
这样很久了

988387069 ***@***.***>, 13 Eyl 2021 Pzt, 09:25 tarihinde şunu
yazdı:

**Comment by M451N9** [comment]
![image](https://user-images.githubusercontent.com/73755015/133165464-94082e4e-b053-4660-8291-07f477abfb39.png)

**Comment by M451N9** [comment]
Windows 10 Pro 21H1 ‎18.‎08.‎2021 19043.1165 Windows Feature Experience Pack 120.2212.3530.0

Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz   3.60 GHz

**Comment by jack60612** [comment]
There is no error
