### ISSUE TITLE
Pool xch_target_address does not change when changing Manage Farming Rewards [BUG]

### ISSUE THREAD

**Issue by DrakeFS** [Chia-Network/chia-blockchain#8471]
**Describe the bug**
Changing the Farming Reward Address in the GUI only updates the original `xch_target_address` in the config.yaml.  

**To Reproduce**

1. Go to the Farm tab
2. Click on Manage Farming Rewards
3. Change the address
4. Verify the pool `xch_target_address` in config.yaml did not change

**Expected behavior**
The pool `xch_target_address` will  be changed to what is set via the GUI.

**Screenshots**
NA

**Desktop**
Affects multiple machines and multiple OS

**Additional context**
If this is the intended behavior, then there needs to be a warning to the User that changing the farming reward address does not include the pool farming reward target address.  Currently there is no way to change the pool `xch_target_address` via the GUI.

**Comment by mariano54** [comment]
There are two input fields, one to change the farmer reward address and one to change the pool reward address. Did you change both?

**Comment by DrakeFS** [comment]
> There are two input fields, one to change the farmer reward address and one to change the pool reward address. Did you change both?

That was it,  I think earlier builds used the second address for something else.  Thanks for the info.
