### ISSUE TITLE
Error: Could not find authentication sk for pk

### ISSUE THREAD

**Issue by temicus** [Chia-Network/chia-blockchain#8494]
**Describe the bug**
Getting every few minutes the Error:
Could not find authentication sk for pk: xxx...
I have this problem already since at least one month. 
Changing pools or solo modes bring nothing. Reinstalling or changing client version also doesn't help.
I had 2 wallets/keys on this machine before and removed in GUI one of them. Maybe its the result.

**To Reproduce**

1. Open the log file
2. check for errors

**Desktop**
win 10 pro, chia client 1.2.6.

**Comment by emlowe** [comment]
This means that many of your plots were plotted using the farmer key that you no longer have on that machine - if you don't have that key anymore, those plots cannot be farmed.
