### ISSUE TITLE
Current Points ballance is 0, when i restart chia it will harvest points, i think it stops when one plot is over and another starts creating[BUG], please help

### ISSUE THREAD

**Issue by Soulstonee** [Chia-Network/chia-blockchain#8504]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by Soulstonee** [comment]
it happens sometimes after second plot copied to destination, first is ok, after second no points

**Comment by loppefaaret** [comment]
could you try and attach you `debug.log` file, under your users folder `~/.chia/mainnet/log/`

**Comment by emlowe** [comment]
We also need the version of chia and which OS. Also, please provide more details on what you are doing and seeing. As is, this report is not actionable due to lack of details
