### ISSUE TITLE
[BUG]I farm solo by old plots. When I caught the block I only got 0.25 chia. How to find 1.75 chia?

### ISSUE THREAD

**Issue by BratecLiss** [Chia-Network/chia-blockchain#8523]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by devtestnet** [comment]
All set all done

**Comment by devtestnet** [comment]
Closed

**Comment by shaneo257** [comment]
check to see your receive address is the same for both farmer and pool rewards

**Comment by loppefaaret** [comment]
if it is a plotNFT plot, you need to "Claim Reward" on the plotNFT under the "Pool" tab

**Comment by 1122dly** [comment]
我也是遇到这样的情况，请问怎么能找回1.75个xch币。

**Comment by 1122dly** [comment]
> 如果是地块， 您需要在 "池" 标签下的地块上 "索赔奖励"

您好，我没有找到“索赔奖励”地方，请问能详细说说吗？

**Comment by 1122dly** [comment]
非常感谢您的回复，我看过管理耕种奖励这里了，没有错！一直都是这个地址且前面几次的奖励0.25+1.75都有收到！就这次只收到0.25！那剩下的1.75能找回来吗？

> 如果您正在耕种旧 OG 地块，并且未收到 1.75 - 也许您配置错误您的"农业奖励目标地址" - 请确保它被设置为您控制的钱包中的地址 - 它位于右上角 3 菜单的"Farm"选项卡下`...`
