### ISSUE TITLE
GUI not displaying correctly [BUG]

### ISSUE THREAD

**Issue by bigmac5753** [Chia-Network/chia-blockchain#8525]
Parts of GUI not displaying correctly.
1.2.6 install from source.
Ubuntu, ryzen 3700x, 1050ti.

![Screenshot at 2021-09-18 10-25-49](https://user-images.githubusercontent.com/17450308/133884132-b55b2958-f919-43d6-9da2-81f3d8cdef0c.png)

**Comment by shaneo257** [comment]
this is a known issue, and it doesn't affect the farming
