### ISSUE TITLE
[BUG] Timelord FTBFS on Gentoo

### ISSUE THREAD

**Issue by ALTracer** [Chia-Network/chia-blockchain#8536]
**Describe the bug**

ChiaVDF fails to build binary wheels during timelord installation.
Some of the fastest amd64 (hello AVX512) boxes might want to run Gentoo compiled from source with performance optimizations, however multilib desktops will encounter this problem. Didn't test on `no-multilib` profile.

**To Reproduce**

1. Get yourself a Gentoo box with CMake and Python3.9 (docker will do), sync the Portage tree and ` emerge dev-libs/gmp[cxx]` etc.
2. Git shallow clone this repository (chia-blockchain) or chiavdf
3. Run `sh install.sh` -- success, enter venv, run `sh install-timelord.sh` -- failure. Alternatively, `pip3 install --user chiavdf`.
4. Notice the error in pip wheel build_ext log of CMake not seeing libgmp headers.

**Expected behavior**

Pip3 should build the binary wheel successfully
CMake should see the multilib headers in `/usr/incude/x86_64-pc-linux-gnu/gmp.h` or `/usr/include/i686-pc-linux-gnu/gmp.h` (depends on USE flags ABI_X86="32 64"`

**Screenshots**

Logs posted in relevant repository https://github.com/Chia-Network/chiavdf/issues/95

**Desktop**

- OS: Linux (5.10 kernel)
- OS Version/Flavor: Gentoo 17.1 amd64 multilib, KDE Desktop
- CPU: AMD Ryzen 3200G (`CFLAGS="-march=native -O2 -pipe"`)

**Additional context**
I tried redefining -DGMP_INCLUDES in setup.py and the wheel built successfully. Except Pip noticed local changes in git copy and bumped wheel version.

**Comment by emlowe** [comment]
We rely on community support for Gentoo and many other linux distributions as it's not viable to directly support them all. We welcome any PRs.
