### ISSUE TITLE
Cannot sync a new wallet from a fully synced node(Loop exception in sync Was not able to add blocks 0-32)

### ISSUE THREAD

**Issue by hhenrry501** [Chia-Network/chia-blockchain#8538]
I have 2 keys in one machine (Windows 10), and am using GUI (1.2.5 and upgrade to 1.2.7) to farm. 

But I got this error when I tried to sync my second wallet which is a new one: 

2021-09-20T23:47:40.711 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-09-20T23:49:34.651 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 555, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 687, in fetch_blocks_and_validate
ValueError: Peer returned no response

2021-09-20T23:49:34.655 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 0-32. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 608, in sync_job
  File "chia\wallet\wallet_node.py", line 668, in _sync
  File "chia\wallet\wallet_node.py", line 565, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 0-32

I tried to upgrade chia, delet mainnet/wallet/db/second_wallet.sqlite , and I still get this error and it's not syncing. 
The other wallet works perfectly fine (fully synced).

**Comment by loppefaaret** [comment]
what kind of drive is Chia installed on ? i fear it might be a HDD that is not fast enough to complete the weight proof prior to a timeout happening ?

**Comment by loppefaaret** [comment]
uhh, and what kind of CPU then ? perhaps its the CPU that cant complete the work prior to timeout then ?

**Comment by hhenrry501** [comment]
> uhh, and what kind of CPU then ? perhaps its the CPU that cant complete the work prior to timeout then ?

I got i9-10850k CPU with 32GB RAM (computer#1) , and chia was installed on HDD. 
"HDD that is not fast enough to complete the weight proof prior to a timeout happening" 
if HDD isn't fast enough, shouldnt all wallets on this computer not be able to sync? but my wallet#1 can sync without problem.

this problem was fixed by logging in this wallet#2 on another computer, and let it start syncing for couple minutes, and then copy/paste the wallet.sqlite file back to computer#1, and restart GUI.  

just so much hassle to sync a cold wallet.

**Comment by loppefaaret** [comment]
im not entirely sure what is going on, but the initial weight proof might be too big for the node to complete if it is on a HDD - im not a developer, just a support person, so dont take my assumtions for anything more than that please!
the further apart a sync has to complete, the more sub epochs it has to include in the weight proof, and i think that just leads to timeouts in some cases

**Comment by hhenrry501** [comment]
> im not entirely sure what is going on, but the initial weight proof might be too big for the node to complete if it is on a HDD - im not a developer, just a support person, so dont take my assumtions for anything more than that please!
> the further apart a sync has to complete, the more sub epochs it has to include in the weight proof, and i think that just leads to timeouts in some cases

I see your point, and I really appreciated your help. 
I just hope they could make it more user friendly, especially to those who dont have much experience in coding
