### ISSUE TITLE
[BUG] Chia blockchain GUI stops chia services during shutdown

### ISSUE THREAD

**Issue by zapalnick** [Chia-Network/chia-blockchain#8544]
I have configured a service that starts `chia start farmer` during system startup.
After starting the Chia Blockchain GUI and then closing it, the service stops.

I suggest one of two solutions:
1. check while running Chia Blockchain GUI if the service is already running. While closing the GUI the services would remain running.
2. While closing the GUI, adding a request whether to close the running services.

Linux Mint 20.2 Uma
Chia blockchain 1.2.7

**Comment by paulhainsworth-chia** [comment]
Added to backlog: https://trello.com/c/fLX1UtT9
