### ISSUE TITLE
I win a block and the  reward do not arrive

### ISSUE THREAD

**Issue by jealalri** [Chia-Network/chia-blockchain#8545]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8542

<div type='discussions-op-text'>

<sup>Originally posted by **jealalri** September 21, 2021</sup>
I win a block in space pool but the reward  no show in my wallet</div>

**Comment by loppefaaret** [comment]
Lets stick to the discussion for now, and try and see if we can figure out if there really is an issue with Chia - or if it something based on a misunderstanding.

**Comment by jealalri** [comment]
This is what I have

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
