### ISSUE TITLE
[Enhancement] GUI and CLI should discourage users from making multiple PlotNFTs

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#8547]
It is very easy to create PlotNFTs both in the UI and in the CLI - however, most of the time users only need one, and creating multiple NFTs is a result of not understanding how they work.

I think the GUI should present a "Are you sure?" whenever the user creates a new PlotNFT if they already have one. If the user has more than 10 PlotNFTs the GUI should strongly discourage them with possibly multiple pop-ups. After 20, the GUI should say that things will probably stop working if they continue. Something like that. The idea is to prevent users from getting themselves into trouble

The CLI should have similar behaviour and language.

**Comment by mariano54** [comment]
Good idea!

**Comment by turbotas** [comment]
I need four - why is it a bad idea?  I'm using multiple pools and move the plots around in groups to spread the risk against a bad pool operator and I only have 80TiB of Plots.  Agree with a hard limit (100?), but don't bother with spurious GUI warnings that affect everyone for an odd edge case - just refuse after 100.

**Comment by defaultsecurity** [comment]
I agree, this is a serious problem. Did you know that after a clean install, the previous PlotNFTs don't show up. They only show up after you create a new PlotNFT (that you will never use) Imagine how many PlotNFTs are created and wasted because of this bug: https://github.com/Chia-Network/chia-blockchain/issues/9733

**Comment by jack60612** [comment]
Resolved in Cli, GUI fix pending

**Comment by jack60612** [comment]
Both PR's Merged, Closing Issue
