### ISSUE TITLE
[BUG] Set and enforce a consistent limit for number of wallets/plotNFTs

### ISSUE THREAD

**Issue by emlowe** [Chia-Network/chia-blockchain#8550]
Currently, in some parts of the code there is an effective limit of 20 wallets (see https://github.com/Chia-Network/chia-blockchain/blob/main/chia/wallet/derive_keys.py#L65)

However, the UI allows creating many PlotNFTs, which each result in a new pooling wallet - this can soon result in a user ending up with more than 20 wallets, which then causes problems, particularly of course in find_authentication_sk() which will return None for any wallet_id > 20

This number should likely be parameterized in config.yaml and certainly enforced throughout the code to avoid users getting into problems.

**Comment by jack60612** [comment]
This should be completed now.

**Comment by jack60612** [comment]
Fixed by #9857

**Comment by jack60612** [comment]
Was also improved on by #9922
