### ISSUE TITLE
[BUG] DNS failing

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/chia-blockchain#8555]
I am seeing DNS issues in the log:
```
2021-09-21T17:44:15.703 full_node chia.full_node.full_node: WARNING  querying DNS introducer failed: All nameservers failed to answer the query dns-introducer.chia.net. IN A: Server 192.168.0.1 UDP port 53 answered The DNS operation timed out after 1.9998652935028076 seconds; Server 192.168.0.1 UDP port 53 answered The DNS operation timed out after 1.9998807907104492 seconds; Server 192.168.0.1 UDP port 53 answered The DNS operation timed out after 1.9998843669891357 seconds; Server 192.168.0.1 UDP port 53 answered The DNS operation timed out after 1.99985933303833 seconds; Server 192.168.0.1 UDP port 53 answered SERVFAIL
```

Also when using dig and getent:
```
; <<>> DiG 9.16.20 <<>> dns-introducer.chia.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 21621
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: b3d1e510d350e8148e70c857614a5247ba0ef1e5a8429ef5 (good)
;; QUESTION SECTION:
;dns-introducer.chia.net.       IN      A

;; Query time: 4999 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Sep 21 17:44:39 EDT 2021
;; MSG SIZE  rcvd: 80
```

Manjaro linux 5.13.15-1

It seems like I'm on ipv6, since I get an ivp6 when querying for google.com:
```
> getent hosts google.com                               
2607:f8b0:4008:807::200e google.com
```

**Comment by mariano54** [comment]
Looks like NetworkManager is setting this as the nameserver automatically (wired connection), is that normal?

```
# Generated by NetworkManager
nameserver 192.168.0.1
```

**Comment by emlowe** [comment]
That DNS is probably coming from your DHCP server? I'm gonna guess 192.168.0.1 is your router/DHCP server - so it's setting it to itself

**Comment by emlowe** [comment]
The DNS introducer looks good to me with both A and AAAA records (macOS and Ubuntu)

**Comment by jack60612** [comment]
> Looks like NetworkManager is setting this as the nameserver automatically (wired connection), is that normal?
> 
> ```
> # Generated by NetworkManager
> nameserver 192.168.0.1
> ```

try telling your router to use 1.1.1.1 which is cloudflare and always works for me

**Comment by mariano54** [comment]
I have a TPLink router. It was setting it to the default TP link DNS servers.
I change to google (8.8.8.8) and cloudflare as backup. It seems to work now.
