### ISSUE TITLE
ERROR    Exception: Failed to fetch block 903659 from

### ISSUE THREAD

**Issue by ShilohMy** [Chia-Network/chia-blockchain#8582]
**Describe the bug**
ERROR    Exception: Failed to fetch block 903659 from {'host': '109.192.89.199', 'port': 8444}, timed out, {'host': '109.192.89.199', 'port': 8444}. Traceback (most recent call last):
:

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by emlowe** [comment]
Failing to fetch a block from a peer is not a bug. You will fetch it from other peers
