### ISSUE TITLE
no llega monto grande pero pequeño si[BUG]

### ISSUE THREAD

**Issue by sergiosurvival** [Chia-Network/chia-blockchain#8602]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by sergiosurvival** [comment]
no me llega 20.935 chaingreen pero 0,2 
![2021-09-26](https://user-images.githubusercontent.com/83919237/134799580-3741b67f-705e-4abb-b2d1-b40f4533a1e4.png)
si

**Comment by sergiosurvival** [comment]
mando captura
![2021-09-26 (1)](https://user-images.githubusercontent.com/83919237/134799605-7c51248e-8b61-494d-8308-21ab101b218f.png)
s

**Comment by loppefaaret** [comment]
This is the github of Chia Network - Your problem seems to be with a fork of our software called "Chaingreen". i suggest you go to their github here:
https://github.com/ChainGreenOrg/chaingreen-blockchain
We are not going to be able to help you with this

**Comment by sergiosurvival** [comment]
Okk okk sorry
