### ISSUE TITLE
[BUG]Invalid pool contract puzzle hash

### ISSUE THREAD

**Issue by youyusi** [Chia-Network/chia-blockchain#8614]
ERROR    Error in pooling: (9, 'Invalid pool contract puzzle hash 5a6e881c0302637891a6c59fa01716799875b87041da5d3266db93425f114a83')

Please tell me what to do

**Comment by youyusi** [comment]
I'm sorry,I filled in the wrong pool contract address,This address is not in my list. Is there any way to solve it

**Comment by loppefaaret** [comment]
nope, the plot is build upon it, so if you manage to change this, it would have to be regenerated anyways.. delete it, and create a new
