### ISSUE TITLE
Repetitive "TLSV1_ALERT_INTERNAL_ERROR" Trying to Connect to Pool from Docker Container

### ISSUE THREAD

**Issue by rfalex11** [Chia-Network/chia-blockchain#8623]
I recently migrated my farmer from a late 2014 iMac (Big Sur 11.5.2) to intel NUC, where I was trying to run the farmer within a docker container.  I had issues with farming on my Mac, as it would corrupt the database after long durations of running.  I had to resolve the issue by deleting the `~/.chia` directory.  It was in the process of syncing ~was at a height of <100,000 when I then migrated the `~/.chia` directory over to the NUC.  The farmer and wallet are now both fully synced.  However, I cannot connect to my pool.  I get the following error every minute within my debug logs:

`2021-09-28T07:46:10.773 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://pool.poolchia.com, Cannot connect to host pool.poolchia.com:443 ssl:<ssl.SSLContext object at 0x7f0c1ea5d7c0> [[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)]`

Unsuccessful Troubleshooting Thus far:
- If i migrate the `~/chia` directory back to my iMac, it farms as expected and no errors occur.  However, this isn't a long term solution due to the aforementioned crashing issues.
- I have checked that there is a valid `/chia-blockchain/mozilla-ca/cacert.pem` file within the docker container, as well as the underlying NUC host. This file matches on all 3 devices/locations (iMac, NUC, docker image - validated w/ hash)
- I've deleted the docker image and re-downloaded it
- I've checked the lib
- I've tried leaving and rejoining the pool from the docker container, and get a similar error:

`root@b4793a88a918:~# chia plotnft create -u https://pool.poolchia.com -s pool
Exception from 'wallet' Error connecting to pool https://pool.poolchia.com: Cannot connect to host pool.poolchia.com:443 ssl:<ssl.SSLContext object at 0x7f9093ec6740> [[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)]`
- I have validated that the `libss1.1` is up to date and tried to upgrade in both the container, and the NUC
- I've validated that `echo -n |openssl s_client -connect pool.poolchia.com:443 |cat -n` returns as `CONNECTED` in both the docker container and the NUC

Additional Info: 

NUC/Container Arch: `Linux 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
iMac Arch: `Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64`
Chia Docker Image: `chianetwork/chia-docker` tag: `latest` , image_id: `c86d8a994ab7`, Created: `11 days ago`
Open

**Comment by emlowe** [comment]
Inside your venv, can you run `python --version` and `python -c "import ssl; print(ssl.OPENSSL_VERSION)"`

**Comment by rfalex11** [comment]
```
(venv) root@b4793a88a918:~# python --version
Python 3.8.10
(venv) root@b4793a88a918:~# python -c "import ssl;print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by emlowe** [comment]
I assume 1.1.1f matches the version of openssl if you run `openssl version`

I don't have any real good ideas, it seems very strange. I know that you said `openssl s_client` works fine - but maybe upgrading to the latest 1.1.1l?

**Comment by rfalex11** [comment]
```(venv) root@b4793a88a918:~# openssl version
OpenSSL 1.1.1f  31 Mar 2020```

**Comment by emlowe** [comment]
Can you show the output of `openssl s_client -connect pool.poolchia.com:443 -verify_return_error -brief -CAfile /chia-blockchain/mozilla-ca/cacert.pem`

**Comment by rfalex11** [comment]
REquested info:

```
root@7ff4644ca658:/chia-blockchain# openssl s_client -connect pool.poolchia.com:443 -verify_return_error -brief -CAfile /chia-blockchain/mozilla-ca/cacert.pem
140171866023232:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1543:SSL alert number 80
```

Also for thoroughness, I realized I didn't include this in my original post:
```

root@7ff4644ca658:/chia-blockchain# openssl s_client -connect pool.poolchia.com:443
CONNECTED(00000003)
140617390617920:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1543:SSL alert number 80
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 309 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
root@7ff4644ca658:/chia-blockchain#
```

**Comment by rfalex11** [comment]
this can be closed - it appears to be a networking issue, as I was able to resolve the problem by updating my `/etc/hosts` to point to the proper IP of the pool DNS, or updating `/etc/resolv.conf` to use a different DNS server

**Comment by emlowe** [comment]
Good glad it was resolved
