### ISSUE TITLE
[BUG]Cannot connect to wallet, connecting just hangs indefinitely

### ISSUE THREAD

**Issue by erock24601** [Chia-Network/chia-blockchain#863]
Bug happens when installing Chia and loading the wallet. Wallet hangs and is unable to open
Had issue using the beta 1.26**

Went to github to install chia blockchain code.
Installed using the installer
Unable to connect to wallet. UI just hangs on connecting

**Expected behavior**
I expected it to connect to my wallet.

**Desktop (please complete the following information):**

- OS: Windows 10
- OS Windows 10 Pro
- CPU: Intel 2600k 3.4ghz

**Additional context**
Interestingly enough when installing, this time around I didn't get the usual errors I get from windows defender. It loaded up got to the connect wallet without asking me if I wanted to run a harvester or farmer which I normally get asked from windows defender.

**Comment by mariano54** [comment]
Try again with beta 27 please

**Comment by ahietala** [comment]
Same issue with 1.0beta27 on Mac OSX. "Connecting to wallet" message and spinner hangs indefinitely. Installed using the MacOS dmg installer.

**Comment by beykovskyb** [comment]
Same issue for me with 1.0beta27 on MAC OSX exact same description
![Screen Shot 2021-02-17 at 7 04 58 PM](https://user-images.githubusercontent.com/79239356/108301669-5cec1000-7157-11eb-86a0-59a48342e4fb.png)

**Comment by beykovskyb** [comment]
> Try again with beta 27 please

Any input?
I was able to open and start syncing the blockchain today with beta 27 but i have been getting this error since

**Comment by beykovskyb** [comment]
@mariano54

**Comment by mariano54** [comment]
Try force quitting the app, then restart your computer

**Comment by beykovskyb** [comment]
Hey Mariano!

Thanks for the reply.

here are the solutions ive attempted so far.

quit the app, restart computer
force quit the app, restart computer
uninstall the app, restart computer, reinstall app

I guess my next step seems like reinstalling my MACOS operating system but
I would like to try to avoid that if possible?

Regards,

Brendan

**Comment by berlef80** [comment]
Have had this happen as well in Beta27.  When I click "reload" on the plot or farm screens, it goes to the screen someone posted above where the wallet just hangs indefinitely.  I am plotting so don't want to shut down Chia and loose that work, but if there is a work around to get back to the farm or plot screen, without shutting down, that would be helpful.

**Comment by beykovskyb** [comment]
Last login: Thu Feb 18 10:11:34 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Applications/Chia.app/Contents/MacOS/Chia ; exit;
Brendans-MBP:~ brendanbeykovsky$ /Applications/Chia.app/Contents/MacOS/Chia ; exit;
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon
true
Running python executable: 
child process success
No cert
Chia directory /Users/brendanbeykovsky/.chia/beta-1.0b27
/Users/brendanbeykovsky/.chia/beta-1.0b27 already exists, no migration action taken
No cert
Have cert
Daemon server started
stderr: Traceback (most recent call last):
  File "src/server/start_full_node.py", line 64, in <module>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "aiosqlite/core.py", line 109, in run
  File "asyncio/base_events.py", line 764, in call_soon_threadsafe
  File "src/server/start_full_node.py", line 59, in main
  File "asyncio/base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "src/server/start_service.py", line 208, in run_service
  File "aiosqlite/core.py", line 117, in run
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 764, in call_soon_threadsafe
  File "asyncio/base_events.py", line 508, in _check_closed
  File "asyncio/base_events.py", line 616, in run_until_complete
RuntimeError: Event loop is closed
stderr:   File "src/server/start_service.py", line 202, in async_run_service
  File "src/server/start_service.py", line 147, in run
  File "src/server/start_service.py", line 118, in start
  File "src/full_node/full_node.py", line 104, in _start
  File "src/full_node/block_store.py", line 27, in create
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.DatabaseError: database disk image is malformed
stderr: [2203] Failed to execute script start_full_node
stderr: Traceback (most recent call last):
  File "src/server/start_wallet.py", line 92, in <module>
  File "src/server/start_wallet.py", line 87, in main
Exception in thread Thread-2:
Traceback (most recent call last):
  File "aiosqlite/core.py", line 109, in run
  File "src/server/start_service.py", line 208, in run_service
  File "asyncio/base_events.py", line 764, in call_soon_threadsafe
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 508, in _check_closed
  File "asyncio/base_events.py", line 616, in run_until_complete
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "src/server/start_service.py", line 202, in async_run_service
  File "aiosqlite/core.py", line 117, in run
  File "src/server/start_service.py", line 147, in run
  File "asyncio/base_events.py", line 764, in call_soon_threadsafe
  File "src/server/start_service.py", line 118, in start
  File "asyncio/base_events.py", line 508, in _check_closed
  File "src/wallet/wallet_node.py", line 146, in _start
RuntimeError: Event loop is closed
stderr:   File "src/wallet/wallet_state_manager.py", line 117, in create
  File "src/wallet/wallet_coin_store.py", line 26, in create
  File "aiosqlite/core.py", line 184, in execute
  File "aiosqlite/core.py", line 129, in _execute
  File "aiosqlite/core.py", line 102, in run
sqlite3.DatabaseError: database disk image is malformed
stderr: [2202] Failed to execute script start_wallet

**Comment by dorkmo** [comment]
how long are you guys waiting on the "connecting to wallet" screen? i feel like ive had to wait a long time before

**Comment by beykovskyb** [comment]
I will do an experiment and get back to you!

**Comment by beykovskyb** [comment]
> how long are you guys waiting on the "connecting to wallet" screen? i feel like ive had to wait a long time before

Been trying to connect for 10 minutes now

**Comment by beykovskyb** [comment]
> how long are you guys waiting on the "connecting to wallet" screen? i feel like ive had to wait a long time before

Have had it trying for an hour solid now. no change

**Comment by dorkmo** [comment]
any luck on rc2 today?

**Comment by beykovskyb** [comment]
Nope it's been trying to connect the wallet for 24hrs plus. Considering
reinstall is unless developer says otherwise

**Comment by beykovskyb** [comment]
*reinstall operating system

**Comment by dorkmo** [comment]
new software update came out this morning so maybe try to reinstall chia

**Comment by beykovskyb** [comment]
Will do, thanks!

**Comment by beykovskyb** [comment]
Bug fixed, thanks all for your tech support and assistance

**Comment by DarrellBrogdon** [comment]
I'm seeing this on 1.0.0

**Comment by baccredited** [comment]
I'm seeing this on 1.0 as well. Chia 1.0.0 on a fresh installed macOS Sierra 10.12.6

I've never installed Chia before, so shouldn't be a collision with old installs. 

Just getting:
Connecting to wallet

With the spinner icon, which never stops.

**Comment by baccredited** [comment]
Quick note on this bug, they really mean it when chia says this:
MacOS Mojave (10.14.x) or newer is required.
https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#MacOS

I was trying to run chia on an older, fully patched High Sierra mac and was getting this 'connecting to wallet' bug.

I installed the software on a newer 'Big Sur' mac and it started immediately.

**Comment by webzsolution** [comment]
@baccredited - I am on Big Sur and I am seeing this. After working well for a few days, starting to see this after an OS update. Restarted and loaded Chia and the issue has persisted for a day. Left it overnight to find it this morning still attempting a connection.

I don't think Big Sur is immune to this. At least not from my experience.

**Comment by DarrellBrogdon** [comment]
I'm running Catalina on a 15" mid-2021 Retna MacBook Pro.  I should have mentioned that.

However, the app did run at first.  My Mac crashed and when I started Chia up after restarting it gives me the "Connecting" screen.  I'm not sure if the crash is related to Chia or not.  Catalina hasn't been all that stable for me and I've had to purposely restart about once a week since installing it.

**Comment by vegaro** [comment]
I am having the same issue on 1.0.0. I had a kernel panic, the Mac restarted and now I get `sqlite3.DatabaseError: database disk image is malformed` and it stays as `Connecting to wallet`.

**Comment by hoffmang9** [comment]
@vegaro Start by deleting your wallet database in `~/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_NUMBER.sqlite` and then start the Chia app to see if it will come up.

**Comment by ZwaZo22** [comment]
same problem with version 1.0.1 here on macOS Catalina.

If I delete the wallet database the problem persists with the full node page 

![Capture d’écran 2021-03-28 à 20 41 17](https://user-images.githubusercontent.com/47155095/112763770-2e8b0b80-9006-11eb-96cd-30b1c997c682.jpg)

**Comment by ZwaZo22** [comment]
Actually, the only way I found to get the control back, is to delete :

- blockchain_v1_mainnet.sqlite blockchain_v1_mainnet.sqlite
- blockchain_wallet_v1_mainnet_NUMBER.sqlite

restart and resync.

Hope there is another easier solution.

Best regards,

**Comment by dominik-zisch** [comment]
> Actually, the only way I found to get the control back, is to delete :
> 
>     * blockchain_v1_mainnet.sqlite blockchain_v1_mainnet.sqlite
> 
>     * blockchain_wallet_v1_mainnet_NUMBER.sqlite
> 
> 
> restart and resync.
> 
> Hope there is another easier solution.
> 
> Best regards,

Bit of an ignorant questions, but i cannot seem to find these files. I've searched but to no avail. Can you point me to the file locations please?

thanks

**Comment by papiblock** [comment]
> > Actually, the only way I found to get the control back, is to delete :
> > ```
> > * blockchain_v1_mainnet.sqlite blockchain_v1_mainnet.sqlite
> > 
> > * blockchain_wallet_v1_mainnet_NUMBER.sqlite
> > ```
> > 
> > 
> > restart and resync.
> > Hope there is another easier solution.
> > Best regards,
> 
> Bit of an ignorant questions, but i cannot seem to find these files. I've searched but to no avail. Can you point me to the file locations please?
> 
> FYI, am on macOS Catalina
> 
> thanks

yeah i second this question. seems that we have to delete the wallet DB but i am not sure where to locate them. i've opened up "package content" but do not see any files in there like that. Anybody here that can help find those on mac? Thanks!

**Comment by hoffmang9** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-is-my-wallet-not-synced-why-can-i-not-connect-to-wallet-from-the-gui

**Comment by papiblock** [comment]
> https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#why-is-my-wallet-not-synced-why-can-i-not-connect-to-wallet-from-the-gui

thanks - i do not know how to find this folder: ~/.chia/mainnet/wallet/db folder

**Comment by papiblock** [comment]
ok whoever is reading further here, on mac go do finder then comd+shift+G and type-in "~/.chia/mainnet/wallet/db" this will take you to db folder that you can delete.

**Comment by danra** [comment]
Anyone reading this - do *not* remove the `db` folder completely, or you'll keep getting the "malformed database" error.
Only remove its contents.

**Comment by DeXtmL** [comment]
None of the above methods work. v1.0.5

To reproduce,
1. Get a new PC
2. open chiaSetup-1.0.5
3. click new private key
4. close chia 
5. open chia again.
6. Observe that your wallet is forever connecting...

**Comment by MadCoderOne332** [comment]
I get this as well today, Windows 10

**Comment by simlshady** [comment]
> None of the above methods work. v1.0.5
> 
> To reproduce,
> 
> 1. Get a new PC
> 2. open chiaSetup-1.0.5
> 3. click new private key
> 4. close chia
> 5. open chia again.
> 6. Observe that your wallet is forever connecting...
> 
> ** Update: solved mine: port 55400 is occupied.
> Chia should give more detailed error msg.

Tell me Sir, how did you change the port? Or how did you repair it.

**Comment by chiauserrich** [comment]
Same issue. I have 20 plots plotted and have been farming for weeks. Now stuck on "connecting to wallet"...

think it may have something to do with Mac Big Sur update. 

I've deleted Chia and reinstalled. Nothing noted in this thread has worked for me. 

issue persists.

**Comment by ryancraigmartin** [comment]
Have never been able to get past Connecting to wallet on High Sierra.

**Comment by hoffmang9** [comment]
As the documentation says, the oldest MacOS this supports is Mojave.

**Comment by PSiKoTiC** [comment]
> Same issue. I have 20 plots plotted and have been farming for weeks. Now stuck on "connecting to wallet"...
> 
> think it may have something to do with Mac Big Sur update.
> 
> I've deleted Chia and reinstalled. Nothing noted in this thread has worked for me.
> 
> issue persists.

Just 'fixed' it had to close the chia program and rebuild block chain and nuke my C:\Users\Owner\.Chia directory Delete this and rerun the Chia executable Wallet will reconnect, need to repoint to plots but it gets going again..

**Comment by MadCoderOne332** [comment]
I would like to add that I see on the Trello board that this is perceived
as a Mac issue. I have this issue on Windows 10 latest build periodically

**Comment by lobabob** [comment]
Have the issue on windows 10 latest build as well.

**Comment by FreeDooMF1** [comment]
> Have the issue on windows 10 latest build as well.

Same thing... still no fixes?

**Comment by ril3y** [comment]
> Have the issue on windows 10 latest build as well.

Same issue.

**Comment by FreeDooMF1** [comment]
> > Have the issue on windows 10 latest build as well.
> 
> Same issue.

full reinstall chia, delete all hiden folders, restart ur pc and then install chia again - works for me

**Comment by NessDan** [comment]
This is an issue on 1.1.2

![image](https://user-images.githubusercontent.com/304269/116774336-f7a37d80-aa29-11eb-9c89-8ebd5c865b87.png)

**Comment by sport174** [comment]
У меня такая же штука не знаю как решит

**Comment by sport174** [comment]
![Uploading 20210501_235723.jpg…]()

**Comment by luijocroussett** [comment]
> This is an issue on 1.1.2
> 
> ![image](https://user-images.githubusercontent.com/304269/116774336-f7a37d80-aa29-11eb-9c89-8ebd5c865b87.png)

Were you able to solve it without closing the application? I am currently plotting and dont want to lose those plots.

**Comment by olegolegoleg** [comment]
Same on 1.1.4:
![image](https://user-images.githubusercontent.com/7686755/117138041-341d0380-adb3-11eb-93ed-ac152a10bb5e.png)

**Comment by cdias900** [comment]
I tried to full reinstall chia, delete all hiden folders, restart my pc and then install chia again, but none of that worked. The real cause of this issue, at least in my case, whas Hyper-V reserving a port range that included the port used by chia (To check if this is the case, just run `netsh interface ipv4 show excludedportrange protocol=tcp` on cmd and see if there is any range reserved that includes port 55400). 
In order to solve it, I just had to disable Hyper-V (`dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` on cmd, the pc will reboot right after the command), reserve a range that included port 55400 running `netsh int ipv4 add excludedportrange protocol=tcp startport=55300 numberofports=200` (You probably can reserve less ports, but I ran the command like this just to make sure it would work) and then enable Hyper-V again (`dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All` the pc will reboot after the command).
After doing all that, the GUI started working again.

**Comment by leopucci** [comment]
> I tried to full reinstall chia, delete all hiden folders, restart my pc and then install chia again, but none of that worked. The real cause of this issue, at least in my case, whas Hyper-V reserving a port range that included the port used by chia (To check if this is the case, just run `netsh interface ipv4 show excludedportrange protocol=tcp` on cmd and see if there is any range reserved that includes port 55400).
> In order to solve it, I just had to disable Hyper-V (`dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` on cmd, the pc will reboot right after the command), reserve a range that included port 55400 running `netsh int ipv4 add excludedportrange protocol=tcp startport=55300 numberofports=200` (You probably can reserve less ports, but I ran the command like this just to make sure it would work) and then enable Hyper-V again (`dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All` the pc will reboot after the command).
> After doing all that, the GUI started working again (1.1.4).

Solved on Windows 10 with version 1.1.3, i did not changed a thing, did not deleted anything. 
The only modificiation that I did was on the ports as described by @cdias900 
The Connecting to wallet screen is gone. Everything working.

**Comment by cdnkrypto** [comment]
![Chia Error](https://user-images.githubusercontent.com/83691425/117200249-4863ff00-adb9-11eb-8f7f-9d688cd4c6e4.JPG)

**Comment by cdnkrypto** [comment]
After the PC reboot I still had the same issues

**Comment by olegolegoleg** [comment]
I've discovered that in my case this is somehow connected with "Keys" tab:
![image](https://user-images.githubusercontent.com/7686755/117269010-91bb5980-ae60-11eb-9fb9-8333cef02d7d.png)

If I clicked on it, the new popup hides all other controls and it is impossible to close it or go back!

If I click "View->Reload" or "View->Force Reload":
![image](https://user-images.githubusercontent.com/7686755/117269314-dba43f80-ae60-11eb-9270-0cd789a2a67c.png)

Then I got: this annoying:
![Screenshot 2021-05-05 150452](https://user-images.githubusercontent.com/7686755/117269463-f5de1d80-ae60-11eb-8de7-f993e8ea45b7.png)

The restart helps in 30%, since as usual it starts on "Keys" tab again. 

The solution in my case: clicking randomly on the background of the keys tab or on the keys values and in 1m the other parts of the window shows up!

**Comment by cdnkrypto** [comment]
So the fix for me was in this order 
1. Shut down Chia
2. Use "Task Manager" to end task for Chia & all related like "Start Mode"
3. Delete .Chia folder under the user profile
4. Reboot computer 
5. Fresh install of Chia 1.1.4

**Comment by Ninacolas** [comment]
Hola, sigo sin poder conectar, me figura conectando al monedero.

**Comment by jbwoods14** [comment]
FIXED FOR ME.
I had this issue on Windows 10, both version 1.15 and 1.14.
Deleting appdata directories didnt help, restarts, force restarts, reboots, reinstalls.
The fix was to go into credential manager, scroll down to keychains, delete the Chia one.

I had uninstalled, so the next step was to install, and it immediately asked me if I wanted to create a new, or type out the words.

**Comment by UnitMK23** [comment]
@jbwoods14 thanks a lot man, this solved the issue for me as well. Had already given up hope for this PC!

**Comment by jbwoods14** [comment]
Awesome to hear!!!!

**Comment by glennposadas** [comment]
MAC Big Sur USER here.

I got stuck at 31%, and the log didn't move for a loooong hours, maybe around 5-7 hours. I quit the app, and restarted my MacBook, didn't help.

I deleted Chia app data:

The '.chia' folder in the user folder
The 'Chia Blockchain' folder in the 'Application support' folder

And then I was able to restart the app from the beginning, had to enter my seed phrase.

But I'm afraid my effort in plotting is now gone :/ Status: not available.

**Comment by suiri573035185** [comment]
![Uploading _20210516080348.png…]()

**Comment by suiri573035185** [comment]
same issue in 1.1.5

**Comment by suiri573035185** [comment]
how to fix it without shutting chia gui down plz

**Comment by nyfirebuff** [comment]
I don't know if it's the right way but it worked for me... This route may, actually it most certainly will delete any current plotting but not your plots already created. I know it deleted my few I had started but I believe this is the only route as that the plotting itself gets corrupt. And the program can't restart because of the corrupt plots. Seems this is the only solution... At least for me. 

Just delete the ".Chia" folder under local disk (C) \ Users (your username). If it won't let you delete it then it's still running in background. Go to task manager and end any and all task running anything Chia. Then you should be able to delete the .chia folder. Once you delete the .Chia folder, Emtpy recycle bin, then Uninstall Chia GUI program. Reinstall Chia GUI.. you shouldn't have to enter your key phrase but double check it's still correct. Then just re-add your plot directories under the plot tab. Everything synced back up for me with no issues.

Let me know if this helped anyone else.

**Comment by jamesalmeida** [comment]
I've had this problem with a mac and a pc. Both of them eventually get this error and I have to shut it all down and now they just hang for over 24hours… About ready to give up on Chia.

**Comment by sinzin91** [comment]
I ran into this as well.

I noticed an error "getaddrinfo ENOTFOUND localhost" in the console logs, so I added the line `127.0.0.1 localhost` to `/etc/hosts` and it worked after restart at that point.

**Comment by kittinzaa** [comment]
tried all the fix in the comment still cannot solve this.

**Comment by davecarter** [comment]
> @vegaro Start by deleting your wallet database in `~/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_NUMBER.sqlite` and then start the Chia app to see if it will come up.

Thank you so much! It fixed my issue.

**Comment by jredner** [comment]
fwiw on Mac, I just shut down Chia app, renamed .chia to .chia.corrupt, restarted Chia app, added the Plots folder under Farm section and I'm back.

**Comment by xazes** [comment]
same issue nothing works .

**Comment by realdevnullius** [comment]
still bugging me on windows with 1.1.6 :(

**Comment by generalissimo3** [comment]
I am also still having this issue on windows with version 1.1.7

**Comment by simlshady** [comment]
Since I only have one farmer /plotter in the network it runs without this bug. For info, i have ubuntu 18.04, port forwarded in my router and upnp enabled

**Comment by ElBiasto** [comment]
Same issue on 1.1.7

**Comment by korolevsv** [comment]
Same issue on 1.1.7 / Windows

**Comment by imangift** [comment]
You can download the Chia database here

https://github.com/chia-database

The download link is in the Radme file

**Comment by craig0100** [comment]
> I tried to full reinstall chia, delete all hidden folders, restart my pc and then install chia again, but none of that worked. The real cause of this issue, at least in my case, was Hyper-V reserving a port range that included the port used by chia (To check if this is the case, just run `netsh interface ipv4 show excludedportrange protocol=tcp` on cmd and see if there is any range reserved that includes port 55400). In order to solve it, I just had to disable Hyper-V (`dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` on cmd, the pc will reboot right after the command), reserve a range that included port 55400 running `netsh int ipv4 add excludedportrange protocol=tcp startport=55300 numberofports=200` (You can probably reserve less ports, but I ran the command like this just to make sure it would work) and then enable Hyper-V again (`dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All` the pc will reboot after the command). After doing all that, the GUI started working again (1.1.4).

This worked for me.  Thank you so much.  This should be added to the official documentation for chia and clones.
