### ISSUE TITLE
v1.2.7 Ubuntu Does Not Show Version Number in help\about chia blockchain[BUG]

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#8650]
**Describe the bug**
I have recently updated to version 1.2.7 using the preferred instructions noted here: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian
After installation the GUI no longer shows the version number under help\about chia blockchain:

![Screenshot from 2021-09-30 13-04-51](https://user-images.githubusercontent.com/48610606/135515677-a34664d2-dda0-406c-b89c-4a25cf3420c1.png)

**To Reproduce**

1. Updated Chia to 1.2.7 (following instructions: https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian)
2. Started Chia GUI per instructions
3. Clicked on Help\About Chia Blockchain
4. Version number is now 0.0 (all previous version this was correct)

**Expected behavior**
Correct version number should be listed in the about (i.e. 1.2.7 for this instance)

**Screenshots**
![Screenshot from 2021-09-30 13-04-51](https://user-images.githubusercontent.com/48610606/135515677-a34664d2-dda0-406c-b89c-4a25cf3420c1.png)

**Desktop**

- OS: Linux
- OS Version/Flavor: Ubuntu 20.04.3 LTS
- CPU: AMD® Ryzen threadripper 3990x 64-core processor × 128 

**Additional context**
NA, the above should have all necessary info. Let me know if there are any questions or specific logs that should be reviewed!
Thank you all!

**Comment by emlowe** [comment]
I assume you mean you used the git clone steps and not the deb installer

Do you have a version field at the bottom of `chia-blockchain-gui/package.json`?

If not go into the chia-blockchain venv (`source ./activate`) and run `python installhelper.py`

**Comment by BrandtH22** [comment]
Yes, I followed the steps from that link under the section: "To Update/Upgrade from previous version"
I do not see a version field within that .json file but the .json file does exist contrary to the error I received when running python installhelper.py:

:~/chia-blockchain$ python installhelper.py
Traceback (most recent call last):
  File "installhelper.py", line 65, in <module>
    update_version()
  File "installhelper.py", line 50, in update_version
    with open(f"{os.path.dirname(__file__)}/chia-blockchain-gui/package.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/chia-blockchain-gui/package.json'

Screenshot showing package.json in gui folder
![Screenshot from 2021-09-30 15-14-09](https://user-images.githubusercontent.com/48610606/135531170-6f2141c1-8dc8-40ef-882c-77c4e889a8c8.png)
:

**Comment by emlowe** [comment]
interesting, it seems the script is failing to put in the proper directory with `os.path.dirname(__file__)`

**Comment by emlowe** [comment]
what version of python?

**Comment by BrandtH22** [comment]
Python 3.8.10
Is there a way another to update the directory reference?

**Comment by emlowe** [comment]
not with that script, it's not particularly clever. You can always add the version yourself to package.json if you want.

```
{
    "name": "chia-blockchain",
    "version": "1.2.7",
    "author": "Chia Network <hello@chia.net> (https://chia.net/)",
}
```

**Comment by BrandtH22** [comment]
Well just retried the update (since 1.2.8 has been released). The version identifier has been updated to 1.2.7!!!
I will close out, thank you for the assistant and explanations!
