### ISSUE TITLE
Chia 1.2.8 Updates to 1.2.6dev67 ..

### ISSUE THREAD

**Issue by ArIulzZz** [Chia-Network/chia-blockchain#8658]
Im running Ubuntu and Windows 10 as well and both of them are the same ..
Ubuntu - git fetch
               git checkout latest
               git reset --hard FETCH_HEAD --recurse-submodules
               cd chia-blockchain-gui
               git fetch
               cd ..
               chmod +x ./install-gui.sh
               ./install-gui.sh

Windows 10 - Setup File was downloaded from official website .

**Comment by loppefaaret** [comment]
yup, its somehow snuck itself in there... 
`chia version` from CLI should report 1.2.8 as expected
so far, we see this:
```
Mac DMG: GUI incorrect says 1.2.6dev67
Windows: GUI incorrect says 1.2.6.dev67
Ubuntu DEB: Correct
Redhat RPM: Correct
Linux manual install: Correct 
```

**Comment by ogunkakisim** [comment]
same problem

**Comment by ogunkakisim** [comment]
I wish they would check before release the GUI. very simple mistake.

**Comment by Magicwalker** [comment]
Build the code without checking .. can it more becareful .. we are farming

**Comment by ArIulzZz** [comment]
No still the Same , Ubuntu and Windows as well !
Shows 1.2.6dev67 and there's no new translations to GUI which means its NOT the new version ..
can someone take a look on this release ? y'all released new version i removed the old one and since this issue my farmer is down for almost 10 hours .....

**Comment by loppefaaret** [comment]
> No still the Same , Ubuntu and Windows as well ! Shows 1.2.6dev67 and there's no new translations to GUI which means its NOT the new version .. can someone take a look on this release ? y'all released new version i removed the old one and since this issue my farmer is down for almost 10 hours .....

Perhaps on ubuntu, you could try and close down all chia services, and `deactivate` out of any running (venv), and then complete:
```
sh install.sh

. ./activate

chia init
```
Are your Windows machine also down ?

**Comment by ArIulzZz** [comment]
I’ve done everything ..
Both of them Ubuntu and windows are popping the same version - 1.2.6dev67 .
On top of that all the new translations doesn’t appear on gui .
Can you release fix version ?

**Comment by emlowe** [comment]
You need to check `chia version` from the command line - if it says 1.2.8 you are ok. On Windows you can also check the file version of Chia.exe (right-click->properties) - it will also say 1.2.8

If you install the DEB on ubuntu - it will say the correct thing 1.2.8.
