### ISSUE TITLE
unspent transaction[BUG]

### ISSUE THREAD

**Issue by Cordy82** [Chia-Network/chia-blockchain#8680]
hello everyone, this is the second time I have the problem that a transaction gets unspend status.
Wallet and blockchain sync.

Normal it work.

Coin
Date
10/02/2021, 01:35:01 AM
Puzzle hash
0xe98df05ce8d7f082980f2d7cfc6d29ad718dcede38804b2cad7730e5f3cd3edd
Address
xch1axxlqh8g6lcg9xq09470cmff44ccmnk78zqykt9dwucwtu7d8mwsw7m7tc
Amount
0.6957 XCH
Current value
$ 114.04
status
Unspent
Type
🍃 Miscellaneous
Confirmed block index
938,679
Spent block index
0
Parent coin info
0x129b9a8c419159ca3ea167fb205ad12eaced112f0890d3184387251b8f60f209

it is a farmed xch from spacepool with recipient address bibox
the credit is deducted in the gui, bibox is waiting for the 12 validations but is all the time 0/12 (normaly in under 1 min validatet

the block seems to have been farmed by the hpool (25% of last 100 blocks)
can someone bring light into the dark

tech: Chia client 1.2.8 (was at that moment the highest version, now updatet to 1.2.9)
win10 on pc

![Screenshot_20211002-101723_Bibox](https://user-images.githubusercontent.com/91777243/135726153-8784a037-f0b9-48ce-af70-02f754d568e2.jpg)
![Screenshot_20211002-101745_Bibox](https://user-images.githubusercontent.com/91777243/135726157-894aa63d-af45-4aa3-8fab-3058fc68f311.jpg)

Here is the second one in the past where i send to my partner with same problem

Txn Hash
0x159c554e64d1dec9fce3f85e96fa0deefc272e6018b0ab96e2b779dc60b00c15
Status
Success - Unspent
Block
850,214
Timestamp
20 days ago (Sep-12-2021 19:22:27 PM) +UTC
Value
0.7 XCH ($112.24)
XCH Price
$213.05 / XCH
From
xch1d3agqjv9vff5j8y9h6lvrp2edapeecpepmylttw2qkjqtra504uqk5xwln
To
xch138kkqxhunc2ejdpvuv2z4ahasmq96l9a4u0jfhl7tlgcl2dcjerqwvtszv
Type
Transaction

Thanks for help
best regards Cordy82

**Comment by Cordy82** [comment]
Blockchain and wallet was and is sync

**Comment by Cordy82** [comment]
![Screenshot_20211002-101723_Bibox](https://user-images.githubusercontent.com/91777243/135709091-49ec789b-0a31-4816-b63d-61d65f9d3c89.jpg)
![Screenshot_20211002-101745_Bibox](https://user-images.githubusercontent.com/91777243/135709093-79f4122f-7020-4d2e-ace3-eb13c5d36e25.jpg)

**Comment by Cordy82** [comment]
Here is the second one in the past to my partner
Txn Hash
0x159c554e64d1dec9fce3f85e96fa0deefc272e6018b0ab96e2b779dc60b00c15
Status
Success - Unspent
Block
850,214
Timestamp
20 days ago (Sep-12-2021 19:22:27 PM) +UTC
Value
0.7 XCH ($112.24)
XCH Price
$213.05 / XCH
From
xch1d3agqjv9vff5j8y9h6lvrp2edapeecpepmylttw2qkjqtra504uqk5xwln
To
xch138kkqxhunc2ejdpvuv2z4ahasmq96l9a4u0jfhl7tlgcl2dcjerqwvtszv
Type
Transaction

**Comment by loppefaaret** [comment]
The software you are providing screenshot from - what is that ? that is not from Chia Network ?
the transaction went through fine, as you can see on a blockexplorer - perhaps you need to contact whoever is providing you with software that incorrectly shows you 0/12 conformations ? 
it might be that their program somehow got the wrong txhash of the transaction, i can see it here:
https://xchscan.com/txns/0xa82dfafdd9561331dfca5dd797f4f2b650c26a9d9d37d4edc69a4e4eb10d43bc
but the program is showing something else as "txid" ? that is assuming that "txid" is "tx hash"
https://xchscan.com/txns/0x29cadc950f5c0a544e6f8fb58852ee6f90d145f13e1cba2a4adc6ed2ea368529
leads to unknown tx hash

**Comment by Cordy82** [comment]
the software from other side is from bibox exchange. The answer from their support: Because XCH has two hashes. The system may sometimes scan a hash that is not a transaction.

They changed it manually and within seconds the credit was posted.

Thank you for your quick and effective answer ;)
