### ISSUE TITLE
1.2.8 network shared drive not connecting [BUG]

### ISSUE THREAD

**Issue by Tianxinya2021** [Chia-Network/chia-blockchain#8716]
Hi:

I have two win10 computers within home network and each has 12 internal hard drives. Instead of running harvest/farm on both, I run a full node on one, say, PC1, and have disk folders shared in another, say PC2. PC1 has mapped drives on those shared folders from PC2. It appears PC1 has no problem using the plots from shared folders in PC2 for the past months. However, when I 'upgraded' to 1.2.8, PC1 chia full node does not show any of the shared plots in PC2 (in plot, farm, pool). No matter how I tried, refreshed, it did not work. I had to switch back to 1.2.6 and all the shared plots in PC2 appeared fine again in PC1 full node.
Hope the team can find time to fix this. Thanks for your hard work.

**Comment by emlowe** [comment]
If you have two computers, you should run the full node + farmer on one (PC1) and a remote harvester on the other (PC2) - there is no need to map the drives across the network as this is likely to introduce unwanted latency.

I have no idea what other problems you might be having. I'm closing this issue.
