### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nagendra129** [Chia-Network/chia-blockchain#8721]
Hi sir,
our chia mining Full node status SYNCED 
since WALLET STATUS **SYNCING (949738)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by shaneo257** [comment]
this is normal behaviour of the node/wallet
the wallet will lag behind the node getting sync, eventually it will catch up

**Comment by Nagendra129** [comment]
Thanking you sir

**Comment by Nagendra129** [comment]
Thanking you sir,
Nagendra (INDIA)
