### ISSUE TITLE
incorrect harvester message related to sub-directories

### ISSUE THREAD

**Issue by Hardcore-fs** [Chia-Network/chia-blockchain#8733]
How can it be "searching directories" and "not checking directories" at the same time?
![plotting](https://user-images.githubusercontent.com/1309004/136102896-3e73de98-4622-4963-8211-609c3d3b5ecf.jpeg)

latest version as of today.

**Comment by jack60612** [comment]
> How can it be "searching directories" and "not checking directories" at the same time? ![plotting](https://user-images.githubusercontent.com/1309004/136102896-3e73de98-4622-4963-8211-609c3d3b5ecf.jpeg)
> 
> latest version as of today.

it wont go recursively according to that error message 
so if your plots are at /plots it wont go to /plots/old and only go to /plots

**Comment by jack60612** [comment]
> clearly you are not reading the messages. it says "searching" ALL 3, becasue they were added separately. Then it says "not checking", it cannot do both, it is a code clash, due to it hitting the "../final" then finding sub-directories. printing messages related to that sub-directory, instead of having an exclusion array of the other added directories then doing a compare to see if they exist in the current scan addition.
> 
> it would be as simple as building an array of all ADDED directory paths, then any ADDED subdirectory that is IN that array , excluding it from the "not checking sub-directory print"

This might be a log bug but it should not affect functionality at all so this would be a pretty low priority issue anyway.
Thanks for the report

**Comment by Hardcore-fs** [comment]
it started out in a docker container
with a single directory:
chia plots add -d /mnt/chia-plots/final

But since it means you have to completely rebuild the docker container if you want to change the paths, so i left it alone.

and instead use:

chia plots add -d /mnt/chia-plots/final/NFS-Plots2
chia plots add -d /mnt/chia-plots/final/NFS-Plots

to add the extra directories, on a restart.

the message is a result of this action, where the paths are added, but the code logic lacks fore thought....
