### ISSUE TITLE
newest update connecting issue [BUG]

### ISSUE THREAD

**Issue by demoniac80** [Chia-Network/chia-blockchain#8747]
Newest update 1.2.9 - 2021-10-01 causing connection to wallet issue.  It just sits there and does the wheel of uselessness.  Looks like the old uninstall/reinstall must be done.

**Comment by cornclose** [comment]
Serious issues on 1.2.9 for me. Several blue screens and crash dumps on Windows and subsequent failures to sync - just spinning circles after a while. Often with failures to load the GUI and be able to select a key. If I can get that far, fails to load the GUI even after a force reload. More crashes and more likely corruption to the database files results in the cycle repeating. I delete the DB files and start a sync from scratch and the same issues occur over again. I’ve reverted back to 1.2.7 and it’s syncing fast and stable now and over half way done in 6 hours.

Something is wrong with 1.2.9 folks..

**Comment by demoniac80** [comment]
Yeah this is taking forever to sync 104k/900K after 2hrs.  Looks like this wasn't tested properly and released half-baked.  Amazingly  I'm still currently plotting while at a snails pace syncing.
