### ISSUE TITLE
1.2.9 Farming just randomly stop receiving challenge

### ISSUE THREAD

**Issue by cyclipse** [Chia-Network/chia-blockchain#8770]
Ever since I upgraded to version 1.2.9 (from 1.2.2), I am having this farming randomly stopped issue. It happens once every 1/2 days, and the way I spotted the issue is the NFT pool graph went flat, then when I check on the challenge received, it was stucked since few hours back (for eg, today when I check on 9.30AM, the last challenge is on 4.40am). Please fixed this issue as we are seriously wasting the resources when its stucked and its indeed makes the farming a hassle to check the challenge every few hours.

**Comment by loppefaaret** [comment]
We would love to fix it, but perhaps you could help us out a bit ?
What Opeerating System and its version are you experiencing this issue on ?
What version of Chia are you using ? 
Can you give a short description of the size and layout of your setup ? are you using 4 drives in the same system ? 70 remote harvesters for a total of 10+PB ? 
And most importantly, you `debug.log` found under your users folder `~\.chia\mainnet\log\` - if you dont want to post it online here, you are welcome to either email to rc 'at' chia.net - or come on to our official chat on https://keybase.io/team/chia_network.public where you can DM me @pyl securely
if you are able to turn on DEBUG and get the issue caught with it on, that would be gold!

**Comment by cyclipse** [comment]
Hi,

If that the case, should I do anything with the plots showing in ERROR?
And after I see this message and I inspect the latest debug.log, I discovered this error message, does it matter in any way?
![image](https://user-images.githubusercontent.com/16812698/136772153-0715565b-3ff5-417a-b347-e0a0a53c93be.png)
![image](https://user-images.githubusercontent.com/16812698/136772331-7b120490-18f1-49ff-95b4-def591297c25.png)

Thanks and best regards.

**Comment by cyclipse** [comment]
Hi,

I try to inspect all the logs, and at the time of failure, the only error log I can see is from the harvester none other than the harvester (ignore the error on 1.55am as it is not network nor chia related, and it is way further after the harvester crashed).
![image](https://user-images.githubusercontent.com/16812698/137057367-7c8fad1d-51a4-430e-889c-9ca704cd08dc.png)

![image](https://user-images.githubusercontent.com/16812698/137057379-a630434b-24ae-4032-9864-6bf2a2b1d2ee.png)

![image](https://user-images.githubusercontent.com/16812698/137057386-ed4e155e-842f-4667-acc2-62276cfe6f98.png)

and thanks for the advice, I will try to run the check and tidy up the plots.

Thanks and best regards.

**Comment by loppefaaret** [comment]
yeah, that leaves us with ensuring your plots are good, i think your harvester might hit a bad plot that causes it to crash

**Comment by loppefaaret** [comment]
that is spacepool not supporting the farmer /PUT command - it shouldnt have any negative effect on farming

**Comment by cyclipse** [comment]
I would say the issue still persist, and the last time it shown up is 3 hours ago.
I had tried to run the plot check, however the result shows otherwise.

After some observation, it seems like "bad plot" was always in the drive where plotting happens, and since I am plotting to the external hard drive, I am guessing the harvester most likely hit a timeout while reading the plots in the drive, and at the same time the plotter writing the plots into the drive, and eventually killed by unhandled timeout exception.

In this case I would say kindly check what logic had been modified in these new versions as I had been doing this way since start, and don't have such issue until this specific version update.
