### ISSUE TITLE
[BUG] Scam!

### ISSUE THREAD

**Issue by gromran** [Chia-Network/chia-blockchain#8808]
since 7 month no one chia...
SCAM!

If you want to do something useful with your storage space where you get paid: use Storj

**Comment by maomingyang1314** [comment]
This is the consequence of capital speculation. Even pigs can fly to the sky. No need to care about this project anymore. There is no future. There is no technology but no team and no team.

**Comment by marssystems** [comment]
If you don't like this project, go and do something else.

**Comment by ByronAP** [comment]
Haahaaaaaa this is a funny thread
