### ISSUE TITLE
[BUG] Does not connect to wallet.....

### ISSUE THREAD

**Issue by mirkobossi** [Chia-Network/chia-blockchain#8833]
**Describe the bug**
When you open the CHIA 1.2.9 application, it keeps doing "connecting to wallet ..." and does nothing else ...
The application was opened and closed several times but remains on that screen without doing anything.
Does anyone know how to solve it,

Thank you so much

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by unixus404** [comment]
my wallet stopped connecting after installing KB5006670, I deleted KB5006670 and it worked

**Comment by mirkobossi** [comment]
> if you check your `debug.log` located under your users folder `~\.chia\mainnet\log\debug.log` - do you see any ERROR reported from the "wallet" service ?

When checking "debug.log" there is no record of anything since the last time I started correctly ... which was since 10/12/21 .... :(

**Comment by wojtekrogala** [comment]
Just had the sam issue. I renamed whole .chia folder. Run app again, and it was looking fine. So I closed it moved back old db and wallet folder. Not working. Moved db, started app again, and it started to syncing from scratch. Fortunately I have other instance which was only 6 days back with syncing, so I copied db and it's syncing right now.

**Comment by Morrison1968** [comment]
Good evening.
My error is:
2021-10-16T18:20:42.618 farmer chia.farmer.farmer         : ERROR    Exception in GET /farmer https://europe.ecochia.io, Cannot connect to host europe.ecochia.io:443 ssl:<ssl.SSLContext object at 0x000001F6F285A840> [getaddrinfo failed]

**Comment by loppefaaret** [comment]
> Good evening. My error is: 2021-10-16T18:20:42.618 farmer chia.farmer.farmer : ERROR Exception in GET /farmer https://europe.ecochia.io, Cannot connect to host europe.ecochia.io:443 ssl:<ssl.SSLContext object at 0x000001F6F285A840> [getaddrinfo failed]

if you are looking for support, i can recommend our offficial chat:
https://keybase.io/team/chia_network.public
or the discussions here on our github:
https://github.com/Chia-Network/chia-blockchain/discussions/support
it seems your farmer is unable to resolve the "europe.ecochia.io" URL at first sight ?
