### ISSUE TITLE
temp2 file should not be copied if final dir on same volume

### ISSUE THREAD

**Issue by cross** [Chia-Network/chia-blockchain#8847]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8846

<div type='discussions-op-text'>

<sup>Originally posted by **cross** October 16, 2021</sup>
In the less common case where temp dir, or at least temp2, is on the same filesystem as the final dir, rename should be used instead of copy.   Using chia 1.2.7 on linux, I started a plot as follows:
```
Starting plotting progress into temporary dirs: /data/chia/tmp and /data/chia/tmp
ID: [...]
Plot size is: 34
[...]
Final Directory is: /data/chia/plots/k34
Using 16 threads of stripe size 65536
```

On my system, `/data` is a large RAID array, so accepting the spindle contention, it's all on the same device.  But at the end of this plot, I see:
```
Approximate working space used (without final file): 1176.562 GiB
Final File size: 429.934 GiB
Total time = 135175.666 seconds. CPU (145.320%) Mon Oct 11 02:07:45 2021
Copied final file from "/data/chia/tmp/plot-k34-2021-10-09-12-34-<keyval>.plot.2.tmp" to "/data/chia/plots/k34/plot-k34-2021-10-09-12-34-<keyval>.plot.2.tmp"
Copy time = 1952.410 seconds. CPU (37.220%) Mon Oct 11 02:40:39 2021
Removed temp2 file "/data/chia/tmp/plot-k34-2021-10-09-12-34-<keyval>.plot.2.tmp"? 1
Renamed final file from "/data/chia/plots/k34/plot-k34-2021-10-09-12-34-<keyval>.plot.2.tmp" to "/data/chia/plots/k34/plot-k34-2021-10-09-12-34-<keyval>.plot"
```

Unless I'm mistaken, the 1952 seconds spent copying the final file should've been a `rename` operation, which would also eliminate the removal of the temp2 file.</div>

**Comment by cross** [comment]
I'd be happy to contribute a fix for this, but I'm having trouble finding where this copying is happening.  Searching the code for "Copied" or "final file" has unexpectedly failed me.

**Comment by loppefaaret** [comment]
The current design is issuing a copy, if the folder is not the exact same for both tmp2 and destination, even if on the same volume - you could point tmp2 to the destination instead of a tmp folder to circumvent the final copy - it would then do a rename instead

Ive labelled is as an enhancement request
