### ISSUE TITLE
[BUG] GUI Connecting to wallet...

### ISSUE THREAD

**Issue by TomekLBN** [Chia-Network/chia-blockchain#8854]
Problew with connect to chciablockchain  i open app and wait oabot 15minuts is not first time i cant open chiablockchain
![chiag](https://user-images.githubusercontent.com/84026721/137641579-90adddfa-a94d-49da-a353-182332749202.png)

**Comment by paulhainsworth-chia** [comment]
@loppefaaret any progress on this one? Looking to see if we should add to our engineering backlog.

**Comment by loppefaaret** [comment]
I lost track of this issue, and i apologies for that, but unless we get an actual `debug.log` as described above, i fear there isn't much we can do. As far as im aware, person have not contacted me through other suggested platforms
