### ISSUE TITLE
[BUG] Full Node saying "Not Synced"

### ISSUE THREAD

**Issue by fotomarker** [Chia-Network/chia-blockchain#8855]
I have a problem with synchronization. There is such a screen all the time (Not Synced).
 Please help.
![chiaproblem](https://user-images.githubusercontent.com/92713785/137687687-a4636609-321c-485d-9477-926d698535b5.jpg)

**Comment by mariano54** [comment]
```
2021-10-18T16:20:57.069 full_node chia.full_node.full_node: ERROR    sync from fork point failed err: UNIQUE constraint failed: coin_record.coin_name
```

Looks like a DB corruption issue. Probably deleting the full node DB will help with this.
