### ISSUE TITLE
[BUG]ERROR Loop exception in sync Was not able to add blocks 8000-8032. Traceback (most recent call last):

### ISSUE THREAD

**Issue by ShilohMy** [Chia-Network/chia-blockchain#8857]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

ERROR    Loop exception in sync Was not able to add blocks 8000-8032. Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 608, in sync_job
    await self._sync()
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 668, in _sync
    await self.batch_sync_to_peak(fork_height, peak)
  File "/home/chia/chia-blockchain/chia/wallet/wallet_node.py", line 565, in batch_sync_to_peak
    raise RuntimeError(f"Was not able to add blocks {start_height}-{end_height}")
RuntimeError: Was not able to add blocks 8000-8032

**Comment by loppefaaret** [comment]
this looks like it potentially is an ERROR entry from the wallet service ? is it repeating that error continuesly ?
could you include a few of the above entries - tell us what exactly is your issue ? what OS, Chia version and perhaps even a short description of the hardware you are running it on ?
