### ISSUE TITLE
[BUG] Plots/Farm/Pool tabs keep loading

### ISSUE THREAD

**Issue by crystal-way** [Chia-Network/chia-blockchain#8887]
Plots/Farm/Pool tabs keeps loading, but never loads. Tried to quit, restart pc, reinstall app. Nothing helps.
OS - W10.

Any ideas how to solve it?

**Comment by ZiRC0Ni0** [comment]
Same problem here:

https://ibb.co/tsPphLH

**Comment by crystal-way** [comment]
i thought maybe there is a better solution. I sync my chia software so many times because of various bugs  :| each time it takes ages to sync. Once completed, new bug arriving... :D :D :D

**Comment by crystal-way** [comment]
This is brilliant. 
I've deleted db, reinstalled chia, it took 2 days to sync. Then worked fine for 1 day, and now i have same story again Plots/Farm/Pool tab's keep loading but never loads. Unbelievable how bad a programmers are at chia.

**Comment by crystal-way** [comment]
So it took no more then 2 weeks. Today i have to restart the computer, so closed the program, restarted PC, and guess...  the crappy chia software can't load plots/farm/pool tabs again...

**Comment by crystal-way** [comment]
look's like your devs are totally losers...
