### ISSUE TITLE
[BUG] Memory leak in start_full_node.exe

### ISSUE THREAD

**Issue by endurance1968** [Chia-Network/chia-blockchain#8893]
Running a full-node under windows the memory consumption increases over time. Typically it is running using ~700MB. But sometime in incresases mem consumption in chunks. I cannot observe a constant growth. Typically 700,1000,1200, 1400, 1600MB jumps after just 1 week of runtime. It seems randomly increasing - I was no t able to relate it to any error log or similar.
After restart and resync done the full node is at ~700MB again typically for some days before starting to grow...

Start Chia Fullnode via GUI. Let it run for approx a week. 
I have several harvesters connected as well as the full node is harvesting. 6 pools are feeded with partials.

Wanted behaviour:
No significant memory increase over time

**Desktop**
Windows 10 64bit latest version and patch
Chia 1.2.9

**Additional context**
![2021-10-20_21h32_00](https://user-images.githubusercontent.com/38796027/138159570-87e3fab8-bb55-47c6-8292-a2afd01404e3.png)

**Comment by surgus** [comment]
Same here, but on Ubuntu.
