### ISSUE TITLE
Wrong version number in macOS ARM download (1.2.11dev0)

### ISSUE THREAD

**Issue by suschizu** [Chia-Network/chia-blockchain#8969]
Hello!
The download https://github.com/Chia-Network/chia-blockchain/releases/download/1.2.10/Chia-1.2.10-arm64.dmg
contains an app with version 1.2.11dev0 - Is this a beta version?
<img width="415" alt="Screen Shot 2021-10-26 at 20 58 54" src="https://user-images.githubusercontent.com/16004333/138943757-d934143d-3d88-4c8c-b89b-844013bd51fc.png">

**Comment by emlowe** [comment]
Fixed in 1.2.11 - finally got it nailed we think!
