### ISSUE TITLE
'NoneType' object is not subscriptable, Fingerprint[BUG]

### ISSUE THREAD

**Issue by number435398** [Chia-Network/chia-blockchain#8986]
After I had to reset my computer abnormally, I started having problems with the client, it wouldn't finish loading. So I updated to the newest version.  It still had problems loading. So I renamed config.yaml and suddenly it didn't know what my key was. So I re-input my key from mnemonics, then the next screen I clicked to skip and got the following error:
"'NoneType' object is not subscriptable"
Then I clicked ok, and then another one came up, saying the same thing. clicked ok, then another error came up that just said "fingerprint", hit ok, then another one came up, then another one, then it just stayed on the same page and wouldn't progress.

**Comment by JakitOo** [comment]
I have the same problem...

**Comment by bennettwbrown** [comment]
I had the same issue when using the GUI. A quick work around, i used the command line interface which let me by pass the issue and restore my account. 

1. follow steps for your system to easily access chia from CLI.
https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#locate-the-chia-binary-executable
2. then i ran `chia keys add`
3. enter mnemonics 
4. then selected the skip option.
5. then ran `chia wallet show` to ensure the wallet loaded fine. At this point loading the GUI worked. 

hope that helps and i didn't miss a step

**Comment by SKARFX** [comment]
Same problem:
![image](https://user-images.githubusercontent.com/44023592/142273515-7de746c0-5b95-45e8-943b-7206461ac828.png)

**Comment by jakubnakielski** [comment]
Same problem :(

**Comment by DUWENINK** [comment]
Same problem :(

**Comment by DUWENINK** [comment]
f

**Comment by Sekaiji** [comment]
I have/had  the same problem. 
I farmed for many month and recently I tried to reinstall the wallet on windows 11 and had the issue. I don't know exactly how I managed to make it work again. Combanation of cleaning the db folder and/or config.yaml

I'm trying today to set a FLAX wallet for the first time and have the same issue when I try to import the mnemonics.
It seems there's many people who are facing this issue. I guess it's not yet widely known because we don't import mnemonics very often but there's definitly a bug or a conflict somewhere.

**Comment by Greco76765** [comment]
I tried using the CLI and attempting to start gave an error already running, even after a restart and even after using stop all in the CLI. What worked for me was this:
https://chiaforum.com/t/reinstalling-chia-from-scratch-what-do-i-need-to-save/4434
Saving the two files
~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite
~/.chia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_xxxxxx.sqlite
 on a different drive and then searching "chia" on C: deleting everything and then reinstalling and putting those files back. Its still syncing as I've had this issue for months and am way behind the blockchain but I am at least connected now. I also port forwarded 8444 to the machine weeks ago, not sure if that affected my outcome.
