### ISSUE TITLE
[BUG] Log formatting not correct

### ISSUE THREAD

**Issue by ByronAP** [Chia-Network/chia-blockchain#8995]
**Describe the bug**
When some exceptions are logged the stack trace is logged as well. This breaks the log format because the trace includes newlines.

**To Reproduce**
Examine log files till say an RPC error is logged with its trace.

**Expected behavior**
Newlines should be stripped from trace before logged.

**Screenshots**
<img width="763" alt="Screenshot 2021-10-27 192736" src="https://user-images.githubusercontent.com/7310089/139162155-f73c57fb-d0a9-4cf7-9872-8d3d81172ac3.png">

**Comment by ByronAP** [comment]
Still active

**Comment by ByronAP** [comment]
That's silly, the level of detail in the log would remain the same just the line endings would be stripped.

**Comment by greyslater** [comment]
in addition this brings serious problems when sending to syslog too as it's not RFC3164 conform
btw: the whole syslog output isn't RFC3164
