### ISSUE TITLE
[BUG] block validation timeout 

### ISSUE THREAD

**Issue by CeryZhai** [Chia-Network/chia-blockchain#9030]
2021-10-30T12:03:40.375 full_node chia.full_node.full_node: WARNING  Block validation time: 2.23 seconds, cost: 4298863116, percent full: 39.081%

what is this log meaning? is this affect my miner reward?

**Comment by JsBlueCat** [comment]
> 2021-10-30T12:03:40.375 full_node chia.full_node.full_node: WARNING Block validation time: 2.23 seconds, cost: 4298863116, percent full: 39.081%
> 
> what is this log meaning? is this affect my miner reward?

me too.

**Comment by mariano54** [comment]
No, this is fine, it's not an issue
