### ISSUE TITLE
[BUG]  --passphrase-file ignored for "chia start"

### ISSUE THREAD

**Issue by moonlitbugs** [Chia-Network/chia-blockchain#9032]
**Describe the bug**
There are three bugs here, filed as one *issue* as they are all interrelated:

### Bug 1 - Cannot start chia with passphrase-file

When starting Chia, the new ```--passphrase-file``` CLI option has no effect; Chia queries the passphrase from the terminal, preventing unattended system start scripts from operating.  Other Chia operations, such as ```keys show``` work as expected.

**To Reproduce**
```console
(venv) ~$ echo -n "Super Secret" > /tmp/chia.pw
(venv) ~$ chia --passphrase-file /tmp/chia.pw keys show
Showing all public keys derived from your master seed and private key:
Fingerprint: 12345678
...
(venv) ~$ chia --passphrase-file /tmp/chia.pw start farmer
Daemon not started yet
Starting daemon
(Unlock Keyring) Passphrase: 
Aborted!
(venv) ~$
```

### Bug 2 - Input sanitizing

The routine that reads the ```--passphrase-file``` preserves spaces within the passphrase (correct) but also includes line termination characters (CRLF) within the passphrase (incorrect).

**To Reproduce**
```console
(venv) ~$ echo "Super Secret" > /tmp/chia.pw   # The correct password but with '\n' on the end.
(venv) ~$ chia --passphrase-file /tmp/chiia.pw keys show
(Unlock Keyring) Passphrase: 
Aborted!
(venv) ~$
```

### Bug 3 - Lack of error/abort on incorrect passphrase

When providing the wrong password in the *passphrase-file*, chia does not abort with an "incorrect passphrase" error.  See the "**To Reproduce**" for [Bug 2](#Bug-2---Input-sanitizing).

### Expected Behavior

Chia should honor ```--passphrase-file``` when starting, and provide useful error output when the passphrase is incorrect.
```console
(venv) ~$ echo "There are no mistakes, just happy accidents" > /tmp/chia.pw
(venv) ~$ chia --passphrase-file /tmp/chia.pw keys show
Invalid passphrase from file /tmp/chia.pw
(venv) ~$ echo $?
1
(venv) ~$ echo $'Super Secret\n\n\r\n\r\n' > /tmp/chia.pw
(venv) ~$ chia --passphrase-file /tmp/chia.pw start farmer
Daemon not started yet
Starting daemon
Starting farmer
...
(venv) ~$
```

### Desktop

- OS:  Slackware Linux
- OS Version/Flavor: Current, *a.k.a.* 15.0
- CPU: AMD Ryzen
- Chia Version: 1.2.11.dev20 (*git main HEAD*) and/or 1.2.10 (*git latest*)

**Comment by stefan-lange** [comment]
Offtopic: I am not a chia developer, but a normal one and this is -by far- one of the best bug descriptions I have ever seen, @moonlitbugs

**Comment by paninaro** [comment]
@moonlitbugs Thanks for the excellent report! The start command is a bit tricky to handle, but I agree that it should be handled.

In the meantime, there is a workaround if you use the `run_daemon` command first, with the --passphrase-file option, and then start the farmer.

`$ chia --passphrase-file /path/to/passphrase.txt run_daemon &`
`$ chia start farmer`

**Comment by justinengland** [comment]
hey @moonlitbugs whats the best email to reach you at? Or are you on keybase. We are impressed by this bug report and wanted to speak with you about further engagement.

**Comment by moonlitbugs** [comment]
Thanks, @stefan-lange !

Ah, good work-around, @paninaro .  I will test on 1.2.11 once I am re-synced.  Yes, yes, I fat-fingered my rsync, wiped my mainnet DB, backup was corrupt, syncing from 0, up to 500K now.  :smile: 

I just sent an email off-list to you, @justinengland ; noticing that chia.net MX is handled by gmail, so you might find it in your Spam folder, not sure.  (I have SPF but not DKIM/DANE on my domain, sometimes gmail is pessimistic.)

**Comment by dreamboatcap** [comment]
> @moonlitbugs Thanks for the excellent report! The start command is a bit tricky to handle, but I agree that it should be fixed.
> 
> In the meantime, there is a workaround if you use the `run_daemon` command first, with the --passphrase-file option, and then start the farmer.
> 
> `$ chia --passphrase-file /path/to/passphrase.txt run_daemon &` `$ chia start farmer`

How can i write a systemd service file after 1.2.10 then? 

```[Unit]
Description=Chia Farmer
Wants=network-online.target
After=network.target network-online.target
StartLimitIntervalSec=0

[Service]
Type=forking
Restart=always
RestartSec=1
User=ubuntu

Environment=PATH=/home/ubuntu/chia-blockchain/venv/bin:${PATH}
ExecStart=/usr/bin/env chia --passphrase-file /path/to/passphrase.txt run_daemon & chia start farmer -r
ExecStop=/usr/bin/env chia stop all -d

[Install]
WantedBy=multi-user.target
```
Didn't work. I tried creating a second systemd file for daemon only but that didn't work either.
```ExecStart=/usr/bin/env chia --passphrase-file /path/to/passphrase.txt run_daemon```
```ExecStart=/usr/bin/env chia start farmer -r```

**Comment by paninaro** [comment]
@dreamboatcap I suspect it's a timing issue that you're hitting. Starting the daemon can take a little while as it performs some checks on your keys at launch. Inserting a sleep might be sufficient, or if you wanted to get fancier, I think you could wait until the daemon binds to port 55400. You should try running chia run_daemon by itself to see how long it takes before it prints out a message like `{"ca_crt": "/home/...`

I just tried the following (not at system start though):

`$ chia --passphrase-file passphrase.txt run_daemon &; sleep 15; chia start farmer`

Sleeping for 15 seconds may not always work, so you could try something larger or look into checking for the port binding. On Ubuntu I would use something like `lsof -i -nP | grep 55400` to determine when the daemon is bound and listening for connections.

As far as the reasoning for allowing a passphrase file to be provided -- The goal was to give DIYers a way to fetch the passphrase from another source, and provide it to chia via a process. This is why the examples include `chia --passphrase-file <(echo -n yourpassphrase) keys show`, where the `echo` command could be replaced by something like `vault kv get --field=passphrase secret/chia` (https://www.vaultproject.io/). Fetching the passphrase over the network is something that could be implemented in many ways. Having the passphrase laying around in an unencrypted file is not a great idea, but again, there are likely interesting solutions that might involve temporarily mounting an encrypted volume to fetch the passphrase, and then unmounting it. Hopefully the community can figure out some best practices around this. We're happy to support making changes as necessary.

**Comment by dreamboatcap** [comment]
I'll try to explain more openly. I can run this command from terminal with no problems.

```$ chia --passphrase-file /path/to/passphrase.txt run_daemon & chia start farmer-no-wallet```

It's running even if i split the commands like this.
```$ chia --passphrase-file /path/to/passphrase.txt run_daemon```
```$ chia start farmer-no-wallet```

In order to run two commands in systemd service i choose to define two service files.

One for daemon:
```[Unit]
Description=Chia Daemon
Wants=network-online.target
After=network.target network-online.target
StartLimitIntervalSec=0

[Service]
Type=forking
Restart=always
RestartSec=1
User=ubuntu

Environment=PATH=/home/ubuntu/chia-blockchain/venv/bin:${PATH}
ExecStart=/usr/bin/env chia --passphrase-file /path/to/passphrase.txt run_daemon
ExecStop=/usr/bin/env chia stop all -d

[Install]
WantedBy=multi-user.target
```
And one for farmer:
```
[Unit]
Description=Chia Farmer
Wants=network-online.target
After=network.target network-online.target chiadaemon.service
StartLimitIntervalSec=0

[Service]
Type=forking
Restart=always
RestartSec=1
User=ubuntu

Environment=PATH=/home/ubuntu/chia-blockchain/venv/bin:${PATH}
ExecStart=/usr/bin/env chia start farmer-no-wallet -r
ExecStop=/usr/bin/env chia stop all -d

[Install]
WantedBy=multi-user.target
```
I can't start daemon service only. I don't think i made a mistake while writing its service file. Please correct me if i'm wrong.

**Comment by moonlitbugs** [comment]
@dreamboatcap I can spot one obvious gotcha with your *systemd* service entries: Running ```chia --passphrase-file /path/to/passphrase.txt run_daemon``` stays in the foreground (until told to exit with ```^C``` or *SIGTERM*), whereas ```chia start farmer-no-wallet``` will background (fork) itself after startup.

So, for your "daemon" service entry, you want: ```Type=simple```, and for your farmer, ```Type=forking```.  I don't use a *systemd* system myself, so don't have a manpage reference for you.  But [this stackexchange answer](https://unix.stackexchange.com/questions/308311/systemd-service-runs-without-exiting) offers a reasonable explanation for a similar (not related to Chia) issue.

**Comment by paninaro** [comment]
Fixes have been merged into main.

**Comment by enemy100** [comment]
workaround:

1. create a expect and .sh files:

sh file:

#!/usr/bin/bash
cd /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon
./chia start farmer
exit



expect file:

#!/usr/bin/expect -f

#set timeout -1
spawn /home/gpu/mineracao/scripts_init/chia/chia-server-start.sh
#set timeout 10
expect "(Unlock Keyring) Passphrase:\r"
send -- "PASSWORD\r"
expect eof
exit 0


https://github.com/enemy100/chia-and-forks-linux-services/tree/master/chia


service file:

[Unit]

Description=CHIA Service
After=syslog.target network.target

[Service]

User=gpu
Group=gpu
WorkingDirectory= /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/
Type=forking
ExecStart= /home/gpu/mineracao/scripts_init/chia/chia.exp

[Install]

WantedBy=multi-user.target
