### ISSUE TITLE
[BUG] Expired let's encrypt intermediate certificate

### ISSUE THREAD

**Issue by petrkr** [Chia-Network/chia-blockchain#9033]
Where windows version of chia has CA certificates store? After Let's encrypt CA expiration now SSL client claim those addresses as "expired".

`
2021-10-30T12:22:51.289 farmer chia.farmer.farmer         : ERROR    Exception in GET /pool_info https://chia.czech.farm, Cannot connect to host chia.czech.farm:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')]
`

server itself has A+ grade on ssl labs https://www.ssllabs.com/ssltest/analyze.html?d=chia.czech.farm

**Comment by emlowe** [comment]
We pull the certs from our own GH repo https://github.com/Chia-Network/mozilla-ca which should pull them regularly from curl. It appears to not be updating regularly, as it does seem a little old.

The certs will be in somewhat differnet places depending on how you installed. For example, if you installed from git they are in the submodule mozilla-ca/cacert.pem. On Ubuntu, if you installed the DEB, they are in `/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/mozilla-ca/cacert.pem`

**Comment by petrkr** [comment]
Windows .exe version from github releases

**Comment by emlowe** [comment]
You can find the cacert.pem file on windows in %LocalAppData%\chia-blockchain\app-VERSION\resources\app.asar.unpacked\daemon\mozilla-ca\cacert.pem

You can replace it with the version from https://curl.se/ca/cacert.pem

We have fixed our problem with updating the pem files, so this should be resolved in the next release
