### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LokiInside** [Chia-Network/chia-blockchain#9038]
While ploting I was brake up LEGAL, and then restart and then was unable to add PLOT agin PLOT to Mac OS agin please fix it and plots cant be added as default root dir as default of app / Not Recognize Plots in Dir !
[YouTube_Video](https://www.youtube.com/watch?v=0fpRwDpBmik)

**Comment by loppefaaret** [comment]
your youtube video has the explanation, closing issue
in case you had a plot going while you chose to restart the machine, or crashed, you need to clean out all the *.tmp files in the temp directory from the previous plotting attempt, as all those files are worthless garbage.
