### ISSUE TITLE
Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.[BUG]

### ISSUE THREAD

**Issue by adc456** [Chia-Network/chia-blockchain#9041]
Cannot claim due to unconfirmed transaction. If this is stuck, delete the unconfirmed transaction.
无法申领奖励。删除未交易重新领取，也是无法到账！

**Comment by adc456** [comment]
ok 了

**Comment by loppefaaret** [comment]
assuming from last comment the issue can be closed

**Comment by jhwhtgg** [comment]
How is it handled? My 1.3.1 update still shows up with this prompt

**Comment by cypher619** [comment]
I am on 1.4 and have this prompt.  I have tried the delete unconfirmed transactions button a number of times but it has not cleared yet.
