### ISSUE TITLE
I cant input text in the join pool.   

### ISSUE THREAD

**Issue by kinkymann** [Chia-Network/chia-blockchain#9042]
I cant enter text or anything in the pool address.  i cant copy paste..   (pool tab)

**Comment by shaneo257** [comment]
its a known issue in 1.2.10, you can either join a pool via the cli or download the latest beta software from https://www.chia.net/download/ with the fix
if you download the beta software, you wont be able to get support

**Comment by kinkymann** [comment]
Ok understood.. thank you..

**Comment by temicus** [comment]
Same problem 🙁

**Comment by emlowe** [comment]
You can use the CLI. Duplicate of #8944

**Comment by temicus** [comment]
@emlowe how can I join a pool using existing nft plots... can't find info. Have tried with "join" but it doesn't work...
