### ISSUE TITLE
The computing power of the whole network is decreasing, but the time to win blocks is increasing

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#9053]
The computing power of the whole network is decreasing, but the time to win blocks is increasing

before today:
`
Total size of plots: 3.335 PiB
Estimated network space: 35.45 EiB
Expected time to win: 2 days and  hours
`
today:
`
Total size of plots: 3.335 PiB
Estimated network space: 32.897 EiB
Expected time to win: 3 days and 18 hours
`

It's strange.......

**Comment by qian-fei** [comment]
It's only 10 minutes
`
Total size of plots: 3.335 PiB
Estimated network space: 32.679 EiB
Expected time to win: 4 days
`

**Comment by Gunrunner101** [comment]
I am seeing the same issue as well. 
`Plot count for all harvesters: 16373
Total size of plots: 1.583 PiB
Estimated network space: 32.401 EiB
Expected time to win: 1 week and 1 day
`

**Comment by yoga2005live** [comment]
This is also reflecting in the the pools regards are getting down
![image](https://user-images.githubusercontent.com/17745923/139744004-3e7e4d9e-0dca-488d-8aa3-5f70dc9a329a.png)
Before with the networks size of 35 the reward of the whole network was higher

**Comment by loppefaaret** [comment]
please read our announcement of the recent "dust storm" on the chain
this caused a general slow down blocks on the network, and some lower end peers to fall behind - combining them both would have a lower overall strength of plots farming on the tip of the blockchain, along with slower block times - compounding the time to win!
once a day the chain reaches a epoch block, and adjust the difficulty, but it could be a day or two before it normalizes
