### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cryptoshaman007** [Chia-Network/chia-blockchain#9056]
1.2.7 Was working fine, after 1.2.8 update my GUI stays loading wallet forever, update to 1.2.10 and still the same issue.
Its working, its farming on the pool, but the GUI just stay loading foverever.
What to do?
Thinking of going back to 1.2.7 again

**Comment by emlowe** [comment]
This bug report is incomplete.

Please include OS version
Please include any log entries
