### ISSUE TITLE
Doesn't work transactions

### ISSUE THREAD

**Issue by andrii-stasiuk** [Chia-Network/chia-blockchain#9060]
Doesn't work transactions with 0 fee, ver. 1.2.3

**Comment by andrii-stasiuk** [comment]
now, it's all transactions does't work after "chia wallet delete_unconfirmed_transactions"

**Comment by andrii-stasiuk** [comment]
ver. 1.2.10 also doesn't work

**Comment by andrii-stasiuk** [comment]
worked after one hour of paid transaction. bitcoin is much faster than this crap

**Comment by loppefaaret** [comment]
there was a third party that flooded the network with 0 fee transactions, sending single mojos around - during these periods, a  transaction fee of atleast 0.00005 is recommended for transaction that you want to go through quickly.
right now, the blockchain has plenty of room for transactions, but that might change if the 3rd party decides to start his "test" again.
see https://github.com/Chia-Network/chia-blockchain/discussions/9049

**Comment by emlowe** [comment]
Fees need to be added when there are lots of transactions, as was happening during the dust storm. UX will be improved, but adding fees solves the issue of transactions not going through
