### ISSUE TITLE
[BUG] sqlite3.OperationalError: database or disk is full - space available, permissions in order

### ISSUE THREAD

**Issue by mcanto73** [Chia-Network/chia-blockchain#9061]
**Describe the bug**
<I can run chia farmer without any kind of issues with version 1.2.7 on a raspberry pi4 with raspbian OS. From this version I'm no more able to connect to peer (full node). I tried 1.2.8 , 1.2.9 and now 1.2.10 but no one works. After 40minutes I'm still trying to connect to peer. If I roll back to 1.2.7 it works and I can connect to peers (full node) in few minutes (about 5 minutes). >

**To Reproduce**

1. Go to 'chia-blockchain'
2. Click on '. ./activate;chia start farmer'
5. <2021-11-01T10:24:33.368 farmer farmer                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-11-01T10:24:33.376 farmer farmer_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f8426cba8> [Connect call failed ('127.0.0.1', 8444)]
2021-11-01T10:24:33.548 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 8444}
2021-11-01T10:24:33.557 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:8444 ssl:<ssl.SSLContext object at 0x7f755de798> [Connect call failed ('127.0.0.1', 8444)]>

**Expected behavior**

**Screenshots**

**Desktop**

Raspberry PI4 4GB - ARM Cortex-A72 (arm v8)
Linux mcanto 5.10.63-v8+ #1457 SMP PREEMPT Tue Sep 28 11:27:02 BST 2021 aarch64 GNU/Linux

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Additional context**

**Comment by loppefaaret** [comment]
it might be cause .1.2.8 introduced some changes to the database - some of those was re-done in 1.2.10 - try and let it run for an hour+ - those are are the highest reports ive heard of people waiting for it to come up after these updates - note that it is a one time thing that it needs to do - after the first time, it shoudl be back to normal again

**Comment by mcanto73** [comment]
> it might be cause 1.2.8 introduced some changes to the database - some of those was re-done in 1.2.10 - try and let it run for an hour+ - those are are the highest reports ive heard of people waiting for it to come up after these updates - note that it is a one time thing that it needs to do - after the first time, it should be back to normal again

Thanks for the reply

Is what you are saying documented anywhere ?
if this is a normal behaviour and it will take hours I suppose that should be documented to avoid users thinking about an issue.

Best regards

**Comment by mcanto73** [comment]
it's almost 24 hours that I'm trying to connect without any success ....
I believe that it's not doing noting ...

**Comment by loppefaaret** [comment]
ok, so you are likely seeing other problems, depending on how you isntalled, git or .deb - the next step is try to run it from CLI - first reboot, to ensure there isnt any leftover Chia processes running in the background
then either do
```
cd ~/chia-blockchain
. ./activate
chia start node
```
if you used git to install, or if you used .deb to install, do:
```
/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia start node
```
if it is failing to start up here, it should return a error and following traceback info about the error in the terminal you started this command from - if not, i need to to locate your `debug.log` under `~/.chia/mainnet/log/` and attach it to this thread

**Comment by loppefaaret** [comment]
issue found in #9100 and possible solution given there
closing

**Comment by mcanto73** [comment]
Hello,
your suggestion doesn't work for me.

I created additional space in the folder where I have .chia and started again, after few minutes I receive the sqlite3 error

(venv) pi@mcanto:~ $ chia start farmer
Daemon not started yet
Starting daemon
(Unlock Keyring) Passphrase:
Unlocking daemon keyring
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
(venv) pi@mcanto:~ $ Traceback (most recent call last):
  File "/home/pi/chia-blockchain/venv/bin/chia_full_node", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'chia_full_node')())
  File "/home/pi/chia-blockchain/chia/server/start_full_node.py", line 60, in main
    return run_service(**kwargs)
  File "/home/pi/chia-blockchain/chia/server/start_service.py", line 255, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/chia-blockchain/chia/server/start_service.py", line 249, in async_run_service
    return await service.run()
  File "/home/pi/chia-blockchain/chia/server/start_service.py", line 171, in run
    await self.start()
  File "/home/pi/chia-blockchain/chia/server/start_service.py", line 135, in start
    await self._node._start(**kwargs)
  File "/home/pi/chia-blockchain/chia/full_node/full_node.py", line 155, in _start
    self.coin_store = await CoinStore.create(self.db_wrapper)
  File "/home/pi/chia-blockchain/chia/full_node/coin_store.py", line 65, in create
    await self.coin_record_db.execute("CREATE INDEX IF NOT EXISTS coin_parent_index on coin_record(coin_parent)")
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/pi/chia-blockchain/venv/lib/python3.7/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: database or disk is full

this is the space available :
/dev/mapper/vg00-lvroot          945M  282M  596M  33% /
/dev/mapper/vg00-lvhome           30G  3.3G   27G  12% /home
/dev/sdi5                        1.6T  1.5T  116G  93% /chia_plot6

.chia is on /chia_plot6

pi@mcanto:~ $ cd /chia_plot6/CHIA/.chia/mainnet/db/
pi@mcanto:/chia_plot6/CHIA/.chia/mainnet/db $ ls -lh
total 28G
-rw-r--r-- 1 pi pi  28G Nov  2 10:23 blockchain_v1_mainnet.sqlite
-rw-r--r-- 1 pi pi  32K Nov  3 15:35 blockchain_v1_mainnet.sqlite-shm
-rw-r--r-- 1 pi pi    0 Nov  2 10:46 blockchain_v1_mainnet.sqlite-wal
-rw-r--r-- 1 pi pi 5.0M Nov  2 10:23 peer_table_node.sqlite

do you have any other suggestion for me ? 

is there some parameters to be tuned for the db ?

what does it means for database full ? 

PS It worked fine with 1.2.7

Best regards

**Comment by mcanto73** [comment]
no guys,
it has 116GB free and no revervation for root.
I'm sure that it's not a space issue at least on this filesystem

any other idea ?

**Comment by loppefaaret** [comment]
could you try these commands, and return the output:
`mount | grep '/chia_plot6'
this will tell me what filesystem you are on, and which command to issue, to find out for sure what the reserved root space is, and if there is any quota in place

**Comment by mcanto73** [comment]
pi@mcanto:/chia_plot6/CHIA/.chia/mainnet/db $ mount | grep '/chia_plot6'
/dev/sdi5 on /chia_plot6 type ext4 (rw,relatime)

pi@mcanto:/chia_plot6/CHIA/.chia/mainnet/db $ sudo tune2fs -l /dev/sdi5
tune2fs 1.44.5 (15-Dec-2018)
Filesystem volume name:   <none>
Last mounted on:          /chia_plot6
Filesystem UUID:          e3eab847-f045-4b81-a9d2-433c1b306016
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
Filesystem flags:         signed_directory_hash
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              108634112
Block count:              434521344
Reserved block count:     2172606
Free blocks:              5801733
Free inodes:              108304450
First block:              0
Block size:               4096
Fragment size:            4096
Group descriptor size:    64
Reserved GDT blocks:      1024
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8192
Inode blocks per group:   512
Flex block group size:    16
Filesystem created:       Wed Jun  2 19:01:45 2021
Last mount time:          Wed Nov  3 11:59:46 2021
Last write time:          Wed Nov  3 11:59:46 2021
Mount count:              47
Maximum mount count:      -1
Last checked:             Wed Jun  2 19:01:45 2021
Check interval:           0 (<none>)
Lifetime writes:          209 TB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:	          256
Required extra isize:     32
Desired extra isize:      32
Journal inode:            8
First orphan inode:       76546131
Default directory hash:   half_md4
Directory Hash Seed:      3d5fa15b-156b-43db-9cb6-c06dee843b3b
Journal backup:           inode blocks
Checksum type:            crc32c
Checksum:                 0xeb82c4be

**Comment by loppefaaret** [comment]
ok, fair enough - last one:
`ls -lah /chia_plot6/CHIA/.chia/mainnet/db`

**Comment by mcanto73** [comment]
Hello,
below what you requested.

I have created TMP and starting again with the following : 
(venv) pi@mcanto:~ $ export TMPDIR=/chia_plot6/CHIA/.chia/mainnet/db/TMP/
(venv) pi@mcanto:~ $ chia start farmer

I don't know if it will help but let's try also it

(venv) pi@mcanto:~ $ ls -lah /chia_plot6/CHIA/.chia/mainnet/db
total 28G
drwxr-xr-x 3 pi pi 4.0K Nov  3 16:35 .
drwxr-xr-x 9 pi pi 4.0K Oct  8 11:41 ..
-rw-r--r-- 1 pi pi  28G Nov  2 10:23 blockchain_v1_mainnet.sqlite
-rw-r--r-- 1 pi pi  32K Nov  3 16:36 blockchain_v1_mainnet.sqlite-shm
-rw-r--r-- 1 pi pi    0 Nov  2 10:46 blockchain_v1_mainnet.sqlite-wal
-rw-r--r-- 1 pi pi 5.0M Nov  2 10:23 peer_table_node.sqlite
drwxr-xr-x 2 pi pi 4.0K Nov  3 16:36 TMP

**Comment by loppefaaret** [comment]
you got 100+ GB free, no quotas or reserved root space, and RW on both the file, and folder... 
reopened

**Comment by mcanto73** [comment]
Hello,
I fixed it with the <export TMPDIR=<somewhere with a lot of space> ; In my case I used the same filesystem where there is the DB.
Now it's synching but connected to peers ... I'm behind of 24 hours

(venv) pi@mcanto:~ $ chia show -s -c
Current Blockchain Status: Syncing 1083533/1089609.
Peak: Hash: 1323bb03fddb235ce40a400f9d8c19a86501a896d65bd7509dfb8801cef16341
      Time: Tue Nov 02 2021 10:22:14 CET                  Height:    1083533

Estimated network space: 35.080 EiB
Current difficulty: 2912
Current VDF sub_slot_iters: 134217728
Total iterations since the start of the blockchain: 4046198288378

  Height: |   Hash:
  1083533 | 1323bb03fddb235ce40a400f9d8c19a86501a896d65bd7509dfb8801cef16341
  1083532 | 2cbaf05a881f58b626283d76f2a9454051989df43316cf313686f9870e95d489
  1083531 | fdc468fd7757d46a55760eb7e2ab4dc4b010f9055d2029a453c08f7073cfadf1
  1083530 | f06c99428741afedc834f02f3d650bf67cc26e779231af38e1a166139ad70e8a
  1083529 | 8b4b4aaa46ab9ce802f1913af0f63a5ce3309d909fee93e5026c43c3c386e932
  1083528 | 2e2b43c9859a5975a0ba1359108199d08293314f8f8e659a8109210a007a45f6
  1083527 | f6f6dd12e2959d96e9137e909603ad89afde74d1c1cfaf86ffd10468ff4fe82b
  1083526 | 403b899379a374529c06ecb359a7a63b3f8f8d1534ba57e95c75bfa4eb53996c
  1083525 | 303f103ccdfa73fa0e39a8b5b5248dba62cacf2e4508f3129ab5bc21c6e57c69
  1083524 | 5969560bfb7d90e9cab49c4dea0053dc044030a646352e5b20818fbf7fc1a3ad

Connections:
Type      IP                                     Ports       NodeID      Last Connect      MiB Up|Dwn
WALLET    127.0.0.1                              40578/8449  f703a56f... Nov 03 17:07:55      0.0|0.0
FARMER    127.0.0.1                              40580/8447  ba37bcf4... Nov 03 17:07:55      0.0|0.0
FULL_NODE 195.130.74.168                          8444/8444  d0cb916e... Nov 03 17:09:12      0.0|0.1
                                                 -SB Height:  1089609    -Hash: 76e2189c...
FULL_NODE 125.67.96.31                            6843/8444  44dae723... Nov 03 17:09:14      0.0|0.0
                                                 -SB Height:  1089609    -Hash: 76e2189c...
FULL_NODE 124.189.43.111                          8444/8444  916f70f4... Nov 03 17:09:13      0.0|0.0
                                                 -SB Height:  1089609    -Hash: 76e2189c...
FULL_NODE 159.196.102.202                         8444/8444  94b9a737... Nov 03 17:09:14      0.0|0.0
                                                 -SB Height:  1089609    -Hash: 76e2189c...

**Comment by mcanto73** [comment]
Hello,
I confirm that issue has been fixed by typing in the shell, before the start command, export TMPDIR=/xxxx , where xxx is a filesytem with a lot of space. 
I found this document : https://stackoverflow.com/questions/16685016/sqlite3-operationalerror-database-or-disk-is-full-on-lustre

that states : <<By default, SQLite uses /tmp temporary directory (not the memory). If /tmp is too small you will get disk full. In that case change the temporary directory like that:  export TMPDIR=<big file system>.>>

currently I'm synchronized ;-)

you can close the issue

(venv) pi@mcanto:~ $ chia show -s -c|grep "Current Blockchain Status"
Current Blockchain Status: Full Node Synced

(venv) pi@mcanto:~ $ chia farm summary
Farming status: Farming

**Comment by loppefaaret** [comment]
thank you for following up with the resolution to the issue!
