### ISSUE TITLE
Not Paying Off through Pooling[BUG]

### ISSUE THREAD

**Issue by allzima1** [Chia-Network/chia-blockchain#9062]
**Describe the bug**
I have connected to the space pool for 2 months but it hasn't paid me off for 2 bloody days. what's run with the network. that is shame. Any suggestions for addressing the problem please?

**Comment by GuidoBartoli** [comment]
Me neither for 2 days, I think it's related to [this](https://github.com/Chia-Network/chia-blockchain/discussions/9049).

**Comment by allzima** [comment]
Yeap that's it. Seems like a DDOS attacks out there. Hoping this gonna be raised in a few days later.

**Comment by emlowe** [comment]
It's really an issue for the pool - but it's caused by the dust storm. Fees now need to be added. Most pools have been working on this through the weekend.
