### ISSUE TITLE
[BUG] withdrawal txid not found on blockchain

### ISSUE THREAD

**Issue by Johnupup** [Chia-Network/chia-blockchain#9065]
**Describe the bug**

I have withdrawed xch from exchange more than 24 hours and given txid, but when i put it in blockchain, it said no transaction found..so when will be proceed or what will happen?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by emlowe** [comment]
This is something likely caused by the dust storm (#9049) - however, this is an issue you need to discuss with the exchange.
