### ISSUE TITLE
[BUG] Stuck syncing 1,075,669

### ISSUE THREAD

**Issue by jabbedxorz** [Chia-Network/chia-blockchain#9077]
**Describe the bug**
My node is stuck at block 1,075,669. Been there since 9:24:22AM on 10/31/2021. My Connections screen shows I am actively downloading from other nodes.

**To Reproduce**

Not sure? It just stopped syncing on its own.

**Expected behavior**

**Screenshots**
![chia](https://user-images.githubusercontent.com/22029038/139742674-e6002559-ab18-4e6a-8697-41363382a1ac.png)

![chia2](https://user-images.githubusercontent.com/22029038/139743002-63f5d697-a40e-4bf4-83b9-8e4f48d5b530.png)

**Desktop**

- OS: Windows
- OS Version/Flavor: 10
- CPU: AMD Ryzen 7 3700X

**Additional context**
I've tried restarting the application and my machine with no luck. Also tried kicking nodes that I was not actively downloading from.

**Comment by jabbedxorz** [comment]
I did a little extra digging and found my antivirus was updated close to the time my syncing stopped. I already had everything added as an exception, so I completely uninstalled it. Still not syncing. Completely disabled all firewall/antivirus stuff and still not syncing. Even though the application is showing I am downloading from nodes, task manager shows either 0 or 0.1 Mbps network usage.

**Comment by Patrik42** [comment]
I've got the same issue with latest version V1.2.10 on a raspberry pi. 
My sync cannot pass height 1.075.142. (Sunday 31.Oct ~2pm CET)
Any ideas how to fix this?
Cheers, Patrik

**Comment by binjie09** [comment]
Check whether there is such an error in the log file
`database disk image is malformed`
If so, unfortunately, you need to resynchronize the database from 0

**Comment by Patrik42** [comment]
Thanks binjie! There was no such line in my debug.log. 
I tried now to switch from INFO to WARNING and deleted/backupped all logs. The system might have been busy writing INFO massages constantly. -> no influence...

Other idea:
I always have to answer my keyring passphrase now, once starting my deamon. Is this correct?

If nowthing helps, i am syncing from 0.

**Comment by jabbedxorz** [comment]
Deleting my databases fixed the issue. I am now SYNCED.

**Comment by loppefaaret** [comment]
issue resolved
