### ISSUE TITLE
CHIA does NOT close out all process's when shutting down.

### ISSUE THREAD

**Issue by lsherring** [Chia-Network/chia-blockchain#9081]
**Describe the bug**
I believe after working the last four days with some very sharp folks in the Chia Forum we believe we know what is causing these intermittent issues across the board especially associated with upgrades, like the one with 1.2.20.

Late Friday night I decided to take my dedicated 100TiB rig and upgrade from 1.2.9 to 1.2.10.  I shut down the CHIA app and proceeded with the upgrade.  After the upgrade, it sat in whirlybird mode for hours.  No matter what I tried, the problem stayed.  I also kept getting 'Cannot connect to 127.0.0.1' twice and then reconnecting to the same and cannot connect over and over again.  Each time was with two messages.

I even did a restore from eight days ago and that still did not work as there was something hanging Chia from a previous version.

Nothing was wrong with my network and boy did we look.  Finally, we all surmised that the shutdown process for CHIA is not 100% complete and remnants of CHIA are still floating in the system.  We do not know if it was the Wallet or Keys, but something was still there, even after a complete uninstall.

I have been in Chia since day one and I happened to pick a day where I was about to get blasted by the dust storm at the same time as my upgrade.  Many people had the same thing occur after upgrading to 1.2.10.  Some people were able to downgrade to 1.2.8 and get back up and running.  I could not.  The upgrade during the dust storm was a MAJOR issue for many.

I was surprised as my rig is dedicated 100% chia.  64gb ram, 5 TiB SSD, 104 TiB Enterprise HDD, with a Ryzen 3950 32 core processor.  It barfed all over itself.  The ONLY way I could get back is to blow away everything Chia-related and start from scratch.

Once I did that, I installed 1.2.10 and put in my 24 words after inputting my passphrase and. voila! All popped up immediately and started to synch.  I had to add the directory of my farms but that was it.

So in closing, I have been in Engineering for 40 years (I was the Director of Engineering where we invented RAID technology for 14 years, yup my fingerprints are in every data center in the world. Pretty cool stuff) so I come with this with lots of experience and from the Chia forum to myself, we have all concluded that Chia DOES NOT shutdown 100% when you shut it down with the GUI.  We saw the same thing when we were inventing RAID in the Lab and the DVT cycle.

I'm running WIN 10 PRO.  

The majority of people who had these issues (not all) were windows based users.  I cannot pinpoint this to you, however, there are dozens of people on the Chia Forum that see the same issue that I did but I only got exasperated due to the dust storm.

I hope a process can be told to the community on upgrading.  Everyone should be closing the Chia GUI first, reboot the rig and then install Chia.  By not re-booting before the install, at that moment you leave yourself open to issues.  Lastly, the reboot does not 100% clear out everything in Chia remnants either.

I hope this helps, please ask anything as I and many others spent almost four days on this issue, and it's a bugger.

Larry

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by ByronAP** [comment]
I was under the impression that this is a well know issue and you have to go through the process list when this happens and force the offending processes to close.  This happens quite regularly that I am just use to it, the bigger problem comes in with the db getting corrupt when they processes don't shut down properly or unexpectedly.

**Comment by paulhainsworth-chia** [comment]
Two likely issues:
- Even on reboot, Windows reserves the port that our daemon needs to start Chia. 
- We have zombies that persist after shutting down Chia.

**Comment by paulhainsworth-chia** [comment]
Hey @lsherring thanks for reporting this. Can you possibly send logs for this? Thanks!
