### ISSUE TITLE
Question about "None of your plots have passed the plot filter yet"

### ISSUE THREAD

**Issue by adbutterfield** [Chia-Network/chia-blockchain#909]
Hi,

On my Farm it says:
"None of your plots have passed the plot filter yet. But you are currently farming 2.376 TiB"

Is something wrong? Is there something I need to do on my side?

Currently using v0.1.27. Had the same thing on all previous versions. I think the first one I started with was v0.1.23.

Let me know if you need any more info!

**Comment by hoffmang9** [comment]
If you haven't completed syncing it will say that. Once you're sure you're synced - block 10700 was peak at 02/11/2021 8:08:24 PM - then you should start getting data in that box.

**Comment by adbutterfield** [comment]
I've been synced for days on previous versions, and it always showed that message. I'm already synced on beta 27, and on the "Plots Passed Filter" column on the table it says 0 / 24.

Maybe they have passed, and it's just a bug in the UI? Any way I could tell?

**Comment by hoffmang9** [comment]
Now that you have it saying 0/24 - you're now in business. Every plot should pass the plot filter 18 times a day so once in a while you'll see 1/24. https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#what-is-the-plot-filter-and-why-didnt-my-plot-pass-it

**Comment by adbutterfield** [comment]
I see. I was just misinterpreting it. I thought the 0 there meant that it still hadn't passed the filter.

Thanks!!!
