### ISSUE TITLE
[BUG]Chia Blockchain 1.2.10  not connected

### ISSUE THREAD

**Issue by Ikac95** [Chia-Network/chia-blockchain#9091]
After the  Blockachain update 1.2.10 a had a problem about connecting to walled, I have deleted C:\Users\.chia\mainnet\wallet
but i stil have problem that chia blockchain cant connect for two days.
![Screenshot (2)](https://user-images.githubusercontent.com/93617488/139945439-22195bcc-3e77-4c12-a216-83600e21170f.png)

**Comment by stefb0403** [comment]
same problem

**Comment by stefb0403** [comment]
![Capture d’écran 2021-11-03 075418](https://user-images.githubusercontent.com/75476148/140019679-2b561399-8dcc-4f5e-b7da-7137d8eab22a.png)

**Comment by loppefaaret** [comment]
@stefb0403 no stef, this is clearly not the same issue - in fact, yours seems just fine ? atleast based on that one single screenshot without explanation.

@Ikac95 this is often an issue with users blockchain database, and not their wallet database, as you said you have tried removing the wallet database
be aware that it is not always the case of a corrupted database, and can be just a slow first start after some setting regarding the database was changed - if you have had it running for over an hour like this, we are a step closer to calling it a database issue, but still not quite identified it as such yet... 
if you could possibly locate your `debug.log` file under your users folder `~\.chia\mainnet\log\debug.log` and attach it to this issue, we might easily be able to identify exactly what is going on

**Comment by Ikac95** [comment]
![Uploading Screenshot (4).png…]()

**Comment by Ikac95** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/93617488/140091968-1535d66a-9f60-416f-b3c2-a50629c2eeeb.png)

**Comment by Ikac95** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7468790/debug.log)

**Comment by loppefaaret** [comment]
ok, i need you to close down chia, reboot the machine, and once your a back again, start up chia, let it run for 2-3 minutes, and attach the new `debug.log` please

**Comment by Ikac95** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7468877/debug.log)

**Comment by Ancientone66** [comment]
![Screenshot from 2021-11-03 10-05-37](https://user-images.githubusercontent.com/93669402/140098008-d5ef25bd-de65-421d-99e9-ead887678984.png)

Same Issue

**Comment by stefb0403** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7472730/debug.log)

**Comment by stefb0403** [comment]
find below debug file, could you please help
thank's

**Comment by loppefaaret** [comment]
> [debug.log](https://github.com/Chia-Network/chia-blockchain/files/7468877/debug.log)

all i can see here, is that you restart Chia plenty of times - i never get anything from the "full_node" other than it starts to initialize the blockchain - and that something is going on that crashes the "daemon" - this crashing of the daemon is likely loosing the internal connection to the "full_node" and in turn, is not catching potential logging from it

perhaps you could try another reboot, and dont start chia
then open up a PowerShell window, and execute the below commands one line at a time (assuming you are on 1.2.10, adjust paths if not):
```
cd ~\AppData\Local\chia-blockchain\app-1.2.10\resources\app.asar.unpacked\daemon\
.\chia.exe start node
```
and let it run for a atleast one hour, without doing anything else - unless it reports anything besides starting the daemon and the full node process - it might quickly report a traceback fault, if so, please report it here

**Comment by loppefaaret** [comment]
> [debug.log](https://github.com/Chia-Network/chia-blockchain/files/7472730/debug.log)

@stefb0403 
you got a corrupted blockchain database by the looks of it, and need to move it out, and resync from 0. which is going to take some time:
WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
If it worked, you can remove the files we put on the Desktop!

**Comment by Ikac95** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/93617488/140372071-af8eea4a-8c65-429a-8b0a-d4966a884a92.png)

**Comment by loppefaaret** [comment]
yup ok, we got it finally, database disk image is malformed:
WINDOWS BLOCKCHAIN DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\db\block* ~\Desktop\
```
Then try opening up the Chia app again
If it worked, you can remove the files we put on the Desktop!

**Comment by Milan201** [comment]
I have had the same problem for three days, I did it with this command and I managed to connect to the nodes.  The only problem is that now I am waiting for it to synchronize all transactions, which will take another three days. 
Thanks loppefaaret👍💪

**Comment by Milan201** [comment]
![Screenshot_20211105-094116_TeamViewer](https://user-images.githubusercontent.com/93665691/140519677-60eff68a-ea78-4248-9096-0adefbec19b2.jpg)


Before

![20211105_144206](https://user-images.githubusercontent.com/93665691/140519781-f44f5f9c-189f-447c-8e77-0354cdd6f3af.jpg)


After

**Comment by Ancientone66** [comment]
I'm still having the same Issue but I'm using linux, any help?

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7486541/debug.log)

**Comment by Ikac95** [comment]
It worked,thank you for help.But now my wallets is empty what about that, i have lost all farmed xch.Will I get back what I lost ?

**Comment by loppefaaret** [comment]
> I'm still having the same Issue but I'm using linux, any help?
> 
> [debug.log](https://github.com/Chia-Network/chia-blockchain/files/7486541/debug.log)

if your problem persists, and the above did not fix it, i suggest trying to open up a support thread here:
https://github.com/Chia-Network/chia-blockchain/discussions
or try joining our Keybase chat:
https://keybase.io/team/chia_network.public
where you can reach me @pyl 
as the issuer's issue is resovled, closing

**Comment by Kingtutking** [comment]
I also have the same problem, I tried to delete the whole mainnet folder, but it still won't connect.

**Comment by Kingtutking** [comment]
Well I actually just solved it, I think mine was a different problem but in case it helps I will type it out here. Use
net stop winnat
Then
net start winnat
then open windowshell run
cd ~\AppData\Local\chia-blockchain\app-1.2.10\resources\app.asar.unpacked\daemon\
Then run
.\chia.exe start node
and the chia.exe network permission will pop out, make sure you select either public or private connection or both if you are not sure which one you are using. 
Mine doesn't sync because of my network permissions where it has been puzzling me for a while:)

**Comment by Kingtutking** [comment]
Also, you can run .\chia.exe start farmer to see if there is any more problems.
