### ISSUE TITLE
[BUG] it won't let me paste the pool url

### ISSUE THREAD

**Issue by albertojmv** [Chia-Network/chia-blockchain#9097]
**Describe the bug**
it won't let me paste the pool url

**To Reproduce**

Join Pool / Change Pool

**Expected behavior**
Join Pool / Change Pool
it won't let me paste the pool url

**Screenshots**
![image](https://user-images.githubusercontent.com/10583719/140002709-5d2d6e77-bf72-4b41-af67-8ccdad20a28b.png)

**Desktop**

- OS: Windows 10
- OS 21H1
- CPU: i5

**Additional context**

**Comment by HEROFreeman** [comment]
the same  problem
os win10 21H1
cpu amd 5950x

**Comment by petrkr** [comment]
duplicate, first try to use "search" than open same again

https://github.com/Chia-Network/chia-blockchain/issues/8944
https://github.com/Chia-Network/chia-blockchain/issues/9004
https://github.com/Chia-Network/chia-blockchain/issues/9042
https://github.com/Chia-Network/chia-blockchain/issues/9071
