### ISSUE TITLE
[BUG] Hi guys , im getting trouble loading the wallet , any suggestions plzz 

### ISSUE THREAD

**Issue by gnikhil002** [Chia-Network/chia-blockchain#9119]
![chia glitch](https://user-images.githubusercontent.com/93718968/140323487-872ea4a5-6361-41df-8a4b-bb763a4bb95a.PNG)

**Comment by lsherring** [comment]
Deleter your wallet DBase and let it resynch....You will still farm but the wallet should re-synch with a full node in a short amount of time.  Look at your error logs.  If it cannot connect to 127.0.0.1, that is your issue.
