### ISSUE TITLE
[ENHANCEMENT] Would be nice to add wallet privkey encryption and wallet lock/unlock commands

### ISSUE THREAD

**Issue by Bibop182** [Chia-Network/chia-blockchain#912]
I believe secure implementation should include:

- Wallet privkey encryption, and use it for all new keys. Each wallet should be encrypted separately. Decrypted keys stores only in memory
- `chia wallet lock`, `chia wallet unlock`, `chia wallet passwd` commands to CLI to manage master secret key locking
- In the GUI at startup, ask for the passphrase for farming and plotting. Keep master and wallet secret keys locked the rest of the time. The passphrase should be requested to send transactions and view private keys and mnemonics.
- May be an exception can be made for the child secret keys such as farmer's and the pool's secret key, and store them clear. But every master key unlocking must require a passphrase to use
- It may be necessary to create a converter from old unencrypted wallets to new wallet format
- It is advisable to have a dialogue to change the passphrase in the GUI

Please, if you deem it necessary, correct me or add your suggestions to the list.

**Comment by hoffmang9** [comment]
You will see essentially these tasks in our public Trello in the Blockchain for launch column. Hit the GitHub project tab for the link.

**Comment by Bibop182** [comment]
I apologize. I did not know. Of course, first I had to look at Trello

**Comment by hoffmang9** [comment]
No apology needed and thanks for your suggestions!
