### ISSUE TITLE
I can't write or paste to change pools. in Version 1.2.10 | 64 bit

### ISSUE THREAD

**Issue by Manny0033** [Chia-Network/chia-blockchain#9138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by Manny0033** [comment]
I can't write or paste to change pools. in Version 1.2.10 | 64 bit

**Comment by emlowe** [comment]
Fixed in 1.2.11
