### ISSUE TITLE
[BUG] After computer reboot, node will not resync

### ISSUE THREAD

**Issue by davila2345** [Chia-Network/chia-blockchain#915]
**Describe the bug**
Last night, my windows 10 laptop restarted for os updates unexpectedly. Chia app states the status of the node as not synced. Status has remained not synced for 10 hours, with no indication of sync progress.

**To Reproduce**

1. Have Windows computer restart while Chia app is still open and synced.
2. When the computer is back on, reopen Chia app and click on your wallet.
3. Navigate to the Full Node page. The status will state "Not Synced" in red with no indication of sync-progression.
4. The "Not Synced" status may persist for an extended period of time. In my case, it has been about 10 hours. 

**Expected behavior**
After I restarted my computer and reopened the Chia app, I expected to navigate to the "Full Node" page and initially see the status state "Not Synced" plus provide an indicator of sync progress. I also expected sync to happen a lot faster, with the ability to monitor the progress of sync. 

**Screenshots**
![2021 2 13 10 34_ticket_not_synced_after_restart](https://user-images.githubusercontent.com/22757932/107854017-288af380-6de7-11eb-9a5c-3056f77166f5.png)

**Desktop (please complete the following information):**

- OS: Microsoft Windows 10 Pro
- OS Version/Flavor: 10.0.18363 Build 18363
- CPU: Intel(R) Core(TM) i7-6600U CPU @2.60GHz  2.81 GHz

**Additional context**
N/A

**Comment by davila2345** [comment]
I ended up reinstalling the Chia app, and I now see what I expected. Not the optimal solution, as this would mean I would have to reinstall the Chia app every time my computer restarts, but at least there is a workaround.

![image](https://user-images.githubusercontent.com/22757932/107855869-0dbe7c00-6df3-11eb-9791-b3979ed21556.png)

**Comment by hoffmang9** [comment]
You were running Beta 26 and it's blockchain was orphaned. As such you probably couldn't get any peers as everyone had upgraded to 27. Once you did it started working on the new chain.

**Comment by davila2345** [comment]
Ah okay makes complete sense. Thank you for quick response!
