### ISSUE TITLE
[BUG] Cannot type in the Pool URL field

### ISSUE THREAD

**Issue by Strider3099** [Chia-Network/chia-blockchain#9152]
The Pool URL text field under the Pool section does not allow me to type any text. Nothing happens when I type in the text field. Text fields in other tabs/sections work as intended except for this field

1. Go to 'Pool'
2. Click in the Pool URL text field
3. Nothing happens

- OS: Mac OS Monterey
- OS Version/Flavor: 12.0.1
- CPU: Mac mini M1, 2020

**Comment by j-filippovs** [comment]
go exactly the same issue

**Comment by Einstein098** [comment]
same Problem on 2 PC`s Windows 10 
Chia 1.2.10
I`m  loading 1.2.11 and try again

**Comment by emlowe** [comment]
Fixed in 1.2.11

**Comment by Strider3099** [comment]
But I am experiencing it on Chia app version: 1.2.11
