### ISSUE TITLE
[BUG] Cannot type in the Pool URL field in v1.2.11

### ISSUE THREAD

**Issue by Strider3099** [Chia-Network/chia-blockchain#9159]
The Pool URL text field under the Pool section does not allow me to type any text. Nothing happens when I type in the text field. Text fields in other tabs/sections work as intended except for this field. I'm experiencing it on v1.2.11 - so this issue still exists, at least on the Mac version.

Go to 'Pool'
Click in the Pool URL text field
Nothing happens
Chia app version: 1.2.11
OS: Mac OS Monterey
OS Version/Flavor: 12.0.1
CPU: Mac mini M1, 2020

**Comment by sargonas** [comment]
I can confirm we verified the fix to this problem (which was introduced in 1.2.10) works as expected in 1.2.11 for macOS.

I just want to triple check you are on 1.2.11 and not 1.2.10, since if so then something else must be amiss that we need to get to the bottom of.

**Comment by Strider3099** [comment]
Thanks, for some reason the download link was leading to 1.2.11dev instead of 1.2.11. It works now that I'm on 1.2.11.
