### ISSUE TITLE
[Enhancement] Show the transaction date/time in wallet history

### ISSUE THREAD

**Issue by krispipeleers** [Chia-Network/chia-blockchain#918]
The wallet history (Windows UI) is showing the sync date/time. It is better to show the transaction date/time. Otherwise you get this weird view with several transactions close to each when catching up on syncing.

**Comment by sielicki** [comment]
Consider reposting this issue in the GUI repository [here](https://github.com/Chia-Network/chia-blockchain-gui/issues)

**Comment by krispipeleers** [comment]
Done
