### ISSUE TITLE
3.35pb unexploded block for 10 consecutive days

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/chia-blockchain#9185]
The log is normal. 3.35pb unexploded block for 10 consecutive days

**Comment by shaneo257** [comment]
looks like the luck factor hasn't been going your way the past few days, if your logs are showing its all normal, and you are getting plots that pass the filter in each round then its working fine
if you have further questions, its best to get support on our keybase at https://keybase.io/team/chia_network.public
