### ISSUE TITLE
[Bug] Chia GUI doesn't finish plots, doesn't accept typing in the "pool url" field

### ISSUE THREAD

**Issue by VetheonGames** [Chia-Network/chia-blockchain#9187]
### What happened?

When making my first plot (after following the quick start guide and reading the various wiki pages) the wallet took **forever** to sync (upwards of a week and a half despite having a 1GB link speed and easily 30 peers on average) and when the plot was finished the software just crapped out two 100 and some gig temp files on 2 separate hard drives.

When trying to join a pool it asks for a pool URL and the fee. Neither of these two fields accept text input or copy pasting.

I'm using the latest version of the GUI client available for download from the Chia Website and it is *beyond* broken. It literally doesn't work.

Is this project dead and I wasted all my time or is there some issue with my GUI Client?

### Version

1.2.10

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
please update to 1.2.11, our latest release, that fixes the issue of not being able to type into the pool URL box
when it comes to plotting, we have blog posts up on chia.net - and there is a multitude of other places to gain information about it
you are also welcome to join our chat at
https://keybase.io/team/chia_network.public - we have severals different chatrooms in there, that perhaps have people able to help you get started - and you can personally message me @pyl there
