### ISSUE TITLE
[Bug] node.chia.net and node-eu.chia.net Peak/block Height problem

### ISSUE THREAD

**Issue by hoca05** [Chia-Network/chia-blockchain#9196]
### What happened?

Looks like 40 blocks low
Example:
Real Height=1,114,448
node-eu.chia.net Height=1,074,610

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Closing issue. We update and restart the nodes from time to time, so it's expected they may fall behind if you connect at an inopportune time. These are not supposed to be "super" nodes that the network relies on in any event.
