### ISSUE TITLE
[Bug] [GUI] GUI bug (windows/mac) negative value in wallet graph

### ISSUE THREAD

**Issue by Plopsi** [Chia-Network/chia-blockchain#9211]
### What happened?

when transactioning chias the GUI gets a little bit strange (always) when you keep it off a bit (24-48h) I just leave a screenshot here:

![grafik](https://user-images.githubusercontent.com/17942998/141010627-65064c3d-0f3a-45cb-afb5-13c5ebb7d294.png)

while not seeing the cursor, i'm sure you get the clou. (number of chias are correct)

- Plopsi

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
yup, we are aware of the issue, that the graph is showing negative values once the wallet increases

**Comment by shaneo257** [comment]
issue https://github.com/Chia-Network/chia-blockchain/issues/8832 has already been lodged
