### ISSUE TITLE
[Bug] After upgrading to 1.2.11, it keeps prompting: connect: Connection timed out. But the farmer is operating normally.

### ISSUE THREAD

**Issue by alex826-pex** [Chia-Network/chia-blockchain#9214]
### What happened?

After upgrading to 1.2.11, it keeps prompting: connect: Connection timed out. But the farmer is operating normally.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by loppefaaret** [comment]
what is it exactly that keeps prompting you ? where do you see this ? and could you give us an example of how it looks ? what did you do prior to it doing that error ?

**Comment by alex826-pex** [comment]
I kept giving this prompt after using the chia start farmer command. When using the GUI interface, this prompt will also be given in the termin
![20211109_234204](https://user-images.githubusercontent.com/62493787/141071483-c3ad4803-fafb-43cc-8ab8-4f82c09872e1.jpg)
al

**Comment by loppefaaret** [comment]
yeah, ok. that should not be happening. any chance you yourself could check your `config,yaml` under `~/.chia/mainnet/config/` and make sure all the logging options are set correct ? 
do you see any mangled output in `debug.log` that looks like it is missing those lines ?

**Comment by loppefaaret** [comment]
another idea, to see which of the 4 services that is started with `chia start farmer` that is the culprit, you could try and start them one at a time:
`chia start farmer-only` `chia start harvester` `chia start node` `chia start wallet-only`

**Comment by loppefaaret** [comment]
another idea, to see which of the 4 services that is started with `chia start farmer` that is the culprit, you could try and start them one at a time:
`chia start farmer-only` `chia start harvester` `chia start node` `chia start wallet-only`
