### ISSUE TITLE
 aleksei772000

### ISSUE THREAD

**Issue by aleksei772000** [Chia-Network/chia-blockchain#9224]
### What happened?

в 1.2.11 при запуске плотинга медмакс и всех других плотеров, отключается кошелек и фарминг готовых плотов!!! приходится синхронизировать заново после окончания новых плотов!!!!

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paulhainsworth-chia** [comment]
Hey there, @aleksei772000 I ran this through Google translate, so apologies that I don't fully understand your report. Are you saying that after plotting with MadMax, you had to re-sync your full node from zero? If not, can you please confirm the issue and if you were able to find a workaround?

**Comment by aleksei772000** [comment]
нет не 0 с нуля- отключаются узлы 8444 - статус не синхронизирован ! и начинает заново подключатся к 8444. и синхронизируется после того как закончится засеивание плота ! то есть фарминга в этот момент не получается плоты простаивают пока не синхронизируется узел11.11.2021, 23:59, "paulhainsworth-chia" ***@***.***>:
Hey there, @aleksei772000 I ran this through Google translate, so apologies that I don't fully understand your report. Are you saying that after plotting with MadMax, you had to re-sync your full node from zero? If not, can you please confirm the issue and if you were able to find a workaround?

**Comment by aleksei772000** [comment]
при начале построения через медмах он сбрасывает узлы 8444- и начинает подключать новые узлы 8444 - приходится ждать пока не синхронизируется ! пока идет засевает плот .....- у меня все простаивает НЕ СИНХРОНИЗИРОВАН

**Comment by loppefaaret** [comment]
If i understand this correct - You are saying that you can farm just fine normally, but when you start using MadMax plotter to create new plotfile - you start loosing sync, and are no longer farming correctly ?

I think this might be related to using the MadMax plotter, with too many resources possibly - if you give the MadMax plotter too much resources, there might not be enough for the node, wallet, farmer and harvester to have their needed work processed when they need it ?
are you using the same drive to plot MadMax plots on, as is also being used to hold the Chia installation ? that might be a thing that would have a possible impact on farming, as MadMax plotter can quickly saturate a drive 
it can also be that you are simply using a drive that the harvester is using as well, to farm already finished plot files ? 
it sounds to me like that it is possible that you are possibly allocating resources that is already being used during normal farming ?

**Comment by Jangir92** [comment]
Всем привет. Я кажется нашёл решение проблемы. удаляете папку db в этом каталоге <C: \ Users \ Админ.chia \ mainnet> После установите старую версию chia 1.1.6 После должна начаться синхронизация. У меня потихоньку пошла синхронизация. Самое важное то, что она не прекращается.

**Comment by loppefaaret** [comment]
I cannot recommend running such old versions - but if that is your choice, and it works for you, i guess thats it - issue fixed
