### ISSUE TITLE
[Bug] Connection error. Check if full node rpc is running at 8555

### ISSUE THREAD

**Issue by vrogojin** [Chia-Network/chia-blockchain#9229]
### What happened?

Upgraded to 1.2.11
Followed the instructions [https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian]
Rebooted the whole machine.

Doing `chia start -r node`
Issuing `chia show -s -c`

Getting this:
```
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up

```
Processes chia_daemon and chia_full_node are running,
but no relevant ports are open for listening. In particular, port 8555 is closed.
Did try to restart chia full node few times with killing all remaining chia processes after `chia stop -d all`.
Nothing works.

Before the DUST STORM everything worked fine on an old chia version (1.2.2)

Any idea, what on Earth is going on?
Should I remove my .chia folder and start resyncing from scratch?
I really do not want to go this way.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by vrogojin** [comment]
Ok, it started finally working. All relevant ports opened and `chia show -s -c` shows what it is supposed to show.
But, it took like 10 minutes to start.
Is it normal?

**Comment by emlowe** [comment]
Yes, there can be long start-up times, depending on the system and the type of disk where the DBs are located.
