### ISSUE TITLE
Impossible to install/compile Chia on FreeBSD

### ISSUE THREAD

**Issue by Gherry777** [Chia-Network/chia-blockchain#9246]
Hello,
today I tried to follow the instruction on how to install Chia on FreeBSD (I used a fresh install 11.4, even if it's outdated).

The instructions are not up to date and, in the end, even manually changing many variables it's impossible to install Chia.
The last error I got (after spending a couple of hours I gave up) is this one:

ERROR: Could not build wheels for chiapos, which is required to install pyproject.toml-based projects

Could anyone provide an updated guide (maybe for FreeBSD12) or could you just have an already compiled Chia if that is impossible (maybe a .pkg so it can be downloaded via the package manager).
Or please just remove support for FreeBSD and just tell people to use Ubuntu/Debian :(

Thank you in advance

**Comment by emlowe** [comment]
freebsd is mostly community-supported and the instructions on the wiki are also maintained by the community. Last we checked (which was in the last month) - they did work.
