### ISSUE TITLE
[Bug] Syncing Problem

### ISSUE THREAD

**Issue by ta1inn** [Chia-Network/chia-blockchain#9262]
### What happened?

I am currently using version .9. After having problems with version .9, I upgraded to the latest version. I downgraded to version .9 as the problem persisted and I encountered more problems.

The problem is as follows. About 5-6 hours after the start of farming, status "sync" appears on the main screen. But on the blocks screen, time remains in the past and does not progress.

It is fixed only after restarting and the sync process starts. Then after 5-6 hours the same problem occurs again. What can I do about it? 

### Version

1.2.9

### What platform are you using?

Pi4

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
What Operating System are you using on the RPi ? is it the standard 64 bit Raspbian OS ? 
If you are able to locate your `debug.log` under you users folder `~/.chia/mainnet/log/` and attach it here to the issue, we might be able to identify possible problems better
