### ISSUE TITLE
GUI does not start after clean new 1.2.11 installation on Ubuntu [Bug] 

### ISSUE THREAD

**Issue by raspstar** [Chia-Network/chia-blockchain#9263]
### What happened?

After doing a clean new 1.2.11 installation on Ubutnu, the GUI does not start up with following errormessages:

npm run electron &
[1] 9827

> chia-blockchain@1.2.6-dev67 electron
> electron .

sh: 1: electron: not found
npm ERR! code 127
npm ERR! path /home/administrator/chia-blockchain/chia-blockchain-gui
npm ERR! command failed
npm ERR! command sh -c electron .

As all previuos versions were running normally, what's wrong?

Thanks and regards,

R.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by raspstar** [comment]
As this is probably related, during install of the GUI following errors occured. How can solve those?

npm WARN tarball tarball data for electron-osx-sign@git+ssh://git@github.com/electron/electron-osx-sign.git#02d6ee7bbe4a7f6a2435baef7db84ced5dbc7990 (sha512-4rg0ghhKXHGrSBsE0tlrpNIENbkd0s777WFPeRCySl6pVmwA69Wcmzr79WG2gzGwNzSkiWOhdIoVV/4dBE+6Jw==) seems to be corrupted. Trying again.

npm WARN tarball tarball data for electron-osx-sign@git+ssh://git@github.com/electron/electron-osx-sign.git#02d6ee7bbe4a7f6a2435baef7db84ced5dbc7990 (sha512-4rg0ghhKXHGrSBsE0tlrpNIENbkd0s777WFPeRCySl6pVmwA69Wcmzr79WG2gzGwNzSkiWOhdIoVV/4dBE+6Jw==) seems to be corrupted. Trying again.

npm WARN tarball tarball data for xmldom@git+ssh://git@github.com/xmldom/xmldom.git#c568938641cc1f121cef5b4df80fcfda1e489b6e (sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA==) seems to be corrupted. Trying again.

npm WARN tarball tarball data for xmldom@git+ssh://git@github.com/xmldom/xmldom.git#c568938641cc1f121cef5b4df80fcfda1e489b6e (sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA==) seems to be corrupted. Trying again.

npm ERR! code EINTEGRITY
npm ERR! sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA== integrity checksum failed when using sha512: wanted sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA== but got sha512-cOF+PgNCQCvHSEYEtJKpRR11b76VLg3BVVCvLBIgeCO4KCQmt3myywGU8fvi3dxudq4UzkL4nIgJajCm1sOsvg==. (32324 bytes)

**Comment by raspstar** [comment]
Hi,

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

solved the problem.

**Comment by John69TheLazy** [comment]
hi i have the same problem

Installing on Ubuntu 20.04 LTS or newer: Using installed node.js version.
Running git submodule update --init --recursive.

Running git submodule update.

npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN tarball tarball data for electron-osx-sign@git+ssh://git@github.com/electron/electron-osx-sign.git#02d6ee7bbe4a7f6a2435baef7db84ced5dbc7990 (sha512-4rg0ghhKXHGrSBsE0tlrpNIENbkd0s777WFPeRCySl6pVmwA69Wcmzr79WG2gzGwNzSkiWOhdIoVV/4dBE+6Jw==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for electron-osx-sign@git+ssh://git@github.com/electron/electron-osx-sign.git#02d6ee7bbe4a7f6a2435baef7db84ced5dbc7990 (sha512-4rg0ghhKXHGrSBsE0tlrpNIENbkd0s777WFPeRCySl6pVmwA69Wcmzr79WG2gzGwNzSkiWOhdIoVV/4dBE+6Jw==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for xmldom@git+ssh://git@github.com/xmldom/xmldom.git#c568938641cc1f121cef5b4df80fcfda1e489b6e (sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for xmldom@git+ssh://git@github.com/xmldom/xmldom.git#c568938641cc1f121cef5b4df80fcfda1e489b6e (sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA== integrity checksum failed when using sha512: wanted sha512-XKfWBSJe4BGKsn67Hypmdfj4fI75a6EsptbrzXzNxKqokfDT3zItQl4xxA1rFvcDBZOBvfDR9tkqlow5xa3AIA== but got sha512-cOF+PgNCQCvHSEYEtJKpRR11b76VLg3BVVCvLBIgeCO4KCQmt3myywGU8fvi3dxudq4UzkL4nIgJajCm1sOsvg==. (32324 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-19T22_03_33_543Z-debug.log
