### ISSUE TITLE
[Bug] chia blockchain 1.2.11 stopped syncing !!!

### ISSUE THREAD

**Issue by AleksandrPDA** [Chia-Network/chia-blockchain#9272]
### What happened?

at an altitude of 1071254, the chia blockchain synchronization suddenly stopped, I went through many ways to fix the error, as a result, I deleted the chia blockchain database, and the synchronization went successfully, but it stopped at an altitude of 552032, I re-delete the blockchain database, the synchronization starts and again stops exactly at 552032. Help me solve my problem

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
Please tell me where can I see this log output
```

**Comment by Jangir92** [comment]
I had the same thing. sync didn’t go on for 7 days. then I deleted the db folder. sync started from the beginning. and reached 552,064.please tell me how to fix it and fix the sync issue

**Comment by jredner** [comment]
Yep.  I have the same issue.  I'm on my third time, blowing away the blockchain DB and the wallet DB to give it a fresh start.  Each time takes multiple days and then just freezes up.  Shutting down the GUI gracefully and restarting doesn't help either.  I'm just trying to retrieve a .25 chia reward in a wallet and so far I'm at this for over a week just trying to bring up the wallet.  Finding it hard to believe this is expected behavior.  Seems really brittle.

**Comment by AleksandrPDA** [comment]
My problem was still not resolved. Why does the support service not help in solving our problem?

**Comment by santiagovirus** [comment]
I have the same problem, anyone could help us? This is terrible!! "F"

**Comment by Jangir92** [comment]
Всем привет. Я кажется нашёл решение проблемы. удаляете папку db в этой папке <C:\Users\Админ\.chia\mainnet> После устанавливаете старую версию chia 1.1.6 После должна начаться синхронизация. У меня потихоньку пошла синхронизация. Самое важное то что она не прекращается.

**Comment by AleksandrPDA** [comment]
благодарю! попробую

**Comment by AleksandrPDA** [comment]
Здорова Джангир! У меня все синхронизировалось! Как ты сказал,я сначало установил версию 1.1.6 синхронизация полного узла дошла но сам кошелек остановился в районе 361000 , Потом я установил версию 1.2.7 и кошелек начал синхронизацию и догнал))) благодаря общим усилиям решили эту проблему и получается  все дело в новых версиях чиа блокчейна 1.2.10 и 1.2.11
