### ISSUE TITLE
[Bug] Blockchain files not deleting while chia uninstall

### ISSUE THREAD

**Issue by tayvs** [Chia-Network/chia-blockchain#9274]
### What happened?

I uninstall chia and system free just few hundreds MB. After manually deleting .chia folder from user directory blockchain GBs of memory were free. Also I fonder when client will use smth like online blockchain platforms? 

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
This is as designed - we leave around those files on purpose.

**Comment by tayvs** [comment]
@emlowe Mb add option to delete blockchain in uninstall menu? It's not obvious what file need to delete and where searching for them
