### ISSUE TITLE
[Bug]  矿池不上传算力  提示更新农民信息错误

### ISSUE THREAD

**Issue by yiqiang320** [Chia-Network/chia-blockchain#9314]
### What happened?

能否支持删除 老旧的矿池账户

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
It is currently not possible to remove extra plotNFT's under the "Pool" tab - we are planning on adding it in a future release!
