### ISSUE TITLE
Beta: problems syncing standalone wallet.

### ISSUE THREAD

**Issue by Taweesakpintakam7m1** [Chia-Network/chia-blockchain#9318]
8 hours later still not synced.
Hopefully someone can fix this.
The problem does not seem to be something I can fix. (even after adding Chia to the firewall manually)

_Originally posted by @mdrodge in https://github.com/Chia-Network/chia-blockchain/discussions/9301#discussioncomment-1660463_

**Comment by luker2013** [comment]
Error syncing for light wallet
![WX20211123-113002](https://user-images.githubusercontent.com/6269043/142967845-33279978-b619-4631-a72d-a0868ad66b90.png)
.

**Comment by mdrodge** [comment]
I've tried multiple times and it just won't (uninstall etc)
The funny thing is the Flax Light Wallet worked first try.

**Comment by mdrodge** [comment]
Our voices go unheard.
