### ISSUE TITLE
[Bug] K32 plots are using more than 256gb of temp space

### ISSUE THREAD

**Issue by zerovski** [Chia-Network/chia-blockchain#9328]
### What happened?

When plotting on a 320gb hard drive, it freezes at 42%, and the hard drive is full, exceding the recommended 256gb (239GiB) space needed to plot.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
make sure you clean out any previous failed attempts .tmp files. failed plots leave behind their .tmp files in the temp directory

**Comment by zerovski** [comment]
Yes I did that! That's not the problem! The drive was formatted.

**Comment by loppefaaret** [comment]
can you replicate the issue ?

**Comment by zerovski** [comment]
> can you replicate the issue ? also, which plotter are you using ? chiapos ? 

Yes I can replicate it. It happens every time I try to plot on a 320gb hard drive. I'm using chiapos plotter.

**Comment by loppefaaret** [comment]
assuming it is formatted as NTFS - do you by any chance have folder compression enabled on the folder that is being used as temp directory ? 
any chance you could try to describe the settings you are using when it seemingly is running out of space ? 
before starting a plot, how much free space is reported on the filesystem ?

**Comment by zerovski** [comment]
Yes, it is formatted as NTFS without folder compression. It's an HDD, not an SSD. The system reports 297GB free. I plot with Chia Proof of Space 1.0.6, k32 plot, in queue with bitfield disabled (it's old hardware). You can see the rest of the settings in the prints i send.
I'm trying to plot now, when it gets to the error i'll sent the message it shows!

![chia 01](https://user-images.githubusercontent.com/81782208/142905095-78d6554d-80b0-4e7f-89fd-5464bf8589e6.PNG)
![chia 02](https://user-images.githubusercontent.com/81782208/142905097-39f8cf9e-144e-44a5-a35e-d514cdfae0b2.PNG)
![chia 03](https://user-images.githubusercontent.com/81782208/142905100-c8904c00-fb81-485a-ada7-9cd4789f144d.PNG)
![print disk](https://user-images.githubusercontent.com/81782208/142905103-ff9d4ba8-bfa2-4489-bfa3-b63314264400.PNG)

**Comment by loppefaaret** [comment]
thank you bery much for the detailed report - one final request:
when it ends up stuck - could you perhaps try and open up a PowerShell window, and switch to E:\ and list the dir ?
```
E:
dir
```
and either copy paste it into a .txt file and attach, or just simply paste it into a message here - it will show me which files are left behind
also if you could add the plot .log file, it should be stored under you users folder: `\.chia\mainnet\plotter\*.log` from this latest attempt

**Comment by zerovski** [comment]
Hi!
No problem, i think this are the files you asked.
Thank you!

![chia 04](https://user-images.githubusercontent.com/81782208/143002547-f4afc5bf-8290-4847-a723-a4303ef13abb.PNG)
![chia 05](https://user-images.githubusercontent.com/81782208/143002555-db5439a5-faf9-46aa-be90-a1d127b92e17.PNG)
[e dir.txt](https://github.com/Chia-Network/chia-blockchain/files/7587036/e.dir.txt)
[plotter_log_104baabb-c406-4cf5-8044-b8270c118384.txt](https://github.com/Chia-Network/chia-blockchain/files/7587037/plotter_log_104baabb-c406-4cf5-8044-b8270c118384.txt)

**Comment by loppefaaret** [comment]
that is absolutely perfect - thank you very much for data you submitted

**Comment by zerovski** [comment]
No problem! If you need any more data, just tell!

**Comment by zerovski** [comment]
Hi!
Any news on this?

**Comment by alginnon** [comment]
hi there, is the temp file location a mapped usb as ready boost normally appears for usb or plug in usb
this may not work correctly and be the issue, only a guess since no one else has responded recently.
Try using a spare hard drive as the temp space for building then copy to location to farm.

**Comment by zerovski** [comment]
> hi there, is the temp file location a mapped usb as ready boost normally appears for usb or plug in usb this may not work correctly and be the issue, only a guess since no one else has responded recently. Try using a spare hard drive as the temp space for building then copy to location to farm.

Hi!
Thank you for your input, but if i understood correctly, that's not the issue here.
The temp location it's a physical drive, SATA HDD, with ready boost already disabled.

**Comment by alginnon** [comment]
Hi there, ok in that case make sure that all hidden files on the drive are being shown.

In windows another option to make sure of is to disable shadow copy for a drive.
https://www.maketecheasier.com/free-up-drive-space-by-removing-shadow-copies/
This link be helpful to check if it enabled or disabled for a drive.

**Comment by alginnon** [comment]
Hi there,
To find out exactly what's taking up space try this to investigate the folder location
https://www.fosshub.com/WinDirStat.html
it should be useful

**Comment by zerovski** [comment]
Ok! I'll try that app and get back with more data!
