### ISSUE TITLE
[1.2.11] Can't connect with nodes

### ISSUE THREAD

**Issue by chinabala** [Chia-Network/chia-blockchain#9338]
I am using 1.2.11

My chia out of sync for days, and realized that it somehow wouldn't be able connect with other nodes.
I've tried reinstall the app, check my 8444 forward ports etc.

Finally, I search for public nodes on Google and manually connect each of them. It works and start syncing.
However, each time I restart the app, I will have to manual connect to available nodes....

Anyone?

**Comment by loppefaaret** [comment]
Close down Chia, and remove the `~\.chia\mainnet\wallet\db\peer*` files - then try and open up Chia again

**Comment by chinabala** [comment]
> Close down Chia, and remove the `~\.chia\mainnet\wallet\db\peer*` files - then try and open up Chia again

removed wallet/db, done.
re-sync wallet, done.
restart pc and open chia sit for 10 min, done.

no chance it'd work. I still have to add nodes manually to get it mining. sad...

**Comment by loppefaaret** [comment]
oh, i made a mistake here - could you try removing the `~\.chia\mainnet\db\peer*` files - sorry about this mistake from me
then restart Chia

**Comment by chinabala** [comment]
> 

Still re-sync both my \db and \wallet. It might take a week I guess...

I'd share my de-bug log below. I think my chia client can't find node and wallet peers for some reason. I am sure my internet and pc are just fine, otherwise there won't be some many same issue posts lately...

`2021-11-26T06:27:19.951 wallet asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-16' coro=<WalletPeers.ensure_is_closed() done, defined at chia\server\node_discovery.py:703> exception=AttributeError("'WalletPeers' object has no attribute 'connection'")>
Traceback (most recent call last):
  File "chia\server\node_discovery.py", line 706, in ensure_is_closed
  File "chia\server\node_discovery.py", line 120, in _close_common
AttributeError: 'WalletPeers' object has no attribute 'connection'
2021-11-26T06:27:31.049 wallet chia.rpc.wallet_rpc_api    : ERROR    error Cannot connect to host backup.chia.net:443 ssl:<ssl.SSLContext object at 0x000002778E5C6740> [getaddrinfo failed]
2021-11-26T06:28:00.673 full_node chia.full_node.full_node: WARNING  querying DNS introducer failed: The DNS operation timed out after 30.012300968170166 seconds`

**Comment by loppefaaret** [comment]
are you not getting connected to any other peers under the "Full Node" ?

**Comment by chinabala** [comment]
> 

Correct. 
I've tried two situations, one's under full synced and another with all db./walllet removed as you suggested. No chance. All other peers can't see me, but I can only manually connect to them.
