### ISSUE TITLE
[Bug] CAT wallet showing CAT puzzle hash in incoming transactions 

### ISSUE THREAD

**Issue by ojura** [Chia-Network/chia-blockchain#9345]
### What happened?

I wasn't sure if this should be a bug report or discussion, but seeing another question in Discussions where the user inadvertedly did this (and doesn't know what's going on) is alarming.

Referencing discussion 9343 with a detailed description:
https://github.com/Chia-Network/chia-blockchain/discussions/9343

TLDR: The light wallet shows the CAT puzzle hash for incoming transactions, and not the real puzzle hash of the underlying standard chia wallet. The users may inadvertedly use these addresses for sending coins and end up possibly burning them.

### Version

Light wallet beta

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by trgarrett** [comment]
As one of the users who has run into this, the big point of confusion for me was that the address I sent to was the only place I could see my CAT on chia explorer.

**Comment by ojura** [comment]
wontfix, PR #9422 closed
