### ISSUE TITLE
[Bug] Windows gui for the light wallet white screens after windows 10 goes to sleep.

### ISSUE THREAD

**Issue by justinengland** [Chia-Network/chia-blockchain#9353]
### What happened?

When running the windows GUI for the new light wallet, it runs fine until windows goes to sleep after not being used for several hours. 

When windows recovers from sleeping, the app GUI is unusable and the application must be restarted to work again. 

### Version

wallet 1.2.11254

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by ActionFaction** [comment]
Screen manager needed in build.

**Comment by emlowe** [comment]
We believe this is fixed in 1.3.4
