### ISSUE TITLE
[Bug] Migrate keys fail while updating 1.2.11 wallet disappeared. (Gui Windows 2011)

### ISSUE THREAD

**Issue by silence48** [Chia-Network/chia-blockchain#9366]
### What happened?

I updated from 1.2.7 to 1.2.11;
Upon doing so i was greeted with the keys migration message.  I was pleasantly surprised.
I set a passphrase for the wallet encryption.
A few minutes passed... I go back to work.
15 minutes later I return and notice that I am now on the wallet login screen and there is no wallet.
![image](https://user-images.githubusercontent.com/35656692/143142864-f1b18feb-c620-40c8-a59c-1179375f2f04.png)
I check my ca folder.  the old keys are still there. I also noticed a new .chia-keys folder in user space

I notice many start_wallet threads but no farmer or harvester.  
![image](https://user-images.githubusercontent.com/35656692/143143137-4d3df620-3f54-47f4-a6f3-15ac207c4358.png)

I just got a firewall popup while typing this bug report saying the start_full_node started. 

I tried to force a reload of the GUI and it got stuck on "signing in" I will have to shut it down and start over. The keys are still there but there is only one file in .chia_keys folder too.

Apparently something also went wrong with my normal automated upgrades at some point because half my farm is down too.  Not very happy with that but I guess I should check it more often. (The other harvesters are either on other windows systems or other linux systems. I happened to upgrade this system manually since it doesn't actually do either.)

Maybe this is because i skipped a couple versions on here? Or maybe the upgrade from 3.09 to 3.10 failed previously I will have to check my logs later and see if i can provide any useful info.

No huge harm because I keep my keys. I just will setup this fullnode freshly.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by silence48** [comment]
after importing a new key, I get a new error
![image](https://user-images.githubusercontent.com/35656692/143143794-f2173683-7603-4943-8a29-1c26804a0fbe.png)

**Comment by silence48** [comment]
restarting the wallet and gui did not fix it.

Signing out of windows and back in and it has worked as intended. 

Windows sucks.

Moral of the story: Don't use windows.

**Comment by emlowe** [comment]
This is likely due to some zombie processes - we do have some engineering items to take a closer look at this issue (see https://trello.com/c/ucSiN8KT) - however, the workaround as noted it to log out (or reboot). Closing this specific issue.
