### ISSUE TITLE
[Bug] After reinstall chia client on new hard disk, balance 0 xch

### ISSUE THREAD

**Issue by Mientowy** [Chia-Network/chia-blockchain#9372]
### What happened?

After installing chia on a new drive, I can see my XCH but at the end and full wallet sync my account is xch 0. I see my mining in history. I didn't transfer my XCH

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
it would be an indicator that there is no XCH on the wallet, if it shows 0 balance - perhaps you can check some of the addresses on an explorer like chiaexplorer.com or xchscan.com ?

**Comment by Mientowy** [comment]
My heart just stopped! I can see on XCHscan that my 12XCH was traded 7 days ago. How is this possible? Is this really happening? Nobody knew my key. I didn't leave him anywhere..

[Zrzut ekranu 2021-11-24 o 16 48 02](https://user-images.githubusercontent.com/94956962/143271108-e6c6f992-329b-4e23-a9b0-ed3a79288e13.jpg)
g?

**Comment by loppefaaret** [comment]
im sorry to say, but someway somehow, someone gained control of your 24 word mnemonic

**Comment by Mientowy** [comment]
that is, all the plots to the trash ... the whole farm to be built again. I have to do this because I won't have any trust in her.
