### ISSUE TITLE
[Bug] chia_harvester became defunct with a segfault

### ISSUE THREAD

**Issue by jayhohoho2019** [Chia-Network/chia-blockchain#9376]
### What happened?

One of my remote harvesters dropped out of the farm.  Upon investigation:
- ps shows chia_harvester defunct.  chia_daemon seems normal at least on the process table
- grep chia /var/log/syslog shows: 
  Nov 24 06:11:07 kernel: [374092.015767] chia_harvester[2015]: segfault at 5 ip 0000000000000005 sp 00007ffec5594d48 error 14 in python3.8[400000+23000]
- nothing around that timestamp in chia's own debug.log, set at INFO
- a command that ran chia start harvester -r brought it back up into the farm. So far so good.
- all nodes run the same version of OS and chia.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by loppefaaret** [comment]
could you check the harvesters `debug.log` ? just make sure there is no ERROR about bad plots - which tend to generally be the culprit when a harvester does malfunction in some way

**Comment by paulhainsworth-chia** [comment]
We don't think you'll see this again, but if you run chia plots check with a large number iterations. If you find a bad plot, please upload it to us here.

**Comment by jayhohoho2019** [comment]
will do.  what represents a large number iterations in chia plots check?

**Comment by jayhohoho2019** [comment]
upload the entire plot of 101GiB when that happens or just the error message?

**Comment by emlowe** [comment]
You won't be able to upload the entire thing here - but if you find one that seems to crash the code - then you can ping us here and we will provide an separate upload URL. A large number  might be 500?
