### ISSUE TITLE
[Bug] Syncing issues

### ISSUE THREAD

**Issue by egmsystems** [Chia-Network/chia-blockchain#9391]
### What happened?

Not Synced, after windows restart
![image](https://user-images.githubusercontent.com/3238522/143509879-dacb42ab-dc90-4918-8f44-65e3a21ade74.png)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
Perhaps i can get you to attach your `debug.log` file - it might help us better diagnose your problem. It is located under your users folder `~\.chia\mainnet\log\`
And could you also try and describe what is happening ? have you been stuck on 323520 ? or is it just sometimes going into red "Not Synced" - but over time still rising ?

**Comment by egmsystems** [comment]
fixes, thanks
