### ISSUE TITLE
[Bug] Unable to lunch the GUI

### ISSUE THREAD

**Issue by abdul-jalil** [Chia-Network/chia-blockchain#9392]
### What happened?

Chia Network GUI is freezing and when I tried to restart the GUI I got the following error after entering the passphrase and the 24 words.
![Screenshot 2021-11-25 194539](https://user-images.githubusercontent.com/19950003/143511107-f515c646-a7fe-42f7-816a-0c14f5bbf24c.jpg)

![Screenshot 2021-11-25 195103](https://user-images.githubusercontent.com/19950003/143511427-e19888f5-077a-44d0-aabf-d3b15a7b92f6.jpg)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by OldButtKicking** [comment]
First try and create an empty new wallet. Don't worry about the key you will delete in a min. If this successful go back to keys screen and recover your existing. The delete the first one.

**Comment by abdul-jalil** [comment]
> First try and create an empty new wallet. Don't worry about the key you will delete in a min. If this successful go back to keys screen and recover your existing. Then delete the first one. This is how I got passed the nontype error

I tried. Same error.

**Comment by abdul-jalil** [comment]
It's working now after restart the computer and re-install CHIA GUI.
