### ISSUE TITLE
Time to Win 

### ISSUE THREAD

**Issue by haxtible** [Chia-Network/chia-blockchain#9397]
I have 1700 Plots and Time to win dont change what the F...

**Comment by haxtible** [comment]
He run on win10

**Comment by loppefaaret** [comment]
Please include valid data for us to help you out - dropping a complaint is not to the right place to do so here

**Comment by haxtible** [comment]
My position not chane by time to win and i am by 1700 Plots .Runing on a win 10 pro version whith 1.2.11 gui.The time to win position from 2 monts not changing to weeks why?

**Comment by loppefaaret** [comment]
Cause the estimation math is putting you around 2 months ? with 1700 k32 plots it puts you just shy of 170 TiB, and with the network at 34.6 EiB (4535091 TiB) that is the expected average time to win.
[chiacalculator.com](https://chiacalculator.com/) seems to come to the same conclusion ?
