### ISSUE TITLE
[Bug] Shadow pools that I never have added myself

### ISSUE THREAD

**Issue by andriitalkstech** [Chia-Network/chia-blockchain#9398]
### What happened?

Pools list keeps showing me pools that I have never added myself.

I have tried to remove it from **config.yaml** but they keep popping up once in 2 runs.
How do I delete/disable shadow pools forever?
![image](https://user-images.githubusercontent.com/84045191/143579223-b9a5d32e-2c5f-4290-b2c3-87c420590ac0.png)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
There was a dev build released based on `main` branch a little whole ago, that had a bugged wallet that caused these random plotNFT's to show up.
it will cause you to have invalid data in a couple of places, that you need to manually clean out:
- `config.yaml` (the `pool_list:` section)
- the Wallet database (`~\.chia\mainnet\wallet\db\blockchain*`)
- the cached data under `'%appdata%\Chia Blockchain'` (`~\AppData\Roaming\Chia Blockchain`)

------
the heavy handed method to clean this out from your install:
Close down Chia
move out affected folders, ei. using PowerShell:
```
mv '~\AppData\Roaming\Chia Blockchain' ~\Desktop\
```
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
```
mv ~\.chia\mainnet\config\config.yaml ~\Desktop\
```
This should have you ready to start up Chia again - having lost all settings, such as log level, UPNP, plot directories, and whatever else you had in `config.yaml`
it will also wipe out any plotNFT's you had under the "Pools" tab
it will also require your wallet to sync back up from 0 - and until it passes the last edit to your pooling plotNFT on the blockchain, it will not farm correctly!

-------
Now if you want to "cheat" a bit here, some stuff you can do is:
- Sync the wallet on another node from 0, and move the wallet database over to skip the downtime of syncing it from 0 on the farmer machine
- manually edit `config.yaml` and remove the "shadow" entries under the `pool_list:` section (done when you switch wallet database)

Remember the cache data under `~\AppData\Roaming\Chia Blockchain` needs to go as well.
