### ISSUE TITLE
connect to wallet loading before 17 hours [Bug] 

### ISSUE THREAD

**Issue by Nagendra129** [Chia-Network/chia-blockchain#9415]
### What happened?

Hi sir,
   my chia rig yesterday onwards not loading connect wallet Loading only how to solve ?
i restart my rig 5-10 times since same issue.

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7636099/debug.log)
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7636112/debug.log)

Ch,Nagendra (INDIA)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
if you could locate the `debug.log` file, located under your users folder `~\.chia\mainnet\log\` and attach it to this issue, we might be able to identify what is going on.
Most times, it is some kind of corruption of the data on your machine, likely from an unclean close down of Chia, or perhaps even a poweroutage ? 
Some people find that their wallet database has been corrupted, and removing it, and resyncing it from 0 fixes the problem.
I'm only guessing here, so only try this if you feel up to doing this, and are able to help yourself restore the files to their original location, if it does not work for you:

WINDOWS WALLET DATABASE RESET

Close down the Chia app, and open up a PowerShell window, and execute the below command:
```
mv ~\.chia\mainnet\wallet\db\block* ~\Desktop\
```
Then try opening up the Chia app again.
If it worked, you can remove the files we put on the Desktop.
If it did _not_ work for you, you can restore the files to their original location by closing down Chia again, and doing this in the PowerShell window:
```
mv ~\Desktop\block* ~\.chia\mainnet\wallet\db\
```
Note that if you got new plots that points to a plotNFT, the wallet needs to sync pass the latest edit before it farms correctly!

**Comment by Nagendra129** [comment]
Hi Sir
same problem is not solved, connecting to wallet loading.
I tried two options since not solved
kindly give suggestion

**Comment by loppefaaret** [comment]
if you could locate you `debug.log` and attach it to this issue please.
the full path is `C:\Users\<USERNAME>\.chia\mainnet\log\debug.log` where `<USERNAME>` is the name of the user account on your windows installation.

**Comment by Nagendra129** [comment]
[]([]([debug.log](https://github.com/Chia-Network/chia-blockchain/files/7643886/debug.log)))

**Comment by Nagendra129** [comment]
Message too large
Your message couldn't be delivered to ***@***.**** because
it exceeds the size limit. Try reducing the message size and resending.

**Comment by emlowe** [comment]
Poolharvest.io is shutdown - you need to stop pooling to them.

**Comment by victortb23** [comment]
I have the same problem. It is only on the same screen "connecting the wallet". Could you please help me? Here is my log file
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/8141119/debug.log)
.
