### ISSUE TITLE
Invalid proof of space[Bug] 

### ISSUE THREAD

**Issue by chia991** [Chia-Network/chia-blockchain#9416]
### What happened?

I have 500t space and haven't won a reward for 70 days. I didn't care at first, but recently I found in my log that it always outputs:ERROR    Invalid proof of space

Is it because version 1.2.11 is incompatible with files made in earlier versions. I wrote down the total output error of the log. Who can translate it for me and tell me what's going on? Thank you

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

```shell
2021-11-27T20:07:38.633 farmer chia.farmer.farmer         : ERROR    Invalid proof of space {'challenge': '0xc1d244b40cd2a5386ccd9779ed789df52708b032d4e0bb9ef00d15bbd884b82b',
 'plot_public_key': '0x80b917e86b9af4d6c6877351e931156e8335e401bdf852c1a264ace5893bbff36ab527f31cb2999245c9cb5fce183a62',
 'pool_contract_puzzle_hash': '0xc3eb57239dc9e138c0a54667a0510d474f5ba625c1ba2f1c5ed724255cd42f03',
 'pool_public_key': None,
 'proof': '0x57748f9d77ad9fb94b651777c5fcefe1da0c081d6fddc060879c58834df86a7c57b6480474fc0523baf3f10abc5b27afbb0cfd70f21ae79a27ce84091422d83b6d4ed4a1913a46fb5ee1b0567fcb3b076ed041cea90ce7f2f9ae01df5a6a0c360e5400587a8b0df6d52ac343f6ac7e8134e98f4077f14a8967d94d0db9b6bbcf387123a461ac8bb5a883eed7cba83b4e61c7d3a9d75d6986f2122a160fadcd17f7e8305ba18165aac8b60f644e4f7f0e109a185e939108415f57830cf9ec947f2de665976fa8019979016c2811354eca5df1d0ed9b73576d89456e9f8f1981935022ca8f787d5e49640fc48a153935bc9240e1e8ccb29f11a730a6be650c98bc266ed2e3cd8c5593',
 'size': 33}
```

**Comment by paulhainsworth-chia** [comment]
Hey @chia991 some questions:
- have you done any changes to your plots
- have you used any forks? 
- have you run chia plots check?
