### ISSUE TITLE
[Bug] Chia full node cannot finish starting up

### ISSUE THREAD

**Issue by yjiangnan** [Chia-Network/chia-blockchain#9418]
### What happened?

I upgraded from 1.2.3 that has been running smoothly for a long time to version 1.2.11. The starting up of full node never finish after hours:
```
:~/chia-blockchain-1.2.11$ chia start node
Daemon not started yet
Starting daemon
chia_full_node: started

:~/chia-blockchain-1.2.11$ chia show -c
Connection error. Check if full node rpc is running at 8555
This is normal if full node is still starting up
```
No matter how long I wait, `chia show -c` shows the same result. `top` command shows that `chia_full_node` is running, with less than 10% CPU usage. The log file shows ONLY the following:
```
2021-11-29T14:14:07.767 daemon chia.daemon.server         : INFO     Starting Daemon Server
2021-11-29T14:14:07.769 daemon chia.daemon.server         : INFO     Waiting Daemon WebSocketServer closure
2021-11-29T14:14:10.720 full_node chia.full_node.full_node: INFO     Default port field not found in config.
```
What is going wrong and what should I do?

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by Jangir92** [comment]
Здраствуйте. я думаю ошибка в последней версии chia.установите старую версию 1.1.2 и попробуйте зайти заново.

**Comment by Jangir92** [comment]
1.2.0
