### ISSUE TITLE
[Bug] Wiki info out of date\wrong. 

### ISSUE THREAD

**Issue by DrakeFS** [Chia-Network/chia-blockchain#9423]
### What happened?

https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#do-my-plots-wear-out-or-go-badgo-stale-over-time-will-i-have-to-regularly-re-plot

Specifically:

> if you are joining/leaving a pool or are switching pools (the pool public key is hard-coded into the plot)

Is no longer true.

From reddit: https://old.reddit.com/r/chia/comments/r539y8/replot/

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
Thank you for pointing that out to us!
A first edit has been added - a review will be done later
https://github.com/Chia-Network/chia-blockchain/wiki/FAQ#do-my-plots-wear-out-or-go-badgo-stale-over-time-will-i-have-to-regularly-re-plot

**Comment by paulhainsworth-chia** [comment]
Hey @danieljperry can you please take a look?

**Comment by danieljperry** [comment]
I just made one clarifying remark. Otherwise it looks good.
