### ISSUE TITLE
Delete all keys should wipe farmer reward and pool reward addresses as well.

### ISSUE THREAD

**Issue by tbladh** [Chia-Network/chia-blockchain#9437]
When wiping your keys and setting upp a new "identity" the farmer reward and pool reward addresses stay the same (derived from the old keys) which is easy to miss. Perhaps not a common case for regular users (although potentially very serious if it were to happen) but is quite confusing when working with testnets.

Expected behavior: Wiping your keys and setting up new ones should result in the first wallet address ultimately derived from your new wallet seed being used as both farmer reward and pool reward. What the user does after that is up to them.

**Comment by emlowe** [comment]
The main reason it doesn't work this way is because of cold wallets - but I agree there is some room for more improvment. The UI will warn you when you delete keys individuall though that your key is being used, perhaps it should do something similar for delete all keys.

**Comment by tbladh** [comment]
> The main reason it doesn't work this way is because of cold wallets - but I agree there is some room for more improvment. The UI will warn you when you delete keys individuall though that your key is being used, perhaps it should do something similar for delete all keys.

I agree. There are several ways to solve this. The salient points to communicate to the user regardless of how it's solved UX wise are that: a) "this can happen", and b) "this is how you avoid it".
