### ISSUE TITLE
[Bug] I cannot install chiablockchain-gui on CentOS 8

### ISSUE THREAD

**Issue by notprogrammer** [Chia-Network/chia-blockchain#9439]
### What happened?

Hello, i cannot install chia-blouckchain-gui on CentOS 8.5.2111 via official manual to installation.

Workflow:

1. rm -rf chia-blockchain
2. git clone https://github.com/Chia-Network/chia-blockchain.git -b latest
3. cd chia-blockchain
4. sh install.sh
5. . ./activate
6. sh install-gui.sh <- i get "Command failed: git checkout master pathspec 'master' did not match any file(s) know to git pro sh install-gui.sh .... "

What is wrong?

Please, help me.

Thanks

### Version

latest

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
(venv) [surf@localhost chia-blockchain]$ sh install-gui.sh
install-gui.sh: line 24: type: apt-get: not found
yum is /usr/bin/yum
yum is /usr/bin/yum
Installing on CentOS/Redhat.
 
## Installing the NodeSource Node.js 12.x repo...
 
 
## Inspecting system...
 
+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m
 
## Confirming "el8-x86_64" is supported...
 
+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_12.x/el/8/x86_64/nodesource-release-el8-1.noarch.rpm'
 
## As yum will try to install Node.js from the AppStream repository
instead of the NodeSource repository, the AppStream's version of Node.js has to be disabled.
## Run `sudo yum module enable -y nodejs` to reactivate the AppStream's Node.js repository.
 
+ yum module disable -y nodejs
Last metadata expiration check: 1:04:24 ago on Wed 01 Dec 2021 06:50:04 PM CET.
Dependencies resolved.
Nothing to do.
Complete!
 
## Downloading release setup RPM...
 
+ mktemp
+ curl -sL -o '/tmp/tmp.lnyzutjoHI' 'https://rpm.nodesource.com/pub_12.x/el/8/x86_64/nodesource-release-el8-1.noarch.rpm'
 
## Installing release setup RPM...
 
+ rpm -i --nosignature --force '/tmp/tmp.lnyzutjoHI'
 
## Cleaning up...
 
+ rm -f '/tmp/tmp.lnyzutjoHI'
 
## Checking for existing installations...
 
+ rpm -qa 'node|npm' | grep -v nodesource
 
## Run `sudo yum install -y nodejs` to install Node.js 12.x and npm.
## You may run dnf if yum is not available:
     sudo dnf install -y nodejs
## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn
 
Last metadata expiration check: 1:04:27 ago on Wed 01 Dec 2021 06:50:04 PM CET.
Package nodejs-2:12.22.7-1nodesource.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 
Running git submodule update --init --recursive.
 
Running git submodule update.
 
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN tar ENOENT: no such file or directory, open '/home/surf/chia-blockchain/chia-blockchain-gui/node_modules/.staging/string-width-a2d1f43f/package.json'
 



........ many lines censored




npm WARN tar ENOENT: no such file or directory, open '/home/surf/chia-blockchain/chia-blockchain-gui/node_modules/.staging/@material-ui/core-7807b5a6/styles/withTheme.d.ts'
npm WARN tar ENOENT: no such file or directory, lstat '/home/surf/chia-blockchain/chia-blockchain-gui/node_modules/.staging/@material-ui/core-7807b5a6/withWidth'
npm WARN tar ENOENT: no such file or directory, open '/home/surf/chia-blockchain/chia-blockchain-gui/node_modules/.staging/@material-ui/core-7807b5a6/colors/yellow.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/home/surf/chia-blockchain/chia-blockchain-gui/node_modules/.staging/@material-ui/core-7807b5a6/styles/zIndex.d.ts'
npm WARN tar ENOENT: no such file or directory, lstat '/home/surf/chia-blockchain/chia-blockchain-gui/node_modules/.staging/@material-ui/core-7807b5a6/Zoom'
npm ERR! code 1
npm ERR! Command failed: git checkout master
npm ERR! error: pathspec 'master' did not match any file(s) known to git
npm ERR! 
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/surf/.npm/_logs/2021-12-01T18_38_42_313Z-debug.log
(venv) [surf@localhost chia-blockchain]$ cat /home/surf/.npm/_logs/2021-12-01T18_38_42_313Z-debug.log
......... many lines censored
18770 verbose stack Error: Command failed: git checkout master
18770 verbose stack error: pathspec 'master' did not match any file(s) known to git
18770 verbose stack
18770 verbose stack     at ChildProcess.exithandler (child_process.js:308:12)
18770 verbose stack     at ChildProcess.emit (events.js:314:20)
18770 verbose stack     at maybeClose (internal/child_process.js:1022:16)
18770 verbose stack     at Socket.<anonymous> (internal/child_process.js:444:11)
18770 verbose stack     at Socket.emit (events.js:314:20)
18770 verbose stack     at Pipe.<anonymous> (net.js:675:12)
18771 verbose cwd /home/surf/chia-blockchain/chia-blockchain-gui
18772 verbose Linux 4.18.0-348.2.1.el8_5.x86_64
18773 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
18774 verbose node v12.22.7
18775 verbose npm  v6.14.15
18776 error code 1
18777 error Command failed: git checkout master
18777 error error: pathspec 'master' did not match any file(s) known to git
18778 verbose exit [ 1, true ]
(venv) [surf@localhost chia-blockchain]$
```

**Comment by gerberla** [comment]
Same on 7. Defaulted to the rpm on their site to get my node back up. It's in the `npm install` part.

**Comment by dkoffler** [comment]
Same issue on Ubuntu 20.04

`16831 verbose stack Error: Command failed: git checkout master
16831 verbose stack error: pathspec 'master' did not match any file(s) known to git
16831 verbose stack
16831 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
16831 verbose stack     at ChildProcess.emit (events.js:198:13)
16831 verbose stack     at maybeClose (internal/child_process.js:982:16)
16831 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
16831 verbose stack     at Socket.emit (events.js:198:13)
16831 verbose stack     at Pipe._handle.close (net.js:607:12)
16832 verbose cwd /chia/chia-blockchain/chia-blockchain-gui
16833 verbose Linux 5.11.0-41-generic
16834 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
16835 verbose node v10.19.0
16836 verbose npm  v6.14.4
16837 error code 1
16838 error Command failed: git checkout master
16838 error error: pathspec 'master' did not match any file(s) known to git
16839 verbose exit [ 1, true ]
`

**Comment by emlowe** [comment]
Yes, latest (which is 1.2.11) has this problem because the package json references a github repo that was changed. This has been fixed in main and will be fixed with the next release which will move latest to that release.

Recommend using the package DEB as a workaround. Or git clone main instead of -b latest.

**Comment by notprogrammer** [comment]
Use main branch is not solution for me on CentOS 8. But thanks your for tip.

`npm WARN tar ENOENT: no such file or directory, open '/home/surf/chia-blockchain/chia-blockchain-gui/packages/gui/node_modules/.staging/@material-ui/core-5fdf8199/styles/zIndex.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/home/surf/chia-blockchain/chia-blockchain-gui/packages/gui/node_modules/.staging/@material-ui/core-5fdf8199/Zoom/Zoom.d.ts'
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/xmldom/xmldom.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/surf/.npm/_logs/2021-12-10T14_53_22_006Z-debug.log
lerna ERR! npm install exited 1 in '@chia/gui'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.2.10-dev132 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@1.2.10-dev132 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/surf/.npm/_logs/2021-12-10T14_53_22_140Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.2.10-dev132 postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@1.2.10-dev132 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/surf/.npm/_logs/2021-12-10T14_53_22_220Z-debug.log
(venv) [surf@localhost chia-blockchain]$ `

**Comment by notprogrammer** [comment]
im waiting for bug fix forChia-blockchain-gui installation on Centos 8
