### ISSUE TITLE
[Bug] Pi isn't re-syncing

### ISSUE THREAD

**Issue by paulhainsworth-chia** [Chia-Network/chia-blockchain#9444]
### What happened?

- Pi 4 8gb running latest ubuntu server, no GUI.
- Was accidentally running timelord, farmer, node. Lost sync 11-21 probably because timelord was running
- Stopped all, rebooted machine, started with chia start node
- Synching began from the 11-21 peak and then stopped at 11-30 peak height 1215397
- log screenshots attached

### Version

11.2.11

### What platform are you using?

Pi4

### What ui mode are you using?

CLI

### Relevant log output

![Screen Shot 2021-12-02 at 10 20 03 AM](https://user-images.githubusercontent.com/86693700/144481492-9a0578b9-373a-4ed2-b919-4a726b6efd86.png)
![Screen Shot 2021-12-02 at 10 19 49 AM](https://user-images.githubusercontent.com/86693700/144481506-05d91bdb-0b7c-437b-b501-2b74725d0f5e.png)

**Comment by clablanche** [comment]
The same : I am syncing and when it is finished, It just said "not synced" and does not try to sync anymore (blocked at the last height synced like describe in this issue). I have to restart nodes, then it syncing and at the end the same... I am working on version 1.2.11.
I worked for months before, but from november it does not work anymore. I even tried to reinstall all. I am using the docker image (so Linux based).
