### ISSUE TITLE
[Bug] Can't log in

### ISSUE THREAD

**Issue by Igoros1** [Chia-Network/chia-blockchain#9445]
### What happened?

Can't login with 24 word key 

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by loppefaaret** [comment]
Could you try and describe a bit more detailed, exactly what you are doing, and what is happening ? are you trying to add 24 word mnemonic key, and it fails ? or are you unable to open up the Chia client ?
