### ISSUE TITLE
[Bug] FEDORA 35 - missing MAD MAX and not able to install it from CLI ['chia plotters install madmax' using apt instead dnf/yum]

### ISSUE THREAD

**Issue by big-john666** [Chia-Network/chia-blockchain#9471]
### What happened?

Hello,

Mad Max is missing in plotter list in GUI and it is not possible to install it from cli as it try to use "apt":

[xxxx@yyyy daemon]$ ./chia plotters install madmax
Installing madmax plotter.
Installing dependencies.
sudo: apt: command not found
Exception while installing madmax plotter: Could not install dependencies Command '['sudo', 'apt', 'install', '-y', 'libsodium-dev', 'cmake', 'g++', 'git', 'build-essential']' returned non-zero exit status 1.
[xxxx@yyyy daemon]$ 

Thank you,

BR

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

GUI

### Relevant log output

```shell
[xxxx@yyyy daemon]$ ./chia plotters install madmax
Installing madmax plotter.
Installing dependencies.
sudo: apt: command not found
Exception while installing madmax plotter: Could not install dependencies Command '['sudo', 'apt', 'install', '-y', 'libsodium-dev', 'cmake', 'g++', 'git', 'build-essential']' returned non-zero exit status 1.
[xxxx@yyyy daemon]$
```

**Comment by emlowe** [comment]
Currently, only Ubuntu (possibly other apt using distros) and macOS are supported for the cli option to install madmax.

**Comment by ChiaMineJP** [comment]
This issue will be fixed once https://github.com/Chia-Network/chia-blockchain/pull/11187 is merged and released.

**Comment by InstantAli3n** [comment]
Does this fix 
```
[xxxx@yyyy chia]$ chia plotters install madmax
Installing madmax plotter.
Installing dependencies.
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package libsodium-dev
E: Unable to locate package cmake
E: Unable to locate package g+
E: Unable to locate package git
E: Unable to locate package build-essential
Exception while installing madmax plotter: Could not install dependencies Command '['sudo', 'apt', 'install', '-y', 'libsodium-dev', 'cmake', 'g++', 'git', 'build-essential']' returned non-zero exit status 100.
```

These two packages don't exist on Fedora
libsodium-dev
build-essential

There is
libsodium-devel

I don't know what the equivalent to build-essential is on Fedora

Maybe this will work?
`sudo dnf groupinstall "Development Tools" "Development Libraries"` 
(https://unix.stackexchange.com/questions/1338/what-is-the-fedora-equivalent-of-the-debian-build-essential-package) 

I'm new to Linux, I want to make sure this will work on Fedora

(Is a separate issue?)

**Comment by emlowe** [comment]
Due to limited resources we aren't able to fully support Fedora with all plotters - this will require a community effort and we will look at any PRs as needed. Closing issue
