### ISSUE TITLE
[Bug] 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by programsalon** [Chia-Network/chia-blockchain#9491]
### What happened?

when I ruan chia 1.2.11 and add the keys of my wallet, then show error 'NoneType' object is not subscriptable, 
![image](https://user-images.githubusercontent.com/16360165/144868097-f8ef9bf6-e557-472f-85f1-83aa596c1476.png)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by programsalon** [comment]
python version is 3.9.0

**Comment by OldButtKicking** [comment]
I discovered a work around for this, create a new wallet first then recreate your wallet. Then you can delete the extra one you had to create

**Comment by G10Rg10C** [comment]
restart the pc twice worked for me

**Comment by Tokarzewski** [comment]
I still have this issue. Can this item be back on the open list?

**Comment by ril3y** [comment]
Yup this is still an issue.  It's happening to me too.

**Comment by isralien** [comment]
Same here.

**Comment by Mainned** [comment]
Same here!

**Comment by kalun85** [comment]
To those who have problem, I reverted my Python 3.9 back to 3.8, restart machine, and the problem went away.  Hope this help other's looking for a solution.

**Comment by LewisBristle** [comment]
I had the same issue with Chia and forks. Today I found out following and it's workin. In CLI run _chia.exe keys delete_all_. After run _chia.exe keys add_, and add your favourite mnenomic.

I hope this helps for you all.

**Comment by UncleLarry3256** [comment]
> I had the same issue with Chia and forks. Today I found out the following and it's working. In CLI run _chia.exe keys delete_all_. After run _chia.exe keys add_, and add your favourite mnenomic.
> 
> I hope this helps for you all.

I'm unfamiliar with CLI so forgive me if this sounds, small brain ig, but are you just running that in the Windows Command Prompt or somwhere else? I just was starting to pool and when I came back from a restart I can't login anymore due to this annoying bug.
