### ISSUE TITLE
[Bug] Tried to open wallet on new machine. Stuck at 854,304

### ISSUE THREAD

**Issue by OldButtKicking** [Chia-Network/chia-blockchain#9498]
### What happened?

Add existing cold wallet to machine.
Nodes connected and sync'd the block chain no problem but 7 days later I realize the wallet is stuck at 854,304
It keeps switching between syncing and not synced but never progresses
Have restarted chia but same result

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by OldButtKicking** [comment]
tried to switch back to my farming wallet and now same issue. Stuck and not progressing. Please tell me I don't have to delete wallet and wait another n days for the same issue

**Comment by OldButtKicking** [comment]
why do I never get an answer when I submit an issue? Is it because it is an issue you don't want to admit to?

**Comment by OldButtKicking** [comment]
I changed back to the original wallet and sure enough sill stuck at 854,304. It took 2 days to get to that point. Is my only option to delete the wallet and try again and hope in 2 days I am not in the same state? can someone pleeeeeesse give me some sort of response ???

**Comment by Evgeny-SPB** [comment]
The same problem. Fresh install on fresh Ubuntu Desktop. Took about 5 days to reach this magic number. Then app became unresponsive. After reboot app hangs on "connecting to wallet".
