### ISSUE TITLE
[Suggestion] Chia light wallet

### ISSUE THREAD

**Issue by dharmeshchowdhary** [Chia-Network/chia-blockchain#9511]
I tested out the light wallet and transferred chia to another wallet. I liked it and the fact that the time it took to sync was very less (approx. 5 min - 10 min) and that amazed me. 
I had a suggestion to the developers - 
1. It would be nice to have a keyring for a wallet too just as we have one for the of chia.
2. Please make the sync process a thorough setup, like it would be great to sync all the wallets at the same time than to switch over different keys again and again to sync.

**Comment by loppefaaret** [comment]
Keeping multiple wallets in sync has been a wish for some time now, and we are considering how to do it - https://trello.com/c/T1OrNzU7/643-sync-multiple-private-keys-at-once-in-wallet

**Comment by dharmeshchowdhary** [comment]
And also please add keyring to the light wallet as well

**Comment by Alex11reg** [comment]
Осторожно троянская программа в версии 1.2.11265 легкий кошелек! C:\Users\Александр\AppData\Local\chia-blockchain\app-1.2.11265\resources\app.asar.unpacked\daemon\d3dcompiler_47.dll - модифицированный Win32/TrojanDropper.Delf.OWF

**Comment by emlowe** [comment]
Closing issue as 1.3 integrated all the keyring password controls together with the light wallet in the single chia download. Multiple wallet syncing is outstanding and tracked in other issues
