### ISSUE TITLE
[Bug] 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by overdoignism** [Chia-Network/chia-blockchain#9513]
### What happened?

'NoneType' object is not subscriptable happend when I tring to import my keywords.

Create an new wallet is nothing help. 

And every time retry, I need to input 24 keywords, so annoying!!

I think, it's so basic and so critical, If you cant fix it ASAP, Maybe the XCH price will missing a zero again.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by overdoignism** [comment]
OK, maybe I have a misspelled.

So, Can you check it in input window and make a knowable message?

Or should we go to use CLI ?

**Comment by Nolly51** [comment]
Same problem, my keys have disappeared and impossible to import the seeds, same message object not subscriptable
I verified the seeds several times

**Comment by Nolly51** [comment]
windows - GUI - CHIA 1.2.11

**Comment by loppefaaret** [comment]
> Same problem, my keys have disappeared and impossible to import the seeds, same message object not subscriptable I verified the seeds several times

not entirely the same issue, as you report that your keys have disappeared, whereas overdoignism as just plainly reporting that he gets it when he imports a mnemonic - perhaps we could try and identify why you lost your keys from the system as well ? 

could you both please try and locate your `debug.log` file under `C:\Users\<USERNAME>\.chia\mainnet\log\` and attach it to this issue please ?

**Comment by Nolly51** [comment]
Everything's OK. After a reset I retrieved my wallet

Le jeu. 9 déc. 2021 à 10:08, loppefaaret ***@***.***> a
écrit :

**Comment by G10Rg10C** [comment]
i've the same problem, what should i do?

**Comment by RobertRuisz** [comment]
me too - same here - cant open my wallet - when i enter my recover code (24 Words) i get a 'NoneType' object is not subscriptable, and when i click continue i get a "Fingerprint" message

**Comment by G10Rg10C** [comment]
guys i've just solved, restart the pc twice worked for me, i know it's a stupid solution but try it.

**Comment by RobertRuisz** [comment]
> guys i've just solved, restart the pc twice worked for me, i know it's a stupid solution but try it.

Yes - worked for me too....

**Comment by erosese** [comment]
This error occurs (twice) with me and blocks the farming.

at first it seems as if the CHIA client freezes. the surface, so the GUI is white, no buttons etc. are visible anymore. After restarting the client (must be shot down via the task manager) the key is no longer present and you have to import the new via the passphrase. This does not work then. 

Last time I rebuilt the fullnode completely. A damn whole week :( and now the error comes again :(


![chia_error1](https://user-images.githubusercontent.com/98394744/150969888-30d0b2c3-620d-432a-8a2a-99948c748c49.png)
)

**Comment by Merallak** [comment]
Same problem here. Restarting te PC won´t solve the problem :/

**Comment by wallentx** [comment]
Related to https://github.com/Chia-Network/chia-blockchain/issues/11175
