### ISSUE TITLE
[Bug] inbound TX to light wallet generated addresses don't show up in regular wallet

### ISSUE THREAD

**Issue by bb-hendrik** [Chia-Network/chia-blockchain#9583]
### What happened?

same keys/wallet on client 1 (lightwallet on win11) and client 2 (regular wallet on win10)
both wallets are in sync

inbound TX sent to address generated by regular wallet shows up in both the light wallet and the regular wallet. 
inbound TX sent to address generated by light wallet shows up in light wallet but does NOT show up in regular wallet

not even after 30 minutes. 

-> balances on light wallet and regular wallet are no longer identical (in sync)
tested with multiple addresses generated by keypair in lightwallet. 
those addresses are not found by regular wallet and balance is not aggregated in total balance. 

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
The lite wallet uses a different key derivation for addresses (we are calling them observable), so anything sent to the receive address displayed in the lite wallet will not be seen by the original wallet, as that wallet only expects hardened derivations. The lite wallet will show balances sent to either type of address derivation, but the original wallet does not.

This behavior is expected (but is admittedly unfortunate, however, it's the cost to move to a derivation model that allows for some other functionality - like observer-only wallets)

**Comment by bb-hendrik** [comment]
Hi emlowe. 
thanks for this answer. I was afraid it was in that direction. 

To a general user this answers compares to this: You are accessing your bank account through your smartphone app and it turns out you're not seeing your entire bank balance. The bank then says: please use the browser on your desktop computer to login to internet banking, or go to an ATM to check your balance using your debit card. You'll then see your full balance of your checking account. 

It renders the app unreliable and unusable. 

When will there be a fix? 

I don't have the list of generated receive addresses from the light-wallet. If I've ever used the light-wallet I can no longer rely on the balance of the regular wallet. 

Isn't this something that should be very explicitly be documented with a big warning sign when you install the light-wallet?

**Comment by emlowe** [comment]
The main "app" will be updated to basically include the lite wallet - in which case that version will be consistent going forward (at this point the lite wallet as a standalone install may go away)

There will be a backwards compatibility issue going forward with prior versions and we will have documentation for this.
