### ISSUE TITLE
Light Wallet Tx does not reflect on the Full Client Wallet

### ISSUE THREAD

**Issue by nanciog** [Chia-Network/chia-blockchain#9585]
I noticed that the balance in my light wallet is not the same as that on the full client wallet. I looked further and found that there are transactions I have received in the light wallet that does not register in the full client wallet.

I am not very technical so I don't know if both wallets are supposed to sync one way only; meaning that transactions on the full client wallet reflect on the light wallet but transactions on the light wallet is independent (does not reflect) on the full client wallet.

I looked around the issues put forward and have not found any similar issues reported so I just wanted to point it out if this is not supposed to be so.

Let me know what else I need to provide to help with this issue if this needs further investigation.

**Comment by emlowe** [comment]
The lite wallet uses a different key derivation for addresses (we are calling them observable), so anything sent to the receive address displayed in the lite wallet will not be seen by the original wallet, as that wallet only expects hardened derivations. The lite wallet will show balances sent to either type of address derivation, but the original wallet does not.

This behavior is expected (but is admittedly unfortunate, however, it's the cost to move to a derivation model that allows for some other functionality - like observer-only wallets)

**Comment by youngfong13** [comment]
This expected behavior is not acceptable from a user perspective and I can't imagine it will meet user expectations.

**Comment by emlowe** [comment]
We will have more documentation coming soon on this change. Perhaps I wasn't clear, but the "full client" will be upgraded in the near future to use the lite wallet functionality. At that point, going _forward_ from that version there will be no issues.

**Comment by youngfong13** [comment]
@emlowe Thanks for the clarification! That makes much more sense.

**Comment by youngfong13** [comment]
> 



> We will have more documentation coming soon on this change. Perhaps I wasn't clear, but the "full client" will be upgraded in the near future to use the lite wallet functionality. At that point, going _forward_ from that version there will be no issues.

Does that include the wallet on the CLI?

**Comment by emlowe** [comment]
Yes (both the CLI and the UI are essentially front-ends on top of the wallet backend)

**Comment by nanciog** [comment]
Thank you for the clarification. I am just sending feedback as per my usages just in case these problems have not yet been documented so they can be addressed.

On another note on lite wallet and full client not having the same transactions, I have sent an outgoing payment from the full client this time around and that transaction is not reflecting on the lite wallet either. Based on the explanation above about certain wallet really being programmed to not see all transactions I would assume this is the case here as well but wanted to raise it in case that is not so.
