### ISSUE TITLE
[Bug] Farming No Plots problem

### ISSUE THREAD

**Issue by ThemeSama** [Chia-Network/chia-blockchain#9598]
### What happened?

Hi everyone,

We have 1664 plots. Everything was fine until December 5th. Farming hasn't seen the plots for 12 days. I was running ```chia plots check``` and everything is fine. Wallet height is increasing. ```chia farm challenges``` is done but if i run ```chia farm summary``` 

```
Farming status: Farming
Total chia farmed: 6.0
User transaction fees: 0.0
Block rewards: 6.0
Last height farmed: 1026672
Plot count for all harvesters: 0
Total size of plots: 0.000 MiB
Estimated network space: 32.889 EiB
Expected time to win: Never (no plots)
```
Is this a bug for this cli command? By the way the GUI doesn't work either (Can't see plots).

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by IanVand** [comment]
I have the same problem. I have ~1100 plots and after upgrading from 1.2.6 to 1.2.11, chia no longer sees the plots in both the CLI and the GUI. I am on Ubuntu.

**Comment by ThemeSama** [comment]
Maybe I return 1.2.10, if no one help us.

**Comment by ThemeSama** [comment]
> This issue has not been updated in 14 days and is now flagged as stale. If this issue is still affecting you and in need of further review, please comment on it with an update to keep it from auto closing in 7 days.

Thanks bot

**Comment by emlowe** [comment]
Please provide relevant log output from the chia log in INFO mode. The log hopefully indicates what the problem is

**Comment by ThemeSama** [comment]
I solved with remove ~/.chia folder and resync again.
