### ISSUE TITLE
[Bug] install.sh forces python upgrade to latest, but chia only works with <= python 3.9.9

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#9627]
### What happened?

This line https://github.com/Chia-Network/chia-blockchain/blob/main/install.sh#L87 executes an install of the latest Python version in the Arch repo, which as of writing this is: 3.10.1. The Chia daemon is unable to launch with an installed Python > 3.9.9.

I'll be submitting a PR to account for this.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by markusmazurczak** [comment]
After updating archlinux python 3.10 was installed which caused that the chia-daemon was unable to start. After quickly applying your fix, I was able to get things back running. Thx
