### ISSUE TITLE
[Bug] farming node caching 

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-blockchain#9635]
### What happened?

after running a long-time farm node, the memory usage scale from 2.5G to 5.8G and cause the system very slowly.
and also cause farmers to lose connection, is this problem with my CPU ? or the software?

### Version

master 

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
Can you please provide some more details on your setup? Number of plots, number of harvesters, etc. Also please clarify how long "a long-time" is?
