### ISSUE TITLE
[Bug]  OOM related problem

### ISSUE THREAD

**Issue by Xinrea** [Chia-Network/chia-blockchain#9652]
### What happened?

Recently, I found some problems while running fullnode, similar to #8908 and some syncing hang issues. My service need to use fullnode rpc so these problems make me have to restart fullnode regularly.
Most of the time it's caused by oom even though there is already 8g of memory, and if I provides 16g of memory it works fine, but when it runs steady I noticed that fullnode usualy only takes about 4g.
I suspect that the problem is in the block data checksum when the node starts because many nodes synchronized from 0 do not have this problem. As the block height increases this problem appears more and more frequently.
I hope there is a way to solve the problem of memory usage.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by durdin85** [comment]
The chia node seems increases memory requirements over time. I've got best luck with plying with sysctl and setting very low value of ``` vm.swappiness``` where adjusting the ```vm.overcommit_ratio``` and also adjusting the ```/proc/CHIA_PID/oom_score_adj```, but the chia daemon got killed eventually anyway, so some automated cron restarts are a must in low-memory environments and I would be also happy to see chia run on much lower memory footprint.
Btw just now I see the full node is allocating 5.3 GB memory, wallet 1.5 GB, harvester 0.7 GB, and daemon 0,3 GB...

**Comment by mariano54** [comment]
This is not fixed
