### ISSUE TITLE
Chia has security holes

### ISSUE THREAD

**Issue by superman00111** [Chia-Network/chia-blockchain#9653]
Due to the peer node IP without encryption, a large number of friends XCH is stolen, "xch19h9y49xwz0h99tfrc5p3fxlrcrtk7dkzhuauk7atje2hhxa0nrsqhxm0z5" and send to the same address. Please add the secondary transaction password in the next version. Please deal with it asap!

**Comment by shaneo257** [comment]
Are your friends running any forks
Are your friends running any 3rd party tools/monitoring?
Did they download the chia client from official means?

**Comment by shaneo257** [comment]
also, suggest they follow this guide on how to become a hard target
https://www.chia.net/2021/05/28/securing-your-chia-how-to-be-a-hard-target.en.html

**Comment by emlowe** [comment]
There is no listed nor suggested security holes - closing issue.
