### ISSUE TITLE
[Bug] peer banning policy affects chia network connectivity

### ISSUE THREAD

**Issue by iliasorazov** [Chia-Network/chia-blockchain#9661]
### What happened?

My node is periodically disconnecting and banning other peers, the most common reason is `Peer has been rate limited and will be disconnected: ..., message: new_compact_vdf` the next common reason is `Failed to fetch block ... from ..., timed out`. Sometimes it bans all the peers and left completely disconnected from the network. I don't see any high cpu usage recently, blocks are rarely filled to more than 15%. Yesterday I've observed a period in time when node-eu.chia.net was 1000 blocks below the peak, so it is probably also affected. If my guess is correct and it not only affects me then the actual reason of bad chia network performance is buggy ban policies and not some mythical dust storms, or.. maybe both.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by iliasorazov** [comment]
I am trying to figure out reasons of this errors and the second one really puzzles me.

https://github.com/Chia-Network/chia-blockchain/blob/b74a3f3849cadeece2fac3efa3cb55d7d3a0647f/chia/full_node/full_node.py#L426-L428

first of all, peer is of type `ws.WSChiaConnection` here and this class do not have a `request_block` method. The only class that has it is `FullNodeAPI` but it always returns a value.

https://github.com/Chia-Network/chia-blockchain/blob/b74a3f3849cadeece2fac3efa3cb55d7d3a0647f/chia/full_node/full_node_api.py#L305-L320

what is going on here?

**Comment by mariano54** [comment]
Interesting. The other peer should stop sending you stuff before it hits the rate limit. Perhaps this was changed in one of the versions. Rate limits are hard to change because some nodes will disconnect others which have different limits.

With respect to the `request_block` method, that is calling this method:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/server/ws_connection.py#L285
