### ISSUE TITLE
[Bug] "chia wallet new_address" No such command

### ISSUE THREAD

**Issue by ruixingchen** [Chia-Network/chia-blockchain#9664]
### What happened?

```- You can obtain a new wallet receive address on the command line with `chia wallet new_address`. Thanks to @jespino for this and a lot more in the next section below.```

but that new_address never happens, I run the command but chia tells me "No such command 'new_address'"

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

CLI

### Relevant log output

```shell
Usage: chia wallet [OPTIONS] COMMAND [ARGS]...
Try 'chia wallet -h' for help.

Error: No such command 'new_address'.
```

**Comment by emlowe** [comment]
The command is `chia wallet get_address` - that information is from pre-release notes and has changed in the interim
