### ISSUE TITLE
(solved) connot install chia after archlinux upgrade (python 3.10)

### ISSUE THREAD

**Issue by Eridanin** [Chia-Network/chia-blockchain#9665]
`Building wheels for collected packages: chiavdf, chia-blockchain
  Building wheel for chiavdf (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:

  vdf_client.cpp:1:10: fatal error: boost/asio.hpp: No such file or directory
      1 | #include <boost/asio.hpp>
        |          ^~~~~~~~~~~~~~~~
`

**Comment by Eridanin** [comment]
solved by installing boost asio libs

**Comment by Eridanin** [comment]
chia daemon doesn't start with python 3.10. Downgraded to python 3.9

**Comment by emlowe** [comment]
Closing issue - python 3.10 support is a known issue at this time

**Comment by mariano54** [comment]
@Eridanin how did you install boost libs? I'm still getting the boost issue.

**Comment by Eridanin** [comment]
> @Eridanin how did you install boost libs? I'm still getting the boost issue.

I am on Archlinux, so it was `sudo pacman -S asio`
