### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by manprinsen** [Chia-Network/chia-blockchain#9666]
I’m expiring memory leak on my chia full node. The start_full_node.exe increment it’s memory usage by 10 mb every 5 seconds.

I’m running chia gui 1.2.11 on Windows 10 enterprise ltsc 17763

**Comment by brause** [comment]
and it peaks out at around 2.1-2.5GB ?

**Comment by manprinsen** [comment]
No, it is increasing. I restarted the pc last Wednesday, then the memory usage of cha process where 1GB (pc has 16gb and there are nothing else that uses that much ram).

ATM, the chia exe uses 4GB of memory.

**Comment by karstenbruch** [comment]
yes and it will stay that way.

**Comment by manprinsen** [comment]
@karstenbruch what do you mean? it cannot be normal that the memory usage increases until the pc is out of memory.
the result of this is ofc that the chia full node crashes.

**Comment by karstenbruch** [comment]
@manprinsen chia can be run on a 4gb raspberrypi4 without gui. It depends what you use. It will not increase above that. by stay i meant it will stay with 4GB.

**Comment by manprinsen** [comment]
@karstenbruch thank you for clearing that up. i will monitor it!

**Comment by OldButtKicking** [comment]
![image](https://user-images.githubusercontent.com/58090640/148661891-b2f6ec57-b3fc-40d9-bf03-a5770c32f86d.png)
mine is currently using ~6.5 gb

**Comment by manprinsen** [comment]
This may be a little of topic. But can I run a chia full node without gui? It would be a interesting test.

I do have another pc which only runs the harvester using the cli and it is working great with 400TB of plots.

**Comment by brause** [comment]
Yes, you can. Use the command line to start:
https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference

The gui - as any gui - does use quite a lot of memory. You will see.

I run a harvester alone on a minecraft server of mine and it barely makes a dent.

**Comment by manprinsen** [comment]
well, @brause , your statement does not seem to be true that the chia full node (exe) only allocates maximum 4GB's of RAM.
ATM the RAM usage is 5.5GB but yesterday it where 6.5GB.

There must be more ppl like me having this issue? 

<img width="667" alt="Screenshot 2022-01-15 at 08 52 42" src="https://user-images.githubusercontent.com/24879444/149614465-d41ff9e2-97cc-42ee-92a5-e7721b0de173.png">


<img width="1440" alt="Screenshot 2022-01-15 at 08 56 22" src="https://user-images.githubusercontent.com/24879444/149614472-9ceb89ce-a48c-40e4-8216-d96f61302d9b.png">

**Comment by brause** [comment]
Hi @manprinsen,
interesting. I have this:
![image](https://user-images.githubusercontent.com/6328682/149616739-54e082da-c54c-4e83-80e6-cd2d52000890.png)

**Comment by brause** [comment]
A memory leak would have crashed your node. My layman answer is there is no discernable leak.

I certainly see none of this "increment it’s memory usage by 10 mb every 5 seconds".

I would have been out of memory weeks ago.

**Comment by brause** [comment]
hahaha, the windows taskmanager seems to be kind of useless in this case. Ignore the screenshot of the windows taskmanager. There are more tasks sprinkled about in this "tool".

**Comment by atomsymbol** [comment]
@manprinsen The `blockchain_v1_mainnet.sqlite` is a memory-mapped file. If the machine is under memory pressure the operating system will automatically unmap **unmodified** mapped pages from memory or save **modified** mapped pages back to the file. Starting another memory-intensive app might force the operating system to perform the unmapping and saving. The memory consumption might depend on Sqlite's configuration.

@brause Your posts are pointless.

**Comment by manprinsen** [comment]
> A memory leak would have crashed your node. My layman answer is there is no discernable leak.
> 
> I certainly see none of this "increment it’s memory usage by 10 mb every 5 seconds".
> 
> I would have been out of memory weeks ago.

Well, it WILL crash when I am out of memory.

**Comment by manprinsen** [comment]
> @manprinsen The `blockchain_v1_mainnet.sqlite` is a memory-mapped file. If the machine is under memory pressure the operating system will automatically unmap **unmodified** mapped pages from memory or save **modified** mapped pages back to the file. Starting another memory-intensive app might force the operating system to perform the unmapping and saving. The memory consumption might depend on Sqlite's configuration.
> 
> @brause Your posts are pointless.

Thanks very much for your in depth reply!

**Comment by brause** [comment]
ok guess you are right, so where exactly is the memory leak which is the point of this ? Otherwise @manprinsen should just close this.

**Comment by manprinsen** [comment]
i did hope that a chia-developer would have a look at this or at least have some tips of troubleshoot this.
but i dont care anymore and are closing this............
