### ISSUE TITLE
[Bug] 1.2.12124 Pool connect

### ISSUE THREAD

**Issue by Michaul** [Chia-Network/chia-blockchain#9687]
### What happened?

![image](https://user-images.githubusercontent.com/27682019/147598399-52d51087-888c-4624-91ad-a4896bbef79e.png)

### Version

1.2.12124

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by shaneo257** [comment]
looks like your not running the correct version, and running a beta version of the node software
