### ISSUE TITLE
Transactions time in wallet is incorrect

### ISSUE THREAD

**Issue by forReason** [Chia-Network/chia-blockchain#9696]
When syncing the wallet on my home Computer the block times are displayed correctly every other block or so
![blocktimes_correct](https://user-images.githubusercontent.com/12736950/147703077-bb72f8fe-b654-4d05-890e-b8ae0b6f7de3.png)

In contrast, in the wallet, the transactions do not show the last known blocktime but the time at which the block was synced to the local wallet.

This is an issue if I only open the wallet at home, say every 3 Months. All transactions then have the current datetime and the overview of the incoming transactions is incorrect.

![transactions](https://user-images.githubusercontent.com/12736950/147703269-7c21663f-1eb0-431b-96e5-a82bb19329bd.png)

**Comment by shaneo257** [comment]
Hi,

This is a known issue where it it doesnt show the correct time/date if you resync your wallet

**Comment by shaneo257** [comment]
not a stale issue

**Comment by forReason** [comment]
hmm. I cant reopen?
