### ISSUE TITLE
[Bug] wrong value of db_sync in config.yaml

### ISSUE THREAD

**Issue by allenpoon** [Chia-Network/chia-blockchain#9698]
### What happened?

If I set the db_sync to 'on' or 'off', it will change to 'true' or 'false' after chia started

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
This seems to be a side effect of the yaml parser - it translates automatically `on` to `true` and `off` to `false`.

**Comment by arvidn** [comment]
I suppose you need quotes for those values.
