### ISSUE TITLE
Same wallet, different balance[Bug] 

### ISSUE THREAD

**Issue by navyfeng** [Chia-Network/chia-blockchain#9699]
### What happened?

Same wallet, different balance
wallet version: 1.2.11, 1.2.5
![0e7b0f4533267ef25e9348777d9ac76](https://user-images.githubusercontent.com/1535983/147745215-bdb818a5-4812-4ad9-b85b-54b63fc49b46.png)
![e60d34e152ed89a5ff852784368bfa5](https://user-images.githubusercontent.com/1535983/147745275-3346a034-daa5-43f6-b82d-056af92e8ffe.png)

### Version

1.2.11 & 1.2.5

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by emlowe** [comment]
For some people with older wallet with a few transactions, syncing it fresh can result in missing XCH because the wallet doesn't look for enough addresses. 

Please try changing `initial_num_public_keys_new_wallet` in config.yaml to 100 and then resync the wallet again.

**Comment by navyfeng** [comment]
> For some people with older wallet with a few transactions, syncing it fresh can result in missing XCH because the wallet doesn't look for enough addresses.
> 
> Please try changing `initial_num_public_keys_new_wallet` in config.yaml to 100 and then resync the wallet again.

Thanks
