### ISSUE TITLE
[Bug] Intermittent problem with long sync times on the light wallet

### ISSUE THREAD

**Issue by danieljperry** [Chia-Network/chia-blockchain#9706]
### What happened?

Syncing the light wallet sometimes takes a very long time. Typically it needs less than three minutes, but sometimes I've given up after an hour and deleted my wallet db, after which point it syncs quickly again.
 
Unfortunately, I have been unable to reproduce this problem with a log file that I can submit. I've been testing offers extensively, so the long sync times may be related. I've also been using CATs and multiple wallets on one machine. I've tried stopping my node for 8 hours, but it seems to sync quickly again.

There is definitely an issue here that will cause frustration for a certain number of users. I'll be sure to post a log file once I'm able to reproduce this problem.

### Version

pacr_dev branch from Dec 23

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by mariano54** [comment]
Can you set logging to DEBUG and show the log? Where is it getting stuck?
@Yostra can you take a look?

**Comment by danieljperry** [comment]
I'm sorry but I haven't been able to reproduce it for the last several days. I wonder if it has already been fixed?

**Comment by danieljperry** [comment]
I'm going to close this until I can reproduce it with a log file.
