### ISSUE TITLE
[BUG] Building from main creates 1.0rc3.dev0 instead of 1.0rc2

### ISSUE THREAD

**Issue by wallentx** [Chia-Network/chia-blockchain#971]
This may be more of a one-off, rather than a bug, but with each release, I usually just `git pull` from `main` and reinstall, then `chia init`. When I did it just a moment ago, I noticed the folder it created was `~/.chia/1.0rc3.dev0`, rather than the `1.0rc2` folder that I was expecting. Also, the wallet didn't seem to want to connect when I launched the GUI, but I didn't look into that too much.

I pulled down the `.zip` source from the 1.0rc2 release assets, and tried to build it after decompressing the archive, but the install fails due to `setuptools-scm` needing `.git` resources, which aren't within the release assets.

I got things to work by doing:
`git checkout tags/1.0rc2` then going through the install process again, and `chia init` creates the expected `~/.chia/1.0rc2` directory, and the GUI loads up my wallet pretty much right away.

**Comment by mariano54** [comment]
Did you do:
git pull 
git pull --tags

**Comment by hoffmang9** [comment]
Alternatively git checkout 1.0rc2
