### ISSUE TITLE
[BUG] PlotNFTs not displayed after clean install

### ISSUE THREAD

**Issue by defaultsecurity** [Chia-Network/chia-blockchain#9733]
### What happened?

- After a clean install and entering mnemonics, the pool tab is empty and does not show previous PlotNFTs.
- **I have to create and add a new PlotNFT to the blockchain to get my previous PlotNFTs to show up.**
- This is a waste of resources on the client side and on the blockchain. I can't believe this hasn't been fixed yet.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by defaultsecurity** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/8547

**Comment by defaultsecurity** [comment]
Also to: https://github.com/Chia-Network/chia-blockchain/issues/9162

**Comment by shaneo257** [comment]
the plot nft wont show until your wallet has synced past the block height of when you created the nft, no need to create a new one each time

**Comment by defaultsecurity** [comment]
I did some testing. You are actually right @shaneo257 . After install I copied over the previous blockchain db and wallet db and the PlotNFTs didn't show. After deleting the wallet db and letting it resync the PlotNFTs showed up and were added to the config.yaml.

### Solution:
**Delete the wallet db and let it resync.**
