### ISSUE TITLE
[Bug] GENERATOR_RUNTIME_ERROR raised   Creating a multiple mint CAT

### ISSUE THREAD

**Issue by easylives** [Chia-Network/chia-blockchain#9743]
### What happened?

I followed the tutorials "Creating a multiple mint CAT" linked below，but an error

```("{'error': 'Failed to include transaction "
 '79dbe19341d1e6b787b6133099448e1b8301b0e75298a033a16ad99278035abc, error '
 "GENERATOR_RUNTIME_ERROR', 'success': False}")
```
raied.

[https://chialisp.com/docs/tutorials/CAT_Launch_Process_Linux_MacOS](https://chialisp.com/docs/tutorials/CAT_Launch_Process_Linux_MacOS)

### my steps:

wallet_address:
*txch1jq0wd7q3r7hruzc2ee8kan2p65f074dxjh5c6e5yn44effevk2mqcgtwhj*

master_publick_key:
*ad588f4b093dc221e1dc8c1607156ddab4ac131ff54eb80bcb4f69e6fa5dfb4f76b96a7f99a5ffbb212302b05d0f5a6e*

```
cats --tail ./reference_tails/delegated_tail.clsp.hex --curry 0xad588f4b093dc221e1dc8c1607156ddab4ac131ff54eb80bcb4f69e6fa5dfb4f76b96a7f99a5ffbb212302b05d0f5a6e --send-to txch1jq0wd7q3r7hruzc2ee8kan2p65f074dxjh5c6e5yn44effevk2mqcgtwhj -a 20000 --as-bytes --select-coin
```
coin id:
*830111fc660e83f522803b6eac9659a0690f5bfb2b7bfff5ca17e9f0c65f1740*
```
cdv clsp curry ./reference_tails/genesis_by_coin_id.clsp.hex -a 0x830111fc660e83f522803b6eac9659a0690f5bfb2b7bfff5ca17e9f0c65f1740 --treehash
```
ph:
*e216d99bcdbf104a0e55ac87275a93a08481ed8fa5c1e3d31141d976cc3f62b7*

fingerprint:
*945233328*
```
chia keys sign -d e216d99bcdbf104a0e55ac87275a93a08481ed8fa5c1e3d31141d976cc3f62b7 -f 945233328 -t m -b
```

sign:
*b1c1b3a4dd0860f2834f8a34f4df32e3a8cab7bd952fa4babbddd21f8b28d2d2baa34a44404f92f988c75fdc2b1d65cd08bc622628c60fe3376913fb1c98e2c6afb1c462f9c5d0bea6ba76615070c7f708a00552686ace2e4fec56bb34cbf81d*

```
cats --tail ./reference_tails/delegated_tail.clsp.hex --curry 0xad588f4b093dc221e1dc8c1607156ddab4ac131ff54eb80bcb4f69e6fa5dfb4f76b96a7f99a5ffbb212302b05d0f5a6e --send-to txch1jq0wd7q3r7hruzc2ee8kan2p65f074dxjh5c6e5yn44effevk2mqcgtwhj -a 20000 --as-bytes --solution "(e216d99bcdbf104a0e55ac87275a93a08481ed8fa5c1e3d31141d976cc3f62b7 ())" --signature b1c1b3a4dd0860f2834f8a34f4df32e3a8cab7bd952fa4babbddd21f8b28d2d2baa34a44404f92f988c75fdc2b1d65cd08bc622628c60fe3376913fb1c98e2c6afb1c462f9c5d0bea6ba76615070c7f708a00552686ace2e4fec56bb34cbf81d
```

assert id:88cea92795206294825a1782a684579fe42a4320211f23e7c43bf312244efe4a
spend_bundle: 
*000000026d68ae429040e2d9b3813f1a51592e5bad6dadfa0e78350272d07dd5e6f14af5901ee6f8111fae3e0b0ace4f6ecd41d512ff55a695e98d66849d6b94a72cb2b6000000174876e800ff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0a5e78ca7174491bdac536df5affb52e97253ec8a66e5375713fdbbff422a2e34f6992aa4c2f20b04b884654159d7fb09ff018080ff80ffff01ffff33ffa0f85f1fe04afe663b73d38f2bb5bc9eaac0212432427dc426724a776e49c67619ff824e2080ffff33ffa099fab77d3fb848267a465f987e1ebfdbf8d9a4531000fc95cadbc59232699c30ff8517487699e080ffff3cffa052d4a883e55975e06ea822172a113e24787c4e46324b2f7f60ba547b58ce90928080ff8080830111fc660e83f522803b6eac9659a0690f5bfb2b7bfff5ca17e9f0c65f1740f85f1fe04afe663b73d38f2bb5bc9eaac0212432427dc426724a776e49c676190000000000004e20ff02ffff01ff02ffff01ff02ff5effff04ff02ffff04ffff04ff05ffff04ffff0bff2cff0580ffff04ff0bff80808080ffff04ffff02ff17ff2f80ffff04ff5fffff04ffff02ff2effff04ff02ffff04ff17ff80808080ffff04ffff0bff82027fff82057fff820b7f80ffff04ff81bfffff04ff82017fffff04ff8202ffffff04ff8205ffffff04ff820bffff80808080808080808080808080ffff04ffff01ffffffff81ca3dff46ff0233ffff3c04ff01ff0181cbffffff02ff02ffff03ff05ffff01ff02ff32ffff04ff02ffff04ff0dffff04ffff0bff22ffff0bff2cff3480ffff0bff22ffff0bff22ffff0bff2cff5c80ff0980ffff0bff22ff0bffff0bff2cff8080808080ff8080808080ffff010b80ff0180ffff02ffff03ff0bffff01ff02ffff03ffff09ffff02ff2effff04ff02ffff04ff13ff80808080ff820b9f80ffff01ff02ff26ffff04ff02ffff04ffff02ff13ffff04ff5fffff04ff17ffff04ff2fffff04ff81bfffff04ff82017fffff04ff1bff8080808080808080ffff04ff82017fff8080808080ffff01ff088080ff0180ffff01ff02ffff03ff17ffff01ff02ffff03ffff20ff81bf80ffff0182017fffff01ff088080ff0180ffff01ff088080ff018080ff0180ffff04ffff04ff05ff2780ffff04ffff10ff0bff5780ff778080ff02ffff03ff05ffff01ff02ffff03ffff09ffff02ffff03ffff09ff11ff7880ffff0159ff8080ff0180ffff01818f80ffff01ff02ff7affff04ff02ffff04ff0dffff04ff0bffff04ffff04ff81b9ff82017980ff808080808080ffff01ff02ff5affff04ff02ffff04ffff02ffff03ffff09ff11ff7880ffff01ff04ff78ffff04ffff02ff36ffff04ff02ffff04ff13ffff04ff29ffff04ffff0bff2cff5b80ffff04ff2bff80808080808080ff398080ffff01ff02ffff03ffff09ff11ff2480ffff01ff04ff24ffff04ffff0bff20ff2980ff398080ffff010980ff018080ff0180ffff04ffff02ffff03ffff09ff11ff7880ffff0159ff8080ff0180ffff04ffff02ff7affff04ff02ffff04ff0dffff04ff0bffff04ff17ff808080808080ff80808080808080ff0180ffff01ff04ff80ffff04ff80ff17808080ff0180ffffff02ffff03ff05ffff01ff04ff09ffff02ff26ffff04ff02ffff04ff0dffff04ff0bff808080808080ffff010b80ff0180ff0bff22ffff0bff2cff5880ffff0bff22ffff0bff22ffff0bff2cff5c80ff0580ffff0bff22ffff02ff32ffff04ff02ffff04ff07ffff04ffff0bff2cff2c80ff8080808080ffff0bff2cff8080808080ffff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff2effff04ff02ffff04ff09ff80808080ffff02ff2effff04ff02ffff04ff0dff8080808080ffff01ff0bff2cff058080ff0180ffff04ffff04ff28ffff04ff5fff808080ffff02ff7effff04ff02ffff04ffff04ffff04ff2fff0580ffff04ff5fff82017f8080ffff04ffff02ff7affff04ff02ffff04ff0bffff04ff05ffff01ff808080808080ffff04ff17ffff04ff81bfffff04ff82017fffff04ffff0bff8204ffffff02ff36ffff04ff02ffff04ff09ffff04ff820affffff04ffff0bff2cff2d80ffff04ff15ff80808080808080ff8216ff80ffff04ff8205ffffff04ff820bffff808080808080808080808080ff02ff2affff04ff02ffff04ff5fffff04ff3bffff04ffff02ffff03ff17ffff01ff09ff2dffff0bff27ffff02ff36ffff04ff02ffff04ff29ffff04ff57ffff04ffff0bff2cff81b980ffff04ff59ff80808080808080ff81b78080ff8080ff0180ffff04ff17ffff04ff05ffff04ff8202ffffff04ffff04ffff04ff24ffff04ffff0bff7cff2fff82017f80ff808080ffff04ffff04ff30ffff04ffff0bff81bfffff0bff7cff15ffff10ff82017fffff11ff8202dfff2b80ff8202ff808080ff808080ff138080ff80808080808080808080ff018080ffff04ffff01a072dec062874cd4d3aab892a0906688a1ae412b0109982e1797a170add88bdcdcffff04ffff01a088cea92795206294825a1782a684579fe42a4320211f23e7c43bf312244efe4affff04ffff01ff01ffff33ff80ff818fffff02ffff01ff02ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff82027fff80808080ff80808080ffff02ff82027fffff04ff0bffff04ff17ffff04ff2fffff04ff5fffff04ff81bfff82057f80808080808080ffff04ffff01ff31ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b0ad588f4b093dc221e1dc8c1607156ddab4ac131ff54eb80bcb4f69e6fa5dfb4f76b96a7f99a5ffbb212302b05d0f5a6eff018080ffffc04065323136643939626364626631303461306535356163383732373561393361303834383165643866613563316533643331313431643937366363336636326237ff808080ffff33ffa0901ee6f8111fae3e0b0ace4f6ecd41d512ff55a695e98d66849d6b94a72cb2b6ff824e20ffffa0901ee6f8111fae3e0b0ace4f6ecd41d512ff55a695e98d66849d6b94a72cb2b6808080ff0180808080ff80ff80ffa0e1befbb92544a95770ae868a6aaf7134b1d1e5ce20670138a1c1ef0611e37a8dffffa0830111fc660e83f522803b6eac9659a0690f5bfb2b7bfff5ca17e9f0c65f1740ffa0f85f1fe04afe663b73d38f2bb5bc9eaac0212432427dc426724a776e49c67619ff824e2080ffffa0830111fc660e83f522803b6eac9659a0690f5bfb2b7bfff5ca17e9f0c65f1740ffa0ebcd7960978c7202a58b1ae579db02e3359f59aaed22cfb8afaea115d7089d11ff824e2080ff80ff8080863590e764459d0058ae21851118c4b5493b210211f4928509a2a7caf344518e939296aae598a762a2435d507f482afd1215c1ec0e3da6e37d9d6c08671b49419bfb80d3d90a55af93a4b31f16bc255f3eac8f8687b77aaa4619a4c0c9bdd884*

``` 
cdv rpc pushtx <spend_bundle>
```

```
("{'error': 'Failed to include transaction "
 '79dbe19341d1e6b787b6133099448e1b8301b0e75298a033a16ad99278035abc, error '
 "GENERATOR_RUNTIME_ERROR', 'success': False}")
```
----

### more info

```
chia show wallet
```
```
Choose wallet key:
1) 3678822947
2) 3001635724
3) 945233328
```
```
 chia wallet show -f 945233328
```
```
Wallet height: 1116346
Sync status: Synced
Balances, fingerprint: 945233328
Wallet ID 1 type STANDARD_WALLET Chia Wallet
   -Total Balance: 0.1 txch (100000000000 mojo)
   -Pending Total Balance: 0.1 txch (100000000000 mojo)
   -Spendable: 0.1 txch (100000000000 mojo)

```

### Version

1.2.11.dev264

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
2022-01-07T17:52:59.897 full_node chia.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "/root/protocol_and_cats_rebased/chia-blockchain/chia/rpc/rpc_server.py", line 83, in inner
    res_object = await f(request_data)
  File "/root/protocol_and_cats_rebased/chia-blockchain/chia/rpc/full_node_rpc_api.py", line 536, in push_tx
    raise ValueError(f"Failed to include transaction {spend_name}, error {error.name}")
ValueError: Failed to include transaction 79dbe19341d1e6b787b6133099448e1b8301b0e75298a033a16ad99278035abc, error GENERATOR_RUNTIME_ERROR
```

**Comment by jiuzhuc** [comment]
i have the same issue when i create a Single Issuance CATs,  but i pushed it to testnet10. how do you fix it?

**Comment by 4oooo4** [comment]
I have exactly same error using simulator, i followed this page https://docs.chia.net/guides/cat-creation-tutorial, Creating a Single Issuance CAT <- works, Creating a Multiple Issuance CAT <- doesn't

`chia version: 2.5.7`

```Traceback (most recent call last):

  File "/chia-blockchain/chia/full_node/mempool_manager.py", line 453, in pre_validate_spendbundle

    sbc, new_cache_entries, duration = await asyncio.get_running_loop().run_in_executor(

                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: ('ValidationError', 117)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/chia-blockchain/chia/full_node/full_node.py", line 501, in _handle_one_transaction

    inc_status, err = await self.add_transaction(entry.transaction, entry.spend_name, peer, entry.test)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/chia-blockchain/chia/full_node/full_node.py", line 2782, in add_transaction

    cost_result = await self.mempool_manager.pre_validate_spendbundle(transaction, spend_name, self._bls_cache)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/chia-blockchain/chia/full_node/mempool_manager.py", line 466, in pre_validate_spendbundle

    raise ValidationError(error)

chia.util.errors.ValidationError: Error code: GENERATOR_RUNTIME_ERROR 

2026-02-08T17:56:58.751 2.5.7 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'GENERATOR_RUNTIME_ERROR',

 'status': 3,

 'txid': '0x0e2d1f2612f15e620759896425b6cb251a40e1f3a608636ea16837c7c06a7212'}```
