### ISSUE TITLE
Can't connect to full node[Bug] 

### ISSUE THREAD

**Issue by DareGames004** [Chia-Network/chia-blockchain#9747]
### What happened?

[
![image](https://user-images.githubusercontent.com/97298020/148559112-959ca86e-1be8-4e3b-b12a-a6f0a5c0a534.png)
](url)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by Zyzonix** [comment]
Hello,
have you checked the following?
- Firewall ports open (Windows might be blocking Chia, try following this guide: [https://thechiafarmer.com/2021/04/20/syncing-problems-on-windows/](https://thechiafarmer.com/2021/04/20/syncing-problems-on-windows/))
- No corrupted .db-file (Therefore check the .chia-folder in your home directory)
- Have you tried a reinstall? (With .chia-folder deleted?)

Best regards
Zyzonix
