### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by staviq** [Chia-Network/chia-blockchain#975]
Fresh install 0.2.2, Windows 10

Gui main page says "Status Not Synced", "Peak Height 256", "Connection Status Connected"

And nothing is happening for several hour now.

**Comment by dorkmo** [comment]
im currently at peak 600 synced. maybe try restart?

**Comment by staviq** [comment]
I can see connections with height of 603, but synchronisation is stuck.

Where are logs stored on windows builds ? I can't find any.

**Comment by dorkmo** [comment]
local disk > Users > (your login) >0.2.2 > log

**Comment by staviq** [comment]
[debug.zip](https://github.com/Chia-Network/chia-blockchain/files/6013124/debug.zip)

**Comment by mariano54** [comment]
Height 603 was correct, you were synced
