### ISSUE TITLE
No sincroniza el Nodo completo, pero si la billetera

### ISSUE THREAD

**Issue by elchivo73** [Chia-Network/chia-blockchain#9759]
### What happened?

El nodo completo dice sincronizando en color amarillo,   Sincronizando 0/1.385.751  y la Billetera dice, Wallet Status Sincronizado (1.393.515). 
Alguien puede indicarme si debo hacer algo para que el nodo completo vuelva a sincronizar, o solo debo seguir esperando.
En la parte de conexiones observo que se conecta y se desconecta continuamente de los otros pares y normalmente solo lo hace a un par.
Saludos y gracias por la ayuda que puedan darme.

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by mariano54** [comment]
Me podes enviar el archivo debug.log que esta ubicado en `~/.chia/log/debug.log` por keybase? Soy sorgente711 en keybase.

**Comment by elchivo73** [comment]
Hola Mariano, cómo estas, te envío el archivo y muchas gracias por tu ayuda.

[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7835667/debug.log)

**Comment by elchivo73** [comment]
Hola hay alguien que pueda darme una mano con mi problema. Gracias

**Comment by elchivo73** [comment]
Hola, ya pude solucionarlo.

1  Detenga el cliente de chía y renombre sus archivos "blockchain_v1_mainnet.sqlite" y "peer_table_node.sqlite", colocándoles al final .BAT,  luego reinicie la PC e inicie el cliente de chia nuevamente y comience a sincronizar desde 0 (puede llevarle días hasta que termine de actualizar, 

La solución la tome desde el post de https://chiaforum.com/u/mariod

https://chiaforum.com/t/not-sync-anymore-from-day-to-day/14838/32

Soy inexperto en el tema y hacia mucho tiempo que estaba con el problema de sincronización, que comenzó luego de un corte de energía y realizando los consejos de MarioD pude lograr que comience a sincronizar.

Quizás hay alguna otra forma para no comenzar desde cero pero no la encontré en todo el foro, y esto es mejor que nada jajajaj.

Abrazo y gracias a todos lo que intentaron ayudarme.
Saludos
