### ISSUE TITLE
[Bug] HarvesterAPI.new_signage_point_harvester RuntimeWarning

### ISSUE THREAD

**Issue by topg-org** [Chia-Network/chia-blockchain#9814]
### What happened?

I'm getting this error from time to time on harvesters only:

/home/user/chia-blockchain/chia/harvester/harvester.py:101: RuntimeWarning: coroutine 'HarvesterAPI.new_signage_point_harvester.<locals>.lookup_challenge' was never awaited
  {
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

### Relevant log output

```shell
/home/user/chia-blockchain/chia/harvester/harvester.py:101: RuntimeWarning: coroutine 'HarvesterAPI.new_signage_point_harvester.<locals>.lookup_challenge' was never awaited
  {
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by alross90** [comment]
same problem at windows, no difference gui or cli. 1.2.11. Need to restart harvester to fix it each time when it hapens.

**Comment by emlowe** [comment]
Can you please provide a few more lines of log output? We need some lines from before and after the error. Thanks

**Comment by PAVoutsinas** [comment]
threading.py:250: RuntimeWarning: coroutine 'HarvesterAPI.new_signage_point_harvester.<locals>.lookup_challenge' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by PAVoutsinas** [comment]
I think I may have found the issue with this problem.  Power and sleep settings. set hard drive to never sleep. Also Sleep function and hybrid sleep need to be disabled in the advance power settings. These settings can be a little hard to find in windows 11, they are there and can be found by searching in the taskbar for "Power and Sleep".

Let me know if my solution was a hit or miss.
