### ISSUE TITLE
[BUG] macOS - Chia Helper Crash

### ISSUE THREAD

**Issue by benwgarton** [Chia-Network/chia-blockchain#982]
**Describe the bug**
Macbook operating as Farmer / Harvester crashes sporadically. 

**Desktop (please complete the following information):**

- OS: macOS
- OS Version/Flavor: 11.2.1
- CPU: 2.3 GHz Quad-Core Intel Core i7

**Additional context**
Panic(CPU 2, time 131717801584690): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff86c3dcce80, spinlock owner: 0xffffff86b5e92ad0, current_thread: 0xffffff86b5e92ad0, spinlock_owner_cpu: 0x2
RAX: 0xffffff86c49a7360, RBX: 0xffffff9361baf5f8, RCX: 0x0000000000000148, RDX: 0x000112e700000000
RSP: 0xffffffa046453aa0, RBP: 0xffffffa046453ae0, RSI: 0xffffff86b5e92ad0, RDI: 0xffffff9361baf5f8
R8:  0xffffffa046453c60, R9:  0xffffff800770f110, R10: 0x0000000000ffffff, R11: 0x0000000000000000
R12: 0xffffff86b5e92ad0, R13: 0x0000000000000000, R14: 0x000112e7c7c03da3, R15: 0xffffff86c49a7360
RFL: 0x0000000000000017, RIP: 0xffffff80076ccb67, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 2), Frame : Return Address
0xffffffa0666abf80 : 0xffffff80077ed5bb 
0xffffffa0666abfd0 : 0xffffff800765fbdd 
0xffffffa046453ae0 : 0xffffff80076ccd04 
0xffffffa046453b10 : 0xffffff800770d930 
0xffffffa046453b30 : 0xffffff800770f149 
0xffffffa046453be0 : 0xffffff800770f646 
0xffffffa046453c50 : 0xffffff800770e694 
0xffffffa046453d10 : 0xffffff80077125e8 
0xffffffa046453d50 : 0xffffff8007c23364 
0xffffffa046453d70 : 0xffffff8007c2344e 
0xffffffa046453db0 : 0xffffff8007c7bfdd 
0xffffffa046453e30 : 0xffffff8007c774e5 
0xffffffa046453ee0 : 0xffffff8007c77311 
0xffffffa046453f40 : 0xffffff8007d698cb 
0xffffffa046453fa0 : 0xffffff80076601f6 

Process name corresponding to current thread: Chia Helper (Renderer)

Mac OS version:
20D74

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000007400000
KernelCache base:  0xffffff8007600000
Kernel slide:      0x0000000007410000
Kernel text base:  0xffffff8007610000
__HIB  text base: 0xffffff8007500000
System model name: MacBookPro11,3 (Mac-2BD1B31983FE1663)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 131717801628878
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000077cbf0c6d8b4
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000226bbbe14 0x0000000000000000
last started kext at 128320090648974: >usb.!UUserHCI	1 (addr 0xffffff7fa7f9e000, size 102400)
last stopped kext at 128397437003503: >usb.!UUserHCI	1 (addr 0xffffff7fa7f9e000, size 102400)
loaded kexts:
com.kairos.driver.DuetDisplay	1
@filesystems.ntfs	3.14.3
>AudioAUUC	1.70
>AGPM	119
>X86PlatformShim	1.0.0
>!APlatformEnabler	2.7.0d0
@filesystems.autofs	3.0
@fileutil	20.036.15
@fsplaceholder	1.14.0
>!AGraphicsDevicePolicy	6.2.2
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
|IO!BSerialManager	8.0.3d9
>!AUpstreamUserClient	3.6.8
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
@GeForce	16.0.0
>AGDCBacklightControl	6.2.2
>!ADiskImages2	1
>!A!IHD5000Graphics	16.0.1
>!AHDA	283.15
>!A!IFramebufferAzul	16.0.1
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.14
>!AMuxControl	6.2.2
>!ASMCLMU	212
>!AThunderboltIP	4.0.3
>eficheck	1
>!ACameraInterface	7.6.0
>!ALPC	3.1
>!UCardReader	511.60.2
>!UTCButtons	256
>!UTCKeyboard	256
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@filesystems.apfs	1677.81.1
>!AAHCIPort	346
@private.KextAudit	1.0
>AirPort.BrcmNIC	1400.1.1
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@kext.triggers	1.0
|IOSerial!F	11
|IOAVB!F	930.1
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
@nvidia.driver.NVDAGK100Hal	16.0.0
@nvidia.driver.NVDAResman	16.0.0
>!ABacklightExpert	1.1.0
|IONDRVSupport	585
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IOAccelerator!F2	439.52
@!AGPUWrangler	6.2.2
|IOSlowAdaptiveClocking!F	1.0.0
>!ASMBus!C	1.0.18d1
>!AGraphicsControl	6.2.2
@!AGraphicsDeviceControl	6.2.2
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOGraphics!F	585
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|Broadcom!BHost!CUSBTransport	8.0.3d9
|IO!BHost!CUSBTransport	8.0.3d9
|IO!BHost!CTransport	8.0.3d9
>usb.!UHub	1.2
>!UMultitouch	264
>usb.IOUSBHostHIDDevice	1.2
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AThunderboltPCIDownAdapter	4.1.1
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
|IOAHCIBlock!S	332
|IOAHCI!F	294
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
|IOUSB!F	900.4.2
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.3d9
|IOReport!F	47
|IO!BPacketLogger	8.0.3d9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1
panic(cpu 6 caller 0xffffff80077e2960): "Spinlock acquisition timed out: lock=0xffffff86c3dcce80, lock owner thread=0xffffff86b5e92ad0, current_thread: 0xffffff86c49a7360, lock owner active on CPU 0x2, current owner: 0xffffff86b5e92ad0, time: 131717801656671"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.81.3/osfmk/i386/locks_i386.c:505
Backtrace (CPU 6), Frame : Return Address
0xffffffa066ac4af0 : 0xffffff80076bab4d 
0xffffffa066ac4b40 : 0xffffff80077fd7e3 
0xffffffa066ac4b80 : 0xffffff80077ede1a 
0xffffffa066ac4bd0 : 0xffffff800765fa2f 
0xffffffa066ac4bf0 : 0xffffff80076ba3ed 
0xffffffa066ac4d10 : 0xffffff80076ba6d8 
0xffffffa066ac4d80 : 0xffffff8007ebef9a 
0xffffffa066ac4df0 : 0xffffff80077e2960 
0xffffffa066ac4e30 : 0xffffff80076daff6 
0xffffffa066ac4e60 : 0xffffff8007708d7b 
0xffffffa066ac4f20 : 0xffffff80077d98b3 
0xffffffa066ac4f60 : 0xffffff80077f6eaa 
0xffffffa066ac4f80 : 0xffffff80077ed5bb 
0xffffffa066ac4fd0 : 0xffffff800765fbdd 
0xffffffa067b93db0 : 0xffffff80077123d1 
0xffffffa067b93e10 : 0xffffff8007c795e9 
0xffffffa067b93f00 : 0xffffff8007c78716 
0xffffffa067b93f40 : 0xffffff8007d698cb 
0xffffffa067b93fa0 : 0xffffff80076601f6 

Process name corresponding to current thread: Chia Helper (Renderer)

**Comment by hoffmang9** [comment]
Please try RC7 https://github.com/Chia-Network/chia-blockchain/releases/tag/1.0rc7
