### ISSUE TITLE
Stop syncing at 1 439 069 [Bug] 

### ISSUE THREAD

**Issue by Szczepann** [Chia-Network/chia-blockchain#9849]
### What happened?

![obraz](https://user-images.githubusercontent.com/84151307/149956461-53dab910-e2d2-44c0-afe5-af4587f0a1ee.png)

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by emlowe** [comment]
Without some log output provided, we won't be able to diagnose this issue.
Please provide logs. Also, this may be related to #9837 or #9677

**Comment by Szczepann** [comment]
I've  made this steps:

_Since it's likely your DB is somehow inconsistent, I recommend resyncing the node db.
stop chia processes
move ~/.chia/mainnet/db/blockchain_v1_mainnet.sqlite out of the way
restart chia_

Now it start syncying from the beggining.

![obraz](https://user-images.githubusercontent.com/84151307/150083192-c4e5a354-1379-4005-8971-951062b7dc43.png)

**Comment by Szczepann** [comment]
After two day of syncing from the beggining it stops again...
![obraz](https://user-images.githubusercontent.com/84151307/150485055-5030f092-4d9c-495f-9c18-b832104b2223.png)

WHAT SHOULD I DO NOW ???

**Comment by Szczepann** [comment]
After Forse reload it starts again and sync full node and wallet. 
Everything is now ok.
