### ISSUE TITLE
[Bug] getting error when sending transaction

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#9873]
### What happened?

I'm trying to make change for my USDS. in the create transaction screen, I enter the address / puzzle hash, the amount, and 0 for the fees. when I click on send, I get an error that says "Error: an integer amount or fee is required (too many decimals).
![Screen Shot 2022-01-19 at 8 53 17 AM](https://user-images.githubusercontent.com/93196638/150159096-d98a1874-12fd-4161-804a-7b6e30817f06.png)

"

### Version

1.12.12.dev143

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7906946/debug.log)

**Comment by paulhainsworth-chia** [comment]
Chia Blockchain main is currently pinned to your next branch, @seeden . Please also note the Farm button needs to go.

**Comment by esaung** [comment]
in the 1.2.12 dev 197 build on mac m1, I can send XCH transactions, but I can't create and send a transaction with any of my CAT wallets.

**Comment by paninaro** [comment]
@seeden has fixed this with commit 2713b725f819326265a49f0ed153e617e8a43e9e
