### ISSUE TITLE
[Bug] Accepting my own offers(CAT to XCH) has caused to lose 15.36 XCHs from my ChiaWallet!

### ISSUE THREAD

**Issue by Yongling01** [Chia-Network/chia-blockchain#9875]
### What happened?

Recently, I encountered a big trouble when using OfferBin to exchange. I'm eager to get your professional guidance. Thank you very much in advance!
The approximate process of this event is as follows:
(1) First, I created three offer (CAT to XCH) in ChiaWallet/ManageOffer several days ago and successfully shared it on OfferBin

(2) Yesterday (January 18), I mistakenly clicked "Accept Offer" when viewing above three offers in ChiaWallet/ManageOffer. After that, I soon found that my 15 XCHs in ChiaWallet disappeared.

(3) Then, I canceled the previously created three offer (CAT to XCH) in ChiaWallet/ManageOffer, however the 15 disappeared XCHs have not been returned back till now. 

I want to know what actions should I take so that the 15 XCHs can be returned to the original ChinWallet as soon as possible?
Appreciate your guidance and support.

![image](https://user-images.githubusercontent.com/98039180/150366138-6b785f58-5f0a-4119-83ad-e137841b415b.png)
![image](https://user-images.githubusercontent.com/98039180/150763274-c9b42aee-6291-4e15-beef-eb9545cb534c.png)
![image](https://user-images.githubusercontent.com/98039180/150163612-a31a3490-2108-47a3-a42e-6b9c481d71fb.png)
![image](https://user-images.githubusercontent.com/98039180/150163698-fb435f16-0930-4df9-bab4-beb7d941a185.png)
![image](https://user-images.githubusercontent.com/98039180/150163853-5cf0f35e-37ce-4201-a35b-50a851a5423a.png)

_I had more than 15.4XCH before I clicked "AcceptOffer (CAT to XCH)" by mistake, and now there is only 0.2 left in ChiaWallet._
![image](https://user-images.githubusercontent.com/98039180/150448547-8fbe55bc-918c-4731-8cef-15196288985c.png)

### Version

Chia Wallet Beta 1.2.11265 (Standalone wallet for Chia Blockchain)

### What platform are you using?

Windows

### What ui mode are you using?

GUI

### Relevant log output

_No response
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7924595/debug.log)
_

**Comment by paulhainsworth-chia** [comment]
@RWilsonChia can you please contact this user?

**Comment by jcheng0509-Chia** [comment]
能把你的Transaction History截个图发一下吗， 就你这几天的截图就可以

**Comment by Yongling01** [comment]
@jcheng0509-Chia @RWilsonChia @paulhainsworth-chia 
Please see the screenshot of transaction history and advise how to find the XCHs back, thank you.

![InkedWeChat Image_20220121091359_LI](https://user-images.githubusercontent.com/98039180/150448304-cc6937c6-2a51-4574-8f72-09fe27586962.jpg)

**Comment by jcheng0509-Chia** [comment]
Did you accept your own offer?

**Comment by Yongling01** [comment]
Yes,  Since this is the first time I use the ManegeOffer function on this light ChiaWallet, mistakenly clicked "Accept Offer" on 2 of them when viewing my own 3 offers(CAT to XCH).  All of these operation were performed on the same PC and same ChiaWallet.

_I have summarized the course of events in the form of process chart, for your information._ 
![WeChat Image_20220121101308](https://user-images.githubusercontent.com/98039180/150453532-376ceb43-26af-4b62-95b6-4a95cd34c908.png)

**Comment by Yongling01** [comment]
> 顺便还问一下， 你用的是同一台电脑的同一个钱包app进行的操作么 还是用其他的电脑接的这个offer 有可能会是Wallet DB出错 显示Balance出错。 或者你可以换一个其他的电脑或者VM重新登陆一次轻钱包看看余额

—— 我在其它2两台电脑登录挖矿钱包也是显示错误的Balance。另外，我昨天把轻钱包上的文件Backup后，重新的同步的结果，仍然是错误的balance。
非常疑惑，accepte my own offer就像左、右手互相传递物品一样，当右手停下来时，左手的物品怎么会凭空消失呢？不应该在严密、科学的BlockChain发生啊。

**Comment by Yongling01** [comment]
@jcheng0509-Chia @RWilsonChia @paulhainsworth-chia @pyl
It always takes a long time to synchronize these abnormal transactions every time, and some warnings will be recorded in the debug.log(please see the attacment).

![image](https://user-images.githubusercontent.com/98039180/150762269-bcb32da8-da57-4aa7-83c2-425a168ffb6b.png)
[debug.log](https://github.com/Chia-Network/chia-blockchain/files/7924563/debug.log)

**Comment by wjblanke** [comment]
<img width="917" alt="Screen Shot 2022-01-24 at 8 19 36 PM" src="https://user-images.githubusercontent.com/1206691/150911656-22ab206d-a907-459e-bd43-591f9e36a4a4.png">

chiaexplorer can see it, so likely a bug in lite wallet. the funds should be ok once we fix it

**Comment by Yongling01** [comment]
@wjblanke
Thank you very much for your efforts to improve. 
Let's try best to make it more and more perfect together!

**Comment by Yongling01** [comment]
@wjblanke
Thank you very much for your efforts to improve. 
Let's try best to make it more and more perfect together!

**Comment by Yongling01** [comment]
@wjblanke 
do you have the schedule to release the new version including this fix?

**Comment by ytx1991** [comment]
For all this kinds of transaction display errors you can try to delete the key and database file then resync SEVERAL times. Make sure you saved the seed words.

**Comment by Yongling01** [comment]
Actually I've tried many times to reinstall the light wallet and resynchronize on different computers, but it hasn't always worked all the time.

**Comment by HVNC1** [comment]
I have a similar situation. I lost 20 chia. How do I get them back? I used 2 wallets with the same key and instead of 40 chia shows 20. on two wallets different amounts

**Comment by Yongling01** [comment]
> 

@wjblanke  do you have the schedule to release the new version including this fix? Does the coming 1.3version have this fix?

**Comment by Yongling01** [comment]
[debug(1st-backup).log](https://github.com/Chia-Network/chia-blockchain/files/8009982/debug.1st-backup.log)
@wjblanke  
After resynchronizing with the latest beta version(v1.2.12254) of light wallet, the lost 15.36 XCHs have not been recovered. Meanwhile, there are many "WARNING  Failed to apply state transition" info in the debug.log. Please refer to the attachment.

![image](https://user-images.githubusercontent.com/98039180/152677419-b1567ce9-b633-46f6-b4b6-158f61d1d14e.png)

**Comment by Yongling01** [comment]
@wjblanke latest version still does not work for retrieve the missing 15.36xchs, please help check the attached debug.log.
![image](https://user-images.githubusercontent.com/98039180/153682887-5f3da6d5-d5e8-433c-b397-8da8ffda7920.png)

[debug(v1.2.12270).log](https://github.com/Chia-Network/chia-blockchain/files/8052162/debug.v1.2.12270.log)

**Comment by Yongling01** [comment]
@wjblanke debug log from latest v1.2.12277 beta version
[debug(v1.2.12277).log](https://github.com/Chia-Network/chia-blockchain/files/8056224/debug.v1.2.12277.log)

**Comment by Yongling01** [comment]
Latest version(v1.2.12356) still does not work for retrieving the missing 15.36xchs, please help check the attached debug(INFO level).log.
![image](https://user-images.githubusercontent.com/98039180/155379017-1d92a8fe-9f38-4b59-ad16-3774a7194dec.png)


[debug_INFO(v1.2.12356).log](https://github.com/Chia-Network/chia-blockchain/files/8126666/debug_INFO.v1.2.12356.log)

**Comment by mariano54** [comment]
We have looked into this, I think coins were transferred out of the wallet or stolen around the same time the trades were created.

**Comment by grandee89** [comment]
Can we please reopen this issue. I have the same problem with the Light Wallet (Version 1.2.12269). I created an offer and now after 4 days I cancelled this. the amount was transfered now to a wallet I do not know. the Offer is just cancelled. How do I get the XCH back.
![image](https://user-images.githubusercontent.com/80603545/157034366-7492629d-2280-4d9e-ab6e-59b7303a215d.png)
![image](https://user-images.githubusercontent.com/80603545/157034476-3f77c8b4-71ee-4725-ab84-7b4241ae0849.png)
![image](https://user-images.githubusercontent.com/80603545/157034612-67e7b37f-0a95-4127-af90-1b8670419bd1.png)

**Comment by Yongling01** [comment]
Actually I disagree with the above conclusion above conclusion at all, and deeply puzzled by the strange investigation process. 
Those missing 15.36xch slept on the address contained in my offers for more than a month. However, it was mysteriously transferred within 1 ~ 2 hours after I provided walletdb to Chia dev team as required. Afterwards, the abnormal prompt (wallet pool_wallet: warning failed to apply state transition) that had always been previously appearing in the debug log no longer appeared when re-syncing the wallet. Obviously, those 15.36xch that didn't logically arrived in my wallet for some reason were handled artificially and strangely, and went to a new address belonging to the the devil!

![image](https://user-images.githubusercontent.com/98039180/157044457-65a6db47-63b6-4142-adc3-271959c9a4cc.png)
![image](https://user-images.githubusercontent.com/98039180/157045919-42040a81-05ee-4dcd-b023-6890f5466e35.png)

[debug(v1.2.12389 without wallet-warning).log](https://github.com/Chia-Network/chia-blockchain/files/8198114/debug.v1.2.12389.without.wallet-warning.log)

**Comment by paulhainsworth-chia** [comment]
Did you receive the 1 space marmot premium coin that was in this offer?

**Comment by grandee89** [comment]
No, I cancelled the Offer. Now I get the amount back after approx 1 our.
