### ISSUE TITLE
[ENHANCEMENT] Reduce directory search frequency or make configurable

### ISSUE THREAD

**Issue by imbeingfollowed** [Chia-Network/chia-blockchain#988]
Harvester_api.py is currently configured to scan for new plots every 2 minutes.

This seems a bit excessive and not great for longevity of drives. It will never need to be done at all if you are finished plotting/mounting drives.

I propose this is changed to 30 minutes or even better to be made configurable and/or disabled with a re-scan parameter.

Thanks

**Comment by mariano54** [comment]
It does not scan the data, all it does is check the directory to see if any new files have been added. If a new one is added, it reads it.

**Comment by imbeingfollowed** [comment]
Yes - it is the directory scanning that I am flagging. Cheers

**Comment by mariano54** [comment]
Does that actually affect longevity? It is only checking the filesystem files and doing a stat OS call.

**Comment by imbeingfollowed** [comment]
That would depend on how smart your disk/OS cache is. I just noticed lots of log entry noise and it seems like an easy routine to cut down on.

**Comment by hoffmang9** [comment]
But then the Keybase channel will be full of "why didn't my plots show up" directly in proportion to the amount of time we raise it by.

**Comment by imbeingfollowed** [comment]
Why don't we meet in the middle then? A 20 minute schedule would mean an average of 10 minutes to locate a new plot and would cut down on 648 scans per day.

**Comment by mariano54** [comment]
It's way too long for the average users, we will have to be full time customer support

**Comment by hoffmang9** [comment]
We could drop it into config.yaml and ship it at the current setting.

**Comment by imbeingfollowed** [comment]
Cheers gents. For me, buying a disk or two is a big investment so I'm trying to make sure it lasts. Indeed it might hit the cache every time depending what other things are running but upping the value for me can only either achieve nothing or mean less wear.  I am happy to continue sed'ing the file so I leave it with you to decide whether to implement.

**Comment by mariano54** [comment]
If any expert knows whether checking for files and stating them has the possibility of adding wear to the disk, please let us know
