### ISSUE TITLE
[Bug] crashes end task restart chia typenone nonsubsriptable finger print 

### ISSUE THREAD

**Issue by caseyxsharp** [Chia-Network/chia-blockchain#9889]
### What happened?

It crashed repeatedly so I had to close it and it kept adding a plot after closing so I had to use task manager to end task to open it again, and then after restoring wallet being asked to upload or skip if I click skip it says typenone and nonsubscriptable, by clicking skip again it just says fingerprint.

### Version

1.2.11.

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by paulhainsworth-chia** [comment]
Please reboot and see if it's reproducible. Can you also please provide screen shots for this? Thanks!

**Comment by esaung** [comment]
I saw this issue in 1.2.12 dev builds also.
