### ISSUE TITLE
Missing transaction

### ISSUE THREAD

**Issue by Arch77778** [Chia-Network/chia-blockchain#9910]
I accidentally sent from a wallet to the same address only GUI, and disappeared transaction, it is in the outgoing, but in the incoming it is not. It didn't appear in the outgoing by time, but appeared in the middle of earlier transactions. How do I get CHIA back?

**Comment by Yongling01** [comment]
this operation is a little similar to that I accepted the offers created by myself, resulting in the loss of 15.36xch... (https://github.com/Chia-Network/chia-blockchain/issues/9875).  @jcheng0509-Chia @RWilsonChia @paulhainsworth-chia

**Comment by esaung** [comment]
can you take a look at chia explorer to see if you can see the coins there?

**Comment by Arch77778** [comment]
They are in the outgoing transactions, but for some reason they are displayed there at an earlier time, and in the incoming they are not.Note the transaction in 0.13, it was not in time.  28.01.2022, 00:18, "esaung" ***@***.***>: can you take a look at chia explorer to see if you can see the coins there?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.You are receiving this because you authored the thread.Message ID: ***@***.***>
