### ISSUE TITLE
[BUG]  Send transactions are limited to 173.25 TXCH

### ISSUE THREAD

**Issue by kiwihaitch** [Chia-Network/chia-blockchain#993]
Attempting to send more than 173.25 TXCH fails.

(venv) haitch@chia-master:/.chia$ chia wallet send -a 500 -m 0.001 -t txch13tutyg6gtkaycx5hqxrwya5t36x8klmvzzlfy4ukgk66eqalw7fss0tt4m
Submitting transaction...
Exception from 'wallet' {'error': "Can't send more than 173250000000000 in a single transaction", 'success': False}

(venv) haitch@chia-master:/.chia$ chia wallet send -a 174 -m 0.001 -t txch13tutyg6gtkaycx5hqxrwya5t36x8klmvzzlfy4ukgk66eqalw7fss0tt4m
Submitting transaction...
Exception from 'wallet' {'error': "Can't send more than 173250000000000 in a single transaction", 'success': False}

(venv) haitch@chia-master:/.chia$ chia wallet send -a 173 -m 0.001 -t txch13tutyg6gtkaycx5hqxrwya5t36x8klmvzzlfy4ukgk66eqalw7fss0tt4m
Submitting transaction...
Transaction submitted to nodes: [('d12b2f3735b3f54da175862f77e6e3d3f74dbad9efcdc865df3d91d86ec6a282', 1, 'None')]
Do chia wallet get_transaction -f 2274570366 -tx 0xb4174a20cc4b71035aa3b1566700abd77b314fb44085be5ea57a351ae60cf9b7 to get status
(venv) haitch@chia-master:/.chia$

(venv) haitch@chia-master:/.chia$ chia version
1.0rc3.dev12
(venv) haitch@chia-master:/.chia$

**Comment by mariano54** [comment]
It happens due to the block size, since you are combining many coins into one. You are hitting the block size limits. Try sending 170 to yourself, then your limit should increase. 

Two things will help:
1. More efficient transactions in block (in progress)
2. Better messaging to explain why there is a max transaction amount

**Comment by hoffmang9** [comment]
Closing for RC7

**Comment by sibitha-bijesh** [comment]
@kiwihaitch , how do you figure out this issue.  I got same issue and my wallet is fully synced.
