### ISSUE TITLE
Lite Wallet only shows 49 offers[Bug] 

### ISSUE THREAD

**Issue by DrKiz** [Chia-Network/chia-blockchain#9954]
### What happened?

Lite wallet stops showing offers after 49.  New offers after that point work, but they do not always show up on the list.

Makes it hard to cancel an offer if it doesn't show up, amiright?

An option to delete confirmed or cancelled transactions is required as well as increasing offers past 49 to 100 or unlimited?

### Version

chia wallet beta 1.2.11265

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by DrKiz** [comment]
Just as a suggestion.  New lite wallet releases should have these features:

1. Show all offers.  Even if its a 1000 pages.
2. Ability to delete or hide old deleted/fullfilled offers as they clutter up the display.
3. Ability to end ALL offers at once as an option.
4. Abitlity to print out or have a file tracking the offers made and fullfilled.

**Comment by paninaro** [comment]
Thanks for the feedback @DrKiz. The GUI (and CLI) have been fixed such that you can show all of the offers with pagination, or all in one go (though I'm not sure I'd recommend that with 1000 offers...)

@sethjenks will be handling the design side of UX improvements. I agree that the GUI should include filtering options. We've also had some discussions about exporting the list of offers.
