### ISSUE TITLE
[Bug] Incomplete number of remote harvesters

### ISSUE THREAD

**Issue by WetAngel** [Chia-Network/chia-blockchain#9959]
### What happened?

When I do `chia farm summary`, I get outdated results with a lot less harvesters. But the missing harvesters are working properly and can find the blocks. This is just a display error.

Expected:
Displays the correct list of harvester IPs and plot number and size.

### Version

1.2.11

### What platform are you using?

Linux

### What ui mode are you using?

CLI

**Comment by esaung** [comment]
Kevin, Please take a look at this issue.

**Comment by xdustinface** [comment]
@WetAngel If your harvesters handle large amounts of plots you can try #9695 which fixes a known issue for large farms (the symptoms you describe sound more or less related).

If that doesn't help or if you have no idea how to try it, please provide some logs from the farmer and one harvester which doesn't appear in the summary. You can share them either here or send them on keybase, im http://keybase.io/dustinface.

**Comment by WetAngel** [comment]
@xdustinface As you mentioned, this is a large farm. All harvesters have been connected to the GUI in 1.2.11 for a while. Clicking on "Farm" and "Plot" in the GUI and even spinning in circles forever, did not show any information about the harvester. Later I moved to CLI.

After reading the changes in #9695, I think this is highly likely to help in this case. But this requires an upgrade of the farmer and all its harversters. This is too much work for me. I will wait for the next Chia update.

I have tried the following.
First, I did `chia farm summary` in the farmer and found that the number of harvesters is 30 less.
(The level of both harvester and farmer is INFO)
I tried `chia start harvester -r` in a harvester that doesn't appear. The farmer shows the following logs:

> 2022-01-28T04:01:57.026 farmer chia.farmer.farmer : INFO peer disconnected {'host': '192.168.0.190', 'port': 8448}
> 2022-01-28T04:01:57.033 farmer chia.farmer.farmer : ERROR Harvester '192.168.0.190/9227968bb809***' did not respond: (version mismatch or time out 90)

Harvester log:

> 2022-01-28T04:01:54.655 daemon chia.daemon.server         : INFO     sending term signal to chia_harvester
> 2022-01-28T04:01:54.656 harvester harvester               : INFO     got signal 15
> 2022-01-28T04:01:54.656 harvester harvester               : INFO     Cancelling reconnect task
> 2022-01-28T04:01:54.656 harvester harvester               : INFO     Closing connections
> 2022-01-28T04:01:54.846 harvester harvester               : INFO     Calling service stop callback
> 2022-01-28T04:01:54.846 harvester harvester               : INFO     Closing RPC server
> 2022-01-28T04:01:55.779 harvester harvester               : INFO     Waiting for socket to be closed (if opened)
> 2022-01-28T04:01:55.779 harvester harvester               : INFO     Waiting for ChiaServer to be closed
> 2022-01-28T04:01:57.030 harvester harvester_server        : INFO     Connection closed: 192.168.\*.\*, node id: \*\*\*
> 2022-01-28T04:01:57.030 harvester chia.harvester.harvester: INFO     peer disconnected {'host': '192.168.\*.\*', 'port': 8447}
> 2022-01-28T04:01:57.030 harvester harvester               : INFO     Waiting for RPC server
> 2022-01-28T04:01:57.781 harvester harvester               : INFO     Closed RPC server
> 2022-01-28T04:01:57.781 harvester harvester               : INFO     Waiting for service _await_closed callback
> 2022-01-28T04:01:57.781 harvester harvester               : INFO     Service harvester at port 8448 fully closed
> 2022-01-28T04:01:58.160 daemon chia.daemon.server         : INFO     process chia_harvester returned 0
> 2022-01-28T04:01:58.804 harvester harvester               : INFO     Started harvester service on network_id: mainnet
> 2022-01-28T04:01:58.805 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.\*.\*', 'port': 8447}
> 2022-01-28T04:01:58.813 daemon chia.daemon.server         : INFO     Register service {'service': 'chia_harvester'}
> 2022-01-28T04:01:58.814 daemon chia.daemon.server         : INFO     registered for service chia_harvester
> 2022-01-28T04:01:58.814 daemon chia.daemon.server         : INFO     {'success': True}
> 2022-01-28T04:02:00.502 harvester harvester_server        : INFO     Connected with farmer {'host': '192.168.\*.\*', 'port': 8447}
> 2022-01-28T04:02:00.514 harvester chia.plotting.manager   : INFO     Loaded 41606 bytes of cached data
> 2022-01-28T04:02:00.759 harvester chia.harvester.harvester: INFO     refresh_batch: event started, loaded 0, removed 0, processed 0, remaining 320, duration: 0.00 seconds
> 2022-01-28T04:02:00.769 harvester chia.plotting.manager   : INFO     Found plot /mnt/3/plot-k32-2022-01-21-18-43-\*\*\*.plot of size 32
> 2022-01-28T04:02:00.770 harvester chia.plotting.manager   : INFO     Found plot /mnt/3/plot-k32-2022-01-21-10-02-\*\*\*.plot of size 32

Then I did `chia farm summary` in farmer and found that almost all the harvesters are displayed, but one less. I also did `chia start harvester -r` on the harvester many times, the logs for the farmer and harvester are the same as above.

After a few minutes, did `chia farm summary` in the farmer, and find that all the harvesters are displayed correctly.

**Comment by xdustinface** [comment]
> @xdustinface As you mentioned, this is a large farm. All harvesters have been connected to the GUI in 1.2.11 for a while. Clicking on "Farm" and "Plot" in the GUI and even spinning in circles forever, did not show any information about the harvester. Later I moved to CLI.

Yeah running it with GUI makes it worse in this case. There will be another PR to fix the GUI part and make the GUI more responsive for large farms.

> After reading the changes in #9695, I think this is highly likely to help in this case. But this requires an upgrade of the farmer and all its harversters. This is too much work for me. I will wait for the next Chia update.

Sounds good. You will have to wait for the next next release though as we won't include #9695 into 1.3 though :)
