### ISSUE TITLE
[ENHANCEMENT] `chia wallet` should have a way to get next receive address

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chia-blockchain#996]
Right now the only easy way to get a wallet receive address is in the GUI or to grab the first wallet address in `chia keys show`.

We should probably both:

- Display a current valid receive address in `chia wallet show`
- Have a way to increment the receive address in `chia wallet show` and/or `chia keys show` via the command line

**Comment by LeonidShamis** [comment]
It could be something like https://bitcoincore.org/en/doc/0.18.0/rpc/wallet/getnewaddress/ - e.g. `bitcoin-cli getnewaddress "label" "address_type"`

Maybe in addition to `chia wallet show` displaying the current valid receive address, something like `chia wallet getnewaddress` would return a new address and set it as the current address.

**Comment by jespino** [comment]
The #1021 PR (already merged) covers at least part of this issue.

**Comment by jespino** [comment]
@hoffmang9 if you give me some explanation of next steps, I can try to make the extra changes needed to close this issue.

**Comment by hoffmang9** [comment]
There only thing left is to see current address because new_address leads to the question of "well, what is the old one."

We should just add a line to `chia wallet show` which shows current wallet receive address - though I'm unclear where we keeping the state of the increment into the derivation path?

**Comment by mariano54** [comment]
There is no rpc for this, we would have to add an rpc that just gets the last address used instead of generating a new one.

This was done on purpose to avoid reusing addresses. But I'm not opposed to adding it

**Comment by hoffmang9** [comment]
Maybe there is a better label for this. get_address that is always unique could work. Most of the words I can think of drive questions.

How about `get_address     get a wallet receive address` and drop new and follow the other get_'s?

**Comment by mariano54** [comment]
Sure that works. So just renaming new_address to get_address?

**Comment by hoffmang9** [comment]
I think that works and is the easiest path.

**Comment by jespino** [comment]
@hoffmang9 @mariano54 great, thanks, I'll create a quick PR for that.

**Comment by jespino** [comment]
Done here #1084

**Comment by hoffmang9** [comment]
And merged
