### ISSUE TITLE
New Plots wil not recognized until restart[Bug] 

### ISSUE THREAD

**Issue by crazybanane** [Chia-Network/chia-blockchain#9965]
### What happened?

I got some new HDDs and i started again to Plot new Plots but GUI didnt recognize it until i restart the GUI with a Waiting time up to 5 min. Normaly it was so that when the Plot is Ready it was Shown Up in the GUI.
Try to reinstall- Go back to 1.2.10 same problem

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by esaung** [comment]
we will consider improving in this in a future update.
