### ISSUE TITLE
[Bug] - white screen show up when typing a decimal first in the amount section of create transaction

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain#9995]
### What happened?

when you type a decimal first in the amount section and fee section with the XCH wallet, the whole UI turns white. typing an integer first then decimal does not cause this issue.

when the white screen shows up, the only way to recover is to hit the view -> reload
![Screen Shot 2022-01-27 at 10 09 31 PM](https://user-images.githubusercontent.com/93196638/151489180-b1cf4ea7-6919-46a5-aa0e-fc72b4b76c47.png)

### Version

1.2.12 dev 197

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by seeden** [comment]
Fixed and pushed in the NEXT branch
